### PR TITLE
SearchKit - cleanup display configuration and add "rewrite" feature

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds the ability to rewrite fields in search displays, while streamlining the display administration screen.

Before
----------------------------------------
image

After
----------------------------------------
image

Comments
----------------------------------------
De-cluttering inspired by conversation with David Tarrant

### CODE REVIEW

**Comment by dptarrant** [comment]
I like the look - much cleaner :)    Using test site I do not see the Display on new line option. 
image

**Comment by colemanw** [comment]
> Using test site I do not see the Display on new line option.

My screenshot was from a List display and yours is from a Table. That's the difference.

**Comment by seamuslee001** [comment]
Jenkins retest this please

**Comment by colemanw** [comment]
retest this please

**Comment by dptarrant** [comment]
Not sure what to test.   Yes, the issue was as Coleman pointed out.  Is that what is meant by retest?

**Comment by colemanw** [comment]
@dptarrant no those are commands to civibot to re-run the automated tests.

**Comment by seamuslee001** [comment]
Merging based on @dptarrant comments and that this looks good to me r-code wise

**Comment by eileenmcnaughton** [comment]
@dptarrant thanks for testing / giving feedback. I agree this looks cleaner!

**Comment by JoeMurray** [comment]
Significant improvement. Thanks @dptarrant and @colemanw

**Pull request merged**
