### PR TITLE
CRM-20832 : Field  is_for_organisation in module_data set as 0 should…

### PR DESCRIPTION
**Pull request by jitendrapurohit**
… be inactive in uf_join table.

Details at https://issues.civicrm.org/jira/browse/CRM-20832.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This looks correct to me - once the rc is cut maybe fix up against the latest (if you do it before rc is cut there is more chance it won't get reviewed in time & you will need to refix)

**Comment by jitendrapurohit** [comment]
Rebased the changes to call on latest upgrade 4.7.26.

**Comment by yashodha** [comment]
@jitendrapurohit wanna rebase this?

**Comment by jitendrapurohit** [comment]
@yashodha moved the changes to 4.7.28 upgrade function.

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit this is stale - I'm going to close & let you re-open when you have rebased  / moved the function

**Pull request closed without merging**
