### PR TITLE
dev/core#3735 Fix for getlist retrieve with id

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fixes [dev/core#3735](https://lab.civicrm.org/dev/core/-/issues/3735) getlist retrieve with id

Before
----------------------------------------
@davejenx has to explain it while our brains fell apart

After
----------------------------------------
Fixed

Technical Details
----------------------------------------
Instead of two ajax requests, we now combine the results with php in a single request.

### CODE REVIEW

**Comment by yashodha** [comment]
@eileenmcnaughton the test is failing here.

**Comment by eileenmcnaughton** [comment]
@yashodha that is actually a good thing - but yes - I do need to add a fix

**Comment by colemanw** [comment]
@davejenx it looks like Eileen has completed the fix here. Can you please review?

**Comment by davejenx** [comment]
@eileenmcnaughton Sorry for the delay in reviewing. Looks good to me, thanks for fixing!

* General standards
    * Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
        * __PASS__ : The goal/problem/solution have been adequately explained with a link to the issue.
    * User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
        * __PASS__: The change would be intuitive or unnoticeable for a majority of users who work with this feature.
    * Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
        * __PASS__: The changes do not require documentation.
    * Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
        * __PASS__: Tested as described in linked issue.
* Developer standards
    * Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
        * __PASS__: The change preserves compatibility with existing callers/code/downstream.
    * Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
        * __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
    * Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
        * __PASS__: The change sufficiently improves test coverage, or the change is trivial enough that it does not require tests.
    * Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
        * __PASS__: The test results are all-clear.

**Comment by eileenmcnaughton** [comment]
Thanks @davejenx  - @colemanw can you merge based on ^^

**Pull request merged**
