### PR TITLE
Added setup pcp page wordpress shortcode

### PR DESCRIPTION
**Pull request by kartik1000**
Overview
----------------------------------------
This PR has added a shortcode option to setup a PCP similar to other shortcodes present in PCP like info and transact.

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@christianwach @kcristiano

**Comment by kcristiano** [comment]
Thanks @eileenmcnaughton I am looking at this and https://github.com/civicrm/civicrm-core/pull/20601

**Comment by kcristiano** [comment]
see comments on https://github.com/civicrm/civicrm-wordpress/pull/253

**Comment by kcristiano** [comment]
This is merge-ready.  WP PR https://github.com/civicrm/civicrm-wordpress/pull/253  has been merged.

**Comment by mattwire** [comment]
Merging per @kcristiano comment

**Pull request merged**
