### PR TITLE
Import fixes - regression + rename on upgrade

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
@demeritcowboy this is the 2 mentioned PRs in the same PR - seems they don't conflict 

https://github.com/civicrm/civicrm-core/pull/23329
https://github.com/civicrm/civicrm-core/pull/23288

Note there are some sample files attached to https://lab.civicrm.org/dev/core/-/issues/3414 for testing

I did get conflicts with https://github.com/civicrm/civicrm-core/pull/23292 

UPDATE - I fixed conflicts to pull in #23292 - which means the bulk can be r-run together & either merged together in full or some part/s can be merged

### CODE REVIEW

**Comment by demeritcowboy** [comment]
```
CRM_Contact_Import_Form_MapFieldTest::testSubmit with data set "save_mapping" (array('new mapping', 'save it', 1), array(array('do_not_import'), array('first_name'), array('last_name'), array('street_address', 2)), array(array('mapping', 1, array('new mapping')), array('mapping_field', 4, array(), array(array('do_not_import'), array('first_name'), array('last_name'), array('street_address', 2)))))
TypeError: CRM_Import_Parser::getUserJob(): Return value must be of type array, null returned

/home/jenkins/bknix-dfl/build/core-23333-1qoge/web/sites/all/modules/civicrm/CRM/Import/Parser.php:85
/home/jenkins/bknix-dfl/build/core-23333-1qoge/web/sites/all/modules/civicrm/CRM/Import/Parser.php:98
/home/jenkins/bknix-dfl/build/core-23333-1qoge/web/sites/all/modules/civicrm/CRM/Import/Parser.php:113
/home/jenkins/bknix-dfl/build/core-23333-1qoge/web/sites/all/modules/civicrm/CRM/Contact/Import/Parser/Contact.php:3560
/home/jenkins/bknix-dfl/build/core-23333-1qoge/web/sites/all/modules/civicrm/CRM/Contact/Import/Form/MapField.php:624
/home/jenkins/bknix-dfl/build/core-23333-1qoge/web/sites/all/modules/civicrm/CRM/Contact/Import/Form/MapField.php:600
/home/jenkins/bknix-dfl/build/core-23333-1qoge/web/sites/all/modules/civicrm/CRM/Contact/Import/Form/MapField.php:560
/home/jenkins/bknix-dfl/build/core-23333-1qoge/web/sites/all/modules/civicrm/tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php:65
```

**Comment by eileenmcnaughton** [comment]
thanks @demeritcowboy  - will fix now & rebase

**Comment by eileenmcnaughton** [comment]
That should pass now - I'll check in on the sub-pr

**Comment by eileenmcnaughton** [comment]
closing since https://github.com/civicrm/civicrm-core/pull/23288 merged in the mean time

**Pull request closed without merging**
