### PR TITLE
dev/events#56 Allow backend (de)registration changes for sold out price set items

### PR DESCRIPTION
**Pull request by larssandergreen**
Overview
----------------------------------------
Currently, when editing price set selections for an event registrant, you cannot add or remove sold out items. This PR makes it possible for backend users to add or remove price set selections that are sold out from registrations. It also ensures that all full selections show (Sold out) text, both on the Register Participant form and the Change Selections and Edit Event Registration forms.

Before
----------------------------------------
If a price set selection is sold out, back-end users can add this selection on Events - Register Event Participant, but if they edit a existing registration they cannot either add or subtract from sold out selections as these are disabled/frozen (except for removing select fields, which was possible). Back-end users may add registrants to sold out selections unintentionally, as there is no warning that selections are sold out on the Register Participant Form. Backend users cannot remove registrants from sold out selections, which should clearly be possible. They cannot override price set limits if required to add participants to sold out selections.

Additionally, "Sold out" was shown twice for text fields and sold out was not show on select options if the participant was currently registered for that selection.

Register Participant: Backend user can register participant for sold out selections and they are unmarked
image

Change Selections: Participant cannot be added or removed from sold out selections, doubled sold out on text field, no sold out on select
image

Public registration: Text field shows sold out twice.
image

After
----------------------------------------
Backend users can register and deregister participants for any price set selection. All price set selections that are sold out are now marked as sold out.

Sold out is only shown after the text field, which is consistent with all other price set fields. Sold out is shown on all relevant select options.

Register participant: Sold out selections are now marked
image

Change Selections: Participant can be added to or removed from all selections, sold out marked once on text field, sold out marked on select option.
image

Public Registration: Text field shows sold out once. Not other public facing change.
image

Comments
----------------------------------------
I've removed some now unneeded code that set form rules for selects.

To my eye, the use of bold, italics and regular text in price sets is a bit too much.
image
It is also inconsistent, as select options that are sold out are not show in italics. My suggestion would be to remove the italics and leave sold out options in regular text. This would be more readable and less of a mishmash.

### CODE REVIEW

**Comment by larssandergreen** [comment]
test this please

**Comment by larssandergreen** [comment]
test this please

**Comment by larssandergreen** [comment]
test this please

**Comment by demeritcowboy** [comment]
@larssandergreen If you click on Details and then on console output on the left in there you'll see:

```
Patch failed at 0002 allow backend (de)registration changes for sold out price set items  
  When you have resolved this problem, run "git am --continue".                             
  If you prefer to skip this patch, run "git am --skip" instead.                            
  To restore the original branch and stop patching, run "git am --abort".                   
  [[ STDERR ]]                                                                              
  error: patch failed: CRM/Event/Form/Registration/Register.php:761                         
  error: CRM/Event/Form/Registration/Register.php: patch does not apply                     
  hint: Use 'git am --show-current-patch' to see the failed patch      
```

i.e. it needs rebasing.

**Comment by larssandergreen** [comment]
Thanks @demeritcowboy

**Comment by larssandergreen** [comment]
jenkins, test this please

**Comment by larssandergreen** [comment]
Merge conflict fixed, ready for review!

**Comment by BettyDolfing** [comment]
Test this please

**Comment by jaapjansma** [comment]
@BettyDolfing and I have tried to review and test this PR. We receive a couple of errors and we weren´t able to test this properly because of those errors.

We setup a price set with four fields, checkbox, textfield, select and radio.  See below:

Screenshot_20220124_140818


We then tried to preview this price set and we saw the following:

Screenshot_20220124_140835

We also attached this price set to an event and the online public registration link gives the following two errors:

Screenshot_20220124_140700

Screenshot_20220124_140715

@larssandergreen are you able to look at this and fix them?

**Pull request closed without merging**
