### PR TITLE
[needs work] Dashboard fixes

### PR DESCRIPTION
**Pull request by julialongtin**
Requires my reentrant invoke() changes. no longer uses seperate http(s) connections to pull in dashlets, and properly displays the dashboard configuration widget.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Is there a ticket for this? It seems to tie in with https://issues.civicrm.org/jira/browse/CRM-17663 although I'm not sure you are aware of that issue (there is a long discussion in the odt attached). I'll test this out - but worth logging a ticket whenever you work on something as a rule

**Comment by colemanw** [comment]
To save you a lot of reading... bottom line from that transcript is that we want to ditch the server calling itself and just load dashlets directly via ajax.

**Comment by eileenmcnaughton** [comment]
Coleman - right - but I'm not opposed to this patch if it works - it wasn't our final vote but it was one of the methods we discussed. I'm going to give it a whirl

**Comment by julialongtin** [comment]
Please keep in mind that the reenterant invoke requires instantiation, so requires the drupal-civicrm (or equivalent) that you're using to have a change similar to https://github.com/julialongtin/civicrm-drupal/commit/a0278babdf68cbe1ecb12d56516a5d403fe33f14

**Comment by eileenmcnaughton** [comment]
I just tried this & the setPrint and setReset functions don't yet exist - so I guess this isn't complete.

As an aside it would be good to pull our the no-brainer part of this & get it merged to simplify the commits. All of this stuff 

-    $contactID = CRM_Core_Session::singleton()->get('userID');
 +    $contactID = CRM_Core_Session::singleton()->getLoggedInContactID();

Is an absolute unmitigated YES

as are the comment fixes & spelling fixes

**Comment by eileenmcnaughton** [comment]
NB - I altered the title to [needs work] please change that to [ready for review] when you want it re-reviewed.

(Currently I am getting a 500 error on it due to those 2 functions mentioned being invalid)

**Comment by eileenmcnaughton** [comment]
NB - just to restate this simply for future readers - our agreed preferred approach to this is 

-  we want to ditch the server calling itself and just load dashlets directly via ajax, finding a way to tell the browser to cache the results appropriately

This approach changes the way the server calls itself - rather than passing it off to the browser. It is an  improvement over the existing approach so provided we can get it to work we are happy to make this change - but keep in mind the preferred approach if the path on this approach gets too rocky.

**Comment by eileenmcnaughton** [comment]
I'm going to close this out cos it's a bit stalled at the moment & is not fully working. Please feel free to re-open if the 500 errors are fixed. But also note closing this PR does not mean the issue is not being worked on. Please check the ticket https://issues.civicrm.org/jira/browse/CRM-17663

**Pull request closed without merging**
