### PR TITLE
jshint fixes

### PR DESCRIPTION
**Pull request by totten**

### CODE REVIEW

**Comment by totten** [comment]
@colemanw @kurund - Any ideas on these last two errors? It does seem like `init()` is defined twice, although it's so long I can't really tell... not clear which `init()` is actually used when...

**Comment by colemanw** [comment]
I think style checking kicked in when I moved this file from /packages to /js

As far as I can tell the history of that file is that we lifted it from a drupal module and dropped it into packages, where it has languished ever since. Any upstream improvements have passed it by, and at this point the civicrm dashboard is so "legacy" that IMO it's a much better candidate for a big swap than a big polish.

IMHO just put a `/* jshint ignore:start */` comment at the beginning of the file and be done with it.

**Comment by totten** [comment]
Agree it's "legacy".

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by colemanw** [comment]
retest this please

**Comment by eileenmcnaughton** [comment]
It says merge on pass.....

**Pull request merged**
