### PR TITLE
[Smarty variables] Consistently assign isAdmin at php layer

### PR DESCRIPTION
**Pull request by eileenmcnaughton**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I can't see why it is a fail - https://test.civicrm.org/job/CiviCRM-Core-PR/45658/consoleFull test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Comment by colemanw** [comment]
Yea, conditionally assigning a boolean only if true is a dumb pattern.

**Pull request merged**
