### PR TITLE
dev/core#389 [preliminary cleanup+ test] Standardise metadat for custom field

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Make metadata for custom fields more consistent, add test

Before
----------------------------------------
Less consistent

After
----------------------------------------
More consistent

Technical Details
----------------------------------------
In digging into dev/core#389 I found a major complexity in fixing it was inconsistent metadata available at different
points in the code. This simply adds metadata to the 'inner-most place' & makes the BAO_CustomQuery object use that

I didn't remove the options loop because I wanted to leave that out of scope as I can't see how / if it is used

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
Test fail relates @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
hopefully this time

**Comment by eileenmcnaughton** [comment]
@seamuslee001 ok it passed this time

**Comment by seamuslee001** [comment]
Changes make sense here standardising output and has good test coverage merging

**Pull request merged**
