### PR TITLE
Slay dragons

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Slay dragons

Before
----------------------------------------
’Twas brillig, and the slithy toves 
      Did gyre and gimble in the wabe: 
All mimsy were the borogoves, 
      And the mome raths outgrabe. 

“Beware the Jabberwock, my son! 
      The jaws that bite, the claws that catch! 
Beware the Jubjub bird, and shun 
      The frumious Bandersnatch!” 

He took his vorpal sword in hand; 
      Long time the manxome foe he sought— 
So rested he by the Tumtum tree 
      And stood awhile in thought. 

And, as in uffish thought he stood, 
      The Jabberwock, with eyes of flame, 
Came whiffling through the tulgey wood, 
      And burbled as it came! 

One, two! One, two! And through and through 
      The vorpal blade went snicker-snack! 
He left it dead, and with its head 
      He went galumphing back. 

“And hast thou slain the Jabberwock? 
      Come to my arms, my beamish boy! 
O frabjous day! Callooh! Callay!” 
      He chortled in his joy. 

’Twas brillig, and the slithy toves 
      Did gyre and gimble in the wabe: 
All mimsy were the borogoves, 
      And the mome raths outgrabe.

After
----------------------------------------
Silence of the monsters

Technical Details
----------------------------------------
The removed code path was deprecated a long long time ago. 
I can still remember how
That code comment used to make me smile
And I knew if I had my chance
That I could make those people read my code comments & use ruddy metadata
And maybe I'd be happy for a while

Comments
----------------------------------------
Time to drive my Chevy to the levee to see if the levee is dry

### CODE REVIEW

**Comment by colemanw** [comment]
Reviewer's note:
--------

I can't remember if I laughed, when I
read about the tests that passed.
But something touched me deep inside
The day, the dragons died.

_So bye, bye Mr. Dragon surprise..._
You were scary
Made us wary
But we couldn't surmise,
Why good ol' code
Was potentially unwise
Singin' `$iAmAnIntentionalENoticeThatWarnsOfAProblemYouShouldReport` dies.
`$iAmAnIntentionalENoticeThatWarnsOfAProblemYouShouldReportUsingOldFormat` dies.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by mattwire** [comment]
Good to
images

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
Bye bye oh dragon of mine 
Drove my test suite to the edge and over the line
And them good ole sprinters were drinking to your demise
Singin' this'll be the day that you die
This'll be the day that you die

**Comment by eileenmcnaughton** [comment]
Did you write the book of tests
And do you have faith in Jenkins above

**Comment by eileenmcnaughton** [comment]
@colemanw given I've already eulogised the dragon can you finish them off?

**Pull request merged**
