### PR TITLE
CRM-20388 - ensure connection errors are properly reported to user.

### PR DESCRIPTION
**Pull request by jmcclelland**
* [CRM-20388: payflo pro payment processor codes rejected payments as completed](https://issues.civicrm.org/jira/browse/CRM-20388)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@jmcclelland i am guessing it would be difficult to mock up a unit test to trigger the errors

**Comment by eileenmcnaughton** [comment]
Really we should throw PaymentProcessorExceptions rather than adding more instances of 'processor specific error handling'. The doPayment method will interpret those & throw 'on behalf' - but eventually we want to take that out of there & have the processors 'throw their own'

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I would have preferred some changes around the exceptions but ok - let's merge this one

**Pull request merged**
