### PR TITLE
Export relationship custom field CRM-18354

### PR DESCRIPTION
**Pull request by sunilpawar**
- [CRM-18354: Export relationship custom field](https://issues.civicrm.org/jira/browse/CRM-18354)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
PR against master is https://github.com/civicrm/civicrm-core/pull/8076 (not yet merged)

**Comment by eileenmcnaughton** [comment]
NB - we normally wait until 4.7 PRs are merged before merging 4.6 ones so it's worth linking them

**Comment by seamuslee001** [comment]
Can't verify the problem described in the Issue

**Comment by josephlacey** [comment]
@seamuslee001 @totten We closed the 4.7 patch for this because it couldn't be reproduced.  I suspect we can close this 4.6 one too.

**Comment by eileenmcnaughton** [comment]
OK - if this is closed against 4.7 I'll close this. Go ahead & re-open once the issues that caused it to be closed against 4.7 are resolved. Closing this means it's a bit easier for reviewers to see what they should focus on & I'm pretty sure you get better visibility when you re-open in compared to just updating it.

**Pull request closed without merging**
