### PR TITLE
CRM-19989 - Constituent Detail Report gives only one result for multi…

### PR DESCRIPTION
**Pull request by yashodha**
…-value custom data

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Just a quick note that this should not be merged for 4.6 until it is confirmed to be fixed in master/4.7

**Comment by yashodha** [comment]
@eileenmcnaughton This fix is already there in 4.7 and works fine in master.

**Comment by eileenmcnaughton** [comment]
Great - will leave to @jackrabbithanna / @guanhuan to decide about merging then

**Comment by guanhuan** [comment]
Fix looks good. Please merge @jackrabbithanna

(still need to get merge permission from Tim)

**Pull request merged**
