### PR TITLE
CRM-19702: Fatal error when merging contact records with custom file fields

### PR DESCRIPTION
**Pull request by monishdeb**
* [CRM-19702: Fatal error when merging contact records with custom file fields](https://issues.civicrm.org/jira/browse/CRM-19702)

### CODE REVIEW

**Comment by colemanw** [comment]
@monishdeb something is wrong with your branch in this PR.

**Comment by colemanw** [comment]
@monishdeb can you please rebase this?

**Comment by monishdeb** [comment]
@colemanw done :)

**Comment by colemanw** [comment]
Thanks.

**Pull request merged**
