### PR TITLE
CRM-19623, code cleanup for report filters and fields, fixed report f…

### PR DESCRIPTION
**Pull request by pradpnayak**
…ilter type

----------------------------------------
* CRM-19623: is not of the type Int when report is filtered with postal code
  https://issues.civicrm.org/jira/browse/CRM-19623

### CODE REVIEW

**Comment by yashodha** [comment]
@pradpnayak : wanna add some test coverage for the same?

**Comment by pradpnayak** [comment]
@yashodha i have added test. Can you please review?

**Comment by eileenmcnaughton** [comment]
I'll try to include it in the review week schedule

**Review by jitendrapurohit — APPROVED** [review]
I've tested this by filtering on `address_options` on several reports(Contact, Activity, etc). Seems to work fine.

**Pull request merged**
