### PR TITLE
CRM-9474 - Simplify contribution page tab titles

### PR DESCRIPTION
**Pull request by colemanw**
https://issues.civicrm.org/jira/browse/CRM-9474

### CODE REVIEW

**Comment by davecivicrm** [comment]
Coleman - this makes sense, but I was wondering if it would break some web tests (due to title change). I'll run a few while the PR test is in progress.

**Comment by colemanw** [comment]
I did a little grepping in the test classes and didn't see anything.

**Comment by davecivicrm** [comment]
Ran WebTest_Contribute_ContributionPageAddTest w/o errors :-)

**Comment by davecivicrm** [comment]
Test failures are unrelated.

**Pull request merged**
