### PR TITLE
WIP: CRM-19828: Fixed problematic "incompleteDateTime" validator for crmUiDatepicker directive.

### PR DESCRIPTION
**Pull request by universalhandle**
* [CRM-19828: incompleteDateTime validator for crmUiDatepicker directive is broken](https://issues.civicrm.org/jira/browse/CRM-19828)

### CODE REVIEW

**Comment by colemanw** [comment]
@GinkgoFJG looks like this test still isn't passing.

**Comment by GinkgoFJG** [comment]
@colemanw: Hmm, never got notified (or didn't see the notice) that it failed. I suspect it is the test that needs fixing because based on the output from Jenkins, this is precisely the problem that the pull request fixes.

Unfortunately, I'm going to need you to show me the PhantomJS ropes. I haven't spent any time unit testing JS. Where do I start?

**Comment by colemanw** [comment]
@GinkgoFJG from within the /civicrm directory, just type 

    npm test

**Comment by GinkgoFJG** [comment]
This test is failing against master, too. I wonder why other PRs aren't getting flagged...

```bash
git checkout origin/master
npm test
```

Output is:

> PhantomJS 1.9.8 (Linux) crmMailingRadioDate crmMailingRadioDate directive should update the UI after changing the model FAILED
	Expected 'Tue Jan 23 2018' to equal 'Mon Jan 22 2018'.
	    at /usr/local/lib/civicrm-buildkit/build/d47/sites/all/modules/civicrm/tests/karma/unit/crmMailingRadioDateSpec.js:123

The cause of the problem is a locale issue. Note the following:

* `datenow` (line 107 of the test) is a string with no notion of timezone.
* In my timezone, running `console.log(new Date('2018-01-23'));` in my browser console returns
    > Mon Jan 22 2018 19:00:00 GMT-0500 (EST)

    This makes sense. At midnight on 1/23, it is still 1/22 on the East Coast of the United States.

When we set the model programmatically, the datepicker widget interprets the passed string in the current timezone (EST in my case), which is also how it delivers its output (Tue Jan 23 2018). On the other hand, the YYYY-MM-DD-formatted string passed to the `Date` constructor on line 110 is treated as GMT, and the time is assumed to be midnight. When the dates are compared, the `dateToString` method converts the latter to EST, causing the day to be decremented by one. The same test could pass or fail depending on where in the world you are when you run it.

It should be noted that the problem could not easily be solved by adding a timezone on line 110 because of [known](https://github.com/ariya/phantomjs/issues/11712) timezone-related date-parsing [issues](https://github.com/ariya/phantomjs/issues/11151) with phantomJS. It should also be noted that upgrading from v1.9.8 to v2.x addresses at least some of these issues.

**Comment by eileenmcnaughton** [comment]
@GinkgoFJG I think we should close this & keep the link to it in JIRA since it is pretty stalled & has been for a while?

**Comment by GinkgoFJG** [comment]
Planning on working on this at the sprint!

**Comment by eileenmcnaughton** [comment]
I'll hold you to that!

**Comment by eileenmcnaughton** [comment]
@GinkgoFJG I'm going to close this & let you re-open when appropriate. It's pretty old

**Pull request closed without merging**
