### PR TITLE
CRM-15656 - Synchronize PHP and MySQL Time Zones   

### PR DESCRIPTION
**Pull request by spalmstr**
Patch Base.php and Joomla.php to synchronize the PHP and MySQL time zones

---
- [CRM-15656: Synchronize PHP and MySQL time zones](https://issues.civicrm.org/jira/browse/CRM-15656)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Hey - can you rebase this to get a clean patch with no conflict.

What I normally do is

git fetch -f origin 
(to make sure the local copy is really up to date)
git rebase origin/master

& then once I've done that I do another round with the -i switch & tidy up the patches a bit more - in particular you can squash them together if they are a fix to a fix ie

git rebase -i origin/master

**Comment by eileenmcnaughton** [comment]
I think the key part of the change is this function needs to be added to the Joomla! system class.

 +/**
+   * Get the time zone from Joomla
+   */
+  public function getTimeZoneString() {
+      $config = JFactory::getConfig();
+      $user = JFactory::getUser();
+      $timezone = $user->getParam('timezone');
+      //$phpTimezone = ini_get('date.timezone');
+      if(!$timezone)
+      {
+          // Get the timezone configured in Joomla
+          $timezone = $config->get('offset');
+      }
+      if (!$timezone)
+      {
+          // Get the time in PHP.
+          $timezone = ini_get('date.timezone');
+      }
+
+    return $timezone; 
+}

**Comment by spalmstr** [comment]
Hi,

 

Thanks – do you do this to an empty folder?  It seemed to screw up my local Git repository.

**Comment by spalmstr** [comment]
Thanks for this – you are right.  

 

"D:\CiviCRM_Custom.git\joomla\administrator\components\com_civicrm\civicrm\CRM\Utils\System\Base.php" needs:

 

@@ -705,7 +705,7 @@

       $timeZoneOffset = sprintf("%02d:%02d", $tz / 3600, abs(($tz / 60) % 60));

-      if ($timeZoneOffset > 0) {

+      if ($tz >= 0) {  // $tz is a number, not a string, so it is better to test it.  00:00 needs a plus sigh.

         $timeZoneOffset = '+' . $timeZoneOffset;

       }

       return $timeZoneOffset;From: Eileen McNaughton [mailto:notifications@github.com] 

 

"D:\CiviCRM_Custom.git\joomla\administrator\components\com_civicrm\civicrm.php" need:

 

@@ -64,6 +64,8 @@

   require_once 'PEAR.php';

   $config = CRM_Core_Config::singleton();

+  // Set the time zone

+  CRM_Core_Config::singleton()->userSystem->setMySQLTimeZone();

}

 function plugin_init() {

 

and

 

"D:\CiviCRM_Custom.git\joomla\components\com_civicrm\civicrm.php" needs:

 

@@ -36,6 +36,9 @@

   require_once 'PEAR.php';

   $config = CRM_Core_Config::singleton();

+   // Set the time zone

+  CRM_Core_Config::singleton()->userSystem->setMySQLTimeZone();

+

   // this is the front end, so let others know

   $config->userFrameworkFrontend = 1;

}

 

I hope this helps:

 

Kind regards,

 

Stephen Palmstrom
Sent: 16 May 2016 09:55
To: civicrm/civicrm-core <civicrm-core@noreply.github.com>
Cc: Stephen Palmstrom <stephen.palmstrom@outlook.com>; Author <author@noreply.github.com>
Subject: Re: [civicrm/civicrm-core] CRM-15656 - Synchronize PHP and MySQL Time Zones (#8371)

 

I think the key part of the change is this function needs to be added to the Joomla! system class.

+/**

*	* Get the time zone from Joomla
*	*/
*	public function getTimeZoneString() {
*	$config = JFactory::getConfig();
*	$user = JFactory::getUser();
*	$timezone = $user->getParam('timezone');
*	//$phpTimezone = ini_get('date.timezone');
*	if(!$timezone)
*	{
*	// Get the timezone configured in Joomla
*	$timezone = $config->get('offset');
*	}
*	if (!$timezone)
*	{
*	// Get the time in PHP.
*	$timezone = ini_get('date.timezone');
*	} +
*	return $timezone; +}

**Pull request closed without merging**
