### PR TITLE
dev/core#4969 Simplify AngularManager loading/caching system

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
2 cleanups to the AngularManager loading/caching system.
Hopefully one of them fixes https://lab.civicrm.org/dev/core/-/issues/4969

Before
----------------------------------------
- `basePages` not guaranteed to be an array.
- AngularModules split into multiple caches which (for unknown reasons) may be getting out-of-sync on some sites.

After
----------------------------------------
- `basePages` guaranteed to be an array.
- All AngularModules stored in same cache.

Technical Details
----------------------------------------
This code is simpler and better regardless of [dev/core#4969](https://lab.civicrm.org/dev/core/-/issues/4969) but I really hope it fixes that too!

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw this is a regression so 5.70?

**Comment by JKingsnorth** [comment]
In terms of QA - the theory looks sound to me (it would be impossible for the raised bug to materialize), and it is running OK in production. Generally the code is tidier as a result of this too.

**Comment by totten** [comment]
I agree the theory sounds reasonable. Merging based on @JKingsnorth's review.

> Multiple caches which (for unknown reasons) may be getting out-of-sync on some sites.

Yeah, in the Gitlab discussion, John K mentions using Memcache, and Jon G mentions using Redis. And it sounds like it happens more for John/Memcache. This accords with my anecdotal understanding: 

* With SQL backend, space limits are almost never issue, and it lacks the means to evict based on space/usage. It only evicts based on TTL.
* With Memcache, it is quite concerned with space limits, and it is quite happy to evict. And the limits are low enough that it matters.
* Redis is sort of in between. It generally has more storage options/space and doesn't evict as much (*but it can do*).

For a cache that's split into multiple items, you usually have same TTL on all parts. (That's all that matters for typical SQL backend.) But for other backends, you need to remember that any record can be evicted at any time. This is why (eg) [any cache-miss on any part of class-index will trigger full `buildIndex()`](https://github.com/civicrm/civicrm-core/blob/889687ab2230822dc5aeb3ea551466e5e15d0cf0/Civi/Core/ClassScanner.php#L61-L76). I think there may be some accommodations in "PrevNext" as well, but that one is hazier in my memory.

**Comment by colemanw** [comment]
Good to know about the unpredictable cache purges. I'll keep that in mind.

**Pull request merged**
