### PR TITLE
(dev/core#1615) Remove the very old CiviCRM installer

### PR DESCRIPTION
**Pull request by mlutfy**
Overview
----------------------------------------

It has been replaced by \Civi\Setup a long time ago, but the drush integration was still using it.

This might make some tests fail?

### CODE REVIEW

**Comment by totten** [comment]
Wow, this'll be great.

Pre-depends: https://github.com/civicrm/civicrm-drupal/pull/679

@mlutfy Looks like `CRM/Core/CodeGen/I18n.php` would re-generate `install/langs.php`. So maybe we can drop that line too?

**Comment by demeritcowboy** [comment]
I'm not sure what the extended tests are telling us but the last time I tried using this installer it couldn't even get going because recent versions of mariadb don't like [this line](https://github.com/civicrm/civicrm-core/blob/ecac570261fe1ed7482aaa63db36ba231851b516/install/index.php#L1042).

So +1

**Comment by mlutfy** [comment]
Test fails include:

- `api\v4\Afform\AfformRoutingTest.testChangingPath`
-  `E2E\Core\LocalizedDataTest.testLocalizedData`

The upgrade suite seems to fail on:

```
++ civi-test-run -b build-1 -j /home/homer/workspace/CiviCRM-Test-QLow/build/junit --exclude-group ornery upgrade
(Clock simulation) Tests will use inherited option TIME_FUNC=linear:500
ls: cannot access '/home/homer/buildkit/build/build-1/web/core//tests/phpunit/Upgrade/*.php': No such file or directory
```

I'm not very familiar with those tests, but they all seem unrelated?

**Comment by demeritcowboy** [comment]
The testChangingPath one is a known fail: https://lab.civicrm.org/dev/drupal/-/issues/197
The testLocalizedData one I thought was fixed at https://lab.civicrm.org/dev/translation/-/issues/84 but maybe the node that is running on needs some kind of update?

**Comment by demeritcowboy** [comment]
I think this is mergeable just there's the earlier note about langs.php, but that doesn't have to be in here.

**Comment by totten** [comment]
civibot, test this please

**Comment by totten** [comment]
(*Note: The HEAD commit predates the current test-jobs, so Github shows a mix of old+new jobs. The important results will be `CiviCRM-PR`, `run-distmaker`, `run-extended-tests`.*)

**Comment by colemanw** [comment]
`run-extended-tests` fails appear to be unrelated or preexisting?

**Comment by totten** [comment]
Agree @colemanw - all pre-existing.

`r-run`: I took the tar/zip files for Backdrop, Joomla, Drupal 7, WordPress -- and did a GUI-based installation. As expected, they all ran cleanly.

**Comment by colemanw** [comment]
Yay!

**Pull request merged**
