### PR TITLE
[REF] extract chunk of code to a separate function

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
code readability improvement

Before
----------------------------------------
code less readable

After
----------------------------------------
code more readable

Technical Details
----------------------------------------
Straight extraction

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton this just needs a space before the= sign.

**Comment by eileenmcnaughton** [comment]
dang/ fixed

**Comment by colemanw** [comment]
@eileenmcnaughton this looks like an improvement, but I think the extraction could be a little cleaner, in particular:

- Parm `$errors` is only used within the function so does not need to be passed as a param.
- Ditto for param `$ctype` which is defined outside the function but never used outside the function, and is based on a variable available to the function.

**Comment by eileenmcnaughton** [comment]
@colemanw good points - although I think you meant exceptions param not errors above

**Comment by eileenmcnaughton** [comment]
fixed per feedback

**Pull request merged**
