### PR TITLE
CIVICRM-836: PR 11580 backported which fixes logging not be able to be enabled on Maria10.2

### PR DESCRIPTION
**Pull request by agilewarealok**
Overview
----------------------------------------
This is duplicate of #11580 for CiviCRM 4.6, PR for 4.7 is already merged.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
there are a bunch of style issues blocking this - but it might not be worth fixing - you should check if @jackrabbithanna is prepared to review it before putting in more time

**Comment by jackrabbithanna** [comment]
@agilewarealok I think this can make it into the LTS. If you fix the style issues it can get into the next LTS release.

**Comment by agilewarealok** [comment]
@jackrabbithanna We've fixed the styling issues.

**Comment by jackrabbithanna** [comment]
Jenkins please re-test this

**Comment by jackrabbithanna** [comment]
I can see that in fixTimeStampAndNotNullSQL() we are adding string replacements, not removing any that were there already, so what was working, should continue to work. Don't see any reason not to merge this. 

Merging #11977

**Pull request merged**
