### PR TITLE
Try running unit tests on phpunit6

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Nice - what about running phpunit 7 for 7.1 + (& maybe 8 for php 7.2+) - we need min phpunit 7 for 7.3 & ideally we would run the most recent version of phpunit that we can to keep our ability to support the latest from regressing

**Comment by seamuslee001** [comment]
@eileenmcnaughton this needs @totten to deploy latest buildkit on test-2 first but yeh but PHPUnit7 is throwing more errors (plus more code changes). I need to review in depth first

**Comment by eileenmcnaughton** [comment]
@seamuslee001 so do you have any reservations about me merging this?

**Comment by eileenmcnaughton** [comment]
I guess it will require some people to update their buildkit?

**Comment by seamuslee001** [comment]
Yeh pretty much that but i don't have a reservation as such just that we may see failures if something runs on max on test-2 without Tim deploying latest buildkit

**Comment by eileenmcnaughton** [comment]
let's see how it goes

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I wonder if any docs need updating now?

**Pull request merged**
