### PR TITLE
dev/drupal#77 Create .htaccess

### PR DESCRIPTION
**Pull request by jamie-tillman**
This is needed to allow access to these files when using Drupal/Apache.  Otherwise, you get access denied.

Relevant GitLab issue is https://lab.civicrm.org/dev/drupal/issues/77

Overview
----------------------------------------
Correcting inability to use URLs in mailing due to Drupal/Apache2 incompatible configuration

Before
----------------------------------------
You can't use URLs in a mailing unless you manually fix this problem.  There appears to be no documentation referring to this problem, but the relevant gitlab issue refers to it.  This has been a problem for many months.

After
----------------------------------------
Added the .htaccess file where needed

Comments
----------------------------------------
This is my first core pull request.  Apologies if I've not followed protocol.

### CODE REVIEW

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by mlutfy** [comment]
@jamie-tillman Welcome to CiviCRM, and thank you for the pull-request!

**Comment by MegaphoneJon** [comment]
Jenkins test this please

**Comment by mlutfy** [comment]
Closing this PR based on Tim's comment on dev/drupal#77

> I just want to echo Jaap's link above (core#1100 and cloud-native#16) - there's a lot of interest in making extern unnecessary by handling more of the extern use-cases through the normal routes. We can't just turn-off extern for existing sites (D7, etc), but I think it makes sense as the default setup for newer builds.

So I think Drupal8 integration will have to implement the altern-extern hook, as WP does.

**Comment by jamie-tillman** [comment]
Can you provide a link to "Tim's comment on dev/drupal#77" that was mentioned?  I don't know how to find that.

**Comment by jamie-tillman** [comment]
While your conclusion about implementing the altern-extern hook makes sense, I see no reason why that precludes this patch.  Perhaps I'm missing something in my inexperience, but it seems silly to allow some future development plan to stop Civi from being slightly more compatible with Drupal 8 via the inclusion of a simple configuration file.

**Pull request closed without merging**
