### PR TITLE
Towards deprecating contributionType in favour of financialType

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Make sure financialType is availabel (& preferred). This commit does not attempt to
change any existing templates

### CODE REVIEW

**Comment by kurund** [comment]
@eileenmcnaughton we also need to handle upgrade for message templates.

**Comment by eileenmcnaughton** [comment]
Yeah - at some point that should happen - I wasn't trying to fully remove contributionType - just take another step towards it - at least for new installs & people wanting to customise.

**Comment by kurund** [comment]
Ok, we should fix it before merging this PR.

**Comment by eileenmcnaughton** [comment]
@kurund I figured it would work it's way through when other people do updates as they copy the master version. 

I spotted an opportunity to deprecate a few more places where the contributionType is used & there didn't seem to be a downside to making this change. But, I don't want to grow the scope of this change - so please close the PR & I'll delete the branch if it's not mergeable

**Comment by kurund** [comment]
@eileenmcnaughton my only concern was that when we drop legacy support, upgraded instances won't show financial types as it will be still using the old variable "$contributionTypeName" instead fo new one. Hence, I was recommending handling this in the upgrade. I do agree with the cleanup in this PR.

**Comment by eileenmcnaughton** [comment]
Yeah - I agree it needs to be done at some point. I'm not extending this PR to cover that upgrade - so if you think it will cause more problems than it solve to merge this I'll close it & we can punt it down the track

**Comment by kurund** [comment]
@eileenmcnaughton I am merging this PR and will add the upgrade as a separate PR.

**Comment by eileenmcnaughton** [comment]
Thanks

**Pull request merged**
