### PR TITLE
[NFC] Preferences form template cleanup

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Moves code around to a more logical place.

Before
----------------------------------------
When the invoicing code was added it was added to the preferences template...badly. Instead of adding code related to invoicing to the relevant preferences template  it was added to a shared template, wrapped in 'ifs'. 

After
----------------------------------------
Code specific to only one preference form moved back to it's own template & shared code simplified.

Technical Details
----------------------------------------
Just moves code around - no change. Note each commit is  a distinct small step in this process

Comments
----------------------------------------
There are still a couple of things to fix on the php side on this form - but this neither creates or fixes those issues.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire almost there for the cleanup round - ping

**Comment by pradpnayak** [comment]
Hi @mattwire 

How about below code to hide/show invoice blcok

```
{literal}
  <script type="text/javascript">
    CRM.$(function($) {
      hideShowInvoiceBlocks();
      $("#invoicing_invoicing").click(hideShowInvoiceBlocks);

      function hideShowInvoiceBlocks() {
        if ($("#invoicing_invoicing").prop('checked')) {
          $("#invoicing_blocks").show();
        }
        else {
          $("#invoicing_blocks").hide();
        }
      }
    });
  </script>
{/literal}
```

**Comment by mattwire** [comment]
@pradpnayak Yes, much better and cleaner.  I've just tested your version and it works perfectly.

**Comment by pradpnayak** [comment]
@JoeMurray / @Edzelopez / @monishdeb  

You might need to update your extension code like EasyBatch, Edit Line Item,  Close Accounting Period etc which add's some settings using jQuery and CiviCRM hooks.

Thanks
Pradeep

**Comment by eileenmcnaughton** [comment]
@mattwire @pradpnayak can we merge this & then @pradpnayak's version as a follow up? There is one more PR based on this https://github.com/civicrm/civicrm-core/pull/13047 which isolates that form

**Comment by eileenmcnaughton** [comment]
also @pradpnayak you may not have seen this https://lab.civicrm.org/dev/core/issues/495 - if I can get the last fix-ups merged I'll work on that & it will give better options for extensions

**Comment by eileenmcnaughton** [comment]
@mattwire I think with #13047 merged the jquery works again - this neither breaks or fixes it

**Comment by eileenmcnaughton** [comment]
(but agree @pradpnayak's is an improvement)

**Comment by mattwire** [comment]
@eileenmcnaughton Ok, I see it is currently broken in master too.  In which case let's merge this and resolve see if the jquery is fixed by #13047 (but still be good to update to use @pradpnayak changes afterwards).

**Comment by eileenmcnaughton** [comment]
@mattwire thanks - merging - once https://github.com/civicrm/civicrm-core/pull/13047 is merged we need to do a good audit!

**Comment by eileenmcnaughton** [comment]
& yes agree re @pradpnayak improvement - also, I don't understand WHY the id changed - but at the moment I think merge #13047 & then look at that

**Comment by pradpnayak** [comment]
Hi @eileenmcnaughton 

I just tested on my local machine on current state of code. It appears that labels for field is printed twice. Is this something fixed in your other PR?

screen shot 2018-11-01 at 16 35 01

**Comment by eileenmcnaughton** [comment]
@pradpnayak let's hope so :-)

**Comment by pradpnayak** [comment]
@eileenmcnaughton I am going to test https://github.com/civicrm/civicrm-core/pull/13047 now

**Comment by eileenmcnaughton** [comment]
thanks @pradpnayak

**Pull request merged**
