### PR TITLE
Prevent viewport jump when toggling help on "Administer CiviCRM" screen

### PR DESCRIPTION
**Pull request by christianwach**
Overview
----------------------------------------
Prevents the page jumping to the anchor when clicking the discovery tab on an item on the "Administer CiviCRM" screen. Fixes https://lab.civicrm.org/dev/core/issues/557

Before
----------------------------------------
The page jumps to the anchor when clicking a discovery tab.

After
----------------------------------------
Prevents the page jumping to the anchor when clicking a discovery tab.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw can you take a look at this - pretty trivial

**Comment by colemanw** [comment]
@christianwach out of curiosity, why are you guarding against `event.preventDefault` not existing? I've never seen that pattern before. Is it an IE6 thing or something?

**Comment by christianwach** [comment]
> Is it an IE6 thing or something?

Yes, it's an IE thing - can't remember which versions it affects, but it could well be an older version. I just use that code out of habit. I can remove the check if you think it's redundant.

**Comment by colemanw** [comment]
One reason I might not have ever seen it is that Civi js mostly uses jQuery whereas here you are handling a raw DOM event. So I think jQuery irons out some of those cross-browser issues for us. Since we're outside that context I think it's fine to leave it in.

**Pull request merged**
