### PR TITLE
Allow psr/log 3

### PR DESCRIPTION
**Pull request by athos-ribeiro**
Allow usage with psr/log 3

### CODE REVIEW

**Comment by demeritcowboy** [comment]
I'm going to need 2.0 for drupal 10 at some point - just curious what requires 3.0?

**Comment by athos-ribeiro** [comment]
> I'm going to need 2.0 for drupal 10 at some point - just curious what requires 3.0?

Thanks for looking into this!

The recently released Ubuntu 22.04 only ships psr/log 3.0, so this is required there for the deb package builds.

**Comment by eileenmcnaughton** [comment]
add to whitelist

**Comment by totten** [comment]
FWIW, the changes in `psr/log` appear to be:

* 2.0.0: https://github.com/php-fig/log/compare/1.1.4...2.0.0?expand=1
* 3.0.0: https://github.com/php-fig/log/compare/2.0.0...3.0.0?expand=1

**Comment by totten** [comment]
Thoughts on the signature changes:

* __Good__: For the most part, they're adding type-hints for the existing signatures. This affects interface-implementers rather than interface-consumers. `civicrm-core` doesn't directly implement `LoggerInterface`. It goes through `AbstractLogger`. So it's somewhat buffered from those changes.

    ```
    $ grep -r 'extend.*Logger' Civi CRM/ ext api/ tests/
    Civi/Api4/Action/System/RotateKey.php:    $logger = new class() extends \Psr\Log\AbstractLogger {
    CRM/Core/Error/Log.php:class CRM_Core_Error_Log extends \Psr\Log\AbstractLogger {
    CRM/Utils/EchoLogger.php:class CRM_Utils_EchoLogger extends Psr\Log\AbstractLogger implements \Psr\Log\LoggerInterface {
    CRM/Utils/SystemLogger.php:class CRM_Utils_SystemLogger extends Psr\Log\AbstractLogger implements \Psr\Log\LoggerInterface {
    ```

* __Unsure__: This may affect compatibility for the optional `monolog` integration. If @eileenmcnaughton and @demeritcowboy are OK with that, then that's cool.

* __Problem__: Within `AbstractLogger` (aka `LoggerTrait`), there is an abstract method `log()` whose signature has changed in each version.

    You may be able to fix the affected methods (`CRM_Utils_System_Logger::log()`, etc). I played around [in a gist to simulate the different contracts](https://gist.github.com/totten/f9c3681ea6d3cb080ede21dbf6561cbb), and this formulation seemed compatible with v1+v2+v3:

    ```php
     public function log($level, $message, array $context = array()): void {
       ...
     }
    ```

Of course, someone needs to try it out with the different variants of `psr/log` to be sure.

**Comment by eileenmcnaughton** [comment]
FYI this is the monolog extension - https://lab.civicrm.org/extensions/monolog - I haven't checked as yet

**Comment by demeritcowboy** [comment]
I've also done a couple tests.

For v3, the addition of return type hints would cause a problem without the suggested change to civi's Error/Log class.

I haven't had a problem so far with drupal 10 (log v2) and doing some tests with civi's log() function it seems fine with the mixed signatures. php (including v8) seems to let you extend a class and change the signature to something LESS specific, but not the other way around.

[This](https://www.php.net/manual/en/language.oop5.variance.php) is a fun read, if the word fun has a very loose definition.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy for a brief moment reading that 'fun link' it became clear what they were saying - before descending again into 'Dogs eat Food but cats can't eat CatFood  unless dogs only eat DogFood - but what about table scraps....'

**Comment by demeritcowboy** [comment]
lol

**Comment by seamuslee001** [comment]
so where are we at with this, I feel like maybe the best course is just to allow psr/log 2 instead but not 100% sure

**Comment by demeritcowboy** [comment]
I don't know how debian packages are made but if that build system needs 3.0 only then just adding 2.0 won't help. I've put up an alternate (https://github.com/civicrm/civicrm-core/pull/23409) but my question would be does debian's build need composer.lock updated too, since then it would force 3.0 on everybody, which then requires php 8 for everyone.

**Comment by totten** [comment]
@demeritcowboy I'm pretty sure `debian.org` would use `composer.json` and ignore `composer.lock`. More specifically, from past reading/discussion, I believe that `debian.org`s approach is:

1. Map the entire dependency graph from `composer` into `deb`. (Ex: The releases `psr/log`@`1.1.3` and `monolog/monolog`@`1.26.0` are mapped to `php-psr-log_1.1.3-2_all.deb` and `php-monolog_1.26.0-1_all.deb`.) The dependency graphs are homomorphic. (See eg [pkg-php-tools/README](https://www.apt-browse.org/browse/ubuntu/trusty/main/all/pkg-php-tools/1.11/file/usr/share/doc/pkg-php-tools/README.Composer) and [dh_phpcomposer](https://manpages.debian.org/unstable/pkg-php-tools/dh_phpcomposer.1.en.html))
2. Only install one version of each library (one version of `php-psr-log`; one version of `php-monolog`)
3. For each major Debian release, choose a cohort of libraries+apps that are either (a) fully inter-compatible or (b) close-enough to be fudged with small patches.

For this approach, you'd expect `composer.lock` to be hopelessly conflicted... and  the manpage for `dh_phpcomposer` specifically refers to `composer.json`. (No mention about `composer.lock`.)

Of course, I haven't kept close tabs on Debian. @athos-ribeiro probably has a more up-to-date understanding of current policy+practice.

**Comment by totten** [comment]
Replaced by #23409 which adds the corresponding PHP patches.

Cheers @athos-ribeiro

**Pull request closed without merging**
