### PR TITLE
Add MembershipType to Api4

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
See #17427 This adds the MembershipType entity to API4

Before
----------------------------------------
Not available

After
----------------------------------------
Available

Technical Details
----------------------------------------

Comments
----------------------------------------
@eileenmcnaughton @colemanw

### CODE REVIEW

**Comment by seamuslee001** [comment]
Test fails relate

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by mattwire** [comment]
@colemanw @eileenmcnaughton Any ideas on this one? The test fails are something to do with relationships.

**Comment by colemanw** [comment]
@mattwire I looked at that test and noticed a flaw. Not sure if it's the only flaw blocking this PR but it can't hurt to fix it. Once that's merged, try doing `git pull --rebase origin master&&git push -f` and see if we still have problems with the test on this PR.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
unrelated fail

**Comment by mattwire** [comment]
Yay :-)

**Pull request merged**
