### PR TITLE
CustomGroup - Add pseudoconstant for extends column

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds missing pseudoconstant to schema, which will allow a SearchKit-based display of custom groups.

Technical Details
----------------------------------------
I'm not sure if there's a reason for this to be missing, but if tests pass then it's probably OK.

Comments
----------------------------------------
Toward https://lab.civicrm.org/dev/user-interface/-/issues/44#note_68136

### CODE REVIEW

**Comment by seamuslee001** [comment]
@colemanw test fail relates https://test.civicrm.org/job/CiviCRM-Core-PR/45946/testReport/junit/(root)/api_v3_ACLCachingTest/testActivityCreateCustomBefore_with_data_set__APIv3_/

**Comment by colemanw** [comment]
@seamuslee001 it was basically a typo in the test. All passing now.

**Comment by KarinG** [comment]
This PR caused all our WFC tests to fail -> RC is fine

image

image

**Comment by colemanw** [comment]
@KarinG I'm hoping this will fix it: #22298

**Pull request merged**
