### PR TITLE
dev/core#2316 - Symfony EventDispatcher dispatch() signature kerfuffle - try 2

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/2316

This is a reworking of https://github.com/civicrm/civicrm-core/pull/19960 to handle the change in the signature of EventDispatcher::dispatch() across symfony v4/5/6.

Before
----------------------------------------
Calls to dispatch() all give warnings in drupal 9 because symfony reversed the order of arguments. Then they fail in drupal 10. Also, the Event class disappears in symfony 6, so can no longer reference it.

It's difficult to see these warnings in drupal 9 because it annoyingly uses `@trigger_error` with the `@`, which silences the warning. But you can see them in drupal's own test environment - most of the warnings included in the count [at this link](https://github.com/colemanw/webform_civicrm/runs/6114535311?check_suite_focus=true#step:17:582) are about this issue. A similar type of test run is [at this link](https://github.com/SemperIT/CiviCARROT/runs/6151780417?check_suite_focus=true#step:18:104)

The lab ticket mentions the notices are appearing in core E2E tests too but I don't see them - perhaps those tests were deactivated temporarily.

After
----------------------------------------
This [test run](https://github.com/SemperIT/CiviCARROT/runs/6161405107?check_suite_focus=true#step:19:102) with the patch applied shows the "indirect deprecation notices" have disappeared. (The self deprecations are handled by another PR I have open - not symfony-related.)

Technical Details
----------------------------------------
* Keep CiviEventDispatcher as close as possible to what it was, so that its signature stays compatible.
* Replace Event with GenericHookEvent
  * In symfony 4, this class needs to continue to extend Event, because the signature of dispatch() in symfony 4 requires the parameter to be Event.
  * In symfony 6, it can't extend Event because it doesn't exist, so extend something else that looks like it.

Comments
----------------------------------------
For the last commit, the github diff is confusing so it might be easier to look at the resulting GenericHookEvent.php file, and then compare GenericHookEventTrait.php to the current master GenericHookEvent.php.

@totten @seamuslee001

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@totten @demeritcowboy @seamuslee001 what is the status of this one?

**Comment by demeritcowboy** [comment]
This is admittedly a difficult PR to review, not just for r-run against various cmses and versions but the architecture and thinking about whether to upgrade all cmses to some higher minimum version of symfony, both for simplification and general upgrade purposes.

From my point of view there's nothing for me to do at this time - if there's discussion needed it can be in the lab ticket.

**Comment by demeritcowboy** [comment]
Now that minimum is 4.4 after https://github.com/civicrm/civicrm-core/pull/23913 have removed this part to simplify:

```patch
diff --git a/Civi/Core/CiviEventDispatcher.php b/Civi/Core/CiviEventDispatcher.php
index ec84eb939e..03721d16e5 100644
--- a/Civi/Core/CiviEventDispatcher.php
+++ b/Civi/Core/CiviEventDispatcher.php
@@ -247,13 +247,10 @@ class CiviEventDispatcher implements CiviEventDispatcherInterface {
       }
     }
     $this->bindPatterns($eventName);
-    if ($this->isDispatcherSignatureBackwards()) {
-      if ($event === NULL) {
-        $event = new GenericHookEvent();
-      }
-      return $this->dispatcher->dispatch($event, $eventName);
+    if ($event === NULL) {
+      $event = new GenericHookEvent();
     }
-    return $this->dispatcher->dispatch($eventName, $event);
+    return $this->dispatcher->dispatch($event, $eventName);
   }

   /**
@@ -415,16 +412,4 @@ class CiviEventDispatcher implements CiviEventDispatcherInterface {
     return 'fail';
   }

-  /**
-   * They changed the signature in version 4.3, so we need to know which way
-   * to pass the parameters.
-   * @return bool
-   * @throws \OutOfBoundsException
-   *   If symfony EventDispatcher not installed at all.
-   */
-  private function isDispatcherSignatureBackwards(): bool {
-    $version = \Composer\InstalledVersions::getVersion('symfony/event-dispatcher');
-    return version_compare($version, '4.3', '>=');
-  }
-
 }
```

**Comment by totten** [comment]
I think this approach makes a lot of sense. 

In the terms of dev/core#2316, I believe this implements the following option:

> (C) ... we have a few basic options...
> * __Break away from `symfony/event-dispatcher`__: `CiviEventDispatcher` would not (going forward, on S4+ builds) directly extend `symfony/event-dispatcher` classes. Instead, do one of these:
>    * __Hard fork__: Copy from `symfony/event-dispatcher` circa 4.2 and build out parallel classes with different namespace where we can control contracts/scheduling

Specifically:

* `Civi\...\CiviEventDispatcher` is no longer a *subclass* of `Symfony\...\EventDispatcher`; it is a *wrapper*.
* The primary type for events is no longer `Symfony\...\Event`. It is now `Civi\...\GenericHookEvent`. (For a transitional period in S4, this class extends `Symfony\...\Event`. But that will go away with S5+.)

---

Some suggestions+questions:

* The typehint for `Civi::dispatcher()` is now incorrect. Perhaps it should be `@return CiviEventDispatcherInterface`? 
* For the transitional S4 period, `CiviEventDispatcherInterface` could extend `Symfony\...\EventDispatcherInterface` (*as was done for `GenericHookEvent` and `Symfony\...\Event`*).
* I found ~10 places in contrib which directly extend `Symfony\...\Event`, which was sensible under the old contract, but I suspect it will break going forward. We need to  be clear about what the is *recommended* base-class will be for the transition.
    * The PR seems to mostly use `GenericHookEvent` for this, although it also adds a class`Symfony4Event` which could also fill that niche. (*You would just need to [shift the `class_exists()` guard](https://gist.github.com/totten/740e50db0ffbbe73f9a7254a1425b04d).*) Which one seems like the better arrangement to land on? (*I'm on the fence, myself.*)
* For whatever the recommended base-class is,  `CiviEventDispatcher::dispatch()` could emit a warning to encourage migrations? That might ensure more timely updates? Does the performance impact seem negligble?
    ```php
    if (!($event instanceof GenericHookEvent)) {
      CRM_Core_Error::deprecatedWarning(sprintf('To achieve both backward+forward compatibility, event %s should extend %s.', get_class($event), GenericHookEvent::class));
    }
    ```

**Comment by demeritcowboy** [comment]
Thanks yes I think you're right the base class needs some thought. At the moment though I'm boggled by this test fail. The first time the assetUrl hook runs, it's all good, but then on subsequent iterations it becomes goofy. Behold:

Here it's just passing an array as the second param. Nothing fancy.

Untitled2

And yet, when it goes into the function, whaaaat?

Untitled3

Something like this came up before, one of the civigrant issues, but it was different. There, it was something like a typehint was doing some coercing. There is a docblock hint here of callable, but (a) it's just a docblock, and (b) if that were the issue here it would(?) happen on the first iteration too.

**Comment by demeritcowboy** [comment]
Extra bizzare, that "Unknown path" text is coming from javascript! When I change this line it picks up whatever text I put there https://github.com/civicrm/civicrm-core/blob/c98e5bd81954f858e13ff513a22fe78acf29ab1c/ang/crmApp.js#L20

**Comment by demeritcowboy** [comment]
Interesting. The earlier parts might be irrelevant, just documenting. It's the segfault that's interesting.

```
memory usage: 115867648
array (
  0 => '\\CRM_Utils_System',
  1 => 'alterAssetUrl',
)ok 1363 - E2E_Cache_TwoInstancesTest::testSingle_reload with data set #0 (array(array('SqlGroup'), 'TwoInstancesTest_SameSQL'))
ok 1364 - # SKIP This environment is not configured to use a memory-backed cache service.
ok 1365 - E2E_Cache_TwoInstancesTest::testDiff_clearA with data set #0 (array(array('SqlGroup'), 'testTwo_a'), array(array('SqlGroup'), 'testTwo_b'))
ok 1366 - # SKIP This environment is not configured to use a memory-backed cache service.
ok 1367 - # SKIP This environment is not configured to use a memory-backed cache service.
ok 1368 - E2E_Cache_TwoInstancesTest::testDiff_clearB with data set #0 (array(array('SqlGroup'), 'testTwo_a'), array(array('SqlGroup'), 'testTwo_b'))
ok 1369 - # SKIP This environment is not configured to use a memory-backed cache service.
ok 1370 - # SKIP This environment is not configured to use a memory-backed cache service.
ok 1371 - E2E_Cache_TwoInstancesTest::testDiff_reload with data set #0 (array(array('SqlGroup'), 'testTwo_a'), array(array('SqlGroup'), 'testTwo_b'))
ok 1372 - # SKIP This environment is not configured to use a memory-backed cache service.
ok 1373 - # SKIP This environment is not configured to use a memory-backed cache service.
memory usage: 117964800
array (
  0 => '\\CRM_Utils_System',
  1 => 'alterAssetUrl',
)ok 1374 - E2E\Core\AssetBuilderTest::testRender with data set #0 ('square.txt', array(11), 'text/plain', 'Square: 121')
ok 1375 - E2E\Core\AssetBuilderTest::testRender with data set #1 ('square.txt', array(12), 'text/plain', 'Square: 144')
ok 1376 - E2E\Core\AssetBuilderTest::testRender with data set #2 ('square.js', array(12), 'application/javascript', 'var square=144;')
memory usage: 117964800
array (
  0 => '\\Civi\\Core\\CiviEventDispatcher',
  1 => 'delegateToUF',
)ok 1377 - E2E\Core\AssetBuilderTest::testGetUrl_cached with data set #0 ('square.txt', array(11), 'text/plain', 'Square: 121')
ok 1378 - E2E\Core\AssetBuilderTest::testGetUrl_cached with data set #1 ('square.txt', array(12), 'text/plain', 'Square: 144')
not ok 1379 - Error: E2E\Core\AssetBuilderTest::testGetUrl_cached with data set #2 ('square.js', array(12), 'application/javascript', 'var square=144;')
not ok 1380 - Error: E2E\Core\AssetBuilderTest::testGetUrl_uncached with data set #0 ('square.txt', array(11), 'text/plain', 'Square: 121')
not ok 1381 - Error: E2E\Core\AssetBuilderTest::testGetUrl_uncached with data set #1 ('square.txt', array(12), 'text/plain', 'Square: 144')
not ok 1382 - Error: E2E\Core\AssetBuilderTest::testGetUrl_uncached with data set #2 ('square.js', array(12), 'application/javascript', 'var square=144;')
not ok 1383 - Error: E2E\Core\AssetBuilderTest::testInvalid
Segmentation fault
```

**Comment by seamuslee001** [comment]
Jenkins retest this please

**Comment by demeritcowboy** [comment]
It's all the same fails just without the segfault so it kept going so it looks like there's more. I need to get my head back into it and look at Tim's suggestions and maybe that will magically clear it.

**Comment by demeritcowboy** [comment]
Closing this and will continue in https://github.com/civicrm/civicrm-core/pull/24132 which takes advantage of symfony 4.4 being the minimum to simplify. I've figured out there where the memory corruption is coming from and just need to figure out what to do about it.

**Pull request closed without merging**
