### PR TITLE
(REF) `ts()` - Move from class-file to `functions.php`

### PR DESCRIPTION
**Pull request by totten**
Overview
--------

`ts()` is a global helper function. This normalizes the way it loads.

Before
------

`ts()` is defined in `CRM/Core/I18n.php`, which is most intuitively understood as a class-file.  As a class-file, you would expect it do one thing (declare `CRM_Core_I18n`) and to load via auto-loader.

In fact, the file does two things: declare `CRM_Core_I18n` and declare global function `ts()`.  For this latter reason, the system is sprinkled with calls to `require_once CRM/Core/I18n.php`. Presumably, folks needed to ensure that `ts()` was defined/parsed early... but didn't actually have a use for calling the class.

After
-----

Follow [this composer convention](https://getcomposer.org/doc/04-schema.md#files).

The global function is declared in a separate file.  This file is loaded very early (whenever the autoloader is registered). The pattern means that `ts()` is implicitly available.

Of course, if you need `CRM_Core_I18n`, it can still be resolved via autoloader.

Assuming this passes, the next couple commits can also drop references to `require_once`.

Comments
-----------

This topic came up in testing a revision of #29991. A general effect of that PR is to move `ts()`  calls from one file (`CRM/Foo/DAO/Bar.php`) to another file (`schema/Foo/Bar.entityType.php`). In the DAO context, it benefits from fiddlybits to load `ts()` -- but in the other context, it doesn't -- which leads to flakiness.

Following the composer idiom for loading global-functions means that you shouldn't have to think so much about how `ts()` gets loaded.

### CODE REVIEW

**Comment by totten** [comment]
Note: Test-failures in `CiviCRM-Extended-PR` require a little more care to interpret. Looking at the negatives:

* There are some pre-existing ones. (See a [baseline from a few days ago](https://test.civicrm.org/duderino/batch/20865960))
* There are new failures on D9/D10/SA configurations -- where Civi is installed as a composer subproject.  The problem is in the test methodology - composer doesn't read the modified version of `composer.json` in this configuration. It won't do until the code is merged.

This feels like the 3rd time in a week that the latter issue has made it hard to interpret test-results. So I'm gonna work a fix for that...

**Comment by totten** [comment]
> There are new failures on D9/D10/SA configurations -- where Civi is installed as a composer subproject. The problem is in the test methodology...

Changed those test jobs and re-fired. Before, those builds didn't run at all. Now, they are running. (They're not expected to pass completely. For proper eval, compare [baseline](https://test.civicrm.org/duderino/batch/20865974) and [new pr run](https://test.civicrm.org/duderino/batch/20865973).)

**Comment by colemanw** [comment]
@totten this looks like a solid change and PR tests are passing. I'm not sure how to interpret the extended tests because in some cases before is worse than after, and vice-versa.
Giving merge-ready as it looks good otherwise.

**Comment by totten** [comment]
Yeah, I think the pre/post test-runs look nominal.

Regular tests are fine. Extended tests are showing some flakiness in `phpunit-core-exts` -- there's a batch of ~40 E2E auth tests which rely on HTTP roundtrips -- where the subrequest fails weirdly. However, it's the same set of failures, and it appears both pre+post patch. They just seem to flipflop a bit with different runs (based on initial result-set and some "Retry" tests).

**Pull request merged**
