### PR TITLE
civicrm/admin/setting/uf - Fix advice about Backdrop Views

### PR DESCRIPTION
**Pull request by totten**
Overview
--------

The screen "*Administer => System Settings => CMS Database Integration*" (`civicrm/admin/setting/uf`) provides advice about enabling Views on multi-DB deployments.

In a stock deployment of Backdrop, the advice is incomplete and does not produce a working system.  This improves the advice.

Before
------

The screen `civicrm/admin/setting/uf` provides advice on configuring Views.It specifically suggests editing `settings.php` to update `array $databases` with a list of table-prefixes.

screen shot 2019-03-07 at 5 46 34 pm

However, in a stock deployment of Backdrop, these prefixes are not used. Why not? *After* evaluating the `settings.php`, Backdrop reads `string $database` and generates a new version of `array $databases` -- but this overwrites any table-prefixes that the admin has put into `array $databases`.

After
-----

The screen `civicrm/admin/setting/uf` provides advice on configuring Views and `settings.php`.

In addition to the previous advice, it also provides Backdrop admins with a snippet that pre-emptively translates `string $database` to `array $databases` *before* setting the table-prefixes.

screen shot 2019-03-07 at 5 45 40 pm

Backdrop subsequently uses this configuration without any further trampling/overriding.

Comments
--------

I initially tried a different UX -- in which we encourage the user to edit `settings.php` and manually change `string $database` to `array $databases`. However, this proved tricky. From a security perspective, you don't want to show advice with specific DB passwords. Moreover, after the system has bootstrapped, it's hard to detect how the configuration is written in `settings.php`.

I settled on this snippet because it:

* Doesn't need to know anything about specific credentials.
* Automatically respects changes in `string $database`.
* Gracefully does nothing if the admin already converted to `array $databases`.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@herbdool ping

**Comment by herbdool** [comment]
Indeed this is tricky! It seems like this does the job. I wonder if a more straightforward solution could be done on Backdrop side where when converting from string to array that it merge in the differences rather than replace. That way someone could have both $database and $databases. I'm going to float the idea there and see if there is any appetite.

**Comment by herbdool** [comment]
This might be a dumb question. Why not just have the sample assign the array of prefixes to `$database_prefix`? It already exists in settings.php and it seems like it can take an array or a string. Unless it can't.

**Comment by herbdool** [comment]
@totten How about this as an alternative patch?

```
diff --git a/CRM/Admin/Form/Setting/UF.php b/CRM/Admin/Form/Setting/UF.php
index 030ebea..70e046c 100644
--- a/CRM/Admin/Form/Setting/UF.php
+++ b/CRM/Admin/Form/Setting/UF.php
@@ -82,6 +82,9 @@ class CRM_Admin_Form_Setting_UF extends CRM_Admin_Form_Setting {
       $dsnArray = DB::parseDSN($config->dsn);
       $tableNames = CRM_Core_DAO::getTableNames();
       $tablePrefixes = '$databases[\'default\'][\'default\'][\'prefix\']= array(';
+      if ($config->userFramework === 'Backdrop') {
+        $tablePrefixes = '$database_prefix = array(';
+      }
       $tablePrefixes .= "\n  'default' => '$drupal_prefix',"; // add default prefix: the drupal database prefix
       $prefix = "";
       if ($config->dsn != $config->userFrameworkDSN) {
```

If the framework is Backdrop then just suggest assigning the whole array to `$database_prefix`, which accepts arrays. I haven't tested this since my test environments put CiviCRM into the same database as Backdrop.

**Comment by totten** [comment]
@herbdool - yeah, if it'll work with `$database_prefix`, and if it plays nice with whatever value might be put into `$database_prefix`, then :+1: for something simpler.

**Comment by herbdool** [comment]
@totten I've been able to test with two databases. Before I patch it I get the base table errors not foun error. After I change `$databases['default']['default']['prefix']= array(` to `$database_prefix = array(` in settings.php then the prefix works well.

Screenshot from 2019-03-12 00-41-13

@totten the above patch works. I've thought of providing an alternative PR for this.

**Comment by herbdool** [comment]
@totten @eileenmcnaughton ready for review

**Pull request closed without merging**
