### PR TITLE
CRM-20243 Upgrade jquery to 1.12

### PR DESCRIPTION
**Pull request by seamuslee001**
* [CRM-20243](https://issues.civicrm.org/jira/browse/CRM-20243)

### CODE REVIEW

**Comment by seamuslee001** [comment]
ping @jackrabbithanna

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by jackrabbithanna** [comment]
Well it passes tests, its these dependency upgrades that worry me the most stability wise, that being said, going from 1.11 to 1.12 shouldn't be a huge thing, candidate for merging this next release

**Comment by jackrabbithanna** [comment]
Merging #10582

**Pull request merged**
