### PR TITLE
Afform - Switch to user-oriented breadcrumbs, move admin link to hover button

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes a usability issue in AdminUI and other Afform-based screens.

Before
----------------------------------------
In full-page mode, breadcrumbs were oriented toward form-building, with links to edit the form and browse FormBuilder.

After
----------------------------------------
In full-page mode, breadcrumbs are oriented toward general users, with links to parent-pages. For form-builders, now there is a little "Edit Form" link in the top-right when you hover over the form.

Technical Details
----------------------------------------
Parent pages are, by default calculated based off the route. This adds a 'title' key in function `afform_civicrm_alterMenu` for the benefit of`CRM_Core_Menu::buildBreadcrumb`.

Alternately, if the Afform has been placed in the navigation menu, then the breadcrumb is calculated based on the parent menu item.

### CODE REVIEW

**Comment by colemanw** [comment]
@larssandergreen it would be great to get this one reviewed & merged :)

**Comment by aydun** [comment]
Test this please

**Comment by aydun** [comment]
I enabled AdminUI and visited a few of its pages:

1. I didn't get the Edit Form link on any pages - maybe I'm not hovering in the right place?
2. The Admin UI pages have double titles: eg http://core-27618-g71y.test-1.civicrm.org:8001/civicrm/admin/custom/group?reset=1 shows 'Custom Field Groups' twice.  Do we need to remove the titles in AdminUI and leave it with the new ones?
3. For Contact Types, the breadcrumb is 'Home > CiviCRM > Administer > Option Groups > Contact Types' but subtype is not an Option Group so you can't edit it from the Options Groups page.  Not a biggie in that Option Groups still need work and maybe Contact Types should move to a new URL.

**Comment by colemanw** [comment]
Thanks for reviewing @aydun 

1. Oh yea, the hover links are only for submission forms, not yet for search forms. For search forms I guess we need to decide if the link should take you to edit the form or the search, or maybe a little gear menu with links to both? Either way, it's a todo, but maybe not a blocker to this PR.
2. Good catch. I had to reach way back into my brain cache to remember how titles are supposed to work in Angular pages. Got it & pushed a fix.
3. Agree that's not a blocker. I think we could fix with an afform-based navigation menu as per this PR the breadcrumbs will align with the nav menu if present and fall back on the url path if not. We'll probably need to wait until we flip the switch permanently on the AdminUI extension though, as the menu item already exists.

**Comment by aydun** [comment]
Great, certainly more user-friendly (albeit less developer-friendly) than the old breadcrumbs. 

It would be good to get the hover link on the search forms but that can be a follow-up.  A link to the form would be enough: from there you can get to the search.

I've put it 'merge ready' in case @larssandergreen has any other thoughts.

**Comment by francescbassas** [comment]
+1 to get a gear menu with links to form and search instead of the hover link for the search form. With the changes in 5.67, you no longer have quick access to form editing. Do we create an issue to track it?

**Comment by colemanw** [comment]
@francescbassas yes that would be helpful if you could open an issue. Thanks.

**Comment by francescbassas** [comment]
Done https://lab.civicrm.org/dev/core/-/issues/4786

**Comment by colemanw** [comment]
... and done! https://github.com/civicrm/civicrm-core/pull/28206

**Pull request merged**
