### PR TITLE
CRM-20391 Added pan trucation to search

### PR DESCRIPTION
**Pull request by pradpnayak**
----------------------------------------
* CRM-20391: Add card number field on search form
  https://issues.civicrm.org/jira/browse/CRM-20391

### CODE REVIEW

**Comment by Edzelopez** [comment]
Jenkin, test this please

**Comment by monishdeb** [comment]
Tested on the patch, working fine. Here's the search form screenshot
image

**Comment by monishdeb** [comment]
Test build failure is not related as it is appearing on other PRs too. On [cosole log](https://test.civicrm.org/job/CiviCRM-Core-PR/14747/consoleFull) tells
``` 
PHP Fatal error:  Class name must be a valid object or a string in /home/jenkins/buildkit/build/core-10139-8m7z4/sites/all/modules/civicrm/CRM/Core/DAO.php on line 1777
````

**Comment by eileenmcnaughton** [comment]
OK - test is good! Issue title is wrong - fix is for pan_truncation

**Pull request merged**
