### PR TITLE
Install CiviCRM in Backdrop is mostly working

### PR DESCRIPTION
**Pull request by herbdool**
Just wanted to post an initial PR and get feedback if anyone is available. This could be part of CRM-17711.

I've gotten CiviCRM installing in Backdrop so that part seems to be fine. But I'm still getting a fatal error after clicking the install button:

`Fatal error: Call to undefined function config_get() in /path/code/core/includes/bootstrap.inc on line 1808`

So it seems like it's not bootstrapping Backdrop once it's trying to go to the Install success page. It has something to do with calling t().

I'll keep investigating and update the PR if I find the issue, otherwise it would help if someone had a moment to try out the install. Thanks!

---
- [CRM-17711: Add Support for Backdrop](https://issues.civicrm.org/jira/browse/CRM-17711)

### CODE REVIEW

**Comment by herbdool** [comment]
In order to test installing on Backdrop, go to example.com/modules/civicrm/install/index.php?civicrm_install_type=backdrop

(You'll also need to download the backdrop civicrm build and apply this PR as a patch. And you might also need to replace the civicrm/backdrop files with the latest version at https://github.com/civicrm/civicrm-backdrop)

**Comment by quicksketch** [comment]
> Fatal error: Call to undefined function config_get() in /path/code/core/includes/bootstrap.inc on line 1808

I encountered this error as well. We can fix it in Backdrop core. I filed an issue at https://github.com/backdrop/backdrop-issues/issues/1834.

**Comment by quicksketch** [comment]
Also, this is looking great! I started doing the same thing until I ran across this, it looks like you've got this almost entirely working!

**Comment by herbdool** [comment]
I'll test this again against your PR to BD core @quicksketch. For this PR to be accepted into CiviCRM core I'll need to get someone other than me to test it as well.

**Comment by herbdool** [comment]
My install runs successfully now so I'd say we're most of the way there now.

On the success page I see the wrong base url being used, but that might be a Drupal issue too since that code wasn't changed (in civicrm_cms_base()).

Another issue is that it isn't setting the default permissions for anon and authenticated users--I'll look into that.

**Comment by herbdool** [comment]
Permissions are being set properly now.

**Comment by PalanteJon** [comment]
I've just successfully tested this patch - installed a fresh copy of Backdrop, tried installing Civi 4.7.8 without this patch and it failed.  Installed the patch (which still merges cleanly on 4.7.8) and was able to install successfully.

**Comment by herbdool** [comment]
Thanks @PalanteJon! I suppose this is now going to be aimed at 4.7.9? @totten

**Comment by PalanteJon** [comment]
Actually @herbdool - I am not seeing the anon/authenticated permissions set properly.  Is there a PR other than this one that you've applied?  I'm using stock Backdrop 1.4.2 and stock Civi 4.7.8 with only this PR applied.

**Comment by herbdool** [comment]
Odd, I need to find out what happened to that commit. I really thought I had pushed that. Luckily it was only a small change.

**Comment by herbdool** [comment]
@PalanteJon apologies. I found the missing changes and I amended the commit. Can you try it again?

**Comment by PalanteJon** [comment]
@herbdool I just tested this and confirm that default user permissions are now set successfully.
@JoeMurray I don't see a "Release Planning" doc for 4.7.9, but could you mark this as successfully QAed?
@totten I just looked at the 4.7.8 release doc and saw you assigned this to yourself.  You can take yourself off this PR unless you have a compelling need!
Finally, one more @herbdool - Feel free to assign the Jira ticket to me to make installation instructions on the wiki.

**Comment by herbdool** [comment]
That's good news @PalanteJon!

I don't think there's a Jira ticket, at least not one which I created.

**Comment by JoeMurray** [comment]
Heh Herb, as Release Manager this month, I'm trying to recruit people to help pare down the backlog of almost 100 PRs, some going back to last summer. I'm wondering if you would be able to help QA another PR if I got someone to QA this PR?

**Comment by herbdool** [comment]
@JoeMurray I can help QA on a different PR. But @PalanteJon already did the QA for this.

**Comment by eileenmcnaughton** [comment]
Based on @PalanteJon's review and based on the fact this only affects backdrop (reading the code all additions include if('backdrop') type stuff  I am now mergining

**Comment by eileenmcnaughton** [comment]
NB looks like there should be some follow up on writing install instructions? Anyone anyone?

**Comment by PalanteJon** [comment]
I'll do the documentation.

**Pull request merged**
