### PR TITLE
(dev/core#251) fix batch copy for multi-select fields

### PR DESCRIPTION
**Pull request by yashodha**
Overview
----------------------------------------
Steps to replicate :
-------------------------

1. Create a profile with membership type field.
2. Click Find Memberships and select a few members and do Update multiple memberships with above profile.
3. Click on copy icon for membership type, it doesn't copy over 1st row to the rest

Before
----------------------------------------
it resets the first row to first option and copies that not the selected one.

After
----------------------------------------
it copies over the chosen value

### CODE REVIEW

**Review by colemanw — CHANGES_REQUESTED** [review]
This code still doesn't make sense to me. What is this conditional trying to ascertain? That the element is a multiselect? That would be super easy:

    if (elementId.is('select[multiple]'))

But instead it is doing some stuff that I don't understand. The api documentation for `.select()` says it triggers an event:

> The select event is sent to an element when the user makes a text selection inside it. This event is limited to `<input type="text">` fields and `<textarea>` boxes.

What is the purpose of triggering a text selection dom event within an if statement? Especially if we are dealing with a select input and *not* a textfield. That event doesn't even apply to that type of field.

**Comment by sdoijad** [comment]
We Can not use   
`if (elementId.is('select[multiple]'))`
Because, selector "elementId" is for ALL the select boxes so here "elementId.is('select[multiple]')" is always  returning FALSE.

**Comment by colemanw** [comment]
Ok so you could use `if (elementId.first().is('select[multiple]'))` but I'm still confused about the use of `.select()` - what is that for?

**Comment by eileenmcnaughton** [comment]
@yashodha looks like this needs action by you

**Comment by yashodha** [comment]
@eileenmcnaughton I will look into this, thanks!

**Comment by eileenmcnaughton** [comment]
@yashodha this has been hanging out waiting for response to the review for a while - I'm going to close it & let you re-open it when you have time / enthusiasm to work on it

**Comment by ErikHommel** [comment]
@yashodha re-opening as I now encounter it at Amnesty International Vlaanderen who have recently upgraded to 5.5.1. Do you have time to look into the reviewer comments?

**Comment by colemanw** [comment]
@yashodha ping - can you please revisit this

**Comment by yashodha** [comment]
@colemanw 
will look into this soon

**Comment by eileenmcnaughton** [comment]
Let's close this in the interim since it's been another 3 weeks & there isn't much in the PR so no big deal to re-create

**Pull request closed without merging**
