### PR TITLE
dev/mail#20 : Preview screen doesn't open until recipients list is built on mail compose screen

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
To replicate the issue:

1. Create a new mailing and fill out everything but not the Recipients field.
2. Now select a recipients group that is either very large or is based on a complex smart group. after selecting it -- click preview HTML/Text.

Before
----------------------------------------
The preview window will not open until the recipient count query has completed. This can also be replicated by setting up a mailing with a large/complex group, saving it, then continuing it and immediately clicking preview. the window will not open until the query completes.

After
----------------------------------------
Preview action doesn't wait for recipient built to complete and opens the preview window instantly.

Technical Details
----------------------------------------
As per the change it directly calls API and doesn't rely on Promise queue to deliver the result in sequence.

### CODE REVIEW

**Comment by monishdeb** [comment]
ping @lcdservices @colemanw

**Comment by eileenmcnaughton** [comment]
also @davejenx

**Comment by lcdservices** [comment]
@monishdeb tested and working as expected. The preview modal opens immediately.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @andrew-cormick-dockery This has been tested but I'd really like you guys to sign off on it too as you got stung by a mailing bug recently

**Comment by monishdeb** [comment]
@lcdservices I have changed my patch, which will now fix the issue where earlier, making any changes on HTML/text content doesn't get reflected in the preview screen, as the content is not saved to DB. On another look, I saw that we don't even need to call ```Mailing.preview``` API as we already have a variable ```$scope.mailing``` which holds the mailing instance and we use it directly and thus resolve all issues

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by lcdservices** [comment]
@monish this looks good. The preview does not depend on the recipients list being built before displaying, and when clicked, will display the mailing content even if autosave is not completed.

**Comment by colemanw** [comment]
@seamuslee001 or @andrew-cormick-dockery I think this is waiting on the green light from one of you.

**Comment by seamuslee001** [comment]
I've reviewed the code and gave this a test using a pretty big mailing and worked as expected. I can't see any ACL issues here. Happy to see this merged

**Pull request merged**
