### PR TITLE
CRM-17846 	Fixing lock name to be less than 64 characters for MySQL 5.7 compatib

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
This is Andrew Perry's patch but I adjusted a little as it was failing tests. I think test coverage is pretty good

---
- [CRM-17846: Improving locks for CiviMail](https://issues.civicrm.org/jira/browse/CRM-17846)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This is an adjustment of https://github.com/civicrm/civicrm-core/pull/7983

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@andrewperry This has now passed - if you can re-review it & are happy then I will merge it (phew)

**Comment by andrewperry** [comment]
That looks great!  I wasn't sure if I changed the jobLog to the id if that would cause issues for people who expect the jobLog to have a discernible name in it but I believe that was your creation to deal with the hackyCode so looks like a fix to me!!

**Comment by eileenmcnaughton** [comment]
I've merged it. I used the github 'squash & merge facility'. This was the first time I used that with commits from more than one author & sad to say it didn't keep the correct attribution & has put one commit with me attached. I was hoping that as the first commit was yours it would keep you instead

**Pull request merged**
