### PR TITLE
dev/core#4424 - ManagedEntity: log errors but don't crash when api entity is missing

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes the reconciliation of managed-entities to be less crashy, especially during installs and upgrades.

Before
----------------------------------------
Missing entity (possibly due to an extension about-to-be-installed-but-not-installed-yet) causes crash.

After
----------------------------------------
Error is logged but no crash.

### CODE REVIEW

**Comment by totten** [comment]
The concept is pretty appealing. I'm a little bit nervous that we're not reproducing the precise scenario behind 4424, but - just looking at this generally - I did do some `r-run`. Specifically:

1. Take an existing extension
2. Add a bad `*.mgd.php` file (ie with non-existent entity)
3. Navigate to `civicrm/menu/rebuild` (or run `cv flush`)

And that seemed to work as-advertised. :smiley: 

I think that the logging policy is a bit too quiet -- i.e. a call to  `Civi::log()->error()` is basically invisible unless you trawl the logs. I would definitely expect an error like this to be more apparent.

(Aside regarding edge-cases: The use of `Entity::get()` as the only index probably has some funny effect for entities like `JobLog` or `System` -- which are real but lack sufficient actions for use with mgd. But I don't think it's really a big deal.)

Question: Is there a possibility for cascade issues - e.g. an extension tries to insert (say) a `EckEntityType` and several `CustomField`s, but the `EckEntityType` is skipped, so the dependents should also be skipped? (*My recollection of the dataflow for that is a little hazy -- just trying to think of an example of dependency.*)

**Comment by colemanw** [comment]
@totten how about we merge this as "better than it was before?"

**Comment by larssandergreen** [comment]
Louder logging seems like it would be annoying for admins, who have no way to do anything about whatever is being logged. I would say it shouldn't even be an error (should be info maybe) as it is intended behaviour.

**Comment by totten** [comment]
>  In most scenarios a missing entity is not a serious error because it's next in line to be installed...

Based on a sample set of... 1 scenario? (ie dev/core#4424) There are plenty of other ways to get a bad value of `entity`, such as:

* Extension `A` is being developed. The developer creates an `*.mgd.php`. The file is loaded. (The debugger says it's loaded!) But the entity is never created. Because there's a typo. The developer just sees that... their data doesn't show up.
* Extension `B` is being developed... with a typo... but the developer never noticed a problem because the desired data was drafted on his local system. So he already has the data. He assumes `mgd.php` works -- and publishes. So site-builder installs it, and... it just quietly doesn't work.
* Extension `C` defines an entity, and extension `D` uses it for an `mgd.php`. But at runtime, extension `C` may be missing because:
    * The site-builder didn't install `C`.
    * The site-builder installed  `C` in January; but in November, they figured that `C` wasn't really used - so they removed it.
    * The site was recently redeployed, but it was managed in git, and a quirk of `gitignore` meant that C was incomplete.
* Extension `E` defines an entity, and extension `F` uses it for an `mgd.php`. But at runtime, the API is missing because the version of `E` got mixed up.
* Extension `G` defines a managed entity. The entity is provided by core, and there isn't a typo. But the API is missing because:
    * The local system has an older version of core, and the extension-developer didn't declare the `<ver>`.
    * The local system has an older version of core, and site-builder didn't care what was in `<ver>` -- because they installed direct from git.

That's +8 scenarios. Unlike 4424, none of these will self-correct after 10ms. Right now, these scenarios are easy to detect/prevent/fix because this problem throws a proper exception. But if it's pushed down to an obscure log, then all of the processes around them get more expensive.

The importance of the problem varies by context (i.e. the specific entity, the specific extension, the expectation of the end-user). But if you look in terms of contracts, a missing entity is the same kind of error-ness as a missing class or missing function -- i.e. it's very likely to indicate bug that someone needs to fix.

**Comment by totten** [comment]
We chatted a bit more and liked a few follow-ups:

* Use the `isUpgradeMode()` to quiet things during the upgrade
* Use the `debug_enabled` flag to elevate more error-level messages to console

But as-is, this is better than status-quo and should go in. However, it probably should to the RC.

**Pull request closed without merging**
