### PR TITLE
Object id is always NULL in ore hook in update activity mode

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
In pre hook for Activity in edit mode Activity id i.e the object id is always NULL.

Before
----------------------------------------
Activity id i.e the object id is always NULL.

After
----------------------------------------
Activity id i.e the object id is NOT NULL.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@pradpnayak makes sense - you need to make good with jenkins though

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by eileenmcnaughton** [comment]
Unrelated fail

**Pull request merged**
