### PR TITLE
CRM-19621 Fix fatal error caused by previous version of fix

### PR DESCRIPTION
**Pull request by seamuslee001**
* [CRM-19621: Contribution "confirm" page does not display state\/country](https://issues.civicrm.org/jira/browse/CRM-19621)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton @monishdeb @jitendrapurohit this fixes the fatal error i found whilst keeping most of Jitendra's fix in tact. Can you please verify that it still fixes the original problem?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 OK - the reservation I had about the original fix was that it altered CRM_Payment_Form which is used multiple code paths, and I wasn't sure what the impact was across them all. This has a test fail :-(

**Comment by eileenmcnaughton** [comment]
& to put that in perspective - I realise it was fixing something introduced by a patch affecting multiple code paths - but this is a change to the rc - so going backwards feels safer than ploughing on in the context of the rc

**Comment by monishdeb** [comment]
@seamuslee001  @eileenmcnaughton can it be closed in favor of https://github.com/civicrm/civicrm-core/pull/9466 ?

**Comment by eileenmcnaughton** [comment]
replaced by #9466

**Pull request closed without merging**
