### PR TITLE
[REF] Migrate fpdi library to be deployed using composer

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This migrates the installation of the FPDI library from the packages folder to being via composer and upgrades from v1.5.0 to v1.5.4 A diff is here https://gist.github.com/5939e12f232f96a3c0b52c527e96f40b

Before
----------------------------------------
FPDI library deployed via packages folder

After
----------------------------------------
FPDI library deployed using composer

ping @totten @demeritcowboy

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 any idea what it does / how we test?

**Comment by seamuslee001** [comment]
@eileenmcnaughton not 100% sure the only reference i can see to it is here https://github.com/civicrm/civicrm-core/blob/master/CRM/Utils/PDF/Utils.php#L129

**Comment by demeritcowboy** [comment]
I'm not at a computer right now but isn't there a feature somewhere that lets you use your own pdf as a template? Does that use this since that's what fpdi does?

**Comment by eileenmcnaughton** [comment]
In that case it's likely the package only exists due to copy & paste since I don't think we do that

**Comment by eileenmcnaughton** [comment]
hmm https://github.com/civicrm/civicrm-core/pull/3545/files

**Comment by eileenmcnaughton** [comment]
OK - looks like copy & paste from cdn tax receipts which DOES use it https://github.com/jake-mw/CDNTaxReceipts/blob/master/cdntaxreceipts.functions.inc#L6

**Comment by eileenmcnaughton** [comment]
Hmm - where do we even call html2pdf_tcpdf from?

**Comment by eileenmcnaughton** [comment]
OK -here is the answer 

https://issues.civicrm.org/jira/browse/CRM-14567 advocated switching to tcppdf and https://github.com/civicrm/civicrm-core/pull/3545/files implemented

BUT
it was 'unimplemented' in 
https://github.com/civicrm/civicrm-core/pull/3587 with the key commit being

https://github.com/civicrm/civicrm-core/pull/3587/commits/8d7ae5ee4f9d0927104fd1b8ecb07f7c25bfa453


which means _html2pdf_tcpdf is unused & should be removed along with the 2 associated packages.

**Comment by eileenmcnaughton** [comment]
Note that if we prefer to deprecate it we could simply make it call  _html2pdf_dompdf along with a deprecation warning

**Comment by seamuslee001** [comment]
I'm fine either way

**Comment by eileenmcnaughton** [comment]
Yeah me too - extensions shouldn't be calling it directly as it is not a supported interface - but if it happens that they do then calling the other function might give them some breathing space without it being much hassle for us to do

**Comment by eileenmcnaughton** [comment]
side point - I think ideally we would have a hook or similar for pdf classes to make them more swappable

**Comment by seamuslee001** [comment]
so @eileenmcnaughton given CDNTaxReceipts uses this library we probably need to do one of the following

1. Migrate to using composer as per here
2. Completely ditch it from composer but install it in the extension specifically (hello version sync issues)
3, Leave it in packages and just note it should be removed at some point perhaps. The other thing is using github's search it doesn't seem to find any direct references to `html2pdf_tcpdf ` 

It should be noted tcpdf is used here https://github.com/civicrm/civicrm-core/blob/master/CRM/Utils/PDF/Label.php#L23 but no sign of the FPDI library tho

**Comment by eileenmcnaughton** [comment]
@seamuslee001 no - they implement their own version I think

**Comment by seamuslee001** [comment]
@eileenmcnaughton i can't see any evidence they have

**Comment by eileenmcnaughton** [comment]
Oh hang on - maybe not - OK - well why not do a PR to them just adding FPDI  to their repo

**Comment by eileenmcnaughton** [comment]
It should come out of core if it's unused in core

**Comment by seamuslee001** [comment]
actually take that back, your right but how is that working with core, so i guess we can probably pull them out this library then (not tcpdf tho)

**Comment by eileenmcnaughton** [comment]
@seamuslee001 actually - https://github.com/jake-mw/CDNTaxReceipts/tree/master/FPDI

**Comment by eileenmcnaughton** [comment]
also we can remove this FUNCTION from core even if not the tcpf package

**Comment by seamuslee001** [comment]
Probably so just in regards to the FPDI library then i think all we need to do is this PR then https://github.com/civicrm/civicrm-packages/pull/287

**Comment by eileenmcnaughton** [comment]
A tentative yes - we also need to remove some or all of the html2pdf_tcpdf function - I'll merge that one now though

**Comment by seamuslee001** [comment]
closing this now

**Pull request closed without merging**
