### PR TITLE
[NFC] Extend send email test to cover for contact tokens being replaced

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This adds a test to verify the fix in https://github.com/civicrm/civicrm-core/pull/21385 for the problem identified from this merge  https://github.com/civicrm/civicrm-core/pull/21365

Before
----------------------------------------
Test doesn't cover contact tokens

After
----------------------------------------
Test covers contact tokens

ping @eileenmcnaughton @demeritcowboy

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
thanks @seamuslee001

**Comment by seamuslee001** [comment]
Note test fail expected as test run started before #21385 was merged but for posterity it was 

```
CRM_Activity_BAO_ActivityTest::testSendEmailBasic
Mr. Anthony Anderson .  not found in  MIME-Version: 1.0
From: testSendEmailBasic@example.com
To: Anthony Anderson <anthony_anderson@civicrm.org>
Subject: testSendEmailBasic subject
Reply-To: testSendEmailBasic@example.com
Date: Mon, 06 Sep 2021 23:50:02 +0000
Content-Type: multipart/alternative;
 boundary="=_ef5401fa5e67ad9df6fca008245cd7d1"

--=_ef5401fa5e67ad9df6fca008245cd7d1
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=utf-8

testSendEmailBasic text {contact.display_name}
--=_ef5401fa5e67ad9df6fca008245cd7d1
Content-Transfer-Encoding: 8bit
Content-Type: text/html; charset=utf-8

testSendEmailBasic html {contact.display_name}
--=_ef5401fa5e67ad9df6fca008245cd7d1--
  
Failed asserting that 'MIME-Version: 1.0\n
From: testSendEmailBasic@example.com\n
To: Anthony Anderson <anthony_anderson@civicrm.org>\n
Subject: testSendEmailBasic subject\n
Reply-To: testSendEmailBasic@example.com\n
Date: Mon, 06 Sep 2021 23:50:02 +0000\n
Content-Type: multipart/alternative;\n
 boundary="=_ef5401fa5e67ad9df6fca008245cd7d1"\n
\n
--=_ef5401fa5e67ad9df6fca008245cd7d1\n
Content-Transfer-Encoding: 8bit\n
Content-Type: text/plain; charset=utf-8\n
\n
testSendEmailBasic text {contact.display_name}\n
--=_ef5401fa5e67ad9df6fca008245cd7d1\n
Content-Transfer-Encoding: 8bit\n
Content-Type: text/html; charset=utf-8\n
\n
testSendEmailBasic html {contact.display_name}\n
--=_ef5401fa5e67ad9df6fca008245cd7d1--\n
' contains "Mr. Anthony Anderson".
```

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by demeritcowboy** [comment]
Thanks. When I get a minute I might put up a PR to have a copy of the test _without_ the tokens, since we've seen elsewhere there's code that sometimes assumes there's always a token present.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy yeah good thinking!

**Pull request merged**
