### PR TITLE
dev/user-interface#53 Reduce presence of Save and Done/New on forms

### PR DESCRIPTION
**Pull request by mlutfy**
Overview
----------------------------------------

https://lab.civicrm.org/dev/user-interface/-/issues/53

Removes less useful variants of "Save" buttons on some forms in an attempt to make the interface less overwhelming.

It also removes the "top" buttons from Manage Events pages, which, for some reason, had slipped under my radar when working on #26886.

Some more details here explaining why I removed "Save and Next", and why sometimes keep "Save and New":  
https://lab.civicrm.org/dev/user-interface/-/issues/53#note_149879

Forms modified:

- Manage Contribution Page
- Manage Event
- New Campaign
- New Financial Batch
- Edit existing contact (New Contact keep the current behaviour, with Save and New available)
- ~~Contact Record > New Contribution (but standalone New Contribution forms keeps old behaviour)~~
- ~~Contact Record > New Membership (same as above)~~
- ~~Contact Record > New Participant (same as above)~~
- ~~Contact Record > New Pledge (same as above)~~

Before/After
-------------------------

### Manage Contribution Page

Before:

image

After:

image

### Edit existing contact

Before:

image

After:

image

Note that for New contacts, the "Save and New" is still there, for people who do batch data entry.

### New Contribution (for a contact)

Before:

image

After:

image

(for Contribution > New Contribution, not associated to a contact, the "Save and New" will still be there)

The same logic applies to:

- New Membership
- New Pledge
- New Participant

Comments
----------------

What's  with ` 'spacing' => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',` ? Seems to have no effect.

cc @larssandergreen @joshgowans @agileware-justin @vingle

### CODE REVIEW

**Comment by vingle** [comment]
Removing Save & Done from Contribution page and Save & New from Edit/Create Contact screen makes good sense.

It might just be me, but I find 'Save & Next' useful when setting up a new contribution page, it saves me a click (and also hints that clicking to the next tab at the top without saving could lose my changes).

**Comment by mlutfy** [comment]
> "It might just be me, but I find 'Save & Next' useful when setting up a new contribution page"

That was my first thought too - and initially I wanted to fix Contribution/Events/Petitions so that they use the same pattern ("Save and Next" when not the last page, and "Save and Done" on the last step), but I got into a mess, because:

- Events does not do  "Next" at all, and has tabs that are not event-specific (ex: reminders)
- Contribution could, but it also has screens that are not exactly steps of a wizard.
- Also Contribution Page initially opens in a popup, which then redirects to the second tab, I think.

so I tossed it in the bin of "good ideas, but not consistent enough to be useful" :grimacing:

**Comment by agileware-justin** [comment]
Great job @mlutfy 👍

I'll review and provide any feedback. Looks good to me on paper.

**Comment by vingle** [comment]
> so I tossed it in the bin of "good ideas, but not consistent enough to be useful" 

Fair enough! Looks good to me too.

I'm guessing _at some point_ these screens will be reworked with Form Builder anyway. It feels like the modern, 'expected' behaviour is for changes to be saved as you click between tabs. Packing a tabbed multi-step form as a wizard feels problematic because 'first time creation' and 'repeat editing' are two different use-cases. An ideal wizzard may want to hide complexity and focus on MVP entity creation. So probably more sensible to focus on edit UX, as this PR does.

**Comment by colemanw** [comment]
> Looks good to me on paper.

For those of us who print our Civi forms on paper 🤣

**Comment by mlutfy** [comment]
@agileware-justin Any luck? Otherwise I think we can merge based on the review by @vingle and no objections?

**Comment by agileware-justin** [comment]
@mlutfy I'll review later today. It's of interest to me for UX, rather than fixing any specific issue that has been reported, hence a weekend job.

**Comment by agileware-justin** [comment]
@mlutfy some feedback:

We do have CiviCRM users who frequently enter in multiple Activities for a single Contact. And others who register the same Contact for multiple Events. I expect that there are others who do enter multiple Contributions for a Contact as well. So in these cases, losing the "Save and New" button may _not be optimal_ and I expect we will receive some feedback about this change.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

Have you scanned the CiviCRM documentation to see if there are any references or screenshots there that need to be updated?

Otherwise, PR looks good to me.

**Comment by mlutfy** [comment]
@agileware-justin Thanks for the feedback. I think it's valid, i.e. I'm sure some people do use the "Save and New" sometimes. Are you suggesting we do not remove the "Save and New" in those circumstances?

Or, in other words:

- what fraction of users do you think use it
- do you think they will be very much annoyed by this change? (imo, since those forms open in popups, it doesn't really slow you down by much)

Good point about screenshots. I had a quick look and found some that either had "Save and New" or had top buttons, which I removed in other PRs:

- https://docs.civicrm.org/user/en/latest/organising-your-data/activities/#types
- https://docs.civicrm.org/user/en/latest/contributions/manual-entry-of-contributions/

**Comment by vingle** [comment]
Just to clarify @agileware-justin - my understanding is this PR doesn't change the UX for someone adding events, contributions or activities to a contact. The only place 'save and new' is being removed from is after clicking 'edit' on the contact dashboard. ie this screen, to add a new contact after editing one…

image

'Save and new' on the 'add contribution' tab isn't impacted, right @mlutfy? Tho, not sure if it's also removed from 'Create New Individual/Household/Org' pages too, or just the edit display? 

image

**Comment by agileware-justin** [comment]
@vingle morning! No that's not correct, this pr does remove the save and new button from contact actions. See pr screenshot for new contribution for a contact.

Was evident that this was the case when I tested which is why I mentioned it.

**Comment by vingle** [comment]
> See pr screenshot for new contribution for a contact.

The PR screenshot is for the Contribution _Page_ creation/manage, not new contribution for a contact. But if what you say is true, then maybe the PR needs updating @mlutfy to make this clear as it reads like it only removes two instances - 'contact edit' and 'contribution page creation/manage'.

**Comment by mlutfy** [comment]
This PR really does remove excess buttons in many places, not just those 2 instances.

I updated the PR summary to list all the forms concerned.

I'm fine with not removing the "Save and New" from "Contact > New X", and merge the rest.

**Comment by vingle** [comment]
> This PR really does remove excess buttons in many places, not just those 2 instances.

Thanks for updating. Sorry, I haven't mastered getting Buildkit running near my Civi/MAMP setup to make it quick to test PRs/patches yet.

**Comment by mlutfy** [comment]
>  I haven't mastered getting Buildkit running near my Civi/MAMP setup to make it quick to test PRs/patches yet.

For what it's worth, recently the PR bot auto-comment was updated (by Coleman/Tim) to include links to the test sites that are built automatically with the PR:

image

(most of the time, I either use those test sites, or I throw the patch in production)

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by colemanw** [comment]
@mlutfy yea maybe we should document that command... https://github.com/civicrm/probot-civicrm/pull/10

**Comment by vingle** [comment]
jenkins, test this please

**Comment by vingle** [comment]
Amazing PR demo feature! Thanks for letting me know.

I was worried that custom fields / profile fields would be impacted - as that's a scenario of 'save-and-new' I use, so am pleased to see they're intact. This seems maybe a little CMS-specific - ie 'save and new / save as copy / save and close' is common in Joomla (and often a good time saver), while Drupal is always just 'save'..

Am sympathetic to Justin's points - I can imagine it impacting some people's. People sitting with a pile of paper registration forms from an offline signup drive, manually entering them into a Civi? Is that very common? But otherwise this looks a good PR and wouldn't impact my workflows.

**Comment by colemanw** [comment]
@mlutfy can you please
a) rebase this to solve merge-conflicts
b) restore the save-and-new buttons per reviewer feedback
And we'll get this merged :)

**Comment by mlutfy** [comment]
Rebased and added back "Save and New" on the "Contact > New X" forms.

With a caveat: they will only show for New Contributions/Membership/Pledge. Not if editing an existing entity.

I still think these buttons cause more cognitive overhead, than they save time for batch entry, because these forms open in popups and it's really quick to 1) validate the data entry 2) add another one.

but I'm happy to iterate on this and circle back in 6 months based on feedback.

**Comment by eileenmcnaughton** [comment]
Looks like this is pretty well agreed - merging

**Pull request merged**
