### PR TITLE
5.6.0 release notes

### PR DESCRIPTION
**Pull request by agh1**

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by totten** [comment]
@agh1 I see the WIP flag is still here. How are we doing on this one? I'm hoping to publish in the first half of the day Wed (US/Eastern).

**Comment by agh1** [comment]
@totten I think it should be good to merge.  Thanks for flagging!

**Comment by seamuslee001** [comment]
@totten only thing to add maybe something on that soft credits report thing

**Comment by totten** [comment]
Thanks @agh1 @seamuslee001. I added a reference to #12860 and merged.

**Pull request merged**
