### PR TITLE
Give administer CiviCRM data access to administer custom groups

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Give administer CiviCRM data access to administer custom groups

Before
----------------------------------------
@UshaMakoa  is trying to give the 'administer CiviCRM data' permission & it's not currently permitting access to this screen (must be defaulting to Administer CiviCRM which encompasses 'administer CiviCRM data'

After
----------------------------------------
@UshaMakoa is testing - watch this space....

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@UshaMakoa did you test this - my feeling is we probably should merge it (it allowed the user with only 'Administer CiviCRM data' to edit custom data config in my testing but I recall you had additional problems

**Comment by demeritcowboy** [comment]
I'm having trouble getting this to work. Even giving `administer civicrm system` as well doesn't seem to allow access to admin pages. And at one point I got `Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'administer CiviCRM data' not found or invalid function name in CRM_Core_Permission::checkMenuItem() (line 562 of .../CRM/Core/Permission.php)`.

**Comment by demeritcowboy** [comment]
You'd also have to update the menu entry permission in xml/civicrm_navigation.tpl, but even editing that menu item doesn't seem to do the trick for me.

**Comment by UshaMakoa** [comment]
Thank you @eileenmcnaughton Sorry but I wasn't sure if I was missing a step or a bug with the patch but I couldn't see the good result...

**Comment by eileenmcnaughton** [comment]
Argh I pushed up access callback - fixed with 

```
<access_arguments>administer CiviCRM data</access_arguments>
```

That ^^ should be added to the xml for any menu item we want 'administer CiviCRM data' to suffice for

**Comment by demeritcowboy** [comment]
It works. And then to get the menu entry yes you have to change its permission too, and then either move it out of the administer menu or change the permission for all of its parents too.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy yeah - it would be nice to think that if this works for @UshaMakoa then we might get some follow up PRs to alter other aspects to make that permission more useful

**Comment by eileenmcnaughton** [comment]
@demeritcowboy shall we merge now - I suspect 4 days is enough

**Comment by demeritcowboy** [comment]
Sounds good.

**Pull request merged**
