### PR TITLE
[WIP] Changes to reconcile PRs #24264 -> #24080 

### PR DESCRIPTION
**Pull request by brienneK**
Overview
----------------------------------------
See conversations on PRs [#24264](https://github.com/civicrm/civicrm-core/pull/24264) and [#24080](https://github.com/civicrm/civicrm-core/pull/24080/files)

Before
----------------------------------------
Selection_055

After
----------------------------------------
Selection_056

Technical Details
----------------------------------------
`'joins'` was changed to `'_joins'` in AbstractProcessor.php, Submit.php, FormDataModel.php (and the previously changed one's in AfformSubmitEvent.php that were originally a part of #24264.

Also added a recursive function in Submit.php to remove the `'joins'` array from `$submissionData`

Comments
----------------------------------------
This is a work in progress to test that the reconciling changes do not break any other functionality

### CODE REVIEW

**Comment by colemanw** [comment]
@briennekordis is this a mix of the two PRs?

**Comment by briennekordis** [comment]
@coleman, yes it is (with some additional changes from `'joins` to `'_joins'` in the files mentioned above), but mostly for the purpose of seeing if those changes pass the checks and to test to make sure it doesn't break any other functionality.

**Comment by colemanw** [comment]
@briennekordis I think what this really needs is unit test coverage. I'm going to work up another PR that combines all of the above plus unit tests.

**Comment by colemanw** [comment]
I've combined this into https://github.com/civicrm/civicrm-core/pull/24264

**Pull request closed without merging**
