### PR TITLE
fixes core#3661: Don't check API permissions in CRM_Mailing_BAO_Mailing::getGroupNames()

### PR DESCRIPTION
**Pull request by MegaphoneJon**
https://github.com/civicrm/civicrm-core/pull/23820 but against the rc.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
now it is

**Comment by eileenmcnaughton** [comment]
does this affect stable?

**Comment by MegaphoneJon** [comment]
I also don't know that this should be reverted - but since it *is* a regression, I'm going to go ahead and do so.

**Comment by totten** [comment]
On a conceptual level, I was originally hesitant about this. After grepping for `getGroupNames()`, I am +1 for this patch - ie it should use unpermissioned lookup.

* In `civicrm-core.git`, `getGroupNames()` is *only* used as a helper for generating tokens during a mail-blast. 
* If (counterfactually) `getGroupNames()` was used in *other ways* (such as a web-UI where the end-user can opt-in/opt-out of mailing-groups), then you would want the list of names to be filtered based on finer permissions. It's a plausible-sounding hypothetical.
* As a factual matter, `getGroupNames()` only supports token-processing for mail-blasts - which is different context.
* There is a subjective business-decision whether to reveal a group-name as part of the message-content... but IMHO that decision is entirely in the hands of the email-author. They exercise that decision by choosing to include `{mailing.group}` (*or choosing to copy-paste the name of the recipient group - which they can do*).
* It seems to me that the security context of the cron-agent is essentially arbitrary -- a funny but necessary detail that arises from how Civi+CMS permission-systems are stapled together. The email-author's decision is more meaningful.

**Comment by eileenmcnaughton** [comment]
I've merged this - but @MegaphoneJon - I think you should ALSO update your code to call the api directly rather than rely on this function

**Pull request merged**
