### PR TITLE
Allow confirm_email_text to be an html token

### PR DESCRIPTION
**Pull request by pbarmak**
Resolves https://lab.civicrm.org/dev/core/-/issues/5027

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
jenkins add to whitelist

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
these were my comments from gitlab

image

**Comment by eileenmcnaughton** [comment]
The alternative is to fully convert the field - https://github.com/civicrm/civicrm-core/pull/29532

**Comment by eileenmcnaughton** [comment]
Hey we fixed this by converting the field to be html so we can close this now https://github.com/civicrm/civicrm-core/pull/29532 is merged

**Pull request closed without merging**
