### PR TITLE
present friendlier error message if petition cannot be displayed.

### PR DESCRIPTION
**Pull request by jmcclelland**
Overview
----------------------------------------
Provide a friendlier error message if a petition cannot be displayed for some reason.

Before
----------------------------------------

If a user clicks on a link to a petition that either doesn't exist, is disabled, or the link doesn't have a sid parameter - the user is redirected to the home page with an error message.

However, the home page may not be accessible to a non-logged in user, so instead of seeing the error, they simply get a forbidden message. Also, depending on how the theme is configured, they may get a page with a different theme than the petition page should display.

After
----------------------------------------

Instead of redirecting the user, display the petition page but without any of the petition elements. If the user has access to sign a petition, then they will stay on the page and get the friendly error message displayed.

Technical Details
----------------------------------------

The old code uses the `CRM_Core_Error::statusBounce()` call. That is replaced with a `$session->setStatus()` call. I wasn't sure if there is an existing way to get quick form to bail on displaying a form so I added a class variable. Maybe there is a better way?!?

### CODE REVIEW

**Comment by demeritcowboy** [comment]
> I wasn't sure if there is an existing way to get quick form to bail on displaying a form so I added a class variable.

Historically it was CRM_Core_Error::fatal(), which was always available to all users/anonymous. But it's not very pretty/friendly either. But the concept of such a page seems like the right concept for this situation. You can get a similar thing with `throw new CRM_Core_Exception()`, but again not pretty/friendly, especially for the message about "petition no longer active". The others are unusual cases so the page wouldn't be seen that often, so for those throwing an exception seems fine. And maybe good enough for "no longer active" one for now, since then at least they see something?

**Comment by jmcclelland** [comment]
Thanks for the feedback @demeritcowboy  - the real goal of this merge is to avoid the confusion on the "no longer active" petitions. 

I'm strongly encouraging our groups to disable petitions after the campaign is done (since these forms become spam magnets). However, I'm getting resistance to disabling them because when they are disabled, the groups gets a steady stream of concerned email messages from people who clicked on the link and get a forbidden message. The group gets tired of these emails so they re-enable the petition.

**Comment by demeritcowboy** [comment]
Maybe could do it like how event info pages work when the event has passed? There's already something similar in the petition template here: https://github.com/civicrm/civicrm-core/blob/fd44ba5a1b8166cb7930947a41ac96ae186674a6/templates/CRM/Campaign/Form/Petition/Signature.tpl#L27-L29

So in the php don't bounce but assign something, then in the tpl display a message.

```php
$this->assign('isActive', $this->petition['is_active']);
```

```
{if !$isActive}
  {ts}This petition is no longer active.{/ts}
{else}
  ... rest of template...
{/if}
```

**Comment by jmcclelland** [comment]
Thanks for the suggestion! I just submitted a [new PR](https://github.com/civicrm/civicrm-core/pull/26446).

**Pull request closed without merging**
