### PR TITLE
CRM-20792: Use CiviCRM Import to remove data from a Contact field.

### PR DESCRIPTION
**Pull request by agilewarealok**
Overview
----------------------------------------
When perform import contact (update) with the empty column in csv file, expect that it should remove data from a Contact field. Looks like the importer skips columns which have an empty value. So, if you want to remove incorrectly set Email fields (eg. home location) being able to import a blank value into that field would be a great way to quickly fixing your data. 

Steps to reproduce the issue:
1. Import a contact with two emails (home & work)
2. Import the same contact with work email value as blank. (With Update on Duplicate condition)
3. Open contact page, You would see work email is still not removed.

Before
----------------------------------------
Import feature was not removing the fields which were passed empty explicitly. This is true for blocks (emails, ims, phones and open ids)

After
----------------------------------------
Now import will remove the block values if passed empty explicitly.

Technical Details
----------------------------------------
Written unit test for this to prevent test case getting failed in future releases.

_Agileware ref: CIVICRM-554_

---

 * [CRM-20792: SUP-1709 Cannot use CiviCRM Import to remove data from a Contact field.](https://issues.civicrm.org/jira/browse/CRM-20792)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins add to whitelist

**Comment by eileenmcnaughton** [comment]
I have just discussed this & I'm happy  that it has a unit test & Justin has confirmed that this is a recent regression rather than a change. It regressed in a recent 4.7 release (around 4.7.20) and I'm also happy that the code looks clean & well written

**Comment by eileenmcnaughton** [comment]
ie. I'm happy to merge this once UI tested

**Comment by mlutfy** [comment]
jenkins, test this please

(I'm lazy and I want a test site)

**Comment by jusfreeman** [comment]
Can we get this PR merged? @eileenmcnaughton or @seamuslee001

**Comment by eileenmcnaughton** [comment]
OK - so I guess I'm still feeling nervous about whether this would blank fields people didn't intend to be blanked. How do we distinguish between 'I don't have this info for this contact right now' vs 'I want to blank this info for this contact' - a 'keyword' in the field seems safer.

I would think @Stoob @agh1 @lcdservices @petednz would all be knowledgeable on what import functionality should do

**Comment by jusfreeman** [comment]
@Stoob Surely for the example you provided, you would use the "Fill" option for the import. Existing data would remain as is, missing data added.

You could also perform an export of the data you wanted to keep, then re-import that data again, just those fields if you were concerned about potential data loss.

If you are performing an "Update" import and the row being imported has empty values, then those values should be imported. Otherwise, how would you be able to clear out incorrect values in bulk?

Consider the example where phone numbers have incorrectly been imported as "home phone" when it should have been "work phone". Using the "Update" import and this PR you could fix that problem fairly easily, remove "home phone" values, import "work phone" values. Without this PR, I'm really not sure what you would do.

This particular example occurs regularly as a problem in CiviCRM due to the selection of "home phone" (or whatever) as the default. It only takes one instance where that is missed and BAM! Data is in the wrong fields. Not great.

It's kinda weird that CiviCRM treats and empty value on import the way it does. I've not seen this type of behaviour in any other software, ever.

Then again, I'm probably biased as we funded this PR due to many support requests from our customers wanting this problem in CiviCRM addressed.

**Comment by jusfreeman** [comment]
@Stoob Happy to discuss alternative approaches. At the end of the day, we just want this problem fixed.

**Comment by eileenmcnaughton** [comment]
@colemanw pinging you in

**Comment by eileenmcnaughton** [comment]
So I think we have
screenshot 2018-03-27 20 06 50
1) skip - no import
2) update - update the contact with any data-containing fields in the csv
3) update including overwriting blank fields, update the contact with any field in the csv 
4) fill - add data where the import has data but the contact does not, skip where the contact has data
5) no duplicate checking, add new contact

I'm struggling a bit to think of the right wording - but it seems like a fairly acceptable way to meet both needs
screenshot 2018-03-27 20 13 28


I suspect that currently if you enter 'null' in the csv field it *may* have the effect of blanking out data - but not sure.

**Comment by Stoob** [comment]
Here are some wording possibilities:
1. "Safe Update" vs. "Full Update"
2. "Update" vs. "Update and Erase"
3. "Update" vs. "Update with Blanks"

**Comment by agh1** [comment]
I agree completely with @Stoob that this should be a new and clearly distinct option from Update.

However, I think the name should be completely distinct too.  If we were to rename Update at all, it would be more confusing, so Update should keep its current name and behavior.  Meanwhile, it would be good to make sure the new option doesn't have "update" in its name.  Here are some ideas:

- Replace
- Obliterate
- Displace
- Supplant

It would also be helpful to put Fill, Update, and the new option in that order so as to give an indication of how assertive the importer should be:

- Fill: trust the import so long as the DB has no value
- Update: trust the import so long as the import has a value
- Obliterate: trust the import even if the import value is blank

One final thought: what is the intended behavior when you import a blank value to Home Phone and there are two or more Home Phone numbers?  Does it wipe out one at random or should it take them all out?

**Comment by agh1** [comment]
@jcorlew had a brilliant idea--[CRM-15522](https://issues.civicrm.org/jira/browse/CRM-15522) to the rescue!

If you import using Update and put the value `NULL` in a field, it will wipe it out.  Just make sure that you don't use proper capitalization: there's a [hack in CiviCRM](https://github.com/civicrm/civicrm-packages/pull/79) we added to help out poor Mr. Null who had that issue.

The only other hiccup is that you can't use it for email because "NULL" is not a properly-formed email address.

Now, I don't know if we should be codifying this quirk of DB_DataObject, but it should serve your needs (and I wouldn't be opposed to adding a special case in the import validation that allows `NULL` as an email address).

**Comment by Stoob** [comment]
I like "Replace" or "Erase" best.   Example..
- Update: Updates database fields with available import data.  Fields in the database will be left as-is if those fields are NOT included in the import or if an import data row is empty.
- Replace : Replace and/or erase any database fields with the import data even if the import row is empty.

**Comment by eileenmcnaughton** [comment]
I'm going to close this because it's stalled on the proposal being agreed rather than code review. It is still tracked through the JIRA issue & if you want to work more on the proposal @jusfreeman  you should open a gitlab issue to track it (& close JIRA)

**Pull request closed without merging**
