### PR TITLE
CRM-20615 Export only those batches whose status is exported

### PR DESCRIPTION
**Pull request by pradpnayak**
----------------------------------------
* CRM-20615: Export only those batches having status Exported
  https://issues.civicrm.org/jira/browse/CRM-20615

### CODE REVIEW

**Review by monishdeb — APPROVED** [review]
Tested, working fine.

@colemanw / @eileenmcnaughton can you please review and merge this PR? Thanks!

**Comment by eileenmcnaughton** [comment]
@monishdeb the code looks fine & I agree it does what is described.

I'm not sure I understand enough to judge if what is described is a correct change & just constitutes a bug fix -  @lcdservices or @agileware might be able to confirm for me? Or Guy I - who I can't ping from github I don't think

**Comment by lcdservices** [comment]
Tested and confirmed. Created a batch and added transactions to it. While in Open status, selected Export action. The file was exported and the batch was correctly changed to the Export status. This was addressing a mismatch between the batch status (Exported) and the generation/download of the export file.

**Comment by JoeMurray** [comment]
So from my perspective, we should change the status to exported after, not before, the export is done. Things fail, especially potentially long running tasks and file downloads.

**Pull request merged**
