### PR TITLE
[REF] Remove unused params from function signature for getACLs

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Improves code readability by removing unnecessary parameters

Before
----------------------------------------
```
public static function getACLs($contact_id = NULL, $group_id = NULL, $aclRoles = FALSE)
```
 - this is only called once with the values for group_id being NULL & aclRoles being TRUE

After
----------------------------------------
```
public static function getACLs($contact_id = NULL) {
```

Technical Details
----------------------------------------
It turns out this function is only called once & the second 2 parameters are hard-coded so we don't need them

Comments
----------------------------------------
This also makes the groupID unnecessary for getACLRoles but will wait on https://github.com/civicrm/civicrm-core/pull/16174 to fix.

### CODE REVIEW

**Comment by seamuslee001** [comment]
Change looks good i confirmed by grep that this was the only place it was being called from merging

**Comment by totten** [comment]
I also did a read-through and the refactoring does look to be equivalent to inlining the typical inputs.

**Comment by eileenmcnaughton** [comment]
Yeah - there is some bad stuff in the ACL code (ie bad join on option group ) that contributes to the deadlocks but the code is so unreadable it has survived. I have been thinking about the caching of metadata & apiv4 though. We are increasingly caching some metadata entities like membershipType - but I have been wondering if that could also cover option values & if apiv4 could use the cached data where available or appropriate (rather than create constructs like the getMembershipType function)

**Comment by eileenmcnaughton** [comment]
Follow up to remove from the downstream fn https://github.com/civicrm/civicrm-core/pull/16180

**Pull request merged**
