### PR TITLE
Update more Portugal provinces

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
Followup to https://github.com/civicrm/civicrm-core/pull/17106

Comments
----------------------------------------
@mattwire @pradpnayak

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Fail is unrelated but I will kick off again to give it an appealing green tick. I want @mattwire to review this as he will be able to tell at a glance if the names are correct now

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
(code changes look right)

**Comment by mattwire** [comment]
Thanks @demeritcowboy

**Pull request merged**
