### PR TITLE
Don't crash if we are recording a contribution, outbound email is disabled and we try to send a receipt

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Set "Outbound Email" to disabled.

Then:
Trigger `CRM_Contribute_BAO_Contribution::completeOrder()` eg. by recording a payment on a contribution that completes an order and you request a receipt (ie. set `is_send_email_receipt` to TRUE on API3 Payment.create which is the default..).

Before
----------------------------------------
Crash, it all falls over.

After
----------------------------------------
You get a helpful message in the logs:
`[warning] Contribution 615632 Failed to send receipt: Outbound mail has been disabled. Click [Administer >> System Setting >> Outbound Email](https://[removed.org]/civicrm/admin/setting/smtp?reset=1) to set the OutBound Email.`
and it all continues to process (except for sending the receipt, obviously, as email is disabled).

Technical Details
----------------------------------------
Why on earth we have `statusBounce()` right down in CRM_Utils_Mail we'll never know. And even better, only if you select certain options. Otherwise it'll do something sensible, like, throw an exception.

But even if you throw an exception we don't catch it and it goes all the way back up the stack. So we wrap a try/catch around the send email bit since it seems pretty reasonable to allow an email to fail and still record the fact that you've got some money properly (technically it does record a contribution but then fails with any other bits, eg custom fields and post processing).

Comments
----------------------------------------
Why do I always fall down the rabbit holes?

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
It looks like our test suite is pretty wedded to the crash

**Comment by eileenmcnaughton** [comment]
Change looks good but you have not yet slain the test dragon

Civi\FlexMailer\ConcurrentDeliveryTest::testMailNonProductionRun
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'civiExit called'
+'Outbound mail has been disabled. Click <a href='/index.php?q=civicrm/admin/setting/smtp&amp;reset=1'>Administer >> System Setting >> Outbound Email</a> to set the OutBound Email.'

/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/tests/phpunit/api/v3/JobProcessMailingTest.php:286
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:291
/home/homer/buildkit/extern/phpunit9/phpunit9.phar:2307

**Comment by demeritcowboy** [comment]
I think also you'll want to catch it on the email activity form and then bounce there, because otherwise you get this instead of the popup alert:

untitled3

**Comment by mattwire** [comment]
@demeritcowboy How do you get to the email activity form when outbound email is disabled?

**Comment by demeritcowboy** [comment]
From the main menu: Contacts - New Email

**Comment by mattwire** [comment]
> From the main menu: Contacts - New Email

So simple... I've added an exception handler

**Comment by demeritcowboy** [comment]
You can also send emails from Manage Case, and this works there too. 👍

**Comment by demeritcowboy** [comment]
Looks like a couple more test fails still:
* Civi\FlexMailer\ConcurrentDeliveryTest
* api_v3_JobProcessMailingTest

**Pull request merged**
