### PR TITLE
CRM-19034 revert the capitlisation of country names

### PR DESCRIPTION
**Pull request by seamuslee001**
@eileenmcnaughton @mlutfy Folks how does this look?

---
- [CRM-19034: Remove line that makes all countries upper case](https://issues.civicrm.org/jira/browse/CRM-19034)

### CODE REVIEW

**Comment by colemanw** [comment]
Nicely done @seamuslee001

**Comment by mlutfy** [comment]
@colemanw Country name translation happens in gettext. The civicrm_country names must always be in English. If people modified them manually as part of some hack, they're on their own.

+1 on the solution! Thank you  @seamuslee001 !!

**Comment by eileenmcnaughton** [comment]
@mlufty can you be explicit if you have reviewed a patch and it is OK to merge? I think that is what your above comment means

**Comment by mlutfy** [comment]
@eileenmcnaughton Yep, patch reviewed and OK to merge. Sorry about that, bad habit :)

**Comment by seamuslee001** [comment]
I've fixed the countries i have missed, the countries with non english characters appear to be doing something strange on my local db but I think the upgrade script is ok, I have also patched the civicrm_country template file

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Pull request merged**
