### PR TITLE
CRM-19129 Allow Users to Select the From Address used for when sendin…

### PR DESCRIPTION
**Pull request by seamuslee001**
…g Email Receipts

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by monishdeb** [comment]
@eileenmcnaughton can you please merge this PR after test. The pr for master is already been tested by jitendra and later merged.

**Comment by eileenmcnaughton** [comment]
I've added merge on pass - but there is a conflict ATM 
                                                                                     
  [GitScan\Exception\ProcessErrorException]                                          
  Process failed:                                                                    
  [[ COMMAND: git apply --check --ignore-whitespace ]]                               
  [[ CWD: /home/jenkins/buildkit/build/core-8758-4v1x7/sites/all/modules/civicrm ]]  
  [[ EXIT CODE: 1 ]]                                                                 
  [[ STDOUT ]]                                                                       
  [[ STDERR ]]                                                                       
  error: patch failed: tests/phpunit/api/v3/CustomValueTest.php:48                   
  error: tests/phpunit/api/v3/CustomValueTest.php: patch does not apply

**Comment by monishdeb** [comment]
Cool :)

**Pull request merged**
