### PR TITLE
CRM-16835 Added fix to allow contributions with Partially paid status…

### PR DESCRIPTION
**Pull request by Edzelopez**
… to be Completed

---
- CRM-16835: Support changing contributions with partially paid status to completed.
  https://issues.civicrm.org/jira/browse/CRM-16835

### CODE REVIEW

**Comment by kurund** [comment]
jenkins, test this please

**Comment by pradpnayak** [comment]
jenkins, test this please

**Comment by davecivicrm** [comment]
Jenkins, test this please

**Comment by davecivicrm** [comment]
Test failures unrelated.

**Pull request merged**
