### PR TITLE
CRM-21546: Implement unique opens filter for mailing opened report

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
This ticket is about adding Yes/No filter called 'Unique Opens' to mailing opened report to list out unique open mailings.

---

 * [CRM-21546: Implement unique opens filter for mailing opened report](https://issues.civicrm.org/jira/browse/CRM-21546)

### CODE REVIEW

**Comment by monishdeb** [comment]
ping @lcdservices @colemanw

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by lcdservices** [comment]
@monish this is not working. Here are the issues:

- when unique opens is selected, the group by statement has too many fields. specifically -- it groups by mailing_event_opened_civireport.id and mailing_event_opened_civireport.time_stamp -- both of which are not contact/email specific, and prevent unique rows
- if you remove those values from group by and also expose open date, we need to wrap open date with ANY_VALUE in the select statement -- or maybe MIN(), so we return the first timestamp for when the email was opened.

**Comment by seamuslee001** [comment]
@lcdservices just noting Brian that ANY_VALUE isn't really a proper solution given that MariaDB doesn't support ANY_VALUE

**Comment by lcdservices** [comment]
@seamuslee001 there are some utility functions that take that into consideration. But in this case, I actually think we want MIN() so we get the first time the email was opened.

**Comment by monishdeb** [comment]
@lcdservices @seamuslee001 I have updated the PR and this is the last commit https://github.com/civicrm/civicrm-core/pull/11401/commits/6bd27fc6d226c832353fdca5dd46bb34fafa86c9 

Note that I have kept ANY_VALUE and this won't get added for MariaDB because of ```CRM_Utils_SQL::disableFullGroupByMode()```

**Comment by lcdservices** [comment]
@monishdeb this is working. no group by errors and the report correctly groups by contact ID when the unique opens filter is selected.

**Comment by colemanw** [comment]
* ([`r-jira`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-jira)) __Pass__
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __Pass__
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __Pass__
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __Pass__
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __Pass__
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __Pass__: Tested by @lcdservices 
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __Pass__: Fits normal report UI patterns.
* ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __Pass__: Standard report code.

**Pull request merged**
