### PR TITLE
CRM-16198 - Search builder fixes for search by financial type, payment i...

### PR DESCRIPTION
**Pull request by davecivicrm**
...nstrument, contribution status and contribution page.

---
- CRM-16198: Financial Type search fails when searched Contribution using Search builder
  https://issues.civicrm.org/jira/browse/CRM-16198

### CODE REVIEW

**Comment by davecivicrm** [comment]
This is a legitimate test failure. The change to Query.php results in calls to contribution get API to fail for payment_instrument / contribution_payment_instrument by 'name' , e.g.

    $contribution = $this->callAPISuccess('contribution', 'get', array(
      'sequential' => 1,
      'contribution_payment_instrument' => 'Cash',
    ));

**Comment by pradpnayak** [comment]
Submitted PR at https://github.com/civicrm/civicrm-core/pull/5528

**Comment by kurund** [comment]
test this please

**Comment by davecivicrm** [comment]
Superceded by https://github.com/civicrm/civicrm-core/pull/5528

**Pull request closed without merging**
