### PR TITLE
Afform - Fix getting and setting boolean/numeric types

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes: https://lab.civicrm.org/dev/core/-/issues/4465
Reviewer's cut of https://github.com/civicrm/civicrm-core/pull/27006

Technical Details
--------------------------------------
This ensures boolean and numeric fields always have the correct type set:
image

### CODE REVIEW

**Comment by colemanw** [comment]
Triggering the online demo to be rebuilt: Jenkins retest this please.
FYI @xavi-xaloc

**Comment by kurund** [comment]
@colemanw 

Did a quick check and the Checkbox defaults are not working for me.
Screenshot from 2023-09-11 17-15-23

**Comment by colemanw** [comment]
@kurund I reproduced... sort of. If the default is actually set, then it works. But there was a bug in the Afform_Admin GUI causing it to not be set. Fixed with 41aa7ec

Whew, this PR has been a slog. Maybe we can finally merge it!

**Comment by colemanw** [comment]
@xavi-xaloc @kurund any objection to merging this now?

**Comment by xavi-xaloc** [comment]
Sorry, @colemanw , but I can't get it work, neither locally nor in the PR link. Could you, @kurund ?

**Review by kurund — APPROVED** [review]
@colemanw @xavi-xaloc 

Latest fixes are working as expected hence, merging the PR.

Screenshot from 2023-09-14 17-19-03

**Pull request merged**
