### PR TITLE
CRM-20563 change fatal error message

### PR DESCRIPTION
**Pull request by Stoob**
CRM-10293 and CRM-20563

---

 * [CRM-20563: Improve 'unable to provide this...' error message](https://issues.civicrm.org/jira/browse/CRM-20563)
 * [CRM-10293: Change 'sorry non recoverable error' text to something nicer](https://issues.civicrm.org/jira/browse/CRM-10293)

### CODE REVIEW

**Comment by kngs** [comment]
I thought this might be a PR I could handle but thought maybe modifying the wording from "when this occured" to "what action you were performing when this occured".

**Comment by Stoob** [comment]
I'm fine with that change.  Please go ahead.  As an aside, I'm not sure if we should be commenting in GitHub or JIRA.

**Review by kngs — CHANGES_REQUESTED** [review]
Suggest following wording change (approved by Stoob):
"Sorry, due to an error, CiviCRM is unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred."

**Comment by Stoob** [comment]
@kngs I just got an important comment.  "CiviCRM" is not appropriate for people who package the software under another name: PowerBase, BlueBird, etc.  

Please replace "CiviCRM is" with "we are"

**Comment by Stoob** [comment]
I have made the final text change incorporating your suggestions @kngs and others.   ready for merge

**Comment by kngs** [comment]
Hi Stoob,
Don't know if you saw my message on MatterMost:

Hi Stoob, I'm sorry you had to make the change. I am still learning the PR system and was going to reach out to Ali, who walked me through my first PR, to make the changes. I also was trying to do a pre and post test; amazing how challenging it is to get that message when you want it!! I thought this would be an easy one but I still have a lot to learn. Is there anything else I need to do? Again my apologies for taking so long (still trying to catch up with work and life after the conference ). Karen

Do I still need to test or submit!?!?
Sorry again for being such a newbie!
Karen

**Comment by eileenmcnaughton** [comment]
Looks like @Stoob approved this to merge and as a wording change that is good enough for me!

**Pull request merged**
