### PR TITLE
Move assign of currency for entityForm outside of foreach so order of fields don't matter

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Per review comment on #13578 Move assign of currency for entityForm outside of foreach so order of fields don't matter

Before
----------------------------------------
Assign of currency won't work if currency is after the money fields

After
----------------------------------------
Assign of currency will work if currency is after the money fields

Technical Details
----------------------------------------

Comments
----------------------------------------
@eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Yep - this is the right follow up

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by mattwire** [comment]
test this please

**Comment by colemanw** [comment]
test this pleas

**Comment by colemanw** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
fail is the db not selected thing - I'm gonna merge this one since I'm pretty confident it is not affecting tests due to formy nature - if it DOES cause fails I'm sure I'll grovel

**Pull request merged**
