### PR TITLE
dev/core#974 Whitelist .ics extension

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
Adds ics file in as a whitelisted file extension

Before
----------------------------------------
.ics files saved as .unkown file

After
----------------------------------------
.ics files saved as .ics

ping @eileenmcnaughton @pfigel @Stoob

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 maybe the rc?

**Comment by seamuslee001** [comment]
have switched to RC @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
@seamuslee001 need to wrap label in 'localize'

**Comment by seamuslee001** [comment]
ok hopefully sorted @eileenmcnaughton

**Comment by seamuslee001** [comment]
Test Fail unrelated

**Pull request merged**
