### PR TITLE
[REF] extract and share code to determine if required contact fields are present

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
[REF] extract and share code to determine if required contact fields are present

Before
----------------------------------------
Identical code in activity import & participant import - a la copy & paste

After
----------------------------------------
Extracted function shared

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by demeritcowboy** [comment]
* General standards
    * [`r-explain`] __PASS__
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __PASS__
* Developer standards
    * [`r-tech`] __PASS__
    * [`r-code`] __PASS__ There some pre-existing awkward use of ts/concatenation/br.
    * [`r-maint`] ____
    * [`r-test`] __PASS__

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @colemanw ok to merge based on ^^

**Comment by eileenmcnaughton** [comment]
thanks @demeritcowboy @seamuslee001

**Pull request merged**
