### PR TITLE
dev/core#4146 Don't repeat Smarty blocks

### PR DESCRIPTION
**Pull request by larssandergreen**
Overview
----------------------------------------
[See Smarty docs](https://www.smarty.net/docsv2/en/plugins.block.functions.tpl). This works in both Smarty 2 and 3.
Have done for all blocks except one that is unused (#27619 deletes).

Tested all in Smarty 2 and 3, except the upgrade snapshot - not entirely sure how to test that, but it seems unlikely to be an issue.
{edit} is barely used (a few times in core, a couple in extensions), but actually seems like a good idea, so I left it rather than remove.

### CODE REVIEW

**Comment by larssandergreen** [comment]
@eileenmcnaughton Can you have a look at this before I go ahead and do the same for the rest of the blocks?

**Comment by eileenmcnaughton** [comment]
@larssandergreen is this currently broken with smarty 2 -or only 3? Can you tell me where I would look to see it?

**Comment by larssandergreen** [comment]
@eileenmcnaughton broken only in Smarty 3. Any crmButton will be doubled, but the first one won't have any text. For example, go to manage any contribution page, you'll see one little hamburger menu button and then the regular button beside.

**Comment by eileenmcnaughton** [comment]
@larssandergreen looks good to me - I tested on v2 & v3 & the approach makes sense (this commit & your other WIP PR  is now in the big PR too for testing on 'all the latest')

**Comment by larssandergreen** [comment]
@eileenmcnaughton These are all done now.

**Comment by eileenmcnaughton** [comment]
unrelated fail 

Test Name | Duration | Age
-- | -- | --
Civi\Afform\AfformGetTest.testAfformAutocomplete

[Test Name](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/5192/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/#)
[Duration](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/5192/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/#)
[Age](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/5192/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/#)
 [Civi\Afform\AfformGetTest.testAfformAutocomplete](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/5192/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/(root)/Civi_Afform_AfformGetTest/testAfformAutocomplete/)

**Pull request merged**
