### PR TITLE
CRM-17854 && CRM-17685 fix - CiviCRM DB Syntax Error when enabling lo…

### PR DESCRIPTION
**Pull request by seamuslee001**
…gging

https://issues.civicrm.org/jira/browse/CRM-17685
https://issues.civicrm.org/jira/browse/CRM-17854

### CODE REVIEW

**Comment by seamuslee001** [comment]
@agileware @eileenmcnaughton This is cherry-pick of Moonish's commit,  I amended the commit to include CRM-17854

**Comment by eileenmcnaughton** [comment]
This is already in 4.7 isn't it? If so if can merge-on-pass

**Comment by seamuslee001** [comment]
yeh it is

**Comment by monishdeb** [comment]
Jenkin, test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @agileware have all the PRs this replaces been closed?

**Comment by agileware** [comment]
@eileenmcnaughton Yes.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I updated the 4.6 version into https://issues.civicrm.org/jira/browse/CRM-17854 - but should we also add 4.7 as a fix version - the ticket doesn't say it's fixed in any version as yet but I think it is ?

**Pull request merged**
