### PR TITLE
CRM-17700 allow contribution get to bypass permissions

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
This is required for wmf because tests run without a logged in user or permissions set.

Bug: T121284
Change-Id: I8ac335ed9a3316e70fe3f182a91fc2cdca450945

---
- [CRM-17700: api Contribution.get applies permissions to custom fields regardless of 'check_permission' flag](https://issues.civicrm.org/jira/browse/CRM-17700)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw I blew all my points on this :-(

BTW I feel pretty confident on this one but you should probably at least be aware of it.

**Comment by colemanw** [comment]
So if I'm reading this right, this is adding an extra param to all the `exportableFields` functions so that they can pass it along to customField retrieval. What I don't get is how this affects non-custom fields.

**Comment by eileenmcnaughton** [comment]
It shouldn't really affect them. They don't apply permissions at the field level. We do some permission field filtering at the api level against getfields - possibly only for contact?

The issue here is that custom field availability data is cached using isPermissioned in the cache string.  & low-down functions. So, if you are trying to do a non-permissioned call but that is not being passed right through to the caching function then permissions are applied regardless of your setting.

**Comment by colemanw** [comment]
Makes sense.

**Pull request merged**
