### PR TITLE
Add hook to modify 'contribution payment links'

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Let's you modify "contribution payment links" via existing hook_civicrm_links.

Before
----------------------------------------
Not possible to add/remove/modify links
image

After
----------------------------------------
Can be modified
Example:
image

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
@mattwire I don't think we exactly have a "policy" for naming, but in my grep it looks like all existing calls to `CRM_Utils_Hook::links` passes a lowercase string as the first param.

**Comment by mattwire** [comment]
@colemanw I copied https://github.com/civicrm/civicrm-core/blob/master/CRM/Contribute/BAO/Contribution.php#L1047 but that shouldn't stop us at least trying to be consistent :-) Happy to change to lowercase

**Comment by mattwire** [comment]
@colemanw Now updated to use lowercase. I've added a note to the dev docs as well although it doesn't seem to have published yet.

**Comment by mattwire** [comment]
Thanks @colemanw

**Pull request merged**
