### PR TITLE
Add option to control display of calendar links.

### PR DESCRIPTION
**Pull request by aydun**
Overview
----------------------------------------
A link to a calendar invite and 'add to Google Calendar' are shown in several places including event information, at registration and in emails.  In some situations, such links are not wanted. This PR adds an option to control whether calendar links are shown or not.

Before
----------------------------------------
Calendar links are shown for all 'public' events.

After
----------------------------------------
Calendar links are shown for all 'public' events iff the 'show_calendar_links' option is set.

Technical Details
----------------------------------------

Comments
----------------------------------------
Has test!

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@aydun check https://github.com/civicrm/civicrm-core/pull/27785 - also don't update event_offline_receipt.text.tpl  - see https://github.com/civicrm/civicrm-core/pull/27733

**Comment by aydun** [comment]
> @aydun check #27785 - also don't update event_offline_receipt.text.tpl - see #27733

Thank you!

**Comment by aydun** [comment]
@eileenmcnaughton Re these two test failures - I'm not sure whether I should be adding these to the expected output, or changing something to stop them showing up where they are not wanted.

**Comment by aydun** [comment]
Thanks @eileenmcnaughton 
Docs: https://lab.civicrm.org/documentation/docs/user-en/-/merge_requests/623

**Pull request merged**
