### PR TITLE
Upgrader (5.34) - Handle unsavable characters in decoded SMTP password

### PR DESCRIPTION
**Pull request by totten**
Overview
--------

In php-mysqli with utf8mb4, the escaping rules do not handle 8-bit characters (`chr(128)`+). ([Demo](https://gist.github.com/totten/4083741b920113ffc569d40053ce849d))

Here's a situation reported by @agileware-justin which provokes this:

> 1. SMTP credentials (mailing_backend) were saved and had been encrypted using mcrypt, prior to PHP 7.1
> 2. SMTP outbound email was NOT enabled, but the SMTP credentials are in the database
> 3. Active PHP version was PHP 7.3, without mcrypt module
> 4. CiviCRM 5.34 upgrade triggers the database error

ping @seamuslee001 @kcristiano. This is based on the discussion for #19700.

Before
------

The behavior can be viewed in two variables:

* Depending on whether `CIVICRM_CRED_KEYS` is set, the upgrader may be writing passwords as plain-text or as `^CTK?` tokens.
* Depending on what value is in `$setting['smtpPassword']`, what value is in `CIVICRM_SITE_KEY`, and whether `mcrypt` is active, we may or may not get 8-bit characters when reading the password   (`CRM_Utils_Crypt::decrypt($setting['smtpPassword'])`).

The fatal combination arises when using plain-text with 8-bit characters. But other combinations (encrypted tokens and/or 7-bit plain-text) seem
fine.

After
-----

As before, combinations involving encrypted tokens and/or 7-bit plain-text are fine.

We don't have a head-on soultion for escaping 8-bit plain-text for use with php-mysqli-utf8mb4.  (Which is insane, right?) But now we manage the symptoms better:

* If you aren't even using SMTP (like in Justin's example), then this is not legit.  We show a warning and simply discard the unneeded/corrupt value of `smtpPassword`.

    Screenshot from 2021-03-02 04-09-45

* If you are using SMTP, then this might theoretically be legit. (We haven't confirmed, but it seems plausible in other locales.) We show a different warning and encourage the sysadmin to setup `CIVICRM_CRED_KEYS` (which will enable the more permissive `^CTK?` format.)

    Screenshot from 2021-03-02 03-42-32

Comments
---------------

This is in the peculiar situation of fixing an upgrader issue for a previous release. If you hit the bug before, then you might've nudged that to make it passable (in which case - it's not longer a problem). The audience for this fix would be "people who had to roll back the upgrade" or "people in the future who run through the same upgrade step". For this group, it makes sense to fix the `5.34.alpha1` upgrader (even if the actual fix is published in 5.34.1 or 5.35.beta1.)

### CODE REVIEW

**Comment by kcristiano** [comment]
@totten This occured on 4 of the sites I upgraded.   The situation was exactly what @agileware-justin  described.

I fixed in each case by restoring, removing `mail_backend` setting and then upgrading and adding the settings back.  My suspicion was that these were all old mcrypt smtp settings that were unused and therefore never fixed.

I've now restored and re-tested two of the 4 sites and I get no errors at all with this path -- BUT -- no warnings.

So I am now baffled.   Shouldn't I get one of these alert messages?

**Comment by totten** [comment]
@kcristiano Thanks for testing. Have you, per chance, added `CIVICRM_CRED_KEYS` to `civicrm.settings.php` in the intervening period? (If it was added -- then that would explain both the report above and the incongruous success in #19700.)

My expectation is:

* If `CIVICRM_CRED_KEYS` is omitted, then the storage medium rejects 8-bit chars and we get the error. Since this can't be saved, it should now give the upfront warning and should ultimately drop the unsaveable value.
* If `CIVICRM_CRED_KEYS` is defined with a new key, then the storage medium works differently (`^CTK?k=<ID>&t=<base64>`), and it accepts 8-bit chars. Since it can be saved, it doesn't complain.

The nub is that... since this is open-source... it's hard to say that nobody ever found a legit use for an 8-bit char in `smtpPassword`. (I don't think it's likely they did... but people do unlikely things all the time...) In my testing, it was already saving successfully for that scenario, and I'm OK with leaving that as a hedge against the unknowable.

Of course, we could still show a warning-  just to say, "This looks suspicious, but we're going to preserve it anyway." As someone who's in the situation with wonky `smtpPassword` data -- would you want the notice even it was a non-fatal situation?

**Comment by kcristiano** [comment]
@totten I did not add the keys.  I used local copies of the client sites.  It makes no sense why the upgrades failed in production and work now.  

I think this PR is needed  - I just haven't been able to reproduce the original issue.  I am hoping Justin can.

**Comment by seamuslee001** [comment]
I tested this out by generating the smtp credentials using mcrypt then disabling mcrypt and trying the upgrade and replicated the failure, after restoring the db I could confirm that I got the warning and also that the upgrade succeeded and that the smtp password was blanked out as expected. I would say this works.

I also tested  a straight base64encoded password (i.e. SMTP password created before 5.34 but no mcrypt involved) and confirmed I didn't get the warning and also that the password was correctly updated so I would say this works as intended and should be included in the 5.35 release merging

**Comment by totten** [comment]
Excellent. Thanks @kcristiano @seamuslee001

**Comment by agileware-justin** [comment]
Looks good to me and should help avoid nasty upgrade stress for other people in the CiviCRM community. Good one :+1:

**Comment by agileware-justin** [comment]
Related Gitlab, https://lab.civicrm.org/dev/core/-/issues/2258

**Pull request merged**
