### PR TITLE
(WIP) Fix PayPal test as it appears contributions are now getting set to be…

### PR DESCRIPTION
**Pull request by seamuslee001**
… completed and not pending

@totten @eileenmcnaughton @monishdeb @jitendrapurohit I'm not sure why this has happened but this fixes the test errors we have been seeing

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
hmm that gives me the heeby jeebies - can we see what commit started it failing?

**Comment by monishdeb** [comment]
Unable to find the commit but as per the PR's test build failure it started to fail 6 days ago - 9th Sept. And this unit test ```testSubmitCreditCardPayPal``` was introduced in 22nd Aug. Don't what causes it to fail

**Comment by monishdeb** [comment]
Morever I gone through the entire workflow where it interacts with paypal for CC payment ( here https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/Payment/PayPalImpl.php#L995 ) 
and I found clean ```$response``` for desired unit test 

```{"receiverbusiness":"sunil._1183377782_biz@webaccess.co.in","receiveremail":"sunil._1183377782_biz@webaccess.co.in","receiverid":"BNCETES6EECQQ","payerid":"DNU49C86RUU2A","payerstatus":"unverified","countrycode":"US","addressowner":"PayPal","addressstatus":"None","invnum":"ef3bbe9423598e7068fe054dfa3b83e2","salestax":"0.00","timestamp":"2016-09-15T13:38:56Z","correlationid":"6bb0ea10a1bfd","ack":"Success","version":"3","build":"000000","firstname":"Junko","lastname":"Adams","transactionid":"71Y80036DE2246723","receiptid":"2330-9021-1299-9705","transactiontype":"webaccept","paymenttype":"instant","ordertime":"2016-09-15T13:38:53Z","amt":"50.00","feeamt":"1.75","taxamt":"0.00","currencycode":"USD","paymentstatus":"**Completed**","pendingreason":"None","reasoncode":"None","l_name0":"Contribution submitted by a staff person using contributor's credit card","l_qty0":"1","l_taxamt0":"0.00","l_currencycode0":"USD","l_amt0":"50.00"} ``` . So I think this PR can be merged @eileenmcnaughton ?

**Comment by totten** [comment]
I have no idea what the correct behavior is here... but a fun fact...

I checked out copies of `4.7.10` and `4.7.9` and ran the tests - it reports the same problem as `master` (` CRM_Contribute_Form_ContributionTest::testSubmitCreditCardPayPal -- incorrect count returned from Contribution getcount`).

**Comment by colemanw** [comment]
This one failing test is really harshing my mellow when reviewing PRs. Could we just mark it as incomplete for now?

**Comment by seamuslee001** [comment]
@colemanw I have just fired in a PR to do that https://github.com/civicrm/civicrm-core/pull/9144 I will then update this PR to be based off that i.e. removing marking as incomplete but i think we should keep this PR alive whilst Eileen gets a chance to investigate if this is a legit change to the test suite or something else is up

**Comment by colemanw** [comment]
Tests are now passing. Do we still need this PR?

**Comment by seamuslee001** [comment]
@colemanw i believe we do as we are currently just skipping this test, We need to work out if this is indeed a change to the test or not and get the test re-running

**Pull request closed without merging**
