### PR TITLE
dev/core#3083 getNonDeductibleAmountFromPriceSet should take into account the financial type of the price field option

### PR DESCRIPTION
**Pull request by herbdool**
Fixes https://lab.civicrm.org/dev/core/-/issues/3083

### CODE REVIEW

**Comment by BettyDolfing** [comment]
Test this please

**Comment by BettyDolfing** [comment]
Test this please

**Comment by jaapjansma** [comment]
* General standards
    * Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
        * __PASS__ : The goal/problem/solution have been adequately explained in the PR.
        * __COMMENTS__: However it is a complicated topic. 
    * User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
        * __ISSUE__: We would expect that on the price set field level the field for non-deductible amount would be hidden when the checkbox at Tax-Deduction at the financial type is unchecked. 
    * Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
        * __PASS__: The changes do not require documentation.
    * Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
        * __PASS__: We tested this in dmaster and in the test environment of this PR. 
* Developer standards
    * Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
        * __PASS__: The change preserves compatibility with existing callers/code/downstream.
    * Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
        * __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
    * Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
        * __PASS__: The change is trivial enough that it does not require tests.
        * __COMMENTS__: Improving test coverage for all those edge case would be a nice addition to make sure the financials keep working as expected in CiviCRM. But not a hard requirement. 
    * Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
        * __PASS__: The test results are all-clear.

@herbdool are you able to hide the non-deductible field on the price set field when the financial type is not deductible?

**Comment by herbdool** [comment]
@jaapjansma is there a standard way to hide or disable fields in CiviCRM? I suppose this only needs to be set on page load so no need for JS here. In the template?

**Comment by jaapjansma** [comment]
I believe adding a css class `hiddenElement` makes it invisible. As the user can change the drop down for financial type the field should be hidden or visible depending on the selection. So I do think you need JS.

**Comment by eileenmcnaughton** [comment]
I'm closing this out because it is stale - but I took a look at the ticket & it seems like a there is not 100% agreement on this. I did suggest that maybe adding a system check would provide some protection against mis-configuration without risking affecting sites that might not think this is a bug

**Pull request closed without merging**
