### PR TITLE
CRM-20242 - Add developer Tab to Activity Detail report

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
* [CRM-20242: Add developer Tab to Activity Detail report](https://issues.civicrm.org/jira/browse/CRM-20242)

### CODE REVIEW

**Comment by yashodha** [comment]
tested, works fine

**Comment by eileenmcnaughton** [comment]
thanks @yashodha !

**Comment by JoeMurray** [comment]
Nice to see such gardening/standardization.

**Comment by eileenmcnaughton** [comment]
Yeah, being able to capture the queries easily makes is easier to debug the reports

**Pull request merged**
