### PR TITLE
dev/core#94 Advanced Search "Display Results As" always displays contact tasks on first search

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
To reproduce:

1. Open Advanced Search.
1. Select "Display Results As" = Memberships (anything other than "Contacts").
1. Search.
1. Task list shows tasks for contacts.

Task list should show tasks for memberships, it will do the second time it is loaded but it ignores the "searchPane" parameter that is passed in via $_REQUEST which is needed to identify the entity type on first load.

https://lab.civicrm.org/dev/core/issues/94

Before
----------------------------------------
Wrong task list is loaded if first advanced search is not displaying results as contacts.

After
----------------------------------------
Correct task list is loaded each time.

Technical Details
----------------------------------------
Because the "Display Results As" parameter is being ignored it is loading the default task which is contacts.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire check this PR by @jitendrapurohit https://github.com/civicrm/civicrm-core/pull/12005 - seems we need to make sure they BOTH stay fixed!

**Comment by mattwire** [comment]
Ok, I've commented on #12005 - that fix is just masking the real issue and re-introducing this issue.  The real issue is that the code is calling `CRM_Contact_Form_Search::setModeValues()` multiple times (and in different orders depending on the code path/type of search) with different `self::$_selectorName` values but only the first one will be used because the function has a static cache.  Removing the cache fixes both @jitendrapurohit issue with custom searches and my (re-introduced) issue with advanced search.  A more advanced fix to untangle the different selectors and multiple callers would be a *much* larger exercise that I don't think we have developer or reviewer time for right now... so if @jitendrapurohit can confirm that this issue in #12001 and #12005 is still fixed with this PR and someone can test the issue reported here it would be good to get this fix into core.

**Comment by eileenmcnaughton** [comment]
Ok thanks - @jitendrapurohit are you able to review this - would be good to merge it before the rc is cut given it's a recent regression. @jitendrapurohit  - If you feel confident about this we should merge to 5.1 before it is cut as it an intra rc regression as described above.

(note I'd rather drop a point release fix to 5.1, or delay to 5.2  than rush this if there is any doubt -ping @totten )

**Comment by eileenmcnaughton** [comment]
"
Remove static caching from setModeValues() as it's called multiple ti…

…mes with different selectors which causes issues with final search results"

LOL and because we are caching a static array

**Review by jitendrapurohit — APPROVED** [review]
Tested and confirmed the fix here works for both the linked issues. Advanced search pane and custom searches work fine after this changes. +1 to get this merged into the latest release @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit if you are still about can you do a PR against 5.1 & I will merge (since I think Matt is / should be asleep)

**Comment by jitendrapurohit** [comment]
@eileenmcnaughton submitted https://github.com/civicrm/civicrm-core/pull/12071

**Comment by eileenmcnaughton** [comment]
Closing this as @jitendrapurohit submitted it to 5.1 & it is now merged via that branch - thanks @mattwire @jitendrapurohit

**Pull request closed without merging**
