### PR TITLE
CRM-16929 fix hiding on zero dollar contribution pages & events

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
- [CRM-16929: Selecting a zero event price should remove billing block](https://issues.civicrm.org/jira/browse/CRM-16929)

### CODE REVIEW

**Comment by davecivicrm** [comment]
This PR completely breaks front-end (online) event registration in my testing. The Payment Block fields are NEVER shown in the form regardless of 'total amount'.

**Comment by eileenmcnaughton** [comment]
It looks like the issue was the assumption that allowConfirmation would be set regardless of whether approval was required.

Changed to

    if (!$this->_allowConfirmation && $this->_requireApproval) {
      $this->_defaults['bypass_payment'] = 1;
    }

Note - the failing test seems to be an infra thing and I was unable to edit the event fees because on my master my event price sets have no financial_type_id (this may or may not be a valid config since it's a local env) .

They were be excluded by a query introduced in the financial type ACLs 
 SELECT
       DISTINCT ( price_set_id ) as id, s.title
    FROM
       civicrm_price_set s
       INNER JOIN civicrm_price_field f ON f.price_set_id = s.id
       INNER JOIN civicrm_price_field_value v ON v.price_field_id = f.id
    WHERE
       is_quick_config = 0  AND s.is_active = 1  AND s.extends LIKE '%1%'  AND s.financial_type_id IN (3,1,4,2) AND v.financial_type_id IN (3,1,4,2)  GROUP BY s.id

**Comment by davecivicrm** [comment]
Jenkins, retest this please.

**Comment by eileenmcnaughton** [comment]
whew

**Pull request merged**
