### PR TITLE
dev/core#3133 - Extend Authx functionality to support validation of externally generated JWTs

### PR DESCRIPTION
**Pull request by anthonyblond**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/3133

Before
----------------------------------------
Authx,when processing a Bearer token, expects the scope claim to be "authx" and the sub claim to be "cid:{thecontactid}", as generated by civicrm itself.

After
----------------------------------------
Other extensions can override the handling of scope and sub claims. For example it would enable this extension to work: https://github.com/australiangreens/civiauth0jwt

Technical Details
----------------------------------------
A symphony event 'civi.authx.jwtclaimscheck' is dispatched, being a new JwtClaimsCheckEvent. An extension listening to this can read the (decoded) claims and as call rejectScope(), acceptScope(), rejectSub() and acceptSub() as required. The AuthX authenticator checks if any overrides are present and uses them instead of the default behaviour.

Comments
----------------------------------------
Very happy for feedback on improvements/changes to this. This is my first contribution to civicrm-core.

### CODE REVIEW

**Comment by johntwyman** [comment]
Here's [the link to the Civi gitlab issue](https://lab.civicrm.org/dev/core/-/issues/3133) for reference.

**Comment by seamuslee001** [comment]
Jenkins add to whitelist

**Comment by anthonyblond** [comment]
The style issues are in the JwtClaimsCheckEvent class, I'll fix that to match https://docs.civicrm.org/dev/en/latest/standards/

**Comment by colemanw** [comment]
@anthonyblond a good trick is to type the command `civilint` after you've made changes and before you type `git comit` - that will tell you if there will be any style errors and you can fix them before submitting the PR.

**Comment by totten** [comment]
@anthonyblond I think this is great idea. It sounds like this bridges a gap/"impedance mismatch" in the JWT schema supported by (a) an external provider (eg `auth0.com`) and (b) the `authx` extension.

I've been going back/forth about the signature of `JwtClaimsCheckEvent` -- it places a lot of emphasis on `sub` and `scope`. But if the JWT originates externally, then the token could be structurally different. For example, Microsoft's auth system reports the fields [`upn` ("user principal name") and `verified_primary_email`](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims) -- an org using MS tokens might prefer to match identities based on `upn` or `verified_primary_email`.  `acceptSub` and `rejectSub` sound a little too specific.

Relatedly, I feel like it would be good to split-out some of authx's default checkers as separate listeners. This would give more options so that new listeners can have higher/lower priorities -- or you might even remove default listeners -- or accept tokens in alternative formats (eg non-JWT; eg JWT signed differently).

On a basic level, `authx` receives a string (`Basic FOO:BAR` or `Bearer ASDF`), and all it really needs to know is the identity of the authenticated user-principal.

What would you think of doing an even where it would also work for the existing checks? Maybe something like https://github.com/civicrm/civicrm-core/compare/master...totten:master-check-event?expand=1. (I haven't tested that, and there are a couple small FIXMEs where it'd be useful to copy-in bits from `JwtClaimsCheckEvent`.)

**Comment by anthonyblond** [comment]
@totten Good point, it is overly focused on sub and scope.

I like the idea of generalising it. I was a bit worried about what would happen with multiple listeners. Some sort of priority could solve my worries.

If I'm understanding what you've got https://github.com/civicrm/civicrm-core/compare/master...totten:master-check-event?expand=1, the approach would be for AuthX itself to listen to the events it fires - that way there is no separation of 'default' and 'custom' logic. I like it. When I made my PR I was trying to change as few things as possible, but that ended up with some issues.

**Comment by anthonyblond** [comment]
@totten Post aus election I have time to turn my attention back to this. Want to test out / fix as necessary your idea here: https://github.com/civicrm/civicrm-core/compare/master...totten:master-check-event?expand=1 as a starting point and either modify this PR or create a new one.

Before making a start on this, I wanted to confirm you haven't been doing more work on this in the meantime, or have something related in the works - don't want to step on your toes.

**Comment by johntwyman** [comment]
Hi @totten just bumping this. @anthonyblond does have capacity to have another go at this but to his question, we just want to make sure we won't be stepping over work you've done in this space since.

**Comment by totten** [comment]
@anthonyblond Big +1. I think it'll be great if you carry on with it.

(I haven't done anything besides that draft/example branch.)

**Comment by anthonyblond** [comment]
@totten I was able to use most of your suggestions directly with only small changes. I've also been able to update my [civiauth0jwt](https://github.com/australiangreens/civiauth0jwt) extension to work with the new events. It all seems to be going smoothly.

I expected the tests to need to be updated, but was working as is. I added 2 new tests in, specifically to cover expired JWTs and nonense JWTs, just to make sure something wasn't slipping through without me realising it.

Would appreciate any feedback you have :)

**Comment by johntwyman** [comment]
Hey @totten - we're wondering if you're able to find some time to review this PR. Appreciate this isn't the highest priority work by any means but we'd love to see it included in core.

We've been using this patch in our dev environment for several months now without issue. Being able to use API4 with the permissions of the calling user in a Single Sign-On context has been incredibly useful.

If there's anything @anthonyblond or I can do to help facilitate review, testing, etc., please let us know.

Cheers!

**Comment by seamuslee001** [comment]
@anthonyblond can you rebase this please and remove the changes to `ext/authx/info.xml` that is unneeded at all

**Comment by seamuslee001** [comment]
closing this in favour of the resubmission here https://github.com/civicrm/civicrm-core/pull/25952

**Pull request closed without merging**
