### PR TITLE
Add titles and icons to entities

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds titles and icons to DAO entities and expose them to APIv4 Entity::get.

Before
----------------------------------------
No consistent way to fetch localized titles and icons for every entity.

After
----------------------------------------
Now there is.

Comments
----------------------------------------
Another step forward for search builder.

### CODE REVIEW

**Comment by colemanw** [comment]
This is kindof a large diff because it required rebuilding every DAO file... but aside from those the change isn't as big as it looks.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Test fails unrelated

**Pull request merged**
