### PR TITLE
Afform: Allow selecting case for relationship

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Allow you to specify a case for relationship. Either a fixed one or one from the form:
image

Before
----------------------------------------
Cannot specify case for relationship

After
----------------------------------------
Can specify case for relationship

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by mattwire** [comment]
test this please

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Comment by colemanw** [comment]
Good change thanks @mattwire

**Pull request merged**
