### PR TITLE
APIv4 - Ensure dataType of option id matches dataType of field

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
While investigating https://lab.civicrm.org/dev/core/-/issues/5360 I unearthed a related issue - sometimes conditional comparisons fail because the dataType of the option value doesn't match the dataType of the field.
This ensures they always match, and improves Afform conditional comparisons.

Before
----------------------------------------
Mismatch

After
----------------------------------------
Match

Technical Details
-----------------
PHP is a sloppy language when it comes to variable data types. If you ask it "which one is a number, 2 or '2'?" it will say "yes". It doesn't help that in the OptionValue table we store mostly numeric values in a varchar column, as strings. Javascript is much more strict, and doesn't consider "2" to be a number, so we get a mismatch when comparing options with field values.
This cleans up the return value of APIv4 GetFields so that fields with a numeric data type will return all option values as numeric, and vice-versa for string-type fields.

### CODE REVIEW

**Comment by colemanw** [comment]
@seamuslee001 this PR caused [a test you wrote back in 2016](https://github.com/civicrm/civicrm-core/pull/8424) to fail...
However the test makes no sense to me. It's checking the ability to create a non-numeric event_type, but that shouldn't be possible, as the field `Event.event_type_id` stores an integer & cannot possibly be non-numeric.
So I've deleted the test.

**Comment by seamuslee001** [comment]
@colemanw I think i wrote the test because there was those out there that had put in event types with strings not ids. Back then there was no enforcement of the option group data type at all. I can't recall why but there was someone who had stuffed an alpha numeric event type in

**Comment by colemanw** [comment]
@seamuslee001 I just can't figure out how that would even work. How can an integer reference a non-numeric string?

**Comment by seamuslee001** [comment]
@colemanw I don't know I suspect that MySQL was doing something odd like truncating a value or something I'm not sure but looking at the linked issue ticket someone seemed to have an issue with the way the sub type parameter was working with non numeric event type ids *shrugs*. I think its probably sane enough to remove the test now i think

**Pull request merged**
