### PR TITLE
CRM-20648, fixed validation to allow participant to register if their…

### PR DESCRIPTION
**Pull request by pradpnayak**
… previous registration is cancelled

----------------------------------------
* CRM-20648: Allow registration in event with cancelled registration
  https://issues.civicrm.org/jira/browse/CRM-20648

### CODE REVIEW

**Comment by colemanw** [comment]
I don't think this is right. Here is the full list of statuses in core which are not "counted":

- No-show
- Cancelled
- Pending (incomplete transaction)
- On waitlist
- Rejected
- Expired
- Pending in cart
- Transferred

I don't think it's appropriate to allow e.g. Rejected participants to register again.
I suggest this PR only targets the one "Cancelled" status and not the others.

@JoeMurray

**Comment by JoeMurray** [comment]
I agree with @colemanw and at most would consider reviewing the clarity of the messages provided in the other context. In particular, Pending incomplete might want to provide front end users with indication that the payment has not yet been received by payment processor, and in backend suggest that if the expected payment turn-around for the processor has elapsed, that they check with the payment processor to see if the payment has been received there and if not, contact user about arranging another payment.

**Comment by Edzelopez** [comment]
@pradpnayak or @monishdeb can you please QA recent changes?

**Comment by monishdeb** [comment]
Working fine, as expected. @colemanw can you please test this PR?

**Comment by pradpnayak** [comment]
Works fine. Can register participant if status is canceled.

**Pull request merged**
