### PR TITLE
dev/core#949 Use "text" type mysql field when exporting any id-type field

### PR DESCRIPTION
**Pull request by agh1**
Overview
----------------------------------------
This is just a freshened-up version of #12598 from @adixon .  Basically, you can't export a custom field with an integer value and a label longer than 16 characters (per [dev/core#181](https://lab.civicrm.org/dev/core/issues/181)).  This is something that can be worked around in many cases (e.g. using an Alphanumeric field type or just having a shorter label), but [with the State/Province field (and presumably Country), there's no way around it](https://lab.civicrm.org/dev/core/issues/949).  The same goes for contact reference fields.

Before
----------------------------------------
First, try a state/province field

1. Create a custom field called Favorite State with the type State/Province.
2. Create contact A with the Favorite State as "District of Columbia".
3. Create contact B with the Favorite State as "Maryland".
4. Search for contact B and export with a custom field mapping that includes Favorite State.  No problem.
5. Search for contact A and export with the same mapping.  DB Error: "Data too long for column 'custom_XX'".

Now for contact reference

1. Create a custom field called Favorite Person with the type Contact Reference.
2. Create individuals named "Alan Dixon" and "Eileen McNaughton".
2. Create contact C with the Favorite Person as "Eileen McNaughton".
3. Create contact D with the Favorite Person as "Alan Dixon".
4. Search for contact D and export with a custom field mapping that includes Favorite Person.  No problem.
5. Search for contact C and export with the same mapping.  DB Error: "Data too long for column 'custom_XX'".

After
----------------------------------------
Same procedure as before, but contacts A and C are exported accurately.

Technical Details
----------------------------------------
@eileenmcnaughton has pointed out (https://github.com/civicrm/civicrm-core/pull/12598#issuecomment-460813585) that it would be better to not use the temp table at all.  That's still preferable, but in the meantime this solves an immediate problem.

-----
https://lab.civicrm.org/dev/core/issues/949
https://lab.civicrm.org/dev/core/issues/181

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@agh1 the problem is this risks solving some problems & creating others. There is a max width on a mysql table that is hit by some sites on export, although less since I did a big cleanup to remove the . I decided some time ago it would take me more time to test enough to feel comfortable  that this change wouldn't just fix some sites & break others then it would to fix it properly & eliminate storing these to the temp table (which has no benefit in this flow).

**Comment by agh1** [comment]
@eileenmcnaughton I understand the anxiety about introducing new problems, especially with variability among database configurations.  However, my understanding is that at the low end of lengths, `TEXT` columns will take up practically the same row length as a `VARCHAR` column that is magically the right length for the value.

Sure, that means that Integer/Select fields with very long labels will take up a lot of row length, causing the export to fail, but those are failing already because they won't fit in `VARCHAR(16)`.  However, I'm not so concerned about really long values so much as reasonably short ones like "Eileen McNaughton" and "District of Columbia" that are just a little bit too long--*and* cannot be shortened.

I ran some tests on a site exporting about 100,000 records with 20 fields in the export: display name and a bunch of custom fields, hacking CRM_Export_BAO_Export to not drop the temp table.  Looking in `information_schema.TABLES`, the average row length *decreased* when I applied the changes here.  

One of the custom fields I added was "favorite state", set to "Maryland".  Changing the value for everyone to "District of Columbia" increased the average row length, but that's to be expected.  If it were a custom field with arbitrary labels, it would certainly be possible to max out the amount stored there and end up with a maximum of 10 columns or so for an export.  But again, that would result in an error even with the status quo.

**Comment by agh1** [comment]
Jenkins retest this please.

**Comment by eileenmcnaughton** [comment]
@agh1 this is stale now - but I suspect it's also not needed any more. As part of the LeXIM approach to improving the export UI we included both a new [angular screen](https://civicrm.org/blog/josh/improvements-to-the-export-interface-are-in-the-works) and incremental clean up (the iterate by month part). The iterative cleanup & adding loads unit tests has been ongoing but this month in conjunction with the extension we did a big push (which goes a bit further than was needed to support the extension). 

Part of the enabler for the big push was actually a suggestion Tim made in NY that allowed us to overhaul our tests (the PrematureExitException) which & the discovery of the blocker to adding tests to cover a regression on exporting soft credits (also in NY  - it was NULL_ARRAY contamination).  Anyway the upshot is that as part of the cleanup this  PR https://github.com/civicrm/civicrm-core/pull/14937 fixes the issues with exporting state & country as a by-product of upgrading the test. Ie a very old regression meant that handling for these fields existed by was never hit.

**Comment by dejan9393** [comment]
It seems i'm still running into this issue on in v5.27.0 - not with the Country or State Province fields, but with a custom field with a Data Type of "Integer" and a Field Type of "Select", where the option labels are greater than 16 characters long

**Pull request closed without merging**
