### PR TITLE
Resolve Issue with Payment Allocation to Contribution Line Item

### PR DESCRIPTION
**Pull request by olayiwola-compucorp**
Overview
----------------------------------------
This pull request addresses an issue where incorrect amounts were allocated to contribution line items during payment processing. 

Considering the contribution entity table provided:

| Line   | Price | Quantity | Subtotal exc Tax | Tax  | Tax total | Total inc Tax |
|--------|-------|----------|------------------|------|-----------|---------------|
| Line 1 | 100   | 1        | 100              | 0%   | 0         | 100           |
| Line 2 | 200   | 1        | 200              | 0%   | 0         | 200           |
| Line 3 | 300   | 1        | 300              | 20%  | 60        | 360           |
| Total  |       |          |                  |      |           | 660           |

Before
----------------------------------------

Before this PR, the following EntityFinancialTrxn was created:

|            | Subtotal exc Tax | Payment 1 (200) | Payment 2 (200)  | Payment 3 (200) |
|------------|-------------------|-----------------------------------------------|-----------------------------------------------|-----------------------------------------------|
| Line 1     | 100               | 30.30                                         | 30.30                                         | 30.30                                         |
| Line 2     | 200               | 60.61                                         | 60.60                                         | 60.60                                         |
| **Line 3**     | **300**               | **90.91**                                         | **83.00**                                         | **69.02**                                         |
| Tax line 1 | 0                 | 0.00                                          | 0.00                                          | 0.00                                          |
| Tax line 2 | 0                 | 0.00                                          | 0.00                                          | 0.00                                          |
| Tax line 3 | 60                | 18.18                                         | 18.18                                         | 18.18                                         |
| Total      | 660               | 200.00                                        | 192.08                                        | 178.10                                        |

From this table, it's evident that incorrect amounts are assigned to line item 3 following the initial payment.

After
----------------------------------------

After this PR, the following EntityFinancialTrxn is created:

|            | Subtotal exc Tax | Payment 1 (200) | Payment 2 (200) | Payment 3 (200) |
|------------|-------------------|-----------------------------------------------|-----------------------------------------------|-----------------------------------------------|
| Line 1     | 100               | 30.30                                         | 30.30                                         | 30.30                                         |
| Line 2     | 200               | 60.61                                         | 60.61                                         | 60.61                                         |
| **Line 3**     | **300**               | **90.91**                                         | **90.91**                                         | **90.91**                                         |
| Tax line 1 | 0                 | 0.00                                          | 0.00                                          | 0.00                                          |
| Tax line 2 | 0                 | 0.00                                          | 0.00                                          | 0.00                                          |
| Tax line 3 | 60                | 18.18                                         | 18.18                                         | 18.18                                         |
| Total      | 660               | 200.00                                        | 200.00                                        | 200.00                                        |

Line Item 3 now receives the accurate allocation with subsequent payments.

Replication Step
----------------------------------------
- Create a pending contribution with a tax line item (maybe 100 + tax 20)
- Make the first partial payment (maybe 60) - Check that the EntityFinancialTrxns created for the payment has the correct total
- Make the second partial payment (maybe 30) - Check that the EntityFinancialTrxns created for the payment has an incorrect total

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
tests didn't complete - test this please

@olayiwola-compucorp how do we replicate this

@JoeMurray are you able to get someone to look - we should get a test if we do merge this

**Comment by jamienovick** [comment]
@olayiwola-compucorp can you add some details of how to recreate the issue via the UI?

**Comment by olayiwola-compucorp** [comment]
@eileenmcnaughton I've updated the PR desc with replication step, I also added a test

cc @jamienovick

**Comment by jamienovick** [comment]
@eileenmcnaughton Do you have what you need to validate this? Would be great to close it off. Best

**Comment by eileenmcnaughton** [comment]
@olayiwola-compucorp I did have a go at an alternate to this - but just got a bit stuck at the end https://github.com/civicrm/civicrm-core/pull/29503 on the test - it's a bigger change but this https://github.com/civicrm/civicrm-core/pull/29503/files#diff-74b281ac668a837edcbfabd5cb0d74b5647c92d24f63777ab964bc6376291e25L167 kinda points out where the real probelm is

**Pull request closed without merging**
