### PR TITLE
Add LEFT, RIGHT and SUBSTRING SQL functions

### PR DESCRIPTION
**Pull request by aydun**
Overview
----------------------------------------
Add LEFT, RIGHT and SUBSTRING SQL functions to APIv4

Before
----------------------------------------
no sense of direction

After
----------------------------------------
improved

Technical Details
----------------------------------------
`LEFT()` and `RIGHT()` are not strictly needed since the same results can be achieved with `SUBSTRING()`, but they are more intuitive and user-friendly.  And SQL provides them all.

@colemanw : LEFT & RIGHT don't work well with '0' characters, but that is the default shown.  Can we set a default value for the parameter?

Comments
----------------------------------------

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Would SUBSTRING() be more general? You can do negative numbers with it to get the same as RIGHT.

**Comment by aydun** [comment]
> Would SUBSTRING() be more general? You can do negative numbers with it to get the same as RIGHT.

@demeritcowboy SUBSTRING() is more general but less intuitive and user-friendly.  So let's do both...

**Comment by demeritcowboy** [comment]
Ok sounds good.
And I agree that the default of 0 that appears would be nice to change.
And maybe out of scope since it's a general issue but for "Extract text" there's no labels on the parameters so it's not clear what it wants.

Also out of scope but unless I'm missing how to group-by on a transformed field this won't help the original stackexchange question. But the feature is still useful for other reasons.

**Comment by colemanw** [comment]
Thanks for this @aydun. It would be helpful to add these to the test suite, can just add a few lines to the existing `SqlFunctionTest`.

This doesn't solve your UX default issue but I noticed a bug when handling `0` as an argument & pushed a fix: #26553

**Comment by aydun** [comment]
@colemanw - thanks, test added.

**Pull request merged**
