### PR TITLE
WIP  dev/core#530 make CiviCase Case Roles bidirectional

### PR DESCRIPTION
**Pull request by alifrumin**
Overview
----------------------------------------
see: https://lab.civicrm.org/dev/core/issues/530

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by colemanw** [comment]
This is quite an undertaking! There are probably more spots in the core code and the new case extension that make assumptions about relationship direction

**Comment by alifrumin** [comment]
Hey @colemanw, that it is.  There are definitely more places in the core code that make assumptions about direction. I looked briefly at the new case extension but not extensively.

**Comment by eileenmcnaughton** [comment]
This one is stale so I'm going to close it - we generally prefer not to have WIP PRs open for too long anyway - maybe there are some small chunks you can bite off

**Pull request closed without merging**
