### PR TITLE
CRM-19985 - CiviContribute Option to default recurring contribs

### PR DESCRIPTION
**Pull request by ghost**
This commit adds an option to tick the recurring contributions checkbox by default on contribution pages. It adds the option to the page admin form, adds a column to the database and modifies the contribution page to effect the selected option.

---

 * [CRM-19985: Add "Ticked by default" option for recurring contributions](https://issues.civicrm.org/jira/browse/CRM-19985)

### CODE REVIEW

**Comment by yashodha** [comment]
@mrlavalava  Your PR has gone stale Can you please rebase your branch ?
Also the upgrade needs to part of 4.7.18 now

**Comment by mattwire** [comment]
Could this be implemented in the same way as the membership contribution autorenew?  (See $autoRenewOption where 0: hide, 1: optional, 2: required)

**Comment by mrlavalava** [comment]
@mattwire I'll take your word for it, as I haven't seen that code yet. This started out as a, "this could be a simple thing for me to start with," but it engendered a lot of discussion via email. Clearly there are a few ways to skin this cat.

As this is my first PR against Civi core I'm more than happy to take from others as to how best to proceed. Rebase for now? Cancel the PR? etc.

**Comment by mattwire** [comment]
@mrlavalava: My apologies, I thought you were trying to solve a different problem :-)

**Comment by petednz** [comment]
@konadave much overlap here with your 'recur only' work you did?

**Comment by konadave** [comment]
Similar. This is adding an option to have the recurring contribution checkbox selected by default, the user would be allowed to deselect it. The extension I did for you makes it a requirement that the checkbox is selected, and completely hides it if the frequency/installment options aren't offered.

This adds the setting to the database. The extension stores it using the settings API.

**Comment by mattwire** [comment]
@petednz @konadave This is probably similar to what you are talking about: https://github.com/mattwire/civicrm-core/commit/c843169cd2a563bb91944df92657b2e81d0010b3.  I'm going to need something like that for the UK direct debit stuff which doesn't really make sense for non-recurring transactions.

**Comment by eileenmcnaughton** [comment]
I'm closing this since it is stale - please re-open if you rebase it. However, I think it's also unclear if this should be in core based on the above

**Pull request closed without merging**
