### PR TITLE
dev/core#1672 Ensure that a langauge prefix is added to urls when cal…

### PR DESCRIPTION
**Pull request by seamuslee001**
…led from crm.Url so correct translation of field lables is returned

Overview
----------------------------------------
This aims to resolve a problem where by when you dynamically load a set of custom fields front end custom form without the use of a profile the wrong locale of the label can be returned

Before
----------------------------------------
Wrong locale information is returned defaults to the system primary

After
----------------------------------------
Correct locale

Technical Details
----------------------------------------
I'm not sure if this solution is the correct one it works in my specific case but would appreciate thoughts from others on this 

ping @mattwire @mlutfy @christianwach

### CODE REVIEW

**Comment by christianwach** [comment]
@seamuslee001 Unfortunately that's not how it works - what you're adding is the language _code_ not the _locale_. This won't allow CiviCRM (in WordPress at least) to determine the correct translation. See #16700 for details of how this happens in WordPress. Have you tried that PR? It might already fix this issue.

**Comment by mattwire** [comment]
@seamuslee001 I think this is a bit more complex - I've not looked into detail yet. I've had similar issues with Stripe.
As you're doing an AJAX call (via CRM.api) I don't think you have access to the session? Which means you need to specify the desired language/locale via that request - the standard URL param for this is `lcMessages`. *Note it's possible what I'm saying is not relevant in this case!*

**Comment by mlutfy** [comment]
Could we have more specific steps to reproduce?

Is it with multilingual, or just civicrm UI translation without multilingual?

**Comment by seamuslee001** [comment]
Hi Folks, thnaks for the feedback I wasn't expecting this to get up first go, let me try and take you through the problem.

I have a site 1 domain, multilingual, english and french. the CMS is drupal8 (but I suspect this wouldn't matter the exact way you craft the urls would be cms specific) We have constructed them a custom event feedback form. We don't use profiles for this purpose but we do use custom fields so we assign the necessary values to the form https://github.com/JMAConsulting/biz.jmaconsulting.ao/blob/master/CRM/Ao/Form/Feedback.php#L34 then all we do is include the customdata template https://github.com/JMAConsulting/biz.jmaconsulting.ao/blob/master/templates/CRM/Ao/Form/Feedback.tpl#L4 

What we were finding was that when we would load the french version of the page (i.e. have /fr) on it, When the form was constructed the locale was correctly set to fr_CA (in our case) which meant that the submit button labels were correctly translated, However the custom fields were all outputting their english language for labels and content. The reason for this is that the url here https://github.com/civicrm/civicrm-core/blob/master/templates/CRM/common/customData.tpl#L14 was never having the french aspect added on e.g. fr/ so that then which was shown by the fact if I put debugging here https://github.com/civicrm/civicrm-core/blob/master/CRM/Custom/Form/CustomDataByType.php#L77 the locale was being outputted there was en_US which is the default language on this specific site. This 'fixed' it for us but its also not necessarily the perfect solution but I wasn't sure what is the perfect solution here.

**Comment by christianwach** [comment]
@seamuslee001 I'm not clear how things work in Drupal, but it looks to me as though there isn't specific handling of locales for Drupal 8 yet - it currently [inherits `getUFLocale()` from `CRM_Utils_System_DrupalBase`](https://github.com/civicrm/civicrm-core/blob/master/CRM/Utils/System/DrupalBase.php#L417-L443). Personally I would first check if that method is functioning as expected and supplying `CRM.url()` with the right "base" URL in the first place.

FWIW, I had to avoid calls to [`CRM_Core_I18n_PseudoConstant::longForShort()`](https://github.com/civicrm/civicrm-core/blob/master/CRM/Utils/System/DrupalBase.php#L442) in [my PR that fixes things in WordPress](https://github.com/civicrm/civicrm-core/pull/16700/files#diff-0761b448ddeed621a369a6e6e9ac2129R463-R469) because it guesses the _locale_ from the language _code_ and guesses incorrectly by default. With my PR in place, I have not been able to break CiviCRM's selection of locale and everything works as expected with the URLs that WordPress multilingual plugins generate.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I'm going to close this - it seems to be mostly a discussion piece and I don't think it needs to be open for that - there is an existing gitlab for the discussion from the looks

**Pull request closed without merging**
