### PR TITLE
CRM-20441 Limit acceptable operators to IN only

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @colemanw

---

 * [CRM-20441: Fatal error on contact summary activity tab for ACL'd user](https://issues.civicrm.org/jira/browse/CRM-20441)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton this mitigates a permission escalation risk that Coleman observed. I have also added a test as well

**Comment by eileenmcnaughton** [comment]
@seamuslee001 agree this is good to merge - I think it's not the full fix to @davejenx issue tho?

**Comment by seamuslee001** [comment]
Correct Dave's issue really now is how we stop a fatal showing on page when perm check fails on an id

**Comment by seamuslee001** [comment]
@eileenmcnaughton this has passed the other PR should deal with Dave's immediate issue

**Pull request merged**
