### PR TITLE
Update custom contact entity reference field values on contact merge

### PR DESCRIPTION
**Pull request by dontub**
Overview
----------------------------------------
Custom `EntityReference` field values referencing a contact are updated on contact merge just like `ContactReference` field values.

### CODE REVIEW

**Comment by colemanw** [comment]
@dontub this looks great! And you added tests!
Looks like a couple [minor style issues](https://test.civicrm.org/job/CiviCRM-Core-Style/7074/checkstyle/).

**Comment by colemanw** [comment]
I love the modern php style you're using here @dontub 

For style/minor fixes we usually squash and force-push so the PR only contains one commit. Do you have a minute to do that?

As a followup, it would be good to move the other dedupe-related functions like `appendCustomContactReferenceFields` out of the overcrowded `CRM_Core_DAO` and into this new class.

**Comment by dontub** [comment]
Moved the two `append` methods from `CRM_Core_DAO`. Shall I also move `CRM_Core_DAO::getReferencesToContactTable()`?

**Comment by dontub** [comment]
@colemanw: Do you think this can be merged?

**Comment by colemanw** [comment]
Thank you for working on this @dontub.
I ended up tackling this same problem while fixing the caching of custom data.
https://github.com/civicrm/civicrm-core/pull/28991 does the same thing as this PR but it makes use of the new cached data provider for custom fields (`CRM_Core_BAO_CustomField::getAll()`).
That PR caused this one to have merge-conflicts, so I've pulled out the tests you wrote (modified one of them to test the DAO function directly) and submitted as #29040

**Pull request closed without merging**
