### PR TITLE
Rename 'Provider' entity to 'SmsProvider'

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes a longstanding `fixme` to rename a badly-named entity.

Before
----------------------------------------
This FIXME was added in 2013!

https://github.com/civicrm/civicrm-core/blob/25bc61bb32b606d6881bf4cdc4d65a9863bbb54b/api/v3/utils.php#L317-L319

After
----------------------------------------
Renamed. Won't impact extensions because class_aliases have been added.

Technical Details
----------------------------------------
This is the same solution we've used for other entities that needed to be renamed. `class_alias` works well to preserve backward-compatibility.

Comments
-------
Targeting the RC because this API was added very recently in #28510

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
OK - test cover should be good on these changes

**Comment by colemanw** [comment]
@eileenmcnaughton I added this FIXME 10 years ago!
Better late than never.

**Comment by eileenmcnaughton** [comment]
@colemanw well done! But, I bet I can find an older fixme....

**Comment by eileenmcnaughton** [comment]
@colemanw what got you onto fixing this - I thought it might have come out of looking at https://github.com/civicrm/civicrm-core/pull/29475 - but that one doesn't touch this I don't think

**Comment by eileenmcnaughton** [comment]
dang test fail is real - ironically the one I wanted to tag ornery

api_v3_SyntaxConformanceTest::testCustomDataGet with data set #75 ('SmsProvider')
Undefined array key "Provider"

/home/homer/buildkit/build/build-4/web/sites/all/modules/civicrm/CRM/Core/DAO/AllCoreTables.php:365
/home/homer/buildkit/build/build-4/web/sites/all/modules/civicrm/tests/phpunit/api/v3/SyntaxConformanceTest.php:869
/home/homer/buildkit/build/build-4/web/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:247
/home/homer/buildkit/extern/phpunit9/phpunit9.phar:2307

**Comment by colemanw** [comment]
@eileenmcnaughton I had just missed a couple spots. Good thing the test caught it!

**Comment by colemanw** [comment]
> @eileenmcnaughton what got you onto fixing this?

At the sprint we wanted to finish some AdminUI work, and we looked at https://github.com/civicrm/civicrm-core/pull/28512 but got confused because we couldn't find the SmsProvider api entity... then finally realized that it [*does* exist](https://github.com/civicrm/civicrm-core/pull/28510) just has a terrible name.

**Pull request merged**
