### PR TITLE
AngularJS - Allow loading multiple apps on a single page

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------

This allows multiple Angular apps to run on a single page. For example, you might display 2x Angular-based tabs, 3x Angular-based WP shortcodes, or 4x Angular-based Drupal blocks.

Before
----------------------------------------
Only one Angular app could run on a page.

The app is loaded by (a) instantiating an `AngularLoader` with a list of required modules and (b) outputting an `ng-app` attribute to initiate client-side setup.

After
----------------------------------------
Any number of apps can be run together in different regions of the page (as blocks, shortcodes, etc).

The apps are loaded by (a) listing all required modules in a shared instance of `AngularLoader` and (b) outputting a `<crm-angular-js>` tag to initiate client-side setup.

Technical Details
----------------------------------------

This change requires loading the resources (JS/CSS/HTML/strings/etc) for all modules in a coordinated fashion. (*To wit: 3x parts of the page may use `ui-sortable`, but you only want to load the `ui-sortable.js` file once.*) Additionally, it requires the browser initialize AngularJS services in multiple sections of the DOM.

Putting it together, here is how to setup a portion of a standard page running an Angular module:

1. Load any required resources for the module (JS/CSS/strings/etc):
   ```php
    Civi::service('angularjs.loader')->addModules('myCoolApp');
    ```
2. Output a tag in the spot where it should appear:
    ```html
    <crm-angular-js modules="myCoolApp">...</crm-angular-js>
    ```

Special Note: Contract change for some extensions
----------------------------------------

Based on https://docs.civicrm.org/dev/en/latest/framework/angular/loader/, a small number of extensions have used the formulation

```php
$loader = new Civi\Angular\AngularLoader();
$loader->setPageName('civicrm/api4');
$loader->setModules(['api4Explorer']);
$loader->useApp([
      'defaultRoute' => '/explorer',
]);
$loader->load();
```

These should still work as-is, but (in the future) they may not co-exist well if some other thing (e.g. Drupal block) adds some Civi-Angular. Instead, these should be changed to:

```php
Civi::service('angularjs.loader')
  ->addModules('api4Explorer')
  ->useApp(['defaultRoute' => '/explorer']);
```

Key changes:

* `$loader->setPageName(...)` is now implicit (based on the active request)
* `$loader->load()` is now automatic. (If the page has any Angular modules, then `load()` will run automatically.)

### CODE REVIEW

**Comment by colemanw** [comment]
@totten this almost works flawlessly. But there is one flaw. When running an angular app using the new service, it works but I get a bunch of jQuery error messages. I ran a diff of the html document before/after and found one significant difference.

**Before:** the script `js/noconflict.js` is the last script in the header.
**After:** all scripts added by angularLoader are _after_ `js/noconflict.js`.

That script (not to be confused with `noConflict.js` in greenwich) is responsible for setting `CRM.$ = jQuery.noConflict()`. Thus the jQuery errors if Angular scripts follow it in the header.

The script is added here: https://github.com/civicrm/civicrm-core/blob/96622c8c36fb7f5cc1708e4574451e5f29ef96aa/CRM/Core/Resources/Common.php#L159-L163

It has a very high weight and should be the last script to load. But for some reason the entire angular bundle loads after this core bundle. Is there some issue with the new Bundle mechanism that it doesn't respect weights?

**Comment by totten** [comment]
@colemanw The problem is actually fairly simple - if you go to start of `render()`, you'll see that it sorts before rendering. Our new event fired after the snippets were sorted.

I pushed up a simple change with the intuitive effect - anything added by the listener will be sorted.

(On second thought, I'm on the fence -- in theory maybe the listener should be *able* to determine final sort order, in which case https://github.com/civicrm/civicrm-core/commit/8188f950d845cebc1c40b59c94e750ec6dcd3527 might be better than https://github.com/civicrm/civicrm-core/pull/19922/commits/ac27ff2e03b2c6905b97e485e307795beed7f154.)

**Comment by totten** [comment]
> (On second thought, I'm on the fence -- in theory maybe the listener should be able to determine final sort order, in which case 8188f95 might be better than ac27ff2.)

Responding to myself - no, the original  ac27ff2 makes more sense. If a listener wants to reorder things in the ac27ff2 world, then it can/should change the `weight`s.  This way `weight` remains the authoritative ordering. In the big picture, the alternative 8188f95 would make ordering more inscrutable.

**Comment by colemanw** [comment]
@totten thanks that fixed the issues I was seeing. Can you please review/merge this now?

**Comment by totten** [comment]
* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __Pass__: I updated the description
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __Pass__
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __Provisional Pass__: There should be an update for https://docs.civicrm.org/dev/en/latest/framework/angular/loader/ too. But we can merge first.
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __Pass__: I spot-checked for regressions on several of the screens that were specifically patched here. Additionally, I also tried out CiviMail, Mosaico, CiviCase Ext, OAuth Client. Tested in both English and French. It seems like various resources (CSS/JS/strings) are still loaded consistently.
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __Pass__: For me, the question was whether existing consumers of `AngularLoader` will work. And they did. I think this is acceptable for merging/deploying, but I think there's a caveat, so I've added that to the description.
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __Pass__
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __Pass__
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __Pass__

@colemanw This looks safe. If you've got other work based on it, then great. I made some changes to the description -- assuming my interpretation of the upgrade DX is right, then please merge.

**Pull request merged**
