### PR TITLE
dev/core#2372 Enable submitOnce for some forms

### PR DESCRIPTION
**Pull request by ahed-compucorp**
Overview
----------------------------------------
The `submitOnce` feature works so well for many forms, but others have some issues with others. I think it is a good idea to enable it for any form if it works without any issue which is 90 per cent of the forms - more in this [PR](https://github.com/civicrm/civicrm-core/pull/14519) and this [comment](https://github.com/civicrm/civicrm-core/pull/14519#issuecomment-502405155).

At first, I prepared a list of [classes](https://gist.github.com/ahed-compucorp/7065f64c8312fb3defe3e4f383eebbd7) that are a subclass of `CRM_Core_Form`, and in this PR I enabled it for the following 37 forms:

| Form Class                                        | URL (if any?)       |
| ---                                               | ---                 |
| CRM_ACL_Form_ACL                                  | civicrm/acl -> add/edit form |
| CRM_ACL_Form_ACLBasic                             | civicrm/acl/basic -> add/edit form |
| CRM_ACL_Form_EntityRole                           | civicrm/acl/entityrole  -> add/edit form |
| ACL_Form_WordPress_Permissions                    | wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Faccess%2Fwp-permissions&reset=1 |
| CRM_Activity_Form_ActivityView                    | civicrm/activity/view?action=view&reset=1&id=107&atype=68&cid=124&context=home |
| CRM_Activity_Form_Search                          | civicrm/activity/search |
| CRM_Activity_Form_Task_AddToTag                   | civicrm/activity/search -> "Add Tags to activities" |
| CRM_Activity_Form_Task_Batch                      | civicrm/activity/search -> "Update multiple activities" |
| CRM_Activity_Form_Task_Delete                     | civicrm/activity/search -> "Delete Activities"  |
| CRM_Activity_Form_Task_FileOnCase                 | civicrm/activity/search -> "File on Case"  |
| CRM_Activity_Form_Task_PickOption                 | civicrm/activity/search -> "Send Email to Contacts"  |
| CRM_Activity_Form_Task_PickProfile                | civicrm/activity/search -> "Update multiple activities"  |
| CRM_Activity_Form_Task_Print                      | civicrm/activity/search -> "Print selected rows"  |
| CRM_Activity_Form_Task_RemoveFromTag              | civicrm/activity/search -> "Remove Tags from activities"  |
| CRM_Activity_Import_Form_DataSource               | civicrm/import/activity (step 1) |
| CRM_Activity_Import_Form_MapField                 | civicrm/import/activity (step 2) |
| CRM_Admin_Form_CKEditorConfig                     | civicrm/admin/ckeditor |
| CRM_Admin_Form_CMSUser                            | civicrm/admin/synchUser |
| CRM_Admin_Form_Generic                            | civicrm/admin/setting/preferences/multisite,civicrm/admin/setting/preferences/campaign,civicrm/admin/setting/preferences/event,civicrm/admin/setting/preferences/event,civicrm/admin/setting/preferences/campaign |
| CRM_Admin_Form_Job                                | civicrm/admin/job?action=add&reset=1 |
| CRM_Admin_Form_LabelFormats                       | civicrm/admin/labelFormats?action=add&reset=1 |
| CRM_Admin_Form_LocationType                       | civicrm/admin/locationType?action=add&reset=1 |
| CRM_Admin_Form_MailSettings                       | civicrm/admin/mailSettings?action=add&reset=1 |
| CRM_Admin_Form_Mapping                            | civicrm/admin/mapping?action=delete&id=1, civicrm/admin/mapping?action=update&id=1&reset=1 |
| CRM_Admin_Form_MessageTemplates                   | civicrm/admin/messageTemplates/add?action=update&id=65&reset=1 |
| CRM_Admin_Form_Navigation                         | civicrm/admin/menu?action=add&reset=1 |
| CRM_Admin_Form_OptionGroup                        | civicrm/admin/options?action=add&reset=1 |
| CRM_Admin_Form_Options                            | Menu -> "Dropdown Options" -> add/edit form for each one |
| CRM_Admin_Form_ParticipantStatusType              | civicrm/admin/participant_status -> add/edit form |
| CRM_Admin_Form_PaymentProcessorType               | civicrm/admin/paymentProcessorType -> add/edit form |
| CRM_Admin_Form_PdfFormats                         | civicrm/admin/pdfFormats > add/edit form |
| CRM_Contact_Form_Task_SMS                         | civicrm/activity/sms/add?action=add&reset=1&cid=185&selectedChild=activity&atype=4 |
| CRM_Contribute_Form_Contribution                  | civicrm/contribute/add?reset=1&action=add&context=standalone          |
| CRM_Contribute_Form_Search                        | civicrm/contribute/search?reset=1 |
| CRM_Contribute_Form_Task_Invoice                  | civicrm/contribute/search?reset=1 -> "Invoices - print or email" |
| CRM_SMS_Form_Provider                             | civicrm/admin/sms/provider?reset=1&action=browse -> add/edit form |
| CRM_UF_Form_Group                                 | civicrm/admin/uf/group?reset=1 -> add/edit form |

Before (sample)
----------------------------------------
- Send Invoice Form (Search Action)
Peek 2021-02-08 16-40
- Find Contributions Form
Peek 2021-02-08 16-06
- New Contribution Form
Peek 2021-02-08 16-10

After (sample)
----------------------------------------
- Send Invoice Form (Search Action)
Peek 2021-02-08 20-43
- Find Contributions Form
Peek 2021-02-08 20-46
- New Contribution Form
Peek 2021-02-09 12-09

Comment
----------------------------------------

I enable it if only the form's buttons still work correctly afterwards.

Issue: https://lab.civicrm.org/dev/core/-/issues/2372

### CODE REVIEW

**Comment by ahed-compucorp** [comment]
Initially, I planned to search and update those 90% well-behaved forms in this PR and then we can figure out the troublesome forms and make PR for them only if they worth the efforts, but after I looked at the number of the classes that are a subclass of `CRM_Core_Form` I became demotivated :( as this became a repetitive/time-consuming task.

The good thing not all of these [classes](https://gist.github.com/ahed-compucorp/7065f64c8312fb3defe3e4f383eebbd7) are a normal form in CiviCRM.

**Comment by demeritcowboy** [comment]
Thanks for your time on this. I've started to take a look. Noting for any other reviewers some things that came up before to look out for:

* Most forms have two versions - the popup one and the not popup one (when the popup forms setting is turned off at admin - customize - display prefs).
* The enter key sometimes functions the same as clicking the submit button.

**Comment by demeritcowboy** [comment]
This must have taken you a really long time. It's probably not worth doing any more at this time.

* General standards
    * [`r-explain`] __PASS__
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __Maybe issue__
      * For the invoice task one, as noted in the ticket with forms that generate a download it freezes the form a bit. So here if you choose PDF instead of email, the form gets "stuck", although the download still works fine.
      * I'm always a bit scared of the contribution form. It has a couple variations. I'm mostly not sure if parts of it are reused other places. If it's just used in the back-office it should be ok.
      * ACL_Form_WordPress_Permissions - didn't test
      * Otherwise all works. Misc minor notes:
        * CRM_Activity_Form_ActivityView - Not necessary to have submitonce since is only ever in view mode but doesn't hurt.
        * CRM_Admin_Form_MessageTemplates - Doesn't work if you press cancel first since it adds its own javascript but cancel isn't important for this.
        * PaymentProcessorType - Didn't even know this existed. Without an extension that supports it though I'm not sure how useful this page is. Some future thing to look at.
        * Prexisting weirdness in mailsettings where save'n'test followed by save can create duplicates but it's not related to submitonce.
* Developer standards
    * [`r-tech`] __PASS__
    * [`r-code`] __PASS__
    * [`r-maint`] __N/A__
    * [`r-test`] __PASS__

**Comment by eileenmcnaughton** [comment]
@demeritcowboy so the 'maybe issue' is the invoice form - although that is possibly 'no worse' and the worry that the backoffice contribution form might be accessed from other places?

**Comment by demeritcowboy** [comment]
Right.

**Comment by eileenmcnaughton** [comment]
OK - I'll merge - I'm pretty sure the back office contribution form is not otherwise accessed. I might take a look at the invoice as a follow up

**Pull request merged**
