### PR TITLE
Downgrade Symfony Service Contracts to 2.2.0 to fix php fatal error i…

### PR DESCRIPTION
**Pull request by seamuslee001**
…n wordpress

Overview
----------------------------------------
5.53/master version of #24170 

ping @eileenmcnaughton @demeritcowboy @kcristiano @totten

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Thanks @seamuslee001.
Let me check if this causes a problem with drupal 9 - we could maybe do one of those `|| ~` things if so.

**Comment by demeritcowboy** [comment]
I get these errors in drupal 9:
* drupal/core-recommended 9.4.5 requires psr/container ~1.1.1
* drupal/core-recommended 9.4.5 requires symfony/service-contracts ~v2.5.1

**Comment by seamuslee001** [comment]
@demeritcowboy I think this should be sorted now i.e. it should install v2.2.0 in the tarballs but permit d9 installing

**Comment by demeritcowboy** [comment]
Ok for me.
@kcristiano does this solve the original problem (if you replace these files and run composer install - but not the ones here the ones from the 5.52 PR since the .lock is different)

**Comment by kcristiano** [comment]
https://github.com/civicrm/civicrm-core/pull/24170#issuecomment-1207410160

**Comment by kcristiano** [comment]
I just did a new build of master (5.53-alpha) and upgraded to that version follwing the steps in the above comment.   this PR looks good as well.

Looks good to merge

**Comment by demeritcowboy** [comment]
@seamuslee001 I can't upmerge 5.52 since there's conflicts and merging this will make more conflicts. Hopefully will get sorted out as part of the 5.53 branching?

**Comment by seamuslee001** [comment]
@demeritcowboy at the moment there is no 5.53 branch so master = 5.53 branch = RC effectively at the moment hence why I did 2 PRs

**Pull request merged**
