### PR TITLE
Removes Joomla Sidebar

### PR DESCRIPTION
**Pull request by vingle**
Overview
----------------------------------------
As discussed here: https://lab.civicrm.org/dev/joomla/-/issues/45 - Joomla 4 has a sidebar, which defaults open, and means the Civi sidebar squashes the main content more. This PR removes that sidebar. 

As Joomla 3 is end-of-life, probably most Joomla users will be on Joomla 4. The sidebar was unique to Joomla, and not present in WordPress or Drupal 9+. Removing the sidebar also stops Civi's main content from being loaded inside a table.

Before
----------------------------------------
image

After
----------------------------------------
image

Technical Details
----------------------------------------
Changes impact two Joomla-specific files – joomla.css and joomla.tpl – so shouldn't impact other CMSs.  Joomla 3 is End-of-life since August 17, other than the paid Extended Support Release programme, and this hasn't been tested there.

Comments
----------------------------------------
If Joomla 3 support is required, this needs testing on Joomla 3.

### CODE REVIEW

**Comment by colemanw** [comment]
Thanks @vingle! It would be great if you could fix the linting errors caught here and an added bonus if you could squash the commits down to one.
image

**Comment by vingle** [comment]
@colemanw thanks - will do. Am keen to clean up joomla.css completely, but that's probably a separate PR.

**Comment by seamuslee001** [comment]
I think in some drupal themes like Garland it could have its own side bar but yes. I think if we are doing this and completely gutting the sidebar  can I suggest we get rid of https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/Invoke.php#L216 and https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/Joomla.php#L32  and https://github.com/civicrm/civicrm-core/blob/master/templates/CRM/Block/blocks.tpl. 

Just also noting that JMA currently has 2 clients that still use Joomla 3 for mainly joomla plugin / module reasons

**Comment by vingle** [comment]
> I think in some drupal themes like Garland it could have its own side bar

That's true.

> can I suggest we get rid of…

That would be a big improvement to the PR – but it's not something I feel confident to do. (removing the function from /core/Joomla.php seems to make that file unnecessary too?)

> JMA currently has 2 clients that still use Joomla 3

Is it possible to get a sense if they value the sidebar? There hasn't been any pushback to removing it on [the Gitlab issue](https://lab.civicrm.org/dev/joomla/-/issues/45) but it's maybe not been seen by so many Joomla users.

**Comment by seamuslee001** [comment]
@vingle I'll see if I can get someone to check in with them.

**Comment by vingle** [comment]
@colemanw – I've cleaned up the css spacing/bug, but struggled to squash - either thru the desktop or webUI (because one commit is a merge?). If you can squash on merge, that's appreciated - or I can make a new PR? 

Not sure about implementing Seamus's suggestions as I don't know how best to check if it would impact other things than Joomla's UI beyond lots of testing on the different CMSs.

**Comment by andrewpthompson** [comment]
@vingle I did a quick test on Joomla 3 (as requested on Mattermost).

No major problems but I did notice 2 minor things:

1. The font size of some text is smaller after applying the patch (like the text below the Grants Summary heading in the screenshot below).
2. There is no white space at all on the left and right side between elements and the edge of the browser window. On the right side this means the browser's right scrollbar can overlap some elements.

image

**Comment by vingle** [comment]
@andrewpthompson thanks alot for doing the check. I foolishly haven't left any J3+Civi dev spaces to test against, but will set one up, fix and resubmit. The shrinking font-size is a little unexpected.

**Comment by JoeMurray** [comment]
@seamuslee001 could you also do a runtime test and include testing of your suggested code improvements to patch then get @monishdeb to QA. @Edzelopez could you check with one or both of our J3 clients?

**Comment by vingle** [comment]
@andrewpthompson - I've just setup a J3 and Civi to test and while I can't replicate the lack of gap on the edges after refreshing the browser (see below), I can see the font-size shrinks from the already too small 13px to 11px.

This is because sizes are set in `ems` not `rems` (like much of Civi css sadly) so removing the table from the markup has changed the parent font-size definition for `.description` from the 13px of `.crm-container table` in civicrm.css to the 11px of `#crm-container` in joomla.css. A reasonable fix for this is to change #crm-container in Joomla.css to 13px. Strictly speaking it should be something modern/accessible like 16px but that's a different issue. Making it 13px at least keeps the UI identical before & after.

image

**Comment by colemanw** [comment]
@vingle... really appreciate your work on this!
It appears that all reviewer feedback has been addressed, so 🚀

**Comment by vingle** [comment]
Thanks @colemanw. I can now make my radical clean-up joomla.css PR: https://github.com/civicrm/civicrm-core/pull/27834!

**Comment by andrewpthompson** [comment]
Thanks for your work on this @vingle 
I think the other problem I saw was some custom css of mine that I added a very long time ago and had forgotten about but thanks for checking and fixing the font size issue. Nice work.

**Pull request merged**
