### PR TITLE
Make SearchKit Required

### PR DESCRIPTION
**Pull request by colemanw**
Overview
-------------------------------------
Ensure that SearchKit is always installed and cannot be disabled.
This allows us to use it for core UI elements.

Before
------------
SearchKit installed by default, but can be disabled.

After
-------------
SearchKit is not allowed to be disabled.
If not already enabled, the upgrader will install it.

Technical Details
---------------
SearchKit was already being enabled on the standard "setup" API, but some installers [don't yet use it](https://lab.civicrm.org/dev/core/-/issues/1615).

As a hedge I've also added a system status check which gives a warning and prompts the admin to immediately install required extensions.
image

### CODE REVIEW

**Comment by colemanw** [comment]
This takes care of upgrading existing installs. The missing piece of this is installing SearchKit for new installs. The current way we do that is documented to basically say "don't do it this way."

https://github.com/civicrm/civicrm-core/blob/a715421290d4afc8b6998e342d3378a35212597c/xml/templates/civicrm_data.tpl#L1776-L1779

**Comment by totten** [comment]
@colemanw - For new installs, don't we already enable by default for real-world deployments (https://github.com/civicrm/civicrm-core/blob/5.54/setup/plugins/init/DefaultExtensions.civi-setup.php#L16)? But you want a strong guarantee -- which means [dealing with the older installers](https://lab.civicrm.org/dev/core/-/issues/1615)?

**Comment by colemanw** [comment]
Ok, good to know that the modern installer already enables it.
What systems still use the older installers @totten ?

**Comment by totten** [comment]
I believe the answer is Joomla, Drush, and a few civibuild types. (In civibuild, D8/D9 use the new one -- but D7/WP/BD use the old one.) In [dev/core#1615](https://lab.civicrm.org/dev/core/-/issues/1615), these are the "Phase 2" items.

**Comment by totten** [comment]
Here are some of the things that we would want to try 

1. Install Civi 5.XX. Enable SearchKit. Disable SearchKit. Upgrade to 5.57(w/PR).
2. Install Civi 5.XX. Enable SearchKit. Upgrade to 5.57(w/PR).
3. Install Civi 5.XX. Don't enable SearchKit. Upgrade to 5.57(w/PR).

The choice of number 5.XX is a bit arbitrary. Some interesting reference points might be:  `5.47` (the civigrant switch), `5.39`/`5.45`/`5.51` (recent ESRs), and 4.6.12 (oldest supported upgrade start-point). Generally, the period of 5.38-5.51 may be interesting since `CRM_Search_Upgrader` indicates new steps every 1-2 months in that period

We probably don't need to `r-run` every permutation during PR review. (The `upgrade-test` covers some flavors of `#3`, and the RC period is officially when people should try these out.) But spot-checking a couple would be prudent.

**Comment by colemanw** [comment]
@totten I did the following test:

1. Build a clean site running 5.35 (when SearchKit was first added as a core extension and had a different key! `search` instead of `search_kit`)
2. Enable SearchKit
3. Disable SearchKit
4. Checkout this branch and run upgrader to 5.57.

**Result:** SearchKit was enabled and renamed properly, but pending upgrades on the extension never ran.

I investigated and found that this was by semi-intentional:
https://github.com/civicrm/civicrm-core/blob/ebb54be3069c9394594385ebff2107ff17da16aa/CRM/Upgrade/Form.php#L573-L574

I think when you wrote that you weren't thinking about the possibility of "new" installed extensions requiring upgrades, but that's the case with a previously-disabled ext.

I made  [this change](https://github.com/civicrm/civicrm-core/pull/24739/commits/f38b6304ffc321b2095a98214edb3043fb007bed) and re-ran the scenario. This time everything came out as expected. SearchKit was renamed and enabled and upgraded. :+1:

**Comment by totten** [comment]
> I think when you wrote that you weren't thinking about the possibility of "new" installed extensions requiring upgrades, but that's the case with a previously-disabled ext.

IIRC, I was thinking about a scenario  like this:

* You had an old version of `search_kit` installed+active. This means that `civicrm_search_display` is out-of-date.
* You want to activate `civigrant`. `civigrant` defines some `civicrm_search_display`s.
* The upgrader should (1) upgrade `search_kit` (`civicrm_search_display`) and then (2) turn on `civigrant` (which inserts some `civicrm_search_display`s). (*If the order is flipped, then `civigrant` cannot correctly insert the record.*)

In the long view, it's probably incorrect to say "Upgrades Always Come First" or "Installations Always Come First". It should ideally be about the shape of the dependencies...

**Comment by totten** [comment]
The reason for saying "Upgrades Always Come First" or "Installations Always Come First" is that it's easier to write that into the upgrader. (You just set the priority-number based on the task-type.)

Perhaps it would work to use the extension-key (rather than the task-type) to pick a priority, e.g.

1. Make a list of all local extensions (active or inactive). Sort by dependency. Assign a numerical weight to every ext.
    ```php
    $weights = [
      'org.civicrm.search_kit' => 0,
      'authx' => 1,
      'org.civicrm.afform' => 2,
      'org.civicrm.civigrant' => 3,
    ];
    ```
2. When adding a task to install _or_ upgrade, the task's priority is like `1000 + $weights[$extKey]`.

I don't know if we have the patience for it right now.

**Comment by colemanw** [comment]
> I don't know if we have the patience for it right now

My thoughts exactly

**Comment by colemanw** [comment]
@totten I think I found a simple solution that works reasonably well: 
8ac3366

**Comment by totten** [comment]
I did some `r-run` to confirm -- which went weirdly. The first time, the GUI-based upgrade failed. After re-running a few more times, the failure seemed sporadic/arbitrary -- it didn't always fail, and (when it did) the place-of-failure shifted around. I also couldn't see a correlation between those errors and the start- or end-configurations. It might be something about my machine (e.g. earlier today, I had a case where a simple `ls` command aborted half-way through).

In any event, some time passed and I tried it several more times (*because I really wanted to reproduce*), but it seems to behave stably now. The last several trials (which did use varied start-points) were all clean.

Merging.

**Comment by demeritcowboy** [comment]
All the test sites now have a status error that says search kit is required. Does buildkit need an update?

**Comment by totten** [comment]
Oh:

Screen Shot 2022-12-02 at 3 50 55 PM

I wonder if https://github.com/civicrm/civicrm-buildkit/pull/735 would fix it...

**Comment by totten** [comment]
Yes, 735 fixes the status-message above -- but it causes some other test failures.

Speculation: While running tests, it periodically rests back to a baseline SQL snapshot -- and making SK mandatory might affect that baseline. Perhaps SearchKit tests somehow assume that the baseline condition is "extension uninstalled"?

**Pull request merged**
