### PR TITLE
Crm 16761 1

### PR DESCRIPTION
**Pull request by zorgalina**
4.7alpha1.sql.tpl - change datatype boolean to tinyint(4); source SelfSvcTransfer line 239, add back missing right paren; SelfSvcUpdate - change module description

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Changes to the upgrade script go stale very quickly - you might need to put that into a separate PR to get the tests to pass & get it in.

We've been working really hard at trying to get comment blocks on all functions & improving our test coverage - it would be good to see some more tests & comment blocks.

NB - if you are having trouble rebasing I always do

git fetch -f origin
git rebase -i origin/master

you can squash commits together when you use the -i flag - if appropriate

**Comment by zorgalina** [comment]
Hi Eileen - I did 'git fetch;  git reset --hard origin/master'

But I will do as you suggested (git fetch -f origin; git rebase -i
origin/master)

I will try again to test - I have a VirtualBox Ubuntu setup but I couldn't
seem to get Selenium working; only the database update test seemed to work,
but I didn't know how/where to include test results.

I will add comment blocks on each function (w/in PHP modules, right?)
I added my updates to 4.7.alpha1.mysql.tpl right after I created the
branch. I will try again and commit it separately - now, if I commit it, do
I attach buildkit database test results?

If  I cannot get Selenium to work or figure out why it isn't (it reported
errors on my install even before I made any changes) - not sure what the
'then' should be here, I can abandon the attempt or hand over the code to a
more skillful person, I don't want it to go to waste.

On Thu, Sep 3, 2015 at 12:57 AM, Eileen McNaughton <notifications@github.com
> wrote:

> Changes to the upgrade script go stale very quickly - you might need to
> put that into a separate PR to get the tests to pass & get it in.
>
> We've been working really hard at trying to get comment blocks on all
> functions & improving our test coverage - it would be good to see some more
> tests & comment blocks.
>
> NB - if you are having trouble rebasing I always do
>
> git fetch -f origin
> git rebase -i origin/master
>
> you can squash commits together when you use the -i flag - if appropriate
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6667#issuecomment-137370832>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by eileenmcnaughton** [comment]
"If I cannot get Selenium to work"

I can't get selenium to work either! I only do phpunit tests. I prefer them philosophically actually - because they force you to write functions that are smaller & more logical for testing purposes. About half of the api suite was actually written in order to do the set-up for unit tests :-)

Re the comments - we follow drupal coding standards - so these are our comments standards.
https://www.drupal.org/node/1354
If you use phpstorm or similar it makes comment blocks really easy :-)

git fetch -f 
The -f updates your local copy of origin/master to point to the latest commit. Otherwise it only moves the pointer when it feels like it (I believer there is a logic there - but it makes sense to me in the way that my 9-year-old sometimes remembers to brush his teeth)

**Comment by zorgalina** [comment]
Ah, thanks Eileen for your quick reply.  I will just do phpunit tests - I
spent > a week (not fulltime) trying to get that effing buildkit all
working and just felt like an idiot.

Regards,
Lesley

On Thu, Sep 3, 2015 at 4:27 PM, Eileen McNaughton <notifications@github.com>
wrote:

> "If I cannot get Selenium to work"
>
> I can't get selenium to work either! I only do phpunit tests. I prefer
> them philosophically actually - because they force you to write functions
> that are smaller & more logical for testing purposes. About half of the api
> suite was actually written in order to do the set-up for unit tests :-)
>
> Re the comments - we follow drupal coding standards - so these are our
> comments standards.
> https://www.drupal.org/node/1354
> If you use phpstorm or similar it makes comment blocks really easy :-)
>
> git fetch -f
> The -f updates your local copy of origin/master to point to the latest
> commit. Otherwise it only moves the pointer when it feels like it (I
> believer there is a logic there - but it makes sense to me in the way that
> my 9-year-old sometimes remembers to brush his teeth)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6667#issuecomment-137600587>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
As for phpunit tests, would I add them to the commit, in what folder?
 I have just been using Netbeans + Vim editor, thanks for tip re: phpstorm .

On Thu, Sep 3, 2015 at 4:34 PM, Lesley Evensen <zorgalina@gmail.com> wrote:

> Ah, thanks Eileen for your quick reply.  I will just do phpunit tests - I
> spent > a week (not fulltime) trying to get that effing buildkit all
> working and just felt like an idiot.
>
> Regards,
> Lesley
>
> On Thu, Sep 3, 2015 at 4:27 PM, Eileen McNaughton <
> notifications@github.com> wrote:
>
>> "If I cannot get Selenium to work"
>>
>> I can't get selenium to work either! I only do phpunit tests. I prefer
>> them philosophically actually - because they force you to write functions
>> that are smaller & more logical for testing purposes. About half of the api
>> suite was actually written in order to do the set-up for unit tests :-)
>>
>> Re the comments - we follow drupal coding standards - so these are our
>> comments standards.
>> https://www.drupal.org/node/1354
>> If you use phpstorm or similar it makes comment blocks really easy :-)
>>
>> git fetch -f
>> The -f updates your local copy of origin/master to point to the latest
>> commit. Otherwise it only moves the pointer when it feels like it (I
>> believer there is a logic there - but it makes sense to me in the way that
>> my 9-year-old sometimes remembers to brush his teeth)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/civicrm/civicrm-core/pull/6667#issuecomment-137600587>
>> .
>>
>
>
>
> --
> زورگلنه ءء لسلی
>



-- 
زورگلنه ءء لسلی

**Comment by eileenmcnaughton** [comment]
re tests - here is a PR I just did making a minor change & adding tests to ensure the change is all good

https://github.com/civicrm/civicrm-core/pull/6678

A couple of notes -

1)  I had to fix a static warning to make the tests pass - I think that is a good thing about the unit tests.
2) You can see I fixed some code comments too.
3) Would be good if you gave @totten some feedback on the buildkit issues. We have just finished the google summer of code & there was a suggestion that some of the (modest) amount of money GSOC pays the project could go towards Tim making getting going easier - but in my brief conversation with Tim we didn't really pinpoint the painpoints

**Comment by zorgalina** [comment]
Thank you very much!
 - I did let totten know about issues I had w/installing node.js in the
buildkit package on Ubuntu 14; re: Selenium I figured it was something I
did/didn't do but will let him know just what happened

On Thu, Sep 3, 2015 at 4:50 PM, Eileen McNaughton <notifications@github.com>
wrote:

> re tests - here is a PR I just did making a minor change & adding tests to
> ensure the change is all good
>
> #6678 <https://github.com/civicrm/civicrm-core/pull/6678>
>
> A couple of notes -
>
> 1) I had to fix a static warning to make the tests pass - I think that is
> a good thing about the unit tests.
> 2) You can see I fixed some code comments too.
> 3) Would be good if you gave @totten <https://github.com/totten> some
> feedback on the buildkit issues. We have just finished the google summer of
> code & there was a suggestion that some of the (modest) amount of money
> GSOC pays the project could go towards Tim making getting going easier -
> but in my brief conversation with Tim we didn't really pinpoint the
> painpoints
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6667#issuecomment-137603566>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
In looking at the details of the build #5320 I don't see my own errors,
just those relating to api_v3_ReportTemplate...is there another tab /link
that I should look at. In past builds I just clicked on Details to see
errors.
In any event I know I need to add Phpunit test and comments to the php, and
re-add my updates to 4.7.alpha1.mysql.tpl

On Thu, Sep 3, 2015 at 12:57 AM, Eileen McNaughton <notifications@github.com
> wrote:

> Changes to the upgrade script go stale very quickly - you might need to
> put that into a separate PR to get the tests to pass & get it in.
>
> We've been working really hard at trying to get comment blocks on all
> functions & improving our test coverage - it would be good to see some more
> tests & comment blocks.
>
> NB - if you are having trouble rebasing I always do
>
> git fetch -f origin
> git rebase -i origin/master
>
> you can squash commits together when you use the -i flag - if appropriate
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6667#issuecomment-137370832>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by eileenmcnaughton** [comment]
Yes I think there is a pre-existing error that just has to be ignored. I hate saying that because I believe that we should keep the tests at 100% all the time but sometimes they do linger broken :-(

**Comment by zorgalina** [comment]
In the earlier build, it wasthe api_v3_Report... error you were talking to
Kurund abt on IRC the 2 days ago that was broken. Earlier this AM, I looked
I saw  no errors (didn't note which build #)..but now there are style
errors listed in GenerateData.php, build # 5351. My PR #6676 says
autmatically merged.  How do you tell who/where GenerateData.php was
submitted from?
meanwhile
 I've added function comments and am trying to analyze what functions to
add to tests/Phpunit in the Event folder and how..


On Fri, Sep 4, 2015 at 10:21 PM, Eileen McNaughton <notifications@github.com
> wrote:

> Yes I think there is a pre-existing error that just has to be ignored. I
> hate saying that because I believe that we should keep the tests at 100%
> all the time but sometimes they do linger broken :-(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6667#issuecomment-137911891>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by kurund** [comment]
@zorgalina You must have modified "GenerateData.php" hence it got committed with your other changes.

Does #6676 includes all your changes?

**Comment by zorgalina** [comment]
I didn't modify GenerateData.php, and  I believe it was not among the files
I commited in my branch CRM-16761-3, for PR #6676 2 days ago

Yes, #6676 includes all my changes, it should include the following:
 CRM/Event/Form/ManageEvent/Registration.php;
CRM/Event/Form/SelfSvcUpdate.php and SelfSvcTransfer.php;
CRM/Upgrade/Incremental/sql/4.7.alpha1.mysql.tpl;
CRM/Upgrade/4.7.alpha1.msg_template/message_templates/event_confirmation_invite_html.tpl
and _text.tpl, event_online_receipt_html.tpl, _text.tpl;
CRM/xml/Menu/Event.xml; templates/Event/Form/ManageEvent/Registration.tpl,
templates/Event/Form/SelfSvcTransfer.tpl and SelfSvcUpdate.tpl.

On Sat, Sep 5, 2015 at 5:39 PM, Kurund Jalmi <notifications@github.com>
wrote:

> @zorgalina <https://github.com/zorgalina> You must have modified
> "GenerateData.php" hence it got committed with your other changes.
>
> Does #6676 <https://github.com/civicrm/civicrm-core/pull/6676> includes
> all your changes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6667#issuecomment-138014989>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
apparently I did change GenerateData.php and like 100 other files that I
had no intention of touching.  When I did those 2 commits (Sept. 3,4) I
dragged along 100 other files.  When I looked at what I had staged on Sept.
3, I saw my 12 files; I committed and then did git push origin CRM-16761-3

On Sat, Sep 5, 2015 at 8:20 PM, Lesley Evensen <zorgalina@gmail.com> wrote:

> I didn't modify GenerateData.php, and  I believe it was not among the
> files I commited in my branch CRM-16761-3, for PR #6676 2 days ago
>
> Yes, #6676 includes all my changes, it should include the following:
>  CRM/Event/Form/ManageEvent/Registration.php;
> CRM/Event/Form/SelfSvcUpdate.php and SelfSvcTransfer.php;
> CRM/Upgrade/Incremental/sql/4.7.alpha1.mysql.tpl;
> CRM/Upgrade/4.7.alpha1.msg_template/message_templates/event_confirmation_invite_html.tpl
> and _text.tpl, event_online_receipt_html.tpl, _text.tpl;
> CRM/xml/Menu/Event.xml; templates/Event/Form/ManageEvent/Registration.tpl,
> templates/Event/Form/SelfSvcTransfer.tpl and SelfSvcUpdate.tpl.
>
> On Sat, Sep 5, 2015 at 5:39 PM, Kurund Jalmi <notifications@github.com>
> wrote:
>
>> @zorgalina <https://github.com/zorgalina> You must have modified
>> "GenerateData.php" hence it got committed with your other changes.
>>
>> Does #6676 <https://github.com/civicrm/civicrm-core/pull/6676> includes
>> all your changes?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/civicrm/civicrm-core/pull/6667#issuecomment-138014989>
>> .
>>
>
>
>
> --
> زورگلنه ءء لسلی
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
Hello Eileen - I would like to add test functions to EventTest.php
(civicrm-core/tests/phpunit/api/v3/EventTest.php) relating to the new
columns needed for my mod.  I created a new PR, #6690, just for the
database update as you suggested doing, since there'd be a lot of activity
on that file. However, there are 2 errors listed, build #5358, relating to
the MembershipType table, but it doesn't seem to me the columns I added
relate to the errors on MembershipType. Should I just remove the 2 add
column commands?

On Sat, Sep 5, 2015 at 8:59 PM, Lesley Evensen <zorgalina@gmail.com> wrote:

> apparently I did change GenerateData.php and like 100 other files that I
> had no intention of touching.  When I did those 2 commits (Sept. 3,4) I
> dragged along 100 other files.  When I looked at what I had staged on Sept.
> 3, I saw my 12 files; I committed and then did git push origin CRM-16761-3
>
> On Sat, Sep 5, 2015 at 8:20 PM, Lesley Evensen <zorgalina@gmail.com>
> wrote:
>
>> I didn't modify GenerateData.php, and  I believe it was not among the
>> files I commited in my branch CRM-16761-3, for PR #6676 2 days ago
>>
>> Yes, #6676 includes all my changes, it should include the following:
>>  CRM/Event/Form/ManageEvent/Registration.php;
>> CRM/Event/Form/SelfSvcUpdate.php and SelfSvcTransfer.php;
>> CRM/Upgrade/Incremental/sql/4.7.alpha1.mysql.tpl;
>> CRM/Upgrade/4.7.alpha1.msg_template/message_templates/event_confirmation_invite_html.tpl
>> and _text.tpl, event_online_receipt_html.tpl, _text.tpl;
>> CRM/xml/Menu/Event.xml; templates/Event/Form/ManageEvent/Registration.tpl,
>> templates/Event/Form/SelfSvcTransfer.tpl and SelfSvcUpdate.tpl.
>>
>> On Sat, Sep 5, 2015 at 5:39 PM, Kurund Jalmi <notifications@github.com>
>> wrote:
>>
>>> @zorgalina <https://github.com/zorgalina> You must have modified
>>> "GenerateData.php" hence it got committed with your other changes.
>>>
>>> Does #6676 <https://github.com/civicrm/civicrm-core/pull/6676> includes
>>> all your changes?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/civicrm/civicrm-core/pull/6667#issuecomment-138014989>
>>> .
>>>
>>
>>
>>
>> --
>> زورگلنه ءء لسلی
>>
>
>
>
> --
> زورگلنه ءء لسلی
>



-- 
زورگلنه ءء لسلی

**Comment by eileenmcnaughton** [comment]
If you look at the test server those 2 tests have been failing recently in general. Unfortunately it used to be easy to figure out what PR broke the tests but I don't know how to anymore.

@davecivicrm I think it's going to be very hard for zorgalina to get this completed & QA'd and the upgrade part to commit without conflicts at the same time - should we merge the upgrade lines - on the basis the could be reverted if this can't get through? I don't know the overall picture with this ticket / QA - I've just been chipping in with comments on this PR

**Comment by zorgalina** [comment]
Hi Eileen,  just to test this out I removed my 2 columns from
4.7.alpha1.mysql.tpl, but the errors persist in the last build. I looked
through the other updates in that file but they seem related to
country/county configuration, payment processor and not MembershipType
itself.
Thanks,
Lesley (zorgalina)

On Mon, Sep 7, 2015 at 1:45 PM, Eileen McNaughton <notifications@github.com>
wrote:

> If you look at the test server those 2 tests have been failing recently in
> general. Unfortunately it used to be easy to figure out what PR broke the
> tests but I don't know how to anymore.
>
> @davecivicrm <https://github.com/davecivicrm> I think it's going to be
> very hard for zorgalina to get this completed & QA'd and the upgrade part
> to commit without conflicts at the same time - should we merge the upgrade
> lines - on the basis the could be reverted if this can't get through? I
> don't know the overall picture with this ticket / QA - I've just been
> chipping in with comments on this PR
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6667#issuecomment-138375621>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
Could it be the test database itself that is broken, what is dataset 66? In
MagicFunctionProvider it looks like getCount should return an array but
getcount should be a single item

On Mon, Sep 7, 2015 at 4:25 PM, Lesley Evensen <zorgalina@gmail.com> wrote:

> Hi Eileen,  just to test this out I removed my 2 columns from
> 4.7.alpha1.mysql.tpl, but the errors persist in the last build. I looked
> through the other updates in that file but they seem related to
> country/county configuration, payment processor and not MembershipType
> itself.
> Thanks,
> Lesley (zorgalina)
>
> On Mon, Sep 7, 2015 at 1:45 PM, Eileen McNaughton <
> notifications@github.com> wrote:
>
>> If you look at the test server those 2 tests have been failing recently
>> in general. Unfortunately it used to be easy to figure out what PR broke
>> the tests but I don't know how to anymore.
>>
>> @davecivicrm <https://github.com/davecivicrm> I think it's going to be
>> very hard for zorgalina to get this completed & QA'd and the upgrade part
>> to commit without conflicts at the same time - should we merge the upgrade
>> lines - on the basis the could be reverted if this can't get through? I
>> don't know the overall picture with this ticket / QA - I've just been
>> chipping in with comments on this PR
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/civicrm/civicrm-core/pull/6667#issuecomment-138375621>
>> .
>>
>
>
>
> --
> زورگلنه ءء لسلی
>



-- 
زورگلنه ءء لسلی

**Comment by eileenmcnaughton** [comment]
Sorry - I pinged you on irc - you can ignore the ones that are already failing - see how many times it has failed for a clue

**Comment by zorgalina** [comment]
OK thanks, I just left IRC but saw your msg!

On Mon, Sep 7, 2015 at 5:46 PM, Eileen McNaughton <notifications@github.com>
wrote:

> Sorry - I pinged you on irc - you can ignore the ones that are already
> failing - see how many times it has failed for a clue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6667#issuecomment-138399217>
> .
>



-- 
زورگلنه ءء لسلی

**Pull request closed without merging**
