### PR TITLE
Fix dev/core#4483 SearchKit crash when in-place-editing a field in a joined entity

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes SearchKit crash when in-place-editing a field in a joined entity (under certain conditions).

Before
----------------------------------------
See https://lab.civicrm.org/dev/core/-/issues/4483

After
----------------------------------------
Fixed

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon Any chance you can review this? I see @colemanw is proposing backports...

**Comment by briennekordis** [comment]
I've reviewed this patch and it does fix the issue reported at https://lab.civicrm.org/dev/core/-/issues/4483

**Comment by clarkac1** [comment]
I now have 5.64.1 on a test system that had this problem, which contains this PR  that fixes the problem according to the release notes (Fix dev/core/4483).  For a user who doesn't have 'Edit all contacts' permission but does have edit to a particular  group of contacts, this still doesn't work.  Using SK, the user cannot do an in-place edit  of custom fields that exist in the relationship between contacts - the in place edit is not enabled

**Comment by colemanw** [comment]
@clarkac1 - looks like the relationship api was never taught to respect ACLs. Here, I think this will fix it! https://github.com/civicrm/civicrm-core/pull/27183

**Pull request merged**
