### PR TITLE
CRM-18701 fix setting of membership amount set on the fly for backoff…

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
…ice membership form

### CODE REVIEW

**Comment by tamarmeir** [comment]
Wooohooo! All financial tables showing the amount entered when recording the membership contribution as opposed to the configured membership price (for amounts both less than and greater than the configured price)! I tested for both cash/check and credit card membership contributions.

One thing I noticed in the financial transaction table is that there is a fee that is deducted which can only be seen when clicking to view the contribution, however I don't see this anywhere in the financial account or the payment processor configuration:

**Link to view contribution:** http://core-8533-22dw3.test-ubu1204-5.civicrm.org/civicrm/contact/view/contribution?reset=1&id=96&cid=203&action=view&context=contribution&selectedChild=contribute), 

**Financial transaction table shows the following:**

"is_error":0,
	"version":3,
	"count":1,
	"id":95,
	"values":[{
		"id":"95",
		"to_financial_account_id":"12",
		"trxn_date":"2016-06-12 01:40:00",
		"total_amount":"150.00",
		"fee_amount":"1.50",
		"net_amount":"148.50",
		"currency":"USD",
		"is_payment":"1",
		"trxn_id":"live_1_575cbd70c3060",
		"status_id":"1",
		"payment_processor_id":"1",
		"payment_instrument_id":"1"

Eileen thought it might be something the payment processor is returning, but we're not sure - @KarinG, Eileen thought it would be preferable for you to test with iATS on master after this PR has been merged?

If it persists, I would think it a separate ticket so IMO this PR can be merged.

Thanks, Eileen, for your non-stop work on this!

**Comment by eileenmcnaughton** [comment]
I guess I had better leave this for review week now so it can get some code review too.

**Comment by KarinG** [comment]
I just pulled https://github.com/civicrm/civicrm-core/pull/8533 into my local master - and have confirmed that CRM-18701 is fixed. Thank you [~eileen] for your ongoing refactoring - every single time you have a pass at the code base.

**Comment by colemanw** [comment]
Code looks good to me. DIdn't study it in-depth but if @KarinG says it's working I feel good about merging this.

**Pull request merged**
