### PR TITLE
Running the fetch_activities cli task stops with a fatal error when t…

### PR DESCRIPTION
**Pull request by davidjosephhayes**
…he incomming mail parser is unable to determine the ezcMailDeliveryStatus. The fetch_activities task will continue to download and attempt to parse the offending email, dying every time. This prevents other mails from being downloaded and parsed.

Error Message: "No clue about the ezcMailDeliveryStatus"

This patch catches that error, prints it, marks the offending email ignored, and allows activities processing to continue.

Should fix issues:
https://issues.civicrm.org/jira/browse/CRM-9484 (last comment in June 2015, 
Second bullet point here: https://forum.civicrm.org/index.php?topic=35916.0

### CODE REVIEW

**Comment by totten** [comment]
jenkins, ok to test

**Comment by davidjosephhayes** [comment]
Woops, styling issues. How do I change a pull request?

**Comment by totten** [comment]
The PR is tied to your branch `davidjosephhayes:master`. Just update that branch and push it to Github. The PR will detect the changes and re-run the test.

**Comment by davidjosephhayes** [comment]
Neat!

**Comment by totten** [comment]
Aside: The first time I submitted a PR which had a bot checking for code-style, it took me like 5 revisions to get it passing. (It was big patch and an unfamiliar style... *ahem*) Anyway, if you ever want to check the style locally, look at "Code Style Tests" in http://wiki.civicrm.org/confluence/display/CRMDOC/Testing

**Comment by davidjosephhayes** [comment]
Kewl. I will do that next time (or this time if it doesn't pass again). Thanks!

**Comment by davidjosephhayes** [comment]
Ok, so it failed again, however the failures seem unrelated to my pull request?

**Comment by kurund** [comment]
yes, these are unrelated test failures

**Pull request merged**
