### PR TITLE
Reformat DAO files to pass linting and use short array syntax

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----

Our code standards covered every file in the core repo *except* the autogenerated DAOs. This cleans them up to pass `civilint` standards. It also makes them the first set of files to use the short array syntax now that we've officially dropped support for php 5.3 :)

Before
----

DAO*.php files were a bit unsightly.

After
---

Code looks much better.

Technical Details
---

We really need to get ourselves a better php prettifier. I had to do some regex hacks to get the output to come out ok.

### CODE REVIEW

**Comment by colemanw** [comment]
@civicrm-builder test this please

**Comment by colemanw** [comment]
@totten let's merge this after the 4.7.30-rc is cut.

**Comment by colemanw** [comment]
@mlutfy will you please ask jenkins to retest this once you've upgraded php on the apache side of our ci?

**Comment by colemanw** [comment]
@mlutfy this is highly prone to merge conflicts so ping me as soon as you get PHP upgraded on our CI server and I'll do a regen + rebase.

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by monishdeb** [comment]
I have rebased the PR, lets wait for the test build to pass.

**Comment by colemanw** [comment]
@monishdeb did you regenerate the dao files when you rebased?

**Pull request merged**
