### PR TITLE
Contact Type Values with Cap in order to be well translated with ts()

### PR DESCRIPTION
**Pull request by UshaMakoa**
Overview
----------------------------------------
_something in the ts() function seems to be case sensitive while when the ContacType values are not with the initial Cap they're not translated_

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Thanks for the patch.

* General standards
    * [`r-explain`] __PASS__
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __PASS__
      * I see the problem and it does fix it. One note for anyone else reviewing: if the site was initially installed in english then you also need to go to Administer - Customize - Contact Types and change the label (which says name on the form) in order to see it working, since otherwise the label is still english even if you change the system language.
* Developer standards
    * [`r-tech`] __PASS__
    * [`r-code`] __PASS__
    * [`r-maint`] __Undecided__
    * [`r-test`] __Pending a test run__

It might need to be an admin who types this but let's see: jenkins test this please.

**Comment by seamuslee001** [comment]
Jenkins ok to test

**Comment by eileenmcnaughton** [comment]
I agree with the change & with the review - MOP

Thanks @UshaMakoa  & @demeritcowboy

**Comment by eileenmcnaughton** [comment]
@UshaMakoa is this the first PR of yours we have merged?

**Comment by UshaMakoa** [comment]
> @UshaMakoa is this the first PR of yours we have merged?

Yes it is! should i have done it differently?

**Comment by eileenmcnaughton** [comment]
No I just thought that was work a bit of a YAY

**Comment by demeritcowboy** [comment]
Also you could add yourself to the [contributors.txt](https://github.com/civicrm/civicrm-core/blob/master/CONTRIBUTORS.txt) file if you're not already in there. Just do a PR to add yourself.

**Comment by demeritcowboy** [comment]
Oops I meant https://github.com/civicrm/civicrm-core/blob/master/contributor-key.yml

**Comment by UshaMakoa** [comment]
do i have to delete the branch now ?

**Comment by demeritcowboy** [comment]
Up to you but civi doesn't need it anymore.

**Pull request merged**
