### PR TITLE
Afform - Add support for ReCaptcha v2

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Supports the Recapta2 element in FormBuilder.

image

Technical Details
----------------------------------------
Depends on #24862 for Afform to support extensions adding new element types.

Comments
----------------------------------------
This refactors #24689, moving the code to an extension and making it event-driven.

### CODE REVIEW

**Comment by seamuslee001** [comment]
This seems like the right direction to me I'm just wondering @colemanw if its worth splitting out the work on the general afform type from the recaptcha work just to try and make things a little mergeable?

**Comment by colemanw** [comment]
Ok I've broken the Afform part into #24862

**Comment by kurund** [comment]
@colemanw 

Thanks, https://github.com/civicrm/civicrm-core/pull/24862 looks good.

While checking this PR, I am getting validation error even if the Recaptcha is checked and valid.

Also would be good to rebase other PR is merged.

**Comment by colemanw** [comment]
Thanks @kurund. I've merged the other PR, rebased this one, and fixed the bug you noticed. I think this is done.

As a followup, I noticed that the validation errors (including this one) don't bubble all the way up to actually get shown to the user. I think we'll need to extend the `CRM_Core_Exception` class to distinguish between safe messages and debug messages (currently none are visible to users without "view debug output" permission)

**Comment by kurund** [comment]
> thanks @kurund. I've merged the other PR, rebased this one, and fixed the bug you noticed. I think this is done.

Yes, it's working as expected now.


> As a followup, I noticed that the validation errors (including this one) don't bubble all the way up to actually get shown to the user. I think we'll need to extend the CRM_Core_Exception class to distinguish between safe messages and debug messages (currently none are visible to users without "view debug output" permission)

I feel CRM_Core_Exception is not passing the errorData correctly. So we might directly need to return the error message.

**Review by kurund — APPROVED** [review]
@colemanw 

Good merge after test fixes. We can handle the sever error message display separately if you don't agree with the above suggestion.

**Comment by colemanw** [comment]
@kurund the reason I'm putting errors as an array is because concatenating html with plain text into a string leads to escaping issues. Better to output the array of errors and let the javascript template render the markup.

**Pull request merged**
