### PR TITLE
CRM-18147 - Advanced filtering on email or email_id does not work for the Contact API

### PR DESCRIPTION
**Pull request by monishdeb**
This patch added the missing fix needed for email attribute when used for advance filtering in Contact API. Missing because this was not handled when improvement was made in early 4.7 release to support advance filtering in API Get.

---
- [CRM-18147: Advanced filtering on email or email_id does not work for the Contact API](https://issues.civicrm.org/jira/browse/CRM-18147)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I'm not too clear about the rationale for this - ie. is it an extra feature or in someway a bug fix.

however, I wouldn't want to see it merged without the magic unit test....

**Comment by monishdeb** [comment]
Its a bug and miss in recent improvements done to support advance filtering for api.get and Search builder for al entites in 4.7. I have updated the PR which include the api test. In addition the PR fixes -  
1. Earlier `civicrm_api3('email', 'create', array('is_primary' => 0, 'email' => email@address, 'contact_id' => id))` always create primary email address as eventually the is_primary attribute got updated to 1
2. Support email_id attribute w/o advance filters

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by monishdeb** [comment]
Jenkin, restest this please

**Comment by jitendrapurohit** [comment]
checked this PR, works fine. Also updated the changes to fix test failing on Jenkins.

**Pull request merged**
