### PR TITLE
[Import] Test + fix for failure to reject invalid ex identifier

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Test from @darrick  + fix - see https://github.com/civicrm/civicrm-core/pull/23473#issuecomment-1135388566

Before
----------------------------------------
Per test - a related contact with an external identifier does not fail if the identifier is not found

After
----------------------------------------
If an external identifier is provided then a contact with that match MUST be found

Technical Details
----------------------------------------

Comments
----------------------------------------
@darrick I took a first stab at this one - I realise though that I need to think through the update modes

- for UPDATE or FILL I think this is correct

But I think maybe I need to not throw the exception in SKIP and NO_MATCH modes - UPDATE - the tests agreed with my hunch (yay tests) - fixed

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Pleased to see test fails since I had a couple of doubts

[Test Result](https://test.civicrm.org/job/CiviCRM-Core-PR/49021/testReport/) (14 failures / +14)
[CRM_Contact_Import_Parser_ContactTest.testImportParserWithDeletedContactExternalIdentifier](https://test.civicrm.org/job/CiviCRM-Core-PR/49021/testReport/junit/(root)/CRM_Contact_Import_Parser_ContactTest/testImportParserWithDeletedContactExternalIdentifier/)
[CRM_Contact_Import_Parser_ContactTest.testImportParserWithUpdateWithCustomRuleNoExternalIDMatch](https://test.civicrm.org/job/CiviCRM-Core-PR/49021/testReport/junit/(root)/CRM_Contact_Import_Parser_ContactTest/testImportParserWithUpdateWithCustomRuleNoExternalIDMatch/)
[CRM_Contact_Import_Parser_ContactTest.testImportParserWithUpdateWithExternalIdentifier](https://test.civicrm.org/job/CiviCRM-Core-PR/49021/testReport/junit/(root)/CRM_Contact_Import_Parser_ContactTest/testImportParserWithUpdateWithExternalIdentifier/)
[CRM_Contact_Import_Parser_ContactTest.testImportParserWithUpdateWithExternalIdentifierButNoPrimaryMatch](https://test.civicrm.org/job/CiviCRM-Core-PR/49021/testReport/junit/(root)/CRM_Contact_Import_Parser_ContactTest/testImportParserWithUpdateWithExternalIdentifierButNoPrimaryMatch/)
[CRM_Contact_Import_Parser_ContactTest.testImportParserWithUpdateWithNoExternalIdentifier](https://test.civicrm.org/job/CiviCRM-Core-PR/49021/testReport/junit/(root)/CRM_Contact_Import_Parser_ContactTest/testImportParserWithUpdateWithNoExternalIdentifier/)
[CRM_Contact_Import_Parser_ContactTest.testImportParserWithUpdateWithChangedExternalIdentifier](https://test.civicrm.org/job/CiviCRM-Core-PR/49021/testReport/junit/(root)/CRM_Contact_Import_Parser_ContactTest/testImportParserWithUpdateWithChangedExternalIdentifier/)
[CRM_Contact_Import_Parser_ContactTest.testImportBillingAddress](https://test.civicrm.org/job/CiviCRM-Core-PR/49021/testReport/junit/(root)/CRM_Contact_Import_Parser_ContactTest/testImportBillingAddress/)
[CRM_Contact_Import_Parser_ContactTest.testImportPrimaryAddress](https://test.civicrm.org/job/CiviCRM-Core-PR/49021/testReport/junit/(root)/CRM_Contact_Import_Parser_ContactTest/testImportPrimaryAddress/)
[CRM_Contact_Import_Parser_ContactTest.testAddressWithCustomData](https://test.civicrm.org/job/CiviCRM-Core-PR/49021/testReport/junit/(root)/CRM_Contact_Import_Parser_ContactTest/testAddressWithCustomData/)
[CRM_Contact_Import_Parser_ContactTest.testImportTwoAddressFirstPrimary](https://test.civicrm.org/job/CiviCRM-Core-PR/49021/testReport/junit/(root)/CRM_Contact_Import_Parser_ContactTest/testImportTwoAddressFirstPrimary/)
[Show all failed tests >>>](https://test.civicrm.org/job/CiviCRM-Core-PR/49021/#showFailuresLink)

**Comment by eileenmcnaughton** [comment]
OK - the tests were failing because external_identifier should not block contact creating in SKIP or NO_MATCH - which was what I was wondering about before

**Comment by eileenmcnaughton** [comment]
@monishdeb - I'm just a bit wary of doing the rest of that `if` cleanup & making this go stale - so would be good to get this merged first (although it's a bigger one to review)

**Comment by colemanw** [comment]
Ok, this fixes a regression and test cover is good.

**Pull request merged**
