### PR TITLE
dev/core#2517 Fix cancel action status to Expired

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
dev/core#2517 Fix cancel action status to Expired

Before
----------------------------------------
Contributioncancelactions updating pending memberships to 'Cancelled' on failed payment

After
----------------------------------------
Contributioncancelactions updating pending memberships to 'Expired' on failed payment

Technical Details
----------------------------------------
Note our general recommendation is to disable the extension unless you want the specific behaviour in in - however, 
per discussion https://lab.civicrm.org/dev/core/-/issues/2517#note_57532
Expired is more consistent with 'no change' than 'Cancelled' - which winds up
blocking new membership requests

Comments
----------------------------------------
@monishdeb this is probably the minimum we need to get merged through to the rc & included in any 5.36 drop

### CODE REVIEW

**Comment by mattwire** [comment]
Note that @Stoob commented on lab that pending may be better in some cases. However, if the change to "Expired" is mostly consistent with what it was doing before then agree that should be done for now and consider further changes in master.

**Comment by Stoob** [comment]
Opinions aside @mattwire how do you plan on setting a membership to Expired that doesn't have an end date (or any dates for that matter) without using status override?  That's why pending makes more sense to me.

**Comment by eileenmcnaughton** [comment]
as @mattwire pointed out the goal is to get back to the intended 'keep the original behaviour' - the extensionisation allows people to opt out of the original behaviour by disabling the extension (recommended)

**Comment by eileenmcnaughton** [comment]
Ok - this seems to be blocked on people wanting the extension to be fixed to do the same thing as disabling the extension - I'm going to close this

**Comment by Stoob** [comment]
pending-members-failed-contribution

Here is an example of the original behavior

**Pull request closed without merging**
