### PR TITLE
dev/core#1950 Update help text and description for the profile add to groups setting

### PR DESCRIPTION
**Pull request by larssandergreen**
Overview
----------------------------------------
Edited help text and description for add to group in profile settings, per https://lab.civicrm.org/dev/core/-/issues/1950

Before
----------------------------------------
Option labelled  "Add new contacts to a Group?" with a help text "Select a group if you are using this profile for adding new contacts, AND you want the new contacts to be automatically assigned to a group."

After
----------------------------------------
Option labelled  "Add contacts to a group?" with a help text "
Select a group if you want contacts to be automatically added to that group when the profile is submitted."

### CODE REVIEW

**Comment by seamuslee001** [comment]
@larssg-wildsight can I suggest that you update https://github.com/civicrm/civicrm-core/blob/329618349ffa338a1006ef859f76b546babf96cf/CRM/UF/Form/AdvanceSetting.php#L50 and https://github.com/civicrm/civicrm-core/blob/329618349ffa338a1006ef859f76b546babf96cf/templates/CRM/UF/Form/Group.hlp#L66 to match that would be helpful as well

**Comment by larssg-wildsight** [comment]
Thanks @seamuslee001, have done.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 is this OK now?

**Comment by seamuslee001** [comment]
This looks fine to me, for future reference it would have been nicer to have all the changes in 1 commit but won't hold you to that this time merging

**Pull request merged**
