### PR TITLE
E2E_Core_ErrorTest - Demonstrate whether error pages are well-formed

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

CiviCRM has a few distinct ways to raise errors, eg `throw new \Exception()`, `CRM_Core_Error::fatal()`, and `CRM_Utils_System::permissionDenied()`.

It also has various (CMS-dependent) ways of getting those errors onto the screen.

For each error screen, there are common expectations, such as "show a well-formatted page" and "send HTTP status code".

This patch adds an E2E test to ensure that the various permutations of (CMS-type, error-type) have well-formed outputs. It is a unit-test for the kind of bug described by @braders in #22805.

Before
----------------------------------------

No E2E/pan-CMS test-coverage.

After
----------------------------------------

The `E2E_Core_ErrorTest` reports on whether errors are actually reported well in each CMS. (The output would be apparent in the [CiviCRM-E2E-Matrix](https://test.civicrm.org/job/CiviCRM-E2E-Matrix/).)

Comments
----------------------------------------

PR tests don't actually run E2E tests across all CMS's -- that's only seen post-merge (or if you run locally).

In my local test-runs on WordPress, this demonstrated that #22805 caused `WordPress_testErrorChrome_*` to flip from failing to passing. It shows no change in `WordPress_testErrorStatus_*`.

### CODE REVIEW

**Comment by totten** [comment]
Some commands that I found helpful:

```bash
## On wpmaster, run the tests (but skip pre-existing problems)
cd ~/bknix/build/wpmaster/web/wp-content/plugins/civicrm/civicrm
phpunit8 tests/phpunit/E2E/Core/ErrorTest.php 

## On wpmaster, run _all_ tests (even if they're known to have pre-existing problems)
cd ~/bknix/build/wpmaster/web/wp-content/plugins/civicrm/civicrm
FORCE_ALL=1 phpunit8 tests/phpunit/E2E/Core/ErrorTest.php

## On wpmaster, run _all_ tests (even problematic ones), but give a thinner summary (less debug info)
cd ~/bknix/build/wpmaster/web/wp-content/plugins/civicrm/civicrm
FORCE_ALL=1 phpunit8 tests/phpunit/E2E/Core/ErrorTest.php --printer '\Civi\Test\TAP'
```

**Comment by totten** [comment]
civibot, test this please

**Comment by eileenmcnaughton** [comment]
I find adding a fake error page into the menu pretty weird - but I get the benefits of more test cover & there is no other 'live' impact

**Comment by totten** [comment]
> (@eileenmcnaughton) I find adding a fake error page into the menu pretty weird - but I get the benefits of more test cover & there is no other 'live' impact

Yup, it's true - there's just not much else you can do to get coverage over the CMS-integration bits. 🤷 

At some point, it might be interesting to develop more of a pattern around "hidden"/"mock" extensions as way to organize E2E testing. (Sort of like `afform_mock` -- if one put this test into some small/hidden extension, it would keep the main runtime a bit cleaner and wouldn't require any major contortions to define the test.)

**Pull request merged**
