### PR TITLE
(dev/core#647) Fix up Test Class names and file names to ensure all t…

### PR DESCRIPTION
**Pull request by seamuslee001**
…est classes are run by Jenkins

Overview
----------------------------------------
This fixes up some test Classes and one file name to get Jenkins / phpunit to find them and run them

Before
----------------------------------------
Test classes skipped

After
----------------------------------------
Test classes not skipped

### CODE REVIEW

**Comment by seamuslee001** [comment]
ping @eileenmcnaughton @totten

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I'm giving this a very optimistic merge-on-pass. Previous finds of these have also found that the test isn't actually passing - for various reasons. Anyway cross figures there are no worms in this can

**Comment by seamuslee001** [comment]
I like optimism

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton i have pulled the contact selector test out into its own PR #13416

**Comment by seamuslee001** [comment]
Merging as per the tag

**Pull request merged**
