### PR TITLE
dev/wordpress#66 Re-instate newer variables but with more support for…

### PR DESCRIPTION
**Pull request by seamuslee001**
… legacy file systems

Overview
----------------------------------------
This re-applies the newer directory lookup functions for wordpress whilst maintaining some backwards compatibility 

Before
----------------------------------------
Non wordpress functions used to derive the upload files directory

After
----------------------------------------
Wordpress functions used to derive the upload files directory but some legacy call back if needed

ping @totten @christianwach @kcristiano

### CODE REVIEW

**Comment by kcristiano** [comment]
@seamuslee001 I applied the patch to master and started to upgrade a 5.28 RC site with the legacy structure.

After replacing the codebase, all pages caused 500 errors.

```
[05-Aug-2020 14:12:40 UTC] PHP Fatal error:  Uncaught CRM_Core_Exception: [0: Cannot read unrecognized property CRM_Core_Config::$ufSystem.

  thrown in /srv/www/example/wp-content/plugins/civicrm/civicrm/CRM/Core/Config/MagicMerge.php on line 220
```

I then tried the Nightly download from download.civicrm.org/latest and that was fine.  

The line that is causing the error is 

```php
$old = CRM_Core_Config::singleton()->ufSystem->getDefaultFileStorage();
```

I tried:

```php
$old = CRM_Core_Config::singleton()->userSystem->getDefaultFileStorage();
```
and that gets rid of the 500 error, but we still get a default to the 'new' paths and urls.

I'll need more time to work on this @christianwach any thoughts?

**Comment by christianwach** [comment]
@kcristiano @seamuslee001 Yup, agree with Kevin - fixing the typo should make this work as expected.

**Comment by kcristiano** [comment]
@seamuslee001 I took another run at this and with the suggested change and I am OK with it.  Can you make the change and then we can do another r-run and get this in 5.29.  I think the earlier it's in the better.

**Comment by seamuslee001** [comment]
@kcristiano @christianwach fixed now

**Comment by kcristiano** [comment]
I've done the following `r-run`

## Old Only  
- Values returned:
  - path = `/srv/www/example.org/wp-content/plugins/files/civicrm`
  - url = `https://example.org/wp-content/plugins/files/civicrm`
**PASS**

## New Only
- Values returned:
  - path = `/srv/www/example.org/wp-content/uploads/civicrm`
  - url = `https://example.org/wp-content/uploads/civicrm`
**PASS** 


## Old and New 
- Only have `civicrm.settings.php` in new directory
- Values returned:
   - path = `/srv/www/example.org/wp-content/uploads/civicrm`
  - url = `https://example.org/wp-content/uploads/civicrm`
**PASS**  As this is Expected

However, extensions are broken as the path and URL cannot be found.

Add the following to `civicrm.settings.php` 
```php
global $civicrm_setting;
$civicrm_paths['civicrm.files']['path'] = '/srv/www/example.org/wp-content/plugins/files/civicrm';
$civicrm_paths['civicrm.files']['url'] = 'https://example.org/wp-content/plugins/files/civicrm';
```
Re-run
- Values returned:
   - path = `/srv/www/example.org/wp-content/uploads/civicrm`
  - url = `https://example.org/wp-content/uploads/civicrm`
**FAIL**  As this is not Expected

Extensions cannot be found.  We can do an override in `civicrm.settings.php` or via the UI, but the question is why does the override not work for `[civicrm.files]`

flushed cache via UI and `cv`
Reset Paths via UI

Paths-URL json https://gist.github.com/kcristiano/64b2aa5969c2dbcf9f2c3eeeba142920

screenshot of extensions

image


I still want to test old and new where the default is the new directories and the old are only there for images/etc.

**Comment by kcristiano** [comment]
## Old and New 
- Old was kept 'just in case for images etc'
- `define( 'CIVICRM_TEMPLATE_COMPILEDIR', '/srv/www/example.org/wp-content/uploads//civicrm/templates_c/');` being used
- Values returned:
   - path = `/srv/www/example.org/wp-content/uploads/civicrm`
  - url = `https://example.org/wp-content/uploads/civicrm`
**PASS**  

So it looks like a mix of old and new where Old is being utilized is giving issues.

@totten any thoughts?

**Comment by seamuslee001** [comment]
@kcristiano just checking i noticed you included a global on `$civicrm_settings` did you also include a global for `$civicrm_paths` when you overrode with just the path?

**Comment by kcristiano** [comment]
@seamuslee001 Correct!  
```php
global $civicrm_paths;
$civicrm_paths['civicrm.files']['path'] = '/srv/www/eastwood/wp-content/plugins/files/civicrm';
$civicrm_paths['civicrm.files']['url'] = 'https://eastwoodrugby.test/wp-content/plugins/files/civicrm';
```
Is what is needed.   I'll also do a PR to add this to https://docs.civicrm.org/sysadmin/en/latest/upgrade/version-specific/

This looks good to merge.

**Comment by seamuslee001** [comment]
I'm going to merge this based on @kcristiano testing

**Pull request merged**
