### PR TITLE
remove civimail-spooler script

### PR DESCRIPTION
**Pull request by MegaphoneJon**
Overview
----------------------------------------
A fun quiz for Civi old-timers - is there any Perl in the codebase?

Before
----------------------------------------
Yes.

After
----------------------------------------
No.

Technical Details
----------------------------------------
How did a procmail filter get included in core? 

Comments
----------------------------------------
I will bet dollars to dimes that no one who hasn't already installed this is going to install it in the future.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
@aydun https://github.com/civicrm/civicrm-svn/tree/v2.0/tools

**Comment by MegaphoneJon** [comment]
Uh - I think @aydun is right?  I got turned around, I intended for this PR to remove [this file](https://github.com/civicrm/civicrm-core/blob/master/tools/scripts/procmail/original-to.pl).  This file is also a long-forgotten relic that's ok to delete - just a different one.

**Comment by demeritcowboy** [comment]
Well, I guess when you're on a roll even your wrong PRs work out anyway.

**Comment by aydun** [comment]
Ah!  Now that makes more sense!

**Pull request merged**
