### PR TITLE
Fix use of not-universally supported mysql field type

### PR DESCRIPTION
**Pull request by eileenmcnaughton**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
In discussion on chat it turns out the version of mysql that doesn't support this is 5.6 & we have been saying for 17 months that it is out of date - if we don't merge this it will be  breaking change on 5.6 - with imports & it will require @totten  to turn off tests on 5.6 which we hadn't done previously

image

We do actually say that we don't support 5.6 anymore - https://docs.civicrm.org/installation/en/latest/general/requirements/#mysql-version

@agileware-justin @Stoob if you want to make a last pitch to keep mysql 5.6 working (or at least without known breakage) - htere is your chance

**Comment by totten** [comment]
@seamuslee001 pointed out that the message indicates MariaDB 10.1 -- which also lacks JSON support.

**Comment by eileenmcnaughton** [comment]
@totten I think we need to merge this then - although we would ideally ALSO up our messaging / decrease our testing around 5.6

**Comment by agileware-justin** [comment]
Just checked a few of the older CPanel hosting accounts. No 10.1 or 5.6.

**Comment by eileenmcnaughton** [comment]
@agileware-justin woohoo

**Comment by totten** [comment]
Agree we should merge this compatibility update for 5.51; and going forward, we should also nudge 10.1=>10.2.

Merging.

**Pull request merged**
