### PR TITLE
CRM-9764 Ensure all custom searches respect ACLs

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@kurund  I did a quick scan of the code & it looks pretty good. I know I've updated individual reports in this type of way.

Am Ok with backporting to 4.4 - although not for a May release.

**Comment by seamuslee001** [comment]
Anything I can do to get this moving?

**Comment by eileenmcnaughton** [comment]
Might be good to bump this again in a week - @kurund just got married & I'm not sure how many of the core team have attended - although I don't think @davecivicrm  did.... Dgg - if you are looking this generally looks OK to me & Seamus has tested with ACLs turned on

**Comment by colemanw** [comment]
If #5839 is the same as this, there is no need for both. Changes in 4.6 will be merged forward into master.

**Comment by seamuslee001** [comment]
@colemanw I wasn't aware that was the case when i made the 2 PRs, They should be the same. I would go with the 4.6 one and then I'll look at doing a 4.4 backport

**Pull request closed without merging**
