### PR TITLE
Revert "CRM-20321, CRM-20652 : Changing membership type should change related contribution and generalise changeFeeSelection function to be used for any entity"

### PR DESCRIPTION
**Pull request by colemanw**
Reverts civicrm/civicrm-core#10370

---

 * [CRM-20321: Changing membership type should change related contribution](https://issues.civicrm.org/jira/browse/CRM-20321)
 * [CRM-20652: Generalise changeFeeSelection function to be used for any entity other](https://issues.civicrm.org/jira/browse/CRM-20652)

### CODE REVIEW

**Comment by colemanw** [comment]
This PR was self-merged. I'm reverting to do a bit of additional review.

**Comment by JoeMurray** [comment]
@colemanw 1. the process up to now has been to allow merges if another senior dev not from same org indicates they are passing the PR as ready to merge. That happened in this case, with @seamuslee001 approving the merge. Or has there been a change in policy on this?

I'm happy to have you do more QA, but concerned that we need clarity on process. Generally, we have been trading reviews with folks in order to get stuff merged with @eileenmcnaughton @jitendrapurohit and in last week or so we are trying to broaden our list of collaborators to help out more folks with getting their stuff reviewed.

**Comment by colemanw** [comment]
@JoeMurray I don't think there was any serious infraction here. Seamus did the review and gave his approval, but then the merge was done "in-house" - as a general rule we want merges to be done by a 3rd party (CT or another partner with merge rights).

We get lax about that rule when PRs are light/simple/safe but in the case of significant changes to critical systems I think it's best to hold that line more strictly.

Thanks for your patience. I'll do a final review this week & get this one back in.

**Comment by eileenmcnaughton** [comment]
To be fair I don't think we do always involve a third party reviewer. I would accept @seamuslee001 approval as adequate to self-merge a PR I have submitted. I would probably seek more input if it didn't seem straight forward (and Seamus is very good at involving others when he things there is a bigger issue). Depending on the complexity of the PR I would go ahead & self-merge based on a less experienced reviewer too.

I guess that is all semantics - ie we all agree that we want more review on more complex or less clear cut PRs

**Pull request merged**
