### PR TITLE
dev/core#1980 Add v4 api LineItem entity

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Adds apiv4 LineItem entity

Before
----------------------------------------
nada

After
----------------------------------------
Voila!

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
Test fails relate

**Comment by eileenmcnaughton** [comment]
test fixes flushed out https://github.com/civicrm/civicrm-core/pull/18395

**Comment by eileenmcnaughton** [comment]
Tests still failing in #18395 but I think https://github.com/civicrm/civicrm-core/pull/18365 removes the hacky set up that a bunch are failing on. Once merged I'll reconsider it

**Comment by mattwire** [comment]
Test fails relate

**Comment by eileenmcnaughton** [comment]
I'm going to close this for now because it's blocked until I can resolve the test failures - which https://github.com/civicrm/civicrm-core/pull/18395 would fix, if working - but it needs  #18365 

I don't want to clog up the review queue with PRs that are not reviewable so I'll re-open this when the blocking-issues are solved

**Comment by seamuslee001** [comment]
@eileenmcnaughton needs a rebase

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I'm there!

**Comment by eileenmcnaughton** [comment]
Woot - it finally passed

**Pull request merged**
