### PR TITLE
Add weights to MemberSelectorSearch

### PR DESCRIPTION
**Pull request by eileenmcnaughton**

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton any reason not to use the getWeight function here?

**Comment by eileenmcnaughton** [comment]
@colemanw cos they are weird actions... not standard ones

**Comment by colemanw** [comment]
Looks like you found a brittle test: [CRM_Member_Selector_SearchTest.testSelectorGetRows](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/4295/BKPROF=dfl,SUITES=phpunit-crm,label=bknix-tmp/testReport/junit/(root)/CRM_Member_Selector_SearchTest/testSelectorGetRows/)

**Comment by eileenmcnaughton** [comment]
That's probably a good fail - I'm not intentionally re-ordering so should tweak to pass that

**Pull request merged**
