### PR TITLE
[REF] [Import] Standardise import text for CustomData import

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Standardise import text for CustomData import - also note there is a master-only regression on this page prior to this patch

Before
----------------------------------------
image

After
----------------------------------------
image

Technical Details
----------------------------------------
This Does alter the text a little -  if it's not OK - it might make sense to move it to the php layer & assign the text

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
It's fine. That whole screen sucks so let's not think too hard about the help text.

**Comment by eileenmcnaughton** [comment]
Lol

**Comment by colemanw** [comment]
@eileenmcnaughton looking at those screenshots... one way to make the scree suck less IMO would be to use a select2 instead of radio buttons for selecting a date format. That rather obscure setting is dominating the screen real-estate on the form, and select2 would make it much more compact.

**Comment by eileenmcnaughton** [comment]
@colemanw it's a lot less obscure when you live in NZ :-) - but yeah if I get to it I might try it

**Pull request merged**
