### PR TITLE
Fixes CRM-19308: Disallow false-y values for paths purged during cach…

### PR DESCRIPTION
**Pull request by ergonlogic**
…e clears.

Fixes: https://issues.civicrm.org/jira/browse/CRM-19308

### CODE REVIEW

**Comment by totten** [comment]
jenkins, add to whitelist

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by monishdeb** [comment]
@seamuslee001 is it good to merge ?

**Comment by eileenmcnaughton** [comment]
I'm going to merge this on the basis that I agree the cleanDirs function SHOULD throw an exception if the target is equal to FALSE (or $!$target )

This is a bit hard to replicate - but at a code level it seems like a fairly clear cut change & does not appear risky to merge this

**Pull request merged**
