### PR TITLE
CRM-11369

### PR DESCRIPTION
**Pull request by mohit-agarwal**
The PR changes "Pending from pay later" wording to "Pay Later(pending)".

### CODE REVIEW

**Comment by mohit-agarwal** [comment]
I have added the space and changed it to "Pay Later (pending)".

**Comment by davecivicrm** [comment]
test this please

**Comment by davecivicrm** [comment]
The commits look good but I've commented on the issue tracker that I think a better replacement would be Pending (pay later). Also, to be complete there needs to be an entry in the upgrade. If we target this for 4.7, then the upgrade .sql would go into CRM/Upgrade/Incremental/sql/4.7.alpha1.mysql.tpl.

**Comment by JKingsnorth** [comment]
These statuses are much tidier.

**Comment by tahirramzan** [comment]
It's resolved but it is still open?

**Comment by JKingsnorth** [comment]
Not resolved, there are merge conflicts. Looks like the PR needs some work before it can be merged in.

**Comment by davecivicrm** [comment]
It's probably related to the copy of civicrm_generated.mysql that's included. Since this is for 4.7 - let's hold off a bit, and I can rebase / merge in a week or so.

**Comment by colemanw** [comment]
See https://github.com/civicrm/civicrm-core/pull/6412

**Pull request closed without merging**
