### PR TITLE
CRM-17693 Increase default string table size to be 255. 255 Character…

### PR DESCRIPTION
**Pull request by seamuslee001**
…s seems fairly common on the db and matches max length of contribution page title

### CODE REVIEW

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
jenkins retest this please

**Comment by seamuslee001** [comment]
@davecivicrm I think the 2nd commit fixes the problems you mentioned

Seamus

**Comment by davecivicrm** [comment]
Works with that last change!

**Pull request merged**
