### PR TITLE
Civi::queue() - Add support for 'template' queues

### PR DESCRIPTION
**Pull request by totten**
Overview
--------

Suppose you are in the habit of making separate queue-instances for different batches of work.  However, you want to allow the sysadmin to configure options like `type`, `batch_limit`, and `retry_interval`.

Solution: Make a template

After
-----

```php
// Use the API to register a template, eg
\Civi\Api4\Queue::create()->setValues([
  'name' => 'my-example',
  'is_template' => TRUE,
  'type' => 'Sql',
  'error' => 'abort',
  'retry_limit' => 5,
  'retry_interval' => 60,
])->execute();

// Later, create a queue from the template
$q = Civi::queue('new-queue', ['template' => 'my-example']);
assert($q inherts the  'type', 'error', 'retry_limit', etc from the template)
```

Comments
----------------------------------------

I'm ambivalent about how to mark a template - eg:

* _Easier patch_: Use `status=>template`
* _Match other entities_: Use a new field `is_template=>1`

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I think is_template is more correct - but there is precedent for the status method - we do that in Contribution - but in fact I think we do BOTH there because we felt that was an especially risky entity. I'm not opposed to the easy route - but suspect we might need to do another alter in which case that might tip it away from easer

**Comment by totten** [comment]
@eileenmcnaughton Converted patch from `status=>template` to `is_template=>1`. Rebased. Updated description.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
fail is unrelated - fix is in https://github.com/civicrm/civicrm-core/pull/23751

**Pull request merged**
