### PR TITLE
Partial Payment UserDashboard

### PR DESCRIPTION
**Pull request by magnolia61**
Overview
----------------------------------------
Enable the 'Pay Now' button for partial paid contributions and display balance due.

Before
----------------------------------------
image

After
----------------------------------------
image

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
This is a slightly updated version of this one (https://github.com/civicrm/civicrm-core/pull/20376) by @MegaphoneJon 

Which in itself was kind of a follow up of previous work in https://github.com/civicrm/civicrm-core/pull/12319 by @jitendrapurohit

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
Applying: Partial Payment UserDashboard                                                  
  Patch failed at 0001 Partial Payment UserDashboard                                       
  When you have resolved this problem, run "git am --continue".                            
  If you prefer to skip this patch, run "git am --skip" instead.                           
  To restore the original branch and stop patching, run "git am --abort".                  
  [[ STDERR ]]                                                                             
  error: patch failed: CRM/Contribute/Page/UserDashboard.php:98                            
  error: CRM/Contribute/Page/UserDashboard.php: patch does not apply                       
  hint: Use 'git am --show-current-patch' to see the failed patch

**Comment by magnolia61** [comment]
I have no clue on what could be wrong. Does the test error point at something om my PR or something unrelated?

**Comment by eileenmcnaughton** [comment]
@magnolia61 sometimes the commit history just won't apply - maybe do a fresh pr - ie close this & then re-do your changes on master & create a new one (if you want to stash your changes to re-apply you can do 

```git reset HEAD~3 ```
- resets git head to 3 commits ago
```git stash```
-- puts your changes into the stash
```git fetch origin```
- makes sure you are up to doate
``` git --hard reset origin/master```
- sets you back to being exactly master branch - hard forces the files to change too
``` git stash pop```
-- re-applies your changes

**Comment by eileenmcnaughton** [comment]
Closing this as it was merged as part of #20376

**Pull request closed without merging**
