### PR TITLE
dev/core#183 Use TempTable builder to generate table for import

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Switches temp table handling to preferred methodology

Before
----------------------------------------
Used temp table builder

Technical Details
----------------------------------------
Replaces this change
https://github.com/civicrm/civicrm-core/pull/13633/files#diff-ca2efbe60fd40d921494640ad925df77R71

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
Test fails show this has specific relevant test cover (now to fix em)

**Comment by demeritcowboy** [comment]
* General standards
    * [`r-explain`] __PASS__
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __PASS__
      * Simple full import run works for both csv and sql.
* Developer standards
    * [`r-tech`] __PASS__
    * [`r-code`] __Issue__
      * Patch does not apply. Needs rebasing mostly because of the `$Id$` parts. Jenkins test this please.
    * [`r-maint`] __PASS with comment__
      * The mapping creation line in the test I'm assuming is copy/paste and doesn't seem needed. Test runs correctly if I remove it.
    * [`r-test`] __PASS__

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by demeritcowboy** [comment]
It needs rebasing because of the `$Id$` parts.

**Comment by eileenmcnaughton** [comment]
ah thanks

**Comment by seamuslee001** [comment]
Merging as per @demeritcowboy 's review

**Comment by eileenmcnaughton** [comment]
@mfb not sure you saw this - I picked this out off your PR & I also fixed the strip numeric. As I mentioned I'm not sure there is much left from your PR except the install side of things which we should discuss with Tim

**Pull request merged**
