### PR TITLE
Issue 1205: allow custom fields of type file for entities

### PR DESCRIPTION
**Pull request by jaapjansma**
Overview
----------------------------------------
The attachment API gives a permission denied on custom file fields on events (and other entities).
This PR removes the white list and removing the white list will check the Attachment API against core entities (even custom ones defined in extensions).

See: https://lab.civicrm.org/dev/core/issues/1205

Before
----------------------------------------
Attachment API on a file uploaded to a custom file field to an event would fail with permission denied.

After
----------------------------------------
Attachment API on a file uploaded to a custom file field to an event would succeed when the user also has access to the connected entity (in this case the event).

Technical Details
----------------------------------------
I have chosen to remove only the definition of the white list. I could have removed the white list but that got me into a corner where I had to redo the DynamicFKAuthorizationTest.

### CODE REVIEW

**Comment by colemanw** [comment]
@totten this whitelist has been problematic for a while...

**Comment by jaapjansma** [comment]
Same PR here: https://github.com/civicrm/civicrm-core/pull/15575

**Comment by seamuslee001** [comment]
Test failure is related here

**Comment by jaapjansma** [comment]
I have moved the test to create an attachment to the CRM_Core_Domain. In the failing test it did not fail as we have removed the white list it is now possible to add attachments to CRM_Core_Domain. Not sure whether this is correct behaviour or not. I do think so.

**Comment by eileenmcnaughton** [comment]
This has had pretty good analysis on gitlab. I've marked this merge-ready to give @totten one last chance to raise a red flag but if no comments in the next couple of days let's merge

**Comment by eileenmcnaughton** [comment]
OK - no response - merging

**Pull request merged**
