### PR TITLE
Afform - move contentEditable directive into crmUI library for reusability

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Basically just moves code from one place to another so that it can be used by SearchKit

Comments
----------------------------------------
Commit broken off from a larger project I'm working on to make review easier.

### CODE REVIEW

**Comment by totten** [comment]
Looks pretty good. I’ll give it a light r-run.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Slightly tangential here @totten @colemanw but noticed that in the CiviCase work you folks had done ages ago you had built in a crmEditable into its stuff https://github.com/civicrm/org.civicrm.civicase/blob/233b4f1b615803afc8bb1c4f871cf14c7d703c70/ang/civicase/Utils.js#L402 is there anything we should care about lifitng from there or is this code far superior and does this code handle text areas well?

**Comment by totten** [comment]
Spot-checked some `r-run` on the GUI editor - worked well. Merge on pass.

>  there anything we should care about lifitng from there or is this code far superior and does this code handle text areas well?

This variant integrates with `ng-model` which is probably a better way to go, because that provides a more documented set of events and validation mechanisms.

**Pull request merged**
