### PR TITLE
Zorg 082815 (PR IS STALE _ PLEASE EDIT THIS WHEN REBASED)

### PR DESCRIPTION
**Pull request by zorgalina**
Payment.php s/b all corrected (from CRM-14591) - ManageEvents/Registration.php spacing fix, SelfSvcTransfer, SelfSvcCancel style fixes (CRM-16761)

---
- [CRM-14591: civicrm_participant.fee_level](https://issues.civicrm.org/jira/browse/CRM-14591)
- [CRM-16761: Self service view, update and cancel for CiviEvent ](https://issues.civicrm.org/jira/browse/CRM-16761)

### CODE REVIEW

**Comment by davecivicrm** [comment]
Leslie - please check and fix the coding style issues in Payment.php and SelfSvcTransfer.php reported here: https://test.civicrm.org/job/CiviCRM-Core-PR/5187/checkstyleResult/new/
(click the Warnings tab for details). Then the rest of the PR tests can run.

**Comment by zorgalina** [comment]
I'll check tomorrow AM if any more space issues remain

On Fri, Aug 28, 2015 at 10:14 AM, Dave Greenberg <notifications@github.com>
wrote:

> Leslie - please check and fix the coding style issues in Payment.php and
> SelfSvcTransfer.php reported here:
> https://test.civicrm.org/job/CiviCRM-Core-PR/5187/checkstyleResult/new/
> (click the Warnings tab for details). Then the rest of the PR tests can
> run.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6616#issuecomment-135836277>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by davecivicrm** [comment]
Do check all the issues under Warnings tab. Not sure all are spacing issues.

On Fri, Aug 28, 2015 at 2:38 PM, zorgalina <notifications@github.com> wrote:

> I'll check tomorrow AM if any more space issues remain
>
> On Fri, Aug 28, 2015 at 10:14 AM, Dave Greenberg <notifications@github.com
> >
> wrote:
>
> > Leslie - please check and fix the coding style issues in Payment.php and
> > SelfSvcTransfer.php reported here:
> > https://test.civicrm.org/job/CiviCRM-Core-PR/5187/checkstyleResult/new/
> > (click the Warnings tab for details). Then the rest of the PR tests can
> > run.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/civicrm/civicrm-core/pull/6616#issuecomment-135836277>
> > .
> >
>
>
>
> --
> زورگلنه ءء لسلی
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6616#issuecomment-135894511>
> .
>



-- 
Best regards,
Dave Greenberg
CiviCRM Team
---------------------
Try CiviCRM - http://civicrm.org

**Comment by zorgalina** [comment]
I copied all the detail lines and checked them one by one-

On Fri, Aug 28, 2015 at 3:19 PM, Dave Greenberg <notifications@github.com>
wrote:

> Do check all the issues under Warnings tab. Not sure all are spacing
> issues.
>
> On Fri, Aug 28, 2015 at 2:38 PM, zorgalina <notifications@github.com>
> wrote:
>
> > I'll check tomorrow AM if any more space issues remain
> >
> > On Fri, Aug 28, 2015 at 10:14 AM, Dave Greenberg <
> notifications@github.com
> > >
> > wrote:
> >
> > > Leslie - please check and fix the coding style issues in Payment.php
> and
> > > SelfSvcTransfer.php reported here:
> > >
> https://test.civicrm.org/job/CiviCRM-Core-PR/5187/checkstyleResult/new/
> > > (click the Warnings tab for details). Then the rest of the PR tests can
> > > run.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > https://github.com/civicrm/civicrm-core/pull/6616#issuecomment-135836277
> >
> > > .
> > >
> >
> >
> >
> > --
> > زورگلنه ءء لسلی
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/civicrm/civicrm-core/pull/6616#issuecomment-135894511>
> > .
> >
>
>
>
> --
> Best regards,
> Dave Greenberg
> CiviCRM Team
> ---------------------
> Try CiviCRM - http://civicrm.org
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6616#issuecomment-135900495>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by eileenmcnaughton** [comment]
I changed the title to show at a glance to would be mergers that this PR is currently stale - if you rebase it please edit it back again

**Comment by zorgalina** [comment]
thanks Eileen

On Thu, Jan 7, 2016 at 4:38 PM, Eileen McNaughton <notifications@github.com>
wrote:

> I changed the title to show at a glance to would be mergers that this PR
> is currently stale - if you rebase it please edit it back again
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6616#issuecomment-169851761>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
I'm going to close this PR - I will work on payment.php, and then participantsandprices.php for the Event Cart; and start from the latest version of CiviCRM

**Pull request closed without merging**
