### PR TITLE
WIP Refs: dev/core#3068 - Update Pay Later attachment filename

### PR DESCRIPTION
**Pull request by stesi561**
First cut at changing filename.

Overview
----------------------------------------

WIP - first cut at updating the Filename of pay later receipts.

### CODE REVIEW

**Comment by stesi561** [comment]
Doesn't look like this area of the code has tests.

The pattern being changed is somewhat replicated in ContrbutionSoft however this seems to related to PCP pages and at first glance doesn't look like notification happens on pay later. Need to test.

**Comment by stesi561** [comment]
Tested by creating a PCP and doing a pay later donation - this has the new "invoice.pdf" filename sent to the "donor" So changes in ContrbutionSoft don't look to be required.

**Comment by stesi561** [comment]
So despite changing all instances of 'reciept.pdf' in the codebase I could grep - editing a contribution and saving with the option to resend receipt - we end up with the original "reciept" being invoice.pdf and the resent one having receipt.pdf

**Comment by demeritcowboy** [comment]
Did your grep pick up the ones that look like `ts('receipt') . 'pdf'`, like in CRM/Contribute/Form/AdditionalInfo.php? P.S. While I think ts() is correct to add, it should probably be wrapped in CRM_Utils_File::makeFilenameWithUnicode, just in case the translation contains characters that don't work in filenames (I'm not saying go change all of them here, just if you're going to add ts() to whatever it is you're updating here).

**Comment by eileenmcnaughton** [comment]
As an aside I've found those pdfs are being attached when I don't want them - the issue is macrons don't render in domPDF :-( so I don't want them going out

**Comment by demeritcowboy** [comment]
> macrons don't render in domPDF

Do you mean macros? In which case what do you mean by macros? Or do you mean some kind of character that isn't in the default fonts included with civi, and so you need to do the steps in the [install guide](https://docs.civicrm.org/installation/en/latest/general/unicode_pdf/) to get a proper unicode font?

**Comment by eileenmcnaughton** [comment]
@demeritcowboy yeah - characters that domPDF supports but because we don't ship deva-vu- fonts don't work by default - turns out it's quite embarrasing to see what has been attached to our emails ...   Māori => M?ori

**Comment by eileenmcnaughton** [comment]
OK - I've created an extension that adds the fonts

https://github.com/eileenmcnaughton/dompdf-fonts

**Comment by eileenmcnaughton** [comment]
Lol - I may have just given away today's worlde!

**Comment by eileenmcnaughton** [comment]
Maybe it could be just 'contribuion.pdf' or acknowledgement?

**Comment by eileenmcnaughton** [comment]
Since this had a ping a month back & no update I'm gonna close - you can open a new PR when ready (& it will be magically at the front of the PR queue rather than hidden on this last page where I rarely dare look)

**Pull request closed without merging**
