### PR TITLE
dev/core#832 Case activity query performs poorly on large databases

### PR DESCRIPTION
**Pull request by agh1**
Overview
----------------------------------------
This straightens out some performance problems with the case activity query.  This uses pseudoconstants instead of joins and replaces a subquery with a more straightforward join.

Before
----------------------------------------
The query crashes the server sometimes with millions of temporary files.

After
----------------------------------------
Output should be the same, but activity statuses, case types, etc. are filled as pseudoconstants in the PHP code rather than appearing from joins to the option value table.

Comments
----------------------------------------
This is mainly being tested in conjunction with #13916.

See [dev/core#832](https://lab.civicrm.org/dev/core/issues/832)

### CODE REVIEW

**Comment by pradpnayak** [comment]
👍 from me on the change, but this isn't a formal review.

**Comment by demeritcowboy** [comment]
Hi @pradpnayak - if you do a Find Cases do you see the recent/scheduled activity columns are blank and also a notice warning? It's strange I can't reproduce it locally just on the test site here, so I was trying to track it down.

**Comment by pradpnayak** [comment]
Hi @demeritcowboy, I haven't tested this PR. I will put some time next week for this

**Comment by agh1** [comment]
Thanks @demeritcowboy and @pradpnayak.  I see the weird notices on http://core-14086-98xr.test-1.civicrm.org:8001 (the Jenkins run in response to https://github.com/civicrm/civicrm-core/pull/14086/commits/cdbecaea68ded59da572dad8ba239c53781a8107), but I couldn't replicate the issue locally either.  The query for that is pulling from a MySQL view, so I wonder if there's something on that environment causing the view to fail.

In the meantime, I did notice one problem where activity types weren't displaying right, so I went through and fixed that along with straightening out the fact that it queried the same fields with different names depending upon the context.

**Comment by demeritcowboy** [comment]
@agh1 CiviCase is fun, yeah? If that change doesn't beat it into submission then could also try adding a `CRM_Core_Error::debug('x', $query);` in there so we can see on the screen what **it** thinks the query is.

**Comment by agh1** [comment]
I just added a test for the functionality that seems to work everywhere but the test site.  Either it passes, and the UI on Jenkins' site is just a fluke, or it will show the query result row and help us figure it out.

**Comment by agh1** [comment]
aha!  with the latest test I could see that the DAO object looks like this:

```
CRM_Core_DAO Object
(
    [resultCopies:protected] => 0
    [_options:protected] => Array
        (
        )

    [_DB_DataObject_version] => 1.8.12
    [__table] => 
    [N] => 1
    [_database_dsn] => 
    [_database_dsn_md5] => e3646250297b2370de2ed1b9715b63dd
    [_database] => core14086a_9z7r0
    [_query] => 
    [_DB_resultid] => 23527
    [_resultFields] => 
    [_link_loaded] => 
    [_join] => 
    [_lastError] => 
    [case_id] => 1
    [case_subject] => 
    [contact_id] => 3
    [sort_name] => Site Administrator
    [phone] => 
    [contact_type] => Individual
    [contact_sub_type] => 
    [ANY_VALUE(t_act_activity_type_id)] => 13
    [case_type_id] => 1
    [case_status_id] => 1
    [ANY_VALUE(t_act_status_id)] => 2
    [case_start_date] => 
    [case_role] => 
    [activity_date_time] => 2019-04-19 00:00:00
    [activity_id] => 1
)
```

The `CRM_Contact_BAO_Query::appendAnyValueToSelect()` function is wrapping those with `ANY_VALUE()`, maybe only on the testing server because it might have SQL_ONLY_FULL_GROUP_BY set.

I'll give `t_act.activity_type_id` and `t_act.status_id` aliases and that should probably do it.

**Comment by seamuslee001** [comment]
@agh1 yes i can confirm that the test server uses stock MySQL5.7 and therefore has ONLY_FULL_GROUP_BY enabled by default

**Comment by agh1** [comment]
The new `CRM_Case_BAO_CaseTest::testCaseActivity()` test passed, which is enough for me to call it a night--`ONLY_FULL_GROUP_BY` strikes again!

**Comment by demeritcowboy** [comment]
Good sleuthing!

**Comment by demeritcowboy** [comment]
Jenkins test this please

**Comment by demeritcowboy** [comment]
* General standards
    * [`r-explain`] __PASS__
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __PASS__
        * Note I DIDN'T test what this PR was originally about, where there's performance issues on a large database. I was going to test that locally but I made the mistake of updating to mysql 5.7 and that's giving me some grief for civi and non-civi.
        * Otherwise it all seems good.
* Developer standards
    * [`r-tech`] __PASS__
        * The scope of this PR expanded a bit from its original of just replacing joins with pseudoconstants, but it seems necessary anyway and I'm not sure it would be worth breaking up into separate PRs.
        * The query/functions are used in several places, and indirectly by some types of ajax calls and also dashlets, but interestingly it doesn't seem to be used by the API that I could see. Entityref doesn't seem to use it either, e.g. file-on-case.
    * [`r-code`] __PASS__
    * [`r-maint`] __PASS__
    * [`r-test`] __PASS__

**Comment by eileenmcnaughton** [comment]
I'm going to merge this based on @demeritcowboy's review but I'm still a little nervous just because the amount of change in this PR means it would be easy to miss something.

However, I do note the added test.

@pradpnayak are you able to commit to taking another look through the code post-merge just to double check & to do some rc testing on this change?

**Comment by eileenmcnaughton** [comment]
@lcdservices @kcristiano @jitendrapurohit @mattwire pinging all of you in the hope you can maybe test this a bit during the rc period (or while in master)

**Comment by demeritcowboy** [comment]
For what it's worth I have my local mysql issues sorted out and am attempting to do a load test to test the original reason for the PR. Will post results.

But yes any additional eyes on this would be great! I did click on a lot of things during testing because I like clicking on things.

While it's been improved over the years there's a certain Moby Dick/Captain Ahab vibe to this query and some day, at the very least, I'd vote to see the 14 day thing pulled out and put into a separate dashlet or something. Separate topic though. Also if you haven't read Moby Dick then ... uh, let's say ... Captain Ahab wins at the end!

**Comment by eileenmcnaughton** [comment]
@demeritcowboy yes that is worth a lot - I don't have too much doubt this will help performance but it's a big change on toxic code so my main worry is unintended consequences

**Comment by agh1** [comment]
A follow-up is https://github.com/civicrm/civicrm-core/pull/14139 which will rebuild the views upon upgrade to 5.14.

**Comment by demeritcowboy** [comment]
Noting that I did some load testing and really only saw any difference for the upcoming and recent dashboard sections, but was about 20% there.

**Comment by eileenmcnaughton** [comment]
Thanks @demeritcowboy - since the problem was an unindexed join the speed increase will depend on the number of activity types & the number of activity statuses - and the number of activities. So I would expect a medium sized DB (e.g 50k contacts) with a large number of activities types & activities to see a much more substantional increase than a DB of the same size with less activity types.

**Pull request merged**
