### PR TITLE
[REF] Update Zetacomponents/mail to be 1.9.5 to fix email validation …

### PR DESCRIPTION
**Pull request by seamuslee001**
…handling

Overview
----------------------------------------
This updates zetacomponents/mail to the most recent version to better handle email validation 

ping @eileenmcnaughton @agileware-justin

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I wish I could find the gitlab this closes - @jusfreeman put all sorts of Agileware refs on the upstream pr but not our git so hopefully @agileware-justin can find & close the gitlab

**Comment by agileware-justin** [comment]
Agileware Refs save the day!
Posted comment on https://lab.civicrm.org/dev/core/-/issues/2604#note_150958

The issue this will fix is https://lab.civicrm.org/dev/core/-/issues/260 - CiviCRM 5.37.2, Both the Fetch Bounces and Process Inbound Emails jobs will fail with error: 'returnPath' is invalid

Have been running this patch since 2021 and it's solved a silent but very detrimental issue, good to see it finally fixed for the community. (Maybe everyone else is solving this problem in their own way and not sharing the solution?)

**Comment by eileenmcnaughton** [comment]
thanks @agileware-justin

**Comment by agileware-justin** [comment]
I think it would be worthwhile adding some unit tests with weird email addresses which would have previously thrown the invalid error. That should mitigate this issue from reoccurring in future too.

**Comment by eileenmcnaughton** [comment]
@agileware-justin if you want to add some the EmailProcessorTest class is pretty easy to adapt

**Pull request merged**
