### PR TITLE
[REF] extract getToFinancialAccount from CRM_Contribute_PseudoConstantt::contributionStatus

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Minor extraction

Before
----------------------------------------
Code less readable

After
----------------------------------------
Code more readable

Technical Details
----------------------------------------
This makes the function much more readable. Note that this function is called from only one place (payment.create) and it is expected the code will be updated so that function calls recordPayment and this function is eliminated. The cleanup is to help with comparing the 2 functions

 I felt that the is_payment logic should go but resisted & just commented

Comments
----------------------------------------
@monishdeb another small one

### CODE REVIEW

**Comment by monishdeb** [comment]
Reviewed the patch, safe to merge

**Comment by eileenmcnaughton** [comment]
@monishdeb I was a bit surprised to realise how little was actually going on in the function once I extracted! It looked so complicated

**Comment by monishdeb** [comment]
You will find such nightmares in such core files which handles financial stuff, esp. on Contribution BAO file, so I am not surprised :)

**Comment by eileenmcnaughton** [comment]
sigh.. this has been a bit of a scary trail to unravel - luckily we already added a lot of unit tests over the past couple of years

**Comment by seamuslee001** [comment]
Merging as per the tag

**Pull request merged**
