### PR TITLE
Afform - Enable creating event from a template

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Enables selecting an event template when using Afform to create a new event.

Before
----------------------------------------
No "Event Template" field available on Afform.

After
----------------------------------------
How to use this feature:
1. Make an Afform for Events
2. Drag required fields to the form (at minimum, Title, Start Date, Event Type)
3. Drag the "Event Template" field to the form
4. Give the form a url, save, and visit the form.
5. Select a template from the list, the rest of the form will be autofilled from the template.
6. Update other fields as desired and save.
7. The saved event will inherit all data from the event template.

Technical Details
----------------------------------------
This expands autofill functionality to work with create actions in addition to update.

### CODE REVIEW

**Comment by Guydn** [comment]
I will test it asap. Is the timezone included ?

**Comment by colemanw** [comment]
> I will test it asap. Is the timezone included ?

That's a complex topic. See https://lab.civicrm.org/dev/core/-/issues/2122

**Comment by Guydn** [comment]
> > I will test it asap. Is the timezone included ?
> 
> That's a complex topic. See https://lab.civicrm.org/dev/core/-/issues/2122

Yes, I saw the issue.

**Comment by Guydn** [comment]
I have tested and the event is created with all the fields :-).
Is there a possibility to load the information of the template (the title, the description , ...) so that the user sees the information coming from the template and is able to change the information if he wants to. Just like the way it works in CiviCRM. As soon as the template is selected, then all the fields are populated and it is possible to change the fields.

**Comment by colemanw** [comment]
@Guydn yes that is how it works. When you select a template it will auto populate the fields on the afform. Is that not working for you?

**Comment by mlutfy** [comment]
I tested Guy's form, and when using a template, the network console shows:

> Cannot process APIv4 request for Event1 (Event.get): Action is not approved

I'm logged-in as an admin, and the patch was applied on top of CiviCRM 6.65 (RC).

**Comment by colemanw** [comment]
Thank you again @Guydn for testing and @mlutfy for debugging. Turns out it was overly-restrictive access checks. I've fixed them and updated this PR, I think it should work now for non-superadmins.

**Comment by mlutfy** [comment]
@colemanw New changes work for me. I tested as an anon users (with a form that allows it), and it populated the form correctly.

Is the test fail related? (core-matrix, action mapping)

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by mlutfy** [comment]
(I'll let someone else merge if tests pass, I would be in conflict of interest)

**Comment by colemanw** [comment]
@mlutfy the test fail is unrelated to this PR

**Comment by colemanw** [comment]
@mlutfy the test fail is unrelated to this PR

**Comment by colemanw** [comment]
@mlutfy the test fail is unrelated to this PR

**Comment by colemanw** [comment]
Note: this broke and [was fixed](https://github.com/civicrm/civicrm-core/pull/35977) (with a test to ensure it doesn't break again!)

**Pull request merged**
