### PR TITLE
Server-side FB conditional evaluation

### PR DESCRIPTION
**Pull request by MegaphoneJon**
Overview
----------------------------------------
See https://lab.civicrm.org/dev/core/-/issues/5182.  If you have a required field on an FB form that's conditionally hidden, it passes client-side "required field" validation but fails it server-side.

Before
----------------------------------------
Silent failure, not all data saved.

After
----------------------------------------
Hidden required fields are un-required server side as well as client-side.

Comments
----------------------------------------
Yes, this should have tests.  Unfortunately I've already overshot my budget considerably on this, since I should've just unrequired the hidden field instead of supporting it.  But I've written this with easy testing in mind - `checkAfformConditional()` is a pure function and should test very quickly.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw is this on your radar

**Comment by MegaphoneJon** [comment]
OK - this is a bit more complex now, but my original patch only considered whether a field had a conditional rule, and not whether it was in a container/fieldset that had a conditional rule.  Now it does.

**Comment by MegaphoneJon** [comment]
@coleman I hope you can advise here.

In the HTML, yes/no fields' values are 1/0.  But when creating a conditional, selecting Yes/No adds "true"/"false" to the afform.  In JS that's fine, in PHP the type juggling is different.

The "Yes/No" is canonically true/false in the API. How/where best to handle this?

I'm hoping there's some way we could record 1/0 in a conditional using a Yes/No field.  Is that doable? Where should I be looking?

**Comment by colemanw** [comment]
@MegaphoneJon I'll check on that...

**Comment by MegaphoneJon** [comment]
@colemanw If you create a yes/no custom field, add it to a FB form, then make a conditional based on it, it will be recorded in the FB HTML something like this:
```
af-if="([[&amp;quot;Grant1[0][fields][Custom_Group.Custom_field]&amp;quot;,&amp;quot;==&amp;quot;,&amp;quot;true&amp;quot;]])"
```
Decoded:
```
af-if="([["Grant1[0][fields][Custom_Group.Custom_field]","==","true"]])"
```

The issue are those quotation marks around `true`, which make it a string not a boolean.

If you actually assign a value to the yes/no field on your form, it will be stored as a `0` or `1`.  Here's the HTML markup generated for such a field. Note the `value="1"` and `value="0"`:
```html
<div class="crm-af-field ng-scope" ng-if="!$ctrl.defn.expose_operator" ng-include="'~/af/fields/' + $ctrl.defn.input_type + '.html'"><!-- ngRepeat: opt in getOptions() track by opt.id --><label ng-repeat="opt in getOptions() track by opt.id" class="ng-binding ng-scope">
  <input class="crm-form-radio ng-pristine ng-untouched ng-not-empty ng-valid ng-valid-required" name="rapid-response-grant-additional-fields-does-your-organization-s-annual-income-exceed-250-000-16" type="radio" ng-model="getSetValue" ng-required="$ctrl.defn.required" ng-model-options="{getterSetter: true}" ng-value="opt.id" value="1" required="required">
  Yes
</label><!-- end ngRepeat: opt in getOptions() track by opt.id --><label ng-repeat="opt in getOptions() track by opt.id" class="ng-binding ng-scope">
  <input class="crm-form-radio ng-not-empty ng-dirty ng-valid-parse ng-valid ng-valid-required ng-touched" name="rapid-response-grant-additional-fields-does-your-organization-s-annual-income-exceed-250-000-16" type="radio" ng-model="getSetValue" ng-required="$ctrl.defn.required" ng-model-options="{getterSetter: true}" ng-value="opt.id" value="0" required="required">
  No
</label><!-- end ngRepeat: opt in getOptions() track by opt.id -->
<!-- ngIf: !$ctrl.defn.required -->
</div>
```

In JS, `"true" == 1` and `"false" == 0` are both `TRUE`.

In PHP, it's version-dependent:
`"true" == 1` is always `TRUE`.
`"false" == 0` is `TRUE` in PHP7.4 and `FALSE` in PHP 8.

If it's possible to encode the `"true"` and `"false"` in the `af-if` as a boolean, not a string, that should solve it.  But as you say, it would be good to be standardized everywhere.  Though the `0` and `1` are are unavoidable - you can't `POST` a boolean value.

**Comment by colemanw** [comment]
> @MegaphoneJon The issue are those quotation marks around true, which make it a string not a boolean.

That's just the serialization at work. When the condition is evaluated, the string gets json-decoded so will be evaluated as `true`.

**Comment by colemanw** [comment]
@MegaphoneJon this PR would need to be adapted to work with #30450 which increases the number of supported operators, and brings it closer in-line to standard operators supported by API4/SearchKit.
Possibly we could leverage `ArrayQueryActionTrait::filterCompare()` to do the evaluation, although we still have to unserialize the values first.

**Comment by MegaphoneJon** [comment]
@colemanw I was working on #25823.  There will be multiple use cases for parsing FormBuilder HTML in PHP.  Perhaps instead we should store a PHP representation of the form?  

I realize sometimes the form doesn't exist on disk - e.g. in `AfformAutocompleteUsageTest`.  I'm just throwing out the idea for your consideration.

**Comment by colemanw** [comment]
Ok thanks again for your work on this @MegaphoneJon. I've taken your branch and added unit tests and support for joins + additional operators.

**Comment by colemanw** [comment]
> There will be multiple use cases for parsing FormBuilder HTML in PHP. Perhaps instead we should store a PHP representation of the form?

I was able to replace the parsing code from this PR with a bit of preprocessing in `FormDataModel::parseFields()`

**Pull request closed without merging**
