### PR TITLE
(dev/core#622) User Dashboard doesn't show Edit Contact Information link

### PR DESCRIPTION
**Pull request by yashodha**
Overview
----------------------------------------
Edit Contact Information is not loading on the dashboard.
The buggy logic leads to having links getting overwritten.

Before
----------------------------------------
 _Edit Contact Information_ link is missing.

After
----------------------------------------
 _Edit Contact Information_ link is showing.

### CODE REVIEW

**Comment by colemanw** [comment]
This looks good. @yashodha it could be made even more concise by using the `+=` operator.

**Review by jitendrapurohit — APPROVED** [review]
Have already tested this PR. See details at https://github.com/civicrm/civicrm-core/pull/13352#issuecomment-449952805. +1 to get this merged after the above changes for `+=` is done.

**Comment by mattwire** [comment]
Tested with updates suggested by @colemanw.  Reviewed by @jitendrapurohit and re-tested by me.  Merge on pass

**Comment by colemanw** [comment]
@yashodha could you do a git squash and force push so this PR is only 1 commit instead of 3?

**Pull request closed without merging**
