### PR TITLE
Move CRM_Core_BAO_FinancialTrxn to CRM_Financial_BAO_FinancialTrxn

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
Move CRM_Core_BAO_FinancialTrxn to CRM_Financial_BAO_FinancialTrxn

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@pradpnayak this looks generally good to me - but were you thinking about adding the dummy `CRM_Core_BAO_FinancialTrxn ` which extends the new class name in this PR or a separate one? (if separate we need to be careful we don't merge one pre-rc-cutting & one post

**Comment by pradpnayak** [comment]
Hi @eileenmcnaughton 

Sorry for late response, got busy with other work. 

Yes I am going to add the dummy CRM_Core_BAO_FinancialTrxn, I was searching for an example, I remember there was something around Task files where Matt or you had created a dummy file with deprecated method, Can't find one, do you have any example that i could use?

Thanks
Pradeep

**Comment by eileenmcnaughton** [comment]
@pradpnayak check this commit https://github.com/civicrm/civicrm-core/commit/bb4187d757af9abb09d6a97b20ccdd62e1b72c62#diff-4cb1584bd70be2cc0c0cd7910c96c0babd80d49ae5e42eb4a29ae1bf3efc2269

**Comment by pradpnayak** [comment]
Hi Eileen,

I have pushed the changes, can you please review?

Thanks
Pradeep

**Comment by eileenmcnaughton** [comment]
@pradpnayak did you see 

api\v4\Entity\ConformanceTest::testConformance with data set "FinancialTrxn" ('FinancialTrxn')
PEAR_Exception: DB Error: unknown error

**Comment by pradpnayak** [comment]
looks like test have passed

**Comment by eileenmcnaughton** [comment]
@pradpnayak I figured out why it is failing & the fix needs to be in the unit test not the BAO class - your change exposed a bug in the v4 api whereby it is currently not calling the create method (bad) and hence it got away without passing in all the required params

#22571 is a partial fix but still needs a fix on the test side

**Comment by eileenmcnaughton** [comment]
@pradpnayak this is stale so I'm closing - but have put up the less ambitious https://github.com/civicrm/civicrm-core/pull/23190 to keep this progressing

**Pull request closed without merging**
