### PR TITLE
CRM-19381 Upgrade phpword to be php7 compatiable

### PR DESCRIPTION
**Pull request by seamuslee001**
- [CRM-19381: phpwod 0.12.1 incompatible with PHP7](https://issues.civicrm.org/jira/browse/CRM-19381)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@totten Tim thoughts on how to solve this problem? 

`Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for zendframework/zend-escaper 2.4.10 -> satisfiable by zendframework/zend-escaper[2.4.10].
    - zendframework/zend-escaper 2.4.10 requires php >=5.3.23 -> your PHP version (5.3.10) does not satisfy that requirement.
  Problem 2
    - Installation request for zendframework/zend-stdlib 2.4.10 -> satisfiable by zendframework/zend-stdlib[2.4.10].
    - zendframework/zend-stdlib 2.4.10 requires php >=5.3.23 -> your PHP version (5.3.10) does not satisfy that requirement.
  Problem 3
    - Installation request for zendframework/zend-validator 2.4.10 -> satisfiable by zendframework/zend-validator[2.4.10].
    - zendframework/zend-validator 2.4.10 requires php >=5.3.23 -> your PHP version (5.3.10) does not satisfy that requirement.
  Problem 4
    - zendframework/zend-escaper 2.4.10 requires php >=5.3.23 -> your PHP version (5.3.10) does not satisfy that requirement.
    - phpoffice/phpword v0.13.0 requires zendframework/zend-escaper 2.4.* -> satisfiable by zendframework/zend-escaper[2.4.10].
    - Installation request for phpoffice/phpword v0.13.0 -> satisfiable by phpoffice/phpword[v0.13.0]`

**Comment by totten** [comment]
Hmm, this is tricky.

 * It's quite intentional that the servers are running stock versions of PHP from Ubuntu -- this gives us a signal about compatibility for many dedicated hosts.
 *  The dependency is only used when generating Word/ODT docs, which is a very new (post-4.7.0?) feature.
 * Since it's recent, it's bad but not terrible if we edge it out somewhere (e.g. "cannot use this particular feature with early versions of PHP 5.3.x" or "cannot use in new PHP 7+"). Note: I'd make a distinction between PDF and Word support (where PDF is long-standing and shouldn't regress for early PHP 5.3.x).
 * IIRC, the app has been warning that PHP 5.3 is outdated (PHP 5.5 is recommended) for some time. When/if we put the squeeze on PHP 5.3, this would be (in the grand scheme of things) a fairly modest way to ratchet the pressure.
 * If we could have access to both 0.12 and 0.13, then we could pick the right one at runtime. Although this isn't a pattern `composer` supports well.
 * An idea: For 4.7.12, we stick with the older phpoffice 0.12. However, we add some refined warning (`CRM/Utils/Check/Component/Env.php`) for users on low PHP 5.3.x pushing them toward PHP 5.3.23+ in the future. Then, in 4.7.13 or 4.7.14, make the switch and upgrade the `test-ubu1204-*` servers.

Ping @colemanw since he knows more about this feature.

**Comment by colemanw** [comment]
Yes the feature is very new and it's only used for generating docs, not 
PDFs. Strong +1 for droping php 5.3 support for this feature. 4.7 
explicitly warns you that you need to update PHP if you want full 
compatibility with all features.

**Comment by seamuslee001** [comment]
@totten as it stands 0.12 cannot work on php7 as it has classes with names of "string" which php7 explicitly outlaws and therefore i think it is an error notice it kicks up. I think at the very least giving a nudge towards php5.3.23 as a bare minimum to me sounds ok as its still php5.3 but just later on.  IT might also be useful to look at the stats to see if we can see what . version of php 5.3 people are running out there

**Comment by totten** [comment]
Replacement: #9104.

**Pull request closed without merging**
