### PR TITLE
--CRM-17209, fixed notice error when contribution status is changed f…

### PR DESCRIPTION
**Pull request by pradpnayak**
…rom core status

### CODE REVIEW

**Comment by davecivicrm** [comment]
Test failures unrelated.

**Comment by davecivicrm** [comment]
Reviewed code w/ Coleman and ran a few manual status change tests. Looks ok.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I agree this looks ok / safe

**Comment by colemanw** [comment]
jenkins, retest this please

**Comment by colemanw** [comment]
retest this please

**Pull request merged**
