### PR TITLE
CRM-20554: Error when running activity report

### PR DESCRIPTION
**Pull request by maitrepylos**
Change the parameters of the select and from function to correct this error.

---

 * [CRM-20554: Error when running activity report](https://issues.civicrm.org/jira/browse/CRM-20554)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by maitrepylos** [comment]
Do I have to do something special?

**Comment by colemanw** [comment]
@maitrepylos I haven't been able to get the error to appear, running the Activity Detail Report and turning on a bunch of filters. Is there a particular configuration needed to trigger it?

**Comment by maitrepylos** [comment]
@colemanw No, I don't have anything like a particular configuration and it appears from time to time.
On the other hand, in the CRM/Report/form. php online file 2622 the functions without parameters are used, which is a concern.

` public function buildQuery($applyLimit = TRUE) {
    $this->buildGroupTempTable();
    $this->select();
    $this->from();
    $this->customDataFrom();
    $this->buildPermissionClause();
    $this->where();
    $this->groupBy();
    $this->orderBy();`

But if you want, I can do a print screen to show you the mistake ?

**Comment by mattwire** [comment]
@maitrepylos Could you update the PR title to include a short description please?  Eg. "CRM-20554: Error when running activity report"

**Comment by maitrepylos** [comment]
Done

**Comment by colemanw** [comment]
Well, I can't reproduce the error at runtime but the code as written is clearly wrong, and this fix appears safe.

**Pull request merged**
