### PR TITLE
dev/core#1822 - Fix missing newly created activity types from the dropdown on the new activity form

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/1822

Adding a new activity type and then going to create a new activity doesn't show the new type in the dropdown on the form. Stopped working in 5.26.

Technical Details
----------------------------------------
The change to use the database default for the `filter` column changed it to null, but it needs 0. One other way to deal with this would be to make the need for 0 in the code more tolerant to also accept null to mean the same thing. Another would be to put back the code that sets a missing filter value to FALSE. But this PR seems more in line with the intended direction of the earlier change.

Comments
----------------------------------------
One thing I'm not sure about is that updating any that got inadvertently set to null will also update ones that someone might have set to null on purpose. But that seems unlikely? Should remove the code comment in the sql upgrade file if it's decided to go with this PR.

### CODE REVIEW

**Comment by seamuslee001** [comment]
This seems sensible to me @colemanw ?

**Comment by colemanw** [comment]
Looks good.

**Comment by demeritcowboy** [comment]
Another thought which I just had: Setting the default to 0 works for activity types, but _might_ introduce a problem somewhere for other option values if they are expecting null and don't deal with 0. I don't know of any offhand, but the default even before the earlier change was null, so for other option values where they don't explicitly do anything they'll now get 0. I'll try grepping for filter and see what comes up.

**Comment by seamuslee001** [comment]
so the filter up and till now was being set to FALSE aka 0 if not set. So they would have had to be passing in a 'Null' value iirc to set it to NULL so I think this is a safe change to make

**Comment by demeritcowboy** [comment]
Oh right it was in BAO/OptionValue - I confused it with Activity. Good because the grep wasn't looking fun.

**Pull request merged**
