### PR TITLE
SearchKit - Allow functions in the WHERE clause

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Advanced feature for SearchKit allows SQL functions in the WHERE clause. They are selected in the same way as the "Field Transformations" tab.

image

### CODE REVIEW

**Review by pfigel — CHANGES_REQUESTED** [review]
This looks great, thanks @colemanw! I've done a quick round of testing and discovered that the generated API4 request appears to be missing the `isExpression` bool in `where` clauses with functions. The generated request for `Year Only Birth Date = 1991` looks like this:

```json
{
  "version": 4,
  "select": [
    "id",
    "display_name"
  ],
  "orderBy": [],
  "where": [
    [
      "YEAR(birth_date)",
      "=",
      1991
    ]
  ],
  "groupBy": [],
  "join": [],
  "having": []
}
```

It should look like this:
```json
{
  "version": 4,
  "select": [
    "id",
    "display_name"
  ],
  "orderBy": [],
  "where": [
    [
      "YEAR(birth_date)",
      "=",
      1991,
      true
    ]
  ],
  "groupBy": [],
  "join": [],
  "having": []
}
```

**Comment by colemanw** [comment]
@pfigel are you sure about that? My understanding is that the 4th boolean argument controls how the 3rd argument is interpreted, not the first. I think the first argument is always parsed as an expression, because a field name is expected.
This PR is limited to the 1st argument of a where clause. The 3rd is still assumed to be a scalar value.

**Comment by pfigel** [comment]
@colemanw I'm fairly certain, yes. `where` without the bool hits [this if](https://github.com/civicrm/civicrm-core/blob/c20245100a2edc18cd77170d8b73b4a5fa4bdfad/Civi/Api4/Query/Api4SelectQuery.php#L454), which expects a field, whereas the bool variant goes [here](https://github.com/civicrm/civicrm-core/blob/c20245100a2edc18cd77170d8b73b4a5fa4bdfad/Civi/Api4/Query/Api4SelectQuery.php#L497) and accepts expressions. The request without `isExpression=true` fails with `Invalid field 'YEAR(birth_date)'`.

**Comment by colemanw** [comment]
Thanks @pfigel - you're right, but IMO that was too restrictive. The first arg of the WHERE clause is always interpreted as an expression, so functions ought to be allowed regardless of the 4th param.

I've loosened the restriction and added a unit test to ensure it works correctly in both modes.

**Comment by eileenmcnaughton** [comment]
Not sure my searches are super useful but they worked....

image


image

**Pull request merged**
