### PR TITLE
CRM-15934

### PR DESCRIPTION
**Pull request by lynxlynxlynx**
bunch of new and updated bounce matching patterns

### CODE REVIEW

**Comment by davecivicrm** [comment]
ok to test

**Comment by lynxlynxlynx** [comment]
Seems I waited too long. Do you prefer if I close this one, rebase locally and open a new PR? I doubt I can just push a rewritten history here.

**Comment by davecivicrm** [comment]
Thanks - Probably best to close and rebase.

**Comment by jitendrapurohit** [comment]
PR has gone stale, submitted a new PR https://github.com/civicrm/civicrm-core/pull/5214 fixing a smarty error found in one regex.

**Pull request closed without merging**
