### PR TITLE
CRM-17238, Dedupe for Individual Birth Date Results in Error

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
https://issues.civicrm.org/jira/browse/CRM-17238

Before
----------------------------------------
Fatal Error

After
----------------------------------------
No Fatal Error

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@JKingsnorth if you have time to test....

@pradpnayak any chance you can do a unit test? I know this is one you picked up from our priorities in gitlab rather than a customer one

**Comment by pradpnayak** [comment]
@eileenmcnaughton where can i find the list of priorities so that i can put some time to fix some of the issues.

**Comment by eileenmcnaughton** [comment]
@pradpnayak I'm very much focussed on the PR queue at the moment but we are making real inroads there so I agree it would be good to think about some other things. I'd like to drive the PRs down a bit more first though - I've been trying to figure out what has been stalling various PRs

**Comment by eileenmcnaughton** [comment]
@pradpnayak just looking - there are a few stalled needing tests - see https://github.com/civicrm/civicrm-core/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-asc+label%3Aneeds-test - if there are any you think you could resolve by writing tests for that would be great BUT - it's also OK to recommend that they are closed & tracked through gitlab if they aren't 'review ready' and you think it is a bit of a big ask for someone else to do what it takes to get it mergeable.

It would be good maybe to push hard on getting the review queue down for another week & then maybe figure out how we can identify other product mtce priorities

**Comment by eileenmcnaughton** [comment]
@pradpnayak I managed to replicate this bug in a unit test BUT your fix DIDN'T fix it for me :-(

I marked the line incomplete.

https://github.com/civicrm/civicrm-core/pull/13179

My best thinking at this stage is to do a getfields to grab field metadata and then if type === 'date' then compare with  '0000-00-00 00:00:00' - I see there are some alternate comparisons suggested here https://stackoverflow.com/questions/559590/selecting-empty-mysql-datetime-fields - but from what I can tell they sacrifice performance for arguably prettier code by adding in calculations.

It's also possible we just skip the comparison with empty for date type fields - I'm not sure we really do intentionally store 0 dates

**Comment by seamuslee001** [comment]
@eileenmcnaughton don't forget about the no-zero-date SQL Mode which might be an issue

**Comment by eileenmcnaughton** [comment]
@pradpnayak I found the sql bug really confusing - a very similar query doesn't fail & it doesn't fail when there are no results - so I think there might be a bit of an sql bug in the mix :-(

**Comment by monishdeb** [comment]
@eileenmcnaughton @pradpnayak  after reviewing the patch and reading the above comments I agree with the approach to set the appropriate default value of a column, which is decided by checking the type. In this direction I made few changes in [here](https://gist.github.com/monishdeb/265e1781a93079e74f5cf01409d6db22) which grabs the column definition of the rule_field and based on the type and/or default value set the placeholder for NULLIF. What are your thoughts?

**Comment by seamuslee001** [comment]
@monishdeb why are you checking in MYSQL for the default and not using the DAO fields?

**Comment by eileenmcnaughton** [comment]
We need to performance test any addition off NULLIF - since it will be unindexed and we already know this is an area of code highly likely to trigger performance issues as it does big comparisons.

Can't we just compare with ' '0000-00-00 00:00:00' for dates?

**Comment by seamuslee001** [comment]
@eileenmcnaughton i don't believe that is allowed under the NO_ZERO_DATE sql mode https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_zero_date

**Comment by eileenmcnaughton** [comment]
@seamuslee001 can we just set the mode before & after the query?

**Comment by eileenmcnaughton** [comment]
SO I see
```
NO_ZERO_DATE is deprecated. NO_ZERO_DATE is not part of strict mode, but should be used in conjunction with strict mode and is enabled by default. A warning occurs if NO_ZERO_DATE is enabled without also enabling strict mode or vice versa.
```

So what does that mean - ie will the replacment for no zero date also ban '0000-00-00'

**Comment by eileenmcnaughton** [comment]
Because if it's deprecated we can just change the mode...

**Comment by magnolia61** [comment]
any idea if this nasty bug will be solvable and what caused it? (because it using birthday fields in dedupe rules used to work). We depend highly on it to prevent duplicates in event registration. Whatever I can do to help test solutions in different scenarios.

**Comment by monishdeb** [comment]
@eileenmcnaughton as per various forums, it does indicate that NO_ZERO_DATE will be deprecated in future versions. Should do some thing like disable/reenable FGB i.e. about doing the same for NO_ZERO_DATE before and after the merge query is fired?

**Comment by eileenmcnaughton** [comment]
@monishdeb I'm OK with trying that but I see this addendum "and make their functionality part of STRICT MODE" so they might not actually be going away

**Comment by eileenmcnaughton** [comment]
@monishdeb @pradpnayak I think this might work -https://github.com/civicrm/civicrm-core/pull/13538 (it at least passes tests with strict mode locally) although it will need to testing incl for performance

**Comment by eileenmcnaughton** [comment]
@magnolia61 that's pretty promising! How big is your database? (just wanting to  check if it qualifies for performance testing)

**Comment by magnolia61** [comment]
> @magnolia61 that's pretty promising! How big is your database? (just wanting to check if it qualifies for performance testing)
Almost 6000

**Comment by eileenmcnaughton** [comment]
erm - so that would be a no on 'qualifies for performance testing' :-)

@pradpnayak / @davejenx  do you have anything suitable

**Comment by pfigel** [comment]
@eileenmcnaughton I tested #13538 against an instance running Civi 5.7 with ~1.5M contacts. "Use Rule" loads in about 2 minutes. The rule I used was: Last Name: 10, First Name: 10, Birth Date: 10, Threshold: 30

Performance seems to depend heavily on field order. Using "Birth Day" as the first field always leads to timeouts. This also times out: First Name: 5, Last Name: 5, Birth Day: 10, Threshold: 15.

I don't think that's related to the patch though, if I'm reading the code correctly.

**Comment by JoeMurray** [comment]
I think the issue may be that there is no index on the birth_date field (https://github.com/civicrm/civicrm-core/blob/master/xml/schema/Contact/Contact.xml). 

@pfigel could you try 
ALTER TABLE civicrm_contact ADD INDEX index_birth_date birth_date;
then see how the performance on those dedupes works.

Things bog down on create, update and delete if we put too many indexes on a table. We've already got 18 on this table. We could have an extension that would add this. :( Or we could add it to core. :(

Not sure on the best alternative.

**Comment by pfigel** [comment]
@JoeMurray we have an index (`dedupe_index_birth_date`) on that column. Looks like it gets created here when you add a dedupe rule (didn't know about this):
https://github.com/civicrm/civicrm-core/blob/19f10174ac7f7e26328a218a7629f2a42589a5e5/CRM/Contact/Form/DedupeRules.php#L311-L314

I feel like the issues is that the fields are processed one by one, and if you find a lot of contacts with a matching field early on, you end up with a temp table with millions of rows. Let's say you have 1M contacts and on average 50 contacts share the same birth date. That's 50M rows already. Then the next field has to work with that table (doing inserts with UNIQUE constraints, performing updates on the weight if the row exists), so it gets even slower.

Probably the current implementation simply doesn't scale well unless you use the right set of columns in the right order. Can't really think of an easy fix.

**Comment by JoeMurray** [comment]
Thanks for the info on the creation of the index. A few thoughts / guesses:

1. Adding an index to a table with 1M+ rows can be slow - might be worth instrumenting how much time that takes. But it sounds like the real problem occurs when queries that make use of the indexed field are executed.
2. The birth date field is likely a poor first index as it probably has a large number of records with the same value - blank. Might be worth some special work to optimize its use in deduping. 
3. Looking at the specific queries that are run to identify potential dupes would be a good first step. I've not dug into that area, but I'd comment here if you posted them (though I'm off tomorrow).

Cheers, Joe.

**Comment by pfigel** [comment]
Turns out for my example rule group (Last Name: 10, First Name: 10, Birth Date: 10) the fields are actually processed in reverse order . The query sequence looks roughly like this:

```sql
CREATE TEMPORARY TABLE dedupe (id1 int, id2 int, weight int, UNIQUE UI_id1_id2 (id1, id2)) ENGINE=MyISAM;
INSERT INTO dedupe (id1, id2, weight)
  SELECT t1.id id1, t2.id id2, 10 weight
  FROM civicrm_contact t1
  INNER JOIN civicrm_contact t2
    ON (t1.birth_date IS NOT NULL AND t2.birth_date IS NOT NULL AND t1.birth_date = t2.birth_date AND t1.birth_date > '1000-01-01' AND t2.birth_date > '1000-01-01')
  WHERE t1.contact_type = 'Individual'
    AND t2.contact_type = 'Individual'
    AND t1.id < t2.id
  GROUP BY id1, id2, weight
  ON DUPLICATE KEY UPDATE weight = weight + VALUES(weight);
-- ~90s, 10M rows
CREATE TEMPORARY TABLE dedupe_copy SELECT * FROM dedupe WHERE weight >= 10;
-- ~20s
INSERT INTO dedupe (id1, id2, weight)
  SELECT t1.id id1, t2.id id2, 10 weight
  FROM civicrm_contact t1
  INNER JOIN civicrm_contact t2
    ON (t1.first_name IS NOT NULL AND t2.first_name IS NOT NULL AND t1.first_name = t2.first_name AND t1.first_name <> '' AND t2.first_name <> '')
    JOIN dedupe_copy ON dedupe_copy.id1 = t1.id AND dedupe_copy.id2 = t2.id
    WHERE t1.contact_type = 'Individual'
      AND t2.contact_type = 'Individual'
      AND t1.id < t2.id
    GROUP BY id1, id2, weight
    ON DUPLICATE KEY UPDATE weight = weight + VALUES(weight)
-- ~25s
-- ... other fields
```

Having `first_name` or `last_name` as the first query seems to be even slower. For `last_name` it'd take ~200s and create >80M rows in `dedupe`.

Using `ENGINE=MEMORY` would shave off about 50s. Not sure if that would be a problem - I reckon MySQL would just fall back to disk if it goes above `max_heap_table_size`. Still, that doesn't really help if you use something like `last_name` as the first query column (it'd be too slow regardless).

**Comment by JoeMurray** [comment]
1. The temp tables likely need more indexes namely any join or group by field. 2. Is MyISAM still faster than other engines like innodb that have had significant performance optimizations since this code was written? 3. Is the Values() fn really needed? 4. The whole algorithm of increasing weight every dupe seems like it may no longer be most performant. 5. The group by's are very expensive. Not sure how insert into... on dupe update performs on different engines. 6. On first query, it might be faster to a) move tests on single fields from ON to WHERE, b) create a temp table with the named fields using most of the WHEREs to reduce number of records before doing a JOIN, c) check if any casting is being done inappropriately on date constant (don't think so), d) brainstorm ways to avoid string equality testing in favour of int equality test. A few ideas if people have time to muck about.

1 and 6b are most promising is my guess.

**Comment by pfigel** [comment]
Continuing the discussion of #13538 performance [here](https://github.com/civicrm/civicrm-core/pull/13538#issuecomment-462439377).

Re: the MyISAM thing, I accidentally took that part of the query from when I was running this patch against 4.6, and it was changed to InnoDB at some point after that. `MEMORY` would still perform a bit better, but not as much (maybe 15%). The other numbers I posted above are still valid (i.e. were in fact tested against 5.7).

I'll move the performance discussion to a new issue if/when we have some cycles to spend on this (unless someone beats us to it).

**Comment by eileenmcnaughton** [comment]
closing in favour of #13538

**Pull request closed without merging**
