### PR TITLE
CRM-19298, (relates to testing on CRM-19621) fix receipts on separate…  …

### PR DESCRIPTION
**Pull request by eileenmcnaughton**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Actually @KarinG @davejenx @jmcclelland I found a fix for the receipts on membership with separate payment. Even though I was leaning against excluding it from the release on the basis that the issue turned out to be unrelated to the membership update issue in #9390, I decided that I was able to fix it in a way that does not feel scary and that achieves the normal goals of simplifying code & extending testing.

In addition fixing all known bugs in a particular piece of code in the same 'attack' feels like a good approach

**Comment by eileenmcnaughton** [comment]
nb please try the RC 24 hours after this has merged

**Comment by KarinG** [comment]
@eileenmcnaughton - just catching up - ok great - will try the rc tomorrow evening. It will be out around 16:42 PST.

**Comment by eileenmcnaughton** [comment]
I think that is good timing it should be regenerated by then. NB do you test separate payments WITH recurring?

**Comment by KarinG** [comment]
I can test that too - (have not yet) - I've got our full iATS master on this instance.

**Comment by eileenmcnaughton** [comment]
unrelated fails

**Comment by eileenmcnaughton** [comment]
@monishdeb @jitendrapurohit  can one of you help out here. I'm trying to fix the online membership receipt template to not have the (wonky) Additional Contribution section. My fix worked on my newly generated site but I guessed at what was required for the upgrade and @KarinG has tested & tells me it didn't work.....

**Comment by eileenmcnaughton** [comment]
Note if this returns no results the upgrade worked

```
 SELECT id, msg_subject FROM civicrm_msg_template m WHERE m.msg_html LIKE '%Additional Contribution%' AND msg_name = 'Memberships - Receipt (on-line)';
```

**Comment by jitendrapurohit** [comment]
@eileenmcnaughton It doesn't work for me too :-(. I see that message template changes are not included in the upgrade sql file and hence `4.7.14.msg_template/civicrm_msg_template.tpl` is not even executed. The already existing recurring templates too remain unchanged after the upgrade. I've submitted a PR - https://github.com/civicrm/civicrm-core/pull/9491.

@KarinG Can you please verify if the PR works for you ?

**Pull request merged**
