### PR TITLE
CRM-17582 - Allow filtering on deleted participants.

### PR DESCRIPTION
**Pull request by mollux**
[CRM-17582](https://issues.civicrm.org/jira/browse/CRM-17582)

### CODE REVIEW

**Comment by mollux** [comment]
Test failure is unrelated

**Comment by eileenmcnaughton** [comment]
When I first read this I thought it meant the participant record had been deleted - then I realised that table doesn't have an is_deleted field so it must mean deleted contacts. I wonder if other people find that confusing or if I'm just easily confused

**Comment by mollux** [comment]
I agree that the label 'Search deleted participants' isn't that clear.
I can change it in 'Include participants who's contact is deleted' , but that's a long label :)

**Comment by colemanw** [comment]
Since most users don't think in terms of sql tables, (pretty sure it's just you Eileen!) there is no difference in their minds between a "deleted participant" and a "deleted contact."

A label like "Include deleted contacts" might be the clearest, assuming that's actually what the query does. If the query *only* gets deleted contacts instead of including them, then the label should probably say "Deleted contacts"

**Comment by mollux** [comment]
The query only gets the deleted contacts, so I will change the label. 
I think including them makes no sense, as these participants don't "count" anymore, its just to be able to delete them. 

Currently you can't see on a participant if the contact is deleted or not (no red line through the name). Does it make sense to add that?

**Comment by colemanw** [comment]
+1

**Comment by davecivicrm** [comment]
@mollux I think following the convention in Advanced Search for the field label would be best:
 Search in Trash<br />(deleted contacts)
screen shot 2015-11-17 at 3 19 46 pm

**Comment by mollux** [comment]
I was just typing the same idea, to make it the same text like the advanced search  :) I will add the changes to the PR tomorrow.

**Comment by davecivicrm** [comment]
Excellent!

On Tue, Nov 17, 2015 at 3:28 PM, mollux <notifications@github.com> wrote:

> I was just typing the same idea, to make it the same text like the
> advanced search :) I will add the changes to the PR tomorrow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/7228#issuecomment-157544012>
> .
>



-- 
Best regards,
Dave Greenberg
CiviCRM Team
---------------------
Try CiviCRM - http://civicrm.org

**Pull request merged**
