### PR TITLE
Display error if large batches will exceed the php.ini max_input_vars

### PR DESCRIPTION
**Pull request by sleewok**
The default value for max_input_vars in PHP is 1000. Batch entries that are >65 will silently error and break the batch data entry. This change will throw a fatal error if the batch size will fail.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Hi - I think Jenkins is going to tell you there are some style errors  - (2 spaces blah blah see https://www.drupal.org/docs/develop/standards/coding-standards )

If it fails on style you should be able to click on the red x to get a result

**Comment by eileenmcnaughton** [comment]
I'm happy for this to be merged once jenkins gets happy about it

**Review by seamuslee001 — APPROVED** [review]

**Comment by monishdeb** [comment]
@seamuslee001 @eileenmcnaughton should I merge it ?

**Comment by seamuslee001** [comment]
I would say yes

**Comment by monishdeb** [comment]
Done :)

**Comment by mattwire** [comment]
The php max_input_vars is also impacting me on the /civicrm/contact/search/advanced when you do some bulk action such as delete.  No error is thrown but (with max_input_vars=1000) you select the action and on the confirmation page it states: Number of selected contributions: 921.
So not sure if this can be caught and flagged to the user at a higher level?

**Pull request merged**
