### PR TITLE
dev/core#4731 - Fix column index error in SearchKit download

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes [dev/core#4731](https://lab.civicrm.org/dev/core/-/issues/4731)

### CODE REVIEW

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
retest this please

**Comment by TomRosenbloom** [comment]
Reviewing this now

**Comment by TomRosenbloom** [comment]
hi @colemanw this is the first time I've done this so please forgive a couple of queries:

1. trying to review using the automatically generated instance for this PR, this doesn't seem to be working - I'm for e.g. clicking on 'Online demo of this PR' above and seeing 'No sites found' (screenshot below)
2. trying to do it locally, I have some familiarity with Docker so I've fairly painlessly got a local copy running following the instructions here: https://docs.civicrm.org/dev/en/latest/tools/buildkit/docker/ and here: https://lab.civicrm.org/michaelmcandrew/civicrm-buildkit-docker, but I'm stumped at trying to build a local copy from your PR (working from https://docs.civicrm.org/dev/en/latest/tools/civibuild/). I think that's the right approach - to build an entire new copy from the fork/branch for your PR?

Any pointers you can give would be much appreciated!

Screenshot:
Screenshot from 2023-11-01 16-44-14

**Comment by colemanw** [comment]
@TomRosenbloom the demo sites get cleaned up if not used for a few days. This will regenerate one:
@civicrm-builder retest this please

Now if you click the demo link you'll see a site available.

For local testing, the easiest way is to download a patch. If you jut append `.diff` to the end of this url like https://github.com/civicrm/civicrm-core/pull/27943.diff then you can download that text file and apply it locally. Lots of instructions online about how to apply a patch, but it's pretty simple. Basically:
```
cd path/to/civicrm
wget https://patch-diff.githubusercontent.com/raw/civicrm/civicrm-core/pull/27943.diff
patch -p1 < 27943.diff
```

**Comment by eileenmcnaughton** [comment]
@TomRosenbloom I've merged this so it is in time for the 5.68 rc - perhaps you could download the rc when it is cut & test there to confirm this is all good. (It will also be on the main dmaster.demo.civicrm.org site now)

**Comment by TomRosenbloom** [comment]
@eileenmcnaughton will  do

**Pull request merged**
