### PR TITLE
CRM-19715 (IIDA-96), removed opening_balance and current_period_openi…

### PR DESCRIPTION
**Pull request by pradpnayak**
…ng_balance field from civicrm_financial_account table and code

----------------------------------------
* CRM-19715:
  https://issues.civicrm.org/jira/browse/CRM-19715

CRM-19715, added DAO changes

----------------------------------------
* CRM-19715: Remove Close Accounting Period code
  https://issues.civicrm.org/jira/browse/CRM-19715

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
So, this code looks fine. How do we convince ourselves we can remove those fields with no impact on anyone? It looks like they were added in 4.7.9 so it isn't such a short time.  (about 9 months)

The best idea I have is to only drop them if they are empty & add a System_Check that reports an error to the site if they continue to exist.

**Comment by JoeMurray** [comment]
Just noting here before putting in issue...The functionality is being moved into an extension. We think on upgrade, if there is relevant data, then the extension should be installed during the upgrade, and the upgrade code should copy data over before the fields are dropped. This requirement will be added, as a UX for changing the fields was added 4.7.9.

**Comment by pradpnayak** [comment]
@eileenmcnaughton i have updated PR. I removed upgrade script to Drop opening_balance and current_period_opening_balance. I will send a separate PR for it as it requires php coding to drop those 2 fields if current_period_opening_balance = 0 and opening_balance = 0

**Comment by eileenmcnaughton** [comment]
I've merge this - can you do a last grep for relevant strings before closing the JIRA @pradpnayak

**Comment by pradpnayak** [comment]
@eileenmcnaughton  yes sure.

**Pull request merged**
