### PR TITLE
CRM-19658 test for is_email_receipt override

### PR DESCRIPTION
**Pull request by KarinG**
Added a test for https://github.com/civicrm/civicrm-core/pull/9353

---

 * [CRM-19658: TEST for CRM-19601 \/ PR 9353](https://issues.civicrm.org/jira/browse/CRM-19658)

---

 * [CRM-19601: api calls to completetransaction and repeattransaction parameter is_email_receipt ignored](https://issues.civicrm.org/jira/browse/CRM-19601)

### CODE REVIEW

**Comment by KarinG** [comment]
Orginal JIRA ticket: https://issues.civicrm.org/jira/browse/CRM-19601
JIRA ticket for the test: https://issues.civicrm.org/jira/browse/CRM-19658

**Comment by KarinG** [comment]
Jenkins test please

**Comment by KarinG** [comment]
Jenkins test this please!

**Comment by KarinG** [comment]
https://issues.civicrm.org/jira/browse/CRM-19658

**Comment by KarinG** [comment]
Ok - so the test is 'correctly' failing -> as that's why we need https://github.com/civicrm/civicrm-core/pull/9353

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I've just copied the above test to demonstrate how to test no email actually goes out - that would be a valuable addition here

```
  /**
   * Test the submit function on the contribution page.
   */
  public function testSubmitEmailReceipt() {
    $form = new CRM_Contribute_Form_Contribution();
    $mut = new CiviMailUtils($this, TRUE);
    $form->testSubmit(array(
      'total_amount' => 50,
      'financial_type_id' => 1,
      'receive_date' => '04/21/2015',
      'receive_date_time' => '11:27PM',
      'contact_id' => $this->_individualId,
      'is_email_receipt' => TRUE,
      'from_email_address' => 'test@test.com',
      'contribution_status_id' => 1,
    ), CRM_Core_Action::ADD);
    $this->callAPISuccessGetCount('Contribution', array('contact_id' => $this->_individualId), 1);
    $mut->checkMailLog(array(
        '<p>Please print this receipt for your records.</p>',
      )
    );
    $mut->stop();
  }
```

**Comment by KarinG** [comment]
@eileenmcnaughton - What if that message/text '<p>Please print this receipt for your records.</p>' changes? It would make this test fail. I decided to go with a test to check if a receipt_date is recorded. But of course that also contains assumptions.

**Comment by eileenmcnaughton** [comment]
@KarinG yep - it does cause the test to fail & people have to fix it - but I think that level of brittleness is ok because if it is a real result of a change the person will be able to identify easily.

NB you don't have to take this further - I did merge it - but maybe someone preparing for gsoc will

**Pull request merged**
