### PR TITLE
[REF] Switch a bunch of core pages to use auto-links

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Follow-up to #26644

Before
----------------------------------------
Hard-coded links

After
----------------------------------------
Auto-links. Added `paths` and `title` metadata where missing.

Comments
----------------------------------------
Because I was bored on the plane.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I just clicked on a whole lotta links - I didn't test entity role or sms but I think I tried all the others...

**Comment by colemanw** [comment]
Thanks @eileenmcnaughton I've updated the docs to reflect the new weight for ENABLE

**Comment by aydun** [comment]
> Because I was bored on the plane.

Clearly we should send you on more flights @colemanw !

**Comment by colemanw** [comment]
@aydun I noticed that all of the pages I refactored in this PR would be good candidates for `civicrm_admin_ui`!
I've added `paths` where needed. The only other thing is that most of them will need `/edit` appended to those paths (IMO it is fine to use `/edit` for create and edit and delete since they all use the same form... maybe not *ideal*, but fine) and the new path added to the menu.xml so the page and form are not both at the same overloaded url.

**Comment by aydun** [comment]
Thanks @colemanw   Several of those are already in AdminUI.  I've added the others to the list at https://lab.civicrm.org/dev/core/-/issues/3912

**Pull request merged**
