### PR TITLE
Improve user checking for mailing reports

### PR DESCRIPTION
**Pull request by davejenx**

### CODE REVIEW

**Comment by seamuslee001** [comment]
@jackrabbithanna @totten this is a backport of https://github.com/civicrm/civicrm-core/pull/10421 Should only merge after June release and once #10421 is merged as well

**Comment by guanhuan** [comment]
https://issues.civicrm.org/jira/browse/CRM-20442

**Comment by seamuslee001** [comment]
@jackrabbithanna this can be merged now

**Comment by jackrabbithanna** [comment]
Merging #10422

**Comment by jackrabbithanna** [comment]
I'm inclined to merge this, for security reasons, and to keep 4.6 somewhat in sync technology wise.  If we have problems with it @seamuslee001 we would need to make any fixes and get them in a release ASAP if things go sideways.  Should we wait a week until 4.7 rc is tested more and we see if there are any problems there?

**Comment by seamuslee001** [comment]
@jackrabbithanna up to you mate, I think that is possibly quite a reasonable strategy the main thing is to make a call to merge or not before the release date, I feel this is pretty safe and is a direct backport from master. Agree and happy to help to work if we need to make emergency fixes. We have at least another 2/3 weeks before release so we can take time if needed

**Comment by jackrabbithanna** [comment]
I commented on the wrong issue....I think this is fine, merging

**Pull request merged**
