### PR TITLE
(REF) Schema - Fix boolean fields in various tables - Split commits

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

This is re-commit of #22954 which aims to improve debugging.

cc @demeritcowboy @monishdeb @colemanw 

Before
----------------------------------------

Numerous fields changed - monolithic commit. Hard to bisect.

After
----------------------------------------

Numerous fields changed - broken into separate commits.

Comments
----------------------------------------

I also made a code-change, splitting the large array in `FiveFortyNine.php` into several smaller files. Some oddities struck me, so I added comments about those.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Thanks @totten. Would also like to revisit the reasoning behind any where before it was implicitly null and now default is explicitly 1. (e.g. menu.is_public)

**Comment by demeritcowboy** [comment]
So I'm ok to merge as-is since should be a no-op. Was that the intent?

**Comment by totten** [comment]
@demeritcowboy I share the presumption that `DEFAULT null`  is more like `DEFAULT 0`, though the other PR has a good point about `is_active` as an exception.  The challenge here is that we have actually had two people give a run-through, and so probably most of the decisions are right, but it's such a long list... that some oddities slip though (like `civicrm_menu.is_public` and `civicrm_report_instance.is_active`).

If we want an exercise to improve confidence in the list as a whole, these two possible exercises come to mind:

* Get more eyes to run through all the changed fields. (Like we each give an additional +1/-1 read on a dozen items... maybe make a table to help divide-and-conquer that effort.)
* Generate some kind of data table comparing the various XML/DAO/SQL/API defaults (and nullability) across both versions. Give extra review to anything with a substantive flip (like `is_public`).

**Comment by totten** [comment]
> So I'm ok to merge as-is since should be a no-op. Was that the intent?

Yeah, I'm down with that.

**Comment by colemanw** [comment]
@monishdeb can you please check the code comments @totten added in this PR and do a followup if necessary?

**Comment by demeritcowboy** [comment]
Note also that menu.is_public is the cause of alert popups not popping up and the oversized styling that fields have now, e.g. on New Individual.

Untitled2

Untitled3

**Comment by colemanw** [comment]
So that's a regression caused by #22954?
Ping @monishdeb

**Comment by demeritcowboy** [comment]
Yes. See thread yesterday in prod-maint chat about weird styling.

**Comment by agileware-justin** [comment]
Related regrets:
https://lab.civicrm.org/dev/core/-/issues/3465
https://lab.civicrm.org/dev/core/-/issues/3464

**Pull request merged**
