### PR TITLE
CRM-20946, use line total of line item to store in financial item table

### PR DESCRIPTION
**Pull request by pradpnayak**
----------------------------------------
* CRM-20946: Wrong entries in financial table when contribution is cancelled
  https://issues.civicrm.org/jira/browse/CRM-20946

### CODE REVIEW

**Comment by Edzelopez** [comment]
Tested patch for the following scenario:

1. Added membership with priceset of options $10 and $20.
2. Set contribution status to pending before saving membership.
3. Cancelled contribution.

Amounts were not proportionally assigned to entries in entity trxn table.
beforepatch

After patch:
Reversal entries are proportionally assigned.
afterpatch

**Comment by pradpnayak** [comment]
@colemanw / @eileenmcnaughton  can you please review?

**Comment by eileenmcnaughton** [comment]
I feel like we have been adding a lot of unit testing covering that function, and the fact this continues to pass unit tests gives me a lot of confidence ... you know where this is going don't you..... if you add a unit test I think this is OK to merge.

**Comment by monishdeb** [comment]
@eileenmcnaughton I have added unit test https://github.com/civicrm/civicrm-core/pull/10726/commits/338a3c3e88d4391d778b444de2831e6e7601a896

**Comment by eileenmcnaughton** [comment]
Looks like editing the xml dataset had some flow on effects...

**Comment by monishdeb** [comment]
@eileenmcnaughton yup forgot to cleanup those newly added contacts in xml. It's fixed now and tests build passes.

**Comment by eileenmcnaughton** [comment]
OK - this looks good to me - the change is the variable passed when deciding if it is a negative or positive transaction and the unit test gives me confidence that this part won't regress again when we do further tweaking

**Pull request merged**
