### PR TITLE
CRM-20546: Multiple issues with creation of membership activities

### PR DESCRIPTION
**Pull request by jitendrapurohit**
Also expands #10323 with additional fixes related to renewal activities creation.

* [CRM-20546: Purchasing a Membership online results in 5 Activities, 2 x Contribution ones, plus Renewal and Signup and Status change](https://issues.civicrm.org/jira/browse/CRM-20546)

### CODE REVIEW

**Comment by petednz** [comment]
@Stoob any chance you can also review since this issue has been a bit of pinball!

**Comment by eileenmcnaughton** [comment]
@monishdeb aren't you working on this too?

**Comment by jitendrapurohit** [comment]
@eileenmcnaughton No, actually the fix for CRM-20546 conflicted with already opened PR of Monish, so had a conversation with him yesterday and extended his PR https://github.com/civicrm/civicrm-core/pull/9468 to fix the extra comments mentioned by Pete https://github.com/civicrm/civicrm-core/pull/9468#issuecomment-289977796

**Comment by joannechester** [comment]
Tested and comments are at; https://issues.civicrm.org/jira/browse/CRM-20546

**Review by monishdeb — APPROVED** [review]
Thanks @jitendrapurohit for making additional fixes and extending desired unit tests. And thanks @joannechester for your review

**Comment by eileenmcnaughton** [comment]
Merging - I agree with @monishdeb this seems to have been confirmed as an improvement by @joannechester  and there is test coverage. I was going to say the code seems to be improved but we seem to have one long function extracted (good) but another long chunk of code added in another function. Perhaps that could have been extracted for readability. Anyway, I'm happy this has been reviewed & tested

**Pull request merged**
