### PR TITLE
dev/core#2666 - (Alternate) Don't repeatedly log about crm-l10n.js during upgrade

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
Alternate to https://github.com/civicrm/civicrm-core/pull/20889

### CODE REVIEW

**Comment by seamuslee001** [comment]
this makes sense but want @totten @colemanw to comment

**Comment by colemanw** [comment]
This makes sense but now I have to ask... if we're in upgrade mode, why add *any* core resources at all? Isn't upgrade mode only true for the ajax callback to run an upgrade step?

**Comment by seamuslee001** [comment]
@colemanw it is also for the /upgrade urls which is the pre ajax and post ajax steps iirc and after and also its upgrade mode if set by drush/wp/cv iirc https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/Config.php#L403

**Comment by colemanw** [comment]
Ok then this is fine

**Comment by demeritcowboy** [comment]
Thanks all.

**Pull request merged**
