### PR TITLE
[NFC] Short array syntax - auto-format CRM directory

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Converts the CRM/ directory to short array syntax.

Before
----------------------------------------
array()

After
----------------------------------------
[]

Notes
--------
Uses https://github.com/thomasbachem/php-short-array-syntax-converter

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw so bear in mind
1) this will make every PR in the Q go stale. For many that won't be a be bad thing as they are stalled on needing a unit test or something & there has been no movement for a while - but I think we should try to get the review q as low as we humanly can first
2) this will make back-ports hard. Given this code is about to be cut to be the basis of the 5.13 ESR it might be good timing - as long as there is no plan to do any further backports to 5.7

ping @mlutfy @totten @seamuslee001

**Comment by colemanw** [comment]
Amazing that it's been 24 hours and this is still mergable!
Doubt it will last too much longer tho.

**Comment by eileenmcnaughton** [comment]
@colemanw Wanna re-do this now & we can merge IMHO. If it makes other PRs go stale then we should close all the ones without the 'has-test' label & ask them to rebase & re-open (after addressing any outstanding feedback).

With the has-test ones we might try to see if we can salvage them ourselves

**Comment by colemanw** [comment]
@eileenmcnaughton I've rebased it.

**Comment by eileenmcnaughton** [comment]
@colemanw not to jenkins liking :-(

**Comment by eileenmcnaughton** [comment]
Maybe breaking it up would help to work out the issues - I think jenkins stds changed

**Comment by eileenmcnaughton** [comment]
So just looking at this - it's actually only a handful of dirs involved I think - I'm putting up a couple of them so you can drop the bulk from this

**Comment by eileenmcnaughton** [comment]
After worrying at this a bit I concluded the best plan is to remove all problematic files from this (which I'm currently doing) & get this merged & then follow up with them. I've removed perhaps more than needed I think but that seems OK

**Comment by eileenmcnaughton** [comment]
I dropped out quite a few files but it's now getting past style - let's merge & then try to mop up

**Pull request merged**
