### PR TITLE
Replace calls to property with standardised getPaymentProcessorObject

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
partial of https://github.com/civicrm/civicrm-core/pull/28617/files#diff-c683b948c8375b8bcc28cea8d54c2210bf8e94e8229b151666c94db370970b36R28

### CODE REVIEW

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test fails are unrelased

**Pull request merged**
