### PR TITLE
Fix for issue 2685

### PR DESCRIPTION
**Pull request by sadashivdalvi**
Issue is reported at https://lab.civicrm.org/dev/core/-/issues/2685

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins ok to test

**Comment by seamuslee001** [comment]
@eileenmcnaughton this I think is a possible intra regression from your $ids work

**Comment by eileenmcnaughton** [comment]
Yeah dang - I thought I could switch it to the rc as we should merge to the 5.40 branch but it is NOT clean - @sadashivdalvi are you able to rebase over the 5.40 branch and force push (probably easiest is to git reset --hard origin/5.40  & then just cherry-pick your patch back on - then us -f when pushing to github)

**Comment by sadashivdalvi** [comment]
ok, will rebase over 5.40 and apply this on it.  Should I then create a PR from there and we close this PR?

**Comment by seamuslee001** [comment]
@sadashivdalvi if you force push onto this current branch it you shouldn't need to re-create the PR

**Comment by sadashivdalvi** [comment]
ok, I did rebase and force push, now you can check and merge.

Thanks,
Sadashiv

**Pull request merged**
