### PR TITLE
Return NULL if variable to convert isoToMysql is null

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
When copying a event or creating new from template having schedule reminder, throws DB:error

Incorrect datetime value: '0' for column civicrm_action_schedule.effective_start_date at row 1

Before
----------------------------------------
When copying a event or creating new from template having schedule reminder, throws DB:error

After
----------------------------------------
Event created with schedule reminder 

Technical Details
----------------------------------------
When event is copied, the CRM_Event_BAO_Event::copy() uses DAO copyGeneric() function to copy Action Schedule data linked to event. When a schedule reminder has effective_start_date set to NULL in database the [CRM_Utils_Date::isoToMysql()](https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/DAO.php#L1816) returns empty string instead of NULL which i guess causes db package to set the value to 0. I am not sure if i need fix the code in copyGeneric() function to not call isoToMysql() if the value is NULL, but thought this might occur of any date field across the code.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
* General standards
    * [`r-explain`] __Soft Pass__
      * It's important to note the problem only comes up if you have sql_mode with NO_ZERO_DATE.
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __PASS__
      * Can reproduce and it fixes it.
* Developer standards
    * [`r-tech`] __PASS__
      * It's a good question where it should go but this seems like an ok place.
    * [`r-code`] __Issue__
      * I'd suggest using empty() instead of CRM_Utils_System::isNull. That function is kooky, and in this case would let a literal `0` through which you don't want.
    * [`r-maint`] __?__
    * [`r-test`] __PASS__

**Comment by demeritcowboy** [comment]
Just cross-referencing: https://github.com/civicrm/civicrm-core/pull/20113 and https://lab.civicrm.org/dev/core/-/issues/2558

**Comment by pradpnayak** [comment]
Hi @demeritcowboy 

Thanks for reviewing, i have changed the code to use empty().

**Comment by demeritcowboy** [comment]
Ok thanks so I think then the remaining question is if this is the right place for it. The linked PR maybe has it in a more generic spot but it's in a 3rd party library so would vote for this one.

One thing this changes is the following situation, but I think it's a good thing (:tm:)

Before:
1. Suppose sql_mode does not have NO_ZERO_DATE
2. Suppose code tries to insert the empty string into a date field defined as NOT NULL.
3. Inserts 0000-00-00, no crash.

After:
1. Crash with "column can not be null", but the code should not be trying to insert a blank into a NOT NULL date field to begin with so this will make those bad spots more obvious. (This is a different situation than the event reminder date where it's allowed to be blank.)

**Comment by eileenmcnaughton** [comment]
@demeritcowboy @pradpnayak  - does this work as an alternate fix? https://github.com/civicrm/civicrm-packages/pull/320

**Comment by demeritcowboy** [comment]
Sorry @pradpnayak the other PR won because it had [more brackets](https://github.com/civicrm/civicrm-packages/pull/322). (That's not the reason - just trying to make a joke.)

**Pull request closed without merging**
