### PR TITLE
ContactSummary - Make notes tab hierarchical

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Building on #31189 and #31408, this makes the contact summary notes tab a collapsed hierarchical display.

Before
----------------------------------------
Notes on notes were shown separately in a popup.

After
----------------------------------------
Notes on notes are shown inline in a hierarchical tree.

Technical Details
---------
This was more difficult than it needed to be because `civicrm_note` doesn't have a simple `parent_id` field but instead uses `entity_table`+`entity_id` to represent either the note parent OR the entity being noted. A `parent_id` column would have been simpler to deal with, but anyway I got it working.

### CODE REVIEW

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by monishdeb** [comment]
@colemanw I noticed an issue with when there is a more then more level 2 hierarchy. Here are the steps: 
1. Add a note - test
2. Add a comment/note 'Test 1.1' on note 'test'
3. Add a comment/note 'Test 1.2' on note 'test'
4. Add a comment/note 'Test 1.1.1' on note 'Test 1.1'

Issue: On tab refresh the note #3 is not present in the hierarchy. It seems like when there is a level 3 note it overrides or hides the other level 2 notes: 
event1

**Comment by colemanw** [comment]
Thanks @monishdeb - looks like that was a pre-existing bug in the new collapsible feature so I've made a PR for 5.80: https://github.com/civicrm/civicrm-core/pull/31474

**Comment by monishdeb** [comment]
Ok after applying the patch from https://github.com/civicrm/civicrm-core/pull/31474 it works fine. Hence merging the PR.

**Pull request merged**
