### PR TITLE
Fix unreplaced template vars in civicrm.settings.php when using legacy installer

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
When using the legacy installer (e.g. sites/all/modules/civicrm/install/index.php) it leaves behind some unreplaced ssl-related template variables.

Before
----------------------------------------
DSN in civicrm.settings.php looks like `mysql://foo:bar@localhost/cividb?new_link=true%%dbSSL%%` after install.

After
----------------------------------------
`mysql://foo:bar@localhost/cividb?new_link=true`

Technical Details
----------------------------------------
The ssl vars are only replaced when using the newer civicrm-setup.

Comments
----------------------------------------
See also https://github.com/civicrm/civicrm-joomla/pull/63

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Jenkins retest this please.

```
PhantomJS 2.1.1 (Linux x86_64) ERROR
Disconnected , because no message in 30000 ms.
```

**Comment by totten** [comment]
This looks safe and reasonable on its own.

Not a blocker, but possibly related - I don't see `dbSSL` in `civicrm.drush.inc` for BD/D7/D8?

**Comment by demeritcowboy** [comment]
Oh that probably has the same problem then. And wp-cli if it does installs too.

**Comment by demeritcowboy** [comment]
Have added https://github.com/civicrm/civicrm-core/pull/21710 as alternate but for readability I think I'd prefer this one and just try to find all the spots where it's used, but the upgrade message might be useful either way.

**Comment by totten** [comment]
Yeah, I think they're complementary. #21692 looks like a fix for new installations, and #21710 looks like cleanup for existing installations.

**Comment by demeritcowboy** [comment]
I meant I would move the upgrade message here and close that one if this is the more desirable route.

**Pull request merged**
