### PR TITLE
CRM-17492 fix - Query speed issue searching on transaction ID

### PR DESCRIPTION
**Pull request by monishdeb**
https://issues.civicrm.org/jira/browse/CRM-17492

### CODE REVIEW

**Comment by colemanw** [comment]
jenkins retest this please

**Comment by eileenmcnaughton** [comment]
Can you just talk me through activity_type_id & activity status id - do they always come in from the form as an array? & hence the 'IN' logic is used?

**Comment by davecivicrm** [comment]
@eileenmcnaughton The Activity Search form supports > 1 activity type AND > 1 activity status in the search criteria - so I imagine they would need to be arrays.

**Comment by monishdeb** [comment]
Yup and we are using multi-select2 element for those two fields and always be in array >=1

**Comment by davecivicrm** [comment]
@monishdeb In my testing this PR causes on regression on Activity Search by Activity Status. I set Status filter to "Completed" activities only, and the search returned activities with status = Scheduled. I reverted the patch and this did NOT happen.
screen shot 2015-12-14 at 10 41 39 am

**Comment by monishdeb** [comment]
Updated the pr.

**Comment by davecivicrm** [comment]
Last fix looks good. Thanks.

**Pull request merged**
