### PR TITLE
CRM-20640: contribution summary report: duplicates values with group filter

### PR DESCRIPTION
**Pull request by monishdeb**
* [CRM-20640: contribution summary report: duplicates values with group filter](https://issues.civicrm.org/jira/browse/CRM-20640)

### CODE REVIEW

**Comment by monishdeb** [comment]
Before : 
image

After fix:
image

**Comment by lcdservices** [comment]
this works great. looks like it may have affected other reports as well.

**Comment by monishdeb** [comment]
Yup that's for sure :)

**Comment by eileenmcnaughton** [comment]
I'm going to merge this because it makes sense. My guess is there might be a performance hit (since adding DISTINCT often has that impact) so it would be ideal to add a unit test to avoid this getting broken again if that gets addresses. There are some existing tests that lay the ground work https://github.com/aydun/civicrm-core/blob/76f2bcedbb714b6785edbdae1d65fcf6a885e1d8/tests/phpunit/api/v3/ReportTemplateTest.php#L351-L351

I'll go ahead & merge this but I would suggest you don't close this out at your end without adding the test

**Comment by monishdeb** [comment]
@eileenmcnaughton this was a regression due to this commit https://github.com/civicrm/civicrm-core/commit/43c1fa192f5ef4e0b34877a49bf0bc5bfe9e307c#diff-d355cdb00cea3915a3cf306c6c08f6a6R3492. As I believe this a miss, (like I said earlier) because the DISTINCT was added (see the link which points to line 3492) for retrieving smart group contacts but not added to fetch contacts of the regular group. I agree that adding DISTINCT will impact performance a bit, alternative would be to use ```GROUP BY group_contact.contact_id``` instead. 

 Thanks for referring that unit-test, will extend it by adding filter to assert this use-case.

**Comment by monishdeb** [comment]
However, on second thought, use of DISTINCT optimizes memory usage but lack speed and for GROUP BY, its nature in terms of performance is just the opposite. So I think we should retain DISTINCT for fetch group contact like we are using in contact's search query.

**Comment by eileenmcnaughton** [comment]
I think you'd have to do testing on some big DBs to determine distinct vs group by - my money says mysql does the same thing under the hood anyway. But, I don't think you need to to solve the performance issue - just protect yourself (with a test) against someone else solving it & rebreaking your fix

**Pull request merged**
