### PR TITLE
Ensure tax_amount is not null

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Per discussion https://github.com/civicrm/civicrm-core/pull/26920#issuecomment-1660069858 - let's ensure tax_amount is 0 rather than NULL

Before
----------------------------------------
Some old data might have NULL in tax_amount

After
----------------------------------------
would be $0

Technical Details
----------------------------------------
I figured we should try to get this into 5.65 hence adding a PR now

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
Tests are happy with this. @eileenmcnaughton what about setting the column to be NOT NULL?

**Comment by totten** [comment]
FWIW, all the `civicrm_contribution` records in the sample data have `tax_amount=null`.

**Comment by eileenmcnaughton** [comment]
I've added the required +default thing (I think the sample data picks that up )

**Comment by colemanw** [comment]
Great! This is passing tests and is clearly an improvement.

**Pull request merged**
