### PR TITLE
[REF] Remove excess handling around contact_id

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
[REF] Remove excess handling around contact_id

The removed code was formerly in a shared function. On looking the
getIDS actually just gets the contact id from the contributionRecur
object & every thing else is extraneous

Before
----------------------------------------
Lotsa code - not a lot of action

After
----------------------------------------
Poof

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton test fails relate here 

```
CRM_Core_Payment_AuthorizeNetIPNTest.testIPNPaymentRecurNoReceipt
CRM_Core_Payment_AuthorizeNetIPNTest.testIPNPaymentRecurSuccess
CRM_Core_Payment_AuthorizeNetIPNTest.testIPNPaymentRecurSuccessMultiAuthNetProcessor
CRM_Core_Payment_AuthorizeNetIPNTest.testIPNPaymentRecurSuccessSuppliedReceiveDate
CRM_Core_Payment_AuthorizeNetIPNTest.testIPNPaymentMembershipRecurSuccess
CRM_Core_Payment_AuthorizeNetIPNTest.testIPNPaymentMembershipRecurSuccessNoLeakage
CRM_Core_Payment_AuthorizeNetIPNTest.testIPNPaymentMembershipRecurSuccessNoLeakageOnlineThenOffline
```

**Comment by eileenmcnaughton** [comment]
Yep - looks like there were a couple of other unnecessary references to it

**Comment by seamuslee001** [comment]
changes look fine to me merging

**Pull request merged**
