### PR TITLE
Fixed fatal error on update multiple case

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
https://civicrm.stackexchange.com/questions/42158/trying-to-bulk-update-cases-through-finding-them-and-profile

Before
----------------------------------------
Bulk update on case via profile failed

After
----------------------------------------
Bulk update on case via profile successful

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Hi @pradpnayak with this patch applied I get `TypeError: Argument 1 passed to CRM_Core_Form_Task::setNextUrl() must be of the type string, null given, called in ...\CRM\Core\Form\Task.php on line 198 in CRM_Core_Form_Task->setNextUrl() (line 97 of ...\CRM\Core\Form\Task.php).`

FYI while I see the deprecations I'm still not sure how to trigger a fail before the patch based on the stackexchange post.

**Comment by demeritcowboy** [comment]
Those steps work for me without fail, just some deprecations.

**Comment by pradpnayak** [comment]
> Those steps work for me without fail, just some deprecations.

Strange, I was able to replicate on dmaster.



https://user-images.githubusercontent.com/2053075/174816005-6f9f2107-ae7a-435e-b6af-99b1fbe7a3b7.mov

**Comment by demeritcowboy** [comment]
Oh I see - when you use the ALL radio instead of selected results.

**Comment by adam-devapp** [comment]
Tested and works on D7 + 5.50.3 CiviCRM on find case -> select bulk update on entries -> select profile -> bulk update. Was producing a fatal error screen before on bulk update load screen.

**Comment by pradpnayak** [comment]
Thank you @demeritcowboy reviewing and testing the PR and @adam-devapp for testing

**Pull request merged**
