### PR TITLE
PHPCS standards on css....

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
I ran phpcbf over our code base & it made these changes to the css - I guess the
standard must prefer them....

@colemanw  I guess these are more compliant with whatever standard it is applying .... I expect we normally skip these folders with phpcs hence no fails normally

### CODE REVIEW

**Comment by totten** [comment]
I had no idea our `phpcs` ruleset had any coverage for CSS... but these changes to look fine IMHO...

**Comment by eileenmcnaughton** [comment]
@totten yeah - I think maybe we skip them somehow when we actually run it. I just ran that `phpbcs` or whatever with our drupal ruleset & it did this

As an aside - we don't seem to grab our coder by default in the buildkit tools?

**Comment by totten** [comment]
Link above is an update for buildkit/civilint to run `phpcs` on `*.css` files.

Buildkit does download Civi's phpcs ruleset, but you have to pass the `phcps --standard=....` option to use it. The commands `phpcs-civi` and `civilint` both set the `--standard` appropriately, but a direct call to `phpcs` would require setting the standard explicitly.

**Comment by totten** [comment]
To my eye, all changes here look (NFC).

Adding 'merge ready' in case @colemanw has further comments.

**Comment by colemanw** [comment]
Agreed.

**Pull request merged**
