### PR TITLE
Remove unused property - not used since import code refactor `_lineCount`

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Remove unused property - not used since import code refactor `_lineCount`

Before
----------------------------------------
image

After
----------------------------------------
poof

Technical Details
----------------------------------------
There is one 'get' on it - that is clearly broken -  I commented that to make it clear for whoever next visits it, There is also one in a deprecated function.

UPDATE - I have a follow on patch that fixes the broken  - not sure whether to push in here or if that would complicate.

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Oh nice - that confirms we have test cover on the specific place with the relevant already broken code - I'll push up the patch that fixes

image

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
persistent fail - but does not feel related - test this please

image

**Comment by colemanw** [comment]
Refactor makes sense

**Pull request merged**
