### PR TITLE
dev/core#1015 Unit test for fix regression on exporting soft credits 

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This adds the unit test for the fixed bug

Before
----------------------------------------
No test

After
----------------------------------------
Test

Technical Details
----------------------------------------
Test portion of https://github.com/civicrm/civicrm-core/pull/14456

Comments
----------------------------------------
Pr has been problematic on tests - submitting test & fix part separately (either is mergeable without the other & it's unclear which is causing problems although working theory is the issue lies with the test leaving DB unclean)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton definitely the tests but the other changes we have merged haven't helped identify what is going on here

**Comment by seamuslee001** [comment]
It feels like something isn't being properly torn down or something i dunno

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I think is failing due to null contamination - we've merged one fix so will retest but it might not be the right one (it was either this or the payment.create one's test fails that got me onto the null as the cause

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 interesting to see related failures here 'move around' as you have removed NULL ARRAY instances... - trying again after the last merge

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton can you rebase this now please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 done

**Review by seamuslee001 — APPROVED** [review]

**Comment by seamuslee001** [comment]
This looks good to me now. Merge on Pass

**Comment by eileenmcnaughton** [comment]
cross fingers! This has been a long road!

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
merging based on @seamuslee001 having marked as 'approved' (& being NFC) - @seamuslee001 YAY finally!

**Pull request merged**
