### PR TITLE
dev/core#5395 ensure number assigned

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
dev/core#5395 ensure number assigned

Before
----------------------------------------
Could wind up as NULL - seems like it causes a js error 

After
----------------------------------------
always a value

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 as discussed - this & the port

**Comment by demeritcowboy** [comment]
This eliminates the js error, but then when you try to save the membership you get

```
 Please correct the following errors in the form fields below:
   Select at least one membership option.
```

**Comment by demeritcowboy** [comment]
I just checked in 5.69 and you get that same error message on save.
So I'm thinking this is one of those "better in than out" fixes, but the feature itself has maybe never worked? So I'll put merge-ready.

**Comment by eileenmcnaughton** [comment]
OK - thanks @demeritcowboy - we put this up based on the gitlab - & yeah no js is better - so merged - as I understand it the logged issue is saying that when a price set has 2 fields and 1 has a membership option selected & the other does not they are not allowed to submit the form - even though a membership option is selected?

**Pull request merged**
