### PR TITLE
CRM-21075 Replace call to CRM_Core_OptionGroup::getValue with CRM_Cor…

### PR DESCRIPTION
**Pull request by seamuslee001**
…e_PseudoConstant::getKey in CommunicationsPreferences edit

Overview
----------------------------------------
When a user would edit their record, a series of notices would be generated because of use of a deprecated function. This no longer happens. 

Before
----------------------------------------
Notices appear about use of deprecated function

After
----------------------------------------
Notices do not appear anymore. I have tested this on a local buildkit install and appears to work as expected.

@JoeMurray @eileenmcnaughton @totten does this look right?

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This looks right to me (not yet tested myself), but, why is this against the rc?

**Comment by seamuslee001** [comment]
@eileenmcnaughton Joe felt that it should be against the RC as per chat in dev-postrelease but happy to shift to master if that is the consensus

**Comment by eileenmcnaughton** [comment]
I don't feel this meets the criteria - it's not a regression, it does not affect properly configured production sites & it is not critical

**Comment by eileenmcnaughton** [comment]
I just tested this against master & am ready to merge it against master. I created a contact using the 'new individual' block & witnessed the error messages. After applying the patch the messages did not appear. Crucially the greeting fields were populated the same on the 2 contacts created - per screenshot

screenshot 2017-08-22 12 32 17

**Comment by seamuslee001** [comment]
@eileenmcnaughton this has passed testing

**Pull request merged**
