### PR TITLE
CRM-19743 Ensure that checking for id in sort column works in arrays …

### PR DESCRIPTION
**Pull request by seamuslee001**
…as well as strings

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Review by jitendrapurohit — APPROVED** [review]
seems to be risk-free, works fine for me.

**Comment by adixon** [comment]
Okay, 'seems to be risk-free' is really not helpful. This code gets used all over CiviCRM and its extensions, and it has been broken for some time, apparently. The new code definitely looks better, but even if it is, we may be inadvertently breaking calls that depended on its previously incorrect behaviour. So let's flag this as definitely needing attention and testing and not rush out a fix that breaks other things.

**Comment by jitendrapurohit** [comment]
I truly get your concern regarding unintentionally breaking calls, but I see if some piece of code works with the previous incorrect behaviour seems to be also supported now as the changes here is only moving and placing a block of code to a right place. 

Also it contains a test for different inputs along with merge build executing clean for the changes.

**Comment by adixon** [comment]
The previous incorrect behaviour I'm referring to - I mean the one from before Oct 25 i.e. before the security patch that broke 4.6.24. So for example, previously, any call to an api with a sort argument of an array instead of a string would appear to have been ignoring the sort argument. With this new patch, it is correctly sorting the result, i.e. it has changed.  I think it would be helpful to identify why the security patch only broke 4.6.24, that might be instructive. We can see that the code was wrong and it broke 4.6 for editing and viewing recurring contributions, but for some reason that particular instance of the error didn't show up in 4.7. That might mean that the error for some reason never occurred in 4.7, or it might mean we just haven't yet identified it completely.

**Pull request merged**
