### PR TITLE
Use metadata for getOptions abbreviation & include currency symbol

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
This refactors the "abbreviation" mode in getOptions to be more consistently metadata-driven, and also adds the currency symbol as an abbreviation to fetch.

Before
----------------------------------------
Implemented with switch statement. Limited to state & country.

After
----------------------------------------
Implemented with metadata in a way that's consistent with the rest of that function.
Includes state, country & currency.

### CODE REVIEW

**Comment by colemanw** [comment]
@agh1 can you please review this as it refactors your code.

**Comment by colemanw** [comment]
I've added test coverage for all 3 fields in question, so this should be a very easy review/merge for anyone, not just @agh1.

**Comment by eileenmcnaughton** [comment]
Makes sense & has good test cover

**Comment by agh1** [comment]
Sorry I couldn't get to it in time, but I really like this approach!

**Pull request merged**
