### PR TITLE
Refer to pledge option group not contribution for pledge status

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Refer to pledge option group not contribution for pledge status

Before
----------------------------------------
For some time pledge & pledge_payment have had their own relevant option groups for statuses but this pledge function is referring to the contribution_status option group

After
----------------------------------------
Switches to apiv4 

Technical Details
----------------------------------------

Comments
----------------------------------------
This causes a fail in https://github.com/civicrm/civicrm-core/pull/23074

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@yashodha you use pledges don't you? Wondering if you could check this one

**Comment by braders** [comment]
I've had a quick look throught the code here and agree the change looks sensible.

**Comment by eileenmcnaughton** [comment]
@monishdeb could you check this

**Comment by eileenmcnaughton** [comment]
I wound up writing almost exactly the same code in another PR today - but it turns out the array cast here https://github.com/civicrm/civicrm-core/pull/23931/files#diff-22fabfe7f9dc81aed350edddfbd061849ac68acf7b2a1f37dad8db2bae364abeR571 is vital for the `count` to work - so closing this & focussing on that one

**Pull request closed without merging**
