### PR TITLE
dev/core#561 Convert pledge search form to use metadata functions

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This doesn't change anything of itself but is a pre-requisite for
- removing jcalendar instances
- supporting params in the url
- supporting appropriate wildcards on text fields (not seemingly relevant on this entity).

In addition it is a driver for cleaning up metadata for our eventual leap away from quickform.

In this case the change highlighted the need to define the html type on the converted field
(pledge_status_id

Before
----------------------------------------
Pledge search form works

After
----------------------------------------
Pledge search form works

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by yashodha** [comment]
@eileenmcnaughton 

Do we have a related ticket for this since we will be having a lot of these - might be easy to keep track.

**Comment by eileenmcnaughton** [comment]
@yashodha yeah probably should - we kinda officially dropped the ticket as a requirement for a PR when we moved to gitlab - but I feel like we are moving back towards requiring them as people get more familiar with gitlab - although we are still a bit rubbish at closing gitlabs once things are resolved...

**Comment by eileenmcnaughton** [comment]
@yashodha I've updated it to reference the jcalendar gitlab. There are multiple things we want to do this consolidation for but that's kinda top of the list

**Comment by yashodha** [comment]
@eileenmcnaughton great, thanks!

**Comment by eileenmcnaughton** [comment]
@yashodha is this good to merge?

**Comment by yashodha** [comment]
@eileenmcnaughton looks good, shall I merge this?

**Comment by eileenmcnaughton** [comment]
@yashodha yep - go ahead

**Comment by yashodha** [comment]
@eileenmcnaughton I am merging this.

**Comment by eileenmcnaughton** [comment]
thanks @yashodha

**Pull request merged**
