### PR TITLE
Follow up fix (master only regression)

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
opps - https://github.com/civicrm/civicrm-core/pull/26844#issuecomment-1636982892

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I'm going to self merge this cos the newly merged regresion will be disruptive

@demeritcowboy

**Comment by demeritcowboy** [comment]
Thanks @eileenmcnaughton

**Comment by demeritcowboy** [comment]
I don't think this was enough. There are still references to $form in preprocess, the errors are just hidden by ajax. e.g. `Warning: Undefined variable $form in CRM_Custom_Form_CustomDataByType->preProcess() (line 60`

**Comment by eileenmcnaughton** [comment]
@demeritcowboy https://github.com/civicrm/civicrm-core/pull/26872 - just doing the write up

**Pull request merged**
