### PR TITLE
CRM-16243 Dependency management for extensions

### PR DESCRIPTION
**Pull request by JohnFF**
Extensions support requires tags, to automatically install extension dependencies.
Contains contributions from myself and @totten at CiviSprint UK 2016.

---

 * [CRM-16243: Dependency management for extensions](https://issues.civicrm.org/jira/browse/CRM-16243)

### CODE REVIEW

**Comment by JohnFF** [comment]
Interesting. Under what conditions?

**Comment by JohnFF** [comment]
@seamuslee001 interesting, under what conditions? Master?

**Comment by seamuslee001** [comment]
@JohnFF John its what Jenkins has reported (click on the red x and see the errors on the 2 extension tests)

**Comment by seanmadsen** [comment]
Before this PR is merged, I'd like to see a PR on the Dev Guide which updates documentation to explain more about `<requires>` and `<ext>`. Our docs currently mention these two elements here: 

* https://docs.civicrm.org/dev/en/latest/extensions/info-xml/#requires
* https://docs.civicrm.org/dev/en/latest/extensions/info-xml/#ext

The docs currently explain that these elements are experimental and don't do anything. If this PR is merged, I'd like for the docs to explain specifically what these elements do and how developers should use them.

**Comment by JohnFF** [comment]
Hold tight, I'll take a second look at it tonight.

It was good to go, but there was a merge commit I - bizarrely - couldn't
quite get rid of. So it was never merged.

**Comment by JohnFF** [comment]
I have a version that appears to work. Tomorrow I will do more testing, run the UTs, and then merge.

**Comment by totten** [comment]
I think this has been replaced by #10899.

**Pull request closed without merging**
