### PR TITLE
Search Kit links improvements

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
This fixes some problems with creating links in Search Kit and improves the UX around editing links.

Before
----------------------------------------
Not possible to link to some entities, e.g. custom contact reference fields.

After
----------------------------------------
Links available for all implicit/explicit joins + custom contact reference fields.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by kurund** [comment]
@colemanw 

Thank you, now we can link the Contact reference custom fields.

**Comment by eileenmcnaughton** [comment]
@kurund does that mean you've tested it?

**Comment by colemanw** [comment]
His comment on GitLab indicated that he did test it.

**Pull request merged**
