### PR TITLE
Removes ~90% of joomla.css - much pre-dates Civi 2.x 

### PR DESCRIPTION
**Pull request by vingle**
Overview
----------------------------------------
CiviCRM used to have to do much more work to integrate into Joomla (which is Bootstrap based) than it does now. Most of the selectors aren't doing anything, or are duplicating css elsewhere in both Civi and Joomla's admin theme.

Before
----------------------------------------
Joomla.css is 445 lines

v3
image
v4
image

After
----------------------------------------
Joomla.css is 40 lines

v3
image
v4
image

Technical Details
----------------------------------------
This rewrite was created by stripping out all css and then adding back that which was visibly required, using ThemeTest to dble check a lot of UI elements. While this Commit has been tested on Joomla 3.x and 4.x it should be tested further by multiple instances before merging given how much is being removed.

Comments
----------------------------------------
As a side effect the change tidies up two css issues - one with modals flowing under the menubar and footer in J3 & J4, and one with external link icons appearing twice in J4.

### CODE REVIEW

**Comment by vingle** [comment]
Having slept on it figured I shouldn't bundle any visual changes into this, no matter how tiny. So have removed that and will update screengrabs above. Goal is there should be no difference between the two version's UI.

While I was at it I removed a type (`margin: 0` appearing twice), fixed the Jenkins issues, and fixed a duplication with Joomla 4 Atum theme showing a second external link icon next to Civi's external link icon, so removed that.

**Comment by eileenmcnaughton** [comment]
@vingle sorry - this has gone stale

@colemanw is there anyone else who should weigh in on this or should we just merge once the rc is cut?

**Comment by vingle** [comment]
@eileenmcnaughton thanks for picking this up. My main worry is impact on front-end pages as that's harder to test against, given the range of front-end setups and themes. Maybe @JoeMurray could also test this on his Joomla sites?

**Comment by eileenmcnaughton** [comment]
@vingle maybe we should merge this next month (so that it's merged after the next ESR is cut)

**Comment by eileenmcnaughton** [comment]
image

**Pull request merged**
