### PR TITLE
Add workflow template for recurring cancelled

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Add workflow template for recurring cancelled

Before
----------------------------------------
No workflow template class

After
----------------------------------------
Tada

Technical Details
----------------------------------------
This is a simple template, with a slightly smaller subset of values than the exisiting one.

It pulls out the recurring part to a trait... I think we want to also create similar traits for Contribuiton messages - which was going to be my next focus.

Comments
----------------------------------------
Test pre-added to CancelSubscriptionTest class testing these values

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@colemanw @seamuslee001 @demeritcowboy any of you OK to merge this? I'd like to add a trait for the contribution ones (already have for participant) & maybe membership so tokens for the base entity are available

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @colemanw @demeritcowboy is this one one of you could look at? It doesn't have the 'has-test' label because I got the tests merged prior to this PR but the change is covered by a unit test.

**Comment by demeritcowboy** [comment]
I've taken a little look it's just an area I rarely deal with. Codewise it looks ok but I'd want to run it which I can try. It looks like this is supporting two templates, for memberships and contributions.

**Comment by seamuslee001** [comment]
I agree with @demeritcowboy on the code structure and we have a decent amount of tests that cover this so I am ok to merge on that basis

**Comment by eileenmcnaughton** [comment]
thanks @seamuslee001 @demeritcowboy - yeah this new code is gonna take us all a bit of getting into

**Pull request merged**
