### PR TITLE
Add custom data when creating smart group

### PR DESCRIPTION
**Pull request by awestuk**
Overview
----------------------------------------
Adds group custom fields when creating a new smart group from search action Group -> Create Smart Group

Before
----------------------------------------
image

After
----------------------------------------
image

Technical Details
----------------------------------------
Mostly just copies https://github.com/civicrm/civicrm-core/pull/21716.

### CODE REVIEW

**Comment by mattwire** [comment]
This seems ok to me. I guess @colemanw may want to take a quick look in case there are any better ways of doing some of this now?

**Comment by seamuslee001** [comment]
Jenkins ok to test

**Comment by yashodha** [comment]
@awestuk You might want to squash your commits. Thanks!

**Comment by aydun** [comment]
Test this please

**Comment by mlutfy** [comment]
I think `CRM_Core_Form_EntityFormTrait` is a way to simplify Entity forms that have custom fields and avoid copy-paste, but since it's a small change and makes it consistent with #21716, I am inclined to merge.

**Comment by colemanw** [comment]
Looks good to me as well

**Pull request merged**
