### PR TITLE
replaceOrgTokens: Remove broken code

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
I'm not sure how far up the chain this breakage goes - but this removes the
clearly broken part & comments further on it

Before
----------------------------------------
Code exists that would fatal if called

image

After
----------------------------------------
poof

Technical Details
----------------------------------------
I'm not sure how far up the chain this breakage goes - but this removes the
clearly broken part & comments further on it

Comments
----------------------------------------
@jmcclelland this code is called from https://github.com/civicrm/civicrm-core/blob/9c1bc317913553a956288e52649f1c372dc7deb0/CRM/SMS/Form/Upload.php#L346 - are you able to confirm whether than function is hit (& it's just the removed part that was seemingly never hit) or whether there is more that can go - since you seem to use the bulk sms flow

### CODE REVIEW

**Comment by jmcclelland** [comment]
This is a real head scratcher. I can confirm that `CRM_Utils_Token::replaceOrgTokens` is being called. In my tests, though, it by-passes most of the code based on this test:

```
if (!self::token_match('org', $token, $str)) {
          continue;
}
```
That tests always results in the `continue` statement being executed becuase non of the tokens I can select start with "org.". I don't know how to get an {org.ANYTHING} token into the SMS unless I type it manually. I'm not sure why you would ever send an SMS to an organization contact, but maybe that's not an assumption we can make.

Also, what about the `$org` parameter? The calling function doesn't seem to set that parameter, which seems like it will cause this function to fail, since it depends on that array containing data.

**Comment by eileenmcnaughton** [comment]
@colemanw you can balance the line add with this line remove if you want :-)

**Comment by eileenmcnaughton** [comment]
Note this is the function that doesn't exist 

image

**Comment by colemanw** [comment]
If it's been broken since 2015, best not think too hard about it.

**Pull request merged**
