### PR TITLE
do not show disabled financial types in select for manage events

### PR DESCRIPTION
**Pull request by kurund**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I took a look at this because what Financial ACLs does is confusing here....

Our demo sites now have a user 'advisor' password 'advisor' who can be used for testing - I added enabled financial acls on the civicrm contribution settings screen & enabled 'access CiviEvent' and 'view event info' to this user's permissions and checked what this user sees when editing the event fee screen

WITH the `administer CiviCRM Financial Types` permission they could specify any financial type on the event config
WITHOUT the `administer CiviCRM Financial Types` permission they could only specify financial types that they have permission to add donations for

So - the `administer CiviCRM Financial Types`  is a kind of override for what financial types they have add rigths for - @JoeMurray is there a logical use case for this is or is it just something lost in time. Obviously looking for any simplifications we can find for financialtypeacls as we try to rationalise them into an extension

**Comment by demeritcowboy** [comment]
Not related to ACLs but for some reason this makes the fee options disappear at the bottom of the Fees tab when editing an event, when the financial type is disabled.

**Comment by darrick** [comment]
If the ACL Financial Type permissions is enabled getAvailableFinancialTypes handles filtering the financial_types based upon the action ("add" in this case).  That function already filters out disabled types.

I think there could be two ways to fix this:

Return all the contact types if the user has the 'administer CiviCRM Financial Types' permission.  I guess just to allow them to enable it via the wrench?  Pray they will be informed it's disabled?


```
if (CRM_Core_Permission::check('administer CiviCRM Financial Types')) {
      $this->addSelect('financial_type_id');
    }
    else {
      CRM_Financial_BAO_FinancialType::getAvailableFinancialTypes($financialTypes, CRM_Core_Action::ADD);
      $this->addSelect('financial_type_id', ['context' => 'search', 'options' => $financialTypes]);
}
```


or just return only the enabled options filtering options only the user has 'add' permission for if "ACL Financial Type" is enabled.

```

      CRM_Financial_BAO_FinancialType::getAvailableFinancialTypes($financialTypes, CRM_Core_Action::ADD);
      $this->addSelect('financial_type_id', ['context' => 'search', 'options' => $financialTypes]);


```

And keep an eye on that wrench.  Might get lost.

**Comment by darrick** [comment]
> I noticed a similar issue to this yesterday - price field options in a contribution price set were showing disabled financial types. That's almost certainly a regression, but from when I couldn't say.

Quick search on my end shows that may be a different issue as the price set field seems to be getting it's types from here: https://github.com/kurund/civicrm-core/blob/8811ad4921150891b206997a7a59fe16a6473e2f/CRM/Financial/BAO/FinancialType.php#L177

**Comment by colemanw** [comment]
retest this please

**Comment by kurund** [comment]
@eileenmcnaughton 

It would be good to merge this. Thoughts!

**Comment by JoeMurray** [comment]
> Not related to ACLs but for some reason this makes the fee options disappear at the bottom of the Fees tab when editing an event, when the financial type is disabled.

The intent is to hide transactions that use Financial Types that are either not permissioned for the user or disabled. 

Disabled could mean many things, including don't allow viewing or changing transactions with that financial type, or, in a twisting of disabled, make them available for everything but new transactions. The latter was not the intent.

**Comment by JoeMurray** [comment]
> I noticed a similar issue to this yesterday - price field options in a contribution price set were showing disabled financial types. That's almost certainly a regression, but from when I couldn't say.

Yes, I see that as a regression. If they could be used for an insert as well as seen in the price field options that would be worse.

**Comment by JoeMurray** [comment]
> If the ACL Financial Type permissions is enabled getAvailableFinancialTypes handles filtering the financial_types based upon the action ("add" in this case). That function already filters out disabled types.
> 
> I think there could be two ways to fix this:
> 
> Return all the contact types if the user has the 'administer CiviCRM Financial Types' permission. I guess just to allow them to enable it via the wrench? Pray they will be informed it's disabled?
> 
> ```
> if (CRM_Core_Permission::check('administer CiviCRM Financial Types')) {
>       $this->addSelect('financial_type_id');
>     }
>     else {
>       CRM_Financial_BAO_FinancialType::getAvailableFinancialTypes($financialTypes, CRM_Core_Action::ADD);
>       $this->addSelect('financial_type_id', ['context' => 'search', 'options' => $financialTypes]);
> }
> ```

I think it is inappropriate to drop the filtering for a person with  'administer CiviCRM Financial Types' permission as they will possibly make mistakes. The only place where the filtering should be removed is on the form to show and possibly re-enable financial types. Jon was referring to price set options.

**Comment by JoeMurray** [comment]
> @eileenmcnaughton
> 
> It would be good to merge this. Thoughts!

+:+1:

**Comment by eileenmcnaughton** [comment]
@JoeMurray @demeritcowboy @MegaphoneJon @darrick my read on the above conversation is that this has been reviewed & agreed, and that the question I raised on testing has been answered. The code hasn't been changes since then so I think that means this is mergeable - but it would be great if someone could confirm

**Pull request merged**
