### PR TITLE
Afform: add checksum support

### PR DESCRIPTION
**Pull request by kurund**

### CODE REVIEW

**Comment by colemanw** [comment]
Thanks @kurund this looks like the right idea. Just need to refine a couple things:

1. The name of the arg you put in here, `"cid"` is not consistent with other url args in Afform (normally it's the name of the entity e.g. `"contact_1"`). Maybe that's ok though since this is a different use-case? Not sure.
2. Afform auto-generates a CiviMail token for each form, so I guess we should include the checksum in that token, or a second token with the checksum? Or maybe you're just supposed to put the checksum token after the Afform token? Either way we should document.

**Comment by kurund** [comment]
> The name of the arg you put in here, "cid" is not consistent with other url args in Afform (normally it's the name of the entity e.g. "contact_1"). Maybe that's ok though since this is a different use-case? Not sure.

I just used `cid` to be consistent with other places where we support checksum. I can rename it to `contact_1`.

> Afform auto-generates a CiviMail token for each form, so I guess we should include the checksum in that token, or a second token with the checksum? Or maybe you're just supposed to put the checksum token after the Afform token? Either way we should document.

Our use case is a bit different. We are using redirecting unsubscribe action to Afform. So I am manually doing redirect and not using CiviMail.  http://localhost/civicrm/myunsubscribe#?cid=123&cs=XXXXX

Where should I document this?

**Comment by colemanw** [comment]
I think insead of a hard-coded string like "contact_1" it needs to use `$entity['name']`

**Comment by kurund** [comment]
> I think insead of a hard-coded string like "contact_1" it needs to use `$entity['name']`

Done

**Comment by colemanw** [comment]
Thanks for your work on this @kurund. I've reviewed more carefully, and found that unfortunately there are some underlying issues that would prevent this from working. Did you try this patch as an anonymous user? I don't think it would work due to the Afform's security policy.
You are validating the checksum but not otherwise escalating permissions so the anonymous user would still not have access to load and save the checksum-contact. What we need is a way to temporarily escalate permissions to those of the checksum-contact.

I anticipated this problem a while ago and tried to make a path forward with #15151 but unfortunately it stalled.

If we get that working, there's one small Admin UX change I would make: I think this shouldn't be under the umbrella of "Auto-Update: Current User" and instead should be under "Accept ID from URL".
image

IMO it makes more sense as an extension of getting the id from the url, rather than an autofill thing.

**Comment by colemanw** [comment]
Looking at @totten's comment at https://github.com/civicrm/civicrm-core/pull/15151#issuecomment-779009601 he sounds optimistic that there is a solution to the problem of escalating afform permissions based on a token, however I'm not sure of the details. @totten does AuthX change the picture of how we'd approach checksum authentication for afforms?

**Comment by totten** [comment]
@kurund @colemanw Yeah, this was the use-case anticipated by [the auto-session authentication flow](https://docs.civicrm.org/dev/en/latest/framework/authx/#flows). An example URL would look like:

```
https://example.com/civicrm/my-form?_authx=Bearer+MY_JSON_WEB_TOKEN&_authxSes=1
```

If `auto`/JWT support is enabled, and if you pass `_authxSes=1`, then authx will setup a session for the visitor. That session will be used by any/all API/AJAX calls. So everything runs as the desired user.

I think it would be good to add [some more tokens](https://github.com/civicrm/civicrm-core/blob/5.48/ext/afform/core/Civi/Afform/Tokens.php#L48) to support these URLs, eg

```php
if (in_array('jwt', Civi::settings()->get('authx_auto_cred'))) {
  $e->tokens['afform']["afform.{$tokenName}LoginUrl"] = E::ts('%1 (URL w/ Login)', [1 => $afform['title'] ?? $afform['name']]);
}
```

A token like this has a couple benefits:

* When a user is composing an email and browsing available tokens, they can discover that authenticated-URLs are available. They don't need to figure out that the exact way to combine URLs and checksums.
* We can change the way the authenticated-link works without updating downstream email templates.

Related:

* [Docs: Authx Credentials: How do you generate a JSON web token?](https://docs.civicrm.org/dev/en/latest/framework/authx/#credentials)
* [Docs: Authx Flows](https://docs.civicrm.org/dev/en/latest/framework/authx/#flows)
* [E2E test for auto-session](https://github.com/civicrm/civicrm-core/blob/5.48/ext/authx/tests/phpunit/Civi/Authx/AllFlowsTest.php#L281)

**Comment by totten** [comment]
Doh, I should've read further -- it wasn't just "anticipated"... it was also [implemented](https://github.com/civicrm/civicrm-core/blob/5.48/ext/afform/core/Civi/Afform/Tokens.php#L75)...

So afform should provide authenticated links if:

* You enable `afform` and `authx` together.
* You configure the form `is_token=true`. (This flag makes sense as a default for any/ public-lead-gen forms -- but not for backend/admin forms.)
* You use the token-picker to make the link. (It should give a token like `{afform.fooBarUrl}` or  `{afform.fooBarLink}`.)

**Comment by colemanw** [comment]
Oh wow I didn't realize the tokens included authentication.
So for autofilling a contact as the token-authenticated user you would set it to "current user"? Does that work even if the contact doesn't have a CMS account?

**Comment by totten** [comment]
>  So for autofilling a contact as the token-authenticated user you would set it to "current user"? 

I think so...

> Does that work even if the contact doesn't have a CMS account?

I expect the CMS account requirement to abide by the setting `authx_auto_user` - which can be one of:

* `require` - If they have a CMS account, authenticate to it. Otherwise, fail.
* `optional` - If they have a CMS account, authenticate to it. Otherwise, proceed with just the Civi contact.
* `ignore` - Do not use CMS account (*even if they have one*). Proceed with just the Civi contact.

For this flow, the current default is `authx_auto_user`=`require`.

**Comment by totten** [comment]
To be transparent... with the auto-login mechanism, I think there are some good things and some issues/limits.

* The mechanism is generic and not tied specifically to Afform or Angular or APIv4 or any of that. It can work with Quickform, APIv3, any AJAX end-point, etc. Improvements to this mechanism can help more pages/use-cases.
* In a CMS-heavy(*) site-architecture, setting `authx_auto_user=require` is better because it means that all the hooks and whatnots work consistently, and the UX can integrate content+links from both Civi+CMS.
* In a CMS-light(*) site-architecture, setting `authx_auto_user=ignore` is better because you don't want to accidentally expose that are only intended for 'logged in user'.
* Of course, it does mean that the user is, ehm, logged-in - so they can access other pages with their same identity. The value of that (good or bad) is quite subjective. But I think perhaps the JWT credential could support some more flags -- eg limit access to specific pages:

    ```php
    $token = Civi::service('crypto.jwt')->encode([
      'exp' => time() + 6*60*60,
      'sub' => 'cid:203',
      'scope' => 'authx',
      'civicrm_routes' => ['civicrm/foo/bar'],
    ]);
    $url = CRM_Utils_System::url('civicrm/foo/bar', '_authxSes=1&_authx=Bearer+' . urlencode($token));
    ```

     I think it's possible to make something like that, but it would deviate from the _typical_ use-cases for CMS session-management, so it would take some finagling (eg *if the user attempts to visit an unintended URL, then show some special prompt*).

----

#### Footnotes

* _"CMS-heavy"_: Sites where _constituents_ have CMS user-accounts. A lot of the constituent UX is built on CMS identities, permissions, hooks, add-ons, etc.
* _"CMS-light"_: Sites where _constituents_ do not have CMS user-accounts. Most of the forms/pages/content come from Civi or from custom code.

**Comment by kurund** [comment]
@colemanw  @totten 

Apologies for the delayed response. I was sick/out whole of last week. Just catching up now.

> I've reviewed more carefully, and found that unfortunately there are some underlying issues that would prevent this from working. Did you try this patch as an anonymous user? I don't think it would work due to the Afform's security policy.

Yes, I have tested with anonymous user and it does work as expected.

`<site-url>/civicrm/communication-preferences#?Individual1=48722&cs=b99b90e77564bd722fcf8f633f3e6bf9_1648482282_1440`

Here are form settings:

afform-settings

For our use case we are not embedding the afform url / token in CiviMail etc.

We are redirecting the CiviMail unsubscribe action to afform where user is provided option to manage their subscriptions.

**Comment by colemanw** [comment]
@kurund from discussions with @totten it looks like Afform will probably never support the old checksums, but the good news is that it already does support the new AuthX JWTs and they will do the same thing you are wanting - authenticate a user to use the form.

**Pull request closed without merging**
