### PR TITLE
Crm 17471 Fix situation where search options not updating for change in membership status

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Comment by seamuslee001** [comment]
@davecivicrm Dave, I shifted tack to go to against 4.6 given this is a bug in both 4.6 and 4.7 makes sense to fix in 4.6 and forward port fix. I am fairly certain this does the trick now.

**Comment by davecivicrm** [comment]
@seamuslee001 I'm not thrilled with making this change in 4.6 as it is not critical, and the change to the core pseudoconstant method MAY impact methods that are expecting to get the name values (have you checked all calls to this method?).

**Comment by seamuslee001** [comment]
@davecivicrm I think given its "broken" in 4.6 its better to get it fixed there. Agree re changing the pseudoConstant so i have switch to changing the call in the buildSearchForm which is much more stable

**Comment by davecivicrm** [comment]
Test failure is unrelated.

**Pull request merged**
