### PR TITLE
Cleanup - Make more calls through Civi::

### PR DESCRIPTION
**Pull request by totten**

### CODE REVIEW

**Comment by colemanw** [comment]
You updating the developer docs wiki too?

**Comment by colemanw** [comment]
jenkins, retest this please

**Comment by colemanw** [comment]
@totten looks like this hung up on a checkstyle error.

**Comment by totten** [comment]
Actually, I think the second commit was also having a problem with some kind of infinite recursion or infinite memory allocation. It was weird - might be able to look at the during the sprint. Otherwise, I'll probably resubmit with only the first commit.

**Comment by eileenmcnaughton** [comment]
Is this dead now?

**Comment by totten** [comment]
Yeah, my feelings won't get hurt if we close it. ;) It's not important enough to justify the time in figuring out the regression.

**Comment by eileenmcnaughton** [comment]
:-)

**Pull request closed without merging**
