### PR TITLE
CRM-15932 - Recurring entity QA fixes

### PR DESCRIPTION
**Pull request by colemanw**
https://issues.civicrm.org/jira/browse/CRM-15932

### CODE REVIEW

**Comment by colemanw** [comment]
Checkstyle warnings are all unrelated to these changes. Looks like we didn't fix style issues in the tools directory but they are still getting checked by the CI.
@totten FYI ^

**Comment by totten** [comment]
@colemanw, thanks. I've updated civilint to ignore tools ( https://github.com/civicrm/civicrm-buildkit/commit/0785d753311e9274a1776ed07f660472485e43b5 ).

**Comment by totten** [comment]
test this please

**Comment by davecivicrm** [comment]
I'm seeing a weird jScript error in some cases - but Coleman isn't. We'll merge this and then try and track that down if we can.

**Pull request merged**
