### PR TITLE
dev/drupal#33 Alter Core setup to allow for consistent drupal impleme…

### PR DESCRIPTION
**Pull request by seamuslee001**
…ntation to previous before userFrameworkFrontend is implemented

Overview
----------------------------------------
This ensures that when drupal implements the concept of the userFrameworkFrontend config property that there is consistent before and after

Before
----------------------------------------
No change

After
----------------------------------------
No Change

ping @eileenmcnaughton @jusfreeman

### CODE REVIEW

**Comment by mattwire** [comment]
@seamuslee001 Not sure I quite understand the reason for this.  It looks like we're adding CMS specific handling for drupal into core files?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I'm not a big fan of extending the is_drupal concept - I think it's better to extend the properties & methods on CRM_Utils_System than to make assumptions about what all drupal variants will do (forever more).

In this case I feel like isFrontend' is probably already true when is_drupal is false - it's just hard to understand the intent of it

**Comment by seamuslee001** [comment]
@eileenmcnaughton isFrontend May not be true if is_drupal is FALSE, i.e. on Joomla Administrator pages is_drupal is false but isFrontend is also false as well

**Comment by eileenmcnaughton** [comment]
@seamuslee001 OK - but you are using is_drupal to mean something functional - what is that something? Because that's the parameter or method name we need IMHO

**Comment by eileenmcnaughton** [comment]
(in general I'm not too sure the purpose of this change)

**Comment by jusfreeman** [comment]
Ping @agileware-fj

**Comment by eileenmcnaughton** [comment]
The work @totten did on theming is discussed here https://github.com/civicrm/civicrm-dev-docs/pull/580 and in the associated PR against civix - I realised getting @totten back on this has been a bit hard due to his other commitments but merging this depends on @totten agreeing it is consistent with the theming approach being adopted - I'm going to assign to @totten & if it stalls on his available I'll close until the theming work he has one is merged

**Comment by eileenmcnaughton** [comment]
Closing this as it's stale & also stalled on another theming PR which Tim says he will get back to this / next? month as he has some mosaico funding & hopes to get it in scope

**Comment by eileenmcnaughton** [comment]
@totten

**Pull request closed without merging**
