### PR TITLE
fixes dev/core#683 Incorrectly encoded state and country names

### PR DESCRIPTION
**Pull request by mfb**
Overview
----------------------------------------
https://issues.civicrm.org/jira/browse/CRM-19261 caused old instances of CiviCRM to add countries and states/provinces with incorrect character encoding.

Before
----------------------------------------
Country = Saint BarthÃ©lemy, province = ViÄ¼akas novads, etc.

After
----------------------------------------
Country = Saint Barthélemy, province = Viļakas novads, etc.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mfb so I guess in the past we've made a point of including the text we are replacing in order to protect from the situation where people have changed it (generally happens in countries with active conflicts & idealogical differences - e.g 'Occupied Territories of Palestine' has bounced a few times. 

But then, I can also see how tedious that could be to do.....

**Comment by mfb** [comment]
If we want to assume that the only error scenario is latin1 encoding, then I could easily update the queries, because I can generate the latin1 bad encoding from the correct one.

I was worried there could be other bad encoding scenarios out there, but maybe not?

**Comment by mfb** [comment]
Ha ok it's not that easy to figure out a formula that works for all the different encoding problems. e.g. `CONVERT(BINARY CONVERT(CONVERT(BINARY 'Viļānu novads' USING latin1) USING utf8) USING latin1)` gives me "ViÃ„Â¼Ã„Ânu novads"  but "ViÃ„Â¼Ã„ï¿½nu novads" is what's in the database.

**Comment by mfb** [comment]
So I think it's easiest to just update these and have release notes to reapply any customizations that were lost?

**Comment by eileenmcnaughton** [comment]
@mfb "If we want to assume that the only error scenario is latin1 encoding, then I could easily update the queries"

Yes - we could probably assume that BUT I think you backed off the 'easily'?

**Comment by mfb** [comment]
Yeah I didn't figure out how to encode from the correct text to what's in the database; I guess because some of the original strings in the mysql.tpl files have the � replacement character in the province name.

Another solution would be to assume everyone has the same encoding problems as my database, and I can use that to generate update queries with the text we're replacing.

**Comment by eileenmcnaughton** [comment]
@mfb let's go with that assumption - I think I feel happier constraining it because this happened a while back so obviously most sites are not hurting over it - safe feels good

**Comment by mlutfy** [comment]
I'm OK with the PR as-is. I looked at some client databases that had customized the list of state/provinces, but it's usually because the use another type of regional unit, and the abbreviations were different, so they would not be impacted by this PR.

I also agree with needing to be sensitive to folks who rename countries/provinces, but I don't think people will have major issues here? (also, I'm sensitive to some extent: it's not something officially supported)

**Comment by eileenmcnaughton** [comment]
@mlutfy I'm happy to defer to you if you feel able to review & merge this!

**Comment by mlutfy** [comment]
I tested the SQL upgrade on a site that was having some of the issues (I never bothered fixing, I would just disable the countries), and it works for me.

I would merge after 24h if there are no objections.

**Comment by seamuslee001** [comment]
Added merge ready based on @mlutfy 's comment

**Pull request merged**
