### PR TITLE
Regression membership creation dev/core#3134

### PR DESCRIPTION
**Pull request by stesi561**
Errors occur when price sets are present but not set

Overview
----------------------------------------

Seems like we need to test for a null value here?

### CODE REVIEW

**Comment by stesi561** [comment]
I don't fully understand the implications of this but this fixes the fatal error - and want to see if this passes tests

**Comment by eileenmcnaughton** [comment]
@stesi561 thanks for this - I was able to replicate based on your steps & I have an altenate fix coming up - rather than handle it loading data (badly) for an unselected line item, only load the selected ones - stand by called

**Comment by eileenmcnaughton** [comment]
@stesi561 can you check alternate fix https://github.com/civicrm/civicrm-core/pull/23027

**Comment by stesi561** [comment]
As you know more about what's going on here and this works - I'll close this in favour of yours! :)

**Pull request closed without merging**
