### PR TITLE
Fix Translation to load related language more reliably

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fix Translation to load related language more reliably

Before
----------------------------------------
When loading translations fallback works within a language family. Ie didn't do any Mexican Spanish translations? it will fall back to Spanish. However, it turns out that if you did SOME translations - ie translated some templates but not others the fallback breaks & it just uses the English

After
----------------------------------------
The templates with a Mexican translation use that, the others fall back to Spanish

Technical Details
----------------------------------------
@totten I captured the bug in a unit test. I also put up a patch that makes it pass. However, this kicks in after all the confusing language negotiation stuff - which I never quite grasped - so I'm not sure this plays nice with that. 

In practice I suspect the release valve of being able to turn off the translation functionality with the 'partial_locales' setting probably makes some of the nuance a bit moot

Comments
----------------------------------------

### CODE REVIEW

**Comment by mattwire** [comment]
So how does this work? Does it rely on you enabling/downloading the related languages?

**Comment by eileenmcnaughton** [comment]
@mattwire - yes if you enable the MessageAdmin extension you can add per-language translations for message templates - and this relates so less common scenario where you have translations for two languages in the same language family (Spanish & Mexican/Latin American Spanish) - it should fall back to the other Spanish variant rather than English if there isn't one for the variant. The happens for normal message template sending

The bug is that it doesn't fall back if you have translations for some but not all the message templates & want it to fall back on only the missing ones

**Comment by mattwire** [comment]
So this will only apply to messagetemplate translations? Or everything?

**Comment by eileenmcnaughton** [comment]
@mattwire potentially anything that implements the translations framework - but at the moment the only implmentation is MessageTemplates with the way to create the translations being in the MessageAdmin extension.

The translations are stored in civicrm_translation which has an entity_id / entity_table structure to describe the field it translates. But just putting a translation in there for another entity might not be enough to make it load - I can't quite recall - I see we need to set translationMode as well in the test example

**Comment by colemanw** [comment]
@mattwire ready to merge this?

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I think this should be mergeable - it has a test....

**Pull request merged**
