### PR TITLE
CRM-21205 use proper currency in batch list

### PR DESCRIPTION
**Pull request by lcdservices**
Overview
----------------------------------------
Retrieve the currencies used by transactions in a batch and prepend to total in the batch list.

Before
----------------------------------------
Currently the batch list prepends the default system currency to the total, regardless of what currencies were used in the batched transactions.

After
----------------------------------------
The currency is retrieved from the transactions and prepended to the total.

Technical Details
----------------------------------------
The currency is retrieved from civicrm_financial_trxn via civicrm_batch_entity.

---

 * [CRM-21205: batch list does not display accurate currency](https://issues.civicrm.org/jira/browse/CRM-21205)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by seamuslee001** [comment]
ping @eileenmcnaughton @pradpnayak @monishdeb does this look right to you?

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
Yep, I'm happy to take @lcdservices word on this - it's a feature that he is the most visible user of & the explanation makes sense. The code change only affects that screen & reads well

**Pull request merged**
