### PR TITLE
Require latest version of pear log

### PR DESCRIPTION
**Pull request by sadashivdalvi**
Overview
----------------------------------------
Current version gives error in drupal watchdog whenever some error is triggered due to something.

Technical Details
----------------------------------------
Deprecated function: Function strftime() is deprecated in Log_file->log() (line 294 of /var/www/html/my_site/vendor/pear/log/Log/file.php)
0 /var/www/html/my_site/core/includes/bootstrap.inc(164): _drupal_error_handler_real()
1 /var/www/html/my_site/vendor/pear/log/Log/file.php(294): _drupal_error_handler()
2 /var/www/html/my_site/vendor/civicrm/civicrm-core/CRM/Core/Error.php(601): Log_file->log()
3 /var/www/html/my_site/vendor/civicrm/civicrm-core/CRM/Core/Error.php(573): CRM_Core_Error::debug_log_message()
4 /var/www/html/my_site/vendor/civicrm/civicrm-core/CRM/Core/Error.php(744): CRM_Core_Error::debug_var()
5 /var/www/html/my_site/vendor/civicrm/civicrm-core/CRM/Core/Error.php(443): CRM_Core_Error::backtrace()
6 /var/www/html/my_site/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php(39): CRM_Core_Error::handleUnhandledException()
7 /var/www/html/my_site/modules/contrib/civicrm/src/Civicrm.php(88): CRM_Core_Invoke::invoke()
8 /var/www/html/my_site/modules/contrib/civicrm/src/Controller/CivicrmController.php(83): Drupal\civicrm\Civicrm->invoke()
9 [internal function]: Drupal\civicrm\Controller\CivicrmController->main()
10 /var/www/html/my_site/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()
11 /var/www/html/my_site/core/lib/Drupal/Core/Render/Renderer.php(627): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
12 /var/www/html/my_site/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext()
13 /var/www/html/my_site/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()
14 /var/www/html/my_site/vendor/symfony/http-kernel/HttpKernel.php(181): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
15 /var/www/html/my_site/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
16 /var/www/html/my_site/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle()
17 /var/www/html/my_site/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle()
18 /var/www/html/my_site/core/lib/Drupal/Core/StackMiddleware/ContentLength.php(28): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
19 /var/www/html/my_site/core/modules/big_pipe/src/StackMiddleware/ContentLength.php(32): Drupal\Core\StackMiddleware\ContentLength->handle()
20 /var/www/html/my_site/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\big_pipe\StackMiddleware\ContentLength->handle()
21 /var/www/html/my_site/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
22 /var/www/html/my_site/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle()
23 /var/www/html/my_site/modules/contrib/cloudflare/src/CloudFlareMiddleware.php(185): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
24 /var/www/html/my_site/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\cloudflare\CloudFlareMiddleware->handle()
25 /var/www/html/my_site/core/lib/Drupal/Core/StackMiddleware/AjaxPageState.php(36): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
26 /var/www/html/my_site/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\AjaxPageState->handle()
27 /var/www/html/my_site/core/lib/Drupal/Core/DrupalKernel.php(704): Drupal\Core\StackMiddleware\StackedHttpKernel->handle()
28 /var/www/html/my_site/index.php(19): Drupal\Core\DrupalKernel->handle()
29 {main}

Comments
----------------------------------------
As per the [1.14.2 release notes](https://github.com/pear/Log/releases/tag/1.14.2) the issue is fixed in this release

### CODE REVIEW

**Comment by colemanw** [comment]
Thanks for this @sadashivdalvi 
@civicrm-builder add to whitelist

**Comment by demeritcowboy** [comment]
@sadashivdalvi How did you install civi - it should have this patch automatically applied: https://github.com/civicrm/civicrm-core/blob/46427960cb57591475061b2a8438b89bcb7ebb2e/composer.json#L277. Is this an old drupal 8 install based on roundearth? Or drupal 8 tarball?

If we did go with a full update anyway, the composer.lock should be updated and we'd need to think about removing the patch.

**Comment by eileenmcnaughton** [comment]
test fail is unrelated - test this please

would be good to update the package & remove the patch

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by sadashivdalvi** [comment]
Hi @demeritcowboy as you pointed and later brought up in comments, I am also removing the patch as that is not required with the newer version

**Comment by eileenmcnaughton** [comment]
@sadashivdalvi can you run composer update on the package & commit the lock file too?

**Comment by sadashivdalvi** [comment]
Hi @eileenmcnaughton 

I committed the composer.lock as you said, note that I used --ignore-platform-reqs for composer update and install as I have 8.2 on my local and platform is set to 7.4.

**Comment by demeritcowboy** [comment]
We need to still support php 7.4 so we can't change that requirement yet.
And we might hit this line: https://github.com/pear/Log/blob/419f8717b85168a51ce22367cc17e49cf8cb289e/Log.php#L831
Also in CRM/Core/Error.php there's a call to setLocale which is defined in our patch - that may or may not be important. Core no longer uses a locale-dependent format, but other uses might.

I guess I'm saying the upgrade might need some testing out first.

Do you know why the patch wasn't applied on your site?

**Comment by sadashivdalvi** [comment]
I have my server on linode and I think I saw it while install that some patch timed out, I think the patch was timed out which is why it was not applied.

Thanks,
Sadashiv

**Comment by demeritcowboy** [comment]
Ah ok.

**Comment by sadashivdalvi** [comment]
What should be the next step here, should I set the php platform to 8.1 as that's what is present on the PR check or should I revert that change and then you will review it?

**Comment by demeritcowboy** [comment]
It needs to stay at 7.4 for another few months. The php minimum can't be changed yet.

**Comment by sadashivdalvi** [comment]
Have reverted to php 7.4 and so the CIviCRM-Core-PR will fail, please review the changes manually

**Comment by demeritcowboy** [comment]
Hi @sadashivdalvi it's because the composer.lock includes updates to everything. Can you do it just updating pear/log? i.e. `composer update pear/log`

**Comment by sadashivdalvi** [comment]
Hi @demeritcowboy 

Did as you asked, only pear/log changes in composer.lock now

**Comment by demeritcowboy** [comment]
Thanks, the fail now I think is that pear/log has defined the requirement as >7.4 instead of >=7.4, so we have a conflict. I think that might be an oversight at their end?

D'oh.

**Comment by sadashivdalvi** [comment]
As I mentioned previously in my comments, we have to use --ignore-platform-reqs for this to work, as we have locked the platform to 7.4, we can wait for few months till we say we go 8.1, our official [requirement page ](https://docs.civicrm.org/installation/en/latest/general/requirements/#php) says 8.1 is compatible and recommended so we ideally should raise the config platform to 8.1.

I leave this call to you.

**Comment by eileenmcnaughton** [comment]
Does the patch apply cleanly on the later psr version? If so I guess we can compromise on 

1) setting the version on the json file to `1.13.3|1.14.`
2) not updating the lock file
3) not removing the patch

if we do that then the tarballs will continue to get the php7.4 version since we are stuck with that & hopefully it installs well for drupal composer installers - the gotcha is that the patch might not apply cleanly  - I'm wondering if you have the  recommended config in place....

`composer config extra.enable-patching true`

per https://docs.civicrm.org/installation/en/latest/drupal/

**Comment by demeritcowboy** [comment]
It's an interesting idea but I'd vote for either updating everybody or waiting for a few months, rather than something that would only update drupal 8, given the original issue sounds like just a network timeout.

I'll do a PR upstream and see what happens.

**Comment by demeritcowboy** [comment]
Ok groovy that was that fast. https://github.com/pear/Log/pull/32. Let's revisit in 24 hrs.

**Comment by eileenmcnaughton** [comment]
jeepers @demeritcowboy  - I think a little piece of my soul just grew back

**Comment by demeritcowboy** [comment]
@sadashivdalvi They've released 1.14.3 so if you can update this then it should build properly and then the only thing we might hit is the trigger_error deprecation linked earlier but we can deal with that.

**Comment by eileenmcnaughton** [comment]
woohoo

**Comment by sadashivdalvi** [comment]
Hi @demeritcowboy 

Have updated the package to 1.14.3

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Comment by demeritcowboy** [comment]
I'm not sure how to troubleshoot this further, and it's slightly complicated by [this issue](https://lab.civicrm.org/infra/ops/-/issues/1017) but I don't think that's the problem here since I can reproduce locally. Although my local stops in a slightly different spot a few log lines up, and I was able to fix it by doing as in https://github.com/civicrm/civicrm-core/pull/29329/files, but that didn't work in jenkins here.

**Comment by eileenmcnaughton** [comment]
Trying to pick this up in https://github.com/civicrm/civicrm-core/pull/30484

**Pull request closed without merging**
