### PR TITLE
Angular - Support popping up an afform or other ang module via ajax modal

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Allows Afforms to work as modal dialogs.

Before
----------------------------------------
Afform as popup not possible

After
----------------------------------------
Now they work.

Technical Details
----------------------------------------
- Fixes the AngularLoader to work with modal dialogs via ajax.
- Dedupes the already-loaded modules to only load what's needed.
- Passes args from the hash part of the url through to the afform (e.g. for pre-loading entities)
- Closes the dialog after submitting the afform (and refreshes search results if the popup originated from a search display)

Comments
-------------------
Also see https://lab.civicrm.org/extensions/certifications/-/issues/5

### CODE REVIEW

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by mlutfy** [comment]
@colemanw I think you have to remove the WIP on the PR?

**Comment by colemanw** [comment]
@mlutfy tests do run on draft PRs. It's passing now.
I'm afraid this won't help with remote forms but it looks very promising for getting Afforms to work as modal popups.

**Comment by aydun** [comment]
(Also noted at https://lab.civicrm.org/extensions/certifications/-/issues/5#note_77861)  

It's getting close in that it loads the form but it does not load the existing content to edit it.  The same link loaded in a new tab does load the content.

**Comment by colemanw** [comment]
@aydun I believe this is fully working now. Ready for review.

**Pull request merged**
