### PR TITLE
[NFC] Remove comment as this has been fixed

### PR DESCRIPTION
**Pull request by eileenmcnaughton**

### CODE REVIEW

**Review by seamuslee001 — APPROVED** [review]

**Comment by eileenmcnaughton** [comment]
The failure is a little worrying but cannot be related to this

**Comment by seamuslee001** [comment]
Jenkins re test this if you wouldn't mind

**Comment by seamuslee001** [comment]
Jenkins re test this please if you wouldn't mind

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
Well it didn't repeat the error @eileenmcnaughton

**Pull request merged**
