### PR TITLE
Composer - Remove non-production code from composer-based installs

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
When installing from `composer` (e.g. Drupal 8-10), non-production files like `tests` and `tools` are present. This can cause confusion because these contain non-production extensions like `phpstorm`.

See https://lab.civicrm.org/dev/core/-/issues/4712

Before
----------------------------------------
Tarball-based installer does not include `tests` & `tools` directories, but composer-based installs does.

After
----------------------------------------
Excluded from both.

Technical Details
----------------------------------------
I had to move the composer scripts out of the tools directory, since we can't delete the directory and also use it!

### CODE REVIEW

**Comment by colemanw** [comment]
@jaapjansma well, I tried, but the tests are pretty unhappy about it.

**Comment by demeritcowboy** [comment]
The composer-y way to do it is put dev stuff in a different package(s)/repo(s) and declare it in the `require-dev` section instead of `require`, but previous attempts to do that have hit some problem in the way jenkins is set up here.

**Comment by jaapjansma** [comment]
@colemanw thanks for your effort so far! I understand it probably requires some tweaking to the test setup, am I right? As the approach is correct but the test suite can not handle the correct approach.

**Comment by colemanw** [comment]
@jaapjansma no I don't think this approach is correct, because these scripts run after `composer install` and that command is used *both* for production sites and also dev sites (and also CI test sites).

**Pull request closed without merging**
