### PR TITLE
CRM-20561 Use composer to provide Auth_SASL

### PR DESCRIPTION
**Pull request by seamuslee001**
* [CRM-20561: Load Net_SMTP, Auth_SASL, Net_Socket via Composer](https://issues.civicrm.org/jira/browse/CRM-20561)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Diff between 4.6 version of Auth_SASL in packages and proposed composer version
https://gist.github.com/seamuslee001/fd5b918285dc864eb113be605ce306c5

**Comment by seamuslee001** [comment]
ping @jackrabbithanna this is what has been merged into master

**Comment by jackrabbithanna** [comment]
Can't afford to have LTS break with TLS 1.0 Deprecation, so erring on the side of updates
merging #10388

**Comment by jackrabbithanna** [comment]
Or maybe not, merging https://github.com/civicrm/civicrm-core/pull/10387
caused conflicts

**Comment by jackrabbithanna** [comment]
@seamuslee001 seems simple to resolve the composer.json conflicts, but what about composer.lock?

**Comment by seamuslee001** [comment]
Closing as no longer needed

**Pull request closed without merging**
