### PR TITLE
[REF] Fix issue where forceing sequential broke webform API chained u…

### PR DESCRIPTION
**Pull request by seamuslee001**
…sage

Overview
----------------------------------------
5.49 backport of https://github.com/civicrm/civicrm-core/pull/23672 

ping @eileenmcnaughton @totten

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This has been confirmed by @KarinG / @demeritcowboy so mop

**Comment by KarinG** [comment]
Our WFC tests are still running too.

**Comment by demeritcowboy** [comment]
I don't know about "confirmed" - I'd agree this is the cause, and that a quick simulation of a similar api call returns the right thing. And it was probably a typo to convert sequential to enforced. Nobody's run it though and as noted the webform tests are still running.

**Comment by eileenmcnaughton** [comment]
Ok- will wait for you to confirm

**Pull request merged**
