### PR TITLE
CRM-20748 Ensure that files that should be removed as part of upgrade…

### PR DESCRIPTION
**Pull request by seamuslee001**
… are

### CODE REVIEW

**Comment by seamuslee001** [comment]
ping @totten i think this may have been what you might have been referring to

**Comment by totten** [comment]
1. Weren't there some other removals -- like `Auth_SASL` and some `*.js` files?
 2. I tend to trust `CRM_Utils_Check` more than post-upgrade messages -- they're a bit more persistent/insistent.

**Comment by seamuslee001** [comment]
Yes but i thought just start with this

**Comment by totten** [comment]
This was updated/resubmitted as#10567.

**Pull request closed without merging**
