### PR TITLE
APIv4 - Add dfk metadata to getfields

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Improves APIv4 metadata about Dynamic foreign keys (DFKs), aka `entity_table` + `entity_id` combos.

Technical Details
----------------------------------------
This has been a long time coming! DFKs have always been quite opaque in our schema. Some improvements to this began [10 years ago(!)](https://github.com/civicrm/civicrm-core/commit/71e5aa5ca52fb158fb91e0636d11b79593ef0929) to make them discoverable at the DAO level, and finally now there's an easy way to get a list of possible join entities from APIv4 getFields. This will make our SK/FB code better by eliminating any hardcoded references to the strings "entity_table" and "entity_id" as the only possible DFK fields we guess exist.

This also fixes some of the random-seeming failures I've seen recently in the APIv4 conformance test, by addressing the entities with bad/missing fk metadata.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I do so love guessing what abbreviation means. If we have to have yet another one can you take a look through the comment blocks & make sure that any that deal with 'diffk' have explainers as to what it means

**Comment by colemanw** [comment]
@eileenmcnaughton yea well the original thing I'm riffing on is called `fk_entity` so I called the new one `dfk_entities` but, yea it could be more self-explanatory I guess. Lemme know if you have a better idea for a name.

**Comment by colemanw** [comment]
@eileenmcnaughton I've just added a `description` to it, so at least there's that.

**Comment by eileenmcnaughton** [comment]
OK & yes, building on something existing makes it a bit more meaningful. We are kind of defining a new concept rather than being too lazy to name something with a meaningful name I guess

**Pull request merged**
