### PR TITLE
Lotsa new features for the Search Kit extension

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
This PR contains a big chunk of work toward Phase II of the Search Kit project.

Highlights
----------------------------------------
- Crud form for managing Saved Searches
- Adds Search Display entity & UI
- Adds first display type: table
- Adds a standalone page for viewing search displays
- Integration with Afform - does the preprocessing needed to embed a Search Display in an Afform
- Code reorganization into 5 Angular modules

### CODE REVIEW

**Comment by seamuslee001** [comment]
@colemanw Jenkins doesn't like your style at the moment https://test.civicrm.org/job/CiviCRM-Core-PR/37716/checkstyleResult/new/

**Comment by colemanw** [comment]
That's just a bug in CodeGen, producing DAO code that Jenkins doesn't like.

**Comment by eileenmcnaughton** [comment]
So I checked with @colemanw & the changes outside search kit are really only affecting search kit. I'm happy to keep search kit moving pretty quickly as it's still beta - it just needs the upgrader & ok to merge IMHO

**Comment by colemanw** [comment]
@eileenmcnaughton your bidding is done

**Comment by eileenmcnaughton** [comment]
OK - let's merge this then - as I mentioned before this is all touching the active-code area that is still in beta

**Pull request merged**
