### PR TITLE
Allow multiple registrations from search actions

### PR DESCRIPTION
**Pull request by larssandergreen**
Overview
----------------------------------------
If `Allow same email and multiple registrations?` is enabled for an event, contacts can be registered for the same event more than once. This is currently possible from the front end and from Register Event Participant and Add Event Registration, but not when using Register participants for event from search actions.

Before
----------------------------------------
When attempting to register a contact for an event, the contact is not registered again and a message pops up to tell you N contacts were already registered.

After
----------------------------------------
Now if `Allow same email and multiple registrations?` is enabled, contacts are registered as usual even if they are already registered for the event.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Yay - this is in the part of the form that is separated out from the parent class - way less scary!

I wonder if  `\Civi\Api4\Event::get()` needs to be ` \Civi\Api4\Event::get(FALSE)`

**Comment by larssandergreen** [comment]
@eileenmcnaughton Presumably you shouldn't have been able to select an event that you don't have permission to access, so couldn't be trying to register people for an event you don't have access to, but I'm happy to add a FALSE if you think it is less likely to cause problems.

**Comment by eileenmcnaughton** [comment]
@larssandergreen just trying to think through the user experience of this - it feels possible people are used to using this action 'safe in the knowledge' the contacts won't be double registered & quietly double registering them might actually be unexpected. Perhaps on validate we should check & then ? something - a check box? a confirm dialog to check its what they meant

Also - when I tried the register form in testing I hit notices / undeclared properties. That, combined with this makes me think we should do something along the lines of

https://github.com/civicrm/civicrm-core/pull/26305

to split out the 2 forms validations

(I haven't given that a spin yet - I suspect this block should be outside the other IFs https://github.com/civicrm/civicrm-core/pull/26305/files#diff-bf1322d204b564c54597cb3cea15d8cd1479303297fab55c9eb6d20eb4e05e9bR175-R177 )

**Comment by eileenmcnaughton** [comment]
Yeah re permissions we can probably get away with the implicit true (famous last words)

**Comment by larssandergreen** [comment]
@eileenmcnaughton Maybe it would be enough to just report to the user something like: `N contacts were already registered for this event, but have been registered again.` Then they'll know for next time, at least. But either way, I feel like this is a fairly rare case (my thought with this, besides just being consistent, was if you wanted to register participants for a bunch of price set options and didn't want to go in and edit every registration, this is how you would do it, even though you end up with double registrations, which may or may not matter). But if you think this is more likely to be a problem than helpful, we can just leave it as is.

**Comment by eileenmcnaughton** [comment]
@larssandergreen I've been meaning to get to doing the next dev-digest so I'll include this in there

**Comment by Stoob** [comment]
If the event has 'multiple registrations' turn on (which is off by default) then the user wants to be able to register folks more than once and it's OK to allow that to happen. But I agree with Lars that the popup notification should be changed.

**Comment by larssandergreen** [comment]
I have added an alert when this happens: "%1 contacts were already registered for this event, but have been added a second time."

**Comment by wmortada** [comment]
This change makes sense to me.

**Comment by eileenmcnaughton** [comment]
Just coming back to this & noting support from @Stoob & @wmortada with the message change - merging

**Pull request merged**
