### PR TITLE
dev/core#975 Fix url for new activity in breadcrumbs

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This fixes a bug in the URL of the new activity link in breadcrumbs, the issue was that an & was replaced with a ,

Before
----------------------------------------
Faulty URL generated

After
----------------------------------------
Proper URL generated

ping @jusfreeman @eileenmcnaughton 

https://lab.civicrm.org/dev/core/issues/975

### CODE REVIEW

**Comment by colemanw** [comment]
@seamuslee001 when I grep for `<path_arguments>` in the codebase, I don't see any ampersands but I do see other examples of commas.

**Comment by mlutfy** [comment]
@seamuslee001 How can we reproduce the issue?

**Comment by seamuslee001** [comment]
sorry @mlutfy @colemanw its about new activity not new case sorry my fault). To reproduce go to search -> find activities Do a basic search, then see in the breadcrumbs new activity, note that the url has a , when it should have an & in the URL

**Comment by eileenmcnaughton** [comment]
@seamuslee001 this was actually a recent (regressive it seems) change made by you - see https://github.com/civicrm/civicrm-core/pull/13654 - so we should a) target the rc & b) figure out what the right fix is

**Comment by eileenmcnaughton** [comment]
@seamuslee001 ok - lets' switch this to the rc & merge per convo in chat

**Comment by seamuslee001** [comment]
@eileenmcnaughton done

**Pull request merged**
