### PR TITLE
Search kit grand totals

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds a row to table displays for grand totals, averages, counts and other statistics.
The aggregation method used can be configured per-column.

To Use
--------------
1. Create a table display
2. Click on "Show Totals In Footer"
3. For each column you can now select an aggregation function and optional label.
4. The result:

image

### CODE REVIEW

**Comment by petednz** [comment]
nitpicking - is 'tally' a commonly enough used term among folk for whom english is not a first language?

**Comment by colemanw** [comment]
@petednz perhaps "Summary" is better?

**Comment by mattwire** [comment]
"Show total in footer".  "Aggregate label" / "Aggregate value"  seems more intuitive.

**Comment by colemanw** [comment]
I've made those changes.

**Comment by eileenmcnaughton** [comment]
@colemanw  I just tested this - but this looks a bit odd & not per your pic

image
```
[
  [
    "SavedSearch",
    "save",
    {
      "records": [
        {
          "name": "by_type",
          "label": "by type",
          "form_values": null,
          "search_custom_id": null,
          "api_entity": "Contact",
          "api_params": {
            "version": 4,
            "select": [
              "contact_type:label",
              "COUNT(id) AS COUNT_id"
            ],
            "orderBy": [],
            "where": [],
            "groupBy": [
              "contact_type"
            ],
            "join": [],
            "having": []
          },
          "expires_date": null,
          "description": null,
          "mapping_id": null
        }
      ],
      "match": [
        "name"
      ]
    }
  ],
  [
    "SearchDisplay",
    "save",
    {
      "records": [
        {
          "name": "by_type_Table_1",
          "label": "by type Table 1",
          "saved_search_id.name": "by_type",
          "type": "table",
          "settings": {
            "actions": true,
            "limit": 50,
            "classes": [
              "table",
              "table-striped"
            ],
            "pager": [],
            "sort": [
              [
                "sort_name",
                "ASC"
              ]
            ],
            "columns": [
              {
                "type": "field",
                "key": "contact_type:label",
                "dataType": "String",
                "label": "Contact Type",
                "sortable": true,
                "tally": {
                  "fn": "GROUP_CONCAT"
                }
              },
              {
                "type": "field",
                "key": "COUNT_id",
                "dataType": "Integer",
                "label": "(Count) Contact ID",
                "sortable": true,
                "tally": {
                  "fn": "GROUP_CONCAT"
                }
              }
            ],
            "tally": {
              "label": "Total"
            }
          },
          "acl_bypass": false
        }
      ],
      "match": [
        "name",
        "saved_search_id"
      ]
    }
  ]
]
```

**Comment by eileenmcnaughton** [comment]
Also - I then updated the search page to SUM rather than COUNT & saved it & when previewing the display it had js errors - presumably because the change hadn't fully flowed through

**Comment by colemanw** [comment]
@eileenmcnaughton it looks to be behaving the way you configured it. You've got the aggregation set to "GROUP CONCAT":

```
"tally": {
                  "fn": "GROUP_CONCAT"
                }
```

**Comment by eileenmcnaughton** [comment]
Ah - that's what it defaulted to - I didn't realise I needed to configure that - probably the defaults could be cleverer?

image

**Comment by colemanw** [comment]
Yes, they were supposed to be cleverer than that. I'm looking into it.

**Comment by eileenmcnaughton** [comment]
OK - I'm going to merge this in the meantime

**Comment by colemanw** [comment]
Ok, in the meantime, here's the fix :) #23573

**Pull request merged**
