### PR TITLE
Wording changes in the Unsubscribe form

### PR DESCRIPTION
**Pull request by philmb**
Change unsubscribe form wording and feedback to reflect that the **Contact** is being unsubscribed, not just a single email address.

See https://lab.civicrm.org/dev/core/-/issues/3174

Overview
----------------------------------------
The Unsubscribe form refers to removing an email address from a Mailing List, when in reality the Contact is removed from the mailing list for all email addresses they may have. For example, if a Contact is subscribed to bulk mail at both Home and Work email addresses and then changes jobs, the inheritor of the Work email account is likely to click the Unsubscribe link, causing the Contact to be unsubscribed at both email addresses. The ideal action is Opt Out, but this is not clear in the language used on the Unsubscribe form, and the general public cannot be expected to parse the distinction between Unsubscribe and Opt Out.

Before
----------------------------------------
An inheritor of a Work email account clicks on an unsubscribe link and the Unsubscribe form says "You are requesting to unsubscribe this email address: **\[email address\]**" suggesting that only that one address -- not the Contact -- is going to be unsubscribed.

After
----------------------------------------
Barring changes to how Mailing Lists/Groups function in the back-end, wording changes to the Unsubscribe form could help clarify for front-end, public users what result their action will take, preventing inadvertent unsubscribes. Such as "You are requesting to unsubscribe **all email addresses for {$display_name}** from the above mailing list", add a link to the Opt Out form, and other language changes.

### CODE REVIEW

**Comment by colemanw** [comment]
@civicrm-builder add to whitelist
@philmb welcome to the inner circle of CiviCRM developers :smile:

**Comment by jmcclelland** [comment]
> > add a link to the Opt Out form
> 
> Is there consensus on doing this? I know that I have many clients that would be opposed to having an opt-out option on the unsubscribe form.

I think a very small percentage of our groups might complain and not want to show the opt out of everything link on the unsubscribe page. 

However, I think that's a losing battle and I would happily tell them it's simply not possible. This proposed approach - just *one* link to include in the email where the subscriber has the option to unsubscribe from the group or opt out of everything - seems to be the general trend for most email lists.

We spend countless support hours trying to explain the difference between the "unsubscribe" link and the "opt out" link and why you might want one or another. 99% of our groups just want a simple answer and they don't want to get angry email messages from their subscribers who say they unsubscribed yet are still getting email. 

Including the Opt Out option on the unsubscribe page elegantly solves all that mess, so I'm a big fan of this aspect of the change.

**Comment by kcristiano** [comment]
@jmcclelland Do you have any data to support the small percentage of our groups?  

I am very opposed to us adding this without a choice for the user.    This should be an option not enabled by default.  Why?   The Orgs I deal have all had me remove opt-out.  I cannot think of a single org that I work with that has opt-out enabled.  

Therefore, I think that what the Orgs want will be vastly different based on who they are and they'll never read a discussion like this.

**Comment by jmcclelland** [comment]
By "our" groups I meant Powerbase groups, not the full spectrum of CiviCRM users. I don't have any data - just going based on typical conversations I have with them about the differences between opt out and unsubscribe. 

For the record, I'm not opposed to making this configurable so sites can choose whether or not the opt out link appears, just saying I'm ok without that option.

**Comment by kcristiano** [comment]
I understand that a configurable option beyond the scope here.   That said, I think deciding for our organizations what we should add to the unsubscribe page is also out of scope.   If we decide it's best practice that opt-out is on the unsubscribe page, then a client is forced to use a template override to remove.   I just don't see this as something we should be doing.

**Comment by philmb** [comment]
Given the lack of consensus about Opt Out, I've removed that line from the template in this commit. I'd rather move forward with the language changes than wait until a full opt-out discussion is determined. I'm totally in favor of @artfulrobot 's suggestion of a robust Communications Preferences page. That is a much better long-term solution.

**Comment by jaapjansma** [comment]
test this please

**Comment by philmb** [comment]
@jaapjansma I'm not sure if you are asking me (who opened the PR) to test, or if "test this please" is a general request. I have tested on my installation, but I don't have the capacity for further testing.

**Comment by jaapjansma** [comment]
@philmb the `test this please` is a command for running automated tests on the CiviCRM community test infrastructure. I added that sentence so I could review and test your PR together with @bettydolfing. But I see that the test is still running.

**Comment by jaapjansma** [comment]
@bettydolfing and I have tested and reviewed this PR we are also struggling whether this is the right solution. 

We are agreeing with @artfulrobot that a communication preference page makes more sense. We do this quite often for our clients because CiviCRM is behind a firewall and the unsubsribe and opt out page is not available for the public. (See for how do this here: https://docs.crm-showcases.org/docs-category/newsletter_subscriptions/ and here for how we did this on our own website: https://www.civicoop.org/en/your-data-were-saved/)

The difficulty is that there are many scenarios such as:

A).  One contact Jaap Jansma has two e-mail addresses (work and private)
B). Jaap Jansma exists multiple times in the database as a contact with the same e-mail address (and each contact is a member of the mailing group)
C). A contact could have multiple bulk mail address (you can enable this at CiviMail Component settings)

This patch and wording change only make sense for scenario A. However it shows the full display name this could be a data breach according to GDPR (not sure if it is depends on the end user organization whether it is). Previously I liked it showed my e-mail address hidden (with asteriks: ja***@civicoop.org) but still recognizable. 

So we doubt whether the proposed wording change is the right change. So our proposal would be to develop a new public update your preference page as a replacement for ubsubscribe and opt out.

**Comment by jaapjansma** [comment]
@artfulrobot I agree with you that it does not belong to this PR and that is quite a project to take on to create communication preference page. And I have no time for that either.

**Comment by philmb** [comment]
To see if we can wrap up this PR, I added some lines to mask the display name per @jaapjansma 's concerns. Now displays as first two letters of each segment of a name, e.g. "Ph***** Mo***** Br*****" Open to comments about any better ways to do that.

**Comment by BettyDolfing** [comment]
Test this please

**Comment by jaapjansma** [comment]
> To see if we can wrap up this PR, I added some lines to mask the display name per @jaapjansma 's concerns. Now displays as first two letters of each segment of a name, e.g. "Ph***** Mo***** Br*****" Open to comments about any better ways to do that.

That is one of the concerns we (@BettyDolfing and I) had. Another concern is that the wording does not make sense as soon as on end user organisation enabled multiple bulk e-mail addresses. At that point the wording is misleading so we are not sure whether this PR is an improvement or not.

**Comment by jaapjansma** [comment]
@philmb did you test with multiple e-mails and all checked for bulk mail? Are all e-mail addresses from this contact unsubscribed? Or only one?

**Comment by philmb** [comment]
@jaapjansma Yes, yes, yes. Here's my test:

1. Create Mailing List group "Test" that includes only myself.
2. In my contact profile, have 2 different email addresses both with "Bulk Mail" checked
3. Create a bulk mailing, send it to the "Test" group.
4. Both email accounts receive the mailing as expected.
5. Click the Unsubscribe link in one of the email accounts and follow through to unsubscribe.
6. An unsubscribe confirmation email is received only in the account from which I clicked the link.
7. My Civi contact profile is removed from the "Test" group. Both email addresses still have the "Bulk Mail" checked.
8. When creating a second mailing to send to the "Test" group, the mailing form indicates that there are "No recipients".
9. I send the second mailing, and neither email account receives it.

This is an accurate description of the behavior/result which I think I have accurately accounted for in the language changes proposed. If you expect a different result, please check for yourself. I don't know what more I can say.

**Comment by jaapjansma** [comment]
@philmb thanks a lot for the description of your testing I might then be mistaken as we could not test this properly as the email functionality is turned off in dmaster and in the test environment belonging to this PR. Otherwise we would have taken time to test this more carefully.

**Comment by kcristiano** [comment]
@philmb 

What I see on unsubscribe after the path is:

image

Unsubscribing works as expected.

I also added an opt-out link and this reads:

image


I dod believe the PR accomplishes what it set out to do.   Wording is rough - do we have consensus that the wording makes sense?

**Comment by philmb** [comment]
@kcristiano , yes, that is what I expect from the latest version. (Without the opt-out link, as discussed above.)

**Comment by eileenmcnaughton** [comment]
I just read through this PR & my take on it is

1) the feedback by @jaapjansma has been addressed through a combination of masking and clarification about the actual behaviour
2) the screenshot at https://github.com/civicrm/civicrm-core/pull/23187#issuecomment-1144198503 is the current behaviour
3) the controversial opt out link has been removed BUT the code to assign it to the template remains 
4) the PR needs rebasing

My analysis is that this would be mergeable if

1) it is rebased
2) the code is fixed so that either [the code assigning the opt-out url to the template](re are some housekeeping items in ) is removed or adequate code comments are added to explain why it should remain there.

@colemanw @seamuslee001 @demeritcowboy @totten / people already commenting on this PR - this has dragged on a bit - would appreciate if any of you feel able to parse the feedback in here & confirm if you think my take is right

**Comment by demeritcowboy** [comment]
I agree with @eileenmcnaughton 's analysis.

**Comment by philmb** [comment]
The code has been rebased and cleaned up as per recent comments by @eileenmcnaughton and @demeritcowboy 
I'm now working for an organization that doesn't use Civi :-( so I'm not in a position to test the latest commit properly.

**Comment by eileenmcnaughton** [comment]
Thanks for the work and good luck in your new job @philmb 

I've moved the changes to #27022  as the rebase hadn't quite worked

**Pull request closed without merging**
