### PR TITLE
dev/core#707 Refactor Batch transaction list code to support hook

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/issues/707

Before
----------------------------------------
Limited to few search field to be used as filter on the batch financial transaction list search form.

After
----------------------------------------
All fields can be used as filter on the batch financial transaction list search form.

Technical Details
----------------------------------------
This PR uses core functions CRM_Contact_BAO_Query to generate query for contribution and also has few optimization.

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
Test failures appear related?

**Comment by eileenmcnaughton** [comment]
If we are going to clean this up I think we should switch to using the api - it would simplify a few things IMHO

**Comment by pradpnayak** [comment]
@MegaphoneJon @monishdeb @lcdservices would like to review this?

**Comment by eileenmcnaughton** [comment]
@pradpnayak is it not possible to use the api instead of the Query object on this page? We have hit a lot of problems because of the way this page interacts over time - I'd love to see it NOT use what we should probably think of as a deprecated approach

**Comment by MegaphoneJon** [comment]
@pradpnayak I was able to test this today by rebasing against 5.13 - there's a bug for me in `master` that prevents me testing this.

It seemed to fix the problem of not being able to search on custom fields - but I believe pagination is broken when this patch is applied.  Only 1 page is listed no matter how many results.

**Comment by eileenmcnaughton** [comment]
@pradpnayak I'm closing this because it's stale - please open a new PR when you are ready. I remain concerned about putting this through the 'search' code rather than the api & in fact I suspect building out a new screen would be less work that de-crazy-ing the existing one

**Pull request closed without merging**
