### PR TITLE
Unit test for CRM-21436

### PR DESCRIPTION
**Pull request by jitendrapurohit**
unit test for https://github.com/civicrm/civicrm-core/pull/11317

---

 * [CRM-21436: Fatal error on contribution page with only pay later enabled.](https://issues.civicrm.org/jira/browse/CRM-21436)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@jitendrapurohit doing some more review on this I believe there is an id set in `$_REQUEST` which is what is throwing things off

**Comment by jitendrapurohit** [comment]
Yes @seamuslee001 I've updated by setting the page id to $_REQUEST and executed AllTest which seems to be executing fine now. 👍

**Comment by seamuslee001** [comment]
Looks good (should we remove the WIP now @jitendrapurohit ?) also ping @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
A test that passes is a mergeable test IMHO. Thanks for the follow through @jitendrapurohit

**Pull request merged**
