### PR TITLE
Test for event#43

### PR DESCRIPTION
**Pull request by MegaphoneJon**
Overview
----------------------------------------
This is a test for #18758.

Comments
----------------------------------------
This is expected to fail before #18758 is merged.  @mlutfy it's up to you whether you want to add this to your own PR or just merge in order.

### CODE REVIEW

**Comment by seamuslee001** [comment]
@MegaphoneJon style issues

**Comment by seamuslee001** [comment]
One of the test fails expected (5.31) now merged re-running

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by mlutfy** [comment]
Thanks @MegaphoneJon ! 

Looks good to me, but will let someone else merge.

**Pull request merged**
