### PR TITLE
CRM-18836 -Update Address.tpl

### PR DESCRIPTION
**Pull request by stevekessler**
Corrected URL for USPS in 4.7 (master).

---
- [CRM-18836: Update Address.tpl for correct url](https://issues.civicrm.org/jira/browse/CRM-18836)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Steve can you log a JIRA for this? (& also edit the CRM-xxxx into the PR title). Thanks

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
(NB I know it's kinda trivial & self-explanatory as a patch but we should still track through JIRA)

**Comment by stevekessler** [comment]
No problem, I will put in JIRA. I was trying to be quick about it when I
found the issue.

On Monday, June 13, 2016, Eileen McNaughton <notifications@github.com>
wrote:

> (NB I know it's kinda trivial & self-explanatory as a patch but we should
> still track through JIRA)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/8554#issuecomment-225777726>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA0-kXy544qB8aJGHYUUSjT0Td71CVCcks5qLi9VgaJpZM4I0uj1>
> .
>


-- 
Steve Kessler
Owner and Lead Consultant
Denver DataMan, LLC
303-587-4428

**Pull request merged**
