### PR TITLE
CRM-18573 -Don't force payment for backoffice pending contribution

### PR DESCRIPTION
**Pull request by pradpnayak**
- [CRM-18573: Don't force payment for backoffice pending contribution](https://issues.civicrm.org/jira/browse/CRM-18573)

### CODE REVIEW

**Comment by pradpnayak** [comment]
in favour of https://github.com/civicrm/civicrm-core/pull/8469

**Comment by JoeMurray** [comment]
@colemanw this is part of the project for accrual accounting - could you work on reviewing, testing and eventually merging this.

@lcdservices could you work on testing this PR?

**Comment by JoeMurray** [comment]
Please close as won't fix.

**Comment by colemanw** [comment]
@JoeMurray those 2 comments seem contradictory. Did you mean them both for the same PR?

**Comment by JoeMurray** [comment]
I've pushed the issue back to @lcdservices for clarification as I couldn't reconcile feedback on issue queue. Sorry for the contradictory messaging. We'll get back to you on this.

**Comment by lcdservices** [comment]
@JoeMurray I replied on the Jira issue. Just wanted to make sure you saw it.

**Comment by JoeMurray** [comment]
Noted. I'm thinking my way through and will need to play on test sites some more before responding.

**Comment by eileenmcnaughton** [comment]
I'm closing this out for now as it is stale & the conversation indicates it's not clear if it should go ahead. I'll make sure it's linked from JIRA. Please re-open as appropriate

**Pull request closed without merging**
