### PR TITLE
Crm 15728 fix

### PR DESCRIPTION
**Pull request by monishdeb**

### CODE REVIEW

**Comment by colemanw** [comment]
It seems like there's a "false merge" commit in this PR.

**Comment by monishdeb** [comment]
@colemanw  I pulled the changes of my other branch named CRM-15728 as it gone stale and merged on updated new master branch  CRM-15728-fix. That merge commit was a result of it. Do I need to rebase at this point as it gone stale again ? or ...

**Comment by colemanw** [comment]
I don't know, you guys at WebAccess seem to prefer a different git workflow than me. Not sure which is better or worse, but I notice you all tend to switch PRs and switch branches a lot which would make my head spin if I did things that way (e.g. I see a lot of PRs that say "closed in favor of ..." where the new PR seems to contain exactly the same changes as the old one).

FWIW this is my typical workflow:

- Make some commits on a branch and create a PR.
- If I need to add a new commit I just push it to the same branch and it gets added to the PR.
- If I need to rebase my commits, I do so and then do `get push -f` which keeps the same PR open with the modified set of commits.
- If the PR gets stale I do `get pull civicrm master --rebase`, fix conflicts when prompted to do so, and then again `get push -f` which simply refreshes the stale PR without having to close it or merge into a different branch.

At this point I think you could still do that with your current branch and it ought to refresh it.

**Comment by monishdeb** [comment]
Thanks for your input coleman :) Yes I did that on my PR changes for api cleanup task but rebase always start at initial commit and   resolve the conflict if any, to the final commit. Things got pretty tedious when a PR got lots of commit with growing number conflicts. As on the otherhand with this switchbranch-merge approach all the conflicts arise in one final merge, so all happen in one go that's why I preferred later approach. Anways I guess the rebase approach is much safer then merge.

**Comment by davecivicrm** [comment]
Tested this using manual merge to master branch. Generally working as expected. Two potential exceptions reported in Jira:
https://issues.civicrm.org/jira/browse/CRM-15728?focusedCommentId=69708&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-69708

**Comment by davecivicrm** [comment]
Monish will be making one additional change in the BAO to preserve the reference_date in prior action_log entries. However, the current functionality is working as expected, so will merge this set.

**Pull request merged**
