### PR TITLE
CRM-18751 - Add method for setting payment processor return URL

### PR DESCRIPTION
**Pull request by colemanw**
https://issues.civicrm.org/jira/browse/CRM-18751
Also see
https://github.com/ixiam/com.ixiam.payment.redsys/pull/9
https://github.com/colemanw/webform_civicrm/pull/42

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
From a code point of view this looks good. My only worry is changing some classes from protected to public might cause problems for the extensions. However, I would be moderately sure only Omnipay overrides this & I guess there must be someway for me to deal with that.

**Comment by colemanw** [comment]
@eileenmcnaughton seems like instead of overriding these functions, extensions can now just set the new variables and they will be respected by the functions in place.

**Comment by colemanw** [comment]
@eileenmcnaughton my first time trying the `ReflectionUtils` trick to access private methods. Works!

**Comment by eileenmcnaughton** [comment]
Coleman has addressed my concerns now. This looks very safe - only adding additional (tested) functions

**Pull request merged**
