### PR TITLE
Batch Update via Profile does not supply data for editing when custom fields created after participant added to event

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/1946

Before
----------------------------------------
Screen Shot 2020-08-22 at 14 58 48

After
----------------------------------------
Screen Shot 2020-08-22 at 14 55 54

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This is very from-layer. If someone does an r-run on this I'm happy to merge

**Comment by marsh-circle** [comment]
works perfectly - thanks @pradpnayak

**Comment by seamuslee001** [comment]
Merging as per review from @marsh-circle

**Comment by marsh-circle** [comment]
Thanks @seamuslee001 :D

**Pull request merged**
