### PR TITLE
Fix WordPress support for Get UF Locale

### PR DESCRIPTION
**Pull request by christianwach**
Overview
----------------------------------------
This PR completes #16289 and solves [the issue on Lab](https://lab.civicrm.org/dev/core/issues/1635). In essence, CiviCRM only displays in the default CiviCRM language, whether on the front-end or in WordPress admin.

Before
----------------------------------------
When "Inherit language" is selected, CiviCRM only displays in the default language set in CiviCRM, whether on the front-end or in WordPress admin.

After
----------------------------------------
When "Inherit language" is selected, the logic that CiviCRM now follows is that:

* CiviCRM's admin screens are displayed in the language that the WordPress User has chosen on their Profile screen, since this is what the rest of the WordPress admin displays to them. If they inherit their language from WordPress, then that is used.
* CiviCRM's front-end forms default to the language that WordPress is set to.
* CiviCRM's front-end forms respect the language that multilingual plugins report.

### CODE REVIEW

**Comment by mattwire** [comment]
I've got this on my site now for testing - so far so good!  @christianwach it's failing on 10 style warnings - can you fix?

**Comment by christianwach** [comment]
> it's failing on 10 style warnings

@mattwire Have force pushed fixes -- let's see how the checks pan out.

**Comment by jaapjansma** [comment]
test this please

**Comment by christianwach** [comment]
Anyone have any ideas why the checks are failing? I see nothing amiss when I look at the details.

**Comment by kcristiano** [comment]
jenkins test this please

**Comment by kcristiano** [comment]
I restarted the test as I know there have been some oddities lately.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by kcristiano** [comment]
* ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))Pass 
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))Pass
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) Pass
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) Pass this allows ML to work as documented
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) Pass
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) Pass
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) Pass
* ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) Pass


This looks merge-ready to me

**Comment by mattwire** [comment]
Thanks @kcristiano @christianwach

**Pull request merged**
