### PR TITLE
Update api.php to fix return array to json string.

### PR DESCRIPTION
**Pull request by sujit-baniya**
Please check the issue fixed

### CODE REVIEW

**Comment by totten** [comment]
jenkins, ok to test

**Comment by totten** [comment]
@itsursujit  -- first, a tip: if you include the issue code (like `CRM-19297`) in the subject line for the PR, then a bot will recognize it automatically. It will create hyperlinks between JIRA and Github (which makes it easier to read).

Second, on the code: although I'm not familiar with the problem, this code looks a bit suspicious to me. This has to do with how things are layered in Civi API:
 * Generally, `civicrm_api3()` (and its synonyms like `civicrm_api()` or `Civi\API\Kernel::run()`) should produce data in a canonical PHP format. (If something seems like an array, then it should be returned as  PHP `array()`. If it looks like a string, it should be returned as PHP string.)
 * Generally, if one needs to output a different format (e.g. JSON or XML or shell), then that's handled at higher level (e.g. `CRM_Utils_REST` or `drush_civicrm_api()`). Ideally, you can convert the entire $result with one simple call (e.g. `json_encode(civicrm_api3(...))` or `serialize(civicrm_api3(...))` or `YAML::encode(civicrm_api3(...))`)
 * This patch seems to be converting output to JSON in the wrong place. For example, if you were writing some server-side code which calls `civicrm_api3()`, you would expect the result to be an array, but this change will return JSON instead. Or if you were outputting XML, then you'd need special rules to decode the JSON bits and then encode the overall result.

**Comment by colemanw** [comment]
Closing for lack of response.

**Comment by colemanw** [comment]
Fixed by #8981

**Pull request closed without merging**
