### PR TITLE
Set default financial_type_id for creating new payment processors (form & api)

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
When adding a payment processor financial_account_id is a required field. This adds a sensible default for this value 'Payment Processor Account'

Before
----------------------------------------
Api allows payment processors to be created without this required field being filled in.

When creating new processors you need to select the field in the UI
screenshot 2018-11-30 13 58 05

After
----------------------------------------
Api will use the default account if none is specified in the api call. If it cannot be loaded (e.g because the account doesn't exist or has been renamed) a mandatory required error will result

screenshot 2018-11-30 13 58 18

Technical Details
----------------------------------------

Comments
----------------------------------------
@monishdeb @mattwire what's the bet this has been annoying you guys forever but like me haven't wanted to spend the time on fixing it (until now :-)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by pradpnayak** [comment]
Hi @eileenmcnaughton 

Thanks for fixing this. Only one concern I have is why we are not using civicrm_financial_account.is_default = true for Financial account type = Asset? I also agree with your fix since the 'Payment Processor Account' does make sense for Payment processors for default install. However one is allowed to rename the financial account from UI and the civicrm_financial_account table doesn't have machine name and label columns where we can make 'Payment Processor Account' always as default. Thoughts?

@JoeMurray @monishdeb

**Comment by eileenmcnaughton** [comment]
@pradpnayak I understand your comment as things that would be good follow ons rather than blockers?

**Comment by pradpnayak** [comment]
@eileenmcnaughton  Yes, This is NOT a blocker and good to merge. But would like @JoeMurray to provide some input on this.

**Comment by monishdeb** [comment]
@pradpnayak has raised a valid point and its not a blocker but then I was thinking if someone already has changed this specific FA name. And after this patch is applied to Civi, I think the paymentProcessor API will fail due to the required parameter. 

Alternatively I was thinking to use the ```is_reserved``` property of FA as result of which one cannot edit/delete that particular FA, as in here I have set the FA.is_reserved = TRUE for PP account:
screencast-12189-role

I think the fix would be to make such FAs which are used in other places - reserved (also disable inline-edit from UI), but that should be in a separate PR with install and upgrade code.

**Comment by eileenmcnaughton** [comment]
@monishdeb I think we should add a label column to the Financial Account table 

I agree this means that IF you have renamed the Payment Processor Account and you try to create a processor by the api it will fail now - but I think that is more correct than creating a processor with no financial account which seems kinda dangerous

**Comment by eileenmcnaughton** [comment]
(I'd also note that creating payment processor instances by api is not a common operation)

**Comment by seamuslee001** [comment]
@eileenmcnaughton @monishdeb that thing with label looks like it might be related to https://lab.civicrm.org/dev/core/issues/566

**Comment by eileenmcnaughton** [comment]
@seamuslee001 yes - but I think we should merge this as that is tangental. We should ideally add a localisable label field to the table & migrate all the form-level places to use label

**Comment by monishdeb** [comment]
Overall, only constraint we felt here about this patch is, what if ```Payment Processor Account``` name is changed as it is editable from UI end, this will compel dev to retain the original name to go through the validation checks for PaymentProcessor.create API. But then if we look on the codebase we already have this risk on all other places where FA id is fetched on basis of name which is supposed to be a m/c name not label. I agree with @eileenmcnaughton that this needs be handled in a separate ticket-PR. 

I will still wait for others to provide their feedback till tomorrow. For now I am marking it with 'merge-ready' as I tested on local and it is working fine. Modified UT ensures the validation check.

**Comment by eileenmcnaughton** [comment]
@monishdeb right - I think it's more of a problem that we let people create invalid processors than that we might deny them the chance to create an invalid processor

**Comment by JoeMurray** [comment]
@monishdeb there is not a clear comment from anyone else directing this to be merged, so it was not appropriate for you to merge it as you were the one who created the PR and marked it as merge ready. Merely not having an objection in a certain period of time is insufficient for your own PR, even if it might be okay when you are merging someone else's. At least that is my understanding of the accepted practice for the last couple of years.

@eileenmcnaughton or @seamuslee001 could you confirm if this is okay to stay merged? Also, can you confirm my understanding about the process for @monishdeb to merge: someone else of an appropriate stature needs to positively indicate a PR of his should be merged. And it should only be him merging his own PR in exceptional circumstances, like if no one else was available when trying to put out a release (although I can't quite see that ever being the case). Others should merge one's PRs, not oneself.

**Comment by JoeMurray** [comment]
My big mistake, sincere apologies @monishdeb !

**Comment by monishdeb** [comment]
No problem at all :)

Cheers!!

**Pull request merged**
