### PR TITLE
dev/core#949 Use text type mysql field when exporting any id-type field

### PR DESCRIPTION
**Pull request by mlutfy**
Overview
----------------------------------------

Reroll of #14361 by @agh1, previously #12598 by @adixon.

To reproduce:

* Create a custom field of type Integer, with Select options
* Create select options that have more than 16 chars, such as "Les phrases en français sont souvent plus longues qu'en anglais" (Text in French is often longer than English).
* Set the value for a contact
* Search contacts, and export that field.

Related issues:

* https://lab.civicrm.org/dev/core/-/issues/181
* https://lab.civicrm.org/dev/core/-/issues/949

Before
----------------------------------------

Field is truncated to 16 chars.

After
----------------------------------------

Field it not truncated.

Technical Details
----------------------------------------

From previous discussion, based on Eileen's feedback of previous PRs, there seems to be consensus that we should not use temp tables. I explored that as a direction, however:

* It's a big can of worms, especially with features such as dedupe-by-address, which work on the tables directly
* I wonder if tmp tables might not be such as bad thing, because ideally exports should run in a queue, so that we can do very large exports without a timeout?

Symbiotic will progressively deploy this patch to all clients, to see if there are performance issues.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@bgm there isn't actually consensus on using text - we need to do a lot of testing to switch all the fields over because there are known mysql limitations are row width so we need to be sure it will still work well with various data sets (large)

On the other hand this is a bug that we know to affect 2 types of fields (and is fixed for all the others)
- phone_type_id - there is an issue in the queue
- custom fields - per the specific description

As you will see if you click through on the failing tests there are a tonne of tests on this code. The main reason I didn't fix this specific case was because I have been very careful to add a new test for every change of any type to this code

**Comment by eileenmcnaughton** [comment]
Note this fixes phones https://github.com/civicrm/civicrm-core/pull/17956

**Comment by mlutfy** [comment]
I did not mention consensus on using 'text', only about getting rid of temp tables :)

The tests will indeed be very useful for narrowing down the scope of fields where we are using text instead of varchar.

Although personally I would argue in favour of using 'text', but I agree it would be safer to first do some benchmarks to be really sure it will not have an impact on a very large export, or narrow down the usage of 'text'. And if we fix this, we should also add a test for long labels. I wanted to rebase and deploy this patch to our sites, to see if we can identify issues.

For posterity, failing tests:

```
    CRM_Export_BAO_ExportTest.testGetSQLColumnsAndHeaders with data set #0
    CRM_Export_BAO_ExportTest.testGetSQLColumnsAndHeaders with data set #1
    CRM_Export_BAO_ExportTest.testGetSQLColumnsAndHeaders with data set #2
    CRM_Export_BAO_ExportTest.testGetSQLColumnsAndHeaders with data set #3
    CRM_Export_BAO_ExportTest.testGetSQLColumnsAndHeaders with data set #4
    CRM_Export_BAO_ExportTest.testGetSQLColumnsAndHeaders with data set #5
    CRM_Export_BAO_ExportTest.testGetSQLColumnsAndHeaders with data set #6
    CRM_Export_BAO_ExportTest.testExportSpecifyFields with data set #0
    CRM_Export_BAO_ExportTest.testExportAddressData
```

most of them expecting a varchar(16) instead of text.

**Comment by eileenmcnaughton** [comment]
@mlutfy yep - if we add a test on the custom data with type int + select - we want that part anyway. Then the fix is either the long route (text) or just fix the few lines of code that are being bypassed

**Comment by mlutfy** [comment]
(I will close for now, until I have time to work on it)

**Pull request closed without merging**
