### PR TITLE
Mixin - Remove case-xml

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Stop advertising case-xml as a mixin, as `hook_civicrm_caseTypes` will be deprecated in favor of API4 Managed Entities.

Technical Details
----------------------------------------
The overlap between `hook_civicrm_caseTypes` and API4 Managed Entities is 100% so we can deprecate the former and stop generating code for it in civix.

See https://github.com/civicrm/civicrm-core/pull/23313

### CODE REVIEW

**Comment by totten** [comment]
I do think it's neat that `hook_managed` / `*.mgd.php` will be able to replace `hook_caseTypes` / `*.xml`. It's more generic and gives more lifecycle options. Huzzah for leverage. 👍 

But.... this PR, at this time... no. To me, the PR looks like "delete first and ask questions later." 🤠 💣

Generally: Core mixins are public APIs. Removing a mixin merits the same high scrutiny as deleting a published hook or CRUD entity. (Even if the bar for that were met -- you certainly wouldn't do it in an RC branch! And especially not if the new replacement is undocumented and hasn't even been merged into `master`!)

Specifically: The `case-xml` mixin is basically a thin wrapper for `hook_caseTypes`. The cost of keeping it is negligible. It should only be deleted when `hook_caseTypes` is deleted. (It could be maintained longer than that, though it's not needed if we have a decent migration path to `hook_managed`.)

I'll grant that deleting `civicrm-core:mixin/case-xml/` doesn't necessarily break downstream extensions (because they could have their own copies). But keeping the mixin in core is in our interest; it means that:

* We can patch it centrally. So, for example, we can add a deprecation notice. Adding this deprecation notice in `civicrm-core` means that it takes on any extensions. (If you let extensions load their own backup copies, then they won't show the deprecation notice.)
* The test still run. So if the hook breaks, we'll know -- rather than being surprised when someone reports a weird backtrace post-release.

More generally, the order-of-operations here should be:

1. Implement new mechanism. Make sure it works.
2. Update dev-tooling/dev-docs/communications to encourage the new mechanism and discourage the old mechanism. Clarify transition steps.
    * For example, someone should make sure that switching formats won't destroy all your `case_type_id` FKs.
    * For example, `civix upgrade` could convert the `*.xml` to `*.php`. Or least raise a warning if it sees the `*.xml` variant.
3. Generate warnings if someone is using the old mechanism.
    * For example, one could generate a warning in `CRM_Case_ManagedEntities` and/or `mixin/case-xml/mixin.php`.
4. After some transitional period, remove the old mechanism.

**Comment by colemanw** [comment]
@totten I'm a bit surprised by your answer, perhaps you know something I don't about this mixin, but just to be clear about my thought process:

- This PR is not to delete or even deprecate `hook_civicrm_caseTypes` which has been around forever.
- This PR is to delete a new, unused mixin which wraps the aforementioned hook.
- The idea here is to prevent confusion caused by presenting a new mixin as "the new way of packaging CiviCase types" when it is in fact not.

I imagine extension developers would get frustrated if we told them "use the new mixin!" and they take a few hours of their time to do so, and then we say "just kidding, don't use that mixin, it's deprecated!" So I thought best to not present it in the first place. When the time comes, they can just migrate from the hook to `.mgd.php`.

**Comment by totten** [comment]
> I imagine extension developers would get frustrated if we told them "use the new mixin!" and they take a few hours of their time to do so, and then we say "just kidding, don't use that mixin, it's deprecated!" So I thought best to not present it in the first place. When the time comes, they can just migrate from the hook to .mgd.php.

I'm not concerned about this. I have zero intention of telling any human that it is important to edit `info.xml` and type `<mixin>case-xml@1.0.0</mixin>`. Your experience (*as someone who edits core-exts, who browses `mixins/*` files, and who used mixins before civix supported them*) should be atypical.

The way I see it, the typical exposure will be this:

1. Download new `civix.phar`
2. Run `civix upgrade`
3. If the extension has `xml/case/*` files, then it will automatically add `<mixin>case-xml@1.0.0</mixin>`.
    * If this happens, the upgrader will tell you that it's doing this, so you might take some time to learn about it. I suspect most people won't bother (because they don't have to). But if they do, then `case-xml` is a drop-in-the-bucket. The same thing is happening with `mgd-php`, `menu-xml`, `ang-php`, `setting-php`, and `theme-php`. After you've understood any one of those transitions, the others are minor adaptations.

So... I'm not worried that `case-xml` specifically will lead anyone into a wasted cul-de-sac of learning.

---

I think what you were aiming for was this: *remove all references to `case-xml` across all spaces ASAP* (eg `civicrm-core.git` and `civix.git`). This I have problems with. Maybe this needs to be more concrete.

* [module.civix.php](https://github.com/totten/civix/blob/master/src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php) for v22.05 is thinner. That's a major goal -- trim down that file. There is a bunch of boilerplate that it no longer generates, such as  `_*_civix_civicrm_caseTypes()`.
* When using civix, it is generally eager to regenerate `module.civix.php`. This can happen with `civix upgrade`, `civix generate:module`, `generate:page`,   `generate:upgrader`, `generate:entity-boilerplate`, and maybe others.
    * _Basically_: `module.civix.php` will be regenerated when you do anything, at all, with civix.
* If an existing extension has `xml/case/*` files, then it needs _something_ to load those files. It needs `_*_civix_civicrm_caseTypes()` or `case-xml`.

If we do that, then the result is this: running one command to add a new artifact (eg `civix generate:page`) would have the side-effect of breaking unrelated, pre-existing artifacts (eg `xml/case/*`). That is alarming. It merits a big redflag, eg

> If _yaddayadda_ (*case xml*), then you must not use the new civix, because it can break things -- unless you go do _yaddayadda_ (*case xml=>mgd*). But _yaddayadda_ hasn't been documented or released, and the migration hasn't been tested. In fact, support for it hasn't been merged yet. So if you do _yaddayadda_, it won't work for at least a couple months.

I do not want such a redflag on a civix release. I would sooner resume generating `_*_civix_civicrm_caseTypes()` in the boilerplate for all extensions. I don't think it matters if the material impact of the redflag is limited to a dozen extensions -- the presence of the redflag would be a drag in itself. It makes the tooling feel flaky.

But I do want to remove `_*_civix_civicrm_caseTypes()`. Very much! Especially if `hook_caseTypes` is going to be deprecated! I don't like the idea that all these extensions would continue loading code for a deprecated hook which 98% don't need...

---

It's tantalizing to score another -160 SLOC on this PR. But look at the bigger score. Public `universe` has 330+ extensions with `_*_civix_civicrm_caseTypes()` boilerplate. The specific boilerplate around `caseTypes` weighs-in at roughly 40 SLOC for each extension. The score on removing  `_*_civix_civicrm_caseTypes()` would be -13,200 SLOC (`330 * -40`) for public `universe`. 

(*Private universe is bigger but harder to examine. `stats.civicrm.org` reports 4,800 extensions, though I have no idea what filtering that has, so I don't want to read anything concrete into it. But we can figure the limit -- ie up to -192,000 SLOC.*)

(*If you take all the boilerplate that can be removed with existing mixins and v22.05, it's roughly 210 SLOC per extension. So the overall limit is like -1,008,000 SLOC. Which... would be a great factoid for a blog title... "Civix v22.05: How to remove 1 million lines of code".*)

Of course, it won't be -13,200 or -1,008,000 all-at-once. The key obstacle is persuading downstream to regenerate templates. For that, we must encourage a sense of confidence that it is easy and safe. Redflags and footnotes undermine that.

IMHO, keeping +160 SLOC (*which is almost entirely test-content*) is a very small price to pay if it can raise confidence in the conversion and gets the ball rolling on -1,008,000 SLOC.

**Comment by colemanw** [comment]
Thanks for the explanation @totten. That makes sense, I agree that even if it's immediately deprecated the mixin is useful for reducing boilerplate in extensions.

Just for the sake of completeness, I note that there's an alternative way of achieving that reduction, but it would be additional work and you've already done a lot. It would be:
1. When running `civix generate*`, scan for the presence of caseType.xml files.
2. If none present, delete the boilerplate hook code from `module.civix.php` and the hook implementation from `module.php`.
3. Otherwise do nothing.

**Pull request closed without merging**
