### PR TITLE
CRM_Core_BAO_Cache - Remove functions deprecated a year ago

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Remove functions deprecated a year ago in the CRM_Core_BAO_Cache class

Before
----------------------------------------
Screen Shot 2020-07-29 at 12 44 27 PM

Screen Shot 2020-07-29 at 12 42 58 PM

Screen Shot 2020-07-29 at 12 43 57 PM

After
----------------------------------------
Poof

Technical Details
----------------------------------------
These have been spitting out deprecation notices for a year

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton test fails relate

**Comment by totten** [comment]
Yeah, a year is a pretty fair wind-down period.

I did a grep on a recent `universe` for references to the deprecated `CRM_Core_BAO_Cache::setItem`, `::getItem`, and `::deleteGroup` -- and these were the only repos that still needed an update:

* https://github.com/greenleafadvancement/com.greenleafadvancement.donorsearch (ping @deepak-srivastava)
* https://github.com/compucorp/civihr (ping @jamienovick)
* https://github.com/catorghans/net.trinfinity.orgis.mi.dataquality (ping @catorghans)

The required updates should be pretty simple - i.e. swapping `CRM_Core_BAO_Cache` with [Civi::cache(...)](https://docs.civicrm.org/dev/en/latest/framework/cache/), e.g.

* If you just need to store 1 or 2 bespoke items in a SQL cache, then use `Civi::cache('long')`.
* If you need to access the cache-group-formally-known-as `contact fields`, then use `Civi::cache('fields')`.

**Comment by eileenmcnaughton** [comment]
Thanks @totten - I think you ping on top of a year of noisy deprecation notices should be enough. I've fixed the tests

**Comment by totten** [comment]
Test failure looks unrelated. We've given a small pause on the pings, but I don't really expect pushback, and those new filings by @eileenmcnaughton were good idea.

Merging.

**Pull request merged**
