### PR TITLE
Setting conversion

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Convert 3 more fields on display preferences form to use metadata

Before
----------------------------------------
no change

After
----------------------------------------
no change

Technical Details
----------------------------------------
The goal is to build the whole form (& other settings / preference forms, including in extensions) from metadata without hard coding. This PR tackles 2 rich text fields (+ one checkboxes). However the sizing of the fields is bad before this & I haven't attempted to resolve

Comments
----------------------------------------
@mattwire this means we will still not have converted any 'YesNo' or text - but getting closer

### CODE REVIEW

**Comment by mattwire** [comment]
@eileenmcnaughton Style warning..

**Comment by eileenmcnaughton** [comment]
@mattwire hopefully fixed

**Comment by eileenmcnaughton** [comment]
@mattwire can you check this one?

**Comment by mattwire** [comment]
Now I get
```
Warning: array_fill_keys() expects parameter 1 to be array, string given in CRM_Admin_Form_Preferences->setDefaultsForMetadataDefinedFields() (line 229 of /home/dev/buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Admin/Form/SettingTrait.php).
```

**Comment by eileenmcnaughton** [comment]
@mattwire I'm not seeing that on the display settings page? I'm seeing some notices on some other pages (which I was going to fix next)

**Comment by mattwire** [comment]
@eileenmcnaughton Looks like this needs rebasing?

**Comment by eileenmcnaughton** [comment]
@mattwire done!

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by colemanw** [comment]
Jenkins is happy :)
@mattwire do you get any more notices now when you test?

**Comment by colemanw** [comment]
Jenkins is happy :)
@mattwire do you get any more notices when you test?

**Comment by colemanw** [comment]
Jenkins is happy :)
@mattwire do you get any more notices when you test?

**Comment by colemanw** [comment]
Jenkins is happy :)
@mattwire do you get any more notices when you test?

**Comment by mattwire** [comment]
Ok good to merge @colemanw @seamuslee001

**Pull request merged**
