### PR TITLE
CRM-19972 Add in post upgrade message about the addition of manage ta…

### PR DESCRIPTION
**Pull request by seamuslee001**
**…gs** permission

ping @totten

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by totten** [comment]
I haven't tested this, but IMHO its scope is reasonable for a last minute patch to `4.7.16-rc` because:
 * The change only provides _advice_ during the upgrade -- it doesn't change runtime logic or database content or UI.
 * From a sysadmin perspective, this probably feels like a recent regression (i.e. `4.7.13+`  doesn't work the same way as `4.7.12` unless they take extra steps).

**Comment by totten** [comment]
@seamuslee001, can you reopen the PR against `master`?

**Comment by seamuslee001** [comment]
closed in favor of https://github.com/civicrm/civicrm-core/pull/9808

**Pull request closed without merging**
