### PR TITLE
CRM-19325 : Search contributions that are not in any batch

### PR DESCRIPTION
**Pull request by monishdeb**
* [CRM-19325: Search contributions that are not in any batch](https://issues.civicrm.org/jira/browse/CRM-19325)

### CODE REVIEW

**Comment by monishdeb** [comment]
This PR exhibit what form-value should be given to an attribute so that the value get eventually processed into ```IS (NOT) NULL``` or ```IS (NOT) EMPTY``` where clause of search query. These are the steps: 
1. Provide selectable or explicit value as in here ```IS NULL``` at https://github.com/civicrm/civicrm-core/pull/9492/files#diff-0a639f0cf282805e238274495195e6a4R1129 

2. Mention the fieldname in ```$specialParams``` array inside postprocess as in [here](https://github.com/civicrm/civicrm-core/pull/9492/files#diff-1933fff668010b3ebd72ee4070e82f00R283) . The value ```IS NULL``` got eventually formatted  into OK (Operator as Key) format as ```array('IS NULL' => 1)``` as in [here](https://github.com/civicrm/civicrm-core/pull/9492/files#diff-e54381bfdf51e31cab376c71ca0d66ffR6075) 
NOTE : if you only want to format the values for NULL/EMPTY value ONLY then mention the fieldName under ```$nullableFields``` as in [here](https://github.com/civicrm/civicrm-core/pull/9492/files#diff-e54381bfdf51e31cab376c71ca0d66ffR6062) 

3. Basically we are formatting the value into OK format before the search query build like how the advance filters work in case of API and other search formvalues. 

4.  Always call ```CRM_Contact_BAO_Query::buildQillForFieldValue(...)``` to build Qill operator and value respectively (as in [here](https://github.com/civicrm/civicrm-core/pull/9492/files#diff-0a639f0cf282805e238274495195e6a4R570) )

**Comment by monishdeb** [comment]
@johanv its working for me,  have a look! 

Here's my test-cases : 
1. Exclude batch 
image

2. Include batch 
image

3. All contributions
image

**Comment by eileenmcnaughton** [comment]
There is a specific issue here (which it looks like you have solved) but, to test the solution further, how easy is it to expand it to search for contributions without pledges? If it is an elegant solution then hopefully we can start to add things like that on we get many requests of that variety (no membership, no event - or perhaps they could be replaced by 'no line item in this price set, with this price field, with this price label etc).

**Comment by monishdeb** [comment]
@eileenmcnaughton pretty simple. Here's my patch https://gist.github.com/monishdeb/c9a0c8da2d1ba29bc7e1cb99d0927a79 on top of this changes to support ```Is pledge Contribution? Yes/No``` 

## -any- case 
image

## Yes case 
image

## No case 
image

**Comment by eileenmcnaughton** [comment]
nice!

**Comment by eileenmcnaughton** [comment]
any thoughts on unit tests?

**Comment by monishdeb** [comment]
@eileenmcnaughton  actually I didn't found any test coverage for Search Form other than Webtest. But lemme try to add one by using ```processSpecialFormValue(...)``` and ```CRM_Contact_BAO_Query``` instance to build search query.

**Comment by eileenmcnaughton** [comment]
I think there are some group tests that use the search form. 

I don't think webtests are really maintained /maintainable :-(

**Comment by monishdeb** [comment]
Yup there are https://github.com/civicrm/civicrm-core/tree/master/tests/phpunit/CRM/Contact/Form/Search/Custom on custom search form and these operate on saved data set and use the custom queries to assert the result. Lemme check how I can make use of Advance Search post process.

**Comment by monishdeb** [comment]
@eileenmcnaughton added unit test for batch filters. Have a look https://github.com/civicrm/civicrm-core/pull/9492/files#diff-c4448e6d970120e7c10d0a05bf6008b5R119

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by monishdeb** [comment]
@eileenmcnaughton I am merging this PR as I have covered unit-test and highlighted the behaviour with screenshot

**Pull request merged**
