### PR TITLE
Add permission metadata to contact is_deleted field

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
This adds a bit more metadata to the contact schema, which I think will come in handy for search builder.
It should make it easier for search builder to automatically give the option to view deleted contacts only to users with permission.

Before
----------------------------------------
Less metadata

After
----------------------------------------
More metadata

Technical Details
--------
The `permission` field property was first added in #14679. APIv4 automatically restricts access to fields with this property based on the current user's permission.

Since contacts without this permission should not be allowed to search for deleted contacts, hiding this field from them makes sense.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw I think this is OK but it's a bit short on documentation & I'm not clear how it will be used or if it will wind up being something that 'seemed like a good idea at the time' - if we add a new metadata key we should document it

**Comment by seamuslee001** [comment]
So will this mean that the is_deleted field won't be returned for people who don't have this permission?

**Comment by colemanw** [comment]
@eileenmcnaughton it was documented in my head :)

I've added to the description - this isn't actually a new metadata key it's already in there for another field and the logic to handle it is already in place.

@seamuslee001 yes that's right. APIv4 automatically does this filtering when you call getFields with checkPermission enabled.

**Comment by colemanw** [comment]
I've rebased this, I think it's good to merge now.

**Comment by eileenmcnaughton** [comment]
@colemanw OK if this is following an existing pattern then that seems fine

**Pull request merged**
