### PR TITLE
5.60

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
_A brief description of the pull request. Keep technical jargon to a minimum. Hyperlink relevant discussions._

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by demeritcowboy** [comment]
I'm not sure what to do with this. If I just close it, I expect github will prompt to open a new one. Is there a way to tell github "don't bother"?

**Comment by eileenmcnaughton** [comment]
@demeritcowboy I'll sort it

**Comment by eileenmcnaughton** [comment]
This one https://github.com/civicrm/civicrm-core/pull/25839 will update & it will understand it is merged

**Comment by demeritcowboy** [comment]
Thanks.
I wonder if in the future when all programming is done by robots they will have these problems. That will be fun to watch.

**Comment by eileenmcnaughton** [comment]
Ah the joy - interesting that it closed this PR when I merged the other - the robots have been busy...

**Pull request merged**
