### PR TITLE
Translate description in DAO files

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Translate description in DAO files

Before
----------------------------------------
Description field not translated in DAO descriptions - this would only really be apparent when calling the getfields api.

After
----------------------------------------
Description field  translated in DAO descriptions 

Technical Details
----------------------------------------
This relates to the attempt here https://github.com/civicrm/civicrm-core/pull/12971
to use description directly in the Entity Forms & questions as to whether it is translated.

Currently they are not but there seems like no downside in translating them

Comments
----------------------------------------
@mattwire @seamuslee001 @colemanw @mlutfy @totten can anyone think of any downsides of doing this.

(note this will go stale quickly)

### CODE REVIEW

**Comment by seamuslee001** [comment]
I don't have a concern with this

**Comment by colemanw** [comment]
My only concern is that it adds addnl burden for translators to translate a bunch of (currently) unused strings.

**Comment by eileenmcnaughton** [comment]
@colemanw I guess the mitigating factor there is it allows us to sync up the schema & form descriptions & start to only maintain the schema one

**Comment by colemanw** [comment]
Caved into the peer/time pressure :)

**Comment by eileenmcnaughton** [comment]
lol - I'll merge #12971 then

**Comment by JoeMurray** [comment]
I like this idea and am happy to see this merged.

**Pull request merged**
