### PR TITLE
Afform - fix missing page title

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes missing title when viewing Afform as a full page.

Before
----------------------------------------
Page title missing.

After
----------------------------------------
Title visible on the page and in the browser tab.

Technical Details
-----------
Evidently this regressed in 3ee3a8829ec6ceade287e5eea9ed6d355ed7e3cc. Not quite sure how the bug slipped in.

### CODE REVIEW

**Comment by kurund** [comment]
@colemanw 

This patch fixes the issue with missing title. 

This issue exist on 5.70.x hence, I think we should backport it to 5.71 branch.

**Comment by colemanw** [comment]
retest this please

**Comment by kurund** [comment]
test this please

**Comment by kurund** [comment]
test this please

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by eileenmcnaughton** [comment]
test this please

**Pull request merged**
