### PR TITLE
[REF] Minor extraction to help cleanup permission code

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
[REF] Minor extraction to help cleanup permission code

Before
----------------------------------------
Code not extracted

After
----------------------------------------
tada

Technical Details
----------------------------------------
Just trying to improve the readability of the super_duper pr which will likely get a few eyes on

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
retest this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
hmm still failing on stuff that seems unrelated to the change

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Pull request merged**
