### PR TITLE
Fix ts() namespace in searchKit & afform extensions

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Ensures all translatable strings in SearchKit & Afform extensions are translated using the extension namespace.

Before
----------------------------------------
Translatable strings not namespaced.

After
----------------------------------------
Fixed.

Comments
----------------------------------------
Also a little minor code cleanup in this PR.

### CODE REVIEW

**Comment by mlutfy** [comment]
Cross-referencing previous discussions on core-ext gettext namespacing/domains:  
https://lab.civicrm.org/dev/translation/-/issues/52

I'm :+1: on merging this.

**Comment by colemanw** [comment]
Sounds like this is merge-ready.

**Comment by seamuslee001** [comment]
@colemanw can you please rebase this?

**Comment by mlutfy** [comment]
jenkins, test this please

```
api_v3_SyntaxConformanceTest::testCreateSingleValueAlter with data set #82 ('UFField')
Failure in api call for UFField create:  Undefined index: type
```

**Comment by colemanw** [comment]
That's an unrelated fail that happens from time to time.

**Comment by mlutfy** [comment]
yay :tada:  thanks @colemanw

**Pull request merged**
