### PR TITLE
Crm 17558:Resolving conflicted for labels by changing id for one group.

### PR DESCRIPTION
**Pull request by sarehag**
Solved the issue by giving the group_type on the Search page a different id.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This patch seems to make sense - but the issue it links to is closed. Has it been separately resolved?

**Comment by sarehag** [comment]
https://issues.civicrm.org/jira/browse/CRM-17558

Looks open to me? Seems I missed a dash in the issue name though, so I guess it didn't tag the issue with this patch. Should I add a comment with this pull request on the issue in Jira?

Please say if something more than the name of the pull request title got messed up, so I can learn.

Thank you.

**Comment by eileenmcnaughton** [comment]
Hmm - I must have just been looking at the wrong ticket!

**Comment by JKingsnorth** [comment]
I guess it needs the 'CRM-17558 ' at the beginning to get picked up. Keeps it nice and consistent anyway. PR looks good @sarehag thanks for picking up this issue =]

**Pull request merged**
