### PR TITLE
Remove legacyCreateMultiple function

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Remove legacyCreateMultiple function

This was annotated deprecated 7 years ago, is called 'legacy' and was nosily deprecated 10 months ago. It IS still called from one jma extenion but I think it's OK to remove with a ping

Before
----------------------------------------
image

After
----------------------------------------
poof

Technical Details
----------------------------------------
@JoeMurray @seamuslee001 - jmagrantapplications is the only universe usage of this function

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton there's a MC

**Comment by eileenmcnaughton** [comment]
@colemanw fixed

**Comment by yashodha** [comment]
@eileenmcnaughton merging this. Thanks!

**Comment by eileenmcnaughton** [comment]
Yay - thanks @yashodha - nice to see these things do eventually die

**Pull request merged**
