### PR TITLE
dev/core#4782 - alternate 2 to 28191 - Allow turning off use of memory engine

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/4782

Before
----------------------------------------
Crash

After
----------------------------------------
Crash, unless you tun on this setting, and then no crash.

Technical Details
----------------------------------------

Comments
----------------------------------------
Alternate to alternate to #28191

### CODE REVIEW

**Comment by robertgarrigos** [comment]
Trying this PR, I'm getting this error: `QuickForm Error: unregistered element` when accessing civicrm/admin/setting/misc

**Comment by robertgarrigos** [comment]
Nop. still same error

**Comment by demeritcowboy** [comment]
Does ConfigAndLog have any more information about which field? It works on the demo site for this PR [http://site-list.test-1.civicrm.org/?filter=core-31662-*](http://site-list.test-1.civicrm.org/?filter=core-31662-*)

Otherwise did the PR apply fully? e.g. if maybe you're testing against an earlier version?

**Comment by robertgarrigos** [comment]
Yes, indeed, the patch didn't apply fully. My fault, here. And yes, this patch is working for me. I could just disable SQL Memory and my civicrm instance in DO is working now.

**Comment by arminpkathrein** [comment]
Same here, it's working for me also.

**Pull request merged**
