### PR TITLE
[WIP] (dev/drupal/7) Implement universal script `civicrm.config.php` and eliminate  CRM_Core_CodeGen_Config

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
This PR introduces `civicrm.config.php` to codebase which is universal php script to initialize Civi. Also by doing so it eliminates the need for ```CRM_Core_CodeGen_Config``` to write the same file using CMS specific template file.

Issue: https://lab.civicrm.org/dev/drupal/issues/7

Technical Details
----------------------------------------
This PR is dependent on https://github.com/civicrm/civicrm-core/pull/12016 for which I have cherry-picked its commit in this PR. This patch has the following changes from code pov:
1. Introduce `civicrm.config.php` in codebase
2. The new file and a universal script ```civicrm.config.php``` contain a mix of https://github.com/civicrm/cv/blob/master/src/CmsBootstrap.php and https://github.com/civicrm/civicrm-wordpress/blob/master/civicrm.config.php.wordpress 
3. Boots CiviCRM instance ```\Civi\Bootstrap::singleton()->bootCivi();```
4. Remove ```CRM_Core_CodeGen_Config```

### CODE REVIEW

**Comment by monishdeb** [comment]
ping @colemanw @totten

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by colemanw** [comment]
@totten I think you are more familiar with this area than me.

**Comment by totten** [comment]
OK, so this PR is flagged "WIP", and maybe I'm responding a bit prematurely... but here goes:

* I don't think we should *remove* the `GenCode` bits for producing CMS-specific variants of `civicrm.config.php`. In an ideal world, perhaps we could... because it would be broadly cleaner/simpler. However, I also strongly suspect there to be edge-cases where they differ, and regressions are... unpopular. Rather, the aim should be to provide this file as a default (when you get the raw code from git) -- while still allowing `GenCode` and `distmaker` to provide backward-compatible variants of `civicrm.config.php`.

* There's several changes from the previous `CmsBootstrap.php` which I don't follow. It's not that I think the file is perfect... but some of the changes seem mysterious/arbitrary. They smell sorta like "we don't need feature X, so let's remove it". This is going to make it hard to keep bootstrap code aligned between cv and core. To be maintainable, I think we really need to keep a few design constraints:

    * The bootstrap class is self-contained. It does not depend on, eg, `civicrm-version.php`. When the bootstrap file changes, we should be able to simply copy it from `cv` to `civicrm-core`.
    * The design/feature-set/interfaces for `CmsBootstrap.php` is the same in cv and core (although they could pass different boot options).

* There may be some confusion because `Bootstrap.php` ([orig](https://github.com/civicrm/cv/blob/master/src/Bootstrap.php), [wp copy](https://github.com/civicrm/civicrm-wordpress/blob/master/civicrm.config.php.wordpress)) and `CmsBootstrap.php` ([orig](https://github.com/civicrm/cv/blob/master/src/CmsBootstrap.php)) are fundamentally different designs -- the former uses Civi-first boot protocol, and the latter uses [CMS-first boot protocol](https://lab.civicrm.org/development-team/cloud-native/issues/7). This means that some designs must be different -- e.g. `CIVICRM_SETTINGS` (Civi-first) vs `CIVICRM_BOOT` (CMS-first). Blending the two doesn't make sense to me in the abstract.

Here's a recommendation for how to address those:

1. In `CRM/Core/CodeGen/Config.php` and `.gitignore`, simply rename `civicrm.config.php` to `civicrm.config-generated.php`.
2. Copy `CmsBootstrap.php` verbatim.
3. If changes are necessary, make those as a series of commits which explain the changes.
4. Create a file `civicrm.config.php` which is just:

```php
// Use new boot protocol if (a) site-admin requests it (`CIVICRM_BOOT`)
// or (b) there's no other option.
if (getenv('CIVICRM_BOOT') || !file_exists(__DIR__ . DIRECTORY_SEPARATOR . `civicrm.config-generated.php`)) {
  require_once __DIR__ . DIRECTORY_SEPARATOR . 'Civi/Cv/CmsBootstrap.php';
   \Civi\Cv\CmsBootstrap::singleton()->bootCms()->bootCivi(); 
}
else {
  require_once    __DIR__ . DIRECTORY_SEPARATOR . `civicrm.config-generated.php`;
}
```

**Comment by monishdeb** [comment]
Thanks, @totten for your feedback. I am closing this PR and will submit a new, as per the recommendations.

**Pull request closed without merging**
