### PR TITLE
CRM-17289 limit membership_type entity reference to active types

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
- [CRM-17289: Membership type field in search form includes disabled membership types](https://issues.civicrm.org/jira/browse/CRM-17289)

### CODE REVIEW

**Comment by colemanw** [comment]
I'll be surprised if this works. Getlist takes a different param structure than 'get'. Example

    civicrm_api3('contact', 'get', array('contact_type' => 'Individual'));

    civicrm_api3('contact', 'getlist', array('params' => array('contact_type' => 'Individual')));

The params sent to the underlying 'get' api are nested, because the outer layer of params are reserved for params to send to 'getlist' (page_num and the like).

**Comment by eileenmcnaughton** [comment]
Hmm - it works in the entity reference - but not obviously in the underlying api

**Comment by eileenmcnaughton** [comment]
@colemanw  if this seems OK to you in principle I'll tidy it up (the comment block) & add a unit test

**Comment by colemanw** [comment]
Yes if it works, fine by me.

**Pull request merged**
