### PR TITLE
Api4 docs improvements

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Improves APIv4 docs and their display in the explorer.

Changes:
----------------------------------------
- Improves get helper functions to be more convenient
- Adds docblocks
- Displays more docblocks in api explorer
- Adds more debug output to api explorer
- Displays code styles in tabs and adds more styles

image

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Before image
Screen Shot 2020-01-30 at 12 42 28 PM

**Comment by eileenmcnaughton** [comment]
@colemanw I have 2 concerns here - one is not that important - ie. as soon as I click on 'debug' the screen gets a bit weird on the left
Screen Shot 2020-01-30 at 1 03 55 PM

My bigger concern is to understand whether there is any performance cost to parsing these details - I recently discovered that there is a moderate performance cost  to the  code that makes  some  api3 functions as deprecated as that gets called over & over - still stepping  through the code to understand....

**Comment by colemanw** [comment]
@eileenmcnaughton are you using shoreditch theme? I don't see the weird spacing issues on my install with shoreditch, but happy to try with other themes.

Re performance: the debug stuff doesn't run at all unless you explicitly pass `debug: true` to the api call. This does set the Api Explorer to do that by default, but I don't think performance is a concern in the Explorer.

**Comment by eileenmcnaughton** [comment]
@colemanw the screen thing is only after I've had a wide thing open in the debug - I think it's ignorable.

Re performance - what about the docblock parsing - does that happen every call - !$this->select seems to be true a lot

**Comment by colemanw** [comment]
@eileenmcnaughton APIv4 uses a lot of reflection to inspect its own params and fields, which provides the validation etc. This PR doesn't change that but I'd be happy to take a look at that from a performance POV.

In the meantime it would be nice if we could merge this bc I've got more unstaged commits stacked up & waiting for this to be merged.

**Comment by eileenmcnaughton** [comment]
OK I'm good to proceed like that

**Pull request merged**
