### PR TITLE
CRM-18528 - unit test to check group filter

### PR DESCRIPTION
**Pull request by jitendrapurohit**
- [CRM-18528: Manage Groups search ignores filters](https://issues.civicrm.org/jira/browse/CRM-18528)

unit test to check https://github.com/civicrm/civicrm-core/pull/8366

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
jenkins, test this please

**Comment by jitendrapurohit** [comment]
test works on local, but fails here. Can jenkins be not updated with former PR #8366?

**Comment by jitendrapurohit** [comment]
jenkins, test this please

**Comment by eileenmcnaughton** [comment]
That PR you mentioned is merged - but I don't see $_GET['is_unit_test'] being set in your test?

Yay for the test!!

**Comment by jitendrapurohit** [comment]
'is_unit_test' [is set in `$this->_params`](https://github.com/civicrm/civicrm-core/pull/8414/files#diff-b6ec2651e7fa5da760fbc3e7ef13279fR36) which i [assign it to `$_GET`](https://github.com/civicrm/civicrm-core/pull/8414/files#diff-b6ec2651e7fa5da760fbc3e7ef13279fR88).

Need to figure out why it fails on jenkins.

**Comment by jitendrapurohit** [comment]
jenkins, retest this please

**Comment by jitendrapurohit** [comment]
jenkins, test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by jitendrapurohit** [comment]
jenkins, test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
ok to test

**Comment by eileenmcnaughton** [comment]
Looks like it is running https://test.civicrm.org/job/CiviCRM-Core-PR/10131/console but it's still showing pending'

**Comment by jitendrapurohit** [comment]
Jenkins, test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@totten another one that doesn't want to fire?

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by yashodha** [comment]
Jenkins test this please

**Comment by monishdeb** [comment]
Closed in favor of https://github.com/civicrm/civicrm-core/pull/8729

**Pull request closed without merging**
