### PR TITLE
Fixes core#3369 scheduled Reminder limited by Participant Role fails if any participant has multiple roles

### PR DESCRIPTION
**Pull request by kainuk**
Overview
----------------------------------------
Fixes the following core issue https://lab.civicrm.org/dev/core/-/issues/3369. @MegaphoneJon created a PR See https://github.com/civicrm/civicrm-core/pull/20981. This PR is based on his work.

An addition in this PR is that it considers that a reminder can be configured to select two participant roles, and the way this is stored / (See comment https://github.com/civicrm/civicrm-core/pull/20981#issuecomment-902527545).

Technical Details
----------------------------------------
This PR contains a test of all the participant role and recipient_listing combinations.

### CODE REVIEW

**Comment by agileware-justin** [comment]
Test this please

**Comment by agileware-justin** [comment]
* General standards
    * Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
        * __PASS__ : The goal/problem/solution have been adequately explained in the PR.
    * User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
        * __PASS__: The change would be intuitive or unnoticeable for a majority of users who work with this feature.
    * Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
        * __ISSUE__: The user documentation should be updated.
        * __COMMENTS__: PR to update documentation is here https://lab.civicrm.org/documentation/docs/user-en/-/merge_requests/579
    * Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
        * __PASS__: Set up Event and registered 8 Participants. Assigned multiple roles to 6 Participants and 2 Participants had Attendee role. Set up Scheduled Reminder to email **Volunteer** or **Speaker** Participant roles. Unpatched, no Participant received the Scheduled Reminder. Patched, all **6 Participants** with the **Volunteer** or **Speaker** Participant roles received the Scheduled Reminder.

Participant test data
participants

**Unpatched**, incorrect result - 0 Scheduled Reminders were sent
unpatched-result

**Patched**, correct result - 6 Scheduled Reminders were sent
patched-result


* Developer standards
    * Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
        * __PASS__: The change preserves compatibility with existing callers/code/downstream.
    * Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
        * __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
    * Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
        * __PASS__: The change sufficiently improves test coverage, or the change is trivial enough that it does not require tests.
    * Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
        * __UNREVIEWED__
        * __COMMENTS__: Waiting for Jenkins to restart and complete tests. Was showing message: "Jenkins is going to shut down" at time of testing. Will update once Jenkins comes back.

**Comment by agileware-justin** [comment]
@eileenmcnaughton OK to merge!

Thanks very much for the fix @kainuk and @MegaphoneJon 

Merge it

**Comment by eileenmcnaughton** [comment]
Merging based on @agileware-justin's review

**Pull request merged**
