### PR TITLE
CRM-18344 - Show attachments on CiviMail review panel

### PR DESCRIPTION
**Pull request by colemanw**
https://issues.civicrm.org/jira/browse/CRM-18344

### CODE REVIEW

**Comment by twomice** [comment]
Reviewing.

**Comment by twomice** [comment]
Jenkins please retest

**Comment by twomice** [comment]
Jenkins retest this please.

**Comment by twomice** [comment]
Jenkins retest this please.

**Comment by twomice** [comment]
Jenkins retest this please.

**Comment by twomice** [comment]
@totten Not sure why, but this patch is failing to merge (according to the Jenkins console output, "error: patch failed: ang/crmMailing/BlockReview.html:24" and "error: ang/crmMailing/BlockReview.html: patch does not apply"), even though "This branch has no conflicts with the base branch".  Might this be some problem in the merge/build system?

**Comment by colemanw** [comment]
I've rebased it, hopefully that fixes things.

**Comment by twomice** [comment]
Tested as follows:

1. Create a new mailing that has two attached files
2. Click "Next" to get to the Review screen.

Expected behavior: Review screen includes a section labeled "Attachments" which includes links to the two attached files.

Actual behavior:
On dmaster: "Attachments" section is not displayed.
On patched test site with this PR: Behaves as expected.

**Comment by twomice** [comment]
@totten Please merge.

**Pull request merged**
