### PR TITLE
CustomFields - Drop unused column 'mask'

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Drops a column which doesn't appear to be used for anything. 

Before
----------------------------------------
`mask` is added to the `CRM/Custom/Form/Field.php` quickform but never printed in the corresponding `CRM/Custom/Form/Field.tpl`, and does not appear to be used anywhere else. I don't see any reference to it in `CRM_Core_BAO_CustomField` when the custom fields actually get rendered.

After
----------------------------------------
Buh bye.

### CODE REVIEW

**Comment by yashodha** [comment]
@colemanw Is this something some extensions could have used may be?

**Comment by colemanw** [comment]
@yashodha I searched through `universe` and couldn't find it used anywhere.

**Comment by yashodha** [comment]
@colemanw merging this PR.

**Comment by MegaphoneJon** [comment]
This breaks upgrades when advanced logging is enabled (and I would guess possibly multilingual).  I think the `dropColumn` function needs to immediately update the logging schema and rebuild triggers.  I'll open a Gitlab ticket.

**Comment by seamuslee001** [comment]
hmm @MegaphoneJon so similar to this patch https://github.com/civicrm/civicrm-core/pull/25421 but slightly different context but same problem right?

**Comment by MegaphoneJon** [comment]
@seamuslee001 Yes, that's correct.  I think maybe `alterColumn` and `dropColumn` should have those lines themselves rather than relying on their being added to the upgrade step.

**Comment by colemanw** [comment]
I'd be ok with adding the logging/schema/rebuild functionality to `dropColumn` and *maybe* `alterColumn`. I agree it would benefit long-term stability but might cause some short-term upset if we don't thoroughly check all the places those functions are used and verify the change is ok.

**Pull request merged**
