### PR TITLE
CRM-21363 Only implement ONLY_FULL_GROUP_BY if it is in the default g…

### PR DESCRIPTION
**Pull request by seamuslee001**
…lobal sql_modes

@mattwire @kcristiano  Matt Kevin can you test this out on your Maria servers and see if things settle down at all? also ping @monishdeb

### CODE REVIEW

**Comment by kcristiano** [comment]
@seamuslee001 success!  Macos mariadb 10.2.10  I applied this patch and https://github.com/civicrm/civicrm-core/pull/11248  

Let me know if I need to test one by one.

**Comment by seamuslee001** [comment]
@kcristiano note this is aimed at the RC branch which should then be forward ported to -> master ping @eileenmcnaughton @monishdeb @totten

**Comment by eileenmcnaughton** [comment]
Merging based on test by @kcristiano & as a recent regression

**Comment by kcristiano** [comment]
@seamuslee001 Thanks I missed the target branch.

**Pull request merged**
