### PR TITLE
Try validate financials again - see how we are progressing

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Same as https://github.com/civicrm/civicrm-core/pull/20420

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
api_v3_ACLPermissionTest.testEntitiesGetHookLimitingHookNoCheck with data set #0
api_v3_ACLPermissionTest.testEntitiesGetCoreACLLimitingHookNoCheck with data set #0
api_v3_ACLPermissionTest.testEntitiesGetCoreACLLimitingCheck with data set #0
api_v3_LineItemTest.testDeleteLineItem with data set "APIv3"
api_v3_LineItemTest.testDeleteLineItem with data set "APIv4"
api_v3_MembershipTest.testActivityForCancelledContribution
api_v3_OrderTest.testCreateOrderIfTotalAmountDoesMatchLineItemsAmountsAndTaxSupplied
CRM_Contribute_BAO_ContributionRecurTest.testAutoRenewalWhenOneMemberIsDeceased
CRM_Core_Payment_BaseIPNTest.testThatCancellingEventPaymentWillCancelAllAdditionalPendingParticipantsAndCreateCancellationActivities
CRM_Event_BAO_ChangeFeeSelectionTest.testCRM19273
CRM_Event_BAO_ChangeFeeSelectionTest.testCRM17151
CRM_Event_Form_Registration_ConfirmTest.testPaidSubmit with data set #0
CRM_Event_Form_Registration_ConfirmTest.testPaidSubmit with data set #1
CRM_Event_Form_Registration_ConfirmTest.testTaxMultipleParticipant
CRM_Financial_BAO_FinancialItemTest.testAdd
CRM_Financial_BAO_FinancialItemTest.testRetrieve
CRM_Financial_BAO_FinancialItemTest.testCreate
CRM_Member_Form_MembershipTest.testFinancialEntriesOnCancelledContribution
CRM_Member_Form_MembershipTest.testTwoInheritedMembershipsViaPriceSetInBackend
CRM_Member_Form_MembershipTest.testTwoMembershipsViaPriceSetInBackendWithDiscount
CRM_Member_Form_MembershipTest.testContributionFormStatusUpdate
CRM_Member_Form_MembershipTest.testCreatePendingWithMultipleTerms
CRM_Report_Form_Contribute_DetailTest.testReportOutput with data set #0
CRM_Report_Form_Contribute_DetailTest.testPostalCodeSearchReportOutput with data set #0
CRM_Report_Form_Contribute_DetailTest.testMultipleSoftCredits
CRM_Report_Form_Contribute_DetailTest.testContributeDetailReportWithNewColumnFromCustomTable

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
closing again for now - I've found a challenge in api_v3_MembershipTest.testActivityForCancelledContribution

**Comment by eileenmcnaughton** [comment]
CRM_Contribute_BAO_ContributionRecurTest.testAutoRenewalWhenOneMemberIsDeceased
CRM_Core_Payment_BaseIPNTest.testLoadMembershipObjectsLoadAll
CRM_Core_Payment_BaseIPNTest.testSendMailMembershipObjects
CRM_Core_Payment_BaseIPNTest.testSendMailMembershipObjectsNoLeakage
CRM_Core_Payment_BaseIPNTest.testSendMailMembershipWithoutLoadObjects
CRM_Core_Payment_BaseIPNTest.testThatCancellingEventPaymentWillCancelAllAdditionalPendingParticipantsAndCreateCancellationActivities
CRM_Event_BAO_ChangeFeeSelectionTest.testCRM19273
CRM_Event_BAO_ChangeFeeSelectionTest.testCRM17151
CRM_Event_Form_Registration_ConfirmTest.testPaidSubmit with data set #0
CRM_Event_Form_Registration_ConfirmTest.testPaidSubmit with data set #1
CRM_Event_Form_Registration_ConfirmTest.testTaxMultipleParticipant
CRM_Member_Form_MembershipTest.testContributionUpdateOnMembershipTypeChange
CRM_Member_Form_MembershipTest.testFinancialEntriesOnCancelledContribution
CRM_Member_Form_MembershipTest.testTwoInheritedMembershipsViaPriceSetInBackend
CRM_Member_Form_MembershipTest.testTwoMembershipsViaPriceSetInBackendWithDiscount
CRM_Member_Form_MembershipTest.testContributionFormStatusUpdate
CRM_Member_Form_MembershipTest.testCreatePendingWithMultipleTerms
api_v3_ACLPermissionTest.testEntitiesGetHookLimitingHookNoCheck with data set #0
api_v3_ACLPermissionTest.testEntitiesGetCoreACLLimitingHookNoCheck with data set #0
api_v3_ACLPermissionTest.testEntitiesGetCoreACLLimitingCheck with data set #0
api_v3_LineItemTest.testDeleteLineItem with data set "APIv3"
api_v3_LineItemTest.testDeleteLineItem with data set "APIv4"
api_v3_MembershipPaymentTest.testCreate
api_v3_MembershipPaymentTest.testGet
api_v3_MembershipTest.testActivityForCancelledContribution
api_v3_MembershipTest.testMultipleMembershipsContribution
api_v3_OrderTest.testCreateOrderIfTotalAmountDoesMatchLineItemsAmountsAndTaxSupplied
api_v3_OrderTest.testOrderWithMixedTax
api_v3_ProfileTest.testProfileSubmitMembershipBatch

**Comment by eileenmcnaughton** [comment]
We seem to be going backwards - I might have made the check stricter?

**Comment by eileenmcnaughton** [comment]
closing for now

**Pull request closed without merging**
