### PR TITLE
Update default is opt in merge rule to use latest cid value

### PR DESCRIPTION
**Pull request by wikimediaWfan**
Overview
----------------------------------------
_A brief description of the pull request. Keep technical jargon to a minimum. Hyperlink relevant discussions._

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by mlutfy** [comment]
hi @wikimediaWfan , thank you for the PR! Could you provide a bit more information on the issue being fixed? Steps to reproduce?

**Comment by wikimediaWfan** [comment]
Hi if you have two contact that needs merge with one opt_out true and one
opt_out false, then you click manual merge. We expect to see the checkbox
for this opt_out since value different. While now there is no checkbox
since we are not checking strict so true is equals to some string.

You could reproduce easily and with the patch, you will able to see
checkbox for opt_out

Sincerely,

Wenjun Fan

**Comment by mlutfy** [comment]
@wikimediaWfan Thanks for the steps to reproduce. Was it intentional to close this PR?

**Comment by wikimediaWfan** [comment]
Yeah. Get a cleaner pr and now merged https://github.com/civicrm/civicrm-core/pull/28160 thanks for asking :)
________________________________

**Comment by mlutfy** [comment]
@wikimediaWfan Excellent, thank you!

**Pull request closed without merging**
