### PR TITLE
SearchKit - Fix viewing search display for anonymous user

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes anonymous access to SearchKit displays.

Before
----------------------------------------
Anonymous user cannot view SearchKit display, even if it is set to bypass permission checks.

After
----------------------------------------
It works again.

Technical Details
----------------------------------------
This regressed in aa5d068b84f7ccd6370dd94339ecdc82c052a2c1 when the single SearchDisplay::run api call was replaced with an array of calls. The gatekeeper `CRM_Api4_Permission` was only able to handle single calls.
This updates it so that it can handle an array of calls - it will call `hook_civicrm_alterApiRoutePermissions` for each one and reject the request if any of them lack permission.

### CODE REVIEW

**Comment by totten** [comment]
I did some `r-run` on on 5.52+master and confirmed it fixed the problem.

To my reading, this improves support for `alterApiRoutePermissions` without altering the general security posture.

The conditional was a little mysterious at first - but after comparing the related code in `CRM_Api4_Page_AJAX::run()`, it seems to match-up. (Added notes to that effect.)

Merge on pass.

**Comment by eileenmcnaughton** [comment]
We haven't branched yet so I'm just wondering whether this is already merged to master (which is kinda the rc) - since we won't up-merge this branch

**Comment by colemanw** [comment]
@eileenmcnaughton the master branch version of this PR is at #24180

**Comment by totten** [comment]
Yeah, to minimize shuffling, we'll branch for 5.53-rc after the current batch of regression-fixes (circa 5.52.1) are merged into master+5.52.

**Pull request merged**
