### PR TITLE
CRM-20251 Make it easier to overwrite front end form help text regard…

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
…ing recurring

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
unrelated fail

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by adixon** [comment]
Very nice!

**Comment by eileenmcnaughton** [comment]
@adixon is that approval to merge?

**Comment by adixon** [comment]
Hmm, well, if you put it like that ... how about putting the getRecurringHelpText static function on the contribution object where a payment processor could override it?

**Comment by eileenmcnaughton** [comment]
I don't have a problem with that, but perhaps it should be more like 'getHelpText('recurring, array());

so it can support multiple, I don't really like passing around 'random' arrays, but I suppose the keys for each piece of text could be documented in the docblock.

**Comment by adixon** [comment]
I think you're proposing a general getHelpText method for the payment processor object, that can be re-used/expanded so that all help text can be customized per payment processor? That sounds excellent. If the method is NOT static, then it wouldn't need the recurring parameter, right? Or are there times where you want help text without a specific contribution? Hmm, I guess that starts getting a bit too icky, I'd go with the single associative array argument with defined keys that can be expanded over time.

**Comment by eileenmcnaughton** [comment]
@adixon what do you think of it now? I admit my distrust of people adding weird & wonderful undocumented things has come through in the way I implemented it .....

Note this can be overridden by the payment processor, but it can also be overridden in a std hook in any extension by assigning a value to the template.

**Comment by adixon** [comment]
You might regret asking, but I went ahead and have a slightly different version of your getText function version here:
https://github.com/civicrm/civicrm-core/compare/master...adixon:CRM-20251
I toned down your distrust a little bit with an eye to making it more readable and easier to add more contexts in the future and also tried to make the documentation consistent about what kind of strings this function is intended to handle. Somewhere we should document this for payment processors and provide a model for overriding. I was going to change your word 'context' because it's so overused, but I couldn't think of a better one.

**Comment by eileenmcnaughton** [comment]
Dang I tried to switch to yours but it has style errors

**Comment by eileenmcnaughton** [comment]
@adixon ok, your changes are incorporated in here now, and I agree they are improvements, despite my general hatred for 'switch' I agree it is right here

**Pull request merged**
