### PR TITLE
Add shortcodes for Personal Campaign Pages

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
@christianwach per discussion :-)

Before
----------------------------------------
No shortcodes for Personal Campaign Pages

After
----------------------------------------
Shortcodes for Personal Campaign Pages

Technical Details
----------------------------------------
To use  via UI you need https://github.com/civicrm/civicrm-wordpress/pull/185

Comments
----------------------------------------
Also ping @kcristiano

### CODE REVIEW

**Comment by kcristiano** [comment]
@mattwire This looks good, I'll give it an `r-run` as soon as I get a chance allong with 185 in civicrm-wordpress

**Comment by kcristiano** [comment]
https://github.com/civicrm/civicrm-wordpress/pull/185#issuecomment-598175338

I have given this and r-run and it looks good to merge.

**Comment by mattwire** [comment]
Marked merge on pass as has been reviewed by @kcristiano

**Comment by yashodha** [comment]
@mattwire looks good, merging this

**Pull request merged**
