### PR TITLE
CRM-21055,   Change the label of cancel button to close on Contribution form

### PR DESCRIPTION
**Pull request by pradpnayak**
----------------------------------------
* CRM-21055: Change label of cancel button
  https://issues.civicrm.org/jira/browse/CRM-21055

Overview
----------------------------------------
Change the label of cancel button to close on Contribution form

Before
----------------------------------------
before

After
----------------------------------------
after

### CODE REVIEW

**Comment by monishdeb** [comment]
@eileenmcnaughton @colemanw I will be merging this PR as this is just a text change.

**Comment by eileenmcnaughton** [comment]
Actually @monishdeb I think you should hold off & get @colemanw to double check this one. Technically it is trivial - but it's not clear to me if anyone would have a different opinion about the wording change (personally I'm neutral)

**Comment by colemanw** [comment]
Well, that button won't make much sense in a non-popup context. "Cancel" is the standard wording for pretty much all popups to close without saving.

**Comment by colemanw** [comment]
I'm guessing the motivation for this change is to disambiguate between cancelling a contribution, and closing the form without saving. Is that correct?
Can you give more details about where/how this is ambiguous in the current UI?

**Comment by lcdservices** [comment]
I think Close is more meaningful and less confusing. Close suggests no action is taking place -- which is what's actually happening. Cancel could have other connotations in this context.

**Comment by agileware** [comment]
Agree with @lcdservices "close" is a better term in this case.

**Pull request merged**
