### PR TITLE
Allow UFMatch to be used in SearchKit - this allows you to filter by eg. 'has a CMS account'

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Allow UFMatch to be used in SearchKit - this allows you to filter by eg. 'has a CMS account'

Before
----------------------------------------
Not possible to create searches that can filter by CMS user.

After
----------------------------------------
Can create searches that can filter by CMS user.

Technical Details
----------------------------------------
Change @searchable flag

Comments
----------------------------------------
Ping @colemanw @seamuslee001 @demeritcowboy

### CODE REVIEW

**Comment by colemanw** [comment]
I see the value of being able to search for contacts with a login, but I'm a little concerned about the usability of this:

1. At minimum, I think the `'Title'` of that entity (which gets set in `UfMatch.xml`) ought to be changed to something intelligible, e.g. "User Account".
2. Do you think the `domain_id` field is a potential gotcha? 

I'd be ok with merging this PR once the title is changed, but for the record I'll note an alternative approach which is to create a virtual search field on the Contact entity (maybe something like `user_account`) which could be directly searchable without needing any joins and without exposing this entity to SearchKit. Those virtual fields are pretty simple to add via SpecProvider. E.g. the contact `'age'` field: https://github.com/civicrm/civicrm-core/blob/c9ae8a39ff03936a06c636d57230d2e433e279c1/Civi/Api4/Service/Spec/Provider/ContactGetSpecProvider.php#L39-L48

**Comment by mlutfy** [comment]
I don't have a strong opinion, but keep in mind eventually CiviCRM Standalone may have a real "User Account" entity (for the login, password, authentication provider).

Having an api4 way of knowing if a contact has a user-account would be very useful, however (api3 has a pretty obscure syntax for that, which I always forget).

**Comment by mattwire** [comment]
@mlutfy I would think that a real "User Account" for standalone could still use the UFMatch entity? It could even use the UFMatch table to define that user - or use it as a mapping like all the other CMS integrations.

**Comment by colemanw** [comment]
Note that I'm not suggesting we change the DAO name or the API name of the entity, just the user-facing title :)

**Comment by demeritcowboy** [comment]
Fun fact: the `civicrm_uf_match` table used to be called `drupal`. We could rename the table back to drupal and dub standalone civi as "drupal classic", to capture all audiences.

**Comment by MegaphoneJon** [comment]
FWIW - I had the exact same need as Matt yesterday and independently made the same change to my code.  So this has been `r-run` successfully.

I'm fine with naming it whatever - "User Account", "User Account Mapping", "User Account Match" etc. all seem good to me.

**Comment by colemanw** [comment]
Ok, I've pushed up the title change & given this MOP.

**Comment by MegaphoneJon** [comment]
Hmm - this allows you to set "User Account" as the primary entity of a SK search, but you can't join to it from the contact table.  That's surprising to me because IIRC the code that builds the join list creates the reciprocal join without any changes to the Contact xml schema.

**Comment by petednz** [comment]
Maybe Jon's comment answers my question. On dmaster i was trying to do a Contact based search and add CMS user as a filter. Yes I see i can do it the other way round but the other thing i was needing to bring in were Drupal Roles, but suspect joining that is going to be CMS specific and hence .... out of scope? Goal (in case someone has a different suggestion other than Views which isn't working for this in d9 either!) is to show Drupal Users with a Role which they 'should' be getting from CiviMemberSynch but have been given manually (and hence incorrectly)

**Comment by colemanw** [comment]
@petednz @MegaphoneJon I've solved joins going the other way: #26109

**Pull request merged**
