### PR TITLE
Mailing location type default null

### PR DESCRIPTION
**Pull request by jmcclelland**

### CODE REVIEW

**Comment by davecivicrm** [comment]
I just upgraded a 4.5.6 site to 4.6.beta1 and this ALTER TABLE statement throws a fatal error because the two mailings I had in that site had 0 in civicrm_mailing.location_type_id.

I'm thinking we need to add a statement to set location_type_id = NULL if location_type_id = 0 before we add the FK. Does that make sense? Alternative thoughts?

**Comment by totten** [comment]
Yes, we should do UPDATE civicrm_mailing SET location_type_id = NULL WHERE location_type_id = 0 before adding FK.

**Comment by totten** [comment]
Reproduced the problem locally; this PR fixes for me: https://github.com/civicrm/civicrm-core/pull/5208

**Comment by jmcclelland** [comment]
Thank you for finding that error! Sorry I missed that use case.

**Pull request merged**
