### PR TITLE
CRM-20811 CIVICRM-167 Schedule Reminders uses mixed terminology for Active state

### PR DESCRIPTION
**Pull request by ghost**
Simple PR to make CiviCRM easier to understand for new users.

See https://issues.civicrm.org/jira/browse/CRM-20811

### CODE REVIEW

**Comment by agileware** [comment]
@seamuslee001 would you mind reviewing when you are free?

**Comment by seamuslee001** [comment]
Sure, is the idea here to not worry about SMS v Email just that scheduled reminder is active?

**Comment by agileware** [comment]
@seamuslee001 yes, just that scheduled reminder is active

**Comment by agileware** [comment]
What are the chances of getting this PR merged?

**Comment by totten** [comment]
FWIW, the original design anticipated that the scheduling mechanism would be useful with several triggers (besides sending a basic email). You'd want to run the scheduling logic (querying various date fields; flagging records that have been visited; etc) but skip the email logic -- instead, maybe fire a hook, fire CiviMail, ping a web-service, or execute some custom logic.

But... I think your interpretation is probably more accurate... if you set `is_active=0`, then it looks like the logic in `CRM/Core/BAO/ActionSchedule.php` will basically ignore the scheduled-reminder (as suggested by skimming `processQueue()`, `buildRecipientContacts()` and `sendMailings()` in ).

There was a project/extension from Veda which did something about sending scheduled reminders in a different way. I don't remember how it worked, but might ping @veda-consulting @deepak-srivastava to see if the change is consistent with their approach.

**Comment by agileware** [comment]
@totten thanks for reviewing and providing feedback

**Comment by jusfreeman** [comment]
Still interested in getting this PR reviewed and committed. Anyone happy to support this PR?

**Comment by eileenmcnaughton** [comment]
I'm going to merge this - it makes sense to me as being clearer

**Pull request merged**
