### PR TITLE
(dev/core#656) unreleased regression - attendee report generates unde…

### PR DESCRIPTION
**Pull request by yashodha**
…fined property notice

Overview
----------------------------------------

You can replicate this on dmaster demo by clicking "Refresh Results" on the "Attendee List" report.  You'll get this notice once per contact:

`Notice: Undefined property: CRM_Report_Form_Event_ParticipantListing::$campaigns in CRM_Report_Form_Event_ParticipantListing->alterDisplay() (line 748 of /srv/buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Report/Form/Event/ParticipantListing.php).
`

Before
----------------------------------------
Lots of notices.

After
----------------------------------------
No notice.

### CODE REVIEW

**Comment by yashodha** [comment]
@seamuslee001 

Can you please confirm?

**Comment by yashodha** [comment]
test this please

**Comment by seamuslee001** [comment]
@yashodha can you please rebase this and put it against the 5.10 branch please

**Comment by seamuslee001** [comment]
also @yashodha why not put this in `CRM/Report/Form.php` instead?

**Comment by seamuslee001** [comment]
i have tested this and confirmed it works, it should be fixed in the RC (5.10) and i think the better place for this var would be in the CRM/Report/Form.php as that is where the rest of the campaigns code is. thoughts @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
@yashodha I've confirmed this affects 5.10 so yes please against 5.10 rc - I'm agnostic about whether it goes on this class or the form class but perhaps we should test a few more forms

**Comment by yashodha** [comment]
@eileenmcnaughton @seamuslee001 

The regression was introduced in https://github.com/civicrm/civicrm-core/pull/13376/files#diff-130d6592c75a141c7859d21177fc884dL41 only for this report. Undoing the same with this PR.

**Comment by eileenmcnaughton** [comment]
@yashodha I changed the base so it's against the rc - but can you get rid of the changes that are not to go in the rc now

**Comment by seamuslee001** [comment]
closing infavor of #13445

**Pull request closed without merging**
