### PR TITLE
Re-Fix Case form task  (export/print not working) (replace quick fix with proper fix)

### PR DESCRIPTION
**Pull request by mattwire**
…itched to using CRM_Core_Form_Task

@eileenmcnaughton @seamuslee001 @colemanw I think this is the correct fix for #11928 and #11926

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire thanks - did you check how that relates to the outstanding issue (print case to pdf only prints first case) - wondering if it fixes it

**Comment by seamuslee001** [comment]
@mattwire thanks for this, it mostly works except for not when you include a case token in the letter. 

this is code that for me makes the case tokens work. It is very much not elegant enough however we need to some how pass $this->caseIds through the reason being is that the PDF code assumes we may have a case id see https://github.com/civicrm/civicrm-core/blob/master/CRM/Contact/Form/Task/PDF.php#L61 https://github.com/civicrm/civicrm-core/blob/master/CRM/Contact/Form/Task/PDF.php#L122 and more importantly https://github.com/civicrm/civicrm-core/blob/master/CRM/Contact/Form/Task/PDFLetterCommon.php#L401 

I suppose they could be swapped to entityIds i guess but we would still need code to know to handle the call to replaceCaseTokens etc

```php
diff --git a/CRM/Core/Form/Task.php b/CRM/Core/Form/Task.php
index 15de89cf78..e6df412ee3 100644
--- a/CRM/Core/Form/Task.php
+++ b/CRM/Core/Form/Task.php
@@ -70,6 +70,13 @@ abstract class CRM_Core_Form_Task extends CRM_Core_Form {
    */
   public $_contactIds;

+  /**
+   * The array that holds all the case ids for use in PDF letters to sort tokens
+   *
+   * @var array
+   */
+  public $_caseIds;
+
   // Must be set to entity table name (eg. civicrm_participant) by child class
   static $tableName = NULL;
   // Must be set to entity shortname (eg. event)
@@ -136,6 +143,10 @@ abstract class CRM_Core_Form_Task extends CRM_Core_Form {

     $form->_entityIds = $form->_componentIds = $ids;

+    if ($form::$entityShortname == 'case') {
+      $form->_caseIds = $form->_entityIds;
+    }
+
     //set the context for redirection for any task actions
     $qfKey = CRM_Utils_Request::retrieve('qfKey', 'String', $form);
     $urlParams = 'force=1';
```

**Comment by mattwire** [comment]
@seamuslee001 Thanks for testing.  I've just pushed a slightly more generic fix based on your proposed fix - can you confirm if that works for you  - it seems to work here!

@eileenmcnaughton It doesn't fix the "only prints one PDF" but this PR should do: #11946

**Comment by eileenmcnaughton** [comment]
@mattwire @seamuslee001 what is the status here? I thought we merged fixes for these bugs? If this is a fix we need to clarify steps to replicate. If it is a follow up tidy up it might be better dropped for now as we have a tonne of similar on our plate & this code seem to have settled down....

**Comment by mattwire** [comment]
@eileenmcnaughton @seamuslee001 It just needs testing and it should be good to go.  It is a follow-up to the quick fix that was committed before (which temporarily undid a lot of the core task abstraction work that I've done), so I think it is important to get it reviewed and back into core.  We are constantly fighting with messy old code and this helps clear out that old code, reduce duplication and allow for generic tests to be written in the future rather than entity specific ones.  For example it will eventually help with things like this: https://github.com/civicrm/civicrm-core/pull/12048

**Comment by eileenmcnaughton** [comment]
OK @seamuslee001 @colemanw I feel both of you got closer to the regressions on this - do either of you feel ok to review this?

**Comment by seamuslee001** [comment]
(*CiviCRM Review Template WORD-1.1*)



* ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) Pass
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) Pass
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) Pass
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) Pass
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) Pass
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) Pass i tested on a demo civicrm instance exporting a PDF with case tokens and also a csv primary fields export. Given the code the export function touches on i also tested doing a contribute primary fields export and confirmed that worked as expected. I also tested seeing what fields were on offer for the select fields in the contribute export and confirmed it makes sense
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) Pass
* ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) Pass

**Comment by seamuslee001** [comment]
Merging

**Comment by eileenmcnaughton** [comment]
Thanks @seamuslee001 @mattwire

**Comment by agh1** [comment]
Quick cross-reference: I believe this is for [dev/core#8](https://lab.civicrm.org/dev/core/issues/8)

**Pull request merged**
