### PR TITLE
CRM-19692: Fix js error on Submit Credit Card Contribution form

### PR DESCRIPTION
**Pull request by jitendrapurohit**
* [CRM-19692: Cannot select Priceset in Backend: Contributions: Submit Credit Card Contribution](https://issues.civicrm.org/jira/browse/CRM-19692)

### CODE REVIEW

**Comment by KarinG** [comment]
Hi - I pulled over this afternoon's civicrm-4.7.14-drupal-20161129.tar.gz
 + cleared all drupal and civicrm caches

But I am still not able to get a priceset to work in Backed: Contributions: Submit Credit Card Contribution - Errors in Firebug Console: 

SyntaxError: missing } after function body
ReferenceError: buildAmount is not defined

backendps

**Comment by KarinG** [comment]
Is it possible that perhaps your fixes are not in the rc yet?

**Comment by KarinG** [comment]
Yes no diff (yet):
karins-macbook-pro:Downloads sysadmin$ diff civicrm_nov28rc/templates/CRM/Contribute/Form/Contribution.tpl  civicrm_nov29rc/templates/CRM/Contribute/Form/Contribution.tpl 
karins-macbook-pro:Downloads sysadmin$

**Comment by eileenmcnaughton** [comment]
@karing this is not merged so will not be in the rc

**Comment by eileenmcnaughton** [comment]
(also PR is against master not the rc)

**Comment by KarinG** [comment]
It has a purple merge button? I can see it was against master - not rc.

**Comment by eileenmcnaughton** [comment]
It has a green merge button for me...

Since you have described this as a regression I would consider it for the rc if you manage to test it & @jitendrapurohit confirms he feels comfortable with that.

**Comment by jitendrapurohit** [comment]
Agree that it should be merged into rc. I've raised fix at https://github.com/civicrm/civicrm-core/pull/9469

**Comment by jitendrapurohit** [comment]
closing in favor of #9469

**Pull request closed without merging**
