### PR TITLE
[NFC] Add test on buildMembershipTypeValues & cleanup class

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Cleanup on test class + add a new test - I found the class wasn't running reliably in isolation so had to strip out some invalid things

Before
----------------------------------------
Various code nastinesses - cleanup issues, wrong params passed, unnecessary double quotes. Incorrect setup resulting in invalid financial entities (line items, transaction)

After
----------------------------------------
Improved, uses order api

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton test failures related?

**Comment by yashodha** [comment]
@eileenmcnaughton It looks like tests are failing again.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
unrelated fail

**Comment by seamuslee001** [comment]
Looks fine mostly just test changes merging

**Pull request merged**
