### PR TITLE
searchui : new screen label format

### PR DESCRIPTION
**Pull request by wyde22**
Overview
----------------------------------------
_A brief description of the pull request. Keep technical jargon to a minimum. Hyperlink relevant discussions._
here i create a new screen of listing of label format `civicrm/admin/labelFormats` for searchkit ui

Before
----------------------------------------
old interface quickform

After
----------------------------------------
new interface with searchkit and formbuilder

Technical Details
----------------------------------------

Comments
----------------------------------------
The link in actions button keep the old interface for the moment

### CODE REVIEW

**Comment by aydun** [comment]
Jenkins add to whitelist

**Comment by aydun** [comment]
Test this please

**Comment by aydun** [comment]
Test this please

**Comment by christianwach** [comment]
@aydun I think this may have been merged without proper testing or something has changed since merging. The new layout doesn't work for me at all in WordPress:

Screenshot 2024-01-22 at 10 11 49

I fixed the internal link in #29065 FYI.

**Comment by christianwach** [comment]
> I think this may have been merged without proper testing or something has changed since merging.

FWIW, [this screen requires Smarty3](https://lab.civicrm.org/dev/core/-/issues/3912#note_157144)

**Pull request merged**
