### PR TITLE
backport for CRM-21014

### PR DESCRIPTION
**Pull request by jackrabbithanna**
* [CRM-21014](https://issues.civicrm.org/jira/browse/CRM-21014)

### CODE REVIEW

**Comment by jackrabbithanna** [comment]
Jenkins re-test this please

**Comment by jackrabbithanna** [comment]
@eileenmcnaughton I'm not sure I understand why the build fails on this PR....it had conflicted with a previous PR slightly, I resolved the merge conflict, and it says this branch has no conflicts with the base branch.  Do you know what I'm doing wrong?

**Comment by seamuslee001** [comment]
@jackrabbithanna Mark can you try doing git pull --rebase <core alias> 4.6 for this branch?

**Comment by jackrabbithanna** [comment]
@seamuslee001 so when trying to do that on my local, which has my fork checked out, it tells me:
fatal: '4.6' does not appear to be a git repository
fatal: Could not read from remote repository.

Should I have civicrm/civicrm-core cloned and do that?

**Comment by seamuslee001** [comment]
@jackrabbithanna forgot before 4.6 put in the alias for civicrm/civicrm-core something like core etc what ever its that is the upstream source you want to "pull" that to your fork --rebasing

**Comment by jackrabbithanna** [comment]
thanks @seamuslee001  :)

**Comment by jackrabbithanna** [comment]
Or I must have fouled it up somehow...Don't suppose there's some right documentation somewhere of what I'm trying to accomplish?

**Comment by seamuslee001** [comment]
@jackrabbithanna just looked at the code from core at the moment and i don't think this PR is needed any more because its escaped

**Comment by eileenmcnaughton** [comment]
When in doubt rebase & squash

**Comment by jackrabbithanna** [comment]
well there was a escape that smaden did, and then eileen later came long and added ':html' in another PR...so this was to match it up....I could close and just redo this patch with a new PR, but I would like to understand why when there are no conflicts it says there are conflicts.....I guess my git-fu needs a little more -fu

**Comment by eileenmcnaughton** [comment]
If you get to the bottom of it let us know :-)

In the meantime try rebasing it with the -i interactive to schmooze it into 1 commit

**Comment by seamuslee001** [comment]
I think its also worth noting for smarty purposes @jackrabbithanna |escape = |escape:'html'  as per https://www.smarty.net/docsv2/en/language.modifier.escape "escape is used to encode or escape a variable to for example html, url, single quotes, hex, hexentity, javascript and mail. By default its html."

**Comment by jackrabbithanna** [comment]
So sounds to be @seamuslee001 the only reason this would be necessary is to keep in sync with 4.7, would just close it out otherwise....I'll probably just create another PR to get this in if necessary

**Comment by jackrabbithanna** [comment]
Looked at master, and it looks like the :'html' is out of master
https://github.com/civicrm/civicrm-core/blob/master/templates/CRM/Contribute/Form/Contribution/PremiumBlock.tpl#L70

So this PR is not necessary, closing

**Pull request closed without merging**
