### PR TITLE
Towards using EntityForm.tpl for Membership type & enabling custom data

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
We now have a standard for enabling custom data on a form that does not currently support it - ie. by using the EntityForm.tpl. The membership type form is partially converted & this takes that a bit further

Before
----------------------------------------
No UI change. Less usage of metadata

After
----------------------------------------
No UI change, more usage of metadata

Technical Details
----------------------------------------
There are 2 things to progress to switch the form over
1) removing fieldAdd type stuff from buildForm
2) removing field specific stuff from the tpl

This does a bit of both. It's mostly aimed at reducing some of the 'noise' to find the real issues in the conversion. So far I have spotted the auto-renew text might be a problem. I think the metadata will handle it as written but I haven't tested much and there is nothing in Field.tpl to cope with putting 2 fields on the same row which is the next challenge.

- note the js can stay in the tpl after the entity form inclusion - this slight change in html structure should not impact the js as it uses field ids not html markup.

Comments
----------------------------------------
@mattwire do you want to take a look - it's just another incremental step & a way to break this down into more manageable chunks

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Just a quick note that I tested the l10n  part - before & after both like 
screenshot 2018-07-30 10 58 59

@mattwire do you want to check this & we can get this merged & then look at 'the next field off the block' - which is autorenew. I haven't done before & afters on that field without a processor enabled yet

**Comment by mattwire** [comment]
* ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) Pass
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) Pass
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) Pass
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) Pass
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) Pass (easier to maintain)
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) Pass (no change)
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) Pass (no change)
* ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) Pass (easier to maintain)

**Comment by mattwire** [comment]
Ok to merge @seamuslee001 @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
thanks @mattwire

**Pull request merged**
