### PR TITLE
CRM-19081 Add test to demonstrate breakage

### PR DESCRIPTION
**Pull request by seamuslee001**
@eileenmcnaughton This demonstrates the breakage i was generating on the state province thing, Still unsure how to properly patch it

---
- [CRM-19081: Support Legacy Search Builder stateProvince Field](https://issues.civicrm.org/jira/browse/CRM-19081)

### CODE REVIEW

**Comment by totten** [comment]
jenkins, test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 trying to get my head around this - the presence of mapping_id causes it to follow a different path than it would without a mapping id. It seems mapping id is used in the following cases:

- import
- export
- search builder

I assume you are working from a group that fits into the latter category?

**Comment by seamuslee001** [comment]
Yes

**Comment by eileenmcnaughton** [comment]
Replacement PR #8890

**Pull request closed without merging**
