### PR TITLE
crm-16954-change-to-next-30-90-last-90-days

### PR DESCRIPTION
**Pull request by joannechester**
Just checking if it breaks any tests, not for merging yet

### CODE REVIEW

**Comment by joannechester** [comment]
How can I find out what has caused the fail for this?  It is not obvious form the Jenkins report..

**Comment by davecivicrm** [comment]
Jenkins, test this please.

**Comment by davecivicrm** [comment]
CRM-16195 has been pushed to 4.8+ based on last conversation between Jon and Coleman. So if there are ready and PR tests pass this time - we can merge.

The mysterious failure (no failures shown in report) was caused by a FATAL in one of the tests. Tim found that by browsing the 'Console' from the PR test report. A fix for that has been merged.

**Comment by joannechester** [comment]
this is the PR for https://issues.civicrm.org/jira/browse/CRM-16954

**Comment by totten** [comment]
It looks like the latest commit (fa95fd8) was tested in https://test.civicrm.org/job/CiviCRM-Core-PR/5176/ , which passed. The Github status is currently weird (stuck on gold with no pending Jenkins jobs).

**Comment by joannechester** [comment]
Jenkins test this please

**Comment by davecivicrm** [comment]
I'm going to just merge this since it had already passed.

**Pull request merged**
