### PR TITLE
Fix JS Error for Free event with multiple participant on registration…

### PR DESCRIPTION
**Pull request by sunilpawar**
Overview
----------------------------------------
When the event is Non Paid Event (Free) and enabled for `Register multiple participants`.

On the Registration screen when a user changes an additional participant through the select field (`How many people are you registering?`), we get a JS error on the browser console.

Screenshot 2021-12-23 at 2 06 06 PM

Before
----------------------------------------
JS Error

After
----------------------------------------
No JS Error, checking function exist or not before calling it.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
The fix seems to be the same as elsewhere - it is probably worth adding a code comment to explain what would fail without the if

image

**Comment by eileenmcnaughton** [comment]
@sunilpawar I've given this merge on pass - but tests are failing https://test.civicrm.org/job/CiviCRM-Core-PR/46004/

can try again test this please

**Comment by yashodha** [comment]
@sunilpawar Can you please squash the commits for merge?

**Comment by sunilpawar** [comment]
@eileenmcnaughton , test failed not related to JS fix..

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by sunilpawar** [comment]
squashed commit

**Pull request merged**
