### PR TITLE
Remove require_dev yoast/phpunit-polyfills

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Remove require_dev yoast/phpunit-polyfills

Before
----------------------------------------
We added it

After
----------------------------------------
We un-added it

Technical Details
----------------------------------------
@demeritcowboy @seamuslee001 as discussed we are backing out this addition.

It was merged to 5.60 so we should back out here - but up-merging it will require some jiggery pokery

Comments
----------------------------------------

### CODE REVIEW

**Comment by demeritcowboy** [comment]
I'm ok to merge to 5.60 but if it will make upmerging easier it should be ok to leave it in 5.60 and just remove in master since it's not used anywhere.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy when I unzipped the tarball into our CI it causes out tests to fall over because as a by-product it pulled in a version of `phpunit` that differed from ours

**Comment by demeritcowboy** [comment]
Ok.
Why are we using composer again?

**Comment by eileenmcnaughton** [comment]
lol

**Pull request merged**
