### PR TITLE
Smarty variables]  Remove isset from a.net

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Remove isset from a.net

Before
----------------------------------------
fatals with default escaping

After
----------------------------------------
always assigned

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
unrelated fail test this please

api\v4\Action\DateTest::testRelativeDateRanges
Failed asserting that an array contains 9.

/home/jenkins/bknix-dfl/build/core-22191-36u0c/web/sites/all/modules/civicrm/tests/phpunit/api/v4/Action/DateTest.php:96
/home/jenkins/bknix-dfl/extern/phpunit8/phpunit8.phar:671

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Comment by seamuslee001** [comment]
This seems fine to me

**Pull request merged**
