### PR TITLE
dev/core#567 Fix missing field when using basic contribution page for multiple contributions.

### PR DESCRIPTION
**Pull request by X-sam**
Overview
----------------------------------------
This addresses a minor oversight in the behavior of basic contribution pages which contributed to recurring memberships not getting properly charged after the first contribution.

Before
----------------------------------------
Previously, when an organization set up a contribution page containing both membership signup and standard donation contributions, the memberships would not auto-renew despite consumers choosing the auto-renew option.

After
----------------------------------------
Memberships with auto-renew selected on contribution pages containing multiple streams result in proper recurring charges.

Technical Details
----------------------------------------
Previously, in situations where `processSecondaryFinancialTransaction` was invoked on a contribution form, calls to the payment processor `doPayment` function would not receive `contributionRecurID` in the `params`, regardless of whether the membership was created with a recurrence (also referred to as "auto-renew" in some contexts). This caused our processor, iATS, to treat such membership signups as one-offs, despite the backend seeming to indicate that there were recurring contributions- showing correctly on contact pages and everything.  

Comments
----------------------------------------
It is possible there are other scenarios which similarly lack proper hydration of this variable prior to invocation of `doPayment`, as we've noted other strangeness around manipulating recurring contributions– I'm keeping an eye out but I feel they'd be out of scope for this PR either way.

### CODE REVIEW

**Comment by mattwire** [comment]
Hi @X-sam thanks for submitting this PR. I've marked as "needs test" because we need to make sure that it does not break in the future. I think this is your first pull request so I realise that may be harder to jump straight into writing tests - there is documentation here https://docs.civicrm.org/dev/en/latest/testing/phpunit/ and you'd probably be able to copy/extend an existing contribution page test.

Maybe @eileenmcnaughton @seamuslee001 @jitendrapurohit could point you in the right direction?

**Comment by eileenmcnaughton** [comment]
add to whitelist

**Comment by eileenmcnaughton** [comment]
jenkins, test this please

**Comment by eileenmcnaughton** [comment]
@mattwire is right that we would want a test on this - it seems to have stalled previously on the need for a test https://lab.civicrm.org/dev/core/-/issues/567

Initial test fails are actual style fails 

image

**Comment by X-sam** [comment]
I'm not a PHP dev and I don't know enough about your tooling to help much in that regard, I'm afraid.

**Comment by jaapjansma** [comment]
@X-sam no problem. Lets see if @mattwire is able to write a unit test. If not we might review this next time we our doing reviews of PR's.

**Comment by jaapjansma** [comment]
test this please

**Comment by jaapjansma** [comment]
@X-sam can you check this PR it has merge conflicts so it is not possible to merge this. If you could fix that we could then review it. 
My suggestion is that this does not need a test and none of the people who think this needs a test did reach out to you to help you.

**Comment by jaapjansma** [comment]
@X-sam thanks a lot. However the unit tests still fails with an error it could not apply your patch. 

This is the error message from the unit test:

```

Process failed:                                                                          
  [[ COMMAND: git am --ignore-whitespace ]]                                                
  [[ CWD: /home/jenkins/bknix-dfl/build/core-22100-2i2gh/web/sites/all/modules/civicrm ]]  
  [[ EXIT CODE: 128 ]]                                                                     
  [[ STDOUT ]]                                                                             
  Applying: Fix bug in secondary membership processing behavior.                           
  Patch failed at 0001 Fix bug in secondary membership processing behavior.                
  When you have resolved this problem, run "git am --continue".                            
  If you prefer to skip this patch, run "git am --skip" instead.                           
  To restore the original branch and stop patching, run "git am --abort".                  
  [[ STDERR ]]                                                                             
  .git/rebase-apply/patch:36: trailing whitespace.                                         
      $result = [];                                                                        
  error: patch failed: CRM/Contribute/Form/Contribution/Confirm.php:1128                   
  error: CRM/Contribute/Form/Contribution/Confirm.php: patch does not apply                
  hint: Use 'git am --show-current-patch=diff' to see the failed patch  

```

**Comment by eileenmcnaughton** [comment]
@X-sam - I think if you squashed the commits it would fix it - it might be easiest to
```
git fetch origin
git reset origin/master
```
And then re-add your changes with

`git add -p`

& then re-do your commit & then `git push` with the `-f` switch to force it

**Comment by eileenmcnaughton** [comment]
This has stalled in the context of github - let's track through gitlab -https://lab.civicrm.org/dev/core/-/issues/567

**Pull request closed without merging**
