### PR TITLE
(WIP) Exploratory branch for composer/D8 builds

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------
This is an exploratory branch with patches needed for (a) building Civi-D8 from git+composer, (b) running GenCode, (c) running unit tests. It is used by https://github.com/civicrm/civicrm-buildkit/pull/496, and I'm opening as a PR so that we see test-runs and have Github generate diff files.

I expect that parts will eventually be broken out as smaller PRs for `master`. The branch is  based on `5.21` because I need to be able to try out builds on a couple different versions (b/c the QA processes will need to be able to test multiple versions).

As an exploratory branch, it may be substantively changed without notice (commits added/rearranged/squashed/removed/rebased).

### CODE REVIEW

**Comment by jackrabbithanna** [comment]
Ooh this will be mana from heaven. Let me know if you want some testing on some issues. 

I have an issue only with 5.21 (last I tried was 5.18 before that), where APIv4 explorer or ajax endpoint would throw an exception about permissions or something, even with uid:1 superuser .. and couldn't get it to work. I wonder if something in here that can help that. I hadn't been hardcoding global $civicrm_paths['civicrm_paths']['civicrm.packages'] .. now I wonder if I should have been.

Is there an existing gitlab issue the changes in CRM_Core_Classloader are for?

I've also had some success and a few issues running Drupal 8.8's Core PHPUnit Functional Javascript (Webdriver) tests with CiviCRM. I got it all basically working but there's also an issue installing the APIv4 extension programmatically in a test, and Civi being able to find the APIv4 classes (this is 5.13). I do programmatically clear caches enough to get all other extensions I've tried work, like Mosaico, CiviDiscount, etc..  But everything else works seems to work so far which is awesome .. Drupal 8 Core test infrastructure is an option for doing CiviCRM tests, at least Chromedriver / Webdriver tests. I had to some special stuff in setUp() .. like update civicrm.settings.php and put in settings overrides for global $civicrm_paths,  and patch civicrm.install in the D8 module a tad. For each test it installs CiviCRM fresh.

Could be totally unrelated to any of the commits you're working on for either issue IDK.

Our way of installing with composer is to start with an ESR version tarball, remove the ./vendor and ./drupal directories .. and then committing that to a private repo, create tag, and alter where composer pulls civicrm/civicrm-core from in the Drupal 8.8 repo root composer.json "repositories" section. I'd patch our repo's version of the core files and build a fresh site.

 If there's a different way you want tested that would help, I'm game for that too.

**Comment by totten** [comment]
> Is there an existing gitlab issue the changes in CRM_Core_Classloader are for?

Gitlab issue - no.

This round of "exploration" is stabilizing, though, so I'll split the changes into some smaller PRs so that there can be more description/discussion.

>  I hadn't been hardcoding global $civicrm_paths['civicrm_paths']['civicrm.packages'] .. now I wonder if I should have been.

Right, let me try to comment on when one would or would-not care about using that:

* If one downloads `civicrm-packages` with a vanilla `composer require civicrm/civicrm-packages`, then it will placed per composer's preferred file structure (`vendor/civicrm/civicrm-packages`) rather than Civi's traditional structure (`$civicrm_root/packages`). This would be a case to use `$civicrm_paths['civicrm.packages']`. (Note: Preferrably that's [automatic](https://lab.civicrm.org/dev/civicrm-asset-plugin/blob/master/README.md#generated-variables)...)
* If you find a mix of build options/plugins/etc which matches the traditional file structure (`$civicrm_root/packages`), then it should not be necessary.

> I've also had some success and a few issues running Drupal 8.8's Core PHPUnit Functional Javascript (Webdriver) tests with CiviCRM...

Nice to hear! D8's test framework is a bit out of my purview right now (e.g. I'm working to get Civi's E2E/API/headless test suites to run on D8), but doing tests which invoke multiple frameworks can be fiddly, so I totally relate.

**Comment by totten** [comment]
So I just want to describe a bit about the disposition of this exploratory branch and its sibling https://github.com/civicrm/civicrm-buildkit/pull/496

Basically, I've been sprinting with a view towards supporting D8 on our CI, which basically means that commands like this work:

```bash
civibuild create mysite --type drupal8-clean --civi-ver master
civi-test-run -b mysite -j /tmp/junit phpunit-api4 phpunit-e2e
```

`civibuild create` decomposes in two parts, `download` and `install`.  My first QA matrix focused on getting those commands to execute and produce a site where you can login as admin/demo users. It's been a week or so since I re-ran this particular matrix, but it was good last time:

```
                download.sh     install.sh      login-admin     login-demo      view-civicrm-dashboard  civicrm-perms
drupal8-empty   ok              ok              ok              ok              na                      na
drupal8-clean   ok              ok              ok              ok              ok                      ok
d8prj-empty     ok              ok              ok              ok              na                      na
d8prj-clean     ok              ok              ok              ok              ok                      ok
d8prj-re        ok              ok              ok              ok              ok                      ok
```

For the `*-clean` build types which include CiviCRM's code from git, I expanded the matrix to include (a) some obvious bugs that cropped on the new build-types and (b) executing tests.  After a number of revisions, the matrix is now at:

```
                        login-demo      menu    /civicrm        Test:E2E/Core   Test:api4               Test:UpgradeData        civicrm.settings.d
drupal8-clean@5.21      ok              ok      ok              ok-but-l10n     ok                      not-supported           ok
d8prj-clean@5.21        ok              ok      ok              ok-but-l10n     ok-but-warns            not-supported           ok
```

The test suites aren't running perfectly - there are failures. But I think it's cogent enough to make CI test sites and local dev sites from Civi's git repos - and run most tests on them.

So I think it's time to close out this "exploratory branch" - splitting the patches into smaller PRs for review and filing issues on known/identified problems.

**Comment by eileenmcnaughton** [comment]
@totten - per comment in chat I think the above is useful information to people following progress on this & it should be 'somewhere' - probably a  gitlab. However, closing  this PR now as it has been otherwise dealt with

**Pull request closed without merging**
