### PR TITLE
[REF] Refactor text fields in price sets

### PR DESCRIPTION
**Pull request by larssandergreen**
Overview
----------------------------------------
Following up on #26375, this refactors the display of text fields in price sets.

Before
----------------------------------------
Text fields are partly put together in the BAO and partly in the tpl. As all the other kinds of price fields are put together exclusively in the BAO, this is confusing and hard to maintain. It also causes sold out options to be labelled (Sold Out) twice.

After
----------------------------------------
No change except sold out options are only labelled once.

Technical Details
----------------------------------------
Text price fields are kind of weird in that they are both fields and options at the same time, so there is a little bit of a work around in here for the labels. Not ideal, but I think it's a reasonable way around that weirdness.

Comments
----------------------------------------
Also makes the new `buildPriceOptionText()` from the previous PR protected.

After this one, the next step will actually improve functionality.

### CODE REVIEW

**Comment by larssandergreen** [comment]
Another GroupTest failure
jenkins test this please

**Comment by larssandergreen** [comment]
Now testPcpReportTotals failing, also seen a few of those
jenkins test this please

**Comment by eileenmcnaughton** [comment]
Tests passed now I think

**Comment by larssandergreen** [comment]
@eileenmcnaughton Thanks, I did this one a while ago and now reading it over here, I think I should revise it as it seems a little janky, so it's a draft for right now.

**Comment by larssandergreen** [comment]
@eileenmcnaughton Actually, would you mind taking a look at this? Basically, it would be nice to be able to build the label that goes after the field with the amount and such in the BAO for text fields, same as we do for the options for all the other elements — rather than building it in the tpl as we do currently with a bunch of conditionals. That's not only to simplify things in general, but my end goal here is to show the number of spaces remaining in each option in the label. But since we already have a label for the text field (the one that ends up to the left of it), I can't see any way to get QuickForm to carry that second label through to the form for us.

That's why I devised this hacky method to carry the second label on a second element that otherwise does nothing. I'm not sure if that's too messy and would appreciate your thoughts.

**Comment by eileenmcnaughton** [comment]
@larssandergreen ok I'll see what I can make of it

**Comment by demeritcowboy** [comment]
This might still be true but has conflicts and is almost a year old. Going to close.

**Comment by eileenmcnaughton** [comment]
@larssandergreen I do have this vaguely in the back of my mind - do we have the objective tracked on gitlab - maybe it might be progressed next week in Hamburg

**Pull request closed without merging**
