### PR TITLE
Standardise implementation of financial type acl in query object

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Standardise implementation of financial type acl in query object

This fixes it to call the selectWhere in the BAO_Query, as apiv4 does. There is test cover in the touched test.

Before
----------------------------------------
Financial ACLs applied deep in the query object

After
----------------------------------------
Applied via the selectWhere hook

Technical Details
----------------------------------------

The primary goal here is to get this logic out of core & to disable this extension on most sites with a view to moving the whole extension out of core in time - especially as we have just hit an issue with this extension requiring civi-contribution & causing problems with sites that disable civi-contribute

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton these test fails seem to relate 

[Test Result](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/8262/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/) (2 failures / +2)
[Civi\Financialacls\LineItemTest.testLineItemApiPermissions with data set "APIv3"](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/8262/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Financialacls_LineItemTest/testLineItemApiPermissions_with_data_set__APIv3_/)
[Civi\Financialacls\LineItemTest.testLineItemApiPermissions with data set "APIv4"](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/8262/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Financialacls_LineItemTest/testLineItemApiPermissions_with_data_set__APIv4_/)

**Comment by eileenmcnaughton** [comment]
OK - so this changes the behaviour a little 

status quo
apiv4
- can load line items if the specific line item AND the contribution is permitted
- contribution is permitted if the financial type is permitted


apiv3 & BAO select 
 - - can load line items if the specific line item AND the contribution has a permitted function type, ie some but not all line items would be loaded from a permitted contribution
- contribution is permitted if the financial type is permitted AND ALL the line items are permittted (possibly inconsistently but at least in some usages of it)

This makes them the same ie LineItem get only works if ALL line items on the contribution are accessible & contribution get only retieves if ALL line items are accessible


I think we need to standardise on one of 3 options

1) LineItem get gets the line items, regardless of whether the Contribution in it's entity is accessible (makes more sense for reporting to me, Contribution.get requires all line items to be accessible.
2) Contribution.get does not require all line items to be accessible to return the contribution but rather at least one  
3) Contribution.get does not require all line items to be accessible to return the contribution but rather the financial type id of the contribution is used

The amount of work to go down any of these 3 paths at this point is similar - since 1 is the hardest & it is done in this PR & only requires a test tweak to get it through

I do note however that they are not equivalent performance wise.

I think the best is to make 1 work  / ie edit the tests for it & merge this & then actual users of the extension can tweak to one of the other options if they experience performance issues

Note that the goal now is to get this code out of core code to the extension, with the goal being the extension would eventually be community maintained outside of core so I don't want to get into any feature requests here

@JoeMurray @seamuslee001

**Comment by eileenmcnaughton** [comment]
Per my last comment I have fixed the test to acknowledge that this PR makes the strict behaviour that was inconsistently applied, consistently applied

**Comment by andyburnsco** [comment]
Tested on WP 5.70 single and multisite for both front-end forms and back end access in conjunction with https://github.com/civicrm/civicrm-core/pull/29369 which effectively does produce the outcome below which appears to be the most comprehensive and preferred option IMO:

> LineItem get gets the line items, regardless of whether the Contribution in it's entity is accessible (makes more sense for reporting to me, Contribution.get requires all line items to be accessible.

I can see how the performance could be quite different looking thru line items and might  take the trade off for the 3rd option which I assume will be the fastest:

> Contribution.get does not require all line items to be accessible to return the contribution but rather the financial type id of the contribution is used.

**Comment by seamuslee001** [comment]
Yeh I think 1 is probably best and given that this standardised on that seems good. I'm going to get jenkins to re-run again

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Pull request merged**
