### PR TITLE
Remove deprecation of order-must-be-pending

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Remove deprecation of order-must-be-pending

Before
----------------------------------------
 We deprecated creating an order with a status other than pending in Aug last year.

After
----------------------------------------
All orders created as pending

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@mattwire I think this has been deprecated long enough

**Comment by mattwire** [comment]
@eileenmcnaughton Seems fine - please can you create a documentation PR for https://docs.civicrm.org/dev/en/latest/financial/orderAPI/ that indicates that it should not be passed/will not have any effect from 5.39(?)

**Comment by eileenmcnaughton** [comment]
@mattwire  https://lab.civicrm.org/documentation/docs/dev/-/commit/860ea553b6118326a0dbf706cb1118a4a43d836b

**Pull request merged**
