### PR TITLE
[REF] Update fetchAll function signature to match parent function

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
Updates the function signature to match the original function in DB/DataObject.php

Before
----------------------------------------
fetchAll with incompatible function signature

After
----------------------------------------
fetchAll with compatible function signature

ping @eileenmcnaughton

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton this is to allow this PR to be merged https://github.com/civicrm/civicrm-packages/pull/281 which is essentially to un comment out their fetchAll function

**Comment by seamuslee001** [comment]
@eileenmcnaughton this should be really simple

**Comment by eileenmcnaughton** [comment]
@seamuslee001 can you explain this one a bit - ie. why is it commented out in packages?

**Comment by seamuslee001** [comment]
@eileenmcnaughton it is commented out in the packages as i did that so we could merge in the DB_DataObject upgrade first. This PR https://github.com/civicrm/civicrm-packages/pull/281 puts the code back to as it is in the upstream package as per https://github.com/pear/DB_DataObject/blob/trunk/DB/DataObject.php#L720 however without this change the test site for the packages PR cannot build

**Comment by eileenmcnaughton** [comment]
@seamuslee001 OK - do you know why we override it? I feel like we should ensure we have a comment to that effect. Non blocking so I will merge

**Comment by seamuslee001** [comment]
@eileenmcnaughton I think because we put it in before it fetchAll was a thing also trying to use the parent function was causing me some errors

**Pull request merged**
