### PR TITLE
SearchKit - Add 'whole row' and 'add row' editable features

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds 2 useful modes to SearchKit editable settings:

1. Edit whole row: enables all fields in row to be edited and saved at once
2. Add new row: enables a new row to be added in-place

image

As an example, this adds an editable searchdisplay for editing custom field options, with the ability to add a new option inline:

image

### CODE REVIEW

**Comment by allinappliadmin** [comment]
not able to apply the patch

**Comment by colemanw** [comment]
> not able to apply the patch

@allinappliadmin you can test on the [Online demo of this PR 🔗](http://site-list.test-1.civicrm.org/?filter=core-31583-*)

**Comment by allinappliadmin** [comment]
> > not able to apply the patch
> 
> @allinappliadmin you can test on the [Online demo of this PR 🔗](http://site-list.test-1.civicrm.org/?filter=core-31583-*)

Formbuilder is not activated. I don't have that much time right now to set everything, sorry :-/

**Comment by highfalutin** [comment]
Thanks @colemanw and sorry for the delay! Finally gave this an `r-run` and it works great. I'd say it's ready to merge.

Feature requests for the future:

- Figure out a way to enter edit mode without using the mouse.
- Perhaps move the save/cancel buttons to the end of the row? Currently, if you start editing at the leftmost cell, then tab through the other fields, you end up at the rightmost cell, and then have to shift-tab all the way back to the beginning to save.
- After clicking the Add button, give focus to the first editable field.

**Comment by colemanw** [comment]
Thanks @highfalutin !

**Pull request merged**
