### PR TITLE
[REF] Fix metadata label for contribution_page_id

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Adds label for contribution_page_id to the html metadata & switches search to use this

Before
----------------------------------------
With ***just*** the xml change we get a label regression
Screen Shot 2020-08-03 at 5 40 14 PM

After
----------------------------------------
By also fixing the metadata it continues to display correctly
Screen Shot 2020-08-03 at 5 40 35 PM

Technical Details
----------------------------------------
@colemanw this is how we can use the existing metadata conventions to present the right labels in html without distorting the meaning of the field & making it unavailable for other purposes

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw can I get you to check this - this is using the html label rather than the title to render the html label - which allows the field title to be used as the field title.

**Comment by colemanw** [comment]
This is an interesting solution. I think I like it.
Lots of fields to update now!

**Comment by seamuslee001** [comment]
Merging based on @colemanw +1

**Comment by eileenmcnaughton** [comment]
woot!

**Pull request merged**
