### PR TITLE
Foreign key for civicrm_custom_field.option_group_id

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
This PR added Foreign key for civicrm_custom_field.option_group_id

### CODE REVIEW

**Comment by pradpnayak** [comment]
@colemanw do we need to add upgrade code for this? or is this something done automatically by running updateindices after upgrade?

**Comment by pradpnayak** [comment]
@colemanw I have updated the version to 5.6. Can you please review now?

**Comment by eileenmcnaughton** [comment]
hopefully if people run update indices it will work - be good if you cold test that though

**Comment by colemanw** [comment]
I can't seem to make it work. My steps:
- Checkout 5.5 + this PR
- Observe that there is one index on the `civicrm_custom_field` table (`FK_civicrm_custom_field_custom_group_id`)
- Run upgrade script
- Can't see any new indexes
- Visit the system status page. Expect to see a missing index warning, but there is none.

**Comment by eileenmcnaughton** [comment]
@colemanw indexes are added by running the api System.updateindices I think

**Comment by eileenmcnaughton** [comment]
(we don't 'impose' index changes as they can make the upgrade process painful so we have a job - it was advertised via a system check but someone turned it off as some old sites had some issues)

**Comment by colemanw** [comment]
Ok I typed `CRM.api3('System', 'updateindexes')` into the browser console and it returned a success state, but the index still doesn't exist in my db :(

**Comment by eileenmcnaughton** [comment]
oh - well this will update it for new installs so I'm Ok with us merging it - at some point some more work needs to be done on the updateindexes. We were working on it but then the check was removed & momentum died. Perhaps the UK sprint though

**Pull request merged**
