### PR TITLE
CRM/Core/ClassLoader.php

### PR DESCRIPTION
**Pull request by coldrunKacper**
Appending extensions path to PHP include_path to allow using Components inside Extensions.

### CODE REVIEW

**Comment by coldrunKacper** [comment]
Please verify.

**Comment by colemanw** [comment]
jenkins, ok to test

**Comment by colemanw** [comment]
@coldrunKacper codeStyle check is going to fail because of some extra whitespace you added. If you could clean that up then the rest of the test suite can run on this.

**Comment by totten** [comment]
Hey, it's great you found a technique to get components loading from extensions.

A few critiques:

1. Most existing extensions (and the current templates in civix) use hook_civicrm_config to register on the include-path. Obviously, that's a problem because it comes too late for component initialization. But it's still there.... so this change would have the effect of double-registering those extensions on the include-path. It would be better to require some kind of opt-in (e.g. put a flag in info.xml or create a flag file in the extension); if the flag is present, then use this early registration.

  * Aside: The current system already gets some criticism for using a long include-path instead of using an optimized class-loader. I'm on the fence about this criticism, but making it 2x long seems a bit much.

2. The typical way to get access to the containers is ```CRM_Extension_System::singleton()->getFullContainer()```. This ensures that:

  * The extension list is cached. (Scanning for extensions is slow.)
  * All the containers are searched. (Administrators may install extensions in a few different locations.)

3. It makes me a bit nervous to have the class-loader include ```civicrm.config.php``` - that expands the scope of ```ClassLoader``` to potentially encompass bootstrapping. (It also creates a call cycle, ```civicrm.config.php => ClassLoader => civicrm.config.php => ClassLoader```, although that's mitigated by ```$this->_registered```.)

Questions: 
 * What do you think relative merits are for (a) changing the way classes are loaded and preserving ```CRM_Core_Component``` as-is vs (b) changing the way ```CRM_Core_Component``` behaves and preserving the way classes are loaded?

**Comment by coldrunKacper** [comment]
I've removed some whitespaces according to the pattern I've found in the rest of the code.
Regarding to the suggestions and questions - it needs to be considered but also requires some deeper look into the core. I'm going to investigate which solution would be the best and give you my answers as soon as I get some time to look at it.

**Comment by coldrunKacper** [comment]
I've made second approach:
- removed ClassLoader previous changes
- moved the code to CRM/Core/Config.php::_initialize() method - it's place when we already have DB setup so we don't need to include/recall civicrm.config.php.
- modified CRM/Utils/Hook.php::config() method to set include_path to its unique paths so we don't get duplicated paths after extension's civix_civicrm_config hook is executed.
Finally we end up with the same include_path as it was before the changes.

**Comment by totten** [comment]
Thanks for pushing on this. Per email, replacing this PR with #6483.

**Pull request closed without merging**
