### PR TITLE
Remove legacy tpl param contributionTypeName

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Remove old legacy tpl param contributionTypeName

Before
----------------------------------------
Still 2 assigns

After
----------------------------------------
No assigns

Technical Details
----------------------------------------
I grepped for this & I think it is otherwise gone & has been for a while

Comments
----------------------------------------

### CODE REVIEW

**Comment by yashodha** [comment]
@eileenmcnaughton will this affect people using modified versions of old message template?

**Comment by eileenmcnaughton** [comment]
@yashodha I guess there is a risk -it's been gone a while but maybe people's templates are uber old :-(

**Comment by seamuslee001** [comment]
I would suggest a pre-upgrade message in that case, i don't think its core's responsiblity to maintain backward comparability forever

**Comment by eileenmcnaughton** [comment]
I'm happy to close this for now & worry about it another time

**Comment by eileenmcnaughton** [comment]
@yashodha out of interest are many Cividesk tpls affected?

Also worth noting that sites are likely to update their templates in 5.20 - or at least think about doing so based on the other message template updates. Not sure if that's an argument for 5.20 change or a 'soon after' change

**Pull request closed without merging**
