### PR TITLE
Upgrader - Display note about token formatting

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------
Improve communications about tokens that may generate different output.

This is a follow-up to https://github.com/civicrm/civicrm-core/pull/19806

Depends: https://lab.civicrm.org/documentation/docs/sysadmin/-/merge_requests/306/

Ping: @eileenmcnaughton 

Before
----------------------------------------

No upgrade notice

After
----------------------------------------

Screen Shot 2021-03-26 at 5 46 37 PM

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@totten I think I would go further and say 'some mail merge tokens for custom fields'

**Comment by totten** [comment]
@eileenmcnaughton I thought it affected both some custom fields and some core fields (eg `contact.created_date`)?

**Comment by eileenmcnaughton** [comment]
@totten only in that some fields that didn't work now do

**Comment by eileenmcnaughton** [comment]
@totten specifically it fixes the 2 issues that we had about received contact.hash not working

**Comment by eileenmcnaughton** [comment]
I'm going to merge this - the upgrade notes can cover the specific fields - only custom fields are CHANGED. Some additional non-custom-fields are resolved

**Pull request merged**
