### PR TITLE
dev/core/issues/806, Fixed DB error already exist when recording recurring payment having tax

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/issues/806

Before
----------------------------------------
DB Error:: Already Exists

After
----------------------------------------
No DB Error

Technical Details
----------------------------------------
The line item build in CRM_Contribute_BAO_Contribution::repeatTransaction() is not in a format that is expected by CRM_Contribute_BAO_Contribution::add(); Hence always new item is added in $params['line_item'] with duplicate values which causes DB error when inserting into civicrm_line_item table.

### CODE REVIEW

**Comment by mattwire** [comment]
@pradpnayak Is there test coverage for this?

**Comment by pradpnayak** [comment]
@mattwire just pushed api test.

Thanks
Pradeep

**Comment by mattwire** [comment]
@pradpnayak Think this needs checking again? There's a couple of debug lines and a diff managed to get in :-)

**Comment by pradpnayak** [comment]
@mattwire oops my bad. Updated PR

**Comment by pradpnayak** [comment]
retest this please

**Comment by eileenmcnaughton** [comment]
@monishdeb @mattwire is this mergeable?

**Comment by eileenmcnaughton** [comment]
@mattwire @monishdeb this looks good to me but I'm just wanting a second opinion

**Comment by mattwire** [comment]
Yes, looks good.

**Comment by eileenmcnaughton** [comment]
@mattwire was that your first merge?

**Comment by mattwire** [comment]
@eileenmcnaughton Sshh..

**Pull request merged**
