### PR TITLE
dev/core#522 CRM-19767 - Add case tokens to email activities

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
In CiviCRM core, case tokens had only been partially implemented. This extends them to work in email activities.

Before
----------------------------------------
- When doing *Print/Merge Document* from a case, tokens for {case.id}, etc, were available.
- When doing *Send Email* from a case, the tokens were missing.

After
----------------------------------------
When doing *Send Email* from a case, tokens for {case.id}, etc, are now available.

Comments
----------------------------------------
Originally submitted as #10252

---

 * [CRM-19767: Add Case Tokens to Case Activities](https://issues.civicrm.org/jira/browse/CRM-19767)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
You totally know what I'm going to say this needs....

**Comment by eileenmcnaughton** [comment]
@colemanw I think this needs tests & if that's not on your priority list I think we should close it & re-open if that changes

**Comment by colemanw** [comment]
@jamienovick originally asked me to do this PR and @guanhuan was planning to assign it to someone at CompuCorp for adding a test.

**Comment by jamienovick** [comment]
@guanhuan over to you...

**Comment by guanhuan** [comment]
@colemanw This totally fell through the cracks. Will get this assigned for next week.

cc @jamienovick

**Comment by guanhuan** [comment]
@vinuvarshith has started a Gitlab ticket for this and have created some tests. He has a question regarding one of the test he is writing. @colemanw would you be able to advise? https://lab.civicrm.org/dev/core/issues/204

**Comment by eileenmcnaughton** [comment]
@guanhuan seems to require an answer from your guy again

**Comment by eileenmcnaughton** [comment]
@guanhuan @colemanw per previous comments closing this to track through gitlab until someone wants to prioritise it

**Pull request closed without merging**
