### PR TITLE
CRM-16876 Change country names to uppercase

### PR DESCRIPTION
**Pull request by joannechester**

### CODE REVIEW

**Comment by joannechester** [comment]
I am not sure about the checkstyle warnings.  They started appearing after I had edited some of the tests by replacing United States with UNITED STATES.

I imagine that the errors weren't appearing earlier in the history of this PR as the files hadn't been changed so they weren't being checked. 

I am quite happy to fix them, but I don't really agree with/understand some of them and I am a tinsy bit worried that I have "fixed" the indents in /tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
when they weren't even wrong because of the remaining warning that I didn't know what to do with.

I started to "fix" the indents in /tests/phpunit/WebTest/Import/SavedMappingTest.php but again I am not sure if they still will be wrong if some of the other warning are dealt with first.

**Comment by colemanw** [comment]
jenkins, retest this please

**Comment by joannechester** [comment]
I don;t know the style rules  very well and am still at the "copy, paste, change" stage.   I don;t have phpStorm or even buildkit working properly so I am not using "the latest style checker.  but when I look at CustomfieldTest and compare it with CustomGroupTest I can't (not) fond a missing brace.

Also I think for SavedMappingTest.php  It is considering the "." in example.com as a concatenator so giving a spurious error message.

**Comment by joannechester** [comment]
Sorry didn't mean to close this, just meant to comment. about the checkstyle warnings

**Comment by eileenmcnaughton** [comment]
Hi Joanne,

I have squashed the country part of your changes into a single commit & backed out of the whitespace changes are that was just getting too hard.

I found one unclosed quotes (now fixed) which could have been manefesting as ? who knows what really :-)  Anyway - let's see how the next jenkins run looks

**Comment by joannechester** [comment]
I think this is good to go as the tests that are failing are unrelated to this PR and have been failing for 16 prior builds

**Pull request merged**
