### PR TITLE
CRM-18324 - Fix tax divison by zero error on Event Dashboard

### PR DESCRIPTION
**Pull request by rajbdilip**
https://issues.civicrm.org/jira/browse/CRM-18324

### CODE REVIEW

**Comment by pradpnayak** [comment]
jenkins, retest this please

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by rajbdilip** [comment]
@monishdeb Could you look into this?

**Comment by yashodha** [comment]
@rajbdilip It would be great to have test coverage with patch.

**Comment by yashodha** [comment]
PR seems alright, though I wasn't able to replicate the notice

**Pull request merged**
