### PR TITLE
SearchKit - Import/Export saved search configuration

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Provides a UI for importing and exporting SavedSearches in JSON format. This allows power-users to copy and paste their Searches between sites. For extension developers, includes a direct link to generate a `.mgd.php` file from the API Explorer.

image

image

Technical Details
----------------------------------------
Exporting smart groups depends on #22228

### CODE REVIEW

**Comment by herbdool** [comment]
@colemanw I've tested this by patching just this PR on the latest 5.46-alpha1. The export works but it requires "Form Core" extension to be enabled, which might not be obvious to many. I only figured that out by looking at the console log and it said "Afform does not exist."

Once I enabled the export works.

Just for testing I tried to rename the search name in the export and import it, but it gives me a db error: already exists. Not sure what I'm doing wrong. I understand that with a clone button this is not strictly needed.

Maybe as a follow-up it could have a checkbox to allow someone to overwrite an existing Saved Search if they have the same name.

**Comment by herbdool** [comment]
Oh, actually it did import the search with my changed name despite the error message.

**Comment by colemanw** [comment]
@herbdool if your export includes other stuff like displays, forms, etc you have to change the name of the search they reference too.

**Comment by colemanw** [comment]
Thank you for testing this @herbdool.
That was a good catch, I didn't mean to create a hard-dependency on Afform, as SearchKit thus far has not required it.
I've amended the commit to add a conditional around the Afform bits so it will skip them if that extension is missing. Without Afform enabled, the export screen no longer crashes and looks like this:

image

**Pull request merged**
