### PR TITLE
dev/core#5584 Fix soft credit default setting & copy down 

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
this fixes a couple of issues with the soft credit type field in the batch data entry screen

Before
----------------------------------------
1) back in 2020 the soft_credit_type field was accidentally changed from optional to required as part of an large change which accidentally dropped off a parameter in [this line](https://github.com/civicrm/civicrm-core/commit/a2eb61520b685cf139a829d65015b2579caed27d#diff-a8aa0473142a72fc757b2dd20805fa12454951109989fab7cc06a4f0b112a9b1R2097) - meaning that `$extra` is being passed in as `$required` - this adds the extra `$required = FALSE` to revert that
2) in addition setting the soft credit contact was causing the soft credit type to be changed to the default value even when it had already been intentionally been set by the user to something else
3) the copy functionality was missing for the soft credit type field 

4) deprecation warning 
image

**note that another notice warning fix on this screen was merged to core today - if you see a notice on size you may not have that patch**

After
----------------------------------------
batch-after

Technical Details
----------------------------------------

The copy functionality was removed in the course of https://issues.civicrm.org/jira/browse/CRM-12653 but it is not clear that it was intentional - I commented on possible reasons in-code for the fields for the soft credit contact & soft credit amount to have been excluded from the copy down - basically either because of the proximity of the too-hard-basket or because there was an anticipation of new functionality that never happened.

Comments
----------------------------------------

### CODE REVIEW

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by demeritcowboy** [comment]
This seems fine there's just some inconsistency in how soft-credit type works and I'm not sure what it's supposed to be so have put merge-ready:
* On a regular contribution I can leave it blank and it will happily make the soft-credit with no type (maybe this is a bug?)
* Here, if I try to blank it out it appears to let me, but the soft-credit gets created with Solicited type.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy from my testing it seemed like you had to enter a soft credit amount to have a soft credit created - were you seeing it create a soft credit even when the soft credit amount was not populated?

**Comment by demeritcowboy** [comment]
No it's that assuming the intent is to allow a soft credit without a type (which would be consistent with the regular contribution form), then you can't do that with this PR because even if you blank out the type field, it creates it with solicited type.

i.e. fill out a batch entry and filling in the soft credit fields, but make the soft credit type blank. When you save, the soft credit has solicited type.

**Comment by colemanw** [comment]
@demeritcowboy @eileenmcnaughton this has been `merge-ready` for a while. Any reason not to merge it?

**Comment by demeritcowboy** [comment]
The sticking point is that the PR attempts to make soft-credit type not required, but then if you leave it blank it sets a type anyway. So I think if it's updated to handle that case properly then it's mergeable, but otherwise no it's not right.

I'll remove the tag. My earlier softness was because I don't really use soft-credit much so am soft on how it's supposed to work.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy so re-testing this & what I see is 

1) if no soft credit contact is selected soft credit remains blank and no soft credit is created - this is correct and it no longer forces a soft credit type to be selected when there is no soft credit to create
2) if a soft credit contact is selected then the soft credit type is then set by javascript to be the default soft credit type. HOWEVER, if the use deliberately changes this to unspecified then their change is ignored.

I guess I didn't really anticipate the user actively trying to enter bad data - we can't handle this well up front because the field should be optional as it is not required for non-soft credits but I guess we could do a post submit validation to ensure that if soft credit contact is set soft credit type should be set too

**Comment by eileenmcnaughton** [comment]
Oh - I see - you CAN create with no soft credit on the main contribution form so we need to treat this as valid (even if my gut says it is probably an old regression to permit it)

**Comment by demeritcowboy** [comment]
Yeah that was the flip side of the question: Is a soft-credit with no type "bad data" or "ok". I would intuitively agree that it's probably a bug that snuck in someday and so is bad data. So another option is try to fix that consistently and not allow bad data.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy - here is a fix to  https://github.com/civicrm/civicrm-core/commit/9e1854a1dca76ede8ac64271823d30de33a7f4b4#diff-1558bdd90651598f70cdf28a8d84c9fe0e8122f6d162ad7a6ce800007784c5a4R420 - to only set to the default value if the form doesn't provide an option.

I did a teenage-boy-style hunt for a can-opener to get those worms loose but didn't find one so leaving those worms in situ

**Comment by demeritcowboy** [comment]
Keep that worm can opener nearby. There will be many more opportunities to use it.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy I'm sure I'll find it when I step on it

**Pull request merged**
