### PR TITLE
CRM-21014 Ensure that preimum name is EOU

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This fixes the issue i believe found in CRM-21014

Comments
----------------------------------------
@seanmadsen Sean can you test the Contribution Page output as well but i have a sneaking suspicion this will cover both

---

 * [CRM-21014](https://issues.civicrm.org/jira/browse/CRM-21014)

### CODE REVIEW

**Comment by seamuslee001** [comment]
ping @eileenmcnaughton @totten as well on this

**Comment by seamuslee001** [comment]
Also Ping @jackrabbithanna

**Comment by seanmadsen** [comment]
This looks good to me. I've tested locally can con confirm that it fixes [CRM-21014](https://issues.civicrm.org/jira/browse/CRM-21014) without introducing any unwanted side effects. Ready to merge :white_check_mark:

**Comment by seamuslee001** [comment]
ping @monishdeb this should be good to merge now

**Comment by eileenmcnaughton** [comment]
I'm happy with this based on @seanmadsen review

**Pull request merged**
