### PR TITLE
[REF] Import - minor cleanup  - generate js on the processor class

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Minor code cleanup

Before
----------------------------------------
Code more crazy

After
----------------------------------------
Code less crazy

Technical Details
----------------------------------------
This moves the js calculation to the processor class for some of the function and simplifies it
so that the concatenation is done at the end.

Test cover is very solid on this

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
Added has-test as tests were added in preparation

**Comment by seamuslee001** [comment]
This looks fine to me and confident that the unit tests here will ensure we have the same output, Merging

**Comment by eileenmcnaughton** [comment]
Thanks @seamuslee001

**Pull request merged**
