### PR TITLE
CRM-15067 use email addresses in profile if present

### PR DESCRIPTION
**Pull request by lcdservices**
* [CRM-15067: Email should appear in the profile in which it is included, rather than always at the top of contribution page](https://issues.civicrm.org/jira/browse/CRM-15067)

### CODE REVIEW

**Comment by kcristiano** [comment]
@lcdservices Rebased patch on current master.   

Tested Patch with a profile with an email field.   Email field appears in the profile.  
Tested with profile without email address.  Email field is above the profiles.   
Tested with two profiles. First has No email field , second has an email field.  Email appears in second profile
Tested with no profiles.  Email field appears.

Rebased https://github.com/civicrm/civicrm-core/pull/10349

**Comment by petednz** [comment]
Has this had any role in breaking the feature of 'create user' in a Profile? See https://issues.civicrm.org/jira/browse/CRM-20834

**Comment by kcristiano** [comment]
@petednz Very possible that it is related.   I did test user creation back in May for both WP and Drupal.   At the time it worked.   Testing again on WP with 4.7.21 user creation is working.   For Drupal I can confirm that it fails.  i am not as familiar with Drupal so I do think it possible that this PR could be to blame.

**Comment by xurizaemon** [comment]
Yep, on an affected site if we I back out the changes in [this block](https://github.com/civicrm/civicrm-core/pull/10079/commits/8803e32bd8e33f5832414b7c97c321d83f78cd29#diff-2b6ae932269516c2f04429d8866ccec7R631) of 8803e32, contributions resume working.

**Pull request closed without merging**
