### PR TITLE
CRM-20453 Fix inconsistencies in XML schema definitions

### PR DESCRIPTION
**Pull request by seancolsen**
This is a minor change that I *think* should not affect anything other than cleaning up some code to make things more consistent. 

I did some analysis on the XML schema while building [this documentation](https://docs.civicrm.org/dev/en/latest/framework/schema-definition/) about it, and in the process of doing so, I found some outliers. I [asked](https://chat.civicrm.org/civicrm/pl/i9nokqyfetfougt48378xug56c) @eileenmcnaughton about this and she suggested I submit a PR to clean up these inconsistencies.

---

 * [CRM-20453: Fix inconsistencies in XML schema definitions](https://issues.civicrm.org/jira/browse/CRM-20453)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
jenkins add to whitelist

**Comment by eileenmcnaughton** [comment]
@seanmadsen this looks good - but you actually have to call bin/regen.sh or civibuild create to regenerate the DAOs after an xml change

**Comment by eileenmcnaughton** [comment]
Please remove WIP from the title when you have redone the DAO

**Comment by seanmadsen** [comment]
Ok @eileenmcnaughton I ran...

```php
cd civicrm/xml
php GenCode.php
```

...and then committed the changes. I hope this was the correct thing to do. (Still learning all this &mdash; thanks for the hand-holding)

**Comment by eileenmcnaughton** [comment]
unrelated test fail

**Pull request merged**
