### PR TITLE
Crm 16621

### PR DESCRIPTION
**Pull request by pradpnayak**
(DO NOT MERGE - Submitted to facilitate testing)

### CODE REVIEW

**Comment by pradpnayak** [comment]
Could any one please tell the Jenkin to retest the PR?

**Comment by davecivicrm** [comment]
Jenkins, test this please.

**Comment by davecivicrm** [comment]
Jenkins, test this please.

**Comment by davecivicrm** [comment]
@pradpnayak and @JoeMurray Tim, Coleman and I discussed at the sprint and we think this is too big a change for a point release. Hoping you can rebase and submit against master for 4.7. Ping us on IRC if we need to discuss / revisit this decision.

**Comment by pradpnayak** [comment]
Submitted new PR at https://github.com/civicrm/civicrm-core/pull/6881

**Pull request closed without merging**
