### PR TITLE
CRM-13725 check custom fields to test for duplicate relationship.

### PR DESCRIPTION
**Pull request by johanv**
Unit test and fix.

---
- [CRM-13725: Make check for duplicate relationship aware of custom fields](https://issues.civicrm.org/jira/browse/CRM-13725)

### CODE REVIEW

**Comment by colemanw** [comment]
@johanv looks like there were some test failures generated from that new checkDuplicateCustomFields function.

**Comment by johanv** [comment]
I think I fixed the problem with the unit tests. But while I was doing this, I realized that there might be a problem if you add a relationship without custom values, and a similar relationship exists with custom values.

**Comment by colemanw** [comment]
Could you add a unit test for that scenario?

**Comment by kurund** [comment]
@johanv any progress on unit tests

**Comment by johanv** [comment]
I just added two tests. One for an existing relationship with custom fields, and a new one without custom fields. And one for an existing relationship without custom fields, and a new one with custom fields.

They both fail. I guess the function checkDuplicateCustomFields (part of the PR) has to be fixed, but it is not always clear what the behaviour should be. Suppose that the existing relationship has no custom fields, and the new one has, but with all custom values null or empty. I guess this should be considered as a duplicate?

**Comment by colemanw** [comment]
I think you will always be comparing relationships that are of the same 
type, therefore they will always have the same custom fields defined 
(granted they might not have ever been entered so the sql row for them 
might not exist, which is slightly different than the row existing but 
with null or empty values). But I think you are correct - for purposes 
of deduping, NULL == EMPTY == MISSING.

**Comment by johanv** [comment]
Still two errors. But I don't really understand what's going wrong here.

**Comment by totten** [comment]
So I haven't fully traced, but this can point in the right direction:

  * The [error output](https://test.civicrm.org/job/CiviCRM-Core-PR/5368/testReport/%28root%29/api_v3_SyntaxConformanceTest__testSqlOperators/testSqlOperators_with_data_set__66/) includes two traces. This is a bit confusing.
  * The first trace+error_message seems to be the outermost API call -- `MembershipType.getcount`. 
  * Which makes [a nested API call to `MembershipType.get`](https://github.com/johanv/civicrm-core/blob/CRM-13725-duplicate_realtionships_check_custom_fields/api/v3/Generic.php#L282) and then returns/outputs any resulting errors.
  * The second trace+error_message seems to be from `MembershipType.get` (with the extra parameter `is_count`). The error message there is `Invalid argument supplied for foreach()`.
  * Guess: `MembershipType.get` then calls `_civicrm_api3_get_using_utils_sql`, where there's a conditional which [checks for `is_count` and then runs a `foreach` loop](https://github.com/johanv/civicrm-core/blob/CRM-13725-duplicate_realtionships_check_custom_fields/api/v3/utils.php#L651). Maybe there's something wrong in this area?

**Comment by johanv** [comment]
I had similar failures with an unrelated PR: https://github.com/civicrm/civicrm-core/pull/6747. Maybe the failures are caused by something else?

**Comment by davecivicrm** [comment]
@colemanw pretty sure @johanv is correct and test failures are unrelated since they occur on all recent PRs on master. However, not merging myself since I'm not sure if the prior threads are resolved.

**Comment by davecivicrm** [comment]
Jenkins test this please.

**Comment by colemanw** [comment]
jenkins, retest this please

**Pull request merged**
