### PR TITLE
CRM-13123 - Fix serialization metadata for uf group type field

### PR DESCRIPTION
**Pull request by colemanw**
Overview
-----

Non-functional change to update schema metadata. A followup of https://github.com/civicrm/civicrm-core/pull/11394

* [CRM-13123: Handle value-separated fields at the dao level](https://issues.civicrm.org/jira/browse/CRM-13123)

### CODE REVIEW

**Comment by colemanw** [comment]
@seamuslee001 since you're familiar with its predecessor can you give this PR a quick look?

**Comment by colemanw** [comment]
@totten turns out we needed SERIALIZE_COMMA after all.

**Comment by seamuslee001** [comment]
@colemanw this looks fine to me, Just wondering when did we merge the other PR? just wondering if its needed on 4.7.30-rc branch or not?

**Comment by colemanw** [comment]
Thanks for the review @seamuslee001.  There's no rush for a particular release since Api4 is still in active development.

**Pull request merged**
