### PR TITLE
dev/core#4038 import contribution fixes in update mode

### PR DESCRIPTION
**Pull request by kurund**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Hmm - this feels wrong - we've been phasing out the unique names - it might be the error is in the use of `contribution_id` elsehwere?

**Comment by kurund** [comment]
@eileenmcnaughton 

Field mapping is passing `contribution_id` and required check is for `id`. I was not sure which was wrong hence fixed required fields.

**Comment by eileenmcnaughton** [comment]
@kurund just thinking - if this fixes for you then we should probably make this change in the rc (& probably backport) and in master potentially we can dig a little deeper

**Comment by kurund** [comment]
@eileenmcnaughton 

Yes, it's working fine for me. Contribution records are updated correctly.

**Comment by eileenmcnaughton** [comment]
@kurund can you switch to the rc then & we'll merge this & revisit in master

**Comment by kurund** [comment]
@eileenmcnaughton 

Here is the PR against RC: https://github.com/civicrm/civicrm-core/pull/25204

**Comment by demeritcowboy** [comment]
This was upmerged from the 5.57 PR, so I think can be closed.

**Pull request closed without merging**
