### PR TITLE
CRM-19148 Fix for on hold data being lost

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
- [CRM-19148: Batch merge - Email on hold data lost when there is a conflict](https://issues.civicrm.org/jira/browse/CRM-19148)

### CODE REVIEW

**Comment by davejenx** [comment]
@eileenmcnaughton I've submitted #9244 to add the test.

This PR is giving a conflict that stops me cherry-picking it. Does the PR need re-doing?

**Comment by davejenx** [comment]
@eileenmcnaughton Did something go wrong with the rebase? This PR now affects 13 files, including some that look like Bjoern's ACL changes + ext/org.civicrm.myextension/CRM/Myextension .

**Comment by davejenx** [comment]
Fab, thanks. Have now run my new test testBatchMergeEmailOnHold (see #9244) which fails without your fix and it succeeds with the fix. Hooray! Good to merge, I reckon.

**Comment by seamuslee001** [comment]
Looks good to merge

**Pull request merged**
