### PR TITLE
CRM-18428: pay later being inappropriately assigned from the contribut…

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
…ion page

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@monishdeb and another! As you can  perhaps tell I'm trying to set up some receipting!

**Comment by eileenmcnaughton** [comment]
I need to check this test. Issue may be test or may be real

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by monishdeb** [comment]
@eileenmcnaughton there is an issue where all the profile information (custom-pre/post_id, honoree_profile_id, onbehalf_profile_id) are missing as now we are explicitly setting the desired values that doesn't include any uf_block attribute. Related test build failure tell us that 'Supporter profile' is missing from message template.

**Comment by eileenmcnaughton** [comment]
Ah they need to be in the white list then? I kinda thought having a white list would move us from 'never knowing what params are used where' to knowing what does & doesn't matter -but maybe a few more params are needed. I think it makes sense just to add them to the whitelist?

Yay test!

**Comment by monishdeb** [comment]
Or should we only bypass the pay_later attributes rather than explicitly setting all other attributes for the same cause ? In this way we no longer need to prepare the white list, what ya say !!

**Comment by eileenmcnaughton** [comment]
I'm on the fence. In general in that code I've been so fed up with undocumented variables being set I've tended to try to force things a bit.

**Comment by monishdeb** [comment]
I agree, please go ahead and update the whitelist, will QA then. If required I will extend unit test to assert those after the current PR is ready to merge.

**Comment by eileenmcnaughton** [comment]
@monish I've updated that whitelist now. 

 I've also added you to my repo so you can push to my commits if you ever want to make a minor change that is easier to do than explain (I say this knowing that I 'think' you meant 'custom_pre_id & 'custom_post_id' ....

**Comment by monishdeb** [comment]
Thanks @eileenmcnaughton :)  Updated the PR, please have a look!!

**Comment by eileenmcnaughton** [comment]
Dang - rookie mistake!

**Comment by monishdeb** [comment]
I guess with that change we have covered all the variables needed for template. I think #8227 also need some attention in terms of current changes, can we somehow include the native formvalue(s) in this function (e.g. amount here) !!

**Comment by eileenmcnaughton** [comment]
Hmm yeah that one is ugly - I'm not sure if this or any of the other recent prs fixes that or if it is still outstanding - but we need to get unit testing on it, if we can replicate it.

**Comment by monishdeb** [comment]
I have already written unit test on pay later https://github.com/civicrm/civicrm-core/pull/8358/files#diff-40e2e0f106ba620465acf3a9a81f2498R1653 as I remember I was not getting the amount value on mail log thats why I have excluded the amount parameter from mailLog assert list.

**Comment by eileenmcnaughton** [comment]
Ah well if that's the case it's easy to verify Ken's one :-)

**Comment by eileenmcnaughton** [comment]
@monishdeb where are we at here? I feel like it's ready to merge but there is follow on from it? Or not?

**Comment by monishdeb** [comment]
Oops I guess we have missed out soft_credt_type_id :/

**Comment by monishdeb** [comment]
My bad .. ignore my earlier comment ... just checked the soft credit data on mail.log everything is there

**Pull request merged**
