### PR TITLE
dev/core#3425 FormBuilder: support advanced filter option for contact reference cus…

### PR DESCRIPTION
**Pull request by kurund**
Overview
----------------------------------------
Contact reference custom data field now respects "Advanced filter" option with this PR

### CODE REVIEW

**Comment by lcdservices** [comment]
@kurund I ran through tests and this is working as expected.

**Comment by kurund** [comment]
Thanks Brain

@colemanw 
One for you.

**Review by colemanw — CHANGES_REQUESTED** [review]
Thanks for your work on this @kurund - however I think this approach is problematic because it only applies the restriction to the client-side.

What this PR does is it takes a secure value (filters) from the server and turns it into an insecure value by sending it to the client side, which then sends it straight back to the server, which treats it as if it were still secure.

It would be better IMO to continue the work started in #24165 and extend it with this functionality. That design already has security built-in by keeping `filters` on the server and never sending them to the client. I'm available to work on that @lcdservices - is this for NYSS?

**Comment by lcdservices** [comment]
@colemanw yes, you can work on this for NYSS.

**Comment by colemanw** [comment]
Ok I'm working on a different PR for this.

**Comment by kurund** [comment]
@colemanw 

Just wondering if you have a different PR that I can review.

**Comment by colemanw** [comment]
@kurund yes! It took me a week but I finally finished! https://github.com/civicrm/civicrm-core/pull/24832 is ready for review.

**Pull request closed without merging**
