### PR TITLE
Crm 19401

### PR DESCRIPTION
**Pull request by spirit-q2**
It's more generalized solution that will work with any custom field of Select type

### CODE REVIEW

**Comment by colemanw** [comment]
jenkins, ok to test

**Comment by colemanw** [comment]
This looks like the right approach to me. Needs someone to test it out.

**Comment by seamuslee001** [comment]
I tested this as per the Issue and does fix the display issue

**Review by seamuslee001 — APPROVED** [review]

**Comment by spirit-q2** [comment]
so, can anyone tell me why my pull request isn't committed?
that one error in the jenkins tests doesn't have anything common with my changes...

**Comment by colemanw** [comment]
@spirit-q2 we have a large backlog of PRs. 3 days is actually a pretty fast turn around time by any standards.

**Comment by spirit-q2** [comment]
Oh =) I get it. 
Thanks anyway!

**Pull request merged**
