### PR TITLE
Afform - Show file field values for existing entities

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Improves the file-upload interface for existing entities.

Before
----------------------------------------
For existing entities, the file upload field was always blank, even if a file already exists.

After
----------------------------------------
image

### CODE REVIEW

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by mlutfy** [comment]
Test failed, probably because c.o was overloaded:

```
E2E\Core\AssetBuilderTest::testInvalid
GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 2000 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by totten** [comment]
civibot, test this please

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
retest this please

**Comment by shaneonabike** [comment]
Ah man @colemanw you rock! This has allowed me to ditch all this brutal custom code and create a ```Form Builder``` that creates a CiviCase with attached documents. Hooray!

The only issue I found is that _if_ I set this field as required the form will never validate even if I do attach a file. I don't know if that is another bug or connected to this one.
Peek 2023-01-24 14-49

**Comment by colemanw** [comment]
@shaneonabike that bug is likely not related to this PR directly. Can you test your form without this PR and see if you get the same validation error? If so we should do a separate bug report.

**Comment by shaneonabike** [comment]
@colemanw  I'm sure you are right. I'll log a new bug related to that.

**Comment by colemanw** [comment]
Retest this please

**Comment by colemanw** [comment]
Looks like tests are passing now but the old "default" test is still in the history making it look red when it's not.
FYI @totten

**Comment by eileenmcnaughton** [comment]
OK - I agree the test fail is not really a thing & happily @shaneonabike has tested so I'm merging

**Comment by Guydn** [comment]
@colemanw It works for custom fields ("File" type) but it does not for the native field "Image Url". 
Tested on wpmaster 5.62

**Comment by Guydn** [comment]
OK, I see the URL when i set a "text" format in Formbuilder.

The use case is to give the possibility for a logged in user to update his photo. How could i do that ?

**Comment by colemanw** [comment]
There has been some talk about fixing this field in the schema, but it would take a bit of work. If someone (maybe you!) wanted to provide a bit of funding we could make it happen!
See https://lab.civicrm.org/dev/core/-/issues/2755

**Comment by Guydn** [comment]
Depends on the amount :-). Knowing that I sponsored recently 2 PRs. 
How many hours would that be ?

**Pull request merged**
