### PR TITLE
CRM-16201 Descriptions and translation for permissions

### PR DESCRIPTION
**Pull request by agh1**
- add descriptions for CMS permissions
- make permission labels and descriptions translatable

### CODE REVIEW

**Comment by davecivicrm** [comment]
Andrew - can you please review and fix the style exceptions so we can rerun the PR test. Thanks.

**Comment by agh1** [comment]
Okay just made those changes

**Comment by davecivicrm** [comment]
As noted on the Jira issue, applying both patches results in numerous Warning + Notice output AND causes the component perms to disappear. (If there's a step I've missed to get this configured - apologies. Let me know.)

**Comment by agh1** [comment]
Nope, you did it right.  I've made changes in a new branch and created #5525

**Pull request closed without merging**
