### PR TITLE
dev/core#3034

### PR DESCRIPTION
**Pull request by jaapjansma**
Overview
----------------------------------------

This is a follow up PR for #22532

Steps to reproduce
----------------------------------------

1. Create a case
2. Export document from this case
3. Check the activity Print/Meger document

Before
----------------------------------------

When creating a document from the manage case screen. The attachment at the activity has the file name of `.unknown`.

After
----------------------------------------

When creating a document from the manage case screen. The attachment at the activity has the file name of `CiviLetter.pdf`.

Comments
----------------------------------------

I also checked the other formats such as ODT and HTML and Word. All of them ended up with a filename attached to the activity with the name `.unknown`.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
With this applied I get a double extension when using non-pdf format, e.g. CiviLetter.docx.docx ?

**Comment by jaapjansma** [comment]
@demeritcowboy yes you are right. I have solved that.

**Comment by demeritcowboy** [comment]
Ok thanks @jaapjansma . I see this is only coming up when you have changed the setting at System Settings - Misc to "combined with file attachment", and so refers to the attachment that then gets stored on the activity, not the downloaded file.

Can you just squash commits?

**Comment by jaapjansma** [comment]
I have squashed the commits into one.

**Pull request merged**
