### PR TITLE
Stop shipping text versions of workflow templates

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Stop shipping text versions of workflow templates

Follow on from https://github.com/civicrm/civicrm-core/pull/27685#issuecomment-1741565801

Before
----------------------------------------
Maintaining a test version and an html version of workflow templates is tedious and adds little value as we can just convert the html to text. The nuances of the formatting perhaps mattered more when disallowing html was common but these days it's extremely uncommon

After
----------------------------------------
Text version is rendered from the html version. The formatting is pretty ho-hum around the tables - but any sites that care can do something about that themselves rather than it being managed in our code base

Technical Details
----------------------------------------
As @larssandergreen suggests - we can remove any of these text versions that are not customised  & advise people that if they have them customised they can either remove them or update them based on the html version

Comments
----------------------------------------
I think maybe we just remove the text version from new installs first & then next release look at those extra steps

### CODE REVIEW

**Comment by larssandergreen** [comment]
🤠🤠🤠 No more updating text templates! (soon?)

**Comment by eileenmcnaughton** [comment]
@larssandergreen nope - it could end - what do you think of how the text versions look (the test fails give an insight)

**Comment by larssandergreen** [comment]
I think we should switch our html2text as discussed previously, here's a PR to see what breaks with that change: #27694.

**Comment by eileenmcnaughton** [comment]
@larssandergreen where I have the most reservations is the way it converts tables - eg

https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/5361/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/testReport/junit/(root)/api_v3_ContributionPageTest/testSubmitMembershipBlockNotSeparatePaymentWithEmail/

**Comment by eileenmcnaughton** [comment]
The formatting looks a lot better with the new library https://github.com/civicrm/civicrm-core/pull/27694 so I think once that is merged my reservations about the formatting go away.

The thing is that if we update the shipped tpl files then everyone who has customised them has to re-customise them.  So the burden of maintaining these text versions is mulitplied not shared. 

At this stage the html versions of some of the event templates is close to 'final' in terms of getting to a point where the form layer / calling code only has so specify a few IDS & any userEnteredText and all the data is loaded in the WorkflowTemplate or tokens layer. We haven't been doing many 'push updates' on these (ie notify people that they need to update customised versions) to save people re-writing them every release but I'm expecting to do a push update on participant offline receipt in the next release & that it will make more sense for that update to push an empty version of the text file at that point. I'm actually leaning towards emptying out the tpl rather than this method - which would only impact new sites.  I would probably do only that template at first - mostly because that template is nearly at the point of being stable with minimal form interaction & we would combine the push update with a removal of form assignments for a bunch of variables (& probably up the messaging a bit).

**Comment by eileenmcnaughton** [comment]
Closing this out as the plan is to remove these one-template-at-a-time rather than en mass (or at least initially). The focus is the offline_event_template

**Pull request closed without merging**
