### PR TITLE
(NFC) FileTest - Mark as ornery

### PR DESCRIPTION
**Pull request by totten**
n/t

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I'm gonna merge this now - style passed - which is the only test that can fail on this - so let's speed it all up....

**Comment by demeritcowboy** [comment]
Ok. If this isn't going to run in the test runs then what I can do is run it somewhere else regularly. It's a security test because if Utils_File::isDir() gets changed to do anything different than the real php is_dir especially with openbasedir it _could_ open up a security hole.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy it still runs in the matrix tests which are checked before any release

**Comment by demeritcowboy** [comment]
Ok thanks. Got it.

**Pull request merged**
