### PR TITLE
CRM-16189, added revenue_recognition_date field for on install and up…

### PR DESCRIPTION
**Pull request by pradpnayak**
…grade

---
- CRM-16189: Improve support for Accrual Method bookkeeping
  https://issues.civicrm.org/jira/browse/CRM-16189

### CODE REVIEW

**Comment by JoeMurray** [comment]
Pradeep, it seems a bit odd to group these two commits into one PR since they aren't really related. But I think both are fine. @yashodha could you please merge

**Comment by yashodha** [comment]
@pradpnayak Could you please rebase and push the changes

**Comment by pradpnayak** [comment]
I rebased PR

**Comment by pradpnayak** [comment]
@eileenmcnaughton can we merge this PR

**Comment by colemanw** [comment]
Looks good.

**Pull request merged**
