### PR TITLE
CRM-21019, Changed column labels on batch transaction listing page

### PR DESCRIPTION
**Pull request by pradpnayak**
----------------------------------------
* CRM-21019: Change column labels
  https://issues.civicrm.org/jira/browse/CRM-21019

Overview
----------------------------------------
This PR fixes the column labels on batch transaction listing page

Before
----------------------------------------
before

After
----------------------------------------
after

### CODE REVIEW

**Comment by lcdservices** [comment]
tested and confirmed. these labels better identify the purpose of each column.

**Comment by pradpnayak** [comment]
@eileenmcnaughton / @colemanw  can you please review?

**Comment by colemanw** [comment]
Yes that's a lot more clear. One suggestion: "Expected Batch Total" and "Actual Batch Total" instead of "Batch Total Amount" and "Actual Batch Total Amount"

**Comment by MegaphoneJon** [comment]
+1 on Coleman's suggestion.

**Comment by colemanw** [comment]
Actually I think the word "batch" is redundant. We know it's a batch already. For those four columns in the 1st screenshot I propose:

| Expected Number of Items | Actual Number of Items | Expected Total Amount | Actual Total Amount |

**Comment by JoeMurray** [comment]
+1 to latest suggestion from Coleman https://github.com/civicrm/civicrm-core/pull/10813#issuecomment-320319934

**Comment by monishdeb** [comment]
@colemanw I have updated the PR. Thanks for your feedback.

**Comment by lcdservices** [comment]
tested and confirmed.

**Pull request merged**
