### PR TITLE
Coding standards / cleanup.

### PR DESCRIPTION
**Pull request by xurizaemon**
Comment changes & formatting, no code changes.

### CODE REVIEW

**Comment by seamuslee001** [comment]
@xurizaemon can you fix the style issue here https://test.civicrm.org/job/CiviCRM-Core-PR/11721/checkstyleResult/new/

**Comment by xurizaemon** [comment]
@seamuslee001 Done. What even is a "LocBlock"?

**Comment by seamuslee001** [comment]
@xurizaemon Location block, used by Events (location tab), its basically an entity of an address_id, phone_id, and email_id

**Review by seamuslee001 — APPROVED** [review]

**Comment by monishdeb** [comment]
And merged

**Pull request merged**
