### PR TITLE
Add workflow template for 'recurring edit' workflow

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Add workflow template for 'recurring edit' workflow

Before
----------------------------------------
now you don't see it

After
----------------------------------------
now you do

Technical Details
----------------------------------------
This adds a declared workflow template for the recurring edit workflow

Comments
----------------------------------------

### CODE REVIEW

**Comment by totten** [comment]
@eileenmcnaughton I've pushed a few more commits up here. Here's what the "Preview" dialog looks like with the new RecurringEdit example:

Screen Shot 2021-09-15 at 3 51 55 AM

**Comment by totten** [comment]
@eileenmcnaughton I've done revisions and rebasing/squashing to use the `Civi/Test/ExampleData/*` (with data-sets named like `entity/Contact/Alex` and `entity/ContributionRecur/Euro5990/cancelled`.

**Comment by eileenmcnaughton** [comment]
@totten that looks good to me - I'd be happy to merge-on-pass this (with a little PR template editing).

I would like to talk about the 'from_email_address' one - because I feel like that could be generic - once this is merged

**Comment by totten** [comment]
> (@eileenmcnaughton) I would like to talk about the 'from_email_address' one - because I feel like that could be generic - once this is merged

Agree on both points. The Smarty variable `receipt_from_email`  feels a bit quirky, and it'd make sense to expose the To/From/etc in a more consistent+common way.

**Comment by eileenmcnaughton** [comment]
@totten also note that I don't think it's really intentional that the template winds up with the [name + email] format rather than just email - it doesn't read right

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @colemanw can one of you escalate this to merge-on-pass. I think @totten & I are agreed it should be merged now so just want someone not already a committer on this PR to approve

**Comment by colemanw** [comment]
Lots of tests here :)

**Pull request merged**
