### PR TITLE
[WIP] Fix for core#1247 (export hooks don't work in 5.17)

### PR DESCRIPTION
**Pull request by MegaphoneJon**
Overview
----------------------------------------
Export hooks no longer work.

Before
----------------------------------------
Export hooks don't work.

After
----------------------------------------
Export hooks kinda work.

Technical Details
----------------------------------------
#14913 moved the line that calls the hook to a place where the hook's arguments are mostly not defined.  This defines most of the arguments.

Comments
----------------------------------------
I need help with thoughts on how to finish this!
* `$ids` doesn't appear to be part of the export object.  We can probably determine which column has the IDs and query the temp table - is this the recommended approach here?  I've never used the `$ids` argument in an extension.
* I added these two lines to allow arguments passed by reference to update the object:
```php
    $this->setExportMode($exportMode);
    $this->setComponentTable($componentTable);
```
However, I'm thinking that we're almost at the point of export here, and these lines are likely useless.  If so, should we perhaps move them into the `if` statement below that deprecates altering them via hook?

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Would it work to just move the block that calls the hook back to where it was before? You'd have to call getHeaderRows() again before it, but that same PR has also moved the hook so that it no longer gets called during tests if suppress_csv_for_testing is set, so I'm thinking just move it back and then think more about it later?

**Comment by demeritcowboy** [comment]
Scratch that last part - I was looking at the PR commit but I see there's been more going on in that file since then.

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon you approach makes  sense & yes we should  deprecate altering  those params - perhaps with a view to them no being pass-by-ref one day

Re ids - we can add a property on the Processor
$ids & give it a setter & getter

In  a perfect world we would grandfather out this hook in favour of one with a really clear contract (probably passing the output_specification array out) but yeah - let's just fix this.

If you can switch to 5.18 we can put out a patch release on 5.17 for this

**Comment by seamuslee001** [comment]
see also https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/issues/157

**Comment by seamuslee001** [comment]
@eileenmcnaughton ids was added in 2018 through this PR https://github.com/civicrm/civicrm-core/pull/12957 which was released in December 2018

**Comment by MegaphoneJon** [comment]
@scardinius I'm working on this now - but even though the docs say `$componentTable` and `$ids` can be passed by reference, I don't think there's any way to actually change the values such that the export is modified.  I looked at https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/pull/201 and it doesn't look like we need to allow passing by reference.  Let me know if that's incorrect!

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon this looks generally good - can you put against 5.18 when you are ready?

**Comment by MegaphoneJon** [comment]
@eileenmcnaughton Yes, once I finish my testing that the getter/setter works as intended.

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon great - thanks - we'll port to 5.17 & drop another release late this week / early next

**Comment by MegaphoneJon** [comment]
Closing in favor of https://github.com/civicrm/civicrm-core/pull/15286.

**Comment by scardinius** [comment]
> @scardinius I'm working on this now - but even though the docs say `$componentTable` and `$ids` can be passed by reference, I don't think there's any way to actually change the values such that the export is modified. I looked at [veda-consulting/uk.co.vedaconsulting.gdpr#201](https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/pull/201) and it doesn't look like we need to allow passing by reference. Let me know if that's incorrect!

@MegaphoneJon yes, exactly. It's not necessary to pass by reference those variables.

**Pull request closed without merging**
