### PR TITLE
Fix plural strings

### PR DESCRIPTION
**Pull request by colemanw**

### CODE REVIEW

**Comment by mlutfy** [comment]
Makes sense. +1 for proper use of `@count`.

To answer your question from IRC regarding the use of `@count` when in singular, there doesn't seem to be a strong convention about it, but I think it's more common to hardcode the number "1" than `@count`. I think it's probably easier for translators to understand that this really is singular, and should not have an impact on other languages.

For example, in some cases, translators may prefer to write "one" rather than "1".

PS: no worries about changing strings at this point. They are relatively few changes, and any improvements to strings, especially these examples, really help make CiviCRM easier to understand and to translate.

**Comment by colemanw** [comment]
Hmm, is the parser still buggy about trailing commas in an array? If so it's going to be a tug-of-war between the string parser and the style checker.
http://wiki.civicrm.org/confluence/display/CRMDOC/Internationalisation+for+Developers#InternationalisationforDevelopers-incodeIn-codestrings(PHP)

**Comment by mlutfy** [comment]
I think that @totten has fixed it in civistrings, but not 100% sure.

**Comment by totten** [comment]
It should be fixed - at least, I wrote a test-case and a passing patch. But my understanding of the parse logic is a bit shallow, so there could be edge-cases that I missed.

 * Commit (test data + parse logic): https://github.com/civicrm/civistrings/commit/a8d51116357d78aba29bb68947d98a60276034db
 * Test logic: https://github.com/civicrm/civistrings/blob/master/tests/Command/ExtractCommandTest.php

You can run "civistrings" directly on a PHP/JS/TPL/HTML file (or folder) to see if it outputs the expected POT. (Note: civistrings is included with buildkit.)

If there's a parsing problem, then we should add an example+patch.

**Pull request merged**
