### PR TITLE
CKEditor Advanced Options - Better validation of options

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----
In the "Advanced Options" of the CKEditor Configurator, api options can be selected. This tweaks the UI to prevent the same option from being selected twice, which would not make sense.

Before
-----
screenshot from 2018-03-02 09 44 36

After
------
screenshot from 2018-03-02 09 41 25

### CODE REVIEW

**Comment by colemanw** [comment]
@seamuslee001 since you were just in there, can you also take a look at this one? It should be straightforward.

**Comment by colemanw** [comment]
While I was at it I also added some validation for JSON input. This will prevent users from entering malformed JSON or raw javascript code.
screenshot from 2018-03-02 12 50 55

**Comment by seamuslee001** [comment]
will take a look @colemanw

**Comment by seamuslee001** [comment]
(*CiviCRM Review Template WORD-1.1*)

* ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) Pass
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) Pass
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) Pass
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) Pass
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) Pass
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) Pass ran the code, verified the validation and also verified that your not able to select the same option more than once
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) Pass
* ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) Pass

**Pull request merged**
