### PR TITLE
Afform - Unify 'is_dashlet', 'is_token' & 'contact_summary' as 'placement'

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Gather some hard-coded "placement" items into an option group. This makes future options easy to add, and easy for other extensions to contribute to.

Before
----------------------------------------
Adding a new "placement" option for Afforms requires modifying Afform getFields metadata *and* modifying the AfGuiEditor angular screen; neither would be easy for a contrib extension to do.
image

After
----------------------------------------
"Page Route" "Frontend" and "Add to Navigation Menu" remain unchanged, but 4 other placement flags have been gathered into an option group. Adding a new "placement" option is a simple matter of inserting an option value. New options will be available from the dropdown (the extension would still need to use some sort of hook to *do* something with Afforms that have that value selected).
image

Technical Details
----------------------------------------
This is backwards-compatible with existing forms: old format is converted on-demand whenever fetching Afforms with the API.

### CODE REVIEW

**Comment by totten** [comment]
Quick thoughts:

* Yeah, it is quite common to export/embed/integrate forms in other subsystems. So I generally like the idea of making it easier to do more of those.

* I like how the select2 widget feels... tidy.

* The concept of "Placement" seems to be like... _twiddly-bits for sharing/using/accessing in more ways_.

* I have to stretch my imagination to understand "Message Token" as a "Placement".  (There is a step of placing the form-reference in some
  concrete spot...  but you don't do that here.  The email/template/author decides where to place things.)

* I don't have any other great words.  Just brainstroming...  these are other phrases/concepts that come to mind: "Export", "Embed",
  "Outputs", "Output Media", "Views", "Integrations", "Entry Points", "Access Points", "Access Media", "Search Displays", "Embeddings",
  "Usages", "Features".

* "Page Route" and "Navigation Menu" strike me as fitting in thsi concept. The only difference is that they need additional data (route/path, title/label).
  In SK, I don't think you bothered the OG/boolean construct, tho? It went with "Search Display" - and it supported more properties for all of them?

* There was another discussion with aydun where he expressed interest in adding some authentication options for mail-tokens.

* I could see CORS packaging as another application of the concept. (You have twiddly bits to allow CORS, constrain domains/IPs, and get access-codes.)

* I  wonder if these add-on features would fit as "entities" with fields/values.  (Ex: "Page" entity with values for "path" and
  "is_public") But that might mean thinking more about the layout of the left-hand panel.

> This is backwards-compatible with existing forms: old format is converted on-demand whenever fetching Afforms with the API.

I have local form with `is_token=1`. Here's what I see

* If I load the PR, flush caches, and open the form... then the select2 widget shows "Message Token". So it's able to read old data files.
  Then I can save, and it writes out the `placement`.
* If I do search (or saved-search) which references a refactored-property (via `where` or `select`), then that stops working.
* (Perhaps a good example of how our tooling for upgrade/validation is lacking...)

**Comment by colemanw** [comment]
> I have to stretch my imagination to understand "Message Token" as a "Placement".

Yea, well, it was a boolean and thus ripe for the plucking! And it's not a terrible stretch to say you are "placing" the form into the token selector widget.

> I don't have any other great words. Just brainstroming...

I didn't feel like "Additional Placement" was the perfect phrase either, but at the late hour I made this PR I didn't want to be the enemy of good so I just hit "submit". But maybe "Additional Usages" is more broad, maybe with a bit of help text like "Other contexts in which this form can be used." ... what about that?

> If I do search (or saved-search) which references a refactored-property (via `where` or `select`), then that stops working.

Maybe I should have clarified that this is backwards-compatible with all *plausible* existing uses, rather than all *conceivable* uses. 😆  I'm willing to bet you the price of a 1st-class ticket to London that such a SavedSearch doesn't exist in `universe`. Because the very nature of these properties is that they are all handled by `@internal` Afform code and have never had any reason to be used publicly. But this PR seeks to change that... once this is merged the `placement` property will have potential `@public` usefulness to other extensions (so we'd need to be more careful with future refactors of it).

**Comment by vingle** [comment]
Really like this UX improvement.

> I didn't feel like "Additional Placement" was the perfect phrase either, but at the late hour I made this PR I didn't want to be the enemy of good so I just hit "submit". But maybe "Additional Usages" is more broad, maybe with a bit of help text like "Other contexts in which this form can be used." ... what about that?

Towards the top it says _'expose the form as standalone webpage'_ – could you reuse that verb? A message token would make sense to me as being exposed, as it's being made visible in the mailing UI.
e.g. 'Also expose as:' or 'Also expose form:' or 'Expose elsewhere:'?

**Comment by colemanw** [comment]
@totten @vingle thanks for your feedback. It seems the only hangup for this PR at this point is wordsmithing. I've taken your suggestions and updated the PR so the title & help text now look like this:

image

Adding `merge-ready` since all feedback has been addressed. If possible I'd like to merge this & then any other wording improvements can be a follow-up PR (honestly the entire UI could do with some copy editing).

**Comment by totten** [comment]
The phrase "Export To" does seem better. I do like the new widgets more than old widgets.

My hangups are more around the API contract. If we had a better game-plan for how to evolve the schema in these spaces, then I'd be good with this schema-change as an incremental improvement. (It's not the schema I would want in 2025, but... it's better than the schema of 2022.)

To my mind, the odds are 80-90% that the schema-change works out well.  (Which means: if we do this kind of thing once, then it is almost-definitely OK.  But if we do this kind of thing 10 times, then it almost-definitely isn't.)

It's not really a complaint about the PR. The PR is at par for the course. I wish the course was better - so that we had a safe way to make this kind change (without having to think things like: "In universe/ext/eck, it hacks into this specific API through an unpublished-event, so maybe it doesn't matter if the published API has a partial schema break").

**Pull request merged**
