### PR TITLE
CRM-20034 - CRM-20034 - Support OR grouping of api get params

### PR DESCRIPTION
**Pull request by colemanw**
* [CRM-20034: Support "OR" params in api get](https://issues.civicrm.org/jira/browse/CRM-20034)

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton Check this out:

apiexploreror2

**Comment by davialexandre** [comment]
@colemanw does this support conditions where the same field is used more than once? Like this: `(start_date >= '2016-01-01' AND (end_date <= '2016-01-01' OR end_date IS NULL))`

**Comment by ErichBSchulz** [comment]
hey this looks good - where does it fit wrt to the API4 efforts and my suggestion for a nest tree structure of AND|OR|NOT operations?

**Comment by colemanw** [comment]
@davialexandre the api3 has never supported adding the same param twice. It's on the roadmap for v4, come help us out over on that project! https://github.com/civicrm/api4

@ErichBSchulz this is a stopgap to provide basic OR support for v3. I suspect it will never get any fancier than this. What you're suggesting for v4 sounds good, let's focus our energies there.

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by ErichBSchulz** [comment]
sweet - ok thanks @colemanw

**Comment by eileenmcnaughton** [comment]
looks cool

**Comment by colemanw** [comment]
Thanks. I'm proud of my css tricks in the api explorer to visualize the and/or groupings.

**Pull request merged**
