### PR TITLE
CRM-16259 Add recordPartialPayment function and test.

### PR DESCRIPTION
**Pull request by davecivicrm**
---
- CRM-16259: Create Payment API
  https://issues.civicrm.org/jira/browse/CRM-16259

### CODE REVIEW

**Comment by mlutfy** [comment]
ok to test

**Comment by davecivicrm** [comment]
@pradpnayak @JoeMurray Marking this as Work In Progress since the new test for the getTotalPayments() method is actually failing.

**Comment by davecivicrm** [comment]
Adding in commits from @eileenmcnaughton PR https://github.com/davecivicrm/civicrm-core/pull/4

**Comment by davecivicrm** [comment]
Jenkins, retest this please.

**Comment by davecivicrm** [comment]
Jenkins, retest this please.

**Comment by eileenmcnaughton** [comment]
Closing in favour of https://github.com/civicrm/civicrm-core/pull/7546 which includes fixes for the enotices causing test failure

**Pull request closed without merging**
