### PR TITLE
CRM-19035: batch merge deleting incorrect contact

### PR DESCRIPTION
**Pull request by deepak-srivastava**
---
- CRM-19035: Batch merge deletes incorrect contact
  https://issues.civicrm.org/jira/browse/CRM-19035

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Ouch - that's confusing!!! That feels like the next breakage in the making - srcId = dstId? 

Note that the test that is failing is directly related and I wonder what version you actually tested your fix on? Because on 4.7.9 rc the issue of the filp the remaining problem is the columns are not being correctly described in the UI - ie on the batch screen the left hand contact is consistently kept & the right hand contact is consistently deleted (with respect for flipedness - but the labels suggest the reverse will happen). 

Notes just to keep my head sane on the terminology

entity1 is the 'to keep' contact & entity2 is to delete.
(the flip action updates the prev next cache table to swap the entity1 & entity2 contacts around).

In the api the original set up was to map 'main_id' to the one to go & 'other_id' to be the one to remove. I believe that this is wrong so the api now aliases those agains the promoted api fields: 
'to_keep_id' & 'to_remove_id'

I believe the params map as follows (with to_keep_id & to_remain_id being my preferred

to_keep_id = dstID = mainId
to_remove_id = srcID = otherId

(although for legacy reasons the api supports otherId = to_keep_id & mainId = to_remove_id)

**Comment by deepak-srivastava** [comment]
@eileenmcnaughton i 've added comment on ticket to support the fix. 
I did test it on 4.7.9 rc, understand the issue and agree with your comment that it breaks the convention but only for data-cache. I 've tried to explain. Please take a look and feedback. Thanks.

**Comment by eileenmcnaughton** [comment]
Just as an aside we do need to treat additional tests on this code as absolutely compulsory for any further changes (which is something we have done for the last 2 releases) as it has already proven itself to be fragile

**Comment by eileenmcnaughton** [comment]
I think this should be re-done against master. 

Note that the test is designed to ensure the details regarding the contact name etc match the id - which they don't after your changes to the test, meaning something is still broken

I think @JKingsnorth is going to take a look at whether we can store the lower ID on the correct side in the first instance & ditch 'autoflip' altogether?

**Pull request closed without merging**
