### PR TITLE
Use Case form for case email action

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Use Case specific email action form for case email action

Before
----------------------------------------
Handling for the case email action is overloaded onto the contact email action

After
----------------------------------------
it has it's own class

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@demeritcowboy I *think* this time I might have nailed moving the case stuff to it's own action form

**Comment by demeritcowboy** [comment]
Ok will take a look.

**Comment by eileenmcnaughton** [comment]
thanks @demeritcowboy

**Comment by demeritcowboy** [comment]
I've been playing with this a bit. Found my notes about the url params: https://lab.civicrm.org/dev/core/-/issues/2463

Something else is now messing with the regular email form and it gives errors about count() for contactIds. Must be recent. Let's see...

**Comment by demeritcowboy** [comment]
I think it's this one: https://github.com/civicrm/civicrm-core/pull/21680

**Comment by eileenmcnaughton** [comment]
@demeritcowboy argh - is it unchanged by this PR?

**Comment by demeritcowboy** [comment]
Applying this PR doesn't change the error.

**Comment by demeritcowboy** [comment]
I think the other one is simple, just checking closer.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy FYI the 3 threads I'm working on are
1) fix email to support missing token entities (membership, participant)
2) fix pdf to support participant tokens (I think the open PR is the last one in this thread)
3) fix metadata to load sanely & not advertise 'machine' tokens but still support them

**Comment by eileenmcnaughton** [comment]
@demeritcowboy so I'm guessing your other PR fixed ^^

**Comment by demeritcowboy** [comment]
> so I'm guessing your other PR fixed

Yes. Will try to finish this today.

**Comment by demeritcowboy** [comment]
So this is really close but it does break the situation where you have Email configured in your case activity list dropdown on Manage Case, which is the other way to reach this task. In that situation there is no cid to start, but now it's somehow setting it to an array and it ends up with the reverse situation as the other problem earlier where now it wants null instead, and then you get an error. I think I'd be ok to merge but not to release it this way.

jenkins retest this please

**Comment by eileenmcnaughton** [comment]
@demeritcowboy do you know what the fix is for that?

**Comment by demeritcowboy** [comment]
I haven't looked close but line 207 isn't expecting an empty array, and to avoid that normally it's null so it doesn't enter the `if`. But there's hopefully a clean fix.

**Comment by demeritcowboy** [comment]
```
CiviCRM_API3_Exception: "invalid criteria for IN"

#0 \CRM\Contact\Form\Task\EmailTrait.php(207): civicrm_api3("Contact", "get", (Array:4))
#1 \CRM\Core\Form.php(650): CRM_Case_Form_Task_Email->buildQuickForm()
#2 \CRM\Core\QuickForm\Action\Display.php(76): CRM_Core_Form->buildForm()
```

**Comment by eileenmcnaughton** [comment]
@demeritcowboy ah yeah - that's in code that is munged into preProcess too - ideally we would extract `$this->getContactDetails()` & it would return already-calculated-value if one exists or calculate one

**Comment by eileenmcnaughton** [comment]
Well merging this & we can track down that last little bit next

**Pull request merged**
