### PR TITLE
dev/core#907 Fix Deprecation notice for PHP7.2 in bin/cli.class.php

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
Title says it all

Before
----------------------------------------
Deprecation notice shows

After
----------------------------------------
No deprecation notice

ping @eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
jenkins is not happy @kcristiano can you  test this - these each ones hurt my brain for some reason so I think I'd rather we do run a proper test

**Comment by seamuslee001** [comment]
@eileenmcnaughton i created this little snippet of code

```
<?php
$array = [4,3,2,1];
while (list($k, $arg) = each($array)) {
  print_r("key {$k}, arg {$arg}\n");
}

foreach ($array as $k => $arg) {
  print_r("key {$k}, arg {$arg}\n");
}
``` 
which produced the following result

```
key 0, arg 4
key 1, arg 3
key 2, arg 2
key 3, arg 1
key 0, arg 4
key 1, arg 3
key 2, arg 2
key 3, arg 1
```

**Comment by kcristiano** [comment]
@eileenmcnaughton I have tested, and I am not seeing any errors in my logs.  But I was unable to reproduce without the patch either.

I've been using `cli.php` to run cron, is there a specific way to reproduce?

It does seem late to get this in to 5.13, would we be better off waiting to 5.14?

**Comment by seamuslee001** [comment]
@kcristiano you will need to be using PHP7.2 for your cron job and i think you may need to ensure you are outputting E_WARNING

**Comment by kcristiano** [comment]
@seamuslee001 Thanks.  Turns out my cli was 7.3 with limited reporting (Errors only)   I was able to reproduce by explicitly calling 7.2.   

The Patch corrects the notice.

**Pull request merged**
