### PR TITLE
Fix upgrade version for #13487

### PR DESCRIPTION
**Pull request by mfb**
Overview
----------------------------------------
#13487 referenced the wrong version in its schema update.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mfb @seamuslee001 does this have any practical impact - if so we should target the rc

**Comment by mfb** [comment]
I have no idea what these XML elements do but I thought it should be correct :)

**Comment by seamuslee001** [comment]
I don't think there is any practical impact of this specific field

**Comment by eileenmcnaughton** [comment]
OK master is fine then

**Pull request merged**
