### PR TITLE
CRM-18455: Don't corrupt address type on 'safe' merge

### PR DESCRIPTION
**Pull request by JKingsnorth**
- [CRM-18455: 'Safe merge' contacts designed to change address location type on conflict](https://issues.civicrm.org/jira/browse/CRM-18455)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Hey - if you'd like any help getting some tests happening with these let me know. I think the dedupe code needs more tests...

**Comment by JKingsnorth** [comment]
I agree - I'm actually trying to fix the tests. But every time I delve into it I see another issue in the code that needs resolving ;] Agreed that I should really be writing the tests first, and fixing the code afterwards.

**Comment by JKingsnorth** [comment]
Closing in favour of a unified PR (https://github.com/civicrm/civicrm-core/pull/8192). Otherwise I'm going to cause conflicts with my own development.

**Comment by JKingsnorth** [comment]
@eileenmcnaughton Is the logic in the merge tool correct that when you 'force' a merge it ignores any conflicts and keeps the details on the 'main' contact?

ie:
Main => Bat Man
Other => Cat Man
Force merge results in => Bat Man since the first names conflict, it keeps the 'main'

I couldn't find any documentation that says what should actually when when you 'force' merge. Safe merge obviously just throws the conflict and skips the merge.

**Comment by eileenmcnaughton** [comment]
I haven't looked into that yet- but I'm expecting to do some merge related work over the next few weeks & hopefully write some new tests. Potentially we could co-ordinate a working group in May's QA cycle

**Comment by JKingsnorth** [comment]
OK, for the time being I'll fix up the existing tests over in the other PR

**Pull request closed without merging**
