### PR TITLE
Actually validate prices; check for admin visibility;set defaults for pr...

### PR DESCRIPTION
**Pull request by zorgalina**
...ice, participant

1.) Adding 'discount' textbox doesn't do discounting - I submitted changes to CiviDiscount which adds the form name for ParticipantsAndPrices which will check if event is discountable and display the Discount code textbox
2.) Validation on array _values['fees'] didn't do validation, that array seems to be null
3.)  In build_price_options, add check for price fields that are meant to be 'admin only'
4.) In setDefaultValues, if participant is new, set their name, email if entered; set price defaults if they exist

### CODE REVIEW

**Comment by colemanw** [comment]
ok to test

**Comment by zorgalina** [comment]
Should I close these pull requests - were they submitted incorrectly? Also, I need to correct the one for Payment.php so, that should be closed/resubmitted right?

**Comment by davecivicrm** [comment]
You don't need to resubmit - you can push new commits to the same PR. The initial test failures are all related to code style issues such as superfluous white space at the end of lines.  You can click the Details tab on this page to see what needs to be fixed line by line: https://test.civicrm.org/job/CiviCRM-Core-PR/3185/checkstyleResult/new/

Also, is there a related issue for this in the Issue Tracker? If not, please create one and reference this PR. If there is already an issue, or after you've created one, please include it in your next commit message using this format: 'CRM-XXXX - description of commit goes here'

**Comment by zorgalina** [comment]
Thank you - I submitted an Issue, CRM-16481 (I had submitted PRs in
Cividiscount w/out creating Issues, perhaps that was not the right
procedure but they were merged in anyway).
I get a page not found/404 on the link you sent me for the style checking.
Browsing the build history on page
https://test.civicrm.org/job/CiviCRM-Core-PR/, I seem only to be able to go
back to build 3273; so I will submit another commit for these changes and
presume that'll give me a new result page for fixing the code.


On Wed, Apr 29, 2015 at 3:57 PM, Dave Greenberg <notifications@github.com>
wrote:

> You don't need to resubmit - you can push new commits to the same PR. The
> initial test failures are all related to code style issues such as
> superfluous white space at the end of lines. You can click the Details tab
> on this page to see what needs to be fixed line by line:
> https://test.civicrm.org/job/CiviCRM-Core-PR/3185/checkstyleResult/new/
>
> Also, is there a related issue for this in the Issue Tracker? If not,
> please create one and reference this PR. If there is already an issue, or
> after you've created one, please include it in your next commit message
> using this format: 'CRM-XXXX - description of commit goes here'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/5678#issuecomment-97609726>.
>



-- 
زورگلنه ءء لسلی

**Comment by davecivicrm** [comment]
jenkins, test this please

**Comment by davecivicrm** [comment]
I've requested rebuild of the test results. We definitely need an issue in Jira for core changes like this w/ details on the changes and fixes you are proposing. Thanks!

**Comment by davecivicrm** [comment]
Lesley - Click 'new warnings' link and the Details tab so see the style warnings. These need to be corrected before the full 'code test' runs. As noted above, you can submit more commits against this PR w/ the style fixes and the test will run again. Jump on IRC to discuss if needed.

**Comment by zorgalina** [comment]
Thank you I will look at the Warnings link (I couldn't find the build link
you sent before)

On Mon, May 11, 2015 at 11:15 AM, Dave Greenberg <notifications@github.com>
wrote:

> Lesley - Click 'new warnings' link and the Details tab so see the style
> warnings. These need to be corrected before the full 'code test' runs. As
> noted above, you can submit more commits against this PR w/ the style fixes
> and the test will run again. Jump on IRC to discuss if needed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/5678#issuecomment-101003590>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
From looking at Checkstyle Warnings in Plain Text - it seems it is due to
not having a JUnit file associated w/these - I will try IRC

On Mon, May 11, 2015 at 8:24 PM, Lesley Evensen <zorgalina@gmail.com> wrote:

> Thank you I will look at the Warnings link (I couldn't find the build link
> you sent before)
>
> On Mon, May 11, 2015 at 11:15 AM, Dave Greenberg <notifications@github.com
> > wrote:
>
>> Lesley - Click 'new warnings' link and the Details tab so see the style
>> warnings. These need to be corrected before the full 'code test' runs. As
>> noted above, you can submit more commits against this PR w/ the style fixes
>> and the test will run again. Jump on IRC to discuss if needed.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/civicrm/civicrm-core/pull/5678#issuecomment-101003590>
>> .
>>
>
>
>
> --
> زورگلنه ءء لسلی
>



-- 
زورگلنه ءء لسلی

**Comment by colemanw** [comment]
jenkins, retest this please

**Comment by colemanw** [comment]
@zorgalina it would be awesome if you could clean up the whitespace issues flagged at https://test.civicrm.org/job/CiviCRM-Core-PR/4662/checkstyleResult/new/

**Comment by zorgalina** [comment]
thanks I will

On Sat, Aug 1, 2015 at 7:43 PM, colemanw <notifications@github.com> wrote:

> @zorgalina <https://github.com/zorgalina> it would be awesome if you
> could clean up the whitespace issues flagged at
> https://test.civicrm.org/job/CiviCRM-Core-PR/4662/checkstyleResult/new/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/5678#issuecomment-126982485>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by davecivicrm** [comment]
Leslie - you can make fixes on your branch, commit and push to Github and that will update this PR automatically. Then we can "ask Jenkins" to rerun the PR tests.

**Comment by zorgalina** [comment]
Apologies for not doing this more quickly - I need to do this locally (I
thought I was able to switch to my branch and edit in Github online and
couldn't recall how)

On Mon, Aug 3, 2015 at 10:09 AM, Dave Greenberg <notifications@github.com>
wrote:

> Leslie - you can make fixes on your branch, commit and push to Github and
> that will update this PR automatically. Then we can "ask Jenkins" to rerun
> the PR tests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/5678#issuecomment-127333605>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
I edited the files from my branch, committed and made the push, acc'ding to
directions here (
http://wiki.civicrm.org/confluence/display/CRMDOC/GitHub+for+CiviCRM),
steps 5-6,

On Mon, Aug 3, 2015 at 12:00 PM, Lesley Evensen <zorgalina@gmail.com> wrote:

> Apologies for not doing this more quickly - I need to do this locally (I
> thought I was able to switch to my branch and edit in Github online and
> couldn't recall how)
>
> On Mon, Aug 3, 2015 at 10:09 AM, Dave Greenberg <notifications@github.com>
> wrote:
>
>> Leslie - you can make fixes on your branch, commit and push to Github and
>> that will update this PR automatically. Then we can "ask Jenkins" to rerun
>> the PR tests.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/civicrm/civicrm-core/pull/5678#issuecomment-127333605>
>> .
>>
>
>
>
> --
> زورگلنه ءء لسلی
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
Committed updates for CRM 16761 (self svc cancel/xfer), Cart Payments,ParticipantsandPayments white space issues CRM #14591

**Pull request closed without merging**
