### PR TITLE
add support for Redis as caching server

### PR DESCRIPTION
**Pull request by herbdool**
https://issues.civicrm.org/jira/browse/CRM-17401

### CODE REVIEW

**Comment by colemanw** [comment]
ok to test

**Comment by totten** [comment]
Ah, cool. A few things:

 * Jenkins reports some style issues. You can see them at https://test.civicrm.org/job/CiviCRM-Core-PR/6000/checkstyleResult/new/ (under "Details" or "Warnings")
 * If you'd like to locally check compliance with the code style, see http://wiki.civicrm.org/confluence/display/CRMDOC/Testing ("Code style tests").
 * It would also be good to add Redis to the list of 'memory' style caches -- https://github.com/herbdool/civicrm-core/blob/59e560215c83e278f1c8d829f52124a83ddc0b95/CRM/Utils/Cache.php#L183
 * There are some unrelated style warnings in `civicrm.settings.php.template`. It's a funny file (it's not exactly PHP but looks like PHP). With the current scope of this patch, I think it would be OK to merge despite that.

**Comment by herbdool** [comment]
I've made style corrections (skipping the template file) and added Redis to memory type of cache.

**Comment by kurund** [comment]
@herbdool Can you check and fix: https://test.civicrm.org/job/CiviCRM-Core-PR/6020/checkstyleResult/new/file.-1806158019/source.763/#93

**Comment by herbdool** [comment]
@kurund what am I looking for? What am I supposed to fix? I don't have credentials for Jenkins as far as I know. It's just blank for me.

**Comment by kurund** [comment]
@herbdool it's an extra blank like hence the style check is failing

**Comment by kurund** [comment]
@herbdool actually check https://test.civicrm.org/job/CiviCRM-Core-PR/6020/checkstyleResult/new/file.-1806158019/ this migt be easier to understand

**Comment by herbdool** [comment]
okay, fixed.

**Pull request merged**
