### PR TITLE
CRM- 20552

### PR DESCRIPTION
**Pull request by yashodha**

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by yashodha** [comment]
@jitendrapurohit can you please test this. This is a clean up from the previously merged PR https://github.com/civicrm/civicrm-core/pull/10332

**Review by jitendrapurohit — APPROVED** [review]
Tested "Add contacts to individual, household and organization" with the PR applied. All tasks were performed correctly without any errors.

**Comment by yashodha** [comment]
merging as per confirmation from @jitendrapurohit

**Pull request merged**
