### PR TITLE
Add privacy fields to ContributionDetail report

### PR DESCRIPTION
**Pull request by alexymik**
Add all privacy fields as columns on the Member Contribution Detail report

Before
----------------------------------------
Do Not Email

After
----------------------------------------
Do Not Phone
Do Not Email
Do Not Mail
Do Not SMS
Do Not Trade

### CODE REVIEW

**Comment by seamuslee001** [comment]
This looks good to me

**Comment by MegaphoneJon** [comment]
I think the move has been to use `$this->getColumns('Contact')` instead of adding columns to reports on a case-by-case basis.  https://github.com/civicrm/civicrm-core/pull/16458 is a similar PR for inspiration.

**Comment by jaapjansma** [comment]
test this please

**Comment by jaapjansma** [comment]
* General standards
    * Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
        * __PASS__ : The goal/problem/solution have been adequately explained in the PR.
    * User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
        * __PASS__: The change would be intuitive or unnoticeable.
    * Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
        * __PASS__: The changes do not require documentation.
    * Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
        * __PASS__: We have tested this with and without this PR on the Membership and Contribution detail report and the columns are available and working.
* Developer standards
    * Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
        * __PASS__: The change preserves compatibility with existing callers/code/downstream.
    * Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
        * __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
    * Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
        * __PASS__: The change is trivial enough that it does not require tests.
    * Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
        * __PASS__: The test results are all-clear.

@mattwire  or @eileenmcnaughton could you merge this PR?

**Pull request merged**
