### PR TITLE
SearchKit - Support the `Group.parents` field

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Enables `Group.parents` field to function correctly in SearchKit.

Before
----------------------------------------
Create a Search for Groups. Add "Parents" column. It displays nothing.

After
----------------------------------------
Works.

Technical Details
----------------------------------------
This adds a 2nd field to the schema with `options.prefetch = false` (the first being Campaigns) This time the field is serialized and not a real FK, but `prefetch=false` makes sense because of the potentially very large number of groups in the database. In order to accommodate that I enabled SK to lookup FK entity from the `pseudoconstant` metadata, in case there are any more weird fields like this, they will work!

Comments
----------------------------------------
This change subtly changes the way the "Campaign" column works, e.g. when doing a search for Contributions and showing "Campaigns" the `prefetch=false` pseudoconstant continues to not load options client-side, but now it *does* use the option list when rendering values (instead of a join) and it removes the confusing dual fields "Campaign ID" and "Campaign Title" in favor of just "Campaign". Requires #25995

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Hmm that title looks like one of those teachable examples of why it matters where you put the comma

**Comment by colemanw** [comment]
@eileenmcnaughton I've updated the title to clarify that I'm not starting a SearchKit Support Group.
Although maybe we need one of those too!

**Comment by samuelsov** [comment]
@colemanw Mostly works but I'm not able to remove a parent once added (reproduced and dmaster) :

Peek 17-04-2023 15-33

**Comment by colemanw** [comment]
Ok thanks @samuelsov I'll do a followup PR to fix the inline-edit.

**Comment by colemanw** [comment]
@samuelsov it's a bug in the BAO. I haven't solved it but have made #26074 to clarify and document the problem.

**Pull request merged**
