### PR TITLE
CRM-21575 - Websites of same type are over-written

### PR DESCRIPTION
**Pull request by yashodha**
Overview
----------------------------------------
Steps to replicate

 - Add website of same type to contact.
 - The second one overwrites the first one.

Before
----------------------------------------
Websites of same type are over-written.

After
----------------------------------------
Able to save websites of same type.

---

 * [CRM-21575: Websites of same type are over-written](https://issues.civicrm.org/jira/browse/CRM-21575)

### CODE REVIEW

**Comment by Elennio** [comment]
I replicate here with the correction and its working great!

**Comment by colemanw** [comment]
* ([`r-jira`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-jira)) __Pass__
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __Pass__
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __Pass__
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __Pass__
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __Pass__
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __Pass:__ Replicated the issue in the UI and then tested the patch in the UI and api explorer to ensure it saves correctly.
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __Pass:__ No impact
* ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __Pass:__ Simplifies code

**Comment by agh1** [comment]
It appears that this has caused a regression where a new website entry is created every time someone fills a profile that has a value in a website field.  See [CRM-21735](https://issues.civicrm.org/jira/browse/CRM-21735).

**Comment by agh1** [comment]
Just a quick note that I've opened #11634 against `4.7.30-rc` to revert this just because the release is coming in 30 hours or so, but if there's a fix in the meantime, that of course would be better.  I just don't know the phone and email code well enough to feel confident writing a proper fix.

**Comment by eileenmcnaughton** [comment]
I merged the revert - I think that is a good 'first line' response

**Pull request merged**
