### PR TITLE
Activity tab performance fix - switch to faster getActivities & getActivitiesCount

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Performance improvement on loading activity tab on contacts

Before
----------------------------------------
Tab slow to load

After
----------------------------------------
Tab fast to load. 

WMF have been running this in production for some time as the activity tab code being removed was taking so long we got white screens on contacts with many activities. The tab loads well with this

Technical Details
----------------------------------------
The getActivitiesCount & getActivities functions are faster & call permission hooks
but we weren't able to switch to them until we resolved some performance issues
(done) and resolved acl inconsistencies (resolved in 5.12) -we can do this now.

From a performance POV the difference is tab-crashes vs tab resolves quickly
on contacts with > 10k activities

Comments
----------------------------------------
I would note that we don't use cases - I feel like this has been tested with cases in the past but it would be good to have a civicase user give it a spin

We also added a lot of tests in the past in preparation for this

@mattwire @colemanw @monishdeb - I think we can finally do this!

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I think it failed on not-previously enabled checks but something to dig into

**Comment by eileenmcnaughton** [comment]
The test did a good job of catching some issues with the date filter - fixed now

**Comment by colemanw** [comment]
@eileenmcnaughton - err, according to the diff you are deleting the file `CRM/Activity/BAO/Activity.php`. That can't be right.

**Comment by eileenmcnaughton** [comment]
@colemanw no - I'm just removing 500 lines of code from it

**Comment by colemanw** [comment]
Wow. You're deleting a 500 line function! That's gotta be some kind of record. :1st_place_medal:

**Comment by eileenmcnaughton** [comment]
:-)

**Comment by colemanw** [comment]
* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __Pass__
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __Pass__: No impact
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __Pass__
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __Pass__:Activity tab still works as expected
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __Pass__: :1st_place_medal: 
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __Pass__
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __Pass__
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __Pass__

**Comment by eileenmcnaughton** [comment]
thanks @colemanw !

**Pull request merged**
