### PR TITLE
Invoice template: Add function to update message tokens during upgrade

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
In conjunction with https://github.com/civicrm/civicrm-core/pull/20867

Overview
----------------------------------------
This is the upgrader for https://github.com/civicrm/civicrm-core/pull/20867 - I thought it was included in that PR in the end but it wasn't

Before
----------------------------------------
Upgraded installs still use the old param

After
----------------------------------------
They use the new param

Technical Details
----------------------------------------

Comments
----------------------------------------
@mlutfy I thought, incorrectly, this had already been merged

### CODE REVIEW

**Comment by colemanw** [comment]
```
PHP Parse error:  syntax error, unexpected ')', expecting variable (T_VARIABLE) in CRM/Upgrade/Incremental/General.php on line 170
```

**Comment by eileenmcnaughton** [comment]
yeah that would do it

**Comment by mlutfy** [comment]
I updated the title so that it's more clear in release notes.

I gave this an `r-run`, from 5.40 to 5.41alpa1 (master branch) and seems to work well.

Before:

civicrm-invoice-before-2021-07-28_14-17

After:

civicrm-invoice-after-2021-07-28_14-18

And PDF works as before:

civicrm-invoice-pdf-2021-07-28_14-19

**Comment by mlutfy** [comment]
And neat update function :)

Thanks @eileenmcnaughton !

**Pull request merged**
