### PR TITLE
(dev/core#255) Changes to copied event location reflects in original …

### PR DESCRIPTION
**Pull request by yashodha**
…event location

Overview
----------------------------------------
Steps to replicate:

1. Create an event X with location A.
2. Create copy of event X say Y and go to location tab for event Y (which will now show location A).
3. Click _Create new location_ radio and then click _Use existing location_, choose option B.
4. Check event X also has location B.

Before
----------------------------------------
 changed event location rather than create new location - original event location gets changed as well.

After
----------------------------------------
only copied event location gets changed.

### CODE REVIEW

**Comment by yashodha** [comment]
@lcdservices Can you please confirm the same as you fixed this in https://github.com/civicrm/civicrm-core/pull/12104

**Comment by lcdservices** [comment]
@yashodha @eileenmcnaughton I reviewed and this looks good. I ran through the testing steps prior to applying the PR and could reproduce the issue. I then applied the PR and confirmed the new/copied event's location does not affect the original event.

**Comment by yashodha** [comment]
@lcdservices thanks!

**Comment by kngs** [comment]
It fixed for me on one Joomla site.  It still doesn't work on another site but it has other javascript (backbone) issues so might still be causing conflicts.  But good on first! Thank you :)

**Comment by eileenmcnaughton** [comment]
thanks for the quick & clear review @lcdservices & for the patch @yashodha

**Pull request merged**
