### PR TITLE
authx - Add configuration screen

### PR DESCRIPTION
**Pull request by kainuk**
Overview
----------------------------------------

This extends the functionality of https://github.com/civicrm/civicrm-core/pull/19727 and adds a configuration screen. This will help with configuring for use with https://github.com/CiviMRF. 

After 
--------------------------------------------
 
Selection_034

Screenshot from 2022-02-05 13-59-02

### CODE REVIEW

**Comment by jaapjansma** [comment]
test this please

**Comment by totten** [comment]
jenkins, test this please

**Comment by totten** [comment]
@kainuk Oooh, I really like that you added a configuration screen!

I notice this branch didn't bring over the description or the test-coverage from #19727. It makes sense -- the tests were still failing due to the `X-Requested-With: XMLHttpRequest` issue. I think maybe we should use #19727 to add the LegacyAuthenticator and its test-coverage -- then use #22058 to add the configuration screen. To that end....

(1) I've ported your fix for `protected function login(AuthenticatorTarget $tgt)` to #19727 and added a fix for `XMLHttpRequest`.

(2) I tried out the new config screen, and it was working. 👍 Kind of impressed that it worked with so little code. I haven't lookd at `CRM_Admin_Form_Generic` much. How hard would it be to either (a) display some of the help/description text for the settings and/or (b) arrange some of the settings in a table so that it's easier to skim.

**Comment by BettyDolfing** [comment]
test this please

**Comment by BettyDolfing** [comment]
test this please

**Comment by totten** [comment]
jenkins, test this please

_Process note_: Something quirky happened with Github. Contemporaneous with the previous comment, I force-pushed a very small copyedit (*adding like 2-5 words; end commit eafc90f7cfd6e0ef4a3201aa44b6316f28dcd02c*), but it didn't appear in web UI for 15+ min, and it didn't send a webhook.

**Comment by totten** [comment]
_Process note_: Hrm, Github also hasn't sent the webhook for `test this please`.

Well, there's a test-run for a nearly identical commit https://test.civicrm.org/job/CiviCRM-Core-PR/46962/ which we can use instead...

**Comment by colemanw** [comment]
It took a while but the test run eventually started

**Pull request merged**
