### PR TITLE
5.48

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
Not sure what to do with civicrm_generated - this may fail tests, but we could regen in master after.

@seamuslee001 @colemanw

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Going to merge but then will redo regen because civicrm_generated does have 5.48 in it.

**Comment by colemanw** [comment]
Probably no rush on that, there's still 3 weeks till master becomes 5.49 @demeritcowboy and forward-merges are easier this way.

**Comment by demeritcowboy** [comment]
Except won't PR tests be using some 5.48 data instead of the latest-greatest until it's re-regen'd?

**Comment by colemanw** [comment]
I dunno release management is more @totten's area.

**Comment by demeritcowboy** [comment]
Or for people making local dev sites from master with sample data their installed version will appear to be 5.48 at first.

**Comment by totten** [comment]
Yeah, if `5.48` rebuilt `civicrm_generated.mysql` and you merge-forward the change (eg `civicrm_navigation.tpl`), then it's best to regen on `master` as well.

Merged the corresponding PR for `master`'s `civicrm_generated.mysql`.

**Pull request merged**
