### PR TITLE
[REF] Move generic preProcess function to the trait

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Code consolidation on forms to send emails - no change to  functionality

Before
----------------------------------------
PreProcess function duplicated

After
----------------------------------------
Shared function on the shared trait

Technical Details
----------------------------------------
Note this  is overriden on the contact email form

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw can you also check this - this is the trait I'm cleaning up to use the entity reference

**Comment by totten** [comment]
FWIW, grepping on where the trait is used finds:

```
(1) CRM/Activity/Form/Task/Email.php:  use CRM_Contact_Form_Task_EmailTrait;
(2) CRM/Contact/Form/Task/Email.php:  use CRM_Contact_Form_Task_EmailTrait;
(3) CRM/Contribute/Form/Task/Email.php:  use CRM_Contact_Form_Task_EmailTrait;
(4) CRM/Event/Form/Task/Email.php:  use CRM_Contact_Form_Task_EmailTrait;
(5) CRM/Member/Form/Task/Email.php:  use CRM_Contact_Form_Task_EmailTrait;
```

This PR removes identical `preProcess()` functions from all the consumers except (2). Item (2) already has a rather different implementation of `preProcess()`. However, my understanding of this situation is that `CRM/Contact/Form/Task/Email.php` would continue to use its own variant of `preProcess()`.

**Comment by eileenmcnaughton** [comment]
@totten - yep it does

**Comment by colemanw** [comment]
Makes sense.

**Comment by colemanw** [comment]
I double checked the [php traits docs](https://www.php.net/manual/en/language.oop5.traits.php) just to make sure. The **Example # 3 Alternate Precedence Order Example** shows that a method declared in a class using a trait overrides the same method from the trait.

**Pull request merged**
