### PR TITLE
Fix contribution online receipt to be, somewhat, previewable

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fix contribution online receipt to be, somewhat, previewable

Before
----------------------------------------
Trying to preview online contribution templates draws a blank

After
----------------------------------------
The line item & tax fields I fixed up for offline & invoice are showing up well now....

image

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@demeritcowboy are you able to look at this - similar to the other two contribution templates (offline & invoice)

**Comment by demeritcowboy** [comment]
The main thing is I see $totalTaxAmount has been mostly removed but there are still some references and they give an undefined notice, and the Amount Before Tax is wrong (which is a logical consequence). I'm talking about the real receipt not preview.

For currencies on preview, I see the same thing as in your screenshot, where the currency is wrong for half of it - but only seems to be in the preview and the real receipt seems ok.

And I thought we fixed removing the time component in the receipt date but I might be getting which templates are which mixed up.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy re "$totalTaxAmount has been mostly removed but there are still some references and they give an undefined notice" - is that a regression already in core - or one created in this PR?

**Comment by demeritcowboy** [comment]
It doesn't seem to be from this PR. I was thinking it might depend how you generate the receipt but it seems to always be missing. Can't be too old since you'd think somebody would have noticed, but it appears missing in 5.52 at least.

**Comment by demeritcowboy** [comment]
https://lab.civicrm.org/dev/financial/-/issues/206

**Pull request merged**
