### PR TITLE
Copy convertToDefaultDate back into only calling function, deprecate

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Copy convertToDefaultDate back into only calling function, deprecate

Before
----------------------------------------
`convertToDefaultDate ` is called from one place - `CRM_Utils_Date::formatDate()` which itself is only called from the import code.
The separation of concerns between these 2 function does not make sense & adds to the complexity

After
----------------------------------------
code from `convertToDefaultDate `  copied back to `CRM_Utils_Date::formatDate()`. The former is now deprecated

Technical Details
----------------------------------------
Only outside usages are some old code in civi-hr which seems otherwise broken but deprecation added rather than removal 

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
The only references in universe I can find to this is 

```
ext/civihr/hrjobcontract/CRM/Hrjobcontract/Import/Parser/Api.php:      CRM_Utils_Date::convertToDefaultDate($params, $dateType, $key);
ext/uk.co.compucorp.civicrm.prospect/CRM/Prospect/ProspectCustomGroups.php:      CRM_Utils_Date::convertToDefaultDate($dateArray, 1, 'value');
```

**Comment by eileenmcnaughton** [comment]
@seamuslee001 - yeah I did ping on chat about whether we should remove those from universe - less sure about prospect but CiviHR is defunct as I understand it


(rebased)

**Comment by eileenmcnaughton** [comment]
https://github.com/civicrm/civicrm-core/pull/28841 builds on this (adds more tests too)

**Comment by eileenmcnaughton** [comment]
This got merged in https://github.com/civicrm/civicrm-core/pull/28841 - looks like there is some small difference so conflicted

**Pull request closed without merging**
