### PR TITLE
CRM-19389: Fatal Error in Forms (4.7.12 Regression)

### PR DESCRIPTION
**Pull request by monishdeb**
- [CRM-19389: Fatal Error in Forms (4.7.12 Regression)](https://issues.civicrm.org/jira/browse/CRM-19389)

### CODE REVIEW

**Review by seamuslee001 — APPROVED** [review]

**Comment by seamuslee001** [comment]
Test failure seems unrelated

**Comment by monishdeb** [comment]
Merging now

**Comment by totten** [comment]
Thanks, generally +1 for this change.

I delayed a bit on merging because I wanted to do a search to find other potential impacts. The original change from my PR is in a gray-area contract-wise:
 * On one hand, there was a conflict within civicrm-core wherein one class referred to the `protected` properties from other classes. This creates a bug - fixable by changing to `public`.
 * On the other hand, changing from `protected` to `public` seems to have broken some subclasses (i.e. subclasses which redeclared the properties and reaffirmed the original `protected` status).
 * Then again, those classes have no business redeclaring the properties. This is not say that PHP makes it completely illegal, but it's confusing design ([discussion of property redeclaration in PHP](https://gist.github.com/totten/8a1efedf512add98e3e808796b0eac63)). In all the cases I've seen so far, I'm pretty sure we could just omit the redeclaration and get the exact same behavior.
 * But a break is a break. What if there's some other, unrecognized class in core that breaks? What if some third party extension breaks?

Which turns this into a practical question... are there others? To answer, I used [`civibuild create universe`](https://github.com/civicrm/civicrm-buildkit/commit/5f7c38fcd1791bb0201fc753103953fd8f2ce904)  to fetch as much Civi code as possible (core + published extensions). Out of ~150 repos, there are ~19 files which *may* declare `protected $_action` (mostly in `civicrm-core`):

```
$ grep -r 'protected \$_action;' -l | wc
     19      19     880
```

Of course, we only care about them if they're subclasses of `CRM_Core_Form`, so let's see that:

```
$ grep 'class.*extends' $( grep -r 'protected \$_action;' -l )
civicrm-core/CRM/Activity/Selector/Search.php:class CRM_Activity_Selector_Search extends CRM_Core_Selector_Base implements CRM_Core_Selector_API {
civicrm-core/CRM/Campaign/Selector/Search.php:class CRM_Campaign_Selector_Search extends CRM_Core_Selector_Base implements CRM_Core_Selector_API {
civicrm-core/CRM/Case/Selector/Search.php:class CRM_Case_Selector_Search extends CRM_Core_Selector_Base {
civicrm-core/CRM/Contact/Page/View.php:class CRM_Contact_Page_View extends CRM_Core_Page {
civicrm-core/CRM/Contact/Selector/Custom.php:class CRM_Contact_Selector_Custom extends CRM_Contact_Selector {
civicrm-core/CRM/Contact/Selector.php:class CRM_Contact_Selector extends CRM_Core_Selector_Base implements CRM_Core_Selector_API {
civicrm-core/CRM/Contribute/Selector/Search.php:class CRM_Contribute_Selector_Search extends CRM_Core_Selector_Base implements CRM_Core_Selector_API {
civicrm-core/CRM/Core/Page/Basic.php:abstract class CRM_Core_Page_Basic extends CRM_Core_Page {
civicrm-core/CRM/Event/Selector/Search.php:class CRM_Event_Selector_Search extends CRM_Core_Selector_Base implements CRM_Core_Selector_API {
civicrm-core/CRM/Grant/Selector/Search.php:class CRM_Grant_Selector_Search extends CRM_Core_Selector_Base implements CRM_Core_Selector_API {
civicrm-core/CRM/Mailing/Page/Browse.php:class CRM_Mailing_Page_Browse extends CRM_Core_Page {
civicrm-core/CRM/Mailing/Selector/Search.php:class CRM_Mailing_Selector_Search extends CRM_Core_Selector_Base implements CRM_Core_Selector_API {
civicrm-core/CRM/Member/Selector/Search.php:class CRM_Member_Selector_Search extends CRM_Core_Selector_Base implements CRM_Core_Selector_API {
civicrm-core/CRM/Pledge/Selector/Search.php:class CRM_Pledge_Selector_Search extends CRM_Core_Selector_Base {
org.civicoop.documents/CRM/Documents/Form/Document.php:class CRM_Documents_Form_Document extends CRM_Core_Form {
org.civicoop.documents/CRM/Documents/Form/NewVersion.php:class CRM_Documents_Form_NewVersion extends CRM_Core_Form {
org.civicoop.documents/CRM/Documents/Selector/Search.php:class CRM_Documents_Selector_Search extends CRM_Core_Selector_Base implements CRM_Core_Selector_API {
uk.co.compucorp.civicrm.booking/CRM/Booking/Selector/Search.php:class CRM_Booking_Selector_Search extends CRM_Core_Selector_Base implements CRM_Core_Selector_API {
```

These results tell us a few things:
 * There are two classes (`CRM_Documents_Form_Document` and `CRM_Documents_Form_NewVersion` in `org.civicoop.documents`) which may need an update. I've opened a PR: https://github.com/CiviCooP/org.civicoop.documents/pull/2 (FYI ping @jaapjansma)
 * `CRM_Core_Selector_Base` appears to have a similar situation as `CRM_Core_Form` -- subclasses gratuitously redeclaring `$_action`, mostly likely because some original class made a mistake which was copy-pasted. However, we don't have the same impetus for cleanup here (since there isn't a suspicious external access).

Note: I'm not deeply attached to changing `CRM_Core_Form::$_action` to `public` - it just looked like the simplest thing at the time. If anyone has an objection, we could switch back to `protected` and change any suspicious/external references (`grep -r 'form.*>_action'`) to use getter/setter methods. But at the moment inertia favors the change to `CRM_Core_Form { public $_action }`.

**Comment by monishdeb** [comment]
Thanks for your feedback @totten :) Well since we were getting fatal errors on various pages and as per your earlier PR I thought this would be the best thing to do. As an alternative I was thought what if we don't redeclare on subclasses rather then changing the access modifier from ```protected``` to ```public```

**Comment by monishdeb** [comment]
bdw ```civibuild create universe``` nice :) 👍

**Pull request merged**
