### PR TITLE
Add more info to recurring contribution edit activity

### PR DESCRIPTION
**Pull request by ejegg**
Overview
----------------------------------------
Adds info about changes in the cycle day or next scheduled contribution date to the activity created when editing a recurring contribution.

Before
----------------------------------------
If you edit the cycle day and the next scheduled contribution date of a recurring contribution they are not mentioned in the edit activity.

After
----------------------------------------
If you edit the cycle day and the next scheduled contribution date of a recurring contribution the old and new values are mentioned in the edit activity, e.g.:
> Cycle day has been updated from 1 to 16 for this subscription.
> Next scheduled contribution date has been updated from to 2024-02-16 for this subscription. 

Technical Details
----------------------------------------
Includes a couple of small cleanup patches

[dev/core#5008](https://lab.civicrm.org/dev/core/-/issues/5008)

### CODE REVIEW

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by colemanw** [comment]
Looks like this overlaps with #28617

**Comment by mattwire** [comment]
@ejegg Sorry I separated and merged the cleanup commits and tried to rebase but messed it up. Your actual functional change is here : https://github.com/civicrm/civicrm-core/commit/2bea756643b51060e51518e8414e7b8d87eaf63b.diff but I can't work out how to get it back into your branch... Might be easier if you can push and open a new PR?

**Comment by ejegg** [comment]
Thanks @mattwire, I've redone the last bit at https://github.com/civicrm/civicrm-core/pull/29564

**Pull request closed without merging**
