### PR TITLE
{drowning-support-needed} Embed Seach display in summary screen

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
@colemanw after meticulously  working through the detailed instructions here https://docs.civicrm.org/dev/en/latest/afform/overview/#embedding  I tried & failed to embed a search display in the summary screen from an import - help

Note that the import creates searches but not an afform - hence I tried with a completely different form (also because the instructions were a bit vague on how I would refer to the one I manually created....)

### CODE REVIEW

**Comment by colemanw** [comment]
LOL ok @eileenmcnaughton I'm happy to help in the morning, but the first step is to get the search display working within an actual Afform, in the exact same way that the `civicrm_admin_ui` extension does it, you want to package a SavedSearch+SearchDisplay within an `.mgd.php` file in the extension, embed it in an afform and also package that afform within the extension in the `ang/` directory.
This should be exactly like it's done in `civicrm_admin_ui` or any other extension that packages SearchDisplays + Afforms. The only difference is going to be that instead of placing that Afform at a standalone URL we'll embed it in the page. I'm happy to help with that step once you do the 1st bit.

**Comment by eileenmcnaughton** [comment]
@colemanw I can't package `.aff` files - because these are dynamic entities..... Can chat tomorrow

**Comment by colemanw** [comment]
@eileenmcnaughton can this be closed now? I think you got it working elsewhere...

**Comment by eileenmcnaughton** [comment]
@colemanw yes - this is not my latest attempt

**Pull request closed without merging**
