### PR TITLE
CRM-16195

### PR DESCRIPTION
**Pull request by MegaphoneJon**
This is my code toward relative date filters.  Given the renewed interest, and also just the size of this code change, I think perhaps I should schedule a 10-minute phone call with a core team person to explain/demo the changes?

---
- [CRM-16195: Give users the ability to create relative date filters for reports and searches](https://issues.civicrm.org/jira/browse/CRM-16195)

### CODE REVIEW

**Comment by davecivicrm** [comment]
Jon - One of us will get back to you to coordinate demo / code review shortly.

**Comment by eileenmcnaughton** [comment]
Jon,

I took a look at this & split it into 2 parts

1) the data storage conversion. I created a PR for this & am keen to see it double-checked & merged
https://github.com/civicrm/civicrm-core/pull/6693
Note that I personally think the order of the date filters is wrong & that This Week, This Year should be at the top - but think that can be discussed after

2) The form work - I squashed all this into 1 commit which I have not done any testing / QA for. I don't think the form work is a blocker to getting value from the data storage work but the data storage is a blocker for the form. So, lets get 1 merged & then you can see where 2 is at 
https://github.com/eileenmcnaughton/civicrm-core/commit/697241b7a296fda07a26ed404a153624eb8031a1

**Comment by eileenmcnaughton** [comment]
I think we should close this. You can grab https://github.com/eileenmcnaughton/civicrm-core/commit/697241b7a296fda07a26ed404a153624eb8031a1 & turn that into a PR for the form if you want - the other part is merged

**Comment by eileenmcnaughton** [comment]
@PalanteJon I'm closing this per my earlier comment - the work you did is not lost - it's summarised into the PR per my last link. But I doubt this PR is going to be revised per se (& I think you have some much quicker wins in your 'PRs I should tidy up for merge to-do list') so I'm going to close it out until you are ready to recreate it or a version of it.

**Pull request closed without merging**
