### PR TITLE
(dev/core#316) Fix crash on Memcache systems when session key involves whitespace

### PR DESCRIPTION
**Pull request by xurizaemon**
Overview
----------------------------------------
As reported @ https://lab.civicrm.org/dev/core/issues/316, there seems to be an issue with Memcache compatibility - keys generated by Cache::cleanKey() permit whitespace, which Memcache does not allow.

This patch addresses the bug and also micro-optimizes some cache logic.

Before
----------------------------------------
* Caching with Memcache does not work -- because the cache-keys used for session-management includes spaces. Report @ https://chat.civicrm.org/civicrm/pl/yo7drhis3pgg3cemfzuctd6ixr
* When reading from the cache, `cleanKey()` is called twice in a row.

After
----------------------------------------
* Hopefully CiviCRM will function with Memcache again. Untested.
* When reading from the cache, `cleanKey()` is called once.

Technical Details
----------------------------------------
Changes cache keys, so may indicate that we should run a cache reset. (But if caching is sane, that shouldn't be required?)

Comments
----------------------------------------

Note for reviewing: Since this issue was reported by a user who upgraded to an official release, there's an implication to me that we don't have memcache as part of our test matrix. This would then require manual testing (perhaps by the affected user) to confirm the fix (or I guess inclusion of memcache in our test matrix).

### CODE REVIEW

**Comment by totten** [comment]
(*CiviCRM Review Template WORD-1.1*)



* ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __Pass__ - I updated the title & description.
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) 
    * __Needs work__ - Could you update `CRM_Core_BAO_CacheTest`? (Incidentally, the test failure seems to indicate that the `cleanKey()` patch is filtering whitespace as expected.)
    * There's tangential/related test-coverage in `tests/phpunit/E2E/Cache/`, but the test-box only runs the tests in a stock MySQL-only environment. So I ran them manually and confirmed they pass with `Redis`, `Memcache`, and `Memcached` drivers.
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __Pass__
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __Pass__
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __Pass__: Agree with your assessment that tests should be run in more environments. That would be good follow-up project, but it doesn't need to block this PR.
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __Unreviewed__: Agree with Chris's comments about this - would be great if @christianwach could try the patch and see if it fixes the problem.
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __Pass__
* ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __Pass__: Any code using `cleanKey()` necessarily has some constraints with how it can use the cache service, but this code is already using `cleanKey()`. I don't think tweaking the algorithm has a substantive affect on the contract (as perceived by cache-using code).

Regarding this:

> Changes cache keys, so may indicate that we should run a cache reset. (But if caching is sane, that shouldn't be required?)

Agree it should be OK as-is. The impact here is changing the effective-key used in memcache for anything involving a space. However, if the effective-key had a space in it before, then it was broken already, and the cache wouldn't be filled.

---

@xurizaemon since this is a recent regression, could you rebase the patch to target the RC branch (`5.5`)? After we merge it into the RC, then we can follow-up with (a) backport to stable (`5.4`) and (b) bulk merge-forward to `master`.

**Comment by xurizaemon** [comment]
Have pushed an additional commit that would hopefully catch this ... let me know if that works!

**Comment by christianwach** [comment]
@xurizaemon One further issue I've run into is that Extensions cannot be installed while Memcached is being used:

```
$Fatal Error Details = array(3) {
  ["message"]=>
  string(19) "Unknown extension: "
  ["code"]=>
  NULL
  ["exception"]=>
  object(CRM_Extension_Exception_MissingException)#6982 (10) {
    ["errorData":"CRM_Core_Exception":private]=>
    array(1) {
      ["error_code"]=>
      int(0)
    }
    ... lots more debugging ...
```

As you can see, `$key` is empty in `CRM_Extension_Container_Collection::getContainer()` - I presume this is as a result of `CRM_Extension_Container_Collection::getKeysToContainer()` grabbing the containers with:

```
$k2c = $this->cache->get($this->cacheKey);
```

FWIW, turning Memcached _off_ allows me to install Extensions.

**Comment by christianwach** [comment]
Apologies in advance if there's too much debugging info below - I've tried to debug the Install Extension process but I get lost in the intricacies of `HTML_QuickForm` so I thought dumping everything I can see might help. The problem in `CRM_Extension_Container_Collection::getContainer()` is that `$key` is not defined:

```
Array
(
    [method] => CRM_Extension_Container_Collection::getContainer
    [key] => 
    [k2c] => Array
        (
            [com.iatspayments.civicrm] => civiroot
            [org.civicrm.shoreditch] => default
        )

    [backtrace] => #0 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Extension/Container/Collection.php(111): CRM_Extension_Container_Collection->getContainer(NULL)
#1 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Extension/Mapper.php(185): CRM_Extension_Container_Collection->getPath(NULL)
#2 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Admin/Form/Extensions.php(85): CRM_Extension_Mapper->keyToInfo(NULL)
#3 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(585): CRM_Admin_Form_Extensions->preProcess()
#4 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Core/StateMachine.php(136): CRM_Core_Form->buildForm()
#5 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Next.php(61): CRM_Core_StateMachine->perform(Object(CRM_Admin_Form_Extensions), 'next', 'Next')
#6 /path/to/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Admin_Form_Extensions), 'next')
#7 /path/to/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Admin_Form_Extensions), 'next')
#8 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle('next')
#9 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Core/Page/Basic.php(398): CRM_Core_Controller->run()
#10 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Core/Page/Basic.php(156): CRM_Core_Page_Basic->edit(1, NULL)
#11 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Admin/Page/Extensions.php(121): CRM_Core_Page_Basic->run()
#12 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(309): CRM_Admin_Page_Extensions->run(Array, NULL)
#13 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem(Array)
#14 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke(Array)
#15 /path/to/wp-content/plugins/civicrm/civicrm.php(1246): CRM_Core_Invoke::invoke(Array)
#16 [internal function]: CiviCRM_For_WordPress->invoke('')
#17 /path/to/wp-includes/class-wp-hook.php(286): call_user_func_array(Array, Array)
#18 /path/to/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#19 /path/to/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#20 /path/to/wp-admin/admin.php(224): do_action('toplevel_page_C...')
#21 {main}
)
```

Debugging further up the line in `CRM_Admin_Form_Extensions::preProcess()` shows the context, though it still doesn't show me exactly why `$key` is undefined:

```
Array
(
    [method] => CRM_Admin_Form_Extensions::preProcess
    [key] => 
    [id] => 
    [GET] => Array
        (
            [page] => CiviCRM
            [q] => civicrm/admin/extensions
            [noheader] => 1
        )

    [POST] => Array
        (
            [qfKey] => 926b1c386f5b9c64184e995104741f62_6496
            [_qf_default] => Extensions:next
            [_qf_Extensions_next] => Install
        )

    [REQUEST] => Array
        (
            [page] => CiviCRM
            [q] => civicrm/admin/extensions
            [noheader] => 1
            [qfKey] => 926b1c386f5b9c64184e995104741f62_6496
            [_qf_default] => Extensions:next
            [_qf_Extensions_next] => Install
        )

    [backtrace] => #0 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(585): CRM_Admin_Form_Extensions->preProcess()
#1 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Core/StateMachine.php(136): CRM_Core_Form->buildForm()
#2 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Next.php(61): CRM_Core_StateMachine->perform(Object(CRM_Admin_Form_Extensions), 'next', 'Next')
#3 /path/to/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Admin_Form_Extensions), 'next')
#4 /path/to/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Admin_Form_Extensions), 'next')
#5 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle('next')
#6 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Core/Page/Basic.php(398): CRM_Core_Controller->run()
#7 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Core/Page/Basic.php(156): CRM_Core_Page_Basic->edit(1, NULL)
#8 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Admin/Page/Extensions.php(121): CRM_Core_Page_Basic->run()
#9 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(309): CRM_Admin_Page_Extensions->run(Array, NULL)
#10 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem(Array)
#11 /path/to/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke(Array)
#12 /path/to/wp-content/plugins/civicrm/civicrm.php(1246): CRM_Core_Invoke::invoke(Array)
#13 [internal function]: CiviCRM_For_WordPress->invoke('')
#14 /path/to/wp-includes/class-wp-hook.php(286): call_user_func_array(Array, Array)
#15 /path/to/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#16 /path/to/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#17 /path/to/wp-admin/admin.php(224): do_action('toplevel_page_C...')
#18 {main}
)
```

Here's what `CRM_Admin_Form_Extensions` looks like at the above moment:

```
    [this] => CRM_Admin_Form_Extensions Object
        (
            [_id:protected] => 
            [_values:protected] => Array
                (
                )

            [_BAOName:protected] => CRM_Core_BAO_Extension
            [_state:protected] => 
            [_name:protected] => Extensions
            [_title:protected] => 
            [_defaults] => Array
                (
                )

            [_options] => 
            [_action] => 1
            [_paymentProcessors:protected] => 
            [_paymentProcessorIDs] => 
            [_paymentProcessorID:protected] => 
            [_is_pay_later_enabled:protected] => 
            [_renderer:protected] => 
            [_dateFields:protected] => Array
                (
                )

            [unsavedChangesWarn:protected] => 
            [ajaxResponse] => Array
                (
                )

            [urlPath] => Array
                (
                    [0] => civicrm
                    [1] => admin
                    [2] => extensions
                )

            [context:protected] => 
            [controller] => CRM_Core_Controller_Simple Object
                (
                    [_title:protected] => CRM_Admin_Form_Extensions
                    [_key] => 926b1c386f5b9c64184e995104741f62_6496
                    [_scope:protected] => CRM_Admin_Form_Extensions_926b1c386f5b9c64184e995104741f62_6496
                    [_stateMachine:protected] => CRM_Core_StateMachine Object
                        (
                            [_controller:protected] => CRM_Core_Controller_Simple Object
 *RECURSION*
                            [_states:protected] => Array
                                (
                                    [Extensions] => CRM_Core_State Object
                                        (
                                            [_name:protected] => Extensions
                                            [_type:protected] => 3
                                            [_back:protected] => 
                                            [_next:protected] => 
                                            [_stateMachine:protected] => CRM_Core_StateMachine Object
 *RECURSION*
                                        )

                                )

                            [_pages:protected] => Array
                                (
                                    [CRM_Admin_Form_Extensions] => 
                                )

                            [_pageNames:protected] => Array
                                (
                                    [0] => Extensions
                                )

                            [_action:protected] => 0
                            [_name:protected] => 
                        )

                    [_embedded:protected] => 1
                    [_skipRedirection:protected] => 
                    [_print] => 0
                    [_generateQFKey] => 1
                    [_QFResponseType] => html
                    [_parent:protected] => 
                    [_destination] => 
                    [_entryURL] => 
                    [_pages] => Array
                        (
                            [Extensions] => CRM_Admin_Form_Extensions Object
 *RECURSION*
                        )

                    [_actions] => Array
                        (
                            [Extensions] => HTML_QuickForm_Action_Direct Object
                                (
                                )

                            [display] => CRM_Core_QuickForm_Action_Display Object
                                (
                                    [_stateMachine:protected] => CRM_Core_StateMachine Object
                                        (
                                            [_controller:protected] => CRM_Core_Controller_Simple Object
 *RECURSION*
                                            [_states:protected] => Array
                                                (
                                                    [Extensions] => CRM_Core_State Object
                                                        (
                                                            [_name:protected] => Extensions
                                                            [_type:protected] => 3
                                                            [_back:protected] => 
                                                            [_next:protected] => 
                                                            [_stateMachine:protected] => CRM_Core_StateMachine Object
 *RECURSION*
                                                        )

                                                )

                                            [_pages:protected] => Array
                                                (
                                                    [CRM_Admin_Form_Extensions] => 
                                                )

                                            [_pageNames:protected] => Array
                                                (
                                                    [0] => Extensions
                                                )

                                            [_action:protected] => 0
                                            [_name:protected] => 
                                        )

                                )

                            [next] => CRM_Core_QuickForm_Action_Next Object
                                (
                                    [_stateMachine:protected] => CRM_Core_StateMachine Object
                                        (
                                            [_controller:protected] => CRM_Core_Controller_Simple Object
 *RECURSION*
                                            [_states:protected] => Array
                                                (
                                                    [Extensions] => CRM_Core_State Object
                                                        (
                                                            [_name:protected] => Extensions
                                                            [_type:protected] => 3
                                                            [_back:protected] => 
                                                            [_next:protected] => 
                                                            [_stateMachine:protected] => CRM_Core_StateMachine Object
 *RECURSION*
                                                        )

                                                )

                                            [_pages:protected] => Array
                                                (
                                                    [CRM_Admin_Form_Extensions] => 
                                                )

                                            [_pageNames:protected] => Array
                                                (
                                                    [0] => Extensions
                                                )

                                            [_action:protected] => 0
                                            [_name:protected] => 
                                        )

                                )

                            [back] => CRM_Core_QuickForm_Action_Back Object
                                (
                                    [_stateMachine:protected] => CRM_Core_StateMachine Object
                                        (
                                            [_controller:protected] => CRM_Core_Controller_Simple Object
 *RECURSION*
                                            [_states:protected] => Array
                                                (
                                                    [Extensions] => CRM_Core_State Object
                                                        (
                                                            [_name:protected] => Extensions
                                                            [_type:protected] => 3
                                                            [_back:protected] => 
                                                            [_next:protected] => 
                                                            [_stateMachine:protected] => CRM_Core_StateMachine Object
 *RECURSION*
                                                        )

                                                )

                                            [_pages:protected] => Array
                                                (
                                                    [CRM_Admin_Form_Extensions] => 
                                                )

                                            [_pageNames:protected] => Array
                                                (
                                                    [0] => Extensions
                                                )

                                            [_action:protected] => 0
                                            [_name:protected] => 
                                        )

                                )

                            [process] => CRM_Core_QuickForm_Action_Process Object
                                (
                                    [_stateMachine:protected] => CRM_Core_StateMachine Object
                                        (
                                            [_controller:protected] => CRM_Core_Controller_Simple Object
 *RECURSION*
                                            [_states:protected] => Array
                                                (
                                                    [Extensions] => CRM_Core_State Object
                                                        (
                                                            [_name:protected] => Extensions
                                                            [_type:protected] => 3
                                                            [_back:protected] => 
                                                            [_next:protected] => 
                                                            [_stateMachine:protected] => CRM_Core_StateMachine Object
 *RECURSION*
                                                        )

                                                )

                                            [_pages:protected] => Array
                                                (
                                                    [CRM_Admin_Form_Extensions] => 
                                                )

                                            [_pageNames:protected] => Array
                                                (
                                                    [0] => Extensions
                                                )

                                            [_action:protected] => 0
                                            [_name:protected] => 
                                        )

                                )

                            [cancel] => CRM_Core_QuickForm_Action_Cancel Object
                                (
                                    [_stateMachine:protected] => CRM_Core_StateMachine Object
                                        (
                                            [_controller:protected] => CRM_Core_Controller_Simple Object
 *RECURSION*
                                            [_states:protected] => Array
                                                (
                                                    [Extensions] => CRM_Core_State Object
                                                        (
                                                            [_name:protected] => Extensions
                                                            [_type:protected] => 3
                                                            [_back:protected] => 
                                                            [_next:protected] => 
                                                            [_stateMachine:protected] => CRM_Core_StateMachine Object
 *RECURSION*
                                                        )

                                                )

                                            [_pages:protected] => Array
                                                (
                                                    [CRM_Admin_Form_Extensions] => 
                                                )

                                            [_pageNames:protected] => Array
                                                (
                                                    [0] => Extensions
                                                )

                                            [_action:protected] => 0
                                            [_name:protected] => 
                                        )

                                )

                            [refresh] => CRM_Core_QuickForm_Action_Refresh Object
                                (
                                    [_stateMachine:protected] => CRM_Core_StateMachine Object
                                        (
                                            [_controller:protected] => CRM_Core_Controller_Simple Object
 *RECURSION*
                                            [_states:protected] => Array
                                                (
                                                    [Extensions] => CRM_Core_State Object
                                                        (
                                                            [_name:protected] => Extensions
                                                            [_type:protected] => 3
                                                            [_back:protected] => 
                                                            [_next:protected] => 
                                                            [_stateMachine:protected] => CRM_Core_StateMachine Object
 *RECURSION*
                                                        )

                                                )

                                            [_pages:protected] => Array
                                                (
                                                    [CRM_Admin_Form_Extensions] => 
                                                )

                                            [_pageNames:protected] => Array
                                                (
                                                    [0] => Extensions
                                                )

                                            [_action:protected] => 0
                                            [_name:protected] => 
                                        )

                                )

                            [reload] => CRM_Core_QuickForm_Action_Reload Object
                                (
                                    [_stateMachine:protected] => CRM_Core_StateMachine Object
                                        (
                                            [_controller:protected] => CRM_Core_Controller_Simple Object
 *RECURSION*
                                            [_states:protected] => Array
                                                (
                                                    [Extensions] => CRM_Core_State Object
                                                        (
                                                            [_name:protected] => Extensions
                                                            [_type:protected] => 3
                                                            [_back:protected] => 
                                                            [_next:protected] => 
                                                            [_stateMachine:protected] => CRM_Core_StateMachine Object
 *RECURSION*
                                                        )

                                                )

                                            [_pages:protected] => Array
                                                (
                                                    [CRM_Admin_Form_Extensions] => 
                                                )

                                            [_pageNames:protected] => Array
                                                (
                                                    [0] => Extensions
                                                )

                                            [_action:protected] => 0
                                            [_name:protected] => 
                                        )

                                )

                            [done] => CRM_Core_QuickForm_Action_Done Object
                                (
                                    [_stateMachine:protected] => CRM_Core_StateMachine Object
                                        (
                                            [_controller:protected] => CRM_Core_Controller_Simple Object
 *RECURSION*
                                            [_states:protected] => Array
                                                (
                                                    [Extensions] => CRM_Core_State Object
                                                        (
                                                            [_name:protected] => Extensions
                                                            [_type:protected] => 3
                                                            [_back:protected] => 
                                                            [_next:protected] => 
                                                            [_stateMachine:protected] => CRM_Core_StateMachine Object
 *RECURSION*
                                                        )

                                                )

                                            [_pages:protected] => Array
                                                (
                                                    [CRM_Admin_Form_Extensions] => 
                                                )

                                            [_pageNames:protected] => Array
                                                (
                                                    [0] => Extensions
                                                )

                                            [_action:protected] => 0
                                            [_name:protected] => 
                                        )

                                )

                            [jump] => CRM_Core_QuickForm_Action_Jump Object
                                (
                                    [_stateMachine:protected] => CRM_Core_StateMachine Object
                                        (
                                            [_controller:protected] => CRM_Core_Controller_Simple Object
 *RECURSION*
                                            [_states:protected] => Array
                                                (
                                                    [Extensions] => CRM_Core_State Object
                                                        (
                                                            [_name:protected] => Extensions
                                                            [_type:protected] => 3
                                                            [_back:protected] => 
                                                            [_next:protected] => 
                                                            [_stateMachine:protected] => CRM_Core_StateMachine Object
 *RECURSION*
                                                        )

                                                )

                                            [_pages:protected] => Array
                                                (
                                                    [CRM_Admin_Form_Extensions] => 
                                                )

                                            [_pageNames:protected] => Array
                                                (
                                                    [0] => Extensions
                                                )

                                            [_action:protected] => 0
                                            [_name:protected] => 
                                        )

                                )

                            [submit] => CRM_Core_QuickForm_Action_Submit Object
                                (
                                    [_stateMachine:protected] => CRM_Core_StateMachine Object
                                        (
                                            [_controller:protected] => CRM_Core_Controller_Simple Object
 *RECURSION*
                                            [_states:protected] => Array
                                                (
                                                    [Extensions] => CRM_Core_State Object
                                                        (
                                                            [_name:protected] => Extensions
                                                            [_type:protected] => 3
                                                            [_back:protected] => 
                                                            [_next:protected] => 
                                                            [_stateMachine:protected] => CRM_Core_StateMachine Object
 *RECURSION*
                                                        )

                                                )

                                            [_pages:protected] => Array
                                                (
                                                    [CRM_Admin_Form_Extensions] => 
                                                )

                                            [_pageNames:protected] => Array
                                                (
                                                    [0] => Extensions
                                                )

                                            [_action:protected] => 0
                                            [_name:protected] => 
                                        )

                                )

                            [upload] => CRM_Core_QuickForm_Action_Upload Object
                                (
                                    [_uploadNames:protected] => Array
                                        (
                                            [0] => attachFile_1
                                            [1] => attachFile_2
                                            [2] => attachFile_3
                                            [3] => uploadFile
                                        )

                                    [_uploadDir:protected] => /path/to/wp-content/plugins/files/civicrm/upload/
                                    [_stateMachine:protected] => CRM_Core_StateMachine Object
                                        (
                                            [_controller:protected] => CRM_Core_Controller_Simple Object
 *RECURSION*
                                            [_states:protected] => Array
                                                (
                                                    [Extensions] => CRM_Core_State Object
                                                        (
                                                            [_name:protected] => Extensions
                                                            [_type:protected] => 3
                                                            [_back:protected] => 
                                                            [_next:protected] => 
                                                            [_stateMachine:protected] => CRM_Core_StateMachine Object
 *RECURSION*
                                                        )

                                                )

                                            [_pages:protected] => Array
                                                (
                                                    [CRM_Admin_Form_Extensions] => 
                                                )

                                            [_pageNames:protected] => Array
                                                (
                                                    [0] => Extensions
                                                )

                                            [_action:protected] => 0
                                            [_name:protected] => 
                                        )

                                )

                        )

                    [_name] => CRM_Admin_Form_Extensions_926b1c386f5b9c64184e995104741f62_6496
                    [_modal] => 1
                    [_actionName] => Array
                        (
                            [0] => Extensions
                            [1] => next
                        )

                )

            [_chainSelectFields:CRM_Core_Form:private] => Array
                (
                )

            [_actions] => Array
                (
                )

            [_formBuilt] => 1
            [_elements] => Array
                (
                )

            [_elementIndex] => Array
                (
                )

            [_duplicateIndex] => Array
                (
                )

            [_required] => Array
                (
                )

            [_jsPrefix] => Invalid information entered.
            [_jsPostfix] => Please correct these fields.
            [_datasource] => 
            [_defaultValues] => Array
                (
                )

            [_constantValues] => Array
                (
                )

            [_submitValues] => Array
                (
                    [qfKey] => 926b1c386f5b9c64184e995104741f62_6496
                    [_qf_default] => Extensions:next
                    [_qf_Extensions_next] => Install
                )

            [_submitFiles] => Array
                (
                )

            [_maxFileSize] => 41943040
            [_freezeAll] => 
            [_rules] => Array
                (
                )

            [_formRules] => Array
                (
                )

            [_errors] => Array
                (
                )

            [_requiredNote] => <span style="font-size:80%; color:#ff0000;">*</span><span style="font-size:80%;"> denotes required field</span>
            [_flagSubmitted] => 1
            [_attributes] => Array
                (
                    [action] => https://islamichistorycommons.org/wp-admin/admin.php?page=CiviCRM&q=civicrm/admin/extensions
                    [method] => post
                    [name] => Extensions
                    [id] => Extensions
                    [class] => CRM_Admin_Form_Extensions
                )

            [_tabOffset] => 0
            [_tab] => 	
            [_lineEnd] => 

            [_comment] => 
            [_key] => 
        )
```

So, somewhere at some point, the `_key` property is not being set. 

@totten Can you suggest how I might be able to pinpoint what's going on?

**Comment by christianwach** [comment]
@totten A little more info: when Memcached is *not* being used, the URL sequence is as follows:

* The "Install" page is: https://domain.org/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Fextensions&action=add&id=org.civicrm.shoreditch&key=org.civicrm.shoreditch
* The resulting location is: https://domain.org/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Fextensions&reset=1&action=browse

When Memcached *is* being used:

* The "Install" page is: https://domain.org/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Fextensions&action=add&id=org.civicrm.shoreditch&key=org.civicrm.shoreditch
* The resulting location is: https://domain.org/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Fextensions

As I said, I'll happily test further given pointers as to where to keep digging.

**Comment by totten** [comment]
I've filed the extension-install issue as https://lab.civicrm.org/dev/core/issues/336

**Pull request merged**
