### PR TITLE
dev/wordpress#86 Ensure that the list of groups in search or on the n…

### PR DESCRIPTION
**Pull request by seamuslee001**
…ew individual screen reflect any ACLs applied on them

Overview
----------------------------------------
As per the linked [lab ticket](https://lab.civicrm.org/dev/wordpress/-/issues/86)

Before
----------------------------------------
List of groups shown on search and on new individual screen do not respect ACLs in WordPress

After
----------------------------------------
Do respect ACLs in WordPress

Technical Details
----------------------------------------
This applies the same logic that has been used for Drupal to WordPress. I suspect that because extensions like the Multisite permissions extension do modifications on the list of groups after this code has occurred it shouldn't make any difference to them.

ping @kcristiano @JoeMurray

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 it's not exactly the same code is it? Because they do share a common parent

**Comment by seamuslee001** [comment]
@eileenmcnaughton this groups handling is in the DrupalBase version see https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/Permission/DrupalBase.php#L23 where as the WordPress extends off the Base.php which just returns all groups. Note DrupalBase AFAIK is used for Drupal8, Drupal, Drupal6, Backdrop

**Comment by eileenmcnaughton** [comment]
@seamuslee001 so this long chunk of code appears to be exactly the same as the one in Drupal Base. If we merge this we will have 2 copies of it to support CMS per 

- Drupal6, Drupal7, Drupal8, Backdrop - use copy of code in DrupalBase
- Wordpress - uses exact copy of code but copied to it's own class
- Joomla! does not use code.

If that is the case we should be able to avoid copying the code by putting the shared code in the base class & doing small overrides in Joomla!

**Comment by kcristiano** [comment]
@seamuslee001 I can test once we determine if this will be the PR or there will be changes.

**Comment by seamuslee001** [comment]
I have shifted this into the Base.php file, lets see what Jenkins makes of it

**Comment by seamuslee001** [comment]
Test Failures look like they were associated with caching so have switched to Civi::$statics

**Comment by seamuslee001** [comment]
@kcristiano I think this is ready for you to test now

**Comment by seamuslee001** [comment]
@kcristiano have you had a chance to test this yet?

**Comment by kcristiano** [comment]
@seamuslee001 Yes I've done a bit on it.  Trying to setup a valid test with Multi-site Extension as well.  I hope to report back soon.

**Comment by kcristiano** [comment]
@seamuslee001 I can both replicate the issue and confirm the fix works on Single Site.

On WP Multi-Site it's a bit trickier as we already have the Mult-Site extension in place.   What is the expected behavior?

I am building a clean Multi-site to test, as my current test Multisite is pretty rough around the edges.

**Comment by kcristiano** [comment]
@seamuslee001 I think it's good to merge.

I see no difference with/without on MultiSite if using the MultiSite extensions as expected.   

This permission  `CiviCRM Multisite: list all groups in domain ` seems to take precedence.

**Comment by andyburnsco** [comment]
On WP multisite, no groups show in basic search or adv search for users restricted to their domain group via https://lab.civicrm.org/extensions/multisite. These users have `CiviCRM Multisite: list all groups in domain` permission.  Groups do show in search builder. 

So, what makes a group in a domain? Related: https://lab.civicrm.org/dev/core/-/issues/1924.

There is civicrm_group_organization and also a zz_civicrm_group_organization table? I had thought adding a group to the domain's default organization which that is set via domain_org_id in civicrm.settings.php and in civicrm_domain table contact_id) was how a group was 'in a domain'.

This change has effect from showing all groups to no groups, except for search builder workaround, which now gives ID as result rather than group name.

image

**Comment by seamuslee001** [comment]
@andyburnsco it is the present of a group in the civicrm_group_organization table as per https://lab.civicrm.org/extensions/multisite/-/blob/master/multisite.php#L452, Did you also check to see if there were any parent/child group relationships between the domain group and those groups. 

if you want the group organization field to show up on the group edit form you will need to make sure that the Administer Multiple Organizations permission/capability has been granted https://github.com/civicrm/civicrm-core/blob/7dc9cb422d359515633c466ad1d1526db9c25bfc/CRM/Group/Form/Edit.php#L461

**Comment by andyburnsco** [comment]
There is no `administer Multiple Organizations` perm at example.org/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Faccess%2Fwp-permissions&reset=1

**Comment by andyburnsco** [comment]
Removing this commit was only route to getting groups to show again. For me, listing all groups to all users is fine and preferable over group search missing entirely. This is what WP users have been used to. My understanding is that this was Drupal based functionality. Users can only see the contacts they are permissioned to in whatever group it is as well. Using multisite.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 ^^

**Comment by andyburnsco** [comment]
Noting that that is on 5.35.2. We are unable to upgrade Civi successfully to latest version to see if it behaves differently. Working on on it per https://lab.civicrm.org/dev/core/-/issues/2827

**Comment by seamuslee001** [comment]
@andyburnsco as far as I am concerned this functionality has never been CMS based. There is absolutely nothing in hook_civicrm_aclGroup that dealt with CMS specific issues. Your issue is strongly likely an extension or something interfering. We have had multiple WordPress sites on 5.35.2 and none have had those problems and we have had at least 2 separate projects where we have had to use hook_civicrm_aclGroup on wordpress sites to control the listing of groups and they have both worked fine

**Comment by andyburnsco** [comment]
What I see is the only groups that show for a domain user on MS are the ones that are tied to the domain organization. I can see that making sense for some use cases, but not all. This undercuts a multisite benefit in seeing "global groups" and then only the contacts they can see within those. Otherwise you start making the redundant group for each domain. That doesn't make sense. 

Thoughts? 

Am I describing the intended behavior correctly?

Civi 5.45.2

**Comment by seamuslee001** [comment]
@andyburnsco as far as I am aware that with multisite extension it is designed to only show groups linked to that domain organization unless you have I think the permission to manage multiple organizations. https://lab.civicrm.org/extensions/multisite/-/blob/master/multisite.php#L183 and their child groups I believe.

**Pull request merged**
