### PR TITLE
(WIP) CRM-19366: Updated EntityFinancialTrxn.xml

### PR DESCRIPTION
**Pull request by behradkhodayar**
Changed `onDelete` status, according to issue #CRM-19366. Closes #CRM-19366 :-)

---
- [CRM-19366: Change civicrm_entity_financial_trxn fk to itself to CASCADE](https://issues.civicrm.org/jira/browse/CRM-19366)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@NDFA Behradm you ened to re run  bin/regen,sh and also need to put in code into the upgrade to convert sites that already have the foreign key to be on cascade delete

**Comment by pradpnayak** [comment]
+1 for the fix. I agree with @seamuslee001 there should be upgrade code to update the ON DELETE rule. I think we should also add upgrade script to delete orphan data from civicrm_entity_financial_trxn table

**Comment by NDFA** [comment]
@seamuslee001  & @pradpnayak I'll get back to you soon with the update. TY

**Comment by JoeMurray** [comment]
jenkins, please test

**Comment by JoeMurray** [comment]
@colemanw the tests are stuck - could you advise or fix? thx

**Comment by seamuslee001** [comment]
@NDFA Behrad this is probably a good example for you to look at for the upgrade script https://github.com/civicrm/civicrm-core/blob/master/CRM/Upgrade/Incremental/php/FourSeven.php#L734.

**Comment by seamuslee001** [comment]
@JoeMurray I think it needs someone with a Jenkins credential to say ok to test.

**Comment by monishdeb** [comment]
Jenkin, ok to test

**Comment by monishdeb** [comment]
Marked [WIP] for upgrade fix.

**Comment by NDFA** [comment]
_Sorry Dudes! I was [super busy](http://www.lotsofjokes.com/busy_day-img-996.jpg)_
@seamuslee001 Seamus added the upgrade function to incremental `FourSeven.class` & updated 4_7_12.
@pradpnayak Fortunately I found no orphan data left away! But truth to be told, I'm not sure enough!

**Comment by NDFA** [comment]
Should I make a new PR?

**Comment by seamuslee001** [comment]
@NDFA Can you do the following git rebase -i (civicrm/civicrm-core repo alias)/master

**Comment by seamuslee001** [comment]
@NDFA once you have done that can you then move https://github.com/civicrm/civicrm-core/pull/9073/files#diff-9f26e5128facbeee21f13196222a7e1cR249 to the 4_7_13 upgrade function

**Review by colemanw — CHANGES_REQUESTED** [review]
Sorry I'm not sure what you've done here but this PR shows 208 commits and 166 files changed. A typical PR has only 1 or two.
You might want to start over by making sure you are on a clean copy of the master branch, making your change and pushing to your fork. Alternately you can submit PRs from this website by browsing the code and clicking "edit" on the file you want to suggest your changes for.

**Comment by NDFA** [comment]
Its Ok to reject the PR, but kinda situation(w/ plenty commits & ...) occurs during rebase/merge. I do agree such a PR yields in a dirty git log, but after all the feature is added correctly.

Anyway, I'll push the changes in another PR. TY.

**Pull request closed without merging**
