### PR TITLE
add hidden support to addField, convert Edit_Lock and Inline_Lock

### PR DESCRIPTION
**Pull request by mallezie**
This adds hidden support to addField, and converts the first inline form to use it. 
First part of https://issues.civicrm.org/jira/browse/CRM-16178

### CODE REVIEW

**Comment by colemanw** [comment]
I think we need a little more clarity on the scope and purpose for `addField`.
I don't think the goal should be for every form to use this function for every element.
These terms are kind of vague but for the sake of this discussion let's say:

- a **field** is a field in the database, declared in the xml and retrievable from api.entity.getfields.
- an **element** is some type of form input. It could represent a database field, or it could just be some random form element for the user to interact with.

The reason I'm making that distinction is because I think the purpose of the new `addField` is to bind fields in the schema to a form. I think we should actively discourage any other use, I'd go so far as to say we ought to throw an exception if `addField` fails to lookup the field in the schema. We already have a perfectly good `addElement` method for putting random elements in a form and people can keep on using it.

**Comment by colemanw** [comment]
Where I'm going with this is that I think `addField` could be an intermediate step toward something even more powerful. Wouldn't it be awesome to have a method to build a complete crud form in a single line of code? A function that would:

- Lookup the schema for a given entity type.
- Iterate through all the fields and call `addField` for each one that has an `html` type declared.
- If this is an update op, lookup the entity with the supplied id and set default values appropriately.

Not that `addField` would ever need to be made private, I think it will always be useful in its own right.

**Comment by mallezie** [comment]
I see, perhaps i was too eager ;-). The addField, and addElement distinction makes sense. Thanks for the clarification. The automatic form generation was something i also thought about. 
I'll update this PR.

**Comment by mallezie** [comment]
I removed the inline_lock addField method. That's indeed a case for addElement. I left the basic declaration in Inline.php since we'll need them anyway. 
The addField in edit _Lock seems legit to me, since that's the modified date field.

**Comment by colemanw** [comment]
Related: https://github.com/civicrm/civicrm-core/pull/5505

**Pull request merged**
