### PR TITLE
Afform - Customizable APIv4-based Autocomplete widget for EntityRef fields

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
This switches all Afform EntityRef fields to use the new APIv4-based Autocomplete widget. That includes "Existing Contact" fields, contact reference custom fields, and fields referring to other entities like `Participant.event_id` or `Contact.employer_id`.

It allows those fields to be configured using SearchKit - any SavedSearch can be selected to filter the results. And a new type of SearchKit display has been created to customize the output.

image

This is a continuation of #24165 which created the new APIv4 widget and implemented it in a limited way.

Before
----------------------------------------
EntityRef fields use the APIv3 `getlist` action which has the following limitations:
- Always checks user permissions, not usable by anonymous or less-permissioned
- Filters cannot be set by form administrator
- Does not respect filters set on contact ref fields
- Output format and input-field is hard-coded (cannot configure how the results appear or which field is being searched on)
- Only works with v3 entities

After
----------------------------------------
- [x] Switch Afform to use new v4 Autocomplete widget for all EntityRef and ContactRef fields.
- [x] Allow filters to be set in schema (e.g. `employer_id` should filter on `contact_type=Individual`)
- [x] Afform - support filters in ContactRef custom fields and other EntityRef fields.
- [x] APIv4 - Convert Autocomplete action to use SearchDisplay::run
- [x] APIv4 - Add a hookable `getDefault` for autocomplete-type displays to allow entity-specific customizations
- [x] SearchKit - GUI for configuring Autocomplete-type display
- [x] Afform - allow search display to be selected for each Autocomplete widget
- [x] Afform - enforce filters on the server-side

### CODE REVIEW

**Comment by aydun** [comment]
Testing this on the test site linked above.  This seems to have caused a regression when adding SK tables.  When you attempt to add a table display, it produces an browser console message of 'parent.getDefaultSort is not a function'  The table is added but Preview fails.

Otherwise, everything I tested is great.

**Comment by colemanw** [comment]
Thanks for testing @aydun - I fixed that bug you spotted and rebased.

**Review by kurund — COMMENTED** [review]
@colemanw 

Overall looks good, I need bit more time to finish my tests. 

Here is minor issue I noticed so far.
- Configure advanced filter for custom field and  use saved search for afform field. This results in empty autocomplete. I feel if saved search is used then filters can be ignored. This is an edge case so  happy if you don't want to tackle in this PR.

**Comment by colemanw** [comment]
Thanks @kurund. IMO the correct behavior is to enforce both the field filters and the SavedSearch selected on the afform. Since the filter is set at the field level I don't think it should be ignored. Just my opinion.

**Comment by kurund** [comment]
@colemanw 

Ok, fair point.

All looks good to me. Ready to merge.

**Pull request merged**
