### PR TITLE
dev/core#1218 Fix Word Replacements on manage case Roles

### PR DESCRIPTION
**Pull request by vakeesan26**
Fix for https://lab.civicrm.org/dev/core/issues/1218

### CODE REVIEW

**Comment by mattwire** [comment]
I think this is correct - as that's a string that's used for display it should be translated. @mlutfy Can you confirm?

**Comment by mlutfy** [comment]
jenkins, add to whitelist

**Comment by mlutfy** [comment]
Yep, seems good! (added merge-on-pass)

**Comment by mlutfy** [comment]
The test fail is unrelated, taking the liberty to merge.

**Pull request merged**
