### PR TITLE
Revert just merged 27412

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
Typo `descrition`, but more importantly the same problem as https://github.com/civicrm/civicrm-core/pull/27010

### CODE REVIEW

**Comment by demeritcowboy** [comment]
wait there's more

**Comment by seamuslee001** [comment]
urg

**Comment by eileenmcnaughton** [comment]
Hmm so we need array_key_exists && $fieldSpec.template?

**Comment by demeritcowboy** [comment]
I'd have to get my head back into it about `template` but for some of the others there's some comments in the PR description comments at https://github.com/civicrm/civicrm-core/pull/27010, and then some discussion later.

**Pull request merged**
