### PR TITLE
dev/core#858 Fix weekly contribution summary

### PR DESCRIPTION
**Pull request by JKingsnorth**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/issues/858

Before
----------------------------------------
The weekly summary was inaccurate because the MySQL YEARWEEK and WEEKOFYEAR functions are not lined up. So report was creating incorrect groupings on WEEKOFYEAR.

After
----------------------------------------
The grouping field has been updated to ensure that contributions are grouped correctly by the week.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@JKingsnorth can we get a test?

**Comment by JKingsnorth** [comment]
Yeh, it needs one. I'll have a crack at it.

**Comment by JKingsnorth** [comment]
@eileenmcnaughton I've hit several issues writing the test for this, and it goes quite 'deep'. This is because the summary report uses a non-standard field type of 'group_by_freq' in the form, to set what 'frequency' to group by.

This 'group_by_freq' isn't understood at the form level, so it isn't implemented in the 'get' layer like \CRM_Report_Utils_Get::processGroupBy is; which means the CiviReportTestCase also doesn't override that setting when it's defined in the report spec...

Happy to document this on the original issue and close the PR as realistically I'm not going to have time to do this much digging on it to create the test.

**Comment by mattwire** [comment]
@JKingsnorth Closing per comments - dev/core#858 is still open to track this

**Pull request closed without merging**
