### PR TITLE
Fix 'cannot determine default entity' error on New Batch page

### PR DESCRIPTION
**Pull request by MegaphoneJon**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/4036

"New Batch" no longer loads.  When you try, you get an error.

Before
----------------------------------------
image

After
----------------------------------------
No error.

Technical Details
----------------------------------------
The error describes things pretty well.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Thanks - can you put against 5.57?

**Comment by demeritcowboy** [comment]
Ah you just did.

**Comment by MegaphoneJon** [comment]
@demeritcowboy This pulls in a bunch of additional commits though.  I feel like there's a way for this to not happen, but not sure what it is?  I just tried creating a new branch off of 5.57 and cherry-picked my commit, but when I force-push to this branch it says "Everything up-to-date".

**Comment by demeritcowboy** [comment]
Since the actual change is so small, I would do `git fetch origin/5.57; git reset --hard origin/5.57` and then manually reapply the change, commit, and force-push.

**Comment by MegaphoneJon** [comment]
Thanks @demeritcowboy, done.

**Pull request merged**
