### PR TITLE
Afform - make summary tab names less weird

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
A little tweak to make the process of replacing contact summary tabs with SearchKit a bit more seamless.

Before
----------------------------------------
A contact summary tab created with SearchKit/Afform could have any label or icon, but the machine name was set to the name of the form, yeilding yucky names like 'afsearchGrants'.

After
----------------------------------------
Form prefix stripped off for friendlier names and to allow 1-1 replacements, e.g. this PR changes the name of the Grants tab back to "grant" which is exactly what it was before #22467

Comments
----------------------------------------
Going forward, this allows transitions like [this one](https://lab.civicrm.org/extensions/cividiscount/-/merge_requests/284) to be backward-compatible with ContactLayout Editor or custom modifications that were made through hooks.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@colemanw does there need to be an upgrade script for when sites have already configured their contact layout?

**Comment by colemanw** [comment]
@eileenmcnaughton yep good idea.

**Comment by colemanw** [comment]
@eileenmcnaughton I ran this upgrade script a few times and I'm happy with it.

**Comment by eileenmcnaughton** [comment]
@colemanw cool I was gonna check if you had r-run it

**Pull request merged**
