### PR TITLE
Afform - Server side conditional evaluation

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
See https://lab.civicrm.org/dev/core/-/issues/5182.  If you have a required field on an FB form that's conditionally hidden, it passes client-side "required field" validation but fails it server-side.

Before
----------------------------------------
Silent failure, not all data saved.

After
----------------------------------------
Hidden required fields are un-required server side as well as client-side.

Comments
----------------------------------------
This extends @MegaphoneJon's work from https://github.com/civicrm/civicrm-core/pull/30094 with support for all operators, and server-side unit tests. TODO: client-side unit tests.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by allinappliadmin** [comment]
I can test. How do I patch with several files to patch? (sorry for the stupid question)

**Comment by MegaphoneJon** [comment]
@allinappliadmin If you're comfortable with the command-line, the `patch` command should work here (I don't know if it's on Windows, but should be on Linux/Mac/etc.).

* Add `.diff` to the end of this URL - "https://github.com/civicrm/civicrm-core/pull/30524.diff".
* Save the resulting file in your Civi root (I'll assume you've named it `30524.diff`).
* Use the command line to navigate to your Civi root.
* Run `patch -p1 < 30524.diff`.

If everything went successfully, you'll see a message that says so.  However, if you try applying it to a version of Civi that doesn't match closely enough, you'll get error messages.  Handling that is beyond the scope of this quick note though :)

**Comment by allinappliadmin** [comment]
I know the way but it's asking me the file to patch
image

**Comment by allinappliadmin** [comment]
image

**Comment by MegaphoneJon** [comment]
@allinappliadmin Ah - On Wordpress, the Civi root is actually in `wp-content/plugins/civicrm/civicrm`, you're in `wp-content/plugins/civicrm`.

**Comment by allinappliadmin** [comment]
I don't understand why the path changes :-/
I'm supposed to be in /civicrm/civicrm

File to patch: ext/afform/core/Civi/Afform/FormDataModel.php    
ext/afform/core/Civi/Afform/FormDataModel.php: No such file or directory

**Comment by allinappliadmin** [comment]
should I include wp-content/plugins/civicrm/civicrm in file path ?

**Comment by colemanw** [comment]
You need to patch from the civicrm directory. Try
```
mv 30524.diff civicrm
cd civicrm
patch -p1 < 30524.diff
```

**Comment by allinappliadmin** [comment]
I'm sorry I'll watch out more the exact path the next time. I was able to patch and test.

I confirm that it works, the contact is created and fields are filled even if some required fields were hidden by the conditional logic.

Great job!

**Pull request merged**
