### PR TITLE
Move messageTemplate call out of create smarty

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
partial from https://github.com/civicrm/civicrm-core/pull/28774 as I work through remaining issues

### CODE REVIEW

**Comment by demeritcowboy** [comment]
It might be this one but I'm getting unit tests reporting fails during core civi install on messagetemplates now. Not sure why it wouldn't come here in jenkins. It's obviously from xml/templates/civicrm_msg_template.tpl but it seems like more than a php notice. That variable should be defined.

```
Undefined array key "optionGroupNames"

/tmp/templates_cKLMQgM.d/%%CA^CAB^CABB3767%%civicrm_msg_template.tpl.php:19
/home/runner/drupal/vendor/civicrm/civicrm-packages/Smarty/Smarty.class.php:2027
/tmp/templates_cKLMQgM.d/%%16^166^166AE87A%%civicrm_data.tpl.php:136
/home/runner/drupal/vendor/civicrm/civicrm-packages/Smarty/Smarty.class.php:1364
/home/runner/drupal/vendor/civicrm/civicrm-core/setup/src/Setup/Template.php:72
/home/runner/drupal/vendor/civicrm/civicrm-core/setup/src/Setup/SchemaGenerator.php:87
/home/runner/drupal/vendor/civicrm/civicrm-core/setup/plugins/installDatabase/InstallSchema.civi-setup.php:85
/home/runner/drupal/vendor/symfony/event-dispatcher/EventDispatcher.php:220
/home/runner/drupal/vendor/symfony/event-dispatcher/EventDispatcher.php:56
/home/runner/drupal/vendor/civicrm/civicrm-core/Civi/Core/CiviEventDispatcher.php:263
/home/runner/drupal/vendor/civicrm/civicrm-core/setup/src/Setup.php:230
/home/runner/drupal/web/modules/contrib/civicrm/civicrm.install:31
```

**Comment by eileenmcnaughton** [comment]
@demeritcowboy that must be why I wound up re-adding it here https://github.com/civicrm/civicrm-core/pull/28774/files#diff-2131b62e0019c60c9029efe45018ac61ae5f687d791013825679af5f9bdf28edR36

**Comment by demeritcowboy** [comment]
Yes I see you're working hard on that one.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy yes - my soul is being shredded into little pieces - might be time to join jenkins & stare longingly into the abyss

**Pull request merged**
