### PR TITLE
CRM-20786 Move deprecated utils functions to the import classes 

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
* [CRM-20786: Move deprecated utils functions to the import classes](https://issues.civicrm.org/jira/browse/CRM-20786)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@monishdeb as discussed - this is really just moving (for now duplicating) code

**Comment by eileenmcnaughton** [comment]
@monishdeb this is the most important of these

**Comment by monishdeb** [comment]
@eileenmcnaughton I am in a dilemma of what should be the correct approach when we find scope to further optimise after moving such old/duplicate code to a better place. Like in this PR #10370 I did some optimisation in ```CRM_Price_BAO_LineItem::changeFeeSelections(...)``` after moving it from  ```CRM_Event_BAO_Participant::changeFeeSelections(..)``` !!

**Comment by eileenmcnaughton** [comment]
I don't think there is a clear rule about it , since these things could always be endlessly optimised. In this case what I find is that a lot of the handling in the moved function is duplicated by the calling function - so I think it's worth looking at that further, but of course, then there is the question of adding tests. I do have some further optimisations I want to make on top of this (although not as far as it might go), but this PR should stand alone to prevent confusion about what it does.

**Comment by monishdeb** [comment]
Ok, well then as per PR changes I did a quick check on UI and its safe to merge. So are you going to include the tests in this PR (if no, will merge it) or on a followup PR?

**Comment by eileenmcnaughton** [comment]
no, not in this one. The tests address the location changes - I'll merge this per your comment

**Pull request merged**
