### PR TITLE
CRM-16230 - Permissions: handle extensions with and without descriptions

### PR DESCRIPTION
**Pull request by agh1**
---
- CRM-16230: Extensions providing permissions will choke
  https://issues.civicrm.org/jira/browse/CRM-16230

Replaces #5560

### CODE REVIEW

**Comment by totten** [comment]
@agh1, would this be related to http://forum.civicrm.org/index.php/topic,36255.0.html ? If I read the patch correctly, it seem so to be more adaptive (ie allowing arrays or strings) -- so it would be backward+forward compatible?

Should we also document this in http://wiki.civicrm.org/confluence/display/CRMDOC/API+changes ?

**Comment by davecivicrm** [comment]
PR test failure is unrelated.

**Comment by agh1** [comment]
@totten yeah, that's the problem.  In CRM-16201, permissions are retrieved either with or without descriptions. The problem is that the extension/module permissions are handled after the base permissions. Either there'll be a problem with the extension providing descriptions or one with it not providing them.

This PR does three things:
* it allows for extensions to provide permission descriptions,
* it maintains backwards compatibility for extensions that don't, and
* it provides a complete array of extension permissions in the appropriate format for the context even if there's a mix of those with and without descriptions

I don't think the API changes page necessarily needs mention of this, but the hook documentation needs it.

**Comment by davecivicrm** [comment]
Tested this patch w/ install of CiviVolunteer which supplies a permission w/o description.

**Pull request merged**
