### PR TITLE
Afform - repeat block metadata update to fix errors when saving blocks

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Followup to #22963 - update any Afform blocks saved in error before the "Save Block" dialog was fixed.

### CODE REVIEW

**Comment by colemanw** [comment]
Ping @demeritcowboy

**Comment by colemanw** [comment]
@demeritcowboy I also just pushed a fix into this PR for the undefined index you noticed in https://github.com/civicrm/civicrm-core/pull/22963#issuecomment-1073032990

**Comment by demeritcowboy** [comment]
I'm still getting the error after running extension upgrades. Does the below help diagnose? entity_type is still null

The json file:

```json
{
    "type": "block",
    "title": "titlex"
}
```

api get:

```
    (1) [
      {
        "name": "afblockTitlex",
        "requires": [],
        "title": "titlex",
        "description": "",
        "is_dashlet": false,
        "is_public": false,
        "is_token": false,
        "permission": "access CiviCRM",
        "type": "block",
        "layout": [
          {
            "#tag": "p",
            "class": "af-text",
            "#children": [
              {
                "#text": "fffffff"
              }
            ]
          },
          {
            "#text": "\n"
          }
        ],
        "entity_type": null,
        "join_entity": null,
        "contact_summary": null,
        "server_route": null,
        "redirect": null,
        "create_submission": null
      }
    ]
```

**Comment by colemanw** [comment]
@demeritcowboy I don't think that particular block should need to have any `entity_type` because it doesn't contain anything to make it entity-specific (the layout is just markup, no `af-field`s). What error do you get when you try to use it?

**Comment by demeritcowboy** [comment]
It's the same errors and the edit button doesn't edit the same as before. If it helps the below is the form it's in.

1. Create submission form.
1. Add a container element.
1. Add a text field inside it.
1. Save the container as a block.


```json
{
    "type": "form",
    "requires": [],
    "title": "bbbb",
    "description": "",
    "is_dashlet": false,
    "is_public": false,
    "is_token": false,
    "server_route": "",
    "permission": "access CiviCRM",
    "create_submission": true,
    "entity_type": null,
    "join_entity": null,
    "contact_summary": null,
    "redirect": null
}
```

```html
<af-form ctrl="afform">
  <af-entity data="{contact_type: 'Individual', source: 'bbbb'}" type="Contact" name="Individual1" label="Individual 1" actions="{create: true, update: true}" security="RBAC" />
  <fieldset af-fieldset="Individual1">
    <afblock-titlex></afblock-titlex>
    <legend class="af-text">Individual 1</legend>
    <afblock-name-individual></afblock-name-individual>
  </fieldset>
  <button class="af-button btn btn-primary" crm-icon="fa-check" ng-click="afform.submit()">Submit</button>
</af-form>
```

**Comment by eileenmcnaughton** [comment]
@demeritcowboy @colemanw what is the status here - we should resolve this before the rc is cut

**Comment by demeritcowboy** [comment]
I suppose the worst is it just might not actually fix existing blocks. And it does fix the "undefined index" notice.

**Pull request merged**
