### PR TITLE
dev/core#927 add first test on cancel 

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Builds on https://github.com/civicrm/civicrm-core/pull/18784 to add a unit test

Before
----------------------------------------
No testing on cancel

After
----------------------------------------
Test added -

Technical Details
----------------------------------------
Original test fails were a membership fix that I pulled out of scope - should be straight forward now

Comments
----------------------------------------

I will rebase if #18784 is merged first

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test errors relate - I will dig - my suspicion is they don't invalidate this change & the tests should be altered but will check


api_v3_ContributionTest.testCompleteTransactionMembershipPriceSet
api_v3_ContributionTest.testPendingToCompleteContribution
api_v3_ContributionTest.testCompleteTransactionMembershipPriceSetTwoTerms
api_v3_MembershipStatusTest.testDeceasedMembershipInline
api_v3_MembershipStatusTest.testDeleteWithMembershipError

**Comment by eileenmcnaughton** [comment]
@seamuslee001 this adds a test for the new extension - so once this is merged I need to ensure it's all wired into tests (& add on install & upgrade) before I move any functionality to it (I've just rebased so tests running again but since this isn't wired in yet I don't think it can fail).

I never remember all the steps

**Comment by seamuslee001** [comment]
@eileenmcnaughton so I think with my recent tweaking of the civi-test-run in buildkit there shouldn't be any need to make changes there (unless its like afform where the test folder is an extra directory deep or anything like that)

**Comment by eileenmcnaughton** [comment]
@seamuslee001 OK - well once this is merged I'll do the install & upgrade bit & we can see

**Comment by seamuslee001** [comment]
Looks fine to me as per https://test.civicrm.org/job/CiviCRM-Core-PR/37572/testReport/(root)/IPNCancelTest/ the test has passed

**Comment by eileenmcnaughton** [comment]
Oh cool

**Comment by seamuslee001** [comment]
But it still doesn't mean that it is enabled / installed on upgrade or anything tho

**Comment by eileenmcnaughton** [comment]
@seamuslee001 https://github.com/civicrm/civicrm-core/pull/18812 ^^

**Pull request merged**
