### PR TITLE
Allow data-params to be specified as an item property and passed to CRM.api3 call

### PR DESCRIPTION
**Pull request by aydun**
See description in Jira - CRM-21741

Overview
----------------------------------------
_A brief description of the pull request. Try to keep it non-technical._

Before
----------------------------------------
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

After
----------------------------------------
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

Technical Details
----------------------------------------
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

---

 * [CRM-21741: For in-place editing, allow data-params to be passed to CRM.api3](https://issues.civicrm.org/jira/browse/CRM-21741)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw one for you I think - although the sprinters might perhaps be assigning review resources

**Comment by colemanw** [comment]
Makes sense to me. This js does not have any unit tests so the PR test results are irrelevant. But it's a safe change - just introducing a new option and not changing any additional functionality.

**Comment by colemanw** [comment]
Can you submit a PR for the docs update as well please?

**Comment by aydun** [comment]
Doc PR: https://github.com/civicrm/civicrm-dev-docs/pull/475

**Pull request merged**
