### PR TITLE
dev/financial#117 - Add link metadata for payment edit link

### PR DESCRIPTION
**Pull request by acrollet**
Overview
----------------------------------------
Adds metadata to edit payment link so that hook_civicrm_links can be used.

Before
----------------------------------------
Edit payment link on View Contribution page cannot be modified by hook_civicrm_links

After
----------------------------------------
Edit payment link on View Contribution page can be modified by hook_civicrm_links

Comments
----------------------------------------
similar PR: https://github.com/civicrm/civicrm-core/pull/1851

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
@acrollet Thank you for your contribution, and welcome to the CiviCRM community!  This PR is appreciated, and it looks pretty solid.  In fact, I think it's identical to another currently open PR, #16401.  If you're able to confirm that #16401 works for you (or @alifrumin if you could check this one) I think that would serve as code review and we could get one of these merged ASAP.

**Comment by acrollet** [comment]
@MegaphoneJon thanks for the review and sorry to have missed the other PR! (I did search the gitlab issues but didn't find anything...) Reviewing the two together, I would say that:

1. The previous PR would definitely work for me
2. It should probably use the ts() function for the first added parameter?
3. I don't know Civi well enough to know if 'payment.manage.action' or 'payment.edit.action' is more appropriate for the third added parameter.

**Comment by MegaphoneJon** [comment]
Thanks @acrollet - and agreed that it's a bit surprising there's no Gitlab issue.  Nonetheless, I think when Alice gets a moment to see those comments, she'll be able to update that pretty quickly.  I'm going to leave a comment on that ticket linking to your comment aboce.

**Comment by alifrumin** [comment]
I am happy to take a look at this tomorrow 👍

**Comment by eileenmcnaughton** [comment]
add to whitelist

**Comment by eileenmcnaughton** [comment]
@alifrumin @MegaphoneJon the process you are working through looks good here - and the PR looks safe / sensible. Ping me to merge one of them when you are agreed.

**Comment by yashodha** [comment]
test this please

**Comment by alifrumin** [comment]
I closed #16401 in favor of this pr because this pr includes the ts() for the more link, has a related gitlab issue (https://lab.civicrm.org/dev/financial/issues/117) and @acrollet  is a new contributor who I would like to see get full credit!

@eileenmcnaughton I believe this is ready to be merged. See full review below:

* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __Pass__ - The change is documented clearly on the pr and in https://lab.civicrm.org/dev/financial/issues/117
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __Pass__ - The change would be intuitive or unnoticeable for a majority of users who work with this feature
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __Pass__ - How to use the hook is documented in https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_links/
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __Pass__ - I tested on a local build and was able to access the Payment Details Links with hook_civicrm_links as expected 
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __Pass__ - The change preserves compatibility with existing callers/code/downstream.
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __Pass__ - The functionality, purpose, and style of the code seems clear+sensible.
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __Pass__
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __Pass__

Great work @acrollet! and thanks @MegaphoneJon for linking us.

**Comment by eileenmcnaughton** [comment]
Nice merging - well done on your first PR merged to core @acrollet  - I'd love to say it's common to get them merged within a day but....

**Pull request merged**
