### PR TITLE
WIP Activity pdf 71 rebased

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Rebased https://github.com/civicrm/civicrm-core/pull/12012 following merge of #14662

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by mattwire** [comment]
See https://lab.civicrm.org/mattwire/emailapi/tree/newtokenprocessor for a useful way to try it out

Also, I renamed Source / Target per @demeritcowboy comments

**Comment by eileenmcnaughton** [comment]
@mattwire as you picked up this part got stalled over the difficulty of adding a many type token & was considered to be a change that should be documented/discussed/ considered/ resolved in it's own right. I can't recall the details but I guess the place to flesh out how this works is the PR template & then we can try to figure it out.

@aydun are there any remaining parts that should be picked off & merged separately or is this all about the many token issue now?

**Comment by seamuslee001** [comment]
test fails relate here @mattwire

**Comment by aydun** [comment]
@eileenmcnaughton @mattwire  I think all that's left here now are the 'special' tokens.  But I also have several other fixes/enhancements for this locally from the October sprint.  I'll combine those with Matt's changes.

**Comment by mattwire** [comment]
I'm going to close this as @aydun is planning to pick up the remaining bits (and I'm not likely to) but we don't want them getting lost. Tracking via https://lab.civicrm.org/dev/core/issues/1614 @eileenmcnaughton

**Pull request closed without merging**
