### PR TITLE
Move BAO and template files into event cart

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This is a partial of https://github.com/civicrm/civicrm-core/pull/17339 - it moves the BAO and template files to the extension and does a limited install - but leaves the more complex work to be done in later PRs. 

Note that the install in this PR **only** works because no tables are created as part of the extension. There are technical issues still to be solved before we can have a core-extension that does anything on install. As a hidden extension this must remain enabled and we use the hidden tag to denote that this is part of core, not an add-on extension. There may come a time when it can be disabled but today is not that day.

Before
----------------------------------------
BAO files in original place

After
----------------------------------------
BAO files moved

Technical Details
----------------------------------------
#/17339  also incorporates work to move to a more extension-like interaction with core (using hooks / api end points ) and towards solving the install issue - this PR just aims to do the technically simple but vey stale-prone part.

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Added OK without test as this is the file moving part - adding tests can't really happen until the code is in the right place - it's a bit chicken & egg but this removes blockers to adding tests

**Comment by eileenmcnaughton** [comment]
@seamuslee001 you were going to check if all the enable steps were OK here

**Comment by seamuslee001** [comment]
yes this was on my things to do

**Comment by mattwire** [comment]
test this please

**Comment by mattwire** [comment]
@seamuslee001 @eileenmcnaughton This is failing on:
```
CRM_Member_Form_MembershipRenewalTest::testSubmitRecurCompleteInstant
Failed asserting that '2' matches expected 1.
```
That must be unrelated?

**Comment by mattwire** [comment]
We also need the changes from bin/regen.sh and .gitignore from https://github.com/civicrm/civicrm-core/pull/17339 here

**Comment by eileenmcnaughton** [comment]
@mattwire I double checked & the .gitignore bit is already done. I added the regen.sh here https://github.com/civicrm/civicrm-core/pull/17839 since it's a bit staley, applies to other extensions, and is crying out for a better fix.

Test fail patch in https://github.com/civicrm/civicrm-core/pull/17830

**Comment by seamuslee001** [comment]
I tested this and found only one issue which was the templates folder path wasn't matching the standard folder path (was missing the Cart subdirectory) after fixing that I can confirm the event cart system works as expected also tested and confirmed the upgrade works as expected as well.

**Comment by seamuslee001** [comment]
Test fail unrelated

**Pull request merged**
