### PR TITLE
APIv4 Explorer - Add REST syntax

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Displays REST syntax in the APIv4 Explorer.

See https://lab.civicrm.org/documentation/docs/dev/-/merge_requests/982#note_69327

image

### CODE REVIEW

**Comment by colemanw** [comment]
@totten one question I have about this. Currently for authentication it outputs `'X-Civi-Auth: Bearer abc123'` - which is a placeholder. Would it make sense to access some AuthX API to output a real live credential string? Or would that be bad security-wise?

**Comment by totten** [comment]
@colemanw It depends...

* For `api_key`s... if it's a local dev site with a superuser, then it's fine+good to automatically insert a real `api_key`. On a production site, I wouldn't. Granted, you could make it conform to the permission-model (*check `edit api keys`*), but... in security UIs... it's common practice to keep keys slightly hidden (*perhaps prompt for a password before revealing*) because... users leave their terminals unattended; users work in public spaces; users do screenshares; etc.

* For `jwt`s ([example code](https://github.com/civicrm/civicrm-core/tree/master/ext/authx#json-web-token))... you can set a time-limit for the token, which reduces the exposure. If you want to automatically present a real value, this would be a more secure way. (*This currently requires server-side code, but we could create a permission/API around temporary tokens... maybe `generate temporary credentials` or `cv api4 Contact.createTempToken duration=900`*)

IMHO, it probably makes sense to start with a UI that works in passive mode (without special access to mange keys) -- then mix-in progressive-enhancements? I'm guessing something like [one of these](https://jsfiddle.net/6p2ch7xn/1/):

Screenshot from 2022-02-07 13-22-10

Related ramblings:

* There is an extension https://civicrm.org/extensions/api-key which provides a web UI for `civicrm_contact.api_key`. If available, the Explorer could hyperlink to it?
* In production, integrations *should* have service-principals (distinct from their regular/personal web-user). The service-principal would have different credentials from the person using the API Explorer.
* You could present an option to authenticate via `Cookie:` and copy the current session-cookie. I would view that as (a) more secure than displaying the stored `api_key` and (b) less secure than the time-limited JWT.

**Comment by totten** [comment]
Back to the main thrust of the PR...

This looks pretty good. I did some `r-run` and pushed up a few small edits:

* Guzzle needs the base URL to end with `/`.
* Change placeholder from `abc123` to `MY_API_KEY`

One thing to verbalize about the Guzzle example... I had suggested this line:

```php
#!require guzzlehttp/guzzle: ^6.3
```

This is sort-of two things:

1. It's an explanatory comment about the assumptions of the code.
2. It's a functional directive *if one uses [pogo](https://github.com/totten/pogo)*. (Ex: I pasted the code into a standalone file `/tmp/z.php` and ran it with `pogo /tmp/z.php`.)

But... `pogo` is admittedly obscure. It might be just as well to remove or revise the comment for a more general audience, eg

```php
## This example requires Guzzle HTTP:
#$ composer require guzzlehttp/guzzle:^6.3
```

Anyway, it's a good improvement,  I'm flagging `merge ready`. If you want to tweak the comment, go for it. Or if you want to merge as is, that's good by me.

**Comment by colemanw** [comment]
OK thanks @totten. I've rebased and removed the extra comment about guzzle because it should be pretty self-explanatory.

**Pull request merged**
