### PR TITLE
SearchKit - Add data segmentation functionality

### PR DESCRIPTION
**Pull request by colemanw**
Overview
-------------
Creates virtual fields based on flexible segmentation criteria.

Creating a Segment:
image

Example use:
image

### CODE REVIEW

**Comment by colemanw** [comment]
Based on extensive discussion our committee has reached a compromise and renamed the entity `VirtualComputedDataClassificationTranspositionPivotSegmentationField`

**Comment by samuelsov** [comment]
Probably not ready for validation yet but just in case, I found that search segment with option list value doesn't work.
Contact subtypes works but gender, activity types or contribution status doesn't.

Example that always gives other:

ksnip_20220420-122457

**Comment by colemanw** [comment]
Thanks for testing this @samuelsov. Yes this PR is ready for review.
That's strange it doesn't work for you because there is a unit test included with this PR for that same scenario and it passes.
I'll check...

**Comment by eileenmcnaughton** [comment]
@colemanw I had a similar experience to @samuelsov - recreated here http://core-23059-10nxw.test-3.civicrm.org:8001/civicrm/admin/search#/edit/2

**Comment by eileenmcnaughton** [comment]
@colemanw Based on my testing this is working - with the exception of the above issue - which you are working on a patch for.

I think on balance it is better to merge this and then keep testing / improving at this stage since I think we will have incremental improvements / requests from here

The 2 things I noticed were

1) overlapping criteria - it's tricky with 'BETWEEN' to be clear about how the limit values will be treated - so it is easy to configure like this without being clear what the impact is - in fact $10 fits into 2 criteria but in search kit it will show up in the FIRST matching criteria - I suspect some UI text to clarify might be the best approach

image

2) I can't add the segments as a filter when I get as far as formbuilder (which would also be necessary to manually build up a link-through I think)

**Comment by eileenmcnaughton** [comment]
I would also note an advantage of merging is that it can be put though the hoops better on your Europe sojourn

**Comment by colemanw** [comment]
@samuelsov @eileenmcnaughton this fixes the bug you noticed. It was a bug in the Angular UI which is why the PHPUnit tests didn't catch it. https://github.com/civicrm/civicrm-core/pull/23265

**Pull request merged**
