### PR TITLE
CRM-21337 ISO compliance for Romanian and Bulgarian counties

### PR DESCRIPTION
**Pull request by JKingsnorth**
Overview
----------------------------------------
We use ISO 3166-2 for county/state names. We noticed there were some spellings that were not consistent with this standard in CiviCRM for Bulgaria and Romania.

Before
----------------------------------------
County spellings were not standard.

After
----------------------------------------
County spellings meet the standard.

Technical Details
----------------------------------------
- Update to tpls for new installs
- Update script for existing installs

---

 * [CRM-21337: ISO compliance for Romanian and Bulgarian counties](https://issues.civicrm.org/jira/browse/CRM-21337)

### CODE REVIEW

**Comment by JKingsnorth** [comment]
I've put this in against 4.7.28, but I can make it 'sooner' if you like.

**Comment by mlutfy** [comment]
I don't see any urgency to merge against 4.7.27-rc. It's been like that for a very long time.

Thanks for the PR! (merge on pass)

**Comment by JKingsnorth** [comment]
Thanks for the review

**Comment by JKingsnorth** [comment]
Jenkins can you retest this please.

**Pull request merged**
