### PR TITLE
dev/core#866, dev/core#1318 Fix failure to import checkboxes for activities

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This seeks to address a long-standing issue whereby checkboxes cannot be imported onto
activities if the name and value match.
https://lab.civicrm.org/dev/core/-/issues/1318
https://lab.civicrm.org/dev/core/-/issues/866
https://issues.civicrm.org/jira/browse/CRM-17493

Before
----------------------------------------
Screenshot from 2020-12-04 17-25-00

After
----------------------------------------
above works and has unit test cover

Technical Details
----------------------------------------
Since this code was written the create was switched from a BAO create to the
activity api create. Simply removing the handling to prepare for the BAO create
allows the api to do it correctly

Comments
----------------------------------------
Since this is just removing code & adding a test the main review task is r-run. However, it might require a reviewer to think about testing different custom field types to be sure

My test csv looked like this

Contact id | cust field | Activity Type ID | Date | subject
-- | -- | -- | -- | --
24 | maybe | Phone call | 2020-01-02 | Interesting

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 this was also part of my import clean up - although it is on activity

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit (cc @petednz) I wonder if you would be able to review this - it might take a little bit of thought to do a suitable r-run

**Comment by mattwire** [comment]
@eileenmcnaughton Needs rebase

**Comment by eileenmcnaughton** [comment]
rebased now - just need to check if it still passes

**Comment by eileenmcnaughton** [comment]
Passing now...

**Comment by colemanw** [comment]
retest this please

**Comment by eileenmcnaughton** [comment]
@colemanw green

**Comment by eileenmcnaughton** [comment]
Hmm - my other tests build on this so I can't submit them until this is merged

**Comment by seamuslee001** [comment]
@eileenmcnaughton I tried testing this on my local I created a custom field set for all activates and created a checkbox single field and a radio field and a text field

When I imported the sheet It didn't give me errors and viewing the activity record showed the correct information as per this screenshot

activity_view

However on clicking edit I found that the checkbox for the Hello option wasn't being checked as per the below screenshot

activity_edit

This is my custom field configuration

Custom field Config

**Comment by demeritcowboy** [comment]
That's odd, especially if it shows on view. When I try it the checkbox looks ok for me on edit. Is it a value/label thing like you originally had Hello and then changed it to "2"? Then it might show on view if the value is stored in custom_value_X as Hello, but it wouldn't match the checkbox value of "2".

**Comment by eileenmcnaughton** [comment]
@seamuslee001 is that regressive? If not it will be easier for me to address it if this is merged first

**Comment by demeritcowboy** [comment]
I've tried a couple things and haven't seen anything unusual except [some preexisting date issues](https://lab.civicrm.org/dev/core/-/issues/2325). I'm not seeing what Seamus is seeing with the checkbox.

**Comment by seamuslee001** [comment]
yeh I'm not sure what happened with my import but I'm comfortable with this PR if @demeritcowboy is

**Comment by demeritcowboy** [comment]
Ok. I've added some wording to https://docs.google.com/document/d/15WUq3hNhNyfM0XB7sJxpwkLFW8ncLgdPfMJ8BP1lUZA/edit# as a candidate for inclusion in the dev digest.

**Comment by eileenmcnaughton** [comment]
Thanks @demeritcowboy @seamuslee001

**Comment by eileenmcnaughton** [comment]
@seamuslee001 were you going to merge this?

**Comment by seamuslee001** [comment]
Merging as per review by @demeritcowboy

**Comment by eileenmcnaughton** [comment]
thanks

**Pull request merged**
