### PR TITLE
On reports make current employer available as a field for display

### PR DESCRIPTION
**Pull request by yashodha**
Overview
----------------------------------------
Expose current employer in fields and display in results as well. I think this was supported earlier.

Before
----------------------------------------
rep_before

After
----------------------------------------
rep_after
result_after

### CODE REVIEW

**Comment by totten** [comment]
Aside/short term tip for reviewers -- The link for the "test sites" above points at an old server. Fixing the bot is a TODO; in the interim, you should be able to edit the link a little to get to the right page:

* Example, bad: [http://site-list.test-ubu1204-5.civicrm.org/?filter=core-12904-*](http://site-list.test-ubu1204-5.civicrm.org/?filter=core-12904-*)
* Example, good: [http://site-list.test-1.civicrm.org/?filter=core-12904-*](http://site-list.test-1.civicrm.org/?filter=core-12904-*)

Note how the `test-ubu1204-5` changes to `test-1`.

**Comment by Clairepickle** [comment]
Tested on demo site and works as expected

**Comment by eileenmcnaughton** [comment]
merging based on @Clairepickle testing. Code looks sensible & non-risky

**Comment by yashodha** [comment]
@Clairepickle @eileenmcnaughton thanks!

**Pull request merged**
