### PR TITLE
bin/givi - Add backdrop support

### PR DESCRIPTION
**Pull request by totten**
This script is little-used but sometimes helpful when juggling multiple
versions in the same source-tree.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
giving this merge on pass as this is limited to an obscure dev tool & is very low risk

**Comment by eileenmcnaughton** [comment]
@totten jenkins hates your indenting

https://test.civicrm.org/job/CiviCRM-Core-PR/12152/checkstyleResult/new/category.183606530/

**Comment by seamuslee001** [comment]
@totten this is good to merge now

**Pull request merged**
