### PR TITLE
add source field to returned fields in Contact.get

### PR DESCRIPTION
**Pull request by MegaphoneJon**
Overview
----------------------------------------
API3 Contact.get doesn't return the `source` (aka `contact_source`) field.

While API3 is deprecated, I think this qualifies as a bug, since I can't think of any other scenario in which a core field isn't returned from the corresponding API3 get call.

You can replicate this with `cv api Contact.get id=3`, or `cv api Contact.get id=3 | grep source` if your eyes are getting tired.

Before
----------------------------------------
APIv3 Contact.get doesn't return the source field.

After
----------------------------------------
It does.

### CODE REVIEW

**Comment by seamuslee001** [comment]
So I think that this seems to be affecting some search / contact selector query tests and I thought it might affect "primary fields" exports @eileenmcnaughton would that be right?

**Comment by MegaphoneJon** [comment]
It looks like these tests need updating more than the patch needs changing - I'll do that if there is otherwise agreement about this.

**Comment by eileenmcnaughton** [comment]
Yeah - I guess there is no good reason not to do this

**Comment by mattwire** [comment]
Ok @MegaphoneJon we have agreement. If you can update the tests I can review/merge

**Comment by eileenmcnaughton** [comment]
fails are in `CRM_Contact_SelectorTest`

**Pull request merged**
