### PR TITLE
Hooks on Cases

### PR DESCRIPTION
**Pull request by bastienho**
These hooks allow extensions to filter cases.

Typically, without usage of API4, extended behaviors such as hierarchical ACLs can't be effective.

### CODE REVIEW

**Comment by bastienho** [comment]
That would be great, but at this time, the cases dashboard uses DAO functions.

Is there a roadmap for migration to API4?

**Comment by demeritcowboy** [comment]
Have you seen https://lab.civicrm.org/extensions/casesummary? Does that help your use-case?

**Comment by bastienho** [comment]
> Have you seen https://lab.civicrm.org/extensions/casesummary? Does that help your use-case?

No, I didn't. But it seems interesting.

Has it been tested with hierarchical-acl?

**Comment by colemanw** [comment]
> @bastienho Has it been tested with hierarchical-acl?

It uses SearchKit, which has been tested to work with ACLs. I'm not sure what you mean by "hierarchical-acl" but all ACL rules should work in SearchKit.

**Comment by bastienho** [comment]
After more tests, many views still don't use APIv4, specially in dashboards. 

These 3 new hook don't impact processes in core since there not automatically called, but they allows extension to implement  filters for advanced settings.

**Comment by bastienho** [comment]
> > @bastienho Has it been tested with hierarchical-acl?
> 
> It uses SearchKit, which has been tested to work with ACLs. I'm not sure what you mean by "hierarchical-acl" but all ACL rules should work in SearchKit.

The new summary manages ACLs via searchkit, but it do not replaces the dashboard view nor the dashlet.

**Comment by demeritcowboy** [comment]
These aren't blocking comments, more just thoughts:

> These 3 new hooks don't impact processes in core

They don't, but once they're there, people will use them and expect them to keep working. So when the dashboard is replaced one of two things will happen:
1. These hooks won't get called anymore, and so stop working, and become deprecated, OR
2. There'll be two competing ways of doing acl which is maybe fine, but increases complexity when they conflict.

The second thing is because _everybody_ wants a different thing on their case dashboard, even different people within the same org, in the past I've usually just made another page that does what they actually want. (One anecdote showing at least one other person using drupal views instead: https://civicrm.stackexchange.com/a/35850/181)

Lastly, usually when new hooks are added a unit test is desirable to protect them, but as per the first point they might get bypassed and then it won't protect them anyway.

But, as you say, at the moment there are a couple screens using the current code.

**Comment by colemanw** [comment]
If we want consistency I think best focus on switching existing screens to use the API. It's really not that hard to swap a SQL query for an APIv4 query, the language is quite similar. Certainly much easier than going all the way with swapping the smarty page out with SearchKit.

**Comment by bastienho** [comment]
>  IMO the `getCases()` function ought to be deprecated in favor of `Civi\Api4\CiviCase::get()`. And APIv4 already has lots of hooks.

@colemanw so I would better make a PR that move from SQL to API in the actual methods?

**Comment by colemanw** [comment]
@bastienho yes IMO it would be better to make a PR that changes `getCases()` internally to use the api instead of a sql query. A lot of what it's doing (e.g. checking permissions, matching pseudoconstants) can be ripped out because the API already does it.

**Pull request closed without merging**
