### PR TITLE
Add $params type declaration to global API functions.

### PR DESCRIPTION
**Pull request by mfb**
Overview
----------------------------------------
Why not add a type declaration for API $params?

Before
----------------------------------------
There is no type declaration for API $params; if you pass in scalar you get Warning: Cannot use a scalar value as an array and then Uncaught exception: CiviCRM_API3_Exception: Input variable `params` is not an array 

After
----------------------------------------
Declare type so IDE can use it, and PHP throws earlier.

### CODE REVIEW

**Comment by colemanw** [comment]
I think the reason is because PHP did not support this until recently.

**Comment by mfb** [comment]
yes but the `array` type declaration has been supported since PHP 5.1.0 so this should be ok now :)  

(real soon now we can add type declarations for strings, nullables etc..)

**Comment by eileenmcnaughton** [comment]
I agree - this might not have been possible before php 7 was min ver but it is now

**Comment by mfb** [comment]
right but it was a PHP 5.1 thing not PHP 7. It looks like there are a bunch of tests passing in a not-array and expecting to get a different error message back.

**Comment by eileenmcnaughton** [comment]
Yeah - I'd be happy to rip out those tests TBH - I feel they are overkill - maybe just one & it doesn't need to be syntax conformance for every entity & action....

**Comment by monishdeb** [comment]
Merging as per tag

**Pull request merged**
