### PR TITLE
dev/core#5079 Handle money localization before anything else in formRule

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
---------------------------------------

dev/core#5079 Handle money localization before anything else in formRule

Before
----------------------------------------
See https://lab.civicrm.org/dev/core/-/issues/5079

After
----------------------------------------
Localized & non-numeric values are handled in the Contribution Main formRule function

Technical Details
----------------------------------------
This ensures the values are passed through the de-localization functions before any more handling is done

Comments
----------------------------------------
@MegaphoneJon

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
This works if someone's put in a localized value (e.g. 5.000$) but doesn't handle alpha characters ("5 dollars").  But it got me looking at the right part of the code.  I'll put up an alternate and you can tell me what you think.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon I pushed it in - also with a small change for https://lab.civicrm.org/dev/core/-/issues/5100 as reported by @wmortada

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon is this all good to merge? I see you closed the other

**Comment by wmortada** [comment]
I've tested this and can confirm that it fixes https://lab.civicrm.org/dev/core/-/issues/5100.

It also appears to fix https://lab.civicrm.org/dev/core/-/issues/5079 as far as I understand this issue. It couldn't reproduce the issue for '5 dollars' but I could reproduce the issue with '$5.00' and can confirm that this fixes the issue.

I've created two separate PRs to backport the fix for dev/core#5100:

- 5.71 https://github.com/civicrm/civicrm-core/pull/29776
- 5.69 https://github.com/civicrm/civicrm-core/pull/29777

**Pull request merged**
