### PR TITLE
Add Examples to api explorer

### PR DESCRIPTION
**Pull request by colemanw**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
cool

**Comment by colemanw** [comment]
All those nice test-generated examples can finally see the light of day :)

The other thing I wanted to add was a tab to display a human-readable version of the docblocks for each api. But I can't seem to find a lightweight combination of tools to achieve this (that wouldn't introduce a bunch of new dependencies to our already bloated packages dir).

**Comment by eileenmcnaughton** [comment]
I had been leaning towards having a second metadata function for apis (or a change to the existing _spec but I think that is too widely used in custom code) that would add notes & documentation and declare permissions.

Doc blocks make sense too - although I guess the driver for what I had been thinking was actually more about the permissions.

**Comment by colemanw** [comment]
I thought I added a permission callback function already. IIRC you 
weren't a fan.

**Comment by colemanw** [comment]
@totten this is odd - it seems that CheckStyle is attempting to parse .tpl files as if they were php

**Comment by eileenmcnaughton** [comment]
There is a callback but you can't query it can you?

I don't remember disliking it - I probably came around.....

**Comment by totten** [comment]
https://github.com/civicrm/civicrm-buildkit/blob/6f197df4f/bin/civilint#L62

civilint autodetects PHP files by looking for "<?php" or "#!/usr/bin/php" in the first line. (This deals with some of the weirder conventions like Drupal's *.module, *.inc, *.install.) documentFunction.tpl is one of the five tpl templates which generates PHP code -- which puts it in a weird place WRT to code-style. But I guess at the end of the day phpcs will not properly check a Smarty=>PHP code-generator, so it should skip those files.

https://github.com/civicrm/civicrm-buildkit/commit/d42ca76f71bf448b25067c60f8c8417fe440fb33

**Comment by totten** [comment]
test this please

**Pull request merged**
