### PR TITLE
CRM-18389: Cannot create recurring membership contribution

### PR DESCRIPTION
**Pull request by monishdeb**
- [CRM-18389: Cannot create recurring membership contribution](https://issues.civicrm.org/jira/browse/CRM-18389)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Hey @monishdeb do you want to add a note as to why this is against the rc rather than master? 

(the usual rule would be it would only go against an rc if it was to fix a regression in the rc although I think that could stretch to the previous point release or a new critical/ security bug (ie. not one that could have been fixed in time for the rc but wasn't but a newly identifed one that had priority for some reason).

**Comment by kurund** [comment]
@eileenmcnaughton we were facing this issue on civicrm.org, hence I wanted to push this in the release.

**Comment by eileenmcnaughton** [comment]
Can I merge all the ones affecting my sites too then :-)

**Comment by kurund** [comment]
Don't you always do that :-)

**Comment by eileenmcnaughton** [comment]
Not into the rcs!!!

**Pull request merged**
