### PR TITLE
Improve I18n schema by including comments and default and NOT NULL or…

### PR DESCRIPTION
**Pull request by seamuslee001**
… NULL statements to be more consistant with non lingual schema

Overview
----------------------------------------
This adds more information to the I18n schema structure so that when the translated schema is created it is more similar to the non multilingual schema

Before
----------------------------------------
New columns that are added may not have correct default or missing comments

After
----------------------------------------
More consistent schema

ping @mlutfy @pfigel @eileenmcnaughton thoughts?

### CODE REVIEW

**Comment by mlutfy** [comment]
I agree on the concept, this would be a nice improvement.

I slightly worry on the duplication. We could run into issues where a description is changed in an XML schema file, but not updated in this i18n file. Probably an exception that does not happen often: some time ago, the interpretation of a field was reversed (`is_something`).

(not against merging, just raising the concern)

**Comment by seamuslee001** [comment]
@mlutfy i think that is the same issue as ensuring DAOs are regenerated etc (which btw this file gets generated when you generate the DAOs by ./bin/setup.sh -g or ./bin/regen.sh)

**Comment by eileenmcnaughton** [comment]
I think @seamuslee001 is correct - this is 'the same' as the main DAOS - merging based on otherwise positive feedback

**Comment by mlutfy** [comment]
Perfect, thank you!

**Comment by MegaphoneJon** [comment]
This seems to have caused a regression - it was caught earlier (translation#38, possible core#1800 as well) but isn't recent at this point, so I didn't tag https://github.com/civicrm/civicrm-core/pull/20753 as a regression.

**Pull request merged**
