### PR TITLE
Afform - Add getters/setters to the AfformSubmitEvent class

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds some missing getter/setter functions to make it easier for 3rd-parties to interact with Afform submissions.

Before
----------------------------------------
Saved ids not accessible, not clear how to read or write the list of records to be saved.

After
----------------------------------------
Better

### CODE REVIEW

**Comment by wyde22** [comment]
Thanks so lot for this patch @colemanw . I'm realizing a test and I had to review a little your code. In my project, i can't use this method `getEntityId(int $index = 0)`. In my phpstorm IDE i have an error in the method `CoreUtil` (class undefined). 

so i change this code for my test :

`
public function getEntityId(int $index = 0) {
    //$idField = CoreUtil::getIdFieldName($this->entityName);
    return $this->entityIds[$this->entityName][$index];
  }
`

My version of civicrm is 5.40.2

**Comment by colemanw** [comment]
> My version of civicrm is 5.40.2

Ah, right, you would need the current beta version of CiviCRM for that to work. It was added here: 12e4505a2193162253eb5a1132af87b0c65bf2b9

For now, I suggest you use this (which is different from what you pasted above because it will return the id not an array). This will be compatible with this PR when you do upgrade:

```php
  public function getEntityId(int $index = 0) {
    $idField = 'id';
    return $this->entityIds[$this->entityName][$index][$idField] ?? NULL;
  }
```

**Comment by wyde22** [comment]
Thanks @colemanw

**Comment by seamuslee001** [comment]
This seems fine to me

**Pull request merged**
