### PR TITLE
CRM-16725 - Add Preview PDF button to PDF Letter task so users can re…

### PR DESCRIPTION
**Pull request by davecivicrm**
…view PDF without creating activity.

---
- CRM-16725:
  https://issues.civicrm.org/jira/browse/CRM-16725

### CODE REVIEW

**Comment by kurund** [comment]
jenkins, test this please

**Comment by colemanw** [comment]
@kurund this is still a wip

**Comment by colemanw** [comment]
Test failures unrelated.

**Comment by davecivicrm** [comment]
Test failure is unrelated.

**Pull request merged**
