### PR TITLE
dev/core#4410: fixed timezone support for standalone

### PR DESCRIPTION
**Pull request by jaapjansma**
Overview
----------------------------------------

This adds timezone support the user of stand alone CiviCRM.

See https://lab.civicrm.org/dev/core/-/issues/4410

@artfulrobot  can you review this?

### CODE REVIEW

**Comment by jaapjansma** [comment]
I have this same issue in a Drupal 10 site where I can change my timezone. Looks like a CiviCRM core issue not handling the timezones correctly in displaying dates.

**Comment by demeritcowboy** [comment]
FYI the PR has a merge conflict.

Just a comment on what you're seeing: TIMESTAMP db fields _do_ (should) display differently when you change the timezone, DATETIME fields have no concept of timezone. The log record at the bottom of the contact summary for example is a mix of these. The created date is a timestamp, and should update, whereas the "last change" is a datetime and will not update. This isn't by design in civi - it's just never really had full timezone support. So here's an example where the user was created with timezone UTC, then switched to New_York. The "last change" doesn't change, but the "created" does, so for now I would expect standalone to work the same.

untitled3

**Comment by demeritcowboy** [comment]
It seems like loadBootstrap is not called in standalone? So then setMySQLTimeZone() doesn't get called.

If I put `CRM_Core_Config::singleton()->userSystem->setMySQLTimeZone();` in web/index.php in invoke() just before `print CRM_Core_Invoke::invoke($args);` then it does _something_. But I haven't been following development enough to know if that's the right place. But that still doesn't make it quite the same as drupal. E.g. the contact summary change info updates the same way as drupal, but on a new contribution the default time doesn't use my specified timezone.

**Comment by demeritcowboy** [comment]
Ok let's merge this and figure out where to put the call to setMySQLTimeZone after. Since obviously the form part is working.

test fail is the usual ongoing fail.

**Pull request merged**
