### PR TITLE
CRM-17493 - Fix importing to checkbox type fields where label is the same as database value

### PR DESCRIPTION
**Pull request by jmcclelland**
Ensure checkbox custom field imports work.

---

 * [CRM-17493: Issue with importing to checkbox type fields where label is the same as database value \(may affect other types too\)](https://issues.civicrm.org/jira/browse/CRM-17493)

### CODE REVIEW

**Comment by mlutfy** [comment]
It's mentioned in the JIRA issue, but I double-checked: this patch was already merged in 4.6, but not 4.7, so seems like something that should be merged (but I haven't tested).

**Comment by seamuslee001** [comment]
@eileenmcnaughton @jmcclelland is this still needed?

**Comment by eileenmcnaughton** [comment]
I'm going to close it & allow @jmcclelland to re-open as those functions have moved since this was submitted. Unclear if a fix is required or not

**Comment by idmacdonald** [comment]
Hi, I am still seeing this problem with imports in CiviCRM 5.10.4 on PHP 7.0. I applied the code changes from this PR, and that has solved the problem. So, I think this fix is still needed. @jmcclelland, have you also found this problem to still be happening?

**Comment by idmacdonald** [comment]
Shall I create a new issue for this on https://lab.civicrm.org ?

**Comment by mlutfy** [comment]
@idmacdonald Please do.

**Comment by jmcclelland** [comment]
Yes, please open on lab.civicrm.org. I'm sorry I never completed this tag. I just checked, and I've been carrying this patch in git repo, so yes, it seems to continue working.

**Pull request closed without merging**
