### PR TITLE
CRM-16189, added opening_balance and current_period_opening_balance d…

### PR DESCRIPTION
**Pull request by pradpnayak**
…b fields code for on install and upgrade

---
- CRM-16189: Improve support for Accrual Method bookkeeping
  https://issues.civicrm.org/jira/browse/CRM-16189

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I'm adding merge on pass on this. I think adding these fields is uncontroversial as they are additional information rather than functional and I'm happy to accept Joe's call on the appropriateness of them.

The PR seems risk-free to me if it passes tests

**Comment by pradpnayak** [comment]
Can some one merge this?

**Comment by JoeMurray** [comment]
@yashodha please merge as checks have passed

**Pull request merged**
