### PR TITLE
CRM-20334, Fatal Error on Submit Credit Card Contribution Form

### PR DESCRIPTION
**Pull request by pradpnayak**
…able

----------------------------------------
* CRM-20334: Fatal Error on Submit Credit Card Form
  https://issues.civicrm.org/jira/browse/CRM-20334

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I agree with this change - but it needs to go into the rc

**Comment by eileenmcnaughton** [comment]
OK - this is against the rc now. I will merge here to - I dont' think that will mess with the rc merges to master & I worry that if multiple people hit this it will cause everyone to work on it.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 FYI

**Comment by JoeMurray** [comment]
@adixon this has been merged and will likely come out in next nightly tarball. Would be great if you could QA. Thx!

**Pull request merged**
