### PR TITLE
[pending core team review] CRM-16621

### PR DESCRIPTION
**Pull request by pradpnayak**
- [CRM-16621](https://issues.civicrm.org/jira/browse/CRM-16621)

### CODE REVIEW

**Comment by davecivicrm** [comment]
@pradpnayak Looks like there's a related test failure at:
https://test.civicrm.org/job/CiviCRM-Core-PR/5786/testReport/junit/(root)/api_v3_SyntaxConformanceTest__testSqlOperators/testSqlOperators_with_data_set__75/

**Comment by pradpnayak** [comment]
jenkins, retest this please

**Comment by totten** [comment]
The style issues don't seem to be the fault of any changes in this PR, but we do need to get through them. Breaking it down:

 * `MagicMerge.php` and `AddMessageTemplateTest.php` - These files have been cleaned up already, but your branch has an old copy. `git pull --rebase origin master` (followed by `git push pradpnayak CRM-16621 -f` or similar) should resolve them.
 *  `GenerateReportData.php`, `crm.searchForm.js`, and `jquery.dashboard.js` have somehow achieved bad styling. It's conceivable that they were missed during the original mass-cleanup, or they could have come through a loophole at some point. (Ex: If you make a change in v4.5, it's not subject to style rules; that change can then get merged forward.)
 * `civicrm.settings.php.template` - This is a problem with the style-checker. It gets a bit confused with the meta-php file.

I'll work on the `civicrm.settings.php.template` issue and the JS files. Could someone else take a crack at `GenerateReportData.php`?

**Comment by davecivicrm** [comment]
@totten I'm doing style fixes on GenerateReportData.php - super fun :-(

**Comment by totten** [comment]
Cleanups:
 * https://github.com/civicrm/civicrm-core/pull/7207
 * https://github.com/civicrm/civicrm-buildkit/pull/196

**Comment by davecivicrm** [comment]
More cleanups: https://github.com/civicrm/civicrm-core/pull/7209

**Comment by davecivicrm** [comment]
@pradpnayak  Can u rebase this please.

**Comment by pradpnayak** [comment]
updated the commit

**Comment by davecivicrm** [comment]
Related test failure now at https://test.civicrm.org/job/CiviCRM-Core-PR/6530/testReport/junit/%28root%29/api_v3_SyntaxConformanceTest__testSqlOperators/testSqlOperators_with_data_set__76/

**Comment by eileenmcnaughton** [comment]
I'm closing this for 2 reasons
1) it's stale & needs rebasing
2) if you do choose to rebase it then it won't have much visibility because it's so far down the list.

So, assuming this is still relevant please re-base & re-open the PR so it shows up near the top of the list.

**Pull request closed without merging**
