### PR TITLE
APIv4 - Fix output of membershipType auto_renew field

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Ensure the "auto_renew" field is returned correctly by the MembershipType API.

Before
----------------------------------------
Returns true/false

After
----------------------------------------
Returns int

Technical Details
----------------------------------------
The field had been declared a "boolean" in the schema, which at a SQL level is exactly the same as "tinyint" but it was resulting in incorrect API output.

See https://github.com/civicrm/civicrm-core/pull/20768#issuecomment-879129624

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
CRM_Member_Form_MembershipRenewalTest.testSubmitRecurCompleteInstantWithMail with data set #0
CRM_Member_Form_MembershipRenewalTest.testSubmitRecurCompleteInstantWithMail with data set #1
CRM_Member_Form_MembershipRenewalTest.testSubmitRecur
CRM_Member_Form_MembershipRenewalTest.testSubmitRecurCompleteInstant
CRM_Member_Form_MembershipTest.testSubmitRecur
CRM_Member_Form_MembershipTest.testSubmitRecurCompleteInstant

**Comment by jitendrapurohit** [comment]
@colemanw Confirmed that the patch fixes the return value of auto_renew. Thanks for the fix :)

image

Test failures seem mostly like test related? the params are [passed as boolean](https://github.com/civicrm/civicrm-core/blob/master/tests/phpunit/CRM/Member/Form/MembershipTest.php#L786), instead of 0/1/2.

**Comment by colemanw** [comment]
@jitendrapurohit @eileenmcnaughton I've updated the tests. Want to merge-on-pass?

**Comment by eileenmcnaughton** [comment]
unrelated fail

**Pull request merged**
