### PR TITLE
Afform - Fix chainSelect to work with anonymous users

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
A few fixes following up from #21749 

- Fixes chainSelect to work with anonymous users
- Correctly handle empty lists (e.g. countries with no states or provinces)

### CODE REVIEW

**Comment by rbaugh** [comment]
I tested commit [2ab97fa](https://github.com/civicrm/civicrm-core/pull/21759/commits/2ab97fabeb3b844b3180f98599d75205f51b540e) and can confirm that it fixes the API call issue for anonymous on getting the state/province data for the field when form loads and when country changes. This was an issue for anonymous users once the chainSelect connection was fixed.

**Comment by colemanw** [comment]
All good. The unit test will get automatically run by our CI infrastructure & the yellow status on this PR will turn green in a couple hours.

**Comment by rbaugh** [comment]
Sounds good, thanks for working on this.

**Comment by colemanw** [comment]
Merging per review & unit tests passing

**Pull request merged**
