### PR TITLE
PayPal Pro IPN - Fix incorrect option_group update

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------

This is primarily a theoretical bug which occurs if the value of the Completed status has been changed for the contribution or contribution_recur option group.

It was picked up in  https://lab.civicrm.org/dev/core/-/issues/4158  but does not appear to be the fix for that issue

Before
----------------------------------------
In a test I was able to verify existing test/s fail if the value for Completed in the contribution status option group is not the same as the contribution recur option group. 

After
----------------------------------------
Correct option group referenced, test checks

Technical Details
----------------------------------------
I think an rc merge without a stable back port is OK (although a backport is OK too)

Comments
----------------------------------------
Incorrect change was https://github.com/civicrm/civicrm-core/commit/ba2fb5afa3aa403467ae4934731684cc51bc830d#diff-fca5e61bfa602d8d253d868b26ca6e7469f343fa3623d937d70480f650cdd3f0R296

### CODE REVIEW

**Comment by totten** [comment]
civibot, test this please

**Comment by totten** [comment]
@eileenmcnaughton There's a test-failure on ` api_v3_JobTest::testCallDisableExpiredRelationships
` which seems to be related+reproducible.

**Comment by eileenmcnaughton** [comment]
Ah - hooks still in place & doing dumb things

**Comment by eileenmcnaughton** [comment]
@totten that passes now

**Comment by totten** [comment]
OK, cool. Glad that part's working @eileenmcnaughton.

**Pull request merged**
