### PR TITLE
Add deprecation notice to hook_civicrm_links used by search forms

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
See [dev/core#5096](https://lab.civicrm.org/dev/core/-/issues/5096).

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Hmm. If something is deprecated and the text says there is a replacment, then any tests should be updated to cover the same thing the test was covering but using the replacement. If there isn't a way to do that yet, then the deprecation could just be a Civi::log() warning instead.

**Comment by colemanw** [comment]
> could just be a Civi::log() warning instead.

Yea good idea.

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by eileenmcnaughton** [comment]
Just noting we hit this & the use of the `log()` without the normal deprecation notice meant that something causing a tonne of logging on prod did not show up in the UI on my dev environment - which is normally my second line of defense (after unit tests) to pick up something like this. (Not sure if we had test cover, but that wouldn't have triggered).

I've put some comments on the gitlab about how we can tone this down a bit since there is not really a viable alternative to implementing that hook for contribution search - which I think means it's a bit premature to create noise for contribution search at this point, maybe some others too. I think it's OK where there is an alternative in admin UI - although (mumble mumble translation)

https://lab.civicrm.org/dev/core/-/issues/5096#note_169100

**Pull request merged**
