### PR TITLE
APIv4 - Add backticks around fields in join criteria

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes https://lab.civicrm.org/dev/mail/-/issues/103
See #22045

### CODE REVIEW

**Comment by seamuslee001** [comment]
Well this makes my test pass so that is something

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by colemanw** [comment]
Test failures appear to be unrelated to this PR, they all seem to be to do with @eileenmcnaughton's work on undefined smarty variables. Tests are failing with a smarty error "Undefined index 'breadcrumb'"

**Comment by colemanw** [comment]
Closing in favor of 5.44 backport #22051

**Pull request closed without merging**
