### PR TITLE
Fold small private function back into only caller

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
In this case we have layers of small functions doing elaborate formatting for each other and then other functions de-formatting. This is part of flattening these functions into a single loop

### CODE REVIEW

**Comment by colemanw** [comment]
Leave it to CiviCRM to make simple things elaborately overcomplicated!

**Comment by eileenmcnaughton** [comment]
As discussed on product maintenance - targetting rc for a few more days on a piece of work to fix up bounce processing for verp to keep changes together

**Comment by eileenmcnaughton** [comment]
Note that https://github.com/civicrm/civicrm-core/pull/27352 includes this but will be rebased out with this merged

**Comment by eileenmcnaughton** [comment]
Closing as this will conflict...

**Comment by eileenmcnaughton** [comment]
Preferred function to merge wil lost this change but keeping that current is more important

**Pull request closed without merging**
