### PR TITLE
Unit test for #16148

### PR DESCRIPTION
**Pull request by jitendrapurohit**
unit test for https://github.com/civicrm/civicrm-core/pull/16148

ping @mattwire

### CODE REVIEW

**Comment by mattwire** [comment]
Thanks @jitendrapurohit

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit can you rebase?

**Comment by mattwire** [comment]
Thanks @jitendrapurohit closing this as it has now been merged via #16148

**Pull request closed without merging**
