### PR TITLE
CRM-21126: fix default selection of member_is_primary input

### PR DESCRIPTION
**Pull request by jitendrapurohit**
Overview
----------------------------------------
default selection of member_is_primary input is not done on passing param through URL.

Before
----------------------------------------
Passing `owner` in the url does not enable any option in `member_is_primary` radio input. 

Eg.  http://dmaster.demo.civicrm.org/civicrm/member/search?reset=1&force=1&status=1,2,3&type=12&owner=1 screen would not select `Primary Member?` input in the membership search form. This would lead to incorrect contacts in export and various task.

image

After
----------------------------------------
`Primary Member?` is correctly selected.

---

 * [CRM-21126: member_is_primary not set by default on passing owner in the url](https://issues.civicrm.org/jira/browse/CRM-21126)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit this seems OK & I guess @lcdservices probably has a vested interest here. But, I think perhaps we should cast $owner to 1 or 0 ? e.g 

$this->_defaults['member_is_primary'] =  ( $owner ? 1 : 0);

**Comment by jitendrapurohit** [comment]
The above would set `Primary Member?` to `No` even if `owner` param is not present in the url. 

Eg. http://dmaster.demo.civicrm.org/civicrm/member/search?reset=1&force=1 would still check the `No` option. 

Shouldn't we clear this field if we don't have any valid value (0 or 1) for owner? Hence the `is_null` check.

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit yep the isNull check is good - but if not null then it is binary - ie. 0 = 0, 1=1 , 2=1, twentyfivefrogs=1

so I am just suggesting making that more expicit

**Comment by jitendrapurohit** [comment]
Have done so now 👍

**Comment by eileenmcnaughton** [comment]
Seems fine to me now. Let's merge on pass

**Pull request merged**
