### PR TITLE
[NFC] code changes for export with merge household

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Minor code tidy ups

Before
----------------------------------------
No change

After
----------------------------------------
No change

Technical Details
----------------------------------------
Changes one variable to be named earlier & stops passing two variables that can be retrieved at no code due to caching in the called function

Comments
----------------------------------------
I'm trying to work through  #11870 & these are 2 minor changes en route to making sense of that (one of them is in that PR already & the other is my own). @monishdeb can you check this & merge.

That code is hurting my head :-(

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by totten** [comment]
jenkins, test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by monishdeb** [comment]
Tested it on local and its safe to merge, doesn't break the workflow. From code pov it makes sense.

**Pull request merged**
