### PR TITLE
API search on custom fields for other entities than contacts (CRM-16036)

### PR DESCRIPTION
**Pull request by johanv**
This is a fix - maybe more a workaround - for CRM-16036.
Sorry for the many commits; there aren't that many changes in the end.

There is a [forum thread](http://forum.civicrm.org/index.php/topic,35956.0.html) about this branch. This fix/workaround is probably not 100% ready, but as it solves the problem, I created a pull request already.

---
- [CRM-16036: API: searching on custom fields only works for contacts](https://issues.civicrm.org/jira/browse/CRM-16036)

### CODE REVIEW

**Comment by johanv** [comment]
Hmm, the [build log](https://test.civicrm.org/job/CiviCRM-Core-PR/2589/console) says:

    ===============================[ php -l ]===============================
    PHP Parse error:  syntax error, unexpected '[' in api/v3/utils.php on line 529
    Errors parsing api/v3/utils.php

But [line 529 of utils.php](https://github.com/civicrm/civicrm-core/pull/5350/files#diff-3076917760efeb467459726ebb6af282R529) is the first line in an if-block, and it says:

    $operator = array_keys($value)[0];

So now I am confused :confused:

**Comment by colemanw** [comment]
That syntax is not supported in every version of php. CiviCRM officially supports php 5.3 (and over half of existing installs in the wild are still running 5.3).

**Comment by eileenmcnaughton** [comment]
I feel like we can close this because it was merged into core in a different PR - any concerns with me closing it?

**Comment by eileenmcnaughton** [comment]
I'm going to close this - like my previous comment this work has already gone into master under a different PR (& is a great improvement - thanks @johanv )

**Comment by johanv** [comment]
No worries. I'm glad that this got fixed in 4.7, because I need this for our own instance :-)

**Pull request closed without merging**
