### PR TITLE
Check tax is present in online contribution page receipt

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This extends the test improvements in https://github.com/civicrm/civicrm-core/pull/28129 to ensure that the fields that depend on the `{contribution.tax_amount}` token are present in the pay later + add payment flow with online contribution pages.

Note @demeritcowboy identified these as missing with use of the receipt but I'm not totall sure which flow. I think this rules it out  in the pending + pay later flow & I re-use most of this test to try out the payment-on-form flow once this is merged

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Sorry I'll update the ticket with the exact steps.

**Comment by eileenmcnaughton** [comment]
thanks @demeritcowboy

**Comment by eileenmcnaughton** [comment]
@demeritcowboy I just checked the insttructions - it should be pretty easy to extend this test to cover that immediate payment scenario (hopefully it all passes this time & can be merged)

**Comment by demeritcowboy** [comment]
Rounding errors:

```
CRM_Contribute_Form_Contribution_ConfirmTest::testSubmitContributionPageWithPriceSetQuantity with data set #0 ('.')
Failed asserting that 3723.0499999999997 matches expected 3723.05.

/home/homer/buildkit/build/build-2/web/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:3392
```

**Comment by eileenmcnaughton** [comment]
@demeritcowboy argh I was focussed on rounding the wrong side

**Comment by eileenmcnaughton** [comment]
Unrelated test fails 

No changes.
Started by upstream project [CiviCRM-Core-Matrix-PR](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/) build number [6325](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6325/)
originally caused by:

GitHub pull request #28138 of commit 1b694a208e40dc7e00b56693d2e4855bc272554c, no merge conflicts.
[Test Result](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6325/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/) (2 failures / ±0)
[Civi\FlexMailer\FlexMailerSystemTest.testText](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6325/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_FlexMailer_FlexMailerSystemTest/testText/)
[Civi\FlexMailer\FlexMailerSystemTest.testHtmlWithOpenAndUrlTracking](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6325/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_FlexMailer_FlexMailerSystemTest/testHtmlWithOpenAndUrlTracking/)

**Comment by demeritcowboy** [comment]
I agree it's unrelated so will merge, but it seems like it might be from https://github.com/civicrm/civicrm-core/pull/28053 which was merged recently even with related fails.

**Pull request merged**
