### PR TITLE
dev/core#1371 Fix e-notice caused by trying to pass in known  to the …

### PR DESCRIPTION
**Pull request by seamuslee001**
…extension downloader when checking requirements

Overview
----------------------------------------
This fixes an e-noticed reported by @stesi561 when running cv ext:download

Before
----------------------------------------
E-notice

After
----------------------------------------
no e-notice

ping @eileenmcnaughton @mattwire

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
will you do a 5.19 pr too?

**Comment by seamuslee001** [comment]
@eileenmcnaughton i can do

**Comment by stesi561** [comment]
The relevant gitlab issue is here: https://lab.civicrm.org/dev/core/issues/1371

**Comment by seamuslee001** [comment]
@eileenmcnaughton 5.19 port is here https://github.com/civicrm/civicrm-core/pull/15763

**Pull request merged**
