### PR TITLE
Datatables update

### PR DESCRIPTION
**Pull request by josephlacey**
CRM-16353 - DataTables API v2 upgrade

---
- [CRM-16353: Upgrade datatables integration to use v2 api](https://issues.civicrm.org/jira/browse/CRM-16353)

### CODE REVIEW

**Comment by josephlacey** [comment]
Hey @colemanw, I've moved all the javascript within CRM.$.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
Looks like it got stalled on minor style fixes

**Comment by eileenmcnaughton** [comment]
@colemanw Can we give this the 'merge on pass' label?

**Comment by colemanw** [comment]
jenkins, retest this please

**Pull request merged**
