### PR TITLE
dev/core#2704 SearchKit - Add support for SQL functions

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Support SQL functions in the SearchKit UI

See https://lab.civicrm.org/dev/core/-/issues/2704

Before
----------------------------------------
Only aggregate functions supported

After
----------------------------------------
More functions work

Comments
----------------------------------------
For now it's limited to functions that take a single field as input.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw I'm struggling to figure out how to see the new functions - not in the listing here

image

**Comment by eileenmcnaughton** [comment]
But I feel like the 'distinct' checkbox is missing

image

**Comment by eileenmcnaughton** [comment]
OK - some cache clearing and I can see they work with no aggregate in place but when aggregate is on the list is more limited (but distinct is back!)

image

With no group by I get this bigger list

image

And year only works

image

As does time only but the output for 'date only' is confusing - it truncates the date but shows '12 am' instead of nothing

image


The 'is null' one is pretty cool.

'math' and 'text' show - but can't be selected

**Comment by seamuslee001** [comment]
I'm thinking that we maybe should merge this as it is a clear improvement unless the others can be fixed up easily but this seems to be a good improvement

**Comment by eileenmcnaughton** [comment]
@seamuslee001 no - it actually causes some things to disappear in aggregate mode at the moment

**Comment by colemanw** [comment]
> @seamuslee001 no - it actually causes some things to disappear in aggregate mode at the moment

What is disappearing @eileenmcnaughton ?

**Comment by eileenmcnaughton** [comment]
@colemanw - see https://github.com/civicrm/civicrm-core/pull/20947#issuecomment-887102275 - first image - no MAX etc

**Comment by colemanw** [comment]
@eileenmcnaughton I can't reproduce that locally. Are you able to reproduce it on the demo site and post a link to that search?

**Comment by eileenmcnaughton** [comment]
@colemanw total_amount & net_amount http://core-20947-5ue5k.test-1.civicrm.org:8001/civicrm/admin/search#/edit/1

**Comment by eileenmcnaughton** [comment]
Also - if you remove group by you get the weird thing with 'Text' being there 'as if' it means something but doesn't seem to (in the drop down)

**Comment by colemanw** [comment]
Ah ok thanks @eileenmcnaughton - found it & fixed both issues.

**Comment by colemanw** [comment]
@eileenmcnaughton and I just pushed up another commit to fix the date formatting.

**Comment by eileenmcnaughton** [comment]
@colemanw api\v4\Action\SqlFunctionTest::testGroupAggregates
Failed asserting that false is true.

/home/jenkins/bknix-dfl/build/core-20947-610bn/web/sites/all/modules/civicrm/tests/phpunit/api/v4/Action/SqlFunctionTest.php:69
/home/jenkins/bknix-dfl/extern/phpunit8/phpunit8.phar:671

**Comment by colemanw** [comment]
@eileenmcnaughton fixed

**Comment by eileenmcnaughton** [comment]
@colemanw the Replace transform isn't working - perhaps you could suppress it long enough to get this merged & then re-add it? I'm otherwise happy with the pr

image

**Comment by colemanw** [comment]
@eileenmcnaughton done. It was supposed to be already hidden because this PR doesn't support > 1 field per function.

**Comment by eileenmcnaughton** [comment]
The things I previously identified are fixed. I did spot one more thing - the functions being offered for amounts are suitable able for text rather than money columns. However, I think that one lends itself to being fixed in a follow up so I'm merging this now @colemanw 

image

**Pull request merged**
