### PR TITLE
CRM-20004 Fix regression Event payment receipt sent twice

### PR DESCRIPTION
**Pull request by spalmstr**
Contributor 
spalmstr commented 6 minutes ago • edited 
@eileenmcnaughton
Did this:
git checkout -b new upstream/4.7.17rc
(that creates a new branch based off the upstream version of 4.7.17rc)
and then
git cherry-pick 9100f86
Then pushed new to origin and created this PR.

### CODE REVIEW

**Comment by spalmstr** [comment]
Sorry about the many false starts.  Eventually, I'll get there.

**Review by seamuslee001 — APPROVED** [review]
Excellent work

**Comment by eileenmcnaughton** [comment]
Well done! I takes a bit to get really comfortable with git - but it's great when you get there.

**Comment by spalmstr** [comment]
Many thanks for your help @JoeMurray isn't aware of it, I think.

**Pull request merged**
