### PR TITLE
Surveys: Fix I18n translation support and WYSIWYG support

### PR DESCRIPTION
**Pull request by seamuslee001**
The "instructions" field is already a wysiyg in singlelingual mode.

Overview
----------------------------------------
This allows for the user interface to update the translation for the instructions field

Before
----------------------------------------
Database is translatable but UI does not support it

After
----------------------------------------
Both DB and UI support translating of the field

Technical Details
----------------------------------------
Note that on the form https://github.com/civicrm/civicrm-core/blob/master/CRM/Campaign/Form/Survey/Main.php#L126 https://github.com/civicrm/civicrm-core/blob/master/CRM/Campaign/Form/Petition.php#L174 it is already a WYSIWYG which means that RichTextEditor is the correct widget to use not TextArea

ping @demeritcowboy @eileenmcnaughton @mlutfy

### CODE REVIEW

**Comment by demeritcowboy** [comment]
So close!

Untitled3

It's strange because the english version seems ok. For some reason the other language shows the html.

**Comment by demeritcowboy** [comment]
Ah if I go back and edit the spanish now the english is html. So it's not being racist it's that there's some double escaping going on.

**Comment by seamuslee001** [comment]
hmm that does feel strange maybe something in the way the l10n form saves?

**Comment by seamuslee001** [comment]
@demeritcowboy I believe I have found the problem see https://github.com/civicrm/civicrm-packages/pull/361

**Comment by mlutfy** [comment]
Correct me if i'm wrong, but I tweaked the PR title because it helps with release notes.

(I haven't tested yet, but sounds like a good catch)

**Pull request merged**
