### PR TITLE
Afform - support opening new case

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Allows the Case entity to be added to Form Builder and configure case client and other fields (including custom). Submitting the form will open a new case for the specified client, which could be the current user, or another contact on the form.

### CODE REVIEW

**Comment by kurund** [comment]
@colemanw 

a. When the form is configured  to use logged in contact information, 
- Contact information correctly updated
- Case correctly created against the logged in user

b. Same for when form is configured to create new contact
- Contact information correctly updated
- Case is not created.

Screenshot from 2022-08-16 18-54-10

Screenshot from 2022-08-16 18-54-28

**Comment by colemanw** [comment]
@kurund based on your screenshot the problem is that you haven't given any value for Case Client so it is unable to save the case.

**Comment by kurund** [comment]
@colemanw 

I want it to be associate with the newly created contact rather than logged in contact. Hence, it's removed.

**Comment by kurund** [comment]
Ok, it needs to be below configuration for linking to the contact
Screenshot from 2022-08-18 10-01-55

**Review by kurund — APPROVED** [review]
Looks good to me and is working as expected. Ready for merging.

**Comment by kurund** [comment]
@colemanw 

This may not be specific to this. It would be nice to create a case without actually including any case field on the form. I am setting case defaults, see below

Screenshot from 2022-08-18 10-46-38

**Comment by kurund** [comment]
@colemanw 

Yes, ofcourse you can delete as per above screenshot. What would be nice to create a case with default values without actually need of any fields on the form.

**Comment by colemanw** [comment]
@kurund you mean if the defaults were magically set without requiring you to set them in the "Values" section of the form?

**Comment by kurund** [comment]
@colemanw

Apologies for the delayed response. Somehow I missed this comment.

I meant if filter values are set it should automatically create a case with those values without a need to include additional fields in the form.

**Pull request merged**
