### PR TITLE
CRM-20029 - Copy custom files when duplicating an event

### PR DESCRIPTION
**Pull request by colemanw**
* [CRM-20029: Events with file custom fields don't copy the files](https://issues.civicrm.org/jira/browse/CRM-20029)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This looks fine. My only reservation is that it is updating a function which appears to me to be in the wrong place

public static function copyCustomFields($oldEventID, $newCopyID) {

would need very little change to sit on the CustomField BAO & be generic. As it is I kinda suspect there is a duplicate function of this out there for another entity somewhere

**Comment by colemanw** [comment]
Yes the comment in `CRM_Event_BAO_Event`:

    // copy activity attachments ( if any )

gives us a pretty good clue where that code was copy-pasted from. Since events cannot have attachments, I suspect that particular line does nothing at all.

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by eileenmcnaughton** [comment]
well, I guess short of refactoring it to be where it should be you could add some code comments so no-one ever edits it again without moving it :-)

**Comment by eileenmcnaughton** [comment]
Merging this - since it seems it was just a request for more comments outstanding

**Pull request merged**
