### PR TITLE
Autoload services based on interfaces/annotations. Convert APIv4 services.

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

(*This is an alternative to #23877 and a follow-up to #23854.*)

Building on #23854's support for scanning PHP classes (`scan-classes@1`), this allows you to auto-register hook-listeners, event-subscribers, and container-services.  This is a fairly generic mechanism which can work with classes in core and contrib.

Moreover, this branch also converts some existing services to use the mechanism, thereby reducing the weight of `Civi/Core/Container.php`. (For an example giving the general idea of a conversion, see ab0d96faafc5032ac0eebbdb91df7d3785c99d36.)

cc esp @colemanw @artfulrobot

Example 1 (Small)
----------------------------------------

This registers a service and subscribes to an event:

```php
/**
 * @service
 * @internal
 */
class CRM_Chef_CatchPhrase extends AutoService implements HookInterface {

  public function getCatchPhrase() {
    return 'Bork bork bork';
  }

  public function hook_civicrm_alterContent(&$content, $context, $tplName, &$object) {
    $content .= $this->getCatchPhrase();
  }

}
```

For example, it would be valid to use the service in these ways:

```php
// (Direct) Call a method in the service
Civi::service('CRM_Chef_CatchPhrase')->getCatchPhrase();

// (Indirect) Fire an event, which happens to go to the service
CRM_Utils_Hook::alterContent($content, ...);
```

As long as the class is visible to `scan-classes@1`, there is no need for explicit registration steps.  You don't need to edit `Civi/Core/Container.php` or implement `hook_container` or edit a PHP mainfile or create an XML/YAML/JSON file. 

Example 2 (Medium)
----------------------------------------

This example is largely the same, except that we use a few more features, eg

* Set a custom name for the service (`@service <name>`).
* Access other services from the container (`@inject <name>`).

```php
/**
 * @service chef.catch-phrase
 */
class CRM_Chef_CatchPhrase extends AutoService implements HookInterface {

  /**
   * @var \Psr\Log\LoggerInterface
   * @inject psr_log
   */
  public $log;

  protected $catchPhrase = 'Bork bork bork';

  public function hook_civicrm_alterContent(&$content, $context, $tplName, &$object) {
    $this->log->info($this->catchPhrase);
    $content .= $this->catchPhrase;
  }

}
```

Example 3 (Large)
----------------------------------------

In this example, we use `AutoServiceInterface` instead of `AutoService`. 

```php
class SwedishChefServices implements AutoServiceInterface {
  public static function buildContainer($container): void {
    $container->setDefinition('chef.catch-phrase', new Definition('CRM_Chef_CatchPhrase'));
    $container->setDefinition('chef.hat', new Definition('CRM_Wardrobe_Hat', ['#fff', '15cm']));
    $container->setDefinition('chef.breakfast', new Definition('CRM_Chef_Menu', ['7:00 AM']));
    $container->setDefinition('chef.dinner', new Definition('CRM_Chef_Menu', ['7:00 PM']));
  }
}
```

This allows more control over the definition(s). `AutoService` is designed for the typical/easy-to-understand case where one class corresponds to one service with some predictable conventions, but it does not give full access to the `$container` API. By contrast, if you implement `AutoServiceInterface` directly, then you can get access to the full `$container` API.

Before
----------------------------------------

* To register a new service, you must edit `Civi/Core/Container.php` (*core*) or implement `hook_container` (*extensions*).
* `Civi/Core/Container.php` is a long list of services.
* `CRM/Api4/Services.php`and `CRM/API4/services.xml` use several different file-loading patterns.
 
After
----------------------------------------

* To register a new service, you may simply extend `AutoService` or `AutoServiceInterface`.
* `Civi/Core/Container.php` is... not as long. Some services have been converted. (And we can convert more.)
* `CRM/Api4/Services.php`and `CRM/API4/services.xml` no longer exist. The related services have been converted.

Comments
----------------------------------------

This is generally similar in spirit to #23877, with a few key distinctions:

* It supports both `HookInterface` and `EventSubscriberInterface`.
* It resolves a couple issues that faced #23877:
    * It supports both `static` and non-`static` listener methods.
    * There are edge-cases where scanning for `EventSubscriberInterface` would be overzealous -- eg you hit classes which are registered by other means (eg existing hook_container registrations) or which subscribedto different dispatchers entirely (eg Drupal's dispatcher, or some library's dispatcher). You need to ensure that Civi only auto-registers subscribers that are appropriate for Civi.
* This variant also helps us to split apart `Civi\CoreContainer`

If the general concept seems OK, and if the tests pass, I could split to some smaller PRs.

### CODE REVIEW

**Comment by totten** [comment]
Just a note from a test-failure:

* The test failure on yesterday's build was about the conversion of `SearchSegmentExtraFieldProvider` and the upgrade-test (circa 5.39.1). I spent a not-entirely-sensible-or-enviable amount of time trying to figure out why. I squeezed on it pretty hard to ensure that the `Definition`s and `Container`s were the same -- but the upgrade still failed, even if the patch produces *exactly* the same `Container` and `SpecGatherer` output.
* The difference appears to be like this: the 5.39.1 upgrade-test runs various steps, including some API calls. The patch had the effect of changing the timing (ie *among upgrade-steps, which upgrade-step makes the API-call that first spurs`SearchSegmentExtraFieldProvider` to action*). The calls in `CRM_Upgrade_Incremental_php_FiveFortyThree::updateGreetingOptions` and the search-kit `Upgrader` are relevant, but the details were counter-intuitive, and I didn't fully understand the dynamic.
* But it only changed within the upgrade-sequence, and it only matters because the upgrader calls APIv4 to edit a couple `OptionValues` (*which effectively pings 50+ listeners for metadata - while the DB is still in broken/mid-upgrade form - which is obviously a recipe for upgrade bugs*).
* So, anyway, on this branch I just left `SearchSegmentExtraFieldProvider` on the legacy-scan, and it works for now. But I think we need stronger enforcement to prevent API calls from slipping into the upgrader.

**Comment by colemanw** [comment]
@totten tests are passing - is this ready for review?

**Comment by totten** [comment]
@colemanw Yeah, I think it's in decent shape. There are a couple bikesheddy that could be changed (e.g. maybe `AutoService{,Interface}` should just be `Service{,Interface}`?). But I probably won't change that unless a reviewer wants it. :)

Anyway, I've also got docs drafted: [merge request](https://lab.civicrm.org/documentation/docs/dev/-/merge_requests/1022) and [web preview](http://think.hm/docs/dev-svc/framework/services).

I'll remove the (EXP) flag.

**Comment by colemanw** [comment]
My take on this PR is that it's merge-ready. It has tests, it passes tests, it has docs, and the code is well-orgnized and commented.
Due to the complex nature of the change I'd recommend merging after the next fork of `master` in a few days.

**Comment by totten** [comment]
@colemanw @demeritcowboy - So this was flagged "merge ready", but I'm aware that there's some overlap with the investigation into test performance.

Do we want to get some improvements merged there -- and then re-run/re-benchmark with this?

**Comment by demeritcowboy** [comment]
I think this is mostly about class scanning? We've determined class scanning itself wasn't the major issue so adding more likely won't change speed much.

So do you mean merge #24491 and then re-run this? Or vice-versa?

**Comment by colemanw** [comment]
I think it's fair to say this PR isn't causing the slowdown since it's not merged, and I agree with @demeritcowboy so let's merge it and I guess note whether future PRs go significantly slower.

**Comment by demeritcowboy** [comment]
My guess is this might be the reason for this: https://github.com/SemperIT/CiviCARROT/actions/runs/3071942401/jobs/4963064480#step:21:36. Will check tomorrow.

**Pull request merged**
