### PR TITLE
Add ContributionSoft v4 api

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Add ContributionSoft v4 api

Before
----------------------------------------
Just empty space

After
----------------------------------------
Tada

Technical Details
----------------------------------------
Very standard

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
I think the test data just needs to include a dummy contribution.

**Comment by eileenmcnaughton** [comment]
@colemanw I looked at the test & can't see where it's creating dummy data - does it just rely on default test data (in which case I'd need to add a setUp routine and create one & tear it down)

I also note the test just throws 'Exception' - our standard is to throw CRM_Core_Exception if we don't have something more specific - is there any reason not to change to that?

**Comment by colemanw** [comment]
I think you'd add it here: https://github.com/civicrm/civicrm-core/blob/master/tests/phpunit/api/v4/DataSets/ConformanceTest.json

Core exception sounds fine to me.

**Comment by eileenmcnaughton** [comment]
@colemanw OK passing now

**Pull request merged**
