### PR TITLE
(WIP) Get Drupal 8 working in 4.6

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @jackrabbithanna We will want a branch in civicrm-drupal but i basically used the 8,x-master branch with a couple of tweaks for 4.6

### CODE REVIEW

**Comment by jackrabbithanna** [comment]
Holy Wow! I wonder what the powers that be would feel about a 4.6-dev release with Drupal 8 and php 7 support.

**Comment by seamuslee001** [comment]
hmm I am now just trying to debug an issue now and will work on the style issues

**Comment by eileenmcnaughton** [comment]
I'm not opposed to this - but it kind of seems like a waste of time - ie. if you want a new feature (drupal8 support of php7 support) then you should upgrade to 4.7. Also, since drupal 8 development is still being actively worked on it seems premature to think about backporting unless you feel you have a 4.7 version that is not changing much any more.

I think whether to merge it is an LTS team call - ie. as long as 4.6 does not have features / fixes that 4.7 does not then the LTS team can make up it's own mind on the relative risks / benefits of backporting new features like php7 support, Mosaico support & drupal 8 support. 

What I would suggest to @jackrabbithanna  & @guanhuan is that they don't feel pressured to rush any decisions about what to add to 4.6 - it has been released for 2 years now & anything that has not been dealt with in that time cannot suddenly be urgent (with usual provisos about recent regressions & security fixes).

**Comment by jackrabbithanna** [comment]
@eileenmcnaughton I believe @seamuslee001 starting putting this together after I asked if it was possible.  To my surprise he pulled this rabbit out of his hat.  I think he must just love to develop and create.  I also think its great.  I don't think there's any intention to make a public release of 4.6 on D8 any time soon or merge this into the main branch, but it may happen that 4.6 lives for a while, because there are those of us that are happy with it, and remain unsure about some things in 4.7.  That may change, with time.  Believe me I'm getting an education just reading all the new notifications from github and all the JIRA filters I subscribed to and paying much more attention to what is going on everyday.  I have a new appreciation for what you have been doing all these years. 4.6 with D8 may never be released for the general public,  But an implementer may be able to implement this for a client if that client decided that's what they wanted, and that implementer could manage it themselves for the client. If people want to play and develop in the sandbox, don't see that does any harm.

**Comment by eileenmcnaughton** [comment]
Yeah - I certainly don't want to suppress @seamuslee001's boundless enthusiasm!

One issue with things that are not ready to merge is they can make keeping an eye on our PR queue more work - so if it is going to be a long-term thing I recommend creating a ticket & adding a link there to the commits or  branch comparision rather than keeping the PR open

**Comment by totten** [comment]
+1 eileen -- As long as things stay aligned with `master`, it's a judgment call by the LTS team whether they want to pursue D8/PHP7. I wouldn't do it if I were you, but I'm sure there are some benefits.

Aside: PHP7 in 4.7 required some, eh, political diligence... because it [nominally changed dependencies](https://civicrm.org/blog/totten/psa-please-verify-php-extension-mysqli) (esp `install/index.php`). If you change dependencies in LTS, consider exercising similar diligence.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I think we should close this & re-open if there is enthusiasm at some point to do this. I would not a LOT of changes have happened since this was opened to support drupal 8 in master & it seems like a big job to get this to the point of merge, without an obvious customer for the work. 

If Svkare DO get a paying customer or decide to self-fund it then they can still use all this work, without us keeping the PR open

**Comment by jackrabbithanna** [comment]
Closing for now, and we can re-open when we get the funding.

**Pull request closed without merging**
