### PR TITLE
CRM-19718: Allow activity Priority field to be included in profiles

### PR DESCRIPTION
**Pull request by yashodha**
* [CRM-19718: Allow activity Priority field to be included in profiles](https://issues.civicrm.org/jira/browse/CRM-19718)

### CODE REVIEW

**Comment by yashodha** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
This looks good to me but a couple of minor things
1) add export = true to the xml. It is not apparently required since the DAO seems to show it anyway.
2) I think we should add uniqueName to the field at this point. It's not currently exposed in search so it won't affect that but since we are adding it to export and it is conceivable that another table could have the same field added I think we should get the unique name established before it gets added anywhere since it's harder to add when a conflict does arise.
3) I notice you have specifically added the field to the UFGroup::buildProfile rather than let the default handle it. But, the default *should* be able to handle it based on the information in the metadata (with some tweaking). I note that prefix_id & suffix_id use the following:

```
      $form->addSelect($name, array(
        'label' => $title,
        'entity' => 'contact',
        'field' => $fieldName,
        'class' => 'six',
        'placeholder' => '',
      ), $required);
```

The metadata should identify any fields that use option groups so we should be able to change the final default to something like:

```
    else {
      if ($field['type']  === 'bool' {
        $form->add('advcheckbox', $name, $title, $attributes, $required);
      }
      elseif (!empty($field['pseudoconstant']['optionGroupName']) {
            $form->addSelect($name, array(
        'label' => $title,
       /// how do we know the entity? We could calculate it from 
      // 'where' => 'civicrm_activity.priority_id', but I'm rather tempted to explicitly add it to the gencode 
     // so the dao holds 'entity' => 'activity', '
        'entity' => 'contact',
        'field' => $fieldName,
        'class' => 'six',
        'placeholder' => '',
      ), $required);
    else {
        $form->add('text', $name, $title, $attributes, $required);
      }
    }
```

**Comment by eileenmcnaughton** [comment]
@colemanw this is the second time in 2 days I've wanted to know the entity or BAO from a field in an array of fields that is 'cross-entity' - I'm tempted to add the DAO or entity to the field metadata to save calculating it - any thoughts.

**Comment by colemanw** [comment]
It would be easy to add...

**Comment by yashodha** [comment]
test this please

**Comment by yashodha** [comment]
test this please

**Comment by yashodha** [comment]
test this please

**Comment by jitendrapurohit** [comment]
jenkins, retest this please

**Comment by kurund** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I have some work in progress on activity & contribution search so I can review this for next release (4.7.17) if it misses this month

**Comment by eileenmcnaughton** [comment]
I'm closing this because I think it is already fixed in core - I could add 'Priority' to a profile although I wasn't sure if there was a particular way it should have worked. I note that we talked about making the change below but haven't - but I think it is fixed without it.

+++ b/xml/schema/Activity/Activity.xml
@@ -260,8 +260,11 @@
   </index>
   <field>
     <name>priority_id</name>
+    <uniqueName>activity_priority_id</uniqueName>
     <type>int unsigned</type>
     <title>Priority</title>
+    <import>true</import>
+    <export>true</export>
     <comment>ID of the priority given to this activity. Foreign key to civicrm_option_value.</comment>
     <add>2.0</add>
     <pseudoconstant>

**Pull request closed without merging**
