### PR TITLE
CRM-21082: CRM_Core_Resources::singleton()->getUrl sends Drupal paths…

### PR DESCRIPTION
**Pull request by laryn**
… to Backdrop install

Overview
----------------------------------------
_Tweaks for Backdrop functionality with getting URLs from extensions._

Before
----------------------------------------
_I installed the CiviCRM-Stripe extension and was testing it when I noticed that the Javascript file was not attaching correctly. It was trying to pull from a Drupal path (`/sites/default/files/...`) rather than a Backdrop path (`/files/...`).

After
----------------------------------------
_Changed a bunch of `drupal_` calls to `backdrop_` calls and added a `CRM_Utils_System_BackdropBase` class to fix the path issue._

### CODE REVIEW

**Comment by totten** [comment]
Cool, I had noticed a related problem -- the "Asset Caching" feature ("Administer => System Settings => Debug") had to be disabled because the `civicrm.files` URL wasn't resolving correctly. This would manifest as failure to load Angular pages (like `civicrm/a/#/cxn`). This seems to fix that, but something else is going wrong. Results from my manual test on :

| code | asset-caching? | do angular pages work? |
| ---- | ----- | ---- |
| current master | enabled | no (due to civicrm.files url issue?)
| current master | disabled | yes
| master + PR 10877 | enabled | no  (maybe something to do with aggregation?)
| master + PR 10877 | disabled | no  (maybe something to do with aggregation?)

**Comment by totten** [comment]
@laryn any particular purpose behind copying/reproducing the base-class -- versus a more minimal page (overriding `getDefaultFileStorage()`)?

**Comment by herbdool** [comment]
I agree, we can just override getDefaultFileStorage() and can still use the Drupal base class.

I suggest also putting the changes from drupal_ to backdrop_ in a separate PR so it can be accepted separately.

**Comment by laryn** [comment]
@totten @herbdool I mainly reproduced it because there were a number of `drupal_*` calls that I wanted to change to `backdrop_*` calls so that it will work without the Drupal compatibility mode turned on in Backdrop. 

I'm open to whatever you think is best, I'm admittedly a bit out of my depth and just trying to make it work. :)

**Comment by laryn** [comment]
And where did I introduce that `undefinedpackages` error...?

**Comment by colemanw** [comment]
I agree we should not have a separate base class for backdrop.
If you wish, we could change `CRM_Utils_System_Backdrop` to extend `CRM_Utils_System_Base` directly instead of extending the Drupal base class. But I don't think we need 2 of them.

**Comment by laryn** [comment]
I will try to revise and see if I can get a better approach.

**Comment by herbdool** [comment]
@laryn I think you can just include the `getDefaultFileStorage()` method you created in `CRM_Utils_System_Backdrop` and it will override the Drupal base path. That's the easiest approach, I think. And it'll be easier to debug if we keep the change small.

We can create new issues and PRs for any other issues we come across in this class. I can help with that.

**Comment by laryn** [comment]
@totten @herbdool Can you try the latest? I'll file another issue and do another PR to switch the `drupal_` calls to `backdrop_` calls.

**Comment by colemanw** [comment]
Looks like this is now redundant.

**Comment by laryn** [comment]
@colemanw Can you clarify what you mean by redundant?

**Comment by laryn** [comment]
@colemanw My bad, just realized I committed these changes in the other branch, too. Thanks.

**Comment by herbdool** [comment]
@laryn @totten  I've tested the latest changes and the Angular pages, like civicrm/a/#/status, work for me with both enabled and disabled assets caching.

**Comment by herbdool** [comment]
@laryn I'm not sure if you even need to create `parseBackdropSiteNameFromRequest` since there's nothing different in the function from `parseDrupalSiteNameFromRequest`.

**Comment by laryn** [comment]
@herbdool I didn't have that initially and it was giving an error due to trying to access a private function. 

I also wasn't exactly sure what these lines did so I didn't change those from 'drupal' to 'backdrop' within that function:

`\Civi::$statics[__CLASS__]['drupalSiteName'] = $sites[$dir];`

**Comment by herbdool** [comment]
@laryn I see so that makes sense to copy it. I'm not sure either about that static 'drupalSiteName' variable. Doesn't seem to hurt. Perhaps @totten can weigh in.

**Comment by totten** [comment]
@laryn @herbdool Great! The smaller patch definitely seems more manageable. Glad it's working now! 🍾 

Splitting out `parseBackdropSiteNameFromRequest()` seems OK to me.

In that context, choosing between `\Civi::$statics[__CLASS__]['drupalSiteName']` and `\Civi::$statics[__CLASS__]['backdropSiteName']` should be primarily aesthetic. A couple reasons:
 * AFAICS, the static variable isn't actually *consumed* anywhere. It seems like a left-over from an unfulfilled/aborted/reconsidered thought. 
 * The `__CLASS__` would resolve differently within the context of `Backdrop.php` vs `DrupalBase.php`.

**Pull request closed without merging**
