### PR TITLE
[REF] Ensure that the from is correctly modified in both the main que…

### PR DESCRIPTION
**Pull request by seamuslee001**
…ry and in the statistics section of the Contribute Summary Report

Overview
----------------------------------------
This aims to ensure that when constructing the from in the statistics section that any extensions that wish to modify the from correctly do so otherwise it can lead to a DB error as the _where clause is not re-created in the statistics

Before
----------------------------------------
Possible DB error if an additional field has been added to the report for a separate table that then isn't included in the from as there is no hooking in the statistics

After
----------------------------------------
No DB error

ping @eileenmcnaughton @mattwire

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton @mattwire I have added a unit test now demonstrating the problem

**Comment by eileenmcnaughton** [comment]
I guess it has a test so that's good but we should really just be telling people to write their own reports - these hooks are a maintenance nightmare

**Comment by eileenmcnaughton** [comment]
I've given this merge on pass - I think it's bad bad bad but it has a test so the badness is not new. If this is about adding ACLs it's even badder since we have a methodology  for that.

**Comment by seamuslee001** [comment]
@eileenmcnaughton its specifically around adding in a financial account column to the report this is the relevant client code i was working with https://github.com/CanadaHelps/chreports/blob/master/chreports.php#L217

**Comment by eileenmcnaughton** [comment]
Sigh  - well  I've let it through since there is precedent for this awfulness & a unit test.

@colemanw this is the sort of thing we need to allow people to do  in our replacement...

**Pull request merged**
