### PR TITLE
CRM-18448 Port fixes from FuzionRepo around allowing for editing of f…

### PR DESCRIPTION
**Pull request by seamuslee001**
…inancial types on recurring contributions to core

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton I think this captures everything and tries to get stuff back into core. I think this is ok but you know this code base more than I do

**Comment by eileenmcnaughton** [comment]
@seamuslee001 hmm if none of it is in core but it's all in 4.7 & nothing is broken & it won't break when you upgrade to 4.7 it might not be worth it.  I suspect there are tpl changes too?

**Comment by seamuslee001** [comment]
Yeh tho it is in fuzion's 4.6 repo and i'm not sure how wide that is but we have been running this in prod for a little while and seems safe.

**Comment by seamuslee001** [comment]
@eileenmcnaughton I have just added in the template files and ported your commit from the fuzion repo So I think this will match the AUG code then

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Pull request merged**
