### PR TITLE
Support for E2E testing with Mink for Afform

### PR DESCRIPTION
**Pull request by MegaphoneJon**
Overview
----------------------------------------
This adds support for E2E testing for Afform using Mink, along with a test class in Admin UI for the Manage Groups page.

This has an intentionally failing test to see if these tests are picked up.

Before
----------------------------------------
No tests

After
----------------------------------------
Tests

Technical Details
----------------------------------------
I'll write this later.

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
test this please

**Comment by seamuslee001** [comment]
@MegaphoneJon can you rebase against the current master?

**Comment by MegaphoneJon** [comment]
Here's the message from Jenkins:
```
CRM_CivicrmAdminUi_ManageGroupsTest::testManageGroups
RuntimeException: Could not fetch version information from http://127.0.0.1:9222/json/version. Check if Chrome is running. See docs/troubleshooting.md if Chrome crashed unexpectedly.
Json Error: Syntax error.
Response was: 

/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/vendor/dmore/chrome-mink-driver/src/ChromeBrowser.php:69
/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/vendor/dmore/chrome-mink-driver/src/ChromeDriver.php:130
/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/vendor/behat/mink/src/Session.php:77
/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/Civi/Test/MinkBase.php:74
/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/Civi/Test/MinkBase.php:23
/home/homer/buildkit/extern/phpunit9/phpunit9.phar:2307
```

I'm guessing a headless Chrome will need to be added to the build process.

**Comment by seamuslee001** [comment]
hmm I know we have headless Chrome for use as part of Karma testing these days but maybe that fires up differently  but I also wonder if that is a problem because you got backtrace not a json object

**Comment by MegaphoneJon** [comment]
What can we do to help get this working on the test infra?  I'm happy to squash, fix merge conflicts etc., but it doesn't make sense to fix the conflict if the tests won't run.

**Comment by totten** [comment]
Based on the code, I believe this is the test-failure that we're expecting:

Screenshot 2024-06-15 at 5 50 16 PM

**Comment by totten** [comment]
* Rebased again to reconcile with latest `composer.lock`  change(30547).
* Updated to remove the part where it intentionally provokes a test-failure
* Changed a folder to match convention (`tests/phpunit/E2E` for end-to-end tests)
* Ran locally via CLI and IDE with Chrome Headless. 
* Used the `SCREENSHOT` flag to make it record a screenshot. (This should probably be updated to make the path more configurable -- so it's easier to configure jobs which treat screenshots as output artifacts. But it's an opt-in thing; not a blocker.)
 
@seamuslee001 @demeritcowboy Unless y'all have some objection, I favor merging this on pass.

**Comment by colemanw** [comment]
Seconded!

**Pull request merged**
