### PR TITLE
Support tplVars in MessageTemplate.send when Smarty disabled

### PR DESCRIPTION
**Pull request by artfulrobot**
Overview
----------------------------------------

The MessageTemplate.send API takes an optional `template_params` or `tplParams` key, which is an array of `key => value` such that content like `${key}` inside of a message gets translated to `value`.

This is a really useful feature for adding custom, one-off use tokens.

However, the current implementation relies on Smarty to do the substitutions. This then fails when the API is called with the  `disable_smarty` param.

This PR applies the `tplParams` to the message template when not using Smarty.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@artfulrobot technically this is an internal only function (not supported via the api etc) but I think you are wanting this because you have an extension that calls this function and you want to pass paramters in?

My worry is that if we add functionality to an internal api then it can easily be cleaned up again so we need to think about how we protect it - or whether we can can formalise some exposure of this. It does somewhat tie into some discovery @totten has on his plate

**Comment by mattwire** [comment]
tplVars is a bit of an undefined mess and gets all kinds of stuff passed in for different templates. @artfulrobot Can you explain a bit more detail your use-case as there might be a better way to do it.

For example:
- *all* tokens in CiviCRM take the form `{entity.key}` (the dot being important).
- You've identified that (I didn't realise) that tplVars are using smarty syntax ie. `${key}` which we don't really want to support because we'd like to drop smarty at least in templates one day.
- You'd like the ability to pass in simple/one-off tokens to a template. Maybe we should add a new, supported syntax for this? Eg. `{key}`. Note that eg. twig uses `{{ var }}` so this would not clash with a future twig template parser.

**Comment by mattwire** [comment]
@artfulrobot Thanks for the explanation. I agree this makes sense as it's not a new feature and there seems no reason not to support it even if we'd like to drop it going forward. That said, it was all a bit of a mystery to me and could really use some docs somewhere - even at a simple level maybe just updating the description on the api parameter so it says *what* will actually be replaced (ie. anything in the format `{$key}`.

**Comment by eileenmcnaughton** [comment]
@artfulrobot you are right I had forgotten that api was there.

I think this would need a test to be mergeable - but I'd also like to wait a bit & get feedback when @totten does some discovery work around this (December I expect) & get a bigger picture plan around handling message templates & apis around that

**Comment by eileenmcnaughton** [comment]
@artfulrobot OK sure - I have a nasty suspicion I wrote that api that I had not recollection of when we started this conversation - but if is simply an entry point into an adhoc existing function - I think we should nail down what apis we should have - which I think is covered in the discovery work Tim has some (small) funding for. What you have written is a good start on that

**Comment by jaapjansma** [comment]
@artfulrobot I did not know `MessageTemplate`.`send` existed. If knew that I would probably not created the email api. The e-mail api is around for more than 5 years so it could also be that the send api is newer. The email api extension also has han integration with civirules.

**Comment by eileenmcnaughton** [comment]
Aha - good old PR https://github.com/civicrm/civicrm-core/pull/2448 -  I was about to point out git blame didn't implicate me after all until I saw my PR comment...

**Comment by demeritcowboy** [comment]
This has merge conflicts.

**Comment by eileenmcnaughton** [comment]
Let's close it for now then - Rich can catch up with Tim if this is still wanted & figure out how to do it in api4

**Pull request closed without merging**
