### PR TITLE
[REF] Fix Syntax on contribution online receipt text

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This fixes a syntax error that I found with a recently installed site

Before
----------------------------------------
Unmatched {\if}

After
----------------------------------------
poof

@eileenmcnaughton @demeritcowboy Can someone confirm my thinking that this is wrong?

### CODE REVIEW

**Comment by demeritcowboy** [comment]
I can look, just probably tomorrow (my time) - so two days from now for you - pretty sure that's how timezones work (grin).

**Comment by eileenmcnaughton** [comment]
@seamuslee001 style

**Comment by demeritcowboy** [comment]
If I reformat the tpl then yes I agree the `{/if}` is misplaced, BUT it also becomes more obvious that the `{else}` just above is wrong since if $amount is blank then using $amount in the output makes no sense, and then comparing to the html version it's not quite the same code regarding the `{else}`.

```
{assign var="greeting" value="{contact.email_greeting}"}{if $greeting}{$greeting},{/if}
{if $receipt_text}
  {$receipt_text}
{/if}
{if $is_pay_later}

  ===========================================================
  {$pay_later_receipt}
  ===========================================================
{/if}

{if $amount}
  ===========================================================
  {ts}Contribution Information{/ts}

  ===========================================================
  {if $lineItem and $priceSetID and !$is_quick_config}
    {foreach from=$lineItem item=value key=priceset}
      ---------------------------------------------------------
      {capture assign=ts_item}{ts}Item{/ts}{/capture}
      {capture assign=ts_qty}{ts}Qty{/ts}{/capture}
      {capture assign=ts_each}{ts}Each{/ts}{/capture}
      {if $dataArray}
        {capture assign=ts_subtotal}{ts}Subtotal{/ts}{/capture}
        {capture assign=ts_taxRate}{ts}Tax Rate{/ts}{/capture}
        {capture assign=ts_taxAmount}{ts}Tax Amount{/ts}{/capture}
      {/if}
      {capture assign=ts_total}{ts}Total{/ts}{/capture}
      {$ts_item|string_format:"%-30s"} {$ts_qty|string_format:"%5s"} {$ts_each|string_format:"%10s"} {if $dataArray} {$ts_subtotal|string_format:"%10s"} {$ts_taxRate} {$ts_taxAmount|string_format:"%10s"} {/if} {$ts_total|string_format:"%10s"}
      ----------------------------------------------------------
      {foreach from=$value item=line}
        {capture assign=ts_item}{if $line.html_type eq 'Text'}{$line.label}{else}{$line.field_title} - {$line.label}{/if}
        {if $line.description} {$line.description}{/if}
          {/capture}{$ts_item|truncate:30:"..."|string_format:"%-30s"} {$line.qty|string_format:"%5s"} {$line.unit_price|crmMoney:$currency|string_format:"%10s"} {if $dataArray}{$line.unit_price*$line.qty|crmMoney:$currency|string_format:"%10s"}
          {if $line.tax_rate != "" || $line.tax_amount != ""}  {$line.tax_rate|string_format:"%.2f"} %  {$line.tax_amount|crmMoney:$currency|string_format:"%10s"}
          {else}
          {/if}
        {/if} {$line.line_total+$line.tax_amount|crmMoney:$currency|string_format:"%10s"}
    {/foreach}
  {/foreach}

  {if $dataArray}
    {ts}Amount before Tax{/ts}: {$amount-$totalTaxAmount|crmMoney:$currency}

    {foreach from=$dataArray item=value key=priceset}
      {if $priceset || $priceset == 0}
        {$taxTerm} {$priceset|string_format:"%.2f"}%: {$value|crmMoney:$currency}
      {else}
        {ts}No{/ts} {$taxTerm}: {$value|crmMoney:$currency}
      {/if}
    {/foreach}
  {/if}

  {if $totalTaxAmount}
    {ts}Total Tax Amount{/ts}: {$totalTaxAmount|crmMoney:$currency}
  {/if}

  {ts}Total Amount{/ts}: {$amount|crmMoney:$currency}
{else}
  {ts}Amount{/ts}: {$amount|crmMoney:$currency} {if $amount_level } - {$amount_level} {/if}
{/if}

{if $receive_date}

  {ts}Date{/ts}: {$receive_date|crmDate}
{/if}
{if $is_monetary and $trxn_id}
  {ts}Transaction #{/ts}: {$trxn_id}
{/if}

{if $is_recur}
  {ts}This is a recurring contribution.{/ts}

  {if $cancelSubscriptionUrl}
    {ts}You can cancel future contributions at:{/ts}

    {$cancelSubscriptionUrl}

  {/if}

  {if $updateSubscriptionBillingUrl}
    {ts}You can update billing details for this recurring contribution at:{/ts}

    {$updateSubscriptionBillingUrl}

  {/if}

  {if $updateSubscriptionUrl}
    {ts}You can update recurring contribution amount or change the number of installments for this recurring contribution at:{/ts}

    {$updateSubscriptionUrl}

  {/if}
{/if}

{if $honor_block_is_active}
  ===========================================================
  {$soft_credit_type}
  ===========================================================
  {foreach from=$honoreeProfile item=value key=label}
    {$label}: {$value}
  {/foreach}
{elseif $softCreditTypes and $softCredits}
  {foreach from=$softCreditTypes item=softCreditType key=n}
    ===========================================================
    {$softCreditType}
    ===========================================================
    {foreach from=$softCredits.$n item=value key=label}
      {$label}: {$value}
    {/foreach}
  {/foreach}
{/if}
{if $pcpBlock}
  ===========================================================
  {ts}Personal Campaign Page{/ts}

  ===========================================================
  {ts}Display In Honor Roll{/ts}: {if $pcp_display_in_roll}{ts}Yes{/ts}{else}{ts}No{/ts}{/if}

  {if $pcp_roll_nickname}{ts}Nickname{/ts}: {$pcp_roll_nickname}{/if}

  {if $pcp_personal_note}{ts}Personal Note{/ts}: {$pcp_personal_note}{/if}

{/if}
{if $onBehalfProfile}
  ===========================================================
  {ts}On Behalf Of{/ts}

  ===========================================================
  {foreach from=$onBehalfProfile item=onBehalfValue key=onBehalfName}
    {$onBehalfName}: {$onBehalfValue}
  {/foreach}
{/if}

{if $billingName}
  ===========================================================
  {ts}Billing Name and Address{/ts}

  ===========================================================
  {$billingName}
  {$address}

  {$email}
{elseif $email}
  ===========================================================
  {ts}Registered Email{/ts}

  ===========================================================
  {$email}
{/if} {* End billingName or Email*}
{if $credit_card_type}

  ===========================================================
  {ts}Credit Card Information{/ts}

  ===========================================================
  {$credit_card_type}
  {$credit_card_number}
  {ts}Expires{/ts}: {$credit_card_exp_date|truncate:7:''|crmDate}
{/if}

{if $selectPremium }
  ===========================================================
  {ts}Premium Information{/ts}

  ===========================================================
  {$product_name}
  {if $option}
    {ts}Option{/ts}: {$option}
  {/if}
  {if $sku}
    {ts}SKU{/ts}: {$sku}
  {/if}
  {if $start_date}
    {ts}Start Date{/ts}: {$start_date|crmDate}
  {/if}
  {if $end_date}
    {ts}End Date{/ts}: {$end_date|crmDate}
  {/if}
  {if $contact_email OR $contact_phone}

    {ts}For information about this premium, contact:{/ts}

    {if $contact_email}
      {$contact_email}
    {/if}
    {if $contact_phone}
      {$contact_phone}
    {/if}
  {/if}
  {if $is_deductible AND $price}

    {ts 1=$price|crmMoney:$currency}The value of this premium is %1. This may affect the amount of the tax deduction you can claim. Consult your tax advisor for more information.{/ts}
  {/if}
{/if}

{if $customPre}
  ===========================================================
  {$customPre_grouptitle}

  ===========================================================
  {foreach from=$customPre item=customValue key=customName}
    {if ( $trackingFields and ! in_array( $customName, $trackingFields ) ) or ! $trackingFields}
      {$customName}: {$customValue}
    {/if}
  {/foreach}
{/if}


{if $customPost}
  ===========================================================
  {$customPost_grouptitle}

  ===========================================================
  {foreach from=$customPost item=customValue key=customName}
  {if ( $trackingFields and ! in_array( $customName, $trackingFields ) ) or ! $trackingFields}
    {$customName}: {$customValue}
  {/if}
  {/foreach}
{/if}
```

**Comment by seamuslee001** [comment]
@demeritcowboy The only way it would make sense to me is if $amount was === 0.00 say so it would fail the bool check but still should be shown on the Receipt but yeh its a bit odd. But that is probably a separate question. Will fix the style problem

**Comment by eileenmcnaughton** [comment]
@demeritcowboy are you saying 'yes this is OK to be  merged but some follow on work makes sense?' -

**Comment by demeritcowboy** [comment]
that sounds ok - eventually yes it should be reconciled with the html version

**Comment by eileenmcnaughton** [comment]
Hmm - not so simple

CRM_Contact_Form_IndividualTest::testOpeningNewIndividualForm
Smarty error: [in CRM/Contact/Form/Contact.tpl line 18]: syntax error: (secure mode) 'call_user_func' not allowed in if statement (Smarty_Compiler.class.php, line 1399)

/home/jenkins/bknix-dfl/build/core-18603-8uesc/web/sites/all/modules/civicrm/packages/Smarty/Smarty.class.php:1100
/home/jenkins/bknix-dfl/build/core-18603-8uesc/web/sites/all/modules/civicrm/packages/Smarty/Smarty.class.php:1860
/home/jenkins/bknix-dfl/build/core-18603-8uesc/web/sites/all/modules/civicrm/packages/Smarty/Smarty_Compiler.class.php:2256
/home/jenkins/bknix-dfl/build/core-18603-8uesc/web/sites/all/modules/civicrm/packages/Smarty/Smarty_Compiler.class.php:1399
/home/jenkins/bknix-dfl/build/core-18603-8uesc/web/sites/all/modules/civicrm/packages/Smarty/Smarty_Compiler.class.php:468
/home/jenkins/bknix-dfl/build/core-18603-8uesc/web/sites/all/modules/civicrm/packages/Smarty/Smarty_Compiler.class.php:307
/home/jenkins/bknix-dfl/build/core-18603-8uesc/web/sites/all/modules/civicrm/packages/Smarty/Smarty.class.php:1499
/home/jenkins/bknix-dfl/build/core-18603-8uesc/web/sites/all/modules/civicrm/packages/Smarty/Smarty.class.php:1432
/home/jenkins/bknix-dfl/build/core-18603-8uesc/web/sites/all/modules/civicrm/packages/Smarty/Smarty.class.php:1912
/home/jenkins/bknix-dfl/build/core-18603-8uesc/web/sites/default/files/civicrm/templates_c/en_US/%%F7/F77/F77C7890%%CMSPrint.tpl.php:64
/home/jenkins/bknix-dfl/build/core-18603-8uesc/web/sites/all/modules/civicrm/packages/Smarty/Smarty.class.php:1914
/home/jenkins/bknix-dfl/build/core-18603-8uesc/web/sites/default/files/civicrm/templates_c/en_US/%%85/854/854F26FC%%unittests.tpl.php:6
/home/jenkins/bknix-dfl/build/core-18603-8uesc/web/sites/all/modules/civicrm/packages/Smarty/Smarty.class.php:1273
/home/jenkins/bknix-dfl/build/core-18603-8uesc/web/sites/all/modules/civicrm/CRM/Core/Smarty.php:183
/home/jenkins/bknix-dfl/build/core-18603-8uesc/web/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Display.php:117
/home/jenkins/bknix-dfl/build/core-18603-8uesc/web/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Display.php:83
/home/jenkins/bknix-dfl/build/core-18603-8uesc/web/sites/all/modules/civicrm/tests/phpunit/CRM/Contact/Form/IndividualTest.php:26
/home/jenkins/bknix-dfl/build/core-18603-8uesc/web/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:226
/home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar:615

**Comment by demeritcowboy** [comment]
That's confusing - none of the fails seem related other than "smarty".

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@demeritcowboy I have i think found the correct if to remove now to fix the tests can you double check?

**Comment by demeritcowboy** [comment]
Ah good sleuthing I see I missed a lone `{if $dataArray}` on a line by its lonesome. I guess I'm still confused about why there were fails for things that have nothing to do with it, but yeah I'll give it another look.

**Comment by demeritcowboy** [comment]
What was the actual error you received? If I do

`php -r "$x = file_get_contents('xml/templates/message_templates/contribution_online_receipt_text.tpl'); preg_match_all('/{if/', $x, $m); echo count($m[0]);"`

it gives 42, and then looking for matching end tags

`php -r "$x = file_get_contents('xml/templates/message_templates/contribution_online_receipt_text.tpl'); preg_match_all('/{\/if/', $x, $m); echo count($m[0]);"`

it also gives 42.

**Comment by seamuslee001** [comment]
@demeritcowboy not sure anymore but this was the error I have recorded 

````
[in string:***********************************************************

{ts}Test-drive Email / Receipt{/ts}

{ts}This is a test-drive email. No live financial transaction has occurred.{/ts}

***********************************************************
{assign var=&quot;greeting&quot; value=&quot;Dear Seamus&quot;}{if $greeting}{$greeting},{/if}
{if $receipt_text}
{$receipt_text}
{/if}
{if $is_pay_later}

===========================================================
{$pay_later_receipt}
===========================================================
{/if}

{if $membership_assign &amp;&amp; !$useForMember}
===========================================================
{ts}Membership Information{/ts}

===========================================================
{ts}Membership Type{/ts}: {$membership_name}
{/if}
{if $mem_end_date}{ts}Membership End Date{/ts}: {$mem_end_date|crmDate}
{/if}

{/if}
{if $amount}
===========================================================
{ts}Membership Fee{/ts}

===========================================================
{if !$useForMember &amp;&amp; $membership_amount &amp;&amp; $is_quick_config}
{ts 1=$membership_name}%1 Membership{/ts}: {$membership_amount|crmMoney}
{if $amount &amp;&amp; !$is_separate_payment }
{ts}Contribution Amount{/ts}: {$amount|crmMoney}
-------------------------------------------
{ts}Total{/ts}: {$amount+$membership_amount|crmMoney}
{/if}
{elseif !$useForMember &amp;&amp; $lineItem and $priceSetID &amp; !$is_quick_config}
{foreach from=$lineItem item=value key=priceset}
---------------------------------------------------------
{capture assign=ts_item}{ts}Item{/ts}{/capture}
{capture assign=ts_qty}{ts}Qty{/ts}{/capture}
{capture assign=ts_each}{ts}Each{/ts}{/capture}
{capture assign=ts_total}{ts}Total{/ts}{/capture}
{$ts_item|string_format:&quot;%-30s&quot;} {$ts_qty|string_format:&quot;%5s&quot;} {$ts_each|string_format:&quot;%10s&quot;} {$ts_total|string_format:&quot;%10s&quot;}
----------------------------------------------------------
{foreach from=$value item=line}
{$line.description|truncate:30:&quot;...&quot;|string_format:&quot;%-30s&quot;} {$line.qty|string_format:&quot;%5s&quot;} {$line.unit_price|crmMoney|string_format:&quot;%10s&quot;} {$line.line_total|crmMoney|string_format:&quot;%10s&quot;}
{/foreach}
{/foreach}

{ts}Total Amount{/ts}: {$amount|crmMoney}
{else}
{if $useForMember &amp;&amp; $lineItem &amp;&amp; !$is_quick_config}
{foreach from=$lineItem item=value key=priceset}
{capture assign=ts_item}{ts}Item{/ts}{/capture}
{capture assign=ts_total}{ts}Fee{/ts}{/capture}
{if $dataArray}
{capture assign=ts_subtotal}{ts}Subtotal{/ts}{/capture}
{capture assign=ts_taxRate}{ts}Tax Rate{/ts}{/capture}
{capture assign=ts_taxAmount}{ts}Tax Amount{/ts}{/capture}
{capture assign=ts_total}{ts}Total{/ts}{/capture}
{/if}
{capture assign=ts_start_date}{ts}Membership Start Date{/ts}{/capture}
{capture assign=ts_end_date}{ts}Membership End Date{/ts}{/capture}
{$ts_item|string_format:&quot;%-30s&quot;} {$ts_total|string_format:&quot;%10s&quot;} {if $dataArray} {$ts_subtotal|string_format:&quot;%10s&quot;} {$ts_taxRate|string_format:&quot;%10s&quot;} {$ts_taxAmount|string_format:&quot;%10s&quot;} {$ts_total|string_format:&quot;%10s&quot;} {/if} {$ts_start_date|string_forma
t:&quot;%20s&quot;} {$ts_end_date|string_format:&quot;%20s&quot;}
--------------------------------------------------------------------------------------------------

{foreach from=$value item=line}
{capture assign=ts_item}{if $line.html_type eq 'Text'}{$line.label}{else}{$line.field_title} - {$line.label}{/if} {if $line.description} {$line.description}{/if}{/capture}{$ts_item|truncate:30:&quot;...&quot;|string_format:&quot;%-30s&quot;} {$line.line_total|crmMoney|string_format:&quot;%10s&quot;}  {if $dataArray}
 {$line.unit_price*$line.qty|crmMoney:$currency|string_format:&quot;%10s&quot;} {if $line.tax_rate != &quot;&quot; || $line.tax_amount != &quot;&quot;}  {$line.tax_rate|string_format:&quot;%.2f&quot;} %  {$line.tax_amount|crmMoney:$currency|string_format:&quot;%10s&quot;} {else}                  {/if}   {$line.line_
total+$line.tax_amount|crmMoney|string_format:&quot;%10s&quot;} {/if} {$line.start_date|string_format:&quot;%20s&quot;} {$line.end_date|string_format:&quot;%20s&quot;}
{/foreach}
{/foreach}

{if $dataArray}
{ts}Amount before Tax{/ts}: {$amount-$totalTaxAmount|crmMoney:$currency}

{foreach from=$dataArray item=value key=priceset}
{if $priceset || $priceset == 0}
{$taxTerm} {$priceset|string_format:&quot;%.2f&quot;}%: {$value|crmMoney:$currency}
{else}
{ts}No{/ts} {$taxTerm}: {$value|crmMoney:$currency}
{/if}
{/foreach}
{/if}
--------------------------------------------------------------------------------------------------
{/if}

{if $totalTaxAmount}
{ts}Total Tax Amount{/ts}: {$totalTaxAmount|crmMoney:$currency}
{/if}

{ts}Amount{/ts}: {$amount|crmMoney} {if $amount_level } - {$amount_level} {/if}
{/if}
{elseif $membership_amount}
===========================================================
{ts}Membership Fee{/ts}

===========================================================
{ts 1=$membership_name}%1 Membership{/ts}: {$membership_amount|crmMoney}
{/if}

{if $receive_date}

{ts}Date{/ts}: {$receive_date|crmDate}
{/if}
{if $is_monetary and $trxn_id}
{ts}Transaction #{/ts}: {$trxn_id}

{/if}
{if $membership_trx_id}
{ts}Membership Transaction #{/ts}: {$membership_trx_id}

{/if}
{if $is_recur}
{ts}This membership will be renewed automatically.{/ts}
{if $cancelSubscriptionUrl}

{ts 1=$cancelSubscriptionUrl}You can cancel the auto-renewal option by visiting this web page: %1.{/ts}

{/if}

{if $updateSubscriptionBillingUrl}

{ts 1=$updateSubscriptionBillingUrl}You can update billing details for this automatically renewed membership by &lt;a href=&quot;%1&quot;&gt;visiting this web page&lt;/a&gt;.{/ts}
{/if}
{/if}

{if $honor_block_is_active }
===========================================================
{$soft_credit_type}
===========================================================
{foreach from=$honoreeProfile item=value key=label}
{$label}: {$value}
{/foreach}

{/if}
{if $pcpBlock}
===========================================================
{ts}Personal Campaign Page{/ts}

===========================================================
{ts}Display In Honor Roll{/ts}: {if $pcp_display_in_roll}{ts}Yes{/ts}{else}{ts}No{/ts}{/if}

{if $pcp_roll_nickname}{ts}Nickname{/ts}: {$pcp_roll_nickname}{/if}

{if $pcp_personal_note}{ts}Personal Note{/ts}: {$pcp_personal_note}{/if}

{/if}
{if $onBehalfProfile}
===========================================================
{ts}On Behalf Of{/ts}

===========================================================
{foreach from=$onBehalfProfile item=onBehalfValue key=onBehalfName}
{$onBehalfName}: {$onBehalfValue}
{/foreach}
{/if}

{if $billingName}
===========================================================
{ts}Billing Name and Address{/ts}

===========================================================
{$billingName}
{$address}

{$email}
{elseif $email}
===========================================================
{ts}Registered Email{/ts}

===========================================================
{$email}
{/if} {* End billingName or email *}
{if $credit_card_type}

===========================================================
{ts}Credit Card Information{/ts}

===========================================================
{$credit_card_type}
{$credit_card_number}
{ts}Expires{/ts}: {$credit_card_exp_date|truncate:7:''|crmDate}
{/if}

{if $selectPremium }
===========================================================
{ts}Premium Information{/ts}

===========================================================
{$product_name}
{if $option}
{ts}Option{/ts}: {$option}
{/if}
{if $sku}
{ts}SKU{/ts}: {$sku}
{/if}
{if $start_date}
{ts}Start Date{/ts}: {$start_date|crmDate}
{/if}
{if $end_date}
{ts}End Date{/ts}: {$end_date|crmDate}
{/if}
{if $contact_email OR $contact_phone}

{ts}For information about this premium, contact:{/ts}

{if $contact_email}
  {$contact_email}
{/if}
{if $contact_phone}
  {$contact_phone}
{/if}
{/if}
{if $is_deductible AND $price}

{ts 1=$price|crmMoney}The value of this premium is %1. This may affect the amount of the tax deduction you can claim. Consult your tax advisor for more information.{/ts}{/if}
{/if}

{if $customPre}
===========================================================
{$customPre_grouptitle}

===========================================================
{foreach from=$customPre item=customValue key=customName}
{if ( $trackingFields and ! in_array( $customName, $trackingFields ) ) or ! $trackingFields}
 {$customName}: {$customValue}
{/if}
{/foreach}
{/if}


{if $customPost}
===========================================================
{$customPost_grouptitle}

===========================================================
{foreach from=$customPost item=customValue key=customName}
{if ( $trackingFields and ! in_array( $customName, $trackingFields ) ) or ! $trackingFields}
 {$customName}: {$customValue}
{/if}
{/foreach}
{/if} line 29]: syntax error: mismatched tag {/if}. expected {/crmScope} (opened line 1). (Smarty_Compiler.class.php, line 2338)

```

**Comment by eileenmcnaughton** [comment]
@seamuslee001 you starting to wish you'd never started on this one?

**Comment by seamuslee001** [comment]
I'm going to close this as clearly this might have been picked up separately but not 100% sure

**Pull request closed without merging**
