### PR TITLE
dev/core#870 priceset hook

### PR DESCRIPTION
**Pull request by sushantpaste**
Overview
----------------------------------------
Currently for price sets pre and post hooks not getting invoked. https://lab.civicrm.org/dev/core/issues/870

Before
----------------------------------------
For price sets pre and post hooks not getting invoked while adding price set or price options etc.

After
----------------------------------------
Price sets pre and post hooks getting invoked while adding price set or price options etc.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Makes sense - I think our preferred syntax is the more concise one seen on Phone BAO

https://github.com/civicrm/civicrm-core/blob/be2fb01f90f5f299dd07402a41fed7c7c7567f00/CRM/Core/BAO/Phone.php#L76

**Comment by yashodha** [comment]
test this please

**Comment by yashodha** [comment]
@sushantpaste Can you please do the needful and squash all commits as well?

**Comment by eileenmcnaughton** [comment]
I just found out we have a docs page for these - https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_post/ - so I guess it will need to be updated off this PR

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by sushantpaste** [comment]
Closing this here is the new updated PR with change https://github.com/civicrm/civicrm-core/pull/15076

**Pull request closed without merging**
