### PR TITLE
Use API4 to get message templates over DAO function

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
Use API to fetch the results instead of DAO so that the results can be altered using hooks

### CODE REVIEW

**Comment by demeritcowboy** [comment]
This works for me the only comment is that it now checks permissions which may cause fails in some situations where before it didn't, but that's maybe not a bad thing.

**Comment by demeritcowboy** [comment]
Also the ordering is slightly different. Now it's case-insensitive, whereas before since it was in php it was case-sensitive.

**Comment by pradpnayak** [comment]
Hi @demeritcowboy 

Thank you for reviewing.

I have added sorting via php now. Can you please review it now?

Thanks
Pradeep

**Comment by demeritcowboy** [comment]
Thanks, it sorts it twice now which is unnecessary but sure why not. Can you squash commits?

**Pull request merged**
