### PR TITLE
Add index to civicrm_contact.created_date & modified_date

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Adds index on civicrm_contact.created_date & modified_date to speed up searches that access those fields

Before
----------------------------------------
Unindexed

After
----------------------------------------
Indexed on new installs or installs that have run the upgrade script

Technical Details
----------------------------------------

Comments
----------------------------------------
Note this will add the indexes to new installs or to installs who run the script to update indexes
(we used to promote this via a status check but there was a bug & we 'hushed' it & stopped trying to fix
the bug)

### CODE REVIEW

**Comment by totten** [comment]
Seems like a sensible change. :+1:

**Comment by MegaphoneJon** [comment]
If I apply this as a patch to 5.17 and run `System.updateindexes` I assume there won't be any repercussions on upgrade to 5.18, because it's not part of the normal upgrade script?

**Comment by eileenmcnaughton** [comment]
That's correct

**Comment by seamuslee001** [comment]
@eileenmcnaughton this now has a conflict can you rebase?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 done

**Comment by seamuslee001** [comment]
Test fail unrelated

**Pull request merged**
