### PR TITLE
[REF] PhpUnit - Update tests to use non-deprecated regex function names

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Test-only cleanup

### CODE REVIEW

**Comment by totten** [comment]
I asked ChatGPT to translate this expression from Perl to PHPUnit:

```perl
die "Bad string" unless $str =~ /pattern/;
```

It returned an essay. The thesis statement was:

```php
$this->assertUpstreamMakingCodeBetterBecause(sizeof((new ReflectionFunction())->getName()), '>', sizeof($laptop->screen));
```

I didn't have the heart to tell it that `sizeof()` isn't really `sizeof()`.

**Comment by colemanw** [comment]
@totten you gotta love the verbosity of PHPUnit. That's why we should get paid per line of code.

What's up with the ext and mixin test failures? Are they using a different version of PHPUnit?

**Comment by totten** [comment]
@colemanw [Yup](https://github.com/civicrm/civicrm-core/pull/27036#issuecomment-1675578450), [here](https://github.com/civicrm/civicrm-buildkit/blob/master/bin/civi-test-run#L23-L32)

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
Closing in favor of https://github.com/civicrm/civicrm-core/pull/27139

**Pull request closed without merging**
