### PR TITLE
[WIP] civicrm_admin_ui Find contacts replacement

### PR DESCRIPTION
**Pull request by samuelsov**
Overview
----------------------------------------
Replacing the Find contacts with Search Kit + Form Builder

Before
----------------------------------------
ksnip_20230530-144659

After
----------------------------------------
ksnip_20230530-145142

Comments
----------------------------------------
The SK could serve as a base for other contact searches after that so it's a good idea to ensure it's as finished as possible.

A few missing features :
-  Alphabetical filter (does any one use this ?)
-  Prev/Next cache navigation
-  No way to add a conditional caption (e.g. for Do not email / Do not phone)
-  Not a lot of icons or ability to combine icons (e.g. for Do not email / Do not phone)

Some things that needs some thoughts :
-  Most searches are auto search which is fine for small list but I don't know if it should be the case here for a full database search. However, a user might wonder why it doesn't show any results when we open the page. Shouldn't we hide the result table until the Search button is pressed to make it clearer ?
-  Is there a way to share the display between multiple searches to avoid duplicating the code later on ?

### CODE REVIEW

**Comment by colemanw** [comment]
Overall, this is a great step forward!
Obviously there are a few details to think about. Here's one:
image

That feels a bit silly. Probably the buttons should either all be in the menu or all be out of the menu. Since the # of buttons is likely to grow, I'd vote for all-in.

**Comment by larssandergreen** [comment]
Agreed that it would be great to have this as finished as possible. I've collected some thoughts here. 

Alphabetical filter: Agreed that this can go (reminds me of a Rolodex).

Search fields: Feels like there is a lot of unused horizontal space here that we could use instead of stacking the fields.

Buttons: I think it would make it more obvious how to use the form if we separate the Search button from the Action, so it is more clear that Search goes with the fields above and Action with the results. Also could use a little space between the count and the Action button.

Row height: Information density is a lot lower here, because of the height of the hamburger menu. Would be nice if we could fit more rows on the screen. The default hamburger menu in SK works better than this one, I think. Agree with @colemanw that it would be best to put all the links in the one menu (view is already covered with the display name, edit is kind of covered there too since edit in place on a contact is a lot more usable than the actual edit form).

Action menu: As we add more actions, this will become increasingly hard to use if it isn't a Select2 that you can start typing in.

Icons: Agreed these are needed. The red cell background is too strong of a visual element for what it means (feels like I should be correcting something).

Top pager: I think this is useful to have, sometimes you want to skip straight to a certain page. I think we need a more minimal pager for the top of the page, maybe all on the right.

Number of rows per page: Would be nice to be able to adjust this here.

Bottom pager: Not quite centered. There's something funky going on with the elements which I think are supposed to be hidden to the right of it, but are actually taking up space.

Name or Email: Too bad to lose the ability to search both at once.

Contact icon: Would be better in a separate column, as is this looks weird if the name breaks onto two lines.

, Contact Type / subtype

**Comment by larssandergreen** [comment]
Great to see more core forms going this way! Agreed that it would be great to have this as finished as possible. I've collected some thoughts here (and have added a couple simple PRs to address some UI elements already). Some of this may be more general thoughts on SK UI than on this specific implementation.

Alphabetical filter: Agreed that this can go (reminds me of a Rolodex).

Search fields: Feels like there is a lot of unused horizontal space here that we could use instead of stacking the fields.

Row height: Information density is a lot lower here, because of the height of the hamburger menu making each row taller than it needs to be. Would be nice if we could fit more rows on the screen. The default hamburger menu in SK works better than this one, I think. Agree with @colemanw that it would be best to put all the links in the one menu (view is already covered with the display name, edit is kind of covered there too since edit in place on a contact is a lot more usable than the actual edit form). I have noticed the Admin UI buttons have been kind of all over the place in terms of sizes and colours, is there an opportunity to simplify these and make them all the same size (smaller)?

Menu items: It's a bit unnecessary to have View Contact, Delete Contact, etc when we are only dealing with one entity on the table (which I think is going to be the case for most places SK will replace tables in core). I could add a PR to not include the entity name when there is only one entity in play, if that makes sense. If we're doing links, I don't think the icons are worth the extra space they take up.

Icons for Do not call, etc: Agreed that these are needed. The red cell background is too strong of a visual element for what it means (feels like I should be correcting something).

Name or Email: Too bad to lose the ability to search both in one field. Is there any way to do that with SK? Could we add that? If not, we definitely want the email field here at a minimum.

Contact Types / Sub types: Similarly would be nice to be able to combine these in one field as they are currently.

Buttons: I think it would make it more obvious how to use the form if we separate the Search button from the Action button, so it is more clear that Search goes with the fields above and Action with the results. Perhaps on separate lines? Also could use a little space between the Action button and the count after it.

Action menu: As we add more actions, this will become increasingly hard to use if it isn't a Select2 that you can start typing in to find your item quickly.

Top pager: I think this is useful to have, sometimes you want to skip straight to a certain page. I think we need a more minimal pager for the top of the page, maybe all on the right.

Number of rows per page: Would be nice to be able to adjust this at the bottom of the page.

Contact icon: Would be better in a separate column, as is this looks weird if the name breaks onto two lines.

Select text: The current text (Any Tag, Any Contact Type) is more useful than just Select because it makes clear to the user what not selecting anything means.

Maybe we could lose the Country column to reduce the amount of breaking onto two lines that goes on. I suspect most users are looking at contacts from one country or maybe a couple, in which case Postal Code and State are enough to differentiate.
 
Anyways, those are some thoughts. I think we should try to keep what works in the current forms as much as possible.

**Comment by samuelsov** [comment]
@larssandergreen agreeing with all points except this:

> Maybe we could lose the Country column to reduce the amount of breaking onto two lines that goes on. I suspect most users are looking at contacts from one country or maybe a couple, in which case Postal Code and State are enough to differentiate.

This really depends on the type of organization or the region it operates. Sometimes State is meaningless while Country is vital. I don't think we should change the current behavior. The good news is it should be easier to customize on a site by site basis.

**Comment by colemanw** [comment]
Thanks @samuelsov and @larssandergreen - some of those items have/can already be addressed:

- ~ABC filter~ (good riddance)
- Inline search fields - form-builder can do this
- Combined name/email search - yes form-builder can do this
- Menu labels - I feel like the defaults of "View Contact" etc. are fine. They don't waste any space if they're tucked inside a menu.
- Icons for do-not-call etc - how about changing the icon to `fa-ban`
- Number of rows per page: yes you can make this configurable on the search display
- Contact icon - I'm not sure it needs to be a separate column, but if we do it ought to have a blank label for that column header to keep the width minimal
- Contact type/subtype combined widget - sorry that's not yet possible
- Button cleanup - I've opened #26394
- Pager position - fixed with https://github.com/civicrm/civicrm-core/pull/26389

**Comment by samuelsov** [comment]
Working on a new iteration, a bit better but I can't:
- do inline label and I'm not fan of the no label / placeholder only approach
- combined name/email search - it might be too recent for the dev site I'm using based on https://github.com/civicrm/civicrm-wordpress
- hide no email/phone icon if not email/phone (no way to add multiple condition? e.g. if email not empty and do no email)

ksnip_20230602-171112

**Comment by aydun** [comment]
@samuelsov For inline filters, from the Elements list, drag a Container just above the search table then drag the filters into the container.  Use the Container's settings icon (top right) to select the Inline layout.

For the combined search, I don't think you can do that directly from FormBuilder, so create a filter for display name and then use the optional Form Code Editor to edit the markup directly to change it to `<af-field name="display_name,email_primary.email">`

**Comment by samuelsov** [comment]
> @samuelsov For inline filters, from the Elements list, drag a Container just above the search table then drag the filters into the container. Use the Container's settings icon (top right) to select the Inline layout.

This is what I do but I guess I'm just not sure of what you guys want. Am I correct to assume that you prefer having all 5 filters in one row like that:

ksnip_20230605-091606

> For the combined search, I don't think you can do that directly from FormBuilder, so create a filter for display name and then use the optional Form Code Editor to edit the markup directly to change it to `<af-field name="display_name,email_primary.email">`

This is what I did in the PR but it doesn't work on my dev site. I will do some more test after upgrading to latest master.

**Comment by colemanw** [comment]
This is shaping up nicely!
[Per our chat](https://chat.civicrm.org/civicrm/pl/p8xttsgwdjnntg7139qtaeed3h), my vote is to remove the Search button in favor of auto-search.

**Comment by colemanw** [comment]
I agree, this looks great!
There are a few untranslated strings in the Afform, I'm pretty sure wrapping them in `{{:: ts() }}` will work (but if not, it's not a blocker we can iterate on translations later).

**Comment by samuelsov** [comment]
> I agree, this looks great! There are a few untranslated strings in the Afform, I'm pretty sure wrapping them in `{{:: ts() }}` will work (but if not, it's not a blocker we can iterate on translations later).

I tried but I was not able to make it work in defn params. Happy to try again if you have an example but could go in another PR as well.

**Comment by colemanw** [comment]
@samuelsov tests are passing! Let's get it rebased & merged :)

**Comment by samuelsov** [comment]
@colemanw ok, it's done, one clean commit :)

**Comment by colemanw** [comment]
Beautiful

**Comment by larssandergreen** [comment]
Looks a lot better. [Noticed an issue](https://lab.civicrm.org/dev/core/-/issues/4360) with the redirects though.

**Comment by larssandergreen** [comment]
Added [another issue](https://lab.civicrm.org/dev/core/-/issues/4384), seems like Advanced Search is not accessible as well.

**Comment by larssandergreen** [comment]
One [more issue](https://lab.civicrm.org/dev/core/-/issues/4396), missing the ability to search in standard "LastName, First Name" format.

**Pull request merged**
