### PR TITLE
Better handle Case Manager and roles on closed cases

### PR DESCRIPTION
**Pull request by ray-wright**
Overview
----------------------------------------
In Civi 4.7 case roles were refactored via #6806 which added a query to only load active relationship from getCaseRole function. This is problematic for closed cases - since theoretically, they should only contain inactive relationships. I'm proposing removing a better way to handle inactive roles rather than just not showing them.

Before
----------------------------------------
On closed cases, the case manager did not display on case listings or inside the manage screen. In addition, roles other than the case manager also appear blank on closed cases. (This is because they are inactive, i.e. end date in the past and disabled.)
nocasemanager
nocasemanager2

After
----------------------------------------
On case listings:
- Default to the active case manager, if no active case manager found, show the name of the most recently expired case manager. 

On the manage case screen:
- Show ALL roles whether or not they are inactive.
- Add a column for end date and gray out inactive roles for visual clarity.
- Add a checkbox for 'show inactive relationships'
 -- Check by default on closed cases (and show inactive relationships)
 -- Uncheck by default on open cases (and hide inactive relationships)

propercasemanager
propercasemanager2
propercasemanager3

Comments
----------------------------------------
This is the first improvement I've suggested that affects multiple areas, please feel free to clean up or suggest more efficient methods! (FYI, I do still need a little a little help in the Activity>Page>Ajax.php file.)

### CODE REVIEW

**Comment by aydun** [comment]
test this please

**Comment by ray-wright** [comment]
I believe this will replace the earlier work started here https://github.com/civicrm/civicrm-core/pull/13144. @jitendrapurohit please feel free to weigh in.

**Comment by ray-wright** [comment]
One current caveat is that the start and end dates for a relationship are only dates, rather that date times. So if two relationships share an end date, there's no way to tell which one is the most recently 'expired' relationship. Would it be problematic to change the relationship start_date and end_date in the xml schema from date to datetime? If it is not, can anyone help me change that and generate the Contact>Relationship>DAO file?

**Comment by colemanw** [comment]
@jitendrapurohit could you please review this?

**Comment by colemanw** [comment]
See proposal at https://lab.civicrm.org/dev/core/issues/542

**Pull request closed without merging**
