### PR TITLE
CRM-20927 -  Allow `civicrm_menu` to store new data in generic column

### PR DESCRIPTION
**Pull request by totten**
Background
==========

To fix CRM-20924 and CRM-20926, we need a place to store per-page
information about the IDS configuration.

More generally, as we continue adding features through extensions, we should
anticipate that the route metadata will expand in ways that we can't
anticipate.  Adding a general-purpose serialized field will help us define
new behaviors through extensions.

Before
======

All metadata in the routing table (`civicrm_menu`) had to stored in a
separate SQL column.

After
=====

Any unrecognized fields will be stored and loaded from the column
`module_data`.

Acceptance Criteria
===================
 * New data can be stored in `civicrm_menu`.
 * Unit-test verifies above.
 * Navigation menu continues to work in UI.
 * The "Administer" screen (which has special menu-handling) continues to work in UI.

---

 * [CRM-20927:  Allow `civicrm_menu` to store new data in generic column](https://issues.civicrm.org/jira/browse/CRM-20927)
 * [CRM-20924: Creating a new activity fails for demo user](https://issues.civicrm.org/jira/browse/CRM-20924)
 * [CRM-20926: Allow extensions to flag PHPIDS html\/json fields](https://issues.civicrm.org/jira/browse/CRM-20926)

### CODE REVIEW

**Comment by totten** [comment]
jenkins, test this please

**Comment by totten** [comment]
jenkins, test this please

**Comment by totten** [comment]
@agh1 I'm not sure how this will play out on the release notes --  this PR was merged implicitly (by virtue of merging a bigger PR, 10709). Depending on how the reporting works (eg querying Github REST API vs querying `git` for merge-commits vs querying `git` for `CRM-XXXX` references), it may or may not show up.

**Comment by agh1** [comment]
@totten thanks for the heads-up.  I query the git log for commit messages saying "merge pull request..." and then scrape for the first thing anything beginning `CRM-` followed by digits.  That means CRM-20927 will get lost because #10709 specifies CRM-20926.

**Comment by agh1** [comment]
I scan through PR intros manually, so your mention of this PR in the intro over there is perfect.

**Pull request merged**
