### PR TITLE
Added conditional check so that it can be altered by hook

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
Added conditional check for printing blocks so that it can be easily altered by hooks if we need to hide certain blocks from printing.

@demeritcowboy

### CODE REVIEW

**Comment by demeritcowboy** [comment]
* General standards
    * [`r-explain`] __Mostly PASS__
      * It could mention that hook_civicrm_alterTemplateFile doesn't get called for this Report.tpl here, so you can't use that. You _can_ customize CaseView.tpl though if you wanted to replace the Print Report link to use your own custom link. So two other approaches here then would be to make it either call hook_alterTemplateFile or make it easier to alter the print report link, but they might be more work.
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __PASS__
* Developer standards
    * [`r-tech`] __PASS__
      * A more general approach to customizing might be better long-term, but this change doesn't prevent that.
    * [`r-code`] __PASS__
      * It's mostly indentation changes. It's just adding in `if` statements that are similar to some that are already in the file for other sections.
    * [`r-maint`] __PASS__
    * [`r-test`] __PASS__

**Comment by pradpnayak** [comment]
@demeritcowboy Yes i agree, ATM no Page/Form hooks are invoked to alter the smarty variables. But for now i am using casetypes() and/or optionValues() hooks to alter the smarty variables. But i am thinking to add support for hook_civicrm_alterContent ().

**Comment by yashodha** [comment]
@demeritcowboy ready to merge or do you expect few changes in documentation etc?

**Comment by demeritcowboy** [comment]
No there's nothing new to document. Seems fine to me.

**Comment by yashodha** [comment]
@demeritcowboy ok, merging this PR as per your review.

**Pull request merged**
