### PR TITLE
Contact/BAO/Query.php: minor fix

### PR DESCRIPTION
**Pull request by nirodaonline**
Overview
----------------------------------------
When looking for spaces, the condition was never true.

Before
----------------------------------------
The condition always failed.

After
----------------------------------------
The condition is now applied.

### CODE REVIEW

**Comment by colemanw** [comment]
@civicrm-builder add to whitelist

**Comment by colemanw** [comment]
@nirodaonline thanks for the fix! It would also be great to have a unit test for this.

**Comment by seamuslee001** [comment]
I think this test failure may relate

```
api_v3_ContactTest::testContactGetSpaceMatches
Failed asserting that 2 matches expected 1.
```

**Comment by nirodaonline** [comment]
@colemanw will try to create one this week.

**Comment by nirodaonline** [comment]
Don't know how to fix the warnings. 
Can't find those white lines.

**Comment by colemanw** [comment]
image

@nirodaonline this means that there is one or more space at the end of these two lines, e.g. after the semicolon.

**Comment by nirodaonline** [comment]
Doh!
I though it referred to empty lines.
Thanks.

**Comment by colemanw** [comment]
I've rebased and squashed this to remove the superfluous merge-commits and cleanup commits. #22240

**Pull request closed without merging**
