### PR TITLE
dev/core#5384 Fix advanced search of activities for deleted contacts

### PR DESCRIPTION
**Pull request by spalmstr**
Overview
----------------------------------------

See [Advanced Search searching in trash by Activity Type yields no results](https://lab.civicrm.org/dev/core/-/issues/5384)

Before
----------------------------------------
In Advanced Search, when searching for an activity type for contacts in Trash, the search never returned any contact.

After
----------------------------------------
Advanced Search now returns contacts with the given activity type.

Technical Details
----------------------------------------
`.../civicrm-core/CRM/Activity/BAO/Query.php` only found activities for contacts not in Trash. This has been changed so if you are searching for contacts in Trash it can find those contacts. 
`.../civicrm-core/CRM/Contact/BAO/Query.php` has been changed so it passes on that you are searching in Trash to the Activity search.
The $onlyDeleted variable may also be useful for other similar queries.

Comments
----------------------------------------
I am hoping it makes no other difference.

### CODE REVIEW

**Comment by spalmstr** [comment]
`CRM/Group/Form/Edit.php` is a hangover from another outstanding PR.

**Comment by mlutfy** [comment]
@spalmstr Personally, I would be comfortable getting this merged. I guess we are all worried about regressions, because the code is a mess, but the changes seem cautious.

Can you:

- Provide clearer steps to replicate the problem? Ex: create an activity of type "meeting" for a contact, then delete the contact, adv-search for the contact in trash?
- Can you remove the change for `CRM/Group/Form/Edit.php`? I'm not sure I agree for that change (the administrative title should be displayed when doing an administrative operation?)

**Comment by spalmstr** [comment]
Basically, if a contact has Activities, you can't them if the contact has been deleted and you are searching in Trash.

Edit.php was part of another PR and got included here in error. If that change is included, it means that when you are deleting a grouip, it tells you which group was deleted rather than just a form title.

**Comment by demeritcowboy** [comment]
I gave it a little run and no obvious problems came up 👍

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by mlutfy** [comment]
Thank you @spalmstr @demeritcowboy !

**Pull request merged**
