### PR TITLE
Order the getContactIDsFromComponent query results 

### PR DESCRIPTION
**Pull request by ray-wright**
Print Merge document from case search doesn't file on correct contact.

Overview
----------------------------------------
With Record generated letters set to "Multiple activities (one per contact)" when you print/merge documents directly on a case, they don't file on the correct contact. Full issue here: https://lab.civicrm.org/dev/core/issues/893

Before
----------------------------------------
When selecting the following cases/contacts in this order (custom sort order on the results page)
- Case Number 103, Contact 560 (Linda)
- Case Number 112, Contact 579 (Victor)
- Case Number 116, Contact 622 (Henry)

Activities are filed in this order
- 560 (Linda) - filed correctly on case 103
- 622 (Henry) - filed INCORRECTLY on case 112 (that case belongs to Victor)
- 579 (Victor) - filed INCORRECTLY on case 116 (that case belongs to Henry)

Rather than the list of contact IDs respecting the sort order, they are in case order.

After
----------------------------------------
When selecting the following cases/contacts in this order (custom sort order on the results page)
- Case Number 103, Contact 560
- Case Number 112, Contact 579
- Case Number 116, Contact 622

Activities are filed in this order
- 560 - filed correctly on case 103
- 579 - filed correctly on case 112
- 622 - filed correctly on case 116

Comments
----------------------------------------
I did run contact level searches and pdf filing and that was not affected/ran as expected. But I'm not sure if there are other places I should test for 'fallout'.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Thanks for doing this. Overall it does seem to fix the issue. Just the function is used in many form tasks across many components so more opinions are needed.

This seems like a lot of comments but except for `r-tech` it's minor stuff.

* General standards
    * [`r-explain`] __PASS__
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __PASS__
      * I'm able to reproduce the problem and the patch does seem to fix it.
      * I get a warning when I leave the pdf download page but I also see it on dmaster.demo so it's not because of this PR.
        * `Notice: Undefined variable: isLiveMode in CRM_Contact_Form_Task_PDFLetterCommon::postProcess() (line 183 of /home/jenkins/bknix-dfl/build/core-15364-8rvor/web/sites/all/modules/civicrm/CRM/Contact/Form/Task/PDFLetterCommon.php).`
* Developer standards
    * [`r-tech`] __Undecided__
      * Some more opinions needed. I took a look to see why this problem doesn't seem to be there for, e.g. contributions or participants, which look like they use the same pattern. Maybe part of the reason is that contact-case is a many-to-many relationship modeled with an intermediate table, whereas contact-contribution is a one-to-many relationship (i.e. a contribution only has one associated contact: contact_id is part of the contribution table). So there's an extra factor. Participants technically have a many-to-many relationship, but it seems to be used differently, at least for the form tasks here, e.g. it doesn't try to look up the event_id in the call to getContactIDsFromComponent, and you don't have access to the event fields as tokens for the pdf, whereas it does lookup case_id and offers the tokens for case.
      * I didn't load-test but does the ORDER BY affect performance for large numbers? This looks maybe used by export too? But passing in 100,000 ids to begin with maybe isn't realistic in the first place.
    * [`r-code`] __Somewhere between ISSUE and PASS__
      * I might add a code comment just above `$order_array .= $idField . ' = ' . $item . ' DESC,';` explaining just a little. It's not that common to see order by with expressions, and the DESC is confusing until you go look at the documentation.
      * The common idiom throughout civi to create a comma-separated string is to loop thru and build an array, then implode at the end. So if this were elsewhere in civi you'd probably see it written like this:
        ```
        $order_array = [];
        foreach ($componentIDs as $item) {
          $order_array[] = $idField . ' = ' . $item . ' DESC';
        }
        $order_array = 'ORDER BY ' . implode(',', $order_array);
        ```
      * And strictly speaking you'd want to escape $idField. Backticks in mysql. I'm not sure if there is an existing function for this. There must be I just don't see it.
        * The existing code should also be escaping it. It doesn't come up because it's always something like `contact_id`, but it should be escaped.
      * Technically `$item` too, as a regular string escape: `CRM_Core_DAO::escapeString($item)`. It's always integers but technically should be escaped.
      * And there's one more git task. Commits that fix styling should be "squashed". See https://docs.civicrm.org/dev/en/latest/tools/git/#rebasing-interactive.
    * [`r-maint`] __Undecided__
    * [`r-test`] __PASS__

**Comment by ray-wright** [comment]
Thank you for the detailed explanation, it is very helpful to me. While I've been around Civi for a bit I don't do a whole lot of work at the core level.

I absolutely get that this is used in a lot of places so could have other reaching, undesirable, effects so thanks for working with me to see if it would be a fix. 

When I was diagnosing I could see that the $form array (from the PDFLetterCommon file) had _contactIds in the wrong order compared to all the other arrays (civicrm_case.id, _componentIds, _entityIds). So I did google-ing to figure out how to order array results by another array. I'll work through your code comments to better meet standards, may take me a day or so.

**Comment by demeritcowboy** [comment]
Just thinking out loud for a moment, there's some OO programming going on here to allow overrides when things are different, but then they call a static function that takes a parameter whose value is specific to the subclass, not completely defeating OO but not taking advantage of it either. If the getContactIdsFromComponent function were not static and were part of CRM_Core_Form_Task, you could replace the parameters inside the function with `$this->getComponentIds()` and `$this->getTableName()` and `$this->getIdField()`, and then also introduce `$this->getOrderBy()`, which in the base class would return null or the empty string, and in CRM_Case_Form_Task would return your ORDER BY.

Then also you're not touching the query for any of the other components.

**Comment by mattwire** [comment]
@demeritcowboy @ray-wright For a bit of background, `CRM_Core_Form_Task` was introduced by me (with help from @eileenmcnaughton) a while ago in an effort to reduce duplication on what was previously duplicated for nearly any entity!  So there is definitely scope for further improvements and what @demeritcowboy is suggesting sounds good in principal!

**Comment by ray-wright** [comment]
We may be getting just over my level of knowledge/confidence. I get where you're going (and it does sound good in principle) I'm a little worried about my ability to execute it. If someone has time to discuss in more detail (via chat or something) that might bode better for success.

**Comment by demeritcowboy** [comment]
Fair enough - I'll DM you in chat.

**Comment by ray-wright** [comment]
@demeritcowboy I just added the changes to both the CRM_Core_Form_Task and the CRM_Case_Form_Task files. I was unsure if I should leave the old getContactIdsFromComponent function in the CRM_Core_Dao file. I did remove it but I now am failing checks. Not sure if it was wise to pull the old function???

**Comment by demeritcowboy** [comment]
I'll chat you in chat. The fail at the moment is about file conflicts.

**Pull request closed without merging**
