### PR TITLE
CRM-17328 - Fix dashlet/report ID mappings

### PR DESCRIPTION
**Pull request by totten**
civibuild has been failing to configure the dashboard because some ID's are
invalid, and some ID's are no longer pointing to the originally prescribed
reports.

---
- [CRM-17328: Almost all 'sample' dashlet reports are broken](https://issues.civicrm.org/jira/browse/CRM-17328)

### CODE REVIEW

**Comment by totten** [comment]
#6949 (master) and #6950 (4.6) are conceptually the same, but the numbers and details are different in each.

**Comment by colemanw** [comment]
What happens when 4.6 gets merged into master?

**Comment by totten** [comment]
A merge conflict. Don't think there's a way to handle this beautifully.

**Comment by colemanw** [comment]
Ok - it'd be great if you can do the merge.

**Comment by kurund** [comment]
@totten since we have separate PR for master, do we need to merge forward?

**Comment by totten** [comment]
Not really -- If there's a way to skip merging for a specific commit/PR, then that would be great. But at the end of the day the tpl's in both branches do need to change (with diff numbers).

**Comment by kurund** [comment]
@totten @colemanw I will handle this during my next merge forward :)

**Pull request merged**
