### PR TITLE
CRM-18563 API or permissions

### PR DESCRIPTION
**Pull request by mollux**
- [CRM-18563: Issues with the API and testing the API](https://issues.civicrm.org/jira/browse/CRM-18563)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by JoeMurray** [comment]
@mollux thanks for all your contributions to core! As Release Manager this month, I'm trying to recruit people to help pare down the backlog of almost 100 PRs, some going back to last summer. I'm wondering if you would be able to help QA another PR if I got someone to QA yours (you have about a half-dozen)?

**Comment by JoeMurray** [comment]
@johanv would you be interested in reviewing this PR?

**Comment by johanv** [comment]
@JoeMurray OK, I'll have a look.

**Comment by johanv** [comment]
At first it was not very clear to me what problem this PR was fixing, so I will describe it
in more detail, for the record.

It fixes a bug in exception messages. How to reproduce:

* Create a user that has 'Access CiviCRM' permissions, but no 'access my cases and activities' 
  and 'access all cases and activities' permissions.
* Log on with that user, and surf to civicrm/api to get the API explorer.
* Choose 'Case' as entity, and 'get' as action.
* Click 'Execute'.

You get this error message:

    {
        "error_code": "unauthorized",
        "entity": "Case",
        "action": "get",
        "is_error": 1,
        "error_message": "API permission check failed for Case/get call; insufficient permission: require Array"
    }

When you do the same after having applied the patch, you get

    {
        "error_code": "unauthorized",
        "entity": "Case",
        "action": "get",
        "is_error": 1,
        "error_message": "API permission check failed for Case/get call; insufficient permission: require ( access my cases and activities or access all cases and activities )"
    }

which is better.

So:

- The issue is valid.
- The fix works.
- It is safe from a security point of view (it just displays correct error messages instead of nonsense).
- I don't think this will have performance implications.
- Nobody will like the original behaviour better than the new one.
- A unit test would have been nice ;-)
- The way the error message is constructed, is a little clumsy. But it was clumsy before. I guess
  this is another issue (there was already a FIXME in the original code).

So as I see it, this is ready to be merged.

**Comment by JoeMurray** [comment]
@johanv Very nice review. @yashodha please merge.

**Comment by eileenmcnaughton** [comment]
OK - from a code readability pov re-using the $permissions var to be a text description when it was previously a permissions array is not that cool. But, as you point out it is not a new thing.

Merging. Both of you are legends!

**Pull request merged**
