### PR TITLE
dev/core#2569 Add in Redirect field into the html afform editor

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This adds the recently added redirect field to the html editor as well as the GUI editor in afform

Before
----------------------------------------
redirect field only found on the GUI editor

After
----------------------------------------
redirect field found on html and gui editor

ping @colemanw @eileenmcnaughton

### CODE REVIEW

**Comment by colemanw** [comment]
@seamuslee001 the markup in this form seems to have diverged from the one in `afform_admin` - they do the same thing, so why not just copy the other into this one.
IMO the two extensions should be merged, but for now, copying and pasting that form to this one would suffice.

**Comment by seamuslee001** [comment]
@colemanw I was nervous about touching the markup to that extent given that the afform_admin I think does more than that but meh will give it a short

**Comment by seamuslee001** [comment]
@colemanw I started to do that work last night but ran into a problems

1. the afform_html editor is just an afform and doesn't have access to the gui's controllers
2.  I was getting select2 for the permission selector https://github.com/civicrm/civicrm-core/blob/master/ext/afform/admin/ang/afGuiEditor/config-form.html#L24, I suspect this is because editor.meta.permissions doesn't exist with the html editor
3. This toggleContactSUmmary function is only in the editor and wasn't sure which afform angular module i should move it to if I should https://github.com/civicrm/civicrm-core/blob/master/ext/afform/admin/ang/afGuiEditor/config-form.html#L65

**Comment by colemanw** [comment]
I'll merge this but I really don't think this extension should exist. Based on your comment @seamuslee001 there are more missing config fields other than `redirect` and it will cause config data loss when saving an afform with this extension.

IMO this should be merged with `afform_admin` asap. I'm picturing the HTML tab in `afform_admin` with a write mode. But there's some work to do modifying or disabling the drag-n-drop from the palette since those can't be dragged into markup.

**Pull request merged**
