### PR TITLE
Fix Drupal8 CiviCRM menu translation on multilingual (and ajax calls)

### PR DESCRIPTION
**Pull request by mlutfy**
Overview
----------------------------------------

Using Drupal8 on a multilingual site using "inherit locale", the menu often does not display in the correct language.

To reproduce:

* Enable Drupal locale, and add a second language, use language prefix as the language detection method.
* Enable multilingual in CiviCRM, add a second language, enable "inherit CMS language".

It will help to clear the localStorage regularly while testing this, because the menu gets cached. So get ready to do `localStorage.clear(); ` after each request (F12 -> Console). 

The first problem is that the menu is loaded with `/civicrm/ajax/navmenu`, instead of, `/fr/civicrm/ajax/navmenu`. Sure, the request passes a `language=fr_CA` argument, but when using the "inheritLanguage" setting, this language argument is ignored.

Sure, we can patch that code, but this missing prefix causes other issues (more on that later), and the code is already pretty messy.

So anyway, the menu is not loading correctly because of the `civicrm-placeholder-url-path`. Drupal8 only adds the language prefix when the path has a route:

## Before the patch

```
Path: civicrm-placeholder-url-path
Base: internal:/
Result: /civicrm-placeholder-url-path?civicrm-placeholder-url-query=1
```

## After the patch :cake:

```
Path: civicrm/placeholder-url-path <- slashed
Base: internal:/
Result: /fr/civicrm/placeholder-url-path?civicrm-placeholder-url-query=1  <- language prefix
```

## Other bugfix

This also resolves any URL generated with `CRM.url()`.

Technical Details
----------------------------------------

The above debug was added to `CRM_Utils_System_Drupal8::url()`.

Comments
----------------------------------------

Why don't crabs give to charity? Because they're shellfish. :drum:

### CODE REVIEW

**Comment by mattwire** [comment]
Looks simple.. we probably need to see this working on drupal7 / wordpress to make sure it doesn't create any regressions there.

**Comment by colemanw** [comment]
I tested this on Wordpress and ran into a bug. The url gets encoded as something like `/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fplaceholder-url-path` (with a url-escaped slash between `civicrm` and `placeholder-url-path`) which means the string replace failed. I've pushed up a fix which correctly escapes slashes in the final output too.

**Comment by colemanw** [comment]
Tested on D7 & works fine.

**Comment by mlutfy** [comment]
@colemanw Nice catch, thank you!

**Pull request merged**
