### PR TITLE
CRM-20228 - CiviMail - Use CRLF instead of LF as EOL for long message…

### PR DESCRIPTION
**Pull request by tschuettler**
… headers

https://issues.civicrm.org/jira/browse/CRM-20228

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@xurizaemon you seem to have your head around this - is it ok to merge?

**Comment by totten** [comment]
Firstly - thanks @tschuettler, esp for pointing out the RFC!

My impression from @xurizaemon's comment in JIRA (pointing to [this doc](https://pear.php.net/manual/en/package.mail.mail-mime.mail-mime.php)) is that this fix is incompatible with PEAR Mail, which means we can't merge it (based on current code+knowledge). There are a couple ways to address this:

 * Research+luck. Figure out *why* upstream wants `\n`. Figure out an alternative.
 * Replace PEAR Mail through a core patch. Do broad upfront QA to ensure that all the various email-composition/delivery scenarios work.
 * Replace PEAR Mail through an extension. Let a few bleeding-edge types use the extension.

If it were me, I'd go for replacing PEAR Mail via extension. ezcMail and SwiftMailer look like better libraries. And now-a-days it is possible to replace it through an extension. For example, suppose we wanted to use SwiftMailer:

 * Activate https://github.com/civicrm/org.civicrm.flexmailer
 * Create a new extension `civix generate:module org.civicrm.swiftmailer`
 * Get the code for SwiftMailer and put it in the extension.
 * Write a listener for [`SendBatchEvent`](https://github.com/civicrm/org.civicrm.flexmailer#events-sendbatchevent). You can loop through `$event->getTasks()` and get the [`mailParams`]("https://github.com/civicrm/civicrm-core/blob/4.7.17/CRM/Utils/Hook.php#L1028). Then you can pass it through to SwiftMailer.

Random other thoughts:
 * ezcMail is already bundled with Civi, so that might be a little easier. But I don't feel it's documented/maintained quite as well as SwiftMailer. Either one seems equally legit to me.
 * If you really don't want a new/second extension, it's patch-welcome for flexmailer to use ezcMail/SwiftMailer. Requirements/review might be a little tougher, but then it wouldn't be a separate extension. Just send a PR to rewrite https://github.com/civicrm/org.civicrm.flexmailer/blob/master/src/Listener/DefaultSender.php

**Comment by eileenmcnaughton** [comment]
I think we should close this & transfer conversation to the JIRA. I don't think it is likely to lead to a merge based on the above & we should close the PR to declutter the PR queue, while not losing the analysis & discussion. (it would be ideal not to lose the momentum either but I guess the lack of an easy fix might do for that)

I'm going to close this, on the basis PRs can always be re-opened if I have been premature

**Comment by eileenmcnaughton** [comment]
@totten My feeling now is that we are inching towards a better solution on mail & we should close this since we never resolved it to be 'safe enough'

**Comment by eileenmcnaughton** [comment]
closing as no update from suggestion I should a few months back

**Pull request closed without merging**
