### PR TITLE
dev/core#942 fix failure to render names for some activities

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Set limit for activity_contact retrieval to 0, allowing to retrieve more than 25 activity contacts when rendering the first 25 activities on the activity contact tab

Before
----------------------------------------
before

After
----------------------------------------
after

Technical Details
----------------------------------------
This moves the logic for retrieving the target contacts back into the getActivities function. We are stil not wanting to bypass the ACLs so still using the
api but strictly limiting the number of contacts we retrieve (at the cost of extra queries, but cheap ones).

Some tests added on the Bulk Mail activity.

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton need name fix here

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
I've cherry-picked my test fix from https://github.com/civicrm/civicrm-core/pull/14236 to this ping @totten

**Comment by seamuslee001** [comment]
@eileenmcnaughton do you want to rebase this to squish the extra commits?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 would do but have to take R to get stitched up - cut finger - can you - or just merge

**Comment by seamuslee001** [comment]
I'm going to merge based on Eileen's comment

**Pull request merged**
