### PR TITLE
CRM-15785 make case_type_id required in schema

### PR DESCRIPTION
**Pull request by eileenmcnaughton**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Tim assigned to you in case you can see a reason not to do this

**Comment by totten** [comment]
The PR should also define the upgrade logic for existing DBs.

AFAIK, there's no legit use-case for a null case_type_id. We could think a bit about what happens when a case-type is deleted, but frankly... no behavior (nulling or deleting) seems good. The right thing should be preventing deletion of case-types that are in-use - which would be orthogonal to this PR.

**Comment by eileenmcnaughton** [comment]
Hmm - OK - the schema has an FK that sets this field to NULL if a case type is deleted so a bit more than that.

In terms of why I wanted to do this - I got custom data working for case but then couldn't get the automated test to work due to this & the bug for which this is the fix
https://github.com/civicrm/civicrm-core/pull/4851

I don't have any particular need to get the case custom data working - it was just scope creep from something else & this one is scope creep from that - so not committed to pushing through on this / fixing case custom data

**Comment by eileenmcnaughton** [comment]
Am closing this - issue should be fixed but this PR is only a minute change & doesn't seem worth keeping it hanging around in the hope the rest gets done

**Pull request closed without merging**
