### PR TITLE
Fix to avoid passing non-money to money::format

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fix to avoid passing non-money to money::format 

Before
----------------------------------------
we are passing the concatentation of 2 money amounts to format money

After
----------------------------------------
Form does a bit more work

Technical Details
----------------------------------------

Comments
----------------------------------------
Response to @demeritcowboy trying to break our tests

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Thanks will take a look.

**Comment by demeritcowboy** [comment]
The code looks ok just I'm having trouble doing an r-run since I'm not sure what the report wants and I keep getting no results. Also another INTL popup came up. Will pick this up again tomorrow, which for you is two days from now.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy yeah I just stepped through this on tests - seems pretty safe to me - the one that affects the forms might deserve a bit more careful checking

**Comment by demeritcowboy** [comment]
Ok I sort of figured out how to run, just still can't see how to have multiple comma separated values but anyway the warning is gone. Looks good.

Aside: when saving the contribution with a recognition date filled in you get

```
    Warning: array_filter() expects parameter 1 to be array, string given in CRM_Contribute_Form_Contribution::formRule() (line 914 of /home/jenkins/bknix-dfl/build/core-19940-91yka/web/sites/all/modules/civicrm/CRM/Contribute/Form/Contribution.php).
    Warning: count(): Parameter must be an array or an object that implements Countable in CRM_Contribute_Form_Contribution::formRule() (line 914 of /home/jenkins/bknix-dfl/build/core-19940-91yka/web/sites/all/modules/civicrm/CRM/Contribute/Form/Contribution.php).
```

**Comment by seamuslee001** [comment]
I'm going to merge based on @demeritcowboy 's review @eileenmcnaughton I think the other 2 issues should probably be put into the lab

**Comment by demeritcowboy** [comment]
Yep. https://lab.civicrm.org/dev/financial/-/issues/172

**Pull request merged**
