### PR TITLE
Add setting default to speed up cache flush

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Adds a define to civicrm.settings.php that speeds up cache flushes

Before
----------------------------------------
slower

After
----------------------------------------
faster

Technical Details
----------------------------------------
Detailed discussion in https://lab.civicrm.org/dev/core/-/issues/2031 but note
this does not add vendor in to make it easier to get it merged (as
there is more complexity there

Comments
----------------------------------------

### CODE REVIEW

**Comment by demeritcowboy** [comment]
This is already in the file - down by line 540. It's just commented out.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy ah - I should uncomment it then - I'll let tests finish first

**Comment by totten** [comment]
Tested locally, and it worked fine. On my system (with well-warmed OS file cache), it improved typical runtime for `cv flush` from ~2.2s to ~1.8s.

+1 for deduping with the existing comment. Pending that, I think it's merge-ready.

**Comment by totten** [comment]
@demeritcowboy The docblock has this bit:

> Remember to use your system's DIRECTORY_SEPARATOR the examples below assume /

Is that a problem with the current patch? Will this work out of the box on Windows?

**Comment by demeritcowboy** [comment]
Ok right good catch. I'm remembering this now. As written the initial `/` at the beginning makes it worse than the hardcoded default in Utils_File::findFiles since it ends up including dot-dirs, and you need 3 backslashes. What I'd suggest for now is just wrap it in

`if (strtoupper(substr(PHP_OS, 0, 3)) !== 'WIN') {`

**Comment by eileenmcnaughton** [comment]
updated

**Comment by totten** [comment]
Test failure looks unrelated/flaky.

I did an `r-run` with the update. Still good on Unix. :+1:

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
oh you merged - I was just trying to decide what the test fail was

**Pull request merged**
