### PR TITLE
dev/core#561 Convert Event Date Search to using datepicker

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This converts the event date field to using datepicker from jcalendar

Before
----------------------------------------
Jcalander is used

After
----------------------------------------
Datepicker is used

ping @eileenmcnaughton @monishdeb

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 yay super close now - this will conflict with the ones I put up yesterday though

**Comment by eileenmcnaughton** [comment]
I mean merge conflict not logic conflict

**Comment by seamuslee001** [comment]
@eileenmcnaughton i'm ok with that, i'll test yours out this AM and hopefully get them moved through and rebase this but would appreciate thoughts on this one as its the most odd ball one of them all

**Comment by eileenmcnaughton** [comment]
@seamuslee001 yeah my feeling is we have to keep if oddball & handle it is the BAO_Query object. If we try to normalise it at the form layer we lose the relativeness when we save to a smart group. Unfortunately that means the function to handle relative date queries will probably need some lines of hack specific to this field

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I think this is doing too much wrangling. I think if we handled 'event_date' as if it were valid in the BAO_Query object we can remove most of this.

We'd need to add the field to the metadata 'as if it were valid' too

```
diff --git a/CRM/Contact/BAO/Query.php b/CRM/Contact/BAO/Query.php
index 849325bf97..5a00812572 100644
--- a/CRM/Contact/BAO/Query.php
+++ b/CRM/Contact/BAO/Query.php
@@ -7021,6 +7021,9 @@ AND   displayRelType.is_active = 1
     }
     $fieldName = substr($values[0], 0, strlen($values[0]) - 9);
     $fieldSpec = $this->_fields[$fieldName];
+    if ($fieldName === 'event_date') {
+      // do absolutely one off special handling here for it
+    }
     $tableName = $fieldSpec['table_name'];
     $filters = CRM_Core_OptionGroup::values('relative_date_filters');
     $grouping = CRM_Utils_Array::value(3, $values);
diff --git a/CRM/Event/BAO/Query.php b/CRM/Event/BAO/Query.php
index 03d83044cb..50f973842b 100644
--- a/CRM/Event/BAO/Query.php
+++ b/CRM/Event/BAO/Query.php
@@ -264,6 +264,11 @@ class CRM_Event_BAO_Query extends CRM_Core_BAO_Query {
         );
         return;
 
+      case 'event_date_low':
+      case 'event_date_high':
+        // do one off special handling here.
+        return;
+
       case 'event_end_date_low':
       case 'event_end_date_high':
         $query->dateQueryBuilder($values,
(END)
```

**Comment by seamuslee001** [comment]
@eileenmcnaughton i'm just struggling a little to get my head around what that would actually look like when the current qill outputs statements on the 2 fields independently maybe there is a way you have thought but its not at the moment clear.

**Comment by eileenmcnaughton** [comment]
Closing - superceded

**Pull request closed without merging**
