### PR TITLE
Deprecate dupeQuery hook

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Deprecte dupeQuery hook

Before
----------------------------------------
hook unused in universe & pretty fugly but no active discouragement

After
----------------------------------------
Marked deprecated - will do the same in docs

Technical Details
----------------------------------------
I did a universe search & found no usages - this hook feels to me like one of those things that got added cos it seemed like a good idea but was never really the right thing in the right place & not that useful. Let's deprecated it here & in the docs
& not encourage people to use it

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton 👍 I just pushed a noisy deprecation notice into this PR as well.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
Thanks @colemanw  - I had been thinking we should add something like `invokeDeprecated()` that would check if a hook is implemented - not just if it does anything - but this is still better with the deprecation

**Comment by eileenmcnaughton** [comment]
unrelated fail

**Pull request merged**
