### PR TITLE
dev/core#1854: Fix Calculation of Overridden Membership Status

### PR DESCRIPTION
**Pull request by MiyaNoctem**
Overview
----------------------------------------
Under certain special circumstances, once a main membership that has related memberships (eg. a membership held by an employer for a maximum number of employees), if the status is overridden for a specific date, and the date has been met so that status for the main membership and its related memberships can now be calculated by the membership status calculation job, some of the related memberships may get deleted.

https://lab.civicrm.org/dev/core/-/issues/1854

Before
----------------------------------------
When a membership has an overridden status until a certain date, and that date is met, the status calculation job will remove the restriction by setting the relevant fields to null, and updating the membership. If that membership has related memberships, the change will be replicated to each membership. To cycle through the memberships, the system will go through the list of all related contacts, and check if each contact has a membership. If the parent membership has a limit on maximum related memberships, the system will start counting memberships, and delete any memberships found after reaching the limit.

The problem presents itself when a membership is found for the n-th contact related to the organization, and the (n+1)-th contact doesn't have a membership, and the (n+b)-th contact does have a membership, where b > 1. When cycling trough the contacts, the ID of the related membership is stored on `$params['id']`. When the system reaches the (n+1)-th contact, which does not have a membership, the instruction to store the membership id is skipped. This means `$params['id']` will now hold the ID of the membership for the n-th contact, which will get updated, and counted twice. Thus, the number of allowed memberships will be reached before all memberships are actually accounted for. Thus, memberships after the max limit is reached will be deleted. 

Furthermore, if there is a contact without a membership after a deleted membership, the same membership will deleted twice, causing a fatal error to be thrown here:

https://github.com/civicrm/civicrm-core/blob/b7bfc6be2f3e6c62548f85571ef032d2989c80cf/CRM/Member/BAO/Membership.php#L641

After
----------------------------------------
Changed the cycle through related contacts, such that if a membersihp fir it does not exeist, `$params['id']` is unset. This will cause the memberships to be counted truthfully, and no side effect of deleting valid memberships will get triggered, nor the double deletion of a membership.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Thanks for the patch - are you able to add a test - we have quite a bit of test cover on this function in CRM_Contact_BAO_RelationshipTest  (much thanks to @agileware-pengyi as I recall)

**Comment by eileenmcnaughton** [comment]
(the explanation makes sense & I don't see any issues with the code-approach)

**Comment by eileenmcnaughton** [comment]
@MiyaNoctem are you able to look at a test here?

**Comment by MiyaNoctem** [comment]
@eileenmcnaughton , I will be working on writing the test today, sorry I took some time, but things have been a little crazy.

**Comment by eileenmcnaughton** [comment]
thanks @MiyaNoctem

**Comment by eileenmcnaughton** [comment]
@MiyaNoctem it might be better to close this out until you have a chance to write the test? Most of the work is in the PR template but that's an easy copy & paste

**Comment by MiyaNoctem** [comment]
Sorry for the wait @eileenmcnaughton, was out for a couple of weeks. It was quite tricky to set-up a case for the test, but I think it's done. Just waiting for all tests to run now.

**Comment by eileenmcnaughton** [comment]
Ok - this makes sense to me - and we are starting to get good test cover here (phew) - thanks for your work on this

**Comment by eileenmcnaughton** [comment]
Look what I just found - https://lab.civicrm.org/dev/membership/-/issues/8 - from a year ago!

**Pull request merged**
