### PR TITLE
[REF] minor code cleanup - do not build order var just to hurt brains

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
minor code cleanup 

The order var is basically orderBy prepended by Order by - which is then stripped.

Just don't

Before
----------------------------------------
More brain pain

After
----------------------------------------
less brain pain

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton test failure here https://test.civicrm.org/job/CiviCRM-Core-PR/24584/testReport/junit/(root)/CRM_Contact_SelectorTest__testSelectorQuery/testSelectorQuery_with_data_set__4/ is relevant

**Comment by eileenmcnaughton** [comment]
@seamuslee001 yeah - an enotice - I can fix that by declaring it but are you ok to give it merge on pass?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 look how cheerful jenkins is now - I'm gonna clean up this function as it has some bugs & it is sh*te to read atm

**Comment by seamuslee001** [comment]
Looks fine to me Jenkins has passed it merging

**Pull request merged**
