### PR TITLE
CRM-17984 test to demonstrate breakage

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
- [CRM-17984](https://issues.civicrm.org/jira/browse/CRM-17984)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This is a regression in tomorrow's planned RC

**Comment by totten** [comment]
@eileenmcnaughton , since #8205 also includes a commit for "CRM-17984 test to demonstrate breakage", can we close #8204 ? (A little confused because the commit msg are the same, but the sha1 and content looks a bit different.)

**Comment by totten** [comment]
I merged the other one, which means there's a test in `master`, and this now conflicts. I'll trust your judgment to rebase/resubmit if the discrepancy was important.

**Comment by eileenmcnaughton** [comment]
Right - this had no value other than to be able to demonstrate jenkins failing on a real error reproduced in a test

**Pull request closed without merging**
