### PR TITLE
handle less common dynamic reference cases

### PR DESCRIPTION
**Pull request by MegaphoneJon**
Civi 5.26 included #17125, "Fix Dedupe entity_tag mangling bug".  This introduced the new method `CRM_Core_DAO::getDynamicReferencesToTable()` and `CRM_Dedupe_MergeHandler::getTablesRelatedToTheMergePair()`.  However, there are two bugs in the implementation:

* It assumes that only one dynamic reference can exist between two tables.  In addition to extensions that may introduce dynamic references, this is also untrue in core: `civicrm_pcp_block` has two dynamic references to `civicrm_contact`: Both `entity_id` and `target_entity_id`.
* It assumes that the column specifying the entity is always called `entity_table`, and this is hard-coded into the SQL in `getTablesRelatedToTheMergePair()`.  However, this column isn't always `entity_table`.  We should pull the correct column name from the metadata.

I don't think there's a Gitlab ticket for PR #17125, so I'm referencing the PR here instead.

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
This looks sensible to me & should go against the PR as a regression based on the description

@MegaphoneJon the test fail relate - and it would be good to also add into that test where it is failing a check for the now-broken thing

**Comment by MegaphoneJon** [comment]
I'm happy to put against the RC if you prefer - technically it's a regression, but I think it's only going to affect folks who have a custom entity with a dynamic reference to `civicrm_contact` where the entity table isn't named `entity_table`, so the number of folks affected may well be just me.

**Comment by MegaphoneJon** [comment]
OK, I found the issue and pushed a fix.

I tried a couple of tests but didn't come up with anything meaningful.  The bug isn't in `CRM_Core_DAO::getDynamicReferencesToTable()` but in `CRM_Dedupe_MergeHandler::getTablesDynamicallyRelatedToContactTable()`.  However, the `civicrm_pcp_block` issue can't actually be triggered here, because in practice, `civicrm_pcp_block.target_entity_type` can never be `contact`.  The second bug ("`entity_table` is hard-coded") only exists in custom entities.

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon  this seems OK to me - but it should be on the rc shouldn't it?

**Comment by eileenmcnaughton** [comment]
Oh I see your comment on that - yes let's go rc as a regression but we can be non-aggressive about porting to the released version

**Comment by MegaphoneJon** [comment]
I just found another hard-coded reference to `entity_table` in `CRM_Dedupe_Merger` from the same commit that added the other.  If this change passes tests I'll redo this against the RC.

**Comment by eileenmcnaughton** [comment]
Thanks @MegaphoneJon sorry this hit you! I'm keen to reduce the number of queries we do during deduping as they can cause contention - but not to the point where things don't work :-)

**Comment by seamuslee001** [comment]
@MegaphoneJon tests have passed now

**Comment by eileenmcnaughton** [comment]
Closing this as we will merge the rc port

**Pull request closed without merging**
