### PR TITLE
CRM-17824 Membership Report: Detail-receive date unmatched with Contribution date

### PR DESCRIPTION
**Pull request by bjendres**
This should fix [CRM-17824](https://issues.civicrm.org/jira/browse/CRM-17824). The `receive_date` was not properly defined after a `GROUP BY` since it didn't have any aggregators. I agree with `karamveer` that the most recent contribution would make the most sense.

The only thing I'm not sure about is whether there is another way of using this report where this patch wouldn't work - I can't think of anything though.

### CODE REVIEW

**Comment by seamuslee001** [comment]
@systopia Can you please fix the style errors found by Jenkins https://test.civicrm.org/job/CiviCRM-Core-PR/11301/checkstyleResult/new/

**Comment by systopia** [comment]
@seamuslee001: that's looking better, right? Thanks.

**Comment by seamuslee001** [comment]
Yes that is, I'll try testing it out at some point but it might be right.

**Comment by seamuslee001** [comment]
I have tested this on a test DB, This does not work as it still picks up the first contribution not the most recent contribution.

**Comment by systopia** [comment]
> I have tested this on a test DB, This does not work as it still picks up the first contribution not the most recent contribution. 

Hm, my client says it works for them. @seamuslee001: Could you give me access to your test data or give instructions on how to reproduce this?

**Comment by seamuslee001** [comment]
Hi @systopia I found it was an error on my part, the report does now have correct receive date but there is a disconnect with the other bits of payment information. I'll send you a direct email with some screenshots so you can see what i mean.

**Comment by seamuslee001** [comment]
@jitendrapurohit tl/dr i worked on this, all this did was display the most recent receive date all the other contribution data didn't match the contribution with the most recent receive date.  This was my stab at fixing the problem but Dave J i think may have had some issues performance wise https://github.com/civicrm/civicrm-core/pull/8837 and this was the first stab by Ellen as well https://github.com/civicrm/civicrm-core/pull/8687

**Comment by eileenmcnaughton** [comment]
In discussion with @seamuslee001 there are actually 3 old PRs open on this. We are going to try to progress #8837 - please help out on that PR if you can!

**Pull request closed without merging**
