### PR TITLE
Scheduled Reminders UI - Show more activity tokens in admin GUI

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

In "Administer => Communications => Scheduled Reminders", this updates the token-picker  to include a more complete list of activity tokens.

This is extracted from @mattwire's branch in #16983.

Before
----------------------------------------
Screen Shot 2021-08-10 at 9 18 25 PM

After
----------------------------------------

Screen Shot 2021-08-10 at 9 19 00 PM

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@totten so for contribute I did a bit of work before making a similar change to ensure that the tokens exposed were the same whichever screen you accessed them through, that they resolved the same way whichever screen you accessed them through and that any new tokens we advertised used the new format that we have been working to agree. (in other words I think a variant of this makes sense but I see it as something worth doing at the end of the reconciliation process)

**Comment by eileenmcnaughton** [comment]
As an aside - I think what we actually want on this screen is an api to fetch the available tokens for the entity - because at the moment this screen does not respond to entity selection - which should happen from a front end ajax call.

My vote would be to close this & plan that api & then later update this screen to call that api

**Comment by totten** [comment]
TBH, I don't care too much either way. To my eye, the patch is better than the status quo (i.e. the Sched Reminder GUI becomes more accurate - doesn't change/add/remove any tokens). If `{activity.*}` has the same kind of reconciliation as `{contribution.*}`, then we're on the hook for the identification+upgrade work regardless of the order of changes. OTOH, this screen isn't super-pressing for me, and yeah, the final form will be something different.

**Comment by mattwire** [comment]
@eileenmcnaughton Agree with the long-term goal. But the activity tokens are reasonably well tested and have been in core for a while so let's not make it difficult to use them.  The "final" form will need to account for "sub-entity type" as well so we can show custom tokens for specific activity types etc.

@totten Merging this because I agree it's better than what we have now and it will directly benefit end-users.

**Pull request merged**
