### PR TITLE
CRM-19453

### PR DESCRIPTION
**Pull request by spalmstr**
Corrects error in Path.hlp that causes Administer -> System Settings -> Directories to fail under Joomla.

---
- [CRM-19453: System->Directories fails to display under Joomla](https://issues.civicrm.org/jira/browse/CRM-19453)

### CODE REVIEW

**Comment by monishdeb** [comment]
@spalmstr seems like PR is not clean since there are unwanted commits. Can you please create a new PR by doing ```cherry-pick```. For reference check https://gist.github.com/unbracketed/889c844473bcca1917e2

This is a technique where we always pick commits (only those required) from one branch to your new branch. Also in order to avoid stale PR like this one, always do ```git pull --rebase upstream master``` . Am closing this PR now since it gone stale.

**Comment by spalmstr** [comment]
Hi Monish,

 

Thanks for your email – I’m still feeling my way round the intricacies of Git, so your email is most helpful.  After generating the last PR, I realised I should have been creating branches to cover the various changes.

 

Stephen

**Comment by monishdeb** [comment]
@spalmstr feel free to ask your git related or any doubt in our dev channel https://chat.civicrm.org/civicrm/channels/dev

**Comment by spalmstr** [comment]
Strange, a PR for another issue seems to have got swept up with this one.

**Pull request closed without merging**
