### PR TITLE
Convert to Field on email Trait to entity reference

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This changes the to field when doing a stand-alone email from a weird java-scripty field to an entity reference field

Before
----------------------------------------
Lots of custom js fo the to field

After
----------------------------------------
Entity reference, like with cc & bcc fields

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw I think this is the commit for the last entity ref field on that form now. I have had a lot of preliminaries merged to get to a somewhat readable switch over

**Comment by eileenmcnaughton** [comment]
@demeritcowboy any chance you could review this for me - it could do with your 'eye-for-gotchas' - it replaces the 'to field' on all the screens for sending emails to one or more contacts (but not civimails)

**Comment by demeritcowboy** [comment]
Sure, can look tomorrow.

**Comment by eileenmcnaughton** [comment]
thanks!

**Comment by demeritcowboy** [comment]
One thing is that if you're on a contact view page and from the actions dropdown choose Send Email, it no longer prepopulates the To field. It's not immediately obvious why.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy thanks - I'll check it out

**Comment by demeritcowboy** [comment]
Oh actually looking at it now afresh it's probably toContact in the template.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy yes - it looks like it needs setDefaultValues - the code is so awful that coming back to it again I can't make much sense of it :-(

I put up this minor simplification https://github.com/civicrm/civicrm-core/pull/17873 for now

**Comment by eileenmcnaughton** [comment]
I'm going to close this for now - per comments on https://github.com/civicrm/civicrm-core/pull/17873

**Pull request closed without merging**
