### PR TITLE
Afform: Fix for formbuilder autocomplete (prefill) on anonymous forms

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Prefill not working on anonymous forms.

To reproduce:

1. Create a form with an individual and an organisation.
2. Add an existing contact autocomplete for the organisation.
3. Select a savedsearch autocomplete that contains the filter eg. Contact organisations (set permission to "open access").
4. Run the form logged in - you can select and prefill organisations.
5. Run the form as anonymous user - you can select organisation but prefill API returns empty result.

Before
----------------------------------------
Prefill not working on anonymous forms.

After
----------------------------------------
Prefill working on anonymous forms.

Technical Details
----------------------------------------
It seems like there are two issues in the code:
1. The savedsearch definition is nested one level deeper in "defn" key. Is that because it's a savedsearch in an autocomplete?
2. The "secureapi4" doesn't seem to respect the result of validateBySavedSearch. I opted to use the standard `civicrm_api4` and checkPermissions=FALSE once it's been validated by `validateBySavedSearch()` but maybe secureApi4 should instead be made aware of savedsearch?

Comments
----------------------------------------
@colemanw Not sure if this is quite the right fix or if this has any security implications.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire is this a 'never-worked'?

**Comment by mattwire** [comment]
> @mattwire is this a 'never-worked'?

I don't know - it's the first time I've tried to use it and it didn't work!

**Comment by eileenmcnaughton** [comment]
OK - @colemanw when you look at this you might consider whether we should target the rc

**Comment by mattwire** [comment]
I've added another commit for JOINS (so eg. we can prefill website linked to contact). This really needs reviewing by @colemanw to see what is the best way here.

**Comment by mattwire** [comment]
test this please

**Comment by colemanw** [comment]
@mattwire I haven't forgotten about this, but are you able to resolve the merge conflicts?

**Comment by colemanw** [comment]
@mattwire ok thanks for your patience. I've tested out your reproduction steps and was surprised that I couldn't initially reproduce the bug. After stepping through the code I think there are 2 issues going on. The first is a genuine bug which skips autocomplete validation as you noted. I've copied your 1-line fix from this PR into #25822. The second issue I think may be a misconfiguration on your form. In order for an anonymous user to update any contacts, you have to use this setting on the contact:
image

Once you do that, I don't think the rest of this PR is needed.

**Comment by mattwire** [comment]
Thanks @colemanw looks like that fixes it.

A related but different issue - Looks like we currently don't have a way to retrieve contact info without enabling create or update? If you untick create/update you get a empty select2 which is a shame because it would be nice to be able to rertreive data without allowing create/update.

**Pull request closed without merging**
