### PR TITLE
Fix extensions tabs following deprecation of old tab code

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Fix extensions tabs following changes in #19066

Before
----------------------------------------
Tabs stopped rendering on extensions page.

After
----------------------------------------
Tabs load and selectedChild works.

Technical Details
----------------------------------------
Add tab javascript resource.

Comments
----------------------------------------
@demeritcowboy @colemanw This is the fix I think!

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Thanks. Works for me!

**Comment by eileenmcnaughton** [comment]
@mattwire @demeritcowboy - quick work! Can you confirm

1) can we close the issue
2) this is against master - should it be against the rc (which was only cut a few days ago)

**Comment by demeritcowboy** [comment]
The other PR was merged yesterday so it's just master.

The lab ticket can close just needs a milestone - doesn't seem to be a 5.34 available.

**Comment by eileenmcnaughton** [comment]
Created - @mlutfy can we make it so Dave can create milestones?

**Comment by mlutfy** [comment]
@eileenmcnaughton On Gitlab or Github? (Gitlab should be easy, but I don't know for Github)

**Comment by demeritcowboy** [comment]
Gitlab. An alternative is add it to the release tasklist to create a new label for whatever the new master is. Not sure where that list/script lives. Maybe this should be its own ticket.

**Pull request merged**
