### PR TITLE
Fix metadata on cancel_reason so it is an exportable field

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Make cancel_reason searchable

Before
----------------------------------------
contribution search ignore the cancel_reason critieria

After
----------------------------------------
filter applied
screenshot 2018-09-05 17 46 23

Technical Details
----------------------------------------
This is an alternative to https://github.com/civicrm/civicrm-core/pull/12761 - it turns out the reason the default clause is not working is the field is not declared as 'exportable'.

I did consider adding a unique name in the xml but the unit test added when the field was added to the form used 'cancel_reason' so I switched the form field to have that name. As it was not previously working no smart groups will be harmed

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by sluc23** [comment]
@eileenmcnaughton  I've tested this PR and confirm it works as expected in Contribution / Advanced Search and Builder for `cancel_reason` field using operators `=` and `LIKE`.

But `IN` operator returns and error

```
   [info] $Fatal Error Details = Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => handle
        )

    [code] => -2
    [message] => DB Error: syntax error
    [mode] => 16
    [debug_info] => SELECT DISTINCT UPPER(LEFT(contact_a.sort_name, 1)) as sort_name  FROM civicrm_contact contact_a LEFT JOIN civicrm_contribution ON civicrm_contribution.contact_id = contact_a.id  WHERE  (  ( civicrm_contribution.financial_type_id IN ("3", "1", "4", "2") AND civicrm_contribution.cancel_reason IN '' )  )  AND (contact_a.is_deleted = 0)    ORDER BY UPPER(LEFT(contact_a.sort_name, 1)) asc  [nativecode=1064 ** You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''' )  )  AND (contact_a.is_deleted = 0)    ORDER BY UPPER(LEFT(contact_a.sort_na' at line 1]
    [type] => DB_Error
    [user_info] => SELECT DISTINCT UPPER(LEFT(contact_a.sort_name, 1)) as sort_name  FROM civicrm_contact contact_a LEFT JOIN civicrm_contribution ON civicrm_contribution.contact_id = contact_a.id  WHERE  (  ( civicrm_contribution.financial_type_id IN ("3", "1", "4", "2") AND civicrm_contribution.cancel_reason IN '' )  )  AND (contact_a.is_deleted = 0)    ORDER BY UPPER(LEFT(contact_a.sort_name, 1)) asc  [nativecode=1064 ** You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''' )  )  AND (contact_a.is_deleted = 0)    ORDER BY UPPER(LEFT(contact_a.sort_na' at line 1]
    [to_string] => [db_error: message="DB Error: syntax error" code=-2 mode=callback callback=CRM_Core_Error::handle prefix="" info="SELECT DISTINCT UPPER(LEFT(contact_a.sort_name, 1)) as sort_name  FROM civicrm_contact contact_a LEFT JOIN civicrm_contribution ON civicrm_contribution.contact_id = contact_a.id  WHERE  (  ( civicrm_contribution.financial_type_id IN ("3", "1", "4", "2") AND civicrm_contribution.cancel_reason IN '' )  )  AND (contact_a.is_deleted = 0)    ORDER BY UPPER(LEFT(contact_a.sort_name, 1)) asc  [nativecode=1064 ** You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''' )  )  AND (contact_a.is_deleted = 0)    ORDER BY UPPER(LEFT(contact_a.sort_na' at line 1]"]
)
```

**Comment by eileenmcnaughton** [comment]
@sluc23 it was trashing the data by applying trim to an array - see https://github.com/civicrm/civicrm-core/pull/12775/files#diff-0a639f0cf282805e238274495195e6a4R509

(I don't actually know that is a good place for trim anyway - I think the form layer & api layer do it and the lower layer may do too but that is an aside)

**Comment by sluc23** [comment]
@eileenmcnaughton now it works as expected with `IN` operator too. Tx for fixing this issue
I'll close #12761 referencing this one

**Pull request merged**
