### PR TITLE
(WIP) CRM-16395 - Installation with localized default settings

### PR DESCRIPTION
**Pull request by samuelsov**
Will read a file settings.json in l10n/xx_XX/ and update the settings depending on the locale selected during installation.

currencies_enabled will not work because it's not a setting, it's an option group.

---
- [CRM-16395: Installation with localized default settings](https://issues.civicrm.org/jira/browse/CRM-16395)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Tests have disappeared so I'm going to re-run them. @totten is this still valid after your settings work?

**Comment by agh1** [comment]
Jenkins, retest this please

**Comment by totten** [comment]
Re: eileen - yes, I think this is still equally valid after the 4.7 settings work. 

The main limitation I see is that it only applies to the web-based installer for D7/WordPress -- the other installers (Joomla, provision_civicrm, civibuild/setup.sh) wouldn't use these files. That doesn't need to be fatal, but just to check-in about an alternative -- in 4.7, you can listen to `SystemInstallEvent` and perform extra initialization on the first boot.  ( [example](https://github.com/civicrm/civicrm-core/blob/4.7.7/Civi/Core/Container.php#L231) ) Wonder if that would work for this? Perhaps we can pick this up at the sprint in Coloardo?

Since the PR isn't mergable, I'm flagging this as "WIP" (work-in-progress).

**Comment by samuelsov** [comment]
@totten ok, i will see if i can rework this to make it work for all type of installer

**Comment by samuelsov** [comment]
Replaced by https://github.com/civicrm/civicrm-core/pull/8538

**Pull request closed without merging**
