### PR TITLE
/dev/core#716 - Add decimals in Contribution Amount on Repeat Contrib…

### PR DESCRIPTION
**Pull request by francescbassas**
…utions Report

See https://lab.civicrm.org/dev/core/issues/716

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Makes sense - Jenkins should pass through that create so if jenkins passes I'm happy to merge

**Comment by seamuslee001** [comment]
Just a question is this the same precision as the core tables?

**Comment by eileenmcnaughton** [comment]
yep :-)

**Comment by seamuslee001** [comment]
Excellent *mr burns fingers*

**Comment by francescbassas** [comment]
Albert Vall-Llobera contributes fixing this issue

**Comment by seamuslee001** [comment]
Tests have passed merging as per the tag

**Comment by eileenmcnaughton** [comment]
@agh1 @seamuslee001 see comment above about a contributor - am wondering if there is some step we should do something to get him into our credits

**Pull request merged**
