### PR TITLE
Resolve issue CRM-21831 on https://issues.civicrm.org/jira/browse/CRM-21831

### PR DESCRIPTION
**Pull request by elgui02**
Overview
----------------------------------------
Resolve issue "When grouping contribution details report by payment method, the group heading is no longer showing the contribution total, only row count"

Before
----------------------------------------

After
----------------------------------------
image

Technical Details
----------------------------------------
Before the code search for the civicrm_contribution_total_amount_sum on aliases but this alias change to civicrm_contribution_total_amount same case with sum column

---

 * [CRM-21831: When grouping contribution details report by payment method, the group heading is no longer showing the contribution total, only row count](https://issues.civicrm.org/jira/browse/CRM-21831)

### CODE REVIEW

**Comment by elgui02** [comment]
of course, if you ask me

**Comment by seamuslee001** [comment]
Jenkins ok to test

**Comment by eileenmcnaughton** [comment]
We should make sure this fix also fixes related https://lab.civicrm.org/dev/report/issues/1

I'm deeply suspicious of these lines

```
  public function select() {
    $this->_columnHeaders = array();

    parent::select();
    //total_amount was affected by sum as it is considered as one of the stat field
    //so it is been replaced with correct alias, CRM-13833
    $this->_select = str_replace("sum({$this->_aliases['civicrm_contribution']}.total_amount)", "{$this->_aliases['civicrm_contribution']}.total_amount", $this->_select);
    $this->_selectClauses = str_replace("sum({$this->_aliases['civicrm_contribution']}.total_amount)", "{$this->_aliases['civicrm_contribution']}.total_amount", $this->_selectClauses);
  }
```

**Comment by elgui02** [comment]
i think this change works on the view but not on the query
> We should make sure this fix also fixes related https://lab.civicrm.org/dev/report/issues/1

I'm deeply suspicious of these lines

  public function select() {
    $this->_columnHeaders = array();

    parent::select();
    //total_amount was affected by sum as it is considered as one of the stat field
    //so it is been replaced with correct alias, CRM-13833
    $this->_select = str_replace("sum({$this->_aliases['civicrm_contribution']}.total_amount)", "{$this->_aliases['civicrm_contribution']}.total_amount", $this->_select);
    $this->_selectClauses = str_replace("sum({$this->_aliases['civicrm_contribution']}.total_amount)", "{$this->_aliases['civicrm_contribution']}.total_amount", $this->_selectClauses);
  }

**Comment by eileenmcnaughton** [comment]
Thanks for this @elgui02 - I took a look & pushed up a variant of this that goes a little bit further - #11917 - if you can take a look there.

**Comment by seamuslee001** [comment]
@eileenmcnaughton should this be closed now?

**Comment by eileenmcnaughton** [comment]
yes - closing this - thanks for this @elgui02 - It has been merged albeit not in this PR

**Pull request closed without merging**
