### PR TITLE
Check if these acl functions are tested - close when test have run (pref with comment as to outcome)

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
_A brief description of the pull request. Keep technical jargon to a minimum. Hyperlink relevant discussions._

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @monishdeb - in order to add a v4 api for LineItems we need to review the functionality currently in the v3 api that should be 'somewhere else' - in the case of this ACL code it *should* be the case that the ACL hook is called & the JMA extension - do you know if it 'works' without these calls?  I believe at least on the GET the hook is already called

fyi @colemanw

**Comment by seamuslee001** [comment]
I am unsure on this topic will leave it for Monish to comment more, I suspect that the ACL hook isn't called but not 100% sure

**Comment by eileenmcnaughton** [comment]
In theory the hook is called by basic_get as part of addSelectWhere - but ....I'm unsure

**Comment by eileenmcnaughton** [comment]
@monishdeb @seamuslee001 no tests .... :-(

**Pull request closed without merging**
