### PR TITLE
Standalone login ux

### PR DESCRIPTION
**Pull request by artfulrobot**
Small steps forward on providing a way to administer users, roles.

This PR provides a SK/FB for listing/editing users. It also reworks the entities for RBAC; moving from separate Role and UserRole entities to a compound roles field on User using a pseudoconstant.

Test updated.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@totten I assume you have seen this

@artfulrobot this is wholly contained within the standalone extension so it's up to you if you want to self-merge this now (or I can) or whether you are wanting to get some pre-merge collaboration

**Comment by totten** [comment]
@artfulrobot Yeah, mapping-entities like `UserRole` and `RolePermission` leave me with some ambivalence. They can handle some edges (vis-a-vis search/batch-update/concurrency) better -- but we don't really need those for `User`s and `Role`s. And they come with some cost -- longer incantations, more split-up model.

So I definitely see the case for converting entity `UserRole` to the field `User.roles`. 👍 

I'm not as keen about converting `Role`+`RolePermission` to `OptionGroup`+`OptionValue`+`RolePermission`.

It seems to me that the model would be more intuitive if you had:

* Entity `User` with field `roles` (with pseudoconstant pointing to `civicrm_role`)
* Entity `Role` with field `permissions` (with a pseudoconstant derived from a callback function - ultimately [hook_permissionList](https://github.com/civicrm/civicrm-core/blob/f48d7e656eb5d716982844e2b9ffab8268e51ee0/Civi/Api4/Action/Permission/Get.php#L38))

Aside: I think there's an interesting conversation to have about defaults and packaging for roles/permissions... But that maybe a separate issue/chat.

**Comment by totten** [comment]
> Aside: I think there's an interesting conversation to have about defaults and packaging for roles/permissions... But that maybe a separate issue/chat.

OK, so how it relates here: suppose you're packaging-up a `Role` to use on other sites. With most tooling (`*.mgd.php`, `configitems`, `*.sqldata.php`, etc):

* It should be pretty easy to package one `Role` record with a `permissions` property.
* It would be more work to package an `OptionValue` record with a list of related `RolePermission` records.

**Comment by seamuslee001** [comment]
@artfulrobot does this support the idea a user could have multiple roles at once?

**Comment by totten** [comment]
@artfulrobot Cool, yes, I think this is a more consistent schema. And I agree about preferring to merge.

FWIW, I also spent some time playing around with it. You probably have a list of notes in your head for things to tackle, but (just in case it helps) here are some of the things that popped out at me:

* "Edit User"
    * Editing various seemed to work. Woot.
    * On the post-submit redirect, the URL got munged a little (dropped the HTTP port). I feel like there was a parallel PR on similar theme, though.
    * "Timezone" field is unclear.
* "Add User"
    * The "Enabled" should be on by default?
    * After submitting, it didn't actually create the user.
* "Edit Role"
    * Huzzah. I edited the label and permissions.
    * On the fence about whether it should allow one to rename an existing role.  It probably works.  OTOH, trying to think of comparable
      entities/fields...  the `civicrm_custom_group.name` and `civicrm_group.name` are both initialized from the title (and then become read-only).
* On `civicrm/admin/users`, there's a checkbox to filter by "Active".  If you toggle and watch the data, it's a bit funny.  (Perhaps because checkbox
  are visually two options -- On|Off -- but the "Active" filter is logically three options - Any|Active|Inactive).
* Nav Menu
     * Titles are little inconsistent.  Maybe call it "Users" and "Roles"?
      * There is a pre-existing submenu for "Users and Permissions" - maybe put the links in there?

**Comment by colemanw** [comment]
@artfulrobot I'm not sure if "X" is a very good name for an afform...

**Comment by colemanw** [comment]
... or a social network LOL

**Comment by colemanw** [comment]
@artfulrobot just wait until https://github.com/civicrm/civicrm-core/pull/27553 is merged or it will conflict.

**Comment by colemanw** [comment]
@artfulrobot ok merged! I would tweet about it but... you know...

**Pull request merged**
