### PR TITLE
dev/core#720 [REF] refactor out components of contributionSummary function

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Code clean up preliminary to resolving performance issues

Before
----------------------------------------
Code hard to read

After
----------------------------------------
Code more readable

Technical Details
----------------------------------------
Once the tests for this - https://github.com/civicrm/civicrm-core/pull/13605 are merged I'll rebase.

I'm happy to break this down into a series of easier-to-review PRs - so far

#13608 (merged) &
#13614 (merged)
#13616 (merged)
#13622 (merged)
#13626

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton needs a rebase

**Comment by eileenmcnaughton** [comment]
thanks @seamuslee001 I've refactored & pushed  - I added has-test as there are already-merged tests.

There is a style issue but I suspect I'll get more interest in reviewing in parts anyway so I've pushed up the first commit separately - here (which doesn't have a style issue) - I can fix the style issue in here if someone DOES want to review them together but I'd probably have to rejig to get the fix in the right commit 

https://github.com/civicrm/civicrm-core/pull/13608/

**Comment by seamuslee001** [comment]
@eileenmcnaughton this needs a rebase again

**Comment by eileenmcnaughton** [comment]
I just spun off https://github.com/civicrm/civicrm-core/pull/13614 - will rebase this once I've seen tests there not trip on a style issue

**Comment by eileenmcnaughton** [comment]
or trip & be fixed as it turned out :-)

**Comment by eileenmcnaughton** [comment]
@colemanw I think this is trival enough to merge now - & then now you've approved removing mean & median I'll do that

**Pull request merged**
