### PR TITLE
Fix BreadCrumb function input on multiple pages

### PR DESCRIPTION
**Pull request by sunilpawar**
Overview
----------------------------------------
fixing BreadCrumb function input on multiple pages

### CODE REVIEW

**Comment by demeritcowboy** [comment]
@sunilpawar I think this is the same as https://lab.civicrm.org/dev/drupal/-/issues/133 but when I looked I was thinking the right solution is to REMOVE the breadcrumb, at least in some places like CRM_Contact_Form_Domain since otherwise it appears TWICE.

**Comment by demeritcowboy** [comment]
Hi, just confirming what I saw earlier in the lab ticket. This is the test site here and with the PR it shows twice. I think at least some of the calls with bad params need to be removed instead.

Untitled

**Comment by sunilpawar** [comment]
@demeritcowboy  i  will check unwanted BreadCrumb call and remove it.
Thanks

**Comment by eileenmcnaughton** [comment]
Closing this out as it seems to be not-review-ready and possibly solved in the interim

**Pull request closed without merging**
