### PR TITLE
CRM-20900 (IIDA-169), fixed query to retrieve payments

### PR DESCRIPTION
**Pull request by pradpnayak**
----------------------------------------
* CRM-20900: Contribution not set to completed when payment is recorded
  https://issues.civicrm.org/jira/browse/CRM-20900

### CODE REVIEW

**Comment by pradpnayak** [comment]
jenkins, retest this please.

**Comment by monishdeb** [comment]
@eileenmcnaughton I have removed the UT ```testPartialPaymentWithCreditCard(...)``` because currently in Civi (after https://github.com/civicrm/civicrm-core/pull/10718 got merged) we are not allowing 'Partially paid' backoffice contribution via UI. Apart from that this PR is ready for QA

**Comment by eileenmcnaughton** [comment]
@monishdeb @pradpnayak I need more explanation about why this change is needed. From reading the code it seems you are basically removing the checks on the status_id of the financial_trxn - ie assuming it is always Completed or Refunded & never Pending/Weird & wonderful variant.

I feel like I need more background before I can feel comfortable with this. I also worry that this might break someone's secret sauce.

**Comment by eileenmcnaughton** [comment]
@pradpnayak it would help if you filled in the PR template!

**Comment by JoeMurray** [comment]
@monishdeb @pradpnayak please respond to @eileenmcnaughton very reasonable request from Sep 20!

**Comment by monishdeb** [comment]
@JoeMurray I'll discuss with @pradpnayak as I am not sure what exactly the core issue (not IIDA specific) is, for which this improvement was made. After then I will update the PR template and also JIRA description.

**Comment by pradpnayak** [comment]
Added info on CiviCRM issue tracker at https://issues.civicrm.org/jira/browse/CRM-20900?focusedCommentId=109510&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-109510

To replicate make sure you enable Deferred Revenue and Always post AR settings.

**Comment by eileenmcnaughton** [comment]
@monishdeb this is stale - I'm going to close & let you re-open when that is fixed (would also need steps to replicate)

**Pull request closed without merging**
