### PR TITLE
dev/core#534 Re-instate pay-now button

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Port of https://github.com/civicrm/civicrm-core/pull/14051

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @kcristiano

**Comment by kcristiano** [comment]
jenkins test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by kcristiano** [comment]
@seamuslee001 This PR restores the PayNow button.   Tested on 5.12.1 with PR applied.    Works properly.  Looks good to merge.

**Comment by totten** [comment]
Dank je, @eileenmcnaughton @kcristiano. Merging based on Kevin's testing.

**Pull request merged**
