### PR TITLE
ensure currency is included to avoid translation problems

### PR DESCRIPTION
**Pull request by jmcclelland**
See https://lab.civicrm.org/dev/core/-/issues/411

This is still a WIP since I'm not sure what extra steps I have to take when I make a message template change. Any suggestions appreciated!

Overview
----------------------------------------
Ensure that the correct currency is printed in the receipt when adding a payment or refund to a contribution that was made using a non-default currency.

Before
----------------------------------------

If you:

1. Make a contribution, then
2. Make a payment to that contribution using a currency that is not the default currency
3. And select to send a receipt

Then... 

The receipt prints the default currency instead of the actual currency used. 

After
----------------------------------------

The correct currency is printed on the receipt.

Technical Details
----------------------------------------

The message template used is the `payment_or_refund_notification`, which uses {$total|crmMoney} instead of {$total|crmMoney:$currency}. Since $currency is left off, the default currency is used.

Comments
----------------------------------------
I've never submitted a change to a message template - are there any extra steps needed for the upgrade process?

### CODE REVIEW

**Comment by demeritcowboy** [comment]
It would need civicrm_generated regenerated. If you're not set up to do that you can [run it online in your fork](https://github.com/civicrm/civicrm-core/blob/master/.github/workflows/regen.yml).

Then the only other step ([e.g. updating here](https://github.com/civicrm/civicrm-core/blob/902fc38d0d6cd9d09ee02f30cc6621747151a06a/CRM/Upgrade/Incremental/MessageTemplates.php#L327)) usually depends on whether it's something admins _have_ to do to keep the template working. I'd say in this case it isn't. If an admin hasn't already customized a template then they will get the update anyway.

**Comment by jmcclelland** [comment]
Hi @demeritcowboy - thanks for your help and sorry I disappeared! I'm back and trying to get this merged.

I tried to follow the directions to run regen online in my fork. But, I got stuck on "# 3. On the right you'll see a dropdown "Run workflow".

I don't see "Run workflow". The "..." menu only has the option: "Create status badge". Maybe a permissions issue? Here's a screen shot:

image

I also tried to run `bin/regen.sh` locally on my laptop and it completed without error. But it generated a new `package-lock.json` (which I presumably would not include) as well as a new `sql/civicrm_generated.mysql` which I presumably *would* include - except the new .mysql file has hundreds of changed lines in it. Is that normal?

**Comment by jmcclelland** [comment]
Thanks. I just committed the generated sql file.

In case you are interested in dummy-proofing the `regen` instructions I'm happy to continue contributing my ignorance :).

I first tried to run the regen action in my own repo, but I didn't see it listed on the left:

image

I guess I need to setup the regen workflow first by clicking that link and copying and pasting it in from the link?

**Comment by demeritcowboy** [comment]
Oh yeah I should add a step in there. This is the problem:

Untitled3

So just in a clean up-to-date git checkout of master, do `git push my-fork master`.

**Comment by jmcclelland** [comment]
Ah - thanks! That does the trick, no I see `regen` - thank you!!

**Comment by demeritcowboy** [comment]
I think this is mergeable. There's an edge-case where if the first payment is e.g. USD and then an additional payment is CAD, it doesn't put the correct currency, but (a) that's no different from before, and (b) this would be unusual.

**Pull request merged**
