### PR TITLE
CRM-20308: Activity copy is always sent FROM logged in user's email ID

### PR DESCRIPTION
**Pull request by monishdeb**
* [CRM-20308: Activity copy is always sent FROM logged in user's email ID](https://issues.civicrm.org/jira/browse/CRM-20308)

### CODE REVIEW

**Comment by monishdeb** [comment]
@ErikHommel please have a look at the final patch, and on the added unit test I have included two use-cases. 

@eileenmcnaughton @colemanw can you merge it if the patch looks ok?

**Comment by ErikHommel** [comment]
Happy @monishdeb , thanks!

**Comment by seamuslee001** [comment]
@monishdeb test failure is related

**Comment by monishdeb** [comment]
@eileenmcnaughton @colemanw  can you please merge this PR? This PR was created after 
1. Reviewing the PR https://github.com/civicrm/civicrm-core/pull/10104 and cherry-picked the commit in this PR.
2. Made additional changes and added Unit test.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 can you just check how this interacts with the work you did - fantastic to see a unit test. If there is overlap then we can merge & fix the overlap since both have tests?

**Review by seamuslee001 — APPROVED** [review]
Looks good to me and picks up the function i created @eileenmcnaughton

**Pull request merged**
