### PR TITLE
CRM-20301 - better output in search results

### PR DESCRIPTION
**Pull request by seancolsen**
* [CRM-20301](https://issues.civicrm.org/jira/browse/CRM-20301)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Just commenting tested this and works ping @totten @eileenmcnaughton

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@totten @eileenmcnaughton the test result here is unrelated and the fix makes sense to me

**Comment by eileenmcnaughton** [comment]
thanks @seamuslee001

**Pull request merged**
