### PR TITLE
dev/core#2550 Fix possible upgrade failures

### PR DESCRIPTION
**Pull request by colemanw**
Overview
------------------
Fixes the upgrade bug reported in https://lab.civicrm.org/dev/core/-/issues/2550

Before
----------------------------------------
Upgrade fails for 5.15 -> 5.36

After
----------------------------------------
This ought to fix it

Technical Details
----------------------------------------
This replaces #21984 with a more generic solution

### CODE REVIEW

**Comment by monishdeb** [comment]
@colemanw @eileenmcnaughton should I create a 5.43 rc PR for this and close #21996 ?

**Comment by colemanw** [comment]
@monishdeb can you confirm this patch fixes the bug?

**Comment by seamuslee001** [comment]
@colemanw I think monish did that in his comment here https://github.com/civicrm/civicrm-core/pull/21984#issuecomment-962633001

**Comment by colemanw** [comment]
Ok, in that case this can be merged and here is the backport PR: #21999

**Pull request merged**
