### PR TITLE
dev/wordpress#62 Update adrienrn/php-mimetyper gitignore file to ensu…

### PR DESCRIPTION
**Pull request by seamuslee001**
…re that sites that manage their systems using git can access the db.json file

Overview
----------------------------------------
This updates the gitignore file as per https://github.com/adrienrn/php-mimetyper/pull/15 I have tested this on a D8 build that we manage with git and confirm that i can now commit in the db.json file 

Before
----------------------------------------
If you manage your site with git the db.json file gets missed

After
----------------------------------------
db.json file doesn't get missed

ping @kcristiano @eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I can't think of any way to test this

**Comment by kcristiano** [comment]
My logic is to have  distmaker to create the tarballs with the PR applied.

The extract and inspect the `.gitignore` file.  

I've done this and it looks good.

**Comment by seamuslee001** [comment]
@kcristiano the problem with doing it via distmaker is that that only works for Drupal 7, WordPress, Joomla folks who manage using git, This doesn't solve it for those of us in D8 land who also manage our sites in git because composer will download from the source repo which has the problematic gitignore. Doing it this way ensures that it works for both D8 folks and also for distmaker because composer packages will apply this even in a d8 context

**Comment by eileenmcnaughton** [comment]
@kcristiano please merge this when you are satisfied

**Comment by seamuslee001** [comment]
@kcristiano I think i have mistook your comment about dismaker please disregard mine I think Kevin is saying he has applied and confirmed it works is that correct?

**Comment by kcristiano** [comment]
@seamuslee001 I apologize that was a bad comment.

I created a 5.28 tarball (same as the one you linked to in the issue - I missed that)

Added to my git repo via the build process and then pushed.  The new `.gitignore` works and the file can be committed.

This looks good to merge.

**Comment by seamuslee001** [comment]
Test fails unrelated merging

**Pull request merged**
