### PR TITLE
fixes dev/financial#187 - don't crash when displaying recurring contributions whose 'template' has no line items

### PR DESCRIPTION
**Pull request by MegaphoneJon**
RC version of https://github.com/civicrm/civicrm-core/pull/21719

### CODE REVIEW

**Comment by colemanw** [comment]
This is a simple enough change, and I like the premise of "don't crash".
Let's merge this and investigate the underlying problem after.

**Comment by demeritcowboy** [comment]
Was this intended to be against 5.42? I'm not sure what the procedure to update it is after merge. I'm thinking: revert, then do the 5.42, then merge forward?

**Comment by MegaphoneJon** [comment]
@demeritcowboy It was suggested this go in the RC, yes.

**Comment by demeritcowboy** [comment]
Ok have added https://github.com/civicrm/civicrm-core/pull/21734. I'm not sure if it will merge forward without reverting this but will find out.

**Pull request merged**
