### PR TITLE
CRM-16333 fix - Allow empty EntityRef values 

### PR DESCRIPTION
**Pull request by mollux**

### CODE REVIEW

**Comment by colemanw** [comment]
Hi, thanks for the PR. Can you describe the bug/problem you are working to solve?
A general note, the php `empty()` should be used with caution since "0" will be considered empty and this may be a valid option (admittedly this is unlikely in the case of entityRef which uses db ids but it's still a good practice to keep in mind).

**Comment by mollux** [comment]
I tried to explain the problem in the issue, but maybe it's not so well explained. So I will do another try at explaining :)

When I go to the Find participants form ( http://d46.demo.civicrm.org/civicrm/event/search ), and try to search all participants without searching for a specific event, I get an error:
'' is not a valid option for field id 
This is because the API call ( https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/Form/Renderer.php#L219 ) is called with an empty ID, which triggers the error. 

I think it has something to do with https://issues.civicrm.org/jira/browse/CRM-15803 , as that issue changed the is_array check in preProcessEntityRef.

The strange part is that I cant' reproduce it on the demo sites, only locally. IaAsked a friend to test the same thing, and he also gets the same error on his environment.

**Comment by colemanw** [comment]
Ok thanks I'll take a look.

**Comment by mollux** [comment]
The underlying issue is in the api call, which throws an error in my local version.

civicrm_initialize();
// mimic the same value as passed from the reference field.
$val = array();
$val[0] = '';
$params = array();
$result = civicrm_api3('event', 'getlist', array('id' => $val) + $params);

in the onApiPrepare_validate() method, _civicrm_api3_validate_fields() is called which checks if id is a valid integer in _civicrm_api3_validate_integer() , but this fails in _civicrm_api3_api_match_pseudoconstant() , as '' is not in the list of valid psuedoconstant values.

But the API exception isn't triggered on the demo version, but IMHO it should.

I don't know if I should discuss this here, or on the issue?

**Comment by mallezie** [comment]
I found a way to reproduce this and broke the http://d46.demo.civicrm.org/civicrm/event/search demo site in the proces (oops)
In the demo data there are 3 'NULL' events, if you delete those first, the issue is reproducable. (Id's 4 / 5 an 6, you can delete them through the api explorer)
The error is thrown by the function _civicrm_api3_api_match_pseudoconstant_value function

**Comment by mollux** [comment]
The null events are indeed why '' is a valid id for an event on the demo environments :) So the test data should be fixed too.

**Comment by colemanw** [comment]
Cool. Good catch. Which field in the event records is NULL?

**Comment by mallezie** [comment]
I think the title and / or event_title field, those are empty on id 4, 5 and 6. 
Seems those are not 'null' events but event_templates

**Comment by colemanw** [comment]
Gotcha.

**Comment by mollux** [comment]
Yes, the problem is the event getOptions api call, tha also returns the templates.
$result = civicrm_api3('Event', 'getoptions', array(
  'sequential' => 1,
  'field' => "id",
));

**Comment by mallezie** [comment]
To be even more specific, the issue is actually the following:
civicrm/event/search without any set params crashes. The only exceptions is when there is an event_template without en event_title,  then it does work.

**Comment by mollux** [comment]
I added a check to filter out the event templates when validating an event id. I think this is the only use case when templates should be filtered out (I used the Event BAO file to check), but I could be wrong.

**Comment by colemanw** [comment]
Hang on, something's not right here. The field event_id should not have a pseudoconstant declared.

**Comment by colemanw** [comment]
I've pinged @monishdeb about the schema change that triggered this bug. I think the right fix is to revert that change and that ought to resolve this issue.

**Comment by mallezie** [comment]
I'm not sure, but seems this https://github.com/civicrm/civicrm-core/pull/5676 is related?

**Comment by monishdeb** [comment]
@mallezie I have reverted the changes which was causing the the current pr to fail

**Comment by magnolia61** [comment]
Forgive me my confusion, but what would be the proper PR to test as a fix for the '' is not a valid option for field id - problem?

**Pull request closed without merging**
