### PR TITLE
Api4 - Set 'usage' property for custom fields

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Sets property for custom fields in APIv4 to be equivalent to core fields.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
this is great but I think we also need to exclude all 4 usages for custom_group_id.is_multiple = TRUE

**Comment by colemanw** [comment]
@eileenmcnaughton I think it is possible to import and export multirecord custom fields though.
Probably can't do duplicate matching with them. Not sure about tokens.

**Comment by eileenmcnaughton** [comment]
@colemanw yeah - there is a specific import for multi record fields but that wouldn't use the usage because I think the usage is more for 'can I import this field as part of the parent entity record'

**Comment by colemanw** [comment]
@eileenmcnaughton ok but multi-valued fields already aren't considered part of the parent record. APIv4 getfields doesn't return them.

**Comment by eileenmcnaughton** [comment]
@colemanw ah OK - I think it is good as is then

**Pull request merged**
