### PR TITLE
Removes default for is_active & is_reserved since they now have DB defaults

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Removes code default for is_active & is_reserved since they now have DB defaults
This is a follow up to https://github.com/civicrm/civicrm-core/pull/19281 
 Is deductible already had a default but it has been fixed so we can rely on it.

Before
----------------------------------------
Code adding a default value in the BAO

After
----------------------------------------
Relying on db default value

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
I suspect that `is_deductible` could be fine either way - which seems to be held up by a lack of issues regarding the field over the years.

It also seems like `is_deductible` is almost entirely ignored by the codebase - the exception is the contribution online receipt, and then only for premiums.

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon probably a reasonable take on it!

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by demeritcowboy** [comment]
I know that is_deductible is used by cdntax, but agree the schema default shouldn't matter. [The stock types](https://github.com/civicrm/civicrm-core/blob/e17b910eed798c71c129401fb47fe0ecf596ad3f/xml/templates/civicrm_data.tpl#L106-L112) would still have their values.

For required, that sounds ok as long as it doesn't then get used by forms automagically to make the checkbox required, which doesn't make sense for a single checkbox. I did a quick check and it seems ok.

**Comment by demeritcowboy** [comment]
jenkins test this please (some kind of date rollover problem)

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I've updated this such that the db default is 0 rather than 1 as per the form & the BAO on is_deductible,

@colemanw @seamuslee001 once this is merged I'll write the upgrade script for the schema changes in pledge & financial type in 5.34

**Comment by eileenmcnaughton** [comment]
update script in https://github.com/civicrm/civicrm-core/pull/19335

**Pull request merged**
