### PR TITLE
(dev/core#705) Disabling Alphabetical Pager is not respected for cont…

### PR DESCRIPTION
**Pull request by yashodha**
…ribution pages.

Overview
----------------------------------------
Steps to replicate :

Go to Admin > Search Preferences and turn off Include Alphabetical Pager

A to Z Pager is off for Find Contacts, Find Contributions, etc
However it is still shown on _Manage Contribution Pages_.

https://lab.civicrm.org/dev/core/issues/705

Before
----------------------------------------
Alphabetical Pager is visible on Manage Contribution Pages

After
----------------------------------------
Alphabetical Pager is not visible on Manage Contribution Pages

Comments
----------------------------------------
This is keeping it consistent with other selectors where Alphabetical Pager is already suppressed.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@yashodha I can see the consistency argument here - but I'm curious why users have requested this since the reason for turning off the pager is generally performance but that seems less applicable here

**Comment by yashodha** [comment]
@eileenmcnaughton 
It was not a performance issue but more a question of consistency since the expected behavior was the alphabetical pager will not be displayed on the search screens which it says on the screen as well.
atpz

**Comment by eileenmcnaughton** [comment]
I created & added a new 'easy-review' label as this just needs a r-run & I'm wondering if this will help me encourage other people test things like this

I'm happy with technical aspects of this - it makes sense

**Comment by francescbassas** [comment]
I tested it and it works as described.

**Comment by eileenmcnaughton** [comment]
thanks @francescbassas ! merging

**Pull request merged**
