### PR TITLE
dev/core#1827 activity search - fixing search by tags

### PR DESCRIPTION
**Pull request by samuelsov**
Overview
----------------------------------------
In activity search, filtering by tag is not working

Before
----------------------------------------
Peek 18-06-2020 17-13

After
----------------------------------------
The search is working as expected for one or multiple tags

Comments
----------------------------------------
First reported 10 months ago https://lab.civicrm.org/dev/core/-/issues/1173

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@samuelsov if this is a regression should it go against the rc?

**Comment by eileenmcnaughton** [comment]
I can't spot any recent related changes - but if you can figure out when it happened...

**Comment by demeritcowboy** [comment]
See also https://lab.civicrm.org/dev/core/-/issues/1173

**Comment by eileenmcnaughton** [comment]
@demeritcowboy OK thanks - master is fine then if the bug has been around for 10 months

I'm happy to merge this if someone tests it

**Comment by demeritcowboy** [comment]
On the test site here I'm getting

`Notice: Undefined offset: 0 in CRM_Activity_BAO_Query::whereClauseSingle() (line 299 of /home/jenkins/bknix-dfl/build/core-17655-3p5h9/web/sites/all/modules/civicrm/CRM/Activity/BAO/Query.php).`

which is a bit weird since line 299 is a blank line. Hmm.

**Comment by demeritcowboy** [comment]
Also it seems this then causes an issue for bare tags (i.e. tags not part of a tagset). And the description comes out as

"No matches found for:
Activity Status In Scheduled, Completed ...AND...
Activity targeted to ...AND...
Activity Tag = "

where the searched for tag description is missing.

**Comment by samuelsov** [comment]
Ok thanks, I will rework this

**Comment by eileenmcnaughton** [comment]
@samuelsov if it's going to be more than a couple of days maybe close & re-open?

**Comment by samuelsov** [comment]
Ok, I will reopen or create a new PR once it's reworked.

**Comment by samuelsov** [comment]
Simpler than before. Taglist are prepared just before (above) regular tag (no break in the switch case). I've manually tested both and it works fine except I've noticed that we can't do both type of tag filter in a single search. I suppose we would need to have a "OR" instead of a "AND" but clearly out of scope.

**Comment by demeritcowboy** [comment]
`r-run` looks good.

And yes I also see that you can't do both types of tags at the same time which is out of scope. In theory advanced search should let you do both by changing the "search operator" near the top to `OR`, and the word description in the results seems to come out correct but it still doesn't find them.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy I have it in my head that you wrote a test for this earlier?

**Comment by demeritcowboy** [comment]
I don't remember doing one and don't see one. I did one about the add/edit tag form but I don't think one for search.

**Comment by eileenmcnaughton** [comment]
Merging based on review by @demeritcowboy above and unit test by @demeritcowboy in #17755

**Pull request merged**
