### PR TITLE
Membership fee token fix dev/core/#377

### PR DESCRIPTION
**Pull request by sushantpaste**
Fixes for https://lab.civicrm.org/dev/core/issues/377 scheduled reminders.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire can you check this - looks similar to https://github.com/civicrm/civicrm-core/pull/12196 which you engaged in discussion (on the first cut)

**Comment by yashodha** [comment]
@eileenmcnaughton I have tested this and can confirm this works as expected.

**Comment by eileenmcnaughton** [comment]
@yashodha given the similarity to the other fix that seems like enough - I've given it the merge-ready flag just to give @mattwire a couple days to comment before it's merged

**Comment by yashodha** [comment]
@eileenmcnaughton sure

**Comment by mattwire** [comment]
Merging based on @yashodha testing and comments

**Pull request merged**
