### PR TITLE
Move 5.49 update to beta

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
@seamuslee001 @demeritcowboy @monishdeb I think this might be enough to ensure any alpha users (should they exist) get our further boolean updates?

### CODE REVIEW

**Comment by demeritcowboy** [comment]
I think this makes sense and r-run seems ok, except there's still one situation: I don't know what the expectation is about how much handholding people who upgrade to an alpha version need, but anyone who did so would then still have 1s in their is_public even after this. But I'm not sure how you would fix that anyway because you can't just set all the records to 0 since that's wrong too. On a new alpha install I think the expectation would just be to recreate the site fresh using beta, so it would just be upgrades to alpha to think about. Or the answer is "roll back to an earlier backup".

**Comment by eileenmcnaughton** [comment]
@demeritcowboy don't the nulls get set to zero in the upgrade?

**Comment by demeritcowboy** [comment]
The short answer is no.

1. Install 5.48, or something <5.49.
2. Upgrade to 5.49.alpha1 as it was when it was alpha1, e.g. 743e263c
3. For whatever reason, maybe due to some magic code somewhere regarding defaults, all the is_public's are 1.

**Comment by demeritcowboy** [comment]
Ok I see what it is. civicrm_menu gets completely rebuilt when you flush cache. Any routing xml that doesn't have `<is_public>true</is_public>` (e.g. [like this](https://github.com/civicrm/civicrm-core/blob/0fd2686e93f48def57f9ea8d30b4f5bef9c1ff90/CRM/Core/xml/Menu/Admin.xml#L674)) has it reset to the default, so when the default was 1, they all become 1. When it's 0, only the ones without that line become 1.

So I'm going to merge, and at least for the is_public I think we're good.

is_ssl should probably also have default 0, and is_exposed I can't find used anywhere, but neither seem to be breaking anything obvious.

**Comment by eileenmcnaughton** [comment]
thanks @demeritcowboy

**Pull request merged**
