### PR TITLE
Remove unused function getRecuringTransactionStatus from PayflowPro c…

### PR DESCRIPTION
**Pull request by seamuslee001**
…lass

Overview
----------------------------------------
This removes an unused function in PayflowPro which already has some issues with it

Before
----------------------------------------
Function existed by uncalled but could have issues

After
----------------------------------------
No function

ping @eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
screenshot 2018-06-11 09 40 33

@seamuslee001 can we also remove the 2 commented out references to this?

@yashodha I'm going to merge this but you might want to test afterwards since you guys are the only known user of PayflowPro

**Comment by seamuslee001** [comment]
@eileenmcnaughton i think you will find both of those comments are within the function its self

**Comment by eileenmcnaughton** [comment]
aha

**Comment by seamuslee001** [comment]
Merging as per the tag

**Pull request merged**
