### PR TITLE
CRM-20657: get all participant ids if multiple contacts register from…

### PR DESCRIPTION
**Pull request by jitendrapurohit**
… webform  https://issues.civicrm.org/jira/browse/CRM-20657

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
test this please

**Comment by colemanw** [comment]
@jitendrapurohit the test failures appear to be related.

**Comment by jitendrapurohit** [comment]
test passes now @colemanw

**Comment by monishdeb** [comment]
Tested, working fine.

**Comment by monishdeb** [comment]
Oops, accidentally closed :( Will merge once test build passes.

**Comment by monishdeb** [comment]
@jitendrapurohit in exchange can you please QA https://github.com/civicrm/civicrm-core/pull/10680 ?

**Pull request merged**
