### PR TITLE
CRM-16135

### PR DESCRIPTION
**Pull request by JoeMurray**

### CODE REVIEW

**Comment by colemanw** [comment]
add to whitelist

**Comment by JoeMurray** [comment]
I'm not sure what to make of the Parsing error: 'No report files were found. Configuration error?'

Let me know if there is something I need to do before this can be merged.

**Comment by davecivicrm** [comment]
Not sure what's up. Just pinged Tim.

**Comment by davecivicrm** [comment]
ok to test

**Pull request merged**
