### PR TITLE
dev/core#1620 - Add campaign_id to template for alterMailContent hook

### PR DESCRIPTION
**Pull request by scardinius**
Overview
----------------------------------------
described here https://lab.civicrm.org/dev/core/issues/1620

### CODE REVIEW

**Comment by mattwire** [comment]
For docs see https://github.com/civicrm/civicrm-dev-docs/commit/017a69bc68cd60a61de36bf88b301cf075de38e1 (template_type) I'm not sure why that's not in the published docs yet @MikeyMJCO ?

**Comment by totten** [comment]
(*CiviCRM Review Template WORD-1.2*)



* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __Pass__
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __Pass__: Does not change UX.
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __Soft Pass__: Agree with @mattwire; this would be good to document.
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __Not tested__
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __Pass__: Adds supplemental information. It's safe for existing listeners to ignore.
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __Pass__
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __Soft Pass__: AFAIK, there's no existing tests to check the data passing through `hook_civicrm_alterMailContent`. It would be better if we had some, but that's a preexisting debt.
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __Pass__: Reported test failure is a common false-negative.

**Comment by yashodha** [comment]
test this please

**Comment by yashodha** [comment]
@eileenmcnaughton We should merge this when tests pass.

**Comment by MikeyMJCO** [comment]
> For docs see [civicrm/civicrm-dev-docs@017a69b](https://github.com/civicrm/civicrm-dev-docs/commit/017a69bc68cd60a61de36bf88b301cf075de38e1) (template_type) I'm not sure why that's not in the published docs yet @MikeyMJCO ?

Docs issue has been resolved - sorry, I neglected to update this at the time!

**Comment by MikeyMJCO** [comment]
Docs PR is approved civicrm/civicrm-dev-docs#830

**Pull request merged**
