### PR TITLE
CiviUnitTestCase - Extract Api3TestTrait and Api3DocTrait

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------
This is a simple refactoring which moves several utility functions out of the base-class `CiviUnitTestCase` and into smaller traits, `Api3TestTrait` and `Api3DocTrait`.

Before
----------------------------------------
* `CiviUnitTestCase` is a 4000-line behemoth.

After
----------------------------------------
* `CiviUnitTestCase` is a 3600-line behemoth, which builds on `Api3TestTrait` and `Api3DocTrait`.
* Other PHPUnit tests can incorporate `Api3TestTrait` if they want to easily perform assertions about API calls.
* Other PHPUnit tests can incorporate `Api3DocTrait` if they want to easily perform assertions about API calls *and also make example files from the API call log*. (Personally, I don't expect to use `Api3DocTrait`, but it's better to move that bit to separate file.)

Comments
----------------------------------------
* I spot-checked a few tests locally to ensure they still pass.
* If the PR test passes, that's a pretty good sign that it works... considering that this refactoring is only test code.
* Additionally, it would be good to write a quicky extension with a test which uses `Api3TestTrait`.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@totten style issue

**Comment by totten** [comment]
Thanks. Fixed/squashed/pushed.

**Comment by eileenmcnaughton** [comment]
Added merge on pass - Jenkins is the only review that matters for this one

**Comment by seamuslee001** [comment]
Tests have passed and only affects unit tests merging

**Pull request merged**
