### PR TITLE
Update AuthSasl Net_SMTP and Net_Socket packages

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This updates the following packages:
 * Pear/auth_sasl from 1.1.0 to 1.2.0 - [diff](https://github.com/pear/Auth_SASL/compare/v1.1.0...v1.2.0)
 * Pear/net_smtp from 1.10.0 to 1.12.1 - [diff](https://github.com/pear/Net_SMTP/compare/1.10.0...1.12.1)
 * Pear/net_socket From 1.0.14 to 1.2.1 - diff(https://github.com/pear/Net_Socket/compare/1.0.14...v1.2.1)

@demeritcowboy @JoeMurray @eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
related or not? test this please

image

**Comment by demeritcowboy** [comment]
jenkins retest this please. I'm not sure it's related - the e2e tests seem randomly failing lately.

And oh look net_socket includes an update to make it php 5 compatible. Better late than never. https://github.com/pear/Net_Socket/commit/2dbc00842de647400a7413b96e83bdd303c2dff7

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Pull request merged**
