### PR TITLE
CRM-19710 - Preserve is_email_receipt parameter through to email sent

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
* [CRM-19710: Preserve is_email_receipt parameter through to email sent](https://issues.civicrm.org/jira/browse/CRM-19710)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@agileware I reviewed #9487 & kept the test & some lines, but I felt we could do better in terms of rationalising the logic. Note this probably does a bit less than yours did. I focussed on the tested flow, but the logic feels right to me - ie. when loadRelatedObjects is called set the detail of the contributionPage in the $_relatedObjects property & dip into that when needed. 

Plus, set the is_email_receipt in one place really explicitly, rather than all these interactions with it. Then extra logic can be added from the other functions.

Finally - I can't see that it is valid to call sendconfirmation with is_email_receipt not set to 1, that does not seem like it's intent, or the way in which it is called.

**Comment by eileenmcnaughton** [comment]
Note, I attributed the commit to you since you did the most important part, so, you'd better make sure you are happy with it.

**Comment by agileware** [comment]
@eileenmcnaughton looks good.  Thanks for following through with this!

**Comment by eileenmcnaughton** [comment]
ok I'll merge - would be great if you can test the rc once cut too

**Pull request merged**
