### PR TITLE
CRM-21813 : Parameter list mismatch

### PR DESCRIPTION
**Pull request by aniesshsethh**
Overview
----------------------------------------
A mismatch of parameter list result in a error 

Before
----------------------------------------
It's a AJAX error 

After
----------------------------------------
Ajax Error gone and execution continues 

Technical Details
----------------------------------------
Just 1 addition in the parameter list to match the footprint of the function.

---

 * [CRM-21813: Function parameter list mismatch doesn't allow save](https://issues.civicrm.org/jira/browse/CRM-21813)

### CODE REVIEW

**Comment by colemanw** [comment]
@civicrm-builder add to whitelist

**Comment by colemanw** [comment]
@aniesshsethh thank you and congratulations on your first Pull-Request to CiviCRM :tada: 

This looks good. One question: it looks like you are passing in the first price set value; I'm wondering what happens though if there is more than one?

**Comment by aniesshsethh** [comment]
@colemanw Thank you 

The thing is, since this function is only called in case of a event, I am not sure if more than one price sets are allowed. Please correct me if I am wrong, I am not experienced in civicrm.

**Comment by aniesshsethh** [comment]
@colemanw I have updated with another possible way

**Comment by eileenmcnaughton** [comment]
@aniesshsethh the final parameter ($discountedPriceFieldOptionID) is eventually optional if you look at how it's passed on. Since you have only replicated an error about it not being passed, not an error with it being passed, I would be inclined to just make it an optional parameter as the safest path - ie....

```
  public static function createDiscountTrxn($eventID, $contributionParams, $feeLevel, $discountedPriceFieldOptionID = NULL) {
```
I would notice that I feel like the event discount code has not been given a lot of attention recently & I would choose the safe path with it since I don't think anyone knows it well at the moment

**Comment by aniesshsethh** [comment]
@eileenmcnaughton understood, agreed and updated as such.

**Comment by eileenmcnaughton** [comment]
Thanks - this makes sense & should not result in functional change, merging.

Well done on the first PR

**Pull request merged**
