### PR TITLE
Request - Allow empty string or 0 as default values

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Makes it easier to fix notices.

Technical Details
----------------------------------------
When trying to solve some notice problems passing the output of this function into `trim()` I tried changing the default to an empty string but it didn't work due to this loosely-typed conditional.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
Test fail relates

```
CRM_Profile_Form_EditTest::testProfileUrl
Exception: CRM_Core_Exception: "getFieldValue failed"
#0 /home/homer/buildkit/build/build-2/web/sites/all/modules/civicrm/CRM/Activity/BAO/Activity.php(1787): CRM_Core_DAO::getFieldValue("CRM_Activity_DAO_Activity", 0, "original_id")
#1 /home/homer/buildkit/build/build-2/web/sites/all/modules/civicrm/CRM/Profile/Form.php(370): CRM_Activity_BAO_Activity::getLatestActivityId(0)
#2 /home/homer/buildkit/build/build-2/web/sites/all/modules/civicrm/CRM/Profile/Form/Edit.php(99): CRM_Profile_Form->preProcess()
```

**Comment by colemanw** [comment]
Ok this is just plain nuts. That form class was passing `0` as the default value, but relying on the bug for the default value to be ignored, because the form would error if it actually came back as `0` because it's checking if the result `is_numeric()`.
https://github.com/civicrm/civicrm-core/blob/f42a804c9666e77f9bdefc3a6ebee7c1f0a0f0c7/CRM/Profile/Form.php#L368-L369
Here are all the other places I could find where `CRM_Utils_Request::retrieve()` is called with a falsey default value which is getting ignored which may be a bug or may be preventing a bug depending on the code! (not a perfect grep, probably missing some but it found a lot):
```
Occurrences of `CRM_Utils_Request::retrieve\([^,)]+, [^,)]+, [^,)]+, [^,)]+, (0|FALSE|'')`

    CRM/Admin/Page  (1 usage found)
        ContactType.php  (1 usage found)
            39 $action = CRM_Utils_Request::retrieve('action', 'String', $this, FALSE, 0);
    CRM/Campaign/Form/Search  (3 usages found)
        Campaign.php  (1 usage found)
            44 $this->_force = CRM_Utils_Request::retrieve('force', 'Boolean', $this, FALSE, FALSE);
        Petition.php  (1 usage found)
            35 $this->_force = CRM_Utils_Request::retrieve('force', 'Boolean', $this, FALSE, FALSE);
        Survey.php  (1 usage found)
            35 $this->_force = CRM_Utils_Request::retrieve('force', 'Boolean', $this, FALSE, FALSE);
    CRM/Contact/Form  (3 usages found)
        DedupeFind.php  (1 usage found)
            42 $this->dedupeRuleGroupID = CRM_Utils_Request::retrieve('rgid', 'Positive', $this, FALSE, 0);
        DedupeRules.php  (2 usages found)
            47 $this->_rgid = CRM_Utils_Request::retrieve('id', 'Positive', $this, FALSE, 0);
            51 $contactType = CRM_Utils_Request::retrieve('contact_type', 'String', $this, FALSE, 0);
    CRM/Contact/Page  (5 usages found)
        DedupeFind.php  (5 usages found)
            69 $gid = CRM_Utils_Request::retrieve('gid', 'Positive', $this, FALSE, 0);
            70 $action = CRM_Utils_Request::retrieve('action', 'String', $this, FALSE, 0);
            74 $cid = CRM_Utils_Request::retrieve('cid', 'Positive', $this, FALSE, 0);
            118 $skippedCount = CRM_Utils_Request::retrieve('skipped', 'Positive', $this, FALSE, 0);
            120 $mergedCount = CRM_Utils_Request::retrieve('merged', 'Positive', $this, FALSE, 0);
    CRM/Contribute/Form  (2 usages found)
        ContributionView.php  (1 usage found)
            68 $force_create_template = CRM_Utils_Request::retrieve('force_create_template', 'Boolean', $this, FALSE, FALSE);
        Search.php  (1 usage found)
            399 $skip_cid = CRM_Utils_Request::retrieve('skip_cid', 'Boolean', $this, FALSE, FALSE);
    CRM/Contribute/Selector  (2 usages found)
        Search.php  (2 usages found)
            334 $qfKey = CRM_Utils_Request::retrieve('qfKey', 'String', CRM_Core_DAO::$_nullObject, NULL, FALSE, 'REQUEST');
            341 $qfKey = CRM_Utils_Request::retrieve('qfKey', 'String', CRM_Core_DAO::$_nullObject, NULL, FALSE, 'REQUEST');
    CRM/Core  (2 usages found)
        Invoke.php  (2 usages found)
            387 $config->cleanupCaches($sessionReset || CRM_Utils_Request::retrieve('sessionReset', 'Boolean', CRM_Core_DAO::$_nullObject, FALSE, 0, 'GET'));
            408 CRM_Utils_Request::retrieve('triggerRebuild', 'Boolean', CRM_Core_DAO::$_nullObject, FALSE, 0, 'GET')
    CRM/Core/Page  (1 usage found)
        Basic.php  (1 usage found)
            197 $id = CRM_Utils_Request::retrieve('id', 'Positive', $this, FALSE, 0);
    CRM/Event/Form  (2 usages found)
        SelfSvcTransfer.php  (1 usage found)
            140 $this->isBackoffice = (CRM_Utils_Request::retrieve('is_backoffice', 'String', $this, FALSE, FALSE, 'REQUEST') && CRM_Core_Permission::check('edit event participants')) ?? FALSE;
        SelfSvcUpdate.php  (1 usage found)
            113 $this->isBackoffice = (CRM_Utils_Request::retrieve('is_backoffice', 'String', $this, FALSE, FALSE, 'REQUEST') && CRM_Core_Permission::check('edit event participants')) ?? FALSE;
    CRM/Event/Form/ManageEvent  (1 usage found)
        ScheduleReminders.php  (1 usage found)
            73 $setTab = CRM_Utils_Request::retrieve('setTab', 'Int', NULL, FALSE, 0);
    CRM/Event/Page  (2 usages found)
        ManageEvent.php  (2 usages found)
            288 $createdId = CRM_Utils_Request::retrieve('cid', 'Positive', $this, FALSE, 0);
            452 $id = CRM_Utils_Request::retrieve('id', 'Positive', $this, TRUE, 0, 'GET');
    CRM/Financial/Page  (2 usages found)
        FinancialTypeAccount.php  (2 usages found)
            86 $id = CRM_Utils_Request::retrieve('id', 'Positive', $this, FALSE, 0);
            87 $this->_aid = CRM_Utils_Request::retrieve('aid', 'Positive', $this, FALSE, 0);
    CRM/Mailing/Page  (1 usage found)
        Browse.php  (1 usage found)
            142 $this->_createdId = CRM_Utils_Request::retrieve('cid', 'Positive', $this, FALSE, 0);
    CRM/Member/Form  (1 usage found)
        MembershipType.php  (1 usage found)
            135 $this->_id = CRM_Utils_Request::retrieve('id', 'Positive', $this, FALSE, 0);
    CRM/Profile  (3 usages found)
        Form.php  (3 usages found)
            341 $gids = explode(',', (CRM_Utils_Request::retrieve('gid', 'String', CRM_Core_DAO::$_nullObject, FALSE, 0) ?? ''));
            364 $this->_gid = CRM_Utils_Request::retrieve('gid', 'Positive', $this, FALSE, 0);
            368 $this->_activityId = CRM_Utils_Request::retrieve('aid', 'Positive', $this, FALSE, 0, 'GET');
    CRM/Profile/Page  (9 usages found)
        Dynamic.php  (1 usage found)
            152 $this->_activityId = CRM_Utils_Request::retrieve('aid', 'Positive', $this, FALSE, 0, 'GET');
        Listings.php  (3 usages found)
            83 $search = CRM_Utils_Request::retrieve('search', 'Boolean', $this, FALSE, 0, 'GET');
            91 $gids = explode(',', CRM_Utils_Request::retrieve('gid', 'String', CRM_Core_DAO::$_nullObject, FALSE, 0, 'GET'));
            111 $this->_gid = CRM_Utils_Request::retrieve('gid', 'Positive', $this, FALSE, 0, 'GET');
        MultipleRecordFieldsListing.php  (2 usages found)
            131 $action = CRM_Utils_Request::retrieve('action', 'String', $this, FALSE, FALSE);
            142 $this->_customGroupId = CRM_Utils_Request::retrieve('customGroupId', 'Positive', $this, FALSE, 0);
        Router.php  (1 usage found)
            45 $gids = explode(',', CRM_Utils_Request::retrieve('gid', 'String', CRM_Core_DAO::$_nullObject, FALSE, 0, 'GET'));
        View.php  (2 usages found)
            64 $gids = explode(',', CRM_Utils_Request::retrieve('gid', 'String', CRM_Core_DAO::$_nullObject, FALSE, 0, 'GET'));
            83 $this->_gid = CRM_Utils_Request::retrieve('gid', 'Positive', $this, FALSE, 0, 'GET');
    CRM/UF/Form  (2 usages found)
        Group.php  (1 usage found)
            91 $this->_id = CRM_Utils_Request::retrieve('id', 'Positive', $this, FALSE, 0);
        Preview.php  (1 usage found)
            35 $fieldId = CRM_Utils_Request::retrieve('fieldId', 'Integer', $this, FALSE, 0);
    tools/extensions/cividiscount/CRM/CiviDiscount/Form  (2 usages found)
        Admin.php  (2 usages found)
            21 $this->_id = CRM_Utils_Request::retrieve('id', 'Positive', $this, FALSE, 0);
            22 $this->_cloneID = CRM_Utils_Request::retrieve('cloneID', 'Positive', $this, FALSE, 0);
```

**Comment by eileenmcnaughton** [comment]
FWIW I use the much less used `retrieveValue` where I can - it doesn't do the form->set thing which is often unneeded. Since it has less usage it might be easier to fix in there?

**Comment by colemanw** [comment]
Yea I'm not going to keep digging into this quicksand.

**Pull request closed without merging**
