### PR TITLE
Add unit test for merge handling on custom data.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Primarily just adding a unit test but also moves the start & stop of the transaction to being further out so a hard fail
later doesn't leave a half-merged state

Before
----------------------------------------
Less tests

After
----------------------------------------
More tests

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
Stylechecker is grumpy

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 can you merge this - should be a no-brainer

**Comment by seamuslee001** [comment]
Changes seem to be fine, mostly in tests which Jenkins has oked and the shifting of the transaction seems fine

**Pull request merged**
