### PR TITLE
Bump DOMPDF to `~1.0.0`

### PR DESCRIPTION
**Pull request by homotechsual**
Having reviewed the changelogs and actual changes here https://github.com/dompdf/dompdf/releases and following a run-test on this I can't find any broken functionality as a result of this upgrade.

There are numerous fixes and improvements in this and the next planned version 1.0.3 will further improve SVG handling.

Overview
----------------------------------------
_Update DOMPDF from `~0.8` to `~1.0.0`._

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_Using the older `0.8.6` release of DOMPDF._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_Using the new `1.0.2` release of DOMPDF._

### CODE REVIEW

**Comment by seamuslee001** [comment]
@MikeyMJCO no update to the composer.lock file?

**Comment by MikeyMJCO** [comment]
Whoops!

**Comment by MikeyMJCO** [comment]
> @MikeyMJCO no update to the composer.lock file?

Done!

**Comment by seamuslee001** [comment]
I tested this on the PR test site all looks good to me merging

**Pull request merged**
