### PR TITLE
dev/core#5330 Fix regression on profile emails for free events

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/5330

dev/core#5330 Fix regression on profile emails for free events

Before
----------------------------------------
When a free event is configured with the profiles described in https://lab.civicrm.org/dev/core/-/issues/5330 the primary email is discarded in favour of the billing address

After
----------------------------------------
It is kept

Technical Details
----------------------------------------
Although this was reported as a regression from 5.70 I did not determine a mechanism - for some reason the `if` started working but the only relevant commit I found did not seem to have caused it https://github.com/civicrm/civicrm-core/commit/19e9a4fcdf7c850eaf141df0ac0abb6569e0ca22#diff-967d81007b3b773e9204a716773928529873c94f82bb21952845f1f1fdcd0255R1049

Comments
----------------------------------------

### CODE REVIEW

**Comment by pradpnayak** [comment]
On dmaster:
Screenshot 2024-07-03 at 22 56 52
Screenshot 2024-07-03 at 22 57 04


On [Online demo of this PR 🔗](http://site-list.test-1.civicrm.org/?filter=core-30609-*)

Screenshot 2024-07-03 at 22 58 23
Screenshot 2024-07-03 at 22 58 36


Primary email is not saved now

**Comment by totten** [comment]
FWIW, when I tried locally:

* __Process__:
    * Made a new free event
    * Reused the default profile for "Your Registration Info"
    * Made a new profile for "Billing Info" (*with just the email address*)
* __Before-patch__: Same problem as reporter. (Two copies of the same address recorded.)
* __After-patch__: Both addresses were recorded. But the "is_primary" flag was placed on the second address ("Individual: Email (Billing)")  rather than the first address ("Individual: Email (Primary)").

If that problem was the only problem, then I think it would be OK to merge. (It's better than status-quo.) But it sounds like there may be another issue (per @pradpnayak's testing).

**Comment by pradpnayak** [comment]
Hi @totten 

I did the same fields as you did http://core-30609-5jrjo.test-1.civicrm.org:8001/civicrm/event/register?reset=1&id=3&cid=0

**Comment by totten** [comment]
@pradpnayak @eileenmcnaughton  Thanks. I think I found where the test-procedures differed. In "Manage Event > XXX > Online Registration", there's the option for "Confirmation Screen":

* On PR site, it had the "Confirmation Screen disabled" (i.e. one-page registration). In this mode, it has the bug -- it loses one of the email addresses. 

    Actually, FWIW, the "Confirmation Screen" config looks weird:

    Screen Shot 2024-07-03 at 6 47 17 PM

* On my local, it had the "Confirmation Screen" enabled (i.e. two-page registration).
    
    Screen Shot 2024-07-03 at 6 49 38 PM

     In this mode, it does record both emails (*albeit with a switheroo on the `is_primary` flag*).

* On my local, when I switched to one-page registration, it started to give the bug.

**Comment by seamuslee001** [comment]
so I think this condition in processRegistration in CRM_Event_Form_Registration might be screwy

```
        CRM_Event_Form_Registration_Confirm::fixLocationFields($value, $fields, $this);
        //for free event or additional participant, dont create billing email address.
        if (empty($value['is_primary']) || !$this->_values['event']['is_monetary']) {
          unset($value["email-{$this->_bltID}"]);
        }
 ```

**Comment by eileenmcnaughton** [comment]
@seamuslee001 yeah - I think we should remove that second portion of the if - I will push that up if you agree  - the is_primary is a bit marginal as in the profile context it would apply to the relevant participant but in billing context to only the primary participant so I'd be inclined to leave it unless we prove it is not needed for multiple participant

**Comment by totten** [comment]
After, re-testing with an eye on the "Confirmation Screen" radio, I don't see the current patch making any difference in the outcome. It looks to me like:

* With 5.69, 5.75-head, or 5.75+patch, the runtime processing leads to the same outcomes.
* The driver is whether the confirmation screen is enabled/disabled.
    * If enabled, then I can record both emails.
    * If disabled, then I can only record one email.
* However, the behavior *feels* worse on 5.75 because the GUI for "Confirmation Screen"  screen widget is flaky/disappear-y on 5.75. (On 5.69, I find it easier to flip that option off+on.)

**Comment by eileenmcnaughton** [comment]
@totten does altering the line @seamuslee001 highlighted make a difference?

**Comment by totten** [comment]
> However, the behavior feels worse on 5.75 because the admin GUI for configuring "Confirmation Screen" is flaky/disappear-y on 5.75.

Coarse bisect points toward 5.72 as being the place where the config screen got screwy. 

> does altering the line @seamuslee001 highlighted make a difference?

@eileenmcnaughton OK, if I'm reading correctly, your comment seems to suggest this patch:

```diff

diff --git a/CRM/Event/Form/Registration.php b/CRM/Event/Form/Registration.php
index f83cff879d..f21aac9a09 100644
--- a/CRM/Event/Form/Registration.php
+++ b/CRM/Event/Form/Registration.php
@@ -1762,7 +1762,7 @@ class CRM_Event_Form_Registration extends CRM_Core_Form {

         CRM_Event_Form_Registration_Confirm::fixLocationFields($value, $fields, $this);
         //for free event or additional participant, dont create billing email address.
-        if (empty($value['is_primary']) || !$this->_values['event']['is_monetary']) {
+        if (empty($value['is_primary'])) {
           unset($value["email-{$this->_bltID}"]);
         }
```

I don't *think* so. But honestly, we're juggling so many versions+configs, it's hard to be sure.

**Comment by eileenmcnaughton** [comment]
@totten yeah - it makes sense that applying the patch per your comment would prevent the billing address from being lost in the no-confirm flow since that line it specific to that flow & not the one that works

**Comment by eileenmcnaughton** [comment]
I just retested this & with the test discussed above we do wind up with both the billing & primary emails stored - which is not the case without the patch - however the is_primary is on the wrong one. This appears to be a clear improvement but not a full fix

image

**Comment by vingle** [comment]
> However, the behavior feels worse on 5.75 because the admin GUI for configuring "Confirmation Screen" is flaky/disappear-y on 5.75

In case this is linked to the changes [here in 5.72](https://github.com/civicrm/civicrm-core/blob/5f6c091b9de486fd84bcc0a28554e269c05f8dd5/templates/CRM/Event/Form/ManageEvent/Registration.tpl#L197) two suggestions 
- removing the conditional `{if !$defaultsEmpty}open{/if}` and just putting `open` – because if that minor UI change fixes it then we know the culprit. 
- removing `collapsible-title` class from the `<summary>` as that was kept in only in the interests of simplicity. But it's not needed any more, and [has some JS targeting it](https://github.com/civicrm/civicrm-core/blob/5f6c091b9de486fd84bcc0a28554e269c05f8dd5/js/Common.js#L1704).

**Comment by totten** [comment]
Just noting what I mentioned on MM - after testing the combined patch, I did get much better results for the runtime problem (*i.e. mis-filing of email addresses*). 👍 

(That still leaves the config-time problem that @vingle is discussing.)

Process-wise, PR fell into an awkward spot (*getting caught up into the 5.75-rc at last minute while having somewhat tenuous/fluid case re:regressionness*). But I do favor merging a fix. Opened a parallel PR for 5.76-(new-rc) to forward-port (#30619).

**Pull request merged**
