### PR TITLE
Fix #2377 role_id is treated as a number instead of string

### PR DESCRIPTION
**Pull request by webmaster-cses-org-uk**
Update formulation of database query to use REGEXP instead of IN() to successfully match multi-valued fields and prevent database error otherwise.

Overview
----------------------------------------
This PR proposes a code fix to resolve https://lab.civicrm.org/dev/core/-/issues/2377 (role_id is treated as a number instead of string).

Before
----------------------------------------
The SQL query produced by this section of the code looks like the following:
```sql
SELECT e.contact_id as contact_id, e.id as entity_id, "civicrm_participant" as entity_table, 43 as action_schedule_id
FROM civicrm_participant e
INNER JOIN civicrm_event r ON e.event_id = r.id
INNER JOIN civicrm_contact c ON c.id = e.contact_id AND c.is_deleted = 0 AND c.is_deceased = 0 
LEFT JOIN civicrm_action_log reminder ON reminder.contact_id = e.contact_id AND
reminder.entity_id          = e.id AND
reminder.entity_table       = 'civicrm_participant' AND
reminder.action_schedule_id = 43
WHERE (e.role_id IN (1)) AND (r.id IN ("346")) AND (r.is_active = 1) AND (r.is_template = 0) AND (e.status_id IN (1)) AND (reminder.id IS NULL) AND (DATEDIFF(DATE('20210918110510'),'2021-09-18') = 0)
```

If a record has multiple participant_roles, which is perfectly valid, a database error like the following occurs, and the scheduled email does not send:
```
Sep 18 23:35:09  [error] $Fatal Error Details = Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => exceptionHandler
        )

    [code] => -1
    [message] => DB Error: unknown error
    [mode] => 16
    [debug_info] => INSERT INTO civicrm_action_log (contact_id, entity_id, entity_table, action_schedule_id)
SELECT e.contact_id as contact_id, e.id as entity_id, "civicrm_participant" as entity_table, 43 as action_schedule_id
FROM civicrm_participant e
INNER JOIN civicrm_event r ON e.event_id = r.id
INNER JOIN civicrm_contact c ON c.id = e.contact_id AND c.is_deleted = 0 AND c.is_deceased = 0 
LEFT JOIN civicrm_action_log reminder ON reminder.contact_id = e.contact_id AND
reminder.entity_id          = e.id AND
reminder.entity_table       = 'civicrm_participant' AND
reminder.action_schedule_id = 43
WHERE (e.role_id IN (1)) AND (r.id IN ("346")) AND (r.is_active = 1) AND (r.is_template = 0) AND (e.status_id IN (1)) AND (reminder.id IS NULL) AND (DATEDIFF(DATE('20210918233509'),'2021-09-18') = 0)
 [nativecode=1292 ** Truncated incorrect DOUBLE value: '1\00013']
    [type] => DB_Error
    [user_info] => INSERT INTO civicrm_action_log (contact_id, entity_id, entity_table, action_schedule_id)
SELECT e.contact_id as contact_id, e.id as entity_id, "civicrm_participant" as entity_table, 43 as action_schedule_id
FROM civicrm_participant e
INNER JOIN civicrm_event r ON e.event_id = r.id
INNER JOIN civicrm_contact c ON c.id = e.contact_id AND c.is_deleted = 0 AND c.is_deceased = 0 
LEFT JOIN civicrm_action_log reminder ON reminder.contact_id = e.contact_id AND
reminder.entity_id          = e.id AND
reminder.entity_table       = 'civicrm_participant' AND
reminder.action_schedule_id = 43
WHERE (e.role_id IN (1)) AND (r.id IN ("346")) AND (r.is_active = 1) AND (r.is_template = 0) AND (e.status_id IN (1)) AND (reminder.id IS NULL) AND (DATEDIFF(DATE('20210918233509'),'2021-09-18') = 0)
 [nativecode=1292 ** Truncated incorrect DOUBLE value: '1\00013']
    [to_string] => [db_error: message="DB Error: unknown error" code=-1 mode=callback callback=CRM_Core_Error::exceptionHandler prefix="" info="INSERT INTO civicrm_action_log (contact_id, entity_id, entity_table, action_schedule_id)
SELECT e.contact_id as contact_id, e.id as entity_id, "civicrm_participant" as entity_table, 43 as action_schedule_id
FROM civicrm_participant e
INNER JOIN civicrm_event r ON e.event_id = r.id
INNER JOIN civicrm_contact c ON c.id = e.contact_id AND c.is_deleted = 0 AND c.is_deceased = 0 
LEFT JOIN civicrm_action_log reminder ON reminder.contact_id = e.contact_id AND
reminder.entity_id          = e.id AND
reminder.entity_table       = 'civicrm_participant' AND
reminder.action_schedule_id = 43
WHERE (e.role_id IN (1)) AND (r.id IN ("346")) AND (r.is_active = 1) AND (r.is_template = 0) AND (e.status_id IN (1)) AND (reminder.id IS NULL) AND (DATEDIFF(DATE('20210918233509'),'2021-09-18') = 0)
 [nativecode=1292 ** Truncated incorrect DOUBLE value: '1\00013']"]
)
```
Note the `[nativecode=1292 ** Truncated incorrect DOUBLE value: '1\00013']"]` MySQL error.

After
----------------------------------------
SQL code produced now looks like the following:
```sql
SELECT e.contact_id as contact_id, e.id as entity_id, "civicrm_participant" as entity_table, 43 as action_schedule_id
FROM civicrm_participant e
INNER JOIN civicrm_event r ON e.event_id = r.id
INNER JOIN civicrm_contact c ON c.id = e.contact_id AND c.is_deleted = 0 AND c.is_deceased = 0 
LEFT JOIN civicrm_action_log reminder ON reminder.contact_id = e.contact_id AND
reminder.entity_id          = e.id AND
reminder.entity_table       = 'civicrm_participant' AND
reminder.action_schedule_id = 43
WHERE (e.role_id REGEXP "(^|)(1)(|$)") AND (r.id IN ("346")) AND (r.is_active = 1) AND (r.is_template = 0) AND (e.status_id IN (1)) AND (reminder.id IS NULL) AND (DATEDIFF(DATE('20210921222407'),'2021-09-21') = 0)
```
Emails send as expected including to participants with multiple participant_role values.

Comments
----------------------------------------
Tested and working stably on our CiviCRM installation (up to 5.37.0 so far) but no unit test case specifically developed (yet) for this scenario.

### CODE REVIEW

**Comment by colemanw** [comment]
@webmaster-cses-org-uk thanks for this PR - a unit test would be super helpful. Are you able to add one? It could build upon existing tests of the search code.

**Comment by jaapjansma** [comment]
@webmaster-cses-org-uk we are reviewing PR's and we went through a couple of long outstanding PR's. We want to review this PR however we are not sure how we can replicate the issue and see whether your fix works. Can you give us a step by step instruction on we can do this as a user?

**Comment by demeritcowboy** [comment]
This has merge conflicts.

**Comment by eileenmcnaughton** [comment]
closing for now due to the merge conflicts - this might be otherwise fixed (with a test) recently

**Comment by webmaster-cses-org-uk** [comment]
> @webmaster-cses-org-uk we are reviewing PR's and we went through a couple of long outstanding PR's. We want to review this PR however we are not sure how we can replicate the issue and see whether your fix works. Can you give us a step by step instruction on we can do this as a user?

Apologies for radio silence - I have been delivering charity events virtually full-time for the last couple of months! How to reproduce this step-by-step:
1. Assign multiple participant roles to an event participant (e.g. in our case "Attendee" and "Volunteer").
2. Create a scheduled reminder for the event that includes either or both of the assigned participant roles.
3. Send the reminder (either wait for cron or use "Execute Now" feature of Scheduled Jobs).
4. Script crashes with error message: "Truncated incorrect DOUBLE value"

As a part-time volunteer who also happens to be chair of trustees currently (!!) I have only very limited time to spend on IT and web development, so haven't yet had the opportunity to learn how to set up and run unit tests and currently can't offer one yet. Apologies for that.

Nonetheless, Eileen suggests this may have been fixed by other means?

**Comment by eileenmcnaughton** [comment]
@webmaster-cses-org-uk  this is the PR that caused the merge conflict - https://github.com/civicrm/civicrm-core/pull/23602 - it looks like it might be addressing the same issue?

**Comment by webmaster-cses-org-uk** [comment]
@eileenmcnaughton Thanks, yes this looks like it fixes the same issue (using the same technique). Have added comment to https://lab.civicrm.org/dev/core/-/issues/2377, which I think we can now close.

**Comment by eileenmcnaughton** [comment]
Great - thanks for checking

**Comment by eileenmcnaughton** [comment]
It looks to me like your patch was the starting point for the other patch - hence the similarity :-)

**Pull request closed without merging**
