### PR TITLE
dev/core#2909 - Repair the option value label for nb_NO language

### PR DESCRIPTION
**Pull request by christianwach**
Overview
----------------------------------------
Follow on from #21813 that tries to repair the label on upgrade to 5.44.beta1

Comments
----------------------------------------
@demeritcowboy Sorry, haven't tested this but assume that following the schema in other upgrade files works here.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Thanks. I'm just going to try editing the base branch here to put it against 5.44. Since it just branched the PR shouldn't need rebasing.

**Comment by demeritcowboy** [comment]
Ah nope it does need rebasing to be against 5.44.

**Comment by demeritcowboy** [comment]
Tested and the upgrade works for me. So this just needs a rebase.

**Comment by christianwach** [comment]
> Tested and the upgrade works for me.

@demeritcowboy Phew :) PR is now against 5.44.

**Comment by demeritcowboy** [comment]
Thanks, looks good!

**Pull request merged**
