### PR TITLE
crm-17125 add contact billing address when no contribution address

### PR DESCRIPTION
**Pull request by mallezie**
https://issues.civicrm.org/jira/browse/CRM-17125

### CODE REVIEW

**Comment by davecivicrm** [comment]
Tim - can you take a look at these test failures. Seems like they might be related to this PR.

**Comment by mallezie** [comment]
this should at least fix some failures, not sure i've got them all. I need to be able to run the tests locally first.

**Comment by davecivicrm** [comment]
Tim - I confirmed that the test regressions are related to this PR.

**Comment by davecivicrm** [comment]
@mallezie Rechecked one of the new test failures, running the best with this PR and without it (on latest master checkout)  - https://test.civicrm.org/job/CiviCRM-Core-PR/5910/testReport/junit/%28root%29/api_v3_ContributionTest/testCompleteTransactionWithReceiptDateSet/

Confirmed  that this test failure (and likely the others) are related to this PR.

Also, would be good to explain (in a comment) why you've changed the getValues function in CRM/Core/BAO/Address.php to grab billing address first. Is this function not used for any other purpose?

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by monishdeb** [comment]
Jenkin, test this please

**Comment by monishdeb** [comment]
Closed in favor of https://github.com/civicrm/civicrm-core/pull/8123

**Pull request closed without merging**
