### PR TITLE
Bump minimum upgradable version to 4.4.7

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
CiviCRM v4.4. was [released back in 2013](https://civicrm.org/blog/colemanw/civicrm-44-is-here). How time flies! This PR bumps the minimum upgradable version from 4.2.9 to 4.4.7.

Before
----------------------------------------
Technically possible to upgrade from 4.2 (although probably not a good idea).

After
----------------------------------------
Now you must be on at least 4.4.7 to upgrade (which is not *quite* as ancient).

Technical Details
----------------------------------------
Although there were other releases in the 4.4 LTS series, none of them contained any schema changes or upgrade steps; 4.4.7 is the last release to modify the schema in that series, which is why I picked that version as the minimum.

Comment
---------
I've also added an update to the documentation: https://github.com/civicrm/civicrm-sysadmin-guide/pull/253

### CODE REVIEW

**Comment by colemanw** [comment]
@totten would you be able to do a little maintenance on the upgrade tests so this can pass jenkins? It's time to cull old test DBs < 4.4.7 and probably generate a new multilingual DB to replace the one from 4.2.

**Comment by eileenmcnaughton** [comment]
I think it's time.... @MikeyMJCO asked the right questions on the docs PR

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@colemanw error now is 

```
Smarty error: unable to read resource:                                 [warning]
&quot;/home/jenkins/bknix-dfl/build/core-17750-4l4r8/web/sites/all/modules/civicrm/CRM/Upgrade/Incremental/sql/4.4.7.mysql.tpl&quot
```

**Comment by colemanw** [comment]
That's strange. Why would a 4.5 upgrade be trying to access a 4.4 upgrade file?
Looks like there's more info at `/home/jenkins/bknix-dfl/build/core-17750-4l4r8/.civibuild/debug/4.5.0-setupsh.sql.bz2.log` on the server. I'm having trouble logging into the jenkins box - are you able to open that file?

**Comment by seamuslee001** [comment]
@colemanw the reason is because of https://github.com/civicrm/civicrm-core/blob/master/CRM/Upgrade/Incremental/php/FourSix.php#L130

**Comment by colemanw** [comment]
Thanks @seamuslee001, good detective work. I've added that sql file back in.

**Comment by seamuslee001** [comment]
Merging now that tests have passed

**Comment by colemanw** [comment]
Thanks @seamuslee001 for seeing it through!

**Pull request merged**
