### PR TITLE
dev/core#1818 Upgrade AngularJS from 1.5.11 to 1.8

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Upgrades the AngularJS library while maintaining backward-compatibility with existing Angular code.

See https://lab.civicrm.org/dev/core/-/issues/1818

Before
----------------------------------------
Angular v1.5.11

After
----------------------------------------
Angular v1.8

Technical Details
----------------------------------------
The biggest breaking change between 1.5 and 1.8 was the default hashPrefix.
See https://github.com/angular/angular.js/blob/master/CHANGELOG.md#location-due-to-1

The solution is to force `crmApp` to default to the old prefix. This ensures that existing modules which rely on `crmApp` for routing (which is nearly all of them) will be unaffected.

The only module I know of that manages its own routing without `crmApp` is Afform. Since that extension is so new, this PR updates it to use the new default prefix since that's recommended by Angular going forward.

### CODE REVIEW

**Comment by seamuslee001** [comment]
@colemanw test fails look related 

```
crmCaseType.crmCaseType CaseTypeListCtrl deleteCaseType when the case type cannot be delted displays the error message
crmCaseType.crmCaseType crmAddName when initialized updates the UI with updated value of scope variable
```

**Comment by demeritcowboy** [comment]
>
> Remove problematic tests
>

I haven't read the release notes but ... curious?

**Comment by colemanw** [comment]
There were two failing tests after upgrading Angular. I looked into them and manually checked what they were supposed to be testing. I found that the UI is still working fine, so the problem is with the test itself. After discussing with the rest of the CT I decided to simply remove the tests because they are problematic for a number of reasons and not covering much of anything.

**Comment by demeritcowboy** [comment]
Ok thanks. I clicked around a little on the civicase admin screens. Didn't look at afform.

I don't know if I exactly agree about the tests but agree they aren't super-important.

**Comment by seamuslee001** [comment]
needs a rebase @colemanw

**Comment by colemanw** [comment]
Unrelated fail

**Comment by seamuslee001** [comment]
I'm going to merge this based on @demeritcowboy 's review and that this will get in the next RC so we will have a month to test it

**Pull request merged**
