### PR TITLE
Dompdf fails on chrome to download

### PR DESCRIPTION
**Pull request by pradpnayak**
Unable to print/merge document from Find Activity search on chrome or firefox

Before
----------------------------------------
Screen Shot 2020-09-29 at 13 21 17

After
----------------------------------------
Able to download pdf

### CODE REVIEW

**Comment by michael-chaplin-gmcvo** [comment]
I have seen this. Print/merge from a Contact action seems unaffected.

**Comment by eileenmcnaughton** [comment]
@pradpnayak is it a regression?

**Comment by demeritcowboy** [comment]
I can't reproduce this on chrome or firefox? Is there something specific about the activity or the print/merge template? Can you give a couple steps? I tried Find - Search Activities, picked a meeting, then put tokens for activity id, subject, details, then downloaded. PDF looks ok?

**Comment by michael-chaplin-gmcvo** [comment]
I have tried several existing sites on 5.28.x and a new install of 5.29.1.
I tried Find - Search Activities, picked a meeting then downloaded but the page crashes just after the "downloading" message in the top RH corner.
On dmaster demo 5.31.alpha1 this worked OK.

**Comment by eileenmcnaughton** [comment]
@michael-chaplin-gmcvo do you think it's fixed i 5.31 (which is in rc now) or is it something environmental?

**Comment by eileenmcnaughton** [comment]
I just tried again to replicate this & failed - @pradpnayak I'm going to close this out based on issues replication (& it being stale).

I did hit another issue that I will investigate but it's not directly related

**Pull request closed without merging**
