### PR TITLE
dev/core#4487 Alternative option: Fix paymentBlock url concat

### PR DESCRIPTION
**Pull request by larssandergreen**
Overview
----------------------------------------
Alternate for #27031. I think this is little more readable and maintainable.

Before
----------------------------------------
Funky JS plus Smarty concatenation breaks if additional URL params are present

After
----------------------------------------
Less funky concatenation. Also simplified the ampersand situation a bit.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I like the idea of the & before not after - makes sense - will see if @sebalis can check it out

**Comment by sebalis** [comment]
I’ve looked at the way this PR solves the issue and I like it much more. This file is now in use on our productive 5.58.1 instance and I’ve verified that contributions work with and without the extra URL parameter (language=en). Of course by using this file I have also inherited the other changes made since 5.58.1, which mainly seem to be QA plus extra checks with a condition called isBackOffice, and I hope that this won’t break anything if it’s used in 5.58.1 – a question unrelated to this PR, admittedly, but if you have any comment I’d be glad to know, otherwise I’ll risk it. In any case, please merge this PR (I have already closed mine) while still allowing me to be credited as a contributor; seems fair to me as I pointed out the issue and where it needed to be solved. ;-)

**Comment by larssandergreen** [comment]
Thanks @sebalis. I think you're probably OK with the new version of the file, since the changes are just reducing PHP warnings, but no promises.

Sorry, this was merged before I saw your note, so I can't add you as a co-author any more.

**Comment by sebalis** [comment]
Many thanks for the advice about the file, @larssandergreen – and not to worry, it seems that the contributor’s credit issue has been very kindly taken care of :-)

**Pull request merged**
