### PR TITLE
send group subscription welcome email only if template is enabled

### PR DESCRIPTION
**Pull request by kurund**
Fixes: https://lab.civicrm.org/dev/core/-/issues/3162

### CODE REVIEW

**Comment by jaapjansma** [comment]
test this please

**Comment by jaapjansma** [comment]
* General standards
    * Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
        * __PASS__ : The goal/problem/solution have been adequately explained in issue.
    * User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
        * __PASS__: The change would be intuitive or unnoticeable for a majority of users who work with this feature.
    * Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
        * __PASS__: The changes do not require documentation.
    * Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
        * __ISSUE__: We did test this in the test environment of this PR. Everything seems to work. However the test environment has `CIVICRM_MAIL_LOG` defined so we are not able to test whether the e-mail gets send or whether it returns in an error.
* Developer standards
    * Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
        * __PASS__: The change preserves compatibility with existing callers/code/downstream.
    * Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
        * __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
    * Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
        * __PASS__: The change is trivial enough that it does not require tests.
    * Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
        * __PASS__: The test results are all-clear.

@kurund do you think there is any risk with merging this without testing the actual mail?

**Comment by kurund** [comment]
@jaapjansma 

I have tested with actual mailings and it is working as expected.

**Comment by jaapjansma** [comment]
@eileenmcnaughton or @colemanw can of you merge this PR? We believe it is safe to merge this.

**Pull request merged**
