### PR TITLE
CRM-17660 - Missin "Littoral" and "Nord-Ouest" provinces in Cameroon

### PR DESCRIPTION
**Pull request by saurabhbatra96**
https://issues.civicrm.org/jira/browse/CRM-17660

### CODE REVIEW

**Comment by seamuslee001** [comment]
@saurabhbatra96 I think you also need to update civicrm_generated.mysql in the sql folder as well and also add in the sql job to the beta2 upgrade file CRM/Upgrade/incremental/sql/4.7.beta2.mysql.tpl

**Comment by yashodha** [comment]
@saurabhbatra96 You should add the upgrade SQL in 4.7.beta3.mysql.tpl

**Comment by saurabhbatra96** [comment]
Thanks! Should be fixed now.

**Comment by yashodha** [comment]
@saurabhbatra96 Could you please rebase your PR?

**Comment by saurabhbatra96** [comment]
@yashodha Hmm. I tried rebasing it and even re-doing the PR. Still showing merge conflicts. Any suggestions?

**Pull request merged**
