### PR TITLE
CRM_17474 standardise address field addition to other reports

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
This also adds add extra address fields to participant listing such as
address_name & county

(This is a follow on to the original patch on this)

### CODE REVIEW

**Comment by colemanw** [comment]
+5 -55
:+1:

**Comment by eileenmcnaughton** [comment]
finally I didn't let my bad habits (comment blocks & tests) stand in the way of a good score!

**Comment by JKingsnorth** [comment]
I second coleman's comment, nice.

**Comment by davecivicrm** [comment]
Test failure unrelated.

**Comment by davecivicrm** [comment]
Nice one !

**Pull request merged**
