### PR TITLE
(dev/cloud-native#3) SerializeCache - Remove unused, incomplete cache-driver

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

The class `CRM_Utils_Cache_SerializeCache` provides a cache-driver for
storing cache records in the filesystem (under `CIVICRM_TEMPLATE_COMPILEDIR`,
using PHP `serialize()` format). Why remove it?

1.  As we work through cleanup in file management (e.g.  #12843,
   dev/cloud-native#3), having an unnecessary reference to
   CIVICRM_TEMPLATE_COMPILEDIR makes it harder to reason about the system.

2. The class is not used. I'm pretty sure it was added speculatively
   (i.e.  with an aim to try using it some day), but that never came to
   pass.  Grepping `universe`, I cannot find any usages or references to
   `SerializeCache`.

3. The implementation is incomplete -- parameters like `get(..., $default)`
   and `set(..., $ttl)` will generate exceptions if used.

Before
----------------------------------------

* Driver exists and is not used.

After
----------------------------------------

* Driver does not exist.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@totten test failure looks like server needs a kick

**Comment by eileenmcnaughton** [comment]
I agree with your analysis - I did a couple of further checks

1) checked that no functional commits had taken place on the file since it was brought over from svn (it did get some changes as part of various cleanups & stdisations but none that suggest it was targetted)
2) searched for a 'Serialize' (case sensitive) in case it was being concatenated in the core code base
3) checked the references to cache options in civicrm.settings.template.php

I feel comfortable this can be removed & we can stop 'fixing it' to meet standards

**Comment by totten** [comment]
jenkins, test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Pull request merged**
