### PR TITLE
Add icons to top-level navigation menu

### PR DESCRIPTION
**Pull request by colemanw**
Overview
--------
Title and screenshot says it all.

screenshot from 2018-09-27 15-42-52

### CODE REVIEW

**Comment by colemanw** [comment]
@kcristiano can you test this on a new install? I've tested the upgrade script but haven't tried installing it from scratch.

**Comment by kcristiano** [comment]
@colemanw The icons do not show on install for both WP and Drupal 7.   This was tested with both a buildkit install and a tarball created via distmaker/civihydra.

However, the expected sql is in sql/civicrm_navigation.sql so I am unsure why this fails.   If I force an upgrade the icons then appear as expected.

**Comment by seamuslee001** [comment]
@colemanw i think you need to do ./bin/regen.sh to ensure the changes get into the civicrm_generated sql

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by colemanw** [comment]
Thanks for the inspiration and the review @kcristiano!

**Comment by seamuslee001** [comment]
@civicrm-builder re test this please

**Comment by seamuslee001** [comment]
test fails unrelated

**Pull request merged**
