### PR TITLE
Add str_starts_with modifier to Smarty

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Add str_starts_with modifier to Smarty

Using str_starts_with like this  will work on Smarty2 / 3 already but needs this to work on Smarty4 / Smarty5 without notices

Before
----------------------------------------
We use `|substr` in a handful of  places in the template layer in core & contact layout editor. It is used in this way in all cases... (ie looking for str_starts_with). In Smarty4 all php functions must be registered or notices will appear

After
----------------------------------------
You can tell it's working cos we get brand new notices when we display the form with phone & im

image

Technical Details
----------------------------------------
@colemanw definitely prefers str_starts_with over substr....

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I just pushed up the notice fix - you can see home address has a both for extension 


image

**Comment by eileenmcnaughton** [comment]
And one last notice on ThankYou 

image

**Comment by colemanw** [comment]
@eileenmcnaughton does this mean the contact layout editor needs to be updated?

**Comment by eileenmcnaughton** [comment]
@colemanw yep - but it can be updated even before this patch is merged - str_contains_str will already work in Smarty 2 & 3 (& noisily in 4)

**Pull request merged**
