### PR TITLE
avoid variable leakage on recurring contribution receipts

### PR DESCRIPTION
**Pull request by jmcclelland**
See https://lab.civicrm.org/dev/core/issues/35

Overview
----------------------------------------
This bug happens if you have more than one iATS recurring contribution and an earlier contribution is assigned to a soft credit, but one or more later contributions are not assigned to a soft credit.

The later contributions have the soft credit information inserted into their receipt because the email message template variables are not properly cleared.

iATS processes multiple recurring contributions in a single session via a cron job, so may be uniquely triggering this error (although the bug is with CiviCRM Core).

Before
----------------------------------------
Some (seemingly at random) recurring contribution receipts are sent out in which donors are credited with honoring people they have never heard of.

After
----------------------------------------
Receipts only honor people if the donor intended to honor them.

Technical Details
----------------------------------------
Most payment processors process each recurring contribution independently of each other - so there is no leakage of template variables.

However, since iATS processes them in one batch, we run into this error.

### CODE REVIEW

**Comment by jmcclelland** [comment]
Hi @KarinG and @adixon - this isn't in fact an iATS bug... but iATS may uniquely trigger it. Have you experienced this behavior? Wondering if you think this is the right fix.

**Comment by eileenmcnaughton** [comment]
@jmcclelland seems a bit risky TBH since some vars are assigned earlier I believe :-( If we HAD consolidated fully on that function it would be ok.

There is an existing attempt re assigning vars in 

CRM_Contribute_BAO_ContributionPage::sendMail & the way to test variables is in CRM_Core_Payment_AuthorizeNetIPNTest::testIPNPaymentMembershipRecurSuccessNoLeakage

**Comment by adixon** [comment]
Eeeks - loading that template without any clarity about what's already assigned in it sounds scary.

The simple alternative would be to unassign soft_credit_type and honor_block_is_active in an else clause after line 2931, which would make sense if you're assuming a pre-populated template.

**Comment by eileenmcnaughton** [comment]
Right there are few ways to fix this & there might be some personal preference involved - the most important part of this fix is the unit test

**Comment by jmcclelland** [comment]
Thanks for the tips on writing tests - I will work on that.

In addition to @adixon's more conservative suggestion... another option might be to clear the template variables at the end of the function rather than the beginning. 

I'll see what I can come up with.

**Comment by jmcclelland** [comment]
I just made a mess of this PR. Started over: https://github.com/civicrm/civicrm-core/pull/11966

**Comment by eileenmcnaughton** [comment]
note that the new PR is #12175 (& per comments there I will only keep it open for 2-3 weeks & close & track in gitlab if you are not able to re-review it)

**Pull request closed without merging**
