### PR TITLE
[Import] Output errors, duplicates csvs directly from the user job table

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
[REF] [Import] Output errors, duplicates csvs directly from the user job table

Before
----------------------------------------
During parsing the errors and duplicate-skips are output to a csv file

After
----------------------------------------
The csvs are generated on demand from the import temp table using a url like

/civicrm/import/outcome?user_job_id=5&status=4&reset=1

Note that this means
1) only the user that did the import can access the output file
2) the file can be re-accessed until the job is cleaned up - at this stage the UI doesn't offer a way to re-visit it but the url can be re-visited

Technical Details
----------------------------------------
Handling of import outcomes was inconsistent - the download mechanism for the rows that were not updating the csv is the next task

Most commits in this PR are also in other open PRs - only the last 1 is new to this PR - requires a menu./rebuild

Comments
----------------------------------------
I found the summary screen confusing - total rows was total rows less those that were already rejected in the Preview screen - that seemed confusing to me so it now reflects the total number of rows - I think it might still be a little odd until I get everything updating in the table

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
unrelated fail

image

**Comment by eileenmcnaughton** [comment]
It only failed on the known error but test this please cos I'm going for the green tick

**Comment by monishdeb** [comment]
Reviewed the patch, that fulfilling all the checks. Posting the detail shortly

**Comment by eileenmcnaughton** [comment]
@monishdeb thanks! - I totally agree re re-visiting - defintely something I hope to get to

**Pull request merged**
