### PR TITLE
[php8.2]  compliant ajax method for custom data on pledge form

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Use php8.x compliant ajax method for custom data on pledge form

Before
----------------------------------------
The pledge form is loading custom data in a way which is not php8.2 compliant & calls 3 toxic functions to do so

After
----------------------------------------
The Custom data is loaded by ajax. I ensured that it works with other currency separators in the process (hence the odd ampersands)

image

Technical Details
----------------------------------------
I tested on both new & edit

Comments
----------------------------------------

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
Deleting a pledge results into a database error after this change.

image

Perhaps, `$this->_id` should be replaced with `getPledgeId()` at https://github.com/civicrm/civicrm-core/blob/master/CRM/Pledge/Form/Pledge.php#L415?

**Comment by eileenmcnaughton** [comment]
thanks @jitendrapurohit I didn't realise delete would be affected - I just pushed up to use `getPledgeID()` in all the places ->_id is referenced

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit I also put up https://github.com/civicrm/civicrm-core/pull/29701 to address that screed of red notices I saw

**Review by jitendrapurohit — APPROVED** [review]
Have completed r-run and and everything appears to be good during testing 👍

**Comment by eileenmcnaughton** [comment]
thanks @jitendrapurohit  - merging based on your review

**Pull request merged**
