### PR TITLE
CRM-15656 joomla time zone

### PR DESCRIPTION
**Pull request by spalmstr**
- [CRM-15656: Synchronize PHP and MySQL time zones](https://issues.civicrm.org/jira/browse/CRM-15656)

### CODE REVIEW

**Comment by spalmstr** [comment]
CRM-15656 - Handle Joomla time zone issues.  There will also be a pull request in the civicrm-joomla repository.  These PRs attempt to deal with the issue when the time zones in MySQL, PHP and Joomla are different by using the Joomla time zone.

**Comment by spalmstr** [comment]
Merge branch failed, so closing pro tem.

**Comment by spalmstr** [comment]
I don't know what the Merge Branch failure means.  Drilling down into the error yields this:

No report files were found. Configuration error?

**Comment by eileenmcnaughton** [comment]
I'm closing this because Monish did an alternate pull request - please test the 4.7.10 rc release when it comes out

**Pull request closed without merging**
