### PR TITLE
CRM-21225: Added a new field, Profile Title so that the Profile Name does not serve a dual purpose of labelling the Profile and displaying the Title for the Profile fields publicly.

### PR DESCRIPTION
**Pull request by agilewarealok**
Overview
----------------------------------------
Add a new field, Profile Title so that the Profile Name does not serve a dual purpose of labelling the Profile and displaying the Title for the Profile fields publicly.

The use case is when you want a Profile to have a name which is used internally and describes how the profile is being used but want to use a different title when the profile is embedded on a contribution, event etc.

eg. "Top secret donors" = Profile Name, versus "Enter your donation details" = Profile Title
Agileware Ref CIVICRM-506

Before
----------------------------------------
Profiles had only single field to show internally and publicly.

After
----------------------------------------
Now profiles have name as well as title, we are using display title for displaying the Title for the Profile fields publicly.

_Agileware Ref: CIVICRM-506_

---

 * [CRM-21225: CIVICRM-506 Add a new field, Profile Title so that the Profile Name does not serve a dual purpose of labelling the Profile and displaying the Title for the Profile fields publicly](https://issues.civicrm.org/jira/browse/CRM-21225)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Hi @jusfreeman There are a few issues here 1. the xml file changes aren't included nor are the changes to sql/civicrm_generate.sql also doing upgrade testing i was finding that this wasn't properly adding the fields in multilingual situation. It also showed a bug in the code as well. I have addrsssed all the issues here https://github.com/seamuslee001/civicrm-core/commit/0a4bb57577

**Comment by jusfreeman** [comment]
Thanks @seamuslee001 I'll ask @agilewarealok to review.

**Comment by JoeMurray** [comment]
I'm in favour of this schema change. I haven't reviewed patch.

**Comment by jusfreeman** [comment]
@seamuslee001 any idea why the build is failing for this PR? The link to the build report is broke.

**Comment by seamuslee001** [comment]
@jusfreeman i think it may have been conflict or something. I have started work on getting the schema changes through as needed here https://github.com/civicrm/civicrm-core/pull/11503

**Comment by jusfreeman** [comment]
@seamuslee001 great thanks, will you be able to manage this PR to final merge? Or do we need to do more stuff with it?

**Comment by seamuslee001** [comment]
@jusfreeman i'll try and manage this one through, there was some chatter on the isssue on MM this morning to resolve the naming of the new column which should be done now

**Comment by totten** [comment]
Discussed this a bit on Mattermost with Eileen and Seamus. On general principle, I agree there's utility in splitting apart the profile `title` used for backend/admin forms (like "Edit Event" or "Edit Contribution Page") and the profile `title` used for frontend/standalone profiles. That could potentially be accomplished by splitting off a new field for the backend titles or frontend titles, and (if I'm interpreting correctly) I think this makes the right call in splitting off the frontend titles. (There are fewer pages/use-cases that would need to be updated.)

Those comments aren't a full review, though -- a full review would, e.g., need to `r-run` it and examine the fallback/transition paths for existing data.

**Comment by jusfreeman** [comment]
@seamuslee001 thanks mate, appreciated.

@totten we weren't really thinking of changing all backend/admin forms, just dealing with the profile use case. Wary of expanding the scope too much and putting noses out of joint. The original issue description, use case is what we're trying to solve here.

I'll leave this one in your respective safe hands :)

Thanks!

**Comment by agilewarealok** [comment]
Closing this one as similar PR(https://github.com/civicrm/civicrm-core/pull/11508) is merged into master.

**Pull request closed without merging**
