### PR TITLE
dev/core#4960 Make Case menu link in relationship tab conditional

### PR DESCRIPTION
**Pull request by ejegg**
Only add the link when CiviCase is enabled

Fixes: https://lab.civicrm.org/dev/core/-/issues/4960

Overview
----------------------------------------
Fix a regression stopping the Relationship tab from loading active relationships when CiviCase not active

Before
----------------------------------------
On 5.70, deactivate CiviCase and load the relationship tab of a contact with active relationships. The active relationships do not load and an ajax call returns with http status 500

After
----------------------------------------
Relationship tab loads normally whether CiviCase is active or not

### CODE REVIEW

**Comment by colemanw** [comment]
Thanks @ejegg can you rebase this for the 5.70 branch?

**Comment by colemanw** [comment]
Looks perfect! Thanks @ejegg

**Comment by ejegg** [comment]
Seems like an unrelated test fail: api_v3_ContributionTest.testSendConfirmationPayLater

**Comment by colemanw** [comment]
Our test infra is having a bad day.

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by colemanw** [comment]
retest this please

**Pull request merged**
