### PR TITLE
Extract code for getting additional return properties, test

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Extract code for getting additional return properties, test

Before
----------------------------------------
Code jumbled

After
----------------------------------------
Code less jumbled

Technical Details
----------------------------------------
@jitendrapurohit this should address the re-ordering issue you spotted.

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
@eileenmcnaughton There is a related warning about the return statement removal in Activity.php file.

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit ug. Actually I have a couple more commits locally. I might add them in. It will be more change so harder to review but less testing overall - you prefer I add before you review? I've extracted more of the getReturnProperties & added more tests

**Comment by jitendrapurohit** [comment]
hmm, yes, would like to review it as a whole 👍

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit OK - I'm gonna be chipping away for a while - but I'll grow this PR a bit

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit I added some more commits. It looks like a lot of code change now but each commit should be self-contained.

This feels like a sensible 'set' because all the changes relate to setting $returnProperties when $fields is NULL (ie. export 'Primary fields') rather than specifying the output fields

**Comment by eileenmcnaughton** [comment]
In my defence - there are 430 extra test lines - the score is not fair

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit I added two more commits - but it's 600 lines of unit tests & 3 lines of code removal

https://github.com/civicrm/civicrm-core/pull/12505/commits/da6fabade4bdb65d310ebab812e60a2969f3ec18 - to fix an enotice blocking the test - pretty sure the removal would not have a negative impact & the 'case' var would never be set as the $queryFields comes from the query object & is very standard

**Comment by jitendrapurohit** [comment]
@eileenmcnaughton Tested on all the export components, contacts, membership, activities, cases, etc and the functionality looks correct. Also tested by inserting some debug statements and checked the values of different variables($returnProperties, etc) before and after the changes and they seem fine in all cases. Can conclude that this is safe to be merged 👍

**Review by jitendrapurohit — APPROVED** [review]

**Comment by eileenmcnaughton** [comment]
Added merge on pass based on @jitendrapurohit testing - thanks heaps!

Just rebased it so will check tests before merging

**Pull request merged**
