### PR TITLE
dev/core#4928 - smarty3 filenames generated by singleUseString are invalid on windows

### PR DESCRIPTION
**Pull request by spalmstr**
Overview
----------------------------------------
This helps to resolve issue https://lab.civicrm.org/dev/core/-/issues/4928 where event registration crashed under Windows due to file name errors.

Before
----------------------------------------
We got errors like:
```SmartyException: "unable to write file <Drupal root>\web\sites\default\files\civicrm\templates_c\en_GB\c3\0d\eb\c30deb6712dca60a591491c1b9b34a88872d619f_0.string.{eval var=$smartySingleUseString|smarty:nodefaults}.php"``` because the file name contained illegal characters for file names under Windows.

After
----------------------------------------
We were able to register for an event.

Technical Details
----------------------------------------

We replace ```string:``` with ```eval:``` in line 1040 of ```<drupal root>\vendor\civicrm\civicrm-core\CRM\Utils\String.php```

Comments
----------------------------------------
Thanks for helpful suggestions in StackExchange.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Thanks for the PR. In the [previous PR](https://github.com/civicrm/civicrm-core/pull/28909/files#diff-5a429c6ee446ea34fcc58e2cf1e84a8befea3239e8519ebe59b32d335761b836R233) there are guards around the call so that it works in both smarty2 and smarty3. We might need to do something similar but different (call `string:` if smarty2, `eval:` if smarty 3). Not sure if that determination should really be in CRM_Core_SmartyCompatibility - the one above might predate it.

Another note is that in the other PR performance wasn't really an issue. It might be more important here but probably not too much.

**Comment by spalmstr** [comment]
The new title is better. I've change the code so it tests for Windows as the first PR failed some tests, presumably because they run under Linux.

**Comment by demeritcowboy** [comment]
Thanks @spalmstr . Are you able to [squash commits](https://docs.civicrm.org/dev/en/latest/tools/git/#rebasing-interactive) and then I think it's mergeable.

**Comment by spalmstr** [comment]
I tried to squash the commits by following the instructions given in the link above.

**Comment by demeritcowboy** [comment]
Did you do a `git push -f` at the end? It doesn't seem updated here?

**Comment by spalmstr** [comment]
I ended up using the instructions for TortoiseGit at the bottom of this link:  [[How do I squash my last N commits together?](https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together)](url). I think we now just have one commit.

**Pull request merged**
