### PR TITLE
CRM-19118 Fix Syntax Confromance test by specifiy data for children a…

### PR DESCRIPTION
**Pull request by seamuslee001**
…nd parent fields when generating test data

### CODE REVIEW

**Comment by seamuslee001** [comment]
@totten this is an alternate to my other PR, goes along the line we discussed of setting test value

**Comment by totten** [comment]
This PR aims to fix a symptom that Jenkins structurally wouldn't identify (i.e. running `api_v3_SyntaxConformanceTest::testCustomDataGet` without a `templates_c` folder). However, I can confirm that it fixes the symptom for me.

It's also arguably NFC because the change is limited to the tests.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton looks like the failure is related to a PR of yours recently

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by totten** [comment]
I don't think this PR is cause of the failures -- they seem to random based on something that slipped in earlier. Notes:
 * In two runs on Jenkins, `api_v3_JobTest` had failures -- but different ones. https://test.civicrm.org/job/CiviCRM-Core-PR/10822/ (testBatchMergeEmailHandling) vs https://test.civicrm.org/job/CiviCRM-Core-PR/10823/ (testBatchMergeIDRange). 
 * Running locally, I've seen times where everything passed, where `testBatchMergeIDRange` failed, and where `testBatchMergeMatchingAddress`
 * Running locally, the same phenomena occur on `master` (if you fix the sytnax-error like bf2e078 does).

Given that the syntax error fixed in bf2e078 is going to block proper test runs, I think it's important to merge.

**Pull request merged**
