### PR TITLE
CRM-17213 add tests for group search

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
This test ensures we don't break the group search while fixing CRM-17213

---
- [CRM-17213: Manage Groups time outs due to CRM-16483](https://issues.civicrm.org/jira/browse/CRM-17213)

---
- [CRM-16483: Fix search builder to accept all operators with contact groups](https://issues.civicrm.org/jira/browse/CRM-16483)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
CRM-17123 further removal of damaging OR query.
Note that in testing this I checked
1) searching in search builder with groups as a criteria
(checked that correct groups show & only 'Added' ones)
2) Exporting  - groups show per above when selected as an export field
3) Groups tab on a contact correctly shows added & removed groups
4) Api calls per tests
5) Manage groups - clicking through shows correct status for all members and it is possible to alter the group criteria to include 'Removed' and they show with the correct status

**Comment by eileenmcnaughton** [comment]
@seamuslee001 this is probably the most important patch in performance to QA - it provides a resolution to the group performance issue that would otherwise block ahem 'certain sites' upgrading to 4.7...

**Comment by seamuslee001** [comment]
Just noting have done some manual tests against a pretty oldish smart group created with search builder, previous situation it would time out on me when running query. Now it comes back perfect. Just also noting that the group_id value was '(400)' It was correctly selected in the search builder form however in the quill it was group(s) in (400) I would have expected the qill to translate to the group title not the raw value. However performance much much improved

**Comment by eileenmcnaughton** [comment]
@seamuslee001 let me know when you feel it is OK to merge. As I mentioned in https://github.com/civicrm/civicrm-core/pull/8645#issuecomment-230605640 I tried to think of all the places where the way in which group title is rendered would make a difference. I have also deployed this live on one site

**Comment by seamuslee001** [comment]
Attaching screenshot of where qill isn't properly translated 
group title not correctly converted

**Comment by eileenmcnaughton** [comment]
I could not create a group that did this - but I am aware from Seamus this is a legacy group. I notice in the legacy group form values there are braces around the group number - ie 

value";a:3:{i:1;a:5:{i:0;s:0:"";i:1;s:5:"(400)";

- would changing it to value";a:3:{i:1;a:5:{i:0;s:0:"";i:1;s:**3:"400";**

change it?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I'm going to merge this as the only issue you found is minor & affects legacy groups & then tackle that in a separate PR if that's OK with you? We have another PR that has already started to conflict with this one so it would be good to get these changes in since they are mostly tested & QAd

**Comment by seamuslee001** [comment]
@eileenmcnaughton merge away

**Pull request merged**
