### PR TITLE
Logging - If valid, then set a locale

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

This is an updated variation of @seamuslee001's #27974, with two key differences:

1. It calls `setLocale()` one time -- from within `createDebugLogger()`. (This becomes an internal detail of how `createDebugLogger()` builds the instance. You don't need to sprinkle it into the log-consuming code.)
2. It calls `setLocale()` conditionally -- if the method actually exists. It's not certain whether the method will ultimately be part of the official `pear/log` releases.  (*And once upstream changes, it may immediately affect D9/D10-style builds.*) This change means that civicrm-core should with `pear/log` in either contingency.

Before
----------------------------------------

* ~~Log file locale is en_US~~
* Log file locale is based on some system default (which may not always be reliably operational)

After
----------------------------------------

* Log file locale is what is set in CiviCRM

### CODE REVIEW

**Comment by demeritcowboy** [comment]
I can check it.

Another way to help drupal 9 is not link to the HEAD of the pear-log PR in composer.json and link to a specific commit there. Then that PR can change without affecting anything right away.

Sidenote: I think in the original PR description it's a typo - the issue isn't that locale is en_US, it's that it's "C" or something that php 8.1.25 no longer thinks is valid (type `php -r "echo setlocale(LC_ALL, 0);"` to see what it thinks).

**Comment by totten** [comment]
> I think in the original PR description it's a typo ... it's that it's "C" or something that php 8.1.25 no longer thinks is valid...

Aah, OK. Updated description.

**Comment by totten** [comment]
> (@demeritcowboy) Another way to help drupal 9 is not link to the HEAD of the pear-log PR in composer.json and link to a specific commit there. Then that PR can change without affecting anything right away.

That makes sense. @seamuslee001 also agreed on MM. It should pin both (a) the base version of `pear/log` and (b) the patch-file on top of `pear/log`. The `requires` constraint is already a specific version. For the PR URL, I rerolled it as a "gist" URL that should be pretty immutable. (*In the face of an evolving branch, I have a bit more confidence in the gist remaining constant.*)

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by totten** [comment]
One part of the test got interrupted. Requested re-run of that part (https://test.civicrm.org/job/CiviCRM-Manual-Test/106/, pending)

**Comment by totten** [comment]
Merging based on prior test-run (*which was all green, save one interruption*) and supplemental test-run (*for the interrupted part*).

**Comment by wmortada** [comment]
I just wanted to check does this fix https://lab.civicrm.org/dev/core/-/issues/4739 ?

**Comment by demeritcowboy** [comment]
Yes. It can be applied to 5.66 too just doesn't apply cleanly so needs to be manually applied.

**Pull request merged**
