### PR TITLE
dev/core#562 Remove free calls from Activity and Member sections of CRM

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This removes uneeded calls to DAO Free function which has been shown to hurt performance

https://lab.civicrm.org/dev/core/issues/562

ping @eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 Jenkins doesn't like your style

**Comment by eileenmcnaughton** [comment]
Per the gitlab this is part of an ongoing cleanup effort - we are deliberately staggering it over several releases (although we are feeling pretty confident by now).

Merge on pass

**Comment by seamuslee001** [comment]
@eileenmcnaughton jenkins has too much sass

**Comment by seamuslee001** [comment]
Merging as per the tag

**Pull request merged**
