### PR TITLE
Change Administer > Communications > Label Formats to Label Page Formats

### PR DESCRIPTION
**Pull request by larssandergreen**
Overview
----------------------------------------
This has tripped me up so many times while looking for Mailing Label Format (the one where you choose which fields appear on the mailing label itself, which is part of Localization > Address Settings).

Change is for new installs only.

Before
----------------------------------------
Administer > Communications > Label Formats

After
----------------------------------------
Administer > Communications > Label Page Formats
Description updated as well.

### CODE REVIEW

**Comment by totten** [comment]
Yeah, I definitely ow "Label Formats" is a confusing. Wordsmithing can be tricky.  "Page" can be interpreted to web-page or printed-page. A few more ideas:

* "Printed Label Formats"
* "Printing Formats"
* "Printer Layouts"

**Comment by larssandergreen** [comment]
@totten I think we need something that indicates it isn't the labels themselves, but the page format that we are talking about.

**Comment by totten** [comment]
If you used a generic office tool - like MS Word or LibreOffice - what the equivalent option be called?

**Comment by larssandergreen** [comment]
@totten Word calls this "Label Options" but you're already in the label making context. For Libre Office, it's similarly contextual.
There's a Google Sheets extension that uses "Label Templates" (but again, in context).

**Comment by demeritcowboy** [comment]
Maybe instead add a link to the other page on each page? e.g.

* On the label formats page: "For choosing the fields that appear on the label, visit `[Address Settings]`."
* On the address settings page: "For available label formats, visit `[Label Formats]`."

**Comment by totten** [comment]
> Word calls this "Label Options" but you're already in the label making context. For Libre Office, it's similarly contextual.
> There's a Google Sheets extension that uses "Label Templates" (but again, in context).

OK, so they do all retain the phrase "Label". (I was thinking about the "Page Setup" links -- but I never actually used those tools to generate labels...)

Anyway, this seems as-clear-or-better than the old, and it's close enough to the old that the `r-user` impact should be OK. Let's give it a go.

**Comment by larssandergreen** [comment]
Thanks @totten. I've added a follow up with @demeritcowboy's suggestion to link between the two forms.

**Pull request merged**
