### PR TITLE
CRM-20573, fixed notice error

### PR DESCRIPTION
**Pull request by pradpnayak**
----------------------------------------
* CRM-20573: User deprecated function: Deprecated function on View Participabt form
  https://issues.civicrm.org/jira/browse/CRM-20573

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Cool - that should reduce it from 3 queries to 1 in each of those instances. Did you load the forms or do it just based on the code (if the former then I'm happy to merged based on that since it is a simple change)

**Comment by eileenmcnaughton** [comment]
Gosh - it is a bit of copy & paste tho huh? All those lines on each form exactly the same

**Comment by pradpnayak** [comment]
Yeah, the notices came up when i was on
1. New/Edit Participant form
2. Viewed participant registration
3. Participant Batch update

**Comment by eileenmcnaughton** [comment]
ok - merged

**Pull request merged**
