### PR TITLE
[REF] CustomField Admin - Decouple page code from form code

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
This moves the forms for creating/editing/previewing/deleting custom data to their own url paths instead of sharing the same path as the page.

Before
----------------------------------------
For no good reason, the forms were sharing the same url as the page, with an extra `action` param in the url. When the page loaded, it would check if e.g. `action=delete` in which case it would go through a bunch of extra steps to embed the delete form and run it within the page. The page template then had to include a bunch of extra conditionals to load the form template.

After
----------------------------------------
Just give the forms their own url and remove all the unnecessary special handling in the page and the template.

Comments
----------------------------------------
I'd really like to know why anyone ever thought this pattern was a good idea. It adds a bunch of extra complexity with no benefit I can think of.

### CODE REVIEW

**Comment by monishdeb** [comment]
@colemanw I encountered a few issues on Custom Field add/edit page: 

1. When I click on the 'Edit' action against any custom field it gives me a fatal error: 
Screenshot 2022-01-21 at 5 12 46 PM

2.  In this screencast below the default values were not loaded on edit screen: 
before

3. In the screencast above I encounter a fatal error in simply submitting an edit form or while adding a custom field. Backtrace : 
```
an 21 11:47:18  [error] 
$Fatal Error Details = array:3 [
  "message" => "One of parameters  (value: ) is not of the type Integer"
  "code" => null
  "exception" => CRM_Core_Exception {#618
    -errorData: array:1 [
      "error_code" => 0
    ]
    #cause: null
    -_trace: null
    #message: "One of parameters  (value: ) is not of the type Integer"
    #code: 0
    #file: "/Users/monish/src/civicrm-core/CRM/Utils/Type.php"
    #line: 469
    trace: {
      /Users/monish/src/civicrm-core/CRM/Utils/Type.php:469 {
        ›   $data = htmlentities($data);
        ›   throw new CRM_Core_Exception("$name (value: $data) is not of the type $type");
        › }
      }
      /Users/monish/src/civicrm-core/CRM/Core/DAO.php:1731 { …}
      /Users/monish/src/civicrm-core/CRM/Core/DAO.php:1695 { …}
      /Users/monish/src/civicrm-core/CRM/Custom/Form/Field.php:521 { …}
      ```

**Comment by colemanw** [comment]
@monishdeb I tried but was unable to reproduce the problem you encountered. Are you sure you cleared caches after applying this patch? I've rebased this PR against `master` and pushed to trigger a new demo site build. Seems to be working fine on that demo too.

**Comment by monishdeb** [comment]
Ok I will check again on my local. Earlier I have cleared the drupal cache, them did a menu rebuild in civi but let me give it another try. 

@colemanw can you please rebase the PR, as it seems there are conflicts on DAOs file.

**Comment by colemanw** [comment]
@monishdeb rebased

**Comment by monishdeb** [comment]
Hmm not sure what happened to my local setup, but after refreshing the DB the patch fixes the issue. However this time I received a few new issues and was able to replicate in local and test build site http://core-22519-5zu87.test-3.civicrm.org:8001 (username: admin / password : E0HkFPCTjdi1) 

As per the new screencast, I created a new custom group and then the 'New Custom Field' popup automatically loads with existing custom fields value. Also, I cannot delete an empty custom group as it throws a validation error, complains about the existing custom field: 
before

**Comment by colemanw** [comment]
@monishdeb thanks for finding those two bugs. They were both related to retrieving the id from the URL. I've fixed them now.

**Comment by monishdeb** [comment]
Looks good to me now. Didn't encounter any new issues after retesting all the pages. Hence merging this PR.

**Pull request merged**
