### PR TITLE
CRM-20431 - Fix unsubscribe group list

### PR DESCRIPTION
**Pull request by jitendrapurohit**
Unit Test added.

---

 * [CRM-20431: Unsubscribe Page shows wrong group names](https://issues.civicrm.org/jira/browse/CRM-20431)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit I seem to recall this is your QA on another PR & you've added a test? Can you confirm, because that will determine if further QA is needed

**Comment by jitendrapurohit** [comment]
No, this was something which was failing for one of our client and I've fixed it including a unit test. So, we need a reviewer to move this forward.

**Comment by seamuslee001** [comment]
Just commenting that @andrew-cormick-dockery has now tested this and released it into AUG Production @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
Ok - given this has been production tested, reviewed by Seamus and has a unit test, and I've read the code & it makes sense to me I'm going to merge this.

Scope is also quite limited

**Comment by jitendrapurohit** [comment]
Thanks @seamuslee001 @andrew-cormick-dockery @eileenmcnaughton

**Pull request merged**
