### PR TITLE
dev/core#5116 - Fix missing language selector for scheduled reminders

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes regression reported in https://lab.civicrm.org/dev/core/-/issues/5116

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by mlutfy** [comment]
odd fail:

```

not ok 445 - Failure: api\v4\Entity\ManagedEntityTest::testRevertSavedSearch
  ---
  message: Failed asserting that '2024-05-04 12:02:23' is equal to '2024-05-04 12:02:24'
    or is greater than '2024-05-04 12:02:24'.
  severity: fail
  ...
```

**Comment by mlutfy** [comment]
jenkins, test this please

**Pull request merged**
