### PR TITLE
Afform - Fix LocBlock address/email/phone saving

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes https://lab.civicrm.org/dev/core/-/issues/5527

Before
-------------
- Could not save event location with blank email/phone
- State/province list did not reload when selecting a country for event address
- Exposed "Existing Location" id field was overwritten on save

After
-----
Fixed

### CODE REVIEW

**Comment by Guydn** [comment]
Thanks a lot ! I will review it on monday.

**Comment by Guydn** [comment]
See my review on gitlab, pending issue

**Comment by Guydn** [comment]
Form with an event template, title, description start and end date, phone and email not required. Form can be  updated (URL is allowed).
1: create an event test 1 with new Address 1 -> Address is saved OK
2: create an event test 2 with new address 2 -> saved OK
3: update Test 1 : remove existing location address 1 (field is kept empty) and create new address 3 -> changed OK
4: update Test 1: remove existing location address 3 and choose another Existing location Address 2 -> changed OK
5: update Test 1: keep the existing location address 2 and modify one field (street) -> changed OK
6: check Test 2 with address 2 -> address 1 is correctly changed with above street change OK
7: country not necessarily filled ->  no impact : OK
And various other tests -> OK
For me this is OK Good news :-)

**Comment by colemanw** [comment]
Great, thanks for the review @Guydn

**Pull request merged**
