### PR TITLE
CRM-17789 - Use mysqli (rebased from mollux/mfb PRs)

### PR DESCRIPTION
**Pull request by seamuslee001**
- [CRM-17789: Support PHP 7](https://issues.civicrm.org/jira/browse/CRM-17789)

### CODE REVIEW

**Comment by seamuslee001** [comment]
I've done some local testing the issue appears to be that the test_dsn is still mysql:// not mysqli:// The other test seems a little flaky

**Comment by seamuslee001** [comment]
@totten @mollux Hey folks, so i have updated the transaction test to allow for either mysql or mysqli to work see https://github.com/seamuslee001/civicrm-core/pull/8940/commits/7d69b618b205472e5fbff1d7074abffe947d517f . I have also made it throw an exception if your trying to run php7 and using mysql dsn.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by totten** [comment]
Since this patch deals a lot with the installer, I did a trial-run with installing tarballs for Drupal/Joomla/WordPress via `civihydra` on MAMP (PHP 5.x), and it still seemed to work normally. However, I ran into some unexpected problems with Backdrop - but have not yet analyzed to determine the cause or origin of the problem.

@seamuslee001 or @jitendrapurohit  , if you'd like to give them a whirl on a real PHP 7 system, I've posted the tarballs to http://think.hm/tmp/d91786dea82b4532b67a657da092ae30104bf6a5/

**Comment by seamuslee001** [comment]
@totten without upgrading an AUG server i have tested in a bleached version of our db which is pretty rudimentary but gave me enough to work with, I'm not seeing any obvious errors caused by this change.

**Comment by jitendrapurohit** [comment]
@totten I've tested the installation from the tarballs on PHP 7 and they worked fine on Drupal, WP. Joomla installation failed for me with the error message :

>Cannot open mysql://root:root@localhost/joomlacms?new_link=true: DB Error: extension not found

It seems it takes the DSN from `civicrm.settings.php` generated. So, Maybe we also need to modify the `$dsn` name from `mysql` to `mysqli` w.r.t the PHP version in [civicrm.settings.php.template](https://github.com/civicrm/civicrm-core/blob/master/templates/CRM/common/civicrm.settings.php.template#L81)?

**Comment by totten** [comment]
@jitendrapurohit tldr

The problem is most likely this: [the Joomla-Civi installer calls `DB::connect`](https://github.com/civicrm/civicrm-joomla/blob/master/admin/configure.php#L166), which is where we set `define('DB_DSN_MODE', 'auto');` (b3029f893f9a)

**Comment by totten** [comment]
The longer explanation about `CIVICRM_DSN` relates to a discussion on the `civicrm-dev@` list (but which may not appear in the Github/JIRA record).

The nub of the question was whether we want to go through and edit `civicrm.settings.php` files to change `CIVICRM_DSN` from `mysql://` to `mysqli://` -- or to keep the DSN identical (but change its interpretation).

 * In support of changing the DSN, there's historically been a secret feature where one could do just that. And some aspects of mollux's patches were based on this assumption.
 * In support of keeping the DSN, it's lower total-cost. Sysadmins don't need to change their `civicrm.settings.php` file whenever they migrate/upgrade/downgrade systems. Developers can assume that the app is always the same driver (fewer configurations to consider/test). Auxiliary installers (like `provision_civicrm` or `civibuild`/`amp`) don't need any special-case logic (based on the target version of Civi or the runtime environment).

The implementation here aims to keep the DSN identical (but change its interpretation). Basically, in `DB::parseDSN()` it says `$dsn = preg_replace('^mysql:','mysqli:', $dsn)`. (But due to the way changes are split among repos, it's a little tricky to simply make that change atomically. Instead, we add the option `DB_DSN_MODE` which can be used to enable the new interpretation of `CIVICRM_DSN`.)

**Comment by totten** [comment]
Joomla PR: https://github.com/civicrm/civicrm-joomla/pull/39

**Comment by totten** [comment]
I've published an updated tarball which adds civicrm/civicrm-joomla#39. It still works on MAMP / PHP 5.5 but needs to be tested on PHP 7.

**Comment by jitendrapurohit** [comment]
Tested the latest tarball and they seemed to work fine on PHP 7 system.

**Comment by totten** [comment]
OK, I've diagnosed the issue mentioned about re: Backdrop. It's unrelated to this or PHP 7. (The problems there were: (1) I didn't know to append `?civicrm_install_type=backdrop` to the installer URL ; (2) the test build uses a 1.5.x which was failing, but 1.4.x still works.).

**Pull request merged**
