### PR TITLE
Remove inappropriate exception handling.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Remove exception when a payment is recorded through the api and the contribution is not partially paid or pending + pay later

Before
----------------------------------------
Exception thrown - e.g when adding a payment to a completed contribution

After
----------------------------------------
Exception not thrown. This check is removed on the basis that the rule is outdated and too narrow

Technical Details
----------------------------------------
Per discussion in https://github.com/civicrm/civicrm-core/commit/570243c292fa7bceea74ce233feceb3f69211e54#r31805899

the core logic has been changed to now accept a payment regardless of contribution status. This reflects the
fact that a payment could be received for a fully paid contribution and we still need to record it.

This exception is inappropriately narrow (& likely in the wrong place since it should probably be closer to
where the decision is made about adding a payment rather than when it is being processed

Comments
----------------------------------------
@JoeMurray this follows on on our discussion - note that this change looks big because the 'else' got removed - requiring a big whitespace change but this really is just the removal of the exception in line 4501 - https://github.com/civicrm/civicrm-core/pull/13442/files?w=1 for without whitespace

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton this needs a rebase now

**Comment by mattwire** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@JoeMurray @monishdeb can we merge this per previous discussions?

**Comment by JoeMurray** [comment]
I agree with the objective and approach in the code. I imagine @lcdservices does as well. @monish?

**Comment by lcdservices** [comment]
I definitely concur.

**Comment by eileenmcnaughton** [comment]
thanks @monishdeb

**Comment by eileenmcnaughton** [comment]
@magnolia61 good question! I guess it stops it from being blocked at one place in the code - it depends if that is the place blocking it in your flow

**Comment by magnolia61** [comment]
@eileenmcnaughton I was thinking about also enabling a Pay Now button for failed contributions from the user dashboard. I will keep it in mind for the partial payment / Pay Now issue https://github.com/civicrm/civicrm-core/pull/12319

**Comment by eileenmcnaughton** [comment]
@magnolia61 so this change DID come off changes @jitendrapurohit proposed for that issue - I just wasn't prepared to see so many changes at once & am working through his changes

**Comment by jitendrapurohit** [comment]
Many thanks for splitting the changes into these separate PRs @eileenmcnaughton. Thank you :-)

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit I know it's kinda messing with you since your code is going stale but I also can't cope with so much change in one PR. The question I really want to resolve next is about what combo of messages going out we should support from Payment api - ie. Payment.confirmation & Contribution.confirmation when completing - there is discussion on it ... somewhere else

**Pull request merged**
