### PR TITLE
fixes financial#181 - don't crash when displaying recurring contribut…

### PR DESCRIPTION
**Pull request by MegaphoneJon**
…ions whose 'template' has no line items

Overview
----------------------------------------
https://lab.civicrm.org/dev/financial/-/issues/187

When a recurring contribution template has no line items, the contact contribution tab crashes.

Before
----------------------------------------
500 error (stack trace on Gitlab ticket)

After
----------------------------------------
No crash.

Comments
----------------------------------------
This regressed in 5.41.0, but the deeper issue is contributions with no line items.  I'm not sure that's something we can fix retroactively though.

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
Note that I didn't write a test because a) I couldn't see a way to replicate having no line items without deleting them, b) I don't think this is behavior we're trying to lock in.

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon I'm OK with that but it would be good to get some code comments into that chunk of code - otherwise it could easily be removed again

**Comment by MegaphoneJon** [comment]
Done, but it has me wondering - do we know why some contributions have no line items?  And in those cases, I think it makes sense to assume that only one line item should exist, and I'm wondering if that makes it possible to write a function that fixes these?  That would be good to drop into an upgrade routine, but I don't know if I'm assuming too much.

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon - no I don't know why some contributions have no line items  - it wasn't on my radar as a 'thing'

**Comment by mattwire** [comment]
This should probably go into the RC

**Comment by MegaphoneJon** [comment]
Good point @mattwire - https://github.com/civicrm/civicrm-core/pull/21729

**Pull request closed without merging**
