### PR TITLE
Add test for mixed Order data

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This test is to try to capture & replicate an issue @christianwach is having with order api on taxes with more than one row - @christianwach I feel like this should be failing from your experience but it didn't locally

Before
----------------------------------------
Less tests

After
----------------------------------------
More tests

Technical Details
----------------------------------------
This didn't replicate the issue but it's useful as a test I think & I can build on it

Comments
----------------------------------------

### CODE REVIEW

**Comment by christianwach** [comment]
@eileenmcnaughton I've added a Gist with complete details of the mismatch:

https://gist.github.com/christianwach/ac8e8460c7f488a9a31f30a2c74eefc6

**Comment by christianwach** [comment]
@eileenmcnaughton A bit more info... so... turns out my Order API call wasn't as clean as I thought it was. Elsewhere, just after the `Order.create`, there was an attempt to update the Contribution with a `contribution_note`. Seems this triggers the recalculation.

I can now confirm that with a Non-taxable Financial Type applied to the Contribution and mixed Line Item Financial Types all seems to be well.

I'll keep digging with other combinations, but it seems updating a Contribution with a `contribution_note` is big no-no.

**Comment by JoeMurray** [comment]
@monishdeb could you work to ensure that a contribution update does not result in inappropriate recalculation of sales taxes, which I imagine involves calculating it differently on subsequent saves.

**Comment by christianwach** [comment]
Recalculation seems to happen any time a Contribution is updated regardless of whether the Financial Type is taxable or not e.g. a trivial update to the "Source":

```php
$result = civicrm_api3('Contribution', 'create', [
  'financial_type_id' => 5, // Happens to be a Taxable Financial Type but need not be.
  'contact_id' => 206,
  'id' => 103,
  'source' => "Something",
]);
```

All taxes will be recalculated and the errors in the Gist can be observed. I've updated it to reflect the situation better:

https://gist.github.com/christianwach/ac8e8460c7f488a9a31f30a2c74eefc6

**Comment by eileenmcnaughton** [comment]
@christianwach thanks for narrowing it down - that helps

**Comment by eileenmcnaughton** [comment]
OK - I can replicate this now - @seamuslee001 we might as well merge this as an extra test & I can build on it to fix Christian's actual problem

**Comment by christianwach** [comment]
> I can build on it to fix Christian's actual problem

@eileenmcnaughton That would be wonderful 🏅

**Comment by eileenmcnaughton** [comment]
@christianwach I'm working on it over here - https://github.com/civicrm/civicrm-core/pull/20357- at this stage my fix assumes a lack of weird data being passed in which I am not sure is true :-)

**Pull request merged**
