### PR TITLE
Fix bug where fields is not present

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fix bug where fields is not present

Before
----------------------------------------
image

After
----------------------------------------
fixed

Technical Details
----------------------------------------
I didn't dig too deeply as I think it was an edge case configuration - the line in question has not changed recently

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by mattwire** [comment]
@eileenmcnaughton I'm worried we might just be masking the real problem with this?

**Comment by eileenmcnaughton** [comment]
@mattwire I think it would occur if you have a custom group configured but have deleted all the fields attached to it - which is not a great config but not site breakingly wrong

**Comment by colemanw** [comment]
Makes sense.

**Comment by MegaphoneJon** [comment]
This bug only occurs in 5.71+, I recommend putting this fix against the rc.

**Pull request merged**
