### PR TITLE
APIv4 - Add GROUP_FIRST aggregate function

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds a useful new SQL function to APIv4, and exposes it to SearchKit.

Before
---------
SearchKit has a "List" transformation (aka GROUP_CONCAT) but gives no control over ORDER BY and no way to return just one record from that list.

After
--------
"List" transformation now gives fine control of the ORDER BY param.
"First" transformation added, which returns the first item from "List". ORDER BY param gives control over which item is considered the first.

Technical Details
----------------------------------------
This fills a gap in the MySql spec. It returns the first result of a GROUP_CONCAT set. By flipping the ORDER BY param from ASC to DESC it will alternately return the _last_ result in the group.

Comments
-------
Adding a corresponding `GROUP_LAST` function would be trivial copy/paste/tweak... but OTOH, it's also trivial to change the ORDER BY from ASC to DESC in SearchKit and get the last element that way.

### CODE REVIEW

**Comment by aydun** [comment]
Looks good in SearchKit.  I think the ascending/descending is sufficiently obvious that we don't need `GROUP_LAST`.

However, in API4 Explorer, I tried:
```
$contacts = \Civi\Api4\Contact::get(TRUE)
  ->setLimit(25)
  ->addGroupBy('contact_type')
  ->execute();
foreach ($contacts as $contact) {
  // do something
}
```

but got an error:
```
{
  "info": "SELECT `a`.`id` AS `id`, `a`.`contact_type` AS `contact_type`, `a`.`external_identifier` AS `external_identifier`, `a`.`display_name` AS `display_name`, `a`.`organization_name` AS `organization_name`, `a`.`contact_sub_type` AS `contact_sub_type`, `a`.`first_name` AS `first_name`, `a`.`middle_name` AS `middle_name`, `a`.`last_name` AS `last_name`, `a`.`do_not_email` AS `do_not_email`, `a`.`do_not_phone` AS `do_not_phone`, `a`.`do_not_mail` AS `do_not_mail`, `a`.`do_not_sms` AS `do_not_sms`, `a`.`do_not_trade` AS `do_not_trade`, `a`.`is_opt_out` AS `is_opt_out`, `a`.`legal_identifier` AS `legal_identifier`, `a`.`sort_name` AS `sort_name`, `a`.`nick_name` AS `nick_name`, `a`.`legal_name` AS `legal_name`, `a`.`image_URL` AS `image_URL`, `a`.`preferred_communication_method` AS `preferred_communication_method`, `a`.`preferred_language` AS `preferred_language`, `a`.`hash` AS `hash`, `a`.`api_key` AS `api_key`, `a`.`source` AS `source`, `a`.`prefix_id` AS `prefix_id`, `a`.`suffix_id` AS `suffix_id`, `a`.`formal_title` AS `formal_title`, `a`.`communication_style_id` AS `communication_style_id`, `a`.`email_greeting_id` AS `email_greeting_id`, `a`.`email_greeting_custom` AS `email_greeting_custom`, `a`.`email_greeting_display` AS `email_greeting_display`, `a`.`postal_greeting_id` AS `postal_greeting_id`, `a`.`postal_greeting_custom` AS `postal_greeting_custom`, `a`.`postal_greeting_display` AS `postal_greeting_display`, `a`.`addressee_id` AS `addressee_id`, `a`.`addressee_custom` AS `addressee_custom`, `a`.`addressee_display` AS `addressee_display`, `a`.`job_title` AS `job_title`, `a`.`gender_id` AS `gender_id`, `a`.`birth_date` AS `birth_date`, `a`.`is_deceased` AS `is_deceased`, `a`.`deceased_date` AS `deceased_date`, `a`.`household_name` AS `household_name`, `a`.`primary_contact_id` AS `primary_contact_id`, `a`.`sic_code` AS `sic_code`, `a`.`user_unique_id` AS `user_unique_id`, `a`.`employer_id` AS `employer_id`, `a`.`is_deleted` AS `is_deleted`, `a`.`created_date` AS `created_date`, `a`.`modified_date` AS `modified_date`, `a`.`preferred_mail_format` AS `preferred_mail_format`
FROM civicrm_contact a
WHERE (`a`.`is_deleted` = \"0\")
GROUP BY `a`.`contact_type`
LIMIT 25
OFFSET 0
 [nativecode=1055 ** Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'core2816430j5mcivi_esiy7.a.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by]",
  "db_error": "unknown error",
  "sql": [
    "SELECT `a`.`id` AS `id`, `a`.`contact_type` AS `contact_type`, `a`.`external_identifier` AS `external_identifier`, `a`.`display_name` AS `display_name`, `a`.`organization_name` AS `organization_name`, `a`.`contact_sub_type` AS `contact_sub_type`, `a`.`first_name` AS `first_name`, `a`.`middle_name` AS `middle_name`, `a`.`last_name` AS `last_name`, `a`.`do_not_email` AS `do_not_email`, `a`.`do_not_phone` AS `do_not_phone`, `a`.`do_not_mail` AS `do_not_mail`, `a`.`do_not_sms` AS `do_not_sms`, `a`.`do_not_trade` AS `do_not_trade`, `a`.`is_opt_out` AS `is_opt_out`, `a`.`legal_identifier` AS `legal_identifier`, `a`.`sort_name` AS `sort_name`, `a`.`nick_name` AS `nick_name`, `a`.`legal_name` AS `legal_name`, `a`.`image_URL` AS `image_URL`, `a`.`preferred_communication_method` AS `preferred_communication_method`, `a`.`preferred_language` AS `preferred_language`, `a`.`hash` AS `hash`, `a`.`api_key` AS `api_key`, `a`.`source` AS `source`, `a`.`prefix_id` AS `prefix_id`, `a`.`suffix_id` AS `suffix_id`, `a`.`formal_title` AS `formal_title`, `a`.`communication_style_id` AS `communication_style_id`, `a`.`email_greeting_id` AS `email_greeting_id`, `a`.`email_greeting_custom` AS `email_greeting_custom`, `a`.`email_greeting_display` AS `email_greeting_display`, `a`.`postal_greeting_id` AS `postal_greeting_id`, `a`.`postal_greeting_custom` AS `postal_greeting_custom`, `a`.`postal_greeting_display` AS `postal_greeting_display`, `a`.`addressee_id` AS `addressee_id`, `a`.`addressee_custom` AS `addressee_custom`, `a`.`addressee_display` AS `addressee_display`, `a`.`job_title` AS `job_title`, `a`.`gender_id` AS `gender_id`, `a`.`birth_date` AS `birth_date`, `a`.`is_deceased` AS `is_deceased`, `a`.`deceased_date` AS `deceased_date`, `a`.`household_name` AS `household_name`, `a`.`primary_contact_id` AS `primary_contact_id`, `a`.`sic_code` AS `sic_code`, `a`.`user_unique_id` AS `user_unique_id`, `a`.`employer_id` AS `employer_id`, `a`.`is_deleted` AS `is_deleted`, `a`.`created_date` AS `created_date`, `a`.`modified_date` AS `modified_date`, `a`.`preferred_mail_format` AS `preferred_mail_format`
FROM civicrm_contact a
WHERE (`a`.`is_deleted` = \"0\")
GROUP BY `a`.`contact_type`
LIMIT 25
OFFSET 0
 [nativecode=1055 ** Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'core2816430j5mcivi_esiy7.a.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by]"
  ]
}
```

The same thing on dmaster does not produce an error.

**Comment by colemanw** [comment]
Thanks for testing this @aydun. I don't think your error relates to this PR.
What you're seeing is a FULL_GROUP_BY_MODE mysql error. And perhaps one demo site has that mode set and the other doesn't, but both queries are equally wrong. You can't select * with group_by like that.

**Comment by aydun** [comment]
Ok, if that is not related then let's merge.

**Comment by colemanw** [comment]
Thanks @aydun

**Pull request merged**
