### PR TITLE
SearchUI: add Find Contributions

### PR DESCRIPTION
**Pull request by aydun**
Overview
----------------------------------------
Replace Find Contributions with SearchKit/FormBuilder

New search currently at civicrm/sk/contrib

Lots of things still to fix, looking for collaboration!

 - [ ] Figure out how to handle payments:
    - In current version, clicking on amount expands to show payment details and buttons 
 - [ ] Figure out how to handle Soft Credits
   - Current version has several filter options
 - [ ] Figure out how to handle Recurring Contributions
   - Current version also searches for these.  Maybe better as a separate search? 
 - [ ] Figure out how to handle PCPs
   - (Does anyone use PCPs?  If so, what is useful in this search?)  Not showing correctly.
 - [x] Add contribution totals
 - [ ] Some actions missing
 - [x] Filters - convert some to Yes/No ([#4415](https://lab.civicrm.org/dev/core/-/issues/4415))
   - done by adding 'is null' fields to search.  Would be nice to rework if/when 4415 is implemented.
   - but this doesn't interact properly with 'Group by' used in the Summary section
 - [ ] Filter layout
   - Current labels and groupings are for dev purposes, need improvement
 - [ ] Add more here ...

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw @aydun I think this question came up on chat but looking at this PR I vote we start a new search_ui extension rather than add this to admin_ui

Admin UI is mature enough to make it the thing - but venturing into the brave new world of replacing search screens will require a different cadence. Also I feel nervous about enabling the admin UI for our site if it might start changing search screens - I think I would not be alone

Note if this WERE against a new separate extension we could merge this even though there would be lots of stuff un-resolved.

**Comment by colemanw** [comment]
That makes sense to me.

**Comment by aydun** [comment]
Ok, @colemanw & @eileenmcnaughton - SearchUI created

**Comment by colemanw** [comment]
@aydun now that new extension exists you could rebase this to the new location.

**Comment by aydun** [comment]
I've put a menu entry under a new 'Experimental' top-level menu so we can have this enabled without disrupting access to the core version.

**Comment by eileenmcnaughton** [comment]
@aydun based on that I think the search ui extension is now under our new-extension-merge regime - which basically means you can self-merge this when you are ready & we don't expect it to reach the same level to be mergeable as we would for changes to existing code.

**Comment by aydun** [comment]
Ok, thanks @eileenmcnaughton

**Comment by aydun** [comment]
Outstanding issues moved to https://lab.civicrm.org/dev/core/-/issues/4440

**Comment by aydun** [comment]
Self-merging as per @eileenmcnaughton

**Pull request merged**
