### PR TITLE
SearchKit - Add "administer search_kit" permission

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds a permission which allows non-admins to use Search Kit.

See https://lab.civicrm.org/dev/core/-/issues/3457

Before
----------------------------------------
Previously the user needed 'administer CiviCRM data' permission to use Search Kit.

After
----------------------------------------
image

Technical Details
-----------------------
When updating the navigation menu permissions, I switched it over to use a `.mgd.php` to insert the menu item instead of creating it with the installer. This should also work better for multi-domain sites.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Working: Don't give administer civicrm or administer civicrm data or administer search_kit => can't do admin stuff but can use existing search displays.

But then add the permission to administer search_kit and while I can now see the admin interface, if I try to save a new search I get a spinning save button. It gives error 403 with `{"error_code":"1","error_message":"Sorry an error occurred and your request was not completed. (Error ID: UYOC-Qphn-rkNB)"}`

**Comment by eileenmcnaughton** [comment]
sounds like progress :-)

**Comment by colemanw** [comment]
How about that, it turns out there was a `fixme` in the API code anticipating we'd hit that problem eventually.
I fixed the fixme and now it's fixed :)

**Comment by awestuk** [comment]
Tested this on production and it's working great! Non-admins can now create and view searches, which is exactly what we wanted.

Only minor issue is that non-admins with this and 'edit all contacts' don't see the 'Related Contacts' entity. I'm assuming that's because permissions on relationships are more complicated. I can see it devolves down to addSelectWhereClause, but haven't got any further than that yet.

**Comment by colemanw** [comment]
@awestuk great. Here's a fix for the other thing you noticed. Can you please review/test #23684.

**Comment by eileenmcnaughton** [comment]
Issues have been addressed upping to MOP

**Pull request merged**
