### PR TITLE
dev/translation#48 Provide fall back function for if php-intl is not present

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------

This provides a softer migration to the use of Brick Money, permitting a fallback to the old method if php-intl is

not present. We have a system check to encourage people to install it as step one of trying to ensure people have it.

Deprecation warnings, upgrade notices can be added later

Before
----------------------------------------
Hard fail if php-intl not installed on 5.28

After
----------------------------------------
Works as before for 5.28, except for a status check telling people they should change

Technical Details
----------------------------------------
I haven't tested this without php-intl installed at this stage - I would be hugely grateful if someone else would to save me trying to re-configure my php. Viewing / editing a contribution will call this code and if there is an issue I would expect a hard fail....

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton I tested this and for this part of Brick Money at least I couldn't get a hard fail to trigger either through running the unit tests or from viewing or editing contributions as per your suggested after i removed intl and without applying this PR. However after applying this PR on a system without intl i do get a warning showing up

```
1) CRM_Utils_MoneyTest::testSubtractCurrencies with data set #6 ('notanumber', 5.0, 'USD', null)
Deprecated function CRM_Utils_Money::subtractCurrencies, use This function should not be called with non-numeric values.
Array
(
    [civi.tag] => deprecated
)


/home/seamus/buildkit/build/47-test/web/sites/all/modules/civicrm/CRM/Core/Error/Log.php:58
/home/seamus/buildkit/build/47-test/web/sites/all/modules/civicrm/vendor/psr/log/Psr/Log/AbstractLogger.php:85
/home/seamus/buildkit/build/47-test/web/sites/all/modules/civicrm/CRM/Core/Error.php:1049
/home/seamus/buildkit/build/47-test/web/sites/all/modules/civicrm/CRM/Utils/Money.php:150
/home/seamus/buildkit/build/47-test/web/sites/all/modules/civicrm/tests/phpunit/CRM/Utils/MoneyTest.php:21
/home/seamus/buildkit/build/47-test/web/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:209
/home/seamus/buildkit/extern/phpunit7/phpunit7.phar:615

ERRORS!
Tests: 12, Assertions: 45, Errors: 1.
```

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I could remove that deprecation notice - or fix the test - it seems really dumb to accept a non-numeric value there...

**Comment by eileenmcnaughton** [comment]
@seamuslee001 so without this PR & without php-intl does the subtract currencies work? It's likely brick money only needs php-intl when it needs it - eg. formatting

**Comment by seamuslee001** [comment]
@eileenmcnaughton yes i ran the `CRM_Utils_MoneyTest` without intl and it passed

**Comment by eileenmcnaughton** [comment]
@seamuslee001 OK - I'll close this - but we will need to do some checks when we do the next part of brick money (replacing formatting code)

**Pull request closed without merging**
