### PR TITLE
CRM-19064 Add in pcp api

### PR DESCRIPTION
**Pull request by seamuslee001**
- [CRM-19064: API for personal campaign page](https://issues.civicrm.org/jira/browse/CRM-19064)

### CODE REVIEW

**Comment by seamuslee001** [comment]
this is dependent on https://github.com/civicrm/civicrm-core/pull/8697

**Review by heavenqueen — APPROVED** [review]
,

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@ggargani this is the PR you should check for tests of new pcp API

**Comment by ggargani** [comment]
Fine!

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by ggargani** [comment]
I tried to sum up all issues we discovered and prepared a new pull request which uses standard function and file names.
I added also the unit tests which succesfully ran in my test environment.
#9049

**Comment by seamuslee001** [comment]
closing in favor of https://github.com/civicrm/civicrm-core/pull/9049

**Pull request closed without merging**
