### PR TITLE
CRM-12227 - Adding extensions path directories resource URLs

### PR DESCRIPTION
**Pull request by danaskallman**
- [CRM-12227: Default \/ Recommended CiviCRM Extension Directory](https://issues.civicrm.org/jira/browse/CRM-12227)

### CODE REVIEW

**Comment by colemanw** [comment]
jenkins, add to whitelist

**Comment by colemanw** [comment]
jenkins, retest this please

**Comment by eileenmcnaughton** [comment]
This is hung up on style issue

MagicMerge.php:237, SpacingAfter, Priority: High

Expected 1 space after "="; 2 found

No description available. Please upgrade to latest checkstyle version.

**Comment by kcristiano** [comment]
@colemanw  It looks like the style error is in this PR https://github.com/civicrm/civicrm-core/pull/6863

Does it need to be fixed here as @danaskallman patch does not touch that paret of the file?

**Comment by totten** [comment]
Resubmitted as #7059. I made a small tweak the default value (`[config.files]/ext`) and fixed the style error. That style error appears to have been introduced to the main codebase outside Dana's patch, but it needed to be fixed so that the test suite could run.

**Pull request closed without merging**
