### PR TITLE
[REF] Replace CRM_Utils_Array::value with ?? in variable assignments

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
This is part of a series of PRs to update an old code pattern. `CRM_Utils_Array::value()` can in many cases be swapped for the new PHP7 `??` operator.

Technical Details
----------------------------------------
This PR was done entirely by regex find/replace. It targets variable assignments that use a single `CRM_Utils_Array::value()` call where the 3rd param is either NULL or omitted.

No manual tweaking was done, only regex. The two patterns used were:

- ` = CRM_Utils_Array::value\(([^,]+), ([^(),]+)\);$`
- ` = CRM_Utils_Array::value\(([^,]+), ([^(),]+), NULL\);$`

For additional safety, this was done with file filter set to `.php`, case-sensitive enabled, and comments and string literals excluded.

Screenshot from 2020-03-13 09-32-54

Comments
----------------------------------------
With 1,698 lines affected, IMO there's only one way to do this: treat it like a mass code autoformat like the one @twomice did a few years ago. Trust the regex, trust the unit tests, do a little spot-checking for sanity's sake, but do not attempt manual review.

### CODE REVIEW

**Comment by twomice** [comment]
1. Any thoughts on how this might impact any return-by-reference usage? Is that even used in the codebase? (FWIW, I did a quick manual review of the PR and didn't see the `return` keyword on any of the changed lines, so this may not be a concern here.)

> The statement `return $foo ?? $bar;` in a return-by-reference function will therefore not work and a warning is issued.

-- From https://www.php.net/manual/en/language.operators.comparison.php

2. Is this meant to be a step toward deprecating `CRM_Utils_Array::value()`? That would be nice.

**Comment by colemanw** [comment]
@twomice #16719 already tackled return statements so this PR should just be variable assignments.

**Comment by twomice** [comment]
:+1: @colemanw

**Comment by colemanw** [comment]
I think the big safety consideration here is what happens when the `$collection` being passed to `CRM_Utils_Array::value()` is not an array. Doing a little testing, this is what I've found: (note this matrix would get more complex if the `$default` being passed to `CRM_Utils_Array::value()`'s 3rd param was something other than `null` but this PR only deals with that simpler scenario).

| `$collection` type | `CRM_Utils_Array::value($key, $collection, NULL)` | $collection[$key] ?? NULL | Behaviors match? |
| ----------------------- | ------------------------------------ | ----------- | -------------------------|
| array | value or null | value or null  | :heavy_check_mark:  |
| null | null | null | :heavy_check_mark:  |
| number | null | null | :heavy_check_mark:  |
| boolean | null | null | :heavy_check_mark:  |
| string | null | string offset or null | sometimes |
| object | null | **fatal error** | :no_entry_sign: |

IMO the last two items are ok. Any code passing a string or an object to a function that expects an array is already broken so it's better to have the errors more prominent.

**Comment by colemanw** [comment]
Test failures should be fixed by merging #16778

**Comment by colemanw** [comment]
This is rebased and tests are passing. It will go stale soon due to its size.

**Comment by mlutfy** [comment]
:+1:  I think this really improves the code readability.

(alas it requires rebase)

**Comment by colemanw** [comment]
@mlutfy - rebased

**Comment by mlutfy** [comment]
OK, so this PR is really scary (huge number of changes), but based on other similar cleanups Coleman as done (which have gone well), I think we should bite the bullet. Last call? :D

**Comment by mlutfy** [comment]
Linting passed, so I merged (after other test runs had passed previously; this was just a 2 line rebase).

**Pull request merged**
