### PR TITLE
Fix dev/core#4104 - APIv4 autocomplete for contributions

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes the bug from https://lab.civicrm.org/dev/core/-/issues/4104

Before
----------------------------------------
Contribution Autocomplete fails.

After
----------------------------------------
image

### CODE REVIEW

**Comment by larssandergreen** [comment]
Thanks Coleman. I've tested, works as it should in general.

I think the select2 should list the Contribution ID. Otherwise, you're kind of in the dark as a user if you're looking for a specific ID. We do show the ID for Contact ID.

Similarly, I don't think including the amount in the fields searched makes sense (if you're looking for Contribution ID 100 and you end up with a bunch of results for $100 contributions). Small detail, not worth worrying about if it is difficult to exclude it.

I think the sort should just be desc by ID, because that's what we're looking for.

This wouldn't be caused by this PR, but in SK using Contribution ID CONTAINS gives you the select2, when I think it should be a text field. I can do a separate issue for that if that would be better. Works correctly in API Explorer.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by colemanw** [comment]
Thanks for the review @larssandergreen - I've updated it to include the ID, which is consistent with other entities.
Also, to be consistent with other entities I think it should still sort by contact name.
But keep in mind that these things can be configured on a per-site and even a per-field basis by overriding the default display in SearchKit.

**Comment by totten** [comment]
Test failures unrelated.

**Pull request merged**
