### PR TITLE
Export class code readability - Reduce passing of variable, define on class 

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Code readability refactor towards being able to review & merge fixes to the Export functionality

Before
----------------------------------------
$contactRelationships passed from pillar to post

After
----------------------------------------
self::$relationshipTypes  used instead

also self::$memberOfHouseholdRelationshipKey & $headOfHouseholdRelationshipKey defined & a function extracted in the test (this is towards adding second test but is added as incomplete at this stage as it passes on local mysql config but not CI config - which is in fact the bug we are working towards addressing) 

Technical Details
----------------------------------------
This is one of series of small refactors aimed at getting the toxic code to a point where I feel comfortable reviewing the proposed changes & bug fix

Comments
----------------------------------------
@monishdeb

### CODE REVIEW

**Comment by monishdeb** [comment]
@eileenmcnaughton earlier when I included the cleanup changes on my earlier PR #11901 and #11870 during rebase, it breaks the workflow and thus reflected on the added test failure. I need to revert some of the changes but still with no luck :( This is a very complex code and took me days to understand and fix the DB error. 
I will first try to correct the errors on those 2 PRs and will review it.

**Comment by eileenmcnaughton** [comment]
@monishdeb the thing is I pretty much concluded I was not going to be able to review your 2 Prs until we had massively simplified the code - ie. I think about 10 more PRs of this size need to be done & merged before we reach the point where we can take the logic of your PRs & fix the actual thing - I wasn't necessarily trying to keep the specific code changes in your PRs as I did this but to eventually enact the logic.

**Review by jitendrapurohit — APPROVED** [review]
I've reviewed the changes on the export screen and while skimming through the code. +1 for the cleanup 👍

**Comment by eileenmcnaughton** [comment]
merging based on @jitendrapurohit  - thanks!

**Pull request merged**
