### PR TITLE
Ensure that the logTableSpec cache key is always in lower case to fix…

### PR DESCRIPTION
**Pull request by seamuslee001**
… intermitant test failures on MySQL8

Overview
----------------------------------------
_A brief description of the pull request. Keep technical jargon to a minimum. Hyperlink relevant discussions._

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by pfigel** [comment]
@seamuslee001 @totten not sure if anything like that is out there, but this may break logging for extensions that create tables with mixed casing. I've used this test to reproduce:

```php
public function testMixedCase() {
  CRM_Core_DAO::executeQuery("DROP TABLE IF EXISTS `civicrm_Test_Mixed_case`");
  CRM_Core_DAO::executeQuery("CREATE TABLE `civicrm_Test_Mixed_case` (
    test_id int(10) unsigned NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`test_id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci");
  $schema = new CRM_Logging_Schema();
  $schema->enableLogging();
  $schema->fixSchemaDifferences();
}
```

Fails with:
```
1) CRM_Logging_SchemaTest::testMixedCase
Undefined index: civicrm_test_mixed_case

/Users/patrick/buildkit/build/coredev/web/sites/all/modules/civicrm/CRM/Logging/Schema.php:683
/Users/patrick/buildkit/build/coredev/web/sites/all/modules/civicrm/CRM/Logging/Schema.php:695
/Users/patrick/buildkit/build/coredev/web/sites/all/modules/civicrm/CRM/Logging/Schema.php:524
/Users/patrick/buildkit/build/coredev/web/sites/all/modules/civicrm/CRM/Logging/Schema.php:284
/Users/patrick/buildkit/build/coredev/web/sites/all/modules/civicrm/tests/phpunit/CRM/Logging/SchemaTest.php:333
```

Related test cleanup: #17269

**Comment by seamuslee001** [comment]
@pfigel yeh this was more of an experiment this is been a moderately frequent on MySQL 8 https://test.civicrm.org/job/CiviCRM-Core-Edge/CIVIVER=master,label=test-3/438/testReport/(root)/CRM_Logging_SchemaTest/testLengthChange/

**Comment by jaapjansma** [comment]
@seamuslee001 I dont have a clue what this PR is about? You left the template of the PR in the description, so could you please update the description. That would help in reviewing PRs.

**Comment by eileenmcnaughton** [comment]
Closing as 'experimental'

**Pull request closed without merging**
