### PR TITLE
Afform GUI enhancements & Search Kit integration

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds major improvements to the Afform GUI, notably the ability to edit Blocks & Search Display forms, plus a clone button, & search bar.

Before
----------------------------------------
Only able to edit Afforms of type Form. Attempts to edit other types in the GUI would crash.

After
----------------------------------------
GUI works with Forms, Blocks, & Search Displays.
image

Technical Details
----------------------------------------
This PR starts with refactoring the way the Afform GUI loads metadata, which boosts performance while improving flexibility for types of forms that can be worked with.

It then adds several points of integration between Search Kit and Afform, with cross-links between the two UIs, and shared metadata processing under-the-hood.

Comments
----------------------------------------
This doesn't create any hard dependencies between Afform & Search Kit, all the integration is done conditionally

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton I fixed the display issue - params needed to be escaped for html. This should be ready for review/merge now.

**Comment by eileenmcnaughton** [comment]
Making notes while testing  - may or may not be related to the PR
1) the experience on a slower search is much better now the count query is not holding up any rendering
2) I have created a search & am adding a table display. However, the preview button is not working
(I'll edit this comment with more)

**Comment by eileenmcnaughton** [comment]
@colemanw note this is stale

**Comment by eileenmcnaughton** [comment]
I managed to get my test to work on dmaster  - it looks a little fugly but it worked (preview button aside) - I suspect that it will be important to be able to specify the operator.


image

On our staging I didn't get it to work (500 error) & have not yet diagnosed the error but I didn't notice anything that had regressed on our staging so if @totten or @seamuslee001 checks the afform stuff I would merge this at that point & keep digging on our staging

**Comment by colemanw** [comment]
Cool. The "fugly" issue is that the civicrm home dashboard doesn't load bootstrap css. I don't have an easy solution to that problem :(

The filters are currently hard-coded to use "CONTAINS" operator.

**Comment by eileenmcnaughton** [comment]
@colemanw so if we have to have a hard-coded operator 'starts with' would be MUCH better for us.

I note the pagers are there even for 1 page which is a little odd

**Comment by eileenmcnaughton** [comment]
@colemanw - so my display has 'use pager' & 20 rows. But at civicrm/search#/display/transactions/transactions there is no pager

**Comment by colemanw** [comment]
Ok. I'll check the pager issue. It shouldn't be a blocker to merging this PR tho.

**Comment by eileenmcnaughton** [comment]
@colemanw no I don't think anything is blocking from my end as it seems non-regressive - just the afform side needs some checks

on our staging we are getting a 500 on civicrm/ajax/api4/Afform/convert & that action is missing in api explorer. I'm gonna stop for the day but I'd rather merge this & then re-test on our staging with an all-in tarball tbh since that is looking like a porting issue

**Comment by seamuslee001** [comment]
I did some light testing on this and confirmed that the afform side of this is ok. I did run into a style issue with using a basic form and then adding a birth date and middle name field the submit button got covered up

test-afform

I'm going to merge this as I believe its an improvement. Also I noticed that when cloning an afform I could save the new form with the same route as the original form which might seem to be some issue

**Comment by eileenmcnaughton** [comment]
Thanks @seamuslee001 - I'll see if I can do some more testing on the tarbal

**Pull request merged**
