### PR TITLE
[WIP] CRM-18563 Check for API exception when testing create without params.

### PR DESCRIPTION
**Pull request by mollux**
- [CRM-18563: Issues with the API and testing the API](https://issues.civicrm.org/jira/browse/CRM-18563)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Ouch! That;s a lot of entities that fail for all the wrong reasons. Good test though

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by JoeMurray** [comment]
@josephlacey Here's another PR that could use some of your love. Looks like the failing tests need to be resolved.

**Comment by josephlacey** [comment]
I'm not completely sure what I'm QA'ing here.  The test does in fact come back with failures, see results below, but that seems to be expected as far as I read the original ticket.  Do all the tests that failed need to be rewritten as separate PR's, so this test doesn't fail?

```
0 joseph@donkeys ~/local/buildkit/build/CRM-18563/sites/all/modules/civicrm/tools » ./scripts/phpunit --filter testWithoutParam_create api_v3_SyntaxConformanceTest
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

.
Installing CRM18563te_dpr5u database
....................................................F.....F...  63 / 122 ( 51%)
......F........F...................F.......FF.............F

Time: 33.75 seconds, Memory: 75.25Mb

There were 8 failures:

1) api_v3_SyntaxConformanceTest::testWithoutParam_create with data set #53 ('LocBlock')
Failed asserting that exception of type "CiviCRM_API3_Exception" is thrown.

/home/joseph/local/buildkit/build/CRM-18563/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:176
/home/joseph/local/buildkit/bin/phpunit4:545

2) api_v3_SyntaxConformanceTest::testWithoutParam_create with data set #59 ('MailingComponent')
Failed asserting that exception of type "CiviCRM_API3_Exception" is thrown.

/home/joseph/local/buildkit/build/CRM-18563/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:176
/home/joseph/local/buildkit/bin/phpunit4:545

3) api_v3_SyntaxConformanceTest::testWithoutParam_create with data set #69 ('Mapping')
Failed asserting that exception of type "CiviCRM_API3_Exception" is thrown.

/home/joseph/local/buildkit/build/CRM-18563/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:176
/home/joseph/local/buildkit/bin/phpunit4:545

4) api_v3_SyntaxConformanceTest::testWithoutParam_create with data set #78 ('Navigation')
Failed asserting that exception of type "CiviCRM_API3_Exception" is thrown.

/home/joseph/local/buildkit/build/CRM-18563/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:176
/home/joseph/local/buildkit/bin/phpunit4:545

5) api_v3_SyntaxConformanceTest::testWithoutParam_create with data set #98 ('PrintLabel')
Failed asserting that exception of type "CiviCRM_API3_Exception" is thrown.

/home/joseph/local/buildkit/build/CRM-18563/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:176
/home/joseph/local/buildkit/bin/phpunit4:545

6) api_v3_SyntaxConformanceTest::testWithoutParam_create with data set #106 ('SavedSearch')
Failed asserting that exception of type "CiviCRM_API3_Exception" is thrown.

/home/joseph/local/buildkit/build/CRM-18563/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:176
/home/joseph/local/buildkit/bin/phpunit4:545

7) api_v3_SyntaxConformanceTest::testWithoutParam_create with data set #107 ('Setting')
Failed asserting that exception of type "CiviCRM_API3_Exception" is thrown.

/home/joseph/local/buildkit/build/CRM-18563/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:176
/home/joseph/local/buildkit/bin/phpunit4:545

8) api_v3_SyntaxConformanceTest::testWithoutParam_create with data set #121 ('WordReplacement')
Failed asserting that exception of type "CiviCRM_API3_Exception" is thrown.

/home/joseph/local/buildkit/build/CRM-18563/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:176
/home/joseph/local/buildkit/bin/phpunit4:545

FAILURES!
Tests: 122, Assertions: 122, Failures: 8.
0 joseph@donkeys ~/local/buildkit/build/CRM-18563/sites/all/modules/civicrm/tools »
```

**Comment by eileenmcnaughton** [comment]
Looks like this is a proof-of-issue-via-test PR - but there are unfixed things it exposes so we can't merge

**Comment by eileenmcnaughton** [comment]
Ported into #8376 (now merged)

**Pull request closed without merging**
