### PR TITLE
Backport https://github.com/civicrm/civicrm-core/pull/5913

### PR DESCRIPTION
**Pull request by rubofvil**
Issue
https://issues.civicrm.org/jira/browse/CRM-19530

Backport from issue
https://issues.civicrm.org/jira/browse/CRM-16575 (https://github.com/civicrm/civicrm-core/pull/5913)

### CODE REVIEW

**Comment by omarabuhussein** [comment]
@rubofvil  the fix inside (CustomQuery.php)  looks good to me but maybe you need to add these lines too :

```php
	                // CRM-19006: escape characters like comma, | before building regex pattern
                $value = (array) $value;
                foreach ($value as $key => $val) {
                  $value[$key] = str_replace(array('[', ']', ','), array('\[', '\]', '[:comma:]'), $val);
                  $value[$key] = str_replace('|', '[:separator:]', $value[$key]);
                }
                $value = implode(',', $value);
```

see here https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/BAO/CustomQuery.php#L350

also these too : 

```php
          $value = str_replace(array('[', ']', ','), array('\[', '\]', '[:comma:]'), $value);
         $value = str_replace('|', '[:separator:]', $value);

```
see here https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/BAO/CustomQuery.php#L342

see the whole diff between you fix and the master branch https://www.diffchecker.com/NZ1v6cEh

I also tried to write some unit tests for it but apparently it is really hard to test it.. a lot of refactoring is needed to be able to do so .

**Comment by omarabuhussein** [comment]
Now regarding the Report/Form.php file , it appear that the fix is not accurate and does not return the desired result when you search for multiple values .. I checked the master and did some manual testing and you would probably replace the switch condetion  for (mhas & mnot ) to :

```php
      case 'mhas':
      case 'mnot':
        // multiple has or multiple not
        if ($value !== NULL && count($value) > 0) {
          $value = CRM_Utils_Type::escapeAll($value, $type);
          $operator = $op == 'mnot' ? 'NOT' : '';
          $regexp = "([[:cntrl:]]|^)" . implode('([[:cntrl:]]|$)|([[:cntrl:]]|^)', (array) $value) . "([[:cntrl:]]|$)";
          $clause = "{$field['dbAlias']} {$operator} REGEXP '{$regexp}'";
        }
        break;
```

**Comment by colemanw** [comment]
@civicrm-builder add to whitelist

**Comment by jackrabbithanna** [comment]
@omarabuhussein just for the book keeping, and thinking about process and documentation going forward, should we update the JIRA issue in question to explain that this was fixed in 4.6 and link to this PR?  OR should backported fixes get separate issues in JIRA, We/ everyone/ @eileenmcnaughton  can discuss that on Mattermost if you like, but whenever a PR is merged we should probably create/update an issue somewhere, even for backports to 4.6 of fixes made in 4.7

**Comment by omarabuhussein** [comment]
yeah I agree @jackrabbithanna  the ticket status should be updated I left a comment their to ask someone with access to update the fix version and I will pay attention for that so thanks for talking about it .

but creating a new ticket for backporting , well I think this not necessary since jira supports multiple fix versions so I think it better to stick to the same ticket rather than creating a new one .

**Comment by omarabuhussein** [comment]
by the way this should be closed in favor of this https://github.com/civicrm/civicrm-core/pull/9440

**Comment by eileenmcnaughton** [comment]
I'm closing based on @omarabuhussein's request

**Pull request closed without merging**
