### PR TITLE
[do not merge]

### PR DESCRIPTION
**Pull request by demeritcowboy**
Do the tests still take 2+ hours with this?

### CODE REVIEW

**Comment by demeritcowboy** [comment]
"Took 1 hr 57 min on test-3"

**Comment by colemanw** [comment]
That's a bit better @demeritcowboy

**Comment by demeritcowboy** [comment]
Yes a little, although on test-3 which is a more better machine it's not too far off some others. I'm re-running my other symfony one which effectively does the same bypass but keeps 4.x for a sanity check. My thinking was the optimizer they introduced leads to memory leaks, because that's what I was having trouble with on that PR, and the timing of that 3->4 update is roughly when it started getting worse. Might even be multiple causes because it went up to 2 hrs, then started getting worser even.

**Comment by demeritcowboy** [comment]
For the record the other PR testing the same idea: "Took 2 hr 44 min on test-1".

**Pull request closed without merging**
