### PR TITLE
prevent the get property from non-object error

### PR DESCRIPTION
**Pull request by wikimediaWfan**
Check if $mail->from exist and if not set reply to to blank

Fixes ` ERROR Trying to get property 'email' of non-object EmailProcessor.php:246 [notice]`

Bug: T318837

Overview
----------------------------------------
_A brief description of the pull request. Keep technical jargon to a minimum. Hyperlink relevant discussions._

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
add to whitelist

**Comment by eileenmcnaughton** [comment]
@wikimediaWfan One more thing to do - if you can put up a PR adding yourself to the ` contributors.yml` file that is used for release notes.

**Comment by eileenmcnaughton** [comment]
@wikimediaWfan One more thing to do - if you can put up a PR adding yourself to the ` contributors.yml` file that is used for release notes.

**Comment by wikimediaWfan** [comment]
> @wikimediaWfan One more thing to do - if you can put up a PR adding yourself to the ` contributors.yml` file that is used for release notes.

Do you mean contributors.txt?

**Pull request merged**
