### PR TITLE
financial#46 - clean money format at form layer - Fix mistreatment of event fees > 1000 when saving

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Same as https://github.com/civicrm/civicrm-core/pull/13721 but on event config page

@MegaphoneJon wanna check this? I tested to see if event is affected as well & it is

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by MegaphoneJon** [comment]
I'll try to get to this today.

**Comment by MegaphoneJon** [comment]
I tested this in a variety of configurations and confirmed that it fixes the problem in all.  This is good to merge.

**Comment by eileenmcnaughton** [comment]
thanks @MegaphoneJon  - hopefully that is the last!

**Pull request merged**
