### PR TITLE
dev/core#2650 Add support for names & labels for token pseudoconstants

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------

This is per https://lab.civicrm.org/dev/core/-/issues/2650 - it adds variations on the token `{contribution.contribution_status_id}` which support names and labels, i.e.

```
{contribution.contribution_status_id}
{contribution.contribution_status_id:name}
{contribution.contribution_status_id:label}
```

Both CRM_Core_SelecetValues::contributionTokens and CRM_Contribute_Tokens->tokenNames
are tested to ensure they return the same keys and labels for each.

And both rendering CRM_Contribute_Tokens via scheduled reminders and
using CRM_Contribute_BAO_Contribution::replaceContributionTokens are tested to ensure
they render them the same.

Before
----------------------------------------
The contribution token processor and legacy contributions use different syntaxes around tokens with potential labels or names and there is no clear plan as to what to standardise on. Also, some of the message templates work pretty hard to get around NOT having `{contribution.contribution_status_id:name}` available

After
----------------------------------------
```
{contribution.contribution_status_id}
{contribution.contribution_status_id:name}
{contribution.contribution_status_id:label}
```

available & consistent in all 4 code places that refer to contribution tokens at the moment

image

Technical Details
----------------------------------------

In the context of this PR no existing tokens are altered or removed & there is
only addition. However, the next step would be to remove the following token
from  {contribution.status}. Since there is no UI availability
of this token it is likely unused - but that step would entail an upgrade
script to remove it from the saved scheduled reminders.

With those parts in place it should be possible to reconcile the remaining tokens,
lock that parity in with tests and move on to exposing the contribution tokens
to message templates.

It would be nice to fully remove CRM_Contribute_BAO_Contribution::replaceContributionTokens
or make it a wrapper for  - however, I fear that might be quite
challenging due to the way it's used with group bys & some pretty intense hackery.

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
dang - that test passes locally & I think it might fail when not in isolation - maybe caching ...

**Comment by eileenmcnaughton** [comment]
Dang that passes locally - I wish there were a way to run unit tests against just one test to see if it passes remotely in isolation

image

**Comment by totten** [comment]
* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __Pass__
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __Pass__: 
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __Pass__
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __Pass__: Used the tokens with both a scheduled reminder and a thank-you PDF. Worked well.
        * (Tangentially, the `{contribution.id}` and `{contribution.contribution_id}` )
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __Pass__: 
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __Pass__
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __Pass__
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __Pass__

**Comment by eileenmcnaughton** [comment]
I've put up this to remove the dead token from action_schedule while we still know it's only available from there https://github.com/civicrm/civicrm-core/pull/20978

**Pull request merged**
