### PR TITLE
CRM-19360 : Exported CSV does not import back in without adjusting import columns

### PR DESCRIPTION
**Pull request by MiltoxBeyond**
The import parser for contacts tried and failed to compare grettings because the exported data already had tokens replaced with data.  On import, the tokens would not be found and would fail.  I implemented
a conversion between the token and available data from the imported row to generate a regex to validate the greeting value.

---
- [CRM-19360: Exported CSV does not import back in without adjusting import columns](https://issues.civicrm.org/jira/browse/CRM-19360)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by monishdeb** [comment]
Jenkin ok to test

**Comment by jitendrapurohit** [comment]
can you fix the [code style issues](https://test.civicrm.org/job/CiviCRM-Core-PR/12321/checkstyleResult/) listed by jenkins ?

**Comment by davejenx** [comment]
Have commented on CRM-19360: "seems an ingenious fix that I think introduces a change in behaviour. Before reviewing the patch in detail, I think it makes sense to agree on what the behaviour should be..."

**Comment by mlutfy** [comment]
I agree with this comment in JIRA by @davejenx: "Chris's suggestion was a less ambitious fix: not auto-selecting the addressee/greetings columns in the import mapping."

Considering this pull-request is rather old and does not have consensus, I will close it for now, but will leave the JIRA issue open.

**Pull request closed without merging**
