### PR TITLE
Revert fix causing unreleased regression

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Unfortunately https://github.com/civicrm/civicrm-core/pull/13250/files which fixes https://lab.civicrm.org/dev/core/issues/469 causes this regression https://lab.civicrm.org/dev/core/issues/671

Revert for the rc & try again

Before
----------------------------------------
Some form parameters ignored in search

After
----------------------------------------
Due care & attention restored

Technical Details
----------------------------------------

Comments
----------------------------------------
@monishdeb @francescbassas we can try again against master :-)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton isn't there more than just the test that needs to be reverted?

**Comment by monishdeb** [comment]
@eileenmcnaughton yes agree and the fix would be at 
```patch 
diff --git a/CRM/Contact/BAO/Group.php b/CRM/Contact/BAO/Group.php
index 00dead650a..61e688c06b 100644
--- a/CRM/Contact/BAO/Group.php
+++ b/CRM/Contact/BAO/Group.php
@@ -695,7 +695,7 @@ class CRM_Contact_BAO_Group extends CRM_Contact_DAO_Group {
     //create/update saved search record.
     $savedSearch = new CRM_Contact_BAO_SavedSearch();
     $savedSearch->id = $ssId;
-    $savedSearch->form_values = serialize($params['form_values']);
+    $savedSearch->form_values = serialize(CRM_Contact_BAO_Query::convertFormValues($params['form_values'], 0, FALSE, NULL, ['event_id', 'membership_type_id']));
     $savedSearch->mapping_id = $mappingId;
     $savedSearch->search_custom_id = CRM_Utils_Array::value('search_custom_id', $params);
     $savedSearch->save();
diff --git a/CRM/Contact/Form/Search/Advanced.php b/CRM/Contact/Form/Search/Advanced.php
index 35cec89cf2..18e9be3d7e 100644
--- a/CRM/Contact/Form/Search/Advanced.php
+++ b/CRM/Contact/Form/Search/Advanced.php
@@ -313,8 +313,7 @@ class CRM_Contact_Form_Search_Advanced extends CRM_Contact_Form_Search {
     }
 
     CRM_Core_BAO_CustomValue::fixCustomFieldValue($this->_formValues);
-
-    $this->_formValues = $this->_params = CRM_Contact_BAO_Query::convertFormValues($this->_formValues, 0, FALSE, NULL, $this->entityReferenceFields);
+    $this->_params = CRM_Contact_BAO_Query::convertFormValues($this->_formValues, 0, FALSE, NULL, $this->entityReferenceFields);
     $this->_returnProperties = &$this->returnProperties();
     parent::postProcess();
   }
```

**Comment by monishdeb** [comment]
I am ok with reverting this change in 5.10.  Marking with Merge on pass

**Comment by eileenmcnaughton** [comment]
@monishdeb yeah @seamuslee001 spotted the same - should be fixed now - I also did a new fix which I put as a comment in the original issue until merging has worked through

**Comment by seamuslee001** [comment]
Test failures unrelated merging as per the tag

**Pull request merged**
