### PR TITLE
dev/core#5534 Fixes overzealous removal of directories

### PR DESCRIPTION
**Pull request by JKingsnorth**
See https://lab.civicrm.org/dev/core/-/issues/5534

Review needed on any impact this could have on the security hardening.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Thanks @JKingsnorth - can you rebase against 5.79?

**Comment by totten** [comment]
To my eye, this looks more consistent with the prior behavior without affecting the symlink issue.

cc @SebastianLisken

**Comment by sebalis** [comment]
That’s my secondary account, @totten :-) – but yes, this is unrelated. The fix is not affected by the choice of `$rmdir` vs.  `TRUE`. I did discuss my reasons for suggesting the change in that line in my bug report, but I did not have the full picture.

**Comment by sebalis** [comment]
So in view of this use case of `cleanDir`, it does seem that this PR should be merged.

**Comment by twomice** [comment]
Test bot says "1 failiing check", which is:

`ERROR: Step ‘Publish xUnit test result report’ failed: The result file '/home/dispatcher/workspace/CiviCRM-Test/build/junit/CRM_AllTests.xml' for the metric 'PHPUnit' is empty. The result file has been skipped.`

I'm thinking that's unrelated to this PR and could be ignored as a blocker to merging.

**Comment by seamuslee001** [comment]
just FYI folks I have rebased this branch for @JKingsnorth onto the RC and updated the PR base

**Comment by seamuslee001** [comment]
I tested this on a joomla site and seems to work fine for me adding MOP

**Pull request merged**
