### PR TITLE
dev/core#4980 Ensure payment processor object is returned

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
https://lab.civicrm.org/dev/core/-/issues/4980

### CODE REVIEW

**Comment by bastienho** [comment]
My thoughs:

It seems correct, but we could avoid warnings by using `isset` instead of `empty`

By the way, is there not any risk of displaying an inappropriate message by assigning another paymentProcessor?

**Comment by eileenmcnaughton** [comment]
I think the risk is OK - ManualProcessor is kind of a dummy object. What warnings to you get with empty & not isse?

**Comment by colemanw** [comment]
@bastienho in PHP, `empty()` never produces notices. It is equivalent to `(!isset($val) || !$val)`

**Comment by bastienho** [comment]
Finally, I think you're right.

It makes the trick.

**Pull request merged**
