### PR TITLE
dev/core#1490 Fix syntax error in Membership Receipt

### PR DESCRIPTION
**Pull request by mlutfy**
Overview
----------------------------------------

https://lab.civicrm.org/dev/core/issues/1490

To reproduce:

* Setup a membership form, basic settings, with a test gateway so that billing fields are enabled
* Enable email confirmation receipts

Result:

### CODE REVIEW

**Comment by mattwire** [comment]
I assume this is a result of all the message template changes in 5.20 @eileenmcnaughton  Do we need to backport this to 5.20 / have an upgrader or anything?

**Comment by eileenmcnaughton** [comment]
@mattwire yeah it would ideally be backported I guess it needs to be a point release specific upgrader line - depends where @totten is placed to do a last drop

**Comment by mlutfy** [comment]
I suspect not many people will run a point-release on December 20. They can edit their msg-tpl if it's an issue, or upgrade to 5.21 in January?

**Comment by eileenmcnaughton** [comment]
yeah - I think if we do a release this should be in but it might not be enough to trigger one

**Comment by agileware-justin** [comment]
Just hit this problem. Thanks @mlutfy

**Pull request merged**
