### PR TITLE
[NFC] Update copyright date for 2020

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Comment by totten** [comment]
Test failure re:style validation are pre-existing, but I pushed up a quick fix for them anyway.

**Comment by totten** [comment]
2020-2004=16 ==> Old enough to get a driver's license.

Maybe this will finally be the year of the self-driving CRM?

**Comment by yashodha** [comment]
@seamuslee001 Should we hold off on merging this till we have a release in 2020?

**Comment by seamuslee001** [comment]
@yashodha nope the December 2019 Release has been branched into the RC so master is essentially now the January 2020 Release

**Comment by demeritcowboy** [comment]
c.f. https://lab.civicrm.org/dev/core/issues/878

**Pull request merged**
