### PR TITLE
(dev/core#2299) Get contact id for the mailing along with display nam…

### PR DESCRIPTION
**Pull request by yashodha**
…e and email

Overview
----------------------------------------
Get contact id for the mailing along with display name and email in getContactInfo method from CRM/Mailing/Event/BAO/Queue.php

Before
----------------------------------------
return display name and email only.

After
----------------------------------------
return display name and email and contact id as well.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@yashodha can you explain the reason for this - if you are trying to access it from an extension we might be better to think about a supported way to expose it since this could be altered again at any time

**Comment by yashodha** [comment]
@eileenmcnaughton yes, it was meant for extension but also when you have a _getContactInfo_ method it makes sense to return contact id as well (since that's the most basic thing) IMO.

**Comment by eileenmcnaughton** [comment]
@yashodha I think you are safer to copy and paste it into your extension & edit it - the core function could & possibly should be replaced by an api call & if some cleanup fairy does that your extension will break

**Comment by eileenmcnaughton** [comment]
@yashodha I'm going to close this because it's been here for a while and I still think you are better not to use this core function from an extension

**Pull request closed without merging**
