### PR TITLE
4.6 Backport Case Activity report fix

### PR DESCRIPTION
**Pull request by jitendrapurohit**
https://issues.civicrm.org/jira/browse/CRM-17504

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
jenkins, test this please

**Comment by jitendrapurohit** [comment]
jenkins, test this please

**Comment by jitendrapurohit** [comment]
jenkins, test this please

**Comment by monishdeb** [comment]
Jenkin, test this please

**Comment by davecivicrm** [comment]
Jenkins, retest this please.

**Comment by davecivicrm** [comment]
Did some testing on this w/ 4.6 and it looks good. Ok to merge on pass.

**Pull request merged**
