### PR TITLE
dev/financial#11 email invoice fails with validation error

### PR DESCRIPTION
**Pull request by lcdservices**
Overview
----------------------------------------
When sending out an email invoice, email validation error is thrown.

Before
----------------------------------------
With invoicing enabled, view a contribution and choose to email invoice. Select a from address and submit the form. An error is returned indicating email verification failed.

After
----------------------------------------
The above works properly.

Technical Details
----------------------------------------
The from email address was set using the option list label instead of the value. The label is URL encoded for display on screen. The encoding triggered the validation failure. This patch retrieves the value instead of the label and sets a default value.

### CODE REVIEW

**Comment by monishdeb** [comment]
@lcdservices I wasn't able to replicate the error. From this screencast, can you tell me if I missed anything?
test-multiple-after

**Comment by lcdservices** [comment]
Hmm... I didn't use the task from search results.
If you view the contribution, there's a button in the bottom right to email invoice. That's where I replicated the issue.

**Comment by monishdeb** [comment]
Oh that's strange
test-multiple-after

**Comment by monishdeb** [comment]
From code pov I think we don't need to pass default from address, as From email address field is required and there is no way one can reach that point without having ```$params['from_email_address']``` value. It might be some old code where this same field weren't required.

**Comment by monishdeb** [comment]
@lcdservices squashed commits and rebased PR.

**Comment by eileenmcnaughton** [comment]
@lcdservices can you confirm you are happy with this PR now - it looks to me like @monishdeb has updated it

**Comment by lcdservices** [comment]
@eileenmcnaughton yes, it's good to go

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
This fail may be related?

**Comment by monishdeb** [comment]
Doesn't seems so as tested again in local:
```
$ phpunit4 tests/phpunit/CRM/Contribute/Form/ContributionTest.php 
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

.
Installing civicrm47_drupal_test database
...................................

Time: 55.08 seconds, Memory: 113.75Mb

OK (36 tests, 437 assertions)
```

Triggering test build again

**Comment by monishdeb** [comment]
jenkins test this please

**Comment by kainuk** [comment]
Hi, just used the patch for a customer and it works. Thanks @lcdservices

**Comment by monishdeb** [comment]
Yeah this is the PR that got the same test failure https://github.com/civicrm/civicrm-core/pull/11992

**Pull request merged**
