### PR TITLE
Fix batch contact/activity update with radio options

### PR DESCRIPTION
**Pull request by ray-wright**
To account for radio option values that contain a space, wrap the value name in quotes.

Overview
----------------------------------------
When updating multiple contacts, activities, etc the 'copy value from first row' is problematic with radio options.

Before
----------------------------------------
If the column is a radio field and the value in the first row contains a space, they copy from first row errors and does fails to set the value down the list. Console error shows: 

> Uncaught Error: Syntax error, unrecognized expression: [value=Value with space]

After
----------------------------------------
With the additional quotes around the value, you can copy the radio value from the first row and apply to the entire list.

Comments
----------------------------------------
This only affected the radio values, other field type values with spaces updated without issues.

### CODE REVIEW

**Comment by colemanw** [comment]
This indeed looks like the correct fix. The only issue with this PR is the extra 2 merge commits. Are you able to rebase those out?

**Comment by ray-wright** [comment]
@colemanw I couldn't figure out how to do it in this patch but I can submit another patch with just the one commit - does that work?

**Comment by colemanw** [comment]
Sure. Whatever works for you :)

**Comment by ray-wright** [comment]
Great - I am actively working on getting better at tracking my own code and submitting PRs. Here's the new one: https://github.com/civicrm/civicrm-core/pull/16855

**Pull request closed without merging**
