### PR TITLE
[Datepicker][REF] Convert mailing date field on mailing search screen…

### PR DESCRIPTION
**Pull request by seamuslee001**
… to date picker

Overview
----------------------------------------
This converts the mailing/sms date on the unscheudled and scheduled and the find sms screens to use date picker

Before
----------------------------------------
jclander used

After
----------------------------------------
date picker used

ping @eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 this works but there were a couple of things I found confusing

1) how does this relate to advanced search? Several breakpoints later I agree the answer is 'it doesn't'

2) I found the resulting date wrangling still pretty overdone & confusing.
IMHO this is more readable & does the same thing. Note mysql is pretty cheerful about the format '2019-01-09 23:59:59' so I don't think we need to covert it to ISO now it's being consistently handled prior to that point (yay datepickder)
```
-    CRM_Contact_BAO_Query::fixDateValues($params["mailing_relative"], $params['mailing_low'], $params['mailing_high']);
+    if (!empty($params['mailing_relative'])) {
+      list($params['mailing_low'], $params['mailing_high']) = CRM_Utils_Date::getFromTo($params["mailing_relative"], $params['mailing_low'], $params['mailing_high']);
+      unset($params['mailing_relative']);
+    }
+    elseif(!empty($params['mailing_high'])) {
+      $params['mailing_high'] .= ' ' . '23:59:59';
+    }
 
     $parent = $this->controller->getParent();
     if (!empty($params)) {
@@ -133,12 +139,7 @@ class CRM_Mailing_Form_Search extends CRM_Core_Form {
         if (isset($params[$field]) &&
           !CRM_Utils_System::isNull($params[$field])
         ) {
-          $queryParams = $params[$field];
-          if (($field == 'mailing_low' || $field == 'mailing_high') && empty($params['mailing_relative'])) {
-            $time = (strrpos($field, 'high')) ? '23:59:59' : '00:00:00';
-            $queryParams = CRM_Utils_Date::isoToMySQL($queryParams . ' ' . $time);
-          }
-          $parent->set($field, $queryParams);
+          $parent->set($field, $params[$field]);
         }
```

**Comment by seamuslee001** [comment]
@eileenmcnaughton i have updated this with your proposed change

**Comment by eileenmcnaughton** [comment]
Unrelated fail

**Pull request merged**
