### PR TITLE
Bump minimum upgradable version to 4.5.9

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Another year, another long-overdue bump to our minimum upgradable version.
4.4 was [released back in 2013](https://civicrm.org/blog/colemanw/civicrm-44-is-here), so I think it's time to finally say goodbye.

Before
----------------------------------------
Minimum upgradable version 4.4.7

After
----------------------------------------
Minimum upgradable version 4.5.9

Comments
----------------------------------------
People using older versions can still upgrade, but they will have to do it in steps, using an intermediate version like 4.7 before upgrading to the latest.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw this seems fine to me - I'm just wondering about docs updates

**Comment by colemanw** [comment]
Here is a docs update: https://lab.civicrm.org/documentation/docs/sysadmin/-/merge_requests/316

**Comment by colemanw** [comment]
Not surprisingly, test failures indicate that you are no longer able to upgrade from version 4.5.0!
@seamuslee001 I can't remember what you did to fix that last year for #17750 but we need to do it again to bump up the starting version in the upgrade tests.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
re coleman's question the answer is here https://github.com/civicrm/civicrm-buildkit/pull/648

**Comment by demeritcowboy** [comment]
Not a blocker but there's a couple spots like this in SEPA Direct Debit: https://github.com/Project60/org.project60.sepa/blob/0e787cca54a0a471d4653206cc45e2bb034a26a0/CRM/Sepa/DAO/SEPAMandate.php#L186

Maybe that needs its DAO's regenerated?

**Comment by colemanw** [comment]
Yes it definitely does! Blame says it was last regenerated 8 years ago.
https://github.com/Project60/org.project60.sepa/blame/0e787cca54a0a471d4653206cc45e2bb034a26a0/CRM/Sepa/DAO/SEPAMandate.php#L186

**Pull request merged**
