### PR TITLE
SearchKit - allow searches based on relationships

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Allows searches to be based on relationships:

image

Before
----------------------------------------
Searches with Contact as an entity could add Related Contacts as a join, but the base table could not be relationship.

After
----------------------------------------
Searches can use Relationships as the base entity, and default action links are provided (view/edit/delete relationship)

Technical Details
----------------------------------------
This makes it possible to use a bridge entity for the base of a search (only if it is annotated `@searchable primary|secondary`)

It also ensures that fields needed for links are available in search displays (previously it ensured ID was returned but some links require other fields as well).

Comments
------------------------
This gets us inches away from being able to replace the Relationships tab on the contact summary screen. If SearchKit and Afform were force-enabled on every install, I'd do it right now.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw  - do you have any expectation of contact actions being available?

image

Or other entities

image

url on search site
http://core-20558-3folt.test-1.civicrm.org:8001/civicrm/admin/search#/create/RelationshipCache?params=%7B%22version%22:4,%22select%22:%5B%22id%22,%22near_contact_id%22,%22near_contact_id.display_name%22%5D,%22orderBy%22:%7B%7D,%22where%22:%5B%5D,%22groupBy%22:%5B%5D,%22join%22:%5B%5D,%22having%22:%5B%5D%7D

**Comment by colemanw** [comment]
That would take some additional refactoring of the SearchKit Admin screen. But (and I think this is more important) the link builder works for SearchDisplays based on relationships.
image

**Comment by eileenmcnaughton** [comment]
OK - I feel like ideally we should be able to add links to edit or view the relationship too - but I guess you are saying 'this is the scope of this change'  - and it works within that scope

**Comment by colemanw** [comment]
Other than the links at the top of that menu?

**Pull request merged**
