### PR TITLE
Revert "Revert #18005 Fix buggy placement of icons"

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Re-apply https://github.com/civicrm/civicrm-core/pull/18005  for 5.31 - it was reverted out of 5.29 purely due to the timing being too short to communicate

This reverts commit 353282c5b079c879af998149dcdb9e994edaec87.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
I compared the two PRs and except for ckeditor which got moved as part of the [recent security update](https://github.com/civicrm/civicrm-core/commit/f7d209264668d2f0e3d87fe1b26c1d996a788828) where it's already changed to remove the css class they're the same.

**Comment by eileenmcnaughton** [comment]
@colemanw so we have communicated about this now - do you want to re-check this & the follow up fix - the follow up fix it the bigger one

**Comment by agh1** [comment]
I'm preparing a new PR now that combines the commits from #18005 and #18087 because it's probably simpler to manage that way.

**Comment by agh1** [comment]
See #18410 for the big combined button PR for 5.31

**Comment by eileenmcnaughton** [comment]
Closing as replaced ^^

**Pull request closed without merging**
