### PR TITLE
dev/core#1760 Improve js escaping in smarty {ts}

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
More thoroughly escapes js strings in smarty `{ts}` to avoid issues with html.

Before
----------------------------------------
Minimal escaping adds slashes to single quotes.

After
----------------------------------------
Uses `json_encode` to completely escape string, converting html entities to unicode to avoid any conflicts.

Technical Details
----------------------------------------
Embedding javascript in an html template using smarty is tricky. You've got a language (js) embedded in a language (html) processed with another language (smarty). This can cause conflicts with certain characters that have special meanings in more than one language.

This  PR attempts to mitigate the risk of conflicts by thoroughly escaping all possible html entities in a javascript string before printing it out to html, converting single and double quotes, angle brackets and ampersands to unicode.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
It seems ok so far. I've added some related notes in the lab ticket since now that you've prompted taking a closer look it made me wonder why `escape='js'` even exists.

One possible issue, but I haven't found a core example, is if you're relying on the fact that it DOESN'T escape html in order to insert html. Since ampersands and angle brackets now get converted. Are there any uses out there like that? Probably rare if any.

**Comment by demeritcowboy** [comment]
* General standards
    * [`r-explain`] __PASS__
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__ It might change how things work if devs are using it in wacky string concatenation ways, but then they're being weird.
    * [`r-run`] __PASS__
      * No issues in the places I looked at, but noting that it's used a lot of places.
      * Also just to verify the `sql` one, the sql files output by gencode.php are the same as before.
* Developer standards
    * [`r-tech`] __pass__
      * A little nervous about this since ts is used everywhere in different contexts: There's php ts(), javascript ts(), javascript CRM.ts(), smarty {ts}. As far as I can see the code change only affects escape=js which is only used in smarty, but there's a refactor here too. To me it looks ok.
    * [`r-code`] __PASS__
    * [`r-maint`] __Undecided__
      * ts in general might be well tested. Not sure about escape='js'.
    * [`r-test`] __PASS__

**Comment by mlutfy** [comment]
I did a bit of testing on the test site. If we switch to Russian, the text gets encoded like this:

```
var archiveWarning = "\u0412\u041d\u0418\u041c\u0410\u041d\u0418\u0415: \u0412\u044b \u043f\u0435\u0440\u0435\u043a\u043b\u044e\u0447\u0430\u0435\u0442\u0435\u0441\u044c \u0438\u0437 \u0442\u0435\u0441\u0442\u043e\u0432\u043e\u0433\u043e \u0440\u0435\u0436\u0438\u043c\u0430 (\u043d\u0430\u043f\u0440\u0430\u0432\u043b\u044f\u0442\u044c \u0432 \u0431\u0430\u0437\u0443 \u0434\u0430\u043d\u043d\u044b\u0445) \u0432 \u00ab\u0436\u0438\u0432\u043e\u0439\u00bb. \u041f\u0440\u043e\u0432\u0435\u0440\u044c\u0442\u0435 \u0420\u0430\u0441\u0441\u044b\u043b\u043a\u0438 -\u003E \u0421\u043e\u0445\u0440\u0430\u043d\u0451\u043d\u043d\u044b\u0435 \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438 \u0438 \u0443\u0434\u0430\u043b\u0438\u0442\u0435 \u0432\u0441\u0435 \u0442\u0435\u0441\u0442\u043e\u0432\u044b\u0435 \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438 \u0441\u043e \u0441\u0442\u0430\u0442\u0443\u0441\u043e\u043c, \u043e\u0442\u043b\u0438\u0447\u043d\u044b\u043c \u043e\u0442 \u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u043e, \u0434\u043e \u043f\u0435\u0440\u0432\u043e\u0433\u043e \u0437\u0430\u043f\u0443\u0441\u043a\u0430 \u043f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u0449\u0438\u043a\u0430 \u0440\u0430\u0441\u0441\u044b\u043b\u043e\u043a. \u0422\u0430\u043a \u0432\u044b \u0443\u0434\u043e\u0441\u0442\u043e\u0432\u0435\u0440\u0438\u0442\u0435\u0441\u044c, \u0447\u0442\u043e \u044d\u0442\u0438 \u0442\u0435\u0441\u0442\u043e\u0432\u044b\u0435 \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438 \u043d\u0435 \u0431\u0443\u0434\u0443\u0442 \u0440\u0435\u0430\u043b\u044c\u043d\u043e \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u044b."
```

Which I guess is fine. It looks a bit like malware, but I guess a malware detector would have to be pretty zealous.

In French it was OK:

```
var archiveWarning = "ATTENTION : Vous allez basculer du mode Test (Rediriger vers la Base de Donn\u00e9es) au mode Actif. Cliquez sur V\u00e9rifiez les Mailings \u003E Mailing archiv\u00e9s, et effacez tous les mailings de test qui n\u0027ont pas le statut \u0022Termin\u00e9\u0022 avant de lancer les t\u00e2ches de travaux  programm\u00e9s automatiques de mailing pour la premi\u00e8re fois. Cela vous garantira qu\u0027aucun mailing de test ne soit r\u00e9ellement envoy\u00e9."
```

> "Since ampersands and angle brackets now get converted. Are there any uses out there like that? Probably rare if any"

I had a quick grep looking for tags such as `<strong>` or `<a>` inside a `ts`, for javascript inside smarty, but haven't found any.

This example caught my eye as being risky, since params are not escaped:

templates/CRM/Case/Form/ActivityToCase.tpl:

```
CRM.alert(ts(statusMsg, {1: '<a href="' + caseUrl + '">' + caseTitle + '</a>'}), '{/literal}{ts escape="js"}Saved{/ts}{literal}', 'success');
```

templates/CRM/Report/Form/Actions.tpl:

```
message: ts({/literal}'{ts escape='js' 1='<em>%1</em>'}Add all contacts to %1 group?{/ts}'{literal}, {1: $('option:selected', '#groups').text()})
```

**Comment by colemanw** [comment]
@mlutfy the russian string might look better if we use the `JSON_UNESCAPED_UNICODE` flag. I guess that would be fine.

**Comment by colemanw** [comment]
@mlutfy I've added that flag - can you do one more quick test before merging?

**Comment by mlutfy** [comment]
Yep, looks good!

```
      var archiveWarning = "ВНИМАНИЕ: Вы переключаетесь из тестового режима (направлять в базу данных) в «живой». Проверьте Рассылки -\u003E Сохранённые рассылки и удалите все тестовые рассылки со статусом, отличным от Выполнено, до первого запуска планировщика рассылок. Так вы удостоверитесь, что эти тестовые рассылки не будут реально отправлены.";
```

French:

```
      var archiveWarning = "ATTENTION : Vous allez basculer du mode Test (Rediriger vers la Base de Données) au mode Actif. Cliquez sur Vérifiez les Mailings \u003E Mailing archivés, et effacez tous les mailings de test qui n\u0027ont pas le statut \u0022Terminé\u0022 avant de lancer les tâches de travaux  programmés automatiques de mailing pour la première fois. Cela vous garantira qu\u0027aucun mailing de test ne soit réellement envoyé.";
```

**Pull request merged**
