### PR TITLE
[almost NFC] Save 12.6 quectoseconds when computing true or false

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
This is so much faster.

### CODE REVIEW

**Comment by colemanw** [comment]
@demeritcowboy I think the `!!` casting does serve a purpose here. It's the equivalent of `(bool)` casting in php.

**Comment by demeritcowboy** [comment]
Ah ok.

**Comment by colemanw** [comment]
You mean !!ok.

**Comment by demeritcowboy** [comment]
Hehe.

Yeah I see now it's "undefined" sometimes.

**Pull request closed without merging**
