### PR TITLE
Ensure relative dates are preserved for custom fields in smart group

### PR DESCRIPTION
**Pull request by jmcclelland**
See https://lab.civicrm.org/dev/core/issues/389

Overview
----------------------------------------

Saving smart groups with custom fields in which a relative date is specified does not work as expected. The date range is hard coded and does not updated when re-run on a different day.

Before
----------------------------------------
When you create a smart group using a custom date field and you choose a relative date option (e.g. This calendar year), the field is saved with the hard-coded dates for the current time, rather than the relative date range specified.

After
----------------------------------------
With this patch in place, relative dates are properly saved and displayed to the user.

### CODE REVIEW

**Comment by sleewok** [comment]
Is this failing because it is using "custom_13" to run the unit test? We will try this on our local dev.

**Comment by jmcclelland** [comment]
Ah - thanks for the feedback. Is there a protocol I should use? I could replace it with a very high number to avoid conflicts. Or, do I need to actually create a custom field and then use the number that I created?

**Comment by seamuslee001** [comment]
@jmcclelland yes you will need to create the custom group + custom field and you should delete them after the last assert you can see https://github.com/civicrm/civicrm-core/blob/master/tests/phpunit/api/v3/CustomFieldTest.php for examples on using API to create custom group etc

**Comment by sleewok** [comment]
We applied the patch on our dev and it doesn't seem to fix the issue for us. The dates do not remain relative after creating the smart group.

**Comment by jmcclelland** [comment]
@sleewok - Weird. I'm not sure why it is not working for you. I just made a screencast demonstrating it working for me:

https://lab.civicrm.org/dev/core/uploads/638e90393e26bf313e485256286fae37/relative-custom-date-fields.webm

Can you take a look and let me know if we are doing different things to test?

@seamuslee001 thanks for the tip. I will rework the test.

**Comment by sleewok** [comment]
it is going to fail again because of this: 
error: tests/phpunit/CRM/Contact/BAO/SavedSearchTest.php: No such file or directory.

**Comment by seamuslee001** [comment]
@sleewok yes a unit test for this kind of change would be needed to ensure we lock in the fix.

**Comment by seamuslee001** [comment]
@sleewok i should also note that the most recent run of unit test is equivalent to a "pass" (tests are failing for environmental reasons following test boxes rebuild) and i note the unit test @jmcclelland actually passed https://test.civicrm.org/job/CiviCRM-Core-PR/22446/testReport/(root)/CRM_Contact_BAO_SavedSearchTest/testCustomFieldRelativeDates/

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
this seems to have had adequate testing by @sleewok & it has test coverage. I'm expecting the tests should be OK now & we can merge

**Comment by jasonobrown** [comment]
I believe there's still an issue with this.  Although the relative dates are initially correct, once the relative time period has passed (ie. 1 week) the Smart Group Criteria is no longer correct.  For example, I created a smart group with a custom field checking for dates matching "This Week".  After 1 week had passed, I went back in and it returns 0 results (it should be returning some results).  The message after clicking edit smart group search criteria shows 

"No matches found for:
Welcome Card Date BETWEEN 'December 2nd, 2018 12:00 AM AND December 8th, 2018 11:59 PM' ...AND...
Welcome Card Date BETWEEN 'November 25th, 2018 12:00 AM AND December 1st, 2018 11:59 PM'"

However, when I go in and look at the Welcome Card Date field (under edit criteria) it still says, "This week".  If I hit search (without making any changes) it searches using the correct parameters.

**Comment by sleewok** [comment]
This happens on my install as well.

**Pull request merged**
