### PR TITLE
CRM-16904, updated 4th parameter to use base url

### PR DESCRIPTION
**Pull request by pradpnayak**
---
- CRM-16904:
  https://issues.civicrm.org/jira/browse/CRM-16904

### CODE REVIEW

**Comment by davecivicrm** [comment]
@pradpnayak Can you rebase this one please.

**Comment by pradpnayak** [comment]
I did just now :)

**Comment by pradpnayak** [comment]
Is test failure related to fix?

**Comment by davecivicrm** [comment]
Test failures unrelated.

**Pull request merged**
