### PR TITLE
(NFC) Update view issues and report bugs link in footer to point to the lab

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
ping @eileenmcnaughton @bgm @totten

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Seems OK - @seanmadsen ? 

BTW this is my preferred link - https://lab.civicrm.org/groups/dev/-/boards - makes it easy to spot the big issues

**Comment by seamuslee001** [comment]
Tho on the board its not as obvious as on the list page how to create a new issue i guess but 6 of 1 half a dozen of the other to me

**Comment by seamuslee001** [comment]
@eileenmcnaughton @seanmadsen do either of you like one of Tim's suggestions

**Comment by eileenmcnaughton** [comment]
@seamuslee001 this sounds like it is speaking my language "in case y'all are too impatient about the updates ....."

Let's do that & merge & close & move on. Easy to re-change later

**Pull request merged**
