### PR TITLE
[NFC] Fix comment block for variable declarations

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Update variable declaration blocks to match correct format

Before
----------------------------------------
'Integer' etc

After
----------------------------------------
int, string

Technical Details
----------------------------------------
Per https://github.com/civicrm/coder/pull/7

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton 

> Parser.php:1359, CommaLastItem, Priority: Normal
--
A comma should follow the last multiline array item. Found: 1

**Comment by eileenmcnaughton** [comment]
@colemanw yeah - that was already there but I fixed - I think we should merge civicrm/coder#7 - I'm not finding more of the newly enabled check now than others - feels not too onerous to me

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Pull request merged**
