### PR TITLE
CRM-20733 - Relationship report improvements

### PR DESCRIPTION
**Pull request by yashodha**
* [CRM-20733: Relationship report improvements](https://issues.civicrm.org/jira/browse/CRM-20733)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@yashodha if you haven't got someone to review these old 4.6 ones it would probably be better to close them & track them through JIRA (ditto any other PRs that are stuck & there is no clear path to getting them unstuck)

**Comment by yashodha** [comment]
@eileenmcnaughton we are deploying this one for our customers and should be pretty safe. Should I get Sunil to confirm?

**Comment by eileenmcnaughton** [comment]
@yashodha you might be able to get @jackrabbithanna to review the 4.6 PRs then. I'm mostly just trying to get stuck PRs closed but it's up to Skvare / Compucorp if they want to merge them

There is a bit of an overhead in having PRs sitting in the PR queue (people spending time assessing them only to re-conclude they are stuck, useful PRs being obscured by ones that are really using github as an issue tracker etc) so in general I'm trying to encourage people to close PRs that are stuck with no clear path forwards. In this case the issue is that only security fixes are really going into 4.6 - so it's unclear if there is a path forwards for this one

**Comment by yashodha** [comment]
@jackrabbithanna yeah, this patch only exposes permission columns and sorting and does NOT deal with is_deleted logic in where clause. I wanted to make bare minimum changes when backporting to 4.6.

**Comment by jackrabbithanna** [comment]
Jenkins test this please

**Comment by jackrabbithanna** [comment]
I'm going to allow this merge if the test suite passes, since it only adds columns and order by to the report for permission to edit  contact a and permission to edit contact b .

**Comment by jackrabbithanna** [comment]
I've tested this code...
And it throws a lot of errors for me...

Perhaps it need to be refactored since its old...

if I leave public function orderBy() { in there, it all seems to work....

@yashodha  why does this method need to be removed?

**Comment by yashodha** [comment]
@jackrabbithanna -  don't recall the reason probably oversight.
Can you please check now?

**Comment by eileenmcnaughton** [comment]
@jackrabbithanna can we merge this or close it if it's not really going to get reviewed  - am trying to get the PR q down a bit

**Comment by eileenmcnaughton** [comment]
@jackrabbithanna I'll close this & let you re-open it if you want to review it (since this seems to be the third time this week I've spent time trying to figure out the status of it better to have it out of the q until there is a path)

**Pull request closed without merging**
