### PR TITLE
dev/core#5416 - Fix missing dates in FormBuilder

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes https://lab.civicrm.org/dev/core/-/issues/5416, replacement for #31103 

Before
----------------------------------------
Missing date fields.

After
----------------------------------------
Fixed.

Technical Details
----------------------------------------
This was an oversight from #30964

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw failures relate

api\v4\Action\AutocompleteTest::testMailingAutocompleteNoDisabledGroups
Undefined array key "input_type"

/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/Civi/Api4/Service/Spec/SpecFormatter.php:293
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/Civi/Api4/Service/Spec/SpecFormatter.php:95
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/Civi/Api4/Service/Spec/SpecGatherer.php:177
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/Civi/Api4/Service/Spec/SpecGatherer.php:124
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/Civi/Api4/Service/Spec/SpecGatherer.php:80
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/Civi/Api4/Generic/DAOGetFieldsAction.php:42
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/Civi/Api4/Generic/BasicGetFieldsAction.php:97
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/Civi/Api4/Generic/AbstractAction.php:464
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/Civi/Api4/Query/Api4SelectQuery.php:75
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/Civi/Api4/Query/Api4EntitySetQuery.php:47
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/Civi/Api4/Action/EntitySet/Get.php:56
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/Civi/Api4/Provider/ActionObjectProvider.php:70
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/Civi/API/Kernel.php:153
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/Civi/Api4/Generic/AbstractAction.php:256
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/api/api.php:91

**Comment by colemanw** [comment]
@eileenmcnaughton fixed

**Comment by justinmosier** [comment]
I'm reviewing this

**Comment by justinmosier** [comment]
Adding details since I'm new to PR reviews...

I tested this using the demo site generated by Jenkins. I had to manually install the FormBuilder extension via the Civi UI because the demo site didn't have it enabled.

**Test 1: PASSED: Date field displays properly within FormBuilder (for Contact Searches)**
image


**Test 2: PASSED: Date field displays properly and filters the data properly on the front end (for Contact Searches)**
image


**Test 3: PASSED: Date field displays properly within FormBuilder (for Activity Searches)**
image


**Test 4: PASSED: Date field displays properly and filters the data properly on the front end (for Activity Searches)**
image

Assuming if it works ok for Contact and Activity searches, it's working ok for other entities.

@colemanw, I think this is good to go.

**Comment by colemanw** [comment]
Thanks @justinmosier

**Pull request merged**
