### PR TITLE
[php8-compat] Upgrade TCPDF version to support php8

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This upgrades the TCPDF Library to be compatible with php8

Before
----------------------------------------
TCPDF version not compatible with php8

After
----------------------------------------
TCPDF compatible with php8

Change log is here https://github.com/tecnickcom/TCPDF/blob/main/CHANGELOG.TXT#L2 and nothing jumps out at me as major issue 

ping @demeritcowboy @eileenmcnaughton

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by demeritcowboy** [comment]
I suppose I should test this with Cdntax.


> Fix vulnerability to roman numeral bombs

Ah good this was fixed in version VI.IV.0 on MMXXI-III-XXVII

**Comment by demeritcowboy** [comment]
A couple things threw me with this but in terms of r-run it's fine. Also checked mailing labels.

1. The version it stamps on pdf files is still 6.3.5 - see https://github.com/tecnickcom/TCPDF/blob/6.4.1/include/tcpdf_static.php#L58
1. There is no release 6.4.2 yet - does 6.4.1 still meet the php 8 needs?

If this is meeting the php 8 needs then I think it's mergeable.

**Comment by seamuslee001** [comment]
@demeritcowboy I found it worked fine for the unit test issue I had on php8, I'm going to merge based on the above

**Pull request merged**
