### PR TITLE
CRM-19729 : token {contribution.financial_type} works but is not list…

### PR DESCRIPTION
**Pull request by yashodha**
…ed as available

### CODE REVIEW

**Review by jitendrapurohit — APPROVED** [review]

**Comment by eileenmcnaughton** [comment]
I wonder if we should add this to the list when there is another ticket open about removing this? I kind of lean to having a token that offers all the financial types in the contribution (as an array & as a group_concat string) & exposing those

**Comment by yashodha** [comment]
@eileenmcnaughton  : I think we should merge it for now, since the underlying code supports the token anyway.
Also I think we should comment on CRM-17140 to remove reference to contribution.financial_type token as well when we actually get to implementing the depreciation of financial type.

**Comment by eileenmcnaughton** [comment]
The underlying code supports it but if it isn't in the UI we don't officially support it. I don't want us to officially support it if we think it should be changed

**Comment by mlutfy** [comment]
Closing this PR: it's been almost a year and no consensus. I will leave the JIRA ticket open, since it's still a valid issue.

**Pull request closed without merging**
