### PR TITLE
Fix next scheduled contribution date on update subscription field, use datepicker

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Switch UpdateSubscription to render as a date datepicker and add metadata for all date fields in ContributionRecur. 

Before
----------------------------------------
UpdateSubscription for recurring contributions tried & fails to use old jcalendar date field. Renders as text instead

After
----------------------------------------
UpdateSubscription for recurring contributions uses "new" datepicker field. Oh & by the way - it works now :-)

screenshot 2018-10-06 16 15 00

Technical Details
----------------------------------------
Metadata for the field is required in the schema as these fields are auto-added by generic code. I've added the necessary "formatType" metadata to all the date fields in ContributionRecur.

### CODE REVIEW

**Comment by colemanw** [comment]
@mattwire shouldn't this include tpl updates as well?

**Comment by mattwire** [comment]
> @mattwire shouldn't this include tpl updates as well to remove the jcalendar includes?

No, if you look at the template `CRM\Contribute\Form\UpdateSubscription.tpl` you'll see it just contains an array of fields in `$editableScheduleFields`.  There was some work done in the past to switch over some core fields using this method but they have to be whitelisted by adding the FALSE to $this->addField

**Comment by colemanw** [comment]
@eileenmcnaughton can you help me understand how those legacy date fields were able to exist on the form yet the .tpl file did not include the jcalendar?
Also typically when converting date fields we need to remove the legacy handling of default values as well. Is that not necessary here?

**Comment by mattwire** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@colemanw we figured out the answer as to how it currently works without jcalendar.tpl ... it doesn't!

Merging this as much better :-)

**Pull request merged**
