### PR TITLE
CRM-20774 - Add check for existing key index in table

### PR DESCRIPTION
**Pull request by jitendrapurohit**
`getMissingIndices()` retrieves the indices based on the value and not on the key. So there is a possibility that it'll also fetch the value -

- if they exist in wrong order.
- some column missing for the index key.

For eg.

    $requiredIndex = index_all - (cacheKey, entity1, entity2, entity3, is_selected).

    $existingIndex = index_all - (cacheKey, entity1, entity2, entity3).

As `is_selected` is not in the table, `updateindices` would attempt to re-create the index which will lead to duplicate `index_all` key error.

This PR displays the existing keys on system status page and ask the user to drop the index so that civi creates the correct one with all columns again.

Test added.

---

 * [CRM-20774: Add check for existing index keys\(different values\) while creating missing indices.](https://issues.civicrm.org/jira/browse/CRM-20774)

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
This is how it looks - 

image

**Comment by seamuslee001** [comment]
@jitendrapurohit looks like you got some test failures buddy https://test.civicrm.org/job/CiviCRM-Core-PR/15987/testReport/(root)/api_v3_SystemCheckTest/testSystemCheckBasic/

**Comment by xurizaemon** [comment]
Oh, I thought we'd fixed "Update Incices" but I see it in the screenshot above.

Make sure you haven't brought back "Incices" instead of "Indices"!

(I don't think you have by looking at the changes, but ...)

**Comment by jitendrapurohit** [comment]
No, the screenshot is from one of our dev site(inz) which is on 4.7.19 and the typo fix was in 4.7.20. I've checked on local(master) and the button looks correct there.

**Comment by seamuslee001** [comment]
This looks good to me, my only thoughts is perhaps there should be a message about reporting it to your administrator if you cannot alter the database or do not know now? ping @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
I'm inclined to think this is good to merge & we could cover the messaging as a follow up?

**Comment by seamuslee001** [comment]
I would be ok with that but do you think that would be a good text addition?

**Comment by eileenmcnaughton** [comment]
yep

**Comment by seamuslee001** [comment]
Happy for this to be merged then

**Comment by jitendrapurohit** [comment]
Thanks @all!

**Pull request merged**
