### PR TITLE
Rename balanceTrxnParams to paymentTrxnParams [REF]

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Backport of https://github.com/civicrm/civicrm-core/pull/15535 for cleaner regression patching

### CODE REVIEW

**Comment by mattwire** [comment]
See comments on #15535 - I don't think this is the right change to make

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by mattwire** [comment]
@eileenmcnaughton Fine! you've sold this via #15535

**Pull request merged**
