### PR TITLE
add json output to cli.php

### PR DESCRIPTION
**Pull request by caracolmzd**

### CODE REVIEW

**Comment by ginkgomzd** [comment]
looks like this file hasn't changed since 4.4 or before. This could be applied to other branches.

**Comment by totten** [comment]
There's a similar patch pending against 4.6 in https://github.com/civicrm/civicrm-core/pull/5840 (specifically, https://github.com/totten/civicrm-core/commit/9eef4d12e47a49ef4534a6206e3dd517b05383d3 ). @ginkgomzd, are there elements of the two we should combine?

**Comment by ginkgomzd** [comment]
@totten the only differences I see are your use of JSON Pretty Print and that I included a short flag.
I think having a short flag (-J) is a feature, especially for people actually using this at the command line. I agree, --json is more self-documenting.

I see you are checking if JSON_PRETTY_PRINT is defined. I don't know how this would not be defined since it is a PHP pre-defined constant. Seems safe to assume then that pretty-print will be used, introducing extra characters into the output. I think this is of limited utility. If it gets dumped to a web browser... you won't see it.. if you have a lot of data returned, it will help little to have it pre-formatted. 
Seems like it is just bloating the data. I say, it's better to exclude the whitespace, and if one wants something more human-readable, they can use the other output option.

**Comment by totten** [comment]
Agree that the short flag (-J) is a bit nicer for humans sitting at the keyboard. :)

By the same token, I like pretty-printing as a default. From my perspective, the main use-case of `cli.php -J` comes when a sysadmin pipes data to other commands, but... even then... I often test commands without piping to inspect the output and make sure it would send the right data. That's easier with pretty-printing. Not sure when `cli.php` would be dumped to a web browser.

`JSON_PRETTY_PRINT` is defined in [PHP 5.4+](http://php.net/json_encode). In PHP 5.3 (which is still officially supported by Civi and used on the test servers), the constant is undefined; accessing it generates warnings/errors.

**Comment by totten** [comment]
I've copied the `-J` option into #5840 (26604a65).

**Pull request closed without merging**
