### PR TITLE
CRM-17355 - Contribution notes on membership receipt template.

### PR DESCRIPTION
**Pull request by johanv**
It would work like this:

```
  {if $notes}
    {foreach from=$notes item=note key=id}
    {$note}<br />
    {/foreach}
  {/if}
```

---
- CRM-17355: Make it possible to print contribution notes on 'Memberships - Receipt (on-line)' template
  https://issues.civicrm.org/jira/browse/CRM-17355

### CODE REVIEW

**Comment by johanv** [comment]
Not sure this is clean enoguh for merging. But maybe it is useful for someone :-)

**Comment by colemanw** [comment]
Seems like you could as easily do this all within the template itself by calling

    {crmAPI var='notes' entity='Note'

**Comment by johanv** [comment]
Cool! I didn't realize I can call the api from smarty.

**Comment by colemanw** [comment]
Yes, the Api Explorer will generate the syntax for you.

**Comment by johanv** [comment]
Thanks for your useful suggestion.

It was not simple to access the contribution ID from the smarty template though. I had to extract it from the line items. But it works, and without patches.

**Pull request closed without merging**
