### PR TITLE
dev/core#1064 Allow personalised 'view in browser' links for mass emails

### PR DESCRIPTION
**Pull request by JKingsnorth**
See https://lab.civicrm.org/dev/core/issues/1064 for full details

### CODE REVIEW

**Comment by mattwire** [comment]
@JKingsnorth I'll review yours if you'll review mine.. :-) https://github.com/civicrm/civicrm-core/pull/15487

**Comment by JKingsnorth** [comment]
> @JKingsnorth I'll review yours if you'll review mine.. :-) #15487

Deal!

**Comment by mattwire** [comment]
@JKingsnorth This makes sense I think - so to be clear, this won't change the {mailing.viewUrl} token but allows you to build your own URL that will allow you to view a personalised version of the mail?
Can you create a docs PR over at https://github.com/civicrm/civicrm-user-guide

**Comment by JKingsnorth** [comment]
Yes, thanks @mattwire , I'll write a docs PR next week.

**Comment by JKingsnorth** [comment]
@mattwire https://github.com/civicrm/civicrm-user-guide/pull/417

However, I haven't checked this on Wordpress or Joomla, as I don't have those dev environments set up =[

**Comment by mattwire** [comment]
@lcdservices @kcristiano Are you able to test this on Joomla / Wordpress respectively?

**Comment by kcristiano** [comment]
@mattwire did an `r-run` with WP works fine with both cleaner urls and without.

**Comment by JKingsnorth** [comment]
Thanks very much for testing it.

**Comment by MikeyMJCO** [comment]
This PR has documentation - the needs documentation label can be removed.

@mattwire

**Comment by JKingsnorth** [comment]
Cool, so this should be good to merge, but let me know if anything else is needed?

**Comment by MikeyMJCO** [comment]
Thanks @colemanw this will hit with 5.24 I'm guessing?

**Comment by JKingsnorth** [comment]
Thanks all =]

**Pull request merged**
