### PR TITLE
Fixes to Group Page PHPUnit test

### PR DESCRIPTION
**Pull request by josephlacey**

### CODE REVIEW

**Comment by totten** [comment]
Thanks for submitting. Really looking forward to this. When we get `CRM_AllTests` passing, we'll be able to configure Github/Jenkins to run it for all PRs (in addition the current PR tests, `api_v3_AllTests` and `Civi\AllTests`), which should prevent future regressions in the CRM suite.

Question/clarification: The patch itself doesn't seem dangerous and it passes the other suites. But... when I run `CRM_Group_Page_AjaxTest` locally, it still shows the same errors as https://test.civicrm.org/job/CiviCRM-Core-Matrix/CIVIVER=master,label=ubuntu1204/2162/testReport/ , so the current symptoms are still outstanding. Do you think we should merge this (because it addresses a different/less-visible problem), or do you want to leave it open (so that you can continue pushing work to this branch/PR)?

**Comment by josephlacey** [comment]
On 02/18/2016 12:14 AM, Tim Otten wrote:
> Question/clarification: The patch itself doesn't seem dangerous and it
> passes the other suites. But... when I run |CRM_Group_Page_AjaxTest|
> locally, it still shows the same errors as
> https://test.civicrm.org/job/CiviCRM-Core-Matrix/CIVIVER=master,label=ubuntu1204/2162/testReport/
> , so the current symptoms are still outstanding. Do you think we should
> merge this (because it addresses a different/less-visible problem), or
> do you want to leave it open (so that you can continue pushing work to
> this branch/PR)?

I see.  I suspect this fix needs to be implemented on all the tests for
this page, not just the one I did.  Tim, is
testGroupListViewAllContacts() still on the list of failures?  If not,
we should be good and I can push up a fix for the other tests pretty quick.

I'd certainly wait on merging this in until all of them are fixed.

**Comment by josephlacey** [comment]
On 02/19/2016 12:43 PM, Joseph Lacey wrote:
> 
> On 02/18/2016 12:14 AM, Tim Otten wrote:
>> 
>> Question/clarification: The patch itself doesn't seem dangerous and it
>> passes the other suites. But... when I run |CRM_Group_Page_AjaxTest|
>> locally, it still shows the same errors as
>> https://test.civicrm.org/job/CiviCRM-Core-Matrix/CIVIVER=master,label=ubuntu1204/2162/testReport/
>> , so the current symptoms are still outstanding. Do you think we should
>> merge this (because it addresses a different/less-visible problem), or
>> do you want to leave it open (so that you can continue pushing work to
>> this branch/PR)?
> 
> I see.  I suspect this fix needs to be implemented on all the tests for
> this page, not just the one I did.  Tim, is
> testGroupListViewAllContacts() still on the list of failures?  If not,
> we should be good and I can push up a fix for the other tests pretty quick.
> 
> I'd certainly wait on merging this in until all of them are fixed.

In the interest of keeping this moving, I pushed my fixes for all the
other tests.  @totten, can you test these to see if the error is no
longer returned?

**Comment by totten** [comment]
Thanks for the updates. It's still producing errors, although they seem different now -- e.g. more `Undefined index: parentsOnly`.

I've posted updated results at: https://gist.github.com/totten/93b4c2da574e872045d2

**Comment by josephlacey** [comment]
On 02/25/2016 04:42 PM, Tim Otten wrote:
> Thanks for the updates. It's still producing errors, although they seem
> different now -- e.g. more |Undefined index: parentsOnly|.

@totten Changed the setup() $params that I think should fix this
problem.  Also added some fixes for the 9 failures.

**Comment by totten** [comment]
@josephlacey , definitely improved. https://gist.github.com/totten/e07a3e311cce891c32d5  Total #problems reduced from 31 to 22.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by josephlacey** [comment]
@totten After a busy few weeks and some yak shaving today, I've gotten the tests to all return without errors and failures.  Part of this is from dealing with the new $groups array structure that's returned to the test since we're calling a different object and method, namely the group id isn't the key anymore.  There were also a few random bugs, things undone from the previous changes.  Perhaps the more notable change is testGroupEditWithAndWithoutPermission() where the difference in permissions is only testable via the links.  It's a little cumbersome.

**Comment by monishdeb** [comment]
@josephlacey @totten can I cherry-pick the changes and submit a new PR with additional changes needed ? The reason for the conflict is recent changes done by me in tests :(

**Comment by monishdeb** [comment]
Closing it in favor https://github.com/civicrm/civicrm-core/pull/8103

**Pull request closed without merging**
