### PR TITLE
Correct CRM-17183 financial entry for cancelling a pending payment

### PR DESCRIPTION
**Pull request by guanhuan**
Fairly sure this issue has been there for a while. Suggest to merge to master as well.

---
- [CRM-17183: Cancelling a pending contribution will set accounting transactions incorrectly ](https://issues.civicrm.org/jira/browse/CRM-17183)

### CODE REVIEW

**Comment by davecivicrm** [comment]
@guanhuan This looks good / makes sense to me. Can you correct the extra whitespace on line 3006 so the PR test can complete. https://test.civicrm.org/job/CiviCRM-Core-PR/5420/checkstyleResult/new/

**Comment by guanhuan** [comment]
Hi @davecivicrm ,

Thanks. I have updated the PR to remove the white spaces. Please can you advise on the check fails? I think some of them are not caused by the PR and at least one of the rest does have conflict with the PR but problem might be on the test side? e.g. https://test.civicrm.org/job/CiviCRM-Core-PR/5440/testReport/junit/(root)/api_v3_ContributionTest/testCreateUpdateContributionCancelPending/

Best

Guanhuan

**Comment by davecivicrm** [comment]
Hi @guanhuan - syntaxConformanceTest failures are unrelated.
* Looks like you need to update api_v3_ContributionTest.testCreateUpdateContributionCancelPending to reflect the change in behavior. Might be just changing values in $compareParams near line 1938.
* Other test failures (including testCreateSingleNowDated) are unrelated (verified by running that test locally with and without this PR - passing for me in both cases).

**Comment by guanhuan** [comment]
Hi @davecivicrm ,

I have updated the unit test to cover the changes I made to the accounting behaviour. It looks fine now. Please let me know if it is OK to merge.

Best

Guanhuan

**Comment by davecivicrm** [comment]
Ran a test with patch and behavior looks correct now. Thanks @guanhuan

**Pull request merged**
