### PR TITLE
CRM-21231: On CiviMail screen make 'Review and Schedule' tab active if required fields are filled

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
The Review and Schedule tab selector becomes active after the user first visits the Review and Schedule screen by clicking the Next button on the Define Mailing screen. It would be preferable for the tab to behave like the next button - become active when all the required fields are completed.

Before
----------------------------------------
The second tab is disabled even if all required fields are filled. Screencast:
civimail-before

After
----------------------------------------
The second tab is enabled after all required fields are filled.
civimail-after

NOTE: Clear cache before testing.

---

 * [CRM-21231: On CiviMail screen make 'Review and Schedule' tab active if required fields are filled](https://issues.civicrm.org/jira/browse/CRM-21231)

### CODE REVIEW

**Comment by mlutfy** [comment]
As a user, we reviewed this patch on the test site created by Jenkins, and it looks good. Tested filing in the mandatory fields, reloading the screen and comparing with the current dmaster site.

However, there are failing tests.

(we are doing review/demo in a sprint)

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by lcdservices** [comment]
tested and this is working as expected.

**Comment by seamuslee001** [comment]
@monishdeb i tested this on a local dmaster. This looks good for when you have filled in all the fields. I agree this is a good improvement. I also noticed that the tab stayed active when i removed a required field e.g. Subject after it was made active. I think we may just need to check that its also watching for changes

**Comment by monishdeb** [comment]
@seamuslee001 thanks for pointing that out, seems like ```this.$validStep()``` never monitor the field changes constantly. Will take a look at it.

**Comment by monishdeb** [comment]
@seamuslee001 I have updated the PR, can you please check now?

**Comment by lcdservices** [comment]
@monishdeb @seamuslee001 just ran a test and it now watches for changes -- if the data in a required field is removed, the link is disabled. I think this is good to go.

**Comment by monishdeb** [comment]
@eileenmcnaughton / @colemanw can you please merge this PR?

**Pull request merged**
