### PR TITLE
dev/core/#3849 Fix profile group add for events

### PR DESCRIPTION
**Pull request by larssandergreen**
Overview
----------------------------------------
This code didn't properly add contacts to groups when using profiles that were set to add to groups in event registrations with multiple participants or multiple profiles.

Before
----------------------------------------
Secondary registrants were added to groups for the primary registrant profiles.
Additionally, when more than two profiles were in use, contacts were not added to all groups, depending on configuration of the event (didn't spend too much time digging into the details on what exactly was happening).

After
----------------------------------------
All registrants are added to the appropriate groups for the profiles set in the event registration.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@twomice here is the one

**Comment by eileenmcnaughton** [comment]
@larssandergreen I'm not going to insist on a unit test on this one cos it's probably a tricky one to do a test for but if you want help writing one next time jump on chat.civicrm.org....

**Comment by twomice** [comment]
I'm testing r-run on this now.

**Comment by twomice** [comment]
r-run: Pass


Steps to reproduce:

1. Create 4 new groups with appropriate names for this purpose:
   - pull-24633: primary 1
   - pull-24633: primary 2
   - pull-24633: additional 1
   - pull-24633: additional 2
1. Create 4 new profiles, each one configured for "Add contacts to a group?" to the like-named Group:
   - pull-24633: primary 1
   - pull-24633: primary 2
   - pull-24633: additional 1
   - pull-24633: additional 2
1. Create an event "Test Event" with online registration:
   - Register multiple participants? Yes
   - Include Profile (top of page): "pull-24633: primary 1"
   - Include Profile (bottom of page): "pull-24633: primary 2"
   - Profile for Additional Participants (top of page): "pull-24633: additional 1"
   - Profile for Additional Participants (bottom of page): "pull-24633: additional 2"
1. Navigate to the online registration form for event "Test 1" and submimt a single registration for 2 participants (noting that these are new gropus and therefore should not have any contacts assigned to them).
1. Observe groups for thes two contacts:
   - Expected: the Primary contact should have been added to groups "pull-24633: primary 1" and "pull-24633: primary 2"; and the additional participant should have been added to groups "pull-24633: additional 1" and "pull-24633: additional 2"


Before (on master):
1. Perform "Steps to Reproduce" and observe groups:
   - Observe (incorrect): the Primary contact has been added only to group "pull-24633: additional 1"; and the additional participant has been added only to group "pull-24633: primary 1" and "pull-24633: additional 2"

After (on patched master with this PR):
1. Perform "Steps to Reproduce" and observe groups:
   - Observed (correct): the Primary contact should have been added to groups "pull-24633: primary 1" and "pull-24633: primary 2"; and the additional participant should have been added to groups "pull-24633: additional 1" and "pull-24633: additional 2"

**Comment by eileenmcnaughton** [comment]
thanks @twomice @larssandergreen

**Comment by larssandergreen** [comment]
Thanks for reviewing @twomice and thanks @eileenmcnaughton.

**Comment by eileenmcnaughton** [comment]
a small inroads into your PRs :-)

**Comment by colemanw** [comment]
FYI this caused a regression because the new code adds a permission check that fails for anon users. See #25025

**Pull request merged**
