### PR TITLE
 CRM-19193: Report header and footer not included for print- and pdf-output

### PR DESCRIPTION
**Pull request by tschuettler**
https://issues.civicrm.org/jira/browse/CRM-19193

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
jenkins, test this please

**Comment by jitendrapurohit** [comment]
Tested, working fine

**Comment by seamuslee001** [comment]
Jenkins ok to test

**Comment by seamuslee001** [comment]
@totten Tim can you get Jenkins to test

**Comment by totten** [comment]
jenkins, ok to test

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by mlutfy** [comment]
(oops, misread.. nevermind!)

**Pull request merged**
