### PR TITLE
CRM-21372: Fix fatal error adding profile on Drupal 8

### PR DESCRIPTION
**Pull request by dsnopek**
See https://issues.civicrm.org/jira/browse/CRM-21372

### CODE REVIEW

**Comment by mlutfy** [comment]
ping @jackrabbithanna This seems OK to me. Any thoughts?

**Comment by jackrabbithanna** [comment]
@mlufty I'll test this against Drupal 8 and Drupal 7 this weekend
@dsnopek This one slipped by and I didn't notice, we'll get it checked out

**Comment by jackrabbithanna** [comment]
Jenkins test this please

**Comment by jackrabbithanna** [comment]
I'm a little unsure about how this will affect Drupal 7 and Drupal 6.
menu_rebuild() is a Drupal 7 api function, and removing it here would mean the menu wouldn't be rebuilt as intended.

Perhaps we need a condition in there to check whether this is Drupal 6 or 7, and if so keep the menu_rebuild(), and if Drupal 8, skip it....

Its either that, or the CRM/Utils/System/Drupal.php and CRM/Utils/System/Drupal6.php should each get the updateCategories() method, and make the call to menu_rebuild() there.

**Comment by mlutfy** [comment]
@jackrabbithanna  `$config->userSystem->updateCategories();` is perhaps not named very well, but it does a `menu_rebuild()` in d6/d7:

https://github.com/civicrm/civicrm-core/blob/master/CRM/Utils/System/DrupalBase.php#L440

**Comment by jackrabbithanna** [comment]
Well sure enough, I must have been looking at the wrong version of that file.
In that case, I did test the D8 functionality, and this patch works as advertised

**Comment by mlutfy** [comment]
(*[CiviCRM Review Template](https://docs.civicrm.org/dev/en/latest/standards/review/) WORD-1.0*)

* ([`r-jira`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-jira)) ✔
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) ✔
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) ✔
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) n/a
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) ✔
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) Based on testing by @jackrabbithanna 
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) n/a
* ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) ✔

**Pull request merged**
