### PR TITLE
CRM-21532 add missing French state/departments

### PR DESCRIPTION
**Pull request by sunilpawar**
Overview
----------------------------------------
Added missing French state/departments

---

 * [CRM-21532: Add state for France](https://issues.civicrm.org/jira/browse/CRM-21532)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I have some concern about the use of a hard-coded id in this (on the upgrade side). There are definitely a number of cases whereby this has been done in the past. But, given the prevalence of copy & paste in our codebase it's probably better we fix this to be a better model. Here are the lines from a previous insert. (I also note the fact 'id' is not in the fields - which is also more correct.)

SELECT @country_id := id from civicrm_country where name = 'Georgia' AND iso_code = 'GE';
INSERT INTO civicrm_state_province (country_id, abbreviation, name)

**Comment by yashodha** [comment]
@sunilpawar Can you please do the needful?

**Comment by sunilpawar** [comment]
@eileenmcnaughton  i have updated the insert statement query as per your suggestion.

**Comment by eileenmcnaughton** [comment]
I did a squash & merge since there were 2 commits - I think it's better for the submitter to squash them / use --amend though, because squash & merge commits look different in our history than normal merges

**Pull request merged**
