### PR TITLE
(WIP) CRM-21733: Adding the ability to override membership until specific date

### PR DESCRIPTION
**Pull request by omarabuhussein**
Overview
----------------------------------------
Improving membership status override to provide extra options to allow temporary status override.

Before
----------------------------------------
If you want to override a membership status, there is a checkbox field called (Status Override?) that you can check/uncheck.

error

After
----------------------------------------
Instead of having a checkbox called (Override Status?) in membership add/edit/renew form, it will be replaced with a select box that allow the user to choose one of three options : 

1- No
2- Override Permanently
3- Override until selected date

If the first option is selected, then the membership will behave as if the old (Override Status?) is unchecked, which means that the membership is subject to membership status rules.

If the 2nd option is selected, then the membership will behave as if the old (Override Status?) is checked, which mean that the membership status is overridden and is not subject to the membership statues rules.

If the 3rd option is selected, then a new field will appear allowing the user to choose a date, in this status, the membership will behave similar to option 2, but when today date is equal or less than the selected date, then the "Update Membership Statuses" scheduled job will automatically convert its status back to No, which means that the membership status is overridden  temporarily only for the selected date and after that it will revert back and be subject to membership status rules

Technical Details
----------------------------------------

 * [CRM-21733: Allow overriding membership status temporarily until specific date](https://issues.civicrm.org/jira/browse/CRM-21733)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Hey, I know this is wip - just a couple of things I thought skimming through it)
1) @mlutfy are we now at the point of not requiring a JIRA? Or is that still in progress
2) I think the api has to continue to support & interpret 'is_override' => 1 as that is part of the test contract (if you need to change the api tests you are breaking the test contract). I'm think create & get can continue to equate TRUE to 'indefinite override.
3) obviously still WIP but there should be new tests for the functionality.
4) things to think about on upgrade are whether existing smart groups & profiles have the field in them & how they will behave

I can see the value of the change

**Comment by mlutfy** [comment]
> @mlutfy are we now at the point of not requiring a JIRA? Or is that still in progress

Not yet. I would be tempted to accept it, but the commit message itself does not have all the information necessary. It's an interesting use-case though. From the commit, we cannot easily find the associated PR with the full info (well, you can, but you have to lookup the commit on github, which is a bit clunky).

I'm also thinking of renaming the dev projects, so that we have references that look like `crm/membership#123` instead of `development-team/membership#1`. -- although I will move that discussion to another ticket.

@omarabuhussein I really appreciate you testing Gitlab! Hopefully we can switch over soon! In the mean time, do you mind creating a JIRA ticket? Your JIRA ticket can simply copy the title & link to the existing Gitlab issue.

**Comment by omarabuhussein** [comment]
thanks guys for the review, first regarding creating a JIRA ticket, according to your email @mlutfy  about 'moving off JIRA', you said  : 

>  JIRA will not be shutdown/archived overnight, but new issue creation will be disabled. Older issues can be resolved on JIRA.

so according to my understanding no one should be able to create new issues on JIRA anymore since it is now locked and that was the reason for me to create it on gitlab. Though I don't mind to create it on JIRA anyway and will do it if it still possible.

regarding the commit message , I was planning anyway to amend it to look like this : 

```
development-team/membership#1 : Adding the ability to override membership until specific date
```

but I agree about your suggestion regarding crm/membership#123,  development-team/membership#1 is not really a great reference for commit messages and PR titles.


Now regarding @eileenmcnaughton other comments : 

> I think the api has to continue to support & interpret 'is_override' => 1 as that is part of the test contract (if you need to change the api tests you are breaking the test contract). I'm think create & get can continue to equate TRUE to 'indefinite override.

Yeah I am too worried about backward-compatibility, and if it up to me I wouldn't make such change to CiviCRM as long as it will stay 4.7, but at the same time CiviCRM does not really follow semver so this is still a gray area.

I will fix the API to support 'is_override' anyway, though I think and according to how civicrm work (which is usually have 1-1 mapping with DAO fields) it might be confusing to keep it. 


> obviously still WIP but there should be new tests for the functionality.

Sure thing, one of the reasons that it is still WIP is because it is missing tests. (I definitely should start doing TDD at someone 😄 )

> things to think about on upgrade are whether existing smart groups & profiles have the field in them & how they will behave

yeah but we can say the same about any extension, webform or view that it still using the field, it is again a problem with not following semver but I am not sure what can be done here other than putting it in the release notes.

though just came an idea to my mind is to rename the field name back to what it was before (is_override), but the problem is such name indicate that it should be a Boolean field, while it will not actually be a boolean though it might be more confusing.

**Comment by eileenmcnaughton** [comment]
@omarabuhussein I wonder if we can grandfather out the field - rather than remove it use triggers to populate it for now & perhaps find some places to add deprecation notices.

**Comment by eileenmcnaughton** [comment]
Just as aside I don't think semver per se is a solution to this - the issue is that we should avoid forcing people to apply breaking changes unless there is a very compelling reason (such as plugging a massive security hole). Semver wouldn't change that - in that we wouldn't do a major version release just for this alteration - if we can't make it non-breaking then I have some thoughts about how we could push it to an extension.

Adding the new field is fairly safe from this point of view & I think there is a real logic to this requirement. But, I think we have to manage rather than drop the other field to ensure this is not a breaking change

**Comment by omarabuhussein** [comment]
>  rather than remove it use triggers to populate it for now & perhaps find some places to add deprecation notices.

hmmm, not sure tbh if it is a good idea or not, I need to think about it.


> Just as aside I don't think semver per se is a solution to this - the issue is that we should avoid forcing people to apply breaking changes unless there is a very compelling reason (such as plugging a massive security hole). Semver wouldn't change that - in that we wouldn't do a major version release just for this alteration - 

I agree in this case, but in general it at least let people know that there will be some breaking changes so they can adapt and update their extensions, views ..etc. but I am aware that there were already numerous discussions about it before so I am not planning to dig it again 😄 
 

> if we can't make it non-breaking then I have some thoughts about how we could push it to an extension

Actually this was my suggestion from the beginning, apparently our project managers already had some discussions with the core team (I think with coleman and tim if I am not mistaken) and they decided to do it in core.

**Comment by eileenmcnaughton** [comment]
I did have a look at the specs in gitlab & supported putting this change in core - but that was off some high level documentation - looking at the code I feel a lot more nervous because the code involves removing a schema field which wasn't clear to me from the spec. 

If I think back to what I understood I guess I was expecting to see the status_override field stay as is & be supplemented by the date field. I'm not sure changing it to 'type' adds a lot that the combination of is_override / is_overide AND has a date doesn't.

If you just add the date field I think you can configure rules that make it work exactly the same unless the date field is set (which should make it non-breaking). The form can still display the 3 options as described

**Comment by mattwire** [comment]
> If I think back to what I understood I guess I was expecting to see the status_override field stay as is & be supplemented by the date field. I'm not sure changing it to 'type' adds a lot that the combination of is_override / is_overide AND has a date doesn't.

If you just add the date field I think you can configure rules that make it work exactly the same unless the date field is set (which should make it non-breaking). The form can still display the 3 options as described

@eileenmcnaughton @omarabuhussein Agree.  If we were starting from scratch we'd use an int for status override type but we are not.  Unless the intention is to add additional override types in the near future I think we should just add the status_override_end_date and keep is_override as is.  That way no existing code will break, and only code that knows about status_override_end_date will use the new functionality.
Perhaps there is some work that could be done to break out the is_override checks into a common shared function, which would allow for further changes to be made more easily in future.

The functionality of this change (ie. override until date) is really useful though and I think, done right does belong in core.

**Comment by guanhuan** [comment]
@omarabuhussein I agree with @eileenmcnaughton and @mattwire that we should keep is_override field name as it is. Unless it brings any obvious benefit, I think leaving the name untouched is the best way forward.

**Comment by omarabuhussein** [comment]
hmm I see, so keeping is_override  as is and only assuming it is a temporarily overridden only if the date field is set sounds like a good approach to me. I will update the PR then.

**Comment by omarabuhussein** [comment]
since the new approach is much different, I've implemented it in this PR https://github.com/civicrm/civicrm-core/pull/11622 and I will close this.

**Pull request closed without merging**
