### PR TITLE
dev/core#1387 Continue removal of "config_backend"

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------
The column `civicrm_domain.config_backend` was previously migrated and dropped by the `FourSeven` upgrade. However, it was *not* removed from the XML/DAO/SQL schema as used on new installations.

See also: https://lab.civicrm.org/dev/core/issues/1387

Before
----------------------------------------

* If you upgrade from 4.6 (or older) to 4.7 (or newer), the column `civicrm_domain.config_backend`  is dropped.
* If you install a new site, the column `civicrm_domain.config_backend` is created.

After
----------------------------------------

* The column is not created on new sites.
* If the column was created in the interim (4.7-5.20), then it is dropped.
* In `CRM_Core_BAO_ConfigSetting`, `retrieve()` and `add()` are deprecated.

Comments
----------------------------------------

I have done some light `r-run` going from 5.19=>5.20 (both with `config_backend` as `NULL` as non-`NULL`). However, I've not done `r-run` of a more difficult upgrade (e.g. 4.4=>5.21).

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@totten given that we still use a 4.2.9 snapshot db as part of the upgrade tests would you feel that covers the more difficult end?

**Comment by mlutfy** [comment]
:+1: cleanup

and as Seamus mentions, it seems pretty safe to merge based on upgrade tests.

**Comment by seamuslee001** [comment]
@totten are you able to fix the upgrade step and the conflict otherwise i think this is mergable

**Comment by eileenmcnaughton** [comment]
@totten looks like this just needs a little tweak  & a rebase

**Comment by totten** [comment]
Rebased for the 5.23.alpha1 and moved the upgrade steps from `FiveTwentyOne` to `FiveTwentyThree`.

**Comment by seamuslee001** [comment]
Added Merge on Pass as i believe this has been tested and I believe that the upgrade tests should ensure that the upgrade works smoothly

**Comment by seamuslee001** [comment]
Test fail unrelated

**Pull request merged**
