### PR TITLE
Upgrade Net_SMTP Package and remove now unneded patches and mov…

### PR DESCRIPTION
**Pull request by seamuslee001**
…e to using composer patches rather than patching in a script file

Overview
----------------------------------------
This upgrades our version of the Net SMTP package, reviewing the code base some of the patches have now been incorporated into the library 

Before
----------------------------------------
Patches happening within a script file and an outdated version of the library used

After
----------------------------------------
Latest version of the library used and patches more standardised

ping @totten @mfb @demeritcowboy

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Just commenting the title probably shouldn't be [REF], since it looks like there's other changes between 1.6 and 1.9 than just these patches. I haven't looked too closely but just browsing https://github.com/pear/Net_SMTP/compare/1.6.x...master

**Comment by seamuslee001** [comment]
Jenkins retest this please

**Comment by demeritcowboy** [comment]
Did some testing. A couple notes:
* They've changed their license to BSD-2, but it makes it more permissive so that seems fine.
* In net-smtp-patch.patch, note they've changed all underscore variables everywhere for some reason, so it needs to be `$this->code` in line 10 not `$this->_code` otherwise you get an E_NOTICE and a blank code.
* For XOAUTH2, one of the things that needs will need to be taken into account on the civi side is that they don't automatically include the word `Bearer` - see https://github.com/pear/Net_SMTP/blob/1.9.0/Net/SMTP.php#L982, so civi will need to prepend that to the token before sending to the library. Unfortunately that may or may not be specific to gmail. The fact that they've left it out suggests it is specific to gmail. So this is a bit inconsistent with the changes in zetacomponents which always includes the word Bearer.
  * But once I made that change and obtained a token manually and then also hacked SMTP.php to always select XOAUTH2, I was able to use that token and create an email in civi and send thru gmail using oauth2.
* I was also able to connect to a regular non-gmail account and send normally with AUTH LOGIN.

**Comment by seamuslee001** [comment]
thanks @demeritcowboy i believe i have fixed that e-notice error thing, given i am just focusing on the package upgrade here i think we can ignore the oauth2 stuff for the moment

**Comment by eileenmcnaughton** [comment]
From talking to @seamuslee001 it seems like oath would be a new feature so non blocking - MOP as review has not thrown up other things

**Comment by demeritcowboy** [comment]
It looks like the while patch file was deleted. Did you not want to keep the custom error which seemed helpful?

**Comment by seamuslee001** [comment]
@demeritcowboy the patch is still in place its just referenced in a specific commit now see https://raw.githubusercontent.com/civicrm/civicrm-core/a6a0ff13d2a155ad962529595dceaef728116f96/tools/scripts/composer/patches/net-smtp-patch.patch this is so that it can work for D8 purposes as well (when civicrm-core is not in the root)

**Comment by demeritcowboy** [comment]
Ok I'm not following but if you're good then ok. When I look on the files changed tab the net result seems to be the patch is now missing.

**Pull request merged**
