### PR TITLE
Afform - Format DisplayOnly fields as view value

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Improves display-only fields in formBuilder to show meaningful values.

See https://lab.civicrm.org/dev/core/-/issues/3779

Before
-------
- A field with dropdown options (e.g. "Activity type") would show the numeric value (e.g. "2") 
- A boolean field would show 1 or 0.
- A date would show in machine format e.g. `01-02-2001`.

After
--------
- A field with dropdown options (e.g. "Activity type") will show label e.g. "Meeting".
- A boolean field will show "Yes" or "No".
- A date is formatted locally e.g. "February 1st, 2001"

### CODE REVIEW

**Comment by samuelsov** [comment]
@colemanw Finally tested this with my colleague Myriam and this mostly works.

The case where it doesn't work is when you have a read-only field with a default value like this:
```html
<af-field name="activity_type_id" defn="{required: false, input_attrs: {}, input_type: 'DisplayOnly', afform_default: '1'}" />
```
gives:

**Comment by mmyriam** [comment]
Now works. Thanks!

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by kurund** [comment]
test this please

**Comment by kurund** [comment]
@colemanw 

can you please check on failing test

**Comment by colemanw** [comment]
I have checked it every way I can think of. It always passes locally but inexplicably fails on Jenkins!

**Comment by kurund** [comment]
test this please

**Comment by kurund** [comment]
test this please

**Comment by kurund** [comment]
@colemanw 

What do you want to do with PR, I have given up on tests to pass. Any ideas?

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by colemanw** [comment]
@kurund I finally tracked it down and it was a real bug: [043d683](https://github.com/civicrm/civicrm-core/commit/043d68325bc50a84e0f49afb59f55156b1b0fe77)

**Comment by kurund** [comment]
@colemanw 

Great thanks

**Pull request merged**
