### PR TITLE
--CRM-17716, fixed code to add missing accounting entries for Members…

### PR DESCRIPTION
**Pull request by pradpnayak**
…hip payments

### CODE REVIEW

**Comment by pradpnayak** [comment]
Jenkin failed, but the details shows 0 warnings

**Comment by davecivicrm** [comment]
@pradpnayak Looks like problem w/ test server. I've asked @totten to look at it.

**Comment by totten** [comment]
jenkins, test this please

**Comment by davecivicrm** [comment]
Looks good to me. I'll push a new version of civicrm_generated.mysql to go with this in a few minutes.

**Pull request merged**
