### PR TITLE
CRM-16961 fix - 4.6.5 search regression on custom fields where option…

### PR DESCRIPTION
**Pull request by monishdeb**
… values have brackets

https://issues.civicrm.org/jira/browse/CRM-16961

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
It's not working for me :-(. The first two queries work on the Db I tested on - but the 3rd is the one now generated

SELECT DISTINCT v.chapter_80 FROM civicrm_value_region_and_chapter_12 v

WHERE   v.chapter_80 LIKE  'Colorado Mountain Bike Association (COMBA)' ;
SELECT DISTINCT v.chapter_80 FROM civicrm_value_region_and_chapter_12 v

WHERE   v.chapter_80 LIKE  CONCAT(UNHEX('01'), 'Colorado Mountain Bike Association (COMBA)', UNHEX('01'))  ;

SELECT DISTINCT v.chapter_80 FROM civicrm_value_region_and_chapter_12 v
WHERE   v.chapter_80 RLIKE '[[:cntrl:]]*colorado mountain bike association (comba)[[:cntrl:]]*'

**Comment by monishdeb** [comment]
Strange because according to my changes whereClause would be. WHERE v.chapter_80 RLIKE '[[:cntrl:]]*colorado mountain bike association (comba)[[:cntrl:]]*'

**Comment by eileenmcnaughton** [comment]
yep - but even stripping the * I actually still got no results returned just running that in mysql

**Comment by eileenmcnaughton** [comment]
try this

``
DROP TABLE IF EXISTS test_wierd_sql;
CREATE TABLE test_wierd_sql SELECT CONCAT(unhex('01'), '(bob)', unhex('01')) as bob_string;
SELECT * FROM test_wierd_sql WHERE bob_string RLIKE '[[:cntrl:]](bob)[[:cntrl:]]'
``

**Comment by monishdeb** [comment]
The reason of having \* is to tackle 0 or one or more occurance of special character and it did worked on my local.

**Comment by eileenmcnaughton** [comment]
(I just edited the above - 'test bob sql')

**Comment by eileenmcnaughton** [comment]
THIS query works. And it makes sense - the brackets were being treated as regex chars.

Note the ``
[[.SOH.]]
`` is more accurate than [[:cntrl:]] but isn't really important to whether it works or not

``
SELECT count(*) as rowCount  FROM  
civicrm_value_region_and_chapter_12 
WHERE   civicrm_value_region_and_chapter_12.chapter_80 RLIKE '[[.SOH.]]*colorado mountain bike association [[.left-parenthesis.]]comba[[.right-parenthesis.]][[.SOH.]]*'
``

**Comment by kurund** [comment]
jenkins, test this please

**Pull request merged**
