### PR TITLE
Add PDF letter functionality for Activities using new token processor

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Adds the ability to create letters from activity search. This is the penultimate chunk of a large piece of work undertaken by @aydun which cleaned up a lot of pdf, task and token code and added tests in order to support this functionality. Unfortunately the ambitiousness of 'doing it right' meant it has stalled multiple times. Currently it is stalled on discussion around the activity contact tokens. I have taken all of @aydun's change less the part that related to those tokens into this PR i order to get the bulk merged

Before
----------------------------------------
Cannot write pdf letters from activity search

After
----------------------------------------
Search is in line with other actions, code is streamlined.

Technical Details
----------------------------------------
Create CRM_Actvity_Form_Task_PDFLetterCommon extending CRM_Core_Form_Task_PDFLetterCommon

Slim down alterActionScheduleQuery() and move most data fetching to prefetch()

Add tests for Activity PDF Letter

Comments
----------------------------------------
@aydun if you are OK with this I will merge as a reviewer's commit @demeritcowboy thank you for your review / engagement on the tokens issue - hopefully we can continue that conversation on the other PR - let me know if you have any concerns with this

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@alifrumin note the contributor for this is @aydun

**Comment by demeritcowboy** [comment]
I'll do a fuller test but two things off the bat:

On the PR test site I get file not found even for pdf. Not sure if that's a temp glitch. Again I'll do a fuller test later.

I'm wondering about whether this still meets the original use-case when there isn't ANY contact info of any kind available to insert as a token. I guess there could be some use-cases, just the results would not have any personalization at all for whoever it's intended for.

**Comment by eileenmcnaughton** [comment]
Yeah - it's definitely a more limited use case - I still want to resolve the rest of it - just trying to get the bulk merged

**Comment by demeritcowboy** [comment]
Still getting file not found. It seems related to the new functionality since it's working for the usual contact-related pdf (and msword), but when used on activity search results it gives a 404.

And for the contact one I also get this when I move on to another page, but it seems unrelated and a preexisting issue. `Notice: Undefined variable: isLiveMode in CRM_Contact_Form_Task_PDFLetterCommon::postProcess() (line 183 of /home/jenkins/bknix-dfl/build/core-14662-3v32y/sites/all/modules/civicrm/CRM/Contact/Form/Task/PDFLetterCommon.php).`

**Comment by aydun** [comment]
It's been a bit overtaken by other things, but I'm hoping to kick it forward again at the sprint.  Do you have an interest in helping it progress?

**Comment by mattwire** [comment]
Merging as I've tested this and it is working for me

**Comment by eileenmcnaughton** [comment]
@aydun well this happened!

**Comment by mattwire** [comment]
See https://lab.civicrm.org/mattwire/emailapi/tree/newtokenprocessor for a useful way to try it out

**Comment by aydun** [comment]
@eileenmcnaughton @mattwire Great!  Many thanks for getting this bit over the line despite my lack of focus on this recently.

**Pull request merged**
