### PR TITLE
dev/core#1605 State/province not copied on shared address

### PR DESCRIPTION
**Pull request by alifrumin**
Overview
----------------------------------------
Ensure the state/province is copied when sharing an address.

More details including screenshots in the gitlab issue: https://lab.civicrm.org/dev/core/issues/1605

Before
----------------------------------------
1. User goes to a contact's summary tab 
2. Clicks "Add Address"
3. Selects the "Use another contact's address" checkbox
4. Selects a contact with an address WITH a state 
5. Clicks Save

**Result:** All the address fields are copied over EXCEPT the state/province.

After
----------------------------------------
When sharing an address the state province field IS copied

To Replicate:
1. User goes to a contact's summary tab 
2. Clicks "Add Address"
3. Selects the "Use another contact's address" checkbox
4. Selects a contact with an address WITH a state 
5. Clicks Save

**Result:** All the address fields are copied over INCLUDING the state/province.

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by alifrumin** [comment]
Jenkins re test this please

**Comment by alifrumin** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
I was just tormenting myself over whether  we could get away with  this without  a test  & then  I scrolled down & lo-and-behold...

**Comment by eileenmcnaughton** [comment]
OK  - I was  able to replicate & see  this fix - I did have some weird experiences doing it but  they were  in the formRule which is untouched so I think unrelated

**Pull request merged**
