### PR TITLE
dev/core#224 Fix participant mail to include additional participant data on pay later

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Alternative to https://github.com/civicrm/civicrm-core/pull/30358

 https://lab.civicrm.org/dev/core/-/issues/224

Before
----------------------------------------
When a participant record is completed via pay later, or a receipt is otherwise sent for a multiple participant event registration after the fact the additional participant profiles are not included

After
----------------------------------------
The additional participant data is included, all profile data now comes from the Workflow Message layer for this receipt

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by JKingsnorth** [comment]
Test failures do look related here. Happy to take a look when you're ready for me to review.

**Comment by eileenmcnaughton** [comment]
this test fix https://github.com/civicrm/civicrm-core/pull/30374/files#diff-40e852becab8b08727c9e75cb29f19a6579d278c986ab619df4ce35fb7196126R297 seems to be causing chaos - just need to fix the tests to adapt to it as they are wrong without that change

**Comment by eileenmcnaughton** [comment]
image

**Comment by eileenmcnaughton** [comment]
@JKingsnorth it's passing

**Comment by JKingsnorth** [comment]
> @JKingsnorth it's passing

I'm hoping to get to this later this week :)

**Comment by eileenmcnaughton** [comment]
@JKingsnorth still on your radar? the rc will be cut on Wed

**Comment by JKingsnorth** [comment]
Yes, sorry, things always get in the way. I'll look at it tomorrow.

**Comment by JKingsnorth** [comment]
@eileenmcnaughton There's an issue with how the extra 'bottom of page' (post) profiles which you can attach to events are being interpreted.

If you set up an event with 3 post profiles and register 2 attendees, then the post profiles for the guest get split into new participant rows instead of being grouped into the information for the second participant.

The screenshot below shows the result with a 2 participant registration:

1 - On the lead booker confirmation (left), the dietary and access requirements for the lead booker are both missing

2 - On the lead booker confirmation (left), the 'post' profiles for participant 2 have been split into erroneous extra participants

3 - On the guest booker confirmation, it only shows their information (correct!) but the information from their post profiles is missing?

image

**Comment by eileenmcnaughton** [comment]
@JKingsnorth I took another look & figured out the things to do differently to replicate the issues you saw - they should be covered by the tests now. Assuming this passes can you give it another whirl

**Comment by eileenmcnaughton** [comment]
CRM_Event_Form_Registration_ConfirmTest::testTaxMultipleParticipant
Failed asserting that '--=_bf98a318b1e9bc7dfe84325fc0bf4f29\n
Content-Transfer-Encoding: 8bit\n
Content-Type: text/plain; charset=utf-8\n
\n
Dear Participant1,\n
\n
Thank you for your registration. This is a confirmation that your registration has been received and your status has been updated to Pending (pay later).\n
\n
Please transfer funds to our bank account.\n
\n
Event Information and Location\n
Annual CiviCRM meet\n
Tuesday October 21st, 2008 12:00 AM-Thursday October 3rd, 2024 4:49 PM\n
\n
[Download iCalendar entry for this event.](http://build-2.127.0.0.1.nip.io:5700/index.php?q=civicrm/event/ical&reset=1&id=1)\n
[Add event to Google Calendar](http://build-2.127.0.0.1.nip.io:5700/index.php?q=civicrm/event/ical&gCalendar=1&reset=1&id=1)\n
Event fees\n
Mr. Participant1 LastName II\n
\n
Item	Qty	Each	Subtotal	Tax Rate	Tax Amount	Total\n
Fundraising Dinner - Standard Rate	1	$300.00	$300.00	10.00%	$30.00	$330.00\n
Total for Mr. Participant1 LastName II	$300.00	$30.00	$330.00\n
Participant2 LastName\n
\n
Item	Qty	Each	Subtotal	Tax Rate	Tax Amount	Total\n
Fundraising Dinner - Student Rate	1	$100.00	$100.00	10.00%	$10.00	$110.00\n
Total for Participant2 LastName	$100.00	$10.00	$110.00\n
Participant3 LastName\n
\n
Item	Qty	Each	Subtotal	Tax Rate	Tax Amount	Total\n
Fundraising Dinner - Student Deluxe	1	$200.00	$200.00	10.00%	$20.00	$220.00\n
Total for Participant3 LastName	$200.00	$20.00	$220.00\n
Amount Before Tax:	$600.00\n
Sales Tax 10.00%	$60.00\n
Total Tax Amount	$60.00\n
Total Amount	$660.00\n
Registration Date	September 3rd, 2024 4:49 PM\n
Transaction Date	September 3rd, 2024 4:49 PM\n
Financial Type	Event Fee\n
Credit Card Information\n
Visa\n
\n
Expires:\n
Public Event Pre Profile\n
email\n
Public Event Post Profile\n
first_name\n
last_name	LastName\n
Public Event Post Post Profile\n
job_title\n
Participant 2\n
Event Pre Profile (Additional)\n
email\n
Event Post Profile (Additional)\n
first_name\n
last_name	LastName\n
Event Post Post Profile\n
job_title\n
Participant 3\n
Event Pre Profile (Additional)\n
email\n
Event Post Profile (Additional)\n
first_name\n
last_name	LastName\n
Event Post Post Profile\n
job_title\n
You may transfer your registration to another participant or cancel your registration up to 0 hours after the event.\n
[Click here to transfer or cancel your registration.](http://build-2.127.0.0.1.nip.io:5700/index.php?q=civicrm/event/selfsvcupdate&reset=1&pid=1&cs=cacbcef08c08c4e5299d3a3908e1524a_1725407347_168)\n
--=_bf98a318b1e9bc7dfe84325fc0bf4f29\n
Content-Transfer-Encoding: 8bit\n
Content-Type: text/html; charset=utf-8\n
\n
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n
<html xmlns="http://www.w3.org/1999/xhtml">\n
<head>\n
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>\n
  <title></title>\n
</head>\n
<body>\n
\n
\n
  \n
        <div></div>\n
  \n
\n
  \n
\n
  <table id="crm-event_receipt" style="font-family: Arial, Verdana, sans-serif; text-align: left; width:100%; max-width:700px; padding:0; margin:0; border:0px;">\n
  <tr>\n
    <td>\n
      <p>Dear Participant1,</p>              <p>Thank you for your registration.            This is a confirmation that your registration has been received and your status has been updated to <strong>Pending (pay later)</strong>.                    </p>\n
      \n
                <p>Please transfer funds to our bank account.</p>\n
            </td>\n
  </tr>\n
  <tr>\n
    <td>\n
      <table style="width:100%; max-width:700px; border: 1px solid #999; margin: 1em 0em 1em; border-collapse: collapse;">\n
        <tr>\n
          <th colspan="2" style="text-align: left; padding: 4px; border-bottom: 1px solid #999; background-color: #eee;">\n
            Event Information and Location          </th>\n
        </tr>\n
        <tr>\n
          <td colspan="2" style="padding: 4px; border-bottom: 1px solid #999;">\n
            Annual CiviCRM meet<br/>\n
            Tuesday October 21st, 2008 12:00 AM-Thursday October 3rd, 2024  4:49 PM          </td>\n
        </tr>\n
\n
                  <tr>\n
            <td colspan="2" style="padding: 4px; border-bottom: 1px solid #999;">\n
              \n
            </td>\n
          </tr>\n
        \n
        \n
                  <tr>\n
            <td colspan="2" style="padding: 4px; border-bottom: 1px solid #999;">\n
                            <a href="http://build-2.127.0.0.1.nip.io:5700/index.php?q=civicrm/event/ical&reset=1&id=1">Download iCalendar entry for this event.</a>\n
            </td>\n
          </tr>\n
          <tr>\n
            <td colspan="2" style="padding: 4px; border-bottom: 1px solid #999;">\n
                            <a href="http://build-2.127.0.0.1.nip.io:5700/index.php?q=civicrm/event/ical&gCalendar=1&reset=1&id=1">Add event to Google Calendar</a>\n
            </td>\n
          </tr>\n
        \n
                                  <tr>\n
            <th colspan="2" style="text-align: left; padding: 4px; border-bottom: 1px solid #999; background-color: #eee;">\n
              Event fees\n
            </th>\n
          </tr>\n
                                                                                 <tr>\n
                      <td colspan="2" style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">\n
                        Mr. Participant1 LastName II\n
                      </td>\n
                    </tr>\n
                                    <tr>\n
                    <td colspan="2" style="padding: 4px; border-bottom: 1px solid #999;">\n
                      <table>\n
                        <tr>\n
                          <th>Item</th>\n
                          <th>Qty</th>\n
                          <th>Each</th>\n
                                                        <th>Subtotal</th>\n
                              <th>Tax Rate</th>\n
                              <th>Tax Amount</th>\n
                                                      <th>Total</th>\n
                                                  </tr>\n
                                                  <tr>\n
                            <td style="width: 180px; padding-bottom: 15px;">Fundraising Dinner - Standard Rate</td>\n
                            <td style="width: 100px;" align="middle">1</td>\n
                            <td style="width: 100px;">$300.00</td>\n
                                                          <td>$300.00</td>\n
                                                              <td>10.00%</td>\n
                                <td>$30.00</td>\n
                                                                                      <td style="width: 100px;">\n
                              $330.00\n
                            </td>\n
                                                      </tr>\n
                                                                          <tr style="margin: 0.5em 0 0.5em;padding: 0.5em;background-color: #999999;font-weight: bold;color: #FAFAFA;border-radius: 2px;">\n
                            <td colspan=3>Total for Mr. Participant1 LastName II</td>\n
                            <td colspan=2>$300.00</td>\n
                            <td colspan=1>$30.00</td>\n
                            <td colspan=2>$330.00</td>\n
                          </tr>\n
                                              </table>\n
                    </td>\n
                  </tr>\n
                                                                                     <tr>\n
                      <td colspan="2" style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">\n
                        Participant2 LastName\n
                      </td>\n
                    </tr>\n
                                    <tr>\n
                    <td colspan="2" style="padding: 4px; border-bottom: 1px solid #999;">\n
                      <table>\n
                        <tr>\n
                          <th>Item</th>\n
                          <th>Qty</th>\n
                          <th>Each</th>\n
                                                        <th>Subtotal</th>\n
                              <th>Tax Rate</th>\n
                              <th>Tax Amount</th>\n
                                                      <th>Total</th>\n
                                                  </tr>\n
                                                  <tr>\n
                            <td style="width: 180px; padding-bottom: 15px;">Fundraising Dinner - Student Rate</td>\n
                            <td style="width: 100px;" align="middle">1</td>\n
                            <td style="width: 100px;">$100.00</td>\n
                                                          <td>$100.00</td>\n
                                                              <td>10.00%</td>\n
                                <td>$10.00</td>\n
                                                                                      <td style="width: 100px;">\n
                              $110.00\n
                            </td>\n
                                                      </tr>\n
                                                                          <tr style="margin: 0.5em 0 0.5em;padding: 0.5em;background-color: #999999;font-weight: bold;color: #FAFAFA;border-radius: 2px;">\n
                            <td colspan=3>Total for Participant2 LastName</td>\n
                            <td colspan=2>$100.00</td>\n
                            <td colspan=1>$10.00</td>\n
                            <td colspan=2>$110.00</td>\n
                          </tr>\n
                                              </table>\n
                    </td>\n
                  </tr>\n
                                                                                     <tr>\n
                      <td colspan="2" style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">\n
                        Participant3 LastName\n
                      </td>\n
                    </tr>\n
                                    <tr>\n
                    <td colspan="2" style="padding: 4px; border-bottom: 1px solid #999;">\n
                      <table>\n
                        <tr>\n
                          <th>Item</th>\n
                          <th>Qty</th>\n
                          <th>Each</th>\n
                                                        <th>Subtotal</th>\n
                              <th>Tax Rate</th>\n
                              <th>Tax Amount</th>\n
                                                      <th>Total</th>\n
                                                  </tr>\n
                                                  <tr>\n
                            <td style="width: 180px; padding-bottom: 15px;">Fundraising Dinner - Student Deluxe</td>\n
                            <td style="width: 100px;" align="middle">1</td>\n
                            <td style="width: 100px;">$200.00</td>\n
                                                          <td>$200.00</td>\n
                                                              <td>10.00%</td>\n
                                <td>$20.00</td>\n
                                                                                      <td style="width: 100px;">\n
                              $220.00\n
                            </td>\n
                                                      </tr>\n
                                                                          <tr style="margin: 0.5em 0 0.5em;padding: 0.5em;background-color: #999999;font-weight: bold;color: #FAFAFA;border-radius: 2px;">\n
                            <td colspan=3>Total for Participant3 LastName</td>\n
                            <td colspan=2>$200.00</td>\n
                            <td colspan=1>$20.00</td>\n
                            <td colspan=2>$220.00</td>\n
                          </tr>\n
                                              </table>\n
                    </td>\n
                  </tr>\n
                                                                                <tr>\n
                <td style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">\n
                  Amount Before Tax:                </td>\n
                <td style="padding: 4px; border-bottom: 1px solid #999;">\n
                  $600.00                </td>\n
              </tr>\n
                                            <tr>\n
                  <td style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">Sales Tax 10.00%</td>\n
                  <td style="padding: 4px; border-bottom: 1px solid #999;">$60.00</td>\n
                </tr>\n
                            <tr>\n
                <td style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">\n
                    Total Tax Amount                </td>\n
                <td style="padding: 4px; border-bottom: 1px solid #999;">\n
                    $60.00                </td>\n
              </tr>\n
                                      <tr>\n
                <td style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">\n
                  Total Amount                </td>\n
                <td style="padding: 4px; border-bottom: 1px solid #999;">\n
                  $660.00                 </td>\n
              </tr>\n
              \n
                              <tr>\n
                  <td style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">\n
                    Registration Date                  </td>\n
                  <td style="padding: 4px; border-bottom: 1px solid #999;">\n
                    September 3rd, 2024  4:49 PM\n
                  </td>\n
                </tr>\n
              \n
                              <tr>\n
                  <td style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">\n
                    Transaction Date                  </td>\n
                  <td style="padding: 4px; border-bottom: 1px solid #999;">\n
                    September 3rd, 2024  4:49 PM\n
                  </td>\n
                </tr>\n
              \n
                              <tr>\n
                  <td style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">\n
                    Financial Type                  </td>\n
                  <td style="padding: 4px; border-bottom: 1px solid #999;">\n
                    Event Fee\n
                  </td>\n
                </tr>\n
              \n
              \n
              \n
              \n
              \n
                              <tr>\n
                  <th colspan="2" style="text-align: left; padding: 4px; border-bottom: 1px solid #999; background-color: #eee;">\n
                    Credit Card Information                  </th>\n
                </tr>\n
                <tr>\n
                  <td colspan="2" style="padding: 4px; border-bottom: 1px solid #999;">\n
                    Visa<br/>\n
                    <br/>\n
                    Expires: \n
                  </td>\n
                </tr>\n
                          \n
           \n
                              <tr>\n
              <th colspan="2" style="text-align: left; padding: 4px; border-bottom: 1px solid #999; background-color: #eee;">Public Event Pre Profile</th>\n
            </tr>\n
                          <tr>\n
                <td style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">email</td>\n
                <td style="padding: 4px; border-bottom: 1px solid #999;"></td>\n
              </tr>\n
                              \n
                              <tr>\n
              <th colspan="2" style="text-align: left; padding: 4px; border-bottom: 1px solid #999; background-color: #eee;">Public Event Post Profile</th>\n
            </tr>\n
                          <tr>\n
                <td style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">first_name</td>\n
                <td style="padding: 4px; border-bottom: 1px solid #999;"></td>\n
              </tr>\n
                          <tr>\n
                <td style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">last_name</td>\n
                <td style="padding: 4px; border-bottom: 1px solid #999;">LastName</td>\n
              </tr>\n
                                  <tr>\n
              <th colspan="2" style="text-align: left; padding: 4px; border-bottom: 1px solid #999; background-color: #eee;">Public Event Post Post Profile</th>\n
            </tr>\n
                          <tr>\n
                <td style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">job_title</td>\n
                <td style="padding: 4px; border-bottom: 1px solid #999;"></td>\n
              </tr>\n
                              \n
                              <tr>\n
              <th colspan="2" style="text-align: left; padding: 4px; border-bottom: 1px solid #999; background-color: #eee;">Participant 2 </th>\n
            </tr>\n
                          <tr>\n
                <th colspan="2" style="text-align: left; padding: 4px; border-bottom: 1px solid #999; background-color: #eee;">Event Pre Profile (Additional) </th>\n
              </tr>\n
                              <tr>\n
                                      <td style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">email</td>\n
                    <td style="padding: 4px; border-bottom: 1px solid #999;"></td>\n
                                  </tr>\n
                                        <tr>\n
                <th colspan="2" style="text-align: left; padding: 4px; border-bottom: 1px solid #999; background-color: #eee;">Event Post Profile (Additional) </th>\n
              </tr>\n
                              <tr>\n
                                      <td style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">first_name</td>\n
                    <td style="padding: 4px; border-bottom: 1px solid #999;"></td>\n
                                  </tr>\n
                              <tr>\n
                                      <td style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">last_name</td>\n
                    <td style="padding: 4px; border-bottom: 1px solid #999;">LastName</td>\n
                                  </tr>\n
                                        <tr>\n
                <th colspan="2" style="text-align: left; padding: 4px; border-bottom: 1px solid #999; background-color: #eee;">Event Post Post Profile</th>\n
              </tr>\n
                              <tr>\n
                                      <td style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">job_title</td>\n
                    <td style="padding: 4px; border-bottom: 1px solid #999;"></td>\n
                                  </tr>\n
                                                <tr>\n
              <th colspan="2" style="text-align: left; padding: 4px; border-bottom: 1px solid #999; background-color: #eee;">Participant 3 </th>\n
            </tr>\n
                          <tr>\n
                <th colspan="2" style="text-align: left; padding: 4px; border-bottom: 1px solid #999; background-color: #eee;">Event Pre Profile (Additional) </th>\n
              </tr>\n
                              <tr>\n
                                      <td style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">email</td>\n
                    <td style="padding: 4px; border-bottom: 1px solid #999;"></td>\n
                                  </tr>\n
                                        <tr>\n
                <th colspan="2" style="text-align: left; padding: 4px; border-bottom: 1px solid #999; background-color: #eee;">Event Post Profile (Additional) </th>\n
              </tr>\n
                              <tr>\n
                                      <td style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">first_name</td>\n
                    <td style="padding: 4px; border-bottom: 1px solid #999;"></td>\n
                                  </tr>\n
                              <tr>\n
                                      <td style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">last_name</td>\n
                    <td style="padding: 4px; border-bottom: 1px solid #999;">LastName</td>\n
                                  </tr>\n
                                        <tr>\n
                <th colspan="2" style="text-align: left; padding: 4px; border-bottom: 1px solid #999; background-color: #eee;">Event Post Post Profile</th>\n
              </tr>\n
                              <tr>\n
                                      <td style="padding: 4px; border-bottom: 1px solid #999; background-color: #f7f7f7;">job_title</td>\n
                    <td style="padding: 4px; border-bottom: 1px solid #999;"></td>\n
                                  </tr>\n
                                            \n
      </table>\n
              <tr>\n
          <td colspan="2" style="padding: 4px; border-bottom: 1px solid #999;">\n
                        You may transfer your registration to another participant or cancel your registration up to 0 hours after the event.            <br/>\n
                        <a href="http://build-2.127.0.0.1.nip.io:5700/index.php?q=civicrm/event/selfsvcupdate&reset=1&pid=1&cs=cacbcef08c08c4e5299d3a3908e1524a_1725407347_168">Click here to transfer or cancel your registration.</a>\n
          </td>\n
        </tr>\n
       </table>\n
\n
</body>\n
</html>\n
\n
--=_bf98a318b1e9bc7dfe84325fc0bf4f29--\n
' contains "job_title	oracle".

**Comment by JKingsnorth** [comment]
@eileenmcnaughton - test failed, do you still want me to take a look or is it WIP?

**Comment by eileenmcnaughton** [comment]
@JKingsnorth I'll have another go - I feel that test passed locally so it might be a fight

**Comment by eileenmcnaughton** [comment]
@JKingsnorth I think I sorted it - it was hard to track down - it's that second commit

**Comment by eileenmcnaughton** [comment]
@JKingsnorth ok tests are a go - any chance you can look at this in time to get it merged before the next rc is cut?

**Comment by JKingsnorth** [comment]
Hi @eileenmcnaughton , sorry for the delay. I'm unlikely to get to this before Thursday 17th, after the security release. But its on my radar.

**Comment by eileenmcnaughton** [comment]
@JKingsnorth just checking in on this one again

**Comment by JKingsnorth** [comment]
Hi @eileenmcnaughton 

This is working for paid events with multiple participants, including where guests have a specified email address.

But for free events, the 'lead booker' email does not contain any guest information or profiles.

But the guest emails do contain their own information correctly.

I think this is because here: https://github.com/civicrm/civicrm-core/pull/30374/files#diff-7316e067630a5ca29e748055e988f9407c9a0ee5cc6be4880b9803c5aa7617a7R323 the `$participant['is_primary'] = $this->getParticipantID() === $participantID;` is supposed to be set, but there's an early return in that method with:

```
      if (!$this->getLineItems()) {
        return [];
      }
```

.. there are no line items because it is a free event.

**Comment by eileenmcnaughton** [comment]
@JKingsnorth ah thanks - once again you thought of a scenario I didn't - hopefully I can fix this & there won't be more!

**Comment by eileenmcnaughton** [comment]
@JKingsnorth fixed, with test, that passes

**Comment by JKingsnorth** [comment]
Thanks @eileenmcnaughton ! This is looking good!

I've tested:

- Event registration with guests:
- - Paid and unpaid
- - Including guest emails with only their own information

- Back-office event registration

**Pull request merged**
