### PR TITLE
4.6: Contribution Pages: fix JS syntax error.

### PR DESCRIPTION
**Pull request by mlutfy**
Overview
----------------------------------------

Public contribution pages were displaying Javascript syntax errors in the browser console. Therefore the form did not work as expected.

### CODE REVIEW

**Comment by jackrabbithanna** [comment]
@bgm Was this a new condition from the latest release?

**Comment by seamuslee001** [comment]
@jackrabbithanna @mlutfy that line looks like it hasn't been touched in years https://github.com/civicrm/civicrm-core/commit/49d77b7f68cb4e12a7bdb2a1a711e54ea2655b19

**Comment by jackrabbithanna** [comment]
This was added recently, but no javascript changes there...https://github.com/civicrm/civicrm-core/pull/11227/files

**Comment by mlutfy** [comment]
I agree with Seamus, according to the git log, it was introduced in https://github.com/civicrm/civicrm-core/commit/49d77b7f68cb4e12a7bdb2a1a711e54ea2655b19, October 2016. It's possible that this didn't have an impact for most people?

It should be easy to confirm: if you have a 4.6 site with public-facing contribution pages, there should be a JS error in the browser console. Possibly have to click around in the price options.

**Comment by jackrabbithanna** [comment]
I do remember now there was a PR to fix a syntax error for 4.6, but the fix actually caused it not to work worse....
https://github.com/civicrm/civicrm-core/pull/11238/files

I ended up rejecting that PR

**Comment by adixon** [comment]
FWIW - my 4.6 install didn't show the error because I was overriding that template and hadn't updated my diff'd copy recently. Amazing that someone didn't notice this earlier.

**Comment by adixon** [comment]
Found another 4.6 install that did show the error. Installed this patch and now get a different console error:
Uncaught ReferenceError: currentTotal is not defined
    at skipPaymentMethod (transact?reset=1&id=2:1295)
    at HTMLDocument.<anonymous> (transact?reset=1&id=2:1250)
    at i (js_ZnzvKOZyPVVEW0ukgCT_FkgAv3sgaJM65eunzgdDuXY.js:124)
    at Object.fireWith [as resolveWith] (js_ZnzvKOZyPVVEW0ukgCT_FkgAv3sgaJM65eunzgdDuXY.js:124)
    at Function.ready (js_ZnzvKOZyPVVEW0ukgCT_FkgAv3sgaJM65eunzgdDuXY.js:124)
    at HTMLDocument.K (js_ZnzvKOZyPVVEW0ukgCT_FkgAv3sgaJM65eunzgdDuXY.js:124)

Sounds like the original patch back in 2016 might have been flawed? 

I converted:
priceSetTotal = currentTotal;
to
priceSetTotal = currentTotal = 0;
and I'm not longer getting the errors, but it seems like no one has really understood or reviewed the original patch.

**Comment by jackrabbithanna** [comment]
We've been using contribution pages with 4.6 LTS on something like 20 client sites for years here and haven't had a problem. @mlutfy is there functionality that is broken for you, or is it just the error in the console?

**Comment by mlutfy** [comment]
@jackrabbithanna I'm not sure. I was having a few problems after my upgrade because the site was customized. I cleaned up things (removed customizations) and saw the JS error. Surely that code does something?

I don't want to waste your time either. I will upgrade this site asap. If this is not affecting you, I am fine with closing this PR.

**Comment by jackrabbithanna** [comment]
It's not a waste of time, I'll review the patch....Thank you for taking the time to do the PR!

Your patch is slightly different than the one I closed, perhaps you have the better solution :)

**Pull request closed without merging**
