### PR TITLE
CRM-19150: Preserve contribution when associated membership is deleted (step 1 of 2 | API and BAO)

### PR DESCRIPTION
**Pull request by monishdeb**
- [CRM-19150: Preserve contribution when associated membership is deleted (step 1 of 2 | API and BAO)](https://issues.civicrm.org/jira/browse/CRM-19150)

### CODE REVIEW

**Comment by monishdeb** [comment]
@joseltorres I have cherry-picked your commit and did some modification. Have a look

**Comment by seamuslee001** [comment]
@monishdeb @joseltorres is it worth keeping the civicrm_api3_membership_delete function as it is in master then in CRM_Membership_BAO_Membership::del() extracting the preserve contribution param there. That way then the return behavior of the api doesn't change. The one thing that probably should be added to the api is in the create spec add information for the preserve_contribution param

**Comment by monishdeb** [comment]
@seamuslee001 there are some limitations in keeping the membership delete api intact, even I was not convinced with the patch earlier but then these are factors : 
1. before calling CRM_Membership_BAO_Membership::del() the api utility fn consider only the membership id in $params and rest of the attributes like here (if we pass preserve_contribution) will be discarded. See https://github.com/civicrm/civicrm-core/blob/master/api/v3/utils.php#L1459
2. CRM_Membership_BAO_Membership::del() consider the first parameter to be integer id not the assosiated array as $params.
Reason why we need to introduce a second boolean parameter as preserve_contribution and I have ensured that the modification done in api won't cause any regression in master.  

I agree with your second point that there need to spec for del which I accidentally deleted from @joseltorres commit. Will update the PR soon.

**Comment by monishdeb** [comment]
Updated PR by adding spec. Here's the screenshot 
image

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by monishdeb** [comment]
Closing in favor of https://github.com/civicrm/civicrm-core/pull/8813

**Pull request closed without merging**
