### PR TITLE
CRM-17837 Improve Lybunt report. …

### PR DESCRIPTION
**Pull request by eileenmcnaughton**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw I'm inclined to merge this on pass & email the partners list & say "hey make sure you test lybunt in your QA this week"  - what do you think?

**Comment by colemanw** [comment]
Ok by me.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
recheck

**Comment by eileenmcnaughton** [comment]
unrelalted fail

**Pull request merged**
