### PR TITLE
Clarify definition of amount field in civicrm_contribution_recur table.

### PR DESCRIPTION
**Pull request by KarinG**
Overview
----------------------------------------
Replacement PR for https://github.com/civicrm/civicrm-core/pull/17204

There was some ambiguity as to whether the amount field in civicrm_contribution_recur table represented the sales tax inclusive or exclusive amount. I checked in with @eileenmcnaughton and people on: https://lab.civicrm.org/dev/financial/-/issues/123 

**I did some research:**
- Membership Type -> auto-renew required (Fee: $1) + Financial Type has Sales Tax associated with it (5%)
- Submit Credit Card for Membership -> (Amount is calculated correctly: $1.05)
- Observe -> **Amount $1.05 (not $1)** is stored in the civicrm_contribution_recur table, so that's the tax inclusive amount

image

**PR to remove ambiguity:** amount to be collected - is clearly total amount - and avoids making this comment unnecessarily complex by adding sales tax wording into it. 

**Before**
----------------------------------------
show FULL columns from civicrm_contribution_recur;

`| amount                       | decimal(20,2)    | NULL            | NO   |     | NULL    |                | select,insert,update,references | Amount to be contributed or charged each recurrence.    `                              

**After**
----------------------------------------
`| amount                       | decimal(20,2)    | NULL            | YES  |     | NULL    |                | select,insert,update,references | Amount to be collected (including any sales tax) by payment processor each recurrence.    `
                       
**Next**
----------------------------------------
After establishing /clarifying that amount is indeed amount to be collected -> I'll work on ensuring that repeattransaction API [recommended for payment processors creating subsequent instalments] works properly when it comes to Sales Taxes.

Technical
----------------------------------------
Looks like I can add this onto `CRM/Upgrade/Incremental/sql/5.27.alpha1.mysql.tpl` - if not please let me know.

**Comment**
----------------------------------------
I will also be updating the Documentation.

### CODE REVIEW

**Comment by KarinG** [comment]
@eileenmcnaughton @seamuslee001 @adixon @mattwire  - this is the replacement PR for when I previously messed up my repo.

**Comment by seamuslee001** [comment]
I've added the merge read flag as I believe all the changes that are required are there now and I think the comment is much clearer than before, I'm not sure we need much more bikeshedding on this one but will leave it open for a bit if people have any strong feelpinions on this

**Comment by mattwire** [comment]
This looks good :-)

**Comment by seamuslee001** [comment]
Seeing as there has been no objections I am going to merge this

**Comment by eileenmcnaughton** [comment]
yay - well done @KarinG  - a deceptively simple PR

**Pull request merged**
