### PR TITLE
Offer singular entity titles

### PR DESCRIPTION
**Pull request by agh1**
Overview
----------------------------------------
In #17527 @colemanw added a much-needed translatable title for each entity.  It was so needed that I had independently developed a different way of doing the same thing in #17675.  The only difference is that he produced plural titles and I produced singular ones.

This builds upon his work there and offers an option to get the singular title for an entity.

Before
----------------------------------------
There's no way to take CRM_Activity_DAO_Activity and know that it's referring to Activity entities.  (I know, aside from the obvious for an English-language reader of code, but you can't get from there to "Elige Actividad").

After
----------------------------------------
The getEntityTitle method for each DAO can optionally return the translated singular title for the activity.

### CODE REVIEW

**Comment by colemanw** [comment]
Hey @agh1 I really like the direction of this!

It does seem a bit backwards to have the default be plural, and `<title>` mean plural, and I understand why you did it that way - to not break backward compatibility with what I've already done.

I appreciate your delicacy, but screw it, your idea is better. Let's go ahead and break it. Let's have `getEntityTitle` return singular by default, and let's have `<title>` be singular in the xml. That way we generally won't need a separate xml tag for the plual version and can just rely on `CRM_Utils_String::pluralize()`.

I'm happy to put up a PR for that unless you want to.

**Comment by agh1** [comment]
No worries--I just updated this to do what I think you're saying.  The XML still supports a `titlePlural` because we already have one instance where running the singular through the pluralizer would result in the cryptic "Instant Messagings".  I could imagine more.  But otherwise, the `title` is singular, `titlePlural` is plural (when produced by the APIv4 `getInfo()`), and the `getEntityTitle()` functions default to singular.

**Comment by colemanw** [comment]
This is great @agh1. I've tested it out and only found one problem, which is that for extensions that have already regenerated their DAOs, PHP was displaying a warning that their `getEntityTitle()` function was incompatible with the one in the parent class `CRM_Core_DAO`. I fixed that by just taking that param out of the parent class, where it wasn't being used anyway.

Extension authors will need to regenerate their DAOs (again) after this is merged.

I also fixed the search extension to once again show plural entity titles, and squashed your commits. Good to go!

**Comment by colemanw** [comment]
Unrelated fail.

**Pull request merged**
