### PR TITLE
CRM-17023 - Search settings

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
- [CRM-17023: ExactFirst doesn't work in quicksearch](https://issues.civicrm.org/jira/browse/CRM-17023)

### CODE REVIEW

**Comment by totten** [comment]
@eileenmcnaughton , I've been a bit back and forth on this. At first glance, it seemed that c3bc1ea was missing the form+config updates (like 2343232). But after testing, it seems that `prefetch`+`config_only` means that the data is still saved and loaded from `config_backend`, so the existing forms still work exactly the same way as before.

Maybe I overdid it with 2343232 -- c3bc1ea seems more efficient. (You don't need to patch the existing admin forms.) By contrast, 2343232 is more thorough -- it removes the cruft and ensures that the `html_*` metadata is correct.  I do want to have good metadata, but really there are two contingencies:

 * We go all the way with CRM-16373 and replace most of the admin UI with a generic one. In this case, we'll have to do a big round of testing/evaluating all the fields/metdata in the new UI. (Even if the metadata is good enough for the current admin UI, it may not be good enough for the new one.)
 * We don't go all the way with CRM-16373. In this case, we continue with the current UI, and it doesn't matter if we've thoroughly vetted `html_*` on the legacy fields.

In either case, there doesn't seem to be much value in going as far as 2343232 did.

**Comment by eileenmcnaughton** [comment]
I would say it's better to go as far as 2343232 - because it at least moves us from one place to the next (if not the final). But, I didn't tackle the form because I was trying not to spend the extra time on it.

**Comment by totten** [comment]
I think I'll have to take it case-by-case. On one hand, if it's a trivial/dumb setting, then I'd rather get them all in a batch (ie moving all data for legacy settings from CRM_Core_Config in one upgrade step). On the other hand, some settings require running special logic when saving, and I'd like to move that logic into `on_change` callbacks.

**Comment by eileenmcnaughton** [comment]
You realise that the upgrade code will migrate them based on tinkering with prefetch & is_config in the metadata (I think you do - just saying in case)

**Comment by totten** [comment]
Yeah, I understand that a high level... at a low level, the prefetch/config_only/config_key/legacy_key stuff blows my mind a bit. They're good for making incremental progress, but it'd be great if there was an end-game for removing them and simplifying the settings architecture. (This is something suggested by [rocky mountain settings group](http://wiki.civicrm.org/confluence/display/CRMDOC/Settings+Reference+Update).)

**Comment by eileenmcnaughton** [comment]
I think prefetch & config_only can be removed without much worry as long as 
1) the settings are not being referred to anywhere as $config->
2) the settings form still works.

**Pull request merged**
