### PR TITLE
CRM-16310 fix for implementing pagination on custom field option list page

### PR DESCRIPTION
**Pull request by jitendrapurohit**
https://issues.civicrm.org/jira/browse/CRM-16310

### CODE REVIEW

**Comment by monishdeb** [comment]
test this please

**Comment by monishdeb** [comment]
test these please

**Comment by colemanw** [comment]
jenkins, retest this please

**Comment by jitendrapurohit** [comment]
@colemanw I've done the changes w.r.t issue's requirement. As everything seems fine to me, can i assign you for QA ?

Thanks.

**Comment by colemanw** [comment]
Sure, sounds good.

**Comment by colemanw** [comment]
This is looking good. My suggestions for refinements:

- Add a "drag handle" icon to the left side of the table, give it css `cursor:move` and only allow dragging from that handle. As it is it's hard to click on links or inline-edit without accidentally dragging a row.
- Use [CRM.status](http://wiki.civicrm.org/confluence/display/CRMDOC/Notifications+and+Confirmations#NotificationsandConfirmations-UnobtrusiveNotifications) to let the user know their changes are saving/saved.
- Don't allow click-sorting the table headers. It just [doesn't make any sense](https://issues.civicrm.org/jira/browse/CRM-13819).
- Wrap crm-editable fields in a div rather than a span, it looks better.
- (nice to have) Redo even/odd row striping after a drag-n-drop.

**Comment by jitendrapurohit** [comment]
@colemanw Thanks for the feedback. I've updated the PR covering the refinements mentioned above.

Thanks:)

**Pull request merged**
