### PR TITLE
dev/membership/#16 Fix duplicate lineitems when creating a recurring membership via backend

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
See https://lab.civicrm.org/dev/membership/issues/16

Before
----------------------------------------
Cannot create new recurring membership via credit card via backend

After
----------------------------------------
Can

Technical Details
----------------------------------------
We just need to update the check for a contribution ID.

Comments
----------------------------------------
@MegaphoneJon Please can you test?

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
I just did an `r-run` and can confirm that this fixes the problem.  I don't have a super-strong sense of this part of the code, but the change looks sensible from what I understand.

**Comment by seamuslee001** [comment]
@mattwire should we put this against the RC?

**Comment by MegaphoneJon** [comment]
@seamuslee001 IMO definitely, since this is a regression from 5.16.

**Comment by mattwire** [comment]
@MegaphoneJon @seamuslee001 Rebased against 5.18 RC  @eileenmcnaughton are you able to take a quick look at this fix for the regression?

**Comment by seamuslee001** [comment]
@mattwire, Eileen has been away i think and not sure when she will come back

**Comment by mattwire** [comment]
@seamuslee001 Ok, I thought it would be good to get a second opinion from someone who's familiar with the cleanup/refactoring we're doing in this area.  That said, I'm happy with the patch, it's simple and clear.  It's also been tested by @MegaphoneJon so your call if you'd like to merge :-)

**Comment by seamuslee001** [comment]
Given Jon's testing i'm going to merge this and if @eileenmcnaughton wants something else she can make the code changes

**Pull request merged**
