### PR TITLE
Disable inline-edit of multi-record custom fields in profiles

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes a bug when editing multirecord custom fields in a profile form.

Steps to Reproduce
----------------------------------------
1. Create a multirecord set of custom fields for contacts (Type "Tab with Table")
2. Create a profile; add the fields to the profile (selecting "Include in multi-record listing?" for each field)
3. Use the profile in edit mode for an existing contact
4. Once you have at least one row of values, click on a value to edit in-place.
5. Javascript error.

After
---------
Profile does not allow inline-edit.

Notes
------
This was reported on StackExchange: https://civicrm.stackexchange.com/questions/25166/disable-inline-editing-of-fields-in-profile-form

### CODE REVIEW

**Comment by bmango** [comment]
I applied these changes to a test site I had set up using Civi 5.1.2. The changes worked when I was logged in as the administrator. No more error was appearing, and I was able to use the inline editing for the dropdown lists in the profile to update values. However, the changes produced another jquery error, a 403 Forbidden error, when I was not logged in as the administrator, but had view edit and delete privileges for the profile.  The error was:
```
jquery.min.js?pacwi7:4 GET http://drupal.benmango.co.uk/civicrm/ajax/rest?entity=contact&action=getoptions&json=%7B%22field%22%3A%22custom_7%22%2C%22context%22%3A%22create%22%7D 403 (Forbidden)
send	@	jquery.min.js?pacwi7:4
ajax	@	jquery.min.js?pacwi7:4
getData	@	jquery.crmEditable.js:216
(anonymous)	@	jquery.jeditable.min.js:17
dispatch	@	jquery.min.js?pacwi7:3
r.handle	@	jquery.min.js?pacwi7:3
```
This was then followed by the original jQuery error: 

```
jquery.jeditable.min.js:34 Uncaught TypeError: Cannot read property 'constructor' of undefined
    at n.fn.init.content (jquery.jeditable.min.js:34)
    at HTMLDivElement.<anonymous> (jquery.jeditable.min.js:18)
    at HTMLDivElement.dispatch (jquery.min.js?pacwi7:3)
    at HTMLDivElement.r.handle (jquery.min.js?pacwi7:3)
```

You can see the new error produced when clicking on the profile dropdowns at the test profile page at [http://drupal.benmango.co.uk/civicrm/profile/edit?gid=14&reset=1&id=109](http://drupal.benmango.co.uk/civicrm/profile/edit?gid=14&reset=1&id=109).

**Comment by colemanw** [comment]
@bmango does your user have "access ajax api" permission?

**Comment by bmango** [comment]
@colemanw - no they didn't. I have now given them permission, and this has solved the first jQuery error (403 Forbidden), but the second jQuery error is still there: 

```
Uncaught TypeError: Cannot read property 'constructor' of undefined
    at n.fn.init.content (jquery.jeditable.min.js:34)
    at HTMLDivElement.<anonymous> (jquery.jeditable.min.js:18)
    at HTMLDivElement.dispatch (jquery.min.js?pad5qd:3)
    at HTMLDivElement.r.handle (jquery.min.js?pad5qd:3)
content	@	jquery.jeditable.min.js:34
(anonymous)	@	jquery.jeditable.min.js:18
dispatch	@	jquery.min.js?pad5qd:3
r.handle	@	jquery.min.js?pad5qd:3
```

**Comment by colemanw** [comment]
I've just attempted to reproduce this by creating a new user and taking away "administer CiviCRM" permission but the profile still worked ok. There must be some permission at play here but I'm not sure which one it is. Can you try adding more permissions to your test user until it works? Let's try to figure out which one it is and then add some code to the JS to check for that permission before attempting the inline edit.

**Comment by colemanw** [comment]
@bmango I've updated this PR to simply not allow inline-edit via profiles instead of trying to fix it, as I don't think it was ever intended to be used in that context anyway.

**Comment by bmango** [comment]
@colemanw Thanks very much for looking at this. Disabling the inline edit makes total sense.

**Comment by colemanw** [comment]
@bmango thanks. If you get a chance to test this PR and confirm it works, we're good to merge :)

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by bmango** [comment]
@colemanw - I have tested that and it works great. There is no longer the ability to edit the fields inline. Everything else is working fine. Many thanks!

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
(*CiviCRM Review Template WORD-1.1*)



* ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) Pass
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) Pass
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) Pass
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) Pass
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) Pass
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) Pass tested by @bmango 
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) Pass
* ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) Pass

**Pull request merged**
