### PR TITLE
[REF] separate financial handling & component transitioning in Payment.create

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Minor code cleanup

Before
----------------------------------------
Code less readable

After
----------------------------------------
Code more readable

Technical Details
----------------------------------------
The goal here is to separate out the concern of handling payments with transitioning
HOPEFULLY we can get to 

```
    if (!$isSkipRecordingPaymentHereForLegacyHandlingReasons) {
      if ($params['total_amount'] > 0) {
        self::recordPayment($contribution['id'], $params, NULL);
      }
      else {
        self::recordRefundPayment($contribution['id'], $params, FALSE);
      }
```

Comments
----------------------------------------
@monishdeb next little 'chip' - I feel like we should decommission recordPartialPayment back into Payment.create (the only place it's being called) so we can unpack it a bit - but maybe we could just cut it out with something like the above

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@monishdeb maybe get this one merged next?

**Review by monishdeb — APPROVED** [review]
Agree with this patch  with calling Contribution.completetransaction API if the payment completes a contribtuion. As the API is responsible to process the components after the associated contribution got complete.

**Comment by monishdeb** [comment]
Existing UT passes too, merging now.

**Comment by eileenmcnaughton** [comment]
Just a clarification - completetransaction was already called - this just splits into 2 parts - the financial processing & then the update related things processing - I think we can do the same with recordPayment as part of making it easier to compare the 2 processes (& generally making it more readable

**Pull request merged**
