### PR TITLE
Api4: Add Price api entities

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Api4 entities for Price, PriceField & PriceFieldValue.

All 3 entities are accessed in the PriceFieldTest

Before
----------------------------------------
No api4 for specified entities

After
----------------------------------------
Basic crud entities created

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton I think I fixed the e-notice causing test failures. It raises the question of whether it's valid to create a priceFieldValue with no name or label, but anyway now you can.

**Comment by eileenmcnaughton** [comment]
@colemanw looks like label is required in v3 - should we declare required somehow?

**Comment by colemanw** [comment]
@eileenmcnaughton if we require it in the db then it will automatically be required by APIv4. Any reason not to do that? It seems silly to allow a field to be null in the db and then manually add validation code to throw an error if it is null.

**Comment by eileenmcnaughton** [comment]
No reason AFAIK

**Comment by colemanw** [comment]
Ok let's see what Jenkins thinks of that

**Comment by eileenmcnaughton** [comment]
jenkins is not impressed! Actually I'm second guessing the 'must have a label' - I wonder if any sites abuse the label being voluntary in any way. Maybe we should merge without that commit & put it up separately & get more feedback

**Comment by eileenmcnaughton** [comment]
On further thought 
1) test fails were related to multilingual. I switched to using php for that
2) I think the v3 api making it required & the UI making label required mean - label is required
3) on the off chance someone was doing something weird with empty labels I changed the label update to set it to a space rather that name

**Comment by seamuslee001** [comment]
This seems to be fine merging

**Pull request merged**
