### PR TITLE
dev/mail#59 - Don't release 5.23 with XOAUTH2 option enabled since it isn't ready yet

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
If the mail protocol option is there people will start using it expecting it to work. It does not work end-to-end yet.

Before
----------------------------------------
Probably several support calls/tickets/chat posts, etc.

After
----------------------------------------
Quieter

Technical Details
----------------------------------------
This leaves the option value in the database but disabled for now.

Comments
----------------------------------------
@seamuslee001

### CODE REVIEW

**Comment by seamuslee001** [comment]
@demeritcowboy i think this is most sensible, note you will need to update the unit tests as well https://test.civicrm.org/job/CiviCRM-Core-PR/32506/testReport/junit/(root)/api_v3_ConstantTest/testmailProtocol_with_data_set__0/

**Comment by seamuslee001** [comment]
I have taken care of the unit test for you @demeritcowboy flagging as merge on pass

**Comment by demeritcowboy** [comment]
Awesome, thanks!

**Comment by seamuslee001** [comment]
test fail unrelated

**Pull request merged**
