### PR TITLE
[TEST] APIv4 - Include CiviGrant in conformance tests

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Make test more inclusive (CiviGrant was feeling left out)

### CODE REVIEW

**Comment by demeritcowboy** [comment]
```
api\v4\Entity\ConformanceTest::testConformance with data set "Grant" ('Grant')
Undefined array key 1921
```

Ah key 1921

**Comment by eileenmcnaughton** [comment]
good old key 1921

**Comment by demeritcowboy** [comment]
Out of my top 2000 keys, I'd rank it about the 1922nd best, maybe 1923rd if I count NULL. (Side thought: Can you count NULL? How much of nothing is there?)

**Comment by colemanw** [comment]
I don't mean to question your taste in keys @demeritcowboy but honestly how can you rank key 1921 above key 2000. I mean, cmon it's two freaking thousand! Doesn't get more keyed up than that. But each to his own I suppose...

**Comment by demeritcowboy** [comment]
Wait, do you rank keys by tasting them? I haven't tried that. Licking the screen seems dangerous, but yolo.

**Comment by eileenmcnaughton** [comment]
Lucky we are only rating the first 2000 - how to rate 2020 would be fighting talk

**Comment by colemanw** [comment]
Nope, the limit was 2000. The `API4TestTrait` couldn't find any options for "grant_type" (because it doesn't ship with any, you have to make your own grant types when you enable that extension) so was just doing this:
https://github.com/civicrm/civicrm-core/blob/9cf73ea67a7895f2ee06995836b840695eb0d729/Civi/Test/Api4TestTrait.php#L318-L319

Fixed it by teaching the API test to make a new option if needed... party like it's 1999!

**Comment by eileenmcnaughton** [comment]
It passes so merging & yep - that is one of the reasons I try to avoid random values

**Comment by demeritcowboy** [comment]
Huh my earlier reference to 2000 was a total coincidence.

Anyway it sounds like you meant to press the merge button? Or maybe this PR needs it pressed 2000 times before it will merge - let's see...

**Comment by colemanw** [comment]
It only works if you pick a random number between 1 - 2000 and it matches -1.

**Pull request merged**
