### PR TITLE
Removes duplicate replace on event fee amount.

### PR DESCRIPTION
**Pull request by agileware-justin**
Removes duplicate replace on event fee amount. Noticed this one whilst reviewing #21738

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@agileware-justin yeah - I was just thinking it looks like a copy & paste error & wondering what it should have been...

**Comment by eileenmcnaughton** [comment]
@agileware-justin this is the other place I listed them https://docs.civicrm.org/sysadmin/en/latest/upgrade/version-specific/

**Comment by eileenmcnaughton** [comment]
Hmm - 5 here, 5 there, a duplicate here, a different duplicate there - maybe there were only 4 :-)

**Comment by agileware-justin** [comment]
These are missing from the upgrader

```
{contribution.contribution_source} -> {contribution.source}
{contribution.payment_instrument} -> {contribution.payment_instrument:label}


```

**Comment by eileenmcnaughton** [comment]
@agileware-justin yeah & also - not all paths had the same tokens - ie. originally (for example not necessarily this one) pdf letters supported `contribution.status` and reminders supported `contribution.contribution_status_id`

I tried to put them in the upgrader as I worked through them & also in the dev docs - but obviously not without making mistakes!

**Pull request merged**
