### PR TITLE
dev/core#2381 - Fix crash when updating tables with blob fields with trigger-based logging enabled

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/2381

1. Turn on logging at admin - system settings - misc.
2. Updating a record in civicrm_file doesn't come up very often, but you can also see this if you just edit the definition of a case type and save. There's only those two tables that have blob fields.

Before
----------------------------------------
Crash / DB Error

After
----------------------------------------
Not crash

Technical Details
----------------------------------------
Comparing fields to see if an UPDATE log record should be made was changed in https://github.com/civicrm/civicrm-core/pull/18782 in 5.35 to take into account upper/lower case and accents. Blob fields have a pseudo-charset called binary which has a pseudo-collation of binary. It's not the same as e.g. utf8_bin, so when you go to do an update on that table the trigger freaks out.

Comments
----------------------------------------
Has test

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I ran this & compared the triggers sql - changes specifically affect

civicrm_case_type_after_update - field = definition
civicrm_file_after_update - field = document
civicrm_search_display_after_update - field = settings

Before

 IFNULL(OLD.`settings`,_utf8'') <> IFNULL(NEW.`settings`,_utf8'') COLLATE utf8_bin

AFTER

OR IFNULL(OLD.`settings`,'') <> IFNULL(NEW.`settings`,''))

I'm getting a crash on editing a saved search before and after this patch with triggers - still digging

**Comment by demeritcowboy** [comment]
You might get the problem with saved search if the extension installs its tables as utf8mb4 but the rest of your civi is utf8. What collation is civicrm_search_display?

**Comment by demeritcowboy** [comment]
I should also note I don't like this PR as much as the alternate - there's a potential issue in this one with columnspecs being out of date if you pass in force=true, I'm just not sure how to "trigger" it in real life.

**Comment by eileenmcnaughton** [comment]
OK so yes - the sql issue IS because our db collation differs from the collation that the contact table is - so the extension was created with the db collation (as a result of us now asking people to remove db collation from extension installs to support mb4 better).

I will speak to this specific patch in a moment but first I want to make the case for reverting https://github.com/civicrm/civicrm-core/pull/18782 out of the rc

What we have is a bit of a perfect storm of changes to encourage mb4 in extensions, this change which as a by-product escalates the impact of mismatched collations and a security release.

I think it's highly likely that sites out there will have extension tables with incorrect collations (we have 4 different combinations of collation and charset on auditing, for historical reasons and because we had to get a bit ahead of our tables with our db charset to accomodate the change in default charset in core).

So my feeling is that we should

1) revert #18782 from the rc
2) add a system check to check if people have mismatched charsets & let that run for a few releases
3) either let the system check / a pre-upgrade check have a bit of time to percolate through before we re-apply #18782 OR look up the specific field on the table to check the charset rather than assuming the db default (my hesitation on this latter is that we already have some developer-issues around the time our install takes which we think is due to existing inefficiency in the logging code and / or it running too much)

It's worth noting that #18782 was picked up as a bug by a sharp-eyed Canadian developer, rather than from a customer report

Specifically to this fix vs the other fix. The OUTCOME of this fix is

image

which seems in line with your analysis

The other patch has a bit too much noise (loss of ` marks) for me to do a good comparison but the salient lines seem like the same change

image


@totten @seamuslee001

**Comment by demeritcowboy** [comment]
I'm ok with reverting it for now. It would be good to work out how extensions should create tables and also how they should get autoincluded in utf8convert (https://lab.civicrm.org/dev/core/-/issues/2237). FYI cdnxreceipts deals with it partly like this but there should be a standard https://lab.civicrm.org/extensions/cdntaxreceipts/-/blob/4cebb499d4b5fea6d7f2b7c7571945065b3c80c3/CRM/Cdntaxreceipts/Upgrader.php#L67-89

Revert PR: https://github.com/civicrm/civicrm-core/pull/19659

**Pull request closed without merging**
