### PR TITLE
[REF] add test & static array to participant values tokens

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
[REF] add test & static array to participant values tokens

Before
----------------------------------------
No visibility into what the array returns since it relies on the mystical & insance bao 'exportFields' function

After
----------------------------------------
Hard coded list & tested

Technical Details
----------------------------------------
The badge screen is the only place in core that leverages this - it actually duplicates some of these tokens. I'm going to rationalise them in a follow up PR

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @colemanw this should be an easy merge I think - I added the test cover before the change to 'prove' it

**Comment by colemanw** [comment]
Looks good.

**Comment by magnolia61** [comment]
Thank you for giving the participant tokens some love 🥰

**Comment by eileenmcnaughton** [comment]
@magnolia61 I'm doing a code cleanup on the tokens in general - if you are able to make some time to test the 5.43 rc when we cut it in October it would be much appreciated as lots of stuff is being changed in token-related codeso some solid testing will be needed....

**Pull request merged**
