### PR TITLE
Fix for failure (fatal error and silent failure) to clean up full text indices

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fix for failure to clean up full text indices

This builds on the test that fails on mariadb 10.4 locally https://github.com/civicrm/civicrm-core/pull/20920 and adds a fix that works for me locally based on 

https://stackoverflow.com/questions/4107599/show-a-tables-fulltext-indexed-columns

Before
----------------------------------------
Hard fail when calling ```findActualFtsIndexNames``` on mariabd 10.4 locally. When I fix it to call the sql in the 'non mysql 8 way' to reflect the tables that are present I get an error on the new test assertion that checks the FULL TEXT indexes were found and deleted.

After
----------------------------------------
Locally this successfully indentifies and deletes the indices.

Technical Details
----------------------------------------
This is also much simpler - the question is whether it works on all sql versions in our matrix

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton I tried this on Max (5.7) and edge (mysql 8) on Max it worked but on edge it failed with 

```
.
Installing build0test_4lhu9 database
EE                                                                 3 / 3 (100%)

Time: 4.78 seconds, Memory: 61.11 MB

There were 2 errors:

1) CRM_Core_InnoDBIndexerTest::testDisabled
Undefined property: CRM_Core_DAO::$index_name

/home/jenkins/bknix-edge/build/build-0/web/sites/all/modules/civicrm/CRM/Core/InnoDBIndexer.php:174
/home/jenkins/bknix-edge/build/build-0/web/sites/all/modules/civicrm/CRM/Core/InnoDBIndexer.php:210
/home/jenkins/bknix-edge/build/build-0/web/sites/all/modules/civicrm/CRM/Core/InnoDBIndexer.php:227
/home/jenkins/bknix-edge/build/build-0/web/sites/all/modules/civicrm/CRM/Core/InnoDBIndexer.php:123
/home/jenkins/bknix-edge/build/build-0/web/sites/all/modules/civicrm/tests/phpunit/CRM/Core/InnoDBIndexerTest.php:53
/home/jenkins/bknix-edge/build/build-0/web/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:254
/home/jenkins/bknix-edge/extern/phpunit8/phpunit8.phar:671

2) CRM_Core_InnoDBIndexerTest::testEnabled
Undefined property: CRM_Core_DAO::$index_name

/home/jenkins/bknix-edge/build/build-0/web/sites/all/modules/civicrm/CRM/Core/InnoDBIndexer.php:174
/home/jenkins/bknix-edge/build/build-0/web/sites/all/modules/civicrm/CRM/Core/InnoDBIndexer.php:210
/home/jenkins/bknix-edge/build/build-0/web/sites/all/modules/civicrm/CRM/Core/InnoDBIndexer.php:227
/home/jenkins/bknix-edge/build/build-0/web/sites/all/modules/civicrm/CRM/Core/InnoDBIndexer.php:123
/home/jenkins/bknix-edge/build/build-0/web/sites/all/modules/civicrm/tests/phpunit/CRM/Core/InnoDBIndexerTest.php:78
/home/jenkins/bknix-edge/build/build-0/web/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:254
/home/jenkins/bknix-edge/extern/phpunit8/phpunit8.phar:671
```

I then changed the Select in your query to have AS index_name on the end and that made the tests pass on MySQL 8

**Comment by eileenmcnaughton** [comment]
@seamuslee001 did you try with the alias against the other versions?

**Comment by eileenmcnaughton** [comment]
I guess it's case?

**Comment by seamuslee001** [comment]
Yeh MySQL8 seems to use the actual column name case rather than what you have in the query which is annoying

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I've updated it

**Comment by seamuslee001** [comment]
if this passes PR tests then we are good

**Pull request merged**
