### PR TITLE
CRM-20498, removed code from run() since its been invoked in parent f…

### PR DESCRIPTION
**Pull request by pradpnayak**
…unction

----------------------------------------
* CRM-20498: buildform hook invoked twice
  https://issues.civicrm.org/jira/browse/CRM-20498

### CODE REVIEW

**Comment by pradpnayak** [comment]
Removed code since this same functions are invoked again from parent class i.e CRM_Core_Page_Basic::run();

**Review by monishdeb — APPROVED** [review]
Tested and confirmed that this patch removes the duplicate code as earlier it overrides the parent ```run()``` function which is already covered in https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/Page/Basic.php#L134

**Comment by monishdeb** [comment]
@eileenmcnaughton @colemanw can we merge it?

**Comment by eileenmcnaughton** [comment]
cool @agh1 actually did a pr to add tests for when buildForm is called twice -  I think I was supposed to be helping him sort out some test issues on it (looks sheepish)

**Comment by agh1** [comment]
@eileenmcnaughton @coleman Yeah i think this actually causes a conflict for https://github.com/civicrm/civicrm-core/pull/10068 it does basically the same thing but without addressing the other places or adding the test

**Pull request merged**
