### PR TITLE
[REF] Fix empty label accessibility issue on report elements

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Fixes accessibility issues on report elements.
Before
----------------------------------------
1. Empty form label on report text element:
Screenshot 2024-07-17 at 11 04 45

2. Empty form label in page break and group by:
Screenshot 2024-07-17 at 11 07 16

3. Empty form label on actions and add contact to group widgets:
Screenshot 2024-07-17 at 11 08 26

After
----------------------------------------
Fixed them all

Technical Details
----------------------------------------
Dependent on https://github.com/colemanw/select2/pull/5

Comments
----------------------------------------
ping @seamuslee001 @colemanw

### CODE REVIEW

**Comment by vingle** [comment]
test this please

**Comment by monishdeb** [comment]
hey @vingle would you give another try to #3 now when the https://github.com/colemanw/select2/pull/6 is merged ?

**Comment by vingle** [comment]
test this please

**Comment by vingle** [comment]
@monishdeb 

I don't know which Reports this PR is referring to but the first I tried gave me an empty label and empty button error:

image

**Comment by monishdeb** [comment]
Similarly this patch fixes : 
- for #1, empty label of input text elements as report filters for all reports
- for #2, empty label to page break / group by checkboxes in all reports

**Comment by vingle** [comment]
Ah I see, thanks - the two issues I flagged weren't targetted in this PR. But the issue that was - missing label for the add to contact select2, was. 

So yes, good to merge from my side.

**Comment by monishdeb** [comment]
Yeah I agree, those are separate issues but good to have them fixed and I'll submit a new PR.

Thank you for your feedback :)

**Pull request merged**
