### PR TITLE
CRM-16373 - $config based on settings (no config_backend). Use Civi:: helper.

### PR DESCRIPTION
**Pull request by totten**
- [CRM-16373: Setting improvements](https://issues.civicrm.org/jira/browse/CRM-16373)

### CODE REVIEW

**Comment by totten** [comment]
This may be a milestone -- `CRM_Admin_Form_Setting` no longer calls `CRM_Core_BAO_ConfigSetting::create()` to store data in `config_backend`. That doesn't mean that all settings forms are simple or that `config_backend` is unused, but it's a nice milestone.

**Comment by totten** [comment]
This is getting relatively cogent -- CRM_Core_Config reads everything from settings; new installations seem to work; and the PR test suite doesn't report any random regressions.

Some remaining tasks:

 1. (Test regression) Decide what to do about *post-boot* overrides in `$civicrm_setting`. (Example: Use hook_civicrm_buildForm to modify `$civicrm_setting`.) This is currently a compatibility-break for downstream developers. I'm inclined to document in the changelog and provide an alternative.
 2. (Test regression) Move the config=>setting migration logic from runtime code to upgrade code (so that it only runs once). Test upgrades.
 3. Rip out more unnecessary code.
 4. Benchmark / optimize with (a) an arbitrary page and (b) an arbitrary unit-test.

@davecivicrm @kurund @eileenmcnaughton -- any opinions on which of those need to be done before merging into `master`?

**Comment by davecivicrm** [comment]
I'd vote for eliminating the test regressions since they are a nuisance in reviewing subsequent PRs.

**Comment by eileenmcnaughton** [comment]
"(Test regression) Move the config=>setting migration logic from runtime code to upgrade code (so that it only runs once). Test upgrades"

In terms of only running once - would it still be possible to run at will - I've enjoyed the relative flexibility of settings in that you can introduce them knowing they won't break a subsequent upgrade (as opposed to adding an activity type that has been added already in 4.6 to 4.4  for example)

**Comment by totten** [comment]
@eileenmcnaughton , it should be unnecessary to run at will. The defaults are read live (modulo cache-flush), so pre-populating `civicrm_setting` doesn't accomplish anything. That should simplify logic during typical installation or typical upgrade or typical domain-creation.  Moreover, there are fewer places where default values are encoded. (*Old*: `xml/templates/civicrm_navigation.tpl` and `civicrm_generated.mysql` and `CRM_Core_Config_Variables` and `config_backend` and `settings/*.php`. *New*: Just `settings/*.php` and an expendable cache record.)

**Comment by totten** [comment]
c139761 (https://test.civicrm.org/job/CiviCRM-Core-PR/5539/) seemed reasonably good - I think the two failures were pre-existing, and I did a pretty careful test of the settings upgrade from 4.5.0=>4.7. Now rebasing to bring up-to-speed with `master`.

**Comment by totten** [comment]
Rebased and we have new test results. The reported test failure, `api_v3_JobTest.testCallSendReminderLimitTo`, is a common false-negative.

**Pull request merged**
