### PR TITLE
dev/core#2188 fix default 'is searchable' to prevent breaking advanced search

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
port of #18970 and #19123to 5.32

@eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I'm find merging this - but did you replicate on 5.32 - the comments @agileware-justin made on the gitlab ticket were kind of like 'this fixes an issue that may or may not be relevant to 5.32'

**Comment by eileenmcnaughton** [comment]
From gitlab - we have @MegaphoneJon identifying this as a long-standing issue and then this 

Screenshot from 2020-12-05 11-34-15

**Comment by seamuslee001** [comment]
closing this out then on that basis

**Comment by totten** [comment]
Reopening. For more discussion about applicability/reproducibility/etc, see [this comment](https://lab.civicrm.org/dev/core/-/issues/2188#note_51345).

@seamuslee001  I also added some more commits to cleanup existing fields during upgrade.

**Comment by totten** [comment]
jenkins, test this please

**Pull request merged**
