### PR TITLE
dev/financial#210: Warn when changing Contribution from non-deductible to deductible

### PR DESCRIPTION
**Pull request by larssandergreen**
Overview
----------------------------------------
If you create a contribution with a non-deductible financial type, the non-deductible amount is set to the amount of the contribution. If you later change the financial type of the contribution to a deductible type, the non-deductible amount will not be changed. The result is that no tax receipt can be issued for the contribution as the full amount is non-deductible, which may not be noticed if tax receipts are issued in bulk.

After
----------------------------------------
If a users changes the financial type from a non-deductible type to a deductible type and the non-deductible amount is non-zero, an alert will be shown warning them they may want to update the non-deductible amount:

image

### CODE REVIEW

**Comment by larssandergreen** [comment]
jenkins test this please

**Comment by demeritcowboy** [comment]
I know this PR seems uncontroversial but I'm wondering about sites that use neither the core print letters function nor cdntaxreceipts, and where the "extra" nondeductible field is irrelevant to them. This message might come up regularly and confuse/annoy them. I don't know of any, just thinking out loud.

Test fail seems related.

**Comment by larssandergreen** [comment]
Test fails were for missing variables, not sure they would ever be missing in real use, but safer to guard them.

My feeling is changing the financial type of a contribution is not a very common thing to do and changing it from a non-tax deductible type to a tax deductible type would be even less common, so it seems like this wouldn't be happening enough to annoy people. But if there's a better way to handle this, let's do that.

What I'm trying to handle is the kind of weird situation where the non-deductible amount is set automatically for you when you add a contribution based on the financial type (so you never think about it) but not changed when you change the contribution financial type (and you wouldn't think to look at it because the financial type of the contribution is now deductible, why would the contribution not be deductible?).

**Comment by larssandergreen** [comment]
upgrade test fail

jenkins test this please

**Comment by demeritcowboy** [comment]
I hear you.
For credit card payments, you can't edit the non-deductible amount field. So you get the warning but you can't action it.

Mixed feelings. Have put merge-ready.

**Pull request merged**
