### PR TITLE
CRM-17281: Fix pledge miscalculation when total amount covers multiple installments

### PR DESCRIPTION
**Pull request by mlutfy**
I also cleaned up the style, to replace, for example:
$statues[1] = array_search('Overdue', $contributionStatus);

with:
$statues[1] = $contributionStatuses['Overdue'];

---
- [CRM-17281: Pledges miscalculate when total amount is not an integer and a payment is received that covers three installments](https://issues.civicrm.org/jira/browse/CRM-17281)

### CODE REVIEW

**Comment by mlutfy** [comment]
The test is perhaps a bit weird (it's my second test ever), but the Pledge API does not do the same as the Pledge form, which calls BAO stuff from outside the BAO "create", i.e. the form calls CRM_Contribute_BAO_Contribution::updateRelatedPledge() directly, and the API does not.

The pledge BAO code is a bit funky, so I don't want to investigate much further for now.

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by JoeMurray** [comment]
Heh Mathieu as Release Manager this month, I'm trying to recruit people to help pare down the backlog of almost 100 PRs, some going back to last summer. I'm wondering if you would be able to help QA another PR or two if I got someone to QA this PR and your other one #8516 ?

**Comment by JoeMurray** [comment]
@jmcclelland would you be interested in QAing this PR?

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by monishdeb** [comment]
@mlutfy there is a related test failure https://test.civicrm.org/job/CiviCRM-Core-PR/12156/ Can you fix it ?  Marking it with WIP for now

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by mlutfy** [comment]
Noting the jenkins error, for posterity:

CRM_Pledge_BAO_PledgePaymentTest::testCreatePledgePaymentForMultipleInstallments
Exception: A fatal error was triggered

/home/jenkins/buildkit/build/core-8540-12hgm/sites/all/modules/civicrm/CRM/Core/Error.php:337
/home/jenkins/buildkit/build/core-8540-12hgm/sites/all/modules/civicrm/CRM/Core/DAO.php:1067
/home/jenkins/buildkit/build/core-8540-12hgm/sites/all/modules/civicrm/CRM/Pledge/BAO/PledgePayment.php:402
/home/jenkins/buildkit/build/core-8540-12hgm/sites/all/modules/civicrm/CRM/Contribute/BAO/Contribution.php:4343
/home/jenkins/buildkit/build/core-8540-12hgm/sites/all/modules/civicrm/tests/phpunit/CRM/Pledge/BAO/PledgePaymentTest.php:403
/home/jenkins/buildkit/build/core-8540-12hgm/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:184
/home/jenkins/buildkit/bin/phpunit4:545

**Comment by monishdeb** [comment]
you must have missed --rebase option i.e. ```git pull --rebase upstream master```

**Pull request closed without merging**
