### PR TITLE
CRM-15919 Address: filter state_province_id by abbreviation in getoptions

### PR DESCRIPTION
**Pull request by agh1**

### CODE REVIEW

**Comment by colemanw** [comment]
Seems like you're changing the behavior of getotions here. Getoptions is for looking up a list of, well, options, not for retrieving info about one object in the db. In this case you aren't interested in a list, just the one value, right?
Seems like what's needed is a stateProvince api.

**Comment by agh1** [comment]
Well, a use case of getOptions is to find the ID for a given label.  I've got "District of Columbia" but I need to know what that should be saved as when I get/save an address.  It's just that unlike many things, there's this alternate label--abbreviation.

A state/province API wouldn't necessarily be bad, but it might be overkill: the only attributes of a state are its name, abbreviation, and country.  Aside from creating new states and changing their names, I'm not sure what would be gained from a state/province API as compared to this fairly small change.

**Comment by colemanw** [comment]
Yea, it's not bad, I guess my hesitation with this is that this will cause inconsistent behavior:

- When passing `'country_id' => 1228, 'value' => "Maryland"` the value param is simply ignored and all states in the US are returned. I'm not even sure why you're passing it.
- When passing `'country_id' => 1228, 'abbreviation' => "MD"` this param now causes the list to return only 1 item.

Maybe another angle to approach this would be to add another 'context' option that would cause abbreviated options (if available) to be returned. Not sure what to call it or how generally useful it would be tho. Well, it would be useful for countries too because they also have abbreviations.

**Comment by agh1** [comment]
Yeah, I got confused in documenting what was going on--you're right that it doesn't filter by value.  I'd be totally fine with a 'context' option as an alternative for consistency's sake.  It would have the benefit that if someone wants to be fancy, they could use that context conditionally based upon the is_province_abbreviated flag on the country.

Now, I poked around a little, and I'd have to add "abbreviation" as a new context option universally, even though it's only used in one situation.  Once I added it as a context and handle it over in CRM_Core_PseudoConstant, it works nicely.  I just think that it's a hack either way.  I'll create a new PR with that change and you can compare the two.

**Comment by agh1** [comment]
Did the context approach at https://github.com/civicrm/civicrm-core/pull/5101 as an alternative to this.  I kind of prefer it, but no strong opinions.

**Comment by colemanw** [comment]
+1 on the context approach.

**Pull request closed without merging**
