### PR TITLE
Crm 16259

### PR DESCRIPTION
**Pull request by pradpnayak**

### CODE REVIEW

**Comment by pradpnayak** [comment]
Could any one please tell the Jenkin to retest the PR?

**Comment by davecivicrm** [comment]
Jenkins, test this please.

**Comment by davecivicrm** [comment]
Pradeep - going forward you have permission on this repo to trigger tests
and retests.

On Mon, Aug 31, 2015 at 11:28 AM, Pradeep Nayak <notifications@github.com>
wrote:

> Could any one please tell the Jenkin to retest the PR?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6461#issuecomment-136454721>
> .
>



-- 
Best regards,
Dave Greenberg
CiviCRM Team
---------------------
Try CiviCRM - http://civicrm.org

**Comment by pradpnayak** [comment]
Jenkins, test this please.

**Comment by davecivicrm** [comment]
Test failures are unrelated.

**Comment by eileenmcnaughton** [comment]
I was just looking at this to see if I could use the refund portion of this for a piece of code I'm working on - but it seems to only accept positive payments @JoeMurray  what was your thinking about refunds - that they would need a separate api function or that they are just not implemented yet ( I lean towards accepting negative payments in payment.create but you may have a reason against).

Where is this api at in terms of going into core? I don't think there are any tests for the api yet so I guess it's not complete? 

(minor point - can we get some comment blocks on the new functions?)

**Comment by pradpnayak** [comment]
jenkins, retest this please

**Comment by pradpnayak** [comment]
closing in favour of https://github.com/civicrm/civicrm-core/pull/7020

**Pull request closed without merging**
