### PR TITLE
Call hook_civicrm_export when exporting custom searches.

### PR DESCRIPTION
**Pull request by johanv**
Overview
----------------------------------------
CRM-21657: hook_civicrm_export is not called when exporting custom search results. Since CRM-8140 was fixed, the problem only shows if you export the custom search fields, not if you make a field selection yourself. 

Before
----------------------------------------
E.g.:
* Click 'search', 'custom searches'
* Click 'basic search' (or any other custom search)
* Click 'search'
* Click 'Select records: All 203 records'
* Click 'Actions', 'Export contacts'
* (Click 'Export custom search fields', and 'Continue' if you are using CiviCRM 4.7.20 or later; this option is not available in earlier versions of CiviCRM.)
* An export is created without calling hook_civicrm_export. 

After
----------------------------------------
E.g.:
* Click 'search', 'custom searches'
* Click 'basic search' (or any other custom search)
* Click 'search'
* Click 'Select records: All 203 records'
* Click 'Actions', 'Export contacts'
* (Click 'Export custom search fields', and 'Continue' if you are using CiviCRM 4.7.20 or later; this option is not available in earlier versions of CiviCRM.)
* An export is created after calling hook_civicrm_export. 

Technical Details
----------------------------------------
Exports of 'ordinary' searches create a temporary table, and pass that table to hook_civicrm_export. Exports of custom searches create a CSV file based on in-memory data.
So I changed the latter so that it also creates a temporary table, and passes it to the hook implementations.

Comments
----------------------------------------
The column definitions that are passed to the hook, are not correct. I say that all columns are varchar(255), which is obviously not true. This might cause troubles if specific hook implementations rely on this.
But I guess you look at the source code to see what I've exactly changed ;-)

---

 * [CRM-21657: hook_civicrm_export is not called when exporting a custom search](https://issues.civicrm.org/jira/browse/CRM-21657)
 * [CRM-8140: Not possible to select fields for export when using Custom Searches](https://issues.civicrm.org/jira/browse/CRM-8140)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
At a high level
1) any hope of a unit test?
2) are there any ways we can better share the code with the non custom code path?

**Comment by johanv** [comment]
I have no clue how to unit test calling a hook. Are there tests that I can look at?
And there are probably ways to better share the code. For the momen this is just a quick hack.

**Comment by eileenmcnaughton** [comment]
This is an example of testing a hook https://github.com/JKingsnorth/civicrm-core/blob/52ed95a82017e7a62a78d587925504f0be8c597d/tests/phpunit/api/v3/ACLPermissionTest.php#L210

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by johanv** [comment]
I will see if I can write a test next week.

**Comment by johanv** [comment]
I tried to add a test, but it fails. Because of 2 issues:

I call [`CRM_Export_BAO_Export::exportCustom()`]([https://github.com/civicrm/civicrm-core/pull/11517/files#diff-2e1de3666cf0b15e640b507b1ab5941fL1200) from [my test](https://github.com/civicrm/civicrm-core/pull/11517/files#diff-4686601201fee8a8402a894c1b7df226R182). But `CRM_Export_BAO_Export::exportCustom()` ends up calling [`CRM_Core_ReportExcel::writeCSVFile()`](https://github.com/civicrm/civicrm-core/pull/11517/files#diff-2e1de3666cf0b15e640b507b1ab5941fR1918), which causes these error messages when running phpunit:
```
1) CRM_Export_BAO_ExportTest::testExportCustomShouldCallHook
Cannot modify header information - headers already sent by (output started at phar:///opt/buildkit/bin/ph
punit4/phpunit/Util/Printer.php:134)                                                              
                          
/var/www/html/sites/all/modules/civicrm/CRM/Utils/System/Base.php:926                             
/var/www/html/sites/all/modules/civicrm/CRM/Utils/System.php:74
/var/www/html/sites/all/modules/civicrm/CRM/Utils/System.php:820
/var/www/html/sites/all/modules/civicrm/CRM/Core/Report/Excel.php:215
/var/www/html/sites/all/modules/civicrm/CRM/Export/BAO/Export.php:1923                                   
/var/www/html/sites/all/modules/civicrm/CRM/Export/BAO/Export.php:1249
/var/www/html/sites/all/modules/civicrm/tests/phpunit/CRM/Export/BAO/ExportTest.php:182
/var/www/html/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:184           
/opt/buildkit/bin/phpunit4:545
```
Even if this problem could be fixed, there is still a call to [`CRM_Utils_System::civiExit()`](https://github.com/civicrm/civicrm-core/pull/11517/files#diff-2e1de3666cf0b15e640b507b1ab5941fR1288), which would cause phpunit to stop running tests.

Any suggestions about how I can create a decent test for this issue?

**Comment by eileenmcnaughton** [comment]
@johanv what I would do is extract the guts of the function, or the part you want to test, to another function & test that - then exportCustom would look something like

```
    public static function exportCustom($customSearchClass, $formValues, $order) {
       self::compileRowsForExport();
      CRM_Core_Report_Excel::writeCSVFile(self::getExportFileName(), $header, $rows);
      CRM_Utils_System::civiExit();
    }
```

**Comment by eileenmcnaughton** [comment]
I'm going to close this because the feature it builds on (per this comment "(Click 'Export custom search fields', and 'Continue' if you are using CiviCRM 4.7.20 or later; this option is not available in earlier versions of CiviCRM.)"

was actually reverted because it caused a regression :-(

Feel free to re-open if you disagree

**Pull request closed without merging**
