### PR TITLE
CRM-18673 fix merge handling of identifal addresses

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
- [CRM-18673: 4.7.8 regression - identical addresses treated as a conflict](https://issues.civicrm.org/jira/browse/CRM-18673)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@JKingsnorth @rocxa do either of you have a change to check this one - it's a regression in the rc

**Comment by eileenmcnaughton** [comment]
unrelated fail

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by JKingsnorth** [comment]
Just double checked this with a matching and a non-matching address - looks OK =] Thanks for the catch and fix @eileenmcnaughton

**Pull request merged**
