### PR TITLE
Add weights to membership type links

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
This includes moving the financial acl permissioning of those links to the financialacls extension (since there was already an affected test in that extension too).

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I had to loosen the type hinting - I could fix pcpLinks to pass objectID but not 'block'

**Comment by seamuslee001** [comment]
@eileenmcnaughton also the manage extensions page passes through a string in the objectId not an int

**Comment by eileenmcnaughton** [comment]
argh the issue is probably that the extension is enabled for everyone - regardless of whether they want these acls - so it needs to check the setting

**Comment by colemanw** [comment]
@eileenmcnaughton is "the setting" now redundant with "the extension is enabled"? And if so should the upgrade code check the setting, conditionally enable the extension based on the setting, and then we can delete the setting?

**Comment by eileenmcnaughton** [comment]
@colemanw the problem is the extension is 'enabled for all' - I'm not sure if we can safely disable it or now - there is still code in core that should be in the extension but perhaps that doesn't cause issues when we disable

**Pull request merged**
