### PR TITLE
dev/joomla#13 lower-case C on CRM_Core_PseudoConstant breaks 5.14 upgrade on Joomla w/ CiviCase

### PR DESCRIPTION
**Pull request by agh1**
Overview
----------------------------------------
A number of places in the code had `CRM_Core_Pseudoconstant` instead of `CRM_Core_PseudoConstant`.  It appears that something about the upgrader on Joomla makes this a problem when it is not an issue in other circumstances.

The result was that the 5.14.0 upgrade would fail on Joomla sites with CiviCase enabled:
https://lab.civicrm.org/dev/joomla/issues/13

Before
----------------------------------------
Joomla upgrade to 5.14.0 fails at the "Rebuild case activity views" step if CiviCase is enabled.  Rolling back, disabling CiviCase, upgrading, and enabling CiviCase succeeds, even though it uses the same functions to do so.

After
----------------------------------------
The upgrade works as expected.

Technical Details
----------------------------------------
After identifying the problem on the one instance, I did a find-and-replace on all mis-capitalizations of CRM_Core_PseudoConstant in the codebase.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I confirmed this is the correct capitalization & the only changes are to capitalisation (& one formatting change which perhaps jenkins needed) - Merge on pass

**Comment by agh1** [comment]
Yeah Jenkins wanted the comma, and then adding the comma meant that my linter said the indenting was whack.

**Comment by totten** [comment]
jenkins, test this please

The test result was a failure in `api_v3_LoggingTest::testRevertRestrictedTables`. This smells like a false-negative, but that one hasn't shown up before on https://lab.civicrm.org/dev/core/wikis/Testy-tests. Unless we get the same failure a second time, I'd say :+1: for merge-on-pass.

**Comment by eileenmcnaughton** [comment]
@totten that's a new one but we should have a patch merged to master if not 5.15 for it

**Comment by eileenmcnaughton** [comment]
unrelated fail

**Pull request merged**
