### PR TITLE
Dashboard - Efficiency tweak

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Minor performance boost for Angular-based Dashboard page.

Technical Details
----------------------------------------
Use static binding for non-changing values.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
r-run still seems to work - how did you identify the need for this?

**Comment by totten** [comment]
Looks sensible to me. I suspect it's identified based on general/systemic preference rather than a specific usage/measurement.

The `{{::ts()}}` always seems look a good idea. The `{{:: $ctrl.foo}}` seems like it might be a little more context-dependent? But looks safe in this case. (The dashboard doesn't include any mechanism for editing or refreshing the dashlet metadata.)

**Comment by eileenmcnaughton** [comment]
@totten so we should always put those `::` before `ts` in angular?

**Comment by totten** [comment]
> @totten so we should always put those `::` before `ts` in angular?

(Reconsiders)  Well... 95% of the time...

The proper question is whether the value will _change_ during the page-view:

* If the value `foo` will not change, then output with `{{:: foo}}`
* If the value `foo` will change, then output with `{{ foo }}`. (*This requires more plumbing to watch for changes. It's not necessarily expensive in isolation, but it can add-up if you have hundreds on a page.*)

Most `ts()` expressions will not change -- they're just simple messages like `ts('Continue')`. But sometimes you have params like `ts("Hello %1", {1: name})` which _might_ change. (A quick-and-dirty grep for  `ts(` in `ang/**.html` suggests the split is roughly 95% vs 5%.) For the 5%, it's a judgment-call.

**Comment by colemanw** [comment]
Right, the `::` at the beginning of the expression tells Angular to evaluate it only once (or, techincally, evaluate it every digest cycle until it resolves to something other than `undefined` and then stop).

If you omit the `::` then Angular will evaluate it every digest cycle, using up the client's cpu needlessly if the value never changes.

**Pull request merged**
