### PR TITLE
Migrate custom file attachments to new case on reassignment.

### PR DESCRIPTION
**Pull request by agilewarealok**
Overview
----------------------------------------
Steps to reproduce the bug:
1. Create a Custom Data Group for Cases and a "File" Field within it
2. Create a new Case, including an uploaded file in the created field
3. Verify the uploaded file can be downloaded
4. "Reassign" the Case to another Contact
5. Attempt to download the updated file

That does not work, CiviCRM  Redirects to Contact's Cases Tab with bounce message "Could not retrieve File"

Before
----------------------------------------
Custom file attachments are not migrated to the new case.

After
----------------------------------------
Custom file attachments are migrated to the new case and downloadable.

Comments
----------------------------------------
_Agileware Ref: CIVICRM-967_

### CODE REVIEW

**Comment by seamuslee001** [comment]
This looks good to me @colemanw @mattwire thoughts?

**Comment by eileenmcnaughton** [comment]
I like the test!

We are adding new functionality specifically to the case entity so we should think about whether there are any cases for this for other entities or it truly is case-specific. Also, we are by-passing the api so we are bypassing hooks and acls (the latter might not be relevant) when we use the dao methods

**Comment by eileenmcnaughton** [comment]
Also - how does this relate to the custom field handling we added to the DAO class to copy custom files?

**Comment by mattwire** [comment]
A big part of the `mergeCases()` function is basically a "copy case entity" function.  We should definitely not be adding more duplicated code here to copy custom files as we already have the `CRM_Core_BAO_File::copyEntityFile()` function but the better fix would be to replace the whole block of code that copies custom fields with `CRM_Core_DAO::copyCustomFields()`.
As there is a test included with this PR it should be quite easy to test if that works.

**Comment by mattwire** [comment]
Test failure is related.

**Comment by jusfreeman** [comment]
We need to re-work this patch, no longer applies cleanly.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by mattwire** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@agilewarealok it's a style failure

**Comment by agilewarealok** [comment]
I think DAO is already handling the custom fields copy in 
copyGeneric function but not sure if it is working well for the files.

I've removed my copy files code and now the Test case I've written is throwing an error.

Can someone guide on this? So we can get this merged in. @eileenmcnaughton @mattwire

**Comment by eileenmcnaughton** [comment]
@agilewarealok I took a look - the issue is the file doesn't exist so the call to CRM_Core_BAO_File::path doesn't retrieve it

I took a look at how api_v3_AttachmentTest works & it has a fn like this

```
  protected function setUp() {
    parent::setUp();
    $this->useTransaction(TRUE);

    $this->cleanupFiles();
    file_put_contents($this->tmpFile('mytest.txt'), 'This comes from a file');
  }
```

What we've been doing is moving utilities in the test code base that support specific types of testing to traits - e.g CRMTraits_ACL_PermissionTrait

I think maybe we want a

CRMTraits_Core_FileTrait

& then move the functions from AttachmentTest that are needed here into that trait & use it from this test (otherwise it's duplication)

**Comment by demeritcowboy** [comment]
Separate from the test, the code in copyGeneric is duplicating the code at https://github.com/civicrm/civicrm-core/blob/master/CRM/Case/BAO/Case.php#L2110, so I get a duplicate INSERT error when I try to reassign a case with a custom field (of any type not just file). If the plan is to use copyGeneric/copyCustomFields then need to also remove the duplicate code?

**Comment by jusfreeman** [comment]
@eileenmcnaughton please close this PR. I think we'll re-submit a new one.

**Comment by eileenmcnaughton** [comment]
@jusfreeman  - sure - but can't you close them?

**Comment by jusfreeman** [comment]
Unit test has been copied to https://github.com/civicrm/civicrm-core/pull/15051

**Pull request closed without merging**
