### PR TITLE
dev/core#926 & dev/core#1048 Fix group search builder bugs

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This pulls fixes for 2 group search bugs from other PRs into one
1) search for groups is empty doesn't work via search builder https://github.com/civicrm/civicrm-core/pull/14553
2) searching within a group for removed contacts ignores the removed status https://github.com/civicrm/civicrm-core/pull/14182

I have combined them into one PR as they both work on the same code (and needed some melding) and I think it's important for them to be tested together. They are both regressions of different ages so targetting 5.15

Before
----------------------------------------
Bug 1 - searching on empty smart groups in search builder fails with a fatal error with critieria like this
Screenshot of failed search critieria

Bug 2 - removed contacts in search results when status=removed have been selected
Screenshot 2019-05-02 17 12 39

After
----------------------------------------

Bug 2
- only removed contacts

Technical Details
----------------------------------------
The underlying issue here (IMHO) is that very complicated group search functionality 'snuck in' through the back door. Some moderately simple (but still tricky) group search functionality was built into advanced search. Since it was done very early on it was not done with the sort of form layer & query layer separation we aim for now. Later groups were exposed in search builder and wound up having all operators exposed. Since some didn't work they were perceived as 'broken' and a succession of people set about trying to fix them to work. Alongside this it was determined that core logic in the way the functionality worked (probably stemming from the very start of group search functionality) was insecure so a series of parallel fixes started tackling that. 

The result has been a very long stream of whack-a-mole in this area :-( The real fix, IMHO, is either to totally re-write it from the ground up with the sort of time budget it should have had in the first place or to remove it from core & let an extension deal with it. However, in practical terms I think we can do neither (people will have pre-existing smart groups based on it). We can do what we have increasingly been doing and insist on unit tests with every fix so we can close the net on the whackamole (I realise some people are frustrated by our requirement that they write unit tests but I also find people remarkably open to us requiring others to meet that standard :-)

The other thing I think we should consider is making a conscious decision to not agree to fixing the remaining underlying issue in core -namely that many of the functions work on regular groups only & in many cases are misleading. Perhaps there is something we can do in the UI to be clearer but I worry we are only one bug-fix away from a whole new round of whackamole and people complaining their server has been brought down by a 'groups empty' search in search builder because it resolves all 2683 smart groups on their site - or similar

Perhaps apiv4 could support something the groaning search builder maybe can't

@monishdeb @jitendrapurohit @jaapjansma @pradpnayak @seamuslee001 @colemanw 

Comments
----------------------------------------
@pradpnayak one of these patches is yours - are you able to review this to check that in my tweaking the 2 together I didn't break anything you fixed (& please also test the other scenario so we can get this merged)

Also, I have a feeling this might not backport well. I'm OK with us trying to port it to 5.14 once merged but let's focus on 5.15 & 5.14 can be an optional extra

https://lab.civicrm.org/dev/core/issues/926
https://lab.civicrm.org/dev/core/issues/1048

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton just looking at the "after" pic for point2, if your searching on contacts removed from the group why are you getting the smart contacts?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I copied that screen shot rather blindly - I don't think it does now

**Comment by seamuslee001** [comment]
I have performed the following testing

1) confirmed that in search builder Groups NULL and Groups NOT NULL work as expected
2) when searching for contacts removed from smart groups only those removed show up

I am unsure if this is within the scope of this PR but i did notice when searching for contacts that have been "Added" to a smart group it would show the ones even removed from the group as well but it did correctly find the "smart" ones as well

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I felt really unsure digging into the code how & if 'added' worked since it seemed to be assumed in the code to mean 'not removed' - I left it as 'it's own thing'

**Comment by eileenmcnaughton** [comment]
sigh - one test fail relates & it doesn't fail in isolation I don't think...

**Comment by eileenmcnaughton** [comment]
@seamuslee001 it passed

**Comment by seamuslee001** [comment]
I'm going to merge this based on my Testing that it has fixed the two specific bugs plus i believe we have improving test coverage in this area which should help regression issues

**Comment by eileenmcnaughton** [comment]
thanks @seamuslee001

**Pull request merged**
