### PR TITLE
CRM-15771 - CRM_Core_Payment - Replace singletons with manager class

### PR DESCRIPTION
**Pull request by eileenmcnaughton**

### CODE REVIEW

**Comment by totten** [comment]
I generally like this commit - but am confused about the removal of CRM_Core_Payment::$_paymentForm. It looks like it's being partially removed -- e.g. $_paymentForm is no longer declared, and setForm() is no longer called, but setForm() and getForm() still use $_paymentForm, and drupal/civitest.module.sample shows it being used by a hook.

I don't have enough experience with hacking CiviContribute to form a strong opinion on this. It would be good to get some +1's or -1's from folks who have worked with CiviContribute more than me. What do you think, @adixon @drastik @Dawnthorn @anemirovsky ?

**Comment by totten** [comment]
I've added comments to http://wiki.civicrm.org/confluence/display/CRMDOC/API+changes#APIchanges-4.6.alpha2:CRM_Core_Payment:Objectconstruction

**Comment by eileenmcnaughton** [comment]
Ah - I see what you mean about the payment form -  although in that case the form could be avoided. The hobbling of the payment form actually happened earlier in 4.6 - I did raise it then but it kind of got lost. The main reason I removed it is that in order to make the forms interact better with the payment processor I made the payment processor an object of the form.  On doing this I found that I had created something recursive and on digging & asking at the time didn't find any support for use of $form in that context. However, now you have dug up something that is at least a theoretical example. 

I guess a safe way might be to cache the form into the cache table in set form & retrieve it with getForm - making it still available if really required.

But, canvassing that change was the main reason for https://civicrm.org/blogs/eileen/46-developer-changes - not yet published. 

Note that this PR is NOT the one that broke that functionality & it doesn't regress it further

 } else if( $paymentObj instanceof CRM_Core_Payment_PayPalImpl && $processorType == 'PayPal' ) {
    // Website Pro  Checkout
    $obj   = $paymentObj->getVar('_paymentForm');
    $value = $obj->getVar('_values');
    $id    = $value['id'];
    if ( $value['event']['id'] ) {
      $id =  $value['event']['id'];
    }

**Comment by eileenmcnaughton** [comment]
as an aside - the code above is pointless - further down in the same example we see a one line alternative
    $cookedParams['custom'] = $rawParams['eventId'];

**Comment by drastik** [comment]
I appreciate the heads up.  

Stripe doesn't use $_paymentForm for anything, nor do any other payprocs I've made.  That is about the extent of what I know on this subject :)

**Comment by eileenmcnaughton** [comment]
I'm going to merge this & take the $form issue to the blog

**Pull request merged**
