### PR TITLE
(NFC) Minor typo: receipients > recipients

### PR DESCRIPTION
**Pull request by UshaMakoa**
/spend 5m

### CODE REVIEW

**Comment by colemanw** [comment]
This is an autogenerated file. The xml needs to be updated and then `GenCode.php` rerun.

**Comment by eileenmcnaughton** [comment]
@UshaMakoa I've added a note to the docs on how to do this https://github.com/civicrm/civicrm-dev-docs/compare/master...eileenmcnaughton:patch-9

This is how the PR winds up looking https://github.com/civicrm/civicrm-core/pull/16810

Since you are doing a bunch of spelling tweaks I'd also be OK with you just putting up the xml fix & we can re-run the DAO generator when you are done

**Comment by UshaMakoa** [comment]
> @UshaMakoa I've added a note to the docs on how to do this [civicrm/civicrm-dev-docs@master...eileenmcnaughton:patch-9](https://github.com/civicrm/civicrm-dev-docs/compare/master...eileenmcnaughton:patch-9)
> 
> This is how the PR winds up looking #16810
> 
> Since you are doing a bunch of spelling tweaks I'd also be OK with you just putting up the xml fix & we can re-run the DAO generator when you are done

Thanks @eileenmcnaughton I'm done.
And I saw https://github.com/civicrm/civicrm-dev-docs/pull/781/files
Understood but need some practice... ;-)

**Comment by eileenmcnaughton** [comment]
@UshaMakoa it's a bit tricky - it's easy to do once you've  got it figured but it  can take a bit  of  figuring out

**Pull request closed without merging**
