### PR TITLE
remove extra field separator field

### PR DESCRIPTION
**Pull request by MegaphoneJon**
Overview
----------------------------------------
See screenshots of "Import Contacts" below.

Before
----------------------------------------
Selection_1799

After
----------------------------------------
Selection_1798

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Ooh and this also fixes a weird thing I was seeing earlier where you click "Previous" and then it crashes after because it wipes out the field separator. I didn't even notice the duplicate.

Actually do you know when this started - should this have been against 5.60?

**Comment by demeritcowboy** [comment]
Hmm now the field separator is missing from Import Activities. Oops.

**Comment by MegaphoneJon** [comment]
Hmm - I tested for this, and I think I maybe got a bit turned around.  I'll replace this and remove the other one.

**Comment by demeritcowboy** [comment]
Thanks. I tried to figure out where the other one was coming from and I think it's dynamic. Then got sidetracked.

**Pull request merged**
