### PR TITLE
setting-admin@1 - Bump version

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

Follow-up to #29173 (ping @colemanw). Since the code of the mixin was changed, we should also increment the version.

### CODE REVIEW

**Comment by colemanw** [comment]
@totten I'm unsure. What does a version increment do exactly? Is it going to cause extensions that declare `setting-admin@1.0.0` to fall-back on a shim? We wouldn't want that.
I think this is ok as long as it doesn't cause extensions to continue spitting out the old format.

**Comment by totten** [comment]
* On general level, it's just good form.
* On lowest level, the edge-case where it matters is vanishingly small.
* The edge-case where it matters is when you have two copies of `setting-admin@1...mixin.php`. The winner is chosen by *highest version* (within 1.x):
    * Raising the version# ensures that it will load the newer implementation
    * Leaving the old version# means that the newer implementation may win... or may lose... who knows. It depends on `$unguaranteedInternalHappenstance`.

**Comment by totten** [comment]
>  (@colemanw) I think this is ok as long as it doesn't cause extensions to continue spitting out the old format.

Rephrasing my answer: exactly, that's why it needs to raise the version. If we don't raise the version, then there's a (very small) edge-case where extensions may continue spitting out the old format.

**Comment by colemanw** [comment]
Cool

**Pull request merged**
