### PR TITLE
CRM-17779: Authorize.Net payments held for fraud detection aren't logged in CiviCRM

### PR DESCRIPTION
**Pull request by monishdeb**
Will add unit test for it soon!!

---
- [CRM-17779: Authorize.Net payments held for fraud detection aren't logged in CiviCRM](https://issues.civicrm.org/jira/browse/CRM-17779)

### CODE REVIEW

**Comment by totten** [comment]
jenkins, test this please

**Comment by eileenmcnaughton** [comment]
Just commenting that I read through this and the code looks good (haven't tested it but the change reads fine.)

**Comment by monishdeb** [comment]
@eileenmcnaughton also the reported has tested on production site  https://issues.civicrm.org/jira/browse/CRM-17779?focusedCommentId=89226&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-89226 and its working for them. However I am sure if we can add any unit test  to assert the new status AUTH_REVIEW (and only can be tested on real time) and can't extend the unit test  tests/phpunit/CRM/Core/Payment/AuthorizeNetTest.php as currently we are simply skipping the test if server is not responsive. So can we simply merge this PR ?

**Comment by PalanteJon** [comment]
@monishdeb You asked if I feel OK merging this on the Jira ticket.

I'll wait for @eileenmcnaughton to give an opinion - I'm not experienced enough with testing to know how best to handle code that relies on an external service like this.  I'm going to propose that one of the trainings during the sprint is to cover different testing scenarios.

**Comment by eileenmcnaughton** [comment]
The code looks good - although I'm no better placed to figure out how to test it :-(

Perhaps Jon you want to go live with it for the customer who requested it? & then ring 25 of your hacker friends & ask them to do some dodgey transactions....

**Comment by PalanteJon** [comment]
This was tested by my client, who holds payments under $5 and over $3000 with the Authorize.Net fraud detection filter.  She reports:
I can confirm that the $1 is in as ‘pending’ in Civi and in Authorize waiting for approval. And I see where I could change “pending” to completed in Civi

I also made a $10 donation which is showing up in Civi fine and not flagging anything in Authorize.

So I think we are all set here. Thanks so much! 
@totten please merge?

**Comment by eileenmcnaughton** [comment]
Merged based on Jon's QA

**Comment by bhugh** [comment]
I had this issue pop up in our CiviCRM installation.  In our case it is because we turned up the "Fraud Protection Suite" settings in authorize.net, causing certain transactions to be "held for review".  After approving the transaction in authorize.net, we discovered that CiviCRM had simply discarded the entire transaction.  Not good.

However, testing the code in this patch, I found it didn't work correctly.  We are still on CiviCRM 4.2, so it is possible that is the reason, but I traced the code in our installation and the most recent version here on GitHub on up the chain, and actually the two are close to identical.  FYI the function CRM_Core_Payment_AuthorizeNet::doDirectPayment is called by CRM_Contribute_BAO_Contribution_Utils::processConfirm which processes the results a bit & the passes them on to CRM_Contribute_Form_Contribution_Confirm::processContribution.

The basic problems are:

 - The functions I just named don't do anything with $params['payment_status_id'].  payment_status_id does exist in the RECURRING payment system, which might be the source of the confusion.  But setting payment_status_id to anything in the $params return from doDirectPayment actually results in nothing at all happening.

 - $params['contribution_status_pending'] is actually effective--values appear to be either 0 or 1.

So here is code that appears to work on our setup:
```
...
 CONST AUTH_REVIEW = 4;
...

switch ($response_fields[0]) {
      case self::AUTH_REVIEW :
        $params['contribution_status_pending'] = 1; //OK, in our ver "Payment_status_id" doesn't seem to do ANYTHING but maybe is_pay_later will
        watchdog ('civi_authorize', "Auth_Review detected for this transaction");
        break;

      case self::AUTH_ERROR :
        $errormsg = $response_fields[2] . ' ' . $response_fields[3];
        return self::error($response_fields[1], $errormsg);
        break;

      case self::AUTH_DECLINED :
        $errormsg = $response_fields[2] . ' ' . $response_fields[3];
        return self::error($response_fields[1], $errormsg);

      default:
        // Success

        // test mode always returns trxn_id = 0
        // also live mode in CiviCRM with test mode set in
        // Authorize.Net return $response_fields[6] = 0
        // hence treat that also as test mode transaction
        // fix for CRM-2566
        if (($this->_mode == 'test') || $response_fields[6] == 0) {
          $query = "SELECT MAX(trxn_id) FROM civicrm_contribution WHERE trxn_id RLIKE 'test[0-9]+'";
          $p = array();
          $trxn_id = strval(CRM_Core_DAO::singleValueQuery($query, $p));
          $trxn_id = str_replace('test', '', $trxn_id);
          $trxn_id = intval($trxn_id) + 1;
          $params['trxn_id'] = sprintf('test%08d', $trxn_id);
        }
        else {
          $params['trxn_id'] = $response_fields[6];
        }
        $params['gross_amount'] = $response_fields[9];
        break;
     }
    // TODO: include authorization code?
    //bhugh, testing
    //print_r($params);
    return $params;
```

Note that this is quite difficult to test.  I tested by going into authorize.net and setting "Enhanced CCV Handling Filter" option "If Card Code value N Does NOT Match" to "Authorize And Hold For Review". Then I entered a (live, not test) credit card payment with deliberately incorrect CCV. This caused authorize.net to hold that transaction for review and return the value 4 (=AUTH_REVIEW) in $response_fields[0].  Then I could check what actually happened to the transaction in CiviCRM.

Another useful way to test is simply set $response_fields[0] = 1; then = 2, =3, =4 etc in a line right about  _switch ($response_fields[0]) {_

Then run a transaction and watch what happens. This (or something similar) would work with either live or test transactions. (I don't know how to trigger the AUTH_REVIEW code in a test transaction--if you could it would making testing a lot easier!)

I realize this isn't exactly a unit test but maybe it will give someone an idea about how a unit test could be made to work.

**Comment by eileenmcnaughton** [comment]
Do you mean 4.2? From 4.7 onwards I would expect  it to keep a pending contribution if it doesn't realise it has succeeded

**Comment by bhugh** [comment]
Yes, the version we're running is 4.2.2  (with a lot of later patches applied--it gets a bit confusing).

**Comment by eileenmcnaughton** [comment]
ug

**Pull request merged**
