### PR TITLE
APIv4 - RequestSpec caching

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Implements in-memory caching for APIv4 getFields. This significantly speeds up SearchKit, especially when the display includes links or in-place editable fields.

Before
----------------------------------------
Every call to getFields would rebuild `FieldSpec` objects from scratch and call every `SpecProvider` for modifications, then transform those objects into an array & filter it down to maybe just the one field you wanted in the first place.

After
----------------------------------------
All of that is cached.

Technical Details
----------------------------------------
Caching happens as late as I could manage it... *after* the `FieldSpec` objects have been modified by every `SpecProvider` and converted to their final array form, but *before* pseudoconstant options are loaded (there's already a cache for those somewhere, I think).

Getting a cache key for this was tricky since `getFields` accepts an array of `$values` which could contain possibly anything. I solved this by tracking which values are actually used by the specProviders. Every time a specProvider calls `RequestSpec->getValue()` we keep track of that and it gets added to the cacheKey.
Probably 90% of entities don't have any fancy specProviders so our tracker knows that all $values can be safely ignored & this keeps caching for them very simple. For more complex entities, there will be considerably more copies of the fields in memory; hopefully that won't be a problem.

`Civi::cache('metadata')->clear()` will trigger a flush of this in-memory cache as well, although that dispatcher was broken so I had to fix it via #29072.

Breaking Changes
-----------------------
The changes in this PR are mostly internal. While a couple of them could hypothetically affect extensions that have very deep integrations with APIv4, a `universe` search shows that to be mostly hypothetical.

1. The params passed to `FieldSpec::setOptionsCallback` function now gives `$field` as an array rather than an object.  This is a pretty obscure feature outside of core. I was only able to find one such example in `universe` (and it was written by me). I [submitted a PR](https://github.com/systopia/de.systopia.eck/pull/106) to update that callback.
2. `SpecProviderInterface::applies` no longer receives `$values` as a 3rd param. This was [only added recently](https://github.com/civicrm/civicrm-core/commit/1be8a0e0c4a5862323429c8388fd0cbbdfea524a) and never documented so I can't find anything in `universe` outside of core, nor would I expect to.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw I feel good about test cover here but can you explain the `modifyApiSpec()` change a bit more - is this one not cached differently to the modify in the ImportSpecProvider?

**Comment by colemanw** [comment]
@eileenmcnaughton this PR basically puts a cache in front of every `SpecProvider`, so the static caching in `ImportSpecProvider::getJobType` is now redundant & should be removed to save memory.

I'll expand the PR description a bit. Docs update might be in order too, I'll check...

**Comment by eileenmcnaughton** [comment]
timing 5.69

image

master with other recent patches, but not this one

image

master with this patch too

image

So this shaved a further 15 seconds-ish off the time the page took to load. That's a definite win - although even 18.72 seconds still feels like there is quite  a bit of room for improvement. I may yet do another cache grind to see but this seems like a clear improvement and our cumulative improvement is dramatic

**Comment by eileenmcnaughton** [comment]
@colemanw I may have been too hasty here - the fields seem to no longer be editable! Still probably easier to address as a follow up since this moves a lot of stuff

**Comment by colemanw** [comment]
@eileenmcnaughton hmm, I thought we had tests for that. Quick test shows the fields as editable for me. Can you give a example search?

**Comment by eileenmcnaughton** [comment]
OK - update - the editable was broken without this but works in 5.68 -  but is broken in 5.69. Importantly the import search kits rely on a non-standard primary key which could be what broke?

**Comment by eileenmcnaughton** [comment]
@colemanw hang on - it might be that they are not editble because the rows imported - let me try changing the status to error & see

**Comment by eileenmcnaughton** [comment]
Yep - that's it! All good

**Pull request merged**
