### PR TITLE
CRM-20052 get Billing Block js working as expeected on Drupal 8 as it…

### PR DESCRIPTION
**Pull request by seamuslee001**
… does elsewhere

Lined Issue https://issues.civicrm.org/jira/browse/CRM-20052

### CODE REVIEW

**Comment by jackrabbithanna** [comment]
@seamuslee001 , @totten 
 I've tested this with the D8 module, and can confirm that this PR fixes the problem

**Comment by jackrabbithanna** [comment]
@colemanw this works for me

**Comment by eileenmcnaughton** [comment]
@seamuslee001 my read on this is that it is mostly whitespace changes + a little bit of 'add the js to the header not the default' and some weighting. If this is correct, and based on Mark's testing I would say 'OK to merge', although given the rc should really have already been cut I would merge after it is cut in order to give this that bit longer in the testing stage (esp since it is not impacting on stable CMS)

**Comment by seamuslee001** [comment]
@eileenmcnaughton yes that is the case and the only other thing is adding in this 

```js
$(function() {
```
Which is a wrapper which is a short had for $document.ready() so this only runs once the dom has been loaded ( which it would do if it was added to the page bottom as it used to) the issue is in D8 we don't appear to have a page-bottom region to add anything to.

**Comment by eileenmcnaughton** [comment]
Ok - let's wait for the rc to be cut & then merge this.

**Pull request merged**
