### PR TITLE
APIv4 - Add MembershipPayment

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Allows Contributions to be joined to Memberships in APIv4 & SearchKit.

Before
----------------------------------------
Join not available.

After
----------------------------------------
image

### CODE REVIEW

**Comment by mattwire** [comment]
This one's a bit tricky... some history here and probably elsewhere. My understanding was that we are slowly deprecating `civicrm_membership_payment` in favour of retrieving the same information via lineitems. The lineitem should always be consistent whereas I think there are various scenarios where the `MembershipPayment` record may not exist.

**Comment by mattwire** [comment]
Also a (rather old) comment here: https://github.com/civicrm/civicrm-core/blob/master/CRM/Member/BAO/MembershipPayment.php#L46
My preference would be to not expose this in API4 but instead provide a way to easily map via lineitems.

**Comment by colemanw** [comment]
Good catch @mattwire. Ok let's not.

**Comment by adixon** [comment]
Agree and thanks for the enlightenment.

**Pull request closed without merging**
