### PR TITLE
[ON HOLD] CRM-21320 Fix selection of mobile number in mass SMS

### PR DESCRIPTION
**Pull request by JKingsnorth**
Overview
----------------------------------------
Fix the logic that selects a contact's phone number when using bulk SMS functionality in CiviCRM.

Before
----------------------------------------
The 'latest' mobile number associated with the contact was selected, regardless of whether the other number is 'primary'.

After
----------------------------------------
The primary mobile number on the contact is selected as a priority.

Technical Details
----------------------------------------

- Add ORDER BY to the phone number selection query, to ensure that primary information is 'preferred'; as already happens with the email selection query.
- Add a test!

Comments
----------------------------------------
This is my first ever test that I've written, please do let me know how to improve it! I was a bit horrified to see that there are no existing tests for the Mailing BAO. And there is a LOT of refactoring that could be done in the getRecipients method. But lets fix the current bugs first...

---

 * [CRM-21320: Mass SMS can select non-preferred mobile number](https://issues.civicrm.org/jira/browse/CRM-21320)

### CODE REVIEW

**Comment by JKingsnorth** [comment]
Yippee, the test without the patch is failing here (https://github.com/civicrm/civicrm-core/pull/11158) and here, with the fix, it works.

**Comment by JKingsnorth** [comment]
@michaelmcandrew Did you get a chance to look at this'n?

**Comment by michaelmcandrew** [comment]
not yet, should be able to this week

**Review by mattwire — CHANGES_REQUESTED** [review]
@JKingsnorth The fix looks entirely correct, and now it's locked in with a unit test.  Looking at the function getRecipients() wow! it is a bit of a mess...  Would be great if you get time to do a proper refactor once this is in.

For this patch, could you make the following changes:
1. Use a variable for the ORDER BY clause ($order_by as used by email).
2. Is this line used for SMS too?
  If not, can it be wrapped in an if (email) $order_by=.. elseif (sms) $order_by= .. clause?  That would help with refactoring later. https://github.com/JKingsnorth/civicrm-core/blob/c72515c451185b0991433ec5d1b463da7667a6dc/CRM/Mailing/BAO/Mailing.php#L156

**Comment by JKingsnorth** [comment]
@mattwire I think this function is undergoing some refactoring by @monishdeb here https://github.com/civicrm/civicrm-core/pull/11142

What's the advantage of using the variable over just writing it out in these cases? (Happy to do so, but just wondering).

That piece of code around selecting emails based on location is not currently used by the SMS functionality - though it would be a good follow-up [=

**Comment by mattwire** [comment]
@JKingsnorth No advantage at all :-)  Just think it would make future refactoring easier, as it's then consistent with the SQL queries for email.

**Comment by JKingsnorth** [comment]
@mattwire Fairenough, I'll make the change [=

**Comment by monishdeb** [comment]
@JKingsnorth @mattwire in relation to #11142 here's my plan. As per refactoring change I have wrapped up the code to fetch location filter and order by in a separate function called ```getLocationFilterAndOrderBy(...)```. So in order to provide the support for sms mode we can extend the function somewhat like 
```php
function getLocationFilterAndOrderBy($selection_method, $location_type_id, $mode = 'mailing') {
  ... 
  'default': 
    if ($mode == 'sms') {
       $order_by = "$phone.is_primary = 1";
    }
   else {
      $location_filter = "($email.is_bulkmail = 1 OR $email.is_primary = 1)";
      $order_by = "ORDER BY $email.is_bulkmail";
   }
}
``` 
And later that $order_by variable can be used in desired query. Extending this fn has another advantage as now we can make use $selection_method and decide the orderBy and location filter accordingly for phone recipients. 

Now back to this issue, I agree with the patch but for more generic fix the getRecipients(...) needs refactoring. So I would say, lets hold this PR for now, and after #11142 gets merged we will extend the getLocationFilterAndOrderBy(...) to handle the query to fetch recipients, accordingly. What do you think?

**Comment by JKingsnorth** [comment]
OK, we can do. I'll rebase this PR after #11142 is merged.

**Comment by michaelmcandrew** [comment]
hey @JKingsnorth,

Sorry I did not get a chance to review this before the holidays. It looks like it is on hold pending #11142 for now but let me know if you need any more eyes on it.

**Comment by JKingsnorth** [comment]
I started looking at this again, now that #11142 has been merged, but I've paused again until https://github.com/civicrm/civicrm-core/pull/11142#discussion_r162647718 is resolved.

**Comment by eileenmcnaughton** [comment]
@JKingsnorth This is stale & on hold so I'm going to close it & let you re-open when it's ready for review again

**Comment by JKingsnorth** [comment]
Thanks @eileenmcnaughton  - sorry this was actually already resolved by https://github.com/civicrm/civicrm-core/pull/11558

**Pull request closed without merging**
