### PR TITLE
dev/core#2568 Enotice fix + test

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Same as https://github.com/civicrm/civicrm-core/pull/20178 but with a test
(and a couple of changes to support that)

Overview
----------------------------------------
dev/core#2568 Enotice fix + test

Before
----------------------------------------
This is mostly about adding the tests for dev/core#2568 - it might be nicer to merge that one to actually fix the bug

After
----------------------------------------
Test added

Technical Details
----------------------------------------
@demeritcowboy so this adjusts another call to use getIDs() - once again I don't feel like I can replicate the issue we were hitting before 

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@demeritcowboy are you able to review this? I have a follow up - but it's just a test that builds off this test - which I'll put up when this is merged

**Comment by demeritcowboy** [comment]
jenkins retest this please (since some relates to https://github.com/civicrm/civicrm-core/pull/20187)

**Comment by demeritcowboy** [comment]
This seems ok. Tried a couple variations.
The setContributionIds() is only used for tests. The other replacements seem ok.

**Comment by eileenmcnaughton** [comment]
thanks @demeritcowboy

**Pull request merged**
