### PR TITLE
Pending #17146 Always use cancelSubscription form if recur has a payment processor

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
There was existing code to handle cancellation if the processor does not support cancellation.

You may still want to record cancellation reason, see instructions to manually cancel with your provider and send a notification email to the contributor.

But if the processor reports that it does not `supportCancelRecurring` the form is never displayed and the built in entity enable/disable via javascript is used. This only really makes sense if there is no payment processor.

Before
----------------------------------------
enable/disable javascript used if processor does not support cancelling recur (cancel link still available in list of recurs!).

After
----------------------------------------
If recurring contribution has a payment processor, always display the cancellation form. Eg.
image

image

Technical Details
----------------------------------------

Comments
----------------------------------------
This cleans up another inconsistency in the way civi handles things. Most of the work leading up to this was yours @eileenmcnaughton so comments would be appreciated.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I agree with this in principle. I'll have to test it out. One thing I'm not sure about though is the assumption that the form doesn't make sense  when no  payment_processor_id is present.  That  is usually the case when recurrings have been imported from  another system & the ability to record a reason is also useful in that scenario

**Comment by mattwire** [comment]
> One thing I'm not sure about though is the assumption that the form doesn't make sense when no payment_processor_id is present

@eileenmcnaughton Ok, let's get rid of the other one altogether - the only reason I didn't apply to the case when no payment_processor_id is present is because I thought that might affect your use-case :-)
Will update the PR.

**Comment by eileenmcnaughton** [comment]
cool

**Comment by eileenmcnaughton** [comment]
@mattwire take a look at #17146 - I think this might get simpler if we do that

**Comment by mattwire** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I'm going to close this for now - let's reopen once #17146 is merged - with whatever changes are needed

**Pull request closed without merging**
