### PR TITLE
Remove references to open flash chart, including uploadchartimage fun…

### PR DESCRIPTION
**Pull request by artfulrobot**
This follows

- https://github.com/civicrm/civicrm-core/pull/15474 and
- https://github.com/civicrm/civicrm-core/pull/15448

in removing the final bits of openflash chart.

**PR is not ready yet: I need help - there's one file left with a reference to `uploadchartimage`: which is `sql/civicrm_generated.mysql` but I don't know how that gets generated?

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@artfulrobot there was discussion about this not working previously so removing is OK - where was that?

**Comment by eileenmcnaughton** [comment]
I think setup.sh or civibuild create will regenerate the generated sql - it's coming from the menu so you have already removed that part

**Comment by seamuslee001** [comment]
there may be a reference in xml/templates/civicrm_navigation.tpl that you will want to get rid of then run ./bin/regen.sh iirc

**Comment by seamuslee001** [comment]
Added Merge on pass looks good and i thought it might have been something there because i thought that is what was used to generate civicrm_generated but clearly it must load in the menu xml as well so all good mate

**Pull request merged**
