### PR TITLE
Add civicrm_admin_ui extension

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds a new bundled extension. So far this extension replaces 2 screens with SearchDisplay Afforms:
- Custom field groups
- Custom fields

Before
----------------------------------------
Old screens made with Smarty

After
----------------------------------------
New screens look very similar, but made with SearchKit and thus user-configurable:

image

### CODE REVIEW

**Comment by mattwire** [comment]
@colemanw Looks very nice but can we keep the group/field IDs in by default? That was a feature added a few years ago that a lot of people find very useful.
image

On second thoughts the ID will become less useful now we can use API4 and access them via the `Group_name.field_name` syntax instead.. is it currently possible to expose that style as one of the fields? Does not need to be by default but should be possible as it saves so much time when doing any extension/custom work. I just had to talk someone (non-dev) through getting the API4 custom field name through the API4 explorer and they really struggled.

**Comment by kcristiano** [comment]
@mattwire I do think we should keep the IDs exposed.  These have proven useful in many case for us and our Clients CiviCRM admins.

**Comment by colemanw** [comment]
Ok added ID column

**Comment by monishdeb** [comment]
@colemanw I found two issues: 
1. On previewing the custom field, it get a blank popup screen
2. Done button background is white, which makes it difficult to read on hover. 

Here's a screencast to demonstrate the two issues: 
 
before


Used test build site http://core-22628-6cyb1.test-3.civicrm.org:8001 ( admin / 2bCuOWlAzpMB )

**Comment by colemanw** [comment]
@monishdeb thanks for the review. I've fixed the preview link. I think the button styling is a generic theme issue which we should address separately.

**Comment by colemanw** [comment]
I'm marking this as a draft because there's one outstanding bug: the drag-sorting is not working properly.

**Comment by demeritcowboy** [comment]
I did a little testing of this along with https://github.com/civicrm/civicrm-core/pull/22716. Because drag'n'drop is frustrating over long lists and the old "move to top/bottom" buttons were handy, I altered the search display to include Order and made it edit-in-place. That works as a workaround (with 22716 applied).

I agree the Done button is weird. Does something like the custom fields page even need a Done button?

**Comment by colemanw** [comment]
Ok I think all the major issues have been addressed so I'm giving this `merge-ready`.
Note that merging this PR simply adds a new extension which is deactivated by default.

**Comment by eileenmcnaughton** [comment]
I'm merging this since it is de-activated  default & known concerns are addressed

**Pull request merged**
