### PR TITLE
[pending core team review] CRM-16617

### PR DESCRIPTION
**Pull request by pradpnayak**
- [CRM-16617](https://issues.civicrm.org/jira/browse/CRM-16617)

### CODE REVIEW

**Comment by JoeMurray** [comment]
Could a core team member determine if this failing check is due to JMA pro bono contributed code?

**Comment by monishdeb** [comment]
Test-build failures are unrelated. (occurred due to https://issues.civicrm.org/jira/browse/CRM-13160 changes)

**Comment by pradpnayak** [comment]
Thanks @monishdeb

**Comment by colemanw** [comment]
- I believe the function `mysql_real_escape_string` is deprecated but I don't know of a better alternative.
- Adding a unit test for `requireValidDBName` would be really great.

**Comment by JoeMurray** [comment]
The function mysql_real_escape_string is deprecated as part of deprecating PHP's mysql extension. It is needed until CiviCRM moves to PHP's mysqli extension.

**Comment by JoeMurray** [comment]
Pradeep, please provide unit test.

**Comment by colemanw** [comment]
@pradpnayak we can merge this once a test is added.

**Comment by eileenmcnaughton** [comment]
Per my comments on the ticket - I think we should let this go through without a test if the code passes QA (I'm not qualified to do that).

Note a PR is also required against master

**Comment by JoeMurray** [comment]
Fwiw, mysql_real_escape_string() is not deprecated in MySQL itself. The
problem is that all mysql_* functions in PHP are deprecated in favour of
msqli_* ones, and this function gets renamed in that library - see
http://php.net/manual/en/mysqli.real-escape-string.php

**Comment by pradpnayak** [comment]
Added unit test

**Comment by pradpnayak** [comment]
https://github.com/civicrm/civicrm-core/pull/7764 against master branch

**Comment by eileenmcnaughton** [comment]
This is superceded now isn't it?

**Comment by xurizaemon** [comment]
@eileenmcnaughton - do you mean the whole patch doesn't apply, or something else? I did wonder (and ask in IRC!) if there was work on the installer at the recent sprints. It still applied to master (just now).

Couple of nitpicks, otherwise I think this looks OK visually -

* Commit messages should be helpful *and accurate*; "CRM-16617, moved function to BAO" actually moves it to DAO.
* I had to look hard at `/^[0-9]*[a-zA-Z_]+[a-zA-Z0-9_]*$/` to see why; it's because [Identifiers may begin with a digit but unless quoted may not consist solely of digits.](http://dev.mysql.com/doc/refman/5.0/en/identifiers.html) (so that's OK). Might be worth documenting?
* As Joe says, I feel like calling methods on an object might want a `method_exists()` or check against actual class.

**Comment by eileenmcnaughton** [comment]
I was looking at this https://github.com/civicrm/civicrm-core/pull/7764 - but that is master not 4.6 actually. However, that is the one to merge first

**Comment by xurizaemon** [comment]
argh ok, yep thought i was looking at the patch to master here

**Comment by colemanw** [comment]
I've copied your comments over to the other PR.

**Pull request merged**
