### PR TITLE
Payment notification formatting, move greeting into table

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Align greeting in payment notification email

Before
----------------------------------------
screenshot from 2019-02-22 11-26-17

After
----------------------------------------

Technical Details
----------------------------------------

Comments
----------------------------------------
per https://github.com/civicrm/civicrm-core/pull/13655#issuecomment-466350703

### CODE REVIEW

**Comment by magnolia61** [comment]
I tested it, it does not show the greeting.
When I exhange the code:
`{if $emailGreeting}<tr><td>{$emailGreeting},</td></tr>{/if}`
to the line in most other templates is used it works ok (and in other templates it is not in its own <tr><td>
`{assign var="greeting" value="{contact.email_greeting}"}{if $greeting}<p>{$greeting},</p>{/if}
`

**Comment by eileenmcnaughton** [comment]
@magnolia61 hmm - I guess we just merged support for $emailGreeting into master branch for that template & you might not have that locally yet?

**Comment by magnolia61** [comment]
You are right. I can confirm the template works fine on current master

**Comment by eileenmcnaughton** [comment]
@monishdeb are you good to merge this follow up per @magnolia61 request

**Comment by monishdeb** [comment]
Agree with the fix. Merging now. 

Thanks, @magnolia61 for your review.

**Pull request merged**
