### PR TITLE
Don't add newlines into HTML emails when viewing activities

### PR DESCRIPTION
**Pull request by larssandergreen**
Overview
----------------------------------------
br tags are added to all activity details, resulting in annoying double empty lines in HTML emails when viewing activities. Besides being annoying, some users may be concerned they sent an email with bad formatting.

Before
----------------------------------------
br tags are added to HTML emails, resulting in this:
image

After
----------------------------------------
If the activity type is email and there are HTML tags present, we don't add br tags — and now the email displays as sent.
image

### CODE REVIEW

**Comment by demeritcowboy** [comment]
There's a stackexchange with a discussion about this, or something similar. Let me see if I can find it but it looks like you may have addressed the reason where it was needed.

**Comment by larssandergreen** [comment]
There's [this one on SE.](https://civicrm.stackexchange.com/questions/38836/extra-blank-lines-in-email-saved-in-activities), which I think this solves. That also links to [this one about notes.](https://civicrm.stackexchange.com/questions/31535/br-tags-inserted-in-rich-text-fields-custom-fieldsets-when-displayed-as-tabs/31574#31574), which this PR doesn't do anything about.

**Comment by demeritcowboy** [comment]
Nice - that would be it. I can review this one.
There's also a unit test I wrote somewhere about something like this, so should be at least partly covered.

**Comment by demeritcowboy** [comment]
So once again I've managed to turn something that seems simple into something complicated.

* General standards
    * [`r-explain`] __PASS__
    * [`r-user`] __PASS__
      * Users will likely be happy.
    * [`r-doc`] __PASS__
    * [`r-run`] __Issue__
      * `$defaults['details']` sometimes gives me undefined index. While it's maybe not common in real life to have an email activity with nothing in the body, one thing we've learned is if you let users do something then they will do it, especially ones named Dave. Apparently I have several of these in my database (both empty details and Dave's).
        * The database default is null for the field, so there's more than one way to end up with this happening even if your name is not Dave. And even if it got assigned as NULL instead of missing, you'd get a php 8 error with strip_tags.
* Developer standards
    * [`r-tech`] __Confused, but out-of-scope so something for future maybe__
      * It's pre-existing but I'm confused about when it uses Activity.tpl vs ActivityView.tpl. I mean it depends on the url, but both potentially have html details, and could potentially be used for any type.
    * [`r-code`] __Issue__
      * While `3` is one of the best numbers, and in my own top 10, it should be `CRM_Core_PseudoConstant::getKey('CRM_Activity_BAO_Activity', 'activity_type_id', 'Email')`.
      * We can't use isset() later in the template if we want to be compatible with smarty-escape-by-default - see [WIP docs](https://lab.civicrm.org/documentation/docs/dev/-/issues/880). So you would want to explicitly assign is_html_email to either true or false.
      * The comparison with strip_tags is not foolproof, since there could be a text alternative stored that has text like `Hello <insert name>`. Since the output is ultimately the output from `{crmStripAlternatives}`, it made me look at the function that powers that (CRM_Utils_String::stripAlternatives), and then noticed that it just picks the "first one", so the strip_tags comparison might be wrong reasonably often (i.e. the output is ultimately text, but is_html_email will be true).
        * You might make an argument that this never comes up for activity type 3 (Email) because civi always stores the html first for those. But (a) Daves, and (b) extensions and imports and whatnot may not always work that way.
        * Is this a blocker? I'm not sure - if it thinks it's html but isn't, then it "squishes" the text. It might be that it's an improvement most of the time, so is still better overall.
        * Out of scope but then I noticed a preexisting issue where the tpl doesn't really properly handle the output if it is actually text but contains angle brackets. It's not necessarily a security issue, but isn't correct.
    * [`r-maint`] __Ok__
    * [`r-test`] __PASS__

**Comment by larssandergreen** [comment]
Thanks Dave! I appreciate this, I've certainly learned some things. After looking into Activity.tpl versus ActivityView.tpl (here's the [code that chooses](https://github.com/civicrm/civicrm-core/blob/master/CRM/Activity/Selector/Activity.php#L154) which template to used based on the type), I thought of a much better way of doing this that covers all cases where Activities of type Email or Inbound Email are displayed. It didn't quite work out for Activity.tpl, but there's a reasonable workaround there (no issues if details is NULL).

Turns out that Activity.tpl handles Inbound Emails, Activities ActivityView.tpl handles Emails and Cases ActivityView.tpl handles both.

>     * `$defaults['details']` sometimes gives me undefined index. While it's maybe not common in real life to have an email activity with nothing in the body, one thing we've learned is if you let users do something then they will do it, especially ones named Dave. Apparently I have several of these in my database (both empty details and Dave's).

This is now handled in Activity ActivityView.tpl and is not an issue in the other two templates.

>     * The comparison with strip_tags is not foolproof, since there could be a text alternative stored that has text like `Hello <insert name>`. Since the output is ultimately the output from `{crmStripAlternatives}`, it made me look at the function that powers that (CRM_Utils_String::stripAlternatives), and then noticed that it just picks the "first one", so the strip_tags comparison might be wrong reasonably often (i.e. the output is ultimately text, but is_html_email will be true).
>       
>       * You might make an argument that this never comes up for activity type 3 (Email) because civi always stores the html first for those. But (a) Daves, and (b) extensions and imports and whatnot may not always work that way.
>       * Is this a blocker? I'm not sure - if it thinks it's html but isn't, then it "squishes" the text. It might be that it's an improvement most of the time, so is still better overall.

We're now only checking for tags in strings that have already been through crmStripAlternatives.

For the broader question of how to handle situations where there is something that looks like a tag that is going to be stripped in an otherwise text message, I feel like the rare text message without line breaks is much less bad than all the extra line breaks in every HTML message. It's 2022 and text-only email messages are rare and text-only email messages that have angle brackets that will get stripped are even rarer. We could try a more specific method using regex but that's a tradeoff of simplicity and maintainability versus maybe not adding some br tags to edge case text-only emails. If you think the balance here is different, I'm happy to add something like that.

Through testing, I think there are worse issues with text emails (for instance, if you edit an Inbound Email that is text, it will be converted to HTML without line breaks because you get a wysiwyg editor. But I think we shouldn't expend a lot of effort supporting text emails at this point - though if this seems important, it wouldn't be too much hassle to fix.

In Case ActivityView.tpl, we are handling more types than just the Email and Inbound Email types that we are handling in the other two templates. I've tested every Activity Type that is in the sample data and haven't seen any problems (though there are definitely other display issues for Cases that are pre-existing). I'm having a hard time imagining a situation where we would have HTML that we would want to add br tags to, but maybe you can.

>       * Out of scope but then I noticed a preexisting issue where the tpl doesn't really properly handle the output if it is actually text but contains angle brackets. It's not necessarily a security issue, but isn't correct.

What are you seeing? I've tried some angle brackets and they are looking correct to me, but if you have a specific example, I can take a look and see if we can fix this at the same time.

I've also fixed the array index issues that were coming up on Activity ActivityView.tpl, while I was in there.

**Comment by demeritcowboy** [comment]
Ah yes I said "try" so I was covered. I guess it meant "do not".

**Comment by demeritcowboy** [comment]
I did look at this the other today and also today. I will write up some thoughts in unit test format.

**Comment by larssandergreen** [comment]
@demeritcowboy If I should add some unit tests, happy to do that. I struggle to see what needs or should have tests in contexts like this.

**Comment by demeritcowboy** [comment]
I haven't got it all in a digestible format, but point-form:
* Underlying issue is details field can have a variety of single or mixed formats including a pseudo-mime format but doesn't have a fixed order but unlike real mime doesn't tell you the mimetype of each part.
  * We aren't trying to fix that here, but for example "copy sent to" activities for assignees are just text/plain, but have html in them. Just as an example.
* As a general rule there's "new features/functions need a unit test", but it's not just that it's that I have 2 (actually 3) matrices like this. I'm ignoring the 3rd one because I think it's a bug in civi that it even lets you get to those pages.

NOT CASE

  | Just html | Mixed with text first | Mixed with html first | Just text
-- | -- | -- | -- | --
Inbound   Email |   |   |   |
Email |   |   |   |   |
Bulk   Email |   |   |   |
Other |   |   |   |   |

CASE

  | Just html | Mixed with text first | Mixed with html first | Just text
-- | -- | -- | -- | --
Inbound   Email |   |   |   |
Email |   |   |   |   |
Bulk   Email |   |   |   |
Other |   |   |   |   |

There's also the fact that this feels like overkill, which I'm conscious of but I'm not sure yet if I agree that it's better to have some squished than to have extra spaces. I need to convince myself - because I remember it used to be that many things were unreadable because they ended up with no line breaks.

**Comment by larssandergreen** [comment]
Even more complicated than it first appeared.

Would it make sense to switch to actually storing full MIME format emails going forward, supporting both formats for backwards compatibility and not worrying too much about the details of how the older emails display? That would also cover the BCC and CC, assuming we keep the headers in there. But that's a much larger change.

Otherwise, this doesn't touch bulk emails or other activity types for non-case activities. To be safe, I could add a check for case activities so that we're only changing email and inbound email types.

The cc and bcc cases could be handled in nl2brIfNotHTML by stripping them before comparing, but if there are other examples like this, that approach might get messy.

What's the third matrix?

**Comment by demeritcowboy** [comment]
Sorry I didn't answer. I can quickly answer the easy one:

> What's the third matrix?

There are places where civi will offer a link to case activities but using the regular activity form. I haven't checked lately but at one time if you edit and save with that form it leads to potential data loss. (Related: https://lab.civicrm.org/dev/core/-/issues/2509)

**Comment by demeritcowboy** [comment]
I see I said "this" weekend but I didn't specify which weekend "this" applied to so I'm still good.

Draft unit test is here: https://github.com/civicrm/civicrm-core/compare/master...demeritcowboy:civicrm-core:unittests-for-activity-newlines?expand=1

* The PR fixes `email-html` and all the case- ones.
* It fails `meeting-text` and `meeting-mixed-text` but they failed before too and are uncommon records in real life. For simplicity we can mark those skipped in the test for now.
* It fails the `bulk-email` ones.
* The test just needs to reconcile some irrelevant whitespace differences for `email-text` and `email-mixed-text`

**Comment by larssandergreen** [comment]
Finally got a chance to get back to this one, thanks again for all the work on this @demeritcowboy

I've tried running the tests (on master) and I'm getting 32 failures, which I think is all of them. Looks like the there are new lines (`\n`) on each line, so nothing matches. Do you get the same results?

**Comment by demeritcowboy** [comment]
I get 9 fails (with your PR applied). How are you downloading the test patch? Try curl'ing this url? https://github.com/civicrm/civicrm-core/compare/master...demeritcowboy:civicrm-core:unittests-for-activity-newlines.diff

**Comment by demeritcowboy** [comment]
Fortunately the test is in a file with the letter A, so we already have results, and yeah lots of fails and it seems to be a newline thing. I wonder if it's a windows difference? But that should matter for html pages. I'll take a look.

```
not ok 163 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "meeting-text" (array('Meeting', 'civicrm/activity?atype=%%atyp...tivity', 'This is text only\nand has tw... line.'), '<span class="crm-frozen-field...pan>\n')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 164 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "bulkemail-text" (array('Bulk Email', 'civicrm/activity/view?atype=%...tivity', 'This is text only\nand has tw... line.'), '<td class="label nowrap">Text...<br />')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 165 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "email-text" (array('Email', 'civicrm/activity/view?atype=%...tivity', 'This is text only\nand has tw... line.'), '<td class="view-value report"....</td>')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 166 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "inbound-text" (array('Inbound Email', 'civicrm/contact/view/activity...tivity', 'This is text only\nand has tw... line.'), '<span class="crm-frozen-field...pan>\n')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 167 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "meeting-html" (array('Meeting', 'civicrm/activity?atype=%%atyp...tivity', '<p>This is html only</p>\n\n<...s.</p>'), '<span class="crm-frozen-field...pan>\n')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 168 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "bulkemail-html" (array('Bulk Email', 'civicrm/activity/view?atype=%...tivity', '<p>This is html only</p>\n\n<...s.</p>'), '<td class="label nowrap">Text...<br />')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 169 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "email-html" (array('Email', 'civicrm/activity/view?atype=%...tivity', '<p>This is html only</p>\n\n<...s.</p>'), '<td class="view-value report"...></td>')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 170 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "inbound-html" (array('Inbound Email', 'civicrm/contact/view/activity...tivity', '<p>This is html only</p>\n\n<...s.</p>'), '<span class="crm-frozen-field...pan>\n')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 171 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "meeting-mixed-text" (array('Meeting', 'civicrm/activity?atype=%%atyp...tivity', '-ALTERNATIVE ITEM 0-\nThis is...E END-'), 'This is mixed<br />\r\nand ha... line.')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 172 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "bulkemail-mixed-text" (array('Bulk Email', 'civicrm/activity/view?atype=%...tivity', '-ALTERNATIVE ITEM 0-\nThis is...E END-'), '<td class="label nowrap">Text...<br />')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 173 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "email-mixed-text" (array('Email', 'civicrm/activity/view?atype=%...tivity', '-ALTERNATIVE ITEM 0-\nThis is...E END-'), '<td class="view-value report"...n</td>')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 174 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "inbound-mixed-text" (array('Inbound Email', 'civicrm/contact/view/activity...tivity', '-ALTERNATIVE ITEM 0-\nThis is...E END-'), '<td class="view-value">\n    ...<br />')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 175 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "meeting-mixed-html" (array('Meeting', 'civicrm/activity?atype=%%atyp...tivity', '-ALTERNATIVE ITEM 0-\n<p>This...E END-'), '<td class="view-value">\n    ...e.</p>')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 176 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "bulkemail-mixed-html" (array('Bulk Email', 'civicrm/activity/view?atype=%...tivity', '-ALTERNATIVE ITEM 0-\n<p>This...E END-'), '<td class="label nowrap">Text...<br />')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 177 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "email-mixed-html" (array('Email', 'civicrm/activity/view?atype=%...tivity', '-ALTERNATIVE ITEM 0-\n<p>This...E END-'), '<p>This is mixed<br />\r\nand...e.</p>')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 178 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "inbound-mixed-html" (array('Inbound Email', 'civicrm/contact/view/activity...tivity', '-ALTERNATIVE ITEM 0-\n<p>This...E END-'), '<p>This is mixed<br />\r\nand...e.</p>')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 179 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "case-meeting-text" (array('Meeting', 'civicrm/case/activity/view?re...seid%%', 'This is text only\nand has tw... line.'), 'This is text only<br />\r\nan... line.')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 180 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "case-bulkemail-text" (array('Bulk Email', 'civicrm/case/activity/view?re...seid%%', 'This is text only\nand has tw... line.'), 'This is text only<br />\r\nan... line.')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 181 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "case-email-text" (array('Email', 'civicrm/case/activity/view?re...seid%%', 'This is text only\nand has tw... line.'), 'This is text only<br />\r\nan... line.')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 182 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "case-inbound-text" (array('Inbound Email', 'civicrm/case/activity/view?re...seid%%', 'This is text only\nand has tw... line.'), 'This is text only<br />\r\nan... line.')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 183 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "case-meeting-html" (array('Meeting', 'civicrm/case/activity/view?re...seid%%', '<p>This is html only</p>\n\n<...s.</p>'), '<p>This is html only</p>\r\n\...s.</p>')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 184 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "case-bulkemail-html" (array('Bulk Email', 'civicrm/case/activity/view?re...seid%%', '<p>This is html only</p>\n\n<...s.</p>'), '<p>This is html only</p>\r\n\...s.</p>')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 185 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "case-email-html" (array('Email', 'civicrm/case/activity/view?re...seid%%', '<p>This is html only</p>\n\n<...s.</p>'), '<p>This is html only</p>\r\n\...s.</p>')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 186 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "case-inbound-html" (array('Inbound Email', 'civicrm/case/activity/view?re...seid%%', '<p>This is html only</p>\n\n<...s.</p>'), '<p>This is html only</p>\r\n\...s.</p>')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 187 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "case-meeting-mixed-text" (array('Meeting', 'civicrm/case/activity/view?re...seid%%', '-ALTERNATIVE ITEM 0-\nThis is...E END-'), 'This is mixed<br />\r\nand ha... line.')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 188 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "case-bulkemail-mixed-text" (array('Bulk Email', 'civicrm/case/activity/view?re...seid%%', '-ALTERNATIVE ITEM 0-\nThis is...E END-'), 'This is mixed<br />\r\nand ha... line.')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 189 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "case-email-mixed-text" (array('Email', 'civicrm/case/activity/view?re...seid%%', '-ALTERNATIVE ITEM 0-\nThis is...E END-'), 'This is mixed<br />\r\nand ha... line.')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 190 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "case-inbound-mixed-text" (array('Inbound Email', 'civicrm/case/activity/view?re...seid%%', '-ALTERNATIVE ITEM 0-\nThis is...E END-'), 'This is mixed<br />\r\nand ha... line.')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 191 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "case-meeting-mixed-html" (array('Meeting', 'civicrm/case/activity/view?re...seid%%', '-ALTERNATIVE ITEM 0-\n<p>This...E END-'), '<p>This is mixed<br />\r\nand...e.</p>')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 192 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "case-bulkemail-mixed-html" (array('Bulk Email', 'civicrm/case/activity/view?re...seid%%', '-ALTERNATIVE ITEM 0-\n<p>This...E END-'), '<p>This is mixed<br />\r\nand...e.</p>')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 193 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "case-email-mixed-html" (array('Email', 'civicrm/case/activity/view?re...seid%%', '-ALTERNATIVE ITEM 0-\n<p>This...E END-'), '<p>This is mixed<br />\r\nand...e.</p>')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
  not ok 194 - Failure: CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "case-inbound-mixed-html" (array('Inbound Email', 'civicrm/case/activity/view?re...seid%%', '-ALTERNATIVE ITEM 0-\n<p>This...E END-'), '<p>This is mixed<br />\r\nand...e.</p>')
  ---
  message: Failed asserting that '\n
  severity: fail
  ...
```

**Comment by larssandergreen** [comment]
Yes, that's the same failures as I'm getting locally. The HTML output from the test has newlines in it.

**Comment by demeritcowboy** [comment]
It seems to be a difference between `|purify` on windows and linux. I've never noticed this before but it adds in a chr(13) on windows. You can see this with e.g. `cv ev "echo CRM_Utils_String::purifyHTML('a' . chr(10) . 'b');" | od -c`:

Linux: `0000000   a  \n   b  \n`
Windows: `0000000   a  \r  \n   b  \r  \n`

While my preference would be that it not do that on windows, I'll just update the test.

**Comment by larssandergreen** [comment]
Huh, that is kind of wild. Agreed that just stripping out the non-HTML line breaks sounds like the most robust approach.

**Comment by larssandergreen** [comment]
Thanks. The failures I'm seeing for the bulk-xxx tests are looking for `<td class="label nowrap">Text Message</td><td>This<br />address<br /><br />is not ours:...<br />` but I think they should actually be looking for `This is mixed...` or `This is html only...` and so on. The text message thing doesn't appear anywhere in the bulk messages.

**Comment by demeritcowboy** [comment]
Look at the comment in the test, or view a bulk email on a site before the patch. The text is supposed to be a summary of the mailing body.

**Comment by larssandergreen** [comment]
Gotcha, not actually a line break problem, it was something else, now fixed. Looks like all the new tests have passed, so unless something else has gone wrong, I think we're good here!

**Comment by demeritcowboy** [comment]
Woohoo! Yeah we should probably merge it before something else happens. Normally I'd ask to rebase out that giant merge commit but let's not jinx it.

I think there was some discussion already about "it's plain text but it contains html", like the send-copy-to on case activities. Those are squished now but the problem there is the storage itself, and I'm not sure how often people actually open those, it's more about having the record.

**Comment by larssandergreen** [comment]
Great! Thanks for doing the heavy-lifting here with the tests.

How naive I was to think this one would be a quick fix.

**Pull request merged**
