### PR TITLE
Add unique names to contact.created_date, modified_date

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Add unique names to contact.created_date, modified_date

Before
----------------------------------------
No unique names

After
----------------------------------------
unique names

Technical Details
----------------------------------------
Preparatory to converting log_date in advanced search to datepicker

Comments
----------------------------------------
@seamuslee001 we probably want to do this before looking at making the change

### CODE REVIEW

**Comment by seamuslee001** [comment]
will this impact triggers at all?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 no - they don't use unique_names - they use the database name

**Comment by seamuslee001** [comment]
adding merge on pass looks ok to me

**Comment by eileenmcnaughton** [comment]
@seamuslee001 based on the test fails I'm thinking to leave this & just use the non-unique names - after all contact table is the boss

**Comment by seamuslee001** [comment]
sounds ok to me

**Pull request closed without merging**
