### PR TITLE
CRM-20620, optimized code to use Batch api

### PR DESCRIPTION
**Pull request by pradpnayak**
----------------------------------------
* CRM-20620: Use batch api to retrieve all the batches
  https://issues.civicrm.org/jira/browse/CRM-20620

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I haven't read in detail but based on a quick skim read this looks like a code improvement - good work

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by pradpnayak** [comment]
Jenkins test this please

**Pull request merged**
