### PR TITLE
CRM-10414 CRM-5946 Use composer to manage pear Mail and apply patches…

### PR DESCRIPTION
**Pull request by seamuslee001**
… for CiviCRM to fix CRM-10414 CRM-5946

Overview
----------------------------------------
This applies the fixes for CRM-5946 and CRM-10414 but uses composer to manage pear Mail

Before
----------------------------------------
pear mail manually managed 

After
----------------------------------------
pear mail composered managed

Technical Details
----------------------------------------
Following the composer version the following diff is produced https://gist.github.com/seamuslee001/78be8ccf141a268285ed0b08e1422236

### CODE REVIEW

**Comment by seamuslee001** [comment]
ping @lcdservices @monishdeb can one of you test this please, To Test you will need to apply patch run composer install and remove the files created by composer from packages

**Comment by eileenmcnaughton** [comment]
This bug may also be affected 
https://issues.civicrm.org/jira/browse/CRM-20228?jql=text%20~%20%22swiftmailer%22

**Comment by seamuslee001** [comment]
I'm not sure there is anything in this that would alter that issue

**Comment by eileenmcnaughton** [comment]
ok

**Comment by totten** [comment]
In general, `composer` is better for dependency-management.

From a QA/review perspective, I think this would ideally be merged after a reviewer:
 1. Double-checks the list original differences (wherein `packages/PEAR/Mail` deviated from upstream)
 2. Reviews the new diff  (`packages/PEAR/Mail` vs `vendor/pear/mail`) for changes that might be substantive.
 3. Does some manual test which involves actually composing+delivering an actual message (through whatever UI in Civi calls PEAR_Mail).

**Comment by seamuslee001** [comment]
@totten one of the things and something which you may notice in this PR is because i did composer update on a system > php5.3 it pulled in later versions of Symphony which aren't able on 5.3 (yes i know we are about to kill it) but just a small catch

**Comment by eileenmcnaughton** [comment]
@seamuslee001 perhaps it makes sense to delay until we have dropped 5.3?

**Comment by seamuslee001** [comment]
@eileenmcnaughton The mail package is PHP5.3 compliant the issue is that when you run `composer update` it will update to whatever is the latest available package "Your" system supports and given we are accepting both Symphony 2.6.x and 3.3.x i think it said ok i'm going to update you to 3.3.x, which then broke on the first test run because it sets that version in the composer.lock. But reverting the symphony changes in composer.lock then allowed it to pass jenkins because Jenkins just runs `composer install` which just installs whatever versions have been specified in composer.lock.

**Comment by eileenmcnaughton** [comment]
I'm going to close this because it's stale & let you re-open when ready. I do have one issue re substance which @totten can opine on. There are 2 options for managing over-the-top patches
1) as you have done
2) having our own fork of the composer repo (this involves intermittent cutting of branches that rebase)

We have done a bit of the latter but not sure it's appropriate here

**Pull request closed without merging**
