### PR TITLE
CRM-20689 - Fix missing handling in upgrade for is_public in multi-li…

### PR DESCRIPTION
**Pull request by yashodha**
…ngual installs

### CODE REVIEW

**Comment by yashodha** [comment]
@jitendrapurohit seems to be missing from https://github.com/civicrm/civicrm-core/pull/10028

**Comment by yashodha** [comment]
test this please

**Comment by yashodha** [comment]
probably should be part of 4.7.20-rc
@jitendrapurohit  Can you please confirm

**Comment by jitendrapurohit** [comment]
should be already included - see https://github.com/civicrm/civicrm-core/pull/10399

**Comment by seamuslee001** [comment]
Agreed ping @totten @colemanw

**Comment by seamuslee001** [comment]
Just agreeing that it should already be covered in the addColumn function which makes more sense there.

**Comment by yashodha** [comment]
I encountered this for 4.7.19, didn't know this has already been fixed for 4.7,20

**Pull request closed without merging**
