### PR TITLE
CRM-19256: Add permission hook

### PR DESCRIPTION
**Pull request by nganivet**
Full implementation for the hook. Has been tested through the org.civicrm.multisite extension.

---
- [CRM-19256: Add a hook to dynamically escalate permissions](https://issues.civicrm.org/jira/browse/CRM-19256)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@nganivet This looks good, I also wonder about whether to chuck it in line 164 as well in the check any perm function as well just for completeness

**Comment by nganivet** [comment]
@seamus - line 164 calls CRM_Core_Permission::check(), which is where we inserted the hook, so the hook will be called when using the function CRM_Core_Permission::checkAnyPerm().

**Comment by totten** [comment]
Some data points... when building the user's navigation menu (`civicrm/ajax/menujs`), this increases the hook count from 10 to 387:

https://gist.github.com/totten/e85bc8f6129c19fd9135fb7f1a78f8c9

When rendering the "Edit Contact" form (`civicrm/contact/add`), this increases the hook count from 460 to 497:

https://gist.github.com/totten/bbeddd067621c1bc59d05eae8c4bb58c

**Comment by nganivet** [comment]
Not sure if you're implying this is an an issue. If so, here are a few 
counter-arguments:

- hook are supposed to be efficient: Drupal and WordPress make extensive 
use of hooks and I never heard they led to performance issues. If they 
do in CiviCRM then we should optimize code by for example caching the 
list of functions triggered by each hook invocation (if not already 
done)

- we're adding 377 hook invocations when building the menus, which 
happens rarely in CiviCRM (upon login and manual trigger) and is cached 
in the database,

- we're adding 37 hooks invocations on a much used function, but that 
represents only 8% of the hook invocations already done anyways

--Nicolas.

------ Original Message ------

**Comment by JoeMurray** [comment]
jenkins, please test

**Comment by JoeMurray** [comment]
does this need rebasing, @nganivet ?

**Comment by nganivet** [comment]
@JoeMurray github says no conflicts with base branch, so I guess not.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by alifrumin** [comment]
Jenkins re test this please

**Comment by agh1** [comment]
Jenkins, retest this please.

**Comment by alifrumin** [comment]
seems like this test failure has nothing to do with this code

**Comment by hoegrammer** [comment]
Been using this in prod for a few weeks and it's working great.

**Comment by hoegrammer** [comment]
Been using this in prod for a couple weeks and it's working great.

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Pull request merged**
