### PR TITLE
dev/core#2231 - Fix failure to calculate next_scheduled_date

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fixes a bug where the completeOrder flow was not setting the next scheduled date on recurrings. This is important for processors who rely on that date for billing ie
- IATS (confirmed affected)
- Omnipay (unconfirmed, likely)
- Stripe (unconfirmed, less likely)
- Eway (unconfirmed, less likely)

This bug affects recurring contribution series initiated on civicrm 5.29 or later

Before
----------------------------------------
0 (1970-00-00) stored as the next scheduled contribution date - confirmed in back office recurring data entry + add Payment flow

After
----------------------------------------
correct date calculated.

Technical Details
----------------------------------------
Regression arose from a reviewer's commit where I tried to meld 2 prs together but git-fu-d a line in from 1 that should not have been included.  It resulted in no date being calculated when receive_date is unset - this is in the completeOrder flow. I have since put a test against master that would have prevented this

Comments
----------------------------------------

### CODE REVIEW

**Comment by KarinG** [comment]
Checks haven't completed yet - but it has been tested!

Before:
image

After: this PR fixes the issue -> Next Scheduled Date is set correctly:
image

**Comment by mattwire** [comment]
@karing @eileen It's been NULL for at least 4 years... and it was only changes in 5.31 not 5.29 where the issue starts to occur - are we sure that's really the cause of the issue?

@seamuslee001 removing merge on pass pending investigation per comment above - feel free to add back if you are convinced this is the cause of the issue.

**Comment by eileenmcnaughton** [comment]
@mattwire the issue is completeOrder is not updating correctly when payment is received - this is the offending line

https://github.com/civicrm/civicrm-core/commit/605665c7a3c4804ba8f453341763ffd74a0d48b9#diff-c886eb445f1cc2f7c23d798c1d2357637a2e5349381057e6074c24a9c7dd1fbcL838

**Comment by mattwire** [comment]
Error was introduced via https://github.com/civicrm/civicrm-core/pull/17744

**Comment by eileenmcnaughton** [comment]
PR with test fixes https://github.com/civicrm/civicrm-core/pull/19122

@mattwire do you want to re-add MOP label?

**Comment by seamuslee001** [comment]
re-adding MOP based on https://chat.civicrm.org/civicrm/pl/8m4kz7syw3dhiq67e841qbkfph

**Comment by eileenmcnaughton** [comment]
Since the fix is in 5.32 one quick thing we can do is tell people how to use search kit to bulk update them should they wish to (search kit is unhidden but not-installed-by-default in 5.32 I believe). I would note 5.33 should be a big jump on 5.32 so people should probably not play too much on the 5.32 version

Use search kit to fix the next scheduled date2020-12-05 16-06

**Comment by KarinG** [comment]
If we get any reports of iATS clients affected by this - they could go to the iATS Payments Recurring Contributions report -> and Sort that Report by Next Scheduled Date
/civicrm/report/com.iatspayments.com/recur?reset=1
Any 1970s will float to the top / will be easily visible.

If there are just a few I would recommend people just Navigate to that Contact's Recurring Series and hit Edit on the Recurring Series to update Next Scheduled Date -> as it needs to be calculated per Series. 

If there are lots a small drush script that will grab the data (last successful completed contribution in that series + interval information) to calculate the Next Scheduled Date and update the civicrm_contribution_recur table directly.

**Comment by eileenmcnaughton** [comment]
Yeah - I suspect - but didn't check - extended reports might have something too. I thought I'd be able to share the url for the above search + criteria which would be easy - but then of course I had a wordpress url & that is not that shareable after all

**Comment by herbdool** [comment]
I ended up just searching directly in the db. At first I threw caution to the wind and enabled SearchKit to try the above but ended up in a bit of pain. SearchKit enabled okay but the icons were all messed up. So I thought perhaps it is dependent on one of the other extensions? (I can't recall if extensions can be prevented from installing if the dependent isn't enabled first) So I enabled Afform Core and that broke the site with some Uncaught errors (couldn't find classes). Anyway, I don't want to make this a bug issue but just to flag my experience with SearchKit thus far.

**Comment by eileenmcnaughton** [comment]
Hmm - it doesn't depend on afform - what theme do you have @colemanw

**Pull request merged**
