### PR TITLE
Allow searchkit joins via EntityRef fields in multivalue custom data

### PR DESCRIPTION
**Pull request by michaelmcandrew**
Overview
----------------------------------------
Building on the following recent developments...

1. we now have a generic entity reference field
2. we now allow multi-value value custom data on any entity

... and with the intention of being able to model arbitrary many to many relationships in CiviCRM.

This PR surfaces joins in SearchKit via entity reference custom fields.

Before
----------------------------------------

Given an entity X, and a 'multi-value custom data entity' Y that has a entity reference field referencing X, users were not able to 

- join from X to Y via the entity reference field
- join from Y to X via the entity reference field

After
----------------------------------------

Given the same scenario, users are able to do both things.

Technical Details
----------------------------------------
The PR works for me in my tests locally but there are some things I am not sure of:

1. whether I should have thought of the multi-value custom data as a bridge entity (I don't think it is necessary or adds much but happy to be corrected on that.
2. appropriate values for `bridge`, `conditions` , `defaults` and `multi` in the join definitions that I am creating.

I factored out the entity reference join code that already existed for single value custom data into a seperate function which we are now also calling from multi-value custom data entities.

PS. I have a demo site set up with this code which I can give you access to if that would help anyone with getting their head around it or any testing.

### CODE REVIEW

**Comment by colemanw** [comment]
@michaelmcandrew thanks for starting this. I wanted to do further refactoring of the function but didn't feel like it had enough test coverage to do so, so I added a few tests and then reorganized the function a bit. The upshot is now we consistently add both sides of the join for all entity reference fields whether they belong to multi-record groups or not.

I'm happy with this test-wise but it would be really helpful if you could `r-run` this and report back.

**Comment by michaelmcandrew** [comment]
Thanks @colemanw - I tested this new file on my local test server running 5.58.0 and it worked as expected. I was able to join via the multi-value custom field entity reference fields. The 'with' joins appeared as expected and I was able to select fields from all entities and the results appeared as expected too.

Thanks for your help with this.

**Comment by adixon** [comment]
Based on a review of the PR and description above, it looks like a multivalue custom fieldset that doesn't include an entity reference is still not going to get the join showing. Or am I missing something? Is a multivalue custom fieldset considered an entity reference here in some way?

**Comment by colemanw** [comment]
@adixon it's only very *very* recently that people have been experimenting with multivalue custom fieldsets on any entity other than Contact. For over a decade it's been limited to Contact-only. I recently made changes to the schema which lift that limitation, but as you note, it's an opt-in. You can probably make the change yourself using [`hook_civicrm_fieldOptions`](https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_fieldOptions/)

**Comment by adixon** [comment]
Thanks, that's helpful. Re: how to make the change, it looks like hook_civicrm_fieldOptions is only about fields, this is a fieldset issue, right? Or in fact, the change I'm making is actually a kind of entity configuration change, not specifically a field or a fieldset property. For a custom entity, there's a managed entity thing to set that configuration (using the cg_extends_objects option group), but for a built-in entity, they look hard-coded with no override option. Am I missing something or is this a PR-welcome kind of situation? I could easily imagine some code that would provide an override opportunity in the existing option group "cg_extend_objects" (currently, if I add e.g. Activities to that option list, it adds it as a duplicate instead of replacement!)

**Comment by adixon** [comment]
Tested by backporting to my civicrm 5.78.4 live site. Confirmed that it didn't enable ability to create multiple record custom fieldset on it's own. Confirmed that it did allow creating mlitple record custom fieldsets by adding a option value (with filter = 1) for Activities.

**Pull request merged**
