### PR TITLE
CRM-21225 Allow for display profile alternate - schema changes only

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
this picks up just the schema changes from https://github.com/civicrm/civicrm-core/pull/11370/files this is in the hope to try to get this part merged through 

Before
----------------------------------------
No diplay_title column on civicrm_uf_group

After
----------------------------------------
display_title added

ping @eileenmcnaughton @agileware @JoeMurray

---

 * [CRM-21225: CIVICRM-506 Add a new field, Profile Title so that the Profile Name does not serve a dual purpose of labelling the Profile and displaying the Title for the Profile fields publicly](https://issues.civicrm.org/jira/browse/CRM-21225)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This seems good to me - do we have a precedent anywhere for naming conventions for front end title fields vs back office title fields?

**Comment by seamuslee001** [comment]
@eileenmcnaughton @totten @jusfreeman I have now renamed the column frontend_title as per discussion on MM. I'll work on the main code once the schema change has been merged

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
We discussed this in chat. The situation is that there is a need for 3 'names'

a symbolic, unchanging machine name
a backend/administrative title (used to browse/select among profiles)
a frontend/page title (like the <h1> on a public page)

We have a standard of name for the first & title kinda covers 2 & 3. After discussion we preferred adding 'frontend_title' to display_title (display when?)

Happy with this change now - merge on pass - it could be extended to other entities like custom data group etc

**Comment by gah242s** [comment]
https://gist.github.com/gah242s/2fbebbb638b8a2065de9eeca7e2a989f
Here's a gist, also posted in MM.  Hopefully it's useful?

**Pull request merged**
