### PR TITLE
CRM-20347 Fatal error on delete participant record with related contr…

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
…ibution

@jitendrapurohit can you review this related issue? See if you think there is any issue with this change

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
shouldn't we add `VIEW` action here? Currently contribution section is not loaded in View Participant page after this change.

**Comment by eileenmcnaughton** [comment]
This is within the 'edit' function
```
  /**
   * called when action is update or new.
   *
   * @return null
   */
  public function edit() {
    // set https for offline cc transaction
    $mode = CRM_Utils_Request::retrieve('mode', 'String', $this);
    if ($mode == 'test' || $mode == 'live') {
      CRM_Utils_System::redirectToSSL();
    }
```

called per

```

    if ($this->_action & CRM_Core_Action::VIEW) {
      $this->view();
    }
    elseif ($this->_action & (CRM_Core_Action::UPDATE |
        CRM_Core_Action::ADD |
        CRM_Core_Action::DELETE
      )
    ) {
      $this->edit();
    }
    else {
      $this->browse();
    }
```

I do wonder if it is possible to load that contribution search results by snippet - which would be much better from a code POV I think

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit @pradpnayak - per suggestion from @pradpnayak on the other JIRA (or somewhere) - this works & since I had hit the same error in a third place (contact user dashboard) I think I'd rather fix it this way, although longer term it would be better to have actions on all forms that reflect their 'gettiness' I think

**Comment by eileenmcnaughton** [comment]
I'm going to set this to 'merge on pass' since it is a fatal in the rc so should be fixed ASAP & is a fix suggested by @pradpnayak - so I am effectively the reviewer on it

**Pull request merged**
