### PR TITLE
Profiles with multi record fields - email and receipts use older values than latest

### PR DESCRIPTION
**Pull request by mountev**
Overview
----------------------------------------
When using a profile with multi record fields for notification or on-behalf-of profile - emails and receipts end up showing oldest (first row of custom table) set of values than the latest submitted ones.

Before
----------------------------------------
image

image

After
----------------------------------------
image

Technical Details
----------------------------------------
CRM_Core_BAO_UFGroup::getValues() uses search query with left joins with multi custom set tables, which won't fetch the latest record for multi record custom set fields. And changing core search query to use sub queries for multi set records is quite a big change and effort. Unless anyone already knows how to do it.

As an alternative - have added a new method to update $values populated by CRM_Core_BAO_UFGroup::getValues() with latest multi record values. The new method is based on CRM_Core_BAO_CustomValueTable::getEntityValues() which is used to display multi record values in contact tab (as a table). The trick used here is that it fetches only the latest record.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@lcdservices where did we get with this? I know there was a fundamental issue that the model doesn't actually imply 'latest is current' so it's not clear what value we 'should' show - but I think you were pushing for latest too.

We would definitely want a unit test to merge this @mountev have you worked with unit tests with Civi before?

**Comment by lcdservices** [comment]
@eileenmcnaughton -- I worked with @mountev on this. And yes, I was pushing for latest. In the context of a profile submission form, I believe this is safe. So not so much pushing -- but believing this is a valid assumption. We can work on a unit test.

**Comment by mountev** [comment]
@eileenmcnaughton have added a test case. Let me know if that's ok or need any amends.

**Comment by yashodha** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
We discussed on pr review call & came down as 'concept approved' on this per @Stoob @MegaphoneJon

**Comment by eileenmcnaughton** [comment]
this needs rebasing though :-(

**Comment by eileenmcnaughton** [comment]
@mountev the test fail relates

**Comment by mountev** [comment]
On v5.16 CRM_Core_BAO_UFGroup::getValues() is returning the latest values which is failing the test case. And without our changes i can see emails fetching the latest values.

**Comment by mountev** [comment]
This PR could be closed. Need to dig in to check what changed in core as CRM_Core_BAO_UFGroup::getValues() is now returning latest, unless someone already knows. Thanks.

**Comment by eileenmcnaughton** [comment]
@mountev OK - I'll close -maybe another PR got merged at some point

**Pull request closed without merging**
