### PR TITLE
Duplicate upgrade step for 5.7.beta1 in 5.8.alpha1 to capture anyone …

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @eileenmcnaughton @colemanw

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 isn't 5.7 the rc? In which case the upgrade script was merged to 5.7 in time for release?

**Comment by seamuslee001** [comment]
@eileenmcnaughton yes but what if someone has already downloaded the 5.7 RC tarball sometime in the last month and upgraded? their db version will be 5.7.beta1 with the old icons

**Comment by eileenmcnaughton** [comment]
@seamuslee001 OK - I would say we don't really cater to that but OTOH I can't see this does any harm!

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Merging as per the tag

**Pull request merged**
