### PR TITLE
CRM-20146 dont hardcode check_number toggle in .tpl

### PR DESCRIPTION
**Pull request by lcdservices**
* [CRM-20146: check_number toggle: don't hardcode value](https://issues.civicrm.org/jira/browse/CRM-20146)

### CODE REVIEW

**Review by JoeMurray — COMMENTED** [review]
This is very useful code quality improvement.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
Yeah - it is better - although that whole chunk of code looks like it is legacy - I'd be happy to merge it if someone confirms it works

**Comment by yashodha** [comment]
@lcdservices I tested this and this fails for on change of "Payment Method" (changed the check_number vaule)

You might want to remove hard-coded value here as well
https://github.com/civicrm/civicrm-core/blob/master/CRM/Contribute/Form/Contribution.php#L655

**Comment by eileenmcnaughton** [comment]
@yashodha looks like it's ready for you to recheck & hopefully merge

**Comment by yashodha** [comment]
@eileenmcnaughton tested works fine

**Pull request merged**
