### PR TITLE
Applies accessible accordion to extension table 

### PR DESCRIPTION
**Pull request by vingle**
Overview
----------------------------------------
While this screen will one day be replaced with a SearchKit/FormBuilder output, for now that can't happen, and the expand accordion isn't keyboard controllable or accessible. This PR address this using the `<details><summary>` pattern, and removes the old JS. 

Before
----------------------------------------
Extensions table and 'add new' tab tablet isn't keyboard controllable / accessible

After
----------------------------------------
They are:
image

Technical Details
----------------------------------------
As well as removing the inline JS for the expand function, this PR changes the table output to have one row per extension, not two (which might help with responsive table CSS/JS).

Technical Details
----------------------------------------
The Summary heading is bold by default. This PR applies a new utility class `crm-accordion-light` to the `<details>` to remove bold styling (and preserve the lighter second line) - but that in itself does nothing. This class will be defined in a separate PR to civicrm.css coming shortly - without that css change this PR will look like this:

image

### CODE REVIEW

**Comment by aydun** [comment]
Test this please

**Comment by aydun** [comment]
Keyboard nav works ok.

The font sizes for the different fields vary so status, version, type, link fields are different to the first column:
image

Also, it's not showing on the 'Add new' tab.  Would be good to keep these similar.
image

It's good to see this becoming more standard!

**Comment by vingle** [comment]
> Also, it's not showing on the 'Add new' tab. Would be good to keep these similar.

Whoops! Forgot that! 

The size issue I'm a bit torn on the best way to handle. The Summary everywhere in civi now is 16px/1rem font size - a [widely](https://designnotes.blog.gov.uk/2022/12/12/making-the-gov-uk-frontend-typography-scale-more-accessible/) [recommended](https://accessibility.digital.gov/visual-design/typography/#:~:text=Use%20a%20large%20enough%20font,length%20that%20promotes%20comfortable%20reading.) accessible size. It is the same elsewhere unless overwritten. However here I agree it stands out as the other cells are 13px. 

Making the rest of the table 16px is a visual jump / outside scope / where does it end - but add something to civicrm.css that all themes will have to follow also isn't great. Using a utility class also isn't great. There's also the issue that JQuery UI is loading the font Verdana just for the table cells - it would be nice to reset that so it uses whatever font the theme has chosen. Welcome other thoughts on this.. cc @artfulrobot.

**Comment by vingle** [comment]
@aydun - thanks for your test, have fixed the bigger issue just now.

As for the size issue - my instinct is to make the summary match the rest of the table at 0.9rem for now as it's closest to what it was before in Greenwich - and it's really up to themes to resize things.

**Comment by vingle** [comment]
Have changed the font-size to inherit from the table its in, to both match the size it was before here, and remove the visual dissonance of different sizes in adjacent table cells. Now looks like this:

image

**Comment by aydun** [comment]
Thanks @vingle - It's now applied to Add as well, but the font sizes still look different on the test site to your screenshot:
image

Is there another update that didn't make it into the commit?

**Comment by vingle** [comment]
@aydun you're completely right, there was an extra line. It's been a long week! Thanks for the perseverance.

**Comment by colemanw** [comment]
Thanks @vingle and @aydun for your work on this. I've `r-run` and checked the code - all good!

**Comment by christianwach** [comment]
Just wanted to say yay to @vingle and @aydun for this - not only adds accessibility but also fixes that weird thing where you sort by Extension name and the discovery tabs stop working 🤦 

Would be nigh on perfect if the Extensions could be listed alphabetically by default but this is a significant improvement!

**Pull request merged**
