### PR TITLE
dev/core#5106 - Fix visibility of afforms & saved searches for disabled components

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes crash when enabling AdminUI extension without all components enabled.

Before
----------------------------------------
See description in https://lab.civicrm.org/dev/core/-/issues/5106

After
----------------------------------------
Works with or without all components enabled.

Technical Details
----------------------------------------
This takes a multi-pronged approach to the problem, since the tab consists of a search display *and* an afform, I fixed both, using different approaches:

- Added a conditional component check to the saved searches.
- Fixed permission checks to the afforms so that a permission to a disabled component (e.g. "Access CiviMember") would always be denied, even for super-admins).
- Fixed a bug in the permission system which misreported disabled components as enabled
- Fixed Afform-core to actually check permissions when loading contact summary tabs

### CODE REVIEW

**Comment by francescbassas** [comment]
I disabled members component on test site with Admin UI enabled, and contact summary is not crashing. Instead, on dmaster if I disable members component with Admin UI enabled I get this error on contact summary 

imatge

Then this PR fix crash for this case.

**Comment by colemanw** [comment]
@francescbassas just to clarify, you are saying this PR *does* fix the bug?

**Comment by francescbassas** [comment]
Yes

**Comment by totten** [comment]
Side note: on MM, Coleman [commented](https://chat.civicrm.org/civicrm/pl/ewnx6m34difjixecfiz1h4t4ta): "The big systemic change that 29828 makes is to always deny permissions that don't exist, even to super-admins."

Just verbalizing some notes about this:

* The situation of "checking permission for a permission that doesn't exist" is the kind of funny edge-case. Sort of conceptually non-deterministic. But between "undefined=>allow" and "undefined=>deny", the "undefined=>deny" sounds better.
* The kind of thing that might be impacted would be... like a small/custom extension which has a typo in a permission-check or neglects to declare permissions. Those would be pre-existing bugs that could be unnoticed/asymptomatic (if you have "undefined=>allow" and if security-configuration is pretty flat). But either way, the premise shows an underlying bug which we don't need to support.
* I'd be hesitant about changing that behavior in a `PATCH` release. But 5.72 isn't released yet, and it seems fair for a monthly update.
* If there's a CMS-level thing which does wildcard permissions (like Drupal `uid=0` or `adminrole.module`), then it affects testing this behavior. But it should be separate/unchanged.

---

Anyway, based on  @francescbassas testing it appears to work. And the testbot is happy. Merging.

**Comment by agileware-justin** [comment]
Checked and confirmed all good on CiviCRM 5.72.1

Thanks @colemanw 👍🏻

**Pull request merged**
