### PR TITLE
Token Parser - Allow tokens with multiple dots (eg {contribution.contribution_recur_id.amount})

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------

Adjust the naming/parsing rules for Civi-style tokens. Tokens may include dots and colons

```
{contribution.campaign_id}
{contribution.campaign_id.name}
{contribution.campaign_id.title}
{contribution.campaign_id:name}
{contribution.campaign_id:label}
```

(*Patch extracted from larger work on specific tokens. Description rewritten to focus on the change to the parser.*)

Before
----------------------------------------

Civi tokens may look like: `{foo.bar}`, `{foo.bar:whiz}` (*recent addition*)

After
----------------------------------------

Civi tokens may look like: `{foo.bar}`, `{foo.bar:whiz}`, and `{foo.bar.whiz}` (*new here*)

Comment
----------------------------------------

Civi supports a hybrid Token-Smarty notation. Any changes in the token-notation require some thought on the interaction with Smarty notations. Fortunately, this change seems consistent with existing dividing line -- these distinctions are still valid:

* Civi tokens do not have a dollar-sign (*distinguishes token `{foo.bar}` and Smarty `{$foo.bar}`, a value expression*)
* Civi tokens do not have spaces (*distinguishes token `{foo.bar}` and Smarty `{foo bar}`, a block with parameters*)
* Civi tokens have at least one dot (*distinguishes token `{foo.bar}` and Smarty `{fooBar}`, a block with no parameters*)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
now we have the no-prefetch pseudo plan we won't need this for campaign_id - but I've updated it to only the more permissive regex for now which we work through some of the remaining issues

**Comment by eileenmcnaughton** [comment]
@totten I'm OK with that I think - there is at least test cover of the token processor context in this PR now

**Comment by eileenmcnaughton** [comment]
@totten are you planning on re-writing the explain?

**Comment by totten** [comment]
@eileenmcnaughton Sure, I'll do that

**Comment by eileenmcnaughton** [comment]
@totten ok - go ahead & merge once you are happy with it

**Comment by eileenmcnaughton** [comment]
@totten since you updated the text to talk about smarty the thing I've been thinking about it this (pseudocode not real code)

```
$contact = new LazyLoadContact($knownVariables);
$this->assignByRef('contact', $contact)

```


```
class LazyLoadContact {
  public function offsetGet($var) {
    if ($var === 'my_special_field') {
       return 'here is your unicorn sir';
  }
}

```

& in smarty

`{$contact.my_special_field}`

```
 - would that output a unicorn

**Pull request merged**
