### PR TITLE
Fix deprecation notice on ExecuteJob screen

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fix deprecation notice on ExecuteJob screen

Before
----------------------------------------
image

After
----------------------------------------
image

Technical Details
----------------------------------------
As long as the api exists it can be easily switched over

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton the only potential gotcha in switching is that `BAO::retrieve()` fetches everything as a string from the db, whereas APIv4 casts types and unserializes arrays. As long as the entity doesn't have any serialized fields it ought to be safe. Otherwise some checking is needed to ensure the old code behaves.

**Comment by eileenmcnaughton** [comment]
@colemanw ah - seems we store `parameters` as line-break separated text. Worst of all worlds except the one where we want this PR to not break anything

I guess I should check the tpl does escapting though

**Comment by eileenmcnaughton** [comment]
@colemanw on further digging -we never use the retrieved values so I just blocked them being loaded! I added an escape to the template but I think it's not really a user value so it's more for 'good form' than to actually escape anything

**Comment by colemanw** [comment]
That works!

**Pull request merged**
