### PR TITLE
Add unit test to check CRM-20311

### PR DESCRIPTION
**Pull request by jitendrapurohit**
* [CRM-20311: Membership cancelation via contribution doesn't create membership status change activity](https://issues.civicrm.org/jira/browse/CRM-20311)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
added merge on pass as this is a test only commit

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
not obvious how the failure relates...

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit fail seems related - not sure why... Maybe cleaning up the loggedInUser within the test will help?

**Comment by jitendrapurohit** [comment]
@eileenmcnaughton Should pass the build now. Thanks:)

**Pull request merged**
