### PR TITLE
CRM-20329: Backend Membership with Payment set to Failed results in M…

### PR DESCRIPTION
**Pull request by jitendrapurohit**
…embership being set to New https://issues.civicrm.org/jira/browse/CRM-20329

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit this looks like the right fix ... wanna do a test - there should be something in CRM_Member_Form_MemberTest to use as a starting point.... ping me on chat if you need help

**Comment by jitendrapurohit** [comment]
@eileenmcnaughton Added Test

**Comment by jitendrapurohit** [comment]
@monishdeb Can you please review and merge this, seems to be a very minor change.

Thanks.

**Comment by monishdeb** [comment]
Tested working fine. Here's the screenshot showing on or before applying the patch. 
image
As you can see without patch, for Failed contribution Student Membership is set to new and after patch is applied I have created another Membership with failed payment and the membership status is changed to Pending which is expected in our case.

**Pull request merged**
