### PR TITLE
CRM-9764 Ensure all custom searches have ACL - Backport to 4.6

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Comment by seamuslee001** [comment]
I think this is fairly safe to be merged in, But is there anything i could do to get this moving?

**Comment by seamuslee001** [comment]
@davecivicrm I think this will fix the undefined notice errors that you found.

**Comment by davecivicrm** [comment]
Latest commit is throwing FATAL DB Syntax errors on 2 of the 3 searches I tested. Details in Jira issue.

**Comment by seamuslee001** [comment]
@davecivicrm I think my latest commit will fix those DB errors you found, I have tested on a 4.6.4 install and seems happy

**Comment by seamuslee001** [comment]
@davecivicrm I think this needs to be re-queued for testing as the errors were in the build phase not test phase

**Comment by davecivicrm** [comment]
Jenkins, test this please.

**Comment by seamuslee001** [comment]
@davecivicrm it seems to have failed again on the build.

**Comment by davecivicrm** [comment]
Seamus - I've asked Tim to look at it.

**Comment by seamuslee001** [comment]
Thanks Dave

**Comment by davecivicrm** [comment]
Prior failures from my testing are now corrected. Good to merge as soon as we get a successful PR test.

**Pull request merged**
