### PR TITLE
CRM-21502 When adding a new address to a contact, and switching location types at the same time, only one address is kept

### PR DESCRIPTION
**Pull request by sharmistharc**
Overview
----------------------------------------
_A brief description of the pull request. Try to keep it non-technical._

Before
----------------------------------------
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

After
----------------------------------------
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

Technical Details
----------------------------------------
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

---

 * [CRM-21502: When adding a new address to a contact, and switching location types at the same time, only one address is kept](https://issues.civicrm.org/jira/browse/CRM-21502)

### CODE REVIEW

**Comment by sharmistharc** [comment]
CRM-21502: When adding a new address to a contact, and switching location types at the same time, only one address is kept

**Comment by JoeMurray** [comment]
It would be better if the template were filled out. :(

**Comment by eileenmcnaughton** [comment]
Well done for tackling this! 

I'm not 100% sure what the 1 you are checking for refers to - probably it would need some code comments. But there are a few other hurdles here. I'll set Jenkins (our CI bot) going but I think you will hit some style errors - we use the drupal coding standards -
 https://www.drupal.org/docs/develop/standards/coding-standards

We would really want a unit test to go with this change but probably best to get existing unit tests & CI running on it first

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
You might find this helpful https://docs.civicrm.org/dev/en/latest/core/contributing/

**Comment by eileenmcnaughton** [comment]
closing as new PR opened for this

**Pull request closed without merging**
