### PR TITLE
CRM-16876 2nd attempt at capitalising country names, Also add a setting allowin…

### PR DESCRIPTION
**Pull request by seamuslee001**
…g users to hide country if country matches that of domain country

### CODE REVIEW

**Comment by seamuslee001** [comment]
@colemanw @mlutfy @eileenmcnaughton @JoeMurray @nganivet 

Picking up on the comments from the previous thread, I think this is a good core change, this will capitalise country names in mailing labels, it does also add a setting option so that people say in Australia where the standard is to hide the country if we are sending within Australia we can enable a setting and that will be hidden.

**Comment by mlutfy** [comment]
I think this is a good short/medium term solution. :+1:

**Comment by JoeMurray** [comment]
Skimmed the PR, didn't notice any gaps, liked the approach. Haven't tested.

**Comment by eileenmcnaughton** [comment]
OK I feel like this has had a thorough review & has been approved so I am merging. Thanks for all your work on this Seamus! It is definitely an improvement although we still have a way to go when it comes to starting to make changes through supported extensions rather than 'yet another setting'

**Pull request merged**
