### PR TITLE
English language/grammar - 4.6 branch

### PR DESCRIPTION
**Pull request by KarinG**
One of my clients would very much like to see this small English language/grammar edit. JIRA: https://issues.civicrm.org/jira/browse/CRM-19289 - Already fixed in 4.7

### CODE REVIEW

**Comment by KarinG** [comment]
@eileenmcnaughton - could you please merge this? Jon ok-ed this for 4.7 and that is already merged. Merci! :-)

**Comment by eileenmcnaughton** [comment]
Tell you client you've gotten it merged for 4.6.21.0 :-)

**Comment by KarinG** [comment]
:-)!

**Comment by eileenmcnaughton** [comment]
Or tell them they should have received it ....

**Pull request merged**
