### PR TITLE
dev/core#4889 - Don't delete my files

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/4889

Before
----------------------------------------
On windows, and mac by default, file paths are case-insensitive, so the status check reports false positives, and the upgrade deletes the files.

After
----------------------------------------
Works with both case-sensitive and not.

Technical Details
----------------------------------------
The upgrade part is here where it reuses the same code: https://github.com/civicrm/civicrm-core/blob/7e2d00f356f254d19c13220e63b4c96f5de10044/CRM/Upgrade/Form.php#L576. Note also that since dirs in the deleted file list are represented with `/*` at the end, previously that code was trying to do is_dir on a path like `/path/to/dir/*`, which is always false. But it will probably still fail anyway if there still files in that folder, but the status check will warn about the folder.

Comments
----------------------------------------
I tested on windows and linux.

Started in 5.70

### CODE REVIEW

**Comment by totten** [comment]
Haven't figured out why, but when I try on macOS, I still get these two symptoms when upgrading 5.63=>5.71:

* For `cv upgrade:db` (or similar), it deletes the files.
* If I manually restore the files, then the status check complains about them.

(My procedure is like https://lab.civicrm.org/dev/core/-/issues/5013)

**Comment by demeritcowboy** [comment]
Does realpath() do something different on your system? If you do `cv ev 'var_dump(realpath(Civi::paths()->getPath("[civicrm.root]/readme.md")));'` does it return false or does it keep the lower-case letters instead of making them big, or does it do something goofy?

**Comment by demeritcowboy** [comment]
Also google says "The running script must have executable permissions on all directories in the hierarchy, otherwise realpath() will return FALSE".

**Comment by demeritcowboy** [comment]
@totten I have an alternate idea but don't want to spend time on it unless the above is the problem. Can you confirm `cv ev 'var_dump(realpath(Civi::paths()->getPath("[civicrm.root]/readme.md")));'` is returning readme.md instead of README.md on your mac?

**Comment by demeritcowboy** [comment]
I ended up making an alternate: https://github.com/civicrm/civicrm-core/pull/29421

**Pull request closed without merging**
