### PR TITLE
Why?

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
Why?

Before
----------------------------------------
Why?

After
----------------------------------------
I'm none-the-whyser, but there's less why.

Technical Details
----------------------------------------
Look at the next line.

Comments
----------------------------------------

### CODE REVIEW

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Comment by larssandergreen** [comment]
Maybe someone just needed to express how they feel about notes?

**Comment by colemanw** [comment]
I just spent an hour writing a detailed, 10 paragraph review of every facet of this PR, then immediately decided to overwrite it with this:
"Looks fine, merging."

**Comment by totten** [comment]
But did you look at the review guidelines? The review criteria are:

* Because
* If
* Somehow

**Comment by demeritcowboy** [comment]
If anyone is curious, the overwrite line used to have an `if` around it, but it's been like this for 15 years.

**Pull request merged**
