### PR TITLE
CRM-21806: Fix issues is search form when FULL_GROUP_BY_MODE enabled

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
On FULL_GROUP_BY_MODE enabled setup, doing any sort on Advance Search list, leads to DB error. 

Before
----------------------------------------
test-multiple-before

After
----------------------------------------
test-multiple-after

Technical Details
----------------------------------------
The issue is on INSERT query when the ORDER BY column is not present in select clause when we perform any sort on the search list. Hence, the fix cannot be applied directly to the insert query as there must be a definite number of select columns to used for inserting values. Reason why in the patch we first fetch the records in intended order and store it in a temp table. Which is then used to populate ```prev_next_cache``` table.

---

 * [CRM-21806: Search builder returns no results](https://issues.civicrm.org/jira/browse/CRM-21806)

### CODE REVIEW

**Comment by monishdeb** [comment]
ping @eileenmcnaughton  @lcdservices

**Comment by lcdservices** [comment]
@monishdeb this looks great. No errors when searching and sorting. Tested with Advanced Search as well as Custom Searches.

**Comment by eileenmcnaughton** [comment]
My main concern about this is adding another temporary so deep into the search . We do have temp tables in searches already but they are used by specific searches (e.g complex relationships). This one would be triggered every search and every time a list of contacts to dedupe is generated from what I can see.

The issue with temp tables is how they interact with replication - in general they are not recommended for data integrity reasons with replication. 

Specifically, however, WMF experienced a serious issue last year due to temp tables in CiviCRM. Over a period of months we witnessed that after a mysql restart replication slowly degraded to the point where the slaves were not keeping up. In the end we discovered the reason was because CiviCRM was created temp tables whenever we synced our mailings with an external supplier. In the replication log the DROP TEMPORARY TABLE statement appeared before the CREATE statement and they were breeding to the point we had tens of thousands of open temp tables on the slave. We 'fixed' it by using the 'evil_skip_BAO' parameter to avoid creating the temp tables. This change would bring back that problem.

As an aside - @monishdeb  the recently merged fix to exception handling in this chunk of code didn't squash the fatal here as it did for custom searches?

@totten is a more robust fix around this in scope for the work / proposals you are doing for wmf?

@ejegg @mepps

**Comment by eileenmcnaughton** [comment]
@jackrabbithanna fyi  - re replication

**Comment by monishdeb** [comment]
@eileenmcnaughton no it doesn't contain the fatal error in that shell and the insert query is necessary for prev/next cache rebuild so we can't bypass that.

 On the other hand, might use the regular table for now instead of temp as I can't think of any other alternative solution :(

**Comment by eileenmcnaughton** [comment]
(It's worth considering this sentence though "the insert query is necessary for prev/next cache rebuild " - I wonder if it really makes sense to rebuild the cache to add a sort - kinda feels like it kills the point of the cache)

**Comment by monishdeb** [comment]
@eileenmcnaughton @lcdservices I have updated the patch and this time I have avoided the use of any temp/regular table but derived table :)

**Comment by lcdservices** [comment]
@monishdeb @eileenmcnaughton this change is working fine.

**Comment by eileenmcnaughton** [comment]
So the query now looks like

```

      INSERT INTO civicrm_prevnext_cache ( entity_table, entity_id1, entity_id2, cacheKey, data )
        SELECT DISTINCT 'civicrm_contact', contact_id, contact_id, 'civicrm search 9a8283f2c7c90293c3810d975aa73086_4543', sort_name
        FROM ( SELECT contact_a.id as contact_id, contact_a.contact_type as `contact_type`, contact_a.contact_sub_type as `contact_sub_type`, contact_a.sort_name as `sort_name`, civicrm_value_constituent_information_1.id as civicrm_value_constituent_information_1_id, civicrm_value_constituent_information_1.marriage_date_3 as custom_3  FROM civicrm_contact contact_a 
LEFT JOIN civicrm_value_constituent_information_1 ON civicrm_value_constituent_information_1.entity_id = `contact_a`.id  WHERE (contact_a.is_deleted = 0)    ORDER BY `custom_3` desc, `contact_a`.`id`  LIMIT 0, 500  ) contact_a 
```

It DOES work - but I need to test performance on our staging server & also it WILL need a unit test.

I'm still trying to understand if we really needed to empty & rebuild the cache rather than just join off it & sort which would be more performant

**Comment by eileenmcnaughton** [comment]
OK - I see the cache builds only for the first 500 rows so the cache is caching the first 10 pages to display - so feeling OK about that. I'll do some performance tests & then we just need... unit test

**Comment by monishdeb** [comment]
@eileenmcnaughton I have added unit test, please have a look.

**Comment by monishdeb** [comment]
@eileenmcnaughton did you get any chance to review this PR?

**Comment by eileenmcnaughton** [comment]
@monishdeb I'm going to close this now as I committed the test separately & we have otherwise addressed this bug in the meantim

**Comment by monishdeb** [comment]
Oh ok thanks :)

**Pull request closed without merging**
