### PR TITLE
CRM-16355 : new options in schedule reminder for mutlilingual installation

### PR DESCRIPTION
**Pull request by samuelsov**
Add 2 options in multilingual installation for schedule reminders:
- filter the recipients of the message based on the language
- set the language of the message - either static or dynamic based on the preferred language

---
- [CRM-16355: Reminders in multilingual sites: allow to define the language of the sending](https://issues.civicrm.org/jira/browse/CRM-16355)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@samuelsov where is this at? do you think you can rebase it & repush - I can't see the failures now - were they real failures?

**Comment by eileenmcnaughton** [comment]
@totten - you probably want to ensure this is in before you do your scheduled reminder refactoring?

**Comment by totten** [comment]
As @eileenmcnaughton mentioned, I'm working on refactoring the scheduled reminder code. However, the target version (4.6 vs 4.7) is under some debate, so I'm going to merge/cherry-pick this directly into my branch. These changes will follow the same path as the rest of the refactoring.

**Comment by davecivicrm** [comment]
Closing per @totten  comment from Jul 20

**Pull request closed without merging**
