### PR TITLE
CRM-17422: Backport #7007 to 4.6

### PR DESCRIPTION
**Pull request by omarabuhussein**
Backporting https://github.com/civicrm/civicrm-core/pull/7007 to 4.6

---
- [CRM-17422: Change in custom field search behaviour impacting on performance](https://issues.civicrm.org/jira/browse/CRM-17422)

### CODE REVIEW

**Comment by omarabuhussein** [comment]
@monishdeb @eileenmcnaughton I tagged you since you original discussed the issue on https://github.com/civicrm/civicrm-core/pull/7007 .. what do you think ?

**Comment by eileenmcnaughton** [comment]
If it backported cleanly & you have tested against 4.6 I'm happy to merge it

**Comment by monishdeb** [comment]
yup @eileenmcnaughton if the backport patch fixes the original issue CRM-17422 then its ready to merge. @omarabuhussein have you test the fix in 4.6 latest ?

**Comment by omarabuhussein** [comment]
thanks guys ,,  I didn't really tested it on latest 4.6 but on a bit older one ... will test again on latest 4.6 and then compare the changes with current code on master and let you know

**Comment by colemanw** [comment]
@omarabuhussein have you tested this yet?

**Comment by omarabuhussein** [comment]
@colemanw  Yes and it work .. but there are many changes happened in this part of code in 4.7 so I want to trace the commit history and try to make the code similar as much as possible to the current code in 4.7 ... I also working on fixing a case where custom field type is a multi select box so this can wait a bit.

**Pull request closed without merging**
