### PR TITLE
[WIP] Alternate Manage groups in Admin UI extension

### PR DESCRIPTION
**Pull request by samuelsov**
Overview
----------------------------------------
Add "Manage group" to Admin UI extension

Differences from the original page:
- "Name" column becomes "Title"
- New column for "Public Title"
- New column "Parents" (edit works but not display)
- instead of writing "smart group", use an icon
- Disable/Enable is now a column instead of a button

Missing features:
- no way to display or refresh count for smart groups
- no hierarchy
- ~~the settings does not open in a popup~~ FIXED (needed a new menu item specific to edit)
- [added 2023-04-03] no way to add filters for smart group or parents

ksnip_20230322-175950

### CODE REVIEW

**Comment by colemanw** [comment]
@samuelsov can you rebase this now that #25955 is merged

**Comment by aydun** [comment]
I attempted to resolve the issue of making the Parents show up by adding `<html><type>Select</type></html>' to the Parents field in Group.xml & regenerating the BAO but that didn't seem to change anything.  Note that if you mark the Parents field as inline editable in the table and click on it, it correctly shows the parents in a select box and saves changes - just that it doesn't show normally.

**Comment by colemanw** [comment]
Here is a fix for getting Group.parents to display correctly: #25994

**Comment by aydun** [comment]
Test this please

**Comment by samuelsov** [comment]
Crap, still not good at rebasing. Let's close and open a new one.

**Pull request closed without merging**
