### PR TITLE
dev/core#4425 Standalone: fix lcMessages not sticking; slightly lazy sessions

### PR DESCRIPTION
**Pull request by artfulrobot**
This is an alternative to https://github.com/civicrm/civicrm-core/pull/27266

## Overview

https://lab.civicrm.org/dev/core/-/issues/4425

To reproduce:

- Administer > System Settings > Extensions: Enable the [update language](https://civicrm.org/extensions/update-language-files) extension, saves time, if you haven't already downloaded the translation files
- Administer > Localization > Languages: Enable two languages (no need for multilingual, just enable a second language)

You should then be able to display pages in different languages, using the `lcMessages=xx_YY` parameter. Ex:

- https://crm.example.org/civicrm?lcMessages=en_US
- https://crm.example.org/civicrm?lcMessages=fr_CA (adapt to the locale you enabled)

This works for a single page, but then does not stick when we navigate to another page.

Before
----------------------------------------

Locale selection is lost when we navigate to another page.

After
----------------------------------------

Locale selection sticks.

Notes
-------

See discussion on the original PR (link above)

"Lazy" sessions are means that when an anonymous user accesses a page, no session is created for them (and therefore no cookie is set) unless data is written to `$_SESSION`. It's good because it means we don't waste disk space or create unnecessary cookies just to store an empty session.

Implementing lazy sessions, however, is not entirely trivial because of the way PHP's sessions work. Drupal does it, and I suspect other CMSes do it too, but you do have to write a whole session handler.

This implements a less-lazy strategy. 

- no session is created for a new, anon user whose request never writes session data.
- a session is created if the request has a PHPSESSID cookie set.
- a session is created if the request writes session data.

It solves:

- So for anon users who don't need sessions, we have the desired lazy behaviour.
- For anon users who do need session data, **including those who use lcMessages to translate the UI**, we load their session data and thus can remember lcMessages on other page visits.
- We still have sessions that work.

### CODE REVIEW

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by mlutfy** [comment]
@artfulrobot wow this is really cool! Tha is for working on this. Sorry I didn't see this earlier. Don't hesitate to mention me on Standalone PRs (I don't often review all open PRs)

**Comment by colemanw** [comment]
@artfulrobot would you be able to rebase the merge conflicts?

**Comment by mlutfy** [comment]
I tested on:

- standalone
- drupal7 with inherit-language
- multilingual, and drupal9 with not-multilingual

Thank you @artfulrobot !

**Pull request merged**
