### PR TITLE
CRM-19967 contact query docs

### PR DESCRIPTION
**Pull request by xurizaemon**
DO NOT MERGE until CRM-4287 is merged please. (How can I better submit / flag a PR like this? Maybe I should just PR it without the changes from CRM-4287 at all, but this builds on that work.)

---

 * [CRM-19967: Contact query inline docs improvements from CRM-4287](https://issues.civicrm.org/jira/browse/CRM-19967)
 * [CRM-4287: Contact search for email address \(& other details\) shows only primary detail matches as results](https://issues.civicrm.org/jira/browse/CRM-4287)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Is this now redundant? Or was it incorporated/ is now closable?

Also, that business of passing around $apiEntity - do you have any idea why that is required in addition to MODE?

If not I don't think we should entrench the pattern

**Comment by xurizaemon** [comment]
Would be nice to get the docs fixes in. Not sure if the merged PR incorporated any of this. @jitendrapurohit do you know?

**Comment by eileenmcnaughton** [comment]
Rebasing over master would probably tell you

**Comment by xurizaemon** [comment]
Replaced by #10090

**Pull request closed without merging**
