### PR TITLE
[REF] Consolidate input params that are primarily used for the membership entity action to an array

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This simplifies the params for the function. In general we are very used to seeing params in the format used for the
api so this seems simpler when a lot of the function is just compiling them for that purpose

Before
----------------------------------------
```
public function processMembership($contactID, $membershipTypeID, $is_test, $changeToday, $customFieldsFormatted, $numRenewTerms, $membershipID, $pending, $contributionRecurID, $isPayLater)
```

After
----------------------------------------
```
 public function processMembership($memParams, $changeToday, $numRenewTerms, $pending) {
```

Technical Details
----------------------------------------

Comments
----------------------------------------
I've been adding a lot of cover to the membershipRenewalTest class to facilitate a cleanup of that function. I think this is just moving params so is adequately covered by those tests

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@monishdeb unrelated to anything else - but it would be nice to have this reviewed. Test cover previously added to membershipRenewalTest

**Comment by eileenmcnaughton** [comment]
@pradpnayak is this one you could add to your super-helpful review drive?

**Comment by pradpnayak** [comment]
Looks good, Did a quick UI membership renewal test, Works fine.

Good to merge

**Comment by eileenmcnaughton** [comment]
thanks @pradpnayak 

@seamuslee001 @colemanw could someone merged based on @pradpnayak's testing?

**Pull request merged**
