### PR TITLE
add sorting for various fields in bookkeeping report

### PR DESCRIPTION
**Pull request by yashodha**
Overview
----------------------------------------
add sorting for various fields (receive, receipt, thankyou date, financial type, etc)  in contribution bookkeeping report

Before
----------------------------------------
No sorting for various fields in contribution bookkeeping report.

After
----------------------------------------
Sorting for various fields in contribution bookkeeping report is available

### CODE REVIEW

**Comment by jaapjansma** [comment]
test this please

**Comment by jaapjansma** [comment]
* General standards
    * Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
        * [ ] __PASS__ : The goal/problem/solution have been adequately explained in the PR.
    * User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
        * [ ] __PASS__: The change would be intuitive or unnoticeable for a majority of users who work with this feature.
    * Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
        * [ ] __PARTIAL PASS__: Tthe changes do not require documentation.
    * Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
        * [ ] __PASS__: There are extra fields for sorting. We only tested the sorting of receive date.
        * [ ] __ISSUE__: We could not test the sorting on receipt date and thank you date because those are not available as a column in the report. 
        * [ ] __ISSUE__: Regarding the sorting of financial type and payment method those fields are  available as a sort field in the report (we checked this in dmaster).
* Developer standards
    * Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
        * [ ] __PASS__: The change preserves compatibility with existing callers/code/downstream.
    * Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
        * [ ] __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
    * Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
        * [ ] __PASS__: The change is trivial enough that it does not require tests.
    * Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
        * [ ] __PASS__: The test results are all-clear.

@yashodha we do think this PR needs some additional work. Please check the sorting of the fields financial type and payment instrument. It looks like those are already available as a sort. And could also make the fields Receipt Date and Thank You Date available as a column?

**Comment by mattwire** [comment]
@yashodha Please review comments from @jaapjansma

**Comment by jaapjansma** [comment]
Betty and I are reviewing PR's and we came across this one. No work has been happened on this PR since 20th of April. So we will close this PR. Feel free to reopen when you continue work on this @yashodha

**Pull request closed without merging**
