### PR TITLE
Intelligently adjust menubar for D7 toolbar toggle

### PR DESCRIPTION
**Pull request by colemanw**
Overview
-----
Civi menubar was being set to width 97% to make room for the Drupal Toolbar toggle. The 2 problems with that are:
- 97% is imprecise - what we really wanted was 100% minus the width of the toolbar toggle.
- Some Drupal sites do not use the toolbar module.

Before
------
Civi menubar set to width 97% unconditionally.

After
------
Civi menubar set to 100% minus the width of the toolbar toggle, but only if the toolbar toggle is actually present on the screen.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw this makes sense - do you know of a case when the if would be false?

**Comment by MikeyMJCO** [comment]
(*CiviCRM Review Template DEL-1.1*)



* Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
    * __UNREVIEWED__
    * __COMMENTS__: Change seems simple enough without explanation however this link provides the context: https://chat.civicrm.org/civicrm/pl/5uh3133bxfd33m3xa3xjpwzaxc
Gitlab, StackExchange).
* Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
    * __PASS__: The test results have failures, but these have been individually inspected and found to be irrelevant.
* Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
    * __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
* Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
     * __PASS__: The changes do not require documentation.
* Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
    * __PASS__: The change sufficiently improves test coverage, or the change is trivial enough that it does not require tests.
* Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
    * __PASS__: Ran on CiviCRM 5.6.0 with the following combinations:
         * With Shoreditch with the Admin Menu module - Civi menu is full width.
         * With Shoreditch without the Admin Menu module - Civi menu has gap to show the expander/toggle.
         * With Shoreditch without the Admin Menu module with the core Toolbar module disabled - Civi menu is full width.
         * Without Shoreditch with the Admin Menu module - Civi menu is full width.
         * Without Shoreditch without the Admin Menu module - Civi menu has gap to show the expander/toggle.
r/toggle.
         * Without Shoreditch without the Admin Menu module with the core Toolbar module disabled - Civi menu is full width.

* User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
    * __PASS__: The change would be intuitive or unnoticeable for a majority of users who work with this feature.
* Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
    * __PASS__: The change preserves compatibility with existing callers/code/downstream.

**Comment by MikeyMJCO** [comment]
> this makes sense - do you know of a case when the if would be false?

@eileenmcnaughton the if will return false if the core toolbar module is disabled or if the admin_menu module is being used instead.

**Comment by eileenmcnaughton** [comment]
Thanks for the review @MikeyMJCO really helpful

**Pull request merged**
