### PR TITLE
WIP Don't enable authnet on new installs, mark as legacy

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Follow on from #16362 and emails from Authorize.net.  The APIs used by the core authorize.net payment processor are deprecated and not supported.
Alternative using supported APIs and current security checks (via signature key) available at https://lab.civicrm.org/extensions/authnet

Before
----------------------------------------
Legacy authorize.net in core and not clear that it will stop working (and is less secure because it does not verify requests as they dropped the md5 support some time ago).

After
----------------------------------------
Legacy authorize.net not available for new installs. Existing installs shown as legacy when selecting via add payment processors.

Technical Details
----------------------------------------

Comments
----------------------------------------
@JoeMurray @eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I think this is still like our number 2 or 3 most used processor so we need to be a bit more careful on this one & get broader buy inn

**Comment by mattwire** [comment]
Statement from Authorize.net: 
AIM/SIM APIs and Simple Checkout Officially Deprecated
Our legacy Advanced Integration Method (AIM) and Server Integration Method (SIM) APIs, as well as our Simple Checkout option, are officially deprecated, meaning we will no longer provide any updates to these APIs. If you or your merchants’ websites or payment solutions use one of these methods, this means the following:
- They can continue to process transactions via the APIs and Simple Checkout
- Use of the APIs and Simple Checkout is “as is,” meaning they will not receive any new updates, including new features, payment network mandate updates, etc.
- Because these methods will no longer be updated, your merchants could face penalties and fees associated with transactions that do not meet mandate/compliance requirements
- Transaction processing functionality could deteriorate over time

**Comment by mlutfy** [comment]
Should we add a Status Check? (that points to a blog post) or just a blog post?

**Comment by yashodha** [comment]
@mattwire this will require updates to generated data as well, right?

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon @kcristiano any thoughts on this one?

**Comment by kcristiano** [comment]
@eileenmcnaughton I think it's a good idea.  We are not removing it, we are just disabling it by default.  If someone wants it bad enough they can turn it back on.

I am reluctant to rename it, but I am probably being over cautious.   

I would like to be sure that the Authorize extension is available to install "in app" by the time this releases.

**Comment by mattwire** [comment]
Closing for now

**Pull request closed without merging**
