### PR TITLE
Move api_key write permission checks from api to BAO

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Port write patch from https://github.com/civicrm/civicrm-core/pull/14660 to 5.15

Before
----------------------------------------
Tests failing on 5.15

After
----------------------------------------
Tests passing

Technical Details
----------------------------------------
@colemanw we need this for tests to pass - but we ALSO need to make sure the current apiv4 master branch ships with 5.15 to keep in sync if we merge this. If we don't I think we should just ignore this particular test fail for 5.15

Comments
----------------------------------------
@totten @seamuslee001 @monishdeb

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw what about this - how do we manage your apiv4 change WRT 5.15 - what apiv4 will ship with 5.15?

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by colemanw** [comment]
@eileenmcnaughton current master branch of api4 is marked as compatible with 5.15 so I think we could cut a release.

**Comment by eileenmcnaughton** [comment]
@colemanw ok - but we need to port this & the other patch back to 5.15 or cut  a release for 5.15 prior to the changes?

**Comment by colemanw** [comment]
I'm losing track of them all @eileenmcnaughton - which other patch? And is that the reason tests are failing on this PR?

**Comment by eileenmcnaughton** [comment]
@colemanw you made changes to apiv4 & to master in tandem. 
The rc branch missed out - this is one of (but not both of) the patches you made to master branch - so it's kinda doomed as is

We either need to make the 5.15 branch run on the version of apiv4 without the patch or backport the patch to 5.15 or ignore the test fails on branch 5.15 

Expediting moving apiv4 into core might not simplify in the short term but might save us from solving both a short term and a long term problem (we might need to resolve the custom data thing in the rc period though)

**Comment by colemanw** [comment]
Oh I see, it was one PR with 2 commits and you've cherry-picked one but not the other of those commits.
Yea we need to backport both for tests to pass. I've added the other to this PR.

**Comment by eileenmcnaughton** [comment]
unrelated fail - @colemanw this is good to merge IMHO but do you need to cut a 5.15 branch of apiv4 as 5.14 civi users should use the apiv4 pre this change

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by totten** [comment]
Discussed this a bit with Eileen on MM; she pointed out that https://github.com/civicrm/org.civicrm.api4/pull/177 is in `api4@master` (developmental branch for upcoming `api4@4.5.0`).

However, that's not been published. The last release is `api4@4.4.2` which doesn't have the change, so `civicrm-*.tar.gz` should ship with a compatible version. The current Ext test-matrix shows the published version of api4 passing on 5.15, so I think we're OK to publish 5.15 on that front.

Looking forward to eventual release of `api4@4.5.0` (`master`)... the `info.xml` probably needs an update to require `civicrm-core@5.16`?

**Comment by eileenmcnaughton** [comment]
closing but opened https://github.com/civicrm/org.civicrm.api4/pull/183 to make sure we don't release an api cut without marking it as non 5.15 compatible

**Pull request closed without merging**
