### PR TITLE
CRM-21262 - Add a system check for the resource URL

### PR DESCRIPTION
**Pull request by MegaphoneJon**
Overview
----------------------------------------
This adds a system check to ensure that the Resource URL is correct.

Before
----------------------------------------
If the resource URL was incorrect, you'd have to know that broken arrow icons in the CiviCRM menus were a symptom of that.

After
----------------------------------------
You'll now be informed via the System Check when a Resource URL is incorrect.

---

 * [CRM-21262: Add a check for incorrect Resource URL](https://issues.civicrm.org/jira/browse/CRM-21262)

### CODE REVIEW

**Comment by colemanw** [comment]
Excellent. I believe CiviVolunteer performs a similar check, but I agree core is a better place for it.
@GinkgoFJG @ginkgomzd FYI.

**Comment by colemanw** [comment]
@MegaphoneJon test failures suggest that this check ought to be bypassed when in unit-test mode.

**Comment by highfalutin** [comment]
Tested; behaves as described. Note: when the Resource URL is incorrect, the System Status screen breaks, so the only people who will see the full message given by this system check are those accessing the site through the api. Users viewing the site in a browser may see the "Incorrect Resource URL" headline under a "System Status: Error" warning when they first log in, but they won't see the instructions given in the full message. Anyway seems worth merging @colemanw

**Comment by colemanw** [comment]
Just wondering if this check will fail for firewalled servers that can't access themselves via http.
Probably. But if someone has the skills to set up one of those, they can probably also figure out how to dismiss this error msg.

**Comment by GinkgoFJG** [comment]
Thanks for the heads-up, @colemanw. Have ripped this out of volunteer.

**Pull request merged**
