### PR TITLE
SearchKit - Fix aggregated joins

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes a bug where adding an aggregated join will cause invalid SQL.

Before
----------------------------------------
The following search will crash:
SEARCH FOR: Activities
WITH (optional): Activity Contacts
GROUP BY: Activity ID

After
----------------------------------------
Search runs without error.

Comments
---------------
When merging this forward, the first commit is already in `master` and can be skipped over if git complains.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw I'm not managing to replicate this - but @kurund if this fixes for you please merge

**Comment by kurund** [comment]
@colemanw @eileenmcnaughton 

Tested above on master and it working as expected.  Did few more random tests and all good.

IMO good to merge.

**Comment by kurund** [comment]
Also tested on 5.42 branch and also working fine.

**Comment by colemanw** [comment]
Thanks @kurund - can you also check this further improvement I did in master: #21420

**Pull request merged**
