### PR TITLE
CRM-17887 - Add a new setting `Financial Batch date`

### PR DESCRIPTION
**Pull request by rajbdilip**
https://issues.civicrm.org/jira/browse/CRM-17887

He's likely referencing the setting at Administer > Localization > Date Formats, Complete Date fields. Unfortunately, those settings don't include a convenient one for this purpose, since by default they include text names of months, etc. So, addin a new field exclusively for financial batches make more sense.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This code looks good to me (@joemurray ) - we need someone to test it though & I'm not sure if we need to wait for next QA week to merge it

**Comment by saurabhbatra96** [comment]
Tested on http://pr8441.test-ubu1204-5.civicrm.org
- Administer->Localization->Date Formats: Changed date format to `%d/%m/%Y`
- Created a new test batch from Contributions->Accounting Batches
- Assigned a dummy transaction to the batch
- Closed & exported the batch in IIF format
- Date was as expected: 
```
DATE

26/05/2016
```

**Comment by rajbdilip** [comment]
@saurabhbatra96 Thank you for testing. :)

**Comment by eileenmcnaughton** [comment]
@totten I feel like this PR has been through a couple of rounds of review & it has been tested. It can wait to be merged in review week - but I kinda want to tag it as 'ready to merge ....' (as opposed to merge on pass which would mean 'merge now damn you')

**Comment by yashodha** [comment]
PR works fine

**Pull request merged**
