### PR TITLE
dev/core#2902 revert apiv3 handling of membership

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This reverts changes that were making api v3 date handling change if skipStatusCalc were set.

Before
----------------------------------------
APiv3 had stopped calculating dates when the (silly) 'skipStatusCal' parameter was passed in

After
----------------------------------------
Code in apiv3 layer reverted back to 5.39 code

Technical Details
----------------------------------------

Comments
----------------------------------------
@KarinG @agileware-fj @artfulrobot

### CODE REVIEW

**Comment by agileware-fj** [comment]
Test addition and approach looks good to me.

I'm doing some run tests on it at the moment.

**Comment by eileenmcnaughton** [comment]
thanks @agileware-fj

**Comment by agileware-fj** [comment]
@eileenmcnaughton All good from the Webform path and clearly works for APIv3 Membership.create per the tests.

Getting some weird results from the Order API, but I highly doubt that's related to this PR.

👍  from me.

**Comment by eileenmcnaughton** [comment]
thanks @agileware-fj let's get @totten or @colemanw to merge this & we'll port to 5.42.1

Can you please log an issue re 'weird results from the Order API,'

**Comment by seamuslee001** [comment]
ok this seems to have general support merging

**Comment by eileenmcnaughton** [comment]
@artfulrobot the tests were just the specific case where passing in 'skipStatusCal' was causing the dates to not calculated. I don't know if there are ohter permutations of weirdness....

**Pull request merged**
