### PR TITLE
Add deprecated warning to hook_civicrm_tabs since it has been depreca…

### PR DESCRIPTION
**Pull request by mattwire**
…ted since 4.7!

Overview
----------------------------------------
It would be nice to remove this hook soon since it's been deprecated since 4.7

Before
----------------------------------------
No deprecated warning.

After
----------------------------------------
Deprecated warning.

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
Looks fine to me

**Comment by eileenmcnaughton** [comment]
@mattwire @seamuslee001 I don't think that is the right way to deprecate a hook - because it  will still be called - you need to have a deprecation notice if there is a change made as a result of calling the hook (unless this  hook is no longer called in core)

**Comment by eileenmcnaughton** [comment]
Removed MOP to make sure it doesn't get merged while pending response to ^^

**Comment by mattwire** [comment]
@eileenmcnaughton You are right. This PR won't work - the hook is called only from CRM/Contact/Page/View/Summary.php. It's been deprecated for 4 years. I guess we need to do an array compare and warn for a few releases before removing.

**Comment by yashodha** [comment]
@mattwire So, this can be closed then. Are you working on a new PR?

**Pull request closed without merging**
