### PR TITLE
CRM-19124 update birth_date to be consistent at point of hook (use da…

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
…tepicker)

### CODE REVIEW

**Comment by JKingsnorth** [comment]
Currently this creates an inconsistent output in the 'pre' hook for the 'Individual' object - details in JIRA.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @JKingsnorth I think I've finally cracked it. I managed to push the formatting down into smarty in a consistent way by assigning smarty_view_format. It's a little weird & magical still, but now consistent with between custom & core dates. If the date is a format that does not include day then it will choose a setting that doesn't.

The hook format should be OK on pre hook now...

**Comment by eileenmcnaughton** [comment]
I believe CRM-15948 is also fixed in this

**Comment by seamuslee001** [comment]
ok so 

Pre Hook - API from drush
```
"birth_date":"19911102000000"
```
Post Hook - API from drush
```
"birth_date":"19911102000000",
```
Pre hook contact summary inline update
```
birth_date":"1991-11-01"
```
Post hook contact summary inline update
```
"birth_date":"19911101000000",
```
Pre Hook Contact Edit screen
```
birth_date":"1991-11-02"
```
Post Hook Contact Edit Screen
```
birth_date":"19911102000000",
```

**Comment by seamuslee001** [comment]
I didn't test updating via Import but i think that gives a pretty good coverage. Pre hook still seems a bit all over the shop, However we do have 2 formats now on Pre which is all right. Post hook looks pretty stable now

**Comment by eileenmcnaughton** [comment]
I think it is a reduction on formats anyway :-)

You think this is good to merge?

**Comment by eileenmcnaughton** [comment]
NB the key thing in my mind is getting rid of custom formats - there are still 2 formats but none of them look like 04/05/2017 which could be 4 May or 5 April....

**Comment by eileenmcnaughton** [comment]
Also note this should affect profile pages too

**Comment by seamuslee001** [comment]
given this appears to be an improvement and a reduction down to 2 formats in the hook output.  I think we should merge this as an improvement

**Comment by eileenmcnaughton** [comment]
thanks @seamuslee001

**Pull request merged**
