### PR TITLE
NFC use checkTaxAmount to calculate lineitem tax_amount on contribution form

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 this looks OK but I'm not quite sure how to test - what tests have you done?

**Comment by seamuslee001** [comment]
I haven't any as yet as we don't have tax set up, I'm not sure how to test either

**Comment by monishdeb** [comment]
@seamuslee001 is their any jira ticket associated with this PR ?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I'm going to close this out on the basis of being 'old & scary'  sorry :-(

**Pull request closed without merging**
