### PR TITLE
[WIP] make more tests fail

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
Just seeing if any tests fail for now. I don't think this is the right way to do this for real since it creates incorrect visual noise.

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by demeritcowboy** [comment]
```
not ok 1114 - Error: CRM_Core_BAO_SettingTest::testGetItemGroup_Override
not ok 1115 - Error: CRM_Core_BAO_SettingTest::testDefaults
not ok 1116 - Error: CRM_Core_BAO_SettingTest::testOnChange
not ok 1117 - Error: CRM_Core_BAO_SettingTest::testSetCivicrmEnvironment
not ok 1118 - Error: CRM_Core_BAO_SettingTest::testPseudoConstants
PHP Fatal error:  Failed to make directory (imageUploadDir) at "/test/override/". Please update the settings or file permissions. in /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/CRM/Core/Session.php on line 517
PHP Stack trace:
PHP   1. {main}() /home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar:0
PHP   2. PHPUnit\TextUI\Command::main() /home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar:615
PHP   3. PHPUnit\TextUI\Command->run() phar:///home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar/phpunit/TextUI/Command.php:162
PHP   4. PHPUnit\TextUI\TestRunner->doRun() phar:///home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar/phpunit/TextUI/Command.php:206
PHP   5. PHPUnit\Framework\TestSuite->run() phar:///home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar/phpunit/TextUI/TestRunner.php:652
PHP   6. PHPUnit\Framework\TestSuite->run() phar:///home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar/phpunit/Framework/TestSuite.php:746
PHP   7. PHPUnit\Framework\TestSuite->run() phar:///home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar/phpunit/Framework/TestSuite.php:746
PHP   8. CiviUnitTestCase::setUpBeforeClass() phar:///home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar/phpunit/Framework/TestSuite.php:703
PHP   9. CiviUnitTestCase::_populateDB() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:311
PHP  10. Civi\Test\Data->populate() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:305
PHP  11. civicrm_api() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/Civi/Test/Data.php:50
PHP  12. Civi\API\Kernel->runSafe() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/api/api.php:22
PHP  13. Civi\API\Kernel->runRequest() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/Civi/API/Kernel.php:81
PHP  14. Civi\API\Provider\MagicFunctionProvider->invoke() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/Civi/API/Kernel.php:149
PHP  15. civicrm_api3_system_flush() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/Civi/API/Provider/MagicFunctionProvider.php:89
PHP  16. CRM_Core_Invoke::rebuildMenuAndCaches() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/api/v3/System.php:33
PHP  17. CRM_Core_Config->cleanupCaches() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/CRM/Core/Invoke.php:373
PHP  18. CRM_Utils_System::flushCache() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/CRM/Core/Config.php:281
PHP  19. Civi\Core\AssetBuilder->clear() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/CRM/Utils/System.php:1493
PHP  20. Civi\Core\AssetBuilder->getCachePath() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/Civi/Core/AssetBuilder.php:238
PHP  21. CRM_Core_Config->__get() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/Civi/Core/AssetBuilder.php:253
PHP  22. CRM_Core_Session::setStatus() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/CRM/Core/Config/MagicMerge.php:248
PHP  23. trigger_error() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/CRM/Core/Session.php:517
```

`not ok 503 - Error: api_v3_ContactTest::testMergedGetWithPermanentlyDeletedContact`

```
not ok 1518 - Failure: api_v3_MembershipStatusTest::testDeceasedMembershipInline
  ---
  message: 'Failure in api call for contact create:  1 Current membership(s) for this
    contact have been set to ''Deceased'' status.'
  severity: fail
  ...
```

`not ok 280 - Error: Civi\Test\ExampleHookTest::testPageOutput`

```
PHP Fatal error:  Some modules define permissions, but the CMS cannot store them: oauth_client in /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/CRM/Core/Session.php on line 517
PHP Stack trace:
PHP   1. {main}() /home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar:0
PHP   2. PHPUnit\TextUI\Command::main() /home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar:615
PHP   3. PHPUnit\TextUI\Command->run() phar:///home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar/phpunit/TextUI/Command.php:162
PHP   4. PHPUnit\TextUI\TestRunner->doRun() phar:///home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar/phpunit/TextUI/Command.php:206
PHP   5. PHPUnit\Framework\TestSuite->run() phar:///home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar/phpunit/TextUI/TestRunner.php:652
PHP   6. PHPUnit\Framework\TestSuite->run() phar:///home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar/phpunit/Framework/TestSuite.php:746
PHP   7. CRM_OAuth_MailSetupTest->run() phar:///home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar/phpunit/Framework/TestSuite.php:746
PHP   8. PHPUnit\Framework\TestResult->run() phar:///home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar/phpunit/Framework/TestCase.php:796
PHP   9. PHPUnit\Framework\TestResult->startTest() phar:///home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar/phpunit/Framework/TestResult.php:626
PHP  10. Civi\Test\CiviTestListenerPHPUnit7->startTest() phar:///home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar/phpunit/Framework/TestResult.php:406
PHP  11. Civi\Test\CiviTestListenerPHPUnit7->bootHeadless() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/Civi/Test/CiviTestListenerPHPUnit7.php:49
PHP  12. CRM_OAuth_MailSetupTest->setUpHeadless() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/Civi/Test/CiviTestListenerPHPUnit7.php:93
PHP  13. Civi\Test\CiviEnvBuilder->apply() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/ext/oauth-client/tests/phpunit/CRM/OAuth/MailSetupTest.php:18
PHP  14. Civi\Test::asPreInstall() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/Civi/Test/CiviEnvBuilder.php:200
PHP  15. Civi\Test\CiviEnvBuilder->Civi\Test\{closure:/home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/Civi/Test/CiviEnvBuilder.php:181-200}() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/Civi/Test.php:40
PHP  16. Civi\Test\CiviEnvBuilder\ExtensionsStep->run() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/Civi/Test/CiviEnvBuilder.php:196
PHP  17. CRM_Extension_Manager->install() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/Civi/Test/CiviEnvBuilder/ExtensionsStep.php:42
PHP  18. CRM_Core_Invoke::rebuildMenuAndCaches() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/CRM/Extension/Manager.php:314
PHP  19. CRM_Core_Config->cleanupPermissions() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/CRM/Core/Invoke.php:381
PHP  20. CRM_Core_Session::setStatus() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/CRM/Core/Config.php:313
PHP  21. trigger_error() /home/jenkins/bknix-dfl/build/core-19939-91j9h/web/sites/all/modules/civicrm/CRM/Core/Session.php:517
```

**Comment by eileenmcnaughton** [comment]
You are on a roll

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
Probably we should close this now but I re-kicked it to see if the money-merge changed anything

**Comment by demeritcowboy** [comment]
Move to lab since I'm probably not going to get to any of them any time soon. The last one I think I saw a variation of at one point on screen and is just that the type of popup message is wrong to begin with.

https://lab.civicrm.org/dev/core/-/issues/2508

not ok 599 - Error: CRM_Contact_Form_Task_EmailCommonTest::testPostProcessWithSignature
not ok 603 - Error: CRM_Contact_Form_Task_UseraddTest::testUserCreateFail
not ok 653 - Error: CRM_Contact_Page_View_UserDashBoardTest::testDashboardContentEmptyContact
not ok 654 - Error: CRM_Contact_Page_View_UserDashBoardTest::testDashboardContentContributionsWithInvoicingEnabled
not ok 655 - Error: CRM_Contact_Page_View_UserDashBoardTest::testDashboardContentContributions
not ok 698 - Failure: CRM_Contribute_BAO_ContributionRecurTest::testAutoRenewalWhenOneMemberIsDeceased
not ok 944 - Error: CRM_Core_BAO_AddressTest::testSharedAddressChaining3
not ok 1115 - Error: CRM_Core_BAO_SettingTest::testGetItemGroup_Override
not ok 1116 - Error: CRM_Core_BAO_SettingTest::testDefaults
not ok 1117 - Error: CRM_Core_BAO_SettingTest::testOnChange
not ok 1118 - Error: CRM_Core_BAO_SettingTest::testSetCivicrmEnvironment
not ok 1119 - Error: CRM_Core_BAO_SettingTest::testPseudoConstants
not ok 507 - Error: api_v3_ContactTest::testMergedGetWithPermanentlyDeletedContact
not ok 1382 - Failure: api_v3_JobTest::testProcessMembershipDeceased
not ok 1418 - Failure: api_v3_LoggingTest::testEnableDisableLogging
not ok 1522 - Failure: api_v3_MembershipStatusTest::testDeceasedMembershipInline
not ok 280 - Error: Civi\Test\ExampleHookTest::testPageOutput
not ok 2 - Failure: Civi\Financialacls\FinancialTypeTest::testChangeFinancialTypeName

**Pull request closed without merging**
