### PR TITLE
Convert final settings on the Display form

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Convert display form to be fully metadata based

Before
----------------------------------------
mix of hard-coding & metadata

After
----------------------------------------
Hard-coding only affects the very-non-standard 'invoicing' setting impact on the form - this should be handled better but is out of scope for now

Technical Details
----------------------------------------
Ties in with other recent preferences forms changes

Comments
----------------------------------------
@mattwire @seamuslee001

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by mattwire** [comment]
test this please

**Comment by mattwire** [comment]
I have reviewed the code and run this PR locally.  Merge on pass

**Comment by seamuslee001** [comment]
Added merge on pass as per Matt's review

**Pull request merged**
