### PR TITLE
Remove unused variable

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------

Before
----------------------------------------
image

After
----------------------------------------

Technical Details
----------------------------------------
I did a universe search & commented that the function is not in use but need to edit unit tests to make it private

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton it's ok to make a member private and still access it from unit tests. `Civi\Test\Invasive` works really well for accessing anything private for the sake of testing:
https://github.com/civicrm/civicrm-core/blob/dc6193f49a76feab6f42932fa3b95fa4658ebb99/Civi/Test/Invasive.php#L5-L11

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@colemanw yeah - although I think I'd rather think more about that since I don't think the tests are testing the right place

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Pull request merged**
