### PR TITLE
Updates RiverLea to latest version

### PR DESCRIPTION
**Pull request by vingle**
Overview
----------------------------------------
5.80 branch version of https://github.com/civicrm/civicrm-core/pull/31534. Updates RiverLea in core from v5.80.7 to v5.80.9: some responsive fixes, contact image & D7+Seven

Before
----------------------------------------
RiverLea is v5.80.7

After
----------------------------------------
RiverLea is v5.80.9

Technical Details
----------------------------------------

5.80.9
 - FIXED - D7 Seven theme .button style overwriting colours
 - CHANGED - D7 Seven, matched page-padding.
 - FIXED - Responsive contact dashboard, below 768px: wrapped contact-summary label/data, wrap action links.
 - FIXED - Responsive contact dashboard, below 500px: improve hidden text and sidetabs width.
 - MOVED - Responsive contact dashboard css from tabs.css to contactSummary.css
 - CHANGED - Walbrook avatar image - made a little larger and thiner border
 - FIXED - better name-spaced AFform padding for front-end vs backend

5.80.8
 - CHANGED - CiviLint - further lint adjustments (tabs for double space, missing semi-colons)
 - FIXED - SearchKit button group hierarchy wrapping button groups
 - FIXED - removed button styling for another (x)-type cancel-only button in SearchKit builder
 - FIXED - avatar positioning works to an extent (floats right in dashboard header for Walbrook / Hackney) (#87)
 - REMOVED - avatar flexbox positioning and simplified css, as not being applied
 - ADDED - dash image border in Walbrook
 - ADDED CSS VARIABLES (3)
    --crm-dash-image-right (distance from right for avatar)
    --crm-dash-image-top (distance from top)
    --crm-dash-image-border (optional border)
 - REMOVED CSS VARIABLES (2)
    --crm-dash-image-justify
    --crm-dash-image-direction

Comments
----------------------------------------
If The Island is enabled, then [there are some quirks](https://lab.civicrm.org/extensions/riverlea/-/issues/85) with RiverLea, ie contact image position is changed via TheIsland's JS - so make sure it's not enabled to test this.

RiverLea uses an internal version numbering of the upcoming Civi version (ie 5.80) it's being tested against plus a rising change third digit for revisions. This third digit isn't related to CiviCRM's version numbering - ie RiverLea 5.80.2 won't relate specifically to CiviCRM 5.80.2. RiverLea's version number and active stream name is displayed in the lower-right corner of internal CiviCRM pages to support debugging. E.g.

image

### CODE REVIEW

**Comment by ufundo** [comment]
Thanks @vingle !

These test fails look unrelated:
```
E2E\AfformMock\MockPublicFormBrowserTest::testUpdateMiddleName
Behat\Mink\Exception\ElementNotFoundException: Element matching css "input#middle-name-1" not found.

/home/homer/buildkit/build/build-5/web/core/vendor/behat/mink/src/WebAssert.php:465
/home/homer/buildkit/build/build-5/web/core/ext/afform/mock/tests/phpunit/E2E/AfformMock/MockPublicFormBrowserTest.php:49
/home/homer/buildkit/extern/phpunit9/phpunit9.phar:2520
```
and
```
E2E_CivicrmAdminUi_ManageGroupsTest::testManageGroups
WebSocket\TimeoutException: Connection timeout: Empty read; connection dead?

/home/homer/buildkit/build/build-5/web/core/vendor/phrity/websocket/lib/Connection.php:360
/home/homer/buildkit/build/build-5/web/core/vendor/phrity/websocket/lib/Connection.php:211
/home/homer/buildkit/build/build-5/web/core/vendor/phrity/websocket/lib/Client.php:241
/home/homer/buildkit/build/build-5/web/core/vendor/dmore/chrome-mink-driver/src/DevToolsConnection.php:139
/home/homer/buildkit/build/build-5/web/core/vendor/dmore/chrome-mink-driver/src/ChromePage.php:73
/home/homer/buildkit/build/build-5/web/core/vendor/dmore/chrome-mink-driver/src/ChromeDriver.php:250
/home/homer/buildkit/build/build-5/web/core/vendor/behat/mink/src/Session.php:175
/home/homer/buildkit/build/build-5/web/core/Civi/Test/MinkBase.php:56
/home/homer/buildkit/build/build-5/web/core/ext/civicrm_admin_ui/tests/phpunit/E2E/CivicrmAdminUi/ManageGroupsTest.php:28
/home/homer/buildkit/extern/phpunit9/phpunit9.phar:2520
```

They both look... familiar.

Any ideas @totten or @seamuslee001 ?

**Comment by ufundo** [comment]
Given all these PR changes are in the extension, which isn't enabled by default, I see no way those fails could be a result of these changes - so I don't think a blocker on merging.

**Comment by ufundo** [comment]
Have clicked through a fair few of the notes and look good.

As an example,  Walbrook with D7 Seven.

Before:
image

After:
image

So definite improvements. Merging.

**Comment by vingle** [comment]
Thanks @ufundo. Odd the image is there, it should be higher up (and is in my tests on Seven :-/). Is it higher in the header in other CMS/Drupal themes by any chance?

image

**Pull request merged**
