### PR TITLE
Check for required mbstring extension

### PR DESCRIPTION
**Pull request by colemanw**

### CODE REVIEW

**Comment by colemanw** [comment]
Grepping around our codebase, we have a habit of always using mbstring functions conditionally. This breaks with that pattern, mostly because of https://github.com/civicrm/civicrm-core/pull/9268. What do we think?

**Comment by colemanw** [comment]
I'm having second thoughts about this because SOAP is rarely used. I'm now inclined to:

- Keep this PR but downgrade it from "error" to "notice"
- Wrap the news widget's use of `mb_substr` in a conditional

**Comment by nganivet** [comment]
Without understanding much of the context ... our database is UTF-8, anyone can type anything in all text fields (ie. I could well enter Russian or Chinese names on any contribution form), and PHP notably breaks if we do not use the mb_* functions with such input.

So I would +1 mandating the mbstring extension as this PR suggests, but also wrap the use in a conditional to be consistent with the rest of the code base. Upvoted Coleman's 2nd suggestion.

**Comment by seamuslee001** [comment]
I am a + on the need for mbstring, I think that it should be needed as it is useful and since php4

**Comment by seamuslee001** [comment]
I am satisfied with Coleman's 2nd option.

**Pull request merged**
