### PR TITLE
[WIP] dev/core#980 [test-dbunit] remove use of discontinued phpunit/dbunit

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Remove obsolete phphunit/dbunit package from our test suite

https://github.com/sebastianbergmann/dbunit/issues/217

Removing our dependency on this removes a hurdle in supporting more recent phpunit versions since we need to migrate over our own classes to extend the namespaced classes, but currently they extend a dbunit class so getting rid of that is a first useful step.

Before
----------------------------------------
phpunit/dbunit used in tests 

After
----------------------------------------
phpunit/dbunit not used in tests 

Technical Details
----------------------------------------
I came into this as the path to updating our phpunit version expectations requires us to start changing how we call phpunit & the path for this is much less clear ... and then it stops

The phpunit/dbunit package has been discontinued. I've removed the reference to it from the top level
extends and one call to it & the test I tried locally passes so it's not needed for ALL tests.

Let's see where it IS needed & what our options are - have at it jenkins

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton 
```
Fatal error: Call to undefined method api_v3_ActivityCaseTest::createDefaultDBConnection() in /home/jenkins/bknix-dfl/build/core-14268-1unqn/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php on line 249
```

**Comment by eileenmcnaughton** [comment]
@seamuslee001 OK - I got past that bit - lessee

**Comment by seamuslee001** [comment]
Jenkins doesn't like your style @eileenmcnaughton https://test.civicrm.org/job/CiviCRM-Core-PR/26195/checkstyleResult/new/

**Comment by eileenmcnaughton** [comment]
closing for now - sub-prs still progressing

**Pull request closed without merging**
