### PR TITLE
QuickSearch - Add Current Employer option

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds "Current Employer" as a quicksearch option in the menubar.

### CODE REVIEW

**Comment by wyde22** [comment]
ok thanks but in the url share in this issue i can see the new data in autocomplete results

**Comment by colemanw** [comment]
> ok thanks but in the url share in this issue i can see the new data in autocomplete results

I don't understand your comment. Can you please explain in detail how you tested and what the result was?

**Comment by composerjk** [comment]
You may need to go to the Settings for [_Search Preferences_](http://core-27766-1257c.test-1.civicrm.org:8001/civicrm/admin/setting/search?reset=1) on the demo site to add the _Current Employer_ option.

**Comment by wyde22** [comment]
ok perfect i can see the new data now. If i want to add a new data (custom field for example) for this quicksearch i have a specific hook or event symfony perhaps ?

It's necessary to modify `CRM/Core/SelectValues.php`

**Comment by colemanw** [comment]
@wyde22 we really try to keep PR discussions focused on the question of "should this PR be merged." Currently we have 138 open PRs!!! It's a lot to manage and we need all the help we can get. You are the reviewer of this PR so it's your job to say "I have tested this PR and it works" or "I have tested this PR and it needs work before it can be merged". That will help us reduce the number to 137 :)

**Comment by wyde22** [comment]
ok @coleman :). No problem i tested this PR and it works. I can see the current employer in the quicksearch. Thanks

**Comment by colemanw** [comment]
Thanks @wyde22 - to answer your questions, custom fields should be available automatically in the list (as long as you remember to check the "Searchable" checkbox when you create the custom field.

**Pull request merged**
