### PR TITLE
Afform - Show breadcrumbs appropriate to whether a form can be edited

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Follow-up to fix some issues with #19691 which added an "Edit Form" link to the top of all Afforms, even those that cannot be edited in the GUI.

This removes the "Edit" link from non-editable forms, and adds the current form back into the breadcrumbs, for the sake of forms which use url params for routing.

While I was at it, I also added a breadcrumb to SearchKit when viewing a search display (standalone).

Before
----------------------------------------
image

After
----------------------------------------
image

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw can we be sure type will always be set - I'm seeing an enotice on this

image

**Comment by colemanw** [comment]
Guess not. I've wrapped it in `isset()` now.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
Ok this works  - I don't know if the 'edit form' bit on the search breadcrumb in entirely intuitive (clicking on edit form takes you to edit but the level below it takes you to view) - but I'm guessing there is a reason for that approach?

image

**Comment by colemanw** [comment]
Well for multi-page forms, the view link ("Camera Peeps" in your screenshot) is for taking you back to the front. It's needed e.g. for the `Afform Html Editor` to return from editing a specific form back to the main list.

**Comment by eileenmcnaughton** [comment]
OK - well I agree it does maintain a link to editing without leaving the afform crumbs broken

**Pull request merged**
