### PR TITLE
CRM-21664 Modified--getting currencies from civicrm_currency table instead bein…

### PR DESCRIPTION
**Pull request by sunnycs121**
Modified file CRM/Core/PseudoConstant.php -- getting currencies from civicrm_currency table instead being hard-coded. [CRM-21664](https://issues.civicrm.org/jira/browse/CRM-21664)

Before
----------------------------------------
Currencies were hardcoded and were missing some currencies like Serbian Dinar, code: RSD and when any contribution with that currency was tried to be created it resulted in error:
"error_message": "Currency not a valid code: "

After
----------------------------------------
All currencies in modification are being pulled from database table civicrm_currency instead of hardcoded.

Comments
----------------------------------------
Test by creating a contribution through API call mentioned in Jira [issue](https://issues.civicrm.org/jira/browse/CRM-21664).

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins ok to test

**Comment by seamuslee001** [comment]
This looks sane to me. I haven't tested this yet but seems sensible ping @monishdeb @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
OK I agree with this - there are at least 4 different currencies used in the test suite so I think we are covered on it

**Comment by seamuslee001** [comment]
@eileenmcnaughton @monishdeb Tests have passed now and I agree with Eileen that we probably have enough unit tests already to cover this

**Comment by eileenmcnaughton** [comment]
Merged - I think this was your first PR merged?

**Comment by sunnycs121** [comment]
@eileenmcnaughton Yes this was my first one.

**Comment by eileenmcnaughton** [comment]
Well done then - we need a pretty badge or something :-)

**Pull request merged**
