### PR TITLE
(WIP) CRM-16421 CRM-17633 Changes to support WP in it's own directory R…

### PR DESCRIPTION
**Pull request by kcristiano**
…eplaces PR#8536

### CODE REVIEW

**Comment by kcristiano** [comment]
test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@kcristiano Kevin where is this at now?

**Comment by kcristiano** [comment]
@seamuslee001 this has been tested along with https://github.com/civicrm/civicrm-wordpress/pull/105.  However, the installer needs to be updated to get around manual steps detailed here 
https://wiki.civicrm.org/confluence/display/CRM/WordPress+installed+in+its+own+directory+issues  in the Next Steps section.  

4.7.13 is ambitious (unless someone at Edale wants to work on this) but by 4.7.14 this should be ready.

**Comment by kcristiano** [comment]
jenkins test this please

**Comment by kcristiano** [comment]
I've tested this and https://github.com/civicrm/civicrm-wordpress/pull/105 against current master.   PR still works as advertised.   I'd like to get this on a release track so we can thoroughly test

**Comment by kcristiano** [comment]
jenkins test this please

**Comment by kcristiano** [comment]
Rebased and replaced this PR with https://github.com/civicrm/civicrm-core/pull/10214

**Pull request closed without merging**
