### PR TITLE
dev/core#4419 - Crash on membership tab of contribution page config (should go into 5.64)

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/4419

Before
----------------------------------------
1. php8 - open membership tab in contribution page config
2. crash

After
----------------------------------------

Technical Details
----------------------------------------
Pretty much the same as https://github.com/civicrm/civicrm-core/pull/26517

Comments
----------------------------------------

### CODE REVIEW

**Comment by larssandergreen** [comment]
Not again! Works for me, good to go.

**Comment by demeritcowboy** [comment]
Actually wait I think this needs to be 5.63. I'm getting confused about what version is what now.

**Comment by demeritcowboy** [comment]
Ok so the issue started in 5.63, but this master is now the RC, so this is right, and then it needs to be backported after to 5.63.

**Comment by colemanw** [comment]
Thanks @demeritcowboy can you also open a PR for the backport?

**Comment by demeritcowboy** [comment]
Backport: https://github.com/civicrm/civicrm-core/pull/26759

**Pull request merged**
