### PR TITLE
CRM-19793 Redirect payment processors that fail result in ugly fatal …

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
…- be prettier

### CODE REVIEW

**Comment by magnolia61** [comment]
I tried this patch and it now throws a decent error message instead of the ugly fatal. nice change

**Review by xurizaemon — COMMENTED** [review]
Feels like as well as redirecting, we should record the failure to debug log here? Otherwise the only evidence is clientside - no records for debugging "why were some payments failing after X change was made?" later.

**Comment by eileenmcnaughton** [comment]
There should be a pending contribution left hanging around to give a clue. But I think the payment processor should be responsible for logging more detail - in the case I've been dealing with there does seem to be info in the system_log table

**Comment by eileenmcnaughton** [comment]
NB - I would like to merge this if you feel you have looked at it carefully enough. Richard has tested it per his comment

**Comment by xurizaemon** [comment]
Suggest adding a `CRM_Core_Error::debug_log_message()` or equivalent to report that the attempt failed before merging.

**Comment by eileenmcnaughton** [comment]
You should be able to push a commit to my branch - I'm sure you have permission

**Comment by xurizaemon** [comment]
sure, but it's one line and you i'm guessing know how to test this - are you sure it'll be faster to wait for me to get set up and able to reproduce that problem?

**Comment by xurizaemon** [comment]
> I'm sure you have permission

nope

Now #9762 instead

**Pull request closed without merging**
