### PR TITLE
Added Pseudoconstant for foreign key table columns

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
Added Pseudo-constant for Country, State and World region foreign key so that api can render this field when passed using name.

### CODE REVIEW

**Comment by colemanw** [comment]
I'm not sure about this change. Declaring both a pseudoconstant AND an FK doesn't seem like a great practice. I think we should generally just do one or the other.

**Comment by pradpnayak** [comment]
@colemanw if you pass state_province_id => 'Goa' in County API in create mode it doesn't accept and throws error as invalid  state_province_id. Adding Pseudoconstant accepts using name in such fields.

**Comment by colemanw** [comment]
Hmm, what about ambiguous ones? What if there was a state in the US or a province in Canada called "Goa"?

**Comment by pradpnayak** [comment]
hmm Agreed. So we will always need to pass id through api where machine name is not only unique column in table. 

I am closing this as it makes sense to use id over name.

**Pull request closed without merging**
