### PR TITLE
CRM-18236: Broadened selection criteria so that contacts who...

### PR DESCRIPTION
**Pull request by universalhandle**
Overview
----------------------------------------
Broadened selection criteria so that contacts who have
received a non-recurring reminder in the past (e.g., for LAST year's
membership) can be included. Necessitated adding protection against
multiple sends in the same day.

Before
----------------------------------------
See symptoms reported on the bug. Additionally, we found that the second year in an annual membership expiration reminder under-sent, excluding contacts reminded last year.

After
----------------------------------------
Made the logic smarter so we could both include the inappropriately excluded contacts and prevent multiple sends in the same day (in case someone configures the scheduled job to run more than once daily).

Comments
----------------------------------------
Patch made against RC branch as we feel this is a regression introduced by pull requests which sought to solve duplicate sends.

---

 * [CRM-18236: Scheduled reminder sends multiple reminders when reference date has changed](https://issues.civicrm.org/jira/browse/CRM-18236)

### CODE REVIEW

**Comment by totten** [comment]
(*CiviCRM Review Template WORD-1.0*)



* ([`r-jira`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-jira)) __Pass__
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __Issue__: PR seems to cause ~25 test failures in the same subsystem.
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __Pass__
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __Pass__
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __Mixed__: It's pretty hard to get one's head around all the scenarios for scheduled reminders, so (personally) I have a policy of doing TDD for that. However, RC's and recent-regressions sometimes require quick action, so adding new tests isn't a hard requirement.
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __Unreviewed__: 
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __Unreviewed__: 
* ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __Mixed__: Given history of TDD for this subsystem, and given that it doesn't change the data-model or API-model, I'd say 👍 as long it passes the tests.

**Comment by GinkgoFJG** [comment]
Jenkins, test this please

**Comment by GinkgoFJG** [comment]
Retesting as I spot-checked some failing tests locally and they passed.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@GinkgoFJG this has not really been reviewed for the rc in good time. Can you explain what the changes that caused a regression were (mostly in terms of time frames - if this is a 'recent regression' )we need to figure out how to get it sorted into the rc. Otherwise we should redo against master & perhaps push harder on the tests

**Comment by totten** [comment]
I'm also not clear on why this is on the RC, and it seems we haven't made the window. Reassigning to `master`.

**Comment by eileenmcnaughton** [comment]
So looking at this & it's too old to count as a recent regression & may have been addressed in the meantime. It also seems a lot more like a long-standing issue than a regression.

I don't believe this should be merged without a unit test & given that the unit test is probably the largest part of this work this should probably be closed if no-one wants to write that test, until someone writes one & it is reviewable.

OTOH it is an issue that a lot of people may have an interest in so @seamuslee001 @monishdeb @jitendrapurohit @davejenx - one of you might be prepared to take the extra steps to get this to the point where it can be reviewed

On the other hand it might finally be a fix to the

**Comment by eileenmcnaughton** [comment]
@GinkgoFJG per above I'm going to close this out for now because it's not really reviewable without a unit test & it is far too old to get a recent regression escalation

**Pull request closed without merging**
