### PR TITLE
Fix core#1026 where an email address synced from a CMS contact is created with no location field.

### PR DESCRIPTION
**Pull request by aydun**
Overview
----------------------------------------
Fix core#1026 where an email address synced from a CMS contact is created with no location field.

Before
----------------------------------------
An email address synced from a CMS contact has no location field

After
----------------------------------------
An email address synced from a CMS contact has a location field which is the current default LocationType

Technical Details
----------------------------------------
Adds a default for `location_type_id` in the API Email.create

Comments
----------------------------------------
See https://lab.civicrm.org/dev/core/issues/1026

### CODE REVIEW

**Comment by colemanw** [comment]
I think this solution is adequate for api3, but for api4 I'd like to cover all entities with this field.
Let's see if after merging https://github.com/civicrm/org.civicrm.api4/pull/162 we can adjust this new unit test of yours to run on both versions.

**Comment by aydun** [comment]
@colemanw Great - I had a quick look at api4 but didn't see an obvious way to add defaults.
I've pulled the latest api4 master with your change and changed the test to include v4 but I get: Failed asserting that null matches expected '1'.

**Comment by colemanw** [comment]
@aydun I've merged that PR now so the defaults will be set. You will need to clear your caches though, since it relies on a provider that gets cached in the civi container.

**Comment by colemanw** [comment]
I've pushed up the change to cover api4 in the test. Merge on pass.

**Pull request merged**
