### PR TITLE
Switch to using new crmPermission block

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Switch to using new crmPermission block

Before
----------------------------------------
deprecated use of `call_user_func_array` in the tpl file

After
----------------------------------------
Use of new `crmPermission` block

Technical Details
----------------------------------------

Before we fully go down this path I want to question which signature we prefer...

1) Current
```
{crmPermission permission='access CiviCRM' not='access CiviCRM Event'}
  blah
{/crmPermssion}
```

Or more matching
```
{crmPermission has='access CiviCRM' has_not='access CiviCRM Event'}
  blah
{/crmPermssion}
```

Or suggested by @colemanw just now
```
{crmPermission has='access CiviCRM' not='access CiviCRM Event'}
  blah
{/crmPermssion}
```

Comments
----------------------------------------
@mattwire @demeritcowboy @seamuslee001 @colemanw @totten - get your bikes out

### CODE REVIEW

**Comment by demeritcowboy** [comment]
I no longer have a bike and my shed is a bit run down, but I vote for `{canHas item="cheezburger"}`

**Comment by eileenmcnaughton** [comment]
Thanks for the constructive and thoughtful input @demeritcowboy :-)

**Comment by demeritcowboy** [comment]
It seems like it would be uncommon, and confusing, to have both `has` and `not` in the same block? I'm thinking for clarity they should be two different blocks, and anything more complex should be assigned to a smarty var in the corresponding php. Or equivalently disallow having both `has` and `not` in the same call.

**Comment by colemanw** [comment]
@demeritcowboy I agree it would be uncommon, but I don't find it confusing. We may be arguing about a scenario that will never happen, so I'm not sure the outcome matters, but IMO it would be fine to support both in the same call. The logic is simply "WITH this perm AND WITHOUT that perm".

**Comment by eileenmcnaughton** [comment]
@colemanw @demeritcowboy this should be right now with the new 'has'  I did document the new crmPermission https://docs.civicrm.org/dev/en/latest/framework/templates/#smarty-templates-introduction

**Pull request merged**
