### PR TITLE
CRM-18128 Return more rows per query and use unbuffered query to mana…

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
…ge the memory

The Limit was set in order to protect memory use. However, if means running often slow queries many times for large exports .. trying another way

### CODE REVIEW

**Comment by monishdeb** [comment]
Tested, working fine. BUT do you think we should define this constant in civicrm.setting.php file so that admin can override the count as per his need ?

**Comment by eileenmcnaughton** [comment]
Yeah potentially - it's still pretty arbitrary - the other question is whether a limit is required at all - I'd be inclined to revisit again if someone feels it's worth doing later

**Comment by eileenmcnaughton** [comment]
I rebased & repushed this - but it was just to remove the internal change id from the commit message - no other change. @monishdeb good to merge?

**Comment by monishdeb** [comment]
Yup

**Pull request merged**
