### PR TITLE
Add custom search handling for jcalendar converstion.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Last activity custom search and event aggregate custom search have been updated to use jcalendar - this just handles any smart groups based on them

Before
----------------------------------------
Pre-update smart groups don't work

After
----------------------------------------
smart groups work

Technical Details
----------------------------------------
I used the methodology from ContribSybunt. I duplicated rather than
shared it because I think the future of these searches is to be more separated from each other

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
I am comfortable that all we are doing is extending a known pattern i have not r-run this yet but i think this method has been proven to be fine @monishdeb @mattwire

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
seem unrelated

Test Result (2 failures / -2)
E2E_Extern_RestTest::testAPICalls.testAPICalls with data set #0
E2E_Extern_SoapTest.testGetContact

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by monishdeb** [comment]
I agree with the patch and we are already doing the same for ```CRM/Contact//Form/Search/Custom/ContribSYBNT.php```. That makes me to think, how about moving the function to parent class. Which would be:
```patch
diff --git a/CRM/Contact/Form/Search/Custom.php b/CRM/Contact/Form/Search/Custom.php
index d6de166cdd..bfef076994 100644
--- a/CRM/Contact/Form/Search/Custom.php
+++ b/CRM/Contact/Form/Search/Custom.php
@@ -205,4 +205,23 @@ class CRM_Contact_Form_Search_Custom extends CRM_Contact_Form_Search {
     return TRUE;
   }
 
+  /**
+   * Format saved search fields for this custom group.
+   *
+   * Note this is a function to facilitate the transition to jcalendar for
+   * saved search groups. In time it can be stripped out again.
+   *
+   * @param array $formValues
+   *
+   * @return array
+   */
+  public static formatSavedSearchFields($formValues, $dateFields = ['start_date', 'end_date']) {
+    foreach ($formValues as $element => $value) {
+      if (in_array($element, $dateFields) && !empty($value)) {
+        $formValues[$element] = date('Y-m-d', strtotime($value));
+      }
+    }
+     return $formValues;
+  }
+
 }
diff --git a/CRM/Contact/Form/Search/Custom/ActivitySearch.php b/CRM/Contact/Form/Search/Custom/ActivitySearch.php
index b2dc8e1694..ae169b2208 100644
--- a/CRM/Contact/Form/Search/Custom/ActivitySearch.php
+++ b/CRM/Contact/Form/Search/Custom/ActivitySearch.php
@@ -42,8 +42,7 @@ class CRM_Contact_Form_Search_Custom_ActivitySearch extends CRM_Contact_Form_Sea
    * @param array $formValues
    */
   public function __construct(&$formValues) {
-    $this->_formValues = $formValues;
-
+    $this->_formValues = self::formatSavedSearchFields($formValues);
     /**
      * Define the columns for search result rows
      */
@@ -429,4 +428,8 @@ ORDER BY contact_a.sort_name';
     list($this->_aclFrom, $this->_aclWhere) = CRM_Contact_BAO_Contact_Permission::cacheClause($tableAlias);
   }
 
+  public static function formatSavedSearchFields($formValues) {
+    return CRM_Contact_Form_Search_Custom::formatSavedSearchFields($formValues);
+  }
+
 }
diff --git a/CRM/Contact/Form/Search/Custom/ContribSYBNT.php b/CRM/Contact/Form/Search/Custom/ContribSYBNT.php
index 8a8703800d..f20a8f6f31 100644
--- a/CRM/Contact/Form/Search/Custom/ContribSYBNT.php
+++ b/CRM/Contact/Form/Search/Custom/ContribSYBNT.php
@@ -413,13 +413,7 @@ AND      c.receive_date < {$this->start_date_1}
       'exclude_start_date',
       'exclude_end_date',
     );
-    foreach ($formValues as $element => $value) {
-      if (in_array($element, $dateFields) && !empty($value)) {
-        $formValues[$element] = date('Y-m-d', strtotime($value));
-      }
-    }
-
-    return $formValues;
+    return parent::formatSavedSearchFields($formValues, $dateFields);
   }
 
```

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@monishdeb I kinda hung off that per the technical details section just because I didn't want to bed it in too much as I hoped it would be kinda temporary - actually I kinda hope the reports themselves won't be in core for that long...

**Comment by monishdeb** [comment]
Hmm ok then. Sorry I missed the Technical Details. 
I am marking it as merge-ready as @seamuslee001 and I find the patch safe to merge. I have tested it in my local and it worked fine for EventAggregate and ActivitySearch. Still good to have @mattwire feedback. 

But I will wait till tomorrow before merge.

**Comment by mattwire** [comment]
I've just run this and can confirm that it fixes the custom searches.  I too would like to see @monishdeb suggestion of adding to the parent class.  If/when we remove reports we can easily copy that function out and it means just adding it to core once (and later removing it) instead of 5 times over.

**Comment by eileenmcnaughton** [comment]
@mattwire @monishdeb I actually agree with you - but I won't get back to this before the rc is cut & I kinda want to focus on the approach for the non-custom search fields - so perhaps it's best to just merge this so the rc can have it?

**Comment by seamuslee001** [comment]
It has been a day and the PR is marked as merge ready, I don't see Matt's comment as a blocker to this being merged. I'm going to merge it given it works but we can look for consolidation in the next round

**Pull request merged**
