### PR TITLE
CRM-19653: Custom field checkboxes migrated incorrectly on merge (part deux)

### PR DESCRIPTION
**Pull request by monishdeb**
* [CRM-19653: Custom field checkboxes migrated incorrectly on merge \(part deux\)](https://issues.civicrm.org/jira/browse/CRM-19653)

### CODE REVIEW

**Comment by JKingsnorth** [comment]
Reviewed on JIRA - this currently resolves one part of the issue.

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by JKingsnorth** [comment]
Thanks again for your work on this @monishdeb

**Comment by monishdeb** [comment]
@JKingsnorth thanks :)

**Pull request merged**
