### PR TITLE
(dev/core#1065) fix condition so that the contact field appears for s…

### PR DESCRIPTION
**Pull request by yashodha**
…tandalone/tab context for create mode

Overview
----------------------------------------
Fix condition so that the contact field appears for standalone/tab context for create mode
Go to Contact, click Grant tab, and add a new grant.

Before
----------------------------------------
No display name visible.
grant_before

After
----------------------------------------
Contact X is display properly in frozen format and can be submitted as well.

grant_after

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@yashodha this seems broken before and after for me

Before

Screen Shot 2019-09-06 at 8 55 03 AM


After
Screen Shot 2019-09-06 at 9 26 23 AM

**Comment by eileenmcnaughton** [comment]
Side notes
1) I'm ok with no test as this is form display
2) We should get this into 5.18 with the other patch
3) test fail is unrelated

**Comment by yashodha** [comment]
@eileenmcnaughton 
This is now working and I have updated the description with screenshots as well.

**Comment by eileenmcnaughton** [comment]
@yashodha I just tried to switch it to 5.18 now we have forked - but it needs a rebase

**Comment by eileenmcnaughton** [comment]
Ok - I did this https://github.com/civicrm/civicrm-core/pull/15238 to roll it on 5.18 so closing this as it's  merged

**Pull request closed without merging**
