### PR TITLE
CRM-21069 Fix crash when event_id is not set

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
If the user has an event registration but the event has been deleted CiviCRM crashes with a CRM_Core_Error::fatal because the event search still tries to lookup the event details.  This patch checks the event_id is set, and skips the registration if it is not.

Before
----------------------------------------
CiviCRM crashes with CRM_Core_Error::fatal()

After
----------------------------------------
CiviCRM shows all event registrations that have valid events.

Technical Details
----------------------------------------
It is unlikely to happen unless data has been modified directly in the database.

---

 * [CRM-21069: Check event ID exists before calling CRM_Event_BAO_Event::isMonetary](https://issues.civicrm.org/jira/browse/CRM-21069)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
(looks like an unrelated fail)

**Comment by MegaphoneJon** [comment]
I just reviewed this and confirm that it makes sense both at a code level, and that I was able to replicate the bug and confirm it's fixed by this patch.

FWIW, foreign keys/cascading deletes mean that this scenario really shouldn't ever happen.  I had to disable foreign key checks to replicate this bug - but better in than out, I suppose.

**Comment by eileenmcnaughton** [comment]
This makes me uncomfortable - handling data errors rather than forcing people to fix it. @colemanw @totten what are your thoughts? One one hand this is safe & fixes an experienced problem. On the other hand I feel like if people mess up their data we shouldn't 'just work anyway'.

**Comment by mattwire** [comment]
@eileenmcnaughton I totally agree there shouldn't be bad data, but sometimes there is!  In this case the impact without this patch is you cannot access the contact event tab at all, as it dies with a "fatal" and no reason why. With the patch the system continues working, without displaying the corrupt event registrations.  I've just updated the patch to write a warning to the log file if this happens - so a sysadmin is made aware it should be fixed.

**Comment by eileenmcnaughton** [comment]
ok this is a pretty rare event & while not ideal it does help in some circumstance - I think enough time has gone on it now - merging

**Pull request merged**
