### PR TITLE
core-54 - Activity created for case role relationship is not assigned…

### PR DESCRIPTION
**Pull request by jitendrapurohit**
… to correct contact

Overview
----------------------------------------
Activity created for case role relationship is not assigned to correct contact.

Before
----------------------------------------
Add a role for a case. The activity created is assigned to the client instead of the relationship contact. Details on the issue link.

After
----------------------------------------
Activity is created for correct contact.

Comments
----------------------------------------
Added unit test.

--------

GitLab Issue - https://lab.civicrm.org/dev/core/issues/54

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
jenkins, retest this please

**Comment by eileenmcnaughton** [comment]
@lcdservices   -  patch seems good (has a test, limited change) but I don't know how to assess if the behaviour change is correct - do you have an opinion - or @guanhuan

**Comment by lcdservices** [comment]
I agree with what this does and tested the patch -- it's working as intended.

One comment --
With the corrected behavior, the activity source is the logged in user, activity assignee is the person assigned the role, and the target is left empty. I think the target should be the case contact. (to be clear, that is the behavior with/without this patch -- this commit doesn't affect the target value)

I think if we're going to fix the issue with the assignee we should also look at fixing the target value (assuming there's agreement that it should be linked to the case contact).

**Comment by eileenmcnaughton** [comment]
I'm going to merge this based on @lcdservices & the straightforwardness & testedness of the patch 

@jitendrapurohit please consider the further suggestion & a follow up patch to address it.

**Pull request merged**
