### PR TITLE
[REF] Move another deprecated function back to the only class that calls it

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
[REF] Move another deprecated function back to the only class that calls it

Before
----------------------------------------
Screenshot from 2021-01-01 09-51-27

After
----------------------------------------
Function relocated to the class that calls it

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by demeritcowboy** [comment]
`r-code`: PASS
`r-run`: PASS

**Pull request merged**
