### PR TITLE
Add ContributionProduct and EntityBatch APIv4 Entity

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Add ContributionProduct and EntityBatch APIv4 Entity

Technical Details
----------------------------------------
I want to raise two points: 

1.  Found that the ContributionProduct.product_id is missing foreign key attribute, will add a separate PR to add that. 
2.  Not sure if we need add pseudoconstant property on EntityBatch.entity_table as I am not sure if it contain finite number of table list, right now I can think of civicrm_financial_trxn and civicrm_contact. 

Comments
----------------------------------------
ping @colemanw @eileenmcnaughton @seamuslee001

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@monishdeb I thought entity_batch was used for the batch entry screen - ie the screen altered by this pr https://github.com/civicrm/civicrm-core/pull/20394 & could hold contribution & membership

**Comment by eileenmcnaughton** [comment]
api\v4\Entity\ConformanceTest::testConformance with data set "EntityBatch" ('EntityBatch')
Exception: At least one Batch is required in test

**Comment by monishdeb** [comment]
> @monishdeb I thought entity_batch was used for the batch entry screen - ie the screen altered by this pr #20394 & could hold contribution & membership

@eileenmcnaughton to reconfirm I did a membership & contribution batch entry and clicked 'Save & Continue Later' but that doesn't populate the entity_batch table. But if you do 'Accounting Batch Entry' it does populate the entity_batch table financial_trxn entries and not sure in which case civicrm_contact entries are populated in this table.

**Comment by eileenmcnaughton** [comment]
@monishdeb I think that adding a pseudoconstant would ONLY affect apiv4 - so it should be Ok to only add the one you know to be true - the contact one seems odd

**Comment by monishdeb** [comment]
> @monishdeb I think that adding a pseudoconstant would ONLY affect apiv4 - so it should be Ok to only add the one you know to be true - the contact one seems odd

Ok will add the pseudoconstant then. regarding contact, its the description about the entity_table [here](https://github.com/civicrm/civicrm-core/blob/master/CRM/Batch/DAO/EntityBatch.php#L124) tells about that civicrm_contact could be one of the entity_table, but not sure when the civicrm_entity_batch is used to hold contact entries. 

On the otherhand, I will also submit a separate PR to make civicrm_contribution_product.product_id foreign key to civicrm_product.id (on delete null).

**Comment by eileenmcnaughton** [comment]
@monishdeb do you it was maybe 'just a good idea' at some point? Perhaps we should merge directly after the rc is cut to be careful but I have doubts about including contact if it's not really possible to populate as that

@demeritcowboy you are our sleuth.... can you find any want for civicrm_entity_batch.entity_table to be anything other than civicrm_financial_trxn ?

**Comment by monishdeb** [comment]
jenkins test this please

**Comment by monishdeb** [comment]
I have addressed point 1) under the Technical Details and submitted a PR for that https://github.com/civicrm/civicrm-core/pull/20553

**Comment by demeritcowboy** [comment]
I've seen 3 things that use the word batch:

* Accounting batches, which are effectively an "export" with tracking so you don't export the same twice.
  * batch and entity_batch, with entity_table civicrm_financial_trxn
* Batch entry for contributions etc, which are effectively an "import".
  * Data here gets stored in civicrm_batch. The whole thing is stored in the data column. @monishdeb you're right that "save and continue later" doesn't use entity_batch, but if you go on to "validate and process" then it DOES also store a record in civicrm_entity_batch with entity_table civicrm_financial_trxn. One reason being that you can re-use these for "export" later as pre-made accounting batches.
* Batch update via profile - the action on search results screens
  * This isn't really the same type of "persistent" batch.

I don't see anything obvious where entity_batch is used for non-financial-transaction, but there's nothing that says it couldn't be used by an extension for such. It seems there was an intent to allow it, but maybe nothing actually uses it for contacts etc:

* https://issues.civicrm.org/jira/browse/CRM-6894
* https://github.com/civicrm/civicrm-svn/commit/93805ed11f6b0b35526be6ad405d4ac549a6d700#diff-2a211839353e146fa0b11f2984fe318f7754d78c664126b7a4e862ee8fa86fe2
* https://issues.civicrm.org/jira/browse/CRM-9834

It mentions Gift Aid - does someone know if that uses it for something other than financial?

**Comment by eileenmcnaughton** [comment]
@demeritcowboy @monishdeb I don't think resolving the pseudoconstant is a blocker on merging this.

However, I found that giftaid [DOES](https://github.com/compucorp/uk.co.compucorp.civicrm.giftaid/blob/66ddb31f5308da1370f89cb679b3f77e9a8ba006/CRM/Civigiftaid/Utils/Contribution.php#L628) use this table with civicrm_contribution.

I feel like we can somewhat rule out civicrm-contact based on discussion so far -but there DOES seem to be a need for extensions to edit what is supported.

At the moment I'm leaning towards using an option group - I'm gonna see if @totten @colemanw @seamuslee001 have thoughts

**Comment by eileenmcnaughton** [comment]
I've transferred the above ^^ to https://lab.civicrm.org/dev/core/-/issues/2682 and am merging this - let's discuss over there

**Pull request merged**
