### PR TITLE
CRM-19960 Hide page title when is supposed to be removed

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @jackrabbithanna @VasanthaKaje

---

 * [CRM-19960: Drupal 8 Standard Page title does not immediately disappear on contact record screen](https://issues.civicrm.org/jira/browse/CRM-19960)

### CODE REVIEW

**Comment by colemanw** [comment]
Can you explain what's happening? Is the html getting escaped so that we literally see the `<span id="crm-remove-title" ...` as the page title?

**Comment by seamuslee001** [comment]
@colemanw that is correct in D8 it is treating it as a plain string as per https://api.drupal.org/api/drupal/core!modules!node!src!Entity!Node.php/function/Node%3A%3AsetTitle/8.2.x

**Comment by jackrabbithanna** [comment]
@seamuslee001 @eileenmcnaughton 

I've tested this and it works for me. I recommend merging

**Review by jackrabbithanna — COMMENTED** [review]
works for me, its good to go

**Pull request merged**
