### PR TITLE
dev/drupal#7 : Implement universal civicrm.config.php 

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
The file `civicrm.config.php` is currently produced by GenCode, and it's required by various backend scripts (extern/* and bin/*). A naive approach might be to simply commit this file -- however, that's problematic because there are ~4 variants of this file (for civicrm-drupal, civicrm-wordpress, civicrm-joomla, and civicrm-backdrop). Please check the 'Technical Details' for the approach taken here to resolve this.

Technical Details
----------------------------------------
Following changes are made in this PR:
1. In .gitignore, simply rename civicrm.config.php to civicrm.config-generated.php as this the new file that will be generated via GenCode. Additional changes are made in config gencode. 
2. Existing file civicrm.config.php is now part of the Civi codebase and now call desired config file as per fall back policy i.e. if CIVI_BOOT variable is set in environment OR civicrm.config-generated.php doesn't exist then call the universal `CmsBootstrap.php` that uses [CMS-first boot protocol](https://lab.civicrm.org/dev/cloud-native/issues/7). 
3. Copy [Cv/CmsBootstrap](https://github.com/civicrm/cv/blob/master/src/CmsBootstrap.php) and [Cv/Encoder](https://github.com/civicrm/cv/blob/master/src/CmsBootstrap.php) in Civi

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@totten @monishdeb what does this require?

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by monishdeb** [comment]
Seems like its failing on test build due to the current change. I will investigate further and fix the remaining issues. For the time being I am marking this PR with WIP

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by mlutfy** [comment]
I'm a bit confused by the rest results (related to the REST endpoint?).

**Comment by monishdeb** [comment]
@mlutfy yes and earlier the external scripts at civicrm/exten/* fail to recognize or should I say, not working with the new generic config file. I tried hard to debug the cause but then taken over by other priority issues at my plate. The reason why I kept this PR on hold but will give another try this week.

**Comment by eileenmcnaughton** [comment]
@monishdeb I'll close this & let you re-open in later - it's been WIP for quite a long time now so better to not have in the queue until WIP related issues are resolved

**Pull request closed without merging**
