### PR TITLE
CRM-21789: 'Find Case' group by issue

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Steps to replicate:
1. Ensure that MySQL FULL_GROUP_BY_MODE is enabled
2. Empty submit the criteria of 'Find Cases' 

Before
----------------------------------------
The actual number of rows listed and the row count per page differs. In the screencast below, only 2 rows are listed despite having 10 counts per page:
test-multiple-before

After
----------------------------------------
The actual number of rows listed and the row count per page is equal now. In the screencast below, 10 rows are listed as per 10 counts per page:
test-multiple-after

---

 * [CRM-21789: 'Find Case' group by issue](https://issues.civicrm.org/jira/browse/CRM-21789)

### CODE REVIEW

**Comment by monishdeb** [comment]
ping @lcdservices @eileenmcnaughton @seamuslee001

**Comment by lcdservices** [comment]
This fixes the issue. Find case search now returns the correct number of results based on the count and pagination setting (number of records to list).

**Comment by colemanw** [comment]
* ([`r-jira`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-jira)) __Pass__
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __Pass__
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __Pass__
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __Pass__
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __Pass__
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __Pass__: By Brian
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __Pass__
* ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __Pass__: Test updated

**Comment by eileenmcnaughton** [comment]
So this means we are using GROUP_CONCAT rather than ANY_VALUE in the second query? My first thought looking was no no no ANY_VALUE is a hack - but I think you may be reducing the hack usage?

I am still concerned though that we are only fixing the query for mysql configs that report the query. To be clear - a query with group by is incorrect if it has fields that are in the select but not in the group by or the aggregate. Using ANY_VALUE is effectively like 'ignore this code error because we haven't managed to fix it properly or just possibly there is a real excuse for it'. Using GROUP_CONCAT is a real fix - because we know all values are returned. We shouldn't only offer the real fix for sites with mysql 5.7 or FULL GROUP BY - that's a bit like saying 'lets' fix all the e-notice identified bugs for the sites that have e-notice reporting enabled'.

I think we should be working towards dropping the if here CRM_Utils_SQL::disableFullGroupByMode()
to give the same queries in all cases. (that doesn't need to be this round but it should be our understood goal)

**Comment by monishdeb** [comment]
@eileenmcnaughton yes I am using GROUP_CONCAT in this case. Also from our last discussion I had in mind to create a separate JIRA ticket and there will be a lot of changes in this direction and might take some time fix em all. So here's the ticket - https://issues.civicrm.org/jira/browse/CRM-21794 

This is one of the priority issue for NYSS so I didn't felt that it would be appropriate to include the improvements as part of this PR.

**Pull request merged**
