### PR TITLE
dev/core#3760 add server side validation for formbuilder

### PR DESCRIPTION
**Pull request by kurund**
Overview
----------------------------------------
Adds a new `'civi.afform.validate'` event and implements a listener to validate required fields.

See: https://lab.civicrm.org/dev/core/-/issues/3760

### CODE REVIEW

**Comment by kurund** [comment]
It would be good to finish [this](https://github.com/civicrm/civicrm-core/pull/23604 for) before I handling server response on client side.

**Comment by colemanw** [comment]
@kurund please add a unit test for this.

**Comment by colemanw** [comment]
@kurund now that https://github.com/civicrm/civicrm-core/pull/23604 is merged can you please rebase this

**Comment by kurund** [comment]
@colemanw ready for your review

**Comment by colemanw** [comment]
I've refactored this to be event-driven so that other extensions (like ReCaptcha) can listen for the same `'civi.afform.validate'` event.

**Pull request merged**
