### PR TITLE
dev/financial#68: Check number doesn't get stored in associated financial_trxn record, if the contribution is made using 'Contribution/Membership batch data Entry' form

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Steps to replicate:

1. Create a Contribution or Membership Batch Data entry with any number of records.
2. Enter the check number and save the contribution(s).
3. Go to the contribution view page.

Before
----------------------------------------
Check number is missing under payment details section. Although contribution's check number is correctly set.

After
----------------------------------------
Check number is not missing under payment details section.

Technical Details
----------------------------------------
Changing the profile field name to check_number from obsolete name contribution_check_number. This led to proper processing of check number and storing it in respective place.  

ping @eileenmcnaughton @JoeMurray

### CODE REVIEW

**Comment by JoeMurray** [comment]
For release notes it might be useful to note when this change from contribution_check_number to check_number occurred.

**Comment by eileenmcnaughton** [comment]
@monishdeb is this a regression? If so can we target 5.18

**Comment by seamuslee001** [comment]
@eileenmcnaughton this likely changed when we change the field name in 4.7.17

**Comment by seamuslee001** [comment]
@monishdeb test failures relate

**Comment by eileenmcnaughton** [comment]
ah - ok master sounds fine

**Comment by seamuslee001** [comment]
@monishdeb I just tried on master via contributions -> Batch data entry and set the payment instrument to be check and it seems to have saved correctly as per the screenshots

batch1
batch2

Is there something i am missing?

**Comment by seamuslee001** [comment]
ok i think i understand now @monishdeb @JoeMurray  i have put up #15272 as an alternate to this PR as i think it is a much straight forward fix than this one

**Comment by seamuslee001** [comment]
closing in favour of #15272

**Pull request closed without merging**
