### PR TITLE
#469 - Error on action "Email - schedule/send via CiviMail" with mult…

### PR DESCRIPTION
**Pull request by francescbassas**
…iple event names filter

See https://lab.civicrm.org/dev/core/issues/469

### CODE REVIEW

**Comment by monishdeb** [comment]
Thanks @francescbassas for fixing this, but after digging down the code it seems like search criteria used to for "Email - schedule/send via CiviMail"  task, simply uses the submitted form values, not just the translated query params that happens on 'Advanced Search' postprocess.

To addess this problem, I present a patch:
```patch
diff --git a/CRM/Contact/BAO/Group.php b/CRM/Contact/BAO/Group.php
index e3a05617c7..72c23c478a 100644
--- a/CRM/Contact/BAO/Group.php
+++ b/CRM/Contact/BAO/Group.php
@@ -695,7 +695,7 @@ class CRM_Contact_BAO_Group extends CRM_Contact_DAO_Group {
     //create/update saved search record.
     $savedSearch = new CRM_Contact_BAO_SavedSearch();
     $savedSearch->id = $ssId;
-    $savedSearch->form_values = serialize(CRM_Contact_BAO_Query::convertFormValues($params['form_values']));
+    $savedSearch->form_values = serialize($params['form_values']);
     $savedSearch->mapping_id = $mappingId;
     $savedSearch->search_custom_id = CRM_Utils_Array::value('search_custom_id', $params);
     $savedSearch->save();
diff --git a/CRM/Contact/Form/Search/Advanced.php b/CRM/Contact/Form/Search/Advanced.php
index 5c7c53ed20..84be3fbf22 100644
--- a/CRM/Contact/Form/Search/Advanced.php
+++ b/CRM/Contact/Form/Search/Advanced.php
@@ -314,7 +314,7 @@ class CRM_Contact_Form_Search_Advanced extends CRM_Contact_Form_Search {
 
     CRM_Core_BAO_CustomValue::fixCustomFieldValue($this->_formValues);
 
-    $this->_params = CRM_Contact_BAO_Query::convertFormValues($this->_formValues, 0, FALSE, NULL, $this->entityReferenceFields);
+    $this->_formValues = $this->_params = CRM_Contact_BAO_Query::convertFormValues($this->_formValues, 0, FALSE, NULL, $this->entityReferenceFields);
     $this->_returnProperties = &$this->returnProperties();
     parent::postProcess();
   }
```
which will fix this issue and kinda improve my earlier fix https://github.com/civicrm/civicrm-core/pull/12910 

In the patch I am assigning the translated formValues to itself, and thus later used as saved criteria for a hidden smart group, that is used by the mail composer to fetch recipients.

**Comment by francescbassas** [comment]
Thanks @monishdeb, I can test your patch and it works perfect. I could not get this code with my digging and it really seems more appropriate. How do we keep going? I create a new PR with your patch? Take advantage of this one?

**Comment by monishdeb** [comment]
Cool. Well I would suggest you can make the changes in your existing branch ```patch-16```, then squash the new commit in old one and then force push commits to update this PR.
Here's the step:

```
$ commit -a -m "new commit message"
$ git rebase -i 
// next on edit screen, edit the 'pick' to 'squash' against last commit and save
$ git push -f origin patch-16
```

Or you can submit a new PR and I would be happy to review that.

One thing I forgot to mention, in my earlier PR if you have noticed ```$this->entityReferenceFields``` which contain special fields whose values need to be translated into query format. One of the special field is ```event_id```,which is the same field causing the issue here.

**Comment by monishdeb** [comment]
Great 😄👍 

Unfortunately, there's a test failure which seems related. Can you please check that?

**Comment by francescbassas** [comment]
CRM_Contact_BAO_GroupTest.testHiddenSmartGroup it's failing.

The test was commited [here](https://github.com/civicrm/civicrm-core/commit/4f3d62b9af9c3c4e8c798015ebea4059b49f1e9c#diff-e374f944d2fa3d1d530f1a7dca9768b2) by @monishdeb 

In the same commit you modify [line 684 CRM/Contact/BAO/Group.php](https://github.com/civicrm/civicrm-core/commit/4f3d62b9af9c3c4e8c798015ebea4059b49f1e9c#diff-0c52165f4315aa7744670ba4fdc615c2R684) in the opposite way you sugggested for [this patch](https://github.com/civicrm/civicrm-core/pull/13250/files#diff-0c52165f4315aa7744670ba4fdc615c2L698).

This escapes my understanding.

**Comment by monishdeb** [comment]
@francescbassas the failure makes sense. As I said earlier, as now we are passing translated version of the form values, to be saved as search criteria, that is later used by hidden-smart group to fetch recipients. The added test by me needs the same treatment and it was suppose to fail because we are simply passing the formValues as it is. This will fix the test failure:

```patch
diff --git a/tests/phpunit/CRM/Contact/BAO/GroupTest.php b/tests/phpunit/CRM/Contact/BAO/GroupTest.php
index d6128fc333..8ddd131761 100644
--- a/tests/phpunit/CRM/Contact/BAO/GroupTest.php
+++ b/tests/phpunit/CRM/Contact/BAO/GroupTest.php
@@ -252,9 +252,10 @@ class CRM_Contact_BAO_GroupTest extends CiviUnitTestCase {
 
     $contactID = $this->individualCreate(['custom_' . $customFieldID => 'abc']);
 
+    $formValues = ['custom_' . $customFieldID => ['LIKE' => '%a%']];
     $hiddenSmartParams = [
       'group_type' => ['2' => 1],
-      'form_values' => ['custom_' . $customFieldID => ['LIKE' => '%a%']],
+      'form_values' => CRM_Contact_BAO_Query::convertFormValues($formValues),
       'saved_search_id' => NULL,
       'search_custom_id' => NULL,
       'search_context' => 'advanced',
```

**Comment by francescbassas** [comment]
Great! All checks have passed.

**Comment by francescbassas** [comment]
@monishdeb is there something missing or can it be merged?

**Comment by monishdeb** [comment]
@francescbassas absolutely not. Sorry I missed it and earlier I was waiting for the tests to pass. Happy with the final change, merging now. Good work 👍

**Comment by francescbassas** [comment]
Thanks @monishdeb and Merry Christmas ;)

**Comment by monishdeb** [comment]
Merry Christmas 🎅

**Comment by eileenmcnaughton** [comment]
@monishdeb this has led to the regression described in https://lab.civicrm.org/dev/core/issues/671

**Comment by eileenmcnaughton** [comment]
@monishdeb so the issue is that the variable $entityReferenceFields that is passed in is empty when called from createHiddenSmartGroup

**Comment by eileenmcnaughton** [comment]
@monishdeb I have an alternate fix - will put up as a PR once the revert is merged through

```
diff --git a/CRM/Contact/Form/Task.php b/CRM/Contact/Form/Task.php
index a8b9691776..c17e6efe14 100644
--- a/CRM/Contact/Form/Task.php
+++ b/CRM/Contact/Form/Task.php
@@ -507,6 +507,7 @@ class CRM_Contact_Form_Task extends CRM_Core_Form_Task {
   public function createHiddenGroup() {
     // Did the user select "All" matches or cherry-pick a few records?
     $searchParams = $this->controller->exportValues();
+
     if ($searchParams['radio_ts'] == 'ts_sel') {
       // Create a static group.
       $randID = md5(time() . rand(1, 1000)); // groups require a unique name
@@ -544,7 +545,9 @@ class CRM_Contact_Form_Task extends CRM_Core_Form_Task {
       $ssId = $this->get('ssID');
       $hiddenSmartParams = array(
         'group_type' => array('2' => 1),
-        'form_values' => $this->get('formValues'),
+        // queryParams have been preprocessed esp WRT any entity reference fields - see
+        // https://github.com/civicrm/civicrm-core/pull/13250
+        'form_values' => $this->get('queryParams'),
         'saved_search_id' => $ssId,
         'search_custom_id' => $this->get('customSearchID'),
         'search_context' => $this->get('context'),

```

**Notes from diagnosis:**


 here is what happens in the main create smart group flow

```
    $queryParams = $this->get('queryParams');

    // Use the query parameters rather than the form values - these have already been assessed / converted
    // with the extra knowledge that the form has.
    // Note that we want to move towards a standardised way of saving the query that is not
    // an exact match for the form requirements & task the form layer with converting backwards and forwards.
    // Ideally per CRM-17075 we will use entity reference fields heavily in the form layer & convert to the
    // sql operator syntax at the query layer.
    if (!$isSearchBuilder) {
      CRM_Contact_BAO_SavedSearch::saveRelativeDates($queryParams, $formValues);
      CRM_Contact_BAO_SavedSearch::saveSkippedElement($queryParams, $formValues);
      $savedSearch->form_values = serialize($queryParams);
    }
```

**Comment by monishdeb** [comment]
I see

**Pull request merged**
