### PR TITLE
E_NOTICES on activity view

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
I have some unit tests I'm working on and these are coming up.

Before
----------------------------------------
1. Send an email from civi.
2. View the email activity.
3.
  ```
  Warning: Undefined array key "mailingId" in include() (line 21 of ...ActivityView.tpl.php).
  Warning: Undefined array key "campaign" in include() (line 32 of ...ActivityView.tpl.php).
  Warning: Undefined array key "engagement_level" in include() (line 39 of ...ActivityView.tpl.php).
  ```

After
----------------------------------------

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
CRM_Activity_Form_ActivityViewTest::testActivityViewPreProcess
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     'target_contact_value' => 'Anderson, Julia'
     'source_contact' => 'Anderson, Anthony'
     'case_subject' => null
-    'id' => 1
+    'id' => '1'
     'subject' => 'Discussion on warm beer'
     'activity_subject' => 'Discussion on warm beer'
     'activity_date_time' => '2022-12-14 00:00:00'
@@ @@
     'modified_date' => '2022-12-14 00:00:21'
     'activity_modified_date' => '2022-12-14 00:00:21'
     'attachment' => null
+    'mailingId' => null
+    'campaign' => null
+    'engagement_level' => null
 )

**Comment by demeritcowboy** [comment]
Maybe appropriate that my PR would fail on a warm beer test...

**Comment by yashodha** [comment]
@demeritcowboy merging this now as tests pass as well. Thanks!

**Comment by eileenmcnaughton** [comment]
lol -

**Pull request merged**
