### PR TITLE
SearchKit for Find Participants during sprint

### PR DESCRIPTION
**Pull request by breheret**
Overview
----------------------------------------
I just do the searchkit and formbuilder for replace the find Participants search (civicrm/event/search)

Before
----------------------------------------
There is QuickForm

After
----------------------------------------
There is SK and formbuilder id Search_ui extension . Is on the Menu Search/Experimental

Technical Details
----------------------------------------
I Add <Html> on several fields in participant.xml. Except 'fee Level ' where it doesn't work where i put type EntityRef
I added filters in the search and formatted the display.
it's staying :
- Add the 'fee level' field which I was unable to put
- Add custom group fields linked to an event/participant
- Add actions that are not native to Searchkit:
	- Cancel registration
	- Email - send now
	- Group - add contacts
	- Group - create smart group
	- Name badges - print
	- PDF letter - print for participants
	- Participant status - change
	- Print selected rows
	- Update multiple participants

Comments
----------------------------------------
It's my first contribution since long time

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins add to whitelist

**Comment by eileenmcnaughton** [comment]
This now has a merge conflict & needs a rebase - I put the DAO changes into a PR here https://github.com/civicrm/civicrm-core/pull/28900 - so I can get them merged & they can just be dropped out of this PR

**Comment by colemanw** [comment]
@breheret are you able to rebase this now that https://github.com/civicrm/civicrm-core/pull/28900 is merged?

**Comment by breheret** [comment]
HI the conflit is 
<<<<<<< sksprint
 * (GenCodeChecksum:2c01c3d92a11190e8bba9dcf97e0938c)
=======
 * (GenCodeChecksum:7e8e26b738a008973b481ca1f7733f60)
>>>>>>> master
I don't really i can do . 
I think a can keep this line
 * (GenCodeChecksum:7e8e26b738a008973b481ca1f7733f60)

Is right ?

**Comment by eileenmcnaughton** [comment]
@breheret you can safely remove that file from your commit because the changes you are trying to make are already merged

**Comment by colemanw** [comment]
Replaced by #29583

**Pull request closed without merging**
