### PR TITLE
dev/core#981 Sorting participants ignored search values.

### PR DESCRIPTION
**Pull request by AlainBenbassat**
Overview
----------------------------------------
Sorting participants ignored search values.

Before
----------------------------------------
When you search for participants of a specific event and then sort the result (e.g. alphabetically), you get all participants of all events.

After
----------------------------------------
The search criteria are respected after sorting.

Technical Details
----------------------------------------
See discussion https://lab.civicrm.org/dev/core/issues/981

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins add to whitelist

**Comment by eileenmcnaughton** [comment]
@AlainBenbassat this will hit the release notes so can you maybe update the description to describe symptoms in a way that informs the users

**Comment by eileenmcnaughton** [comment]
@AlainBenbassat I'm going to merge this - but you can still fix up the template after it's merged.

**Comment by agh1** [comment]
@AlainBenbassat @eileenmcnaughton do you all think this should be in the 5.14 branch?  It's a fairly recent regression (as best I can tell from #12998 in 5.13.0).

**Comment by AlainBenbassat** [comment]
@agh1 Yes, why not add it to 5.14. It's just a small correction.

**Comment by eileenmcnaughton** [comment]
@AlainBenbassat can you do a PR against th 5.14 branch?

**Pull request merged**
