### PR TITLE
fixes event#64: Send event confirmation to submitted email address

### PR DESCRIPTION
**Pull request by MegaphoneJon**
Overview
----------------------------------------
An event registration that's submitted with an email that differs from the (existing) contact's primary email will go to the primary email.  It should go to the submitted email.

Before
----------------------------------------
Event registration confirmations go to the existing primary email.

After
----------------------------------------
Event registration confirmations go to the email submitted.

Technical Details
----------------------------------------
My last line isn't necessary - the Manage Event screen won't allow you to enable email confirmations if we don't ask for an email, so it should always be present.  But who knows what those extension writers get up to?

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Thanks for the patch I can take a look. I think this is addressing the same (or similar) problem that https://github.com/civicrm/civicrm-core/pull/18984 was.

**Comment by MegaphoneJon** [comment]
@demeritcowboy Yes, this seems like it's the same as #18984.  I see Eileen requested a test there, I'll see what I can do about that.  It's a little tricky because it's form-level but we'll work it out.

**Comment by demeritcowboy** [comment]
Great, thanks.
I was actually just looking at this and am noticing that by removing line 1110 it's possible now that $email could retain its value from earlier on in the code and so end up being the notify address, and not defaulting to primary. I.e. initialize $email to null before the loop, or change it to use a different variable.

**Comment by MegaphoneJon** [comment]
OK - I incorporated feedback from #18984.  I've changed the variable name so that we don't accidentally reuse an old one, changed the thank-you page email to match the confirmation email recipient, and added a test.

**Comment by demeritcowboy** [comment]
* General standards
    * [`r-explain`] __PASS__
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __PASS__
* Developer standards
    * [`r-tech`] __PASS__
    * [`r-code`] __PASS__
      * I think I was mistaken on the other PR about the effect of isset vs empty (and here in this PR `!`), because we're talking about a situation where the person is most likely a logged-in user. Otherwise the only way anything comes up is because it's a weird dedupe rule that doesn't use email, and again there's no practical difference.
    * [`r-maint`] __PASS__
    * [`r-test`] __PASS__

There are some other unusual use-cases which I'd say ignore for now but just noting that if email is optional and you leave it blank, then there's a mismatch:
* The thank-you says it was sent to your primary, but it doesn't actually send anything.
* It's not clear which is the desired outcome - if I leave it blank, to me it means don't send me anything, but I suppose it's possible some people might think the other way that it should default to primary, which would also be what the form does when there is no email field on the form.

There's also a pre-existing weirdness that if there is no primary and you don't enter an email, then the Thank-you page says "A registration confirmation email has also been sent to", with no email listed.

**Pull request merged**
