### PR TITLE
Move acl check for contributionView to the extension

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Move acl check for contributionView to the extension

Before
----------------------------------------
Code that belongs in the extension is in the core form

After
----------------------------------------
moved to the extension

Technical Details
----------------------------------------

Comments
----------------------------------------
@monishdeb are you able to review this?

### CODE REVIEW

**Comment by mattwire** [comment]
I think this will probably make https://github.com/civicrm/civicrm-core/pull/22588 go stale any chance of a review on that one :-)

**Comment by eileenmcnaughton** [comment]
@mattwire I took a  look & you are right it would have conflicted. This PR moved 2 parts

1) status bounce on no-access
2) availability of links

I've removed the second part from the PR - as that bit would have 
a) conflicted and
b) been able to be solved better by hooks in the context of your PR. 

However, I think your PR is removing the financialacl hackery without re-instating the functionality via a hook (presumably the links hook) - so `$canEdit` is still being assigned but no longer being heeded -

**Comment by colemanw** [comment]
Merging as the cleanup is an improvement and part of a larger effort we don't want stalled.

**Comment by eileenmcnaughton** [comment]
thanks @colemanw  - I did remove the conflict potential from it to make this one mergeable

**Pull request merged**
