### PR TITLE
CRM-16354 - Add missing Textarea option to schema

### PR DESCRIPTION
**Pull request by colemanw**
https://issues.civicrm.org/jira/browse/CRM-16354

### CODE REVIEW

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
@totten this gave a green light a little too quickly so I looked into the test result and it appears that if the test suite crashes then that counts as "no failures". Yikes.

**Comment by totten** [comment]
jenkins, test this please

**Comment by totten** [comment]
@colemanw , I've created another PR where I can test Jenkins error scenarios, so we don't need to block fixes on this one.

**Comment by colemanw** [comment]
Ok I've removed the bad schema dump from the commit. I'll let someone with a less weird sandbox run regen sometime (not urgent).

**Comment by colemanw** [comment]
retest this please

**Pull request merged**
