### PR TITLE
CRM-17691 do not use default return properties from search screen …

### PR DESCRIPTION
**Pull request by eileenmcnaughton**

### CODE REVIEW

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
jenkins retest this please

**Comment by davecivicrm** [comment]
@eileenmcnaughton Just patched latest pull from master locally with this PR and I'm getting a pile of notices from Find Contributions:
Notice: Undefined property: CRM_Core_DAO::$contribution_campaign_id in CRM_Contribute_Selector_Search->getRows() (line 409 of /Users/dgg/git/crm_v4.7/CRM/Contribute/Selector/Search.php).
Notice: Undefined property: CRM_Core_DAO::$contribution_campaign_id in CRM_Contribute_Selector_Search->getRows() (line 410 of /Users/dgg/git/crm_v4.7/CRM/Contribute/Selector/Search.php).
Notice: Undefined property: CRM_Core_DAO::$is_pay_later in CRM_Contribute_Selector_Search->getRows() (line 417 of /Users/dgg/git/crm_v4.7/CRM/Contribute/Selector/Search.php).
Notice: Undefined index: is_test in CRM_Contribute_Selector_Search->getRows() (line 424 of /Users/dgg/git/crm_v4.7/CRM/Contribute/Selector/Search.php).
Notice: Undefined property: CRM_Core_DAO::$contact_sub_type in CRM_Contribute_Selector_Search->getRows() (line 446 of /Users/dgg/git/crm_v4.7/CRM/Contribute/Selector/Search.php).

**Comment by davecivicrm** [comment]
Adding WIP label since this is not ready to merge.

**Comment by eileenmcnaughton** [comment]
I figured out why my e-notices were getting eaten & have fixed them. In the case of campaign a bit reluctantly as I couldn't see any evidence of it actually being rendered in the UI

**Comment by davecivicrm** [comment]
Thanks, looks good. Did a bunch of tests w/ Contrib Seach => Tasks and getting expected data.

**Comment by eileenmcnaughton** [comment]
You didn't spot anywhere that campaign was used did you? I guess it could be embedded in a search 'somewhere'

**Pull request merged**
