### PR TITLE
SearchKit - default displays and ACL-aware links

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
This gives every SavedSearch an auto-generated table display, and makes use of it in the UI to more conveniently view or embed a saved search without needing to manually create a display. In the UI it's referred to as the "Search results table" to emphasize the fact that it's the same table as shown on the "compose search" screen, and is not configurable like other displays.

In the process I refactored the way links are understood by SearchKit to take ACLs into account.

Before
----------------------------------------
- Search displays must be manually created.
- Links and in-place edit fields are not ACL aware, and show up regardless of user's permission level,

After
----------------------------------------
- Every saved search automatically gets a default display.
- Default displays are calculated at runtime, not stored in the database (so they are always up-to-date if search params are changed).
- Links and in-place edit fields are ACL aware and will gracefully degrade to plain text if the user lacks edit permission.
- Added a "View" link from the SavedSearch listing screen which links to a full-screen view of the default display.
- UI supports creating an Afform based on the default search display.

image

image

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I tested this & it seems to work well. The annoyance I continue to hit is that the label has no defaults & is not near the 'save' button - not sure what others think but I would move it & also give it a default

Anyway - I was able to see the acls working fine & the save worked.

However, the checkboxes to select individual contacts don't seem to be selectable (I have the follow up formatting PR applied locally). I seem to be able to replicate this locally with the admin user too so will try on the test site

image

**Comment by eileenmcnaughton** [comment]
@colemanw check http://core-21929-1mu15.test-3.civicrm.org:8001/civicrm/admin/search#/edit/1 - the rows cannot be selected for actions

**Comment by colemanw** [comment]
Thanks @eileenmcnaughton - I think the action checkboxes might have been broken by the previous refactor but anyway I've pushed up a fix to this PR.

**Comment by colemanw** [comment]
@eileenmcnaughton I've pushed up a default label for search displays as well, just for you :)

**Comment by eileenmcnaughton** [comment]
The defaults kick in on the add display - not the original screen - which was the one that I was thinking of above. 

Action links work now - merging

**Comment by eileenmcnaughton** [comment]
unrelated test fails

**Pull request merged**
