### PR TITLE
CRM-16243 - Extension API - Automatically enable dependencies

### PR DESCRIPTION
**Pull request by JohnFF**
This applies to the install and enable actions.

Handling download is a different task. Ideally, we'd use composer for
downloading. But I'm not sure if that needs to block support for install/enable.

This consumes dependency data from info.xml, as in:

```
<extension key="org.civicrm.cvform" type="module">
  <requires>
    <ext>org.civicrm.api4</ext>
 </requires>
</extension>
```

Consequently, one would need to declare extension dependencies twice (once for
the download dependencies in composer.json; once for the runtime dependencies in info.xml).

This is a rebased version of #8022 which resolves merge-conflicts.
Taken from #9257 .

---
- [CRM-16243: Dependency management for extensions](https://issues.civicrm.org/jira/browse/CRM-16243)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by JohnFF** [comment]
@eileenmcnaughton Tested with 1000+ contacts. 
As it contains the work in #9257 , feel free to close that.

**Comment by JohnFF** [comment]
@totten Struggling to remove a couple of merge commits...

**Comment by eileenmcnaughton** [comment]
If you do 

```
git pull --rebase origin master
```
it should remove them  - you need to do git push -f to push them up afterwards

**Comment by totten** [comment]
Replaced by #11101.

**Pull request closed without merging**
