### PR TITLE
Improve utilities & tests for working with js notation

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds & improves utilities for working with js notation.

Before
----------------------------------------
Less functionality & tests.

After
----------------------------------------
More functionality & tests.

Comments
----------------------------------------
Removes dependence on an external library & improves robustness & accuracy of reading/writing js notation.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw looking at this the existing test cover seems pretty solid - but you seem to have removed 2 rows - can you comment on that. I'm otherwise fairly happy to rely on the tests here given this is a function perfectly suited to unit testing with good coverage

**Comment by colemanw** [comment]
Hey @eileenmcnaughton - I added a bunch of rows to the tests but don't think I removed anything. Which rows were you referring to?

**Comment by colemanw** [comment]
I just thought of a few more ways to break it, so I've added some more tests and fixed the `getRawProps()` fn to handle double-escaped backslashes and regex expressions.

**Comment by eileenmcnaughton** [comment]
Looks good - I think the cover is pretty solid now!

**Pull request merged**
