### PR TITLE
dev/core#1186 - ignore exception if no description field

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/issues/1186

Before
----------------------------------------
Datatables error because of uncaught exception

After
----------------------------------------
Golden silence.

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
@demeritcowboy I think it would be helpful if we were able to generate a unit test here

**Comment by demeritcowboy** [comment]
@seamuslee001 I agree but I need to push back a little. Just no promises.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I agree but I  also think we should be more lenient when people are fixing regressions - so patch desirable but not required here IMHO

**Comment by eileenmcnaughton** [comment]
@mattwire are you able to test?

**Comment by seamuslee001** [comment]
added a unit test here https://github.com/civicrm/civicrm-core/pull/15058

**Comment by eileenmcnaughton** [comment]
this looks safe to me & has a test now - merging

**Comment by demeritcowboy** [comment]
Thanks!

**Comment by mattwire** [comment]
Thanks @demeritcowboy @eileenmcnaughton

**Comment by MegaphoneJon** [comment]
With PR #14658 applied (currently unreleased) this bug popped up on me today when generating PDF letters.  So I applied this patch and can also confirm it fixes the issue.

**Pull request merged**
