### PR TITLE
"Contact Sub Type" dropdown disappears when fields validation occurs

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/issues/699

Before
----------------------------------------
before

After
----------------------------------------
after

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by pradpnayak** [comment]
test this please

**Review by MegaphoneJon — APPROVED** [review]
I replicated the bug and confirm that this fixes it.  I also reviewed the template changes. This looks good, test fail is unrelated.  I'm not sure if Eileen will want this squashed before merge but it's otherwise fine.

**Comment by eileenmcnaughton** [comment]
yes, please squash @pradpnayak & then ping me to merge.

Thanks @MegaphoneJon

**Comment by pradpnayak** [comment]
@eileenmcnaughton 

I have squashed commit can you review now?

Thanks @MegaphoneJon

**Pull request merged**
