### PR TITLE
financial#160 - set correct from_financial_account_id on an edited fee amount FinancialTrxn

### PR DESCRIPTION
**Pull request by MegaphoneJon**
https://lab.civicrm.org/dev/financial/-/issues/160

Overview
----------------------------------------
The `from_financial_account_id` is set incorrectly on the FinancialTrxn created when editing the `fee_amount` on an existing contribution.

Before
----------------------------------------
The `from_financial_account_id` is the financial account of the default `payment_instrument_id`.

After
----------------------------------------
The `from_financial_account_id` is the financial account of the contribution's `payment_instrument_id`.

Comments
----------------------------------------
Replication steps are in Gitlab, but I'll note that once you've replicated the bug, you can keep on replicating it simply by increasing the `fee_amount` on the existing contribution, which makes it quick to iterate.

### CODE REVIEW

**Comment by seamuslee001** [comment]
@MegaphoneJon style issues https://test.civicrm.org/job/CiviCRM-Core-PR/38295/checkstyleResult/new/

**Comment by monishdeb** [comment]
Tested on local and confirmed that the patch fixes the incorrect recording of from_financial_account_id on fee change. Added unit test captures this behaivour accurately. Marking with MoP

**Comment by seamuslee001** [comment]
Test fail looks like it relates @MegaphoneJon

**Comment by MegaphoneJon** [comment]
Thanks @seamuslee001.  I added a check on line 3477 to ensure that the previous contribution's `payment_instrument_id` isn't null before relying on it.

**Pull request merged**
