### PR TITLE
[REF] Fix jquery validation for on behalf of fields when combined wit…

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
per https://github.com/civicrm/civicrm-core/pull/18099

### CODE REVIEW

**Comment by seamuslee001** [comment]
I have ported the other 2 commits that Karin had used in her testing as well MOP

**Comment by eileenmcnaughton** [comment]
@seamuslee001 so the other 2 commits are already in 5.28?

**Comment by seamuslee001** [comment]
yes

**Comment by seamuslee001** [comment]
test fails unrelated

**Comment by KarinG** [comment]
Thank you for backporting this 👍

**Comment by KarinG** [comment]
Documenting my testing -> 

Ok here's what I did -> D8/5.27.4 -> then pulled in:
```
karins-MBP:civicrm-core sysadmin$ curl https://github.com/civicrm/civicrm-core/commit/2ee6dbf5b8ee194e0d495d4ea8fc21575151973f.diff --output 973f.diff
karins-MBP:civicrm-core sysadmin$ curl https://github.com/civicrm/civicrm-core/commit/fb48213098e5f1beb76df36ec7126166dcc21294.diff --output 1294.diff
karins-MBP:civicrm-core sysadmin$ curl https://github.com/civicrm/civicrm-core/commit/4d305c8cbb11dd0b130c9eef69480f0dccfb505c.diff --output b505.diff
```
Applied patches (1 + 1 hunk succeed; 2 applied manually) -> then cleared caches and next: configured contribution page with on behalf of and I can payment process (with or without filling out the on behalf of section)

**Comment by KarinG** [comment]
I've now update a live site to the 5.27 branch (thus with this PR in) - and 

Contribution are processing fine. That's the most import thing - donors not getting stuck on a non-responsive Review Contribution button.

I did notice a small ad-hoc regression -> where none of the I'm contributing on behalf of an organization look required if a donor changes their mind and hits the go back button on the confirm page. This was definitively not the case before the jquery PRs on Contribution pages:

Reproducing this on dmaster:
image

Hitting Review Contribution -> CiviCRM does remember that these were required after all - except for State/Province ?!
image

Do you want me to log this in a new lab ticket?

**Comment by seamuslee001** [comment]
yes please @KarinG

**Comment by KarinG** [comment]
Okie -> done: https://lab.civicrm.org/dev/core/-/issues/1941

**Pull request merged**
