### PR TITLE
CRM-21395 port https://github.com/dompdf/dompdf/pull/1570/files using…

### PR DESCRIPTION
**Pull request by seamuslee001**
… patch files to civicrm dompdf to fix no-block-level error found

Overview
----------------------------------------
Further information can be found on this State Exchange post https://civicrm.stackexchange.com/questions/21139/error-no-block-level-parent-found-not-good

Before
----------------------------------------
Invoice wasn't produced

After
----------------------------------------
invoice is now produced

ping @monishdeb @eileenmcnaughton @KarinG @adixon

### CODE REVIEW

**Comment by KarinG** [comment]
Confirming that this patch fixes the PDF generation (specifically Print Invoice button) -> in 4.7.27

**Comment by eileenmcnaughton** [comment]
Merging based on Karin's review. Seems safe/limited & this is a backport only

**Comment by mattwire** [comment]
@seamuslee001 @eileenmcnaughton Problem with this is that it breaks composer update on every subsequent run as patch returns non-zero if patch is already applied.  Can we add something like:
`if [[ $? -eq 1 ]]; then
	exit 0;
fi
`
to the end of the script please?

**Comment by seamuslee001** [comment]
Thanks @mattwire I've got a plan

**Pull request merged**
