### PR TITLE
API4 Explorer - Remove confusing "Save" button

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes https://lab.civicrm.org/dev/core/-/issues/3155

This button was added as a prototype for saving a smart group from the Explorer.
But since that time SearchKit has evolved with the same functionality.
Since the presence of the button in the Explorer is confusing and redundant with SearchKit, I think it's best to remove it.
It also has a tendency to break the layout on smaller screens.

Before
----------------------------------------
Ack, too many buttons, broken layout, what does "Save" even do??
image

After
----------------------------------------
image

### CODE REVIEW

**Comment by braders** [comment]
Looks good to me. API explorer still seems to be working correctly without the save button on the test site.

**Comment by colemanw** [comment]
Any objections @eil

**Comment by colemanw** [comment]
Any objections @eileenmcnaughton?

**Comment by eileenmcnaughton** [comment]
OK - this makes sense the 'save' button is kinda superceceded

**Pull request merged**
