### PR TITLE
CRM-17404 - NULL values in 'do_not_*' fields if blank in contact:crea…

### PR DESCRIPTION
**Pull request by saurabhbatra96**
…te API.
Upgrade script will now update NULL values to 0 and set default value as 0 for the future.

https://issues.civicrm.org/jira/browse/CRM-17404

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@davecivicrm did this just miss the beta going out? Ie. needs to go in a later .mysql?

**Comment by eileenmcnaughton** [comment]
Also https://github.com/civicrm/civicrm-core/pull/7368

**Comment by davecivicrm** [comment]
@saurabhbatra96 Sorry this missed beta 1. Can you update the PR by moving your change to 4.7.beta2.mysql.tpl ? Thanks.

**Comment by davecivicrm** [comment]
Thanks so much @saurabhbatra96 for your work on these issues!

**Pull request merged**
