### PR TITLE
Used buildoptions function to get all groups

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
API Contact get fails when trying to retrieve contact from group(if Group Name and Group Title is different ). 

Before
----------------------------------------
DB Error: no such field when trying to get contact through api

After
----------------------------------------
No Error.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@pradpnayak looks like we locked in the anomaly somewhat deliberately with a test :-(

@colemanw does apiv4 support an equivalent of the 'group' param - which filters by group, including smart groups....

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by pradpnayak** [comment]
Hi @eileenmcnaughton 

I have removed unwanted commits and pushed a api test. Can you please review?

Thanks
Pradeep

**Comment by eileenmcnaughton** [comment]
@pradpnayak I think we have a situation where the code was originally written to accept 'title'. You have added code to accept 'name' but it breaks the acceptance of title. That is arguably OK (ie. it makes more sense) but we have a test contract to support 'title' so we need to make that continue to work.See the fail

```
api_v3_ContactTest::testContactGetWithGroupTitle
Failure in api call for contact get:  DB Error: syntax error
 SELECT contact_a.id as contact_id, contact_a.is_deleted as `contact_is_deleted`, 
            CONCAT_WS(',',
            GROUP_CONCAT(DISTINCT IF(civicrm_group_contact.status = 'Added', civicrm_group_contact.group_id, '')),
            GROUP_CONCAT(DISTINCT civicrm_group_contact_cache.group_id)
          )
          as groups  FROM civicrm_contact contact_a LEFT JOIN civicrm_group_contact ON contact_a.id = civicrm_group_contact.contact_id  LEFT JOIN civicrm_group_contact_cache ON contact_a.id = civicrm_group_contact_cache.contact_id   LEFT JOIN civicrm_group_contact `civicrm_group_contact-5c2f673a663f2` ON (contact_a.id = `civicrm_group_contact-5c2f673a663f2`.contact_id AND `civicrm_group_contact-5c2f673a663f2`.status IN ('Added'))  WHERE  ( contact_a.is_deleted = '0' AND  ( ( `civicrm_group_contact-5c2f673a663f2`.group_id = Test group C  ) )  )   GROUP BY contact_a.id LIMIT 0, 25 
```


I think you will need to do something like this

```
   if (isset($params['group'])) {
     $groups = $params['group'];
-    $allGroups = CRM_Core_PseudoConstant::group();
+    // For legacy reasons a group may be referred to by title.
+    $groupsByTitle = CRM_Core_PseudoConstant::group();
+    $groupsByName = CRM_Contact_BAO_GroupContact::buildOptions('group_id', 'validate');
     if (is_array($groups) && in_array(key($groups), CRM_Core_DAO::acceptedSQLOperators(), TRUE)) {
       // Get the groups array.
       $groupsArray = $groups[key($groups)];
       foreach ($groupsArray as &$group) {
-        if (!is_numeric($group) && array_search($group, $allGroups)) {
-          $group = array_search($group, $allGroups);
+        if (!is_numeric($group) && array_search($group, $groupsByName)) {
+          $group = array_search($group, $groupsByName);
+        }
+        elseif (!is_numeric($group) && array_search($group, $groupsByTitle)) {
+          // It would be nice to give a deprecated warning here but it would break some tests.
+          $group = array_search($group, $groupsByTitle);
         }

```

**Comment by pradpnayak** [comment]
@eileenmcnaughton I have updated the PR with your suggested change. Can you please review?

**Comment by eileenmcnaughton** [comment]
Looks good to me - great stuff @pradpnayak

**Pull request merged**
