### PR TITLE
CRM-16389 - Absolute URLs in HTML Profile Snippets

### PR DESCRIPTION
**Pull request by jmcclelland**
Ensure profile html snippets have absolute URL

---
- [CRM-16389: html snippet references to scripts and css files does not reference CIVICRM_UF_BASEURL](https://issues.civicrm.org/jira/browse/CRM-16389)

### CODE REVIEW

**Comment by kurund** [comment]
@jmcclelland can you please fixed the errors reported by jenkins

**Comment by totten** [comment]
@jmcclelland , apologies for the delay in getting to this patch.

To recap: when one adds a resource from the 'civicrm' extension, it composes a URL based on `$config->resourceBase` (by default). This patch changes that -- within a certain context, it will instead use `$config->userFrameworkBaseURL`. The intent is to change it from relative URLs to absolute URLs

A few critiques:

 * It doesn't look like the values of `resourceBase` and `userFrameworkBaseURL` are ordinarily interchangeable. On my local system, the patch produces absolute URLs... which are wrong (e.g. `http://d46.l/packages/jquery/plugins/jquery.tableHeader.js`). To see why, here are some example values (spot-checked from the `civicrm.org` production system):

<table><tbody>
<tr><td>www</td><td>resourceBase</td><td>"/sites/all/modules/civicrm/"</td></tr>
<tr><td>www</td><td>userFrameworkBaseURL</td><td>"https://civicrm.org/" </td></tr>
<tr><td>drush</td><td>resourceBase</td><td>"https://civicrm.org/sites/all/modules/civicrm/"</td></tr>
<tr><td>drush</td><td>userFrameworkBaseURL</td><td>"https://civicrm.org/"</td></tr>
</tbody></table>

 * There are a few more items in the HTML which have relative URLs -- e.g. the "Cancel" buttons and (if you enable user creation) the login link. A bit nervous about more edge-cases, and this function is starting to look bad, but I wouldn't necessarily block a bugfix. However... it might be easier for you to approach generically (eg "How to make all URLs in a given page absolute?" -- maybe patch to allow `civicrm/profile/create?snippet=external` and then kill all the code in `CRM_UF_Page_Group::profile()`?). Your first commit suggests that we could conditionally change `resourceBase` across the entire app.

 * I wish we could replace profile snippets with something else. They invite CSRF, and it's hard to make a pageflow that looks sane. If we have to spend time on this use case, I'd rather spend it on finding a (secure) way to use JS widgets + CORS + snippet mode + API.

**Comment by jmcclelland** [comment]
Thanks Tim - I agree we shouldn't commit this as is. I will pursue your suggestions of adding snippet=external and mucking with the resourceBase variable in CRM/Core/Config.php.

I hate snippets too. However, the other option we had been using quite successfully (embedding via an iframe) is starting to have it's own problems (see https://civicrm.stackexchange.com/questions/4667/using-iframes-to-present-contribution-page-on-remote-site/4676#4676).

I had never heard of CORES but just did some [reading on Wikipedia](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing). It seems promising and would solve the other typical complaint we get: if there's an error on the page the user is redirected to the civicrm site.

**Comment by kurund** [comment]
jenkins, test this please

**Comment by davecivicrm** [comment]
Closing per @jmcclelland comment above.

**Pull request closed without merging**
