### PR TITLE
4.7.10 merge

### PR DESCRIPTION
**Pull request by yashodha**

### CODE REVIEW

**Comment by yashodha** [comment]
test this please

**Comment by seamuslee001** [comment]
@yashodha this looks like it still needs rebasing against master as Jenkins can't apply the patches

**Comment by yashodha** [comment]
test this please

**Comment by yashodha** [comment]
test this please

**Comment by seamuslee001** [comment]
@yashodha Jenkins can't apply the patches onto master i think it needs rebaseing

**Comment by yashodha** [comment]
merges have already been done

**Pull request closed without merging**
