### PR TITLE
dev/financial#69 Fix misrecording of payments against non pay_later Pending contribution.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fixes bugs when payments are added against a non-pay later contribution. There were 2 different bugs
1) bug in form layer when the payment is fully paid
2) bug in BAO layer for partial payments.

This fixes both. It may be a regression, hence 5.19

Before
----------------------------------------
I replicated

1) Create pending contribution by api 
CRM.api3('Contribution', 'create', {'contact_id' : 203, 'financial_type_id' : '1', 'contribution_status_id' : 2, total_amount: 60})

Screen_Shot_2019-10-14_at_5.50.52_PM

2) Add payment - in fact I think it depends a bit on which payment instrument you use - I used cash in the end

Screen_Shot_2019-10-14_at_5.51.25_PM

3) Screen_Shot_2019-10-14_at_6.02.01_PM

After
----------------------------------------
Only one payment recorded in both full payment & partial payment mode

Technical Details
----------------------------------------
1) The lines removed from AdditionalPayment are updating the status & are no longer required in the form layer. They caused one bug

2) When the payment api calls Contribution.create to update the status it needs to pass  'is_post_payment_create' => TRUE, which is a parameter solely for the Payment.create bao to indicate all financial transactions have been actioned. Long term it would not be needed as all payment adds would go via payment.create & handling in Contribution.create will go

Comments
----------------------------------------
@monishdeb @MegaphoneJon @JoeMurray possible payment regression.

It was logged a month ago so not a 5.18 regression - am OK to port to 5.18 or just target 5.19

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton may want to have another go uploading the screenshots

**Comment by eileenmcnaughton** [comment]
@seamuslee001 done - also targetting 5.19 now

**Comment by mattwire** [comment]
test this please

**Comment by seamuslee001** [comment]
This code change makes sense to me but would apprecaite a confirmation from @monishdeb or @JoeMurray

**Comment by monishdeb** [comment]
I tested on my local and it does fix the regression occurred for fully paid and partial payment. Also added UT confirms the fix. I am happy to merge this PR.

**Pull request merged**
