### PR TITLE
Fix PR testing running by reverting #23903

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
_A brief description of the pull request. Keep technical jargon to a minimum. Hyperlink relevant discussions._

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton @totten I think this should permit apiv4 unit tests to run at the moment PRs are failing because apiv4 unit tests aren't running on pre boot error

**Comment by eileenmcnaughton** [comment]
hmm - that's tricky - our wmf tests were failing - hence the revert of it - well let's see how it goes & we can try to find something that works in both cases

**Comment by totten** [comment]
Adding some more details from @seamuslee001's diagnosis and my steps to reproduce:

* The problem specifically affects `tests/phpunit/api/v4/Entity/WorkflowMessageTest.php` -- which has a `@dataProvider` that can fire the hook.
* The problem does not affect 5.51 -- because it doesn't use `@dataProvider`
* The problem does affect master.
* The problem doesn't apply when you first run the test. It applies on the second run.
* If you restore the original DB in between, then it runs again.

The focus seems to be the `@dataProvider`. It is generally risky to have `@dataProvider`s which rely on full bootstrap and/or high-level services. If the implementation of `@dataProvider` skipped the hooks, then it would be more consistent/reliable.   A couple ideas for that:

* Use two different instances of `ExampleDataLoader` -- the test-only instance used by `@dataProvider` would only scan core. The runtime instance used by` Civi\Api4\ExampleData` would scan everything.
* Follow the pattern of `Civi\Api4\Entity\ConformanceTest` (`testEntitiesProvider()`, `getEntitiesHitech()`, `getEntitiesLowtech()`). To wit: the `@dataProvider` relies on a heuristic/lotech/fallible method, and we have an extra check just to make sure that lotech method works.

**Comment by eileenmcnaughton** [comment]
Ah interesting - dataProvider is nicer in that you get a test per entry but we can also iterate within the test - also - I don't think it's testing much at the moment....

**Comment by demeritcowboy** [comment]
Sounds like this is no longer needed.

**Pull request closed without merging**
