### PR TITLE
RM385-65: Membership end date incremented twice by duration when pending contribution with amount 0.0

### PR DESCRIPTION
**Pull request by agilewarealok**
Overview
----------------------------------------
When a membership has a minimum fee of $0.00 and an admin renews their membership with a pending contribution, the membership end date is incremented by duration both when the pending contribution is created and after the contribution is marked as completed.

Steps to reproduce:
1. Find any contact in Civicrm
2. View the contact
3. Click MemberShips
4. Add a membership with a minimum fee of $0.00 - not lifetime
5. Click More -> Renew next to membership
6. Tick Record renewal Payment
7. Mark renewal contribution as pending and submit payment
8. Note that the membership end date has incremented by the duration outlined in the membership type
9. Navigate to Contributions section
10. Mark newly created contribution as complete
11. Refresh and navigate to Memberships page, note that membership end date has incremented again

Before
----------------------------------------
Membership period were incremented twice both when contribution is created and after the contribution is marked as completed.

After
----------------------------------------
Membership period gets incremented only once when the contribution is marked as completed.

_Agileware Ref: RM385-65_

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I'm just wondering about this - it's against 4.6 so unlikely to get reviewed  / merged - but does the bug exist in 4.7/master?

**Comment by agilewarealok** [comment]
No it's not reproducible in 4.7/master.

**Comment by eileenmcnaughton** [comment]
that's good to hear

**Comment by jackrabbithanna** [comment]
Jenkins test this please

**Comment by jackrabbithanna** [comment]
Merging #11730

**Pull request merged**
