### PR TITLE
Use temp table methods; provide TempTable::getCreateSql() method for debugging

### PR DESCRIPTION
**Pull request by mfb**
Overview
----------------------------------------
Use TempTable methods to create some more temp tables; add TempTable::getCreateSql() method for debugging purposes.

Before
----------------------------------------
Temp tables are created via SQL statements.

After
----------------------------------------
TempTable methods are used instead; a new method allows developers to print the automatically generated create statement.

### CODE REVIEW

**Comment by mfb** [comment]
jenkins retest this please

**Comment by mfb** [comment]
jenkins retest this please

**Comment by eileenmcnaughton** [comment]
I tested this and I got a fatal sql error on the date added custom search. The reason is just an extra row that needs to go - ie

```
--- a/CRM/Contact/Form/Search/Custom/DateAdded.php
+++ b/CRM/Contact/Form/Search/Custom/DateAdded.php
@@ -297,8 +297,6 @@ class CRM_Contact_Form_Search_Custom_DateAdded extends CRM_Contact_Form_Search_C
         print "</pre>";
       }
 
-      CRM_Core_DAO::executeQuery($sql, CRM_Core_DAO::$_nullArray);
-
       $includeGroup = "INSERT INTO {$this->_igTable} (contact_id, group_names)
                  SELECT      d.id as contact_id, civicrm_group.name as group_name
                  FROM        {$this->_datesTable} AS d

```

ALSO when you update this can you rip out those debug blocks & refs to $this->_debug - there is no excuse for us having that junior-dev-hackery in our codebase

**Comment by eileenmcnaughton** [comment]
(I do like your function to support getting the query - I expect that future unit test writers will thank you for it!)

**Comment by eileenmcnaughton** [comment]
Regarding the second block - it should only be accessed when 

```
    $useTable = (CRM_Utils_System::getClassName($form->controller->getStateMachine()) == 'CRM_Export_StateMachine_Standalone');
```

I could find no way to access that form & I suspect it's dead

**Comment by mfb** [comment]
I didn't remove all references to _debug in CRM/Contact/Form/Search/Custom/DateAdded.php since they are not related per se, but I could.

Also re: the dead form - are you saying I should remove it in this PR or just making a note?

**Comment by eileenmcnaughton** [comment]
Re the dead form - just making a note - in fact I found it IS used - kinda - out of scope for this

& yeah - please rip out all those refs - be good to get them gone and really!?

**Comment by mfb** [comment]
btw, does Civi prefer squashed commits for PR?

**Comment by eileenmcnaughton** [comment]
@mfb yes - please squash & re-push & I'll add merge on pass. What we are looking for is 'complete commits' - so it's OK to have multiple commits if each one stands alone. In this case however the removal of that extra query call is in a different commit to the one it belongs in & it's probably easier to squash to a single commit than to 'sort them out'

**Comment by mfb** [comment]
@eileenmcnaughton think this is ready (and then I can do another round of similar changes...)

**Comment by eileenmcnaughton** [comment]
Ok - this was just pending a squash which has been done so - merging

**Pull request merged**
