### PR TITLE
Fix an HTML error in Calculate.tpl

### PR DESCRIPTION
**Pull request by mlutfy**
Overview
----------------------------------------

There was an HTML error with a 'span' tag that was not closed correctly because the markup was outside the condition.

I also did a bit of code-style cleanup.

Most of it is NFC, except that I added the string "for this participant" now moved inside the span. It doesn't make sense to have it outside.

Before
----------------------------------------
```
<div id="pricesetTotal" class="crm-section section-pricesetTotal">
--
   <div class="label
   " id="pricelabel">
   Total Fee(s)</span>
   for this participant      </div>
   <div class="content calc-value"  id="pricevalue" ></div>
   </div>
```
Screen Shot 2019-09-05 at 7 17 25 PM

```
After

<div id="pricesetTotal" class="crm-section section-pricesetTotal">
--
   <div id="pricelabel" class="label ">
   <span id='amount_sum_label'>Total Fee(s) for this participant</span>
   </div>
   <div class="content calc-value"  id="pricevalue"></div>
  </div>

```

And on a membership page

```
<div id="pricesetTotal" class="crm-section section-pricesetTotal">
--
<div id="pricelabel" class="label ">
   <span id='amount_sum_label'>Total Amount</span>
   </div>
   <div class="content calc-value"  id="pricevalue"></div>
   </div>

```

No  noticeable visible change

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
Code looks good - if someone does an r-run & confirms the html this is mergeable

**Comment by eileenmcnaughton** [comment]
I tested this locally & edited my findings in the PR template above. Summary = yes, this fixes a broken html tag.

Merging

**Comment by mlutfy** [comment]
thanks :)

**Pull request merged**
