### PR TITLE
Smarty variables]  Remove another isset - deferredFinancialType

### PR DESCRIPTION
**Pull request by eileenmcnaughton**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Comment by eileenmcnaughton** [comment]
this one has passed now

**Comment by eileenmcnaughton** [comment]
@demeritcowboy this is the last of the isset ones...

After this there is *just* enotices and over-escaping to worry about....

**Pull request merged**
