### PR TITLE
dev/core#2310 Searchkit - Perform bulk updates in batches; improve user feedback.

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/2310

Adds a batch system to search kit. This avoids server timeouts, and improves the user experience.

Before
----------------------------------------
Simple save button processes all records at once with no user feedback.

After
----------------------------------------
Processes bulk updates/deletes 500 at a time, with a progress bar, spinner & text to indicate which records are being processed.

image

Technical Details
----------------------------------------
This breaks the batches into groups of 500 records at a time. That number is currently a hard-coded constant. I guess we could make it a setting if needed.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Ohh this is exciting - I can't kick the tyres until next week though

**Comment by eileenmcnaughton** [comment]
@colemanw this is nice.

I experience a real lag in the other fields in the screen - this is the before screen shot - note how long it takes for the field to change to a hand - campaign is also fairly slow  (there are quite a few). I originally thought it was worse after but I'm not so sure now. I think it warrants further investigation but is non-blocking on this

Before
before2021-01-30 12-32

After
after2021-01-30 12-38

**Comment by colemanw** [comment]
@eileenmcnaughton I think the slow lag when opening up the "Add Value" select is due to it waiting on `Contribution.getFields`. I'm not sure why that call is taking so long but I would guess it is due to an excessively long pseudoconstant list in one or more of the fields... perhaps there are a lot of campaigns?

**Comment by colemanw** [comment]
@eileenmcnaughton I think this will help with your loading time issue: https://github.com/civicrm/civicrm-core/pull/19463

**Pull request merged**
