### PR TITLE
Payflow Pro not payflo

### PR DESCRIPTION
**Pull request by xurizaemon**
Overview
----------------------------------------
Honestly, I just wanted to correct the typing of "payflo" in one error message (because it refers to [a different payment processor](https://www.payflo.com/)). Using the right words / terms :arrow_forward: less confusion for users.

Before
----------------------------------------
Error message refers to "payflo"

After
----------------------------------------
Error message refers to "Payflow Pro", the payment processor in question.

Technical Details
----------------------------------------

* This changes some error messages to the consistent naming (may be implications for translation).
* Also some comment cleanups.
* Also notes that there's a getFoo() function which doesn't seem to return a value, printing instead.

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Review by seamuslee001 — APPROVED** [review]

**Comment by seamuslee001** [comment]
@xurizaemon are you able to squish this into 1 commit and fix the style issue reported by Jenkins?

**Comment by xurizaemon** [comment]
Three commits for clarity IMO @seamuslee001 - wanted to separate the docs changes from the functional change. Happy for you to squash on merge if that's your jam.

**Comment by xurizaemon** [comment]
Updated with fixes for the two remaining "You must use "/**" style comments for a function comment" warnings.

**Comment by xurizaemon** [comment]
What do you make of that `getRecurringTransactionStatus()` that doesn't return anything @seamuslee001 @eileenmcnaughton ? Is that potentially something to care about or is it a special use of the get prefix?

Feels like Payflow Pro has been in chat / SE a bit since some recent release. I may be wrong!

**Comment by seamuslee001** [comment]
Giving this merge on pass, all the changes relate to either comment blocks or correcting typos in error messages

**Comment by seamuslee001** [comment]
@xurizaemon I believe its a very small payment processor, i believe there was an issue with a recent DB upgrade that stuffed up the formatting of amount passed to the processor. In regards to this particular piece of code it is an oddball however it doesn't appear to be used at all doing a grep in the core code there are only 1 other reference apart from the function it's self and its commented out 
```
seamus@civicrmdevelopment:~/buildkit/build/47-test/sites/all/modules/civicrm$ grep -ir 'getRecurringTransactionStatus' *
CRM/Core/Payment/PayflowPro.php:  public function getRecurringTransactionStatus($recurringProfileID, $processorID) {
CRM/Core/Payment/PayflowPro.php:    //     c  $trythis =        $this->getRecurringTransactionStatus($recurringProfileID,17);
```

I'm going to merge this as the changes are straight forward and i don't think the issue of `getRecurringTransactionStatus` should hold up this PR

**Pull request merged**
