### PR TITLE
dev/core#690 - Civi\API - Fix entity permission check for trusted calls

### PR DESCRIPTION
**Pull request by pfigel**
Overview
----------------------------------------
`Civi\API\Subscriber\DynamicFKAuthorization` is responsible for checking permissions on entities attached to other (parent) entities by imitating the permissions of the parent entity.

Before
----------------------------------------
When API requests with `check_permissions` set to `0` are processed, `DynamicFKAuthorization` first checks whether the parent entity is an allowed delegate, and then permits the call since it's trusted. However, if the entity is not an allowed delegate, `DynamicFKAuthorization` throws an exception.

`custom_6` is a custom file field for memberships. `civicrm_membership` is not an allowed delegate, so this API request would fail:
```php
civicrm_api3('Attachment', 'create', [
  'field_name' => 'custom_6',
  'entity_id' => 123,
  'name' => 'README.txt',
  'mime_type' => 'text/plain',
  'content' => 'Please to read the README',
  'check_permissions' => 0,
]);
```

After
----------------------------------------
`DynamicFKAuthorization` first checks whether the API request is trusted and permits the request if that's the case. Other checks are only performed if the API request is untrusted.

This API call now succeeds:
```php
civicrm_api3('Attachment', 'create', [
  'field_name' => 'custom_6',
  'entity_id' => 123,
  'name' => 'README.txt',
  'mime_type' => 'text/plain',
  'content' => 'Please to read the README',
  'check_permissions' => 0,
));
```

### CODE REVIEW

**Comment by colemanw** [comment]
@civicrm-builder add to whitelist

**Comment by colemanw** [comment]
@totten and I have reviewed this and agree with the change. Bonus points for submitting a test!
Marked as merge-on-pass.

**Comment by eileenmcnaughton** [comment]
@pfigel the first test fail definitely relates
```
api_v3_AttachmentTest::testCreateFailure with data set #4 ('CRM_Core_DAO_Domain', array('test_M8q2M_exampleFromContent.txt', 'text/plain', 'My test description', 'My test content'), '/Unrecognized target entity/')
api call should have failed but it succeeded We expected a failure for Attachment create but got a success: Array
(
    [is_error] => 0
    [version] => 3
    [count] => 1
    [id] => 4
    [values] => Array
        (
            [4] => Array
                (
                    [id] => 4
                    [name] => test_M8q2M_exampleFromContent.txt
                    [mime_type] => text/plain
                    [description] => My test description
                    [upload_date] => 2019-02-05 01:22:44
                    [entity_table] => civicrm_domain
                    [entity_id] => 3
                    [icon] => fa-file-text-o
                    [created_id] => 
                    [url] => http://core-13529-5rg74.test-1.civicrm.org:8001/index.php?q=civicrm/file&amp;reset=1&id=4&eid=3
                    [path] => /home/jenkins/bknix-dfl/build/core-13529-5rg74/sites/default/files/civicrm/custom//test_M8q2M_exampleFromContent_a13be65852085b60704983b6cad60b67.txt
                )

        )

)

Failed asserting that 0 matches expected 1.

/home/jenkins/bknix-dfl/build/core-13529-5rg74/sites/all/modules/civicrm/Civi/Test/Api3TestTrait.php:70
/home/jenkins/bknix-dfl/build/core-13529-5rg74/sites/all/modules/civicrm/Civi/Test/Api3TestTrait.php:115
/home/jenkins/bknix-dfl/build/core-13529-5rg74/sites/all/modules/civicrm/tests/phpunit/api/v3/AttachmentTest.php:359
/home/jenkins/bknix-dfl/build/core-13529-5rg74/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:196
/home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit5/phpunit5.phar:598
```

**Comment by pfigel** [comment]
I'm uncertain on how to proceed here. Obviously removing the test case would work, but then we're basically declaring `Attachment.create` can be used with any entity. Not sure what implications that would have.

I suppose at the very least we'd want to check that the entity does exist so that API requests with something like `entity_table=civicrm_thisdoesntexist` fail. Is that enough or do we need to limit things further?

**Comment by colemanw** [comment]
@pfigel I agree that an additional check for the existence of the entity would be good.

**Comment by pfigel** [comment]
I added a check against `CRM_Core_DAO_AllCoreTables::isCoreTable`, so the code shouldn't accept invalid tables any more.

I changed the failing test in `api_v3_AttachmentTest` to use permission checking, in which case we'd still throw errors for entities that aren't allowed delegates. This reflects the change in behaviour we'd be introducing with this change - allowing arbitrary (valid) entities to have attachments.

While trying to use `CRM_Core_DAO_AllCoreTables::isCoreTable`, I noticed that it doesn't seem to be working - it's checking for class names rather than table names. The method is used only once in core (in `CRM_Core_BAO_CustomGroup`), and the intention there is to look for table names, so there should not be much risk of breakage for the included fix. I can split that into a separate issue and/or add `CRM_Core_DAO_AllCoreTables::reaIsCoreTable` if needed. 😄

**Comment by monishdeb** [comment]
Merging as per tag

**Comment by pfigel** [comment]
ping @colemanw to double-check if the change to `CRM/Core/DAO/AllCoreTables.php` was okay for merging since it wasn't part of the initial review

**Comment by colemanw** [comment]
Looks good to me.

**Pull request merged**
