### PR TITLE
E:: to make it look after the extension's translation

### PR DESCRIPTION
**Pull request by dev-allinappli**
Overview
----------------------------------------
_A brief description of the pull request. Keep technical jargon to a minimum. Hyperlink relevant discussions._

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by colemanw** [comment]
I don't see a `use` statement at the start of this file, so `E` would be undefined.

**Comment by allinappliadmin** [comment]
oups, what it missing?

**Comment by colemanw** [comment]
This line belongs under the `namespace`
https://github.com/civicrm/civicrm-core/blob/64afffad3a34c93475dec65f059ceb50fded3443/ext/afform/core/Civi/Afform/AfformMetadataInjector.php#L14

**Comment by allinappliadmin** [comment]
is it ok now?

**Comment by mlutfy** [comment]
@allinappliadmin Can you rebase into 1 commit?

```
git rebase -i master
```

then in the editor, "squash" the 2nd and 3rd commit (`s` in the comment, instead of `pick`)

then:

```
git push (your-remove) (your-branch) --force
```

**Comment by allinappliadmin** [comment]
> @allinappliadmin ah - apparently I can do the rebase (github lets me modify your PR/branch) - fixed it for you
> 
> It's your first commit on this repo 🎉

youpi !

**Comment by colemanw** [comment]
Thanks @allinappliadmin

**Pull request merged**
