### PR TITLE
CiviMail - New autocompletes for selecting recipients

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
When composing a mailing, this replaces the single include/exclude/groups/mailings widget with two widgets, one for include and another for exclude. Groups and mailing are still combined together in autocomplete results, but are loaded more efficiently by APIv4.

Original proposal: https://lab.civicrm.org/dev/core/-/issues/4045

Replaces #26522 

Before
----------------------------------------
image

After
----------------------------------------
- 2 widgets on separate lines (Include/Exclude)
- Little wrench button given some text to make it more visible
- "Hidden Smart Group 123456" relabeled "Search Results"

image

Technical Details
----------------------------------------
Builds on #26536 and #26583 to create a SearchDisplay that UNIONS groups and mailings.

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by agileware-justin** [comment]
Would be good to get rid of the almost completely useless "~ 94 recipients" text and instead replace this with a URL "Show Recipients" which links to a contact listing of the actual recipients for the mailing based on the criteria. Open in new page - similar to the Mailing report links.

Because showing some of the recipients is far less useful than showing the actual recipients.

Otherwise, definitely better than the current feature. Thanks!

**Comment by colemanw** [comment]
@agileware-justin just to keep things focused, please open a different issue for that. This PR doesn't touch that piece.

**Comment by agileware-justin** [comment]
No worries

**Comment by demeritcowboy** [comment]
This works for me.
I [can no longer select null](https://lab.civicrm.org/dev/core/-/issues/1912), so I can't no longer send nothing to nobody. But my _set_ of thoughts on that is _empty_.

**Comment by colemanw** [comment]
Now how will @demeritcowboy get in touch with his old friend Null?

**Comment by demeritcowboy** [comment]
Ah, [clever reference](https://github.com/civicrm/civicrm-packages/blob/61ff39518dfd54449158bfd44670063d84615015/DB/DataObject.php#L4936)!

> // CRM-15522 ends

Yeah, if only.

**Comment by colemanw** [comment]
> // CRM-15522 lives!

**Comment by colemanw** [comment]
Even in APIv4, it lives on!
https://github.com/civicrm/civicrm-core/blob/fbdb1ee2b15db21d348286b0c0ffa52150d7ad30/Civi/Api4/Utils/FormattingUtil.php#L56-L68

**Pull request merged**
