### PR TITLE
Support street address sorting for contact detail report

### PR DESCRIPTION
**Pull request by mountev**
Overview
----------------------------------------
Support street address sorting in contact detail report.

Before
----------------------------------------
No support for street address sorting.

After
----------------------------------------
image

### CODE REVIEW

**Comment by yashodha** [comment]
test this please

**Comment by yashodha** [comment]
test this please

**Comment by yashodha** [comment]
@mountev tested this, works fine. I am merging the PR.

**Comment by agh1** [comment]
FYI I opened #16029 because I noticed this when putting together the release notes and remembered that there is no index on street address.  (We had a client reporting problems using the quick search, and we fixed it by adding the index manually to their database, meaning to write a general fix but putting it off until now.)

**Pull request merged**
