### PR TITLE
CRM-16189, added script for new activity type 'Closing Accounting per…

### PR DESCRIPTION
**Pull request by pradpnayak**
…iod'

---
- CRM-16189: Improve support for Accrual Method bookkeeping
  https://issues.civicrm.org/jira/browse/CRM-16189

### CODE REVIEW

**Comment by Edzelopez** [comment]
jenkins, please retest

**Comment by Edzelopez** [comment]
jenkins, retest this please

**Comment by Edzelopez** [comment]
@colemanw test failures related?

**Comment by colemanw** [comment]
@Edzelopez please rebase and we'll test it again.

**Comment by Edzelopez** [comment]
Rebased the PR.

**Comment by Edzelopez** [comment]
@colemanw can we merge this since checks have passed?

**Pull request merged**
