### PR TITLE
SearchKit - Update crmSearchAdminFields.html to use X icon instead of ban icon for removing fields

### PR DESCRIPTION
**Pull request by kapn1966**
Confusing icon choice. Should be trash rather than ban.

Overview
----------------------------------------
_A brief description of the pull request. Keep technical jargon to a minimum. Hyperlink relevant discussions._

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins add to whitelist

**Comment by mmyriam** [comment]
Reviewing this PR at CiviCamp Montreal and several of us here think that the icon used to remove the field in the Select Fields tab should be the same icon used to remove the column in the preview at the bottom of the screen. Currently the X is used. Using the trash bin would cause clutter. Also the tooltips should be consistent.

Necessary changes:
* X for icon in top list
* "Remove" for tooltip in bottom table

image

image

**Comment by mmyriam** [comment]
Glad you agree. Actually you can just modify this PR if you are comfortable doing that.

**Comment by kapn1966** [comment]
I'm fine with the idea, but not really sure about how to do it. I guess I just try to make further code changes in this automatically created branch?

**Comment by kapn1966** [comment]
I have managed to changed the icon choice for this PR to an X, but I can't figure our how to add files to make the change from "clear" to remove as you suggest in the lower section. What happens now to this change? Do you approve? Or someone else?

**Comment by mmyriam** [comment]
I will review this PR. You can make the tooltip change in a different PR.

**Comment by mmyriam** [comment]
Confirming that icon is changed in Select Fields tab of SearchKit configuration.

Still to do:
* Change tooltip to Remove in preview 
* Change icon to X (fa-times) in displays

**Comment by kapn1966** [comment]
I'll try to track down those other file locations and make the changes you suggest. I'm thinking Thursday afternoon ET.

**Comment by mattwire** [comment]
@kapn1966 Please follow up with the other changes in a new PR

**Pull request merged**
