### PR TITLE
CRM-16367 / 4.6 Payment: implement the payment_token

### PR DESCRIPTION
**Pull request by torenware**
This time, actually merge to the right branch.

### CODE REVIEW

**Comment by kurund** [comment]
test this please

**Comment by torenware** [comment]
@kurund -- I'd guess this run will also fail.  

I think the problem arises from this error 
````
api_v3_SyntaxConformanceTest::testCreateSingleValueAlter with data set #31 ('PaymentToken')
api result array comparison failed checking if created_date was correctly updated
````

PaymentToken has some required arguments, which is causing it to fail in api_v3_SyntaxConformanceTest::testSimple_get().  From the looks of things, class api_v3_SyntaxConformanceTest needs to be modified to notify it how to create a test PaymentToken entity. 

If I'm right here:  what's a good example as to how to handle an entity that has required parameters?

**Comment by kurund** [comment]
@torenware I think last failure was unrelated, hence restarted the test run, let's wait till it finishes.

**Comment by torenware** [comment]
Kurund,

Looks like Build #3328 (May 1, 2015 7:34:08 PM) is stuck.  Still in the system after 6 hours.

I think you need to put it out of its misery :-)

R

Rob Thorne
Torenware Networks

**Comment by eileenmcnaughton** [comment]
Rob, I did a PR against your branch to get past the failing syntax conformance test. There are 2 parts. One is that the test highlighted the current create syntax was actually resulting in the created table having

	`created_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Date created',

ie. this "DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" was some sort of default for that field type. I decided we did want DEFAULT CURRENT_TIMESTAMP but not the on-update part. So, the schema change makes that explicit & generated the updated sql that is in a separate PR.

The second issue is that the core handling of timestamps is somewhat flawed - so I supressed it with a view to fixing properly in 4.7 - ref CRM-16431

**Pull request merged**
