### PR TITLE
Invoice Workflow template - add domain tokens

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Invoice Workflow template - add domain tokens

Before
----------------------------------------
The invoice task form has specific code to assign domain-token-like data to the invoice form

After
----------------------------------------
The values are actual tokens - and the template for NEW installs uses these. There is no change to existing install templates and the values they are used to using are still assigned

image

Technical Details
----------------------------------------
While this commit lays the ground work to clean these values up out of the invoice task it does not, in itself, do that. We have done that with other tokens and have upgrade helpers but there is no urgency to do so & it can be out of the scope of this PR.

Note that this will make these tokens widely available - we can hide the audience if we really really want to - but to my mind if these are useful in one message layout then it's because they are useful - the only thing 'special' about their usage here is that more effort has been put into layout, in part because of the availability I think

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@totten this fixes one of the 'fixme' aspects of your test for the workflow templates. I will do look at the others but just want to note that https://lab.civicrm.org/dev/core/-/issues/3656 is where we should mostly focus since that is where the blockers are to unhiding

**Comment by totten** [comment]
This looks conceptually good. I had some success with `r-run` on the preview UI for msgtpl, and I pushed up some tweaks to labels. But I'm having some oddities with domain tokens in CiviMail. Still trying to figure it out.

**Comment by eileenmcnaughton** [comment]
label changes look good - thanks for those

There is some caching in tokens - could that be your issue?

**Comment by totten** [comment]
Could've been.  I tried again with tighter control over the steps, and it seems the tokens are working on CiviMail. :)

| Steps                                                                  |      preview-html    | send-email |
|--|--|--|
| git checkout invoice_domain   ; cv ext:uninstall flexmailer ; cv flush |      full            | full |
| git checkout invoice_domain~2 ; cv ext:uninstall flexmailer ; cv flush |      partial         | partial |
| git checkout invoice_domain   ; cv en  flexmailer ; cv flush           |      full            | full |
| git checkout invoice_domain~2 ; cv en  flexmailer ; cv flush           |      partial         | partial |

So... merge on pass!

**Pull request merged**
