### PR TITLE
CRM-16160: Changes to add search by age to Advanced Search

### PR DESCRIPTION
**Pull request by aydun**
In the Demographics section of Advanced Search, this adds fields:
Min Age (int), Max Age (int), As of Date (date)

The date field is hidden until an age is entered in either box.
If a date is entered, the ages are evaluated as of that date, otherwise it defaults to the age as of the date of searching.

---
- [CRM-16160: Add search by age in Advanced Search](https://issues.civicrm.org/jira/browse/CRM-16160)

### CODE REVIEW

**Comment by colemanw** [comment]
ok to test

**Comment by kurund** [comment]
@aydun Can you please on errors reported by test suite.

**Comment by aydun** [comment]
@kurund Done!

**Comment by davecivicrm** [comment]
Did some QA and code review. The queries are working nicely. There are some issues with the HTML markup / layout:
1. Demographics.tpl : duplicate open and close TR tags (improperly nested TR's) lines 28-31, 32-35 and 42-45
2. If Birth Date > Choose date range is used, the layout for the Age (Min Age / Max Age) fields is messed up.
screen shot 2015-06-22 at 3 15 38 pm

**Comment by magnolia61** [comment]
Would it be very hard to include this age filter to the Contact Summary and Participant list report?

**Pull request merged**
