### PR TITLE
CRM-18535 - Fix api.get permission joins to null fields

### PR DESCRIPTION
**Pull request by colemanw**
https://issues.civicrm.org/jira/browse/CRM-18535

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Excellent, all we need now is a unit test....

**Comment by johanv** [comment]
Are there examples of unit tests that test access permissions?

**Comment by eileenmcnaughton** [comment]
api_v3_ACLPermissionTest class is one

**Comment by johanv** [comment]
Thx. I will look at it once I manage to get phpunit running again on my system ;-)

**Comment by eileenmcnaughton** [comment]
Cool - we are at the sprint for another couple of days so if you do get to it in that time we should be able to get it QAd & merged

**Comment by colemanw** [comment]
I've added a test.

**Comment by colemanw** [comment]
I cannot for the life of me figure out why this test won't pass. It passes on its own, but not when the whole test class is run. I think there is some strange caching of acls going on but I can't find it.
But now I have a niggling doubt about whether this is really a good change after all. If the user has limited access, why are we giving them access to entities just because contact_id is null?

**Comment by eileenmcnaughton** [comment]
good question...

**Pull request closed without merging**
