### PR TITLE
dev/drupal#193 Remove test for l10n mysql generated files (not used by Civi\Setup)

### PR DESCRIPTION
**Pull request by mlutfy**
Related to #29242 - the test was already disabled, but we don't need it anymore, as l10n mysql files are not necessary anymore.

Epic: https://lab.civicrm.org/dev/drupal/-/issues/193

### CODE REVIEW

**Comment by totten** [comment]
@mlutfy The test is checking two things -- *either* that translations appear in the static SQL file *or* that SQL translations appear in dynamic SQL. (It depends on [this out-of-date metadata](https://github.com/civicrm/civicrm-core/pull/29305/files#diff-dd2d62d6668a5fc3a73d3a94df6046b13098e3edb5275b61056340c3b07ae6a8L57).)

I see the point the older/static SQL is being obsoleted  :+1:  so that part doesn't need testing. But shouldn't we still test the newer/current scenario?

**Comment by mlutfy** [comment]
@totten oh ok, so I can just replace with `_getSqlLive` and keep the code?

**Comment by totten** [comment]
@mlutfy Yeah, that would do in a pinch. But it's not hard to clean up a little more - I can throw up another PR in a sec.

**Comment by totten** [comment]
@mlutfy  OK, alternate: https://github.com/civicrm/civicrm-core/pull/29311

**Comment by mlutfy** [comment]
@totten excellent - closing this PR in favour of that one

**Pull request closed without merging**
