### PR TITLE
enotice fixes in fatal error template

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
enotice fixes in fatal error template

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Is it good or bad that it only took 2 minutes of clicking to find a fatal error page? (grin)

**Comment by yashodha** [comment]
@eileenmcnaughton looks good to me, merging this.

**Comment by demeritcowboy** [comment]
Ooh just beat you to it. Hey @yashodha if you're around can you squish https://github.com/civicrm/civicrm-core/pull/21183 ?

**Comment by eileenmcnaughton** [comment]
that was a flurry of activity!

**Pull request merged**
