### PR TITLE
Afform - support file uploads

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Support file fields as part of Afform.

Technical Details
----------------------------------------
Adds a new API action Afform.submitFile which receives uploaded files one at a time after the form is submitted.

Comments
----------------------------------------
So far this supports adding but not removing files when updating an entity.

### CODE REVIEW

**Comment by seamuslee001** [comment]
@colemanw 

```
PHP Fatal error:  Cannot declare class api_v4_AfformCustomFieldUsageTest, because the name is already in use in /home/jenkins/bknix-dfl/build/core-21150-6yacd/web/sites/all/modules/civicrm/ext/afform/mock/tests/phpunit/api/v4/AfformFileUploadTest.php on line 161
```

**Comment by colemanw** [comment]
Oops. Now fixed @seamuslee001

**Comment by seamuslee001** [comment]
@colemanw I tried testing this filling in my test form as an anon user after adding a file upload field to the Constituent Information Custom field. I kept getting a 403 on the civicrm/ajax/api4/Afform/submitFile url

```json
{
    "type": "form",
    "requires": [],
    "title": "Test Form",
    "description": "",
    "is_dashlet": false,
    "is_public": true,
    "is_token": false,
    "server_route": "civicrm/test-form-test",
    "permission": "*always allow*",
    "redirect": ""
}
```
```html
<af-form ctrl="afform">
  <af-entity data="{contact_type: 'Individual', source: 'Test Form'}" url-autofill="0" type="Contact" name="Individual1" label="Individual 1" actions="{create: true, update: true}" security="FBAC" />
  <fieldset af-fieldset="Individual1">
    <legend class="af-text">Individual 1</legend>
    <fieldset class="af-container">
      <div class="af-container af-layout-inline" style="border: 1px solid #000000">
        <af-field name="first_name" />
        <af-field name="middle_name" />
        <af-field name="last_name" />
        <af-field name="birth_date" />
        <af-field name="display_name" />
        <af-field name="constituent_information.Test_File_Field" />
      </div>
    </fieldset>
  </fieldset>
  <button class="af-button btn-primary" crm-icon="fa-check" ng-click="afform.submit()">Submit</button>
</af-form>
```

**Comment by colemanw** [comment]
@seamuslee001 good catch. I had forgotten to declare permissions for the new "submitFile" api action.
I've fixed it now.

**Pull request merged**
