### PR TITLE
Refs CRM-21268 Missing French overseas departments.

### PR DESCRIPTION
**Pull request by nowszy**
Overview
----------------------------------------
Refs CRM-21268

---

 * [CRM-21268: Missing French overseas departments.](https://issues.civicrm.org/jira/browse/CRM-21268)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins ok to test

**Comment by seamuslee001** [comment]
Jenkins retest this please

**Comment by seamuslee001** [comment]
Jenkins retest this please

**Comment by seamuslee001** [comment]
ping @eileenmcnaughton @totten i have tested the upgrade locally and confirmed it adds in the overseas territories correctly. This is good to merge

**Comment by nowszy** [comment]
Why tests have failed? It seems to be not related to my changes.

**Comment by seamuslee001** [comment]
@nowszy the test failure was a temporary failure due to geocoding limits. I have got the system to re-run the tests and they now pass

**Comment by mlutfy** [comment]
I reviewed the code and had a quick look at the test site that was generated. I also note that 4.7.26 being branched, 4.7.27 is the correct file. Merging.

Thanks @nowszy @seamuslee001 !

**Pull request merged**
