### PR TITLE
Membership User Dashboard.tpl adding Recurring links and cleanup

### PR DESCRIPTION
**Pull request by shaneonabike**
Overview
----------------------------------------
In order to improve the UX experience for people on the User Dashboard I wanted to add the Recurring links (Cancel Subscription, Update Billing, and Update Recurring Amount). These are normally available in a Contribution email, but while useful I felt it would be good that we include them also in the dashboard.

As well, I have a few folks confused about the `Renew Now` link as it implies that the Membership needs to be renewed and appears _even_ when the Membership is Active and not in Grace. So I wanted to change that around a bit.

Finally, I standardized all the buttons to the same format as the rest of the buttons to be consistent.

Before
----------------------------------------
Selection_023

After
----------------------------------------
Selection_022

Selection_024

Comments
----------------------------------------
+ Not sure if the way that I am "checking" the status to display the `Renew Now` is correct, but I'm happy to change that if need be
+ If people think we should add an icon I'm happy to add one as well for easier identification

### CODE REVIEW

**Comment by colemanw** [comment]
I would have liked to see these changes go into the new [user_dashboard extension](https://github.com/civicrm/civicrm-core/tree/master/ext/user_dashboard) rather than this old .tpl file which is likely to be deleted once that extension is done.
See further discussion at https://github.com/civicrm/civicrm-core/pull/27792

That said, I'm not against adding these changes to the tpl for now. Realistically it will be a few years before it gets deleted, so that might suit your timeframe.

**Comment by shaneonabike** [comment]
I think that is totally a fair request. If we can merge this and then I can (not right away) make a a merge request against the new extension I will be happy to do that as well.

**Comment by colemanw** [comment]
@composerjk I believe you use this feature - can you review this PR?

**Comment by adixon** [comment]
Definitely looks like an improvement to a feature my clients rarely use (but might be more willing to use now). I can't say much about the code except that I don't see anything wrong with it and that counts for very little. With membership stuff, I always worry about edge cases, but since this is a display feature for authenticated users, what's the worst that could happen? Thanks shane!

**Comment by mlutfy** [comment]
I work at the same shop as Shane, but for what it's worth, we use this feature regularly (instead of custom dashboards), and we will backport the patch to all our clients, so it should help catch any issues if there are any (although admittedly, not many of our clients use auto-renew memberships).

**Comment by colemanw** [comment]
That seems like sufficient consensus.

**Comment by composerjk** [comment]
At a glance, it seems reasonable. One thing to check:

When comparing`$activeMember.status` against `Current`, does `New` also need to be checked? Or does `$activeMember.status` get set to `Current` even during that window of a current membership being set as `New` (for the first 3 months, by default)?

I'm not in a position to test this morning. But, that's the main thing that I noticed.

**Comment by shaneonabike** [comment]
@composerjk Of course! I totally don't know how I missed that. I'll create a new merge request to quickly repair that!

**Pull request merged**
