### PR TITLE
SearchKit - enable search by case role

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Permits searching for contacts by case role in SearchKit.

image

Technical Details
----------------------------------------
Required heavy refactoring of the APIv4 EntityBridge code to permit asymmetric bridges and bridges to multiple entities.

Comments
----------------------------------------
In order to feel safe about this refactor I added a bunch of test coverage.

### CODE REVIEW

**Comment by colemanw** [comment]
Retest this please

**Comment by kurund** [comment]
@colemanw 

Overall working fine and the use case mentioned is working fine. Noticed minor glitch.

screenshot-wp localhost_7979-2021 11 26-11_28_51

Duplicate contacts are listed. However, grouping by contact id does fix it.

Tested few other searches and refactoring didn't have regressions.

**Comment by colemanw** [comment]
@kurund that's because without specific relationship types specified, it is returning both sides of each relationship - in the screenshot, Alida Adams is clearly the case client, so is getting returned as the "B" side of each relationship. Adding an ON clause could filter those out.

**Comment by Guydn** [comment]
I have CiviCRM 5.44 and Compucorp Case extension 2.4.0 (last one). I use a lot Civicase.
The PR was implemented. 
Searches with cases (dossier in French) were broken, see screenshots. Maybe I should have done some technical action (caches, database action, ...) ....

PEC case search
PEC case history
PEC ist of activities
PEC list of case

And I tried to build one search (from contact) and I was not able to see the new entities (contact case roles).
The PR was rolled back immediately.

**Review by kurund — APPROVED** [review]
@colemanw

Okie that makes sense. Good to merge IMO

**Comment by kurund** [comment]
@Guydn 

Do you mean you are running the master branch? Can you check without the case extension to rule out potential issues with the extension?

**Comment by Guydn** [comment]
I have just tried another time. Caches were cleaned.
 It works, as you can see I the screenshot. I do get the report with case and case coordinator :-).
PEC patch case roles
I saw this time the new entities case client case contact roles.
The previous searches are ok.
However I have lost all the forms, related my previous searches

**Comment by colemanw** [comment]
Thanks for retesting this @Guydn. I think the issue you experienced with missing forms is unrelated to this PR, as this doesn't touch any form code.

**Pull request merged**
