### PR TITLE
dev/core#561 Convert birth_date & deceased_date to datepicker

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Convert birth_date & deceased_date to datepicker

Before
----------------------------------------
birth_date & deceased_date don't use datepicker

After
----------------------------------------
Now they do

Technical Details
----------------------------------------
Part of ongoing effort to eliminate jcalendar

Comments
----------------------------------------
@seamuslee001 well these 2 don't seem so hard

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton i tested this, upgraded worked well date fields look good, on the relative date search tho it produced an error

```
Oct 29 07:24:08  [error] $Fatal Error Details = Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => handle
        )

    [code] => -19
    [message] => DB Error: no such field
    [mode] => 16
    [debug_info] => SELECT DISTINCT LEFT(contact_a.sort_name, 1) as sort_name
       FROM civicrm_contact contact_a
      WHERE  ( civicrm_contact.birth_date BETWEEN '20161030000000' AND '20191029235959' )  AND (contact_a.is_deleted = 0)

      GROUP BY sort_name
      ORDER BY sort_name asc [nativecode=1054 ** Unknown column 'civicrm_contact.birth_date' in 'where clause']
    [type] => DB_Error
    [user_info] => SELECT DISTINCT LEFT(contact_a.sort_name, 1) as sort_name
       FROM civicrm_contact contact_a
      WHERE  ( civicrm_contact.birth_date BETWEEN '20161030000000' AND '20191029235959' )  AND (contact_a.is_deleted = 0)

      GROUP BY sort_name
      ORDER BY sort_name asc [nativecode=1054 ** Unknown column 'civicrm_contact.birth_date' in 'where clause']
    [to_string] => [db_error: message="DB Error: no such field" code=-19 mode=callback callback=CRM_Core_Error::handle prefix="" info="SELECT DISTINCT LEFT(contact_a.sort_name, 1) as sort_name
       FROM civicrm_contact contact_a
      WHERE  ( civicrm_contact.birth_date BETWEEN '20161030000000' AND '20191029235959' )  AND (contact_a.is_deleted = 0)

      GROUP BY sort_name
      ORDER BY sort_name asc [nativecode=1054 ** Unknown column 'civicrm_contact.birth_date' in 'where clause']"]
```
I think its because civicrm_contact should actually be contact_a i think

**Comment by eileenmcnaughton** [comment]
ah makes sense - I guess we can wrangle that

**Comment by eileenmcnaughton** [comment]
@seamuslee001 OK - fixed

**Comment by seamuslee001** [comment]
Re-tested and confirmed that the fatal is gone and results are correct Merge on Pass

**Pull request merged**
