### PR TITLE
dev/core#778: Prevent Changing Amount on Membership Validation Fail

### PR DESCRIPTION
**Pull request by MiyaNoctem**
Overview
----------------------------------------
After submitting a membership creation form, if any validation errors occured, the form would be rebuilt, overriding the minimum fee for all membership types with the amount submitted on the form. Furthermore, if the financial type included taxes, these would get calculated and added again to the amount, causing the total amount to increase by the tax rate for every time the form's
validation failed.

Before
----------------------------------------
If an error was found on membership form validation, the submitted total amount was being used to override the minimum fee for all membership types. If the financial type associated to the membership also had taxes added to it, front end would then use this amount to calculate taxes and add them again. Thus, every time the validation failed, taxes would get recalculated and added to the amount.

After
----------------------------------------
Fixed by only overriding amount of selected membership type and subtracting tax amount from total amount.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Oh wow that's awful, I'll take a look - this feels like it's adding handling to address something but there is an underlying sillyness that might be what we should be changing instead.

We'd need a test on this somehow - I'll give it some thought

**Comment by MiyaNoctem** [comment]
@eileenmcnaughton , yeah quite nasty. I do agree this is a reactive approach to fixing this, and thought on a couple of alternatives, but they would require pretty big changes in front and back-end. We could, for example, have all tax calculations done by back-end, and front-end just display the values. If tax is set for the financial type, front-end could show the amount of the tax, calculated using rate and given amount, but not change the total amount. Yeah, I think that could be the cleaner approach. Having all calculations done in front-end may require some more artifacts (eg. store original amounts for the membership to check if user changed the value or not).

Let me know what you think.

**Comment by MiyaNoctem** [comment]
@eileenmcnaughton , have you given any thought to this? Do you think we can ship it like it is? Or should I try some other solution?

**Comment by eileenmcnaughton** [comment]
@MiyaNoctem I dug in - I think the answer is to have the 'with tax' value always available to js from the php layer & to simplify the js down - this PR is not the fix but it lays the groundwork for it

https://github.com/civicrm/civicrm-core/pull/16059

**Comment by MiyaNoctem** [comment]
@eileenmcnaughton, I had a look at your PR and I think I understand what you're suggesting. So the idea would be to use CRM_Member_BAO_Membership::buildMembershipTypeValues() to feed that data to the template, so it is all available on the front-end and it can do all calculations right?

I'll wait for your PR to be merged, though, so I can rebase my work on it to implement this fix.

**Comment by eileenmcnaughton** [comment]
The above patch is merged - it should be possible now to do

```
diff --git a/templates/CRM/Member/Form/Membership.tpl b/templates/CRM/Member/Form/Membership.tpl
index 8dd6f42ab5..b091a45d51 100644
--- a/templates/CRM/Member/Form/Membership.tpl
+++ b/templates/CRM/Member/Form/Membership.tpl
@@ -276,9 +276,8 @@
         // skip this for test and live modes because financial type is set automatically
         cj("#financial_type_id").val(allMemberships[memType]['financial_type_id']);
         var term = cj('#num_terms').val();
-        var taxRates = {/literal}{$taxRates}{literal};
         var taxTerm = {/literal}{$taxTerm|@json_encode}{literal};
-        var taxRate = taxRates[allMemberships[memType]['financial_type_id']];
+        'tax_rate' => $values['tax_rate'],
       ];
     }
 
diff --git a/templates/CRM/Member/Form/Membership.tpl b/templates/CRM/Member/Form/Membership.tpl
index 8dd6f42ab5..b091a45d51 100644
--- a/templates/CRM/Member/Form/Membership.tpl
+++ b/templates/CRM/Member/Form/Membership.tpl
@@ -276,9 +276,8 @@
         // skip this for test and live modes because financial type is set automatically
         cj("#financial_type_id").val(allMemberships[memType]['financial_type_id']);
         var term = cj('#num_terms').val();
-        var taxRates = {/literal}{$taxRates}{literal};
         var taxTerm = {/literal}{$taxTerm|@json_encode}{literal};
+        'tax_rate' => $values['tax_rate'],
       ];
     }
 
diff --git a/templates/CRM/Member/Form/Membership.tpl b/templates/CRM/Member/Form/Membership.tpl
index 8dd6f42ab5..b091a45d51 100644
--- a/templates/CRM/Member/Form/Membership.tpl
+++ b/templates/CRM/Member/Form/Membership.tpl
@@ -276,9 +276,8 @@
         // skip this for test and live modes because financial type is set automatically
         cj("#financial_type_id").val(allMemberships[memType]['financial_type_id']);
         var term = cj('#num_terms').val();
-        var taxRates = {/literal}{$taxRates}{literal};

```

Although that is a further cleanup rather than the fix to this

**Pull request closed without merging**
