### PR TITLE
contributor_key.yml: add civiservice.de to four users, remove one duplicate

### PR DESCRIPTION
**Pull request by sebalis**
Hi, on behalf of my colleagues at civiservice.de @AHowiller, @Detsieber, @mariav0 and @TobiasVoigt I would like to augment their data in contributors_keyxml by stating civiservice.de as their organization. This was decided in a civiservice.de meeting yesterday (Thursday). Also I am adding Maria’s surname (with her permission) and removing a duplicate occurence of my own data.

Thanks for merging :-)

### CODE REVIEW

**Comment by sebalis** [comment]
Okay, it turns out that I can’t count to four (see commit message), but the change of data is still what everyone wants :-)

**Comment by sebalis** [comment]
push --force has come to my rescue :-)

**Comment by eileenmcnaughton** [comment]
@sebalis so the intent it is to remove yourself? @agh1 what is the implication for release notes if someone is removed?

**Comment by eileenmcnaughton** [comment]
Oh I see - it's only your doppelganger we are removing....

**Pull request merged**
