### PR TITLE
CRM-19496 Removed check for group contact delete

### PR DESCRIPTION
**Pull request by Edzelopez**
---
- CRM-19496: Unable to remove contacts from group
  https://issues.civicrm.org/jira/browse/CRM-19496

### CODE REVIEW

**Comment by Edzelopez** [comment]
Reason for removing the check:

This check returns an error every time someone tries to Remove/Rejoin/Delete a contact from a group using the functionality provided under the Groups tab. This is because the status is passed alongwith the $params and thus the API conducts a check which will never return any results.

For eg. If a person is added to the group, when the user clicks Remove, the status "Removed" is sent as a param to the API. The API does a check to see if the user is already present in the group, but uses the status = Removed param. In such a case, since the user hasn't been removed yet, the API returns a count == 0 which then throws an exception. I'm not sure if this check is required, but if it is indeed required, then it would need some sort of filtering of status vs REST API use cases.

**Review by JoeMurray — CHANGES_REQUESTED** [review]
I'm a bit reluctant to make this change down inside this function. Wouldn't it be better to adjust the $params passed to the function so they don't include 'Removed', at whatever layer decides to call this function?

**Comment by seamuslee001** [comment]
I opened and got an alternate PR to work here https://github.com/civicrm/civicrm-core/pull/9248 which has now been merged by @colemanw  

@JoeMurray @Edzelopez The check is required as its needed for Syntax Conformance Tests as the tests expect the delete api to throw and exception if it can't find row to delete. Because of passing an invalid id. 

Also we need to be able to have status passed as a param into the groupcontact.delete call anyway in case people are doing it from 3rd party code.

**Comment by seamuslee001** [comment]
Also it's worth noting that the rejoin a group uses the delete function as well and passes a status of Added in

**Pull request closed without merging**
