### PR TITLE
Resolve dev/core#2768 Reinstate code into APIv4 that handled magic fu…

### PR DESCRIPTION
**Pull request by seamuslee001**
…nctions

Overview
----------------------------------------
This aims to resolve https://lab.civicrm.org/dev/core/-/issues/2768 by putting back in the code for the magic function call that was copied across to the trait

Before
----------------------------------------
Cannot use setLangauge on an abstract action

After
----------------------------------------
can

ping @eileenmcnaughton @totten @colemanw

### CODE REVIEW

**Comment by colemanw** [comment]
Is the only difference that one triggers `API_Exception` and the other triggers `CRM_Core_Exception`?

**Comment by seamuslee001** [comment]
@colemanw this also seems different https://github.com/civicrm/civicrm-core/pull/21235/files#diff-780f41610781b746530c5bce9688972d2099f79432b94a6de67a50caad3f9e9eR204 but yes broadly I think it is the Exception difference and it doesn't make sense to use API_Exception in the trait. I also tried doing it as some kind of a wrapper but couldn't make it work

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @colemanw so yes this would have saved me a lot of debug & hopefully will save someone else.

I think the only argument against doing it is that it offends our developer sensibilities when we feel sure we must be able to do it with less lines - which is probably the wrong priority. 

@seamuslee001 could you bang a test along these lines in

```
  public function testV4Exception() {
    $this->expectException('API_Exception');
    \Civi\Api4\System::flush(FALSE)->getLanguage();
  }
```

- I tried it locally on a 'random class' and it fails correctly
```
Failed asserting that exception of type "CRM_Core_Exception" matches expected exception "API_Exception". Message was: "Unknown method: Civi\Api4\Action\System\Flush::getLanguage()" at
```

**Comment by seamuslee001** [comment]
ok have added the test @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
OK - I'm +1 on merging this - added merge-ready

**Pull request merged**
