### PR TITLE
Remove slow join from activity search

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This removes the unindexed join from activity search. The join is used to apply component
permission filtering and to retrieve the activity_type - however, this latter is still rendered
by the pseudoconstant handling

Before
----------------------------------------
Slow join

After
----------------------------------------
Faster

Technical Details
----------------------------------------

Comments
----------------------------------------
Will need some performance testing on a site that uses ACLs once we have seen if tests fail.

On sites without ACLs it should be clearly faster.

### CODE REVIEW

**Comment by seamuslee001** [comment]
Test fails look related @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@jaapjansma I see you are testing - do you have any sites with ACLs & largish datasets. I haven't cleaned up the tests on this because I was hoping @andrew-cormick-dockery would get a chance to check this for performance. It performs better for contacts not subject to ACLs

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
I did some testing of this on the AUG test infrastructure and didn't notice any significant deterioration in performance. @eileenmcnaughton are you able to fix the test failures

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Test fail unrelated

**Pull request merged**
