### PR TITLE
Pass-thru empty values from api contribution_sendconfirmation

### PR DESCRIPTION
**Pull request by colemanw**

### CODE REVIEW

**Comment by colemanw** [comment]
@seamuslee001 FYI, it's usually better to append new arguments to the end of a function signature to avoid breaking stuff downstream (in this case, webform_civicrm broke from this change).

**Comment by seamuslee001** [comment]
sorry about that @colemanw

**Comment by colemanw** [comment]
No worries, caught it pretty quick.

**Comment by colemanw** [comment]
Merged the first commit into 4.7.13-rc since I caught it before the release.

**Pull request merged**
