### PR TITLE
Set limit to 0 when processing send sms task

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
Select contact more than 25 with a valid  phone type and try to send SMS using 'SMS - schedule/send'

Before
----------------------------------------
only 25 contacts are shown selected  in 'To' field and 25 contacts SMS is sent

After
----------------------------------------
All contacts selected from the search page are shown in 'To' field

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Thanks @pradpnayak. If this broke in 5.44 it might be worth making the PR against 5.49?

**Comment by pradpnayak** [comment]
> Thanks @pradpnayak. If this broke in 5.44 it might be worth making the PR against 5.49?

Yes I did

**Comment by demeritcowboy** [comment]
It needs a little rebasing since now it seems to be picking up another commit.

**Comment by demeritcowboy** [comment]
Looks good now.
Tested and correctly includes all contacts now.

**Comment by agileware-justin** [comment]
The default bug, "Limit 25" strikes again! 🪳🪳🪳

**Pull request merged**
