### PR TITLE
Afform - fix undefined function error

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes bug from 1ff8423300d85100e026741111383cdabd5fce05

Before
----------------------------------------
Error in console, cannot set default value for fields.

After
----------------------------------------
Fixed.

### CODE REVIEW

**Comment by colemanw** [comment]
retest this please

**Comment by totten** [comment]
@colemanw 

* `r-run`: I'm not sure what the original bug is. I played around with using `afform_admin` GUI in Firefox to manipulate defaults on a few fields (`first_name`, `preferred_language`, and custom multi-select with a list of cheeses). The defaults seemed to work about the same before+after the patch. (Although in both cases, the admin UI got a little quirky when re-displaying defaults on the custom multi-select.)
* `r-code`: The idea of the patch looks sensible, based on how the `isMultiple()` function is positioned.

So I'll flag merge ready. If it fixes, then go ahead and merge. (If you need more testing/feedback, then let meknow.)

**Comment by totten** [comment]
Remind me never to get into a wild-west duel with @eileenmcnaughton.

**Comment by eileenmcnaughton** [comment]
@totten lol - I generally figure if someone has just introduced an error & put up a fix they are deep in it

**Comment by colemanw** [comment]
@totten @eileenmcnaughton thanks. The `function isMultiple()` was never defined, so this was a hard error when e.g. setting default values from the URL (it was defined as `this.isMultiple()`).

**Pull request merged**
