### PR TITLE
Avoid confusion between contributors and contributor-key

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
This comes up every couple months. The first line in CONTRIBUTORS.txt was updated a while ago to say it's an archive, but it's not enough to avoid the confusion.

Before
----------------------------------------
CONTRIBUTORS.txt (an archive) gets confused with contributor-key.yml (the currently used file).

After
----------------------------------------
Move CONTRIBUTORS.txt into the release-notes folder and rename it so it has the word archive in the filename.
(Originally was going to leave a stub in the original location so that any links don't break, but there doesn't seem to be anything.)

Technical Details
----------------------------------------
Incertitude in the appellation of the cyberian rolls makes bad.

Comments
----------------------------------------
FYI @joshgowans @agh1 @alifrumin

### CODE REVIEW

**Comment by agh1** [comment]
I'm all for this, but at the same time is anything actually linking to CONTRIBUTORS.txt, either here on GitHub or in a site's code?

**Comment by demeritcowboy** [comment]
I don't see anything in universe but I was thinking more in Bing results or some publication. But yeah it's probably not going to cause any real problems to remove completely.

**Comment by yashodha** [comment]
@demeritcowboy merging this.

**Comment by demeritcowboy** [comment]
Thanks!

**Pull request merged**
