### PR TITLE
CRM-20928 Use cUrl (not file_get_contents) for update check

### PR DESCRIPTION
**Pull request by JohnFF**
Overview
----------------------------------------
Many server hardening guides recommend disabling allow_url_fopen=0. This effectively disabled file_get_contents, which in turn breaks the code that retrieves the pingback to mothership.

Before
----------------------------------------
Pingback would be broken, resulting in a site status error, if the server was configured with allow_url_fopen disabled.

After
----------------------------------------
Works with no error (on sites with PHP curl installed).

Technical Details
----------------------------------------
Uses standard Civi Curl library functions instead. This also coincidentally reduces the pingback code's volume.

Comments
----------------------------------------
Breaks unit tests due to a lack of a remote pingback service to test against. This PR is submitted not in expectation that it will be merged and break unit tests, but at Tim Otten's request.

---

 * [CRM-20928: Use cUrl not file_get_contents for update check](https://issues.civicrm.org/jira/browse/CRM-20928)

### CODE REVIEW

**Comment by mattwire** [comment]
Jenkins, test this please

**Comment by mattwire** [comment]
Test failure seems to be unrelated. I'd say this is good to merge as it improves consistency within CiviCRM.  We can get into a discussion about requiring cURL another day but it's already required as the extensions page uses it via the same CRM_Utils_Httpclient that this PR uses.  @JohnFF It would be nice to see another Jira/PR raised to add a warning to the civicrm status page if cURL is missing?
@colemanw @totten happy to merge?

**Comment by colemanw** [comment]
I don't think the test failure is unrelated. See comment in description of this PR about why it breaks the test.

**Comment by mlutfy** [comment]
jenkins, test this please

(I don't see the test log, and I don't understand why the test is failing?)

**Comment by mlutfy** [comment]
@JohnFF To create a test pingback service, can you open a ticket in the 'ops' project: https://lab.civicrm.org/infrastructure/ops/issues ?

**Comment by eileenmcnaughton** [comment]
I think we should close this & progress #10800 - which we can bring back to life now php 5.3 is gone

**Comment by eileenmcnaughton** [comment]
I'm closing this because I think the way forward is to utilise guzzle

**Pull request closed without merging**
