### PR TITLE
Crm 17763

### PR DESCRIPTION
**Pull request by lcdservices**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by totten** [comment]
The reported test failure seems to be an unrelated bug in the test-class triggered by the new month (Jan). Patch is #7524.

**Comment by totten** [comment]
Chatted a bit with @colemanw on IRC, and passing through the full `report()` data makes the contract/surface-area a bit larger. Passing through the `$mailing` or `$job->mailing_id` seems like less to maintain. The downstream hook implementer can call `report()` if desired. I'm happy to make this change if it's the preferred way.

Alternatively, you could add a unit-test to make sure we meet the enlarged contract, e.g. the test might:
 1. Register a hook listener. Run some assertions to ensure that the hook data looks OK. (`CRM_Core_FieldOptionsTest::setUp` should be a pretty simple demonstration of using a hook in a test.)
 2. Generate and send a mailing. Maybe just copy or edit `api_v3_JobProcessMailingTest::testBasic`.

**Comment by lcdservices** [comment]
yeah, that makes sense. I updated the PR accordingly.

**Comment by colemanw** [comment]
@lcdservices are you adding this hook doc to the wiki?

**Comment by lcdservices** [comment]
I will. but was waiting for it to be merged first.

**Comment by totten** [comment]
Wonderful. Looks like we're good to go.

**Pull request merged**
