### PR TITLE
Standalone - Convert entityTypes to new schema format

### PR DESCRIPTION
**Pull request by totten**
Revision to #30023 entityTypes conversion.
See https://lab.civicrm.org/dev/core/-/issues/4999

This makes the `preInstall` callback more widely available.

### CODE REVIEW

**Comment by totten** [comment]
Fired manual test with Standalone (`phpunit-e2e` and `phpunit-core-exts`). Should show up as: https://test.civicrm.org/job/CiviCRM-Manual-Test/146/

**Comment by ufundo** [comment]
r-runs nicely for me and the manual test looks good :raised_hands: 

should we maybe `extended-tests` for good measure?

**Comment by colemanw** [comment]
Sorry @ufundo saw your comment after merging. If there are problems they should be confined to Standalone.

**Comment by ufundo** [comment]
All good!

**Pull request merged**
