### PR TITLE
Renamed test class.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
I wonder if this test was running before?

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I'm giving this a merge on pass since it is simply fixing a mis-named test class & jenkins is the reviewer here

**Comment by seamuslee001** [comment]
@eileenmcnaughton test failures are related not sure if that was why maybe test class was renamed but not sure if we should dig in before merging this

**Comment by eileenmcnaughton** [comment]
perhaps they never worked :-( @monishdeb you wrote some of this test class... recall anything

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton jenkins appears to be happy now

**Comment by eileenmcnaughton** [comment]
All hail jenkins!

**Pull request merged**
