### PR TITLE
Whitespace cleanup  in invoice template

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Whitespace cleanup  in invoice template

https://github.com/civicrm/civicrm-core/pull/24113/files?w=1

Comments
----------------------------------------
whitespace only - but I think it exposes an extraneous 'if' at the end which I'll dig into after. Note this could be a regression as the sql is not yet regenerated

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
OK - I was wrong about tests not picking up - looks like I need to edit in tests too - still can't see where that if opens

**Comment by eileenmcnaughton** [comment]
[Test Result](https://test.civicrm.org/job/CiviCRM-Core-PR/50444/testReport/) (2 failures / +2)
[CRM_Contribute_Form_Task_InvoiceTest.testInvoiceForDueDate](https://test.civicrm.org/job/CiviCRM-Core-PR/50444/testReport/junit/(root)/CRM_Contribute_Form_Task_InvoiceTest/testInvoiceForDueDate/)
[CRM_Contribute_Form_Task_InvoiceTest.testInvoiceForLineItems](https://test.civicrm.org/job/CiviCRM-Core-PR/50444/testReport/junit/(root)/CRM_Contribute_Form_Task_InvoiceTest/testInvoiceForLineItems/)

**Comment by eileenmcnaughton** [comment]
@demeritcowboy - this is hopefully straight forward....

**Comment by seamuslee001** [comment]
Reviewing this with the ?w=1 mode everything looks right

**Comment by eileenmcnaughton** [comment]
thanks @seamuslee001

**Pull request merged**
