### PR TITLE
[REF] simplify & add tests on getMappingParams

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
More code cleanup for export + Tests extended to cover search builder (all that operator stuff

Before
----------------------------------------
Less re-usable

After
----------------------------------------
More re-usable

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton 

> Test Result (1 failure / -989)
>    CRM_Core_BAO_MappingTest.testSaveMappingFields with data set #0

**Comment by eileenmcnaughton** [comment]
Argh introduced an enotice - should pass this time

**Comment by eileenmcnaughton** [comment]
@colemanw it passed!

**Comment by eileenmcnaughton** [comment]
@colemanw of the open refactors I think this one is most on your critical path

**Comment by colemanw** [comment]
A variable named `$v` is pretty mysterious... but this fn doesn't have to be beautiful.

**Pull request merged**
