### PR TITLE
CRM-17762 fix pledge edit for to not needlessly delete schedule data

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
This prevents edited schedule data being deleted when unrelated data is edited (e.g campaign, email receipt)

---
- [CRM-17762: Pledge schedule data lost when unrelated edits are done](https://issues.civicrm.org/jira/browse/CRM-17762)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw how does QA work on something like this in a post-Dave world? Normally where things touch on forms at this stage of the cycle I wouldn't merge them without some sort of blessing from Dave. But now we are Daveless....There are a couple of other PRs in a similar category.

**Comment by colemanw** [comment]
In general I would like to move us from "Dave manually tests everything" over to "The PR comes with a unit test and the core team does a quick code review before merging"

**Comment by eileenmcnaughton** [comment]
Generally in the past manual testing has been the focus for form flows (like this one - the api pretty well by-passes this). I'm happy just to merge it - but I think Dave's testing picked up an awful lot of stuff that wasn't otherwise found.

**Comment by eileenmcnaughton** [comment]
NB - Dave's testing also meant that the UI was being regularly QA'd for any changes de facto. I can understand where you want to move to - but I think our code coverage is a very long way from that & there are real blockers to adding unit tests in many cases so it's definitely not going to happen overnight

**Comment by eileenmcnaughton** [comment]
OK - I'll merge this - I've been using the patch in production against 4.6 so it must work....

**Pull request merged**
