### PR TITLE
Revert merge from master

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton i think you broke the RC with this https://github.com/civicrm/civicrm-core/commit/3c8e8aabad4502b0d1e95cd5e78615cfd17f6058 because it moved it to .20. I believe this correctly reverts that commit pining @davejenx as well

**Comment by seamuslee001** [comment]
I think we should probably revert this as well https://github.com/civicrm/civicrm-core/commit/3c8e8aabad4502b0d1e95cd5e78615cfd17f6058

**Comment by eileenmcnaughton** [comment]
ug did I - that seems like a very big commit!

**Comment by seamuslee001** [comment]
yeh

**Comment by eileenmcnaughton** [comment]
Yuck yuck yuck  - expletitives! I did have this moment  when something wierd happened but!!!

**Comment by seamuslee001** [comment]
@eileenmcnaughton i have reverted the other merge from master just as a precautionary measure

**Comment by eileenmcnaughton** [comment]
oh - so I merge the wrong way around???

**Comment by seamuslee001** [comment]
@eileenmcnaughton i think so, I think you were hoping to merge 4.7.19 -> master not master -> 4.7.19

**Comment by eileenmcnaughton** [comment]
This seems to be the PR - but is says into master https://github.com/civicrm/civicrm-core/pull/10266

**Comment by seamuslee001** [comment]
I think you were trying to fix jenkins issues so this https://github.com/civicrm/civicrm-core/pull/10266/commits/c85b067db283912cf2bcf91123c1fc675716c998 and https://github.com/civicrm/civicrm-core/pull/10266/commits/3c8e8aabad4502b0d1e95cd5e78615cfd17f6058 are the problem commits

**Comment by eileenmcnaughton** [comment]
screenshot 2017-04-29 00 57 29

That's so confusing - I see 2 separate things on this screen

**Comment by seamuslee001** [comment]
so the overall PR was merged into master but that commit was merging master branch into 4.7,19 and i think its only showing what elements of that commit make up part of the PR i think

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by eileenmcnaughton** [comment]
OK - that seems like you are right to me - I think we should let @guanhuan @totten @colemanw know & merge this on pass 

If we feel like normality is not returned we should consider skipping a release.

Offending PR link is https://github.com/civicrm/civicrm-core/pull/10266

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by totten** [comment]
After we fix this, I expect folks will habitually resume the practice of forward-porting RC fixes to `master` -- but wouldn't that cause a sort of reverberation where the revert ultimately applies to `master`?

Feels like we need to either:
 1. Do a revert like #10277; then all forward-porting via cherry-pick?
 2. Do a rewrite of the history (force-push) so that this never happened?

**Comment by totten** [comment]
> That's so confusing - I see 2 separate things on this screen
> ...
> Offending PR link is #10266

I think it's confusing because #10266 didn't actually *cause* the problematic merge, but it's one of the few places where the problematic merge is *visible*. Pay close attention to the text of the merge message:

 * "Merge branch 'master' into 4.7.19-rc" ==> that's how it looks if you use `git merge`. 
 * If this had been done through the Github UI, then it'd say something like "Merge pull request #9982  from eileenmcnaughton/4.7.19-rc2".

Theory:
 * Something like this was done via CLI: `git checkout 4.7.19-rc ... git merge master ... git push origin 4.7.19-rc`. 
 * (Plausible? Well, some folks use a personal dev-branch with the same name as the canonical branch, and then it's easy to mix-up: `git push myuser 4.7.19-rc` and `git push origin 4.7.19-rc`.) 
 * Later on, #10266 aimed at forward-porting `4.7.19-rc` changes to `master`. The errant merge commit appears in the history, but it's basically a nullop (because `master` already has `master` commits), so it hardly registers as a blip in the Github UI.

**Comment by eileenmcnaughton** [comment]
I did have a moment when I was trying to merge something into 4.7.19 & suddenly it was already there - I checked my repos to see if I had pushed to 4.7.19rc but it's set up via https - which means entering a username & password

upstream        https://github.com/civicrm/civicrm-core.git

**Pull request closed without merging**
