### PR TITLE
Fix: Batch update participants with checkboxes fails

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/issues/89
Fix error when trying to use batch update with custom checkboxes

Before
----------------------------------------
Does not submit

After
----------------------------------------
Does submit, unit tested

Technical Details
----------------------------------------
For readability I will rebase once https://github.com/civicrm/civicrm-core/pull/12048 is merged - the actual changes for this are quite minor

Comments
----------------------------------------
I suspect other batch updates may have a similar bug :-(

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
style warning will be ok when rebase is done

**Comment by mattwire** [comment]
@eileenmcnaughton It's a bit hard to see what code was changed because of the move to a separate function?  Can you give us a clue.  Also note that you may want to take a look at CRM_Core_Task_Batch which currently is only used for cases but should be easy to extend to other batch tasks when time is available.

**Comment by eileenmcnaughton** [comment]
@mattwire - this is the 'first' PR - #12048 per above - sorry if it wasn't clear

**Comment by monishdeb** [comment]
Tested the patch here's the before/after

BEFORE
----------------------------------------
test-multiple-before

AFTER 
----------------------------------------
test-multiple-after

**Comment by eileenmcnaughton** [comment]
@mattwire also, noted on the idea of extending - in this case the slowest parts were replication & writing the unit test so I backed off doing other entities for now - but we could maybe use a data provider for the test which would resolve that

**Comment by eileenmcnaughton** [comment]
@mattwire ok - good point - will tweak that when I rebase over the merged patch

**Comment by eileenmcnaughton** [comment]
Ouch - I accidentally pushed the commit that was for this one into https://github.com/civicrm/civicrm-core/pull/12048 before merging! So I merged by accident. I'm going to merge this too as it is just comments but @monishdeb any chance you can double check you are happy with the merged code now

**Pull request merged**
