### PR TITLE
CiviMail - New widget for selecting recipients

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
When composing a mailing, this replaces the single include/exclude/groups/mailings widget with two widgets, one for include and another for exclude. Groups and mailing are still combined together in autocomplete results, but are loaded more efficiently by APIv4.

Before
----------------------------------------
Single widget for include/exclude groups and mailings. Loading can be quite slow because it has to load 4 times.

image

After
----------------------------------------
Two widgets, each one loads only once so it's much faster:

image

When building the mailing from search results, the hidden group is simply called "Search Results" and cannot be de-selected:
image

Technical Details
----------------------------------------
Builds on #26507 to autocomplete a UNION of both groups and mailings. 

Comments
----------------------------------------
Technically, APIv4 is capable of doing enough UNIONs to show each group and mailing twice (for both include and exclude in the same widget). But I personally don't like that UX - I find it cluttered when the same results pop up twice, you end up  scrolling past more things you don't want.

### CODE REVIEW

**Comment by larssandergreen** [comment]
Will be great to have a speedier interface for this. Agreed that include and exclude are better in two fields.

I think for the UI, those narrow fields are going to be pretty painful to use (especially if you have lengthy names for mailings). Maybe one per line instead?

I don't think the "Group by Contact" / "Parent Group by Contact" are useful info and they just make it harder to use by showing fewer groups, suggest removing. The icon is enough to tell you if a group is smart or not.

I like the Unsent/Sent Mailing thing, but would prefer a created or sent date to the name of the creator. Not sure what the third line in there is, seems to be a duplicate of the first one. Order should be in desc by date (created or scheduled/sent), not clear what it is now.

Do we include archived mailings? They are not included in the current widget. I'd say no.

It seems like I can sometimes include and exclude the same group and sometimes cannot. Can't seem to find a rhyme or reason as to when. When I can include and exclude, I can also include or exclude twice. This clears up one save and re-open, but potentially confusing for the user. Good that I can't include or exclude the current mailing.

Not sure if it is related, but I'm getting a more than usual amount of "Sorry an error occurred and your information was not saved" when testing this on a Traditional Mailing (not seeing any on Mosaico).

**Comment by colemanw** [comment]
@larssandergreen I wholeheartedly agree they ought to be put on two lines but unfortunately the angular template is quite brittle and I was unable to do it in a way that was friendly toward Mosaico (which reuses the same template). I was hoping to avoid having to coordinate a syncronized release of Mosaico & core. I'll keep thinking about the smoothest path there, but for now this works for both.

> Do we include archived mailings? They are not included in the current widget. I'd say no.

Yes, the current widget does include them. Debatably it should not, but I didn't want to change too many things at once.

> Not sure what the third line in there is, seems to be a duplicate of the first one.

Can you share a screenshot?

> Order should be in desc by date (created or scheduled/sent), not clear what it is now.

Currently it's ordered by:
1. Groups before mailings
2. Name ASC

Sorting by name is pretty standard for an autocomplete, but I see the argument for date.

**Comment by awestuk** [comment]
Tested this and it's a big improvement! The two dropdowns are faster, and the extra information is useful. It feels much more solid, and all the flakiness of the previous field is gone. 

Agree that archived mailings probably shouldn't be in there, but if they were before then fair enough. It'd be nice to have a small delay before the search kicks in to avoid extra ajax calls. 

(Just as a matter of interest, does the dropdown _have_ to make an ajax call when searching? I only ask because searching/adding multiple groups to the 'In Groups' dropdown in Search Kit is instantaneous, even with our 5k groups.)

**Comment by colemanw** [comment]
Replaced by #26585

**Pull request closed without merging**
