### PR TITLE
dev/core#582 - Search Builder: Switch to new date/timepicker widget

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes some recent regressions with missing datepicker widgets and icons in searchbuilder by using the new `crmDatepicker` widget. This has the upshot of solving 2 longstanding searchbuilder shortcomings: date wasn't displayed in a human-readable format, and time wasn't available to select.

Before
----------------------------------------
Datepicker icon missing in Search Builder date fields.
Datepicker values display in machine format.
No datepicker for Search Builder datetime fields.

After
----------------------------------------
Icon restored for date fields.
Datepicker uses human-readable format.
Date+time widget for datetime fields.

Comments
----------------------------------------
See https://lab.civicrm.org/dev/core/issues/582

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw can you put it against the rc? This will trigger a patch release

**Comment by colemanw** [comment]
@seamuslee001 I've just pushed up a better solution, which switches to use the crmDatepicker widget and fixes a long-standing UX headache of the date not displaying in a user-friendly format.

**Comment by eileenmcnaughton** [comment]
@colemanw I just tested this & contact.modified_date worked but contribution.receive_date didn't

**Comment by colemanw** [comment]
@eileenmcnaughton Ok I think I got it this time (and date).

**Comment by eileenmcnaughton** [comment]
I got an error on searching on receive_date - but am not sure if that relates or was pre-existing 

screenshot 2018-12-12 11 01 36

**Comment by eileenmcnaughton** [comment]
Ah it does relate I think

 $fieldNameTypes[$name] = CRM_Utils_Type::typeToString(CRM_Utils_Array::value('type', $field));

will return Timestamp for a DateTIme field - resulting in the above faulty validation I think.

**Comment by eileenmcnaughton** [comment]
Also AFTER the search the datepicker doesn't load

screenshot 2018-12-12 11 05 52

**Comment by colemanw** [comment]
@eileenmcnaughton I'm not able to reproduce either of those - be sure you've updated your checkout (I've force-pushed to this branch) and cleared your javascript caches.

**Comment by eileenmcnaughton** [comment]
@colemanw I just tried on the pr demo site & it seemed ok so I'll merge it through.

Perhaps we can merge to 5.8 & then re-test the tarball before pushing 5.8.1

**Comment by colemanw** [comment]
Thanks. I'm hoping that @petednz can test this out as well before we push this change into a point release.

**Comment by eileenmcnaughton** [comment]
@colemanw we should probably get it merged to 5.8 branch now though?

**Comment by stesi561** [comment]
Shoreditch is present but not being used (apart from for mosaico).

**Comment by colemanw** [comment]
@stesi561 unfortunately that's one of its quirks - it messes with the Civi page even if you don't mean for it to. Disable the extension completely and you'll see the double-datepicker-icon go away.
It's not a huge bug but one that would be nice to get fixed in Shoreditch.

**Comment by stesi561** [comment]
Cannot disable due to dependencies... :) Okay I'll take your word for it.

**Pull request merged**
