### PR TITLE
(dev/core#4999) Convert xml schema to new entityType.php format

### PR DESCRIPTION
**Pull request by colemanw**
Overview
---------
This overhauls the way schema entities are declared.
Implements plan from https://lab.civicrm.org/dev/core/-/issues/4999

Before
---------
- An entity type (e.g. "Activity") was declared in an xml file (e.g. `xml/schema/Activity/Activity.xml`).
- The GenCode script was used to generate a DAO file (e.g. `CRM/Activity/DAO/Activity.php`) and install/uninstall sql files.
- Note that the xml files themselves were never used at runtime, they were just the source of generated DAO & SQL files.

After
-------
- An entity type (e.g. "Activity") is declared in a php file (e.g. `schema/Activity/Activity.entityType.php`).
- No code needs to be generated. Schema information is read directly from `entityType.php` files at runtime.
- The xml files along with the generated sql files can be deleted.
- DAO files can be [gutted to an empty class](https://github.com/civicrm/civicrm-core/pull/29991) extending `CRM_Core_DAO_Base`.

### CODE REVIEW

**Comment by totten** [comment]
@colemanw OK, so here are forays into synthesizing #29472 and #29422... 

* To generate `civicrm-core:schema/**.entityType.php`, I used https://github.com/totten/civix/pull/342 and simply copied the schema-files to/from placeholder extension. Something like:
    ```bash
    cd sites/all/modules/civicrm
    (cd ext && civix generate:module placeholder)
    mkdir -p "ext/placeholder/xml/schema/CRM"
    cp -r xml/schema/* ext/placeholder/xml/schema/CRM/
    (cd ext/placeholder && civix convert-entity --core-style)
    cp -r ext/placeholder/schema schema
    ```
* [Branch A](https://github.com/civicrm/civicrm-core/compare/master...totten:civicrm-core:master-phpsql-a?expand=1) builds on those files. It also updates all references to `CRM_Core_CodeGen_Schema` and uses `SqlGenerator` instead. So it generate core-core schema from `*.entityType.php`
    * I wanted to see that the new SQL output matches the old SQL output. The basic idea is
        ```bash
        cp sql/civicrm.mysql sql/civicrm.mysql-orig
        ./bin/setup.sh -g
        diff -u sql/civicrm.mysql-orig sql/civicrm.mysql
        ```
    * However, the immediate issue is that `setup.sh` will fail because the table-sort algorithm doesn't work with core tables. (This issue would affect any call path; it's just easier QA in this flow.)
        ```
        Parsing schema description schema/Schema.xml
        Extracting database information
        Extracting table information
        Generating civicrm.config.php
        Generating table list
        Generating sql file

        Fatal error: Uncaught MJS\TopSort\CircularDependencyException: Circular dependency found: Activity->Phone->Contact->Contact
                in .../modules/civicrm/vendor/marcj/topsort/src/CircularDependencyException.php on line 34
        MJS\TopSort\CircularDependencyException: Circular dependency found: Activity->Phone->Contact->Contact
                in .../modules/civicrm/vendor/marcj/topsort/src/CircularDependencyException.php on line 34
        ```

* [Branch B](https://github.com/civicrm/civicrm-core/compare/master...totten:civicrm-core:master-phpsql-b?expand=1) builds on Branch A. It moves the `SqlGenerator` to be part of `civimix-schema`'s `SchemaHelper`. And it still uses that for for core generation.
    * This ~~works~~ _fails in the same way_. So it loads+uses the code from `civimix-schema` to initialize core-core. But `SqlGenerator` dies on the same circular dependency.

For comparison, these are the sort-algorithms floating around:

* [Core's `orderTables()`](https://github.com/civicrm/civicrm-core/blob/5.72/CRM/Core/CodeGen/Specification.php#L152-L164) (*Status-quo sort used by core-core tables*)
* [Civix's `orderTables()`](https://github.com/totten/civix/blob/v23.12.2/src/CRM/CivixBundle/Command/AddEntityBoilerplateCommand.php#L155-L188) (*Status-quo sort used by extensions*)

**Comment by colemanw** [comment]
@totten I think there might be some actual circular dependencies in our schema unfortunately. 🙈 

But looking at the error message you shared it doesn't *look* like a circle (`dependency found: Activity->Phone->Contact->Contact`), so maybe 🤞🏻 🤞🏻 it's a simple matter of doing this? aab3802f106574a1dcd1286ae21c7f123efcd17e

**Comment by totten** [comment]
@colemanw OK, updates: 

* Rebased and combined with `master-phpsql-b`. 
* Extracted a couple small PRs: https://github.com/civicrm/civicrm-core/pull/29825, https://github.com/civicrm/civicrm-core/pull/29826
* We'll probably want to re-run `convert-entity` before a final merge. But it's a lot easier to test the branch if we have some live schema files.
* Can currently run `./bin/setup.sh -g` and view reasonable-looking output (`sql/civicrm.mysql`).
* I've included fixes for several things -- but the generated SQL still doesn't quite run yet.
* A decent way to test is like:
    ```bash
    ./bin/setup.sh -g && amp sql -r ~/bknix/build/dmaster/web/ -Ncivi <  sql/civicrm.mysql
    ```

    (*After we get that working, we can look to `cv core:install`...*)
* Right now, it fails for me with:
    ```
    ERROR 1830 (HY000) at line 2729: Column 'case_type_id' cannot be NOT NULL: needed in a foreign key constraint 'FK_civicrm_case_case_type_id' SET NULL
    ```

**Comment by totten** [comment]
There's an extra set of test-runs attached to the last commit... to confirm that tests will generally work the same in other environments. We encountered one issue which should be fixed. The latest run looks OK. (*The extra tests aren't __green__.... but they are consistent with baseline. [PR supplement](https://test.civicrm.org/duderino/batch/20865826),[baseline](https://test.civicrm.org/duderino/batch/20865827)*)

**Comment by colemanw** [comment]
Everything's passing & the additional test run didn't turn up anything.
Whew! This was a big endeavor!

**Comment by totten** [comment]
Hail, Github, full of grace,
the Testing is with thee.
Blessed art thou amongst data-stores
and blessed is the fruit of the keyboard, CiviCRM
Holy Github, Mother of Patches,
pray for us mergers,
now and at the hour of our commit. 
Amen.

**Comment by colemanw** [comment]
Amen.

**Pull request merged**
