### PR TITLE
ContactSummary - Replace Relationships tab with SearchKit display

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
2nd tab now replaced by a search display (first was [Notes](https://github.com/civicrm/civicrm-core/pull/27610)).

Before
----------------------------------------
Outdated code to render 2 tables: one for active relationships and one for inactive ones.

After
----------------------------------------
Strikingly similar 2-table layout, but uses SearchKit.

Comments
------------
Frustratingly I wasn't able to delete very much of the old code because it's still in use by the obscure "User Dashboard" that most people have never heard of. It would be good to replace that whole thing with SearchKit too.

### CODE REVIEW

**Comment by aydun** [comment]
Relationships like 'Child of' 'Sibling of' have a 'Manage Case' link in the actions menu despite their being no related cases.
image

One thing with rows formatted as 'disabled' is that all the action links are also light grey suggesting that those actions are disabled when they're not.  Maybe leave the formatting of actions alone.  Not specific to this display.

Just noting that this replaces the display in core, not as part of AdminUI or SearchUI that can be disabled.  I think that's ok for this display but if anyone has customised this tab it will force them to change with whichever release contains this.  It would be useful to document how this can be overridden (I think that is create your own tab, and disable this one by going to Formbuilder and unticking the 'Add as tab' option).

**Comment by colemanw** [comment]
@aydun thanks for testing. Oof that looks like a bug in the way the extra join provider works. Yay another rabbit hole blocking SK UI swaps. Down I go...

**Comment by colemanw** [comment]
@aydun fixed!
At this point this PR is about 25% SearchDisplay and 75% fixes and unit tests. So IMO it would be a good thing to merge before branching `master` tomorrow.

**Comment by aydun** [comment]
Nice - fixes the issue above.

**Comment by aydun** [comment]
... and good to see we didn't lose you down the rabbit hole for too long!

**Comment by colemanw** [comment]
Thanks @aydun good to be back, however briefly.

**Pull request merged**
