### PR TITLE
dev/core#3738 - Add APIv4 rekey function

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds a helpful new function to APIv4.

See https://lab.civicrm.org/dev/core/-/issues/3738

### CODE REVIEW

**Comment by colemanw** [comment]
@artfulrobot they are very similar, the differences between this `rekey` and your proposed `pluck` are that:
- `rekey` is more flexible in that you can pass it either an array or a callable.
- `rekey` alters the `Result` and returns `$this` for chainability vs `pluck` which returns the altered array and leaves the Result untouched.
- `pluck` is more flexible in that it can act as a whitelist to filter out unwanted items.

I can see potential advantages of both. Personally I think I'd find `rekey` more useful because the I can't think of any scenarios where I would need those two features from `pluck`:
- Filtering unwanted keys: I would just not add them to the `select` in the first place.
- Not altering the Result: I've never had the need to rekey a result twice in 2 different ways. But if I did need to keep the unaltered results around I could either clone it or store it like `$original = $result->getArrayCopy();` before calling `rekey()`.

But like I said in gitlab, if you can think of a use for `pluck` we can certainly add it as well. Doesn't hurt.

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by colemanw** [comment]
@artfulrobot I feel like this PR got held up on bikeshedding but is actually mergeable as-is.
Just to clarify one possible misunderstanding:

> Callable: not sure I see the use, and incresaes repeated work

It's optional. You don't have to pass a callable you can just pass an array. See unit test which demonstrates both styles.

**Comment by colemanw** [comment]
Thanks.

**Comment by agileware-justin** [comment]
Thank you! 👍🏻

**Pull request merged**
