### PR TITLE
dev/core#2743 Add no-prefetch campaign psuedoconstant

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
dev/core#2743 Add no-prefetch campaign psuedoconstant

Having a pseudoconstant defined does a few things

-  it helps with v3 api performance per https://lab.civicrm.org/dev/core/-/issues/2743
-  it makes v4 api support the syntax `{campaign_id:label}` (without you having to know the 'label' on that particular entity is the title). 
- it causes options to be pre-loaded on some screens - eg. the searchkit update action.

The first 2 of these are always good things. However, the 3rd is bad when there could be many options (eg. for campaigns, groups). Hence we currently have a system where the pseudoconstants have been removed or never added for SOME FK entities.

But - we discussed and agreed that if we can have 1 & 2 without 3 then that is a good thing and we can do that by

1) adding an optional 'prefetch' key
2) updating apiv4 NOT to load options where prefetch is set and is false

Before
----------------------------------------
cannot access campaign_id:name via v4 api

After
----------------------------------------
tada

Technical Details
----------------------------------------
This is only part of the change (& test fails will likely highlight the next part). The goal is to add a new nuance to how apiv4 handles these

This gets us away from the problem we have where pseudoconstants are useful for a few things (not least consistent syntax) but cause performance problems when they are pre-loaded if there are many - e.g campaigns

Comments
----------------------------------------
@colemanw 

Also - docs PR https://lab.civicrm.org/documentation/docs/dev/-/merge_requests/963

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw  this is the first bit

**Comment by colemanw** [comment]
I think you may have a false sense of security because in this PR you are adding back something that previously existed, so we know it's not going to be catastrophic. However, I note that the goal here is to add pseudoconstants as a convenience lookup for fields that already have an FK, so in the near future we might add a pseudoconstant for e.g. `Participant.contact_id:label` to get the display name of the participant with a handy shortcut. Neat! And also, Crash! Here's what it will do:

- Every time a Participant record is created or updated with APIv3, the `contact_id` value will pass through `_civicrm_api3_validate_integer` which in turn calls `_civicrm_api3_api_match_pseudoconstant`, which will fetch every contact in the database and store it in an array :)
- UIs that rely on pseudoconstants will attempt to load every contact in the database and present it on a form. For example, Search Builder and the APIv(3|4) Explorer will try to load them all into javascript.

It seems like the line of demarcation for whether or not we want this is the presence of a real FK on the field (as opposed to a pseudo-fk to an option_value). And in that case, the "prefetch" flag might actually be redundant. What if we teach our various UIs to prefer FKs over pseudoconstants when available, then the 2 can co-exist relatively peacefully.

**Comment by eileenmcnaughton** [comment]
@colemanw OK - you are right in that this fixes the immediate but dangles a future possibility that it can't meet...

But, I'm not sure the line is whether there is an FK or not - the obvious ones like financial_type_id definitely need to be passed through validate_integer.

If we adjusted apiv3, apiv4 & search kit to 'care about' prefetch would that future proof us (I was initially expecting to do that for v4 & search kit but leave v3 as in this case it's being described as a performance regresson but we could add a v4-like approach to v3 on that)

**Comment by seamuslee001** [comment]
closing as this was included in #21046 which has now been merged

**Pull request closed without merging**
