### PR TITLE
Test fix to catch dev/core#2231 - I need to retest this as it didn't fail on jenkins when it should have

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
The orignal test had a somewhat convoluted flow to set up the artifacts
which bypassed our preferred flow & meant it did not pick up a bug in that
flow. This alters the test to catch that

Overview
----------------------------------------
_A brief description of the pull request. Keep technical jargon to a minimum. Hyperlink relevant discussions._

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by seamuslee001** [comment]
well the test still passed

**Comment by eileenmcnaughton** [comment]
@seamuslee001 yeah - which is odd since I don't think the other is merged through yet... I did replicate the test failing locally I believe

**Comment by seamuslee001** [comment]
@eileenmcnaughton I had been holding off merging 5.33 so you could try and make this properly fail but given 5.33 is merged I'm not sure what to do with this PR

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I'll test again locally to see whether I can break it:-)

**Comment by eileenmcnaughton** [comment]
Closing until I can confirm this is right

**Pull request closed without merging**
