### PR TITLE
Switch docblock code to use markdown syntax.

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
We are moving toward markdown in docblock comments. This is a step in that direction.

Before
----------------------------------------
    /**
     * Docblocks would look like this:
     *
     * @code
     *   $foo = 'bar';
     * @endCode
     */

After
----------------------------------------
    /**
     * Docblocks look like this:
     *
     * ```
     *   $foo = 'bar';
     * ```
     */

Comments
----------------------------------------
APIv4 already uses a markdown parser for docblocks, so this is just another step in that direction.

### CODE REVIEW

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
retest this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
test this please

**Comment by colemanw** [comment]
test this please

**Pull request merged**
