### PR TITLE
Crm 16029 default financial accounts translated

### PR DESCRIPTION
**Pull request by jaapjansma**
CRM-16029 - create financial type in localised CiviCRM. Improved Johanv's commit. See https://issues.civicrm.org/jira/browse/CRM-16029

### CODE REVIEW

**Comment by davecivicrm** [comment]
@jaapjansma  and @eileenmcnaughton Note that I tested this PR - and it did not work for me. Details here: https://issues.civicrm.org/jira/browse/CRM-16029?focusedCommentId=79373&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-79373

**Comment by jaapjansma** [comment]
Thanks @eileenmcnaughton for testing this. Follow up is in the issue. I have also tested the master branch with and without this patch and it looks like the bug this patch is addressing does not exist in the master nor in the 4.6 branch. It does exist in a 4.4 branch.

**Comment by eileenmcnaughton** [comment]
Jaap - so, you are comfortable the 4.4 fix is good - it certainly looked safe

**Comment by colemanw** [comment]
Wrapping the strings in `ts()` is clever, but the real fix would be to use machine names instead of labels.
Really the function `accountOptionValues` ought to be deprecated and removed as it's redundant with a much better function that can actually do what you want: `CRM_Core_PseudoConstant::get`.

Replace lines 228 and 229 with that function to fetch names instead of labels, and the rest of the PR becomes unnecessary.

**Comment by davecivicrm** [comment]
Closed in favor of https://github.com/civicrm/civicrm-core/pull/6759

**Pull request closed without merging**
