### PR TITLE
dev/core/issues/569, Fixed DB Error: no such field when the user tries to search by the 'Address Location' field

### PR DESCRIPTION
**Pull request by pradpnayak**
https://lab.civicrm.org/dev/core/issues/569

Overview
----------------------------------------
DB Error: no such field when the user tries to search by the 'Address Location' field

Before
----------------------------------------
No Error

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@pradpnayak are you able to add a test for this?

**Comment by kcristiano** [comment]
@pradpnayak this PR no longer applies cleanly.   Should we close or will you rebase and add tests?

**Comment by eileenmcnaughton** [comment]
@pradpnayak I wrote a test for this but your fix didn't work :-(

I'm pretty sure the code has changed since you wrote it so it is no longer the fix so I'm closing - this was the test

```
index 8f35c2d845..f79519edb4 100644
--- a/tests/phpunit/CRM/Contact/SelectorTest.php
+++ b/tests/phpunit/CRM/Contact/SelectorTest.php
@@ -48,7 +48,7 @@ class CRM_Contact_SelectorTest extends CiviUnitTestCase {
    * @throws \Exception
    */
   public function testSelectorQuery($dataSet) {
-    $params = CRM_Contact_BAO_Query::convertFormValues($dataSet['form_values'], 0, FALSE, NULL, []);
+    $params = CRM_Contact_BAO_Query::convertFormValues($dataSet['form_values']);
     foreach ($dataSet['settings'] as $setting) {
       $this->callAPISuccess('Setting', 'create', [$setting['name'] => $setting['value']]);
     }
@@ -71,9 +71,9 @@ class CRM_Contact_SelectorTest extends CiviUnitTestCase {
       $this->assertLike($this->strWrangle($queryString), $this->strWrangle($sql[$index]));
     }
     // Ensure that search builder return individual contact as per criteria
-    if ($dataSet['context'] == 'builder') {
+    if ($dataSet['context'] === 'builder') {
       $contactID = $this->individualCreate(['first_name' => 'James', 'last_name' => 'Bond']);
-      if ('Search builder behaviour for Activity' == $dataSet['description']) {
+      if ('Search builder behaviour for Activity' === $dataSet['description']) {
         $this->callAPISuccess('Activity', 'create', [
           'activity_type_id' => 'Meeting',
           'subject' => "Test",
@@ -109,6 +109,8 @@ class CRM_Contact_SelectorTest extends CiviUnitTestCase {
 
   /**
    * Test the civicrm_prevnext_cache entry if it correctly stores the search query result
+   *
+   * @throws \CRM_Core_Exception
    */
   public function testPrevNextCache() {
     $contactID = $this->individualCreate(['email' => 'mickey@mouseville.com']);
@@ -173,6 +175,21 @@ class CRM_Contact_SelectorTest extends CiviUnitTestCase {
    */
   public function querySets() {
     return [
+      [
+        [
+          'description' => 'Weird location test',
+          'class' => 'CRM_Contact_Selector',
+          'settings' => [],
+          'form_values' => [['location_type-1', 'LIKE', '%', 1, 0]],
+          'params' => [],
+          'return_properties' => NULL,
+          'context' => 'builder',
+          'action' => CRM_Core_Action::NONE,
+          'includeContactIds' => NULL,
+          'searchDescendentGroups' => FALSE,
+          'expected_query' => [],
+        ],
+      ],
       [
         [
           'description' => 'Empty group test',

````

**Comment by pradpnayak** [comment]
Updated PR at https://github.com/civicrm/civicrm-core/pull/18341

**Pull request closed without merging**
