### PR TITLE
CRM-19330

### PR DESCRIPTION
**Pull request by spalmstr**
Suppress Add Contacts to Group where user does not have Edit All Groups permission.

---
- [CRM-19330: Add Contacts to Group appears in reports where user can't even view all contacts under Joomla](https://issues.civicrm.org/jira/browse/CRM-19330)

### CODE REVIEW

**Comment by spalmstr** [comment]
Once again a PR has failed with:
No report files were found. Configuration error?

**Comment by spalmstr** [comment]
This one fails with the same error as others I have submitted.

**Comment by seamuslee001** [comment]
@spalmstr Stephen the error is here In "sites/all/modules/civicrm/", rename "master" to "backup-master-20161006164106-21".
In "sites/all/modules/civicrm/", create "master" using "origin/master".
In "sites/all/modules/civicrm/", apply "https://github.com/civicrm/civicrm-core/pull/9184" on top of "c210663cc5c65b0dea881f49ca37f0db3abd81ce".

                                                                                     
  [GitScan\Exception\ProcessErrorException]                                          
  Process failed:                                                                    
  [[ COMMAND: git apply --check --ignore-whitespace ]]                               
  [[ CWD: /home/jenkins/buildkit/build/core-9184-89kzy/sites/all/modules/civicrm ]]  
  [[ EXIT CODE: 1 ]]                                                                 
  [[ STDOUT ]]                                                                       
  [[ STDERR ]]                                                                       
  error: patch failed: CRM/Report/Form.php:1498                                      
  error: CRM/Report/Form.php: patch does not apply  

What that means to me is that you need to rebase against upstream master and only pick the relevant commits

**Comment by spalmstr** [comment]
Hi Seamus,

 

Many thanks, that is helpful.  I’ll see if I can pick my way through the process though I am developing on Joomla, not Drupal so the path is different. I take it by origin you mean civicrm/civicrm-core as opposed to my fork.  Where can I find the error log so I don’t need to trouble you?

 

Stephen

**Comment by seamuslee001** [comment]
Hi Stephen, What i normally do is click on the x to go to the test report then click on console log and that normally provides some help

**Comment by spalmstr** [comment]
Close following coding standard errors.

**Pull request closed without merging**
