### PR TITLE
Afform - improve display of error messages

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Thanks to ddc3de8 from @MegaphoneJon we can now pass error messages directly to the client. This takes advantage of that new feature and switches from guessing what the message should be, to directly using the message that comes back from the server.

Before
----------------------------------------
1. Access denied error message was hard-coded client-side.
2. In some cases (noticed on WP site) the form was not being blocked even when the submission limit was reached.

After
----------------------------------------
1. Client shows whatever message is passed back from the server.
This allows 2 different error messages when the form is blocked so the user knows the difference between a form they have no access to vs a form that has reached its submission limit.
2. Bug fixed

To reproduce
---------
1. Create a submission form.
2. Give it a url and a submission limit of 1.
3. Visit the form and submit it.
4. Visit the form again.

At step 4, the form should become disabled and an error message should display alerting the user that the form is not open for submissions. On some WP sites this was broken entirely, and this PR fixes it. On other sites the behavior should be the same before & after.

### CODE REVIEW

**Comment by briennekordis** [comment]
I'd be happy review this @colemanw, if you could please provide some replication steps.

**Comment by colemanw** [comment]
Sure @briennekordis I've updated the description.

**Comment by briennekordis** [comment]
Interestingly, I am getting the same (correct) behavior- a disabled form and a message that states "Sorry This form is not currently open for submissions."- both with and without the patch applied when I try it out on WordPress sites.

**Comment by colemanw** [comment]
@briennekordis me too! I've never been able to reproduce this locally, but @MegaphoneJon saw this symptom on one of his sites, and @guyiac has this exact bug on one of his.

**Comment by briennekordis** [comment]
Since I can't replicate the issue, and the one that @MegaphoneJon and I encountered was Stripe specific, instead of Afform, perhaps @guyiac could test this and/or provide additional replication steps.

**Pull request merged**
