### PR TITLE
[WIP] By Default throw Execptions

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This PR switches the default behaviour of CRM_Core_Error:: to be to throw Exceptions rather than the Fatal as previous 

Before
----------------------------------------
Old Fatal Error Screen by default

After
----------------------------------------
by default we throw exceptions

ping @eileenmcnaughton @totten

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 interesting. I'd love this to be the default in dev environments but not for live for a few releases - I wonder if we could have some temporary handling off environment = 'development'

**Comment by seamuslee001** [comment]
@eileenmcnaughton i have altered the code that way now will see what the unit tests do this time, they borked half way through which was interesting

**Comment by eileenmcnaughton** [comment]
@seamuslee001 it might be good to pull out all the test changes into a separate PR since we should be able to get those merged even if we don't take the plunge with the whole thing in a hurry

**Comment by seamuslee001** [comment]
so this is where it baulked before

```
Sorry. A non-recoverable error has occurred.
One of parameters  (value: foo@example.com) is not of the type Positive 



#0 /home/jenkins/bknix-dfl/build/core-15606-rikk/web/sites/all/modules/civicrm/CRM/Utils/Type.php(488): CRM_Core_Error::fatal("One of parameters  (value: foo@example.com) is not of the type Positive")
#1 /home/jenkins/bknix-dfl/build/core-15606-rikk/web/sites/all/modules/civicrm/CRM/Utils/Type.php(219): CRM_Utils_Type::validate("foo@example.com", "Positive", TRUE)
#2 /home/jenkins/bknix-dfl/build/core-15606-rikk/web/sites/all/modules/civicrm/CRM/Contact/BAO/Query.php(3746): CRM_Utils_Type::validateAll((Array:2), "Positive")
#3 /home/jenkins/bknix-dfl/build/core-15606-rikk/web/sites/all/modules/civicrm/CRM/Contact/BAO/Query.php(2082): CRM_Contact_BAO_Query->includeContactIDs()
#4 /home/jenkins/bknix-dfl/build/core-15606-rikk/web/sites/all/modules/civicrm/CRM/Contact/BAO/Query.php(570): CRM_Contact_BAO_Query->whereClause(FALSE)
#5 /home/jenkins/bknix-dfl/build/core-15606-rikk/web/sites/all/modules/civicrm/CRM/Contact/BAO/Query.php(529): CRM_Contact_BAO_Query->initialize(NULL)
#6 /home/jenkins/bknix-dfl/build/core-15606-rikk/web/sites/all/modules/civicrm/CRM/Contact/BAO/Query.php(4631): CRM_Contact_BAO_Query->__construct((Array:2), (Array:7), (Array:21), TRUE, FALSE, 1, TRUE, TRUE, TRUE, NULL, "AND", NULL, 1)
#7 /home/jenkins/bknix-dfl/build/core-15606-rikk/web/sites/all/modules/civicrm/tests/phpunit/CRM/Contact/BAO/QueryTest.php(897): CRM_Contact_BAO_Query::apiQuery((Array:2), (Array:7), NULL, NULL, 0, 2)
#8 [internal function](): CRM_Contact_BAO_QueryTest->testContactIDClause()
#9 phar:///home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar/phpunit/Framework/TestCase.php(1071): ReflectionMethod->invokeArgs(Object(CRM_Contact_BAO_QueryTest), (Array:0))
#10 /home/jenkins/bknix-dfl/build/core-15606-rikk/web/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php(215): PHPUnit\Framework\TestCase->runTest()
#11 phar:///home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar/phpunit/Framework/TestCase.php(939): CiviUnitTestCase->runTest()
#12 phar:///home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar/phpunit/Framework/TestResult.php(698): PHPUnit\Framework\TestCase->runBare()
#13 phar:///home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar/phpunit/Framework/TestCase.php(894): PHPUnit\Framework\TestResult->run(Object(CRM_Contact_BAO_QueryTest))
#14 phar:///home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar/phpunit/Framework/TestSuite.php(755): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#15 phar:///home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar/phpunit/Framework/TestSuite.php(755): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#16 phar:///home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar/phpunit/Framework/TestSuite.php(755): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#17 phar:///home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar/phpunit/TextUI/TestRunner.php(545): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#18 phar:///home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar/phpunit/TextUI/Command.php(195): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), (Array:58), TRUE)
#19 phar:///home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar/phpunit/TextUI/Command.php(148): PHPUnit\TextUI\Command->run((Array:8), TRUE)
#20 /home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar(570): PHPUnit\TextUI\Command::main()
#21 {main}

Found EXITCODES=""`
```

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I think I'd be OK switching that fatal call to throwing an exception but if wee do that I'd probably  limit changes in this area for 5.20 as it's kinda deep

**Comment by eileenmcnaughton** [comment]
@seamuslee001 maybe best for after the rc is cut but I concluded that 

1) the apiErrors in CRM_Core_BAO_CustomValueTable::setValues could be converted with no change as it seems only called from api type places &
2) setting the error mode in most of the tests makes no difference as it is done in the base class & they just repeat that

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton where do you think we are with this one?

**Pull request closed without merging**
