### PR TITLE
Increase size of mysql field in export table for column with CRM_Utils_Type::T_INT type

### PR DESCRIPTION
**Pull request by scardinius**
Overview
----------------------------------------
described here https://lab.civicrm.org/dev/core/issues/1661

### CODE REVIEW

**Comment by seamuslee001** [comment]
I think this is ok but also kind of feels like its a papering over a bigger issue @eileenmcnaughton any thoughts on the best solution here? Also most of the test fails relate

**Comment by eileenmcnaughton** [comment]
I commented in gitlab - we have dealt with these through metadata to date & there is handling in the class  - we really really need to replicate in a test before making changes to this class as the table width can break exports

**Comment by eileenmcnaughton** [comment]
(you can see from the failing tests where the tests are to use as a starting point :-)

**Comment by eileenmcnaughton** [comment]
I'm closing this as it fails tests - however I have put up an alternate here - https://github.com/civicrm/civicrm-core/pull/17956 that addresses the issue by improving standardisation. Note that it won't apply cleanly on older versions as I did preliminary cleanup

**Pull request closed without merging**
