### PR TITLE
Expose Primary member only/Non primary member only filter in membersh…

### PR DESCRIPTION
**Pull request by yashodha**
…ip reports.

Overview
----------------------------------------
Expose _Primary member only/Non primary member only_ filter in membership reports which is more intuitive rather than IS NULL/ IS NULL.

Before
----------------------------------------
mem_before

After
----------------------------------------
mem_after

Comments
----------------------------------------
Found one more occurence of the said filter.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@yashodha I've added merge on pass since this is consistent with other reports changed in a similar way - but ideally we'd get a docbloc on the new function

**Comment by eileenmcnaughton** [comment]
@jusfreeman FYI - @yashodha has been doing this as an alternative to recent PR put up by Agileware - she's made it a bit more consistent across reports than the original PR I think & the technical approach is what was agreed there. Just mentioning so you can give @yashodha a big thumbs up

**Comment by jusfreeman** [comment]
@eileenmcnaughton @yashodha I agree that this change adds an essential feature when managing inherited memberships, thanks for your work.

I would like to point out that the field label and the options themselves are effectively invisible to a user scanning this page, trying to answer the question: **How do I only show primary members in this report?**

1. The field label does not match or have a clear correlation to what the user is searching for in the user interface.
2. The keywords they are searching for are hidden behind a drop-down option.
3. And when this drop-down is selected, the important options are right at the bottom of the list - preceded by comparative operators.

This really does not make sense from a user perspective at all.

**Membership Owner ID** is itself a very odd field label to use. CiviCRM itself uses Contact ID to refer to contacts.

**Primary** is the keyword used on the CiviCRM Memberships tab to describe the inherited relationship and so really should be available on the Memberships Reports as a filter.

As a result, I suspect that whilst this feature exists - only a very small number of users will actually find it and use it. The majority will continue complaining that there is no way to filter in Membership Reports by Primary Members only.

option-1

option-2

find-memberships

view-primary

**Comment by jusfreeman** [comment]
@jaapjansma I've noticed you are also concerned about user experiences in CiviCRM. Would you like to comment on this one too?

**Comment by eileenmcnaughton** [comment]
@agh1 ping

**Comment by jaapjansma** [comment]
@jusfreeman yes I am concerned abuut user experience. I have never heard anyone complaining about this. However said that I do think you make a good improvement looking at the pictures.

**Comment by jusfreeman** [comment]
@jaapjansma thanks for taking time to read and post a comment 👍

**Comment by MegaphoneJon** [comment]
I feel split now!  On the original PR this came up on, I was won over by the technical argument against having a separate filter; seeing @jusfreeman's comments have made a compelling UX argument.  And poor @yashodha is caught in the middle of us!

I'd like to suggest a compromise:  Let's alter the label on the filter to be "Primary Membership/Member Owner ID"?  The wording feels a little awkward to experienced Civi folk, but I believe that a) it improves discoverability of this option, b) minimizes the amount of additional work needed to get this merged.

**Comment by yashodha** [comment]
@MegaphoneJon I would also vote changing the verbiage of the label itself to make it more visible.
@jusfreeman @agh1  @eileenmcnaughton Thoughts?

**Comment by eileenmcnaughton** [comment]
Seems ok to me

**Comment by agh1** [comment]
After all this, I actually think "Primary Membership" would be a better label.

"Membership Owner ID" is actually a little misleading, since this filters the membership ID of the primary membership, not the contact ID of the primary member, despite sounding like that.  The word "owner" doesn't seem to be used in the UI anywhere besides these reports--it's just a column name in the database.

"Primary Membership" works in all of the contexts:

- "primary membership is equal to 31"
- "primary membership is less than 104"
- "primary membership - primary members only"
- "primary membership - non-primary members only"

**Comment by jusfreeman** [comment]
@agh1 thanks and yes, I agree with label change to "Primary Membership"

**Comment by jusfreeman** [comment]
Will post some more comments on #14585

**Pull request merged**
