### PR TITLE
AdminUI - add Scheduled Jobs page

### PR DESCRIPTION
**Pull request by aydun**
Overview
----------------------------------------
Adds the Scheduled Jobs settings page to AdminUI extension

Before
----------------------------------------
Scheduled Jobs is old-world.

After
----------------------------------------
Scheduled Jobs is SK/FB.  This looks a bit different to the old one, and is a more typical SK/FB representation.  I have removed 'parameters' from the listing since it takes a lot of space and adds little useful information.

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
This is great @aydun!
I'm impressed at how close you managed to imitate the original page.
I agree separating out some columns is a good thing, but as the demo site has a narrow D7 theme it makes me want to compromise on width a bit. What about these columns:

| Name + Description | Frequency | Last Run | Enabled | Api Entity + Action |
| --- | --- | --- | --- | --- |

And what about putting all of the actions into a dropdown since there's 5 of them and none stand out as "I would use this all the time and must have it at my fingertips"

**Comment by aydun** [comment]
@colemanw thanks - please see the updated version of civicrm/admin/job2

**Comment by colemanw** [comment]
Not to let perfect be the enemy of good, @aydun why don't you go ahead and delete the `civicrm/admin/job` display from this PR and rename `job2` to take its place and we can merge this.

**Comment by aydun** [comment]
@colemanw Ok, I've removed the first search and changed the URL for the second.

**Comment by aydun** [comment]
> And maybe I should revisit that old issue where someone suggested we add the down-arrow-caret to SearchKit buttons, that might make the UI more intuitive

That would be good.

**Pull request merged**
