### PR TITLE
Change Activity tag to use select2

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/issues/924

Before
----------------------------------------
Screen Shot 2019-05-15 at 00 11 14

After
----------------------------------------
Screen Shot 2019-05-15 at 00 02 54

### CODE REVIEW

**Comment by pradpnayak** [comment]
ping @monishdeb

**Comment by colemanw** [comment]
Most places in the UI now tags are displayed in color. Example from `CRM_Activity_Form_Activity`:

    $tags = CRM_Core_BAO_Tag::getColorTags('civicrm_activity');

    if (!empty($tags)) {
      $this->add('select2', 'tag', ts('Tags'), $tags, FALSE, [
        'class' => 'huge',
        'placeholder' => ts('- select -'),
        'multiple' => TRUE,
      ]);
    }

But **warning** this changes the format from an array to a comma-separated list, so the form processing has to deal with that.

**Comment by pradpnayak** [comment]
@colemanw have pushed the change. Can you please review now?

**Comment by monishdeb** [comment]
Tested working fine. Merging now.

**Comment by colemanw** [comment]
Looks good :+1:

**Pull request merged**
