### PR TITLE
REF Convert forms to standard customData template

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
This converts *ALL* forms that are adding customData in a similar way to use the `CRM/common/customDataBlock.tpl` file which was added as part of the entityForm work last year.

Before
----------------------------------------
Each form adds custom data to the form in a similar way but using a copy of the code.

After
----------------------------------------
Each form adds custom data in exactly the same way.

Technical Details
----------------------------------------
The eventual goal is to convert all of these forms to use the entityFormTrait but that requires a significant amount of work on each form and is likely to introduce bugs requiring significant testing.
The change here standardizes the addition of customData across those forms, adding standard "getters" where necessary which will help with the eventual conversion to entityform.

In all cases, we are removing a few lines of code from each form which will make future maintenance easier and we can be sure that certain variables are assigned to each of the templates.

Comments
----------------------------------------
@eileenmcnaughton @seamuslee001 @lcdservices @alifrumin I realise this is quite a big PR and I could split out some of the commits into separate PRs - but I didn't want to flood the PR queue...  As each of the form changes are self-contained perhaps you could test a couple each, and if there are any that cause issues, I'll pull them out as separate PRs for further work?

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by colemanw** [comment]
Code review looks good. User testing:

* [ ] Activities
* [ ] Cases
* [ ] 
* [ ] 
* [ ] 
* [ ] 
* [ ] 
* [ ]

**Comment by colemanw** [comment]
@mattwire - found this problem while testing Surveys:

To reproduce:

- Create a survey

Result:

> Fatal error: Call to undefined method CRM_Campaign_Form_Survey_Main::getEntitySubTypeId() in /home/jenkins/bknix-dfl/build/core-13412-4bl1l/sites/all/modules/civicrm/CRM/Custom/Form/CustomData.php on line 58

**Comment by mattwire** [comment]
Thanks @colemanw I've just pushed https://github.com/civicrm/civicrm-core/pull/13412/commits/2c024dc655533d8f607fd3d39dea3c739b46789b which fixes the issue with surveys/petitions along with a code comment explaining why.

**Comment by colemanw** [comment]
* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __Pass__
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __Pass__: No user impact
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __Pass__
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __Pass__: See checklist above
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __Pass__: Less code, more consistency.
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __Pass__
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __Pass__
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __Pass__

**Comment by seamuslee001** [comment]
Merging as per @colemanw 's review and tag

**Comment by eileenmcnaughton** [comment]
@agileware I'm pretty sure you hit a bug on custom data - maybe on event info & this is a follow up to a short term revert on that? Maybe you could do some testing of master in your scenario/s

**Pull request merged**
