### PR TITLE
[wip]CRM-20158, added function to retrieve payment processor id

### PR DESCRIPTION
**Pull request by pradpnayak**
----------------------------------------
* CRM-20158: Store card type and last 4 digits of credit card
  https://issues.civicrm.org/jira/browse/CRM-20158

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw can you take a look at this & confirm to what extent this function is required - it seems to me an api call would work in it's place & passing in $returnField as a parameter seems kinda dubious to me (like the sort of coding we used to do a lot of but are trying to move away from).


I feel like in theory this would work instead

```
$paymentProcessorID = $result = civicrm_api3('EntityFinancialTrxn', 'getvalue', array(
  'return' => array("financial_trxn_id.payment_processor_id.id"),
  'entity_table' => "civicrm_contribution",
  'entity_id' => 1,
));
```

**Comment by colemanw** [comment]
I think this can be done with the api, similar to my commet in #9877

**Comment by eileenmcnaughton** [comment]
I just added the [wip] to indicate that it's not clear this PR should still be open - it looks like @colemanw 's approach should be used

**Comment by JoeMurray** [comment]
I agree the API call suggested by @eileenmcnaughton does the same thing.

**Pull request closed without merging**
