### PR TITLE
Membership#9 - show notifications for membership renewal

### PR DESCRIPTION
**Pull request by MegaphoneJon**
Overview
----------------------------------------
When renewing a membership via the back-office form, no on-screen notification appears.  This is technically a regression but appears to be quite old, so no need for urgency.

Before
----------------------------------------
No notification appears.

After
----------------------------------------
Notification appears.
selection_791

Technical Details
----------------------------------------
The only functional change is removing the two `return` statements.  I additionally extracted the renewal message into its own method so that I could extend the tests to cover it.

Comments
----------------------------------------
Ideally the new method would be `private`, not `public` but it would be a great deal more work to test `postProcess()` so I made the new method public to make it testable.

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins retest this please

**Comment by eileenmcnaughton** [comment]
hmm that means perhaps we should merge this at the same time https://github.com/civicrm/civicrm-core/pull/12583

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I think the other is still stalled - but this has a a test so ignore my attempt to tie them together

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by MegaphoneJon** [comment]
test this please

**Comment by MegaphoneJon** [comment]
The test I added for this PR has failed twice - but works for me locally.  It's pulling the notification message with `getStatus()` but it seems like a second status message is also being added, screwing up the test.  I'm not sure why this is happening - I already rebased to ensure it wasn't a new PR.  I wonder if some other test isn't properly cleaning up?

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon maybe add CRM_Core_Session::getStatus - which does a reset - to the tear down

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon perhaps if we merge this first & retry

https://github.com/civicrm/civicrm-core/pull/13878

BUT, I'd also like to remove the reference to the end date from the message - in another PR someone is trying to remove that from non-renewal status messages so let's not add back here if it's not happening (the reason to renew it is that hooks could alter it & the one that would show in this case would be inaccurate)

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I tried this locally & got a really surprising fail - am curious as to what this fail was now

**Pull request closed without merging**
