### PR TITLE
fix Colombian provinces

### PR DESCRIPTION
**Pull request by sluc23**
Overview
----------------------------------------
Fix 2 Colombian provinces.
Ref: https://es.wikipedia.org/wiki/Departamentos_de_Colombia

Before
----------------------------------------
province name `Caldea` must be `Caldas`
province `Huila` is missing

After
----------------------------------------
`Caldas (id: 2151)`
`Huila (id: 10365)`

Comments
----------------------------------------
I'm not sure if **civicrm_generated.mysql** is the only file to fix this

### CODE REVIEW

**Comment by sluc23** [comment]
This PR doesn't fix existing installations, just for new ones.
Not sure how to deal with existing ones, as in our case we fixed this manually in the DB

**Comment by MegaphoneJon** [comment]
It's pretty east @sluc23!  Here's a good example: https://github.com/civicrm/civicrm-core/pull/12168/.  The only caveat is that the `INSERT` statement should be `INSERT IGNORE` to avoid giving an error to sites that have already fixed this.  In the example I linked you, it was fixed in [a separate commit](https://github.com/civicrm/civicrm-core/pull/12168/).

**Comment by seamuslee001** [comment]
it should also be noted that that file that you have edited is normally generated via running `./bin/setup.sh -Dg` i think so what you need to do is edit the template file as per 12168 and then run that script and it will auto generate the generated data file and then you will want to edit the 5.11.alpha1 upgrade file

**Comment by JoeMurray** [comment]
Closing since you need to update a different file, not the generated one. Please resubmit.

**Comment by sluc23** [comment]
tried to run `./bin/setup.sh ` using docker buildkit, but having some issues. I'll try doing other way. tx for the tips, I'll make another PR when everything is ready

**Pull request closed without merging**
