### PR TITLE
Use new `crm-angular-js` instead of `ng-app` to bootstrap AngularJS

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Updates the method used to bootstrap Angular for internal consistency.

Before
-------------
A few places use the `AngularLoader` class directly and the old `<div ng-app>` tag.

After
---------
All core code switched to using the new `angularjs.loader` service and the new `<crm-angular-js>` tag.
Using old methods now emit a deprecation warning to remind extension authors to update their code.

Technical Details
----------------------------------------
The difference between the two is that `crm-app` (which is provided by AngularJS) can only be used once per page, but `crm-angular-js` can be reused multiple times per page so that multiple modules inserting apps don't interfere with each other.

Comments
---------
Extensions which inject Angular content include Afform, CiviVolunteer, and CiviCase. Switching them all to use `crm-angular-js` will prevent collisions.

### CODE REVIEW

**Comment by seamuslee001** [comment]
@colemanw I tried this on my local and I cleared cache and also disabled the Asset Builder cache but when I tried to create a new mailing (non mosaico) it didn't work it didn't seem to run any angular at all.  Dashboard and V4 API seemed to be fine but not Traditional Mailings

traditional-mailing-failing

**Comment by colemanw** [comment]
@seamuslee001 it wasn't enough to change the tag I had to change the loader server-side too. I went ahead and did further cleanup.

**Comment by seamuslee001** [comment]
I tested on the PR test site traditional mailings APIv4 and also tried loading up an afform and they all worked. merging

**Comment by mattwire** [comment]
@colemanw @seamuslee001 It seems this never got documented and seems pretty fundamental to the way we use angularjs? - https://docs.civicrm.org/dev/en/latest/framework/angular/loader/

I've opened issue https://lab.civicrm.org/documentation/docs/dev/-/issues/872

**Pull request merged**
