### PR TITLE
Added a DB check to prevent deleting exisiting CiviCRM data from database.

### PR DESCRIPTION
**Pull request by agilewarealok**
Overview
----------------------------------------
CiviCRM installation step provides does not perform sufficient checks or provide any warning to user that existing CiviCRM database will be wiped.

Before
----------------------------------------
Existing CiviCRM data getting wiped out  without any error message warning.

After
----------------------------------------
User cannot proceed further without manually removing the CiviCRM tables, error message is added in CiviCRM Database check. If they do that, then they really know what they are doing.

Comments
----------------------------------------
_Agileware Ref: CIVICRM-1140_

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Ouch - I think PR suggests you had a painful experience....

**Comment by agilewarealok** [comment]
@eileenmcnaughton Indeed!

**Comment by eileenmcnaughton** [comment]
@petednz any chance @jitendrapurohit or Luke could test this?

**Comment by demeritcowboy** [comment]
Questions:
* why does it only do the check for wordpress and joomla?
* why ignore errors (line 1308) in the @mysqli_select_db but then not also ignore errors in the following commands?

Also some nitpicks:
Line 527: Instead of "Does database has data from previous installation?" it should be "Does the database have data from a previous installation?"
Line 1318: Instead of "CiviCRM data from previous installation does not exists in " it should be "CiviCRM data from a previous installation does not exist in "

**Comment by eileenmcnaughton** [comment]
@demeritcowboy thanks for taking a look- I don't suppose you tested it did you?

**Comment by demeritcowboy** [comment]
> 
> 
> @demeritcowboy thanks for taking a look- I don't suppose you tested it did you?

I did a wordpress install once a couple years ago and I don't really do joomla, so sorry no I didn't try. I'm assuming this isn't something I could test from the fancy auto test sites.

**Comment by demeritcowboy** [comment]
I tried reproducing the problem first without the patch and couldn't do it. On the first try I visited sites/all/modules/civicrm/install/index.php (drupal 7) and I get the attached screenshot.

Untitled

Then I removed civicrm.settings.php and tried again and I got this:

Untitled2

So can the PR be updated to include steps to reproduce, and even if I could reproduce it the code suggests it wouldn't get checked on drupal, so maybe the PR description can explain why it skips the check for drupal.

**Comment by eileenmcnaughton** [comment]
Thanks heaps @demeritcowboy 

Merging

**Comment by demeritcowboy** [comment]
Oh ok I was hoping at least the english typos would get fixed (the nitpicks).

**Comment by eileenmcnaughton** [comment]
Ouch sorry I misread - will put them up now & merge

**Comment by demeritcowboy** [comment]
Thanks!

**Comment by eileenmcnaughton** [comment]
@demeritcowboy What specifically should we change on wording? ie what should we change to

**Comment by demeritcowboy** [comment]
Line 527: Instead of "Does database has data from previous installation?" it should be "Does the database have data from a previous installation?"
Line 1318: Instead of "CiviCRM data from previous installation does not exists in " it should be "CiviCRM data from a previous installation does not exist in "

**Comment by eileenmcnaughton** [comment]
oh I see - I couldn't read the 'does it has' image

**Comment by eileenmcnaughton** [comment]
@demeritcowboy I'm now worried I might need to see an optomistrist....

**Comment by demeritcowboy** [comment]
Optomistrist? Someone who helps you see the bright side of things?

**Comment by eileenmcnaughton** [comment]
:-) sigh

I would also like to say I am pre coffee & about to fix that

**Comment by demeritcowboy** [comment]
All good.

**Pull request merged**
