### PR TITLE
Icons in colored boxes for relationship permissions

### PR DESCRIPTION
**Pull request by agh1**
Overview
----------------------------------------
This follows on some conversation between @colemanw, @aydun, @eileenmcnaughton, and me in #12415 regarding how creepy [`fa-eye`](https://fontawesome.com/v4.7.0/icon/eye) is.

Before
----------------------------------------
An eye appears for view-only relationship permissions and an asterisk for view-and-edit permissions.

After
----------------------------------------
An eye appears within a green square for view-only relationship permissions and both that and a pencil in a blue square appear for view-and-edit permissions.

image

image

Technical Details
----------------------------------------
All rendering of these icons and their titles is now handled by a new Smarty template, simplifying future changes.

### CODE REVIEW

**Comment by colemanw** [comment]
This looks great Andrew. One very minor nitpick, I think the 2nd screenshot would look better with the icons lined up to the left of the explanation text.

**Comment by eileenmcnaughton** [comment]
This is so good @agh1 - kudos to you & @aydun

**Comment by aydun** [comment]
Very nice!

**Comment by agh1** [comment]
I agree with @colemanw's suggestion.  Here's what it now looks like when viewing a single relationship:
image

**Comment by seamuslee001** [comment]
Merging as per the tag

**Comment by seamuslee001** [comment]
@agh1 I think this might need some user docs updating / icons

**Comment by aydun** [comment]
Doc issue: https://github.com/civicrm/civicrm-user-guide/issues/344

**Pull request merged**
