### PR TITLE
Import - fix regression on matching by contribution ID

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
port https://github.com/civicrm/civicrm-core/pull/24366

### CODE REVIEW

**Comment by Detsieber** [comment]
Thank you so much @eileenmcnaughton -  this patch helped solving my problem!

I want to note, there is one minor problem left: In my use case for contribution import, I need to update the total_amount to "0".
In the past, it was okay to set this field to "0". However now, I have to set it to "0.00" in order to make the update parser understand, that the value is not empty...
Of course, this is a minor issue, since there is an easy workaround. However, out there might be regular import procedures relying on "total_amount='0' ".

**Comment by eileenmcnaughton** [comment]
@Detsieber  - can you log a gitlab for the other issue - I'm sorry you hit this when we were still getting to releasing the fix - we might have prevented you hitting it

**Comment by Detsieber** [comment]
@eileenmcnaughton - see: https://lab.civicrm.org/dev/core/-/issues/3828

**Comment by Detsieber** [comment]
> I'm sorry you hit this when we were still getting to releasing the fix - we might have prevented you hitting it

no matter - I am very happy this was fixed so quickly!

**Pull request merged**
