### PR TITLE
dev/core/issues/740, Show form on validation error

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/issues/740

Before
----------------------------------------
before

After
----------------------------------------
after

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by pradpnayak** [comment]
@eileenmcnaughton can this be merged?

**Comment by eileenmcnaughton** [comment]
This doesn't work for me with or without the patch - although I get a different error - perhaps my file type is also upsetting it  - not sure

Screenshot 2019-03-22 11 58 56


@colemanw this is the second time in 2 days I've hit issues where a 'form' is using a 'page' class with setEmbedded - is this some early variant on the popup construct - or the actual preferred way to do it ? Class is CRM_Contact_Page_View_Note

**Comment by eileenmcnaughton** [comment]
OK - I managed to replicate this with just an image - my previous effort was another file. I think this is bad. I think we are forcing an edit form onto a view page& I suspect it's because it was done a long time ago before we developed better methods. 

However, I couldn't see any negative effect when viewing or editing the note with this change & other entities seem OK too. If there IS any negative impact from this then
1) we will have switched one definite bug for a-possible-nother but
2) at least the commit history will help us then to find out what's going on - the reasons for the current decisions are obscured back into the svn dark ages.

**Comment by eileenmcnaughton** [comment]
As a final point - this seems kinda low-risk - I mean any negative fallout would be on a fairly obscure form & likely just a UI bug

**Pull request merged**
