### PR TITLE
CRM-20658: Fatal error on Dedupe rule for > 1 match

### PR DESCRIPTION
**Pull request by jitendrapurohit**
[Docs](https://dev.mysql.com/doc/refman/5.7/en/temporary-table-problems.html) mentions `Can't reopen table:` occurs if temporary tables are referred twice in a single query. Modifying this to create another referral table to join if there are two instances present in a single query string.

Unit test added.

---

 * [CRM-20658: Fatal error on Dedupe rule for \> 1 match](https://issues.civicrm.org/jira/browse/CRM-20658)

### CODE REVIEW

**Comment by petednz** [comment]
This fixes the problems we had on both test and production sites.

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit I tested this and it still gave me an error (with 3 critieria). I did get it to work with a small change - note the use of the $tempTable variable.

```
    $tempTable = 'dedupe_copy' . uniqid();
              //Create second copy as single temp table cannot be referred twice in a single query.
              $dao->query("CREATE TEMPORARY TABLE $tempTable SELECT * FROM dedupe WHERE weight >= {$weightSum}");
              $dupeCopyJoins = array($dupeCopyJoin, str_replace('dedupe_copy', $tempTable, $dupeCopyJoin));
```

As I've commented elsewhere I think we need to do some refactoring to get a final fix. However, given this fixes the immediate issue (with the change above), does not introduce any further nastiness and has a unit test I think we should merge it as soon as you have made that change.

I believe there may be another proposed fix in the queue but I have focussed on this one because of the unit test. Once that is in further changes can be considered

**Comment by eileenmcnaughton** [comment]
Can you take a look at #10405 - it's actually very similar - and pull in anything from there that you think would improve this?

**Comment by eileenmcnaughton** [comment]
(or alternately I can merge that & then merge your test as a follow up if you think that makes sense)

**Comment by jitendrapurohit** [comment]
sure, will take a look this evening 👍

**Comment by jitendrapurohit** [comment]
closing in favor of #10405

**Pull request closed without merging**
