### PR TITLE
Report Template test for SelectWhere - add test

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Add unit test to reports with selectWhereClause hook

Before
----------------------------------------
not tested

After
----------------------------------------
tested

Technical Details
----------------------------------------
Provides test for https://github.com/civicrm/civicrm-core/pull/12772 - although 'contact/detail' needs to be removed as part of getting that merged

Comments
----------------------------------------
@pradpnayak

### CODE REVIEW

**Comment by pradpnayak** [comment]
Awesome! Thank you so much @eileenmcnaughton 

I wasn't sure how to add unit test that will invoke hook.  This is a good example to bookmark.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 wanna give this merge-on-pass

**Comment by seamuslee001** [comment]
Yep affects only tests, real judge is Jenkins adding merge on pass

**Comment by eileenmcnaughton** [comment]
unrelated fails

**Pull request merged**
