### PR TITLE
(NFC) Add 'schema' to \Civi\Token\TokenProcessor()

### PR DESCRIPTION
**Pull request by aydun**
Overview
----------------------------------------
Extracted from #13174 #12012  Small change to \Civi\Token\TokenProcessor() to add a schema setting - as discussed with / proposed by @totten   NFC currently, but allows

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by aydun** [comment]
test this please

**Comment by mattwire** [comment]
I've reviewed this, it's adding code to support new functionality so does not impact existing functionality.  The code change has been discussed with @totten so I'm happy with the principle.  @seamuslee001 @eileenmcnaughton Could one of you merge?

**Comment by seamuslee001** [comment]
Merging based on @mattwire 's review

**Pull request merged**
