### PR TITLE
dev/core#1425 Replace deprecated setting function

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Replaces a deprecated fn in the test suite

Before
----------------------------------------
Deprecated CRM_Core_BAO_Setting::setValueOption used

After
----------------------------------------
api used - 

Technical Details
----------------------------------------
Note we can't use Civi::setting here because only the api handles  arrays - I wonder what apiv4 does

Comments
----------------------------------------

### CODE REVIEW

**Comment by yashodha** [comment]
@eileenmcnaughton 
You might want to address other places as well like https://github.com/civicrm/civicrm-core/blob/master/tests/phpunit/CRM/Core/BAO/PreferencesTest.php#L24

**Comment by eileenmcnaughton** [comment]
Sigh - yes - the 'scope' of my current round of effort is to get to the point where this can be merged https://github.com/civicrm/civicrm-core/pull/15975 - which I think probably means that needs resolving :-(

I won't add it to this PR though.

**Comment by eileenmcnaughton** [comment]
Also - this has raised the fact that Civi::settings() is kind of inconvenient with arrays - I expect it's too late to address that (@totten ) but maybe a v4 Setting api would combine the help of apiv3 with some of the cleaner code of the Civi::settings()

**Comment by eileenmcnaughton** [comment]
@seamuslee001 can I get a merge on this - only affects tests but then I might be able to merge the deprecation

**Pull request merged**
