### PR TITLE
CRM-19301 fix dashboard upgrade for multilingual sites

### PR DESCRIPTION
**Pull request by seamuslee001**
- [CRM-19301: 4.7.11 upgrade fails for installs with multiple languages enabled](https://issues.civicrm.org/jira/browse/CRM-19301)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@mlutfy Hey Mathieu

Are you able to test out this patch on some of your installs? I think this should do the job

**Comment by totten** [comment]
jenkins, test this please

**Comment by seamuslee001** [comment]
just pinging @colemanw as well

**Comment by colemanw** [comment]
Code looks good.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by totten** [comment]
Passes the multilingual upgrade test.

**Pull request merged**
