### PR TITLE
[REF] extract updateFinancialAccountsOnContributionStatusChange

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Function extraction - updateFinancialAccountsOnContributionStatusChange

Before
----------------------------------------
Code less readable

After
----------------------------------------
Code more readable

Technical Details
----------------------------------------
Basic extraction

Comments
----------------------------------------
@monishdeb @pradpnayak @mattwire can one of you look - I think this makes the calling function much easier to make sense of - there are a couple more blocks in the fn that make sense to do the same with - also chucking in some deprecation notices would tell us if some parts of the code are ever being hit & when

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by pradpnayak** [comment]
Looks good to me.

**Comment by mattwire** [comment]
@eileenmcnaughton Ugh! There's some nasty contribution_status getLabel() stuff in there and then comparing strings.  That'll break for non-english, or if anyone changes the labels on contributions...  I realise you're not changing it here, but I'd prefer if the contribution_status_id was passed into the function rather than the label.  At least then it could be fixed within the function.

**Comment by eileenmcnaughton** [comment]
@mattwire I'm open to looking at something like that as a follow up - I don't like to mix changes in with extractions

**Comment by mattwire** [comment]
Merging per comments.  @eileenmcnaughton Please do follow up to eliminate the nasty getLabel comparisons.

**Pull request merged**
