### PR TITLE
Afform - support default values for fields

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Allow default values for fields per https://lab.civicrm.org/dev/core/-/issues/2734

Before
----------------------------------------
Not possible to configure default values for Afform fields.

After
----------------------------------------
image

Technical Details
----------------------------------------
This adds an `"afform_default"` property to the field definition.
It does not use the `"default_value"` property from getFields because that's more to do with Civi's schema and often not appropriate for a form.

### CODE REVIEW

**Comment by colemanw** [comment]
@MegaphoneJon I recall you also requested this feature.

**Comment by eileenmcnaughton** [comment]
@colemanw this works a treat & I'm happy to merge it - however, I have a follow up request - for the selects I could only select one option but it's a multi-select field so more than one would also be useful.

Feel free to self-merge this once you've read this & decided what, if anything, you want to do about the follow up request


image

**Comment by colemanw** [comment]
Ok, I've updated the UI to support multi-selects, and also enhanced the UI to allow setting defaults not only from the gear menu but also more directly (at least for fields with select options):
image

**Comment by eileenmcnaughton** [comment]
@colemanw there is something confusing about the new UI - if I select 'Check' in the new widget then it gets selected under the gear section - but if I add to it from the gear section it doesn't flow back to widget part. I found a few other weird things - but all under the category of the 2 field elements not being in sync

**Comment by colemanw** [comment]
Thanks @eileenmcnaughton - you're right there was an odd bug in there. Should be fixed now.

**Comment by eileenmcnaughton** [comment]
working well now

**Pull request merged**
