### PR TITLE
[REF] APIv4 - Use caching to speed up invoke function

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Makes APIv4 a bit faster when it's run numerous times per request.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
There is definitely some improvement with this

Current master without this
~35 seconds

image

With
~28 seconds

imagem

(although other runs got less improvement)

We should merge this!

But note that it still compares badly to the 11 seconds I could get if I could just cache the spec in function (but that would require permiting pass-by-reference

image

image

**Comment by colemanw** [comment]
@eileenmcnaughton I think what we need to do is make 2 types of specProviders: a cached one that doesn't care about `$values`, and an uncached one. Should be way less callbacks that way.

**Comment by eileenmcnaughton** [comment]
@colemanw that makes sense

**Comment by eileenmcnaughton** [comment]
@colemanw or alternatively there is the way your sql alterthing does it - where it declares what field / fields it cares about - but maybe that gets tricky quickly -& the performance adds are less there - just thinking that contact.get returns the same geifields for contact type individual regardless of almost all of the x possible fields it might receive there

**Comment by colemanw** [comment]
I ended up doing something similar to this @eileenmcnaughton - but instead of relying on the specProviders to declare what fields they care about, we spy on them by tracking which values they request. https://github.com/civicrm/civicrm-core/pull/29066

**Pull request merged**
