### PR TITLE
CRM-18625 - payment processors - correctly set test URLs from edit form

### PR DESCRIPTION
**Pull request by ineffyble**
Update the hardcoded list of fields to use the test fields for site, recur, button, subject, and api when updating the test processor record.

---
- CRM-18625: Authorize.net not saving testing URL
  https://issues.civicrm.org/jira/browse/CRM-18625

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by eileenmcnaughton** [comment]
I have tested this and was able to reproduce the problem as described & verify that the patch fixes it. The code looks appropriate & I can't see anyway it could affect anything beyond the specific form

**Comment by totten** [comment]
jenkins, ok to test

**Comment by josephlacey** [comment]
@seamuslee001 @eileenmcnaughton I've also verified this bug and that the patch fixes this on 4.7.  This can be merged.

**Pull request merged**
