### PR TITLE
fix contribution import for payment instrument update

### PR DESCRIPTION
**Pull request by kurund**
Fix for https://lab.civicrm.org/dev/core/-/issues/3038

### CODE REVIEW

**Comment by kurund** [comment]
@eileenmcnaughton
It would be good to get your thoughts on this fix.

**Comment by jaapjansma** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@kurund I have a plan for a more solid fix - once https://github.com/civicrm/civicrm-core/pull/23519 is merged I can start to leverage some of the metadata based checking

**Comment by eileenmcnaughton** [comment]
@kurund I tested this on PR https://github.com/civicrm/civicrm-core/pull/23586 & it is fixed with that applied - although I suspect the actual fix was

https://github.com/civicrm/civicrm-core/commit/f6fc1b15afbc8bf5a2bf06441e0ae62c2bb3b188#diff-a223445bfabeca3421466f7add0f896b2f7126287cbbd3124665781336f086d9L956-R947

Closing this out now - but if you have a chance to review it with #23586 would be much appreciated

**Pull request closed without merging**
