### PR TITLE
Regenerate civicrm_generated after #22686 and codegen params to in_array are backwards

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
All activities are solo activities.

Before
----------------------------------------
Everyone does everything alone

After
----------------------------------------
Most activities are done with friends

Technical Details
----------------------------------------
backwards params

Comments
----------------------------------------
An alternative is use a different method since it's come up before there's some weirdness sometimes with in_array, but this PR should be a straightforward review.

### CODE REVIEW

**Comment by totten** [comment]
So if there was some issue where the test-processes depended on the previous/poorly-chosen activity examples -- then that would show up in the test-run for the companion PR, right (#24577)?

**Comment by demeritcowboy** [comment]
Not yet since I didn't realize it was backwards until after I made that regen. I should reregen it with this patch applied.

**Comment by demeritcowboy** [comment]
Ok so now any test weirdness should show up on this PR.

**Comment by seamuslee001** [comment]
well tests pass

**Pull request merged**
