### PR TITLE
Use a reduced font awesome for search input placeholder

### PR DESCRIPTION
**Pull request by pminf**
Overview
----------------------------------------
This should solve https://lab.civicrm.org/dev/core/-/issues/5512 by using the already loaded font awesome font with a reduced character set. 

Before
----------------------------------------
The default sans-serif is used for the quicksearch placeholder's icon and text. Font Awesome is not used for the icon, like intended.
image

After
----------------------------------------
Font awesome is used for the quicksearch placeholder's icon but not for it's text. The text is rendered by the default sans-serif font.
image

Technical Details
----------------------------------------
 This uses the usual font awesome src but with an explicit unicode range. Characters outside this range won't be rendered with this font.

### CODE REVIEW

**Comment by ufundo** [comment]
Thanks @pminf ! 

I've changed the base branch to 5.78 as I think this is a regression and would be good to include in any future point releases.

It generally looks good to me but will test some more tomorrow.

I did wonder if we can redefine our main "FontAwesome" font to always have restricted unicode range - so avoiding the need for a separate FontAwesomeSafe? I would have thought it is good to be "safe" everywhere FontAwesome is used?

**Comment by eileenmcnaughton** [comment]
@ufundo you moved this to 5.78 - is it in 5.79 yet? Our policy is to merge any regressions to the rc branch first & after that look at backporting / merging to the stable branch. The rc branch is forward-merged to master (but the stable is not)

**Comment by ufundo** [comment]
Sorry @eileenmcnaughton have updated now

**Comment by vingle** [comment]
> I did wonder if we can redefine our main "FontAwesome" font to always have restricted unicode range - so avoiding the need for a separate FontAwesomeSafe? 

I think FontAwesomeSafe is an entire font just for the one search icon character. There are already unicode ranges set up on the main FA6 font and the FA4 shims font: https://github.com/FortAwesome/Font-Awesome/blob/37eff7fa00de26db41183a3ad8ed0e9119fbc44b/css/v4-font-face.css#L19 - adding a unicode value for every icon in use by Civi seems like a bit of overkill?

**Comment by eileenmcnaughton** [comment]
> adding a unicode value for every icon in use by Civi seems like a bit of overkill?

Perhaps we should do this now in the interests of getting the regression fixed & re-fix in master @vingle ?

**Comment by vingle** [comment]
@eileenmcnaughton personally I'd use an SVG background image rather than create a new font-family for this one bug, but yes sounds like it's worth merging as an immediate fix for Ubuntu users.

**Comment by eileenmcnaughton** [comment]
thanks @vingle - I'm gonna merge this based our your OK - & hopefully some combo of you @pminf & @ufundo can do an improved fix in master

**Pull request merged**
