### PR TITLE
Remove "page=CiviCRM" query string from WordPress front-end (5.26)

### PR DESCRIPTION
**Pull request by christianwach**
Overview
----------------------------------------
Duplicate of #17350 against 5.26 branch. Requires [this PR to CiviCRM-WordPress](https://github.com/civicrm/civicrm-wordpress/pull/194). Solves [this issue on Lab](https://lab.civicrm.org/dev/wordpress/-/issues/49).

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
hmm - this was on master but from comments I understand it should be 5.26 -so I tried to change it - but without success

**Comment by kcristiano** [comment]
@eileenmcnaughton this is/was on 5.26  and I do think it should be.  There seem to be some false commits now.   Can we fix?

**Comment by christianwach** [comment]
WTF? I'm pretty sure this didn't have all those extra commits yesterday. I'll force-push an update shortly.

**Comment by kcristiano** [comment]
I've been doing as much `r-run` as I can on this.

I've been using 5.26.RC as the testing version.

I've tested in the following configurations - all are CiviCRM 5.26RC + #17352 and https://github.com/civicrm/civicrm-wordpress/pull/194

- WP 5.4.1 cleaner URLS
- WP 5.4.1 Old style ugly URLS
- WP 5.4.1 Cleaner URLS and [WP REST API Mailing Links](https://docs.civicrm.org/dev/en/latest/api/v3/wp-rest/#settings)
- WP 5.5.alpha cleaner URLS
- WP 5.5.alpha Old style ugly URLS
- WP 5.5.alpha Cleaner URLS and [WP REST API Mailing Links](https://docs.civicrm.org/dev/en/latest/api/v3/wp-rest/#settings)

I have gone through the following on ALL of the above.

- Contribution Pages with shortcode
- Contribution pages with CiviCRM url
- membership Pages with shortcode
- membership pages with CiviCRM url
- Event list and Register Pages with shortcode
- Event List and register pages with CiviCRM url
- CiviMail Traditional - default urls
- CiviMail Traditional - WP REST URLS
- User Dashboard
- As many admin pages as needed to set up and configure the above

I've tested old links in the style of `https://wplocal.test/civicrm?page=CiviCRM&q=civicrm%2Fuser&reset=1&id=202&cid=202`  and they redirect to `https://wplocal.test/civicrm/?q=civicrm%2Fuser&reset=1&id=202&cid=202&civiwp=CiviCRM`  on WP 5.4.1 and 5.5.alpha

I've upgraded from 5.25 to 5.26 on one of the instances with these PRs

All behavior (so far) is as expected with one exception:

On WP 5.5 with mailing links set to use WP REST API the public view does not work on WP 5.4.1.   This may be related to [Lab WP 52](https://lab.civicrm.org/dev/wordpress/-/issues/52)

I could not reproduce on WP 5.5.alpha  - but more testing is needed.

My inclination is that this is much better in than out and having it merged will allow more testing.   I still have to go through Profiles, and I am sure I have forgotten something.

@christianwach  Any thought?    

cc @totten  @eileenmcnaughton

**Comment by gah242s** [comment]
Wow!  That's impressive.  Reading through that list, it looks like it already takes care of extensions like Caldera Forms.  Is that a correct assumption or are extensions also going to have to be updated also?

**Comment by kcristiano** [comment]
I ignored Caldera Forms CiviCRM (for now) as it does not use CiviCRM URLs.   You _could have_ some redirection going on  so we will need to tets that, but I want to focus on the core functionality first.

**Comment by gah242s** [comment]
Sounds reasonable!  Thanks to you and the others for buckling down so tightly on this.

**Comment by seamuslee001** [comment]
@kcristiano So would you think that we should merge this noting the outstanding issue with lab WP 52?

**Comment by kcristiano** [comment]
@seamuslee001  I do - I'd like to see if @christianwach  has an opinion, but without this we are risking breaking ALL of CiviCRM.   With this PR we've found one issue that only affects mailings that use the new (5.25) WP REST API filter for mailing endpoints.   

Merging also gives us time to test between now and June 3rd

**Comment by eileenmcnaughton** [comment]
I've added merge-ready based o @kcristiano's comments. I feel like absent feedback against from @christianwach in the next 24 hours we should merge & start testing with this merged

**Comment by christianwach** [comment]
I made a small change to the linked PR in response the testing done by @kcristiano and it seems to solve the only outstanding issue.

**Comment by kcristiano** [comment]
see https://github.com/civicrm/civicrm-wordpress/pull/194#issuecomment-631561883

Based on that commit and further `r-run` this is good to merge

**Pull request merged**
