### PR TITLE
Add GroupTokens to replace WelcomeTokens

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
In conjunction with https://github.com/civicrm/civicrm-core/pull/24235

Hmm - this would make `{group.title}` work - but I see `replaceResubscribeTokens` actually concatentates several group titles together - not quite sure how we could do this to support that too ....

```
  public static function &replaceResubscribeTokens(
    $str, &$domain, &$groups, $html,
    $contact_id, $hash
  ) {
    if (self::token_match('resubscribe', 'group', $str)) {
      if (!empty($groups)) {
        $value = implode(', ', $groups);
        self::token_replace('resubscribe', 'group', $value, $str);
      }
    }
    return $str;
  }
```

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton style warnings

**Comment by eileenmcnaughton** [comment]
It has passed now

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 this has passed now

**Comment by seamuslee001** [comment]
Yeh this seems sensible

**Pull request merged**
