### PR TITLE
dev/core#3701 - Prevent e-notice on map fields form

### PR DESCRIPTION
**Pull request by tschuettler**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/3701

Before
----------------------------------------
e-notice appears

After
----------------------------------------
e-notice disappears

Technical Details
----------------------------------------
I chose 5.51 as target branch since this was a review based on the rc testing. Feel free to recommend otherwise.

Comments
----------------------------------------
I can't wrap my head around, what the javascript in https://github.com/civicrm/civicrm-core/blob/4a01628cfa19ac305b5734e8ea36713f363b8d91/templates/CRM/Contact/Import/Form/MapField.tpl#L24-L34 is actually supposed to achieve.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
OK - so in terms of what the script does - if you use a saved mapping then on the MapField screen you can update it or save new

image

If you go next & then back

image

Then I think that script is what means the right checkbox is selected

image

**Comment by eileenmcnaughton** [comment]
Or at least - it attempts to.....

**Comment by eileenmcnaughton** [comment]
@tschuettler yeah - I suspect the script should just be re-written from scratch in jquery

**Comment by totten** [comment]
Whoops, looks like we were working at the same time!

I think that #23906 and #23908 were motivated by the same notice, but they're not mutually exclusive. #23906 appears to be tackling the funny lifecycle of `$isCheked`, and #23908 tackles the problem of broken `{if}`s.

**Comment by tschuettler** [comment]
@eileenmcnaughton I figured it could make sense to use the `UserJob` metadata to see if a saved mapping is used and if so which one. 
However, the saved mapping is not updated to the `UserJob` when creating a new mapping in the map fields step. I played around with the code to get that part working, but I feel that I'm out of depth here to create a sustainable solution.

**Comment by eileenmcnaughton** [comment]
oh right - so we haven't been saving those fields cos I thought it was something kinda internal to that form - but to add them to what is saved add them to this array

https://github.com/civicrm/civicrm-core/blob/d2b81f5aacdc3ae28412861cbd691e503617a236/CRM/Import/Forms.php#L100-L126

**Comment by eileenmcnaughton** [comment]
I had a go at 'the big cleanup' - it's against master not the rc cos there is quite a bit of change in it to merge in so late in the rc period

https://github.com/civicrm/civicrm-core/pull/23950

**Comment by eileenmcnaughton** [comment]
I'm gonna close this out in favour of the other - since it's close

**Pull request closed without merging**
