### PR TITLE
dev/core/issues/991, fixed set default values for find contact search form

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/issues/991

Before
----------------------------------------
Screen Shot 2019-05-29 at 11 46 59

After
----------------------------------------
Screen Shot 2019-05-29 at 11 47 12

### CODE REVIEW

**Comment by scardinius** [comment]
@pradpnayak no, this fix doesn't resolve my problem in https://lab.civicrm.org/dev/core/issues/991

**Comment by pradpnayak** [comment]
@scardinius i believe it does fix the setting default values on the Find contact form.

**Comment by pradpnayak** [comment]
jenkins retest this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton thoughts on this given the general changes to search forms?

**Comment by eileenmcnaughton** [comment]
I took a look at this & agree it doesn't work because now (not necessarily always) - contact basic search is not used to load a search for a smart group from a basic search. 

I took a look at a better fix & it's tough - I think we probably want to think a bit more through the stored & unstoring of smart groups - essentially the advanced search should be responsible for 'packing & unpacking' the groups it stores as saved searches. I feel like a bit of cleanup & digging is required to get us there though 

I did add this earlier as a preliminary simplification
https://github.com/civicrm/civicrm-core/pull/14891

I'm going to close this because it doesn't get us there :-(

**Pull request closed without merging**
