### PR TITLE
Add Receipt Text field to Offline Contribution Forms (both "New Contribution" and "New Credit Card Contribution")

### PR DESCRIPTION
**Pull request by alifrumin**
Overview
----------------------------------------
Adds a "Receipt Text" field to Offline Contribution Forms (both "New Contribution" and "New Credit Card Contribution") that displays when the "Send Receipt?" checkbox is checked. The text entered into the "Receipt Text" field is displayed in the receipt.

Before
----------------------------------------
The message template used for offline contributions contains a "receipt_text" token:  

offlineReceipt

but there is no field to enter receipt text when creating a backend contribution:  
noReceiptTextField

### To Replicate
1. Go to a Contact's Contribution Tab
2. Click "Record Contribution (Check, Cash, EFT...)"
3. Check the "Send Receipt?" checkbox 

EXPECTED RESULT - No "Receipt Text" field

After
----------------------------------------
On both the "New Contribution" and "New Credit Card Contribution" backend forms which can be found by going to a Contact Record, Clicking the Contributions tab for that Contact Record and then clicking "Record Contribution (Check, Cash, EFT...)" or "Submit Credit Card Contribution" respectively.

**When** one clicks the "Send Receipt?" checkbox 
**Then** a "Receipt Text" field appears, the text entered into the "Receipt Text" field is displayed in the receipt.

ReceiptTextField

### To Test
1. Go to a Contact's Contribution Tab
2. Click "Record Contribution (Check, Cash, EFT...)"
3. Check the "Send Receipt?" checkbox 
4. Enter some text into the "Receipt Text" field
5. Click Save (you will need to fill out all the required fields)

EXPECTED RESULT - The text entered in the  "Receipt Text" field displays in the receipt.

### CODE REVIEW

**Comment by magnolia61** [comment]
I like it, but think it would be wise to make a help icon or small help text under the field you are adding. The help text should mention that the receipt text is inserted/injected in the regular template.

**Comment by mattwire** [comment]
> I like it, but think it would be wise to make a help icon or small help text under the field you are adding. The help text should mention that the receipt text is inserted/injected in the regular template.

Agreed - this a a common question I get asked by clients and I can never quite remember how it works myself!

**Comment by alifrumin** [comment]
Great idea!

I took a stab at some help text copy I did both a short description below the field and a help text icon with more details see screenshot below:
rtht

Open to suggestions for improvement.

**Comment by alifrumin** [comment]
jenkins retest this please

**Comment by mlutfy** [comment]
Hi Alice,

Considering this is a UI change, it would be great to have an associated issue under:  
https://lab.civicrm.org/dev/user-interface/issues

Some people might monitor issues on that tracker specifically, and it would be great to have their buy-in.

(We often hear pushback from people who discover UI changes once the stable release rolls out, since they do not follow the PR queue, so having those issue trackers is a way to make it easier to engage with some areas of CiviCRM development.)

**Comment by eileenmcnaughton** [comment]
I'm actually really uncomfortable with this - we have unresolvable issues around the receipt text in the membership form because its inconsistent across processors & I feel like to add this in core we need to set the bar on code cleanup to be that it happens from completetransaction & is unit tested - which I personally think puts us in the place of 'this is probably better done in an extension than as an additional feature in core)

**Comment by alifrumin** [comment]
Just in case anyone is looking at this later. I created a public extension that does this: https://github.com/aghstrategies/com.aghstrategies.receipttext

**Pull request closed without merging**
