### PR TITLE
(core/dev#2104) Add target custom data to activity report

### PR DESCRIPTION
**Pull request by yashodha**
Overview
----------------------------------------
Add target custom data to activity report

Before
----------------------------------------
Only activity custom data can be searched
activity_before

After
----------------------------------------
Activity and target contact custom data can be searched
activity_after

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
My worry is it might not be clear which contact this relates - in the Extended reports report that provides this I've prefixed the fields - which is a bit fugly

**Comment by yashodha** [comment]
@eileenmcnaughton

You mean in UI, it should show that the custom data is related to target contact. Not sure about adding to labels /custom group name here. It might be worth it to add the explanation in help file since this is technically documentation. Thoughts?

**Comment by demeritcowboy** [comment]
@yashodha Is there interest in pursuing this or should we close for now?

**Comment by eileenmcnaughton** [comment]
closing based on 10 days passing since ^^ - we can always re-open/revisit

**Pull request closed without merging**
