### PR TITLE
CRM-20821 & CRM-20938 : minor fix

### PR DESCRIPTION
**Pull request by monishdeb**
* [CRM-20821: Saving an existing premium product breaks the image URLs](https://issues.civicrm.org/jira/browse/CRM-20821)
 * [CRM-20938: The auto-resizing of uploaded premium products images does not preserve aspect ratio](https://issues.civicrm.org/jira/browse/CRM-20938)

### CODE REVIEW

**Comment by seanmadsen** [comment]
This looks ready-to-merge to me.

**Comment by monishdeb** [comment]
@colemanw can you please merge this PR? There was a mistake from my end while making additional changes on #10720

**Comment by monishdeb** [comment]
Merging as approved by @seanmadsen and it's a typo fix

**Comment by eileenmcnaughton** [comment]
Good on you guys for spotting it

**Pull request merged**
