### PR TITLE
CRM-18546 Duplicate email addresses created when merging in 4.7

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
- [CRM-18546: Duplicate email addresses created when merging in 4.7](https://issues.civicrm.org/jira/browse/CRM-18546)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@jkingsworth @deepak-srivastava  so this is the patch for the 4.7 regression on emails discovered when reviewing  #8192

Once we have these 4.7 regressions fixed I'll be back to the start line - which was the slow query in #8251 - (not having any tests & not being able to write them was blocking that ) & my fixes to allow criteria to be passed in to the merge job. I realise they might not be doable this cycle - but at least the changes for them will be less now the other refactoring is done

**Comment by JKingsnorth** [comment]
I'll check this out tomorrow, and it would be great to get the slow query one into this review cycle too if there's time.

**Comment by eileenmcnaughton** [comment]
@JKingsnorth not sure if you would prefer to work with a smaller PR or a bigger PR so I have created a new PR with all the remaining changes in it #8251 but am leaving this open too. I think smaller PRs are easier to QA - but it's easier to do testing on bigger PRs than of several smaller ones so I'm not sure what the balance is.

However, if you feel smaller PRs are easier then I need to break out the fix in that larger one that deals with a regression off CRM-18480 (which I discovered when the tests I had written for the other patches stopped working :-)

**Comment by eileenmcnaughton** [comment]
I'm merging this based on @JKingsnorth 's comment here https://github.com/civicrm/civicrm-core/pull/8251#issuecomment-220148692 - he has QAd this patch but not approved the others in that PR

@JKingsnorth I wanted to merge this now so I can tidy the other PR up again - but please do add the supporting comments on the QA here as I mentioned

@deepak-srivastava you probably want to be aware of this as it might affect your hook.

**Comment by JKingsnorth** [comment]
Yup, here's the manual tests I conducted on the primary commit.

* Tested safe merging contacts with duplicate email addresses - no duplicate email created (other fields migrated as expected)
* Tested safe merging contacts with duplicate email address and conflicting addresses - caught as a conflict
* Tested force merging those contacts - no duplicate email address added
* Tested safe merging contacts with duplicate phones - no duplicate phone created either - yay
* Tested a 'manual' merge and the add/overwrite options for location fields still work as expected

**Comment by eileenmcnaughton** [comment]
Thanks - I'll try to make sense of the other PR - do you prefer me to put the remaining commits (3) as 1 PR or 3 - I think I can disentangle those ones

**Pull request merged**
