### PR TITLE
Update event_online_receipt_html.tpl

### PR DESCRIPTION
**Pull request by Detsieber**
Fix for https://lab.civicrm.org/dev/core/-/issues/5088

### CODE REVIEW

**Comment by seamuslee001** [comment]
ping @eileenmcnaughton @Detsieber any chance you could have a 5.72 version?

**Comment by eileenmcnaughton** [comment]
Opps! yeah this should be against 5.72

**Comment by Detsieber** [comment]
@eileenmcnaughton @seamuslee001 I am sorry, but I don't how to create a 5.72 version...

**Comment by eileenmcnaughton** [comment]
@Detsieber you can specify the branch here 
image


- but probably you would need to rebase over the 5.72 branch to get rid of commits that don't belong to it - eg

```
git reset --hard origin/5.72
git cherry-pick ff1a26d
git push -f ......
```

**Comment by eileenmcnaughton** [comment]
OK - I've done a port PR so I'll close this

FYI these are the commands I used

```
git checkout -b 572 origin/5.72
git fetch origin pull/29707/head && git cherry-pick FETCH_HEAD
git push eileen 572

```

**Pull request closed without merging**
