### PR TITLE
Add temporary file to help Joomla installers (5.54-rc)

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

Forward-port #24479 from 5.53-stable to 5.54-rc

### CODE REVIEW

**Comment by totten** [comment]
Since the issue affects Joomla install/upgrade mechanism, we discussed on MM and decided on this sequence:

1. Merge on 5.54-rc
2. Test upgrade with RC tarball
3. Merge on 5.53-stable (https://github.com/civicrm/civicrm-core/pull/24479)

**Comment by eileenmcnaughton** [comment]
argh
CRM_Activity_BAO_ActivityTest::testSendEmailBasic
RuntimeException: Scanned file CRM/Contact/Import/Parser.php for class CRM_Contact_Import_Parser, but it was not found.

/home/jenkins/bknix-dfl/build/core-24572-905ke/web/sites/all/modules/civicrm/Civi/Core/ClassScanner.php:205
/home/jenkins/bknix-dfl/build/core-24572-905ke/web/sites/all/modules/civicrm/Civi/Core/ClassScanner.php:138
/home/jenkins/bknix-dfl/build/core-24572-905ke/web/sites/all/modules/civicrm/Civi/Core/ClassScanner.php:113
/home/jenkins/bknix-dfl/build/core-24572-905ke/web/sites/all/modules/civicrm/Civi/Core/ClassScanner.php:92
/home/jenkins/bknix-dfl/build/core-24572-905ke/web/sites/all/modules/civicrm/Civi/Core/ClassScanner.php:61

**Comment by totten** [comment]
Adding some bones to the placeholder fixes that error (on my local).

**Comment by totten** [comment]
@eileenmcnaughton  I did some `r-run` with this process:

* Install Joomla 3.10
* Install Civi 5.49
* Upgrade to Civi 5.53.0 or 5.54-rc

A few things:

* Is there a link to the problem-report?
* On upgrading 5.49.5=>5.53.0, I could see that it left behind the old `CRM/Contact/Import/Parser.php`. However, I did not immediately find a way to provoke the error.
* On upgrading 5.49.5=>5.54-rc, I could see it replaced `CRM/Contact/Import/Parser.php` with the placeholder file. However, there appear to be several left-over files in the heirarchy. 
    ```
    10731  06-02-2022 21:55   civicrm/CRM/Custom/Import/Parser.php
    28772  06-02-2022 21:55   civicrm/CRM/Import/Parser.php
    10361  06-02-2022 21:55   civicrm/CRM/Activity/Import/Parser.php
    11296  06-02-2022 21:55   civicrm/CRM/Event/Import/Parser.php
    34069  06-02-2022 21:55   civicrm/CRM/Contact/Import/Parser.php
    ```

I'm not opposed to releasing a placeholder file even if we don't have full steps to reproduce (*though that would be better*) but... isn't it going to have the same problem with these other files?

**Comment by seamuslee001** [comment]
@totten for a problem report see this thread https://chat.civicrm.org/civicrm/pl/9hr177izmbym7kbkkoxn7ha5br

**Comment by totten** [comment]
Oooh. Thanks @seamuslee001. So for `r-run`, I need to retry with an event registration:

>  I'm using Gantry 5 for theming and when I try to sign up for an event through Civi, the following error occurs. Although, I'm able to successfully sign up and it appears in my participants page within civi. However the error page causes this message to pop up. N

**Comment by totten** [comment]
OK, the event registration angle didn't help me reproduce. But I can reproduce by using "Import Contacts" and going all the through the import. It only manifested as a warning on my local Joomla. But the patch does make it go away.

>  isn't it going to have the same problem with these other files?

Answering my own question... no-yes:

* The specific error about `setImportStatus` only applies to this one file. Even though there are other leftover files in this hierarchy, there's a strong element of happenstance (*dependent upon classes override which methods*).
* There are many more leftover files. As a spot-check, I compared `com_civicrm/admin/civicrm.zip` for 5.49.5 and 5.54-rc -- and there were 197 files which would (in a proper upgrade) be removed. That included ~77 core files and ~120 vendor files.

**Pull request merged**
