### PR TITLE
Remove isset from online contribution receipt

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Remove isset from online contribution receipt

Before
----------------------------------------
fatal errors in api_v3_ContributionTest with grumpy smarty (due to isset)

After
----------------------------------------
isset fails fixed....

Technical Details
----------------------------------------
This removes the isset checks that re failing around
totalTaxAmount (solved the same way as offline
https://github.com/civicrm/civicrm-core/pull/22560/files#diff-fd5668d5492e5f0ec55b7f8a10eccfa4ea9de249e4cf2383a2e0d36dbd92ebe0R134
)

It also removes the isset around contribution.amount_level (switching
to a token) and the enotice on isQuickConfig - this
switches to loading that information & also using a more meaningful variable.
Note that line items should always be assigned so that check is silly.

Comments
----------------------------------------
still some notices around soft credits - but will leave for a follow up

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@monishdeb if you are able to squeeze this into your review efforts it would be great.... (sql goes stale a lot)

**Comment by monishdeb** [comment]
on it..

**Comment by monishdeb** [comment]
r-run passed on a new install and upgrade. There is no breakage on the online contribution receipt mail. Hence merging this PR.

**Comment by eileenmcnaughton** [comment]
yay - thanks @monishdeb

**Pull request merged**
