### PR TITLE
 CRM-20617 : Use API for Batch transaction Listing instead of query

### PR DESCRIPTION
**Pull request by pradpnayak**
----------------------------------------
* CRM-20617: Add hook to alter Batch transaction Listing query
  https://issues.civicrm.org/jira/browse/CRM-20617

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins test this please

**Review by monishdeb — APPROVED** [review]
working fine, this fulfills our IIDA requirement and didn't affect the underlying query.

**Review by jitendrapurohit — APPROVED** [review]
Confirmed that the hook works fine. We need to update docs with the details of this newly added hook probably at  https://github.com/civicrm/civicrm-dev-docs/tree/master/docs/hooks.

**Comment by monishdeb** [comment]
As per discussion with @JoeMurray, we need to rethink of handling this i.e. manipulating the query by adding hook isn't the proper solution. Need to rewrite https://github.com/JMAConsulting/civicrm-core/blob/03e0d76bc1df1f18ec07244740abc735b6ae66b1/CRM/Batch/BAO/Batch.php#L632
to use EntityBatch API.

**Comment by eileenmcnaughton** [comment]
I'm going to close this & let you re-open it when it is review ready

**Pull request closed without merging**
