### PR TITLE
CRM-20566: Fatal error on submit of 'Edit Contribution'

### PR DESCRIPTION
**Pull request by monishdeb**
* [CRM-20566: Fatal error on submit of 'Edit Contribution'](https://issues.civicrm.org/jira/browse/CRM-20566)

### CODE REVIEW

**Comment by monishdeb** [comment]
@eileenmcnaughton can you merge it?

**Comment by alifrumin** [comment]
I'm at the St. Louis sprint, I was running into this problem yesterday, I can test this.

**Comment by alifrumin** [comment]
With this PR I was successfully able to submit an edited contribution from the "Edit Contribution" page, I did not get a fatal error (0 is not a valid option for pcp_id) as documented in the jira issue (and as I was when testing yesterday) Thank you @monishdeb.

@eileenmcnaughton this looks ready to be merged

Looks good to be merged to me @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
Thanks, I've merged this. I'm pretty sure this is a regression on the unreleased 4.7.20 not the released 4.7.19 - so changing the JIRA to that. Please change again if I am wrong

**Comment by alifrumin** [comment]
I was testing against master (so Im thinking unreleased 4.7.20 too)

**Pull request merged**
