### PR TITLE
CRM-19110: Fix delete pledge payments

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
- [CRM-19110: Changing Amount of Pledge Creates Additional Expected Installments Instead of Updating Existing Installments](https://issues.civicrm.org/jira/browse/CRM-19110)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
this is a backport which I tested on a 4.6 site & it solved the problem as described

**Comment by seamuslee001** [comment]
@eileenmcnaughton  I think this may be related to your PR https://test.civicrm.org/job/CiviCRM-Core-PR/10941/testReport/(root)/CRM_Pledge_BAO_PledgePaymentTest/testDeletePledgePayments/

**Comment by eileenmcnaughton** [comment]
hmm - master has a different signature on the test helper - hopefully that will fix it

**Comment by seamuslee001** [comment]
@eileenmcnaughton you need to fix your dot block :-P

**Pull request merged**
