### PR TITLE
dev/core#1291 Use name instead of label to check contribution status

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
This will fail if the label is changed (eg. different language).  Now it won't.

https://lab.civicrm.org/dev/core/issues/1291

Before
----------------------------------------
Check label

After
----------------------------------------
Check name

Technical Details
----------------------------------------
Need to check name not label.

Comments
----------------------------------------
@mlutfy This is similar to other translation fixes you've done - can you check?

### CODE REVIEW

**Comment by mlutfy** [comment]
Seems OK on code review. How can I reproduce?

**Comment by mattwire** [comment]
@mlutfy I'm not sure how you could reproduce - I just came across it when tracing another issue and thought "that will cause problems".

**Comment by jitendrapurohit** [comment]
Agree with the change made here. It looks like this file was recently changed and refactored here - https://github.com/civicrm/civicrm-core/pull/15124/files. This PR seems to revert that line to correctly retrieve the status value by name.  +1 to get this merged

**Comment by mlutfy** [comment]
Merging based on Jitendra's review, and also on #15391 from @samuelsov.

**Pull request merged**
