### PR TITLE
fix autoloading issue for cv & civix cli tools

### PR DESCRIPTION
**Pull request by wannesderoy**
Remove the $autoloader::getLoader() method call, because the $autoload var already contains that result by requiring the autoload.php from the Drupal 8 web root.

Overview
----------------------------------------
Small update to Drupal8.php file to fix an autoloading issue for cli tools like cv & civix.

Before
----------------------------------------
The autoloader from Drupal was being required. Then the getLoader() was called on a class in the autoloader (which did not exist). But the autoloader already contains the result of that method.

After
----------------------------------------
We removed the getLoader() method on the autoloader class and pass it straight to request component.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@wannesderoy are you able to resubmit against master branch rather than against the 5.4 branch - 5.4 is in the testing stage prior to a release first Wed of next month - we are now merging to master for later releases

**Comment by eileenmcnaughton** [comment]
@dsnopek @jackrabbithanna

**Comment by eileenmcnaughton** [comment]
these lines were added here - https://github.com/davecivicrm/civicrm-core/commit/45b293a277a1d542c074c227358ab2b9cede59df

**Comment by wannesderoy** [comment]
@eileenmcnaughton thanks for taking a look! I submitted a new pull request against the master branch https://github.com/civicrm/civicrm-core/pull/12498

**Comment by dsnopek** [comment]
This change is going to break things in Drupal 8, and I don't think it'll fix the problem you're experiencing (at least without adding another problem :-)).

```
$autoloader = require_once $root . '/autoload.php';
```

This will only return the autoloader class the first time that `require_once` is called. If this method is called more than once, then `$autoloader` will contain `TRUE` which will cause problems when later code tries to use it as an object.

The original code was:

```
$autoloader = require_once $root . '/vendor/autoload.php';
if ($autoloader === TRUE) {
  $autoloader = ComposerAutoloaderInitDrupal8::getLoader();
}
```

So, other than the change from 'vendor/autoload' to just 'autoload.php', it'll do the same thing as your new code the first time this runs. But without the check for `=== TRUE`, it'll fail the second time.

The class `ComposerAutoloaderInitDrupal8` is what Drupal should be naming the autoloader class per its composer.json. If you're building your Drupal code base some other way, you may need to update your composer.json to have:

```
    "config": {
        "autoloader-suffix": "Drupal8"
    },
```

That said, the best fix would be to make it so that the $autoloader object is cached somewhere the first time this runs, so that running it again would just use that same object again, rather than trying to load the autoload.php a second time.

**Comment by wannesderoy** [comment]
I reverted my change to Drupal8.php locally and reinstalled the vendor packages with the new config line "autoloader-suffix": "Drupal8". This indeed fixed my initial problem.

The problem in our Drupal 8 setup is that our vendor folder is outside the Drupal root. If you download the core from [here](https://www.drupal.org/project/drupal/releases/8.5.5) it is. But there are many other ways of installing Drupal. And the best practice around a vendor folder is not to have them in the webroot.
I still would like to suggest that

**Comment by dsnopek** [comment]
There's this issue in Gitlab about running with the vendor directory outside of the webroot (a couple things are required):

https://lab.civicrm.org/dev/drupal/issues/9

This linked PR is the closest to solving the issue in your comment above:

https://github.com/civicrm/civicrm-core/pull/12198

... but maybe your solution is better! Then we don't need to have list a possible paths at all. Please post a new PR :-)

**Comment by wannesderoy** [comment]
I've made a new PR https://github.com/civicrm/civicrm-core/pull/12499 

For now this does seem like the simples solution! I will test it more extensively and hope no other issue emerg.

**Pull request closed without merging**
