### PR TITLE
Fix to tax calculation on Contribution page

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
https://civicrm.stackexchange.com/questions/37533/wrong-tax-calculation-on-donation-pages

Before
----------------------------------------
Screen Shot 2020-08-29 at 00 57 36

After
----------------------------------------
Screen Shot 2020-08-29 at 00 57 10

### CODE REVIEW

**Comment by seamuslee001** [comment]
@KarinG are you able to review this one?

**Comment by KarinG** [comment]
I think Eileen is taking the weekend off - so I'll be the one saying that it needs a test :-)

**Comment by KarinG** [comment]
Any history on why and when this broke?

**Comment by pradpnayak** [comment]
> Any history on why and when this broke?

I haven't investigated as this was pro-bono to help on [SE](https://civicrm.stackexchange.com/questions/37533/wrong-tax-calculation-on-donation-pages).

**Comment by KarinG** [comment]
I opened a lab issue -> https://lab.civicrm.org/dev/core/-/issues/1983 -> confirming that this code edit fixes 'Total Tax Amount on the Contribution (generated in backoffice/offline) no longer adds up to sum of the Tax Amount for the individual line items' as well. 

Will look at the previous sale tax unit tests I've added in the past to see if I can expand one to cover this scenario.

**Comment by eileenmcnaughton** [comment]
@pradpnayak I have put up https://github.com/civicrm/civicrm-core/pull/18290 - it differs only slightly from your fix - I think it helps with the underlying confusingness of what is going on in that bit of code while being substantively the same fix

**Comment by eileenmcnaughton** [comment]
@pradpnayak I'm closing this as we merged the variant

**Pull request closed without merging**
