### PR TITLE
CRM-16112 add type for api _spec functions … 

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
A

### CODE REVIEW

**Comment by colemanw** [comment]
Funny we seem to have gotten the same idea at the same time.
I added a few types but mostly was sorting out the misuse of 'title' attribute and changing lengthy titles to the more appropriate 'decription' in #5394
Since this is already stale, I'd suggest you wait for me to merge #5394 before rebasing this one (just waiting for tests to complete, should be done soon)

**Comment by eileenmcnaughton** [comment]
Dang that sucks - looks like it will be quite a big rebase due to our amazing mental synchronicity

**Comment by colemanw** [comment]
I'll do the rebase if you'll finish off the multiple relationship patch :)

**Comment by eileenmcnaughton** [comment]
sold!

btw I did a syntaxConformance test too - but haven't added that as there are still several that are failing - ie. tidy up in incomplete so did't do the syntax conformance

**Comment by colemanw** [comment]
Hmm... pretty straightforward except if a param is supposed to be an array, what on earth is the type?

**Comment by eileenmcnaughton** [comment]
yeah - I was a bit stuck on that too... I suspect it will not cause a problem in the api layer if it is string in that case - as I think the checking will only affect pseudoconstants.

Alternatively we could add array to CRM_Utils_Type.

Or we could add something to the api that says yeah - don't get too hung up on this field because it's an aberation - e.g 

$params['group'] ['is_abhorrent'] = 1;

and work to only use arrays in standardised ways...

**Comment by colemanw** [comment]
Rebased as #5397

**Pull request closed without merging**
