### PR TITLE
 Add upgrade to replace legacy contribution tokens from message templates

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Add upgrade to replace legacy contribution tokens from message templates

Before
----------------------------------------
People with saved templates with the old values would need to manually fix them before using them to create a pdf of send an email

After
----------------------------------------
DB updated automatically

Technical Details
----------------------------------------
Under legacy token replacement these 4 work
contribution.contribution_status
contribution.contribution_status_id:label
contribution.campaign
contribution.campaign_id:label

But only the label ones work with the processor. This upgrades the
old ones our of the message templates table

Comments
----------------------------------------
@demeritcowboy

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Easiest review ever ... no file changes! ... merge-on-pass.
He he...

**Comment by eileenmcnaughton** [comment]
Argh - that commit got so broke!

**Comment by eileenmcnaughton** [comment]
OK - I think now...

**Comment by eileenmcnaughton** [comment]
@demeritcowboy should be OK now

**Comment by demeritcowboy** [comment]
I admit I'm getting confused by all the different contexts but think I have this one straight now.

Ok so non-workflow templates, e.g. used for Find Contributions - Send Email: Good.

For workflow, the upgrade doesn't replace them but you can't use these tokens in workflow templates anyway, because it doesn't have the context and needs to get the data from smarty variables. Although when you do use them, e.g. in the offline receipt template and by choosing send receipt when you make a contribution, it seems to know enough to recognize them as tokens in the sense it "replaces" them, but they are replaced by blanks, instead of outputting a literal `{contribution.X}`.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy yeah I'm starting to look at the workflow templates a little - eg. here https://github.com/civicrm/civicrm-core/pull/21611 & that converts them to allowing tokens - in that case contribution recur (the example data config is missing there though I think)

**Pull request merged**
