### PR TITLE
CRM-21203 Fixes for Joomla 3.8+ CRON/cli and directories

### PR DESCRIPTION
**Pull request by mattwire**
Work in progress fixes for Joomla 3.8 to fix cli.php and cron.php

---

 * [CRM-21203: cli.php PHP error prevents cron jobs from running](https://issues.civicrm.org/jira/browse/CRM-21203)

### CODE REVIEW

**Comment by vingle** [comment]
I've tested this on Joomla 3.8.1 and J3.7.5 with CiviCRM 4.7.25 and confirm crons are running as expected, with no adverse behaviour.

**Comment by mattwire** [comment]
@totten Thoughts on merging?  Without it civi on Joomla is a bit broken... and it doesn't seem to have any adverse effects for those who have installed.  As it only touches one file it can't impact anything other than Joomla sites...

**Comment by seamuslee001** [comment]
I think the code makes sense and is limited to Joomla integration only. I have seen supportive comments in JIRA and here that this fixes the issues reported. I think this is good to merge @totten @eileenmcnaughton

**Comment by jorich-2000** [comment]
I have tried this on a couple of joomla 3.8.1 sites running under PHP 7.0.24 and 7.1.16 - although CRON runs I get a list of warnings:
/httpdocs/administrator/components/com_civicrm/civicrm/bin/cli.php" successfully completed in 1 seconds, output:

PHP Notice: Constant JPATH_ISWIN already defined in /var/www/vhosts/nlcbanham.org.uk/httpdocs/libraries/import.legacy.php on line 64
PHP Notice: Constant JPATH_ISMAC already defined in /var/www/vhosts/nlcbanham.org.uk/httpdocs/libraries/import.legacy.php on line 65
PHP Notice: Constant JROUTER_MODE_RAW already defined in /var/www/vhosts/nlcbanham.org.uk/httpdocs/libraries/import.legacy.php on line 72
PHP Notice: Constant JROUTER_MODE_SEF already defined in /var/www/vhosts/nlcbanham.org.uk/httpdocs/libraries/import.legacy.php on line 79
PHP Notice: Constant JROUTER_MODE_RAW already defined in /var/www/vhosts/nlcbanham.org.uk/httpdocs/libraries/import.php on line 60
PHP Notice: Constant JROUTER_MODE_SEF already defined in /var/www/vhosts/nlcbanham.org.uk/httpdocs/libraries/import.php on line 67

**Pull request merged**
