### PR TITLE
[search kit] Semicolon vs comma

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
@colemanw This is the error on my local I was seeing earlier. Not sure why it doesn't show on the test site / dmaster.demo.

Before
----------------------------------------
* ReferenceError: assignment to undeclared variable apiParams
* Search kit searches list doesn't load completely

After
----------------------------------------

Technical Details
----------------------------------------
Comma

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
Yes that was definitely a typo. MOP.

**Comment by demeritcowboy** [comment]
Oh it's the enable debugging setting. When it's on it seems to also make angular more angrier.

**Comment by colemanw** [comment]
Haha. Too bad the debug setting makes our `.tpl` based pages nearly unusable, prompting me to turn it off. What idiot added that feature anyway?

**Comment by demeritcowboy** [comment]
He he.
Must have been that other Coleman.

**Comment by colemanw** [comment]
Now I've enabled debug mode and hitting this bug. Merging fixes it.

**Pull request merged**
