### PR TITLE
Make is_archived work as a url-search parameter

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Eg civicrm/mailing/browse/scheduled?reset=1&is_archived=1&force=1

Before
----------------------------------------
is_archived cannot be passed in the url using our normal url protocol

After
----------------------------------------
```civicrm/mailing/browse/scheduled?reset=1&is_archived=1&force=1``` works, other params would work if in metadata

Screen Shot 2020-05-15 at 12 57 17 PM

Technical Details
----------------------------------------
Ref https://github.com/civicrm/civicrm-core/pull/16478

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins retest this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton I checked this and i saw that it still wasn't quite being passed to the underlying query but i suspect that that is a problem with this search form given it is different to all the others

**Comment by eileenmcnaughton** [comment]
@seamuslee001 ok - I've hacked it around - I guess making this screen work with the url was never really the point - the point was to see how this field would convert to metadata, but having framed it around the field I had to make it work

**Comment by seamuslee001** [comment]
(*CiviCRM Review Template WORD-1.2*)



* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) Pass
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) Pass
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) Pass
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) Pass I was able to pass in is_archived=1 and also as 0 as appropriate into the urls and confirmed that it worked correctly with the current search interface
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) Pass
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) Pass
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) Pass
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) Pass

**Pull request merged**
