### PR TITLE
Recipient phone number is invalid or recipient does not want to receive SMS" error and Contacts with DoNotSms preference failing to filter out during Mass Sms in 5.x

### PR DESCRIPTION
**Pull request by jyothi-shree21**
https://lab.civicrm.org/dev/core/issues/273

**Reason for changes:** https://github.com/veda-consulting/org.civicrm.sms.clickatell/issues/20#issuecomment-404499746

**Overview**
civicrm/CRM/Activity/BAO/Activity.php is failing in function sendSMSMessage(Because $doNotSms = TRUE;)
1>Fix for the error-"Recipient phone number is invalid or recipient does not want to receive SMS" while sending Sms to individual.
2>Fix for filtering out contacts with preference "donotsms" while mass sms

**Before:**
$doNotSms = TRUE; in civicrm/CRM/Activity/BAO/Activity.php

'do_not_sms' => CRM_Utils_SQL_Select::fragment()->where("$contact.do_not_sms = 0"), missing in civicrm/CRM/BAO/Mailing.php in function ($isSMSmode) {}

**After:**
$doNotSms = TRUE; - This flag is removed altogether in civicrm/CRM/Activity/BAO/Activity.php

'do_not_sms' => CRM_Utils_SQL_Select::fragment()->where("$contact.do_not_sms = 0") is included within if ($isSMSmode) {} in civicrm/CRM/BAO/Mailing.php

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
add to whitelist

**Comment by eileenmcnaughton** [comment]
@jyothi-shree21 check the link to our coding standards here - https://docs.civicrm.org/dev/en/latest/core/contributing/ - your first hurdle is getting the whitespace right.

Also - looks like you want to squash into one commit - TBH I would just reset to origin/master & re-do the commit & then force push rather than rebase in this case.

**Comment by eileenmcnaughton** [comment]
Note that @deepak-srivastava is working with the submitter in the first instance

**Comment by jyothi-shree21** [comment]
Reopened in https://github.com/civicrm/civicrm-core/pull/12554

**Pull request closed without merging**
