### PR TITLE
updated italian provinces (CRM-5048)

### PR DESCRIPTION
**Pull request by masetto**
Overview
----------------------------------------
There are some wrong italian abbreviation provinces added in [CRM-5048](https://issues.civicrm.org/jira/browse/CRM-5048).

Comments
----------------------------------------
I modified only `xml/templates/civicrm_state_province.tpl` and not `sql/civicrm_generated.mysql` and other language files. I don't know how to do and if I have to do.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
For sql/civicrm_generated.mysql, manually updating it would work here since no ids are changing. For an upgrade script, something like https://github.com/civicrm/civicrm-core/blob/1c8707d6ae7f034474e400a42a4650985616b631/CRM/Upgrade/Incremental/sql/5.26.alpha1.mysql.tpl#L9-L13 should work, just instead of `s.name` of course you'd use `s.abbreviation`.

**Comment by masetto** [comment]
@demeritcowboy What do you advise me to do?
- manually update sql/civicrm_generated.mysql?
- create a new CRM/Upgrade/Incremental/sql/5.29.beta2.mysql.tpl file? Or change the last one (5.9.beta1.mysql.tpl).

**Comment by demeritcowboy** [comment]
Thanks for the update. Code looks ok and will try it out later today.

**Comment by seamuslee001** [comment]
Jenkins add to whitelist

**Comment by demeritcowboy** [comment]
* General standards
    * [`r-explain`] __PASS__
      * Normally the subject uses the lab ticket code not the old jira code, since then the bot can link them, so it would be `dev/core#2145 - updated italian provinces`. And you can still have the link to jira in the description.
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __PASS__
      * Install works. Upgrade works / and shows correct province for existing contacts.
* Developer standards
    * [`r-tech`] __PASS__
    * [`r-code`] __PASS__
    * [`r-maint`] __PASS__ Don't usually have unit tests for these.
    * [`r-test`] __PASS__

**Comment by seamuslee001** [comment]
Merging as per @demeritcowboy 's review

**Pull request merged**
