### PR TITLE
[Test] fix test setup on ANet tests

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Test set up fix, including fixing Order.create to support being chained

Before
----------------------------------------
Test set up creates invalid Order & hence tests to ensure Order is correct fail

After
----------------------------------------
Test uses methods that create valid transactions. In order to support it I had to fix Order.create to support being chained

Technical Details
----------------------------------------
Per https://github.com/civicrm/civicrm-core/pull/15706 the setup for this test
is creating invalid transactions. This fixes - I had to do an order fix in the process

Comments
----------------------------------------
Issue exposed in https://github.com/civicrm/civicrm-core/pull/15706

### CODE REVIEW

**Comment by mlutfy** [comment]
jenkins, test this please

I'm not sure if the test fails are related:

```
    CRM_Export_BAO_ExportTest.testGetSQLColumnsAndHeaders with data set #5
    CRM_Export_BAO_ExportTest.testExportComponentsMembership
    CRM_Member_Selector_SearchTest.testSelectorGetRows
```

**Comment by eileenmcnaughton** [comment]
@mlutfy yep - it was an e-notice - should be fixed now

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@mlutfy this is passing now!

**Comment by mlutfy** [comment]
:tada:

**Pull request merged**
