### PR TITLE
dev/core#1082 properly regenerate civicrm_generated file

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
Ensure that message templates are created correctly initially by runing ./bin/regen.sh

This PR will go stale relatively quickly

ping @eileenmcnaughton @demeritcowboy

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Feels like this would affect 5.15 but not 5.14 so gtg

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by demeritcowboy** [comment]
@eileenmcnaughton It does affect 5.14 new install with sample data.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy argh -

**Comment by eileenmcnaughton** [comment]
@seamuslee001 5.14 too?

**Comment by demeritcowboy** [comment]
Did a quick look around. Seems good. Also tried installing with master and seems ok (it warned about schema upgrade needed, which makes sense, and that went ok). Thanks @seamuslee001.

**Pull request merged**
