### PR TITLE
Fix deletion of contact sub_type in api4

### LINKED ISSUE #160: Contact::update() clears contact subtype
Using version 4.5.0 (master) + CiviCRM master.

This resets contact subtype to null!  (There are two custom values being set here as well which do get set).
```
    $results = \Civi\Api4\Contact::update()
      ->addWhere('id', '=', $contact['id'])
      ->addValue('Documents.Document_Type', $this->mapDocumentType($params))
      ->addValue('Documents.Date_Uploaded', $uploadDate)
      ->execute();
```

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes https://github.com/civicrm/org.civicrm.api4/issues/160 and cleans up the contact BAO to not arbitrarily delete a contact's sub-type.

Before
----------------------------------------
BAO deletes a contact's sub-type for no apparent reason. I think this was a workaround from back when the field was a single select or checkboxes on the form and an empty value would come back as null. That's no longer the case and the form seems to work fine without this hack, so I removed it.

After
----------------------------------------
A contact can be saved without the subtype being deleted.

Comments
----------------------------------------
Api4 test coverage added.

### CODE REVIEW

**Comment by seamuslee001** [comment]
test fail looks related @colemanw https://test.civicrm.org/job/CiviCRM-Core-PR/26876/testReport/junit/(root)/CRM_Contact_BAO_ContactType_ContactTest/testUpdateContactSubtype/

**Comment by colemanw** [comment]
Ok I've removed some more wild & wacky handling of this field in favor of consistency.

**Comment by colemanw** [comment]
@eileenmcnaughton I tried this with your contacteditor extension, and it's not an issue because that form refuses to change contact type if the sub type is not empty.

**Comment by colemanw** [comment]
Retest this please

**Pull request merged**
