### PR TITLE
Improve schema metadata for Search Kit

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Improves the relevance of entities listed in Search Kit by:
1. Excluding entities from disabled components.
2. Designating some entities as not searchable.

Before
----------------------------------------
1. All entities returned from APIv4 `Entity::get()`.
2. No metadata about which entities are searchable.

After
----------------------------------------
1. APIv4 `Entity::get()` excludes entities from disabled components.
2. Search kit excludes API entities annotated `@searchable false`.

### CODE REVIEW

**Comment by colemanw** [comment]
@seamuslee001 @eileenmcnaughton @totten this PR is mostly just adding metadata. It'll go stale quickly.

**Comment by seamuslee001** [comment]
Makes sense to me MOP

**Comment by seamuslee001** [comment]
@colemanw test fail relates

`api\v4\Entity\ConformanceTest::testEntitiesProvider`

**Comment by colemanw** [comment]
Right. That's because the test suite doesn't enable all components by default. Should be fixed now.

**Pull request merged**
