### PR TITLE
CRM-17690 - Grant fields being retrieved by default when completely i…

### PR DESCRIPTION
**Pull request by jitendrapurohit**
…rrelevant https://issues.civicrm.org/jira/browse/CRM-17690

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
jenkins, test this please

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
jenkins retest this please

**Comment by eileenmcnaughton** [comment]
I haven't tested this - but the code looks correct to me.

**Pull request merged**
