### PR TITLE
dev/core#1798 - "End of yesterday" Relative Date Filter

### PR DESCRIPTION
**Pull request by semseysandor**
Overview
----------------------------------------
[GitLab Issue](https://lab.civicrm.org/dev/core/-/issues/1798)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins add to whitelist

**Comment by eileenmcnaughton** [comment]
@magnolia61 @MegaphoneJon is either of you able to test this.

Note this is a first-time contributor - so thank you @semseysandor & I'll spare you my push on unit tests this round :-)

**Comment by semseysandor** [comment]
@eileenmcnaughton It's OK, I've added the tests as well

**Comment by eileenmcnaughton** [comment]
Ohh - well done!

**Comment by eileenmcnaughton** [comment]
@semseysandor looks like you have some style warnings picked up by jenkins - if you click on the red x above you should see them.

**Comment by jaapjansma** [comment]
* General standards
    * Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
        * __PASS__ : The goal/problem/solution have been adequately explained in the PR.
    * User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
        * __PASS__: The change would be intuitive or unnoticeable for a majority of users who work with this feature.
    * Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
        * __PASS__: The changes do not require documentation.
    * Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
        * __PASS__: We followed the description given in the lab issue. 
* Developer standards
    * Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
        * __PASS__: The change preserves compatibility with existing callers/code/downstream.
    * Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
        * __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
    * Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
        * __PASS__: The change sufficiently improves test coverage, or the change is trivial enough that it does not require tests.
    * Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
        * __PASS__: The test results are all-clear.

@eileenmcnaughton @seamuslee001 could one of you merge this PR?

@semseysandor Thanks for your PR and thanks for all your hard on it including adding a test and well described issue on how to reproduce it!!

**Pull request merged**
