### PR TITLE
CRM-19186 / CRM-20959 Subsequent Installments of Recurring Credit Card Contributions Indicate a Payment Instrument of Check

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
CRM-19186
CRM-20959

---

 * [CRM-19186: Subsequent Installments of Recurring Credit Card Contributions Indicate a Payment Instrument of Check](https://issues.civicrm.org/jira/browse/CRM-19186)
 * [CRM-20959: IPN recording incorrect contribution data](https://issues.civicrm.org/jira/browse/CRM-20959)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@xurizaemon this fixes the problem & moves to a better tested / more recommended copy path - but it would need thorough review. I think I'll set to WIP until you have prod tested it.

**Comment by eileenmcnaughton** [comment]
also needs a jira

**Comment by eileenmcnaughton** [comment]
Oh right - I actually wrote a patch as well as a fix  - I guess I'll remove WIP & wait for you to confirm how it goes in production. Note that I think it's better to give any date clean up script it's own PR so we can close this against the issue it is closed in

**Comment by monishdeb** [comment]
Patch works fine. Only stuff remaining, like @xurizaemon said will be to write upgrade code to fix the oddities in financial trxn. Are we expecting a separate PR for that?

**Comment by eileenmcnaughton** [comment]
@monishdeb I don't think we should hold this PR on the upgrade code

**Comment by monishdeb** [comment]
This patch fixes the bug described in the issue. Merging it now

**Comment by monishdeb** [comment]
@eileenmcnaughton in exchange can you review and merge this PR https://github.com/civicrm/civicrm-core/pull/10681 ?

**Pull request merged**
