### PR TITLE
Fix wrong exit function

### PR DESCRIPTION
**Pull request by colemanw**
https://issues.civicrm.org/jira/browse/CRM-19211

### CODE REVIEW

**Comment by colemanw** [comment]
This looks like the wrong function was being used to exit. The way it was written it would have caused a fatal error due to the missing required param, but probably no one noticed because it was a silent ajax call?
@deepak-srivastava can you confirm this fix?

**Comment by eileenmcnaughton** [comment]
If you add a JIRA for this & put it in dedupe component we can pick it up in the QA cycle

**Comment by colemanw** [comment]
Done.

**Comment by totten** [comment]
Agree the old code would be erroneous.

The new code technically changes the response type, but the consumer doesn't even try to parse the output, so it's fine.

This needed a small style fix  (558cd7c7e). Merged manually.

**Pull request merged**
