### PR TITLE
CRM-17212: Set session handler to "files" in extern/*php

### PR DESCRIPTION
**Pull request by xurizaemon**
Resubmit of #6736 

As per discussion in that thread 
- no, it's not possible to configure this in Pantheon via php.ini
- yes, this bug prevents sites receiving IPN on Pantheon
- it does feel like coupling, but given that neither Pantheon nor CiviCRM permit configuration in this path, there seems to be no alternative
- this will remain an issue on such environments as long as CiviCRM initialises session in external scripts before loading configuration (ie, destroy external scripts and use callbacks)

---
- [CRM-17212: Set session handler to "files" in extern\/*php](https://issues.civicrm.org/jira/browse/CRM-17212)

### CODE REVIEW

**Comment by colemanw** [comment]
I'm not totally opposed to merging this, but would you consider one more idea to loosen the coupling:
what about putting the pantheon-specific code (`ini_set...`) in a separate php file, and locating that file somewhere it could be overridden.
Then change all the above patches from

    if (defined('PANTHEON_ENVIRONMENT')) {
      ini_set('session.save_handler', 'files');
    }

to

    include_once 'path/to/extern_config.php';

The nice thing about `include_once` is that it won't bomb if the file is missing. So the Pantheon distro of CiviCRM could ship with that file, others could ship with other files as necessary. If we could think of a way to locate that file outside the civicrm directory that would be a plus, but even if we stick it in the civicrm/extern directory and ship it with core, that's still IMO a small step forward (at least all the pantheon-specific stuff is in one file instead of 8).

**Comment by eileenmcnaughton** [comment]
Note that most of these files are not required. The code is in place to bypass the ipn files for Authorize & Paypal IPNS (by calling civicrm/payment/ipn/x rather than that file). 

The 2 google ones I would advocate against fixing since the main blocker to us getting those out of core is finding nay evidence of anyone who actually uses it & then using that person as the tester.

We also have a pretty clear path WRT getting DPS out of core which should move soon-ish.
That leaves rest, soap & install. I suspect there is a better option for soap but I have no idea about the other 2.

Which one is driving this? I would probably look to only 'fix' soap & install with the goal of eliminating the others.

**Comment by xurizaemon** [comment]
@colemanw if I land back on this (ie if I hit another site that breaks as a result) then I'll explore whether we can load config before `session_init()`, my expectation is that the session is entirely useless here and just got copied in back in the dark ages

Don't really care if this makes it into core, submitted PR as part of "let's see if we can make CiviCRM behave on Pantheon" because it's a nice to have but it's not funded work or anything.

**Comment by colemanw** [comment]
I guess I should either merge this or close it. Eenie meenie minie... merge.

**Pull request merged**
