### PR TITLE
dev/core#830 [REF] Add unit tests on contribution recur trxn_id, contribution recur processor id

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Clean up & additional tests for recurring contribution search fields

Before
----------------------------------------
Less tests, more special handling

After
----------------------------------------
More tests, less special handling

Technical Details
----------------------------------------
This is preliminary cleanup towards exposing cancel_reason as a search field, as committed to in [proposal to add the field](https://lab.civicrm.org/dev/core/issues/830). This change

- adds unit tests for the trxn_id & processor_id fields
- makes the handling of 2 existing fields more generic
- adds contribution recur field data to the contribution query object so it can be accessed.

Some points about the last of these. Basically we have a situation where the query object needs metadata to avoid field by field handling. We have done this is some wierd & wonderful ways with dependencies on 'import' & 'export' metadata info to the point where they were given to so many fields as to become meaningless.

I think this method is better - ie. just adding the additional metadata to the query class for all the entities it deals with. A recently merged PR means 'where' data is still available using this method.

Also I have added uniquenames to the contribution recur fields. Uniquenames no longer really matter outside
- the query object
- profiles
- possibly import & export

We only really expose recurring contribution info through the query object of these so it should be safe. In a future happy
space apiv4 & namespacing will render uniquenames a distant memory.

I couldn't rip out the special handling entirely without dealing with the labels that go into the qill. I figure we should merge this & then address that - but briefly the issue is that @mattwire has just changed all the labels to not quite work in this context so we need to discuss / agree how to manage 'Recurring Contribution Trxn ID' vs'Trxn ID'.

I also didn't want to rip out the special handling fully in advance of https://github.com/civicrm/civicrm-core/pull/14118
being merged as there could be a performance regression if we let more code hit that unnecessary join line

UPDATE - the unit tests showed that if I include fields in $fields without uniqueNames they can clobber the fields from other entities. I have added a whitelist to work through this with more care

Comments
----------------------------------------
@mattwire @colemanw @seamuslee001 @monishdeb FYI - I think this is fairly straightforward but the label follow up might need more discussion.

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 if we merge this I'll take a look at the date fields for contribution recur search

**Comment by seamuslee001** [comment]
This looks right to me, adding unique aliases for the fields change looks good and is backed up with some tests, I also believe we have enough tests in this area to show if this was to break anything, merging

**Pull request merged**
