### PR TITLE
Scheduled Jobs - Define and track  "last_run_end"

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Currently if a job throws an exception it's caught and logged in JobLog. But if it fails for another reason (eg. 500 error, Out of Memory) it silently crashes and stops all jobs from running because it tries to run again and crashes every time you run cron.

Before
----------------------------------------
No easy was to identify that a job started but did not finish. You can analyse the civicrm_job_log table but as you won't find a "job completed" log entry it requires some interesting queries to identify this situation (because you have to try to match the lack of a record with an existing "job start" record of which there will be many...

After
----------------------------------------
If a job completes (whether successful or by exception) it will record a last_run_end date in the job table.

This could be used to improve system status messages but also the queuing and prioritising of scheduled jobs. For example a simple sort on last_run_date is not empty would prevent a single bad job from stopping execution of all other jobs.

Technical Details
----------------------------------------
Add a new field to the table. Add job to scheduled job runner to clear and populate the field.

Comments
----------------------------------------
We don't implement any logic in this PR to use the field for analysis or to prioritise the job queue. This could be done in a future PR.

### CODE REVIEW

**Comment by totten** [comment]
This does seem like a pretty good idea, and the patch includes some good/non-obvious bits.

 (I haven't run tho.)

**Comment by totten** [comment]
@mattwire Error:

``` 
Add last_run_end column to Job table (CRM_Upgrade_Incremental_php_FiveSeventyTwo::addColumn(civicrm_job,last_run_end,last_run_end timestamp NULL DEFAULT NULL COMMENT "When did this cron entry last finish running"))
Error executing task "Add last_run_end column to Job table"

In Error.php line 971:
                                          
  [Civi\Core\Exception\DBQueryException]  
  DB Error: syntax error                  
                                          
```

**Comment by totten** [comment]
For the rest of the patch, I did some `r-run` and provoked various hacks (e.g. using `sleep(5)` to slow down job; interjecting exceptions and PHP fatals). It seemed to behave as expected.

Should allow a brief pause in case others have comments. Flagging `merge ready`.

**Comment by highfalutin** [comment]
Reading through the code, this looks good and I agree it will be useful.

**Comment by seamuslee001** [comment]
I think people have had some time now to get their heads around this merging

**Pull request merged**
