### PR TITLE
dev/report#31 - Api4 Explorer: Support SQL functions and HAVING clause

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
This adds UI support for new APIv4 features. Sql functions and aliases are now available in the API explorer, as is the HAVING clause.

See also: https://lab.civicrm.org/dev/report/-/issues/31

Before
----------------------------------------
UI didn't show new features.

After
----------------------------------------
UI updated.

Technical Details
----------------------------------------
Includes tests for loading SQL function metadata.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Only affects apiv4 explorer so this should be safe

**Comment by totten** [comment]
`r-explain`: The descriptions on #17047 and #16947 are rather... thin... given what's going on here. Is there a Gitlab issue or docs PR that should be referenced?

**Comment by totten** [comment]
OK, I found+hyperlinked the related Gitlab issue. It doesn't talk much about what's going on here.

Probably most of the `r-explain`/`r-docs` problem I'm sensing is more about the earlier PR (#16947). For this PR and the API explorer, one might just do some screenshots of the updated API Explorer...

**Comment by eileenmcnaughton** [comment]
To some extent the explorer update IS the documentation of the earlier change - however @colemanw you had better also do a docs update on new apiv4 capabilities

Test fail unrelated

**Pull request merged**
