### PR TITLE
CRM-17754 Include resent headers to ensure that SPF and probably DMAR…

### PR DESCRIPTION
**Pull request by seamuslee001**
…C checking works as Mail Clients will know we are forwarding on the reply

### CODE REVIEW

**Comment by totten** [comment]
+1 for dgg's question in JIRA -- it would help to have some instructions about how to test this.

**Comment by seamuslee001** [comment]
Have responded to the question in JIRA. Probably simplest test is to create a dummy civimail with reply tracking and then reply to it and check the headers of the reply and make sure that it correctly uses the resent-from to do the testing of DMARC and SPF

**Comment by eileenmcnaughton** [comment]
I tried this without success but it might be the domain config? @xurizaemon 

NB the reply should have been forwarded to my Fuzion email but I did not receive it - presumably it's in my spam folder.... if I knew how to get to it


Aug 17 16:14:09 fugu postfix/pickup[2867]: 3AB2728079D: uid=33 from=<eileen@x.x>
Aug 17 16:14:09 fugu postfix/cleanup[18033]: 3AB2728079D: info: header To: eileen@x.x.x from local; from=<eileen@x.x>
Aug 17 16:14:09 fugu postfix/cleanup[18033]: 3AB2728079D: info: header Subject: test from local; from=<eileen@x.x>
Aug 17 16:14:09 fugu postfix/cleanup[18033]: 3AB2728079D: info: header From: Eileen McNaughton <eileen@x.x> from local; from=<eileen@x.x>
Aug 17 16:14:09 fugu postfix/cleanup[18033]: 3AB2728079D: message-id=<a1b43438-300d-4da9-6881-db4ee0b66b8d@x.x>
Aug 17 16:14:09 fugu postfix/cleanup[18033]: 3AB2728079D: resent-message-id=<20160817041409.3AB2728079D@fugu.fuzion.co.nz>
Aug 17 16:14:09 fugu postfix/qmgr[1819]: 3AB2728079D: from=<eileen@x.x>, size=60792, nrcpt=1 (queue active)
Aug 17 16:14:14 fugu postfix/smtp[17372]: 3AB2728079D: to=<eileen@fuzion.x.x>, relay=ASPMX.L.google.com[2404:6800:4008:c07::1b]:25, delay=4.8, delays=0.36/0/2.1/2.3, dsn=2.0.0, status=
sent (250 2.0.0 OK 1471407253 14si9210414ioe.126 - gsmtp)
Aug 17 16:14:14 fugu postfix/qmgr[1819]: 3AB2728079D: removed

**Comment by litespeedmarc** [comment]
At Jefferson coding sprint.  @kcristiano thinks he might be able to give this a testing whirl.  Mentioning him, so he can get a moniker to the pull request.

**Comment by kcristiano** [comment]
Comments in JIRA https://issues.civicrm.org/jira/browse/CRM-17754.  

@eileenmcnaughton  This patch works and would be OK to merge

**Comment by eileenmcnaughton** [comment]
Thanks @kcristiano glad to see this resolved!

**Comment by seamuslee001** [comment]
Thanks @kcristiano for persisting with this as well

**Pull request merged**
