### PR TITLE
Add ability to edit email custom data to Email inline edit

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Add ability to edit email custom data to Email inline edit

(includes the change in https://github.com/civicrm/civicrm-core/pull/30840)

Before
----------------------------------------
Some time back we added support for Custom Data on 'any' entity. Since then we have added UI editing support for some entities (MembershipType, FinancialAccount, FinancialTransaction, RelationshipType etc) and have a general principle that ideally this would be standard. 

On the location entities we have support for Custom Fields on Addresses, only.

After
----------------------------------------
Support for Custom fields in the edit pane (not view as yet) of the Inline Email trait - code written ready to be generalised to phone (& other location entities if I get keen) and to other forms with Email on it.

image

Technical Details
----------------------------------------
The new functionality requires Smarty5. It uses Apiv4 and the approach is not possible with Smarty2. It likely works with Smarty3 & 4 but given that this will take some time to phase in and pre-Smarty5 is being phased out at the same time it feels like the easiest / best approach is to limit ourselves to 1 smarty version.

Comments
----------------------------------------
To easily create the custom fields grab 
`git clone  https://github.com/eileenmcnaughton/testdata.git`

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
thanks @mattwire

**Comment by demeritcowboy** [comment]
I don't know if it was intentional but this prevents the inline email block from working at all in smarty2 even if you don't have custom fields on the email. https://lab.civicrm.org/dev/core/-/issues/5507

**Comment by seamuslee001** [comment]
@eileenmcnaughton @demeritcowboy just flagging that this causes a fun thing, If you are editing an email address and you check the Bulk Mailings box but then you uncheck it you get a javascript alert with boo in it as per https://github.com/civicrm/civicrm-core/commit/8189551c25e543e3a69f2ee19dbdd31edc68f1be#diff-f489283d43525602a5a90b8092c5189dd5d8b0392a30e789b4f99cd86eae1d69R103 This was found by @andrew-cormick-dockery and @johntwyman

**Comment by eileenmcnaughton** [comment]
@seamuslee001 it only does that cos Halloween is coming up

**Pull request merged**
