### PR TITLE
addField in CRM_Contact_Form_Relationship, add Date support to AddField

### PR DESCRIPTION
**Pull request by mallezie**
Change CRM_Contact_Form_Relationship to use addField. 
Add necessary changes to schem
Add Date support to addField method. 
https://issues.civicrm.org/jira/browse/CRM-16178

### CODE REVIEW

**Comment by mallezie** [comment]
@colemanw eileen asked me to ping you, to check these PR's ;-)

**Comment by colemanw** [comment]
Sorry for the delay, I'm on vacation till the 26th and will take a look asap when I get back.
@eileenmcnaughton feel free to merge things in the meantime if they look good to you.

**Comment by eileenmcnaughton** [comment]
Coleman - overall it looks good & you have obviously agreed in principle. I guess that's good enough. It did pass the tests.

**Comment by mallezie** [comment]
Thanks for the merge. @colemanw Enjoy your vacation!

**Pull request merged**
