### PR TITLE
PHP - Remove unneeded polyfills for php 7.3 & 7.4

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Followup to #28583 this removes code only needed by older versions of php.

Technical Details
----------------------------------------
Core [now requires php 7.4](https://lab.civicrm.org/dev/core/-/issues/4812) so polyfills are not necessary.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I'm torn on this one tbh - although we don't support pre 7.4 any more it kinda feels like we could leave this a bit longer just to help people transition. Unlike a lot of other aspects of supporting earlier PHP versions including the polyfills has no real cost to us

**Comment by colemanw** [comment]
Well, if it is helpful then I agree we could leave them in.
I'm just not sure *how* it's helpful though. Won't Civi crash on unsupported php versions either way?

**Comment by totten** [comment]
It'll crash as soon as we introduce either (a) third-party package updates that need php74 or (b) starting using [PHP 7.4 syntax](https://www.php.net/manual/en/migration74.new-features.php).

**Comment by eileenmcnaughton** [comment]
Yeah - I can see those new syntaxes being appealing -

**Comment by totten** [comment]
> although we don't support pre 7.4 any more it kinda feels like we could leave this a bit longer just to help people transition.

If we do a soft/fake switch, then I think we should keep the test-infra on php73. It's not fair to expect contributors to abide by soft-php73-support if all the tooling points to php74. I guess you would call it a "documentation-only"/"documentation-first" change.

I'm OK with either "docs-first-cycle" or a "clean break", but (*given the steps already taken*) I'd probably vote for clean break to php74.

**Comment by colemanw** [comment]
> It's not fair to expect contributors to abide by soft-php73-support if all the tooling points to php74

I don't see any reason to go down that road. Devs are going to start writing 7.4-flavored code now (myself included), and that will quickly make the presence of these polyfills moot.

**Comment by eileenmcnaughton** [comment]
OK - let's merge. I would have happily left this in for a couple of releases but definitely want the tests switch over & don't want the fact it's 'not broken yet' on 7.3 to delay the tests

**Pull request merged**
