### PR TITLE
dev/core#2122 - Revert event timezones 5.47 version

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
Backport of https://github.com/civicrm/civicrm-core/pull/22930 and https://github.com/civicrm/civicrm-core/pull/22940.

### CODE REVIEW

**Comment by pradpnayak** [comment]
Is there any chance this will get merged into 5.47 next release?

**Comment by Barijohn** [comment]
This would be usefu,l as I have some clients with 100s of events they are going to have to review. If we can get this merged it would make everyones life much easier.

**Comment by agh1** [comment]
[Cross-referencing from Mattermost](https://chat.civicrm.org/civicrm/pl/5rdpjws3afbr8ed864txmrskae), could we please avoid merging this until after the security release is cut? I think it will simplify messaging to keep things separate and avoid introducing mayhem into a security release.

If people are on 5.47.x, they're no worse off if the security release lacks the revert.  If they're on an earlier version, we can/should point out that 5.46.3 is preferred because of this timezone problem.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy FYI - we chatted about this in Core team catchup today & @totten is going to put some effort into this next week - so dont feel you have to keep fighting this battle right now

**Comment by demeritcowboy** [comment]
If one of the issues is how big this PR is, I'll maybe point out that as of right now, it's relatively easy to see that this reverts at least the relevant code files to the same as 5.46. If you run the below script from inside a checkout of this PR, at least half of the output is just docblock changes, and the only diffs that look like they might be related are actually completely separate things:
* https://github.com/civicrm/civicrm-core/commit/3027c167a4ddce33cfb6c9ce6fa4629b7fa9048f
* https://github.com/civicrm/civicrm-core/commit/186e835db0d5a2df20a3b84c1ae10d3679669c20

```sh
#!/bin/sh
# replace with right path
pathto546=/path/to/civi546
diff "${pathto546}/CRM/Contribute/BAO/Contribution.php" CRM/Contribute/BAO/Contribution.php
diff "${pathto546}/CRM/Core/CodeGen/GenerateData.php" CRM/Core/CodeGen/GenerateData.php
diff "${pathto546}/CRM/Core/SelectValues.php" CRM/Core/SelectValues.php
diff "${pathto546}/CRM/Event/BAO/Event.php" CRM/Event/BAO/Event.php
diff "${pathto546}/CRM/Event/BAO/Participant.php" CRM/Event/BAO/Participant.php
diff "${pathto546}/CRM/Event/DAO/Event.php" CRM/Event/DAO/Event.php
diff "${pathto546}/CRM/Event/Form/ManageEvent/EventInfo.php" CRM/Event/Form/ManageEvent/EventInfo.php
diff "${pathto546}/CRM/Event/Form/ManageEvent/Registration.php" CRM/Event/Form/ManageEvent/Registration.php
diff "${pathto546}/CRM/Event/Form/Participant.php" CRM/Event/Form/Participant.php
diff "${pathto546}/CRM/Event/Form/ParticipantFeeSelection.php" CRM/Event/Form/ParticipantFeeSelection.php
diff "${pathto546}/CRM/Event/Form/Registration.php" CRM/Event/Form/Registration.php
diff "${pathto546}/CRM/Event/Form/SelfSvcTransfer.php" CRM/Event/Form/SelfSvcTransfer.php
diff "${pathto546}/CRM/Event/ICalendar.php" CRM/Event/ICalendar.php
diff "${pathto546}/CRM/Event/Page/EventInfo.php" CRM/Event/Page/EventInfo.php
diff "${pathto546}/CRM/Event/Page/List.php" CRM/Event/Page/List.php
diff "${pathto546}/CRM/Event/Page/ManageEvent.php" CRM/Event/Page/ManageEvent.php
diff "${pathto546}/CRM/Event/Tokens.php" CRM/Event/Tokens.php
diff "${pathto546}/CRM/Financial/BAO/Payment.php" CRM/Financial/BAO/Payment.php
diff "${pathto546}/CRM/Utils/Check/Component/Env.php" CRM/Utils/Check/Component/Env.php
diff "${pathto546}/CRM/Utils/Date.php" CRM/Utils/Date.php
diff "${pathto546}/Civi/Api4/Service/Spec/Provider/EventCreationSpecProvider.php" Civi/Api4/Service/Spec/Provider/EventCreationSpecProvider.php
diff "${pathto546}/api/v3/Event.php" api/v3/Event.php
diff "${pathto546}/templates/CRM/Core/Calendar/ICal.tpl" templates/CRM/Core/Calendar/ICal.tpl
diff "${pathto546}/templates/CRM/Event/Form/ManageEvent/EventInfo.tpl" templates/CRM/Event/Form/ManageEvent/EventInfo.tpl
diff "${pathto546}/templates/CRM/Event/Form/ManageEvent/Registration.tpl" templates/CRM/Event/Form/ManageEvent/Registration.tpl
diff "${pathto546}/templates/CRM/Event/Form/Registration/EventInfoBlock.tpl" templates/CRM/Event/Form/Registration/EventInfoBlock.tpl
diff "${pathto546}/templates/CRM/Event/Page/EventInfo.tpl" templates/CRM/Event/Page/EventInfo.tpl
diff "${pathto546}/templates/CRM/Event/Page/List.tpl" templates/CRM/Event/Page/List.tpl
diff "${pathto546}/templates/CRM/Event/Page/ManageEvent.tpl" templates/CRM/Event/Page/ManageEvent.tpl
diff "${pathto546}/xml/schema/Event/Event.xml" xml/schema/Event/Event.xml
diff "${pathto546}/xml/templates/message_templates/event_offline_receipt_html.tpl" xml/templates/message_templates/event_offline_receipt_html.tpl
diff "${pathto546}/xml/templates/message_templates/event_offline_receipt_text.tpl" xml/templates/message_templates/event_offline_receipt_text.tpl
diff "${pathto546}/xml/templates/message_templates/event_online_receipt_html.tpl" xml/templates/message_templates/event_online_receipt_html.tpl
diff "${pathto546}/xml/templates/message_templates/event_online_receipt_text.tpl" xml/templates/message_templates/event_online_receipt_text.tpl
diff "${pathto546}/xml/templates/message_templates/participant_cancelled_html.tpl" xml/templates/message_templates/participant_cancelled_html.tpl
diff "${pathto546}/xml/templates/message_templates/participant_cancelled_text.tpl" xml/templates/message_templates/participant_cancelled_text.tpl
diff "${pathto546}/xml/templates/message_templates/participant_confirm_html.tpl" xml/templates/message_templates/participant_confirm_html.tpl
diff "${pathto546}/xml/templates/message_templates/participant_confirm_text.tpl" xml/templates/message_templates/participant_confirm_text.tpl
diff "${pathto546}/xml/templates/message_templates/participant_expired_html.tpl" xml/templates/message_templates/participant_expired_html.tpl
diff "${pathto546}/xml/templates/message_templates/participant_expired_text.tpl" xml/templates/message_templates/participant_expired_text.tpl
diff "${pathto546}/xml/templates/message_templates/participant_transferred_html.tpl" xml/templates/message_templates/participant_transferred_html.tpl
diff "${pathto546}/xml/templates/message_templates/participant_transferred_text.tpl" xml/templates/message_templates/participant_transferred_text.tpl
diff "${pathto546}/xml/templates/message_templates/payment_or_refund_notification_html.tpl" xml/templates/message_templates/payment_or_refund_notification_html.tpl
diff "${pathto546}/xml/templates/message_templates/payment_or_refund_notification_text.tpl" xml/templates/message_templates/payment_or_refund_notification_text.tpl
```

**Comment by agileware-justin** [comment]
@demeritcowboy it would be ideal if this PR was included in 5.47.3 and then any other PRs having database changes scheduled for 5.47.3 were deferred to 5.47.4 - that way, it would make it easier to upgrade sites which have been fixed prior to 5.47.3

**Comment by agh1** [comment]
Just to leave a vote of confidence: we have a client that got upgraded to 5.47.0 and has thousands of events, so they quickly noticed the problems.  They started fixing some events manually, and then some got either double-fixed or fixed-then-unfixed, so the event situation got to be a mess.  In the course of applying security updates last week, I decided to load 5.47.2 plus this patch and pretend the whole thing was 5.47.2 (since that's how the upgrade steps were set in this PR at that time).  After the database upgrade, I took the `civicrm_event` values from a pre-5.47 backup and overwrote the date values in the table.

Because this was a heavy-handed cleanup where we didn't trust that the event times weren't modified manually, I can't speak to the upgrade process.  However, the site has been running without complaint for nearly a week like this.

**Comment by demeritcowboy** [comment]
Thanks @agh1.

This doesn't purport to fix _every_ event even if nobody touches them. To do that it would need info that isn't really available. Some events are going to still be off even after the revert.

You may want to check their message templates since there was a discrepancy between the 5.48 and 5.47 versions of this and last week the 5.47 version wouldn't have updated the templates: https://github.com/civicrm/civicrm-core/pull/22946/files#diff-99abed8aacb3a268c5d519bafc259dbc5dce4af550df346495b04f9d504d3fabR340

**Comment by demeritcowboy** [comment]
> After the database upgrade, I took the civicrm_event values from a pre-5.47 backup and overwrote the date values in the table

Yes I had mused about a similar procedure at https://github.com/civicrm/civicrm-core/pull/22940#issuecomment-1068525150. So many people may find using their backups of the civicrm_event table as the best way to recover.

**Comment by demeritcowboy** [comment]
@totten I think we want to remove this in this version: https://github.com/civicrm/civicrm-core/pull/22946/files#diff-78291209ee1dcf9c9ccd5e8d6cb8a9ee38408a81cad6cd50009150399d3bbd81R38-R45

**Comment by demeritcowboy** [comment]
That link doesn't seem to link properly. I'm referring to the upgrade warning about avoiding using 5.47: https://github.com/civicrm/civicrm-core/blob/6c70a7c1973e9925044688bbe1c87145819b9304/CRM/Upgrade/Incremental/php/FiveFortySeven.php#L36-L43

**Comment by demeritcowboy** [comment]
Also this seems to have crept back in and shouldn't be there: https://github.com/civicrm/civicrm-core/blob/8e30e889f4d3bd708cd98549297f7e40103998ae/CRM/Upgrade/Incremental/php/FiveFortySeven.php#L102-L105

**Comment by totten** [comment]
> Also this seems to have crept back in and shouldn't be there: 

Oops, yup, snuck in while re-porting between 5.47/5.48. Fixed.

**Comment by totten** [comment]
Merging based on MM discussion.

**Pull request merged**
