### PR TITLE
Convert confirm email text to html

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Confirm email text is text but demand for it to be html

Before
----------------------------------------
Field is text

After
----------------------------------------
Field is html

Technical Details
----------------------------------------
In the template is is already wrapped in `<p>` tags & that seems to not be messing stuff up too much where sites already have html so maybe we can just leave the db as is?

@seamuslee001 in my db it is not html-encoded when saved by just putting the text in there? 

image

The only place we output the field on the template layer is via tokens and in the token layer it should be passed through htmlentities - https://github.com/civicrm/civicrm-core/blob/fda883144a350d2dabc8ad0a51a4d04d340680fc/Civi/Token/TokenRow.php#L284-L290

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
hmm ok 1. we should make sure we purify the default value before passing it ot the wysiwyg to avoid xss I think

**Comment by eileenmcnaughton** [comment]
@seamuslee001 ckeditor kinda swallows the script on that field for me - but I think it could be an issue with a different wysiwig. The issue is in `setDefaults()` so I put a fix in there but I didn't see any reason to limit to this field as I can't think when purifying values set here wouldn't be a good thing to do

**Comment by agileware-justin** [comment]
Thanks! 👍🏻

**Comment by seamuslee001** [comment]
This seems fine to me

**Comment by eileenmcnaughton** [comment]
thanks @seamuslee001

**Comment by agileware-justin** [comment]
Causes regression, https://lab.civicrm.org/dev/core/-/issues/5180

**Comment by agileware-justin** [comment]
Regression fixed by https://github.com/civicrm/civicrm-core/pull/30081

**Pull request merged**
