### PR TITLE
Examples

### PR DESCRIPTION
**Pull request by eileenmcnaughton**

### CODE REVIEW

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
@eileenmcnaughton the test failures look like they are related to the new examples for contribution and payment processor apis.

**Comment by eileenmcnaughton** [comment]
@totten  is it possible to quash phpcs on this one - this test fixes a large number of files to comply & has a small number of regressions. 

There is a second issue whereby cleanup on tests has become yucky over time - leading to test failures when I refreshed - not new tests per @colemanw s comment but tests where ids are no longer correct due to poor clean up. I hacked past 1 & can do past the other but it doesn't fail locally

**Comment by eileenmcnaughton** [comment]
NB - the revealed failure 'may' be a real problem as the change seems to be around fee_amount & net_amount - https://github.com/civicrm/civicrm-core/commit/c689c1354d9c1338de5895b144e852a053825949#diff-6b5a5a671ebd3581b77ce6071ee2fd76 but I'm going to try to hack past rather than identify & fix

**Comment by totten** [comment]
test this please

**Comment by totten** [comment]
I agree that we shouldn't be blocking PRs because of style defects in /examples/ (at least, not until we get /examples/ up to the baseline).

civilint is supposed to ignore the auto-generated files in the /DAO/ or /examples/ folders. There was a bug (fixed in https://github.com/civicrm/civicrm-buildkit/commit/8b87172ac54e66c44327087afa2f8f86297ddfca ). I checked the console for the new test run, and it appears to have accepted the files.

**Comment by eileenmcnaughton** [comment]
@totten any idea - it fails ... erm but not test show as failing when I click through. ContributionTest passes locally.

The change to the example relates to fee_amoung & total_amount - could be a real error but not new to this PR if it is

**Pull request merged**
