### PR TITLE
CRM-18508: Display State/Province in event address in registration emails

### PR DESCRIPTION
**Pull request by twomice**
I'm a little unfamiliar with changes to system message templates. This just changes the template files under xml/templates/. Where would I create a test for this change? Do I need to change anything under sql/, CRM/Upgrade/, or elsewhere?

---
- [CRM-18508: State\/Province not shown in Event Confirmation Emails](https://issues.civicrm.org/jira/browse/CRM-18508)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This is tricky to test - we have loads of tests on the contribution side at the form level so it would be easy to add there - but on the test side we don't have any tests to test submitting the form :-(

Writing a test against CRM_Core_BAO_MessageTemplate::send  would be really cool - there are no existing tests though so it would take figuring out how to set that up

**Comment by yashodha** [comment]
You also need to handle upgrade for the same.
you need to do following steps:
1. mkdir -p CRM/Upgrade/4.7.x.msg_template/message_templates
2. cp xml/templates/message_templates/event_offline_receipt_html.tpl CRM/Upgrade/4.7.x.msg_template/message_templates/
_for each of the changed templates_
3. cp CRM/Upgrade/4.7.alpha1.msg_template/civicrm_msg_template.tpl CRM/Upgrade/4.7.x.msg_template/civicrm_msg_template.tpl
4. Update version in CRM/Upgrade/4.7.x.msg_template/civicrm_msg_template.tpl
5. Include CRM/Upgrade/4.7.x.msg_template/civicrm_msg_template.tpl in CRM/Upgrade/Incremental/sql/4.7.x.mysql.tpl

You can also check out PR :#6531

**Comment by twomice** [comment]
OK, hmm. Need a few days to make time for this, esp. the testing. Will target by next Wednesday.

**Comment by yashodha** [comment]
@twomice Now that 4.7.9 has been released, it would be great to have upgrade in place for 4.7.10.

**Comment by yashodha** [comment]
tested this, country and state province which were missing are now showing. Upgrade PR will follow.

**Pull request merged**
