### PR TITLE
CRM-17494 - Fixed participant role filtering for non numeric participant role values

### PR DESCRIPTION
**Pull request by mollux**
[CRM-17494](https://issues.civicrm.org/jira/browse/CRM-17494)

### CODE REVIEW

**Comment by kurund** [comment]
jenkins, add to whitelist

**Comment by colemanw** [comment]
need to perform escaping to prevent sql-injection

**Comment by mollux** [comment]
Ow, indeed, I will adapt patch

**Comment by mollux** [comment]
I think the test failure is unrelated to the changes.

**Comment by colemanw** [comment]
jenkins, retest this please

**Pull request merged**
