### PR TITLE
[REF] improve function signature on updateFinancialAccountsOnContributionStatusChange

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Removes a parameter than can only have one value & a large IF chunk that is affected by it

Before
----------------------------------------
Less readable

After
----------------------------------------
More readable

Technical Details
----------------------------------------
This private function is only called from one place. The conditional before it is called is
if ($context == 'changedStatus') {

Ergo $context is ALWAYS changedStatus when this function is called.

As a result I have removed context from the function signature & the if that checks it is
equal to 'changedStatus'

Comments
----------------------------------------
@monishdeb @mattwire @seamuslee001 if one of you can look - this requires a quick grep but it's a small change that looks like a big change due to removal of an if / confusion

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by demeritcowboy** [comment]
Grep confirms it's only used in the one spot.

And that $context is only used in updateFinancialAccountsOnContributionStatusChange() in one spot.

And that $context is always statusChanged (technically if $context is TRUE it would also trigger the `==`, but besides being silly it would trigger both spots the same so doesn't change anything).

Also agree that the indentation/whitespace makes it look like more than it is and there's only 5 lines really changed.

**Comment by seamuslee001** [comment]
Merging as per @demeritcowboy 's review

**Comment by eileenmcnaughton** [comment]
Thanks @demeritcowboy @seamuslee001 - this makes further readability improvements easier

**Pull request merged**
