### PR TITLE
dev/core#908 Fix issue when click back arrow after creating a case to…

### PR DESCRIPTION
**Pull request by seamuslee001**
… create a second new case

Overview
----------------------------------------
This fixes a perticularly perculiur situation, In that someone has just created a case for a contact but now want to create a 2nd case for them so they click the back button to go back to the create case screen but the preProcess is not run a 2nd time so the necessary fields are not added to the form class

Before
----------------------------------------
Error shown as per lab ticket 

After
----------------------------------------
No error and 2nd case created correctly

ping @jusfreeman @eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@demeritcowboy any chance you can look at this?

**Comment by jusfreeman** [comment]
Back link to the Gitlab,  https://lab.civicrm.org/dev/core/issues/908

**Comment by jusfreeman** [comment]
@seamuslee001 sorry to report that this PR doesn't fix the bug. When you click Back arrow after creating a new Case and change some details then click Save again the same error is shown. See https://video.drift.com/v/ab4Kdb7dV8o

**Comment by seamuslee001** [comment]
@jusfreeman your testing that on dmaster.demo.civicrm.org which will only use the code in the master not the PR. To get the PR test site you need to click on the details of the test build and then click on ConsoleLog and then click on Full console log or similar

**Comment by demeritcowboy** [comment]
I can also take a look.

**Comment by demeritcowboy** [comment]
I still get the same error on the test site here but I have a question. I'll post on the lab ticket.

**Comment by seamuslee001** [comment]
ok so the issue still stands in standalone mode but works fine when your doing it via the cases tab on contact summary screen

**Comment by jusfreeman** [comment]
@seamuslee001 I tested on a different CiviCRM site not dmaster with the PR applied. The video is just from the original bug report - same steps, same problem.

**Comment by mattwire** [comment]
@jusfreeman @seamuslee001 @demeritcowboy Where did we get to with this - it fixes the issue in one place but not another?

**Comment by demeritcowboy** [comment]
@mattwire There's more discussion in the lab ticket but there's two issues. One is a fatal error, which happens with things other than case, like activities, but there you get a nicer bounce, so it's inconsistent, and the other is the request to have save+back+save function a little more like "save and new copy". I see the latter as being a separate feature and am not sure of a good way it could be implemented to be consistent with other entities.

**Comment by jusfreeman** [comment]
@mattwire this PR didn't fix the problem when I last tested it. See comments on https://lab.civicrm.org/dev/core/issues/908#note_21402

**Comment by jaapjansma** [comment]
Betty and I are reviewing PR's and we came across this one. We reacted in the issue on lab. Basically we could not reproduce it anymore on 5.23 and dmaster (5.24alpha1). So we think this PR could be close as it seems that the bug has been fixed in the mean time.

**Comment by eileenmcnaughton** [comment]
Closing per ^^

**Pull request closed without merging**
