### PR TITLE
WorkflowMessage - Enable strict parsing of annotations

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

Not sure it's a good or bad idea. Spot-checked some local tests, and they seemed OK. Let's see what Jenkins thinks.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@totten jenkins is positively cheerful - but does it matter that @braders patch isn't merged yet in terms of this one?

**Comment by totten** [comment]
@eileenmcnaughton The two patches might interact. (*Not at a `git` level -- but functionally.*)  Since I think the other is probably more important (*this one was on a lark*), I'd suggest merging #25790 first and then re-run the test here.

**Comment by eileenmcnaughton** [comment]
@totten ok - let's merge the other - @colemanw has been ignoring it for 3 days - I doubt 2 more will matter + it would fail tests if it was a problem IMHO.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@totten it still passes

**Comment by totten** [comment]
@eileenmcnaughton  Wow, ok. I guess we can do this then.

* Flipping this to "strict" is better from a core dev POV -- i.e. more likely to prevent bugs.
* Nut, generally, "strictness" toggles should be available to downstream -- they represent a pressure-relief-valve for someone mixing versions of core/extensions in random ways.
* It's kind of hard to care about as a hypothetical.

IMHO, the stricter policy is better than the looser policy -- but if anyone ever gets bitten by it, then it's discussion-welcome/patch-welcome to improve "strictness" toggles generally.

**Comment by eileenmcnaughton** [comment]
OK - lets' merge this - I think stricter is better & we are better not to tie ourself in knots over what might be handy for extension writers - esp on functionality that probably isn't much in use in the wild

**Pull request merged**
