### PR TITLE
Remove old dropped items from the schema xml

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Removes unused fields and indexes which were dropped prior to 4.4.7 which is currently the min upgradable version.
No reason to keep them around any longer.

Before
----------------------------------------
Unused cruft in the xml.

After
----------------------------------------
Gone.

Technical Details
----------------------------------------
Items in the schema xml with a `<drop>` tag are ignored. You can confirm that this PR has no effect on the generated DAO files by running GenCode.

Comments
----------------------------------------
Out of caution, I only removed the ones that were completely obsolete (older than the min upgradable version).
But honestly, I don't think any of them serve a purpose.
Maybe originally there was some sort of plan to give the `<drop>` tag additional functionality like auto-removing items during upgrade, but that never happened. So from what I can tell, we should just delete all the dropped stuff from the xml as there's no good reason to keep it around.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
I think if you were doing incremental upgrades through every version with a git/dev build with a rerun of gencode each time then if there was an upgrade script in the middle somewhere that touches the field it would fail since it never would have added it in this rewritten historical timeline. So for more recent ones maybe an issue.

**Comment by colemanw** [comment]
> I think if you were doing incremental upgrades through every version with a git/dev build with a rerun of gencode each time then if there was an upgrade script in the middle somewhere that touches the field it would fail since it never would have added it in this rewritten historical timeline. So for more recent ones maybe an issue.

I'm skeptical about the feasibility of that. The trouble with `<drop>` tags in our schema is that they capture one piece of the history, but not enough to actually build a working database of a previous version.

E.g. if you checked out the code of v5.29 and tried to build a 4.6.0 database with it, it wouldn't work because there are many other types of schema changes (e.g the column type or default value of a column) that don't have any historical record in the xml.

**Comment by demeritcowboy** [comment]
Ok yeah I might have the order backwards - ignore the comment.

**Comment by yashodha** [comment]
@colemanw can we delete the whole file ActivityAssignment.xml and ActivityTarget.xml as we dropped these tables ages ago.

**Comment by eileenmcnaughton** [comment]
Despite the excruciating mind numbingness I managed to look through all of these and they all seem correct.

**Comment by eileenmcnaughton** [comment]
@yashodha yes - I won't miss those files if someone wants to remove them.....

**Pull request merged**
