### PR TITLE
Remove last references to `_contributeMode`

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Remove last references to `_contributeMode`

Before
----------------------------------------
`_contributeMode` still set or declared in a few places but never used

image

After
----------------------------------------
poof

Technical Details
----------------------------------------

Comments
----------------------------------------
@mattwire

### CODE REVIEW

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by mlutfy** [comment]
test backlog, still running

**Comment by eileenmcnaughton** [comment]
unrelated test fails

[Test Result](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/) (48 failures / +47)
[Civi\Authx\AllFlowsTest.testAnonymous](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testAnonymous/)
[Civi\Authx\AllFlowsTest.testStatelessGuardSiteKey](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatelessGuardSiteKey/)
[Civi\Authx\AllFlowsTest.testStatefulStatelessOverlap](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatefulStatelessOverlap/)
[Civi\Authx\AllFlowsTest.testIgnoredHeaderAuthorization](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testIgnoredHeaderAuthorization/)
[Civi\Authx\AllFlowsTest.testIgnoredHeaderAuthorization_anon](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testIgnoredHeaderAuthorization_anon/)
[Civi\Authx\AllFlowsTest.testMultipleStateless](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testMultipleStateless/)
[Civi\Authx\AllFlowsTest.testJwtMiddleware](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testJwtMiddleware/)
[Civi\Authx\AllFlowsTest.testStatelessContactOnly with data set #3](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatelessContactOnly_with_data_set__3/)
[Civi\Authx\AllFlowsTest.testStatelessContactOnly with data set #4](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatelessContactOnly_with_data_set__4/)
[Civi\Authx\AllFlowsTest.testStatelessContactOnly with data set #5](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatelessContactOnly_with_data_set__5/)
[Civi\Authx\AllFlowsTest.testStatelessContactOnly with data set #6](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatelessContactOnly_with_data_set__6/)
[Civi\Authx\AllFlowsTest.testStatelessContactOnly with data set #7](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatelessContactOnly_with_data_set__7/)
[Civi\Authx\AllFlowsTest.testStatelessContactOnly with data set #8](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatelessContactOnly_with_data_set__8/)
[Civi\Authx\AllFlowsTest.testStatelessUserContact with data set #0](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatelessUserContact_with_data_set__0/)
[Civi\Authx\AllFlowsTest.testStatelessUserContact with data set #1](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatelessUserContact_with_data_set__1/)
[Civi\Authx\AllFlowsTest.testStatelessUserContact with data set #2](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatelessUserContact_with_data_set__2/)
[Civi\Authx\AllFlowsTest.testStatelessUserContact with data set #3](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatelessUserContact_with_data_set__3/)
[Civi\Authx\AllFlowsTest.testStatelessUserContact with data set #4](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatelessUserContact_with_data_set__4/)
[Civi\Authx\AllFlowsTest.testStatelessUserContact with data set #5](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatelessUserContact_with_data_set__5/)
[Civi\Authx\AllFlowsTest.testStatelessUserContact with data set #6](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatelessUserContact_with_data_set__6/)
[Civi\Authx\AllFlowsTest.testStatelessUserContact with data set #7](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatelessUserContact_with_data_set__7/)
[Civi\Authx\AllFlowsTest.testStatelessUserContact with data set #8](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatelessUserContact_with_data_set__8/)
[Civi\Authx\AllFlowsTest.testInvalidJwt with data set #0](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testInvalidJwt_with_data_set__0/)
[Civi\Authx\AllFlowsTest.testInvalidJwt with data set #1](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testInvalidJwt_with_data_set__1/)
[Civi\Authx\AllFlowsTest.testInvalidJwt with data set #2](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testInvalidJwt_with_data_set__2/)
[Civi\Authx\AllFlowsTest.testExpiredJwt with data set #0](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testExpiredJwt_with_data_set__0/)
[Civi\Authx\AllFlowsTest.testExpiredJwt with data set #1](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testExpiredJwt_with_data_set__1/)
[Civi\Authx\AllFlowsTest.testExpiredJwt with data set #2](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testExpiredJwt_with_data_set__2/)
[Civi\Authx\AllFlowsTest.testStatefulLoginAllowed with data set #0](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatefulLoginAllowed_with_data_set__0/)
[Civi\Authx\AllFlowsTest.testStatefulLoginAllowed with data set #1](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatefulLoginAllowed_with_data_set__1/)
[Civi\Authx\AllFlowsTest.testStatefulLoginAllowed with data set #2](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatefulLoginAllowed_with_data_set__2/)
[Civi\Authx\AllFlowsTest.testStatefulLoginProhibited with data set #0](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatefulLoginProhibited_with_data_set__0/)
[Civi\Authx\AllFlowsTest.testStatefulLoginProhibited with data set #1](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatefulLoginProhibited_with_data_set__1/)
[Civi\Authx\AllFlowsTest.testStatefulLoginProhibited with data set #2](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatefulLoginProhibited_with_data_set__2/)
[Civi\Authx\AllFlowsTest.testStatefulAutoAllowed with data set #0](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatefulAutoAllowed_with_data_set__0/)
[Civi\Authx\AllFlowsTest.testStatefulAutoAllowed with data set #1](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatefulAutoAllowed_with_data_set__1/)
[Civi\Authx\AllFlowsTest.testStatefulAutoAllowed with data set #2](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatefulAutoAllowed_with_data_set__2/)
[Civi\Authx\AllFlowsTest.testStatefulAutoProhibited with data set #0](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatefulAutoProhibited_with_data_set__0/)
[Civi\Authx\AllFlowsTest.testStatefulAutoProhibited with data set #1](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatefulAutoProhibited_with_data_set__1/)
[Civi\Authx\AllFlowsTest.testStatefulAutoProhibited with data set #2](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatefulAutoProhibited_with_data_set__2/)
[api_v4_AfformRoutingTest.testChangingPermissions](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/api_v4_AfformRoutingTest/testChangingPermissions/)
[api_v4_AfformRoutingTest.testChangingPath](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/api_v4_AfformRoutingTest/testChangingPath/)
[MockPublicFormTest.testGetPage](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/MockPublicFormTest/testGetPage/)
[MockPublicFormTest.testPublicCreateAllowed](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/MockPublicFormTest/testPublicCreateAllowed/)
[MockPublicFormTest.testPublicEditDisallowed](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/MockPublicFormTest/testPublicEditDisallowed/)
[MockPublicFormTest.testAuthenticatedUrlToken_Plain](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/MockPublicFormTest/testAuthenticatedUrlToken_Plain/)
[MockPublicFormTest.testAuthenticatedUrlToken_Html](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/MockPublicFormTest/testAuthenticatedUrlToken_Html/)
[MockPublicFormTest.testAuthenticatedLinkToken_Html](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6351/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/MockPublicFormTest/testAuthenticatedLinkToken_Html/)

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
it passed!

**Comment by seamuslee001** [comment]
I'm just doing a grep in universe to see if this will impact anything

**Comment by seamuslee001** [comment]
After updating my copy of the universe and doing a grep this is what came up for me, Nothing jumps out as breaking based on this I don't think

```
seamus@civicrmdevelopment:~/buildkit/build/universe$ grep -r '_contributeMode' *
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Contribute/Form/Contribution.php:  public $_contributeMode = 'direct';
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Contribute/Form/AdditionalPayment.php:  public $_contributeMode = 'direct';
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Contribute/Form/AbstractEditPayment.php:  public $_contributeMode = 'direct';
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Contribute/Form/ContributionBase.php:  public $_contributeMode;
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Contribute/Form/ContributionBase.php:    $this->_contributeMode = $this->get('contributeMode');
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Contribute/Form/ContributionBase.php:    $this->assign('contributeMode', $this->_contributeMode);
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Contribute/Form/Contribution/Confirm.php:    if ($this->_contributeMode === 'notify' ||
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Contribute/Form/Contribution/Confirm.php:          if (((isset($this->_contributeMode)) || !empty($this->_params['is_pay_later'])
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Contribute/Form/Contribution/Confirm.php:        $form->_contributeMode = 'direct';
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Contribute/Form/Contribution/Confirm.php:        $form->_contributeMode = 'notify';
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Contribute/Form/Contribution/Confirm.php:          if ($form->_contributeMode == 'notify') {
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Member/Form/Membership.php:  public $_contributeMode = 'direct';
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration.php:    $this->_contributeMode = $this->get('contributeMode');
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration.php:    $this->assign('contributeMode', $this->_contributeMode);
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration.php:    if ($this->_contributeMode === 'direct' && empty($params['is_pay_later'])) {
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration.php:    if ($this->_contributeMode != 'checkout' ||
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration.php:      $this->_contributeMode != 'notify'
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Event/Form/Participant.php:  public $_contributeMode = 'direct';
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Event/Form/Participant.php:    if ($form->_contributeMode != 'notify' && empty($params['is_pay_later'])) {
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration/Confirm.php:    if ($this->_contributeMode !== 'express') {
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration/Confirm.php:          $this->_contributeMode == 'checkout' ||
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration/Confirm.php:          $this->_contributeMode == 'notify'
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration/Confirm.php:    if (($this->_contributeMode == 'checkout' ||
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration/Confirm.php:        $this->_contributeMode == 'notify'
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration/Confirm.php:    if ($form->_contributeMode != 'notify' && empty($params['is_pay_later'])) {
core/civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration/Confirm.php:    $form->_contributeMode = $params['contributeMode'];
core/civicrm-core/CRM/Contribute/Form/Contribution.php:  public $_contributeMode = 'direct';
core/civicrm-core/CRM/Contribute/Form/AdditionalPayment.php:  public $_contributeMode = 'direct';
core/civicrm-core/CRM/Contribute/Form/AbstractEditPayment.php:  public $_contributeMode = 'direct';
core/civicrm-core/CRM/Contribute/Form/ContributionBase.php:  public $_contributeMode;
core/civicrm-core/CRM/Contribute/Form/ContributionBase.php:    $this->_contributeMode = $this->get('contributeMode');
core/civicrm-core/CRM/Contribute/Form/Contribution/Confirm.php:        $form->_contributeMode = 'direct';
core/civicrm-core/CRM/Contribute/Form/Contribution/Confirm.php:        $form->_contributeMode = 'notify';
core/civicrm-core/CRM/Member/Form/Membership.php:  public $_contributeMode = 'direct';
core/civicrm-core/CRM/Event/Form/Registration.php:    $this->_contributeMode = $this->get('contributeMode');
core/civicrm-core/CRM/Event/Form/Participant.php:  public $_contributeMode = 'direct';
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Contribute/Form/Contribution.php:  public $_contributeMode = 'direct';
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Contribute/Form/AdditionalPayment.php:  public $_contributeMode = 'direct';
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Contribute/Form/AbstractEditPayment.php:  public $_contributeMode = 'direct';
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Contribute/Form/ContributionBase.php:  public $_contributeMode;
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Contribute/Form/ContributionBase.php:    $this->_contributeMode = $this->get('contributeMode');
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Contribute/Form/ContributionBase.php:    $this->assign('contributeMode', $this->_contributeMode);
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Contribute/Form/Contribution/Confirm.php:    if ($this->_contributeMode === 'notify' ||
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Contribute/Form/Contribution/Confirm.php:          if (((isset($this->_contributeMode)) || !empty($this->_params['is_pay_later'])
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Contribute/Form/Contribution/Confirm.php:        $form->_contributeMode = 'direct';
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Contribute/Form/Contribution/Confirm.php:        $form->_contributeMode = 'notify';
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Contribute/Form/Contribution/Confirm.php:          if ($form->_contributeMode == 'notify') {
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Member/Form/Membership.php:  public $_contributeMode = 'direct';
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration.php:    $this->_contributeMode = $this->get('contributeMode');
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration.php:    $this->assign('contributeMode', $this->_contributeMode);
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration.php:    if ($this->_contributeMode === 'direct' && empty($params['is_pay_later'])) {
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration.php:    if ($this->_contributeMode != 'checkout' ||
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration.php:      $this->_contributeMode != 'notify'
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Event/Form/Participant.php:  public $_contributeMode = 'direct';
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Event/Form/Participant.php:    if ($form->_contributeMode != 'notify' && empty($params['is_pay_later'])) {
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration/Confirm.php:    if ($this->_contributeMode !== 'express') {
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration/Confirm.php:          $this->_contributeMode == 'checkout' ||
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration/Confirm.php:          $this->_contributeMode == 'notify'
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration/Confirm.php:    if (($this->_contributeMode == 'checkout' ||
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration/Confirm.php:        $this->_contributeMode == 'notify'
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration/Confirm.php:    if ($form->_contributeMode != 'notify' && empty($params['is_pay_later'])) {
drupal-module/civicrm_drush/vendor/civicrm/civicrm-core/CRM/Event/Form/Registration/Confirm.php:    $form->_contributeMode = $params['contributeMode'];
ext/cloneeventregistration/CRM/Event/Form/Task/CloneEventRegistration.php:  public $_contributeMode = 'direct';
ext/uk.co.vedaconsulting.offlinemembershipwizard/CRM/Offlinemembershipwizard/Form/Wizard/Membership.php:  public $_contributeMode = 'direct';
ext/uk.co.vedaconsulting.offlinemembershipwizard/CRM/Offlinemembershipwizard/Form/Wizard/Confirm.php:      $this->_contributeMode = 'direct';
ext/uk.co.vedaconsulting.offlinemembershipwizard/CRM/Offlinemembershipwizard/Form/Wizard/Confirm.php:      if ($this->_contributeMode == 'direct' && $assignCCInfo) {
```

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I have been using scopes in phpstorm to make these easier - see

image


Not sure why I missed some of the ones you have -but yeah the non-core ones in your list are not affected

**Pull request merged**
