### PR TITLE
[REF] Make datepicker element and actions accessible if label is defined but associated directly like in report filter

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Make datepicker element and actions accessible if label is defined but associated directly like in report filter

Before
----------------------------------------
Empty label of Actions:
Screenshot 2024-07-17 at 10 17 01

Empty label of date filter:
Screenshot 2024-07-17 at 10 17 23

After
----------------------------------------
Fixed

Dependent on https://github.com/colemanw/select2/pull/6

### CODE REVIEW

**Comment by vingle** [comment]
test this please

**Comment by vingle** [comment]
Still giving errors, presumably as it waits for https://github.com/colemanw/select2/pull/6

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by monishdeb** [comment]
hey @vingle hope you are doing good! 

I have rechecked the patch with the [demo site](http://site-list.test-1.civicrm.org:8001/?filter=core-30693-*)  and it fixes the date filter a11y issue about not having label : 
event1


Can you please review the patch?

**Comment by vingle** [comment]
@monishdeb - that works for me - ready to merge.

**Comment by monishdeb** [comment]
Thank you @vingle

**Pull request merged**
