### PR TITLE
Convert AuthorizeNet to doPayment()

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Ref https://lab.civicrm.org/dev/financial/-/issues/135 Convert from deprecated doDirectPayment to doPayment

Before
----------------------------------------

After
----------------------------------------

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I've flagged this one has-test as I think the Authorize.net test cover would catch anything this affected. Change makes sense & we are still returning $params so the issue we hit before (where the returned is 'used' for values other than the expected ones) won't come into play

**Comment by mattwire** [comment]
Thanks @eileenmcnaughton I've gone for the really simple, play it safe to get us onto doPayment() and "complete" https://lab.civicrm.org/dev/financial/-/issues/135.
We can look at return params etc. as a follow-on. It also gets rid of an `is_array()` which causes problems when doPayment() returns a propertyBag (though we should be returning an array not a propertyBag anyway).

**Comment by eileenmcnaughton** [comment]
@mattwire yeah I agree with playing it safe! I think there is quite a bit of work to do to be sure that returning less is safe even though in theory it would be good to do so - I don't see the removed is_array in here?

**Comment by mattwire** [comment]
In the parent doPayment() which is no longer called: https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/Payment.php#L1389

**Comment by eileenmcnaughton** [comment]
@mattwire oh right - but that is what is returned - we expect payment processors to continue to return an array - which is what you said about - so that is at best neutral

**Pull request merged**
