### PR TITLE
[REF] CustomGroup - cleanup handling of serialized fields in old function

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
More cleanup toward getting sanity in our custom field handling.
Use new isSeralized method rather than looking at html_type to figure out how to handle the data.

Before
----------------------------------------
Old function old.

After
----------------------------------------
Old function updated.

Comments
----------------------------------------
The function didn't appear to be correctly handling Multi-Select Country or Multi-Select State/Prov fields so this should also fix that.

### CODE REVIEW

**Comment by colemanw** [comment]
retest this please

**Comment by pradpnayak** [comment]
Did a quick test for all custom field type

1. On Contact summary page the custom fields are populated correctly on view and edit(standalone and inline) form.
2. In profile create mode the data is saved correctly against the contact.
3. in profile view mode data is populated for the contact
4. In profile edit mode the data is populated and saved correctly against the contact.
5. Advance Search works fine and returns result.

But incase when profile is added to event or contribution page, the data for multi option field like checkbox, multi-select, multi-country and multi-state is not populated. This is an issue with or without this patch.

The code looks good to merge since above issue can also be replicated without applying this patch.

**Comment by eileenmcnaughton** [comment]
Merging based on review by @pradpnayak

**Comment by colemanw** [comment]
@pradpnayak I found the solution to the bug you found, a problem in the function `CRM_Event_BAO_Participant::formatFieldsAndSetProfileDefaults`... git blame suggests that you wrote this function in 2016, so the bug has likely been around for a while.

https://github.com/civicrm/civicrm-core/pull/16981

**Comment by eileenmcnaughton** [comment]
Lol @pradpnayak git never forgets :-)

**Comment by pradpnayak** [comment]
@eileenmcnaughton, Yes it was quite long time and i guess the logic in CRM_Core_BAO_UFGroup::setProfileDefaults() was changed after my fix. I have similar issue fixed for GDPR extension in feb because it failed to setdefault after they upgraded Civi to 5.20.3

**Pull request merged**
