### PR TITLE
CRM-18772 46 backport

### PR DESCRIPTION
**Pull request by seamuslee001**
- [CRM-18772: Add in ability to check if field already exists in the database](https://issues.civicrm.org/jira/browse/CRM-18772)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
You are missing a method - but I'm happy to accept this for 4.6 as it is additional code only

**Comment by eileenmcnaughton** [comment]
(happy to ... when it passes)

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
I'm merging this because it really is just a copy of the 4.7 version of the function & the tests are included

**Pull request merged**
