### PR TITLE
dev/core#2593 Fully remove loadRelatedObjects from PaypalExpress

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
dev/core#2593 Fully remove loadRelatedObjects from PaypalExpress

Before
----------------------------------------
Lots of code in paypal express that was used to support the recur() function but is now no longer required

After
----------------------------------------
poof

Technical Details
----------------------------------------
@seamuslee001 this would be the last change touching the Paypal express side of things as https://lab.civicrm.org/dev/core/-/issues/2593 would now be fixed for paypal express

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton are there any unit tests on paypal express ipn?

**Comment by eileenmcnaughton** [comment]
2 in the PaypalProIPN class

image

**Comment by eileenmcnaughton** [comment]
Actually 4  - these 2 too 
image

**Comment by seamuslee001** [comment]
That gives me confidence this is fine merging

**Pull request merged**
