### PR TITLE
CiviCRM, removing an extension from the file system before it is disabled and uninstalled causes infinite session status error messages to be shown to all CiviCRM admins, which cannot be dismissed.

### PR DESCRIPTION
**Pull request by agileware-justin**
Overview
----------------------------------------
CiviCRM, removing an extension from the file system before it is disabled and uninstalled causes infinite session status error messages to be shown to all CiviCRM admins, which cannot be dismissed.

Before
----------------------------------------
Remove an extension from the file system before it is disabled and uninstalled. The following screenshots demonstrates what a CiviCRM admin user will experience, where-ever they go in CiviCRM. Clicking the **Dismiss (X)** button on the notification does not stop the notification reappearing. It will just pop-up again on the next screen.

Screenshot_20211002_104557

Screenshot_20211002_104633

Screenshot_20211002_104700

Screenshot_20211002_104727

Screenshot_20211002_104836

After
----------------------------------------
Remove an extension from the file system before it is disabled and uninstalled. The Extension Missing status is shown on the Extensions page. **No more** session status alerts on every single page, for each extension which cannot be dismissed. Sanity is restored.

Screenshot_20211002_105020

Technical Details
----------------------------------------

Comments
----------------------------------------
This type of overzealous alerting does not help in anyway. Happy to accept feedback on other ways to reduce alerts to one single, dismissable alert if this is not the correct approach.

Agileware Ref: CIVICRM-1859

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Stacktrace
CRM_Extension_Container_CollectionTest::testGetPath
Undefined variable: exc

/home/jenkins/bknix-dfl/build/core-21699-3s52/web/sites/all/modules/civicrm/tests/phpunit/CRM/Extension/Container/CollectionTest.php:42
/home/jenkins/bknix-dfl/build/core-21699-3s52/web/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:260
/home/jenkins/bknix-dfl/extern/phpunit8/phpunit8.phar:671

**Comment by mattwire** [comment]
@agileware-justin I've come across this and agree it's not great user experience! Can we make the error into a system check instead of removing it?

**Comment by yashodha** [comment]
@agileware-dev failing test looks related.

**Comment by demeritcowboy** [comment]
Going to close since seems to have stalled but feel free to reopen.

**Pull request closed without merging**
