### PR TITLE
Swap out button/submit inputs for button elements

### PR DESCRIPTION
**Pull request by agh1**
5.29 RC equivalent of #18087

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Timing-wise the 5.29 release is probably a good target for something that might affect markup in this way - it's right after a security release so people should hopefully be able to move to it at their own pace - especially if they are aware of this

**Comment by colemanw** [comment]
I'm not quite sure what's the rush to merge this into 5.29. I think it's a great improvement, but I do have one concern: a lot of javascript targets form buttons by name or by id. I think this could potentially break some scripts.

**Comment by eileenmcnaughton** [comment]
@colemanw I think it arose from my concern on the original PR that having just merged a bunch into 5.29 we would merge a bunch more into 5.30 -meaning anyone who updated styling for 5.29 would need to do so again for 5.30

**Comment by mattwire** [comment]
@colemanw I'd prefer to see this in 5.29 given the changes that have already gone in. It will almost certainly break (eg. Stripe) but it's going to be much easier to just have a single version to target, rather than have to do different things for 3 different versions (ie. 5.28 no button changes, 5.29 some button changes, 5.30 some more button changes). The same would apply to themes I think.

**Comment by colemanw** [comment]
A more cautious approach would be to revert the changes from 5.29 and only target 5.30. I'm not gonna block it from going into 5.29 if there is consensus but I do foresee some breakages throughout the universe of core+extensions that we probably haven't thought of yet.

**Comment by agh1** [comment]
Just to be clear I have no strong feelings about 5.29 vs. 5.30.  I will say that if this is to go into 5.29 we should do it this coming week or else we won't be giving folks enough chance to test it out.

I don't know who else has UI changes arriving in 5.29, but the two I wrote are the following:

- #18005 which makes the buttons look the same but (as we discovered later) makes the periphery of `<input>` buttons unclickable.  The only markup changes are removing a bunch of non-breaking space characters, eliminating the `crm-i-button` and `crm-icon-button` classes, and eliminating the theoretical support for sprite icons on buttons (which aren't actually used anywhere anymore).
- #18054 which only removes the gradient background file and the CSS to enable it on buttons and pop-up headers.

I'm fairly confident #18054 won't cause anyone problems unless their theme/extension is proactively going for a retro look by including the gradient somewhere else.

On its own, #18005 probably won't trip up anyone's customizations, but if we leave it in without this PR, some people will notice that they have to click on the actual button text for many buttons.  It would be simple enough to revert it and merge to `master`, but I think the real consideration is whether there are even more markup changes in 5.29 besides these.

**Comment by mattwire** [comment]
Ok, I've tested this and it doesn't break Stripe because I use `[type="submit"].validate` as the selector which works with both.

On my dev environment I have found one site-specific customisation (some javascript targetting contribution pages) that will need to change the selector from `input[type="submit"].validate` to the above. Also themes will need to be updated.

We need to make sure we communicate this change well - maybe an upgrader notice @agh1? The improvement with this and other related PRs is massive from a UI/theme perspective and will actually help with javascript customisations in the future because you can rely on a button being a button!

Based on all the above I'm going to merge this for 5.29.

**Comment by agh1** [comment]
@mattwire I think the communication will need to be early and often, and I'm concerned that the upgrader is too late and probably the wrong audience.  We've been fairly clear for years that template overrides are at-you-own-risk things.  While there's the chance that someone has custom JS, the much more serious thing is extensions and themes.

In those cases, end users will assume things are "taken care of", and developers won't necessarily realize they have an issue unless we tell them ahead of the release.

I think something clear should be put on blast--what do you think about this list of places?

- `@channel` on the extensions Mattermost
- `@channel` on the product maintenance Mattermost
- the dev listserv

I'm happy to write something up.

**Comment by mattwire** [comment]
@agh1 sounds great. I have no preference where/how we notify, only that it gets the best chance of getting to the right people - and given that most of my info comes directly from watching github I wouldn't know where that is :-) So I'm happy with your list.

**Comment by eileenmcnaughton** [comment]
@agh1  are you doing something about this - we'd better get some comms out!

**Comment by eileenmcnaughton** [comment]
@agh1 @mattwire @colemanw note I just merged a PR @colemanw put up to revert this. The issue wasn't the PR but just that we didn't really move quickly enough on the communication to keep it in the rc that is only 2 weeks from release.

**Comment by eileenmcnaughton** [comment]
ie per @agh1 " the communication will need to be early and often," - we missed 'early'

**Comment by eileenmcnaughton** [comment]
Note this PR is open again https://github.com/civicrm/civicrm-core/pull/18087 - ideally we can get a rebase

**Pull request merged**
