### PR TITLE
dev/core#3781 Downgrade Symfony Service Contracts to 2.2.0 to fix php fatal error i…

### PR DESCRIPTION
**Pull request by seamuslee001**
…n wordpress

Overview
----------------------------------------
This downgrades the version of symfony/service-contracts from 2.5.2 to 2.2.0 to fix a php fatal error when using wordpress and iThemes Security plguin

Before
----------------------------------------
Fatal error when using CiviCRM 5.52.0 and iThemes Security due to function declaration issue

After
----------------------------------------
No fatal error hopefully

Technical Details
----------------------------------------
The important change here is this https://github.com/symfony/service-contracts/compare/v2.2.0...v2.5.2#diff-9651ec0079b8028b20179b76c3b685511ca54d4e64f1948dfebaad06de0a303dR46 which is why a downgrade is needed

ping @demeritcowboy @kcristiano @eileenmcnaughton @totten

### CODE REVIEW

**Comment by kcristiano** [comment]
Thanks @seamuslee001 and @demeritcowboy 

`r-run`

- WP 6.0.1
- php 7.4
- Install civicrm 5.51.3
- add plugin using symfony ContainerInterface   I used https://wordpress.org/plugins/better-wp-security/
- Upgrade 5.52.0 from http://download.civicrm.org/latest/
- fatal error
- build 5.52.0 via distmaker with `--civi-ver 5.52 --patch https://github.com/civicrm/civicrm-core/pull/24170`
- remove full `civicrm` directort
- replace with new tarball
- works - no errors

This looks good to merge

**Comment by demeritcowboy** [comment]
Thanks @kcristiano

**Comment by totten** [comment]
OK, so the situation on this was:

* Civi v5.51 pulled in Symfony `~3.0 || ~4.4` (which was *de facto*  `v4.4` for D9 and `v3.4` for D7/D8/WP/BD/J)
* Civi v5.52 now pulls in Symfony v4.4 (for all environments)
* Pulling in Symfony 4.4 consistently means that it now also pulls in `symfony/*-contracts` (*which, like other common dependencies, is a potential point of conflict*)

In tightening the requirement to 4.4, the reassuring thing was that we already had 4.4 working (on D9). However, in theory (and in this bug-report), it could cause a flip-flop in compatibility - switching around the third-party plugins which do (or don't) have Symfony conflicts.

Anyway, I don't have a simple mitigation. I'm just flagging that there could be more/similar symptoms from this change, and it may be good to contemplate how to react if this turns into a game of whack-a-mole. Of course, we shouldn't do anything drastic based on one bug-report. I just want to encourage some contemplation. :)

(Aside: IMHO, it's been quite helpful that we have a [universe](https://docs.civicrm.org/dev/en/latest/tools/universe/) of extensions to analyze during development/review. Might be interesting for [fetch-universe](https://github.com/civicrm/civicrm-buildkit/blob/master/bin/fetch-universe) to pull in a larger set of CMS plugins...)

**Comment by seamuslee001** [comment]
@totten the other thing I would say is that the symfony/*-contacts versions don't seem to track as closely with the other versions, It was just that when we updated to 4.4 by its self we brought in an upgrade to the symfony/service-contracts version that didn't need to be brought in and even looking at the 6.1 version of dependency injection which is the only thing that requires the service-contacts it is ok with 2.2. https://github.com/symfony/dependency-injection/blob/6.1/composer.json#L22

**Comment by demeritcowboy** [comment]
FYI I needed to update the drupal 10 [snippet](https://lab.civicrm.org/-/snippets/84) to do the `|| ~` thing since the constraints in https://github.com/drupal/core-recommended/blob/10.0.x/composer.json require psr 2.0 and contracts 3.1

**Pull request merged**
