### PR TITLE
CRM-14538 - Partial payments for Memberships - Fix

### PR DESCRIPTION
**Pull request by rameshrr99**
partial payment works in the same principle of Event registration (partial payment)
-  Record partial payment for membership.
- only the contribution record will be assigned a status of Partially Paid until the balance owing is zero. This will allow staff to easily locate partially paid transaction.
- membership transaction is set to new/current - even if a single payment gets recorded

Imporvement needed
change selection functionality in membership veiw need to be developed 
sending out receipt when creating a offline membership need to be done

---

 * [CRM-14538: Partial payments for Memberships](https://issues.civicrm.org/jira/browse/CRM-14538)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins ok to test

**Comment by seamuslee001** [comment]
Jenkins ok to test

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by JoeMurray** [comment]
@rameshrr99 could you rebase and resubmit your PR so it doesn't change 681 files? 

I'd encourage you to close this PR and open a new clean one.

**Comment by petednz** [comment]
What happened to the work to allow this partial membership? I don't see more PRs by https://github.com/rameshrr99 - did this just fade away? asking due to https://civicrm.stackexchange.com/questions/27824/how-to-set-up-a-particularly-wonky-membership-type

**Pull request closed without merging**
