### PR TITLE
CRM-19223 - Tighter permissions for migration scripts

### PR DESCRIPTION
**Pull request by totten**
To test this, I created Drupal users with different permissions (e.g. `administer CiviCRM` versus no particular permissions) and checked the outputs before/after the patch. I specifically tested the change with:
- `migrate/export.php`
- `migrate/import.php`
- `migrate/exportJSON.php`
- `migrate/importJSON.php`

but did not specifically test:
- `migrate/move.php`
- `encryptDB.php`

---
- [CRM-19223](https://issues.civicrm.org/jira/browse/CRM-19223)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I think migrate/move.php is similar enough to the others not to be tested separately & I agree with disabling encryptDB

Giving this merge on pass based on the above testing @xurizaemon do we need to communicate back to the reporter.

We should also do this in 4.6

**Comment by xurizaemon** [comment]
Yes, let's make sure they know this comes out & they are credited for reporting.

**Comment by totten** [comment]
Jenkins reports a failure in `CRM_Contact_BAO_ContactType_ContactTest.testCRM19133` which feels a bit implausible (and which doesn't occur locally). Will ask for a retest.

**Comment by totten** [comment]
jenkins, test this please

**Comment by seamuslee001** [comment]
Look good agree re doing it against 4.6

**Comment by seamuslee001** [comment]
@eileenmcnaughton @totten @xurizaemon Is this good to merge?

**Pull request merged**
