### PR TITLE
REF Deprecate API3 _ipn_process_transaction()

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
The `_ipn_process_transaction()` function is a wrapper method called by both API3 `completetransaction` and `repeattransaction` before calling `completeOrder()`.  We would like to stop calling `completeOrder()` at all for `repeattransaction` and deprecate `completetransaction` in favour of calling API3 `Payment.create`.

`_ipn_process_transaction()` is basically just manipulating parameters before passing along to `completeOrder()`. This duplicates the contents of that function and puts it directly in the calling API. This allows us to deprecate `_ipn_process_transaction()` and work towards simplification of the `repeattransaction`/`completetransaction` API functions.

Before
----------------------------------------
Both API calls use `_ipn_process_transaction()`.

After
----------------------------------------
CiviCRM core does not use `_ipn_process_transaction()`.  @artfulrobot GoCardless is currently calling this function directly and when this PR is merged you'll see deprecation notices so that will need fixing at some point (perhaps copy the contents of the function initially?).

Technical Details
----------------------------------------
Explained above.

Comments
----------------------------------------

### CODE REVIEW

**Comment by mattwire** [comment]
Marked as "ok-without-test" because this is well tested code and we are not changing anything - just duplicating code.

**Comment by mattwire** [comment]
@artfulrobot per your comment in the code:

> Handle the case where the original Contribution failed, but then a successful one comes in. (Issue #82)

Which is almost certainly because `Contribution.repeattransaction` doesn't work unless there is a previous "Completed" contribution which is not always the case (Eg. the previous one failed, was refunded etc.). That will be fixed by https://github.com/civicrm/civicrm-core/pull/22487 and then you'd be able to call repeattransaction directly.

I should note that deprecating does not mean removing as yet! We'd normally wait about six months before actually removing the function and I'm proposing that you simply make a copy of it in the GoCardless code until you are ready to update/clean it up.

**Comment by demeritcowboy** [comment]
I haven't r-run'd and usually stay away from this area but

* Appears to be a straight copy.
* Variable names are all the same.
* No pass-by-ref in the original calling function to think about.
* It comes at the end of the functions so doesn't affect vars after it.
* Universe shows the depracatee (deprecee?) is only used here and in gocardless. It should still function as before but with a notice.

Jenkins retest this please.

**Comment by mattwire** [comment]
Thanks @demeritcowboy

**Comment by eileenmcnaughton** [comment]
Yep agree - that function was definitely never supported to be called from outside of core but since you identified a place calling it then deprecation = better than removal.

The repeatransaction function is still called within completeOrder but is ALMOST completely separated from the rest of the function (if it only supported 'Pending' as status it would return)

**Pull request merged**
