### PR TITLE
CRM-20859 Attempt to fix issue with unsubscribe where we don't consider all pot…

### PR DESCRIPTION
**Pull request by seamuslee001**
…ential includes

### CODE REVIEW

**Comment by JoeMurray** [comment]
Please update title with CRM issue number

**Comment by seamuslee001** [comment]
@JoeMurray have updated title now Joe

**Comment by JoeMurray** [comment]
Thx!

**Comment by eileenmcnaughton** [comment]
@seamuslee001 - where do you think this is at? It looks very much like one that has languished due to lack of unit test

**Comment by eileenmcnaughton** [comment]
@seamuslee001 let's close this & bring it back to life if you decide to revisit & write a test - I don't think it would be mergeable without one (just going through some of the very oldest PRs)

**Pull request closed without merging**
