### PR TITLE
dev/core#1386 Allow advanced search for contributions without a soft credit related

### PR DESCRIPTION
**Pull request by francescbassas**
https://lab.civicrm.org/dev/core/issues/1386

### CODE REVIEW

**Comment by francescbassas** [comment]
test this please

**Comment by BettyDolfing** [comment]
test this please

**Comment by jaapjansma** [comment]
Betty and I are reviewing PR's and we came across this PR.

* General standards
    * Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
        * __PASS__ : The goal/problem/solution have been adequately explained in the PR and in the issue.
    * User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
        * __ISSUE__: The change would noticeably impact the user-experience but does not require training.
        * __COMMENTS__: We would suggest renaming the list of options to:
           *  Contributions Only
            * Soft Credits Only
            * ~~Soft Credits with related Hard Credit~~ Contributions and their related soft credit
            * Contributions (~~only~~) without a soft credit
            * ~~Both~~ All
    * Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
        * __PASS__: The changes do not require documentation.
    * Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
        * __PASS__: We have tested this PR and it works. 
* Developer standards
    * Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
        * __PASS__: The change preserves compatibility with existing callers/code/downstream.
    * Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
        * __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
        * __COMMENTS__: We have given this pass. However the added option has a name which is unclear to us.
    * Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
        * __PASS__: The change is trivial enough that it does not require tests.
    * Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
        * __PASS__: The test results are all-clear.

@francescbassas could have a look at our remark on the user impact? Are you able to rename the options so it becomes a bit more clear.

**Comment by francescbassas** [comment]
Options renamed. Thanks for the review.

**Comment by jaapjansma** [comment]
Betty and I have tested the changes and this pr is ready to be merged. 
However we do think it might be good to refactor/redesign the find contributions screen and how the drop down of soft credits fits into it However that is a lot of work and out of the scope of this PR. 

@eileenmcnaughton or @mattwire could one of you merge this PR?

**Comment by eileenmcnaughton** [comment]
I actually disagree that this change is trivial enough it doesn't require tests- we have had no end of problems with soft- credit related search features & I think in general adding any new feature to search or reports requires a test.

However, it's merged now - and we got the queue down a bit

**Comment by eileenmcnaughton** [comment]
Update - @seamuslee001 has written the missing test!

**Pull request merged**
