### PR TITLE
CRM-17120 Unit test to ensure replacing deprecated function (to get labels) does not cause regressions.

### PR DESCRIPTION
**Pull request by saurabhbatra96**
- [CRM-17120: Function CRM_Core_OptionGroup::getLabel does not use caching](https://issues.civicrm.org/jira/browse/CRM-17120)

### CODE REVIEW

**Comment by saurabhbatra96** [comment]
@eileenmcnaughton Ma'am please have a look.

**Comment by eileenmcnaughton** [comment]
Looks great - I feel like the line indentation might be not quite right- but if it isn't Jenkins will let us know.

Good to merge if it passes Jenkins!

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
add to whitelist

**Comment by eileenmcnaughton** [comment]
@totten I don't think my add to whitelist worked....

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by monishdeb** [comment]
add to whitelist

**Comment by eileenmcnaughton** [comment]
@saurabhbatra96 the good news is the tests finally ran. The bad news is they hit some coding standards complaints :-(

**Comment by saurabhbatra96** [comment]
Looks like my text editor was not configured to use spaces instead of tabs to indent. I'll fix it ASAP.

**Comment by saurabhbatra96** [comment]
Rather strange. The "api_v3_CustomValueTest" is running just fine on my local machine. And the schedule mailing for the past issue is back again.

**Comment by kurund** [comment]
unrelated test failures

**Comment by eileenmcnaughton** [comment]
Yay!

I did a quick grep for CRM_Core_OptionGroup::getLabel & there are only 11 instances left - so we are on our way to getting rid of it!

**Pull request merged**
