### PR TITLE
Crm 17616

### PR DESCRIPTION
**Pull request by JohnFF**
@eileenmcnaughton This will need testing on an install with over 500 contacts. From my POV it looks fine and performs well on a DB of 205.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
the only change is the use of a constant?

**Comment by eileenmcnaughton** [comment]
unrelated test fail

**Comment by JohnFF** [comment]
Tested with 1000+ contacts.
Taken from #9257 .

**Comment by eileenmcnaughton** [comment]
@JohnFF confirmed he has tested with 500+ & this is the PR per Samuel with a coding improvement

**Pull request merged**
