### PR TITLE
SHOR-17: Fixed pages dropdown design issues

### PR DESCRIPTION
**Pull request by mukeshcompucorp**
Overview
----------------------------------------
This PR does the following changes in campaigns,
https://s.nimbusweb.me/share/1658672/7fbgty60du9lwq57ule0

It just adds right container based on the standard structure of civicrm

Before
----------------------------------------
gotv voter tracking training 3

After
----------------------------------------
gotv voter tracking training 4

### CODE REVIEW

**Comment by mattwire** [comment]
@mukeshcompucorp Probably fine. but can we have before/after screenshots with shoreditch disabled as well please?

**Comment by mukeshcompucorp** [comment]
@mattwire Please see now

**Comment by mattwire** [comment]
@colemanw Very minor html tweak.  Good to merge

**Comment by eileenmcnaughton** [comment]
merging based on @mattwire review

**Pull request merged**
