### PR TITLE
dev/core#2715 remove the  mystery self::_trxns property

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
dev/core#2715 remove the  mystery self::_trxns property

Before
----------------------------------------
`self::_trxns` set rather than using an in-function variable

After
----------------------------------------
in function variable

Technical Details
----------------------------------------
The setting on self::_trxnIDs has always been a blocker to making this code
more logical. I took a dive into it & decided it is only operating
as a normal variable and not being used between functions in a
functional way

@monishdeb I'm gonna need you to dig in to see if you agree with my analysis that this isn't needed.

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
hmm

```
PHP  46. Civi\Api4\Service\Spec\Provider\EntityTagFilterSpecProvider->applies() /home/jenkins/bknix-dfl/build/core-21391-8353w/web/sites/all/modules/civicrm/Civi/Api4/Service/Spec/SpecGatherer.php:65
PHP  47. in_array() /home/jenkins/bknix-dfl/build/core-21391-8353w/web/sites/all/modules/civicrm/Civi/Api4/Service/Spec/Provider/EntityTagFilterSpecProvider.php:52

Warning: in_array() expects parameter 2 to be array, null given in /home/jenkins/bknix-dfl/build/core-21391-8353w/web/sites/all/modules/civicrm/Civi/Api4/Service/Spec/Provider/EntityTagFilterSpecProvider.php on line 52
```

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton it keeps hitting that same thing I have no idea why

**Comment by demeritcowboy** [comment]
```
CRM_Activity_Form_SearchTest::testSearch
Error: Access to undeclared static property: CRM_Contribute_BAO_Contribution::$_trxnIDs

...\CRM\Financial\BAO\FinancialItem.php:105
...\CRM\Price\BAO\LineItem.php:420
...\CRM\Contribute\BAO\Contribution.php:3516
...\CRM\Contribute\BAO\Contribution.php:225
...\CRM\Contribute\BAO\Contribution.php:489
...\api\v3\utils.php:1314
...\api\v3\Contribution.php:87
...\Civi\API\Provider\MagicFunctionProvider.php:89
...\Civi\API\Kernel.php:149
...\Civi\API\Kernel.php:81
...\api\api.php:22
...\Civi\Test\Api3TestTrait.php:292
...\Civi\Test\Api3TestTrait.php:173
...\tests\phpunit\CiviTest\CiviUnitTestCase.php:1073
...\tests\phpunit\CRM\Activity\Form\SearchTest.php:14
```

**Comment by eileenmcnaughton** [comment]
Does that work when it's not a singleton? I feel like it would just always get NULL

image

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by eileenmcnaughton** [comment]
I just removed the reference in FinancialItem - I think that would always be NULL

**Comment by eileenmcnaughton** [comment]
@monishdeb is this one on your todo list?

**Pull request merged**
