### PR TITLE
CRM-20184 Missing email_greeting in Workflow Templates

### PR DESCRIPTION
**Pull request by magnolia61**
Overview
----------------------------------------
The token {contact.email_greeting} was introduced to give site admins control over the type and formality of the greeting. This token was only introduced in a few system workflow templates. This PR adds it to the others. Also it adds the display name to the email subject to be clearer 

Before
----------------------------------------
Even though {contact.email_greeting} was introduced the workflow templates did not work as expected.
 
After
----------------------------------------
All (actually all but some) of the templates now have the {contact.email_greeting} for both the html and the text version. Also the display name is added to the subject to clearer discern between mails.

Technical Details
----------------------------------------
templates were changes in xml/templates/message_templates/ and I added them to the upgrade script.

Comments
----------------------------------------

---

 * [CRM-20184: Some System Workflow templates still miss {contact.email_greeting}](https://issues.civicrm.org/jira/browse/CRM-20184)

### CODE REVIEW

**Comment by magnolia61** [comment]
Hi @twomice & @sunilpawar, I saw you have been involved in issues regarding greeting tokens for civicrm in the past, would any one of you like to review my PR to make the system workflow messages consistent in the use of the {contact.email_greeting} token? The PR provides an upgrade script. Thanks!

**Comment by twomice** [comment]
Jenkins test this please.

**Comment by twomice** [comment]
Thanks @magnolia61 for the PR.

1. In general I like the idea of using email_greeting instead of display_name in emailed message templates. 
2. Adding display_name to the subject line should probably be discussed separately on its own merits. It may not be a slam-dunk "yes" from all concerned parties; either way, I recommend putting it in a separate issue and separate PR. (That will also reduce the sheer size of this PR, which is daunting.)
3. As far as I can tell, you're taking the right approach to changing templates in the upgrade scripts, but it's pretty hard (not your fault) to see what's changed, since the diffs are just "+" lines on new files. Not sure what to do about that, but also not sure I'll have time to work out the differences.
4. Automated tests failed somewhere. You'll need to look at those results and fix whatever is failing. The test results are no longer available (I think it's because the PR is 14 days old now), so I've issued a request (my previous comment to Jenkins) to start those tests again. When the tests are done, if there's a failure, you can click the "Details" link to find what failed and clues about why.

**Comment by jaapjansma** [comment]
This PR looks good to me. I agree with @twomice  that the display name should be a separate PR ideally. But as it is already here I would rather review it is as mergeable because it is not a big deal. 
@magnolia61 I do think you have to make sure the automated tests will pass. I do think that will include change the test as the tests which are failing are looking up whether a certain text exists in the email send out. (And it doesnt as you have changed it).

**Comment by magnolia61** [comment]
@jaapjansma Would that be as easy as replacing  'Dear Mr. Anthony Anderson II' with 'Dear' in:

[](https://github.com/civicrm/civicrm-core/blob/73499ef32848dc0dc472abad9196d9fba1b219f4/tests/phpunit/CRM/Core/Payment/AuthorizeNetIPNTest.php)
$mut->checkAllMailLog(array(
      'Membership Type: General',
      'Mr. Anthony Anderson II" <anthony_anderson@civicrm.org>',
      'Amount: $ 200.00',
      'Membership Start Date:',
      'Supporter Profile',
      'First Name: Anthony',
      'Last Name: Anderson',
      'Email Address: anthony_anderson@civicrm.org',
      'This membership will be automatically renewed every',
      'Dear Mr. Anthony Anderson II',
      'Thanks for your auto renew membership sign-up',
    ));

**Comment by jaapjansma** [comment]
I am not sure whether that is enough it depends on what the test exactly is testing. Maybe @eileenmcnaughton  can help with this?

**Comment by eileenmcnaughton** [comment]
@magnolia61 It does seem like replacing 'Dear Mr. Anthony Anderson II', with the greeting value makes sense - although hopefully it's a 'real' value like Dear Anthony not just Dear - might need to ensure that in the test set up

**Comment by magnolia61** [comment]
Anyone? Is the failing test related? I cant figure out how it would be related

**Comment by jaapjansma** [comment]
I dont think it is related.

**Comment by eileenmcnaughton** [comment]
No - I think not

**Comment by eileenmcnaughton** [comment]
I don't feel like I can review a PR with so many changes  - it might need to be broken up - if you want to put a PR for a single template I can take a look at that (that might help find any issues too)

**Comment by magnolia61** [comment]
ehm. I'll try. BTW to upgrade system message templates, are the files in  xml/templates/message_templates necessary or are they generated automatically. I included them in this PR.

**Comment by eileenmcnaughton** [comment]
@magnolia61 I'm not that sure - perhaps @monishdeb @jitendrapurohit 
or @yashodha can advise as they have done this sort of update before

**Comment by magnolia61** [comment]
@eileenmcnaughton Shall I change this PR temporarily to be only for 1 template, or create a new one?

**Comment by eileenmcnaughton** [comment]
@magnolia61 using this PR keeps the comments for us  which is nice - start with the template you care most about!

**Comment by magnolia61** [comment]
I narrowed it down to 3 templates for review, and will add the other templates after initial review.

**Comment by MikeyMJCO** [comment]
I have concerns with this specific change: https://github.com/civicrm/civicrm-core/pull/11674/files#diff-806ccbd10f012c10552ca0100fb047dd

**Comment by eileenmcnaughton** [comment]
I'm closing this in favour of #12296 (which excludes the email subjects change & uses new upgrade logic)

**Pull request closed without merging**
