### PR TITLE
dev/core#4231 Fix failure to import non-default state

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fixes https://lab.civicrm.org/dev/core/-/issues/4231

Before
----------------------------------------
As described in https://lab.civicrm.org/dev/core/-/issues/4231 & as replicated in the attached test

After
----------------------------------------
Fixed

Technical Details
----------------------------------------
The import is relying on apiv4 getfields to return the available state options here
https://github.com/civicrm/civicrm-core/blob/68108b0a1dd4ea65d213030ed0b17d58cdf3cfc9/CRM/Import/Parser.php#L1741-L1745

getFields is returning only the states from the default country, not other countries even though the api call does not specify them.

Note that the default country is not configured by default & perhaps is more commonly used on older sites. Also note that when set it literally is the default country, not the only country

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
Hmm, I just spent about half an hour debugging this test and tracing through the import code... I'm finding those classes particularly difficult to follow.

Generally speaking, the problem is that each field is being processed atomically, the importer classes are failing to pass relevant context into APIv4.getFields, which APIv4 needs so it can handle the interrelatedness of fields like county->state->country.

I don't know how much we'd have to fight against the Importer code to achieve this, but the ideal solution would be to give APIv4 the context data it needs. The general formula for this (as seen in APIv4's [own handling of pseudoconstant lookups](https://github.com/civicrm/civicrm-core/blob/c26a7a076cb21df9bb79ff7cf57796be49184f4b/Civi/Api4/Generic/AbstractAction.php#L531-L537)) is:

1. TopSort the array in order of dependencies (e.g. country should be resolved before state, state before county). There's already [a utility function to do this](https://github.com/civicrm/civicrm-core/blob/89f5ee868df191639b5a7c097bf1bf7e9fda6291/Civi/Api4/Utils/CoreUtil.php#L464).
2. Pass the array of resolved `$values` into `APIv4::getFields()` so that it knows e.g. the value of `country_id` when looking up options for `state_province_id`.
3. That's it. It's pretty simple, but the Importer classes might put up a good fight regardless.

**Comment by eileenmcnaughton** [comment]
@colemanw hmm - the importer code builds up an array of available options for each field it is importing at the start. Then while importing it checks the value against the id, name, label & abbreviation to find a match. It doesn't know all the countries it will be dealing with when it starts, or even if all rows that have a state will have a country field. And if they don't have a country it might not be the site default country - (for a small number of states that would be ambigous & would rightly fail on import)

In my database there are less than 2k states - that doesn't feel to me like the sort of size that I would want to avoid loading all at once, given each row doesn't have that many keys (I would want to avoid serilizing/unserializing it though) - so I'm really looking for the `getFields` to not filter if no filter is passed to it

**Comment by colemanw** [comment]
@eileenmcnaughton if you want to fetch all states, there's probably a way to do that. But I think the underlying problem will persist: without passing any context to the api, it has no way of knowing the difference between e.g. Maryland, USA and Maryland, Liberia, as this test demonstrates:

https://github.com/civicrm/civicrm-core/blob/d2ce7f708c84c00a77654ceb0a4731cf45f7423f/tests/phpunit/api/v3/AddressTest.php#L487-L488

**Comment by eileenmcnaughton** [comment]
@colemanw yeah - but the import class handles that - ie it works with the information it has to get the best pick or lets the user know if it is unresolvably ambigous - but it does that row by row whereas it resolves options at the start

**Comment by eileenmcnaughton** [comment]
Also worth noting that import does a validate process before the import process

**Comment by colemanw** [comment]
@eileenmcnaughton where does the import code fetch the list of states?

**Comment by eileenmcnaughton** [comment]
@colemanw it does it here https://github.com/civicrm/civicrm-core/blob/68108b0a1dd4ea65d213030ed0b17d58cdf3cfc9/CRM/Import/Parser.php#L1741-L1745

**Comment by colemanw** [comment]
@eileenmcnaughton I don't think it's specific to APIv4. The API just delegates to `CRM_Core_Pseudoconstant` which in turn calls `BAO::buildOptions` which does this:

https://github.com/civicrm/civicrm-core/blob/ab913b2b59ba44d65127da8c8e0f9d80f16063e4/CRM/Core/BAO/Address.php#L1221-L1229

**Comment by eileenmcnaughton** [comment]
@colemanw hmm - that ` if (empty($props['country_id']) && $context !== 'validate') { ` - if I could get the context to be `validate` ? Do you know if the api could pass context through?

**Comment by colemanw** [comment]
@eileenmcnaughton unfortunately not. And that would also affect how the output is formatted.
Seems like the only practical fix at this point would be to add a special case in the Import_Parser class to fetch all states/provinces without using the API.

**Comment by eileenmcnaughton** [comment]
@colemanw OK - I think I'd gotten to that conclusion - I might see if I can lazy load in some way but will think about that

**Comment by colemanw** [comment]
Ok this is working now so let's merge it.

**Pull request merged**
