### PR TITLE
Move the code to add or clear employer from relationship backoffice form to BAO

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
The Relationship backoffice form has a core function ```setEmploymentRelationship()``` responsible for adding/clearing employer data to an individual contact when a 'Employee of' relationship is added/updated. This code needs to present at the BAO level so that Relationship.create API can 

Before
----------------------------------------
Relationship.create API cannot add the employer contact after a current 'Employee of' relationship is created

After
----------------------------------------
1. Relation.create API can add/clear the employer contact after a current 'Employee of' relationship is created or expired.
2. Added an optional relationship.create API parameter ```is_current_employer```

Technical Details
----------------------------------------
The added UT ensures that it doesn't break the logic in API or at form level.

Comments
----------------------------------------
ping @eileenmcnaughton @jitendrapurohit @mattwire @seamuslee001

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
failure seems related @monishdeb

**Comment by mattwire** [comment]
test this please

**Comment by mattwire** [comment]
@monishdeb +1 on code cleanup/fixes/improvement!  Is this employer behaviour documented anywhere (ie. at docs.civicrm.org)?  If not, could you raise a PR/issue against the docs so we can capture this behaviour there in future.

**Comment by monishdeb** [comment]
Thanks @mattwire. And good point.. yes I can see the documentation in here https://docs.civicrm.org/user/en/latest/organising-your-data/relationships/#connecting-employees-and-employers. I think that would be enough to have only the behavior documented and not outlining the technical aspect about how we can use relationship API to set employer field too?
 As this PR centralizes the code so that Relationship API and form acts like one for creating employer relationship + code cleanup + UT

**Comment by jitendrapurohit** [comment]
Seems like this change disable the relationship if current employer setting is disabled on the form. Pretty sure it worked fine before the latest commit(fix test failure) made today on this PR.

To replicate -

- Add a current employer to a contact.
- Edit the relationship and disable the current employer checkbox.
- The complete relationship is disabled instead of removing the current employer.

**Comment by eileenmcnaughton** [comment]
this is stale + seems to need further work

**Comment by eileenmcnaughton** [comment]
This is stalled & stale :-( I pulled the unit test together with enough changes to make it pass inot a new PR https://github.com/civicrm/civicrm-core/pull/14950 :-)

**Pull request closed without merging**
