### PR TITLE
dev/core#4696 - Increase length of ActionSchedule.name (again)

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Companion to #27907 for 5.67

Technical Details
----------------------------------------
This repeats the upgrade step from 5.66.1, since 5.66 will not be forward-merged to 5.67. It also bumps the version so that anyone already using 5.67.beta1 will get this upgrade step.

### CODE REVIEW

**Comment by totten** [comment]
@colemanw Right, 5.66 changes do need to propagate to 5.67. But `git merge` is only reliably clean for RC=>master.  The standard play is to treat PRs on `5.66-stable` and `5.67-rc` as separate deliverables.

> I targeted 5.67.0 for the upgrader because it's fine to wait until release day to merge this. Until then, upgrade-tests won't like it.

No. In that approach:

* The RC will be less representative of the actual release.
* The PR will take attention on the day-of-release.
* The PR will never give a clean test-run, unless we specifically change the process to accommodate it.
* If there's some other upgrade issue comes to light in the next week, then it will be MC'd.

There's no need or benefit to holding our fire till the last second. We're not 18th century minutemen running low on gunpowder. The standard approaches to schema-changes-in-RC are:

* __The Easy Way__: Target the change at 5.67.beta1. 
* __The Good Way__: Raise the version to 5.67.beta2 and target 5.67.beta2.

**Comment by colemanw** [comment]
@totten ok I went with the good way & have updated the description. Thanks for the colorful analogy to the Revolutionary War.

**Comment by totten** [comment]
Yeah, it just needed the cherry-pick for 5.66 part. Added that. Merge on pass.

**Comment by colemanw** [comment]
Whoops, as soon as you cherry-picked that my mistake jumped out at me. See #27907

**Comment by colemanw** [comment]
@totten I've updated the cherry-pick to reflect the final convergence. If that looks ok you can re-add MOP.

**Comment by totten** [comment]
@colemanw OK, makes sense. Re-add MOP.

**Pull request merged**
