### PR TITLE
Advanced Search: icon for the Search Settings

### PR DESCRIPTION
**Pull request by mlutfy**
Overview
----------------------------------------

Converts the "Search Settings" fieldset to something toggled by an icon.

Before
----------------------------------------

Greenwich:

image

image

The Island:

image

image

After
----------------------------------------

Greenwich:

image

image

The Island:

image

image

Technical Details
----------------------------------------

Intentionally keeping this change small, because going forward we may want to only do these things in RiverLea.

Comments
----------------------------------------

Based on changes proposed by @vingle  in #31226

### CODE REVIEW

**Comment by vingle** [comment]
Looks great. One little suggested change [here](https://github.com/civicrm/civicrm-core/pull/31293/files#diff-39a23f4f14eca5ce48a561ed6a03ccb635cd39cb45cdc7f28ef9fa3be73a4800R2298):
```
.crm-container details.crm-accordion-settings summary::before {
    content: '\f013';
    ++ margin-right: 0.5rem;
}
```
image

**Comment by mlutfy** [comment]
@vingle I pushed this change : 

```
diff --git a/css/civicrm.css b/css/civicrm.css
index d4a26ee431..a07a2aa878 100644
--- a/css/civicrm.css
+++ b/css/civicrm.css
@@ -2319,7 +2319,7 @@ div.crm-master-accordion-header a.helpicon {
 .crm-container details > summary:before {
   font-family: "FontAwesome";
   display: inline-block;
-  width: 1em;
+  padding-right: 0.5rem;
   content: "\f0da";
   font-size: 13px;
 }
```

It applies to all accordion icons, but I think it's better this way, because `width: 1em` was a strange assumption?

image

**Comment by vingle** [comment]
@mlutfy looks good - RiverLea also doesn't put a width on the icon, and just adds a margin-right. I guess it might come from when it was using a background image sprite so the width needed setting.

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by mlutfy** [comment]
(set to merge-ready based on Nic's review, but avoiding self-merge)

**Pull request merged**
