### PR TITLE
[WIP] Wondering how much I can break things

### PR DESCRIPTION
**Pull request by demeritcowboy**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Pretty much

**Comment by demeritcowboy** [comment]
He he. Not a record though I think.

I want to leave this open for a bit since if https://github.com/civicrm/civicrm-core/pull/21060 gets merged I'd like to run this again and see if anything other than fopen/unlink calls come up.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy so you have set a challenge of most breakage?

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
Tests finish now - it looks like we rely on leakage to avoid enotices....

image

**Comment by demeritcowboy** [comment]
The first one yes. The "secure" ones we've seen before and are "real" but happen because the earlier fail doesn't reset the mode. Some of the ones at the end are tests that expect an exception, so there's nothing actually wrong there just that type of test isn't compatible with this type of error-handling.

The second one is very interesting since at first glance suggests the test shouldn't be working normally:

`CRM_Contribute_ActionMapping_ByTypeTest::testTokenRendering
Failure in api call for job send_reminder:  fopen(/home/jenkins/bknix-dfl/build/core-21064-6l9mr/web/sites/default/files/civicrm/templates_c/en_US//%%27/27E/27EEDEE2%%string%3A%0A++++++first+name+%3D+Alice%0A++++++receive_date+%3D+February+1st%2C+2015+12%3A00+AM%0A++++++contribution+status+id+%3D+1%0A++++++new+style+status+%3D+Completed%0A++++++new+style+label+%3D+Completed+Label%2A%2A%0A++++++id+1%0A++++++contribution_id++-+not+valid+for+action+schedule%0A++++++cancel+date+August+9th%2C+2021+12%3A00+AM%0A++++++source+SSF%0A++++++legacy+source+%0A++++++financial+type+id+%3D+1%0A++++++financial+type+name+%3D+Donation%0A++++++financial+type+label+%3D+Donation%0A++++++payment+instrument+id+%3D+4%0A++++++payment+instrument+name+%3D+Check%0A++++++payment+instrument+label+%3D+Check%0A++++++non_deductible_amount+%3D+%E2%82%AC+10.00%0A++++++total_amount+%3D+%E2%82%AC+100.00%0A++++++net_amount+%3D+%E2%82%AC+95.00%0A++++++fee_amount+%3D+%E2%82%AC+5.00.php): failed to open stream: File name too long`

**Comment by eileenmcnaughton** [comment]
@demeritcowboy people have complained before about those filenames - from security/privacy POV & also disk clutter - we use CRM_Utils_String::parseOneOffStringThroughSmarty from greetings now

**Comment by demeritcowboy** [comment]
Do you mean something like:

```patch
index d957c3cb9d..d2ebe17c4d 100644
--- a/Civi/Token/TokenCompatSubscriber.php
+++ b/Civi/Token/TokenCompatSubscriber.php
@@ -127,7 +127,7 @@ class TokenCompatSubscriber implements EventSubscriberInterface {

     if ($useSmarty) {
       $smarty = \CRM_Core_Smarty::singleton();
-      $e->string = $smarty->fetch("string:" . $e->string);
+      $e->string = CRM_Utils_String::parseOneOffStringThroughSmarty($e->string);
     }
   }
```

It seems the test was working normally because what happens when the fopen call fails is smarty then autogenerates a different filename just using rand(): https://github.com/civicrm/civicrm-packages/blob/6998b962b50abb4aa48097e251ecfd9ea202e294/Smarty/Smarty.class.php#L1532.

I can try and see what happens.

And it seems I've been running with Matt's smarty error patch applied all this time. Interesting.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy I think there is an alternate error handler patch that patches core not packages on the thread about error handling

**Comment by eileenmcnaughton** [comment]
@demeritcowboy have you hit peak breakage here - or do you have bigger goals?

**Comment by demeritcowboy** [comment]
The smarty modifier `|default` gave me pause, because its whole purpose is that the var might be missing, but the way smarty compiles it is `<?php $this->assign('to', ((is_array($_tmp=@$this->_tpl_vars['to'])) ? $this->_run_mod_handler('default', true, $_tmp, '_high') : smarty_modifier_default($_tmp, '_high'))); ?>` which uses the `@` to try to silence the error but that is what can lead to the problems in php 8.

But I could put up the token one. I'm thinking many of the other fails here are just fallout from the first fails.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy I suspect the first part of this patch is a change we should actually make (which is unrelated to the second part)

**Comment by eileenmcnaughton** [comment]
I am observing your ongoing dedication to breaking things with the ongoing dedication of the rabbit trying to chew a cardboard box to bits in the background. It feels zen

**Comment by demeritcowboy** [comment]
😄

**Comment by demeritcowboy** [comment]
Closing and have parked what's left in https://lab.civicrm.org/dev/core/-/issues/2795

**Comment by eileenmcnaughton** [comment]
You've given up without achieving full breakage!

**Pull request closed without merging**
