### PR TITLE
dev/core#1670 copy custom fields from master to shared address

### PR DESCRIPTION
**Pull request by samuelsov**
Overview
----------------------------------------
Shared address custom fields are not copied from master. The contact summary is correct because it is taking the values from the master. However, custom fields values are empty for shared address on reports and exports.

https://lab.civicrm.org/dev/core/-/issues/1670

Before
----------------------------------------
The custom fields on address are not copied from master to shared addresses in the database.

After
----------------------------------------
The custom fields on address are copied from master to shared addresses.

Technical Details
----------------------------------------
Eileen has suggested using DAO CopyGeneric which I did as much as possible.
However, it is only applicable for creation, not for update.
It might be cleaner to simply use dao copyCustomFields in both create and update instead.

I've added some unit testing which are failing without the patch and pass correctly after that.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
The fails seem related. In case the jenkins report disappears they are:

```
not ok 1468 - Failure: CRM_Export_BAO_ExportTest::testMergeSameAddress
  ---
  message: Failed asserting that actual size 1 matches expected size 2.
  severity: fail
  ...
```

```
not ok 1469 - Failure: CRM_Export_BAO_ExportTest::testMergeSameAddressGreetingOptions
  ---
  message: Failed asserting that two strings are equal.
  severity: fail
  data:
    got: random string Mr. Anthony Anderson II, Mr. Anthony Anderson II, Dr. Sarah Smith
      II
    expected: random string Mr. Anthony Anderson II, Dr. Sarah Smith II
  ...
```

```
not ok 1498 - Failure: CRM_Export_BAO_ExportTest::testExportGetPreview
  ---
  message: Failed asserting that two arrays are equal.
  severity: fail
  data:
    got:
    - first_name: Anthony
      last_name: Anderson
      Home-street_address: Ambachtstraat 23
      Home-city: Brummen
      Home-country: Netherlands
      Home-email: home@example.com
    - first_name: Anthony
      last_name: Anderson
      Home-street_address: Ambachtstraat 23
      Home-city: Brummen
      Home-country: Netherlands
      Home-email: anthony_anderson@civicrm.org
    expected:
    - first_name: Anthony
      last_name: Anderson
      Home-street_address: Ambachtstraat 23
      Home-city: Brummen
      Home-country: Netherlands
      Home-email: home@example.com
    - first_name: Anthony
      last_name: Anderson
      Home-street_address: ""
      Home-city: ""
      Home-country: ""
      Home-email: anthony_anderson@civicrm.org
  ...
```

**Comment by samuelsov** [comment]
Ok, I will try to use 
```
$addressDAO->copyCustomFields($addressId, $addressDAO->id);

**Comment by samuelsov** [comment]
Ok, thanks, I will rework this.

**Comment by samuelsov** [comment]
I have done a new simpler version without using DAO CopyGeneric. I've managed to run the tests locally.

**Comment by eileenmcnaughton** [comment]
Hidden under the 'ignore me because I've been given the 'needs-work' label was the fact that the needs work was actually just the since-fixed red x

**Comment by eileenmcnaughton** [comment]
In fact the only blocker here seems to be that this got given the kiss-of-death label and our review queue was so overrun we didn't have time to triage the hidden gems like this one.

**Pull request merged**
