### PR TITLE
CRM-17500 fix display name etc not being updated from billing

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
This is tested here in contribution flow

---
- [CRM-17500: Display Name and Sort Name are no longer updated from online contribution page when it contains an email address](https://issues.civicrm.org/jira/browse/CRM-17500)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw -26 +114 - it's so unfair!

**Comment by colemanw** [comment]
You should really study some of the techniques in https://en.wikipedia.org/wiki/International_Obfuscated_C_Code_Contest#Examples

**Comment by davecivicrm** [comment]
@eileenmcnaughton Style warnings at https://test.civicrm.org/job/CiviCRM-Core-PR/6367/checkstyleResult/new/

**Comment by eileenmcnaughton** [comment]
only an unrelated fail now

**Pull request merged**
