### PR TITLE
[WIP] - debug failing test

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
Similar to https://github.com/civicrm/civicrm-core/pull/17702

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Look at the activity_date_time for the last one compared to the first two.

The query itself is non-deterministic, it just happens to work because mysql lets you do it. (The query crashes on mariadb with full-group-by enabled.) It seems like maybe here it's using a different algorithm now as to how it chooses which one of the case activities to include when grouped by case id and the specific activity is not specified somewhere in the query. I don't know what's changed that would cause this though?

Ideas:
1. The query could be made more group-by friendly, but will probably hurt performance without some other changes too.
2. Pull out the activity-related stuff into a separate function instead of in the same query. Again maybe performance slowdown.
3. Change the test, i.e. accept that if you don't specify the sort then you don't know what the sort will be. Except then it might pick a different date_time than the one associated with the activity_type_id, i.e. here it's picking Follow-up, and both do happen to be followups, but one is the one scheduled at 3 days and one is the one scheduled at 21 days. In my local database it picks Open Case each time.


```
Array
(
    [case_id] => 2
    [case_subject] => Case Subject
    [contact_id] => 18
    [sort_name] => D`souza, Antonia
    [phone] => 
    [contact_type] => Individual
    [contact_sub_type] => 
    [activity_type_id] => 14
    [case_type_id] => 1
    [case_status_id] => 1
    [status_id] => 1
    [case_start_date] => 2020-06-28
    [case_role] => Relation 1 for relationship type create
    [activity_date_time] => 2020-07-01 00:00:00
    [activity_id] => 5
)
Array
(
    [case_id] => 4
    [case_subject] => Case Subject
    [contact_id] => 20
    [sort_name] => Pitt, Adam
    [phone] => 
    [contact_type] => Individual
    [contact_sub_type] => 
    [activity_type_id] => 14
    [case_type_id] => 1
    [case_status_id] => 1
    [status_id] => 1
    [case_start_date] => 2020-06-28
    [case_role] => Relation 1 for relationship type create
    [activity_date_time] => 2020-07-01 00:00:00
    [activity_id] => 21
)
Array
(
    [case_id] => 3
    [case_subject] => Case Subject
    [contact_id] => 19
    [sort_name] => Roy, Darric
    [phone] => 
    [contact_type] => Individual
    [contact_sub_type] => 
    [activity_type_id] => 14
    [case_type_id] => 1
    [case_status_id] => 1
    [status_id] => 1
    [case_start_date] => 2020-06-28
    [case_role] => Relation 1 for relationship type create
    [activity_date_time] => 2020-07-19 00:00:00
    [activity_id] => 16
)
```

**Comment by eileenmcnaughton** [comment]
@demeritcowboy it's fine IMHO to turn off full group by mode before the query to make the sort work....

**Comment by demeritcowboy** [comment]
Thanks but that isn't the problem. Something in mysql 5.7 is choosing a different activity to return than before.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy - OK looking at the test the goal seems to be to make sure it sorts as  it should when told to - the check you commented out seems more like 'control group behaviour' than anything that needs to happen a certain way

**Comment by demeritcowboy** [comment]
Agree it's not the most important assert in that test.

**Pull request closed without merging**
