### PR TITLE
Inherited organisation membership is not transferred to the individual contact if one of two relationship types defined in the membership type is disabled

### PR DESCRIPTION
**Pull request by agilewarealok**
Overview: Steps to reproduce
----------------------------------------

1. Membership Type A has option to inherit membership for Relationship A and Relationship B
2. Organisation A has Membership Type A, with status Current
3. Individual A has Relationship A and Relationship B to Organisation A
4. Individual A inherited membership has a status of Current
5. Individual A, Relationship A to Organisation A is Disabled
6. Individual A, Relationship B to Organisation A is Disabled
7. Individual A inherited membership is automatically removed
8. Individual A, Relationship A to Organisation A is Enabled
9. Individual A inherited membership is not re-created

Individual A should have inherited membership re-created if one Relationship is enabled with Organisation A

Before
----------------------------------------
Membership not re-created if one relationship is not enabled.

After
----------------------------------------
Membership is re-created after one of the relationships is enabled.

Comments
----------------------------------------
_Agileware Ref: CIVICRM-1063_

### CODE REVIEW

**Comment by seamuslee001** [comment]
@agh1 i know you have been dabbling in membership stuff recently do you have any feelings on this PR?

**Comment by eileenmcnaughton** [comment]
@agilewarealok this one has style issues

**Comment by agh1** [comment]
I don't have time to review this now (got less PR review work done in Brooklyn than I hoped), but based purely on the description, it sounds like a bug.  For someone to test this out, I'd expect they'd want to:

- create a new membership for already-related contacts and confirm it inherits
- create a new relationship to a contact that's already a member and confirm the membership inherits
- delete the master membership for already-related contacts and confirm it makes the inherited one disappear
- have a contact with two relationships to separate contacts with memberships that should inherit along those relationships.  delete one of the master memberships, and ensure that the contact still inherits a membership from the other.
- have a contact with two relationships to separate contacts with memberships that should inherit along those relationships.  disable one of the relationships, and ensure that the contact still inherits a membership from the other.
- based on the last, disable the other relationship, and ensure that the contact no longer inherits any membership.
- based on the last, re-enable either relationship, and ensure that the membership inherits again.
- have a contact that inherits a membership along two relationships, disable one, and ensure that the membership still inherits.
- based on the last, disable the other relationship, and ensure the membership disappears
- based on the last, re-enable either relationship, and ensure the membership reappears

**Comment by jusfreeman** [comment]
@eileenmcnaughton just noting that this PR is not "stale" - just needs some pretty minor work to get rid of the conflicts.

**Comment by eileenmcnaughton** [comment]
@jusfreeman you are welcome to rebase it & re-open it - that can also have the effect of bringing it onto the front page - which can be good

**Comment by agileware-pengyi** [comment]
@eileenmcnaughton I think this one can be closed then?

**Comment by eileenmcnaughton** [comment]
@agileware-pengyi OK - I'll close it -but I don't think all the stuff in it has been brought over yet.  Still we can experiment with uncommenting more lines of the test Agileware wrote once the other is merged

**Comment by agileware-pengyi** [comment]
@eileenmcnaughton I think #15731 is the last one?

**Comment by eileenmcnaughton** [comment]
@agileware-pengyi I think so  - that unit test was quite a good 'shopping list' of what should work. The code was just so incomprehensible though!

**Pull request closed without merging**
