### PR TITLE
Add icons to contact summary tabs

### PR DESCRIPTION
**Pull request by colemanw**
Before
-----
No icons in tabs

After
-----
screenshot from 2018-10-26 10-09-35

Technical Details
-------
Any extension that adds a tab via `hook_civicrm_tabset` can specify the icon by adding that to the array (no change to the hook signature is needed, it just works). If they don't, they get `fa-puzzle-piece`.

Notes
-------
Shoreditch also adds these icons, but does it in a less robust way. Once this is merged, Shoreditch should be updated to remove those or there will be double-icons.

### CODE REVIEW

**Comment by JonScreat** [comment]
@jamienovick no, the icons we discussed can be seen here:
screen shot 2018-10-26 at 15 37 02

**Comment by jamienovick** [comment]
@colemanw up to you if you think these are any better?

**Comment by colemanw** [comment]
I think there's pros and cons to both sets.  I'll create a style guide page that takes the best of both and canonizes it so we don't keep making it up over and over.

**Comment by mattwire** [comment]
@colemanw Nice! I wish shoreditch would take this approach and build from the ground up rather than just try to wrap over the top of everything.

**Comment by colemanw** [comment]
Please see https://github.com/civicrm/org.civicrm.styleguide/pull/22

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I'm merging this as it is consistent with what was agreed on civicrm/org.civicrm.styleguide#22

**Pull request merged**
