### PR TITLE
CRM-18713 complete

### PR DESCRIPTION
**Pull request by jmcclelland**
Alternate, more comprehensive fix to CRM-18713. This is an alternative PR to https://github.com/civicrm/civicrm-core/pull/8626.

---
- [CRM-18713: SMS activity requires mobile phone to be set as primary](https://issues.civicrm.org/jira/browse/CRM-18713)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
wanna tackle the style warning fails?

**Comment by jmcclelland** [comment]
Yup - thanks for the heads up. white space fixes committed.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by jmcclelland** [comment]
I don't understand jenkins error. The error link (https://test.civicrm.org/job/CiviCRM-Core-PR/10317/checkstyleResult/error/) takes me to a page that says:

No report files were found. Configuration error?

What does that mean?

**Comment by eileenmcnaughton** [comment]
Click on console & you get to 

https://test.civicrm.org/job/CiviCRM-Core-PR/10317/console

& in there

```
In "sites/all/modules/civicrm/", apply "https://github.com/civicrm/civicrm-core/pull/8628" on top of "0b0c49f1a3b3e58b4dbacc17f8228b63eadccd68".

                                                                                     
  [GitScan\Exception\ProcessErrorException]                                          
  Process failed:                                                                    
  [[ COMMAND: git apply --check  ]]                                                  
  [[ CWD: /home/jenkins/buildkit/build/core-8628-34tem/sites/all/modules/civicrm ]]  
  [[ EXIT CODE: 1 ]]                                                                 
  [[ STDOUT ]]                                                                       
  [[ STDERR ]]                                                                       
  error: patch failed: CRM/Activity/BAO/Activity.php:1447                            
  error: CRM/Activity/BAO/Activity.php: patch does not apply                         
                                                                                     
                                                                                     

automerge [-R|--rebuild] [-K|--keep] [-N|--new] [--path PATH] [--url-split URL-SPLIT] [--passthru PASSTHRU] [--] [<url>]...

```

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by davejenx** [comment]
@jmcclelland You say this is an alternative fix to #8626 which has now been merged, so is this PR still relevant?

**Comment by jmcclelland** [comment]
I think it is up to core team. This pull requests does important re-factoring and code cleanup so it is still relevant. However, it might not be worth the time needed to QA it. See https://issues.civicrm.org/jira/browse/CRM-18713 for a long discussion about the reasons for this PR.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I'm going to close this - after this long your comment about time to QA it sounds on the money - I suspect at this point it's easier to start from scratch to refactor this as other changes will have happened

**Pull request closed without merging**
