### PR TITLE
CRM-20464, fixed smarty error

### PR DESCRIPTION
**Pull request by pradpnayak**
----------------------------------------
* CRM-20464: Smarty error when receipt is send for recording payment
  https://issues.civicrm.org/jira/browse/CRM-20464

### CODE REVIEW

**Comment by seamuslee001** [comment]
@pradpnayak Pradeep can you edit this PR to be against the RC branch?

**Comment by pradpnayak** [comment]
@seamuslee001 Updated.

**Comment by seamuslee001** [comment]
Cheers

This looks good and makes sense to me @eileenmcnaughton @monishdeb

**Comment by monishdeb** [comment]
Yup looks good

**Pull request merged**
