### PR TITLE
(dev/core#1252) Fix paging on contribution summary

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
@VangelisP I haven't put this through it's paces but I think something like this would be the right way to fix the paging bug & also improve the report

Before
----------------------------------------
Paging sometimes not available - FGB dependent

After
----------------------------------------
Screen Shot 2019-10-19 at 1 23 52 PM
Screen Shot 2019-10-19 at 1 25 10 PM
Screen Shot 2019-10-19 at 1 25 04 PM

Technical Details
----------------------------------------
Per https://lab.civicrm.org/dev/core/issues/1252#note_24325

Comments
----------------------------------------
https://lab.civicrm.org/dev/core/issues/1252

@yashodha you might have an interest in this - also maybe @kcristiano

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@VangelisP it looks like we will do another 5.18 drop early next week - if you are able to check out if this resolves the issue without other issues we might be able to get it into that drop

**Comment by VangelisP** [comment]
I will start reviewing it asap

**Comment by VangelisP** [comment]
Hello @eileenmcnaughton , looks like it's working **properly** and we got the pager back without any side-effects (that i could see). Tried it in Civi 5.16.2 & 5.18.3.

**Comment by kcristiano** [comment]
Reproduced the issue , did an r-run with the patch and pagination works.   I would like to see this in 5.19 (RC)  I also agree it makes sense to add to 5.18 if another release is being readied

**Comment by mattwire** [comment]
Merging based on @kcristiano review.  @eileenmcnaughton Do you want to do a backport for 5.18?

**Comment by eileenmcnaughton** [comment]
OK - I've created a 5.19 port - https://github.com/civicrm/civicrm-core/pull/15558 - we shouldn't really have merged this to master once we decided to put in 5.19 but I doubt it will matter

**Comment by eileenmcnaughton** [comment]
5.18 https://github.com/civicrm/civicrm-core/pull/15559

**Comment by mattwire** [comment]
@eileenmcnaughton Sorry, I read 5.19 in the comments and my mind gave up noticing that it was still on master branch

**Pull request merged**
