### PR TITLE
(dev/core#1615) WordPress - Enable plugin (if needed)

### PR DESCRIPTION
**Pull request by totten**
Overview
--------

When installing CiviCRM, ensure that the civicrm-wordpress plugin is enabled.

This contributes toward https://lab.civicrm.org/dev/core/-/issues/1615, https://github.com/civicrm/civicrm-buildkit/pull/854, and cv's `CoreLifecycleTest`.

ping @kcristiano 

Before
------

Suppose you have a clean WordPress site and an extracted copy of `civicrm-X.Y.Z-wordpress.zip`.

If you perform installation using `cv core:install`, then it fails with:

```
$ cv core:install --db=.... --cms-base-url=...
...
Creating civicrm_* database tables in wpmastercivi_i8z5e
[Setup:info] [Preboot.civi-setup.php] Load minimal (non-DB) services
[Setup:info] [InstallSchema.civi-setup.php] Install database schema
[Setup:info] [InstallSchema.civi-setup.php] Load basic tables
[Setup:info] [InstallSchema.civi-setup.php] Load sample data
[Setup:info] [BootstrapCivi.civi-setup.php] Bootstrap CiviCRM

In WordPress.php line 66:
                                           
  [Error]                                  
  Undefined constant "CIVICRM_PLUGIN_DIR"  
```                                       

However,  you can make it work with some extra prep:

```
wp plugin activate civicrm
wp eval '$c=[civi_wp()->admin, "add_wpload_setting"]; if (is_callable($c)) $c();'
cv core:install --db=.... --cms-base-url=...
```

After
-----

Just go straight to:

```
cv core:install --db=.... --cms-base-url=...
```

Internally, this adds an extra step - which would appear in the log as:

```diff
 [Setup:info] [InstallSchema.civi-setup.php] Install database schema
 [Setup:info] [InstallSchema.civi-setup.php] Load basic tables
 [Setup:info] [InstallSchema.civi-setup.php] Load sample data
+[Setup:info] [WordPress.civi-setup.php] Activate CiviCRM plugin
 [Setup:info] [BootstrapCivi.civi-setup.php] Bootstrap CiviCRM
```

Comments
--------

If you look at `FlushDrupal.civi-setup.php`, `FlushDrupal8.civi-setup.php`, and `FlushBackdrop.civi-setup.php`, they all include a similar step to auto-enable the integration module.

The main difference here is ordering.  The others run at the very end; this runs a little earlier. Reason:  during `BootstrapCivi`, `CRM_Utils_System_WordPress` depends on having some constants (`CIVICRM_PLUGIN_URL` and `CIVICRM_PLUGIN_DIR` from `civicrm-wordpress:civicrm.php`). Putting this earlier ensures we have those.

### CODE REVIEW

**Comment by totten** [comment]
Test failures are pre-existing.

I was able to use the zip file to install locally (with both web UI and `cv core:install`).

**Comment by eileenmcnaughton** [comment]
GIven merge-ready - is mergeable but maybe pending response from @kcristiano

**Comment by eileenmcnaughton** [comment]
@totten did you see ^^

**Comment by totten** [comment]
Thanks @kcristiano.

* I do think that's an issue with `distmaker` / 30925 (e.g. `distmaker` had regressed for your workflow, and 30925 still hasn't fixed that). 
* If you use the distmaker output from CI on this PR (https://test.civicrm.org/duderino/batch/run-distmaker/20869741), does that work? (*I'm able to use -- and to see that the `civicrm_generated.mysql` file is part of the zip.*)
* I'll add some comments on 30925 about why I think its current revision isn't working for you.

**Comment by kcristiano** [comment]
> If you use the distmaker output from CI on this PR (https://test.civicrm.org/duderino/batch/run-distmaker/20869741), does that work? (I'm able to use -- and to see that the civicrm_generated.mysql file is part of the zip.)

Yes, that works as expected.

Not sure about the test failures, I've been seeing them on a number of PRs and not sure if they are valid.  otherwise, this looks good to merge.

**Comment by totten** [comment]
> (@kcristiano) Not sure about the test failures, I've been seeing them on a number of PRs and not sure if they are valid. otherwise, this looks good to merge.

Yup, unrelated. Basically, those tests were added newly in the past few months -- but that combination (test+WP) wasn't presented in core PR test-matrix. So we need to figure them out, but it's not related to this PR.

**Pull request merged**
