### PR TITLE
CRM-18563 Check for API exception when testing create without params.

### PR DESCRIPTION
**Pull request by seamuslee001**
This is a port of the PR Eileen re-did of Mollox's against 4.7 submitted for testing

---
- [CRM-18563: Issues with the API and testing the API](https://issues.civicrm.org/jira/browse/CRM-18563)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton I think this is pretty close to the fixes you merged to master, thoughts on this?

**Comment by eileenmcnaughton** [comment]
Adding merge on pass - as @seamuslee001 says the code change is small & keeping api consistency is important

**Comment by seamuslee001** [comment]
@eileenmcnaughton this can be merged now

**Pull request merged**
