### PR TITLE
Add missing translations to case activity revisions

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Add ts tags to template.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Looks good +1

**Comment by pradpnayak** [comment]
Adding () brackets intentional?

**Comment by yashodha** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
This looks good to me - only question is whether @mlutfy has any thoughts on whether the brackets make it easier or harder for translators or are neutral

**Comment by mlutfy** [comment]
The parenthesis seem odd in a diff, but presumably makes sense visually? Would you have a screenshot nearby?

This is what I am imagining:

* Activity 2020 - View (Current Revision)
* Activity 2019 - View (Prior Revision)
* Activity 2018 - View (Prior Revision)

(yeah, I'm a bit too lazy to test on the demo site, but you didn't include steps to reproduce :-)

**Comment by demeritcowboy** [comment]
The current screen looks like this, and if there were more rows they would say View Prior Revision.

Untitled

**Comment by mlutfy** [comment]
This is pure bike-shed on a screen few people see, but personally I prefer:

* "View (Current Revision)" on the first item
* only "View" for the old versions, without "(Prior Revision)".

That way the "(Current Revision)" is a clear indicator of the state.

CiviCRM is very verbose sometimes, cluttery, and imho the context here is clear enough.

Grepping around, another screen seems to have "{ts}(this is the current revision){/ts}" and "`{ts}(this is not the current revision{/ts}`, although, again, very verbose, few people would really notice the "not" here. Having `{ts}(Current Revision){/ts}` would make sense?

@mattwire Unless someone has a strong opinion (and I don't either), your call? :)

**Comment by demeritcowboy** [comment]
Just regarding the other grep (the standard case activity view), the way it is now is pretty good I think. The "this is not the current revision" shows in red if you're not viewing the current revision (it's even a hardcoded "red"!), and it is helpful when you're flipping back and forth to know if you are viewing the current revision. The flipping back and forth is not the best UI to see changes, but that's yet another thing.

**Comment by mlutfy** [comment]
My bad. Thanks!

**Comment by demeritcowboy** [comment]
It's all good. You're right there's too many words sometimes and I didn't think of this before but that would be another advantage to an emoji-based codebase... no words and no ts() needed...

**Comment by mattwire** [comment]
@demeritcowboy @mlutfy Thanks - I've updated per "View (Current Revision) / View"

**Comment by demeritcowboy** [comment]
Looks good.

**Comment by mlutfy** [comment]
Thanks @mattwire ! Merging as per @demeritcowboy 's review.

**Pull request merged**
