### PR TITLE
[REF] Import - extract duplicate code to function

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Straightforward function extraction to reduce duplicate code.
This is a followup to #16979

Before
----------------------------------------
Same code in 4 places

After
----------------------------------------
Now just in one place

Comments
----------------------------------------
FIXME: Extracting this was a first step, but there's also still lots of inconsistency
and duplication with how the various import classes handle custom data.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
This looks ok to me. There's a `trim()` difference for one of them but it seems incorrect before.

For r-run I'm not even sure multivalued checkboxes are working on import even before the patch, but I got the same non-result both before and after the patch so it's consistent.

**Comment by colemanw** [comment]
@demeritcowboy for your "before" test were you using `master` or a release? We should ensure it wasn't a recent regression in master, as there have been other changes to this code recently such as #16979.

**Comment by demeritcowboy** [comment]
It was master. I looked on stackexchange just to see if maybe there were some pointers if I was doing it wrong and the most recent I found was from 2018 and it didn't seem to be resolved. And then I went off to something else. I can take another look with a release.

**Comment by demeritcowboy** [comment]
Same in 5.24.4.

**Comment by colemanw** [comment]
I suspect that reconciling these classes with the way contact import does it would fix a lot.

**Pull request merged**
