### PR TITLE
CRM-16185-wordy-change-to-relative-filter-names

### PR DESCRIPTION
**Pull request by joannechester**
uses the pattern
"Timer interval" Prior to Previous "Time Interval"  eg Month prior to previous month 

Choose between this and https://github.com/civicrm/civicrm-core/pull/5495

### CODE REVIEW

**Comment by joannechester** [comment]
I can't tell why it failed the checks.  Would it be because it is in conflict with #5495?

**Comment by colemanw** [comment]
Looks like the CI server had diarrhea in the middle of running the test.
Retest this please.

**Comment by colemanw** [comment]
Retest this please.

**Comment by joannechester** [comment]
dgg has decided against adding this to 4.6, so I need to redo against master. 
However I'm not closing this yet, as I want to ask someone about how to deal with the test failure. I am not sure if the details of that will still be accessible to me if I close this PR.

**Comment by joannechester** [comment]
Having looked at the test and rechecked the PR, I can only conclude that the failure is spurious or the test if faulty.  Changing 5 text strings shouldn't lead to a failure.  What happens next in these circumstances?

**Comment by davecivicrm** [comment]
Joanne - the PR test failure is unrelated. If we were moving ahead w/ this in 4.6, I would merge and close. But since (I think) we've agreed to hold off - you can close.

**Comment by kurund** [comment]
test this please

**Pull request closed without merging**
