### PR TITLE
SearchKit - Add UI for arithmetic equations

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Allows adding, subtracting, dividing and multiplying any number of values in SearchKit
image

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
It's hard to make the case this example is very useful but it almost works - the handling of NULL is an issue.

@colemanw up to you if you want to merge & then fix the NULL or fix it & I'll re-test. I know you are doing some PR jugging at the moment.

image

**Comment by colemanw** [comment]
@eileenmcnaughton I think you're referring to the way MySql handles NULL values in an expression by evaluating the entire expression to NULL. I don't think there's much we can do about that, it's a ~bug~ feature of MySql.
In a more realistic example, would it still be a problem?

**Comment by eileenmcnaughton** [comment]
@colemanw yeah it would - my wmf code is utterly full of COALESCE or IFNULL statments - because they are often adding 'amount given to this fund + amount given to that fund.

The my sql looks like
```
total_amount = IFNULL('net_amount', 0) + IFNULL('fee_amount', 0)
``

**Comment by colemanw** [comment]
Ok, I'd like to merge this & then think about how to address that issue.

**Comment by eileenmcnaughton** [comment]
cool - that's fine with me

**Pull request merged**
