### PR TITLE
[REF] Refactor location-related BAOs to use `writeRecord`

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Updates location BAOs (phone, im, website, email, open id, and address) to use `writeRecord`, noisily deprecate and stop using add/create functions.

Technical Details
--------------------------------
The most challenging was Address which had a lot of extra processing in the `add` function as well as a nonstandard extra `$fixAddress` parameter. Extra processing has been moved to hooks and `fixAddress` to its own function (actually it was already its own function, so never really needed to be a param!).

The `Address::add` function also provided legacy support for custom data in the format `custom_x => 'foo'` mixed into the $params whereas all other BAO create/add functions expect a single key `custom`. I've removed that extra bit and moved it to the `Address::legacyCreate` function which seemed fitting.

### CODE REVIEW

**Comment by aydun** [comment]
Address, IM, Phone, Website all work: I added entries to `cg_group_extends`, created custom groups/fields via UI, then APIv4 get & update all works as expected.

All looks good, other than the failing tests.

**Comment by colemanw** [comment]
Thanks @aydun did you happen to test Address custom data in the UI e.g. on "Edit Contact" or editing an address inline on the summary screen?

**Comment by aydun** [comment]
I have now!

The custom fields work for Address on Contact inline edit but styling isn't great:

image

And on full Edit Contact:
image

Also shows on contact summary:
image

The field shows up when editing an Event Location:
image
but ... it is not saved and produces:
```
    Notice: Only variable references should be returned by reference in Civi\Core\Event\GenericHookEvent->__get() (line 197 of /home/jenkins/bknix-dfl/build/core-25944-8ixv/web/sites/all/modules/civicrm/Civi/Core/Event/GenericHookEvent.php).
    Deprecated function: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in HTML_Common->_parseAttributes() (line 162 of /home/jenkins/bknix-dfl/build/core-25944-8ixv/web/sites/all/modules/civicrm/packages/HTML/Common.php).
    Deprecated function: strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in CRM_Utils_PagerAToZ::getDynamicCharacters() (line 100 of /home/jenkins/bknix-dfl/build/core-25944-8ixv/web/sites/all/modules/civicrm/CRM/Utils/PagerAToZ.php).
```

**Comment by colemanw** [comment]
Ok thanks @aydun that looks similar to the error tests are giving. I'll look into it.

**Comment by aydun** [comment]
Still fails for Event locations

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
@aydun I believe this is all working now :)
Giving `merge-ready` & will merge unless you spot any other issues.

**Pull request merged**
