### PR TITLE
Setting::getItem - use deprecatedWarning instead of just logging

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
I don't think this will change anything in core, but let's see if anything comes up in tests.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Yeah I guess those would fail - we can remove those tests now

**Comment by demeritcowboy** [comment]
Is there still value in testing civicrm_setting overrides for core and custom settings? I've updated the test so it still does that.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy I think there is still value in testing the functionality - but via `Civi::setting()->get()` or the api

**Comment by demeritcowboy** [comment]
Ok updated.

**Pull request merged**
