### PR TITLE
Fixed CRM-18159: sending test mail to group did not include an acl yet.

### PR DESCRIPTION
**Pull request by jaapjansma**
See https://issues.civicrm.org/jira/browse/CRM-18159?focusedCommentId=87759&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-87759

### CODE REVIEW

**Comment by jaapjansma** [comment]
I have updated this PR with a new SQL statement

**Comment by eileenmcnaughton** [comment]
@jaapjansma we aren't really patching 4.4 now - but a couple of people have done PRs for security patches & we are probably going to merge them & make the release available.

As long as you can vouch this is safe & the issue is fixed in 4.7 I'm OK to merge this (on your head be it :-))

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by jaapjansma** [comment]
@eileenmcnaughton no need to merge this. As this merged into 4.7 and i am going to prepare to to fix this in 4.6 also

**Pull request closed without merging**
