### PR TITLE
CRM-17650 ensure that replyto_email is updated when re-using a previo…

### PR DESCRIPTION
**Pull request by seamuslee001**
…us mailing and changing the from address

### CODE REVIEW

**Comment by davecivicrm** [comment]
Related open PR https://github.com/civicrm/civicrm-core/pull/7407. Are both needed?

**Comment by seamuslee001** [comment]
I don't think the other PR will solve the problem in so far as it seems to only affect the sending on of mail where CIviCRM is acting in a relay mode essentially. This PR covers the updating of the relevant field in the db which i think solves the problem as I think the fundamental problem is caused by the from_email field changing but not replyto_email changing with it.

**Comment by davecivicrm** [comment]
Works nicely (tested multiple changes of From while composing - each time the Reply updates). Thanks @seamuslee001

**Comment by freeform-sg** [comment]
Thank you for this! Is there any chance of getting this committed to the 4.6 branch as well?

**Pull request merged**
