### PR TITLE
[NFC] dev/mail#103 Add in unit test to demonstate issue with API…

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This test is currently failing but does replicate the issue 
See https://lab.civicrm.org/dev/mail/-/issues/103

Before
----------------------------------------
No Test

After
----------------------------------------
Test

ping @colemanw @eileenmcnaughton

### CODE REVIEW

**Comment by colemanw** [comment]
I see, so the problem is that the custom group name contains an illegal character (a space).
Perhaps the fix needs to be an upgrade query such as
```sql
UPDATE civicrm_custom_group SET name = REPLACE(name, ' ', '_');
```

**Comment by colemanw** [comment]
And/or maybe this: https://github.com/civicrm/civicrm-core/pull/22049

**Comment by colemanw** [comment]
Before merging this PR I would add a comment to the test that spaces in machine names are *not allowed*!
If those backticks solve the problem, great, but it's still not something we want to encourage.
Also, note that you had to resort to using sql directly to get spaces in the name, because the api won't let you do it!

**Comment by seamuslee001** [comment]
@colemanw I have added a comment to the test now and I think this is mergeable now

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
Actually @seamuslee001 there is a `BaseCustomValueTest` class in the APIv4 tests to help with custom field cleanup so we probably want this test to extend that class.

**Comment by seamuslee001** [comment]
ok done @colemanw

**Pull request merged**
