### PR TITLE
Upgrade and generated sql changes for CRM-16761

### PR DESCRIPTION
**Pull request by jitendrapurohit**
https://issues.civicrm.org/jira/browse/CRM-16761

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
jenkins, test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@jaapjansma I think you also need to change the civicrm_event and civicrm_participant schema xml files. The issue is that Jenkins is going to insert data as part of the build process and it isn't finding column selfcancelxfer_time  which suggests that its not being created as part of the create table. Which I think is defined by the xml files. @davecivicrm  Dave would i be correct here?

**Comment by davecivicrm** [comment]
@seamuslee001 You're correct. I'd like this to go into the next tarball so I'll rework the PR now.

**Comment by davecivicrm** [comment]
@jitendrapurohit  - Closed in favor of https://github.com/civicrm/civicrm-core/pull/7248. Added changes to schema xml files, define FK for transferred_to_contact_id in upgrade, added Transferred participant_status_type to civicrm_data.tpl.

**Pull request closed without merging**
