### PR TITLE
Added pseudoconstant for civicrm_tag.parent_id

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
Added pseudoconstant for civicrm_tag.parent_id

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@pradpnayak test fail relates - likely  the data in the test is invalid & it can't get away  with  that  with this patch

**Comment by pradpnayak** [comment]
@eileenmcnaughton is it because the options are not refreshed when a tag is created?

**Comment by colemanw** [comment]
retest this please

**Comment by pradpnayak** [comment]
retest this please

**Pull request merged**
