### PR TITLE
[REF]  Separate export form classes out & simplify task handling

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This separates out the rest of the export classes to be separate classes extending the parent. 2 functions are switched to overrride

Before
----------------------------------------
Lots of wrangling to get entity specific information. Task title involves lots of noise to do one boolean check

Screen Shot 2020-09-25 at 2 04 10 PM

After
----------------------------------------
Entity specific information is on the class (partially - in progress)

Technical Details
----------------------------------------

Comments
----------------------------------------
@colemanw

### CODE REVIEW

**Comment by JoeMurray** [comment]
@monishdeb could you review this? Thx

**Comment by eileenmcnaughton** [comment]
@monishdeb did you get a chance to look at this?

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by monishdeb** [comment]
Sorry for delay. Tested export action with 'select fields' option on all desired entities like contact, activity, event, contribution, grant etc. without any issue. Merge action is rightfully disabled on the appropriate export entity page like activity, contribution etc. Overall, good initiative towards making entity specific export classes, towards adding more clarity. I am happy with the PR, merging now.

**Comment by eileenmcnaughton** [comment]
thanks @monishdeb

**Pull request merged**
