### PR TITLE
composer require --dev yoast/phpunit-polyfills

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
per https://github.com/civicrm/civicrm-core/pull/25609#issuecomment-1437544704

https://github.com/Yoast/PHPUnit-Polyfills

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
yeah that

api_v3_SystemCheckTest::testSystemCheckBasic
PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

/home/jenkins/bknix-dfl/build/build-0/web/sites/all/modules/civicrm/Civi/Test.php:242
/home/jenkins/bknix-dfl/build/build-0/web/sites/all/modules/civicrm/Civi/Test/CiviEnvBuilder.php:186
/home/jenkins/bknix-dfl/build/build-0/web/sites/all/modules/civicrm/Civi/Test.php:40
/home/jenkins/bknix-dfl/build/build-0/web/sites/all/modules/civicrm/Civi/Test/CiviEnvBuilder.php:200
/home/jenkins/bknix-dfl/build/build-0/web/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:266
/home/jenkins/bknix-dfl/extern/phpunit8/phpunit8.phar:1721

test this please

**Comment by eileenmcnaughton** [comment]
CRM_Event_BAO_ChangeFeeSelectionTest::testCRM20611
PEAR_Exception: DB Error: no database selected


@totten I wonder if we could stop tests when this sort of Exception is caught - does phpunit have the concept of a terminating event?

test this please

**Comment by totten** [comment]
> @totten I wonder if we could stop tests when this sort of Exception is caught - does phpunit have the concept of a terminating event?

I'm not aware of one. There's always `exit()`, which you might be able to sprinkle into `CiviTestListener`?

I have no idea how much time it would save. On one hand, 130 tests is not small. Other the hand, when mysqld goes away, the tests should fail straight-away.

I've been tempted to install https://plugins.jenkins.io/naginator/. It could be a rabbit hole (*e.g. if it doesn't play nice with other plugins*), but it also might Just Work.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

ok 1342 - CRM_Core_Payment_AuthorizeNetIPNTest::testIPNPaymentMembershipRecurSuccessNoLeakageOnlineThenOffline
FATAL: Unable to delete script file /tmp/jenkins7842799724246385970.sh

**Comment by eileenmcnaughton** [comment]
OMG - it passed

**Pull request merged**
