### PR TITLE
CRM-19773 - Check permisions for all entities in reports

### PR DESCRIPTION
**Pull request by colemanw**
* [CRM-19773: Call hook_civicrm_selectWhereClause from the BAOs](https://issues.civicrm.org/jira/browse/CRM-19773)

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton and @nganivet if this passes muster with your testing, then we can also do a little cleanup and remove calls to the now deprecated `buildACLClause` function.

**Comment by nganivet** [comment]
Thanks Coleman, impressive work! I shall have a little time next week to work on the refactoring of the multisite extension with the new hook and moving out code from core. Will keep you updated.

**Comment by eileenmcnaughton** [comment]
I tested this by throwing together a quick unit test against the lybunt report and I was able to demonstrate the acl worked. I will push up the unit test separately.

I agree with the acl approach, but I feel it needs some socialising as people are writing acl-related code without understanding what is done in core.

**Comment by JoeMurray** [comment]
Elegant approach.

**Pull request merged**
