### PR TITLE
CRM-19448 - Extend api permissions to cover entity_table/entity_id

### PR DESCRIPTION
**Pull request by colemanw**
https://issues.civicrm.org/jira/browse/CRM-19448

### CODE REVIEW

**Comment by colemanw** [comment]
@seamuslee001 this continues our work from before. My concern about this is performance - it adds a lot of subqueries. Hopefully the mysql optimizer sorts it out, but if you could test it out on a larger dataset that would be very helpful.

**Comment by seamuslee001** [comment]
@colemanw are you thinking run tests on join to civicrm_entity_tag + other tables How complex you think i should test? and would this cover custom_x tables?

**Comment by colemanw** [comment]
I think a good reality check would be to test an entity_tag.get api call with check_permissions = 1 while logged in as a limited permissioned user (ideally one who is subject to an acl rule). Test it with and without this patch to see if there is a significant performance impact.

So far I haven't applied this to custom fields. I'll take a look at that.

**Comment by seamuslee001** [comment]
I've tested this and there doesn't appear to be any negative performance implications good to merge

**Pull request merged**
