### PR TITLE
CRM-18836 Update Address.tpl

### PR DESCRIPTION
**Pull request by stevekessler**
The URL for USPS is not correct any longer.  Here is the new address - https://www.usps.com/business/web-tools-apis/welcome.htm

---
- [CRM-18836: Update Address.tpl for correct url](https://issues.civicrm.org/jira/browse/CRM-18836)

### CODE REVIEW

**Comment by yashodha** [comment]
Jenkins test this please

**Comment by eileenmcnaughton** [comment]
Since this is merged into master it should get test on pass. Ticket can be closed when this is merged

**Comment by eileenmcnaughton** [comment]
(NB this is also very safe. Ideally we would not do any merging outside QA week but since master DID get merged this one is ok to merge too)

**Comment by eileenmcnaughton** [comment]
unrelated fail

**Pull request merged**
