### PR TITLE
dev/core#4766 Fix event merging profiles together

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fix event merging profiles together

https://lab.civicrm.org/dev/core/-/issues/4766

Before
----------------------------------------
Cats are not cool

After
----------------------------------------
Cats are cool

Technical Details
----------------------------------------
This resolves the logged issue but I wonder if the pre help is in the wrong place?

image

Comments
----------------------------------------
@demeritcowboy @briennekordis

### CODE REVIEW

**Comment by briennekordis** [comment]
Cats *are* cool, and so is this PR; confirmed that it fixes the problem I encountered. Thanks, @eileenmcnaughton !
I could see an argument for the pre-help location going both ways:
 * It would look nice nested under the title of the Profile and be visually easier to understand it relates to that Profile.
 * I've also seen clients use the pre-help to state "Skip this next section if...", which is easier to catch if it's above the Profile's title (but maybe only marginally so).

**Comment by demeritcowboy** [comment]
I see - being cool and evil aren't mutually exclusive. So I take back the "not cool" but will still stand by my statement that cats are evil though.

I get a `Warning: Undefined array key "postPageProfiles"` when there is no profile.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy I pushed up a notice fix. Cats are a bit evil...

**Comment by demeritcowboy** [comment]
😈 

Will merge and can think about the help text.

**Comment by eileenmcnaughton** [comment]
Yeah - help text not clearly regressive

**Pull request merged**
