### PR TITLE
CRM-17528. Remove pxIPN.php and use CiviCRM callback instead.

### PR DESCRIPTION
**Pull request by xurizaemon**
- Note that this defines getNotifyURL() in the CRM_Core_Payment_PaymentExpress class rather than in CRM_Core_Payment where it appears in 4.7.
- Around line 370 in CRM_Core_Payment_PaymentExpressIPN I am unsure how self::singleton($mode, $component, $paymentProcessor) was working - did that function really have those parameters, or did it just not matter?

---
- [CRM-17528: Use civicrm\/payment\/ipn for core DPS payment processor](https://issues.civicrm.org/jira/browse/CRM-17528)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Note that there is a 4.6 PR https://github.com/civicrm/civicrm-core/pull/7155 - assuming we merge the 4.6 before we stop merging to master then this is not required. (I have one query on the 4.6 PR but overall agree with it)

**Comment by eileenmcnaughton** [comment]
We are at the point now where there is a viable published alternative to this broken core processor and I think we should probably communicate that the instance in core is no longer supported, actually doesn't work & will be removed as soon as any gets around to it (or indeed to doing the mentioned communication)

**Comment by xurizaemon** [comment]
Do you feel up to giving a bullet point of what is broken about it here? As a pre announcement or something :)

**Comment by eileenmcnaughton** [comment]
Ipns don't work & in core - this migfht fix it but also core version doesn't work with new accounts

**Comment by eileenmcnaughton** [comment]
I'm closing this because it's stale & probably going to be ditched in favour of https://issues.civicrm.org/jira/browse/CRM-17792

**Pull request closed without merging**
