### PR TITLE
Afform - Store all values in submission record

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Stores all submitted values in the submission record, including saved ids. This allows values to be retrieved from the submission for debugging or display purposes.
Builds on #24080

Technical Details
----------------------------------------
Required some refactoring of the structure of the ids/values arrays to make them more compatible with each other:
- Prefixed `['_joins']` with an underscore so it never conflicts with a field name
- Consistently use `CoreUtil::getIdFieldName()` helper so we are compatible with entities that don't use `'id'` as the unique identifier.
- Make join entities follow the same structure as primary entities.

### CODE REVIEW

**Comment by briennekordis** [comment]
Hi @colemanw, while testing this PR it was found that `$joins` without the underscore is a part of `$this->values`, so two joins (`$joins` and `$_joins`) end up within the `$submissionData` array.

**Comment by colemanw** [comment]
@briennekordis perhaps when performing the final merge we need to unpack `fields` and rename `joins` to `_joins`.

**Comment by briennekordis** [comment]
@colemanw I'm willing to keep reviewing/working on this PR to make a suggestion that would do what you mention above (to keep the ball rolling on this), but could you please elaborate on what you mean by unpacking `fields`?

**Comment by colemanw** [comment]
@briennekordis I've updated this PR with the commit from @MegaphoneJon plus your work to alter the array structure (modified a bit) and some unit tests to lock in the functionality.

**Comment by briennekordis** [comment]
@colemanw That all sounds great; thank you!

**Comment by seamuslee001** [comment]
This seems fine to me, probably just needs an r-run is there more needed to be done on this PR @colemanw ?

**Comment by colemanw** [comment]
IMO this is complete as the unit tests demonstrate that it works. Are you satisfied with this @briennekordis?

**Comment by briennekordis** [comment]
@colemanw Yes! I also tried out this revised patch on a dev site to double check the data structure of the submission; it looks good to me. 

Selection_057

**Pull request merged**
