### PR TITLE
God has answered

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Answers a long-standing theological question.

Before
----------------------------------------
"Dear God why did I have to write this?"

After
----------------------------------------
"Dear Tim, behold what you have written, for it is good. `CRM_Utils_SQL_Select` bestows upon CiviCRM the divine gifts of APIv4, and SearchKit, and Smart Groups with hookable queries. Begone foul demons of query string manipulation, and rejoice at the good news of object-oriented query building!"

@totten

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Actually it's more likely the [oracle](https://www.oracle.com) would answer.

And if god had wanted us to query he would have given us indexes.

**Comment by eileenmcnaughton** [comment]
So I guess it turns out Coleman has answered === god had answered so Coleman === god ?

**Comment by demeritcowboy** [comment]
I've marked as needs-test since we don't want the existence of god or this new prophet feature to get broken in future versions. Shouldn't be too hard to write such a test.

**Comment by demeritcowboy** [comment]
Needs documentation.

**Comment by colemanw** [comment]
@demeritcowboy perhaps we can re-use existing documentation via
```
<import>scripture</import>
```

**Comment by demeritcowboy** [comment]
Hehe. I think you'd have to specify min version  since there's no Matthew in the earlier versions. Although I notice the Jesus feature is a bit broken in recent versions (regression?).

**Comment by colemanw** [comment]
The version history is a bit convoluted, as it pre-dates vcs and sem-ver. And it's hard to find a compiler for Aramaic these days.

**Comment by totten** [comment]
Question for next week's liturgy: Does Lucifer send bugs to interfere with the earthly project? Or are bugs part of the grand plan?

**Comment by kcristiano** [comment]
Bugs are to test your faith and part of the grand plan I think.

**Comment by totten** [comment]
The Code moves in Mysterious Ways.

**Pull request merged**
