### PR TITLE
[needs-rebase] Net_SMTP, Auth_SASL, Net_Socket - Load via composer

### PR DESCRIPTION
**Pull request by totten**
Note: `pear.php.net` is in the middle of a multiday outage, so downloading
PEAR packages is a bit flaky.  For `Net_Socket` and `Auth_SASL`, we
work-around the outage by referencing specific git commits in
`composer.json`.  Fortunately, these packages are small and don't change
much, so these should be pretty close to the latest stable.

CRM-20561

---

 * [CRM-20561: Load Net_SMTP, Auth_SASL, Net_Socket via Composer](https://issues.civicrm.org/jira/browse/CRM-20561)

### CODE REVIEW

**Comment by totten** [comment]
Looks like `Net_SMTP` v1.7.1 isn't installable on PHP 5.3 (although it might work... git log shows they updated just to match a PEAR guideline). Switching back to v1.6.x -- we were using 1.6.x before, and it seems to work with PHP 5.3.

**Comment by eileenmcnaughton** [comment]
I have updated the title of this PR to reflect the fact this PR is stale & needs rebasing. Please update the title once you have done this :-)

**Comment by eileenmcnaughton** [comment]
@totten I'm going to close this - by the time it needs a rebase it's probably better just to start again. If this is worth keeping track of you should open a ticket but if it is not utterly below your caring threshhold it can drift into nothingness

**Comment by xurizaemon** [comment]
Since there was existing work here, I raised it as CRM-20561

But we should use Net_SMTP 1.7.3 or better, since otherwise we will break sites using TLS on PHP >= 5.6.7 (CRM-18408).

**Comment by seamuslee001** [comment]
@xurizaemon the problem with 1.7.3 is it requires php 5.4 which is beyond our minimum

**Pull request closed without merging**
