### PR TITLE
CRM-20561 Use composer for Net_SMTP and Net_Socket and patch for TLS and CiviCRM Custom Error

### PR DESCRIPTION
**Pull request by seamuslee001**
* [CRM-20561: Load Net_SMTP, Auth_SASL, Net_Socket via Composer](https://issues.civicrm.org/jira/browse/CRM-20561)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
4.6 Diff between current packages versions of Net_SMTP and Net_Socket and proposed composer versions https://gist.github.com/seamuslee001/66109ba62b4778f393d846b465106819

**Comment by seamuslee001** [comment]
@totten @jackrabbithanna updated diff between packages and composer versions https://gist.github.com/seamuslee001/34b7e25998ae22d71b5c02c28a21960b

**Comment by seamuslee001** [comment]
Also @totten @jackrabbithanna this is the diff for Exception.php which is installed as well with composer (already done in composer in 4.7) 
https://gist.github.com/seamuslee001/f40662b57722a97de43740cad7e72c74

**Comment by totten** [comment]
Soft +1 -- these 4.6 changes match my recollection of similar 4.7 changes, and I wouldn't expect these parts of the codebase to be very different. However, I haven't done any 4.6 testing.

**Comment by jackrabbithanna** [comment]
So I lean to a soft +1 too.  I really don't want to risk having everyone's 4.6 installations stop working because of the TLS issue.  @totten and @seamuslee001  , any recommendations on how / what to test this directly?  I'm going have to pick someone's brain on how to be able to build CiviCRM from a PR's branch, so that I can install it and test it.  Any resources you can link to for that too would be appreciated.

**Comment by seamuslee001** [comment]
@jackrabbithanna ok so the simplest way to test this is to do the following 

1. Make sure you have composer installed and working off the core repo i.e. having the tools/scripts/composer/ dir
2. Cherry-pick PR or if you have built off buildkit do hub checkout https://github.com/civicrm/civicrm-core/pull/10387
3. Run composer install
4. go into packages/Net/ and remove SMTP.php and Socket.php (or stash them somewhere outside of module dir)
5. Try and send some CiviMail in test format and verify that everything still works as expected. This also applies to the Auth_SASL PR.

**Comment by jackrabbithanna** [comment]
Can't afford to have LTS break with TLS 1.0 Deprecation, so erring on the side of updates
Merging #10387

**Pull request merged**
