### PR TITLE
Fix missing translate tag

### PR DESCRIPTION
**Pull request by wintermoor**
added missing {ts} string

Overview
----------------------------------------
_A brief description of the pull request. Keep technical jargon to a minimum. Hyperlink relevant discussions._

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins ok to test

**Comment by eileenmcnaughton** [comment]
thanks for the patch @wintermoor - if you can add yourself to https://github.com/civicrm/civicrm-core/blob/master/contributor-key.yml we can include you in the release notes
https://github.com/civicrm/civicrm-core/blob/master/contributor-key.yml

**Comment by wintermoor** [comment]
Dear Eileen, 

thank you. I feel fabulous fame incoming ;) 

I will take a closer look on missing translation string in February. No big change for the core, but I can't use perfect contact data in an inperfect translated CRM. It hurts my heart... 

Best 
Torben

    Am Donnerstag, 28. Januar 2021, 22:43:16 MEZ hat Eileen McNaughton <notifications@github.com> Folgendes geschrieben:  
 
 


thanks for the patch @wintermoor - if you can add yourself to https://github.com/civicrm/civicrm-core/blob/master/contributor-key.yml we can include you in the release notes
https://github.com/civicrm/civicrm-core/blob/master/contributor-key.yml

**Comment by eileenmcnaughton** [comment]
Fabulous fame is the best type

**Pull request merged**
