### PR TITLE
dev/core#2642 Add filter by custom fields in Accounting Batch

### PR DESCRIPTION
**Pull request by muniodiego**
Overview
----------------------------------------
When filtering transactions to be included in a batch, custom field filters do not work.

Comments
----------------------------------------
Issue: https://lab.civicrm.org/dev/core/-/issues/2642

### CODE REVIEW

**Comment by seamuslee001** [comment]
Test fail relates here

```
CRM_Financial_Page_AjaxTest::testGetFinancialTransactionsList
Invalid argument supplied for foreach()

/home/jenkins/bknix-dfl/build/core-20556-3fg6v/web/sites/all/modules/civicrm/CRM/Batch/BAO/Batch.php:708
```

**Comment by muniodiego** [comment]
@seamuslee001 , Bug fixed.

**Comment by demeritcowboy** [comment]
* General standards
    * [`r-explain`] __PASS__
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __PASS__
      * Did a light run.
* Developer standards
    * [`r-tech`] __PASS__
    * [`r-code`] __Just needs a squash__
      * Can you [squash commits](https://docs.civicrm.org/dev/en/latest/tools/git/#rebasing-interactive)?
      * Just making a note that at line 776 the existing code calls CRM_Contact_BAO_Query and the second parameter can include custom fields by just setting the defaultReturnProperties() second parameter to TRUE, however the rest of this batch function doesn't really use the query except for some minor where clause manipulation, so changing it to TRUE doesn't help much and you still need to build the query.
    * [`r-maint`] __?__
      * A test would be nice. It's a public static function so in theory shouldn't depend on too much setup.
    * [`r-test`] __PASS__

**Comment by demeritcowboy** [comment]
@muniodiego Are you able to [squash commits](https://docs.civicrm.org/dev/en/latest/tools/git/#rebasing-interactive) and perhaps add a unit test?

**Comment by demeritcowboy** [comment]
Thanks for updating. I'm going to merge.

**Pull request merged**
