### PR TITLE
CRM-20282 Added credit card type field to bookkeeping report

### PR DESCRIPTION
**Pull request by Edzelopez**
----------------------------------------
* CRM-19997: Add Credit card type fields in contribution related reports
  https://issues.civicrm.org/jira/browse/CRM-19997

---

 * [CRM-20282: Add credit card type field for Bookkeeping report](https://issues.civicrm.org/jira/browse/CRM-20282)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Just picking off this one as it is the most straight forward. It tests fine & I can't see any gotchas.

Can I just get you rebase & squash the 2 commits into one & then we can merge.

Also, if you wanted to add pan_truncation, this would be the report to do it on

**Comment by Edzelopez** [comment]
@eileenmcnaughton Done!
I think adding pan_truncation deserves it's own issue since ideally this wouldn't be the only report that could make use of it.

**Comment by eileenmcnaughton** [comment]
Hmm - I'm not sure I would want to see it on all the reports, tbh I'm not even sure card type should be on all of them

**Comment by eileenmcnaughton** [comment]
test this please

**Pull request merged**
