### PR TITLE
Align template fields on Email template with pdf, sms

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Same as https://github.com/civicrm/civicrm-core/pull/29577 but for Email template -  note this requires https://github.com/civicrm/civicrm-core/pull/29505 which makes the permission check in the email layer unnecessary

Before
----------------------------------------

After
----------------------------------------

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by mattwire** [comment]
test this please

**Comment by demeritcowboy** [comment]
@mattwire this shouldn't be merged until the other PR about the permissions is updated and merged, because this PR removes a permission check.

**Comment by mattwire** [comment]
@demeritcowboy Thanks for catching that. This PR was reviewed pre-coffee :-)

**Comment by eileenmcnaughton** [comment]
this change is merged here https://github.com/civicrm/civicrm-core/commit/01dd81730deeeb68f697d31ca5e692677a90bcb8

**Pull request closed without merging**
