### PR TITLE
[NFC] Add in unit test to lock in the fix for the is_deleted in where…

### PR DESCRIPTION
**Pull request by seamuslee001**
… clause issue

Overview
----------------------------------------
This adds in a unit test specifically for the is_deleted field to lock in the fix in #20724

Before
----------------------------------------
No unit test

After
----------------------------------------
Unit test

ping @demeritcowboy @colemanw

### CODE REVIEW

**Comment by colemanw** [comment]
I really don't like tests which directly use the `Api4SelectQuery` object. That class is for internal use only and we should be able to refactor it without breaking brittle tests which expect it to always stay the same.

Note that the `ContactApiKeyTest` uses the api instead.

**Comment by seamuslee001** [comment]
@colemanw have moved it now and also changed it as you have suggested can you check again please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by colemanw** [comment]
Thanks for updating it @seamuslee001. Looks good.

**Pull request merged**
