### PR TITLE
dev/core#2027 Add/update to UK county list

### PR DESCRIPTION
**Pull request by JKingsnorth**
See https://lab.civicrm.org/dev/core/-/issues/2027

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This doesn't need a test IHMO - it's mostly checking the changes seem right.

**Comment by seamuslee001** [comment]
@MikeyMJCO does this look right to you?

**Comment by seamuslee001** [comment]
Test fails relate and also @JKingsnorth should there be an update statement for the ones you are correcting rather than just inserting?

**Comment by eileenmcnaughton** [comment]
I think the previous line is missing a semi-colon, causing the test fails

**Comment by JKingsnorth** [comment]
@seamuslee001 the reason for not doing an update/delete on the changed ones is explained here: https://lab.civicrm.org/dev/core/-/issues/2027 (they're not geographically equivalent).

But really the 'renamed' ones should be added as part of the update still - so I'll make that change.

**Comment by JKingsnorth** [comment]
Added the renamed counties as part of the upgrade script. Please see https://lab.civicrm.org/dev/core/-/issues/2027 for comments and discussion.

**Comment by eileenmcnaughton** [comment]
@MikeyMJCO if you give this the thumbs up I will merge....

**Comment by MikeyMJCO** [comment]
I do :-)

**Comment by seamuslee001** [comment]
@JKingsnorth can you rebase this please

**Comment by MikeyMJCO** [comment]
I have one very minor gripe, `Rhondda, Cynon, Taff` the official usage is `Rhondda Cynon Taf` though I believe the comma separated non-Welsh taff spelling is the ISO one. I would prefer the correct/official usage. https://www.rctcbc.gov.uk/

**Comment by eileenmcnaughton** [comment]
argh @JKingsnorth it's stale again - sorry!

**Comment by JKingsnorth** [comment]
@eileenmcnaughton - Rebased! (pesky civicrm_generated.mysql...)

@MikeyMJCO - going back to what we were talking about 'standardising on the ISO list, yes it has the commas in the ISO list (https://www.iso.org/obp/ui/#iso:code:3166:GB) and it even has the commas in the 'Welsh language' version it supplies on that list as well.

I think, as with other areas, we should leave it with the ISO values to keep consistency? (And maybe write to ISO and get them to change their standard :P)

**Comment by MikeyMJCO** [comment]
> @eileenmcnaughton - Rebased! (pesky civicrm_generated.mysql...)
> 
> @MikeyMJCO - going back to what we were talking about 'standardising on the ISO list', yes it has the commas in the ISO list (https://www.iso.org/obp/ui/#iso:code:3166:GB) and it even has the commas in the 'Welsh language' version it supplies on that list as well, which is probably wrong!
> 
> I think, as with other areas, we should leave it with the ISO values to keep consistency? (And maybe write to ISO and get them to change their standard :P)

Sure, I'll poke the Data Management team at Welsh Government and get it on their radar.

**Pull request merged**
