### PR TITLE
CRM-19888 fix import to prefer default country when resolving states.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
* [CRM-19888: On contact import, State field does not respect default country](https://issues.civicrm.org/jira/browse/CRM-19888)

### CODE REVIEW

**Comment by alifrumin** [comment]
At the Maryland code spring, I'm gonna QA this

**Comment by alifrumin** [comment]
Jenkins retest this please

**Comment by alifrumin** [comment]
I was able to replicate this bug by following the steps in the jira issue https://issues.civicrm.org/jira/browse/CRM-19888 and then tested the fix on a local site  with this patch. 

Instead of getting the second address as being in Guyana it was in the United States. This code works as expected. It is failing 1 check (could be related to recent buildkit issues).

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@alifrumin are you going to lean on @colemanw to merge? I believe he is there with you :-)

**Comment by colemanw** [comment]
@eileenmcnaughton 

> ContactTest.php:305, IncorrectExact, Priority: High
> Line indented incorrectly; expected 2 spaces, found 1
> --
> ContactTest.php:312, CommaLastItem, Priority: Normal
> A comma should follow the last multiline array item. Found: 'ABC'

**Comment by eileenmcnaughton** [comment]
I can't even find those lines in the 2 test files I altered

**Comment by eileenmcnaughton** [comment]
ie line 312 is

 $this->runImport($contactValues, CRM_Import_Parser::DUPLICATE_UPDATE, CRM_Import_Parser::VALID, $mapper, $fields);

& it mentions

A comma should follow the last multiline array item. Found: 'ABC'

**Comment by alifrumin** [comment]
good point @eileenmcnaughton, thank you for the reminder and thank you @colemanw for taking a look at this.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I've set it running again - I can't find the strings that are failing lint in this file

**Comment by eileenmcnaughton** [comment]
test this please

**Pull request merged**
