### PR TITLE
afform - use smarty template to render dynamic custom group block

### PR DESCRIPTION
**Pull request by ufundo**
Overview
----------------------------------------
Here's something I never thought I'd do: **use smarty to generate afforms.**

This PR replaces the PHP string-fu currently used to generate the afform html layout for dynamic <afblock-custom-X-y> blocks with a smarty template.

Before
----------------------------------------
- layout for the block html is generated with PHP string fu

After
----------------------------------------
- layout for the block html is generated with a smarty template
- should generate the same string and behave exactly the same

Comments
----------------------------------------
@colemanw I was thinking this approach would extend well to generating standalone afforms for custom group CRUD forms (and thereafter contact summary tabs). Putting this PR up as a prelim to get your feedback on the approach

(Have been using a more complex variant of this in a project and it's working well.)

### CODE REVIEW

**Comment by colemanw** [comment]
@ufundo yep I'm good with this. Just needs a newline at the end of the `.tpl` file.

**Comment by kcristiano** [comment]
@ufundo  @colemanw I just upgraded a site from 5.75 ESR to master I am getting the following error 

```
[19-Nov-2024 13:43:55 America/Los_Angeles] PHP Fatal error:  Smarty error: [in afform/customGroups/afblock.tpl line 5]: syntax error: invalid attribute name: '$custom.fields' (Smarty_Compiler.class.php, line 1549) in /home/cividev/sites/local/public/wp-content/plugins/civicrm/civicrm/packages/Smarty/Smarty.class.php on line 1215
```

Any thoughts?

**Comment by demeritcowboy** [comment]
The foreach block is php syntax not smarty, although smarty5 might be ok with it.

**Comment by ufundo** [comment]
Ah. My reading of the below is its acceptable (standard even) from Smarty3 onwards, but not available in Smarty2 :facepalm:

https://www.smarty.net/docs/en/language.function.foreach.tpl

**Pull request merged**
