### PR TITLE
WIP Consolidate code to add custom fields to form

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Proposal for consolidating code for custom data on forms (initial step) V2 - Ref #11899 

Before
----------------------------------------
No functional change.

After
----------------------------------------
No functional change.

### CODE REVIEW

**Comment by mattwire** [comment]
We still need a line like this in postProcess to actually save the custom data if it doesn't already exist:
```
$params['custom'] = CRM_Core_BAO_CustomField::postProcess($submitted, $this->_id, 'MembershipType');
```

**Comment by eileenmcnaughton** [comment]
@mattwire I looked at the tpl extraction just now & have confirmed that part works - if you put that in a separate PR I could do a quick merge on it.

Regarding the other part - I'm trying to get my head around how it would work with mulitple data blocks - ie. address, email, website - & still digging on there. I have a simple extraction PR here as part of that #11900 (which I could merge if you wanted to review)

My thinking is to build up something like 

```
$this->customDataEntities = ['Contact' => ['id' => [4]], 'Address' => ['id' => [5,6,7]];
```
& have the trait or helper able to parse & process that array

**Comment by mattwire** [comment]
Template extracted to PR #11950

**Comment by eileenmcnaughton** [comment]
@mattwire thanks - merged

**Comment by eileenmcnaughton** [comment]
@mattwire I'm going to close both of these as they are still both WIP. I will try to put some more time in soon & will re-open one or both when they seem merge ready

**Pull request closed without merging**
