### PR TITLE
Menubar - Improve flexibility & remove hardcoded values

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Minor tweak to `crm.menubar.js` to make it less reliant on the presence of a `<div id="crm-container">` which may not be present on non-civicrm pages.
Also tweaks the js to remove hardcoded pixel values to work better with theme overrides.

Before
----------------------------------------
Problems loading on non-civicrm pages.
Hardcoded values interfere with theme overrides.

After
----------------------------------------
Works better on non-civicrm pages.
Works better with theme overrides to the menu size & breakpoints.

Comments
----------------------------------------
Fixes https://www.drupal.org/project/civimenu/issues/3068607
Fixes https://lab.civicrm.org/dev/core/issues/1127

### CODE REVIEW

**Comment by totten** [comment]
`r-code` : Looks much nicer without the magic numbers. 👍 

@AkA84, any chance you'll be able to look at this?

**Comment by colemanw** [comment]
AkA84 tested this & approved it on the gitlab issue. Looks to be merge ready.

**Comment by mattwire** [comment]
It would be good to see an `r-run` on Joomla / Wordpress + with mosaico editor before merging to ensure this doesn't cause any regressions there.  @vingle @lcdservices @kcristiano Are you able to do any of those checks?

**Comment by kcristiano** [comment]
@colemanw I am unsure about the 'non-civicrm' is that a Drupal Only thing?   In WP the menu looks fine after applying the patch.  

I do think the only way to really test this in the wild is to merge it and monitor the 5.17 RC.

**Comment by mattwire** [comment]
Merging based on @kcristiano comments

**Comment by colemanw** [comment]
@kcristiano yes there is a [drupal module](https://www.drupal.org/project/civimenu) to display the Civi menubar on selected non-civi pages. It wouldn't be hard to create a WP plugin to do the same.

**Comment by AkA84** [comment]
@colemanw what version is this PR going to be in? 5.16 or later?

**Comment by mattwire** [comment]
@AkA84 It's in master (so 5.17) but I think it would make sense to backport for 5.16 if @colemanw agrees - as then we have all "theme related" changes in 5.16 including the new theming subsystem.  And you can target 5.16 with shoreditch.

**Comment by colemanw** [comment]
Ok I've opened up a backport PR.

**Pull request merged**
