### PR TITLE
Mailings menu: simplify Draft/Sent

### PR DESCRIPTION
**Pull request by mlutfy**
Overview
----------------------------------------

CiviCRM menus are very pedantic and programmer-oriented (saves a click while testing, but makes you read a lot more).

The CiviMail menu has always made me struggle, with so many technical things in one place, that most admins go and hide under a blanket.

This PR propose a tiny change that I think will not be too polemic:

- "Draft and Unscheduled Mailings" becomes "Draft Mailings"
- "Scheduled and Sent Mailings" becomes "Sent Mailings"

On the first one, I think we can agree that "unscheduled" is a silly word, and not an actual mailing status.

On the second one, I think most admins, at a glance, won't be confused and think "omg is my scheduled mailing now stuck in the purgatory". In my mind, there are "mailings I'm working on" and "mailings I don't need to worry about".

This PR only affects new installations.

Before
----------------------------------------

image

After
----------------------------------------

image

Comments
----------------------------------------

- I forgot how to run Regen.
- The "New Mailing (traditional)" was moved by the [ducttape](https://civicrm.org/extensions/duct-tape) extension.

### CODE REVIEW

**Comment by shaneonabike** [comment]
I also think that the terminology is confusing, and repetitive. A small change but actually super clear and clean.

**Comment by seamuslee001** [comment]
@agileware-justin @johntwyman do either of you have any opinions on this?

**Comment by agileware-justin** [comment]
@mlutfy here's the regen doco, https://docs.civicrm.org/dev/en/latest/framework/database/#binregensh

**Comment by agileware-justin** [comment]
@seamuslee001 I agree with any and all changes to improve the UI.

**Comment by agileware-justin** [comment]
Whilst we are here, what's with this: **New Mailing (Traditional)** - who's tradition? Are these based on the beliefs of ancient CiviCRM users? Or perhaps based on some traditional Scottish Jig?

Scottish-Jig-Sending-CiviCRM-Mailing

**Comment by johntwyman** [comment]
I definitely like the change to "Draft Mailings". I think that makes a lot of sense.

I'm on the fence about the other change. I understand the rationale but would caution that Scheduled is a distinct, meaningful status apart from Sent.

**Comment by eileenmcnaughton** [comment]
We could word-replace 'traditional' with 'Olde English' maybe?

**Comment by yashodha** [comment]
@mlutfy +1 on this. You might want to fix generated data as well. Thanks!

**Comment by homotechsual** [comment]
> I definitely like the change to "Draft Mailings". I think that makes a lot of sense.
> 
> I'm on the fence about the other change. I understand the rationale but would caution that Scheduled is a distinct, meaningful status apart from Sent.

This is a very valid point, an unscheduled mailing is absolutely still a draft. But a scheduled mailing has not been sent so either the latter link should stay as is or refactor out to three distinct links/views (if possible with just menu/link changes) - Draft, Scheduled (unsent) and Sent

**Comment by mlutfy** [comment]
> "This is a very valid point, an unscheduled mailing is absolutely still a draft."

I agree it's a valid point semantically, but I think (and bear with me), it's where CiviCRM sometimes fails: we try to be very semantically correct, and that means having a very verbose/overloaded interface that makes sense to developers but not to admins. (I don't mean to offend anyone, I'm a dev/geek and have been using CiviCRM for more than 15 years and I haven't bothered to propose to change this until now, I'd often just ducttape around these things.)

However, a Scheduled Mailing cannot be edited, so it's not like a Draft. It's really different state (which makes it a valid concern), and the interface makes that clear with different search options.

.. but is a precedent: "in progress" mailings are also a different state, and don't have a special mention in the menu. I'd argue they're probably even more important (when there's a problem).

Does it deserve a special mention in the menus? As an admin, what's the difference between scheduled and sent? What's the primary intention when I click on that? If there is no obvious answer, I prefer to keep it simple. During an initial training, very few people ask "where will my scheduled mailings be?". And once they will have sent their first mailing, it will (usually) be intuitive to them because they are redirected to the scheduled/sent mailings page.

Personally I would just have "Mailings > Dashboard", which would have a New button, and search options for draft/scheduled/sent, but I'm not into drastic changes, so I'm trying to do small iterative changes that most people won't notice (similar to #23831, no complaints so far).

**Comment by homotechsual** [comment]
> Does it deserve a special mention in the menus? As an admin, what's the difference between scheduled and sent? What's the primary intention when I click on that? If there is no obvious answer, I prefer to keep it simple. During an initial training, very few people ask "where will my scheduled mailings be?". And once they will have sent their first mailing, it will (usually) be intuitive to them because they are redirected to the scheduled/sent mailings page.
> 
> Personally I would just have "Mailings > Dashboard", which would have a New button, and search options for draft/scheduled/sent, but I'm not into drastic changes, so I'm trying to do small iterative changes that most people won't notice (similar to #23831, no complaints so far).

Fair enough

**Comment by lcdservices** [comment]
Keep in mind that with Drupal there is an option to enable an advanced workflow which adds three permissions -- create mailing, schedule mailings, and approve mailings. With that enabled, a scheduled mailing is not necessarily queued to be sent unless it has also been approved. The current scheduled and sent list is where a user with approval permission goes to review and approve a mailing.

**Comment by wmortada** [comment]
This sounds sensible to me. I'm all for keeping it simple.

**Comment by mlutfy** [comment]
Thank you everyone for the feedback.

I have rebased & regen'ed & squashed the branch. Ready for merge ;-)

**Comment by colemanw** [comment]
Word-count of PR change: 4
Word-count of PR discussion: 570 :rofl:

**Comment by wmortada** [comment]
Plus a jig.

**Pull request merged**
