### PR TITLE
(dev/core#4292) Add validation to verify html body content for empty t…

### PR DESCRIPTION
**Pull request by yashodha**
…ext/ only image in mailing

Overview
----------------------------------------
Add validation to verify html body content for empty text (if image are used) and show the error accordingly. This requirement is in place to minimize the chance of the domain being marked as spam by an internet service provider.

Before
----------------------------------------
No error thrown for no text just images

After
----------------------------------------
Voila!

### CODE REVIEW

**Comment by demeritcowboy** [comment]
I agree with the principle, but I do know there are sites that regularly send flyers where the email is just one giant jpg. They shouldn't, but they do. Perhaps it could just be a warning?

**Comment by yashodha** [comment]
@demeritcowboy Well that means they get to ignore the warning and will then face consequences. The point was to make sure they don't get to that point. I am ready to make changes if we have consensus on the warning instead of triggering the rule.

**Comment by seamuslee001** [comment]
@yashodha tho this is more than just a warning right?

**Comment by yashodha** [comment]
@seamuslee001 this is form rule and will not allow to go ahead without text avoiding future problems.

**Comment by demeritcowboy** [comment]
I'm not strongly opposed since the person could just add a `.` or something to the email and then it would validate, but on a different note, this PR is adding code to a deprecated function and only runs if not using flexmailer, which is now enabled on all sites since 5.57, so it's in the wrong spot.

**Comment by demeritcowboy** [comment]
@yashodha What do you want to do with this? This is adding code to a deprecated function that will eventually be removed.

**Comment by yashodha** [comment]
@demeritcowboy We would need to address this in the right spot in an alternate PR now that function has been deprecated.

**Comment by eileenmcnaughton** [comment]
I'm closing this cos I think it would never be hit here any more - not sure the best alternative as flexmailer confuses me

**Pull request closed without merging**
