### PR TITLE
Cleanup - Remove old unused schema/xml files.

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Delete old files from schema tables that no longer exist.

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by demeritcowboy** [comment]
This looks good. I'm not sure og-sync ever used the bridge tables, unless they were used from something external.

**Comment by colemanw** [comment]
As far as I can tell they were never used.

**Comment by demeritcowboy** [comment]
I couldn't find anything in civiverse.

**Comment by eileenmcnaughton** [comment]
I did some checks and agree these are unused

**Pull request merged**
