### PR TITLE
Add field mapping api

### PR DESCRIPTION
**Pull request by sudhabisht**
Added some addition changes to fix below fail test,
1. api_v3_MappingTest::testDeleteMappingInvalid
2. All test of api_v3_MappingFieldTest
3. CRM_Core_PseudoConstantTest:: testOptionValues

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
In general we are trying to work towards the BAO never setting session messages - but rather throwing exceptions & having the form or api deal with those appropriately (the api already has handling so it's just the form)

**Comment by eileenmcnaughton** [comment]
Is this superceded? Can it be closed?

**Comment by sudhabisht** [comment]
@eileenmcnaughton , there was one api failure which work on local.

**Comment by monishdeb** [comment]
Jenkin, test this please

**Comment by eileenmcnaughton** [comment]
OK - I thought PR 6104 might have been a replacement for this - seems it is still relevant

**Comment by kurund** [comment]
jenkins, test this please

**Comment by kurund** [comment]
jenkins, test this please

**Comment by davecivicrm** [comment]
jenkins, test this please.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
jenkins, retest this please

**Comment by colemanw** [comment]
Looks like the [syntaxConformanceTests](https://test.civicrm.org/job/CiviCRM-Core-PR/6632/testReport/junit/(root)/api_v3_SyntaxConformanceTest__testCreateSingleValueAlter/testCreateSingleValueAlter_with_data_set__57/) have picked up a regression.

**Comment by monishdeb** [comment]
Strange. It works fine for ``api_v3_SyntaxConformanceTest::testCreateSingleValueAlter with data set #57 ('SavedSearch')`` on local. Also tested rest of the functionality, working as expected.

**Comment by colemanw** [comment]
jenkins, retest this please

**Comment by colemanw** [comment]
Still getting test failures.

**Pull request merged**
