### PR TITLE
[WIP] highly contrived unit test to show passing test that should fail

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
Highly contrived example to show change in what happens during api calls when a db error occurs after https://github.com/civicrm/civicrm-core/pull/19323

Locally at least, this failed before. Now it passes. Seeing what happens here.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Log here shows: `ok 1564 - CRM_Core_SssTest::testA`

FYI @eileenmcnaughton @seamuslee001

**Comment by demeritcowboy** [comment]
If you have access to look at ConfigAndLog on the server here it should show the No Such Field error in there.

**Comment by demeritcowboy** [comment]
The other test fails here are likely because this contrived test changes the schema in a way that doesn't reset between tests. The point of this was to show that a db error during an api call now sometimes gets caught whereas before it didn't and so kind of half disappears. Possibly it could rethrow, but it maybe depends why it's catching it?

**Comment by eileenmcnaughton** [comment]
@demeritcowboy to what extent is the lack of fail ok given this is a getfields call - I suppose you could argue that the getfields should pass & skip the field & the other calls should fail

**Comment by demeritcowboy** [comment]
I can try to make up a more generic example but it should be reproducible with any api call where a db error occurs during the call, or some other pear problem.  The main thing is api calls used to let these errors percolate up because they were pear `errors`, but now they are pear `exceptions` and the api is catching them.

**Comment by eileenmcnaughton** [comment]
Hmm but the API *should* convert them to API_Exceptions - so I guess we need to fix that

**Comment by demeritcowboy** [comment]
You might be right this maybe does turn out to be more specific to `getfields`, or at least a smaller scope. I'll look closer tomorrow.

**Comment by eileenmcnaughton** [comment]
thanks

**Pull request closed without merging**
