### PR TITLE
Make flexmailer mandatory

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Make flexmailer mandatory

Before
----------------------------------------
- flexmailer optional
- setting permits fallback to 'traditional_mode`

After
----------------------------------------
- flexmailer mandatory
- fallback setting removed

Technical Details
----------------------------------------
The next challenge will be to figure out how to remove the chunks of code that this makes fully obsolete

Comments
----------------------------------------

### CODE REVIEW

**Comment by demeritcowboy** [comment]
This seems ok. I know there was some discussion in chat but I didn't follow it so not sure if there's something to look out for here.

I did have a weird experience on one run because I had happened to visit the extension page first before the upgrade (and it oddly looked installed but that's not the issue). When I then went to the upgrade screen it crashed since it couldn't find \Civi\Services\Flexmailer until I cleared cache. But I'm chalking it up to just clicking around too much.

**Comment by demeritcowboy** [comment]
Also I do still have flexmailer settings in the Admin - CiviMail menu, but not a blocker.

**Comment by seamuslee001** [comment]
My only slight hesitation on this is have we had any notices to those that have Flexmailer enabled but the setting set to bao?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 we removed the last reason to have it as BAO with the double https thing

**Comment by seamuslee001** [comment]
@eileenmcnaughton my point being is what if people had previously deliberately set it to be BAO for whatever reason this would now completely change things for them I would assume.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 yeah - the `bao` option is gone for both those people & those who don't have flexmailer - personally I only ever encountered sites with `bao` set by accident who had bugs that were fixed by turning it on - I never saw anyone suggest it as a solution to a problem ....

**Pull request merged**
