### PR TITLE
campaign cleanup for sybunt report and show disabled campaigns as well

### PR DESCRIPTION
**Pull request by yashodha**
Overview
----------------------------------------
Centralize and cleanup code for campaigns in reports and show disabled campaigns as well

Before
----------------------------------------
sybunt_before

After
----------------------------------------
sybunt_after

Comments
----------------------------------------
Inactive campaigns can be seen in report filter and results as well.

### CODE REVIEW

**Comment by yashodha** [comment]
test this please

**Comment by yashodha** [comment]
@eileenmcnaughton @seamuslee001 
clean up changes for report

**Comment by eileenmcnaughton** [comment]
Looks good to me

**Comment by yashodha** [comment]
@eileenmcnaughton thanks!

**Pull request merged**
