### PR TITLE
Remove unused extra param in getAllModulePermissions

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Remove unused deprecated function param in the permissions class.

Technical Details
----------------------------------------
This function is only called in one place and always with the same param.

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton as far as I can tell this function is only called from one place. Any reason to believe otherwise?

**Comment by eileenmcnaughton** [comment]
@colemanw 

sadly

image


- FYI I seem to recall someone working on changing that function to accept the descriptions around about the woolman sprint....

**Comment by eileenmcnaughton** [comment]
I think CiviHR is unmaintained though - possibly to the point where we can remove from universe....

**Comment by colemanw** [comment]
@eileenmcnaughton ok so this param is always TRUE except for civihr. IMO that's good enough.

**Comment by eileenmcnaughton** [comment]
OK - I'm gonna merge

@jamienovick FYI - are you able to confirm CiviHR is abandoned - if so we can stop including it in the code we search when we make changes like this

**Comment by totten** [comment]
@colemanw @eileenmcnaughton I think the other callers for `getAllModulePermissions()` are in UF integrations:

```
civicrm-joomla/libraries/joomla/form/fields/civiperms.php:    $extPerms = self::$civiConfig->userPermissionClass->getAllModulePermissions(TRUE);
civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Core/Permission/Base.php:  public function getAllModulePermissions($descriptions = FALSE): array {
civicrm-drupal-8.x/vendor/civicrm/civicrm-core/CRM/Core/Permission.php:    $module_permissions = CRM_Core_Config::singleton()->userPermissionClass->getAllModulePermissions(TRUE);
```

**Comment by colemanw** [comment]
@totten thanks for finding that. Those are all ok because they pass `TRUE` and we're just removing support for `FALSE`.

**Pull request merged**
