### PR TITLE
SearchKit - Add ability to run tasks via clicking links

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Makes it possible to use tasks and links interchangeably in SearchKit.

Before
----------------------------------------
Tasks such as "Communication Preferences - Alter" only available in the dropdown actions menu.

After
----------------------------------------
They can be added as links. The actions menu does not need to be present on the display for them to work.

image

### CODE REVIEW

**Comment by aydun** [comment]
Lots of changes!  But the end result seems to work and does what it says.

**Comment by rbaugh** [comment]
I have an issue with using this on a custom entity, which is where this originally came from. When using a built-in entity, the link is working correctly. But when I try and use, say the delete action, it is just taking me to the CiviCRM home page. 

If I use the "Actions" menu, I can delete a specific item by selecting the checkbox and then using the "Actions" delete menu item. But the new link is not working.

Is there something that needs to be set up on the custom entity side to make this work?

**Comment by rbaugh** [comment]
Overall, I don't think there is a "/manage" endpoint on the custom entity. I had set up a FB form and created a custom url with "/manage" and I kept getting the FB form when using the delete action. So I changed my FB url to see if that would help, and I just get the CiviCRM dashboard page since the endpoint doesn't exist.

**Comment by colemanw** [comment]
@rbaugh as far as I can tell this is working with custom entities. My steps to reproduce:

1. Download and enable the [`ECK` extension](https://github.com/systopia/de.systopia.eck).
2. Add a custom entity type + subtype
3. Create a couple test records of the custom type
4. Open SearchKit and search for entities of that new type
5. Add a search display
6. Add a "buttons/links/menu" to the display
7. Enable "Delete" as a link
8. Preview the display, try the delete button. It will pop up the bulk-delete action with a single record selected, and will successfully delete the record when you tell it to.

image

**Comment by rbaugh** [comment]
On a clean install of our extension, I was able to confirm this was working as expected.

**Pull request merged**
