### PR TITLE
AdminUI: Migrate LabelFormat from SearchUI to AdminUI

### PR DESCRIPTION
**Pull request by aydun**
Overview
----------------------------------------
Move the LabelFormat listing from SearchUI to AdminUI.

Before
----------------------------------------
`civicrm/admin/labelFormats` is old
image

After
----------------------------------------
`civicrm/admin/labelFormats` is SK & FB when AdminUI is enabled.
image

Comments
----------------------------------------
The original screen conflates 2 option groups into one table, making the ordering a bit nonsensical.
This splits them into 2 tabs for clarity.

### CODE REVIEW

**Comment by colemanw** [comment]
@aydun SearchKit does support drag-n-drop ordering of option values.

**Comment by aydun** [comment]
> @aydun SearchKit does support drag-n-drop ordering of option values.

Yes, but it's not showing up on this search. Maybe because it's starting from Option Group rather than Option Values.

Probably best if I just rebuild this search.

**Comment by aydun** [comment]
@colemanw I've rebuilt this starting from OptionValues and drag and drop ordering now works.  That looks odd when different types (option groups) are in the same display so I've used the tabs approach to separate them.  However, the Add button does not show up in the tabs.

**Comment by colemanw** [comment]
@aydun there was just a small problem in your add link (probably end-of-sprint fatigue) which I've fixed.
Tested this and it works quite well. MOP.

**Comment by colemanw** [comment]
retest this please

**Comment by aydun** [comment]
Thanks for those fixes @colemanw !

Test fails look to be infrastructure.  Test this please

**Comment by colemanw** [comment]
Infrastructure also has end-of-sprint fatigue. I just merged it anyway.

**Comment by aydun** [comment]
Thanks @colemanw

**Pull request merged**
