### PR TITLE
CRM-20864 - install/index - add database name and port parameter

### PR DESCRIPTION
**Pull request by Armfoot**
1. adds the database name to all invocations of the recently introduced
connect function;
2. adds the `$port` parameter to the connect function with `NULL` as default
value (avoiding the specific else block for this assignment).

---

 * [CRM-20864: Add database value for connect function in install\index.php](https://issues.civicrm.org/jira/browse/CRM-20864)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @totten I believe this is a fix to the recent regression - but I'm not  sure if there hasn't been a fix merged in the meantime that makes this redundant?

**Comment by seamuslee001** [comment]
Jenkins ok to test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton i think this picks up the fix that Totten merged in and re-does it a little, I'm not sure about adding database name but i guess that seems sensible here

**Comment by eileenmcnaughton** [comment]
OK- I think I'd like to see @totten weigh in since I didn't follow the issue that happened too closely

**Comment by eileenmcnaughton** [comment]
@totten do you think this is obsolete now?

**Comment by totten** [comment]
Maybe?

@Armfoot , I was reading the well-investigated https://civicrm.stackexchange.com/a/19405/93, and it describes a few possible changes (including this approach and including a`$port=NULL` approach -- the `$port=NULL` change was merged in the intervening period). However, the article suggests that passing through a `$database` might be more correct.

Could you explain that a little more? e.g. are there are some edge-cases that would work better with this patch, or is the difference more aesthetic?

**Comment by eileenmcnaughton** [comment]
I'm going to close this because it's blocked pending a response to @totten question from @Armfoot & has been for quite a while. I think in cases like these it's better to close & then get @Armfoot to re-open when ready, since that also gives it more prominence when re-opened

**Pull request closed without merging**
