### PR TITLE
dev/core#5141 - Fix non-selectable select2 in 'Clone Report' popup

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes https://lab.civicrm.org/dev/core/-/issues/5141

Before
----------------------------------------
Cannot select navigation in "Clone Report" popup.

After
----------------------------------------
Works.

Technical Details
----------------------------------------
This partially reverts 8eb6aa4.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@larssandergreen FYI

**Comment by demeritcowboy** [comment]
I see it's only in the popup version, when done from the report itself. If you do it from the report listing it's ok.

A secondary thing though - not sure if this was working earlier - when you use the popup version, the checkbox for "Include in reports menu" doesn't get checked, so the parent menu field is meaningless unless you go edit the report after and check that box.

**Comment by colemanw** [comment]
> @demeritcowboy A secondary thing though - not sure if this was working earlier - when you use the popup version, the checkbox for "Include in reports menu" doesn't get checked, so the parent menu field is meaningless unless you go edit the report after and check that box.

Hmm, any idea how that can be fixed?

**Comment by demeritcowboy** [comment]
> any idea how that can be fixed

Use searchkit?

**Pull request merged**
