### PR TITLE
Add hook to alter display value or Custom field value

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
Add hook to alter display value or Custom field value

Comments
----------------------------------------
There is no specific hook to alter the display of custom field value unless we use some jquery. This hook will provide ability to alter the display of the custom field value like adding html tags, manipulating labels based on value etc

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
Is this different from `hook_civicrm_fieldOptions` because it will work on non-option value fields?

**Comment by eileenmcnaughton** [comment]
@josephlacey any impact on your stuff?

**Comment by eileenmcnaughton** [comment]
@pradpnayak we better get a test on it so we don't break it if we are adding a hook

**Comment by pradpnayak** [comment]
@MegaphoneJon I agree with you that hook_civicrm_fieldOptions() can be used to manipulate the labels. However in some scenarios its not feasible to generate the field options array with 10k records incase of reference field. CiviCRM doesn't provide custom field with entity ref but via code either using buildform or alterEntityRefParams hooks we can change the html type of the field or api params. 

Scenarios like having autocomplete custom field, changing to api param to use Event, Contribution as entity or loading options from external site using their rest api. 

This hook mainly allow to rewrite the display value for custom field for above scenario or if the label needs to be converted into anchor tag or needs to be highlighted etc

**Comment by jaapjansma** [comment]
Betty and I are reviewing PR's and we started with the ones which are updates least recently. And we found this issue.

Our main comments are:
* From the description it is unclear what problem is being solved (I can deduct this as a developer but it is not explained)
* And the documentation is still missing. 

@pradpnayak are you still going to add documentation for the hook? If not I will advice to close this PR. 
If you don't react I assume no further work will be done on this.

**Comment by jaapjansma** [comment]
We will close this PR.

**Pull request closed without merging**
