### PR TITLE
CRM-19354 fix fatal on pdf generation if no trxn_id exists

### PR DESCRIPTION
**Pull request by lcdservices**
- [CRM-19354: receipt PDF generation error](https://issues.civicrm.org/jira/browse/CRM-19354)

### CODE REVIEW

**Comment by yashodha** [comment]
@lcdservices : Can you please fix style errors as per
https://test.civicrm.org/job/CiviCRM-Core-PR/11603/checkstyleResult/new/

**Comment by lcdservices** [comment]
I've updated to address that line.

**Comment by yashodha** [comment]
Jenkins test this please

**Comment by yashodha** [comment]
unrelated failure

**Pull request merged**
