### PR TITLE
Add missing state for South Korea

### PR DESCRIPTION
**Pull request by jgrygierek**
There is a missing state for South Korea, added according to: https://www.iso.org/obp/ui/#iso:code:3166:KR.

### CODE REVIEW

**Comment by colemanw** [comment]
@civicrm-builder add to whitelist

**Comment by colemanw** [comment]
This PR looks good, thanks!
One nitpick: the comment in the upgrade file makes sense, but the comment you added to `civicrm_state_province.tpl` is just noise. If we added a comment for every minor change we made to our codebase, there would be millions and millions of "added a line" or "removed a line" comments and our code would be unreadable!

Ideally this PR should be a single commit rather than 2 or 3. We usually use `git rebase` or `git commit --amend` and then `get push --force` to clean up and squash commits for a PR.

**Comment by jgrygierek** [comment]
> One nitpick: the comment in the upgrade file makes sense, but the comment you added to `civicrm_state_province.tpl` is just noise. 

There are similar comments in this file, so I just added another one. But I can remove it if you want.

**Comment by colemanw** [comment]
> There are similar comments in this file, so I just added another one. But I can remove it if you want.

Yes our code is messy in places but we are trying to clean it up and prevent it from getting messier :)

**Comment by eileenmcnaughton** [comment]
I'm gonna merge this & just do a separate PR to remove the extra lines. I'm already hurt my brain on how a 'special self-governing city' fits with the concept of a state.

Thanks for the PR @jgrygierek  - if you can please do a second PR adding yourself to https://github.com/civicrm/civicrm-core/blob/master/contributor-key.yml we can credit you

**Comment by eileenmcnaughton** [comment]
Actually on looking I'm going to leave those comments there they are - there are so many in that stateCountry.tpl & some are useful so they can't really be cleaned up without a lot of time. However, the kicker is that they are grouped by country and then the later ones are obviously added when they arose - meaning that the comments do tell you something at a glance - ie the country

**Pull request merged**
