### PR TITLE
WIP Make case activity form respect the civicaseActivityRevisions setting

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
The setting `civicaseActivityRevisions` in core is ignored via the CiviCase UI and only respected when using the API:
image

This means that when administering a case with "Embedded activity revisions" enabled you lose the history when making changes to an activity.

Before
----------------------------------------
Setting in core but not respected by core UI.

After
----------------------------------------
Setting in core is respected by core UI. Do not lose data when editing activities on cases if setting enabled.

Technical Details
----------------------------------------
By switching all create calls to the API we automatically respect the setting as well as calling pre/post hooks in all cases (instead of bypasses when using the DAO directly).

Comments
----------------------------------------
For new installs it is *preferred* to use extended logging. But for existing systems it is not necessarily a simple process to change.  A core setting should work as expected in core! And for the kind of uses cases are intended losing history is a bad thing!

@demeritcowboy

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Thanks - will give it a spin.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I see there  is  an existing test - can  we edit that to cover this change?

**Comment by demeritcowboy** [comment]
I was looking at that earlier and started drafting one. That particular test is testing an activity you can't/shouldn't edit in the UI, but it's similar.

**Comment by demeritcowboy** [comment]
I'm tracking my testing and intermediate scribblings at https://lab.civicrm.org/dev/core/issues/1532

**Comment by mattwire** [comment]
Closing as tracked via https://lab.civicrm.org/dev/core/issues/1532 and @demeritcowboy has made some progress on a migration-based approach instead.

**Pull request closed without merging**
