### PR TITLE
[REF] Remove deprecated methods of booting drupal container and getti…

### PR DESCRIPTION
**Pull request by seamuslee001**
…ng drupal timezone information

Overview
----------------------------------------
This fixes a compatibility issue with Drupal 9 in that prepareLegacyRequest has been removed and also drupal_get_user_timezone has been removed infavour of date_default_timezone_get

Before
----------------------------------------
Deprecated methods used

After
----------------------------------------
Non Deprecated methods used

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
I ran a an instance of the [D8-matrix](https://test.civicrm.org/job/CiviCRM-D8-Matrix/137/) with this patched in and the results were no more meaningfully worse than before

ping @MikeyMJCO @KarinG @totten

**Comment by MikeyMJCO** [comment]
This looks good to me.

**Comment by seamuslee001** [comment]
Merging as per review from Mikey

**Pull request merged**
