### PR TITLE
APIv3 - Fix overzealous pseudoconstant matching

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes regression caused by #22282.

Before
----------------------------------------
An api3 call like this would fail due to strict case matching:
```
civicrm_api3('CustomGroup', 'get', [
  'extends' => "contact",
]);
```

After
----------------------------------------
Works fine. SQL is case-insensitive so there's no reason not to allow it.

Technical Details
----------------------------------------
Strings do not need to be strictly matched to pseudoconstants during get operations.

### CODE REVIEW

**Comment by seamuslee001** [comment]
test fails relate IMO @colemanw

**Comment by colemanw** [comment]
Ok, I've fixed one test by throwing the expected `API_Error` in that particular function. The other two tests were IMO just plain bad. They were testing a quirk of the APIv3 Contact Query Object which they expected to fail in a particular way and now it doesn't. But I see no reason why it should have failed that way, and all other tests are passing. So I removed them.

**Comment by colemanw** [comment]
Retest this please

**Comment by colemanw** [comment]
Retest this please

**Comment by colemanw** [comment]
@seamuslee001 it's passing now

**Pull request merged**
