### PR TITLE
CRM-16445 - crmUiRichtext - Fix "Source" mode. Listen to 'key' event.

### PR DESCRIPTION
**Pull request by totten**
See also:
- http://civicrm.stackexchange.com/questions/2492/civimail-mailings-not-saving-or-corrupting
- http://stackoverflow.com/questions/17358203/how-to-detect-ckeditor-source-mode-on-change-event

This is not strictly part of CRM-16445, but it's very similar (dealing with
the events emitted by ckeditor).

### CODE REVIEW

**Comment by colemanw** [comment]
This looks good to me.

**Comment by davecivicrm** [comment]
Tim - is there a 'symptom' of a problem this fixes that I can test for?

**Comment by totten** [comment]
The way I tested:
 * Create a mailing
 * Add "?angularDebug=1" to URL
 * In "HTML" area, enter some text.
   * Look in the debug panel. Note the text is there.
 * In "HTML" area, change to "Source" mode and add more text.
   * Look in the debug panel. Note the text is unchanged.

**Comment by davecivicrm** [comment]
Cool. Good catch.

**Pull request merged**
