### PR TITLE
dev/core#844 Unit test

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
This is a unit test to replicate https://lab.civicrm.org/dev/core/issues/844

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@pradpnayak jenkins is being sulky

**Comment by pradpnayak** [comment]
@eileenmcnaughton updated the unit test.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
test this please

**Comment by mlutfy** [comment]
@pradpnayak Since 844 is still open, I assume this is a test to demonstrate the bug?

Since the PR is stale I will close for now, but feel free to re-open when it's ready for a new round of review.

**Pull request closed without merging**
