### PR TITLE
(WIP) CRM-20160 - Remove restriction on which entities the Attachment api supports

### PR DESCRIPTION
**Pull request by colemanw**
* [CRM-20160: Attachment api does not work with all entities](https://issues.civicrm.org/jira/browse/CRM-20160)

### CODE REVIEW

**Comment by tunbola** [comment]
Tried this Fix on my local and was able to create an Attachment for the LeaveRequest Entity in civihr.

**Comment by colemanw** [comment]
@totten can you please review this?

**Comment by totten** [comment]
I think it's fine to continue putting discussion here, but I'm flagging this WIP because the discussion in #10010 indicates that we need major changes. If you'd rather close/reopen, that's also valid/appreciated.

**Comment by totten** [comment]
The discussion in the other PR is a bit long, but just to capture the gist of it -- `DynamicFKAuthorize::authorizeDelegate()` relies on a simulated/subordinate API call.  `DynamicFKAuthorization` uses whitelist of entities because the API call is based on soft/informal expectations. I'd expect them to hold true as a matter of best-practice, but there's no historical or design reason to think that they actually do hold across the board.

**Comment by eileenmcnaughton** [comment]
@colemanw I'm going to close this because it appears to be long-term WIP & it seems it needs major changes. There was a suggestion half a year ago to close/re-open when ready - I think that makes sense

**Pull request closed without merging**
