### PR TITLE
[WIP] Grant afform enabled

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Add afform option for Grant
    
    This isn't actually working that well for me locally but putting up as a PR to see how it works on the
    build site as my problems might be local environment related

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
OK - seeing some brokenness - http://core-19021-2j3s3.test-3.civicrm.org:8001/civicrm/admin/afform#!/?name=0

Screenshot from 2020-11-23 19-43-42

**Comment by eileenmcnaughton** [comment]
Definitely not working - but it might be more generic afform brokenness

**Comment by seamuslee001** [comment]
@eileenmcnaughton needs a rebase now

**Comment by eileenmcnaughton** [comment]
@totten @colemanw I did get this to load.... although creating a grant form broke my site - error looks familiar

Screenshot from 2020-12-01 14-26-07

**Comment by eileenmcnaughton** [comment]
OK - the gotcha is that you have to specify civicrm/ in the url.....

**Comment by eileenmcnaughton** [comment]
OK - I created the form but can't submit it because I can't add contact id to it. Tangentially the feature that felt missing was specifying a field default - I deleted all statuses but 'submitted' but the person still has to select it despite it being a required field

**Comment by eileenmcnaughton** [comment]
@totten @colemanw I'll close this since I guess it's not really intended for merge at this stage so it works as well closed as open - however, where I got to is

1) it works to create grant afforms
2) contact id is a required field so I couldn't actually get the form to submit unless I knew that

I terms of using this as a back office form 2 seemed blocking. As a front end form I suppose it could be embedded in an individual form (although I didn't figure that out) and I think there is a clear use case for a front end form to submit grant applications. However, the status thing is a bit fugly on that front (it's a required field, you can restrict the available options in afform but not make it unrequired, or fill the only option by default).

I feel like this would be useful to pursue as a simple entity - so I will close but not delete the branch

**Pull request closed without merging**
