### PR TITLE
Clean up parameters in add payment form

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Clean up parameters in add payment form

Before
----------------------------------------
The code in this form was copied from another form (back when the form was created).  A lot of the code is for the contribution to be created - but this form never interacts with the contribution create/update method - it only calls Payment.create - hence making up an invoiceID & passing it to doPayment & never using it is unhelpful. LIkewise calling the function to format contribution custom fields

After
----------------------------------------
The fields passed to the Payment.create are assembled in one place so it is clear where they are coming from

Technical Details
----------------------------------------
I'm trying to fix the fact this form doesn't create the billing address - but fighting with confusing code

Comments
----------------------------------------

### CODE REVIEW

**Comment by mattwire** [comment]
@eileenmcnaughton test fails relate

**Comment by eileenmcnaughton** [comment]
CRM_Contribute_Form_AdditionalPaymentTest::testAddPaymentForPartiallyPaidContribution
substr(): Passing null to parameter #1 ($string) of type string is deprecated

/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/CRM/Contribute/Form/AdditionalPayment.php:330
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/CRM/Contribute/Form/AdditionalPayment.php:294
/home/homer/buildkit/build/build-

**Comment by eileenmcnaughton** [comment]
cool - heaps of tests on it - hopefully that casting fixes

**Comment by eileenmcnaughton** [comment]
mixin test fails only this time - test this please

**Comment by eileenmcnaughton** [comment]
test fail unrelated test this please
                                                                               
  [PHP Warning] Undefined array key "name" at /home/homer/buildkit/build/buil  
  d-1/web/sites/all/modules/civicrm/Civi/Api4/Action/Setting/GetFields.php:44  
  [PHP Warning] Undefined array key "name" at /home/homer/buildkit/build/buil  
  d-1/web/sites/all/modules/civicrm/Civi/Api4/Action/Setting/GetFields.php:44  
  [PHP User Warning] Smarty error: unable to read resource: &quot;CRM/Shimmy/  
  Example.tpl&quot; at /home/homer/buildkit/build/build-1/web/sites/all/modul  
  es/civicrm/packages/Smarty/Smarty.class.php:1100                             
  [PHP User Warning] Smarty error: unable to read resource: &quot;CRM/Shimmy/  
  Example.tpl&quot; at /home/homer/buildkit/build/build-1/web/sites/all/modul  
  es/civicrm/packages/Smarty/Smarty.class.php:1100                             
  Skip. No tests found for theme-php@1                                         
  Error processing mixins: setting-admin@1

**Pull request merged**
