### PR TITLE
CRM-21722 Check configuration of payment processors when saving config

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
This implements a simple method to check payment processor configuration by executing the existing checkConfig() method and displaying any errors via the Payment processor configuration UI.  Previously checkConfig was only executed (silently) when actually loading the processors on the page and the errors were never used (or seen).  This resulted in payment processors seemingly missing from contribution pages with no indication as to why.
If errors are detected you will now be bounced back to the processor config page (press cancel if you don't wish to configure everything at this point).

@eileenmcnaughton @seamuslee001 This should be a simple one to review and shouldn't break anything important :-)

---

 * [CRM-21722: Payment processor check configuration](https://issues.civicrm.org/jira/browse/CRM-21722)
localhost_8000_civicrm_admin_paymentprocessor_reset 1 action update id 5

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
The change makes a lot of sense. 

The refreshUrl stuff seems unwieldly & I don't fee we use that pattern a lot - is all that refreshUrl stuff required because we should really do this in the validate function?

**Comment by seamuslee001** [comment]
Also what does the "The Warning Message hasn't been saved" thing mean. I agree that the changes make sense. @eileenmcnaughton i think we would need to check the template as well if we wanted to hack at the refreshUrl stuff given it is assigned as a smarty var

**Comment by mattwire** [comment]
@seamuslee001 Ignore "The warning message hasn't been saved", it's from an extension (civisubscription) that I had enabled and you won't see it when testing this patch.

@eileenmcnaughton We can't call checkConfig() in formrule (the validate function) because the payment processor needs to be saved first.  So we call it in postprocess and redirect back to the payment processor config (via refreshURL) if there are errors.
I did not like the name "refreshURL" either, but I just used the existing variable that was already being assigned to the smarty template.  If there is a more standard pattern I'm happy to tidy this up and the template too.

**Comment by eileenmcnaughton** [comment]
@mattwire OK - that seems reasonable - there might be a cleaner way but it does seem like more work to find it than seems warranted - merging

**Pull request merged**
