### PR TITLE
CRM-20046 - better output for recently viewed list

### PR DESCRIPTION
**Pull request by seancolsen**
Full details in [CRM-20046](https://issues.civicrm.org/jira/browse/CRM-20046).

### CODE REVIEW

**Comment by seanmadsen** [comment]
@xurizaemon you might like to review this

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
This looks good to me, Also tested this on AUG sandbox and indeed fixes the problem ping @totten

**Comment by totten** [comment]
jenkins, add to whitelist

**Comment by totten** [comment]
Thanks @seamuslee001 . Agree. Flagging merge-on-pass.

**Comment by seamuslee001** [comment]
@totten @eileenmcnaughton test failures are unrelated can be merged

**Pull request merged**
