### PR TITLE
Unit tests for 22429 and apply same treatment to other money format functions

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
Unit tests for https://github.com/civicrm/civicrm-core/pull/22429

This will fail at the moment since the fix isn't upmerged to master yet, but that's good since it shows the issue.

### CODE REVIEW

**Comment by seamuslee001** [comment]
ok forward port has now been done, so confirmed it failed before forward port and now re-running

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by colemanw** [comment]
retest this please

**Comment by demeritcowboy** [comment]
This test passes locally. Will try just rebasing.

**Comment by demeritcowboy** [comment]
Oh it's the moneyNumber() function that's failing. That function doesn't seem to be used anywhere but maybe needs the same treatment as money().

**Comment by demeritcowboy** [comment]
Have updated and applied the same empty-ish checks to the other functions that the test exposed.

**Comment by seamuslee001** [comment]
Looks good to me IMO

**Pull request merged**
