### PR TITLE
Refactor CRM_Core_BAO_Email to use DAO::writeRecord

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Part of an ongoing refactoring process to deprecate `create`, `add` and `del` BAO functions in favor of the generic `writeRecord` & `deleteRecord` + hooks.

Before
----------------------------------------
Old code pattern, email BAO doesn't support saving custom data.

After
----------------------------------------
New pattern, supports custom data.

### CODE REVIEW

**Comment by colemanw** [comment]
Thanks for the review @aydun agreed to merge. To your questions:
1. It would also require core forms so support it, including the inline "emails" form on the contact summary screen, so it would be a bit more work than just adding that line.
2. I recently noticed that too. I'll check it.

**Comment by aydun** [comment]
Re 1: Ok, yes it would require more work for core forms.  I was thinking of API usage, but it probably makes sense for the custom fields to show in the UI in the right places if it is enabled by default.  As it is, you have to enable it if you want it and so know it may not be fully supported in the UI.

**Comment by colemanw** [comment]
@aydun I've followed up with #25944

**Comment by aydun** [comment]
@colemanw Great - I've also tested that.

**Pull request merged**
