### PR TITLE
Some extra tidy up ExportComponents function. 

### PR DESCRIPTION
**Pull request by seamuslee001**
Just splitting out a further two sections of the Export Components function which appear to be easily able to be spun out into their own functions

### CODE REVIEW

**Comment by davecivicrm** [comment]
@seamuslee001 I applied this PR. Then with sample DB did:
- Advanced Search
- Filter by Address > State = CA
- Export (all rows) => Select Fields to Export
- Display Name + Current Employee
Export looked fine, but on next page load got these notices:
Notice: Undefined variable: query in CRM_Export_BAO_Export::getGroupBy() (line 177 of /Users/dgg/git/crm_v4.7/CRM/Export/BAO/Export.php).
Notice: Trying to get property of non-object in CRM_Export_BAO_Export::getGroupBy() (line 177 of /Users/dgg/git/crm_v4.7/CRM/Export/BAO/Export.php).
Notice: Undefined variable: groupBy in CRM_Export_BAO_Export::getGroupBy() (line 203 of /Users/dgg/git/crm_v4.7/CRM/Export/BAO/Export.php).

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@davecivicrm Dave i think this is ready for another test

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by davecivicrm** [comment]
Jenkins, ok to test.

**Comment by totten** [comment]
jenkins, test this please

**Comment by davecivicrm** [comment]
Jenkins, retest this please.

**Comment by davecivicrm** [comment]
Retested the new commit and it looks good. Thanks @seamuslee001

**Pull request merged**
