### PR TITLE
(NFC) Expand unit test to show off double protocol error

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
Adds in a unit test to prove the problem here https://github.com/civicrm/civicrm-core/pull/14128

Before
----------------------------------------
No test

After
----------------------------------------
Test

ping @eileenmcnaughton @agilewarealok

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I guess you means you will merge that one then - this can be merged once that fixes it

**Comment by seamuslee001** [comment]
@eileenmcnaughton yep merged the other, i expanded this one a bit as the CKEditor has an "Other" protocol which basically doesn't add anything so this tests that it correctly works with other + a specific protocol set

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
test should now pass as #14128 has been merged

**Pull request merged**
