### PR TITLE
Fix CKEditor5 link editing in modal dialog

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes https://lab.civicrm.org/extensions/ckeditor5/-/issues/4

Before
----------------------------------------
Editing links broken for wysiwyg within popup dialog.

After
----------------------------------------
Fixed.

Technical Details
------------
See https://api.jqueryui.com/dialog/#method-_allowInteraction

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Oh wow - I totally didn't expect that to be a core fix

**Comment by colemanw** [comment]
Some of this low-level configuration stuff in jQuery UI can only be overridden once. It's not a hook or event that an extension can subscribe to.

**Comment by seamuslee001** [comment]
On my initial testing this is looking good

**Comment by seamuslee001** [comment]
This works for me merging

**Pull request merged**
