### PR TITLE
dev/core#597 Fix broken api get filter on financial_type

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fixes filter on 'name' being mishandled in FinancialType.get call

Before
----------------------------------------
Using name filter results in no results returned

After
----------------------------------------
Filter works correctly

Technical Details
----------------------------------------
The pseudoconstant on the field was causing a transformation of input that was not correct. I removed the pseudoconstant & updated the getLabel calls to use the pseudoconstant for the field they actually relate to

Comments
----------------------------------------
@mattwire can you check this doesn't break your fix. This should be back-ported to 5.8 once merged

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire this needs you to check / input

**Comment by seamuslee001** [comment]
I tested the change to FinancialType locally and confirmed it fixes the API. However haven't tested the premiums stuff

**Comment by seamuslee001** [comment]
@eileenmcnaughton i have also now tested the premiums pages and it looks good to me

**Comment by seamuslee001** [comment]
Given Matt's Comment in product maintenance and my testing i'm going to merge this

**Pull request merged**
