### PR TITLE
Resolve a conflict with Wordpress CSS

### PR DESCRIPTION
**Pull request by vingle**
Overview
----------------------------------------

Issue was affecting menu item wrap/overflow, described here: https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/issues/192.

Before
----------------------------------------
image

After
----------------------------------------
image

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@kcristiano this is one of 2 prs (the other being https://github.com/civicrm/civicrm-core/pull/14563 ) that seem like they probably should be against master as they appear to be not recent regressions (the criteria for the rc). 

However, both seem fairly minor & like good changes and I'm wavering.  I feel like if we are going to consider permitting either into the rc (rather than master) we should consider both - so my question is how far have you gotten with your rc testing. What I really don't want to do is invalidate the rc testing you have done. We can push these to master if you have any doubts about feeling comfortable with letting the changes into the rc.

**Comment by kcristiano** [comment]
@eileenmcnaughton It's a very minor change.  I don't believe it will invalidate the testing as it's a minor change.   I am about 50-60% of the way through so we can add now and it will get good coverage.

I don't think it's a recent regression, I think the GDPR extension added the long links, and the WP css forced `nowrap` for quite some time.   All that said I am fine with this going in the RC.

I have tested this change in Drupal, Joomla and WP but only on the Contact Summary screen.   I think we should merge, I'll update my RC sites  and that way we will get further testing as I go through teh rest of the [list](https://lab.civicrm.org/dev/rc/issues/6)

**Comment by eileenmcnaughton** [comment]
@kcristiano OK - I'm going to merge based on your recommendation (& wordpress expertise). While it is not a criteria for decisions like this I would also note @vingle put up this fix in response to being pinged on chat as a community minded help effort.

**Comment by eileenmcnaughton** [comment]
I would also note I consider both @kcristiano & @vingle to be subject matter experts in WP styling

**Pull request merged**
