### PR TITLE
CRM-17832 - Fix method call to Redis

### PR DESCRIPTION
**Pull request by colemanw**
https://issues.civicrm.org/jira/browse/CRM-17832

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
In order to test this I 
- installed redis server  & started it
- installed phpredis the php client. 
- added the following to civicrm.settings.php 
define('CIVICRM_DB_CACHE_CLASS', 'Redis');
define('CIVICRM_DB_CACHE_PORT', 6379)

On flushing the caches (through Admin->system settings->Cleanup caches & update paths I experienced the fatal error as described & the test fixed as described.

I also hit an enotice which I will push a patch for

**Comment by eileenmcnaughton** [comment]
Actually the e-notice was all me

**Comment by totten** [comment]
@eileenmcnaughton, nice notes about testing! All of us who merge/review should keep notes like that.

**Comment by eileenmcnaughton** [comment]
@totten  so here's the thing - how do we now deal with minor changes that come out of QA - ie. this is my proposed patch based on the QA I did on this issue  https://github.com/civicrm/civicrm-core/pull/8111

**Comment by totten** [comment]
@eileenmcnaughton - If making a PR that's a follow-up, I'd include a note in the new PR. "This is a followup to #99999" and merge or close the old one (to taste). In the title or labels, maybe put a word like "[FOLLOWUP]"?

In terms of the spreadsheet... putting the item on the spreadsheet is a judgement call. Don't want to make the process too cumbersome.

**Pull request merged**
