### PR TITLE
dev/core#4377 Disable broken Also Include for event scheduled reminders

### PR DESCRIPTION
**Pull request by larssandergreen**
Overview
----------------------------------------
Follow up to #23101. Also Include did not actually work for event scheduled reminders, but it will still an available option through Manage Event.

Before
----------------------------------------
Also Include enabled from Manage Event.

After
----------------------------------------
Also Include disabled from Manage Event. Also added help text and added a missing ts.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw I think you made this stale - did you address the stuff it covers?

**Comment by larssandergreen** [comment]
I'll look at this again, I don't think @colemanw's PR covers this (except coincidentally for one file).

**Comment by larssandergreen** [comment]
@eileenmcnaughton Pushed a new version.

There is also an issue with a warning about the location of the hlp, which was moved in one of the PRs since this one. I'll deal with that in a separate PR once this is merged.

**Comment by larssandergreen** [comment]
Jenkins test this please

**Comment by eileenmcnaughton** [comment]
OK - this seems a consensus position from the discussion on the other PR so merging - thanks @larssandergreen

FYI @MegaphoneJon

**Comment by colemanw** [comment]
Cool. I'm currently working on rewriting this form and my local WIP deletes all of that godawful javascript. No harm merging this as a stopgap though.

**Pull request merged**
