### PR TITLE
Flexmailer - Enable `traditional` mailing support by default

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Switches to defaulting to flexmailer, if enabled.

This should be merged in conjunction with https://github.com/civicrm/civicrm-core/pull/19806
in order to keep those on the default in consistent state
(ie they will already be getting display-rendering for custom fields
and that will still be the case if 19806 is merged)

Before
----------------------------------------
If not otherwise set flexmailer defaults to using Mailing_BAO classes

After
----------------------------------------
If not otherwise set flexmailer defaults to flexmailer class

Technical Details
----------------------------------------
Step towards only having one code path to maintain

Comments
----------------------------------------

### CODE REVIEW

**Comment by totten** [comment]
This is a good idea and agree with linking it to #19806.

One small observation - the idea behind `default=>auto` is that the sysadmin specifically defers to upstream. I used this pattern because I expected we would want to flip the default at some point. Right now, the [effective interpretation of auto](https://github.com/civicrm/civicrm-core/blob/f93358e1a901fa8c927767c7af87961ca742a023/ext/flexmailer/src/Listener/Abdicator.php#L42-L57) is "Use `bao`". But we could change it to mean "use `flexmailer`".

If the only concern is new installations, then `default=>flexmailer` and `default=>auto[aka flexmailer]` are the same. The difference is for existing sites that are aligned with the default. (*You might call these agnostic configurations.*) Depending on utter happenstance, some agnostics have blank/omitted `civicrm_setting` (*ie they track the metadata-default*) while others have `civicrm_setting` persisted with the old default (*so they don't track metadata-default*). 

IMHO, `default=>flexmailer` maybe makes sense if the intent is to leave some agnostics on `bao`. But if the idea is to flip all agnostics to `flexmailer`, then `default=>auto[aka flexmailer]` would be more effective.

**Comment by eileenmcnaughton** [comment]
@totten OK - I think switching auto over makes more sense - where would we make that change

**Comment by totten** [comment]
@eileenmcnaughton Since we've merged the token fix, I've pushed up the revision for how to flip the interpretation of `auto`.

**Comment by eileenmcnaughton** [comment]
Looks good - this is now Tim's change & I am the review so MOP

**Pull request merged**
