### PR TITLE
Replace $db_config['server'] by $db_config['host']

### PR DESCRIPTION
**Pull request by GuGuss**
The $db_config['server'] is wrong and ends up in "Could not connect to database."

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
(the previous comment was an instruction to Jenkins to run tests on the patch - I don't know about the appropriateness of the change but @totten should be able to advise.

Note that you should log a JIRA ticket for any proposed changes - https://issues.civicrm.org/jira/secure/Dashboard.jspa

JIRA is the place to explain why you think a change is required and also potentially get feedback on whether it is appropriate (although that is also done on PRs & the distinction between what discussion happens on the PR & what happens on the ticket is pretty organic)

**Comment by totten** [comment]
I tried using grep to figure out how the function is called, and it looks like `checkMysqlThreadStack` <= `$database_checks` <= `checkDatabase` <= `install/index.php`, which in turn constructs `$databaseConfig` using

https://github.com/civicrm/civicrm-core/blob/master/install/index.php#L109
https://github.com/civicrm/civicrm-core/blob/4.6/install/index.php#L79

There do appear to be a few different ways that `$databaseConfig` could be initialized, but the immediately visible ones use `server` instead of `host`, which is consistent with the old code.

@GuGuss , assuming that `host` is used in some cases... could you figure out what these cases are where it changes between `server` and `host`, and how to reconcile them?

**Comment by eileenmcnaughton** [comment]
jenkins, add to whitelist

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
jenkins, add to whitelist

**Comment by eileenmcnaughton** [comment]
Note we are no longer merging to master so this would need to be merged into master before it could be considered for 4.6.

I would probably suggest to close it until it's in master to keep the PR list more skimmable - unless you plan to work on it pretty soon.

**Comment by totten** [comment]
FWIW, I had a use-case where this came up -- testing the new `drupal8-clean` build profile on MAMP/OSX with MySQL using an alternate port (ramdisk config). Not sure yet if this is the solution (b/c there were other problems in that config), but thought it was worth noting.

**Comment by eileenmcnaughton** [comment]
I've created this JIRA to track this

https://issues.civicrm.org/jira/browse/CRM-18653

I'm going to close this PR for now as it needs to be QAd & merged against master before we can look at it on 4.6 - please create a new PR against master if this is still valid - or update the JIRA with any notes

**Pull request closed without merging**
