### PR TITLE
Full-text search for Activities in Advanced Search form.

### PR DESCRIPTION
**Pull request by quoma**
Implemented the functionality to search activities by a text query and operator ("Contains", "Starts with", etc.) in Advanced Search form.

### CODE REVIEW

**Comment by quoma** [comment]
@civicrm-builder I don't think so, needs a code review.

**Comment by quoma** [comment]
@civicrm-builder, it needs a code review

**Comment by colemanw** [comment]
jenkins add to whitelist

**Comment by colemanw** [comment]
@quoma - civicrm-builder (aka jenkins) is a bot ;)

**Comment by agh1** [comment]
Jenkins, retest this please

**Comment by agh1** [comment]
@quoma I'm going through a number of open PRs that may be considered for 4.7.8, and to be considered, this will need the tests to be passing.  It looks like you've just got style problems such as lacking empty lines between the `break`s within your `switch`, extra spaces, missing spaces, and so forth.  Please [read the checkstyle warnings](https://test.civicrm.org/job/CiviCRM-Core-PR/9278/checkstyleResult/new/) (use the Details tab to see the actual issues and line numbers). 

If you can commit your fixes in the next couple of days and the tests pass, we'll be able to consider it for merging this month.

**Comment by JoeMurray** [comment]
Heh @quoma thanks for all your contributions. As Release Manager this month, I'm trying to recruit people to help pare down the backlog of almost 100 PRs, some going back to last summer. I'm wondering if you would be able to help QA another PR if I got someone to QA this PR?

**Comment by JoeMurray** [comment]
@quoma could you create an issue in JIRA indicating what you intended this PR to do it would be easier . Thanks.for it to be QA'd.

**Comment by JoeMurray** [comment]
@anuditverma would you be interested in QA'ing this PR?

**Comment by JoeMurray** [comment]
@anuditverma, as you haven't responded, I'm going to have @bsilvern take a look at this PR. Let me know if you would have time to work on reviewing something next week in the release candidate.

**Comment by bsilvern** [comment]
QA Review: This new feature creates in the Activities section of the Advanced Search page a mode selection drop-down with nine search modes and a search string text box, providing comprehensive text search capabilities for activities. I focused my testing only on activity types Phone calls, Emails, and Tell a friend (out of around 70 defined activity types) for 27 tests in total, in addition to additional random poking around.

Generally, this PR performs as expected, but I noted the following issues for which there is room for improvement:

1.	A Help popup should be added to explain:
●	Which fields are searched in each activity type. Those seem to include subject and details, but not location. I did not attempt to test other fields than those three.
●	Any known quirks or limitations (see below).
●	A reminder of the RegEx characters which have special meaning and therefore need to be escaped might be useful.

2.	Searching with modes "Does not contain", "Does not start with" and "Does not end with": NULL text fields are not matched.
Not sure if this is a bug or a feature, but it was not what I expected and should be explained in the Help.

3.	Searching with "Contains all the words" mode: Matches if all words appear anywhere within the searchable fields of an activity (not necessarily with all search word in a single field). Not unexpected, but not obvious. Should be mentioned in the Help.

4.	HTML fields, e.g. Details field of Email or Phone call activity, cause unexpected behavior in the following search modes:
●	Starts with
●	Does not start with
●	Ends with
●	Does Not End with
●	RegEx expressions that involve ^ (beginning of string) or $ (end of string).
This is due to the implicit `<p>` and `</p>` that surrounds each paragraph.
I found that `^.{3}start_of_text` did match in my test cases, but I was unable to explicitly match the HTML characters. Using `^<p>start_of_text`, for example, resulted in no matches and `^&lt;p&gt;start_of_text` was displayed in the search box after the search. I also tried `^\<p\>start_of_text`, also receiving no match, and resulted in `^\&lt;p\&gt;start_of_text` displayed in the search box.
Similarly, I found that `end_of_text.{6}$` matches, presumably due to the implicit `</p>\r\n` at the end of the string.
Matching would similarly be expected to fail due to any other HTML tags embedded within the otherwise matching text.
To add a layer of confusion to this, angle brackets in HTML are stored inconsistently in civicrm_activity. Assume CKeditor shows the text value in SOURCE mode as `<p>Hello <strong>Bob</strong></p>`.
This is stored in civicrm_activity as `<p>Hello &lt;strong&gt;Bob&lt;/strong&gt;</p>`
Note that while `<p>` is stored as `<p>`, `<strong>` is stored as `&lt;strong&gt;`. Argh!

5. Other problematic characters: Apostrophes in HTML fields are not matched by an apostrophe in the search box as they are stored as `&#39;`. I did not test other non-alphanumeric characters. Matching on special characters could possibly be improved by a transliterating operation on the search string prior to the query, but this is complicated by the inconsistent encoding methods used in each field. In any case, any special characters which behave unexpectedly should be documented in the Help. 

6. "OR" mode: This PR did not function as I expected in OR mode, but then neither did version 4.7.8 without this PR. For example, with OR mode selected I searched activities for Subject=Bob, Has Followup Activity=No, Activity Status=Cancelled. I got 0 results returned which is not the expected result as there were activities which met some of the criteria. The search performed seems to be an AND of the criteria, despite the message provided: 
`Activities without Followup Activities ...OR...`
`Subject Like %Bob% ...OR...`
`Activity Status In Cancelled`
Searching activities in OR mode therefore appears to be broken, and this prevented testing this PR in that mode.
Submitted [CRM-19010](https://issues.civicrm.org/jira/browse/CRM-19010).

In conclusion, the primary issue with this PR is that searches on HTML text fields may return unexpected results due to the HTML tags and encoding of certain characters. Possible solutions include:
●	Strip each field of tags and fix character encoding on the fly during the search. Probably a significant performance hit.
●	Strip HTML tags and fix character encoding when saving activity details. I'm not sure what the implications of this might be. Does this field need to contain HTML?
●	Add a details_text field to the table and a trigger to ensure that it stays sync'd with the details field. Would increase the DB size while providing little benefit to most users.
●	Leave it as-is, but well-document the quirks of HTML searches in the Help. Most users of course will never read the Help, even when they don't get the expected results. Some may not even realize the results are wrong.

Note that these same issues currently exist in Full Text Search or Search Builder when performing a search on activity details.

**Comment by JoeMurray** [comment]
@bsilvern could you clarify if all of the concerns you have regarding functionality are ones that are already present with Full Text Search and activity Search Builder results? If so, it might be useful to create a separate issue to modify the functionality for all of them together so that there are consistent results between different approaches. 

@quoma would you be able to address the issues identified by @bsilvern in time for next month's merge? We're starting to identify potential PRs to merge in July, and it would be great to see this one included.

**Comment by bsilvern** [comment]
@JoeMurray: Yes, HTML fields do present a problem when using any of the search methods.

<table border=0 cellpadding=0 cellspacing=0 width=911 style='border-collapse:
 collapse;table-layout:fixed;width:684pt'>
<tr height=17 style='height:12.75pt'>
  <td align="center" align="center" height=17 class=xl69 width=64 style='height:12.75pt;width:48pt'>Issue</td>
  <td align="center" class=xl70 width=234 style='width:176pt'>Description</td>
  <td align="center" class=xl70 width=156 style='width:117pt'>Advanced Search (PR-7833)</td>
  <td align="center" class=xl70 width=187 style='width:140pt'>Search Builder</td>
  <td align="center" class=xl70 width=206 style='width:155pt'>Full Text Search</td>
 </tr>
 <tr height=68 style='height:51.0pt'>
  <td align="center" height=68 class=xl66 style='height:51.0pt'>1</td>
  <td align="center" class=xl65 width=234 style='width:176pt'>Help</td>
  <td align="center" class=xl67 width=156 style='width:117pt'>Needed</td>
  <td align="center" class=xl67 width=187 style='width:140pt'>Yes, refers to
  <a href="https://book.civicrm.org/user/current/the-user-interface/searching">Civi book</a></td>
  <td align="center" class=xl67 width=206 style='width:155pt'>Yes</td>
 </tr>
 <tr height=51 style='height:38.25pt'>
  <td align="center" height=51 class=xl66 style='height:38.25pt'>2</td>
  <td align="center" class=xl65 width=234 style='width:176pt'>&quot;Does not contain&quot;,
  &quot;Does not start with&quot; and &quot;Does not end with&quot;: Match Null
  fields</td>
  <td align="center" class=xl67 width=156 style='width:117pt'>No</td>
  <td align="center" class=xl67 width=187 style='width:140pt'>N/A</td>
  <td align="center" class=xl67 width=206 style='width:155pt'>N/A</td>
 </tr>
 <tr height=51 style='height:38.25pt'>
  <td align="center" height=51 class=xl66 style='height:38.25pt'>3</td>
  <td align="center" class=xl65 width=234 style='width:176pt'>&quot;All the words&quot;:
  Matches if words appear in any searched field in any combination.</td>
  <td align="center" class=xl67 width=156 style='width:117pt'>Yes</td>
  <td align="center" class=xl67 width=187 style='width:140pt'>N/A</td>
  <td align="center" class=xl67 width=206 style='width:155pt'>N/A</td>
 </tr>
 <tr height=51 style='height:38.25pt'>
  <td align="center" height=51 class=xl66 style='height:38.25pt'>4a</td>
  <td align="center" class=xl68 width=234 style='width:176pt'>RegEx: ^ and $: Match only with
  wildcards due to implicit HTML tags, e.g. &lt;p&gt;</td>
  <td align="center" class=xl67 width=156 style='width:117pt'>Yes</td>
  <td align="center" class=xl67 width=187 style='width:140pt'>Yes</td>
  <td align="center" class=xl67 width=206 style='width:155pt'>N/A</td>
 </tr>
 <tr height=34 style='height:25.5pt'>
  <td align="center" height=34 class=xl66 style='height:25.5pt'>4b</td>
  <td align="center" class=xl68 width=234 style='width:176pt'>RegEx: Match fails due to HTML
  formatting tags, e.g. &lt;strong&gt;</td>
  <td align="center" class=xl67 width=156 style='width:117pt'>Yes</td>
  <td align="center" class=xl67 width=187 style='width:140pt'>Yes</td>
  <td align="center" class=xl67 width=206 style='width:155pt'>N/A</td>
 </tr>
 <tr height=34 style='height:25.5pt'>
  <td align="center" height=34 class=xl66 style='height:25.5pt'>4c</td>
  <td align="center" class=xl68 width=234 style='width:176pt'>Like: Matches only with
  wildcards due to implicit HTML tags, e.g. &lt;p&gt;</td>
  <td align="center" class=xl67 width=156 style='width:117pt'>N/A</td>
  <td align="center" class=xl67 width=187 style='width:140pt'>Yes</td>
  <td align="center" class=xl67 width=206 style='width:155pt'>N/A</td>
 </tr>
 <tr height=34 style='height:25.5pt'>
  <td align="center" height=34 class=xl66 style='height:25.5pt'>4d</td>
  <td align="center" class=xl68 width=234 style='width:176pt'>Like: Match fails due to HTML
  formatting tags, e.g. &lt;strong&gt;</td>
  <td align="center" class=xl67 width=156 style='width:117pt'>N/A</td>
  <td align="center" class=xl67 width=187 style='width:140pt'>Yes</td>
  <td align="center" class=xl67 width=206 style='width:155pt'>N/A</td>
 </tr>
 <tr height=34 style='height:25.5pt'>
  <td align="center" height=34 class=xl66 style='height:25.5pt'>4e</td>
  <td align="center" class=xl68 width=234 style='width:176pt'>Other modes: Match fails due to HTML
  formatting tags, e.g. &lt;strong&gt;</td>
  <td align="center" class=xl67 width=156 style='width:117pt'>Yes (using "Contains" operator)
</td>
  <td align="center" class=xl67 width=187 style='width:140pt'>Yes (using "=" operator)</td>
  <td align="center" class=xl67 width=206 style='width:155pt'>Yes</td>
 </tr>
 <tr height=34 style='height:25.5pt'>
  <td align="center" height=34 class=xl66 style='height:25.5pt'>5</td>
  <td align="center" class=xl65 width=234 style='width:176pt'>Apostrophes in HTML fields:
  Match fails</td>
  <td align="center" class=xl67 width=156 style='width:117pt'>Yes</td>
  <td align="center" class=xl67 width=187 style='width:140pt'>Yes</td>
  <td align="center" class=xl67 width=206 style='width:155pt'>Yes</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td align="center" height=17 class=xl66 style='height:12.75pt'>6</td>
  <td align="center" class=xl65 width=234 style='width:176pt'>OR mode performs as expected</td>
  <td align="center" class=xl67 width=156 style='width:117pt'>No</td>
  <td align="center" class=xl67 width=187 style='width:140pt'>Yes</td>
  <td align="center" class=xl67 width=206 style='width:155pt'>N/A</td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td align="center" width=64 style='width:48pt'></td>
  <td align="center" width=234 style='width:176pt'></td>
  <td align="center" width=156 style='width:117pt'></td>
  <td align="center" width=187 style='width:140pt'></td>
  <td align="center" width=206 style='width:155pt'></td>
 </tr>
 <![endif]>
</table>

**Comment by JoeMurray** [comment]
@colemanw As the person responsible for UX of CiviCRM in general, I'm wondering if you can comment on where we should go next on dealing with searches of html fields, based on @bsilvern's great summary here. It doesn't appear that @quoma is still engaged, despite the very useful functionality the PR provides.

**Comment by eileenmcnaughton** [comment]
I think if it's not working, & not being worked on we should open a JIRA, link to this & note that there is code & discussion here & close the PR.

JIRA is the place to track work that is not on the verge of completion

**Comment by litespeedmarc** [comment]
Echo @eileenmcnaughton's comments.  If we're not going to follow-up on items, then it's time to close this (there seem to be quite a few "almost complete" PRs waiting to get merged).  I'm compiling a list of old PR and recommended actions for them, that I'll share with a few key players at the end of this sprint.  Being fairly new here, don't have the clout (yet) to be able to do this, but for this one would recommend closing.

Created https://issues.civicrm.org/jira/browse/CRM-19416 for the original feature request, which is linked to the outstanding issue mentioned above, (https://issues.civicrm.org/jira/browse/CRM-19010)

**Pull request closed without merging**
