### PR TITLE
dev/cloud-native#16 Migrate Contribution Page widget extern url to us…

### PR DESCRIPTION
**Pull request by seamuslee001**
…e the normal CMS routing mechanism

Overview
----------------------------------------
This migrates the Contribution Page Widget js end to use an endpoint within the normal routing system

Before
----------------------------------------
extern file used

After
----------------------------------------
Non extern route used

ping @eileenmcnaughton @totten @kcristiano

### CODE REVIEW

**Comment by totten** [comment]
I haven't tested, but the broad contours look good. :+1:

**Comment by seamuslee001** [comment]
@eileenmcnaughton @totten I have expanded the test coverage here to cover both endpoints which shows we are getting a consitatnt return from both endpoints, Is there anything else needed to prove that this works?

**Comment by eileenmcnaughton** [comment]
I was kinda hoping @kcristiano would test it...

**Comment by kcristiano** [comment]
did an r-run.

Without the PR:

image

script:

```
<script type="text/javascript" src="http://wpcvmaster.test/wp-content/plugins/civicrm/civicrm/extern/widget.php?cpageId=1&widgetId=1&format=3"></script>
```


With the PR:

Script:

```
<script type="text/javascript" src="http://wpcvmaster.test/civicrm/contribute/widget/?cpageId=1&widgetId=1&format=3"></script>
```

Widget looks off:

image

**Comment by seamuslee001** [comment]
Did you rebuild the menu Kevin?

**Comment by kcristiano** [comment]
I did, and cleared caches.

**Comment by seamuslee001** [comment]
@kcristiano I rebased this and re-tested and after clearing menu cache my url was `http://wp-demo/civicrm/contribute/widget/?cpageId=1&widgetId=1&format=3`  and the widget looked like the attached in the preview
widget_preview

Are you able to re-test?

**Comment by kcristiano** [comment]
@seamuslee001 I'll do this, it may take a few days, but I'll give you feedback.

**Comment by kcristiano** [comment]
@seamuslee001 sorry for the delay but I cannot get the patch to apply on d7 master or wp master.

**Comment by seamuslee001** [comment]
@kcristiano rebased now for you mate

**Comment by kcristiano** [comment]
@seamuslee001 I did a new `r-run`  Preview is good and on remote site:

image


Contribution works directing me to real form.

Tested on:

WP 5.5.1
CiviCRM master
php 7.3

Looks good to merge.

**Comment by eileenmcnaughton** [comment]
boom

**Pull request merged**
