### PR TITLE
[REF] Change LineItem.qty to be CRM type of FLOAT rather than Money a…

### PR DESCRIPTION
**Pull request by seamuslee001**
…s this field needs decimals but not to have $ added

Overview
----------------------------------------
JMA Has been working on shifting to using search kit based table for listing of line items in the Edit Line item extension. This has shown up a problem which is that all decimal columns are treated as T_MONEY by CiviCRM and therefor when rendered in the search kit a $ is added to the qty as per the before. This is incorrect to me. I don't think changing it to be a T_FLOAT should change anything significantly 

Before
----------------------------------------
image

After
----------------------------------------
image

ping @laurensamille @eileenmcnaughton @colemanw @monishdeb @JoeMurray

### CODE REVIEW

**Comment by mattwire** [comment]
Why was lineitem.qty ever a decimal? Shouldn't it be an int?

**Comment by mattwire** [comment]
Ok, some history and rationale here https://github.com/civicrm/civicrm-core/pull/4612 for it being a (float). Seems like it regressed to be a decimal at some point..

**Comment by seamuslee001** [comment]
@mattwire so looking at that PR it converts it to being sql type of decimal which then gencode assumes is going to be Money PHP Type not a float PHP Type

**Comment by eileenmcnaughton** [comment]
@seamuslee001 so my understanding is that we are introducing a new option for the xml definition - which makes me think a) it will need documentation & 
b) is there any label we can give it that is more intuitive than `crmType` - which is an internal gencode thing but doesn't have a very obvious meaning

I *think* all the values for 'type' as sql types - in which case a different field makes sense - is it really a `data_format_type`/  (or perhaps `dataFormatType` is more consistent with the other fields in the xml)

**Comment by seamuslee001** [comment]
@eileenmcnaughton crmType isn't anything new as per https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/CodeGen/Specification.php#L362 its been an option forever but just not used for "decimal" types before. Also you can see that crmType is already defined here https://docs.civicrm.org/dev/en/latest/framework/database/schema-definition/#table-field

**Comment by eileenmcnaughton** [comment]
OK - if it's already documented then yeah - all good

**Pull request merged**
