### PR TITLE
CRM-20474 Refactor UFField api to be standardised

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
* [CRM-20474: Refactor UFField api to follow standard api \/ BAO format](https://issues.civicrm.org/jira/browse/CRM-20474)

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
seems one can not add any fields to the profile after this change. Trying to add a field on "Name and Address" profile gives an error `The selected field already exists in this profile`. Do we have anyone to fix this and make it compatible for the latest master?

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit I pulled the refactoring of the duplicateFields check into #10244 - are you able to QA that? If that's all good I'll take a look at the rest of what is in this PR

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I'm going to merge what is currently in this PR if it passes - just moving code from the api to the create function and some fixes from @saurabhbatra96 that I have QA'd

Then I'll open a second PR which switches the form to call the api & consolidates create+add into one place & ask @jitendrapurohit to review that

**Pull request merged**
