### PR TITLE
CRM-16189, added function to retrieve values from settings

### PR DESCRIPTION
**Pull request by pradpnayak**
---
- CRM-16189: Improve support for Accrual Method bookkeeping
  https://issues.civicrm.org/jira/browse/CRM-16189

### CODE REVIEW

**Comment by pradpnayak** [comment]
(DO NOT MERGE - Submitted to facilitate testing)

**Comment by pradpnayak** [comment]
will commit unit test soon

**Comment by eileenmcnaughton** [comment]
I'm not quite clear the value this is adding. The settings function should have caching in it so the caching is not a valuable addition. In general I would say the Pseudoconstant classes are being deprecated so that is what caught my eye here.

I'm guessing that you are storing some new settings in an array rather than flat settings & are adding this to get the settings out of it again? How many settings are involved? Would it be better just to store them as multiple flat settings? THere is precedent for that

**Comment by pradpnayak** [comment]
The CiviContribute settings form is coded in such a way that it stores submitted values in a serialized form as a single setting in civicrm_setting. So i didn't wanted to store them as a flat settings. Modifying the code may lead to major change in other parts of the code since this settings are used in many classes.  Therefore created a new function that would retrieve necessary settings values from CiviContribute settings

**Comment by eileenmcnaughton** [comment]
Hmm - I don't think the contribute settings storing as an array is good as it differs from other ways of storing settings :-( It's just another inconsistency.

If we have to live with an inconsistency because it's too hard to change for now I would generally make sure I heavily comment the code explaining why (& linking to relevant discussions) so people can't fall into thinking it's a good pattern. I would also move the fn to either the contribute BAO or the settings BAO since it is not a pseudoconstant

**Comment by pradpnayak** [comment]
I have moved the function to BAO and also added comment.

**Comment by JoeMurray** [comment]
@colemanw could you review this, as it is a dependency for merging #8565, which is a dependency for others.

**Comment by colemanw** [comment]
I'm merging this because it's needed elsewhere and is a pretty harmless (if possibly redundant) wrapper around Civi::settings

**Pull request merged**
