### PR TITLE
Fix undefined tpl vars in CiviReport

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes a whole bunch of PHP notices on CiviReport screens.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
FYI some test fails:

    api_v3_JobTest.testMailReportForPrint
    CRM_Report_Utils_ReportTest.testOutputPrint

**Comment by colemanw** [comment]
Yea I left off an `!` from an `empty()`. Glad the tests caught it.

I'm toying with the idea of using a mass regex replace to do simple transformations like `{if $foo.bar}` => `{if !empty($foo.bar)}`. It would result in a daunting PR but IMO is safer because a human doesn't have to write it.
It wouldn't be able to do the weird cases but could save us a lot of manual work for the simple ones.

**Comment by demeritcowboy** [comment]
I kind of agree with @eileenmcnaughton that some of these are pointing out places where something is missing that shouldn't be, maybe even some rogue typos, and so a mass replace with `empty` would hide those, but on the other hand it would be no different than it's been for years. So 🤷

**Comment by demeritcowboy** [comment]
jenkins retest this please

E2E\Core\AssetBuilderTest::testInvalid

**Pull request merged**
