### PR TITLE
SearchKit - enable tags for Saved Searches

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Allows saved searches to be tagged, for categorization in SearchKit.

Screenshot from 2021-09-05 18-13-34

Comments
----------------------------------------
The tag widget I made in Angular was inspired by the "Labels" dropdown in GitHub in which the search box serves a double-purpose with a "create new tag" option.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw so I've hit a couple of things in testing so far

1) I did a `civibuild create dmaster` locally & search wouldn't load. The issue appears to be that the way in which we install extensions in that scenario (which is more a dev scenario I guess) doesn't load the option value change - which seems to be required for the field to load.

2) (more serious) - if you go to http://core-21376-80rtm.test-1.civicrm.org:8001/civicrm/admin/search#/list & try to add the tag 'ea' to the second search it fails with js errors (it might be the shortness of the tag name since I assigned the longer tag more easily)

image

**Comment by colemanw** [comment]
@eileenmcnaughton Ok I fixed the 2nd issue. The first I think is just a matter of clearing caches so that `hook_civicrm_managed` runs?

**Comment by eileenmcnaughton** [comment]
@colemanw yeah - the first relates to how we install search kit in a new build scenario. I'm ok with it not being in scope for this change since I think only devs will be affected for now

**Comment by eileenmcnaughton** [comment]
@colemanw unrelated to this but  a minor usability thing I hit in testing is that having saved a search if I now want to do a new search on another entity I can't  - without going back to the main search page - a 'new search' button or similar would help
image

**Comment by eileenmcnaughton** [comment]
This is working well now - I expect we will hit the dev install issue a few more times but I'm happy to deal with that separately

**Comment by eileenmcnaughton** [comment]
@colemanw another thought - not required for this to be merged - but being able to search by author would be the other search box that would be useful on this screen I think (created vs modified is a bit ambigous & tbh I could make a case for an editable 'owner_id' fields because I semi-often create groups for other people & it's unlikely I would remember who in a year's time - we actually pseudo do this by telling everyone to include their name or initials in the group name)

**Comment by colemanw** [comment]
Ok @eileenmcnaughton I've added https://github.com/civicrm/civicrm-core/pull/21388

**Pull request merged**
