### PR TITLE
CRM-16973 - filter FROM Email Address select by domain_id

### PR DESCRIPTION
**Pull request by davecivicrm**
---
- CRM-16973: CiviMail not respecting multisite ACL
  https://issues.civicrm.org/jira/browse/CRM-16973

### CODE REVIEW

**Comment by seamuslee001** [comment]
Hi Dave, looks good and works well on my test system, Would it also be possible to backport https://github.com/civicrm/civicrm-core/pull/6366 to 4.6 as well as that would solve the groups ACL problem

**Comment by eileenmcnaughton** [comment]
Seamus - please do a PR for the backport (if you have time). I agree it needs to go into 4.6

**Comment by seamuslee001** [comment]
@eileenmcnaughton see https://github.com/civicrm/civicrm-core/pull/6424

**Comment by eileenmcnaughton** [comment]
unrelated failures

**Pull request merged**
