### PR TITLE
APIv4 Explorer - Format array params using add methods instead of set

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Improves OOP code generated from the APIv4 Explorer, by using sugar methods `addGroupBy()` and `addRecord()`.

Before
----------------------------------------
image

After
----------------------------------------
image

### CODE REVIEW

**Comment by braders** [comment]
Just given this a quick check, and it works well for `addGroupBy`. However, I'm a bit confused by the reference to records in the `arrayParams`; I can't see any trace of a `addRecords` method in CiviCRM. Am I missing something?

**Comment by colemanw** [comment]
> Just given this a quick check, and it works well for `addGroupBy`. However, I'm a bit confused by the reference to records in the `arrayParams`; I can't see any trace of a `addRecords` method in CiviCRM. Am I missing something?

It's in the Replace and Save actions, e.g. https://github.com/civicrm/civicrm-core/blob/db11224f49b015c1bfc031a0ad87ba7ed1bf499e/Civi/Api4/Generic/AbstractSaveAction.php#L175

Note that it's called `addRecord` and that's why the API Explorer is lopping off the trailing `"s"`.

**Comment by braders** [comment]
> Note that it's called addRecord and that's why the API Explorer is lopping off the trailing "s". (I see I typed that wrong in the issue description. Now fixed.)

As I see. So that's given me enought to figure out how to test, and it seems to be working as expected 👍

**Comment by colemanw** [comment]
Unrelated test fail

**Pull request merged**
