### PR TITLE
Remove always true parameter & associated IF from previously shared function

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Remove always true parameter & associated IF from previously shared function

Before
----------------------------------------
image

After
----------------------------------------
params not passed by ref, skipFile removed as well as the code that would be hit if it were true

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton can you check the MCs

**Comment by eileenmcnaughton** [comment]
@colemanw done

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@colemanw resolved & passing....

**Pull request merged**
