### PR TITLE
Cache spec provider mods

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Cache spec provider mods

Before
----------------------------------------
25 rows load in 1.34 minutes

(500 error seems to be timeout related - ie 30 sec max_execution_time)

image

After
----------------------------------------
loads in 13.72 seconds

image

Technical Details
----------------------------------------
@colemanw I'm not sure if this is the right place - it is still slow - ie 14 seconds is still too slow. The slowness seems to be at the php layer not sql  but the slowness seems to be only from `fieldBelongsToEntity` now - I feel like we used to have caching in the spec that got removed for other reasons but not all entities need this level of decision making & perhaps they could opt out of it.

ie `fieldBelongsToEntity` bypasses this caching because every row passes in different values - although none matter for this entitiy

Note that this timing (28 seconds) has the in-function caching https://github.com/civicrm/civicrm-core/pull/29059

image

That PLUS this seems to be marginally faster than just this 

image

Retrying that slow POST with profiling enabled it takes 35 seconds with this and the static caching applied with notable items being

- 6.3 seconds spent on 130,807 calls to `getCodeDocs()`
- 8.3 seconds spent on 80,028 calls to ` unoptimisedEventDispatcher->callListeners`

Big picture these are components of `formatEditiableColumn()` which takes up 33.7 seconds once this patch is applied - and 23.9 of that is used in `fieldBelongsToEntity()` - but what I'm not finding, which is highlighted by the above 2 items, is slowness due to too much mysql querying - rather too much php processing

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton are you testing with the latest changes from https://lab.civicrm.org/dev/core/-/issues/4905 which should have dramatically sped-up the `fieldBelongsToEntity` function.

**Comment by eileenmcnaughton** [comment]
@colemanw I'm testing with what is merged so far.... my take is that reduced the queries to load custom data -but I'm seeing large amounts of time being used at the php layer on building the field spec - e.g 6.3 seconds spent on 130,807 calls to getCodeDocs()

**Comment by colemanw** [comment]
@eileenmcnaughton what's the calling function that calls `getCodeDocs` so many times? Maybe we need to use `Civi::$statics` there.

**Comment by colemanw** [comment]
@eileenmcnaughton would this help at all? #29061

**Comment by eileenmcnaughton** [comment]
@colemanw it does help - but not nearly as much as calling modifySpec thousands of time less would...

**Comment by colemanw** [comment]
@eileenmcnaughton I think #29066 will solve it for you then, as it caches post-`SpecProvider`-mods.

**Pull request closed without merging**
