### PR TITLE
Do not check for the extension we are trying to download itself

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This ensures that we ignore if the extension we are trying to download is not its self already installed

Before
----------------------------------------
Create brand new civibuild instance
Navigate to Extensions UI
Click on Add New
Select mjwshared
Click Download and Install
Error

After
----------------------------------------
Repeat same steps as above but install is successful

ping @mattwire @eileenmcnaughton

### CODE REVIEW

**Comment by seamuslee001** [comment]
I'm going to add merge on pass to this PR based on the fact it fixes william Mortada's issue as per comment in chat here https://chat.civicrm.org/civicrm/pl/rkwq1ojcqtrnjccjkwgkfjqxde

**Comment by wmortada** [comment]
I've tested this again on a fresh instance of wpmaster and can confirm that installing an extension fails without this patch but succeeds with it.

**Comment by seamuslee001** [comment]
Thanks @wmortada

**Comment by seamuslee001** [comment]
Test fail is unrelated

**Pull request merged**
