### PR TITLE
CRM-20972 Attempt to handle new type of Exception thrown in php7.1 wh…

### PR DESCRIPTION
**Pull request by seamuslee001**
…en function call has too few variables

- [CRM-20972 PHP7.1 New Exception generated causing failures in API_v3_SyntaxConformanceTests](https://issues.civicrm.org/jira/browse/CRM-20972)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@totten this passed by php7.1 set up and Jenkins has given it the nod. @eileenmcnaughton any thoughts on this?

**Comment by eileenmcnaughton** [comment]
Interesting, and kinda cool. Since it's in the test suite jenkins is the ultimate arbiter of this patch. However, I think the main benefit of adding it is to show people what can be done (& perhaps later they will in their own extensions) so it probably at least needs to be flagged as a php 7.1 thing

**Comment by eileenmcnaughton** [comment]
oh I see - it is required for the tests - still think it would be nice to note it as 7.1 support

**Comment by seamuslee001** [comment]
@eileenmcnaughton how would you see that it should be noted as php7.1 support?

**Comment by seamuslee001** [comment]
@eileenmcnaughton I have added a code comment in each function now about the new Exception

**Comment by eileenmcnaughton** [comment]
Fantastic

**Pull request merged**
