### PR TITLE
SearchKit - Fix campaign, event & primary address dropdowns

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes [dev/core#3950](https://lab.civicrm.org/dev/core/-/issues/3950) and [dev/core#3982](https://lab.civicrm.org/dev/core/-/issues/3982)

Before
----------------------------------------
Multiple problems with SearchKit select lists

After
----------------------------------------
EntityRef to the rescue! :superhero: 

Technical Details
----------------------------------------
For fields with both an FK and an option list, prefer the FK because it's more efficient to render an autocomplete than to pre-load potentially thousands of options into a select dropdown. It also solves the bugs with Campaign lists (which has a funky set of no-prefecth options) and contact primary address dropdowns (which aren't strictly part of the contact entity so those options hadn't been loading).

### CODE REVIEW

**Comment by aydun** [comment]
Test this please

**Comment by aydun** [comment]
That fixes the problem in https://lab.civicrm.org/dev/core/-/issues/3982

But ... in the dropdown for country, the additional information shown is the id.  It would be more useful to show the ISO code field.

image

The states show the country which is useful:
image

**Comment by colemanw** [comment]
Thanks @aydun I've added a customized display for Countries with your suggestion.

**Comment by aydun** [comment]
Thanks - Looks good.

More generally, is it possible to search on multiple fields in an autocomplete?  For example, can it be configured to search on both name and iso so that if I type in 'gb' it would find 'United Kingdom'?

**Comment by colemanw** [comment]
@aydun yes - these Autocompletes use a special type of SearchKit display that you can configure. The search logic currently treats all fields on the top line as searchable using OR. For performance reasons I didn't include other lines in the search so if you wanted to do this on a particular form you'd need to configure an autocomplete search display for that form and use "rewrite" to place both name and iso on the top line of the autocomplete results.

**Pull request merged**
