### PR TITLE
Add calling function to deprecatedWarning log message

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
When `CRM_Core_Error::deprecatedWarning()` is triggered it's helpful to know where it is called from.

Before
----------------------------------------
No idea what triggered this:
```
 [warning] Attributes passed to CRM_Core_Form::add() are not an array.
Array
(
    [civi.tag] => deprecated
)
```

After
----------------------------------------
Ah, it was triggered by `CRM_Gdpr_SLA_Entity::addField`:
```
 [warning] Attributes passed to CRM_Core_Form::add() are not an array. Caller: CRM_Gdpr_SLA_Entity::addField
Array
(
    [civi.tag] => deprecated
)
```

Technical Details
----------------------------------------
Uses the same code as `deprecatedFunctionWarning()` to get the name of the calling function.

Comments
----------------------------------------

### CODE REVIEW

**Comment by demeritcowboy** [comment]
I've run into this - 👍 for concept.

When I test it though it doesn't give me the right function. I guess you've used array element '2' to avoid having it say the caller is deprecatedFunctionWarning itself(?), but then when it's a direct call to deprecatedWarning it just says something like CRM_Core_Form::buildForm which doesn't tell me the actual form.

This seemed to work for me:

```php
    $dbt = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 3);
    $callerFunction = $dbt[1]['function'] ?? NULL;
    $callerClass = $dbt[1]['class'] ?? NULL;
    if ($callerFunction !== 'deprecatedFunctionWarning' || $callerClass !== 'CRM_Core_Error') {
      // The caller is already in the message if we came from deprecatedFunctionWarning itself
      $message .= " Caller: {$callerClass}::{$callerFunction}";
    }
```

**Comment by mattwire** [comment]
Thanks @demeritcowboy I've updated to partially use your solution - I don't think there is a perfect one here!

On a site I have this running if I use array index 1 I get:
```
[warning] Attributes passed to CRM_Core_Form::add() are not an array. Caller: CRM_Core_Form::add
```

if I use array index 2 I get:
```
[warning] Attributes passed to CRM_Core_Form::add() are not an array. Caller: CRM_Msgtplsender_Form_Email::buildQuickFormFromEmailTrait528
```

What do you think?

**Comment by demeritcowboy** [comment]
Right...ok - Hmm I think a complication here is the nature of that specific Form::add() one because it's not Form::add() that's deprecated, but its caller is doing something deprecated. Just thinking out loud for a minute:

* Form::add() and others like it could themself look up its caller and include it in the message.
* More generically, we _could_ log the whole stack trace but that will flood logs. Or always log both the first and second levels of callers.

**Comment by demeritcowboy** [comment]
Ok I did a grep for all the calls to deprecatedWarning and most of them are actually like the Form::add() one, where they are talking about what their caller did not what they are doing. So I'm changing my vote and agree your original was the best one, with the '2' and without the `if`, and then we should fix up the handful of deprecatedWarning calls that are using it differently. For example some should really be deprecatedFunctionWarning, e.g. the one in CRM/ACL/BAO/ACL.php

**Comment by mattwire** [comment]
@demeritcowboy Ok, how about this?

I don't actually see any need for `deprecatedFunctionWarning()` to call `deprecatedWarning()` as it only saves 2 lines of code and they are next to each other anyway! That also avoids getting the backtrace/caller twice - I've updated the PR.

I added a second commit to flag the function you found as deprecated. I don't see an obvious replacement for `check()` which would be needed to call `deprecatedFunctionWarning()` - that could be handled in a follow-up PR.

**Comment by demeritcowboy** [comment]
Yeah it might not be worth trying to optimize lines of code. And agree that I don't know what the replacement would be for those other calls so can leave for future.

r-run checks out.

**Pull request merged**
