### PR TITLE
CRM-21541 CRM.moneyFormat can't handle values with zero or one decimals

### PR DESCRIPTION
**Pull request by semseysandor**
Overview
----------------------------------------
If the Monetary Value Format is set to display one or zero decimals, adding members doesn't work.

Before
----------------------------------------
Bug description:
[JIRA](https://issues.civicrm.org/jira/browse/CRM-21541)

After
----------------------------------------
Now it can display amounts correctly.

Technical Details
----------------------------------------
Changed the **CRM.moneyFormat()** function to be able to detect if format is set to zero or one decimals, then format the value according to this.

Comments
-----------------------------------------
Might be wise to extend the test cases to include monetary values with one or zero decimals in the future.

### CODE REVIEW

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by mlutfy** [comment]
@semseysandor Thank you for the patch!

I noticed that a fair amount of code comments were changed because of the formatting of your code editor. Would it be possible to update your PR so that it includes only the specific lines changes? It will be easier to review that way and will help reduce noize in the git log.

**Comment by semseysandor** [comment]
@mlutfy Yes, no problem, it's done

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by mlutfy** [comment]
@semseysandor Thanks!

@jaapjansma Ping, I think you may have thoughts on this patch?

**Comment by jaapjansma** [comment]
Looks good to me on a first sight. I need more time to test and review this patch.

**Comment by mattwire** [comment]
We get a lot of problems relating to money formatting both on the PHP and the javascript side. The patch itself looks good but there will almost certainly be other cases in the future that cause it to break again. I wonder if we'd be better integrating a simple jquery money formatting library to replace this function instead of tweaking it. Eg. https://github.com/autoNumeric/autoNumeric or http://openexchangerates.github.io/accounting.js/ (I haven't tested either of them) @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
I strongly agree that a js formatter is likely to get us out of money  hell - as it did with datepicker (in the end)

**Comment by jaapjansma** [comment]
test this please

**Comment by jaapjansma** [comment]
Betty and I have reviewed this PR.

* General standards
    * Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
        * __PASS__ : The goal/problem/solution have been adequately explained in the PR and in JIRA
    * User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
        * __PASS__: The change would be intuitive or unnoticeable for a majority of users who work with this feature.
    * Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
        * __PASS__: The changes do not require documentation.
    * Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
        * __PASS__: We have tested this with the patch applied and without with the patch applied we can add memberships with a payment without any errors.
* Developer standards
    * Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
        * __PASS__: The change preserves compatibility with existing callers/code/downstream. Altough I found it hard to review the code as I am not good in Javascript.
    * Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
        * __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
    * Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
        * __PASS__: We do think that this change does not require tests. However a test would have a been a surplus.
    * Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
        * __ISSUE__: The automated test did not run. Probably because it is a javascript change.

**Comment by eileenmcnaughton** [comment]
I'm merging based on @jaapjansma's review - since the commits are a bit messed up & I don't want to mess with the attribution I'm going to 'squash and merge'  - but it doesn't give the best git history - next time we'll work with you to get a clean commit @semseysandor  - in the meantime - congrats on your first merge

**Comment by semseysandor** [comment]
@eileenmcnaughton Thank you, I'm happy I could contribute! Yes the commits were a mess, in the middle there was a point when I was considering closing and opening a new one... I believe next time I can get it nice & clean.

**Pull request merged**
