### PR TITLE
split sql select into two selects for performance reasons

### PR DESCRIPTION
**Pull request by adixon**
Overview
----------------------------------------
As per https://lab.civicrm.org/dev/core/-/issues/3031

Traced to some sql in CRM/Mailing/Event/BAO/Unsubscribe.php which was executing when checking whether a contact was subscribed to one or more groups.

Before
----------------------------------------
On sites with a reasonably large number of contacts and mail enabled smart groups.
Very high CPU and delays when viewing mail-enabled smart groups on a contact.
Very high CPU when running some system jobs (e.g. bounce processing).

After
----------------------------------------
Somewhat improved.

Technical Details
----------------------------------------
As per the issue discussion, the sql is much more efficient when split into two separate queries in place of the existing OR, presumably due to the ability of mysql to use (internal) caches.

Comments
----------------------------------------
There may be other related issues due to the use of smart groups for mailings, I can still see some load with these activities when the smart group caches are rebuilt.

### CODE REVIEW

**Comment by mattwire** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@adixon style issue 

image

**Comment by eileenmcnaughton** [comment]
@adixon based on discussion it seems this IS a recent regression & it would be good if your PR were against the 5.48 rc branch

**Comment by adixon** [comment]
I've removed the extra blank row and updated the PR to go against 5.48 but maybe I need to redo the whole thing against 5.48, this doesn't seem right yet ...

**Comment by eileenmcnaughton** [comment]
@adixon yep - you probably want to reset --hard against origin/5.48 & then cherry-pick it on

**Comment by adixon** [comment]
Replaced with https://github.com/civicrm/civicrm-core/pull/23051

**Pull request closed without merging**
