### PR TITLE
CRM-21135 - Activity filter preference are not remembered when enable…

### PR DESCRIPTION
**Pull request by jitendrapurohit**
…d in display preference

Overview
----------------------------------------
Fix Activity filter to be remembered if enabled in settings. 

Before
----------------------------------------
Reload of a page removes the filter setting saved in the database.

After
----------------------------------------
works fine.

Technical Details
----------------------------------------
This seem to be due to the difference in form fields which is `activity_type_filter_id` and `activity_type_exclude_filter_id` and the setting saved in db does not include `filter` text in it - `activity_type_id` and `activity_type_exclude_id` respectively.

Either this need to handled by:
- changing the form id of this field to be the same as of db setting key OR
- replace db id with the form id as done in this PR(used to be the same in previous versions).

Comments
----------------------------------------
Tagging as wip until the unit test is covered for this use-case.

---

 * [CRM-21135: Activity filter preference are not remembered when enabled in display preference](https://issues.civicrm.org/jira/browse/CRM-21135)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit @monishdeb I think this can go into the rc if we feel comfortable in time. It's not really critical IMHO but it is a recent regression - which is the key criteria for the rc. If you think it is risky / underbaked & low impact then maybe it can wait anyway?

**Comment by jitendrapurohit** [comment]
I tagged the ticket as critical since [priority level](https://issues.civicrm.org/jira/secure/ShowConstantsHelp.jspa?decorator=popup#PriorityLevels) contains recent regression as a symptom. Agree this only affects when the setting is enabled on the Display Preference and doesn't cause any data loss, happy to lower the priority in jira.

**Comment by eileenmcnaughton** [comment]
Ah you are right! By that definition it is critical. Anyway - the bigger question is to rc or not to rc - what do you think?

**Comment by jitendrapurohit** [comment]
I'll say rc, as this is immensely safe imo and will also include a unit test later today.

**Comment by monishdeb** [comment]
Yup, its safe .. patch worked for me... waiting for the UT and will merge on pass.

**Comment by eileenmcnaughton** [comment]
@monishdeb if you feel this is solid we should put against the rc. The criteria for the rc is that it is a recent regression. If you have doubts then master is fine

**Comment by jitendrapurohit** [comment]
@eileenmcnaughton oops, I've just created an rc https://github.com/civicrm/civicrm-core/pull/10932. I'll keep this open until RC decision is done. Added unit test and removing wip tag now.

**Pull request closed without merging**
