### PR TITLE
CRM-20461 - Use api instead of query so that post hook gets invoked for additional participants

### PR DESCRIPTION
**Pull request by jitendrapurohit**
* [CRM-20461: post hook not invoked after updating status for additional participants](https://issues.civicrm.org/jira/browse/CRM-20461)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I like the test -but I think we should just call the api to update - feels like unnecessary complexity otherwise

**Comment by eileenmcnaughton** [comment]
I'm wondering if we really want to catch the exception - it is hard to imagine when it would happen & one way or another I think it would get caught further up.

@totten do you have any opinion when we should catch vs not catch exceptions - I'm inclined to think that if an exception would only happen in a really weird unpredicted situation we should let the form layer / api catch it

**Comment by monishdeb** [comment]
@eileenmcnaughton on grepping ```updateParticipantStatus``` usage in Core it is used in 4 places : 
```
CRM/Contribute/BAO/Contribution.php:1758:        CRM_Event_BAO_Participant::updateParticipantStatus($participant->id, $oldStatus, $updatedStatusId, TRUE);
CRM/Contribute/BAO/Contribution.php:1791:        CRM_Event_BAO_Participant::updateParticipantStatus($participant->id, $oldStatus, $updatedStatusId, TRUE);
CRM/Contribute/BAO/Contribution.php:1951:        CRM_Event_BAO_Participant::updateParticipantStatus($participant->id, $oldStatus, $updatedStatusId, TRUE);
CRM/Event/BAO/Participant.php:215:      self::updateParticipantStatus($participant->id, $status, $participant->status_id);
```
That is on if -
1. there is a payment failure during paid event registration
2. related event's contribution payment is completed from pending
3. related event's contribution status is changed to ```Cancelled``` in backoffice form
4. participant status is updated via participant edit form
So all the four scenarios is triggered only via logged-in user action who has proper event permission, so there is no way any permission related exception thrown via participant.API. Apart from that Participant.create API didn't through any native exception (unlike Activity.API :p )

The patch is working fine, tested in my local

**Review by monishdeb — APPROVED** [review]

**Comment by eileenmcnaughton** [comment]
Thanks @monishdeb

**Pull request merged**
