### PR TITLE
Crm 14591

### PR DESCRIPTION
**Pull request by zorgalina**
CRM 14591 - sum up line_item values for Event report

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I'm just wondering what we should do to get this back on track.

I'm kind of happy for you to be the 'product manager' for event cart and where code only touches that component to let you make a call on whether it should go in.

However, this really needs to go into master before it can be considered for 4.6 now.

Also, there is a separate commit in here for a separate issue which possibly requires separate treatment. 

What should we do with this PR? Should we close it & then you can do 2 separate new ones? One for cart against master and the other one against ? master also?

@colemanw any thoughts?

**Comment by eileenmcnaughton** [comment]
hmm are you on the whitelist?

**Comment by zorgalina** [comment]
Is that addressed to me? Am I on the whitelist? Do you mean I should be the
product mgr for event cart? I know it needs work!

On Mon, Jan 18, 2016 at 6:50 PM, Eileen McNaughton <notifications@github.com
> wrote:

> hmm are you on the whitelist?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6398#issuecomment-172722131>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by eileenmcnaughton** [comment]
@colemanw can you add to whitelist

& yes, @zorgalina  I was thinking you might be product manager for the event cart - if @colemanw thinks that's a good idea. I don't think too many other people are familiar with it enough to test your patches / evaluate patches to it.

**Comment by zorgalina** [comment]
I will do it/be it if you allow it, make it so.  What do I need to do
(other than testing and trying to get it working well as possible) -
administratively or such?

On Wed, Jan 20, 2016 at 11:50 AM, Eileen McNaughton <
notifications@github.com> wrote:

> @colemanw <https://github.com/colemanw> can you add to whitelist
>
> & yes, @zorgalina <https://github.com/zorgalina> I was thinking you might
> be product manager for the event cart - if @colemanw
> <https://github.com/colemanw> thinks that's a good idea. I don't think
> too many other people are familiar with it enough to test your patches /
> evaluate patches to it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6398#issuecomment-173338910>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by colemanw** [comment]
jenkins, add to whitelist

**Comment by colemanw** [comment]
@zorgalina i dub thee Event Cart Manager.
Basically from now on if you submit a PR for the event cart code we will just merge it without question.
Other responsibilities would be to be the one to field questions about event carts when others in the community raise them.

**Comment by eileenmcnaughton** [comment]
And to review whether other people's patches to event cart make sense

**Comment by zorgalina** [comment]
Okay - and so if people log Issues I'd need to answer/address them on
behalf of CiviCRM

On Wed, Jan 20, 2016 at 12:05 PM, Eileen McNaughton <
notifications@github.com> wrote:

> And to review whether other people's patches to event cart make sense
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6398#issuecomment-173344560>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by colemanw** [comment]
Yes.
Currently the tests are failing due to style errors. To see the errors, click on the "details" link below, then click on the errors, and go over to the "details" tab.

**Comment by zorgalina** [comment]
right (I know about that,having made many style before errors dealing
w/self-service cancel/transfer feature)

On Wed, Jan 20, 2016 at 2:25 PM, colemanw <notifications@github.com> wrote:

> Yes.
> Currently the tests are failing due to style errors. To see the errors,
> click on the "details" link below, then click on the errors, and go over to
> the "details" tab.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6398#issuecomment-173381674>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by eileenmcnaughton** [comment]
I've done a replacement for this against master https://github.com/civicrm/civicrm-core/pull/8427

I excluded the report change as I'm still inclined to let this fly under the radar of our normal level of QA so long as it is limited to the event cart subsystem.

@zorgalina do you still have an interest in this patch?

**Pull request closed without merging**
