### PR TITLE
[ready-for-core-team-review]CRM-16189, added code to create entries in accounting tables for defe…

### PR DESCRIPTION
**Pull request by pradpnayak**
…rred revenue

---
- CRM-16189: Improve support for Accrual Method bookkeeping
  https://issues.civicrm.org/jira/browse/CRM-16189

### CODE REVIEW

**Comment by pradpnayak** [comment]
depends on https://github.com/civicrm/civicrm-core/pull/8579

**Comment by Edzelopez** [comment]
Are test failures related? Seems like I've been getting these for quite a few PRs
@eileenmcnaughton @colemanw

**Comment by Edzelopez** [comment]
jenkins, retest this please

**Comment by colemanw** [comment]
jenkins, retest this please

**Comment by colemanw** [comment]
@Edzelopez console output is showing the following error:

  ```
  not ok 348 - Failure: api_v3_ContributionTest::testCreateContributionWithPaymentInstrument
  ---
  message: 'Failure in api call for contribution create:  Undefined variable: updateLineItems'
  severity: fail
  data:
      got: 1
      expected: 0
```

**Comment by monishdeb** [comment]
Jenkin, test this please

**Comment by pradpnayak** [comment]
Jenkin, test this please

**Comment by pradpnayak** [comment]
Rebased PR and fixed code and test 

@colemanw can you please review?

**Comment by colemanw** [comment]
Have reviewed the code and all looks good. Tests are passing.

**Pull request merged**
