### PR TITLE
Declare pseudoConstant for PaymentToken.payment_processor_id

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Declare pseudoConstant for PaymentToken.payment_processor_id

Before
----------------------------------------
Some api funtionality missing - see below

After
----------------------------------------
this works

```
    return PaymentToken::create(FALSE)
      ->setValues([
        'token' => '5dff49d4-462c-432e-a12a-9f4c997e34c3',
        'contact_id' => $id,
        'payment_processor_id:name' => 'dlocal',
        'ip_address' => '192.168.1.1',
      ])
      ->execute()
      ->first();
```

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
Hmm, it's already a FK. SearchKit understands those without a pseudoconstant.
Why is this needed?

**Comment by eileenmcnaughton** [comment]
@colemanw yeah I didn't think it would be needed but this fails without it

```
    return PaymentToken::create(FALSE)
      ->setValues([
        'token' => '5dff49d4-462c-432e-a12a-9f4c997e34c3',
        'contact_id' => $id,
        'payment_processor_id:name' => 'dlocal',
        'ip_address' => '192.168.1.1',
      ])
      ->execute()
      ->first();
```

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
@eileenmcnaughton try this:
```diff
- 'payment_processor_id:name' => 'dlocal',
+ 'payment_processor_id.name' => 'dlocal',
```

**Comment by eileenmcnaughton** [comment]
@colemanw  yeah - but avoiding having to go 'oh this one works for the other similar entity but not this one' was why I did this PR - where it walks like a pseudoconstant it should quack like a pseudoconstant

**Comment by colemanw** [comment]
I'm trying to imagine how a pseudoconstant quack would sound...

**Comment by eileenmcnaughton** [comment]
it would be a pseudo-quack

**Comment by eileenmcnaughton** [comment]
test this please

**Pull request closed without merging**
