### PR TITLE
dev/core#2645 Proposed fix for exporting preferred_mail_format field

### PR DESCRIPTION
**Pull request by akosgarai**
Overview
----------------------------------------
A patch for [CORE-2645](https://lab.civicrm.org/dev/core/-/issues/2645)
Exporting in localized civicrm crashes due to long translation for preferred_mail_format varchar(8) field.

Before
----------------------------------------
Export of all contact data with at least one contact with preferred_mail_format 'Both' in Hungary l10n crashes with 
`Data too long for column 'preferred_mail_format'` exception.

After
----------------------------------------
The export works again, the csv is downloadable.

Technical Details
----------------------------------------
The preferred_mail_format is varchar(8) by default, but it is not long enough for the Hungarian translation, so that it has been changed to varchar(16), that is enough long for the translated string.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
Jenkins add to whitelist

**Comment by yashodha** [comment]
@akosgarai Can you please squash the commits?

**Comment by akosgarai** [comment]
The commits have been sqashed @yashodha

**Comment by yashodha** [comment]
@akosgarai Thanks!

**Pull request merged**
