### PR TITLE
[upstream-merge-required] Fix CRM-17834 incorrect member dates after completing a payment for a future membership

### PR DESCRIPTION
**Pull request by guanhuan**
https://issues.civicrm.org/jira/browse/CRM-17834

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Hey, we are no longer forward merging from 4.6 to 4.7 so we need to know this is fixed in 4.7 before we can merge a patch into 4.6 (and preferably tested in 4.7 - otherwise it would be better qualified as taped together with duct tape than fixed).

I'd be happy to work with you on writing a 4.7 test - there are some for that function in api_v3_ContributionTest class around the completetransaction method.

**Comment by eileenmcnaughton** [comment]
Note I edited the title to indicate what this PR is waiting on - please re-edit when that is no longer the case. It makes it easier to skim the PR list

**Comment by guanhuan** [comment]
Hi @eileenmcnaughton, thanks for the information. I am happy to help with the test for this scenario. For this fix, in my opinion, the fact that CiviCRM allows users to set a start date for a pending membership naturally leads to the expectation that the start date will take effect in appropriate scenarios. We can have a further discussion around the relevant Civi behaviours separately.

**Comment by eileenmcnaughton** [comment]
I'm going to close this out for now because it can't be considered for 4.6 until it's merged into master - please re-open once it's merged upstream.

**Pull request closed without merging**
