### PR TITLE
[ready-for-core-team-review]CRM-19799, fixed contribution params to include line items

### PR DESCRIPTION
**Pull request by pradpnayak**
----------------------------------------
* CRM-19799: LineItems incorrect at both Contribution Level and Financial Accounts Level
  https://issues.civicrm.org/jira/browse/CRM-19799

### CODE REVIEW

**Review by jitendrapurohit — APPROVED** [review]
Tested and confirmed that it fixes the `line_item` for priceset contributions stated in the issue. Just pinging @eileenmcnaughton if she's fine with the changes.

**Comment by eileenmcnaughton** [comment]
Yay for the test!

I feel that we should be trying to push the elicitation of the line items back to the form layer. I believe the way in which the form object is passed around with variables somewhat randomly snatched from it is confusing.

So, I would prefer to see $paymentParams['line_item'] passed in - which would trigger
```
      if (isset($paymentParams['line_item'])) {
        // @todo make sure this is consisently set at this point.
        $contributionParams['line_item'] = $paymentParams['line_item'];
      }
```

**Comment by pradpnayak** [comment]
@eileenmcnaughton  @jitendrapurohit @monishdeb 
Have pushed the changes

**Review by jitendrapurohit — APPROVED** [review]
also works after the latest changes. Thanks.

**Pull request merged**
