### PR TITLE
CRM-19303 - Refactor getDefaultFileStorage() function

### PR DESCRIPTION
**Pull request by colemanw**
* [CRM-19303: CKEditor configuration can't be edited on a Drupal multisite installation](https://issues.civicrm.org/jira/browse/CRM-19303)

### CODE REVIEW

**Comment by colemanw** [comment]
This attempts to make the code readable by refactoring the "if the cms is this then do that" logic into separate functions, per the fixme left by @totten.

The only substantial change is to the drupal function, which no longer relies on guessing the sitename based on the location of the civicrm module, but instead takes it directly from the files directory.

I have not tested this with multisites in D7, and haven't tested at all on D8 or D6, but I think it _should_ work. Some actual testing would be welcomed.

Easiest way to test is to type `CRM.config.CKEditorCustomConfig` in your console, and see if the object contains a correct url (paste the url into your browser and check it, also verify it has the correct `sites/sitename/files` sitename).

**Comment by seamuslee001** [comment]
Looks good @colemanw

**Comment by colemanw** [comment]
Actually it occurs to me that the code I wrote for Drupal would probably work for every CMS. Maybe that's the only function we need.

**Comment by colemanw** [comment]
Looking into it more, I think the code that was written for Wordpress is the best, and ought to work on every CMS.
So here is a more aggressive PR: #9458.
It will need testing in Drupal and Joomla!

**Pull request closed without merging**
