### PR TITLE
Make civicrm_mapping.name required and fix index to be unique

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Make `name` field required, fix the UI index an actual UI index. 

Before
------------------
Name field can be null even though it's supposed to be unique. Index named UI, but is not an UI. 

After
---------------
Sanity.

Technical Details
---------------------------
Because the `name` field was previously not required (or unique), this adds a shim to the BAO which will provide a unique name if one has not been supplied during creation.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
thanks!

**Comment by eileenmcnaughton** [comment]
@colemanw so am I right in thinking

`MappingCreationSpecProvider`can be deleted now?


For some reason `MappingField.name` is required at the apiv4 level - even though a blank string is valid and the xml does not require it

```
<field>
    <name>name</name>
    <title>Field Name (or unique reference)</title>
    <type>varchar</type>
    <length>255</length>
    <comment>Mapping field key</comment>
    <add>1.2</add>
  </field>
```

**Comment by eileenmcnaughton** [comment]
Ah - cos it is `strpos`
```
  public function applies($entity, $action) {
    return strpos($entity, 'Mapping') === 0 && $action === 'create';
  }
```

**Comment by eileenmcnaughton** [comment]
I just dropped this back to merge-ready cos I think we should remove that `SpecProvider` too - or alternaitvely limit to `Mapping` not the strpos

**Comment by colemanw** [comment]
@eileenmcnaughton oh, I just noticed that `Mapping.name` column is not required in the xml. That seems wrong. Why would we allow that?

**Comment by eileenmcnaughton** [comment]
@colemanw I think it's an oversight - I think it is pretty much enforced at the form level

**Comment by colemanw** [comment]
@eileenmcnaughton ok I've updated it.

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
Looks like there a few places where no-name mappings get created. I've fixed them up and added a deprecation notice in the BAO when no name is supplied for a new mapping.

**Pull request merged**
