### PR TITLE
CRM-19664 - continue with import even if one row has extid match

### PR DESCRIPTION
**Pull request by jmcclelland**
* [CRM-19664](https://issues.civicrm.org/jira/browse/CRM-19664)

### CODE REVIEW

**Comment by petednz** [comment]
confirming that both Laryn and Fuzion have tested this patch and are using it on live sites.

Is the issue that the checks are failing. if so can @jitendrapurohit take a look?

**Comment by seamuslee001** [comment]
@petednz the issue is that there is style issues with the code https://test.civicrm.org/job/CiviCRM-Core-PR/15855/checkstyleResult/new/

**Comment by jitendrapurohit** [comment]
Not sure, but the ticket seems like a duplicate of https://issues.civicrm.org/jira/browse/CRM-20494 whose fix has been merged and included in 4.7.20 - https://github.com/civicrm/civicrm-core/pull/10276 @jmcclelland Does that fix work for you or changes made here fixes another use-case?

**Comment by jmcclelland** [comment]
There seems to be several similar patches.

I don't think CRM-20494 solves the problem as well as this patch because it will only work if both the external id and id are matched OR the user is skipping duplicates or not checking duplicates.

This patch should work in all cases.

Additionally, I have submitted https://issues.civicrm.org/jira/browse/CRM-19620 which also addresses the same line of code in CRM-20494, however, it adds a check for contacts that are deleted. I would prefer that both this patch and the patch submitted in CRM-20494 be merged and that CRM-20494  be closed as a duplicate.

**Comment by eileenmcnaughton** [comment]
@jmcclelland this has merge on pass but has not been merged, apparently through oversight. Has anything changed since that label was given?

**Comment by jmcclelland** [comment]
Not to my knowledge - PTP has been running this patch for several months.

**Comment by eileenmcnaughton** [comment]
thanks

**Pull request merged**
