### PR TITLE
CRM-21585 - Fix erasing membership start_date when membership batch data entry

### PR DESCRIPTION
**Pull request by chandana-bandara**
Overview
----------------------------------------
This PR fixes the issue of membership start date erasing issue when making batch membership data entry

Before
----------------------------------------
The input field for membership's starting date is empty in membership batch data entry

After
----------------------------------------
The input field for membership's starting date get populated with the member's existing membership starting date in membership batch data entry

Comments
----------------------------------------
Not sure if the initial functionality was intentional. I.e. not populating the membership's starting date.

---

 * [CRM-21585: Batch Date Entry Membership Renewal erases start date](https://issues.civicrm.org/jira/browse/CRM-21585)

### CODE REVIEW

**Review by tommybobo — APPROVED** [review]

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by jitendrapurohit** [comment]
@coolbit Jenkin test is failing as this PR has gone stale and need to be rebased.

**Comment by coolbit** [comment]
@jitendrapurohit Is there anything I should do here? I appreciate any documentation in that case.

**Comment by coolbit** [comment]
Shall I go ahead and rebase it to the master branch?

**Comment by jitendrapurohit** [comment]
You need to do this, for eg: from your terminal (on CRM-21585 branch) -

    $ git pull --rebase upstream master

where `upstream` is the `civicrm/civicrm-core` remote listed in `$ git remote -v`.

This will pull the latest changes to your local civicrm directory. 

- If there are conflicts
  - you need to resolve it manually, maybe you'll get the conflict in `templates/CRM/Batch/Form/Entry.tpl` file.
  - After resolving the conflict enter this into your terminal.

        $ git add <filepath>
        $ git rebase --continue

- Push the latest code to your branch.
   
      $ git push origin CRM-21585 (use -f option before `origin` if not pushed with this command).

where `origin` is the `coolbit/civicrm-core` remote listed in `$ git remote -v`.

Hope that helps! If not, you can create a new branch and re-submit a new pull request and close this one.

**Comment by jitendrapurohit** [comment]
@coolbit I saw the "before edited" comment of yours which said you needed a documentation. Anyway, the above can work and yes you need to rebase it to the master branch.

**Comment by coolbit** [comment]
In the master branch, https://github.com/civicrm/civicrm-core/blob/master/templates/CRM/Batch/Form/Entry.tpl has my patch applied already. Is that it or is there anything else I need to do to make it complete?

**Comment by jitendrapurohit** [comment]
ok - I see the change made in this PR is already submitted https://github.com/civicrm/civicrm-core/pull/11202 and merged into CiviCRM version 4.7.30. So you can now close this pull request.

**Comment by monishdeb** [comment]
@coolbit I am closing this PR in favor of #11202 which is already merged against 4.7.30. Thanks!

**Comment by coolbit** [comment]
@monishdeb Sure. No worries.

**Pull request closed without merging**
