### PR TITLE
CRM-17036 - Getting started 4.6

### PR DESCRIPTION
**Pull request by sunilpawar**
- [CRM-17036: Getting Started dashlet widget](https://issues.civicrm.org/jira/browse/CRM-17036)

### CODE REVIEW

**Comment by totten** [comment]
If you rebase, the style error should go away.

**Comment by kurund** [comment]
@sunilpawar can you rebase this or submit new PR for 4.6

**Comment by colemanw** [comment]
@sunilpawar have you verified that adding this change in 4.6 will not be a problem when upgrading to 4.7 (e.g. the data will not be added twice?)

**Comment by sunilpawar** [comment]
We have added check in upgrade process for 4.6 and 4.7 to avoid duplicate record

**Comment by colemanw** [comment]
Rebased as https://github.com/civicrm/civicrm-core/pull/7278

**Pull request closed without merging**
