### PR TITLE
CRM-19327 - remove invalid SQL character

### PR DESCRIPTION
**Pull request by caracolmzd**
resolve issue CRM-19327
 posted to SE: https://civicrm.stackexchange.com/questions/12647/what-causes-the-sms-system-to-stop-working-and-throw-db-errors

---
- [CRM-19327: DB error for SMS mailing job](https://issues.civicrm.org/jira/browse/CRM-19327)

### CODE REVIEW

**Comment by yashodha** [comment]
@GinkgoFJG  Can you please file an issue in JIRA for the same.

**Comment by GinkgoFJG** [comment]
I think this mention was meant for @ginkgomzd.

**Comment by yashodha** [comment]
@GinkgoFJG  You're right :)
@ginkgomzd Can you please file an issue in JIRA for the same.

**Comment by ginkgomzd** [comment]
https://issues.civicrm.org/jira/browse/CRM-19327

**Pull request merged**
