### PR TITLE
dev/core#5440 fix admin-only price field display

### PR DESCRIPTION
**Pull request by awestuk**
https://lab.civicrm.org/dev/core/-/issues/5440

### CODE REVIEW

**Comment by awestuk** [comment]
I don't _think_ the fails are related

**Comment by demeritcowboy** [comment]
I'm not sure what the right fix is - this is called from a few places, otherwise I would say assign the adminFld var in php. Given it's a recent bug I'd say this is ok for now, but the PR should be rebased against 5.78.

The eventual goal is to get rid of php calls in smarty and call_user_func only works right now because there's temporarily allowance for it.

**Comment by awestuk** [comment]
Maybe even just not supply the admins fields in the array at all, for non-admins? I'll have a look.

**Comment by eileenmcnaughton** [comment]
@awestuk - I haven't tested this but I think this approach would work https://github.com/civicrm/civicrm-core/pull/31087

**Comment by demeritcowboy** [comment]
Closing since the other PR was merged. I'll put up a 5.77 backport of it.

**Pull request closed without merging**
