### PR TITLE
Add Unit Test for :CRM-20840 - ensure no receipt for recur payment if contrib page says …

### PR DESCRIPTION
**Pull request by jmcclelland**
…no receipt

Here's a failing test to start with.

Overview
----------------------------------------
Ensure the if a recurring payment is made using a contribution page with receipts turned off, CiviCRM should not send any receipts.

Before
----------------------------------------
If a recurring payment is made using a contribution page with receipts turned off, a receipt is still generated on each payment (tested using authorize).

After
----------------------------------------
WIP - no code changes made.

Technical Details
----------------------------------------

Comments
----------------------------------------
See test

### CODE REVIEW

**Comment by jmcclelland** [comment]
@eileenmcnaughton any ideas? I have managed to write a failing test, but I'm stuck with the fix.

I _think_ the problem/fix has something to do with `CRM_Contribute_Form_Contribute_Confirm::processFormContribution()` but it seems that my test doesn't invoke this code.

**Comment by eileenmcnaughton** [comment]
@jmcclelland the reason the test is failing is in the set-up here

https://github.com/JKingsnorth/civicrm-core/blob/3137781d03c0b140f79b1cb11590f40cb9bac2e7/tests/phpunit/CiviTest/CiviUnitTestCase.php#L3148-L3148

Because is_email_receipt is not set when the recurring contribution is created it defaults to the db default which is 1. I'm not sure if this is a clue to the bug you are experiencing, or whether it suggests the test is not exactly mimicing your issue

**Comment by jmcclelland** [comment]
@eileenmcnaughton - thanks for the response. If I manually override in the test when creating the recurring contribution, and set is_email_receipt=0, then the test succeeds. But... when running through the steps manually the receipt is sent. 

It seems that the logic for sending receipts is solid: api level takes precedence, then the civicrm_contribution_recur table's is_email_receipt, and lastly the contribution page.

The problem is that the civicrm_contribution_recur record seems to get set incorrectly when the recurring contribution is initially created and I think it's in the `CRM_Contribute_Form_Contribute_Confirm::processFormContribution()` function.

Maybe I need to devise a test that simply tries to create a recurring contribution, but follows a code path that uses that function?

**Comment by eileenmcnaughton** [comment]
@jmcclelland try this

https://github.com/aydun/civicrm-core/blob/15fb6a061e26325038575291b3dfe5822ceaacc5/tests/phpunit/CRM/Contribute/Form/ContributionTest.php#L256-L256

**Comment by jmcclelland** [comment]
Thanks Eileen! That seems to be exactl what I was looking for.

I did have to modify the CRM_Contribute_Form_Contribution::testSubmit() so it returns the contribution. Do you see any problems with that?

Now I get a success when I'm expecting a failure, so closer but still not done.

**Comment by jmcclelland** [comment]
Also, @eileenmcnaughton, I'm avoiding an authorize.net error about a duplicate subscription by randomly setting the street number. Is there a better way?

**Comment by eileenmcnaughton** [comment]
@jmcclelland there was a patch merged that might relate to this in the past day or so, so if it's passing & should not just check that the issue is not that it got fixed by someone else.

Re street address, really we want a.net to do mock responses but that is complex & involves different php versions :-( - your hack seems ok

**Comment by eileenmcnaughton** [comment]
but maybe use timestamp so it will always be different if not too many digits?

**Comment by jmcclelland** [comment]
Thanks again for the feedback Eileen. Authorize seems to accept an address number that is a timestamp (as the time stamp gets longer that could change - but I think we can reasonably cross that bridge when we get there). 

And I'm ready to commit this as a test-only PR. I think the fix must have happened else where. It's also possible that the fix mean that NEW recurring contributions have is_email_receipt properly set. However, a recurring contribution that was created before the fix might have that set to 1. So it would require a data update to fix previous ones.

In any event... if checks pass on my last commit, then I think it's ready to go.

**Comment by eileenmcnaughton** [comment]
Merged!

**Pull request merged**
