### PR TITLE
CRM-16858 fix - Participant Status & ID error in adv.search builder

### PR DESCRIPTION
**Pull request by monishdeb**
- [CRM-16858: Participant Status & ID error in adv.search builder](https://issues.civicrm.org/jira/browse/CRM-16858)

### CODE REVIEW

**Comment by davecivicrm** [comment]
Jenkins, test this please.

**Comment by monishdeb** [comment]
Jenkin, test this please

**Comment by monishdeb** [comment]
Jenkin, test this please

**Comment by totten** [comment]
Oooh, I don't what's going on, but that's -13 SLOC on an 1100 SLOC function. Hoowa! :)

**Comment by kurund** [comment]
jenkins, test this please

**Comment by davecivicrm** [comment]
Previous test failure is unrelated. (api_v3_CustomValueTest.testCreateCustomValue)

**Comment by monishdeb** [comment]
Test failure is unrelated.

**Pull request merged**
