### PR TITLE
Add unique constraint on ufmatch user ID+domain ID

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Currently it is possible to map more than one contact ID to a single (CMS) user ID in the UFMatch (civicrm_uf_match) table. This is not desired because we do not support multiple contacts for a single user account.

Before
----------------------------------------
Can create multiple contacts for a single user account.

After
----------------------------------------
Unique constraint does not allow more than one contact mapped to a single user ID / domain.

Technical Details
----------------------------------------
Adds a unique constraint on the table

Comments
----------------------------------------
@colemanw @artfulrobot I understand the table is being handled differently in standalone?

### CODE REVIEW

**Comment by awestuk** [comment]
What happens if there are some in the database already? You know, hypothetically, asking for a friend...

**Comment by mattwire** [comment]
test this please

**Comment by mattwire** [comment]
@MegaphoneJon @awestuk I can only think of a pre-upgrade message or something.

**Comment by totten** [comment]
> (@mattwire) I can only think of a pre-upgrade message or something.

+1

> (@artfulrobot) v 5.x ... v 5.(x+1) ...

It seems like the idea is to give a time-period for adapting. But different sites follow different upgrade paths.

If the idea was to make the step deferrable/discretionary, then that would also the job. But that kind of thing has to be improvised currently. (*See also: [wish for deferrable steps]](https://lab.civicrm.org/dev/core/-/issues/4581)*)

**Comment by mlutfy** [comment]
Would it be possible to disable foreign key checks while the key is added? I've run into similar issues before, and it makes it possible to at least fix the index, and the old data can be cleaned up later.

i.e.

```
CRM_Core_DAO::executeQuery("SET FOREIGN_KEY_CHECKS = 0;");
// add key
CRM_Core_DAO::executeQuery("SET FOREIGN_KEY_CHECKS = 1;");
```

I added a system check on our monitoring for this, and so far discovered two sites having the issue (2 sites being a very small subset of our sample).

https://lab.civicrm.org/extensions/symbiotic/-/blob/master/CRM/Symbiotic/Utils/Check/DuplicateUFmatch.php

**Comment by mattwire** [comment]
I've refactored this and implemented it *only* as a system check. If the index does not exist it will try to add it if there are no duplicates. If there are duplicates it will show an error message in the system checks and a link to the docs (need to add the docs..)

**Comment by twomice** [comment]
Late to the party. Can someone describe (if known) the conditions whereby mulitple contacts could be linked to a single CMS user?

**Comment by mattwire** [comment]
> Late to the party. Can someone describe (if known) the conditions whereby mulitple contacts could be linked to a single CMS user?

@twomice Unfortunately not. Like your issue it happened on one site more than once but I never got to the bottom of it.

**Comment by twomice** [comment]
@mattwire wrote:

> (need to add the docs..)

There's a ticket (https://lab.civicrm.org/dev/core/-/issues/5650) now because that link points to a "#todo" 404. Do you know if those docs were ever written up?

**Pull request merged**
