### PR TITLE
Remove always-true IF

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Remove always-true IF

Before
----------------------------------------
`$relationshipId` is set to NULL so ` if (!$relationshipId) {` is always true

After
----------------------------------------
If removed - here is how the patch looks with w=1

image

Technical Details
----------------------------------------
This is all just whitespace - but it's a hard to read diff 

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw if you are still about can you MOP this?

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
@eileenmcnaughton this trick still works for making the diff easier to read: https://github.com/civicrm/civicrm-core/pull/22399/files?w=1

**Comment by eileenmcnaughton** [comment]
@colemanw yep that is where the screen shot is from!

**Pull request merged**
