### PR TITLE
Fix links for tabs on manage event

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
See https://github.com/civicrm/civicrm-core/pull/12747#discussion_r236948035

Before
----------------------------------------
Links to manage event tabs broken following work on "selected tab" functionality.

After
----------------------------------------
Links to manage event tabs working.

Technical Details
----------------------------------------
Events are "unique" in that each tab has it's own full URL, whereas all other "tabheader" pages in CiviCRM use a single link and a "selectedChild" parameter to specify which tab to load.

Comments
----------------------------------------
@jitendrapurohit Please review.

### CODE REVIEW

**Comment by mattwire** [comment]
This will need to go against the RC if we are happy with it

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit what do you think? @mattwire yes - can you transfer it to the rc?

**Review by jitendrapurohit — APPROVED** [review]
Tested on the manage event page - works fine 👍 Thanks @mattwire

**Comment by eileenmcnaughton** [comment]
Ok this needs to be against 5.8 - I'm a little on the fence about whether it is the best fix - but it resolves the issue in the rc

**Comment by mattwire** [comment]
@seamuslee001 Rebased onto 5.8

**Comment by seamuslee001** [comment]
Merging as per the tag and Jitendra's review thanks @mattwire

**Pull request merged**
