### PR TITLE
fix for regression on saving contributions from backend

### PR DESCRIPTION
**Pull request by MegaphoneJon**
Overview
----------------------------------------
https://chat.civicrm.org/civicrm/pl/tptdmnjfypr5t84qes99dbz6me

### CODE REVIEW

**Comment by seamuslee001** [comment]
@MegaphoneJon test fails relate e.g. CRM_Batch_Form_EntryTest::testMembershipRenewalDates
Undefined index: fields /home/jenkins/bknix-dfl/build/core-21110-6sebs/web/sites/all/modules/civicrm/CRM/Financial/BAO/Order.php:408 @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
I just tried & failed to replicate this - I'm going to try installing line item editor in case that relates

**Comment by eileenmcnaughton** [comment]
So this was fixed in master - but obviously after the 5.40 rc was cut. The following lines are what is in 5.41 & appear to fix it to me - https://github.com/civicrm/civicrm-core/pull/21118

**Comment by eileenmcnaughton** [comment]
Closing in favour of #21118

**Pull request closed without merging**
