### PR TITLE
CRM-14126: Updating HttpClient to use HttpGuzzle instead of CURL

### PR DESCRIPTION
**Pull request by omarabuhussein**
I have updated httpclient to use httpGuzzle library instead of curl , so now the users can download any extension even if  open_basedir is set .

---
- [CRM-14126: HttpClient.php library used by CiviCRM issues a PHP warning when open_basedir is set](https://issues.civicrm.org/jira/browse/CRM-14126)

### CODE REVIEW

**Comment by colemanw** [comment]
jenkins, add to whitelist

**Comment by omarabuhussein** [comment]
@colemanw 

Any idea why the test failed ? the test result show no error.

**Comment by colemanw** [comment]
jenkins, retest this please

**Comment by omarabuhussein** [comment]
@colemanw 

the build failed because it can't find the  'GuzzleHttp\Client'  class which i added as a dependency to composer.json .... does jenkins skip composer.json file ?

**Comment by colemanw** [comment]
The composer.json looks fine. What might be the problem is that I don't see how you are attempting to include it at runtime - I don't see anything like a `require_once` in the patch.

**Comment by omarabuhussein** [comment]
isn't the autoloader will autoload these classes ?

**Comment by colemanw** [comment]
@totten if the problem is autoloading, I wonder if we ought to be including it at bootstrap.

**Pull request closed without merging**
