### PR TITLE
Afform - Support repeatable relationships

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Supports creating multiple relationships at once using the "Repeatable" feature in the relationship fields.

See https://chat.civicrm.org/civicrm/pl/r3nw5p4z9jyg9gx61dndp99ipe

Before
----------------------------------------
Relationship blocks could be repeated, but only the first one would save

After
----------------------------------------
All repeated relationships save.

### 1. Create form, add relationship fieldset and make it repeatable

image

### 2. When filling out form, click the "Add" button to add multiple relations

image

### 3. Relationships have been created

image

### CODE REVIEW

**Comment by michaelmcandrew** [comment]
@colemanw - any reason why we can't get this merged? Are you waiting on some testing or feedback? Would be great to get it out the door soon.

**Comment by colemanw** [comment]
@michaelmcandrew it's just the usual bottleneck. I've made the PR but no one has reviewed it, but IMO it's ready to merge.

**Comment by michaelmcandrew** [comment]
No problem @colemanw - I think @kurund can review if that works?

**Comment by mattwire** [comment]
I applied it to a couple of test sites but found it a bit confusing. I don't know if it's working as expected or if these are the case without this patch but I found:
- Don't seem to be able to add relationship fields without manually adding relationship fieldset from list first.
- Can't see how to make them repeatable

**Comment by kurund** [comment]
@mattwire 

Here is a sample form to collect related information.

Screenshot from 2023-01-12 20-00-36

**Comment by kurund** [comment]
@colemanw 

I tried using above form and the relationship data is not saved.

There are no errors. Am I missing something?

**Comment by kurund** [comment]
@mattwire 

Here is a sample form with `repeatable` fields.

Screenshot from 2023-01-12 20-16-51

**Comment by kurund** [comment]
@colemanw 

Relationship data is not saved using above form. Am I missing something?

**Comment by colemanw** [comment]
@kurund based on the above screenshot you are trying to create a relationship between two individuals of type "team member is" - that sounds like a relationship type that's meant to go between an individual and an organization?

**Comment by colemanw** [comment]
@kurund @mattwire I've updated the description with some screenshots. Hope that helps.

**Comment by kurund** [comment]
> @kurund based on the above screenshot you are trying to create a relationship between two individuals of type "team member is" - that sounds like a relationship type that's meant to go between an individual and an organization?

@colemanw 

I have created a new relationship type between Individual and Individual
Screenshot from 2023-01-20 17-10-47

Then tried to configure form
Screenshot from 2023-01-20 17-18-46

Form is not saved and getting below error in the console.
Screenshot from 2023-01-20 17-13-58

Not that if I switch to `child of` as per your example it's working fine.

**Comment by kurund** [comment]
@colemanw 

Looks like this branch has conflicts. Let me know once it's resolved and when above issues are fixed.

**Comment by colemanw** [comment]
@kurund I've rebased this, and it now includes @mattwire's changes from #25620 which fix the reciprocal relationship bug you noted. So I think this is good to go now.

**Pull request merged**
