### PR TITLE
Use getter function for entity id as on some forms  is protected.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Use a getter function to access $this-_id as on some forms it is protected. Follow up to Follow up to https://github.com/civicrm/civicrm-core/pull/12095

Before
----------------------------------------
No change

After
----------------------------------------
no change

Technical Details
----------------------------------------
The affected function was extracted in #12095 & is only called from one place. This is a trivial tweak to it

Comments
----------------------------------------
@mattwire

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @colemanw any chance one of your can merge this - it's a follow up from something v recently merged (per above)

**Comment by seamuslee001** [comment]
@eileenmcnaughton what if a form doesn't define `function getEntityId`

**Comment by eileenmcnaughton** [comment]
@seamuslee001 it is a newly added function currently only called from one form - which is fixed to have that function in this PR

**Comment by seamuslee001** [comment]
I'm satisfied that this is only affecting the only form that this function uses, however do you think we should do a if function_exists check at all and throw an exception if not to make sure no one adds to the form without adding the relevant function?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I think anyone adding it to a form & testing it would see the error pretty clearly!

**Comment by eileenmcnaughton** [comment]
(ie. a hard fail would be better than a soft fail if they don't add the function)

**Comment by seamuslee001** [comment]
(*CiviCRM Review Template WORD-1.1*)



* ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) Pass
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) Pass
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) Pass
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) Pass
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) Pass
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) Pass
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) Pass
* ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) Pass

**Pull request merged**
