### PR TITLE
CRM-20062 - new counties of Kenya

### PR DESCRIPTION
**Pull request by nowszy**
New counties of Kenya.
Refs: https://issues.civicrm.org/jira/browse/CRM-20062

### CODE REVIEW

**Comment by seamuslee001** [comment]
@mlutfy can you take a look at this and see what you think?

**Comment by eileenmcnaughton** [comment]
I think my reservation is the same as @JKingsnorth here - ie. I agree with keeping the former provinces for upgraded sites, but feel like it's not a good idea for new installs.

Does anyone feel there is a case for new installs? 

Unfortunately this has also gone stale :-(

**Comment by xurizaemon** [comment]
Since this is SQL-via-.tpl, would it work to add some check that identifies if there are any entries in `civicrm_address` using an ID associated with a former province, then determines whether to rename existing KE province entries if any such addresses exist in the db, or remove them if there's no need to retain older provinces?

It might be more straightforward to do this in PHP than Smarty?

**Comment by eileenmcnaughton** [comment]
Can you check the alternative #9937, which takes @xurizaemon's suggestion about removing the old states if not in use, into account

**Comment by eileenmcnaughton** [comment]
Closing in favour of #9937 (which still needs review to be merged & incorporates feedback comments)

**Pull request closed without merging**
