### PR TITLE
CRM-20873 : Fix issue where getTree try to load is_public field before it is added in upgrade

### PR DESCRIPTION
**Pull request by seamuslee001**
… it is added in upgrade

@agileware Fozzy are you able to test this out to see if it helps

### CODE REVIEW

**Comment by agileware** [comment]
@seamuslee001 legend 👍  Glad you're authorised to implement this type of workaround.

Will test and report back.

**Comment by monishdeb** [comment]
@seamuslee001 I have updated the PR with https://github.com/civicrm/civicrm-core/pull/10662/commits/5f30cf81282ed57b3672648b34e67d3d856577cd commit where I have changed the logic to fetch the column names rather than adding/deleting the ```is_public``` key. Because this would safeguard any adding or deleting of new column from ```custom_group``` table.  What ya say?

**Comment by monishdeb** [comment]
As per discussion with @seamuslee001 on MM it seems like this particular ```getTree(..)``` fn is called whenever view cache is built during drush upgrade before this adding this new column ```is_public``` to customGroup table at DB and DAO. That leads to current issue, so I am reverting my last commit that eliminates the usage of version.

**Comment by monishdeb** [comment]
Tested, working fine.

**Pull request merged**
