### PR TITLE
dev/core#1941 Revert "Fix issues with select2 validation when it is part of hidden 'On behalf of organisation' block"

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------

This partially reverts commit 2ee6dbf5b8ee194e0d495d4ea8fc21575151973f which appears to have caused a minor regression

Before
----------------------------------------
Description per https://lab.civicrm.org/dev/core/-/issues/1941

After
----------------------------------------
@KarinG Can you confirm if the bug goes away with this

Technical Details
----------------------------------------

Comments
----------------------------------------
I haven't attempted to figure out a fix at this stage - I've just been trying to replicate & track it down- I suspect @mattwire would prefer to propose a fix than to have this reverted & we still have another day or so before we need to finalise this.

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton this will likely cause other regressions such as causing forms not to be able to be submitted if there is on behalf of set

**Comment by eileenmcnaughton** [comment]
@seamuslee001 yes - it worked inn my very limited testing - but I suspect this is not the last word on it. Having tracked it down I'm going to focus on the other regression & let others test / weigh in on this

**Comment by seamuslee001** [comment]
@eileenmcnaughton I just tested this on my local and it didn't fix the issue for but it did re-introduce the problem that the form would not submit

**Comment by eileenmcnaughton** [comment]
@seamuslee001 hmm so it seemed to fix if for me - in terms of the original problem - that wasn't a regression so removing a regression in favour of the original problem would be 'OK' at a pinch - but obviously if it doesn't even fix it....

**Comment by seamuslee001** [comment]
@eileenmcnaughton I tried on a completely different buildkit and you will see that the same problem still exists but you will see that with this patch the form cannot be submitted at all because the css class hasn't been added to the hidden select
onbehalfof

**Comment by eileenmcnaughton** [comment]
@seamuslee001 OK - I was only able to partially revert - it worked in my testing - but perhaps I missed something - I'll see if @mattwire has a fix overnight (since I'm looking at the other regression ATM)

**Comment by seamuslee001** [comment]
Hopefully this gif works @eileenmcnaughton you will note that after going back from the confirm step to the main steps the astrisks dissapear which is the problem here.
onbehalfof3

**Comment by KarinG** [comment]
The jquery edits: regessions - the ‘not being able to submit the Review Your Contribution’ being the major one. This is a minor one - and I’d say perhaps ok to leave it for now in favour of not risking re-regression on the major one.

**Comment by eileenmcnaughton** [comment]
I'll close for now

**Pull request closed without merging**
