### PR TITLE
CIVICRM-230 CRM-17040 Add unit tests for CRM-17040 - Import Contribut…

### PR DESCRIPTION
**Pull request by ghost**
Overview
----------------------------------------
First attempt at unit test for CRM-17040

Before
----------------------------------------
No unit tests, which is scary.

After
----------------------------------------
Unit tests! Happy place.

Technical Details
----------------------------------------
Unit tests.

Comments
----------------------------------------
Test all things.

### CODE REVIEW

**Comment by agileware** [comment]
Jenkins please test.

**Comment by agileware** [comment]
Appears that the test did not actually execute... doh!

**Comment by eileenmcnaughton** [comment]
It might be a mismatch between file name & class name

CRM_Contribution_Import_Parser_ContributionTest
vs
CRM/Contribute/Import/Parser/ContributionTest

**Comment by agileware** [comment]
@seamuslee001 this PR depends on this other PR, https://github.com/civicrm/civicrm-core/pull/10797

Is that included when Jenkins does it's test?

**Comment by seamuslee001** [comment]
@agileware No it only pulls in the current PR i could do a custom test run including both of them if needed

**Comment by agileware** [comment]
@seamuslee001 only if it's not a major PITA

**Comment by agileware** [comment]
Closing this PR. I've committed the tests against the original PR so that the two can be verified together, sorry for not doing that initially. See https://github.com/civicrm/civicrm-core/pull/10797

**Pull request closed without merging**
