### PR TITLE
Fix invalid markup on extension page - remove dots from ids & classes

### PR DESCRIPTION
**Pull request by colemanw**
Overview
-----
Fixes invalid html in the tpl.

Before
----
Rows in the table would have an id like "extension-org.civicrm.cividiscount" and a class like "crm-extension-org.civicrm.cividiscount"

After
-----
Rows have an id like "extension-cividiscount" and a class like "crm-extension-cividiscount".

### CODE REVIEW

**Comment by seamuslee001** [comment]
@colemanw should L35 be updated as well given that also generates strange markup?

**Comment by twomice** [comment]
@colemanw FYI, I tried changing the id (as on L35) and the collapse/expand functionality still works fine. Probably okay to change L35 and then test again.

**Review by twomice — APPROVED** [review]
(*CiviCRM Review Template WORD-1.1*)



* ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __Pass__
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __Pass__: There are 7 test failures under the test api_v3_JobProcessMailingTest::testConcurrency.testConcurrency; I can't imagine any possible way these failures could be related to this patch.
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __Pass__
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __Pass__
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __Pass__
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __Pass__: I visited the Extensions page on the jenkins test site and verified that the expand/collapse and "install" controls work as expected.
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __Pass__: This only changes HTML code, which end users do not examine.
* ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __Pass__: I can imagine this might break JavaScript or CSS in some custom extension, but considering the limited scope of this patch, and considering that the affected page is the Extensions Admin screen, it seems very unlikely any such extensions exist.

**Comment by seamuslee001** [comment]
Merigng as per @twomice 's review

**Pull request merged**
