### PR TITLE
CRM-21006 Ensure that Buttons are correctly displayed

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
Button title not displaying sanely, this fixes it

ping @jackrabbithanna @eileenmcnaughton @totten @seanmadsen 

Could one of you test these out, i think these are the problem issues

---

 * [CRM-21006](https://issues.civicrm.org/jira/browse/CRM-21006)

### CODE REVIEW

**Comment by seanmadsen** [comment]
I added a commit here. The commit message has some relevant details, but I'd like to explain a little more...

This PR touches many files but does the same exact thing in all of them &mdash; adds the Smarty [escape](https://www.smarty.net/docsv2/en/language.modifier.escape) modifier to variables that appear within `title` or `alt` attributes. There are lots of code locations, so I haven't tested each change from within the UI. But I really can't imagine how this could possible cause any harm. Many of these Smarty variables probably do *not* contain untrusted data, and thus do not *need* the `escape` modifier. But my reasoning here is that we're better safe than sorry. Worst case scenario, we end up with a title or alt text that is double encoded. This would be ultra-rare, and the effect would be minimal, in that `<` and `>` would display to the user as `&lt;` and `&gt;` in hover text or alt text. Super minor. So I think it's worth it to apply this fix. 

Code locations found with: 

```regex
(title|alt)=(['"])((?!\2).)*\{\$((?!(\|(escape|crmDate))|\}).)+\}((?!\2).)*\2
```

**Comment by seanmadsen** [comment]
Even though I worked on this PR, I think it's worth explicitly stating that I approve of the work from @seamuslee001 here and personally feel this PR is ready to merge.

**Comment by seanmadsen** [comment]
Oh one more thing &mdash; Why `alt` and `title`? Why *not* other HTML attributes like `src` etc? Because `alt` and `title` are much more likely than other attributes to contain untrusted data. If anyone can think of another HTML attribute which commonly contains untrusted data, I think it'd be worth plugging it into that regex and re-running it against the codebase.

**Comment by seamuslee001** [comment]
Test failure i believe is unrelated

**Comment by colemanw** [comment]
I agree this is better in than out. If there is any double-escaping we can sort that out later.

**Pull request merged**
