### PR TITLE
dev/core#158 group contacts list and export limits results to 500 records

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Issue: https://lab.civicrm.org/dev/core/issues/158
@lcdservices 

To reproduce:

 create a group and add > 500 contacts to it
 go to the manage groups page and click contacts for that group to get the listing
 select all records and choose the export contacts action
 only 500 records are selected for export

Before
----------------------------------------
Can only export 500 contacts

After
----------------------------------------
Can export "All" contacts.

Technical Details
----------------------------------------
The limit in CRM/Contact/Selector restricts the PrevNextCache to 500.  The PrevNextCache is only used for contact searches and appears to only be used when entering via Manage Groups.

Removing the PrevNextCache allows the contact searches/Manage Group UI to work like every other entity type - where this issue has not occurred.

### CODE REVIEW

**Comment by mattwire** [comment]
Note: 3 separate commits as the first two are safe and can be reviewed/merged without additional risk.  The first is entirely code cleanup, the second ensures that entityDAOName is set for contacts as well and is needed by the 3rd commit.

**Comment by lcdservices** [comment]
I ran through some tests of the two related issues:

- run an advanced search with "display results as" = activities; select rows and export activities (confirm the activity export context is retained)
- go to manage groups, view contact list, and export contacts (confirm all records exported when > 500)

I hit errors like:
Error: Cannot access protected property CRM_Export_Form_Select::$_task in CRM_Activity_Form_Task::preProcessCommon() (line 92 of /var/www/html/sites/all/modules/civicrm/CRM/Activity/Form/Task.php).

I went through and changed the protected properties to public in Core/Form/Task.php and Contact/Form/Task.php and both tests worked. Not sure if that's the best way to handle it though.

**Comment by mattwire** [comment]
> Error: Cannot access protected property CRM_Export_Form_Select::$_task in CRM_Activity_Form_Task::preProcessCommon() (line 92 of /var/www/html/sites/all/modules/civicrm/CRM/Activity/Form/Task.php).

@lcdservices Right.  When we originally added CRM_Core_Form_Task we just added it for cases. However, because you can switch contexts in advanced search and export is tied into the task framework we need all CRM_*_Form_Task entities that allow export to inherit from CRM_Core_Form_Task - then export can access the relevant properties.  I've just made that change and updated the PR - can you test again?

**Comment by lcdservices** [comment]
@mattwire Just ran another set of tests with that PR. Both test steps described above now work. No protected property errors and both scenarios worked as expected. However, it introduced a new regression -- when you perform search results and click "next" to navigate to the next page of results, the results open in a modal window instead of the existing search context. I confirmed that issue is definitely caused by this PR.

**Comment by eileenmcnaughton** [comment]
@mattwire - that's  a hell of a big patch given that we urgently need a patch in the rc before it is cut later this week - is there a smaller version of it that might give less pause for a last minute rc addition?

**Comment by eileenmcnaughton** [comment]
@mattwire I believe I identified the cause of the regression - #12273

Note that if there is not an outstanding bug I don't have a lot of appetite to make any further changes to these forms until any issues have settled down so can we close this out?

**Comment by eileenmcnaughton** [comment]
@mattwire I'm going to close this for now as the bug is otherwise fixed & there is an outstanding issue with this PR. Also, I'm disinclined to have another refactor in this area for a while if we can avoid it

**Pull request closed without merging**
