### PR TITLE
Add angular form to civiimport extension

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Add alternate import angular mapping form for contribution import in the civimport extension

Before
----------------------------------------
The underlying Import code supports more configuration, but the Quickform mapping screen does now

After
----------------------------------------
New functionality exposed via the `civiimport` extension. Civiimport currently ships disabled in core as an alpha extension. It already provides an api & search-kit interaction with the import tables. This PR also adds to is such that it replaces the `Mapping` form for contribution import. 

image

Technical Details
----------------------------------------
The intent is to follow a similar leap-by-extension approach as with the export UI. Ie initially cleanup the underyling code, then put a new UI in an extension as an option, eventually making it compulsory. In the case of CIviImport the eventual compulsory will be the extension & the core code will over time migrate out of core

Comments
----------------------------------------

### CODE REVIEW

**Comment by totten** [comment]
civibot, test this please

**Comment by eileenmcnaughton** [comment]
Test one

image

**Comment by eileenmcnaughton** [comment]
Test two - import with 'save' action for contact


image

image

image

Legal name added

image

**Comment by eileenmcnaughton** [comment]
Note I'm updating over here as I test it https://docs.google.com/spreadsheets/d/1lW9Xob111SU78f-G-YX8dfXsYHyKJsi-eCQG3mvOkl4/edit?usp=sharing

**Comment by colemanw** [comment]
Code looks pretty good. One general note about the Angular code is that in 2022 I can only think of one reason why you would ever create a `Controller`, and that is if you are using `NgRoute` which requires controllers.

In every other case including this one the code is nicer if you use a `Component`. For one thing it allows you to stop polluting the `$scope` variable with every kitchen sink. A component automatically assigns just one thing to `$scope`: a variable named `$ctrl` which is an alias to itself. Everything else can go in there. So instead of `$scope.myFunction = function()` in the controller, you can do `this.myFunction = function()` in the controller and then reference it in the template using `$ctrl.myFunction`.

**Comment by eileenmcnaughton** [comment]
hmm - I think civix still creates a controller - I can look at switching if I can get my head around it

**Comment by eileenmcnaughton** [comment]
@colemanw does it make a difference to whether it makes sense to try to switch over if it is possible it might be a page at some point - ie if the quickform goes away in the future

**Comment by colemanw** [comment]
Nope, no difference. I use `Components` everywhere.

**Comment by eileenmcnaughton** [comment]
But not in the place I looked to for 'how-to'

image

**Comment by colemanw** [comment]
Here's an example: https://github.com/civicrm/civicrm-core/blob/0709aeed842fd3e4711f65a5bf1cc7ecddff62f6/templates/CRM/Queue/Page/Monitor.tpl#L1-L3

**Comment by colemanw** [comment]
@eileenmcnaughton here's a better example :)
https://github.com/civicrm/civicrm-core/pull/24581/files?w=1

**Comment by eileenmcnaughton** [comment]
@colemanw I converted the main controller & it's working! - I wasn't brave enough to take on the inner controller (in part because I hit a regression when digging in in & am now gonna start reading about testing..... )

**Pull request merged**
