### PR TITLE
[REF] Convert Elavon Payment Processor to be a core Extension

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This Converts Elavon to be a core extension and adds in a unit test on the Payment Processor

Before
----------------------------------------
Elavon Payment Processor shipped in core

After
----------------------------------------
Elavon Payment Processor shipped as a core extension and disabled by default

Note I did the upgrade script for 5.54.alpha1 because I figured we would do this post branching but it seems branching has been delayed a while

ping @eileenmcnaughton @totten @monishdeb

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This looks good from a code point of view - I'm going to r-run the install & rely on your test / your prod site testing ./ the fact the processor part is pretty well worn code for the `Elavon` functionality

A couple of points though
- `mixins` - my understanding is we don't need to include the `mixin` folder for extension releases that don't support earlier CiviCRM versions (including core extensions`
- `mgd` values for `cleanup` and `update` - I think the new install will wind up with `unused` for `cleanup` - which probabaly should be the default (even thought I personally mistrust it). I'm not sure about 'update` flip a coin

**Comment by seamuslee001** [comment]
Re Mixins I just presumed we committed everything and the Mixin files were there just as a backup

**Comment by eileenmcnaughton** [comment]
I checked a handful of other core extensions & they were 'mixin-free`

**Comment by colemanw** [comment]
Correct, and if you are using the latest version of Civix, it should not have generated the `mixin` directory if your `<ver>` is set high enough in `info.xml`, which it is so I'm not sure what's going on there, but at any rate the directory can be removed.

**Comment by seamuslee001** [comment]
ok I have removed the mixin folder and rebased to fix the conflict but I think this should be fine

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton is there any other issues with this PR now?

**Comment by eileenmcnaughton** [comment]
I'll wait & see if tests pass & then give it an r-run

**Comment by seamuslee001** [comment]
@eileenmcnaughton this is now rebased and as mentioned in call the upgrade tests some how cover both ways i.e. when you have payment processors of type elavon and when you don't

**Comment by eileenmcnaughton** [comment]
I gave this an r-run on the upgrade but am relying on the tests for the processor functionality as I don't have a way to test & the process @seamuslee001 went through to add tests on that first was solid

**Pull request merged**
