### PR TITLE
CRM-20780 Add drupal option to define CMS_ROOT

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
* [CRM-20780: Add drupal option to define CMS_ROOT](https://issues.civicrm.org/jira/browse/CRM-20780)

### CODE REVIEW

**Comment by seamuslee001** [comment]
I'm ok with it

**Comment by totten** [comment]
Why does this need a new constant? In `civicrm.settings.php`, can't one now say:

```
global $civicrm_paths;
$civicrm_paths['cms.root']['path'] = '/var/ww/foo';
```

**Comment by eileenmcnaughton** [comment]
I can try that

**Comment by totten** [comment]
Erm, responding to my own comment a bit...

1. I do think it'll be long-term more coherent to handle path/url overrides through `$civicrm_paths` array.

2. There are a few older bits of code which explicitly call `cmsRootPath()`, eg [here](https://github.com/civicrm/civicrm-core/blob/4.7.20/CRM/Extension/System.php#L106) or [here](https://github.com/civicrm/civicrm-core/blob/4.7.20/CRM/Utils/System/Base.php#L657). These call-paths don't currently respect the global `$civicrm_paths`. One of this should solve that:

   * Search/replace. Most places currently calling `cmsRootPath()` should instead call `Civi::paths()->getVariable('cms.root', 'path');`
   * Hotwire. Use a patch just like this one you wrote, but -- instead of reading `CMS_ROOT` -- read `$GLOBALS['civicrm_paths']['cms.root']['path']`.

**Comment by eileenmcnaughton** [comment]
@totten kinda snap - I tried it & this worked find - so I'll swap to that

```
    global $civicrm_paths;
    if (!empty($civicrm_paths['cms.root']['path'])) {
      return $civicrm_paths['cms.root']['path'];
    }
```

**Comment by eileenmcnaughton** [comment]
I have merged @totten addition & I'm taking that plus previous discussion as approval & adding merge-on-pass

**Pull request merged**
