### PR TITLE
dev/core#585 Fix setting target contact on activities when creating a case with activity sequence.

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/issues/585

Before
----------------------------------------
Case sequence activities created with no target contact.

After
----------------------------------------
Case sequence activites created with target contact.

Technical Details
----------------------------------------
I don't claim to fully understand how this works and why it regressed in 5.6 but my proposed fix just adds the target contact id to the params passed to the activity.create api.

Comments
----------------------------------------
@stoob

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire can you put this against 5.9?

**Comment by eileenmcnaughton** [comment]
@colemanw can you review this?

**Comment by lcdservices** [comment]
I was able to reproduce the issue and have confirmed the PR fixes the issue. The first follow-up activity has a target contact, as do subsequent activities as preceding ones are completed.

**Comment by eileenmcnaughton** [comment]
Thanks @lcdservices - merging!

**Pull request merged**
