### PR TITLE
CRM-17959 - allow URL to be redirected if the queue ID is invalid but…

### PR DESCRIPTION
**Pull request by andrew-cormick-dockery**
… the URL ID is OK

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins test this please 

Note this should still get core teams's eyes on it

**Comment by totten** [comment]
jenkins, add to whitelist

**Comment by seamuslee001** [comment]
Test failures look unrelated to this PR @totten perhaps related to change in phpunit?

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
@totten  I think this is OK - any concerns from your side? $turl is not user input so the lack of escaping seems OK

**Comment by kcristiano** [comment]
tested PR:

Steps to reproduce:

- Create a mailing with external links (eg https://civicrm.org)
- Send mailing
- test that links work properly 
- delete rows from civicrm_mailing_event_queue table
- Click links in email again- expected behavior is redirect to sites home page

Condition Reproduced.

Applied patch - Manually.  Note @totten doing hub checkout <PR> rolled CiviCRM back to a prior version and introduced an unrelated error.   Therefore, cherry picking or applying the patch was the only way to go here.

After Patch perform the following steps:

- Go back to email
- click links in email
- They now are resolved properly

Further tests:
- deleted row from civicrm_mailing_trackable_url - Note ID
- Find that ID in email click on that link.  Expected to be redirected to home page
- works properly

Also verified with WordPress and Joomla 

@eileenmcnaughton PR looks good to merge.

**Comment by mlutfy** [comment]
Discussed with @seamuslee001, we should use CRM_Utils_Rule::mysqlColumnNameOrAlias() to filter the variable in the SQL query.

We will discuss with Tim and probably open a followup PR to address this.

**Comment by eileenmcnaughton** [comment]
Thanks guys!

**Comment by mlutfy** [comment]
For reference, followup SQL fix and test added in : https://github.com/civicrm/civicrm-core/pull/8516

**Pull request merged**
