### PR TITLE
CRM-21434: Add activities to recent items on view and edit

### PR DESCRIPTION
**Pull request by niels-heinemann**
When viewing activities push them to the recent items stack.

---

 * [CRM-21434: Add activities to recent items on view and edit](https://issues.civicrm.org/jira/browse/CRM-21434)

### CODE REVIEW

**Comment by mlutfy** [comment]
Hi,

Can you open a JIRA issue? https://docs.civicrm.org/dev/en/latest/core/contributing/

The test errors seem to be syntax-related, but from the github UI I don't think it shows the presence of tabs. Can you double-check?

This is a new feature that might be somewhat disruptive to users who are not used to seeing activities in the Recent Items.

* Is it disabled by default?
* Have you tried implementing this as an extension? (hooks buildForm and pageRun should help)

**Comment by nielosz** [comment]
https://issues.civicrm.org/jira/browse/CRM-21434
Changed tabs to spaces.

Activities were added to the stack before but in an inconsistent manner. Some activities were, some not. I couldn't identify a rule which was followed. So this PR brings value to people who want activities to be seen in the stack. People disliking this feature may deselect activities provider in the corresponding setting (civicrm/admin/setting/misc -> Recent Items Providers). I do not think they would benefit from keeping the current random selection.

**Comment by mlutfy** [comment]
Ah, hmm, right. Looking at other entities, they either get added to Recent Items from the BAO or the Form class, often both.

The Activity BAO has quite a few conditions on how to add activities to the Recent Items (mostly permission-related), as well as parameters such as `skipRecentView`. Maybe that code should be moved to a function, and call that from the Form class?

Do you have a specific use-case where an activity wasn't being added to the Recent Items?

**Comment by nielosz** [comment]
Thanks for your review! Activity BAO calls RecentItems's Add method only on create. Handling the view action here seems quite complicated and I don't know any massive benefits. Do you?

**Comment by nielosz** [comment]
Hmm, I'm not sure if my english skills are sufficient but I'm reading this as "Push the update related code to the BAO". I'm gonna have a look.

**Comment by eileenmcnaughton** [comment]
@nielosz why don't you start by getting the view only part in a PR & merged since that part seems simple

**Comment by eileenmcnaughton** [comment]
@nielosz are you OK to rebase this & squash to a single commit.

@mlutfy I will merge the squashed 'view-only' version - unless you comment back to register concerns

**Pull request closed without merging**
