### PR TITLE
CRM-16188, added order api for create action with test

### PR DESCRIPTION
**Pull request by pradpnayak**
---
- CRM-16188: Create an order API
  https://issues.civicrm.org/jira/browse/CRM-16188

### CODE REVIEW

**Comment by pradpnayak** [comment]
depends on https://github.com/civicrm/civicrm-core/pull/7659

**Comment by pradpnayak** [comment]
jenkins, retest this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I think this is mostly OK but it's quite hard to see exactly how the api is looking reading it - can you generate some examples and add them to the commit?

You just need to run the tests without having defined anything that would block it - ie https://github.com/civicrm/civicrm-core/blob/master/tests/phpunit/CiviTest/CiviUnitTestCase.php#L2367

I'm not sure you are calling the callApiSuccessAndDocument here? It should be called once per entity/action combo and also for any variants that are worth documenting - but to do that you need to pass subparams

https://github.com/civicrm/civicrm-core/blob/master/tests/phpunit/CiviTest/CiviUnitTestCase.php#L1087

I'll take another look later - I couldn't just skim this

**Pull request merged**
