### PR TITLE
Add pager to bottom of Manage Contribution Pages

### PR DESCRIPTION
**Pull request by larssandergreen**
There was no pager at the bottom of the page, now there is.

### CODE REVIEW

**Comment by mattwire** [comment]
@larssandergreen Can you add a screenshot?

**Comment by larssandergreen** [comment]
@mattwire
image

**Comment by eileenmcnaughton** [comment]
Looks good

**Comment by KarinG** [comment]
Awesome 🎉 -> is that your first official contribution Lars? 👍

**Comment by eileenmcnaughton** [comment]
@KarinG I task you with finding the official party emjoi (I think it might not be @larssandergreen first but I still like party emjois)

**Comment by seamuslee001** [comment]
Jenkins add to whitelist

**Comment by larssandergreen** [comment]
@KarinG I think I've updated text here and there before, but more or less,
sure!

**Comment by KarinG** [comment]
Congrats! 🥳 

How did you create the screenshot? I was going to apply your patch to our ectemnia repo for you but you got it done somehow 🙂

**Comment by larssandergreen** [comment]
@KarinG It's from a test site, not ours. But we don't really need the patch
right away, not a big deal. I know now that there isn't a pager on the
bottom of that page.

**Pull request merged**
