### PR TITLE
Fixed pre hook params for LineItem

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/1994

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Thanks @pradpnayak - I've added merge-ready to give @monishdeb a bit longer to check in case it's used somewhere in the line item editor. Also @KarinG maybe

I don't think a test is needed on this one since we don't specifically test hook params on other pre hooks

**Comment by seamuslee001** [comment]
@eileenmcnaughton can you rebase

**Comment by eileenmcnaughton** [comment]
It's not my PR - @pradpnayak

**Comment by seamuslee001** [comment]
@pradpnayak this will need a rebase

I checked this out locally and then ran the lineitemeditors unit tests and they all passed so I think this is fine

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I kicked off the tests so I can swap merge-ready to merge-on-pass which is more accurately the intent

**Comment by seamuslee001** [comment]
Test fail unrelated

**Pull request merged**
