### PR TITLE
CRM-21276: Call the buildAmount hook before saving memberships in the backend

### PR DESCRIPTION
**Pull request by mlutfy**
Overview
----------------------------------------

See https://issues.civicrm.org/jira/browse/CRM-21276

Comments
----------------------------------------

I also tested with CiviDiscount (although I found some unrelated incompatibilities with cdntaxcalculator), it did not introduce a change in behaviour.

### CODE REVIEW

**Comment by mlutfy** [comment]
ping @JoeMurray Any thoughts?

**Comment by eileenmcnaughton** [comment]
@monishdeb @mlutfy this has been stalled a long time & I'm not quite sure what to do with it - I understand from the ticket that the issue is that the priceset is reloaded. It feels like that might be a bad thing to do (arguable) but if not it probably makes sense to call the hook in the getSetDetails function, or somewhere more generic.

Having said that the risk appears to only be calling the function twice on the same built set & that seems to be fairly clearly not happening here.

**Comment by eileenmcnaughton** [comment]
@monishdeb can you take a look at this at some point - I'm still unsure what to do

**Comment by mattwire** [comment]
@mlutfy I agree with this in principal.  However, is it possible to detect whether the buildAmount hook was called from the backend or the frontend?  As there are use-cases where it is desirable to only do things if run via the frontend.

**Comment by mlutfy** [comment]
@mattwire Maybe I am misunderstanding the question, but it seems like a separate issue? i.e. the hook does not currently allow that, and I mostly need to be able to apply tax calculations on pricesets in various places of CiviCRM. imho this patch fixes an inconsistency.

(In a buildAmount, you can check who is the currently logged-in user, which might also be authenticated by checksum, then check their permissions to see if they would have access to certain features?)

**Comment by mattwire** [comment]
>  imho this patch fixes an inconsistency.
@mlutfy I agree.  However, the fact that it didn't use to work on the backend may be something that extension developers have relied on.

For example my extension implements the buildAmount hook: 
https://github.com/mattwire/uk.co.mjwconsult.variablerecurpayments/blob/master/variablerecurpayments.php#L221

But for the client use-cases would be undesirable for the amounts to be modified when working via the backend.  I'm quite happy to modify the extension, but I'd like to be sure that there is actually a way to detect if the hook is being called from the backend, for example by ensuring that $this->isBackOffice is set before the hook is called.

**Comment by mattwire** [comment]
@mlutfy Actually, it's possible I am misunderstanding the issue.  I assumed when you said "backend" you meant "backoffice", ie. not frontend (contribution pages etc).  But maybe you actually mean the database?

Can you give an example workflow to clarify?

**Comment by eileenmcnaughton** [comment]
@mlutfy I'm going to close this out - I think we need more work to get this mergeable (testing, detail, analysis, is this the right approach etc) and I don't feel like this is on a priority list at the moment. We could move it to gitlab or just continue to track through JIRA

**Pull request closed without merging**
