### PR TITLE
Cleanup of api_v3_membership_create towards #11556

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
This is a partial of #11556 - it contains part of that code tidy up

Before
----------------------------------------
Code less maintainable

After
----------------------------------------
Code more maintainable

Technical Details
----------------------------------------
Adds commenting and rearranges the new/updated membership params if/else so it is clear what is being set in each case

@eileenmcnaughton This is an extraction towards #11556

### CODE REVIEW

**Comment by mattwire** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@omarabuhussein a reviewable chunk of that other one!

**Comment by eileenmcnaughton** [comment]
I went through this & agree there is no functional change, just a readability change. Merging

**Comment by omarabuhussein** [comment]
sorry I was on vacation on 3 days ago and missed it.

**Pull request merged**
