### PR TITLE
dev/core#2907 - Fix mailing contact tokens when flexmailer is disabled

### PR DESCRIPTION
**Pull request by cleardesign**
Overview
----------------------------------------
This PR should fix issue [2907 ](https://lab.civicrm.org/dev/core/-/issues/2907#note_80494)

Before
----------------------------------------
Having FlexMailer extension disabled when attempt to use contact tokens (ex: {contact.email_greeting_display}) in new mailing it will not work. 

After
----------------------------------------
Having FlexMailer extension disabled when attempt to use contact tokens (ex: {contact.email_greeting_display}) in new mailing, tokens will be processed successfully .

Comments
----------------------------------------
I am not sure if this is the right solution as this is the first time I touch civicrm core code. Please note that the problem with missing contact tokens appear only when FlexMailer extension is disabled.
The problem is there at least since 5.43 until current version 5.53.

### CODE REVIEW

**Comment by mlutfy** [comment]
add to whitelist

**Comment by mlutfy** [comment]
@cleardesign Thank you for submitting a pull-request! The automated tests will run to see if it finds any issues with the patch, then a review might look at it. Ideally, if people can test the patch, that will help move things forward.

Regarding flexmailer: the aim is to replace older bits of CiviCRM code that few people dare venture into (insufficient tests, old spaghetti code, etc). Running CiviCRM without flexmailer is still supported, the aim is still to eventually delete that code and require flexmailer (I think that was on the roadmap 2 years ago, but admittedly not a top priority).

**Comment by eileenmcnaughton** [comment]
There are a bunch of test fails - hidden in there will be the one tricky one that has held us back from making `flexmailer` mandatory - I'll try to find the gitlab - but is there a reason not to enable `flexmailer` - the net effect of this change is pretty similar to enabling `flexmailer`....

[Test Result](https://test.civicrm.org/job/CiviCRM-Core-PR/51541/testReport/) (19 failures / +19)
[CRM_Mailing_MailingSystemTest.testMailerPreviewExtraScheme](https://test.civicrm.org/job/CiviCRM-Core-PR/51541/testReport/junit/(root)/CRM_Mailing_MailingSystemTest/testMailerPreviewExtraScheme/)
[CRM_Mailing_MailingSystemTest.testBasicHeaders](https://test.civicrm.org/job/CiviCRM-Core-PR/51541/testReport/junit/(root)/CRM_Mailing_MailingSystemTest/testBasicHeaders/)
[CRM_Mailing_MailingSystemTest.testText](https://test.civicrm.org/job/CiviCRM-Core-PR/51541/testReport/junit/(root)/CRM_Mailing_MailingSystemTest/testText/)
[CRM_Mailing_MailingSystemTest.testHtmlWithOpenTracking](https://test.civicrm.org/job/CiviCRM-Core-PR/51541/testReport/junit/(root)/CRM_Mailing_MailingSystemTest/testHtmlWithOpenTracking/)
[CRM_Mailing_MailingSystemTest.testHtmlWithOpenAndUrlTracking](https://test.civicrm.org/job/CiviCRM-Core-PR/51541/testReport/junit/(root)/CRM_Mailing_MailingSystemTest/testHtmlWithOpenAndUrlTracking/)
[CRM_Mailing_MailingSystemTest.testMailingActivityCreate](https://test.civicrm.org/job/CiviCRM-Core-PR/51541/testReport/junit/(root)/CRM_Mailing_MailingSystemTest/testMailingActivityCreate/)
[CRM_Mailing_MailingSystemTest.testMailingReplyAutoRespond](https://test.civicrm.org/job/CiviCRM-Core-PR/51541/testReport/junit/(root)/CRM_Mailing_MailingSystemTest/testMailingReplyAutoRespond/)
[CRM_Mailing_MailingSystemTest.testUrlTracking with data set #0](https://test.civicrm.org/job/CiviCRM-Core-PR/51541/testReport/junit/(root)/CRM_Mailing_MailingSystemTest/testUrlTracking_with_data_set__0/)
[CRM_Mailing_MailingSystemTest.testUrlTracking with data set #1](https://test.civicrm.org/job/CiviCRM-Core-PR/51541/testReport/junit/(root)/CRM_Mailing_MailingSystemTest/testUrlTracking_with_data_set__1/)
[CRM_Mailing_MailingSystemTest.testUrlTracking with data set #2](https://test.civicrm.org/job/CiviCRM-Core-PR/51541/testReport/junit/(root)/CRM_Mailing_MailingSystemTest/testUrlTracking_with_data_set__2/)
[Show all failed tests >>>](https://test.civicrm.org/job/CiviCRM-Core-PR/51541/#showFailuresLink)

**Comment by eileenmcnaughton** [comment]
Ah - this is the issue - https://lab.civicrm.org/dev/core/-/issues/2898 - the ideal way forwards is to decide what to do about that & then make flexmailer mandatory & remove the code you are touching here

**Comment by mlutfy** [comment]
I think we can close this now that flexmailer is required?

**Pull request closed without merging**
