### PR TITLE
Add deceased date token

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Per https://github.com/eileenmcnaughton/nz.co.fuzion.civitoken/issues/63

### CODE REVIEW

**Comment by destrieux** [comment]
Hi it seems the build is over but some tests were not successful - best

**Comment by yashodha** [comment]
@eileenmcnaughton You need to add the token in advertised tokens
https://github.com/civicrm/civicrm-core/blob/master/tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php

**Comment by destrieux** [comment]
Hi

I edited 

wp-content/plugins/civicrm/civicrm/CRM/Contact/Tokens.php 
	to add 'deceased_date’, 
	under   protected function getExposedFields(): array {…

To add the token in advertised tokens, I understood from your post I needed to edit also 
wp-content/plugins/civicrm/civicrm/CRM/Core/BAO/MessageTemplate.php
	where I expected to find a section beginning with  " public function getAdvertisedTokens(): array {« 
	but it's missing on my side 

I probably did something wrong; sorry about this, and thanks for your help
Best

**Comment by eileenmcnaughton** [comment]
@destrieux you need to make the one line change from this PR. In addition the values are likely cached so you need to clear caches (or if you applied the line last night they may have cleared in the meantime.)

The token is {contact.deceased_date}

**Comment by destrieux** [comment]
Many thanks Works perfectly Envoyé de mon iPhoneLe 16 mai 2023 à 23:45, Eileen McNaughton ***@***.***> a écrit :﻿
@destrieux you need to make the one line change from this PR. In addition the values are likely cached so you need to clear caches (or if you applied the line last night they may have cleared in the meantime.)
The token is {contact.deceased_date}

**Comment by seamuslee001** [comment]
@eileenmcnaughton test fail relates

```
CRM_Core_BAO_MessageTemplateTest::testContactTokensRenderedByTokenProcessor
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 checksum |cs=6bef3620b989b8a46bb3c565f0d599f1_1684275337_168\n
 id |7\n
 t_stuff.favourite_emoticon |\n
+deceased_date |\n
 '

/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php:644
/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:229
/home/homer/buildkit/extern/phpunit8/phpunit8.phar:1721
```

**Comment by eileenmcnaughton** [comment]
test this please

**Pull request merged**
