### PR TITLE
Prevent missing activity data from API v3 calls

### PR DESCRIPTION
**Pull request by tbember**
Overview
----------------------------------------
On a given contact's Activities tab, when the sum of contacts referenced by "Added by", "With Contact", and "Assigned to" columns is large (> 25), there is missing/incomplete data on these fields.

Before
----------------------------------------
image

After
----------------------------------------
image

Technical Details
----------------------------------------
Activity API calls such as `civicrm_api3('Activity', 'get', $params)` return missing/incomplete "Added by", "With Contact", and "Assigned to" fields data when the sum of contacts referenced by these fields (across all returned activities) exceeds 25.

This happens because the contacts are fetched by an API call that is limited to return a maximum of 25 items.

Comments
----------------------------------------
In the proposed solution, the contacts are split into chunks of 100 items in order to prevent memory limit issues.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@tbember can you check out https://github.com/civicrm/civicrm-core/pull/14223

**Comment by eileenmcnaughton** [comment]
Thanks for digging into this - we also concluded the limit was the problem - the issue is https://lab.civicrm.org/dev/core/issues/942

However, in our tests we wound up with a bigger rewrite to cope with things like mailings with some thousands of recipients & performance in those instances. We are hoping to finalise a new code drop in the next few days - please test #14223 & see how it works for you

**Comment by eileenmcnaughton** [comment]
add to whitelist

**Comment by eileenmcnaughton** [comment]
@tbember also - I think this is your first PR - so .... welcome. 

If you hit a regression the product-maintenance & dev-post-release channels are a great place to check on chat.civicrm.org to see if anyone else has hit it & is working on it. You can also check the https://lab.civicrm.org/groups/dev/-/boards channel - & see what is in the regressions column for any unidentified regressions. This one was identified 3 days ago but the need for performance testing & some local issues I've had with a brick than used to be my laptop has slowed us down on it a bit - I would have preferred to have had a fix released by now

**Comment by tbember** [comment]
Hi @eileenmcnaughton, thanks for the information! This is very helpful.

I can confirm #14223 works for me too!

**Pull request closed without merging**
