### PR TITLE
FormBuilder: add af field container to facilitate easy styling

### PR DESCRIPTION
**Pull request by kurund**
Overview
----------------------------------------
There is no easy way to style all the elements belonging to `af-field`. My proposal here to add a container that will allow to control this and help in better styling especially on the frontend.

In the below example I have just increased spacing between fields. Note that css changes are not part of this PR as it depends on the theme etc.

Before
----------------------------------------
before

After
----------------------------------------
after

### CODE REVIEW

**Comment by colemanw** [comment]
I'm not sure I understand the motivation for this change. Currently, every `afField` is enclosed in an `<af-field></af-field>` tag. You can target those tags with css.

image

**Comment by kurund** [comment]
@colemanw 

I did try adding style to `af-field` but it does not work. I was thinking because it's a directive behaves slightly different. Am I missing something?

**Comment by colemanw** [comment]
CSS works on those elements, you just have to ensure your rule is specific enough to apply. I suggest you play around with it in your browser console. Remember that it's an element not a class, so your rule would be `af-field {}` not  `.af-field {}`! In Chrome I just select the element in my console and click the little [+] to add a new css rule. I note that it automatically suggested `af-field.af-field-type-text {}` - so that should also help with your styling efforts, every `af-field` element automatically gets a css class based on the type.

image

**Comment by kurund** [comment]
@colemanw 

Above didn't work on CiviCRM 5.43.2 :( However, tested on latest release and is working as per above.  May be I will need to upgrade.

**Comment by colemanw** [comment]
I honestly don't think there's any difference btw those versions as far as this markup is concerned, but ok.

**Comment by kurund** [comment]
hmm, that's strange..

Screenshot from 2022-02-07 18-48-23

**Comment by colemanw** [comment]
Dealing with CSS inheritance can be tricky. There's probably some other style on the page overriding it.

**Comment by kurund** [comment]
Yes, however same stuff works with upgraded CiviCRM :) So will go for upgrade.

**Pull request closed without merging**
