### PR TITLE
CRM-19587, donot delete financial account if its present in civicrm_f…

### PR DESCRIPTION
**Pull request by pradpnayak**
…inancial_item table

----------------------------------------
* CRM-19587: DB Error when trying to delete FInancial Account
  https://issues.civicrm.org/jira/browse/CRM-19587

### CODE REVIEW

**Comment by yashodha** [comment]
@pradpnayak Can you provide test coverage for the same?

**Comment by monishdeb** [comment]
@pradpnayak can we add unit test for this ?

**Comment by pradpnayak** [comment]
Added CRM test

**Review by JoeMurray — CHANGES_REQUESTED** [review]
Could we separate the PR for the functional change from the code cleanup changes. BTW, lots very useful code cleanup - thanks.

**Comment by pradpnayak** [comment]
Separated PR at https://github.com/civicrm/civicrm-core/pull/9346

**Pull request merged**
