### PR TITLE
CRM-21526: CRM_Utils_System_Drupal8::authenticate() should change the Drupal user

### PR DESCRIPTION
**Pull request by dsnopek**
See https://issues.civicrm.org/jira/browse/CRM-21526

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@jackrabbithanna if you think this looks right I'm good to merge it (or for you to)

**Comment by jackrabbithanna** [comment]
Code looks right, and think lets merge this so we can continue to flesh out the rest of the issue.
merging #11381

**Comment by dsnopek** [comment]
Thanks!!

**Comment by jackrabbithanna** [comment]
This month is the month to bring in all the updates you have into the Drupal module and CiviCRM Core....I have some company authorized time to do reviews, testing, and help with issues, and some personal time too....If you want to make a big push this month, lets do it!

**Comment by dsnopek** [comment]
We can for sure try! It's kind of a short month, given that the 2nd half is eaten up by holidays, but we can try and make the most of next week :-)

**Comment by jackrabbithanna** [comment]
Great, make what PRs you can next week, and I'll be reviewing them over the next weekend and over the holidays

**Comment by colemanw** [comment]
@jackrabbithanna @dsnopek I'd like to schedule a call for anyone interested in D8 packaging to discuss the way forward with composer. @totten & I briefly discussed it last week and we think creating a new repo for the D8-civicrm code is the best solution for the version number problem that's currently blocking us (composer doesn't recognize the format 8.x-4.x). So let's hash that out and any other issues wrt composer and carve a path forward.

**Comment by jackrabbithanna** [comment]
@colemanw sounds good to me, available most days from 10-2:45 central time, and then in the evenings

**Comment by dsnopek** [comment]
@colemanw Sure! Just let me know :-)

**Pull request merged**
