### PR TITLE
Remove issets from Options.tpl

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
This is accessible from civicrm/admin/options/email_greeting?reset=1

I could not figure out where showVisibility comes from (if anywhere) but I removed the rest...

### CODE REVIEW

**Comment by yashodha** [comment]
@eileenmcnaughton test failures look related.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @colemanw @demeritcowboy @yashodha  this one is passing now if anyone can look (finally)

**Comment by demeritcowboy** [comment]
This doesn't seem to be working. I can't see where offhand but it causes the Label column to change to Title, and then it gives errors about missing `title`. And the page at Administer - System Settings - Option groups is completely off.

But FYI showVisibility used to be at https://github.com/civicrm/civicrm-core/commit/38f6870aee45a150c9e18c6fdeee665fb17ac89d#diff-f0929799b6517b03abe7ac776a2aeb3d8e86b9df21415332690bd988f636d2e6

**Comment by eileenmcnaughton** [comment]
@demeritcowboy I will look again but I put up a separate PR for showVisibility

**Comment by eileenmcnaughton** [comment]
I think I fixed it - this includes the spin off in 1 commit cos I thinki it's mergeable as is

**Comment by eileenmcnaughton** [comment]
@demeritcowboy I think this bit is OK now

**Comment by eileenmcnaughton** [comment]
thanks @demeritcowboy - I also just found a test you wrote that is going to be very useful for this work! `testOpeningForms`

**Pull request merged**
