### PR TITLE
CRM-20747: {contribution.campaign} token not working on Contribution ThankYou letter

### PR DESCRIPTION
**Pull request by monishdeb**
* [CRM-20747: {contribution.campaign} token not working on Contribution ThankYou letter](https://issues.civicrm.org/jira/browse/CRM-20747)

### CODE REVIEW

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by colemanw** [comment]
@monishdeb test failure looks to be related.

**Review by jitendrapurohit — APPROVED** [review]
Tested and confirmed that campaign token populates correctly in the pdf generated.

**Comment by monishdeb** [comment]
Merging as per Jitendra's review

**Pull request merged**
