### PR TITLE
CRM-19322 - Fix unitialized table name var

### PR DESCRIPTION
**Pull request by niels-heinemann**
Just saw an unkown variable.

---
- [CRM-19322: Use of unitialized var in Mailing.php](https://issues.civicrm.org/jira/browse/CRM-19322)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by nielosz** [comment]
Can't see any tab?! Used github to edit and indendet w/ spaces...

**Comment by seamuslee001** [comment]
@nielosz there are its in the part before the $

**Comment by yashodha** [comment]
@nielosz : Can you please file an issue in JIRA for the same?

**Comment by nielosz** [comment]
CRM-19322

**Pull request merged**
