### PR TITLE
(dev/core#696) Changes to copied event phone and email reflects in or…

### PR DESCRIPTION
**Pull request by yashodha**
…iginal event phone and email

Overview
----------------------------------------
Steps to replicate:

1. Create an event X with location A, including email A and phone A
2. Create copy of event X say Y and go to location tab for event Y (which will now show location A).
3. Click Create new location radio and then click new location B, including email B and phone B.
4. Check event X - email B and phone B will be listed

Before
----------------------------------------
Event X has phone and email updated to B

After
----------------------------------------
Event Y has phone and email updated to B which is the desired behavior.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Just a quick comment per my note on the gitlab - my vague recollection is the 'eroneous' behaviour was something that DGG did by design - as I recall the idea was that if a location changed it was good to be able to edit all at once. However, if others weigh in that would override my recollection :-)

**Comment by yashodha** [comment]
@eileenmcnaughton 
I don't recollect this being a feature, though it certainly stuck out like a bug to me :). We had a similar bug with address (reported by a few users) which was fixed for 
https://lab.civicrm.org/dev/core/issues/108
https://lab.civicrm.org/dev/core/issues/255

**Comment by lcdservices** [comment]
@yashodha I've tested and confirmed this works as expected.
@eileenmcnaughton I agree with the change. If a person is intentionally choosing to create a new location, that should affect the email and phone as well -- they should not remain tied to the original location. Otherwise there is no way to disconnect the email/phone from the initial event when creating a copy.

**Comment by eileenmcnaughton** [comment]
@lcdservices OK - thanks - added merge-ready then - I'll leave a few days more & if no comments we can merge

**Comment by yashodha** [comment]
@lcdservices @eileenmcnaughton thanks!

**Comment by eileenmcnaughton** [comment]
@yashodha I think anyone else who wanted to weigh in on this had a chance since I emailed the dev list so @lcdservices's input carries the day!

**Comment by jitendrapurohit** [comment]
Seems this change affects the storage of email and phone fields? Related gitlab - https://lab.civicrm.org/dev/core/-/issues/1973 @yashodha @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
ug - @yashodha will you have a chance to look?

**Comment by eileenmcnaughton** [comment]
I think this addresses the regression without breaking your fix @yashodha

**Pull request merged**
