### PR TITLE
AdminUI - Add Financial Types and Assigned Financial Accounts screens

### PR DESCRIPTION
**Pull request by NicolasdRa**
Overview
----------------------------------------
Financial Types Screen with Search Kit added, plus the drilldown search to Assigned Financial Accounts

Before
----------------------------------------
VirtualBox_vm_11_10_2022_16_33_10

After
----------------------------------------
VirtualBox_vm_11_10_2022_16_34_05

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
woohoo - are you in contributors.yml yet?

**Comment by colemanw** [comment]
@civicrm-builder add to whitelist

**Comment by seamuslee001** [comment]
Hi @NicolasdRa can you please fix the code style issues with this PR please https://test.civicrm.org/job/CiviCRM-Core-PR/51755/checkstyle/

**Comment by NicolasdRa** [comment]
Will certainly do tomorrow morning in the sprint. Thanks.

**Comment by seamuslee001** [comment]
@colemanw @NicolasdRa I'm not sure how this can be fixed but in the Help Text section the ts isn't working

financial_type_help

**Comment by colemanw** [comment]
I've updated this PR. Ready for review.

**Comment by larssandergreen** [comment]
Just noticed that the Edit and Delete buttons for this don't work on dmaster. Added an [issue](3951).

**Comment by colemanw** [comment]
@larssandergreen thanks for reporting. Can you check #24837

**Pull request merged**
