### PR TITLE
Fix pricefield pseudoconstant.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fixes PriceField entity to build options for the price_set_id pseudoconstant field

Before
----------------------------------------
```
$result = civicrm_api3('PriceField', 'getoptions', [
  'field' => "price_set_id",
]);
```
Returns nothing

After
----------------------------------------
Above returns
```
{

    "is_error": 0,
    "version": 3,
    "count": 8,
    "values": {
        "1": "Contribution Amount",
        "7": "Fall Fundraiser Dinner",
        "3": "Help Support CiviCRM!",
        "4": "Member Signup and Renewal",
        "2": "Membership Amount",
        "5": "Pledge for CiviCRM!",
        "6": "Rain-forest Cup Youth Soccer Tournament",
        "8": "Summer Solstice Festival Day Concert"
    }
}
```

Technical Details
----------------------------------------
The price field turns out not to be returning pseudoconstant fields for 2 reasons
1) the label field is defined but the name field is not
2) any price fields with no domain are filtered out. In my single domain db this is
all of them.

I think we can safely understand NULL domain_id as 'not restricted by domain'. For some tables
(membershipType) it is a required field but for PriceField it is not.

I would be inclined to say it should be required less often. However, where it is required thenn
the OR IS NULL should never be true

Comments
----------------------------------------

@seamuslee001 @colemanw

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Also note that for memberships the domain id filtering is not actually seen as a good thing by AUG - https://github.com/eileenmcnaughton/org.civicrm.multisite/issues/26

**Comment by eileenmcnaughton** [comment]
@yashodha maybe of interest to you

**Comment by pradpnayak** [comment]
Test failure looks related, but change make sense. Good to merge once test passes

**Comment by seamuslee001** [comment]
Merging as per @pradpnayak 's review

**Pull request merged**
