### PR TITLE
CRM-20458: Added civi.dao.preDelete event and event class.

### PR DESCRIPTION
**Pull request by universalhandle**
* [CRM-20458: Add civi.dao.preDelete event](https://issues.civicrm.org/jira/browse/CRM-20458)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@totten looks OK to me - can you check & merge?

**Comment by eileenmcnaughton** [comment]
@GinkgoFJG this looks OK to me, I'd like to get @totten's blessing but have not seen a sign of life from his as yet. But, I suspect you probably already discussed this approach with @totten ?

**Comment by eileenmcnaughton** [comment]
as an aside - we did discuss a slight change to the pre hooks so they would look like

try {
  // pre delete hook
}
catch (dontYouDareDeleteThisException $e ) {
  return;
}

// delete away

**Comment by GinkgoFJG** [comment]
We discussed the use of events vs. hooks some. There was no pre or post hook for the entity I wished to act on, but I noticed a post event was raised and figured it made as much sense to raise a pre event too. I can't remember if I explicitly proposed adding the event, though.

**Comment by totten** [comment]
This patch is stylistically consistent some other events (`civi.dao.postUpdate`, etal), and it passes the test suite.

**Pull request merged**
