### PR TITLE
Eileenmcnaughton my reports

### PR DESCRIPTION
**Pull request by samuelsov**
What's in this PR:
- ability to create a report that nobody except people with 'administer private reports' can edit (option in the Access tab)
- have a My personal reports section in the all reports page.

I have removed the permission 'access own private reports' which was not very useful.
What's missing but might be more work to implement:
- there is no 'my reports' menu for now so we might want to improve that.
- there is no UI for admin to see all private reports

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Hi @samuelsov I checked this & I'm happy with it - ie. the changes you made I'm happy with & it seems to work.

I added a couple more commits such that the my reports navigation script is in the initial install script & can be optionally re-instated / added when you go to the navigation menu page & click 'reset reports'.

One thought I have is that saving to 'my reports' does allow people to 'steal' reports from the main 'my reports' - perhaps it makes sense to add an additional confirm saying 'this is the only report from this template - do you want to put a copy in my reports' - or perhaps block more aggressively?

I would be ok merging as is & adding what we agree on that front as a follow up

**Comment by eileenmcnaughton** [comment]
Or we could just assume 'save a copy' if it is the only report off the template & people choose save to my reports. It might not fit every edge case but a more sophisticated patch would be .... welcome

**Comment by eileenmcnaughton** [comment]
OR we could put the domain contact id as the owner for the pre-created reports - that's sounding easy....

**Comment by samuelsov** [comment]
I'm ok with the way it is right now but as we talk about it, i'd rather have a "Add to my report" action button instead of a checkbox. It would be visible for global reports only and could open a popup for letting the user choose if he want it to be a copy or not. Then for personal report, we could have a button "Make this report public" to revert it.

**Comment by eileenmcnaughton** [comment]
what say I fix the issue in the script & merge this & push up the actions pr & maybe we can tweak more on top of that

**Comment by samuelsov** [comment]
yes, sure, let's do that

**Pull request merged**
