### PR TITLE
Fix fatal error on logging tab when hook alters logging tables.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
The logging tag of a contact fails to load if logging is enabled and a custom table has been excluded by hook. This is especially appropriate for custom tables with only calculated values (ping @jmcclelland )

Before
----------------------------------------
Logging report fails if a hook like this is in play

```
/**
 * Implements hook_alterLogTables().
 *
 * @param array $logTableSpec
 */
function mymodule_civicrm_alterLogTables(&$logTableSpec) {
  unset($logTableSpec['civicrm_value_calculated_custom_table']
}
```

After
----------------------------------------
Report loads

Technical Details
----------------------------------------
When a custom table is removed from logged tables by hook (e.g a calculated table like a summary table) the logging report
still tries to include it but fails with a fatal error.

This patch excludes it from the list of customDataEnabled logging tables

Comments
----------------------------------------
Adding a unit test for this relies on the report being testable - will rebase one #12065 is merged

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@monishdeb got it -  - the buildTemporaryTables was being called from beingPostProcessCommon AND postProcess. Once I took it out of postProcess we kinda didn't need postProcess any more...

**Comment by eileenmcnaughton** [comment]
@monishdeb try again

**Comment by monishdeb** [comment]
@lcdservices this fix is about doing cleanup in the logging report and disabling FGB before queries are executed. As per my test, it does work on FGB enabled setup. But still, I will keep my PR open https://github.com/civicrm/civicrm-core/pull/11464 until we got a test environment to ensure FGB fix and afterward I can test my fix on that env.

**Comment by eileenmcnaughton** [comment]
Well of course I approve :-)

**Comment by jmcclelland** [comment]
Thanks for the work on this @eileenmcnaughton . Summary Fields doesn't use the alterLogTables hook, but perhaps it should (pending this fix).

**Comment by eileenmcnaughton** [comment]
@jmcclelland yeah - it is helpful on large databases not to log calculated data. Although, it would also be helpful if updating calculated data didn't update contact modified_date - there is an internal ticket on that with WMF but not yet prioritised to a sprint

**Comment by eileenmcnaughton** [comment]
@monishdeb is this waiting @lcdservices approval?

**Comment by monishdeb** [comment]
@eileenmcnaughton yes because this will discard most of the FGB fixes made in  https://github.com/civicrm/civicrm-core/pull/11464 (which was billable work) OR I can still keep my fixes but that won't matter if I merge this PR because FGB will be disabled for logging summary report.

**Comment by lcdservices** [comment]
(I know I'm behind on reviewing stuff -- plan to catch up this afternoon...)

**Comment by eileenmcnaughton** [comment]
@monishdeb I think we should start to work on getting proposals approved in gitlab per https://lab.civicrm.org/dev/core/issues/97#note_4422 -

**Comment by seamuslee001** [comment]
I believe that this is ok to merge

**Pull request merged**
