### PR TITLE
Fix a regression whereby payment details are not saved from the AdditionalPayment form

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Port https://github.com/civicrm/civicrm-core/pull/15537/commits
- also includes preliminary renaming param commit

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton test fails look related at least the syntax ones

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton test failures look related

**Comment by seamuslee001** [comment]
style issues @eileenmcnaughton https://test.civicrm.org/job/CiviCRM-Core-PR/29765/checkstyleResult/new/

**Comment by eileenmcnaughton** [comment]
@seamuslee001 yeah the battle with syntax conformance on the 5.19 one is more the issue

**Comment by eileenmcnaughton** [comment]
unrelated fail

**Pull request merged**
