### PR TITLE
CRM-19415, CRM-16514 - Add tests for limit_to use-cases

### PR DESCRIPTION
**Pull request by totten**
- [CRM-16514: Scheduled reminder for event sends email repeatedly](https://issues.civicrm.org/jira/browse/CRM-16514)

---
- [CRM-19415: Scheduled reminders: Add Receipient and Limit To Tests don't pass](https://issues.civicrm.org/jira/browse/CRM-19415)

### CODE REVIEW

**Comment by totten** [comment]
jenkins, test this please

**Comment by totten** [comment]
Changes:
 * Rebased to latest master
 * Commented out the tests which are failing
 * Filed JIRA issue for someone to examine why the tests are failing - and fix them. https://issues.civicrm.org/jira/browse/CRM-19415

**Comment by totten** [comment]
IMHO, this should be merged (if Jenkins does not report any regressions). Considerations:
 * It adds some new tests which will help protect us going forward.
 * There are some disabled tests which need attention (CRM-19415), but that attention should be driven by JIRA.

**Comment by litespeedmarc** [comment]
@totten , can you document in CRM-19415, the name of the disabled tests, so that someone picking that JIRA can know where to focus.

Based on @totten's comment, and knowing that these only cover unit tests.  Can an admin please go ahead and merge this?

Thank you.

**Comment by totten** [comment]
Thanks, @litespeedmarc -- a good point. I've updated the description of CRM-19415 to note the disabled tests.

For the record, Jenkins failed on this PR due to two unrelated, preexisting issues (
CRM_Dedupe_MergerTest.testGetOrganizationMatches and CRM_Contribute_Form_ContributionTest.testSubmitCreditCardPayPal).

**Pull request merged**
