### PR TITLE
Add unit tests to cover date field imports

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This is the test cover for this extraction - https://github.com/civicrm/civicrm-core/pull/23498 - in the process I found that importing address custom fields with dates are currently broken - this has a fix for that. Note it also contains https://github.com/civicrm/civicrm-core/pull/23491 as the test utils in that were needed

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
@eileenmcnaughton can you rebase this one?

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
@eileenmcnaughton php syntax error in `tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php`

**Pull request merged**
