### PR TITLE
Redirect to Profile "create" screen when there is no Contact ID

### PR DESCRIPTION
**Pull request by christianwach**
Overview
----------------------------------------
Implements [this improvement proposal on Lab](https://lab.civicrm.org/dev/core/-/issues/3138).

Before
----------------------------------------
On Profile "edit" screens when there is no Contact ID, `statusBounce` redirects to the homepage of the site.

After
----------------------------------------
On Profile "edit" screens when there is no Contact ID, `statusBounce` redirects to the Profile "create" screen.

### CODE REVIEW

**Comment by kcristiano** [comment]
* ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) PASS
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) PASS
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) PASS
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) PASS
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) PASS
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) PASS: Applied to WP 5.9.2, CV Master, wothout patch any edit profile redirects user to home page with no message.  With it they get statusBounced to the create page with a notice
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) PASS: This is more expected behavior from a user perspective.

**Comment by kcristiano** [comment]
Update `r-run` with D7 also passes.

**Comment by eileenmcnaughton** [comment]
@agh1 @Stoob any opinion on this one

The only thing that crosses my mind is that I'm not 100% clear if it is possible to have a form that works in edit mode but not add mode - in which case redirecting to add mode would be weird

**Comment by jaapjansma** [comment]
@christianwach could you give your opinion on @eileenmcnaughton comment? 
As it looks like @eileenmcnaughton has some hesitation on merging this PR and we are doing PR reviews and we are wondering on a way forward with this PR. So that why we are curious about your opinion.

**Comment by Stoob** [comment]
I'm not so sure about this.  The intent of the edit profile is to edit a contact which cannot be done without an id.  If there is no id, why it is a improved behavior to allow someone to create contact?  Maybe the intent is that they edit and do not create a contact.

**Comment by kcristiano** [comment]
@Stoob currently StatusBounce will redirect them to the home page with no error at all if a contact ID is not fund (token or logged in contact).  That is causing massive confusion.

I think we must do something.   Falling back to create seemed a good idea to me, but I am open to other ideas.

**Comment by Stoob** [comment]
That is not ideal behavior. But what about providing an error message "No contact ID found, cannot edit without contact ID"

**Comment by christianwach** [comment]
> But what about providing an error message "No contact ID found, cannot edit without contact ID"

@Stoob Because that error is only displayed on another page rendered by CiviCRM - and is therefore never shown on the home page after redirection because that page isn't rendered by CiviCRM. The "Profile Create" page *is* a CiviCRM page, so a message of that nature is indeed shown there.

**Comment by christianwach** [comment]
> could you give your opinion on @eileenmcnaughton comment?

My tuppence-worth is that the redirect should be to a page that is rendered by CiviCRM. That would, at minimum, display the Status Bounce message. I'm not particular about the exact page but agreed with @kcristiano that "Profile Create" seemed like the most logical choice given that there isn't a CiviCRM "Do Nothing Except Give Feedback" page.

**Comment by Stoob** [comment]
A profile form can work in add mode and edit mode but only if _permissions_ are **on** for both operations. Attached illustration. I lack the context to know why contact ID is missing from the edit mode in the first place.  But switching to create mode seems like a risky assumption to me.  A Civi-native error message seems most conservative solution IMHO
perms

**Comment by jaapjansma** [comment]
test this please

**Comment by christianwach** [comment]
> A Civi-native error message seems most conservative solution IMHO

@Stoob Having read your comments again, I tend to agree with this conclusion. Would there be a case for a special CiviCRM path (e.g. `civicrm/error` or something like that) which is reserved for displaying feedback messages and that could be redirected to in cases such as this?

**Comment by eileenmcnaughton** [comment]
I'm going to close this one & we can track in gitlab since it seems there is no consensus to make this change

**Pull request closed without merging**
