### PR TITLE
dev/core#561 Replace jcalendar with datepicker in Price Field Form

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This changes the active on and expire on fields from jcalendar to be datepicker fields on the Price Field.

Before
----------------------------------------
Used Deprecated jcalendar

After
----------------------------------------
Uses better datepicker

ping @eileenmcnaughton @mattwire @monishdeb

### CODE REVIEW

**Comment by monishdeb** [comment]
@seamuslee001 can you please rebase your PR

**Comment by monishdeb** [comment]
Tested the PR worked fine. Here's the screencast where I found the two daetpicker date fields are working well:
after


However, on Price Field view I am not happy how the date values are shown. Though not related to the current topic, but was thinking if you can include this patch in the PR too, or do you want to me to send a separate PR for this patch:
```patch
diff --git a/templates/CRM/Price/Page/Field.tpl b/templates/CRM/Price/Page/Field.tpl
index fdbfddf01a..0a02c7ee77 100644
--- a/templates/CRM/Price/Page/Field.tpl
+++ b/templates/CRM/Price/Page/Field.tpl
@@ -79,8 +79,8 @@
         <td class="nowrap">{$row.weight}</td>
         <td class="crm-editable" data-field="is_required" data-type="boolean">{if $row.is_required eq 1} {ts}Yes{/ts} {else} {ts}No{/ts} {/if}</td>
         <td id="row_{$row.id}_status">{if $row.is_active eq 1} {ts}Yes{/ts} {else} {ts}No{/ts} {/if}</td>
-        <td>{if $row.active_on}{$row.active_on|date_format:"%Y-%m-%d %T"}{/if}</td>
-        <td>{if $row.expire_on}{$row.expire_on|date_format:"%Y-%m-%d %T"}{/if}</td>
+        <td>{if $row.active_on}{$row.active_on|crmDate}{/if}</td>
+        <td>{if $row.expire_on}{$row.expire_on|crmDate}{/if}</td>
         <td>{if $row.html_type eq "Text"}{$row.price|crmMoney}{else}<a class="action-item" href="{crmURL p="civicrm/admin/price/field/option" q="action=browse&reset=1&sid=$sid&fid=$fid"}">{if $isReserved}{ts}View Price Options{/ts}{else}{ts}Edit Price Options{/ts}{/if}</a>{/if}</td>
         {if $getTaxDetails}
             <td>{if $row.tax_rate != '' && $row.html_type eq "Text / Numeric Quantity"}
```
Which does this:
after

**Comment by seamuslee001** [comment]
Yeh agreed done @monishdeb

**Comment by monishdeb** [comment]
Thanks. Since the changes are meant for the UI end and don't need UT to capture the behavior, also checked the form submission. I am happy with this patch. Marking merge-on-pass

**Comment by seamuslee001** [comment]
Merging as per the tag

**Pull request merged**
