### PR TITLE
CRM-19641 Further Fix

### PR DESCRIPTION
**Pull request by seamuslee001**
* [CRM-19641](https://issues.civicrm.org/jira/browse/CRM-19641)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 tell me what you have tested here - this is a tricky thing to test - but also pretty fringe so tell me about this....

**Comment by seamuslee001** [comment]
@eileenmcnaughton I haven't tested it but @xurizaemon pointed out that when we were doing the escaping for the title we needed $tableName in a not escaped format.

**Comment by eileenmcnaughton** [comment]
@xurizaemon can you confirm we should merge this. How on earth do we test this file? @colemanw @yashodha do you guys know?

**Review by xurizaemon — APPROVED** [review]
* This feels like an improvement.
* The array key should not be escaped for SQL, or we may grab an incorrect (prob missing) entry from the array. This is likely to lead to invalid SQL (`SELECT foo AS , bar AS b2`)
* Escape on output would be an improvement here, since an SQL escaped column title may not be XML safe, and it feels like that may be what happens. Assuming this is going to output to XML, who knows.
* To make this testable, it probably needs a lot of refactoring. Testing this as is looks like it will result in code *and* tests that would be hard to comprehend 👎  - Eileen linked to [an article on why peer review doesn't happen when it's too hard](http://www.vox.com/science-and-health/2016/11/23/13713324/why-peer-review-in-science-often-fails) today, my takeaway from this is that I took a look at [`Report.php`](https://github.com/civicrm/civicrm-core/blob/78c187fb99b27616e605adf5bf3c0495266d07b1/CRM/Case/XMLProcessor/Report.php) file and said "yep, I don't have time to comprehend what is supposed to be going on here". Which packs down to "too hard".
* Please take the time to write meaningful commit messages 👍 , that will help future contributors (incl us two weeks from now).

**Pull request merged**
