### PR TITLE
CRM-21808 Install custom group for Contribution or ContributioRecur s…

### PR DESCRIPTION
**Pull request by scardinius**
…ubtypes based on XML file
https://issues.civicrm.org/jira/browse/CRM-21808

Overview
----------------------------------------
It will be useful to create custom group by XML file also for subtypes of Contribution or ContributionRecur entities.

Before
----------------------------------------
It's not possible to properly install custom group for Contribution or ContributionRecur entity with particular subtype (financial type)

After
----------------------------------------
There is a possibility to create custom group for Contribution or ContributionRecur by *install.xml file or during upgrade step of extension by executeCustomDataFileByAbsPath(./my_contrib_custom.xml).

Technical Details
----------------------------------------
Add to CustomGroup XML element those options:

    <extends_entity_column_value_option_group >FinancialType</extends_entity_column_value_option_group>
    <extends_entity_column_value>Donation</extends_entity_column_value>

### CODE REVIEW

**Comment by seamuslee001** [comment]
pinging @eileenmcnaughton i think you have been doing some custom stuff lately

**Comment by eileenmcnaughton** [comment]
Hmm this is different to what I was working on - I don't know this code & in particular whether it is a way we are currently encouraging people to set up custom groups - @totten might know!

**Comment by eileenmcnaughton** [comment]
If we ARE still developing this code then the way to get a list of supported entities rather than to hard-code is

```
  $nonGenericEntities = array('Contact', 'Individual', 'Household', 'Organization');

  $customFieldEntities = array_diff_key(CRM_Core_SelectValues::customGroupExtends(), array_fill_keys($nonGenericEntities, 1));
```

**Comment by eileenmcnaughton** [comment]
I think this code is so marginally supported /used that I either need to say

a) no, we are not accepting changes to it or
b) erm Ok- if you say this helps I'll merge it, taking your word for it.

I'll go with b

**Comment by JoeMurray** [comment]
@monish could you review briefly for any expected impact problems, given @eileen's reason for merging and lack of substantive review endorsements from others.

**Pull request merged**
