### PR TITLE
[REF] Afform - Code cleanup in LoadAdminData API action

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Minor code simplification and added docblocks in the `loadAdminData` Afform API.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw looks simple - I can r-run if you confirm where I would see it

**Comment by eileenmcnaughton** [comment]
My transform isn't working - but it's pre-existing - ie 'amount' is not getting MATH options - trying another field

**Comment by eileenmcnaughton** [comment]
Possibly this is also pre-existing

image


image

**Comment by eileenmcnaughton** [comment]
@colemanw I was able to add & select a date field & transform to YEAR - the transform options for date field also seemed a bit confusing - ie

image


but 'LOWER CASE still leaves the only cased thing in the date in upper case & I'm not sure what the MATH ones would mean in this context

image

**Comment by eileenmcnaughton** [comment]
@colemanw so the summary is - I think that all the things I spotted testing this are unchanged by this & if you are happy that is the case then go ahead & merge

**Comment by colemanw** [comment]
Hoo boy, those are a lot of issues with the transforms. I think a lot of the issue is that not all sql functions are appropriate for every field and the UI needs to do a better job of making that clear.
Another part is that pseudoconsant matching happens in the post-processing not the sql query so `UPPERCASE(financial_type_id:label)` isn't going to work as expected. If we worked at it a bit I think it could be fixed but yea that's currently broken.

**Comment by eileenmcnaughton** [comment]
@colemanw I suspect once we can do them on combined fields the issues will change again so maybe it's worth figuring out that first

**Comment by colemanw** [comment]
Well there is a way to do pseudoconstants in SQL, by rewriting the query to use `FIELD()` like this: https://github.com/civicrm/civicrm-core/blob/1930b3e80feeaf4d8df1d1d81a19e3071b760402/Civi/Api4/Query/Api4SelectQuery.php#L318-L327
I don't know how it would impact performance if we switched them ALL to work that way. We could switch the ones inside functions to do so though, and that would get things like UPPERCASE working.

**Comment by eileenmcnaughton** [comment]
@colemanw I guess that's the question isn't it - should they all work in sql or should we do some parts in php. I guess that's why I think working on combining the fields makes sense - because whether you hit the limits of mysql in there might drive that answer

**Pull request merged**
