### PR TITLE
Avoid permission checking on getOrganizationNames

### PR DESCRIPTION
**Pull request by francescbassas**
Overview
----------------------------------------
see related issue Bookkeeping Transactions Report insufficient permissions

Before
----------------------------------------
Users with contribution permissions can't visualize the Bookeeping Transactions Report

After
----------------------------------------
Users with contribution permissions can visualize the Bookeeping Transactions Report

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Yep - per previous discussion I agree this is the right fix

**Comment by JoeMurray** [comment]
I think this change breaks the usability for organizations that have multiple sets of books for which different staff are permissioned to view data.

**Comment by eileenmcnaughton** [comment]
@JoeMurray I can't see any evidence that any nuance of organisations in the changed call...

**Comment by JoeMurray** [comment]
Perhaps I'm wrong. 

I haven't traced through the permissions involved in https://github.com/civicrm/civicrm-core/blob/master/CRM/Financial/BAO/FinancialAccount.php#L468. My guess was that people could have made a contact in org1 not able to view org2 record, and then they wouldn't be able to see the accounts for org2. I guess alternatively they could use ACLs on the financial accounts directly. But even in that case I wouldn't want to override the permissions and let people see the accounts for other orgs, and doing it in this report would let them see all of the related bookkeeping entries which is really what should be hidden between the orgs. The main points of associating financial accounts with organizations is to allow multiple organizations to have separate books in civi, and that often involves a desire to keep things from being viewable by all the other orgs.

**Comment by francescbassas** [comment]
Thanks for reviewing this. For your comments I undersand that if there is no affectation for this PR the solutions is enough. Otherwise we need to return to the first PR https://github.com/civicrm/civicrm-core/pull/13159 to define FinancialAccount permissions.

**Comment by eileenmcnaughton** [comment]
Yeah - let's see if @JoeMurray is able to get @monishdeb to dig into it to check

**Comment by monishdeb** [comment]
I did some investigation and found that getOrganizationNames() was introduced in this PR https://github.com/civicrm/civicrm-core/pull/10112. Back then, this was implemented in core to limit FA owners in BK (Bookeeping report) filter, based on ACL permission. In core, this function is only used for BK. Other then that, it is used in easybatch extension [here](https://github.com/JMAConsulting/biz.jmaconsulting.easybatch/blob/master/easybatch.php#L251) 

         I have confirmed that ACL permissions are the only ones which have an effect on filtering FA organizations in that option list, as I went deep into the code where the permission clause is built https://github.com/civicrm/civicrm-core/blob/master/CRM/ACL/BAO/ACL.php#L732 So without ACL, the rest of the user who has to administer/view contribution permission can see the all the FA orgs w/o this patch.

_Overall in my opinion, BK report query won't get affected if we merge this PR in terms of ACL permissioning, as it is only about showing all the FA orgs in the 'Debit/Credit - FA Owner' select field._ 

(After merge I will retain the original behaivour in BK report via [Financial ACL Report Extension](https://github.com/JMAConsulting/biz.jmaconsulting.financialaclreport))

**Comment by JoeMurray** [comment]
Reviewing the Financial ACL Report extension, it will properly filter ACLs for financial accounts for the bookkeeping report if it is installed. No change is required.

Although I had a concern that the PR will cause sites with ACLs to show unpermissioned objects, I've since realized that if they don't have the Financial ACL Report extension installed and they leave the affected filters blank they would get unpermissioned content, eg staff of one org would be able to see sensitive financial information about another that the ACLs had been setup to prevent. Allowing them to filter on content just for the unpermissioned org won't change that. So I'm no longer opposed to the PR. Let's merge.

**Comment by JoeMurray** [comment]
@monishdeb can you make any needed updates to Easy Batch extension and make a new release before next Wednesday when this change will come out in the RC? Thanks.

**Comment by JoeMurray** [comment]
:)

**Comment by francescbassas** [comment]
Thanks all!

**Pull request merged**
