### PR TITLE
CRM-18212 allow triggers to be managed offline.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
- [CRM-18212: Allow for triggers to be managed offline](https://issues.civicrm.org/jira/browse/CRM-18212)

### CODE REVIEW

**Comment by monishdeb** [comment]
Two style warnings :/

**Comment by eileenmcnaughton** [comment]
sorted - actually one space failed 2 tests :-)

**Comment by totten** [comment]
jenkins, test this please

**Comment by totten** [comment]
Close in favor #8171.

**Pull request closed without merging**
