### PR TITLE
dev/core#752 Add cid parameter when loading custom data via backend f…

### PR DESCRIPTION
**Pull request by seamuslee001**
…orms so that hooks can modifiy based on contact_id being viewed

Overview
----------------------------------------
This picks up work by @sluc23 from #13191, this adds the cid parameter into customdata urls as per discussion in lab

Before
----------------------------------------
no cid parameter

After
----------------------------------------
cid parameter

Technical Details
----------------------------------------
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

Comments
----------------------------------------
ping @mattwire @eileenmcnaughton @sluc23

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I feel like $contactID is a more common smarty variable

**Comment by seamuslee001** [comment]
Probably i guess i was just riffing based on the lab ticket

**Comment by sluc23** [comment]
looking forwards to have this merged, tx @seamuslee001 !
This will make our life easier when coding custom field's related logic

**Comment by eileenmcnaughton** [comment]
Putting aside my preference for meaningful variable / parameter names - I'm OK to merge this  if you review it @sluc23

**Comment by sluc23** [comment]
yes, it works.. this hook will set `contactID` as default value in Activity's custom field  (simplest example, then you can use `contactID` to calculate/search other values) .  
Previously some jQuery / `$_POST` magic was needed..

```php
function testhook_civicrm_buildForm($formName, &$form) {
  if ($formName == 'CRM_Custom_Form_CustomDataByType') {
    if ($form->getAction() == CRM_Core_Action::ADD) {
      foreach ($form->_elements as $index => &$element) {
        if ($element->_attributes['name'] == 'custom_1_-1') {
          // Set Contact ID as default value to a custom field
          $element->_attributes['value'] = $form->getVar('_contactID');
        }
      }
    }
  }
}
```

**Review by sluc23 — APPROVED** [review]
tested!

**Comment by eileenmcnaughton** [comment]
Merging based on @sluc23 review

@sluc, @seamuslee001  -is there something here that could be documented?

**Comment by sluc23** [comment]
@eileenmcnaughton  do you think is a good idea to add the hook sample i've posted in the `hook_civicrm_buildForm` documentation?

**Comment by sluc23** [comment]
only issue, so far, is that only works for Activities, until we spread this for the rest of entities.. I will doing some PRs to extend it for the rest..

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon any opinions about where / how to document?

**Pull request merged**
