### PR TITLE
Add Job Entity to Api4

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Add the Job entity to Api4

Before
----------------------------------------
Not available

After
----------------------------------------
Available.

Technical Details
----------------------------------------

Comments
----------------------------------------
This will allow us to replace the Scheduled jobs with a nice searchable one based on searchkit

### CODE REVIEW

**Comment by colemanw** [comment]
This API will probably need building out to add more job-related actions, but I don't see any reason not to go ahead & merge this bare-bones version.

**Comment by eileenmcnaughton** [comment]
I'm fine with this - but it does rather open the question of whether we should have a bit of a practice for supporting `where` for these new api versions - I'm thinking at the moment of the `processGreeting` job

**Comment by mattwire** [comment]
@eileenmcnaughton Just thinking out loud it might even make more sense to have a different entity for the "adhoc" jobs? Eg. JobAction. The reason for exposing "Job" at this point is that it allows us to implement the admin interface in searchkit.

**Comment by eileenmcnaughton** [comment]
yeah I get your point. It was pretty messy in v3

I think I'd still like to have `where` generally available to that class - @colemanw thoughts?

**Comment by mattwire** [comment]
Ah, you mean `where` to select which jobs to run? Seems like a good idea.

**Comment by eileenmcnaughton** [comment]
yeah - tbh several of the api actually do what an update does - ie api v4 empty contact update will `process_greetings` - but you have to 'trick' it wih a meaningless value update which feels a bit odd

**Pull request merged**
