### PR TITLE
Fix UTC offsets when retrieving timezone string in WordPress

### PR DESCRIPTION
**Pull request by christianwach**
Overview
----------------------------------------
Fixes [this issue on Lab](https://lab.civicrm.org/dev/wordpress/-/issues/121).

Before
----------------------------------------
In WordPress, one can choose e.g. `UTC+4` as the site's timezone. This results in no value being returned by `get_option('timezone_string')` which may lead to unexpected results in CiviCRM.

After
----------------------------------------
When choosing e.g. `UTC+4` in WordPress, a deprecated (but still currently valid) `Etc/UTC-4` timezone string is used.

Comments
----------------------------------------
There is a companion PR in [the CiviCRM-WordPress repo](https://github.com/civicrm/civicrm-wordpress/pull/298).

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@christianwach ping me if you need help getting this merged - I'm kinda assuming @kcristiano will merge it

**Comment by demeritcowboy** [comment]
I also took a quick look just haven't had a chance to run yet but the idea looked good.

**Comment by christianwach** [comment]
@eileenmcnaughton Thanks - @kcristiano wants to err on the side of caution and run it in some [production contexts](https://lab.civicrm.org/dev/wordpress/-/issues/121#note_92039) before merging. Similar code is actually in a number of relatively high profile WordPress plugins, so I'm confident he'll find it works as expected.

**Comment by kcristiano** [comment]
Thanks @eileenmcnaughton I'll add `merge-ready` once I am ready to merge these.

**Comment by demeritcowboy** [comment]
I did a quick little run. For example for this core PR part of it, creating an activity via command line and leaving the date blank sets the activity date to the wrong time currently, and with the PR sets it according to the configured offset.

**Comment by kcristiano** [comment]
Thanks @demeritcowboy I've also done a number of test and `r-run`   I was waiting on one last test on a staging site that has a custom implementation using the API but this looks good to merge.

**Pull request merged**
