### PR TITLE
Fix CRM-15984: "Add campaign field on Email activity form"

### PR DESCRIPTION
**Pull request by twomice**
* [CRM-15984: Add campaign field on Email activity form](https://issues.civicrm.org/jira/browse/CRM-15984)

### CODE REVIEW

**Comment by twomice** [comment]
Jenkins test this please.

**Comment by twomice** [comment]
Some tests that are failing here are also failing for master, e.g., 
`not ok 23 - Error: CRM_Activity_BAO_ActivityTest::testGetActivitiesCountforAdminDashboard`  What can I do here?

**Comment by twomice** [comment]
Jenkins test this please.

**Comment by twomice** [comment]
Jenkins is finding no test failures but several test Errors, all of which are also happening in master.  What's my best course of action here?

**Comment by twomice** [comment]
Jenkins is finding 9 test failures, all of which are also happening on a fresh `civibuild create d47` site. What's my best course of action here?

**Comment by twomice** [comment]
Yay, finally passing tests!

**Review by jitendrapurohit — APPROVED** [review]
QA'd the changes and confirmed that the campaign field is correctly added to Email Activity task.

**Comment by jitendrapurohit** [comment]
@twomice PR has gone stale, would require a rebase + push in order to let someone merge it.

**Comment by jitendrapurohit** [comment]
cherry-picked the changes and created an updated PR at https://github.com/civicrm/civicrm-core/pull/10317.

**Comment by eileenmcnaughton** [comment]
Closing as replaced

**Pull request closed without merging**
