### PR TITLE
CRM-18435 handling for membership type etc fields

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
master version of #8600

---
- [CRM-18435: Membership type smart group (from < 4.6) stops working in 4.6.15](https://issues.civicrm.org/jira/browse/CRM-18435)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton I have tested this on AUG against an old membership smart group and appears to do sensible things

**Comment by eileenmcnaughton** [comment]
@agileware do you think this is OK as a replacement for your PR? The main difference (apart from the test) is it creates a new function for your logic, rather than altering the existing one

**Comment by agileware** [comment]
@eileenmcnaughton Seems fine.

**Comment by eileenmcnaughton** [comment]
OK I'll merge this then - you & @seamuslee001 gave your PR a pretty good review & I don't think this is much different - + I converted your review notes to unit tests which give some confidence.

Merging now will put it in 4.6.10

**Pull request merged**
