### PR TITLE
CRM-16189, added Closing Accounting form

### PR DESCRIPTION
**Pull request by pradpnayak**
---
- CRM-16189: Improve support for Accrual Method bookkeeping
  https://issues.civicrm.org/jira/browse/CRM-16189

### CODE REVIEW

**Comment by Edzelopez** [comment]
Could one of the admins please ask Jenkins to retest this?

**Comment by Edzelopez** [comment]
jenkins, retest this please

**Comment by colemanw** [comment]
The upgrade script in this PR is causing test failures.

**Comment by Edzelopez** [comment]
@colemanw fixed upgrade script. Can this be merged?

**Comment by colemanw** [comment]
Yes looks good.

**Pull request merged**
