### PR TITLE
TokenCompatSubscriber - Consolidate chained regex. Use more singular …

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
…regex.

Chaining a series of independent regex's can make it a bit harder to think about - e.g. you have consider the impact of sequencing.

Calling `preg_replace()` with an array means that the order won't affect the outcome, but it still allows you write each regex as a distinct item.
This is the patch from the second part of this comment

https://github.com/civicrm/civicrm-core/pull/30100#issuecomment-2089428409

### CODE REVIEW

**Comment by totten** [comment]
civibot, test this please

**Comment by totten** [comment]
There was one failure in that run (re: `mixin`). I think it was flaky/unrelated. Re-ran it (https://test.civicrm.org/job/CiviCRM-Manual-Test/142/) and it passed.

**Comment by aydun** [comment]
Interesting - I've not used that version. The regexps were put together with the intention that they were sequential: handle empty brackets before the more general collapsing of adjacent curlies etc. But if the tests pass then this works too.

**Comment by aydun** [comment]
> Chaining a series of independent regex's can make it a bit harder to think about - e.g. you have consider the impact of sequencing.
>
> Calling preg_replace() with an array means that the order won't affect the outcome, but it still allows you write each regex as a distinct item.

@totten @eileenmcnaughton the [PHP manual notes](https://www.php.net/manual/en/function.preg-replace.php#refsect1-function.preg-replace-notes) says "When both pattern and replacement are arrays, matching rules will operate sequentially. That is, the second pattern/replacement pair will operate on the string that results from the first pattern/replacement pair, not the original string" which seems to contradict the quoted comment above.  Sequencing still applies, its just that it is based on the ordering of array elements rather than the ordering of statements.

I think therefore the two versions (with & without this PR) are functionally identical, although arguably more confusing now!

**Comment by eileenmcnaughton** [comment]
interesting

**Pull request merged**
