### PR TITLE
CRM-20600 - Purify Angular HTML

### PR DESCRIPTION
**Pull request by totten**
## Overview

Organic HTML documents have small discrepancies in notation (e.g. `<div/>` vs `<div></div>`; `` vs ``). If you parse one of these documents and then re-encode it, the content may change in several ways. Those trivial differences make it hard to perform sanity checks. 

This PR puts the Angular HTML into a format that will appear consistent across decode/encode cycles.

Note: This PR originated as part of #10085, but it should be safe on its own. This PR is just cleanup on this existing HTML. Breaking it out reduces the mental-load of reviewing #10085. 

## Acceptance Criteria

 * The HTML should pass through PHP `DOMDocument` system (decoding and then re-encoding) with minimal changes.
 * The existing Angular UI's ("New Mailing", "Manage Case Types", "Manage Connections") should still work as before.

---

 * [CRM-20600: Expose AngularJS screens to hooks](https://issues.civicrm.org/jira/browse/CRM-20600)

### CODE REVIEW

**Comment by totten** [comment]
jenkins, test this please

**Comment by totten** [comment]
Aside: the first acceptance criteria is a bit soft, and you know it's being addressed because the unit-test in 10085 passes. That basically means there's only one QA item left: ensuring that the existing screens still open/work.

**Comment by monishdeb** [comment]
@totten I have tested the all screens under crmMailing/* ,  crmCaseType/*  and other changed files via UI, after applying the patch. The PR is good to merge.

**Review by monishdeb — APPROVED** [review]

**Comment by totten** [comment]
Thanks you sir. :)

**Pull request merged**
