### PR TITLE
Fixed Activity Type and status in Search Builder

### PR DESCRIPTION
**Pull request by digitlimit**
A Fix for  incorrect translation of Activity type and Activity Status search using Search Builder
Referenced here : https://issues.civicrm.org/jira/browse/CRM-17571

### CODE REVIEW

**Comment by totten** [comment]
jenkins, ok to test

**Comment by digitlimit** [comment]
@totten Please how to do I fix failed checks for style?

**Comment by totten** [comment]
@digitlimit, check https://wiki.civicrm.org/confluence/display/CRMDOC/Testing ("Code-style tests").

Note that `civilint` and buildkit are mostly used/tested on Unix (Linux+OSX), but if you poke into the other pieces (`PHP_CodeSniffer`, `coder`) you can probably piece together something for other environments. The standards currently being enforced are https://github.com/civicrm/coder/tree/2015-01-19

**Comment by digitlimit** [comment]
@totten I have made some changes which passed `civilint` tests, Please how to I commit these changes to current PR

**Comment by monishdeb** [comment]
Closing in favour of #7913

**Pull request closed without merging**
