### PR TITLE
dev/core#4542 Fix priority handling in ACLs when dealing with objects…

### PR DESCRIPTION
**Pull request by sebalis**
… other than contacts, and remove code duplication

Overview
----------------------------------------
An alternative to PR #27380 – see https://github.com/civicrm/civicrm-core/pull/27380#issuecomment-1712371292 for details.

Comments
----------------------------------------
I do not have the capabilities to test this. Feel free to discard this if it’s inappropriate to suggest untested code.

### CODE REVIEW

**Comment by sebalis** [comment]
The actual problem description is at https://github.com/civicrm/civicrm-core/pull/26592#issuecomment-1711969867

**Comment by sebalis** [comment]
The failed test is [Civi\FlexMailer\ConcurrentDeliveryTest::testConcurrency with data set #5](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/4620/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_FlexMailer_ConcurrentDeliveryTest/testConcurrency_with_data_set__5/) – I wonder if that is caused by my change or a volatile test.

**Comment by colemanw** [comment]
Let's retest this please

**Comment by colemanw** [comment]
@sebalis as a general rule we like refactors and code extractions of this sort. If tests pass then very likely this will be mergeable.

**Comment by sebalis** [comment]
Ah, suddenly the tests are successful without me having to add a dummy commit – phew :-)

**Comment by sebalis** [comment]
I can report that  @TobiasVoigt has successfully used my version of ACL.php on a test instance with CiviCRM 5.65.0. The file has had no other commits since then, so this is a relevant first real-life (if not full) test for this PR.

**Comment by sebalis** [comment]
In other words, his presentation has been rescued. We are very gratul, in particular to @seamuslee001 and we have hope that no in-presentation bug fixing will be required :-)

**Comment by TobiasVoigt** [comment]
Many thanks to everybody involved also from my side! Great example story for how awesome the CiviCRM community is for my upcoming presentation. Great work! :)

**Comment by colemanw** [comment]
Thanks @sebalis, the code looks good, tests are passing and it has been `r-run` by @TobiasVoigt . Merging.

**Comment by sebalis** [comment]
That’s great news, thanks!

**Pull request merged**
