### PR TITLE
CRM-19871 CRM-19898 Fix issue where changing weight of a membership t…

### PR DESCRIPTION
**Pull request by seamuslee001**
…ype changes the default membership type for contribution pages

### CODE REVIEW

**Comment by seamuslee001** [comment]
@konadave @pradpnayak @mathavanveda Can you please test out this fix to see if it will fix the issue around changing membership_type_id weight

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by konadave** [comment]
I can confirm that the default is saved properly to civicrm_price_field_value table. I'll be able to test fully on client system tomorrow.

**Comment by konadave** [comment]
@seamuslee001 Yes this works.

**Review by jitendrapurohit — APPROVED** [review]

**Pull request merged**
