### PR TITLE
Decorative chevrons should be icons not angle quotes

### PR DESCRIPTION
**Pull request by agh1**
Overview
----------------------------------------
There's a bunch of random places where angle quotes `»` are used decoratively to highlight a button or link.  These are more appropriately icons, but they were missed in migration to Font Awesome because they were never the old sprite icons.

There are a few reasons to do this:

1. The icons generally look better and more consistent with other things.
2. The chevrons were being used as a meaningless catch-all for all kinds of links.
3. They don't trick screen readers or translation software into thinking they're something meaningful.
4. They're more easily grepped for replacing at some later point.

Most are `fa-chevron-right` since that's the [standard icon we use](https://docs.civicrm.org/dev/en/latest/framework/ui/#icons) for advancing to the next thing.  However, some were more appropriately other things (including things as varied as `fa-history` to `fa-trash`).

However, I left behind instances where the chevrons were being used in text to delimit menu items (e.g. in text that says to visit "Administer » System Settings").

Before
----------------------------------------
A bunch of links and buttons have angle quotes.
Screenshot_2020-05-06 Import Contacts ‹ reviewbuttons — WordPress

Screenshot_2020-05-06 Name and Address  Copy id 16  - Sherman Barkley reviewbuttons

image

After
----------------------------------------
They're replaced with icons.

Screenshot_2020-05-06 Import Contacts ‹ reviewbuttons — WordPress(1)

Screenshot_2020-05-06 Name and Address  Copy id 16  - Sherman Barkley reviewbuttons(1)

image

Technical Details
----------------------------------------
I'm sure I missed some, but this at least sets the standard.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
So of course on any UI change you're going to get 10 different opinions which are all not wrong (or are all wrong, depending on your opinion). Anyway here's one:

I like that in general the `»` should be actual icons, so +1 overall.

I see a couple of out-of-scope things (like `&nbsp;` and pre-existing spacing issues) but the one thing that stands out to me is the administration console page: If we're making changes there then these seem like they should be bullets or something instead. The icon makes it seem like they're expandable sections, and looks too big and heavy.

**Comment by agh1** [comment]
I completely agree @demeritcowboy.  The chevrons are mean to indicate "do this next", but that's meaningless if everything gets a chevron.  I started thinking about replacing them with bullets or something, but then I went wild.  See #17259 for a resolution of the admin console and too many other things.

**Comment by colemanw** [comment]
Also noteworthy - the double chevron character is actually meaningful in other languages like French, and it doesn't mean what the icons seem to think it means.
Doesn't mean what you think it means

**Comment by mattwire** [comment]
Reviewed as best I can - changes (icons) are low risk.

**Pull request merged**
