### PR TITLE
Why not make the buttons flat?

### PR DESCRIPTION
**Pull request by agh1**
Overview
----------------------------------------
CiviCRM buttons have a gradient image as their background, and this does a lot to make CiviCRM look dated.  I was dealing with buttons for another PR, and I thought to myself, "Why not just make the buttons flat?  Does *anyone* like the gradient?"  So, here we are.

I also removed the CSS that makes cancel buttons imperceptibly dimmer than the others.  I seriously only noticed this by reading the CSS.

Anyway, moving away from an image as the button background opens the door to potentially setting button colors according to their role and importance.  The text color is just too feeble to matter, and I think it would be more disruptive to add contrast than to just get rid of it.

Before
----------------------------------------
image
image

After
----------------------------------------
image
image

Technical Details
----------------------------------------
There are other gradient images all over the place.  It could be a project to remove/replace them.  This isn't so ambitious, and the goal here is to make a very incremental improvement that many might not even notice.

Comments
----------------------------------------
I originally thought of this as a trial balloon, but then I realized the result is much less radical than it seems.  If this is popular, by all means merge it.  If not, maybe it can be the beginning of a conversation on how to make improvements to the core UI that aren't as opinionated as a theme but help make core more attractive and maintainable.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I feel like we need a standard list of people to ping in on things like this. I feel like @vingle @mattwire @christianwach @mlutfy @colemanw maybe have an interest. Possibly @jamienovick too although I doubt this affects shoreditch

**Comment by totten** [comment]
I think I'm +1 on this for maybe a silly reason. I was playing with a Bootstrap3 configurator, trying to see if there was some low-hanging fruit to make it less clashy on Greenwich... and the most annoying bit was reproducing the texturing on buttons. If we made Greenwich a little flatter, it might be easier to match.

**Comment by vingle** [comment]
I'm a +1 on removing image gradients. They remind me of when we had rounded corner images for buttons too!

**Comment by jamienovick** [comment]
No objections from me on a conceptual level, but I'd just mention that we should keep our eyes on the prize - the aim is to get over to bootstrap 3 for markup, so if this time could be best spent doing something that migrates us there then that's where the time should go rather then touching up the old markup (which just creates more work for theme developers, breaks things downstream and creates challenges for us to maintain Shoreditch). But based on Tims comment this appears to be taking us on the right path.

**Comment by eileenmcnaughton** [comment]
I don't know much about theming but my understanding is that removing an !important is always a good thing

**Comment by christianwach** [comment]
No objections from me 👍

**Comment by mattwire** [comment]
All comments positive, merging!

**Pull request merged**
