### PR TITLE
Bump minimum upgradable ver to 4.2.9

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Upgrade code is large and difficult to maintain so should be periodically culled. It's been a year since we last did so.

Before
----------------------------------------
Could theoretically be upgraded from 4.1.3 (although there were no CI tests running to ensure this)

After
----------------------------------------
Requires 4.2.9, which is covered by tests.

Comments
----------------------------------------
Now the actual code matches the documentation, which for the past year has recommended upgrading to 4.2.9 prior to downloading the latest: https://github.com/civicrm/civicrm-sysadmin-guide/pull/78/files

### CODE REVIEW

**Comment by totten** [comment]
Nice citation for the docs update last year. Seems like a very reasonable phase-out.

Also worth noting that the 4.2.x upgrade steps have a particularly large quantity of code, so this culling removes 11 ksloc (or ~20% of all upgrade logic).

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
Looks good to me - merging

**Pull request merged**
