### PR TITLE
CiviEvent - Error registering through advanced search task

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This aims to fix smarty fatal error on using a search-task to register contacts for an event. Steps to reproduce:

* Perform an advanced search
* Select one or more contacts
* Choose the register contacts to an event search task

Before
----------------------------------------
Form does not display. There's a Smarty error.

After
----------------------------------------
Form displays. No error.

ping @eileenmcnaughton @petednz

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Thanks @seamuslee001 - if @petednz tests this then please merge - ohterwise I'll try to test once tests pass

**Comment by totten** [comment]
`r-run`, `r-code` is good.  I may update the description. Merge on pass.

**Comment by totten** [comment]
Update: The original symptom is fixed, but I've hit an issue when trying to use the form...

**Comment by totten** [comment]
Seamus reported reproducing.

Technically, one could still merge as-is (in a "do no harm" sense) - but it's the same functional limit from user POV. I think it's going to be easier to track/backport/etc if we keep updating on this PR.

**Comment by eileenmcnaughton** [comment]
See https://github.com/civicrm/civicrm-core/pull/19125 for what seems to work for this for me locally

**Pull request closed without merging**
