### PR TITLE
CRM-17154 report actions improvement

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Also add delete to action buttons

---
- [CRM-17154: CiviReport enhancements](https://issues.civicrm.org/jira/browse/CRM-17154)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@samuelsov I have just recut this over the top of our newly merged master - I haven't re-reviewed or made any changes we have discussed yet...

**Comment by samuelsov** [comment]
I think it's better to have buttons or links rather than a select list for actions. The only place (i believe) where a select gives actions is in a search result and i don't think it's clear for the user that it will trigger an action when an item is selected.

I'd rather use a dropdown menu (e.g. "Actions" button from the contact summary page) as a starting point.
In this case, i think we should quite easily:
1. separate the "show results" (the obvious action) from "save, save a copy, delete" and possibly "add to my report"
2. have a dropdown menu "actions" (like in the contact page) or "export" that contains links for "print, pdf, csv (with icons)
3. add a title "Display as" for the type of display (tabular, bar, pie)

**Comment by eileenmcnaughton** [comment]
Sigh - but the search style was @colemanw's suggestion :-)

**Comment by colemanw** [comment]
The nice thing about using select2 for actions is the searchability, which is good for long lists of actions.
The not nice things is that it's inconsistent with places like "actions" on the contact summary page. Both of those designs have their flaws, though. And moving toward a consistent, well-designed action menu for use in our app would be a great project for someday.

**Comment by eileenmcnaughton** [comment]
Hmm & what about WRT this specific change - what is your position on it?

**Comment by colemanw** [comment]
Overall :+1: 
There are a few refinements I would make, like giving the dropdown the `crm-action-menu` css class.
Also adding an icon to each item in the menu would be a nice-to-have and maybe quick-n-easy.
There's also no logical reason *not* to have "add to group" be in the same menu and would just take a little javascript to implement (hiding the current "add to group" menu and showing it in a popup when choosing that action).
None of those are blockers IMO.

**Comment by eileenmcnaughton** [comment]
Hmm @samuelsov so now I'm not clear if you & @colemanw disagree. From my point of view I can accept either approach.

**Comment by samuelsov** [comment]
I guess as coleman mentioned, have a consistent action menu is a project for another day and need more than a short discussion in github.

I will probably keep the select2 for now and see how far i could go without postponing the merge of this PR (add icons, add to group in the list)

**Comment by eileenmcnaughton** [comment]
@samuelsov should I read into your comment that you are tweaking it at the moment?

**Comment by samuelsov** [comment]
@eileenmcnaughton I'm not working on it right now but i plan to... if you want to do it, please go but warn me first to avoid duplicate work

**Comment by JoeMurray** [comment]
@spalmstr would you be interested in reviewing this PR?

**Comment by eileenmcnaughton** [comment]
I think @samuelsov  is already engaged on this one

**Comment by spalmstr** [comment]
Hi Joe,

 

Many thanks for several emails and link to the planning spreadsheet.  The spreadsheet contains useful information as well as the list of PRs etc.

 

I confess to being a bit hazy about what the PR is supposed to do, as the issue doesn’t really explain it save that it seems to be a change to the user interface of CiviReports (or perhaps I’ve even misunderstood that).

 

Have I understood correctly that the process is to use a remote terminal, e.g. Putty, to create the test site as per the instructions and that the process gives you the URL for the test site?  Am I right in thinking that the PRs are just tested against Drupal, or should we also be testing against Joomla and WordPress?  The organisation I support runs CiviCRM under Joomla.

 

Are there any test scripts that can be used in the process?

 

When do you need the results?  This review is just one of many ‘balls in the air’.

 

Looking at the list makes me realise the Trojan work all you good folk are doing maintain CiviCRM.

 

Kind regards,

 

Stephen Palmstrom

**Comment by spalmstr** [comment]
In which case, I am happy to bow out.

**Comment by samuelsov** [comment]
This issue still needs a bit of work (adding css classes / icons) and then a fair bit of testing.
@spalmstr - I think i can handle this, thanks !

**Comment by samuelsov** [comment]
A few things that need to be fix : 
* delete action doesn't seems to work
* save a copy action doesn't display a screen to ask for a new report title / description as the button does
* when doing an action, the page refresh but the action is not always reseted
* "View as ..." actions are not correctly filtered (View as tabular data is never displayed)
* avoid duplicate button / action -> i suggest to keep only "Refresh result" as a button and all others in the Actions list for simplicity's sake... most user just want to refresh.

**Comment by eileenmcnaughton** [comment]
OK - I'll take a look

**Comment by eileenmcnaughton** [comment]
I've pushed fixes for

- delete action doesn't seems to work
- avoid duplicate button / action -> i suggest to keep only "Refresh result" as a button and all others in the Actions list for simplicity's sake... most user just want to refresh.

Re 

- "View as ..." actions are not correctly filtered (View as tabular data is never displayed)

That isn't in the actions menu at this stage - but it only shows on specific reports and only AFTER the results are showing - e.g Contribution Summary - it should be unchanged by this PR

**Comment by eileenmcnaughton** [comment]
I'm looking at these 2 now 

- save a copy action doesn't display a screen to ask for a new report title / description as the button does
- when doing an action, the page refresh but the action is not always reseted

**Comment by eileenmcnaughton** [comment]
I had a go at the icons but I couldn't figure out how to add the option with an icon without mangling the font. Note that I could not add a span to precede it using the method

```
      $select = $this->add('select', 'task', NULL, array('' => ts('Actions')), FALSE, array(
        'class' => 'crm-select2 crm-action-menu fa-check-circle-o huge crm-search-result-actions')
      );
      foreach ($tasks as $key => $task) {
        $select->addOption($task['title'], $key, array(
          'class' => 'crm-i ' . CRM_Utils_Array::value('class', $task)
        ));
      }
```
screenshot 2016-06-22 16 01 42

**Comment by eileenmcnaughton** [comment]
@samuelsov I have addressed the issues you identified!!

**Comment by samuelsov** [comment]
@eileenmcnaughton wow, already ? let me check...

**Comment by samuelsov** [comment]
@eileenmcnaughton Overall, i'm happy with it. 
I just have a few concerns : 
* if you export as csv (same for pdf), the action is not reseted so if you do a view results after that using the button, it will export instead of refreshing the page
* can we remove the "view results" from the action list ? it is already there as a button
* "Update" seems unclear to me (do we want to update the display or save the report), can we change it to "Save" (not blocking, i let you judge which one is best)
* add contacts to group should definitively go to the action list (but let's have another PR for that later)

**Comment by eileenmcnaughton** [comment]
I changed update to Save & removed the extra refresh. I'm struggling to clear out the action on csv though

**Comment by eileenmcnaughton** [comment]
Hmm - I can't think my way through how to handle the csv & pdf at the moment - I can't clear the setting before it js-submits because if I do it will lose the settng but there is no refresh to unset it through php....

**Comment by eileenmcnaughton** [comment]
@samuelsov I think I got it this time! I really want to get this merged before Yashi forks the rc - are you able to recheck it? Probably late for you? Maybe given it's gotten to a point of clear blockers which I believe are resolved I should merge ? At least the release cycle means this is the last-minute before test-week starts, not the last minute before release

**Comment by yashodha** [comment]
Merging as per confirmation from @JoeMurray @eileenmcnaughton

**Comment by samuelsov** [comment]
A bit too late but all is good :thumbsup:

**Pull request merged**
