### PR TITLE
Alternate fix to remove extraneous tax display

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
@jitendrapurohit what about this as an alternative to https://github.com/civicrm/civicrm-core/pull/29859

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Review by jitendrapurohit — APPROVED** [review]
Thank you for the fix @eileenmcnaughton. Confirmed this is working fine 👍

**Comment by seamuslee001** [comment]
@eileenmcnaughton test fail seems to relate

```
CRM_Contribute_Form_ContributionTest::testEmailReceiptOnPayLater with data set #0 (true)
Error: Typed property CRM_Contribute_Form_Contribution::$order must not be accessed before initialization

/home/homer/buildkit/build/build-2/web/sites/all/modules/civicrm/CRM/Contribute/Form/Contribution.php:939
/home/homer/buildkit/build/build-2/web/sites/all/modules/civicrm/CRM/Contribute/Form/Contribution.php:971
/home/homer/buildkit/build/build-2/web/sites/all/modules/civicrm/CRM/Contribute/Form/Contribution.php:618
/home/homer/buildkit/build/build-2/web/sites/all/modules/civicrm/CRM/Core/Form.php:774
/home/homer/buildkit/build/build-2/web/sites/all/modules/civicrm/Civi/Test/FormWrapper.php:143
/home/homer/buildkit/build/build-2/web/sites/all/modules/civicrm/tests/phpunit/CRM/Contribute/Form/ContributionTest.php:2148
/home/homer/buildkit/build/build-2/web/sites/all/modules/civicrm/tests/phpunit/CRM/Contribute/Form/ContributionTest.php:625
/home/homer/buildkit/build/build-2/web/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:284
/home/homer/buildkit/extern/phpunit9/phpunit9.phar:2307
```

**Comment by eileenmcnaughton** [comment]
@seamuslee001 yeah - I opened a couple or PRs to tackle some of those side-issues - this was one https://github.com/civicrm/civicrm-core/pull/29907

**Comment by eileenmcnaughton** [comment]
I don't think I did the last one - was kinda on hold for those others

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
I've brought this back to the actual issue - I think it will still hit a notice - likely fixed by this https://github.com/civicrm/civicrm-core/pull/29936 & one other

**Comment by eileenmcnaughton** [comment]
Just the one fail - I expect https://github.com/civicrm/civicrm-core/pull/29936 to address

CRM_Contribute_Form_ContributionTest::testEmailReceiptOnPayLater with data set #1 (false)
Undefined array key "tax_amount"

/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/CRM/Price/BAO/PriceField.php:786
/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/CRM/Price/BAO/PriceField.php:497
/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/CRM/Contribute/Form/Contribution.php:963
/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/CRM/Contribute/Form/Contribution.php:615
/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/CRM/Core/Form.php:774
/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/Civi/Test/FormWrapper.php:143
/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/tests/phpunit/CRM/Contribute/Form/ContributionTest.php:2148
/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/tests/phpunit/CRM/Contribute/Form/ContributionTest.php:625
/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:284
/home/homer/buildkit/extern/phpunit9/phpunit9.phar:2307

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
Merging based on @jitendrapurohit's review

**Pull request merged**
