### PR TITLE
Rename agpl-3.0.txt to License

### PR DESCRIPTION
**Pull request by carlin-q-scott**
Overview
----------------------------------------
This is the standard name for the license file and will improve this project's community score from GitHub.

### CODE REVIEW

**Comment by philipwhiuk** [comment]
Based on https://help.github.com/en/articles/adding-a-license-to-a-repository shouldn't it be `LICENSE` ?

**Comment by carlin-q-scott** [comment]
@philipwhiuk Yes, or LICENSE.md. However, I don't think capitalization matters. I can fully capitalize it though to make sure it matches the documentation.

**Comment by eileenmcnaughton** [comment]
@totten @colemanw @mlutfy pinging you in case you can see any reason for hesitation

The link above says "In the file name field, type LICENSE or LICENSE.md (with all caps)."

I'd probably vote for the latter but a soft vote

**Comment by eileenmcnaughton** [comment]
let's go with it!

**Pull request merged**
