### PR TITLE
(NFC) Update CRM/Event folder for the new coder style

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
Title says it all ping @eileenmcnaughton @totten @colemanw

### CODE REVIEW

**Comment by colemanw** [comment]
I'd be tempted to merge this into the 5.13 branch to make ESR backports simpler in the future.

**Comment by seamuslee001** [comment]
@colemanw @totten switched to 5.13

**Comment by colemanw** [comment]
test this please

**Comment by seamuslee001** [comment]
Merging as per the tag

**Pull request merged**
