### PR TITLE
dev/translation#48 Implement Brick/Money to better handle money values

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This implements the PHP library brick/money https://github.com/brick/money to better handle currency amounts

Before
----------------------------------------
Non standard library used

After
----------------------------------------
Library used to make calculations

https://lab.civicrm.org/dev/translation/-/issues/48

ping @eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Looks good to me - when you fix the style can you add     "ext-intl": "*" to composer.json

**Comment by seamuslee001** [comment]
done @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I worked on my own mini-implementation of this - https://github.com/civicrm/civicrm-core/pull/17609

& I hit an issue where the value 
269.565217391 caused it to get upset - I wonder if there is one that long in the tests

In the PR I did adding rounding was the answer - but that's because I wanted rounding too

**Comment by eileenmcnaughton** [comment]
@seamuslee001 can you try adding 269.565217391 to the test to ensure it doesn't kill it

**Comment by eileenmcnaughton** [comment]
(if good then let's merge)

**Comment by seamuslee001** [comment]
@eileenmcnaughton had to add in the rounding but this should work now

**Comment by eileenmcnaughton** [comment]
@seamuslee001 that's what I thought - this does make sense in the context of how this is called - ie. it's serving up presentation layer information, but if it were called earlier in the chain it could cause problems. That's non-blocking here since but I think the learning we should take is that we should pass around the Money object & convert to float at the last minute - so really this function probably *should* return a money object 

I think it's OK to merge but we need to do some docs / communicate on this before we are done with it..

@mattwire FYI

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I'm flinching a bit here -we didn't dig that deep on whether php-intl could be missing. we should think about 
-status checks
- keeping a fallback for now
- noise
- pre-upgrade message

**Comment by JoeMurray** [comment]
Just a question you've likely already examined but...have we checked about whether our money fields can support all currencies? As I recall there are a number that have a different number of decimals other than 2, and I imagine the ones that require more need to be excluded as unsupported. There were some national currencies like this that are in the standard iirc and others that have had support in CiviCRM at different times like bitcoin. 

BTW, has anyone spent the money to buy https://www.currency-iso.org/ ? We should charge this to the core team and make it available to developers working on money as needed without inappropriately publishing it.

**Comment by eileenmcnaughton** [comment]
@JoeMurray  they do btc - which has many decimal places....

**Pull request merged**
