### PR TITLE
dev/core#1246 fix fatal error on search builder if a core contact type is disabled

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
This is a more thorough treatment of @eileenmcnaughton's #15279 that makes the code more contact-type agnostic by removing some hard-coded assumptions about what contact types should & shouldn't exist.

https://lab.civicrm.org/dev/core/issues/1246

Before
----------------------------------------
Fatal error on search builder.

After
----------------------------------------
Works

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw can you switch branch to the rc? We should include in 5.17 drop

**Comment by colemanw** [comment]
retest this please

**Comment by seamuslee001** [comment]
added Merge on pass as added Merge on pass to 5.17

**Comment by eileenmcnaughton** [comment]
unrelated  fail

**Pull request merged**
