### PR TITLE
Fix missing contactID when registering for paid event from waitlist

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
See https://lab.civicrm.org/extensions/stripe/-/issues/347 but note this is not a Stripe issue and variants of this will happen with any payment processor because no contact ID is passed in when registering from the waitlist.

For a processor using payment propertyBag accessing contactID will cause CiviCRM to crash. For a payment processor using the passed in array there will at least be a PHP notice if contact_id is accessed and anything that needs the contact ID will not be setup correctly.

Before
----------------------------------------
Attempt to make a paid registration from the waitlist has no contact ID and can cause payment processors to fail.

After
----------------------------------------
Attempt to make a paid registration from the waitlist succeeds.

Technical Details
----------------------------------------
The registration code is rather complex but basically:
- When registering via waitlist (civicrm/register/confirm?participantId=X) the parameters that get passed to the `processPayment()` function (https://github.com/civicrm/civicrm-core/blob/master/CRM/Event/Form/Registration/Confirm.php#L1262) does not include a contact ID in the `$value` array.
- When registering through the "normal" register form a contact ID *is* included in the `$value` array as `$value['contact_id'].
- We already calculated the primary contact ID and it's a simple step to pass it in if not already set.

Comments
----------------------------------------
There's not much testing on register from waitlist. I found `CRM_Event_Form_Registration_RegisterTest::testDoubleWaitlistRegistration()` which could probably be extended.

### CODE REVIEW

**Comment by mattwire** [comment]
test this please

**Comment by seamuslee001** [comment]
@mattwire I had a client that faced this issue and the substantive part of your patch worked for me but I see for your test it is failing with 

```
InvalidArgumentException: setAmount requires a numeric amount value

/home/jenkins/bknix-dfl/build/core-23358-2tktp/web/sites/all/modules/civicrm/Civi/Payment/PropertyBag.php:466
/home/jenkins/bknix-dfl/build/core-23358-2tktp/web/sites/all/modules/civicrm/Civi/Payment/PropertyBag.php:241
/home/jenkins/bknix-dfl/build/core-23358-2tktp/web/sites/all/modules/civicrm/Civi/Payment/PropertyBag.php:366
/home/jenkins/bknix-dfl/build/core-23358-2tktp/web/sites/all/modules/civicrm/Civi/Payment/PropertyBag.php:129
/home/jenkins/bknix-dfl/build/core-23358-2tktp/web/sites/all/modules/civicrm/CRM/Core/Payment/Dummy.php:192
/home/jenkins/bknix-dfl/build/core-23358-2tktp/web/sites/all/modules/civicrm/CRM/Event/Form/Registration/Confirm.php:1272
```

**Comment by eileenmcnaughton** [comment]
the test did it

**Comment by agileware-justin** [comment]
Fixes https://lab.civicrm.org/dev/core/-/issues/3105

**Pull request merged**
