### PR TITLE
core#2633 : Cannot remove Group Organisation selection in multisite setup

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Steps to replicate:

1. Go to any existing or create new group.
2. Select 'Organization' from the drop down and save.
3. Go the setting page of the group and unselect the organisation.

Before
----------------------------------------
Revisit the group setting form and you will find that the organisation selection is not removed.

After
----------------------------------------
Revisit the group setting form and you will find that the organisation selection is removed.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@johntwyman - is this something you could test / review?

**Comment by johntwyman** [comment]
> @johntwyman - is this something you could test / review?

@eileenmcnaughton sure thing. Reckon I can test today/tomorrow. Will add a comment ASAP.

**Comment by eileenmcnaughton** [comment]
thanks @johntwyman  - I appreciate it

**Comment by johntwyman** [comment]
@eileenmcnaughton @monishdeb I've tested this PR against our multisite installation. I have noted the following:

- when I change the organization and click Save, the record in `civicrm_group_organization` is _updated_ accordingly
- when I remove the organization and click Save, the record in `civicrm_group_organization` is _removed_ accordingly
- when I click Settings for the group, the "Associated Organization" dropdown _always_ prefills the current domain/subsite organization contact

So as tested, the PR produces the right results in the database but the form is always prefilling the dropdown with the current domain/subsite's organization contact.

**Comment by eileenmcnaughton** [comment]
@johntwyman I feel like that's by design & possibly coming from the multisite extension? Using the domain organization was the way we got away from the non-performant parent-child set up if I recall correctly

**Comment by demeritcowboy** [comment]
Is there agreement on how the dropdown should work here?

**Comment by jaapjansma** [comment]
@monishdeb are you willing to do some follow up work based on @johntwyman review? If not we would advice to close this PR.

**Pull request merged**
