### PR TITLE
SearchKit - Take search filters from the url when viewing a standalone display

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
This passes through all query params from the url fragment as search filters to the display.

Before
----------------------------------------
Query params ignored

After
----------------------------------------
Query params passed to search filters.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw I'm not sure how to construct a url to test this

**Comment by eileenmcnaughton** [comment]
oh hang on - this DID work

https://dmaster.localhost:32353/civicrm/search#/display/alive/lpa?id=196

**Comment by eileenmcnaughton** [comment]
OK this works - I can also filter by fields that are NOT specified in the saved search in any way

https://dmaster.localhost:32353/civicrm/search#/display/alive/lpa?last_name=Ivanov

But AFAIK it's not until we have a form that you could access anything that your permissions would not normally permit (configuration dependent) 

@totten @seamuslee001 also

**Comment by eileenmcnaughton** [comment]
@colemanw I did some more testing on this and hit something else we should probably consider 

The only way I could filter by gender is link this

image


But I suspect that filtering by gender_id as a number would be wanted. I'm OK with this being merged if we are committed to supporting that url format (& we can consider enhancing to include gender_id / gender_id:name after

**Comment by colemanw** [comment]
@eileenmcnaughton I've pushed up an additional change to allow variations on the field suffix, so that if e.g. `gender_id:label` is in the SELECT clause you can pass url args `gender_id:label=Male` or `gender_id:name=M` or `gender_id=2` interchangeably.

**Comment by eileenmcnaughton** [comment]
@colemanw that's better - I'm a bit tempted to move this to the rc because it only just moved out and I started doing a bit of documenting yesterday and it might be easier if this were in ( the stuff I did yesterday triggered a 'published' email but I can't see it yet)

**Comment by eileenmcnaughton** [comment]
oh - found the link to my efforts so far https://docs.civicrm.org/user/en/latest/the-user-interface/search-kit/

**Comment by eileenmcnaughton** [comment]
looks like the formatting is pretty wonky atm

**Comment by colemanw** [comment]
Ok @eileenmcnaughton I've changed the base. Agree this is suitable for merging into the RC.

**Pull request merged**
