### PR TITLE
CRM-17646 Add hook for modifying field option lists

### PR DESCRIPTION
**Pull request by colemanw**
https://issues.civicrm.org/jira/browse/CRM-17646

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton I'm proud of this one: it adds new methods, several new unit tests, more comments and a new hook, for a grand total of **−563** SLOC :)

**Comment by eileenmcnaughton** [comment]
AND it's impossible for me to backport :-(

**Comment by colemanw** [comment]
Note: also merge https://github.com/civicrm/civicrm-drupal/pull/336 & https://github.com/civicrm/civicrm-drupal/pull/337 when merging this.

**Comment by colemanw** [comment]
@eileenmcnaughton if you really wanted to you could do a minimal sort of backport that calls the new hook "all over the place" where custom field options are retrieved in 4.6 and not worry about all the consolidation.

**Comment by eileenmcnaughton** [comment]
Ah - is this one just custom field options? The requests I've been getting are for tags, & option values (activity type right through to obscure things). The driver for the request is actually reducing clutter not security

**Comment by colemanw** [comment]
This PR creates a hook for modifying the option list of any field. It deprecates [hook_civicrm_customFieldOptions](http://wiki.civicrm.org/confluence/pages/viewpage.action?pageId=86213400).

See http://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_fieldOptions

**Comment by colemanw** [comment]
Was working offline last week an just ended up pushing a bunch of semi-related, semi-random fixes into this branch. Better merge it before it gets any bigger.

**Pull request merged**
