### PR TITLE
CRM-18212 - Allow triggers to be managed offline

### PR DESCRIPTION
**Pull request by totten**
This is a reformulation of @eileenmcnaughtons's #8036.  A few things:
1. The basic idea is the same -- the SQL operations for managing triggers
   can be redirected to a file. Many things are copied/imitated from #8036.
2. No changes are required to the logging layer (CRM-18310).
   I feel like the original patch added unnecessary layers and had to
   work fairly hard to disable standard logging functionality (e.g.
   normal logging has severity-levels and the ability to reroute
   messages to non-file media).
3. The feature is flagged as EXPERIMENTAL. While it seems to do what's
   advertised, I'm not convinced that we've actually defined a 
   reproducible configuration -- i.e. there's more rules/workflows
   involved to using this mode, and I'm not enitrely sure what they are.
   Moreover, producing tests to support this configuration is
   problematic (because normally test environments have high privileges).

---
- [CRM-18212: Allow for triggers to be managed offline](https://issues.civicrm.org/jira/browse/CRM-18212)
- [CRM-18310: Add tests to debug functions, fix identified error & add ability to log raw messages](https://issues.civicrm.org/jira/browse/CRM-18310)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by totten** [comment]
jenkins, test this please

[Last build](https://test.civicrm.org/job/CiviCRM-Core-PR/8867/) reported a large number of strange errors which don't reproduce locally. (`[nativecode=1005 ** Can't create table 'Ig_civicrm_temp_custom_03eb52ea6c0eed91143d438238271951' (errno: 24)]` and `PEAR_Exception: DB Error: no such table`)

**Comment by totten** [comment]
jenkins, test this please

**Comment by eileenmcnaughton** [comment]
#test

I tried turning logging one and off with this setting present & absent in civicrm.settings.php

  global $civicrm_setting;
$civicrm_setting['CiviCRM Preferences']['logging_no_trigger_permission'] = 1;

As expected 
- without the setting the triggers were dropped and created when I turned logging on and off through the UI
- with the setting the trigger sql was output to a file and I got a message with the file name.

I tried running the trigger sql output for turn-on & turn-off actions and it ran fine.

I also verified that when turning triggers on & off missing log tables were created (by deleting a log table & then re-enabling triggers). This continued to work with & without the setting

**Pull request merged**
