### PR TITLE
See how many tests fail with this check

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
_A brief description of the pull request. Keep technical jargon to a minimum. Hyperlink relevant discussions._

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by seamuslee001** [comment]
1902 failures

**Comment by eileenmcnaughton** [comment]
Excluding syntax conformance now - also using apiv4 to avoid that first fail - although I note it shows an apiv3 bug - it check_permissions = FALSE is not getting the whole way down the v3 api Contribution query stack

CRM_Activity_BAO_ActivityTest::testTargetContactNotavaliable
Failure in api call for Contribution get:  Undefined property: CRM_Core_Permission_UnitTests::$permissions
#0 /home/jenkins/bknix-dfl/build/core-20420-2pveb/web/sites/all/modules/civicrm/CRM/Core/Permission/UnitTests.php(48): PHPUnit\Util\ErrorHandler->__invoke(8, 'Undefined prope...', '/home/jenkins/b...', 48, Array)
#1 /home/jenkins/bknix-dfl/build/core-20420-2pveb/web/sites/all/modules/civicrm/CRM/Core/Permission.php(125): CRM_Core_Permission_UnitTests->check('all CiviCRM per...', NULL)
#2 /home/jenkins/bknix-dfl/build/core-20420-2pveb/web/sites/all/modules/civicrm/CRM/Core/Permission.php(218): CRM_Core_Permission::check(Array)
#3 /home/jenkins/bknix-dfl/build/core-20420-2pveb/web/sites/all/modules/civicrm/CRM/Core/Permission.php(264): CRM_Core_Permission::customGroupAdmin()
#4 /home/jenkins/bknix-dfl/build/core-20420-2pveb/web/sites/all/modules/civicrm/CRM/Core/BAO/CustomField.php(377): CRM_Core_Permission::customGroupClause(2, 'civicrm_custom_...')
#5 /home/jenkins/bknix-dfl/build/core-20420-2pveb/web/sites/all/modules/civicrm/CRM/Core/BAO/CustomField.php(591): CRM_Core_BAO_CustomField::getFields(Array, false, false, NULL, NULL, false, false, true)
#6 /home/jenkins/bknix-dfl/build/core-20420-2pveb/web/sites/all/modules/civicrm/CRM/Contribute/BAO/Query.php(872): CRM_Core_BAO_CustomField::getFieldsForImport('Contribution')
#7 /home/jenkins/bknix-dfl/build/core-20420-2pveb/web/sites/all/modules/civicrm/api/v3/Contribution.php(250): CRM_Contribute_BAO_Query::defaultReturnProperties(2)
#8 /home/jenkins/bknix-dfl/build/core-20420-2pveb/web/sites/all/modules/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_contribution_get(Array)
#9 /home/jenkins/bknix-dfl/build/core-20420-2pveb/web/sites/all/modules/civicrm/Civi/API/Kernel.php(149): Civi\API\Provider\MagicFunctionProvider->invoke(Array)
#10 /home/jenkins/bknix-dfl/build/core-20420-2pveb/web/sites/all/modules/civicrm/Civi/API/Kernel.php(81): Civi\API\Kernel->runRequest(Array)
#11 /home/jenkins/bknix-dfl/build/core-20420-2pveb/web/sites/all/modules/civicrm/api/api.php(22): Civi\API\Kernel->runSafe('Contribution', 'get', Array)

**Comment by eileenmcnaughton** [comment]
I'll re-test once https://github.com/civicrm/civicrm-core/pull/20415 is merged

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
CRM_Contribute_BAO_ContributionRecurTest.testAutoRenewalWhenOneMemberIsDeceased
CRM_Core_BAO_MessageTemplateTest.testContactTokens
CRM_Core_Payment_BaseIPNTest.testThatCancellingEventPaymentWillCancelAllAdditionalPendingParticipantsAndCreateCancellationActivities
CRM_Event_BAO_ChangeFeeSelectionTest.testCRM19273
CRM_Event_BAO_ChangeFeeSelectionTest.testCRM17151
CRM_Event_Form_Registration_ConfirmTest.testPaidSubmit with data set #0
CRM_Event_Form_Registration_ConfirmTest.testPaidSubmit with data set #1
CRM_Event_Form_Registration_ConfirmTest.testTaxMultipleParticipant
CRM_Financial_BAO_FinancialItemTest.testAdd
CRM_Financial_BAO_FinancialItemTest.testRetrieve
CRM_Financial_BAO_FinancialItemTest.testCreate
CRM_Member_Form_MembershipTest.testFinancialEntriesOnCancelledContribution
CRM_Member_Form_MembershipTest.testTwoInheritedMembershipsViaPriceSetInBackend
CRM_Member_Form_MembershipTest.testTwoMembershipsViaPriceSetInBackendWithDiscount
CRM_Member_Form_MembershipTest.testContributionFormStatusUpdate
CRM_Member_Form_MembershipTest.testCreatePendingWithMultipleTerms
CRM_Report_Form_Contribute_DetailTest.testReportOutput with data set #0
CRM_Report_Form_Contribute_DetailTest.testPostalCodeSearchReportOutput with data set #0
CRM_Report_Form_Contribute_DetailTest.testMultipleSoftCredits
CRM_Report_Form_Contribute_DetailTest.testContributeDetailReportWithNewColumnFromCustomTable
CRM_Report_Form_TestCaseTest.testReportOutput with data set #0
CRM_Report_Form_TestCaseTest.testReportOutput with data set #1
CRM_Report_Form_TestCaseTest.testReportOutput with data set #2
CRM_Report_Form_TestCaseTest.testBadReportOutput with data set #0
CRM_Report_Form_TestCaseTest.testBadReportOutput with data set #1
api_v3_ACLPermissionTest.testEntitiesGetHookLimitingHookNoCheck with data set #0
api_v3_ACLPermissionTest.testEntitiesGetCoreACLLimitingHookNoCheck with data set #0
api_v3_ACLPermissionTest.testEntitiesGetCoreACLLimitingCheck with data set #0
api_v3_LineItemTest.testDeleteLineItem with data set "APIv3"
api_v3_LineItemTest.testDeleteLineItem with data set "APIv4"
api_v3_MembershipTest.testActivityForCancelledContribution
api_v3_PaymentTest.testRefundPaymentWithCancelledPaymentId
api_v3_ProfileTest.testLegacySet
api_v3_ProfileTest.testContactActivitySubmitWithoutActivityId
api_v3_ProfileTest.testContactActivitySubmitWrongActivityId
api_v3_ProfileTest.testContactActivitySubmitWrongActivityType
api_v3_ProfileTest.testContactActivitySubmitSuccess
api_v3_ProfileTest.testProfileApplyWithoutProfileId
api_v3_ProfileTest.testProfileApplyInvalidProfileId
api_v3_ProfileTest.testProfileApply
api_v3_ProfileTest.testSubmitWithTags
api_v3_ProfileTest.testSubmitWithNote
api_v3_ProfileTest.testSubmitGreetingFields

**Comment by eileenmcnaughton** [comment]
I'm fairly sure these 3 represent real bugs
CRM_Core_Payment_BaseIPNTest.testThatCancellingEventPaymentWillCancelAllAdditionalPendingParticipantsAndCreateCancellationActivities
CRM_Event_BAO_ChangeFeeSelectionTest.testCRM19273
CRM_Event_BAO_ChangeFeeSelectionTest.testCRM17151

**Comment by seamuslee001** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
api_v3_ACLPermissionTest.testEntitiesGetHookLimitingHookNoCheck with data set #0
api_v3_ACLPermissionTest.testEntitiesGetCoreACLLimitingHookNoCheck with data set #0
api_v3_ACLPermissionTest.testEntitiesGetCoreACLLimitingCheck with data set #0
api_v3_LineItemTest.testDeleteLineItem with data set "APIv3"
api_v3_LineItemTest.testDeleteLineItem with data set "APIv4"
api_v3_MembershipTest.testActivityForCancelledContribution
api_v3_PaymentTest.testRefundPaymentWithCancelledPaymentId
CRM_Contribute_BAO_ContributionRecurTest.testAutoRenewalWhenOneMemberIsDeceased
CRM_Core_Payment_BaseIPNTest.testThatCancellingEventPaymentWillCancelAllAdditionalPendingParticipantsAndCreateCancellationActivities
CRM_Event_BAO_ChangeFeeSelectionTest.testCRM19273
CRM_Event_BAO_ChangeFeeSelectionTest.testCRM17151
CRM_Event_Form_Registration_ConfirmTest.testPaidSubmit with data set #0
CRM_Event_Form_Registration_ConfirmTest.testPaidSubmit with data set #1
CRM_Event_Form_Registration_ConfirmTest.testTaxMultipleParticipant
CRM_Financial_BAO_FinancialItemTest.testAdd
CRM_Financial_BAO_FinancialItemTest.testRetrieve
CRM_Financial_BAO_FinancialItemTest.testCreate
CRM_Member_Form_MembershipTest.testFinancialEntriesOnCancelledContribution
CRM_Member_Form_MembershipTest.testTwoInheritedMembershipsViaPriceSetInBackend
CRM_Member_Form_MembershipTest.testTwoMembershipsViaPriceSetInBackendWithDiscount
CRM_Member_Form_MembershipTest.testContributionFormStatusUpdate
CRM_Member_Form_MembershipTest.testCreatePendingWithMultipleTerms
CRM_Report_Form_Contribute_DetailTest.testReportOutput with data set #0
CRM_Report_Form_Contribute_DetailTest.testPostalCodeSearchReportOutput with data set #0
CRM_Report_Form_Contribute_DetailTest.testMultipleSoftCredits
CRM_Report_Form_Contribute_DetailTest.testContributeDetailReportWithNewColumnFromCustomTable
CRM_Report_Form_TestCaseTest.testReportOutput with data set #0
CRM_Report_Form_TestCaseTest.testReportOutput with data set #1
CRM_Report_Form_TestCaseTest.testReportOutput with data set #2
CRM_Report_Form_TestCaseTest.testBadReportOutput with data set #0
CRM_Report_Form_TestCaseTest.testBadReportOutput with data set #1

**Comment by eileenmcnaughton** [comment]
I'm not actively working on this this week so it doesn't belong in the review queue at the moment

**Pull request closed without merging**
