### PR TITLE
Report enhancements

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Add source as a detail report filter, allow grouping by date

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
unrelated test issues

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
I tested this on a 47 CiviBuild report changes work as expected and was able to see title changes as well

**Comment by monishdeb** [comment]
@eileenmcnaughton there is a regression due to these changes. When you use barchart on 'Contribution Summary' report it throws notices and unable to build barchart, because the $field['title'] is also used as an interval for building barchart 
1. https://github.com/civicrm/civicrm-core/blob/master/CRM/Report/Form/Contribute/Summary.php#L353
2. and then https://github.com/civicrm/civicrm-core/blob/master/CRM/Report/Form/Contribute/Summary.php#L816
which is incorrect as we need to use m/c name as interval rather then field label. So I would say 'whack-a-mole' regression :p 

  I have submitted a PR for this https://github.com/civicrm/civicrm-core/pull/8839.

**Pull request merged**
