### PR TITLE
Deprecate guess work in processPriceSet

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Testing to see how much of this we can deprecate - line items should
be 'complete' before reaching the processing function

Overview
----------------------------------------
_A brief description of the pull request. Keep technical jargon to a minimum. Hyperlink relevant discussions._

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by seamuslee001** [comment]
decent amount of test fails here

**Comment by eileenmcnaughton** [comment]
@seamuslee001 yep - seems to  be mostly because tests aren't using the order api & are doing weird setup - I think the answer is to make the order api easier to use - see #20681 

api_v3_ContributionTest.testRepeatTransactionMembershipRenewContributionNotCompleted with data set #1
api_v3_ContributionTest.testRepeatTransactionMembershipRenewContributionNotCompleted with data set #2
api_v3_ContributionTest.testRepeatTransactionMembershipRenewContributionNotCompleted with data set #3
api_v3_ContributionTest.testRepeatTransactionMembershipRenewContributionNotCompleted with data set #5
api_v3_ContributionTest.testRepeatTransactionMembershipRenewContributionNotCompleted with data set #6
api_v3_ContributionTest.testRepeatTransactionMembershipRenewContributionNotCompleted with data set #8
api_v3_ContributionTest.testRepeatTransactionMembershipRenewContributionNotCompleted with data set #9
api_v3_ContributionTest.testRepeatTransactionMembershipRenewContributionNotCompleted with data set #10
api_v3_ContributionTest.testRepeatTransactionMembershipRenewCompletedContribution
api_v3_ContributionTest.testRepeattransactionRenewMembershipOldMembership
api_v3_ContributionTest.testRepeatTransactionAlteredAmount
api_v3_ContributionTest.testRepeatTransactionMembershipCreatePendingContribution
api_v3_ContributionTest.testSendMailWithAPISetFromDetails
CRM_Core_Payment_PayPalIPNTest.testIPNPaymentInputMembershipRecurSuccess
CRM_Core_Payment_PayPalIPNTest.testhookAlterIPNDataOnIPNPaymentSuccess
CRM_Core_Payment_PayPalIPNTest.testPayPalIPNSuccessDeletedContact
CRM_Core_Payment_PayPalProIPNTest.testIPNPaymentRecurSuccess
CRM_Core_Payment_PayPalProIPNTest.testIPNPaymentMembershipRecurSuccess
CRM_Core_Payment_PayPalProIPNTest.testIPNPaymentCRM13743
CRM_Core_Payment_PayPalProIPNTest.testIPNPaymentExpressNoError
CRM_Core_Payment_PayPalProIPNTest.testIPNPaymentExpressRecurSuccess
CRM_Event_BAO_AdditionalPaymentTest.testPaymentWithCustomPaymentInstrument
CRM_Event_BAO_AdditionalPaymentTest.testAddPartialPayment
CRM_Event_BAO_AdditionalPaymentTest.testTransactionInfo
CRM_Event_BAO_ChangeFeeSelectionTest.testCRM19273
CRM_Event_BAO_ChangeFeeSelectionTest.testCRM21245
CRM_Event_BAO_ChangeFeeSelectionTest.testCRM20611

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 it's basically stalled on https://github.com/civicrm/civicrm-core/pull/20678 - once that is merged I'll get this passing & finish the financial fixes which is 1/3 of what membership api is stalled on (the other is the #20672  & something I now know how to fix but haven't)

**Comment by eileenmcnaughton** [comment]
Closing for now - stalled on review-ready PRs - note the ACTUAL change in here is 

https://github.com/civicrm/civicrm-core/pull/20678/files#diff-a16d4d7449cf5f3a0616d1d282a32f27ab6d3f7d2726d076c02ad1d4d655af41R394-R396

**Pull request closed without merging**
