### PR TITLE
[REF] BAO_Contact - Remove CRM_Utils_Array::value and other unnecessary code

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Some minor code cleanup in the Contact BAO class.

Before
----------------------------------------
Messier.

After
----------------------------------------
Neater.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw let's get this merged https://github.com/civicrm/civicrm-core/pull/16787 before considering this PR - I already had that open to do subsequent cleanup on #16724

**Comment by seamuslee001** [comment]
@colemanw can you rebase

**Comment by colemanw** [comment]
retest this pleases

**Comment by seamuslee001** [comment]
Changes all look consistent and look fine, Jenkins has oked it merging

**Pull request merged**
