### PR TITLE
 Stop adding obsolete currencies to new installs

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Stop adding obsolete currencies to new installs
    
CYP - Cyprus Pound
    https://www.centralbank.cy/en/banknotes-and-coins/cyprus-pound
    
LTL - Lithuanian litas
    https://en.wikipedia.org/wiki/Lithuanian_litas#:~:text=The%20Lithuanian%20litas%20(ISO%20currency,centas%2C%20nominative%20plural%20centai).
    
GWP - replaced in 1997 https://en.wikipedia.org/wiki/Guinea-Bissau_peso
    
LVL - https://www.investopedia.com/terms/forex/l/lvl-latvian-lat.asp#:~:text=The%20Latvian%20lats%20(LVL)%20was,was%20replaced%20by%20the%20euro.
    
MTL - https://www.investopedia.com/terms/m/mtl.asp
    
 ROL - https://en.wikipedia.org/wiki/Romanian_leu
    
SDD - https://www.investopedia.com/terms/s/sdd-sudanese-dinar.asp#:~:text=The%20Sudanese%20dinar%20(SDD)%20was,replaced%20the%20original%20Sudanese%20pound.
    
SIT - https://www.investopedia.com/terms/s/sit-slovenian-tolar.asp
    
SKK - https://en.wikipedia.org/wiki/Slovak_koruna
    
TMM - https://en.wikipedia.org/wiki/Turkmenistani_manat

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I was a bit surprised to find this lot in there 


(167, "XAG", NULL, "961", "Silver"),
(168, "XAU", NULL, "959", "Gold"),
(169, "XBA", NULL, "955", "Bond Markets Units European Composite Unit (EURCO)"),
(170, "XBB", NULL, "956", "European Monetary Unit (E.M.U.-6)"),
(171, "XBC", NULL, "957", "European Unit of Account 9 (E.U.A.-9)"),
(172, "XBD", NULL, "958", "European Unit of Account 17 (E.U.A.-17)"),
(173, "XCD",  "$", "951", "East Caribbean Dollar"),
(174, "XDR", NULL, "960", "Special Drawing Right"),
(175, "XFO", NULL,  NULL, "Gold-Franc"),
(176, "XFU", NULL,  NULL, "UIC-Franc"),
(177, "XOF", NULL, "952", "CFA Franc BCEAO"),
(178, "XPD", NULL, "964", "Palladium"),
(179, "XPF", NULL, "953", "CFP Franc"),
(180, "XPT", NULL, "962", "Platinum"),
(181, "XTS", NULL, "963", "Code for testing purposes"),
(182, "XXX", NULL, "999", "No currency involved"),

**Comment by seamuslee001** [comment]
look i'm sure you can still pay for things in gold right?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 that's not the problem - it's the people who won't take my XTS!

**Comment by seamuslee001** [comment]
this seems ok to me merge ready

**Comment by colemanw** [comment]
I guess this means no one will be able to donate to CiviCRM using platinum. But we still accept code for testing purposes!

**Comment by eileenmcnaughton** [comment]
@colemanw I didn't remove platinum....

**Pull request merged**
