### PR TITLE
Ensure that class-index is up-to-date after toggling extensions (B)

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

Builds on #24712. Note that #24743 and #24744 are two similar alternatives.

Description TODO.

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by totten** [comment]
* I suspect the variant in 24743 is more correct than 24744 wrt support for all lifecycle operations (install/enable/disable/uninstall). 
* When installing several extensions at the same tim, I suspect the variant in 24744 would fire fewer flushes than 24743. However, I'm not sure if that's impactful.

**Comment by eileenmcnaughton** [comment]
@totten so my take away from this is that we have generally stored most of the data that relates to site configuration (apis, configured pages, entities etc) in the `metadata` cache for the last little while. Looking at this I realise that you have also added in a new cache `index` for the class scanner. There are interdependencies between the two - in this specific case the entities and apis are being stored in the `metadata` cache but the available classes in the `index` cache so clearing `metadata` and not clearing `index` is a recipe for problems.

I think we should consider clearing the `index` cache from `rebuildMenusAndCaches` - which is called in this particular flow, and would make this redundant.

I'm not sure that will really solve the problem because as long as we have interdependent info in the two separate caches then clearing one & not the other will cause issues - but I do think we need a quick fix & a longer term fix

**Comment by totten** [comment]
Between variants (A) #24743  and (B) #24744, I think that (A) is in better shape (ie handles more lifecycle events; no merge-conflicts).

**Comment by eileenmcnaughton** [comment]
Hmm - OK there is a bit of ambiguity on the flow here 

 `rebuildMenuAndCaches() calls cleanupCaches() => flushCache()`

in that both `metadata` and that awful `CRM_Core_Tables` cache are cleared MORE than the index.

I think `CRM_Core_DAO_AllCoreTables` should probably use the metadata cache 


image

image

I'll look to merge the other PR & do some more testing but I think the above might hint at where an outstanding issue might be

OTOH I updated my live site to the unreleased 5.54 & the class loader issue there was fixed by the `psr0` fix (I only thought I'd applied that fix last week).

**Pull request closed without merging**
