### PR TITLE
Upgrade Karma version to latest version

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This upgrades Karma to the latest version according to npm

ping @eileenmcnaughton @colemanw

### CODE REVIEW

**Comment by seamuslee001** [comment]
jenkins re test this please

**Comment by seamuslee001** [comment]
jenkins re test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
test this please

**Comment by seamuslee001** [comment]
Merging as per the tag

**Pull request merged**
