### PR TITLE
CRM-18277 : add test for the contact.source field.

### PR DESCRIPTION
**Pull request by mlutfy**
- [CRM-18277: Backend Credit Card Transactions rewrite Source as 'recurring contribution'](https://issues.civicrm.org/jira/browse/CRM-18277)

### CODE REVIEW

**Comment by mlutfy** [comment]
I'm being super lazy (no dev env setup for tests) and wanted to see if this test will fail.

**Comment by eileenmcnaughton** [comment]
hey - since this didn't fail we should probably merge it - it's a correct addition to the test suite even if it didn't replicate your issue isn't it?

**Comment by mlutfy** [comment]
hmm, although was it the correct syntax? When I had written it, it was supposed to fail.

**Comment by eileenmcnaughton** [comment]
Closing in favour of #8387

**Pull request closed without merging**
