### PR TITLE
Switch replaceGreetingTokens over

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Another attempt at https://github.com/civicrm/civicrm-core/pull/21701 - note this replaces `replaceGreetingTokens` but if it works I would then stop calling & deprecate  that function & move the love up to processGreetingTemplate & then up one more level 

@colemanw I'm a bit stuck tracking down an apiv4 caching issue

```
    $group = \Civi\Api4\Group::get()
      ->addSelect('custom.*', 'id')
      ->addWhere('title', '=', 'Test Group With Custom Field')
      ->execute();
```

is failing because the apiv4 cache is loaded before the custom field is added

so this test fails
not ok 602 - Failure: CRM_Contact_Form_Task_AddToGroupTest::testAddToNewGroupWithCustomField

  ---
  message: new_custom_group.Custom_Field element exists?
  severity: fail

Before
----------------------------------------
legacy call to the hook replace

After
----------------------------------------
calls the token processor

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by totten** [comment]
There's also a test failure in `DynamicFKAuthorizationTest`. The backtrace is long - here's a condensed interpretation:

1. To reset the test (`DynamicFKAuthorizationTest::tearDown()`), it must recreate an `Organization`
2. To recreate an organization, it must set the greeting - for which the template has token `{contact.organization_name}`.
3. To resolve the token, it must determine what type of data is in`organization_name` (money, date, etc)
4. To determine the type, it pulls a list of all fields on `Contact` API
5. To get a list of fields on `Contact` API, it pulls a list of all possible joins
6. To get a list of all possible joins, it loops through `AllCoreTables` and scans all tables.
7. When looping through `AllCoreTables`, it tries to access `CRM_Fake_DAO_FakeFile`
8. But this DAO isn't real - it's just a fake value used to exercise the authz code. Failure due to undefined class.

I guess there are a couple potential weak-links in the chain. It could be the mocked entity ("Use a real entity - or make full class for the mock one!"). Or it could be the join-scan ("Writing to one table shouldn't require scanning all tables!").

**Comment by eileenmcnaughton** [comment]
@totten still not finishing :-(

**Comment by eileenmcnaughton** [comment]
the worst of the fails seem to be in this zone

RUN:[[./scripts/phpunit --tap --log-junit '/home/jenkins/workspace/CiviCRM-Core-PR@2/junit/Civi\AllTests.xml' '--exclude-group' 'ornery' 'Civi\AllTests']]
Parsing schema description /home/jenkins/bknix-dfl/build/core-21790-sdjf/web/sites/all/modules/civicrm/xml/schema/Schema.xml
Extracting database information
Extracting table information
TAP version 13
PHPUnit 8.5.15 by Sebastian Bergmann and contributors.

ok 1 - Civi\API\Event\PrepareEventTest::testOnPrepare with data set #0 ('onPrepare_null', array('Widget', 'frobnicate', array(98, 'green', 3)), array('frob[green]'))
# Installing core21790sdjftest_g5eol database
ok 2 - Civi\API\Event\PrepareEventTest::testOnPrepare with data set #1 ('onPrepare_wrapApi', array('Widget', 'frobnicate', array(98, 'green', 3)), array('frob[go green] and frob[who green]'))
not ok 3 - Error: Civi\API\Subscriber\DynamicFKAuthorizationTest::testOk with data set #0 ('Widget', 'create', array(20))
not ok 4 - Error: Civi\API\Subscriber\DynamicFKAuthorizationTest::testOk with data set #1 ('Widget', 'get', array(20))
not ok 5 - Error: Civi\API\Subscriber\DynamicFKAuthorizationTest::testOk with data set #2 ('FakeFile', 'create', array(10))
not ok 6 - Error: Civi\API\Subscriber\DynamicFKAuthorizationTest::testOk with data set #3 ('FakeFile', 'get', array(10))
not ok 7 - Error: Civi\API\Subscriber\DynamicFKAuthorizationTest::testOk with data set #4 ('FakeFile', 'create', array('fake_widget', 20))

**Comment by eileenmcnaughton** [comment]
@totten I think I might cry in the corner for a bit...

**Comment by totten** [comment]
Yeah, I went poking around `testApi4CustomEntityACL` yesterday, and it was a bit of a mystery to me. Just verbalizing in case it raises ideas... it seems that the test does this:

* Create a contact (`C2`); flag it as deleted; add some custom data
* Implement `hook_civicrm_aclWhereClause` to allow access to `C2`
* Use `CustomValue.get` to read *both* the custom-data and *also* `contact.first_name` (via join?)
* The result of `CustomValue.get` does mention C2 - but it fails to return the joined `contact.first_name`.

So... (1) i'd wouldn't have thought to test joining from `CustomValue` to a `contact`, though I guess it is pretty reasonable use-case; (2) given that it is a join, I would've expected `contact_id.first_name` or `entity_id.first_name` rather than `contact.first_name`; (3)  assuming all that is as-intended, it's hard to see why a change in *contact-greeting-tokens* would prevent `first_name` from loading. (4) I set breakpoints and inspected the DB during execution, and I could see that the `first_name` in the DB was the expected value.

My only theory is some kind of caching issue? Like the mechanism of token-valuation causes some cache to hydrate (or not hydrate), and the same cache is somehow important to the `CustomValue.get` join mechanism? Nothing comes to mind, though there are some parts of this code-path where I'm not super-familiar...

---

Happy to see some other failures in `TokenProcessorTest`s. I've worked on those tests for `hook_civicrm_token*()`, so maybe I'll give that  whirl.

**Comment by totten** [comment]
> Civi.Token.TokenProcessorTest.testRenderLocalizedHookToken
> Civi.Token.TokenProcessorTest.testHookTokenDiagonal
> Civi.Token.TokenProcessorTest.testHookTokenExtraChar

Pushed up a patch which should fix these. Each test registers more hook-listeners, and the hook-listeners aren't getting called at the needful time (due to `Civi::$statics[__CLASS__]['hook_tokens']`).

As for why the PR caused a change... I guess that the test invokes `indivdualCreate()` fairly early/often. With the revision, we get a very early call-path like `individualCreate()` => `replaceGreetingTokens()` => `TokenProcessor` => `CRM_Contact_Tokens`. Thus, fairly early on, it hydrates `Civi::$statics[__CLASS__]['hook_tokens']`. But now the hook-token-list is frozen, and it doesn't matter what the hook-listeners do.

@eileenmcnaughton The patch removes the static-cache because that seemed simple -and because I'm not sure it's frequent enough to need the static-cache. But I'm not wedded to that change. If you can figure a better way, then that's cool. Hopefully this at least points toward the issue.

**Pull request merged**
