### PR TITLE
Security messages should only be displayed to the appropriate users.

### PR DESCRIPTION
**Pull request by elinw**
# CRM-16314

### CODE REVIEW

**Comment by davecivicrm** [comment]
Elin - Ping us on IRC if you have questions about the style warnings.

**Comment by colemanw** [comment]
@agh1 is working on similar code, might be good for him to take a look at this.

**Comment by agh1** [comment]
Just talked through with @totten - the only way that code gets called is via CRM_Utils_Check::checkAll(), which in turn is called in only two places:
* CRM_Utils_Check::showPeriodicAlerts(), which requires Administer CiviCRM
* the System.check API, which also requires Administer CiviCRM

@PalanteJon @GinkgoMZD and I are in the middle of adding a system status page that will have these messages, too, but it'll also be limited to Administer CiviCRM.  We're planning on adding an additional permission so that a monitoring system using the API will have the permission to see the messages without being able to do all admin things.  (This would be similar to what @mlutfy did at https://github.com/aghstrategies/com.aghstrategies.civimonitor/commit/faaf74c083dedf7287f767cf057073faecb257ae .)

**Comment by agh1** [comment]
@elinw the issue does seem important, however--I just don't think this specific change would make a difference because it's already checking for the permission.

**Comment by elinw** [comment]
What would be really great in Joomla is to be able to limit it to those with core.admin rights. 
I did a fair amount of tracing (and I think the other fix I pushed to my pr about the rest authentication takes care of some of the other alert issues) but I really had trouble getting this specific set to not show (unlike say the update available one that works as I would expect).  But  I will look some more at it and let you know.  

Elin

**Pull request closed without merging**
