### PR TITLE
CRM-18661 Fix & add test for financial rows created by repeattransaction

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
- [CRM-18661: Two identical payments get associated with one contribution - also on demo site](https://issues.civicrm.org/jira/browse/CRM-18661)

### CODE REVIEW

**Comment by tamarmeir** [comment]
Taking a look at this now.....

**Comment by tamarmeir** [comment]
Tested by recording membership contribution from contribution page - only one line showed, but no payment instrument. Recording a membership contribution from the back end also resulted in one line being showed, but this time the payment instrument also showed - first screen shot shows results from GUI, second shows results from API explorer in financial transaction table.

picture1
picture3

**Comment by tamarmeir** [comment]
Re-tested - still receiving permission warnings as described in https://issues.civicrm.org/jira/browse/CRM-18757, and still no payment instrument listed in financial transaction - sorry :-(

**Comment by KarinG** [comment]
Confirmed CRM-18661 is resolved!

crm-18661

**Comment by KarinG** [comment]
Let's merge this in - definitively solves a critical issue.

**Pull request merged**
