### PR TITLE
CRM-19093 - i18n executeQuery regex pb

### PR DESCRIPTION
**Pull request by samuelsov**
Small fix that can have a big impact on multilingual installation of CiviCRM.
I have done a fair amount of test but a regex expert could help ensure it's the good approach.

The goal is to avoid having `civicrm_events_in_cart` being replaced by `civicrm_event_fr_CAs_in_cart` because the name contains the full name of another table, i.e. `civicrm_event`.

---
- [CRM-19093: executeQuery in i18n regex not working 100%](https://issues.civicrm.org/jira/browse/CRM-19093)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mlutfy are you able to review this. Or @TobiasLounsbury  is my go-to regex person...

**Comment by mlutfy** [comment]
@samuelsov Can you add a comment above the regexp to give an example of what it should, and should not match?

Ex:

```
// CRM-19083 
// Matches tables such as: civicrm_foo
// but must not match: civicrm_bar.
```

I think this is an area obscure enough to justify excessive code comments.

**Comment by samuelsov** [comment]
@mlutfy should be clearer

**Comment by mlutfy** [comment]
Patch seems good to me. Thanks!

**Pull request merged**
