### PR TITLE
CRM-19657 Fall back to system wide information if no default from email can be …

### PR DESCRIPTION
**Pull request by seamuslee001**
…found and no contribution page can be used and no receipt from is passed in and add test to prove it

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton this adds in the 2nd domain layer that Jamie had and i think it makes sense, from_email and from_name in the domain.getsingle call are called based on the from_email_address option group and can be empty if no default found. So rather than falling back to the logged in user we fall back here the email address set in the organisation information (domain_email) and the name of the domain which is as per Jamie's PR and I have added a test to prove this

**Comment by eileenmcnaughton** [comment]
Looks good - @jmcclelland did you see this?

Are all other PRs closed / JIRA? Do we mark the JIRA documentation required to suggest this is worth documenting? & is it explained anywhere that a documenter could understand? (pinging @seanmadsen  for any doco input)

**Comment by seanmadsen** [comment]
I'd be willing to help with necessary documentation updates as required by this PR, but Eileen was right - I don't understand enough about what's going on here to help with documentation, even after reading [CRM-19657](https://issues.civicrm.org/jira/browse/CRM-19657).

**Comment by seamuslee001** [comment]
@seanmadsen the issue here was that when a recurring contribution was processed the email address that was being used if no receipt_from_email or receipt_from_name was passed in, was the logged in user which was a difference from 4.6. 

So now the system runs through a series of checks for recurring contributions to work out which from_email / name combination to use

1. It uses any passed in details
2. If there is a contributionPage linked uses the details from there if possible
3. Still if not found any, then use default from email address from the from _email address options
4. if still not found any then use the email address and name from the Domain information settings
5. If still not found any good candidates then use the name and email address of logged in user

**Comment by seanmadsen** [comment]
Thanks for the summary, @seamuslee001. Seems like a good change! 

Based on that info, my initial reaction is that no documentation updates would be required for this change. If someone else thinks we should update docs for this change, and you want my help with those updates, then I'll need a little more info about what we should be documenting here.

**Pull request merged**
