### PR TITLE
SearchKit - Support form filters for relationships

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Makes it possible to filter related contacts by relationship fields.

Ref https://lab.civicrm.org/dev/core/-/issues/3468

Before
----------------------------------------
1. Create a search for a contact and a related contact
2. Create a search form
3. You can add filter fields for each contact, but not the relationship itself

After
----------------------------------------
image

### CODE REVIEW

**Comment by kurund** [comment]
@colemanw 

Looks good on the editor and now we can select relationship fields. 

Screenshot from 2022-08-19 11-02-51

However, on search relationship fields are not displayed.
Screenshot from 2022-08-19 11-07-00

**Comment by colemanw** [comment]
@kurund - adding columns to a search display is a separate configuration and doesn't have to do with filters.

**Comment by colemanw** [comment]
@kurund I just tried again and the filter fields are showing up for me. Try clearing caches.

**Comment by kurund** [comment]
@colemanw 

Weird now it's working. Might have been caching issue or my mistake with applying the patch.

Good to merge.

**Pull request merged**
