### PR TITLE
[WIP] Move Order API CRUD to CRM_Financial_BAO_Order

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
_A brief description of the pull request. Keep technical jargon to a minimum. Hyperlink relevant discussions._

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@monishdeb so my thinking around this is that rather than move that whole part across - to move more chunks. I'm not yet convinced the signature for 'create' is what we want for v4 - I'll put up a PR to show what I was thinking we might get to

**Comment by monishdeb** [comment]
ok

**Comment by eileenmcnaughton** [comment]
@monishdeb I don't think the signature will necessarily be the same - apiv4 gives us more flexibility around the signature and I think the apiv3 signature is potentially a weakness of it. 

My thinking - which I'll comment more here - https://github.com/civicrm/civicrm-core/pull/20829 is that we want to separate the v3 order api in the bits that deal with the incoming & outgoing signature - which would stay in the v3 api and the bits that do the work - which would be moved to the BAO_Order class.

The current PR just separates out those 2 loops - it doesn't move over the entity create work - in part because I think the contribute_mode stuff needs cleanup first to make the logic separable - the blocker to that should be almost gone as I have responded to reviewer feedback over here https://github.com/civicrm/civicrm-core/pull/20670 and I think it's mergeable

**Comment by eileenmcnaughton** [comment]
@monishdeb are you ok with closing this out? I'm keen to add the v4 order api when we add the code to use it (for afform I think) and to think through the most usable signature

**Comment by monishdeb** [comment]
Sure

**Pull request closed without merging**
