### PR TITLE
dev/core#1283 fix inability to export more than 255 chars

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fixes a bug where custom fields longer than 255 chars are not completely exported

Before
----------------------------------------
FIeld truncates or crashes

After
----------------------------------------
Field exports

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
(*CiviCRM Review Template WORD-1.2*)



* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) Pass
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) Pass improves export process
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) Pass
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) Pass - replicated the hard fail and after applying the PR and clearing cache confirmed that this fixes it and confirms that the string is not truncated
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) Pass
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) Pass
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) Pass
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) Unknown

**Comment by Stoob** [comment]
thanks for looking into this and the quick fix!

**Comment by eileenmcnaughton** [comment]
@seamuslee001 nagged on your behalf :-)

**Comment by Stoob** [comment]
thanks @seamuslee001 👍

**Pull request merged**
