### PR TITLE
CRM-19778 - Api.getoptions - Filter status id by case type id

### PR DESCRIPTION
**Pull request by colemanw**
* [CRM-19778: Allowed statuses per case-type](https://issues.civicrm.org/jira/browse/CRM-19778)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@colemanw test failure looks related https://test.civicrm.org/job/CiviCRM-Core-PR/15934/testReport/junit/(root)/api_v3_CaseTest/testCaseStatusByCaseType/

**Comment by colemanw** [comment]
@seamuslee001 highly frustrating because it passes on my local. I'm going to stick in a print statement to see if I can get more useful insight to why it fails in Jenkins.

**Comment by seamuslee001** [comment]
@colemanw got a different test failure this time https://test.civicrm.org/job/CiviCRM-Core-PR/15978/testReport/junit/(root)/api_v3_CaseTest/testCaseStatusByCaseType/

**Comment by colemanw** [comment]
Hmm @seamuslee001 that looks like the same caching problem. I thought I had solved it.

**Comment by colemanw** [comment]
Screw it, I've tried everything I can think of. But the bug needs fixing, test or no.

**Pull request merged**
