### PR TITLE
CRM-18406 Added unit test for activity create/update when contributio…

### PR DESCRIPTION
**Pull request by Edzelopez**
…n is created/updated

---
- CRM-18406: When a contribution is edited it doesn't update the activity to match
  https://issues.civicrm.org/jira/browse/CRM-18406

### CODE REVIEW

**Comment by Edzelopez** [comment]
Unit test in favour of #8384

**Comment by Edzelopez** [comment]
@monishdeb Test failures related to #8384

**Comment by monishdeb** [comment]
Merged #8384 .

**Comment by monishdeb** [comment]
Jenkin test this please.

**Comment by monishdeb** [comment]
seems like there are 22 new failure as per the earlier fix, will submit new PR to fix those test failures

**Comment by monishdeb** [comment]
Jenkin retest this please

**Pull request merged**
