### PR TITLE
PCP - Add metadata for SearchKit dynamic joins

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Gets PCP joins working with SearchKit.

Before
----------------------------------------
APIv4 and SK had no way of understanding the relationship between PCPs and ContributionPages/Events.

After
----------------------------------------
Dynamic foreign key added. The DFK system is now more flexible in general to accommodate the different way it's done in this entity.

Comments
----------------------------------------
This will un-stuck @aydun's work on a PCP screen for AdminUI. To make that search display you can:
- Search for PCPs
- With Contributions
- With Events
- Add either event title or contributionPage title as a column, then use field transformations to coalesce the two into 1 column.

### CODE REVIEW

**Comment by aydun** [comment]
I think it was @kcristiano looking at PCP's

**Comment by kcristiano** [comment]
I will review as soon as I can

**Comment by kcristiano** [comment]
I also tried with a left join and that returns PCP info but nothing from the related contribution page

**Comment by colemanw** [comment]
@kcristiano thanks so much for reviewing this. Although the API-part of things were working, I had to make one more change to SearchKit to get it correctly constructing the dynamic joins. I've just pushed up a fix which I think is finally complete.

Note that the search you tested with and pasted into this PR will not work (the export contains the bad join syntax) but if you delete the join & re-add it, all should be well! Happy New Year.

**Comment by colemanw** [comment]
@kcristiano I've just rebased this again, it would be great to get it merged.

**Comment by kcristiano** [comment]
Thanks @colemanw I will do this as soon as I can.

**Comment by kcristiano** [comment]
I have done a new `r-run`  and the update code works as expected.

This looks good to merge.

**Comment by colemanw** [comment]
Thanks @kcristiano!

**Comment by colemanw** [comment]
@kcristiano is there a PR you were working on to expose PCPs to AdminUI?

**Comment by kcristiano** [comment]
@colemanw There will be, I have to finish up the links.

**Pull request merged**
