### PR TITLE
Separate loadRelatedObjects params in complete/repeattransaction

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Separate params being passed to loadRelatedObjects from params being passed through later functions.

Before
----------------------------------------
More difficult to disentangle.

After
----------------------------------------
Easier to disentangleify.

Technical Details
----------------------------------------
- `loadRelatedObjects` accepts an input array and reads `payment_processor_id` and `component` from that array. For repeat/completetransaction we are not passing component.
- `$input` is passed through to _ipn_process_transaction and completeOrder but `payment_processor_id` is never used (it's filtered out in the case of repeattransaction but not in completetransaction. But code inspection shows it's not used.

Comments
----------------------------------------
@eileenmcnaughton Further simplification.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire per dm - do we even need to loadRelatedObjects anymore - we only use ```$contribution->_relatedObjects['paymentProcessor']``` once - it's at the bottom of this snippet but I included the lines a little earlier because they relate

```
    $paymentProcessorId = '';
    if (isset($objects['paymentProcessor'])) {
      if (is_array($objects['paymentProcessor'])) {
        $paymentProcessorId = $objects['paymentProcessor']['id'];
      }
      else {
        $paymentProcessorId = $objects['paymentProcessor']->id;
      }
    }

....

    // If paymentProcessor is not set then the payment_instrument_id would not be correct.
    // not clear when or if this would occur if you encounter this please fix here & add a unit test.
    if (empty($contributionParams['payment_instrument_id']) && isset($contribution->_relatedObjects['paymentProcessor']['payment_instrument_id'])) {
      $contributionParams['payment_instrument_id'] = $contribution->_relatedObjects['paymentProcessor']['payment_instrument_id'];
    }


```

**Comment by eileenmcnaughton** [comment]
That gave me an idea - let's see what tests hit that line - https://github.com/civicrm/civicrm-core/pull/18259

**Comment by eileenmcnaughton** [comment]
Nice - the line has test cover! https://github.com/civicrm/civicrm-core/pull/18259#issuecomment-680298970 - including from the api & BaseIPN class.

**Comment by mattwire** [comment]
Superseded

**Pull request closed without merging**
