### PR TITLE
Way to alter schedule reminder email body

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
There isn't a way you can alter the email body or subject before the message is render, unless you over-ride by re-rendering in altermailparams hook. 

This PR allows to change the body by using civicrm_container() hook see eg below

```
function abc_civicrm_container($container) {
  $container->addResource(new \Symfony\Component\Config\Resource\FileResource(__FILE__));
  $container->findDefinition('dispatcher')->addMethodCall('addListener',
    array(\Civi\Token\Events::TOKEN_EVALUATE, '_abc_evaluate_tokens')
  );
}

function _abc_evaluate_tokens(\Civi\Token\Event\TokenValueEvent $e) {
  foreach ($e->getRows() as $row) {
    CRM_MembershipApproval_Utils::$_tokenActId= NULL;
    if ($row->context['actionSearchResult']->entityTable == 'civicrm_activity') {
      $actTypeId = $row->context['actionSearchResult']->activity_type_id;
      if ($actTypeId = 13) {
        $row->context->addMessage('subject', 'update subject', 'text/plain');
        $row->context->addMessage('body_text', 'text message', 'text/plain');
        $row->context->addMessage('body_html', 'html message', 'text/html');
      }
      catch (Exception $e) {
        // ignore
      }
    }
  }
}
```

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@totten can you check this - my understanding is tokenRow is part of an existing documented supported interface so we'd probably want a test to add extra functionality to it but you might like to comment on appropriateness first

**Comment by seamuslee001** [comment]
@pradpnayak just checking you can't implement your own listener and set a really high priority?

**Comment by pradpnayak** [comment]
Hi @seamuslee001 

I tried but couldn't make it work, do you have any such example for reference if you have done before?

Thanks
Pradeep

**Comment by seamuslee001** [comment]
@pradpnayak is it not possible in the token render vent to do something like the following?

```php
$tokenProcessor = $e->getTokenProcessor();
$tokenProcessor->addMessage('body_html', 'xxx', 'text/html');
```

**Comment by pradpnayak** [comment]
Thanks @seamuslee001 will try.

**Pull request closed without merging**
