### PR TITLE
Add Api4 Membership entity

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Add Membership to API4

Before
----------------------------------------
Not there

After
----------------------------------------
There

Technical Details
----------------------------------------

Comments
----------------------------------------
@eileenmcnaughton @colemanw

### CODE REVIEW

**Comment by colemanw** [comment]
retest this please

**Comment by eileenmcnaughton** [comment]
@mattwire I think when we create the Membership.create action for v4 we should 'get it right' WRT line items. I'm inclined to think we should pass in skipLineItem and set the expectation that other api functions are used to create line items.

However, I'm not sure I understand it all well enough yet to be 100% sure .... The problem arises if it's possible for memberships to have a specified number of terms and be pending with no attached contribution. If so the only place the number of terms is stored is the line items.... I'm trying to find the ticket I logged but my digging so far suggests there is nasty mess around line items with memberships

https://github.com/civicrm/civicrm-core/blob/e0dba5848ef5016b4d3e952bc71ea7d58db0dc59/CRM/Member/BAO/Membership.php#L325

**Comment by mattwire** [comment]
@colemanw Could we add the "get" for now and disable create until we're sure we know how it should work?
@KarinG See comments from @eileenmcnaughton above. I think this may tie in with your auto-renew issues?

**Comment by KarinG** [comment]
Thanks @mattwire - The additional +1 term of Membership as a results of a new contribution in a recurring contribution series - even though:

Membership type being configured as No auto-renew option
`civicrm_membership.contribution_recur_id` = NULL
`civicrm_contribution_recur.auto_renew`= 0

Is a separate issue I think. I'm closing in on proposing a solution for that.

**Comment by eileenmcnaughton** [comment]
I've been thinking about this & I think we might need a 'dont_do_nasty_shit_with_line_items' param in the BAO that defaults to TRUE for apiv4...

**Pull request closed without merging**
