### PR TITLE
Use api to create activity and removed hardcoded status id

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
Use api to create activity and removed hardcoded status id

Before
----------------------------------------
Status Id was hardcoded to 2

After
----------------------------------------
Replaced hardcoded value with name and used api to create activity

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This seems straight forward, sensible, and inline with our general approach.

Do we have any tests that cover this createActivityExport function or more generally the CRM/Financial/BAO/ExportFormat class @pradpnayak

**Comment by pradpnayak** [comment]
I am afraid to say there isn't any unit test, I guess we had written webtest when it was implemented in 2014.

**Comment by eileenmcnaughton** [comment]
@pradpnayak any chance you could add 'something' with this change - I'd settle for 'anything that takes us forwards on test cover in this area - even if it just shows the function being called without a fatal

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by pradpnayak** [comment]
@eileenmcnaughton yes i will, can you please help me if we have test related to export? I can come up with a unit test if i get a starting point.

**Comment by eileenmcnaughton** [comment]
@pradpnayak I would add something to  CRM_Batch_BAO_BatchTest that calls

   CRM_Batch_BAO_Batch::exportFinancialBatch($batchIds, $this->_exportFormat, $this->_downloadFile);

I feel like if you can just get to the point of calling the function with no errors that is enough to have extended our cover. - the CRM_Utils_System::civiExit(); function now throws an exception although per https://github.com/civicrm/civicrm-core/pull/14608 I'm still struggling to quite figure out how to do the testing using it (will have another dig on that one now)

**Comment by eileenmcnaughton** [comment]
test this please

**Pull request merged**
