### PR TITLE
CRM-20549 no limit on event permission check api call

### PR DESCRIPTION
**Pull request by lcdservices**
* [CRM-20549: manage events does not list all events](https://issues.civicrm.org/jira/browse/CRM-20549)

### CODE REVIEW

**Comment by mfb** [comment]
You should also add  `'options' => array('limit' => 0),` up above in getLocationEvents so it's possible to list locations for more than 25 events.

**Comment by lcdservices** [comment]
agreed and done.

**Comment by seanmadsen** [comment]
Reviewing this now

**Review by JoeMurray — COMMENTED** [review]
Code looks okay. @monishdeb please test on cfis site and merge if it works.

**Comment by seamuslee001** [comment]
This makes sense to me

**Comment by eileenmcnaughton** [comment]
I'm merging this as I know it was tested by @mfb already - & discussed on MM

**Pull request merged**
