### PR TITLE
CRM-19692: Fix js error on Submit Credit Card Contribution form

### PR DESCRIPTION
**Pull request by jitendrapurohit**
* [CRM-19692: Cannot select Priceset in Backend: Contributions: Submit Credit Card Contribution](https://issues.civicrm.org/jira/browse/CRM-19692)

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
jenkin, retest this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@KarinG over to you to test this & confirm

**Comment by KarinG** [comment]
Will do - with new RC tomorrow.

**Comment by KarinG** [comment]
Ok - I copied Jitendra's edits into today's RC and can now see the pricesets. Some CSS to make we can save for later. It's rather important we bring this back. 

lineitems

**Comment by seamuslee001** [comment]
Agree with the testing from @KarinG replicated the same issue and works with fix on my 4.7.14-rc dev spot

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
So this is a consensus to merge?

**Comment by seamuslee001** [comment]
That would be my impression @eileenmcnaughton

**Comment by KarinG** [comment]
Double checked this w/ civicrm-4.7.14-drupal-20161202.tar.gz	02-Dec-2016 16:42 	17M	 - all good

**Pull request merged**
