### PR TITLE
No longer install the Contribution Cancel Actions, CiviCRM Core Extension by default on new CiviCRM sites

### PR DESCRIPTION
**Pull request by agileware-justin**
Overview
----------------------------------------
No longer install the Contribution Cancel Actions, CiviCRM Core Extension by default on new CiviCRM sites.
See https://lab.civicrm.org/dev/core/-/issues/2517

Before
----------------------------------------
Contribution Cancel Actions, extension installed by default on new CiviCRM sites.

After
----------------------------------------
Contribution Cancel Actions, extension NOT installed by default on new CiviCRM sites.

Technical Details
----------------------------------------

Comments
----------------------------------------

Because @eileenmcnaughton said:
> I think the next step in deprecating the extension is to remove it from the sql that installs in on new CiviCRM installs. I would merge a PR that did that if I saw one

Agileware Ref: CIVICRM-1851

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
thanks @agileware-justin - speedy!

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I guess we can ditch these tests now - I think there are some within the extension too

**Comment by seamuslee001** [comment]
so we have lost the result and this now has conflicts but I would say we should pull the tests out of CRM/ and api_v3_x classes but lets leave the extension UTs there and let them run (which would enable the extension when the UT is run) that way we can check if anything in core change how the extension behaves if it is enabled

**Comment by colemanw** [comment]
@agileware-justin did you see the above comments?

**Comment by agileware-justin** [comment]
> did you see the above comments?

Yes @colemanw I did. Needs a bit more instruction to make sense of it.

**Comment by colemanw** [comment]
@agileware-justin first step would be a rebase. Could you refresh this PR so that tests can run again, and then we'll look at fixing whatever tests get miffed.

**Comment by agileware-justin** [comment]
@demeritcowboy please read https://lab.civicrm.org/dev/core/-/issues/2517

Regardless of whether it is this PR or not, this problem in CiviCRM needs to be fixed. Where is the next PR to keep this moving along?

**Comment by eileenmcnaughton** [comment]
@agileware-justin I'm happy to merge this PR or a different PR if the tests are passing with it

**Comment by agileware-justin** [comment]
@eileenmcnaughton go for it.

**Comment by colemanw** [comment]
@agileware-justin the reason this PR hasn't gotten any review attention is because it's still in need of a rebase, per my comment from November. The next step would be to look at what tests fail, and then based on Eileen's September comment it looks like some tests may no longer be relevant and can be removed.

**Comment by agileware-justin** [comment]
@colemanw I've done the rebase but this PR is closed, is not reflecting the change.

**Comment by eileenmcnaughton** [comment]
@agileware-justin just open a new PR from your branch - - or - if you still need to regenerate the sql it might be easier to create a new branch

**Comment by agileware-justin** [comment]
Is there an immutable bit set on this PR? It can't be re-opened?

**Comment by colemanw** [comment]
Correct, GitHub won't allow you to re-open a PR after force-pushing or recreating a branch. But you can open a new one just like this: https://github.com/civicrm/civicrm-core/compare/master...agileware:CIVICRM-1851?expand=1

**Comment by agileware-justin** [comment]
RIght, understood.

So the standard advise "Going to close but feel free to reopen" should actually be something like: "Going to close this PR. Please submit a **new PR** to **restart** the process"

**Comment by demeritcowboy** [comment]
Noted, although it seems some PRs can be, even after force-push etc (e.g. https://github.com/civicrm/civicrm-core/pull/21068). Maybe there's just a plugin running here that prevents it for Justins (grin).

I'll adjust my wording for future.

**Comment by mattwire** [comment]
@demeritcowboy It's a permissions thing I think - I can't reopen it either so I think it's only the person who closed it that can :-(

**Comment by mattwire** [comment]
I'd note that I prefer re-opening PRs that starting a new one when the author responds (as @agileware-justin has done here) because it keeps the history etc. much cleaner if you ever need to go back and search

**Comment by mattwire** [comment]
Linking the new PR here https://github.com/civicrm/civicrm-core/pull/22686

**Comment by demeritcowboy** [comment]
Ah maybe that's it.

**Comment by colemanw** [comment]
I have permissions to open PRs, but once it had been force-pushed, the button was disabled and tooltip said "Branch has been force-pushed or recreated"
I don't think there's anything wrong with @demeritcowboy's wording. PRs *can* be reopened, you just have to do so before rebasing the branch.

**Comment by agileware-justin** [comment]
> PRs can be reopened, you just have to do so before rebasing the branch.

I checked another PR that was closed by someone else. There is **no button** to **Reopen pull request**.

Looks like if the author closes the PR, they can reopen. But not it is closed by someone else.

**Comment by eileenmcnaughton** [comment]
The advantage of opening new PRs is they wind up  on the front page and appear as 'current'.  Once PRs are off the first 1-2 pages I would rarely look at them (I used to pro-actively do so, like @demeritcowboy has done here) but I manage my prioritisation a bit differently now because  it got too hard

**Pull request closed without merging**
