### PR TITLE
[REF] DAO - Add helper function to check if component is enabled

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds a helper function to make it easier to check if a DAO or BAO file belongs to a disabled component.

Before
----------------------------------------
A couple add-hoc functions in CiviCase & CiviCampaign

After
----------------------------------------
Deprecated those in favor of central function that works for every BAO & DAO.

Technical Details
----------------------------------------
Yay for late-static binding.

Comments
--------------
This is covered by APIv4 tests.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
This looks and runs ok. There's a small handful of extensions that use isCampaignEnable.

**Comment by colemanw** [comment]
@demeritcowboy this deprecation won't break those extensions

**Comment by demeritcowboy** [comment]
It's more just asking for second set of eyes.

**Comment by colemanw** [comment]
Thank your

**Pull request merged**
