### PR TITLE
dev/core#2833 Fix Contact Type change on Backend Membership Credit Ca…

### PR DESCRIPTION
**Pull request by sunilpawar**
Overview
----------------------------------------

**Individual** Contact get changed to **Organization**

Reproduction steps
----------------------------------------
1. Individual Contact must have an Existing Membership Record (may be with **Expired** Status) 
1. Choose Renew with Credit card action
1. select **Record Payment from a Different Contact?** checkbox and choose Organisation Contact for field **Payment From**
1. Keep Billing Name and Address of Individual Contact (Used Dummy Processor for testing).

Now, click on 'Renew' Button.

Individual Contact 'Contact Type' get changed from **Individual** to **Organization**

Same issue with  **Submit Credit Card Membership** functionality.

Current behaviour
----------------------------------------
Contact Type Changes from **Individual** to **Organization**

Expected behaviour
----------------------------------------
Contact type should not change.

Environment information
----------------------------------------
Able to re-create issue on https://dmaster.demo.civicrm.org (5.43.alpha1)
Same issue exist on 5.21 version also. So its not a new issue.

### CODE REVIEW

**Comment by seamuslee001** [comment]
Test fails relate

```
CRM_Member_Form_MembershipTest.testFinancialEntriesOnCancelledContribution
CRM_Member_Form_MembershipTest.testTwoInheritedMembershipsViaPriceSetInBackend
CRM_Member_Form_MembershipTest.testTwoMembershipsViaPriceSetInBackendWithDiscount
```

**Comment by sunilpawar** [comment]
> Test fails relate
> 
> ```
> CRM_Member_Form_MembershipTest.testFinancialEntriesOnCancelledContribution
> CRM_Member_Form_MembershipTest.testTwoInheritedMembershipsViaPriceSetInBackend
> CRM_Member_Form_MembershipTest.testTwoMembershipsViaPriceSetInBackendWithDiscount
> ```

working on it.

**Comment by sunilpawar** [comment]
@seamuslee001 i have fixed test cases..

**Comment by jaapjansma** [comment]
test this please

**Pull request merged**
