### PR TITLE
 Notice if no prev. mailing reports exist in a system

### PR DESCRIPTION
**Pull request by yurg**
https://civicrm.stackexchange.com/questions/20943/blank-page-in-mailings-with-notice/

Overview
----------------------------------------
_A brief description of the pull request. Try to keep it non-technical._

Before
----------------------------------------
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

After
----------------------------------------
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

Technical Details
----------------------------------------
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
jenkins, add to whitelist

**Comment by eileenmcnaughton** [comment]
I've set our CI-bot going - but I think it's going to declare some style issues as I think your whitespace is not in line with our coding standards (we use 2 spaces per drupal coding standards) 

There are some links on this page
https://docs.civicrm.org/dev/en/latest/core/contributing/

**Comment by yurg** [comment]
Sorry, have made it really quick; will redo according to coding standards.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
that definitely looks like a solid enotice fix - merging

**Pull request merged**
