### PR TITLE
dev/membership#29 Add civicrm_line_item.membership_num_terms

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This adds the field membership_num_terms to the civicrm_line_item table

No logic is in this PR but the intent is to use this to address a long-standing bug on the membership renewal form and simplify logic elsewhere.

When renewing a membership using the back office form it's possible to specify the number of terms (if not using a price set). However, when the payment comes in the number of terms specified on the form is not saved. If it's all happening within one form submission this can be held in memory but for delayed payments it is simply gone.

Note that this field will not be reliably populated until we have done a lot of cleanup & switching to order->payment flow. However, the payment creation code will continue to assume '1' for membership lines if it is NULL. We can't assume existing lines are only for 1 term so NULL better represents what is known.

Before
----------------------------------------
Nowhere to store the intended number of membership terms for a line item

After
----------------------------------------
Can be stored in civicrm_line_item.membership_num_terms

Technical Details
----------------------------------------
The discussion in gitlab is hard to read as the proposal changed over time https://lab.civicrm.org/dev/membership/-/issues/29 - landing on the simplest variant to solve this issue.

A number of options were discussed including 
- a metadata field for more open ended storage 
- putting data on the membership_payment table instead of the line item table
- a complicated status based approach
- using the qty field as being the number of terms being purchased

Some notes to the above
1) There was pushback against a serialised field because people would like to report on the value once it's actually reliable. Also, I was concerned a serialised field might be a maintenance headache if extensions used it instead of custom data fields. In addition @herbdool made the point that the payment completion metadata I had in mind (effective date & message text can be entered on the back office form) more accurately belong at the contribution level.

2) We are almost at the point where we can fully deprecate the membership payment table (as a duplication of the line item table) so I'm opposed to adding to it. In addition the membership_num_terms is a field on the price_field_value table which line item mirrors

3) the status based approach was based on trying to solve a wider scope of issues but it turned out that this needs to be narrow in scope to get this part sorted

4) I was strongly in favour of the qty field being logically the number of terms purchased - However, @jamie-tillman made a point about rounding issues 

"he line item shows a qty of 1 even though I purchased 3 terms.  So that is still sort of a "package deal" like I was discussing.  A qty of 3 would require the item price to be $6.67 and would never total out properly.  As it stands, I've bought "1" of "something"." 

The change to utilise this would wind up similar to https://github.com/civicrm/civicrm-core/pull/18582/files#diff-4c9d0b1abe07057a4eea2b47bc627eecb95face8ed8d86c1c005312a52cca811L432

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Noting that I wrote about this in the dev-digest 2 days ago

**Comment by monishdeb** [comment]
Looks good. @eileenmcnaughton can you please remove the hash code change in CRM/Contribute/DAO/ContributionProduct.php and squash the commits to one?

**Comment by herbdool** [comment]
This looks good to me too. Thanks @eileenmcnaughton!

**Comment by eileenmcnaughton** [comment]
Thanks @herbdool , @monishdeb

@monishdeb the extraneous line magically disappeared when I rebased :-) Now squashed

**Comment by monishdeb** [comment]
Final patch looks good now. Based on @herbdool and my review I am merging this PR.

**Pull request merged**
