### PR TITLE
Move determination of year & month to formatCreditCardDetails

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Minor code re-org Per https://github.com/civicrm/civicrm-core/pull/16514 it makes sense as a better place for these

Before
----------------------------------------
allocation of  year & month are in a code chunk that concerns itself with assignments

After
----------------------------------------
allocation of  year & month are in a code chunk that concerns itself with building params

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this  please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
This looks fine to me I think @mattwire ?

**Pull request merged**
