### PR TITLE
[wip] Remove bad smell handling of addFinancialItem

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This is bad. If we have to set this here like this we are doing something wrong

Not really expecting this to pass - just looking to tests to highlight how this is / isn't working
Before
----------------------------------------
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

After
----------------------------------------
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

Technical Details
----------------------------------------
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by monishdeb** [comment]
Hmm agree, back then that changeFee functions turned out be a nightmare for me to handle all scenario. So added that tag for special handling of Text price field kind. But I agree with you it could better be handled in a generic way. Perhaps presence of id here might not be the fix as its breaking two UTs. But let me look at it again what we can do to fix it.

**Comment by eileenmcnaughton** [comment]
@monishdeb I think I see the reason for those tests - just pushed a change - I'll still close this out when you've had time to ponder it though :-)

**Comment by monishdeb** [comment]
Hmm that commit remind me of https://github.com/civicrm/civicrm-core/pull/13521/files#diff-e57ed384488b5985e5a0a5c166a6b0f0R772   

I will now test this patch on diff. change fee scenario.

**Comment by eileenmcnaughton** [comment]
@monishdeb this is now passing (with one known failure). I'll close this now (we can re-open if we think we should merge it as is)

**Pull request closed without merging**
