### PR TITLE
CRM-18594 Attempt to add test to check aphabetical event type

### PR DESCRIPTION
**Pull request by seamuslee001**
- [CRM-18594: Creating event templates throws an 'Invalid Entity Filter' exception](https://issues.civicrm.org/jira/browse/CRM-18594)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton @mollux I believe this verifies the error on the alphabetical extending eventType

**Comment by eileenmcnaughton** [comment]
@seamuslee001 what is the status here? Still required / needing fixing?

**Comment by jitendrapurohit** [comment]
test this please

**Comment by colemanw** [comment]
@civicrm-builder test this please

**Comment by colemanw** [comment]
@seamuslee001 can you give an update on what needs doing with this?

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
If it passes, merge it, if it fails close it.

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by monishdeb** [comment]
@seamuslee001 there are 3 related unit test failures https://test.civicrm.org/job/CiviCRM-Core-PR/12155/ . Can you fix those ?

**Pull request merged**
