### PR TITLE
(dev/core#1104) make admin panels hookable

### PR DESCRIPTION
**Pull request by yashodha**
Overview
----------------------------------------
Make it easy to show/hide items on administer screen.

Before
----------------------------------------
not easy to hide elements from admin screen

After
----------------------------------------
can be done using the hook.

### CODE REVIEW

**Comment by mattwire** [comment]
@yashodha I'm not clear what this allows you to do?  Could you provide a screenshot or update description?

**Comment by eileenmcnaughton** [comment]
Documentation issue (& jenkins approval aside) I'm comfortable with adding this hook after seeing the patch - it's not being added in the middle of a complex function but rather at the end as a final change to 'tinker' so it's not locking us into maintaining toxic code around it. It also feels very similar to some or our other patterns around editing available blocks on a page.

So in principle I think this makes sense - once docs & jenkins are addressed

I'm also relaxed about this not having a test as it is very 'close to the surface'

**Comment by yashodha** [comment]
@mattwire 
some admins might not want some roles to see all the overwhelming settings on the admin page. The hook just makes it easy
Before
before

After
after

**Comment by yashodha** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@yashodha will you also do a PR to add to the docs repo?

**Comment by yashodha** [comment]
@eileenmcnaughton sure, I am going to add documentation as well.

**Comment by mattwire** [comment]
@yashodha Looking at the code it looks like that admin page is retrieving links from the admin menu but bypassing permission checks?  Would it be better to change the way the menu links are retrieved so that only the ones which a role has permission for are displayed?

**Comment by eileenmcnaughton** [comment]
I think this hook is OK- it seems like the sort of place in the code where we have a clear expectation of what the hook will do - ie it will just alter an array & once @yashodha documents it the implications of that array will be clear & documented.

Where I think new hooks are bad is when they are added into toxic code & the hook implementer could tweak any one of a number of things with the expectation the core code won't change in a way that will break their hook. 

@yashodha I'm merging this because you said you WOULD document it - I'll leave it to you to make good on that

**Comment by eileenmcnaughton** [comment]
I added this for it https://github.com/civicrm/civicrm-dev-docs/issues/656

**Comment by yashodha** [comment]
@eileenmcnaughton Thanks for closing this! Here is the doc link as promised https://github.com/civicrm/civicrm-dev-docs/pull/657

**Comment by eileenmcnaughton** [comment]
thanks @yashodha

**Comment by MikeyMJCO** [comment]
I'm closing the docs PR linked to this as it's stalled awaiting fixes. This remains needs-documentation.

**Pull request merged**
