### PR TITLE
Added api UFJoin::delete

### PR DESCRIPTION
**Pull request by TobiasLounsbury**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This can be merged once tests complete (assuming they pass :-)

**Comment by eileenmcnaughton** [comment]
As an aside - I expect some tests are commented out for this entity in syntax conformance that could be uncommented now

**Comment by seamuslee001** [comment]
Should there be any changes made to API permissions due to this change?

**Comment by totten** [comment]
The permissions are currently declared as https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/DAO/permissions.php#L498 . It appears that UFJoin imitates UFGroup, which isn't explicitly declared -- it should default to requiring `administer CiviCRM`. I'm down with that.

For some of the other actions of UFGroup/UFJoin, they also accept 'manage event profiles' permission. Don't know why UFGroup.delete was left out... could be a valid reason. But generally seems OK to say that UFJoin.delete uses the same permissions as UFGroup.delete.

**Pull request merged**
