### PR TITLE
AllCoreTables - Generate file every time

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----
This autogenerated file was not being updated as often as necessary, and the freshness checks were almost as expensive as just generating the file, if not more.

Before
-----
File generated only when needed, but the checks to see if it was needed involved generating the file plus some additional work. They also did not always work, according to recent experience with https://github.com/civicrm/civicrm-core/pull/11739.

After
-----
File generated every time. This should not affect git because the new file will usually be identical.

### CODE REVIEW

**Comment by colemanw** [comment]
FYI @totten 
@monishdeb this is in response to your comment https://github.com/civicrm/civicrm-core/pull/11739#issuecomment-370028966

**Comment by seamuslee001** [comment]
test failure looks related

**Comment by monishdeb** [comment]
@colemanw it seems like you also need to change the assert check in `CRM_Core_CodeGen_FreshnessTest.testReflection`

**Comment by monishdeb** [comment]
@totten I have created https://lab.civicrm.org/dev/drupal/issues/12 in this regard, i.e. to create/update `AllCoreTables.php` without using CodeGen.

**Comment by totten** [comment]
A few observations:

* @coleman, the main expense in generating PHP code actually isn't processing Smarty or preparing the source-material -- it's in beautifying/post-processing the PHP code. IIRC, the old mechanism avoided the cost of beautification.
* @monishdeb, I think the D8/composer-style installation is still OK as long as `AllCoreTables` is committed to git. However, we might not get any warning-signs when the committed code is out-of-date. (Unfortunately, the current freshness test doesn't actually work very well. Why? Because the test-scripts run `GenCode` as part of setup... obscuring any problems in freshness...)

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by monishdeb** [comment]
@colemanw I have fixed the test failure with this change - https://github.com/civicrm/civicrm-core/pull/11755/commits/acc660f44b78da2f9e563c77778bf47c19d19e97 about skipping Codegen task that rewrites tables in AllCoreTables.data.php on test environment, thus passes the failing UT ```CRM_Core_CodeGen_FreshnessTest.testReflection```

**Comment by colemanw** [comment]
Thanks @monishdeb. I think this has received sufficient review and is good to merge now that tests are passing.

**Comment by monishdeb** [comment]
Thanks @colemanw for merging it :)

( That needs me to rebase https://github.com/civicrm/civicrm-core/pull/11739 now )

**Pull request merged**
