### PR TITLE
Remove `_subName` property

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Remove `_subName` property

Before
----------------------------------------
subName only accessed from this function & the places being removed in https://github.com/civicrm/civicrm-core/pull/26844/files#diff-1a220e071c24dde6c43cc3e60d31805da72604d8774dbb7c26d6111a324c9cb4L37

image

After
----------------------------------------
Internal variables ued

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by demeritcowboy** [comment]
`$form->_subName` is still used in setGroupTree in this file. It isn't replaced by the commit referenced in the PR description.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy that function is no longer called - I added a deprecation notice to it to give gdpr a chance to stop using it

**Comment by demeritcowboy** [comment]
Ok, just since that deprecation was just added, that doesn't give them the usual time, because it's broken in the same version the deprecation was added. But yes they could copy the function as a quick fix, so I don't want to hold this up.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy since the value is being retrieved from the url in all cases it should still work when calling the deprecated function I think

**Comment by demeritcowboy** [comment]
But it's still being accessed here without anything setting it: https://github.com/civicrm/civicrm-core/blob/dc5f6e2b853db99d3682de0584df75c4c8d6501a/CRM/Custom/Form/CustomData.php#L241

But for gdpr, ok I see two places, and _they_ set it [here](https://github.com/veda-consulting-company/uk.co.vedaconsulting.gdpr/blob/377dcdf2648db2bb5d408a5482ecc29e7571a3be/CRM/Gdpr/Form/ManageEvent/TermsAndConditions.php#L24) and [here](https://github.com/veda-consulting-company/uk.co.vedaconsulting.gdpr/blob/377dcdf2648db2bb5d408a5482ecc29e7571a3be/CRM/Gdpr/Form/ContributionPage/TermsAndConditions.php#L22).

So ok.

**Pull request merged**
