### PR TITLE
CRM-19179: Set primary location during manual merge

### PR DESCRIPTION
**Pull request by JKingsnorth**
- [CRM-19179: Handle 'primary' contact information when manually merging contacts](https://issues.civicrm.org/jira/browse/CRM-19179)

### CODE REVIEW

**Comment by JKingsnorth** [comment]
todo:
* write some tests

**Comment by JKingsnorth** [comment]
@eileenmcnaughton @colemanw I'd like to make this testable but I wasn't sure how to get started wih a unit test (i'd rather not make a web test). Effectively it would be making the 'mergeLocations' function testable. Is the best way just to generate specific location blocks and then 'handwrite' the arrays of data to go into the 'mergeLocations' function and then check the outcome for the location entities and returned data?

**Comment by eileenmcnaughton** [comment]
Hey John - just wanted to note I am aware of this & hope next week I can look at the test issue

**Comment by JKingsnorth** [comment]
@eileenmcnaughton That's great, thanks Eileen. I hope I'll be able to do it but I could use a few pointers.

**Comment by JKingsnorth** [comment]
@colemanw @eileenmcnaughton Just wondering if you'd had a chance to take a look at this one? There was quite a bit of work in refactoring the JS, so I'd like to get this finished off before the PR goes stale.

We've been using this in production for a while now and had no reported issues. But it would be good to get some unit tests on it if possible.

**Comment by colemanw** [comment]
Code looks good to me. Need to find someone to test the functionality.

**Comment by eileenmcnaughton** [comment]
@JKingsnorth hopefully I'll try this at the London sprint

**Comment by JKingsnorth** [comment]
Ah great, thanks very much to you both.

I guess I'll see you at the conference Eileen. Unfortunately not able to make the sprint this year.

**Comment by eileenmcnaughton** [comment]
I'm going to merge this. I tested & it looks good to me - the right address choices were made with regards to type & primary, and, as John says it is in production already.

I still want us to do the tests, but I don't think we need to hold this up on that

**Pull request merged**
