### PR TITLE
dev/core#3084 Bug fix on line item financial types

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------

https://lab.civicrm.org/dev/core/-/issues/3084

I expect some fixes to v3 order api might be needed to get tests to pass

Before
----------------------------------------
per steps on https://lab.civicrm.org/dev/core/-/issues/3084

After
----------------------------------------

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@davejenx this should fix the regression you reported. It caused a test to fail but that test ALSO related to one of your issues - https://lab.civicrm.org/dev/core/-/issues/860 - I concluded the error was in the test & have updated the test to be more internally consistent....

**Comment by davejenx** [comment]
Fantastic, thanks @eileenmcnaughton ! This does indeed fix the regression. Apologies if one of my tests caused complications.

**Comment by demeritcowboy** [comment]
I'm confused about how much the goat costs - it looks like $15 for the goat and then $200 in taxes - I hope you at least get good road maintenance out of that. (grin)

Seriously, I don't have a good sense of how this will affect calls to Order api. But it sounds correct. https://github.com/civicrm/civicrm-core/blob/e5e212b5aceb17ec4a2ed901ecc4cf59b27d64da/CRM/Financial/BAO/Order.php#L419-L423

**Comment by eileenmcnaughton** [comment]
I think it's a bit of a tax rort - you make a tax free donation AND buy a VERY CHEAP GOAT at the same time....

**Comment by demeritcowboy** [comment]
Hehe.
By the way if I search for "How much does a goat cost?", which has probably put me on all kinds of surveillance watchlists now, there's a surprising range of results, including things like a $3000 Billy Goat Debris Loader, which I both want to know more about and at the same time am scared to find out.

**Comment by eileenmcnaughton** [comment]
maaa-aaaa

**Comment by demeritcowboy** [comment]
> maaa-aaaa

Agreed.

**Pull request merged**
