### PR TITLE
CRM-21426: Removed duplicate submit buttons on Cancel/Delete Event Participants

### PR DESCRIPTION
**Pull request by ghost**
# Overview
This PR solves an inconsistency with other confirmation pages which only have one set of buttons instead of two. It removes the buttons at the top of the Cancel Event Participants and Delete Event Participants pages and also changes the title of the submit button from "Continue" to "Cancel Registrations" on the Cancel Event Participants page.

### Steps to get to the page:
1. Go to CiviCRM > Events > Find Participants > Search
2. Select a few records
3. From Actions, choose Cancel registration
4. Repeat the above and from Actions choose Delete registration

# Screenshots
### Before:
before

### After:
after3

# Technical Details

- This PR alters the `templates/CRM/Event/Form/Task/Cancel.tpl` file to remove the HTML for the buttons at the top of the form.

- It also alters the `CRM/Event/Form/Task/Cancel.tpl` file to change the title of the submit button.

# Comments
Please review and merge to the master branch.

---

 * [CRM-21426: Cancel Event Participants - Duplicate Submit Buttons](https://issues.civicrm.org/jira/browse/CRM-21426)

### CODE REVIEW

**Comment by mlutfy** [comment]
@mihaelmladenov Thanks for the patch. Can you open a JIRA issue on https://issues.civicrm.org? This is necessary so that the change gets correctly logged in the Release Notes. c.f. https://docs.civicrm.org/dev/en/latest/core/contributing/

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by mihaelmladenov** [comment]
Hi Mathieu,

I just registered at the site and am pending approval. My e-mail is
mihaelmladenov1986@gmail.com. Can you approve it and I will create the JIRA
issue after that. Thanks!

Best regards,
Mihael

**Comment by mlutfy** [comment]
@mihaelmladenov done!

**Comment by mihaelmladenov** [comment]
@mlutfy Thanks. I've created one:
https://issues.civicrm.org/jira/browse/CRM-21426

**Comment by mlutfy** [comment]
I tested this patch (on http://core-11277-19jsu.test-ubu1204-5.civicrm.org).

@mihaelmladenov Could you also fix the "Delete Participants" action?

capture d ecran de 2017-11-14 13-39-20

capture d ecran de 2017-11-14 13-39-32

capture d ecran de 2017-11-14 13-39-59

capture d ecran de 2017-11-14 13-40-14

**Comment by mihaelmladenov** [comment]
@mlutfy This is now done and pushed.

**Comment by seamuslee001** [comment]
Jenkins ok to test

**Comment by mlutfy** [comment]
@mihaelmladenov  That's a good improvement too, but I was talking about the "Delete Participants" action, it still has the top buttons as well:

capture d ecran de 2017-11-14 13-39-20

Otherwise we're creating an inconsistency, by having Cancel and Delete behave differently.

**Comment by mihaelmladenov** [comment]
@mlutfy This is now also fixed.

**Pull request merged**
