### PR TITLE
SearchKit - Filter search listing by creator

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds a search input to filter by name of author or editor on main SearchKit screen.

image

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
thanks @colemanw - I'm wondering if 'modified_id' would be better if we are using one of the existing fields - it would at least allow someone to 'take ownership'

Or should I just put up a PR to add owner id to the schema & we can expose to people to alter as they wish

@seamuslee001 any opinion?

**Comment by seamuslee001** [comment]
I feel like we should probably have both fields as searchable, I note at the moment on say the Managed Groups screen there is only a sort on its creator field it seems.

**Comment by eileenmcnaughton** [comment]
I think @colemanw is worried about real estate?

**Comment by colemanw** [comment]
Well if I somehow figure out a way to add OR support in filters then it could be "Filter by author..." which could search both fields at once.

**Comment by colemanw** [comment]
@eileenmcnaughton I added the support for OR in filters, so now it filters on both in a single field.

**Comment by eileenmcnaughton** [comment]
@colemanw that's great. How broadly does the OR work? In terms of performance OR is fine if you are querying 2 fields in the same table and server-breakingly-bad if they are in different tables (unless you use a UNION like we do in quicksearch)

**Comment by colemanw** [comment]
It's agnostic about performance (allows any combination of fields), but not yet exposed to the Afform Admin UI so not a visible feature yet.

**Comment by eileenmcnaughton** [comment]
@colemanw yeah that makes sense. It would be REALLY useful as a same-table filter.

**Comment by colemanw** [comment]
@eileenmcnaughton was that a MOP endorsement?

**Comment by eileenmcnaughton** [comment]
Hmm - I was gonna test on the test site - but something is awol

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
This works well - I added a screenshot at the top

**Pull request merged**
