### PR TITLE
SearchKit - Support fields in apiBatch task

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Allows api batch tasks to include fields for the user to interact with.

Technical Details
----------------------------------------
Try the following task as a test & use it in a search for Individuals:

```php
    $tasks['Individual']['rename'] = [
      'title' => E::ts('Rename Person'),
      'icon' => 'fa-random',
      'apiBatch' => [
        'action' => 'update',
        'fields' => [
          ['name' => 'first_name', 'required' => TRUE],
          ['name' => 'last_name', 'default_value' => 'Hello'],
        ],
        'confirmMsg' => E::ts('Rename %1 %2'),
        'runMsg' => E::ts('Renaming %1 %2...'),
        'successMsg' => E::ts('Successfully renamed %1 %2.'),
        'errorMsg' => E::ts('An error occurred while attempting to enable %1 %2.'),
      ],
    ];
```

### CODE REVIEW

**Comment by aydun** [comment]
Thanks! Mostly does exactly what I want. One problem: clearing values does not work.
Eg: with a text field, leaving it blank results in an error, or a field with a select list of values, selecting 'None' results in an error.

By contrast, using the existing 'Update' action correctly handles both of those cases.

**Comment by colemanw** [comment]
@aydun I'm assuming you already set required to false for those fields?

**Comment by aydun** [comment]
Yes, required is not set on those fields.

If it is required then for the text box update, the button is greyed out until text is entered - ie works as expected.

**Comment by colemanw** [comment]
@aydun ok I've pushed up another commit to ensure values are initialized if they don't have a `default_value`, which seems to fix the problem you described.

**Comment by aydun** [comment]
Thanks @colemanw - that fixes it.

**Comment by aydun** [comment]
FYI - https://lab.civicrm.org/documentation/docs/dev/-/merge_requests/1204 https://lab.civicrm.org/documentation/docs/dev/-/merge_requests/1203

**Pull request merged**
