### PR TITLE
CRM-18338: Fix test CRM_Dedupe_MergerTest

### PR DESCRIPTION
**Pull request by monishdeb**
- [CRM-18338: Fix test CRM_Dedupe_MergerTest](https://issues.civicrm.org/jira/browse/CRM-18338)

### CODE REVIEW

**Comment by JKingsnorth** [comment]
Does not pass manual merge test.

**Comment by monishdeb** [comment]
As per our discussion on the ticket, should I close this PR ?

**Comment by JKingsnorth** [comment]
Yup, probably best, I'll try and put something together. But there are some
more serious bugs on my list before I get to this. Thanks though Monish.

**Comment by monishdeb** [comment]
Welcome :)  I think you would need the test fix in this PR

**Pull request closed without merging**
