### PR TITLE
dev/core#2763 cache clearing fix

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fatal error on installing extensions - conditions apply

Before
----------------------------------------
Fatal error when running `civibuild create wmff` (this ships with buildkit)

After
----------------------------------------
works

Technical Details
----------------------------------------
This is a load order thing.

What I'm seeing is that when enabling extensions there is an extension in the mix which calls api v4 to get the default for a setting. This triggers a caching process for the v4 info - seemingly before the DAO is available -presumably settings are loaded before the entityTypes hook is called. This results in the info for v4 api entity being stored in `Civi::cache('metadata')` with NULL for the `'dao'` value.

Later when `rebuildMenuAndCaches` was called the dao cache in allCoreTables is cleared but the api info cache wasn't.

This puts the clearing of the metadata cache in there next to the clearing of the metadata stored in `allCoreTables`.

I moved the metadata setting earlier in the function (into 
```   // also cleanup all caches
    $config->cleanupCaches($sessionReset || CRM_Utils_Request::retrieve('sessionReset', 'Boolean', CRM_Core_DAO::$_nullObject, FALSE, 0, 'GET'));
```
which is probably the most arguable part of this change. That is how I tested it & the most important part is that they are together - however - I *think* it makes sense to move this to the cacheClear function both because it IS clearing caches and because it will then call hook::entityTypes BEFORE it calls settings and menu rebuild hooks - which *should* help with this work around I found in dataprocessor

```
/**
 * Implements hook_civicrm_alterMenu().
 *
 * @link https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_alterMenu/
 */
function dataprocessor_civicrm_alterMenu(&$items) {
  // This hook is called BEFORE civicrm_entityTypes so DataProcessor API calls will fail with missing BAO in
  //   some cases (eg. running cv flush from cli)
  // So we manually run it here before calling alterMenu function
  $entityTypes = [];
  _dataprocessor_civix_civicrm_entityTypes($entityTypes);
  foreach ($entityTypes as $entityType) {
    CRM_Core_DAO_AllCoreTables::registerEntityType(
      $entityType['name'],
      $entityType['class'],
      $entityType['table'],
      $entityType['fields_callback'] ?? NULL,
      $entityType['links_callback'] ?? NULL
    );
```

backtrace for the loading of the api info WITHOUT dao info

image

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@jaapjansma if you find time I'd be interested to know if this change makes your code ^^ redundant

**Comment by colemanw** [comment]
Code makes sense & tests pass. I think this is better in than out so merging.

**Comment by eileenmcnaughton** [comment]
thanks @colemanw

**Comment by jaapjansma** [comment]
Thanks for merging this. The code mentioned I do not recognize and I did look it up and saw @mattwire made that fix. So thanks for solving this.

**Comment by eileenmcnaughton** [comment]
Ok cool @jaapjansma  -  I actually found it because I was going to alter the signature of the function that your extension calls. It's definitely not a function we would support extensions to call directly but I did a universe search & found it. It's probably worth removing that if you can to future proof your code because if a core change caused that to break it would not be considered a regression

**Comment by jaapjansma** [comment]
For the moment I will keep the function as it is, as data processor is also used in older versions of CiviCRM and it would be nice when the extension is compatible with older versions of civi and newer versions of civi. Thanks for spotting this and fixing it.

**Comment by eileenmcnaughton** [comment]
@jaapjansma yeah I get around that by doing new releases tagging more recent civi versions & leaving people on older releases the option of using the older version of the extensions that have been tested against their civi-release - but I agree this change is not urgent

**Comment by jaapjansma** [comment]
Yes that is one way of doing it. I find it difficult to decide which version people have to use as those are my clients and they are paying me to do development work for them. 

Let me try to explain with an example why for personally this is not going to work.
One of my clients is a membership organization with 20.000 members, around 100 local chapters. They use CiviCRM for their head office (with around 20 full time employees).
I work for them approximatly 2 days per month. They ask me to various things around CiviCRM and a couple of them is small development tasks, and sometimes this includes an addition to an existing extension. Such as data processor, civirules or so...
They are still on CiviCRM version 5.14 and they wont upgrade soon as upgrading requires a lot of their resources as they need to test the whole system, including the member and chapter portal. But they are using the latest data processor version as they have paid me to develop additional functionality. 
So that is why I want to keep the extension compatible with older versions of CiviCRM as much as possible.  

By the way almost all of my development work is done by paying clients such as the example above.

**Pull request merged**
