### PR TITLE
Db dsn

### PR DESCRIPTION
**Pull request by julialongtin**
Add a dbDsn command line argument to CodeGen, so that users with no root access to their database server can use mysql's localize when creating files, without the (dirty, IMO) hack in setup.sh

### CODE REVIEW

**Comment by xurizaemon** [comment]
I am willing to review this PR.

@eileenmcnaughton ping

**Comment by eileenmcnaughton** [comment]
Cool - you should probably add yourself as willing to be in the super cleaners wg https://docs.google.com/spreadsheets/d/14j8YgFTeMneuLI7iKOBhZYu1i1oksvKLG47W7hYUwU0/edit

**Comment by colemanw** [comment]
@xurizaemon are you still up for reviewing this one?

**Comment by colemanw** [comment]
jenkins, retest this please

**Comment by colemanw** [comment]
jenkins, retest this please

**Comment by JoeMurray** [comment]
Julia as Release Manager this month, I'm trying to recruit people to help pare down the backlog of almost 100 PRs, some going back to last summer. I'm wondering if you would be able to help QA another PR if I got someone to QA this PR?

**Comment by totten** [comment]
This PR has a conflict, and #8940 has been merged which also addresses the issue of GenCode/ escaping/DSNs, but it does so differently. #8940 introduces alternative logic for escaping which does not rely on any DSN's.

**Pull request closed without merging**
