### PR TITLE
Update the list of required extensions to install during test db populate

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
There are some more required extses now.

Before
----------------------------------------
Difficult to properly test things locally unless you're set up however the jenkins run does it.

After
----------------------------------------
Can run phpunit like a normal person and have the right extses installed.

Technical Details
----------------------------------------

Comments
----------------------------------------
@highfalutin @kurund This addresses the inability to reproduce the test fails for https://github.com/civicrm/civicrm-core/pull/27107 locally.

Flexmailer is in sql/civicrm_data/civicrm_extension.sqldata.php. I'm not sure why there's two places.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Hmm I think at least some of the fails are pointing out real things. Argh this was supposed to be a quick win.

**Comment by colemanw** [comment]
@demeritcowboy I think we can just skip Afform in the v3 conformanceTest

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Pull request merged**
