### PR TITLE
Remove additional custom fields deletegroup functions

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This is a continuation of the other pr @eileenmcnaughton 

I have tested by running ./bin/regen.sh and showed no errors. I tried running the generateReportData.php but i think it has prexisting issues

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 when does generateReportData.php get called?

**Comment by seamuslee001** [comment]
@eileenmcnaughton i can't see it getting called at all 

```
grep -r 'generateReportData' *
seamus@civicrmdevphp7:~/buildkit/build/47-test/sites/all/modules/civicrm$
```

**Comment by eileenmcnaughton** [comment]
@seamuslee001 that seems to co-incide with the suggestion it doesn't really work :-)

**Comment by eileenmcnaughton** [comment]
thanks for updating those code comments - all good - should we stick a deprecation warning in   CRM_Core_BAO_Cache::deleteGroup now?

**Comment by seamuslee001** [comment]
@eileenmcnaughton probably, based on the code in the CRM/Core/BAO/Cache/Psr16.php there appears to be 3 extensions not yet converted. We have merged 1 PR for the lineitem editor but haven't yet had a new release and then created a PR for the dashboard one but then its just HR

**Comment by eileenmcnaughton** [comment]
@seamuslee001 so our practice has been to add those deprecation warnings & then when in dev mode the extension gets noisy but on prod sites it isn't. But, it we are nice we can add issues against the extensions in question (or if super nice PRs)

**Comment by eileenmcnaughton** [comment]
&I  tbh the CiviHR one probably won't update for quite a while because they have a different upgrade schedule (I think they target specific releases of Civi) so if we add the deprecation notice they can upgrade in their own timeframe

**Comment by eileenmcnaughton** [comment]
unrelated fail

**Pull request merged**
