### PR TITLE
CRM-13283 - Status page project

### PR DESCRIPTION
**Pull request by MegaphoneJon**
This is the work that Andrew and I worked on during the post-Denver sprint, Michael's work is largely separate.

### CODE REVIEW

**Comment by colemanw** [comment]
Wait, no bomb icon? How are we supposed to know what's going on with CiviCRM without a bomb icon??

**Comment by eileenmcnaughton** [comment]
Looks like Jenkins has something to say.... but I think despite the claim of 45 alerts a lot of them are in a single block of code

**Comment by PalanteJon** [comment]
This looks to mostly be civilint stuff...I didn't civilint others' code, and by the look of it, maybe didn't even civilint all of mine.  I'll go over that tomorrow.

**Comment by agh1** [comment]
I think I'm the culprit on most of it--spacing issue here and there.  I'll take care of it in a minute.

**Comment by agh1** [comment]
Okay so I created https://github.com/PalanteJon/civicrm-core/pull/1 against PalanteJon/status-page-jon which should fix the problems.  And yes, I was responsible for 90% of the problems (I was putting spaces after function comments all over the place).

**Comment by PalanteJon** [comment]
Just a note that this should be CRM-13823, not CRM-13283.

**Comment by eileenmcnaughton** [comment]
still red :-(

**Comment by agh1** [comment]
These are a bunch of test failures--some of the new api, and others that are new tests themselves.  @ginkgomzd @PalanteJon you know the new API code better than I.

@colemanw here you go:
bomb

**Comment by colemanw** [comment]
:+1:
Ooh, github comments have lots of emoticons. How about:
 :bomb:

**Comment by eileenmcnaughton** [comment]
looks like they are mostly e-notices

**Comment by eileenmcnaughton** [comment]
Looks like an integer rather than a string is being passed to the severity map function - leading to enotice - leading to bomb

**Comment by PalanteJon** [comment]
This is on my radar for this week, I haven't forgotten!  The severity map should be able to take integer OR string, depending on the value of the $reverse argument.  I'll get this sorted.

**Comment by eileenmcnaughton** [comment]
How goes on this?

**Comment by PalanteJon** [comment]
At the top of my list for Wednesday.

**Comment by PalanteJon** [comment]
Eileen, Andrew - OK, I took a crack at this today.  Andrew, I think you're more familiar with the code in question, so I'd like you to review.  My first commit removed a few calls to severityMap where we were already evaluating integers.  There's a second commit I did NOT make - look at $returnValues here: https://github.com/PalanteJon/civicrm-core/blob/status-page-jon/CRM/Utils/Check/Env.php#L418.

It seems like that array isn't used anywhere - and there's an e-notice because $return isn't defined.  I'm not sure what this code is intended to do, but I wanted to check in with you before simply removing it.

Finally - when I clicked on "Details" on my failed build merge above, I got a 404 error.  Do the test reports expire?

**Comment by eileenmcnaughton** [comment]
They do expire - but you have a new result now due to your new commit. Sadly it's rejected you on test formatting

**Comment by PalanteJon** [comment]
Ugh, the one day my linter isn't working...but that's OK, I'm just
excited to have a new test result.  I'll check this out today.

**Comment by PalanteJon** [comment]
Hmm - these Jenkins results all relate to files that aren't touched by this PR.  It points to formatting issues with:
ActivitySearch.php
ContribSYBNT.php
EventAggregate.php
TagContributions.php
FourFive.php
AddMessageTemplateTest.php

None of those are the 24 files we edited: https://github.com/civicrm/civicrm-core/pull/5973/files

Does that mean we're off the hook?

**Comment by totten** [comment]
Spot checking a random file, the smelly code in `CRM/Contact/Form/Search/Custom/ContribSYBNT.php`  appears to have originated circa March 1 (8bb3a4f3) and it was cleaned up circa May 14 (d14ccbdc). It doesn't have anything to do with this PR, but I suspect that the PR hasn't been rebased or merged since early May (and thus never got the cleanup). Tangentially: Github says it can't merge the branch automatically due to conflicts. If it were my branch, I'd rebase and resolve conflicts.

**Comment by PalanteJon** [comment]
I can take a hint :)  I'll try not to let this sit too long.

**Comment by PalanteJon** [comment]
Hmm...I rebased but I'm still getting errors?  I'm going to ask Joseph for some git help.

**Comment by PalanteJon** [comment]
Closing in favor of #6276.

**Pull request closed without merging**
