### PR TITLE
EventCart - Update readme to reflect current state

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Updates readme file for core ext.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw seems OK - I think it might be quite easy to move the `civicrm_event_carts` table to the extension - just basically move the xml & run the entity boilerplate stuff - that would mean new installs don't get the table - so we would have to stop enabling on new installs to make it work

**Comment by eileenmcnaughton** [comment]
annoyingly there is one other core table interaction - civicrm_participant.cart_id

The right fix would be to move it to a separate table in the cart extension but that is obviously more work

**Comment by eileenmcnaughton** [comment]
Good to merge - I just made some comments above & wasn't sure if the conversation had petered out or not

**Comment by colemanw** [comment]
> The right fix would be to move it to a separate table in the cart extension but that is obviously more work

That sounds like the correct way to do the migration though

**Pull request merged**
