### PR TITLE
(WIP) Email Preview Cluster

### PR DESCRIPTION
**Pull request by utkarshsharma**
I found some styling errors and I have tried to remove them, apart from a few minor edits.

### CODE REVIEW

**Comment by totten** [comment]
It looks like the code-style tests are passing. One step closer. :)

Next up: One of the unit tests -- `api_v3_SyntaxConformanceTest` -- is failing. The purpose of `SyntaxConformanceTest` is to check that various APIs are consistent. This PR introduces a new API entity, `Prevem`, with a custom action, `login`, but it doesn't introduce any of the conventional API actions (`get`, `create`, `delete`).

IMHO, those actions would be meaningless, so SyntaxConformanceTest should skip `Prevem` -- I don't see a real use-case for `Prevem.get`/`Prevem.create`/`Prevem.delete`. The app works fine with CiviMail directly accessing prevem's native REST API. To skip, update the list of ignored items: https://github.com/civicrm/civicrm-core/blob/master/tests/phpunit/api/v3/SyntaxConformanceTest.php#L85

OTOH, SyntaxConformanceTest is generally important, and maybe I'm too close to this one to see the problem. @eileenmcnaughton or @colemanw, do you have any thoughts or objections about the new Prevem API?

**Comment by eileenmcnaughton** [comment]
I don't see a problem with opting an entity out of having normal crud actions - if they don't logically apply

**Comment by eileenmcnaughton** [comment]
Am I right in thinking this was a GSOC project? It looks abandoned :-(

It also looks useful - but I'm inclined to think it should be an extension rather than core

**Comment by utkarshsharma** [comment]
Hi Eileen!
Yes, it was a GSoC project, from 2015, and yes it is kind of abandoned now.
But I'd be more than happy to get back to working on it and getting it
incorporated into the software, if possible. Can we chalk out a plan or
something?

**Comment by eileenmcnaughton** [comment]
The easiest way to put this into people's hands & make it (very) useful would be to convert it to an extension - did you look into that at all?

**Comment by utkarshsharma** [comment]
I don't think so.

**Comment by eileenmcnaughton** [comment]
It's pretty easy to create an empty extension using Civix https://github.com/totten/civix & then mostly it's a case of moving the new classes & api into there. There is a function to create the shell of an angular page

Are you still studying or have you moved on since?

**Comment by utkarshsharma** [comment]
I'll look into all of that and get back to you ASAP.
I'm still studying. Still one year to go before I graduate.

**Comment by colemanw** [comment]
@totten may be working on something similar right now.

**Comment by eileenmcnaughton** [comment]
@utkarshsharma a good place to discuss chat.civicrm.org

**Comment by eileenmcnaughton** [comment]
I'm closing this as a PR as it is not ready for review (stale) - but I have opened https://issues.civicrm.org/jira/browse/CRM-19491 as a way to track & retrieve this. I assigned it to Monish who I believe is leading in this area at the moment

**Comment by eileenmcnaughton** [comment]
NB obviously when there IS something new to review a new Pull request is appropriate

**Pull request closed without merging**
