### PR TITLE
Throw spaghetti

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Enable escape on output for unit tests

Before
----------------------------------------
Not enabled for unit tests - issets & things that are notices when it is on sneak through

After
----------------------------------------
Enabled for unit tests - although I suspect only some since I think there would have been more failures otherwise. 

Technical Details
----------------------------------------

Comments
----------------------------------------

https://github.com/civicrm/civicrm-core/pull/22070/files#diff-b0e39754f5c0209c45b75774d772d429b3f947203d0681794120256f1c4d2c68R412 is the key line

### CODE REVIEW

**Comment by totten** [comment]
Spaghetti

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 the spaghetti stuck!

**Comment by colemanw** [comment]
Neat. Can you maybe add a description to this PR @eileenmcnaughton so we know what we're looking at (other than Tim's spaghetti monster illustration)

**Comment by eileenmcnaughton** [comment]
@colemanw doesn't it say it all?

**Comment by colemanw** [comment]
Ok, tests are happy and this is a step in the right direction.

**Comment by davejenx** [comment]
I've hit a side-effect of the addition of 6 lines to CRM/Report/Form.php at line 2500:

```
       if (!empty($value['no_display'])) {
         unset($this->_columnHeaders[$key]);
       }
+      foreach (['colspan', 'type'] as $expectedKey) {
+        if (!isset($this->_columnHeaders[$key][$expectedKey])) {
+          // Ensure it is set to prevent smarty notices.
+          $this->_columnHeaders[$key][$expectedKey] = FALSE;
+        }
+      }
     }
```

In a custom report, with the above change in place, `no_display` on items in `$this->_columnHeaders` is no longer respected: these columns are displayed. With these 6 lines removed, it works as before: the columns are hidden. Alternatively putting those 6 lines within an `else` block under the `!empty($value['no_display'])` condition also works.

The custom report does all its business in postProcess(), with a fixed set of columns defined there with e.g.

```
    $this->_columnHeaders = array(
      'batch_title' => array('title' => 'Batch'),
      'receive_date' => array('title' => 'Date Received'),
      ...,
      'contact_id' => array('title' => 'Contact ID', 'no_display' => TRUE),
```

Then constructs a query & runs buildRows(), formatDisplay(), doTemplateAssignment(), endPostProcess(). Worked in 5.35.2. Does this need rejigging to work with current CRM/Report/Form.php or should CRM/Report/Form.php be amended?

**Comment by eileenmcnaughton** [comment]
@davejenx so my reading is that the lines above unset no_display and then they are re-added but the 'ensure fields are set part' - it feels like the easiest would be to reverse the order- so the isset happens last?

**Comment by davejenx** [comment]
Hi @eileenmcnaughton , thanks for taking a look!

Yes, reversing the order works, so that the 6 added lines (from `foreach (['colspan', 'type'] ...)`) go above the `if (!empty($value['no_display']))` condition instead of below.

Or as I suggested, put those 6 lines within an `else` block under the `!empty($value['no_display'])` condition - that way, we don't create extra entries only to delete their parent entry afterwards.

**Comment by eileenmcnaughton** [comment]
@davejenx do you want to put one of those options up as a PR

**Comment by davejenx** [comment]
Thanks @eileenmcnaughton , done: #23321 .

**Pull request merged**
