### PR TITLE
Updating php-weasyprint to latest version

### PR DESCRIPTION
**Pull request by sadashivdalvi**
Overview
----------------------------------------
Can't install civicrm 5.71.1 on php 8.3

Technical Details
----------------------------------------
Php-WeasyPrint is locked at 0.13 version which works only till php 8.2 version so the installation fails, we should go to latest version i.e. 1.3.0 so that it works with php 8.3

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Hi @sadashivdalvi I think maybe you ran `composer update` instead of just `composer require pontedilana/php-weasyprint:'^1'`, so it updated everything which is too much.

**Comment by sadashivdalvi** [comment]
Hi @demeritcowboy 

Have reverted my changes and committed the composer.lock again so that it has changes only for weasyprint and dependecy updates.

Thanks,
Sadashiv.

**Comment by demeritcowboy** [comment]
I think what happened this time is that in composer.json for symfony/process, it only allows 4 or 6, and weasyprint 1.x doesn't allow 4, so it jumps to 6 and then ends up requiring php 8 which is too high. Maybe try this change and then try again?

```diff
-"symfony/process": "~4.4 || ~6.0",
+"symfony/process": "~4.4 || ~5.0 || ~6.0",
```

**Comment by sadashivdalvi** [comment]
I tried making that change in composer.json but that still makes the composer update process to 6.x may be because my local has php 8 or something, so I remove 6.0 from the version list and committed what I got.

Thanks,
Sadashiv.

**Comment by demeritcowboy** [comment]
I see, except I think that might prevent drupal10 installs. Would need to test.

An alternative might be make the same suggested change to allow 4 and 5 and 6, then `composer require pontedilana/php-weasyprint:'^1'`, then then run `composer update symfony/process:~5.0` to lock a 5 version for tarballs.

Sorry this is probably more work than you were hoping.

**Comment by sadashivdalvi** [comment]
ok, Did that and recommitted the files.

Thanks,
Sadashiv.

**Comment by demeritcowboy** [comment]
```
CRM_Core_ComposerConfigTest::testHardLocks
Check hardlock for symfony/process
Failed asserting that 'v5.4.36' matches PCRE pattern "/^v4\.4\./".

/home/homer/buildkit/build/build-2/web/sites/all/modules/civicrm/tests/phpunit/CRM/Core/ComposerConfigTest.php:37
```

I think that test fail is more about warning that something might be changing without thinking about it, rather than saying you can't change it, and we've kinda thought about it so I think it's a matter of updating the test.

```diff
-'symfony/process' => '/^v4\.4\./',
+'symfony/process' => '/^v5\.4\./',
```

Looking at the changelog https://github.com/symfony/process/compare/v4.4.41...v5.4.36#files_bucket nothing too interesting comes up except they've removed some functions that wouldn't be used in core and likely only @totten would ever use, and a universe search doesn't show them being used.

So if you can update that test, and [squash commits](https://docs.civicrm.org/dev/en/latest/tools/git/#rebasing-interactive), and in the meantime I'll give it a run to see if the updated weasyprint works.

**Comment by sadashivdalvi** [comment]
Currently we can't install civicrm 5.71.1 on php 8.3 because of php-weasyprint, can we try to check this?

Thanks,
Sadashiv.

**Comment by demeritcowboy** [comment]
@sadashivdalvi Can you update that test (CRM_Core_ComposerConfigTest::testHardLocks) as suggested in the previous comment, and [squash commits](https://docs.civicrm.org/dev/en/latest/tools/git/#rebasing-interactive), and then I think we can merge this.

**Comment by sadashivdalvi** [comment]
@demeritcowboy Did as you said, and now the tests passed.

Thanks,
Sadashiv.

**Comment by demeritcowboy** [comment]
Great, thanks. Are you able to [squash commits](https://docs.civicrm.org/dev/en/latest/tools/git/#rebasing-interactive)?

**Comment by sadashivdalvi** [comment]
@demeritcowboy 

I tried git rebase -i upstream/master
and it did gave me the vim editor with my comits marked as picked, and then I force pushed the commits, did I miss something?

Thanks,
Sadashiv.

**Comment by colemanw** [comment]
@sadashivdalvi you should change "pick" to "s" (for "squash") for all but the first commit. This will squash them into a single commit.

**Comment by sadashivdalvi** [comment]
@demeritcowboy done.

**Comment by sadashivdalvi** [comment]
@demeritcowboy Would like to know, will this be included in the 5.72 release or do I need to add a PR to the 5.72 branch?

**Comment by demeritcowboy** [comment]
I don't think civi is officially supported with 8.3? It's still considered "edge" (e.g. https://test.civicrm.org/job/CiviCRM-Core-Edge/CIVIVER=master,label=bknix-tmp-edge/3352/consoleText)

**Comment by sadashivdalvi** [comment]
Currently we say that civicrm is compatible with php 8.3 in https://docs.civicrm.org/installation/en/latest/general/requirements/ but we can't install the module on php 8.3 until we have this fix released, which is why I think we should consider to release this fix in 5.72 release, I want to install civicrm on production environment which is running php 8.3 but can't do it as composer install fails, I don't want to use the dev-master approach as it's a production website.

Thanks,
Sadashiv

**Comment by jofranz** [comment]
@eileenmcnaughton Would it hurt to also merge this into RC? Looks like it would reward @sadashivdalvi for being eager reporting and providing a PR :thinking: 

@sadashivdalvi Guess creating a PR against RC sounds like a good idea

**Comment by sadashivdalvi** [comment]
@jofranz Do you mean I should send PR to the [5.72](https://github.com/civicrm/civicrm-core/tree/5.72) branch?

**Comment by jofranz** [comment]
> @jofranz Do you mean I should send PR to the [5.72](https://github.com/civicrm/civicrm-core/tree/5.72) branch?

@sadashivdalvi Exactly :)

**Comment by sadashivdalvi** [comment]
@demeritcowboy @jofranz have send another PR on 5.72 branch at https://github.com/civicrm/civicrm-core/pull/29806

Thanks,
Sadashiv.

**Comment by demeritcowboy** [comment]
Oops I think we've now blocked drupal 9. I know it's EOL but we should give some lead time for civi to stop supporting it. I'll try some tests - maybe something like `"pontedilana/php-weasyprint": "^0.13.0 || ^1"` will work.

**Pull request merged**
