### PR TITLE
APIv4 - Make the @searchable flag explicit for OptionList type entities.

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Improves code for categorizing entities for SearchKit, making searchability easier to grok and less magical/mysterious.

Comments
----------------------------------------
When I was first trying to figure out how to categorize entities in SearchKit I came up with this "OptionList" type, which seemed like a good idea at the time. But then I later developed the `@searchable` flag which works much better.
The OptionList trait may or may not be useful in future, maybe we'll just get rid of it if not.
But I think it's better not to couple it with the `@searchable` flag, as that's not exactly the same thing.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw so are fields like 'MembershipType.minimum_amount' still accessible with this change?

**Comment by colemanw** [comment]
@eileenmcnaughton this doesn't change any functionality, just the structure of the code.

**Comment by eileenmcnaughton** [comment]
@colemanw per discussion I think we should expose many of these in search kit now we have the to-be-documented 'secondary' notification

**Comment by colemanw** [comment]
@eileenmcnaughton it's updated now

**Comment by eileenmcnaughton** [comment]
OK - so the entities marked as secondary were not available before but now they are in the 'long list'

I think that's a good thing as they all have fields you might want to display & the main reason we didn't before was the UI

**Comment by colemanw** [comment]
Yep

**Pull request merged**
