### PR TITLE
dev/core#5390 enable UI setting admin for standaloneusers

### PR DESCRIPTION
**Pull request by ufundo**
Overview
----------------------------------------
This enables the setting-admin mixin for standaloneusers which allows UI access to the session timeout setting.

Before
----------------------------------------
- session timeout is only settable via API

After
----------------------------------------
- session timeout settable through UI

image

image

Comments
----------------------------------------
Would be nice to hae a UI to set in other human units (days / hrs / mins) but not sure how that would be implemented.

Maybe the menu item could be better in `Users and Permissions`. But also this feels like a relatively advanced setting, so maybe it's fine where it is.

### CODE REVIEW

**Comment by ufundo** [comment]
Added a button to the admin page from the User Account admin screen 
image

**Comment by colemanw** [comment]
@ufundo it might be more human-friendly to make the unit "minutes" instead of "seconds" in the UI.

**Comment by ufundo** [comment]
agree that would definitely be better. is there any easy way to do that with these auto-generated settings pages?

**Comment by ufundo** [comment]
potential brute force approach would be to change the units of the setting itself to minutes. any reason why anyone might need sub-minute accuracy?

**Comment by totten** [comment]
> potential brute force approach would be to change the units of the setting itself to minutes. any reason why anyone might need sub-minute accuracy?

Hard to think of a good reason for session TTL specifically to be sub-minute.

---

The setting `standaloneusers_session_max_lifetime` was introduced in 5.70 with a default value of `24*24*60*60`. If downstream has changed or materialized the value, then there's the migration question. (Any existing values in `civicrm_setting` or `$civicrm_setting` would be off by a factor of 60.) But it's a yucky question. The setting is unlikely to have been customized on any sites, esp without a GUI. OTOH, it has been around 6+ months, and we have no visibility. OTOOH, "Standalone" has been in "Preview" period, so it's caveat emptor. OTOOOH, it's quite annoying for downstream when data changes sneakily, and it's good to keep the habit of migrating.

(*FWIW, here's untested pseudocode of an upgraade-notice: https://gist.github.com/totten/f84b82c59e80fb89bb0f7417372c45b2. That wouldn't make it easy for affected parties, but it would prevent a cycle of debugging=>reporting=>triage=>fixing=>releasing.*)

**Comment by colemanw** [comment]
I think that due to the "preview" nature of Standalone it's fine to change the units. IMO the simplest "migration" would be to delete the row in `civicrm_settings` if it exists.

**Comment by totten** [comment]
> IMO the simplest "migration" would be to delete the row in `civicrm_settings` if it exists.

Yeah, I don't think there's any need to proactively convert data...

**Comment by ufundo** [comment]
That's a lot of hands @totten .

I'd venture it's more hands than people who have been able to install Standalone, find this setting exists, and set a value for it - especially given no UI until this week.

https://github.com/civicrm/civicrm-core/pull/30951

**Pull request merged**
