### PR TITLE
Fix createEmployerRelationship to work with the data it has when doing a lookup, test

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fix createEmployerRelationship to work with the data it has when doing a lookup, test

Before
----------------------------------------
When doing a batch merge a contact will fail to merge (as a conflict) if they have an existing employer relationship on the relationship

After
----------------------------------------

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@demeritcowboy any chance I could get you to look at this - the replication is basically as per the test

**Comment by eileenmcnaughton** [comment]
thanks heaps

**Comment by demeritcowboy** [comment]
Interestingly it still distinguishes between two relationships that are otherwise the same except for a custom field and so (correctly I think) let's you add two of the same that only differ by a custom field. Not sure where that code is happening now but I can see a valid use for that so ok good. It might be more common for a relationship type other than employer, but maybe if you were using relationships to track multiple job roles for a person at the same company or something like that.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy yeah - I think there are some conflicting use cases around the whole relationship matching issue tbh

**Pull request merged**
