### PR TITLE
dev/core#4707 Don't error if extension has empty `requires` tag

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Handle empty tags in extensions' `info.xml` without crashing.

See https://lab.civicrm.org/dev/core/-/issues/4707

Before
-----
Crash

After
-------
No crash

### CODE REVIEW

**Comment by seamuslee001** [comment]
@colemanw test fail relates here

**Comment by colemanw** [comment]
Ok I've added unit test coverage for this, and as a bonus I've fixed a potential PHP8 bug with undeclared properties being set in the `CRM_Extension_Info` class (with test coverage for that as well).

**Comment by seamuslee001** [comment]
@colemanw should this be against the RC?

**Comment by colemanw** [comment]
@seamuslee001 I guess so. It's not technically a regression, but it does fix a bug so if we want to get bugfixes in sooner than later, yes.

**Comment by totten** [comment]
Confirmed this does appear to fix load-error on "Manage Extensions". :+1:

> ...undeclared properties being set in the CRM_Extension_Info...

FWIW, in all of universe, I could only find a couple cases of unrecognized tags. I'm pretty sure none of these would be affected by having the tighter `$info` object. 

```
Check ./universe/ext/au.com.agileware.civicontactapi/info.xml
  Extras: versioncode
Check ./universe/ext/civicontactapi/info.xml
  Extras: versioncode
Check ./universe/ext/com.aghstrategies.giftmemberships/info.xml
  Extras: documentation
Check ./universe/ext/com.cividesk.helptab/info.xml
  Extras: documentation
Check ./universe/ext/org.project60.bic/info.xml
  Extras: phpCompatibility,phpIncompatibility
Check ./universe/ext/uk.co.compucorp.civicrm.booking/info.xml
  Extras: documentation
```

>  It's not technically a regression...

Yeah, I probably would'a gone with `master` too, but the patch is small, so I won't pushback if y'all  want RC.

**Comment by colemanw** [comment]
Thanks @totten, I think either version is fine. I'll go ahead & merge, on the off-chance that a user of 5.67 prefers not crashing to crashing.

**Pull request merged**
