### PR TITLE
CRM-16165 fix - Combining online membership signup with a recurring addi...

### PR DESCRIPTION
**Pull request by monishdeb**
...tional contribution results in incorrect recurring contribution amount and frequency

https://issues.civicrm.org/jira/browse/CRM-16165

### CODE REVIEW

**Comment by davecivicrm** [comment]
jenkins, test this please

**Comment by eileenmcnaughton** [comment]
I'm not getting that error locally - will get Jenkins to retest in case it's Authorize.net timing

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by davecivicrm** [comment]
The actionSchedule test failure is unrelated. Both Eileen and I ran the entire api test (api_v3_ContributionPageTest) locally and all methods passed including the one that's reporting a failure on jenkins.

**Pull request merged**
