### PR TITLE
(dev/core#2944) Make report column groups hookable

### PR DESCRIPTION
**Pull request by yashodha**
Overview
----------------------------------------
Provide a way to manipulate column groups in report to change the order of the column checkboxes in the Columns tab

Before
----------------------------------------
No way to manipulate column groups.

After
----------------------------------------
Column groups in report are now exposed

Technical Details
-------------------------
Ideally, there should be some weight mechanism to alter the display of the columns.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
I added the needs-documentation label since https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_alterReportVar would need updating. Ideally a test too! e.g. https://github.com/civicrm/civicrm-core/blob/e0c2ee78aa2172e49ff977ce4bad7aa9d7b31c3a/tests/phpunit/api/v3/ReportTemplateTest.php#L350

**Comment by eileenmcnaughton** [comment]
It's worth nothing you can already change the assigned value in other hooks

**Comment by jaapjansma** [comment]
@yashodha @bettydolfing and I are reviewing PR's and we came across this one. It looks like this PR is stalled because @demeritcowboy said it needs documentation and @eileenmcnaughton said it is already possible. What do you think about this? If you agree with @eileenmcnaughton we might close this PR. If not are you able to provide documentation as well?

**Comment by eileenmcnaughton** [comment]
Yeah - lets' close this & @yashodha can bring it back if still needed. We are definitely try to add less to the reports & switch to search kit but @yashodha has been doing quite a bit of good cleanup too

**Pull request closed without merging**
