### PR TITLE
dev/core#2717 Use Same order ->payment flow for non recurring back of…

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
dev/core#2717 Use Same order ->payment flow for non recurring back office memberships as for recurrings

Before
----------------------------------------
If a recurring contribution is created we use the order api, otherwise magic custom code

After
----------------------------------------
Consistent use of the order api

Technical Details
----------------------------------------
Note - I'm expecting a test fail on the first run of this - if there isn't one it might mean that there is a missing piece of test cover as I think doing this change had been blocked by not storing membership_num_terms in the line item table (it never worked for recurrings for mulitiple terms iirc

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton 

```
Form.php:579, After, Priority: High
Expected 1 blank line after function; 2 found
```

**Comment by eileenmcnaughton** [comment]
I think the test fails here might actually be 'good' - but I want to get the pre-requisite merged https://github.com/civicrm/civicrm-core/pull/20941

**Comment by eileenmcnaughton** [comment]
@monishdeb I just rebased the one you just merged out of this - if you look with no whitespace https://github.com/civicrm/civicrm-core/pull/20936/files?w=1 this is less than it looks - but it alters it to do Order->payment.create for non-recurring card payments.

I'll follow this up with a switch to using the v4 membership api (which I'll add) from within the Order.create api - but I wanted to get this test-cover extension first

**Comment by monishdeb** [comment]
I have tested on my local, tried different use-cases which touch the code where Order API call is introduced and didn't encounter any breakage/regression. Reviewed the patch. Changes look good and make sense. Merging now.

**Comment by eileenmcnaughton** [comment]
Thanks @monishdeb !

**Pull request merged**
