### PR TITLE
5.17 bump version and add in release notes

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
Bumps version to 5.17.1 and adds in the release notes

ping @eileenmcnaughton @totten

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
unrelated fail

**Comment by demeritcowboy** [comment]
@seamuslee001 Just curious does CRM/Upgrade/Incremental/sql/5.17.1.mysql.tpl automatically make its way into 5.18 and master at some point? The reason I'm asking is that currently if you were to upgrade straight from 5.16 up to 5.18 it skips the 5.17.1 upgrade tasks completely since the mysql file isn't present in 5.18. Should I have added it when I did https://github.com/civicrm/civicrm-core/pull/15239?

**Comment by seamuslee001** [comment]
@demeritcowboy i think that is ok because you fixed the original function that is called in 5.17.alpha1 which is run in that process so i think it will be ok but @totten would be best on this

**Comment by demeritcowboy** [comment]
Ok thanks you're right in this *specific* instance it doesn't matter but I guess this answers my question that you DO in general need to add a blank tpl file when first adding something for a new point release otherwise the upgrade task for it won't run. It actually says this in the docs in a big box, but of course I didn't read the docs (https://docs.civicrm.org/dev/en/latest/framework/upgrade/#incremental-sql-files).

**Comment by seamuslee001** [comment]
@demeritcowboy so i guess the solution would be is the following 

for the RC -> add in a step for it in the beta1 stage
for the backport put it against the new point release i geuss but @totten  is the best one to guide us here

**Comment by demeritcowboy** [comment]
Since 5.17.1 isn't released yet wouldn't the simplest be for me to just add the .tpl file that's already added to 5.17 by this PR to 5.18 and master?

**Comment by totten** [comment]
One usually doesn't need to worry about this with most PRs/backports; however, if there's a patch that's getting put into both RC and stable branches, then it's important to think about the different upgrade paths. (Another related link: [rg-upgrades](https://docs.civicrm.org/dev/en/latest/standards/review/#rg-upgrades))

Strictly speaking, the most thorough approach would be:

* In `5.17`, bump 5.17.0 to 5.17.1 and include an upgrade-step specifically for `5.17.1`.
* In `5.17`, bump 5.18.beta1 to 5.18.beta2 and include an upgrade-step specifically for `5.18.beta2`.
* In both cases, write the upgrade step in a way that's idempotent - so that it's safe if somebody re-executes. (However, the exact patch/code may be nominally different.)

This fixes things up for the (small but important) frontline constituency who use an RC. In fact, it should work in just about every upgrade-path that an admin could choose, e.g.

* `5.16.x` => `5.17.1` (b/c step is defined once)
* `5.16.x` => `5.18.0` (b/c step is defined once)
* `5.16.x` => `5.17.0` => `5.17.1` => `5.18.0` (b/c step is idempotent)
* `5.16.x` => `5.18.beta1` => `5.18.beta2` (b/c step is defined once)
* `5.17.0` => `5.17.1` => `5.18.beta2` (b/c step is idempotent)
* `5.17.0` => `5.18.0` (b/c step is defined once)
* `5.18.beta1` => `5.18.0` (b/c step is defined once)

However, I don't really want to proscribe a one-size-fits-all process for something which happens in maybe 4% of backports and whose importance depends on circumstance.

It's *best* to have different upgrade steps for 5.17.1 and and 5.18.beta2. However, in this context (given that RC is only a few days old and the change isn't major), you probably wouldn't get any complaints from the KISS approach of just adding `5.17.1.mysql.tpl` to the `5.18` branch.

**Pull request merged**
