### PR TITLE
SearchKit - Add primary email, phone, im as searchable fields

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Makes it easier to search and display contact primary email, phone, im without using any joins in SearchKit.
See [dev/core#3659](https://lab.civicrm.org/dev/core/-/issues/3659)

image

### CODE REVIEW

**Comment by aydun** [comment]
Looks good.  The 3 fields show up in explorer starting from `Contact.get`.  Also implicit joins eg from `Participant.get` `contact_id.primary_email` works.  `primary_email` can also be used in WHERE clauses.

In SK the fields show where expected - ie as available columns and where clauses.

Two things that seem odd:
1.  in API Explorer, I can select `primary_email` and that works.  But it is not returned if I don't select any fields or choose '\*'.  I guess that's ok not to include by default, but it seems odd not to include it with '\*'.

Similarly, if I start from Participant.get, the select fields include `contact_id.primary_email` but it is not returned as part of `contact_id.*`

2.  in Search Kit,  `Email (primary)` shows as a column header and in the WHERE clause dropdown BUT is not available as a join condition.  See [this](http://core-23819-43jm9.test-1.civicrm.org:8001/civicrm/admin/search#/create/Participant?params=%7B%22version%22:4,%22select%22:%5B%22id%22,%22Participant_Contact_contact_id_01.display_name%22,%22Participant_Contact_contact_id_01.primary_email%22%5D,%22orderBy%22:%7B%7D,%22where%22:%5B%5B%22Participant_Contact_contact_id_01.primary_email%22,%22%3D%22,%22%22%5D%5D,%22groupBy%22:%5B%5D,%22join%22:%5B%5B%22Contact%20AS%20Participant_Contact_contact_id_01%22,%22INNER%22,%5B%22contact_id%22,%22%3D%22,%22Participant_Contact_contact_id_01.id%22%5D%5D%5D,%22having%22:%5B%5D%7D)  and look at the condition fields under Participant Contact.  That doesn't matter much since you can use it in WHERE but is slightly anomalous.

Besides that. everything I tested worked as expected.

**Comment by colemanw** [comment]
Thanks for the review @aydun. Yes there are some limitations to virtual fields. Not including them with `SELECT *` is by design. In APIv4, `*` means "all core fields" so it includes custom fields & extra/virtual fields. This was a conscious decision to avoid performance bottlenecks.

**Comment by aydun** [comment]
Ok, that makes sense. 

Also, `Contact.getFields` results for `primary_email` all seem reasonable (not that I don't understand how they are all used!). 

Looks good to me. `r-run`: ok

**Comment by colemanw** [comment]
Aside, it would be possible albeit trickier to add `primary_address`. The SQL would be more complex because it would need to grab the site's default address formatting rule and convert it to a SQL concatenation of all the address fields to be returned as a single string.

**Comment by eileenmcnaughton** [comment]
I've added merge-ready based on the review by @aydun - I could probably go further & merge this but am pre-coffee so want to recognise that weakness in my ability to fully process this right now

**Comment by eileenmcnaughton** [comment]
I took a look at this and in fact it ties in with something else I've been looking at /  a discussion I've been meaning to raise

When I dug into the tokens I was able to switch most entities to use apiv4. The exception was the `Contact` entity because of the way it uses primary location fields. This would allow us to switch over - it would require some aliasing.

I had assumed that rather than the fields winding up being `primary_email` they would be `contact_id.primary_email.email` where `primary_email` implies 'add a join to the email table called `primary_email`  and then fields within that table would be available eg. `contact_id.primary_address.street_address` etc. The virtual fields wasn't a solution I was thinking of so I can't argue my imagined 'implicit join' is better but I just want to throw a few more things in the mix which I thought would need to be part of this discussion ....


1. address fields - you suggest we want a display - I think for the use cases I'd been thinking of (both search kit and tokens) the thing I wanted was all the fields you can get through v3 api - 'primary_city', 'primary_state_province_id:label` etc
2. billing_address fields - the specific use case I have at the moment is for tokens - I've been going through the message templates and using tokens where available, which permits code cleanup, UI previews and form-flow-separation. Where variables do not have existing tokens I've been looking at adding them and `billing_address.street_address` etc are the current gap I'm looking at. These make a lot of sense as tokens to me
3. `create` actions. What I find is that I use `apiv4` as much as possible - but with `contact.create` I always fall back on `v3 api` because it is so much easier to use than having  to deal with email, phone, address etc in `apiv4`. I would really like to use a fix (virtual field or implicit join) that also eases the create action AND makes it easier to define sample data. 
- . SampleData - we now have an api that retrieves sample data - my hope was that we could define this in a way that works for `apiv4` create and can be used in tests to that effect and in the sort of Message template sample - I had a go at this a long time ago but stalled on wanting to being able to define details in a suitable way https://github.com/civicrm/civicrm-core/compare/master...eileenmcnaughton:example?expand=1#diff-ca12cadedc2f586707e2184820777f5cef768ce03dd4e94186d9ac2621d9adf9R31


I would note that this PR does improve the UI experience but I'd been keen to catch up & chat briefly on this

**Comment by colemanw** [comment]
I agree as well. A consistent way to get all fields for primary email/phone/im/address from Contact.get, as well as a way to *set* those fields from Contact.create/update would be ideal, and it would also unblock #21690 which was stalled due to lack of a way to pass phone/address/email fields into the contact api.

I'm not sure what the params ought to look like exactly. `primay_address.city` and `primary_phone.phone` seems pretty reasonable. 

I'll note that for deduping purposes (which @kurund recently asked about on chat and I referred him to the discussion on #21690), the deduper actually accepts multiple phones, multiple emails, etc when it searches for matches. It seems a shame to cripple that functionality at the API level by only accepting single values.
I guess we could also consider supporting locations like `home_address.city` and `work_phone.phone`. Maybe as a followup.

**Comment by mattwire** [comment]
Just noting that I think this is a good idea, at least for primary details. However we need to be careful with the location types because these are configurable and it could get messy - eg. I'm not sure what the actual restrictions are on what can be in `civicrm_location_type.name` and that's what we'd be exposing in the API.

**Comment by colemanw** [comment]
I've opened #23845 which improves this PR by using implicit joins instead of subquery-based virtual fields.

**Pull request closed without merging**
