### PR TITLE
CRM-20243 - Add check for deleted files and try removing them as part of upgrade

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @totten @jackrabbithanna this is an attempted port of Tim's work to 4.6. The issue is that especially the Joomla upgrade can leave files that we have removed from this or the packages repo behind. So this attempts to clean them up as part of the upgrade

Tim are you able to check if my porting of your work makes sense

---

 * [CRM-20243](https://issues.civicrm.org/jira/browse/CRM-20243)

### CODE REVIEW

**Comment by jackrabbithanna** [comment]
In the comment block for CRM/Utils/Check/Source.php can you update it to say 4.6 instead of 4.7 ?

**Comment by totten** [comment]
Agree the header docs should say "4.6" to "4.7", but it's not a blocker.

Had a couple concerns/questions initially (e.g. A: that `composer.json` might be in a different place for older versions -- but this is right for 4.6. B: that the path constructions needs to work differently, but this was already addressed.). 

On general principles, seems good to me.

**Comment by seamuslee001** [comment]
@totten @jackrabbithanna I have run this a few times with a local 4.6 buildkit and seems to work as expected, Made some changes to help make the usorting work but not that necessary and i updated the version to be 4.6 not 4.7 as per request.  I also made a change because i noticed it was already adding a / onto the end of $civicrm_root

As long as tests pass i think this should be sound to merge

**Comment by totten** [comment]
Thanks.

+1 for the changes.

**Pull request merged**
