### PR TITLE
Eliminate calls to `CRM_Contribute_PseudoConstant::contributionStatus` and deprecate it noisily

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
`CRM_Contribute_PseudoConstant::contributionStatus` needs to be noisly deprecated - but need to not be called first 

Before
----------------------------------------
`CRM_Contribute_PseudoConstant::contributionStatus` 
is code-comment deprecated with the comment saying

```
   * @deprecated use standard methods like
   *   CRM_Core_PseudoConstant::getLabel('CRM_Contribute_BAO_Contribution', 'contribution_status_id', $contributionStatusID);
   *   CRM_Core_PseudoConstant::getName('CRM_Contribute_BAO_Contribution', 'contribution_status_id', $contributionStatusID);
   *   CRM_Core_PseudoConstant::getKey('CRM_Contribute_BAO_Contribution', 'contribution_status_id', $contributionStatusID);
   *   & don't specify 'CRM_Contribute_BAO_Contribution' if you mean 'CRM_Contribute_BAO_ContributionRecur' ...
   *
```

After
----------------------------------------
Noisy deprecation notice

Technical Details
----------------------------------------
There are quite a few places to remove from core before it can be noisly enabled

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
There are enough I'll stick to the 'first tranche'

[Test Result](https://test.civicrm.org/job/CiviCRM-Core-PR/51385/testReport/) (340 failures / +340)
[CRM_Activity_Form_SearchTest.testSearch](https://test.civicrm.org/job/CiviCRM-Core-PR/51385/testReport/junit/(root)/CRM_Activity_Form_SearchTest/testSearch/)
[CRM_Activity_Form_SearchTest.testQill](https://test.civicrm.org/job/CiviCRM-Core-PR/51385/testReport/junit/(root)/CRM_Activity_Form_SearchTest/testQill/)
[CRM_Activity_Form_SearchTest.testTaskController with data set #0](https://test.civicrm.org/job/CiviCRM-Core-PR/51385/testReport/junit/(root)/CRM_Activity_Form_SearchTest/testTaskController_with_data_set__0/)
[CRM_Activity_Form_SearchTest.testTaskController with data set #1](https://test.civicrm.org/job/CiviCRM-Core-PR/51385/testReport/junit/(root)/CRM_Activity_Form_SearchTest/testTaskController_with_data_set__1/)
[CRM_Activity_Form_SearchTest.testTaskController with data set #2](https://test.civicrm.org/job/CiviCRM-Core-PR/51385/testReport/junit/(root)/CRM_Activity_Form_SearchTest/testTaskController_with_data_set__2/)
[CRM_Activity_Form_SearchTest.testTaskController with data set #3](https://test.civicrm.org/job/CiviCRM-Core-PR/51385/testReport/junit/(root)/CRM_Activity_Form_SearchTest/testTaskController_with_data_set__3/)
[CRM_Activity_Form_SearchTest.testTaskController with data set #4](https://test.civicrm.org/job/CiviCRM-Core-PR/51385/testReport/junit/(root)/CRM_Activity_Form_SearchTest/testTaskController_with_data_set__4/)
[CRM_Activity_Form_SearchTest.testTaskController with data set #5](https://test.civicrm.org/job/CiviCRM-Core-PR/51385/testReport/junit/(root)/CRM_Activity_Form_SearchTest/testTaskController_with_data_set__5/)
[CRM_Activity_Form_SearchTest.testTaskController with data set #6](https://test.civicrm.org/job/CiviCRM-Core-PR/51385/testReport/junit/(root)/CRM_Activity_Form_SearchTest/testTaskController_with_data_set__6/)
[CRM_Activity_Form_SearchTest.testTaskController with data set #7](https://test.civicrm.org/job/CiviCRM-Core-PR/51385/testReport/junit/(root)/CRM_Activity_Form_SearchTest/testTaskController_with_data_set__7/)
[CRM_Activity_Form_SearchTest.testTaskController with data set #8](https://test.civicrm.org/job/CiviCRM-Core-PR/51385/testReport/junit/(root)/CRM_Activity_Form_SearchTest/testTaskController_with_data_set__8/)
[CRM_Batch_BAO_BatchTest.testGetBatchFinancialItems](https://test.civicrm.org/job/CiviCRM-Core-PR/51385/testReport/junit/(root)/CRM_Batch_BAO_BatchTest/testGetBatchFinancialItems/)
[CRM_Batch_Form_EntryTest.testMembershipRenewalDates](https://test.civicrm.org/job/CiviCRM-Core-PR/51385/testReport/junit/(root)/CRM_Batch_Form_EntryTest/testMembershipRenewalDates/)
[CRM_Batch_Form_EntryTest.testProcessMembership with data set #0](https://test.civicrm.org/job/CiviCRM-Core-PR/51385/testReport/junit/(root)/CRM_Batch_Form_EntryTest/testProcessMembership_with_data_set__0/)
[CRM_Batch_Form_EntryTest.testProcessMembership with data set #1](https://test.civicrm.org/job/CiviCRM-Core-PR/51385/testReport/junit/(root)/CRM_Batch_Form_EntryTest/testProcessMembership_with_data_set__1/)
[CRM_Batch_Form_EntryTest.testProcessContribution with data set #0](https://test.civicrm.org/job/CiviCRM-Core-PR/51385/testReport/junit/(root)/CRM_Batch_Form_EntryTest/testProcessContribution_with_data_set__0/)
[CRM_Batch_Form_EntryTest.testProcessContribution with data set #1](https://test.civicrm.org/job/CiviCRM-Core-PR/51385/testReport/junit/(root)/CRM_Batch_Form_EntryTest/testProcessContribution_with_data_set__1/)
[CRM_Contact_BAO_QueryTest.testGetSummaryQueryWithFinancialACLDisabled](https://test.civicrm.org/job/CiviCRM-Core-PR/51385/testReport/junit/(root)/CRM_Contact_BAO_QueryTest/testGetSummaryQueryWithFinancialACLDisabled/)
[CRM_Contact_BAO_QueryTest.testGetSummaryQueryWithFinancialACLEnabled](https://test.civicrm.org/job/CiviCRM-Core-PR/51385/testReport/junit/(root)/CRM_Contact_BAO_QueryTest/testGetSummaryQueryWithFinancialACLEnabled/)

**Comment by JoeMurray** [comment]
Should the following be changed?

1. https://github.com/civicrm/civicrm-core/blob/master/xml/schema/Financial/FinancialTrxn.xml#L168
2. https://github.com/civicrm/civicrm-core/blob/master/xml/schema/Contribute/Contribution.xml#L413

FWIW, I think it makes the codebase confusing and less maintainable to use the _name_ contribution_recur_status as the option group on the contribution_status field, though I am sure you had good reasons to do this.

**Comment by eileenmcnaughton** [comment]
The name should match the option group value - as opposed to the field name - but when using `getKey` or `getName` it is the field name you pass

**Comment by eileenmcnaughton** [comment]
& yep - we should update the comments

**Comment by eileenmcnaughton** [comment]
So the contribution one above shouldn't be changed - that is the correct option group for contributions. The financial trxn one should be & should have it's own option group. However, that group has not yet been created & hadn't previously been on my radar. It's not blocking on this piece of work AFAIK but worth doing.

Note `contribution_recur_status` is an example in the code comment , rather than the only group that might be more appropriate - perhaps that isn't clear. I can revisit the comment

**Comment by eileenmcnaughton** [comment]
Hmm - the little bit of stuff towards this has stalled so I guess the 'big project' has really stalled here. Closing

**Pull request closed without merging**
