### PR TITLE
CRM-17959 - allow URL to be redirected if the queue ID is invalid but…

### PR DESCRIPTION
**Pull request by andrew-cormick-dockery**
… the URL ID is OK

### CODE REVIEW

**Comment by totten** [comment]
jenkins, add to whitelist

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by alifrumin** [comment]
@josephlacey and I are working on this one

**Comment by josephlacey** [comment]
This is working on 4.6 and can be merged, @seamuslee001.  It can be reproduced the same as https://github.com/civicrm/civicrm-core/pull/7728#issuecomment-223785113.

**Comment by josephlacey** [comment]
@eileenmcnaughton

**Pull request merged**
