### PR TITLE
Ornery++

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This flags some particularly slow tests in the apiv3SyntaxConfirmanceTest so they do not run on PR runs. These tests used to be a good little canaries but have grown soft & fat as we improved our code & no longer have the stamina to run several times a day in a timely manner

Before
----------------------------------------
On PRs submitted about the same time
image

image

After
----------------------------------------
On this PR apiv3 time taken

image

& with the second ornery 

image

Technical Details
----------------------------------------
There are a couple of other tests we could do this to but with this change the apiv3 tests are faster than the crm test so there might not be much to gain from further apiv3 test speed improvements

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by colemanw** [comment]
> api_v3_SystemCheckTest::testSystemCheckBasic with data set "APIv3" (3)
Exception: CRM_Core_Exception: "checkDefaultMailbox not in results"

@eileenmcnaughton I suspect the test failure has to do with the component not being enabled. Probably the syntax conformance tests would enable all components & then other tests would just blithely assume they are always enabled.

**Comment by eileenmcnaughton** [comment]
@colemanw that makes sense - I had concluded the test was not improving things as much as I hoped (the screenshots above are not consistent) & that the one that creates the custom data sets might be a bigger win - but then all these tests .....

**Comment by eileenmcnaughton** [comment]
@colemanw I got it!

**Pull request merged**
