### PR TITLE
(NFC) CRM-19323: Advanced search relationship date clause description…

### PR DESCRIPTION
**Pull request by ravi-sharma**
…s are inaccurate.

### CODE REVIEW

**Comment by totten** [comment]
jenkins, ok to test

**Comment by seamuslee001** [comment]
@ravi-sharma Ravi, I think the end date quill was correct in the current code, I.e, if we are searching for end dates from x date it would be on or after x date and the to is on or before. 

Where as for start dates it is start date on or after  x for where there is a value in the from box and the to date should be on or before x date

**Comment by ravi-sharma** [comment]
@seamuslee001 Thanks for the notes, made few adjustments. Could you please check now?

**Comment by seamuslee001** [comment]
Hi @ravi-sharma I have tested and the language looks good, this can be merged in now. @totten

**Pull request merged**
