### PR TITLE
CRM-20144 (NFC) Update tests and example

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @eileenmcnaughton

---

 * [CRM-20144: API contact.get group='x' yields ""DB Error: no such field""](https://issues.civicrm.org/jira/browse/CRM-20144)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Actually @seamuslee001 I think we should keep the tests that we have but change which one calls the document function. i.e we aren't breaking contract on that PARTICULARLY obscure format - but we want the example to come from a sensible one

**Comment by seamuslee001** [comment]
@eileenmcnaughton fixed up

**Comment by eileenmcnaughton** [comment]
perfect

**Comment by twomice** [comment]
Curious: What does "NFC" signify in this PR's title?

**Comment by totten** [comment]
@twomice "NFC" is "Non-Functional Change"; it's mentioned in https://github.com/civicrm/civicrm-core/blob/master/.github/CONTRIBUTING.md . It's a way to flag a change and say "I believe this change is extremely safe."

Changes to docblocks and whitespace are quintessential NFC. The changes to `api/v3/examples` look like NFC. For changes to test-logic, it can be more subjective/debatable whether to use the "NFC" label.  In this particular case, I'm +1 for the change (regardless of whether "NFC" label is on it).

**Comment by twomice** [comment]
Thanks @totten !

**Comment by xurizaemon** [comment]
I was confused by that use of the term too, both since it has an [existing meaning](https://en.wikipedia.org/wiki/NFC), and since it can be read two ways (a change which is nonfunctional (=broken), or a change which has no affect on functionality).

I don't have a better suggestion right now, but I'm in favour of us reducing CiviCRM-specific terminology and preferring terms that are readily familiar to new contributors.

**Pull request merged**
