### PR TITLE
dev/translation#13 Enable users to choose their own language for accessing CiviCRM

### PR DESCRIPTION
**Pull request by aydun**
Overview
----------------------------------------
Users on multilingual sites are able to select their language of choice from the available languages.  Monolingual sites have only been able to set the language for all users.

This change enables users of monolingual sites to select their own language without affecting other users.

The background for this is https://lab.civicrm.org/dev/translation/issues/13  although this implementation has evolved from that suggested in the 'Approach' section.  This replaces PR #12405 

Before
----------------------------------------
In monolingual mode, /admin/setting/localization
screenshot from 2018-12-05 23-40-55

After
----------------------------------------
In monolingual mode, /admin/setting/localization
screenshot from 2018-12-06 12-17-18

Results in Language Switcher block being shown (same as in multilingual mode)
screenshot from 2018-12-06 12-19-23

Technical Details
----------------------------------------
This introduces a new localization setting 'uiLanguages'.  The existing logic for determining the appropriate language in multilingual mode is extended to monolingual (looking at request url, session, uf_match etc).  In line with that, the language switcher block is not shown if the setting 'Inherit CMS Language' is set.  The UI Languages setting on the settings page is not shown in multilingual mode nor when 'Inherit CMS Language' is selected.

There are no (intentional!) changes to multilingual mode

Comments
----------------------------------------
A documentation PR will be provided.

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Test Failure looks related @aydun

**Comment by aydun** [comment]
@seamuslee001 In the test environment, are the l10n files installed?  So does `CRM_Core_I18n::languages()` return all the languages or just `en_US` ?

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
hmm test failure here https://test.civicrm.org/job/CiviCRM-Core-PR/23519/testReport/junit/(root)/CRM_Core_I18n_LocaleTest/testUiLanguages/ still looks to be an issue @aydun maybe FR_CA isn't in the default one

**Comment by seamuslee001** [comment]
ping @mlutfy You might be into this one

**Comment by mlutfy** [comment]
Hi @aydun, this works great! I have only a small superficial request: can you change the string "UI Languages" to "Available Languages"?

When we are in multi-lingual mode, the interface looks like this:

capture d ecran de 2018-12-12 10-03-37

I think the wording should be imitated. "UI" is a geeky term, and "Available languages" does not imply multi-lingual data anyway.

(The "Languages available to users of this installation" doesn't mean anything useful, so I would ignore that string.)

**Comment by aydun** [comment]
Thanks @mlutfy - I've changed "UI Languages" to "Available Languages"

**Comment by mlutfy** [comment]
Great! Seems OK to merge.

**Pull request merged**
