### PR TITLE
dev/translation#30 Move l10n resource dir under private files

### PR DESCRIPTION
**Pull request by ejegg**
Overview
----------------------------------------
Allows the `l10n` directory to be outside of the main codebase, so installing files there doesn't change dirty the contents of a `vendor` directory. Later on, it could be possible to compile customized `*.mo` / `*.po` files to store in that directory.

Before
----------------------------------------
L10n files were always stored at the `[civicrm.root]/l10n`. When CiviCRM was installed via `composer`, installing `l10n` files would mean copying them into the `vendor` directory and making upgrades difficult.

After
----------------------------------------
L10n files can be stored under any of the following, in order of precedence:

* A custom location defined in `$civicrm_paths['civicrm.l10n']['path']`
* A custom location defined in `CIVICRM_L10N_BASEDIR` (for use with `xml/GenCode.php`)
* `[civicrm.private]/l10n` (often equivalent to `[civicrm.files]/l10n`; ex: `sites/default/files/civicrm/l10n`)
* `[civicrm.root]/l10n` (the traditional location)

Technical Details
----------------------------------------
Registers a new `[civicrm.l10n]` variable with \Civi\Paths and adds an `l10nDir` property to config via MagicMerge (probably unnecessary). Gets rid of function-scoped static caching in `I18n::getResourceDir()`. The `civicrm.l10n` factory function consults a `define()` before looking up `civicrm.private so that it can be used in GenCode.

### CODE REVIEW

**Comment by ejegg** [comment]
This is failing because we don't have CIVICRM_TEMPLATE_COMPILEDIR set when running GenCode, and it's used to look up civicrm.private "for backwards compatibility". Would the fix be to explicitly set the civicrm.private path before running GenCode.php? Where would we do that?

**Comment by mlutfy** [comment]
Hi @ejegg, this looks really nice! It seems like your latest commits have fixed the GenCode issue? I will try to test this.

**Comment by nganivet** [comment]
Thanks, that is a great change! I would rather have this directory managed like all others via the settings though through a define. Is there a particular reason to use CIVICRM_L10N_BASEDIR rather than a more classic $civicrm_setting['Directory Preferences']['l10nDir']?

**Comment by totten** [comment]
jenkins, test this please

**Comment by totten** [comment]
I think this is good in its introduction of the `[civicrm.l10n]`.

> ... adds an l10nDir property to config via MagicMerge (probably unnecessary) ...

Agree, my gut says it's not necessary and should be removed. Mainly because it just adds room for ambiguity. (Note: `MagicMerge` was primarily created for backward compatibility, and there are lots of newer things -- in `settings` and in `paths` -- which aren't exposed via `MagicMerge`.) To my eye, there's probably also an issue if you deploy on a basic `en_US` site with read-only source-code. (Specifically, any call to `$config->l10nDir` would try to autocreate the `l10n` dir... but that folder doesn't necessarily, and it's not necessarily writeable, and MagicMerge will complain if mkdir fails.)

> Is there a particular reason to use CIVICRM_L10N_BASEDIR rather than a more classic $civicrm_setting['Directory Preferences']['l10nDir']?

Loading boot-critical information via settings framework can be a bit finnicky.  For example, when `GenCode` creates `civicrm_data.LOCALE.mysql` in a pre-install/pre-boot environment, there is no settings system, no `civicrm_setting` table, and probably no DSN/database. The cases where one tries to make these things work in a pre-install/pre-boot environment can be... mentally challenging.

(On the flipside, IMHO, there's no real value in exposing web UI options for manipulating `l10nDir`.)

Tangentially... it might be possible to replace `CIVICRM_L10N_BASEDIR` with `$civicrm_paths['civicrm.l10n']['path']`, but... if I'm interpreting correctly, the use of the `define()` is actually helping to short-circuit code-paths that would breakdown in `GenCode` context.

I think the `define()` is OK as long as it's clear that it's GenCode-only/internal-only .

**Comment by totten** [comment]
I did some `r-run` testing and also reverted the `MagicMerge::$l10nDir` property (*now pushed up*). And all of these worked fine:

* Run GenCode with default location. Verify that `civicrm_data.fr_FR.mysql` is translated with the given mo data.
* Run GenCode with a custom location (via env-var `CIVICRM_L10N_BASEDIR`). Verify that `civicrm_data.fr_FR.mysql` is translated with the given mo data.
* Open web UI with `fr_FR` as active language - and load data from default location (`[civicrm.root]/l10n`).
* Open web UI with `fr_FR` as active language - and load data from `[civicrm.private]/l10n` (automatic override)
* Open web UI with `fr_FR` as active language - and load data from a custom location (`$civicrm_paths['civicrm.l10n']['path']`).

(*Testing note: When using non-default locations, one wants to see that it actually loads content from the alternate location despite the presence of the traditional folder. You could potentially build custom mo files, but I found it easier to repurpose files from other languages e.g. `cp -R $civicrmRoot/l10n/es_MX $filesRoot/civicrm/l10n/fr_FR`*)

**Comment by totten** [comment]
(*CiviCRM Review Template WORD-1.2*)



* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __Pass__. Seems good. I made a few edits to show the precedence more visually.
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __Pass__: Does not change UI
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __Comment__: The docs have a list of path variables - should be updated to document, but don't need to block this.
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __Pass__: See discussion above.
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __Pass__: It still loads from the same location as normal.
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __Pass__
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __Pass__: The unit-tests provide some coverage over the default case; and, as we add more cases to E2E matrix going forward, I think we'll also get coverage of the non-default case.
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __Comment__: Waiting for new test-run to finish following rebase and small edit

**Pull request merged**
