### PR TITLE
CRM-21157 Convert civicrm_subscription_history.date column to be time…

### PR DESCRIPTION
**Pull request by seamuslee001**
…stamp rather than datetime to help with timezone issues

Overview
----------------------------------------
DateTime mysql columns do not handle timezones well, so lets convert this column for new installs so that timezone issues aren't a problem for group subscription history information

Comments
----------------------------------------
@eileenmcnaughton @totten

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@totten is this enough to trigger your new warning system?

**Comment by seamuslee001** [comment]
@eileenmcnaughton needed to manually add it which i have done now

**Comment by totten** [comment]
Good idea. 

Regarding "System Status" and "Doctor When", those changes should be enough to have the prod the admin to change the data-type. However, I don't think Doctor When will update the default. It probably needs a patch around [here](https://github.com/civicrm/org.civicrm.doctorwhen/blob/0a91833c0143a06602a3a515d07285e2555be195/CRM/DoctorWhen/Cleanups/ConvertTimestamp.php#L20-L23) and [here](https://github.com/civicrm/org.civicrm.doctorwhen/blob/0a91833c0143a06602a3a515d07285e2555be195/CRM/DoctorWhen/Cleanups/ConvertTimestamp.php#L46-L47).

For general QA... ideally, what we'd do is identify the use cases where `SubscriptionHistory`  is create/updated and try them (for old/new sites). After grepping for `SubscriptionHistory` and `civicrm_subscription_history`,  these items in particular stick out:

 * `CRM_Contact_BAO_SubscriptionHistory::create()` seems to be used most of the time
 * `CRM_Contact_BAO_GroupContact::bulkAddContactsToGroup()`
 * `sql/GenerateData.php` 

IMHO, we don't need unit-tests for these things, but someone should give a quick/manual test with use-cases involving them.

**Comment by eileenmcnaughton** [comment]
I tested this on a local install creating a clean build before & after applying this patch. I tested adding an individual contact to a group from their group tab and bulk add & removing contacts from a search & made the following observations

1) test coverage of the function is quite good (numerous tests pass through it) but I couldn't find a specific test that checks the subscription_history & the fact no api exists for it is probably evidence no-one has done one (and the reason I stopped short of adding one this time as it was a bit more than I wanted to do in this review)
2) before the patch the dates were inaccurate on my local, incorrect by 10 hours. After they were correct
3) when doing a bulk remove from a group remove subscription history records are created even if the contact was not in the group to start with.

Conclusion - this does what it says & is an improvement

**Pull request merged**
