### PR TITLE
CiviMail: Fix logic for handling SMTP socket errors, temporary failures and permanent failures

### PR DESCRIPTION
**Pull request by mfb**
Overview
----------------------------------------
Fixes support for sending mail directly to AWS SES via SMTP by detecting additional temporary failure modes.

Before
----------------------------------------
If the AWS account's SES rate limit is exceeded, SES responds with code: 454, response: "Throttling failure: Maximum sending rate exceeded," and CiviMail considers this message to have "bounced."

After
----------------------------------------
CiviMail will interpret non-5xx response not as a bounce, but rather as a temporary failure (logged and skipped). A 5xx response code, on the other hand, will be respected as a permanent failure and message will be considered bounced.

Technical Details
----------------------------------------
This is an extension of the logic provided by https://issues.civicrm.org/jira/browse/CRM-14799 and https://issues.civicrm.org/jira/browse/CRM-9191

### CODE REVIEW

**Comment by mfb** [comment]
We've been running this in production for some time and it's working great, on 3 different mail servers, not just AWS.

**Comment by eileenmcnaughton** [comment]
@mfb I think this makes sense but I think it also warrants a unit test just on that function - ie. giving a few variants of $message and checking the output - should be pretty quick & easy to write with a data provider

**Comment by mfb** [comment]
👍 Sounds good. I actually found a minor bug in this method (also affecting Flexmailer), just pushed a commit to fix it.

By the way, one philosophical aside about this logic:  A 5xx failure in my experience isn't necessarily a "bounce" per se, because this is an error being returned by the mail relay server, not the final destination. It could just be something like the sending account has been suspended, and once that is resolved, the delivery should be reattempted.   So.. in summary, :woman_shrugging: I'm just not 100% sure how to handle all the possible failure scenarios here.. :)

**Comment by eileenmcnaughton** [comment]
@mfb so where you are unsure I would say - keep this change as conservative as you can so it is mergeable and follow up later with the more difficult scenarios. (ie. don't mix changing the hard stuff & the easy stuff in one PR if you can help it or the former with trip up the latter)

**Comment by mfb** [comment]
I can't remove the needs-test label :)

I think this is a good start for test coverage, but if anyone else has SMTP failures from their logs I could add them here.

**Comment by eileenmcnaughton** [comment]
I'm going to merge this - the code looks sensible and well-written & has an appropriate test and this feels like a great starting point for any future tweaks.

As an aside - I think that where we introduce a function with a unit test we should mention that in the comment block to encourage future devs to expand it. Not holding this up on that though

**Pull request merged**
