### PR TITLE
CRM-19453

### PR DESCRIPTION
**Pull request by spalmstr**
This is a repeat of the previous of the same name.  I've recreated the branch having merged it from a new pull of master.
This PR takes note of the comments made about regular expressions.  A different regular expression is only used if the directory separator is \.  The new regular expression matches both \ and /.

---

 * [CRM-19453: System-\>Directories fails to display under Joomla](https://issues.civicrm.org/jira/browse/CRM-19453)

### CODE REVIEW

**Comment by spalmstr** [comment]
I am wondering if it is worth pursuing this PR as it has failed in a completely unrelated area:

CRM_Contact_BAO_ContactType_ContactTest::testCRM19133
Failure in api call for CustomValue create:  DB Error: syntax error
 INSERT INTO civicrm_value_93e0ce3ec8ea569e758321e014145484_1  ( `93e0ce3ec8ea569e758321e014145484_1`,`entity_id` ) VALUES ( 'value 1',1 ) ON DUPLICATE KEY UPDATE 93e0ce3ec8ea569e758321e014145484_1 = 'value 1' [nativecode=1064 ** You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '93e0ce3ec8ea569e758321e014145484_1 = 'value 1'' at line 1]

The PR is not touching contact types.  If no other user is seeing the problem, then I shall simply patch my system at every update.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
That error is intermittant...

**Comment by spalmstr** [comment]
Yet another failure; again it looks completely unrelated:

**Comment by spalmstr** [comment]
api_v3_LoggingTest::testRevertRestrictedTables
Undefined offset: 0

/home/jenkins/buildkit/build/core-9863-63975/sites/all/modules/civicrm/tests/phpunit/api/v3/LoggingTest.php:332
/home/jenkins/buildkit/build/core-9863-63975/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:184
/home/jenkins/buildkit/bin/phpunit4:545

**Comment by spalmstr** [comment]
It passed - that looks hopeful.

**Comment by seamuslee001** [comment]
So my feeling is this If Stephen has tested this on a windows based machine, I can try installing Joomla on a linux vm apply this patch see if anything changes, If anything doesn't change then i think we are ok. thoughts @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
@seamuslee001 yep - if you can do that & we get the commit tidied up then I think it can merge. I note the code really does seem to indicate no change for non-windows users

**Comment by seamuslee001** [comment]
Tested this on a linux VM and appears to have not made any changes to the files and still looks good

**Comment by eileenmcnaughton** [comment]
OK @spalmstr can you work through those rebase instructions to tidy it up & I'll merge

**Comment by spalmstr** [comment]
Thanks - that is a good sign.  I've attempted to follow the instructions, but just when I thought I was beginning to understand Git, I saw some problems!  I did replace the pick commands with s at some point, but ended up having to comment them out. The reason for all the commits was that I couldn't see way of rerunning the test on the PR without doing so.

Here is a console log:

Stephen@JUPITER MINGW64 /d/CiviCRM_Custom.git/joomla/administrator/components/com_civicrm/civicrm (CRM-19453)
$ git fetch -f origin

Stephen@JUPITER MINGW64 /d/CiviCRM_Custom.git/joomla/administrator/components/com_civicrm/civicrm (CRM-19453)
$ git rebase -i origin/master
error: cannot 'squash' without a previous commit
You can fix this with 'git rebase --edit-todo' and then run 'git rebase --continue'.
Or you can abort the rebase with 'git rebase --abort'.

Stephen@JUPITER MINGW64 /d/CiviCRM_Custom.git/joomla/administrator/components/com_civicrm/civicrm (CRM-19453|REBASE-i)
$ git rebase -i origin/master

It seems that there is already a rebase-merge directory, and
I wonder if you are in the middle of another rebase.  If that is the
case, please try
        git rebase (--continue | --abort | --skip)
If that is not the case, please
        rm -fr "D:/CiviCRM_Custom.git/joomla/administrator/components/com_civicrm/civicrm/.git/rebase-merge"
and run me again.  I am stopping in case you still have something
valuable there.

Stephen@JUPITER MINGW64 /d/CiviCRM_Custom.git/joomla/administrator/components/com_civicrm/civicrm (CRM-19453|REBASE-i)
$ git rebase --edit-todo
error: cannot 'squash' without a previous commit
error: unusable instruction sheet: '.git/rebase-merge/git-rebase-todo'
error: cannot 'squash' without a previous commit
error: unusable instruction sheet: '.git/rebase-merge/git-rebase-todo'

Stephen@JUPITER MINGW64 /d/CiviCRM_Custom.git/joomla/administrator/components/com_civicrm/civicrm (CRM-19453|REBASE-i)
$ git rebase --continue
error: cannot 'squash' without a previous commit
error: please fix this using 'git rebase --edit-todo'.

Stephen@JUPITER MINGW64 /d/CiviCRM_Custom.git/joomla/administrator/components/com_civicrm/civicrm (CRM-19453|REBASE-i)
$ git rebase --edit-todo
error: cannot 'squash' without a previous commit
error: unusable instruction sheet: '.git/rebase-merge/git-rebase-todo'
error: cannot 'squash' without a previous commit
error: unusable instruction sheet: '.git/rebase-merge/git-rebase-todo'

Stephen@JUPITER MINGW64 /d/CiviCRM_Custom.git/joomla/administrator/components/com_civicrm/civicrm (CRM-19453|REBASE-i)
$ git commit
fatal: Could not open file .git/rebase-merge/done for reading: No such file or directory

Stephen@JUPITER MINGW64 /d/CiviCRM_Custom.git/joomla/administrator/components/com_civicrm/civicrm (CRM-19453|REBASE-i)
$ git rebase --continue
error: cannot 'squash' without a previous commit
error: please fix this using 'git rebase --edit-todo'.

Stephen@JUPITER MINGW64 /d/CiviCRM_Custom.git/joomla/administrator/components/com_civicrm/civicrm (CRM-19453|REBASE-i)
$ git rebase --edit-todo
error: cannot 'squash' without a previous commit
error: unusable instruction sheet: '.git/rebase-merge/git-rebase-todo'

Stephen@JUPITER MINGW64 /d/CiviCRM_Custom.git/joomla/administrator/components/com_civicrm/civicrm (CRM-19453|REBASE-i)
$ git rebase --edit-todo

Stephen@JUPITER MINGW64 /d/CiviCRM_Custom.git/joomla/administrator/components/com_civicrm/civicrm (CRM-19453|REBASE-i)
$ git rebase --continue
Successfully rebased and updated refs/heads/CRM-19453.

Stephen@JUPITER MINGW64 /d/CiviCRM_Custom.git/joomla/administrator/components/com_civicrm/civicrm (CRM-19453)
$ git push -f
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/spalmstr/civicrm-core.git
 + 38bd875573...7927bd07d9 CRM-19453 -> CRM-19453 (forced update)

Stephen@JUPITER MINGW64 /d/CiviCRM_Custom.git/joomla/administrator/components/com_civicrm/civicrm (CRM-19453)
$

**Comment by eileenmcnaughton** [comment]
hmm - no commits left in the pr....

I think maybe you started trying to squash from the first commit? They squash into the row above so you can't put a 's' on the first row

**Comment by spalmstr** [comment]
Thanks - as I said, I'm still learning more about Git.  There were two pick rows and the instructions didn't say to leave the first one.

**Comment by spalmstr** [comment]
Just recreated the commit.

**Pull request closed without merging**
