### PR TITLE
CRM-20537 Make the case_id, contact_id index on civicrm_case_contact …

### PR DESCRIPTION
**Pull request by seamuslee001**
…unique following check with Coleman

- https://issues.civicrm.org/jira/browse/CRM-20537

### CODE REVIEW

**Comment by seamuslee001** [comment]
ping @colemanw @eileenmcnaughton

**Comment by colemanw** [comment]
@seamuslee001 does this need any kind of upgrade script to fix the index for existing sites? Or does that happen automatically?

**Comment by seamuslee001** [comment]
@colemanw Well @eileen added in a new system of Fixing missing indexes which i think should cover this @eileen any thoughts?

**Comment by eileenmcnaughton** [comment]
I'm not clear whether it will fix them to be unique or not - but I think the system does set a precedent for us ensuring they are correct on new installs & merging that fix, & separately addressing the upgrade portion in the index reconciliation - when there is no functionality change. We might need to add a check that the index uniqueness has not been abused before adding.

**Pull request merged**
