### PR TITLE
CRM-20600 - Upgrader - Display warning if asset-caching is likely to fail

### PR DESCRIPTION
**Pull request by totten**
After releasing v4.7.21, there were several inquiries about sites in which
Angular pages failed to load.  In cases diagnosed so far, this has been a
result of inconsistent configurations or overzealous HTTP restrictions
applied to the `imageUploadDir`.

Ordinarily, we would address this kind of thing with a status check.
Unfortunately, the problem breaks that "Status" page...  so we have to
display a bit sooner.

---

 * [CRM-20600: Expose AngularJS screens to hooks](https://issues.civicrm.org/jira/browse/CRM-20600)

### CODE REVIEW

**Review by seamuslee001 — APPROVED** [review]
This looks fine to me @totten thoughts @eileenmcnaughton

**Comment by totten** [comment]
Reviewed by Seamus.

Locally tested on D7 for 4.7.20=>4.7.22 with each permutation of:
 * __Upgraders__: 
   * Web-based upgrade
   * drush-based upgrade
 * __Configurations__: 
   * Default (with matched `imageUploadDir`/`imageUploadURL`)
   * Misconfigured (with `civicrm.settings.php` overriding `imageUploadURL` to use garbage)

**Comment by herbdool** [comment]
I've got this problem on Pantheon even when imageUploadDir and imageUploadURL match.

I'm trying to figure out why.

**Comment by herbdool** [comment]
For now I'm disabling CSS/JS caching until we can figure this out.

**Comment by herbdool** [comment]
@totten Is there a way to disable asset caching in civicrm.settings.php or is it just in the GUI?

**Comment by seamuslee001** [comment]
@herbdool probably depends on who is doing the caching, if its a setting in CiviCRM GUI that your altering then yes you would access it by i think 

```
global $civicrm_setting
$civicrm_setting['setting_name'] = value;
``` 
I think tho @totten will know most

**Comment by totten** [comment]
1. See https://wiki.civicrm.org/confluence/display/CRMDOC/Override+CiviCRM+Settings . Specifically, I'd expect it to look like `$civicrm_setting['domain']['assetCache'] = 0;`

2. I vaguely recall Pantheon has some special kind of distributed filesystem. Propagation-delays or dirty-reads could be problematic.

3. Not necessarily encouraging this, but it might be OK to either:

 * Update the messaging/prose to point out that "Asset Caching" is toggleable.
 * Flip the default behavior to disabled (opt-in rather than opt-out), and then use a 'status' check to suggest a opting in.

**Comment by herbdool** [comment]
@totten thanks.

2. Pantheon has a "load balancer" but only for the production environments of professional plans and higher. This means that the "bindings" can change and point to the alternate filesystem if the load needs to be distributed. But I was getting this error on the dev environment too so I think it may require something like the [civicrm.files], [civicrm.private] patch I was working on.

3. Opt-in might be safer. I'm not sure how many sites are having this issue.

4. Is there a way to get it to regenerate the cached file? By clearing the main Civi cache? Does it regenerate when toggling on/off/on?

**Comment by herbdool** [comment]
@totten and one final question: does it regenerate the cached file if it can't find it?

**Comment by herbdool** [comment]
I can get it working if I manually rename and upload the angular js and json files from a site where it was working. But I can't seem to get it to regenerate the files on its own.

**Comment by totten** [comment]
Basically, it does a lazy-build -- the first time you need the file, it creates it. More discussion in https://docs.civicrm.org/dev/en/master/framework/asset-builder/

Whenever you visit an Angular page, it computes a digest code that becomes part of a filename (`XXXX` in `angular-modules.XXXX.js`). If the file `angular-modules.XXXX.js` doesn't exist, then it creates it. 
 * You can force it to regenerate by doing a general system flush (e.g. `drush cvapi system.flush` or `cv flush`). This changes the `XXXX`.
 * Generally, any change that affects `XXXX` will cause a new build. The main values that feed into `XXXX` are [here](https://github.com/civicrm/civicrm-core/blob/4.7.22/Civi/Core/AssetBuilder.php#L259-L262) and [here](https://github.com/civicrm/civicrm-core/blob/4.7.22/CRM/Core/Config/Runtime.php#L176-L182). (Of note... the `cacheCode` is a value that changes whenever you do a general system flush.)

The specific functions which cause it to build are:
 * [AssetBuilder::getUrl()](https://github.com/civicrm/civicrm-core/blob/4.7.22/Civi/Core/AssetBuilder.php#L124)
 * ... which calls [AssetBuilder::build()](https://github.com/civicrm/civicrm-core/blob/4.7.22/Civi/Core/AssetBuilder.php#L142)
 * ... which calls `file_exists()`

**Comment by herbdool** [comment]
I tried to recreate the issue on a fresh CiviCRM install on Pantheon and couldn't so that's good news. I had thought this might require the PR here https://github.com/civicrm/civicrm-core/pull/10513 but doesn't make a difference--so long as ImageUploadDir/URL are not set to the ~/files/private/civicrm (though there are other good reasons for that PR)

Sorry for distraction. But big thanks for your help.

**Pull request merged**
