### PR TITLE
CRM-19453

### PR DESCRIPTION
**Pull request by spalmstr**
This is a recreation of a failed PR.  The PR is to solve a problem with Windows installations by using a constant in the system rather than attempting to edit a file path to determine the site root.  Under Windows the latter operation fails because the directory separator is a backslash not a forward slash.

---

 * [CRM-19453: System-\>Directories fails to display under Joomla](https://issues.civicrm.org/jira/browse/CRM-19453)

### CODE REVIEW

**Comment by spalmstr** [comment]
Yet another failure with:
No report files were found. Configuration error?
What should the configuration be?

**Comment by seamuslee001** [comment]
@spalmstr Stephen you need to rebase against the current master 

Do the following git fetch <upstream repo alias>
when on this branch do git rebase -i <upstream repo alias>/master 
If at any time the rebase stops and says there is an error do git mergetool and look for lines that start with <<< and fix them down to lines >>> 
Once you have fixed the errors do git rebase --continue 

One the rebase has fully finished do git push <your repo alias> CRM-19453 -f

**Comment by jitendrapurohit** [comment]
@spalmstr You can find step by step procedure here - https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

**Comment by spalmstr** [comment]
Closing and recreating.

**Comment by spalmstr** [comment]
Hi Jitendra,

 

Many thanks for your help with this and link to the step-by-step instructions.  I tried rebasing my local master on civicrm/civicrm-core and pushing it to my local fork.  The core and fork master branches still did not align so I ended up deleting my fork and recreating it and then cloning it locally before creating the CRM-19453 branch making the change again.  I confess to finding the PR process very frustrating – it took a few minutes once I knew the file to change to make the correction, and it has taken days to get the PR submission to work.  I am still learning about the intricacies of Git.

 

There may still be issues with the principle involved in the change; if so, I apologise.  I am still climbing the CiviCRM learning curve.

**Pull request closed without merging**
