### PR TITLE
CRM-16716 -- Filter with recur contribution status and modified date …

### PR DESCRIPTION
**Pull request by jitendrapurohit**
…for `Last Contribution Processed` date filter https://issues.civicrm.org/jira/browse/CRM-16716

### CODE REVIEW

**Comment by davecivicrm** [comment]
Next Scheduled Contrib Date filter still not working for me with this patch applied. Details on JIRA.

**Comment by jitendrapurohit** [comment]
jenkins, test this please

**Comment by jitendrapurohit** [comment]
jenkins, test this please

**Comment by davecivicrm** [comment]
Test failure unrelated.

**Pull request merged**
