### PR TITLE
Add APIv4 Pledge Autocomplete

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes [dev/core#4131](https://lab.civicrm.org/dev/core/-/issues/4131)

Similar fix to #25485

image

### CODE REVIEW

**Comment by seamuslee001** [comment]
@colemanw should this be against the 5.59 RC branch?

**Comment by colemanw** [comment]
@seamuslee001 changed to 5.59

**Comment by colemanw** [comment]
Test failure appears to be unrelated

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Pull request merged**
