### PR TITLE
dev/core#1400 Users with 'view own cases' permission can't open resolved cases

### PR DESCRIPTION
**Pull request by kainuk**
Overview
----------------------------------------
The discussion about this PR is found in issue https://lab.civicrm.org/dev/core/-/issues/1400.
Steps to reproduce in https://lab.civicrm.org/dev/core/-/issues/2409 .
The discussion is still open but for some organisations this creates a real problem. They can use this PR.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Thanks @kainuk have added https://github.com/civicrm/civicrm-core/pull/19674 and then followup https://github.com/civicrm/civicrm-core/pull/19675 to address the change this causes for dashlets.

jenkins retest this please.

**Comment by eileenmcnaughton** [comment]
So my take on what is going on is that you think this should be merged @demeritcowboy and then you would like @kainuk to review your 2 follow ups - if that is the case can you confirm & @kainuk can you remove WIP?

**Comment by demeritcowboy** [comment]
While I'd like to find out what changed to cause this problem, removing 'any' appears to be a way to fix the problem that only seems to affect the dashlets, and in any case (double pun) there doesn't seem to be a reason for 'any' to be in this line (i.e. semantically why would asking for type='any' add a restriction).

I do have one hesitation in that the My Cases dashlet has other problems, but that's both before and after this, it just might be a clue as to the real problem.

**Comment by demeritcowboy** [comment]
In my testing this goes back **much** farther than 5.12 as indicated in the ticket, and even predates the dashlet(?!) So yes I think can remove WIP here and it's mergeable and dashlet problems are something completely different.

**Comment by eileenmcnaughton** [comment]
OK - done

**Comment by demeritcowboy** [comment]
Thanks

**Pull request merged**
