### PR TITLE
[REF] Move clone template functionality from api to bao

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Moves code block from one place to another, for better reusability in api4.

Before
----------------------------------------
Code in api.

After
----------------------------------------
Code in bao.

### CODE REVIEW

**Comment by mlutfy** [comment]
Test fail seems unrelated?

```
CRM_Member_BAO_MembershipTest::testRenewMembership
Verify correct end date is calculated after membership renewal
Failed asserting that two strings are equal.
```

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by colemanw** [comment]
@mlutfy that looks to be a recent regression in core, I'm seeing it on a number of PRs. So other than that, this PR is passing tests.

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
@mlutfy was that a "merge on pass" endorsement?

**Comment by mlutfy** [comment]
I don't always feel like the most qualified for this kind of PR, but considering you are the one who initially added this code in the API, and it makes sense to have it in the BAO instead, merge on pass! :)

**Comment by colemanw** [comment]
retest this please

**Comment by eileenmcnaughton** [comment]
test this please

**Pull request merged**
