### PR TITLE
CRM 18406 When a contribution is edited it doesn't update the activity to match

### PR DESCRIPTION
**Pull request by joseph-t-martin**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Cool - do you think you could pull that bit of code into a separate function? The function is already obscenely long so it would be good not to add to it's length. I also really like short functions with self-documenting names & the comment block on them is an obvious place to explain the rationale & link to the issue if appropriate

**Comment by andrewperry** [comment]
Nice work @joeyisking and thanks @eileenmcnaughton for suggestion! @joeyisking is there an existing update activity method that all the fields could be passed to for a single update rather than recursing through them?  There must be somewhere, since you can update an Activity through the UI, but my quick look through CRM_Activity_BAO_Activity didn't pick it.

**Comment by eileenmcnaughton** [comment]
Oh yeah - I didn't look at that - probably better to just call the create.activity api - that way you can be sure the hooks are called

**Comment by rohankatkar** [comment]
@joeyisking , I think, instead of writing separate function including API to update just a subject for contribution activity, I'll suggest you to make changes at, https://github.com/civicrm/civicrm-core/blob/master/CRM/Contribute/BAO/Contribution.php#L552,  where activity is getting updated for contribution.

Please check, https://github.com/civicrm/civicrm-core/blob/master/CRM/Activity/BAO/Activity.php#L1858-L1861. Here stuff for activity subject is  already done.

I have attached a patch file with my changes on JIRA ticket https://issues.civicrm.org/jira/browse/CRM-18406. Can you please take a look at my patch? I have tested the patch with your scenario. 

And let me know whether attached patch works in your case?

**Comment by monishdeb** [comment]
Closing in favour of https://github.com/civicrm/civicrm-core/pull/8384

**Pull request closed without merging**
