### PR TITLE
dev/event#19 remove obsolete scriptFee & scriptArray

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Removes unused parameters scriptFee & scriptArray

https://lab.civicrm.org/dev/event/issues/19#note_25984

Before
----------------------------------------
They exist

After
----------------------------------------
Unicorns are real 

Technical Details
----------------------------------------
Both @mattwire & myself determined these are obsolete, unused parameters, removing

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by yashodha** [comment]
@eileenmcnaughton looks right and confirm that variables are obsolete.

**Comment by eileenmcnaughton** [comment]
thanks @yashodha good to have less cruft causing confusion

**Pull request merged**
