### PR TITLE
Adopts to latest When package

### PR DESCRIPTION
**Pull request by agileware-pengyi**
Overview
----------------------------------------
Adopts to the latest `When` package. The current bundled `When` package may generate wrong recurring dates. This PR is just an idea for updating the dependencies and requires the `When` package updated first.

For example:
setting
result

Before
----------------------------------------
Wrong recurring dates in some cases.

After
----------------------------------------
Correct dates with the above settings.

Comments
----------------------------------------
Any testing required for this one?

Agileware ref: CIVICRM-1223

### CODE REVIEW

**Comment by agileware-pengyi** [comment]
@seamuslee001 this is the one I mentioned. Thanks.

**Comment by seamuslee001** [comment]
@agileware-pengyi is there an associated PR for packages should we be looking at getting this in composer?

**Comment by agileware-pengyi** [comment]
@seamuslee001 I just submitted the [PR](https://github.com/civicrm/civicrm-packages/pull/260). Not sure how to work with the composer here.

**Comment by eileenmcnaughton** [comment]
@agileware-pengyi this will need to be against master branch

**Comment by agileware-pengyi** [comment]
@eileenmcnaughton thanks. Will do if this is acceptable.

**Comment by totten** [comment]
>(Seamus) @agileware-pengyi is there an associated PR for packages should we be looking at getting this in composer?
>
> (Pengyi) @seamuslee001 I just submitted the PR. Not sure how to work with the composer here.

Right, as Seamus indicates, there is a choice here to (a) do the upgrade within `civicrm-packages.git` or (b) migrate to `composer.json` at the same time as doing an upgrade.

There's fairly limited guidance about this. The file `VERSIONS.php` has some docs, and I've added a [PR](https://github.com/civicrm/civicrm-packages/pull/261) to talk more about `composer.json` migration. See e.g. [revised VERSIONS.php with PR](https://github.com/totten/civicrm-packages/blob/master-versions/VERSIONS.php).

Either technique is acceptable, but migrating is better in the long-term (involves more upfront risk/time; but going forward, it provides simpler workflow on upgrades and provides better visibility into pkg mgmt).

**Comment by totten** [comment]
For `RecurringEntity` BAO changes, it might be good to ping @deepak-srivastava and give a few days to see if he has any thoughts.

**Comment by seamuslee001** [comment]
It should also be noted that we can't use the When package v3.x because they specify PHP7.1 in their composer.json so you either target master branch with a specific commit before they switched to PHP7.1 or do as Pengyi is doing.

**Comment by eileenmcnaughton** [comment]
Superceded by https://github.com/civicrm/civicrm-core/pull/15223

**Pull request closed without merging**
