### PR TITLE
CRM-19385 - Remove id column from cache tables (rebased)

### PR DESCRIPTION
**Pull request by colemanw**
* [CRM-19385: Look at REMOVING id column from cache tables](https://issues.civicrm.org/jira/browse/CRM-19385)

### CODE REVIEW

**Comment by wdgordon** [comment]
Hi, we have tested this and we found a couple of issues when we removed the id in civicrm_prevnext_cache - the problem seemed to be prevNextCache.php with the function getSelection, and also Query.php with the function getCachedContacts. We tried changing these, but weren't 100% sure of the logic so thought it would be better for you to take a look.

**Comment by colemanw** [comment]
Can you please give more details about the problems you encountered?

**Comment by bhahumanists** [comment]
Both of the functions reference the now-removed id column. 

Core/BAO/PrevNextCache.php - getSelection()
Contact/BAO/Query.php - getCachedContacts()

**Comment by colemanw** [comment]
I have updated the PR. Can you please retest @wdgordon and @bhahumanists

**Comment by bhahumanists** [comment]
There's one more reference in Query.php/getCachedContacts() - the $groupByCol includes pnc.id.

I removed that, dropped the fields and it's all currently all running fine so far.

**Comment by colemanw** [comment]
Ok I've fixed that last reference.

What I'm still not clear about is whether this change actually improves performance. Has anyone found evidence that it does?

**Comment by eileenmcnaughton** [comment]
unrelated test failure.

**Comment by eileenmcnaughton** [comment]
NB @colemanw all the changes except dropping the ids stand alone from the actual dropping of the ids so we could get those merged & rebase.

I think the logic for why this would help is fairly strong, however, it's hard to prove it on multiple sites because each site has  a variant of the issue

**Comment by bhahumanists** [comment]
fwiw I'm trying to get metrics on this. I have a count of the deadlocks in the last week. I'll revert the patch and see how many I get in the next week.

**Comment by eileenmcnaughton** [comment]
@bhahumanists so, to clarify, you have had this patch deployed & the relevant columns dropped from the tables in production for a week?

**Comment by bhahumanists** [comment]
@eileenmcnaughton yep, that's right. No problems with the patch specifically, other than _maybe_ groups loading a little more slowly - but that's so placebo it's hard to be sure. Trying to get metrics on that too.

**Comment by eileenmcnaughton** [comment]
I've added a separate PR with all the non-db changes on this so we can get that merged outside the stale-inducing DB changes

FWIW I think we should fix & merge the db changes on the basis
1) we know that the autoincrement is specifically implicated in SOME KINDS of deadlocks
2) we know that changing the way those insert deadlocks work (converting the table to memory) makes a big difference 
3) we have a real problem with people reporting on changes on deadlocks because there are different kinds of deadlocks in play & most sites are not distinguishing between the different types.
4) in separate work, with reported excellent results, we have a not-yet-ready-for-review PR that changes the civicrm_acl_contact_cache to no longer had an id primary key, so this provides a step towards that.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I don't suppose you managed to trial removing these id primary keys at all?

**Comment by bhahumanists** [comment]
So after trialling this:

--there is no speed difference
--my initial data suggests it didn't reduce the number of deadlocks significantly for us
--the pr as is breaks ordering and sorting in smart groups (presumably because of changes in CRM/Contact/BAO/Query.php)

**Comment by colemanw** [comment]
Not promising.

**Comment by eileenmcnaughton** [comment]
no - the part that has the regression was the part I merged so I will review

- the problem with the analysis is that this will help with deadlocks with a particular cause - and so far we don't know if that cause was affecting @bhahumanists

**Comment by eileenmcnaughton** [comment]
I tested & failed to replicate the regression so need more info. It will have been in the merged part

**Pull request closed without merging**
