### PR TITLE
Menubar z-index fixes

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes an issue where modal dialogs can be obscured by the CiviCRM menu.

Before
----------------------------------------
Dialog opens behind menubar

After
----------------------------------------
Dialog stays below the menubar

Technical Details
----------------------------------------
Also introduces a new css body class `ui-dialog-open` to make it easier to move things out of the way of open dialogs.

### CODE REVIEW

**Comment by kcristiano** [comment]
@colemanw I tried to apply the patch but am getting errors.   I've tried directly applying to master and with `--patch` option via buildkit 

```
git apply --check ~/Downloads/14067.patch
error: patch failed: js/Common.js:927
error: js/Common.js: patch does not apply
error: patch failed: js/Common.js:944
error: js/Common.js: patch does not apply
error: patch failed: js/crm.ajax.js:572
error: js/crm.ajax.js: patch does not apply
error: patch failed: css/crm-menubar.css:240
error: css/crm-menubar.css: patch does not apply
error: patch failed: CRM/Utils/System/Drupal.php:861
error: CRM/Utils/System/Drupal.php: patch does not apply
error: js/crm.drupal7.js: No such file or directory
```

Am I doing it wrong?

**Comment by colemanw** [comment]
@kcristiano that log output suggests that you have checked out a branch in git with the patch already applied. Notice the last line says `js/crm.drupal7.js: No such file or directory` - well this PR deletes that file, so if it's already deleted then I think you've got the patch applied already.

**Comment by colemanw** [comment]
@kcristiano update - I think part of this PR accidentally got prematurely merged into the 5.13 branch. Whoops. That's why your patch does not apply. I've rebased this PR and now the patch is much smaller.

So essentially this PR has already been merged, except for the last two commits which were just cleanup. That's not a disaster, we just need to get it reviewed and approved before the 5.13 release (and if there are problems then we'd have to revert it).

**Comment by kcristiano** [comment]
@colemanw You are correct the removal of `js/crm.drupal7.js` is in 5.13.  https://github.com/civicrm/civicrm-core/commits/5.13 shows `de8d1a877605a975fc534bd3af252f92cc11a9fa` was committed 2 days ago.   

If I checkout to `9e50980ef47ac918b2342059ecd52dbccb68551f` I can apply the patch, but if I checkout 5.13 at `d1c5a34c937988e99af7cdde6cd9ba63281c89b9`  the patch doesn't apply as it's already in 5.13.

But how can that be if the PR is open?

**Comment by kcristiano** [comment]
I now see your comment and I have been able to apply the patch and will report back after testing

**Comment by kcristiano** [comment]
@coleman Tested on WP and Drupal 7.   This fix  does solve the issue.  I tested on laptop and desktop.

This looks good to merge.

**Pull request merged**
