### PR TITLE
CRM-20870: CiviCRM API - Membership get with join on Contact with Group parameter returns incorrect results. Group parameter is ignored

### PR DESCRIPTION
**Pull request by monishdeb**
* [CRM-20870: SUP-1808 CiviCRM API - Membership get with join on Contact with Group parameter returns incorrect results. Group parameter is ignored](https://issues.civicrm.org/jira/browse/CRM-20870)

### CODE REVIEW

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by agilewarealok** [comment]
Hey @monishdeb ,

I've extended this PR to support filtering on Country and State. Created new PR by merging commits from this PR and my mine. https://github.com/civicrm/civicrm-core/pull/11144

Unit tests has been written for the same.

**Comment by monishdeb** [comment]
@agilewarealok great, the question is there are lots of other contact fields which do not work well with membership.get API as a filter, so should we keep adding support for those filters? or to find a general fix to support all contact related filters which aren't working. I tried to find a solution for later but without any success. 

@colemanw / @eileenmcnaughton can you review and merge this PR

**Comment by agilewarealok** [comment]
@monishdeb 
That's correct. adding individual fields will be less maintainable. We have to find a general fix which supports all contact fields.

**Comment by JoeMurray** [comment]
I'd prefer to have more smaller, more self-contained PRs, @agilewarealok . Can you reroll your separate enhancement and add a comment that it is dependent on this one (if it is)? Thx.

**Comment by colemanw** [comment]
Here's what I'd like to see:

- At a lower-than-this level, make a list of contact pseudo-fields which are supported by api.Contact.get but are not real columns on the civicrm_contact table.
- Whenever any entity joins on contact (not just Membership), check for the presence of those fields and call contact.get api to perform the necessary special handling. Pass the ids retrieved by that get call as a filter to limit the results.

Tim did something similar at the api wrapper level (not necessarily the right place to add this in core, but this was from an extension). He added a special param called `case_filter` and then called the case api when filtering activities by case params. IMO we ought to just parse out parms using the dot notation instead of adding a special extra param so that the api syntax works like normal. But the way he called the case api and then passed in the ids to the parent api call is a good model to work from here. It allows the contact api to do the heavy lifting for us:

https://github.com/civicrm/org.civicrm.civicase/blob/master/CRM/Civicase/ActivityFilter.php#L53-L58

@monishdeb ping me if you want to discuss further.

**Comment by jusfreeman** [comment]
We've got two PRs here basically trying to solve the same problem (which by the way was requested & solved in July).

As I see it either:

- #10684 needs to be updated, based on the feedback and then (fingers crossed) merged OR
- #11144 gets reviewed and merged

So who is going to do this **work** ? @monishdeb @JoeMurray 
And who will then **merge** the PR? @eileenmcnaughton @colemanw 

The current situation needs to be fixed, Membership API capabilities right now are very limited.

**Comment by monishdeb** [comment]
@jusfreeman I'll find a generic fix as per @colemanw suggestion, but I am afraid this will take some time (try to wrap up on/before next friday) because I got some other open PRs of mine in priority which I need to work and get them merged into core at earliest. Will that be ok?

**Comment by jusfreeman** [comment]
> I'll find a generic fix as per @colemanw suggestion, and that fix will also include the solution for CRM-20977, so #11144 won't be required then. But I am afraid this will take some time (will try to complete on/before next friday) as I got some other open PRs of mine in priority. Will that be ok?

@monishdeb thanks very much, greatly appreciated. Just want to ensure we get this one closed and merged.

**Comment by colemanw** [comment]
Closing both in anticipation of Monish's generic fix.

**Comment by jusfreeman** [comment]
Hi @monishdeb, just wondering if there is a new PR yet which provides this functionality?

I am concerned that there was a lot of time, effort, money invested in this PR and would like to see this investment realised.

If you have not had time to develop the new PR, then I would like to suggest just re-opening and merging this one so we can get the required features in place. Someone can refactor at a later date.

**Comment by jusfreeman** [comment]
@colemanw any objections to re-opening this PR since nothing better has materialised.

Better to have an imperfect solution than no solution at all.

**Comment by eileenmcnaughton** [comment]
OK - so wrt the api here are the criteria I think are important

1) there is a unit test
2) the signature for the function call is 'correct'
3) it has no adverse effects

If the fix is imperfect then I think that it should also be spammed with comments to indicate this - in this case that seems to be the case. However, I'm not opposed to getting this through in advance of a more generic fix providing the syntax to call the api is consistent with what the final syntax would be & the functionality is consistent with our general api principles. In this case I haven't looked carefully enough to ascertain the syntax but that would be a good thing to add to the PR description.

With regards to closing & re-opening PRs - I would like us to do both more freely. ie there are a lot of PRs that are never going to progress and that suck time just by being there. I would personally love to close ALL PRs older than 1 month - on the clear understanding that people should go ahead and re-open them if appropriate. Anyway that's a long way of saying I think it's always OK to re-open a PR if the code is still valid & should be under active consideration

**Comment by monishdeb** [comment]
@jusfreeman I am afraid, I won't be able to work on this until next week, as I got some priority tasks on my plate which I need to wrap up first :(  Reason why I am creating a new PR on this patch as I can't reopen this PR since the branch is deleted. Or alternatively I would suggest to bring these changes in a extension for the time being until my I submit a new PR with the generic fix?

 @JoeMurray

**Comment by colemanw** [comment]
Thanks for the update Monish. Since you can work on it soon I'm in favor of waiting. A generic fix would be about 100 times more effective since it will cover many fields in all apis, not just 1 field in 1 api.

**Comment by JoeMurray** [comment]
Actually, we've long since spent the fixed budget on this (Justin is funding) and I think Justin would like the simpler, already working solution rather than the one proposed that we'd need him to help fund.

**Comment by jusfreeman** [comment]
@eileenmcnaughton can you please re-open this PR, I know it's not perfect - but it solves a real world problem and no one else has stepped up to fund or develop a generic fix.

For perspective, work on solving this problem started in July 2017. It's now Feb 2018 and the problem still exists in CiviCRM today :(

**Pull request closed without merging**
