### PR TITLE
CRM-18332 - Logging report - Extract methods storeDB() & revert()

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
- [CRM-18332: Make logging.revert accessible from the api & tested](https://issues.civicrm.org/jira/browse/CRM-18332)

### CODE REVIEW

**Comment by totten** [comment]
Agree this is a tidy-up and seems reasonable to extract this bits.

Nitpicks on style:
 * When first reading, I saw code changes and thought, "That doesn't look like NFC!" But if it was based on a safe refactoring (like PHPStorm's "Extract Method"), then the description makes more sense.
 * Took a moment to figure out what the change was. In naming commit/PR, something like this might be more descriptive `CRM-18332 - Logging report - Extract methods loadDB() & revert()`
 * The name `setDB()` feels misleading since it doesn't accept the DB as an input. Again, `loadDB()` or `pickDB()` might make more sense.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
NB this has been edited in discussion with review with Tim & so adding merge on pass to it. The PR is included in other PRs which I will rebase on it.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by totten** [comment]
QA notes: Carefully read code to see if the 'extract method' was safe -- i.e. ensuring that each symbol/variable/function would have the same meaning in its new context.

**Pull request merged**
