### PR TITLE
CRM-17283 Allow for searching on partcipant registration date

### PR DESCRIPTION
**Pull request by seamuslee001**
- [CRM-17283: Add in ability to search on Participant Registration Date](https://issues.civicrm.org/jira/browse/CRM-17283)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@davecivicrm Dave, I know this is a new feature, will need to be re-branched against master after the branching for 4.7. But I'll probably be useful to get feedback in the meantime on the idea / Code Review. As i mentioned in the ticket i think this is sound for backport and have tested against 4.6 code and seems happy

**Comment by colemanw** [comment]
This is already against master so no need to resubmit. We just need to wait until the 4.7 branch has been created before merging.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by davecivicrm** [comment]
@seamuslee001 We think this is a really useful feature, the commits look good, and I did some manual testing w/ the patch and it works as expected. Given that the Registration Date column has always been included in (and the default sort for) the search results - we're pushing this into 4.7. Thanks!

**Pull request merged**
