### PR TITLE
CRM-19133 Unassigning contact subtype for a custom group causes data loss

### PR DESCRIPTION
**Pull request by francescbassas**
I think this patch solves the problem. Or at least it works for me.

### CODE REVIEW

**Comment by totten** [comment]
jenkins, add to whitelist

**Comment by monishdeb** [comment]
Taking for QA

**Comment by monishdeb** [comment]
@francescbassas there are some style warnings related to this PR. See the related test build https://test.civicrm.org/job/CiviCRM-Core-PR/10871/ you need to fix these.

**Comment by monishdeb** [comment]
@francescbassas you also need to change the message here https://github.com/civicrm/civicrm-core/blob/master/templates/CRM/Contact/Form/Contact.tpl#L240. You will get this message when you remove a subtype on Edit Individual form.

**Comment by monishdeb** [comment]
I have added unit test for the changes. Here's my PR https://github.com/civicrm/civicrm-core/pull/8772

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by monishdeb** [comment]
Jenkin test this please

**Pull request merged**
