### PR TITLE
Resolve Issue with Payment Allocation to Contribution Line Item 

### PR DESCRIPTION
**Pull request by olayiwola-compucorp**
Overview
----------------------------------------
This pull request addresses an issue where incorrect amounts were allocated to contribution line items during payment processing. 

Considering the contribution entity table provided:

| Line   | Price | Quantity | Subtotal exc Tax | Tax  | Tax total | Total inc Tax |
|--------|-------|----------|------------------|------|-----------|---------------|
| Line 1 | 100   | 1        | 100              | 0%   | 0         | 100           |
| Line 2 | 200   | 1        | 200              | 0%   | 0         | 200           |
| Line 3 | 300   | 1        | 300              | 20%  | 60        | 360           |
| Total  |       |          |                  |      |           | 660           |

Before
----------------------------------------

Before this PR, the following EntityFinancialTrxn was created:

|            | Subtotal exc Tax | Payment 1 (200) | Payment 2 (200)  | Payment 3 (200) |
|------------|-------------------|-----------------------------------------------|-----------------------------------------------|-----------------------------------------------|
| Line 1     | 100               | 30.30                                         | 30.30                                         | 30.30                                         |
| Line 2     | 200               | 60.61                                         | 60.60                                         | 60.60                                         |
| **Line 3**     | **300**               | **90.91**                                         | **83.00**                                         | **69.02**                                         |
| Tax line 1 | 0                 | 0.00                                          | 0.00                                          | 0.00                                          |
| Tax line 2 | 0                 | 0.00                                          | 0.00                                          | 0.00                                          |
| Tax line 3 | 60                | 18.18                                         | 18.18                                         | 18.18                                         |
| Total      | 660               | 200.00                                        | 192.08                                        | 178.10                                        |

From this table, it's evident that incorrect amounts are assigned to line item 3 following the initial payment.

After
----------------------------------------

After this PR, the following EntityFinancialTrxn is created:

|            | Subtotal exc Tax | Payment 1 (200) | Payment 2 (200) | Payment 3 (200) |
|------------|-------------------|-----------------------------------------------|-----------------------------------------------|-----------------------------------------------|
| Line 1     | 100               | 30.30                                         | 30.30                                         | 30.30                                         |
| Line 2     | 200               | 60.61                                         | 60.61                                         | 60.61                                         |
| **Line 3**     | **300**               | **90.91**                                         | **90.91**                                         | **90.91**                                         |
| Tax line 1 | 0                 | 0.00                                          | 0.00                                          | 0.00                                          |
| Tax line 2 | 0                 | 0.00                                          | 0.00                                          | 0.00                                          |
| Tax line 3 | 60                | 18.18                                         | 18.18                                         | 18.18                                         |
| Total      | 660               | 200.00                                        | 200.00                                        | 200.00                                        |

Line Item 3 now receives the accurate allocation with subsequent payments.

Replication Step
----------------------------------------
- Create a pending contribution with a tax line item (maybe 100 + tax 20)
- Make the first partial payment (maybe 60) - Check that the EntityFinancialTrxns created for the payment has the correct total
- Make the second partial payment (maybe 30) - Check that the EntityFinancialTrxns created for the payment has an incorrect total

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I just dug back into this code & remembered a bit of what is going on that sucks....

`getPayableItems()` returns an array of `lineItems` but what we need is an array of `financialItems` so this bit of code melds them together - argh. So in my code was a refactor to not do that - but the whole thing got way to big - I'd like to have another go at refactoring it tho cos it's super confusing working with LineItems & then trying to map them to financial items. Maybe I can find a smallish baby step?

image


My misgivings on this PR are introducing the rounding - it might be the right thing but in the past we have removed or added rounding  & it feels like someone always claims the new behaviour is a regression. I'm also not sure about the 'left over allocation' part but I don't have my head in it enough to be sure on that

**Comment by eileenmcnaughton** [comment]
OK - this is a baby-step on trying to make it less insane https://github.com/civicrm/civicrm-core/pull/29893

**Comment by eileenmcnaughton** [comment]
Just an update - I've done a series of small refactors that move the code to a saner place without changing the actual calculation - I've gotten it to the point where all payable Items are calculated in getPayableItems - including the sales one. I'm going to do a couple more passes to try to make the arrays a little saner & then worry about the actual fix.

**Comment by olayiwola-compucorp** [comment]
Thanks, @eileenmcnaughton for the update.

**Comment by eileenmcnaughton** [comment]
@omarabuhussein @jamienovick talking with CT today we agreed to merge my riff on your work today so that it hit 5.74 rc (the same release as the refactors I already did to support it) - can you please give master / the rc a spin & let me know how you go & if we need to make further changes

**Comment by omarabuhussein** [comment]
@olayiwola-compucorp ^

**Comment by eileenmcnaughton** [comment]
I guess there just aren't that many people in our community with names beginning with O so perhaps somewhere in there there is an excuse for my mix up

**Comment by omarabuhussein** [comment]
it is okay, don't worry about it :)

**Pull request closed without merging**
