### PR TITLE
Don't put API calls in the upgrader

### PR DESCRIPTION
**Pull request by totten**
n/t

### CODE REVIEW

**Comment by demeritcowboy** [comment]
In case the log disappears they're all this one in the stock preupgrade messages https://github.com/civicrm/civicrm-core/blob/6c2c45309ae82d69d922c354648714f02e32f1d8/CRM/Upgrade/Incremental/General.php#L137

**Comment by colemanw** [comment]
@totten FYI there was some work done last year to make APIv4 calls upgrade-safe, because it filters values by `CRM_Core_DAO::getSupportedFields` and that function only returns fields supported by the current version (even during an upgrade state).

**Comment by colemanw** [comment]
retest this please

**Comment by demeritcowboy** [comment]
Patch no longer applies. Github says yes, git says no. One of them is lying.

**Comment by totten** [comment]
@demeritcowboy @colemanw I've rebased, and... it does pass now... though it's slightly deceptive, because 
[this bit](https://github.com/civicrm/civicrm-core/blob/364933b020f6d5d808b71082f2b3ac0ccd96d425/CRM/Upgrade/Incremental/MessageTemplates.php#L473-L484) hides some failed assertions.

**Comment by demeritcowboy** [comment]
I'm just wondering if it's too harsh to completely prevent it. For example one of them is just setting a setting, which ok could be a SQL query where you serialize it yourself, but it seems like the risks in using the function is low. Or some of them are ensureOptionValueExists(), which is intended to be used in upgrade scripts, so if that one's dangerous we should update that function.
But I suppose we could always grow the functionThatIsNotSupposedToGrow if it's decided a future given upgrade task could also be excluded.

**Comment by demeritcowboy** [comment]
@totten What do you want to do with this one? Close for now as being too nuanced to be so strict?

**Pull request closed without merging**
