### PR TITLE
Ensure there is a record of queueRunner exceptions in ConfigAndLog

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Ensure there is a record of queueRunner exceptions in ConfigAndLog

Before
----------------------------------------
There doesn't seem to be any retained record of errors during queue processing

After
----------------------------------------
Logged to the ConfigAndLog

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by totten** [comment]
Do you have a more specific example of where it fails to log?

To try an example, I hacked the upgrader to include an invalid SQL call. Then I ran the upgrade a few ways (with+without patch, different UIs). Basic steps were like:

```
## 1. Reset DB and cleanup log
civibuild restore &&  rm -f ~/bknix/build/dmaster/web/sites/default/files/civicrm/ConfigAndLog/*log*

## 2. Run whichever upgrader we want to test

## 3. Check the log
joe ~/bknix/build/dmaster/web/sites/default/files/civicrm/ConfigAndLog/*log
```

And here's the observed output in the log:

| Upgrader | Behavior before patch | Behavior after patch |
| -- | -- | -- |
| `civicrm/upgrade?reset=1` | Logs backtrace __two__ times | Logs backtrace __three__ times |
| `drush civicrm upgrade-db` | Logs backtrace __two__ times | Logs backtrace __three__ times |
| `cv upgrade:db` | Logs backtrace __one__ time | Logs backtrace __one__ time | 

Perhaps there's some difference between the use-case that you're trying and these use-cases?

**Comment by eileenmcnaughton** [comment]
@totten we have someone reporting failures on imports on their staging and live sites with no recorded error - so I'm in the dark about the underlying problem - hence wanting to ensure there is something logged

**Comment by totten** [comment]
@eileenmcnaughton FWIW, it's hard to know what error to simulate... but I simulated an error with this:

```diff
diff --git a/CRM/Contact/Import/Parser/Contact.php b/CRM/Contact/Import/Parser/Contact.php
index 11f59ffb5a..a081ddebb5 100644
--- a/CRM/Contact/Import/Parser/Contact.php
+++ b/CRM/Contact/Import/Parser/Contact.php
@@ -138,6 +138,9 @@ class CRM_Contact_Import_Parser_Contact extends CRM_Import_Parser {
    */
   public function import(array $values): void {
     $rowNumber = (int) $values[array_key_last($values)];
+    if ($rowNumber === 27) {
+      throw new \RuntimeException("Oooga booga!");
+    }

     // Put this here for now since we're gettting run by a job and need to
     // reset it for each task run.
```

And then using "Import Contacts" with `contact-more-than-100-rows.csv`. Running as `admin`. The result:

* The web UI shows the failure:
    Screen Shot 2022-09-05 at 3 52 48 PM
* The log file shows the failure:
    ```
    Sep 05 15:50:19  [info] Running task: Processed 20 rows out of 135
    
    Sep 05 15:50:19  [info] Running task: Processed 25 rows out of 135
    
    Sep 05 15:50:20  [info] $CRM_Queue_Page_AJAX_runNext_error = RuntimeException: "Oooga booga!"
    #0 /Users/totten/bknix/build/dmaster/web/sites/all/modules/civicrm/CRM/Import/Parser.php(2120): CRM_Contact_Import_Parser_Contact->import((Array:12))
    #1 /Users/totten/bknix/build/dmaster/web/sites/all/modules/civicrm/CRM/Queue/Task.php(101): CRM_Import_Parser::runJob(Object(CRM_Queue_TaskContext), 1, 5, 0)
    #2 /Users/totten/bknix/build/dmaster/web/sites/all/modules/civicrm/CRM/Queue/Runner.php(253): CRM_Queue_Task->run(Object(CRM_Queue_TaskContext))
    #3 /Users/totten/bknix/build/dmaster/web/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(36): CRM_Queue_Runner->runNext(TRUE)
    #4 /Users/totten/bknix/build/dmaster/web/sites/all/modules/civicrm/CRM/Queue/ErrorPolicy.php(89): CRM_Queue_Page_AJAX::{closure}()
    #5 /Users/totten/bknix/build/dmaster/web/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(38): CRM_Queue_ErrorPolicy->call(Object(Closure))
    #6 /Users/totten/bknix/build/dmaster/web/sites/all/modules/civicrm/CRM/Core/Invoke.php(285): CRM_Queue_Page_AJAX::runNext()
    #7 /Users/totten/bknix/build/dmaster/web/sites/all/modules/civicrm/CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem((Array:17))
    #8 /Users/totten/bknix/build/dmaster/web/sites/all/modules/civicrm/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke((Array:4))
    #9 /Users/totten/bknix/build/dmaster/web/sites/all/modules/civicrm/drupal/civicrm.module(471): CRM_Core_Invoke::invoke((Array:4))
    #10 /Users/totten/bknix/build/dmaster/web/includes/menu.inc(527): civicrm_invoke("queue", "ajax", "runNext")
    #11 /Users/totten/bknix/build/dmaster/web/index.php(21): menu_execute_active_handler()
    #12 {main}
    ```

**Comment by totten** [comment]
Oh, @eileenmcnaughton , but if you coerce a slightly different exception...

```diff
diff --git a/CRM/Contact/Import/Parser/Contact.php b/CRM/Contact/Import/Parser/Contact.php
index 11f59ffb5a..c081532b55 100644
--- a/CRM/Contact/Import/Parser/Contact.php
+++ b/CRM/Contact/Import/Parser/Contact.php
@@ -151,6 +151,10 @@ class CRM_Contact_Import_Parser_Contact extends CRM_Import_Parser {
     $relatedContacts = [];

     try {
+      if ($rowNumber === 27) {
+        throw new \CRM_Core_Exception("Abba dabba!");
+      }
+
       $params = $this->getMappedRow($values);
       $formatted = [];
       foreach ($params as $key => $value) {
```

Then it swallows the exception. It proceeds with the upgrade (past the failed record) and reports that the record failed with message `Abba dabba!`. However, it does not report any backtraces. This is because `CRM_Contact_Import_Parser_Contact` captures the exception and doesn't report anything. (*ie it's not a general issue with queue runner*)

**Comment by eileenmcnaughton** [comment]
@totten so that suggests that behaviour is correct in the second example.

In the first example we have a `wtf error` - so the backtrace in your image is invaluable in terms of getting more info from sites that hit it - was that backtrace present WITH this patch & missing without? If so then this should be merged (I don't think worrying about overlogging in other scenarios is important - not worth sinking extra time into - but had this been merged into the rc / last stable I might have been able to track down the error that I'm being messaged about and / or known if the fix I did fixed the user's issue - and hence saved myself a few hours looking for other possible causes)

**Comment by totten** [comment]
> ...was that backtrace present WITH this patch & missing without?

Oops, right. I was testing the baseline pre-patch. Here's the behavior with the PR:

* For the first exception ("Oooga booga!"), it now creates a double-log.
* For the second exception ("Abba dabba!"), it has no effect. The `CiviCRM.log` does not get a backtrace, and the CSV result report shows just the bare message "Abba dabba!".

The queue-runner already does what you were trying to add here. The issue is `CRM_Contact_Import_Parser_Contact::import()` (and similar functions). If you read the try/catch, it captures the error and directs it to `setImportStatus()`. This is probably good overall (*eg it provides a nicer CSV error-report and proceeds to other import tasks*), but it also supersedes the generic error-handling. That's why "Abba dabba!" is never logged (*with or without this PR*).

I think you're looking for something more like this:

```diff
     catch (CRM_Core_Exception $e) {
+      Civi::log()->notice('Import of {row} failed: {exception}', ['row' => $rowNumber, 'exception' => $e]);
       $this->setImportStatus($rowNumber, $this->getStatus($e->getErrorCode()), $e->getMessage());
       return;
     }
```

Or (*since they are several importers, and they all call `setImportStatus()`*) perhaps it would make sense to patch `setImportStatus()` to CC errors to the Civi log?

**Comment by eileenmcnaughton** [comment]
Hmm I wrote a reply  but it got lost :-(

The Abba dabba!" scenario is working as it should and error handling is correct. There is no reason for additional logging

The "Oooga booga!" scenario is being hit 'in the wild' (although it might be resolved now). I was never able to get a back trace from the user for the 'queue falling over' bug - so I haven't been able to diagnose it. I don't know if the user failed to find the backtrace or it wasn't logged - your testing suggests it was the user who failed to find it. 

I guess we may as well close this - I think the upshot is that until we can replicate the error that we can't diagnose at the moment we can't add this debugging for fear it might log an extra backrace

**Pull request closed without merging**
