### PR TITLE
WIP Pass params through quickform object properly instead of re-exporting…

### PR DESCRIPTION
**Pull request by mattwire**
… (and losing everything that was previously done eg. via postProcess / hooks)

Overview
----------------------------------------
This was identified when manipulating the quickform _params array via the postProcessHook and finding that it behaved differently between the event registration and the contribution pages.  On event registration pages it correctly retains any modifications made by `$this->get('params'); $this->set('params', $modifiedParams);`  But on contribution pages it does not - because the postProcess function is not calling `$this->set()` and all the modifications to the $this->_params array are lost when they are re-exporting from the form in the `CRM_Contribution_Form_Confirm::preProcess()` function.

Before
----------------------------------------
Form params NOT passed through from Main->Confirm on contribution pages.  Form params passed through from Register->Confirm on event registration pages.

After
----------------------------------------
Form params passed through from Main->Confirm on contribution pages and passed through from Register->Confirm on event registration pages.

Technical Details
----------------------------------------

Comments
----------------------------------------
I'm surprised this has not been causing issues - but I imagine it's been worked around by running the same or similar functions multiple times to achieve the same result.

@eileenmcnaughton @colemanw I would appreciate some quick feedback on this if possible as it's currently a blocker for the stripe upgrade.

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
I think we also might need to handle the further processing of params which were handled based on the previous value it received from exportValue() function? 

Eg - the `price_<id>` key in `$this->_params` was set to an integer value and now it gets posted as an array which displays the below warning on the confirmation/thankyou page -

image

**Comment by eileenmcnaughton** [comment]
I haven't dug into this but in terms of how it should work in principle my preference would be

1) we have a parameter such as $form->form_values that always holds the values as submitted & work towards that being the case on every form
2) we avoid passing around calculated values where they could be calculated on the next form with shared code (obviously performance can be a thing but often it's stuff that's otherwise cached anyway)
3) we have a clearly defined array called something like $processed_values that holds things we really need to pass - eg. any the id of entities created in the last step

**Comment by jitendrapurohit** [comment]
@mattwire looks like the test failures are related?

**Comment by mattwire** [comment]
@jitendrapurohit I'm going to look at this in Barcelona.  I think it needs to be resolved as we're basically running a whole load of things multiple times instead of processing the form params once and using them.

**Comment by mattwire** [comment]
This blew up.. :-( But we should be able to use `pre_approve_parameters` to work around this for payment processors.

**Pull request closed without merging**
