### PR TITLE
CiviEvent - Error registering through advanced search task

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
port https://github.com/civicrm/civicrm-core/pull/19125

### CODE REVIEW

**Comment by timindaburgh** [comment]
I made the changes in the three files that had additions and/or deletions. I then added the new file. After testing by placing two participants selected from a search into an upcoming active event, both events were correctly added to the records of the two participants. However, there was an error that came up upon saving the participants to the event: 

> getFieldValue failed

Otherwise, the patch did work and the database was updated accurately.

**Comment by eileenmcnaughton** [comment]
Wow - this is a flakey bit of code - we all get different errors.

Still you are up & running again now - @totten I'm inclined to merge & release this as confirmed-to-be-better (although this is the version that worked for me & not you & different to the 5.33 pr atm)

**Comment by totten** [comment]
> >  However, there was an error that came up upon saving the participants to the event:
> >
> > >    getFieldValue failed
> >
> > Otherwise, the patch did work and the database was updated accurately.
>
> Wow - this is a flakey bit of code - we all get different errors.

Yeah, this one has had it tough at QA. For me, there are a few distinct issues which all produced a similar symptom.

__Symptom__: The registration-form is supposed to show a bunch of fields (e.g. pricing options, e.g. payment tracking, e.g. custom-fields) which depend on the specific event. These fields are displayed progressively (via AJAX) while you fill-out the form. If the AJAX call fails, then the fields don't show up. 

At first glance, you may not even notice this problem. ([I didn't notice when first testing the same patch on 5.33...](https://github.com/civicrm/civicrm-core/pull/19125#issuecomment-739133215)). The form still *looks* plausible. The error isn't displayed in real time. You can even submit the form, and it will create a `civicrm_participant` record. But something is likely askew with the completeness/integrity because it didn't collect the standard data, and you will eventually see an error-message in a future pageview.

Recap: The symptom is that fields are missing from UI because an AJAX call to `civicrm/contact/view/participant` (`CRM_Event_Page_Tab`) fails with "HTTP 500". However, you may not *see* any explicit messages about this failure until you navigate to another screen.

__Causes and Fixes__: The symptom has had a few causes:

(1) There's the "getFieldValue required" error which @timindaburgh mentioned. This is now a reliable problem. I've seen locally on multiple workstations/builds and on the autobuild test site, and I believe it's what Eileen noticed on an autobuild test site. The problem arises  because this form uses a helper (`CRM_Contact_Page_View::checkUserPermission`) which is not well-defined for this use-case. I pushed https://github.com/civicrm/civicrm-core/pull/19125/commits/2497350fbcc8f3a9073b5722835541eccaa83537 to the 5.33 branch which appears to resolve this.

(2) `qfKey` is the [CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery) protection token, and it's required by most forms/subforms. The AJAX request must have a `qfKey` that matches the subform. There are competing revisions to address this, e.g. [turning off qfKey (ignoreKey=TRUE)](https://github.com/civicrm/civicrm-core/pull/19125/commits/1db1f8e3d0f8d8b5a88536889ddaed66ec2a2abd) or [setting qfKey correctly](https://github.com/civicrm/civicrm-core/pull/19125/commits/df80fbabc873519be8b08d2d49a682826e671994). I believe that both patches handle `qfKey`, but it's better to keep CSRF protection enabled.

(3) The AJAX request for `civicrm/contact/view/participant` optionally accepts an `action` parameter, which determines the subform to display. If not passed explicitly, then it somehow picks a default/implicit action. In my previous testing, I had a problem where the default/implicit `action` was wrong. (*This manifested just like issue (2) for `qfKey`.*). [Setting the action explicitly](https://github.com/civicrm/civicrm-core/pull/19125/commits/df80fbabc873519be8b08d2d49a682826e671994) resolved it. No one else has reported this problem, and I can't reproduce it now. However, there's no downside to passing the `action` explicitly.

**Comment by totten** [comment]
Did a final `r-run` on autobuild test site. Tested both the search-task (registering 1x and 3x contactx) and the standalone menu item ("Events => Register event participants" with 1x contact). In all cases, the full form displays. No AJAX HTTP 500. No lingering error-notices. 

Merging this as near-term fix per MM discussion. Eileen's aiming to do a cleaner/separate route for this in `master`.

**Pull request merged**
