### PR TITLE
dev/financial#11 Expand unit test to ensure that the correct currency…

### PR DESCRIPTION
**Pull request by seamuslee001**
… is outputted in the token

Overview
----------------------------------------
Expands a unit test to cover for the fix by @MegaphoneJon in #18714 

Before
----------------------------------------
Unit test doesn't cover the specific scenario

After
----------------------------------------
Unit test covers the specific scenario

ping @MegaphoneJon @demeritcowboy @eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
nice

**Comment by seamuslee001** [comment]
(note I am expecting the first test run to fail cos it started before i merged the other PR)

**Comment by seamuslee001** [comment]
Expected test fail (Test run had started before fix merged)

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Pull request merged**
