### PR TITLE
Fix master-only regression on import fields

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fix master-only regression on import fields

Before
----------------------------------------
State & Country & Location Type ID no longer show as importable fields in the contribution import

After
----------------------------------------
They're back

Technical Details
----------------------------------------
This undoes a change I made very recently here https://github.com/civicrm/civicrm-core/pull/30930/files#diff-a2daa0eb4d93f084aa2ad66b42fd4a351f38c8f230a0895870c7da8c520ab6dcR2408 - I was confused about hot the filter on fk_entity fit & first removed that filter for all entities & then put it back - but put it back for the ones that did not originally have it.

We DO want to be able to specify the contact's State, Country etc when importing contributions

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton test fails look relevant here 

```
CRM_Dedupe_BAO_RuleGroupTest::testSupportedCustomFields
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     'civicrm_address' => Array (
         'name' => 'Address Name'
         'city' => 'City'
-        'country_id' => 'Country'
-        'county_id' => 'County'
+        'country_id' => 'Country ID'
+        'county_id' => 'County ID'
         'geo_code_1' => 'Latitude'
         'geo_code_2' => 'Longitude'
         'master_id' => 'Master Address ID'
         'postal_code' => 'Postal Code'
         'postal_code_suffix' => 'Postal Code Suffix'
-        'state_province_id' => 'State'
+        'state_province_id' => 'State/Province ID'
         'street_address' => 'Street Address'
         'supplemental_address_1' => 'Supplemental Address 1'
         'supplemental_address_2' => 'Supplemental Address 2'
```

**Comment by eileenmcnaughton** [comment]
The test fails are just label changes but they highlight that 

1) the dedupe code is getting fields with usage = import instead of duplicate matching - for legacy reasons and
2) the test cover on that chunk is super solid

So it seems like a good moment to fix it properly - at least for the address entity

**Comment by eileenmcnaughton** [comment]
OK @seamuslee001 I did a 'real' fix over at https://github.com/civicrm/civicrm-core/pull/31004 & a 'get past tests' fix here

**Comment by eileenmcnaughton** [comment]
Passing - & deployed in prod for us

**Pull request merged**
