### PR TITLE
dev/event#58 Ensure custom data is not saved to template's row

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
dev/event#58 Ensure custom data is not saved to template's row

Before
----------------------------------------
Create a new set of custom fields (I've been using text, date and select inputs in my tests)
Create a new event template and fill out all necessary inputs (I've also entered something in the title, summary and description).
Create a new event using the newly created template. Enter something in all necessary fields as well as in the custom fields.
Click 'Continue'
Return to 'Info and Settings' - the data entered in the custom fields is gone :/
Open the template in edit mode. The custom data we previously entered in the event is here now

After
----------------------------------------
Saves to event

Technical Details
----------------------------------------
This ensures than when we are copying (implicity a create-new-action) we do not
update an existing row in the custom data table by explicity unsetting the
id in the copy function. This has been bouncey behaviour because
the formatting for form purposes relies on form type formatting and yet
for save purposes it's not really fit for purpose. Although a bit
hacky this approach should be robust & avoids a re-write on the form

Comments
----------------------------------------

### CODE REVIEW

**Comment by agileware-justin** [comment]
Direct link back to Gitlab, https://lab.civicrm.org/dev/event/-/issues/58

**Comment by eileenmcnaughton** [comment]
I just pushed up unit tests - I had that moment of 'ug I don't want to write a test for this' but I pushed through

**Comment by agileware-justin** [comment]
@eileenmcnaughton Have tested and confirmed this PR works as intended. Thanks very much!

Funny bunnies

**Comment by eileenmcnaughton** [comment]
thanks some binky

**Comment by seamuslee001** [comment]
Merging as per the review from the bunnies

**Comment by eileenmcnaughton** [comment]
it's strangely mesmerising...

**Pull request merged**
