### PR TITLE
Export code cleanup: Convert relationships to pseudonames at the point of loading

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Minor code cleanup

Before
----------------------------------------
Code messier

After
----------------------------------------
Code less messy

Technical Details
----------------------------------------
The convertToPseudoName function is called on each instance of the DAO loaded from the relationship query. It makes sense to do this when it is first loaded rather than to pass it deep into the parent function & then do it.

Note we removed the clone action from the main loop a while back -ie. we iterate through a DAO for main export properties & later for relationship properties. We got no issues from that, which feels it was higher risk than doing the same in the secondary loop.

Comments
----------------------------------------
Testing should be done in conjunction with https://github.com/civicrm/civicrm-core/pull/12579 which is more complicated but will require the same sorts of UI tests

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
Seems to break the relationship export. It works fine without this changes. To replicate -

- Search `Parent of` relationship from Advanced Search.
- Export the results
- Select field to export as follows 

image

- Exported CSV has the same parent first and last name for all the rows listed.

**Comment by eileenmcnaughton** [comment]
Thanks @jitendrapurohit - once I've sorted out https://github.com/civicrm/civicrm-core/pull/12579 I'l add a test to capture that & try to fix it

**Comment by twomice** [comment]
@eileenmcnaughton Looks like this PR is part of a larger code cleanup, initiated by efforts at fixing CRM-20632, which is an issue we're facing now. Anything I could do to help this along? (I suspect the complexity is such that adding more manpower doesn't help, but just in case ...)

**Comment by eileenmcnaughton** [comment]
@twomice I stopped progressing it because I was struggling to get the parts reviewed - the current PR that is wanting review is this one https://github.com/civicrm/civicrm-core/pull/12672 & once that is reviewed & merged I'll put the next chunk up - so yes, you could definitely help progress this!

**Comment by colemanw** [comment]
@eileenmcnaughton time for the next chunk.

**Comment by twomice** [comment]
Jenkins test this please.

**Comment by twomice** [comment]
@eileenmcnaughton Having trouble following the PRs here; is there another one that's awaiting review on the way to resolving CRM-20623?

**Comment by eileenmcnaughton** [comment]
@twomice this probably needs more work on this one - but if you are ready to do some more review I'll revisit it and fix the issue above + add test, or replace this

**Comment by twomice** [comment]
@eileenmcnaughton yes I've got time for a review or two.

**Comment by eileenmcnaughton** [comment]
@twomice @jitendrapurohit I was able to capture the issue as described by @jitendrapurohit in a unit test & address it.

I've updated the PR with those fixes - it did grow it a bit but it's definitely moving in the right direction. I have some more fixes locally that build on this that I will do as the next PR

**Comment by jitendrapurohit** [comment]
The failing test is the one added in this PR and it fails on my local too.

**Review by jitendrapurohit — APPROVED** [review]
Confirming that the issue mentioned in my above comment is fixed. Also checked the exports related to different components and relationships. They seem to work fine after the change 👍

**Comment by eileenmcnaughton** [comment]
thanks @jitendrapurohit

**Comment by twomice** [comment]
Thanks @jitendrapurohit !

**Comment by eileenmcnaughton** [comment]
@twomice can you put those up onto github - perbhaps a WIP PR. I'm really curious as to whether it will look like the changes I was imagining next

**Comment by twomice** [comment]
@eileenmcnaughton I don't have any code to offer at this point, was just quoting you where you said "I have some more fixes locally that build on this that I will do as the next PR" in a comment above, and offering to review the next PR(s) if/when you put them up.

**Comment by eileenmcnaughton** [comment]
@twomice oh I misread

**Comment by eileenmcnaughton** [comment]
I think I'm going to fix up the handling of phonetypes yet - I think you can see if you look at the code now we are almost at the point where we can just array merge in php & not write the household stuff to temp table at all

**Pull request merged**
