### PR TITLE
CRM-21494 trigger pre hook on mailing bounce

### PR DESCRIPTION
**Pull request by mountev**
Overview
----------------------------------------
This triggers the pre hook when a mailing bounce is processed, allowing you to modify the bounce type, parse the bounce reason in a custom manner, or perform other follow-up actions.

Implementation example
----------------------------------------
https://github.com/mountev/com.example.myextension/blob/master/myextension.php#L136

---

 * [CRM-21494: trigger pre hook on mailing bounce](https://issues.civicrm.org/jira/browse/CRM-21494)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
HI,

this makes sense but I checked the Website::create function & there is a nuance

```
    $hook = empty($params['id']) ? 'create' : 'edit';
    CRM_Utils_Hook::pre($hook, 'Website', CRM_Utils_Array::value('id', $params), $params);
```

probably worth adding the post hook too

```
    CRM_Utils_Hook::post($hook, 'Website', $website->id, $website);
```

**Comment by mountev** [comment]
Both actions, and post-hook added.

**Comment by eileenmcnaughton** [comment]
Looks good - we should also pass out the id in the PRE hook on edit - ie

CRM_Utils_Array::value('id', $params) as the 3rd param

**Comment by totten** [comment]
jenkins, add to whitelist

**Comment by mountev** [comment]
pre hook 3rd arg added.

**Comment by eileenmcnaughton** [comment]
Looks good to me now

**Comment by eileenmcnaughton** [comment]
I would note that I think the code by-passes this hook to do a $dao->save() in at least one place - so you may wish to update it to use the api

**Pull request merged**
