### PR TITLE
fixed number format problem with PayPal fee calculation

### PR DESCRIPTION
**Pull request by bjendres**
properly format calculated `net_amount`

### CODE REVIEW

**Comment by davecivicrm** [comment]
@systopia Is there a related issue tracker item for this? If not, please file one (and include symptoms of the bug). Thanks!

**Comment by davecivicrm** [comment]
Fix for https://issues.civicrm.org/jira/browse/CRM-17218

**Comment by yashodha** [comment]
Jenkins test this please

**Comment by systopia** [comment]
:-)

Can Jenkins properly test live/test PayPal contributions?

**Pull request merged**
