### PR TITLE
[Ref] Mark unused date functions as deprecated

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Flags unused functions for removal

Before
----------------------------------------
Not clear functions are on their way out

After
----------------------------------------
Functions are clearly deprecated

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by mlutfy** [comment]
Seems fine by me, but will let someone else more qualified to merge :)

**Comment by eileenmcnaughton** [comment]
@mlutfy this is really a case of doing a grep & seeing if you agree they aren't used

**Comment by mlutfy** [comment]
I'm still seeing this:

```
$ grep -r returnDateRangeSelector
CRM/Core/Form/Date.php:      = CRM_Core_Form_Date::returnDateRangeSelector(
CRM/Core/Form/Date.php:  public static function returnDateRangeSelector(
bgm@erdenet:~/repositories/civicrm-core$ grep -r addDateRangeToForm
CRM/Core/Form/Date.php:    CRM_Core_Form_Date::addDateRangeToForm(
CRM/Core/Form/Date.php:  public static function addDateRangeToForm(
```

Other than that, I grepped in a set of extensions and they were not used there.

**Comment by eileenmcnaughton** [comment]
@mlutfy yep - aren't those calls from the deprecated functions?

**Comment by mlutfy** [comment]
Long day ;-)

**Pull request merged**
