### PR TITLE
Drop binding current domain settings bag to CRM_Core_Config on boot

### PR DESCRIPTION
**Pull request by ufundo**
Curiosity will probably cause some failed tests.

But this was ["extremely backward" 9 years ago](https://github.com/civicrm/civicrm-core/commit/23bb9c85dfd571bf91309ece5c02dc16c8b709cb#diff-dc1c0506257784ef60b0b3f296a5e64c633c0a19d47dbd87885eb21852836fd6), so I couldn't help myself...

### CODE REVIEW

**Comment by ufundo** [comment]
Well, I was not expecting tests to pass...

Looking at the original commit, I think the real test would be whether the `getSettings` and `settings` property in MagicMerge can be removed. It looks like some of the places it was used in the constructor have since been superceded... so, maybe?

**Comment by eileenmcnaughton** [comment]
@totten would probably know

**Comment by colemanw** [comment]
@ufundo this is stale, is it still relevant?

**Comment by ufundo** [comment]
From looking at [the original commit](https://github.com/civicrm/civicrm-core/commit/23bb9c85dfd571bf91309ece5c02dc16c8b709cb#diff-dc1c0506257784ef60b0b3f296a5e64c633c0a19d47dbd87885eb21852836fd6) it seems like this line isn't doing much any more?

But I definitely don't have a full picture of the context.

@totten I think you had a little look at this at the sprint?

**Comment by mlutfy** [comment]
If I understand correctly, it's for settings that were previously on `$config->something`, and now should be accessed using `Civi:settings()->get()`?

Looking at core, I see, for example, uses of `CRM_Core_Config::singleton()->doNotAttachPDFReceipt`, which is also a setting (and it's probably much worse in extensions).

If yes, where is the best place to check for valid `$config` properties, so that we could PSA against using deprecated ones?

**Comment by ufundo** [comment]
> If I understand correctly, it's for settings that were previously on $config->something, and now should be accessed using Civi:settings()->get()?

So it relates to this difference, but I don't think it should change the actual behaviour.

As I've understood it, all the action happens in `CRM_Core_Config_MagicMerge`.

The settings that are available on the `CRM_Core_Config` singleton are listed in `getPropertyMap`.

Take `doNotAttachPDFReceipt` as an example.

```
# start with the config object
$config = CRM_Core_Config::singleton();

# these are all equivalent
$config->doNotAttachPDFReceipt
$config->__get('doNotAttachPdfReceipt')  # because its a magic method
$config->getSettings()->get('doNotAttachReceipt')  # because its defined as a ['setting'] in the property map
```

So the question is, what do we get from `$config->getSettings()`?

Well, we get whatever we got back from `Civi::settings()`, whenever it was first getSettings is called on the $config object. The line to be removed is making sure "the first time getSettings is called on $config object" is at this same point in the boot.

But I don't see why we need to do that - Civi:settings() should always be returning the same thing from this point forward, so we don't need to make a special case of doing it here. 

It seems like quite a trivial change - maybe not worth the risk. But it also might be one small step on the way to cleaning up some of these very old parts of CRM_Core_Config, which seem to predate all the nicer cleaner services like SettingsManager.

**Comment by ufundo** [comment]
> Civi:settings() should always be returning the same thing from this point forward

Assumption in here is that the domain doesn't change during the course of the request? If it can, then the CRM_Core_Config settings are going to keep returning results from the original domain.

**Comment by mlutfy** [comment]
In a way, it was warming up the cache, but it's not necessary?

Either way, I would assume/hope that the entire concept of backwards-compat with `$config` isn't really necessary anymore, even if that is not what is proposed here.

So I feel comfortable with removing bits of it, and taking a small risk, for the sake of cleaning up the code.

It's not really my call though, but I can add merge-ready to nudge it forward :smile:

**Comment by totten** [comment]
Yeah, when I first read this bit of code, I felt a pang of "What the heck was that comment?" 🙃 

It's also tricky that the git commit alludes to some unnamed test.

Since the gist of the comment is about fixating the `domain`... the test is probably something with switching domains. If you dig back around early 4.7.x (*when the patch was written*), there were helper functions to switch between domains (`::setDomain()`, `::resetDomain()`), and they appeared in [one test](https://github.com/civicrm/civicrm-core/blob/23bb9c85dfd571bf91309ece5c02dc16c8b709cb/tests/phpunit/api/v3/SettingTest.php#L369-L386). NB:

https://github.com/civicrm/civicrm-core/blob/23bb9c85dfd571bf91309ece5c02dc16c8b709cb/tests/phpunit/api/v3/SettingTest.php#L377-L380

You can only pass the test if `$config` was substantively locked-in before the reset. The test seems pretty intentional (5b887f26ae68648ee6e13bcf9964d6228f6d26e0), although the rationale is opaque to me.

Subsequently,  the test-case was removed (c9dbc47c1a676a05908675c9fe5a0b11f4562a79). The same commit also removed the helper functions for switching domains. To my interpretation, that's the most persuasive thing:

* Hey, maybe other processes could switch the active domain. Maybe `$config` needs to be tied to a specific domain.
* It's certainly plausible for an email cron-job to switch the active-domain (e.g. to resolve `{domain.*}`). It's not the only way to work. But it's plausible.
* ___Ah! But `setDomain()` and `resetDomain()` don't even exist anymore!___ 
* The edge-case behavior for switching-domains becomes irrelevant... when no one is allowed to switch domains...

So I don't see any reason to keep it around.

**Pull request merged**
