### PR TITLE
Smarty notice fix

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fixes

image

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
[Test Result](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/559/BKPROF=dfl,SUITES=phpunit-e2e,label=bknix-tmp/testReport/) (1 failure / +1)
[E2E\Core\AssetBuilderTest.testInvalid](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/559/BKPROF=dfl,SUITES=phpunit-e2e,label=bknix-tmp/testReport/junit/(root)/E2E_Core_AssetBuilderTest/testInvalid/)


test this please

**Comment by demeritcowboy** [comment]
Upgrades are (sort of) failing now - there is no $form variable so this causes a fatal error on the success screen. In fact there is no such variable as $afterUpgradeMessage - it must be some old code - the message you're seeing is inside `$message`.

**Comment by demeritcowboy** [comment]
Fix is at https://github.com/civicrm/civicrm-core/pull/25554

**Pull request merged**
