### PR TITLE
dev/core#2717 Simplify batch membership renewal

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Simplify batch membership renewal

This builds off https://github.com/civicrm/civicrm-core/pull/20882 and makes the assumption that we only need 2 code paths in this form

1) form option is_renew chosen AND a current membership exists => then use the renew code
2) form option is renew not chosen or no current membership exists => then use the create code.

It removes handling for the (hopefully already unreachable and / or broken)
- form option is_renew chose and no membership exists 
- for option is_renew chosen but only cancelled or pending memberships exist 

Before
----------------------------------------
A lot of code that was relevant to obscure pathways on the online contribution form (that doesn't have a separate 'new membership' process

After
----------------------------------------
poof

Technical Details
----------------------------------------
@monishdeb @kcristiano @jitendrapurohit  this is a  bit of a bigger change to the batch membership form from a required r-run POV - I'm hoping one of you can help on it

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@monishdeb thanks for merging #20882  - I've rebased that out of this now

**Comment by kcristiano** [comment]
@eileenmcnaughton I had thought I had commented here.  But I must have not.

I did start with an `r-run` and get the following on batch submission

```
[13-Aug-2021 09:26:05 America/New_York] PHP Fatal error:  Uncaught TypeError: Return value of CRM_Batch_Form_Entry::legacyProcessMembership() must be an instance of CRM_Member_BAO_Membership, instance of CRM_Member_DAO_Membership returned in /srv/www/buildkit/wpcv/web/wp-content/plugins/civicrm/civicrm/CRM/Batch/Form/Entry.php:1132
Stack trace:
#0 /srv/www/buildkit/wpcv/web/wp-content/plugins/civicrm/civicrm/CRM/Batch/Form/Entry.php(840): CRM_Batch_Form_Entry->legacyProcessMembership('18', '1', Array, 'Batch', Array, Array)
#1 /srv/www/buildkit/wpcv/web/wp-content/plugins/civicrm/civicrm/CRM/Batch/Form/Entry.php(525): CRM_Batch_Form_Entry->processMembership(Array)
#2 /srv/www/buildkit/wpcv/web/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(526): CRM_Batch_Form_Entry->postProcess()
#3 /srv/www/buildkit/wpcv/web/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Upload.php(152): CRM_Core_Form->mainProcess()
#4 /srv/www/buildkit/wpcv/web/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Upload.php(119): CRM_Core_QuickForm_Action_Upload->realP in /srv/www/buildkit/wpcv/web/wp-content/plugins/civicrm/civicrm/CRM/Batch/Form/Entry.php on line 1132
```

I'll look further and comment.   I want to log what I find as I find it

**Comment by eileenmcnaughton** [comment]
@kcristiano I've fixed ^^

If you are going to do a thorough r-run I could go a bit further with the clean up (the balance of how much to fix depends a bit on whether the reviewer is more code focussed or r-run focussed)

**Comment by eileenmcnaughton** [comment]
@kcristiano ah - now I've refreshed my memory - the renew membership code has 3 paths (it was written for front end forms) 

- the removed one that deals with non-renewals
- the one I'd like to remove that deals with when is is supposed to be a renewal but they are not a current member
- the actual renewal

I'm not sure if 2 is reachable - I'll put up a separate PR with it removed & you can tell me if you can figure out the difference.

**Comment by eileenmcnaughton** [comment]
OK - here is the PR with the code I'm not sure the reachability of ripped out https://github.com/civicrm/civicrm-core/pull/21126

**Comment by kcristiano** [comment]
@eileenmcnaughton I will look at these over the next few days.   Thanks for all the work here.

**Comment by eileenmcnaughton** [comment]
@kcristiano yeah there is quite a bit more to do - but I think there is a big question to answer - how much of the code is actually reachable - which will alter the scope of the next bit.

My goal is to get the code using the Order api

**Comment by kcristiano** [comment]
@eileenmcnaughton I've done some more `r-run` on this one.   

The form works, but if you try and rely on the Membership Type to set the end date on new memberships, none is set.

Renewals do extend the membership the number of terms.   

I'll also review the alternative Patch.   

In additional this shows a regression in the RC - membership Dashboard has a fatal error.  I'll open an issue for that.

**Comment by eileenmcnaughton** [comment]
@kcristiano can you outline the steps for "but if you try and rely on the Membership Type to set the end date on new memberships, none is set." - I'll make sure it has test cover & works

**Comment by kcristiano** [comment]
More details:

- Create batch
- Choose contacts
- set start date
- leave end date blank

image


Memberships created without end date

image

```
mysql sa@(none):wpcvmastercivi_s301l> select id,contact_id,membership_type_id,source,join_date,start_date,end_date from civicrm_membership where source like '%1931%'   
+------+--------------+----------------------+------------+-------------+--------------+------------+
| id   | contact_id   | membership_type_id   | source     | join_date   | start_date   | end_date   |
|------+--------------+----------------------+------------+-------------+--------------+------------|
| 40   | 22           | 1                    | Batch 1931 | 2021-08-15  | 2021-08-15   | <null>     |
| 41   | 169          | 1                    | Batch 1931 | 2021-08-15  | 2021-08-15   | <null>     |
| 42   | 128          | 1                    | Batch 1931 | 2021-08-15  | 2021-08-15   | <null>     |
+------+--------------+----------------------+------------+-------------+--------------+------------+

3 rows in set
Time: 0.007s

```

**Comment by kcristiano** [comment]
For comparison - add via back office  - not in batch mode:

image

Results as expected - end date based on Membership Type

image

**Comment by eileenmcnaughton** [comment]
@kcristiano I'm going to dig into this - but I suspect it is unchanged by this PR which I would expect to deal with renewals. This could be a regression though

**Comment by eileenmcnaughton** [comment]
@kcristiano I went back to 5.33 & tested entering a membership without entering the end_date & it was blank back then - potentially we should fix it to set something

**Comment by kcristiano** [comment]
Thanks @eileenmcnaughton that makes sense.

**Comment by kcristiano** [comment]
@eileenmcnaughton This PR and https://github.com/civicrm/civicrm-core/pull/21126  now have conflicts.  I was satrting to look at 21126 as I expect we want to merge that if possible.   This PR is an improvement, so if we want to go in small steps, this looks good to merge once the conflicts are solved.

**Comment by kcristiano** [comment]
@eileenmcnaughton Not yet for merge.

I found one other issue today.

- Find an expired membership
-  use batch mode to update that contacts memberhip
- set new expiry date
- membership status stays expired

image

**Comment by eileenmcnaughton** [comment]
@kcristiano so the expiration date was set in the batch mode - but it didn't update the status (only the date)?

**Comment by kcristiano** [comment]
Correct - Running on 5.39 right now to see if the unpatched version works.

**Comment by kcristiano** [comment]
Just tested on 5.39 and renewing updates expiry date and status.

**Comment by kcristiano** [comment]
I'll also comment on #21126 

I just did renewals on that one and the date and ststus upadted, so perhaps we need to focus on that PR as the alternative

**Comment by eileenmcnaughton** [comment]
@kcristiano oh interesting

**Pull request merged**
