### PR TITLE
WIP: Switch to Brick/Money instead of deprecated money_format

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
`money_format` is deprecated in PHP7.4 and any tests that use money formatting will fail when run on PHP7.4.

Switch our core money formatting functions to use Brick/Money.

We have already deprecated `$config->moneyvalueformat` and I think we should deprecate `$config->moneyformat` as well - I don't see a sensible way to do this without announcing that custom money formats will no longer be supported. The default should be much better with Brick/Money because it's more likely to be correct for the locale / currency specified so I don't think this would be a problem.

Before
----------------------------------------
`money_format` used in core.

After
----------------------------------------
`money_format` not used in core.

Technical Details
----------------------------------------
Brick/Money doesn't seem to support formatting without a currency symbol (ie. only number). So I've implemented a custom formatter for this per their guidelines.

Comments
----------------------------------------
@eileenmcnaughton @seamuslee001 @KarinG @jaapjansma @sluc23 @JoeMurray It would be good to get some testing/feedback on this. Also on the question of removing `moneyformat` and `moneyvalueformat` settings completely. Maybe if required in the future we could introduce a hook that allows specifying custom formatters?

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire I agree with deprecating moneyValue.

@seamuslee001 & I closed the other PR on this because we wanted the php-intl warnings to flush out how big an issue that was going to be before we pressed ahead on making it not-work-without it.

(The already merged part turns out not to require php-intl so that is OK)

**Comment by seamuslee001** [comment]
The one other thing I am nervous about is do we have an accurate sense of how many sites may or may not be using moneyValueFormat in a value that is not the default, those notices only just went out in a released version, I have been thinking of waiting until like August/September to move forward on that.

**Comment by eileenmcnaughton** [comment]
Yes - that's my general feeling - maybe dig into the js library in the meantime so that the money is being formatted before submit

**Comment by KarinG** [comment]
Perhaps send an email message to the dev-list to give people a heads up?

**Comment by eileenmcnaughton** [comment]
As discussed let's close this out for now  and give the new status checks a bit longer to perculate. But I think deprecating moneyValue is a good idea

**Comment by mattwire** [comment]
See branch https://github.com/mattwire/civicrm-core/tree/moneyformat

**Pull request closed without merging**
