### PR TITLE
standaloneusers: remove property type declarations to make php7.3 compat

### PR DESCRIPTION
**Pull request by artfulrobot**
See https://lab.civicrm.org/dev/core/-/issues/4746

### CODE REVIEW

**Comment by colemanw** [comment]
Thanks @artfulrobot -- we should be able to drop 7.3 support in December after the next ESR.

**Comment by totten** [comment]
Fired test-run on `standalone-clean,min` (https://test.civicrm.org/job/CiviCRM-Manual-Test/108/, pending). Merge on pass.

**Comment by seamuslee001** [comment]
This seems to have produced some more normal results on the standalone-clean,min run

**Comment by totten** [comment]
> This seems to have produced some more normal results on the standalone-clean,min run

Agree. It fixed the fatal. 👍 I believe the other stuff was preexisting.

**Pull request merged**
