### PR TITLE
Port https://github.com/civicrm/civicrm-core/pull/20040

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
https://github.com/civicrm/civicrm-core/pull/20040

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton I think your missing the additional commit with the formatting?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I think if we port this we can leave the issue open but remove the regression tag (as there will be no known instances but the visibility might be helpful)

**Comment by seamuslee001** [comment]
@eileenmcnaughton I think you need https://github.com/civicrm/civicrm-core/pull/20074 as well right?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 yes - added

**Pull request merged**
