### PR TITLE
(WIP) add currency column to membership type minimum price

### PR DESCRIPTION
**Pull request by Christophenkoa**
Overview
----------------------------------------
We are altering the membership type table by adding a new column currency.

Before
----------------------------------------
When creating a membership-type, the minimum amount fee is required without any way to choose a currency associated with.

proof

In the db schema there is no currency column in the membershipType table: 
gsoc2

After
----------------------------------------
The change is made on the db schema
gsoc

Technical Details
----------------------------------------

Comments
----------------------------------------
I am new with civicrm stuff then I really need support before the next release of CiviCRM

### CODE REVIEW

**Comment by Christophenkoa** [comment]
@mattwire thanks. Let me change and update my pull request

**Comment by mattwire** [comment]
Hi @Christophenkoa you need to run `/bin/setup.sh -g` to "regenerate" the DAO and sql files. Then you should commit the changes that it makes to this PR (you will add `CRM/Member/DAO/MembershipType.php` and I think `civicrm_generated.mysql`).

**Review by mattwire — CHANGES_REQUESTED** [review]
Hi @Christophenkoa you need to run `./bin/setup.sh -g` to "regenerate" the DAO and sql files. Then you should commit the changes that it makes to this PR (you will add `CRM/Member/DAO/MembershipType.php` and I think civicrm_generated.mysql).

**Comment by mattwire** [comment]
Hi @Christophenkoa Thankyou for all your work on this. I have reviewed and it is good - it works well.  But I am going to close this because we ran out of time to develop this further (for example making it available on the UI and making other parts use the currency option). We can re-open in the future if we do get time (eg. a future gsoc project).

**Pull request closed without merging**
