### PR TITLE
dev/drupal#43 Update composer requirement on PSR Log and civicrm-cxn-…

### PR DESCRIPTION
**Pull request by seamuslee001**
…rpc to fix compatability issue with psr/log from Drupal8

Overview
----------------------------------------
This updates the civicrm-cxn-rpc and psr/log requirements so that the version of psr/log will be 1.1 installed. the cxn has just had a new release with the updated log requirement done which is the only change between the releases. This fixes a compatibility issue with Drupal 8

Before
----------------------------------------
Compatibility issue with Drupal 8 over version of psr/log to install

After
----------------------------------------
No issue

ping @totten @eileenmcnaughton @MegaphoneJon @mlutfy

### CODE REVIEW

**Comment by mlutfy** [comment]
Seems good to me.

**Comment by mlutfy** [comment]
@seamuslee001 dev/mail#34 seems like the wrong ref? Is this dev/drupal#43 ?

**Comment by seamuslee001** [comment]
@bgm yes woops

**Comment by mlutfy** [comment]
Mind also squashing your commit description?

**Comment by seamuslee001** [comment]
done @mlutfy

**Comment by seamuslee001** [comment]
@mlutfy would you consider it as "merge on pass"

**Pull request merged**
