### PR TITLE
Blank out membership_online_receipt - text version

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Blank out membership_online_receipt - text ve

As with the offline event receipt this reduces the maintenance effort, given that we generate a text version anyway

Before
----------------------------------------
We ship a text version of the online_membership_receipt

After
----------------------------------------
We no longer ship it - people who have not customised it & new installs will be updated to blank 

A text version is generated on send

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by demeritcowboy** [comment]
api_v3_ContributionPageTest.testSubmitMembershipBlockNotSeparatePaymentWithEmail
    api_v3_ContributionPageTest.testSubmitMembershipBlockNotSeparatePaymentZeroDollarsWithEmail
    api_v3_ContributionPageTest.testSubmitMembershipBlockIsSeparatePaymentPayLaterWithEmail
    api_v3_ContributionPageTest.testSubmitMembershipBlockIsSeparatePaymentWithEmail
    api_v3_ContributionPageTest.testSubmitMembershipBlockIsSeparatePaymentZeroDollarsPayLaterWithEmail
    CRM_Core_Payment_AuthorizeNetIPNTest.testIPNPaymentMembershipRecurSuccessNoLeakage
    CRM_Core_Payment_AuthorizeNetIPNTest.testIPNPaymentMembershipRecurSuccessNoLeakageOnlineThenOffline
    CRM_Core_Payment_BaseIPNTest.testSendMailMembershipObjects
    CRM_Core_Payment_BaseIPNTest.testSendMailMembershipObjectsNoLeakage
    CRM_Core_Payment_BaseIPNTest.testSendMailMembershipWithoutLoadObjects
    CRM_Upgrade_Incremental_BaseTest.testMessageTemplateUpgrade
    CRM_Upgrade_Incremental_BaseTest.testMessageTemplateUpgradeAlreadyCustomised
    CRM_Upgrade_Incremental_BaseTest.testMessageTemplateGetUpgradeMessages

**Comment by eileenmcnaughton** [comment]
I fixed up the tests 

1) the string 'Membership Type General' is tested a bit but the space between Type & General is no longer a space. It also doesn't seem to be consistent between my local & jenkins so I stopped testing it as a single string
2) the upgrade tests were specifically testing against the content of the online memberhsip receipt text version - which is wiped out here. I switched to the html version

**Comment by colemanw** [comment]
[api_v3_ContributionPageTest.testSubmitMembershipBlockIsSeparatePaymentPayLaterWithEmail](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6263/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/testReport/junit/(root)/api_v3_ContributionPageTest/testSubmitMembershipBlockIsSeparatePaymentPayLaterWithEmail/)
[api_v3_ContributionPageTest.testSubmitMembershipBlockIsSeparatePaymentZeroDollarsPayLaterWithEmail](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6263/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/testReport/junit/(root)/api_v3_ContributionPageTest/testSubmitMembershipBlockIsSeparatePaymentZeroDollarsPayLaterWithEmail/)

**Comment by demeritcowboy** [comment]
```
CRM_Contribute_Form_Contribution_ConfirmTest.testSubmitContributionPageWithPriceSetQuantity with data set #0
CRM_Contribute_Form_Contribution_ConfirmTest.testSubmitContributionPageWithPriceSetQuantity with data set #1
```

**Comment by demeritcowboy** [comment]
All that just to really do `$str = '';` ...

**Comment by eileenmcnaughton** [comment]
@demeritcowboy sigh

**Pull request merged**
