### PR TITLE
dev/core#5163 Afform - Fix conditionals to support array values

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes https://lab.civicrm.org/dev/core/-/issues/5163

### CODE REVIEW

**Comment by allinappliadmin** [comment]
I applied this commit but I'm not getting the pop-up to set the condtionnal logic (on the alpha).
In the console, I'm getting these errors using greenwich theme (if of any help):

Impossible de vérifier <input pattern='^civicrm\/[-0-9a-zA-Z\/_]+$'> car le modèle (pattern) n’est pas une expression régulière valide : invalid character in class in regular expression

image

**Comment by colemanw** [comment]
@allinappliadmin there are a lot of PRs to manage. I'm going to go ahead & merge this one as @guyiac was able to test it at the sprint.

**Comment by guyiac** [comment]
I tested this against the pr demo site and it appears to work as expected.

**Comment by colemanw** [comment]
@allinappliadmin which CMS are you using? Wordpress?

**Comment by allinappliadmin** [comment]
Condition to show 'first name' if prefix is 'Mme'

image

Doesn't show up

image

**Comment by allinappliadmin** [comment]
> @allinappliadmin which CMS are you using? Wordpress?

I was using a test form that didn't work. Creating a new one and operators appear

image

the translation is also weird with a mix of French and English

**Comment by colemanw** [comment]
@allinappliadmin - glad to know it's working for you.
Yes, the translations will need to be updated.

**Comment by allinappliadmin** [comment]
> Condition to show 'first name' if prefix is 'Mme'
> 
> image
> 
> Doesn't show up
> 
> image

Actually it doesn't. There should be a 'Firstname' field but it's not showing up

**Comment by allinappliadmin** [comment]
> > Condition to show 'first name' if prefix is 'Mme'
> > image
> > Doesn't show up
> > image
> 
> Actually it doesn't. There should be a 'Firstname' field but it's not showing up

but the 'is like' operator works fine

**Comment by kcristiano** [comment]
@colemanw @guyiac I am testing this on latest master and I cannot get conditionals to work on a select field.  

This fails:

image


This fails:

image

This also fails:

image

The use case is to record only certain data based on the case type or a custom field.   Attached is the Form Builder with only standard fields.

Am I missing something or does this PR need more work?

[afformAddActivityCase-conditionals.tgz](https://github.com/user-attachments/files/16181553/afformAddActivityCase-conditionals.tgz)

**Comment by colemanw** [comment]
@kcristiano I think "Case Type" is a weird field in the schema because it was originally implemented as serialized but in practice a case can only have one type.
Is that the only field you're having trouble with or are there others?

**Comment by kcristiano** [comment]
> @kcristiano I think "Case Type" is a weird field in the schema because it was originally implemented as serialized but in practice a case can only have one type. Is that the only field you're having trouble with or are there others?

:)  It's what I need, but I will now try another.   I did try case status as another.   Let me see what else I can try,

**Comment by kcristiano** [comment]
OK so it does work with 

`Constituent Information: Most Important Issue`  and `Constituent Information: Marital Status`

So My issue is that Case Status and Case Type won't work to set the conditionals.  

Do we need to open another issue for this?

**Comment by colemanw** [comment]
I was wrong, case_type may have been multivalued in the past but it's been fixed, so ought to work. Yep better open an issue.

**Comment by colemanw** [comment]
@kcristiano is this still a bug? Is there an issue for it?

**Comment by kcristiano** [comment]
https://lab.civicrm.org/dev/core/-/issues/5163#note_170998   updated, but yes this is still an issue.

**Pull request merged**
