### PR TITLE
[REF] Upgrade DomPDF to v0.8.6

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
Upgrades DomPDF version to v0.8.6

Before
----------------------------------------
DomPDF Version 0.8.5 used

After
----------------------------------------
DomPDF version 0.8.6 used

Technical Details
----------------------------------------
Fixes a minor security issue and also fixes a few other issues https://github.com/dompdf/dompdf/releases/tag/v0.8.6

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 given we have just cut the rc I'm OK merging this - since we do generally try to keep this up to date - any thoughts?

**Comment by seamuslee001** [comment]
I had tested this on a firefox page and worked so lets merge it tbqh

**Comment by eileenmcnaughton** [comment]
@seamuslee001 ok - I'm fine with merging if you fix up the PR template - we should link to the changelog changes in that

**Comment by seamuslee001** [comment]
Updated now @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
Cool - just noting this requires php7.1 so any ESR backport is out

**Comment by eileenmcnaughton** [comment]
This might require some action?

 Note on resource references: Because of the changes in resource security, some resources (images, external stylesheets) that would previously load with the default settings may not longer load. To ensure compatibility with this release ensure the remote resources can be loaded and that any local filesystem resources are within the directory specified by the chroot setting. By default, chroot is set to the Dompdf directory. Information on how to change these settings can be found in the readme section on setting options.

This update addresses the following announced vulnerabilities:

**Comment by colemanw** [comment]
@seamuslee001 I don't really understand how Composer works, but why is the `"content-hash"` not getting updated at the top of the file in this PR?

**Comment by seamuslee001** [comment]
@colemanw checking this suggests that https://stackoverflow.com/questions/46185777/is-content-hash-a-mandatory-part-of-composer-lock it is only when things change in composer.json that the hash gets updated

**Pull request merged**
