### PR TITLE
CRM-16467-first go at action menu changes

### PR DESCRIPTION
**Pull request by joannechester**

### CODE REVIEW

**Comment by kurund** [comment]
jenkins, test this please

**Comment by joannechester** [comment]
I think I need to make some associated changes on other action menus, so this should be a WIP for now. ( See https://issues.civicrm.org/jira/browse/CRM-16467 for details.)

**Comment by joannechester** [comment]
All changes made now

**Comment by kurund** [comment]
jenkins, test this please

**Pull request closed without merging**
