### PR TITLE
dev/core#3077 - CiviCase - Call hooks when creating relationships

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Refactors creating relationships when opening a new case to use ~~APIv4~~ (temporarily using the BAO method), which calls hooks.

Before
----------------------------------------
No hooks called.

After
----------------------------------------
~~Api used~~, hooks called, code easier to read.

Technical Details
---------------
The attempt to use APIv4 failed if the case client is an Organization, due to some extra (faulty?) validation & processing which happens at that layer. IMO that needs tests and fixing, but for now, this calls `BAO_Relationship::add()` directly.

Comments
---------------------
I stepped through the unit tests and confirmed that this function has good test coverage.

### CODE REVIEW

**Comment by seamuslee001** [comment]
Looks fine to me @mattwire @demeritcowboy work for you?

**Comment by mattwire** [comment]
Works for me :-)

**Comment by demeritcowboy** [comment]
One of the exact same things happens as in the previous attempt to use api: It crashes for org clients. I haven't tested further because I now expect all the same issues will come up.

**Comment by colemanw** [comment]
@demeritcowboy do you remember what issue or PR that happened before?

**Comment by demeritcowboy** [comment]
I had linked to it in my comment on https://github.com/civicrm/civicrm-core/pull/22810#issuecomment-1047297842 - it was https://github.com/civicrm/civicrm-core/pull/15030

**Comment by colemanw** [comment]
Thanks for the `r-run` @demeritcowboy. I've updated the description & added the label.

**Pull request merged**
