### PR TITLE
CRM-16675 remove unused function composeMessage on ContributionPage c…

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
…lass

On grepping I find only composeMessageArray rather than any calls to this function. I'm pretty sure it has been an orphan for many many releases - but would like another pair of eyes on if possible.

There are some other unused functions that I will add to the ticket & do as separate PRs if I get to them.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
NB - also a couple of unused variables removed

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
failure is unrelated

**Comment by eileenmcnaughton** [comment]
@colemanw any chance you can double check I'm not missing something here before merge. I think I've been chickening out of removing this function since around 3.4

**Comment by colemanw** [comment]
Couldn't find any kind of reference to it, except once in a comment.

**Pull request merged**
