### PR TITLE
Remove recordPayment function.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Looks like we actually got rid of usage of this function - it was originally called by the AdditionalPayment form - but that form now calls Payment.create

Before
----------------------------------------
Function exists

After
----------------------------------------
Gone

Technical Details
----------------------------------------
We've been really clear that people should be using the api to make payments for a long time now so I don't think we need to worry about external code calling this

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by magnolia61** [comment]
Congrats on this milestone step of a long way working to switch over to payment.create :-

**Comment by eileenmcnaughton** [comment]
Thanks @magnolia61 - there has been a lot of mess to fight through

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
So i did the following

```
seamus@civicrmdevelopment:~/buildkit/build/47-test/sites/all/modules/civicrm$ grep -ir 'recordPayment' *
CRM/Contribute/Form/AbstractEditPayment.php:        $recordPaymentLink = CRM_Utils_System::url('civicrm/payment',
CRM/Contribute/Form/AbstractEditPayment.php:        CRM_Core_Session::setStatus(ts('Please use the <a href="%1">Record Payment</a> form if you have received an additional payment for this Partially paid contribution record.', [1 => $recordPaymentLink]), ts('Notice'), 'alert');
CRM/Contribute/Form/ContributionView.php:      $this->assign('addRecordPayment', TRUE);
CRM/Contribute/BAO/Contribution.php:  public static function recordPaymentActivity($contributionId, $participantId, $totalAmount, $currency, $trxnDate) {
CRM/Financial/BAO/Payment.php:    CRM_Contribute_BAO_Contribution::recordPaymentActivity($params['contribution_id'], CRM_Utils_Array::value('participant_id', $params), $params['total_amount'], $trxn->currency, $trxn->trxn_date);
CRM/Financial/BAO/Payment.php:  public static function recordPayment($contributionId, $trxnData, $participantId) {
release-notes/5.12.0.md:- **[REF] Extract recordPayment portion
templates/CRM/Contribute/Form/ContributionView.tpl:  {if $addRecordPayment}
templates/CRM/Contribute/Form/ContributionView.tpl:{if $addRecordPayment}
templates/CRM/Event/Form/EventFees.tpl:{assign var=isRecordPayment value=1 }
templates/CRM/Event/Form/EventFees.tpl:          {assign var=isRecordPayment value=0 }
templates/CRM/Event/Form/EventFees.tpl:    {if $accessContribution and ! $participantMode and ($action neq 2 or !$rows.0.contribution_id or $onlinePendingContributionId) and $isRecordPayment and ! $registeredByParticipantId }
``` 
Confirmed that recordPayment function is no longer called merging

**Pull request merged**
