### PR TITLE
[REF] Refactor to switch from pear HTTP Request class to using Guzzle

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This refactors a couple of calls from using the PEAR HTTP_Request class to using guzzle

Before
----------------------------------------
Pear HTTP_Request class used

After
----------------------------------------
Guzzle used

ping @eileenmcnaughton @demeritcowboy

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by demeritcowboy** [comment]
I tested the google-guzzle one. Works.

For the other one you [need an approved account](https://docs.civicrm.org/user/en/latest/initial-set-up/addresses/#configuring-address-standardization-to-work-with-usps) right? Codewise it's not exactly the same code pattern as the google change, so I can't confirm it.

**Comment by seamuslee001** [comment]
@demeritcowboy I guess my thinking is that 1) does it still produce the same urls as before and 2) is the getStatusCode and getRequestBody appropriate swap outs here?

**Comment by demeritcowboy** [comment]
Ok. I like clicking on things though 👉 ⏏️ 

I can take a look code-wise.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy if your clicking verifies this ul https://github.com/civicrm/civicrm-core/pull/17420/files#diff-f157d159ec8c521a9559a994cf3d265cR72 is unchanged I'm comfortable merging

**Comment by demeritcowboy** [comment]
The url is the same.

BEFORE:
```
GET /something?API=Verify&XML=%3CAddressValidateRequest%20USERID%3D%22abc%40ljdsalkf.com%22%3E%3CAddress%20ID%3D%220%22%3E%3CAddress1%3E%3C%2FAddress1%3E%3CAddress2%3E123%20Main%20St.%3C%2FAddress2%3E%3CCity%3EAaaaaaa%20Bbbb%3C%2FCity%3E%3CState%3EAL%3C%2FState%3E%3CZip5%3E12345%3C%2FZip5%3E%3CZip4%3E%3C%2FZip4%3E%3C%2FAddress%3E%3C%2FAddressValidateRequest%3E HTTP/1.1
User-Agent: PEAR HTTP_Request class ( http://pear.php.net/ )
Connection: close
Accept-Encoding: gzip
Host: www.usps.gov
```

AFTER:
```
GET /something?API=Verify&XML=%3CAddressValidateRequest%20USERID%3D%22abc%40ljdsalkf.com%22%3E%3CAddress%20ID%3D%220%22%3E%3CAddress1%3E%3C%2FAddress1%3E%3CAddress2%3E123%20Main%20St.%3C%2FAddress2%3E%3CCity%3EAaaaaaa%20Bbbb%3C%2FCity%3E%3CState%3EAL%3C%2FState%3E%3CZip5%3E12345%3C%2FZip5%3E%3CZip4%3E%3C%2FZip4%3E%3C%2FAddress%3E%3C%2FAddressValidateRequest%3E HTTP/1.1
Host: www.usps.gov
User-Agent: GuzzleHttp/6.2.1 curl/7.64.0 PHP/7.3.12
```

**Comment by seamuslee001** [comment]
Merging this based on @demeritcowboy 's review and @eileenmcnaughton 's comment

**Pull request merged**
