### PR TITLE
CRM-15903 - Cleanup class inheritance of CRM_Utils_System_* functions

### PR DESCRIPTION
**Pull request by colemanw**
https://issues.civicrm.org/jira/browse/CRM-15903

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Coleman - just a note - the next level of phpcs tightening (enforced in drupal but not in civi at this point) is a full stop at the end of a function comment - probably worth doing when you add new comments

**Comment by colemanw** [comment]
Thanks @eileenmcnaughton I was moving around comments here rather than writing them from scratch but I'll try to remember that for the future. Might be good to do a mass-regex to fix capitalization and punctuation issues.

**Comment by totten** [comment]
So it sounds like "php -l" is failing on CRM/Utils/System/Drupal.php one line 348:

```php
(new CRM_Utils_System_Drupal8())->loadBootStrap(array(), FALSE);
```

This line is valid in PHP 5.4+ but is invalid in PHP 5.3 (which is used on all our servers and is the official target). In 5.3, one must break that out into two statements:

```php
$system = new CRM_Utils_System_Drupal8();
$system->loadBootStrap(array(), FALSE);
```

I did a quick search ( find -name '*.php' -exec php53 -l {} \;  | grep -v 'No syntax errors detected' ), and it looks like CRM/Event/Form/ParticipantFeeSelection.php may also have a pre-existing PHP 5.4-ism (although, for some reason, my local copy of PHP 5.3 won't specify what it is...).

**Comment by colemanw** [comment]
Thanks @totten that seems to have fixed it. I'm really looking forward to dropping support for php 5.3 (have I mentioned that I'm a big fan of the compact array format).

**Comment by colemanw** [comment]
Wow the tests actually passed :D

**Pull request merged**
