### PR TITLE
[REF] Stop passing cacheKey to refillCache

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Minor function cleanup

Before
----------------------------------------
Unnecessary param passed in

After
----------------------------------------
Unnecessary param removed.

Technical Details
----------------------------------------
The function is only called from one place & there is no need to pass it in

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw minor related cleanup - I'm going to start on next round soon

**Comment by mattwire** [comment]
@eileenmcnaughton Needs rebase

**Comment by totten** [comment]
Agree it needs a rebase. Otherwise, merge on pass.

**Comment by eileenmcnaughton** [comment]
rebased

**Comment by seamuslee001** [comment]
Merging as per @totten 's comment

**Pull request merged**
