### PR TITLE
CRM-18435: Change logic of CRM_Utils_Array::formatArrayKeys ...

### PR DESCRIPTION
**Pull request by ghost**
…to check array lengths, reinstate use when building membership_{type,status}_id options for saved searches.

### CODE REVIEW

**Comment by seamuslee001** [comment]
does this break smart groups created in 4.6 or greater ?

**Comment by agileware** [comment]
@seamuslee001 We've tested both pre-4.6 groups and post-4.6 groups.  Test cases:
- [1 => 1] // Old format, single type / status with ID 1
- [1] // New format, single type / status with ID 1 (tested since initial PR)
- [1 => 1, 2 => 1, 3 => 1] // Old format, multiple type / status
- [2 => 1, 1 => 1, 3 => 1] // Old format, multiple type / status, 1 as 1st key
- [1, 2, 3] // New format, multiple type / status
- [2, 1, 3] // New format, multiple type / status, 1 as 1st key (Broken in 4.6.13, 4.6.14)

**Comment by seamuslee001** [comment]
@agileware cool yeh i just tested updating a smart group on our system that we new that was working and seems to still be working and the updated formValues look ok. 

@eileenmcnaughton I think this is safe, I tested on AUG ubox updating smart group created since our 4.6 upgrade. will dm you the form values if you can just check it that would be grand

**Comment by eileenmcnaughton** [comment]
Ok - this is too late for this QA cycle but hopefully can be included next month

**Comment by davejenx** [comment]
Tested this PR successfully on a 4.6.16 site with lots of smart groups: reported as working correctly both for smart groups created before the 4.6 upgrade and those created since.

**Comment by totten** [comment]
I don't fully understand the patch, but it sounds like this is a contact change in a generic helper function. Based on `grep`, the helper function appears to be used in three places:
 1. `CRM/Contact/BAO/Query.php` -- `legacyConvertFormValues()`
 2. `CRM/Core/BAO/CustomField.php` -- `formatDisplayValue()` (handling checkbox fields)
 3. `CRM/Contact/BAO/Contact.php` -- `add()` (handling `preferred_communication_method`)
 
Sounds like it's been checked in the first case. Has anyone determined whether the change makes sense in the other cases?

**Comment by eileenmcnaughton** [comment]
I'm taking a look at this now. I'm inclined to add a new function & deprecate the existing one to reduce the risk Tim mentions - although it does appear to me that the changes to formatArray are improvements I worry that even good change could have unintended consequences. Will comment more soon.

**Comment by eileenmcnaughton** [comment]
I'd like to replace this with this PR

https://github.com/civicrm/civicrm-core/pull/8600/files

It takes all your logic but a couple of differences

1) per my comment above - I duplicated & deprecated formatArrayKeys rather than altering it.
2) unit tests :-)
3) I hit some issues on 'group' so I backed up passing the extra params through the array formatting function. I realise that you indicated it fixes contact_type & tags - so this is not completely an improvement. But, I was getting fatal errors on groups in some cases. So, I opted to keep the fix narrow & look at that as a second round.

Any thoughts / concerns? If you are happy with my PR please comment to that effect on it & I can merge it.

I will submit the same tests & a modified set of the changes against master

**Comment by eileenmcnaughton** [comment]
4.6 #8600 master #8602

**Comment by eileenmcnaughton** [comment]
NB thanks to @seamuslee001 for the test examples

**Comment by eileenmcnaughton** [comment]
no not @seamuslee001  - you are unthanked. Thanks to @agileware :-)

**Comment by agileware** [comment]
@eileenmcnaughton Tested this out and it seems to work okay.  No problems here - the scope of our PR is probably a bit wrong now anyway.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
Opps this is the one we are closing isn't it?

**Pull request closed without merging**
