### PR TITLE
CRM-21601: Support non deductible token in contribution and event receipt

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Support a Non-deductible amount for a) Line Items, and b) the whole contribution in the following:
1) Contributions - Receipt (off-line), Contributions - Receipt (on-line)
2) Events - Receipt only, Events - Registration Confirmation and Receipt (off-line), Events - Registration Confirmation and Receipt (on-line)

Technical Details
----------------------------------------
The patch enables the user to choose ```$non_decutible_amount``` available against a whole contribution or each line-item.

---

 * [CRM-21601: Support non deductible token in contribution and event receipt](https://issues.civicrm.org/jira/browse/CRM-21601)

### CODE REVIEW

**Comment by Edzelopez** [comment]
Tested PR, looks good.

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by colemanw** [comment]
@Edzelopez can you please give more details about what you tested and why it looks good? See https://docs.civicrm.org/dev/en/latest/standards/review/

**Comment by Edzelopez** [comment]
@colemanw apologies for the vague QA result. I tested this against event participants offline and online, and contributions offline and online. I was able to get a value for the {$non_deductible_amount} variable in smarty.

Contribution offline receipt:
token

Value in email:
email

Few changes I would like to add:

1. Enable the non deductible amount as a token that can be selected from the Tokens list.
2. Format the variable so that it appears as an amount rather than an integer using 
    `CRM_Utils_Money::format`

**Comment by monishdeb** [comment]
@Edzelopez please check my inline reply:

> 1. Enable the non deductible amount as a token that can be selected from the Tokens list.
I saw that for other amount token like totalAmount there were using modifier crmMoney. So I thought in these case we need to use ```$non_deductible|crmMoney:$currency|string_format:"%10s"``` 
> Format the variable so that it appears as an amount rather than an integer using
CRM_Utils_Money::format
It's strange that we are not exposing any contribution token so that we can choose these token from token widget, for these message template. So I am not sure if we ONLY need to expose non_deductible token in token widget all contri tokens. For later we need to create a separate issue.

**Comment by Edzelopez** [comment]
@monishdeb yes, I found it quite strange as well that the tokens related to contributions are not exposed on a receipt that is supposed to go out for various contributions. Maybe some input from @JoeMurray @eileenmcnaughton or @colemanw will help here on if we should plan on supporting selection of contribution related tokens here.

**Comment by monishdeb** [comment]
On further investigation, I found that for message templates, only Contact and Address tokens are available to choose from widget because these tokens are generally supported on all other kinds of templates. However, for specific tasks like 'Thank-you Letter for Contributions (PDF)' and 'Send Email' via 'Find Contribution' search form, contribution tokens are exposed and available to choose. 

Likewise if somehow we can indicate the purpose of a message template, like template used for backoffice contribution, the contribution token will only be exposed along with general tokens, then that would be a great enhancement.

**Comment by JoeMurray** [comment]
Tokens associated with contributions should be available when mailing is done via Find Contributions (or Advanced Search returning contributions) followed by search results action of Email - send now, Receipts - print or Email, or Thank-you letters - print or email. 

I'm not familiar with how the line item tokens used for receipts (and perhaps thank you letters) work. I'd like the non-deductible amount for each line item to follow the same pattern as existing line item tokens for amount and description/label.

Edsel, could you supplement the testing on event and contribution line items with membership as well?

**Comment by eileenmcnaughton** [comment]
I feel like the msg_template has a workflow_id that links to an option_value and the option value has a component_id attached. We don't use it - but if we did put components on (at least for contributions in the first instance) we could add them.

**Comment by JoeMurray** [comment]
Could you elaborate on what would be a generic approach to providing line item values needed for tax receipts? Do you want something supporting other line item fields, other contribution fields, all compnent fields?

**Comment by eileenmcnaughton** [comment]
Hmm - yeah - I guess we need to dig in the code but adding a one-liner in 7 different places looks suspicious to me. This is not an area of codeI have high confidence in so we would need a bunch of tests at minimum but also, if it is a contribution token it should be showing up in the contribution tokens.

ALSO, we haven''t really resolved how we assign contribution level vs line item level to the receipts. I did a PR to assign an array of the financial types used in a PR to the template but wound up closing it because it was a bit piecemeal in terms of us not really having figured out a solid approach to tokens & maybe pushing back on just adding more in

**Comment by JoeMurray** [comment]
So:
1. Totally agree we should be doing some code improvement to go with this. Tests are the best place to start.
2. So in US there is no special tax receipt needed, unlike the Cdn Tax Receipts extension. Just showing the deductible amount (based on subtracting the non-deductible from the total) is sufficient, so long as it is indicates what the donation was for in terms of different line items. So I don't think there is any need for tokens. Should we perhaps modify the existing receipts to include more details like this? That seems like stirring a pot that will cause trouble.
3. Is there a design problem with the current approach to assigning values for use by Smarty from contributions and line items? We could try to tackle a bit of cleanup, but I'm not clear what it should be.
4. @monishdeb can you see any code cleanup you could do in these files that would reduce their toxicity?
5. A different problem I see is that we didn't solicit reviews and QA beyond you and Coleman, and the PR was stale after 5 months. If we managed to get feedback on a newly submitted PR that included tests and maybe did some other improvements would that be sufficient?

**Comment by eileenmcnaughton** [comment]
Right so really the tests are the biggest thing. The secondary one is that we shouldn't be assigning values to email templates in multiple places = we should be working towards only doing it in one. I think the change should at least take some steps in that direction.

I guess my other doubts are probably lower priority than those 2

**Comment by JoeMurray** [comment]
Thanks for this ore specific and actionable feedback. @monish could you take a look at possibly refactoring to reduce the number of places doing the assigning of values to templates and going ahead if it looks promising eg passing args in each place to function that does it.

**Comment by eileenmcnaughton** [comment]
@monishdeb I'm going to close this in favour of some new ones. I think maybe one in api_v3_ContributionPageTest would make sense & use this fn
    $this->swapMessageTemplateForTestTemplate();

**Pull request closed without merging**
