### PR TITLE
CRM-18353 skip url from IDS check

### PR DESCRIPTION
**Pull request by sunilpawar**
- [CRM-18353: allow to skip extension url from IDS check](https://issues.civicrm.org/jira/browse/CRM-18353)

### CODE REVIEW

**Comment by sunilpawar** [comment]
build failed but nothing related to changes submitted

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
NB - what JIRA does this relate to?

**Comment by sunilpawar** [comment]
CRM-18353

**Comment by josephlacey** [comment]
@yashodha @eileenmcnaughton This same patch for 4.7 was merged in, but not this 4.6 backport.  I'm not sure exactly how to test this, but presumably if the former is fine, the latter is.

**Comment by eileenmcnaughton** [comment]
Looking at the code it seems really safe - ie it's just adding a hook & if that was OK in 4.7 then I feel pretty good on 4.6

**Comment by PalanteJon** [comment]
@josephlacey I actually asked Tim about testing hooks three days ago and he sent me this (below).  I know this is already merged, but themoreyouknow.jpg

Example of testing a hook -- api_v3_ContactTest::testGetQuickEmailACL()          

note how it calls $this->hookClass->setHook('civicrm_aclWhereClause', array($this, 'aclWhereNoBobH'));

**Pull request merged**
