### PR TITLE
CRM-21677 - more report clean up

### PR DESCRIPTION
**Pull request by yashodha**
Overview
----------------------------------------
in continuation of #12698

Before
----------------------------------------
Pledged But not Paid Report
pnb_before
Campaign Survey Details
survey_before
Walklist
walk_before

After
----------------------------------------
Pledged But not Paid Report
pnb_after
Campaign Survey Details
survey_after
Walklist
walk_after

Comments
----------------------------------------
standardizes the state province display in some reports

### CODE REVIEW

**Comment by pradpnayak** [comment]
Code looks good and have tested on Survery Details, Pledged but not Paid Report and Walklist report.

Good to merge!

**Comment by eileenmcnaughton** [comment]
Thanks for the patch @yashodha  & the review @pradpnayak

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by yashodha** [comment]
@eileenmcnaughton @pradpnayak thanks!

**Pull request merged**
