### PR TITLE
WIP Allow Contribution.Get to retrieve by trxn_id

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Towards https://lab.civicrm.org/dev/financial/issues/57

See https://github.com/civicrm/civicrm-core/pull/15166 for the Payment.Get API

We want to deprecate trxn_id on the contribution entity in favour of the one on payment (financial_trxn) but we can't retrieve any of them using the API!  This PR fixes that so that:
* Contribution.Get will return contributions where the trxn_id is matched on the contribution or any payments linked to the contribution.  An additional array property `payment_trxn_id` contains any trxn_ids found on payments.

Before
----------------------------------------
Not possible to work with payment trxn_ids via API

After
----------------------------------------
Can use payment trxn_ids via API in a sensible way.  Makes it much easier for payment processors to identify contributions based on transaction IDs passed to them from the processor.

Technical Details
----------------------------------------
Contribution.get additionally calls Payment.get to identify any contributions that have the trxn_id on a related payment.

Comments
----------------------------------------
@eileenmcnaughton @KarinG @adixon @monishdeb Be good to get thoughts / review here.  This should help us work towards https://lab.civicrm.org/dev/financial/issues/57

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I'm really undecided about this - I think we need to make the trxn_id on payments much more visible but I'm not sure about melding it in with contribution.trxn_id - which in theory would be redundant once payment.trxn_id is fully available. I can't quite decide whether this is a path to get us to be able to switch over or a way to be stuck forever with contribution.trxn_id being mixed in with payment.trxn_id

Supporting being able to retrieve trxn_id from payment.get & filter by it is a clear yes & that should be able to move through fairly quickly as a separate PR - we have tests that should be pretty easy to tweak to cover it too under api_v3_PaymentTest

**Comment by adixon** [comment]
I'm convinced by Eileen here - yes to add a new payment.get by transaction id, but don't mix it up with the contribution.get looking through the payment transactions.

**Comment by mattwire** [comment]
@eileenmcnaughton @adixon Thanks for looking. 
I worked this through when developing the new Authorize.net extension and the Contribution.get with trxn_id seemed like a much better way to get the information required to do a repeattransaction: https://github.com/mattwire/com.donordepot.authnetecheck/blob/master/CRM/Core/Payment/AuthNetIPNTrait.php#L296  (Contribution.get is named Mjwpayment.get_contribution here because it's the modified version).
In the code link above, the alternative would be to do:
1. Payment.get to look for matching trxn_ids on the payments.
2. Contribution.get to look for matching trxn_ids on the contributions (because it's just as likely to be saved there at the moment depending on how the contribution was created).
3. Look through the returned arrays for contribution IDs that were returned, hope there was only one and then use it.

The same will be required for the updated extension.  If we settle on the idea that a contribution represents a payment processor "order" and a payment an individual "transaction" then we may well get multiple IPN responses with the same transaction IDs (eg. fail, retry, fail succeed) or IPN responses with difference transaction IDs.

For the first contribution submitted it is by no means guaranteed where the `trxn_id` will have been recorded - it may be on one of the `civicrm_financial_trxn` records or the `civicrm_contribution` records.  Having to run two separate API functions makes it much more complex to code and also much more complex to deprecate one in the future.  By being able to get `trxn_id` for payments/contributions via either payment or contribution API keeps CiviCRM core in ultimate control of how the field on `civicrm_contribution` may be deprecated in the future because we can change the internals without affecting the API output.

I was pretty surprised when I found that Payment.get didn't allow you to search by `trxn_id` but that means we can be pretty certain that every payment processor is either using unsupported interfaces or the Contribution.get API (which won't retrieve trxn_ids linked to payments at present).

**Comment by mattwire** [comment]
Closing this for now as there's a few other changes need considering

**Pull request closed without merging**
