### PR TITLE
CRM-21637 - Search Criteria for Card Type ID and Card Number not resp…

### PR DESCRIPTION
**Pull request by yashodha**
…ected in Batch

Overview
----------------------------------------
Steps to replicate
-----------------------
1. Create a new accounting batch
2. Filter on Card Type ID and Card Number, click search
3. It shows all results irrespective of credit card type and number

Before
----------------------------------------
criteria

result_before

After
----------------------------------------
after

### CODE REVIEW

**Comment by yashodha** [comment]
@monishdeb Can you please check this?

**Comment by pradpnayak** [comment]
@yashodha The SS for after looks wrong.

**Comment by yashodha** [comment]
@pradpnayak What looks wrong, can you please elaborate?

Also it seems if multiple options are selected for filter criteria it is NOT working
eg, Filter on payment instrument = credit card, debit card fails with DB error while it works for single option

@monishdeb it is because  where is not built properly

**Comment by eileenmcnaughton** [comment]
test fail looks related (style issue)

**Comment by yashodha** [comment]
@eileenmcnaughton @monishdeb 
all tests pass

**Comment by monishdeb** [comment]
@yashodha actually like Pradeep said, I am working on an issue about refactoring the code to replace the query with ```EntityFinancialTrxn``` api to retrieve batch transactions and here's the PR  https://github.com/civicrm/civicrm-core/pull/10395 which is 70% done and about to complete by this week itself. 

 Although the current patch fixes the issue as I have tested on my local and ok to merge. But I am afraid the current fix will be obsolete as it will be replaced by #10395 .

**Comment by pradpnayak** [comment]
@yashodha  I meant screenshot(SS) you attached initial was of some report. I guess you updated it.

**Comment by eileenmcnaughton** [comment]
@monishdeb do you want to make a call here  - this is pretty trivial so I think it is probably OK to be merged. The lack of tests gives me pause but I think it could squeak through without them & it seems the bigger change got deprioritised / too hard.

**Comment by monishdeb** [comment]
@eileenmcnaughton I agree, its a trivial but essential fix. Earlier I was hoping to complete the refactoring changes made in #10395 but it will take a long time as I encountered a limitation while changing the search query. I am happy to merge it without UT as it doesn't hit any big change plus the fix is pretty simple and straightforward.

**Pull request merged**
