### PR TITLE
dev/core#4773 - Fix APIv4 query regression

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes SearchKit crash reported in [dev/core#4773](https://lab.civicrm.org/dev/core/-/issues/4773).

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
I'll run this I guess but I can already see that it fixes the issue, I stared at this line all morning.  I just wasn't clear on whether it was necessary to convert array-based values via a loop or something.  Is `convert()` really only needed when we're comparing fields or using MySQL functions?  I can see that an array would only apply if you were using `IN` with values selected in the query.

**Comment by colemanw** [comment]
@MegaphoneJon this function is not meant to parse absolutely everything, its just trying to glean whatever scalar values it can from the `WHERE` clause to get some known values about the records being returned (for example if the `WHERE` clause includes `contact_type = 'Individual'` then we know for a fact that every contact returned will be an individual... that sort of thing).

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by MegaphoneJon** [comment]
OK - I tested this manually and it fixes the problem.  Coleman's answer explains why this is sufficient.  However, the test fail seems to relate.

**Comment by colemanw** [comment]
Test failures are all over the place, I doubt they're related
@civicrm-builder retest this please

**Comment by colemanw** [comment]
That worked! Thanks again for reporting @MegaphoneJon

**Pull request merged**
