### PR TITLE
[WIP] CRM-15861: Offline membership renewal doesn't display priceset choices

### PR DESCRIPTION
**Pull request by monishdeb**
---

 * [CRM-15861](https://issues.civicrm.org/jira/browse/CRM-15861)

### CODE REVIEW

**Comment by monishdeb** [comment]
@litespeedmarc I have created this separate PR which contains the least changes for CRM-15861 after using your patch and on top of that I have made some modification in terms of how price-set ID ,price-field value were set as default, share a common formRule with ```New Membership``` and ```Membership Renewal``` form etc. 

Yet to include:
1. Handle postprocess (if needed)
2. Include test as written in #9216 

But before proceeding further I need you to review my patch. Please have a look!

**Comment by litespeedmarc** [comment]
This is awesome.  Won't be able to get at this until the week-end.

**Comment by nganivet** [comment]
@monishdeb @litespeedmarc One of our customers need this improvement. How can we help with testing? Do you have a test plan or other instructions?

**Comment by monishdeb** [comment]
@nganivet thanks for your help. There are two ways you can test this patch:

#### via patch
```
$ wget https://github.com/civicrm/civicrm-core/pull/11182.patch
$ cd <civicrm directory>
$ git apply 11182.patch OR patch -p1 < 11182.patch
```

#### or via CMS test build
1. visit http://core-11182-4a65.test-ubu1204-5.civicrm.org 
2. login with (pradmin/pradmin1234) and test

**Comment by litespeedmarc** [comment]
@nganivet 's comment made me look at this a bit more than 5 minutes.  Still not a detailed review, but I'm not sure this patch will work.  The "payload" for price set based renewals was really in `renewMembershipPriceSet` (or something like that) done during the submit.  I think this is what @monishdeb meant by "post processing".

This looks considerably different.

The unit tests were pretty comprehensive, specially in the area of multi-org price sets.  I would definitively feel better reviewing something that showed those unit tests passing again.  This will avoid "bun fights".

**Comment by monishdeb** [comment]
@litespeedmarc agree with you, so let me add those UT and do what's necessary on form submission. As I said earlier this patch is not complete but reason why I still pinged Marc here, is to review the code I've done till now, in order to check the UX changes, if its all there. 

 @nganivet let me add those remaining changes (need another day) and I will then ask you to test.

**Comment by nganivet** [comment]
Here is the result of my tests on the CMS test build:
- for memberships initially created with a price set:
  - renewing the membership works and presents the original price set used to create the membership,
  - clicking on the 'Switch to single membership view' presents the classic membership renewal, but includes an additional 'Choose price set' section allowing to switch back to the original priceset used (ie. does not present a price set selection)
  - choosing this section returns to the original price set view (ie. does not allow to choose a different price set)
- for memberships NOT initially created with a price set:
  - renewing the membership presents the classic membership renewal, including the 'Change membership type' link, except that it does not include any 'Choose price set' section (neither the classic one nor the new one detailed above)

Comments:
- what happens if the price set is changed between the time the membership was created and the time it is renewed - can this lead to inconsistencies and/or database errors?
- why is this not possible to choose another price set when renewing a membership created with a price set?
- why is it not possible to renew the membership through a price set when it as not created with one?

Issues found:
- when renewing a membership through the same price set used for creation:
  - original choices made in the price set are not always reflected: the original membership had a checkbox item and a dollar amount item. The renewing screen shows the checkbox is checked but the dollar amount not filled out with the previous value
  - when selecting another membership type in the price set, the recorded contribution shows the correct line items but the renewed membership is still of the original type rather than the new type selected

**Comment by litespeedmarc** [comment]
1a. Good.
1b. Sounds wrong.  Used to / should just bring you back [here](https://issues.civicrm.org/jira/secure/attachment/53277/Screen%20Shot%202.png).
1c. Sounds wrong.  Used to / should bring you back to the original screen from 1a.

2a. Sounds wrong.  Used to / should bring you to [this screen](https://issues.civicrm.org/jira/secure/attachment/53277/Screen%20Shot%202.png]) so long as there are active price sets defined for the membership being renewed.

3a. Logic used to pick "most relevant" price set. If price set used at contribution covered membership type, then this price set was used.  If not, then one was picked that would cover the membership type, and the most of this contact's other membership orgs.  I had feedback from several people that this was rather heuristical and convoluted, so in the end, only the first rule was kept.  The logic became pick contribution price set.  If it doesn't cover membership type being renewed, then it doesn't and ultimately this would result in membership type getting changed once user renewed (assuming user picked a price set option for same org).
3b. It used to be / should be.
3c. So long as a price set covers the membership type being renewed, then it used to be / should be possible.

4a. The initial implementation never handled this.  The reference use case (think of it as MVP) didn't need this, so this was left in the code as `// TODO`
4b. It used to work correctly @mattwire had also identified an issue related to this which I had fixed.

**Comment by litespeedmarc** [comment]
@monishdeb any preference onto next steps?  Maybe I should see if I can re-apply 9216 "fresh"?

**Comment by nganivet** [comment]
@litespeedmarc would be happy to test another version of that patch with our use case if this helps. PLease provide URL to test site if available.

**Comment by yashodha** [comment]
some more findings:

- Used this price set (http://core-11182-4a65.test-ubu1204-5.civicrm.org/civicrm/admin/price/field?reset=1&action=browse&sid=9)
- Create an offline membership using price set with membership type General (see source, membership type and end date are correct)

cdc_mem1

Now renew using price but choose Student instead
member_renew

Results for membership type, end date and source are all wrongly calculated based on the initial select price set.
renewed_membership

For reference this is the [membership](http://core-11182-4a65.test-ubu1204-5.civicrm.org/civicrm/contact/view/membership?action=view&reset=1&cid=206&id=36&context=membership&selectedChild=member)

**Comment by monishdeb** [comment]
@nganivet @yashodha @litespeedmarc thank you all for your feedback, will address those issues in next round of changes. 

@nganivet actually I am doing the fixes in my local so I am afraid you need to reply on CMS link provided by test build.

@litespeedmarc re
> @monishdeb any preference onto next steps? Maybe I should see if I can re-apply 9216 "fresh"?

The reason behind creating this separate PR was to take the least changes from 9216 that's needed to support CRM-15861. You can help in bringing the other changes which are necessary like Unit Test, form submission changes, UI tweaks etc. by providing patch on top of my changes.  I will add those as commit on your name (as per https://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit) What ya say? 😉

**Comment by litespeedmarc** [comment]
I started on this, but find it extremely hard.  I am finding myself fixing many things that we had fixed over the course of 6-8 months with our client.

I really wish that we could have started with PR-9216, removing what we felt wasn't required instead of from scratch, and selectively applying parts of PR-9216.  @monishdeb , can we please take this approach?

Unfortunately, I only had 3-4 hours to work on this on the week-end.  By the time I got setup (lost an hour with VOL-299), and another 30 minutes with DB upgrade not working out-of-the-box (needed to run GenCode).  This only left me with about 1-2 hours, just enough time to see what's going on and make comments here, but not actually fix & test anything.

Barring changing the approach taken, the best I can do is pinpoint the parts of 9216 that are missing and/or would fix the issues pinpointed above.  Unfortunately, I will not be able to look at this again for a little while.

* The portion with `shouldIncludeChoosePriceSetOption`, and its caller in parent class, ensuring consistent price set handling.
* By removing default selection logic in `getLastPriceSetUsed` (now renamed to `getPriceSetFromEntityID`) in the scenario where membership type wasn't through a contribution, we are no longer setting `_priceSetId`/`priceSetId`, which results in user not being able to renew using a priceset (as identified by others/testers above).  Not setting an intelligible default here opens up a whole whack of workflows worms / functional bugs that can ultimately result in data loss.
* As mentioned earlier, the `submitRenewMembershipsPriceSet` was the heart / core of the changes, dealing with handling many use cases identified above.

**Comment by monishdeb** [comment]
@litespeedmarc I share the same pain. I did started with #9216 and cherry-picked your commits and started to cleanup things brick by brick and #11182 was a effort in this direction and it took me 1 day to understand, decide what's needed and think about alternatives how to simplify further. But later I realized that I need to start from scratch and use your patch to bring up the least changes needed to support this CRM-15861. So here's the limitations I faced:
1. There are huge functions ```getLastPriceSetUsed``` and ```setPriceSetDefaultsToLastUsedValues``` which I was not comfortable with and was stuck how to simplify the underlying code.
2. There were some additional changes related to bringing the set-default logic into parent function.
3. Manual handling of line-items like in ```submitAddContributionLineItemsToParams``` whereas we need rely on Membership::create() fn and bring necessary changes whats needed to be there in parameters before passing it to for processing membership.

Usually, we use to distribute large patch into meaningful chunks and create a separate PRs respectively. So it would be easy to review and get the changes merge sequentially. I won't mind to close this PR but can you clean up #9216 and bring changes which are only necessary to support CRM-15861 and submit a separate PR?

**Comment by monishdeb** [comment]
Anyways I think I need to close this PR #11182

**Comment by litespeedmarc** [comment]
The one suggestion I can make -- I think I remember mentioning something a little while back.  Is to start with 9216, and remove `submitRenewMembershipsPriceSet`, and to not enable functionality in the .TPL.

Once you do that, you will get a LOT of PhpStorm warnings about unused methods, and also some compile errors which you can fix by removing applicable branches as they would never be applicable given that the .TPL would never allow for a price set to be specified.

In theory, this would at least remove any "left-over" clean-ups, and really help focus on the core of CRM-15861 (the reverse of this removal).  I had, before the CiviCRM Montreal sprint (which I never got to go to because I stupidly broke my shoulder blade 3 days before it) created a stash with this in it. 

I think that was one of @JoeMurray 's goals (no clean-up in 15861), so I had like a good little scout prepared that (and tested it back then).

Although I really can't afford any more time for another couple weeks, I did spent 10 minutes to restart the VM, reapply, merge conflicts, but not actually test anything.  End-result is this patch, which can be applied on 9216.

[CRM_15861__Remove_all_changes_priceset_related_.patch.zip](https://github.com/civicrm/civicrm-core/files/1432527/CRM_15861__Remove_all_changes_priceset_related_.patch.zip)

As far as authors / revisions, etc... it doesn't really matter to me if I'm included in revision history or not, so feel free to start a new (clean) PR / Branch.

I really do hope we *can* get 15861 solved.  There are a lot of people wanting this as far as I can tell.

**Pull request closed without merging**
