### PR TITLE
CRM-19221: Disabled role causes php notices

### PR DESCRIPTION
**Pull request by liedekef**
- [CRM-19221:  Disabled role causes php notices](https://issues.civicrm.org/jira/browse/CRM-19221)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins, Ok to test

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by totten** [comment]
jenkins, ok to test

**Comment by eileenmcnaughton** [comment]
Looks fine + safe to me

**Pull request merged**
