### PR TITLE
[NFC] Add test to demonstrate error passing in empty array for checkb…

### PR DESCRIPTION
**Pull request by seamuslee001**
…ox and select custom fields

Overview
----------------------------------------
This adds a unit test showing that passing empty array for a checkbox field errors on type hint issues

Before
----------------------------------------
No Test

After
----------------------------------------
Test

@eileenmcnaughton @colemanw @totten thoughts?

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Well I think the test fails :-) 

You are expecting [this line](https://github.com/civicrm/civicrm-core/pull/30743/files#diff-c4c0ce9b13571546955de8b5a9062d54caf55495425dd40c36044e3b028c43e1R157) to convert to NULL along the way?

**Comment by eileenmcnaughton** [comment]
where would it be converted into a string if it were NOT empty?

**Comment by colemanw** [comment]
Try https://github.com/civicrm/civicrm-core/pull/30728

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 looks like the test  is not stylish enough

**Pull request merged**
