### PR TITLE
dev/core#4439 Fix price set select broken price attr regression

### PR DESCRIPTION
**Pull request by larssandergreen**
Overview
----------------------------------------
Fixes regression due to #26375

Before
----------------------------------------
Price attribute for selects is broken as it is being put together per option, instead of for the whole select.

After
----------------------------------------
Price attribute for selects as before.

### CODE REVIEW

**Comment by mlutfy** [comment]
Works for me - and nice simple fix. Thank you Lars for the quick fix!

@eileenmcnaughton Should this go in the RC and/or 5.63 branch?

**Comment by mlutfy** [comment]
test error was:

>  fatal: unable to access 'https://lab.civicrm.org/extensions/angularprofiles.git/': Failed to connect to lab.civicrm.org port 443 after 131153 ms: Connection timed out

**Comment by colemanw** [comment]
@larssandergreen can you change the base to 5.63?

**Comment by larssandergreen** [comment]
@colemanw Yes, I think this is now on 5.63.

**Comment by mlutfy** [comment]
@larssandergreen I think there was a hiccup with the PR.  I think maybe you switched the branches here on github, and it pulled all the changes from master to 5.63.

To PR on an older branch, you have to `git checkout 5.63` and then `cherry-pick` your commit.

**Comment by larssandergreen** [comment]
@mlutfy OK, so in that case I would open a new PR and close this one?

**Comment by mlutfy** [comment]
@larssandergreen probably easier to open a new PR (there's probably a way, but for me this is a regular snafu).

**Comment by larssandergreen** [comment]
OK, got it now to update this PR, needed to change to 5.63 both locally and on the PR itself as the target branch.

**Comment by mlutfy** [comment]
yep looks good to me

@colemanw is anything else required to also get it in the RC/master?

**Comment by eileenmcnaughton** [comment]
@mlutfy @larssandergreen  - the right process is to do the patch against the rc in the first instance for any regression (unless it is master only). We then forward merge the rc & if appropriate back port the patch.

In this case the rc is 5.64 so that should have been the initial target branch.

However, @seamuslee001 has already opened a PR to ensure this is in the rc so all good.

**Pull request merged**
