### PR TITLE
additional changes for CRM-15889

### PR DESCRIPTION
**Pull request by jitendrapurohit**
https://issues.civicrm.org/jira/browse/CRM-15889?focusedCommentId=70743&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-70743

### CODE REVIEW

**Comment by colemanw** [comment]
This PR looks good, however checking how the api/bao create function works it looks like it neglects to pass the `$active` param to `CRM_Contact_BAO_Relationship::relatedMemberships`
See https://github.com/civicrm/civicrm-core/blob/master/CRM/Contact/BAO/Relationship.php#L63
Looking a bit closer it seems to not be taking updates into account since the condition `if (!empty($params['contact_id_a']))` does not have to be true when updating, but related memberships may still need to be altered if the `is_active` param is changed.

**Comment by colemanw** [comment]
@eileenmcnaughton can you comment on the above?

**Comment by jitendrapurohit** [comment]
Updated this PR handling the alteration of related membership if the `is_active` param is changed from the api.

Thanks.

**Comment by colemanw** [comment]
Replaced by https://github.com/civicrm/civicrm-core/pull/5277

**Pull request closed without merging**
