### PR TITLE
Afform (et al) - Fetch more complete list of permissions via APIv4

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

In a handful of configuration screens (for Afform, CiviReport, and the "Navigation Menu"), the administrator may choose from a list of permissions. With this PR, it fetches the list of permissions via APIv4 - yielding a more complete, more filterable, and more alterable list.

(This has been extracted from #19428.)

Before
----------------------------------------

The screens fetch the list via `CRM_Core_Permission::basicPermissions(...)`. The signature of this function is a little funny, and it's missing options (such as `*always allow*` and such as permissions defined in Drupal/WordPress). Here's an example:

Screen Shot 2021-02-04 at 2 17 24 PM

After
----------------------------------------

The screens fetch the list via `Civi\Api4\Permission::get()`, which is more clearly defined and which yields a more complete list.

This reveals additional options, such as `*always allow*` permission:

Screen Shot 2021-02-04 at 4 49 12 PM

For CiviReport, the UI widget switches to `select2`:

Screen Shot 2021-02-04 at 2 16 57 PM

This patch also tweaks `Permission::get()` to (a) use gentler title for `*always allow*` and (b) resolve some warnings on Drupal/Backdrop.

### CODE REVIEW

**Comment by seamuslee001** [comment]
I'll QA this one

**Comment by seamuslee001** [comment]
@totten I reviewed this and it looks right to me but I noticed that the order feels a bit odd in that whilst they are alpha ordered by the name of the permission the groups are a bit all over the place as per the screenshots attached

menu_permission

report_permissions

**Comment by totten** [comment]
@seamuslee001 Yup, you're quite right. I've changed it to sort on the printed `title` (instead of the hidden `group,name`).

**Comment by seamuslee001** [comment]
This looks good to me now merging

**Pull request merged**
