### PR TITLE
dev/core#2117 - Add compatibility aliases for 'scriptFile' and 'styleFile' resources

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

In the resource/region subsystem, each "snippet" or "resource" has a `name`. This is sometimes used downstream to modify the resources.

In 5.31.beta, the default `name` for some resources changed. This patch improves backward-compatibility by adding aliases for the old names.

See: https://lab.civicrm.org/dev/core/-/issues/2117

Before & After
----------------------------------------

The patch changes the default naming when one calls  `addScriptFile($ext, $file)` or `addStyleFile($ext, $file)`:

* __Prior versions (e.g. 5.27)__: The `name` is the URL. (Roughly -- but not exactly -- the same as `getUrl($ext, $file, TRUE)`.)
* __Current 5.31.beta__: The `name` is the combination `$ext:$file`.
* __This Patch__: The `name` is the combination `$ext:$file`, and the `aliases` are based on the URL(s).

Comments
----------------------------------------

For testing on my local, I used this snippet in a throw-away extension. Both variant A+B work with the patch.

```php
function foobar_civicrm_alterBundle($b) {
  switch ($b->name) {
    case 'coreStyles':
       // Variant A: Use URL as name
      $url = Civi::resources()->getUrl('civicrm', 'css/civicrm.css', TRUE);
      $b->update($url, ['disabled' => TRUE]);

//      // Variant B: Use "ext:file" as name
//      $b->update("civicrm:css/civicrm.css", ['disabled' => TRUE]);
  }
}
```

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
retest this please

**Comment by seamuslee001** [comment]
As discussed in the PR review queue meeting we feel this improves the situation and there may need to be further tweaks

**Comment by eileenmcnaughton** [comment]
We discussed this in PR review meeting. There are some outstanding edge cases @christianwach has raised so this might not be the last word here but we felt it was important to merge this so other rc testers don't hit the fatal error

**Comment by agileware-justin** [comment]
Cool!

**Pull request merged**
