### PR TITLE
Move function to only form that calls it

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
There was a time when we were moving stuff into AbstractEditPayment but really it is better to have private functions when we have done the work to determine that they are only used from one place - because then we know we can edit  / fix them

I did a universe search & this is a straight move to a child class

### CODE REVIEW

**Comment by larssandergreen** [comment]
Tests died.
Test this please.

**Comment by larssandergreen** [comment]
Test this please

**Comment by yashodha** [comment]
@eileenmcnaughton  looks good, merging this PR.

**Comment by eileenmcnaughton** [comment]
thanks @yashodha & @larssandergreen

**Pull request merged**
