### PR TITLE
Remove workflow_id reference

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Remove workflow_id reference

Before
----------------------------------------
Legacy field `workflow_id` referenced

After
----------------------------------------
correct field `workflow_name` referenced

Technical Details
----------------------------------------
This is a null op - we have code to ensure workflow_name is set when workflow_id is set

Comments
----------------------------------------
This reduces confusion

### CODE REVIEW

**Comment by totten** [comment]
OK, so the code generally looks sensible, and the tests pass.

I think the main bit for `r-run` (which I'll take a stab at) is to actually register a msgtpl with `workflow_name` sans `workflow_id` and observe that the "Edit Message Templates" and "New Mailing" screens show a reasonably filtered list of templates (*incl/excl the existing ones and the sample one, as expected*).

**Comment by eileenmcnaughton** [comment]
@totten if you do `civibuild create wmff` you will get that config - filter for 'failed' on the template screen

**Comment by totten** [comment]
* __Setup__: Added a pair of default+reserved templates for `workflow_name=cheese_curdling` (https://gist.github.com/totten/18b83ca437daecff4149c983b185b1a7).
* __Expectation__: Generally, on the updated files/screens, the new template(s)  should be handled like any other system-workflow-template. They should should not appear as user-templates.
* ✅ __Mailings => New A/B Test__:   The patch to `CRM/Mailing/Info.php` fixes the dropdown of "Mailing Templates" (ie *it now hides all workflow-templates from this list*).
* ⚠️ __Mailings => New Mailing__: Despite the patch to `CRM/Mailing/Info.php`, it incorrectly shows "Cheese Curdling". Maybe the operative `workflow_id` filter is actually in `ang/crmMailing/Templates.js`
* ✅ __Admin => Comm => Message Templates__: The templates are correctly categorized. The patch fixes a bug where the "Cheese Curdling" template had the wrong actions. (It was showing "Disable"/"Delete", akin to a user-template. It should show "Revert to Default" and "View Default".)
* ⚠️ __Admin => Comm => Message Templates: "Revert to Default"__: The link shows up now, but it's crashy:
    Screen Shot 2021-09-30 at 4 54 35 PM

**Comment by totten** [comment]
Added fixes for the latter two.

**Comment by eileenmcnaughton** [comment]
Merging this based on agreeing with your updates

**Pull request merged**
