### PR TITLE
[Example failing test] CRM-21320 Test for mass SMS recipients

### PR DESCRIPTION
**Pull request by JKingsnorth**
* [CRM-21320: Mass SMS can select non-preferred mobile number](https://issues.civicrm.org/jira/browse/CRM-21320)

### CODE REVIEW

**Comment by JKingsnorth** [comment]
Jenkins, retest this please

**Comment by JKingsnorth** [comment]
Jenkins, retest this please

**Comment by JKingsnorth** [comment]
Jenkins retest this please

**Comment by seamuslee001** [comment]
jenkins re test this please

**Comment by JKingsnorth** [comment]
@seamuslee001 Thanks for kicking this off again =] Fingers crossed for a fail in the right place this time ;]

**Comment by JKingsnorth** [comment]
I need to create a dummy sms provider name in the option group, and then populate all the fields on the SmsProvider create.

**Comment by mattwire** [comment]
@JKingsnorth Have you seen this PR: https://github.com/civicrm/civicrm-core/pull/10946?  I think there is significant overlap with what you are trying to do

**Comment by JKingsnorth** [comment]
@mattwire Yes, looks like some overlap. However, this focuses on the 'mass SMS' mailing tool method.

The test I've added here is primarily to catch the bug described in CRM-21320 - but I'd be happy to refactor this test based on your work over there when it's merged in.

**Pull request closed without merging**
