### PR TITLE
dev/core#2710 Cannot disable contact type/sub-type

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Steps to replicate: 

1. Click on Administer -> Customize Data and Screens -> Contact Types.
2. Disable any contact type or sub-type
3. Doesn't affect, page refreshes but the disabled contact sub-type is still active

Before
----------------------------------------
after

After
----------------------------------------
after

Comments
----------------------------------------
ping @colemanw @eileenmcnaughton @seamuslee001

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@monishdeb 2 things

1) I fixed the title to use the syntax the bot picks up - you can copy it to clipboard from within gitlab
image

2) it looks like your fix is trying to clear the cache at the point of retrieval - we should be clearing it at the point of save - presumably BAO_ContactType needs to call ``Civi::cache('contactTypes')->flush()`` when the contact type is edited

**Comment by monishdeb** [comment]
@eileenmcnaughton thanks for updating the title. For item 2, I am not sure how to trigger the `Civi::cache('contactTypes')->flush()` as trigger the disableEnableAPI call [here](https://github.com/civicrm/civicrm-core/blob/master/templates/CRM/common/enableDisableApi.tpl#L42) which trigger ContactType.setValue APIv3. Maybe extend this code to trigger the cache flush [here](https://github.com/civicrm/civicrm-core/blob/master/templates/CRM/common/enableDisableApi.tpl#L67) ?

**Comment by eileenmcnaughton** [comment]
@monishdeb yeah - maybe set it to call a 'real api' - those enableDisables bypass hooks as well I think

**Comment by eileenmcnaughton** [comment]
Hmm @colemanw maybe you can comment - do we need to override the setValue api for contact_type to behave like a 'real api' - I'm sure I tried to remove setValue & you gave it a new lease of life at some point

**Comment by monishdeb** [comment]
@eileenmcnaughton @colemanw

 The idea of getting rid of `setvalue` (as i believe its deprecated now) and use `create` action instead, actually made me to do:  
```diff
diff --git a/templates/CRM/Admin/Page/ContactType.tpl b/templates/CRM/Admin/Page/ContactType.tpl
index a8b122919f..ce86bc09ea 100644
--- a/templates/CRM/Admin/Page/ContactType.tpl
+++ b/templates/CRM/Admin/Page/ContactType.tpl
@@ -32,7 +32,7 @@
     </tr>
     </thead>
     {foreach from=$rows item=row}
-      <tr id="contact_type-{$row.id}" data-action="setvalue" class="{cycle values="odd-row,even-row"} {if !empty($row.class)}{$row.class}{/if} crm-contactType crm-entity {if NOT $row.is_active} disabled{/if}">
+      <tr id="contact_type-{$row.id}" data-action="create" class="{cycle values="odd-row,even-row"} {if !empty($row.class)}{$row.class}{/if} crm-contactType crm-entity {if NOT $row.is_active} disabled{/if}">
         <td class="crm-contactType-label crm-editable" data-field="label">{ts}{$row.label}{/ts}</td>
         <td class="crm-contactType-parent">{if $row.parent}{ts}{$row.parent_label}{/ts}{else}{ts}(built-in){/ts}{/if}</td>
         <td class="crm-contactType-description crm-editable" data-field="description" data-type="textarea">{$row.description}</td>
 ```
  This one line change fixes the current issue, not sure whats the difference in terms of cache-flush for these two actions but this one line fix in tpl works for me.

**Comment by eileenmcnaughton** [comment]
@monishdeb the one-line patch seems fine to me as long as it passes r-run

**Comment by eileenmcnaughton** [comment]
Yep - I tested & it works a treat!

**Pull request merged**
