### PR TITLE
Clicking a price option causes the payment method to change

### PR DESCRIPTION
**Pull request by m-asgari**
Overview
----------------------------------------
_A brief description of the pull request. Try to keep it non-technical._

Before
----------------------------------------
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

After
----------------------------------------
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

Technical Details
----------------------------------------
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by m-asgari** [comment]
Overview: On an event registration page, where there are multiple payment method options, clicking a price field radio button or checkbox causes the payment method to change.
How it works currently:
1. Create an event with online registration, at least one credit-card payment method, the Pay Later option, and price options that will present as checkboxes or radio buttons (price set or regular fees). 
2. Visit the public-facing event registration form and fill out the form. Click on a payment method, then click on the price field checkbox or radio button. Observe that the payment method changes automatically when you click the price field checkbox or radio buttons.
How it should work: Clicking price field options should not change the selected payment method.
Acceptance Criteria: Clicking price field options does not change the selected payment method.

**Comment by eileenmcnaughton** [comment]
Can you explain the rationale for this change - it seems to be a change to api v4 which is not used in core....

**Comment by colemanw** [comment]
Looks to me like the wrong branch was submitted for this PR.

**Comment by m-asgari** [comment]
look at the https://issues.civicrm.org/jira/browse/CRM-21696

**Pull request closed without merging**
