### PR TITLE
[NFC] Test - Improve tearDown cleanup of domain contacts

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
[NFC] Test - Improve tearDown cleanup of domain contacts

Before
----------------------------------------
``createDomainContacts`` does not ensure the domain contacts have a from_email

After
----------------------------------------
``createDomainContacts`` does ensure the domain contacts have a from_email

Technical Details
----------------------------------------

Comments
----------------------------------------
Trying to iron out test inconsistencies

### CODE REVIEW

**Comment by seamuslee001** [comment]
Test fails relate here I believe @eileenmcnaughton

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton can you rebase?

**Comment by eileenmcnaughton** [comment]
@colemanw yes I do seem to have acquired an air of mystery

**Comment by monishdeb** [comment]
@eileenmcnaughton seems like the test failures are related

**Pull request merged**
