### PR TITLE
[REF] Fix accessiblity issue on drupal menu toggle button

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Fix accessiblity issue on drupal menu toggle button

Before
----------------------------------------
Very low contrast on toggle menu: 
Screenshot 2024-07-17 at 11 29 30

After
----------------------------------------
fixed

Comments
----------------------------------------
ping @colemanw @eileenmcnaughton  @seamuslee001

### CODE REVIEW

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by eileenmcnaughton** [comment]
@monishdeb can you ping @vingle on any PRs that touch css / theming. He is pretty much our guru on this front now

**Comment by vingle** [comment]
I can see this fixes an a11y error, but I think it creates a UI issue as a result. Are you able to screengrab before and after? When I tested I got this after:

image

vs this before:

image

ie the transparent text colour is being used to hide the button name. Perhaps a better fix would be to wrap the text in `.sr-only` as you have elsewhere? ie

```
<label class="crm-menubar-toggle-btn" for="crm-menubar-state">
  <span class="crm-menu-logo"></span>
  <span class="crm-menubar-toggle-btn-icon"></span>
  <span class="sr-only">Toggle main menu</span>
</label>
  ```

**Comment by monishdeb** [comment]
Thanks @vingle for your feedback, I have updated the PR as per your suggestion and it worked for me. Can you please verify the patch?

**Comment by vingle** [comment]
Thanks @monishdeb - looks good to me. 

As the button text is still transparent does it show a WAVE/etc error still? In which case should both this and your previous PR stand? Or does the fact the text is wrapped in `sr-only` negate that?

**Comment by monishdeb** [comment]
@vingle oops I missed your comment. Yes WAVE doesn't complain about the error now and can't notice any html break for adding sr-only span. I have tested this on d9 site and looks good to me.

**Pull request merged**
