### PR TITLE
CRM-16761 - Source, templates for forms and email, Event menu updates

### PR DESCRIPTION
**Pull request by zorgalina**
11 files comprising updates to Event/ManageEvent/Registration, new files SelfSvcTransfer, Update, updates to Event confirmation and registration email and Event menu

---
- [CRM-16761: Self service view, update and cancel for CiviEvent ](https://issues.civicrm.org/jira/browse/CRM-16761)

### CODE REVIEW

**Comment by davecivicrm** [comment]
Test failures unrelated.

**Comment by davecivicrm** [comment]
@zorgalina Please see my comments about missing and mis-named files here: https://issues.civicrm.org/jira/browse/CRM-16761?focusedCommentId=79148&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-79148

**Comment by zorgalina** [comment]
Okay; I had put the message templates into the Upgrade/4.7 message
templates folder, seeing others there.  Just to confirm, I need to rename 2
and put them into civicrm-core/xml/templates/message_templates/ -RE:
CRM/Upgrade/4.7.alpha1.msg_template/ is it only for brand new templates
(not existing ones)?

On Tue, Sep 8, 2015 at 5:32 PM, Dave Greenberg <notifications@github.com>
wrote:

> @zorgalina <https://github.com/zorgalina> Please see my comments about
> missing and mis-named files here:
> https://issues.civicrm.org/jira/browse/CRM-16761?focusedCommentId=79148&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-79148
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6691#issuecomment-138739219>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by davecivicrm** [comment]
The Upgrade/..../4.7.alpha1.message_template folder should contain complete copies of the 4 message templates that you are modifying - with the 'correct' names (e.g. event_confirmation_invite_html.tpl
 is NOT the correct current name for that template - it should be participant_confirm_html.tpl). The upgrade script will use these to replace existing default content for these in the civicrm_msg_template table.

The xml/templates/msg_template folder needs to always contain the latest complete templates as well. But in this case your commit purpose is to patch the existing files with your modifications (basically adding the additional lines of logic) as you've done here: https://github.com/zorgalina/civicrm-core/commit/d7a09c87ef5a622bf159300868050270a7c41c51

However, please do NOT replace {contact.email_greeting} with Dear {contact.display_name} as you are reverting a deliberate change in the templates to use the preferred token.

**Comment by zorgalina** [comment]
alright, thanks

On Wed, Sep 9, 2015 at 12:26 PM, Dave Greenberg <notifications@github.com>
wrote:

> The Upgrade/..../4.7.alpha1.message_template folder should contain
> complete copies of the 4 message templates that you are modifying - with
> the 'correct' names (e.g. event_confirmation_invite_html.tpl
> is NOT the correct current name for that template - it should be
> participant_confirm_html.tpl). The upgrade script will use these to replace
> existing default content for these in the civicrm_msg_template table.
>
> The xml/templates/msg_template folder needs to always contain the latest
> complete templates as well. But in this case your commit purpose is to
> patch the existing files with your modifications (basically adding the
> additional lines of logic) as you've done here: zorgalina@d7a09c8
> <https://github.com/zorgalina/civicrm-core/commit/d7a09c87ef5a622bf159300868050270a7c41c51>
>
> However, please do NOT replace {contact.email_greeting} with Dear
> {contact.display_name} as you are reverting a deliberate change in the
> templates to use the preferred token.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6691#issuecomment-139021152>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
I did not intend to replace the greeting contact.email_greeting with
'Dear..'; so I assume I didn't start with the latest code

On Wed, Sep 9, 2015 at 12:27 PM, Lesley Evensen <zorgalina@gmail.com> wrote:

> alright, thanks
>
> On Wed, Sep 9, 2015 at 12:26 PM, Dave Greenberg <notifications@github.com>
> wrote:
>
>> The Upgrade/..../4.7.alpha1.message_template folder should contain
>> complete copies of the 4 message templates that you are modifying - with
>> the 'correct' names (e.g. event_confirmation_invite_html.tpl
>> is NOT the correct current name for that template - it should be
>> participant_confirm_html.tpl). The upgrade script will use these to replace
>> existing default content for these in the civicrm_msg_template table.
>>
>> The xml/templates/msg_template folder needs to always contain the latest
>> complete templates as well. But in this case your commit purpose is to
>> patch the existing files with your modifications (basically adding the
>> additional lines of logic) as you've done here: zorgalina@d7a09c8
>> <https://github.com/zorgalina/civicrm-core/commit/d7a09c87ef5a622bf159300868050270a7c41c51>
>>
>> However, please do NOT replace {contact.email_greeting} with Dear
>> {contact.display_name} as you are reverting a deliberate change in the
>> templates to use the preferred token.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/civicrm/civicrm-core/pull/6691#issuecomment-139021152>
>> .
>>
>
>
>
> --
> زورگلنه ءء لسلی
>



-- 
زورگلنه ءء لسلی

**Comment by davecivicrm** [comment]
I guess not. That was a recent change in 'master'.

**Comment by zorgalina** [comment]
I have the right versions now and will re-apply my additions and re-commit
to xml and to Upgrade/4.7.alpha.. w/correctly-named files for
participant_confirm*

On Wed, Sep 9, 2015 at 1:28 PM, Dave Greenberg <notifications@github.com>
wrote:

> I guess not. That was a recent change in 'master'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6691#issuecomment-139036757>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by jitendrapurohit** [comment]
closed in favor of https://github.com/civicrm/civicrm-core/pull/7145

**Comment by jitendrapurohit** [comment]
created new PR at https://github.com/civicrm/civicrm-core/pull/7145

**Pull request closed without merging**
