### PR TITLE
[NFC] Second pass at release notes for 5.46

### PR DESCRIPTION
**Pull request by alifrumin**
Overview
----------------------------------------
Cleans up release notes for 5.46 (better late than never).

### CODE REVIEW

**Comment by colemanw** [comment]
Is the idea to just merge this into master, or backport it to 5.46 & 5.47?

Probably it should be put up against the 5.47 branch because that will get forward-merged into master, and can also be backported if another 5.46 release is made.

**Comment by alifrumin** [comment]
Good point, I changed the base branch to 5.47 let me know if you would like me to do anything else to move this along.

**Comment by colemanw** [comment]
@alifrumin all those extra commits in this PR now are from master. It takes a little git-fu to remove them from your branch.
Sometimes it's easier to just delete & recreate it:
```
git checkout master
git branch -D rn5.46take2
git checkout 5.47
git checkout -b rn5.46take2
git cherry-pick 174645168d93ef2b55e3d8dfd9a11b805ded42b5
git push -uf alifrumin rn5.46take2
```
(might have to adjust that last line if your remote isn't called `alifrumin`

**Comment by alifrumin** [comment]
sorry! rookie mistake. Should be better now.

**Comment by totten** [comment]
+1 for `5.47` (RC) as the best base-branch here. That ensures the change applies to all future (higher-numbered) releases.

Additionally, I think this also merits a backport to `5.46` (stable). That ensures that it shows up in https://download.civicrm.org/about/5.46.0.

**Comment by totten** [comment]
Tests passed. 🙃 Merged. Backport is #22816.

Thank you @alifrumin!

**Pull request merged**
