### PR TITLE
[REF] Accessiblity fix - empty form label on new individual form

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
This patch fixes the empty form label accessibility issues on new individual form. An empty form abel erlror is triggered when a <label> tag is present in your form and associated with an input (form field), but does not contain any text and this form has such element which doesn't have label text like email, phone location types, website type etc. 

Before
-------
Screenshot 2024-07-15 at 16 38 04

After
-----
cred1

Technical Details
----------------------------------------
It adds a title attribute to those element with missing label text, that is used by select2 improvement made in this PR https://github.com/colemanw/select2/pull/5 about utilizing title attribute as a label placeholder. 

Dependent on https://github.com/colemanw/select2/pull/5 

cc @seamuslee001 @colemanw

### CODE REVIEW

**Comment by monishdeb** [comment]
Jenkins restest this please

**Comment by vingle** [comment]
test this please

**Comment by vingle** [comment]
This is still giving me errors, presumably because it's waiting on https://github.com/colemanw/select2/pull/5

**Comment by vingle** [comment]
Jenkins retest this please

**Comment by vingle** [comment]
This works for me as described, good to merge.

**Pull request merged**
