### PR TITLE
Update path in civicrm.settings.php.template for smarty3

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Update path in civicrm.settings.php.template for smarty3

Before
----------------------------------------
You had to specify the path of the autoload for smarty 3

After
----------------------------------------
As we have merged it to packages we know the path & can make it so they just have to uncomment it

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw this should be a trivial merge

**Comment by colemanw** [comment]
Ok, I assume only new installs will get this in their settings.php file and others will have to port it?

**Comment by eileenmcnaughton** [comment]
@colemanw yep

**Comment by MegaphoneJon** [comment]
@eileenmcnaughton Is this going to work on Drupal 8+?  packages are a sibling of `vendor/civicrm-core`, not a child.

**Pull request merged**
