### PR TITLE
Remove Log.php require_once statements

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
Removes now unnecessary require_once statements for Log.php files

ping @totten @eileenmcnaughton

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
ping @totten seems to have passed now we have merged the composer and the removal of the original log files

**Comment by seamuslee001** [comment]
@totten given the issue we were seeing in the test earlier i have added in the Log files to the cleanup files list so that hopefully there are no clash issues on Joomla

**Comment by eileenmcnaughton** [comment]
Agree this makes sense & we have definitely merged enough parts of this switch we are committed :-)

**Comment by colemanw** [comment]
Ok but how is the new `vendor/pear/log/Log.php` file getting included? I don't see any include statement that refers to it. Don't we need to alter these `require_once`es to point to the new `vendor/pear/log/Log.php` instead of just removing them?
@eileenmcnaughton @seamuslee001 @totten see bug report in #13835

**Comment by eileenmcnaughton** [comment]
No idea but the revert works....

**Comment by seamuslee001** [comment]
@colemanw no because composer is including the library’s folder in its psr-0 autoloader

**Comment by seamuslee001** [comment]
Also note since this was merged I have run another ext matrix and api4 tests pass

**Comment by colemanw** [comment]
@seamuslee001 is there something I need to do in my local sandbox other than `cv flush` to make the new include work? I'm still having trouble locally.

**Comment by seamuslee001** [comment]
@colemanw make sure you have run composer install based on the latest master that should hopefully take care of it

**Pull request merged**
