### PR TITLE
CRM-20179 - jstree upgrade and other js performance improvements

### PR DESCRIPTION
**Pull request by colemanw**
* [CRM-20179: Upgrade jstree](https://issues.civicrm.org/jira/browse/CRM-20179)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I've taken a look at this code and from a code point of view it appears to improve the poor methodology used to build the admin menu. The code is UI-oriented and any affects should be limited to specific screens and areas. I would note that I would see Coleman as being our resident expert on this ajax& js oriented code so I feel that as long as we can confirm via UI testing that the following things still seem OK we should merge:

1) after rebuilding the navigation menus they seem OK & that deeper menus are still built.
2) menus still translate
3) on a multidomain menus don't x-populate
4) Form for configuring tags still loads - I think this check is low importance as Coleman has been actively working on that form.
5) it appears the survey, campaign petitions in-line editing might be affected
6) also enable/ disable button.

Some thoughts about what this *might* impact outside of core
- extensions that implement crmEditable. Extended reports fits into this & I would need to check & test
- extensions that implement the enable/ disable. CiviDiscount fits in this.

I'm inclined to suggest we merge this shortly after the rc is cut to give it time before the next release, however it does tackle a significant cause of unnecessary queries.

@seamuslee001 fancy testing this is fine on a multi-domain site. It would kick in after civicrm/menu/rebuild at a guess

**Comment by colemanw** [comment]
Thanks for the review @eileenmcnaughton. FYI I benchmarked the change for loading the nav menu and it this makes it 5x faster by reducing hundreds of queries down to 1.

**Comment by seamuslee001** [comment]
I'll try and test this PR today and report back (just starting Tuesday Aus Time)

**Comment by seamuslee001** [comment]
I took a look at this, There appears to be an issue on manage price sets where the disable button does not work anymore it comes up with a. something is not a function. I ran into a separate issue on the manage tags screen which was separate to this. I have opened a PR to address this here https://github.com/civicrm/civicrm-core/pull/9913/files

**Comment by seamuslee001** [comment]
Apart from those issues i think this is pretty good

**Comment by eileenmcnaughton** [comment]
@seamuslee001  is the only outstanding issue the priceset enable/disable & the action for that is on @colemanw ?

**Comment by colemanw** [comment]
@seamuslee001 I just tried it and saw the same problem, but after a force-refresh clearing my browser cache, the problem went away.

**Comment by eileenmcnaughton** [comment]
OK - I think we could merge based on that.

**Comment by seamuslee001** [comment]
Yeh it could well have been caching / environmental issue

**Comment by colemanw** [comment]
Please try it again just to be sure. I don't want to ship something 
that's broken.

**Comment by seamuslee001** [comment]
confirmed it was an environmental problem, have re-tested and found ok

**Comment by colemanw** [comment]
Thanks for reporting back.

**Pull request merged**
