### PR TITLE
CRM-19165 Use permission sensitive function to create strip-numeric f…

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
…unction

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by colemanw** [comment]
Looks ok to me.

**Comment by eileenmcnaughton** [comment]
@colemanw  is that 'merge-on-pass' ?

**Comment by colemanw** [comment]
I'll vote for that :)

**Comment by monishdeb** [comment]
oops seems like test build ran again and failed, how's this possible :/

**Pull request merged**
