### PR TITLE
dev/search#63 Add recurring contributions to contribution reports

### PR DESCRIPTION
**Pull request by larssandergreen**
I've added Contribution Recurring as a filter, column and group by to the Contribution Summary report. After this has been reviewed, I'll add the same to other relevant reports. Thanks to @sluc23 for the dbAlias that I copied from his Report Plus extension.

### CODE REVIEW

**Comment by larssandergreen** [comment]
Not totally clear to me if I need the dbAlias in each of the three here, but testing seems to indicate yes.

**Comment by eileenmcnaughton** [comment]
Makes sense - @yashodha are you OK to review this?

**Comment by MegaphoneJon** [comment]
I'm not suggesting this isn't a worthwhile endeavor to do in core - but I want to point out that this already exists in [Extended Reports](https://civicrm.org/extensions/extended-reports), which has many improved versions of the core reports.

**Comment by larssandergreen** [comment]
@MegaphoneJon I didn't realise that this functionality exists in Extended Reports, because in order to filter for recurring or non-recurring payments you need to know that non-recurring payments have a null recurring payments field and recurring payments a non-null field. So hopefully this is a little simpler for folks like me who didn't know the database structure. But Extended Reports is great for flexibility and I think it's good to have this available in both.

**Comment by eileenmcnaughton** [comment]
I'm going to merge this - it seems fairly straight forward & obviously useful in some cases.

**Pull request merged**
