### PR TITLE
core-34 Add view-only option on permissioned relationships

### PR DESCRIPTION
**Pull request by aydun**
(This is a follow-on from https://github.com/civicrm/civicrm-core/pull/11922 but I can't reopen that one, which itself was a replacement for https://github.com/civicrm/civicrm-core/pull/11892 )

Overview
----------------------------------------
This adds a new option to permissioned relationships to provide view-only access.  Previously, a permissioned relationship always provides edit access.

Before
----------------------------------------
A permissioned relationship provides view and update access to the other contact. There is no option for view-only access.

After
----------------------------------------
The permissioned relationship can provide View and Update or View Only access.

screenshot from 2018-07-04 12-55-46

Technical Details
----------------------------------------
The is_permission_a_b and is_permission_b_a fields are changed from 0/1 boolean to 0/1/2.  As previously 0 = no access, 1 = edit (view & update). In addition 2 = view only.

For clarity, the constants `CRM_Contact_BAO_Relationship::NONE`, `CRM_Contact_BAO_Relationship::EDIT`, `CRM_Contact_BAO_Relationship::VIEW` are used.

This means all existing permissioned relationships continue to function as now and provide edit access.

Comments
----------------------------------------
Unit tests are included for normal and second-degree relationships.
Incorporates @agh1's suggestion to use icons on the relationship screen
screenshot from 2018-07-04 12-53-11

https://lab.civicrm.org/dev/core/issues/34

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@agh1  are you able to re-review this. It looks generally good, sensible & narrowly-scoped to me. I note the upgrade script line is missing but there is a case to be made for getting the rest of the review first as that is the most likely to go stale

@petednz  - you may also have an interest

**Comment by agh1** [comment]
Yes, I'd be happy to review.  Can't happen today, but early next week.  I'm excited this is happening!

**Comment by eileenmcnaughton** [comment]
@aydun test fail seems unrelated but if you squash your commits & re-push they will run again & hopefully a pretty green tick will follow

**Comment by aydun** [comment]
@eileenmcnaughton - that worked ... pretty green tick now showing!

**Comment by eileenmcnaughton** [comment]
Passing yay. In your court @agh1

**Comment by agh1** [comment]
* Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
    * __PASS__ : The goal/problem/solution have been adequately explained in the PR.
* Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
    * __PASS__: The test results are all-clear.
* Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
    * __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
* Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
    * __ISSUE__: The user documentation should be updated.
    * __COMMENTS__: This shouldn't hold up merging this PR.  There's just a passing mention of relationship permissions on the [Relationships page](https://docs.civicrm.org/user/en/latest/organising-your-data/relationships/), but this will make the screenshot out of date, and the new options should be briefly documented.
* Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
    * __PASS__: The change sufficiently improves test coverage, or the change is trivial enough that it does not require tests.
* Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
    * __PASS__: Created user "Test 1", granted "Author" role (has no special CiviCRM permissions).  Added a relationship with view+edit permission for Test 1 with another contact "Test 2" and one with view-only permission with another contact "Test 3".  Logging in as Test 1, I could use a profile in Edit mode to edit Test 2.  I could use a profile in View mode to see Test 3, but Edit mode redirected me to the site's home page.  Attempting to see any other contact in View mode displayed the error `You do not have permission to edit this contact record. Contact the site administrator if you need assistance.`
* User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
    * __PASS__: The change would be intuitive or unnoticeable for a majority of users who work with this feature.
    * __COMMENTS__: Sight-impaired users will have trouble identifying which relationships have which permissions (this is not a newly-introduced problem, but one that could be resolved relatively easily).  I'd recommend that the icons get `title` attributes saying "X can be viewed by Y" for each instance.
* Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
    * __PASS__: The change potentially affects compatibility, but the risks have been sufficiently managed.
    * __COMMENTS__: This is handled as reasonably as possible.  The value `1`, which represented the combined view and edit permission in the past, continues to mean "view and edit".  Consequently, no schema upgrade is necessary.  Only one potential issue I could imagine: someone might look for `is_permission_a_b` to be positive/truthy and act like that's sufficient for assuming the contact has edit permission when in fact the value is `2` and it's just read-only.  There's no way to accommodate that situation, and it's the smoothest potential way to upgrade I can think of.

**Comment by eileenmcnaughton** [comment]
merging based on @agh1 thorough review @aydun can you follow up on docs?

**Comment by agh1** [comment]
I just wrote a follow-up to this that adds the `title` attribute I mentioned earlier--see #12487.

**Comment by colemanw** [comment]
That eyeball is really creepy looking. Just sayin...

**Comment by colemanw** [comment]
@aydun  I'm not sure if there's anything better, at least it's not as bad as this icon that used to be in older versions of CiviCRM!  

But I do think it would be more intuitive to use 2 icons to represent 2 permissions rather than lumping them into 1. So I would do an eye for "view" and an eye plus a pencil for "view + edit"

**Comment by agh1** [comment]
@colemanw I think a pencil has usually indicated "go edit this" or "this is editable" rather than "this contact has the power to edit".  I had suggested in https://github.com/civicrm/civicrm-core/pull/11922#discussion_r178658697 [`fa-pencil-square-o`](https://fontawesome.com/v4.7.0/icon/pencil-square-o) might be distinct enough, along with some other options.

If you're creeped out by [`fa-eye`](https://fontawesome.com/v4.7.0/icon/eye), there's [`fa-binoculars`](https://fontawesome.com/v4.7.0/icon/binoculars), which may be more implictly creepy but less viscerally weird.

I got experimenting: one idea is to put them in squares and give a little color-coding:
image

The one consideration with separate icons is that you'll never have editing without viewing, and the second icon will just be taking up space.

**Comment by colemanw** [comment]
I understand that the two permissions are intertwined, nevertheless I think having 2 icons to represent 2 permissions is much more clear visually.
Andrew I really like the way you did those icons. I vote for the eye and the pencil. It looks less creepy in a green box ;)

**Comment by eileenmcnaughton** [comment]
It's a less clockwork orange look

**Comment by aydun** [comment]
Yes, I like those - eye and pencil in boxes.

**Comment by yashodha** [comment]
@aydun does this also handle permission on user dashboard? I mean which links to show or not show depending on the permission granted.

**Pull request merged**
