### PR TITLE
CRM-18586 - add delete link and fix add more button

### PR DESCRIPTION
**Pull request by jitendrapurohit**
https://issues.civicrm.org/jira/browse/CRM-18586

Previously delete link used to get built from [CRM/Contact/Form/Edit/CustomData.tpl](https://github.com/civicrm/civicrm-core/blob/master/templates/CRM/Contact/Form/Edit/CustomData.tpl#L47-L50) as each row was generated by calling the buildQuickForm() of `Contact/Form/Edit/CustomData.php`. Now, as we build this with `CRM.buildCustomData()`, we need to specify delete link for Inline display for Contacts.

### CODE REVIEW

**Comment by colemanw** [comment]
@jitendrapurohit does this PR depend on #8422?

**Comment by jitendrapurohit** [comment]
No, these links will be shown even if #8422 is not merged.

**Comment by ltaliano** [comment]
we're working on this

**Comment by ltaliano** [comment]
@jitendrapurohit  I tested this and in order to get it to work I had to apply #8418 which has been closed, as this patch depends upon 8418 can you resubmit to include the changes in 8418.

**Comment by jitendrapurohit** [comment]
You need to apply https://github.com/civicrm/civicrm-core/pull/8422 to load all the fields on Edit Page, as #8418 was closed in favor of 8422 which provided a better fix for it.

**Comment by ltaliano** [comment]
@jitendrapurohit Sorry about that. I'm new. I tested your changes and the links do appear without #8422. I also tested #8422 which works to solve the original problem (not displaying multiple fields). I was confused because #8422 and #8450 have the same PR # CRM-18586.

**Pull request merged**
