### PR TITLE
Delete all entitytags of a contact in a single api call.

### PR DESCRIPTION
**Pull request by wdecraene**
[CRM-15267](https://issues.civicrm.org/jira/browse/CRM-15267)

### CODE REVIEW

**Comment by colemanw** [comment]
jenkins, test this please

**Comment by wdecraene** [comment]
(Attempt to) fix the relevant phpunit test.

(if not ok, suggestions are welcome - no experience with phpunit)

**Comment by colemanw** [comment]
jenkins, add to whitelist

**Comment by colemanw** [comment]
jenkins, retest this please

**Pull request merged**
