### PR TITLE
dev/core#2865 - Missing message templates from 5.39/5.40

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/2865

Before
----------------------------------------
Message template updates not manually added to this function when they were updated.

After
----------------------------------------
Ideally, wouldn't need to do this. But is now done.

Technical Details
----------------------------------------
They were php8 updates. Not functional changes.

Comments
----------------------------------------
In the github view it looks like I've removed one, but I've just moved it down beside its friends.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I have a feeling we kinda didn't bother due to the non-functional nature - but that will make it easy if I have any other changes to make this release - knowing it's already in the upgrade script means I would just have to edit the template

**Comment by demeritcowboy** [comment]
Ok. And 5.43 is probably a good version to do this if any.

**Comment by demeritcowboy** [comment]
I'm noticing the other upgrade message about tokens doesn't really look like an action item, just boilerplate text. Maybe it should have a bullet?

Untitled

**Comment by eileenmcnaughton** [comment]
@demeritcowboy it's pretty long - maybe it IS time to create a page where people can see which ones are out of date.

I think the reason we didn't do this 'just for non-functional change' was so people wouldn't feel like there was an action on them - when there wasn't much to do - we might want to keep that stress for a release where we have more 'real' updates

**Comment by demeritcowboy** [comment]
Hmm, yeah maybe you're right.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy it WOULD be great to have a smarter upgrade that seemlessly did the update for default & non-customise & maybe we could have some key that tells us if it is a 'notify' update - in which case they would be actively encouraged to review the update

**Pull request closed without merging**
