### PR TITLE
CRM-18298 - implement geocoderFormat hook

### PR DESCRIPTION
**Pull request by MegaphoneJon**
- [CRM-18298: Implement hook_geocodeFormat](https://issues.civicrm.org/jira/browse/CRM-18298)

### CODE REVIEW

**Comment by PalanteJon** [comment]
Coleman reviewed this PR as #8027 - this is just an updated PR with a fixed merge conflict he requested I fix.

**Comment by colemanw** [comment]
jenkins, retest this please

**Comment by eileenmcnaughton** [comment]
Just a quick question - I always find it hard to know with these when the wikidocs get updated - but I guess just a note that this hook does need to be added to there

**Comment by PalanteJon** [comment]
Of course! The docs are already updated. Sorry; opening a second PR means the conversation gets split. 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
