### PR TITLE
CRM-20715 Add Index on is_deceased column

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @eileenmcnaughton @totten I think this is a useful improvement we already have an index on is_deleted

---

 * [CRM-20715: Add index on is_deceased column in civicrm_contact](https://issues.civicrm.org/jira/browse/CRM-20715)

### CODE REVIEW

**Comment by totten** [comment]
Adding new indices seems safe/free. Observations/questions/due-diligence:
 * In my imagination, you'd usually use `is_deceased` as an extra filter (one among many). But maybe you have a use-case? Something like "find all deceased contacts" or "find all living contacts"?
 * The patch doesn't mention the upgrader. Is that because there was a previous patch for the upgrader to reconcile all declared indices?

**Comment by seamuslee001** [comment]
@totten yes we do we have a regular cron job that works to set a custom field NULL if someone is deceased and also we have a cron job that does things to deceased contacts. Also i think it makes sense to even for filtering for large datasets to have the index. B) yes there is now the missing index reconciliation work that still needs some tinkering but 90% works fine

**Comment by eileenmcnaughton** [comment]
I guess what I wondered when I saw it was whether it should be a combined index

**Comment by seamuslee001** [comment]
@eileenmcnaughton what would you combine it with? sort_name?

**Comment by eileenmcnaughton** [comment]
I guess it depends a bit on how you use it, since you are the one finding it relevant

**Comment by seamuslee001** [comment]
I would have thought you would use it in queries like AND is_deceased = 0 or is_deceased =1 i note that the sort name one is a combo of is_deleted, sort_name, id but all the rest on the table appear to be single column indexes. To me it makes sense to have a single column index

**Comment by eileenmcnaughton** [comment]
OK - I think the answers to all questions ask make sense - merged it!

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I just hit this again because I've been going through considering removing indexes from our schema. It turns out in my testing that most queries run much better with no index on is_deleted than they do with. The same seems to be the case for a bunch of low cardinality fields.

In the event we actually don't have this index in our DB so I won't change that - but I was wondering how this came to be added (it's not hugely clear from the description :-)

Each index we have on a large table takes about 500MB of disk so we have some incentive there - but I'm more interested in removing indexes which slow down enough queries we are better without them. (This field is rarely in a query & when it IS it probably is the key filter - so that probably means it does more good than harm. is_deleted by contrast is in nearly every query & is rarely the best choice of index - despite what mysql thinks.....)

**Comment by demeritcowboy** [comment]
Cross-ref to recent ticket about removing indexes https://lab.civicrm.org/dev/core/-/issues/1634

**Pull request merged**
