### PR TITLE
CRM-20417 - translate strings

### PR DESCRIPTION
**Pull request by yashodha**
* [CRM-20417: Translate strings](https://issues.civicrm.org/jira/browse/CRM-20417)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@yashodha this seems fine, except those translates are missing so consistently it almost looks like a pattern?

**Comment by eileenmcnaughton** [comment]
or do you think it is just dreaded copy & paste?

**Comment by yashodha** [comment]
@eileenmcnaughton I think it's more of a case of 'copy and paste'. With this commit though I think I have covered them all.

**Comment by eileenmcnaughton** [comment]
Cool!

**Pull request merged**
