### PR TITLE
Bump min PHP version to 7.3.0

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
See [dev/core#3991](https://lab.civicrm.org/dev/core/-/issues/3991)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@colemanw can you update composer.json php version as well,

**Comment by seamuslee001** [comment]
Also these defines / comments will need updating 

https://github.com/civicrm/civicrm-drupal/blob/7.x-master/civicrm.module#L44 
https://github.com/civicrm/civicrm-wordpress/blob/master/civicrm.php#L7
https://github.com/civicrm/civicrm-wordpress/blob/master/civicrm.php#L68
https://github.com/civicrm/civicrm-joomla/blob/master/admin/admin.civicrm.php#L56
https://github.com/civicrm/civicrm-joomla/blob/18bc43adc16b7d57efe86640a030c653b082d693/site/civicrm.php#L26
https://github.com/civicrm/civicrm-joomla/blob/18bc43adc16b7d57efe86640a030c653b082d693/admin/configure.php#L34

**Comment by seamuslee001** [comment]
@colemanw I have done the composer.json side of things now @eileenmcnaughton @totten I think we are ok to merge this once the min profile is on php7.3

**Comment by eileenmcnaughton** [comment]
@seamuslee001 so we need to make a change to CI before we can merge this?

**Comment by seamuslee001** [comment]
@eileenmcnaughton yeh we need to do this https://github.com/civicrm/civicrm-buildkit/pull/748 first

**Comment by seamuslee001** [comment]
Now that CI has been resolved merging this

**Pull request merged**
