### PR TITLE
dev/core#5336 Remove non active groups from cloned mailing #5336

### PR DESCRIPTION
**Pull request by gngn23**
Overview
----------------------------------------
Remove deactivated groups while copying a mailing.

This seems to be the simplest solution for
https://lab.civicrm.org/dev/core/-/issues/5336

Before
----------------------------------------
- Send mailing to a group/mailinglist
- Deactivate the group
- Copy the mailing 
- The group is still included in the new mailing, it's members are counted in the preview list of recipients ...
- ... but the group is not shown in the "include groups" select (so you cannot remove it)
- The new mailing would be send to the deactivated group

After
----------------------------------------
- The deactivated group is not included in the new mailing.
- A message is shown about the removed groups

Technical Details
----------------------------------------
We fetch deactivated groups in the clone mailing and remove them.
This happens in the `CRM_Mailing_Controller_Send` constructor.

Comments
----------------------------------------
I am still new at civi and this is my first core PR - so if there is any improvement needed please note.

The actual change is quite simple (at least I think so).

But I played around a bit with group titles including HTML like "test &lt;b&gt;group&lt;/b&gt;".
This ends in the database escaped as "test &amp;lt;b&amp;gt;group&amp;lt;/b&amp;gt;".
In all the other places (like Mange Groups) this is shown as escaped HTML entitites.
But passing the title to `CRM_Core_Session::setStatus()` it would only be sanitized with `CRM_Utils_String::purifyHTML()` leaving the HTML intact and "execute" the bold tag ("test <b>group</b>").
To prepend this clean the title using `htmlentities()`. I hope this is the right way to go.

### CODE REVIEW

**Comment by monishdeb** [comment]
Congrats @gngn23 for submitting your first PR. 

After reading the steps to replicate the problem, it seems like the main issue is with the recipient preview screen that show the recipient count/list from disabled group as per this comment:

> The group is still included in the new mailing, it's members are counted in the preview list of recipients ...

 So my first thought would be that if Mailing 1 has group A and B where group B is deactivated afterward and then Mailing 2 is cloned from Mailing 1. But isn't the recipients from Group B affects both the preview recipient list and count of Mailing 1 and 2? So shouldn't we fix the preview recipient listing? And would be bonus to throw a status message like `Warning: 9 recipients from disabled group B are excluded` or so. Intention is with this fix we are ensuring that the disabled group are not copied over to the new mailing but existing mailing still got the recipients from disabled group counted
 
 Then I gone through the comments in core ticket and I think my suggestions aligns with the option 2 [here](https://lab.civicrm.org/dev/core/-/issues/5336#note_167634)

**Comment by gngn23** [comment]
@monishdeb : Thank you for the feedback.

> So my first thought would be that if Mailing 1 has group A and B where group B is deactivated afterward and then Mailing 2 is cloned from Mailing 1. But isn't the recipients from Group B affects both the preview recipient list and count of Mailing 1 and 2?

The only thing the PR does is prevent group B to be added to mailing 2 (i.e. it removes deactivated groups from the cloned mailing).
Mailing 1 remains unchanged.

> So shouldn't we fix the preview recipient listing?

I think the preview is correct and does not need changing - it counts all recipients included in the mailing.
If we change the preview (like _"including the following recipients from deactivated groups"_) we would also need to adjust the group select (see below).

Behavior _without_ the proposed change:
- deactivated group B is added to mailing 2
- but B is not visible in the group select, so
  - you do not get feedback that it is included
  - and you cannot remove group B from the new mailing 
- preview correctly counts all recipients including those from B (that is the only indicication you get that B is part of the mailing).
- In the end mailing 2 would be send to all recipients from the deactivated group B (without a chance to remove group B). 

This is changed by [option 1](https://lab.civicrm.org/dev/core/-/issues/5336#note_167634) which is implemented by this PR:
- deactivated group B is _not_ added to mailing 2
- an alert informs the user about the removal of the deactivated group
- so mailing 2 is in a clean state

In our opinion this is the cleanest (and simplest) solution because:
- It conforms with the usual behavior: you cannot add a deactivated group to a mailing.
- It keeps the former behavior (which some people might depend on): 
  - if you deactivate a group which is already included in a mailing (which is not yet sent)
  - and you send the mailing, the group's contacts will be included.
- To change this behavior would need a lot of discusion to find the "correct" and "expected" way. 
  From the discussion in [#5336](https://lab.civicrm.org/dev/core/-/issues/5336) the discussion:
  - [JonGold](https://lab.civicrm.org/dev/core/-/issues/5336#note_167678):
   "I'll defer to the folks who encounter this because it's an edge case" (although he also prefers option 2)
  - MariaV who created the ticket was also [fine with option 1](https://lab.civicrm.org/dev/core/-/issues/5336#note_167701)
- I also suppose that the group select is used in other places (in core and in extensions) so a change in it's functionality (like showing deactivated groups) would concern those other places

>  And would be bonus to throw a status message like Warning: 9 recipients from disabled group B are excluded or so.

The PR does include a warning like "_Remove [count] disabled group(s) while copying: [list-of-remoed-groups]_".
It does not give feedback about the number of removed recipients - that could be added.

**Comment by monishdeb** [comment]
@gngn23 hmm so my first impression with this comment 

> The group is still included in the new mailing, it's members are counted in the preview list of recipients ... 

was that preview list of recipients are considering the recipients from disabled group which is incorrect. But on second thought, for existing mailing, I think it doesn't matter. And I agree with you and others, moving forward the new copied mailing should get rid of the deactivated group + there's a indicator for that as status message. I am happy with patch. Just one thing, can you create a separate PR for the `contributor-key.yml` change, as this PR will get stale like it is now. OR you could rebase your PR to resolve the conflicts.

**Comment by gngn23** [comment]
@monishdeb thank you for review.
I created a separate PR for the contributor-key.yml change

**Comment by monishdeb** [comment]
I have also asked Maria to review, yesterday to ensure it doesn't miss any edge case or so.   I'll wait another day and then merge this PR.

**Pull request merged**
