### PR TITLE
AfformScanner - Allow altering search paths with internal event

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

This should make it possible to add/remove/prioritize Afform folders.

Quick demo for @eileenmcnaughton 

Example
----------------------------------------

```php
Civi::dispatcher()->addListener('&civi.afform.searchPaths', function(&$paths){
  $paths[] = [
    'weight' => 50,
    'path' => __DIR__ . '/new-ang',
    'module' => E::LONG_NAME,
  ];
});
```

Comments
----------------------------------------

I've only lightly tested. Process:

* Take an extension with some `ang/*.aff.html` files
* Move all of them to another folder (eg `new-ang`)
* Implement the event listener (as in the example)
* Run `cv ang:html:list`. Inspect the results.

Haven't done any UI-level testing.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@totten I've tested this & it works with one further tweak - which I have added to this PR - if you are OK with it then let's merge

**Comment by totten** [comment]
Nice catch @eileenmcnaughton. Agree with change. Bump up to MOP.

**Comment by eileenmcnaughton** [comment]
Hmm - there is a problem - perhaps the weights in the tests need adjusting

**Comment by eileenmcnaughton** [comment]
@totten further fix based on test - in my testing I set weight to 'work' in the extension (ie I made it lower than 0) but it seems I need to make it higher than 0 & this PR needs this update

**Comment by eileenmcnaughton** [comment]
OK - it passed & I think the tests proved the last tweak

**Comment by eileenmcnaughton** [comment]
I put a note in docs to write something about this here https://lab.civicrm.org/documentation/docs/dev/-/issues/895

**Pull request merged**
