### PR TITLE
Extract getCurrentMembership

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Extract getCurrentMembership

Before
----------------------------------------
currentMembership not reliably accessable from anywhere in class 

After
----------------------------------------
Extracted

Technical Details
----------------------------------------
Note I've moved the fixmembershipStatusBeforeRenew here - it is just compensating for the possibility of
the job not being run. On the Membership form we run it in preProcess but this feels like our first
chance in this form

Coments
----------------------------------------
The goal is to decommission the legacyProcessMembership function

### CODE REVIEW

**Comment by colemanw** [comment]
```diff
CRM_Batch_Form_EntryTest::testMembershipRenewalDates
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2021-07-16'
+'2016-04-01'
```

**Comment by eileenmcnaughton** [comment]
Interesting - tests are working then :-) I suspect the test might need fixing - will look

**Comment by eileenmcnaughton** [comment]
@colemanw this is passing now - it was a loop-leakage issue

**Comment by monishdeb** [comment]
Tested in local, r-run passed. Reviewed code looks good.

**Pull request merged**
