### PR TITLE
dev/core#1450 Try reducing the size of the temporary table so it only…

### PR DESCRIPTION
**Pull request by seamuslee001**
… contains contact_ids

Overview
----------------------------------------
Aims to reduce the size of the temporary table down by only including the contact_ids that we are finding

Before
----------------------------------------
3 columns in the temporary table

After
----------------------------------------
1 column and that only contains integers in the temporary table

ping @mattwire

### CODE REVIEW

**Comment by mattwire** [comment]
@seamuslee001 This seems sensible and a logical next step - did you test this on a live system and was it an improvement?

**Comment by MegaphoneJon** [comment]
* General standards
    * Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
        * __ISSUE__: There's no reference to ACLs.  This PR should mention that the table in question is the ACL contact cache temporary table (though I suppose by including this, it's now searchable so I guess this is a PASS now?)
    * User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
        * __PASS__
    * Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
        * __PASS__: The changes do not require documentation.
    * Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
        * __PASS__: I'm giving this a soft pass; it works well in my dev environment.  Despite decent ACL test coverage, @mattwire requested live system testing, which feels reasonable.  I'll deploy this to a production site later today.
* Developer standards
    * Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
        * __PASS__: The change preserves compatibility with existing callers/code/downstream.
    * Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
        * __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
    * Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
        * __UNREVIEWED__
        * __COMMENTS__: This seems like it deserves a test, but I see ACLs are well-tested.  If @seamuslee001 can point to a test that fails if this code were incorrect, I think we can merge without an additional test.
    * Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
        * __UNREVIEWED__

**Comment by seamuslee001** [comment]
@MegaphoneJon @mattwire we have plenty of tests in api_v3_ACLPermissionTest class and i suspect if there was something wrong here then we would know about it quickly, is this good enough to merge then?

**Comment by MegaphoneJon** [comment]
@seamuslee001 I feel comfortable, but I also don't mind running this in production for a week (it's running now) if it will allay concerns.

**Comment by jaapjansma** [comment]
Betty and I are reviewing PR's and we came across this one and we think this one can be merged.

@eileenmcnaughton or @mattwire can one of you merge this one?

**Comment by eileenmcnaughton** [comment]
Merging based on review by @MegaphoneJon & advice from @jaapjansma

**Pull request merged**
