### PR TITLE
CRM-20304 - Add option to alphabetize option values

### PR DESCRIPTION
**Pull request by yashodha**
* [CRM-20304: Add option to alphabetize option values](https://issues.civicrm.org/jira/browse/CRM-20304)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Looks like a handy feature - but by not using the api this will bypass any hooks. Are we sure there are not now, or likely to be, any hooks allowing custom options to be filtered and no chance someone would have a hook running when those are updated?

**Comment by colemanw** [comment]
IMO @eileenmcnaughton this is fine not using the api because it is a backend admin-only change. The hooks are for altering option values when displaying them, not when editing them.

**Comment by colemanw** [comment]
@yashodha I tested this and encountered an error.
Clicking the "Alphabetize Options" button worked well, as expected, but I get a fatal when doing the following:

- Open the "Edit Multiple Choice Options" in a dialog
- Click the "Alphabetize Options" button
- Without closing the dialog, try dragging the options around. An error occurs.

error

**Review by colemanw — CHANGES_REQUESTED** [review]
I tested this out and encountered an error. The code looks good.

**Comment by mepps** [comment]
@colemanw I was able to reproduce the bug you saw, but the good news is that it still saves the new order of options so the fix should just be catching why it isn't getting to success.

**Comment by mepps** [comment]
I found an additional bug, which is that if edit multiple choice options is opened in a separate screen and you press the alphabetize button, it opens the edit page again as a modal, rather than just reordering them in the page.

screenshot from 2017-09-29 14-15-46

**Comment by mepps** [comment]
See PR above where I have fixed the two bugs associated with this PR.

**Pull request closed without merging**
