### PR TITLE
CRM-16500 - Added more options to job frequency to make it more useable

### PR DESCRIPTION
**Pull request by bdombro**
---
- CRM-16500: Add more common options to scheduled job frequency
  https://issues.civicrm.org/jira/browse/CRM-16500

### CODE REVIEW

**Comment by davecivicrm** [comment]
jenkins, test this please.

**Comment by kurund** [comment]
jenkins, test this please.

**Comment by bdombro** [comment]
@davecivicrm  I'm new at this.  Is there something I did wrong?

**Comment by ginkgomzd** [comment]
@bdombro check the details link. your code didn't conform to the style standards.

**Comment by colemanw** [comment]
@bdombro you can get this PR mergeable by:

- Checkout your `more-job-frequencies` git branch locally
- Run `git pull upstream master --rebase` (assuming the civicrm remote is named "upstream")
- Fix anything flagged by the code-style checker (at a glance it looks like missing whitespace around the `==` operator)
- Do `git push --force`

**Comment by magnolia61** [comment]
Any chance this fix can qualify for inclusion in 4.6.4 It's a very nice small improvement :-)

**Comment by monishdeb** [comment]
@bdombro there is a recent changes https://github.com/civicrm/civicrm-core/commit/d0be1535d809b206890bcd4f72ebd4ba8fb1c86d made on CRM/Core/ScheduledJob.php file thats why the current PR changes is not mergeable with master. Can you please rebase your branch, resolve the merge-conflicts manually and update the PR ?

**Comment by colemanw** [comment]
This fixes the merge conflict, cleans whitespace to match our coding standards, and addresses some problems with the logic where the switch statements would fall through without a break or return at the end: https://github.com/civicrm/civicrm-core/pull/6357

**Pull request closed without merging**
