### PR TITLE
CRM-21195 - Add icon picker when editing menu item

### PR DESCRIPTION
**Pull request by colemanw**
* [CRM-21195: Adding the ability to add icons to menu items](https://issues.civicrm.org/jira/browse/CRM-21195)

### CODE REVIEW

**Comment by colemanw** [comment]
@jamienovick @omarabuhussein @seamuslee001 This enhances https://github.com/civicrm/civicrm-core/pull/11025 with the nice popup icon picker we use elsewhere.

**Comment by seamuslee001** [comment]
@colemanw @omarabuhussein @jamienovick

I just tested this out and i think there needs to be a corresponding change made in L531 of `CRM/Core/BAO/Navigation.php` because when you select the icon from the picker it only has `fa-phone` for example that gets stored and we need the `fa` class as well in the span. So L51 should get `fa ` added before `%s`

**Comment by omarabuhussein** [comment]
Thanks @colemanw , but I agree with @seamuslee001 since we need both **fa fa-iconName**  where the icon picker only add **fa-iconName** part, But I am not sure tbh about where to handle this because part of my work which is documented here https://github.com/civicrm/civicrm-user-guide/pull/216 is based on the fact you can use either the pre-shipped font awesome icons or any custom icon you want, so doing this inside CRM/Core/BAO/Navigation.php is not fitting into that purpose.

probably a better approach could be doing it in **CRM_Admin_Form_Navigation** inside **postProcess** method after  L133 : 

```php
if (!empty($params['icon'])) {
$params['icon'] = 'fa' . $params['icon'];
}
```

though this will still allows only font-awesome icons to be used when adding icons through the form, extension developers can still create another form or edit the exsiting one to add whatever custom icons they want which is not possible if that was done inside **CRM/Core/BAO/Navigation.php**.

**Comment by colemanw** [comment]
Thanks for the feedback @omarabuhussein and @seamuslee001. I've pushed up a change that adds our special `crm-i` class which is a superset of `fa` (or at least it potentially could be extended). And fixed the icon picker so it doesn't get confused by the presence of that extra class.

This allows a different icon set to be used by e.g. an extension which uses the api to push data to the menu.

I also enhanced the menu editor UI so it shows the icons in the jstree.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
I tested this latest version, i don't see the issues i previously did and i like the icon picker as well looks fine for merging to me

**Comment by colemanw** [comment]
Thanks @seamuslee001 for testing :1st_place_medal:

**Comment by omarabuhussein** [comment]
Created two PRs to update the docs and the help text ^.

**Pull request merged**
