### PR TITLE
(dev/core#223) Expose prefix and suffix in reports

### PR DESCRIPTION
**Pull request by yashodha**
Overview
----------------------------------------
Add prefix and suffix to _getContactColumns_ method.

Before
----------------------------------------
prefix_before

After
----------------------------------------
pre_after

### CODE REVIEW

**Comment by yashodha** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I'm ok sneaking this through without a test - just need to check the output

**Comment by eileenmcnaughton** [comment]
OK - I tested this & it works well.

Note that only reports that use that fn will get the additional fields (hopefully one day that will be all of them)

**Pull request merged**
