### PR TITLE
SearchKit - Allow random sorting (Fixes dev/report#75)

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Allows search displays to be sorted in random order.

https://lab.civicrm.org/dev/report/-/issues/75

image

### CODE REVIEW

**Comment by seamuslee001** [comment]
@colemanw just wondering if its possible to get a test on this maybe just testing that RAND() gets added sensibly to the query?

**Comment by colemanw** [comment]
Ok added a test @seamuslee001

**Comment by eileenmcnaughton** [comment]
@colemanw I just tested this & it seems fine. One thing - I hadn't spotted that sort box before - is it new? Or did I just miss it. I feel like it *should* be a multiselect rather than single select

This is mergeable once you have responded (one way or another) to ^^

**Comment by colemanw** [comment]
It was there already, hidden in plain sight :). And it does allow you to select multiple fields to sort by.

**Pull request merged**
