### PR TITLE
Riverlea - updates post-checkin PR

### PR DESCRIPTION
**Pull request by ufundo**
Overview
----------------------------------------
Follow up to https://github.com/civicrm/civicrm-core/pull/31478 - merge in some more updates made in the external repo

Comments
----------------------------------------
~This doesn't fix all the discrepancies yet. Still working on that but it's been complicated by some of the linting changes being applied slightly differently in the external repo.~

This should bring the core version exactly into line with the external version, if these further whitespaces changes are merged to the external repo https://lab.civicrm.org/extensions/riverlea/-/merge_requests/44/diffs

### CODE REVIEW

**Comment by vingle** [comment]
This looks good to me…

**Comment by vingle** [comment]
Just dble checking from the demo, this doesn't seem right? Maybe with this now in core I need to unpublish the version in the extensions directory? Obvs the fewer people running two copies the better… 

image

**Comment by ufundo** [comment]
> Just dble checking from the demo, this doesn't seem right? Maybe with this now in core I need to unpublish the version in the extensions directory? Obvs the fewer people running two copies the better…

Ah yes I think it would make probably make sense to unpublish now.

**Comment by mlutfy** [comment]
@vingle I re-published it, but as "work-in-progress" and updated the intro text to mention that it is now part of core. This way, we can still gather stats, but exclude it from available upgrades.

What do you think? Feel free to update the text.

**Comment by vingle** [comment]
@bgm - sounds a good idea. The text changes work, thanks (would be nice to diminish the download button a bit but obvs not viable).

Will the stats pick up presence of the extension, or enabled extensions only?

**Comment by mlutfy** [comment]
Enabled only (we also have core version stats).

**Pull request merged**
