### PR TITLE
4.7.18 rc

### PR DESCRIPTION
**Pull request by eileenmcnaughton**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 will this work?

**Comment by seamuslee001** [comment]
Nope fails still on the git scan but i suspect as its passed testing on the rc branch we can merge it in

**Comment by eileenmcnaughton** [comment]
ok - let's try that. I think it's fine....

**Comment by eileenmcnaughton** [comment]
hopefully that worked

**Pull request merged**
