### PR TITLE
[ready for core team review] CRM-20793, CRM-20799: Add filter - activity date and status on search criteria of activity listing AND make activity filter user preference an optional setting

### PR DESCRIPTION
**Pull request by monishdeb**
* [CRM-20793: Add filter - activity date and status on search criteria of activity listing  ](https://issues.civicrm.org/jira/browse/CRM-20793)

---

 * [CRM-20799: make activity filter user preference an optional setting](https://issues.civicrm.org/jira/browse/CRM-20799)

### CODE REVIEW

**Comment by monishdeb** [comment]
@lcdservices as per changes this is how it will represent the 1-row table layout: 
image
Tried with restricting the width as much as I can but any further resizing will trim placeholder and doesn't looks good. 

And as an alternative I have prepared another patch with 2-rows table layout:
image


NOTE: The display layout will get detoriated due to populating from/to date fields if we choose absolute date range as filter. Need to refactor ```templates/CRM/Core/DateRange.tpl``` to fix their position.

**Comment by monishdeb** [comment]
The patch also contains fix for CRM-20799 where add a conditional setting ```preserve_activity_tab_filter``` under 'Display Preferences' : 
image

**Comment by lcdservices** [comment]
@monishdeb the labels should consistently be above the fields. see screenshot. Also, in the help text, "contact's" is being visibly escaped. Other than that -- both the filters and setting is working great.

image

**Comment by monishdeb** [comment]
@lcdservices thanks for your feedback, fixed the label placement and that typo on help text.

**Comment by lcdservices** [comment]
looks great.

**Pull request merged**
