### PR TITLE
dev/core#116 Search builder searches on primary addresses are producing unexpected results

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Steps to replicate:

1. Contacts > Country > Primary is empty - returns many addresses, many of which have country field AND are set to primary
2. Contacts > Country > Primary is NULL - same as above

Before
----------------------------------------
test-multiple-before

After
----------------------------------------
test-multiple-after

### CODE REVIEW

**Comment by monishdeb** [comment]
ping @eileenmcnaughton @lcdservices

**Comment by mattwire** [comment]
@monishdeb Could you update the PR subject per https://docs.civicrm.org/dev/en/latest/tools/git/#pr-subject:
"dev/core#116 Search builder searches on primary addresses are producing unexpected results"

**Comment by monishdeb** [comment]
@mattwire done, thanks for pointing that out :)

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit any chance you could review this?

**Review by jitendrapurohit — APPROVED** [review]
@eileenmcnaughton @monishdeb Tested the changes. It works as expected on the search builder form. Good to merge 👍

**Comment by eileenmcnaughton** [comment]
Merging based on @jitendrapurohit review. Am happy that there is test coverage & the change is straightforward

**Comment by monishdeb** [comment]
Thanks @jitendrapurohit

**Pull request merged**
