### PR TITLE
Unit test for PR#12699

### PR DESCRIPTION
**Pull request by monishdeb**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@monishdeb yay - thanks for this - shall we merge #12669 now?

**Comment by monishdeb** [comment]
@eileenmcnaughton you're welcome. So from here we can either merge #12669 and then rebase this PR to expose the modification I have done. OR you can bring the specific change in #12669 UT. I think I am going to take the first approach, what do you say?

**Comment by eileenmcnaughton** [comment]
@monishdeb first approach sounds good to me - we just need to ask jenkins to retest once merged

**Comment by eileenmcnaughton** [comment]
@monishdeb ah - it IS stale

**Comment by monishdeb** [comment]
@eileenmcnaughton nope its not 😉

**Comment by eileenmcnaughton** [comment]
Hah

**Comment by monishdeb** [comment]
Merging as per tag

**Comment by eileenmcnaughton** [comment]
fantastic - thanks @monishdeb

**Pull request merged**
