### PR TITLE
5.5

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Contribution detail report fixes

Before
----------------------------------------
fatal errors under some circumstances

After
----------------------------------------
errors resolved

Technical Details
----------------------------------------
This is a backport of https://github.com/civicrm/civicrm-core/pull/12661 and https://github.com/civicrm/civicrm-core/pull/12660 in order to have the fixes in next release

Comments
----------------------------------------
@seamuslee001

### CODE REVIEW

**Comment by seamuslee001** [comment]
adding merge on pass as i agree with the backport

**Comment by KarinG** [comment]
Awesome

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 test failed on server related issues. I'm going to merge this as the server issues seem to be a bit ongoing & the patches have been tested against master & will be tested again when the next full run happens

**Pull request merged**
