### PR TITLE
dev/core/495 Introduce generic settings form (fully metadata driven)

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Replace event preferences form with one based on generic code - no change to user

Before
----------------------------------------
Extra code

After
----------------------------------------
Less code

Technical Details
----------------------------------------
@totten @colemanw @mattwire @pradpnayak this is really the culmination of the settings form work  - it means that by defining an xml entry like 
```
 <item>
     <path>civicrm/admin/setting/preferences/event</path>
     <title>CiviEvent Component Settings</title>
     <page_callback>CRM_Admin_Form_Generic</page_callback>
  </item>
```

And adding this key to the relevant settings

```
    'settings_pages' => ['event' => ['weight' => 20]],
```

You can have a settings form without creating a class for it at all. Also the settings on the form can be altered using the alterSettingsMetadata hook

The obvious question is why create a new key - why not use 'group' - @mattwire & I discussed this & felt
a) 'group' was pretty contaminated & poorly aligned with the settings forms
b) you might want to show a setting on multiple pages
c) you might want more nuanced data - e.g weight 

Also note that I thought I would be able to use page_arguments rather than popping an element of the url. However this turned out to be more limited & brittle than I expected & other places in core use the url appendage approach - e.g option values

Comments
----------------------------------------
Only event done here but multisite, campaign, member are all doable with minimal change

https://lab.civicrm.org/dev/core/issues/495

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@mattwire @seamuslee001 @colemanw @totten @monishdeb @jitendrapurohit @pradpnayak 

I would like to be really clear once we merge this what interaction with settings form is supported. I would like to say that extending core settings forms is NOT supported but this approach is - ie. using the Generic form + metadata.

The question is whether using the SettingTrait is supported - my original intent was that it would be but after seeing how this works I'm inclined to say not - if this doesn't work for them they can build their own form or figure out a generic way to patch core / our metadata spec to meet their needs. Thoughts?

**Review by jitendrapurohit — APPROVED** [review]
I've done a user testing on this PR and event settings works well before/after this change. Passing the `r-user` review phase from my side 👍

**Comment by colemanw** [comment]
@eileenmcnaughton this looks great!
One nitpick: what is the purpose of `templates/CRM/Admin/Form/Generic.tpl`? All it does is include another template. Why not just use that template directly?

**Comment by colemanw** [comment]
@eileenmcnaughton also, just to be really annoying, can't we make this even *more* generic and not have a `menu.xml` entry for each form? E.g. only have one entry in menu.xml for `civicrm/admin/setting/preferences` which loads the generic form, checks the path argument and says "ok we're on path `civicrm/admin/setting/preferences/foo` -- are there any settings with the "foo" key? If yes, display them. If no, give a 404. That's basically how the optionValue form works.

**Comment by eileenmcnaughton** [comment]
@colemanw hmm I tried adding this & doing a menu rebuild & it didn't work

```
+++ b/CRM/Core/xml/Menu/Admin.xml
@@ -561,9 +561,9 @@
      <page_callback>CRM_Admin_Form_Preferences_Campaign</page_callback>
   </item>
   <item>
-     <path>civicrm/admin/setting/preferences/event</path>
-     <title>CiviEvent Component Settings</title>
-     <page_callback>CRM_Admin_Form_Generic</page_callback>
+    <path>civicrm/admin/setting</path>
+    <title>CiviCRM Settings</title>
+    <page_callback>CRM_Admin_Form_Generic</page_callback>
   </item>
   <item>
      <path>civicrm/admin/setting/preferences/mailing</path>
~
~
~
```
I might need some more pointers

**Comment by eileenmcnaughton** [comment]
@colemanw I made the suggested tpl file change though.

Also re above - the xml also defines a title although I guess there could be a default

**Comment by JoeMurray** [comment]
I love the direction of this. Let me ask a very high level question. If this is merged, what kinds of settings if any will not be able to be added to the Settings page? Also, what will happen to extensions that use other (older) methods of extending the core settings forms? Our normal practice is to deprecate first, not break a bunch of things immediately.

**Comment by eileenmcnaughton** [comment]
@JoeMurray so this PR - https://github.com/civicrm/civicrm-core/pull/13048 is where we look at what extensions might be impacted - short story
- only Mosaico needs to make a change & that is only to prevent deprecation notices
- extending the settings form is not & hasn't been supported & we discourage doing so

Regarding "what kinds of settings if any will not be able to be added to the Settings page"
In theory you can add any setting. In practice there may be some remaining quirkyness on some of them that must be fixed first - e.g the Display Preferences form still has a lot of weird handling for the contact edit preferences field that I think is just about layout

**Pull request merged**
