### PR TITLE
Notice fixes for when mailing key does not exist

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
These were picked up from the civi log but would relate to the different statuses the mailing might have

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Having trouble with this one:
(a) I don't see how these warnings can come up. The whole point of this page is to display report.mailing so it can't really be missing. Even if it's just scheduled but not sent, the var is still there.
(b) You've indicated they're in civi log but typically smarty warnings about missing vars aren't in the log - only if it's a crash.
(c) I do see warnings about $group.mailing, but that's a different var not covered in this PR. Similarly I see one about campaign (since I don't happen to have campaigns where I'm looking).

**Comment by eileenmcnaughton** [comment]
@demeritcowboy - this covers the Campaign one https://github.com/civicrm/civicrm-core/pull/31654

I guess the notice I was seeing in the logs could be group.mailing not just plain mailing - there is soooo much noise from these smarty notices in the php log it's hard to know - because I seem to be be looking at  a backtrace for each one with a lot of scrolling.... I suspect what might be happening is that actually an invalid mailing_id is being hit in the url - so the php log is getting filled with noise - but nothing usable is rendered

**Comment by colemanw** [comment]
@eileenmcnaughton this has a merge-conflict

**Comment by demeritcowboy** [comment]
I don't think this should be merged. It's the wrong "mailing" var in my opinion.

**Comment by colemanw** [comment]
Ok let's close it for now.

**Pull request closed without merging**
