### PR TITLE
CRM-21499: Add filter for tagset page

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
This is a followup PR of #11352 to add filter for TagSet forms too. 

After
----------------------------------------
test-multiple-before

---

 * [CRM-21499: Add filter to manage tags page](https://issues.civicrm.org/jira/browse/CRM-21499)

### CODE REVIEW

**Comment by monishdeb** [comment]
ping @lcdservices @colemanw

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by colemanw** [comment]
I pushed a few fixes to add a clear button to the search boxes, and to ensure the search is cleared when refreshing the display.

**Comment by monishdeb** [comment]
Thanks @colemanw :) this looks great
test-multiple-before

**Pull request merged**
