### PR TITLE
[REF][Export] Minor cleanup on household merge properties

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Minor code cleanup (from #14782)

Before
----------------------------------------
The 'work' of determining household return properties is in 2 places

After
----------------------------------------
Consolidated

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
@eileenmcnaughton test failures appear to be related.

**Comment by eileenmcnaughton** [comment]
@colemanw passing now

**Comment by eileenmcnaughton** [comment]
thanks @colemanw - once https://github.com/civicrm/civicrm-core/pull/14790 is merged I'll pull out the one that handles the new $fields format

**Pull request merged**
