### PR TITLE
CRM-19931 - Payment block is not hidden if fee level with amount zero…

### PR DESCRIPTION
**Pull request by yashodha**
… is chosen

### CODE REVIEW

**Comment by yashodha** [comment]
test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by yashodha** [comment]
jenkins test this again

**Comment by yashodha** [comment]
test this please

**Comment by yashodha** [comment]
test this please

**Comment by jackrabbithanna** [comment]
Candidate for merging, needs to be merged with https://github.com/civicrm/civicrm-core/pull/9814

**Comment by jackrabbithanna** [comment]
Merging #9734

**Pull request merged**
