### PR TITLE
Renders customfields under campaign search in Campaign dashboard

### PR DESCRIPTION
**Pull request by VangelisP**
Overview
----------------------------------------
Customfields that are being attached to a campaign entity do not render on the search page of campaign dashboard, therefore, a user cannot use them to search for campaigns using those customfields.

Related issue: https://lab.civicrm.org/dev/core/issues/1354

Before
----------------------------------------
Customfields do not render on the search form of Campaign dashboard

After
----------------------------------------
Customfields render on the search form of Campaign dashboard and user can search with these.

Technical Details
----------------------------------------
During buildform of campaign dashboard, a new call is being made to a function that takes care of rendering customfields on the form itself by analysing the `html_type` & `datatype`.

Additionally, during the actual search, if field is a customfield, we `LEFT JOIN` the related table(s)

Comments
----------------------------------------
All comments are welcome!

### CODE REVIEW

**Comment by jaapjansma** [comment]
@VangelisP Is this still work in progress or is this PR finished and ready for review?

**Comment by VangelisP** [comment]
Hi @jaapjansma , it's basically waiting for someone to review and if it's actually worth adding it to core.
Comments are highly appreciated for constructive criticism :D

**Comment by jaapjansma** [comment]
@VangelisP thanks for your quick response. Could remove the [wip] from the title as well? We will review this PR right now.

**Comment by jaapjansma** [comment]
* General standards
    * Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
        * __PASS__ : The goal/problem/solution have been adequately explained in the PR and the issue.
    * User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
        * __PASS__: The change would be intuitive or unnoticeable for a majority of users who work with this feature.
        * __ISSUE__:  On many search screen in CiviCRM the custom field is displayed in a frame with a blue bar with the custom group title. In the search campaign screen it shows the field but not grouped per custom group. We would advice to fix this before this PR could be merged. 
    * Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
        * __PASS__: The changes do not require documentation.
    * Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
        * __FAIL__:  We have tested this PR and it does not work with a custom date field. The dashboard is broken when a searchable custom date field is added to the campaign. In the log the following error is shown: `Element 'select date' does not exist in HTML_QuickForm::_loadElement()`
* Developer standards
    * Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
        * __PASS__: The change preserves compatibility with existing callers/code/downstream.
    * Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
        * __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
        * __COMMENTS__: There are some todo's mentioned in the code, such as searching on date ranges etc.. 
    * Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
        * __PASS__: The change sufficiently improves test coverage, or the change is trivial enough that it does not require tests. However it would even be more wonderful if this PR has a test.
    * Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
        * __PASS__: The test results are all-clear.

Our main comment is that this PR is not ready to be merged because when a searchable date is field is added to the campaign the dashboard is completely broken.  @VangelisP are you able to fix the error with the date field?

**Comment by VangelisP** [comment]
I can definitely rework this PR so that it can be compliant with the latest CiviCRM and also close the issues with the dates (and some visuals)

**Comment by jaapjansma** [comment]
We will close this PR as no work has been done and we have checked with @VangelisP and probably no work would happen anyway.

**Pull request closed without merging**
