### PR TITLE
chore: Included githubactions in the dependabot config

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.

Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot

GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins ok to test

**Comment by demeritcowboy** [comment]
Two thoughts:
* As noted before I think Actions should just be turned off in this main repo, since the existing action is meant to be run in a fork.
* Dependabot already does its thing in this repo and I'm not clear on how this would or wouldn't override. For example does this _add_ github-actions into the default config, or does it completely override the default config so that it _only_ does github-actions.

**Comment by naveensrinivasan** [comment]
Ok. I will close the PR. Thanks

**Comment by demeritcowboy** [comment]
Appreciate the PR though! We should probably look closer at how to configure dependabot to see if we're missing out on something.

**Pull request closed without merging**
