### PR TITLE
dev/core#2660 - Remove old menu entry for "New Tag"

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/2660

Before
----------------------------------------
1. Contact -> New Tag.
1. It goes to the same place as Manage Tags.

After
----------------------------------------
No practical change.

Technical Details
----------------------------------------
This seems to be left over from when the tags screen was redone. There is a real "new tag" url, but it's a different url and on the manage tags screen you have more options like parents or tagsets, so since people are already going to that screen in practice they aren't losing anything.

Comments
----------------------------------------
Only for new installs.

### CODE REVIEW

**Comment by colemanw** [comment]
Looks good @demeritcowboy
On an administrative note, you can have this PR automatically close the issue by putting "`Fixes dev/core#2660`" in the commit message (not the PR, has to be the actual commit msg)

**Comment by demeritcowboy** [comment]
Ok thanks noted - although I'd still want to go put in the milestone. It's probably not simple to have it do that automatically.

**Comment by demeritcowboy** [comment]
Interesting - there's only one record in the civicrm_contact table. Hmm.

**Comment by demeritcowboy** [comment]
I see what it is. The regen script needs updating, for fantastic reasons which the margins here are too small to contain.

**Comment by colemanw** [comment]
Goodbye old new tag

**Pull request merged**
