### PR TITLE
define format at one place

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
Move pdf format array at one place so that it can be altered using hooks

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@pradpnayak while that is a bit less repetitive it's hard to imagine that it would be very robust to alter it in a hook.

I followed the code through & seems that if `pdfFormat` is something other than an array an option value will be loaded

```
    // Get PDF Page Format
    $format = CRM_Core_BAO_PdfFormat::getDefaultValues();
    if (is_array($pdfFormat)) {
      // PDF Page Format parameters passed in
      $format = array_merge($format, $pdfFormat);
    }
    elseif (!empty($pdfFormat)) {
      // PDF Page Format ID passed in
      $format = CRM_Core_BAO_PdfFormat::getById($pdfFormat);
    }
```

It does still seem to wind up with a limited list of values
https://github.com/civicrm/civicrm-core/blob/59e21298a6ebafa712c6403186cbbcb0ecc6b7aa/CRM/Core/BAO/PdfFormat.php#L46-L95 - so doesn't quite get us to override so I'm still following the code -

But, what will you eventually try to set it to?

**Comment by eileenmcnaughton** [comment]
OK - looking - we don't ship with any option values in the pdf formats option group - which is configured at this url

civicrm/admin/pdfFormats?reset=1

But we could? We could move that invoice pdf format metadata to a row in that option group & then you could alter that per site?

I admit option groups are not always universally loved but since the data structure seems to already exist....

**Comment by eileenmcnaughton** [comment]
@pradpnayak looks like jenkins wants a change
image

**Comment by pradpnayak** [comment]
Fixed the indentation,

This PR also depends on https://github.com/civicrm/civicrm-core/pull/24090/files

**Comment by pradpnayak** [comment]
retest

**Comment by pradpnayak** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
I tested this out & it works OK.
However, I'm less convinced the other should be an option group - I am leaning to just adding `px` to the hard-coded list for now & sharing the list - I did post in chat to see if someone thinks otherwise. I'm going to merge this since I think we can just add `px` to the existing functions if it comes to it & this other-wise is good

**Pull request merged**
