### PR TITLE
Membership form submit status message refactor

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Minor refactor of code around setting submit status message, adds a test

Before
----------------------------------------
Code less logically grouped

After
----------------------------------------
Code more logically grouped.

Technical Details
----------------------------------------
This is a small refactor aimed at bringing code that is logically related together. There is a loop that iterates through    
```
   foreach ($this->_memTypeSelected as $memType) {
```
and creates memberships. It is an obvious candidate for extraction but it also turns out that loop builds up the $createdMemberships array for the sole purpose of setting the message for the form user. It seems fairly clear to me that every time we see 

```
        $createdMemberships[$memType] = $membership;
```

What we should really see is some variant of 
```
$this->addStatusMessage(
```

Comments
----------------------------------------
Reviewable subset in #12694

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton i tested this PR but what i found was that when performing a backend renewal as the logged in user i was not seeing any status messages appear. This was just by clicking on the renew not renew credit card entering in an amount and saving. The membership would be properly renewed but no status message would appear

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I don't think this touches the Renewal form. I just tested on master (without this patch) & got no message on the renewal form

**Comment by mattwire** [comment]
Does this need a rebase now that #12694 is merged?

**Comment by eileenmcnaughton** [comment]
I'm pretty sure I already rebased it - not sure why the tests failed but I think it was an infrastructure issue

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by mattwire** [comment]
Ok, happy for this to be merged now.

**Comment by mattwire** [comment]
@seamuslee001 Ok, happy for this to be merged now.

**Pull request merged**
