### PR TITLE
[NFC] test fix for leap year

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
test fails on Feb 26 in leap years.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I believe in fact the tests fail on Feb 27 on leap years....

image

**Comment by demeritcowboy** [comment]
Oh yes, probably every day between feb 26 and feb 28. Ok let me get my time machine and rejig.

**Comment by demeritcowboy** [comment]
The feb 29 I couldn't do in my head. But it can be confirmed by seeing that:

`php -r "echo date('Y-m-d', strtotime('2024-02-29 - 2 year + 3 day'));"` gives `2022-03-04`

and

```
SELECT DATEDIFF(
        IF(
            DATE(CONCAT(YEAR('2024-02-29'), '-', MONTH('2022-03-04'), '-', DAY('2022-03-04'))) < '2024-02-29',
            CONCAT(YEAR('2024-02-29') + 1, '-', MONTH('2022-03-04'), '-', DAY('2022-03-04')),
            CONCAT(YEAR('2024-02-29'), '-', MONTH('2022-03-04'), '-', DAY('2022-03-04'))
        ),
        '2024-02-29'
    );
```
returns 4

**Comment by demeritcowboy** [comment]
Ah I should put this against 5.71, otherwise tests on backports will fail for a few days.

**Comment by eileenmcnaughton** [comment]
Happy 29th of Feb

**Comment by demeritcowboy** [comment]
I still can't get over how you're living in the future.

I think I'm going to propose to the [insert whatever org controls time] that individual regions be allowed to regulate if they want leap years, since our time systems are too simple with just timezones and DST.

**Comment by eileenmcnaughton** [comment]
shame it doesn't allow me to tell you who will win lotto

**Pull request merged**
