### PR TITLE
(NFC) Minor string error : for for > for

### PR DESCRIPTION
**Pull request by UshaMakoa**
/spend 15m

### CODE REVIEW

**Comment by mattwire** [comment]
@UshaMakoa Thankyou. Because this is an autogenerated file you have to make the change here: https://github.com/civicrm/civicrm-core/blob/master/xml/schema/Core/PrintLabel.xml#L25 and then re-generate the file. You have to run the gencode script to do this - see https://docs.civicrm.org/dev/en/latest/framework/database/schema-definition/  @MikeyMJCO Do we have any better documentation explaining how to regenerate entities?

**Comment by colemanw** [comment]
I've updated it.

**Comment by MikeyMJCO** [comment]
@mattwire I'm not aware of any better documentation for it.

**Comment by mlutfy** [comment]
Merging as per merge-on-pass tag, and quick code review.

**Pull request merged**
