### PR TITLE
CRM-20804 (IIDA-150) fixed code to assign proportional line item for …

### PR DESCRIPTION
**Pull request by pradpnayak**
…not paid yet

----------------------------------------
* CRM-20804: Financial items are not assigned proportionally for partially paid contribution
  https://issues.civicrm.org/jira/browse/CRM-20804

### CODE REVIEW

**Comment by monishdeb** [comment]
@pradpnayak can you fix the related test build failures

**Review by monishdeb — CHANGES_REQUESTED** [review]
@pradpnayak can you fix the related test build failures

**Comment by eileenmcnaughton** [comment]
This PR does not have enough information to be reviewed. Steps to replicate & unit test are the obvious gaps. Is it still valid / separate from other PRs being reviewed

**Comment by pradpnayak** [comment]
@eileenmcnaughton  i will add unit test and update the issue soon.

**Comment by eileenmcnaughton** [comment]
Thanks @pradpnayak - if soon is not in the next week it's probably better to close this & re-open when you have had a chance to fix

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by eileenmcnaughton** [comment]
I'm going to close this out & let you re-open it when it's ready for review per comments on 5 Sep

**Pull request closed without merging**
