### PR TITLE
CRM-18490: API does not return Address ID via API

### PR DESCRIPTION
**Pull request by monishdeb**
- [CRM-18490: API does not return Address ID via API](https://issues.civicrm.org/jira/browse/CRM-18490)

### CODE REVIEW

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by eileenmcnaughton** [comment]
The test fail on this was a real regression & I'm fairly sure this was the commit that caused it

**Comment by monishdeb** [comment]
Yup I agree but we tested for CRM_Contribute_Form_ContributionTest::testSubmitCreditCardWithBillingAddress failure and it was running clean on our local, also checked in the testsite with ssh credential.  Even tested getsingle api on Address entity with address id everything works fine but due to some reason it is failing only on Jenkin. I will do further investigation and will submit PR later.

**Comment by eileenmcnaughton** [comment]
maybe it's a leakage issue - with the PR tests they should run clean except the few pre-existing intermittant ones

**Comment by monishdeb** [comment]
Should I comment out the apiSingle code or use Address.get api instead for now ?

**Pull request merged**
