### PR TITLE
CRM-21061 - Fix rare report error when the report name is longer than 64 Char

### PR DESCRIPTION
**Pull request by ghost**
Overview
----------------------------------------
Change civicrm_report_instance, report_id from 64 characters to 512 characters to match civicrm_option_value, value to avoid errors caused by truncating CiviCRM report name which are greater than 64 chars.

See https://issues.civicrm.org/jira/browse/CRM-21061

Before
----------------------------------------
64 character limit causes report_id to be truncated for long report names and incorrect value stored.

After
----------------------------------------
Increase to 512 character limit which should reduce the likelihood report name is truncated.

Technical Details
----------------------------------------
Change report_id to 512 varchar

Comments
----------------------------------------
See https://issues.civicrm.org/jira/browse/CRM-21061

### CODE REVIEW

**Comment by agileware** [comment]
hey @jackrabbithanna are you able to review this for 4.6?

**Comment by jackrabbithanna** [comment]
I will, we're planning on going through the PR queue for 4.6 soon and do a bunch of testing and bugfix / minor update merges.

**Comment by jackrabbithanna** [comment]
I think this can make it into the next release

**Comment by jackrabbithanna** [comment]
Merging #10859

**Pull request merged**
