### PR TITLE
dev/core#1067 Clean Money before creating Campaign record and add test

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This ensures that if a value like $5,000 is entered that 5000 is stored in the database correctly

Before
----------------------------------------
Non Numeric number causes 0 to be stored

After
----------------------------------------
Goal Revenue is properly stored

ping @jusfreeman @eileenmcnaughton @pfigel 

https://lab.civicrm.org/dev/core/issues/1067

### CODE REVIEW

**Comment by jusfreeman** [comment]
Thanks @seamuslee001 

Would you mind adding a link to https://lab.civicrm.org/dev/core/issues/1067 in the PR description too?

**Comment by jusfreeman** [comment]
I like the test too :)

#hastest

**Comment by eileenmcnaughton** [comment]
@jusfreeman done - it's annoying that we don't have a gitbot doing that :-(

**Comment by eileenmcnaughton** [comment]
@jusfreeman if you have an interest in reviewing this it falls in the category of 'I would merge this if a trusted reviewer did a review using the review template & recommended it be merged' - ie there are no  blockers from my point of view other than someone taking the time to review it (as opposed to some PRs where even a review isn't enough to merge them because there is some underlying concern about the technical approach or things it might impact)

@MegaphoneJon do we want a tag for PRs in this camp - ie. no specific merger concerns about a PR so a reviewer has a lot of 'power' to progress it

**Comment by jusfreeman** [comment]
@seamuslee001 happy to review - as mentioned by @eileenmcnaughton eileen it does look like there are other fixes in this PR but there's no explanation?

**Comment by seamuslee001** [comment]
@jusfreeman the only "fix" in this PR is the one for the ticket. The rest is just re-arranging the code so i can generate a unit test

**Comment by jusfreeman** [comment]
@seamuslee001 cool man will test and report back!

**Comment by jusfreeman** [comment]
@seamuslee001 tested and working as expected thanks!

Any chance you can also add these UX improvements to the page:
* Provide Revenue Goal field help, like: "Use this field to enter the number representing the Revenue Goal"
* Display the defined CiviCRM currency as a prefix for the field, eg. $AUD which is a visual indication for what to be entered here.

As I mentioned on https://lab.civicrm.org/dev/core/issues/1067

**Comment by eileenmcnaughton** [comment]
I'm going to merge based on the 'tested and working' part not the scope creep part....
@seamuslee001 if you do add help text it should be via the Entity Form method & .metadata

**Comment by MegaphoneJon** [comment]
> @MegaphoneJon do we want a tag for PRs in this camp - ie. no specific merger concerns about a PR so a reviewer has a lot of 'power' to progress it

We can take this discussion to Mattermost.  If that makes sense as a label to you, then sure!  However, someone with "triager" permission isn't able to make that call.  So it's really up to the "mergers" and not triagers whether it's helpful.

**Comment by eileenmcnaughton** [comment]
Looks like this caused a regression

https://lab.civicrm.org/dev/core/issues/1233

**Pull request merged**
