### PR TITLE
CRM-19102 backported changes to 4.6

### PR DESCRIPTION
**Pull request by sunilpawar**
- [CRM-19102: Refactor the Paypal IPN code to replay transactions](https://issues.civicrm.org/jira/browse/CRM-19102)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
If you are going to backport this please also backport the unit test

**Comment by eileenmcnaughton** [comment]
NB test fails are unrelated

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
I don't have any appetite for backporting more payment processor changes to 4.6. I'm trying to tail it off - but if you want to take responsibility for it & have tested it adequately I will merge it. 

We have had to fix a few regressions in 4.7 resulting in paypal std changes and I think we are finally just about stable on that front

**Comment by eileenmcnaughton** [comment]
@sunilpawar @nganivet can we close this - it's over a year old & I don't think there is or is likely to be any resource committed to reviewing it for 4.6

**Comment by nganivet** [comment]
Yep, let's close it then. The commit is in our repo if anybody wants to get to it later.

**Pull request closed without merging**
