### PR TITLE
CRM-21071 - Fix event location saving

### PR DESCRIPTION
**Pull request by colemanw**
Overview
-----

In the Location tab (when configuring an event), saving more than one email address will give unexpected results, sometimes overwriting, sometimes duplicating the existing email address.

The fix touches code which is also used for profiles, so we need to ensure we haven't broken anything while testing. Someone needs to test out creating a profile and using it to save an email address.

* [CRM-21071: Event Location Tab: Second Email and Phone fields broken](https://issues.civicrm.org/jira/browse/CRM-21071)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@colemanw I tested this & it's good but I think #11568 is better for the second commit

**Pull request closed without merging**
