### PR TITLE
dev/core#1864 Revert changes to ACL test and ACL API class and update…

### PR DESCRIPTION
**Pull request by seamuslee001**
@eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 isn't that the same as the one I merged https://github.com/civicrm/civicrm-core/pull/17796

**Comment by seamuslee001** [comment]
@eileenmcnaughton nope that one had the changes in the API Class and also commented out the ACL unit tests which my 5.28 one didn't

**Comment by eileenmcnaughton** [comment]
@seamuslee001 so this reverts the one I merged & re-fixes ? https://github.com/civicrm/civicrm-core/pull/17796 - I'm getting confused

**Comment by eileenmcnaughton** [comment]
OK - you are on it - I am not

**Comment by seamuslee001** [comment]
it reverts what isn't merged into 5.28 and applies what needs to to fix the problem

**Comment by eileenmcnaughton** [comment]
That old chestnut

**Comment by seamuslee001** [comment]
Test fail expected and unrelated

**Pull request merged**
