### PR TITLE
dev/core#2652 - Civi\Report - Add is null / is not null to OP_MULTISE…

### PR DESCRIPTION
**Pull request by nirodaonline**
…LECT_SEPARATOR

Overview
----------------------------------------
Add options "is null" / "is not null" to CiviReport filter type CRM_Report_Form::OP_MULTISELECT_SEPARATOR.

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins ok to test

**Comment by demeritcowboy** [comment]
Thanks for the PR

* General standards
    * [`r-explain`] __PASS__
      * Just it might not be clear to everyone what OP_MULTISELECT_SEPARATOR is. Checkboxes for example.
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __PASS__
      * Choice not present before. Is present and works after.
* Developer standards
    * [`r-tech`] __PASS__
    * [`r-code`] __PASS__
    * [`r-maint`] __?__
    * [`r-test`] __PASS__

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon this looks like it has been reviewed & is just looking for a bit of endorsement - any thoughts?

**Comment by seamuslee001** [comment]
I'm a +1 on this but will let Jon weigh in

**Comment by MegaphoneJon** [comment]
Are you asking me for a UX review?  This is definitely a useful feature.  I could bikeshed the inconsistent wording between this/Search Kit/Search Builder - but this language is consistent within CiviReport, so I don't see any reason to block a merge.

**Pull request merged**
