### PR TITLE
CRM-18959

### PR DESCRIPTION
**Pull request by nishant-bhorodia**
Created a function `getCustomFields` to fetch all custom fields related to Contact Types and their subtypes

---
- [CRM-18959: Import fails when custom multi-value date field is imported](https://issues.civicrm.org/jira/browse/CRM-18959)

### CODE REVIEW

**Comment by darrick** [comment]
You copied code to a new function but ended up dropping references to issue CRM-18708 in the comments.

I'm guessing [CRM-18708](https://issues.civicrm.org/jira/browse/CRM-18708) fixed the issue with importing multi-value fields but now things are failing if the imported field requires formatting.  Is this the case?  Just want to be clear about it before I test.

Thanks

**Comment by darrick** [comment]
Commented to soon.  Just saw [PR-8556](https://github.com/civicrm/civicrm-core/pull/8566) which explains the issue a bit better.

**Comment by nishant-bhorodia** [comment]
Hello @darrick

Sorry for late response, I was out for weekend.
Thank you for testing this. Please let me know if you need any help or clarification.

Many Thanks :)

**Comment by eileenmcnaughton** [comment]
Please check #8662  - proposed replacement PR

**Pull request closed without merging**
