### PR TITLE
Unit test for CRM-15815.

### PR DESCRIPTION
**Pull request by johanv**
## A unit test for CRM-15815.
- CRM-15815: Two chained create calls, with the first one creating an array
  https://issues.civicrm.org/jira/browse/CRM-15815

### CODE REVIEW

**Comment by totten** [comment]
ok to test

**Comment by colemanw** [comment]
retest this please

**Comment by johanv** [comment]
I am not sure what you mean with 'retest this'. This patch contains a failing unit test, to illustrate the bug. So it was expected that it would generate more errors in the test suite.

**Comment by colemanw** [comment]
@johanv that directive was for the CI system, not for you ;)

**Comment by johanv** [comment]
Ok, thank you for pointing this out :-)

**Comment by totten** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
Replaced by https://github.com/civicrm/civicrm-core/pull/6417

**Pull request closed without merging**
