### PR TITLE
Standardise some more event template tokens

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Standardise some more event template tokens

Before
----------------------------------------
This is mostly where we have an established pattern and / or a disrepancy between the templates

After
----------------------------------------

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by larssandergreen** [comment]
@eileenmcnaughton I can't the allow_selfcancelxfer to work - but maybe a caching issue? Is it working on your end?

**Comment by larssandergreen** [comment]
@eileenmcnaughton Also, what steps are there between us and being able to switch to generating text messages from the HTML? Sure would be nice.

**Comment by eileenmcnaughton** [comment]
hmm good question @larssandergreen - I think it's easy to say 'if there is no text template then use the html' in our existing code. The hard part is how do we deal with sites that already have text versions? Do we delete them? Do we leave them but not add to new sites? & If the latter then do we need to still figure out how they should be re-written?

**Comment by larssandergreen** [comment]
@eileenmcnaughton I think if we give it a little test run and it works well, we can remove the text versions for new sites and for any site that has the default text template. For sites with a customized text template, I guess we alert them on upgrade — but then we'd need to provide some kind of mechanism for them to remove the text versions themselves (or at least provide instructions as to how they can do that via API Explorer). I think almost everyone with a customized template would be happy to no longer have to deal with a text version.
I think we can just say that the text versions are no longer receiving updates.

**Comment by eileenmcnaughton** [comment]
@larssandergreen ok - makes sense - I've been thinking about moving the tpl files to being loaded via Managed too.

**Comment by eileenmcnaughton** [comment]
@larssandergreen I did some more testing on it & also swapped out the other token in that piece & a couple more


image

**Comment by eileenmcnaughton** [comment]
@larssandergreen in the context of this PR I think changing the text version still makes sense - but I don't think it needs testing for these ones

**Comment by eileenmcnaughton** [comment]
@larssandergreen we have discussed & agreed that in 5.67 the event offline receipt will not ship with a text version (as a first step towards removing them all).

I have removed the update to that template from this

**Pull request merged**
