### PR TITLE
Add unique names and unique title for recurrings.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Adds key unique_title to the entity definition schema

Before
----------------------------------------
Only possible to determine one 'title' field

After
----------------------------------------
'title' & 'unique_title' can both be defined - the latter is for situations where multiple entities may be involved (e.g advanced search) and disambiguation is needed

Technical Details
----------------------------------------
Per discussion https://github.com/civicrm/civicrm-core/pull/14737/files#r300889057
we hace a need sometimes to display context dependent titles & context independent titles.

This adds unique_title for the purpose

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton what's the reason for also adding unique names here?

As you know I'm not a big fan of unique names, preferring nested arrays/objects where the entity name is explicit and the fields specific to that entity are contained within. That's how afform works.

**Comment by eileenmcnaughton** [comment]
@colemanw for advanced search... pretty much the reason for all the unique names - part of the linked pr

**Comment by seamuslee001** [comment]
This looks fine to me and is how we are moving with field conversions for datepicker. Merging

**Comment by mattwire** [comment]
This has the potential to add a LOT of additional strings just so we can have the entity name in the title - surely there's a better way than this? @bgm any thoughts on the translation side?

**Comment by eileenmcnaughton** [comment]
@mattwire they will only get added as needed & pretty much the only strings that get added are being moved not genuinely added - half a dozen ATM

**Pull request merged**
