### PR TITLE
Set ContactType.name as required in the schema.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
I came across this weird WHERE clause & I'm pretty sure it's compensating for a mistake in the schema

I also set what I think are sensible defaults on is_reserved & is_active

Before
----------------------------------------
in civicrm_contact_type
 - name = not required
 - is_active = no default
 - is_reserved = no default

After
----------------------------------------
name is required
is_active defaults to 1
is_reserved defaults to 0

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by totten** [comment]
Sounds pretty sensible. :+1:

Won't this require updates to `CRM/Upgrade` and `civicrm_generated.mysql` (ie `bin/regen.sh`)  to (a) backfill any blanks and (b) reflect the schema change?

**Comment by eileenmcnaughton** [comment]
@totten done

**Comment by seamuslee001** [comment]
Merging as unit tests pass and also the concern has been resolved

**Comment by aydun** [comment]
@seamuslee001 I may be missing something obvious ... but it doesn't look like Tim's first point about backfilling blanks has been implemented.

**Pull request merged**
