### PR TITLE
APIv4 - merge ActionUtil with Request::create

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Consolidates some APIv4 code with v3.

Before
----------------------------------------
The `Request::create` function was broken for v4, and `ActionUtil` had been serving the same purpose but in a non-broken way.

After
----------------------------------------
Deleted `ActionUtil` and fixed `Request::create` to work correctly with v4.

### CODE REVIEW

**Comment by colemanw** [comment]
Retest this please

**Comment by seamuslee001** [comment]
@colemanw the test rig is getting tied up on the test suite. 

```
CRM_Utils_API_MatchOptionTest
```

**Comment by colemanw** [comment]
@seamuslee001 looks like that was caused by an uncaught exception caused by `civicrm_api3_create_success` trying to do `getfields` with no entity.

**Comment by seamuslee001** [comment]
@colemanw test failures look related

**Comment by seamuslee001** [comment]
@colemanw latest test failures look related

**Comment by colemanw** [comment]
@seamuslee001 I got the tests passing by cleaning up all the places where the api wrapper was being used incorrectly, e.g. with missing `$params['version']` or null `$entity`.

**Comment by eileenmcnaughton** [comment]
Looks like our test cover is working well here - merging now they are passing

**Pull request merged**
