### PR TITLE
dev/accessibility#10 : Make datepicker accessible

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
A user should be able to use datepicker with the help of control keys, not just cursor actions, pretty much similar to this example
https://dequeuniversity.com/library/aria/date-pickers/sf-date-picker

Before
----------------------------------------
Datepicker widget is not accessible

After
----------------------------------------
Datepicker widget is accessible via control keys:
test-multiple-after

ping @colemanw @vingle @seamuslee001

### CODE REVIEW

**Comment by monishdeb** [comment]
Combination of accesskeys and the actions, on datepicket popup : 
1. Tab (5 times) = Default date / current date >> Close button >> Month button >> Year button >> repeat to 1st step
2. Tab to month >> up and down arrow to change month (Jan comes next after Dec on arrowup and vice-versa on arrowdown) >> tab next to select year >> tab next to select day starting from 1st day. 
3. Tab to year >> up and down arrow to change year (year doesn't change if its first or last year in the range) >> tab next to select day starting from 1st day. 
4. On days, use up, down, left and right arrow to change days. Keep pressing down or up arrow on days will switch to next or previous month respectively.

**Comment by colemanw** [comment]
FYI now that html5 is so mature, at some point we should look at simply using the native html5 `<input type="date">` element instead of jQuery.

**Comment by eileenmcnaughton** [comment]
Can we ping @vingle on these too please

**Comment by monishdeb** [comment]
@colemanw I did a quick experiment how it behaves in terms of accessibility, very impressive and smooth. Here's a partial patch to test the html5 on contribution receipt date (although need some additional code to render time field like datepicker): 
```diff
diff --git a/CRM/Contribute/Form/Contribution.php b/CRM/Contribute/Form/Contribution.php
index c824a9d846..9c0a0a43b8 100644
--- a/CRM/Contribute/Form/Contribution.php
+++ b/CRM/Contribute/Form/Contribution.php
@@ -781,7 +781,9 @@ class CRM_Contribute_Form_Contribution extends CRM_Contribute_Form_AbstractEditP
     $receiveDateRequired = !$this->_values['is_template'] && !$this->_mode;
     // add various dates
     $this->addField('receive_date', ['entity' => 'contribution'], $receiveDateRequired, FALSE);
-    $this->addField('receipt_date', ['entity' => 'contribution'], FALSE, FALSE);
+    // pseudocode tp detect the web broswer, as datepicker is not supported in Safari or not accessible
+    //$inputType = CRM_Utils_SameSite::isSafari(mb_convert_encoding($_SERVER['HTTP_USER_AGENT'], 'UTF-8')) ? 'datepicker' : 'date';
+    $this->addField('receipt_date', ['entity' => 'contribution', 'type' => 'Date'], FALSE, FALSE);
     $this->addField('cancel_date', ['entity' => 'contribution', 'label' => ts('Cancelled / Refunded Date')], FALSE, FALSE);
 
     if ($this->_online) {
diff --git a/CRM/Core/Form.php b/CRM/Core/Form.php
index 4e8f85e754..55fc9199fc 100644
--- a/CRM/Core/Form.php
+++ b/CRM/Core/Form.php
@@ -2033,6 +2033,9 @@ class CRM_Core_Form extends HTML_QuickForm_Page {
         $text = $props['text'] ?? NULL;
         unset($props['text']);
         return $this->addElement('advcheckbox', $name, $label, $text, $props);
+        
+      case 'Date':
+        return $this->add('date', $name, $label, $props, $required);
 
       case 'File':
         // We should not build upload file in search mode.
```

Demo : 
after


Another thing I noticed that the html5 date input field is not supported in Safari in some version and not accessible in other. 
So I think we need to support both jQuery and html5 date on basis of `CRM_Utils_SameSite::isSafari` . Should I submit a separate PR based on same approach?

**Comment by monishdeb** [comment]
@eileenmcnaughton I did :) Forgot to ping @JoeMurray

**Comment by vingle** [comment]
@eileenmcnaughton I'm on holiday this week but separate to reviewing this a very enthusiastic yes from me to swapping to `input type="date"` (would also let me drop [~110 lines of Riverlea](https://lab.civicrm.org/extensions/riverlea/-/blob/main/core/css/components/_form.css?ref_type=heads#L503-615) CSS).

FWIW the demo on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date works on my desktop Safari and is keyboard controllable, and works on iOS Safari too (tho less sure how to test a11y there).

**Comment by colemanw** [comment]
@monishdeb IMO we want the widget to use html-5 *or* jQuery. I'm not very interested in supporting both. If it works well in most browsers, then maybe we just have to advise people to use a browser that supports accessibility.

In order to make the switch, we need to verify the html-5 widget can:
1. Read/write ISO format (`YYYY-MM-DD HH:MM:SS`) while displaying localized dates (e.g. `MM/DD/YY`) to the user
2. Support time inputs

**Comment by vingle** [comment]
I'd second that. 
1. *kind of*. "The displayed date format will differ from the actual `value` — the displayed date is formatted based on the locale of the user's browser, but the parsed `value` is always formatted `yyyy-mm-dd`" ([ref](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#value)). So if Civi wants to force a datetime format different to the user's OS default (e.g. USA-style MDY or YMD or DMY from [most other places](https://en.wikipedia.org/wiki/List_of_date_formats_by_country)), it [looks at first search like ](https://stackoverflow.com/questions/7372038/is-there-any-way-to-change-input-type-date-format) it can't do this - or can only do this with web components / a JS plugin. I guess this opens the question of - beyond backwards compatibility - if a Civi instance owner really would want to set a Civi-wide rule for MM-DD vs DD-MM regardless of the national norm for the end-user, as my feeling is that's bad UX/i18n.
2. There are input types for [time](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time) and combined as [datetime-local](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local) - using `YYYY-MM-DDThh:mm`.

**Comment by colemanw** [comment]
I'm sold!

**Comment by eileenmcnaughton** [comment]
I'm just doing some drive-by cheerleading for this work

**Comment by monishdeb** [comment]
Thanks @colemanw and @vingle for your feedback. My apologies for simply picking my old work without doing any  investigation of what's been in latest news for datepicker improvement. It seems we can definitely change the jquery datepicker widget to HTML5 date. At this point I think it would be better to create a new PR and close this one❣️

**Comment by vingle** [comment]
@monishdeb def agree with you. Is this something you're working on, or should we open a gitlab issue?

**Pull request closed without merging**
