### PR TITLE
dev/core#846 Convert Recurring forms to entity forms

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Partial conversion of recurring forms to entity forms

Before
----------------------------------------

After
----------------------------------------
This adds the various requires to convert the form - but with no actual change

Technical Details
----------------------------------------
The main step to convert is to include the trait - I will later add cancel_reason field as an entity field

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton need some jenkins love https://test.civicrm.org/job/CiviCRM-Core-PR/25633/checkstyleResult/new/

**Comment by eileenmcnaughton** [comment]
@seamuslee001 ok - fixed - I'm not convinced jenkins is right about this one

**Comment by mattwire** [comment]
@eileenmcnaughton Can you please rebase.  Then we can merge

**Comment by eileenmcnaughton** [comment]
@mattwire done

**Comment by eileenmcnaughton** [comment]
Note there is a follow on in https://github.com/civicrm/civicrm-core/pull/13997

**Comment by eileenmcnaughton** [comment]
@mattwire are you good to merge this?

**Comment by eileenmcnaughton** [comment]
@mattwire looks like you already reviewed this & it should be ok to merge now

**Pull request merged**
