### PR TITLE
activity import: allow multivalue custom data

### PR DESCRIPTION
**Pull request by michaelmcandrew**
See https://lab.civicrm.org/dev/core/-/issues/2799

### CODE REVIEW

**Comment by seamuslee001** [comment]
@michaelmcandrew I think this probably could do with a unit test

**Comment by jaapjansma** [comment]
@michaelmcandrew I and @bettydolfing are doing review of PR's and we see that this one needs a unit test. Are you able to provide this with unit test? If not we will propose to close this PR.

**Comment by michaelmcandrew** [comment]
It is on my list but I am unlikely to write a PR for a month or so at least :(

Feel free to close and I will re-open when I can get round to doing so.

**Comment by jaapjansma** [comment]
Ok. I will close it for now and when you are ready feel free to reopen. Or create a new PR.

**Pull request closed without merging**
