### PR TITLE
CRM-20012 set empty date values

### PR DESCRIPTION
**Pull request by lcdservices**
* [CRM-20012: contribution batch update: can't unset thank you date value](https://issues.civicrm.org/jira/browse/CRM-20012)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@lcdservices I've done work on dates in a different PR #9729 which completely removes the chunk of code you are editing - can you test it there  - I suspect that it will still need a tweak similar to what you have added  - although it would apply to non-date fields too?

I'll add you permission to push to my github fork

**Comment by lcdservices** [comment]
I don't think your PR is working with the same code. Your PR deals with accounting batch code -- mine addresses bulk update via profile (which has a task file name of "batch" but is not the same as accounting batches).

**Comment by eileenmcnaughton** [comment]
For background - the datepicker widget is much simply than the dateTime fields because it stores the date in a standardised format & presents it in a custom format - meaning that all the code we have for date wrangling is not required with the datepicker field.

**Comment by eileenmcnaughton** [comment]
I've tested & fixed this in #9729  - basically ripping out legacy handling to make the datepicker work properly  fixed this - https://github.com/civicrm/civicrm-core/pull/9729/commits/ce6f5b88f9d5cb25a88f413f3e651cca43e051fb

**Comment by eileenmcnaughton** [comment]
superceded by #9729

**Pull request closed without merging**
