### PR TITLE
Correct inconsistent fileID reference

### PR DESCRIPTION
**Pull request by mecachisenros**
Overview
----------------------------------------
Correct inconsistent `$fileID` reference causing new File entity creation when updating a Contact's custom field of type File.

Before
----------------------------------------
Steps to reproduce:
1. Create a custom field of type File for Contacts entity.
2. Create a file through the API:
```
$file = civicrm_api3('File', 'create', [
  'document' => "An attachment.",
  'mime_type' => "text/plain",
  'uri' => "some_attachment.txt",
]);

// result
    ...
    "values": {
        "id": "80",
        "mime_type": "text/plain",
        ...

```
3. Update a Conctact's custom File field ( ie Attachment, `custom_13`) through the API passing the created `file_id` in step 1:
```
$contact = civicrm_api3('Contact', 'create', [
  'contact_type' => "Individual",
  'id' => 203,
  'custom_13' => 80,
]);

// result
    ...
    "values": [
            "contact_id": "203",
            "custom_13": "81", // file id 81, a new file has been created
            ...
```

After
----------------------------------------
The custom File (`custom_13`) is updated with the passed `file_id` as expected.

Technical Details
----------------------------------------
N/A

Comments
----------------------------------------
N/A

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins ok to test this

**Comment by seamuslee001** [comment]
ping @jitendrapurohit @eileenmcnaughton

**Comment by kcristiano** [comment]
I tested this on Drupal 7 and WP.  I can recreate the issue without the patch, and once patched custom files are created correctly and when updating/creating the contact record the same id created is attached.



* ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) Pass
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) Pass
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) Pass  
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) Pass
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) Pass
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) Pass: tested via API using drush and cv on Drupal 7 and WP.  Also tested via editing and updating Contact via UI (direct Edits) and via Profile.
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) Pass
* ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) Pass:  Changes should not affect external calls as they should use `file_id` which has not changed

**Comment by mecachisenros** [comment]
thank you @seamuslee001 and @kcristiano

**Pull request merged**
