### PR TITLE
CRM-20973: Fixes "Call to undefined function Civi\API\civicrm_api3_create_error() …

### PR DESCRIPTION
**Pull request by dsnopek**
… in Civi/API/Kernel.php on line 413"

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I'm really mystified about this - if this is an issue why does anything work? Is there anything special about your environment or how you are calling CiviCRM

**Comment by seamuslee001** [comment]
@eileenmcnaughton looking at the github search for this function where it is called, its called from other places but this is the only place that has a namespace and because civicrm_api3_create_error isn't within that namespace it is looking for a function civicrm_api3_create_error within the namespace and its failing so adding \ takes it back to the root

**Comment by eileenmcnaughton** [comment]
OK - but it's not new so why has something that would seem catastrophic not been apparent until now?

**Comment by seamuslee001** [comment]
*shrugs shoulders* *flips tables*

**Comment by totten** [comment]
jenkins, add to whitelist

**Comment by dsnopek** [comment]
@eileenmcnaughton Maybe it just took a long time for anyone to notice because it's an error during an error condition? The code that needs the `\` is only called when there's an error to create the error object, and this is also an error, so even though a nice error object isn't coming back to the caller, it's still an error when an error should happen.

I haven't done `git blame` or anything, but I suspect the call to `civicrm_api3_create_error()` existed before that file had a `namespace` declaration, and so maybe the error conditions weren't checked that thoroughly after the namespace was added? That's my best random guess :-)

In any case, I doubt it has anything to do with something special in my environment, but I personally encountered the error when installing the civicrm_views module on Drupal 8 which was doing a bad API call on purpose for dubious reasons - see https://issues.civicrm.org/jira/browse/CRM-20974

**Pull request merged**
