### PR TITLE
CRM-18688: Cancel IPN cancels entire membership

### PR DESCRIPTION
**Pull request by nishant-bhorodia**
**Issue:**
If user cancels the payment on off-site payment processor (Sagepay, Paypal etc.), It cancels entire membership.

**Reason:**
In `public function cancelled`, the status of membership was set to "cancelled" without checking the current status of the membership.

**Solution:**
Cancel the status only if membership status is not one of the active statuses (new, current or grace).

---
- [CRM-18688: Cancel an IPN payment when renewing membership cancels entire membership](https://issues.civicrm.org/jira/browse/CRM-18688)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Hi @nishant-bhorodia can you create a PR against master also I think there may be something here 

https://github.com/civicrm/civicrm-core/blob/master/CRM/Contribute/BAO/Contribution.php#L1697
https://github.com/civicrm/civicrm-core/blob/master/CRM/Contribute/BAO/Contribution.php#L1731

pinging @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
You'll also be surprised I'd like to discuss writing a unit test for it :-)

I would probably tackle writing a test for this by adding a new api call (e.g contribution_recur.cancel) and testing it via that. This is not  a change I would personally want to deploy to customers without 'purchasing a test warranty' and as I'm sure your colleagues will tell you I have completely convinced them to write unit tests daily now :-)

**Comment by nishant-bhorodia** [comment]
Hello @seamuslee00,
Thank you. I will create a PR for master as well.

Hello @eileenmcnaughton 
I am having a look into how to write unit tests and will update the PR with tests. Although is there anything you'd like me to take care of while writing the tests for this ?

Thanks in advance.

Kind Regards,
Nishant Bhorodia

**Comment by eileenmcnaughton** [comment]
I guess ideally we want to wrap the code in an api for testing & not have the logic on the IPN class as it is really BAO logic as to what to do when a recurring contribution is cancelled, not IPN logic. Ideally the IPN would call the api function

**Comment by nishant-bhorodia** [comment]
So if I understood right, we create a function inside BAO, called contribution_recur_cancel which accepts the $membership and Transaction status and write all the "status change" login in that function, then we write test to test this new function.

Am I close ? :)

**Comment by eileenmcnaughton** [comment]
yep - although I would probably expose it through the api & test it via that wrapper. Does the function need to know more than the recurring contribution id ?  Just to be clear - if we are NOT cancelling active statuses here- what statuses ARE we cancelling memberships for?

Are you stopping short of removing these lines

 $membership->status_id = $membershipStatuses['Cancelled'];
$membership->save();

because you are not sure if there is a use case for them somewhere somehow - or because you think there is a valid use case.

If the former, I can't think of a valid use case. I would be inclined to suggest emailing the dev list & if no-one else can justify those lines completely removing them rather than just hobbling them

**Comment by nishant-bhorodia** [comment]
Those lines need to execute for the following case:

1. user wants to sign up for a new membership.
2. Hitting continue creates a membership with "pending" status, before civi redirects to off site payment gateway (Sagepay, Paypal etc.)
3. User changse his/her mind  and cancels payment on the off site payment gateway.

In above scenario, the membership needs to be cancelled and that's where we need that code.
But because there is no check, regardless of what the current status of the membership is, it just gets cancelled if user cancels the payment.

**Comment by eileenmcnaughton** [comment]
Ah, I guess that is the way Civi works at the moment - except I would possibly prefer just to leave pending in that case. Perhaps it makes more sense to white list in Pending? In which case I think it's OK to leave on the processor class since it is very specific to a particular workflow (which I kind of disagree with but not enough to blow the scope of this fix out of the water).

**Comment by nishant-bhorodia** [comment]
So what you mean is rather than checking for $activeStatuses, I should just check for "Pending" status and run the code ?

And do we write a test in this case ?

**Comment by eileenmcnaughton** [comment]
Yes to the first question. Re the latter I feel a bit more relaxed about the test with the functionality clarified by specifying pending (& because I'm not convinced about changing the  Pending to Cancelled rather than leaving Pending anyway)

**Comment by nishant-bhorodia** [comment]
Thanks @eileenmcnaughton  :)

**Comment by guanhuan** [comment]
Hi @eileenmcnaughton ,

I believe currently if the payment gateway sent back a cancellation callback, it cancels the related objects in CiviCRM. Although Paypal never sends back any cancellation signal previously (not sure if this is changed now). The fix is mainly targeting the cancellation cancels also the active objects which breaks membership renewal process.

Could you let us know if there is anything else we need to do to push this fix forward?

Best

Guanuhan

**Comment by eileenmcnaughton** [comment]
I think in the discussion above we agreed that a whitelist of statuses where it IS appropriate to cancel the membership makes sense (rather than a list of ones where it does not) - although I'm still not convinced that the membership object should be updated from Pending if the payment fails, restricting this to Pending status seems like an acceptable compromise.

NB actually getting it merged will also depend on who steps up for the QA cycle & resources there.

**Comment by eileenmcnaughton** [comment]
OK I feel we've been through the hoops on this one & I think the change is good. Merging

**Comment by eileenmcnaughton** [comment]
I just merged this but I realised just now it's against 4.6 & it's not clear if it is fixed in master? Normally the rule is to merge to master first so people don't upgrade & re-encounter a fixed bug. Looks like I made a mistake merging first - or is there a PR against master that I just need to track down?

**Comment by nishant-bhorodia** [comment]
Hello @eileenmcnaughton,

Thank you for merging this. I will create a PR for master as well today.

Kind Regards,
Nishant Bhorodia

**Comment by eileenmcnaughton** [comment]
Great

**Pull request merged**
