### PR TITLE
[REF] Refactor price field form to allow for unit testing of the form

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This refactors the Price Field Form for unit testing and adds in a unit test for #18297 

Before
----------------------------------------
No Unit test

After
----------------------------------------
Unit Test

I expect this to fail until #18297 is merged

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
so a couple of things (non blocking since I think this is just a part-step)

1) ideally we should convert to an entity form since I *think* that is why MembershipType blocks over-long values in minimum_fee (or it might be     $this->addRule('minimum_fee', ts('Please enter a monetary value for the Minimum Fee.'), 'money');
)

2) the final check in the test should be the expected value not a calculated value so we are sure of what we are checking
ie  

```  $this->assertEquals(CRM_Utils_Rule::cleanMoney($this->publicFieldParams['option_amount'][1]), $priceOptions['values'][$priceOptions['id']]['amount']);
```
 vs

```
   $this->assertEquals(10.00 $priceOptions['values'][$priceOptions['id']]['amount']);
 ```

**Comment by seamuslee001** [comment]
@eileenmcnaughton this is already an entity form i think https://github.com/civicrm/civicrm-core/pull/18414/files#diff-d202b67f619f01e882ad298d75d47c6dR23

**Comment by seamuslee001** [comment]
@eileenmcnaughton I believe I have addressed Item 2 now and I think Item 1 is already addressed but it might be a bit problematic on that form given your dealing with 2 different entities on the same form (i.e, you have a PriceField entity and a PriceFieldValue entity being handled on the same form)

**Comment by eileenmcnaughton** [comment]
ok

**Comment by seamuslee001** [comment]
Test failures as expected

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
```
Test Result (2 failures / +2)
CRM_Price_Form_FieldTest.testLargeFloatOptionValue with data set #0
CRM_Price_Form_FieldTest.testLargeFloatOptionValue with data set #1
```

**Comment by eileenmcnaughton** [comment]
@seamuslee001 probably the test is too ambitious - if you look at the screenshot I did php truncates those strings & short of switching to brick money there is not much we can do

**Comment by seamuslee001** [comment]
@eileenmcnaughton the problem is that it was highlighting a problem where by it was chopping after the first thousand char anyway.

**Comment by seamuslee001** [comment]
@eileenmcnaughton so after we merged your fix the tests passed.  This is because the database can support up to 9 digits before the decimal separator and 9 after as per the test. But because on the Field Form (unlike the edit option value form) we get the DAO attributes the form field gets a max length  set to 14 char  so 123,456,789. = 12 chars already https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/DAO.php#L826

**Pull request merged**
