### PR TITLE
Fix edit button for 'Import/Export Mapping'

### PR DESCRIPTION
**Pull request by m-hobby**
Overview
----------------------------------------
Fix the edit button for 'Import/Export Mapping' new searchkit admin page.

Before
----------------------------------------
Edit button re-loads the admin page instead of form
image

After
----------------------------------------
Edit button correctly loads the field edit
image

Technical Details
----------------------------------------

Comments
----------------------------------------
Thanks @pradpnayak

### CODE REVIEW

**Comment by pradpnayak** [comment]
Looks good to me, tested with the URL change. The Mappings are updated correctly

**Comment by eileenmcnaughton** [comment]
@19ATF72 are you able to fix the style issues - https://test.civicrm.org/job/CiviCRM-Core-Style/7840/checkstyle/

**Comment by eileenmcnaughton** [comment]
the other test fails all look unrelated

**Comment by eileenmcnaughton** [comment]
This is mergeable apart from the style issue based on the above - I have created https://github.com/civicrm/civicrm-core/pull/28801 to address the style issue so we can get this improvement merged

**Pull request closed without merging**
