### PR TITLE
[REF] Add Index onto job_id column to speed up loading of a specific …

### PR DESCRIPTION
**Pull request by seamuslee001**
…job's job log

Overview
----------------------------------------
I'm not sure why this isn't an FK but any who adding this index should speed up loading of pages like `civicrm/admin/joblog?jid=34&reset=1` 

Before
----------------------------------------
No index on this so query like `AND job_id = x` need to do full table scans

After
----------------------------------------
Index

ping @eileenmcnaughton @demeritcowboy

### CODE REVIEW

**Comment by demeritcowboy** [comment]
My only hesitation is the comment in the xml just above, where it explicitly says "not a foreign key just for logging". I suppose it means there are some sites where this never has anything in it and so this would be a wasted index, but I'm not sure what sites that would be, and other than disk space probably still wouldn't be a performance hit. I don't see anything in https://issues.civicrm.org/jira/browse/CRM-8358 that gives more explanation.

So +1.

**Comment by seamuslee001** [comment]
@demeritcowboy my other thought was that perhaps it meant that if a job got removed or something via managed entities or something then the logs for that job don't get removed as well

**Comment by demeritcowboy** [comment]
Good thought, although that would just need the right ON DELETE clause.

**Comment by mattwire** [comment]
@seamuslee001 Agree. But can we handle this one at the same time: https://github.com/civicrm/civicrm-core/pull/24746

**Comment by seamuslee001** [comment]
closing in favour of #24746

**Pull request closed without merging**
