### PR TITLE
(REF) Standardize UFField create function

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Makes UFField::create act more like other BAO::create functions.
Also fixes a bug introduced in #14041 where Formatting fields cannot be created in the API or UI

Before
----------------------------------------
Nonstandard quirky function.
Adding a Formatting field to a profile broken on master branch.

After
----------------------------------------
More reasonable function.
Fixed adding a Formatting field to a profile.
.

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton this fixes a bug caused by my last PR #14041

**Comment by eileenmcnaughton** [comment]
@colemanw I took a look at this but I feel nervous that there are lots of changes under the banner 'cleanup' in here & I don't feel confident that I would pick up if there is an error in here on doing code review

**Comment by colemanw** [comment]
@eileenmcnaughton since the BAO should now be acting in a standard way, I've taken it off the syntaxConformanceTest blacklist, which should help with your nervousness :)

**Comment by colemanw** [comment]
Adding `has-test` label because this PR adds syntaxConformanceTest coverage to the `UFField` api.

**Comment by seamuslee001** [comment]
@colemanw test fail looks related https://test.civicrm.org/job/CiviCRM-Core-PR/25905/testReport/junit/(root)/api_v3_SyntaxConformanceTest__testCreateSingleValueAlter/testCreateSingleValueAlter_with_data_set__82/

**Comment by seamuslee001** [comment]
I think given that with the syntax conformance test passing then i think we are ok with this refactor here. I'm going to merge this on the basis it fixes an error and that 5.14 is not yet in RC so have time to test

**Pull request merged**
