### PR TITLE
APIv4 - Properly show deprecated joins in unit tests (fixes dev/core#2771)

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Replacement for #21188

See https://lab.civicrm.org/dev/core/-/issues/2771

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
thanks @colemanw  - this looks good. We've never discussed exceptions much - in part because in the past all roads went to `CRM_Core_Exception` - but the issues this release suggest we might need to think a bit more about what ones we use & how

**Comment by eileenmcnaughton** [comment]
@colemanw @seamuslee001 - am I just imagining it or did CI not run on this?

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton seems so could happen if the webhook from github failed for some reason

**Comment by eileenmcnaughton** [comment]
@seamuslee001 yeah I just spotted another of @colemanw's PRs (probably at a similar time) that hasn't run

**Pull request merged**
