### PR TITLE
dev/core#4076 split up the theme method

### PR DESCRIPTION
**Pull request by herbdool**
Fixes https://lab.civicrm.org/dev/core/-/issues/4076.

This is an oddball. The Drupal 8 version needed to be different from the other flavours. I haven't tested it.

### CODE REVIEW

**Comment by seamuslee001** [comment]
This seems fine to me @demeritcowboy @kcristiano thoughts?

**Comment by herbdool** [comment]
I've tested this in Drupal 9, Drupal 7 and Backdrop. I've also tested in "maintenance" by visiting `/civicrm/upgrade`. It all works. The Drupal 9 code is the only new code that wasn't moved from somewhere else.

I'm going to bug @demeritcowboy again since it's similar to my other recent PRs.

---

I would create a follow-up issue to resolve some confusion with this whole theme workflow. WordPress and Joomla will always short circuit `CRM_Utils_System::theme()` by printing directly rather than return it. And in Drupal* they will normally return the content, which then usually gets `echo`ed anyway right away. The only reason for returning anything seems to be when a Drupal* system calls `CRM_Core_QuickForm_Action_Display::renderForm()` or `CRM_Utils_REST::loadTemplate()` (only called with some antique(?) `civicrm/inline` paths). But how important is that if WordPress and Joomla will *never* make it that far.

**Comment by demeritcowboy** [comment]
For drupal 8 what's happening for me is the upgrade screen looks like this. Note the upgrade button isn't a button or clickable link. And it's very plain with no styling of the sections and just black and white. Does it depend on what theme you're using on the drupal side? I have "seven".

Untitled3

**Comment by herbdool** [comment]
My attempt was to try to use Drupal 9 specific functionality that is used for the Drupal 9 upgrade screen which looks like this:

d9-upgrade

There are a couple things that we may need to figure out: how to set the proper title (it should read something like "Upgrade to 5.XX ..." or "Your database has already been upgraded to...". I'm not sure since the CiviCRM "maintenance" variable could happen not just with the upgrade. I'm not sure how it was set in Drupal 7 since it doesn't appear in Drupal 7-specific class. 

Drupal 7:
d7civi

The other thing is the styling as you noted. Drupal 9 maintenance will use a different renderer class which won't print out the menus or breadcrumb. Like D7 Civi upgrade screen I think we should not print out the menus and breadcrumb, but still include the Civi css so the button styling looks better.

Without this PR, it looks like the following (with menus, breadcrumb etc):

d9civi-without-patch

and with the PR it looks like this to me (no menus - good, but also no Civi css - bad):

d9civi-with-patch

Oddly it still uses the default Drupal front theme whereas the main Drupal upgrade screen just has a grey background.

**Comment by herbdool** [comment]
I forgot that Drupal 7 (and Backdrop) use `drupal_get_title()` such as in `https://api.drupal.org/api/drupal/includes!theme.inc/function/template_preprocess_maintenance_page/7.x. So it can get the title that way. And I think the theme function in question here assumes that.

**Comment by herbdool** [comment]
Okay, I figured out the title: using the `civicrm.page_state` service from the civicrm module.

**Comment by herbdool** [comment]
2023-02-12 17 17 40 d9civi lndo site 1aad97739996

**Comment by demeritcowboy** [comment]
Or at first glance this seems to work:
```
$build['content'] = [
  '#markup' => \Drupal\Core\Render\Markup::create($content),
];
```

**Comment by herbdool** [comment]
I've taken your suggestion and stripped out the maintenance part. I'll create a follow-up issue for that.

I think the Drupal renderer strips out inline JS, CSS. I noticed the `<button>` tag got stripped out from the HTML. Plus we may need to explicitly include Civi core resources.

**Pull request merged**
