### PR TITLE
CRM-15915 standardise output on custom fields with arrays 

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
This is a replacement for https://github.com/civicrm/civicrm-core/pull/5104/files

I have done  it against 4.6 rather than master as the other fixes went into 4.6 & it's good to get api fixes working in as many versions as possible. 

I have some small misgivings about this as it IS possible that a dev might have coded around the way it currently works & this could cause problems. It's not an obvious coding pattern to follow - ie. because if you are looking for the values of the custom field they are in the values of the relevant field - they just happen to be the array keys as well.

I'm inclined to think this is OK - but we should 
a) add it to the change log
b) potentially keep this PR open until your last bugs are fixed (so if a release goes out in the meantime it isn't in it)
c)  then do a quick blog mentioning there have been a bunch of minor fixes & people should check the list - are you up to do the blog/ update the change log @johanv 

@totten @colemanw - FYW (like FYI but For your wisdom - should you care to impart some :-)

---
- [CRM-15915: API returns values of multi-select custom field in different format depending on the entitiy the custom field set is used for.](https://issues.civicrm.org/jira/browse/CRM-15915)

### CODE REVIEW

**Comment by johanv** [comment]
I guess I can do a blog post. But I am not sure I can do it today. Is tomorrow ok?

I am not sure about what you mean with the change log. Where can I find it?

**Comment by eileenmcnaughton** [comment]
The change log it here

http://wiki.civicrm.org/confluence/display/CRMDOC/API+changes

I was more thinking the blog might be next week or so. I want to merge in your custom data one too but just getting my head around everything. I've rebased / squashed it into 2 commits rather than 24 & am looking at some changes. I'll give you feedback once I've looked more

**Comment by johanv** [comment]
Cool. In the mean time, I will try updating the changelog. (tonight or tomorrow)

**Comment by eileenmcnaughton** [comment]
Hmm test output is not promising

**Comment by johanv** [comment]
Changelog is updated with the changes I am aware of. I added question marks to the things that are not merged yet.

**Comment by eileenmcnaughton** [comment]
I'm going to close this out now it's conflicted until one of us has time to kick it back into gear- it did cause test fails which is where it stalled :-(

**Comment by colemanw** [comment]
Hate to lose out on all those tests :(

**Comment by eileenmcnaughton** [comment]
Yes - the JIRA is still open & I added a link to this PR

**Pull request closed without merging**
