### PR TITLE
CRM-21613:  'Manage Tag' page Improvements

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
1. Bring a visual indicator to show search in progress while searching for a tag.
2. Don't try to fetch the tag ids on basis of each character typed on search box, rather than delay by 1sec and fetch the ids on basis of string entered. This will improve performance for sites which have >1k tags.

Before
----------------------------------------
test-multiple-before

After
----------------------------------------
test-multiple-after

---

 * [CRM-21613: Search issues on 'Manage Tag' page](https://issues.civicrm.org/jira/browse/CRM-21613)

### CODE REVIEW

**Comment by monishdeb** [comment]
ping @lcdservices @colemanw

**Comment by lcdservices** [comment]
this looks good. the visual indicator of search is helpful, especially when there are a large number of tags being searched, and this patch also improves the reliability of the search.

**Comment by eileenmcnaughton** [comment]
I think @lcdservices review is generally enough here as this is a form layer fix & @lcdservices has tested it. I have added 'merge-ready' in order to give @colemanw a week or so to weigh in if he wishes

**Comment by colemanw** [comment]
I'm not a huge fan of the big grey box which blocks everything. Changing the **x** next to the search box into a spinner during searching would be more subtle but possibly just as effective.

**Comment by monishdeb** [comment]
"I'm not a huge fan of the big grey box which blocks everything" that was my intention :) not to allow any changes to tree structure while searching, might break something or leads to an incorrect tag tree. But will change the **x** with spinning Civi logo ? beside search box while searching 👍

**Comment by colemanw** [comment]
Ok I see what you mean, people shouldn't interact with the tree while it's being rebuilt.
Maybe it's just the color that bugs me. Normally our `$.block()` styling is white/transparent.

**Comment by monishdeb** [comment]
@colemanw thanks for the tip :) it did work. And here's the commit https://github.com/civicrm/civicrm-core/pull/11510/commits/47de3b98b417e3efffa7dd968b5923e83dda3a8b

**Pull request merged**
