### PR TITLE
(dev/core#594) Fix key-value mappings for WYSIWYG setting (editor_id). Accept keyColumn option.

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This fixes an issue where by the editor_id setting does not work properly because the javascript and other parts are expecting the string of the name of the Editor whereas in https://github.com/civicrm/civicrm-core/commit/719eda4a59b6c95aa670ce9c95aa10d2f91478ac#diff-45cac86e3687ecb3e1996985223d2a31 it was changed to keyed on values because that is what is the default for settings pseduoconstants 

Before
----------------------------------------
* Saving the `editor_id` in the GUI leads to an invalid setting.
* In the metadata used for `Settings.getoptions` in APIv3, one can set an `optionGroupName`. The key-value mappings are implicitly based on `value=>label`.

After
----------------------------------------
* Saving the `editor_id` in the GUI leads to a valid setting.
* In the metadata used for `Settings.getoptions` in APIv3, one can set an `optionGroupName`.  By default, the key-value mappings are based on `value=>label` (as before), but one may optionally customize with the `keyColumn`. This parallels the [XML Schema convention](https://docs.civicrm.org/dev/en/latest/framework/database/schema-definition/#table-field-pseudoconstant) that shapes most generic `*.getoptions` calls.

ping @mattwire @monishdeb @andrewpthompson @MegaphoneJon

### CODE REVIEW

**Comment by totten** [comment]
@seamuslee001 Cool, that makes sense -- so it's basically adapting a convention from the DAO/fields metadata to also work in the settings metadata. I'll just update the description so that it reflects that.

**Comment by seamuslee001** [comment]
@totten i'm working on a post upgrade message now. In terms of running it i would check out the test site -> go to the display preferences -> set the editor to be ckeditor -> make sure the configure button is visible -> then after saving the page check a page with a text editor e.g. manage contribution page and check the ckeditor loads.

**Comment by seamuslee001** [comment]
@totten added the post upgrade message now

**Comment by andrewpthompson** [comment]
@seamuslee001 I've tested this patch and it works as expected.

**Comment by seamuslee001** [comment]
@totten if your happy with the upgrade message i think this is good for merge @monishdeb

**Comment by totten** [comment]
Thanks @andrewpthompson - that covers the last `r-run` criterion. 👍 

@seamuslee001, I did a little copy-editing on the message. Merge-on-pass.

**Comment by seamuslee001** [comment]
thanks @totten

**Pull request merged**
