### PR TITLE
dev/core#2288 - Alternative fix search range for select/radio custom fields - now disabling the combination

### PR DESCRIPTION
**Pull request by kainuk**
Overview
----------------------------------------
This is an alternative fix for  https://github.com/civicrm/civicrm-core/pull/19332 . 

It follows a different assumption. PR 19332 assumes the combination search range and radio buttons makes sense, and it must be fixed. This PR argues it does make less sense and disallows it. It makes saving this combination impossible.  

Technical
----------------------------------------
The range code from the template is also removed. It cannot be used anymore.

Comments
---------------------------------------
There maybe some users that have this combination in use. The effect of the patch is that the field will disappear in the screen. Opening the definition and saving it will solve the problem

### CODE REVIEW

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Comment by demeritcowboy** [comment]
I've commented on the lab ticket. My own vote is for this one but it would be good if upgrade for the field and existing smart groups is handled by upgrade script.

**Comment by eileenmcnaughton** [comment]
We discussed this one in PR queue collaboration & there was a general preference for this approach rather than supporting something we didn't think was intended / which seemed unpredictable

Thanks @kainuk @demeritcowboy

**Comment by demeritcowboy** [comment]
Just noting that while I applied the patch to see what a smart group would look like, so I can say it doesn't crash if you make such a field and search for it, other than that I didn't really review it.

**Pull request merged**
