### PR TITLE
mailing#96: Warn on invalid mailing options

### PR DESCRIPTION
**Pull request by MegaphoneJon**
https://lab.civicrm.org/dev/mail/-/issues/96

Overview
----------------------------------------
Specifying a "Selection Method" in mailing options (in CiviMail) without specifying a location type gives a DB error.

Steps to replicate (demo server is fine):
* Create a new mailing.
* Click the wrench next to "Recipients".
* Set a *Selection Method* other than "Automatic" but do not touch *Location Type*.
* Attempt to submit the mailing (or press the "X Recipients" to recalculate immediately).
Selection_1115

Before
----------------------------------------
Unhelpful errors: "Mailing content is out of date, please refresh" or "DB Error: Syntax Error".

After
----------------------------------------
Helpful error: You set an email Selection Method without specifying a Location Type.  Please go back and change your recipient settings (using the wrench icon next to "Recipients".

### CODE REVIEW

**Comment by demeritcowboy** [comment]
jenkins retest this please. It's one of those intermittent timing fails:

```
CRM_Core_BAO_MessageTemplateTest::testContactTokens
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'cs=97eb423fd8d6818a0ff94c275a14b641'
+'cs=f4173719ab4208304c208bda26cc9602'

/home/jenkins/bknix-dfl/build/core-20536-3u4rj/web/sites/all/modules/civicrm/tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php:173
```

**Comment by ericfg** [comment]
a subset of sites I maintain ran into problems after the update this patch was included in. 
on those sites, it sees an empty selection method as having value, 

the solution that I'm using for now is changing 
` if ($email_selection_method !== 'automatic' && !$location_type_id)`
 to 
`  if ($email_selection_method !== 'automatic' && is_numeric($location_type_id))`

does that still work for the contexts that led you to add this check? if so I'll submit the change

**Comment by demeritcowboy** [comment]
I'm having trouble relating `it sees an empty selection method as having value` with `is_numeric($location_type_id)` and why that would fix it. Can you give some specific values for what you're seeing for $email_selection_method and $location_type_id when the problem comes up?

**Comment by ericfg** [comment]
when starting from a contact search and selecting to use civimail to email that result set it throws the error, but since the user is not at a screen with a wrench they can't do anything. 

I don't know what the value is that php is reading as existing in $location_type_id, I can get that info for you soon. 
All I know is that if I change it to look to see if location_type_id is numeric (which if set in a way that will have any result it should be) the error goes away and we can use civimail from search results again. 

that change solves my edge case (on a number of sites that were built at different times and are on different servers) and keeps the original intent of the change in place.  I maintain sites that did not hit this problem on the 5.40 update so I understand that this is not an issue most people are hitting. I'm just at a loss to understand what's going on at this point. 

I'll get you more info when I have time to dig into this more.

**Pull request merged**
