### PR TITLE
dev/core#1287 Allow bidirectional relationship assignment based on contact type A

### PR DESCRIPTION
**Pull request by scoobird**
Overview
----------------------------------------
When assigning relationships from search results, look at contact types for both A and B.
image
image

Before
----------------------------------------
Only target contact type (Contact B) is considered

After
----------------------------------------
All relationship options where either contacts A and/or B fit the criteria are considered.
image

Comments
----------------------------------------
Not sure if there are other implications for changing this.

### CODE REVIEW

**Comment by colemanw** [comment]
@civicrm-builder add to whitelist

**Comment by colemanw** [comment]
@scoobird thanks for this! Hopefully someone in the community will step up to test it soon.

**Comment by demeritcowboy** [comment]
I'm happy to look at this since my head is in A-to-B/B-to-A space right now (and will probably take years to recover from it). The test failure might be related - I'm not too familiar with the SyntaxConformance ones but this failure suggests maybe there's something about Profiles that might be related.

**Comment by demeritcowboy** [comment]
Hi @scoobird. Unfortunately I don't think this is right. Perhaps I'm misinterpreting the issue but see my comments below and let me know what you think.

* General standards
    * [`r-explain`] __Undecided__
      * For one, the stackexchange post linked in the [lab ticket](https://lab.civicrm.org/dev/core/issues/1287) seems like a different question, where they are getting dropdown choices that they think shouldn't be there. I might post separately on the stackexchange post, but at least based on the description here seems different.
        * (For the record, for the SE post, I think civi is technically doing the right thing. Now whether there's a use-case to batch-relate a set of orgs to a single individual is a valid question, especially for something like Employee, and so what they seem to be asking is that civi should hide those. But it's an equally valid question that maybe somebody has a use for it in a more general case than Employee so why prevent it.)
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __Issue__
      * I think the results end up backwards. If I add the type like in the before/after screenshots and then do a contact search and add to an org, I get these two records, which is wrong.


      * Compared to e.g. Volunteer, your relationship type definition is backwards. If you were to define it the same way as Volunteer you wouldn't need any patch.
      * It also ends up backwards if you first search for orgs and then try to batch relate those orgs to a single individual.
* Developer standards
    * [`r-tech`] __PASS__
    * [`r-code`] __PASS__
    * [`r-maint`] __Undecided__
    * [`r-test`] __PASS__
      * Test failure seems unrelated. Also it passes fine when I run the test locally with the patch applied.

**Comment by demeritcowboy** [comment]
Ok thanks for the explanation - I was confused by the screenshot that showed the "is" corresponding to the "Individual", but your "is"'s are corresponding to the orgs.

And yes you're right there's nothing on the create screen itself that gives guidance or enforces consistency with the stock relationship types. That might make for an interesting extension: "Relationship Counselor" is probably what I'd call it...

When you add your update I'll give it another go.

**Comment by demeritcowboy** [comment]
Overall it looks good but I did a grep to see where the changed function was used and discovered a feature I didn't know existed. See r-run below.

* General standards
    * [`r-explain`] __PASS__
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __Issue__
      * With CiviCase enabled there's a dropdown action on contact search results called `Add To Case As Role`, and with the patch it causes two things:
        * There are roles that appear that shouldn't (like Org related ones when the search result selected contact and case client are both individuals), and you get warning notices if you try to use them and it doesn't assign anything (which is probably good though).
          * Example: `Notice: Undefined offset: 6 in CRM_Case_Form_AddToCaseAsRole->postProcess() (line 78 of .../CRM/Case/Form/AddToCaseAsRole.php).`
        * The relationship types in the choice list seem to be backwards from what I see in a stock install like dmaster.demo.civicrm.org, and then if you choose one that is a regular individual to individual it assigns it, but the reverse of what was listed. Example: On a stock install the list has "Benefits Specialist is", and it assigns that correctly. With the patch, the dropdown shows "Benefits Specialist" (the other direction), but then assigns the "Benefits Specialist is" direction on the case. There's an argument that the dropdown here isn't complete to begin with, but on the public demo it's consistent with itself.
* Developer standards
    * [`r-tech`] __PASS__
    * [`r-code`] __PASS__
    * [`r-maint`] __Undecided__
    * [`r-test`] __PASS__

Sorry it seemed so good until I did the grep. It's amazing what changing 3 lines can do. I haven't looked yet at why it's causing this.

**Comment by scoobird** [comment]
@demeritcowboy thanks so much for taking another look! And no need to apologize. That feature is new to me too, I'm not a heavy user of CiviCase. I will take a look at AddToCaseAsRole.php. Curious that it is behaving in a backwardsly way. I wonder if the two can be brought more into alignment.

**Comment by jaapjansma** [comment]
Betty and I are reviewing PR's and we wonder whether we can test this PR. And whether this PR is ready to be merged (after testing) or whether it needs more work based on the comments from @demeritcowboy 

If it needs more work do you plan to  do this @scoobird?

**Comment by scoobird** [comment]
@jaapjansma Hello! Yes, there is still work needed on this to resolve any issues with Case behavior. I have it on my task list.

**Comment by jaapjansma** [comment]
We will close this PR as no work has taken place since 19 feb.

**Pull request closed without merging**
