### PR TITLE
Upgrade htmlpurifier to 4.10 to support PHP7.2 and install via composer

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This upgrades the HTML Purifier library to be version 4.10 to support PHP7.2 and installs it via composer

ping @mfb @totten

### CODE REVIEW

**Comment by mfb** [comment]
There are some hardcoded references to the HTMLPurifier path in CRM/Core/IDS.php and CRM/Core/ClassLoader.php

**Comment by mfb** [comment]
I know that HTMLPurifier needs to cache some things, but I can't see if/where that is happening in my instance. should be some directories (CSS, HTML, URI) containing files with the HTMLPurifier version and a hash, e.g. CSS/4.10.0,4114918a13a428a8482a8a449792a5a8747582b5,1.ser

**Comment by seamuslee001** [comment]
you should check wherever this resolves to `$tmpDir = empty($config->uploadDir) ? CIVICRM_TEMPLATE_COMPILEDIR : $config->uploadDir;`

**Comment by mfb** [comment]
I believe Civi has disabled the cache for some reason.

https://github.com/civicrm/civicrm-core/blame/master/CRM/Utils/String.php#L646

But why? The cache really helps speed up HTML Purifier.

**Comment by seamuslee001** [comment]
looks like its been there from the beginning
 https://github.com/fuzionnz/civicrm-svn/commit/f3de1ba2d5d75dc0c1aaac141d4e427eb2436eab#diff-9d6269d591a48b7a9682ff8f0af422f5R602

**Comment by mfb** [comment]
I think it'd be good to enable caching either in this or another PR.

Not sure what else uses HTMLPurifier. I guess the "IDS" system does but need to figure out what input would use it.

**Comment by seamuslee001** [comment]
thanks @mfb i have updated this PR to update the class loader and config paths there will be some other changes needed when we go to rip out the purifier in the packages but i think i got that covered

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 related fail

**Comment by mfb** [comment]
I would suggest updating the test assertion, as adding noopener+noreferrer is a security improvement.

**Comment by seamuslee001** [comment]
Yeh will do but the test does prove there is slightly different output between the versions of htmlpurifer @mfb @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
@seamuslee001 it's stale - I didn't quite know what to make of the test thing but assume it's ok

**Comment by mfb** [comment]
I'm not sure we actually need the class paths, if we could just rely on composer autoload, but no harm done updating them as long as everything is working.

**Pull request merged**
