### PR TITLE
dev/financial#56 Fix inappropriate sales tax row addition

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
https://lab.civicrm.org/dev/financial/issues/56

Before
----------------------------------------
Before

After
----------------------------------------
After

### CODE REVIEW

**Review by MegaphoneJon — APPROVED** [review]
I tested this and it fixes the problem.  Thanks Pradeep!

**Comment by MegaphoneJon** [comment]
fail seems unrelated.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
Merging based on @MegaphoneJon review, test presence & quick check of the code

**Pull request merged**
