### PR TITLE
CRM-19438, fixed for memcached issue, since it returns string rather …

### PR DESCRIPTION
**Pull request by pradpnayak**
…NULL

---
- CRM-19438: Entries in financial item not recorded properly when created via offline Membership form
  https://issues.civicrm.org/jira/browse/CRM-19438

### CODE REVIEW

**Comment by pradpnayak** [comment]
Memcached/Memcache returns empty string if not found in cache while other caching tool returns NULL. Therefore $values for memcache will be 

 Array
(
  [0] =>
)

**Review by colemanw — APPROVED** [review]
This change looks right to me.

**Comment by monishdeb** [comment]
@pradpnayak @colemanw is this PR ready for merge if already tested ?

**Comment by JoeMurray** [comment]
@eileenmcnaughton this bug had caused a lot of data corruption on one client's site. I think it should be considered a critical bug and be prioritized for backporting to 4.6. Who else should be involved in that?

**Comment by JoeMurray** [comment]
I'm not sure how to handle the data repair query. It should be run on machines for the period during which memcached was enabled.

Here is a start on an 'upgrade' query. On quick scan it appears to be designed to work for contributions with just a single line item, which is what our client has. 

UPDATE 
 civicrm_entity_financial_trxn ceft 
INNER JOIN civicrm_financial_item cfi ON cfi.id = ceft.entity_id  AND ceft.entity_table = 'civicrm_financial_item'
INNER JOIN civicrm_line_item cli ON cli.id = cfi.entity_id  AND cfi.entity_table = 'civicrm_line_item'
INNER JOIN 
(SELECT 
cft.id financial_trxn_id,
cft.total_amount trxn_amount,
cfi.id item_id,
cli.id  line_id,
ceft.id ceft_id
 FROM civicrm_financial_trxn cft 
INNER JOIN civicrm_entity_financial_trxn ceft ON ceft.financial_trxn_id = cft.id
INNER JOIN civicrm_financial_item cfi ON cfi.id = ceft.entity_id  AND ceft.entity_table = 'civicrm_financial_item'
INNER JOIN civicrm_line_item cli ON cli.id = cfi.entity_id  AND cfi.entity_table = 'civicrm_line_item'
INNER JOIN civicrm_entity_financial_trxn ceft1 ON ceft1.financial_trxn_id = cft.id  AND ceft1.entity_table = 'civicrm_contribution'
INNER JOIN civicrm_contribution cc ON cc.id = ceft1.entity_id
GROUP BY cft.id
HAVING sum(cfi.amount) <> cft.total_amount ) temp ON temp.item_id= cfi.id AND ceft.id=temp.ceft_id AND temp.line_id = cli.id

SET 
cli.line_total = trxn_amount,
ceft.amount = trxn_amount,
cfi.amount = trxn_amount;

**Pull request merged**
