### PR TITLE
Painstaking unravelling of function

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Unwravels `getParams` function in import

Before
----------------------------------------
I couldn't follow the code

After
----------------------------------------
50 commits later I can

Technical Details
----------------------------------------
The comment points to the point of this - I want to add in option_value transformation at this very early point & do it for both the main contact & related contacts - not in this PR but addable now

Comments
----------------------------------------
There is a lot of test cover on this code

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton is this covered by tests?

**Comment by eileenmcnaughton** [comment]
@colemanw yep - well covered - in both MapFieldTest & Parser_ContactTest

**Comment by colemanw** [comment]
Ok. The refactoring looks sensible.

**Comment by eileenmcnaughton** [comment]
what about the original code ... did that look sensible?

**Comment by eileenmcnaughton** [comment]
yay

**Pull request merged**
