### PR TITLE
dev/core#1422 Ensure that the form values are correctly passed onto t…

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Port of https://github.com/civicrm/civicrm-core/pull/15962

@seamuslee001 I don't think this should trigger a point release but let's merge it & include it if there is one

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 this is the patch you think @davejenx should try?

**Comment by seamuslee001** [comment]
no its https://github.com/civicrm/civicrm-core/pull/15977

**Comment by eileenmcnaughton** [comment]
@seamuslee001 but this is a 5.19 port of that....

**Comment by seamuslee001** [comment]
@eileenmcnaughton no it isn't this is for the Event badge search fix (which i agree should be ported to 5.19 anyway but that is different)

**Comment by eileenmcnaughton** [comment]
@seamuslee001 ah OK - it probably makes sense to port the other too

**Comment by seamuslee001** [comment]
@eileenmcnaughton added a port for #15977 here https://github.com/civicrm/civicrm-core/pull/15991

**Pull request merged**
