### PR TITLE
Clarify definition of amount field in civicrm_contribution_recur table.

### PR DESCRIPTION
**Pull request by KarinG**
Overview
----------------------------------------
There was some ambiguity as to whether the amount field in civicrm_contribution_recur table represented the sales tax inclusive or exclusive amount. I checked in with @eileenmcnaughton and people on: https://lab.civicrm.org/dev/financial/-/issues/123 

**I did some research:**
- Membership Type -> auto-renew required (Fee: $1) + Financial Type has Sales Tax associated with it (5%)
- Submit Credit Card for Membership -> (Amount is calculated correctly: $1.05)
- Observe -> **Amount $1.05 (not $1)** is stored in the civicrm_contribution_recur table, so that's the tax inclusive amount

image

**PR to remove ambiguity:** amount to be collected - is clearly total amount - and avoids making this comment unnecessarily complex by adding sales tax wording into it. 

**Before**
----------------------------------------
show FULL columns from civicrm_contribution_recur;

`| amount                       | decimal(20,2)    | NULL            | NO   |     | NULL    |                | select,insert,update,references | Amount to be contributed or charged each recurrence.    `                              

**After**
----------------------------------------
`| amount                       | decimal(20,2)    | NULL            | YES  |     | NULL    |                | select,insert,update,references | Amount to be collected by payment processor each recurrence    `
                       
**Next**
----------------------------------------
After establishing /clarifying that amount is indeed amount to be collected -> I'll work on ensuring that repeattransaction API [recommended for payment processors creating subsequent instalments] works properly when it comes to Sales Taxes.

Technical
----------------------------------------
Looks like I can tag this onto `CRM/Upgrade/Incremental/sql/5.26.alpha1.mysql.tpl` - if not please let me know.

**Comment**
----------------------------------------
I will also be updating the Documentation.

### CODE REVIEW

**Comment by adixon** [comment]
I like the inclusion of the 'by payment processor'. I'm not convinced about the use of the word 'collected', that's not a word that we've been using or has a universal meaning. 
Does: "Amount to be transacted by payment processor on each recurrence" work?
It's terrible English but fairly unambiguous ...

**Comment by seamuslee001** [comment]
@KarinG I'm not going to try to wade in on the english here but once it is settled can you please change this line https://github.com/civicrm/civicrm-core/blob/master/xml/schema/Contribute/ContributionRecur.xml#L44 and then run `./bin/setup.sh -g`  and commit the changes which should change the DAO file as well which should ensure that any new installs get the correct comment

**Comment by eileenmcnaughton** [comment]
I think I'd go further & have 'Amount to be collected (including any sales tax)....'

**Comment by mattwire** [comment]
> I think I'd go further & have 'Amount to be collected (including any sales tax)....'

@KarinG Thanks for tackling this one :-) I agree we should be explicit and change the text to something like @eileenmcnaughton suggested so it explicitly mentions sales tax.

**Comment by KarinG** [comment]
Uh - something went wrong updating my buildkit... I did not try to change 135 files... I promise :-)

**Comment by KarinG** [comment]
@seamuslee001 - and I must be doing something wrong here too:

I ran - setup.sh -> but I don't see any edits ( other than to: b/CRM/Upgrade/Incremental/sql/5.26.alpha1.mysql.tpl )
```
karins-MBP:civicrm sysadmin$ ./bin/setup.sh -g
+ '[' -n '' ']'
+ '[' -n 1 -a -d /Applications/MAMP/htdocs/buildkit/build/dmaster/web/sites/all/modules/civicrm/./bin/../xml ']'
+ pushd /Applications/MAMP/htdocs/buildkit/build/dmaster/web/sites/all/modules/civicrm/./bin/../xml
/Applications/MAMP/htdocs/buildkit/build/dmaster/web/sites/all/modules/civicrm/xml /Applications/MAMP/htdocs/buildkit/build/dmaster/web/sites/all/modules/civicrm
+ '[' -z 3306 ']'
+ PHP_MYSQL_HOSTPORT=127.0.0.1:3306
+ php -d mysql.default_host=127.0.0.1:3306 -d mysql.default_user=dmasterciv_xyswi -d mysql.default_password=LieuIJElq01m0TUd GenCode.php schema/Schema.xml '' Drupal

civicrm_domain.version := 5.26.alpha1

Parsing schema description schema/Schema.xml
Extracting database information
Extracting table information
Generating civicrm.config.php
Generating table list
Generating sql file
Generating sql drop tables file
Generating data files for en_US
Generating data files for af_ZA
Generating data files for ar_EG
Generating data files for bg_BG
Generating data files for ca_ES
Generating data files for cs_CZ
Generating data files for da_DK
Generating data files for de_CH
Generating data files for de_DE
Generating data files for el_GR
Generating data files for en_AU
Generating data files for en_CA
Generating data files for en_GB
Generating data files for es_ES
Generating data files for es_MX
Generating data files for et_EE
Generating data files for fa_IR
Generating data files for fi_FI
Generating data files for fr_CA
Generating data files for fr_FR
Generating data files for he_IL
Generating data files for hi_IN
Generating data files for hu_HU
Generating data files for hy_AM
Generating data files for id_ID
Generating data files for it_IT
Generating data files for ja_JP
Generating data files for km_KH
Generating data files for ko_KR
Generating data files for lt_LT
Generating data files for lv_LV
Generating data files for mk_MK
Generating data files for nb_NO
Generating data files for nl_BE
Generating data files for nl_NL
Generating data files for pl_PL
Generating data files for pt_BR
Generating data files for pt_PT
Generating data files for ro_RO
Generating data files for ru_RU
Generating data files for sk_SK
Generating data files for sl_SI
Generating data files for sq_AL
Generating data files for sr_RS
Generating data files for sv_SE
Generating data files for tr_TR
Generating data files for uk_UA
Generating data files for vi_VN
Generating data files for zh_CN
Generating data files for zh_TW
Generating navigation file
Generating sample file
Generating CRM_Core_I18n_SchemaStructure...
+ popd
/Applications/MAMP/htdocs/buildkit/build/dmaster/web/sites/all/modules/civicrm
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ echo

+ echo 'NOTE: Logout from your CMS to avoid session conflicts.'
NOTE: Logout from your CMS to avoid session conflicts.

karins-MBP:civicrm sysadmin$ git status
On branch master
Your branch is ahead of 'origin/master' by 3 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   CRM/Upgrade/Incremental/sql/5.26.alpha1.mysql.tpl

```

**Comment by KarinG** [comment]
Sorry folks - I messed up my own repo so badly - I just had to hit delete... 

I've got a fresh one -> with only 1 commit -> https://github.com/civicrm/civicrm-core/compare/master...KarinG:master - but can't hook that back up here can I?

**Pull request closed without merging**
