### PR TITLE
CRM-20860 Add in ability to create field type of password from metadata

### PR DESCRIPTION
**Pull request by seamuslee001**
* [CRM-20860](https://issues.civicrm.org/jira/browse/CRM-20860)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
THis feels like an improvement to me @xurizaemon thoughts

**Comment by seamuslee001** [comment]
I would add that without metadata we already use password fields here https://github.com/civicrm/civicrm-core/blob/master/CRM/Admin/Form/Setting/Smtp.php#L61 to me it makes sense to allow it to be dynamically created based on metadata as well and the rest is just styling to match it to Textboxes

**Comment by monishdeb** [comment]
👍 for this PR. We can utilise this new field type for adding Payment Processor credentials, ext that invloves third party setting credentials etc.

**Comment by eileenmcnaughton** [comment]
I'm going to merge this - it makes not change on it's own so there is nothing to actually test & feels like a fairly well trodden path (ie. core quickform functionality)

**Pull request merged**
