### PR TITLE
[REF] minor tidy ups on very nasty function

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Changes
- switches to using cached function rather than deprecated function to get MembershipTypeDetails (covered by existing tests)
- remove unnecessary date formatting

Before
----------------------------------------
Nasty

After
----------------------------------------
Still nasty if I'm honest

Technical Details
----------------------------------------
It used to be necessary to ISO format code before DAO->save. However, along the line wee fixed it lower
down & no longer need this smattered all over the code. Test proves it's OK (actually they noisily pointed out that the code had to stop unpacking the separated string as it was now getting that done for it :-)

Comments
----------------------------------------

### CODE REVIEW

**Comment by yashodha** [comment]
@eileenmcnaughton You might want to squash your commits.

**Comment by eileenmcnaughton** [comment]
@yashodha I wasn't going to on this one because the 3 commits do different things - but I could squash the first 2 I guess since that's just the test plus the fix that follows

**Comment by eileenmcnaughton** [comment]
Ok test squashed into the commit it tests

**Comment by colemanw** [comment]
Looks good.

**Pull request merged**
