### PR TITLE
CRM-17983

### PR DESCRIPTION
**Pull request by mollux**
- [CRM-17983](https://issues.civicrm.org/jira/browse/CRM-17983)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@totten so this still needs merging...

**Comment by totten** [comment]
@eileenmcnaughton , yup. It sounds like Dave J was pretty thorough in testing. :) I'm going to quickly spot-check a couple items (just because this is a last-minute merge).

**Comment by totten** [comment]
In my spot-check, found a problem with custom-data (which was on Dave's list of tests). I'll break out a spreadsheet with the various changes so that we can keep track of which have been tested.

**Comment by totten** [comment]
Reviewing the patch and Dave's notes, prepared https://docs.google.com/spreadsheets/d/1p7FGP74xWUZ4mTQkYGCwjd7vgXAR3k5ZSekX53AvX3k/edit?usp=sharing . There were a handful of other pages to try out (e.g. `civicrm/ajax/flipDupePairs` and `civicrm/ajax/grouplist`); all were fine except the custom-data (`civicrm/ajax/multirecordfieldlist`).

Steps:
 1. Create a new multi-value custom data group
 2. Add a new field with label "Good or bad"
 3. Go to a contact and view the new tab

Produces error:

```
May 03 15:56:15  [info] $Fatal Error Details = Array
(
    [message] => One of parameters  (value: Good or bad?) is not of the type MysqlColumnName
    [code] => 
)


May 03 15:56:15  [info] $backTrace = #0 /Users/totten/buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Core/Error.php(371): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /Users/totten/buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Utils/Type.php(424): CRM_Core_Error::fatal("One of parameters  (value: Good or bad?) is not of the type MysqlColumnName")
#2 /Users/totten/buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Core/Page/AJAX.php(225): CRM_Utils_Type::validate("Good or bad?", "MysqlColumnName")
#3 /Users/totten/buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Custom/Page/AJAX.php(115): CRM_Core_Page_AJAX::defaultSortAndPagerParams(0, 10)
#4 [internal function](): CRM_Custom_Page_AJAX::getMultiRecordFieldList()
#5 /Users/totten/buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Core/Invoke.php(278): call_user_func((Array:2))
#6 /Users/totten/buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:12))
#7 /Users/totten/buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3))
#8 /Users/totten/buildkit/build/dmaster/sites/all/modules/civicrm/drupal/civicrm.module(454): CRM_Core_Invoke::invoke((Array:3))
#9 [internal function](): civicrm_invoke("ajax", "multirecordfieldlist")
#10 /Users/totten/buildkit/build/dmaster/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#11 /Users/totten/buildkit/build/dmaster/index.php(21): menu_execute_active_handler()
#12 {main}
```

**Comment by mollux** [comment]
@totten I found the issue, and added a fix to this PR

**Comment by totten** [comment]
Great. Confirmed that fixes it. :)

**Pull request merged**
