### PR TITLE
regen after 28800

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
regen after #28800

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@demeritcowboy will this make is harder to up-merge once https://github.com/civicrm/civicrm-core/pull/28895 is done  + the regen for that - or are we gonna have to deal with pain either way?

**Comment by demeritcowboy** [comment]
Right. I wasn't sure about the upgrade script part. That 5.69.1 version seems inevitable but doesn't exist yet, so how to handle?

**Comment by eileenmcnaughton** [comment]
@demeritcowboy ie how do we deal with the 5.69 version failing until some release stuff is done? I think we leave that for @totten when he is dealing with the release & focus on merging the other parts 5.70, the other 5.69 part & sorting out the up-merge.

**Comment by demeritcowboy** [comment]
Thinking... but will try not to think too hard...
In the meantime will close this.

**Pull request closed without merging**
