### PR TITLE
CRM-19948: Store Attachment uploader information

### PR DESCRIPTION
**Pull request by davialexandre**
This PR changes the Attachment API in order for it to save the current logged in contact ID as the uploader of the file.

The ID is stored in the `created_id` field, which was added to the File entity. On `Attachment.create`, only when adding a new file (i.e. File.id is empty), we set the `created_id` as logged in contact ID.

The `created_id` field is not required and, on delete, it's set to null. This was done because:
- There might be existent files on the database
- A few other places use the File BAO directly and we don't want/need to update all them right now
- When deleting a contact, we still might want to keep the file.

Note: I couldn't find a way to test the upgrader, so I'm not really sure if it's working. I tried to play with https://github.com/civicrm/civicrm-upgrade-test but didn't have any success

---

 * [CRM-19948: Store the Attachment uploader information](https://issues.civicrm.org/jira/browse/CRM-19948)

### CODE REVIEW

**Comment by davialexandre** [comment]
Ok, so I managed to run civicrm-upgrade-test. I ran `civibuild upgrade-test drupal-demo *.sql.bz2` and the output was this:

```
Summary
4.0.0-setupsh.sql.bz2   ERROR
4.0.8-setupsh.sql.bz2   ERROR
4.1.0-setupsh.sql.bz2   ERROR
4.1.6-setupsh.sql.bz2   ERROR
4.2.0-setupsh.sql.bz2   OK
4.2.16-setupsh.sql.bz2  OK
4.2.9-setupsh.sql.bz2   OK
4.3.0-setupsh.sql.bz2   OK
4.4.0-setupsh.sql.bz2   OK
4.4.5-setupsh.sql.bz2   OK
4.5.0-setupsh.sql.bz2   OK
4.5.5-setupsh.sql.bz2   OK
4.6.0-setupsh.sql.bz2   OK
4.6.11-setupsh.sql.bz2  OK
4.7.0-setupsh.sql.bz2   OK
```

I assume I can ignore the errors on 4.0 and 4.1 and, given that everything is ok on 4.7.0, it means the upgrade works?

**Comment by davialexandre** [comment]
hey @totten @colemanw, does this look ok to you? What about the output from the upgrade-test, does it mean the upgrade is ok?

**Comment by guanhuan** [comment]
Should be fine if 4.0 and 4.1 failed since they are not supported any more? @totten

**Comment by monishdeb** [comment]
@davialexandre  can you please rebase your PR as it has gone stale. Here are the steps to do so:
```
$ git pull --rebase upstream master // if upstream is pointed to civicrm/civicrm-core repo
// manually resolve conflicts >> git add the file 
$ git rebase --continue 
$ git push -f origin CRM-19948-store-attachment-uploader-information 
```

Also please move the upgrade task to ```upgrade_4_7_32()```

**Comment by monishdeb** [comment]
Closing in favor of https://github.com/civicrm/civicrm-core/pull/11739

**Comment by davialexandre** [comment]
hey @monishdeb, sorry I didn't have the time to rebase and update it. Thanks a lot for the review and for creating a new PR with the necessary updates. Please let me know if you need help with anything

**Pull request closed without merging**
