### PR TITLE
CRM-17476 - Fixes result structure of api.customvalue.get

### PR DESCRIPTION
**Pull request by mollux**
[CRM-17476](https://issues.civicrm.org/jira/browse/CRM-17476)

### CODE REVIEW

**Comment by mollux** [comment]
Jenkins test this please

**Comment by mollux** [comment]
I think Jenkins didn't pick up this patch, as I don't see it in the queue.

**Comment by davecivicrm** [comment]
ok to test

**Comment by davecivicrm** [comment]
add to whitelist

**Pull request merged**
