### PR TITLE
CRM-16842 add EntityBatch api

### PR DESCRIPTION
**Pull request by mallezie**
https://issues.civicrm.org/jira/browse/CRM-16842

### CODE REVIEW

**Comment by kurund** [comment]
@mallezie it might be good to document this new API on http://wiki.civicrm.org/confluence/display/CRMDOC/API+changes

**Comment by mallezie** [comment]
@kurund i'll document it when i'm able to resolve the test-failures, and get this merged? Not sure however when i'm able to get to those. 

We'll probably need to add docs for the other API-additions as wel? 
https://issues.civicrm.org/jira/browse/CRM-16517 (merged)
https://issues.civicrm.org/jira/browse/CRM-16769 (in progress)
https://issues.civicrm.org/jira/browse/CRM-16701 (in progress)

The empty BAO file is necessary to make the API-file similar to the other api file's. The wrapper api-function always calls the BAO 
´´´function civicrm_api3_entity_batch_create($params) {
  return _civicrm_api3_basic_create(_civicrm_api3_get_BAO(__FUNCTION__), $params);
}´´´
This is used in 'all' api files, so to keep this consistent i added the empty BAO wrapper.

**Comment by kurund** [comment]
@mallezie thanks for the update.

**Comment by kurund** [comment]
jenkins, test this please

**Comment by johanv** [comment]
I updated the changelog on http://wiki.civicrm.org/confluence/display/CRMDOC/API+changes.

**Comment by kurund** [comment]
jenkins, test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
Closing in favour of https://github.com/civicrm/civicrm-core/pull/6995

**Pull request closed without merging**
