### PR TITLE
Convert Event Participant Registration Date to datepicker

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Convert form to use datepicker:
* Register Participant - Registration Date

Partial from #12973

Before
----------------------------------------
Using old jcalendar.

After
----------------------------------------
Using "new" datepicker.

### CODE REVIEW

**Comment by colemanw** [comment]
I can confirm this works in the UI, but `CRM_Event_Form_ParticipantTest` tests will need to be updated as this is causing failures.

**Comment by mattwire** [comment]
test this please

**Comment by seamuslee001** [comment]
@mattwire should this still be WIP?

**Comment by eileenmcnaughton** [comment]
49 instances of jcalendar left...

**Comment by seamuslee001** [comment]
Removed WIP as it seems Matt has fixed the problem with the tests, Based on Coleman's review and the tag i'm going to merge this

**Comment by mattwire** [comment]
@seamuslee001 Thanks, think I was waiting for the tests to pass, but seeing as they did :+1:

**Pull request merged**
