### PR TITLE
[REF] APIv4 - Rename trait 'SoftDelete' to 'SoftDeleteEntity'

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Simple file rename for consistency with other traits

Before
----------------------------------------
APIv4 has some "ability" traits, named:
- ManagedEntity
- SortableEntity
- ReadOnlyEntity
- SoftDelete

After
----------------------------------------
- SoftDeleteEntity

### CODE REVIEW

**Comment by colemanw** [comment]
@braders - this would be a good one for you to review

**Comment by braders** [comment]
@colemanw Honestly I'm not that familiar with the API4 code, but this looks sensible enough.

The only concern that springs to mind is that extensions could be using this trait - you'll know better than me if that's a legitimate concern or not.

**Comment by colemanw** [comment]
In general that's a smart thing to consider @braders. In this particular case I would say very unlikely because the trait is new, internal, and not documented anywhere. However I vaguely recall @monishdeb working on some extension code where I suggested this trait might be useful to him, so I'll just add merge-ready here and give him a chance to double-check that.

**Comment by demeritcowboy** [comment]
Github still thinks jenkins is queued for this but it appears to have passed tests and is pretty straightforward.

**Pull request merged**
