### PR TITLE
dev/mail#23: Bounce processing doesn't catch pattern 'user doesn't exist'

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Some email providers throw the bounce pattern "user doesn't exist", which is not found, and therefore results in bounce_type "syntax". However, this bounce pattern should result in immediately put the email addresses to on-hold.

Before
----------------------------------------
Does not detect bounce pattern 'user doesn't exist ' as invalid bounce type.

After
----------------------------------------
Detect bounce pattern 'user doesn't exist ' as invalid bounce type.

Comments
----------------------------------------
ping @lcdservices @eileenmcnaughton @seamuslee001

### CODE REVIEW

**Comment by seamuslee001** [comment]
@monishdeb you need to escape `\` the `'` in doesn't

**Comment by monishdeb** [comment]
Thanks @seamuslee001 for pointing that out. 

(how could I missed that *sigh*)

**Comment by seamuslee001** [comment]
I'm going to add merge on pass on this given i have tested the regex using a tester. Jenkins will tell us if the upgrade goes wrong at all and the change looks correct to me

**Comment by monishdeb** [comment]
Thanks @seamuslee001 

FYI here's how I tested my change earlier:
```php
    $p = 'user doesn\'t exist';
    CRM_Core_Error::debug_var('a', CRM_Mailing_BAO_BouncePattern::match($p));
```
which prints
```$p = Array(
'bounce_type_id' => 6,
'bouce_reason' => 'user doesn\'t exist',
)
```

Earlier w/o patch I was getting:
```
```$p = Array(
'bounce_type_id' => NULL,
'bouce_reason' => 'user doesn\'t exist',
)
```

**Comment by seamuslee001** [comment]
Merging as per the tag

**Pull request merged**
