### PR TITLE
Rename the Find and Merge Duplicates Contacts menu item

### PR DESCRIPTION
**Pull request by mlutfy**
Overview
----------------------------------------

CiviCRM tends to be very verbose on things and users often find this to be overwhelming and feel silly.

Before
----------------------------------------

image

After
----------------------------------------

image

Comments
----------------------------------------

~~I hesitated to further shorten to "Merge Duplicates" (without the "Contacts" at the end), because I'm not sure what kind of other merging one would do, but I figured that when reading that gigantic menu, one might forget that they are in the "Contacts" menu.~~

Edit: after discussion: I updated for "Manage Duplicates"

### CODE REVIEW

**Comment by mlutfy** [comment]
Suggestion from @petednz 

> Contact Matching, De-duplication and Merging

.. as something that best describes the process of what we call deduping. I would prefer to keep the menu item itself short, but it could make sense for the page title.

**Comment by mlutfy** [comment]
Looking elsewhere:

- Salesforce: Manage Duplicate Records
- Dynamics: Duplicate Detection Rules
- SuiteCRM: Duplicate Check

I think I prefer "Manage Duplicates" :thinking:

**Comment by mlutfy** [comment]
I updated the PR to use "Manage Duplicates".

I also notice two "thumbs-up", in case anyone wants to merge-on-pass ;)

**Comment by eileenmcnaughton** [comment]
@mlutfy you have been sabotaged

**Comment by mlutfy** [comment]
Fixed :musical_note:

**Pull request merged**
