### PR TITLE
CRM-16195 use option values to store relative date filter config

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
- [CRM-16195: Give users the ability to create relative date filters for reports and searches](https://issues.civicrm.org/jira/browse/CRM-16195)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
unrelated fail (recent regression - how do we track these down)

Appears to be stale now - but that will need resolving immediately prior to merge as it will keep going stale as it touches sql files that always go stale :-(

**Comment by eileenmcnaughton** [comment]
@PalanteJon my experience with this part (the date transformation to option value) was that it worked fine & if you have no reservations I am happy to re-fix the conflict & merge this. As mentioned on the other PR I DID tidy the form work into a single commit but I have done no testing on it - but I can create a PR for that for testing (or you can) once this is merged

**Comment by PalanteJon** [comment]
@eileenmcnaughton Thank you!  Sorry for not doing more of this work myself, I just can't prioritize this right now.  It's fine to have a PR just to move option values into the db.  Also, didn't @totten do work in the 4.7 cycle so we could break update SQL into separate files to avoid merge conflicts?

**Comment by davecivicrm** [comment]
@eileenmcnaughton I thought we had decided to push this to 4.8?

**Comment by eileenmcnaughton** [comment]
Hi Dave,

I don't know - but I was working on relative date filters & thought the patch had mostly stalled because of time so I thought I could break this part out of it - which works really well - even if it isn't front end configurable without the form work which is where I think it fell down

**Comment by davecivicrm** [comment]
@eileenmcnaughton I'm a bit concerned about going down this road towards user-configurability without having the 'configuring' part thoroughly worked out. If we discover that there's a better place to store this given the settled on approach, then we'd have a bit of a mess undoing this. 

What are the advantages of pushing this into 4.7 w/o the configuration work?

**Comment by eileenmcnaughton** [comment]
The main advantage of this as I see it is that there is a lot of demand for re-ordering the options at the moment. Prior to 4.6 the most commonly used filters were at the top. From 4.6 the most used filters -  like 'This Month' became things that needed to be scrolled to. This doesn't allow individual users to re-order but it makes it easy for developers & consultants to meet their requests

It did occur to me it might change again - but the version in this patch is quite structured so it could be transformed again in a logical way.

**Comment by davecivicrm** [comment]
... and now I'm wondering who / how / why the order was changed. Looking at the current list, it seems like whether we merge this or not, the default order should be thought through (and I agree that 'This ...' selections should be first or near the top).

**Comment by eileenmcnaughton** [comment]
Yeah - Joanne was happy to come up with a proposed order (as an end user) - I expect she will want it patched in the 4.6 they upgrade to (whether a core patch or a Fuzion patch).

I think the change was a data restructure (from enum) or something like that

**Comment by PalanteJon** [comment]
The various relative filters are currently hard-coded, this patch moves them to the OptionValue table, so we get enabling/disabling/reordering them "for free".  There's precedent for other OptionValue data that can be enabled/disabled/reordered but the values shouldn't be edited; I don't think this is different from, say, example.org/civicrm/admin/options?gid=24&reset=1.

While I agree that it's possible they'll be moved out of OptionValue, I very much doubt it.  While the code isn't written, I have a very good sense of what it'll look like, and I don't see any reason to continue using OptionValue for this purpose.

**Comment by davecivicrm** [comment]
@eileenmcnaughton ok if you're up for making it happen / merging (and following up if unintended consequences) - then go for it. However, can you get an improved order from Joanne so the default option value order better reflects real use cases.

**Comment by eileenmcnaughton** [comment]
Yeah - @joannechester said she was happy to do QA / submit a patch to fix up the order once this is merged.

Since it needs to be merged in a time-sensitive fashion - ie & rebase & merge before it goes stale, we thought that the re-ordering would  be better done after it's merged (as long as it happens before alpha is cut which seems fine)

**Comment by davecivicrm** [comment]
@eileenmcnaughton go for it!

**Comment by joannechester** [comment]
This PR inserts the old filter names rather than the new filter names into the db names and also has doesn't include the last 60 days, next 60 days and next 90 days filters.

I am happy to make the changes/additions as it was my PRs that made the changes, but I am not sure how to do that.  Do fork eileen's :CRM-16195-rebase and submit a PR to that?

**Comment by eileenmcnaughton** [comment]
@joannechester I've merged it so you can alter & do a PR against master. I think any other process would bring us back to stale change needs rebasing

**Comment by eileenmcnaughton** [comment]
@joannechester & of course we are looking to you to review the weights & come up with the best variation on that :-)

**Comment by joannechester** [comment]
@davecivicrm I have reinstated the new labels for the filters  and re-ordered them to make more sense, See https://github.com/civicrm/civicrm-core/pull/6788.
I am happy with the order for the first 30 and the last 4 filters. No order will be perfect for everyone and anyway, now people can re-order to suit their needs.

**Pull request merged**
