### PR TITLE
CRM-17036 - Getting started 4.6

### PR DESCRIPTION
**Pull request by sunilpawar**
New PR for 4.6

---
- [CRM-17036: Getting Started dashlet widget](https://issues.civicrm.org/jira/browse/CRM-17036)

### CODE REVIEW

**Comment by colemanw** [comment]
@davecivicrm @totten @kurund do we want to accept this backport? It is a sizeable patch but nice functionality.
Alternative would be to wait & leave it in the LTS team's hands when they take over & this dashlet has gotten some real world testing in 4.7.

**Comment by davecivicrm** [comment]
@colemanw I'm open to accepting it BUT currently the 4.7 (master) version is broken - both on my local and on the dmaster demo (widget header is there but doesn't populate). I also noticed several of the sample report widgets seem to be broken :-(
screen shot 2015-09-29 at 6 14 02 pm

**Comment by colemanw** [comment]
Sounds like it's going to wait, at least until the version in master stabilizes.

**Comment by davecivicrm** [comment]
@colemanw I’m concerned that the Getting Started Widget ‘regression’ may be unrelated to Sunil’s code since it WAS working fine for several weeks after their PR was merged. Not sure how to debug it - do you know how?

**Comment by totten** [comment]
The regression related to the declaration of `gettingStartedUrl`. #6861 fixes this by adding metadata for the setting.

For 4.6, declaring the setting metadata is recommended but not strictly required.

**Pull request closed without merging**
