### PR TITLE
CRM-20510: Petition signature doesn't show as an activity type for scheduled reminder

### PR DESCRIPTION
**Pull request by monishdeb**
* [CRM-20510: Petition signature doesn't show as an activity type for scheduled reminder](https://issues.civicrm.org/jira/browse/CRM-20510)

### CODE REVIEW

**Comment by monishdeb** [comment]
```Petition Signature``` activity type is now available in SR form
image

**Comment by pradpnayak** [comment]
QA'd
Petition and other Activity type for Campaign are visible now in drop down list.

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by seamuslee001** [comment]
@monishdeb can you fix the style issue? whitespace end of line 289

**Comment by monishdeb** [comment]
Thanks @seamuslee001 , updated the PR

**Comment by eileenmcnaughton** [comment]
Merging. @pradpnayak has confirmed this fixes the issue & it makes sense and is a safe patch IMHO

I think that using buildOptions would have had the same effect and in general we are trying to move things that way, but not going to hold this up on that.

**Pull request merged**
