### PR TITLE
Add Colombia missing state

### PR DESCRIPTION
**Pull request by joapta**
There is a missing state for Colombia added according to: https://www.iso.org/obp/ui/#iso:code:3166:CO

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins ok to test

**Comment by demeritcowboy** [comment]
Oops this is conflicted now. Can you rebase?

**Comment by seamuslee001** [comment]
@joapta are you able to fix the conflicts here?

**Comment by demeritcowboy** [comment]
Hi @joapta you need to rebase and squash the commits because the first commit is still a conflict. See https://docs.civicrm.org/dev/en/latest/tools/git/#rebasing

```
Applying: Add Colombia missing state                                                     
  Patch failed at 0001 Add Colombia missing state                                          
  When you have resolved this problem, run "git am --continue".                            
  If you prefer to skip this patch, run "git am --skip" instead.                           
  To restore the original branch and stop patching, run "git am --abort".                  
  [[ STDERR ]]                                                                             
  error: patch failed: CRM/Upgrade/Incremental/sql/5.45.alpha1.mysql.tpl:1                 
  error: CRM/Upgrade/Incremental/sql/5.45.alpha1.mysql.tpl: patch does not apply           
  error: patch failed: sql/civicrm_generated.mysql:11878                                   
  error: sql/civicrm_generated.mysql: patch does not apply                                 
  error: patch failed: xml/templates/civicrm_state_province.tpl:4142                       
  error: xml/templates/civicrm_state_province.tpl: patch does not apply                    
  hint: Use 'git am --show-current-patch' to see the failed patch
```

**Comment by colemanw** [comment]
I've rebased it for you

**Pull request merged**
