### PR TITLE
ScheduledReminders - Add option list for limit_to column and fix type

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
This cleans up metadata for the `ActionSchedule.limit_to` field to make it easier to work with in the API.

Replaces #23487

Before
----------------------------------------
`limit_to` column is 'boolean' in the metadata and has no option list, but effectively it has 3 options: NULL, '0' and '1'.

After
----------------------------------------
Changed type to 'integer', added pseudoconstant, and renamed the '0' option to '2' so it isn't as easily confused with NULL.

### CODE REVIEW

**Comment by totten** [comment]
Yeah, `limit_to` is rough, and those named options are nicer.

Wondering about the impact on downstream. Did a quick grep on `universe` for `ActionSchedule`.  Some interesting ones:

* https://github.com/veda-consulting/uk.co.vedaconsulting.membershiprenewal/blob/master/CRM/Membershiprenewal/Utils.php#L230C32-L230C42 
* https://lab.civicrm.org/extensions/action-provider/-/blob/1.125/Civi/ActionProvider/Action/Event/CreateRecurringEvent.php?ref_type=tags#L101
* https://lab.civicrm.org/extensions/civicrm-advanced-events/-/blob/1.2.2/CRM/AdvancedEvents/Form/RecurringEntity.php?ref_type=tags#L79

Some observations:

* In `membershiprenewal`, it uses ActionSchedule in APIv3. But I *think* the value of `limit_to` is `1`, which aligns.
* In `action-provider` (cc @jaapjansma) and `civicrm-advanced-events` (cc @mattwire), they appear to have more range of values for `limit_to`. They are using the`CRM_Core_BAO_ActionSchedule::add()` instead of APIv3/APIv4. But even with APIv3/APIv4,  it would be the same issue, right?
* There were some other ext's that called `ActionSchedule` API (`messagetplreplyto`, `scheduledccrecipients`), but they were reads (`getsingle`, `getcount`) and I didn't see them filtering on `limit_to`.

I dunno... maybe it would work just to do a substitution during `add`/`create`/`update` (`limit_to=0` ==> `limit_to=2`)?

**Comment by colemanw** [comment]
Ok @totten how's this:

**Comment by totten** [comment]
That looks reasoable to me, @colemanw. I might wait a day or so to see if Jaap or Matt has any feedback (*since they would understand the context of those extensions better*).

**Comment by colemanw** [comment]
Thanks @totten, I've checked those extensions and they appear to be compatible with the changes. Gonna merge this before it gets more merge-conflicts.
FYI @mattwire & @jaapjansma

**Pull request merged**
