### PR TITLE
5.41 to master

### PR DESCRIPTION
**Pull request by eileenmcnaughton**

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton test fail is interesting here

**Comment by eileenmcnaughton** [comment]
@seamuslee001 yeah - we will need to merge + fix I think but that relates to the incorrect data issue - I'll look

**Comment by eileenmcnaughton** [comment]
I think the issue is that the test change to 5.41 https://github.com/eileenmcnaughton/civicrm-core/commit/11736aba4778a4beaf40a1ccaf93ebed9e01a9fd is inappropriate in master due to master using better test set up

**Comment by eileenmcnaughton** [comment]
alt upmerge #21246

**Pull request merged**
