### PR TITLE
APIv4 - Fix dumb typo breaking color lookup

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes a dumb typo which caused the afform type selector to look funny.

Before
----------------------------------------
image

After
----------------------------------------
image

### CODE REVIEW

**Comment by monishdeb** [comment]
Jenmkins test this please

**Comment by seamuslee001** [comment]
Jenmkins test this please

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by colemanw** [comment]
Jenkins test this please

**Pull request merged**
