### PR TITLE
[REF] Use CRM_Utils_Mail::send for sending emails for confirming unsu…

### PR DESCRIPTION
**Pull request by seamuslee001**
…bscribe resubscribe auto replies and subscribing

Overview
----------------------------------------
This refactors the mail sending code for handling auto replies, unsubscribe/resubscribe/subscription confirmations to using the CRM_Utils_Mail::send method

Before
----------------------------------------
Multiple separate invocations of pear mail without running through a hook

After
----------------------------------------
Single invocation of pear mail and passing through the alterParams and alter content hooks

ping @eileenmcnaughton @mattwire

### CODE REVIEW

**Comment by mattwire** [comment]
@seamuslee001 Test fails relate

**Comment by mattwire** [comment]
@seamuslee001 This is great! I had not realised that these messages bypassed hooks etc.

**Comment by seamuslee001** [comment]
@mattwire fixed the test failures now

**Comment by mattwire** [comment]
@seamuslee001 I tested this on a system with mail set to "redirect to database" and one that can actually send mail. Clicking an unsubscribe link (eg https://example.org/civicrm/mailing/unsubscribe?reset=1&jid=59&qid=29&h=64c9d6be9bd2bb44) works without the patch (an email is sent) but does NOT seem to work with the patch - no email is sent?

**Comment by seamuslee001** [comment]
@mattwire do you have any logs with errors?

**Comment by mattwire** [comment]
@seamuslee001 No logs - it is because you are passing `$params['to'`] and `CRM_Utils_Mail::send()` requires `$params['toEmail']`

**Comment by seamuslee001** [comment]
@mattwire that looks like to have been it, I have fixed that on all emails changed here and also expanded a mailing subscription test to check that the email is sent and that a sensible message id header is set as well

**Comment by eileenmcnaughton** [comment]
@seamuslee001 still failing :-(

**Comment by mlutfy** [comment]
In case the test result disappears from jenkins:

```
Stacktrace

api_v3_MailingGroupTest::testMailerProcess
Message-ID: <s .  not found in  MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="=_3fda462e069d3aa3be34e24d37f2c065"
From: "FIXME" <info@EXAMPLE.ORG>
To: <test@test.test>
Subject: Subscription Confirmation Request
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Return-Path: do-not-reply@setting.com
Reply-To: civicrm+c.4.2.acb3c277fc3b61a7@setting.com
Date: Sat, 13 Jun 2020 22:52:25 +0000
Message-ID: <civicrm+s.4.2.acb3c277fc3b61a7@setting.com>
```

**Comment by seamuslee001** [comment]
@eileenmcnaughton @mattwire @mlutfy I believe I have fixed the test now

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @mlutfy perhaps you could trade this for https://github.com/civicrm/civicrm-core/pull/17305

**Comment by demeritcowboy** [comment]
jenkins test this please

**Comment by demeritcowboy** [comment]
* General standards
    * [`r-explain`] __PASS__
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __PASSed for the parts tested__
      * Tested optout, unsubscribe, resubscribe.
      * Didn't test the others.
      * Tested with and without the generate Message-ID setting.
      * Didn't test hooks.
* Developer standards
    * [`r-tech`] __PASS__
    * [`r-code`] __PASS__
    * [`r-maint`] __PASS__
    * [`r-test`] __PASS__

**Comment by seamuslee001** [comment]
@eileenmcnaughton can you merge based on @demeritcowboy 's review

**Comment by eileenmcnaughton** [comment]
thanks @demeritcowboy - really appreciate all the review work you do and I have a tonne of confidence in your ability to ferrit out any gotchas

**Comment by mattwire** [comment]
Thanks @demeritcowboy @eileenmcnaughton Sorry @seamuslee001 this fell off my radar!

**Pull request merged**
