### PR TITLE
dev/core#2057 Reduce queries when calling activity.create

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This reduces queries in 2 ways
1) if the action is 'create' then existing activity contacts cannot exist, so do not try to delete them
2) if the action is 'edit' then look for & delete for all 3 record types at once.

There are still questions about how we can improve this further but it should remove up to 3 queries per
Activity.create call

Before
----------------------------------------
Up to 3 queries to determine if existing activity contacts exist - even for create, where it is not possible

After
----------------------------------------
Generally 0 queries on create & 1 on edit

Technical Details
----------------------------------------
@demeritcowboy I'm still pondering this a bit but I thought I'd get it open as I'd really like your eyes on it. I'm hoping to wrap up my query hunt in the first half of next week

Comments
----------------------------------------

Incorporates https://github.com/civicrm/civicrm-core/pull/18604 & can be rebased on that being merged

Testing
----------------------------------------
I augmented api_v3_ActivityTest::testActivityUpdate in the previous cleanup on this code in preparation for this

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@demeritcowboy just thinking about the best end-position for this - (beyond this PR) & I think the right approach might be 2 select queries for create ie

Approach 1
1) alter the delete query to be specific to which ones are NOT to be kept (ie record_type_id = 2 AND contact_id NOT IN (1,2,3) OR record_type_id = 3 AND contact_id NOT IN (3,5,6) )
2) the do a get for records IN those to be kept
3) filter the list to be saved & then save the ones that are needed

Approach 2
Alternately do 1 query & make decisions at the php layer - that works fine unless there are 10k activity contacts - but perhaps that is not an issue for activity.create to worry about because paths that deal with high load should manage that in their subsystem

In both approaches - we want to stop doing checks where params id is not set

**Comment by demeritcowboy** [comment]
This looks good. The single non-array parameter concept brought up some preexisting issues but something for another day.

**Comment by demeritcowboy** [comment]
Regarding the end-position, just a comment that it might not be worth uber-optimizing something like updates, e.g. mysql is smart enough not to actually do a query if the row being updated isn't changing.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy on " mysql is smart enough not to actually do a query if the row being updated isn't changing."

from what I can tell it does use a write-lock to do that though - so it increases deadlocks

Regarding this PR - does  the 'This looks good'  mean - "'I've taken a quick look & this makes sense at a high level" or "I believe this is mergeable"

**Comment by demeritcowboy** [comment]
It's mergeable and locally it passed the other test PR I put up.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 can you merge based on @demeritcowboy review?

**Comment by eileenmcnaughton** [comment]
thanks @seamuslee001

**Pull request merged**
