### PR TITLE
Importer - Increase size of queue batches

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

Addresses a simple, recent, and significant change in performance.

See https://github.com/civicrm/civicrm-core/pull/23669#discussion_r889758336

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
this is fine - I probably would have waited on @andyburnsco testing - but if you want to change in 5.52 that's OK.  I have been digging into a performance issue that impacts imports but it was unrelated to this

**Comment by totten** [comment]
Yeah, it would be nice to hear back how that went. But he did an emoji on my '100' suggestion...

Maybe we go for the safer `50` on both #24151 and 24152 then bump it up further when we hear back.

(*Assuming #24152 also passes in a few minutes,  I think we could just edit this one to `50` and go straight to merge.*)

**Comment by andyburnsco** [comment]
> this is fine - I probably would have waited on @andyburnsco testing - but if you want to change in 5.52 that's OK. I have been digging into a performance issue that impacts imports but it was unrelated to this

I tried 250 and 500 batchSize, the performance did not noticeably change, which is different than my experience with API CSV Importer (it made a difference there). 1 to 1.5s per contact import with several custom fields. However, I did hit concerning errors  and one that broke the db and civi requiring db restore, but could not find a debug and backtrace for it, will test again today. It was a vague `DB Error: constraint violation`. I was able to trigger the error importing 1 record by including county, removing county worked.

On an import that broke the db, it imported 1830 records consecutively (status column = IMPORTED) and then ERROR for the rest with vague `DB Error: unknown error`.  Not seeing any bad data that would have caused it.

  @eileenmcnaughton what issues or PR's are the performance related ones? We may be able to pitch in some funding. Background processing, multiple jobs / threads are all priorities for us.

**Comment by eileenmcnaughton** [comment]
@andyburnsco the biggest part of the performance issue in my testing turned out to be a cache miss - https://github.com/civicrm/civicrm-core/pull/24156 - we use a Redis cache and that seems to be slower than I might have expected - so I'm not sure if you will get the same improvement with that fix & some related fixes that we did (I'm also going to check in with our sysadmins on the speed of the Redis cache which seems to be a confounding factor).

**Comment by eileenmcnaughton** [comment]
Please create a gitlab with whatever you can find on the `DB Error: unknown error`

**Comment by andyburnsco** [comment]
Seems like this merge did not take. Just noting a small batch queue creates a delay between queues (3-4s in my tests) looking at the detailed logging table.
image

It was 5 this PR #24151 made it 100 now it is 5 again... https://github.com/civicrm/civicrm-core/blob/master/CRM/Import/Parser.php#L673

Noting detailed logging off doesn't seem to have that much of an effect, which is surprising.

**Comment by andyburnsco** [comment]
50 is probably what it should be and is safest for all installs: https://github.com/civicrm/civicrm-core/pull/24152

**Comment by eileenmcnaughton** [comment]
See https://github.com/civicrm/civicrm-core/pull/24772

**Pull request merged**
