### PR TITLE
CRM-20309 Schedule mailing jobs at increasing times

### PR DESCRIPTION
**Pull request by rthouvenin**
This implements the first solution that I suggest in CRM-20309.

---

 * [CRM-20309: Ensure A\/B tests can be sent in parallel](https://issues.civicrm.org/jira/browse/CRM-20309)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@tttp any chance you could review this?

**Comment by mattwire** [comment]
@rthouvenin Does this limit overall send rate to 1 per second?  Eg. if your send mail job runs every 5 minutes and you have > 300 emails to send I think with this patch it would only send 300 per 5 minutes?  Or am I wrong?

**Comment by rthouvenin** [comment]
@mattwire This does not limit the send rate. It sets the scheduled date of mailing jobs (that is, a row of `civicrm_mailing_job`, not in the sense of a system scheduled job. Right, this is confusing...), not email deliveries. Also, the modified loop is for a single mailing. It is right to say that with this patch, at most one job per second will be processed for each mailing. But if you have mailings with multiple jobs, and each job is processed in less than one second, you should probably increase the batch size :)

**Comment by tttp** [comment]
@eileenmcnaughton yes, sure.

State so far:

We've put it on prod. As expected, it has no impact on "normal" mailings, as in "delaying" the sending of children jobs by 1 sec has no impact on the mailing speed (the cron picks up the next job, that happen to be scheduled 1 sec after the first one and it works fine, no big surprise). 

We had some AB testings, but so far none with a size bigger than our batch size (10k). It worked fine too, obviously, the new code wasn't touched.

We should have a bigger AB mailing so we can test "for real" the impact of Romain's patch later this week.

Stay tuned...

X+

**Comment by mattwire** [comment]
@rthouvenin Say I have one mailing which I schedule to send "now".  It has 1000 recipients and my civimail is configured as follows: job size=0 (single job); batch=5000; throttle time: 0.  Scheduled task runs every 5 minutes. Will those 1000 emails be sent as quickly as possible, or will they be sent one per second?

**Comment by rthouvenin** [comment]
They will be sent as quickly as possible.

**Comment by tttp** [comment]
@mattwire, the code change is only when you have a job size <> 0 (and the mailing size is bigger than the job size). In your case, it won't change a thing, as you will not have children jobs

**Comment by eileenmcnaughton** [comment]
Now I think I understand this it makes sense to me - look forward to feed back later in the week

**Comment by eileenmcnaughton** [comment]
@tttp I believe this is waiting on feedback from you to merge

**Comment by rthouvenin** [comment]
Since Apr 26th, we've sent 23 pairs of A/B tests. 12 were sent to groups of size <10k, 11 to groups of size from 10k to 78k. We currently have a job size of 10k and a limit of 3 cron jobs.
All emails were sent fine regardless of size. The big ones had their jobs scheduled at 1-second interval as expected.

**Pull request merged**
