### PR TITLE
Repair "Norwegian Bokmål" string

### PR DESCRIPTION
**Pull request by christianwach**
Overview
----------------------------------------
Fixes [this issue](https://lab.civicrm.org/dev/core/-/issues/2909) on Lab so that "Norwegian Bokmål" renders correctly.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I guesss we should also add an upgrade script for existing dbs

**Comment by christianwach** [comment]
@eileenmcnaughton Ah, yes. Hmm, I have never looked at that process before. Any docs or a bare-bones example I could look at?

**Comment by demeritcowboy** [comment]
Also the string is in sql/civicrm_generated.mysql - you don't need to regenerate the whole file just a direct edit would be ok here.

The upgrade part is a bit tricky because (a) you don't want to update it if they've customized it, and (b) if they installed civi in non-english then the string you're looking to verify in (a) might be translated. But it doesn't have to be perfect - just don't update if no match. So I think something like https://github.com/civicrm/civicrm-core/blob/5b6ef63d89f640b8f97b1d7b21f00e2c1a34dc80/CRM/Upgrade/Incremental/php/FiveTwentySix.php#L106-L115

**Comment by colemanw** [comment]
@christianwach - can you take a stab at ^

**Pull request merged**
