### PR TITLE
ScheduledReminders - Rewrite entire form using metadata

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
This is a comprehensive rewrite of the "Scheduled Reminders" create/edit form.

Before
----------------------------------------
Terrible code + some usability problems. Impossible to add a new scheduled mapping type (e.g. a new one based on SearchKit) without adding even more hacks to an already overcomplicated mess.

After
----------------------------------------
Form code is entirely driven by metadata, no entity-specific hacks, easy to add new mapping types declaratively.
Usability somewhat improved.

Techie Details
---------
The complexity of the form lies in the fact that various fields have different meanings depending on the selected mapping type. For example the `entity_value` field might mean "Activity Type" or "Financial Account" or "Event Type" or "Event ID". The `entity_status` field also refers to different option lists, sometimes dependent on the selection of `entity_value` and it may or may not allow multiple values and it may or may not be required.
The form also allows those fields to be pre-selected when embedded on an Event page, and the old Quickform HierSelect widget coped very poorly with all those scenarios. As a result the form employed a *lot* of javascript to handle specific hard-coded issues, and a few bespoke ajax callbacks. None of which worked perfectly.
The `postProcess` & `validate` functions employed a sub-function called `parseActionSchedule` which was doing way too much work: 1. to detangle all the overcomplicated form values 2.  preprocessing that really belonged in the BAO, and 3. to save a field-mapping (alarmingly this was happening during form validation AND postProcess!).

This rewrite moves all of that logic into the BAO and getFields, allowing each mapping-type to set metadata appropriately (e.g. is a particular field required for this mapping type? does it support multiple values? does it have a different option list depending on another field selection?). This allowed me to delete the bespoke ajax callbacks and just call api4.getFields from the form. The new metadata also describes the relationship between fields (so when you update one field it knows which others to reload). All this new dynamic metadata benefits more than just the form, it also allowed a [SearchKit-based ScheduledReminders screen for AdminUI](https://github.com/civicrm/civicrm-core/pull/26896).

Comments
----------------------------------------
Further reading:
- #26923
- #26896 
- #26881 
- #26884
- #26876
- https://issues.civicrm.org/jira/browse/CRM-15536

### CODE REVIEW

**Comment by larssandergreen** [comment]
Good to see what has to be the wonkiest form anywhere spruced up.

Few comments and small suggestions (some of these were also present in the old form, but I think are minor changes worth making at this point):

The "Add Reminder" button at civicrm/admin/scheduleReminders is broken (opens the browse page in the pop-up instead of the add form).

For Limit or Add Recipients, the new UI is confusing for an Event. Am I limited or adding recipients when I choose a group, a participant role or specific contacts? It's unclear.

It might be better to move the Limit or Add Recipients / Recipients field up to above trigger date, so it is together with the other "who is this going to" options.

Similarly, move Repeat up above Record Activity, so the date options are all together.

From name and From email fields are a little too small. They should also be in the Email Screen section.

Email Screen is a weird heading. Just Email would be fine, though it could also be made non-collapsible with no heading to simplify.

**Comment by colemanw** [comment]
Thanks @larssandergreen for reviewing this beast.

> The "Add Reminder" button at civicrm/admin/scheduleReminders is broken (opens the browse page in the pop-up instead of the add form).

Fixed.

> For Limit or Add Recipients, the new UI is confusing for an Event. Am I limited or adding recipients when I choose a group, a participant role or specific contacts? It's unclear.

Fixed. Changed the label to "Recipients" for Events (consistent with Activities, which also don't allow you to add "additional" recipients).

> It might be better to move the Limit or Add Recipients / Recipients field up to above trigger date, so it is together with the other "who is this going to" options.

Good suggestion, might be a little tricky, I've left as-is for now.

> Similarly, move Repeat up above Record Activity, so the date options are all together.

Done.

> From name and From email fields are a little too small. They should also be in the Email Screen section.

Done.

> Email Screen is a weird heading. Just Email would be fine, though it could also be made non-collapsible with no heading to simplify.

Done. Changed "Email Screen" to "Email" and "SMS Screen" to "SMS".

**Comment by larssandergreen** [comment]
That's great, @colemanw. I will continue to review, though might take a bit to come back to this.

**Comment by totten** [comment]
Re: layout - 

(1) There's an unlabeled row that describes when the message goes out. There are a few other fields that also describe the timing of the messages. I like that the timing fields are next to each other. 

Screenshot from 2023-08-08 19-29-42-highlight

But the unlabeled one feels mysterious, and it all kind-of runs-together. 

Perhaps these should be split-out to a fieldset called "_Scheduling_" or "_Schedule_"? 

(*Then the next few fields -- "Recipients", "Enabled" -- would shift upward and remain in the top fieldset.*)

(2) "Record Activity" feels like the odd-man-out. Would it make sense at the bottom of the "Email" section? i.e. the reason to enable this box is that you want a record of each email sent (*i.e. it copies the subject, body, etc from the email to an activity*).

**Comment by colemanw** [comment]
@totten ah, in your screenshot, the "When (trigger date)" row was being hidden due to a weird js bug which I've fixed. Now it looks like this:
image

Note the form is a bit bigger when you have a multilingual site (adds 2 fields) and an SMS provider configured (adds a bunch) so I'm not entirely sure what the optimal arrangement of fields is per @totten and @larssandergreen's suggestions. But I wonder if this PR is "good enough" to merge given it's massive goal of "metadata-based-code overhaul" and modest goal of "somewhat improve usability".

**Comment by totten** [comment]
@colemanw Yeah, I think it's great that the widgets are backed by metadata. Subjectively, the dynamic select2 stuff feels a lot nicer than the hierarchical selects did. Esp when typing/filtering (eg for "Activity Type" or "Event" name). So general woot.

> But I wonder if this PR is "good enough" to merge given it's massive goal of "metadata-based-code overhaul" and modest goal of "somewhat improve usability".

Yeah, that's fair.

Just reflecting - I think the layout of this screen has been so weird that I (and probably others) have been afraid to touch it - i.e. fixing the layout would make it unrecognizable to folks who've learned the (weird) layout. But that's really ossification. It's nice to have an excuse for reorganizing it. 

I think it would be great if we get could other layout improvements into the same release. But I agree we don't need to block this PR on that.

---------

A couple other small bits I noticed in testing:

* Open "Add Reminder" in its own tab. Fill in some data (e.g. by "Activity Type". After saving, there's a message: `( ! ) Warning: Undefined array key "mode" in /Users/totten/bknix/build/s3/web/core/CRM/Admin/Form/ScheduleReminders.php on line 318` (*Observed on php81.*)
    * (*The warning is less problematic on D7 and more problematic on standalone -- where it has a cascade effect which kills the HTTP redirect. But that part may be an issue with standalone and its recent updates to error handling.*)
* Make a new reminder and fill out the form as a typist -- pressing the `Tab` key to navigate. (Enter a "Title: Hello"; press `Tab`; choose "Used for: Activity"; press `Tab`). When new fields are added, the `Tab` skips past them. So you have to tab-backward. Not a killer thing. 
    * This is more of a functional issue, and it did work before. But... if it's a long fix and it's the only functional issue... then it would be fair to merge and follow-up.

**Comment by colemanw** [comment]
Thanks @totten I've pushed a fix for the undefined index.

> Make a new reminder and fill out the form as a typist -- pressing the `Tab` key to navigate. (Enter a "Title: Hello"; press `Tab`; choose "Used for: Activity"; press `Tab`). When new fields are added, the `Tab` skips past them. So you have to tab-backward. Not a killer thing. 

The only way I was able to reproduce this was by adding `sleep(2);` in `CRM_Api4_Page_AJAX::run()` because you have to hit the tab key faster than the metadata can load. I'm not sure how to improve the UX there because when the select2s are loading they are either disabled or hidden, and I don't think you can tab into either.

**Comment by totten** [comment]
> (@colemanw) I've pushed a fix for the undefined index.

Great.

> The only way I was able to reproduce this was by adding sleep(2); in CRM_Api4_Page_AJAX::run() because you have to hit the tab key faster than the metadata can load.

Strange, it's simple/reliable for me. Observed in Firefox and Chrome. I retried with a few different keystroke-sequences, and maybe that's the difference. Compare:

1. Focus on "Title". Press `f` `o` `o` `tab`. (_Moves to next field._) Press `a` `c` `tab`. (_Selects "Activity Type" and moves to next field._)
    * N.B. The _select_ and _move_ come from the same keypress.
    * The _move_ here winds up too far.
2. Focus on "Title". Press `f` `o` `o` `tab`. (_Moves to next field._) Press `a` `c` `enter`. (_Selects "Activity Type"._) Press `tab`. (_Moves to next field._)
    * The _select_ and _move_ come from _different_ keypresses.
    * It works nicely. (*Although, presumably, the AJAX-sleep-hack might change it.*)

FWIW, I have this fear of pressing `enter` in the middle of any form. (*It might save prematurely...*) But if you know that `enter` is OK, then one can habituate to it.

> I'm not sure how to improve the UX there because when the select2s are loading they are ...

Ah, it's contingent on an AJAX request to decide what fields to show, so the timings are too different. (User expects a to focus the next field in, say, 50-150ms. AJAX takes 100-1,000ms.) Bridging that gap is probably pretty awkward.

**Comment by colemanw** [comment]
@totten ah, I see now. Yes I was hitting `enter` instead of `tab` to make the selection in the select2.
Still not sure of the right fix though.

**Comment by totten** [comment]
Yeah, I don't know how either. It feels like the kind of thing that probably has a clever flag built into  `select2`. But absent that, all I can imagine is something more [heavy-handed with multiple parts](https://gist.github.com/totten/439d301defc27f1eab9dee566f61756a).  Or maybe prefetch more metadata so that it doesn't need an AJAX call. Both sound like burdensome changes.

Regardless... the current PR (even with the tab quirk) is still a net-improvement on the typing experience... IMHO the negative side (*50% chance of a quirk in the tabbing-experience, depending on your specific keystroke*) is outweighed by the positive side (_`select2` autocomplete is much better than `<select multiple>`_).

**Pull request merged**
