### PR TITLE
Quick Search By Legal Name

### PR DESCRIPTION
**Pull request by sunilpawar**
Overview
----------------------------------------
Organization contact have legal name field, but there is no way include legal name in quick search.

Before
----------------------------------------
No way to include legal name in quick search.
Screenshot 2022-03-14 at 2 34 25 PM

After
----------------------------------------
Option available to include legal name in quick search, default value is `No`.
Screenshot 2022-03-14 at 2 26 11 PM

Screenshot 2022-03-14 at 2 32 30 PM

### CODE REVIEW

**Comment by colemanw** [comment]
When I read the title of this PR I assumed you were just going to add an item to this list:
image

Which would have felt like a more manageable change. Because those search prefrerence settings are actually meant to affect more than just quickearch - they apply to advanced search & search builder too.

**Comment by sunilpawar** [comment]
@colemanw is it ok, if i provide additional option for legal name by keeping current functinality..?

**Comment by colemanw** [comment]
I'm going to close this as it's been 3 weeks with no reply from the OP, but it can be reopened once the feedback has been incorporated.

**Comment by omegaresearchfoundation** [comment]
The addition of a Search Preferences option to include 'legal name' to the quick search (and advance search and search builder) would be extremely useful for our use case. @sunilpawar how much additional work would it take to replicate this for search builder and advanced search so that it is consistent with Nickname?

**Comment by sunilpawar** [comment]
@omegaresearchfoundation  I think legal name get work in Advanced Search on field `Complete OR Partial Name`
For having separate option on quick search ,  i will start working it ..

**Pull request closed without merging**
