### PR TITLE
CRM-16387 - Backport Civi\Core\Container and lock fixes

### PR DESCRIPTION
**Pull request by totten**
- [CRM-16387: problem creating job locks when triggering mailings](https://issues.civicrm.org/jira/browse/CRM-16387)

### CODE REVIEW

**Comment by totten** [comment]
Depends on https://github.com/civicrm/civicrm-packages/pull/116

**Comment by totten** [comment]
jenkins, test this please

**Comment by totten** [comment]
The test failure on this only occurs when running the suite -- not when running individually. I bisected the test classes and found that it's some kind of interaction with `api_v3_ContributionTest`.

**Comment by totten** [comment]
jenkins, test this please

**Comment by totten** [comment]
jenkins, test this please

**Comment by totten** [comment]
jenkins, test this please

**Comment by totten** [comment]
jenkins, test this please

**Comment by eileenmcnaughton** [comment]
@totten do you want this merged for Wed release?

**Comment by totten** [comment]
@lcdservices, how did your testing with this PR end up?

**Comment by eileenmcnaughton** [comment]
merge or close?

**Comment by eileenmcnaughton** [comment]
@totten should this go into 4.4 - only one promised release left...

**Comment by totten** [comment]
I defer to the 4.4. release manager. ;) 

I'd be a soft -1 on merging. Half the rationalization for this was that it would make backporting things to 4.4 easier -- but not much point if 4.4 reaches its EOL soon.

**Comment by eileenmcnaughton** [comment]
I'm a soft plus 1 :-) Reason being that if it IS a safe backport then I prefer people to have more similar code where possible.

But, just looking - there are a bunch of changes to existing as well - I'll close then

**Pull request closed without merging**
