### PR TITLE
[REF] Stop passing contributionPageID to isEmailReceipt

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
[REF] Stop passing contributionPageID to isEmailReceipt

Before
----------------------------------------
code does a lot of work in various places to pass in contribution_page_id

After
----------------------------------------
is_email_receipt looked up based on contribution - we can remove those places after this

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
Looks like a few tests hit this

```
api_v3_ContributionPageTest.testSubmitMembershipBlockIsSeparatePaymentPaymentProcessorNowChargesCorrectAmounts with data set #0
api_v3_ContributionPageTest.testSubmitMembershipBlockIsSeparatePaymentPaymentProcessorNowChargesCorrectAmounts with data set #1
api_v3_ContributionPageTest.testSubmitZeroDollar
api_v3_ContributionPageTest.testSubmitMembershipBlockNotSeparatePaymentProcessorInstantRenew
api_v3_ContributionPageTest.testSubmitMembershipBlockNotSeparatePaymentWithEmail
api_v3_ContributionPageTest.testSubmitMembershipBlockNotSeparatePaymentZeroDollarsWithEmail
api_v3_ContributionPageTest.testSubmitMembershipBlockIsSeparatePaymentWithEmail
api_v3_ContributionPageTest.testSubmitMembershipBlockIsSeparatePaymentZeroDollarsPayLaterWithEmail
api_v3_ContributionPageTest.testSubmitMembershipBlockIsSeparatePaymentPaymentProcessorNow
api_v3_ContributionPageTest.testSubmitMembershipComplexPriceSetPaymentPaymentProcessorRecurInstantPayment
api_v3_ContributionPageTest.testSubmitMembershipPriceSetPaymentPaymentProcessorSeparatePaymentRecurInstantPayment
api_v3_ContributionPageTest.testSubmitMembershipIsSeparatePaymentNotRecur
api_v3_ContributionPageTest.testSubmitPledgePayment
api_v3_ContributionTest.testCompleteTransactionContributionPageFromAddress
api_v3_ContributionTest.testCompleteTransactionMembershipPriceSet
api_v3_ContributionTest.testCompleteTransactionMembershipPriceSetTwoTerms
CRM_Contribute_Form_Contribution_ConfirmTest.testPayNowPayment
```

**Comment by eileenmcnaughton** [comment]
yay - thanks - that makes it easy to alter!

**Comment by eileenmcnaughton** [comment]
I re-opened this rather with the change rather than starting a new PR because the above ^^^ lists all the tests that cover the code I tidied up in this PR

**Comment by yashodha** [comment]
@eileenmcnaughton the tests are passing and this is the only one call to the method. It looks good to me to merge.

**Pull request merged**
