### PR TITLE
CRM-16595 extend API so setvalue supports T_DATE + T_TIME columns

### PR DESCRIPTION
**Pull request by kenwest**

### CODE REVIEW

**Comment by colemanw** [comment]
Hi @kenwest  we are in the process of deprecating and hopefully removing the "setvalue" api. What's your use-case here and could you possibly use the "create" api instead?

**Comment by kenwest** [comment]
My use case is a short-term need to get the eWAY Recurring Payment Processor working for 4.6.3. It's something Eileen is in the midst of moving into core.

**Comment by eileenmcnaughton** [comment]
This is primarily around setting the trxn_id?

**Comment by kenwest** [comment]
I was using 'setvalue' to set the 'receipt_date'

**Comment by colemanw** [comment]
Is there a reason that 'create' action won't work for this?

**Comment by kenwest** [comment]
Coleman, I haven't tried that, but I'm sure it will. Judging by Eileen's work rate on beefing up Payment Processors, I suspect my little hack won't be needed for long. As you're planning to deprecate 'setvalue' I suggest you close this PR.

**Pull request closed without merging**
