### PR TITLE
Fix CRM-20401: use native CiviCRM recurring links

### PR DESCRIPTION
**Pull request by twomice**
This just adds the contribution ID to $ids if it's available. I'm unsure why that's not already being done, despite being expected by CRM_Contribute_BAO_Contribution::composeMessageArray() .

---

 * [CRM-20401: Cancel\/modify URL receipt links not correct for Paypal Website Payments Pro](https://issues.civicrm.org/jira/browse/CRM-20401)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@twomice the test failure looks legit @eileenmcnaughton thoughts?

**Comment by eileenmcnaughton** [comment]
It relates to --=_74ac560e02cc19ef19aa73133351f098--
' contains "cancelSubscriptionUrl:::http://dummy.com". 

sounds familiar & like something on this was discussed recently although I don't recall merging.

I really would want to ensure any fixes to this code include test coverage

**Comment by twomice** [comment]
Changed to WIP. Need to look at test failures and test coverage.

**Comment by twomice** [comment]
@seamuslee001 or @eileenmcnaughton Regarding the failing test: Why should the Cancel / Billing / Update URLs for the Dummy processor be pointing to http://dummy.com? I know it's the "Recurring Payments URL" and "Site URL" for the Dummy processor in this test, but: why do we expect these URL to point to that external domain instead of going through CiviCRM?

**Comment by twomice** [comment]
@seamuslee001 or @eileenmcnaughton any thoughts? Who would know about this?

**Comment by jitendrapurohit** [comment]
jenkins, retest this please

**Comment by twomice** [comment]
@jitendrapurohit Thanks for trying. I've decided to just re-write the test to match the code change. This code change *intends* to change the URL so that it contains "[site-name.com]/civicrm" instead of "dummy.com", so I'm working from the view that the test is wrong. Somebody please talk me out of that if you like.

**Comment by eileenmcnaughton** [comment]
I'm happy with the test change

**Comment by twomice** [comment]
Jenkins test this please.

**Pull request merged**
