### PR TITLE
[REF] [Test] IDE cleanup on ReportTemplateTest

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Code cleanup in test class

Before
----------------------------------------
Margin super-colourful in IDE

After
----------------------------------------
Easier to spot ACTUAL errors, code more compliant

Technical Details
----------------------------------------
Various - comments, use of double quotes, less preferred or deprecated functions.

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
@eileenmcnaughton can you pls rebase this?

**Comment by eileenmcnaughton** [comment]
rebased!

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
Changes look good to me merging

**Pull request merged**
