### PR TITLE
oauth-client - Add test for existing Auth Code flow behavior

### PR DESCRIPTION
**Pull request by highfalutin**
Preparation for work on the OAuth client extension to support OAuth tokens linked to particular contacts, as discussed with @totten at https://lab.civicrm.org/dev/core/-/issues/2181#note_58421

Before I make any PRs that change the inner workings of the auth code flow, this adds a test that asserts the existing behavior as a baseline.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Looks like jenkins doesn't love this as much as I do https://test.civicrm.org/job/CiviCRM-Core-PR/40573/checkstyleResult/new/

**Comment by highfalutin** [comment]
oh Jenkins! PHPStorm is formatting my code to PSR-12 standards. Do you happen to know how I can tell it to use the style that Jenkins likes?

**Comment by highfalutin** [comment]
I think I wasn't understanding https://docs.civicrm.org/dev/en/latest/tools/phpstorm/#code-style-setup. I'll reformat. And then just close this PR and make a new one, yes?

**Comment by seamuslee001** [comment]
this looks fine to me @totten ?

**Comment by totten** [comment]
Ooh, yes, please. More test coverage. :) 

This is a test-only enhancement, so there's no `r-run`/`r-user`/etc. Looks pretty good and passes tests. Merging.

**Pull request merged**
