### PR TITLE
Enable/Disable switcher button added.

### PR DESCRIPTION
**Pull request by helenagarcia90**

### CODE REVIEW

**Comment by kurund** [comment]
jenkins, add to whitelist

**Comment by colemanw** [comment]
Typically the api is thinner than this, calling upon the BAO to do the heavy lifting. Is there a reason this needs to be different @totten ?

**Comment by eileenmcnaughton** [comment]
This seems pretty stalled :-( And the PR is out of date too. I'm not clear enough about the changes to the cxn api to know whether this is right - @totten  is the right person to review this. But if you still think this patch should go in I think it would be worth creating a JIRA to link it to. I would probably advocating closing the PR & linking to the patch from the ticket (since it is stale) or rebasing the PR to be fresh again

**Comment by totten** [comment]
I think that this is one of the patches that Helena worked on during the sprint, and I missed the notifications about it at the time. I'll try a quick resolution of the MC.

**Comment by totten** [comment]
Merged manually. Thanks you, @helenagarcia90 ! I'll forward-port to 4.7.

**Comment by totten** [comment]
Forward port is https://github.com/civicrm/civicrm-core/pull/7556

**Pull request merged**
