### PR TITLE
5.27.0 release notes - initial run

### PR DESCRIPTION
**Pull request by agh1**
FYI @alifrumin will be following up soon with changes

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
@agh1 Thanks again as always to you and @alifrumin for this.

With the move to extensions included in core, have you given thought to including changes to those extensions in the release notes?

**Comment by agh1** [comment]
@MegaphoneJon that's a great suggestion, and we haven't really thought about it.  It would make sense since there's less and less difference between a shipped extension you have to enable and a component like CiviCampaign that isn't enabled by default.  However, there's a workflow difference if those are in different repos.  I also don't know how strict extension maintainers are about requiring all changes to be in a PR merged with a commit.  (We don't look at each commit--there are too many--and not everything has an issue, so we have to work PR by PR.)

At this point, is it just the sequentialcreditnotes extension, and if so, do you know if the intent is that the `master` branch of `civicrm-core` gets active development or that the extension retains its own repo and it's included like a package?  If the former, we should be fine since PRs will be needed to make changes.  If the latter, we'll presumably still have PRs to merge the new version, so it can be something like:

```md
**Update AwesomeExtension to v1.1 ([123](https://github.com/civicrm/civicrm-core/pull/123))**

See [the extension's changelog](https://github.com/awesome/extension/CHANGELOG.md) for details.
```

**Comment by agh1** [comment]
I see that the iATS extension is included in the tarball but not in buildkit, and it is not in this repo.  There's no way for us to keep track of changes there.  I don't know why the two included extensions are handled so differently.  The way it's included [doesn't have any reference to version](https://github.com/civicrm/civicrm-core/pull/11052/files) unlike things included via composer.  When the included iATS extension changes, there's really no way for us to know, and I'm not eager to chase down changes in repos all over the place.

**Comment by MegaphoneJon** [comment]
I think your suggestion on how to log these in the release notes makes a lot of sense; if the extension isn't in `civicrm-core` then the `Update AwesomeExtension` approach works great.

Why the two extensions are handled so differently is a good question, but out of scope here.  I assume it's because of their different histories (one was code removed from core, the other not).  I assume this issue will rear its head when the next core extension is brought in.

**Comment by agh1** [comment]
Thanks @MegaphoneJon I made a [post in the extensions :tomato: most](https://chat.civicrm.org/civicrm/pl/gqduebhxuifd5rin66umtztaph) to point this out and get folks thinking about this.

**Comment by seamuslee001** [comment]
Test fail unrelated

**Pull request merged**
