### PR TITLE
Enable single value alter for payment processor

### PR DESCRIPTION
**Pull request by eileenmcnaughton**

### CODE REVIEW

**Comment by totten** [comment]
Yeah, the list of skipped entities has gotten long. Seems like a nice idea to fix a few of these. This came up during Chris's conversation about toggling `payment_processor`'s `is_active` in https://issues.civicrm.org/jira/browse/CRM-20591

FWIW, `SyntaxConformanceTest` has two ways of opting out of `testCreateSingleValueAlter()` -- `toBeSkipped_updatesingle` (which is a blunt instrument) and `getKnownUnworkablesUpdateSingle` (which is more surgical). In retrospect, we probably should discourage the blunt opt-outs.

**Comment by eileenmcnaughton** [comment]
yep -I put this up to show @xurizaemon  - was expecting it to fail :-)

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Pull request closed without merging**
