### PR TITLE
5.3.0 release notes

### PR DESCRIPTION
**Pull request by agh1**

### CODE REVIEW

**Comment by agh1** [comment]
Still to do: contributor list and boilerplate.

**Comment by seamuslee001** [comment]
@agh1 it is likely we will have at least 1 maybe 2 more PRs that will be going into 5.3

**Comment by eileenmcnaughton** [comment]
sounds good - we have 2 PRs to merge but in fact they are both just updates to items already in the notes

**Comment by agh1** [comment]
@eileenmcnaughton great--these are ready to go.  If you (or whoever merges) can just add the PR link within the parentheses on the existing issues to merge, that would be perfect.

**Pull request merged**
