### PR TITLE
dev/core#4783 Fix ability to clone and delete Contribution Pages when AdminUI enabled

### PR DESCRIPTION
**Pull request by aydun**
Overview
----------------------------------------
Bug fix: with AdminUI enabled, the links to clone and delete Contribution Pages did not work.

Before
----------------------------------------
Links to clone and delete just go a listing of Contribution Pages

After
----------------------------------------
Clone and delete works

Technical Details
----------------------------------------
Moves the clone and delete actions to civicrm/admin/contribute/manage

@colemanw - in the bulk actions we have a 'Delete Contribution Pages' action using the delete task and 'Delete Contribution Page' using the delete action with different UI's. Presumably we are preferring the api task version rather than the older action one?

Comments
----------------------------------------
Reviewer: please check clone & delete of Contribution Pages works both with and without AdminUI enabled.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@aydun this is OK against master but it might be preferable against the rc - purely up to you - if you don't want to alter then master is fine

**Comment by eileenmcnaughton** [comment]
actually - 2 gitlabs relate to this - so prob should go for the rc -

**Comment by francescbassas** [comment]
I tested on demo PR site, and I can confirm that after install Admin UI, it is now possible clone contribution pages.

imatge

**Comment by colemanw** [comment]
@aydun thanks for this. Code looks good. Review looks good. Can you rebase this PR for 5.68?

**Comment by aydun** [comment]
Grrr - must learn more git magic !  

See #28189

**Pull request closed without merging**
