### PR TITLE
Fix dataSource test to test permissions

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fix dataSource test to test permissions

Before
----------------------------------------
As @colemanw pointed out the test check was bypassing the permission check

After
----------------------------------------
Calls it

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
would have picked up the deprecation in https://github.com/civicrm/civicrm-core/pull/28325

**Comment by eileenmcnaughton** [comment]
The test run started before the fix was merged so we got  the fail & next run should pass - test this please

CRM_Contact_Import_Form_DataSourceTest::testDataSources
Expected array of selectWhereClauses for civicrm_user_job.created_id, instead got "= 3 OR is_template = 1" Caller: Civi\Api4\Query\Api4SelectQuery::getAclClause

/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/CRM/Core/Error.php:1129
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/CRM/Core/DAO.php:3194
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/Civi/Api4/Query/Api4SelectQuery.php:367
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/Civi/Api4/Query/Api4SelectQuery.php:88
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/Civi/Api4/Generic/DAOGetAction.php:106
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/Civi/Api4/Generic/DAOGetAction.php:94
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/Civi/Api4/Provider/ActionObjectProvider.php:72
/home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/Civi/API/Kernel.php:156

**Comment by colemanw** [comment]
Retest this please

**Comment by eileenmcnaughton** [comment]
unrelated fail

**Pull request merged**
