### PR TITLE
Address schema: index street_address column

### PR DESCRIPTION
**Pull request by agh1**
Overview
----------------------------------------
The `civicrm_address.street_address` column is unindexed, though it is queried in the quick search and now can be sorted in a report as of #15581.  This can cause performance problems on even moderate-sized databases.

Before
----------------------------------------
No index on `civicrm_address.street_address`

After
----------------------------------------
Index on `civicrm_address.street_address`

Comments
----------------------------------------
~~I'm writing an upgrade step now.~~ [done]

### CODE REVIEW

**Comment by demeritcowboy** [comment]
I tried this out and it works but see below:

* General standards
    * [`r-explain`] __PASS__
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __PASS__
      * Tested upgrade from 5.19.4 to master. Index created ok.
      * I don't see any speedup but I don't see any problems. I'm using stock settings and/or may not have enough contacts, but see below.
* Developer standards
    * [`r-tech`] __PASS with comment__
      * The required DAO and xml file updates are here and running gencode.php correctly generates civicrm.mysql.
      * Looking at the EXPLAIN for quicksearch, and also I looked at it for advanced search and the constituent detail when sorted by address, it doesn't seem like it helps much? See example output below.
    * [`r-code`] __Minor Issue__
      * Because 5.21alpha1 was split to beta1 a couple hours after this PR was put up the upgrade script is in the wrong function. Strictly speaking now it should be in the upgrade_5_21_beta1() function.
    * [`r-maint`] __PASS__
    * [`r-test`] __PASS__

```
> explain SELECT DISTINCT(id), data, sort_name, exactFirst
    ->         FROM   (
    ->             ( SELECT IF(sts.street_address = 'main', 0, 1) as exactFirst, cc.id as id, CONCAT_WS( ' :: ',
    ->             sort_name, email, street_address )
    ->              as data
    ->             , sort_name, email, street_address
    ->             FROM   civicrm_contact cc LEFT JOIN civicrm_email eml ON ( cc.id = eml.contact_id AND eml.is_primary = 1 )  LEFT JOIN civicrm_address sts ON ( cc.id = sts.contact_id AND sts.is_primary = 1 )
    ->      WHERE ( sts.street_address LIKE '%main%')  AND cc.is_deleted = 0
    ->     ORDER BY exactFirst, sort_name
    ->     LIMIT 0, 10 )
    ->     ) t
    ->     ORDER BY exactFirst, sort_name
    ->     LIMIT    0, 10;
+------+-------------+------------+--------+------------------------------------------------+-----------------------------+---------+-------------------------------+------+---------------------------------------------------------------------+
| id   | select_type | table      | type   | possible_keys                                  | key                         | key_len | ref                           | rows | Extra                                                               |
+------+-------------+------------+--------+------------------------------------------------+-----------------------------+---------+-------------------------------+------+---------------------------------------------------------------------+
|    1 | PRIMARY     | <derived2> | ALL    | NULL                                           | NULL                        | NULL    | NULL                          |   10 | Using temporary; Using filesort                                     |
|    2 | DERIVED     | sts        | range  | index_is_primary,FK_civicrm_address_contact_id | index_is_primary            | 2       | NULL                          |  169 | Using index condition; Using where; Using temporary; Using filesort |
|    2 | DERIVED     | cc         | eq_ref | PRIMARY,index_is_deleted_sort_name             | PRIMARY                     | 4       | x.sts.contact_id |    1 | Using where                                                         |
|    2 | DERIVED     | eml        | ref    | index_is_primary,FK_civicrm_email_contact_id   | FK_civicrm_email_contact_id | 5       | x.sts.contact_id |    1 | Using where                                                         |
+------+-------------+------------+--------+------------------------------------------------+-----------------------------+---------+-------------------------------+------+---------------------------------------------------------------------+
```

**Comment by agh1** [comment]
@demeritcowboy I just rebased and moved it to a new 5.22.alpha1 upgrade step.

For the performance improvements on the quick search, I think you're right: the where uses both the address search query in `civicrm_address.street_address` and `civicrm.contact.is_deleted`, which is not indexed on its own, though it was at one time:
https://github.com/civicrm/civicrm-core/blob/9bbd0ad5ba1382329d2e6c354021149f3786e8b9/xml/schema/Contact/Contact.xml#L840-L845

Anyway, my bigger rationale is the new street address sort on the Constituent Detail report introduced in #15581, but now I'm wondering whether that has any effect either.  A simple example query is:

```sql
SELECT SQL_CALC_FOUND_ROWS contact_civireport.sort_name as civicrm_contact_sort_name, contact_civireport.id as civicrm_contact_id, address_civireport.street_address as civicrm_address_street_address  
FROM civicrm_contact contact_civireport 
  LEFT JOIN civicrm_address address_civireport
                           ON (contact_civireport.id =
                               address_civireport.contact_id)  AND
                               address_civireport.is_primary = 1
WHERE ( contact_civireport.is_deceased = 0 ) AND ( contact_civireport.is_deleted = 0 )   
ORDER BY address_civireport.street_address ASC
```

The sorting seems to be on the address field of the joined result, which won't be indexed, right?

This may be something to drop in that case.

**Comment by demeritcowboy** [comment]
Yeah I had looked at the other two queries also including the report sorting and it didn't use the index and did a filesort. I can't think of a quickie.

Regarding is_deleted, indexes on boolean fields, especially when searching on the more common value, often don't get used. I expect it was removed because all it was doing was slowing down writes.

**Comment by seamuslee001** [comment]
it also looks like it was replaced with a combo index of is_deleted,id and sort_name which is probably quite useful in most search cases when your sorting on a name as it will be filtering on the sort name field https://github.com/civicrm/civicrm-core/blob/9bbd0ad5ba1382329d2e6c354021149f3786e8b9/xml/schema/Contact/Contact.xml#L847

**Comment by JoeMurray** [comment]
Waaay back there was deliberate decision to not index street address but to rely on address parsing and sorting parts of address separately, like street name and street number eg for Walk list report.

**Comment by eileenmcnaughton** [comment]
I'm find with adding indexes on new installs but we stopped adding indexes in upgrade scripts as it can take a  really long time and imposing a really slow upgrade is a problem. We encourage sites to run the api command to update the indexes (I think it might require manual intervention in some old DBs & we stopped trying to fix that when we ditched the check as we didn't really have enough info to resolve it.) I'm happy to merge this without the upgrade script part

**Comment by demeritcowboy** [comment]
But what we were concluding (or at least what I think we were concluding) is that a single index on street_address NEVER seems to get used by the query optimizer, at least in the practical situations where it comes up. So it would just add write overhead.

**Comment by agh1** [comment]
Yeah I'm going to close because it doesn't seem to help anything.  The street address parsing @JoeMurray mentions is nice in theory, but most things don't use the parsed data.  @eileenmcnaughton that's a good point about not adding indexes on upgrades.

**Pull request closed without merging**
