### PR TITLE
CRM-21773 Fix merging multi-value custom fields

### PR DESCRIPTION
**Pull request by JKingsnorth**
Overview
----------------------------------------
Multi-value custom fields are ignored during the merge process, when they should be merged provided we tick the box to move them during the process.

Before
----------------------------------------
Multi-value fields not migrated.

After
----------------------------------------
Multi-value fields are migrated if required.

---

 * [CRM-21773: CRM-20858 breaks merging multi-value custom groups](https://issues.civicrm.org/jira/browse/CRM-21773)

---

 * [CRM-20858: Custom fields migrated even when not asked during merge](https://issues.civicrm.org/jira/browse/CRM-20858)

### CODE REVIEW

**Comment by JKingsnorth** [comment]
The test should FAIL - proving the issue.

**Comment by JKingsnorth** [comment]
It failed, good: not ok 988 - Error: CRM_Dedupe_MergerTest::testMigrationOfSomeCustomDataOnEmptyCustomRecord

**Comment by JKingsnorth** [comment]
Now, with the fix, it should pass.

**Comment by JKingsnorth** [comment]
Erk, that's weird. The multi-value custom group isn't coming out in relTables for some reason. It works on our staging site, but it's not working in the test suite for some reason...

**Comment by JKingsnorth** [comment]
@eileenmcnaughton I think this is failing because \CRM_Dedupe_Merger::relTables is being cached in a static variable, so it's not loading up the new group I'm creating. Can you advise me on how to clear that static variable cache? I'm not sure it's even possible since the scope of the static variable is limited to the function itself? How do other unit tests get around these issues?

**Comment by eileenmcnaughton** [comment]
@JKingsnorth search for Civi::statics - that is a static var that is cleared between test runs & can be cleared from outside the function

**Comment by JKingsnorth** [comment]
Thanks @eileenmcnaughton - I'll try that out.

**Comment by JKingsnorth** [comment]
@eileenmcnaughton @systopia This is ready for review now! I had to refactor the static variable caching to get the tests to work. Thanks for the tip Eileen.

**Comment by eileenmcnaughton** [comment]
(*CiviCRM Review Template WORD-1.1*)

* ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) Pass
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) Pass - added by John
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) Pass, actual change is simple. Caching change is positive
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) Pass - not required
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) Pass - mild code improvement
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))Pass - John tested: 
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) Pass: 
* ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) Pass - trivial change:

**Comment by eileenmcnaughton** [comment]
thanks @JKingsnorth  & @systopia

**Comment by JKingsnorth** [comment]
Thanks all.

**Comment by systopia** [comment]
Thanks @eileenmcnaughton  and @JKingsnorth !

**Pull request merged**
