### PR TITLE
NFC CRM-19028 - Change get(userID) to getLoggedInContactID()

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
This is a much cut down version of #8635 which has got stale & I'm closing

@colemanw can you look & merge

---
- [CRM-19028: Change get(userID) to getLoggedInContactID()](https://issues.civicrm.org/jira/browse/CRM-19028)

### CODE REVIEW

**Review by colemanw — CHANGES_REQUESTED** [review]
You are calling a static function non-statically. Why?

**Comment by eileenmcnaughton** [comment]
I was following the wise precedent set by another code committer....

https://github.com/civicrm/civicrm-core/blame/master/CRM/Core/BAO/Dashboard.php#L103

**Comment by eileenmcnaughton** [comment]
lost interest - too hard

**Comment by colemanw** [comment]
Now I feel guilty for setting a bad example...
Here's some penance: #9227

**Pull request closed without merging**
