### PR TITLE
Typo Fix

### PR DESCRIPTION
**Pull request by homotechsual**
Overview
----------------------------------------
_Minor typo fix (full-tet to full-text) spotted by R4zoli._

### CODE REVIEW

**Comment by yashodha** [comment]
@MikeyMJCO You might want to squash the commits. Thanks!

**Comment by MikeyMJCO** [comment]
That should be squashed now (thanks @yashodha!)

**Comment by MikeyMJCO** [comment]
For future Typo PRs - is there a way for a PR to skip tests (in this instance it seems costly for a typo fix) or do we not do that?

**Comment by colemanw** [comment]
We don't have a way to skip tests, but it costs us nothing to run them & our test infra can handle it.

**Pull request merged**
