### PR TITLE
CRM-21029 - Report - Fix Activity Report SQL Syntax Error

### PR DESCRIPTION
**Pull request by monishdeb**
Rc PR of https://github.com/civicrm/civicrm-core/pull/10819

---

 * [CRM-21029: Activity report SQL syntax error](https://issues.civicrm.org/jira/browse/CRM-21029)

### CODE REVIEW

**Comment by totten** [comment]
I'm soft +1 for `4.7.24-rc` since (a) it seems the regression was very recent (`4.7.23`) and (b) we're still early in the 4.7.24 RC period and (c) you seem to have comprehension of both the original PR and the follow-up PR. 

We do have higher bar for RC updates -- some quick 👍 or 👎 from @colemanw, @eileenmcnaughton, or @seamuslee001 would be reassuring.

**Comment by colemanw** [comment]
:+1: for fixing regressions ASAP

**Comment by eileenmcnaughton** [comment]
I think recent regressions firmly includes the last couple of releases

**Comment by seamuslee001** [comment]
Just commenting i would have been a +1

**Pull request merged**
