### PR TITLE
(dev/core#365) Scheduled Reminders - Add effective end and start date, extend unit test

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Add optional effective end and start date filter while sending schedule reminders. And extend unit-test to add the filters

Comments
----------------------------------------
ping @eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@monishdeb if you add a screenshot on the UI I'll add to the dev digest

**Comment by eileenmcnaughton** [comment]
@monishdeb the tests are still winning

Test Result (2 failures / +2)
CRM_Core_BAO_ActionScheduleTest.testContactCustomDateNoAnniversary
CRM_Core_BAO_ActionScheduleTest.testMembershipOnMultipleReminder

**Comment by eileenmcnaughton** [comment]
@monishdeb I took a look at this & it looks like the test fails are just bleed - ie you defined this for one test

```
  'subject' => 'subject sched_membership_end_2week',
      'effective_start_date' => '2012-05-01 01:00:00',
```

but it messes with a different one

Also the date seems wrong on grad_tomorrow because it doesn't say what it seems to - this might be better

```
       'start_action_offset' => '1',
       'start_action_unit' => 'day',
       'subject' => 'subject sched_contact_grad_tomorrow',
-      'effective_start_date' => date('YmdHis', strtotime('-2 days')),
+      'effective_start_date' => '2013-10-15 20:00:00',
     ];

```

The actual code looks good so if the tests pass the code is fine IMHO

**Comment by monishdeb** [comment]
@eileenmcnaughton I am finally able to fix all the failing unit tests. I am pretty sure now all the SR unit-test has ESD and EED set during scheduling a reminder in different use-case. Can you please have a look.

**Comment by eileenmcnaughton** [comment]
OK - this is passing tests & makes sense

**Pull request merged**
