### PR TITLE
Address test fails

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
https://github.com/civicrm/civicrm-core/pull/29381/files#diff-fbfaf120d8d99e85c4b6c453a4efc47f4a9b3e8d896caecfd8b23c7602b3cebbR106 got deprecated between PR running tests & being merged

@mattwire @colemanw

### CODE REVIEW

**Comment by colemanw** [comment]
Thanks @eileenmcnaughton - apparently I can't keep up with myself.

**Comment by demeritcowboy** [comment]
I'm just running the one failed suite over at https://test.civicrm.org/job/CiviCRM-Manual-Test/121/

**Comment by demeritcowboy** [comment]
Oh the tooling there seems broken. Ok jenkins test this please.

**Comment by demeritcowboy** [comment]
jenkins test this please

**Comment by demeritcowboy** [comment]
infra fail but it passed that suite before so ...

**Pull request merged**
