### PR TITLE
Fix issues found whilst running local test of PR 10934 which are due …

### PR DESCRIPTION
**Pull request by seamuslee001**
…to sqlmodes not being set right on ubu 16.04

Overview
----------------------------------------
These are some fixes of test failures shown up by PR #10934 

@eileenmcnaughton @mfb @totten so I applied the PR locally and ran tests, it kicked up some issues such as date issues and also the full group by issues. There are a couple of further issues in regards to reports that aren't covered by this but this should fix most of the issues

### CODE REVIEW

**Comment by seamuslee001** [comment]
In regards to the activity one this is what it reported locally previously

```
INSERT INTO civicrm_temp_activity_details_57f85da98e241e8843fa7e3a168c4973 (activity_id,activity_date_time,source_record_id,status_id,subject,source_contact_name,activity_type_id,activity_type,case_id,case_subject,camp
aign_id )
       SELECT DISTINCT tbl.*  from (
            SELECT civicrm_activity.id as activity_id
            ,
                civicrm_activity.activity_date_time,
                civicrm_activity.source_record_id,
                civicrm_activity.status_id,
                civicrm_activity.subject,
                contact.sort_name as source_contact_name,
                civicrm_option_value.value as activity_type_id,
                civicrm_option_value.label as activity_type,
                null as case_id, null as case_subject,
                civicrm_activity.campaign_id as campaign_id

            from civicrm_activity
            left join civicrm_option_value on
                civicrm_activity.activity_type_id = civicrm_option_value.value
            left join civicrm_option_group on
                civicrm_option_group.id = civicrm_option_value.option_group_id

INNER JOIN civicrm_activity_contact ac ON ac.activity_id = civicrm_activity.id
INNER JOIN civicrm_contact contact ON ac.contact_id = contact.id

LEFT JOIN civicrm_activity_contact src ON (src.activity_id = ac.activity_id AND src.record_type_id = 2 AND src.contact_id = contact.id)

            where
                    1
                AND civicrm_option_group.name = 'activity_type' AND civicrm_activity.is_deleted = 0 AND civicrm_activity.is_current_revision =  1 AND civicrm_activity.is_test= 0 AND civicrm_activity.status_id = 1 AND civicrm_option_value
.component_id IS NULL
           )
as tbl
LEFT JOIN  civicrm_case_activity ON ( civicrm_case_activity.activity_id = tbl.activity_id )
    WHERE  civicrm_case_activity.id IS NULL GROUP BY tbl.activity_id, tbl.activity_type, tbl.case_id, tbl.case_subject  ORDER BY tbl.status_id asc, tbl.activity_date_time asc  [nativecode=1055 ** Expression #6 of SELECT list is not in GR
OUP BY clause and contains nonaggregated column 'tbl.source_contact_name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by]
```

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@monishdeb any thoughts on how to fix this https://test.civicrm.org/job/CiviCRM-Core-PR/17808/testReport/junit/(root)/CRM_Activity_BAO_ActivityTest/testGetActivitiesForAdminDashboard/ all this is caused by is the change in L941 of CRM_Activity_BAO_Activity which is to address https://test.civicrm.org/job/CiviCRM-Core-Matrix/CIVIVER=master,label=ubuntu1604/4341/testReport/junit/(root)/CRM_Activity_BAO_ActivityTest/testGetActivitiesForAdminDashboard/

**Comment by monishdeb** [comment]
@seamuslee001 I have pushed commit in this branch, that fixes those two Activity failures. Hopefully this will pass now :crossed_fingers:

**Comment by eileenmcnaughton** [comment]
I'm really uncomfortable with this approach of fixing FULL GROUP BY issues en masse without each item being a separate fix with unit tests & steps on testing. We've not really had good history with full group by fixes in terms of regressions & we seem to have a queue full of FULL GROUP BY prs going nowhere fast :-(

**Comment by eileenmcnaughton** [comment]
Closing this since it's stale - I think each of these items needs it's own PR, steps as to how to hit the query & unit test

**Pull request closed without merging**
