### PR TITLE
dev/core#2079 [REF] clean up call to apiQuery

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This fixes a few things
1) fixes apiQuery to be called statically as it is a static function
2) casts results directly to details
3) removes unused variable

Before
----------------------------------------
Screen Shot 2020-10-03 at 9 09 42 AM

After
----------------------------------------
1) fixes apiQuery to be called statically as it is a static function
2) casts results directly to details
3) removes unused variable

Technical Details
----------------------------------------
The query object that is instantiated is not used in the static function, which instantiates it's own

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton I tried finding a unit test that covered this but couldn't

**Comment by eileenmcnaughton** [comment]
@seamuslee001 you are right - that class had no cover (& is only called from Member_label despite it's name). I've added a basic 'no error' test to at least ensure this code is passed through.

**Comment by eileenmcnaughton** [comment]
ug - some sort of caching in jenkins - added a couple of lines to try to find it.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 ok - the test is passing now

**Comment by seamuslee001** [comment]
changes seem fine now merging

**Pull request merged**
