### PR TITLE
dev/drupal#176 - allow symfony 6

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
https://lab.civicrm.org/dev/drupal/-/issues/176

Before
----------------------------------------
Have to use a modified version of core to install on drupal 10

After
----------------------------------------
Can install on drupal 10 (along with https://github.com/civicrm/civicrm-core/pull/25054)

Technical Details
----------------------------------------
Note composer.lock is not changed here, so other cmses will still get what they are currently getting.

Comments
----------------------------------------
This and the other PR are the last remaining "hacks" needed.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Comment by seamuslee001** [comment]
@demeritcowboy can you please rebase this and run `composer update php` and commit the change to the lockfile (should likely only be a hash) as I see in the console `Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.`

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by demeritcowboy** [comment]
Woo!

**Pull request merged**
