### PR TITLE
CRM-18416: Developer API Explorer Financial Item displays wrong param…

### PR DESCRIPTION
**Pull request by yashodha**
…eter for Currency

---
- CRM-18416: Developer API Explorer Financial Item displays wrong parameter for Currency
  https://issues.civicrm.org/jira/browse/CRM-18416

### CODE REVIEW

**Comment by totten** [comment]
Interesting - I didn't know currencies had numeric codes. Using the symbolic codes (`USD`, `GBP`, etc) does feel more sensible.

What worries me a bit, though... is this going to be a contract change on API? For example, my understanding was that the API sometimes allows you to fields using the `name` (which then gets translated to the `id` or `value`). If the `name` is remapped, wouldn't that be a breaking-change?

**Comment by colemanw** [comment]
My concerns are about breaking the form layer (see comments on ticket), I don't think this would be an api regression because this is just metadata cleanup not funcional.

**Comment by monishdeb** [comment]
Before merging this PR @rohankatkar and I have ensured (after running setup.sh) that the currencies used in desired entities are working fine on api explorer and also checked the behavior in Search Forms + backoffice/online Contribution.  In addition I am going to add unit-test and extend webtest Search form to with respect to it, that's why I have kept the issue opened.

**Comment by monishdeb** [comment]
Earlier in API explorer the currency `value` was used instead of `name`, reason why it throws validation error 
`{
    "is_error": 1,
    "error_message": "Currency not a valid code: "
}`
as per `CRM_Utils_Rule::currencyCode($value)` it checks in `name`.
Before merging this PR I have tested on Search Forms and API Explorer for desired entities and its working fine. However only for Contribution.get API I am getting no result which I believe is a separate issue and will fix it. Will add api test for currency and extend Search Form webtest later.

**Pull request merged**
