### PR TITLE
News dashboard - Code cleanup to update js & css

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Improves javascript & css code in the News Dashboard.

Before
----------------------------------------
Before & After should look exactly the same.

After
----------------------------------------
Before & After should look exactly the same, but code has been updated:

- Use css class instead of inline style for unread items
- Use `CRM.cache` instead of `window.localStorage`
- Longer preview snippet for wide screens

### CODE REVIEW

**Comment by colemanw** [comment]
retest this please

**Comment by demeritcowboy** [comment]
For some reason it counts the number of make-it-happens as 3 when there's 4, whereas the current dashlet gets it right. I haven't looked at why.

Both before and after get the webinars wrong, both in count and they have weird blank entries. So maybe that's separate. I'm not a fan of webinars so maybe it's somehow picking up a vibe from me over the aether.

Otherwise visually everything checks out, including read/unread items. I can't test the wide-screen change.

**Comment by demeritcowboy** [comment]
Oh wait the count is a count of unread right? So that would explain the difference. Obviously I don't use this dashlet...

**Comment by colemanw** [comment]
Ok thanks for the review.

**Pull request merged**
