### PR TITLE
dev/financial#39: Drop checkMD5 support from Authorize.net

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
As per https://support.authorize.net/s/article/What-is-the-MD5-Hash-Security-feature-and-how-does-it-work note, Authorize.net is phasing out MD5 based transHash element in favor of the SHA-512 based transHashSHA2. This PR removes the MD5 check in Authorize.net payment processor 

Before
----------------------------------------
MD5 hash check is present 

After
----------------------------------------
Removed md5 hash support from Authorize.net payment processor 

Comments
----------------------------------------
ping @eileenmcnaughton @JoeMurray @MegaphoneJon

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Thanks @monishdeb I think this is the right move  - it will stop working & we should remove it before it does

**Comment by nganivet** [comment]
@eileenmcnaughton @monishdeb Auth.net did not say that it retires the MD5 check, but is replacing it with a stronger cryptographic check based of SHA2. So it seems that removing the MD5 check in our code is negatively impacting the security of our interface, and we should rather replace that check with an SHA2 check as described in https://developer.authorize.net/support/hash_upgrade.

This would translate as:
1. in CRM/Core/Payment/AuthorizeNet.php,
  - create a checkSHA2() function
  - change line 175 to call either $this->checkMD5 or $this->checkSHA2() based on which input parameters are set (transHash vs transHashSHA2)
2. in CRM/Core/Payment/AuthorizeNetIPN.php, 
  - rename checkMD5() function to checkHash()
  - change line 375 to call either $paymentObject->checkMD5 or $paymentObject->checkSHA2 based on which input parameters are set (transHash vs transHashSHA2)

I understand this will take some coding time and we might need to fundraise for this, but can we at least for now not delete the existing code/logic and implement the above with an empty checkSHA2() function (ie. return TRUE;). This way we just will have to implement the checkSHA2() function later (rather than re-implement all the logic that is already there).

**Comment by eileenmcnaughton** [comment]
@nganivet I don't think a code placeholder will save a later coder any time. Those lines will be easy enough to re-add later on

**Comment by nganivet** [comment]
@eileenmcnaughton Would you provide us with the opportunity to add these lines, and most probably SHA2 hash function, to replace the current patch? I would hate for the next CiviCRM release to be less secure than the current one.

**Comment by eileenmcnaughton** [comment]
@nganivet - if you want to write a patch to add the SHA support and associated unit test then I think that would be acceptable to be merged to core. 

There are a number of other people who do tonne of review and would be up for a review-swap I expect, so I don't think it's critical that I have time to review it
 
I'm not sure if there is any complexity in handling the situation for people who already have a MD5 hash configured - ie will their md5 hash code still work? If not the patch needs to deal with that & perhaps have some unit testing on it

**Pull request merged**
