### PR TITLE
5.34.0 release notes: final edits and late changes

### PR DESCRIPTION
**Pull request by agh1**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Thanks for once again tacking this @agh1

**Comment by MegaphoneJon** [comment]
Flagging #19209 as miscategorized.  It's listed under "CiviEvent", but the events that are getting IDs are Symfony events, not CiviEvents.

**Comment by eileenmcnaughton** [comment]
nice to see they are so well read

**Comment by MegaphoneJon** [comment]
Even better if I'd read it yesterday... but seriously, yes, this is a valuable resource and I read each one the morning of a new release.

**Comment by agh1** [comment]
Good catch I just opened PR #19528 to fix it.

**Pull request merged**
