### PR TITLE
Added test cases for failing relationship creation

### PR DESCRIPTION
**Pull request by shaneonabike**
Overview
----------------------------------------

As described in [issue#3874](https://lab.civicrm.org/dev/core/-/issues/3874) I created a test scenario for relationships that cannot be created using APIv4. The scenario essential entails disabling an existing relationship and then attempting to create another with the same details. 

While I didn't test this I believe this also fails with different information but matching contacts.

### CODE REVIEW

**Comment by shaneonabike** [comment]
Hey @colemanw can you relaunch the test as I'm not sure whether it is failing because it's supposed to or because I need to fix my syntax.

**Comment by colemanw** [comment]
@shaneonabike you can do that just by typing a comment with the words "test this please"

**Comment by colemanw** [comment]
^ and that did it.

**Comment by shaneonabike** [comment]
@colemanw seems like it's failing like it should. So now how do we proceed? Do you build a patch for the API and then we integrate this?

**Comment by colemanw** [comment]
I don't currently have spare time for that but can try to get to it when I do, maybe next month. I'm currently working on funded projects for FormBuilder.

**Comment by shaneonabike** [comment]
Yeah advancements with FormBuilder awesome! If you _have time_ point me in the direction of where to fix this in core. I can maybe try as it is holding back a client of mine in doing CiviCase forms.

**Comment by colemanw** [comment]
@shaneonabike The error is set by this, so it's a matter of figuring out what the heck is going on in that function and trying to clean it up:

https://github.com/civicrm/civicrm-core/blob/5e794c90b9c3132f9e792b513e9434721d825712/CRM/Contact/BAO/Relationship.php#L817-L898

**Comment by colemanw** [comment]
Fixed by https://github.com/civicrm/civicrm-core/pull/25047

**Pull request closed without merging**
