### PR TITLE
dev/core/issues/286, used generic function to generate label for cust…

### PR DESCRIPTION
**Pull request by pradpnayak**
…om field

Overview
----------------------------------------
https://lab.civicrm.org/dev/core/issues/286

Before
----------------------------------------
customfield-before

After
----------------------------------------
customfield-after

Technical Details
----------------------------------------
Used generic function to generate label for custom field.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@pradpnayak how does this fit with 5.3 - is this fixed in 5.3.2? We don't put fixes into 4.6 that aren't in 5.x

Also note 4.6 is pretty much on it's last bit of life  - it's slated to end at the end of this year - which would mean last release is at the start of Dec. I imagine it would be mostly security fixes going into it over these final months (although we will probably try to delay the next security release until after 4.6 ends) - so there is a better than average chance this will never be reviewed.

**Comment by pradpnayak** [comment]
@eileenmcnaughton this is [fixed](https://github.com/civicrm/civicrm-core/pull/7453) for version >= 4.7 but not for 4.6 and since the change for 4.7 is huge i thought to do a simple fix. 

@KarinG had also submitted PR(same fix) against 4.6 in January 2018 but i am not sure how did it got fixed in her case.

**Comment by eileenmcnaughton** [comment]
OK thanks - good to know it's sorted in master - will leave to the LTS team for 4.6.

**Comment by eileenmcnaughton** [comment]
I don't think this sort of thing is going into 4.6 anymore - let's close it out

**Pull request closed without merging**
