### PR TITLE
[NFC] Update AllCoreTables.data.php

### PR DESCRIPTION
**Pull request by monishdeb**
This PR is about updating the `CRM/Core/DAO/AllCoreTables.data.php`.

### CODE REVIEW

**Comment by monishdeb** [comment]
@colemanw sorry I forgot to put WIP in this PR. Yes, that's a hackish fix and I was looking in that direction to use it. Updating the patch in a min.

**Comment by colemanw** [comment]
I'm just confused about why the syntax isn't already being converted. Looking at the code, it should already be passing the file through the syntax converter.

**Comment by monishdeb** [comment]
No, it doesn't that's why I was forced to use that hackish fix, which is a bit strange. Searching for the exact cause.

**Comment by monishdeb** [comment]
@colemanw actually you are right, after running the Gencode 3rd time, this the final patch which I have updated. But then I was earlier getting improper indentation on around `[` and `]`. That makes me do the hackish fix. 

On the other hand earlier you were not able to update this `AllCoreTables.data.php` because you need to delete this file first to get created by Gencode. Anyways I think the PR is good to merge now :)

**Comment by colemanw** [comment]
Thanks Monish. I guess you'll need to rebase #11739 after we merge this.

**Comment by colemanw** [comment]
I think this can be closed if you've already incorporated these changes into the other PR.

**Pull request closed without merging**
