### PR TITLE
[REF] Fix Order class to not reload if already loaded

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
[REF] Fix Order class to not reload if already loaded

Before
----------------------------------------
Potential to reload multiple times

After
----------------------------------------
Loads if required

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
api.v4.Entity.ConformanceTest.testConformance with data set "Relationship"

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
Test fail unrelated makes sense to me merging

**Pull request merged**
