### PR TITLE
fix multi-value custom fields on participant import

### PR DESCRIPTION
**Pull request by MegaphoneJon**
Overview
----------------------------------------
Importing multi-value custom fields on "Import Participants" crashes the import.

Before
----------------------------------------
```
PHP Fatal error:  Uncaught TypeError: explode(): Argument #2 ($string) must be of type string, array given in /home/jon/local/mysite/web/wp-content/plugins/civicrm/civicrm/CRM/Import/Parser.php:1363
```

After
----------------------------------------
No crash.

Technical Details
----------------------------------------
This code in `CRM_Event_Import_Parser_Participant::formatValues()` is duplicative of code in `CRM_Import_Parser::getMappedRow()`.  `formatValues()` is only called once, in `CRM_Event_Import_Parser_Participant::import()`, which always calls `getMappedRow()` first.

Comments
----------------------------------------
This test will fail until https://github.com/civicrm/civicrm-core/pull/25945 is merged, because of the bug with the role_id.

Also, all of `formatValues()` is suspect because it's matching on incorrect array keys (e.g. `participant_event_id` and not `event_id`.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon I agree that ripping code out of the legacy functions is generally the right approach - if you rebase this & it passes it can be merged IMHO

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon let's do the rc though

**Comment by yashodha** [comment]
@MegaphoneJon you might want to rebase this PR

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
CRM_Event_Import_Parser_ParticipantTest::testImportWithExternalID
Undefined array key 12

/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/CRM/Import/Form/MapField.php:237
/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/CRM/Import/Form/MapField.php:283
/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/CRM/Import/Form/MapField.php:86
/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/tests/phpunit/CRM/Event/Import/Parser/ParticipantTest.php:83
/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/tests/phpunit/CRM/Event/Import/Parser/ParticipantTest.php:123
/home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:229
/home/homer/buildkit/extern/phpunit8/phpunit8.phar:1721

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon the test fail relates sadly as I would love to merge this given it rips out old rubbish & adds a test and bonus fixes a bug

**Comment by eileenmcnaughton** [comment]
I created a new PR for this with the test fixed & conflicts resolved - https://github.com/civicrm/civicrm-core/pull/26926

**Comment by MegaphoneJon** [comment]
Thank you @eileenmcnaughton. It's an unfortunate side effect of being able to apply arbitrary patches that non-functional/test fixes in PRs are often lower priority.

**Pull request closed without merging**
