### PR TITLE
[REF] initial extraction of loading saved mapping to qf format

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Minor extraction

Before
----------------------------------------
Less readable

After
----------------------------------------
Janky but in the right direction. The phoneType & imProvider stuff looks nasty but not more nasty

Technical Details
----------------------------------------

Comments
----------------------------------------
@colemanw

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
That's quite an argument list! Are you sure all of those params are necessary?

**Comment by eileenmcnaughton** [comment]
@colemanw no - I don't think they are - but I'm a strong believer you do the extraction as clean as possible and then start to clean up the params - otherwise the risk of mistakes is a lot higher

**Comment by eileenmcnaughton** [comment]
@colemanw this has passed now

**Pull request merged**
