### PR TITLE
CRM-17669 Add additional run frequencies for sched

### PR DESCRIPTION
**Pull request by konadave**
duled jobs.

---
- [CRM-17669: Add additional run frequencies for scheduled jobs](https://issues.civicrm.org/jira/browse/CRM-17669)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
jenkins, test this please

**Comment by eileenmcnaughton** [comment]
ok to test

**Comment by davecivicrm** [comment]
ok to test

**Comment by davecivicrm** [comment]
@konadave Thanks for working on this improvement! We are limiting 'new feature' changes to the upcoming 4.7 release - so closing this one in favor of https://github.com/civicrm/civicrm-core/pull/7404 (for 4.7). We also need some test coverage for this change and I think @eileenmcnaughton will be taking a look at that.

**Pull request closed without merging**
