### PR TITLE
dev/core#2676 SearchKit - Add LocBlock entity to display Event location data

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Allows Event location data (address, email, phone, im) to be searched on and displayed in SearchKit.

See https://lab.civicrm.org/dev/core/-/issues/2676

### CODE REVIEW

**Comment by seamuslee001** [comment]
Code looks right to me but will leave this open for @michaelmcandrew to review as well

**Comment by colemanw** [comment]
Ping @kurund

**Comment by michaelmcandrew** [comment]
@colemanw - I do not really know much at all about this part of the codebase so can't really be of much help. Nothing stands out in any case.

**Comment by colemanw** [comment]
@michaelmcandrew I think what Seamus was saying is that he reviewed the code but hasn't run it. If you can do so then his half and your half together would make a complete review and this can be merged.

**Comment by michaelmcandrew** [comment]
Got it - @kurund - could you test this as part of the relevant Omega issue.

**Comment by eileenmcnaughton** [comment]
@colemanw I just pulled this down as I thought it would be easy to verify but I'm seeing not seeing it

image

**Comment by colemanw** [comment]
@eileenmcnaughton see http://shouldiblamecaching.com

**Comment by eileenmcnaughton** [comment]
@colemanw yeah that was it

So this works but I hit a usability issue - as soon as I added 'address' it added a conditional on the location type. It took me a while to realise that was why no results were coming back. I doesn't seem to happen on email (And if we WERE to add some default conditional it would be is_primary not location type = billing)

image

**Comment by colemanw** [comment]
@eileenmcnaughton ok I've created #20803

**Comment by eileenmcnaughton** [comment]
OK - with that out of scope of this PR I'm happy to merge this one

**Pull request merged**
