### PR TITLE
Bump Minimum Required PHP to be 5.6

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This bumps the minimum required PHP version to be 5.6 as per https://civicrm.org/blog/eileen/end-of-life-plans-for-5x-php-versions-planning-for-70-eol

Before
----------------------------------------
Previously minimum php version was 5.5

After
----------------------------------------
Minimum php version is 5.6

ping @totten @eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 we should do this for sure. I think we should possibly also increase the   const MIN_RECOMMENDED_PHP_VER = '7.0'; variable - since this is the last month of php support for it

**Comment by seamuslee001** [comment]
@eileenmcnaughton are we prepared to recommend anything higher than 7.1 at this stage?

**Comment by eileenmcnaughton** [comment]
And in fact  const RECOMMENDED_PHP_VER = '7.1'; - we should be recommending php 7.2 now IMHO

**Comment by eileenmcnaughton** [comment]
ah snap - YES I think so  - there is the smtp password version but I think we just live with the advice that people re-save their passwords when updating to php 7.2

**Comment by seamuslee001** [comment]
done that now @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
OK - looks good to me!

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 this is the wrong branch I just realised - 5.9 will be the last php 5.5 supporting version

**Comment by seamuslee001** [comment]
@eileenmcnaughton switched to master

**Comment by seamuslee001** [comment]
Merging as per tag

**Pull request merged**
