### PR TITLE
CRM-21834 - Add "Submit Credit Card Registration" link to Register Event Participant screen

### PR DESCRIPTION
**Pull request by chitra1236**
Overview
----------------------------------------
Allow for cc registrations through the backend link is not showing at Register Event Participant

Before
----------------------------------------
"Submit Credit Card Registration" works for Contributions and Memberships but not Event Participant

After
----------------------------------------
"Submit Credit Card Registration" for Event participant should work same as Contributions and Memberships

Technical Details
----------------------------------------
changes in the template to show the link, rest functionality is already working

Comments
----------------------------------------
Unit test is already written at https://github.com/civicrm/civicrm-core/blob/master/tests/phpunit/api/v3/ParticipantPaymentTest.php

---

 * [CRM-21834: Add "Submit Credit Card Registration" link to Register Event Participant screen](https://issues.civicrm.org/jira/browse/CRM-21834)

### CODE REVIEW

**Comment by mattwire** [comment]
Jenkins add to whitelist

**Comment by mattwire** [comment]
@chitra1236 Hi, thanks for your contribution.  Any chance of a before/after screenshot?  You can do this quite easily with the chrome browser for example: 1. open dev tools (F12); 2. Click the arrow in top left "Select an element on the page"; 3. Hold down control key and drag the area you want to screenshot; 4. The screenshot automatically downloads as a png file!

**Comment by mattwire** [comment]
add to whitelist

**Comment by mattwire** [comment]
test this please

**Comment by mattwire** [comment]
jenkins, add to whitelist

**Comment by mattwire** [comment]
@seamuslee001 Thought I was able to add these to whitelist?  Can you?

**Comment by seamuslee001** [comment]
Jenkins add to whitelist

**Comment by eileenmcnaughton** [comment]
@chitra1236 the test error relates to this PR - are you still interested in following up on the steps to get this merged?

(@guanhuan - is this one of yours?)

**Comment by eileenmcnaughton** [comment]
I'm going to close this out since it's not review-ready (tests weren't passing) and the committer is not engaged at this stage.

The code is still tracked from the JIRA issue so can be resuscitated when someone wants to get a new PR review ready

**Pull request closed without merging**
