### PR TITLE
CRM-19418 - Cancelled Contribution Info Box not shown in non-english …

### PR DESCRIPTION
**Pull request by sluc23**

### CODE REVIEW

**Comment by colemanw** [comment]
@ixiam can you please update your copy of 4.6 and try again. Looks like there are merge conflicts.

**Comment by colemanw** [comment]
@civicrm-builder add to whitelist

**Comment by ixiam** [comment]
@colemanw  hmm that's weird.. I just used a fresh fork repo.. I don't see any error log in Jenkins where the conflict is.. I'll try again

**Comment by ixiam** [comment]
@colemanw I've found this in Jenkins log.. any idea what it means?

**Errors**

    No report files were found. Configuration error?

**Pull request closed without merging**
