### PR TITLE
CRM-19925 Bao updates

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Add entity data to fields array so it can be used in search etc without contortions to derive it. Also, add date format data to fields metadata

---

 * [CRM-19925: Add metadata to fields array with entity info & date format info](https://issues.civicrm.org/jira/browse/CRM-19925)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @yashodha @totten @colemanw @monishdeb - anyone have an opinion / concern with this - it will go stale very quickly so I want to resolve quickly.

This does not add any usage of the metadata

**Comment by eileenmcnaughton** [comment]
NB @seamuslee001 the date forma part was part of my revised fix for your bug....

**Review by seamuslee001 — APPROVED** [review]

**Comment by eileenmcnaughton** [comment]
Once merged @ErichBSchulz has pointed out the DAO section of this should be updated https://wiki.civicrm.org/confluence/display/CRMDOC/Database+Reference

**Comment by eileenmcnaughton** [comment]
@ErichBSchulz it was a bit of a lazy update but I got it done....

**Pull request merged**
