### PR TITLE
Afform - basic support for creating event participant

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
This is pretty basic, but it's a start, and checks a box on https://lab.civicrm.org/dev/core/-/issues/3761

Before
----------------------------------------
No Afform support for Events.

After
----------------------------------------
Basic support for adding a participant (unpaid).

Comments
----------------------------------------
Todo: Payment processor support.
Todo: Conditional custom fields (currently all participant custom fields are available even if they don't apply).
Todo: I think we need some kind of "workflow" mechanism in Form Builder to support stuff like waiting lists, provisional participants (requiring admin approval), and pending payments.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
retest this please

**Comment by wmortada** [comment]
* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __PASS__
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __PASS__: Fairly obvious how to add a participant to a form. Works as a user would expect.
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __PASS__ : I don't think documentation is needed at this stage. It's pretty straightforward.
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __PASS__: Created form with event participant field. Tested form submission. Participant was added to event. Note that the registered date and participant role were blank for the registered participants. See below for screenshots.
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __PASS__: New feature. No change to existing functionality.
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __PASS__
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __PASS__
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __N/A__

image

image


Suggestions for further improvement:

- The registered date should by default be set to the current date and time
- The participant role should by default be set to 'attendee'

**Comment by colemanw** [comment]
Thanks for the review @wmortada - reviewing PRs is extremely helpful to the project! :star: :star: :star: 

I'll work on adding those default values, I agree they would be beneficial.

**Pull request merged**
