### PR TITLE
Only call getGroupACLRoles if contactID is present

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Only call getGroupACLRoles if contactID is present

Before
----------------------------------------
I don't see how the query could ever return anything if contactID is not a number

After
----------------------------------------
Not called if contactID is not a number

Technical Details
----------------------------------------
@seamuslee001 I kept this small as it needs a bit of thinking through but I can't see a reason why it would make sense to call the function with no contactID

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton if the user is Anonymous then what would have been $contact_id here 0?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 that's why I moved that part back out of the function & to the calling function

**Comment by eileenmcnaughton** [comment]
@seamuslee001 did ^^ answer your question?

**Comment by seamuslee001** [comment]
yep i think this is ok merging

**Pull request merged**
