### PR TITLE
Migrate date field to datepicker on ChangeCaseType form

### PR DESCRIPTION
**Pull request by colemanw**
Migrates a field to datepicker and updates some old code.

Note: this form seems somewhat broken. The "reset timeline" option doesn't appear to do anything. Neither does the date field have any effect on anything as far as I can tell. But in my testing it's no more broken after this patch than it was before.

### CODE REVIEW

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by colemanw** [comment]
@demeritcowboy does this form actually work in your client's CiviCase? I'm wondering if the breakage was recent.

**Comment by demeritcowboy** [comment]
@colemanw It works in that install but note that by design it doesn't update any activities touched since creation, so only activities with is_auto=1 have the date changed. So maybe related to it not appearing to do anything in your case?

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by demeritcowboy** [comment]
Tested at http://core-13701-6uxs5.test-1.civicrm.org:8001. Seems to work as expected. Tested with both changing the type and date and then also just the date and not type.

initialstate

afterchangingdateandtype

**Comment by demeritcowboy** [comment]
Note I had to log in as admin since demo didn't seem to have access to anything in the cases menu or to even see the menu. That seems separate from this change though.

**Comment by colemanw** [comment]
Thanks for the testing @demeritcowboy 
@civicrm-builder retest this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Pull request merged**
