### PR TITLE
Remove code supporting no longer supported Joomla passwords (from Joomla...

### PR DESCRIPTION
**Pull request by elinw**
... 1.0) and fixing a Joomla 1.5 style query that won't work in 1.6+.

### CODE REVIEW

**Comment by elinw** [comment]
There is still a lot of old code in here (such as JRequest and version check for < 1.6 which is not supported) but also some really sad "Do Something" code where it's really not clear what is wanted or what the input params are supposed to represent e.g. loaduser($user)  (what is $user supposed to be? is the return supposed to be Boolean or is that just a place holder?).  If there was some clarification of what those are about probably they could be taken care of.

**Comment by colemanw** [comment]
Thanks @elinw! IMO code cleanup is always in season. In trying to figure out what some of that other code does, you might want to compare it to the same functions in CRM_Utils_System_Drupal from which it was no doubt originally copied.
If your ide and some grepping confirms that some broken code is completely unused (which would make sense if it is broken) I'd vote to just remove it.

**Comment by JSProffitt** [comment]
@elinw - Agreed that removing the JRequest should removed ASAP, as the filtering is better handled by JInput. Probably makes sense to just add a class properties for the application object and the input property into the constructor. I couldn't find any other need for the loaduser method, so it seems safe to remove completely. While removing the 1.6 check, it might also make sense to switch those URL replacements to use JURI::root() and JURI::base(true) to reduce the number of conditions.

**Comment by elinw** [comment]
It seems to me that we  could add a $user property and delete a lot of
duplicate JFactory::getUser()s.   THe loadUser() seems odd because it is
taking $user which is usually a JUser object and if it existed why would
you need to load it.  I could, on the other hand, see the need for it if
$user referred to the userid. (See my PR about REST authentication).

**Comment by lcdservices** [comment]
I concur. ;-)

**Comment by elinw** [comment]
Any thoughts on whether we need the setBreadcrumbs when it seems to me that the Civi breadcrumbs work just fine natively?   
I feel like we should also be able to use the native page title handling or at least copy it to here, so it works like a page title.

**Comment by elinw** [comment]
Also do you notice that the AddStyle etc methods don't have a weight argument?  Would it be smart to add a local constant?

**Pull request merged**
