### PR TITLE
set default values (if present) for state and country for new address block

### PR DESCRIPTION
**Pull request by sunilpawar**

### CODE REVIEW

**Comment by colemanw** [comment]
Sorry, this is now partially redundant due to #7773 - would you be able to rebase & squash this PR into one commit (no need for the extra whitespace commit) minus the inline form bit?

**Comment by nganivet** [comment]
Just merged this PR with the latest master.

**Comment by colemanw** [comment]
@nganivet thanks, but this now gives us 3 commits in the PR instead of one, and there's still the redundant line in CRM_Contact_Form_Inline_Address (which thanks to the merge you can now see in the diff). Would you or @sunilpawar be able to rebase/squash this branch?

**Comment by nganivet** [comment]
Deleted extra line, don't know how to squash but if you look at the changes tab all lok good, so you can just merge.

**Comment by colemanw** [comment]
1. The way to rebase is by doing: `git rebase -i c11f21f~1` and when it shows you a document listing commits, you should delete the ones unrelated to this PR (erase their lines), leave the first commit at "pick" and set the others to "squash".

2. Unfortunately this PR doesn't quite work right. See comments on the issue.

**Pull request closed without merging**
