### PR TITLE
Freeze readonly fields

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
alternate to https://github.com/civicrm/civicrm-core/pull/20197

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton as a follow-up (not a blocker) I think we should add `readonly` to the APIv4 output. Would it make more sense on `get` or `getFields`? And how should `set` be handled in the case of `readonly`?

**Comment by demeritcowboy** [comment]
Thanks @eileenmcnaughton this works for me and also still satisfies formRules etc.

@pradpnayak if you can confirm this also works for you then I think it's mergeable.

The `@todo` comment isn't necessary anymore in the trait, but that's minor.

**Comment by eileenmcnaughton** [comment]
@colemanw I guess it could work on getfields - it's just a getMandatory() look up when compiling

**Comment by colemanw** [comment]
Ok @eileenmcnaughton I added it to #20191

**Comment by pradpnayak** [comment]
Yes it does,

thanks @eileenmcnaughton  and @demeritcowboy

**Pull request merged**
