### PR TITLE
(WIP) CRM-20533 index fixes

### PR DESCRIPTION
**Pull request by aydun**
Alternative approach to fixing index creation problem relating to FK's  - see CRM-20533 for discussion

---

 * [CRM-20533: 'Update Indices' System Status action can get tied up \(index name already exists, localised dbs?\)](https://issues.civicrm.org/jira/browse/CRM-20533)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit @aydun is this superceded by the fix already merged?

**Comment by aydun** [comment]
@eileenmcnaughton your simple question consumed much of my day :-) 

I've been back over the changes, fixes, reports, suggested fixes etc and I think I see a way forward.  This PR is not superceded by the merged fix although having looked at it again, it needs a few changes.  The fix so far drops indexes before re-creating them but does not the address the problem of indexes used in foreign keys.

To recap so far:
- index definitions have changed over time so the indexes in code may not exist or may not match actual indexes in the DB
- checks were added to compare the intended and actual indexes and attempt to fix them
- the first version of the code corrected missing indexes but did not check for existing index names resulting in failures
- fixes have been added to drop index names before creating them, which addresses some of the problems
- however, attempts to drop some indexes fail if they are used in foreign key constraints

Part of the difficulty here is the 'smart' way that MySQL handles indexes for foreign key constraints:
From https://dev.mysql.com/doc/refman/5.7/en/create-table-foreign-keys.html  Referring to the constraint definition "The index_name value is ignored if there is already an explicitly defined index on the child table that can support the foreign key. Otherwise, MySQL implicitly creates a foreign key index..."  So we don't know from the constraint definition whether an index will be created for the FK or whether it will use an existing explicit index.

If an explicit index is being used in a constraint then attempts to drop it result in errors.  Approaches so far include:

1) One suggested approach is to set foreign_key_checks=0.  Disabling the check seems a risky approach for data integrity and according to a note at https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_foreign_key_checks, it will not work for some versions: "As of MySQL 5.7.5, dropping an index required by a foreign key constraint is not permitted, even with foreign_key_checks=0. The foreign key constraint must be removed before dropping the index (Bug #70260)."

2) As indicated by the previous point, the FK constraint could be dropped.  The sequence is: drop constraint, drop explicit index, create new explicit index, add constraint.  However, our starting point is to change the explicit index that just so happens to be being used to satisfy a FK constraint.  We need to identify what the constraint is so that it can be re-created.  There is a risk that one of the drop index/create index/add constraint steps fails leaving the database in a worse state without the FK constraint.  This approach would then need to expand the schema reconciliation to verify that all constraints are correct as well as the indices.  While that may be a useful check to add this approach potentially causes more problems than it solves.

3) Dropping the explicit index only causes problems if it is the only index supporting the foreign key, so another approach is to create a new index that supports the constraint.  The solution then is to create the new FK index, drop and recreate the explicit index.

The approach in this current PR is to explicitly create FK_* indices first so that constraints are satisfied by those, then adjust the explicit indexes.  However, that is done for all tables and FK's.  That has the effect that a freshly installed system complains about missing indices and 'fixing' them results in unnecessary indices.

I have not found a way to determine whether an index is the only one satisfying a FK, so the approach may need to be try dropping it, catch the error and then try other things.  Note that there is additional information in information_schema.innodb_sys_foreign and information_schema.innodb_sys_foreign_cols but querying that requires 'process' privilege which may not be available.

So maybe the logic should be:

```
If index is missing, create it - no problems.
If index name exists with wrong specification:
  try to drop current index
  if ok:
    // simple case
    create new index
  else:
    // the index is used in FK so rename it, create new and drop old
    // mysql 5.7 has index rename but not in earlier versions
    create tmp index as copy of current
    drop current index
    create new index
    try to drop tmp index
    if ok:
      // the new index satisfies the FK, so we're done
    else:
      // the new index does not satisfy FK, so create explicit FK index
      create FK index for columns involved
      try to drop tmp index
      if ok:
        // all done
      else:
        // some other problem ...
        log details
```

I'll try adjusting my code to match ...

**Comment by eileenmcnaughton** [comment]
Wow - thanks for the great analysis @aydun and for taking the time to understand what the vague & confusing reports were

**Comment by seamuslee001** [comment]
So really the biggest problem we got now is where we are trying to alter an index that is used in a FK (which i think is the case in civicrm_case_contact setting that to be unique index)

**Comment by eileenmcnaughton** [comment]
I guess it's also an option to come up with a routine specific to one known problematic index

**Comment by eileenmcnaughton** [comment]
@aydun I'm going to close this because a replacement PR can be created & we don't need this open to continue to comment on it. Note that #11250 has just been merged so any error messages will only show if you revert that.

**Comment by colemanw** [comment]
I'm curious to know why we can't temporarily disable FK constraints while rebuilding indexes.

**Comment by eileenmcnaughton** [comment]
I think there is mention above that not all DBs permit it

**Comment by colemanw** [comment]
Ok, another thought - if the problem only affects old versions of mySql, we could just tell people to upgrade if they encounter a missing index error and the auto-repair function fails.

**Pull request closed without merging**
