### PR TITLE
[Smarty variables] - remove isset

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
[Smarty variables - remove isset

Before
----------------------------------------
fatal with smarty escape on output

After
----------------------------------------
works

Technical Details
----------------------------------------
@demeritcowboy is this ever set? I couldn't find it...

Comments
----------------------------------------

### CODE REVIEW

**Comment by demeritcowboy** [comment]
It used to be here but then seems to have magically disappeared after this:
https://github.com/civicrm/civicrm-core/blob/4466c37a948395c3a1fd32b08a0dcda39f983287/templates/CRM/HRDCase/Form/CaseView.tpl#L42

**Comment by eileenmcnaughton** [comment]
@demeritcowboy I think I can remove that bit-of-if then

**Comment by eileenmcnaughton** [comment]
@demeritcowboy updated

**Comment by demeritcowboy** [comment]
Silly question - what page is this tpl used on?

**Comment by eileenmcnaughton** [comment]
@demeritcowboy I think a basic find activities hits this - try adding this to civicrm.settings.php 

```
define('CIVICRM_SMARTY_DEFAULT_ESCAPE', TRUE);
```

and deleting templates_c

(note anything you hit right now when you do that likely has an open PR right now)

**Comment by demeritcowboy** [comment]
I tried Find Activities, also advanced search displayed as activities, all the case-y screens, and the contact activity tab. I put some markup in the tpl and it never showed up.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy I did hit it - I thought it was in manage case or something - did you try with the define set?

**Comment by demeritcowboy** [comment]
With the define, even clearing templates_c, I don't hit this. I'm not sure this file is used anymore, e.g. just grepping https://github.com/civicrm/civicrm-core/blob/34f8a8ae95e1f08cfa567a103adb6fd78e3b7681/templates/CRM/Activity/Page/Tab.tpl#L20

**Comment by eileenmcnaughton** [comment]
hmm - I could swear I hit it - although my head is spinning - I'm down to just one isset (and 20 open PRs)

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
unrelated fail

**Pull request merged**
