### PR TITLE
dev/core#2650 dev/core#2814 Add support for preferred syntax for contact tokens

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
dev/core#2650 dev/core#2814 Add support for preferred syntax for contact tokens #21570

This adds support for the new unambiguous syntax such as `{contact.prefix_id:label}`. The previous labels like `{contact.individualPrefix}` still work - but are not 'advertised'

Before
----------------------------------------
Only legacy style tokens work, legacy style tokens advertised

After
----------------------------------------
legacy AND new style tokens work, new style tokens advertised

Technical Details
----------------------------------------
This is a step towards switching to apiv4. An important difference with v4 is
that we can distinquish between 'not fetched' and 'empty' - saving us
from extra queries when it is not clear - which will in turn
allow us to switch greeting
processing over & still support the performance tweaks via
that method

Next steps:

-  to move the contact part of this out of the TokenCompat subscriber into a token class
- add more logical support for location tokens (we talked about `{primary_address.street_address}` where the api join specifies `primary_address` as the table.
- switch `replaceGreetingTokens` over to use the processor

Comments
----------------------------------------
@seamuslee001 @colemanw I think this is mergeable now - test cover ensures the legacy ones still work.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@totten are you ok with merging this & pushing out thinking about where to handle deprecated - this at least starts to list them out which is a required step & adds the test cover

**Comment by colemanw** [comment]
I'm all in favor of the new syntax and the test coverage looks good. I think this is merge-ready.

Just curious to know why the function `getContactTokens()` outputs field labels without running them through `ts()` - what are those labels used for? IMO if we did want to translate them we shouldn't hard-code it in this function but should use APIv4 `getFields` to provide the labels.

**Comment by eileenmcnaughton** [comment]
@colemanw yeah - I copy-pasted them in from where they were coming from - but the goal is to switch over to that over the next few refactor PRs

**Comment by eileenmcnaughton** [comment]
@colemanw if you merge this then I will sort out the labels before the rc is cut - it will become easy once the class separation etc has been done

**Comment by colemanw** [comment]
Deal.

**Comment by magnolia61** [comment]
Would it take much to support :label & :name syntax also for custom tokens and other entities?

**Comment by eileenmcnaughton** [comment]
@magnolia61 so for other entities - no that pretty much works for everything (except maybe contact now) - for custom tokens - that might take a be more

**Comment by eileenmcnaughton** [comment]
@magnolia61 oh hang on - I just realised - this PR IS for contact tokens so I obvious did do them :-)

**Pull request merged**
