### PR TITLE
CRM-20474 update UFField form to use api.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
This removes the UFField::Add function, only called from the form & create. Create it still pretty jumbled, but all
in one place now

---

 * [CRM-20474: Refactor UFField api to follow standard api \/ BAO format](https://issues.civicrm.org/jira/browse/CRM-20474)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit are you able to QA this? If this works ok then I'll close out the issue & leave it at that

Basically I've changed the form to use the api

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by jitendrapurohit** [comment]
Seems to be working fine. Just got an e-notice after adding `Formatting` field to a profile.

>Notice: Undefined offset: 1 in CRM_UF_Form_Field->postProcess() (line 534 of /Users/jitendra/src/civicrm/CRM/UF/Form/Field.php).

**Comment by eileenmcnaughton** [comment]
just pushed a fix for the enotice

**Comment by seamuslee001** [comment]
Test this please Jenkins

**Review by jitendrapurohit — APPROVED** [review]
This can be merged now. Thanks @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
Thanks @jitendrapurohit (@saurabhbatra96 I finally got the bulk of this work you did merged!)

**Comment by saurabhbatra96** [comment]
Thanks, haven't​ been active on Github for quite some time, should catch up some time!

**Pull request merged**
