### PR TITLE
Permit additional (freeform) relative date filters - e.g 'last 18 months', 'last 45 days'

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Genericise 'ending' date filter and add tests

Adds unit tests for date filters of the type 'ending' and adds more options - that are not exposed in the UI but could be exposed via an extension or the api

Before
----------------------------------------
The following 'ending' options work from date filters but have no tests
```
Last 60 days including today	ending_2.month
Last 2 years including today	ending_2.year
Last 3 years including today	ending_3.year
Last 30 days including today	ending.month
Last 90 days including today	ending.quarter
Last 7 days including today	ending.week
Last 12 months including today	ending.year
```

After
----------------------------------------
The above options still work and have unit tests

In addition it is possible to add additional 'ending' filters into the civicrm_option_value table and they will work in the UI - e.g

screenshot 2018-08-17 15 13 55

results in 

screenshot 2018-08-17 15 14 36

The additional filters supported are
```
ending_n.month
ending_n.week
ending_n.year
ending_n.day
ending_n.quarter
```
Where n can be any number. The choice of label is up to the person adding them.

Technical Details
----------------------------------------
Currently we have hard coded variants of 'ending_2.year' for 'Last 2 years including today' and
for month, week and quarter we support last month ending today etc. 

There is a complexity in that the current month entries are
```
ending_2.month = 'Last 60 days ending today'
ending.quarter = 'Last 90 days ending today'
```
I think it was done this way primarily to get the language right but as the period gets longer
(my interest is in supporting 18 months) the mismatch between 30 days & a month becomes more & more of an issue.

I actually feel a pretty good case could be made for replacing the default
entries so instead of

```
ending_2.month = Last 60 days including today
```
we would have
```
ending_60.day = Last 60 days including today
```
(I would probably do that on new installs only if we go that way)

Comments
----------------------------------------
I haven't focussed on any code rationalisation as I wanted to keep this to
additional code not changes to current & discuss / agree if this approach (ie. for the 'n'
entries we are respectful of actual month lengths & we leave it to future option value
enterers to worry about the wording.

@MegaphoneJon @magnolia61 @joannechester you have all had a role in previous work around these filters

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon @magnolia61 any chance either of you can chime in on the appropriateness of my calculations etc

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon I was hoping to discuss this with you....

**Comment by MegaphoneJon** [comment]
I was guiltily eyeing this today!  I'll do my best to make time on this tomorrow.

**Comment by eileenmcnaughton** [comment]
thanks @MegaphoneJon it does need a little bit of thought (aka coffee) around the interpretations (given the 30 days assumption previously) so .... coffee

**Comment by MegaphoneJon** [comment]
After a moment's reflection, I thought, "Of COURSE @eileenmcnaughton wants me to review this PR".  So I did.

My primary concern here is that we're locking in the incorrect behavior for months with a test.  I would feel better if we were NOT testing the `ending.month` and `ending_2.month` scenario.  I would feel better still if we allowed passing in the datetime per my last comment, so we could actually test with absolute dates.

Tangentially, just yesterday I was writing some custom code to pull dates that amounted to "last 12 calendar months not including the one we're currently in" (e.g. on "2018-09-07" relative dates would be "2017-09-01 to 2018-08-31").  It was as simple as:

```php
    $startDate = (new DateTime('first day of this month last year'))->format('Y-m-d');
    $endDate = (new DateTime('last day of last month'))->format('Y-m-d');
```

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon I updated so that we are testing the day variants & adding the day variants on new installs and I altered the descriptor on new installs. I left a couple of things out of scope.

1) adding the day variants on new installs & renaming the month variants to say 'last one month". I think we could get away with that with an upgrade message. We couldn't remove the current month variant in case it is used in reports / smart groups already. I note that I only focussed on 'ending' & 'starting' still exists so I think the change can wait for another round.

2) relative dates seems easy enough to add but I didn't want to rewrite the tests right now.


++ b/CRM/Utils/Date.php
@@ -1083,12 +1083,14 @@ class CRM_Utils_Date {
    *   Relative time frame: this, previous, previous_1.
    * @param int $unit
    *   Frequency unit like year, month, week etc.
+   * @param string $relativeToDate
+   *   Date for the range to be relative to, in a format understood by strtotime.
    *
    * @return array
    *   start date and end date for the relative time frame
    */
-  public static function relativeToAbsolute($relativeTerm, $unit) {
-    $now = getdate();
+  public static function relativeToAbsolute($relativeTerm, $unit, $relativeToDate = 'now') {
+    $now = getdate(strtotime($relativeToDate));
     $from = $to = $dateRange = array();
     $from['H'] = $from['i'] = $from['s'] = 0;
     $relativeTermParts = explode('_', $relativeTerm);
(END)

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by magnolia61** [comment]
Not sure if this is 100% related but some relative filters seem to got broken after some changes in May: https://lab.civicrm.org/dev/core/issues/438

**Comment by eileenmcnaughton** [comment]
@magnolia61 ok - this isn't actually merged yet.... but are you on the latest?

**Comment by MegaphoneJon** [comment]
I'm so sorry I haven't had a chance @eileenmcnaughton - but I've bumped this up in my priority.  I'm busy so I haven't had time for pro-bono work outside of governance, but I know this has sat.

**Comment by eileenmcnaughton** [comment]
Just a note that the https://lab.civicrm.org/dev/core/issues/438 is unrelated

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon how is that list looking?

**Review by MegaphoneJon — APPROVED** [review]
OK, I got a chance to look at this tonight and I'm satisfied.  I'll note that `CRM_Utils_Date::relativeToAbsolute('ending', 'day')` gives an unexpected result:
```
~dmaster(branch:master*) » cv ev 'return CRM_Utils_Date::relativeToAbsolute('ending', 'day');'
{
    "from": "20181108000000",
    "to": "20181107235959"
}
```
but that doesn't seem to affect anything else, and that's not an option someone would pick since "today" is an option.

**Comment by eileenmcnaughton** [comment]
Thanks @MegaphoneJon  !

**Comment by sluc23** [comment]
Hi @eileenmcnaughton , will this PR allow to create custom time filters within extensions, or am I misunderstanding the scope of this? 
In that case, how would it be created in the extension? 
(In my case a customer asks us to add "Last 9 months including today" filter)

**Comment by eileenmcnaughton** [comment]
@magnolia61 I didn't tackle ending_n.fiscal_year - or a bunch of other possible alternatives

**Comment by magnolia61** [comment]
I added a freeform relative date filter for "This Fiscal Year". https://github.com/civicrm/civicrm-core/pull/13440 After giving it some thoughts it does not seem desirable to have a ending_n.fiscal_year. It just does not make sense. What we needed was This and x fiscal years back. Hope I used to code logic well enough, it works perfectly for us. If someone could take a look at the logic I used, I could change the other filters for 'this' (for year, month, etc)

**Pull request merged**
