### PR TITLE
CRM-21297 - Automatically fill database details in Drupal installer

### PR DESCRIPTION
**Pull request by wmortada**
Overview
----------------------------------------
The installer should obtain the database settings and populate these fields in the installer when installing on Drupal.

Before
----------------------------------------
The installer for WordPress automatically completes the database settings.  This isn't currently the case for Drupal.

After
----------------------------------------
 * The database fields in the installer are automatically populated.
 * The installer requires that the user be logged in as a Drupal administrator (`administer site configuration`).

---

 * [CRM-21297: Automatically fill database details in installer for Drupal](https://issues.civicrm.org/jira/browse/CRM-21297)

### CODE REVIEW

**Comment by totten** [comment]
@kcristiano, your work on WP installer has been an inspiration -- William here at the Devon sprint is making a similar improvement for Drupal. :)

**Comment by kcristiano** [comment]
@totten Test patch on a WP install (buildkit and manual).  Installer worked fine.   Would be a good idea to test an install on Joomla as well - back when I added this we broke Joomla for a bit if I recall correctly.   @wmortada nice work!

**Comment by totten** [comment]
Cool @kcristiano . I was just building tarballs so that I could try out a fresh build for each CMS. Will post back when I've got a result.

**Comment by kcristiano** [comment]
Can you share the tarballs? I have quite a number of different wo configurations I can test against @totten

**Comment by totten** [comment]
Correction: My test machine runs MySQL on a ramdisk, and it filled up, causing the failures. 

In actuality, both WP zip and Joomla zip are installing. WP is 👍 . Joomla is throwing some unfamiliar warnings (although I suspect these aren't the fault of this patch).

**Comment by wmortada** [comment]
Thanks @kcristiano and @totten.  I've made the suggested changes.

**Comment by totten** [comment]
I just wanted to add some more notes about what happened as work progressed at the sprint. We found that the patch could (in some circumstance) expose the DB credentials on a new site to non-admin users -- which would be a problem.

The same issue doesn't affect WP because the WP admins cannot directly visit `civicrm/install/index.php` -- doing so produces a failure. Rather, the WP admin must first activate Civi in the WP "Plugins" screen and then click a link to open an embedded page that incorporates `install/index.php`.

To resolve this for Drupal, we wanted to add a permission check so that `install/index.php` could only be used by Drupal admins -- William started working on a way to get that running, but (towards the end of the sprint, as time was running out) ran into an issue WRT to session management. (`install/index.php` stores some data in a session-variable, and the timing of this doesn't line up well with the bootstrap.) It should be resolvable but needed a bit more time.

**Comment by wmortada** [comment]
Thanks @totten.  I have done some more work on this and think I have now got this working.  I wanted to do some tests before committing another update.

**Comment by wmortada** [comment]
I've edited the code so the install type is now stored in POST rather than SESSION.  I could then remove the session from the start of the script and add in the code to bootstrap Drupal and get the user.

This works in a standard Drupal install in CiviBuild but I haven't tried this with Drupal installed in a subfolder (or any other configuration).  I'd appreciate other people checking this out to see if it works for them.  Thanks!

**Comment by wmortada** [comment]
We should also change the text on the installer page to make it clear that the database connection settings have been pre-filled with the Drupal database settings but these can be changed if the user wants to use a separate database.

**Comment by totten** [comment]
Nice. I've retested installation on each CMS. Drupal has the improvement (and does require an authorized user). Backdrop and Joomla appear to work as before. WordPress is currently being problematic:

screen shot 2017-10-18 at 2 35 39 pm

(The "100" is a debug code that I hacked in. It showed that the error was being raised toward the end of `wp-admin/includes/menu.php`.)

I haven't determined *why* this PR causes that symptom, but I have verified that:
 * The problem occurs when installing the patched `.zip`
 * The problem does not occur when installing the [latest nightly/master `.zip`](http://download.civicrm.org/latest).

Any thoughts @wmortada @kcristiano?

**Comment by kcristiano** [comment]
@totten First off that CiviHydra is neat!

I ran the test and my suspicion is that the js redirect we do after the install is what is throwing the error. That is where I see the error, the redirect looks like it fails and sends us back to the installer which is done.

 When we redid the installer the last thing we added was a redirect to the `wp-admin/admin.php?page=CiviCRM`  I will try and find the redirection code and test with it off.

**Comment by kcristiano** [comment]
@totten @wmortada in WP the issue is in https://github.com/civicrm/civicrm-core/blob/master/install/index.php#L1705 or https://github.com/wmortada/civicrm-core/blob/bb79149d74998c12cb0a8370b0c5b7f4c01026b3/install/index.php#L1716 in this PR.  

As to why the redirect fails is beyond me right now.  That was not changed.   The redirect was problematic to get working when it was added, but it has worked until now.   Any input would be appreciated.

**Comment by kcristiano** [comment]
@totten https://github.com/kcristiano/civicrm-core/commit/8c55161b2233ecfab800aae723bfea40ab194490  Fixes the redirect on WP on my local.   I expect I should send a PR to the @wmortada 's Fork but I am not seeing an option to do am PR to that fork (I see tons of others but not that one).   Let me know the best way to get this code where we can test via CiviHydra

**Comment by totten** [comment]
@kcristiano Confirmed that 8c55161 fixes WordPress install UX. 

@wmortada I've cherry-picked the above and appended to your PR's branch (`CRM-21297`). It now appears as 138a796.

The last patch is clearly scoped in a way that only applies to WordPress code (within the block `elseif ($installType == 'wordpress') {...}`), so I don't think we need to retest other CMS's.

**Comment by kcristiano** [comment]
Thanks @totten I need to figure out the git commands that allowed you to do that.

I will rebuild the WP install media and test on all my configurations.  As 4.7.27 includes all of the changes this will be good to test.   None of the changes affects what was merged for WP, but I'd rather be safe than sorry.  Based on the time line I am thinking this would be for 4.7.28 or the December release?

Thanks @wmortada for this work - it's a great improvement.

**Comment by totten** [comment]
I successfully tested D7 installer in an extra configuration. (I usually test on MAMP with mysql on an alternative port. The new test was on Ubuntu 16.04 with mysql on the implicit/default port.)

@kcristiano To cherry-pick from your repo, I used [hub cherry-pcik <url>](http://hub.github.com/) - ie `hub cherry-pick https://github.com/kcristiano/civicrm-core/commit/8c55161b2233ecfab800aae723bfea40ab194490`

If @kcristiano feeds back with success on his next test, I think we're ready to merge.

**wmortada** said:
> We should also change the text on the installer page to make it clear that the database connection settings have been pre-filled with the Drupal database settings but these can be changed if the user wants to use a separate database.

This is optional and at your discretion. IMHO, the general layout/behavior is just as clear as before, and we should be careful about over-tuning the text. (The same installer UI is still used for Backdrop -- which still defaults to dummy values.) We can certainly hold the PR open a bit longer if you prefer, or we can merge this and handle the text changes as a separate PR.

**Comment by kcristiano** [comment]
@totten My tests show this is working for WP, both a standard install and WP in its own directory as described here: https://issues.civicrm.org/jira/browse/CRM-17633  

I agree we are ready to merge

**Comment by wmortada** [comment]
Thanks @totten and @kcristiano!  I'm happy to go ahead with the merge if you are.

I will have a look at the installer text separately. In any case I've added a [separate issue](https://issues.civicrm.org/jira/browse/CRM-21299) for implementing the same functionality for Backdrop. I've already started work on this and it should be fairly similar to the code for Drupal.  I wanted to get the code for Drupal right first before submitting a pull request for that.

**Comment by herbdool** [comment]
@wmortada thanks for working on the Backdrop PR as well! I can test when ready.

**Comment by wmortada** [comment]
@herbdool no worries.  I'm afraid I haven't got much further with this since October but it's on my to do list to look at.

**Pull request merged**
