### PR TITLE
CRM-18303 - Reload contribution object after update

### PR DESCRIPTION
**Pull request by mjwright**
When completeOrder() was moved out of the BaseIPN class it was modified to use civicrm_api3('Contribution', 'create', $contributionParams) instead of $contribution->save(). Other downstream code needs the $contribution object to contain the completed transaction, so it must be reloaded after the API call.

---
- [CRM-18303: Online pledge payments paid through payment processor never complete](https://issues.civicrm.org/jira/browse/CRM-18303)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Could we move the loading to the sendMail function? Make it more standalone with less stuff passed in? Would improve testability if we did

**Comment by eileenmcnaughton** [comment]
(as an aside $contribution->save bypasses hooks which was the reason to ditch calls to it)

**Comment by mjwright** [comment]
In addition to sendMail, the loading is needed by updateRecurLinkedPledge (and maybe addActivity?).  There is probably a lot that could be reworked here.

**Comment by eileenmcnaughton** [comment]
Note I've added https://github.com/civicrm/civicrm-core/pull/8057 for the pledge side of this...

**Comment by eileenmcnaughton** [comment]
I just realised the test failures on this do actually seem to be regressions / blockers to merging it. 

I'm not sure of the cause of the test fails ATM

The other PR now sets the contributionStatusID more consistently.

**Comment by eileenmcnaughton** [comment]
The handling for contribution_status_id is now in this PR https://github.com/civicrm/civicrm-core/pull/8092 (which hopefully passes tests).  What I really want to do is get some more tests in there to replicate the formatting issue around the dates so we can lock in a fix. Hopefully we can work through that in Tim's new working group QA process

**Comment by eileenmcnaughton** [comment]
Closed in favor of PR 8053

**Comment by eileenmcnaughton** [comment]
damn wrong one!

**Comment by monishdeb** [comment]
Closed in favour of https://github.com/civicrm/civicrm-core/pull/8107

**Pull request closed without merging**
