### PR TITLE
CRM-12326 quicksearch speed improvements

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Plus tests to cover CRM-17023, CRM-10687 (partially - this ticket added no tests & this PR backfills it somewhat )

---
- [CRM-12326: Name&email search is not using indexes correctly](https://issues.civicrm.org/jira/browse/CRM-12326)
- [CRM-17023: ExactFirst doesn't work in quicksearch](https://issues.civicrm.org/jira/browse/CRM-17023)
- [CRM-10687: Allow quicksearch by multiple fields](https://issues.civicrm.org/jira/browse/CRM-10687)

### CODE REVIEW

**Comment by kurund** [comment]
jenkins, test this please

**Comment by eileenmcnaughton** [comment]
Per feedback from @seamuslee001 ACLs need review on email part of query

**Comment by eileenmcnaughton** [comment]
OK I've added more tests & ACL handling.

@seamuslee001 wanna give it a go again. I'm targetting 4.7 & Fuzion 4.6 repo for this (not 4.6 core )

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
feedback on this is good. test fail is unrelated

**Pull request merged**
