### PR TITLE
[REF] [Import] [Custom] Remove another in-between class

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
A universe search shows no other references

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton can you rebase this one?

**Comment by eileenmcnaughton** [comment]
@colemanw rebased

**Comment by colemanw** [comment]
Seems like for consistency with the other names, the class which should be getting deleted is `CRM_Custom_Import_Parser_Api`. All the other import parser classes end with `_Parser` not `_Parser_Api`.

**Comment by eileenmcnaughton** [comment]
@colemanw `CRM_Custom_Import_Parser_Api` is the class which is in use... I haven't changed the in-use class for any of them - I've been removing the unnecessary in-between parent layer. If I change the final class name then that is a bigger change as it's renaming the in-use class

**Comment by colemanw** [comment]
@eileenmcnaughton ok. But needs another rebase :(

**Pull request merged**
