### PR TITLE
CRM-20273 Added credit card type field for contribution details report

### PR DESCRIPTION
**Pull request by Edzelopez**
* [CRM-20273: Add credit card type field for Contribution Details Report](https://issues.civicrm.org/jira/browse/CRM-20273)

### CODE REVIEW

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by monishdeb** [comment]
Tested, working fine
image

**Comment by eileenmcnaughton** [comment]
@monishdeb looks like this one missed the shared join function

**Comment by monishdeb** [comment]
@eileenmcnaughton updated and tested the PR

**Pull request merged**
