### PR TITLE
CRM-21587, Notice error for Grant date fields

### PR DESCRIPTION
**Pull request by pradpnayak**
* [CRM-21587: Notice error for grant date fields](https://issues.civicrm.org/jira/browse/CRM-21587)

### CODE REVIEW

**Comment by pradpnayak** [comment]
closing in favour of https://github.com/civicrm/civicrm-core/pull/11445

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
Code looks good - can you squash to one commit. Per #11445 this appears to have been reviewed & just needs to have a quick UI test on import / export. I think this is pretty low risk & am happy to accept that test being done by another dev @ JMA & to merge once that is confirmed

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
I just did a quick export test - no noticeable change so am merging. (using squash which doesn't give as good a history as if the submitter squashes but letting that slip )

**Pull request merged**
