### PR TITLE
Fix Fatal error on membership detail report (with ACLs enabled) dev/core/#100

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
@MegaphoneJon per #12144 backport of #12094

### CODE REVIEW

**Comment by seamuslee001** [comment]
are we back porting to 5.2 or 5.1?

**Review by seamuslee001 — APPROVED** [review]

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon it seems we have to do a second point release as there was a bug in the previous. You are right - this is a bit borderline but I like the idea of have no known recent regressions in our latest published version & get to that baseline

**Comment by eileenmcnaughton** [comment]
& yes @MegaphoneJon if you are able to test it - I had the fix about 2 months ago TBh but no-one to test if for me :-(

**Comment by MegaphoneJon** [comment]
Well - the good news is that this works when applied to a 5.1.0 site.  I guess I'm a little mystified by it - I can see that when `from()` is called, `$this->_aclFrom` isn't defined, so I'm not sure why it's still referenced.  Still - this fixes the problem and ACLs are respected, so I can't complain.

**Comment by eileenmcnaughton** [comment]
:-) - I think the buildACL is burried a bit deeper now

**Pull request merged**
