### PR TITLE
Disable failing test in PR runs for now

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
All tests are failing on this today - let's suppress it for now - we can unsuppress once resolved but this test is really gonna rely on @totten or @mlutfy to resolve

### CODE REVIEW

**Comment by mlutfy** [comment]
@eileenmcnaughton @totten I think we can completely remove this test, since `civicrm-setup` does not require these files anymore? (towards deprecating the old installer)

**Comment by eileenmcnaughton** [comment]
It wouldn't be missed....

**Comment by totten** [comment]
> (@mlutfy) I think we can completely remove this test, since civicrm-setup does not require these files anymore? (towards deprecating the old installer)

 I'd agree that the files are deprecated - but in my copy of `universe`, all variants of `civicrm.drush.inc` still use `$sqlPath . '/civicrm_data.' . $lang . '.mysql'`. I don't think they're inert yet? (Does Aegir still rely on that the installer from `civicrm.drush.inc`?)

**Comment by mlutfy** [comment]
@totten Yep good point - I opened an issue here: https://lab.civicrm.org/dev/drupal/-/issues/193

and created a few PRs to work towards that.

Aegir does not use this code for Drupal8+, but for Drupal7 it was still being used. I don't think many people use it though, except .. CiviCRM Spark and a handful of Symbiotic clients.

**Comment by totten** [comment]
This was backported to 5.69, so it'll show up in those release-notes. Just noting that I think the test-failure points to a data problem. I've split off separate issue about that (https://lab.civicrm.org/dev/translation/-/issues/84). For `5.69.5`, I'm planning to manually override `civicrm-5.69.5-l10n.tar.gz` with the dataset from `5.69.4` (*with adapted version-number*).

**Pull request merged**
