### PR TITLE
Add metadata so Activity Created Date is available in Form Builder

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes https://lab.civicrm.org/dev/core/-/issues/3002

Before
----------------------------------------
Created Date, Modified Date not available when adding exposed filters in a search form.

After
----------------------------------------
Now it is.

Comments
-----------------------------------
The purpose of this PR is to make these fields available as search filters, but the upshot is that one of the two will now be available on CRUD forms as well.
The `modified_date` is flagged `readonly` which stops it from being available on CRUD forms, but `created_date` is technically editable and will now be available. I think it's a rare but valid use-case where you want to edit the `created_date` of an activity, e.g. when importing old data.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw should these be availble? These are intended to be updated by triggers  - on modified_date in particular I think input would be ignored if less recent that the data entry time

@seamuslee001

**Comment by colemanw** [comment]
@eileenmcnaughton I updated the description ^ you're right `modified_date` shouldn't be editable, but it won't be because of the `readonly` flag.

**Comment by eileenmcnaughton** [comment]
OK - I guess this is fine - I think we don't normally expose created_date because that is a db action but if no one has objectsion then it's OK @demeritcowboy  @mattwire @jitendrapurohit

**Comment by colemanw** [comment]
@eileenmcnaughton I don't hear any objections

**Comment by eileenmcnaughton** [comment]
ok

**Pull request merged**
