### PR TITLE
CRM-18438: Default currency shown in contribution selector

### PR DESCRIPTION
**Pull request by yashodha**
---
- CRM-18438: Default currency shown in contribution selector
  https://issues.civicrm.org/jira/browse/CRM-18438

### CODE REVIEW

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by yashodha** [comment]
Jenkin test this please

**Comment by yashodha** [comment]
this is a regression caused by https://github.com/civicrm/civicrm-core/commit/c7940124e4599b93915192005b450c4ccc9b7c53  where return properties have been shrunk to bare minimum.

**Comment by rohankatkar** [comment]
Webtest is added for same at: https://github.com/civicrm/civicrm-core/pull/8184

**Pull request merged**
