### PR TITLE
dev/mail/15 deal better with spaces in from email address

### PR DESCRIPTION
**Pull request by michaelmcandrew**
see https://lab.civicrm.org/dev/mail/issues/15

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@michaelmcandrew a) thank you very much & b)regex changes are scary - can we spin the regex into it's own function & add a test that iterates through a few strings?

**Comment by seamuslee001** [comment]
Also @michaelmcandrew should we go through the databases and run this in an upgrade as well?

**Comment by michaelmcandrew** [comment]
@eileenmcnaughton - I've extracted it to a function and added a unit test.

@seamuslee001 - I don't think it is worth the risk of introducing a bug to the upgrade script since

1) it is a real edge case that people have two spaces in their from email (and as eileen said, could be argued this is a misconfiguration)
2) we are now santizing on input, and also correcting on output. the only time this would be an issue is if someone had already scheduled an email with a double space email address. they can fix it after upgrading by simply editing the email which will force the value to be recalculated. it will not affect any subsequent emails.

**Comment by eileenmcnaughton** [comment]
@michaelmcandrew test fail relates

PHP Fatal error:  Call to protected method CRM_Admin_Form_Options::sanitizeFromEmailAddress() from context 'CRM_Core_OptionGroupTest' in /home/jenkins/buildkit/build/core-12346-

@michaelmcandrew @seamuslee001 I agree that it is probably enough to fix going forwards. Probably anyone experiencing this error has already been hurt & self-fixed it. We could add a system check but I'm not convinced it's worth the effort. We could also do a str_replace double space for single when actually sending - it might still not be a priority to do that though

**Comment by eileenmcnaughton** [comment]
@michaelmcandrew next rc gets cut on Wed - would be nice to get this merged since it seems stuck on something trivial

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Change seems fine to myself and Eileen adding merge on pass thanks @michaelmcandrew

**Comment by seamuslee001** [comment]
Merging as per the tag

**Pull request merged**
