### PR TITLE
(WIP) CRM-19923: Scheduled reminders for activities based on "created date"

### PR DESCRIPTION
**Pull request by twomice**
FYI, this is a replacement PR for https://github.com/civicrm/civicrm-core/pull/9726.

---

 * [CRM-19923: Scheduled reminders for activities based on "created date"](https://issues.civicrm.org/jira/browse/CRM-19923)

### CODE REVIEW

**Comment by twomice** [comment]
Jenkins test this please.

**Comment by twomice** [comment]
Jenkins test this please.

**Comment by twomice** [comment]
I stumped, as the PR is hitting errors in Jenkins testing, but I can't get it to fail in development.  I've made sure to run `civibuild reinstall` on the site after checking out the appropriate branch, but still the relevant tests are passing.

```
cd /opt/buildkit/build/d47/sites/all/modules/civicrm/
git checkout CRM-19923-b_scheduled_reminder_activity_create 
git pull origin CRM-19923-b_scheduled_reminder_activity_create
civibuild reinstall d47
cd tools
```

```
as@as76:/opt/buildkit/build/d47/sites/all/modules/civicrm/tools (CRM-19923-b_scheduled_reminder_activity_create)$ scripts/phpunit CRM_Core_BAO_ActionScheduleTest
Installing d47test_h7cpy schema
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

PHP Warning:  declare(encoding=...) ignored because Zend multibyte feature is turned off by settings in /opt/buildkit/build/d47/sites/all/modules/civicrm/vendor/zetacomponents/mail/src/transports/variable/var_set.php on line 2
PHP Stack trace:
PHP   1. {main}() /opt/buildkit/bin/phpunit4:0
PHP   2. PHPUnit_TextUI_Command::main() /opt/buildkit/bin/phpunit4:545
PHP   3. PHPUnit_TextUI_Command->run() phar:///opt/buildkit/bin/phpunit4/phpunit/TextUI/Command.php:100
PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///opt/buildkit/bin/phpunit4/phpunit/TextUI/Command.php:149
PHP   5. PHPUnit_Framework_TestSuite->run() phar:///opt/buildkit/bin/phpunit4/phpunit/TextUI/TestRunner.php:440
PHP   6. PHPUnit_Framework_TestSuite->run() phar:///opt/buildkit/bin/phpunit4/phpunit/Framework/TestSuite.php:747
PHP   7. PHPUnit_Framework_TestCase->run() phar:///opt/buildkit/bin/phpunit4/phpunit/Framework/TestSuite.php:747
PHP   8. PHPUnit_Framework_TestResult->run() phar:///opt/buildkit/bin/phpunit4/phpunit/Framework/TestCase.php:724
PHP   9. PHPUnit_Framework_TestCase->runBare() phar:///opt/buildkit/bin/phpunit4/phpunit/Framework/TestResult.php:612
PHP  10. CiviUnitTestCase->runTest() phar:///opt/buildkit/bin/phpunit4/phpunit/Framework/TestCase.php:768
PHP  11. PHPUnit_Framework_TestCase->runTest() /opt/buildkit/build/d47/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:184
PHP  12. ReflectionMethod->invokeArgs() phar:///opt/buildkit/bin/phpunit4/phpunit/Framework/TestCase.php:909
PHP  13. CRM_Core_BAO_ActionScheduleTest->testMailer() phar:///opt/buildkit/bin/phpunit4/phpunit/Framework/TestCase.php:909
PHP  14. CiviMailUtils->assertRecipients() /opt/buildkit/build/d47/sites/all/modules/civicrm/tests/phpunit/CRM/Core/BAO/ActionScheduleTest.php:771
PHP  15. CiviMailUtils->getAllMessages() /opt/buildkit/build/d47/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviMailUtils.php:291
PHP  16. CiviMailUtils->convertToEzc() /opt/buildkit/build/d47/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviMailUtils.php:211
PHP  17. spl_autoload_call() /opt/buildkit/build/d47/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviMailUtils.php:352
PHP  18. Composer\Autoload\ClassLoader->loadClass() /opt/buildkit/build/d47/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviMailUtils.php:352
PHP  19. Composer\Autoload\includeFile() /opt/buildkit/build/d47/sites/all/modules/civicrm/vendor/composer/ClassLoader.php:322
.
Installing d47test_h7cpy database
.......................

Time: 39.48 seconds, Memory: 79.50Mb

OK (24 tests, 529 assertions)
```

Could someone offer some tips on how to get dev and Jenkins to behave in the same way?

**Comment by twomice** [comment]
Jenkins, test this please.

**Comment by mlutfy** [comment]
@twomice Any thoughts what to do with this PR?  Is it still on your radar?

**Comment by twomice** [comment]
@mlutfy No, I was stuck on testing (see my last comment). Tell you what, I'll look at it again on Friday, and if I'm hitting the same weirdness I'll update you here.

**Comment by eileenmcnaughton** [comment]
@twomice since this is stale I'm closing it & you can re-open if / when you get back to it.

**Comment by twomice** [comment]
Yep.

**Pull request closed without merging**
