### PR TITLE
(WIP) dev/core#2141 - OAuth2 exploratory branch

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

This PR is to provide testing while the branch goes through rapid change. The aim will be to split out some parts within the week.

See also: https://lab.civicrm.org/dev/core/-/issues/2141

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
fail is on warnings

**Comment by stesi561** [comment]
Attempting to r-run.
Enabled extension via api3 
head to civicrm/admin/oauth#!/
Don't see any options to select. 
Don't see any errors on console.
Don't see any errors in ConfigAndLog or watchdog - there is an info that seems to be dumping  civicrm_views_tokens into Civicrm ConfigAndLog

**Comment by demeritcowboy** [comment]
Do you just see a blank screen? It should look like this. I see it's not obvious that those words are links until you hover. I just have a habit of clicking on things even if I'm not supposed to... So just click on where it says `Google Mail` for example.

Untitled

**Comment by stesi561** [comment]
Sorry had taken a screenshot but forgot to attach!
I'm wondering if I need to include something else - I just applied -> https://patch-diff.githubusercontent.com/raw/civicrm/civicrm-core/pull/18863.patch
image

**Comment by stesi561** [comment]
I do see -> `<!-- ngRepeat: provider in theProviders -->` in the table body?

**Comment by demeritcowboy** [comment]
You're running 5.31 and then applying this patch? I'm running master which has some of this in it, and then just applied that one other patch about the button.

**Comment by stesi561** [comment]
Yes tried applying it to the RC.

**Comment by demeritcowboy** [comment]
There might be some supporting stuff in 5.32/master that it needs. To be honest not sure - I think most of this PR is in 5.32/master. There was a really short flurry of merges in the last two days.

**Comment by totten** [comment]
@stesi561 Yeah, for 5.31 backport, there are probably more patches. In addition to [the OAuth-specific patches](https://lab.civicrm.org/dev/core/-/issues/2141#note_50008), it likely needs at least  https://github.com/civicrm/civicrm-core/pull/18731. (The screen with the missing data relies on that patch.)

**Comment by totten** [comment]
>  I'm wondering if I need to include something else - I just applied -> https://patch-diff.githubusercontent.com/raw/civicrm/civicrm-core/pull/18863.patch

Oops, I didn't communicate clearly enough. :( During the previous week, I was rebasing this PR whenever bits gets merged into `master` (5.32). Therefore, the URL above will give you *the combination of all unmerged patches* rather than *the combination of all accumulated (merged or unmerged) patches*. 

For anything prior (eg `5.31-rc`), one needs to backport all the PRs individually.

Since #18914 was merged into `5.32-master` yesterday, we only have one more patch to merge (#18911).  All of these will be in `5.32-rc` (upcoming).

**Comment by eileenmcnaughton** [comment]
@totten just a reminder that this is kinda close to the point where it should be closed

**Comment by totten** [comment]
Everything in that was in this branch has either been merged in more focused PRs - or sent off to live the docs/issue-tracker.

**Pull request closed without merging**
