### PR TITLE
CRM-20396 Corrected payment_processor in contrib params

### PR DESCRIPTION
**Pull request by adixon**
Fixing incorrect transaction record for event registrations.

---

 * [CRM-20396: Event participation payments not correctly recorded in financial_trxn table](https://issues.civicrm.org/jira/browse/CRM-20396)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@adixon Alan are you able to write a unit test for this

**Comment by adixon** [comment]
Short answer .. no.

**Comment by monishdeb** [comment]
@JoeMurray @adixon @seamuslee001 I have tested this patch and it has resolved the issue. 
Bad news is, I have tried to add a CRM Unit test to ensure that there is a ```payment_processor_id``` in respective financialTrxn record, but unfortunately, I found no alternative to pass paymentProcessor information (as an object) at form level to do a successful payment. Tried to modify existing [test function](https://github.com/civicrm/civicrm-core/blob/master/CRM/Event/Form/Registration/Confirm.php#L1287) but without any success.

**Comment by adixon** [comment]
monish - glad to hear to worked. Did you check the original issue? This patch only fixed the payment processor field in the trxn table for me, but didn't fix the to_financial_account_id value, though I couldn't see why (but I didn't spend much time on that bit). Do you have any insight into that part of the problem?

**Comment by monishdeb** [comment]
@adixon @eileenmcnaughton I have added a unit test to ensure that payment processor id got stored in financial_trxn. This is the commit https://github.com/civicrm/civicrm-core/pull/10124/commits/5e40de8466ce038d8bb8df4892908d87a24a4d8c

**Comment by adixon** [comment]
Thanks for the test, that's great.

The incorrect value in to_financial_account_id - I suspect there are other circumstances that must be involved, I'll have to dig deeper if it's not affecting your test environment.

**Comment by eileenmcnaughton** [comment]
@monishdeb I think you are saying this is good to merge?

FWIW I'm not completely happy with the way $form->_paymentProcessor is set- I think the methodology is more reliable in the back office forms, but I am happy to merge this at this point if both of you are happy.

**Comment by eileenmcnaughton** [comment]
Merging because I think your comment here https://github.com/civicrm/civicrm-core/pull/10124#issuecomment-292943347 agreed that the fix is right & it was just the lack of a unit test blocking the issue.

**Pull request merged**
