### PR TITLE
Fix obscure dedupe scenario where 'bad' location data can overwrite good data

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------

Our api permits the creation of addresses with no actual address-related data. I'm not sure this is a good
thing but one way or another some addresses got into our database with no useful information and I'm not convinced we are alone.

When merging it's possible for a null address record to be treated as 'not a conflict' with an address record
with the same location but actual data, and for the null record to be retained. This fixes it such that in that
scenario the retained record is the one with data.

This is pretty obscure and an argument could be made for not fixing it. On the other hand this extends tests on the code
(in addition to the fairly extensive set in testBatchMergesAddresses) and I also did a few tangental cleanups

Before
----------------------------------------
- per the test
1) create 2 contacts
2) give them both home addresses via the api, leave one of them with no address data
3) use the Contact.merge api or Job.process_batch api to merge the other contact with address data into the contact with a null home address

-> The useful home address is lost

After
----------------------------------------
Per above but the useful information is retained

Technical Details
----------------------------------------

Comments
----------------------------------------
@JKingsnorth @pfigel any chance either of you could look?

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
hmm - let me double check that - I might have something in the cleanup PR I need in here (since I've put this up separately)

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit any chance you can review this too?

**Comment by jitendrapurohit** [comment]
Tested and confirmed the fix. Though i wasn't able to replicate the exact problem via UI, the API test ensures that in a case with null address record on the main contact can be kept as it is after the merge api is executed on it.

Applied the PR and tested different merge scenarios. The end result looks fine in all the manual test cases.

**Review by jitendrapurohit — APPROVED** [review]

**Comment by seamuslee001** [comment]
Merging as per the review by @jitendrapurohit

**Pull request merged**
