### PR TITLE
Backport CRM-19799 to 4.7.15

### PR DESCRIPTION
**Pull request by colemanw**
* [CRM-19799: LineItems incorrect at both Contribution Level and Financial Accounts Level](https://issues.civicrm.org/jira/browse/CRM-19799)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by guanhuan** [comment]
test this please

**Comment by colemanw** [comment]
test this please

**Comment by colemanw** [comment]
Test failures appear to be unrelated.

**Pull request merged**
