### PR TITLE
dev/core#2233 - Fix broken tabs on profiles admin page

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/2233

Same as https://github.com/civicrm/civicrm-core/pull/19130 but for the profiles admin page.

@mattwire @colemanw

### CODE REVIEW

**Comment by seamuslee001** [comment]
Tested this on my local and confirmed that it works MOP

**Comment by colemanw** [comment]
I believe this should be against the 5.33 branch.

**Comment by demeritcowboy** [comment]
Same question came up in 19130 but it's just master.

**Comment by colemanw** [comment]
Ok

**Comment by seamuslee001** [comment]
@colemanw as Max would say you missed the RC by that much

**Comment by demeritcowboy** [comment]
Strange error. Looks like a couple other PRs have it too. Going to assume a glitch. Jenkins retest this please.

```
Unable to send e-mail. Contact the site administrator if the problem     [error]
persists.
Build step 'Execute shell' marked build as failure
```

**Pull request merged**
