### PR TITLE
Remove function deprecated noisly in 2020

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Remove function deprecated noisly in 2020

Before
----------------------------------------
image

After
----------------------------------------
poof

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
test this please

**Comment by mattwire** [comment]
@eileenmcnaughton What should this be replaced with? It's broken a few extensions (civicrm-advanced-events, documents, gdpr, civibooking) and I can't see what the replacement should be?

**Comment by colemanw** [comment]
Oof, I guess we should have done a `universe` search before removing this one. Not great timing for reverting this PR because it was merged so long ago (`5.61.0`). What to do?

**Comment by seamuslee001** [comment]
@mattwire if my memory servers me correctly you should be refactoring to use this function instead https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/Form.php#L1565

**Pull request merged**
