### PR TITLE
Make all icons aria-hidden

### PR DESCRIPTION
**Pull request by agh1**
Overview
----------------------------------------
Per [Font Awesome's accessibility guidelines](https://fontawesome.com/v4.7.0/accessibility/) the icon itself should have `aria-hidden="true"` in basically all cases.

Before
----------------------------------------
A screen reader will pick up an empty `<i>` element and then whatever text goes along with it.

After
----------------------------------------
A screen reader will skip the icon and just pick up the text.

Technical Details
----------------------------------------
Regex to find icons:

```regex
<(\w+) ((?:(?!aria-hidden|>).)*?class=['"][^'">]*crm-i(?: [^'">]*)['"](?:(?!aria-hidden|>).)*)></\1>
```

Comments
----------------------------------------
There may be some stray spots where there's just an icon with no explanation or other information, but the solution there is to add screen reader text, not to tell the screen reader there's a weird empty tag.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by agh1** [comment]
(Resolved merge conflict)

**Comment by agh1** [comment]
> Can't connect to MySQL server

Jenkins retest this please

**Comment by mattwire** [comment]
test this please

**Comment by mattwire** [comment]
@agh1 It feels like a helper function would be useful here that inserts the `<i class=icon..` markup?

**Comment by agh1** [comment]
Yeah that's what CRM_Core_Page::crmIcon and {icon} do (added in #17279 and updated in #17289). For the sake of clarity on this PR and sheer time, however, I'm not in the position of rewriting every icon to use the helpers.  It's faster and less error-prone to just insert the attribute for now.

**Comment by eileenmcnaughton** [comment]
@agh1 this needs a rebase

**Comment by agh1** [comment]
Thanks @eileenmcnaughton I just rebased.

**Comment by seamuslee001** [comment]
@agh1 can you rebase this please

**Comment by agh1** [comment]
Thanks @seamuslee001 just rebased

**Comment by seamuslee001** [comment]
Changes look good to me merging

**Pull request merged**
