### PR TITLE
CRM-20351 Multiple pages repeat stuff in the page run() method, invoking hooks multiple times

### PR DESCRIPTION
**Pull request by agh1**
----------------------------------------
* CRM-20351: hook_civicrm_buildForm invoked twice on create/edit ACL form
  https://issues.civicrm.org/jira/browse/CRM-20351

### CODE REVIEW

**Comment by agh1** [comment]
Test failures are unrelated, as best as I can tell.  I'm getting the `CRM_Dedupe_MergerTest` problems on master, and I can't reproduce the `CRM_Event_BAO_AdditionalPaymentTest` failure locally.

**Comment by jitendrapurohit** [comment]
test this please

**Comment by seamuslee001** [comment]
@agh1 are you able to rebase this?

**Comment by agh1** [comment]
@seamuslee yeah not a prob. #10278 was opened and merged all in the course of the day and broke this--go figure.

**Comment by colemanw** [comment]
Sorry @agh1 I didn't see this one before merging he other.

**Comment by colemanw** [comment]
@agh1 @eileenmcnaughton  
looks like there are some relevant test failures.

**Comment by monishdeb** [comment]
@agh1 @colemanw @eileenmcnaughton  I have squashed multiple commits and fixed related test failures. Also reviewed the patch and its working fine. Since the changes here are vital to basic page, so I need if someone can eyeball the patch to ensure that the fix won't cause any uninteded regression, before merge.

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by monishdeb** [comment]
@colemanw I have fixed the related test build failures.

**Pull request merged**
