### PR TITLE
groupContact BAO - standardize add function

### PR DESCRIPTION
**Pull request by colemanw**
Overview
------
Cleans up the `CRM_Contact_BAO_GroupContact::add` function to behave more like a standard bao function. This gets it to the point where Api4 can actually use it.

Notes
-----
Function appears to be unused according to my grep, but anyway these changes should be non-breaking. IMO if existing tests pass, we're good.

### CODE REVIEW

**Comment by colemanw** [comment]
Actually @seamuslee001 it would be really nice to push this into 5.6 because it's needed for the next release of Api4 and the LayoutEditor extensions. I believe these changes are safe & backward-compatible, but that might not even matter. According to my grepping this function isn't used anywhere in core or api3.

**Comment by seamuslee001** [comment]
@colemanw that's fine i was just labeling based on what the target branch was given that Tim's bot which normally does the labeling is down because of pad thai issues. They also seem consistant with the groupOrganization BAO, Only thing is the group Org doesn't hook https://github.com/civicrm/civicrm-core/blob/master/CRM/Contact/BAO/GroupOrganization.php#L50 Going to give this merge on pass

**Comment by eileenmcnaughton** [comment]
@seamuslee001 is this what passes for pass at the moment?

**Comment by eileenmcnaughton** [comment]
@colemanw this function will be called by GroupContact.create api v3 (in response to your unused) - it should be tested already in that context

**Comment by seamuslee001** [comment]
@eileenmcnaughton yes it is

**Comment by colemanw** [comment]
> this function will be called by GroupContact.create api v3 (in response to your unused) - it should be tested already in that context

@eileenmcnaughton I agree it should, but it doesn't. It uses its own special sauce.

**Pull request merged**
