### PR TITLE
fatal error fixes in PHP 8.1

### PR DESCRIPTION
**Pull request by kurund**
Steps to replicate:
- create a profile with only custom field
- add it to the contact summary using contact summary layout
- try saving the data

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
@kurund style error

**Comment by larssandergreen** [comment]
Jenkins test this please

**Comment by eileenmcnaughton** [comment]
[api\v4\Entity\ActionScheduleTest.testGetOptionsBasic](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/3951/BKPROF=dfl,SUITES=phpunit-api4,label=bknix-tmp/testReport/(root)/api_v4_Entity_ActionScheduleTest/testGetOptionsBasic/) is an unrelated fail

**Comment by eileenmcnaughton** [comment]
looks safe & sensible

**Pull request merged**
