### PR TITLE
[REF] CiviGrant - Switch to writeRecord/deleteRecord + BAO hooks

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Code refactor in CiviGrant BAO to use newer code patterns.

Comments
----------------------------------------
Probably needs `r-run` creating and updating grants, esp checking that notes and attachments work correctly.

### CODE REVIEW

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by monishdeb** [comment]
@colemanw I encountered an issue. I used the test build site http://core-26594-5azma.test-1.civicrm.org:8001 (--account-name=admin --account-pass=MTQAGHbae3F8) and on contact summary's Grant tab, when I simply submit the Grant update form it creates a new grant record each time: 
update


On the other hand, the empty grant type on a fresh install of civigrant is another issue that I guess is covered in  https://github.com/civicrm/civicrm-core/pull/25387 . 

The rest are working fine, like the note and attachments are saved properly, also tried with grantapplication, did CRUD operation on grant etc.

**Comment by colemanw** [comment]
Thank you for reviewing @monishdeb - I've pushed up a fix for that (form submit function was using the old `$ids` pattern).

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by monishdeb** [comment]
Looks good now. I retested on test-build site and it works fine. I am not sure about an intermittent problem, as you can see in the screencast sometimes it takes too much time to save in popup edit/new grant form, but on refresh, I cannot replicate the issue again:
update

I repeated the same on my local but can't replicate it. I think it's just a glitch and did a thorough code review and can't find any possible cause.

**Comment by monishdeb** [comment]
Based on my review above, merging this PR.

**Pull request merged**
