### PR TITLE
Revert "CRM-19621: Contribution confirm page does not display state/c…

### PR DESCRIPTION
**Pull request by seamuslee001**
…ountry"

This reverts commit dd22a911411feae27dfe99d5640312e6f5807d04.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Cool - I'll leave if until @monishdeb & @jitendrapurohit have had time to object & then merge. Per my previous comments my preference is not to put ourselves through the stress of fixing CRM-19621 in time for 4.7.14 if there is any doubt.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I'm not sure you have actually explained the problem you hit anywhere?

**Comment by seamuslee001** [comment]
@eileenmcnaughton I posted the backtrace on the other ticket

**Comment by monishdeb** [comment]
@seamuslee001 what is the ticket number ?

**Comment by seamuslee001** [comment]
@monishdeb CRM-19621 and I posted the error i got with debug here https://github.com/civicrm/civicrm-core/pull/9399

**Comment by eileenmcnaughton** [comment]
replaced by #9466

**Pull request closed without merging**
