### PR TITLE
CRM-18510 - Fixed regression when search for location types.

### PR DESCRIPTION
**Pull request by mollux**
[CRM-18510](https://issues.civicrm.org/jira/browse/CRM-18510)

### CODE REVIEW

**Comment by xurizaemon** [comment]
Since column names can't (AFAIK) contain hyphens, I think that this may need renaming (validateColumnAlias?) to avoid being misleading.

Sorry - but I think saying one thing and doing another is the sort of thing that leads to bad code outcomes :)

**Comment by mollux** [comment]
I agree it's misleading, but renaming isn't the solution, as e.g. CRM_Util_sort is used both for column names and aliases, but there is no way to know if the passed sort string is an alias or a column name. (e.g. both "sort_name" and  "Home-street_address" are used when doing an advance search on address).
So we could add a separate validation for aliases and check before using the validate method if there is a hyphen in the name, and then use the correct one, but IMO that isn't a good solution.

A solution would be to rename the check to mysqlColumnNameOrAlias, and put more logic in there (e.g. is there is a hyphen, then we assume is is an alias, so there can't be a dot and a table name).
Another solution would be to get rid of the hyphens in aliases (which would big, as this is clearly not test-covered)

**Comment by xurizaemon** [comment]
OK, I agree. Shall we keep the current function name and just add comment
in function docs that it's column or alias?

I'm surprised it's even legal SQL to have hyphen in an alias. How does the
query engine tell if it's a minus when used in group or order part of
statements? IDK. But that's not our problem rn :)
On 9 May 2016 5:56 PM, "mollux" <notifications@github.com> wrote:

I agree it's misleading, but renaming isn't the solution, as e.g.
CRM_Util_sort is used both for column names and aliases, but there is no
way to know if the passed sort string is an alias or a column name. (e.g.
both "sort_name" and "Home-street_address" are used when doing an advance
search on address).
So we could add a separate validation for aliases and check before using
the validate method if there is a hyphen in the name, and then use the
correct one, but IMO that isn't a good solution.

A solution would be to rename the check to mysqlColumnNameOrAlias, and put
more logic in there (e.g. is there is a hyphen, then we assume is is an
alias, so there can't be a dot and a table name).
Another solution would be to get rid of the hyphens in aliases (which would
big, as this is clearly not test-covered)

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/civicrm/civicrm-core/pull/8317#issuecomment-217781689>

**Comment by seamuslee001** [comment]
@xurizaemon I think if you want to use a column alias in an order by or group by you can do '<alias>' and it will respect hypens i think

**Comment by mollux** [comment]
@seamuslee001 they need to be surrounded by ` (backticks) not ' (singel quotes), see https://github.com/civicrm/civicrm-core/blob/master/CRM/Contact/BAO/Query.php#L2698 how this is implemented (without using the escape method, as it didn't exist at the time that code was written :) )

**Comment by xurizaemon** [comment]
I concur that it's possible @seamuslee001, I guess whether it *should* be done or not is a matter of taste :)

@mollux's fix as it is deals with the situation at hand so 👍  to that

**Comment by totten** [comment]
Had some chat discussion about this. It seemed pretty promising to update the validation so that accepts either:
 * (a) bare words (eg `[a-zA-Z0-9_]+`)
 * (b) backtick phrases (eg backtricks around `[a-zA-Z0-9+\- \+\?]+`)

**Comment by totten** [comment]
jenkins, test this please

**Comment by eileenmcnaughton** [comment]
@mollux you continue to do amazing work on this!

Will you do a 4.6 once this is merged? If so please ping me from it so I can get it merged.

**Comment by totten** [comment]
Agree that the PR looks nice.

Unfortunately, it seems to have disproven an assertion from the chat -- namely, that the values being validated actually include the backtick. The current patch yields the same error. :( Note that if you inspect `CRM_Utils_Sort::__construct()`, `$vars` includes the literal "Home-street_address" without backticks.

I'm going to have to publish RC without this, but I think it would be great if we could an updated PR submitted to `4.7.8-rc`.

**Comment by mollux** [comment]
As just discussed on MM, CRM_Utils_Sort should both use validate and escape, to guarantee that backticks are added (adding the escape functionality to validate isn't a good idea IMO). The escaping was initially there, see https://issues.civicrm.org/jira/browse/CRM-17983?focusedCommentId=88445&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-88445 and https://github.com/civicrm/civicrm-core/pull/8265/commits/56a83ec579c685cde51837ded7e16dd1e76aae7f

I went through all the places where CRM_Util_Sort is used, and I think CRM_Contact_BAO_query is the only one that alters the sort, so I fixed that to make it work with an escaped string.

**Comment by totten** [comment]
Replaced by #8442.

**Pull request closed without merging**
