### PR TITLE
CiviMail - Update path metadata

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes up the paths in metadata to match actual links used in the UI.

Before
---------
Hard-coded links to angular page, missing copy action

After
--------
Uses the general system links that will redirect to core angular page or mosaico page as appropriate. Added missing copy action.

### CODE REVIEW

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
retest this please

**Comment by samuelsov** [comment]
@colemanw All good to me.

FYI, to replace the screen with SK/FB, we still need to add path for the following actions:
- pause -> civicrm/mailing/browse?action=disable&mid=[id]&reset=1
- resume -> civicrm/mailing/browse?action=reopen&mid=[id]&reset=1
- archive -> civicrm/mailing/browse/archived?action=renew&mid=[id]&reset=1

**Pull request merged**
