### PR TITLE
SearchKit - fix deprecated join

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes deprecated warning noted in https://lab.civicrm.org/dev/core/-/issues/2689#note_62477

Replaces https://github.com/civicrm/civicrm-core/pull/20966

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Ah cool. Thanks.
Works.

**Comment by eileenmcnaughton** [comment]
@colemanw total_amount & net_amount http://core-20947-5ue5k.test-1.civicrm.org:8001/civicrm/admin/search#/edit/1

**Comment by demeritcowboy** [comment]
jenkins retest this please

CRM_Core_Payment_AuthorizeNetIPNTest::testIPNPaymentRecurNoReceipt
GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to apitest.authorize.net port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by demeritcowboy** [comment]
Oh, I see that test is failing everywhere.

**Comment by eileenmcnaughton** [comment]
yeah - we can ignore that one - I think we do a live curl call to A.net (they must love us)

**Pull request merged**
