### PR TITLE
SearchKit - Selectable option-value format

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Using a similar UX to #30703, this provides a selector for how an option value should be formatted.

image

### CODE REVIEW

**Comment by colemanw** [comment]
@demeritcowboy you know you wanna merge this

**Comment by demeritcowboy** [comment]
jenkins retest this please (patch doesn't seem to apply?)

**Comment by colemanw** [comment]
> I dunno, the UI already seems kind of full?

We've added the same type of "Format" selector in the same place for date fields. That also could have been accomplished via some complex smarty rewrite, but I think the goal of SearchKit is to be as friendly & useful as possible.

**Comment by demeritcowboy** [comment]
If you set both a format and a rewrite, then the format is ignored. I guess that's "correct", just seems like two things for the same thing.

**Comment by colemanw** [comment]
@demeritcowboy how about we hide the format selector if rewrite is in-use

**Comment by demeritcowboy** [comment]
Sure.

**Pull request merged**
