### PR TITLE
dev/core#2434 Fix price set id widget

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
https://github.com/civicrm/civicrm-core/pull/19719 against master as this seems to affect master not 5.35

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
I tested this on my local and confirmed it fixed the problem

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by colemanw** [comment]
I think the source of the regression was #19531 where the `id` field was given `html_type: number` so it stopped being a select. But I agree with this fix and I think that other PR just exposed that this form code was wrong.

**Pull request merged**
