### PR TITLE
Contemplate nothingness

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Allow NULL to be NULL without converting it to NULL.

Before
----------------------------------------
NULL or NULL

After
----------------------------------------
NULL is NULL

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I'm not sure about merging this - it's crying out for a gif war & @totten & @demeritcowboy might miss it if it gets merged too quick

**Comment by demeritcowboy** [comment]
If you nullify null, does that create a higher level of nullness, like aleph0, aleph1, ...

I'm going to propose that should be a new php feature.

**Comment by eileenmcnaughton** [comment]
jenkins looked into the abyss & baulked

**Comment by demeritcowboy** [comment]
jenkins test this please

**Comment by colemanw** [comment]
Branch merged & deleted. It is now nothing, yet one with everything.

**Pull request merged**
