### PR TITLE
CRM-18701 remove inappropriate actions from processAmount

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
I need to fix a bug in that function & I'm struggling with the readability so I have refactored the 'amount_priceset_level_radio' setting back to the form. In the process I came to the conclusion that the CRM_Event_BAO_Participant::createDiscountTrxn is not actually working and the problem is in this line 

$contributionParams['trxnParams']['from_financial_account_id'] = CRM_Contribute_PseudoConstant::financialAccountType(
        $contributionParams['contribution']->financial_type_id, $relationTypeId);

which is not retrieving the value it should.

This is the case before & after the patch - so I'm going to log a separate ticket for that. https://issues.civicrm.org/jira/browse/CRM-18775  @JoeMurray

---
- [CRM-18701: civicrm_financial_item has wrong amount when overriding line item price](https://issues.civicrm.org/jira/browse/CRM-18701)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@josephlacey this is the refactor I was hoping you could take a look at...

**Comment by josephlacey** [comment]
@eileenmcnaughton I've reviewed this and have a few questions about it.  Since we have the luxury, probably better to discuss them quickly in-person when you have a minute.

**Comment by josephlacey** [comment]
@eileenmcnaughton and I discussed
- a redundant instance of the function
- an extra argument
- a potential deprecation of the email

All are fixed.  I then tested the updated code for creating a discount and having that reflected in the database.

**Comment by tamarmeir** [comment]
Almost.... tested the latest build - see attached screen shot for membership contribution created - membership type amount is $100, overrode with a $50 contribution - from apiexplorer, I see the following which leads me to believe that this issue is not yet fixed:

**Line item table:**

	"is_error":0,
	"version":3,
	"count":1,
	"id":97,
	"values":[{
		"id":"97",
		"entity_table":"civicrm_membership",
		"entity_id":"31",
		"contribution_id":"95",
		"price_field_id":"4",
		"label":"General",
		"qty":"1.00",
		"unit_price":"100.00",
		"line_total":"100.00",
		"participant_count":"0",
		"price_field_value_id":"7",
		"financial_type_id":"2",
		"deductible_amount":"0.00"

**Financial item table:**

	"is_error":0,
	"version":3,
	"count":1,
	"id":94,
	"values":[{
		"id":"94",
		"created_date":"2016-06-09 18:51:54",
		"transaction_date":"2016-06-09 18:51:00",
		"contact_id":"203",
		"description":" General",
		"amount":"100.00",
		"currency":"USD",
		"financial_account_id":"2",
		"status_id":"1",
		"entity_table":"civicrm_line_item",
		"entity_id":"97"

**From financial transaction table:**

	"is_error":0,
	"version":3,
	"count":2,
	"values":[{
		"id":"116",
		"entity_table":"civicrm_financial_item",
		"entity_id":"58",
		"financial_trxn_id":"58",
		"amount":"50.00"

membership_line_item_override

I get the same results with an amount greater than that expected (i.e. default amount is populated in line item and financial item tables), but it looks as if the financial transaction table is being updated correctly (with the amount that is either greater or less than the configured membership price).

**Comment by eileenmcnaughton** [comment]
The pull request you have commented on was a preliminary tidy up - this is the one with the fix https://github.com/civicrm/civicrm-core/pull/8533

**Pull request merged**
