### PR TITLE
Add api-v4 discount api

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Add api-v4 discount api

Before
----------------------------------------
Now you don't see it

After
----------------------------------------
Now you do

Technical Details
----------------------------------------
@colemanw  I was wanting to use the api to do a `getOptions` on price-set-id WHERE the entity-entity-id combo is the relevant event. Do I do something to make this getFields take more where

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton dynamic pseudoconstants are very much a thing in APIv4. The `getFields` action already accepts a `values` array. However, something in the BAO needs to take those values and do something smart with it.
See https://github.com/civicrm/civicrm-core/pull/27054

**Comment by eileenmcnaughton** [comment]
@colemanw that PR shows controlFields (none that have entity_id + entity_table) but no examples of where the `BAO` is doing something to filter it

**Comment by colemanw** [comment]
@eileenmcnaughton on a related topic, I noticed there is no pseudoconstant for the `entity_table` field - that's not good for SearchKit or the api in general. Needs a whitelist of possible entity tables, like this:
https://github.com/civicrm/civicrm-core/blob/297cd23d7faa2605c18dc10ec70ba46516ace784/xml/schema/ACL/ACLEntityRole.xml#L44-L51

**Comment by eileenmcnaughton** [comment]
AFAIK it is only possible for it to be events!

**Comment by colemanw** [comment]
@eileenmcnaughton I think since the functional code in this PR is all by me, it's on you to review & merge!

@mattwire IDK but it's confusing!

**Comment by eileenmcnaughton** [comment]
@mattwire this Discount entity basically has time fields + a price set ID - cividiscount has more functionality over & above that I guess but I don;t know if it could leverage these fields

**Comment by eileenmcnaughton** [comment]
@colemanw I did hit an issue with this - however, the fix is a bit broader than this entity & the content of this patch is fine so will merge & post follow up

**Comment by larssandergreen** [comment]
@mattwire I wondered about Discounts vs. CiviDiscounts as well, but I think they are really quite disparate concepts. Discounts apply a different price set for event registrations based on dates (between these dates, use this price set instead of the default one for the event), CiviDiscounts are pretty much completely different.

Really, Discounts would probably be better handled by having one price set with price fields that are active or inactive for the relevant dates, as Discounts pretty much provide that same functionality, but less flexibly. It wouldn't be a huge project to convert them, I don't think, but I'm not volunteering!

**Comment by eileenmcnaughton** [comment]
@larssandergreen yes - good point re moving the date fields to the price_field entity - that makes a lot of sense & I hadn't thought about it before. It espectially makes sense once we start to support them in form builder. I don't expect to do any immediate changes but will keep thinking about that one

**Pull request merged**
