### PR TITLE
Improve styling of address block on summary screen

### PR DESCRIPTION
**Pull request by colemanw**
Overview
-------
More consistent styling of the address block with other elements of the contact summary screen; makes the block easier to see when the contact does not have an address.

Before
----------
screenshot from 2018-08-23 11-40-54

After
------
screenshot from 2018-08-23 11-37-52

Before (w Shoreditch)
------
screenshot from 2018-08-23 11-36-23

After (w Shoreditch)
--------
screenshot from 2018-08-23 11-36-47

### CODE REVIEW

**Comment by colemanw** [comment]
@tschuettler  I'm on a contact summary improvement kick right now!
BTW have you seen the new [Layout Editor](https://civicrm.org/blog/colemanw/contact-layout-editor-help-put-on-the-finishing-touches) extension?

**Review by tschuettler — CHANGES_REQUESTED** [review]
@colemanw I agree that it does make more sense to display the label all the time.

It currently does not work for multiple addresses. 
I'm not sure whether multiple addresses should stay more compact by spanning over both columns or using the same design as the other elements like E-Mail or Phone.

This contact has actually 4 addresses:
grafik

**Comment by tschuettler** [comment]
The extension looks like a really nice feature! We currently get along with ACL-based display of custom field sets reasonably well.

**Comment by colemanw** [comment]
@tschuettler whoops, that was a mistake. Now fixed.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by tschuettler** [comment]
I can confirm that it works again: 
grafik

It seems like #12708 introduced the odd spacing between multiple addresses in https://github.com/civicrm/civicrm-core/commit/8fa8736ff10bff3962774174e592f91fd62433a6#diff-6e4b278c9fc95f56b5040a44db65e310R25 

Do we need that there or can we add something with more specificty to counter it?
```css
.crm-address-block {
    clear: none;
}
```
This would look better to me:
grafik

**Comment by colemanw** [comment]
Thanks @tschuettler  - you're right that `clear:both` was causing problems. I've removed it as it wasn't really essential to the previous PR; I had added it "just in case" but if it's causing problems, let's get rid of it.

**Comment by tschuettler** [comment]
Thanks @colemanw - it's looking good now.

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Pull request merged**
