### PR TITLE
Experimental: Invalidate and do not flush group contact cache

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
I'm struggling to see why we ever need to actually trigger an opportunistic flush of the group contact cache. As long as the cache is invalidated then it should be built on demand.
Any performance impact would seem mitigated by the fact that an opportunistic flush can happen on almost any request, whereas the cache rebuild would only happen on a request that actually requires it! So the actual user who needs to query the cache may seem some slowdown but the poor user who just wanted to check his email address won't get any slowdown.

After this there are only two places that call `CRM_Contact_BAO_Contact_Utils::clearContactCaches()` (cli.class.php and import preview).

Before
----------------------------------------
Cache flush may occur when we only need to invalidate the cache and don't need to actually use it.

After
----------------------------------------
Cache flush only occurs when we actually need to access it.

Technical Details
----------------------------------------
`CRM_Contact_BAO_GroupContactCache::flushCaches()` clears out entries from expired cached groups and then clears the cache date. But clearing the expired cache and *updating* the cache date is done when we rebuild the cache so why do it twice?

Comments
----------------------------------------
@eileenmcnaughton Be interested in your thoughts here? I've not tested this on a real site yet but I can't get my head around *why* we would ever want to proactively clear the cache rather than just invalidate it. I don't think there is anywhere that tries to access the group contact cache without `load()`ing it first.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire without having dug in I think this might be right - I agree it needs live testing but I think your logic makes sense.

One thing is that by only invalidating the groups a contact is already in we miss the groups they should now be added to

**Comment by eileenmcnaughton** [comment]
@mattwire another thought in the vein of 'unintended consequences' - I wonder if this could lead to the size of the cache table getting pretty large on site who don't have the cron enabled. Currently you either have

a) the ability to configure crons in which case you should ideally disable opportunistic cache clearing with the setting - which would likely make this a no-change or
b) no ability to configure crons - in which case opportunistic cache flushing is probably the only process by which large rarely groups would ever be cleared from the group cache table
c) or - the ability to configure crons but no idea how to best configure your site for group caching

I suspect c is a fairly big group & we should possibly do more to encourage the use of the cron / the setting - but for b I'm thinking this change might mean the table bloats up over time (if they have old groups they don't use much)

**Comment by JoeMurray** [comment]
Going back to initial architecture, I wonder if part of our problem is that the group contact cache has data that both changes frequently due to contact changes AND is traversed for some operations like determining civimail recipients. AWS guidance on caching says: 
"Is caching effective for that data? Some applications generate access patterns that are not suitable for caching—for example, sweeping through the key space of a large dataset that is changing frequently. In this case, keeping the cache up to date could offset any advantage caching could offer." (https://aws.amazon.com/caching/best-practices/)

Same page suggests that while a lazy load cache approach is generally good, occasionally a write through pattern is appropriate: "In a write-through cache, the cache is updated in real time when the database is updated. ... A good example is any type of aggregate, such as a top 100 game leaderboard, or the top 10 most popular news stories, or even recommendations." Our group cache is an aggregate.

So I think we have over the years been suffering because our problem domain doesn't fit well with cache optimized use cases.

In terms of the particular suggestion here, I'm a bit unclear on the terminology and implementation. Normally it should be possible to invalidate a key and rebuild a cache entry for a key. The word 'flushing' suggests to me a combination of invalidating a key and some memory reclamation/garbage collection operation. But maybe (I haven't looked at the code) flush also involves rebuilding. 

If we are aiming to have essentially an in-memory table of the complete 'cache' always available, then this is more like the write-through cache pattern. 

If the problem is that recalculating a group's contacts is expensive because it potentially affects other groups too, one pattern to try to improve responsiveness some of the time is to move the calculation to a background thread. That's the idea behind the cron. Ideally the cron would be updating invalidated group cache entries frequently before they had to be built in the context of a webserver page request. We've struggled to get acceptance of using slightly outdated entries, which would allow us to avoid frequent and expensive rebuild operations.

I think leaving an invalidated group cache un-rebuilt makes sense a) if cron can sometimes rebuild it in the background, b) it will reduce the number of group cache entries rebuilt because the group will not infrequently have more than one change before a rebuild. I think Matt's point is b).

I sense that Eileen's concern is that we want to ensure lazy loading always rebuilds an entry if it has been invalidated.

**Comment by demeritcowboy** [comment]
This has been WIP for several months so going to close but feel free to reopen.

**Pull request closed without merging**
