### PR TITLE
Mailing - ignore case-sensitive string when extracting category from mail template tokens

### PR DESCRIPTION
**Pull request by michaeljanuszkiewicz**
Overview
----------------------------------------
It looks like tokens that are 'alone' inside an HTML are accidentally stripped out of the plain text version that CiviCRM generates.

Steps to recreate

* Set outbound emial to redirect to DB
* Create a new mailing with the HTML
```
<html>
<head>
<title></title>
</head>
<body>
<p>Serial BOLD&nbsp;1:&nbsp;<strong>{contact.display_name}</strong></p>
<p>Serial 2:&nbsp;{contact.display_name}</p>
<p>Serial 2:&nbsp;{CONTACT.DISPLAY_NAME}</p>
</body>
</html>
```

* Send it
* Check the civicrm_mailing_spool table
* Inspect the body field
* Notice that it is correct in HTML version, but missing in plain text version

Before
----------------------------------------
Example:
image

After
----------------------------------------
Example:
image

Technical Details
----------------------------------------
Civi CRM_Utils_String::htmlToText use library: rcube_html2text (file: CRM_Mailing_BAO_Mailing). Library convert html template to text version.

For tags like: strong, b, th, etc.. (look variable: callback_search and method: tags_preg_callback in class rcube_html2text )
method is removing specified tags and return string which is uppercase. 
Example: <strong>token:{contact.display_name}</strong> will be converted to TOKEN:{CONTACT.DISPLAY_NAME}
CiviCrm not processing uppercase tokens.

### CODE REVIEW

**Comment by JKingsnorth** [comment]
Jenkins test this please.

**Comment by eileenmcnaughton** [comment]
add to whitelist

**Comment by eileenmcnaughton** [comment]
Test failures are releated

**Comment by JKingsnorth** [comment]
Test failures related to the change in the regex pattern @michaeljanuszkiewicz  ?

**Comment by michaeljanuszkiewicz** [comment]
Yes, test failed because strtolower changed all tokens to lowercase and when it comes to compare it doesn't work. Reason for that is that some of the tokens have camelcase naming conversion: unsubscribeUrl, optOutUrl. Because they are in use in many places it would be massive change. Will check if rcube_html2text package change is allowed.

**Comment by JKingsnorth** [comment]
Hi @totten 

The cause of the issue is that the library we use to convert HTML emails into plain text will sometimes CAPITALISE text as part of the 'interpretation', for example in a <strong> tag.

This is defined here: https://github.com/civicrm/civicrm-packages/blob/b57d6f400165ffc1b79af9df141b271365652864/html2text/rcube_html2text.php#L645-L660

So <strong>{contact.display_name}</strong> becomes <strong>{CONTACT.DISPLAY_NAME}</strong>

This means that the token does not get parsed/recognised; and is displayed as 'blank' in the email.

So the possible solutions are:
1) Override the package (or find another way) for the parser to 'skip' tokens
2) Change the token handling as above

(I thought we could just proces tokens before the plain text version was generated - but of course this doesn't work at all because the plain text version is in the DB and the tokens are replaced on sending.)

**Comment by JKingsnorth** [comment]
@eileenmcnaughton Yes, I could probably write a test to demonstrate the issue, I've made a note on our internal tracker.

**Comment by JKingsnorth** [comment]
OK, I'll create a gitlab issue for it, feel free to close this.

**Pull request closed without merging**
