### PR TITLE
[REF] APIv4 - Use new class_args metadata to remove special handing

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Cleans up the internal process of resolving an APIv4 request, taking advantage of new metadata added in #22831 to remove workarounds and special cases.

Before
----------------------------------------
When creating an API request, special logic was needed for `CustomValue` and `CiviCase` apis.

After
----------------------------------------
Metadata used.

Comments
----------------------------------------
This is massively covered by existing tests.

### CODE REVIEW

**Comment by totten** [comment]
Looks like a good change. I think the affected use-cases should already have pretty decent test-coverage. Merge on pass.

**Comment by colemanw** [comment]
@totten thanks. The test failure looks like the same caching bug which is solved by #22843.

**Comment by totten** [comment]
Lol, right. Well, I've been working on a response to your observations over on that one.

**Comment by totten** [comment]
jenkins, test this please

**Pull request merged**
