### PR TITLE
(WIP) [Closed/Ignore] CRM-19923: Scheduled reminders for activities based on "created date"

### PR DESCRIPTION
**Pull request by twomice**
TODO:
1. Add unit tests to verify correct functionality for reminders scheduled against 'activity created date'
2. If necessary add unit tests to ensure this doesn't break reminders scheduled against 'activity date/time'

NEED INPUT:
1. This PR includes schema changes and new triggers. What's expected in terms of test coverage for such changes?

---

 * [CRM-19923: Scheduled reminders for activities based on "created date"](https://issues.civicrm.org/jira/browse/CRM-19923)

### CODE REVIEW

**Comment by twomice** [comment]
Can someone suggest what I should do about the merge conflicts related to `GenCodeChecksum`?

**Comment by totten** [comment]
General design note: the UI for scheduled reminders has a drop down for choosing different date fields. In the case of activities, it would make sense to show two different fields (i.e. `activity_date_time` and `created_date`). There's a similar split in the contribution-oriented reminders. IIRC, that dropdown corresponds to `$actionSchedule->start_action_date`.

> Can someone suggest what I should do about the merge conflicts related to GenCodeChecksum?

First `git pull --rebase origin master` or `git rebase origin/master`. This will present the merge-conflict locally. Revert the files and then rerun `setup.sh -g`. Continue with the rebase.

> 1. Add unit tests to verify correct functionality for reminders scheduled against 'activity created date'
> 2. If necessary add unit tests to ensure this doesn't break reminders scheduled against 'activity date/time'

Makes a lot of sense. You may have spotted these already, but a few files that might be good to look at:
 * `CRM/Contribute/ActionMapping/ByType.php` (esp note `getDateFields()`)
 * `tests/phpunit/CRM/Contribute/ActionMapping/ByTypeTest.php` 
 * `tests/phpunit/CRM/Activity/ActionMappingTest.php` (esp. `addAliceMeeting()` which creates an activity and sets `activity_date_time` to match `$this->targetDate`)
 * `tests/phpunit/Civi/ActionSchedule/AbstractMappingTest.php` is a common base-class used for newer tests. It has docblock about general organization/design.

> This PR includes schema changes and new triggers. What's expected in terms of test coverage for such changes?

I'd keep it simple. Just have a test create an activity, read the activity, and assert that the `created_date` is accurate (maybe with a some margin of error due to performance variations in test server; like 5 seconds; eg `assertApproxEquals(strottime(...), strtotime(...), 5`).

**Comment by twomice** [comment]
This PR has become a git mess. Will submit another.

**Comment by twomice** [comment]
Closing. Replacement is at https://github.com/civicrm/civicrm-core/pull/9738

**Pull request closed without merging**
