### PR TITLE
[REF] dev/core#3658 Regenerate civicrm_generated to ensure that group…

### PR DESCRIPTION
**Pull request by seamuslee001**
…ing is added on installs

Overview
----------------------------------------
Regenerates civicrm_generated for 5.51 to ensure grouping field is filled out on install

Before
----------------------------------------
Grouping field not filled out on install

After
----------------------------------------
It is

ping @eileenmcnaughton @colemanw

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by seamuslee001** [comment]
@civicrm-builder test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I'm pretty sure there will be another stable point version soon - should we do this against stable too?

**Comment by seamuslee001** [comment]
@eileenmcnaughton if we are doing another stable then yes

**Comment by eileenmcnaughton** [comment]
I think we should - this week

**Pull request merged**
