### PR TITLE
CRM-19051 Logging - setting to allow offline triggers not respected i…

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
…n all cases

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by AkA84** [comment]
@eileenmcnaughton i'd be happy to test this, i only need the test steps!

Also, out of curiosity: is `CRM_Core_Config::singleton()` deprecated now in favour of `\Civi::settings()`?

**Comment by eileenmcnaughton** [comment]
Thanks @AkA84 so the way this works is that if this setting is enabled it does NOT spit out an error when upgrading regarding triggers if  the mysql account does not have SUPER privillege and the change log tab shows when the mysql account does not have SUPER privilege and logging is turned on.

The rationale is that in a replicated environment the SUPER permission & the ability to create triggers have greater security implications so it may make sense to manage the triggers offline & this setting should allow that to be done without degrading functionality.

Re config vs settings. The config object precedes the concepts of settings. Some things like $config->userSystem are not deprecated but those settings that used to be stored in the config_backend field on the civicrm_domain table are now moved to settings and accessing them via CRM_Core_Config::singleton() is deprecated in favour of \Civi::settings()

So, I guess to test:
1) turn on logging on 4.7.9
2) edit a contact & look at the change log tab
3) remove the SUPER permission from the mysql account
4) check the change log tab - should look different
5) try running the upgrade - should give an error
6) add this setting by coding it into civicrm_settings
7) change log should look like it did in step 2 & upgrade should now run

**Comment by AkA84** [comment]
Hi @eileenmcnaughton , sorry for taking so long to reply. I'm sorry but it doesn't seem i'm able to replicate your steps, i'm probably missing something

1) I turned logging on my 4.7.9 build, in /civicrm/admin/setting/debug?reset=1
2) I've edited a contact and i see a new row in the table "admin@example.com | <date>"
3) Now I've removed the SUPER permission from the mysql user that buildkit created with my `d47` build
4) The log tab look the same as before
5) This "upgrade" i'm not sure what you're referring to, /civicrm/upgrade ? If yes, it just tells me that i'm at the latest version
6) I've added `$civicrm_setting['CiviCRM Preferences']['logging_no_trigger_permission'] = 1;` in civicrm_settings
7) still the same as before

**Comment by eileenmcnaughton** [comment]
Sorry I think you actually need to remove the TRIGGER permission to replicate this in a non-replicated environment. With replication off the lessor TRIGGER permission is sufficient to create triggers because you can only use triggers for privilege escalation in a replicated environment

**Comment by davejenx** [comment]
@eileenmcnaughton Tested as follows...

Before applying PR:
1) Turned on logging in my local 4.7 dmaster build (so not using MySQL replication).
2) Edited a contact and I see an advanced-logging-style entry in the change log.
3) Removed the SUPER and TRIGGER permissions from the mysql user that buildkit created with my dmaster build.
4) The change log tab now shows simple-logging-style entries.
5) /civicrm/upgrade?reset=1 gives error: CiviCRM 4.7.13 requires MySQL trigger privileges.
6) Added $civicrm_setting['CiviCRM Preferences']['logging_no_trigger_permission'] = 1; in civicrm.settings.php .
7) The change log tab still shows simple-logging-style entries.
8) /civicrm/upgrade?reset=1 gives error: CiviCRM 4.7.13 requires MySQL trigger privileges.

After applying PR:
9) The change log tab now shows advanced-logging-style entries, however first contact view attempt gave DB Error: insufficient permissions, subsequent contact views worked but edits give DB Error: insufficient permissions.
10) civicrm/upgrade gives "Your database has already been upgraded to CiviCRM 4.7.13", which I guess means it got past the permissions issue.

So it looks like the PR succeeds in bypassing the permission check in these cases but the permissions then aren't sufficient for a fully-functioning Civi. I'd have expected the triggers to have been created already in this scenario, maybe some actions are resulting in Civi attempting to recreate triggers?

**Comment by eileenmcnaughton** [comment]
I just discussed this with Dave and the issue he hit is that the triggers were defined by a contact with high permissions & they then got downgraded so they didn't run (ie. the definer needs to have a higher level of permissions). This is not the intended scenario (which is the definer should have full permissions.) So this is not a concern

Merging

**Pull request merged**
