### PR TITLE
CRM-20965: Add PR template

### PR DESCRIPTION
**Pull request by mickadoo**
## Overview
Github offers [pull request templates](https://github.com/blog/2111-issue-and-pull-request-templates) to standardize the content of pull requests. This should help improve the description of pull requests to core.

## Before
There is no pull request template, or structure.

## After
A new template is added which will be automatically added to the description input whenever a new pull request is created.

## Comments
- This pull request description uses the new template.
- This template is modified from the [CiviHR version](https://github.com/civicrm/civihr/blob/staging/.github/PULL_REQUEST_TEMPLATE.md)
- Please feel free to suggest a better format for the template

---

 * [CRM-20965: Add Pull Request Template](https://issues.civicrm.org/jira/browse/CRM-20965)

### CODE REVIEW

**Comment by totten** [comment]
* Big +1 on adding a template for PR descriptions. 
 * I really like the Overview/Before/After and the links for screenshot tools.
 * Tempted to drop "Technical Details".  That's just a gut reaction -- don't have a pithy rationalization.
 * Tempted to add "Testing", "Review Suggestions", or "Risks".  Basically, as a reviewer, I appreciate when authors clearly communicate about (a) what scenario/configuration they tested and (b) what remaining risks or test-activities merit attention or disclaimers. (Ideally, the reviewers could help with those; or maybe pull-in someone else; or maybe publish a note with RC.)

These are examples of what I mean:
  * "This code uses some edgy HTML5 stuff -- I tested in Chrome/FF/Safari but don't have IE8, but it would be great if someone could test in IE8." 
 * "I tested this with the PayPal.com sandbox, but the codepath is also used by Authorize.net. Someone with Authorize.net access should try it out."
 * "These options X, Y, Z can be mixed in many ways. I've spot-checked X1+Y{2,3}+Z{2,5} but don't have access/capacity to test X2 and Z3."

**Comment by mickadoo** [comment]
@totten 

I'm fine with dropping technical details, for CiviHR it's used as an overview for bigger PRs to introduce a new service or architecture change. If it's not likely to be used for the majority of PR descriptions then I'll drop it, just let me know.

For CiviHR for testing we just have a "tests pass" checkbox, but with Jenkins this isn't required here (and hopefully won't be in the future when we get Jenkins set up with CiviHR). I'm happy to add another section like "Suggestions" as long as you think it will be used by most descriptions - the key is to keep it minimal and allow expansion where the developer feels the need.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
So the status of this PR as I understand it is that it is agreed it is an improvement. There are some soft suggestions that are not resolved but are not blockers to merging. It feels no-risk & easy to edit later as people start to see the potential - we should merge this now I think & fix more later if we wish

**Comment by mickadoo** [comment]
@eileenmcnaughton that's a fair assessment. I was waiting a bit to see what the consensus is on dropping "technical details" or adding new sections. What do you think yourself?

**Comment by eileenmcnaughton** [comment]
Honestly  I don't know - I think once we are using it suggestions will come in thick & fast - merging!

**Pull request merged**
