### PR TITLE
 CRM-17287 Test fixes

### PR DESCRIPTION
**Pull request by monishdeb**
- [CRM-17287: Broken Unit Tests on master](https://issues.civicrm.org/jira/browse/CRM-17287)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This looks like another step towards standardisation & robustness - yay.

& I think what I'm seeing is that the form standardises the input so support for the old style params can be dropped without breaking existing ones?

**Comment by davecivicrm** [comment]
Test failure unrelated AND this fixes a warning I've been seeing in Manage Groups recently: Strict warning: Declaration of CRM_Contact_BAO_SavedSearch::save() should be compatible with CRM_Core_DAO::save($hook = true) in require_once() (line 37 of /Users/dgg/git/crm_v4.7/CRM/Contact/BAO/SavedSearch.php). Thx @monishdeb

**Comment by totten** [comment]
Reading the PR, I had question as Eileen about `QueryTestDataProvider` - it seems to imply that the format of the saved-search data changed somewhere. If so, then it would help to clarify how the data gets migrated.

**Comment by eileenmcnaughton** [comment]
So, a general note on migration - I think the way we are starting to look at the migration is that it is the job of CRM_Contact_BAO_Queries::convertFormValues to handle any changes to how the forms deal with data. This function should ensure that :

a) a consistent (ok -consistent-ish) format is presented to the query object
b) legacy formats are supported thus far but no further

In other words the handling of the wierd & wonderful belongs in convertFormValues with the ultimate goal that all parameters that get to the main query object would use the same standardised formats as the API & so things like handling of 'participant_end_date_high' could come out of the query object because it would only see 'participant_end_date' => array('>' => 'tomorrow') or whatever

We would ideally get really serious about testing convertFormValues function!

Note that I  tried at one point to make it possible for people to export saved_searches from their site & have them added to the test-suite - see https://github.com/civicrm/civicrm-core/blob/master/tests/phpunit/CRM/Contact/BAO/GroupTest.php#L135-135 - it tests for error not correct results - but it might be possible to get @seamuslee001 to contribute some more saved search datasets to this folder https://github.com/civicrm/civicrm-core/tree/master/tests/phpunit/CRM/Contact/BAO/SavedSearchDataSets to increase the coverage ...

**Comment by seamuslee001** [comment]
@eileenmcnaughton I can have a poke around our db and try and come up with some common ideas, However of course getting it all set up will be the important thing and i may need yours or others (thinking maybe @totten ) in understanding what the test suite adds to the db in so far as say membership types etc. Contributions etc is the biggest area that we can help on, We have heaps of custom fields which we do smart groups on which probably won't be helpful here but stuff like Smart group on members of x type and z,y status or contributions in x time period or of y type is possibly helpful here

**Comment by eileenmcnaughton** [comment]
@seamuslee001 there are many different levels of what can be tested. The test covered in https://github.com/civicrm/civicrm-core/blob/master/tests/phpunit/CRM/Contact/BAO/GroupTest.php#L124 don't rely on the DB being very set up as they just test that no fatal errors will happen - regardless of results. Only one part of the testing jigsaw for sure!

**Comment by monishdeb** [comment]
@totten as per the search fixes made for all Contact attributes (in https://github.com/civicrm/civicrm-core/pull/6360), I have changed whereClause() build logic in way that it expect formValue as in (id1,id2, ... ) format instead of array(id1 => 1, id2 => 1, ...) format, in case of group and tag. Handling migrate was a miss from my earlier PR changes and after discussion with @eileenmcnaughton and kurund we agreed to support the legacy format rather then writing the migrate logic in upgrade. So this is my PR https://github.com/civicrm/civicrm-core/pull/6827. Also in test case I have kept both legacy and standard format in DataProvider

**Pull request merged**
