### PR TITLE
Allow click-through and open tracking to be enabled/disabled by default

### PR DESCRIPTION
**Pull request by mfb**
Overview
----------------------------------------
Civi instances may want to set the default state of click-through and open tracking for new mailings.

Before
----------------------------------------
Click-through and open tracking always default to true.

After
----------------------------------------
A new CiviMail component setting allows for setting the click-through and open tracking defaults.

### CODE REVIEW

**Comment by mfb** [comment]
test this please

**Comment by MegaphoneJon** [comment]
I reviewed this code, but haven't done an `r-run` yet - I'm going to ask a coworker to do it in the morning.  This looks good, it's using modern approaches to the code, but it does need documentation.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by mfb** [comment]
@MegaphoneJon I'm thinking I could document this @ https://docs.civicrm.org/user/en/latest/email/mass-mailings-using-civimail/#tracking-tab what do you think?

**Comment by mfb** [comment]
Jenkins re test this please

**Comment by colemanw** [comment]
retest this please

**Comment by mfb** [comment]
test this please

**Comment by mfb** [comment]
retest this please

**Comment by megaphonetech-dennis** [comment]
I did an r-run, but I'm not able to do a code-level review.

(CiviCRM Review Template DEL-1.2)

* General standards
    * Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
        * __PASS__ : The goal/problem/solution have been adequately explained in the PR.
    * User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
        * __PASS__: The change would be intuitive or unnoticeable for a majority of users who work with this feature.
    * Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
        * __PASS__: There are relevant updates for the documentation.
        * __COMMENTS__: I believe the author is correct in identifying https://docs.civicrm.org/user/en/latest/email/mass-mailings-using-civimail/#tracking-tab as the appropriate location for this documenation.
    * Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
        * __PASS__: I verified the presence of new checkbox options in CiviMail Component Settings. Then, I tested four scenarios: enabled checkbox for *click-through tracking by default* only; enabled checkbox for *open tracking by default* only; both checkboxes unchecked; and both checkboxes checked. For each scenario, I verified the *Review and Schedule* screen reflected the appropriate indicators for tracking *click-throughs* and *opens*. I also inspected the emails sent and verified that tracking code for external links were either present or not as expected based on defaults set.

**Comment by seamuslee001** [comment]
I have created a documentation issue here https://github.com/civicrm/civicrm-user-guide/issues/445 based on Jon and Dennis's review I'm marking this as merge on pass

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Pull request merged**
