### PR TITLE
Further optimize creditnote_id generation

### PR DESCRIPTION
**Pull request by ejegg**
Overview
----------------------------------------
In case the credit notes started at an offset other than 1, avoid a potentially
very slow process of creditnote generation.
This will enable users to archive ancient contributions or start their creditnotes at a non-zero offset in case of migrating to CiviCRM without importing all existing contributions.

Before
----------------------------------------
In a DB with 48,000 contributions having a creditnote_id but
whose largest creditnote_id is 48,100, Civi makes a lookup call for
every creditnote_id between CN_48001 and CN_48101 (100 queries) when
refunding a contribution.

After
----------------------------------------
After: In a DB with 48,000 contributions having a creditnote_id but
whose largest creditnote_id is 48,100, Civi makes 3 db queries when
refunding a contribution.

Technical Details
----------------------------------------
Instead of assuming that the next available creditnote_id is equal to the count plus one, then
looping upwards until you find a free one, use db queries to actually find the maximum
creditnote_id and start from there. The loop SHOULD be unnecessary now, but I haven't
deleted it in case two donations are being refunded simultaneously.

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by ejegg** [comment]
This will enable users to archive ancient contributions or start their creditnotes at a non-zero offset in case of migrating to CiviCRM without importing all existing contributions.

**Comment by bjendres** [comment]
See also lab/Core #1308

**Comment by mattwire** [comment]
@bjendres @ejegg Is there anyone else who can verify / review this? From a code point of view it looks sensible but I'd like confirmation that it is working in a real scenario.

**Comment by eileenmcnaughton** [comment]
Closing this out as code has been restructured & it won't apply now. We do also have a different plan for how to resolve the inefficiency on this now

**Pull request closed without merging**
