### PR TITLE
[NFC] Add in Further debugging to authx test to try and debug issue o…

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------

Small change to test assertions. This should hopefully make it easier to understand a failure on php81.

### CODE REVIEW

**Comment by totten** [comment]
@seamuslee001 Failing on phpcs/civilint

Note: I've cleaned up the description a bit.

**Comment by seamuslee001** [comment]
@totten sorted that and it seems it is failing in step 3 https://test.civicrm.org/job/CiviCRM-E2E-Edge/BLDTYPE=drupal-clean,CIVIVER=master,label=test-3/lastCompletedBuild/testReport/(root)/Civi_Authx_AllFlowsTest/testMultipleStateless/

**Comment by totten** [comment]
OK, so (just for clarity/background) the pseudocode for the steps leading up to i=3:

```php
$client = new HttpClient('cookies'=>'on');
/*i=0; L*/ $client->get('civicrm/authx/id', ['Authorization' => "Bearer {$lebowskiApiKey}");
/*i=1; A*/ $client->get('civicrm/authx/id' /* anonymous */);
/*i=2; D*/ $client->get('civicrm/authx/id', ['Authorization' => "Bearer {$demoApiKey}");
/*i=3; A*/ $client->get('civicrm/authx/id' /* anonymous */);
```

The situation being tested is a bit ambiguous. (The HTTP client supports cookies, and the client sends requests with stateless auth. Should the server initialize an authenticated session anyway?)  The tested behavior is (IMHO) more "correct", though that's by-the-by. The important thing is that it behaves consistently -- so if you write/test a REST integration on (say) D9, then you can run the same integration on D7/WP/BD/J.

But this failure... hmmm.... it's a preplexing. If it gets through steps 0=>1 without creating a session, then it seems weird to setup a session on steps 2=>3. 


I guess follow-up things to inspect might be....

* Which ID is it retaining on step `i=3`?
* Are cookies coming back? Are the cookies changing?

**Comment by totten** [comment]
There may be some discussion about pending php81 issues, but this is still merge-ready. So...

**Pull request merged**
