### PR TITLE
add grid layout support for searchkit

### PR DESCRIPTION
**Pull request by kurund**
Overview
----------------------------------------
* Add grid display layout for search kit

https://lab.civicrm.org/dev/core/-/issues/2776

### CODE REVIEW

**Comment by colemanw** [comment]
(*CiviCRM Review Template WORD-1.2*)

* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) PASS
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) PASS
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) *We need more docs for searchKit but that shouldn't block this PR*
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) PASS: New grid display works great.

* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) PASS: Uses all the new SearchDisplay code patterns.
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) PASS
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) PASS
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) Search Displays don't have tests but that shouldn't block this PR.

**Comment by colemanw** [comment]
@kurund I've tested it out, and given the PR merge-on-pass.

image


One thing I'd like to see, either in a follow-up or in this PR is control over the alignment within cells. I see it's hard-coded to "center" but could be configured with some buttons in the display admin section (`fa-align-left`, etc)

**Comment by kurund** [comment]
@colemanw 

Great thanks.

> One thing I'd like to see, either in a follow-up or in this PR is control over the alignment within cells. I see it's hard-coded to "center" but could be configured with some buttons in the display admin section (fa-align-left, etc)

Make sense, will do a follow up PR soon.

**Comment by eileenmcnaughton** [comment]
@kurund - it's really cool to see you contributing a new layout - it would be good if you could add more screenshots to this PR or to th follow up PR / more about how it's useful so I can share that in the dev digest.

As an aside one thing that is already requested for the table layout & I expect would be requested here is the option to have gridlines

**Comment by kurund** [comment]
@eileenmcnaughton 

Here is an example of use case: https://github.com/civicrm/civicrm-core/pull/21225#issuecomment-903959953

**Comment by eileenmcnaughton** [comment]
cool

**Pull request merged**
