### PR TITLE
Add hook to alter display value or Custom field value

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
Add hook to alter display value or Custom field value

Comments
----------------------------------------
There is no specific hook to alter the display of custom field value unless we use some jquery. This hook will provide ability to alter the display of the custom field value like adding html tags, manipulating labels based on value etc

### CODE REVIEW

**Comment by seamuslee001** [comment]
This looks good to me @mattwire @eileenmcnaughton thoughts?

**Comment by MikeyMJCO** [comment]
I got carried away and merged the docs PR on this already! If this ends up not getting merged let me know so I can revert the docs merge!

**Comment by yashodha** [comment]
@pradpnayak looks good to me as well. Can you please squash your commits?

**Comment by pradpnayak** [comment]
@yashodha done!

**Comment by yashodha** [comment]
@pradpnayak Great, thanks! Have you added the documentation in dev docs as well?

**Comment by pradpnayak** [comment]
yes, can be found at https://github.com/civicrm/civicrm-dev-docs/pull/786

**Comment by yashodha** [comment]
@pradpnayak Merging this now.

**Pull request merged**
