### PR TITLE
$frequency_unit is not translated

### PR DESCRIPTION
**Pull request by masetto**
When I have only one frequency unit, `$frequency_unit` is not translated and it appears always in english.

### CODE REVIEW

**Comment by colemanw** [comment]
Thanks for submitting a PR to CiviCRM.
I don't believe this is the correct fix. The `ts` function can only translate literal strings, and here you are using it on a variable.
IIRC, the frequency units are stored in an option list, and option lists are translated during install. Did you install Civi in your own language?

**Comment by masetto** [comment]
in `civicrm_option_value` table `recur_frequency_units` labels is translated. For example I see `label` "giorno" and `name` and `value`  are equal to "day": `$frequency_unit` has not the value of `label` field, but the `value` and I cannot change this one because in smarty tpl many tests (`if then else `) are performed on english values.

**Comment by colemanw** [comment]
I found the offending code. And it is quite bad (also about 10 years old). It assigns the `name` instead of the `label` for display on the form :(. And double-bad, it attempts to pluralize it by adding an `(s)` at the end :( :(. This will need to be changed to assign the label not the name, and forget about pluralization it's not possible.

https://github.com/civicrm/civicrm-core/blob/5da7cc4936ccca8b8cfaac4c8880da9b1a58261e/CRM/Contribute/Form/Contribution/Main.php#L549-L572

**Comment by demeritcowboy** [comment]
See also https://lab.civicrm.org/dev/translation/-/issues/53

**Comment by eileenmcnaughton** [comment]
It looks like the preferred approach is to do something more like 

https://github.com/civicrm/civicrm-core/pull/19655/files

@masetto is this something you are still working on?

**Comment by masetto** [comment]
Hi @eileenmcnaughton, I close this PR. I'm satisfied with your solution, but is partial because it would also need to consider when {if `$frequency_interval > 1`

**Comment by eileenmcnaughton** [comment]
@mlutfy can you comment on the right way to handle plurals (as a follow on to your patch)

**Comment by mlutfy** [comment]
Something like this?

```
 {if $frequency_unit eq 'day'}
  <p><strong>{ts 1=$frequency_interval}This contribution will be automatically processed every %1 days.{/ts}</strong></p>
{elseif $frequency_unit eq 'week'}
  <p><strong>{ts 1=$frequency_interval}This contribution will be automatically processed every %1 weeks.{/ts}</strong></p>
{elseif $frequency_unit eq 'month'}
  <p><strong>{ts 1=$frequency_interval}This contribution will be automatically processed every %1 months.{/ts}</strong></p>
{elseif $frequency_unit eq 'year'}
  <p><strong>{ts 1=$frequency_interval}This contribution will be automatically processed every %1 years.{/ts}</strong></p>
{/if}
```

We could also use `$frequency_interval` as a count parameter, and then use the count/plural options of ts, which could avoid the `{if $frequency_interval > 1}`.

Ex:

{ts count=$pager->_totalItems plural='All %count records'}

```
 {if $frequency_unit eq 'day'}
  <p><strong>{ts count=$frequency_interval plural='This contribution will be automatically processed every %1 days.'}This contribution will be automatically processed every %1 day.{/ts}</strong></p>
{elseif $frequency_unit eq 'week'}
  <p><strong>{ts count=$frequency_interval plural='This contribution will be automatically processed every %1 weeks.'}This contribution will be automatically processed every %1 week.{/ts}</strong></p>
{elseif $frequency_unit eq 'month'}
  <p><strong>{ts count=$frequency_interval plural='This contribution will be automatically processed every %1 months.'}This contribution will be automatically processed every %1 month.{/ts}</strong></p>
{elseif $frequency_unit eq 'year'}
  <p><strong>{ts count=$frequency_interval plural='This contribution will be automatically processed every %1 years.'}This contribution will be automatically processed every %1 year.{/ts}</strong></p>
{/if}
```

It's not particularly easy to read, but it's probably the best option.

**Pull request closed without merging**
