### PR TITLE
Fix import activity & add tests

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Extends https://github.com/civicrm/civicrm-core/pull/23703 to do all the same things for activity import

### CODE REVIEW

**Comment by aydun** [comment]
On first screen of Activity Import, the help icon produces a pop-up with no information.

Warnings on second page:
```
    Warning: Undefined array key "savedMappingName" in include() (line 8 of /home/jenkins/bknix-dfl/build/core-23703-3lxzt/web/sites/default/files/civicrm/templates_c/en_US/%%2E/2E3/2E3CBBFD%%MapTable.tpl.php).
    Warning: Undefined array key 2 in include() (line 77 of /home/jenkins/bknix-dfl/build/core-23703-3lxzt/web/sites/default/files/civicrm/templates_c/en_US/%%2E/2E3/2E3CBBFD%%MapTable.tpl.php).
    Warning: Trying to access array offset on value of type null in include() (line 77 of /home/jenkins/bknix-dfl/build/core-23703-3lxzt/web/sites/default/files/civicrm/templates_c/en_US/%%2E/2E3/2E3CBBFD%%MapTable.tpl.php).
    Warning: Undefined array key 2 in include() (line 77 of /home/jenkins/bknix-dfl/build/core-23703-3lxzt/web/sites/default/files/civicrm/templates_c/en_US/%%2E/2E3/2E3CBBFD%%MapTable.tpl.php).
    Warning: Trying to access array offset on value of type null in include() (line 77 of /home/jenkins/bknix-dfl/build/core-23703-3lxzt/web/sites/default/files/civicrm/templates_c/en_US/%%2E/2E3/2E3CBBFD%%MapTable.tpl.php).
    Warning: Undefined array key 2 in include() (line 77 of /home/jenkins/bknix-dfl/build/core-23703-3lxzt/web/sites/default/files/civicrm/templates_c/en_US/%%2E/2E3/2E3CBBFD%%MapTable.tpl.php).
    Warning: Trying to access array offset on value of type null in include() (line 77 of /home/jenkins/bknix-dfl/build/core-23703-3lxzt/web/sites/default/files/civicrm/templates_c/en_US/%%2E/2E3/2E3CBBFD%%MapTable.tpl.php).
    Warning: Undefined array key "savedMappingName" in include() (line 83 of /home/jenkins/bknix-dfl/build/core-23703-3lxzt/web/sites/default/files/civicrm/templates_c/en_US/%%2E/2E3/2E3CBBFD%%MapTable.tpl.php).
    Warning: Undefined array key "mappingDetailsError" in include() (line 107 of /home/jenkins/bknix-dfl/build/core-23703-3lxzt/web/sites/default/files/civicrm/templates_c/en_US/%%2E/2E3/2E3CBBFD%%MapTable.tpl.php).
    Warning: Undefined array key "highlightedRelFields" in include() (line 14 of /home/jenkins/bknix-dfl/build/core-23703-3lxzt/web/sites/default/files/civicrm/templates_c/en_US/%%31/319/31965542%%highLightImport.tpl.php).
```

**Comment by aydun** [comment]
After hitting Continue on step 2 (Match fields):

```
Error: Call to undefined method CRM_Activity_Import_Parser_Activity::setFieldMetadata() in CRM_Import_Parser->getMappedFieldLabel() (line 1773 of /home/jenkins/bknix-dfl/build/core-23703-3lxzt/web/sites/all/modules/civicrm/CRM/Import/Parser.php).
```

**Comment by aydun** [comment]
When using a saved mapping, I get extra empty dropdowns:
Screenshot-8

**Comment by eileenmcnaughton** [comment]
I just rebased this over the fixes on participant - and got through the whole flow

image

**Comment by colemanw** [comment]
Let's get this merged so we can test them all together

**Comment by eileenmcnaughton** [comment]
@aydun can you re-test once merged & we will address any issues  - it's actively broken without this

**Pull request merged**
