### PR TITLE
Fix regression on case export from recent export fix

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fix enotices & fatal error on case export

Before
----------------------------------------
screenshot 2018-07-20 10 53 46

screenshot 2018-07-20 11 06 41

After
----------------------------------------
screenshot 2018-07-20 11 30 51

Technical Details
----------------------------------------
I experienced a lot of inconsistency in my testing of this & switching to a component specific class that extended the main one seemed much more reliable - and as a approach it offers the possibility of much cleaner code

Comments
----------------------------------------
I don't think this affects 5.4 rc

@mattwire @lcdservices @kcristiano ping

### CODE REVIEW

**Comment by lcdservices** [comment]
tested and confirmed. this fixes the undefined property warnings.

**Comment by eileenmcnaughton** [comment]
@lcdservices adding merge on pass on your review - did you check 5.4? I thought it wasn't there but also thought my head was spinning after looking at this for a while

**Comment by lcdservices** [comment]
I tested against the master branch and could reproduce. After applying the PR the error was removed.

**Comment by mattwire** [comment]
:+1:

**Comment by eileenmcnaughton** [comment]
@mattwire do you think 5.4 is affected?

**Comment by mattwire** [comment]
@eileenmcnaughton Yes looks like 5.4 is affected :-( #12316 and #12320 will need to be backported before this PR can be applied to 5.4 though.

**Comment by eileenmcnaughton** [comment]
@mattwire can you do a backport PR for 5.4?

**Comment by mattwire** [comment]
Why are these commits not in the 5.4 branch but are in the 5.3 branch?

https://github.com/civicrm/civicrm-core/commit/6e3090fb1e4cabe750cf68b37f0863d380723d39
https://github.com/civicrm/civicrm-core/commit/39fecc8ad7e1acb389babde7271e0270d14ce611

**Pull request merged**
