### PR TITLE
dev/core#3049 - Update autocomplete custom fields to use APIv4

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Implements the suggestion in https://lab.civicrm.org/dev/core/-/issues/3049#note_92908 to use APIv4 for custom fields of type Autocomplete-Select.

Comments
------------
The upshot of this change is that when used on an afform these fields will now respect the permission settings and allow anonymous users to see autocomplete results if the form field is configured to do so.

### CODE REVIEW

**Comment by colemanw** [comment]
@larssandergreen @MegaphoneJon can either of you review this one?

**Comment by MegaphoneJon** [comment]
Just to flag that @briennekordis is reviewing this, to prevent Lars doing redundant work.

**Comment by colemanw** [comment]
@briennekordis I've updated this PR to include a fix for https://lab.civicrm.org/dev/core/-/issues/4476

**Comment by colemanw** [comment]
@MegaphoneJon @briennekordis it would be good to get this merged before next week's release since it fixes the Afform bug you found.

**Comment by briennekordis** [comment]
> @MegaphoneJon @briennekordis it would be good to get this merged before next week's release since it fixes the Afform bug you found.

I'm getting a Loading failed error with this patch when I follow the rep steps on the [reported bug](https://lab.civicrm.org/dev/core/-/issues/3049#note_92908)

Selection_037

**Comment by colemanw** [comment]
@briennekordis sorry if it wasn't clear, per [my issue comment](https://lab.civicrm.org/dev/core/-/issues/3049#note_92919) this PR wasn't intended to fix profile forms, only Afforms. But since you're testing it I went ahead and pushed up a 2nd commit to add the necessary validation to make profile forms work. If you try it again I think you'll find everything is working as you expected it to.

**Comment by briennekordis** [comment]
@colemanw Ah, sorry I didn't make that connection either. That being said, I just tried the patch with the newly pushed commits and now it does work for me on profile forms, but *not* on Afform.

Selection_039


```
[debug] AJAX Error ({error_id}): failed with exception
Array
(
    [error_id] => zRLB-SlRd-8DLE
    [exception] => Civi\API\Exception\UnauthorizedException: "Authorization failed"
#0 Civi/API/Kernel.php(147): Civi\API\Kernel->authorize(Object(Civi\Api4\Provider\ActionObjectProvider), Object(Civi\Api4\Generic\DAOGetAction))
#1 Civi/Api4/Generic/AbstractAction.php(249): Civi\API\Kernel->runRequest(Object(Civi\Api4\Generic\DAOGetAction))
#2 api/api.php(91): Civi\Api4\Generic\AbstractAction->execute()
#3 ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php(107): civicrm_api4("OptionValue", "get", (Array:8), NULL)
#4 ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php(121): Civi\Api4\Action\SearchDisplay\Run->processResult(Object(Civi\Api4\Result\SearchDisplayRunResult))
#5 Civi/Api4/Provider/ActionObjectProvider.php(72): Civi\Api4\Action\SearchDisplay\AbstractRunAction->_run(Object(Civi\Api4\Result\SearchDisplayRunResult))
#6 Civi/API/Kernel.php(156): Civi\Api4\Provider\ActionObjectProvider->invoke(Object(Civi\Api4\Action\SearchDisplay\Run))
#7 Civi/Api4/Generic/AbstractAction.php(249): Civi\API\Kernel->runRequest(Object(Civi\Api4\Action\SearchDisplay\Run))
#8 ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php(97): Civi\Api4\Generic\AbstractAction->execute()
#9 Civi/Api4/Generic/AutocompleteAction.php(183): Civi\Api4\Action\SearchDisplay\AbstractRunAction->execute()
#10 Civi/Api4/Provider/ActionObjectProvider.php(72): Civi\Api4\Generic\AutocompleteAction->_run(Object(Civi\Api4\Generic\Result))
#11 Civi/API/Kernel.php(156): Civi\Api4\Provider\ActionObjectProvider->invoke(Object(Civi\Api4\Generic\AutocompleteAction))
#12 Civi/Api4/Generic/AbstractAction.php(249): Civi\API\Kernel->runRequest(Object(Civi\Api4\Generic\AutocompleteAction))
#13 api/api.php(91): Civi\Api4\Generic\AbstractAction->execute()
#14 CRM/Api4/Page/AJAX.php(116): civicrm_api4("OptionValue", "autocomplete", (Array:5), NULL)
#15 CRM/Api4/Page/AJAX.php(55): CRM_Api4_Page_AJAX->execute("OptionValue", "autocomplete", (Array:5), NULL)
#16 CRM/Core/Invoke.php(319): CRM_Api4_Page_AJAX->run((Array:5), NULL)
#17 CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem((Array:16))
#18 CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke((Array:5))
#19 drupal/civicrm.module(472): CRM_Core_Invoke::invoke((Array:5))
#20 buildkit/build/dmain/web/includes/menu.inc(527): civicrm_invoke("ajax", "api4", "OptionValue", "autocomplete")
#21 buildkit/build/dmain/web/index.php(21): menu_execute_active_handler()
#22 {main}
```

**Comment by colemanw** [comment]
@briennekordis please check the permission setting for that field. By default it is "User-Based" but if you want to allow anonymous access it must be changed to "Form-Based':
image

**Comment by briennekordis** [comment]
> @briennekordis please check the permission setting for that field. By default it is "User-Based" but if you want to allow anonymous access it must be changed to "Form-Based': 
@colemanw,  Ah, thanks. Updated the field specific permissions and can verify that this patch fixes the issue when permissions are configured properly on profiles and afforms.

**Comment by colemanw** [comment]
Thanks for reviewing @briennekordis

**Pull request merged**
