### PR TITLE
[REF] Relocate another deprecated utils function to the only class that calls it.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
[REF] Relocate another deprecated utils function to the only class that calls it

Before
----------------------------------------
Function sits in the old deprecated utils file

After
----------------------------------------
Function sits in the one class that calls it

Technical Details
----------------------------------------
I removed the tests because they didn't test much & what they did test
seemed like stuff we should alter

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 this has passed now - the same as the others you have merged

**Comment by eileenmcnaughton** [comment]
@seamuslee001 once this is merged I'll look at the next step on the import cleanup

**Comment by seamuslee001** [comment]
Looks fine to me merging

**Pull request merged**
