### PR TITLE
CRM-16029 - Follow-up fixes for multilingual financial types and accounts

### PR DESCRIPTION
**Pull request by mollux**
[CRM-16029](https://issues.civicrm.org/jira/browse/CRM-16029)

### CODE REVIEW

**Comment by davecivicrm** [comment]
Jenkins, retest this please.

**Comment by davecivicrm** [comment]
Jenkins, test this please.

**Comment by mollux** [comment]
Jenkins, retest this please.

**Comment by mollux** [comment]
Jenkins, retest this please.

**Comment by davecivicrm** [comment]
ok to test

**Comment by davecivicrm** [comment]
add to whitelist

**Comment by davecivicrm** [comment]
I've asked @jaapjansma to QA this since he filed the original issue.

**Comment by jaapjansma** [comment]
The fix looks ok to me. Thanks @mollux

**Pull request merged**
