### PR TITLE
CRM-17000 CRM-11256 speed up api separator handling

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
- [CRM-17000: API performance: _civicrm_api3_separate_values](https://issues.civicrm.org/jira/browse/CRM-17000)
  - [CRM-11256: optimization to _civicrm_api3_separate_values](https://issues.civicrm.org/jira/browse/CRM-11256)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This patch has been around a long time but got stalled on 'is it really faster' I think it will be interesting to see if it's any quicker than other PRs on Jenkins

**Comment by eileenmcnaughton** [comment]
Clearly that second attempt wasn't a win!

**Comment by colemanw** [comment]
I don't think the PR test suite is any good at benchmarking -- too many other variables at play like server load, etc.
However the devel module can help. As of 4.7 the devel page timer and other footer stuff plays nicely with Civi ajax, so it's easy to do benchmarking simply by running stuff in the api explorer.
I'll give it a shot if I find some free time, or someone else can.

**Comment by eileenmcnaughton** [comment]
Yeah - this is sleeping not dead from my point of view :-)

**Pull request closed without merging**
