### PR TITLE
[REF] Add in Unit test to demonstrate error when trying to import a c…

### PR DESCRIPTION
**Pull request by seamuslee001**
…ampaign id int rather than name or label of the campaign

Overview
----------------------------------------
@eileenmcnaughton as discussed this shows the problem when importing a contribution with campaign id rather than the campaign label

Before
----------------------------------------
No test 

After
----------------------------------------
Test

ping @andrew-cormick-dockery @johntwyman just FYI

### CODE REVIEW

**Comment by seamuslee001** [comment]
Test fails as expected without #24815

**Comment by andrew-cormick-dockery** [comment]
I'd add tests for:

* name
* title
* failure text - intentionally fail, examine text upon failure.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Pull request merged**
