### PR TITLE
APIv4 Export - Fix logic for exporting pseudoconstant syntax

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes an edge-case issue with exporting records with option-value type fields.

Before
----------------------------------------
Logic was trying to guess which was right based on how the option keys look.

After
----------------------------------------
Logic actually checks where the options come from to get it right.

Comments
----------------------------------------
The bulk of this diff is just indentation change, adding an IF around some code.

### CODE REVIEW

**Comment by totten** [comment]
@colemanw Check code style

**Comment by colemanw** [comment]
@totten fixed

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by colemanw** [comment]
I'd prefer this get merged into `5.45` since it fixes new functionality in that release.

**Comment by seamuslee001** [comment]
Code seemed fine to me and will test with the RC all together and adds some extra Unit tests

**Pull request merged**
