### PR TITLE
error in input tag

### PR DESCRIPTION
**Pull request by ankitjain28may**

### CODE REVIEW

**Comment by ankitjain28may** [comment]
@civicrm-builder pls see this..!

**Comment by colemanw** [comment]
Jenkins, test this please.

**Comment by colemanw** [comment]
@ankitjain28may thanks for submitting this fix. FYI civicrm-builder is our testbot. AKA Jenkins.

**Comment by eileenmcnaughton** [comment]
Jenkins seems to be a bit unenthused here - I'll try triggering it again!

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by ankitjain28may** [comment]
I will check it out..!!

**Comment by eileenmcnaughton** [comment]
That is an unrelated test failure

**Comment by eileenmcnaughton** [comment]
Tim & I agreed this looks pretty safe

**Pull request merged**
