### PR TITLE
Remove use of ignoreException from SMTP settings form

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Temporary tables permissions are required in various places in CiviCRM. Remove this check that uses `ignoreException()` from the form.

Before
----------------------------------------
One more use of ignoreException().

After
----------------------------------------
One less use of ignoreException().

Technical Details
----------------------------------------

Comments
----------------------------------------
@eileenmcnaughton @seamuslee001 @demeritcowboy Came across this one and thought it was a good/easy one to get rid of. Agree?

### CODE REVIEW

**Comment by demeritcowboy** [comment]
@mattwire there's some extra commits in both of these PRs. Otherwise the idea sounds good just from a code read here:

1. Exception is thrown. It gets logged - good.
1. Then it says `Your %1 settings are correct`, which is a positive way to start the year, but obviously not right. So maybe in this line `elseif (!is_a($result, 'PEAR_Error'))` also want to add `&& !is_a($result, 'Exception')`

**Comment by eileenmcnaughton** [comment]
@demeritcowboy it can't be a PEAR_ERROR at that point as you point out. But rather than assigning the exception to $result & then checking if it's an exception it makes sense to just set the message in the catch

Do we know how to trigger this exception to test it?

**Comment by demeritcowboy** [comment]
Setting the message in the catch sounds fine but then you still need to avoid hitting the elseif lower down somehow otherwise it will _also_ set the status with the conflicting message `Your %1 settings are correct`. So maybe statusBounce() since this is a form?

I don't offhand know how to trigger it.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy something like this

```
      if (defined('CIVICRM_MAIL_LOG') && defined('CIVICRM_MAIL_LOG_AND_SEND')) {
          $testMailStatusMsg .= '<br />' . ts('You have defined CIVICRM_MAIL_LOG_AND_SEND - mail will be logged.') . '<br /><br />';
        }
        if (defined('CIVICRM_MAIL_LOG') && !defined('CIVICRM_MAIL_LOG_AND_SEND')) {
          CRM_Core_Session::setStatus($testMailStatusMsg . ts('You have defined CIVICRM_MAIL_LOG - no mail will be sent.  Your %1 settings have not been tested.', [1 => strtoupper($mailerName)]), ts("Mail not sent"), "warning");
        }
        try {
          $mailer = CRM_Utils_Mail::_createMailer($mailerName, $params);
          $result = $mailer->send($toEmail, $headers, $message);
          CRM_Core_Session::setStatus($testMailStatusMsg . ts('Your %1 settings are correct. A test email has been sent to your email address.', [1 => strtoupper($mailerName)]), ts("Mail Sent"), "success");

        }
        catch (Exception $e) {
          $message = CRM_Utils_Mail::errorMessage($mailer, $result);
          CRM_Core_Session::setStatus($testMailStatusMsg . ts('Oops. Your %1 settings are incorrect. No test mail has been sent.', [1 => strtoupper($mailerName)]) . $message, ts("Mail Not Sent"), "error");

        }
```

**Comment by seamuslee001** [comment]
So this is making a change which is causing different behaviour to previous

I r-runed this locally using buildkit but with this change I am winding up with a fatal error screen rather than being redirected back to the form with an error popup.

This seems to be because the first error gets caught by the Exception but then as part of the php destruction process it triggers at least with SMTP backend a call to disconnect the SMTP connection and temporyErrorScope destruction has already reverted the error scope back to using CRM_Core_Error::handle as the callback

Even then when I commented out the destruction in temporaryErrorScope it still gives me a fatal cos it throws a PEAR Exception after it has already caught the first exception as the 2nd is coming the php destruction phase

also to @eileenmcnaughton 's point  "it can't be a PEAR_ERROR at that point as you point out. " it can and it is this is because by default our PEAR mode is not exception handling and the default callback is https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/Config.php#L89 for our unit tests we specifically override the default and use Exceptions for any PEAR errors https://github.com/civicrm/civicrm-core/blob/master/tests/phpunit/CiviTest/CiviUnitTestCase.php#L327

**Comment by eileenmcnaughton** [comment]
@seamuslee001 we need to deconstruct within a try-catch then

**Comment by seamuslee001** [comment]
@eileenmcnaughton Are you suggesting that essentially we wrap this https://github.com/pear/Mail/blob/master/Mail/smtp.php#L228 otherwise I don't know how we would intervene in the destruct phase. Also note that even then we would still need the temporaryErrorScope to convert from PEAR_ERROR to PEAR_Exception as current default behaviour of CiviCRM does not do this

**Comment by mattwire** [comment]
@seamuslee001 This seems to work by explicitly setting the temporaryErrorScope to useException. I guess once we've got no `ignoreException()` left we might be able to cleanup and remove the `useException()` calls.

@demeritcowboy I've fixed the if/else.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 if this works for you & doesn't cause further issues & you haven't solved further I'm OK merging it

I feel like you have made progress on solving a bigger issue here so if you think that is solvable we can hang back

**Comment by seamuslee001** [comment]
This works for me, I'll have a follow up PR to address an additional issue that I was talking with Tim about yesterday

**Pull request merged**
