### PR TITLE
[NFC] Fix messaging on logging/multilingual

### PR DESCRIPTION
**Pull request by MegaphoneJon**
Overview
----------------------------------------
This PR updates the messaging around enabling logging and/or multilingual capabilities.

Before
----------------------------------------
* References to unsupported MySQL versions are present.
* The *Languages, Currencies, Locations* page incorrectly tells people that advanced logging and multilingual can't both be enabled (c.f #6553).
* An API exception isn't translatable.
* Poor grammar is present.

After
----------------------------------------
All fixed.

Technical Details
----------------------------------------
lol nope

### CODE REVIEW

**Comment by demeritcowboy** [comment]
It looks like there is still a check about logging at https://github.com/civicrm/civicrm-core/blob/5.20.1/CRM/Admin/Form/Setting/Localization.php#L96, and the last time I tried multilingual with logging a few months ago I ended up getting fatal errors. I just tried it again now (enable multilingual first, then logging) and it doesn't crash right away but you still get fatal errors if you try to set available countries. So maybe it works overall, just some glitches. Anyway should the check in the line above be removed if it is mostly supported?

**Comment by MegaphoneJon** [comment]
@demeritcowboy I haven't tested logging + multilingual.  I noticed this warning on a client site, saw it was out-of-date, and did as much as I could within the scope of an `[NFC]` PR.  Based on your real-world experience, it sounds like I'm putting too much faith in #6553 doing what it says it does.

Unless someone can chime in (@monishdeb maybe?) saying that they know of a site that runs both multilingual and logging in production, I'm going to suggest we close this.

**Comment by eileenmcnaughton** [comment]
@petednz @jitendrapurohit doesn't Fuzion have both working?

**Comment by eileenmcnaughton** [comment]
The bit about the SUPER privilege actually does save some confusion for a small number of sites - this one might be sneaking into the too hard basket

**Comment by MegaphoneJon** [comment]
@eileenmcnaughton I removed the reference to the SUPER privilege because it's not needed on MySQL 5.5+, which is the minimum supported version.  I understand if folks feel differently, but I lean toward pruning references that don't apply to supported versions.

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon SUPER IS needed if you do replication - I kinda assumed that was implied by binary logging - but I guess not. We have this issue on our WMF servers

**Comment by mlutfy** [comment]
Multilingual and logging doesn't work very well.

If you try to access data from log tables from CiviCRM, CiviCRM will try to fetch from the SQL views, but they won't exist.

Discussion from the translation channel:  
https://chat.civicrm.org/civicrm/pl/xm3haw3uxbr4tpsxff68winbcc

Symbiotic runs with a patch that tries to address it, but it sometimes causes us upgrade problems:  
https://gist.github.com/mlutfy/85a4c4ae90c6a4e021d5832ef970aaeb

(I still haven't gotten around to implementing the solutions Seamus had suggested)

**Comment by MegaphoneJon** [comment]
This was meant as a trivial cleanup; I'm happy with this closed if folks aren't all on the same page on what's needed here.

**Comment by mlutfy** [comment]
It's reopening old wounds ;-)

I think it's a good cleanup. Mind keeping this bit until we figure it out?

```
{ts}(Multilingual support currently cannot be enabled on installations with enabled logging.){/ts}
```

**Comment by eileenmcnaughton** [comment]
Closing - agreed changes in https://github.com/civicrm/civicrm-core/pull/16539

**Pull request closed without merging**
