### PR TITLE
Search Builder - Enhance UI with Select2 and EntityRef

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Improves the UI of Search Builder (the classic one in core, not the new Search Kit extension) by using Select2 dropdowns for selecting options & autocompleting contacts, events, etc instead of needing to enter numeric ids.

Before
----------------------------------------
image

After
----------------------------------------
image

Technical Details
----------------------------------------
The *After* screenshot includes PR #19463 to demonstrate that this fixes the issue caused in that other PR. Note that this PR does not require that one.

Comments
----------------------------------------
This change was motivated by #19463, in which removing Campaign pseudoconstants broke the Campagn select list in Search Builder.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
I think it's an improvement except that for `Contact - ContactID` it lets you enter an id same as before, but for example `Case - CaseID` or `Participant - ContactID`, it's now a dropdown list with names which doesn't seem right.

Also there's a pre-existing issue for contributions - will make a ticket.

**Comment by colemanw** [comment]
@demeritcowboy thanks for the review. I've updated the code to not render an entityRef for an entity's own ID field.

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Comment by demeritcowboy** [comment]
Looks good.

**Comment by seamuslee001** [comment]
I'm going to merge this based on @demeritcowboy 's testing

**Comment by colemanw** [comment]
Thanks @demeritcowboy !

**Pull request merged**
