### PR TITLE
NFC cleanup to financial classes

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Just a quick cleanup of a few comments / unused variables.

Before
----------------------------------------
more messy code

After
----------------------------------------
less messy code

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
these all make sense

**Comment by eileenmcnaughton** [comment]
test fail is odd but it's hard to see how it can related

```
CRM_Contribute_BAO_ContributionTest::testcreateProportionalFinancialEntries
Exception: PEAR_Exception: "DB Error: already exists"
 * ERROR TYPE: DB_Error
 * ERROR CODE: -5
 * ERROR MESSAGE: DB Error: already exists
 * ERROR MODE: 16
 * ERROR USERINFO: INSERT INTO civicrm_financial_account
```

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by eileenmcnaughton** [comment]
This fail relates to another PR merged today (@colemanw that activity report one - the test green tick  was from before this test was added)

merging

**Pull request merged**
