### PR TITLE
Return function to only calling class

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Return function to only calling class

Before
----------------------------------------
Only 1 universe usage - which makes sense as this is low level & would not make sense to call from anywhere else. Function is very much part of what the `PrevNextCache` class does - ie manages saving dedupe matches to the prev next cache 

image

After
----------------------------------------
Moved to be private on calling class

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by colemanw** [comment]
@eileenmcnaughton some MC here too

**Comment by eileenmcnaughton** [comment]
thanks @colemanw  - fixed

**Comment by JamesBugden314** [comment]
Verified that fn is not used in universe. Change is simply scoping. Looks good to go.

**Comment by eileenmcnaughton** [comment]
@colemanw can you merge per review ^^

**Pull request merged**
