### PR TITLE
Function extraction (Move towards generic custom data support for all entities)

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Basic code clean up

 (reviewer's commit from https://github.com/civicrm/civicrm-core/pull/12088/commits/28bbc8d1c69f39a5d583d514006be29df060af61)

Before
----------------------------------------
Code not re-usable

After
----------------------------------------
Code re-usable

Technical Details
----------------------------------------
@mattwire this is a review commit of your patch here 
https://github.com/civicrm/civicrm-core/pull/12088/commits/28bbc8d1c69f39a5d583d514006be29df060af61

In general I think your patch makes sense as an extraction & I thought it worth splitting this part off & getting it merged so we could build on it. I still have thoughts about whether this is the best place for the extracted function (back to our traits experiments) but I think a refactoring can have several steps & this is a step in the right direction.

Changes I made from yours
1) I left off the change in utils.php as I didn't know the reason
2) comments changes
3) This is the significant one - I changed the order of the params in addToForm as 
  a) they didn't seem to match what was being passed in from the membership form and 
  b) it seemed that subName would be more often used

Comments
----------------------------------------
@mattwire if you confirm that you think this sub-commit is good to go I will merge as a reviewers's commit

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire to tease out a bit more of the bigger approach....

I have some thoughts - 

1) we looked at using the trait approach - (ie. this was my[ first cut ](https://github.com/civicrm/civicrm-core/compare/master...eileenmcnaughton:cust_data_al?expand=1)& you did a second one ). What I potentially LIKE about the trait approach is we could include it from the parent by simply using an 'if function exists' type function. I don't think we can 100% prevent having to 'mark' each form that we want custom data added to in some way - a property, a function, a trait inclusion or whatever - since we need to do some form of whitelisting

2) I really want to get my head around syncing the address custom data block into our overall approach - it adds  some extra challenges - but they also apply to email, phone etc blocks

3) once we have replaced those 3 repetitive lines with addCustomDataToForm I think it makes sense to re-cut the functions that make up addCustomDataToForm - there is not a great logical separation between what they do IMHO and they are hard to add a test to. I'd rather see the extraction of params from the form & urls distinct from the handling of them

4) I'm still not convinced we should enable any additional entities by default - only that they should be enable-able. (FWIW the 2 entities I currently care about are RelationshipType and Email)

5)if we are doing a lot of form-intensive testing we might want to take the chance to convert some datepicker fields on those same forms while we are at it.

**Comment by mattwire** [comment]
* ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) PASS
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __Undecided__
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) PASS
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) PASS (functions have detailed docblocks)
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) PASS (stepping stone towards common methods to add custom data to forms)
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __Undecided__: PASS (works as before)
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __Undecided__: PASS (no change for user)
* ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __Undecided__: PASS

This is a code improvement that will make it easier to add custom data to any form.

**Comment by mattwire** [comment]
@eileenmcnaughton Merge on pass

**Comment by monishdeb** [comment]
Merging as per tag.

**Pull request merged**
