### PR TITLE
Stop parsing doPayment params into class _params and access directly

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
The core AuthorizeNet implementation stores a set of parameters in the protected `$_params` class variable. It is the only payment processor that also merges the parameters passed into `doPayment()` into this class variable.

Before
----------------------------------------
Parameters from doPayment assigned to class params variable.

After
----------------------------------------
Parameters from doPayment not assigned to class params variable and passed manually to the two methods that use them.

Technical Details
----------------------------------------
The `$params` passed into doPayment are used in:
- `doPayment()`
- Child methods `_getAuthorizeNetFields()` and `doRecurPayment()`
Instead of setting them onto the class params variable pass them directly to those functions.

The class variable contains parameters that are set in the constructor and do not change such as username/password and it makes sense to keep these separate. There is no need to set the `$params` onto the class variable because they are not used anywhere else and it becomes less clear which is the "master" copy.

There is a further issue not tackled here: `$params` is copied to `$newParams` and passed to `alterPaymentProcessorParams` hook twice. But the use is inconsistent, sometimes with the original `$params` being accessed and sometimes with the potentially updated `$newParams` being accessed. This could lead to unexpected things happening if values are changed via hooks. The behaviour remains the same before/after this PR.

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire I agree this would be an improvement - but the reason I've focussed on testing Authorize.net with property bag and NOT making any changes within Authorize.net to support that is that Authorize.net is the stand in for the practices likely to be in use by processors in the wild. In particular as one of the oldest processors (along with Paypal which ideally we should do the same tests with) it is likely to have been the starting point for copy & paste

So I think we should hold off on any changes like this until we have either
a) fixed property bag to work in this pattern or
b) done a thorough audit of processors 'out there' to find out what patterns really are in use.

**Comment by mattwire** [comment]
Looking at all payment processors that I can find and excluding any that do not have a release/published code/have not been updated in the last 5 years or do not claim support for at least 4.7 I get the following list:
```
all/modules/civicrm/CRM/Core/Payment/AuthorizeNet.php
all/modules/civicrm/CRM/Core/Payment/Dummy.php
all/modules/civicrm/CRM/Core/Payment/Elavon.php
all/modules/civicrm/CRM/Core/Payment/FirstData.php
all/modules/civicrm/CRM/Core/Payment/Manual.php
all/modules/civicrm/CRM/Core/Payment/PayJunction.php
all/modules/civicrm/CRM/Core/Payment/PayPalImpl.php
all/modules/civicrm/CRM/Core/Payment/Realex.php
all/modules/civicrm/ext/ewaysingle/CRM/Core/Payment/eWAY.php
all/modules/civicrm/ext/payflowpro/CRM/Core/Payment/PayflowPro.php
all/modules/civicrm/tests/extensions/test.extension.manager.paymenttest/main.php
default/files/civicrm/ext/au.com.agileware.ewayrecurring/au_com_agileware_ewayrecurring.class.php
default/files/civicrm/ext/bitpay/CRM/Core/Payment/Bitpay.php
default/files/civicrm/ext/ca.civicrm.contributionrecur/CRM/Core/Payment/RecurOffline.php
default/files/civicrm/ext/ca.civicrm.contributionrecur/CRM/Core/Payment/RecurOfflineACHEFT.php
default/files/civicrm/ext/ca.civicrm.contributionrecur/CRM/Core/Payment/RecurOfflineBasic.php
default/files/civicrm/ext/civicrm-2checkout/CRM/Core/Payment/Twocheckout.php
default/files/civicrm/ext/civicrm-bitpay/CRM/Core/Payment/Bitpay.php
default/files/civicrm/ext/civicrm-nutritionsociety/CRM/Core/Payment/PayPalImpl.php
default/files/civicrm/ext/civicrm-stripe/CRM/Core/Payment/Stripe.php
default/files/civicrm/ext/com.donordepot.authnetecheck/CRM/Core/Payment/AuthNetCreditcard.php
default/files/civicrm/ext/com.donordepot.authnetecheck/CRM/Core/Payment/AuthNetEcheck.php
default/files/civicrm/ext/com.donordepot.authnetecheck/CRM/Core/Payment/AuthorizeNetCommon.php
default/files/civicrm/ext/com.iatspayments.civicrm/CRM/Core/Payment/Faps.php
default/files/civicrm/ext/com.iatspayments.civicrm/CRM/Core/Payment/FapsACH.php
default/files/civicrm/ext/com.iatspayments.civicrm/CRM/Core/Payment/iATSService.php
default/files/civicrm/ext/com.iatspayments.civicrm/CRM/Core/Payment/iATSServiceACHEFT.php
default/files/civicrm/ext/com.iatspayments.civicrm/CRM/Core/Payment/iATSServiceSWIPE.php
default/files/civicrm/ext/globalpayments/CRM/Core/Payment/Globalpayments.php
default/files/civicrm/ext/nz.co.fuzion.omnipaymultiprocessor/CRM/Core/Payment/OmnipayMultiProcessor.php
default/files/civicrm/ext/nz.co.fuzion.omnipaymultiprocessor/CRM/Core/Payment/PaymentExtended.php
default/files/civicrm/ext/org.civicrm.smartdebit/CRM/Core/Payment/Smartdebit.php
default/files/civicrm/ext/org.project60.sepapp/CRM/Core/Payment/SDD.php
default/files/civicrm/ext/org.project60.sepapp/CRM/Core/Payment/SDDNG.php
default/files/civicrm/ext/redsys/CRM/Core/Payment/Bizum.php
default/files/civicrm/ext/redsys/CRM/Core/Payment/Redsys.php
default/files/civicrm/ext/uk.artfulrobot.civicrm.gocardless/CRM/Core/Payment/GoCardless.php
default/files/civicrm/ext/uk.co.mjwconsult.recurmaster/CRM/Core/Payment/RecurmasterSlave.php
default/files/civicrm/ext/uk.co.nfpservice.onlineworldpay/CRM/Core/worldpaymain.php
default/files/civicrm/ext/com.pesc.usaepay/CRM/Core/Payment/usaepay.php
default/files/civicrm/ext/btcpay/CRM/Core/Payment/Btcpay.php
```

Of those about 6 had the `$_params` variable declared on the class but was not used anywhere within `CRM_Core_Payment`. I've created PRs for those cases.

The *only* two that are using it and the only two that have the getParam/setParam pattern are core AuthorizeNet and core RealEx.
RealEx does not have the problem because it does not assign via a `foreach` loop.

For AuthorizeNet I originally tried to resolve by supporting `Array Iterator` in PropertyBag but that doesn't work because an iterator won't fallback to the legacy keys so you only get a list of "propertyBag" keys in the resulting `$_params` array.
Calling setParam with a valid legacy or propertyBag key eg. `$this->_setParam('amount', 100 * $params['amount']);` will work if *either* `amount` or `total_amount` is set if `$params` is a propertyBag. If it's an array it'll only work if the actual key exists. So for RealEx passing a propertyBag into `doPayment()` actually makes it more likely to work than passing the existing inconsistent array - the change in this PR does the same for AuthorizeNet.

Note that before we actually pass a propertyBag into `doPayment()` that works with AuthorizeNet we need something like this: https://github.com/civicrm/civicrm-core/pull/17886/commits/feb7f70e23c84eed851cb6693fb836cd8c7e96c9

**Comment by eileenmcnaughton** [comment]
@mattwire that list is a good start - which are the ones you excluded? 

We have been able to avoid adding breaking changes to payment code & I have seen a few processors that I have not touched in more than 5 years turn out to be in use

**Comment by mattwire** [comment]
Excluded:
- https://civicrm.org/extensions/payleap-payment-processor - no code repo
- https://civicrm.org/extensions/paperless-transactions-ccach-payment-processor - no known installs, 5 years old
- https://civicrm.org/extensions/omngateway - last release 2012 no code repo
- https://civicrm.org/extensions/zaakpay-indian-payment-processor - last release 2013
- https://civicrm.org/extensions/zaakpay-indian-payment-processor - last release 2014
- https://civicrm.org/extensions/secure-trading-payment-processor - no repo no release
- https://civicrm.org/extensions/worldpay - no repo no release
- https://civicrm.org/extensions/payflowlink - last release 2011 no repo
- https://civicrm.org/extensions/rabobank-omnikassa-payment-processor - no release last update 5 years ago
- https://civicrm.org/extensions/paystation-payment-gateway - last update 2012 no repo
- https://civicrm.org/extensions/cm-cic-payment - last update 2014
- https://civicrm.org/extensions/paysafe - missed this one but on checking code it does not use any array iterator functions so ok.
- https://civicrm.org/extensions/ukconfpserviceonlineworldpay - last update 2015. Known to break various payment related things due to core overrides etc. - we've shipped a system check in mjwshared for 2 years now warning users to remove the worldpay extension.
- https://civicrm.org/extensions/tsys - missed this too. Uses array_key_exists on qfKey but no array iterator functions so no issue here.

**Comment by eileenmcnaughton** [comment]
OK - thanks - I'll put something together for the dev-digest to propose the canary shooting

**Comment by eileenmcnaughton** [comment]
I made a start on getting information together to put this out to the dev digest today (about 6 hours) 

Most of the time went into auditing and documenting the params that payment processors can and should currently expect - https://lab.civicrm.org/documentation/docs/dev/-/merge_requests/919/diffs - since I don't think saying 'we need to break our contract because the parameters that are expected / required to be in params are not documented' is very compelling.

I also took a dig into the code to find the minimum amount of breakage required & have 2 prs talking to jenkins which fix hte propertyBag so that authorize.net works without making any changes to it - ie we can still iterate without losing any params  (https://github.com/civicrm/civicrm-core/pull/20514 & https://github.com/civicrm/civicrm-core/pull/20511 )  They both add tests which they pass - but I won't leave them open as they are not concept approved & primarily exist as part of the documentation of this decision that the community needs to make - ie what level of contract breakage we should proceed with.

I should note my goal at this stage is to document this decision and hand it over to the community / other mergers to make a decision on this as I think that this is a key contract within our code (since it affects sites ability to receive money). When we embarked on this we thought we could avoid breakage but as we have gone along we have determined that if we actually pass the propertyBag over the doPayment 'barrier' then it's unlikely that zero sites will experience breakage.  The list above suggests it could be 'very few' (although it turns out that wmf would have been one of them if we hadn't had solid unit tests).

I'm going to aim to write this up for the digest some time over the next week

**Comment by nganivet** [comment]
One of our clients is using the CM-CIC payment processor, I checked and it will break as using both the array_merge and foreach patterns on the $params array. The stats indicate this extension is used by 10 sites, so fair but of use for an extension that is 7 years old, kudos to @eileenmcnaughton !

Here is the breakdown on usage for the other 'older' extensions:
com.groupwho.paperlesstrans.json                           0
org.civicrm.payment.payleap.json                              0
uk.co.artechconsultancy.payment.worldpay.json       2
nz.co.fuzion.payflowlink.json                                      1
nz.co.fuzion.omngateway.json                                   1
org.civicrm.payment.zaakpay.json                              1
uk.co.nfpservices.module.civicrm_SecureTrading.json   2
net.trinfinity.orgis.omnikassa.json                               3
nz.co.fuzion.paystation.json                                        6
coop.symbiotic.paysafe.json                                     14
nz.co.fuzion.cmcic.json                                             10
com.aghstrategies.tsys.json                                      98

If implementing this PR, I would therefore suggest to fully audit & correct the tsys, cmcic, paysafe and paystation extensions, and just warn the other extension authors via a direct email.

Cividesk will volunteer correcting the cmcic extension if needed/helpful.

**Comment by totten** [comment]
Related (slightly broader) discussion: https://lab.civicrm.org/dev/core/-/issues/2643

**Comment by jaapjansma** [comment]
@mattwire do you plan to work on this PR? If not can you close it? As per comment from @nganivet it requires addition work.

**Comment by nganivet** [comment]
For what it's worth, I think we should regroup to make this happen. Most of the work has already been done by @mattwire and @eileenmcnaughton, and we've already identified the -small- list of 'at-risk' extensions that need to be looked at.

I have volunteered fixing the cmcic extension, but can't volunteer for the others as I have no way to test. If the other extensions were also audited and fixed, could we get a consensus on merging this PR or are there other blocking factors?

**Comment by nganivet** [comment]
PS. the extensions are (per above posts): tsys, cmcic, paysafe and paystation.

**Comment by eileenmcnaughton** [comment]
I'm not planning on engaging more on the property bag side of things - - the reason I put a lot of work into documenting it was to hand over my involvement

**Comment by jaapjansma** [comment]
@bettydolfing and I are doing reviews of PR. We will close this PR as it requires additional work and no one is able to take on this work. We have no hard feelings about not moving this forward, as such thing might happen and over time other things might got attention or priority.

**Pull request closed without merging**
