### PR TITLE
Make reCAPTCHA settings clearer

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Make the reCAPTCHA settings a bit clearer:
- Capitalise consistently.
- Explicitly state that it is "v2 Checkbox" because you need specific keys and it didn't actually say that anywhere!

Before
----------------------------------------
image

After
----------------------------------------
image

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@MikeyMJCO any thoughts on this? The only part that seems less clear to me is the changing of the word 'keys' to 'checkbox'

**Comment by MikeyMJCO** [comment]
> @MikeyMJCO any thoughts on this? The only part that seems less clear to me is the changing of the word 'keys' to 'checkbox'

Agreed, I'd probably say this should be left with the title as "Recaptcha v2" or "Recaptcha v2 Settings".

Move the clarification that you need the specific settings for v2 checkbox to the paragraph below and/or highlight in the docs.

**Comment by mattwire** [comment]
@MikeyMJCO @eileenmcnaughton Done - see updated screenshot.

**Pull request merged**
