### PR TITLE
dev/core#4501 Redis - fix ttl on prev-next cache

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Redis - fix ttl on prev-next cache

Before
----------------------------------------
The ttl is not being set on the prevnext keys when the cache in use is `Redis`. This can been seen by doing a search in the UI via basic search or advanced search (but not search kit) and then opening up `redis-cli`.

In redis-cli you can find the keys created using the keys command

image

The ttpl for those keys can be seen with the ttl command - ie 

```
 ttl  "/prevnext/civicrm search CRMContactControllerSearch1v64jxfujuckw4g4o40kg8wcck0wscs4wskcwkck0g4gg48wws_8715/all"
```

Without this patch the `ttl` is always -1

After
----------------------------------------
Afterwards the ttl should have a value at all times - note that I testing searching along with selecting & unselecting specific contacts and deleting a contact from within the set

Technical Details
----------------------------------------
The expires was being set on the key before it was created - not doing anything. I could not find any evidence that it is possible to create an empty key & hence concluded we have to set expires first key-add. It seems redis-cli accepts expires as part of the `set` command and I think our php library supports that for the basic set - but not all the variants

Comments
----------------------------------------
tips
1) if using Redis on docker it is good to add redis-cli & redis-monitor to .bash_aliases like

```
alias redis-monitor='docker-compose --file /home/eileen/dev/fundraising-dev/docker-compose.yml exec queues redis-cli monitor'
alias redis-cli='docker-compose --file /home/eileen/dev/fundraising-dev/docker-compose.yml exec queues redis-cli'
```
2) if using `Redis` on a system with a password try something like this in .profile

```
export REDIS_PWD=totally_secret_password
alias redis-monitor='redis-cli -a $REDIS_PWD monitor'
alias redis-cli='redis-cli -a $REDIS_PWD'
```

3) you can count the keys that are on your system like this
You can also count them like this ....

```
redis-cli keys *prevnext* | wc -l
```

4) if you have had Redis running for a while you may have a build up of keys from prev-next searches (we have 35k) - there is no api action to clear these but you can use eval (via cv or drush) to clear them out

```
 cv php:eval "\Civi::service('prevnext')->deleteItem();"
```

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @johntwyman this is probably the more useful one - along with possibly https://github.com/civicrm/civicrm-core/pull/27113

**Comment by johntwyman** [comment]
Currently our Redis cache is reasonably small so I'm not seeing an absurdly high number of keys, as occasionally we go so far as to issue a `FLUSHALL` via `redis-cli`. In other words, the non-expiry of keys in our Redis cache eventually causes problems.

So I'm all for this change. Thanks @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
@johntwyman yes ' eventually' is probably fair - this has taken years to get to this point for us

**Comment by eileenmcnaughton** [comment]
@totten we have just deployed this in production & I can confirm that the ttl is now being set on the prevnext redis keys!

**Comment by totten** [comment]
@eileenmcnaughton That's pretty cool. I did some `r-run` and poked at the Redis data. TTL looks much better. :smile:  

Aside: Hadn't seen the redis `MONITOR` command before. That's pretty handy. (*It's interesting to see a few anomalies in key names, but that's by-the-by...*)

Tests are passing.

Changes are focused on Redis + PrevNext, so I don't think there's much else to test.

Let's merge it

**Comment by eileenmcnaughton** [comment]
thanks @totten - I actually have an action for parsing Redis monitor output - https://github.com/eileenmcnaughton/org.wikimedia.systemtools/blob/master/Civi/Api4/Redislog.php#L32 - it also has some parsing for the query log - https://wikitech.wikimedia.org/wiki/Fundraising/Internal-facing/CiviCRM#Performance_tracking - which is what I use for getting to the bottom of performance issues

**Pull request merged**
