### PR TITLE
CiviMail: Fix reply forwarding for mailers with From: and Return-path: limitations

### PR DESCRIPTION
**Pull request by mfb**
Overview
----------------------------------------
Depending on the email delivery provider in use, a forwarded reply could fail to send.

Before
----------------------------------------
Currently when CiviCRM forwards a reply to a mailing, it preserves the contact's email address in the From: and Return-path: headers.  However, to minimize abuse, large commercial email delivery providers typically only allow From: and Return-path: headers that use a verified address or domain.  This means the forwarded reply cannot be sent.

After
----------------------------------------
This PR instead uses `'do-not-reply@' . CRM_Core_BAO_MailSettings::defaultDomain()` as the email address in the From: and Return-path: headers so the forwarded reply can be sent.  The name is preserved in the From: header so the recipient can see who actually sent it, and the email address is preserved in the Reply-to: header so it can be replied to.

Technical Details
----------------------------------------
The error message that can be seen currently if the SMTP server does not accept the sender email address is: 

> Ignoring exception thrown by nullHandler: 10006, Failed to send data [SMTP: Invalid response code received from SMTP server while sending email.  This is often caused by a misconfiguration in Outbound Email settings. Please verify the settings at Administer CiviCRM >> Global Settings >> Outbound Email (SMTP). (code: 554, response: Message rejected: Email address is not verified...

### CODE REVIEW

**Comment by mfb** [comment]
Jenkins test this please

**Comment by mfb** [comment]
We've been running this in production for some time and it's working great, on 3 different mail servers, including AWS SES.

**Comment by eileenmcnaughton** [comment]
@mfb - this is stale - I'm gonna close it so you can re-open when re-based

**Comment by mfb** [comment]
@eileenmcnaughton I've rebased, can you re-open this or should I create a new PR?

**Comment by mfb** [comment]
IIRC there was actually a bug in GitHub where you cannot reopen a PR after it has been rebased.
You actually have to put it back to how it was, then reopen it, then you can rebase it.
Not sure if they ever fixed this...

**Comment by mfb** [comment]
Yeah I think I'd have to revert the rebase. New PR open @ #12641

**Pull request closed without merging**
