### PR TITLE
WIP: Patch civi crm host port agnostic

### PR DESCRIPTION
**Pull request by tiotsop01**
Overview
-------------------------------
Making it easy to provide the absolute system path at runtime from the environment in CiviCRM rather than hardcoded in a file

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins ok to test

**Comment by seamuslee001** [comment]
ping @totten @JoeMurray

**Comment by totten** [comment]
I know this is WIP, but JFYI - the current test failure is related to syntax in `JobTest.php`. In Github UI, click on the red "X" or or "Show all checks => Details" to drill-down to https://test.civicrm.org/job/CiviCRM-Core-PR/21015/ ; from there, the "26 new warnings" will give info.

It's often faster to check code-style locally. If you have buildkit, try [`civilint <FILE>`](https://docs.civicrm.org/dev/en/latest/tools/civilint/). Alternatively, if you like doing things from scratch:
* Install https://github.com/squizlabs/PHP_CodeSniffer 
* Clone https://github.com/civicrm/coder (which is CiviCRM's relaxed variant of the Drupal coding standard)
* Run `phpcs --standard=PATH-TO-CIVICRM-CODER/coder_sniffer/Drupal <FILE>`

**Comment by eileenmcnaughton** [comment]
How does the test fit with the proposed change? Is it included by mistake?

**Comment by tiotsop01** [comment]
@eileenmcnaughton The test is not for this change, I will fix that when the PR is ready

**Comment by eileenmcnaughton** [comment]
@tiotsop01 OK - just in general it's better not to leave PRs open for any longer than you need to in WIP status - if for no other reason than by the time it's ready for review it will no longer be near the top of the list  & may languish. 3 days is not long but if it gets more than a week I recommend closing & re-opening when ready

**Pull request closed without merging**
