### PR TITLE
CRM-19636, fixed db error for Top Donor report when filtered using Co…

### PR DESCRIPTION
**Pull request by pradpnayak**
…ntact Name, Contact sub type, Contact type etc

----------------------------------------
* CRM-19636: DB error on Top Donor Report
  https://issues.civicrm.org/jira/browse/CRM-19636

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Does using $this->getBasicContactFilters() work?

**Comment by monishdeb** [comment]
@pradpnayak can you bring the changes suggested by Eileen ?

**Comment by pradpnayak** [comment]
getBasicContactFilters() has extra filters compared to contact filters defined in Top Donor report(9 extra). Is it fine to add additional contact filters on this report?

**Comment by eileenmcnaughton** [comment]
I think so - unless one of them doesn't work. It confuses people when the filters vary by report

**Comment by pradpnayak** [comment]
@eileenmcnaughton , @monishdeb i have added the changes.

**Comment by monishdeb** [comment]
Ok, reviewing

**Comment by monishdeb** [comment]
Works fine, tested with contact filters w/o group by

**Pull request merged**
