### PR TITLE
CRM-20695 show processed token in greeting dropdown

### PR DESCRIPTION
**Pull request by sunilpawar**
https://issues.civicrm.org/jira/secure/attachment/61371/Greeting_list_with_token.png

https://issues.civicrm.org/jira/secure/attachment/61370/Greeting_list_with_processed_token.png

* [CRM-20695: show processed Greeting in drop down list](https://issues.civicrm.org/jira/browse/CRM-20695)

### CODE REVIEW

**Comment by colemanw** [comment]
@sunilpawar I'm a little unclear on the acceptance criteria for testing this. Can you describe the before/after effect of this code change? A screenshot would be helpful.

**Comment by sunilpawar** [comment]
@colemanw  I have attached image (before and after) in ticket

**Comment by eileenmcnaughton** [comment]
I just tested this & it's not actually working correctly for me - the after looks like 
screenshot 2017-12-04 18 01 47

The code may have changed since you wrote this & currently 2 open issues touch related code (one is #11095) - so I will keep looking at this as I look at those

**Comment by eileenmcnaughton** [comment]
@sunilpawar I just tested this again & it still appears to be worse with this patch than without. I think that the reason is the code has changed from the code you wrote the patch against :-( I'm going to close this & let you re-open it when you have it fixed against the latest code.

WITHOUT PATCH 
screenshot 2018-03-25 19 05 50


WITH PATCH
screenshot 2018-03-25 19 06 39

**Pull request closed without merging**
