### PR TITLE
CRM-18467: Set amount to appear on pay-later receipt

### PR DESCRIPTION
**Pull request by monishdeb**
- [CRM-18467: Amount doesn't appear on Pay Later receipt](https://issues.civicrm.org/jira/browse/CRM-18467)

### CODE REVIEW

**Comment by monishdeb** [comment]
@kenwest @eileenmcnaughton I have extended the pay later unit test to assert amount. Please have a look.

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
Looks good to me. I generally like to ensure no cludgey fix gets added without a semi-abusive comment pointing out that it is a hacky way to do it but the end result is locked in by a test - however, it's not compulsory (it is cathartic though).

I added merge on pass

**Comment by eileenmcnaughton** [comment]
unrelated fail

**Pull request merged**
