### PR TITLE
CRM-17339 master fix - Error when importing contributions matched on email

### PR DESCRIPTION
**Pull request by monishdeb**
https://issues.civicrm.org/jira/browse/CRM-17339

### CODE REVIEW

**Comment by monishdeb** [comment]
Test failure is not related

**Comment by colemanw** [comment]
After much experimentation I still don't know the "perfect" way to handle merge conflicts in github.

It looks like what you've done here is to create a new commit specifically for 4.7. Since git won't recognize it as the same commit from #6901 it will still report a conflict when we try to merge 4.6 -> master, but at least we will know that it's safe to ignore (git checkout --ours).

An alternative (what I might have done) is to checkout the master branch, merge 4.6 into it, resolve the conflict by pasting in this code, and create a PR with the result. This seems a bit "cleaner" to git because it fixes the code /and/ resolves the merge conflicts.

But it's still a bit messy in the act of doing it.

Maybe there's an even better way? I don't know. For now I'll just merge this and ignore conflicts from #6901 in the subsequent merge-forward.

**Comment by colemanw** [comment]
Interestingly git did not report a conflict while merging forward. I don't quite understand why, but nice work :)

**Comment by monishdeb** [comment]
Actually I did checkout master branch and merged 4.6 on it. Since I only need the patch of DeprecatedUtils.php file, manually resolved the conflict only on that file >> stashed the patch >>  re-applied on the same branch after cleaning >> committed and created this PR. This approach works for me in few mege-forwards I did in past but as you said, there must be a perfect way to do this :)

**Comment by colemanw** [comment]
Brilliant :+1:

**Pull request merged**
