### PR TITLE
Add html_attributes to API4 Setting

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Used to specify eg. size for an HTML element

Before
----------------------------------------
Not available via API.

After
----------------------------------------
Available via API.

Technical Details
----------------------------------------
This is a metadata field specified by the `.settings.php` metadata and does not exist in the database - like `html_type`.

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
@mattwire is the data_type really `string`?

**Comment by mattwire** [comment]
> @mattwire is the data_type really `string`?

No it's Array :-)

**Comment by colemanw** [comment]
For consistency with other APIv4 `getFields` I think it should be called `input_attrs`. E.g.:
https://github.com/civicrm/civicrm-core/blob/ea9f2153f2ec19c17a4bf8c1a826520bd1d12f84/Civi/Api4/Generic/BasicGetFieldsAction.php#L372-L375

**Comment by colemanw** [comment]
@mattwire did you see this comment ^

**Comment by mattwire** [comment]
> For consistency with other APIv4 `getFields` I think it should be called `input_attrs`. E.g.:
> 
> https://github.com/civicrm/civicrm-core/blob/ea9f2153f2ec19c17a4bf8c1a826520bd1d12f84/Civi/Api4/Generic/BasicGetFieldsAction.php#L372-L375

I'm just exposing an existing field - it's defined as `html_attributes` in lots of settings.php already

**Comment by mattwire** [comment]
@eileenmcnaughton Are you able to take a look at this one?

**Comment by eileenmcnaughton** [comment]
I don't really know how to procede with settings anymore - the last documentated agreement we had (see dev-docs) was that the data type should be 'String' and we would indicate multiple via the `serialize` key. However, we didn't agree a new way of doing it or follow the documented method in the last release so I really don't know where we are at - @totten & @demeritcowboy might...


The last understanding I had is that we were trying to push

1) settings use a simple describle data structure & we attempt to get rid of those in core that don't (we still have not 100% gotten rid of the `contribute_settings` but it is deprecated & mail store we are just treating as an outlier
2) we would describe the type of values in the settings (eg int, string) & validate and or transform them on create using the pseudoconstants / options functions
3) we provide the `Generic` settings form which works as long as people declare settings appropriately

I can see the case for getting rid of `serialize` in both settings & the schema more generally - although there is a bit of work involved - using `is_multiple` was the alternate I suggested

I also note there was some talk of being able to add a single option via `cv` - I created an issue for that to be possible via the `api4` more broadly for settings & other actions as I think it is genuinely useful albeit not as a `cv` specific feature https://lab.civicrm.org/dev/core/-/issues/4051

**Comment by mattwire** [comment]
@eileenmcnaughton I don't think this has anything to do with serialize? It's effectively a companion of "html_type" as it describes how to display the html element. Just like html_type it only exists in the xml/DAO and not in the database table.

**Comment by mattwire** [comment]
test this please

**Comment by demeritcowboy** [comment]
Yeah I guess this is a different type of thing, where the value would only ever be specified in code. One question then is is the same code that handles actual settings the same as the code that processes this use of the word Array. I'm not sure.

**Comment by mattwire** [comment]
See https://github.com/civicrm/civicrm-core/blob/master/CRM/Admin/Form/SettingTrait.php - `html_attributes` is basically passed as-is to quickform addElement functions.

**Comment by eileenmcnaughton** [comment]
Just noting - I don't think we should 'just expose existing fields' in apiv4 - I think we should get the metadata right via apiv4 - whatever that means - that's obviously requires conversation.


However, I personallly hate `input_attrs` - cost what does that even mean? I mean in this context I can assume `attrs` is an abbreviation for `attributes` but ....

**Comment by mattwire** [comment]
Here is an example of where it would be used if returned: https://github.com/eileenmcnaughton/nz.co.fuzion.civixero/blob/master/CRM/Civixero/Form/XeroAuthorize.php#L185

**Comment by eileenmcnaughton** [comment]
@totten @colemanw I think probably `is_multiple` should be primary metadata - at the apiv4 level `serialize` seems to be a stand-in for that but in fact the apiv4 consumer needs to know whether it will get back / should submit an array, not how that array is stored. Ditto the Settings.

html_attributes.class seems to have 2 functions in practice. One seems somewhat required & the other not so much

1) add the `huge` class - this kinda makes sense to me I think? Although I'm not completely sure it is about layout & telling us something about the field presentation. It is in possibly the same sort of thing as  size & font which are also suggested as html attributes but possibly a bit closer to acceptable theming?
2) adding crmSelect2 class - I think ideally we would just present them all as Select2 on the GenericSettings form & reformat the options on that form layer if the option lookup doesn't do so adequately

**Comment by mattwire** [comment]
test this please

**Comment by mattwire** [comment]
test this please

**Comment by mlutfy** [comment]
jenkins, test this please

**Pull request closed without merging**
