### PR TITLE
changed wording to Total Fee & Total Paid

### PR DESCRIPTION
**Pull request by magnolia61**
Overview
----------------------------------------
wording change for payment / refund template

Before
----------------------------------------
Total Amount
Totally Paid

After
----------------------------------------
Total Fee
Total Paid

Technical Details
----------------------------------------
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by seamuslee001** [comment]
@magnolia61  you will need to update the tests as well specifically `tests/phpunit/CRM/Contribute/Form/AdditionalPaymentTest.php` and `tests/phpunit/api/v3/PaymentTest.php`

I think this makes sense to me @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
@magnolia61 am I right in thinking calling it 'fee' is not new? I feel like it's not a great word but it was in use before we switched things up so it's 'OK'

**Comment by magnolia61** [comment]
Yeah, "fee" makes it clear here that it applies to the contribution, and is not the amount of the particular payment or refund. It makes it easy to understand the email. Also "Balance Owed"  and "Balance Due" are mixed in the templates. For now good like this I think.

**Comment by eileenmcnaughton** [comment]
OK - I'm happy with this - it's a bit rushed & it would have been nice to kick the tyres & get the 'best words' - but the words were a bit cofeffeed in that they were really misleading prior to touching this so we were starting from the point of 'it's broken' & 'not broken' is a good goal for 5.20

**Comment by eileenmcnaughton** [comment]
unrelated fail

**Pull request merged**
