### PR TITLE
SHOR-16: Fixed spacing between & table structure issues

### PR DESCRIPTION
**Pull request by mukeshcompucorp**
Overview
----------------------------------------
This PR does the following changes in  events &membership,
https://s.nimbusweb.me/share/1658463/wio5iu8bx6wh6acdboe2
https://s.nimbusweb.me/share/1658577/of6mlr257iq3cu45kax9
https://s.nimbusweb.me/share/1658623/97b6qfuzf3ykkwibgvlz

Before
----------------------------------------
rain forest cup youth soccer tournament participants training 2

After
----------------------------------------
rain forest cup youth soccer tournament participants training 3

Before
----------------------------------------
civimember training 8

After
----------------------------------------
civimember training 9

Before
----------------------------------------
civimember training 10

After
----------------------------------------
civimember training 11

### CODE REVIEW

**Comment by mattwire** [comment]
@mukeshcompucorp Probably fine. but can we have before/after screenshots with shoreditch disabled as well please?

**Comment by mukeshcompucorp** [comment]
@mattwire please see now

**Comment by mattwire** [comment]
@colemanw This is very minor html fixes. Good to merge.

**Comment by eileenmcnaughton** [comment]
merging based on @mattwire review

**Pull request merged**
