### PR TITLE
(dev/mail/8) Using ACL to restrict mailing recipients leads to fatal error

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Steps to replicate:
1. Assign an ACL permission for one or more contacts
2. Compose a mailing and select a recipient group. Ensure that those contacts are included in that group
3. Submit and Send Mailing immediately

Issue link - https://lab.civicrm.org/dev/mail/issues/8

Before
----------------------------------------
Result into fatal error - https://pastebin.com/aMa2KYy0

After
----------------------------------------
Fixed the error.

### CODE REVIEW

**Comment by seamuslee001** [comment]
@monishdeb test failures look related

**Comment by monishdeb** [comment]
Strange after fixing the test failures, it passes on local
```
Monishs-MacBook-Pro:civicrm monish$ phpunit4 tests/phpunit/CRM/Mailing/BAO/MailingTest.php 
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

.
Installing civicrm47_drupal_test database
..

Time: 19 seconds, Memory: 67.25Mb

OK (3 tests, 90 assertions)
```

But fails in Jenkin :/

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 remaining fail didn't seem related - are you up with this enough to review. Seems like it needs to be merged to this rc

NB @seamuslee001  @totten a case could be made to include it in a 5.0.1 drop. I'm agnostic - I don't think I would argue for a 5.0.1 drop specifically to include this as it was a regression in 4.7.31 rather than 5.0.0 - but since there is now a PR open for a 5.0.0 specific regression (#11975) & if this is very clear cut then I think it could go in a 5.0.1 drop on the grounds it is dealing with a critical error & it is fairly recent (only one more release ago)

**Comment by seamuslee001** [comment]
@eileenmcnaughton last time i checked the fail was related directly to Monish's test but we will see what this run does. The change looks right to me but isolated testing as the tests passing but doing something like `./tools/scripts/phpunit 'CRM_AllTests'` causes it to fail why? __flips tables__

**Comment by monishdeb** [comment]
@seamuslee001 earlier my added UT was failing because the contacts created in it was affecting other UTs in that test-case. Now when I added the data cleanup at the end of it, this should pass now. Lets see!

**Comment by monishdeb** [comment]
This is weird, now the test failure reappear again and changed nothing :/ https://test.civicrm.org/job/CiviCRM-Core-PR/20117/

If I trigger the test build then it might show different failure

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by eileenmcnaughton** [comment]
@monishdeb I found it!! Comments in this code turn out to be prescient - switch to Civi::static caching in the function below
```
  /**
   * Fill the acl contact cache for this contact id if empty.
   *
   * @param int $userID
   * @param int|string $type the type of operation (view|edit)
   * @param bool $force
   *   Should we force a recompute.
   */
  public static function cache($userID, $type = CRM_Core_Permission::VIEW, $force = FALSE) {
    // FIXME: maybe find a better way of keeping track of this. @eileen pointed out
    //   that somebody might flush the cache away from under our feet,
    //   but the alternative would be a SQL call every time this is called,
    //   and a complete rebuild if the result was an empty set...
    $_processed = array(
      CRM_Core_Permission::VIEW => array(),
      CRM_Core_Permission::EDIT => array());
```

**Comment by monishdeb** [comment]
I was not making any noise until what Jenkins has to say this time 😉

**Comment by eileenmcnaughton** [comment]
:-)

**Comment by monishdeb** [comment]
At least this is a different failure this time https://test.civicrm.org/job/CiviCRM-Core-PR/20220/

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by seamuslee001** [comment]
Permission changes look fine to me and the change in the mailing is correct IMO

**Comment by seamuslee001** [comment]
(*CiviCRM Review Template WORD-1.1*)



* ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) Pass
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) Pass
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) Pass
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) Pass
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) Pass
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))Pass i believe others have reported this fixes things for them.
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) Pass
* ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) Pass

**Comment by seamuslee001** [comment]
merging

**Comment by monishdeb** [comment]
Thanks @eileenmcnaughton @seamuslee001

**Pull request merged**
