### PR TITLE
Fix broken table in contribution_online_receipt_html.tpl

### PR DESCRIPTION
**Pull request by BorislavZlatanov**
Related JIRA issue: https://issues.civicrm.org/jira/browse/CRM-17357

### CODE REVIEW

**Comment by yashodha** [comment]
Can you please submit a patch for handling this in upgrade as well?
Thanks for the patch :)

**Comment by BorislavZlatanov** [comment]
@yashodha Sure, can you point me to the right location for that? I managed to find the templates for the install, but not sure where to look for the upgrade scripts.

**Comment by yashodha** [comment]
Sure, you need to do following steps:
1. mkdir -p *CRM/Upgrade/4.7.alpha3.msg_template/message_templates* 
2. cp  *xml/templates/message_templates/contribution_online_receipt_html.tpl* *CRM/Upgrade/4.7.alpha3.msg_template/message_templates/*
3. cp *CRM/Upgrade/4.7.alpha1.msg_template/civicrm_msg_template.tpl* *CRM/Upgrade/4.7.alpha3.msg_template/civicrm_msg_template.tpl*
4. Update **version** in CRM/Upgrade/4.7.alpha3.msg_template/civicrm_msg_template.tpl
5. Include *CRM/Upgrade/4.7.alpha3.msg_template/civicrm_msg_template.tpl* in *CRM/Upgrade/Incremental/sql/4.7.alpha3.mysql.tpl*

You can also check out PR :#6531

**Comment by colemanw** [comment]
Alpha3 has already been released - I think you mean he should target alpha4.

**Comment by BorislavZlatanov** [comment]
@yashodha I did it for alpha4, as suggested by @colemanw . Please let me know if I didn't do something right. My first time. :)

Also, I have a question. I'd like to use these fixes in production rather soon, but the stable 4.7 might come out after a while. So it makes sense to me to add the same upgrade steps for 4.6.9. I imagine the steps are exactly the same, just the version is different. Right?

**Comment by yashodha** [comment]
Yep, only version number needs to be changed.

**Comment by yashodha** [comment]
All the version references should be for 4.6.x, I can still see some for 4.7.
Also the PR has to submitted for 4.6 branch and not master.

**Comment by BorislavZlatanov** [comment]
Ah, ok, I'll close this PR and open a new one against the 4.6 branch. 

What do you mean by version references?

**Comment by yashodha** [comment]
Cool, thanks :)
I mean files like CRM/Upgrade/4.7.alpha4.msg_template/civicrm_msg_template.tpl  etc should not be there.

**Comment by BorislavZlatanov** [comment]
Closing this PR. The replacement is here: https://github.com/civicrm/civicrm-core/pull/6944

**Pull request closed without merging**
