### PR TITLE
Fully switch unit tests over to Smarty5

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
port https://github.com/civicrm/civicrm-core/pull/30644 to 5.76 - since that is where CiviCarrot is right now

### CODE REVIEW

**Comment by demeritcowboy** [comment]
This seems fine but just to clarify - civicarrot defaults to the current release candidate, but you can specify in your extension what to test against. E.g. cividiscount says master: https://lab.civicrm.org/extensions/cividiscount/-/blob/master/tests/civicarrot.json?ref_type=heads. I assume this came from deduper which has no config file. See [carrot config file docs](https://civicrm.io/node/12).

So if the only motivation is deduper, then I don't know if this is necessary.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy yeah - it's not a blocker on deduper because it actually is ALSO configured to run tests using probot & I got that working in the meantime - however, I lean to merging this just cos I think it reduces confusion

**Comment by demeritcowboy** [comment]
Ok just let me check one thing and then I'm ok to merge.
(I don't want to get into it here but in general I think there's confusion around the bootstrap.php file that civix generates because it assumes you're using buildkit and the assumptions and preloads it has. It comes up periodically in chat, and while relevant here, maybe a discussion for a different PR.)

**Comment by eileenmcnaughton** [comment]
thanks @demeritcowboy

**Comment by demeritcowboy** [comment]
FYI this alone doesn't make deduper tests run. There's something about class and table not being defined, but seems like a separate issue, possibly related to civi's schema changes.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy yeah - that seems to be because I changed the entityTypes mixin to v 2 without realising I need to convert the `entityTypes` file - I think I've switched it back now

**Pull request merged**
