### PR TITLE
Increment minimum upgradable version

### PR DESCRIPTION
**Pull request by colemanw**
Overview
-----
This changes the upgrader to only allow direct upgrades from 4.1. Previously 4.0 was "supported" but @totten and I don't think it was actually working.

Technical Notes
-----
Removes related upgrade files and hacks pertaining to upgrades previous to 4.1.3.

Anecdote
-----
Can you belive that 4.1.3 is actually the highest version of 4.1? Yes it had only *three* releases! Boy those were the days...

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I read through this & all removals relate to files pre 4.1.3 so I think it's good to merge. Agree that it's OK to ask people to upgrade through an earlier version for really old sites

**Comment by eileenmcnaughton** [comment]
@colemanw my only hesitation is documentation- is this covered somewhere?

**Comment by totten** [comment]
Relatedly, I think this change reflects reality. According to `civicrm-upgrade-test`, you currently cannot upgrade directly from 4.0 or 4.1, and the policy on test infra (for a long time) has been to test snapshots for 4.2+.

**Comment by colemanw** [comment]
@totten - actually I see `4.0.0-setupsh.sql.bz2` in the databases directory in `civicrm-upgrade-test`, but maybe that's not used. What is the lowest base version we test on infra? I think this PR should sync with that.

**Comment by seamuslee001** [comment]
@colemanw @totten @eileenmcnaughton this is the current config on the PR test bot for master branch 

`  5*|master*) UTVERS="4.2.9-multilingual_af_bg_en.mysql.bz2 4.4.0* 4.5.0* 4.6.0* 4.7.0*"`

**Comment by totten** [comment]
Yes, `4.0.0-setupsh.sql.bz2` is in there -- that's how I can see that it fails. :)

The `CiviCRM-Core-PR` job has been selecting DB snapshots for testing with this:

```bash
case "$CIVIVER" in
  4.3*)    UTVERS="4.2.9-multilingual_af_bg_en.mysql.bz2 4.3.0*" ;;
  4.4*)    UTVERS="4.2.9-multilingual_af_bg_en.mysql.bz2 4.3.0* 4.4.0*" ;;
  4.5*)    UTVERS="4.2.9-multilingual_af_bg_en.mysql.bz2 4.3.0* 4.4.0* 4.5.0*" ;;
  4.6*)    UTVERS="4.2.9-multilingual_af_bg_en.mysql.bz2 4.3.0* 4.4.0* 4.5.0* 4.6.0*" ;;
  4.7*)    UTVERS="4.2.9-multilingual_af_bg_en.mysql.bz2 4.4.0* 4.5.0* 4.6.0* 4.7.0*" ;;
  5*|master*) UTVERS="4.2.9-multilingual_af_bg_en.mysql.bz2 4.4.0* 4.5.0* 4.6.0* 4.7.0*" ;;
  *)      echo "UpgradeTest failed: Unrecognized version ($CIVIVER)" ; exit 1; ;;
esac
```

`CiviCRM-Core-Matrix` used to be similar, but now it's a bit more flexible. It uses the filter `4.2.9-multilingual_af_bg_en* "@4.2..$CIVIVER:10"` which means:

* Always include `4.2.9-multilingual_af_bg_en`
* Take the list of all the snapshots between `4.2` and the targeted `CIVIVER`. Pick up to 10 snapshots. If there are more than 10 snapshots, then pick the oldest one, the newest one element, and random in-between. Try to avoid picking multiple items in the same series.

**Comment by eileenmcnaughton** [comment]
I've proposed a related docs update https://github.com/civicrm/civicrm-sysadmin-guide/pull/78 - I think it might be more conservative that this PR - but I think that's OK.

I would support you proceeding to merge this @colemanw if you are happy with that doc update

**Pull request merged**
