### PR TITLE
core#1826: Ignore location_type_id when deduping postal address

### PR DESCRIPTION
**Pull request by MegaphoneJon**
Overview
----------------------------------------
[Core#1826](https://lab.civicrm.org/dev/core/-/issues/1826) builds on [this Stack Exchange question](https://civicrm.stackexchange.com/questions/34671/dedupe-rule-ignores-the-location-type-for-email-phone-but-does-not-ignore-for-ad), which discusses the inconsistency of location types when deduping.  Location type is ignored for emails and phones, but considered for postal address.  Per Stack Exchange, the consensus is to ignore location_type_id for postal addresses.

Before
----------------------------------------
When deduping, we don't count identical address fields (e.g. postal code) if the addresses have different location types.

After
----------------------------------------
When deduping, we **do** count identical address fields (e.g. postal code) if the addresses have different location types.

Comments
----------------------------------------
The only functional change is removing the two lines in `CRM_Dedupe_BAO_Rule`.  In the tests, I moved the `createRuleGroup()` helper method to a parent class so I could make use of it in `CRM_Dedupe_MergerTest`.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
So the only reason I can think of for this inconsistency is that address fields have a strong likelihood of crashing you db & this somewhat reduces it - e.g your grid of all the addresses with postal_code = 90210 against every other address with the same postal code will grow without this join.

However, that only mitigates the issue & don't think it is a 'reason' for this.

If you fix the style warning & tests pass I think it's OK but perhaps @pfigel @JKingsnorth have thoughts

**Comment by jitendrapurohit** [comment]
Tested and confirmed that the patch correctly avoids loc type while deduping address fields on contacts. I think this is ok to merge after warnings fixes. Thanks @MegaphoneJon 👍

**Comment by eileenmcnaughton** [comment]
Unrelated testing - merging based on @jitendrapurohit testing & discussion above

**Comment by MegaphoneJon** [comment]
test this please

**Comment by MegaphoneJon** [comment]
@eileenmcnaughton This says you're merging it but it's still open?

**Comment by MegaphoneJon** [comment]
My client did testing and realized that my patch only affected "standard" dedupe operations - but the data is passed in a different format when submitting a profile or importing.  The follow-up was easy, the test was hard.  Not sure if this needs an additional review @eileenmcnaughton @jitendrapurohit.

**Pull request merged**
