### PR TITLE
Convert Navigation cache group to current cache defition system

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This is a subset of #14487 which only coverts the navigation cache group to standard cache definition

Before
----------------------------------------
Navigation cache group used deprecated cache methods

After
----------------------------------------
Navigation cache group uses current caching definition

Technical Details
----------------------------------------
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

Comments
----------------------------------------
When doing an r-run a reviewer should test that the following can occur:

When you navigate to menu/rebuild?reset=1 the cache is appropriately cleared and re-populated
When you save the Localisation settings form check that the cache gets appropriately rebuilt. Also confirm that when you add an item to the navigation menu etc it stays there appropriately.

### CODE REVIEW

**Comment by seamuslee001** [comment]
jenkins re test this please

**Comment by seamuslee001** [comment]
Failures were 

```
api_v3_ContactTypeTest.testContactUpdateSubtypeValid with data set #0
CRM_Contact_BAO_ContactType_ContactTypeTest.testGetMethods
CRM_Contact_BAO_ContactType_ContactTypeTest.testDel
``` 

but don't seem to make sense in context of this PR

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Failure was

```
E2E_Cache_SqlGroupTest::testSetTtl
```

**Comment by seamuslee001** [comment]
@eileenmcnaughton i think this is ready for a review now

**Comment by eileenmcnaughton** [comment]
Ok - this looks good - test fail is unrelated I believe - merging

**Pull request merged**
