### PR TITLE
CRM-18405 unformat amount to do math operation

### PR DESCRIPTION
**Pull request by sunilpawar**
- [CRM-18405: When creating a contribution in the back-end, total amount is incorrect](https://issues.civicrm.org/jira/browse/CRM-18405)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I'm not loving this.

 It works - but I feel like it would be better to assign it to the tpl unformatted & then format it in the tpl. Making that change might be riskier though

**Comment by eileenmcnaughton** [comment]
ah no I take it back - what I would prefer to see is a data attribute that has the raw value & use that rather than the fomatted value. I think we made that change to the price set stuff in calculate.tpl

Mixing formatted & unformatted values seems like hard work but data attributes rock

**Comment by sunilpawar** [comment]
for new contribution, how we going to prepare raw value for total amount and fee amount, page not going to refresh and we can change amount at any time?

**Comment by eileenmcnaughton** [comment]
Hmm - just reading through CRM/Price/Form/Calculate.tpl - it has a function calculateText that does something like what you are doing (and ideally would use the same code as what you are doing) and then it assigns that to the data val

    cj('#pricevalue').data('raw-total', totalfee).trigger('change');

So I guess the question is whether you can figure out a way to share code with Calculate.tpl (which should be on all or most money pages) rather than duplicating it.

**Comment by monishdeb** [comment]
Closing in favor of https://github.com/civicrm/civicrm-core/pull/8386

**Pull request closed without merging**
