### PR TITLE
Add import function to parser

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Add import function to parser to map the mapper input to it's meaning

This function is not used in as of this PR but it is used in
https://github.com/civicrm/civicrm-core/pull/23288/

That PR is a bit stalled & getting the function added also allows
for other places to call it (ie kill off the enotices on the preview
screen and remove all the silly parameters in the construct)
so trying to get just the function merged

### CODE REVIEW

**Comment by seamuslee001** [comment]
This seems fine to me

**Comment by eileenmcnaughton** [comment]
thanks @seamuslee001

**Comment by eileenmcnaughton** [comment]
I slightly altered the function (but not the fact that the function is not called from anywhere as of this PR) - to add in the titles

**Comment by eileenmcnaughton** [comment]
Fail is new to me but clearly unrelated as the function is not called

CRM_Core_DAOTest::testSqlModePresent
Failed asserting that an array contains 'ONLY_FULL_GROUP_BY'.

**Pull request merged**
