### PR TITLE
Fixed fatal error for class not found when managed hook is invoked during upgrade

### PR DESCRIPTION
**Pull request by colemanw**
Backport of #17004 for 5.24

### CODE REVIEW

**Comment by colemanw** [comment]
Ping @totten

**Comment by colemanw** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
related fail
```
PHP Fatal error:  Uncaught PEAR_Exception: DB Error: unknown error in /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php on line 922
 DB_Error: DB Error: unknown error in unknown on line unknown
#0 /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php(922): CRM_Core_Error::exceptionHandler(Object(DB_Error))
#1 /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/packages/DB.php(998): PEAR_Error->__construct('DB Error: unkno...', -1, 16, Array, 'UPDATE civicrm_...')
#2 /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php(575): DB_Error->__construct(-1, 16, Array, 'UPDATE civicrm_...')
#3 /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php(223): PEAR->_raiseError(Object(DB_mysqli), NULL, -1, 16, Array, 'UPDATE civicrm_...', 'DB_Error', true)
#4 /home in /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/CRM/Core/Error.php on line 916

Fatal error: Uncaught PEAR_Exception: DB Error: unknown error in /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php on line 922
 DB_Error: DB Error: unknown error in /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/CRM/Core/Error.php on line 916

PEAR_Exception: DB Error: unknown error in /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/CRM/Core/Error.php on line 916

Call Stack:
    0.0008     519784   1. {main}() /home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar:0
    0.0385    9371400   2. PHPUnit\TextUI\Command::main() /home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar:570
    0.0385    9380192   3. PHPUnit\TextUI\Command->run() phar:///home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar/phpunit/TextUI/Command.php:148
    0.3945   24338632   4. PHPUnit\TextUI\TestRunner->doRun() phar:///home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar/phpunit/TextUI/Command.php:195
    0.3976   24474408   5. PHPUnit\Framework\TestSuite->run() phar:///home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar/phpunit/TextUI/TestRunner.php:545
    3.1385   58556896   6. PHPUnit\Framework\TestSuite->run() phar:///home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar/phpunit/Framework/TestSuite.php:755
    3.1404   58557480   7. api\v4\Action\ComplexQueryTest->run() phar:///home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar/phpunit/Framework/TestSuite.php:755
    3.1404   58557480   8. PHPUnit\Framework\TestResult->run() phar:///home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar/phpunit/Framework/TestCase.php:894
    3.1404   58557856   9. PHPUnit\Framework\TestResult->startTest() phar:///home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar/phpunit/Framework/TestResult.php:637
    3.1404   58557856  10. Civi\Test\CiviTestListener->startTest() phar:///home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit6/phpunit6.phar/phpunit/Framework/TestResult.php:395
    3.1404   58558272  11. Civi\Test\CiviTestListener->bootHeadless() /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/Civi/Test/CiviTestListener.php:59
    3.1404   58558272  12. api\v4\Action\ComplexQueryTest->setUpHeadless() /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/Civi/Test/CiviTestListener.php:103
    3.1454   58560584  13. api\v4\Action\ComplexQueryTest->loadDataSet() /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/tests/phpunit/api/v4/Action/ComplexQueryTest.php:41
    3.1455   58567152  14. civicrm_api4() /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/tests/phpunit/api/v4/Traits/TestDataLoaderTrait.php:52
    3.1455   58567784  15. Civi\Api4\Generic\DAOCreateAction->execute() /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/api/api.php:84
    3.1456   58567784  16. Civi\API\Kernel->runRequest() /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/Civi/Api4/Generic/AbstractAction.php:231
    3.1464   58574736  17. Civi\Api4\Provider\ActionObjectProvider->invoke() /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/Civi/API/Kernel.php:150
    3.1464   58576704  18. Civi\Api4\Generic\DAOCreateAction->_run() /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/Civi/Api4/Provider/ActionObjectProvider.php:68
    3.1499   58695512  19. Civi\Api4\Generic\DAOCreateAction->writeObjects() /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/Civi/Api4/Generic/DAOCreateAction.php:41
    3.1501   58695984  20. CRM_Contact_BAO_Contact::create() /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/Civi/Api4/Generic/Traits/DAOActionTrait.php:166
    3.1555   58707792  21. CRM_Contact_BAO_Contact::processGreetings() /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/CRM/Contact/BAO/Contact.php:421
    3.1590   58809512  22. CRM_Core_DAO::executeQuery() /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/CRM/Contact/BAO/Contact.php:2866
    3.1590   58810744  23. CRM_Core_DAO->query() /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/CRM/Core/DAO.php:1408
    3.1590   58810768  24. CRM_Core_DAO->query() /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/CRM/Core/DAO.php:421
    3.1590   58810768  25. CRM_Core_DAO->_query() /home/jenkins/bknix-dfl/build/core-17010-86f/web/sites/all/modules/civicrm/packages/DB/DataObject.php:1829
```

**Comment by eileenmcnaughton** [comment]
test this please

**Pull request merged**
