### PR TITLE
Undo breakage of multi-primary key entities

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This undoes https://github.com/civicrm/civicrm-core/pull/24287 which basically just deliberately causes something we provide partial support for not to work at all

Before
----------------------------------------
We have supported extensions creating entities with multiple primary keys via codegen for a long time. However, we have provided limited additional support and extensions have to do their own stuff to 'make it work'. https://github.com/civicrm/civicrm-core/pull/24287 changed that by adding a 'throw a fatal error if someone has tried to create a multi-primary key'

After
----------------------------------------
This rolls back https://github.com/civicrm/civicrm-core/pull/24287 & returns the behaviour to the previous behaviour for multi-primary-key entities.  I don't want to scope creep into adding more support - just to undo the random and unnecessary breakage

Technical Details
----------------------------------------
I put up an extension in a parallel PR that creates a basic entity that generates a multi-primary key using `regen` and works to create entities and also interact with contact merges. In practice we use mysql `Replace` directly to get the benefit of the primary key so are not particularly concerned by the limitations  but for `get` [we have this](https://github.com/civicrm/civicrm-core/pull/24585/files#diff-7577b4c9e1f46d7dfd10e0a2b15726c7f97f472cfd8b096443e1e8821870dd14R33-R38) to make it work
 

Comments
----------------------------------------

We should merge this 'unbreak' to the rc & probably look at the other PR with the additional tests for master

### CODE REVIEW

**Comment by seamuslee001** [comment]
@demeritcowboy I think this is the same issue you ran into

**Comment by eileenmcnaughton** [comment]
@demeritcowboy I think @totten added it cos he thought doing partial support was fugly - but breaking existing code is even more fugly

**Comment by demeritcowboy** [comment]
Ok.
In the revert though why hardcode `id`? The previous was just element `[0]`.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy yeah - going back to what it was before the rc - which works in the test in the oother PR (otherwise you get an e-notice)

**Comment by demeritcowboy** [comment]
Oh so _also_ reverting https://github.com/civicrm/civicrm-core/pull/24275.

So in <=5.53 composite keys only worked if they had a field called `id` in them, which is odd but...ok.

So ok. I've put merge-ready if @totten has anything to add.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy - it's probably fairly to say the work with limits - but the `id` actually really just protects against e-notices elsewhere - which could be addressed differently in master but my goal here was to get back to the pre rc behaviour for composite keys in the rc & anything else can be in master

**Comment by totten** [comment]
> So in <=5.53 composite keys only worked if they had a field called id in them, which is odd but...ok.

Yeah, basically this. It seems odd to me too -- if one has an `id` which is sufficiently unique+available for use with `save()`, then there's your PK (*as per normal convention*). I don't see why you'd define a composite-key on top of that. (*Uniqueness constraint, sure. Composite PK, hrm.*) Conversely, for any cases I imagine with a composite-key, it seems that `save()` would be destructive if you `save()`d with only part of the key.

But, OK, if we stipulate that there's some pre-existing arrangement where this was sensible+working... then the patch looks like it would provide continuity.

**Comment by eileenmcnaughton** [comment]
"So in <=5.53 composite keys only worked if they had a field called id in them, which is odd but...ok." - hmm not quite - it depends on the actions etc & what work arounds you have in place but we don't have an id field -

**Pull request merged**
