### PR TITLE
Run scheduled reminder job hourly

### PR DESCRIPTION
**Pull request by wmortada**
As per https://lab.civicrm.org/dev/core/-/issues/2916, daily seem too infrequent for a default.

Before
----------------------------------------
The scheduled reminder job runs daily by default.

After
----------------------------------------
The scheduled reminder job runs hourly by default.

### CODE REVIEW

**Comment by mlutfy** [comment]
I think these files also need to be updated:

```
$ grep -r "Send Scheduled Reminders" | grep -v Hourly
sql/civicrm_generated.mysql: (9,1,'Daily',NULL,NULL,'Send Scheduled Reminders','Sends out scheduled reminders via email','job','send_reminder',NULL,0),
sql/test_data_second_domain.mysql:    ( @domainID, 'Daily' ,  NULL, 'Send Scheduled Reminders',     'Sends out scheduled reminders via email',                                                     'job', 'send_reminder',           NULL, 0),
```

**Comment by wmortada** [comment]
Thanks @mlutfy I've updated those two files as well.

**Comment by eileenmcnaughton** [comment]
@mlutfy do you think this is ok now?

**Comment by mlutfy** [comment]
yep, thanks, merging!

**Pull request merged**
