### PR TITLE
Drupal bootstrap failures should throw debuggable exception

### PR DESCRIPTION
**Pull request by ErichBSchulz**
### Updated Description

Suppose one is submitting a request to a backend entry-point (such as `rest.php` or `cv`). If the system an incompatible/incomplete configuration, it could produce a hard exit with the error like `Sorry, could not locate bootstrap.inc`. However, tracing this error was often difficult because the hard exit did not report a backtrace. This makes the error condition more debuggable.

### Original Description

As [discussed with @totten](https://chat.civicrm.org/civicrm/pl/7xerz3qae7ncdeuy67czab93be) in the chat.

I'd like to fix that `error_reporting` call too but need some guidance first.

### CODE REVIEW

**Comment by totten** [comment]
jenkins, test this please

**Comment by eileenmcnaughton** [comment]
@totten can you look at this - I believe it is good-to-merge

**Comment by totten** [comment]
+1 @erichbschulz. I test a couple synthetic misconfigurations (e.g. missing `bootstrap.inc` and running `loadBootStrap()` by way of `cv`). This patch means that boot failures experienced in `cv` are easier to debug/inspect now. :)

**Review by ErichBSchulz — COMMENTED** [review]
Cool! Hope it helps someone sometime

**Pull request merged**
