### PR TITLE
Make api4 select query object more sane

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Refactoring toward adding new features to APIv4. Some cleanup is needed first.

Before
----------------------------------------
Messier, buggier.

After
----------------------------------------
Mess cleaned up, bugs fixed, more test coverage.

### CODE REVIEW

**Comment by colemanw** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@colemanw test fails relate

**Comment by eileenmcnaughton** [comment]
@colemanw  still failing

**Comment by colemanw** [comment]
@eileenmcnaughton :eyes:!

**Comment by eileenmcnaughton** [comment]
Test cover is good here....

**Pull request merged**
