### PR TITLE
Check in Riverlea extension with history from v0.7

### PR DESCRIPTION
**Pull request by ufundo**
Overview
----------------------------------------
Demo for https://github.com/civicrm/civicrm-core/pull/31389#issuecomment-2473156178

Before
----------------------------------------
- Riverlea is packaged into the tarball at distribution
- It's not included if you install with composer

After
----------------------------------------
- It's checked into the main repo

Technical Details
----------------------------------------
Created using 
```
# from civicrm-core repo
git remote add riverlea-ext https://lab.civicrm.org/extensions/riverlea.git
git fetch riverlea-ext
git checkout riverlea-ext/main
git switch -c riverlea-check-in
git filter-branch --tree-filter "mkdir -p ext/riverlea; git mv -k * ext/riverlea" HEAD
git rebase master
```
The rebase requires some manual intervention - e.g. on .gitignore, and because some of the riverlea branch history isn't totally linear.

End product can be verified with
```
rm -rf ext/riverlea
git clone https://lab.civicrm.org/extensions/riverlea.git ext/riverlea
rm -rf ext/riverlea/.git
git diff
```

Comments
----------------------------------------
This is currently missing the last few commits for 5.80.3 in the external repo.

Would prob be good to squash some of the earlier history?

### CODE REVIEW

**Comment by ufundo** [comment]
cc @vingle

**Comment by vingle** [comment]
> Would prob be good to squash some of the earlier history?

For sure - there will always be the original extension to check if needed. Happy to take your lead, otherwise [around v0.7](https://github.com/civicrm/civicrm-core/pull/31478/commits/a22e8c3bf1888bdea00d27ebb85fdfc0c4c2be82) would go back before Settings Screen & Dark Mode was added, but after Hamburg.

I'll shrink RiverLea's .gitignore a little. This PR doesn't update the dist scripts yet right - that would be another PR?

**Comment by eileenmcnaughton** [comment]
@ufundo - against 5.80 no?

**Comment by eileenmcnaughton** [comment]
Re the earlier commits - yeah - nice to squash but if it's not trivial to do I would possibly not bother?

**Comment by eileenmcnaughton** [comment]
thanks @ufundo - we also need to reverse the distmaker from 5.80

**Comment by ufundo** [comment]
Now with prefixed commit messages :grinning:

**Comment by ufundo** [comment]
> We also need to reverse the distmaker from 5.80 

Included that also

**Comment by ufundo** [comment]
Seems to be working on the test site

**Comment by eileenmcnaughton** [comment]
I've seen those fails before - but I didn't solve them - (I hit them trying to add test coverage & abandoned the attempt)

CRM_Contact_Page_View_UserDashBoardTest::testDashboardContentEmptyContact
Exception: CRM_Extension_Exception_MissingException: "Failed to find extension: civi_mail"
#0 /home/homer/buildkit/build/build-4/web/sites/all/modules/civicrm/CRM/Extension/Container/Basic.php(143): CRM_Extension_Container_Basic->getRelPath("civi_mail")
#1 /home/homer/buildkit/build/build-4/web/sites/all/modules/civicrm/CRM/Extension/Mapper.php(233): CRM_Extension_Container_Basic->getPath("civi_mail")
#2 /home/homer/buildkit/build/build-4/web/sites/all/modules/civicrm/CRM/Core/Resources.php(261): CRM_Extension_Mapper->keyToBasePath("civi_mail")

**Comment by ufundo** [comment]
Oof I am bad at remembering to lint pre MR, but that is a new personal record for style fails.

Weird about the other test. Will investigate tomorrow

**Comment by vingle** [comment]
@ufundo which version are you linting at present? v5.80.5 which came out last night? https://civicrm.org/extensions/riverlea-theme-framework

**Comment by ufundo** [comment]
Yep, 5.80.3

**Comment by vingle** [comment]
> I think it would be easier to make a separate MR to merge those if/when this is merged because the linting turns out to be non-trivial.

Tho the version where all the changes to RL are continuing to happen will have diverged from this even more by then - diffing will be v hard because of the lint change, so it would be some manual effort going thru line by line of each commit?

Would it be possible to lint lab.civicrm.org/extensions/riverlea - and apply any other changes from here needed there (ie to gitignore), so that it's relatively trivial to update this PR with the latest RiverLea when it's at merge-on-pass…?

**Comment by ufundo** [comment]
> Would it be possible to lint lab.civicrm.org/extensions/riverlea - and apply any other changes from here needed there (ie to gitignore), so that it's relatively trivial to update this PR with the latest RiverLea when it's at merge-on-pass…?

Yes, but I would wait until this is merged to do that, so you have a final fixed version of what needs to be merged back.

**Comment by ufundo** [comment]
So...

Potential contentious changes:

**Remove `&` css selectors + line breaks for `:is(a, b)`**
https://github.com/civicrm/civicrm-core/pull/31478/commits/af505c36c305cb638be488c60dd906d82221e5ad

**Linter doesn't allow empty declarations, make them explicitly empty (with `unset` - though is that right?)**
- https://github.com/civicrm/civicrm-core/pull/31478/commits/2f9d2bfaf54b1921e9bfa23cabbabe58e4dc1cb2

**Use the copy we already have for Bootstrap3 JS**
https://github.com/civicrm/civicrm-core/pull/31478/commits/fdf26735b003252c754ca0588a3af8f4686f0a8f
I'm not sure why riverlea ever had its own? But it's a dupe, and an external library so shouldn't be checked in.

**Comment by ufundo** [comment]
Outstanding issue that the linter doesn't seem to understand css variable names with numbers in them, e.g. `--crm-tabs-2-border`

That seems like something that should change at the linter end. @totten any idea how we would do that?

**Comment by vingle** [comment]
> Yes, but I would wait until this is merged to do that, so you have a final fixed version of what needs to be merged back.

I've never merged two such diverged branches before so it makes me nervous, but if you think it's possible… (or we'd just repeat the linting steps you're taking to past the tests here on RL 5.80.5?)

> Linter doesn't allow empty declarations, so this is to make them explicitly empty. Though is unset the right key to use?

I think so, but I'll need to test it. The empty css variables here are doing a mix of 'inherit' and 'initial' which is what unset is for, but there's always unexpected quirks

> Remove `&` css selectors + line breaks 

`&` is [valid CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting#child_selectors). New but valid. Could the linter need an update?

> Use the copy we already have for Bootstrap3 JS

Yes that makes sense. I have a faint memory that if a theme's JS folder is empty but overwrites bootstrap.css then it doesn't load Bootstrap JS - ie it expects to find both css and js in the theme. But that a) might have changed; b) maybe wouldn't apply to a core theme; c) my memory could be wrong. Still worth a test tho after removing.

> css variable names with numbers in them

Can always change on the extension side if not.

**Comment by totten** [comment]
> (@ufundo) Outstanding issue that the linter doesn't seem to understand css variable names with numbers in them, e.g. --crm-tabs-2-border
>
> That seems like something that should change at the linter end. @totten any idea how we would do that?

__Context__: The general substance of Civi's linter is to take [Drupal's phpcs linting rules](https://www.drupal.org/project/coder) and drop any rules that are hard-conflicts with traditional Civi code. (Drop rules that can only be satisfied by making a compatibility-break.) Additionally, it may drop a few other rules that are inconvenient (*though those are patch-welcome to fix both codebase+linter*).

__Comments__:

* I had forgotten that `phpcs` has CSS rules! But that's where these CSS rules are coming from.
* Sometimes updating to a newer ruleset will bring support for new syntax. But not this time...
* If I evaluate `ext/riverlea/core/css/_variables.css` with the current `drupal/coder`@`8.3.25` and `phpcs`@`3.11.1`, then it still presents the same errors.
* It looks like `phpcs`  [probably won't fix this](https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/605#issuecomment-2332424449) because they're deprecating the CSS linter.

__Intreventions__:

* Near term, the easiest thing is probably to disable the discontented linting rule: https://github.com/civicrm/coder/pull/20
* Long term, we may want to find some other CSS linter and [swap it in](https://github.com/civicrm/civicrm-buildkit/blob/bac0341602536dbe4c01a88172f304b1a46fa65f/bin/civilint#L196-L207).

**Comment by ufundo** [comment]
> Near term, the easiest thing is probably to disable the discontented linting rule: ruleset.xml - Opt-out of malfunctioning/deprecated CSS linting rule coder#20

Brilliant, thanks @totten !

Is there any more to do to get that through to Jenkins?

**Comment by totten** [comment]
> Is there any more to do to get that through to Jenkins?

Should be all done. But in case you're curious for future reference, the process for this change is like:

1. Update `civicrm/coder.git`
2. Update `civicrm/civicrm-buildkit.git` (`composer.json` + `composer.lock` -- pull in the new `coder` revision)
3. Deploy: Either wait a few hours (*let caches organically expire on Jenkins workers*) or force an update (*`sudo touch /etc/bknix-ci/buildkit-ts` on each worker node*)

**Comment by eileenmcnaughton** [comment]
I'm going to merge this now it is passing since I think that will give us time to QA / hit issues / adjust /follow up

**Pull request merged**
