### PR TITLE
Update Payment or receipt notification template

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Update Payment or receipt notification template

Before
----------------------------------------
Template is outputting notices on render per https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6927/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/testReport/junit/(root)/api_v3_PaymentTest/testPaymentEmailReceiptFullyPaid/

After
----------------------------------------
@demeritcowboy I'm pretty sure the notices were coming from the event location section so I copied the event section over from the online event receipt

image

Technical Details
----------------------------------------
I also added finacial trxn tokens & fixed up the preview 

image

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
[Test Result](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6936/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/testReport/) (4 failures / -36)
[api_v3_PaymentTest.testPaymentEmailReceipt](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6936/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/testReport/junit/(root)/api_v3_PaymentTest/testPaymentEmailReceipt/)
[api_v3_PaymentTest.testPaymentEmailReceiptFullyPaid](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6936/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/testReport/junit/(root)/api_v3_PaymentTest/testPaymentEmailReceiptFullyPaid/)
[api_v3_PaymentTest.testRefundEmailReceipt with data set #0](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6936/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/testReport/junit/(root)/api_v3_PaymentTest/testRefundEmailReceipt_with_data_set__0/)
[api_v3_PaymentTest.testRefundEmailReceipt with data set #1](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6936/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/testReport/junit/(root)/api_v3_PaymentTest/testRefundEmailReceipt_with_data_set__1/) fails are due to the text version removal

**Comment by eileenmcnaughton** [comment]
Notice fails 

image

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by demeritcowboy** [comment]
There's still the warnings about phone_type and phone_ext but that happens before too.

**Pull request merged**
