### PR TITLE
dev/core#67: Create Machine Name for Payment Processors

### PR DESCRIPTION
**Pull request by MiyaNoctem**
Overview
----------------------------------------
Currently, there is no reliable way to identify a payment processor, as the primary key may change from installation to installation and the name is a field that is manageable by the user and could be changed. Our specific use case is we need to be able to determine reliably if a specific payment processor is used for an extension we're building, that enables users to pay for memberships using recurring contributions, but this may also be needed in future development of CiviCRM payment processors.

Before
----------------------------------------
There was no reliable way to identify a payment processor, as both ID and name could change from installation to installation.

After
----------------------------------------
The 'key_name' field was added to payment processors so it can be used as a machine name of sorts to unequivocally identify a processor within CiviCRM code and extensions.

### CODE REVIEW

**Comment by seamuslee001** [comment]
Maybe i guess so is the thinking @MiyaNoctem that the current title or label would be the public facing one?

**Comment by guanhuan** [comment]
@mattwire  Is the class name meant to be used as machine name of the payment processors? There is no comment in the schema that explains this.

**Comment by mattwire** [comment]
@guanhuan Well the class_name will always be unique by definition - so if you just require a unique identifier for the processor type that would suffice I would think?  Unless I'm missing something?

**Comment by guanhuan** [comment]
Hi @mattwire, I don't think class_name is unique, it defines which payment class this payment processor should be using I believe. If you create more than one paypal standard payment processors, you can see the class_name fields have same value.

I actually don't think any field on payment processor table except ID field can be made unique since all payment processors have live and test modes.

**Comment by mattwire** [comment]
> Currently, there is no reliable way to identify a payment processor, as the primary key may change from installation to installation and the name is a field that is manageable by the user and could be changed. Our specific use case is we need to be able to determine reliably if a specific payment processor is used

@guanhuan Of course if you create more than one of the same type the class_name will be the same.  But I thought that was exactly what you were trying to do based on the use case described?  So if there is a difference, can you expand on your use-case to explain what you are actually trying to achieve?

**Comment by guanhuan** [comment]
Hi @mattwire,

If I understood correctly, payment processors have multi-layer structure, from top to bottom: Payment Class, Payment Processor Type and Payment Processor. The value in class_name field of Payment Processor is inherited from the value in class_name field of Payment Processor Type.

Now this structure by design enables multiple Payment Processor Types to use same Payment Class and also multiple Payment Processors to use same Payment Processor Type. CiviCRM's UI is also designed to allow admin to create multiple payment processors with the same type/ class for what ever reason: different BANK nominal account, payment method (debit card/ credit card) etc. 

If we need to build some logics around a specific Payment Processor instance, there is currently no way we can identify that specific Payment Processor expect using the primary ID. This make it difficult to refer to this payment processor instance in the code.

I think it is useful as a general improvement to have machine key for payment processors.

**Comment by mattwire** [comment]
Right.  So I think I understand what you are trying to do now - have you seen https://lab.civicrm.org/dev/financial/issues/2?  It would not really just a "machine key" but an internal name for the processor which might get used in various places.  Note that to uniquely identify a processor you may also be able to use a combination of name + username fields.

**Comment by guanhuan** [comment]
Hi Matt, thanks for the suggestion and the reference to the issue. 

I have replied to the issue separately about this. I think if the purpose of the name field is cleared up, it definitely is better than not having an identifier at all. However, I think machine key needs to be something that is not editable via UI. 

Will wait to see the result of the discussion.

**Comment by eileenmcnaughton** [comment]
You should ping in all the people on https://lab.civicrm.org/dev/financial/issues/2 - it seems to be agreed there is an issue but the spec for fixing it seems to be still open to me - I have added a note to both issues that this PR has been raised

**Comment by adixon** [comment]
The various uses of the word "payment processor" is always a problem in these discussions, it means so many different things. I think a more detailed description of why you need this would be useful, since as Matt notices there are already ways to identify uniquely all the entries in each of the relevant tables, and providing another way is bound to create future confusion and ambiguity in the core code if it gets used.

Just so we're all clear - you are talking about "payment processor instances" that correspond to the rows of the table civicrm_payment_processor.

On the other hand, there is already some nasty bits in that table that could use some cleanup, IMHO:

Here's what I'd rather do:

1. Use the existing "name" field in a manner similar to what you are talking about - i.e. a machine/internal name that is not editable, but is set uniquely in some fashion on creation. There's already a index on that field (in combination with is_test and domain_id), and I suspect that was how it was originally supposed to be used. I think people who use domains probably need to think through the implications on this one.

2. Create a separate "label" field that is used more as the public label where name is currently used (e.g. as options on the payment page). It can be populated with the existing "name" field on creation.

Certainly, the use of the existing "name" field for both the public interface identifier and the internal identifier makes things confusing when you have more than one active payment processor that you want to call "Credit Card" for the public. This is not unusual: for example when you have two payment processor accounts for separate currencies.

**Comment by eileenmcnaughton** [comment]
I think @adixon comments make a lot of sense - we possibly need TWO new fields - one for backend label & one for front end. Thanks for checking the index @adixon  - it is already uniqueish-enforced. There is precedent for either 'label' or 'title' to be used in other tables - there is precedent for frontend_title to be used in the uf_group table.

Note I feel based on previous comments about there being duplicate tickets we need to get input from the people in ticket mentioned above - notably @agh1 who logged it

**Comment by agh1** [comment]
Yeah I agree with @eileenmcnaughton that we ultimately need two new fields, for a total of three:

- a backend label
- a machine name
- a label for the option in contribution forms

I don't have strong opinions as to which of these should inherit the current `name` field.  I figure that it should probably be the machine name, and on upgrade, the value should be copied to the backend label.  I also figure the contribution form option should default to the backend label if the option label is blank.  Doing these things should result in no change for organizations who upgrade.

**Comment by guanhuan** [comment]
@adixon @eileenmcnaughton  That sounds good. If I remember correctly, the name field is already unique in UI workflow (though in the database there will always be a live entry and a test entry). As long as we define the name field as machine name and make it uneditable/ difficult to edit then that fulfils the story in this PR too.

**Comment by eileenmcnaughton** [comment]
So my understanding is 

1) add new field 'label'
2) add new field 'frontend_label'

(or alternatively the above could be title - feels less right for a processor but we have precedence for frontend_title)

and 
3) we hide the name field from the UI.

**Comment by eileenmcnaughton** [comment]
@jusfreeman I feel like this might be something you have an interest in?

**Pull request closed without merging**
