### PR TITLE
Added further tests for process_membership job: check status for inherited memberships

### PR DESCRIPTION
**Pull request by davejenx**
Overview
----------------------------------------
Added further checks for process_membership job: check that status is updated correctly for inherited membership. In function testProcessMembershipUpdateStatus.

Before
----------------------------------------
No tests for inherited membership processing.

After
----------------------------------------
Tests for inherited membership processing.

Technical Details
----------------------------------------
In existing function testProcessMembershipUpdateStatus.

Comments
----------------------------------------
Test was failing during development with inherited membership being deleted. Tracked this down to a static variable in CRM_Member_BAO_Membership::createRelatedMemberships(). There is a reset parameter for this static, so I used that to work around the problem. The issue should not occur outside tests. An alternative approach would be to replace the static variable with Civi::$statics but note reset facility is used elsewhere: CRM-17723. See CRM-4213, CRM-19735.

### CODE REVIEW

**Comment by davejenx** [comment]
@eileenmcnaughton The next instalment!

**Comment by davejenx** [comment]
@eileenmcnaughton Oops, accidentally committed cherry-picked stuff too, please don't merge until I've fixed!

**Comment by davejenx** [comment]
OK, that's reverted now. Think we're OK.

**Comment by eileenmcnaughton** [comment]
@davejenx - do you want to rebase -i to drop them out & squash the patches?

**Comment by davejenx** [comment]
@eileenmcnaughton I'm not familiar with how that's done.

**Pull request merged**
