### PR TITLE
dev/core#4555 When using a Contribution Page with a Membership Price Set, the contribution amount information never shows on the thank you page

### PR DESCRIPTION
**Pull request by alifrumin**
Overview 
------------
More info in https://lab.civicrm.org/dev/core/-/issues/4555

### CODE REVIEW

**Comment by larssandergreen** [comment]
I noticed that this same info is missing on the confirmation page too, maybe the same changes are needed there?

**Comment by MegaphoneJon** [comment]
I know it's release day - but if this is a recent regression, should it go into the rc?  I'm genuinely not sure tbh.

**Comment by alifrumin** [comment]
I updated the confirm.tpl file too.

**Comment by larssandergreen** [comment]
@MegaphoneJon It doesn't look like a recent regression in the tpl. Maybe something changed in the form class though?

**Comment by eileenmcnaughton** [comment]
There was change a few releases back that might relate - how confident are people with the change cos I think the rc would be good if people are confident - I see it has had a few eyes on

**Comment by larssandergreen** [comment]
I don't have my head wrapped around this $useForMember business, but maybe someone else does. If we're eliminating it from here, maybe it should also be eliminated from the membership online receipt, if the same change also had the same effect there (not sure, would have to be tested). Maybe it could even be eliminated entirely?

I think the regression is in 5.61, so I'm not sure it absolutely needs to be in the RC.

**Comment by alifrumin** [comment]
I agree with @larssandergreen. This fix works for the use cases I tested but I think it would be worth looking further into why it broke to begin with.

**Comment by eileenmcnaughton** [comment]
@alifrumin ok cool - there was a change in the assignemtn of `$useForMember` that caused other problems earlier - I think this has just taken longer to surface

**Comment by eileenmcnaughton** [comment]
I think the underlying problems was that I tried to figure out what useForMember meant & standardise behaviour in the related code - but it actually turned out to be one of those hacked variables that got a value shoved into it at various points to force specific behaviours

**Comment by eileenmcnaughton** [comment]
As we are about to fork 5.66 I'm gonna merge this so it is in that rc - we can target further fixes at 5.66 & do any needed backports from there

**Comment by alifrumin** [comment]
Thanks!

**Pull request merged**
