### PR TITLE
dev/financial#158  change UI parts of contribution soft schema to soft credit

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Through out the ContributionSoft.xml fields are referred to as 'Contribution Soft x' but in the UI we normally use 'Soft Credit'
When exposing these fields through Search Kit/ Afform / Metadata based functions I believe 'Soft Credit' is more meaningful

Per https://lab.civicrm.org/dev/financial/-/issues/158

Before
----------------------------------------
e.g.
```<title>Soft Contribution Amount</title>```

After
----------------------------------------
```<title>Soft Credit Amount</title>```

Technical Details
----------------------------------------
I think we did talk about having 2 titles - one for context specific places & one for non-context aware places - that might make sense

Comments
----------------------------------------
Note I've only done the xml so far - will regenerate if agreed and / or merged

### CODE REVIEW

**Comment by seamuslee001** [comment]
This makes sense to me

**Comment by eileenmcnaughton** [comment]
@seamuslee001 this was in the dev digest a week ago so I think we can take that as no dissent

**Comment by seamuslee001** [comment]
Agreed can you run `./setup.sh -g` please and then we can merge

**Comment by eileenmcnaughton** [comment]
@seamuslee001 done

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Pull request merged**
