### PR TITLE
Add a couple more weights

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
per https://github.com/civicrm/civicrm-core/pull/26244 https://github.com/civicrm/civicrm-core/pull/26241 & https://github.com/civicrm/civicrm-core/pull/26233

### CODE REVIEW

**Comment by demeritcowboy** [comment]
This seems to change the order. I definitely think Manage should be the leftmost one, not needing to scroll off to the right to get to it.
Otherwise seems ok.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy that was definitely a mistake from me looking at the row below for what the action was.

I saw some more links in the same file & added weight - I slightly re-ordered them cos it seemed like delete should last - but can change again if you prefer

**Comment by demeritcowboy** [comment]
Thanks.
It's true that there are some sites that almost never use "Assign to another client", so there's an argument for it being last. In practice it probably doesn't matter too much.
And if I understand right now you can just implement hook_links to change the weight if you want so that seems easy enough.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy yep that is the idea. I'm not wedded to re-ordering - I just wanted to add initial weights that where possible give the same actions the same weight across multiple entities - ie I'm going with view = -20, update = -10 & delete = 100 and putting delete always at the right feels consistent - but it's consistency rather than a particular order I'm trying for

**Pull request merged**
