### PR TITLE
Consolidate code to add custom fields to form

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Proposal for consolidating code for custom data on forms (initial step) 

Before
----------------------------------------
no change

After
----------------------------------------
no change

Technical Details
----------------------------------------
@mattwire looking at #11805 I'm wondering if we should do some steps like this first?

Comments
----------------------------------------

I retained

+    $this->set('type', $type);
+    $this->set('subType', $subType);
+    $this->set('entityId', $entityId);
+

But have some doubts about those lines

### CODE REVIEW

**Comment by mattwire** [comment]
Ref #11794

**Comment by mattwire** [comment]
@eileenmcnaughton This looks good... I've just proposed #11910 which takes this a little bit further.

**Comment by mattwire** [comment]
Not sure if $this->set... lines are required either.

**Comment by eileenmcnaughton** [comment]
@mattwire I'm going to close both of these as they are still both WIP. I will try to put some more time in soon & will re-open one or both when they seem merge ready

**Pull request closed without merging**
