### PR TITLE
CiviMail - Only display "Headers and Footers" if there are headers and footers

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

Anecdotally, traditional CiviMail users follow several different tactics for managing templates, such as:

1. Define 1 (or more) `Message Template`(s); each template includes a complete layout. Don't use headers or footers for layout.
2. Define 1 (or more) `Header`(s) and  `Footer`(s) with partial layouts. Don't use  `Message Template`s for layout.
3. Define a universal `Header`/`Footer` with partial layouts - and then use `Message Template`s for different content.

The importance of the "Header" and "Footer" fields vary - if you use approach (1), the headers/footers are distractions and could be completely removed from the system. For (2), they're central part of composition process. For (3), the values should be set but rarely consulted or changed. The current layout represents a compromise (making the fields always-available but not in-your-face).

This change is an optimization for scenario (1) - if you don't use headers/footers, then you should disable them, and the UI will become cleaner.

Additionally, once you have the technique of hiding the field completely, then you can consider moving the fields to a more prominent spot to improve usability for folks in scenario (2). I'm on the fence about some details, so I've left that as a matter for a different PR.

Depends: #15325
Origin: https://lab.civicrm.org/dev/core/issues/1258

Before
----------------------------------------

The "Headers and Footers" tab is *always* displayed.

Screen Shot 2019-09-18 at 1 51 22 PM

After
----------------------------------------

The "Headers and Footers" tab is only displayed if there are some headers or footers to choose from. If there aren't any, then the section is omitted.

Screen Shot 2019-09-18 at 1 51 39 PM

Comments
----------------------------------------

There are some other changes that may be good follow-ups:

* Provide some doc/help to encourage in scenario (1)
* Provide a better layout and doc/help for folks in scenario (2)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@totten are you able to rebase this now please

**Comment by yashodha** [comment]
@totten Can you please squash all your commits?

**Comment by yashodha** [comment]
@totten would be great if you could squash all commits :)

**Comment by totten** [comment]
Good point, @yashodha @seamuslee001! I've rebased so that the commit from 15325 are no longer listed -- leaving just two commits.

(I haven't re-`r-run`, but hopefully it'll be easy to try out when the autobuild test-site is available.)

**Comment by yashodha** [comment]
@totten tested this, works fine. I am merging this.

**Pull request merged**
