### PR TITLE
SearchKit - Support multiple arguments to field transformations aka SQL functions

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Enhances the SearchKit UI to allow multiple fields to be acted upon at once in a function.

Before
----------------------------------------
Field transformations only work on a single field

After
----------------------------------------
Multiple inputs can be acted upon, e.g. GREATEST or LEAST of multiple fields, or concatenating multiple fields with static strings.

Comments
----------------------------------------
Note: SQL functions still don't work with pseudoconstants. That's a known issue.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw so in testing I hit 2 things straight away

http://core-21528-8oma1.test-3.civicrm.org:8001/civicrm/admin/search#/edit/1

1) CONCAT with a null went awol - this is a pretty artificial one but I think it should still work
image

image

2) I couldn't find 'sum' in the list - eg. net_amount + fee_amount



image

**Comment by colemanw** [comment]
Yea, I think the `SUM` function in MySql only works on aggregates, and for non-aggregates you're supposed to use math operators, which APIv4 doesn't understand. Not sure the solution to that one...

**Comment by eileenmcnaughton** [comment]
@colemanw ok - so the main use case we have is the add together 2 cells one

**Comment by colemanw** [comment]
Help me think about what syntax APIv4 should support for math operations like that.

**Comment by eileenmcnaughton** [comment]
OK - I'll jump on mm in 30 mins

**Comment by eileenmcnaughton** [comment]
Discussed with @colemanw & this is not the final PR on this functionality. Merging now to make it easier to keep working on & keep testing 

This functionality is a case of the sooner it's merged the more and UI gotchas are likely to be spotted

**Pull request merged**
