### PR TITLE
CRM-19296 - Improvements in action schedule reminder activity and postemailsend with more params

### PR DESCRIPTION
**Pull request by Kajakaran**
issues
1. Reminder sent activity does not display actual email content which was sent by scheduled reminder job
2. postEmailSend hook does not have enough information if want to do more logging for reminder
3. Spool BAO does not return spoolmail object

The above issues are handled in this PR

---
- [CRM-19296: Reminder Sent acitivity and postEmailSend hook in mailing improvement](https://issues.civicrm.org/jira/browse/CRM-19296)

### CODE REVIEW

**Comment by totten** [comment]
jenkins, ok to test

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by monishdeb** [comment]
@Kajakaran can you fix the 5 style warnings mentioned in test build failure https://test.civicrm.org/job/CiviCRM-Core-PR/12020/checkstyleResult/new/ ?

**Comment by davejenx** [comment]
@Kajakaran I'm happy to review this for 4.7.15 if you can get it passing the automated tests.
@monishdeb looks like that test build no longer exists, do we need to trigger a re-test so @Kajakaran can see the style warnings?

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by davejenx** [comment]
@Kajakaran Tests have been re-run, style warnings are now at https://test.civicrm.org/job/CiviCRM-Core-PR/12984/checkstyleResult/new/ .

**Comment by jitendrapurohit** [comment]
Jenkin test this please

**Comment by jitendrapurohit** [comment]
@davejenx I've cherry-picked the commit and created a new PR fixing the style warnings at https://github.com/civicrm/civicrm-core/pull/9583. Will you be able to review it?

Thanks.

**Comment by jitendrapurohit** [comment]
This can be closed in favor of https://github.com/civicrm/civicrm-core/pull/9583

**Pull request closed without merging**
