### PR TITLE
CRM-17656 - Cannot edit activities with custom fields in popup from a…

### PR DESCRIPTION
**Pull request by jitendrapurohit**
… search results screen https://issues.civicrm.org/jira/browse/CRM-17656

### CODE REVIEW

**Comment by colemanw** [comment]
@monishdeb does this need forward-porting to `master`?

**Comment by davecivicrm** [comment]
This was a Paid Issue Queue fix (hence in 4.6). Should forward port if the bug exists in master.

**Comment by monishdeb** [comment]
@colemanw  @davecivicrm actually this is a backporting changes of https://issues.civicrm.org/jira/browse/CRM-16990. Only thing to port forward would be the webtest ``testActivityCustomData``

**Comment by davecivicrm** [comment]
Test forward ported: https://github.com/civicrm/civicrm-core/pull/7414

**Pull request merged**
