### PR TITLE
Add utils for finding nested array items

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Just adding a utility function

Before
----------------------------------------
no change

After
----------------------------------------
no change

Comments
----------------------------------------
This is a reviewers cut of #12183

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Very much more elegant!

**Comment by monishdeb** [comment]
Accurate patch + UT. Happy with the patch.

**Comment by seamuslee001** [comment]
merging as per the tag

**Comment by totten** [comment]
JFYI, we now have two versions of this functionality -- `CRM_Utils_Array::pathGet()` and `CRM_Utils_Array::pathSet()` have been around since 2015 (4.6.7).

Not really keen to push through a cleanup/reconciliation in this context... maybe we can do something for 5.5...

**Comment by colemanw** [comment]
Aww, that's a shame we all missed that. I'll do a followup PR for cleanup...

**Pull request merged**
