### PR TITLE
CRM-17860 - Align bootstrap logic in tests; looser coupling

### PR DESCRIPTION
**Pull request by totten**
Traditionally, setting up tests for CiviCRM involved various files in `tests/phpunit/CiviTest/civicrm.settings.*.php`. These files were hardwired into `CiviUnitTestCase`. If you wanted to do anything with tests in Civi, you were tied to those files.

This patch refines the mental model a bit. A developer should understand these concepts:
1. Sometimes, it's to better to run tests on a full/live with CMS and proper URLs. (Ex: End-to-end tests.) Sometimes, it is better to run tests on a headless DB. (Ex: API tests.)
2. To configure a headless DB, add an extra option to `civicrm.settings.php`.
3. At runtime, you can choose which DB to use by setting an environment variable (`CIVICRM_UF` or `CIVICRM_SETTINGS`).
   - By default, it searches for the main copy of `civicrm.settings.php` and does a full boot w/CMS.
   - If you set env var `CIVICRM_UF=UnitTests` then it will use the headless DB.
   - If you set env var `CIVICRM_SETTINGS=/path/to/something.php`, then it will use an alternative config file.
4. The above works the same way for civicrm-core and for extensions -- as long as they use  [`cv php:boot`](https://github.com/civicrm/cv) to handle bootstrap. The `cv` command can be used in tests, and it can be used manually (e.g. configuring the normal DB or the headless DB).

Nitty-gritty notes for folks familiar with current test framework:
- The wrapper `tools/scripts/phpunit` should work the same way as before. (For API/CRM/Civi tests, it uses the headless DB. For web tests, it uses the full/live/CMS-backed DB.)
- `cv php:boot` enables one to boot without any pre-knowledge of the directory structure.
- Technically, `cv` doesn't actually understand the `CIVICRM_UF` variable. Rather, the default template for `civicrm.settings.php` now includes some checks (`if CIVICRM_UF == UnitTests`).
- Previously, low-level bootstrap was triggered when `CiviUnitTestCase.php` or `CiviSeleniumTestCase.php` included `CiviTest/civicrm.settings.(local,dist).php`. This broke PHPUnit and PSR conventions; now, low-level bootstrap is triggered when `tests/phpunit/CiviTest/bootstrap.php` calls `cv`.

Example commands:

| Description | Command | Comments |
| --- | --- | --- |
| Run an API on full/CMS-backed DB | `cv api system.flush` |  |
| Run an API on headless DB | `env CIVICRM_UF=UnitTests cv api system.flush` |  |
| Run WebTests on full/CMS-backed DB | `phpunit tests/phpunit/WebTest/AllTests.php` |  |
| Run WebTests on full/CMS-backed DB | `./tools/scripts/phpunit WebTest_AllTests` | Sugary/preexisting wrapper |
| Run API Tests on full/CMS-backed DB | `phpunit tests/phpunit/api/v3/AllTests.php` | Bad idea -- `CiviUnitTestCase` tries to clobber DB. In practice, you're safe -- it will display an error instead. |
| Run API Tests on headless DB | `env CIVICRM_UF=UnitTests phpunit tests/phpunit/api/v3/AllTests.php` |  |
| Run API Tests on headless DB | `./tools/scripts/phpunit api_v3_AllTests` | Sugary/preexisting wrapper |
| Run Codeception on full/CMS-backed DB | `codecept run` | (Assumes your bootstrap code delegates to `cv`). |
| Run Codeception on headless DB | `env CIVICRM_UF=UnitTests codecept run` | (Assumes your bootstrap code delegates to `cv`). |
| Run Behat on full/CMS-backed DB | `behat` | (Assumes your bootstrap code delegates to `cv`). |
| Run Behat on headless DB | `env CIVICRM_UF=UnitTests behat` | (Assumes your bootstrap code delegates to `cv`). |

---
- [CRM-17860: More consistent, flexible handling of tests for extensions](https://issues.civicrm.org/jira/browse/CRM-17860)

### CODE REVIEW

**Comment by totten** [comment]
jenkins, test this please

**Comment by colemanw** [comment]
@totten wondering if you can either finish & merge this or else cherry-pick & merge 9c3d45c so I can run Civi unit tests again.

**Comment by totten** [comment]
Cherry-picked and submitted: https://github.com/civicrm/civicrm-core/pull/7656

**Comment by totten** [comment]
jenkins, test this please

**Pull request merged**
