### PR TITLE
Metadata - Add "civicrm_note" to "note_used_for" option group

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes API bug due to incomplete metadata.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
retest this please

**Comment by totten** [comment]
The upgrade-failures (eg https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/4668/BKPROF=dfl,SUITES=upgrade,label=bknix-tmp/testReport/junit/(root)/CivicrmUpgradeTest/CivicrmUpgradeTest_5_13_5_setupsh_mysql_bz2/) sound related.

The other failures in https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/4668/ are weird. For `phpunit-{api3,api4,crm,core-exts}`, they all say `Fatal error: Allowed memory size of 2147483648 bytes exhausted`. I don't believe the host ran out of memory. The quantity is an exact match to the `ini_set('memory_limit', '2G')` that appears in various bootstrap bits. And the error arose on two different hosts (`test-4` and `rabul-t450s`). It smells like a memory-leak. But I don't see how this PR could cause that. (Maybe some other change?) I dunno. It's worth running the test again...

**Comment by totten** [comment]
civibot, test this please

**Comment by colemanw** [comment]
> The upgrade-failures (eg https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/4668/BKPROF=dfl,SUITES=upgrade,label=bknix-tmp/testReport/junit/(root)/CivicrmUpgradeTest/CivicrmUpgradeTest_5_13_5_setupsh_mysql_bz2/) sound related.

Yea I forgot to make the callback function static 🙄

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
Test fails were interesting, I think adding the FK link from Note to Note caused it to add an infinite number of AclWhere clauses to check permissions to join itself to itself. Fixed with [58fe06e](https://github.com/civicrm/civicrm-core/pull/27396/commits/58fe06e14decb3e9e934bdfb7a9b495d91d44f45)

**Pull request merged**
