### PR TITLE
dev/core#4999 - Remove generated DAO code, use CRM_Core_DAO_Base instead

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
The sequel to https://github.com/civicrm/civicrm-core/pull/29472 - implements the replacement of generated DAO code.

Before
----------
Hundreds of DAO files full of generated code.

After
--------
Generated code replaced by a single common base class.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
now you are just showing off

image

**Comment by colemanw** [comment]
@eileenmcnaughton I'm just getting started 😁 check out #30022!

**Comment by totten** [comment]
@colemanw The first commit is... kinda massive. When it comes time to debug, it would be easier to isolate problems if the chunks are a bit smaller. Ex:

```bash
for DIR in CRM/*/DAO  ; do git commit $DIR -m "DAOs - Convert $DIR to skinny template" ; done
```

**Comment by colemanw** [comment]
@totten so if I make that change you're otherwise happy to merge this?

**Comment by totten** [comment]
@colemanw Yeah, I think so -- with one caveat. I've defined a new label `run-extended-tests`, and it should cause the server to run a supplemental series of tests (more variants with `min` and `max` rather than `dfl`; and with different UFs.)

The extended suite probably isn't passing in its baseline, so... for apples-to-apples comparison... [this should be the extended tests without the patch](https://test.civicrm.org/duderino/batch/20865906) and [this should be the extended tests for the current commit](https://test.civicrm.org/duderino/batch/20865905). Whenever you push a rebased version, it should :crossed_fingers:  fire another instance of `CiviCRM-Extended-PR` with the current patch.

**Comment by totten** [comment]
@colemanw There do appear to be regression reports when running `phpunit-core-exts` on other UFs. The symptoms are a bit varied. Interestingly, they seem to be similar among pure-composer deployments (i.e. D9, D10, and the current standalone-clean).

(*Additionally, there's also an odd failure in `backdrop-clean` + `php74m57` + `phpunit-crm` -- where PHP exhausted a 2GB memory limit. I don't if that's some fluke, or if memory usage is actually higher. I've re-fired that test to see if it repeats...*)

**Comment by totten** [comment]
Re: The failure in `backdrop-clean` + `php74m57` + `phpunit-crm` -- OK, it is clean in the baseline, and it memory-exhaustion seems consistent/reproducible with the patch. Perhaps a memory leak? Wild logs?

**Comment by totten** [comment]
Just a note for anyone following the issue (but not the PMs...), we realized the PR was editing the various DAO files... but then they would get re-generated during the test. :facepalm: The goal, of course, is to stop generating DAOs... so the PR also does that now. Consequently, the results have also changed a lot.

---

Re: `wp-demo` issues - Right now, they're all failing due to [this bootstrap error](https://github.com/civicrm/civicrm-core/assets/1336047/bb0158af-4674-464e-8a9c-52a01844a1c1). In English: during bootstrap, it needs to setup SQL cache, and this uses some DAO metadata (`CRM_Core_DAO_Cache::getTableName()`). Resolving that now triggers a bunch of other work. In particular, evaluating `Civi::paths()->getPath(`[civicrm.root]/schema/...')` - but on WordPress, this variable is more dynamic. (It reads settings - which aren't available yet at this point in bootstrap.)

One fix: don't call `getTableName()` so early:

```diff
diff --git a/CRM/Utils/Cache/SqlGroup.php b/CRM/Utils/Cache/SqlGroup.php
index dbc24d8772..627ae9d959 100644
--- a/CRM/Utils/Cache/SqlGroup.php
+++ b/CRM/Utils/Cache/SqlGroup.php
@@ -76,7 +76,8 @@ class CRM_Utils_Cache_SqlGroup implements CRM_Utils_Cache_Interface {
    * @return \CRM_Utils_Cache_SqlGroup
    */
   public function __construct($config) {
-    $this->table = CRM_Core_DAO_Cache::getTableName();
+    $this->table = 'civicrm_cache';
     if (isset($config['group'])) {
       $this->group = $config['group'];
     }
```

Alternatively, keep the early call to `getTableName()` , but don't rely on this path-variable so early.

```diff
diff --git a/Civi/Schema/EntityRepository.php b/Civi/Schema/EntityRepository.php
index 2bfdd29553..5cfece72e3 100644
--- a/Civi/Schema/EntityRepository.php
+++ b/Civi/Schema/EntityRepository.php
@@ -87,7 +87,7 @@ class EntityRepository {
 
   private static function loadCoreEntities(): array {
     $entityTypes = [];
-    $path = \Civi::paths()->getPath('[civicrm.root]/schema/*/*.entityType.php');
+    $path = dirname(__DIR__, 2) . '/schema/*/*.entityType.php';
     $files = (array) glob($path);
     foreach ($files as $file) {
       $entity = include $file;
```

To my eye, comparing the aesthetics of each, that's a wash. (*They're both slightly more hard-coded-y. But I can't think of a practical way in which they'd cause a miscalculation.*) I like how the first one gives a simpler callpath overall. __However__ the second is probably more robust -- if there are _other_ callpaths (where pre-boot code checks for DAO metadata), then the second one is more likely to work.

**Comment by totten** [comment]
Issue with `CRM_Foo_DAO_Bar::$_tableName` -- the property does have external references. Pushed up fixes for the core-references.

In universe, [there are ~6 extensions (~30 lines of code) referencing `$_tableName`](https://gist.github.com/totten/42b61d3a0e1dcd9dca5334d6cb4d25b0). Unfortunately, I don't think there's any way to use magic-methods to backfill that. But breaking them down into groups, it may be manageable:

* __Core entities__: There are only 3 core entities which get directly examined in a problematic way. We could manually add `$_tableName` back to CRM/Contact/DAO/Contact.php`, `CRM/Event/DAO/Event.php`, and `CRM/Activity/DAO/Activity.php`. (*Those are all in CiviVolunteer - so one could similarly update CiviVolunteer. Dealers choice...*)
* __Contrib entities__: Most of the time, the extension is inspecting its own entity. The core-update won't change their DAO classes. (*In the future, when they run `civix upgrade`, they'll need to fix. But the timeline on that is more generous.*)
* __Dynamic entities__: There is one extension with a dynamic lookup that would problematic.  civirules` calls `$table = $daoClass::$_tableName;`. `civirules` could switch to `getTableName()` in advance.

**Comment by colemanw** [comment]
> @totten One fix: don't call getTableName() so early:
> Alternatively, keep the early call to `getTableName()`, but don't rely on this path-variable so early.

I vote for both.

**Comment by totten** [comment]
> (@colemanw) I vote for both.

Agreed with the impulse. Looking at the new failures, it turns out that the two options were not equal. While they both seemed to work on WP, one option (dropping `CRM_Core_DAO_Cache::getTableName()`) leads to these `ts()` errors on other platforms. Why?

* The new `*.entityType.php`/`EntityRepository` stuff has an undeclared dependency on `ts()`.
* Note how `ts()` is a function - so it doesn't benefit from autoloading. In current `master`, `ts()` loads implicitly with the first DAO. (Each DAO  extends `CRM_Core_DAO`, and `DAO.php` explicitly requires `CRM/Core/I18n.php`, which defines `ts()`.)
* For some installation paths, that call to `CRM_Core_DAO_Cache::getTableName()` was the first DAO and therefore the provider of `ts()`.  It came before SQL was generated, so it masked the undeclared dependency.

We either keep the call to `CRM_Core_DAO_Cache::getTableName()`, or we load `ts()` another way. We could sprinkle-in more calls to `require_once "CRM/Core/I18n.php"`. Although... in composer-land... the idiom is to use a separate file for global-functions (e.g. with [autoload: files](https://getcomposer.org/doc/04-schema.md#files)).

I've opened a separate PR for that (#30071). In the mean-time, maybe keep this call to `CRM_Core_DAO_Cache::getTableName()` and proceed fixing other DAO issues?

**Comment by colemanw** [comment]
@totten I've gone through all the test failures. In all cases it was due to slight discrepancies between the old core/codeGen vs the new civix/convert-entity. I've submitted https://github.com/totten/civix/pull/349 to fix all those inconsistencies, regenerated the schema files in this PR, and voilà! All PR tests are now passing, although some of the extended tests are still hitting our old friend the out-of-memory error. Any ideas about that?

**Comment by totten** [comment]
@colemanw Cool. That definitely looks a lot better now.

--

I don't have any new ideas about the memory issue affecting `backdrop-clean`+`php74m57`+`phpunit-crm`. I was kinda hoping everything else might lead some to accidental improvement.  🙄 

IIRC, it had looked like the memory issue was less "backdrop" and more "php74". But let's do some more... artisanal test-runs for comparison purposes.

* [bd+php74m57+crm](https://test.civicrm.org/job/CiviCRM-Test-QLow/11758/console) (*the failure we've seen so far - which exhausts memory*)
* [bd+php80m57+crm](https://test.civicrm.org/job/CiviCRM-Test/2543/console)
* [d7+php74m57+crm](https://test.civicrm.org/job/CiviCRM-Test/2540/console)
* [wp+php74m57+crm](https://test.civicrm.org/job/CiviCRM-Test/2542/console) (*we don't often run this, so it may be noisy. but who knows, maybe it's informative*)

--

Coming back to straight phpunit failures, we're not quite off the hook yet. The combinations involving `standalone-dev`+`phpunit-core-exts` are new. They appear in both `php74`+`php82`, but [most don't appear in the baseline](https://test.civicrm.org/job/CiviCRM-Test-QLow/11832/testReport/), so that doesn't look like a fluke.

**Comment by totten** [comment]
@colemanw Re: memory-exhaustion -- With some new test-results (*linked in prior comment*), I think we can say:

* PHP version ___is___ a factor (*php74+php80 both run out of memory; php81+php82 both complete*)
* MySQL version ___is not___ factor (*php74m57 and php74m80 are the same*)
* UF ___is not___ a factor (*BD+D7+WP all affected the same*)

**Comment by colemanw** [comment]
> @totten PHP version is a factor (php74+php80 both run out of memory; php81+php82 both complete)

Well, that's not much to go on... but I wonder if it could be the case that later versions of PHP are simply masking the bug because they are more memory-efficient and so manage to make it through the test run without exhausting memory.

**Comment by totten** [comment]
@colemanw Another way to look at it: it seems like a memory-leak somewhere -- but ___where___? (Optimistically, a singular bug in one place -- eg `civicrm-core` or `phpunit` or `php` or some PECL)

One idea - I made a small patch to print out memory usage as the tests progress.

* It seems that a difference can be observed in smaller/local test-runs (on macOS or Linux). Anecdotally, I ran this patch with the first 100 tests from `CRM/Activity/` on each combination of `civicrm-core` (`master`/`noDao`) and `php` (`7.4.29`/`8.1.19`). 
    * The average memory-growth for `noDao+7.4.29` was 0.23mb/test -- much higher than the 0.1mb/test on every other configuration. (*Some memory-growth seems necessary, since PHPUnit is actually tracking test-results...*)
    * It's not quite high enough to explain everything. (Like... `phpunit-crm`  has 3500 tests, so you'd project only 825mb of leakage. `phpunit-api4` has even more tests -- 4000 tests --- yet it completes without crashing.)
    * That suggests that it's not a flat cost per-test. Some tests leaks more than others.
*  Anyway, I've pushed up that patch. Hopefully the next round of test-output will help find a bit more shape to the leak.

Aside: I tried skimming https://www.php.net/ChangeLog-8.php for memory leaks between the highest-known-bad-environment (8.0.19; circa May 2022) and the lowest-known-good-environment (8.1.19; circa May 2023). There seemed to be a dozen. You could easily rule-out half of them as things we don't use. But the list wasn't small enough or obvious enough to quickly recognize a culprit.

**Comment by colemanw** [comment]
@totten based on that last commit that printed memory usage, looking at e.g the first result from `backdrop-clean | php74m57` it appears that memory jumps up every time the database is reinstalled for a new set of tests. So maybe this PR affects that install process somehow?

**Comment by totten** [comment]
After [filtering the output](https://gist.github.com/totten/0ea1db364c1f208b75a12261430abfab), it looks like `CRM_Activity_BAO_ActivityTest` is a good example to provoke excessive memory-usage on php74/php80. (*It's not the biggest leaker, but it has a high-concentration of many sub-tests with big leaks.*) 

```bash
CIVICRM_UF=UnitTests phpunit9  --printer 'Civi\Test\TAP' tests/phpunit/CRM/Activity/Form/ActivityViewTest.php
```

For php74, it gives:

```
Installing dmastertest_hskvs schema
TAP version 13
PHPUnit 9.6.5 by Sebastian Bergmann and contributors.

Installing dmastertest_hskvs database
ok 1 - CRM_Activity_Form_ActivityViewTest::testActivityViewPreProcess
memory: 123.093 MB
ok 2 - # SKIP This test is boring.
memory: 129.902 MB
ok 3 - CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "bulkemail-text" (...
memory: 136.224 MB
ok 4 - CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "email-text" (...
memory: 143.822 MB
ok 5 - CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "inbound-text" (...
memory: 154.599 MB
ok 6 - CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "meeting-html" (...
memory: 161.615 MB
ok 7 - CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "bulkemail-html" (...
memory: 168.039 MB
ok 8 - CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "email-html" (...
memory: 174.814 MB
ok 9 - CRM_Activity_Form_ActivityViewTest::testNewlinesLookRight with data set "inbound-html" (...
memory: 182.269 MB
ok 10 - # SKIP This test is boring.
memory: 189.110 MB
```

Fun fact: This test frequently flipflops wrt activating CiviCase. (The  `setUp` calls `enableComponent('CiviCase')`, and the `tearDown` calls `disableComponent('CiviCase')`.) You can reduce the flipflopping by commenting-out `disableComponent()`, and then... the memory-leakage is ***significantly*** reduced.

| # | scenario              | Memory increase after 10 sub-tests from ActivityViewTest | 
|--|-----------------------|------------------------|
|1| php74 master          | 118-105=> +13mb (~1.3mb per test) |
|2| php82 master          | 114-104=> +10mb (~1.0mb per test) |
|3| php82 noDao           | 117-102=> +15mb (~1.5mb per test) |
|4| php74 noDao           | 189-123=> +66mb (~6.6mb per test) | 
|5| php74 noDao+disable   | 129-121=> +8mb (~0.8mb per test) |

**Comment by totten** [comment]
@colemanw Ah, missed your last comment. Agree. They point in same direction.

**Comment by totten** [comment]
Note: On a lark, I tried throwing a call to [gc_collect_cycles](https://www.php.net/manual/en/function.gc-collect-cycles.php) -- didn't help.

**Comment by totten** [comment]
Pushed up a patch to `EntityRepository` which fixes memory usage  (as measured by `ActivityViewTest` locally). By the same 10th-test metric, it's using `+14mb` (~1.4mb per test) which is close to the baseline.

It would seem that `include $file` on php81 is considerably more forgiving about repeated-reloads of the same data-file (compared to php74/php80).

**Comment by colemanw** [comment]
Fantastic @totten!
Who knew that using extra memory to stash stuff in a static var would actually save memory.

**Comment by ufundo** [comment]
Just seeing lots of the Standalone fails look permission related, and may be because the branch is missing this fix https://github.com/civicrm/civicrm-core/commit/3b09431837f89b74d4d23cbfb868f47a27ddb0bb ?

**Comment by colemanw** [comment]
@ufundo good guess. Unfortunately that's not it; this branch does contain that commit :/

**Comment by ufundo** [comment]
It seems some entity hook listeners have gone astray.

On a clean buildkit standalone-dev build on master:

```
cv ev "echo json_encode(\Civi::dispatcher()->getListeners('hook_civicrm_post::User'));"
[["CRM_Standaloneusers_BAO_User","self_hook_civicrm_post"]]
```

Switching to this branch:
```
cv ev "echo json_encode(\Civi::dispatcher()->getListeners('hook_civicrm_post::User'));"
[]
```

Given there's a few different hooked things on the Standalone User entity, I could see this causing problems!

**Comment by totten** [comment]
Wow, nice find @ufundo @colemanw.

Coleman pinged me to see if there might be a cleaner alternative to 647816709820f1c351d42131dae0dd42989a3ae6. If we revisit the topic of `CRM_Core_DAO_Cache::getTableName()` (*see [hereabouts](https://github.com/civicrm/civicrm-core/pull/29991#issuecomment-2078351073); notably, `ts` cleanup was been charged now*), then I think we can drop some conditions/code-paths instead of creating more. In local testing on `standalone-dev`, it now only calls `loadCoreEntities()` one time. I did a trial-run on #30238, and it seemed OK for D7. We'll see how it does on the extended suite.

**Comment by colemanw** [comment]
Thanks @totten that last commit indeed simplified the early-bootstrap issues & extended test runs are good! Finally merge time.

**Pull request merged**
