### PR TITLE
[REF] Convert from session status to deprecation warning

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
_A brief description of the pull request. Keep technical jargon to a minimum. Hyperlink relevant discussions._

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
OK  - this will trigger errors in tests & dev experience so that makes sense

**Comment by eileenmcnaughton** [comment]
Hmm - tests failing - I wonder if they are bad tests or a problem. I'm still in the back office participant tests but can check those next

**Comment by colemanw** [comment]
It looks like this affects 5.64. Should we backport?

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

      Failed to extract civicrm/civicrm-core:angular-jquery-dialog-service: (  
  9) '/nix/store/1455vmxwb4scsi53ahq11xxy72k35p97-unzip-6.0/bin/unzip' -qq '/  
  home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/vendor/comp  
  oser/tmp-69ab277613078138dc0d17163c85df59.zip' -d '/home/homer/buildkit/bui  
  ld/build-0/web/sites/all/modules/civicrm/vendor/composer/2e7dae9c'

**Comment by eileenmcnaughton** [comment]
I don't think the test fails relate

**Pull request merged**
