### PR TITLE
APIv4 documentation & code cleanup

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
A few tweaks and improvements to APIv4 code & documentation

After
----------------------------------------
- APIv4 Explorer now writes full OOP code for chained calls.
- Tried to clarify the docs about how `defaults` works.
- Pluralized entity name variables better (e.g. the plural of "Activity" is "Activities" not "Activitys")
- Cleaned up some unnecessary stuff from the `BasicReplaceAction` that predates the ubiquity of the `Save` action.
- Cleanup mismash of camelCase underscore_case in debug output.

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by colemanw** [comment]
test this please

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
This is ready to go; should get merged today prior to the RC branch as it fixes up some unreleased code.

**Comment by seamuslee001** [comment]
(*CiviCRM Review Template WORD-1.2*)



* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) Pass
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) Pass
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) Pass
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) Pass tested this on the PR Test site and all looks fine and the explorer looks correct to me
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) Pass
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) Pass
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) Pass
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) Pass

**Pull request merged**
