### PR TITLE
Add entity-types-php mixin

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
This adds a new mixin to scan for entity types.

Before
----------------------------------------
Entity types are pre-scanned and compiled by civix into an extension's `.civix.php` file.

After
----------------------------------------
Now there's a new mixin and civix could be adapted to take advantage of it.

### CODE REVIEW

**Comment by colemanw** [comment]
@totten What would be required to get civix to take advantage of this mixin? Currently civix writes the contents of every `*.entityType.php` directly into the `.civix.php` file and we'd want it to rip that out and use the mixin/shim instead as part of `civix upgrade`.

**Comment by eileenmcnaughton** [comment]
Could we use this as the chance for a new hook which is loaded post-boot. I feel like having a second hook for 'most' entities might help us regain some sanity

**Comment by totten** [comment]
If it's still an issue, then I'd also consider a second hook.

However, I'm not sure it's a still an issue. For a while, it was a bit of a pet-peeve for me -- because I found it rather confusing how `hook_entityTypes` would fire at weird moments. However, there are two encouraging signs:

* (Empirically) If you wrote this and did some `r-run`, then that suggests it's working. We might want to `r-run` form a few more angles (different environments/flavors of booting), but it's encouraging.
* (Analytically) Now-a-days, `CRM_Core_Config::singleton()` and `Container::boot()` start the system with a [limited dispatch policy](https://github.com/civicrm/civicrm-core/blob/6d93344eef2a43772e3042d6b337fdd76496e8dc/Civi/Core/Container.php#L606-L610) which should throw errors if `hook_entityTypes` still ran early. I did a quick breakpoint on a new build and found that `hook_entityTypes` executed after the container was fully bootstrapped. (The hook should run when there's first reflective operation on a DAO class -- and the breakpoint shows it running  as [part of this step](https://github.com/civicrm/civicrm-core/blob/62dd6eca04690eaf6cefdfe3243b66f7ad4f467a/CRM/Core/Config.php#L89) -- which clearly comes after the container booted.)

One risk to think about - if an extension taps into `hook_container` and does some kind of reflective/DAO work, then it might fire a bit sooner. But... I think that would still be OK ...  because `\CRM_Extension_System::singleton()->getMixinLoader()->run();` still runs before `hook_container`.

**Comment by colemanw** [comment]
Ok, I just tried `r-run` and didn't get very far. My steps were to:
1. Check out this branch
2. Switch SearchKit to the mixin:
```diff
diff --git a/ext/search_kit/info.xml b/ext/search_kit/info.xml
index 6b07f2c245..10ed29e3de 100644
--- a/ext/search_kit/info.xml
+++ b/ext/search_kit/info.xml
@@ -31,6 +31,7 @@
     <mixin>scan-classes@1.0.0</mixin>
     <mixin>menu-xml@1.0.0</mixin>
     <mixin>mgd-php@1.1.0</mixin>
+    <mixin>entity-types-php@1.0.0</mixin>
   </mixins>
   <civix>
     <namespace>CRM/Search</namespace>
diff --git a/ext/search_kit/search_kit.php b/ext/search_kit/search_kit.php
index c098cda2fe..27bf875ac0 100644
--- a/ext/search_kit/search_kit.php
+++ b/ext/search_kit/search_kit.php
@@ -89,7 +89,7 @@ function search_kit_civicrm_angularModules(&$angularModules) {
  * @link https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_entityTypes
  */
 function search_kit_civicrm_entityTypes(&$entityTypes) {
-  _search_kit_civix_civicrm_entityTypes($entityTypes);
+  // _search_kit_civix_civicrm_entityTypes($entityTypes);
 }
 
 /**
```
3. Type `cv flush` into the command line. Got a big stack of errors. This seems like the relevant bit:
```
#21 phar:///home/colemanw/bknix/bin/cv/src/Command/BaseCommand.php(63): civicrm_api('System', 'flush', Array)
#22 phar:///home/colemanw/bknix/bin/cv/src/Command/FlushCommand.php(37): Civi\Cv\Command\BaseCommand->callApiSuccess(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), 'System', 'flush', Array)
#23 phar:///home/colemanw/bknix/bin/cv/vendor/symfony/console/Command/Command.php(255): Civi\Cv\Command\FlushCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 phar:///home/colemanw/bknix/bin/cv/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 phar:///home/colemanw/bknix/bin/cv/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Civi\Cv\Command\FlushCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 phar:///home/colemanw/bknix/bin/cv/src/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 phar:///home/colemanw/bknix/bin/cv/vendor/symfony/console/Application.php(149): Civi\Cv\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 phar:///home/colemanw/bknix/bin/cv/src/Application.php(49): Symfony\Component\Console\Application->run()
#29 phar:///home/colemanw/bknix/bin/cv/bin/cv(27): Civi\Cv\Application::main('phar:///home/co...')
#30 /home/colemanw/bknix/bin/cv(14): require('phar:///home/co...')
#31 {main}
            [is_error] => 1
            [error_message] => Entity not loaded: SearchDisplay
```

**Comment by totten** [comment]
I've been trying this mixin with a couple other extensions and different versions of civicrm-core.  The other extensions were `mosaico` and `civigeometry`; in both cases, I made a local-only branch for the ext. (In both cases, running `civix upgrade` and then manually doing something like 8de7881b35e3f98d38b147dcf23f5a44d5dfe035.)

With `mosaico`, it generally seemed alright - because the minimum version was core@5.47.

With `civigeometry`, the minimum was a more interesting 5.13. I  didn't test that far back -- 5.27 was the test-target for some other mixins, so I tried that, but it didn't work, so I shifted further ahead to figure out the dividing line. Eventually I got more disciplined and [used some throw-away scripts to try various flows and various versions](https://gist.github.com/totten/6cde6ac11386df6ce6ca126a936d1ed3).

```
OUTCOME         COMMAND

fail            bash tmp/try-civigeo.sh new 5.38 ; echo "exit=$?"
fail            bash tmp/try-civigeo.sh new 5.43 ; echo "exit=$?"
fail            bash tmp/try-civigeo.sh new 5.44 ; echo "exit=$?"
ok              bash tmp/try-civigeo.sh new 5.45 ; echo "exit=$?"
ok              bash tmp/try-civigeo.sh new 5.47 ; echo "exit=$?"
ok              bash tmp/try-civigeo.sh new 5.48 ; echo "exit=$?"

fail            bash tmp/try-civigeo.sh quick-up 5.44 ; echo "exit=$?"
ok              bash tmp/try-civigeo.sh quick-up 5.45 ; echo "exit=$?"
ok              bash tmp/try-civigeo.sh quick-up 5.48 ; echo "exit=$?"

fail            bash tmp/try-civigeo.sh flush-up 5.44 ; echo "exit=$?"
ok              bash tmp/try-civigeo.sh flush-up 5.45 ; echo "exit=$?"
ok              bash tmp/try-civigeo.sh flush-up 5.48 ; echo "exit=$?"
```

So (based on light testing) `entity-types-php` does not work on `core <= v5.44`, but it does work on `core>= v5.45`.

(*Anecdotally, I thought I saw more interesting edges where there were momentary upgrade-failures circa 5.43-5.47, but they only appeared in some adhoc runs. When I used the more disciplined script, then that went away. It was properly a procedural inconsistency -- hence the move to scripting.*)

It's fair to add `entity-types-php` to core even if it doesn't run on ancient versions. However, there's the question of how  `civix` incorporates it. Spit-balling:

* _Wait_: Leave as-is for a bit longer.
* _Raise Minimum_: If you generate an ext with entities, then it must target `<compatibility>` at 5.45 or greater.
* _Opt-in_: If a developer opts into `civix mixin --enable=entity-types-php`, then civix can stop generating the `hook_entityTypes` stub. Otherwise, it continues generating `hook_entityTypes`.

**Comment by colemanw** [comment]
@totten it sounds like the bottom line for this PR is that you should hit the **`Merge`** button. And then we can continue discussion on the civix side.

**Comment by totten** [comment]
Added more test coverage. Merge on pass.

**Pull request merged**
