### PR TITLE
check admin menu from admin menu module is present before hiding CiviCRM menu toggle button

### PR DESCRIPTION
**Pull request by sunilpawar**
Overview
----------------------------------------
Drupal 7 provide Toolbar module to show the admin menus, but does not provide drop down option of sub menus on mouse over. There is another module which is commonly used is 'Admin Menu' which provide sub menu selection on mouse hover.

In CiviCRM, We have feature to toggle CiviCRM Menu if Drupal Admin menus are present. To check Drupal menu exist or not we refer `toolbar` module id `#toolbar`, In case site admin not using `toolbar` module and instead using 'Admin Menu' module. 

The `Admin menu` generate different id `#admin-menu`, But civicrm only checking for `#toolbar`.

So even admin menu are present CiviCRM hide the toggle button and also hide the Drupal menu.

These change make sure to check first `#toolbar` is exist, if  `#toolbar` is not present then it look for `#admin-menu`, If both not found then it hide the toggle button and Drupal Menu too.

Before
----------------------------------------
Toggle but was missing.
Screenshot 2021-01-13 at 7 53 33 PM

After
----------------------------------------
Toggle button is present

### CODE REVIEW

**Comment by colemanw** [comment]
The approach using `timeout` seems problematic. Is the timeout waiting for an ajax response?

**Comment by colemanw** [comment]
@sunilpawar ^

**Comment by colemanw** [comment]
Is the timeout waiting for an asynchronous load? If so then it will fail intermittently depending on connection speed.

**Comment by eileenmcnaughton** [comment]
@sunilpawar did you see the above question?

**Comment by eileenmcnaughton** [comment]
@sunilpawar I'm closing this & returning it to gitlab because it stalled on responding to feedback months ago - issue is https://lab.civicrm.org/dev/core/-/issues/2696 - it's also a pretty trivial amount of code so the discussion of the above is most of the work

The good thing is that if you do decide it should be re-opened your new PR will be on the front page and get attention again :-)

**Pull request closed without merging**
