### PR TITLE
Remove unneeded zendframwork/zend-validator and zendframwork/zend-stdlib packages as not required by …

### PR DESCRIPTION
**Pull request by seamuslee001**
…any other package

Overview
----------------------------------------
This removes an unneeded package from our vendor directory

Before
----------------------------------------
unneeded package included

After
----------------------------------------
unneeded package not included

ping @eileenmcnaughton

### CODE REVIEW

**Comment by seamuslee001** [comment]
It looks like both of these packages were originally required by PHPWord package https://github.com/PHPOffice/PHPWord/blob/0.13.0/composer.json#L39 however the zend-validator package was dropped for their 0.14 release https://github.com/PHPOffice/PHPWord/blob/0.14.0/composer.json#L48 and the stdlib was dropped on their 0.15 release (the version we are onto) https://github.com/PHPOffice/PHPWord/blob/0.15.0/composer.json#L60

**Comment by seamuslee001** [comment]
ping @totten @colemanw as well

**Comment by totten** [comment]
@seamuslee001 Makes sense to me. Skimming the git history of `civicrm-core:composer.lock` validates (a) that these came in for a previous version of phpword and (b) that none of the other packages are listing it as dependencies.

IMHO, if one can use the autobuild test site to do a light `r-run` and generate a doc w/phpword, then it's good to go.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test sites were gone :-(

**Comment by seamuslee001** [comment]
test site should be back now @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
Ok - I was still able to create a MS word doc on the test site so I guess all good

**Pull request merged**
