### PR TITLE
CRM-16769 Add Mapping and mappingfield API

### PR DESCRIPTION
**Pull request by mallezie**
https://issues.civicrm.org/jira/browse/CRM-16769

### CODE REVIEW

**Comment by mallezie** [comment]
The contact_type constraint was removed since that fields can also contain other values. (so as 'Participant') however tha api correctly validates on this.

**Comment by monishdeb** [comment]
Jenkin, test this please

**Comment by kurund** [comment]
jenkins, test this please

**Comment by monishdeb** [comment]
Closed in favor of https://github.com/civicrm/civicrm-core/pull/6104

**Pull request closed without merging**
