### PR TITLE
[REF] [export] . Move greeting params retrieval to the place in the code where it is used

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Moves the code that interprets greetings closer to where it is useed

Before
----------------------------------------
2 instances of the code, hard to see the usage

After
----------------------------------------
1 instance, close to usage

Technical Details
----------------------------------------
Just a cleanup

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
Good change! I was just scratching my head over that one!

**Comment by eileenmcnaughton** [comment]
Yeah it doesn't cleanup the code that much but saves future devs the same pain!

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
unrelated fail

**Pull request merged**
