### PR TITLE
Fix event fee help

### PR DESCRIPTION
**Pull request by larssandergreen**
Overview
----------------------------------------
I managed to mix up two help texts in #26291. This fixes that regression so the right help texts come up. Also removed the now unneeded titles and fixed the missing title for Payment Processor.

### CODE REVIEW

**Comment by larssandergreen** [comment]
Concurrency test fail
Jenkins test this please

**Comment by colemanw** [comment]
Cool. I'm looking to see where in the code those titles are now supplied but not spotting it...

**Comment by larssandergreen** [comment]
@colemanw It was in #26265

**Comment by colemanw** [comment]
Cool @larssandergreen I wonder how much faster CiviCRM pages would render if we switched over all help bubbles to use the field title and removed that crazy tpl file loading.

**Comment by larssandergreen** [comment]
@colemanw Yeah, it would be a good experiment to try. Ideally, you'd just specify the title inline in the tpl if you wanted something specific or there wasn't a field associated or fall back on the field label if not. In a totally ideal world, you'd just stick the help text in the schema and only have hlp files for general help, but we are a long way from that.

**Pull request merged**
