### PR TITLE
CRM-18221 filter relativize with realpath function to properly configure [civicrm.root] and [civicrm.files] on hosts with symlinked file systems

### PR DESCRIPTION
**Pull request by kcristiano**
- filter relativize with realpath function to properly configure [civicrm.root] and [civicrm.files] on hosts with symlinked file systems
- style cleanups

---
- CRM-18221: CiviCRM Resource URL causing issues on initial install with WP
  https://issues.civicrm.org/jira/browse/CRM-18221

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
How does this patch relate to #8466 ?

**Comment by kcristiano** [comment]
@eileenmcnaughton #8466 looks to be a just a nudge to users that have upgraded to 4.7 to make use of the new more portable formats.

This patch fixes issues we've encountered with WP on hosts with symlinked directories.  I would like to see both merged, but I do not see a dependancy.

**Comment by alifrumin** [comment]
@kcristiano and I tested this patch on a local wordpress build with sym-links the patch is safe it only fixes a use case on one particular host, when we expanded the use case it doesn't work, @kcristiano is going to look at it some more.

**Comment by kcristiano** [comment]
Thanks @alifrumin The patch was designed for one host in mind WP Engine and it works there.   Appreciate the testing as I want this to work on any host that has a symlinked or oddly constructed file system.

**Comment by kcristiano** [comment]
Discussed this Issue/PR at the Ft Collins Sprint with @colemanw  and @totten 

This issue and the corresponding PR solves the issue at WP Engine.   WP Engine is mounting NAS storage in the same tree and the cleanup in the PR allows the install to work correctly and CiviCRM operate as normal.

However, in testing CiviCRM in the various symlink scenarios detailed above, this path is not a solution.   For that we will need the override detailed above.   At this point I do not think we can detect a symlink during install to enable the setting, so this needs to be a fix in documentation.

My opinion is we should still merge the PR as it does solve the issue present at WP Engine.   It also has no effect on any other standard installations.

**Comment by JoeMurray** [comment]
Heh Kevin as Release Manager this month, I'm trying to recruit people to help pare down the backlog of almost 100 PRs, some going back to last summer. I'm wondering if you would be able to help QA another PR if I got someone to QA this PR and your other ones like #8536 and WordPress #103 ?

**Comment by jmilone** [comment]
I just encountered the issue which this patch fixes on another WordPress host (not WP Engine). They are build on top of Amazon and appear to have a similar architecture. Same problem, same fix works. Just wanted to report.

**Comment by kcristiano** [comment]
@jmilone Thanks for the report.  I am sure that there are other hosts/server configs that need this.   WP Engine is the only common thread I had before and I could duplicate it there.   I'd like to see this merged for the next release.

@JoeMurray I am glad to help on QA, my only reluctance is i am abroad 6/17 until 6/28.

**Comment by eileenmcnaughton** [comment]
Kevin - I feel unclear what conclusion you reached with @totten  & @colemanw  - did they agree 'better out than in' in discussion - or is there still something to resolve here

**Comment by kcristiano** [comment]
@eileenmcnaughton The end result was better out than in.   I don't think we have anything else to resolve here, I just wanted to give them a chance to chime in.

**Comment by colemanw** [comment]
Err, did you two mean "better in than out?" - I thought that was the thrust of the conversation.

**Comment by eileenmcnaughton** [comment]
Well who cares what I meant ... is this better in than out?

**Comment by colemanw** [comment]
Based on the comments above I'd say "in" but I don't have in-depth knowledge about the change. Not sure if @totten knows more about it.

**Comment by JoeMurray** [comment]
The code looks good to me, and the testing is working out. Kevin is gone till June 28 and I think we're getting caught on typos as the rest of his comments suggest in rather than out. Could we merge this?

**Comment by eileenmcnaughton** [comment]
OK - I agree - I think people did a load of digging & decided it was not the perfect fix but it was an improvement. Merging

**Pull request merged**
