### PR TITLE
Unit test for CRM-19408

### PR DESCRIPTION
**Pull request by twomice**
- [CRM-19408: Create extension.getremote API](https://issues.civicrm.org/jira/browse/CRM-19408)

### CODE REVIEW

**Comment by twomice** [comment]
Feedback welcome. Besides the test, this also creates a new direcctory test/mock/, to contain files that serve as mocks for remote URLs; I'm not sure if that's the best name or place for these files.

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by colemanw** [comment]
Test failures are unrelated.

**Comment by twomice** [comment]
Thanks, @colemanw !

**Pull request merged**
