### PR TITLE
dev/core#2742 fix group type on group create from form

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
_A brief description of the pull request. Keep technical jargon to a minimum. Hyperlink relevant discussions._

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by totten** [comment]
`r-run`: Tested locally. When creating the new group, you can toggle 2 checkboxes (leading to 2x2 permutations). I tested all 4 permutations - each seemed to work well.

**Comment by eileenmcnaughton** [comment]
@totten should this be MOP?

**Comment by totten** [comment]
@eileenmcnaughton - Needs `r-explain`. Otherwise, yeah, I think all the other criteria are met.

**Comment by totten** [comment]
@eileenmcnaughton Tests pass. Since 5.41-rc is about to branch, I'm gonna go ahead and merge this pre-description. We can fix the description post-merge.

**Pull request merged**
