### PR TITLE
CRM_Core_BAO_CMSUser - do not set time limit for PHP CLI execution

### PR DESCRIPTION
**Pull request by AronNovak**

### CODE REVIEW

**Comment by davecivicrm** [comment]
test this please

**Comment by AronNovak** [comment]
May you please consider to commit this?

**Comment by colemanw** [comment]
@AronNovak there are now 3 commits in this pull-request (and one of them is a local merge, which we try to avoid in PRs). Was that intentional?

**Comment by AronNovak** [comment]
Yes, sorry, as I prepared another pull request, I made this mistake. The only thing that was intentional is https://github.com/AronNovak/civicrm-core/commit/7c63ede147c6565eb6b9d8a171afb576ee4ca756 . Would you like that I create a new PR?

**Comment by colemanw** [comment]
I think you can avoid this by not creating PRs from your master branch.
Try this:

git checkout master
git checkout -b CMSUser
git reset --hard 7c63ede
git push origin CMSUser

Then open your pr on github from the new branch.

**Comment by AronNovak** [comment]
Thanks for the explanation.
https://github.com/civicrm/civicrm-core/pull/6045

**Pull request closed without merging**
