### PR TITLE
SearchKit - Add default text/image to displays; support custom file fields

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Allows for "placeholder" text in a search display when a column value is empty. Also works for image fields.
Image fields now support custom file fields to display images out-of-the-box.

Technical Details
----------------------------------------
This breaks out image into its own column type, and generates the url to access custom file fields.
A new 'empty_value' property allows for a placeholder text/image to display when a field is blank.

### CODE REVIEW

**Comment by colemanw** [comment]
retest this please

**Comment by jaapjansma** [comment]
test this please

**Comment by jaapjansma** [comment]
We (@kainuk, @bettydolfing and I) are reviewing PRs and we checked this PR.



* General standards
    * Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
        * __PASS__ : The goal/problem/solution have been adequately explained in the PR. This could have been explained better it tooks some guesses and what to do. We missed a step a step by instruction on how to test or reproduce this.
    * User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
        * __PASS__: The change would noticeably impact the user-experience (eg requiring retraining), however we believe it is a naturally approach.
    * Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
        * __FAIL__: The user documentation should be updated. E.g. https://docs.civicrm.org/user/en/latest/the-user-interface/search-kit/#search-displays
    * Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
        * __PASS__: We created a new search with search kit and included a custom file field and displayed this as an image. We also provided a default image for when the field was empty. We then checked the output of the display and it all seemed to work. 
* Developer standards
    * Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
        * __PASS__: The change potentially affects compatibility, but the risks have been sufficiently managed.
    * Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
        * __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
    * Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
        * __PASS__: The change sufficiently improves test coverage.
    * Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
        * __PASS__: The test results are all-clear.

@colemanw can you also update the user documentation?

Although we miss the update for the user documentation we believe this PR is ready to be merged. @demeritcowboy what do you think?

**Comment by colemanw** [comment]
Thanks for the review @jaapjansma!
I will try to write some docs when I get time, but right now I'm focused on building out features for SearchKit.
It would be nice to organize a docs sprint just for SearchKit now that people are really using it.

**Pull request merged**
