### PR TITLE
dev/core/-/issues/1794, changed int to tinyint for boolean fields

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/1794

Before
----------------------------------------
Deselected value is not saved

After
----------------------------------------
Deselected value is saved

### CODE REVIEW

**Comment by seamuslee001** [comment]
@pradpnayak can you fix the upgrade 

```
diff --git a/CRM/Upgrade/Incremental/sql/5.27.alpha1.mysql.tpl b/CRM/Upgrade/Incremental/sql/5.27.alpha1.mysql.tpl
index 6b785a4698..b2364e975c 100644
--- a/CRM/Upgrade/Incremental/sql/5.27.alpha1.mysql.tpl
+++ b/CRM/Upgrade/Incremental/sql/5.27.alpha1.mysql.tpl
@@ -6,5 +6,5 @@ WHERE html_type LIKE 'Multi-%' OR html_type = 'CheckBox';
 ALTER TABLE `civicrm_contribution_recur` CHANGE `amount` `amount` DECIMAL( 20,2 ) COMMENT 'Amount to be collected (including any sales tax) by payment processor each recurrence.';

 -- dev/core/-/issues/1794
-ALTER TABLE `civicrm_custom_group` CHANGE `collapse_adv_display` `collapse_adv_display` TINYINT(4) UNSIGNED NULL DEFAULT '0' COMMENT 'Will this group be in collapsed or expanded mode on advanced search display ?’;
+ALTER TABLE `civicrm_custom_group` CHANGE `collapse_adv_display` `collapse_adv_display` TINYINT(4) UNSIGNED NULL DEFAULT '0' COMMENT 'Will this group be in collapsed or expanded mode on advanced search display ?';
 ALTER TABLE `civicrm_custom_group` CHANGE `collapse_display` `collapse_display` TINYINT(4) UNSIGNED NULL DEFAULT '0' COMMENT 'Will this group be in collapsed or expanded mode on initial display ?';
```

**Comment by pradpnayak** [comment]
Hi @samuelsov 
i have now pushed the fix

**Comment by colemanw** [comment]
@pradpnayak this is obviously more correct for the schema, but I'm just curious to know why this broke the checkbox on the form. Either way the field would be able to store a 1 or a 0.

**Comment by pradpnayak** [comment]
Hi @colemanw , recent change in DB package(i.e 5.23) caused the regression. I believe if the field is boolean it can be either 0 or 1 even though the value for the field in $param is set as null(NULL when unchecked), but incase of type integer the NULL value is ignored unless you pass as a string.

**Comment by pradpnayak** [comment]
Hi @colemanw 

This caused since 5.23 as there was DB package update. Previously if the data type was int and is empty than it would have set to 0 using intval() function, when a field is unchecked its set to empty. But newer version excludes update if the data type is int and is empty. 

Older version:
https://github.com/civicrm/civicrm-packages/blob/5.22/DB/DataObject.php#L1204

Newer version: 
https://github.com/civicrm/civicrm-packages/blob/master/DB/DataObject.php#L1415

**Pull request merged**
