### PR TITLE
Contact tokens - Implement fall back from billing address to primary address

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This fixes the tokens for the contact to provide data from the Primary address if no billing address exists. The billing address is a bit of an odd ball because it feels like they meant to implement 'is_billing' like 'is_primary' whereby each contact has exactly one at all times but somehow didn't quite do that. In the few places it is used in the code it is treated is 'get the best address to use for billing, treating is_billing as best, but use is_primary as a fall back' This is how the invoice class handles it - which is the class that has a need for these tokens

Before
----------------------------------------
billing tokens are empty if the contact has a primary address but not billing address

After
----------------------------------------
billing tokens fall back to the primary address where there is no billing address.

Technical Details
----------------------------------------
The billing address tokens were added a while back to be used from WorkflowMessage templates but have not been put in use as yet because most of the templates use the address attached to the contribution

On attempting to swap them out I found that the billing tokens have been broken for a while - fixed in https://github.com/civicrm/civicrm-core/pull/29120 & also incorporated into this PR  - this means we don't have to worry about unexpected behaviour changes :-)

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
>  it feels like they meant to implement 'is_billing' like 'is_primary'

Yea I see that @eileenmcnaughton. You've convinced me that this would be ok to bake into the API itself. Do you wanna do that before or after merging this?

**Comment by eileenmcnaughton** [comment]
@colemanw let's go with after cos this adds the tests

**Comment by eileenmcnaughton** [comment]
@colemanw also cos https://github.com/civicrm/civicrm-core/pull/29122 builds on this & actually that flushed out a couple of things this didn't

**Comment by eileenmcnaughton** [comment]
Merging per above

**Pull request merged**
