### PR TITLE
WIP: dev/core#1650 Fix for "Financial Type" listed twice in contrib export

### PR DESCRIPTION
**Pull request by twomice**
Overview
----------------------------------------
When exporting contributions, one may export both the Financial Type ID (an integer) and the Financial Type label (a string). Confusingly however, these two fields are both named "Financial Type" in the "Select Fields to Export" form:
financial_type

If you select them both, your export will include both Financial Type ID (an integer) and the Financial Type label (a string). But if you only select one, you can't be sure which you'll get.

Before
----------------------------------------
See overview above.

After
----------------------------------------
The fields are labelled distinctly:
fixed

Technical Details
----------------------------------------
This PR takes a blunt approach by changing the field label to "Financial Type ID" in the xml schema; it's unknown how this will affect the field label in its many appearances throughout the UI. Suggestions are welcome for a more elegant approach.

Comments
----------------------------------------
Currently I'm just watching to see how the tests do.

### CODE REVIEW

**Comment by twomice** [comment]
Jenkins test this please.

**Comment by colemanw** [comment]
This touches on a larger problem in our schema. The "correct" label of a field is context-dependent. In the export context, I agree this makes sense. However, on an entity form, the status-quo is better.
IIRC we solve this in other places by tweaking the labels in the export code and leave the "ID" off the label in the schema.

**Comment by kartik1000** [comment]
@colemanw, Can you give more insight on how to do this since the list where "Financial Type" is displayed is connected directly to DAO and updating DAO is not the right solution.

**Comment by colemanw** [comment]
I think it's fine to just change the title in `\CRM_Contribute_BAO_Contribution::exportableFields()`; that's how we do it elsewhere. Here's an example of altering the title of another field:
https://github.com/civicrm/civicrm-core/blob/11da2c0866b8bbc17116205a6424afa7db702a5d/CRM/Contact/BAO/Contact.php#L1608

**Comment by kartik1000** [comment]
@colemanw Thanks, I have made the changes as you suggested and have pushed it to the PR opened by me. Please check https://github.com/civicrm/civicrm-core/pull/17147

**Comment by jaapjansma** [comment]
Betty and I are reviewing PRs and we came across this one. It looks like the work is continued in #17147. So we would propose to close this PR.

**Pull request closed without merging**
