### PR TITLE
Hook to alter menubar css variables & fix breakpoint in WP

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Makes the menubar more flexible and configurable; fixes a couple issues with breakpoints.

Before
----------------------------------------
- Menubar breakpoint hardcoded at `768px` which works for Drupal & Joomla but causes weird problems on WP with screen widths between 768 - 783px.

After
----------------------------------------
- Generic hook added to allow altering of dynamic asset params
- Several menubar variables exposed to the hook
- Implemented hook internally to modify breakpoint to match WP admin theme

### CODE REVIEW

**Comment by colemanw** [comment]
@kcristiano would you be able to verify this works for you in WP?

With the civicrm menubar displaying underneath the WP admin bar...
**Before:** Shrinking your screen width to just under 783 will collapse the WP admin menu but *not* the Civi menu, which looks weird.
**After:** Civi menubar collapses below 783 to stay in sync with WP.

Tip: In Chrome if you hit F12 to open the console and then position the console on the side instead of along the bottom of the window, you can adjust your screen width by dragging the console divider line and it will conveniently show you the screen dimensions as you're doing it.

**Comment by kcristiano** [comment]
@colemanw With patch applied:

783px:

image

< 783px:

image


But less than 783 px on add contact screen:  no menu

image


New Mailing:  No menu

image

**Comment by colemanw** [comment]
Thanks for testing @kcristiano - I can't reproduce that issue on my local WP demo site on those screens. The fact that it works for you on some screens but not others suggests there might be a caching issue?

**Comment by kcristiano** [comment]
@colemanw It may have been caching.  I think it's better in than out and would like to see it in for 5.14 RC, so I agree it should be merged.

**Comment by seamuslee001** [comment]
@colemanw can you rebase against 5.14 in that case then

**Comment by seamuslee001** [comment]
Added merge on pass based on Kevin's comments

**Comment by seamuslee001** [comment]
Merging

**Pull request merged**
