### PR TITLE
Add support for Pricesetentity api3

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
Added support PriceSetEntity(civicrm_price_set_entity) for API3

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
We should probably add the apiv4 entity instead - I don't think we are adding to apiv`3 now

**Comment by pradpnayak** [comment]
I have already sent a pr to support API4, shall I close this if api3 support not needed?

**Comment by eileenmcnaughton** [comment]
@pradpnayak yeah probably - unless you really want ot push for us to add apiv3 - but it seems like we haven't needed it until now so v4 is probably enough

**Comment by colemanw** [comment]
I agree. APIv3 doesn't need any new features.

**Pull request closed without merging**
