### PR TITLE
SHOR-16: Fixed campaign

### PR DESCRIPTION
**Pull request by mukeshcompucorp**
Overview
----------------------------------------
This PR does the following changes in campaign,
https://s.nimbusweb.me/share/1658636/rp6ka8qg1dq3cys790q4

Before
----------------------------------------
find memberships training 3

After
----------------------------------------
find memberships training 4

### CODE REVIEW

**Comment by seamuslee001** [comment]
ping @colemanw

**Comment by eileenmcnaughton** [comment]
@mattwire wanna check this?

**Comment by eileenmcnaughton** [comment]
@mukeshcompucorp I think we need more info on what has been 'fixed' here - ie the screen & why it is better since there is no actual standard we are working towards on core markup. Note  it might make sense to close this & push back to gitlab until we clarify whether the concept should be approved

**Comment by eileenmcnaughton** [comment]
@mukeshcompucorp @guanhuan I'm closing this because it was stale - but also note the reason it stalled was because @mattwire didn't know where to look for it

**Comment by guanhuan** [comment]
Thanks @eileenmcnaughton for flagging this up. I will discuss with the team and see if we need to follow this up.

**Pull request closed without merging**
