### PR TITLE
CRM-16761 -Update and add modules to support self svc Event cancel an…

### PR DESCRIPTION
**Pull request by zorgalina**
…d transfer from email link.  (finally -due to creating branch from remote upstream/master)

### CODE REVIEW

**Comment by kurund** [comment]
@zorgalina this PR indicates that you have modified 102 files. Can you please confirm the changes.

**Comment by zorgalina** [comment]
No, I cannot confirm 102 files - in the previous email I sent, I listed the
files I committed, and pushed; I obvs. screwed something up, b/c I did NOT
modify 102 files.  I staged, and committed, and then pushed the files I
listed in my previous email.  If it says 102 files, I will delete/get rid
of this PR!  I only staged, and committed, the files I listed in my
previous message.  I certainly didn't modify 102 files, I apologize for the
mess this has created.

On Sat, Sep 5, 2015 at 6:02 PM, Kurund Jalmi <notifications@github.com>
wrote:

> @zorgalina <https://github.com/zorgalina> this PR indicates that you have
> modified 102 files. Can you please confirm the changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6676#issuecomment-138015955>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
I think I know what happened (yesterday) I tried using directions for git
rebase from an email from Eileen; and after I did that, it appeared that I
had staged like a hundred files. I git rm'ed them all and git checkout --
files.  I only had meant to update 1 file, which was
CRM/Upgrade/Incremental/sql/4.7.alpha1.mysql.tpl
When I pushed that (to CRM-16761-3) I must have pushed 101 other files as
well.

On Sat, Sep 5, 2015 at 8:26 PM, Lesley Evensen <zorgalina@gmail.com> wrote:

> No, I cannot confirm 102 files - in the previous email I sent, I listed
> the files I committed, and pushed; I obvs. screwed something up, b/c I did
> NOT modify 102 files.  I staged, and committed, and then pushed the files I
> listed in my previous email.  If it says 102 files, I will delete/get rid
> of this PR!  I only staged, and committed, the files I listed in my
> previous message.  I certainly didn't modify 102 files, I apologize for the
> mess this has created.
>
> On Sat, Sep 5, 2015 at 6:02 PM, Kurund Jalmi <notifications@github.com>
> wrote:
>
>> @zorgalina <https://github.com/zorgalina> this PR indicates that you
>> have modified 102 files. Can you please confirm the changes.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/civicrm/civicrm-core/pull/6676#issuecomment-138015955>
>> .
>>
>
>
>
> --
> زورگلنه ءء لسلی
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
Okay here is what I DID want to be part of that PR, these 12 files I meant
to commit:
https://github.com/zorgalina/civicrm-core/commit/397934db2ade80fb52fac10a9eb3f5c5d0d9c479
 from Sept. 3.

The second commit  from Sept. 4 (
https://github.com/zorgalina/civicrm-core/commit/579ff507347cd7218e9573746801a37440970d75)
is basically a nightmare and I did NOT mean to commit that.



On Sat, Sep 5, 2015 at 8:31 PM, Lesley Evensen <zorgalina@gmail.com> wrote:

> I think I know what happened (yesterday) I tried using directions for git
> rebase from an email from Eileen; and after I did that, it appeared that I
> had staged like a hundred files. I git rm'ed them all and git checkout --
> files.  I only had meant to update 1 file, which was
> CRM/Upgrade/Incremental/sql/4.7.alpha1.mysql.tpl
> When I pushed that (to CRM-16761-3) I must have pushed 101 other files as
> well.
>
> On Sat, Sep 5, 2015 at 8:26 PM, Lesley Evensen <zorgalina@gmail.com>
> wrote:
>
>> No, I cannot confirm 102 files - in the previous email I sent, I listed
>> the files I committed, and pushed; I obvs. screwed something up, b/c I did
>> NOT modify 102 files.  I staged, and committed, and then pushed the files I
>> listed in my previous email.  If it says 102 files, I will delete/get rid
>> of this PR!  I only staged, and committed, the files I listed in my
>> previous message.  I certainly didn't modify 102 files, I apologize for the
>> mess this has created.
>>
>> On Sat, Sep 5, 2015 at 6:02 PM, Kurund Jalmi <notifications@github.com>
>> wrote:
>>
>>> @zorgalina <https://github.com/zorgalina> this PR indicates that you
>>> have modified 102 files. Can you please confirm the changes.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/civicrm/civicrm-core/pull/6676#issuecomment-138015955>
>>> .
>>>
>>
>>
>>
>> --
>> زورگلنه ءء لسلی
>>
>
>
>
> --
> زورگلنه ءء لسلی
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
Can I delete the PR, will that clear up the build?
I see here https://github.com/civicrm/civicrm-core/pull/6676/files  that
102 files are listed and I didn't change them or intend to commit them at
all.

On Sat, Sep 5, 2015 at 8:36 PM, Lesley Evensen <zorgalina@gmail.com> wrote:

> Okay here is what I DID want to be part of that PR, these 12 files I meant
> to commit:
>
> https://github.com/zorgalina/civicrm-core/commit/397934db2ade80fb52fac10a9eb3f5c5d0d9c479
>  from Sept. 3.
>
> The second commit  from Sept. 4 (
> https://github.com/zorgalina/civicrm-core/commit/579ff507347cd7218e9573746801a37440970d75)
> is basically a nightmare and I did NOT mean to commit that.
>
>
>
> On Sat, Sep 5, 2015 at 8:31 PM, Lesley Evensen <zorgalina@gmail.com>
> wrote:
>
>> I think I know what happened (yesterday) I tried using directions for git
>> rebase from an email from Eileen; and after I did that, it appeared that I
>> had staged like a hundred files. I git rm'ed them all and git checkout --
>> files.  I only had meant to update 1 file, which was
>> CRM/Upgrade/Incremental/sql/4.7.alpha1.mysql.tpl
>> When I pushed that (to CRM-16761-3) I must have pushed 101 other files as
>> well.
>>
>> On Sat, Sep 5, 2015 at 8:26 PM, Lesley Evensen <zorgalina@gmail.com>
>> wrote:
>>
>>> No, I cannot confirm 102 files - in the previous email I sent, I listed
>>> the files I committed, and pushed; I obvs. screwed something up, b/c I did
>>> NOT modify 102 files.  I staged, and committed, and then pushed the files I
>>> listed in my previous email.  If it says 102 files, I will delete/get rid
>>> of this PR!  I only staged, and committed, the files I listed in my
>>> previous message.  I certainly didn't modify 102 files, I apologize for the
>>> mess this has created.
>>>
>>> On Sat, Sep 5, 2015 at 6:02 PM, Kurund Jalmi <notifications@github.com>
>>> wrote:
>>>
>>>> @zorgalina <https://github.com/zorgalina> this PR indicates that you
>>>> have modified 102 files. Can you please confirm the changes.
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/civicrm/civicrm-core/pull/6676#issuecomment-138015955>
>>>> .
>>>>
>>>
>>>
>>>
>>> --
>>> زورگلنه ءء لسلی
>>>
>>
>>
>>
>> --
>> زورگلنه ءء لسلی
>>
>
>
>
> --
> زورگلنه ءء لسلی
>



-- 
زورگلنه ءء لسلی

**Comment by zorgalina** [comment]
Closed PR due to 102 files changed

**Comment by zorgalina** [comment]
Since I deleted that PR, does that solve the problem? I entered a new PR
#6691 which has just the 11 files I meant to commit - I submitted the
database update (4.7.alpha1.mysql.tpl)  separately in PR # 6690.

On Sat, Sep 5, 2015 at 8:54 PM, Lesley Evensen <zorgalina@gmail.com> wrote:

> Can I delete the PR, will that clear up the build?
> I see here https://github.com/civicrm/civicrm-core/pull/6676/files  that
> 102 files are listed and I didn't change them or intend to commit them at
> all.
>
> On Sat, Sep 5, 2015 at 8:36 PM, Lesley Evensen <zorgalina@gmail.com>
> wrote:
>
>> Okay here is what I DID want to be part of that PR, these 12 files I
>> meant to commit:
>>
>> https://github.com/zorgalina/civicrm-core/commit/397934db2ade80fb52fac10a9eb3f5c5d0d9c479
>>  from Sept. 3.
>>
>> The second commit  from Sept. 4 (
>> https://github.com/zorgalina/civicrm-core/commit/579ff507347cd7218e9573746801a37440970d75)
>> is basically a nightmare and I did NOT mean to commit that.
>>
>>
>>
>> On Sat, Sep 5, 2015 at 8:31 PM, Lesley Evensen <zorgalina@gmail.com>
>> wrote:
>>
>>> I think I know what happened (yesterday) I tried using directions for
>>> git rebase from an email from Eileen; and after I did that, it appeared
>>> that I had staged like a hundred files. I git rm'ed them all and git
>>> checkout -- files.  I only had meant to update 1 file, which was
>>> CRM/Upgrade/Incremental/sql/4.7.alpha1.mysql.tpl
>>> When I pushed that (to CRM-16761-3) I must have pushed 101 other files
>>> as well.
>>>
>>> On Sat, Sep 5, 2015 at 8:26 PM, Lesley Evensen <zorgalina@gmail.com>
>>> wrote:
>>>
>>>> No, I cannot confirm 102 files - in the previous email I sent, I listed
>>>> the files I committed, and pushed; I obvs. screwed something up, b/c I did
>>>> NOT modify 102 files.  I staged, and committed, and then pushed the files I
>>>> listed in my previous email.  If it says 102 files, I will delete/get rid
>>>> of this PR!  I only staged, and committed, the files I listed in my
>>>> previous message.  I certainly didn't modify 102 files, I apologize for the
>>>> mess this has created.
>>>>
>>>> On Sat, Sep 5, 2015 at 6:02 PM, Kurund Jalmi <notifications@github.com>
>>>> wrote:
>>>>
>>>>> @zorgalina <https://github.com/zorgalina> this PR indicates that you
>>>>> have modified 102 files. Can you please confirm the changes.
>>>>>
>>>>> —
>>>>> Reply to this email directly or view it on GitHub
>>>>> <https://github.com/civicrm/civicrm-core/pull/6676#issuecomment-138015955>
>>>>> .
>>>>>
>>>>
>>>>
>>>>
>>>> --
>>>> زورگلنه ءء لسلی
>>>>
>>>
>>>
>>>
>>> --
>>> زورگلنه ءء لسلی
>>>
>>
>>
>>
>> --
>> زورگلنه ءء لسلی
>>
>
>
>
> --
> زورگلنه ءء لسلی
>



-- 
زورگلنه ءء لسلی

**Comment by davecivicrm** [comment]
@zorgalina the new PR looks like it has the correct commits in it. we'll review shortly. thanks!

**Pull request closed without merging**
