### PR TITLE
Add unit test for emailing receipts from additional payment page

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Adds a unit test for receipts from additional payment page

Before
----------------------------------------
No test

After
----------------------------------------
test

Technical Details
----------------------------------------
While this PR is primarily about expanding testing it also rationalises some parameters to make them pass.

Note that the goal is to move this function off this class to somewhere api accessible so breaking the connections
with the form makes sense & in fact some like the fromEmails handling are really just badly copied & pasted from elsewhere
(ie. the fromEmailIds doesn't exist & is created on the fly to house the email being passed in

Comments
----------------------------------------
@seamuslee001 here - I didn't think the other test was what was needed so I added this.

Goal is to get rid of $this from the function & call if from the api..

@JoeMurray @jitendrapurohit @monishdeb 

Note there in terms of how creating the ability to send receipts from the payment api & migrating forms to use it develops there is a question.

Say we call Payment.create and we want to send a receipt (from Additional Payment form, Contribution Form, Event Form, Webform, custom code etc) it seems to me that we might wish to send

1) a payment receipt only
2) a payment receipt AND the standard contribution receipt if this completes payment for the contribution
3) the standard contribution receipt if this completes payment for the contribution (only)
4) the payment receipt if not completing the contribution and the contribution receipt if we ARE completing the contribution
5) 'other' - ie. we don't have a  pattern for this per se but we might choose to expand to other receipts later

Should the syntax on payment create be

```
$params['is_email_receipt']  = 1;
```
and if so what does that mean

or 
```
$params['is_payment_receipt'] = 1;
$params['is_contribution_receipt_if_completed'] = 1;
``

or 
```
$params['receipts'] => [
[ 'id' => 'contribution_online_receipt', 'when' => 'if_completed],
[ 'id' => 'payment_or_refund_notification', 'when' => alwaysd],
];
```

I worry this last one, while most nuanced, could be confusing and imply we support things we don't

### CODE REVIEW

**Comment by monishdeb** [comment]
Agree with the patch and works fine for me. Added UT captures the scenario correctly. Marking with Merge on pass

**Comment by monishdeb** [comment]
@eileenmcnaughton on a separate note, I found that there are functions with same name defined in different places, but all does the same - send reciept on backoffice event registration/contribution/membership/batch etc. 
```
Monishs-MacBook-Pro:civicrm monish$ grep -irn " emailReceipt(" CRM/
CRM//Member/Form/Membership.php:991:  public static function emailReceipt(&$form, &$formValues, &$membership, $customValues = NULL) {
CRM//Contribute/Form/AdditionalPayment.php:509:  public function emailReceipt(&$params) {
CRM//Contribute/Form/AdditionalInfo.php:327:  public static function emailReceipt(&$form, &$params, $ccContribution = FALSE) {
CRM//Event/Form/ParticipantFeeSelection.php:280:  public function emailReceipt(&$params) {
CRM//Event/Cart/Form/Checkout/Payment.php:336:  public function emailReceipt($events_in_cart, $params) {
```
May be we should keep one common function say ```emailReceipt($params, $usedFor = 'contribution')``` which will send recipet in different context by processing the params (and of couse the parameters should be formatted at formlevel before calling this fn). What you say?

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
@monishdeb Yes I agree that ideally we would have one function that can send receipts without using the form. 

I kinda had 2 in mind from a signature POV

```
MessageTemplate.send ['id' => ...., 'contact_id' => ''..., 'contribution_id' => ....]

```

And I guess We aleady have Contribution.sendconfirmation - it may make sense to Payment.sendconfirmation Even.sendconfirmation - possibly only as a transitional thing as it will take time to build up the code to support the generic MessageTemplate.send


What do you think of the question as to WHICH mais to send when we add a payment though?

i forsee us using this mehod whereever we now use completetransaction eventually so the code adds the payment & the contribution is completed if by accepting that payment it is complete - however it does mean we need some way to distinguish if we want to send the payment confirmation and / or the contribution confirmation

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
Merging

**Pull request merged**
