### PR TITLE
Fix broken civgrant shortcut link

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fix broken civgrant shortcut link

Before
----------------------------------------
Broken link in 

image

After
----------------------------------------
it works

Technical Details
----------------------------------------
This started out as an enotice fix but wound up as a functionality fix - a good reason for devs to use debug mode + smarty-secure mode

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
So are the `path` and `query ` being ignored for some reason? They seem redundant with `url`.

**Comment by colemanw** [comment]
Ok I figured that out - the format expected from hook additions is different than the ones provided by core. Makes migration such a joy...

I've cleaned that up and pushed another fix for the missing contact summary action.

**Comment by eileenmcnaughton** [comment]
I just tested with your changes & it still worked

**Comment by eileenmcnaughton** [comment]
test this please

**Pull request merged**
