### PR TITLE
dev/core#339 Install CiviCRM tables using utf8mb4

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This changes the standard civicrm mysql tables to be in utf8mb4 and associated charset

Before
----------------------------------------
Tables installed using utf8

After
----------------------------------------
Tables installed using utf8mb4

ping @eileenmcnaughton @totten @demeritcowboy

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Cool. FYI these 4 tests should fail: https://github.com/civicrm/civicrm-core/pull/18828#issuecomment-713758946

The last one I think I was mistaken and it's also just a test update needed.

**Comment by eileenmcnaughton** [comment]
Ok - so to articulate this makes it so that new installs install in utf8mb4 & the arguments are

1) converting is already supported so the fact more sites will be on utf8mb4 is not a material change
2) there is some risk that some extensions will install in utf8 AND the relevant fields will be used in a join - in which case they are incompatible but the majorty of extensions are probably fine
3) new installs *should* get the benefit of the new approach & not have to later update
4) this is in effect upping the presure on our existing path
5) we no longer support a level of mysql that does not support uft8mb4 - it's likely some sites still use one but unlikely for new installs

**Comment by seamuslee001** [comment]
@eileenmcnaughton fixed the tests

**Comment by demeritcowboy** [comment]
If you install sample data the custom field tables are still utf8 - from civicrm_generated.mysql. Otherwise looks good to me.

**Comment by seamuslee001** [comment]
Thanks @demeritcowboy updated that now @eileenmcnaughton you good to MOP this?

**Comment by seamuslee001** [comment]
Jenkins  retest this please

**Comment by demeritcowboy** [comment]
@seamuslee001 that was the 4th test that failed for me earlier. Me thinks it's a real fail and it doesn't like COMPRESSED. I was surprised it didn't fail the first time here.

**Comment by seamuslee001** [comment]
@demeritcowboy I think I have found it, I had updated install query to specify the ROW_FORMAT was to be DYNAMIC, the problem being is that that was being carried through to the log table even tho the test was specifying COMPRESSED which would have been ok other than the fact that the test was putting in a `KEY_BLOCK_SIZE` setting for the table which is incompatible with DYNAMIC row format as per https://dev.mysql.com/doc/refman/5.6/en/innodb-compression-syntax-warnings.html

**Comment by eileenmcnaughton** [comment]
This was notified in the dev-digest. Tests now passing & we have discussed this - merging

**Pull request merged**
