### PR TITLE
"Fail hard" is too hard

### PR DESCRIPTION
**Pull request by yurg**
Had to make changes in order to restore project from  Fatal Error; Please, please,  some more mercy next time via  crm.alert / 
CRM_Core_Session::setStatus instead of firing exceptions.

### CODE REVIEW

**Comment by colemanw** [comment]
The BAO is responsible for business logic (that's what the "B" stands for) and not presentation. So throwing an exception is more appropriate for the BAO than reaching into the user's session to set a status message (which would not be an appropriate action to take e.g. if the BAO was being called from the api). Generally what we want to do is *catch* the exception in the form layer and present a nice error message to the user.

**Comment by xurizaemon** [comment]
CRM-18504

Also code style on comments here.

**Comment by xurizaemon** [comment]
https://issues.civicrm.org/jira/browse/CRM-18504

**Comment by xurizaemon** [comment]
This patch is not OK - it appears to restore a SQL injection vulnerability addressed in 4.7.7. Please follow the issue linked above which I will be working on today.

**Pull request closed without merging**
