### PR TITLE
dev/core#3514 Add interface to allow extensions that deal with imports to cope with 5.51

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
I have to update `csvImporter` for 5.51 & there is also AdvImport & they need to be able to use the userJob table - this allows them to define interfaces

(Depends: #23888)

Before
----------------------------------------
Core UserJob table has a hard-coded list of job-types

After
----------------------------------------
Extensions can declare UserJob interfaces

Technical Details
----------------------------------------
The required functions are
```  public static function getUserJobInfo(): array;```
```  public static function runJob(\CRM_Queue_TaskContext $taskContext, int $userJobID, int $limit, int $offset): bool;```

Comments
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/3514

### CODE REVIEW

**Comment by totten** [comment]
I haven't tested the csvimporter, but I did include this patch while doing some r-run aimed at #23888 ("Import Contacts", "Import Activities", "Import Custom Data"). They all appeared to work as before. :+1: 

I suspect there is some test-coverage (eg the unit-tests for importer probably have an implicit reliance on this).

If it's working for @eileenmcnaughton on `csvimporter`, then +1 for merge. We just need to get the dependency #23888 first.

**Comment by eileenmcnaughton** [comment]
@totten - I'm not expecting it to work with `csvimporter` - I'm expecting it to be possible to do a big fix-up on `csvimporter` so it does work - but at least with this merged I can do that

**Comment by totten** [comment]
Ah. In that case, I've done trial run with a dummy extension: https://gist.github.com/totten/377b3d84a8f948c554dba18a4b2ad850

With the dummy extension, I was able to alternately inspect the UserJob list and toggle the `foojob` extension.

```
## Inspecting
cv api4 UserJob.getFields '{"loadOptions":true}' +w name=job_type
cv ev 'return CRM_Core_BAO_UserJob::getTypes();'

## Toggling
cv en foojob
cv dis foojob
```

That seemed to work. (Which is expected -- given that there's test-coverage for scanning interfaces generally, and given that these specific interfaces are working in core.)

**Comment by eileenmcnaughton** [comment]
OK - the other finished tests so I merged it - which I think was all this was waiting on to get MOP based on the above

**Pull request merged**
