### PR TITLE
Fix for 4.6

### PR DESCRIPTION
**Pull request by nganivet**
(still a few other places but non-important / too complex to refactor).

### CODE REVIEW

**Comment by seamuslee001** [comment]
@kcristiano  Kevin can you take a look at this please?

**Comment by seamuslee001** [comment]
@nganivet Can you please fix the style errors as found here https://test.civicrm.org/job/CiviCRM-Core-PR/11798/checkstyleResult/new/

**Comment by kcristiano** [comment]
@seamuslee001 @nganivet I have tested this patch on an existing 4.6.21 site (applied cleanly) and a new install.

Patch works as expected.   I see no issue in merging to 4.6 branch

**Comment by colemanw** [comment]
Looks like there's still one style warning:

>     Defaults.php:151
>     There should be no white space after an opening "("

**Comment by colemanw** [comment]
@nganivet if there is an associated Jira issue would you please close it?

**Pull request merged**
