### PR TITLE
Tidy up on_hold handling in holdEmail function.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Follow up on https://github.com/civicrm/civicrm-core/pull/11807 with code tidy ups

Technical Details
----------------------------------------
Per discussion on #11807 with @seamuslee001 the code doesn't make sense - the field is required with a default of 0 so handling for 'null' is illogical & confusing. Test in that PR still passes

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by lyyana** [comment]
it works fine. Thanks a lot.

**Comment by eileenmcnaughton** [comment]
Merging as a reviewer's commit based on re-testing by original submitter

**Pull request merged**
