### PR TITLE
Add testing to Authorize.net and remove the lines that are repeated

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Removes transaction instantiation and later-duplicated lines of code from Authorize.net

Before
----------------------------------------
This adds tests to confirm that the status and modified date are updated & then removes the handling from A.net.

With these lines gone it's apparent that the transaction is not required here

After
----------------------------------------
transaction and duplicated lines removed

Technical Details
----------------------------------------
In Authorize.netIPN updates are made to the contributionRecur that are later made in ContributionRecur::updateOnNewPayment

This adds test cover to ensure no change and then removes them.

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
Looks fine to me

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton style warnings

**Comment by seamuslee001** [comment]
Test fail unrelated

**Pull request merged**
