### PR TITLE
CRM-17488 Fix bounce status on mailing detail report

### PR DESCRIPTION
**Pull request by JKingsnorth**
- [CRM-17488: Mailing detail report does not report bounces correctly](https://issues.civicrm.org/jira/browse/CRM-17488)

### CODE REVIEW

**Comment by rocxa** [comment]
Do not merge.. capitalization of 'bounced' and 'successful' for the param/filter values needs reverting to lower-case.

**Comment by JKingsnorth** [comment]
What issue is it causing having the caps?

**Comment by JKingsnorth** [comment]
rocxa's perfectly right - shouldn't have capitalised the values. This broke the link on the mailing summary report, and it doesn't really make sense to have the value's capped. Fixed with latest commit.

**Comment by davecivicrm** [comment]
@seamuslee001 Can you take a look / test this out on your site?

**Comment by seamuslee001** [comment]
@davecivicrm sure mate, it may be a couple of days, I'm attending a national meeting for my organisation in another state but will try my best to test

**Comment by seamuslee001** [comment]
@davecivicrm just gave it a spin on a local dev machine looks good

Seamus

**Comment by davecivicrm** [comment]
@seamuslee001 Thanks much (and such a quick turn aound)!

**Comment by JKingsnorth** [comment]
Thanks for the review @seamuslee001 and the merge @davecivicrm

**Pull request merged**
