### PR TITLE
Upgrade - Bump minimum upgradable version to 4.6.12

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Removes old upgrade code, requires at least version `4.6.12` to upgrade to the latest version of CiviCRM in a single step (upgrading from older versions is still possible by breaking it into smaller steps, e.g. 4.4 -> 4.6, then 4.6 -> latest.

Before
----------------------------------------
Minimum upgradable version = 4.5

After
----------------------------------------
Minimum upgradable version = 4.6

Comments
----------------------------------------
I know it's been less than a year since the [last bump](https://github.com/civicrm/civicrm-core/pull/21408), but 4.5 was not an LTS release so hasn't been supported for a very long time.

### CODE REVIEW

**Comment by totten** [comment]
I think the test failure indicates that we should bump up https://github.com/civicrm/civicrm-buildkit/blob/f4901d24508cf335584f5aaa711584a632262497/bin/civi-test-run#L348

Relatedly, we really should add some more snapshots to https://github.com/civicrm/civicrm-upgrade-test/tree/master/databases... maybe snapshots for a few 5.x ESRs...

**Comment by totten** [comment]
https://github.com/civicrm/civicrm-buildkit/pull/659 should make test system ignore the older snapshots (and start testing some newer snapshots).

**Comment by totten** [comment]
jenkins, test this please

**Comment by colemanw** [comment]
Thanks @totten this is passing now.

**Comment by totten** [comment]
Cool. Merging.

**Pull request merged**
