### PR TITLE
dev/core/issues/842, Fixed code to update website rather delete

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/issues/842

Before
----------------------------------------
Website gets deleted when updated

After
----------------------------------------
Website is updated

### CODE REVIEW

**Comment by seamuslee001** [comment]
@pradpnayak are you able to add a unit test to this and do you have any idea of when it broke?

**Comment by pradpnayak** [comment]
@seamuslee001 this was reported in https://civicrm.stackexchange.com/questions/29114/inline-editing-of-website-field-deletes-it which can be replicated on >= 5.10

Not sure but it may be related to these commits https://github.com/civicrm/civicrm-core/pull/13169 and https://github.com/civicrm/civicrm-core/pull/13170

**Comment by eileenmcnaughton** [comment]
@pradpnayak this has been a really fragile bit of functionality :-( Would be v grateful if you can add a test so we can hopefully break the cycle

**Comment by eileenmcnaughton** [comment]
@elisseck are you able to review?

**Comment by pradpnayak** [comment]
Hi @eileenmcnaughton 

This issue is more of UI so do you want me to add unit test for UI submit or just for the CRM_Core_BAO_Website::process() function?

Thanks
Pradeep

**Comment by eileenmcnaughton** [comment]
@pradpnayak I had assumed the latter - does that work out or is it kinda pointless?

**Comment by elisseck** [comment]
@eileenmcnaughton Yes i'll be happy to review this since my recent PRs touched this functionality (although i'm not 100% sure how they would have caused this :) ). Should be able to get to it tonight.

**Comment by elisseck** [comment]
Okay I tested this on a buildkit build of current 5.13.alpha1 and i'm seeing some really strange behavior that I don't understand. The behavior described in the issue is not consistent at all for me. Here is a little screencast you'll see a failure when I add the 4th website but you'll see a bunch of successes as well. This is mostly FYI for writing this test I think it's going to be confusing:

dev_core_842

However weird this is... checking out the PR _does_ seem to resolve this issue after editing websites for a few minutes I saw no more issues... so my review is as follows:

* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __PASS__
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __PASS__
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __PASS__
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __PASS__
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __PASS__
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __PASS__
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __PASS__
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __Undecided__: It would be great to see the test as discussed above although I can't say much there because i'm definitely guilty of not writing tests for my previous PRs (sorry!!).

**Comment by eileenmcnaughton** [comment]
@elisseck caught out huh :-) But thanks for doing the review

**Comment by mieg** [comment]
This fixes the issue for me, on 5.11.0 / Drupal 7.65. Thanks @pradpnayak!

**Comment by colemanw** [comment]
I think this needs to be merged into 5.12.

**Comment by eileenmcnaughton** [comment]
I've put this against 5.12 https://github.com/civicrm/civicrm-core/pull/13939

**Comment by eileenmcnaughton** [comment]
Closing as merged through via 5.12 - would be happy to see that test though :-)

**Pull request closed without merging**
