### PR TITLE
Revert "Swap out button/submit inputs for button elements"

### PR DESCRIPTION
**Pull request by colemanw**
Reverts civicrm/civicrm-core#18091

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This came up in conversation on Friday. I was initially keen for the buttons change to be merged to 5.29 - but at that point I was expecting us to move fairly quickly & robustly on it - in other words that we would be giving around 4 weeks notice of the change to extension writers. We let that slip & with only 2 weeks left it doesn't really make sense to keep this in 5.29

I note that both Coleman & I observed the buttons in shoreditch are now often invisible & I think it's this patch.

I re-opened @agh1's PR against master so if we can get that rebased then we can merge again once a bit more testing has been done & avoid the 2-week notice issue.

**Comment by demeritcowboy** [comment]
So one problem now that's back in 5.29 is the button icons don't click (https://github.com/civicrm/civicrm-core/pull/18005#issuecomment-669936497), which was what #18087 was originally about. It's liveable though.

**Comment by eileenmcnaughton** [comment]
@colemanw arg ^^

**Comment by mattwire** [comment]
Yes there's a few other UI changes (mostly button related) that went into 5.29 which is why we merged this one too. It really needs to be all or none and with the other changes but not this one the buttons in 5.29 are going to get a lot of complaints.

**Comment by colemanw** [comment]
@mattwire which other PRs need to be reverted?

**Comment by mattwire** [comment]
@colemanw I'm not sure offhand. There's a list somewhere on one of the tickets leading off #18087 I think. Shoreditch has been pretty broken since at least CiviCRM 5.27 (https://github.com/civicrm/org.civicrm.shoreditch/issues/465) so breaking it more doesn't seem a good reason in itself to revert.
I do understand about the communication issue but we did discuss the reasons for merging at some length via the other PRs and it was agreed that it was much less painful to make all the UI changes in a single release that not many might be upgrading to because of 5.28 being a security release. And I thought this change would break Stripe but it didn't because we're already using some fairly generic button detection (ie. type=submit class=validate) because of the range of ways buttons were presented.

**Comment by demeritcowboy** [comment]
Would a temporary workaround be something like this that loads on every page:

```
CRM.$('input[type="submit"]').each(function() {
  var t = CRM.$(this);
  t.parent().find('i').click(function() { t.click(); });
});
```

It works on all the pages I tried. It's hokey I know but posting in case it comes down to that.

**Pull request merged**
