### PR TITLE
SearchKit - Add translatable descriptions to entities

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds user-friendly descriptions to the top-level entities in SearchKit, and makes it possible to add them to other entities as well.

Before
----------------------------------------
Entities had descriptions derived from code comments, which were written for developers and English-only

After
----------------------------------------
Entities can have a user-friendly description which is translated.

image

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Why is package.lock..json in there

**Comment by colemanw** [comment]
:man_shrugging: guess it snuck in there somehow. I've removed it.

**Comment by eileenmcnaughton** [comment]
This is OK technically but I'd like @MikeyMJCO to review the descriptions from here down https://github.com/civicrm/civicrm-core/pull/20598/files#diff-070daea06764f9c4a24a6e5472572d0133ba072b7ded1df7e2975f6b49f7292eL3 given we should try to get them right before the translators engage

**Comment by eileenmcnaughton** [comment]
ug @colemanw this has gone stale. If you rebase we can merge & if @MikeyMJCO has any suggestions any time before we branch then we can alter

**Comment by colemanw** [comment]
Ok rebased.

**Comment by eileenmcnaughton** [comment]
OK - I trawled through this & couldn't see anything that didn't belong - let the great stale-making begin

**Pull request merged**
