### PR TITLE
CRM-19982: Can't enter dates in 4.7.16. Can only enter characters in …

### PR DESCRIPTION
**Pull request by yashodha**
…word birth

### CODE REVIEW

**Comment by yashodha** [comment]
seems to be a regression caused by https://github.com/civicrm/civicrm-core/commit/3cef3c00ce1e3de5ee93ee44bc1a1d1d3d406385

**Comment by yashodha** [comment]
test this please

**Review by seamuslee001 — APPROVED** [review]
Appears to save correctly on the demo site built off the PR pinging @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
Can we leave this & re-test on the other one - I think Ive got past those issues there

**Comment by eileenmcnaughton** [comment]
NB - you can push to that branch if after testing it there you still think there is an issue this would fix

**Comment by eileenmcnaughton** [comment]
OK - it is on that branch too - I'll merge this & fix that over the top

**Pull request merged**
