### PR TITLE
Add in frontend_title field for Contribution Pages to allow site mana…

### PR DESCRIPTION
**Pull request by seamuslee001**
…gers to specify a title for a page different to that for use from the backend

Overview
----------------------------------------
This adds the ability for site managers to set different titles for a contribution page for use on the public side to that on the admin side.

Before
----------------------------------------
Only one title field is avaliable for both public and admin sections

After
----------------------------------------
Optionally separate public title field for use on transaction public facing pages

ping @eileenmcnaughton @jusfreeman @MikeyMJCO @johntwyman

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by bjendres** [comment]
looks good to me, tested via front end, back end, api3 and incremental upgrade

**Comment by totten** [comment]
Additional note from discussing with Seamus - he reports that the new field is allowed to be blank, and (if omitted) then it uses the old title logic.

**Review by johntwyman — APPROVED** [review]

**Comment by jusfreeman** [comment]
@seamuslee001 thanks for this enhancement. Can we make the text longer than 255 characters? This can be limiting for long titles which may have typical components like: Campaign Name Year - Location - Date - Page Title Call To Action

**Comment by seamuslee001** [comment]
@jusfreeman i'll open a separate PR so we can discuss if we / should or not increase the length of the column. I'll merge this now but would you be thinking of the column that is now going to be the more adminy side of things or the public side of things?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 maybe discuss  the length on gitlab not a PR now I think about it

**Comment by jusfreeman** [comment]
@seamuslee001 it was the frontend title, but don't worry about it. Looking at the schema I can see that the title field range in size from 64, 127 and 255 characters. So going with 255 is at least following the current pattern. Interesting fact, WordPress uses a TEXT field not VARCHAR for Post Title, that's 64kb. Drupal 7, on the other hand, had 255 characters.

**Comment by jusfreeman** [comment]
Standardise length of Title fields in CiviCRM database schema, use 255 characters for all
https://lab.civicrm.org/dev/core/issues/1306

**Pull request merged**
