### PR TITLE
Use TempTable methods

### PR DESCRIPTION
**Pull request by mfb**
Overview
----------------------------------------
Use the TempTable methods to create some more temporary tables.

Before
----------------------------------------
Various classes create temporary tables via raw SQL.

After
----------------------------------------
Use CRM_Utils_SQL_TempTable methods to create temporary tables.  It should no longer be necessary to cleanup temporary tables in tests as they will have unique names.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mfb can you rebase this? It's stale because the (slooowww) functions from the Activity BAO have now been entirely removed

**Comment by eileenmcnaughton** [comment]
I tested these last 2 cases - all good. Merging

**Comment by mfb** [comment]
\o/  we could also do some similar fixes for import.

**Comment by eileenmcnaughton** [comment]
@mfb yeah - although I want some tests added to import before I touch that huckery code!

**Pull request merged**
