### PR TITLE
APIv4: Automatically add 'OR IS NULL' to 'NOT CONTAINS'

### PR DESCRIPTION
**Pull request by aydun**
Overview
----------------------------------------
In APIv4 'NOT CONTAINS', automatically add a 'OR IS NULL' since we just want to know that a particular value is not present but don't care whether the field has any other value or is empty.

Before
----------------------------------------

1. On standard sample data, for one contact, set "Most Important Issue" to "Education" and on another contact set "Environment"
2. Create a SearchKit on Contacts with a `WHERE` of `Constituent Information:Most Important Issue` `Contains` `Education`
3. Confirm results include those in 1.
4. Change to `Doesn't Contain`
5. Note only the contact with "Environment" is shown - not all the other records with no value set for "Most Important Issue"

After
----------------------------------------
All contacts without 'Education' as the 'Most Important Issue' are returned.

Technical Details
----------------------------------------
Not sure whether there is a better way to implement this.

Comments
----------------------------------------
This can be worked around in SK by adding an 'OR' group with 'IS EMPTY' but this is cumbersome.

### CODE REVIEW

**Comment by colemanw** [comment]
I'm not sure we need to go with the full IS EMPTY here (which expands into a compound expression like `field = "" OR field IS NULL`) because if the field is already a string then the NOT CONTAINS ought to cover it, so we just need the IS NULL bit.

**Comment by aydun** [comment]
Ok ... updated

**Comment by colemanw** [comment]
@aydun this looks good. Probably a unit test could be added around here:
https://github.com/civicrm/civicrm-core/blob/6dd43f076916e16d88d6733737f15c65576c758a/tests/phpunit/api/v4/Action/ContactGetTest.php#L141

or here:
https://github.com/civicrm/civicrm-core/blob/6dd43f076916e16d88d6733737f15c65576c758a/tests/phpunit/api/v4/Action/ContactGetTest.php#L203

**Comment by aydun** [comment]
@colemanw Thanks - tests added

**Pull request merged**
