### PR TITLE
dev/core#2398 - Fix save'n'test button on mail account form

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/2398

1. Add a new mail account.
2. Fill it out. It doesn't have to be real info.
3. Click save and test.
4. Click save.
5. You now have two accounts.

Before
----------------------------------------
Two accounts.

After
----------------------------------------
One account. Sometimes two is better than one, but not here.

Technical Details
----------------------------------------
The button was using the "refresh" action, which even though it results in a submit it prevents completing the form cycle.

Comments
----------------------------------------
Not related to button-rama. Maybe technically a regression since the button was introduced in 5.32, but it's not a critical issue since you can just delete the duplicate account.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I tested this but failed to replicate - when I allowed it to operate in the model the box closed when I chose save and test so I couldn't hit save again

image

**Comment by demeritcowboy** [comment]
Oh maybe it only comes up if you have popups turned off. I assume that screenshot is from something else?

**Comment by eileenmcnaughton** [comment]
yeah - let's remove that

**Comment by eileenmcnaughton** [comment]
Ok - I could replicate this without popups enabled & no issues with or without with them enabled. I think this could have gone against the rc on the 'arguable regression case' - but given the obscurity of this master is fine

**Comment by demeritcowboy** [comment]
Thanks!

**Pull request merged**
