### PR TITLE
Import - make tracking fields import-specific

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Import - make tracking fields import-specific

Before
----------------------------------------

The import tracking table adds some fields to track what happens - but actually different imports have different things to report on 

After
----------------------------------------
The imports can define the fields they track - in the case of contact I've added 2 fields -  'related_contact_created' &  'related_contact_matched' - which are the count of related contacts created or matched. This comes out of discussion with @darrick https://github.com/civicrm/civicrm-core/commit/578e4db3773f70f13e0bc76c02f2768c37293528#r75332645 and is not necessarily the final conclusion of what is best to track  - but I think definite the tracking fields by import is a better structure 

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by darrick** [comment]
@eileenmcnaughton I've lost tracked of where you mentioned how errors should be handled.  It was in regards to how the related contact was throwing an unhandled error when not found by external identifier.

I mention that because as I'm testing the current base and I'm running into unhandled exceptions which are causing the import to crash. 

Like this line: https://github.com/civicrm/civicrm-core/blob/b586573164eea83a4e424f5befbce5bca0a461a1/CRM/Contact/Import/Parser/Contact.php#L1201

The import crashes here because no error code is set: https://github.com/civicrm/civicrm-core/blob/b586573164eea83a4e424f5befbce5bca0a461a1/CRM/Contact/Import/Parser/Contact.php#L242

I searched through the parser and number of exceptions are thrown with no error code being set.  I thought maybe it would be good to first sort that out.  And make sure there are tests for all that.  

Also, some of the error messages could use some cleanup: https://github.com/civicrm/civicrm-core/blob/b586573164eea83a4e424f5befbce5bca0a461a1/CRM/Contact/Import/Parser/Contact.php#L2034

I was thinking over the next week I could do a PR to make sure there are tests for each exception and that the ERROR code and description makes sense.  To me this will cut down on the noise a bit.  As with my trouble with the multiple dupes is more an issue of figuring how dedupe mechanism missed the first two but matched the third. 

And I think that will help get your work you've already done solidly in place for the release.  And then for a later release working on the triage wizard would drive what tracking fields may be required.   

On another note.  The import code is running about 10x to 20x faster.  What used to take over an hour for me is down to 5 to 10 minutes.  That's for about 7000 records.

**Comment by darrick** [comment]
This is why I'm getting multiple duplicates:
image

Using my custom rule.  One match is from col_10 and the other from col_13.  From a user perspective I tried using the "Find and Merge Duplicate Contacts" page which turned up nothing from my rule.  So, later during triage being able to click on the record to see what CRM_Dedupe_Finder::paramDupes returns would be useful.  Or have the import track the dupe ids. 

But, first I'm just tying to trigger all the exceptions get a decent status_message and status into the import table.

**Comment by darrick** [comment]
@eileenmcnaughton So something like this.  Make sure each exception is caught and logs a status and message in the import table for the Contact Parser: https://github.com/civicrm/civicrm-core/compare/master...darrick:handle_all_contact_import_exceptions 

Quick search shows 1 down and 4 to go:
```
618:          throw new CRM_Core_Exception($prefixString . ts('Mismatched or Invalid contact subtype found for this related contact.'));
630:        throw new CRM_Core_Exception($errorMessage);
643:      throw new CRM_Core_Exception($tempMsg);
1210:      throw new CRM_Core_Exception(ts('Matching this contact based on the de-dupe rule would cause an external ID conflict'));
```

**Comment by eileenmcnaughton** [comment]
@darrick was this link there - https://github.com/civicrm/civicrm-core/pull/23692/files#diff-6381f637d7d41cb4ea44e8337383a8be3fb2f0c4ce894e8513981113fc2ea672R2148 when you tested?

**Comment by eileenmcnaughton** [comment]
@darrick I've pulled your commit in (and rebased some other-wise merged stuff out)

The main point of this PR is to

1) clean up the multiple points of exception handling and
2) make it possible to define the 'tracking fields' for the import per import

The reason for the second is that what is helpful to track for contact imports differs from contribution imports (I'm stil not qutie there on contribution import but they currently report on created soft credits via status & that might be the best way or extra fields might be)

5.51 hasn't forked yet (slightly delayed in the hope of getting the import a bit better since we have a long month & will still get 4 weeks of rc) - but my goal is to get all the big code bits in the right place by the time we do so that if there are regressions it's easy to port them between 5.51 & future branches and we are not fixing the code we want to replace. I'm going to document this a bit more today

**Comment by darrick** [comment]
@eileenmcnaughton okay.  I did just add another test for another exception.  The other unhandled exceptions are in validateParams.  I wasn't quite sure what to do with that.  I put some comments in my last commit about it.  Mainly just curious if validateParams should be updating the import with status messages.  https://github.com/civicrm/civicrm-core/commit/4ccd09f12455e32cc92e130f1b9c272a4e9e73f0

**Comment by eileenmcnaughton** [comment]
@darrick I moved the call to `validateValues` out of the `import` process - the form flow is that the `MapField` page calls `validateValues` which updates the status to `ERROR` if not valid. Then the `import` doesn't attempt those - so it doesn't make sense to call `validateValues` within import as anything it can reject will already be validated - 


image

**Comment by eileenmcnaughton** [comment]
@darrick I took a look at your last commit & pulled in a couple of the changes - but the test seems like it's still experimental on your part so I left it - I agree that `testImport` should no longer catch exceptions & it should check `$dataSource->getRow()` to interogate the error message

**Comment by darrick** [comment]
@eileenmcnaughton the test wasn't experimental.  It worked.  I did change the contactType variable passed to testImport to match how testValidate is done.  I also accidentially renamed it to testImport2.

I could do a quick patch to your current commit if that helps.

**Comment by eileenmcnaughton** [comment]
@darrick ah - it was the accidental renaming that made me think it was experimental

**Comment by eileenmcnaughton** [comment]
@darrick I should also mention the QA area I still feel needs to be covered off - how well address & custom field updating work in UPDATE and FILL modes - there are about 400 lines of code that are mostly doing nothing but I'm too scared to remove them until I feel sure we have cover on 

- what happens when an address is updated and a Country or State is added and the location has an existing address 
- ditto but with a street address
- ditto but with various combos of location & primary location
- ditto but with address custom fields
- ditto but with contact custom fields

I'm pretty sure WMF has code that allows Country to be added to an existing address if it doesn't conflict with the state - but over all I haven't tested address updates or fill mode as thoroughly as I would like to at this stage.

**Comment by colemanw** [comment]
This looks mergeable based on engagement & tests

**Comment by darrick** [comment]
> @darrick I should also mention the QA area I still feel needs to be covered off - how well address & custom field updating work in UPDATE and FILL modes - there are about 400 lines of code that are mostly doing nothing but I'm too scared to remove them until I feel sure we have cover on
> 
>     * what happens when an address is updated and a Country or State is added and the location has an existing address
> 
>     * ditto but with a street address
> 
>     * ditto but with various combos of location & primary location
> 
>     * ditto but with address custom fields
> 
>     * ditto but with contact custom fields
> 
> 
> I'm pretty sure WMF has code that allows Country to be added to an existing address if it doesn't conflict with the state - but over all I haven't tested address updates or fill mode as thoroughly as I would like to at this stage.

I'm not quite exactly parsing this.  I am liking the DataProviders.  Should I create a testImportUpdateFillOrSkip function that first creates a contact record with primary and main address locations with custom fields and then for each Update, Fill, Skip mode .... and each main or primary ..

* map Country only.  
* map State only
* map address custom field
* map contact custom field

Or maybe I add also add the contact to be updated to the provider.

I also will have to wait until this is merged.

**Comment by eileenmcnaughton** [comment]
@darrick - yes this has merge-on-pass so I can get it merged soon (I've just had some issues with the latest rebase - but hopefully sorted now)

Regarding the test - yes - something like that would be brilliant and would increase my confidence that we won't (haven't?) break stuff

**Comment by eileenmcnaughton** [comment]
oh - it's easier I find in tests to use the external identifier than the contact id - because you can hard-code that

**Pull request merged**
