### PR TITLE
CRM-19393 Do not transalate when managing log tables

### PR DESCRIPTION
**Pull request by seamuslee001**
- [CRM-19393: Unable to enable logging after upgrade](https://issues.civicrm.org/jira/browse/CRM-19393)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by colemanw** [comment]
@civicrm-builder test this please

**Comment by colemanw** [comment]
@seamuslee001 there appears to be one new failure associated with this PR (the syntaxconformancetest) the other two are pre-existing problems.

**Comment by seamuslee001** [comment]
@colemanw i believe i have fixed the syntax conformance test and found it is actually broken on master (not sure how its not showing up in our test suites)

**Comment by seamuslee001** [comment]
@colemanw i ended up having to skip it reason is Product.create has a create spec that specifies a default value therefore it creates a row and doesn't complain. 

I tested this against master and got the same error locally by doing 

./tools/scripts/phpunit --tap --filter testWithoutParam_create 'api_v3_SyntaxConformanceTest'

I have asked Tim to do the same test to see if he gets a failure as well but it seems strange that it would not fail on our master test suite

**Comment by colemanw** [comment]
Thanks @seamuslee001 .
Looks like our nitpicker found an extra space in SyntaxConformanceTest.php line 1085

**Pull request merged**
