### PR TITLE
Refactor entityParams in Order.Create API so it is easier to understand/modify

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Partial from #18096 - this is a refactor only.

Before
----------------------------------------
More compact, less easy to understand/modify code.

After
----------------------------------------
Less compact, clearer code. Allows for easier changes for individual entities (eg. adding participant statuses per #18096).

Technical Details
----------------------------------------

Comments
----------------------------------------
@eileenmcnaughton Could you review/merge? I'll rebase #18096 after

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire I did the same refactor myself and came out with a slightly different outcome (mostly switching on $item['entity_table'] since we know what the entity is from the table & reducing the IFs on $entityParams). However, the only thing of significance / that couldn't equally well be done in a future round is that I think

```
break 2;
```

is wrong - as that would take us  out of both the switch AND the line item iteration loop - meaning that a contribution line item would block a later membership item being created. I guess we want to check that scenario is tested before making this change

**Comment by eileenmcnaughton** [comment]
hmm - it might be OK - actually - perhaps - just looking at the test config we have

``` 
   $orderID = $this->callAPISuccess('Order', 'create', [
      'total_amount' => 400,
      'financial_type_id' => 'Member Dues',
      'contact_id' => $this->_contactID,
      'is_test' => 0,
      'payment_instrument_id' => 'Check',
      'receive_date' => '2019-07-25 07:34:23',
      'line_items' => [
        [
          'params' => [
            'contact_id' => $this->ids['contact'][0],
            'membership_type_id' => $this->ids['membership_type'][0],
            'source' => 'Payment',
          ],
          'line_item' => [
            [
              'label' => 'General',
              'qty' => 1,
              'unit_price' => 200,
              'line_total' => 200,
              'financial_type_id' => 1,
              'entity_table' => 'civicrm_membership',
              'price_field_id' => $priceFieldID,
              'price_field_value_id' => $generalPriceFieldValueID,
            ],
          ],
        ],
        [
          'params' => [
            'contact_id' => $this->ids['contact'][1],
            'membership_type_id' => $this->ids['membership_type'][0],
            'source' => 'Payment',
          ],
          'line_item' => [
            [
              'label' => 'General',
              'qty' => 1,
              'unit_price' => 200,
              'line_total' => 200,
              'financial_type_id' => 1,
              'entity_table' => 'civicrm_membership',
              'price_field_id' => $priceFieldID,
              'price_field_value_id' => $generalPriceFieldValueID,
            ],
          ],
        ],
      ],
    ])['id'];
```

**Comment by eileenmcnaughton** [comment]
Hmmm no the second break is definitely out of 
```
 foreach ($params['line_items'] as $lineItems) {
```

- so it should be moderately easy to tweak the setup in CRMTraits_Financial_OrderTrait to have an order where the first line item is purely a contribution item

**Comment by eileenmcnaughton** [comment]
Just adding needs test because we want to ensure that case were the line items is an array with a contribution line as the first line is covered

**Comment by mattwire** [comment]
@eileenmcnaughton This now has a test which should improve the test coverage for the Order API - thanks @jitendrapurohit

**Comment by mattwire** [comment]
test this please

**Comment by jitendrapurohit** [comment]
Thank you for the update @eileenmcnaughton  👍

**Comment by mattwire** [comment]
@eileenmcnaughton I've updated the PR and tests are now passing

**Comment by eileenmcnaughton** [comment]
yep that works

**Pull request merged**
