### PR TITLE
CRM-19649 - Multiple wysiwyg config presets

### PR DESCRIPTION
**Pull request by colemanw**
* [CRM-19649: ckeditor includes html\/head\/body tags](https://issues.civicrm.org/jira/browse/CRM-19649)

### CODE REVIEW

**Comment by colemanw** [comment]
@lcdservices this is ready for testing. This feature allows you to set different CKEditor configurations based on context (I've added a couple contexts for now, we can add more later).

@JKingsnorth note that we are reverting the `fullPage` setting from #7993 because it broke existing functionality where the html `<head>` and `<body>` tags were in the message header/footer. So instead of hard-coding the `fullPage` option for CiviMail, you can configure whatever settings you want for that context via the UI.

ckeditor config

**Comment by JKingsnorth** [comment]
Thanks for the heads up on this. Seems to work well =]

**Comment by mfb** [comment]
Message templates are confusing, because in some parts of the Civi UI, they can be sent on their own, without any separate header/footer, while in other parts of the UI, they can be wrapped with a header adn footer.

That seems confusing / complicated (to me :)

It seems like we want some way to indicate whether a message template already its header and footer, or is designed to be wrapped in a header and footer.  If the former, then fullPage should be set to true.  If the latter, then fullPage should be set to false.

**Comment by mfb** [comment]
I opened https://lab.civicrm.org/dev/mail/issues/42 as a proposal for more work on this.

**Pull request merged**
