### PR TITLE
Set CMS page title from Angular

### PR DESCRIPTION
**Pull request by colemanw**

### CODE REVIEW

**Comment by colemanw** [comment]
@totten what do you think of using a directive to set the page title like this?

The intent here is that you include the extra `<h1>` tag on your angluar page to hedge your bets - under most circumstances this directive will hide that tag and use the CMS-generated one instead, but if the page appears outside the cms then it will still work.

Regarding the syntax, I opted for `<h1 crm-ui-title>{{ts('The title')}}</h1>` instead of `<h1 crm-ui-title="ts('The title')"></h1>` for no important reason other than "it looks better". The latter would have made setting a watcher a bit easier but it seems to work fine this way.

You can see it in action on the status page.

Thoughts?

**Comment by colemanw** [comment]
One potential issue with this is that `document.title` only supports plain text while `<h1>` tags support rich-text. So if the title wanted to include e.g. an icon, or if generally the page title wanted to be different from the document title, then this directive isn't quite sophisticated enough. I don't think this implementation paints us into a corner though; it could be expanded to support e.g.

    <h1 crm-ui-title crm-document-title="ts('The title')">
      <i class="crm-i fa-rocket"></i>{{ts('The title')}}
    </h1>

**Comment by colemanw** [comment]
I'm also tempted to rename this thing `crm-page-title` instead of `crm-ui-title` since it's not really a UI widget.

**Comment by totten** [comment]
That's getting pretty slick. :)

Agree that `crm-ui-title` sounds more like a widget title, so `crm-page-title` makes sense.

IIRC, the technique of using `scope.$watch(function(){})` can be sensitive to performance because the function will be run during every digest cycle. (Digest cycles can happen as frequently as each keypress.) `scope.$watch(expr)` is supposed to be safer. I don't have any hard numbers to indicate whether it's acceptable/unacceptable in this case, although I feel like DOM interaction is on the slow side.

The technique for identifying the CMS's in-page title (`$('h1').not('.crm-container h1')`) obviously feels a little fragile, but in practice we're generating the page-content anyway (which reduces the odds of stray `<h1>`s), and the old bug (always showing bad titles) seems worse than the theoretical new bug (sometimes inserting the title in the wrong place).

(If we really wanted to be strict... one might put in a dummy title by default, scan for it during `.config()` or on first usage, and save a reference to it. However, I do like this simplicity of `$('h1').not('.crm-container h1')`.)

**Comment by colemanw** [comment]
Actually it does do what you described as preferable -- while the selector is indeed `$('h1').not('.crm-container h1')` it performs an additional check to see if the contents of the tag match the expected contents (which indeed starts off with the placeholder "CiviCRM"); other `h1` tags in the dom will be unaffected.

**Comment by colemanw** [comment]
Re performance, I could not find a way to $watch an element's inner html without using a function. Do you know of a way? But sticking a console.log statement in the callback fn only resulted in a couple of calls during an actual update, and none otherwise (so it's apparently not happening at regular intervals like once per millisecond).

**Comment by totten** [comment]
Re: `$('h1').not('.crm-container h1')` -- brilliant, you're right. I'll learn how to read someday. ;)

True that `update()` doesn't run frequently. However, I did this experiment which does produce prolific output:
 1. Edit CiviMail UI (`2step.html`) to set a title (`<h1 crm-ui-title>{{ts('Edit Mailing')}}</h1>`).
 2. In the watch checker, put `console.log()` right before `return $el.html();`

Agree that there isn't a general way to watch DOM content in Angular. If this performance issue is problematic, then we'd have to use the other notation `<h1 crm-ui-title="ts('The title')"></h1>`. The key bit there is that the `$watch()` can do its thing with pure-JS (no DOM checks are runtime).

**Comment by colemanw** [comment]
@totten I've changed the name to crmPageTitle and added support for `crm-document-title`

You can see it in action on the status page, where the document title contains the count, but page title does not (since it would be redundant with the count in the tabs just below the h1.

Re performance. Bummer. Maybe try it this way for now and see how it goes?

**Comment by colemanw** [comment]
Ok I couldn't get it to work using $watch(attrs.foo) prob because the attrs don't change but their evaluated value does. But this worked, and might even be the right way to do it per https://gist.github.com/bennadel/2b4c59a58254c92b6c39#file-scope-watch-htm-L90

**Comment by totten** [comment]
Think you're right -- that's the way one is supposed to use $watch() functions.

JFYI: https://test.civicrm.org/job/CiviCRM-Core-PR/6271/checkstyleResult/new/

**Comment by colemanw** [comment]
In that case there's really no difference. I've removed the [last commit](https://github.com/colemanw/civicrm-core/commit/8774b640747bb59419d39d6ef2c4beda007dbb3b) since we have to define a function either way, I don't see how it would help performance to use an attribute rather than inner html - the contents of the function isn't going to affect how often the function gets called. Either way it has to evaluate something.

**Comment by totten** [comment]
Just for clarity... the underlying computation is different. Compare:

 * *With the attribute* (include 8774b640747):
   * Initialization (Once): Read a single DOM attribute
   * Digest (Recurring): Check a JS property. (Granted: This JS property is computed... but it's computed from other JS data, and any further optimization is the framework's job.)
 * *With the DOM node* (exclude 8774b640747):
   * Initialization (Once): Don't need to read anything
   * Digest (Recurring): Serialize a DOM subtree

However, as I said, I don't have any firm numbers that reading a DOM subtree in `$watch()` is problematic - only intuition that we're crisscrossing the wiring of the framework.

(Aside: Wonder if it would be more maintainable or less maintainable to provide icon as parameter, e.g. `<div crm-page="{icon: 'foo', title: ts('Foo Bar')}">`)

**Comment by colemanw** [comment]
I believe jQuery is pretty efficient at grabbing stuff from the dom, not too worried. I'd prefer to keep as-is unless a problem surfaces.

Speaking of icons... another advantage of keeping as-is: we get icons for free! Check out how well this works :)

    <h1 crm-page-title crm-icon="fa-flag">Hello</h1>

**Comment by seamuslee001** [comment]
Jenkins re-test this please

**Pull request merged**
