### PR TITLE
BasicPageLoadTest - Add basic E2E test which requests every nav-menu item

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

This test doesn't ensure that every page works correctly.  It merely ensures that every page sends a well-formed response.  This should flag obvious crashes.

Marked as "Draft". Just want to see what happens. It will likely fail because (a) the `tidy` PECL is needed and (b) there are a number of small/random HTML quality issues.

Depends: https://github.com/civicrm/civicrm-buildkit/pull/646

Before
----------------------------------------

Test does not exist.

After
----------------------------------------

Example output when requesting a malformed page:

Screen Shot 2021-08-24 at 6 20 13 PM

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by colemanw** [comment]
Neat.

**Comment by seamuslee001** [comment]
@totten 

```
RUN:[[./scripts/phpunit --tap --log-junit '/home/jenkins/workspace/CiviCRM-Core-PR/junit/E2E_AllTests.xml' '--exclude-group' 'ornery' 'E2E_AllTests']]
TAP version 13
PHP Fatal error:  Declaration of E2E\Core\BasicPageLoadTest::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /home/jenkins/bknix-dfl/build/core-21249-7exz7/web/sites/all/modules/civicrm/tests/phpunit/E2E/Core/BasicPageLoadTest.php on line 31
```

**Comment by totten** [comment]
> (@eileenmcnaughton) You might like to also check `CRM_Core_Page_HookTest`

Ah, cool. They seem similar in that both are fairly broad. They differ in how requests are simulated (headless vs E2E), what they make assertions about (hook-invocations vs HTML quality), and where they get the list of candidates (routing-table vs nav-menu).

Maybe there's some smarter way to approach each of those aspects? OTOH, if we think in terms of "Swiss Cheese Model", then maybe it's just as well for these two layers-of-cheese to have their gaps+fillings in different places.

> (@seamuslee001) `PHP Fatal error:  Declaration of E2E\Core\BasicPageLoadTest::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /home/jenkins/bknix-dfl/build/core-21249-7exz7/web/sites/all/modules/civicrm/tests/phpunit/E2E/Core/BasicPageLoadTest.php on line 31`

Thanks, fixed.

**Comment by demeritcowboy** [comment]
Not sure what to do with this one but it doesn't seem to be actively in progress and nothing in several months. Feel free to reopen.

**Pull request closed without merging**
