### PR TITLE
Re-enable any queues that were disabled for background processing, on end

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
… 

Overview
----------------------------------------

This addresses what is likely an artificial scenario but

essentially if these steps are followed twice in separate processes
- create a queue
- run the queue via runAll

The second time will fail because the queue was disabled & no re-enabled, despite being perisistent

Before
----------------------------------------

After
----------------------------------------
Persistent queues are more re-usable

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by totten** [comment]
Yeah, I think it's fair/symmetric to say: "We're only disabling background while the foreground thing is active." Agree it's a kind of a funny/unlikely scenario.  If you're happy with it and it passes, then go ahead and merge. 

Just to verbalize some characteristics of this approach:

* If the `runAll()` crashes, then you're stuck in disabled state until an admin intervenes.
* The `runAll()` and `runAllViaWeb()` would behave differently. This only restores background for `runAll()`.
* If you want both of them to restore background, then maybe put the new call from `runAll()` to `handleEnd()`. (*That method should be used by both.*)

**Comment by eileenmcnaughton** [comment]
@totten yeah - I wasn't sure about putting it in `handleEnd` but I am open to moving to `handleEnd` - note I managed to replicate this in a crm only test - it required some flushing that is  a bit artificial but I guess the use case is having a persistent queue that may or may not have items in it at any point in time

**Comment by eileenmcnaughton** [comment]
Actioning " If you're happy with it and it passes, then go ahead and merge."

**Comment by totten** [comment]
> I guess the use case is having a persistent queue that may or may not have items in it at any point in time

Just to verbalize more, because this comment didn't connect for me.

In my mind, I comprehend 4 main scenarios -- based on mixing two main variables:

* _Persistent vs ephemeral_ (new style vs old style)
    * Is `$queue` stored in `civicrm_queue`?
    * There's no real advantage to the ephemeral style AFAIK, except for continuity for older callers.
* _Background service vs transactional batch_ (`outbound_mail` vs `import_1234`).
    * Do we handle an open-ended task-list forever? Or do we handle a specific task-list for short timeframe?
    * These can have different implications for how you comprehend configuration, logging, etc.

Mixing those, we get the 4 cases:

| Case | Definition | Typical Execution Method | Additional Notes
| -- | -- | -- | -- 
| Persistent background service | __Persistence__: civicrm_queue <br/> __Name__: outbound_mail | APIv4 Queue  (called via cron or coworker) | 
| Persistent batch run |__Persistence__:  civicrm_queue <br/> __Name__: import_1234 | CRM_Queue_Runner->runAllInteractive() | Internally may involve other methods (e.g., runAllViaWeb(), APIv4, coworker, etc).
| Legacy batch run | __Persistence__: n/a <br/> __Name__: import_1234 | CRM_Queue_Runner->runAllViaWeb() |  
| Legacy background service | __Persistence__: n/a <br/> __Name__: outbound_mail | Varied  | This was only done in contrib. I think there were a couple variations on it.

I interpreted your goal/scenario as "Write phpunit tests involving a persistent background service". If I were trying to do that, how would I have approached testing?

1. `runAll()` probably wouldn't have entered my mind. A persistent background service has no end (*there is no such as "all" unless you're going to do an infinite sleep-poll loop, which you don't want in a test*).
2. Background services run via APIv4 `Queue.runItems` (via cron/coworker). 
3. So I probably would've landed on something like:
    ```php
    function testMyQueue() {
      Civi::queue('foo', [ .... 'batch_limit' => 9999...]);
      ...
      Civi\Api4\Queue::runItems()->setQueue('foo')->execute();
    }
    ```
 
Relatedly -- `Queue.runItems` is the envisioned as the normal thing for a background service, so it doesn't muck around with `disableBackgroundExecution()`.

(*None of that's a criticism. I can see how one might interpret `runAll()` to mean "run every item that's currently available" -- so then you would think to use `CRM_Queue_Runner->runAll()`, esp if you'd used it before for batch-runs.*)

**Comment by eileenmcnaughton** [comment]
@totten thanks - I picked up `runAll` from the docs https://docs.civicrm.org/dev/en/latest/framework/queues/#1-creating-a-queue & an existing unit test usage

**Pull request merged**
