### PR TITLE
Fix incorrect placeholder text on 'Create Campaign' form

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes some incorrect placeholder text on the form to create/edit a campaign, for the select fields "Campaign Type" and "Campaign Status"

Before
----------------------------------------
image

After
----------------------------------------
image

### CODE REVIEW

**Comment by colemanw** [comment]
@agh1 I think this might be related to some work you did fixing placeholders for accessibility.

**Comment by demeritcowboy** [comment]
crossref: https://lab.civicrm.org/dev/core/-/issues/2411

**Comment by demeritcowboy** [comment]
This works for me.

As noted in the ticket this also happens with grants, but doesn't come up in other places because the field is usually required. Just oddly for the grants page it's required and also shows a placeholder.

**Comment by demeritcowboy** [comment]
Grants PR: https://github.com/civicrm/civicrm-core/pull/19768

**Comment by eileenmcnaughton** [comment]
merging based on @demeritcowboy review

**Pull request merged**
