### PR TITLE
ensure shared address is updated in reverse

### PR DESCRIPTION
**Pull request by jmcclelland**
Overview
----------------------------------------

Resolves https://lab.civicrm.org/dev/core/-/issues/4479

When Contact A's address is shared with Contact B and contact B updates that address, ensure it is updated in Contact A's records as well.

Before
----------------------------------------

Shared address changes are only propagated when the owner of the address updates the address. They are not propagated when a contact that is sharing the address updates it.

To replicate:

1. Create contact A with address A.
2. Create contact B with name and email. Create a shared address with address A
3. Create a profile with first name, last name, email and address (use primary address).
4. Fill out the profile with contact name and email (so it matches) contact B. Enter a new address.

The result:

Contact A has the old address
Contact B has the new address, but it is still displayed as if it is shared with Contact A.

After
----------------------------------------

The edit to Contact B's address propagates to Contact A so they continue having the same address.

### CODE REVIEW

**Comment by agileware-justin** [comment]
udpated? or updated?

**Comment by jmcclelland** [comment]
Thanks for the heads up on the typo in the pull request name. Should be fixed now. And seems like the test failures are related. I'm working on that now.

**Comment by jmcclelland** [comment]
@agileware-justin I think I have finally this sorted out now. Unit tests for the win :).

Let me know if it looks ok to you and I can rebase all the commits into one.

**Comment by agileware-justin** [comment]
Thanks @jmcclelland I'll test this now. Good work!

**Comment by agileware-justin** [comment]
Jenkins test this.

**Comment by agileware-justin** [comment]
Tested and confirmed working

1. Created Contact A with address A.
2. Created Contact B with name and email, use a shared address with address from Contact A.
3. Submitted a profile with first name, last name, email and address (use primary address).
4. Fill out the profile with contact name and email (so it matches) Contact B. Enter a new address.
5. The result, the edit to Contact B's address propagates to Contact A

The shared address has been updated. Both Contact B and Contact A have the same address.

**Comment by jmcclelland** [comment]
Thanks @agileware-justin - I just squashed the commits so it should be ready to merge.

**Comment by seamuslee001** [comment]
@jmcclelland can you add a note into https://docs.civicrm.org/user/en/latest/organising-your-data/contacts/ to indicate shared addresses will be updated in both directions?

**Comment by jmcclelland** [comment]
@seamuslee001 Yes - good idea. I just opened an MR: https://lab.civicrm.org/documentation/docs/user-en/-/merge_requests/686

**Pull request merged**
