### PR TITLE
Update civicrm_generated

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
Some message template changes didn't get into the sample data.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@demeritcowboy I think you need to close this & re-do after we've up-merged your 5.39 PR or we will never get out of merge -hell

**Comment by seamuslee001** [comment]
@eileenmcnaughton I'm going to take care of that for him

**Comment by eileenmcnaughton** [comment]
tada - stale!

**Comment by seamuslee001** [comment]
@demeritcowboy I think your changes didn't touch civicrm_domain.mysql so there was no issues with the up merge so I don't know if we still need this?

**Comment by demeritcowboy** [comment]
That's interesting how the upmerge works then since I would have expected it to update the civicrm_domain line in civicrm_generated so that master would now show 5.39, but it doesn't.

**Pull request closed without merging**
