### PR TITLE
CRM-19987 do not show activities for disabled activity type

### PR DESCRIPTION
**Pull request by sunilpawar**
* [CRM-19987: Disabled activities are shown in search results](https://issues.civicrm.org/jira/browse/CRM-19987)

### CODE REVIEW

**Comment by yashodha** [comment]
test this please

**Comment by xurizaemon** [comment]
This patch does not appear to remove activities from the contact's activity tab as intended?

I agree with @docjava, it doesn't make sense to include disabled activity types in the resultset, then skip them. If there was a large number of activities of a disabled type, this approach would not perform well. (Disabling an activity type to reduce load seems like a likely tactic for a beleagured CRM admin.)

**Comment by eileenmcnaughton** [comment]
I have read this feedback & am adding reviewer comments on the 4.7 version with these in mind

**Comment by jackrabbithanna** [comment]
The same fix for 4.7 was not merged, so this will not be, closing.

**Pull request closed without merging**
