### PR TITLE
Afform - Allow public submission (PUB-CONTACT). Expand E2E test coverage.

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------
This makes it possible to submit new contact records to `Afform` as an anonymous user, and it includes E2E test-coverage to that effect.

Before
----------------------------------------

In [afform-security](https://lab.civicrm.org/dev/core/-/wikis/afform-security):

* ❌ None of the `PUB-*` scenarios work.
* ✅ `SELF-CONTACT` (with authenticated CMS user) works.
* ⚠️ There is some partial work toward other SELF-* variations, but the approach needs a change. ([Related discussion](https://chat.civicrm.org/civicrm/pl/dtkfh8xibtrqxdk6q1cwazzasr))

After
----------------------------------------

The patch introduces some new configuration options:

Screen Shot 2021-02-10 at 11 39 46 PM

These choices are recorded in the form as part of the `<af-entity>` options, eg:

```xml
<af-entity name="me" type="Contact"  security="RBAC"
  actions="{create: true, update: false}"/>
```

The `security` option describes the access-control model for this form:

* __[Role-based access control (RBAC)](https://en.wikipedia.org/wiki/Role-based_access_control)__: Based on the authenticated user, their roles, and the correlated permissions. (aka `checkPermissions=TRUE`)
* __Form-based access control (FBAC)__: Disable RBAC. Instead, rely on options configured in this form. (aka `checkPermissions=FALSE`)

A few examples of how these would be used:

* `PUB-CONTACT` ==> Set `security=fbac` and `actions={create:true}`
* `BACK-MENTOR` ==> Set `security=rbac` and `actions={create:true,update:true}`
* `SELF-CONTACT` ==> Set `security=fbac` and `actions={update:true}` (and the autofill by user)

Those scenarios are not all tested here. Here is the expected change in support for scenarios:

* ✅ `PUB-CONTACT` works and has an E2E test.
* ✅  `SELF-CONTACT` (with authenticated CMS user) works.
* ⚠️ The partial work has been walked back.

Technical Details 
----------------------------------------

Testing the various security scenarios will require a number of examples. This adds a new type of test-file with an aim to make it easier to test these. The test case for `PUB-CONTACT` is written with three files:

* `ext/afform/mock/ang/mockPublicForm.aff.html`: An example of form which does PUB-CONTACT scenario (layout/HTML)
* `ext/afform/mock/ang/mockPublicForm.aff.json`: An example of form which does PUB-CONTACT scenario (metadata)
* `ext/afform/mock/ang/mockPublicForm.test.php`: A unit-test which makes some valid and invalid submissions

(See: 189366f11217742fb28d4a4d0e5363fbac381feb) 

The nice thing about this is model is that it's easier to inspect/iterate - you can load the example into the web-based editor, and you can run/submit the example interactively. The example HTML and the assertions are in adjacent files.

### CODE REVIEW

**Comment by totten** [comment]
@seamuslee001 (cc @colemanw ) - OK, updated tests, runtime, admin GUI, and PR description. This should be working/reviewable now.

**Comment by seamuslee001** [comment]
@totten maybe I am being a bit daft but it seems you have removed the checksum handling but its not present elsewhere? Maybe I'm just not picking up how that is being handled now in this model?

**Comment by totten** [comment]
> ...it seems you have removed the checksum handling but its not present elsewhere? Maybe I'm just not picking up how that is being handled now in this model?

Right. Just a note for the record -- we talked about this out-of-band. The basic issue is that the checksum/token was being applied at the wrong level. It should determine the active user/contact rather than binding individual entities. This is also the main issue in the MM log at https://chat.civicrm.org/civicrm/pl/dtkfh8xibtrqxdk6q1cwazzasr

**Comment by seamuslee001** [comment]
I tested this and created a public form (i.e. open to Anon users) and in RBAC mode the form failed to submit which is expected as Anon users didn't have access CiviCRM. It did render the following error which probably could be styled better than a standard alert

permission-errror-afform

When I changed it to be Form based Access Control (FBAC) the form correctly submitted and created a new contact (it was a very basic new individual form) 

One thing I would also say is that on Garland with a very basic form as per the screenshot the submit button gets half hidden which isn't related to this PR but probably needs to be fixed.

I'm going to flag this as merge ready as, following todays meeting Coleman is also going to give this a look over as well

**Comment by eileenmcnaughton** [comment]
@colemanw this is in your court it seems

**Comment by colemanw** [comment]
@totten from the screenshot it looks like you are setting create/update mode checkboxes on a per-form basis? My concern about that is that many forms will need this to be on a per-entity basis.
Simple example: allow a checksum user to update their mailing preferences and, and create an activity record when they submit the form. That's an UPDATE op for the contact but CREATE for the activity.

**Comment by totten** [comment]
@colemanw It's not per-form -- it's per-entity (`<af-entity>`) which is how I recalled our chat. The screenshot just elides the context. (Note, for example, that `security` and `actions` appear on `af-entity` in `mockPublicForm.aff.html`, `FormDataModelTest`, and `Generic.html` , putting it adjacent to the `url-autofill`, which is also per-entity.) I'll update the `r-explain` to mention how this affects the schema.

There is a similar consideration, though, regarding with `Email`/`Phone`/`Address`, which I wasn't as sure about. These are modeled as joined-entities rather than entities in their own right. I fiddled locally with the idea of adding some mapping to do implied grants (e.g. "UPDATE on Contact implies CREATE|UPDATE|DELETE on Email/Phone/Address"). But then I realized I haven't really touched `af-join` stuff before, so it seemed better to KISS and only reason about the first part. But I think what's needed is some docs for the tags and some examples how the markup would look.

**Comment by eileenmcnaughton** [comment]
@totten looks like this needs a rebase

**Comment by totten** [comment]
Yup, thanks @eileenmcnaughton . Rebased.

I think there's a known-issue that this doesn't address join-entities, but we haven't really sorted what that should be. The immediate question (@colemanw @seamuslee001) is whether we should merge this first and sort that later -- or vice-versa.

**Comment by colemanw** [comment]
retest this please

**Pull request merged**
