### PR TITLE
Rename function enableFullGroupByMode to be reenableFullGroupByMode t…

### PR DESCRIPTION
**Pull request by seamuslee001**
…o be more expliict about what the function does

Overview
----------------------------------------
This just renames the function as per discussion with Eileen and Tim

ping @eileenmcnaughton @totten

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
re-enable just doesn't camel well :-(

**Comment by eileenmcnaughton** [comment]
( I support this change but will wait a bit to see any comments from @totten before labelling it up)

**Comment by totten** [comment]
Agree this is clearer. 👍  Merge on pass.

**Comment by eileenmcnaughton** [comment]
As a follow up @seamuslee001 I have been trying locally (5.6 FULL GROUP BY) & I think you should remove these checks

CRM_Utils_SQL::supportsFullGroupBy() 

- It does adequate mysql checks & the above is not so much 'support full group by ' as 'is mysql 5.7' - which is pseudo for 'anyValueHackWorks' on this system - but from my testing the turn off code is not limited to 5.7

**Pull request merged**
