### PR TITLE
5.67

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Comment by colemanw** [comment]
@seamuslee001 the `set-version` commit needs to be dropped from this PR.

**Comment by demeritcowboy** [comment]
I don't think there's a choice. Previous experience suggests that if it's removed it will just come back again in the next upmerge PR. It shouldn't change the conflicted files. Let's see.

**Comment by demeritcowboy** [comment]
Oh I don't have permission to do it when there's a conflict.

**Comment by colemanw** [comment]
I was hoping to make this a bit less painful with #27922

**Pull request merged**
