### PR TITLE
CRM-18483: Paypal payments - Pending (Incomplete Transaction)

### PR DESCRIPTION
**Pull request by monishdeb**
- [CRM-18483: Paypal payments - Pending (Incomplete Transaction)](https://issues.civicrm.org/jira/browse/CRM-18483)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
It's probably better to deal with this in the IPN class it relates to for 2 reasons
1) then it can be added to the unit tests
2) we are kind of deprecating these extern/ipn entrance points

**Comment by monishdeb** [comment]
In my opinion I would prefer to deprecate the exten/ipn calling in future version not in 4.7 stable version, because it would take time to write the improvement along with test coverage and it might invite unintended regressions. What ya think ?

**Comment by eileenmcnaughton** [comment]
I don't think there is such a thing any more - I think we are going to be doing ongoing continuous improvements with stricter QA. OTOH the future version thing just led to us getting well down the track before discovering 2 payment processors didn't work at all on 4.7

**Comment by eileenmcnaughton** [comment]
As an aside - this comes from a recent decision to bootstrap civicrm from the ipn & now we are doing semi-authentication off the parameters. Are we going down the right path here? It feels dodgey from a security point of view - perhaps we should go back to the original ticket & figure out if there was an alternative fix to bootstrapping. We can easily test paypal pro IPN through unit tests so we are on much safer territory there

**Comment by eileenmcnaughton** [comment]
Hmm - perhaps paypal pro won't replicate it - still the question remains - are we walking into a security hole if we start bootstrapping & they adding layers of logging in or authentication.

**Comment by monishdeb** [comment]
Ok will take a look at it

**Comment by mlutfy** [comment]
For what it's worth, the loadBootstrap seems to make Drupal fail (with IPNs / paypal standard). I ran into this issue with 2 Drupal clients. If we cannot find a proper solution, I would vote in favor of reverting the initial patch from CRM-18245.

**Comment by eileenmcnaughton** [comment]
I vote to revert it for now & I'll try to do a better PR for next month. I might get it done in time for this month - but I don't want to guarantee that or that Monish will have time to review it if I do

**Comment by monishdeb** [comment]
I agree to revert the changes 
Line 56 -  CRM_Utils_System::loadBootStrap(); 
as this will fix for Drupal and wordpress but break Joomla.  Although the current PR changes make it work for all 3 CMS but its kinda hackish fix on a security point of view and need to found a alternative fix for it but that will need time.

**Comment by monishdeb** [comment]
@eileenmcnaughton @mlutfy I have updated the PR should I merge it !!

**Comment by eileenmcnaughton** [comment]
yep - we just need to re-open the original issue now!

**Comment by monishdeb** [comment]
On second thought I think its better to retain previous code ONLY for Joomla for this release.  I will definitely send a alternative PR to avoid bootstraping but for the time being its better to revert the changes only for Drupal and WP.

**Comment by monishdeb** [comment]
Reopened https://issues.civicrm.org/jira/browse/CRM-18245

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by eileenmcnaughton** [comment]
I'm OK with this - I'm happy to look at trying to do an improved version so make paypal std more like the others

**Comment by monishdeb** [comment]
Sure

**Pull request merged**
