### PR TITLE
SearchKit - Update operator labels

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Updates search kit labels to hopefully better describe ReGex

### CODE REVIEW

**Comment by seamuslee001** [comment]
Seems fine to me @mlutfy any objections?

**Comment by mlutfy** [comment]
I don't mean to nitpick, but why not "Regular Expression Matches" ?

- despite SearchKit being a dev tool, "Reg Exp" is scary looking. Exp could be "exponent" or "explosive" :-)
- if it's a space issue, I'd prefer Regex, because it's a more commonly used acronym, but keep in mind that most other languages do not use the term Regex, only the long form. French uses "Expression régulière", and I'm not sure how I would translate "No Regexp Match" (other than "Ne correspond pas à l'expression régulière").

Looking at my email filtering programs, a more common pattern is to have only "Contains" or "Does not contain", and then geeky people know they can use regexps (notable exception: in LibreOffice, it's a checkbox on the search options).

(when things are difficult to translate, it's often a sign that they are difficult to understand for most non-hardcore-dev English speakers)

**Comment by colemanw** [comment]
@mlutfy there is already a "CONTAINS" operator, and yes there is a space issue so brevity is important. But maybe a less-technical term for Regex could be "Pattern"?

What about "Matches Pattern" / "Doesn't Match Pattern".

**Comment by mlutfy** [comment]
@colemanw Works for me. Thanks!

**Pull request merged**
