### PR TITLE
Add pre/post create hooks for OptionValue 

### PR DESCRIPTION
**Pull request by i-grou**
Overview
----------------------------------------
For Civicase extension it is required to have post create hook to monitor if option value was enabled/disabled. Somehow hooks on create are missing, so this PR will add them.

Technical Details
----------------------------------------
Just updated `CRM_Core_BAO_OptionValue::add()` method to add pre/post create/edit hook calls.

### CODE REVIEW

**Comment by mattwire** [comment]
@ivan-compucorp There is some inconsistency where pre/post hooks are called (sometimes in add(), sometimes in create()).
In the case of `CRM_Core_BAO_OptionValue` `add()` is called directly in various places so the pre/post hooks should be added there. Do you want to tadd them to `CRM_Core_BAO_OptionGroup` at the same time?

**Comment by eileenmcnaughton** [comment]
Actually I'm OK  with this location - I did a bit of a grep and most of the places are a bit obscure & could  be fixed if people hit the need for the  hook to be called.

The one that probably should be fixed is the Admin options form.

Given there is no logic regarding add vs create I think we should be working towards deprecating the add functions & folding them into create.

Note we try  to squash the syntax a little: 

```
    $hook = empty($params['id']) ? 'create' : 'edit';
    CRM_Utils_Hook::pre($hook, 'Phone', $params['id'] ?? NULL, $params);
....
    CRM_Utils_Hook::post($hook, 'Phone', $phone->id, $phone);




```

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by ivan-compucorp** [comment]
I guess it's a good idea to add pre/post delete hooks too. What do you think?

**Comment by eileenmcnaughton** [comment]
So there are symfony listeners on delete actions but as far as I know we are still adding them - @colemanw any thoughts?

**Comment by eileenmcnaughton** [comment]
@mattwire I'm OK with this now - I think we can update any places that bypass it - ideally to dall apiv4....

**Comment by mattwire** [comment]
@eileenmcnaughton I think it's a really bad idea to add this to create and have yet another hook that is sometimes called, sometimes not. The amount of time I and other developers waste because hooks are not consistently called is unbelievable!
Let's just add it to the `add` and have some consistency please! In terms of coding/testing we don't lose anything by putting it there and we *do* gain consistency

To back that up:
- `CRM_Core_BAO_OptionValue::add()` is directly called in at least 5 places in core *including by API4* in `DAOActionTrait->writeObjects()`. So merging this in the create function would mean that any calls for OptionValue by API4 would not call the hook. That doesn't seem very obscure.
- It is also called in `CRM_Core_OptionValue::addOptionValue` which in turn is called in a further 5 places none of which seem particularly obscure.

**Comment by eileenmcnaughton** [comment]
I'd rather add it to the right place - but @colemanw why is apiv4 calling a weird function for add?

We could fix CRM_Core_OptionValue::addOptionValue to call create fairly easily

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I can't see the call in ) is directly called in at least 5 places in core including by API4 in DAOActionTrait->writeObjects()

I see it in 
- 'create' 
- 2 heavily  deprecated places relating to old extensions system
- addOptionValue


The latter is called from 
- some deprecated places
- saving report instances
- The generic admin form.


The generic admin form seems worth fixing.

**Comment by ivan-compucorp** [comment]
Moved create/edit hooks to add() method, also added delete hooks. Could you check if it's okay guys?

**Comment by yashodha** [comment]
@ivan-compucorp Can you squash your commits?

**Comment by ivan-compucorp** [comment]
Squashed.

**Comment by mattwire** [comment]
@ivan-compucorp This PR has just been merged: https://github.com/civicrm/civicrm-core/pull/16714 which provides a way to listen for create/edit on optionvalues and all other entities. Instead of merging this could you build a solution using that?

**Comment by ivan-compucorp** [comment]
@mattwire actually I've already solved my issue using symfony listeners like that:
```
Civi::dispatcher()->addListener('civi.api.respond', ['CRM_Civicase_Event_Listener_CaseTypeCategoryIsActiveToggler', 'onRespond'], 10);
```

So this PR can be closed.

**Pull request closed without merging**
