### PR TITLE
dev/core#183 Use Standard CRM_Utils_SQL_TempTable builder to create temporary tabl…

### PR DESCRIPTION
**Pull request by seamuslee001**
…e in Campaign and upgrade

Overview
----------------------------------------
This converts the creation of temporary tables in CRM/Campaign and CRM/Upgrade to be standardised through the CRM_Utils_SQL_TempTable interface

Before
----------------------------------------
Uses the deprecated `CRM_Core_DAO::createTempTableName` function to generate a temporary table name

After
----------------------------------------
Uses the standard CRM_Utils_SQL_TempTable functionality

ping @monishdeb @eileenmcnaughton @totten

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Hmm -  I can take the upgrade ones on faith based on upgrade tests but I found the other borked

Screen Shot 2019-11-11 at 9 59 19 AM

**Comment by eileenmcnaughton** [comment]
We should probably wrap those fns in some sort of unit test..

**Comment by seamuslee001** [comment]
@eileenmcnaughton have just pushed a fix for that malformed category thing

**Comment by seamuslee001** [comment]
@eileenmcnaughton i have added a unit test for the change in CRM/Campaign/BAO/Query.php but i'm not sure how i would be able to generate one for the Interview change

**Comment by eileenmcnaughton** [comment]
I was able to reserve & interview without fatal error & it passed through these lines - gtg

**Pull request merged**
