### PR TITLE
CRM-21632 - {membership.fee} prints out in documents with 9 decimal p…

### PR DESCRIPTION
**Pull request by yashodha**
…laces

Overview
----------------------------------------
Membership fee prints out in documents with 9 decimal places due to recent changes

Before
----------------------------------------
fee_before

After
----------------------------------------
fee_after

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
We should be able to get rid of the $ no? I think it's just another param?

**Comment by samuelsov** [comment]
Yes we should keep the same behaviour as before if possible (i.e. not adding the currency) using `$onlyNumber` param : 

```php
CRM_Utils_Money::format($value, NULL, NULL, TRUE);
```

**Comment by yashodha** [comment]
@eileenmcnaughton @mattwire @samuelsov 

You are right, made the changes and now showing amount sans currency

change_after

**Comment by eileenmcnaughton** [comment]
Thanks @yashodha - if you squash the commits I will add merge-on-pass tag

**Comment by yashodha** [comment]
closed in  favor of #12196

**Comment by eileenmcnaughton** [comment]
Cool - I gave it merge on pass

FWIW I usually do the following to squash commits
```
git fetch -f origin master
git rebase -i origin/master
git push -f myrepo mybranch
```

**Comment by paulorokonui** [comment]
https://civicrm.stackexchange.com/questions/25892/currency-formatting-incorrectly-on-membership-renewal-reminders?noredirect=1#comment29441_25892

Seems to be a problem still for Membership Renewal Reminders - does this use a different process?

**Comment by eileenmcnaughton** [comment]
quite possibly - you are on 5.4.1 right now? (5.5 is out on Wed)

**Comment by paulorokonui** [comment]
Yes, so any idea how I can resolve this?

**Comment by mattwire** [comment]
@paulorokonui Do you know which messagetemplate is being used for the scheduled reminder?  And do you have a screenshot/copy-paste of the part which is failing?

**Comment by paulorokonui** [comment]
This is a template I've created for Membership Renewal Reminders - screen shots as follows
message
template
...one is the template and the other is the resulting message

**Comment by eileenmcnaughton** [comment]
@paulorokonui can you open an issue to track in gitlab?

**Comment by paulorokonui** [comment]
Registered but can't see the Create New Issue bit anywhere :(

**Comment by paulorokonui** [comment]
Hi Eileen, I was wondering what the process is from here regarding this bug - looking at the report I'm not sure if anything is happening with it or is scheduled to happen? We are ok with working round this - I'm just not sure how things work with this sort of problem.

Thanks

Paul

**Comment by eileenmcnaughton** [comment]
@paulorokonui by this bug you mean the new bug you have been describing - not the bug fixed by this issue? 

I think you are working on a custom template you wrote for the scheduled reminder? The core built in templates use the following format to render date fields - which passes it through a formatter

 {$paymentAmount|crmMoney}
or 
 {$paymentAmount|crmMoney:$currency}

Maybe something like that will work for you

**Comment by paulorokonui** [comment]
Hi Eileen, thanks for this, I’ll give that a try.
Regards,
Paul

**Comment by grantwatt** [comment]
We have a similar problem with the membership fee token being expressed with 9 decimals points in scheduled reminders. So I am wondering if suggestion above has resolved the problem.

**Pull request closed without merging**
