### PR TITLE
CRM-17789 - CRM_Custom_Form_Group - Simplify reltype list

### PR DESCRIPTION
**Pull request by totten**
- [CRM-17789: Support PHP 7](https://issues.civicrm.org/jira/browse/CRM-17789)

### CODE REVIEW

**Comment by totten** [comment]
Score: -30 SLOC on the principal! (Alas, +18 on the simple/generic helper w/docs...)

**Comment by seamuslee001** [comment]
tested this, works sensibly

**Comment by jitendrapurohit** [comment]
Tested this using different relationship types(normal/multilingual setup) for subtypes, organisation, households, etc. All seems to be loading in the formatted display correctly. This is good to be merged.

Thanks!

**Comment by totten** [comment]
jenkins, test this please

**Comment by totten** [comment]
jenkins, test this please

**Comment by totten** [comment]
The reported failure `CRM_Contribute_Form_ContributionTest.testSubmitCreditCardPayPal` is pre-existing/not-relevant.

**Pull request merged**
