### PR TITLE
CRM-20392, Code cleanup

### PR DESCRIPTION
**Pull request by pradpnayak**
----------------------------------------
* CRM-20392: Credit card payment not recorded when contribution is partially paid
  https://issues.civicrm.org/jira/browse/CRM-20392

### CODE REVIEW

**Comment by monishdeb** [comment]
@eileenmcnaughton reviewed the cleanup and changes works for me. Can you merge it if it looks good. This is related to #10126

**Comment by eileenmcnaughton** [comment]
so this has test coverage somewhere else?

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I'm ok to merge based on @monishdeb review once the tests pass as it does look like a straightforward cleanup.

It would be good to confirm what test coverage there is over this- although I believe it is fairly well covered

**Pull request merged**
