### PR TITLE
(WIP) CRM-18460 - Contribution Aggregate custom search - use relative date …

### PR DESCRIPTION
**Pull request by MegaphoneJon**
…fields

### CODE REVIEW

**Comment by seamuslee001** [comment]
I applied this to a local 4.7 install tested by checking different contribution date ranges and they all come out well with correct end time and start time for the dates as well. I haven't yet tested checking if smart groups built with this custom search would be impacted or how they would be impacted.

**Comment by PalanteJon** [comment]
@seamuslee001 You're right - this would almost certainly break a saved custom search created before this.  Hmm.  I could maybe write a SQL statement to fix the saved search values?  Or I could reinsert the old date fields, but hidden - but that feels less maintainable in the long term.  Unless someone thinks otherwise, I'll look at the SQL.

**Comment by seamuslee001** [comment]
Don't forget John the form Values is in serialised form. 

So in my mind there are 2 ways of attacking that problem. No. 1 in the upgrade add in to the PHP files a job of finding all saved searches using this custom search. Unseralising the form values. Altering the array of data to match up with the new form values. Re-serialise the values and update the DB. Or 2. Try and do the same job when the smart group is loaded. Both will be a bit of trial and error but I think 1 may be better. But exactly what conversion would need to happen I don't know

**Comment by seamuslee001** [comment]
@PalanteJon John

I have done  a bit of testing over this weekend of a possible solution. Adding the following code to the top of the __construct function seems to do the right thing and it would replace the current 

```php
$this->_formValues = $formValues 
```

```php

    $date_conversion = array(
       'contribution_date_low' => 'start_date',
       'contribution_date_high' => 'end_date',
    );
    foreach ($date_conversion as $new_field => $old_field) {
      if  (!array_key_exists($new_field, $formValues) && array_key_exists($old_field, $formValues)) {
        $formValues[$new_field] = $formValues[$old_field];
      }
    }
    if (!array_key_exists('contribution_date_relative', $formValues)) {
      $formValues['contribution_date_relative'] = 0;
    }
    $this->_formValues = $formValues;

```

**Comment by PalanteJon** [comment]
@seamuslee001 Thank you for this!  I was on the fence about whether I wanted to do the work to push this into core, but with this code to test, I'll definitely put in the effort.  It might be a week or so before I get the chance though!

**Comment by eileenmcnaughton** [comment]
Hi, I'm happy to look at getting this merged this review week if you are able to get the fix through, esp since Seamus has already done some review on it

**Comment by PalanteJon** [comment]
I'll see what I can do @eileenmcnaughton but I'm prioritizing reviewing others' code that I think is more important!  If this slips a month, I doubt anyone will care.

**Comment by JoeMurray** [comment]
Heh Jon, as Release Manager this month, I'm trying to recruit people to help pare down the backlog of almost 100 PRs, some going back to last summer. I'm wondering if you would be able to help QA another PR if I got someone to QA this PR?

**Comment by JoeMurray** [comment]
@samuelsov would you be interested in reviewing this PR?

**Comment by samuelsov** [comment]
@JoeMurray As far as i understand, @PalanteJon need to rework it and @seamuslee001 / @eileenmcnaughton have there hands on the reviewing already. If i'm wrong, i have no problem reviewing it.

**Comment by PalanteJon** [comment]
@samuelsov this is correct.  Let's hold this PR for now until I have time.

**Comment by litespeedmarc** [comment]
@PalanteJon .  Jon, following up on outstanding issues this coding sprint.  Are you still intent on doing the last changes required?

**Comment by PalanteJon** [comment]
Hey @litespeedmarc - I've been watching your cleanup with great approval!  I knew it would eventually come around to me...

I've explained the situation to the Partners' list and the core team - but in short, I'm leaving my job in the next week or so.  After a break of a couple of weeks, I'll be wrapping up work on all open PRs.  So while I generally approve of what you're doing, I think I'll ask to be considered a special case for the next few weeks!

**Comment by litespeedmarc** [comment]
Well, by you replying you've given it a heartbeat, which means its still alive.  I've flagged this as WIP for now.  You can remove the label and adjust title once its ready (hopefully you have access to do this on your own PRs).

**Comment by monishdeb** [comment]
Closing in favor of https://github.com/civicrm/civicrm-core/pull/9493

**Pull request closed without merging**
