### PR TITLE
Convert the Fullfilled Date field in preimum section on backoffice co…

### PR DESCRIPTION
**Pull request by seamuslee001**
…ntribution from from jcalendar to datepicker

Overview
----------------------------------------
This converts the Full filled date which is in the preimum tab on backend contribution add / edit screens from jcalendar to datepicker

Before
----------------------------------------
Legacy jcalendar used
Screenshot 2019-04-01 14 06 01

After
----------------------------------------
Modern datepicker used
Screenshot 2019-04-01 14 08 00

ping @eileenmcnaughton @mattwire @monishdeb

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I noticed 2 things

1) When I go to edit it the defaults don't fill right
Screenshot 2019-04-01 14 10 59

2) there are 2 places in the CRM_Contribute_Form_AdditionalInfo form that still seem to do some date wrangling that may not be required now - & may relate to 1

**Comment by eileenmcnaughton** [comment]
Actually default bug is prob from CRM_Contribute_Form_Contribution

```
      if ($this->_productDAO->fulfilled_date) {
        list($defaults['fulfilled_date']) = CRM_Utils_Date::setDateDefaults($this->_productDAO->fulfilled_date);
      }
```

**Comment by seamuslee001** [comment]
thanks @eileenmcnaughton i think i have fixed the defaults now

**Comment by eileenmcnaughton** [comment]
Yes it looks better now

**Comment by seamuslee001** [comment]
@eileenmcnaughton sorted

**Pull request merged**
