### PR TITLE
CRM-21712: unit test

### PR DESCRIPTION
**Pull request by monishdeb**
This PR adds unit test for https://github.com/civicrm/civicrm-core/pull/11592

---

 * [CRM-21712: Improve Fiscal Year filter for reports](https://issues.civicrm.org/jira/browse/CRM-21712)

### CODE REVIEW

**Comment by monishdeb** [comment]
ping @magnolia61 @MegaphoneJon @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
Typo error - check your class name

PHP Fatal error:  Cannot redeclare class CRM_Utils_StringTest in /home/jenkins/buildkit/build/core-11663-5w0te/sites/all/modules/civicrm/tests/phpunit/CRM/Utils/StringTest.php on line 346

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
requires #11592 to pass I guess

**Comment by monishdeb** [comment]
Closing in favor of https://github.com/civicrm/civicrm-core/pull/12137

**Pull request closed without merging**
