### PR TITLE
FormBuilder - group subscription support

### PR DESCRIPTION
**Pull request by kurund**
Overview
----------------------------------------
Add groups support for Form Builder

image

Screenshot from 2024-07-18 00-08-14

### CODE REVIEW

**Comment by JadeGaunt** [comment]
Tested this and noted my findings below, one thing I'm confused about is how the opt in & out and opt in only configuration options are meant to differ. 

Opt in & out: Checkbox which adds you to the group as expected after confirming by email. Leaving the checkbox unticked, I would have expected to have been removed from the group though unless I'm misunderstanding that?

Opt in only: When checkbox ticked, user gets added to group after confirming by email. I don't see how this differs from the opt in & out option.

Auto add: This works without having to add any fields to the form. You just add the group in the value field and then select 'yes' from the dropdown list and users will automatically be added to groups without needing to confirm their email.

Auto remove: This works, you have to select the group as the value and then select yes and then users will automatically get removed from the group selected in the value. You can select more than one group as well.

Also not a huge issue but line 37 of GroupSubscription.php has a spelling error, 'configue' instead of 'configure'.

**Comment by colemanw** [comment]
@kurund @JadeGaunt I've pushed an update for all of that, and also updated the screenshot in the description of this PR.

**Comment by kurund** [comment]
@colemanw 

Your changes looks good to me and is working as expected.

One unrelated bug is one cannot resubscribe to a group via double-opt-in which they have unsubscribed.

**Comment by kurund** [comment]
@colemanw 

Here is the PR for subscription fixes: https://github.com/civicrm/civicrm-core/pull/30758

**Comment by colemanw** [comment]
I've squashed a few commits and added a test to cover NULL values e.g. when leaving a dropdown unselected.
I think this is merge-ready. @JadeGaunt @mattwire do you want to give it any more testing?

**Comment by JadeGaunt** [comment]
@colemanw tested this on my end and is looking good to merge :-)

**Pull request merged**
