### PR TITLE
DAO - Remove fieldKeys(), getLog() and getTableName()

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Removes redundant functions from DAO boilerplate.
Followup to https://github.com/civicrm/civicrm-core/pull/18492

Before
----------
Generated DAO files contain 3 redundant functions.

After
----------
Generated DAO files do not contain redundant functions.

Technical Details
----------

In 2020, 9d89b14d9daeb7ab2a1b8df02434bc74cfec5938 added these functions to the base class, effectively making them redundant in the generated DAO files.
But out of an abundance of caution, they were not immediately removed from the DAO template.
This was so that extensions that generate DAOs with civix (which uses the same template from core) would not immediately lose backward-compat with prior versions of Civi.

At this point enough time has gone by. The functions were added to 5.31 which is quite a few ESR-releases old now.
Any extension wishing to generate DAO files compatible with versions < 5.31 can do so by using an older version of core
when running `civix generate:entity-boilerplate`.

### CODE REVIEW

**Comment by seamuslee001** [comment]
Its probably not significant but I notice with the fieldKeys we are loosing some static caching as https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/DAO.php#L3359 isn't wrapped in Civi::statics unlike the old functions in each individual DAO

**Comment by colemanw** [comment]
@seamuslee001 yes, the old functions were not only a waste of space but also a waste of memory (the function they read from `self::fields()` already uses caching).

**Comment by colemanw** [comment]
New high score for the week!

image

**Comment by eileenmcnaughton** [comment]
@colemanw ouch - I wouldn't have merge it I'd realised it leapfrogs you ahead like that.

**Pull request merged**
