### PR TITLE
Extract `getProfileDisplay()`

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Extract `getProfileDisplay()`

Before
----------------------------------------
the shared part of the code is in a function that does 'other stuff'

After
----------------------------------------
Shared part extracted

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by monishdeb** [comment]
@eileenmcnaughton can I review this?

**Comment by eileenmcnaughton** [comment]
@monishdeb yes please - I need to fix the fails though

**Comment by eileenmcnaughton** [comment]
Ah looks like the test fail was already fixed locally - let's see how it goes now

**Comment by monishdeb** [comment]
@eileenmcnaughton there's is a related error:
```
TypeError: CRM_Event_BAO_Event::getProfileDisplay(): Argument #6 ($note) must be of type ?array, string given, called in /home/homer/buildkit/build/build-1/web/sites/all/modules/civicrm/CRM/Event/BAO/Event.php on line 1302
```

**Comment by eileenmcnaughton** [comment]
thanks @monishdeb - can you merge https://github.com/civicrm/civicrm-core/pull/30393 in the meantime? Then I can rebase out

**Comment by eileenmcnaughton** [comment]
@monishdeb it has passed now

**Comment by monishdeb** [comment]
> thanks @monishdeb - can you merge #30393 in the meantime? Then I can rebase out

done

**Comment by monishdeb** [comment]
Tested, looks good.

**Comment by eileenmcnaughton** [comment]
thanks @monishdeb

**Pull request merged**
