### PR TITLE
SearchKit - Add 'merge contacts' task

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Allows duplicate contacts to be merged from SearchKit.

Before
----------------------------------------
No option to merge contacts.

After
----------------------------------------
image

image

Technical Details
----------------------------------------
Included some cleanup in the Dedupe form to make it work better with ajax, and fixed some (but not all) of the undefined template variables).

### CODE REVIEW

**Comment by seamuslee001** [comment]
Looks good to me merging

**Comment by eileenmcnaughton** [comment]
@colemanw it turns out this causes a regression as it should redirect to the merged contact after merging but now redirects back to the search results - this apparently is quite bad for users

**Comment by colemanw** [comment]
@eileenmcnaughton was it a6f2a80ffbddfc0788199ec824b8aff46ccd1542 that caused the regression?

**Comment by eileenmcnaughton** [comment]
@colemanw yep!

**Pull request merged**
