### PR TITLE
Lower-case field name uf_group.post_URL, cancel_URL

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Lower-case field name uf_group.post_URL & cancel_URL

Before
----------------------------------------
field name is 'post_URL'

After
----------------------------------------
field name is 'post_url'

Technical Details
----------------------------------------
Apiv4 can't handle it as is... mysql doesn't care but it is bad practice & inconsisten & I've added handling to support api-v3

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton we have a few fields like this:
- `UFGroup.post_URL`
- `UFGroup.cancel_URL`
- `Contact.image_URL`
- `ContactType.image_URL` (deprecated)

I agree it's horribly inconsistent to use any uppercase letters in the schema, but what exactly do you mean when you say APIv4 can't handle it? When I've played around with `image_URL` fields in the APIv4 explorer it seems to work ok... (I just tried both read & write and it worked fine).

**Comment by colemanw** [comment]
Aside, our schema is nothing if not amusing. Check out the comment on this field:
https://github.com/civicrm/civicrm-core/blob/b9b48cea87b0f4f129a42c8468d250d1f72c851e/xml/schema/Core/UFGroup.xml#L205-L212

**Comment by eileenmcnaughton** [comment]
@colemanw yeah - I think I was wrong about the apiv4 issue - but I think the upper case in field names will hurt us sooner or later as php & mysql seem to get ever stricter - and fixing this field is perhaps a good test for one day maybe fixing the contact one....

**Comment by monishdeb** [comment]
Merging based on MoP tag.

**Comment by eileenmcnaughton** [comment]
thanks @monishdeb

**Pull request merged**
