### PR TITLE
civicrm_webtest.install - Restore access to edit message templates and tags

### PR DESCRIPTION
**Pull request by totten**
This affects demo builds and (theoretically) other test systems.

### CODE REVIEW

**Comment by seamuslee001** [comment]
@totten should we add in manage tags permission?

**Comment by totten** [comment]
@seamuslee001 Yeah, both of those seem like issues where the test/demo system got left behind. :( Thanks.

Aside: Grepping on these, it's interesting to note that there was an upgrade alert for `edit message templates` (encouraging downstream admins to update their permission settings) -- but  `manage tags` didn't have an alert. That's the kind of gotcha we need to handle better as reviewers.

**Comment by seamuslee001** [comment]
Agree @totten do you think we should add in a post upgrade message for the manage tags?

**Comment by seamuslee001** [comment]
Jenkins test this please

**Pull request merged**
