### PR TITLE
Fix search extension excluded from tarball

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fix search extension excluded from tarball

Before
----------------------------------------
search not in the generated tarballs

After
----------------------------------------
voila

Technical Details
----------------------------------------
We missed this bit

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
retest this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
test this please

**Comment by seamuslee001** [comment]
test this please

**Comment by seamuslee001** [comment]
Test fail unrelated

**Pull request merged**
