### PR TITLE
dev/core#2355 - E_NOTICE on Manage Contribution and Manage Event listings

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/2355

Coming from recent change at https://github.com/civicrm/civicrm-core/pull/19472

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
OK - tbh I'd rather declare the property on the class but also let's just get this fixed

**Comment by eileenmcnaughton** [comment]
@demeritcowboy I just thought - is 5.34 affected?

**Comment by demeritcowboy** [comment]
Oh hmm. The original report was against 5.34, but it was only fixed in master. At the moment it's all consistent but yeah 5.34 still has the bug.

**Comment by demeritcowboy** [comment]
Ah but you noted it wasn't a recent issue.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy thanks - I remember now!

**Pull request merged**
