### PR TITLE
[NFC] Cleanup DAO factory classes for code standards

### PR DESCRIPTION
**Pull request by colemanw**
These 2 files did not pass linting.

### CODE REVIEW

**Comment by mattwire** [comment]
@colemanw Just checking these are not autogenerated files?

**Comment by mattwire** [comment]
test this please

**Comment by colemanw** [comment]
test this please

**Comment by colemanw** [comment]
@mattwire right. They have DAO in their name which caused them to get overlooked by linting, but they are not autogenerated.

**Pull request merged**
