### PR TITLE
dev/core/issues/277, Fixed count to include only live recurring contr…

### PR DESCRIPTION
**Pull request by pradpnayak**
…ibution

Overview
----------------------------------------
https://lab.civicrm.org/dev/core/issues/277

Before
----------------------------------------
before

After
----------------------------------------
new

### CODE REVIEW

**Comment by JoeMurray** [comment]
If the tab count for recurring contributions is going to exclude test ones, then we should probably order the recurring contributions on the tab to put non-test ones first followed by test ones, preserving rest of current ordering within each set.

**Comment by eileenmcnaughton** [comment]
I agree with @JoeMurray - i think the count should include inactive as completed / cancelled are still as relevant as current

**Comment by pradpnayak** [comment]
@JoeMurray and @eileenmcnaughton thanks for the feedback. 

I have pushed the changes to include inactive contribution recur in count and also to sort the list using is_test and start_date. 

new

**Comment by mattwire** [comment]
@pradpnayak This looks good.

Following on from feedback from @JoeMurray @eileenmcnaughton (these points may be better as a follow-up PR, but we should get some feedback on (2) before merging this one:

1. I agree that ordering test transactions last is an improvement, but this will now be different from the contributions list which doesn't do that.
2. It has always annoyed me that the contributions list is ordered newest first, but the recurring contributions list is ordered oldest first.  Any thoughts on fixing that @KarinG @JoeMurray @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
@pradpnayak I support changing to newest first on recurring contributions tab

@guanhuan also

So, proposals (not necessarily blocking this or each other)
1) update count on contribution recur tab to include inactive
2) order contribution recur first by (**is_test ASC, start_date DESC**) - or end_date? or next sched date?
3) order contribution by (**is_test**, receive_date DESC)

I think these are minor & if a small group of highly interested people in this area are unanimous we can proceed

**Comment by eileenmcnaughton** [comment]
I've added merge- ready as I think this is mergeable but we should try to discuss next steps a little more over the next few days

**Comment by eileenmcnaughton** [comment]
Oddly I'm more uncomfortable with making a label change decision without inviting more input than I am about changing the order - probably I just find the newest first case so compelling. I am assuming 'newest' = most recently started.

Inactive also includes completed. I don't like the breakdown as both Cancelled & Completed are as important as in process / pending when I view the tab

**Comment by KarinG** [comment]
Newest first (start_date is probably best as we can now start a series in the future) is no- brainer and would make me personally super happy - I scroll lots:

```
MariaDB [civicrm_semperit_com]> select count(*) from civicrm_contribution_recur where contact_id=2;
+----------+
| count(*) |
+----------+
|      211 |
+----------+

```
Completed -> is not as inactive as one might think :-) You can still Edit a Completed Recurring Contribution Series (token is still on file/active) - and you can Edit that to add on 6 more installments and/or to up the amount. 

Canceled is the only status that's really done (in the GUI here: there is no more buttons), but I also don't see a need to split them up between active and not active; not even with my 211 - I actually like them in order.

image

**Comment by eileenmcnaughton** [comment]
Yeah I would vote for in order - @guanhuan @MiyaNoctem you recently re-organised the recurring tab - was there a reason to do 2 sections as opposed to in order. Sometimes 'Cancelled' is 'Cancelled & restarted' & from my pov chronological is more usable - per @KarinG screenshot

**Comment by mattwire** [comment]
test this please

**Comment by mattwire** [comment]
@pradpnayak So if you update this PR to change the order on recurring to:
`(is_test ASC, start_date DESC)`

then I think we probably have consensus to merge.

**Comment by eileenmcnaughton** [comment]
Looks like the sort is changed per above https://github.com/civicrm/civicrm-core/pull/12553/files#diff-8723151381cc13de28f6686a8ca18a98R193

I'm merging this so it hits 5.5 rc - we can still iterate further improvements if we wish

**Comment by mattwire** [comment]
@eileenmcnaughton @pradpnayak No, the sort is still set to start_date ASC...

**Comment by mattwire** [comment]
@eileenmcnaughton @pradpnayak I've posted a follow-up PR in #12610

**Comment by pradpnayak** [comment]
Sorry @mattwire @eileenmcnaughton i was held up on different work. I have added my testing notes on #12610

**Pull request merged**
