### PR TITLE
CRM-20847 updating PINGBACK_URL to https in CRM_Utils_VersionCheck

### PR DESCRIPTION
**Pull request by jackrabbithanna**
* [CRM-20847](https://issues.civicrm.org/jira/browse/CRM-20847)

### CODE REVIEW

**Comment by jackrabbithanna** [comment]
Backported from https://github.com/civicrm/civicrm-core/pull/10373
Pretty much a no-brainer, merging

**Comment by seamuslee001** [comment]
Just noting we should not merge until after June 7

**Comment by jackrabbithanna** [comment]
@seamuslee001 ok, you got that message in there just in time :)

**Comment by seamuslee001** [comment]
@jackrabbithanna Unless we aren't gonna do a release of 4.6 in June then its ok to merge if we are doing a June 4.6 release then we need to hold until after then

**Comment by jackrabbithanna** [comment]
I think that is TBD at this moment, so we'll hold

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by jackrabbithanna** [comment]
Merging #10408

**Pull request merged**
