### PR TITLE
dev/core#1919 - Missing resubscribe url in text/plain version of unsubscribe confirmation email

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/1919

1. Go back in time about 10 years so that your email reader displays text-only versions of emails.
2. Unsubscribe from a mailing.
3. Read the email confirmation - it's missing the url to resubscribe at the end.

Another way to see this without needing time travel is to go to Administer - CiviMail - Headers,Footers.. and look at the one for unsubscribe and look in the text format section.

Before
----------------------------------------
`You have been un-subscribed from the following groups: {unsubscribe.group}. You can re-subscribe by mailing {action.resubscribe} or clicking `

After
----------------------------------------
`You have been un-subscribed from the following groups: {unsubscribe.group}. You can re-subscribe by mailing {action.resubscribe} or clicking {action.resubscribeUrl}`

Technical Details
----------------------------------------
`ts` in the xml was missing a parameter.

Comments
----------------------------------------
In the github UI it's hard to see but for civicrm_generated the change is at the end of the row for id 5.

### CODE REVIEW

**Comment by seamuslee001** [comment]
@demeritcowboy do we need to have an upgrade step associated with this?

**Comment by demeritcowboy** [comment]
Oh, yes you're right, if they haven't modified already. Will do.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 your comment has been addressed

**Comment by mattwire** [comment]
This looks fine - @demeritcowboy It would really make sense to try and make these actual messagetemplates at some point - would make management of them much simpler.

**Comment by eileenmcnaughton** [comment]
I think @michaelmcandrew tried to do that once.

**Comment by demeritcowboy** [comment]
Thanks!

**Pull request merged**
