### PR TITLE
Enforce standard line endings

### PR DESCRIPTION
**Pull request by colemanw**
See https://help.github.com/articles/dealing-with-line-endings/

### CODE REVIEW

**Comment by colemanw** [comment]
Yikes I just noticed the scary-looking warning in templates/CRM/Financial/ExportFormat/IIF.tpl saying not to change any invisible characters. Does anyone know if that applies to line-endings?

**Comment by kurund** [comment]
@colemanw this is kind of special file :)  Read: ***** IMPORTANT ************* note in the template

**Comment by kurund** [comment]
test this please

**Comment by colemanw** [comment]
Kurund yes I did read it, that's why I said "yikes" :)
But my specific question is, does it care about line endings? My guess is no, it seems to care more about tab characters. But i would be great to find out. How can we test it?
If that file can't have its line-endings changed then we won't be able to enforce this with a .gitattributes file.

**Comment by totten** [comment]
That file has a comment, "I'm wondering if it's better not to use smarty for this." ... +1

IIRC, Dave Dantowitz did a lot of work IIF a while back - might ping him.

**Comment by kurund** [comment]
@colemanw @totten That file is used to create IIF export file which is used for importing in QuickBooks.

**Comment by davecivicrm** [comment]
Coleman said ok to close, not critical to deal with now.

**Pull request closed without merging**
