### PR TITLE
dev/core#711 Add in upgrade step for removing Google+ from website ty…

### PR DESCRIPTION
**Pull request by seamuslee001**
…pe option value

Overview
----------------------------------------
Adds in an upgrade step to remove the Google+ option value for website_type_id field but only if there is no websites that have been assigned as google plus

Before
----------------------------------------
Google Plus option value in the database

After
----------------------------------------
Google Plus option value not in the database

ping @agileware-pengyi @eileenmcnaughton @totten

### CODE REVIEW

**Comment by yashodha** [comment]
@seamuslee001 this is upgrade for #16099

**Comment by seamuslee001** [comment]
correct @yashodha

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by demeritcowboy** [comment]
* General standards
    * [`r-explain`] __PASS__
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __PASS__
      * Tested upgrade with and without contacts that have a google+ website. As expected it leaves the option if you have contacts with a google+ website.
      * Also tested upgrade with the google+ option already disabled by an admin. Still works the same way.
      * Noting that if anyone's considering that the upgrade should disable the option instead of leaving it alone when there are existing contacts with a google+ website, then that would bring up that, um, "bug" where it would silently change the website type if you edit the contact later even just to change a phone or something.
* Developer standards
    * [`r-tech`] __PASS__
    * [`r-code`] __PASS__
    * [`r-maint`] __PASS__
    * [`r-test`] __PASS__

**Pull request merged**
