### PR TITLE
C51-384: Added case tokens on Email Activity Modal

### PR DESCRIPTION
**Pull request by deb1990**
Overview
----------------------------------------
As part of this PR, "Case" tokens has been added to the Email Activity Modal.

Before
----------------------------------------
before

After
----------------------------------------
after

Technical Details
----------------------------------------
In `CRM/Contact/Form/Task/Email.php`, added a block of code to add the Case Tokens when `caseId` is present.
The added code is similar to https://github.com/civicrm/civicrm-core/blob/b8ebe34c530297a2c8b6a7380ac204c6153ff74c/CRM/Contact/Form/Task/PDF.php#L124

### CODE REVIEW

**Comment by swastikpareek** [comment]
Looks good.

**Comment by shitijg** [comment]
passed internal Compucorp testing. 
Gitlab ref: https://lab.civicrm.org/dev/core/issues/668
@colemanw

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by colemanw** [comment]
* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __Pass__
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __Pass__: More consistent behavior between email and pdf screens.
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __Pass__ - I think this is self-explanatory and doesn't need user docs.
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __Pass__: Tested by @shitijg 
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __Pass__: Code matches existing code in the PDF system.
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __Pass__
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __Pass__
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __Pass__ - I think we can do without one here.

**Comment by colemanw** [comment]
Test fails unrelated.

**Pull request merged**
