### PR TITLE
Dont use do-not-reply@domain.org

### PR DESCRIPTION
**Pull request by BorislavZlatanov**
https://issues.civicrm.org/jira/browse/CRM-17753

### CODE REVIEW

**Comment by davecivicrm** [comment]
Jenkins, test this please.

**Comment by davecivicrm** [comment]
@BorislavZlatanov Thanks for working on this. A few comments:
- This type of change should go into master branch as it's non-critical.
- I don't know this code too well, BUT I thought that the Reply-to needs to carry the contact_id, hash etc. so that user can confirm subscription by replying to the confirmation request email. Like this:
Reply-To: c.202.1.c29ec6aec53230b6@civicrm.org
- I think changing the Return-path to use the specified default FROM email address makes sense.
- When you resubmit the pull request against master branch, you'll need to fix the 'style warnings' listed here: https://test.civicrm.org/job/CiviCRM-Core-PR/7194/checkstyleResult/new/
(You can download CiviCRM buildkit tools which include civilint - a tool that allows you to check your changes for style conformance before committing: https://github.com/civicrm/civicrm-buildkit/blob/master/README.md)

**Comment by BorislavZlatanov** [comment]
@davecivicrm Thanks for the comments.

Hmm, maybe you are right about the Reply-To: header. But how does the confirmation actually happen then? Is it processed when the bounces are processed?

P.S. I triple-checked to make sure there are no tabs or whitespace, yet here they are. Maybe the damn Windows playing tricks on me. Sigh...

**Comment by seamuslee001** [comment]
@BorislavZlatanov  I would check on CRM/Utils/Mail/EmailProcessor.php (file name not exact but location certainly). That handles all the processing of emails received into the bounce email address. That may also give you clues as to what is required.

**Comment by eileenmcnaughton** [comment]
I use phpstorm which helps me manage the whitespace issue amongst other things - it does have a cost :-( - but you can evaluate it for free and I think if you go on the Early Acceptance Programme you can keep getting their bleeding edge releases (I used to do that I think). Otherwise I think NetBeans is still free.

Should we close this PR since it seems we need a PR merged into master first?

The current status is that we are no longer merging from 4.6 to master so anything that is wanted in 4.6 needs to be in master first before it can be considered for 4.6.

Regarding: " Is it processed when the bounces are processed?" - the answer is yes. That is part of the information available to the bounce processor job.

**Comment by BorislavZlatanov** [comment]
Thanks for the info, guys. Sure, we can close this PR. I'm under tight time-constraints right now so I'm not able to open a new PR against master. If no one has done so, I'll open a new PR when I have more availability again.

**Comment by colemanw** [comment]
Yes please do.

**Pull request closed without merging**
