### PR TITLE
CRM-20243 Remove outdated sample jquery.min.js from phpword package

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @totten @xurizaemon

---

 * [CRM-20243](https://issues.civicrm.org/jira/browse/CRM-20243)

### CODE REVIEW

**Comment by totten** [comment]
This seems safe enough.

Would phpoffice work if we removed the entire folder `vendor/phpoffice/phpword/samples`? We've been burned by sample/demo scripts before, and it seems like good preventive measure.

**Comment by seamuslee001** [comment]
@totten not sure, i just aimed to hit the specific JS as that seemed the most of concern

**Comment by totten** [comment]
Reading the code in the `samples` folder, I'm pretty sure we can and should kill it.

**Comment by seamuslee001** [comment]
@totten i believe i have now updated it correctly to remove everything in the samples folder

**Comment by jackrabbithanna** [comment]
Is exception misspelled in this composer.json, or maybe the script file name itself "pear-execption" ?

**Comment by seamuslee001** [comment]
@jackrabbithanna in the script name should get fixed in https://github.com/civicrm/civicrm-core/pull/10384

**Comment by seamuslee001** [comment]
@totten i have rebased this now

**Pull request merged**
