### PR TITLE
Cleanup towards dev/core#2308

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Cleanup towards https://lab.civicrm.org/dev/core/-/issues/2308

Before
----------------------------------------
More confusing

After
----------------------------------------
Less confusing

Technical Details
----------------------------------------
@demeritcowboy I removed the thing in here causing tests to fail - this might be a reasonable compromise between been worth doing some testing on but not too insane to read

Comments
----------------------------------------

### CODE REVIEW

**Comment by demeritcowboy** [comment]
I started looking at this earlier and got sidetracked. I intend to review it.

**Comment by eileenmcnaughton** [comment]
Thanks @demeritcowboy - the goal of updating via import is a bit lower on my list now that I've discovered we can do what we wanted with search kit - but I still think this is pretty good clean up & I'll probably still chip away at it after this is merged

**Comment by demeritcowboy** [comment]
jenkins test this please

**Comment by demeritcowboy** [comment]
* General standards
    * [`r-explain`] __PASS__
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __PASS__
* Developer standards
    * [`r-tech`] __PASS__
    * [`r-code`] __PASS__
    * [`r-maint`] __PASS__
    * [`r-test`] __PASS__

**Comment by eileenmcnaughton** [comment]
Thanks @demeritcowboy

**Pull request merged**
