### PR TITLE
Allow text to be translated and fix URL paths in calls to docURL() function.

### PR DESCRIPTION
**Pull request by braders**
Overview
----------------------------------------
Primarially this ensures that the text passed to `docLink` can be translated (or word replaced). In a handful of cases I've also updated paths which were 404'ing to the appropriate locations.

Before
----------------------------------------
- Hardcoded text
- Some links to https://docs.civicrm.org 404'd

After
----------------------------------------
- Use of `{ts}` instead of hardcoded text
- Links don't 404

### CODE REVIEW

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by mlutfy** [comment]
Thanks @braders - seems like a good fix to me. This function has always been a bit problematic. I will leave open for others to review, because I keep forgetting some of the fine print about this function.

**Comment by seamuslee001** [comment]
jenkins, test this please

**Comment by totten** [comment]
Yeah, it's tricky to work with those functions, and I think this PR is doing it effectively.  For `r-run`, I spot-checked about ~2/3 of the changes (mostly in English; but also several in French), and all the links look good. Merging.

**Pull request merged**
