### PR TITLE
CRM-17846 - Fixing lock name to be less than 64 characters for MySQL 5.7 compatibility

### PR DESCRIPTION
**Pull request by andrewperry**
Backport for LTS

---
- [CRM-17846: Improving locks for CiviMail](https://issues.civicrm.org/jira/browse/CRM-17846)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Assuming this passes https://github.com/civicrm/civicrm-core/pull/8133
can you QA that you are happy with that alternate version and that it is missing any dumb errors? If so I will merge that one & can you please update this one.

Note that there will be an RC release available next week and it would be great if you could test that out - please make any notes about testing you do on the PR that we merge against master

**Comment by andrewperry** [comment]
Fixed in #8133

**Comment by eileenmcnaughton** [comment]
are you doing a replacement 4.6 one?

**Comment by andrewperry** [comment]
Ooops! Closed the wrong ticket.  Thanks @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
Odd - it's failing here - it looks the same as the 4.7 version

**Comment by andrewperry** [comment]
Yeah, I didn't have 4.6 running on my local dev so last night I though I would try using the modernised settings call in order to keep Lock.php in perfect sync with 4.7 but it was a step too far.  I just submitted the fix as you spoke!

**Comment by eileenmcnaughton** [comment]
:-)

I wish it would work. I sped up the tests soooo much

**Comment by andrewperry** [comment]
@eileenmcnaughton the config call change has done the trick so I think this is ready for merge too.  Thanks so much for your help squashing this one - there's some nice stuff in MySQL 5.7 that it's nice to be able to use in projects that share a DB server with Civi!

**Comment by eileenmcnaughton** [comment]
Ok - I'm good to merge this - it looks to be the same as the one merged to master

**Pull request merged**
