### PR TITLE
Add "phpstorm" extension

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

CiviCRM has several dynamic interfaces, such as the service-container, CRUD API, and hook system. PhpStorm is a common IDE that ordinarily presents options based on the static structure. This patch implements a process for [integrating some dynamic data](https://www.jetbrains.com/help/phpstorm/2021.3/ide-advanced-metadata.html) into PhpStorm.

Usage
----------------------------------------

Enable the extension:

```bash
cv en phpstorm
```

Whenever the container is rebuilt, this will create a file `[civicrm.files]/.phpstorm.meta.php`. As long as this folder is visible to PhpStorm, it should enable autocompletion for `Civi::service()`:

Screen Shot 2023-08-25 at 4 35 26 AM

Comments
----------------------------------------

This workflow ensures that the list is updated whenever you enable or disable an extension.

There are probably things that could benefit from this, such as `civicrm_api4()` or `addListener()`.

### CODE REVIEW

**Comment by mattwire** [comment]
@totten This is great! Will certainly help me with development. But do we really want this shipping with CiviCRM? It's a dev tool which has no use on a production system?

**Comment by colemanw** [comment]
> But do we really want this shipping with CiviCRM?

@mattwire it doesn't. :) Nothing in the `tools` directory goes into the tarball.

**Comment by highfalutin** [comment]
> Nothing in the `tools` directory goes into the tarball.

So if I want to use the extension in a non-`civibuild` site, I'd just put it in my normal extensions dir?

**Comment by colemanw** [comment]
@highfalutin yes you can download it from the `tools` dir and install like a normal extension.

**Pull request merged**
