### PR TITLE
[REF] Cleanup on import rows error

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
[REF] Cleanup on import rows error

Trying (and not yet succeeding) to replicate https://lab.civicrm.org/dev/core/-/issues/2566
I was able to step through & eliminate one more place where we call dao->query() instead
of CRM_Core_DAO::executeQuery

Before
----------------------------------------
 $db->query($query, $args);

After
----------------------------------------
CRM_Core_DAO::executeQuery

Technical Details
----------------------------------------
This is a pretty minor simplification but am looking for more help replicating https://lab.civicrm.org/dev/core/-/issues/2566 - which could be done in conjunction with an r-run on this

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@demeritcowboy @jitendrapurohit  - is this something either of you would review? It's a minor refactor I did while trying to replicate something else

**Comment by demeritcowboy** [comment]
* General standards
    * [`r-explain`] __PASS__
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __PASS__
      * Gave it a little run while trying to replicate the original lab issue, which I did - see lab.
* Developer standards
    * [`r-tech`] __PASS__
    * [`r-code`] __PASS__
      * It was there before but variables inserted into sql statements make me nervous, but I suppose it's limited here how they get their values.
      * For the message string, before the patch it might have inserted null, whereas now it would insert `''`. I don't think it makes a difference here though if it just gets output into a csv later.
    * [`r-maint`] __?__
    * [`r-test`] __PASS__

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Comment by eileenmcnaughton** [comment]
@demeritcowboy thanks - & I'm glad you managed to figure out / replicate the original issue - we might be able to resolve it now

**Pull request merged**
