### PR TITLE
Fix caching on campaign pseudoconstant

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fix caching on campaign pseudoconstant

Before
----------------------------------------
static

After
----------------------------------------
```Civi::statics```

Technical Details
----------------------------------------
tests like it better - pulled out of the token PRs

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton checkstyle failed, and not just because of the poor grammar in "isCampaignEnable"

**Comment by eileenmcnaughton** [comment]
@colemanw you can't mess with history

image

**Comment by eileenmcnaughton** [comment]
@colemanw passed now

**Comment by colemanw** [comment]
Sorry @eileenmcnaughton I just read this code and actually paid attention, and now it occurs to me to ask: "what could possibly be the benefit of caching the results of `in_array()`?" I can think of none. I think this whole function should be reduced to 1 line.

**Comment by eileenmcnaughton** [comment]
@colemanw I think you're right!

**Pull request merged**
