### PR TITLE
[REF] Cleanup MailingAB BAO

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Some code cleanup and modernization in the MailingAB BAO.

Before
----------------------------------------
Excess boilerplate code.

After
----------------------------------------
- Use writeRecord function instead of boilerplate.
- Use api defaults for domain_id instead of setting in BAO:
    - Used `_civicrm_api3_mailing_a_b_create_spec()` function to set domain_id in v3,
    - APIv4 `FieldDomainIdSpecProvider` will set it automatically based on the required property in the schema.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This removal of domain_id handling from the BAO would be an issue if anyone calls it directly - but I feel OK about that because this BAO was new well after the api was established as the supported way to interact

**Comment by colemanw** [comment]
> This removal of domain_id handling from the BAO would be an issue if anyone calls it directly - but I feel OK about that because this BAO was new well after the api was established as the supported way to interact

What made me feel ok about it was that the commit message for adding that BAO literally says "Add API support", so I don't think it was intended to serve any other purpose. Usage check turns up 0.

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
retest this please

**Pull request merged**
