### PR TITLE
Applies accessible accordion to SearchKit, adds fallbacks

### PR DESCRIPTION
**Pull request by vingle**
Overview
----------------------------------------
SearchKit builder screen uses two custom angular accordions - this replaces them with `<details><summary>`.

Before
----------------------------------------
Search Kit accordions not accessible/keyboard controllable.
image

After
----------------------------------------
They are.
image

Technical Details
----------------------------------------
This PR adds some css to stop Bootstrap3 from breaking details/summary, and adds some fallback styling on details/summary as while many modern CMS admin themes will make the summary bold, and change the cursor, older ones don't.

Technical Details
----------------------------------------
There is a small UI change as the accordion previously used fieldset/legend.

### CODE REVIEW

**Comment by ufundo** [comment]
Tested this. HTML markup looks good and keyboard focusing works nicely for me.

But I don't get the open/close icons on default theme. It looks like bootstrap3.css has a rule that is overriding the default  `display: list-item` on `summary` elements.

image

There seem to be quite a few extra commits as well, could it be rebased?

**Comment by ufundo** [comment]
Can see [this PR fixes it in Greenwich](https://github.com/civicrm/civicrm-core/pull/28448
) - but can we not do it below the theme css level? 

Something like this in civicrm.css? Bit hacky but it's bootstrap3's fault...
```
.crm-container #bootstrap-theme summary {
    display: list-item;
}
```

**Comment by colemanw** [comment]
retest this please

**Comment by vingle** [comment]
@artfulrobot - well he hasn't replied but didn't bring it up at the sprint - and the point he raises was discussed by Coleman and I - and I think this is the least worst way to go given the various dependencies.

That said, I have a new PR for civicrm.css almost ready around accordions, so maybe it makes sense to remove civicrm.css from this PR and make it just about SearchKit? And have a separate PR for the proposed change to civicrm.css so it's all together (and easier to test once / replicate in a theme)?

**Pull request merged**
