### PR TITLE
[REF] Move getCustomFieldTokens to the tokens class, annotate more deprecations

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Move getCustomFieldTokens to the tokens class, annotate more deprecations

This deprecates (quietly) another function on CRM_Utils_Token. It's a pretty small function -
the sort you'd just copy & paste if you wanted to use outside of core but
I didn't add noise. 

Before
----------------------------------------
`CRM_Utils_Token` being called for a 3 line function, only used in token classes, to get custom tokens

After
----------------------------------------
Duplicated onto the class, deprecated (still called from the `TokenTrait` but from a function that is itself a candidate for removal - once we've checked universe. The only class that uses the trait has good test cover)

Technical Details
----------------------------------------
The only core place that still calls this is the tokenTrait
- which is 'used' by activity tokens - and I haven't started to think about
whether that class actually needs the `_N_` handling that it uses the tokenTrait
to possibly support (my recollection is that functionality is not enabled)

Anyway - I'm leaving that question for later because I'm not sure if the token
trait is used outside of core or how our final interface will look

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Test fail due to 2 changes being recently merged - all tests failing

CRM_Member_Form_Task_PDFLetterTest::testMembershipTokenReplacementInPDF
Non-conformant hook_civicrm_alterMailParams(..., messageTemplate): Unrecognized keys: schema
Array

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
@eileenmcnaughton needs rebase

**Comment by eileenmcnaughton** [comment]
@colemanw rebased - although I think it might be in a race with https://github.com/civicrm/civicrm-core/pull/21713 to see which one makes the other stale :-)

**Comment by colemanw** [comment]
@eileenmcnaughton checkstyle strikes again

**Comment by eileenmcnaughton** [comment]
@colemanw hopefully this time!

**Comment by colemanw** [comment]
@eileenmcnaughton just a few failures...
```
Test Result (437 failures / +436)
```

**Comment by eileenmcnaughton** [comment]
@colemanw ug - would be easier if #21713  were merged  but will fix that up in this PR anyway

**Comment by eileenmcnaughton** [comment]
@colemanw ok should be easy now since only the trait class calls that function now

**Pull request merged**
