### PR TITLE
[REF] Extract duplicate handling code

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
[REF] Extract duplicate handling code

Before
----------------------------------------
Code in long function

After
----------------------------------------
Code in own function

Technical Details
----------------------------------------
This winds up being a very strange process - however the inital goal seems to be
to unravel error handling to appropriate exception throwing & catching
& a bit of back & forth helps us isolate the code places

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
looks like that fixed it

**Comment by seamuslee001** [comment]
@eileenmcnaughton test fails relate

```
CRM_Contact_Import_Parser_ContactTest.testImportParserWithUpdateWithoutExternalIdentifier
CRM_Contact_Import_Parser_ContactTest.testImportDeceased
CRM_Contact_Import_Parser_ContactTest.testImportFill
CRM_Contact_Import_Parser_ContactTest.testImportAmbiguousStateCountry
```

**Comment by eileenmcnaughton** [comment]
Hmm looks like I deleted a word during reformatting & hence broke it - I think it should be right now

**Comment by seamuslee001** [comment]
@eileenmcnaughton same 4 tests fail still

**Comment by eileenmcnaughton** [comment]
@seamuslee001 not quite ... we are back to the same 4 failing. That's an achievement :-)

Anyway my type was too strict so should be OK next time

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
fail seems odd

Stacktrace
CRM_Core_BAO_CustomFieldTest::testFileDisplayValueNoDescription
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'              <a href="/index.php?q=civicrm/file&amp;reset=1&amp;id=1&amp;eid=3&amp;fcs=2780969e0ba7f3bcb39c6f3f5bd76181fa342eba5f02025b81de1a5d14b1943e_1607068898_168" title="test_file.txt">\n
+'              <a href="/index.php?q=civicrm/file&amp;reset=1&amp;id=1&amp;eid=3&amp;fcs=2780969e0ba7f3bcb39c6f3f5bd76181fa342eba5f02025b81de1a5d14b1943e_1607068899_168" title="test_file.txt">\n
                 <i class="crm-i fa-paperclip" aria-hidden="true"></i>\n
               </a>'

/home/jenkins/bknix-dfl/build/core-19103-33p9p/web/sites/all/modules/civicrm/tests/phpunit/CRM/Core/BAO/CustomFieldTest.php:937
/home/jenkins/bknix-dfl/build/core-19103-33p9p/web/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:226
/home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar:615

**Comment by seamuslee001** [comment]
Looks good now

**Pull request merged**
