### PR TITLE
dev/core#183 CRM/Dedupe/BAO/QueryBuilder/IndividualUnsupervised.php report to using CRM_Utils…

### PR DESCRIPTION
**Pull request by seamuslee001**
…_SQL_TempTable

Overview
----------------------------------------
This converts temporary table syntax to using CRM_Utils_SQL_TempTable interface in CRM/Dedupe files

Before
----------------------------------------
Legacy format used

After
----------------------------------------
CRM_Utils_SQL_TempTable used

ping @eileenmcnaughton @totten @monishdeb

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Using $this when not in object context :-(

Screen Shot 2019-11-12 at 12 49 56 PM

**Comment by eileenmcnaughton** [comment]
@seamuslee001 the reason the above doesn't cause a test fail is it is never hit I believe - testBatchMergeEmailOnHold should otherwise fail

**Comment by eileenmcnaughton** [comment]
OK - the function comments re-inforce it not being called 

"An alternative version which might perform a lot better
   * than the above. Will need to do some testing"

And we can see the only place the class is called

Screen Shot 2019-11-12 at 12 56 45 PM

**Comment by seamuslee001** [comment]
@eileenmcnaughton ok pushed up to remove that function now

**Comment by eileenmcnaughton** [comment]
OK - trying to test to see if the other is hit https://github.com/civicrm/civicrm-core/pull/15827 -

**Comment by eileenmcnaughton** [comment]
Well that's bad news - the tests don't hit it. I'm good with the function removal but need to dig more on the other

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton now that we have merged #15849 are you good with this now?

**Comment by eileenmcnaughton** [comment]
Ok - merge on pass as the code now gets a test pass-through

**Comment by seamuslee001** [comment]
Test fail unrelated

**Comment by magnolia61** [comment]
I hit a fatal error with this PR applied.
Screenshot from 2019-12-28 10-10-57

```
    [code] => -5
    [message] => DB Error: already exists
    [mode] => 16
    [debug_info] => CREATE TEMPORARY TABLE `civicrm_tmp_e_dedupe_7f4acdb4ca55e07e7c552114c5a75b12` ENGINE=InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci AS SELECT * FROM civicrm_tmp_e_dedupe_ad86ee0bed80712470ca464e8d7108a4 WHERE weight >= 20 [nativecode=1050 ** Table 'civicrm_tmp_e_dedupe_7f4acdb4ca55e07e7c552114c5a75b12' already exists]
    [type] => DB_Error
    [user_info] => CREATE TEMPORARY TABLE `civicrm_tmp_e_dedupe_7f4acdb4ca55e07e7c552114c5a75b12` ENGINE=InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci AS SELECT * FROM civicrm_tmp_e_dedupe_ad86ee0bed80712470ca464e8d7108a4 WHERE weight >= 20 [nativecode=1050 ** Table 'civicrm_tmp_e_dedupe_7f4acdb4ca55e07e7c552114c5a75b12' already exists]
    [to_string] => [db_error: message="DB Error: already exists" code=-5 mode=callback callback=CRM_Core_Error::handle prefix="" info="CREATE TEMPORARY TABLE `civicrm_tmp_e_dedupe_7f4acdb4ca55e07e7c552114c5a75b12` ENGINE=InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci AS SELECT * FROM civicrm_tmp_e_dedupe_ad86ee0bed80712470ca464e8d7108a4 WHERE weight >= 20 [nativecode=1050 ** Table 'civicrm_tmp_e_dedupe_7f4acdb4ca55e07e7c552114c5a75b12' already exists]"]
```
)

**Comment by seamuslee001** [comment]
are there any other associated errors?

**Comment by magnolia61** [comment]
Screenshot from 2019-12-28 11-15-27
Screenshot from 2019-12-28 11-15-47

**Pull request merged**
