### PR TITLE
CRM-17917 Fix d8 install requirements

### PR DESCRIPTION
**Pull request by seamuslee001**
- [CRM-17917: Add support for Drupal 8](https://issues.civicrm.org/jira/browse/CRM-17917)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 my only hesitation merging this is the new variant gets priority over the previous - would only one of these be set at any point in time?

**Comment by seamuslee001** [comment]
@eileenmcnaughton I think so but this is basically a rebadged work of @totten Tim maybe able to shed more light here

**Comment by eileenmcnaughton** [comment]
confirmed with @totten the keys are mutually exclusive - merging

**Pull request merged**
