### PR TITLE
Update 4.7.alpha1.mysql.tpl

### PR DESCRIPTION
**Pull request by gah242s**
CRM-17136 Added Punjab Province for Pakistan

---
- [CRM-17136: Missing PK-PB Province](https://issues.civicrm.org/jira/browse/CRM-17136)

### CODE REVIEW

**Comment by kurund** [comment]
@gah242s looks like this PR has gone stale, can you please rebase or submit a new PR for the same

**Comment by monishdeb** [comment]
Closed in favor of https://github.com/civicrm/civicrm-core/pull/6682

**Comment by gah242s** [comment]
I've got to admit, I'm lost.  Looks like @monishdeb took care of this.  How did it go stale?  To rebase something looks like it requires some pretty intimate knowledge with the current base.   Oh well, I'll keep trying to help, just hope I'm not creating more work.

**Comment by kurund** [comment]
@gah242s  One of the reason for PR for being stale is someone else worked on the same code. So you have a merge conflict, hence you need to rebase or do another PR. @monishdeb took care of this. thanks for your patch.

**Pull request closed without merging**
