### PR TITLE
CRM-18559 sync functions from master which seem to resolve this in th…

### PR DESCRIPTION
**Pull request by seamuslee001**
…e same but more elegant way

### CODE REVIEW

**Comment by seamuslee001** [comment]
@davejenx @eileenmcnaughton This syncs up 4.6 to how master creates the subTypeClauses here, I think its more elegant / maintainable given it would match 4.7 code. Would appreciate some QA on this but I think its pretty good

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I agree with keeping in sync with master - I thought the 2 were closer than they are.

We should bring back the tests from master too.

NB tests have been failing all day a lot of the time - I think qa week is overloading jenkins

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
OK - I'm happy to merge this because I think sanity here relies on keeping 4.6 & master in sync - I'm pushing up the test variations

**Comment by seamuslee001** [comment]
Also i can't see other obvious deviations I think on the actual getTree code here. I think this explains why in Dave's summary, this was the only CRM that was 4.6 only and not 4.7 and 4.6

**Pull request merged**
