### PR TITLE
Bump minimum upgradable version to 4.7.32

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Removes old upgrade code, requires at least version `4.7.32` to upgrade to the latest version of CiviCRM in a single step (upgrading from older versions is still possible by breaking it into smaller steps, e.g. 4.5 -> 4.7, then 4.7 -> latest).

Before
----------------------------------------
Minimum upgradable version = 4.6

After
----------------------------------------
Minimum upgradable version = 4.7
CiviCRM is 12k sloc lighter!

Comments
----------------------------------------
The [last bump](https://github.com/civicrm/civicrm-core/pull/22238) was a year and a half ago, and there are practical reasons (like php and mysql version issues) that make it impossible to upgrade in huge leaps and bounds, so I don't think there's any good reason to keep this old upgrade code around.

### CODE REVIEW

**Comment by seamuslee001** [comment]
Test failures relate @colemanw but not quite as you would expect

**Comment by colemanw** [comment]
@seamuslee001 I think it's just the usual - we have to bump the upgrade tests like we did for #22238

**Comment by seamuslee001** [comment]
@colemanw 

This doesn't seem like the usual issue

```
In SettingsBag.php line 129:
                                                           
  [Error]                                                  
  Class "CRM_Upgrade_Incremental_php_FourSeven" not found  
                                                           

Exception trace:
  at /home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/Civi/Core/SettingsBag.php:129
 Civi\Core\SettingsBag->loadValues() at /home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/Civi/Core/SettingsManager.php:157
 Civi\Core\SettingsManager->getBagByDomain() at /home/homer/buildkit/build/build-0/web/sites/all/modules/civicrm/Civi.php:218
 ```

**Comment by totten** [comment]
@colemanw I definitely had the same thought a few weeks ago. So general 👍.

On details... the last of the `4.7.x` series was `4.7.31`; `4.7.32` was not a real release. This is based on `git tag`, `git ls-remote`, and [sf.net](https://sourceforge.net/projects/civicrm/files/civicrm-stable/). (*`4.7.32` must have been a momentary thing after `4.7.31` was locked-in but before we renamed things for `5.0`.*) 

In terms of suitability for downstream users, I don't think it really makes a difference if we put the boundary at `4.7.31` or `4.7.32` or `5.0.0`.

What it does influence is the scope of automated testing. (*This is where I noticed it.*) In the [DB snapshot list](https://github.com/civicrm/civicrm-upgrade-test/tree/master/databases), there are examples from `4.7.31` and `5.7.3`. My impression:

* With `MINIMUM_UPGRADABLE_VERSION` set to `4.7.32` or `5.0.0`, the oldest passable snapshot will be `5.7.3-setupsh.mysql.bz2`. (*This would not exercise `FiveZero`, `FiveOne`, `FiveTwo`, etc.*)
* With `MINIMUM_UPGRADABLE_VERSION` set to `4.7.31`, the oldest passable snapshot will be `4.7.31-setupsh.mysql.bz2`. (*This would exercise `FiveZero`, `FiveOne`, `FiveTwo`, etc. But you would need to restore the function `upgrade_4_7_32()`.*)

So if read correctly, your impulse was to allow upgrades from the last of 4.7.x, which is probably better, but it would need an update, no?

**Comment by totten** [comment]
With 355a0c3 and https://github.com/civicrm/civicrm-buildkit/commit/84c401e6a71cca7b31871179298b7e0da90c9726, it's pass now.

Merging.

**Comment by colemanw** [comment]
Thanks @totten I agree

**Pull request merged**
