### PR TITLE
dev/core#4097 Type fix for formatLocaleNumeric method

### PR DESCRIPTION
**Pull request by redcuillin**
Overview
----------------------------------------

CRM_Utils_Number::formatLocaleNumeric() method throws fatal error due to string paramater.

Before
----------------------------------------
Any call to CRM_Utils_Number::formatLocaleNumeric() fails with error: "Fatal error: Uncaught Error: NumberFormatter::format(): Argument #1 ($num) must be of type int|float, string given
in /path/to/civicrm/civicrm/CRM/Utils/Number.php on line 123"

After
----------------------------------------
Method returns correctly formatted $amount variable, as intended.

Technical Details
----------------------------------------
Added lines to test if string $amount can be converted to an int or float. Integer strings converted to proper ints, float strings to floats.

Comments
----------------------------------------
I wasn't able to find an existing built-in CiviCRM utility to parse strings to numeric values in this way, but it may exist, in which case it should probably be used instead.

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton @demeritcowboy thoughts?

**Comment by seamuslee001** [comment]
Jenkins ok to test

**Comment by demeritcowboy** [comment]
Hmm. @redcuillin What is your locale (default language) in civi and what do you have for decimal and thousands separators on the admin - localization page? I think what might be happening is the civireport is sending something like a european `12,34` value to the formatter.

**Comment by demeritcowboy** [comment]
Oh it's when you sort by a custom field and choose to have that field as section header - it's trying to format `12 (1)` or something like that.

**Comment by demeritcowboy** [comment]
Actually what it's trying to format is the empty string when it fails. Maybe either return early if the empty string, or don't even call it [here](https://github.com/civicrm/civicrm-core/blob/dc2db78f43990458b54eb75ced73b7ad794e6156/CRM/Report/Form.php#L2388) if `$val === ''`

**Comment by redcuillin** [comment]
@demeritcowboy. It seemed simpler than that to me, unless I'm missing something.

The parameter signature for CRM_Utils_Number::formatLocaleNumeric() is incompatible with the parameter signature for NumberFormatter::format().

In Number.php
```php
    public static function formatLocaleNumeric(string $amount, $locale = NULL): string { }
```

In NumberFormatter docs:
```php
    public function format(int|float $num, locale = NULL): string|false { }
```
Because $amount is required to be a string by the method signature, and Numberformatter::format will only accept and int or a float, whether it's an empty string, a numeric string or any other type of string, it's still going to cause a fatal error when it's passed to Numberformatter::format() isn't it?

FWIW when I echo out the values being passed to formatLocaleNumeric, they are all simple integers in string form. That seems to confirm to me that it's the string type that's the problem, not the $amount value itself.

**Comment by demeritcowboy** [comment]
You're right that there's a signature difference but php does this thing where it autoconverts if it can. You can see it with e.g.

`php -r '$formatter = new \NumberFormatter("en_US", NumberFormatter::DECIMAL); echo $formatter->format("12");'`

which happily outputs 12 even though it's given a string. But

`php -r '$formatter = new \NumberFormatter("en_US", NumberFormatter::DECIMAL); echo $formatter->format("");'`

gives the error you describe.

For debugging I used `\CRM_Core_Error::debug_log_message(var_export($val, TRUE));` and then looked in ConfigAndLog, and it indicated that the crash happened when it tried to format the empty string, and the only time I could reproduce it was when I sorted the civireport on the custom field and checked the box for section header (does that match your report settings?)

**Comment by redcuillin** [comment]
Ok, I follow. Yeah, I guess I thought the point of type hinting was to get away from the whole weakly typed thing, and forgot that what needed to be a strict type in one place would not be strict in another.

Yes, some custom fields had empty values that should not have been empty, and that was generating the error.
 I'm updating my PR with a simple early return if empty string encountered.

I considered making the change in [Form.php](https://github.com/civicrm/civicrm-core/blob/dc2db78f43990458b54eb75ced73b7ad794e6156/CRM/Report/Form.php#L2388) or [CustomField.php](https://github.com/redcuillin/civicrm-core/blob/cab24e487d59f70f6d87a5f2decfd91a8ac69558/CRM/Core/BAO/CustomField.php#L1282), but I'm not familiar enough with the code to want to mess with Form.php, and it seemed more useful to avoid the potential for others creating the same problem in the future. But YMMV.

**Comment by demeritcowboy** [comment]
Thanks. Yeah php is being a bit strange/inconsistent.
Are you able to [squash commits](https://docs.civicrm.org/dev/en/latest/tools/git/#rebasing-interactive)?

**Comment by redcuillin** [comment]
Have squashed commits.

**Comment by demeritcowboy** [comment]
Thanks but it seems to be including a whole bunch of files. Since the patch is so small, I'd try either `git reset --soft upstream/master`, where upstream is the real civi, then git commit. Or the same but with `--hard` instead of soft, which will wipe all changes but it's easy to redo your changes in this case.

**Comment by redcuillin** [comment]
Yeah, I messed up and unwisely pulled in upstream changes.
Will do-over.

**Comment by redcuillin** [comment]
Rather than unpicking whatever I did with the branch I used for the pull request, I'm going to close this PR and create the change in a fresh branch with a fresh PR.

**Pull request closed without merging**
