### PR TITLE
CRM-18362 get current local for navigation menu

### PR DESCRIPTION
**Pull request by sunilpawar**
- [CRM-18362: navigation menu is always displayed in English](https://issues.civicrm.org/jira/browse/CRM-18362)

### CODE REVIEW

**Comment by colemanw** [comment]
If you want, you could do additional cleanup for the sake of consistency, changing this line:
https://github.com/civicrm/civicrm-core/blob/4.7.5/CRM/Core/Resources.php#L606
and this one:
https://github.com/civicrm/civicrm-core/blob/4.7.5/CRM/Core/Resources.php#L756

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by jitendrapurohit** [comment]
@sunilpawar I get an error after applying this PR.

    Fatal error: Cannot redeclare CRM_Core_I18n::setLocale() in CRM/Core/I18n.php on line 686

This is when using CiviCRM language switcher to enable French from English.

**Comment by sunilpawar** [comment]
removed duplicate function, i also see existing CRM_Core_I18n::setLocale function not called from anywhere , converted that function to static.

**Comment by sunilpawar** [comment]
reverting last commit

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by JoeMurray** [comment]
Heh Sunil as Release Manager this month, I'm trying to recruit people to help pare down the backlog of almost 100 PRs, some going back to last summer. I'm wondering if you would be able to help QA another PR if I got someone to QA this PR?

**Comment by samuelsov** [comment]
This patch seems good but i will do some tests and ensure there is no regression.

**Comment by samuelsov** [comment]
I've seen no regression, please merge

**Pull request merged**
