### PR TITLE
EventTestTrait [WIP]

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This creates a new trait `\Civi\Test\EventTestTrait` that can be used from core tests and from extension tests - as such it needs to have a stable signature from close to when it is introduced (we could maybe have a release of wriggle room but after than we should not change it)

Before
----------------------------------------
Test set up for events is inconsistent in core and extensions & often is not fully valid

After
----------------------------------------
Trait can be included in tests called `\Civi\Test\EventTestTrait` and it provides the following (so far)

Functions
**Primary test functions**
- `createEventPaid()`
- `createEventUnpaid()` (@todo)
- `getEventID()`

**Secondary functions**
I haven't made these private as I think they should be pretty stable but they are primarily expected to be accessed through the primary functions
- `createEvent()`
- `getEventExampleData()`

The trait follows the convention from core tests of registering the ids created in the property `$ids`. It also registers the tables in the property `tablesToCleanUp` - while this might in practice be used as `tablesToTruncate` some of the tables should not be truncated (price set) so that seemed like the wrong name. It does not take responsibility for the clean up.

Note that the signature for the functions is a bit tricky to get right around how many parameters to accept. I settled on the idea that if tests wanted more consquential customisation that to specify eventParameters & priceSetParameters then the test should do that set up. So if the customisation of the priceSet goes beyond specifiying values like is_quick_config and min_fee and goes into option values then it should be handled outside of `createEventPaid`

Technical Details
----------------------------------------
Note that 

1) This still has a dependency on a function in `CiviUnitTestCase`
2) I'm expecting to add 

Comments
----------------------------------------
I think it would be good to merge https://github.com/civicrm/civicrm-core/pull/26294 & reduce the noise in this PR

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton this follows a slightly different MO than what I was going for with the generic `createTestRecord` and `saveTestRecords` functions, which have their own transaction-aware rollback mechanisms. I think your helper functions could build on those rather than handling the rollbacks in a different way. See:
https://github.com/civicrm/civicrm-core/blob/34f8db52805c365aecf60ce6435ca167c8a69a30/Civi/Test/Api4TestTrait.php#L30-L85

**Comment by eileenmcnaughton** [comment]
@colemanw yeah it's kind of a different purpose - in that I'm trying to create valid complex entities - so it's not just having all the required fields - it's having meaningful values in them & valid interrelationships between the entities - ie an event should have a price set, appropriate profiles, including for mutliple participants to be useful in tests beyond api-type tests.

The $ids pattern is pretty well established in the main test suites - but I could add to the testRecords too - the goal is to provide the data to support the test cleanup effort - not to determine how it would be done

**Comment by eileenmcnaughton** [comment]
[Test Result](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/2331/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/testReport/) (60 failures / ±0)
[api_v3_ContributionTest.testRepeatTransactionPassedInFinancialTypeTwoLineItems](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/2331/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/testReport/junit/(root)/api_v3_ContributionTest/testRepeatTransactionPassedInFinancialTypeTwoLineItems/)
[api_v3_ContributionTest.testCompleteTransactionWithParticipantRecord](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/2331/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/testReport/junit/(root)/api_v3_ContributionTest/testCompleteTransactionWithParticipantRecord/)
[api_v3_ContributionTest.testSendMailEvent](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/2331/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/testReport/junit/(root)/api_v3_ContributionTest/testSendMailEvent/)
[api_v3_EventTest.testDeleteWithExistingParticipant with data set "APIv3"](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/2331/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/testReport/junit/(root)/api_v3_EventTest/testDeleteWithExistingParticipant_with_data_set__APIv3_/)
[api_v3_EventTest.testDeleteWithExistingParticipant with data set "APIv4"](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/2331/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/testReport/junit/(root)/api_v3_EventTest/testDeleteWithExistingParticipant_with_data_set__APIv4_/)
[api_v3_JobTest.testTemplateRemindAdditionalContacts](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/2331/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/testReport/junit/(root)/api_v3_JobTest/testTemplateRemindAdditionalContacts/)
[api_v3_JobTest.testDeletedEventRemindAdditionalContacts](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/2331/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/testReport/junit/(root)/api_v3_JobTest/testDeletedEventRemindAdditionalContacts/)
[api_v3_OrderTest.testGetOrderParticipant](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/2331/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/testReport/junit/(root)/api_v3_OrderTest/testGetOrderParticipant/)
[api_v3_OrderTest.testAddOrderForParticipant](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/2331/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/testReport/junit/(root)/api_v3_OrderTest/testAddOrderForParticipant/)
[api_v3_ParticipantPaymentTest.testPaymentCreate](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/2331/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/testReport/junit/(root)/api_v3_ParticipantPaymentTest/testPaymentCreate/)
[Show all failed tests >>>](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/2331/BKPROF=dfl,SUITES=phpunit-api3,label=bknix-tmp/#showFailuresLink)

**Comment by colemanw** [comment]
@eileenmcnaughton `createTestRecord()` will only supply values for you if they are missing and required. So if your function is already supplying all required values with your preferred data, then you can just use `createTestRecord()` instead of `APIv4::create()` and it will work exactly the same, except it will also handle cleanup for you.

**Comment by eileenmcnaughton** [comment]
@colemanw - right & that is great if you are doing apiv4 style tests - but when working with an event you want a paid event with all that comes with that - which is a lot. You don't just want the required fields and you DO want all the fields to have internal integrity

**Comment by eileenmcnaughton** [comment]
@colemanw but I have updated so that the entities get recorded in https://github.com/civicrm/civicrm-core/pull/26348/files#diff-40e852becab8b08727c9e75cb29f19a6579d278c986ab619df4ce35fb7196126R99 so the cleanup CAN kick in if that is the method you are using to do cleanup

**Pull request closed without merging**
