### PR TITLE
CRM-16826: Fix updating addresses via Profiles

### PR DESCRIPTION
**Pull request by JKingsnorth**

### CODE REVIEW

**Comment by JKingsnorth** [comment]
I'm not sure if these failures are related, but I'll investigate after the weekend.

**Comment by davecivicrm** [comment]
John - pretty sure these are unrelated, but running tests again now.

**Comment by davecivicrm** [comment]
Jenkins test this please.

**Comment by JKingsnorth** [comment]
Looks good, thanks Dave.

**Comment by davecivicrm** [comment]
Recreated bug, applied patch, worked through the use cases listed and a few more (profile with multiple address location types, with one new location type, profile create).

**Pull request merged**
