### PR TITLE
CRM-20159 - Contact API - Refine & test return values

### PR DESCRIPTION
**Pull request by totten**
* [CRM-20159](https://issues.civicrm.org/jira/browse/CRM-20159)

### CODE REVIEW

**Review by seamuslee001 — APPROVED** [review]
I believe this is a sensible and has tests happy with it @eileenmcnaughton

**Comment by seamuslee001** [comment]
Test fail un related. Issue is an infrastructure issue which has been reported.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton what do you think of this, To me it makes sense

**Comment by eileenmcnaughton** [comment]
ok

**Pull request merged**
