### PR TITLE
dev/core#2814 Fix activity:sendEmail follow up

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Follow up fix on https://github.com/civicrm/civicrm-core/pull/21365

@demeritcowboy

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton any chance of expanding the test cover to prevent further regressions?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 Yeah - but probably not for a few days - I'd vote for merging this & then I'll try to add in when I revist to remove the calls to `removeCaseTokens` to avoid anyone getting confused

**Comment by seamuslee001** [comment]
using the test in #21386 I was able to verify this fixed the problem Dave D outlined

**Comment by eileenmcnaughton** [comment]
Thanks @seamuslee001 appreciate that - I hope to add more tests when I convert the case tokens - although we have to work through the date issue on that first but then

**Pull request merged**
