### PR TITLE
dev/core#4905 - Use cached getFieldObject instead of new customField

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Use already-loaded custom field info instead of refetching it from the database.

Part of https://lab.civicrm.org/dev/core/-/issues/4905

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw this one kinda hurt my brain a bit - I took a look at 1 of the 3 places changed & felt that switching to an array made more sense - ie https://github.com/civicrm/civicrm-core/pull/29108

**Comment by colemanw** [comment]
@eileenmcnaughton I've rebased this now with your changes. I still think it's good to merge & hopefully less brain-hurty now.

**Comment by eileenmcnaughton** [comment]
@colemanw I guess this is OK - but could we perhaps add a deprecation notice to the function & encourage use of the array instead - those use cases could easily switch to the array

**Comment by colemanw** [comment]
Ok @eileenmcnaughton I've added the deprecation notice to the function that returns an object in favor of the one that returns an array.
I imagine someone in the future will say "why the heck did they deprecate objects over arrays? Objects are way cooler!"

Answer: "*some* objects are cool. DAO objects are not."

**Comment by eileenmcnaughton** [comment]
@colemanw lol - it's kinda like the nerdy dad trying to be cool who doesn't realised he is just telling Dad jokes?

**Comment by colemanw** [comment]
Hey, I resemble that remark

**Pull request merged**
