### PR TITLE
CRM-20312 Fix typo

### PR DESCRIPTION
**Pull request by aydun**
* [CRM-20312: Identify and fix missing indexes](https://issues.civicrm.org/jira/browse/CRM-20312)

### CODE REVIEW

**Comment by aydun** [comment]
@eileenmcnaughton please merge

**Comment by eileenmcnaughton** [comment]
done! I couldn't see the problem at first :-)

**Comment by agh1** [comment]
@eileenmcnaughton should this be brought into 4.7.19-rc so it's in the same release as the typo it fixes?

**Comment by eileenmcnaughton** [comment]
probably - but it would be ok to pretend we never saw it....

**Comment by petednz** [comment]
I saw it

**Pull request merged**
