### PR TITLE
CRM-18284 -- Cannot create mailing labels from all found contacts if they are sorted

### PR DESCRIPTION
**Pull request by jitendrapurohit**
- [CRM-18284: Cannot create mailing labels from all found contacts if they are sorted](https://issues.civicrm.org/jira/browse/CRM-18284)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
What return properties are needed here? Can we add them more selectively? From memory the default is "I don't care how much I hammer your server" - which would be good to avoid

**Comment by eileenmcnaughton** [comment]
Ah I see - return properties is kind of a code for which tables to add into the FROM clause. I guess ideally we would add them to the FROM not the return properties....

**Comment by jitendrapurohit** [comment]
@eileenmcnaughton made the necessary changes. This is now added to FROM clause and task dropdown seems to work correctly.

**Comment by eileenmcnaughton** [comment]
Actually - we really should have a test on this - even though it's not the performance hit it was it's still adding joins in cases where they are not necessary and sooner or later someone will want to fix that & without tests it will regress again...

**Pull request merged**
