### PR TITLE
CRM-20760 - Can't add fee to an event or contribution page in update …

### PR DESCRIPTION
**Pull request by yashodha**
…mode.

### CODE REVIEW

**Comment by yashodha** [comment]
@jitendrapurohit can you please QA this.

**Comment by yashodha** [comment]
@seamuslee001 wanna look at this PR?
not sure why https://github.com/civicrm/civicrm-core/commit/1019b2fe8e5e506f34cf338d6e4e77f601b408c4#diff-03753662a69aab9f4543e6a8492d2e64R173 was added

**Comment by seamuslee001** [comment]
@yashodha Yash, that was added i think because of the situation where someone would try and re-enable a price field rather than a price option that used a disable FT so all that was passed through to the API call was is_active = 1 i think so no option values perse (this is from the action links menu iirc)

**Comment by seamuslee001** [comment]
@yashodha just confirmed that this reverts that check

To reproduce 1. Create a test financial type 2. Create price set with a text/html price field using the test financial type 3. Disable newly created price field 4. Disable test financial type 5. Enable price field note that it enables successfully with your patch, prior it does not enable and diplays message saying price field uses disabled FT or incorrect FT  @jitendrapurohit

**Comment by yashodha** [comment]
we can close this since it has been fixed under CRM-20805

**Pull request closed without merging**
