### PR TITLE
fix related to issue dev/core#127, in depth overlap of filter related contacts

### PR DESCRIPTION
**Pull request by hosseinzoda**
Overview
----------------------------------------
Hi Friends. I found another bug in my recent change.

This is about entering the same query but with different relationship type.
`$this->_displayRelationshipType`

Technical Details
----------------------------------------
These changes was my best understanding of how this function should behave.
Feel free to change it.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by hosseinamin** [comment]
I can't make sense out of these errors. Probably the error is related to authorize.net

**Comment by eileenmcnaughton** [comment]
Yes, these failures are unrelated

**Comment by eileenmcnaughton** [comment]
I put tried running this live & couldn't replicate the bug that this was trying to fix - although I thought maybe I saw it. But, this does fix the bug in the test context & adds a fix to lock it in so I think it's better that we merge it.

I couldn't get it to miscalcluate with this applied

**Pull request merged**
