### PR TITLE
CRM-16927 fix - Notice Search membership with custom fields

### PR DESCRIPTION
**Pull request by monishdeb**
https://issues.civicrm.org/jira/browse/CRM-16927

### CODE REVIEW

**Comment by kurund** [comment]
jenkins, test this please

**Comment by monishdeb** [comment]
jenkins, retest this please

**Comment by shawnholt** [comment]
this looks pretty stubstantial.  I noticed no change on Grant search form.  should this work for grants and other entities?

**Comment by shawnholt** [comment]
I can test if/when you add grants please.

**Comment by monishdeb** [comment]
@shawnholt I have updated the PR, please verify the patch if it works for you. Thanks

**Comment by shawnholt** [comment]
tried patch against 4.6.5 (not dev) but it applied fine.  didn't work for grants.
error message:
````
Warning: array_key_exists(): The first argument should be either a string or an integer in CRM_Utils_Array::value() (line 55 of /home/xxxxx/public_html/test/sites/all/modules/civicrm/CRM/Utils/Array.php).
Warning: array_key_exists(): The first argument should be either a string or an integer in CRM_Utils_Array::value() (line 55 of /home/xxxxx/public_html/test/sites/all/modules/civicrm/CRM/Utils/Array.php).
Notice: Array to string conversion in CRM_Core_BAO_CustomQuery->where() (line 416 of /home/xxxxx/public_html/test/sites/all/modules/civicrm/CRM/Core/BAO/CustomQuery.php).
Notice: Array to string conversion in CRM_Core_BAO_CustomQuery->where() (line 433 of /home/xxxxx/public_html/test/sites/all/modules/civicrm/CRM/Core/BAO/CustomQuery.php).
Warning: array_key_exists(): The first argument should be either a string or an integer in CRM_Utils_Array::value() (line 55 of /home/xxxxx/public_html/test/sites/all/modules/civicrm/CRM/Utils/Array.php).
Warning: array_key_exists(): The first argument should be either a string or an integer in CRM_Utils_Array::value() (line 55 of /home/xxxxx/public_html/test/sites/all/modules/civicrm/CRM/Utils/Array.php).
Notice: Array to string conversion in CRM_Core_BAO_CustomQuery->where() (line 416 of /home/xxxxx/public_html/test/sites/all/modules/civicrm/CRM/Core/BAO/CustomQuery.php).
Notice: Array to string conversion in CRM_Core_BAO_CustomQuery->where() (line 433 of /home/xxxxx/public_html/test/sites/all/modules/civicrm/CRM/Core/BAO/CustomQuery.php).

**Comment by monishdeb** [comment]
Strange. I tried to replicate the same with Grant checkbox custom fields but with no success. Please check the screenshot http://snag.gy/XEafN.jpg . Anyways I am merging my PR and the changes will reflect in 46 demo tomorrow. Let's see if the notice/bug are still there on demo site.

**Pull request merged**
