### PR TITLE
APIv4 - Add Contact.age_years extra field to make age calculations easy

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds a calculated field to APIv4 which makes it simple to return or filter on a contact's age.

image

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I'm gonna have a crack at making this available as a token if I can work through the preliminaries to this

**Comment by colemanw** [comment]
It should be easy enough to make it a token, as far as APIv4 is concerned it's a real field now.

**Comment by eileenmcnaughton** [comment]
cool - I'm just working on getting contact tokens over to apiv3

**Comment by eileenmcnaughton** [comment]
Works a treat

**Pull request merged**
