### PR TITLE
CRM-21365 Fix Currency

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Improve handling of currency

Comments
----------------------------------------
This is proposed as an alternative to #11210 and #11325

---

 * [CRM-21365: Currency code not passed to processor \(PayPal - Website Payments Pro\)](https://issues.civicrm.org/jira/browse/CRM-21365)

### CODE REVIEW

**Comment by mattwire** [comment]
@eileenmcnaughton Yes, this is a better "fix".  Does the getCurrency function have to be in CRM_Core_Form though?  It couldn't go somewhere like CRM_Utils_Money or something?

**Comment by eileenmcnaughton** [comment]
I think it's appropriate to the form class because it's about how the form holds that information.

**Comment by colemanw** [comment]
Yes to form class but I agree CRM_Core_Form is not a great place for something this specific. What about putting it in  CRM_Core_Payment_ProcessorForm.

**Comment by eileenmcnaughton** [comment]
The forms we care about (event forms, contribution pages) don't inherit from that class. (I did suggest about 3 years ago creating a current parent but that was not taken up then & we now have a bunch of functions in that top level form class that are there so those 2 form-sets can inherit from them.)

Once 5.3 is gone we can look at moving all those functions (there are maybe half a dozen) into a trait class.

**Comment by mattwire** [comment]
@eileenmcnaughton I'm happy with your explanation for location of that function :-)

**Comment by colemanw** [comment]
Sorry I still don't get it. This diff looks to me like it would produce a fatal error. Because you're adding a function to `CRM_Core_Form` but calling it from `CRM_Core_Payment_ProcessorForm` which does not extend `CRM_Core_Form` so wouldn't that crash?

**Comment by eileenmcnaughton** [comment]
In that function we call $form->getCurrency();

$form will be an instance of 

   * @param CRM_Contribute_Form_Contribution_Main|CRM_Event_Form_Registration_Register|CRM_Financial_Form_Payment $form

**Comment by colemanw** [comment]
Ah, I get it now. Thanks @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
@GinkgoFJG can you confirm this works for your bug (looking for the pr now)

**Pull request merged**
