### PR TITLE
dev/financial#6 Update the recurring contribution when we edit the template contribution

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
https://lab.civicrm.org/dev/financial/-/issues/6

When we update a template contribution we are specifying what the *next* contribution should be. As the recurring contribution represents the "contract" or "subscription" we need to update the amount to match the new amount on the template.

The "amount" field on the recurring contribution should probably (eventually) be deprecated because it's duplicating information we already have elsewhere in more detail.

As the template contribution is used to configure the next payment the recurring contribution should match that expectation.

If we can update the amount via the template contribution we disable updating via the "Edit recurring contribution" form because it will be updated automatically in the other direction.

Before
----------------------------------------
Recurring contribution amount not update to match template.

After
----------------------------------------
Recurring contribution amount updated to match template.

Captura de ecrã de 2021-09-14 16-49-17

Technical Details
----------------------------------------
This is implemented using the "new" hook style interface that @colemanw added recently. If a template contribution is updated the associated recurring contribution is updated to match the new amount/currency.

Comments
----------------------------------------
@jaapjansma

### CODE REVIEW

**Comment by colemanw** [comment]
Hook code looks right to me, someone needs to review the functionality. A unit test would be really, really good to include with a PR like this.

**Comment by mattwire** [comment]
@colemanw Thanks! Yes I will get a test sorted for this one but wanted to get a bit of review first to make sure it was the right approach :-)

**Comment by mattwire** [comment]
```
CRM_Contribute_Form_UpdateSubscriptionTest.testMail
api_v3_ContributionPageTest.testSubmitPledgePaymentPaymentProcessorRecurFuturePayment
api_v3_ContributionPageTest.testSubmitPledgePayment
```

**Comment by mattwire** [comment]
test this please

**Comment by mattwire** [comment]
test this please

**Comment by jaapjansma** [comment]
test this please

**Comment by BettyDolfing** [comment]
test this please

**Comment by jaapjansma** [comment]
@mattwire I tried to test this and I get a warning when editing the template contribution and changing the amount, see screenshot:

Screenshot_20220314_110649

I believe that updating the amount on the template is a separate issue from this PR, see this PR: #21471 for a fix. 

* General standards
    * Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
        * __PASS__ : The goal/problem/solution have been adequately explained in the PR.
    * User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
        * __PASS__: The change would be intuitive or unnoticeable for a majority of users who work with this feature.
    * Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
        * __PASS__: The changes do not require documentation.
        * __COMMENTS__: In the long run we might want to update the documentation to explain the idea of a template contribution. But that is not related to this PR. 
    * Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
        * __PASS__: We created a new recurring contribution, checked the template, checked the edit recurring. And then updated the total amount of the template through the API explore (because of the warning above which is fixed in this PR: #21471). And then we checked everything again.
* Developer standards
    * Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
        * __PASS__: The change preserves compatibility with existing callers/code/downstream.
    * Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
        * __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
    * Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
        * __PASS__: The change sufficiently improves test coverage, or the change is trivial enough that it does not require tests.
    * Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
        * __PASS__: The test results are all-clear.

@eileenmcnaughton or @colemanw can one of you merge this PR?

**Comment by adixon** [comment]
This needs more testing to make sure it also works with the line item editor, since that will be required on any recurring contribution with line items that you want to update. My initial testing suggests it doesn't work, but I'm confused enough that I'm no longer certain of anything.

Specifically - the line item editor is doing a save on a contribution BAO object, which I would assume would trigger the edit event on the contribution object that this PR is now paying attention to, but there's a whole whack of assumptions that are unclear from my understanding or the available documentation ...

**Comment by eileenmcnaughton** [comment]
As an aside - I think we should bring the line item editor into core & make it a standard part of the contribution form at some point - but I've thought that for a couple of years now & haven't done anything

**Pull request merged**
