### PR TITLE
Add participant tokens to pdf task

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Add participant tokens to pdf task

Before
----------------------------------------
Only contact tokens available in pdf letter task

After
----------------------------------------
contact, domain, participant tokens available

Technical Details
----------------------------------------
I've got this working - but I'm gonna try to break it down a bit into some more PRs just to convince myself all the parts are correct. 

Comments
----------------------------------------
@demeritcowboy this is on the pdf side - but the email side would wind up similar with the only difference being that I think on the email side we would have to check for enitty -specific tokens & if none then group by the contact id - ie  2 emails for a 2 contributions doesn't make sense if all the fields are identical.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Fatal error: Cannot make non static method CRM_Core_Form_Task::getContactIds() static in class CRM_Contact_Form_Task in /home/jenkins/bknix-dfl/build/core-21695-3no2/web/sites/all/modules/civicrm/CRM/Contact/Form/Task.php on line 21

**Comment by colemanw** [comment]
@eileenmcnaughton needs rebase

**Comment by eileenmcnaughton** [comment]
@colemanw done - fyi   https://github.com/civicrm/civicrm-core/pull/21696 is a sub-pr of this

**Comment by eileenmcnaughton** [comment]
This PR is the last in the 'pdf tokens' strand of work - looking for someone to test so we can get it merged - maybe @magnolia61 ?

**Comment by magnolia61** [comment]
I am glad to try and get this one tested as well.

Probably the cause is in my setup somewhere but I get 
`Fatal error: Allowed memory size of 536870912 bytes exhausted `
I'll continue to test and keep you posted here.

**Comment by magnolia61** [comment]
image

**Comment by magnolia61** [comment]
Result with pdf print/merge:
afbeelding

Same template but using scheduled reminders:
afbeelding

**Comment by eileenmcnaughton** [comment]
@magnolia61 that's not good - can you past your message template text in here & I'll try it too

**Comment by magnolia61** [comment]
```
<h2><strong>PARTICIPANT CORE</strong></h2>

<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse: collapse; width: 100%;">
	<tbody>
		<tr>
			<td width="30%">Participant Rol</td>
			<td width="30%">participant.role : label</td>
			<td width="30%">{participant.role_id:label}</td>
		</tr>
		<tr>
			<td width="30%"> </td>
			<td width="30%">participant.role : name</td>
			<td width="30%">{participant.role_id:name}</td>
		</tr>
		<tr>
			<td width="30%">Participant Status</td>
			<td width="30%">participant.status : label</td>
			<td width="30%">{participant.status_id:label}</td>
		</tr>
		<tr>
			<td width="30%"> </td>
			<td width="30%">participant.status : name</td>
			<td width="30%">{participant.status_id:name}</td>
		</tr>
		<tr>
			<td width="30%">Participant Register Date</td>
			<td width="30%">participant.register_date</td>
			<td width="30%">{participant.register_date}</td>
		</tr>
		<tr>
			<td width="30%"> </td>
			<td width="30%">participant.register_date short</td>
			<td width="30%">{participant.register_date|crmDate:"shortdate"}</td>
		</tr>
		<tr>
			<td width="30%">Participant Wachtijst</td>
			<td width="30%">participant.must_wait</td>
			<td width="30%">{participant.must_wait}</td>
		</tr>
		<tr>
			<td width="30%">Participant Is_Paylater</td>
			<td width="30%">participant.is_pay_later</td>
			<td width="30%">{participant.is_pay_later}</td>
		</tr>
		<tr>
			<td width="30%">Participant ID</td>
			<td width="30%">participant.participant_id</td>
			<td width="30%">{participant.id}</td>
		</tr>
		<tr>
			<td width="30%">Participant Source</td>
			<td width="30%">participant.source</td>
			<td width="30%">{participant.source}</td>
		</tr>
		<tr>
			<td width="30%">Participant Is Test</td>
			<td width="30%">participant.is_test:label</td>
			<td width="30%">{participant.is_test:label}</td>
		</tr>
		<tr>
			<td width="30%"> </td>
			<td width="30%"> </td>
			<td width="30%"> </td>
		</tr>
	</tbody>
</table>

```

**Comment by magnolia61** [comment]
> 
> 
> I am glad to try and get this one tested as well.
> 
> Probably the cause is in my setup somewhere but I get `Fatal error: Allowed memory size of 536870912 bytes exhausted ` I'll continue to test and keep you posted here.

This error only happens when I include the `{participant.balance}` token

**Comment by magnolia61** [comment]
Same for event core tokens:
afbeelding

**Comment by eileenmcnaughton** [comment]
@magnolia61 - I'll have to recheck this -will try to put something up after dinner

**Comment by eileenmcnaughton** [comment]
@magnolia61 I think I found it

**Comment by magnolia61** [comment]
For the participant core tokens your latest changes work!
afbeelding
and also for participant custom tokens:
afbeelding

the event tokens remain empty though

**Comment by eileenmcnaughton** [comment]
@magnolia61 I think that last update might fix the event tokens

**Comment by magnolia61** [comment]
> 
> 
> @magnolia61 I think that last update might fix the event tokens

They still render empty with me...

**Comment by eileenmcnaughton** [comment]
@magnolia61 looks like I had a change locally that I thought was extraneous - but wasn't - just pushed it in

**Comment by magnolia61** [comment]
Bingo! that was it. Now also rendering event core and custom tokens

(only issue now is the empty custom date field anomaly listed here: https://lab.civicrm.org/dev/core/-/issues/2891 but that is not pdf creation specific)

**Comment by eileenmcnaughton** [comment]
Thanks @magnolia61  - hopefully if tests pass this time this will be mergeable (@colemanw )

**Comment by eileenmcnaughton** [comment]
@magnolia61 I think I found the fix for your date token issue - I've pushed a fix in + a test (cross fingers this doesn't send me down another round of test-whackamole :-)

**Comment by magnolia61** [comment]
> 
> 
> @magnolia61 I think I found the fix for your date token issue - I've pushed a fix in + a test (cross fingers this doesn't send me down another round of test-whackamole :-)

You did it. Empty custom date fields do not mess up the other tokens anymore

**Comment by eileenmcnaughton** [comment]
@magnolia61 Yay - depending how this goes with getting merged & the other ones on the path (#21706 #21705 & #21688 & #21676) I might have a go at squeezing in participant tokens for email before the rc is cut - there is a bit of a gotcha there though https://lab.civicrm.org/dev/core/-/issues/2862

**Comment by magnolia61** [comment]
Test passed ✅

**Comment by colemanw** [comment]
Merging based on review from @magnolia61

**Comment by eileenmcnaughton** [comment]
yay - thanks for your work on this @magnolia61

**Pull request merged**
