### PR TITLE
4.6

### PR DESCRIPTION
**Pull request by sujit-baniya**
CRM-17571 Bug Fix - Cannot search for Activity type and status in Search Builder (it translates values incorrectly)

---
- [CRM-17571: Cannot search for Activity type and status in Search Builder (it translates values incorrectly)](https://issues.civicrm.org/jira/browse/CRM-17571)

### CODE REVIEW

**Comment by colemanw** [comment]
PR submitted to wrong branch.

**Comment by itsursujit** [comment]
In which branch should I make PR?

**Comment by colemanw** [comment]
If you scroll up on this page you'll see 173 commits - that's wrong, there should only be one (or however many you made for this fix). The problem is that you made the change in your `4.6` branch and are trying to merge it into our `master` branch. Git then thinks you are trying to merge *everything* from CiviCRM 4.6 into master.
If you want to submit the PR to the master branch, make the changes based on master, not 4.6.

**Comment by itsursujit** [comment]
Sir,
Actually I'm new to github on how to make PR. I'm currently having the CiviCRM version: 4.6.13. Under 4.6 Branch I could not see the Pull Request Option. Should I submit to master or 4.6?

Kind Regards

**Comment by colemanw** [comment]
I posted instructions at https://issues.civicrm.org/jira/browse/CRM-17571?focusedCommentId=85631&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-85631

**Pull request closed without merging**
