### PR TITLE
Remove unneeded use of CRM_Core_DAO::$_nullArray in executeQuery or s…

### PR DESCRIPTION
**Pull request by seamuslee001**
…imilar calls

Overview
----------------------------------------
title says it all and why was this like it in the first place? 

ping @eileenmcnaughton @monishdeb @mattwire

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
> why was this like it in the first place?

Allow me to demonstrate...
 COPY. :scissors: PASTE. :recycle: REPEAT

> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?
> why was this like it in the first place?

**Comment by eileenmcnaughton** [comment]
@mattwire - ^^ the technical explanation of the problem...

**Comment by eileenmcnaughton** [comment]
Actually there is another technical detail. On an unknown but now truly outdated version of php it was not possible to have a default parameter on variables passed by reference. They concurrently believed that passing by reference was more performant (@tttp debunked that around 2010)

**Comment by tttp** [comment]
Thanks  @seamuslee001! 

duh, not a bug per se, but it sure lasted a fair bit longer than needed ;)

**Pull request merged**
