### PR TITLE
CRM-21842 - Fix links to documentation

### PR DESCRIPTION
**Pull request by MegaphoneJon**
Overview
----------------------------------------
This fixes broken links to the documentation.

Before
----------------------------------------
Links to: https://docs.civicrm.org/user/en/stable/initial-set-up/installation-and-basic-setup

After
----------------------------------------
Links to: https://docs.civicrm.org/user/en/stable/initial-set-up/installation-and-basic-set-up

---

 * [CRM-21842: broken link](https://issues.civicrm.org/jira/browse/CRM-21842)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
I gave this merge on pass as I think this is trivial enough not to need any further checks

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by eileenmcnaughton** [comment]
I'm pretty comfortable the test fail is an intermittant test fail related to Authorize.net, merging

**Pull request merged**
