### PR TITLE
CRM-21528 fix add2Group

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fix fatal error on add2Group, tidy up report

Before
----------------------------------------
Fatal

After
----------------------------------------
no fatal

---

 * [CRM-21528: top donor report: add2group error](https://issues.civicrm.org/jira/browse/CRM-21528)

### CODE REVIEW

**Comment by lcdservices** [comment]
tested and confirmed that we can now add contacts to a group and the report is generating expected results.

**Comment by eileenmcnaughton** [comment]
unrelated test fail

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
I note that this has now been tested by Brian. I haven't tested the code but the code changes look sensible to me

**Comment by eileenmcnaughton** [comment]
@yashodha you should probably decide re merging on this one

**Comment by colemanw** [comment]
Merging based on testing and reviews. Code looks good to me as well.

**Comment by yashodha** [comment]
@eileenmcnaughton Top Donor Report is throwing a DB error on running
Check here
http://dmaster.demo.civicrm.org/civicrm/report/instance/14

**Pull request merged**
