### PR TITLE
CRM-20490 Navigation: add utility for adding menu items

### PR DESCRIPTION
**Pull request by agh1**
* [CRM-20490: Allow extension developers to easily add nav menu items](https://issues.civicrm.org/jira/browse/CRM-20490)

### CODE REVIEW

**Comment by seanmadsen** [comment]
@agh1 this looks cool! I'd like to try it out. 

How would you feel about making a PR on the Dev Guide with some documentation about how to use this new utility? (We could keep the Dev Guide PR un-merged until this core PR is merged.) Then I could read that documentation, try out this new utility &mdash; and in doing so, give both the docs and the utility a good test/review.

**Comment by agh1** [comment]
@seanmadsen Basically, the dev documentation change would be to modify [hook_civicrm_navigationMenu](https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_navigationMenu/) to add a sentence about this and replace the examples with the code in the header here.  Happy to do so, but I want to wait in case folks think this class should have a different name or usage.

**Comment by totten** [comment]
I was trying to think about what notes to capture from our Mattermost conversation. Some highlights were:

 1. Proposed: Only make one instance of this helper class (to avoid rescanning). Expose it via a different hook (a little later). Enable new methods/refactoring of the helper class in the future.
 2. Proposed: Add a hook earlier in the process -- just after reading the DB. This basically lets you define a couple pseudo-records in `civicrm_navigation` (although you'd also need a pseudo-field for declaring `parent` without ID#s.)
 3. Proposed: Buffer/enqueue the list of insertions so that they can be processed *after* the hook finishes.

Thinking about this a bit more... I think we really need some form of buffering/enqueueing (in addition to 1 or 2). Both the status-quo and #10265 have a problem which is currently asymptomatic. The problem scenario:

> Extension A (eg "SuperDuper Contribution Reports") inserts a subitem under Extension B's menu (eg "SuperDuper Reporting"), but this will only work if Extension B's menu is assimilated first.

It's asymptomatic because most of the nav elements have been in core -- pretty much all extensions are tapping into core menus. But it'll become more of an issue as features move into extensions

A quickfix is for Extension A to use Symfony-style hook registration and set a later priority.

A better fix is to buffer the additions and resolve ID#s after all menu items are defined. (Then it doesn't matter what order the hook-listeners execute.)

**Comment by mlutfy** [comment]
If anyone works on Extension menu items, please add a parameter to specify the full key of the extension (org.civicrm.example). This will be required to eventually translate menu items added by extensions.

**Comment by eileenmcnaughton** [comment]
@agh1 @totten what is the status here - is this irrevocably stalled ? stalled but will work on it someday (in which case close + re-open is good since it's tracked through JIRA) or not really blocked just not processed

**Comment by eileenmcnaughton** [comment]
I clarified this with @totten & he said status was that this needs changes per his feedback - I'm going to close it & you can re-open @agh1 once those things are addressed (hopefully at that point it will spring back to the top of the queue rather than languishing down here)

**Pull request closed without merging**
