### PR TITLE
CRM-19675 Add relative date range option

### PR DESCRIPTION
**Pull request by konadave**
* [CRM-19675: Add relative date range option](https://issues.civicrm.org/jira/browse/CRM-19675)

### CODE REVIEW

**Comment by monishdeb** [comment]
That's a great improvement but I am not sure how this will work in these use-cases : 
1. If user chose From - previous year/To - This year will it work ? Because internally EACH relative value is translated into BETWEEN clause like ```previous.year``` is translated into 
``` BETWEEN => array('1st Jan 2015', '31st Dec 2015')``` and ```this.year``` as ```BETWEEN => array('1st Jan 2016', '31st Dec 2016')```. So am not sure how this relative date range actual WHERE clause will turn out to be. 
2. What are the available relative values user should fill ? ```this.year``` or ```This calendar year```
3. There is no validation to put a check on the relative date range from/to values respectively. 

@eileenmcnaughton your thought on this ?

**Comment by konadave** [comment]
1. The entered From and To values do not go through the same processing as the other relative terms. They are processed just like Choose Date Range.
2. Anything you can throw at PHP strtotime() function.
3. If the user creates a date range where To is before From then they will get no result.

**Comment by monishdeb** [comment]
Ahh ok, got it. As per strtotime() identifiers I used (Contribution recieve date between 'yesterday' and 'today')
image

But I get all CiviCRM contributions, seems like there is no affect on the result set also there is no Qill message for it. 
image

**Comment by konadave** [comment]
Here's what I get.

screen shot 2016-11-28 at 8 54 14 am

Then I change the date of one contribution and get this.

screen shot 2016-11-28 at 8 57 58 am

I notice in your results screenshot that it doesn't indicate the search criteria like it does in mine.

**Comment by eileenmcnaughton** [comment]
Hmm - so this means instead of searching for 'last day' you can add a strtotime friendly string?

Note that in 4.6 or 4.7  it is already possible to add your own option values to the 'last week', 'last year', 'last 3 years' list.  

@agh1 @colemanw do you have any opinion on this from a UI point of view?

From a technical point of view this appears to be happening very much at the form layer - which is good - with the data converted well before it hits the BAO.

**Comment by PalanteJon** [comment]
> Note that in 4.6 or 4.7 it is already possible to add your own option values to the 'last week', 'last year', 'last 3 years' list.

Not 100% true.  There was work underway to support this, which stalled.  What DID happen is that the existing options, which were previously hard-coded in PHP, were moved into the database (in an OptionGroup).  However, the BAO isn't equipped to handle strings other than the ones that currently exist.  The only real advantage at this time is the ability to easily disable/reorder the existing options.

**Comment by mlutfy** [comment]
I'm not sure I'm very comfortable with the impact for non-English speakers.

> "strtotime — Parse about any English textual datetime description into a Unix timestamp"

Unrelated, but for reference, this is the 4.6 PR, which I will close until this PR is resolved: https://github.com/civicrm/civicrm-core/pull/9423

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @colemanw - it would be nice to figure out what to do with this - it's pretty old & has not progressed (& I think @konadave  no longer has an interest?)

It's potentially a nice (possibly obscure) change but there are 2 possible technical issues
1) it doesn't work well for non-English speakers
2) looks like it uses jcalendar - which assumes the fields are still , or will continue to be , non datepicker fields. 

I suspect that we would need to ensure those fields are migrated to datepicker & it works with that - so there is some work possibly. Also, I don't normally merge search changes without a test - but this is mitigated by the fact it's handled at the form layer. (how would that interact with smart groups?)

My personal belief is that if it's not clear there is a short-term path to progress an old ticket it's better to track through JIRA than the review q.

**Pull request closed without merging**
