### PR TITLE
dev/core#297 : fix broken permission 'access my cases and activities'

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
See https://civicrm.stackexchange.com/questions/25950/problem-with-civicase This regression is caused by CRM-21461 changes.

Before
----------------------------------------
The permission 'access my cases and activities' was broken.

After
----------------------------------------
The permission 'access my cases and activities' was fixed.

---

 * [CRM-21461: Case Dashlet enhancement](https://issues.civicrm.org/jira/browse/CRM-21461)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
Test fail seems unrelated @colemanw thoughts?

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
I agree with this fix. I think since this is a regression we should merge it into the RC branch.

**Comment by eileenmcnaughton** [comment]
@colemanw it looks like it regressed in 4.7.31 - which is long enough ago it's not an automatic for the rc, although it looks pretty safe so I think if you are confident then delivering the fix sooner rather than later makes sense

**Comment by colemanw** [comment]
Yes I give this fix my official seal of approval.
Actually, there's no `:seal:` emoji, so I guess I'll have to give it a goat of approval: :goat:

**Comment by MegaphoneJon** [comment]
Just flagging this as open despite Coleman's goat of approval.

**Comment by petednz** [comment]
was this in 5.6.1? https://civicrm.stackexchange.com/questions/27218/civicase-access-all-cases-and-activities-issues

**Comment by eileenmcnaughton** [comment]
was it backported?

**Comment by Myrddinwylit** [comment]
I don’t know what that means to be backported? I have a test site setup using the bitnami VirtualBox build - with civicrm 5.6.1 
And I am getting the “too many redirects” on any account that doesn’t have “views all cases” permission checked when I try to access the case dashboard or case management. I can however get to create new case.

**Comment by Myrddinwylit** [comment]
Ok after some late night playing around it seems the issue is not this fix, but something going wrong with the [Civicase Extenstion](https://github.com/civicrm/org.civicrm.civicase) When I disabled this extension everything worked as it suppose to - going to post this issue there

**Pull request merged**
