### PR TITLE
Add Option Group descriptions from templates/CRM/Admin/Page/Options.tpl

### PR DESCRIPTION
**Pull request by aydun**
Overview
----------------------------------------
Add Option Group descriptions from templates/CRM/Admin/Page/Options.tpl

Before
----------------------------------------
Description/help text is in smarty template

After
----------------------------------------
Descriptions in `civicrm_option_group.description` field, accessible to APIv4/SearchKit etc

Technical Details
----------------------------------------
'{ts escape="sql"}' copied from current tpl - not sure whether that is right here.

A few things to note compared to the tpl:
- `activity_type`: has '{help id='id-activity-type'} - omitted here
- `accept_creditcard`: 2 lines including html `<br>`  Need to decide whether these are to be treated as html fields.
- `from_email_address`: has `{if $allowLoggedIn}`, and embedded `<em>` `&lt;`  Added the longer text
- `participant_status` in smarty but is not an `option_group`
 
Could remove strings from tpl but we're trying to replace the admin pages where these are used, not improve them.

Comments
----------------------------------------
@colemanw

### CODE REVIEW

**Comment by aydun** [comment]
Hmm - failure is 
```
"ALTER TABLE `civicrm_option_group_en_US` MODIFY COLUMN `description` TEXT [nativecode=1347 ** 'core2514343604civi_g5mny.civicrm_option_group_en_US' is not BASE TABLE]"]
```
But the upgrade doesn't directly attempt to modify a `..._en_US` table.  How do we get around that?

**Comment by aydun** [comment]
Thanks @colemanw !

**Comment by colemanw** [comment]
That did the trick :)

**Comment by colemanw** [comment]
Great one @aydun!

**Pull request merged**
