### PR TITLE
4.7.27 rc

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Comment by seamuslee001** [comment]
ping @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
@seamuslee001 the DAO patch is breaking it - do I merge & then we try to fix?

**Comment by seamuslee001** [comment]
I think so

**Comment by eileenmcnaughton** [comment]
done! Wanna try re-running the regen to see what happens on master now?

**Pull request merged**
