### PR TITLE
WIP CRM-17977 Usability of allowed countries/states

### PR DESCRIPTION
**Pull request by JKingsnorth**
- [CRM-17977: Localisation screen "Available States and Provinces" list](https://issues.civicrm.org/jira/browse/CRM-17977)

### CODE REVIEW

**Comment by JKingsnorth** [comment]
Jenkins, retest this please

**Comment by alifrumin** [comment]
@josephlacey and I looking at this PR

**Comment by alifrumin** [comment]
Changing the UI widget to Advanced Multi Select seems to go against the larger trend... the civi community is moving towards deprecating Advanced Multi Select on user screens but since this is an admin screen we think its fine. Really like the title change.

**Comment by alifrumin** [comment]
tried to test the patch but it did not cleanly apply, need to retest. 

@totten can you rerun jenkins test

**Comment by josephlacey** [comment]
jenkins ok retest please

**Comment by mlutfy** [comment]
Is it still possible to select "all countries" and "all provinces"?

**Comment by mlutfy** [comment]
Tested this on the right sandbox this time, and +1 to the PR which reverts to what it was like in 4.6 (advselect).

I agree with @alifrumin that we should move away with advselect (we could do it for the currencies field). It would be useful to have "select all/none" in other places.

Select2 version 4 supports custom renderers as a way to have "select all" / "select none" (https://github.com/select2/select2/issues/195), but we are currently using select2 v3.5 and upgrading is non-trivial (will affect people's customizations). That's a bigger issue, and considering how often people modify the enabled countries/provinces, I would merge the PR for now.

**Comment by mlutfy** [comment]
Got the OK from Alice and Joseph. Merging.

**Pull request merged**
