### PR TITLE
CiviCase - Fix crash when fetching status_id pseudoconstant

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes crash reported in https://civicrm.stackexchange.com/q/46209

Before
----------------------------------------
Fatal error when upgrading (reportedly)

After
----------------------------------------
Crash avoided, although I'm still not sure the underlying cause.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
I read their post as that they can do the upgrade, but then when loading the "afsearchFarmSes..." (some custom form?) they get that error. I assume the form includes some case type field.

**Comment by chumkui** [comment]
I can confirm that this has addressed the immediate problem of CiviCRM failing to load.  I'll try and isolate the issue as demeritcowboy points out, we do use SearchKit forms now extensively and I'll check to see what that particular form does. Thanks again

**Comment by colemanw** [comment]
I'm going to merge this based on the theory that "not fatal error" is generally preferable to "fatal error"

**Comment by colemanw** [comment]
Thanks @chumkui that all makes sense to me. SearchKit uses APIv4 which is more sophisticated than v3 and has a habit of passing around arrays of multiple values when v3 could only cope with a single value - in this case it was fatal.
But I'm not sure how useful this filtering is really, and I'm inclined to leave things as-is rather than go nuts with potentially cpu-time-wasting loading of multiple activity types. As-is, it all seems to work.

**Comment by chumkui** [comment]
Glad it was useful Coleman - cannot comment on the bigger picture as I have enough problem trying to get my head around how CiviCRM is put together, I am glad i'm just an admin with minimal 'dev' :-) Thanks again for the fix!

**Pull request merged**
