### PR TITLE
CRM-21304 quash form reload message when refreshing

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Says huuuush to this message
screenshot 2017-10-12 18 01 33

Before
----------------------------------------
Above message suppressed when navigating away from the dedupe find screen by clicking a button (actually a redirect)

After
----------------------------------------
Above message also suppressed when reloaded or otherwise navigating away

Comments
----------------------------------------
There is no information stored on this page/form that would be worrisome to lose. Treat as a page, not a form

---

 * [CRM-21304: Dedupe usablity, quash refresh message in more cases](https://issues.civicrm.org/jira/browse/CRM-21304)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by ejegg** [comment]
Works locally, no work lost by reloading except resetting the result pager

**Comment by colemanw** [comment]
@eileenmcnaughton that didn't work for me, but this did. (commit added)

**Comment by eileenmcnaughton** [comment]
@colemanw Ok - that seems to be working.... merging

**Pull request merged**
