### PR TITLE
Fix php 7.2 countable warning

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fixes a notice on php 7.2

Before
----------------------------------------
per https://lab.civicrm.org/dev/core/issues/406#note_12393
Warning: count(): Parameter must be an array or an object that implements Countable in CRM_Event_Form_Participant->submit() (line 1722 of .../all/modules/civicrm/CRM/Event/Form/Participant.php).

After
----------------------------------------
no notice

Technical Details
----------------------------------------
if $taxAmt is NULL then it will give the error !empty works on NULL and on an empty array

Comments
----------------------------------------
@seamuslee001 I could be convinced to put this against the rc just on the basis we are now recommending php 7.2

### CODE REVIEW

**Comment by seamuslee001** [comment]
I think this makes sense and happy for it to be on the RC ;)

**Comment by eileenmcnaughton** [comment]
@seamuslee001 ok - on the rc now

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Pull request merged**
