### PR TITLE
CRM-21772 Online Event registration 'include profile' don't support contribution profiles

### PR DESCRIPTION
**Pull request by kewljuice**
Overview
----------------------------------------
On paid event registration, I need to capture some data via contribution profiles to be kept with the event contribution!

Comments
----------------------------------------
https://issues.civicrm.org/jira/browse/CRM-21772

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I tested this & could replicate the issue -  but not as a recent regression - it was present back to 4.7.27 at least.

In terms of the patch - I think in the interest of reducing cruft code we should call the create rather than add function on contribution on [this line ](https://github.com/civicrm/civicrm-core/pull/11684/files#diff-7a2ee8f032ba2340f94769e7a164e587R1069).  If we do that we will not need as much code handling as adding the custom params to contributionParams will be enough.

From my read of the code we'd just need to check the soft credit is not processed twice

**Comment by kewljuice** [comment]
Hi @eileenmcnaughton,

Do you have an example how to implement Custom Fields with the create function?

I have tried unsuccessfully to pass the $customParams (key, value) Array via $contribParams['custom'].

    // CRM-21772: save custom contribution profile fields
    if (!empty($customParams)) {
      $contribParams['custom'] = $customParams;
    }

    // create contribution record
    $contribution = CRM_Contribute_BAO_Contribution::create($contribParams); 

    /*
    // CRM-21772: save custom contribution profile fields
    if (isset($contribution->id) && !empty($customParams)) {
      CRM_Core_BAO_CustomValueTable::postProcess($customParams, 'civicrm_contribution', $contribution->id, 'Contribution');
    }
    */

But the `CRM_Core_BAO_CustomValueTable::store` function in `CRM_Contribute_BAO_Contribution::create` requires more then just key, value for Custom Fields.

**Comment by eileenmcnaughton** [comment]
@colemanw @lcdservices @agh1 @MegaphoneJon - this one & #11151 have been sitting in the queue for a while. I have some reservations about the implementation (too much work on the form layer).

But I also have a concern that I feel these are things Dave G had blocked for a reason - I'm not too sure the details but it feels like it might be unpredictable to allow contribution custom fields on an event page if it doesn't turn out to be monetary or perhaps if more than one payment is made against it.

I think the heeby jeebies I get from these 2 PRs is really what is blocking them so would be good to get some thoughts

**Comment by lcdservices** [comment]
I haven't tested it, but in principle I do think we should be able to include contrib fields in event profile forms. Really, anywhere we record a contribution we should be able to include contrib related fields. And my recollection is that this was supported at some point in the past -- but that may have been a while ago...

**Comment by JoeMurray** [comment]
For free event registratuons there were times when we didn't create a contribution, other times when there was a $0 contribution that people complained about. I think it is appropriate to be standardizing support for contribution custom field support in front and backend for any type of purchase: priceset and non-priceset membership and event and contribution.

**Comment by eileenmcnaughton** [comment]
Hmm - I still feel uncomfortable with this - there are multiple scenarios where a contribution record would not be created - $0, needs approval, waitlist - and in these cases we would simply throw away entered data. I feel like merging this we would be promising something we can't deliver & would cause problems down the track when people want their 'bugs' fixed

@colemanw your thoughts?

**Comment by JoeMurray** [comment]
I'm quite comfortable waiting for a more complete evaluation of the UX, what is/will be supported, etc. I have no opposition in principle to this functionality being in core, and I agree with @eileenmcnaughton 's nervousness around committing to this without a full evaluation and plan.

**Comment by eileenmcnaughton** [comment]
I still feel nervous here - I'm going to close it since that seems to be my feeling each time I visit it. If you are really keen to revive it lets' see if some tests might make it less uncomfortable or if we can find a way to do it in an extension

**Pull request closed without merging**
