### PR TITLE
SearchKit - Allow SearchSegments to be packaged as .mgd.php

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
This allows SearchSegments to be packaged and distributed in extensions, along with Saved Searches and Search Displays.

Comments
-----------------
This would allow, e.g. a [SearchKit-based Case Dashboard](https://lab.civicrm.org/dev/core/-/issues/3477) to be packaged.

### CODE REVIEW

**Comment by aydun** [comment]
Tested - works!

Could SavedSearch.export also include segments using in the search?

As search kit usage grows, there could be lots of segments.  It would be useful to have some sort of grouping or owner of these, possibly like OptionGroup/OptionValue.  Relatedly, it would be convenient to allow the API export function to take more than one id, - or a group id.

**Comment by aydun** [comment]
The SearchSegment.export produces names like '**SearchSegment**_Status_Ongoing' whereas the SavedSearch.export references 'SUM(**segment**_Status_Ongoing:label)'  It would be helpful to have consistent naming.

**Comment by colemanw** [comment]
> Could SavedSearch.export also include segments used in the search?

That would be nice. Tricky but nice.

> It would be useful to have some sort of grouping or owner of these, possibly like OptionGroup/OptionValue.

I'm not sure how common the trick from https://lab.civicrm.org/dev/core/-/issues/3477 is going to be. Generally speaking, a data segment is kind of both. It's an option group with a bunch of option values, and I think most of the time a single segment with multiple options will do the job. I'd guess it's pretty rare to have to create a bunch of search segments that all belong together.

> The SearchSegment.export produces names like 'SearchSegment_Status_Ongoing' whereas the SavedSearch.export references 'SUM(segment_Status_Ongoing:label)' It would be helpful to have consistent naming.

That's just the name of the Managed record. The name of the segment itself is consistent. Managed names are their own beast, and generally don't match the 'name' of the record itself.

**Comment by aydun** [comment]
Ok, thanks

**Pull request merged**
