### PR TITLE
CRM-19900 Enable/Disable payment processor from summary page only disables live

### PR DESCRIPTION
**Pull request by mattwire**
Don't use generic javascript function on summary screen.  Add a function in Financial BAO Paymentprocessor to enable/disable payment processor and trigger this.

---

 * [CRM-19900: Enable\/Disable payment processor from summary page only disables live](https://issues.civicrm.org/jira/browse/CRM-19900)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire I'm inclined to think we should tackle this by adding it to the BAO create action - ie. within the create action if you enabled or disable the live payment processor it would do the same to the test one  - this would give api users the same behaviour (& make the enabledisable tpl function work properly I think). In general the BAO should implement business logic & I think this is a business rule

**Comment by jackrabbithanna** [comment]
This seems like rather huge PR, may be nice to have it broken down into more manageable/review-able chunks.  @eileenmcnaughton @totten @colemanw

**Comment by totten** [comment]
Yeah, the long list of commits is pretty hard to read. Many of those commits are already in `master`, so this might be an issue with how merges were done. (Ex: If you do a `git merge` or `git pull` several times during development of the PR, this kind of thing might happen. Instead of basic pull, I suggest `git pull --rebase origin master`)

It may be workable to rebase now, e.g.

```
git checkout disable_payment_processor -b disable_payment_processor_rebased
git pull --rebase origin master
git push mattwire disable_payment_processor_rebased
```

and then open a different PR.

**Comment by mattwire** [comment]
Whoa! That went pretty wrong.  I did a rebase earlier on something else and clearly screwed up somewhere... Please see https://github.com/civicrm/civicrm-core/pull/9891 that replaces this one

**Pull request closed without merging**
