### PR TITLE
CRM-21283 Incorporate Barbados and Antigua and Barbuda parishes into …

### PR DESCRIPTION
**Pull request by seamuslee001**
…list of states as per ISO documentation https://en.wikipedia.org/wiki/ISO_3166-2:BB https://en.wikipedia.org/wiki/ISO_3166-2:AG

Overview
----------------------------------------
This picks up the initial work done here https://github.com/civicrm/civicrm-core/pull/10696/files but standardizes the abbreviation correct to the ISO as per the wikipeida links

Before
----------------------------------------
No parishes were listed

After
----------------------------------------
Parishes are listed

@monishdeb @eileenmcnaughton @totten @mlutfy this is a pretty straight forward thing just adding in more states as per the ISO

### CODE REVIEW

**Comment by monishdeb** [comment]
Tested on 4.7.27 install and upgrade, working fine.

**Comment by monishdeb** [comment]
@seamuslee001 before merge I want mention a minor change I made - https://github.com/civicrm/civicrm-core/pull/11100/commits/07b81c551502520143e1f7874c3f2da3e31819ba 

Do you agree?

**Comment by seamuslee001** [comment]
Yep i’m Happy with this @monishdeb

**Comment by monishdeb** [comment]
even Jenkin too :)

**Pull request merged**
