### PR TITLE
CRM-17324 Log upgrade steps

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
This puts the meter back into thermometer watching.  Prints a granular
log line for each upgrade migration patch.

TODO:
- The Drush harness should install a logging callback that captures Civi
  output and displays it on the console.

Bug: T99842
Change-Id: I8977b6b06b4eac9cd7e5ac5768c783d8560abfe3

---
- [CRM-17324: Log upgrade progress to CiviCRM log](https://issues.civicrm.org/jira/browse/CRM-17324)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@totten any hesitation with this?

**Comment by seamuslee001** [comment]
Test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by totten** [comment]
+1

**Pull request merged**
