### PR TITLE
Riverlea - disable dark mode by default

### PR DESCRIPTION
**Pull request by ufundo**
Overview
----------------------------------------
Lots of CMSes don't like dark mode, so disable it by default in Riverlea. See https://github.com/civicrm/civicrm-buildkit/pull/901

Before
----------------------------------------
- default is inherit (ie respect your browser/OS's dark mode setting)
- if your CMS theme doesn't support dark mode, then liable to clashes that dont look good

After
----------------------------------------
- default is light (never use dark mode)
- you can switch it to inherit (or dark) in Display Settings or in Riverlea Settings

### CODE REVIEW

**Comment by colemanw** [comment]
> Lots of CMSes don't like dark mode

We could make an exception for standalone?

**Comment by ufundo** [comment]
Yes, I think that would be next step

**Comment by demeritcowboy** [comment]
I don't normally look at theming stuff but anything that turns off dark mode is The Right Thing To Do™

**Comment by ufundo** [comment]
@colemanw  follow up https://github.com/civicrm/civicrm-core/pull/31633

**Comment by ufundo** [comment]
Thanks @demeritcowboy . Standalone might go over to the Dark Side though still :imp:

**Comment by ufundo** [comment]
I'm thinking this should probably be backported to 5.81 and maybe even 5.80.

@totten any view on this?

**Comment by ufundo** [comment]
@totten PRs if you think it makes sense. Feel free to take em or leave em!
https://github.com/civicrm/civicrm-core/pull/31643
https://github.com/civicrm/civicrm-core/pull/31644

**Pull request merged**
