### PR TITLE
dev/core#767 Add 'Cancelled / Refunded Date' and 'Cancellation / Refund Reason'

### PR DESCRIPTION
**Pull request by avall-llovera**
Overview
----------------------------------------
Add the fields and filters 'Cancelled / Refunded Date' and 'Cancellation / Refund Reason' in the Detail Contributions Report

https://lab.civicrm.org/dev/core/issues/767

Before
----------------------------------------
**Columns**
columns_without_fields

**Filters**

filters_without_fields

After
----------------------------------------
**Columns**
columns_with_fields

**Filters**

filters_with_fields

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
add to whitelist

**Comment by francescbassas** [comment]
jenkins test this please

**Comment by francescbassas** [comment]
jenkins test this please

**Comment by francescbassas** [comment]
jenkins test this please

**Comment by yashodha** [comment]
tested this, works fine.

**Pull request merged**
