### PR TITLE
Hide Adding Option Value for Locked Groups

### PR DESCRIPTION
**Pull request by mickadoo**
Overview
----------------------------------------

You can edit option values from a few different places:

1. `civicrm/admin/options?gid=<option_group_id>`
1. `civicrm/admin/options/<option_group_name>`
1. `civicrm/admin/custom/group/field/option?action=browse&gid=<custom_group_id>&fid=<custom_field_id>`

When "is_locked" = 1 only the first method hides the button to add new option values In all. In all places you can delete option values, despite the notice on locked group edit pages saying:

> This option group is reserved for system use. You cannot add or delete options in this list.

The button to add an option value will be hidden for locked option groups by this PR. It will also remove the option to delete option values for locked option groups.

Before
----------------------------------------

##### From Custom Field Edit page

image

##### From Option Group Edit Page Using Group ID

image

##### From Option Group Edit Page Using Group Name

image

After
----------------------------------------

##### From Custom Field Edit page

image

##### From Option Group Edit Page Using Group Name

image

##### From Option Group Edit Page Using Group ID

image

------------------

[Link to Issue](https://lab.civicrm.org/dev/core/issues/55)

Notes
----------------------------------------

I fixed a few unrelated typos and removed one unused `$config` variable in this

### CODE REVIEW

**Review by ajesamson — APPROVED** [review]
Looks good. Await more reviews from others (non compucorp)

**Comment by ajesamson** [comment]
* Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
    * __PASS__ : The goal/problem/solution have been adequately explained in the PR.
* Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
    * __UNREVIEWED__
* Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
    * __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
* Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
    * __UNREVIEWED__
* Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
    * __UNREVIEWED__
* Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
    * __PASS__: A new civicrm was setup with civibuild `civibuild create civi47   --type drupal-demo   --civi-ver master --url "http://civi47.local:9091" --admin-pass admin --web-root /vagrant/civi47` locally. After setup, the reported issues were verified, visiting all the three links specified in the overview. The option value `is_locked` was set to `1` to confirm add options button is still visible. Hub was setup and used in switching branch to this PR. The links were re-visited to confirm the `add options` button was hidden from user's view.
* User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
    * __PASS__: The change would be intuitive or unnoticeable for a majority of users who work with this feature.

**Comment by mickadoo** [comment]
@colemanw any chance we could get a review for this? Willing to put in time reviewing another PR if needed

**Comment by colemanw** [comment]
@mickadoo in the last screenshot it says "You cannot add or delete options in this list" right above items that contain a "Delete" button beside them... ?

**Comment by mickadoo** [comment]
@colemanw that's a good point, it looks like this message never matched functionality. I've added 3 new commits to remove the option to delete option values for locked options groups, both in the custom field edit screen and the option group edit screen.

**Review by ajesamson — APPROVED** [review]
Approved

**Comment by ajesamson** [comment]
Updates approved @mickadoo.

**Comment by colemanw** [comment]
I give a __Pass__ to the remaining items in the checklist.

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Pull request merged**
