### PR TITLE
CRM-19679 fix custom file upload in multi-record set

### PR DESCRIPTION
**Pull request by lcdservices**
* [CRM-19679: multi custom data: file field errors on new record save](https://issues.civicrm.org/jira/browse/CRM-19679)

### CODE REVIEW

**Comment by yashodha** [comment]
@lcdservices : Can you fix the warnings as per https://test.civicrm.org/job/CiviCRM-Core-PR/12687/checkstyleResult/new/

**Comment by lcdservices** [comment]
done.

**Comment by jitendrapurohit** [comment]
Seems the field ID is not populated correctly due to improper cgcount, I've submitted an alternate PR https://github.com/civicrm/civicrm-core/pull/9436. Can you please check if it works for you ?

Thanks.

**Comment by monishdeb** [comment]
@lcdservices does #9436 works for you ?

**Comment by lcdservices** [comment]
yes, #9436 is working for me. thx.

**Comment by yashodha** [comment]
closing in favor of #9436.

**Pull request closed without merging**
