### PR TITLE
Fix height of select2 box (appears squished)

### PR DESCRIPTION
**Pull request by smaen123**
Before
image

After
image

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins add to whitelist

**Comment by seamuslee001** [comment]
@smaen123 was this on a contribution page or something? just trying to figure out where this was hit. Also did you look to see if it was an issue with your theme overriding the height of the select2?

**Comment by mattwire** [comment]
@seamuslee001 It happens with various themes and affects every select2

**Comment by eileenmcnaughton** [comment]
@artfulrrobot

**Pull request merged**
