### PR TITLE
avoid divide-by-zero when validating 'other amount' on contribution pages

### PR DESCRIPTION
**Pull request by MegaphoneJon**
Overview
----------------------------------------
A proposed fix for https://lab.civicrm.org/dev/core/-/issues/5079, and an alternate to https://github.com/civicrm/civicrm-core/pull/29717.

Before
----------------------------------------
Submitting alpha characters in "Other Amount" gives a divide-by-zero error.

After
----------------------------------------
Fails validation.

Technical Details
----------------------------------------
This works because `getLine()` a few lines above will return zero here.  But a code comment says `getLine()` is getting phased out so maybe this needs to be handled higher up?

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon so my thoughts here are

1) it doesn't replace the other PR because that one would handle the situation where the incoming amount is `1.000,99 EUR` & transpose it to 1000.99 rather than 1
2) this probably is the right place since it's already clear the code relates to a specific form scenario & while part of me thinks it should like on the form it relates to that would be hard.
3) I feel like it would be better to make this narrower - ie still set the various keys - just do it without some line-level handling

image

**Comment by MegaphoneJon** [comment]
@eileenmcnaughton I like your suggestion better - the concern I (later) thought of was not recording line items for free event registrations.  Does the fact that you have a screenshot mean you have the code ready to push? You can add it to #29717 and we can close this.

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon OK - I added it

**Pull request closed without merging**
