### PR TITLE
CRM-17852 - Misspeled state names in Estonia/Lithuania

### PR DESCRIPTION
**Pull request by sarehag**
CRM-17852, asked in IRC for feedback since there was a mismatch between wikipedia and issue, but used description on wikipedia rather than issue after asking in IRC. Added a comment with basically same info as here. Im new with this, so if i am doing something wrong, please tell me and I will try to fix.

---
- [CRM-17852: Misspeled state names in Estonia\/Lithuania](https://issues.civicrm.org/jira/browse/CRM-17852)

### CODE REVIEW

**Comment by colemanw** [comment]
jenkins, add to whitelist

**Comment by eileenmcnaughton** [comment]
I just merged this since it had merge on pass - but now I have some misgivings. Shouldn't the sql have been

UPDATE civicrm_state_province SET name = 'Harjumaa' where name = '"Harjumsa";

**Comment by colemanw** [comment]
I'm not sure, the ids seem to be fixed. At least `id` doesn't seem to be auto-incrementing based on how the INSERT is being done.
Also if you were to do it that way, you'd probably need to also specify the country id so you didn't accidentally mess up the name of a province in an unrelated country that happened to be (correctly) spelled the way this one was misspelled.

**Comment by eileenmcnaughton** [comment]
There seems to be a precedent for both ways in previous scripts - but bear in mind that customers often edit their own state province tables (quite reasonably)- and the Insert is for new installs.

**Comment by colemanw** [comment]
Now you've got me worried... I'll rework it.

**Comment by sarehag** [comment]
Would you like me to change the script so that it updates based on both state name and id? That way all the databases where the name has not been changed will be changed and any databases where the users have changed the name to something else will not be changed.

**Comment by colemanw** [comment]
I think it should be based on state name and country id.

    UPDATE civicrm_state_province SET name = 'Harjumaa' where name = 'Harjumsa' AND country_id = 1069;

This is already merged, but if you could send a follow-up PR to make that change, that would be much appreciated.

**Comment by sarehag** [comment]
Absolutely, I'll get right on it. Sorry for causing so much trouble on my first pull request.

**Comment by eileenmcnaughton** [comment]
Sadly you probably need to join onto country & get the country name to be really safe

**Comment by colemanw** [comment]
@sarehag thanks for your persistence, sorry our schema isn't easier to work with. Ok how about grabbing the country id by name and stashing it in a sql variable.

**Comment by sarehag** [comment]
Absolutely, no worries.

**Comment by eileenmcnaughton** [comment]
@sarehag thanks for your first patch! Yay you!

**Pull request merged**
