### PR TITLE
Replace some calls to CRM_Core_Error::fatal with exceptions

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Continues ongoing changes to replace CRM_Core_Error::fatal with
- status bounce in forms where appropriate otherwise
- throwing exceptions

Before
----------------------------------------
Fatal used

After
----------------------------------------
Exception used

Technical Details
----------------------------------------
@seamuslee001 @mattwire @colemanw we've replaced a lot of these with no fallout - maybe we should pick up the pace on them? We finally got to the end of $dao->free()

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 ok with this?

**Comment by seamuslee001** [comment]
@eileenmcnaughton should we be tsing these Exceptions?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 it seems to 'depend' - in this case I left it unchanged

**Comment by eileenmcnaughton** [comment]
I would note these are 'should never be hit' exceptions

**Comment by seamuslee001** [comment]
I've umed and arded over whether we need to ts i don't think so in this case so merging

**Pull request merged**
