### PR TITLE
[Smarty variables] [CiviCase] remove isset from case dashboard

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
[Smarty variables] remove isset from case dashboard

Before
----------------------------------------
Fatals on case dashboard with smarty escape by default

After
----------------------------------------
fixed

Technical Details
----------------------------------------
Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by demeritcowboy** [comment]
I don't know if trying to put this test in testOpeningForms will work. Enabling civicase in tests seems to require more than just enabling civicase, and this test was originally meant for simple stuff. When I haven't been able to make tests work here I've just made a separate test somewhere else, like how tests/phpunit/CRM/Case/Form/SearchTest extends CiviCaseTestCase, although it doesn't use Invoke (it maybe should).

**Comment by eileenmcnaughton** [comment]
@demeritcowboy that test actually passes locally- but I can't replicate it failing on jenkins & it doesn't seem worth fighting that battle so I removed

**Comment by demeritcowboy** [comment]
Ok yes that's the kind of thing that's blocking me on the smarty static one too. Trying to debug it locally isn't helpful.

The enableCiviCase line is still in here, but I guess we'll see if that passes.

**Comment by eileenmcnaughton** [comment]
fail is that known unrelated one

**Pull request merged**
