### PR TITLE
Crm-16981- CiviMail - fix visible mailings for ACLed and multisite users

### PR DESCRIPTION
**Pull request by MegaphoneJon**

### CODE REVIEW

**Comment by seamuslee001** [comment]
@PalanteJon Jon one other thing i have found in my testing is that for mailings that don't have a group set, they can still go across domains (you could be dealing in sending mailings based on other mailings for instance perhaps). So in my testing i have added in after the array_keys implode

```php
$domain_id = CRM_Core_Config::domainID();
``` 

then in the query have in the or statement

```sql
AND m.domain_id = $domain_id
```

**Comment by seamuslee001** [comment]
@davecivicrm This patch looks fine. I think given that this was working properly up until 4.6 for drupal folk it probably should also be merged into 4.6, It is a fairly minimal patch and also I think it would be a good extension for Joomla and Wordpress folk

**Comment by kurund** [comment]
jenkins, add to whitelist

**Comment by eileenmcnaughton** [comment]
Note that this has gone out to our 4.6 users in the fuzion repo so is in live testing - although our most avid tester is actually Seamus anyway :-)

**Pull request merged**
