### PR TITLE
Remove redundant custom field types

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Custom field `html_type` 'Select Country' and 'Select State/Province' served no purpose and have been removed. They are the same as 'Select', just with a different data_type.

Before
----------------------------------------
The `html_types` 'Select Country' and 'Select State/Province' exist.

After
----------------------------------------
Now they don't.

Technical Details
----------------------------------------
This adds an APIv3 shim to display the old types, which should mitigate the impact on APIv3 users.
No shims added for APIv4 since it's relatively new.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Test Result (1 failure / -13)
CRM_Core_BAO_CustomFieldTest.testGetFieldsForImport

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@colemanw this I think will work fine but we will need a corresponding PR to update here https://github.com/civicrm/civicrm-drupal/blob/7.x-master/modules/views/civicrm.views.inc#L567 and maybe https://github.com/civicrm/civicrm-drupal/blob/7.x-master/modules/views/civicrm.views.inc#L465 but probably doesn't matter that one

**Comment by colemanw** [comment]
Ok @seamuslee001 I have opened https://github.com/civicrm/civicrm-drupal/pull/622

**Comment by seamuslee001** [comment]
Changes look good and I have tested the views changes and they work as well merging

**Pull request merged**
