### PR TITLE
CRM-16734 participant tokens in participant pdf - cleanup

### PR DESCRIPTION
**Pull request by johanv**
This PR replaces #8260. I just squashed the commits.

As for the comments of @jitendrapurohit:
- {participant.participant_role} and {participant.participant_role_id} seem to work.
- I removed {participant.transferred_to_contact_id} because I have no clue what it should do.
- I removed {event.fee_amount} because fee_amount applies to participant, not to event.
- I don't think it is wrong that {participant.participant_role_id} returns an integer. But a token {participant.participant_role} that returns the name of the role, would be nice. I still have to look at this.

---
- [CRM-16734: Add participant tokens to participant pdf action](https://issues.civicrm.org/jira/browse/CRM-16734)

### CODE REVIEW

**Comment by johanv** [comment]
If I refactor this wisely, i think I can fix CRM-16579 as well.

**Comment by colemanw** [comment]
@johanv so is this still a work-in-progress?

**Comment by johanv** [comment]
Sorry, I have to postpone this once again, because of other work :-(

**Comment by monishdeb** [comment]
Ok, I am marking it with [WIP]

**Comment by jitendrapurohit** [comment]
@eileenmcnaughton Can we close this as it hasn't progressed from a long time? Also, one can always re-open this when anyone feels to work on it.

**Comment by magnolia61** [comment]
@johanv any chance of reviving this wip in order to have participant custom tokens in both pdf and scheduled reminders? I opened a gitlab issue for this at: https://lab.civicrm.org/dev/core/issues/348

**Pull request closed without merging**
