### PR TITLE
Settings to disable creating relationship on shared address creation

### PR DESCRIPTION
**Pull request by samuelsov**
Overview
----------------------------------------
CiviCRM create by default a employee/employer relationship when creating a shared relationship between an individual and an organisation. Sometimes we want more control over the relationship and we don't want CiviCRM to mess with the current relationships.

As suggested in several issues, the simple solution is to have a setting to disable this behaviour.

Before
----------------------------------------
In a individual contact, when creating a shared address with a non employer organization, it will disable any active employer relationship, create a new one and update current employer

After
----------------------------------------
In Misc settings (/civicrm/admin/setting/misc?reset=1):

58cfaf66-2de4-40b2-ae1a-a2100f6dd99b

By default, the value is Yes and the behaviour is the same as before.
If the setting is set to No, CiviCRM won't change or create any relationship when doing a shared address.

Comments
----------------------------------------
Also see https://issues.civicrm.org/jira/browse/CRM-21008

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
https://lab.civicrm.org/eileen/Product-maintenance/issues/14 really highlighted to me the issues for maintaining settings. In this case the setting seems to be because we want to guess what the user wants rather than ask them - I think we must be able to come up with a UI way - pop up or similar - to find out what the user actually wants to do when delinking an address associated with an employee

@colemanw might have an idea

**Comment by colemanw** [comment]
I agree with Eileen. When creating a shared address there probably should be a checkbox saying "Set *Organization Name* as current employer."

**Comment by tschuettler** [comment]
A setting may still be desired to define the default for the checkbox. Having the checkbox would only help for UI modifiications, but not for API usage or CSV imports.

**Comment by eileenmcnaughton** [comment]
@tschuettler it might make sense to support a parameter at the api level - that's something we can lock in with a unit test & hence has less maintainability issues

**Comment by tschuettler** [comment]
Yeah, that sounds reasonable.

**Comment by samuelsov** [comment]
Regarding maintenance, i trust you on this.

You suggest to add a checkbox when linking/delinking an address: it seems reasonable. 
Even if it adds some complexity to the end user, i like that it brings some transparency.
We will have to make it clear however that it will not only change the current employer but also disable any existing employer relationship (adding a help icon my be enough).

Regarding the suggested api change / unit test, i will try to do it but any help is welcomed :-)

**Comment by samuelsov** [comment]
Well, it complicates things quite a bit.  I'm not sure i will have the resource to finish this.

Note that we need to :

- dynamically load the checkbox (only for address of individual with shared address of an organization)
- ensure that when we edit an already existing shared address, it does ask if we want to update the current employer (not really intuitive to ask again but not a good idea to assume one way or another)
- make it work on quick edit and contact edit as well (same code ?)
- ideally, add a parameter in the api & unit test for this

Also, the relationships are not currently updated when we remove a shared address so i guess we don't have to add this checkbox in this context (plus it could be tricky in term of UI).

@colemanw Just to be sure, is this what you had in mind ?

screenshot_2018-07-27 dr esta cruz civicrm sandbox on drupal 7 2

**Comment by colemanw** [comment]
@samuelsov yes I think that looks great. I've done a lot of work on that form and I'm happy to help out if it feels unfamiliar to you. Do you have a WIP patch you'd like me to help with?

**Comment by eileenmcnaughton** [comment]
@samuelsov looks like your WIP patch rather than this one is likely to be merged - if you are not going to work on this in the next week or 2 let's close & track through gitlab & open a PR when you are ready

**Comment by samuelsov** [comment]
Ok, i'm working on a new patch on : samuelsov:CRM-21008-3
Let's close this one.

**Comment by eileenmcnaughton** [comment]
Great @samuelsov - I look forward to seeing it

**Pull request closed without merging**
