### PR TITLE
Remove references to invalid action

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Remove references to invalid action - 1028 does not exist 

image

Before
----------------------------------------
A bunch of always true ifs

After
----------------------------------------
gone

Technical Details
----------------------------------------

All these references refer to comparing action to 1028. The comments make is clear that they are looking for 'preview' mode - but preview mode is 1024. The checks are all does-not-equal. So, they would have always been true for a very long time.

Copy & paste is dead long live copy & paste

Comments
----------------------------------------
I checked & in actual preview mode the contents of the if resolve to TRUE

### CODE REVIEW

**Comment by colemanw** [comment]
Just to show my love of copy-and-paste, here is my thoughtful review of this PR:

(*CiviCRM Review Template DEL-1.2*)


* General standards
    * Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
        * __UNREVIEWED__
        * __PASS__ : The goal/problem/solution have been adequately explained in the PR.
        * __PASS__ : The goal/problem/solution have been adequately explained with a link (JIRA, Github, Gitlab, StackExchange).
        * __ISSUE__: Please provide a better explanation of the goal/problem being addressed.
        * __ISSUE__: Please provide a better explanation of how this solution works.
        * __COMMENTS__: 
    * User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
        * __UNREVIEWED__
        * __PASS__: The change would be intuitive or unnoticeable for a majority of users who work with this feature.
        * __ISSUE__: The change would noticeably impact the user-experience (eg requiring retraining), and the approach should be changed.
        * __ISSUE__: The change would noticeably impact the user-experience (eg requiring retraining), and we need a better transition/communication plan.
        * __PASS__: The change would noticeably impact the user-experience (eg requiring retraining), but this has been addressed with a suitable transition/communication plan.
        * __COMMENTS__: 
    * Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
        * __UNREVIEWED__
        * __PASS__: There are relevant updates for the documentation.
        * __PASS__: The changes do not require documentation.
        * __ISSUE__: The user documentation should be updated.
        * __ISSUE__: The administrator documentation should be updated.
        * __ISSUE__: The developer documentation should be updated.
        * __COMMENTS__: 
    * Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
        * __UNREVIEWED__
        * __PASS__: 
        * __ISSUE__: 
* Developer standards
    * Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
        * __UNREVIEWED__
        * __PASS__: The change preserves compatibility with existing callers/code/downstream.
        * __PASS__: The change potentially affects compatibility, but the risks have been sufficiently managed.
        * __ISSUE__: The change potentially affects compatibility, and the risks have **not** been sufficiently managed.
        * __COMMENTS__: 
    * Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
        * __UNREVIEWED__
        * __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
        * __ISSUE__: Something was unclear to me.
        * __ISSUE__: The approach should be different.
        * __COMMENTS__: 
    * Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
        * __UNREVIEWED__
        * __PASS__: The change sufficiently improves test coverage, or the change is trivial enough that it does not require tests.
        * __PASS__: The change does not sufficiently improve test coverage, but special circumstances make it important to accept the change anyway.
        * __ISSUE__: The change does not sufficiently improve test coverage.
        * __COMMENTS__: 
    * Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
        * __UNREVIEWED__
        * __PASS__: The test results are all-clear.
        * __PASS__: The test results have failures, but these have been individually inspected and found to be irrelevant.
        * __ISSUE__: The test failures need to be resolved.
        * __COMMENTS__:

**Comment by seamuslee001** [comment]
@eileenmcnaughton I had thought that part of this was that preview got the id of view and its self maybe but maybe something is confusing me

**Comment by colemanw** [comment]
Oh yea, bitwise logic, `PREVIEW + VIEW = 1028`. Maybe there is something to that?

**Comment by eileenmcnaughton** [comment]
Hmm - well the Preview screen is the only one with an action of 'preview' @seamuslee001 -  and the value is 1024 on that screen....

**Pull request merged**
