### PR TITLE
APIv4 Explorer: Generate short cv code

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Generates the clever shorthand cv code that @totten made.

Before
----------------------------------------
image

After
----------------------------------------
image

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton does this help you hate APIv4 less on the CLI?

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@colemanw yes- I'm not sure it goes far enough but I don't want perfect to be the enemy of the good on this one

**Comment by eileenmcnaughton** [comment]
ok-without-test as outside tested  / testable subsystems

**Comment by totten** [comment]
Ooooh, I didn't see this one back on August 6. I just wanna say "huzzah"

**Comment by colemanw** [comment]
Thanks @totten.
Unfortunately there's a bug - APIv4 is strict about input types, which causes problems like this on the CLI:

image

**Pull request merged**
