### PR TITLE
docs/dev/-/issues/884 - Change 'Other' gender to 'Non-binary'

### PR DESCRIPTION
**Pull request by agileware-justin**
Overview
----------------------------------------

Change 'Other' gender to 'Non-binary'. See https://lab.civicrm.org/documentation/docs/dev/-/issues/884

Before
----------------------------------------
'Other' gender

After
----------------------------------------
'Non-binary' gender

Technical Details
----------------------------------------

Comments
----------------------------------------
Requires mysql re-gen

### CODE REVIEW

**Comment by homotechsual** [comment]
The question here becomes how far do we subdivide this? Agender is not strictly non-binary and if we're in here we should add a "prefer not to say" option as standard.

**Comment by homotechsual** [comment]
I think a reasonable core-starter is

Female
Male
Other
Prefer not to say

**Comment by seamuslee001** [comment]
Also there is this extension here https://civicrm.org/extensions/gender-self-identify that can help but I agree with @homotechsual on the defaults for CiviCRM

**Comment by agileware-justin** [comment]
The PR has a link to the docs issue which is worth reading.

I don't know if the docs author has a GitHub account, so their voice may not be heard here. So I'll ping them to invite them to comment.

**Comment by colemanw** [comment]
I think the rationale for "Other" is that it's the widest possible umbrella. Other, more specific terms like "nonbinary" can be added as needed by the organization, or the Gender Self-Identify extension allows end-users to create their own options without an admin.
I'd also like to point out that by default the field is not required, so the user can simply leave it blank, which is equivalent to "Prefer not to say"

**Comment by eileenmcnaughton** [comment]
FYI this is the test issue - 

image

**Comment by UeNu9** [comment]
@colemanw  I am in favor of adding the "Prefer not to say" option to core, as it can be a valuable impulse for users who have not considered yet that asking for gender could mean asking for sensitive information. 
I agree that "Other" is a wider and more inclusive term than "Non-binary", even though I find the wording a bit derogative.

**Comment by colemanw** [comment]
Closing this PR based on lack of general agreement to change 'Other' to "Non-binary"

**Pull request closed without merging**
