### PR TITLE
Convert the type on the UserJob entity to be a string

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Currently we are storing a numeric ID - however if we
permit non-core classes to register types we find numeric ids
quickly become hard to manage as uninstalling an extension could
change the id. This switches to using a string type

Before
----------------------------------------
`civicrm_user_job` uses `type_id` to track the job 'type' - but this can't be extended because an integer varies

After
----------------------------------------
`civicrm_user_job` now users `job_type` - a var char

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by totten** [comment]
__r-run: DB Upgrade__: I did some imports on `5.51.beta1`, ran the upgrade to `5.51.beta2` (*patch added*), and inspected `civicrm_user_job`. The resulting schema matched, and the `job_type`'s appeared to correlate to the previous `type_id`s. :+1: 

__r-run: Import UI__:  I ran "Import Contacts", "Import Activities", and "Import Custom Data" (mostly using `testdata`, though I twiddled the `activities.csv` to set `source_contact_id`). The results appeared to be the same, but I think this is a new warning on the "Import Contacts" and "Import Activities":

Screenshot from 2022-06-29 00-25-48

Seems like a relevant warning, no?

**Comment by eileenmcnaughton** [comment]
Ah - that needs to be changed to `job_type:label`

**Comment by eileenmcnaughton** [comment]
@totten if it is just that e-notice are you OK to merge this & then I will do a follow up for it? It's a bit easier for me that way

**Comment by totten** [comment]
Well, I hadn't dug into see if the warning was meaningful. So I took a look now - and, in fact, page-title was wrong when using "Import Activities". Added a commit to fix.

**Comment by totten** [comment]
Grepped around for other references to `type_id`. There are some comments that can be updated like:

```
* Get the name of the type to be stored in civicrm_user_job.type_id.
```

But that has no functional impact. That can be follow-up.

Aside for the record - as eileen noted elsewhere, this field is pretty new and only becomes meaningful with 5.51. So we don't expect that contrib has any `r-tech` reliance on this (yet). And it's a lot easier to adjust if we can get this into 5.51 before there is more meaningful downstream reliance.

Merge on pass.

**Comment by totten** [comment]
AFAICS, #23893 doesn't have any changes affecting `Summary.php` or `FiveFiftyOne.php`, so :crossed_fingers: you won't have to play the rebase game :basket: :basketball: :bouncing_ball_person: .

**Comment by eileenmcnaughton** [comment]
@totten I would have had to to update this PR without overwriting your patch

**Pull request merged**
