### PR TITLE
Calculate unit_price based on qty

### PR DESCRIPTION
**Pull request by konadave**
Overview
----------------------------------------
When a template contribution is created for a recurring contribution, the unit_price on the line item is set to match the line_total, ignoring qty. This was discovered because it throws of the sync with Xero. Discussion on MM: https://chat.civicrm.org/civicrm/pl/54a3no8hzb8t8cgbwnrupdxbsc

### CODE REVIEW

**Comment by mattwire** [comment]
@konadave Error seems to be `Failure in api call for Order create:  Undefined array key "qty"`

**Comment by konadave** [comment]
@mattwire So I need to find and fix a broken test too?

**Comment by mattwire** [comment]
@konadave Well it's triggered a lot of failed tests. In theory it's caused by this PR so maybe it's just that `$lineItem['qty']` is not set in various situations? If you click on details and look down into the backtrace I think each one is the same error and it tells you which lines it was triggered on.

**Comment by konadave** [comment]
Hold on this. Looking in client DB I see the need to address qty == 0. Will address tomorrow.

**Comment by eileenmcnaughton** [comment]
@konadave this looks correct to me - it seems like a (fairly old)  regression so maybe target 5.50 rc?

**Comment by konadave** [comment]
I did more looking into line items with qty == 0 in client db, and none of them are linked to a recurring contribution. Can't think of a reason for a zero qty recurring contribution. And I'm pretty sure this method is only called in the context of a recurring contribution.

@eileenmcnaughton do you think it's safe to ignore qty == 0 here? And if not, should it therefore make sure that line_total is zero instead?

**Comment by eileenmcnaughton** [comment]
@konadave if qty is 0 I would expect lin_total to be too - so we would wind up with 0 / 1 - which would be zero - that seems fine?

$lineItem['line_total'] / ($lineItem['qty'] ?? 1)

**Comment by konadave** [comment]
@eileenmcnaughton Using ??, if qty is explicitly set to zero then we get divide by zero. How about this?

**Comment by eileenmcnaughton** [comment]
@konadave I think maybe the `else` there should be the unit_price still being equal to the line_total

**Comment by eileenmcnaughton** [comment]
@konadave to pass style 

`}
else {`

Also - should this be against 5.50 so it is in the next rc?

**Comment by konadave** [comment]
@eileenmcnaughton maybe my eyes are crossing, but `} else {` is what I did. I don't really know what version it should be against; client that discovered issue is on 5.46.3, which this method is slightly different.

**Comment by eileenmcnaughton** [comment]
@konadave  - check under control structures - https://www.drupal.org/docs/develop/standards/coding-standards

If is against the rc it will get released slightly quicker - which is what we do for regressions

**Comment by konadave** [comment]
@eileenmcnaughton sorry, misunderstood what you were telling me. Against rc sounds fine. Thanks.

**Comment by eileenmcnaughton** [comment]
@konadave you have to change the base branch to 5.50

**Comment by konadave** [comment]
is this totally jacked at this point?

**Comment by eileenmcnaughton** [comment]
@konadave when it's like that I normally do a `git reset --hard origin/5.50` and then cherry-pick your patch back on & do a forced push

**Comment by eileenmcnaughton** [comment]
Otherwise merged

**Pull request closed without merging**
