### PR TITLE
Allow custom fields of type Autocomplete-Select to be multivalued

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Reviewer's cut of #16923
Support multi-select for auto-complete custom field

Before
----------------------------------------
Custom fields of type "Autocomplete-Select" could only be single-valued.

After
----------------------------------------
Custom fields of type "Autocomplete-Select" can optionally be multi-valued.
Existing fields are unaffected.

Technical Details
----------------------------------------
At the time of the original #16923 PR, whether a custom field was single or multi-valued was not well-defined. Now it is, with the addition of a `serialize` column making this change relatively simple.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Test Result (2 failures / +2)
CRM_Export_BAO_ExportTest.testSingleSelectAutoComplete
CRM_Export_BAO_ExportTest.testMultiSelectAutoComplete

**Comment by eileenmcnaughton** [comment]
@pradpnayak looks like the original PR was yours (& triggered quite a bit round of clean up/rationalisation). Can you review this please?

**Comment by pradpnayak** [comment]
Hi @colemanw 

I did some UI test today, Here are my findings and test results

Created custom group and added custom field of type auto complete.

1. Multi-Select option
before patch: Not available via UI
after patch:  Available via UI 

2. Added/Updated contact via backend new/edit contact form
before patch: Single select only
after patch:  options can be multi-selected on the form and values appeared correctly on view contact after saving.

3.  Added/Updated contact via profile on create/edit mode
before patch: Single select only
after patch:  options can be multi-selected on the form and values appeared correctly on view contact after saving profile.

4. Front End Contribution form
before patch: Single select only
after patch:  options can be multi-selected on the form and values appeared correctly on view contact and also on Confirm , Thankyou and receipt.

5. Front End Event registration form
before patch: Single select only
after patch:  options can be multi-selected on the form and values appeared correctly on view contact but did NOT appear on Confirm , Thankyou screen and receipt. (but was saved against the contact)

6. Search
6.a Report
before patch: worked
after patch: Not working when more than one option is selected in field criteria

6.b Advance 
before patch: Not working when more than one option is selected in field criteria 
after patch: Not working when more than one option is selected in field criteria

7. Views 
- Fields
before patch: worked
after patch: worked

-- filter
before patch: worked
after patch: Not working when more than one option is selected in field criteria

**Comment by colemanw** [comment]
@pradpnayak thank you for the testing. I think we are in the home-stretch here. Are you able to patch any of those issues you found?

**Comment by eileenmcnaughton** [comment]
@pradpnayak my take on your review is that with this PR the new feature does not work everywhere - but not that it is worse anywhere - which would make it mergeable & follow up improvements 'patch welcome' - what is your take?

**Comment by pradpnayak** [comment]
Yes, please merge the PR, and will try to push PR for bugs in coming days

**Comment by eileenmcnaughton** [comment]
thanks @pradpnayak

**Comment by magnolia61** [comment]
Nice one. Would my issue https://lab.civicrm.org/dev/core/-/issues/465 be related?

**Pull request merged**
