### PR TITLE
(dev/core#944) Report doesn't show value for disabled options in results

### PR DESCRIPTION
**Pull request by yashodha**
Overview
----------------------------------------

Steps to replicate:

* Create a contribution with custom data *Donor Information* with field *How long have you been a donor?* with seleted option *Less than 1 year*

* Disable *Less than 1 year* option.

*The value is displayed in report result.

 The option should still be present in report results though not on edit/create screens.

Before
----------------------------------------
The value is **not** displayed in report result.

After
----------------------------------------
The value **is** displayed in report result.

Comments
----------------------------------------
The option should still be present in report results though not on edit/create screens.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
* General standards
    * [`r-explain`] __PASS__
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __PASS__
* Developer standards
    * [`r-tech`] __PASS__
        * I see the getOptions() function is already called with context="search" (which would previously have been ignored) from a couple places via the various places that call CRM_Core_BAO_CustomField::addQuickFormElement(), and so it seems like this affects those, e.g. find contributions, profile search, etc. But I don't see any obvious problems, and for example on Find Contributions it also fixes the same problem there.
        * But just as a comment I'm wondering if there's something off about the context parameter to begin with because for example with or without the patch if you view an activity with a custom field that has a disabled option the field is blank, but I would expect it to still show you the value in view mode?
    * [`r-code`] __PASS__
    * [`r-maint`] __PASS__
    * [`r-test`] __Undecided__

**Comment by eileenmcnaughton** [comment]
@colemanw can you take a look at this - I don't know all the thinking around these contexts

**Comment by eileenmcnaughton** [comment]
@agh1 @Stoob @lcdservices @MegaphoneJon is this change controversial in your opinions? I can see the logic for it  but I feel like this may have been discussed before & I'm not sure if there were dissenters

**Comment by MegaphoneJon** [comment]
Sigh...unfortunately very controversial.  However, I think between all folks who have weighed in before, we're agreed that the status quo for "disabled" options doesn't work for many folks, and we need something else moving forward.

I gave this some thought today, and I like adopting the pattern from relationship permissioning: Convert the boolean `is_active` to an integer, with 0 and 1 retaining their meanings and 2 meaning "Read only/frozen".  E.g. for option lists (the most important of several entities that could benefit here) it means, "You may not pick this option for new records, but it will appear as a search/filter option where applicable, and editing a record that has this value won't fail to save (which it does when `is_active` is `0`).

I know that's more work than what's suggested here, but it could be picked off in chunks.  Since this would be a new metadata option the code could be centralized.

**Comment by lcdservices** [comment]
I agree with @MegaphoneJon -- it's been controversial. I like his proposal, though I suspect that would be a significant level of effort, and would be concerned that it creates complexity in what is otherwise a fairly simple concept (enabled/disable). The distinction that proposal is making is between something that is unavailable (disabled) for selection but the data is preserved and available for searching/reporting -- vs. something that is not available at all. But if you truly want an option to be unavailable completely, wouldn't you just delete it? That's less nuanced, and Jon's proposal provides a useful middle ground. But I'm not sure it's a broad enough use case to merit inclusion in core.

Because the context is backend reporting, my inclination is to say the change as proposed is safe and useful (and the "simple" solution). Maybe the more nuanced and refined approach could be handled in an extension?

**Comment by Stoob** [comment]
I think this proposal is attempting to fix a regression.  About a year ago we discussed disabled field options and how they **are**:
-  visible both on a contact and in results/reports
but **are not**:
- select-able as a filter 
- enter-able as new data
That has been longstanding (as long as I can remember) behavior in Civi.  Apparently recently that has changed and this proposal is attempting to change it back.

@MegaphoneJon proposal is even more useful behavior than what used to be and actually makes sense.  But we should still be mindful of how the change in search-ability of disabled fields might affect some users.  I don't think an extension is necessary - this is a core issue.

**Comment by MegaphoneJon** [comment]
@Stoob - I recall that conversation differently, do you have a link to it?

My sense is that this was changed intentionally, and there's a very good argument that this is correct behavior.  I suppose we could also do a `git bisect` to find out which commit changed it, and look at the notes.

We can also merge it and see if anyone complains about the new behavior, but that feels a bit cavalier.

**Comment by Stoob** [comment]
I found it @MegaphoneJon https://lab.civicrm.org/dev/core/issues/19 including my testing on 4.6

**Comment by eileenmcnaughton** [comment]
@yashodha I'm  going to  close  this out because it's stale & it also can't be reviewed until  we are clear that it's 'concept-approved' -  so gitlab  is a better  place for that

**Pull request closed without merging**
