### PR TITLE
Ensure editable buttons don't sit underneath other page elements.

### PR DESCRIPTION
**Pull request by torrance**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw this passes my QA - which went something along the lines of "Do I know anything about this? No. Who do I ask about things like that? Ah I ask Torrance. Who submitted the PR? Torrance". 

However leaving for now it in the hope you might see it & confirm your pure joy with this PR.

**Comment by colemanw** [comment]
Thanks @torrance for this.
Maybe this is the right fix, but z-index hacks never bring me joy :(
The trouble with setting the z-index for one element on the page is that it starts an arms-race with who gets to be on top, and gets a bit absurd at the end (the z-index of the civi menu is 99999 or so).
What other page elements were being a problem exactly?

**Comment by torrance** [comment]
@colemanw If you want to watch Pete Davis' description of the bug here: http://quick.as/jznki9w6q

But basically, this isn't an arms race — it's raising the buttons above subsequent page elements which don't need a z-index applied.

**Comment by colemanw** [comment]
Thanks, the video helps.

**Comment by AkA84** [comment]
I can confirm that the issue is fixed by the PR, the tick button is clickable without the pencil icon below getting in the way

I did however noticed that visually you have the same problem (the pencil icon appearing above the tick button) when you actually submit the new value

test

This is due to the fact that the class `.crm-editable-saving`, which is applied to `.crm-editable` on submit, has `opacity: 0.8`, thus making the button appearing underneath the pencil icon as if there was still a `z-index` problem.

Not sure if this needs to be fixed, but thought it was worth pointing it out

**Comment by totten** [comment]
It sounds like it's agreed that this is an improvement over status quo. A follow-up to fix the other concern would be great, but there doesn't seem to be much cost to accepting it.

Thanks all for writing+reviewing!

**Pull request merged**
