### PR TITLE
dev/core#650 Use popups for links

### PR DESCRIPTION
**Pull request by chamilwijesooriya**
Overview
----------------------------------------
[GitLab Issue 650](https://lab.civicrm.org/dev/core/issues/650)

Before
----------------------------------------
* Membership and Recurring Contribution links opened as separate pages
## Steps to reproduce:
1. Create a recurring contribution manually
```php
$result = civicrm_api3('ContributionRecur', 'create', [
    'contact_id' => contact_id_of_your_choosing,
    'amount' => 50,
    'frequency_interval' => 1,
]);
```
2. Create a membership
3. Link the recurring contribution to the membership
```php
$result = civicrm_api3('Membership', 'create', [
    'id' => id_of_the_membership,
    'contribution_recur_id' => id_of_the_recurring_contribution,
]);
```
4. View the membership and click on recurring contribution link
membership

5. View the recurring contribution and click on membership link
recur

After
----------------------------------------
* In templates/CRM/Contribute/Page/ContributionRecur.tpl added class `crm-popup` to the hyperlink in following code block
```
{if $recur.membership_id}
<tr>
    <td class="label">{ts}Membership{/ts}</td>
    <td><a class="crm-hover-button" href='{crmURL p="civicrm/contact/view/membership" q="action=view&reset=1&cid=`$contactId`&id=`$recur.membership_id`&context=membership&selectedChild=member"}'>{$recur.membership_name}</a></td>
</tr>
{/if}
```

* In templates/CRM/Member/Form/MembershipView.tpl added class `crm-popup` to the hyperlink in following code block
```
{if $contribution_recur_id}
<tr>
    <td class="label">{ts}Recurring Contribution{/ts}</td>
    <td>
        <a class="crm-hover-button" href='{crmURL p="civicrm/contact/view/contributionrecur" q="reset=1&id=`$contribution_recur_id`&cid=`$contactId`&context=contribution"}'>View Recurring Contribution
        </a>
    </td>
</tr>
{/if}
```

### CODE REVIEW

**Comment by chamilwijesooriya** [comment]
@colemanw sorry for that. Updated the PR

**Comment by mattwire** [comment]
@chamilwijesooriya I've tested this and I'm not sure it quite does what you describe.

* If you open one of the pages above as a separate page the links will open as popups - this is an improvement and I would be happy for this to be merged.
* However, when you view one of the pages above in a popup and THEN click the link it is opened as a page and the popup is closed - did you intend for that?

**Comment by chamilwijesooriya** [comment]
@mattwire I'm not sure about your 2nd observation, 'cause it works the same as 1st for me. 
It should be working as normal popups in civi, on top of each other.

**Comment by mattwire** [comment]
> It should be opening as normal popups in civi, on top of each other.

For me the crm-popup seemed to be removed when loaded via a popup.  I added it via the browser console to test but don't really like the popups on top of each other - we don't do that anywhere else.  @colemanw The right thing to do I think is to load the link in the *same* popup but that goes a little beyond my popup/js foo?

**Comment by chamilwijesooriya** [comment]
@mattwire in that case I'm not sure what else to do. I just followed what's mentioned here under CRM.popup https://docs.civicrm.org/dev/en/latest/framework/ajax/

**Comment by chamilwijesooriya** [comment]
It seems to replace the existing popup if I use the class `action-item` instead of `crm-popup`. Any thoughts @mattwire ?

**Comment by colemanw** [comment]
I've re-tested this and the new `action-item` class does the trick perfectly. It now opens within the same dialog, and clicking done brings you back to the membership record. Thanks @chamilwijesooriya!

**Comment by chamilwijesooriya** [comment]
Cheers

**Pull request merged**
