### PR TITLE
CRM-21764: Recurring Events without Price Set fail to save

### PR DESCRIPTION
**Pull request by agilewarealok**
Overview
----------------------------------------
**Steps to reproduce:**

1. Create a recurring event with a bit of recurrence
2. Edit a specific event, update any field, such as the event description text field
3. Save, select "only this event"

Before
----------------------------------------
Nothing happens, Event is not really saved. CRM/Core/Page/AJAX/RecurringEntity.php::updateModeAndPriceSet fails because it returns an empty array, causing the save action to fail without any errors or notices.

After
----------------------------------------
We update price set only if we have any which results in expected response from  updateModeAndPriceSet of CRM/Core/Page/AJAX/RecurringEntity.php. Now event details are getting saved as expected.

_Agileware Ref: CIVICRM-831_

---

 * [CRM-21764: Recurring Events without Price Set fail to save](https://issues.civicrm.org/jira/browse/CRM-21764)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by jusfreeman** [comment]
@eileenmcnaughton good to merge?

**Comment by eileenmcnaughton** [comment]
I haven't had time to test yet :-(

I did spot one thing I think @agilewarealok needs to fix - can you address the file permissions - you shouldn't be changing them. I use 
```
git config core.filemode false
```
for that - either globally or in the repo

**Comment by agilewarealok** [comment]
@eileenmcnaughton 

Sure I've updated the permissions for this PR and will take care of it in future.

Thanks!

**Pull request merged**
