### PR TITLE
CRM-21278: Enable Logging leads to error on non-archive server

### PR DESCRIPTION
**Pull request by jitendrapurohit**
Overview
----------------------------------------
Enabling logging on a non-archive engine fails to an error

Before
----------------------------------------
Fatal error is displayed If logging is enabled on a non-archive MariaDB.

After
----------------------------------------
Log tables is created with innodb instead of Archive engine.

Technical Details
----------------------------------------
This checks if an archive engine is present and creates log tables accordingly.

Comments
----------------------------------------
I see some logging enhancements were made as a part of https://github.com/civicrm/civicrm-core/pull/7988 where it seems to convert all archive engine tables to innodb using updatelogtable api. Should we also change the default engine for the log tables directly to be created with InnoDB?

    $engine = strtoupper(CRM_Utils_Array::value('engine', $this->logTableSpec[$table], 'InnoDB'));

instead of the checks done in this PR?

---

 * [CRM-21278: Enable Logging leads to error on non-archive server.](https://issues.civicrm.org/jira/browse/CRM-21278)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@jitendrapurohit i think there has been some long term discussion on this but i can't remember where it got to. it might be worthwhile emailing the dev list and asking for opinions. I know that archive tables are bit more brittle than INNODB but do take up significantly less space

**Comment by MegaphoneJon** [comment]
https://civicrm.org/blog/eileen/who-did-what-when

**Comment by jitendrapurohit** [comment]
I'm not sure what the conclusion is. Basically it should depend on the user of how he/she might need to specify the engine? Moreover, this PR concentrates on building the log tables with InnoDB ONLY IF the archive engine is not present. For eg: [latest version of MariaDB](https://mariadb.com/kb/en/library/archive/) does not include this by default. 

@eileenmcnaughton @seamuslee001 Do you think considering a check makes sense here? OR maybe I can update this by throwing a formrule instead of a DB error similar to "Logging cannot be enabled as ARCHIVE engine is not present."?

**Comment by mlutfy** [comment]
I don't mean to armchair, but considering that logging is rather complex and is used/supported by a small group of users, I don't think that we should support two types of engines for that feature (unless there is a good technical reason to do so).

Enabling the archive engine is rather easy, so I don't think it's too much to ask to admins? (i.e. I support the 2nd option you propose: to show a warning to admins when they try to enable logging)

**Comment by eileenmcnaughton** [comment]
I would probably agree about a graceful fail rather than 'just handling it' - we should probably suggest they enable archive on their server or install https://github.com/eileenmcnaughton/nz.co.fuzion.innodbtriggers to switch to INNODB tables.

**Comment by jitendrapurohit** [comment]
ok - as we don't want to use innodb instead of archive, will close this for now.

**Comment by adam-devapp** [comment]
This was helpful to enable archive format on MariaDB:

**Install Archive plugin**

MariaDB> INSTALL PLUGIN archive SONAME 'ha_archive.so';

**Show Plugins**

MariaDB> show engines \G

Hopefully this will help someone else.

**Pull request closed without merging**
