### PR TITLE
[NFC] Extract case activity permission check.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Function extraction for code legibility - no functional change

Before
----------------------------------------
long block of code

After
----------------------------------------
shorter block of code

Technical Details
----------------------------------------
This is part of refactoring to address duplicate queries for permission checks - no change
in this commit other than an extraction

Comments
----------------------------------------

### CODE REVIEW

**Comment by pradpnayak** [comment]
The changes look good to me. However do we need to perform checks one more time for CiviCase at 2755?

**Comment by eileenmcnaughton** [comment]
@pradpnayak I don't think I've removed any checks - I did move them higher up in the function as well as extracting - but that should be no-change

**Comment by pradpnayak** [comment]
@eileenmcnaughton I meant  line 2755 is doing same checks for Civicase for defined permission at https://github.com/civicrm/civicrm-core/blob/ac4b9bc366647f1c1577d9786162a1db4ffe4f2e/CRM/Activity/BAO/Activity.php#L2721 .

Since you are already checking for CiviCase than isn't it safe to remove those permission from $compPermissions array?

**Comment by eileenmcnaughton** [comment]
@pradpnayak so bigger picture what I think will work better is to generate a list of activity types that the contact can access before the main query & then setting an activity_type_id filter before the query runs - the current methodology is broken for getcount :-( and painfully slow under some circumstances.

I kinda need to resolve this https://lab.civicrm.org/dev/core/issues/454 to be able to do that part - but I figure in the meantime I can clean up the functions a bit to make the next change easier.

**Comment by pradpnayak** [comment]
@eileenmcnaughton make sense now. This is good to merge but would be great if @colemanw have a look at this once since he has better sense on Check Permissions and CiviCase.

**Comment by eileenmcnaughton** [comment]
Thanks @pradpnayak

**Comment by eileenmcnaughton** [comment]
test this please

**Pull request merged**
