### PR TITLE
dev/core#4753 Afform - Fix boolean options

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Fixes default values in yes/no radio fields in FormBuilder.

See steps to reproduce in https://lab.civicrm.org/dev/core/-/issues/4753

Technical Details
----------------------------------------
The previous code was taking care to cast option values to true/false for boolean fields, but this was then undone by the two-way binding on the field. By breaking the binding we can update the values in a way that won't be undone by the Angular bindings.

### CODE REVIEW

**Comment by colemanw** [comment]
@mattwire this definitely needs r-run with various field types as it potentially impacts Select, ChainSelect (e.g. State/Province), Checkbox & Radios.

**Comment by JSProffitt** [comment]
It seems like this solution is a little problematic, as it attempts to force a checkbox to act as a radio button. The semantic use of the HTML control is especially important for users that would depend on accessibility aids. It would be better to fix the radio button alone to support the "two options, choose only one" or the "multiple options, choose only one" use cases as a radio button with the boolean value. It's only binding the label and value that is creating the error.

**Comment by colemanw** [comment]
Hi @JSProffitt thanks for reviewing - could you please describe how to reproduce the bug you found with this PR and I'll try to correct it.

**Comment by mattwire** [comment]
test this please

**Comment by mlutfy** [comment]
Works for me.

Tested this on a form with pretty much everything: chain-select (state-province), radios, yes/no (including one that was causing problems if we select 'no'), file uploads, contactRef autoselect, multiple address blocks, kitchen sink, unicorns, etc.

**Comment by mattwire** [comment]
@mlutfy Can you tell me where you found the unicorn? I'd like to add one to one of my forms.

**Pull request merged**
