### PR TITLE
[TEST] dev/core#1046 - tests for case type edit screen

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
I've pulled out the passing tests from https://github.com/civicrm/civicrm-core/pull/15367 that could be merged since they don't depend on any changes.

Before
----------------------------------------
It won't stop raining. Squirrels eating my food.

After
----------------------------------------
Tests.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
more test is more good

**Comment by demeritcowboy** [comment]
So it stopped raining around the same time this was merged. That can't be coincidence. The squirrels are still there though, but maybe that requires some E2E tests...

**Comment by eileenmcnaughton** [comment]
And the clouds parted

**Pull request merged**
