### PR TITLE
dev/core#4951 Remove text version of online event receipt in 5.69 - known to cause errors with Smarty3

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
This is already removed in 5.70 &
our upgrade script will update any un-modified versions of this to be empty based on this change
https://lab.civicrm.org/dev/core/-/issues/4951

### CODE REVIEW

**Comment by totten** [comment]
This confused me for a moment. Just quick notes for record -- this only removes the *plain-text* rendering.  The HTML rendering is separate. And comparing the content of 5.69/5.70:

 `ls -l xml/templates/message_templates/*_text.tpl`

* 5.70 is where you see a huge number of blanked-out  plain-text templates
* 5.69 is where you see a couple of of blanked-out plain-text templates

So the plot-arc of blanking-out the plain-text templates is a little longer, and I don't remember all the details, but Eileen appear to be saying that it's OK to move this back a little earlier in the phase-out.

**Comment by eileenmcnaughton** [comment]
Yeah - we basically started slowly & then picked up pace - one reason is likely to be that subtle changes in the layout will cause test fails so it was a bit of a slog to do this - jenkins will tell us....

**Comment by eileenmcnaughton** [comment]
the merge on pass is OK - it's getting it to pass! I'm not quite sure if there is any quick fix but it would suck to leave smarty 3 problems

I guess we could just remove the breaky code which is probably only this part

https://github.com/civicrm/civicrm-core/pull/29292/files#diff-0308db5d2dfbc986c85e0d58458d77f2eb3010d8ce7504890ef8b76b73b43485L151-L167

There is another part where there is a + in the template -but I don't know if causes crashes too (depends on the type of the variable)

Alternatively we could mark those tests skipped in 5.69 - which might be OK since they are primarily run in master

Or there might be a way to get it to load the old version for the tests

Or we could go through all the fixes in master - on those tests - but I think it was a slog to get those right & might take a bit to backport

**Comment by demeritcowboy** [comment]
Or remove the status check suggestion to use smarty 3 in 5.69. People are upgrading to 5.69 because of the google thing, and then seeing the warning. Or downgrade it to blue.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy yeah maybe but there are security patches on Smarty3 & Smarty4 that are not applied to Smarty2 - so having spotted that today I'm working on the assuming that Smarty2 is likely to have security vulnerabilitys that 3 & 4 don't - so blocking people from addressing security issues because our tests are failing in ways that are not meaningful but just a bit of a dog to fix feels like the wrong priority

**Comment by demeritcowboy** [comment]
Looking at the tests that are failing, I'd be ok with marking them skipped in 5.69 (or ornery, so we could ignore?), even though it's an ESR release, to save having to make [this patch](https://github.com/civicrm/civicrm-core/pull/29269)

```diff
-$eileen->getSoul() ?? NULL;
+NULL
```

**Comment by eileenmcnaughton** [comment]
yeah - I'm glad you went for soul not sanity cos I think THAT test might already be Ornery

- I went for skip cos Ornery will still fail whenever Tim goes to do a new point release which will ocnfuse

**Comment by totten** [comment]
> ...there are security patches on Smarty3 & Smarty4 that are not applied to Smarty2 - so having spotted that today I'm working on the assumption...

Hrm, rabbit holes. Methinks you're forgetting something. Our last audit of v2 was in September 2023 (https://civicrm.org/advisory/civi-psa-2023-01-smarty-v2-audit) - we adapted one fix and affirmatively demonstrated that the others don't apply. (*I know because it took a few days to analyze all of them sufficiently.*) The last security patch advertised upstream was March 2023 (per https://github.com/smarty-php/smarty/security, https://github.com/smarty-php/smarty/releases). So the Sep 2023 results are current with official advisories. (Of course, if you have new information about something not on the disclosure list, then that would be good to know...)

**Comment by eileenmcnaughton** [comment]
@totten that's good to know - but still if we DO have smarty issues then we probably won't patch Smarty2 again so best people can get off it

**Pull request merged**
