### PR TITLE
Schema - Add 'default_fallback' for fields

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
This takes a hacky thing and makes it metadata-driven

Before
----------------------------------------
Our `writeRecord` code guesses about filling fields like "frontend_title" with a fallback value.

After
----------------------------------------
Instead of guessing based on the field name, we add metadata to the schema explicitly describing the default fallback value.

### CODE REVIEW

**Comment by monishdeb** [comment]
Looks good. Tested on local and there's is a test coverage for the new cool evaluator `default_fallback`. Merging this,

**Comment by monishdeb** [comment]
@colemanw at some point I think these special attributes needs to be documented somewhere or already is?

**Comment by monishdeb** [comment]
And can we extend default_fallback to have mixed values (not always column name(s) but fn name too?) like say Group.created_id is defaulted to logged in contact ID during create so can we do:
```
Group.entityType.php 
<?php
....

  'created_id' => [
    ...
    'default_fallback' => 'CRM_Core_Session::getLoggedInContactID',
  ]
  ```
  Or may be another attribute say `default_callback` ?

**Comment by colemanw** [comment]
@monishdeb `default_callback` is a good idea! I think we could save a lot of BAO code that way.

**Pull request merged**
