### PR TITLE
Unit test for PR#16603

### PR DESCRIPTION
**Pull request by jitendrapurohit**
Overview
----------------------------------------
Unit test for changes made in #16603  @mattwire 

Build process will fail until the main PR is merged.

### CODE REVIEW

**Comment by yashodha** [comment]
test this please

**Comment by yashodha** [comment]
@jitendrapurohit test failure is related. Can you please check this?

**Comment by jitendrapurohit** [comment]
@yashodha This is a unit test to test the change done in https://github.com/civicrm/civicrm-core/pull/16603 so it is meant to fail until that PR is merged :). @mattwire Can you pls move this commit into your main PR? We can then close this one and reduce the open PR count :)

**Comment by mattwire** [comment]
Thanks @jitendrapurohit I've moved this test into #16603

**Pull request closed without merging**
