### PR TITLE
core#1225 fix Event Info and Contribution Page Settings templates

### PR DESCRIPTION
**Pull request by MegaphoneJon**
Overview
----------------------------------------
This makes some changes to templates that should **not** be visible to end users, but makes the underlying HTML less ugly.

Before
----------------------------------------
Elements are positioned by use of this line:
```html
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
```

After
----------------------------------------
We use sane rendering techniques to position our elements, and use the same positioning techniques on identical elements.

Technical Details
----------------------------------------
There's almost no technical detail to mention.

Comments
----------------------------------------
This started out as my adding a class to a table cell that had none on the event info template, but when I saw what the contribution page template looked like I expanded my scope to remove something rather hideous.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon I added a sig-markup label to allow Compucorp to identify things that could affect shoreditch

**Comment by mlutfy** [comment]
How long should we wait before merge? Themes can do QA during the RC period?

**Comment by seamuslee001** [comment]
@mlutfy i don't think we should wait i'm going to merge this

**Comment by eileenmcnaughton** [comment]
@mlutfy @seamuslee001 I don't actually think we should wait when we give that label - I didn't merge it earlier because I hadn't reviewed it

**Pull request merged**
