### PR TITLE
CRM-20915: Creating credit card registration for event stores payment method as check

### PR DESCRIPTION
**Pull request by monishdeb**
* [CRM-20915: Creating credit card registration for event stores payment method as check](https://issues.civicrm.org/jira/browse/CRM-20915)

### CODE REVIEW

**Comment by Edzelopez** [comment]
Works as expected after patch.

**Comment by eileenmcnaughton** [comment]
@monishdeb @Edzelopez this works & makes sense but I really wanted to add tests on this. Unfortunately there were no existing tests on this form :-( 

However, I created a test, (which requiring some extraction)  here #10725 for that class.

The test DOES demonstrate this bug with the addition of one line to the bottom of the test class

    $this->assertEquals('Debit Card', $contribution['payment_instrument']);

I have left that line out because I wanted to submit it passing. If you can review & confirm the extraction & get that merged and then add that line to this PR then I will be happy to merge this pr

**Comment by monishdeb** [comment]
@eileenmcnaughton I have reviewed and cherry-picked the commit from #10725. Also added that extra line. Please have a look!

**Comment by eileenmcnaughton** [comment]
@monishdeb great - I'm happy to merge this - as long as you confirm that you did take a look at my patch & make sure I didn't do anything dumb (now this PR has both our code & I can confirm I am happy with & have reviewed the code you wrote)

**Comment by eileenmcnaughton** [comment]
@monishdeb this is ok to merge from my pov - do you want to confirm my part looks ok to you?

**Comment by monishdeb** [comment]
@eileenmcnaughton yup just did a quick test on my local. Did event registration w/o live mode and it works fine, didn't cause any unintended regression.

**Pull request merged**
