### PR TITLE
Move FirstData payments into a core-extension

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
 Move Legacy FirstData processor to an core-extension
    
    This is one of a handful of processors that is in core but we believe is no longer in use.
    

Before
----------------------------------------
FirstData is in main CRM_Core_Payment folder, but not enabled on new installs

After
----------------------------------------
FirstData is moved to a core-extension, enabled only on upgrade for sites with existing payments linked to processors of FirstData type. Extraneous FirstData payment processor records removed on other sites.

Technical Details
----------------------------------------
Upgrade script not yet written but the plan is
    1) Look for any instances of PaymentProcessors linked to the FirstData class. If none exist
    delete the FirstData row from the civicrm_payment_processor_type table
    2) Look for any financial_trxn records linked to any existing FirstData payment processor instance
    (recurrings are not possible here). If none exist delete from civicrm_payment_processor & civicrm_payment_processor_type
    3) If there IS a processor row then install the extension. The install makes no DB changes as this
    extension is only intended for those who already depend on it existing. As such it is also hidden.
    

Comments
----------------------------------------
    Planning for complete removal from core is punted for now. However, we should start to see stats on whether it is enabled  for anyone over time. We could use status checks in the extension for messaging, once we have it.

### CODE REVIEW

**Comment by seamuslee001** [comment]
jenkins re test this please

**Comment by mattwire** [comment]
Lot's of style warnings. Most of these are in files that needs fixing. However, there are some in autogenerated files (*.civix.php) and you don't have `Upgrader/Base.php` but that fails too. @seamuslee001 @totten @MikeyMJCO Can we tweak the style checker to ignore filenames which match a pattern?

**Comment by eileenmcnaughton** [comment]
We should fix civix to pass

**Comment by MikeyMJCO** [comment]
> We should fix civix to pass

Agreed, Civix should be generating lint/style checker compatible output.

**Comment by mattwire** [comment]
> Agreed, Civix should be generating lint/style checker compatible output.

Agree, just not sure if anyone is planning on fixing civix any time soon?

**Comment by eileenmcnaughton** [comment]
Well - this is hardly urgent - I don't think we can bypass style checking to get it merged - whether we use civix or not. But if this is part of a process of moving things out of core then tackling the things it throws up is more the point than the actual PR  /  moving out FirstData

**Comment by mattwire** [comment]
Sure, I flagged as an issue with eventcartext (where I fixed the style issues before submitting) and it must have been an issue with sequentialcreditnotes too?

**Comment by eileenmcnaughton** [comment]
Yeah I guess I fixed for sequential credit notes. I don't remember so it probably was quick

**Comment by eileenmcnaughton** [comment]
I'm going to close this for now & focus on doing the pre-ceding steps first - namely - fix the processor to use doPayment, checkout the style issues & figure out the upgrade steps

**Pull request closed without merging**
