### PR TITLE
dev/user-interface#48 Update CiviCRM logo

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
dev/user-interface#48 Update CiviCRM logo

https://lab.civicrm.org/dev/user-interface/-/issues/48

Before
----------------------------------------
Old logo used with 'empowered by' - e.g invoice & @joshgowans told us to change it a year ago

After
----------------------------------------
new logo

Technical Details
----------------------------------------
I used the image @joshgowans uploaded but note that the image size is greater - does this matter?

image

Also there an svg file - perhaps @vingle knows what to do with that

image

Comments
----------------------------------------

### CODE REVIEW

**Comment by vingle** [comment]
The SVG *should* be smaller, and higher-resolution at any screen-size. Will take a look Monday.

**Comment by eileenmcnaughton** [comment]
thanks @vingle

**Comment by vingle** [comment]
There is an SVG of the new logo which is 7.87kb: https://lab.civicrm.org/marketing/marketing-assets/-/blob/master/logo/CiviCRM-logo-2019-F2.svg?ref_type=heads. I'd suggest using only that instead of the PNG as it will look high res at all screen sizes.

Or to stick with the PNG, I think that one wasn't brilliantly compressed - there's smaller 99px and 198px(2x) versions here. Let me know if you want me to make a new PR, not sure how to modify a PR.

Civi99
civi198

**Comment by eileenmcnaughton** [comment]
@vingle yes please to your offer of doing a new PR - def not in my wheelhouse here

**Comment by vingle** [comment]
@eileenmcnaughton added one here https://github.com/civicrm/civicrm-core/pull/30486

**Comment by eileenmcnaughton** [comment]
thanks heaps @vingle

**Comment by vingle** [comment]
On reflection and after some good discussion with Rich, realise you were right - and this was the best approach for quickly changing the logos without breaking anything else. So can we go back to this original PR, but with a small .png file and a new .svg file? Improving the CSS to load an SVG instead of PNG can happen at theme level / later.

If I attach them to the comment I think Github re-renders them, but maybe you could take them from [this branch](https://github.com/vingle/civicrm-core/tree/update-logo/i)/or the above pr? Or would you prefer I just update my PR and leave the CSS intact?

**Comment by eileenmcnaughton** [comment]
@vingle can you just remove the changes you don't want from your branch & re-open?

**Comment by vingle** [comment]
@eileenmcnaughton have done - https://github.com/civicrm/civicrm-core/pull/30486 - only the image changes. 

Am afraid there's now 9 commits there (kept trying to get the SVG aspect ratio the same to minimise breakages) – and I can't squash them via the webGUI as that's where I did the whole thing.

**Comment by eileenmcnaughton** [comment]
I'll live with the 9 commits - appreciate it

**Pull request closed without merging**
