### PR TITLE
CRM-20264: handle submission of CC type and number during 'record payment'

### PR DESCRIPTION
**Pull request by monishdeb**
* [CRM-20264: Store CC type and last 4 digits from Contribution form](https://issues.civicrm.org/jira/browse/CRM-20264)

### CODE REVIEW

**Comment by monishdeb** [comment]
@eileenmcnaughton there is a miss - while 'Record Payment' form submission ```card_type_id``` is not recorded in financial_trxn table. Fixed it in this PR.

**Comment by eileenmcnaughton** [comment]
@monishdeb 2 things

1) should this be against the rc
2) there is a huge amount of confusion about the different parameter arrays in play but my feeling looking at the AbstractEditPayment class is that we are moving TOWARDS using $this->_params & perhaps we should back up & use $this->_params rather than passing in $submittedValues & then overwriting it. I think @pradpnayak's PR actually does that. We merged the tests @pradpnayak wrote which gives some comfort :-)

**Comment by colemanw** [comment]
Ok I've opened up #10228 against the RC.

**Comment by JoeMurray** [comment]
@monishdeb , can you test changing https://github.com/civicrm/civicrm-core/pull/10207/files#diff-c47ce3f6314a68836ccb5ea3cf7105beR370 on the new PR being created by coleman against rc so that it passes $this->_params ? if it works, let's follow @eileenmcnaughton 's intuition.

**Comment by monishdeb** [comment]
@JoeMurray I have made the changes in the new PR https://github.com/civicrm/civicrm-core/pull/10228 and is merged by Eileen.

**Pull request closed without merging**
