### PR TITLE
CRM-19454 Fixed unset of localised columns fails in some custom searches.

### PR DESCRIPTION
**Pull request by deepakaryan1988**
Fixed unset of localised columns fails in some custom searches.

---
- [CRM-19454: Unset of localised columns fails in some custom searches](https://issues.civicrm.org/jira/browse/CRM-19454)

### CODE REVIEW

**Comment by monishdeb** [comment]
@deepakaryan1988 you need to create PR against master as I can see the PR is pointing against 4.7.10-rc

**Comment by monishdeb** [comment]
Closing this PR, please create a new PR against master branch

**Comment by yashodha** [comment]
@deepakaryan1988 this looks lot like #9170

**Comment by deepakaryan1988** [comment]
@yashodha sure creating a PR against master branch.
Thanks!

**Comment by deepakaryan1988** [comment]
Here is the new PR
https://github.com/civicrm/civicrm-core/pull/9175

**Pull request closed without merging**
