### PR TITLE
dev/core#5307 Check for group array with IN clause on the delete form

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
5.75 port of https://github.com/civicrm/civicrm-core/pull/30464

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit @stesi561 are you able to confirm this port is still working OK?

**Comment by stesi561** [comment]
I'll try and get to this this afternoon/tomorrow.

**Comment by seamuslee001** [comment]
any update @stesi561 ?

**Comment by seamuslee001** [comment]
Merging as I think this is better in than out

**Pull request merged**
