### PR TITLE
CRM-16527 - Hide credit card section in membership contribution form

### PR DESCRIPTION
**Pull request by Kajakaran**
1. Membership contribution form has set-up with membership-types rather than membership-price sets in the membership setting tab 
2. When 100% discount applied on membership, form should hide credit card section, at the moment, it is not happening. 

Please refer the issue raised here. 

https://github.com/dlobo/org.civicrm.module.cividiscount/issues/86

---
- [CRM-16527: Hide credit card fields in membership contribution form.](https://issues.civicrm.org/jira/browse/CRM-16527)

### CODE REVIEW

**Comment by kurund** [comment]
@Kajakaran I think PR has 3 fake merge commits. Can you please cherry-pick genuine commits and submit a new PR

**Comment by Kajakaran** [comment]
@kurund 

Pls find the new PR https://github.com/civicrm/civicrm-core/pull/5873

**Comment by davecivicrm** [comment]
Closed in favor of https://github.com/civicrm/civicrm-core/pull/5873

**Comment by bcobin** [comment]
With Civi 4.6.10 and CiviDiscount 3.2, this is broken again. I do not want to do an upgrade to 4.7 here and this is functionality the client really needs - what do I do?

**Pull request closed without merging**
