### PR TITLE
CRM-20058, added submit credit card payment link

### PR DESCRIPTION
**Pull request by pradpnayak**
----------------------------------------
* CRM-20058: Add Credit Card Payment link for partially paid contribution
  https://issues.civicrm.org/jira/browse/CRM-20058

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Do we need to only do this for sites with backoffice processors like we do on backoffice contribution pages - ie.  CRM_Financial_BAO_PaymentProcessor::hasPaymentProcessorSupporting(array('BackOffice')

**Comment by JoeMurray** [comment]
@pradpnayak , I agree we should test along the lines that Eileen suggests. @eileenmcnaughton where would one find the list of values of things like 'BackOffice' ? I'm not sure of exact manner, but it would be good to see that referenced somewhere in the docblock if not in the signature itself.

**Comment by eileenmcnaughton** [comment]
There are a bunch of functions on CRM_Core_Payment that define the capabilities of the processor. 

This function

```

  /**
   * Is there a processor on this site with the specified capability.
   * @param array $capabilities
   *
   * @return bool
   */
  public static function hasPaymentProcessorSupporting($capabilities = array()) {
    $result = self::getPaymentProcessors($capabilities);
    return (!empty($result)) ? TRUE : FALSE;
  }
```
checks for capabilities such as 

supportsLiveMode
supportsTestMode
supportsFutureRecurStartDate
supportsCancelRecurring
supportsRecurContributionsForPledges(

& a few others
I could add the above to the doc block for that function, but I wouldn't want it to be seen as a complete list

**Comment by eileenmcnaughton** [comment]
here you go https://github.com/civicrm/civicrm-core/pull/9941

**Comment by Edzelopez** [comment]
Hi @eileenmcnaughton 
I have added the check for backoffice credit card payments. Is this ready to merge?

**Comment by eileenmcnaughton** [comment]
Yep, thanks @Edzelopez

**Comment by eileenmcnaughton** [comment]
Actually @Edzelopez I guess the mode should not be set to live but figured out? ie. it could be test? This is merged & I'll close & leave it to you to add another ticket for that if you agree

**Pull request merged**
