### PR TITLE
dev/mail#79 - Fix MS Exchange/IMAP. Use OpenID Connect.

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

This addresses a bug (https://lab.civicrm.org/dev/mail/-/issues/79) where the OAuth2 implementation does not work with MS Exchange Online's IMAP.

Before
----------------------------------------

When requesting a token for the `ms-exchange` provider, Civi requests multiple permissions, including  `User.Read` (to determine the default email address) and `IMAP.AccessAsUser.All` (to connect the relevant mailbox).

Thanks to @demeritcowboy's debugging, we can see there is a problem in Microsoft's services: it treats these permissions as mutually-exclusive. (If you have `User.Read` permission, then `IMAP.AccessAsUser.All` does not work.)

After
----------------------------------------

Stop requesting `User.Read` permission. Consequently, we can't read the default email address from `https://graph.microsoft.com/v1.0/me`. Instead, we can use OpenID Connect to determine the email address.

Comments
----------------------------------------

Tested in local builds of 5.32.beta with both:

* https://github.com/totten/oauth2-imap-demo - Complete the consolidated pageflow, get some real IMAP data
* `dmaster`  - Apply patch and flush caches. Register a new "Mail Account" and run "Save & Test".

### CODE REVIEW

**Comment by seamuslee001** [comment]
@totten should this be against the 5.32 branch?

**Comment by totten** [comment]
@seamuslee001 Yes, thanks for catching that. Switched it over.

**Comment by demeritcowboy** [comment]
* Yay it works.
* I'm still seeing User.Read showing up, and with the wrong scope, but since it comes at the end of the list and it's not being accessed it doesn't affect anything. I'm not sure where it's coming from - I also tried deleting the token/mail account and cleared caches and started again.
  * Oauth admin:
    scopes1 
  * Inspect:
    scopes2
* Also checked that google was still working (although still having refresh token acquisition problems for google but it's probably separate).
* Just a note regarding outlook.office`365`.com vs outlook.office.com - it looks like this [was changed in May](https://github.com/MicrosoftDocs/office-developer-exchange-docs/commit/9d5d6b8eac0e9ea3d2b1525c735baf11eadd6817) but without any explanation. They seem to be equivalent but yes seems office.com is the more current.

**Comment by seamuslee001** [comment]
I'm going to merge based on @demeritcowboy 's testing

**Pull request merged**
