### PR TITLE
Michaelmcandrew safe dbname

### PR DESCRIPTION
**Pull request by michaelmcandrew**

### CODE REVIEW

**Review by colemanw — CHANGES_REQUESTED** [review]
Looks like you've renamed the function `requireValidDBName` but not updated all the places that call it.

Also could you please update `CRM_Core_DAOTest::testRequireValidDBName`

**Comment by michaelmcandrew** [comment]
@colemanw. have updated the test - sorry for missing that. I don't think this function is called anywhere else.

**Review by colemanw — APPROVED** [review]

**Comment by colemanw** [comment]
Thanks @michaelmcandrew - was there a jira issue for this?

**Comment by michaelmcandrew** [comment]
@colemanw - it was a follow up of CRM-16617

**Pull request merged**
