### PR TITLE
Test data - set current domain version

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Replacement for #17734 - always ensure test run with the current domain version.

Before
----------------------------------------
Domains not set correctly.

After
----------------------------------------
Should be fixed.

Technical Details
----------------------------------------
I think the problem with #17734 is that it was fetching the version from the first domain, but that one was set to 2.2!

### CODE REVIEW

**Comment by colemanw** [comment]
retest this please

**Comment by seamuslee001** [comment]
retest this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
closing in favour of #17897

**Pull request closed without merging**
