### PR TITLE
Participant - Mark registered_by_id field deprecated

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Followup to #24167 which added a new field. This marks the old field as deprecated.

Technical Details
----------------------------------------
The old field stores a participant id. It's now deprecated in favor of the new created_id field which stores a contact id.

Comments
----------------------------------------
Note that `@deprecated` tag on a field doesn't really do anything functional, it's just a note to developers.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw I don't know that this is deprecated - it is still used functionally in some code to find the original participant record (in some of the receipting code I think - and I don;t think it is replaced by the other - they have different implications

**Comment by eileenmcnaughton** [comment]
This is how the `registed_by_id` is used (not necessarily the only way - but the one I'm currently aware of)

https://github.com/civicrm/civicrm-core/pull/24320/files#diff-1514ef8ee60c9afffee4761f7c65e56eeafd4ec9cf8e98b1c81225dd4a71e44eR31

**Comment by mattwire** [comment]
`registered_by_id` is quite well tangled up in a few things including the receipting code. It will likely be a while before we can stop using it. I think @colemanw intention here is to make it clear to developers that we should not use it for anything new?

**Comment by colemanw** [comment]
Ok maybe this PR is premature.

**Comment by eileenmcnaughton** [comment]
Hmm - I'm not sure it's just the PR is premature - I don't think we have a plan to remove it as it is not just tangled up - it's performing a functional purpose of associating participant records together - which is distinct from the contact association we have just added

**Pull request closed without merging**
