### PR TITLE
(dev/core/45) show image files inline when clicked instead of download

### PR DESCRIPTION
**Pull request by yashodha**
Overview
----------------------------------------
show image files inline when clicked instead of download

Before
----------------------------------------
Steps to replicate:

1. Create a note with an attached image file.
2. View the note and click the file.
3. It directly downloads the file.

After
----------------------------------------
Clicking the image file shows the file inline

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@guanhuan I feel sure I had someone at your end touching images & how they acted not that long ago - wanna assign a reviewer (one line patch so really it's a behaviour / logic check)

**Comment by yashodha** [comment]
test this please

**Comment by davialexandre** [comment]
For reference, these are the changes Eileen is talking about: https://github.com/civicrm/civicrm-core/pull/10883/files

Interestingly, we submitted this change exactly because we needed to be able to view images inline. Previously, CiviCRM would always download files and we added the `download` param so that we could tell it if we want the file to be download or not. After that, we made sure to add `download=0` to all files we wanted to be displayed inline.

What the changes in this PR do is that now it will be impossible to download images, even if I add `download=1` to the URL, which I think will be confusing.

Probably a better solution would be to do the same thing we did and make sure of adding `download=0` to any files you want to be displayed inline.

**Comment by eileenmcnaughton** [comment]
@yashodha looks like this needs to be changed per above

**Pull request closed without merging**
