### PR TITLE
dev/core#1584 Add function to specify whether payment processor requires email address

### PR DESCRIPTION
**Pull request by aydun**
See https://lab.civicrm.org/dev/core/issues/1584

### CODE REVIEW

**Comment by colemanw** [comment]
@aydun the style checker says there needs to be a blank line after your new function and before the class closing brace.

**Comment by eileenmcnaughton** [comment]
@aydun you are not thinking this needs to be called anywhere from core at this stage, only from webform for now - I think the comment block needs a lot more 'juice' or someone could legitimately remove this as 'unused'

**Comment by jaapjansma** [comment]
Betty and I are reviewing PRs and we came across this issue and we are wondering how we could test this PR functional and without any technical knowledge
@aydun can you help us with that by providing a step by step instruction on how to test this?

**Comment by aydun** [comment]
@eileenmcnaughton - freshly squeezed comment 'juice' added.  And a test!

@jaapjansma - good question... This adds a capability to payment processors but does not change anything visible in core.  To see the effect, you could:

1. Install CashPP, create a webform using a contribution page configured with CashPP and observe that it fails if no email address is provided.  
2. Then apply this PR and the corresponding webform_civicrm one and observe that the email address is no  longer required.  

Links are in the lab issue at the top of this PR.

... but the only reservation was the doc block so it may get merged before you do further testing!

**Comment by eileenmcnaughton** [comment]
The changes address my issues

**Pull request merged**
