### PR TITLE
CRM-17789 WIP 4.6 support for PHP 7 

### PR DESCRIPTION
**Pull request by seamuslee001**
* [CRM-17789: Support PHP 7](https://issues.civicrm.org/jira/browse/CRM-17789)

### CODE REVIEW

**Comment by yashodha** [comment]
test this please

**Comment by seamuslee001** [comment]
@yashodha this won't work without https://github.com/civicrm/civicrm-packages/pull/176 as a bare minimum but there is also https://github.com/civicrm/civicrm-packages/pull/171 needed for php7 support

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@jamienovick @jackrabbithanna This PR teamed with https://github.com/civicrm/civicrm-packages/pull/171 seems to make 4.6 work on a php7 install using buildkit

**Comment by jackrabbithanna** [comment]
@seamuslee001 Well although this PR doesn't touch a ton of files, its dependent PR sure does.  One of our main goals with supporting the LTS is to ensure stability.  This seems like a fairly drastic change with potential to have a regression.   It would be great to be able to run 4.6 on PHP7, but not at the cost of regressions.  Many clients that run 4.6 will be running it on servers with php 5.4 or 5.5, possibly even 5.3.x Jenkins hasn't finished its test as I'm writing this, lets see what it says.  I definitely don't want to be responsible for breaking the LTS, first release we involved with.  When i wearing my developer hat I'm not opposed to having it get in, but when i wear my businessman "keep the current clients happy" hat I get a little nervous.  I'm wondering how we can battle test this a little more stringently than for some other PRs. It makes me wonder if we should occasionally do rc versions for 4.6. Do you know what version of php the jenkins test runs against? I'd like to see it pass the entire test suite with the minimum required php version of 4.6.  I put this question to you for this PR: "Would you update CiviCRM with this PR merged in on your 5 most important client's production websites tomorrow, who happen to be running php 5.5?"

**Comment by seamuslee001** [comment]
@jackrabbithanna Yep totally with you I did this more as an experimental / ability to sort of point people saying hey you wanna try 4.6 on php7 you will need this and this but we think it might work but let us know kinda way

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by jackrabbithanna** [comment]
I'm definitely interested in what @guanhuan and Compucorp's thoughts are on this as well. I'm not sure what the power's that be would think of a 4.6-rc-php7 version that could be let out into the wild and battle tested for a while...even then those that would use it probably want to use it with php7 and not older versions. I vote we err on the side of caution, so not merging in the next release, keep it open but unmerged for now, figure out a way to battle test it some more. Perhaps we think of ways of making it accessible to people though....

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by jackrabbithanna** [comment]
We're considering this patch for inclusion into the LTS at some point this year (no rush).  @guanhuan let me know if you have any objections.  There would need to be a lot of testing.  We have one client that wants it, and more may come...so I'm thinking about making it happen for them (before merging) and letting it run in a production site for while.  Let this PR get some real world experience...

@seamuslee001 if you catch wind of anything related to this that breaks in 4.7 and needs fixing, let us know so we can make this a possibility for 4.6

**Comment by seamuslee001** [comment]
@jackrabbithanna i have ported some fixes around some port specifies and also some php7.1 fixes one specific one has been merged in master and 2 others haven't yet

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I think we should close this & track through JIRA until someone is wanting to put in  enough time to review this to the point of merge. Work won't be lost (I think in general old PRs that are not merge-ready should be closed & tracked through JIRA)

**Comment by jackrabbithanna** [comment]
This is something that we will want to do eventually, we're looking at php 7 support for 4.6 for sometime early next year, will close now, but we have this when that work begins

**Pull request closed without merging**
