### PR TITLE
CRM-18761 fix for dodgey date revert

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
- [CRM-18761: Revert function borks on datetime fields because they are formatted with dashes & colons etc](https://issues.civicrm.org/jira/browse/CRM-18761)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This refers to the situation where logging it enabled & a change with a date field (membership subscription) is reverted

**Comment by JoeMurray** [comment]
@josephlacey would you be interested in QA'ing this PR?

**Comment by josephlacey** [comment]
@eileenmcnaughton @JoeMurray The code on this looks fine, but I'm not sure how to QA this.  When does this function get called?

**Comment by eileenmcnaughton** [comment]
So, if you have 

- Database logging turned on

- and you merge 2 contacts with at least the one to be deleted having records in the subscription_history table 

- go to the change log & click on the activity merged record

- from the revert screen revert the change

**Comment by josephlacey** [comment]
I didn't have any problems reverting merged contacts as described, so I would suspect this is fine to merge in. @eileenmcnaughton @JoeMurray

**Pull request merged**
