### PR TITLE
CRM-21322: create hook to modify entityRef fields

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Create a hook to modify the parameters passed to entityRef fields. This will allow developers to do things like define custom api entities for tagset lookups.

After
----------------------------------------
Introduce hook ```hook_civicrm_alterEntityRefParams(&$params)```

---

 * [CRM-21322: create hook to modify entityRef fields](https://issues.civicrm.org/jira/browse/CRM-21322)

### CODE REVIEW

**Comment by lcdservices** [comment]
This looks good. With this hook we can modify the parameters used to build entityRef fields.

**Comment by seanmadsen** [comment]
Associated docs PR: https://github.com/civicrm/civicrm-dev-docs/pull/433

Please ping me there when this PR is merged.

**Comment by monishdeb** [comment]
ping @colemanw @mlutfy @eileenmcnaughton

**Comment by mlutfy** [comment]
Seems good to me. I had discussed with Monish about having more flexibility so that we can override an entityRef on a specific form only, which is now possible with the latest commit to this PR.

Since this is about adding a hook, ping @totten ?

**Comment by monishdeb** [comment]
Thanks @mlutfy for your feedback. 

@colemanw / @totten can you review and merge this PR?

**Pull request merged**
