### PR TITLE
[REF] Accessibility fixes in contact summary page

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Fixed the issues highlighted in before section on contact summary page

Before
----------------------------------------
Empty header link in relationships and notes tab: 
Screenshot 2024-07-29 at 14 30 09

Empty label:
Screenshot 2024-07-29 at 17 01 57

After
----------------------------------------
Fixed

Technical Details
----------------------------------------
Depends on PR change [here](https://github.com/civicrm/civicrm-core/pull/30748/files#diff-8c802c11623f140bd6b578ea6a418592ea30d41951b652d4cffa9b14cff77b6fR18)

Comments
----------------------------------------
ping @seamuslee001 @colemanw @vingle

### CODE REVIEW

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by vingle** [comment]
test this please

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by monishdeb** [comment]
Jenkins test this please

**Pull request merged**
