### PR TITLE
dev/membership#2 - Add membership start date and registration start/end date to schedule reminder

### PR DESCRIPTION
**Pull request by jitendrapurohit**
Overview
----------------------------------------
Add membership start date and event registration start/end date to schedule reminder.

Before
----------------------------------------
No membership start date OR event registration start/end date available on the form

**Membership** -
image

**Event** -
image

After
----------------------------------------
Available and working.

**Membership** -
image

**Event** -
image

--------

Gitlab Issue - https://lab.civicrm.org/dev/membership/issues/2

### CODE REVIEW

**Comment by monishdeb** [comment]
Jenkins test this please

**Comment by mattwire** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@michaelmcandrew is this one you could review?

**Comment by mattwire** [comment]
@jitendrapurohit Could you update the PR subject per https://docs.civicrm.org/dev/en/latest/tools/git/#pr-subject:
"dev/membership#2 - Add membership start date and registration start/end date to schedule reminder"

**Comment by michaelmcandrew** [comment]
@jitendrapurohit I did some manual testing of this functionality. It is fairly hard to test this stuff but I feel like some things are not working correctly.

I created two conferences:
```
cv api event.create title="reg closes may 1 2018" event_type_id=Conference start_date=2018-06-06T0900 registration_end_date=2018-05-01T0000
cv api event.create title="reg closes may 1 2019" event_type_id=Conference start_date=2019-06-06T0900 registration_end_date=2019-05-01T0000
```
I then registered the same contact at each with status registered

I then set a scheduled reminder as shown in the following screen shot:
scheduled-reminder

but running `cv api job.send_reminder` did not cause any scheduled reminders to be sent.

I would have expected the contact to receive one scheduled reminder.

**Comment by eileenmcnaughton** [comment]
I think we would need a test on it

**Comment by michaelmcandrew** [comment]
@eileenmcnaughton - scheduled reminders itself seems quite under tested. From what I can see, there is [a single web test](civicrm/tests/phpunit/WebTest/Admin/Form/ScheduleReminderTest.php) for the admin form and nothing testing that the reminders are behaving as they should.

I'm guessing this is at least in part because there is a lot of set up: creating events and participants (or memberships and members), running cron jobs, etc. and that the output (email) is a bit hard to test.

Also, the scheduled reminders api is also a little under developed (read non existent).

Not sure if there have been attempts in the past to improve testing in this area of CiviCRM. 

:mountain:

**Comment by eileenmcnaughton** [comment]
@michaelmcandrew I think @totten HAS created some tests - so they might just be somewhere unexpected...

**Comment by jitendrapurohit** [comment]
test this please

**Comment by jitendrapurohit** [comment]
@michaelmcandrew seems the event in your testing has `registration_end_date` set as 1 may 2019 and the reminder is set to execute 6 months before the date which might not be true unless the date is - 1 may minus 6 months.

I've written a unit test which should explain the test procedure. My initial testing was something like -

- Create event with registration end date set to tomorrow.
- Create sched reminder with offset = 1 day before registration end date.
- Register a participant to the event.
- Execute SR job and verify if the mail was sent.

**Comment by michaelmcandrew** [comment]
> seems the event in your testing has registration_end_date set as 1 may 2019 and the reminder is set to execute 6 months before the date which might not be true unless the date is - 1 may minus 6 months.

@jitendrapurohit - I created two events.

> `cv api event.create title="reg closes may 1 2018" event_type_id=Conference start_date=2018-06-06T0900 registration_end_date=2018-05-01T0000`

^ for this one, I thought the email would be sent because the we are less than 6 months before the registration date but no email was sent

> `cv api event.create title="reg closes may 1 2019" event_type_id=Conference start_date=2019-06-06T0900 registration_end_date=2019-05-01T0000`

^ For this one, I wanted to ensure that no email was sent.

**Comment by michaelmcandrew** [comment]
> Also, the scheduled reminders api is also a little under developed (read non existent).

Ah, so ActionSchedule is scheduled reminder. Sorry - I didn't realise that.

**Comment by jitendrapurohit** [comment]
Thanks for the review @michaelmcandrew. Seems like the review is positive with the below test requirement?

>A test that created an event 2 weeks in the future, and a scheduled reminder to be sent 1 week before the event and ensured that it wasn't sent 'today' would be nice to have but is not necessary.

I've added this to the PR now. @eileenmcnaughton @michaelmcandrew Can we have this merged into core?

**Comment by monishdeb** [comment]
Great work @jitendrapurohit and thank you all for your feedback. I have tested the PR and the schedule reminder is behaving correctly on those 3 new dates added for membership and event + UT. 

Hence marking with merge-on-pass

**Comment by michaelmcandrew** [comment]
looks great @jitendrapurohit :)

**Pull request merged**
