### PR TITLE
CRM-16526 [fantastic PR that adds tests] Unit tests for Financial Type ACL test

### PR DESCRIPTION
**Pull request by Edzelopez**
---
- CRM-16526: ACLs for Financial Types
  https://issues.civicrm.org/jira/browse/CRM-16526

### CODE REVIEW

**Comment by Edzelopez** [comment]
@JoeMurray are there any more unit tests required? The other new functions related to the FT ACL are just used for creating permissioned where clauses and checking if ACL for FT is enabled,

**Comment by JoeMurray** [comment]
As discussed, additional tests needed for each public static function without one. Also, move code from API later into new BAO as per Eileen implied auggestion.

**Comment by Edzelopez** [comment]
anything holding off merging this?

**Comment by eileenmcnaughton** [comment]
Nope!

**Comment by Edzelopez** [comment]
Thanks! :)

**Pull request merged**
