### PR TITLE
Unhide message admin UI

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Unhide message admin UI

Before
----------------------------------------
Message admin extension ships with CiviCRM but not visible in the extensions screen

After
----------------------------------------
image

Technical Details
----------------------------------------
The extension works - it has a bug that I need to log - but I don't think being bug-free is a criteria - just not insanely alpha

Comments
----------------------------------------

### CODE REVIEW

**Comment by totten** [comment]
This would be great... but... for a regular site running default flows, isn't the translation non-functional right now? I think we're missing the part which says: "When loading any random message-template, get the one with the closest locale."

**Comment by eileenmcnaughton** [comment]
@totten yeah - seems so - also the way in which you wound up implementing the translate doesn't allow for it to be done in the extension (I originally thought it would be like my extension where the core function would not need to be aware that there was a translation because an api listener would check & load it - but it seems we have to do that in the heart of the MessageTemplate loadTemplate function)

**Comment by eileenmcnaughton** [comment]
I need to figure out the distinct core hacks I'm running to get this to work currently - looks like there are 5 fiels (& an unrelated patch) I hacked to get it to work to display locale well in the UI too https://gerrit.wikimedia.org/r/c/wikimedia/fundraising/crm/civicrm/+/751849

**Comment by eileenmcnaughton** [comment]
In interests of not having unmergeable prs open .. closing

**Pull request closed without merging**
