### PR TITLE
[REF] simplify CRM_Activity_BAO_Activity function by using early returns

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Minor code simplification - this is simpler than it looks in github - it removes 2 if blocks that can be avoided by an early return - and makes the function more legible

Before
----------------------------------------
function less legible

After
----------------------------------------
function more legible

Technical Details
----------------------------------------
This function returns a bool. In the process it sets the  variable, however, once set to false in two places
it can never be set to true, so I am simply replacing a big if block with an early return to simplify the code.

This is a further block that can go but it is a slightly different patter & would remove 2 levels of 'if'
so it feels like an easier review if I leave that out of scope

Comments
----------------------------------------
@colemanw @seamuslee001 any chance one of you could take a look. It's actually pretty minor & covered by a handful of tests like testGetActivityByAclCannotViewAllContacts added to api_v3_ACLPermissionTest in preparation for cleanup

### CODE REVIEW

**Comment by seamuslee001** [comment]
(*CiviCRM Review Template WORD-1.2*)



* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) Pass
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) Pass
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) Pass
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) Pass this is well covered by unit tests already so as long as Jenkins approves we should be fine
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) Pass
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) Pass reviewed the code it simplifies it down a bit and just makes it a bit more straight forward
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) Pass
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) Pass

merging

**Comment by eileenmcnaughton** [comment]
thanks @seamuslee001

**Comment by magnolia61** [comment]
Would this solve the "Deprecated function: Non-static method CRM_Activity_BAO_Activity::checkEditInboundEmailsPermissions() should not be called statically in CRM_Activity_Page_Tab->preProcess()" I am getting, or am I utterly confused?

**Comment by eileenmcnaughton** [comment]
@magnolia61 no - it's unrelated - that function should probably be made static

**Pull request merged**
