### PR TITLE
CRM-18744 - Add prompt text when search term not found

### PR DESCRIPTION
**Pull request by colemanw**
https://issues.civicrm.org/jira/browse/CRM-18744

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton I think this will address your users' complaints.
Do you think it is urgent enough to merge into the 4.7.10-rc?

**Comment by eileenmcnaughton** [comment]
I'll test it and see how it goes. I'm inclined to think master is fine - because we probably want to put it out to test for a bit since they experienced it as an intermittent problem.

As a side note the hooks that allow you to edit quicksearch struggle a bit with the fact the list of fields is hard coded in navigation.js.tpl - just noting it in case you have to touch that code again and being aware it's blocking customisation affects the choices you make. The sort of things we would want to add are 'Contribution ID' or 'Invoice number'.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
We deployed this & our users confirm it is an improvement so I'm merging this

**Pull request merged**
