### PR TITLE
[REF] Add test for line item, extract fn

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Function extraction, add test

Before
----------------------------------------
Long chunk

After
----------------------------------------

This just extracts the inner of the function & adds a test

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton style issue https://test.civicrm.org/job/CiviCRM-Core-PR/31762/checkstyleResult/new/

**Comment by eileenmcnaughton** [comment]
thanks @seamuslee001 I've been struggling with weird output on style issues lately

**Comment by seamuslee001** [comment]
yeh @demeritcowboy found the problem there and i just deployed the fix

**Comment by seamuslee001** [comment]
test fail looks related @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
ug

**Comment by eileenmcnaughton** [comment]
unrelated fail

**Pull request merged**
