### PR TITLE
CRM-17631: Process mailing jobs by scheduled date

### PR DESCRIPTION
**Pull request by JKingsnorth**
- [CRM-17631: Mailings: process jobs by scheduled date instead of mailing ID](https://issues.civicrm.org/jira/browse/CRM-17631)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Nice!

**Comment by totten** [comment]
Wow, yeah, sorting by scheduled date does sound right. :)

One critique: the query is a join of jobs-to-mailings, and it's returning the jobs. If you have a mailing with 5 jobs, wouldn't the 5 jobs have the same values for `scheduled_date` and `mailing_id`? Thus, among the 5 jobs, the ordering would be non-deterministic. I think the `j.id` is needed to make the ordering deterministic.

How about:
 * `ORDER BY j.scheduled_date ASC, j.mailing_id, j.id` or
 * `ORDER BY j.scheduled_date ASC, j.id` ?

**Comment by JKingsnorth** [comment]
Yup this shouldn't definitely be j.id! That's what I intended but apparently didn't do. Thanks for spotting this I'll fix it up tomorrow.

**Comment by JKingsnorth** [comment]
Last commit fixes the sort order by job id.

**Comment by JKingsnorth** [comment]
Please could you re-test this Jenkins?

**Comment by JKingsnorth** [comment]
Jenkins re-test please

**Comment by JKingsnorth** [comment]
Jenkins, re-test this please

**Pull request merged**
