### PR TITLE
Allow profile.submit api for tags

### PR DESCRIPTION
**Pull request by colemanw**
Before
------
Profile submitted via api could not remove all tags from a contact.

After
-------
Profile submitted via api can remove all tags from a contact.

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton this further fixes #12825

**Comment by eileenmcnaughton** [comment]
@colemanw I have tested this & confirm it works. Changes look good. Test looks like it covers. I think the test fails are unrelated - but you might prefer against the rc anyway

**Comment by colemanw** [comment]
Yes don't merge just yet, I'll rebase this against 5.6 and include the other commit.

**Comment by colemanw** [comment]
Ok good to go.

**Comment by colemanw** [comment]
Unrelated test fails.

**Pull request merged**
