### PR TITLE
[NFC/Unit test] - Failing test demonstrating blank timestamp updates

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
This will fail at the moment.

In https://github.com/civicrm/civicrm-packages/pull/319 insert() was patched to also look for timestamp db fields when inserting a blank date in a field that allows nulls. But update() was not also patched so it has the same problem with timestamp types.

Before
----------------------------------------
DB Error: unknown error
Incorrect datetime value: '0' for column `whatever` at row 1

After
----------------------------------------
After https://github.com/civicrm/civicrm-packages/pull/326, stores null in the db

Technical Details
----------------------------------------
It only fails if sql_mode has NO_ZERO_DATE.

Comments
----------------------------------------
https://github.com/civicrm/civicrm-core/pull/20476

### CODE REVIEW

**Comment by seamuslee001** [comment]
Test fail expected

**Comment by seamuslee001** [comment]
```
CRM_Core_DAOTest::testUpdateTimestampWithBlankDate
Exception: PEAR_Exception: "DB Error: unknown error"
 * ERROR TYPE: DB_Error
 * ERROR CODE: -1
 * ERROR MESSAGE: DB Error: unknown error
 * ERROR MODE: 16
 * ERROR USERINFO: UPDATE  `civicrm_cache`  SET `group_name` = 'mytest' , `path` = 'mypath' , `data` = 'some updated data' , `created_date` = 20210717231255 , `expired_date` = 0   WHERE (  `civicrm_cache`.`id` = 487 )   [nativecode=1292 ** Incorrect datetime value: '0' for column 'expired_date' at row 1]
 * ERROR DEBUGINFO: UPDATE  `civicrm_cache`  SET `group_name` = 'mytest' , `path` = 'mypath' , `data` = 'some updated data' , `created_date` = 20210717231255 , `expired_date` = 0   WHERE (  `civicrm_cache`.`id` = 487 )   [nativecode=1292 ** Incorrect datetime value: '0' for column 'expired_date' at row 1]
 ```

**Comment by seamuslee001** [comment]
now that https://github.com/civicrm/civicrm-packages/pull/326 has been merged, Jenkins retest this please

**Comment by demeritcowboy** [comment]
Thanks @seamuslee001

**Pull request merged**
