### PR TITLE
(dev/core#394) : Wildcards are ignored in some smart group criteria, when the smart group is directly generated for a mailing

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Steps to replicate:
1. Create a text custom field used for Individual
2. Choose any contact and add custom field value say 'abc'
3. Go to Advance Search and search contact with criteria "custom field = '%a%'"
4. Select the contact and choose task 'Email - schedule/send via CiviMail'
5. Redirected to 'New Mailing' but with no recipient count 

Before
----------------------------------------
screencast-before

After
----------------------------------------
screencast-after

Technical Details
----------------------------------------
As per the fix, we should first translate the formvalues in query format before saving the criteria for saved search which restores the operator and doesn't strip the wildcard which is essential, especially when such saved criteria are used by smart group. In addition, did a minor change to getRecipients() to ignore the cache_date of hidden smart groups for rebuilding its contact, as from UI there is no way we can rebuild recipients for such hidden smart group in other word cache_date is not updated.

### CODE REVIEW

**Comment by monishdeb** [comment]
ping @lcdservices @colemanw

**Comment by lcdservices** [comment]
Tested and confirmed this PR works as expected with the given test steps.

**Comment by eileenmcnaughton** [comment]
@monishdeb test fail is related

Fatal error: Cannot use object of type CRM_Core_DAO_CustomField as array in /home/jenkins/bknix-dfl/build/core-12910-8xc5z/sites/all/modules/civicrm/tests/phpunit/CRM/Contact/BAO/GroupTest.php on line 251

GIving this merge on pass as once that is resolved then I'm happy with @lcdservices testing + unit test

**Comment by eileenmcnaughton** [comment]
@monishdeb failing on a related e-notice

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Pull request merged**
