### PR TITLE
More buttonrama fallout

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fixes a notice from Buttonrama - affects 5.31+

Before
----------------------------------------
Screen Shot 2020-10-21 at 6 25 18 PM

After
----------------------------------------
poof

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by demeritcowboy** [comment]
I don't think this is the same as with [static](https://lab.civicrm.org/dev/core/-/issues/2108). This seems like an instance where it should be passing an array but isn't: https://github.com/civicrm/civicrm-core/blob/39610e8bbae5fa23a3c5c150f2cca3ec25533608/CRM/Import/Form/DataSource.php#L53

**Comment by eileenmcnaughton** [comment]
@demeritcowboy Ah - ok - I assumed but yeah - let's fix to pass an array

**Comment by eileenmcnaughton** [comment]
Fixed

**Comment by demeritcowboy** [comment]
There's a double-space that snuck in there but otherwise looks good. Could also pass NULL since those html params don't mean much for file uploads. It didn't seem to make a difference when I tested.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy OK - I went with NULL

**Comment by demeritcowboy** [comment]
Looks good!

**Pull request merged**
