### PR TITLE
CRM-20201 Fix issue where manage tags page would not display properly…

### PR DESCRIPTION
**Pull request by seamuslee001**
… if tag set does not have a created by set

[CRM-20201 Manage Tags page does not work if a tag set does not have created by set](https://issues.civicrm.org/jira/browse/CRM-20201)

### CODE REVIEW

**Comment by seamuslee001** [comment]
ping @colemanw I found this testing your other patch does this look ok to you?

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@eileenmcnaughton test failure looks false can you confirm?

**Comment by eileenmcnaughton** [comment]
Yeah, unrelated, possibly date related as Feb 28 is notorious for causing odd bugs - really we should care harder

**Comment by eileenmcnaughton** [comment]
@seamuslee001 has confirms this affects the current rc & demo'd this patch fixing the issue.

The code looks clear & sensible - just doing some 'if exists' checks

**Pull request merged**
