### PR TITLE
[NFC] Cleanup Custom Groups and associated tables in api v4 unit test…

### PR DESCRIPTION
**Pull request by seamuslee001**
…s so that multiple runs can be performed

Overview
----------------------------------------
This cleans up various Custom Groups/Custom Fields 

Before
----------------------------------------
Tests leave created custom value tables around

After
----------------------------------------
Tests cleaned up custom value tables

ping @eileenmcnaughton @colemanw @totten

### CODE REVIEW

**Comment by colemanw** [comment]
I thought this was supposed to be taken care of by BaseCustomValueTest which always drops custom fields and tables as part of `setUp()`

**Comment by seamuslee001** [comment]
@colemanw it was the actual custom_value_xxx tables that weren't seem to be getting cleaned up

**Comment by colemanw** [comment]
That's supposed to happen here: https://github.com/civicrm/civicrm-core/blob/0b49aa04156bc88a6dd11c70a8b3d83af00d18f4/tests/phpunit/api/v4/Action/BaseCustomValueTest.php#L44

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @colemanw  the cleanup needs to happen in the tearDown - otherwise it doesn't happen when the test fails. There is code to handle that in the main unittest class - but not in the v4 api tests

It also should not be done in setup - it should be cleanup after the relevant test not some precaution against the test not having done it's thing

**Comment by demeritcowboy** [comment]
Is this still needed after https://github.com/civicrm/civicrm-core/pull/20876 (which by itself doesn't seem to have solved the recurring api4 test fail unfortunately)?

**Comment by colemanw** [comment]
Nope

**Pull request closed without merging**
