### PR TITLE
Make period_type mandatory for MembershipType

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
We have a test ensuring period_type is mandatory at the api level. However, it isn't for api
v4 - the error is a different issue (handling of pseudoconstants when mapping v3 to v4). This
fixes that separate issue & declares required to re-fix for v4

Before
----------------------------------------
period_type not declared as mandatory (but has a db default of rolling). In apiv3 & form layer it is mandatory, but not apiv4

After
----------------------------------------

period_type declared as mandatory (but has a db default of rolling), required in apiv3, v4, form layer

Technical Details
----------------------------------------
Test came from https://issues.civicrm.org/jira/browse/CRM-20010 -  I think re-reading this it is probably right to make it mandatory & use the default less

Comments
----------------------------------------

Came from test issues in https://github.com/civicrm/civicrm-core/pull/18388

### CODE REVIEW

**Comment by seamuslee001** [comment]
style issue

**Comment by eileenmcnaughton** [comment]
Hmm - the failure changes with https://github.com/civicrm/civicrm-core/pull/18365 merged as the test no longer uses the same setup - I will see if I can get that merged first

**Comment by mattwire** [comment]
@eileenmcnaughton Test failures relate

**Comment by eileenmcnaughton** [comment]
I'm going to close this for now because it's blocked until I can resolve the test failures - but it needs  #18365 

I don't want to clog up the review queue with PRs that are not reviewable so I'll re-open this when the blocking-issues are solved

**Comment by colemanw** [comment]
@eileenmcnaughton needs rebase

**Comment by eileenmcnaughton** [comment]
@colemanw rebased now - let's see how it goes....

**Comment by eileenmcnaughton** [comment]
OK - this cleanup should address https://github.com/civicrm/civicrm-core/pull/18413

**Comment by eileenmcnaughton** [comment]
This is passing now

**Comment by seamuslee001** [comment]
Looks fine to me merging

**Pull request merged**
