### PR TITLE
CRM-19816 - Improve activity search filters

### PR DESCRIPTION
**Pull request by colemanw**
* [CRM-19816: Improve activity search filters](https://issues.civicrm.org/jira/browse/CRM-19816)

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
jenkins, test this please

**Comment by jitendrapurohit** [comment]
jenkins, test this please

**Comment by eileenmcnaughton** [comment]
@colemanw I'll do a performance test on this - I believe I can invoke by api call - can you confirm the api call?

civicrm_api3('Activity', 'get', array('source_contact_id' => 1));
civicrm_api3('Activity', 'get', array('activity_contact_id' => 1));

etc?

**Comment by eileenmcnaughton** [comment]
OK - I have tried 

civicrm_api3('Activity', 'get', array('source_contact_id' => 1));

with & without the change & the timing seems much the same. There are noticeable speed issues coming from the poor handing of activity_type_id in the query object but not from this.

DB is Maria DB 5.5. Database is large & returned rows are around 10k.

I didn't use complex criteria so I don't know if some variants of the query could be trickier.

**Comment by colemanw** [comment]
Thanks for the testing @eileenmcnaughton

**Pull request merged**
