### PR TITLE
Add default location for API v3 creates of Address, IM, OpenID and Phone

### PR DESCRIPTION
**Pull request by aydun**
Has tests.

Default location was recently added for APIv3 Email.create
(https://github.com/civicrm/civicrm-core/pull/14489)
and for Address, Email, IM, OpenID and Phone in APIv4
(https://github.com/civicrm/org.civicrm.api4/pull/162)
so this brings consistency of behaviour for these entities between each other
and between APIv3 and APIv4

Overview
----------------------------------------
_A brief description of the pull request. Try to keep it non-technical._

Before
----------------------------------------
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

After
----------------------------------------
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

Technical Details
----------------------------------------
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by mattwire** [comment]
@aydun Test failures look related

**Comment by eileenmcnaughton** [comment]
@aydun I thought we were pretty much at the point of freezing api v3 & saying 'apiv4 is where we learnt from our mistakes - go use that'

**Comment by aydun** [comment]
@eileenmcnaughton I I hadn't realised we were freezing APIv3. Does that mean we are now ok to use APIv4 in core as v3 is?  I had checked with @colemanw (https://github.com/civicrm/org.civicrm.api4/pull/162) and it seemed sensible to eliminate this small difference, mostly to aid any future v3 -> v4 conversions.

**Comment by eileenmcnaughton** [comment]
@aydun well @colemanw just needs to fix a few more things & we will ship v4 with core. v3 is not totally frozen but we definitely try not to touch it anymore

**Comment by seamuslee001** [comment]
I would be in favour of merging as it would also mean we have consistent behaviour between v3 and v4. I also wasn't aware or wouldn't be in favour of freezing or anything like that at the moment for api v3. I was still understood it would be being added to tweaked etc

**Comment by eileenmcnaughton** [comment]
@seamuslee001 no you are right - we are not there yet with freezing apiv3 - I just think we should aim to get there in the short term - happy for you to merge this if you wish

**Comment by aydun** [comment]
Thanks all !

**Comment by colemanw** [comment]
Yay for more tests :tada:

**Pull request merged**
