### PR TITLE
CRM-17645 - WIP on api hooks, joins, permissions

### PR DESCRIPTION
**Pull request by colemanw**
- [CRM-17645: ACL Hook for Cases](https://issues.civicrm.org/jira/browse/CRM-17645)

### CODE REVIEW

**Comment by totten** [comment]
Seems like a useful hook -- might be more useful if you can access `$params`. Then you change the interpretation of certain filters or add custom filters.

Ideally, I think it should pass through `$apiRequest` (which provides a somewhat normalized representation of the API call), e.g.

```
/**
 * @param array $apiRequest
 *   The full API request, with the parsed entity, action, params, etal. (See Civi\API\Request::create).
 * @param CRM_Utils_SQL_Select $query
 *   The alterable query.
 */
function hook_civicrm_entityGet($apiRequest, $query)
```

However, most of the flows around `_civicrm_api3_basic_get()` don't currently provide access to `$apiRequest`, so it's a little tricky to get a reference to it. Maybe:
 a. Sprinkle `$apiRequest` around the various places which call `_civicrm_api3_basic_get()`. There are ~80 boring places which call it using a simple formula, and ~16 novel places. Example: https://gist.github.com/totten/44891ccdf88ea59fadff
 b. Keep track of the active API requests. (Since API requests sometimes overlap, use a stack.) https://gist.github.com/totten/f3288da69b06fc0d10c3

**Comment by colemanw** [comment]
What you're describing is basically what [hook_civicrm_apiWrappers](http://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_apiWrappers) does. I'm starting to think that this proposed hook is too similar to that one, and the existing hook might actually serve the needs of the client in this case.
I'll try using the existing one and see how far I get.

**Comment by totten** [comment]
For purposes of CRM-17645 (e.g. access control of Case API), I take your point -- one could use `hook_apiWrappers` to inject extra access constraints (e.g. "lookup the current user and inject extra filters for `case_type_id`").

Although there may be some misunderstanding: when I looked at that technique (hook-alter for API SQL queries), a different problem came to mind -- expressiveness of API requests (wrt joins, aggregation, subqueries, functions). For that problem, `hook_entityGet($apiRequest,$query)` provides flexibility and performance that `hook_apiWrappers` would not. However, it sounds like that's not in your scope, so maybe it makes sense to exercise Patience and wait until we can tackle API expressiveness head-on.

**Comment by colemanw** [comment]
jenkins, retest this please

**Pull request closed without merging**
