### PR TITLE
CRM-21502 When adding a new address to a contact, and switching location types at the same time, only one address is kept

### PR DESCRIPTION
**Pull request by sharmistharc**
Overview
----------------------------------------
On first round I got style issue error due to spacing related problem. Now It has fixed. So second time it is requested for the review

Before
----------------------------------------
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

After
----------------------------------------
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

Technical Details
----------------------------------------
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

---

 * [CRM-21502: When adding a new address to a contact, and switching location types at the same time, only one address is kept](https://issues.civicrm.org/jira/browse/CRM-21502)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
replaces #11375

**Comment by eileenmcnaughton** [comment]
If you click on the red x you will see it takes you through to the failing test - https://github.com/eileenmcnaughton/civicrm-core/blob/cb7213564d0edee9dacf32802daf2940b290f566/tests/phpunit/api/v3/LoggingTest.php#L315

It's worth taking the time to be able to run tests locally (& preferably write them for any change)

Here is the relevant docs section 
https://docs.civicrm.org/dev/en/latest/testing/


It seems like you are dealing with a form that passes through an address like

address
(array('location_type_id' => 1, street_address => 'blah')
array('location_type_id' => 2, street_address => 'blah blah')
);

And we possibly have already

address(array('location_type_id' => 2, street_address => 'blah');

I haven't quite got myself around the flow here as to what gets passed in & what goes wrong ( I would write a unit test & go through it in a debugger to make sense of it)

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@sharmistharc I set the tests running again. Can you confirm if you are still invested in seeing this through. I'm aware that at around the time you submitted this a number of patches were submitted as part of an application process so if you have moved on & it is still failing I think we will close it

**Comment by MegaphoneJon** [comment]
@DanielvV is this something you have any interest in?  I know you have an interest in the address code.

**Pull request closed without merging**
