### PR TITLE
Upgrade When package to the lastest version 

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This picks up the work from @agileware-pengyi in #14903 and goes for more of a straight composer way with this PR. Note that this PR is expected to fail testing

Note to @agh1 please make sure @agileware-pengyi is credited

Before
----------------------------------------
Old version of When package is used

After
----------------------------------------
Newer version of When package used

In terms of tests i am expecting that CRM/Core/BAO/RecurringEntityTest is going to fail as it is locally which suggests we do have some unit tests already covering this code

ping @jusfreeman @eileenmcnaughton 

Agileware ref: CIVICRM-1223

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
fail relates

**Comment by jusfreeman** [comment]
@seamuslee001 thanks and thanks for adding the Agileware ref! Legend!

**Comment by seamuslee001** [comment]
@jusfreeman i'm not sure how to fix the test failures but given that Pengyi has looked into it already maybe he can give some guidance here

**Comment by jusfreeman** [comment]
@seamuslee001 we won't be able to get to this one today, however should have time next week. It's on our board to action.

**Review by agileware-pengyi — COMMENTED** [review]
I have reviewed the fails.
Should I submit a new PR against this branch or the master branch?

**Comment by agileware-pengyi** [comment]
I have made the changes in [this commit](https://github.com/agileware/civicrm-core/commit/1156e9427c7e93c4c5325e8e12ed4d45d2548dc1)

**Comment by seamuslee001** [comment]
Thanks @agileware-pengyi  i have brought that commit in, i will need another reviewer to review this now @eileenmcnaughton @monishdeb

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I think this is mergeable it  you and @agileware-penjyi have reached agreement - without having gone into the code to the level you two have nothing  jumps out as concerning

**Comment by agileware-pengyi** [comment]
@seamuslee001 thanks

**Comment by seamuslee001** [comment]
@eileenmcnaughton @agileware-pengyi  i have also just pushed one minor change which is setting the ignoring of exceptions to only happen when in UnitTests UF because i figure we still want Execptions to be thrown so they show up as status messages

**Comment by agileware-pengyi** [comment]
> @eileenmcnaughton @agileware-pengyi i have also just pushed one minor change which is setting the ignoring of exceptions to only happen when in UnitTests UF because i figure we still want Execptions to be thrown so they show up as status messages

That makes sense to me. Just noting that this exception with message `The start date must be the first occurrence.` is not checked by the old version.

**Comment by agileware-pengyi** [comment]
Working on exclude dates issue. It needs some changes for the new version.

**Comment by agileware-pengyi** [comment]
Following the old way to generate the occurrences. https://github.com/agileware/civicrm-core/commit/410b8581328cdaa4b48ab89435c564b8ef40cac3

More confidence with this one because of fewer changes.

One thing I notice is that `error` is not defined in both [old](https://github.com/civicrm/civicrm-packages/blob/master/When/When.php) and [new](https://github.com/tplaner/When/blob/master/src/When.php) version. Should we keep it?

https://github.com/civicrm/civicrm-core/blob/e058b2669cd4b9f9b64c0b6c70ff24162346f05b/CRM/Core/BAO/RecurringEntity.php#L992

https://github.com/civicrm/civicrm-core/blob/e058b2669cd4b9f9b64c0b6c70ff24162346f05b/CRM/Core/BAO/RecurringEntity.php#L1018

**Comment by eileenmcnaughton** [comment]
Ug - needs a rebase

**Comment by seamuslee001** [comment]
rebased now @eileenmcnaughton

**Comment by mattwire** [comment]
Merging so we get plenty of testing during the 5.20 release cycle. @seamuslee001 Do we need a PR to remove from packages?

**Pull request merged**
