### PR TITLE
CRM-16650 - Rewrite shortcode form

### PR DESCRIPTION
**Pull request by colemanw**
https://issues.civicrm.org/jira/browse/CRM-16650

### CODE REVIEW

**Comment by christianwach** [comment]
On reviewing this, I'm concerned about the hack to prevent WP toolbars from popping up above the dialog. I would recommend setting the `z-index: 1001` on the Civi dialog rather than overriding the WordPress defaults. Civi will not be popular if this messes up the expected behaviour for WP core and other plugins.

**Comment by JoeMurray** [comment]
@christianwach comment seems accurate to me.

**Comment by colemanw** [comment]
@christianwach I agree the hack is ugly, but disagree it will mess up any core WP functionality, as it only modifies the z-index of WP toolbars for the duration of the popup. As soon as it is closed, things go back to normal.

**Comment by christianwach** [comment]
@colemanw Okay, that's reassuring. I've just noticed that the modal is injected into the DOM when the button is clicked and removed when done. I assumed it behaved like the previous version. Will keep testing.

**Pull request merged**
