### PR TITLE
SMS Provider searchkit admin ui

### PR DESCRIPTION
**Pull request by samuelsov**
Overview
----------------------------------------
SMS Provider search kit for admin UI replacement - replacement to https://github.com/civicrm/civicrm-core/pull/28512

Before
----------------------------------------
288107045-f0c7e92d-eee9-48af-b427-08f50cfa2690

After
----------------------------------------
ksnip_20240301-161702

### CODE REVIEW

**Comment by mmyriam** [comment]
Mostly ok but when creating a new provider doesn't close the pop-up form on save. Instead empties the form fields. The new provider is created though.

**Comment by mmyriam** [comment]
Fixed.

**Comment by mattwire** [comment]
test this please

**Comment by colemanw** [comment]
retest this please

**Pull request merged**
