### PR TITLE
Search ext: rename to Search Kit, mark as beta

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Label new search extension "Search Kit" beta1.

Before
----------------------------------------
- Search creator
- Hidden extension

After
----------------------------------------
- Search Kit
- Beta1
- Not hidden

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Yes - I think this covers the outstanding issues

**Comment by eileenmcnaughton** [comment]
I commented on https://github.com/civicrm/civicrm-core/pull/17775 to flag this - we should merge before the rc is cut

**Comment by mattwire** [comment]
:+1:

**Comment by eileenmcnaughton** [comment]
Since 5.31 is being cut tomorrow & this has 2 thumbs up ^^ - I'm going to merge this now

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @totten how do we install in buildkit installs without adding to all new installs?

**Pull request merged**
