### PR TITLE
CiviCRM Scheduled Reminders, adds support for Participant fields and Participant Custom Fields as Tokens in Scheduled Reminders

### PR DESCRIPTION
**Pull request by agileware-justin**
Overview
----------------------------------------
Adds support for Participant fields and Participant Custom Fields as Tokens in Scheduled Reminders.

Solves this Gitlab Feature Request, Custom Participant tokens not working in scheduled reminders
https://lab.civicrm.org/dev/core/-/issues/348

Before
----------------------------------------
Cannot use Participant fields or Participant Custom Fields as Tokens in Scheduled Reminders, which is sad :cry: 

After
----------------------------------------
Now able to use Participant fields or Participant Custom Fields as Tokens in Scheduled Reminders :grinning: 

Technical Details
----------------------------------------
Includes commits from PR https://github.com/civicrm/civicrm-core/pull/20334 as the two are dependant on a change to the getCustomFieldTokens function.

Comments
----------------------------------------
Ping @mattwire 

Agileware Ref: CIVICRM-1731

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@totten probably best if you review this one once you get to that part of the message template work - it does extend our TokenProcessor surface & I want to be really clear about our test cover and about how we want to represent pseudoconstants etc before we extend our surface area on this

**Comment by magnolia61** [comment]
Thanks a lot for submitting this PR :-) I opened up an issue about this exact matter a while ago: https://lab.civicrm.org/dev/core/-/issues/348 

I have been successful in testing this wonderful pr, except for custom date fields. 
When I include a custom participant date field token in a reminder mail, it will stop all tokens from being processed.

If you need help testing, I would be glad to do so. Cheers, Richard

**Comment by agileware-justin** [comment]
@magnolia61 ready for testing again :)

**Comment by totten** [comment]
I was chatting a bit with @eileenmcnaughton about this. (You may remember she'd spent a chunk of time on testing/comparing tokens for #19806.) She raised the point that we ought to have some test-coverage.

It can be a bit daunting to write a first test for this, but I think there's a good example at https://github.com/civicrm/civicrm-core/blob/5.38/tests/phpunit/CRM/Mailing/TokensTest.php#L6. It's really just the two functions --  `getExampleTokens()`  and `testTokensWithMailingId()`.

**Comment by agileware-justin** [comment]
@totten 

> (You may remember she'd spent a chunk of time on testing/comparing tokens for #19806.) She raised the point that we ought to have some test-coverage.

Not on my radar at all, thanks for pointing out

>  It's really just the two functions -- getExampleTokens() and testTokensWithMailingId().

Thanks for the tip. Will see what we can do here. Might be worthwhile to submit that as a follow-up PR because this one is a bit of a PITA to update already each time.

**Comment by MegaphoneJon** [comment]
Scheduled Reminders can also go to an "Additional Contact", and those contacts don't have to have a participant record.  When doing manual testing, we should make sure that participant tokens handle the lack of a participant gracefully (which I think means returning NULL).

**Comment by agileware-justin** [comment]
@magnolia61 or @MegaphoneJon would either of you have time to do a follow-up PR with the unit tests for this PR?

**Comment by petednz** [comment]
or @jitendrapurohit

**Comment by agileware-justin** [comment]
Thanks @petednz

**Comment by magnolia61** [comment]
I am (technically) not able to write a test. @petednz are you suggesting that @jitendrapurohit would be able to do so?

**Comment by petednz** [comment]
technically he can, in terms of when he can get to it with our current workload is an open-ended question. it is not high on our list, just there as 'help the community' task when we can

**Pull request closed without merging**
