### PR TITLE
dev/core#2164 Fix for exporting in localized civicrm crashes due to l…

### PR DESCRIPTION
**Pull request by wannesderoy**
Fix for exporting in localized civicrm crashes due to long translations in columns T_Boolean

### CODE REVIEW

**Comment by kewljuice** [comment]
[https://lab.civicrm.org/dev/core/-/issues/2164](https://lab.civicrm.org/dev/core/-/issues/2164)

**Comment by nielosz** [comment]
Should be working :+1:

**Comment by fpoulain** [comment]
I am also facing to this bug. I am getting an error ```[nativecode=1406 ** Data too long for column 'on_hold' at row 9]"]``` at export because it tries to put « Suspendue - par rebond » in a `varchar(16)`. This patch seems to fix the issue.

**Comment by bjendres** [comment]
@wannesderoy I extended your patch to fix the unit tests (see https://github.com/civicrm/civicrm-core/pull/19963). That's now been pulled into core, so I think you can close this one.

**Comment by eileenmcnaughton** [comment]
Closing per merged fix ^^

**Pull request closed without merging**
