### PR TITLE
CRM-19098 Add in Group Settings to add new group on import

### PR DESCRIPTION
**Pull request by seamuslee001**
- [CRM-19098: Include Group settings (mailing list or acl) when creating group on import](https://issues.civicrm.org/jira/browse/CRM-19098)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton this was merged into master and i think its a useful improvement

**Comment by seamuslee001** [comment]
@eileenmcnaughton this should be safe to merge

**Comment by colemanw** [comment]
jenkins, retest this please

**Comment by eileenmcnaughton** [comment]
unrelated fails

**Pull request merged**
