### PR TITLE
Extract field wrangling to determineReturnProperties

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Code cleanup on exportComponents

Before
----------------------------------------
Less readable

After
----------------------------------------
More readable

Technical Details
----------------------------------------
This encases the wrangling of the field format to it's own function.

This code is heavily tested

Comments
----------------------------------------
@colemanw

### CODE REVIEW

**Comment by colemanw** [comment]
This seems like an ok intermediate step but ultimately I would hope that the processor expects `$fields` to be in the already wrangled format, and so it seems to me the wrangling belongs in a util class somewhere and marked `@deprecated` and, finally, will be removed with the ExportUi extension is merged into core.

**Comment by eileenmcnaughton** [comment]
@colemanw yeah - just trying to isolate the code that works with them

**Comment by colemanw** [comment]
@eileenmcnaughton tests make sad face

**Comment by eileenmcnaughton** [comment]
Hmm yeah - fixed - try again

**Pull request merged**
