### PR TITLE
(dev/mail#41) "Preview as HTML"  - Fix error with tracking urls

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
Fix regression in email preview. Use-case:

* Compose a "Mailing => New Mailing"
* Fill in basic in fields.
* In the body of the mailing, include a hyperlink
* Press the button "Preview as HTML"

This is an alternate version to https://github.com/civicrm/civicrm-core/pull/13813 based on Monish's comment at https://github.com/civicrm/civicrm-core/pull/13813#issuecomment-472682777 

Before
----------------------------------------
Fatal error generating trying to preview mailing

After
----------------------------------------
Preview works

ping @monishdeb @eileenmcnaughton @scardinius

### CODE REVIEW

**Comment by lcdservices** [comment]
I tested this and confirmed it fixes the issue. This should probably be considered for a dot release, or at least the 5.13.0 release, as it's clearly a regression.

**Comment by seamuslee001** [comment]
i've put this against 5.13 now based on Brian's comment ping @eileenmcnaughton @mattwire @monishdeb

**Comment by colemanw** [comment]
This change looks good to me. Tagging merge-on-pass based on my code review and Brian's testing.
@seamuslee001 I'd also be happy to consider this for 5.12.2

**Comment by eileenmcnaughton** [comment]
unrelated fail

**Pull request merged**
