### PR TITLE
Add metadata to is_primary fields

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Improves some field information for the sake of Form Builder.

Before
----------------------------------------
Less accurate field info.

After
----------------------------------------
Better info about fields for Form Builder to use.

Comments
----------------------------------------
Strange but true: the Email is_primary field was in the xml twice... and no one noticed for years!

### CODE REVIEW

**Review by seamuslee001 — APPROVED** [review]

**Comment by demeritcowboy** [comment]
Several of the "CheckBox" html type additions are actually Radios on the contact form. I'm not sure if that makes a difference where this data gets used. The confusing one is address location is_primary, which actually is a checkbox. But email, IM, open id, phone, etc are all Radio.

**Comment by colemanw** [comment]
I've thought about it some more and you're right they probably should be radios, but a special type of radio that spans multiple blocks. (e.g. if you have 3 email blocks on a form, the "is_primary" radio between all 3 blocks would be linked so only one can be selected). Still thinking about how to implement that on the Form Builder side. Marking this WIP for now.

**Comment by seamuslee001** [comment]
I think this looks right now @demeritcowboy ?

**Comment by demeritcowboy** [comment]
I'm good.

**Comment by eileenmcnaughton** [comment]
I'm still a bit icky  about the change  to radio - if  you  just showed one field then it would be a checkbox (& on  post save the others get changed). I'm not sure  if the html  type   is  actually used to display  them   though  so it's possibly ok - @jackrabbithanna does civicrm_entity determine  how  to  display fields based on html_type?

**Comment by colemanw** [comment]
@eileenmcnaughton yes I struggled with this too, but what eventually made the icky taste go away was considering:

1. This isn't a change since there's no metadata currently.
2. On civi forms they are already radios.
3. Checkboxes really doesn't make sense if you think about it. What does unchecking a box supposed to mean? You can't *not* have a primary.
4. This works great for afforms :)

**Comment by eileenmcnaughton** [comment]
@colemanw well afform is the way of the future .... OK

**Pull request merged**
