### PR TITLE
CRM-19346 - Enforce unique gender ids

### PR DESCRIPTION
**Pull request by ineffyble**
Add a rule to prevent two genders having the same ID.

---
- CRM-19346:
  https://issues.civicrm.org/jira/browse/CRM-19346

### CODE REVIEW

**Comment by seamuslee001** [comment]
@ineffyble can you fix the style?

**Comment by colemanw** [comment]
Why would two options ever be allowed to have the same id or value??

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by colemanw** [comment]
What about adding a unique sql index instead?

**Comment by seamuslee001** [comment]
@colemanw as in on value + option_group ?

**Comment by elisseck** [comment]
Reviewing this - Looks like a good idea to apply to anything... as coleman commented all option values should be unique not just gender. Can you make this more generalized e.g. put your change under the [global formRule](https://github.com/ineffyble/civicrm-core/blob/539088f5b8132291ef8d1817b618c9c02beb4f37/CRM/Admin/Form/Options.php#L350) and remove the condition that it only applies to group 'gender'? That would in theory cover a UI fix and then maybe a database fix as suggested above (that a user should never encounter) could potentially come later.

**Comment by ineffyble** [comment]
Closing in favour of #11089

**Pull request closed without merging**
