### PR TITLE
CRM-17175 - Support passing of custom field value in force mode to Ac…

### PR DESCRIPTION
**Pull request by davecivicrm**
…tivity Search.

---
- CRM-17175: Enable search activity by custom fields in force mode
  https://issues.civicrm.org/jira/browse/CRM-17175

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I've always wondered what the risk is in allowing any field in the url to be used as a default if the field exists on the form - we seem to have a sort-of whitelisting system where we add specific values adhoc on request but, I wonder if we shouldn't think about it the other way - ie on a search form what would be unsafe in the url? What about other forms?

**Comment by davecivicrm** [comment]
@eileenmcnaughton For search forms, allowing 'any' field that exists in the form seems like a good idea. Not sure if there are security implications??

**Comment by eileenmcnaughton** [comment]
Let's as Tim:-) ... @totten

**Comment by davecivicrm** [comment]
Test failure unrelated. Merging this improvement for now. Can replace with a more generic solution if @totten thinks it's a good idea and there are resources to implement.

**Comment by colemanw** [comment]
I can't think of a downside to allowing civi forms to accept url arguments. It'll still get validated in postprocess like everything else.

**Comment by totten** [comment]
On the policy question whether it's acceptable to use filters passed via URL, I think it's OK as long as some basic criteria are respected, e.g.

 1. The existence and content of the filter should be displayed so that the user knows what he's looking at. (We usually have the 'qill' to address this, or it also works to provide a form element pre-populated with the filter options.)
 2. The content of the filter is properly escaped (in both SQL and HTML).
 3. The page doesn't have any side-effects (e.g. deleting or modifying records).

AFAIK, our search pages generally meet these criteria.

**Comment by eileenmcnaughton** [comment]
FWIW - I recently did a sample extension (note the addition of the script that says blah) for someone that allowed parameters in the url - in their case they wanted price-options pre-defaulted https://github.com/eileenmcnaughton/alv.org.au.pagecustomisations/blob/master/pagecustomisations.php#L144

**Pull request merged**
