### PR TITLE
[REF] [Export] Stop passing exportParams & sqlColumns around

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Another minor export refactor

Before
----------------------------------------
Parameters needlessly passed around

After
----------------------------------------
Class methods used

Technical Details
----------------------------------------

Comments
----------------------------------------
Test cover is good

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@colemanw green tick on this now

**Comment by colemanw** [comment]
Much cleaner.

**Pull request merged**
