### PR TITLE
Ensure that keys are set in tabValues before hitting smarty

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Ensure that keys are set in tabValues before hitting smarty

Before
----------------------------------------
Use of isset in smarty template

After
----------------------------------------
template can rely on values being set (although it might need to differentiate between 0 and NULL with 'is_numeric'

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
This seems fine to me merging

**Comment by colemanw** [comment]
This caused a bug. Here's a fix #22040

**Pull request merged**
