### PR TITLE
Convert membership Import to use select2

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Convert membership Import to use select2 when selecting mapping fields

Before
----------------------------------------
Membership import uses a `hierselect` element but it it's actually hierarchical - it only collects the field name & the code to support the `hierselect` is just copy & paste

After
----------------------------------------
It's switched to using `select two`

Technical Details
----------------------------------------
@colemanw I am working towards an export-ui type approach on the Contribution import, which has some complexity. But I wanted to get the array right for select 2 and doing it for a simple import seemed like a good way to develop the code that delivers the array while also getting a code cleanup & a UI improvement on the membership import.

image

image

Old version - - I tried out the 'color' for the highligted fields & Coleman & I agreed to ditch it & the above is more consistent with other screens

image

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I pulled out https://github.com/civicrm/civicrm-core/pull/24357 to a separate PR - there are a couple more I can do that with, depending how quickly this moves

**Comment by colemanw** [comment]
@eileenmcnaughton is the "red" color for required fields?
IMO the asterisk is fine & making the text red is unnecessary as we don't do that anywhere else in the Civi UI AFIAK.

**Comment by eileenmcnaughton** [comment]
@colemanw yeah it is for required fields & is a feature on the existing import screen - I don't have a strong opinion on UI  but it would be a change to un-red it

**Comment by eileenmcnaughton** [comment]
@colemanw this is looking good now to me - let me know if you want me to break down the PR at all

**Comment by eileenmcnaughton** [comment]
thanks @colemanw

**Pull request merged**
