### PR TITLE
Credit note upon cancellation

### PR DESCRIPTION
**Pull request by guanhuan**
Allow credit note to be generated and downloaded when a invoice is cancelled.

### CODE REVIEW

**Comment by davecivicrm** [comment]
@guanhuan I think this change needs to go into 4.7 since it requires an upgrade - so this PR should be against the 'master' branch.

Upgrade for the msg templates should be in CRM/Upgrade/4.7.alpha1.msg_template/message_templates/contribution_invoice_receipt_html.tpl. You also need to commit the change to contribution_invoice_receipt_text.tpl in the Upgrade tree AND update both files in xml/templates/msg_templates folder.

Thanks!

**Comment by guanhuan** [comment]
Hi Dave,

Sorry to simply ignored that (should have done that). Is it possible for us to look to get this enrolled into 4.6.9?

Best

Guanhuan

**Comment by davecivicrm** [comment]
If critical, this can go in 4.6.9 if you're up for fully implementing and testing the upgrade.

Please review the example of msg template upgrades in CRM/Upgrade/Incremental/sql/4.6.3.mysql.tpl, e.g.
- include in that file
- create new folder and file (as in ../CRM/Upgrade/4.6.3.msg_template/civicrm_msg_template.tpl)
- commit updated versions of the 2 msg template files in that directory and in xml/templates

Then you should take a test 4.6.8 install, pull your patch, and run the upgrade process to verify that everything is working.

**Comment by guanhuan** [comment]
Hi Dave,

Thanks for the advice. I have added the update script and templates following the steps in your comment above and I did a test upon upgrading a clean 4.6.8 installation. The invoice+credit note is printed out as expected with default message template on cancelled contributions.

Let me know if there is anything you need for this to get pushed through.

Best

Guanhuan

**Comment by guanhuan** [comment]
jenkins, test this please

**Comment by davecivicrm** [comment]
Test failure is unrelated.

**Pull request merged**
