### PR TITLE
CRM-20529 fix incorrect file link display on custom record view

### PR DESCRIPTION
**Pull request by andrewpthompson**
A problem affected the view page for a custom field record. In CRM/Core/BAO/CustomField.php, the file ID was not provided to getFileURL() so the query in getFileURL() always returned the first file for a contact as it had insufficient info to find the right one if there were multiple.

This proposed change looks up the file ID from the civicrm_file table based on uri. This is not ideal (as file ID could have been passed through from other functions) but this seemed like the best way to fix without changing interfaces. I'm open to suggestions if there's a better way; my skills are pretty limited so I might need some pointers!

Also a change to CRM_Utils_File::getFileURL() returns a clean filename in the link rather than an obfuscated filename to make the display of the link on the custom field View pop-up consistent with that of the Edit pop-up.

**Steps to test patch:**
1. Create a custom field set with a file field and another field e.g. integer, and set to allow multiple records and display as tab with table. _(Note: you need the second field because if the custom field set only contains a file field then when a record is added an error is given, "One of parameters (value: -0) is not of the type Integer".)_
2. Add at least two records of this new type to a contact, with a different file attached to each record.
3. View (not Edit) the second record and the file link displayed is correct for the second file, with clean file name displayed in the link.

---

 * [CRM-20529: File custom field in multi-record field set displays first record's file for all records](https://issues.civicrm.org/jira/browse/CRM-20529)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins, ok to test

**Comment by seamuslee001** [comment]
Jenkins, ok to test

**Comment by lcdservices** [comment]
This patch works. I'm not crazy about using the uri as the lookup value to get details about the file record -- but there's nothing else of value passed to this function, so it's all we really have to work with. The hash value makes it unique, and so it should be fine to handle this way.

**Comment by andrewpthompson** [comment]
Thanks for reviewing Brian. Much appreciated.
In looking at this PR again I noticed that there is now a conflict which led me to find that the same issue was reported more recently in CRM-20779 and changes subsequently merged in `CRM/Core/BAO/CustomField.php`. I haven't looked at it properly yet but it could makes my changes to that file redundant, although I think the change to `CRM/Utils/File.php` is worth having so that clean file names are shown for View, consistent with Edit.

**Comment by andrewpthompson** [comment]
I have checked and CRM-20779 does mean that my change to `CRM/Core/BAO/CustomField.php` is no longer required. But my change to `CRM/Utils/File.php` so that clean file names are displayed in the custom field View (consistent with Edit) is still needed.

**Comment by eileenmcnaughton** [comment]
I went to check this & get 

screenshot 2018-03-23 19 37 19

I guess the changes are otherwise merged & this is obsolete

**Comment by andrewpthompson** [comment]
Yes closing this PR was the correct action. I didn't even notice this had happened but [CRM-21336](https://issues.civicrm.org/jira/browse/CRM-21336) made the same change for clean file URLs and the remainder was implemented in a different way by CRM-20779, so this PR was redundant. Thanks.

**Pull request closed without merging**
