### PR TITLE
Improve formatting for Tax Rate on price page template

### PR DESCRIPTION
**Pull request by mfrausto-mdw**
Overview
----------------------------------------
Improve "Tax Rate" format on price pages.

Before
----------------------------------------
Tax_rate_before

After
----------------------------------------
Tax_rate_after

Technical Details
----------------------------------------
This is only a template modification.

Comments
----------------------------------------
None.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
add to whitelist

**Comment by eileenmcnaughton** [comment]
That looks better & changing at the template level is the right place. Looks like this is your first Civi patch so thank you!

**Comment by mattwire** [comment]
@eileenmcnaughton @mfrausto-mdw We've tackled this at the php level in other places by casting to a float (eg. in event/contribution pages).  The problem with doing it this way at the template means we hardcode 2 decimal places which isn't necessarily desired.  Example here of the (preferred) way of doing it: https://github.com/civicrm/civicrm-core/blob/master/CRM/Financial/Form/FrontEndPaymentFormTrait.php#L65

The LineItem.tpl is included in lot's of places (including the contribution/event registration pages) so it's probably a case of switching more code to use the function linked above.

**Comment by eileenmcnaughton** [comment]
@mattwire ah yeah - OK

**Comment by eileenmcnaughton** [comment]
Where does this show up?

**Comment by eileenmcnaughton** [comment]
@mfrausto-mdw based on the above we need steps to replicate to progress this

**Comment by eileenmcnaughton** [comment]
Let's close this out for now since it doesn't seem to be an agreed fix - if we can get steps to replicate in a gitlab issue we can move forwards with it

**Pull request closed without merging**
