### PR TITLE
CRM-16243 - Activate extension dependencies

### PR DESCRIPTION
**Pull request by JohnFF**
Overview
----------------------------------------
Extension management involves multiple problems, such as:
 * *Download*: This is the process of *obtaining code* and *putting it on the filesystem*. For PHP applications, the *download* process must be able to identify *one specific version of each package* (the best-fit match that's mutually agreeable for all other packages). The downloader must also *acquire permission to write to the filesystem*, which can be a sensitive issue depending on the PHP application's security posture.
    * This corresponds to `CRM_Extension_Downloader` in `civicrm-core`.
    * Other tools like `composer`, `bower`, `drush make`, and `git submodules` also handle downloading code.
 * *Activation*: This is the process of *updating the local system configuration* -- eg *adding new tables* or *registering new option-values*. The *activation*  should address requirements like *activating/deactivating modules in the correct order* (to ensure that dependencies are available when executing their install logic).
    * This corresponds to `CRM_Extension_Manager` in `civicrm-core`.
    * In Drupal, this corresponds to the screen "Administration => Modules".
    * `composer`, `bower`, `drush make`, and `git submodules` do not handle activation. (At most, they provide a post-install *hook* where you can delegate to the real activation logic.)

This PR addresses only *activation*. Strictly separating *download* and *activation* poses some trade-offs:
 * _Upside_: We can make *incremental progress* -- we don't need to solve every edge-case of every workflow upfront.
 * _Upside_: Downstream integrators can/do/will customize their builds (picking different bits of code to download). The activation procedure is compatible with many different ways of getting the code.
 * _Downside_: There is *potential* for duplicated metadata (e.g. `info.xml` and `composer.json` both identify dependencies).
 * _Critique_: The risk of duplicated metadata is *speculation* since we don't actually have a full solution for downloading. *If and when* we have a canonical practice for downloading dependencies, then we can look at a tactical change to de-dupe the metadata. In the interim, the lack of *any* activation holds back *any/all* approaches extension dependency management.
 * _Aside_: This is the same path the Drupal ecosystem followed. First, the core project introduced support for *activation* of dependencies. Second, third-party efforts (for drush and composer) dealt with *download*.

Before
----------------------------------------
No dependency support for extensions.

After
----------------------------------------
Extensions may declare their dependencies in `info.xml`  using the `<requires>` tag:

```xml
<extension key="org.civicrm.cvform" type="module">
  <requires>
    <ext>org.civicrm.api4</ext>
  </requires>
</extension>
```

When activating the `cvform` extension, Civi will first activate `api4` (and any of its dependencies).

Technical Details
----------------------------------------
 * Resolving the correct order requires a *topological sort*. This is accomplished by importing the new library https://github.com/marcj/topsort.php

Comments
----------------------------------------
This feature was a long time in development thanks to bitrot. In previous PR's, discussions were derailed by consideration of the *download* issues. This PR is *only* dealing with activation.

---

 * [CRM-16243: Dependency management for extensions](https://issues.civicrm.org/jira/browse/CRM-16243)
 * (Note: Description rewritten by totten 2017-08-25.)

### CODE REVIEW

**Comment by seanmadsen** [comment]
I've added documentation for this PR here: https://github.com/civicrm/civicrm-dev-docs/pull/417

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
I have tested this on buildkit by downloading shoreditch and Mosaicothen trying to install Mosaico. It complained about missing flexmailer extension, downloaded it and refreshed list of extensions and was able to successfully install Mosaico after that. Then trying to disable flexmailer it complained that it was a dependancy for another enabled extension. After disabling Mosaico then i was able to disable shoreditch. 

On the whole this is a positive change and appears to work as is expected. Also the information was showing whether its requirements were being met.

A minor thing to include later on would be is to disable the install button if the requirements aren't met but i see this as being a secondary matter.

**Comment by totten** [comment]
jenkins, test this please

**Comment by eileenmcnaughton** [comment]
Any thoughts about syntax for a version of the dependency

  <requires>
    <ext>nz.co.fuzion.accountsync</ext>
    <ver>1.1</ver>
  </requires>

Seems most consistent

**Comment by JohnFF** [comment]
Agree

**Comment by seanmadsen** [comment]
In response to @eileenmcnaughton's [comment](https://github.com/civicrm/civicrm-core/pull/11101#issuecomment-338450071)...

Thinking _only about the XML_, I think it would be better to use attributes because if an extension has multiple dependencies, then this is clearer...

```xml
<requires>
  <ext ver="1.1">nz.co.fuzion.accountsync</ext>
  <ext ver="2.0">com.lolcats.icanhascheezburger</ext>
</requires>
```

than this...

```xml
<requires>
  <ext>nz.co.fuzion.accountsync</ext>
  <ver>1.1</ver>
  <ext>com.lolcats.icanhascheezburger</ext>
  <ver>2.0</ver>
</requires>
```

---

But thinking more broadly than just the XML...

My understanding is that this PR, as-is, doesn't do any version checking. If we are thinking about version checking, things get a bit more complicated. Do we want to support minimum versions and maximum versions? There was quite a bit of debate, before merging this PR, about whether to go with this `info.xml` approach or to develop functionality to manage extension dependencies with Composer (because the Composer project has already figured out how to address these complexities with dependencies). My knowledge on this topic is somewhat superficial, but my gut tells me that if we want improve extension dependency handling beyond the capabilities of this PR, then we're better off in the long run if we put our efforts towards Composer instead of building on top of this `info.xml` approach. That was essentially the outcome of a discussion we had at the UK sprint &mdash; merge this PR for now, because the work is already done, *then* aim towards eventually using Composer to manage extension dependencies.

**Pull request merged**
