### PR TITLE
Remove '$dao->free()' part 1

### PR DESCRIPTION
**Pull request by aydun**
See https://lab.civicrm.org/dev/core/issues/562

First round: remove lines exactly matching '$dao->free();'

### CODE REVIEW

**Comment by seamuslee001** [comment]
@aydun can you rebase against current master please

**Comment by seamuslee001** [comment]
Jenkins retest this please

**Comment by aydun** [comment]
@eileenmcnaughton @seamuslee001 This was a quick test - a bit of perl hackery adapted from previous mass changes to docs - to remove exact matches of '$dao->free();' under the CRM tree, and then see how the test suite reacted.  The tests ran cleanly here although I wonder how much the tests would actually pick up any issues related to this.

How do you want to segment and test this?  There are matches under other directories and places where the variable is not '$dao'    All can be picked up by tweaking the perl regexp.

Maybe:
- remove all '$dao->free()' 
- as above but variants of 'dao'
- examine other lines calling '->free()' - but excluding calls to `CRM_Core_Config::free()`

Each stage requires progressively more review.

**Comment by eileenmcnaughton** [comment]
@aydun I'm pretty confident about ripping these out - but I'd probably merge 3-4 files worth now & a few after the rc with an increasing pace - starting  with higher traffic files like CRM/Core/DAO.php perhaps in the first round since it would be there is we did see something.

**Comment by aydun** [comment]
@eileenmcnaughton Ok, here's 4 for starters

**Pull request merged**
