### PR TITLE
dev/user-interface#48 Update CiviCRM logo to new version & SVG

### PR DESCRIPTION
**Pull request by vingle**
Overview
----------------------------------------
Adds the more recent CiviCRM logo following [this Issue](https://lab.civicrm.org/dev/user-interface/-/issues/48). It is intended to replace this PR: https://github.com/civicrm/civicrm-core/pull/30443 - with updated CSS to use an SVG, and smaller file size for both svg and png.

Before
----------------------------------------
Uses PNG, 99px, pixely.

image

After
----------------------------------------
Uses SVG, 140px, vector so no pixels on zoom.

image

Technical Details
----------------------------------------
Both versions have transparent backgrounds.  This PR does use some absolute positioning - it would be better to use Flexbox - but that can be done at Theme level, for now this adopts the new logo with minimal changes to css.

Comments
----------------------------------------
The logo isn't being described for accessibility purposes. Using an important image as background image has been flagged as being not very accessible, as you can't add an alt tag to it.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@vingle this looks great - I completely trust you on this but perhaps we should be tagging in someone more qualified to review it than me?

**Comment by mattwire** [comment]
This seems a good one for @joshgowans to confirm?

**Comment by vingle** [comment]
Also @artfulrobot. Sorry to bring you into this PR, but – in the interests of minimizing changes – I'm replacing pixel-pushing CSS with even more pixel-pushing CSS. I'd welcome your input whether that's ok, as themes can/will rewrite this whole footer with better CSS. 

Also about defaulting to svg rather than png which seems sensible and gives much more theme & extension flexibility over the logo size, but maybe I miss something (am keeping both files there to preserve external/old links to the .png).

**Comment by vingle** [comment]
> Re pixel pushing, IDK where this is used exactly

@artfulrobot this is in Greenwich's civicrm.css. 

All you suggest is obvs better, (I'd also be ok with something like `empowered by <span class="sr-hidden civicrm-logo">CiviCRM, accompanied with a logotype of two interlocking green and blue triangles</span>`) but the reason I didn't is because Greenwich is hopefully soon to be replaced – and that's my priority over markup rewriting/cleanup because of the problem of breaking themes. 

For the original issue of updating the logo, this PR does that, and is only really as bad as the previous markup/css (maybe even a little bit better, because svg?).

**Comment by vingle** [comment]
> both these bits of work are to satisfy visual users that the branding is up-to-date and do nothing about accessibility

That's the bit where I pause. But do we know for sure that while it's not recommended, the current approach where the word CiviCRM text is hidden, is inaccessible?

> i.e. this commits us to 5 bits of work. Fix the markup now and it's potentially just this work (1); we might not even need more special CSS in themes.

My count is a bit different:

**Break markup**
1. initial work
2. themes need to update
3. those whose themes don't update (e.g. Shoreditch) might get unfortunate effects (made more complex that this code is for front-end display so likely has a bunch of people customising it).

**Don't break it yet**
1. initial work. It won't break Shoreditch or The Island as both still load core's civicrm.css. 
1.b - unrelated work - replacement of Greenwich with new theme architecture
2. update markup and related core css.
3. only themes not using the theme architecture need to update.

Tho actually now I see that for Aah probably 'don't break it' would take two steps. And both scenarios might break things for any end users who has styled the 'empowered by' region in anyway. I'm inclined to go back to Eileen's original PR which was just to swap the image files, no css or markup changes (just with smaller files).

**Comment by vingle** [comment]
>  I'm 99% sure that text in an SVG in a background image is not exposed [in an accessible way] to screenreaders

Ah I didn't mean the svg - the current markup looks like this:

```
<div class="crm-public-footer" id="civicrm-footer">
    empowered by <a href="https://civicrm.org/" title="CiviCRM.org - Growing and Sustaining Relationships" target="_blank" class="empowered-by-link"><div class="empowered-by-logo"><span>CiviCRM</span></div></a>  
</div>
```    

The span has visibility set to hidden so it's screen-reader fine I think (would be better with `sr-only`, obvs, but then there's quite a bit here that could be "2024 better").

**Comment by vingle** [comment]
Have reduced this PR to only change the images, following this discussion.
 - themes can change the CSS as they wish. They can also point to the SVG rather than the PNG.
 - at some point the markup may change, and themes will need to respond to that. But no point changing Eileen's original PR (just swapping the images) to do this now.

**Comment by eileenmcnaughton** [comment]
thanks @vingle -

jenkins - test this please

**Pull request merged**
