### PR TITLE
dev/core#2251 provide default receive_date

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fixes a fatal in a slightly obscure flow

Before
----------------------------------------
see https://lab.civicrm.org/dev/core/-/issues/2251

After
----------------------------------------
fixed

Technical Details
----------------------------------------

Comments
----------------------------------------
@demeritcowboy

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Thanks for the PR but I still get the same fatal error. This issue came up while looking at [another set of problems](https://lab.civicrm.org/dev/core/-/issues/2248) with the participant form and so it seems like something "higher up" has changed to cause several issues with this form. I'm not sure what though since it doesn't seem like the surrounding code has changed much.

**Comment by eileenmcnaughton** [comment]
hmm - I could swear it worked for me

**Comment by demeritcowboy** [comment]
I can check again but you can see it here in the test site logs too: http://core-19307-4mib6.test-3.civicrm.org:8001/admin/reports/event/57

(admin pass 8uGO5A1jjWmf)

**Comment by demeritcowboy** [comment]
Ok so I think this patch is actually against master and there's been other things elsewhere that have also changed that work alongside it to prevent the fatal in master, but when applied to 5.33 it's still fatal. Do you want to just put it against master?

**Comment by eileenmcnaughton** [comment]
@demeritcowboy OK - good idea

**Comment by eileenmcnaughton** [comment]
Ohh yay - it switched cleanly

**Comment by demeritcowboy** [comment]
Phooey now I can't even reproduce on stock master. So it seems something else between Dec 12 and now has been changed that fixed it separately.

What's also weird, but I'm not sure is worth tracking down for this, is that this PR should prevent you entering a blank date on edit, and yet with the PR it's still blank even after saving.

**Comment by demeritcowboy** [comment]
Ok for the second part I see that it's the empty string coming thru not a null, so it doesn't replace the empty string as the value. So I think that's actually correct, so my guess is that what has changed since 5.33 (somewhere) is that the empty string is not being converted to 0 anymore.

**Comment by eileenmcnaughton** [comment]
Hmm this is getting tricksy. My feeling is this patch is probably correct regardless as we should default the date to now if not provided & this is right before contribution create

**Comment by demeritcowboy** [comment]
That makes sense.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 we seem to have agreement to merge this - although the original problem still seems squishy

**Comment by seamuslee001** [comment]
@eileenmcnaughton so should this be rebased against 5.33 or kept as master then or is the consensus the 5.33 issue is separate?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I think merge on master - it is not clear that it fixes anything in 5.33, least of all a regression

**Comment by seamuslee001** [comment]
ok merging to master

**Pull request merged**
