### PR TITLE
Afform - Support ContactType-specific tabs and blocks

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
When adding an Afform to the contact summary as a block or a tab, this lets you pick which contact type(s) it should appear for.

Before
----------------------------------------
Blocks and tabs appear for all contact types

After
----------------------------------------
image

Comments
--------------
Adds test coverage where there was none before.

### CODE REVIEW

**Comment by seamuslee001** [comment]
@colemanw 

```
Fatal error: Uncaught Error: Class "api\v4\Api4TestBase" not found in /home/jenkins/bknix-dfl/build/core-25069-3c2q2/web/sites/all/modules/civicrm/ext/afform/core/tests/phpunit/Civi/Afform/AfformContactSummaryTest.php:9
```

**Comment by colemanw** [comment]
@seamuslee001 - yea I've seen that before. The only other unit test in `civicrm/ext/*` to try to use `Api4TestBase` suffered the same fate and @eileenmcnaughton hacked around it with
https://github.com/civicrm/civicrm-core/blob/5f0a735dd66f1eed860235ae108a743657939465/ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php#L4-L5

So I could do the same thing here, but it's kinda ugly. I suspect the underlying problem is that when Jenkins runs unit tests from `civicrm/tests/phpunit/*` it registers that directory as either an include path or a PSR root, but when it runs unit tests from `civicrm/ext/*` it registers the tests directory in the extension as a root but not the core tests directory.
That's my hunch but I have no idea where to go looking to test that hypothesis. Do you?

**Comment by seamuslee001** [comment]
@colemanw AFAIK when extension unit tests are run nothing in the Core's tests/ folder is ever loaded for it.

**Comment by seamuslee001** [comment]
also this is the stock standard phpunit bootstrap that is created for extensions https://github.com/civicrm/civicrm-core/blob/master/ext/elavon/tests/phpunit/bootstrap.php#L6 and basically does this https://github.com/civicrm/cv/blob/master/src/Command/BootCommand.php#L25

**Comment by colemanw** [comment]
@seamuslee001 how would you add the `civicrm/tests/phpunit` directory to that loader?

**Comment by colemanw** [comment]
I don't want this issue blocked so I've pushed up the same woraround as used in SK. Hopefully temporary.

**Comment by seamuslee001** [comment]
Generally my thought is that if I'm writing tests for an extension nothing in the core tests/ folder is available to me

**Comment by colemanw** [comment]
Well this is a core extension so the line is a little blurrier, and the APIv4 test base has some really useful stuff in it. Potentially we could move that useful stuff into a trait that's in a different directory if that would help.

**Comment by seamuslee001** [comment]
generally when we have wanted to have test functions available to extensions (core ext or others for me its the same its an extension test not a core test) then they have been moved into the Civi/Test/ folder e.g. the ContactTestTriat, the ACLPermissionTrait etc

**Comment by eileenmcnaughton** [comment]
I think we have been trying to add some test helpers to core to be available to extensions - but very immature - the most obvious is the trait with `callApiSuccess` etc - but we are kinda moving away from that.

I had assumed that `Civi::test` would have the various helpers (since extensions run tests on deployment installs)

**Comment by colemanw** [comment]
OK if someone can MOP this one I'll follow-up with the tidy-ups.

**Comment by colemanw** [comment]
Test fails are unrelated

**Comment by eileenmcnaughton** [comment]
@colemanw I just tested this & got 2 e-notices - one which I think is possibly caused by this 

image

(Am ok for this to  be merged & that to be a follow up)

**Comment by colemanw** [comment]
Followed-up with https://github.com/civicrm/org.civicrm.contactlayout/pull/123

**Pull request merged**
