### PR TITLE
NFC ensure that git is fully uptodate when running distmaker

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @totten

### CODE REVIEW

**Comment by totten** [comment]
I need more context description.

FWIW, I'm initially -1 due to one use-case. Suppose you're developing a patch to `distmaker` and need to test it locally (to ensure that it produces the correct tarballs).  The process is rather fiddly because of the `git checkout` stuff, e.g. you have to say:

```bash
cd distmaker
vi dists/foo.sh
git commit -m 'WIP - Trying to patch foo.sh'  dists/foo.sh
./distmaker.sh all
## Wait while it runs...
## Check the resulting tarballs.
## Uh oh, something was wrong. We need to revise.
vi dists/foo.sh
git commit --amend dists/foo.sh
./distmaker.sh all
## Ah, that's better. Cleanup the commit mesage.
git commit --amend
```

Basically, if you want to iterate on `distmaker` and produce a decent-looking patchset, then you need to do a bit of rewriting history (squashing or amending commits). If `distmaker` is *also* doing a `git pull` as part of the process, then rewriting that history is going to get mind-bending.

Perhaps you could describe more about the problem scenario leading to this PR?

**Comment by seamuslee001** [comment]
Hi Tim, What i have found is that i have a build with type dists that i use to generate dists Sometimes of 4.6 and sometimes of 4.7. But i use a different civibuild for my main coding, So when i go to generate a dist I make sure that distmaker.conf has correct branch and then running ./distmaker.sh all it only uses the code it has currently, It doesn't go and check if there have been updates in the remove, I have to manually do a git pull to make that happen if its been "stale" for like at least a couple of weeks

**Comment by eileenmcnaughton** [comment]
@seamuslee001 what do you want to do here? Close due to lack of interest or try to convince Tim?

**Comment by seamuslee001** [comment]
closing this as i think this will be too complicated to manage this way

**Pull request closed without merging**
