### PR TITLE
dev/core#142 Add chain select to state and counties in Search Builder

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
The Search Builder state and county fields don't filter with reference to the country or state fields that are within the same AND grouping. The state field displays the states from the countries that have states enabled, and the county field displays all counties in alphabetical order.

Proposal:
1.  Make the states drop-down depend upon a country of the same location type, within the same "AND" grouping. Do the same for the counties with regard to the states. This would require some kind of parameter to be sent to the address/getoptions API to filter the list, but it would make them work in the same way as elsewhere in CiviCRM.
2. If there are no counties present for a state or no state present for a country, then render empty select list.

Before
----------------------------------------
State/Counties don't reload on changing country/state respectively in Search builder for same location type.

After
----------------------------------------
State/Counties reload on changing country/state respectively in Search builder for same location type (here as per screencast check that two location type used Home and Billing)
test-multiple-after

### CODE REVIEW

**Comment by monishdeb** [comment]
ping @colemanw @agh1 @lcdservices

**Comment by MegaphoneJon** [comment]
@monishdeb you say, "Make the states drop-down depend upon a country of the same location type".  Does this imply that the country field is now a required field to search by state/province in Search Builder?

**Comment by agh1** [comment]
@monishdeb @colemanw In playing around with this, I did find a somewhat serious problem: when a Country field changes, all State/Province fields with that location type change their options, even within other "Also include contacts where" groupings.  To recreate, let's say you are planning an event in Detroit:

1. Search for contacts in Michigan:

   ```
   Contacts | Country | Home | = | United States
   Contacts | State | Home | = | Michigan
   ```

2. Search for contacts in Ontario by clicking "Also include contacts where" and setting up:

   ```
   Contacts | Country | Home | = | Canada
   Contacts | State | Home | = | Ontario
   ```

Notice that the state dropdown where Michigan had been selected now has nothing selected and offers only Canadian provinces.

**Comment by monishdeb** [comment]
Thanks @colemanw for merging this PR.

@MegaphoneJon not quite, I would say on presence of country field IF there is a state filter selected which got same location type as of country, it will reload the select list as per selected country. If there is no country present, state will simply populate the states of default country configured. And I agree I should have documented this fact in my PR description.

@agh1 if you find any other issue/miss please create a separate issue and assign to me and thanks for your feedback :)

**Comment by monishdeb** [comment]
@agh1 so as per the expected behaviour I think change on country field should only affect the block where the selection made? Like here it shouldn't affect the state field under  "Also include contacts where" but all state fields under "Include contacts where"?

**Comment by agh1** [comment]
@monishdeb exactly--the markup looks like each section is in its own div with the class `crm-search-block`, which may help with narrowing the selector.

**Comment by monishdeb** [comment]
Yup agree, would you like to create a issue on gitlab and assign it to me?

**Comment by agh1** [comment]
@monishdeb no prob.  I opened [https://lab.civicrm.org/dev/core/issues/150](dev/core#150) though I can't change assignments.

**Comment by colemanw** [comment]
Good catch. Thanks @agh1

**Comment by colemanw** [comment]
@agh1 can you please check https://github.com/civicrm/civicrm-core/pull/12230

**Pull request merged**
