### PR TITLE
I have no words

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
I found something so bad it will still surprise you.... nearly 14 years ago the function being re-written was renamed `postProcessOld` and has survived ever since - through multiple cleanups....

https://github.com/civicrm/civicrm-svn/commit/b38c7439ae5547a3e2cf0da7688c09c958edf33f#diff-cd4c018f48220049f23ad56d9a9d8b02db5b3e7bc4d6d36294ce4278a38f87acR256

@colemanw @seamuslee001 @totten @demeritcowboy I win the 'find the worst code competition' - give up now

### CODE REVIEW

**Comment by seamuslee001** [comment]
Excellent work there

**Comment by demeritcowboy** [comment]
Yeah I think you get to wear the crown. For now...

I thought I might [have this beat](https://github.com/civicrm/civicrm-core/pull/15736/files). It's older but not in terms of how long it lasted.

The `$$` variables PRs from a while ago might be close.

In recent memory there was @colemanw's `if (data && !data)`: https://github.com/civicrm/civicrm-core/pull/23188/files#diff-e1b49e1fa048ef40357b75c1a7c096fd2d154708ac7623afc4bcafd5c6fd02eeL103

**Comment by eileenmcnaughton** [comment]
@demeritcowboy yeah seems there were a few contenders!

**Comment by colemanw** [comment]
Just let @eileenmcnaughton have her moment of glory.

**Pull request merged**
