### PR TITLE
dev/core#2486 - Add foreign key on civicrm_contribution_product.product_id 

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
 Add foreign key on civicrm_contribution_product.product_id 

Before
----------------------------------------
No foreign key on product ID 
 
After
----------------------------------------
Added foreign key on civicrm_contribution_product.product_id (on delete null)

Technical Details
----------------------------------------
Followup PR of https://github.com/civicrm/civicrm-core/pull/20505  

Comments
----------------------------------------
ping @colemanw @eileenmcnaughton @seamuslee001 

(should we target this patch after 5.39-rc cut??)

### CODE REVIEW

**Comment by colemanw** [comment]
Jenkins says:
```
mysql:
ERROR 1215 (HY000) at line 3829: Cannot add foreign key constraint
```

**Comment by seamuslee001** [comment]
@monishdeb can you rebase this please?

**Comment by monishdeb** [comment]
Thanks @seamuslee001 for notifying the conflict. Rebased now.

**Comment by colemanw** [comment]
This looks good. Thanks @monishdeb

**Pull request merged**
