### PR TITLE
Extension Page Tabs

### PR DESCRIPTION
**Pull request by JohnFF**
Overview
----------------------------------------
Members of our community across the world work hard to develop great new extensions for CiviCRM. These extensions contain innovative new features, exciting improvements, and make CiviCRM even more useful for the organisations that proudly use it. Unfortunately, the extensions screen shows them in one long list. Unable to see the wood for the trees, many sysadmins leave the repository empty handed. This submission aims to resolve that.

The rules:
1. Each extension may have only one category. This is to prevent developers adding a category only tangentially related to their extension.
2. The extension's category is set in the info.xml file. There is currently no technical restriction on what category may be used. This allows site admins to make their own categories. The aim is that the Extension Review team would enforce a minimalist naming structure.
3. Some categories get their own tab, some are included on other tabs (e.g. Payment Processors are included under "Finance")
4. "Utilities" is used where ever an extension didn't fit into another category.
5. Default categories were included. If you are an extension maintainer, please **do not edit** the default json file, but instead alter the extension's info.xml file.
6. Extensions are ordered within their category by their status. This is currently alphabetical, and could be easily replaced with a better ordering system.

Before
----------------------------------------
old_extensions_screen

After
----------------------------------------
screenshot_20181011_020304

Technical Details
----------------------------------------
Loads defaults from a json file, throws an Exception if it can't be found.

Comments
----------------------------------------
2 more changes to make at the point of writing: Renaming from "AddNew" to "Category" or "Tab", and making the tab names all lowercase.

### CODE REVIEW

**Comment by mattwire** [comment]
Have you seen the work done previously by @twomice https://github.com/twomice/org.civicrm.extensionsui

There was a long discussion at last years sprint.  We didn't think this approach was a good idea because:
1. It relies on the maintainer of each extension updating their own extensions (ie. info.xml).
2. It does not allow classification to be done in the extensions directory.

I think the preferred solution is to add/replace the existing metadata system on civicrm.org so that all "metadata" can be centralised, changed in one place and reflected via any UI that implements the extdir (or a new) API.  This allows (for example):
1. An extension to be marked as broken.
2. An extension to be marked as popular.
3. Categories to be assigned/removed.
4. Comments/reviews/ratings to be added.

Any changes in this area will require discussion and concept approval first, so we should reference it back to a gitlab issue, for example see here: https://lab.civicrm.org/extensions/extensions-directory/issues

**Comment by totten** [comment]
John and I are talking at the Bamford sprint about how to reconcile the approaches. @twomice @GinkgoFJG @mattwire, perhaps we could get on the phone today to chat a little about it?

**Comment by JohnFF** [comment]
Hi @totten - just wondering if there's more you'd like me to do on this in the meantime, and what the status of it is?

**Comment by eileenmcnaughton** [comment]
Sadly @johnff is not doing civi stuff now :-(

This  is not mergeable yet due to some blockers outside it &  movement appears to be in the extension now.

Closing this & tracking through gitlab https://lab.civicrm.org/dev/core/issues/1303

**Pull request closed without merging**
