### PR TITLE
CRM-20441 Check to see if user has permission on the activities befor…

### PR DESCRIPTION
**Pull request by seamuslee001**
…e getting rest of information. If fails silently remove the activity from the list of ids

### CODE REVIEW

**Comment by seamuslee001** [comment]
ping @eileenmcnaughton @colemanw @lcdservices

**Comment by seamuslee001** [comment]
@davejenx can you try testing this PR out on your code base

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I agree with this as a fix for the rc but can we add some more code comments to clarify that this is likely not the final fix - ideally both the api & the form should follow the same rules for displaying activities - but we need to be clear about what portion of the contacts they need to have access to to see the activity. I'm pretty sure 'all assignees' is not required.

**Comment by seamuslee001** [comment]
@eileenmcnaughton i have added some comments didn't mention API and form specifically but i think the gist is clear

**Comment by lcdservices** [comment]
I agree with the patch. But also agree with the MM conversation that we probably only need the user to have access to one of the connected contacts in order to have permission to see the activity.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 couple of test fails.

**Comment by seamuslee001** [comment]
@eileenmcnaughton tests should be fixed now

**Comment by eileenmcnaughton** [comment]
Happy to merge as a temporary fix per discussions, given we are in rc mode

**Pull request merged**
