### PR TITLE
dev/core#4833 Add unit test for legacy invoice number format

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This adds a unit test to compliment the fix from @twomice https://github.com/civicrm/civicrm-core/pull/28474

Before
----------------------------------------
No unit test for legacy format

After
----------------------------------------
Unit test

ping @mattwire @eileenmcnaughton

### CODE REVIEW

**Comment by seamuslee001** [comment]
Test fail as expected because test run started before #28474 was merged

```
Test Result (1 failure / ±0)
CRM_Core_Payment_AuthorizeNetIPNTest.testLegacyInvoiceNum
```

**Comment by twomice** [comment]
Wow, thanks @seamuslee !

**Comment by seamuslee001** [comment]
Test fails this time seem unrelated

Jenkins re test this please

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Comment by eileenmcnaughton** [comment]
Obviously you are the jenkins whisperer @demeritcowboy

**Pull request merged**
