### PR TITLE
Fetch line items from correct contribution when repeating a contribution

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Alternate to https://github.com/civicrm/civicrm-core/pull/16826

Before
----------------------------------------
The code was correctly calculating the contribution to use as a template, but allowing a different contribution to be the potential line item source

After
----------------------------------------
line items retrieved from template contribution

Technical Details
----------------------------------------

Comments
----------------------------------------
@pradpnayak I've taken your test but am using a different fix which bypasses rather than changes the code you were touching

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton looks like most of the test failures relate

**Comment by eileenmcnaughton** [comment]
The remaining problem is a test set up problem (it works in isolation but is probably a bit silly)

**Comment by pradpnayak** [comment]
Hi @eileenmcnaughton 
Yes your fixed worked. for my use case.
Thanks !

**Comment by seamuslee001** [comment]
@eileenmcnaughton this test failure looks related https://test.civicrm.org/job/CiviCRM-Core-PR/34032/testReport/junit/(root)/CRM_Contribute_BAO_ContributionRecurTest/testAutoRenewalWhenOneMemberIsDeceased/

**Comment by yashodha** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
turns out test issue was a static var.

**Comment by eileenmcnaughton** [comment]
@pradpnayak this test has started failing because the date checks are only valid up until some point in time - if you have a chance to double check...

**Pull request merged**
