### PR TITLE
[NFC/Test] Unit test activity-contact variations

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
This tests various activity contact variations when creating/updating an activity. It may overlap some existing tests and may not contain every possible variation but gives some peace of mind.

c.f. https://github.com/civicrm/civicrm-core/pull/18609

Technical Details
----------------------------------------
Mostly it creates an activity with or without some targets/assignees, and then updates the activity changing the targets/assignees.

Comments
----------------------------------------
I also did a local run where I converted it to not use an array as the parameter when the array only had 1 element. It failed on the same things before and after 18609, so something for another day.

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by demeritcowboy** [comment]
Those were probably real fails because the other tests in the file probably aren't expecting the added contacts. I'll see if I can update.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
hmm twice now it has failed on the same thing

```
PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 20480 bytes) in /home/jenkins/bknix-dfl/build/core-18619-8wfoo/web/sites/all/modules/civicrm/CRM/Utils/API/HTMLInputCoder.php on line 179
```

**Comment by eileenmcnaughton** [comment]
I saw that on a different PR too

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Comment by demeritcowboy** [comment]
Can someone sanity check what I'm looking at? https://github.com/civicrm/civicrm-core/blob/5653540610b4dba449c920857bd86f9ed53ab0ac/tests/phpunit/CRM/Utils/Mail/EmailProcessorTest.php#L161

It assigns it the result to $groupID, but the return value is not an int/id it's the array result from the api call. Then it uses it in the next line as an id, which when it reaches replaceGroups() https://github.com/civicrm/civicrm-core/blob/5653540610b4dba449c920857bd86f9ed53ab0ac/CRM/Mailing/BAO/Mailing.php#L1746 is then a big array not an id.

I've confirmed locally by adding a print_r($values) just after there.

It doesn't explain why it's all of a sudden crashing now, but how did that ever work?

**Comment by eileenmcnaughton** [comment]
@demeritcowboy yeah looks wrong! I wonder if the memory crashes are just a threshhold thing - I feel like there is a small memory leak somewhere & this just adds a bunch more places it can happen pushing it over a limit

**Comment by seamuslee001** [comment]
jenkins retest this please

**Comment by demeritcowboy** [comment]
Yay!

**Pull request merged**
