### PR TITLE
dev/core#1485 Fix field name for join_date to be membership_join_date…

### PR DESCRIPTION
**Pull request by seamuslee001**
… in line with the DAO schema

Overview
----------------------------------------
This matches the changes for start_date and end_date as per https://github.com/civicrm/civicrm-core/blob/master/CRM/Upgrade/Incremental/php/FiveEighteen.php#L75 

Before
----------------------------------------
Join date ignored when importing memberships

After
----------------------------------------
Join date if supplied in the file is respected

ping @eileenmcnaughton

### CODE REVIEW

**Review by jamie-tillman — COMMENTED** [review]
I pulled the file from your PR and ran an import, however, and it did not work.  It utilized today's date on the import.

The final piece of the puzzle is adding the membership_join_date key to the $changes array in lines 708-712.  If the key isn't renamed to 'join_date', then the create() method won't pick it up.  That method only looks for 'join_date'.

**Comment by jamie-tillman** [comment]
> 
> 
> I pulled the file from your PR and ran an import, however, and it did not work. It utilized today's date on the import.
> 
> The final piece of the puzzle is adding the membership_join_date key to the $changes array in lines 708-712. If the key isn't renamed to 'join_date', then the create() method won't pick it up. That method only looks for 'join_date'.

I modded the $changes array to add the new key and an import worked with your changes, so I would anticipate that minor addition completing the fix.

**Comment by seamuslee001** [comment]
ok done so now @jamie-tillman

**Comment by eileenmcnaughton** [comment]
I was able to write a unit test for this that I will put up separately but fix looks good & @jamie-tillman has tested /r-run it so I'm merging

**Comment by eileenmcnaughton** [comment]
Test commit here https://github.com/civicrm/civicrm-core/pull/16127

**Pull request merged**
