### PR TITLE
CRM-20805 : Fatal Error when adding new membership type on a contribu…

### PR DESCRIPTION
**Pull request by jitendrapurohit**
…tion page  https://issues.civicrm.org/jira/browse/CRM-20805

### CODE REVIEW

**Comment by seamuslee001** [comment]
@jitendrapurohit Jitendra can you take a look at the test failure here. Also @yashodha would this potentially fix in CRM-20760?

**Comment by seamuslee001** [comment]
I have tested this in a specific situation as per my comment here https://github.com/civicrm/civicrm-core/pull/10548#issuecomment-310572377 I can confirm this patch still ensures that you cannot enable price fields if the Financial Type associated with the price field is disabled

**Comment by jitendrapurohit** [comment]
Fixed the failures listed by jenkins. Thanks for notifying @seamuslee001

**Comment by eileenmcnaughton** [comment]
Looks like @seamuslee001 has OKd this plus @jitendrapurohit has written a test (yay). My assessment of the code is that it absolutely makes sense & appears safe, merging

**Comment by yashodha** [comment]
works great!

**Comment by eileenmcnaughton** [comment]
Thanks for the confirmation @yashodha

**Pull request merged**
