### PR TITLE
CRM-21765: Commit files to git which are static but are generated from CodeGen like DAO files

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Add `SchemaStructure.php` and `langs.php`  to git, reducing the need to run `GenCode`.

Before
----------------------------------------
 * The files `SchemaStructure.php` and `langs.php` do not exist in git. 
 * To get these files, you must either download the tarball or run GenCode.

After
----------------------------------------
 * The files `SchemaStructure.php` and `langs.php` are stored in git.
 * If you run GenCode, then these files will be updated. However, you generally don't need to update them.

---

 * [CRM-21765: Commit files to git which are static but are generated from CodeGen like DAO files](https://issues.civicrm.org/jira/browse/CRM-21765)

### CODE REVIEW

**Comment by totten** [comment]
Ah, the test raises an interesting point that the generated code doesn't pass style guidelines. We haven't noticed because the file was never checked by CI before. 

In theory, `GenCode` has a reformatting mechanism (part of `CRM_Core_CodeGen_Util_Template`) to address style issues, but it's not perfect. You could fiddle with the template or the formatter, but..

It's probably easier to grant an exception for auto-generated code. We did that a long time ago for DAO's, like this: https://github.com/civicrm/civicrm-buildkit/blob/f55cdde/bin/civilint#L54-L55

**Comment by monishdeb** [comment]
Thanks @totten for notifying that and I have now created a PR https://github.com/civicrm/civicrm-buildkit/pull/392 to skip those two files from civilint check

**Comment by totten** [comment]
OK, merged the update for `civilint`.

Before we had the `civilint` exception, did you by chance try manual edits on the `CRM/Core/I18n/SchemaStructure.php` and `install/langs.php`? The reason I ask... after running `GenCode` locally, I wind up with slightly different files. (And the differences look like style fixups.) But I think it'll get confusing if the committed files differ from the generated files.

Maybe go back to the unedited files? Or maybe update `xml/templates/schema_structure.tpl` to make the edits more durable?

**Comment by monishdeb** [comment]
@totten yes you are right I did manual edit before I got your comment. So now I have regenerated those two files and updated the patch. Hopefully civilint doesn't pick up the style error this time :)

**Comment by totten** [comment]
Thanks, @monishdeb ! The results are now consistent across multiple runs of GenCode.

**Pull request merged**
