### PR TITLE
Add enableSimpleExtension upgrade function

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
@totten per our discussion here is the upgrade function we talked about. Now the question is from where to run it.
Ideally I think it would run up-front before any of the incremental steps, regardless of what version we're coming from (so even if we're upgrading from 5.0.0 it would first enable the core extensions before running any upgrade steps). Is there a place for that?

### CODE REVIEW

**Comment by totten** [comment]
@colemanw These places come to mind for me, based on different theories/rationales.

1. Theory: "The component-extensions are special pre-requisites that need to be addressed before the upgrader can execute."
    * See https://github.com/civicrm/civicrm-core/blob/ee5ca931e84d39118c047f2a307342f4681f480a/CRM/Upgrade/Form.php#L475-L478 (which calls a pre-upgrade step, `CRM_Queue_BAO_QueueItem::findCreateTable`)
2. Theory: "There's already a step to enqueue component-extension activation, which almost works. Update it to use `enableSimpleExtension()` and to apply an earlier `$weight`."
    * See https://github.com/civicrm/civicrm-core/blob/854a117f56a31504be219e568cc6bddb08c16c24/CRM/Upgrade/Incremental/php/FiveSixtyThree.php#L44-L46
    * Variant 2a: Set the weight to run right before `doCoreFinish()`.
    * Variant 2b: Set the weight to run amongst the `FiveSixtyThree` stuff (before any `FiveSixtyFour` stuff).

Verbalizing a bit about that...

* We have incomplete information about the circumstances of failures.
* As I understand, the operative theory is: Problems arise when `doCoreFinish()` flushes the system - which emits an open-ended invitation for other subsystems to act. These other subsystems presumably depend on CiviContribute/CiviEvent/CiviMember/etal and fail because they're not installed yet.
* This implies that the upgrade-process runs as far as `doCoreFinish()` -- which means that all the regular/preceding steps  (`upgrade_5_60_alpha1()`, `upgrade_5_61_alpha1()`, etc) completed successfully.
* Variants (1), (2a), and (2b) should all have the same effect on `doCoreFinish()`. They all put the activation before the risky part.
* They differ in their impact on regular-steps (`upgrade_X_Y_Z()`). Specifically, can regular steps rely on loading classes like `Civi\Api4\Contribution` (et al)?
    * Variant (1) means that *all* regular `upgrade_X_Y_Z()` functions can rely on loading `Civi\Api4\Contribution`  (*assuming the component is enabled*).
    * Variant (2a) means that *no* regular `upgrade_X_Y_Z()` functions can rely on loading`Civi\Api4\Contribution`  (*assuming the component is enabled*).
    * Variant (2b) means that *some* regular `upgrade_X_Y_Z()` functions can rely on `Civi\Api4\Contribution` (*assuming the component is enabled*).
    * (*Class-loading may or may not be sufficient to make the upgrade steps be good/bad/useful/risky. There's also the question of how metadata changes interact with upgrade-paths. And if you wind-up skipping upgrade-steps for inactive component-extensions, then that's another can of worms.*)
* They differ in how "special" or "conventional" they feel.
    * Variant (1) is a very special (unconventional) place to put an upgrade step.
    * Variant (2a) is a somewhat special (somewhat conventional) place to put an upgrade step.
    * Variant (2b) is an unspecial (very conventional) place to put an upgrade step.

Viewed through the operative theory (as I understand it), _these variants are a distinction without a difference_. They're all plausible. They're all provisional (*limited by our incomplete information of the problems*).

I only see how to differentiate them based on one's general/prior attitudes toward upgrade-logic and conventionalism. My prior attitudes would favor (2a) (_right before doCoreFinish_) or maybe (2b) (_amongst FiveSixtyThree steps_). I might be skeptical of (1), though I can't rule it out either (*since our knowledge of the problem-scenarios is incomplete*).

**Comment by colemanw** [comment]
Thanks for verbalizing all that @totten. I want to add some more evidence for Theory 1:
- The `eventcart` extension moved classes out of core
- The `financialacls` extension moved classes out of core
- The `legacycustomsearches` extension moved classes out of core
- The `sequentialcreditnotes` extension moved classes out of core
- The `ckeditor4` extension moved classes out of core
- `civigrant` moved an entire component's worth of classes out of core!
- And of course, `civi_case`, `civi_event`, et.al.

I think this comment describing the `financialacls` extension sums up the thrust:

https://github.com/civicrm/civicrm-core/blob/45f06fc823ed473b751f9774c09c4bc310cc2eed/ext/financialacls/info.xml#L26

Or, in more detail, [this commit message](https://github.com/civicrm/civicrm-core/commit/38c87aa27801454de6ba9864a34d4068e1f2fe0d) says, in-part:

> ...this approach permits an  incremental cleanup-up-to-separation  process. For example we could create an  extension for  a feature and move some code to it and later move some other code...

So, since 2020 @eileenmcnaughton and others have been working to gradually move php classes out of core and into core-extensions. In theory that's a perfectly safe thing to do, as long as we force-enable the extension, the class will still be available just as it always was. However, the one increasingly glaring flaw with that assumption is the upgrader.

- I recall several upgrade-related bugs caused by the `legacycustomsearches` code removal.
- I believe the same sort of thing affected `civigrant`.
- Now we're hitting it with APIv4.

But based on the direction all this code is moving in, I don't think we can expect it to stop, and I don't think we can safely predict exactly which classes are needed by what code when. But since the goal is to LExIM-ify core code, I think we need to safeguard our upgrades both for now and for future migrations.

**Comment by totten** [comment]
@colemanw That confuses me. Yes, certainly, we agree that reorganizing code around extensions is a generally good long-term project. But I don't follow how that supports (1) -- the idea that component-extensions should be activated as pre-upgrade steps.

>  as long as we force-enable the extension, the class will still be available just as it always was. 

What is a class from `eventcart`, `financialacls`, `sequentialcreditnotes`, `legacycustomsearches`, or `ckeditor4` that needs to be available during the execution of the core-upgrade? I mean, you're saying that we've moved all these things from core-core to core-ext. Great. And we did without (1). I'm searching the core-upgrade code, and I don't see anywhere that it calls classes from these exts.  (*But it's a lot of code - maybe I'm just missing it.*)

It seems good that we *don't* have those calls. It means fewer dependencies for the upgrader. It means that you can (e.g.) reorganize the class-logic of `ext/legacycustomsearches` and be confident that the core-DB upgrader will still work. Also, the point of extensionization is to make smaller, more independent units. If we preemptively encourage core-upgrade steps that depend on classes from core-exts, then aren't we moving in the opposite direction (*encouraging more of the covert dependencies that are risky/hard-to-debug*)?

**Comment by colemanw** [comment]
@totten I don't see option 1 as encouraging or even supporting coupling between core upgrade code and extension code. Rather I see it as preventing lots of upgrade crashes that are going to frustrate our users and make CiviCRM seem unstable when anything happens like:
1. A hook fires during upgrade, and someone's custom code calls a BAO function that's been moved
2. Someone's `hook_civicrm_container` implementation relies on a core class that's moved
3. Any php class at all contains a `use` statement which brings the whole system crashing down

My point was that the pace of these core -> ext migrations is increasing, and we should do everything we can to prevent that process from making CiviCRM unstable or unusable. How confident are we, for example, that the entire contents of the `CRM/Contribute` directory could be moved into the `civi_contribute` extension without any of the above tripping us?

**Comment by colemanw** [comment]
I think we can sit on this unless we get more confirmed bug reports. The check added in #27453 may be sufficient for now.

**Pull request closed without merging**
