### PR TITLE
CRM-20590, add pre and post hook invocation for delete and create/edi…

### PR DESCRIPTION
**Pull request by pradpnayak**
…t option

----------------------------------------
* CRM-20590: Add pre and post hook for EntityBatch
  https://issues.civicrm.org/jira/browse/CRM-20590

### CODE REVIEW

**Comment by pradpnayak** [comment]
Jenkins re test this please

**Comment by pradpnayak** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
I think we should put a create function into CRM_Batch_BAO_EntityBatch and put these hooks (& functions) in there. This is currently a bit of an inconsistent construct, & trying to add hooks to it highlights that

**Comment by pradpnayak** [comment]
Makes sense. I will update the changes soon.

**Comment by pradpnayak** [comment]
@eileenmcnaughton I have pushed the changes suggested by you. Can you please review?

**Comment by colemanw** [comment]
Looks good.

**Pull request merged**
