### PR TITLE
Fixed Coding Styles

### PR DESCRIPTION
**Pull request by sujit-baniya**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
Note that our coding standards are https://www.drupal.org/coding-standards

**Comment by colemanw** [comment]
Can you please explain the purpose of this PR? It does not appear to be about coding style. Is there an issue for this?

**Comment by itsursujit** [comment]
I was given a task to fix the issue as per the job requirement. I think the
other developers had some better solution for PR. You can deny the PR.

On Mon, Mar 14, 2016 at 3:29 AM, colemanw <notifications@github.com> wrote:

> Can you please explain the purpose of this PR? It does not appear to be
> about coding style. Is there an issue for this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/7858#issuecomment-196057992>
> .
>



-- 

Kind Regards!

*Sujit Prasad Baniya  *
Senior Software Engineer, Deerwalk Services Pvt. Ltd
*PHP/MySQL Consultant*, Winrock International
m: +977 9856034616 a: Maitidevi, Kathmandu-33, Nepal
s: http://sujitbaniya.com.np e: itsursujit@gmail.com
[image: Facebook]  <https://facebook.com/itsursujit> [image: Google +]
 <https://plus.google.com/u/0/115341160046512501603> [image: LinkedIn]
 <https://www.linkedin.com/in/itsursujit> [image: Skype]
<https://htmlsig.com/skype?username=sujit.baniya2011> [image: Github]
<https://github.com/itsursujit>

**Comment by eileenmcnaughton** [comment]
did you take a look at the drupal coding standards link above? It looks like you did a good job of creating a PR - but the coding standards you are using are not the ones we follow. 

NB - here is an example of a minor comments tidy up https://github.com/civicrm/civicrm-core/compare/master...eileenmcnaughton:comments?expand=1 

We don't enforce it but according the whitespace spec there shou

**Comment by eileenmcnaughton** [comment]
NB we should probably close this PR out & you can re-open it if you want it re-reviewed? Otherwise the fact it's been refreshed tends not to show up

**Pull request closed without merging**
