### PR TITLE
--CRM-16259, added function to allocate line item proportinally

### PR DESCRIPTION
**Pull request by pradpnayak**

### CODE REVIEW

**Comment by JoeMurray** [comment]
jenkins, test this please

**Comment by davecivicrm** [comment]
Jenkins, retest this please.

**Comment by davecivicrm** [comment]
Test failure is unrelated.

**Comment by davecivicrm** [comment]
@pradpnayak Looks like merging in https://github.com/civicrm/civicrm-core/pull/7475 has caused merge conflicts for this PR. Also, still missing test for new BAO method (assignProportionalLineItems)

**Comment by pradpnayak** [comment]
@davecivicrm did some changes and added unit test

**Comment by pradpnayak** [comment]
Rebased PR and updated the unit test

**Comment by JoeMurray** [comment]
This has passed Jenkins testing. Could we get it merged before it goes stale? There is another PR ready to go in that depends on this, and a further one coming. Thanks!!

**Pull request merged**
