### PR TITLE
Support multi-select for auto-complete field

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
Support multi-select for auto-complete custom field

Before
----------------------------------------
After

After
----------------------------------------
Before

Technical Details
----------------------------------------
CiviCRM doesn't provide ability to make auto complete custom field to select multiple field through unless you specify multiple=1 in attribute either using api or updating the attribute field in civicrm_custom_field.

### CODE REVIEW

**Comment by colemanw** [comment]
First off, I think this is a good and useful feature. Thanks for working on it :+1: 

There are a few test failures to address, as well as some things to consider about the implementation:

The lack of UI makes this feature incomplete (currently the only way to make a multi-autocomplete is by altering the field programmatically). I'm not sure if this should be merged until it's added to the UI.

The implementation is reasonable, but inconsistent with other fields. To contrast:

- This implementation doesn't change the name of the field type ("Autocomplete-Select") but adds "multiple=1" to the field attributes.
- For other custom fields, the pattern is to change the field type, e.g. "Multi-Select Country" or "Multi-Select Country"

I see drawbacks to both. Adding an attribute is difficult to query (you resorted to using `stristr` in this PR which is really not ideal). But the status-quo is pretty bad too. As the code comment says:

> FIXME: Currently the only way to know if data is serialized is by looking at the html_type. It would be cleaner to decouple this.

So I think the best solution is to add a new "serialize" column to the `civicrm_custom_field` table, and get rid of those "Multi-" prefixed field types that are not real field types. I realize that's a sizeable refactoring job much larger than the original scope of this PR, but what can I say.

**Comment by pradpnayak** [comment]
Hi @colemanw 

The attribute to add through UI is implemented in https://github.com/civicrm/civicrm-core/pull/16922

**Comment by colemanw** [comment]
@pradpnayak for many years now I've been gradually improving the custom field code so that we can move away from determining serialization based on html type. I think with a few more rounds of cleanup we can actually do this the right way. Please help review/merge #16968 which will get us one step closer.

**Comment by colemanw** [comment]
@pradpnayak I think we really can do this. I'm working in a branch to add the `serialize` column and eliminate redundant field type names like "Multi-Select". But in order to get this done I really need you to test out & review #16968 and #16970 so we can get them merged.

**Comment by colemanw** [comment]
@pradpnayak I've opened a new PR for this now that the `serialize` legwork is done. See  #18449

**Pull request closed without merging**
