### PR TITLE
Campaign - Make name index unique

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Updates `Campaign.name` index to be unique and use standard naming convention.

Technical Details
----------------------------------------
Index was added by @eileenmcnaughton in 4edfa3eafe960e468cfdb9f3bf95de956ea2dc70 - I think not flagging it `unique` was an oversight as its name starts with `UI_`. Also the index had a non-standard name which is not supported by the schemaHandler so I changed it from `UI_campaign_name` to `UI_name`.

Comments
------------------
Without this piece of metadata, #25994 doesn't work quite right for campaigns.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw upgrade script?

**Comment by colemanw** [comment]
@eileenmcnaughton added. In the process I noticed that the index had a nonstandard name and in order to use the schemaHandler to add it in an upgrade script it needed to be changed to `UI_name` which I've done.

This should be good to go except it has no failsafe in the upgrade script in case any databases contain duplicate campaign names. Do you think that's a possiblity?

**Comment by colemanw** [comment]
@eileenmcnaughton ok I've added some "just in case" SQL to ensure names are unique before adding the index.

**Comment by eileenmcnaughton** [comment]
Looks like we need a bit of this sort of love https://github.com/civicrm/civicrm-core/pull/25996

**Comment by colemanw** [comment]
Yea and also there are other indexes in the same table with nonstandard names & we ought to update those too as a followup.

**Pull request merged**
