### PR TITLE
dev/core#249 Fix crash when performing export all contacts from search

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Regression since #12341, #12349, related to #12320.

Error: undefined function `getContactIds()`

To reproduce:

1. Do an empty search
1. Select all contacts
1. Choose "Export" from the task list
1. Export the default fields

Before
----------------------------------------
Crash.

After
----------------------------------------
Export works again.

### CODE REVIEW

**Comment by totten** [comment]
A fix for this should target 5.4 (RC) because the regression appears in the RC.

When testing patches here, we need to check both:

1. Export contacts (Ex: Search for "Jerome". Select all contacts. In the task-list, choose to export.)
2. Batch update (Ex: Search for "Jerome". Select all contacts. In the task-list, choose to update multiple.)

With this patch, it fixes `1` but breaks `2`. :(

**Comment by totten** [comment]
@mattwire posted a revision here along with some explanatory comments on Mattermost.

> I think part of the issue here is the introduction of the Core_Form_Task classes has required some changes to class inheritance etc. And in particular, getContactIds() is no longer part of the class being called.

This does smell like a better theory of the problem (although I still don't claim to fully understand what we're juggling around). In any event, the following use-cases  are passing `r-run` with the lastest 094208c:

* Search for "Jerome".
   * Select all. Export. ==> Observe same 3 exported 👍 
   * Select all. Update multiple. ==> Observe same 3 available for date 👍 (Also, make some changes and observe they work.)
* Search for all contacts
   * Select all. Export. => Observe all 203 exported. 👍
   * Select four arbitrary contacts. Export. => Observe all 4 exported. 👍
* Search for all contributions.
   * Select all. Export. => Observe all 93 exported. 👍 

@mattwire could you update to target 5.4?

**Comment by seamuslee001** [comment]
Given @totten's comments i have added the merge ready label, noting that the target of the PR needs to change to be 5.4, ping also @lcdservices Brian you may want to try applying this as well and testing it.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
(*CiviCRM Review Template WORD-1.1*)



* ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) Pass
* ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) Pass
* ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) Pass
* ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) Pass
* ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) Pass
* ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) Pass tested by myself and Tim and the outcome is as expected
* ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) Pass
* ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) Pass

**Pull request merged**
