### PR TITLE
Package Riverlea theme extension during CiviCRM build

### PR DESCRIPTION
**Pull request by mlutfy**
Overview
----------------------------------------

Alternate to #31324 - adds RiverLea into core packaging.

Related: https://lab.civicrm.org/extensions/riverlea/-/issues/44

Before
----------------------------------------

:building_construction: 

After
----------------------------------------

:fish: 

Comments
----------------------------------------

cc @vingle

### CODE REVIEW

**Comment by vingle** [comment]
I'm not seeing it in the Extensions listing - but I'm not seeing IATS there either? Both are in 'add new' list but probably just because they are in the extensions directory.

**Comment by mlutfy** [comment]
@vingle It's there: if you click on the "run-distmaker" details, you will see a list of tar.gz files. You can download them to inspect their contents.

Example, using the standalone tar.gz:

```
$ ls -1 civicrm-standalone/core/ext/riverlea/
CHANGELOG.md
Civi
LICENSE.txt
README.md
composer.json
core
fonts
info.xml
js
managed
riverlea.civix.php
riverlea.php
settings
streams
```

I also checked d7, backdrop, wordpress, joomla, joomla-alt. All seems OK.

**Comment by mlutfy** [comment]
weird, the failed test just seems to say:

```
umount: /home/homer: target is busy.
Build step 'Execute shell' marked build as failure
```

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by vingle** [comment]
It works!

One thing I noticed, and this isn't a fault of this PR but *another thing* is the extension invites me to update (from 1.0.10 to 1.0.11) but when it does it updates to the custom extensions folder, so gives this message:

'A copy of the extension (riverlea) is in a system folder (/Sites/localhost/civicrm-standalone/core/ext/riverlea). The system copy will be preserved, but the new copy will be used.'

So I guess this means two things:
 - good: people can update RiverLea to the latest version without waiting to upgrade Civi core.
 - not-so-good: having two divergent copies of RiverLea on a system is going to be the norm. That seems like a possible problem, unless there's a way at some point in the future to simplifying the removal of the custom copy.
 
I realise this re-opens the debate on [how best to bundle](https://lab.civicrm.org/extensions/riverlea/-/issues/44). Somehow I'd thought people would only upgrade their RiverLea outside of Civi upgrades in edge-cases to resolve specific bugs - with plenty of warning of the risks, but that 'update core extension X' prompt is pretty compelling…

**Comment by mlutfy** [comment]
> "the extension invites me to update [...] not-so-good: having two divergent copies of RiverLea on a system is going to be the norm. "

Core could avoid displaying upgrade notifications for core-shipped extensions? (I thought it was already the case, because for iATS that could cause problems too)

Maybe for some active contributors, on dev sites, people will use the main/master version. On production sites, I would not expect people to upgrade out of cycle. I mean, sure people want backports all the time, that applies to core too. That's why we have monthly releases.

Unrelated, but so I stop triggering a build: The failed test was "[E2E_CivicrmAdminUi_ManageGroupsTest.testManageGroups](https://test.civicrm.org/job/CiviCRM-Test/31377/testReport/(root)/E2E_CivicrmAdminUi_ManageGroupsTest/testManageGroups/)" which does not seem related.

**Comment by vingle** [comment]
> Core could avoid displaying upgrade notifications for core-shipped extensions? 

I'm guessing as this only relates to iATS, that gets around this by only releasing in sync with Civi release? The last release seems to be May, so it's not like RiverLea with multiple new updates a week.

I'm not sure how much work is involved in changing the upgrade notification notice? 

Referencing @ufundo's message on the topic [here](https://lab.civicrm.org/extensions/riverlea/-/issues/44#note_172697). I'm a bit torn - after the effort to get it packaged this way it seems a shame to go back to the full bundle option. That also makes my dev a bit more complex afaict. BUT multiple copies of a theme 'by accident' feels like a debugging headache when the end-users flagging bugs might not have root access to delete the duplicate.

**Comment by mlutfy** [comment]
> "after the effort to get it packaged this way it seems a shame to go back to the full bundle option"

Wouldn't full-bundle mean moving the git repo code directly in `civicrm-core`? And then you would have even less flexibility. That does not seem like a good idea in the short term.

> "it's not like RiverLea with multiple new updates a week."

If you're shipping with core, regardless where the git repo lives, you have to expect slower delivery cycles. You get wider adoption, but slower delivery. So a bug might take up to 4 weeks to be deployed, or an average of 2 weeks. It's not that bad :)

And if there is a major issue, then it might be part of a minor release (ex: 5.80.1).

So I would advise to stay the course. The problem raised is that people are encouraged to upgrade out-of-core-cycle, and we should avoid that unless they downloaded the extension somewhere else. I think we should only expect that for developers / people playing on dev sites. They can live with the duplication/confusion.

**Comment by vingle** [comment]
> The problem raised is that people are encouraged to upgrade out-of-core-cycle, and we should avoid that unless they downloaded the extension somewhere else. 

Yes. So are you suggesting I could avoid that by a) not packaging any more releases after this PR is merged (until 5.81); b) some future fix, ideally during the 5.80 RC stage, to turn off those upgrade notifications for default extensions?

FWIW - I think the path to being default in core is longer, at least for front-end – because front-end use cases are so numerous that it will only be with hundreds of instances testing I could feel confident it's ok for 1000s. But back-end feels it's had quite a good few months of tyre-kicking and has 50+ installs, so any issues are hopefully small.

**Comment by mlutfy** [comment]
Yep, I recommend (b)

**Comment by eileenmcnaughton** [comment]
I just set that test re-running but it seems like an unrelated fail & this should be merged.

Regarding the issue around 2 copies - that is not a new issue & one we have to deal with regardless of whether we add the extension to the core repo or leave it in an extension for now - the message people see *should* tell them that unless they have a clear specific reason (e.g because they are testing a beta version or have custom hacks) to override the version of the extension sitting in the core civicrm folder they should delete it

I would ALSO suggest that you start to tag your riverlea releases with the civicrm version & version compatibility with the relevant civicrm version aligning with the core version. that would mean devs / beta testers can grab a later version but for most people the relationship between the 2 will be one to one.

**Comment by vingle** [comment]
> I would ALSO suggest that you start to tag your riverlea releases with the civicrm version & version compatibility with the relevant civicrm version aligning with the core version.

Good point @eileenmcnaughton. With the tag just in the info.xml? And do you think it's ok to set two `<ver>` to indicate min and max versions? e.g.:
```
 <version>1.1.0</version>
 <compatibility>
    <ver>5.75</ver>
    <ver>5.80</ver>
  </compatibility>
  ```
As every RL release has a min compatability of 5.75. Version 1.1.0 would have a 'max' 'tested against' of 5.80, while version 1.2.0 (e.g.) might have a max of 5.81?
  
To make the link even more obvious, I had thought about changing RL's version numbering to sync with the Civi core version it goes into. ie 1.80.0, 1.81.1? But maybe a bit unconventional to jump the numbers / potentially confusing?

FWIW the goal once RL is packaged is to only do bug fixes to the packaged theme (e.g. 1.1.0, 1.1.1, 1.1.2), to avoid it diverging from what people are testing in the RC – and keep any other work (ie bigger changes / things that aren't essential / general improvements) into a separate RL branch tagged for the next release (1.2.0 etc).

**Comment by mlutfy** [comment]
Eileen was suggesting you tag the main version with the same number as core, such as:

```
<version>5.80.0</version>
```

to indicate that this is the version that ships with 5.80.0. It's just an indicator though. No need to overthink it imo. Sooner or later, the code will probably move into the `civicrm-core` git repo, and versions will be tagged automatically.

There is no concept of "max compatibility" version. You should tag it with the minimum required version. This is relevant mostly for LTS, because we don't want them to upgrade, if the newer extension version is for the latest stable.

**Comment by mlutfy** [comment]
Merging as per Eileen's MoP.

**Comment by eileenmcnaughton** [comment]
@mlutfy @vingle yes, I was suggesting that in a few months the versioning WILL be the same as the core release - so I would switch to that now / soon / when you next look at tagging a release

@vingle I would probably keep the civiversion compatibility tightly linked to the CiviCRM version on the basis that it reduces the expectation that you would be testing it against anything other than the latest version  I would suggest that there is relatively low need for people to be installing newer releases of riverlea against older releases of CiviCRM & where people to want to do that then they can own the work of checking compatibility - which is what I think the implication is when the new riverlea releases have latest civicrm compatibility

**Comment by vingle** [comment]
@eileenmcnaughton thanks. I've done this now (changed version number to 5.80.0) but it's left me with two questions:
 - when Civi 5.80.1/.2/etc comes out, should I update my info.xml to match this, even if I've not made any changes?
 - when I make changes between those .1/.2/.3 releases ([as I just did](https://lab.civicrm.org/extensions/riverlea/-/commit/742f729285bb3eb3c4854345b831cf7e4ac7369d)) should I keep the version number static and just delete and rebuild the release in gitlab (as I just did)? Or not release anything (which perhaps undermines the benefit of having a decoupled extension)? Previously I would have just tagged/released a new v1.1.next.

**Comment by eileenmcnaughton** [comment]
@vingle so if your version is 5.80.0 & civi version compat is 5.80 then I would just release 5.80.1 / 5.80.2 if & when it makes sense for Riverlea to push out an update 

When CiviCRM 5.81.0 goes out then I would say 'yeah release riverlea 5.81.0 too - but if, say, you weren't doing any active development on riverlea that month & didn't feel like it then skipping a civi-release or 2 wouldn't really matter

**Comment by vingle** [comment]
> Yep, I recommend (b)

I've opened an issue along these lines, feel free to edit/adjust: https://lab.civicrm.org/dev/core/-/issues/5593.

(NB this was made more urgent today because one of the main testers of RiverLea running on 5.80 ran into this issue of duplicate extensions after following an upgrade notice).

**Comment by eileenmcnaughton** [comment]
@vingle you have talked about 2 approaches - improving the message & just putting riverlea fully in core in 5.80 - have you landed on the former? We would basically need to not tell people about upgrades to riverlea at all I think ? (Which maybe argues for the latter)

**Comment by vingle** [comment]
@eileenmcnaughton I'd hoped for maybe 3 months of riverlea shipping as a separate packaged extension, but I hadn't anticipated the complexities this brings about - ie once I've released a newer version, users are encouraged to upgrade, and this will leave two different versions of the extension in two places in their setups.

If it's not realistic to solve that before 5.81, then yes, probably we need to go back to putting it fully in core. 

Thinking this thru:

- I think the testing of backend is pretty comprehensive, tho there are doubtless some SearchKit and FormBuilder scenarios that no-one's yet tested, plus combinations with custom extensions (your Tivy bugs, for e.g. I've seen nothing like, nor can I recreate), ntm responsiveness on all four subthemes/streams.
- I would keep use in frontend with a 'use with caution / at own risk' warning until there's much more testing. On Standalone that should be ok as there's no CMS theme to fight with, but everywhere else the risk of CMS theme specificity clashes hiding important input fields/buttons/functions is enough to make me urge big caution for existing instances.
- From my side I'll need to change the way I build and test the extension as I'll be committing to core and (at present) needing someone to merge my PRs. Which should be fine, I just need to figure that out - especially as I will probably want a testing branch that I push periodically around Civi releases, but will also need to do a quick emergency push of fixes if something has broken (e.g. RL 1.1.3/5.80.2 fixed two nasty regressions with a broken OpenStreetMap and hidden datepicker in modals).
- @ufundo [offered to try to join RiverLea's commit history into CiviCore's](https://lab.civicrm.org/extensions/riverlea/-/issues/44#note_172997) if/when it goes into core - I've no idea how tricky that is or the risk of breaking other things. But that commit history is useful to me to understand regressions.

What would be the other steps to do this? Just a new PR that reverts this PR and puts RiverLea in its entirety into `/ext/`?

**Pull request merged**
