### PR TITLE
(WIP) CRM-14382 Updates Danish States/Provinces

### PR DESCRIPTION
**Pull request by mpnordland**
In 2007 Denmark changed to having 5 regions instead of 16 counties/cites as their level one divisions. This adds the data to the template. I have not added an incremental change because Lobo's comment in the JIRA issue recommended leaving it alone for current sites. More comment is requested.

---
- [CRM-14382: Danish regions, state\/provinces under localization is outdated](https://issues.civicrm.org/jira/browse/CRM-14382)

### CODE REVIEW

**Comment by mpnordland** [comment]
Somehow my CRM-18699 fix ended up in here. That was not intentional, how should I remove it?

**Comment by colemanw** [comment]
@mpnordland that happens if you commit your changes to your master branch and then open multiple PRs from it. In this case you can rebase it out and force-push. Use the `git rebase -i HEAD~3` command.

**Comment by mpnordland** [comment]
I tried to rebase it, I think I ended up with the changes still included but the commit gone. I've never rebased before. Since I had already pushed those commits I don't think that helped. I've probably made a huge mess of it.

**Comment by eileenmcnaughton** [comment]
When you do git rebase -i you get a screen of proposed patches. You can delete a row in that screen & that patch will be dropped.

(you can also re-order patches & 'squash' them by replacing the p(ick) on the left side with s(quash). Either s or squash is accepted.

**Comment by eileenmcnaughton** [comment]
NB - I normally do 
```
git pull --rebase upstream master
```
(assuming you have called the remove 'upstream' - it might be origin)

before I do a rebase -i

and I normally do a 

```
git fetch -f upstream 
```
(or origin) 

to make sure my local remotes are up to date and then

```
git rebase -i upstream/master
````

(or origin)

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
(even though it's not rebased let's see what Jenkins says)

**Comment by JoeMurray** [comment]
@mlutfy here's an i18n / l10n issue

**Comment by JoeMurray** [comment]
Micah, as Release Manager this month, I'm trying to recruit people to help pare down the backlog of almost 100 PRs, some going back to last summer. I'm wondering if you would be able to help QA another PR if I got someone to QA this PR?

**Comment by mpnordland** [comment]
@JoeMurray I could do that, what PR should I QA?

**Comment by yashodha** [comment]
@mpnordland 
 You could QA some of the PR's are listed on here https://docs.google.com/spreadsheets/d/1fmHFOZ83ectSPCMWvXwCeJgrw4KpYi8JEV2ZDkd6XDU/edit#gid=529353056

More details at
https://github.com/civicrm/release-management

**Comment by JoeMurray** [comment]
Wonderful, thanks @mpnordland ! What about trying to QA #8476 ?

**Comment by eileenmcnaughton** [comment]
In order to remove the patches that do NOT belong in this PR you should do the following (assuming your remote for core is 'origin'

git fetch -f origin
git rebase -i origin/master

**Comment by mpnordland** [comment]
@eileenmcnaughton would the core remote mean this repo or my fork? Using these commands with my fork (origin in my clone) pushing these changes fails because the tip of my branch is behind it's remote counterpart.

**Comment by eileenmcnaughton** [comment]
OK - so for me

git remote -v shows:
upstream	https://github.com/civicrm/civicrm-core.git (fetch)
upstream	https://github.com/civicrm/civicrm-core.git (push)
eileen	git@github.com:eileenmcnaughton/civicrm-core.git (fetch)
eileen	git@github.com:eileenmcnaughton/civicrm-core.git (push)

And I would normally do

git pull --rebase upstream master 
git push -f eileen mybranch

pretty regularly just to 'keep current'

But if I want to change the commits I would do
git fetch -f upstream
(to make sure my local tracking branch is fully up-to-date. The -f makes sure the pointer is moved)
git rebase -i upstream/master

(rebase -i allows you to edit what is in it)

**Comment by yashodha** [comment]
@mpnordland any progress on this?

**Comment by mpnordland** [comment]
Unfortunately no, getting this finished is pretty low priority until I get the site launched for the client.

On July 12, 2016 7:33:18 AM EDT, Yashodha Chaku <notifications@github.com> wrote:
>@mpnordland any progress on this?
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/civicrm/civicrm-core/pull/8478#issuecomment-232016607

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by eileenmcnaughton** [comment]
I'm going to close this & let you re-open it when you are ready. The advantage of that is it saves people time checking the status  of it & when you re-open it rises up to the top of the  list rather than being hidden

**Comment by eileenmcnaughton** [comment]
NB when you re-open please set the fix version on the JIRA ticket to the next point release to get visibility

**Pull request closed without merging**
