### PR TITLE
CRM-19286 - civicrm_survey is used by CiviCampaign and should be allo…

### PR DESCRIPTION
**Pull request by jmcclelland**
…wed.

### CODE REVIEW

**Comment by yashodha** [comment]
test this please

**Comment by jmcclelland** [comment]
Hi Yashodha,

The console output of the error is:

		GitHub pull request #8961 of commit 130fdda50fd34f9f9eb5b94aba7c1a82a01b9328 automatically merged.
		[EnvInject] - Loading node environment variables.
		Building remotely on test-ubu1204-5 in workspace /home/jenkins/workspace/CiviCRM-Core-PR
		[CiviCRM-Core-PR] $ /bin/bash /tmp/hudson4096042085776421296.sh
		[[Download core-8961-6fu7h (type 'drupal-clean' in '/home/jenkins/buildkit/build/core-8961-6fu7h')]]
		[[Update caches]]
		error: Failed connect to github.com:443; Connection timed out while accessing https://github.com/civicrm/civicrm-backdrop.git/info/refs
		fatal: HTTP request failed
		Build step 'Execute shell' marked build as failure
		[CHECKSTYLE] Collecting checkstyle analysis files...
		[CHECKSTYLE] Finding all files that match the pattern checkstyle/*.xml
		[CHECKSTYLE] Computing warning deltas based on reference build #11426
		[xUnit] [INFO] - Starting to record.
		[xUnit] [INFO] - Processing JUnit
		[xUnit] [INFO] - [JUnit] - No test report file(s) were found with the pattern 'junit/*.xml' relative to '/home/jenkins/workspace/CiviCRM-Core-PR' for the testing framework 'JUnit'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'JUnit'?
		[xUnit] [ERROR] - No test reports found for the metric 'JUnit' with the resolved pattern 'junit/*.xml'. Configuration error?.
		[xUnit] [INFO] - Setting the build status to FAILURE
		[xUnit] [INFO] - Stopping recording.
		Finished: FAILURE

Do you know what that means?? Let me know if there is anything I can do to fix the commit.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@jmcclelland Heya would it be possible to add a new test into tests/phpunit/api/v3/UfJoinTest.php something like https://github.com/civicrm/civicrm-core/blob/master/tests/phpunit/api/v3/UFJoinTest.php#L128 to ensure this works in the future.

**Comment by yashodha** [comment]
@jmcclelland : There was a multilingual upgrade fix for 4.7.11, that needs to be master as well.

**Comment by jmcclelland** [comment]
@seamuslee001 thanks for the suggestions. I just added a new test - let me know how it looks (I'm inexperienced with unit tests).

@yashodha do you mean I need to rebase with master again? I just did and then did a push with -f to this branch. I hope that does the trick (otherwise let me know if I should do something else).

Thanks!
jamie

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by yashodha** [comment]
@jmcclelland : good to go. The upgrade bug has been fixed/merged and tests run green :)

**Pull request merged**
