### PR TITLE
Participants and prices.php

### PR DESCRIPTION
**Pull request by zorgalina**
Correct whitespace issues

### CODE REVIEW

**Comment by colemanw** [comment]
jenkins, add to whitelist

**Comment by colemanw** [comment]
@zorgalina hey since you're looking at these files, want to also review the patch at https://issues.civicrm.org/jira/browse/CRM-10432 to see if it's still needed?

**Comment by zorgalina** [comment]
ok I will leave a comment in the Issue - I didn't see this (dup.emails)

On Mon, Aug 3, 2015 at 6:00 PM, colemanw <notifications@github.com> wrote:

> @zorgalina <https://github.com/zorgalina> hey since you're looking at
> these files, want to also review the patch at
> https://issues.civicrm.org/jira/browse/CRM-10432 to see if it's still
> needed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6400#issuecomment-127444386>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by colemanw** [comment]
@zorgalina did you mean to close this issue and delete your branch? It hasn't been merged yet.

**Comment by zorgalina** [comment]
Well no, I didn't really - I was about to go on IRC for advice- I am
following the directions here (
http://wiki.civicrm.org/confluence/display/CRMDOC/GitHub+for+CiviCRM) and I
thought that I screwed up on creating a branch, the example seemed like an
arbitrary name for the branch (cool-footer?).
 I deleted my branch, thinking that I must have done it wrong. New to Git
branch,commit and push here. But I think at least I am right to use master
(for future release) and not a particular rev (4.6). I checked in the patch
for Event Participant Report on 4.6, it's a simple one-liner, but probably
should have used master there as well!

On Mon, Aug 3, 2015 at 6:53 PM, colemanw <notifications@github.com> wrote:

> @zorgalina <https://github.com/zorgalina> did you mean to close this
> issue and delete your branch? It hasn't been merged yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-core/pull/6400#issuecomment-127453157>
> .
>



-- 
زورگلنه ءء لسلی

**Pull request closed without merging**
