### PR TITLE
Deprecate `CRM_Contact_BAO_Relationship::del()` in favour of `deleteRecord()`

### PR DESCRIPTION
**Pull request by aydun**
Another `del()` deprecation

Move status message out of business-layer

### CODE REVIEW

**Comment by colemanw** [comment]
Thanks @aydun this looks great.
One refactoring note: since the process is to deprecate the `del()` function but not remove it, we don't want to change the signature. In the other PR I cast the output to `(bool)` since the `del()` function in that other BAO returned a bool. But this function was returning an object, so no need for the casting, you can just directly return the output of `deleteRecord` which also returns an object.

**Comment by aydun** [comment]
Thanks @colemanw - in the 3 places I found that call `CRM_Contact_BAO_Relationship::del()`, the return is ignored anyway so thought it was safe to change it.  But I'll change to be without the cast.

**Comment by aydun** [comment]
Ok - there's a lot of variability when you start to look at these things!

**Comment by colemanw** [comment]
@aydun style warnings:


Details | File | Category | Type | Severity | Age
-- | -- | -- | -- | -- | --
  | Relationship.php:630 | ArrayDeclaration | NoSpaceAfterDoubleArrow | Error | 1
Expected 1 space between double arrow and "$id"; 0 found
  | Relationship.php:630 | OperatorSpacing | NoSpaceAfter | Error | 1
Expected 1 space after "=>"; 0 found

**Pull request merged**
