### PR TITLE
 EntityRef - Search by id when an integer is entered

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
When the user types an integer into an EntityRef field, return the record with that ID first.

https://lab.civicrm.org/dev/core/-/issues/2400

### CODE REVIEW

**Comment by colemanw** [comment]
@demeritcowboy since you've already started reviewing this one, I've just pushed up a commit that should fix the "File on Case" entityRef.

**Comment by demeritcowboy** [comment]
* General standards
    * [`r-explain`] __PASS__
    * [`r-user`] __PASS__
    * [`r-doc`] __yes and no__
      * I think in lieu of docs I might update the text that appears when you click in the box - currently it says "Start typing a name or email" (or it seems to say different things for different entities and sometimes says nothing). It's just that just looking at the widget it's not obvious you can enter an id.
    * [`r-run`] __Ok__
      * There's a weird issue but ONLY for Case and I'm not going to think too much about it: If you have a form with `addEntityRef(..., ['entity' => 'Case', 'api' => ['params' => ['case_id' => [some criteria]]]])`, the id typing feature allows you to get around that restriction since it will accept case_id's outside whatever the criteria is. It's not a security problem per se, the backend lookups still check permissions it seems, just gets around what the author intended. It only applies to the case_id field, i.e. a restriction on case_type still functions as normal. The weird thing is that for other types of entities it will still ALSO use the original id restriction, or at least the ones I tested.
        * The upshot of this is that you can file activities on the same case they are already filed, which either creates duplicates or gives it a new activity id, which isn't great but is hard to say how much of a real-world problem it would be.
      * I also tested hook_alterEntityRefParams and it still seems ok.
* Developer standards
    * [`r-tech`] __PASS__
    * [`r-code`] __PASS__
    * [`r-maint`] __?__
    * [`r-test`] __PASS__

**Comment by seamuslee001** [comment]
Test fail unrelated merging on @demeritcowboy 's review

**Comment by seamuslee001** [comment]
Just noting that this caused a regression https://github.com/civicrm/civicrm-core/pull/19723 https://lab.civicrm.org/dev/core/-/issues/2434

**Comment by colemanw** [comment]
I don't think this PR was the culprit. Made a note on #19723

**Pull request merged**
