### PR TITLE
[code-quality] [jcalendar] remove jcalendar usage from participant_register_date on event search

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This removes one more place where legacy jcalendar is used.

Before
----------------------------------------
Deprecated pattern used

After
----------------------------------------
preferred pattern used

Technical Details
----------------------------------------
 There is actually still one left on the form (event date)
which I left out for now as it involves thinking about the fact event is a different entity & might warrant different representation in the arrays

Comments
----------------------------------------
@seamuslee001 @mattwire @colemanw maybe one last push will rid us of that pesky jcalendar....

### CODE REVIEW

**Comment by seamuslee001** [comment]
not having much luck with jenkins @eileenmcnaughton https://test.civicrm.org/job/CiviCRM-Core-PR/26418/checkstyleResult/new/

**Comment by eileenmcnaughton** [comment]
@seamuslee001 sigh - and I'm the one that wants to make it stricter!

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @mattwire @colemanw so I think when converting these fields there are a few gotchas ./ things to check

1) does a smart groups still work if it has been upgraded 
2) do the dates stay relative - in the brave new world the saved form values should look like

```
         [participant_register_date_relative] => this.month
                            [participant_register_date_low] => 
                            [participant_register_date_high] => 

```

But without [this hack](https://github.com/civicrm/civicrm-core/pull/14330/files#diff-e54381bfdf51e31cab376c71ca0d66ffR1557) it was saving the resolved date  - which we would expect to create issues like https://lab.civicrm.org/dev/core/issues/389

I would ideally like to get this one merged before the next rc is cut

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by mattwire** [comment]
Tested and works here

**Pull request merged**
