### PR TITLE
CRM-12132 - Allow custom TTL for forms

### PR DESCRIPTION
**Pull request by adixon**
A simple improvement to the caching strategy to prevent stale contribution form caches from lingering.

---
- [CRM-12132](https://issues.civicrm.org/jira/browse/CRM-12132)

### CODE REVIEW

**Comment by totten** [comment]
I think I'm +1 on concept.

Instead of hard-coding `20` minutes, it should at least use a constant... and perhaps a setting?

**Comment by seamuslee001** [comment]
I am also a +1 I think a setting would be nice but IMO i think that that shouldn't actually block a release.

**Comment by seamuslee001** [comment]
@adixon Alan can you do a git fetch <repo alias for core repo>/master && git rebase -i origin/master and remove the 2nd commit merging master in and then do git push <your repo alias> CRM-12132 -f

**Comment by adixon** [comment]
Okay, thanks for this - I've just rebased and fixed up the hard-coded 20 minute thing (converted to a constant and checks for a setting, even though it doesn't provide a web interface to change it - in theory a payment processor extension could modify it though).

**Comment by seamuslee001** [comment]
I think this makes sense to me @totten what do you think?

**Pull request merged**
