### PR TITLE
CRM_Utils_Check - Soften messages for read-only extensionsDir

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------
The `extensionsDir` is a configurable folder where extension source-code can be written.

The folder may be managed with a few policies:

 * Web-writable -- Allow the web-based admin to perform download/upgrade functions. (Ex: A small NGO where the web designer also installed Civi.)
 * Read-only -- Allow a sysadmin/developer to manage the folder (with CLI/API/cv/git/etc), but don't allow web-based admin to perform download/upgrade functions. (Ex: A public demo site where visitors can preview the admin functionality -- but shouldn't be able to install their favorite crypto miner.)
 * Disable -- Don't allow any extensions to be loaded through this folder.

The web-writable policy is generally the default (because it's easier to get extensions and apply security updates), but it's no panacea. This PR improves messaging when someone has a different policy.

Before
----------------------------------------

There are redundant messages ("Directory not writeable"), and they strongly push the admin toward web-writable policy.

screen shot 2018-03-28 at 3 16 38 pm

After
----------------------------------------

There is only one message ("Read-Only Extensions"). It still encourages web-writable policy, but it lowers the severity and presents it a choice ("if you want X, do Y").

screen shot 2018-03-28 at 3 35 49 pm

Comments
----------------------------------------

A few folks have raised related conversations before. Please feel free to comment or thumbs-up/down. CC @xurizaemon @bgm @agh1 @MegaphoneJon

### CODE REVIEW

**Comment by seamuslee001** [comment]
:+1:

**Comment by agh1** [comment]
I like this: having the folder read-only will stand in the way of a feature (in-app extension installs and upgrades), but that feature isn't necessary for day-to-day operations and it might be intentionally blocked.  I'm actually on the fence about whether it really should be a `notice`: a ` warning` implies something is *wrong*, while a `notice` says it's merely out of the ordinary.

**Comment by seamuslee001** [comment]
Agree with Andrew i think it should be a notice not a warning

**Comment by herbdool** [comment]
Looks like it got merged as a warning, not a notice. I would have preferred it be a notice too. 

Another reason to keep it unwritable is because we need to patch extensions and we can't fork and use our own private source if it was web-writable.

**Comment by eileenmcnaughton** [comment]
@herbdool the fix softened it to a warning - I'm happy to accept a patch that softens further if people think that makes sense - I think I do agree with that

**Pull request merged**
