### PR TITLE
Add in handling for a column entity

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
Add in handling to generate whereclause when there is an `entity` column present

ping @eileenmcnaughton @totten @monishdeb  I would appreciate your thoughts on this. I'm not sure how good this is at present.

### CODE REVIEW

**Comment by Edzelopez** [comment]
Just adding my 2 cents. I applied the PRs at #11906 and #11924 and merged this one as well. While the first two solved the problem on my multilingual setup, the third one didn't solve it for ACL enabled accounts. 

I got this error while trying to build the recipient list for a new mailing, using an ACL driven account having access to just 1 group.

Error: https://pastebin.com/aMa2KYy0
Backtrace: https://pastebin.com/5jznRDcz

**Comment by eileenmcnaughton** [comment]
@seamuslee001 seems stalled on needing a test (I would close & re-open when you have a test if it's one for the to-do list)

**Comment by seamuslee001** [comment]
@monishdeb @eileenmcnaughton just circulating back to this one, I'm not sure how to generate a unit test when no entities are built like this.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 remind me again what sort of entity this was intended to solve....

**Comment by seamuslee001** [comment]
@eileenmcnaughton this was aiming to solve the situation whereby at the moment `civicrm_mailing_group` uses `entity_id` + `entity_table` and one of those tables is `civicrm_group` which could be `civicrm_group` or `civicrm_group_en_US` and it was felt using the entity name might be easier rather than `entity_table`

**Comment by eileenmcnaughton** [comment]
@seamuslee001 ah that is wringing some bells. So, if we merge this what are the next steps? Or is this just sowing the possibility that we may solve it differently later one day (in which case we might track it through gitlab until such time rather than merge?)

I thought this extension might use that form but it seems it just misses - https://github.com/eileenmcnaughton/nz.co.fuzion.entitymessages

**Comment by seamuslee001** [comment]
Yeh all this is doing is just adding the underlying code that would generate the WHERE statement. The next steps would be 1. Create an entity column on civicrm_mailing_group 2. create upgrade step to convert entity_table data to entity and drop entity_table 3. run UI tests etc to confirm that no breakage happens. I would see the latter steps happen in separate PRs, this is just sowing it so that the where clause should be able to be generated when entity column is used

**Comment by eileenmcnaughton** [comment]
Hmm - well this PR seems largely safe but I feel nervous re-opening this can of worms when I believe we have gotten the regressions under control at the moment & it seems to potentially involve DB changes etc

**Comment by eileenmcnaughton** [comment]
@seamuslee001 - can we close this & track from gitlab. If we re-open the larger issue we can re-do it - but I feel uncomfortable still - per above

**Comment by eileenmcnaughton** [comment]
Per previous comments - closing unless we want to revisit now that there is nothing current to fix

**Pull request closed without merging**
