### PR TITLE
Hyphenate Civi-Import in the title/label

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Hyphenate Civi-Import in the name

Before
----------------------------------------
Extension label is 'CiviImport'

After
----------------------------------------
Extension label is 'Civi-Import'

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by yashodha** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by totten** [comment]
FWIW, the "-" is pretty unusual.

```
[~/bknix/build/universe] grep -r --exclude-dir=.git 'Civi[A-Z]' |wc -l
 232684

[~/bknix/build/universe] rep -r --exclude-dir=.git 'Civi-[A-Z]' |wc -l
    656

## Exclude phpdocs from contrib, where "Civi\Foo\Bar" is documented as "Civi-Foo-Bar.html"
[~/bknix/build/universe] grep -r --exclude-dir=.git 'Civi-[A-Z]' |grep -v /phpdocs|wc -l
     22
```

<details>
<summary>Full list of matches</summary>

```
docs/civicrm-dev-docs/docs/testing/phpunit.md:If you've worked with PHPUnit generally, you can build tests from first principles and incorporate CiviCRM. Although we're presenting in the context of PHPUnit and Civi extensions, the advice is more general -- it may be applied to other kinds of deliverables (such as Civi-CMS integrations and modules).
ext/org.wikimedia.rip/info.xml:  <name>Civi-RIP</name>
ext/afform/docs/roadmap.md:  which is to say that (a) it's fine for a Civi-Angular page and (b) it's lousy on a non-Angular page.
core/civicrm-core/mixin/scan-classes@1/mixin.php: * Scan for files which implement common Civi-PHP interfaces.
core/civicrm-core/ext/authx/README.md:    * __X-Header (`xheader`)__: The credential is again submitted with an HTTP header (`X-Civi-Auth:`). The header behaves the same as the common header. The
core/civicrm-core/ext/authx/tests/phpunit/Civi/Authx/AllFlowsTest.php:    $response = $http->send($request->withHeader('X-Civi-Key', CIVICRM_SITE_KEY));
core/civicrm-core/ext/authx/tests/phpunit/Civi/Authx/AllFlowsTest.php:    $response = $http->send($request->withHeader('X-Civi-Key', 'not-the-site-key'));
core/civicrm-core/ext/authx/tests/phpunit/Civi/Authx/AllFlowsTest.php:   * (2) anything/everything else (CMS/login-form/parameter/X-Civi-Auth stuff).
core/civicrm-core/ext/authx/tests/phpunit/Civi/Authx/AllFlowsTest.php:    return $request->withHeader('X-Civi-Auth', $cred);
core/civicrm-core/ext/afform/docs/roadmap.md:  which is to say that (a) it's fine for a Civi-Angular page and (b) it's lousy on a non-Angular page.
core/civicrm-core/CRM/Utils/GuzzleMiddleware.php:              $request = $request->withHeader('X-Civi-Auth', "Bearer $tok");
core/civicrm-core/CRM/Utils/REST.php:   *       Indicated by either (a) custom headers like `X-Request-With`/`X-Civi-Auth`
core/civicrm-core/CRM/Utils/REST.php:      // <xheader> Current request has valid `X-Civi-Auth:` ==> Custom header AND strong-secret param
core/civicrm-core/ang/api4Explorer/Explorer.js:              "CRM_AUTH='X-Civi-Auth: " + restCred + "'\n\n" +
core/civicrm-core/ang/api4Explorer/Explorer.js:              "  'headers' => ['X-Civi-Auth' => " + phpFormat(restCred) + "],\n" +
core/civicrm-core/ang/api4Explorer/Explorer.js:              "      " + phpFormat('X-Civi-Auth: ' + restCred) + ",\n" +
drupal-module/civicrm_entity/civicrm_entity_controller.inc:    * OK - here is where we will actually 'Do' something that is Civi-Specific
tools/civicrm-buildkit/app/config/drupal-sym2/download.sh:##    civicrm-drupal/   Concrete copy of Civi-Drupal integration
tools/civicrm-buildkit/app/config/drupal-sym2/download.sh:##           drupal/    Symlink to Civi-Drupal
tools/civicrm-buildkit/app/config/drupal-sym1/download.sh:##           drupal/    Concrete copy of Civi-Drupal integration
tools/civicrm-buildkit/bin/civi-test-run:  echo "example: Run the KarmaJS and DB-upgrade tests on D7/Civi-Master build"
```

</details>


Is the problem that (in many fonts) little-el and big-eye look the same? e.g "Civi" + "Import" looks identical to a gibberish phrase "Civil" + "mport"?

I don't suppose it would do to use a label without the "Civi" prefix? e.g. "Importer" or "Import Inspector" or "Extended Imports"?

**Comment by eileenmcnaughton** [comment]
I guess at a pinch we can use a space - although a hyphen does seem like the sort of thing you should be able to use in a label

**Comment by totten** [comment]
> I guess at a pinch we can use a space

Slick 😺

**Comment by eileenmcnaughton** [comment]
OK - it passes with a space

**Comment by colemanw** [comment]
@eileenmcnaughton I'm coming into this fresh and not sure if this is merge-ready or not. The discussion seems to have settled on a space, but the patch uses a hyphen.
Personally I'd favor a name that doesn't start with Civi at all, but I won't stall this process based on my opinion.

**Comment by eileenmcnaughton** [comment]
@colemanw that's odd - cos the only reason to switch to a space was it failing unit tests - which seem to pass now - I'm gonna give them another kick

test this please

**Comment by eileenmcnaughton** [comment]
@colemanw it passed again - I'm pretty sure there was no good reason not to use a hyphen - just a test fail - I'll change the pr title back

**Pull request merged**
