### PR TITLE
dev/core#289 - Fix links on case dashboard

### PR DESCRIPTION
**Pull request by colemanw**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 

@colemanw why / when did this regress? Do you know

**Comment by colemanw** [comment]
I'm not sure. Here's what I do know:

- That code was last updated 6 months ago by Monish.
- It contains a small typo (`caseid` instead of `caseId`, which is what the class `CRM_Case_Page_CaseDetails` is looking for)
- When I'm logged in as an admin, it works despite the typo
- When I'm logged in as a normal user, it does not work

Digging in a little deeper, when I debug the variable retrieval as an admin, it is still unable to get the value from the url due to the typo but `CRM_Utils_Request::retrieve` nevertheless works, because it is able to retrieve it from storage in the form object. I think this is because the url does not contain `&reset=1`.

So really, this bug just needs fixing and has gone unnoticed for a while due to caching.

**Comment by seamuslee001** [comment]
@colemanw @eileenmcnaughton i tested this on a 5.4 instance and it didn't seem to fix it

**Comment by eileenmcnaughton** [comment]
:-(

**Comment by colemanw** [comment]
@seamuslee001 I actually couldn't reproduce any issues with changing an activity status. This PR is to fix the fact that the activity list won't load at all in some cases.

**Comment by seamuslee001** [comment]
@colemanw i still get the error when i click the pencil icon on the case dashboard as highlighted in this image. I think its because the key is being passed is `type` when the activity form i think is expected atype
edit case error

**Comment by seamuslee001** [comment]
but also just thinking it through myself why is that pencil there anyway

**Comment by colemanw** [comment]
Ok thanks @seamuslee001 that helped me track down the bug.
Again that code hasn't been updated in 6 months so it really doesn't look like a recent regression. It's been broken for a while.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @colemanw this is against master which is fine given it's not a recent regression - if we get it merged today it will hit 5.5 rather than 5.6

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by mattwire** [comment]
test this please

**Comment by jmcheung** [comment]
I've tested the Case.php file and it appears to fix our site!!

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by eileenmcnaughton** [comment]
fail is unrelated

**Pull request merged**
