### PR TITLE
CRM-19715 (IIDA-96), Removed Close Accounting Period Activity Type

### PR DESCRIPTION
**Pull request by pradpnayak**
----------------------------------------
* CRM-19715: Remove Close Accounting Period code
  https://issues.civicrm.org/jira/browse/CRM-19715

### CODE REVIEW

**Comment by pradpnayak** [comment]
Close Accounting Period activity type was implemented for Close Accounting Period functionality which is now moved into an extension. This PR includes removal of Close Accounting Period Activity type and its related activities.

**Comment by eileenmcnaughton** [comment]
@JoeMurray @pradpnayak are you confident that all activities of the Close Accounting Period type should be removed from the Db. The safe option would seem to be to only remove them if none exist.

Note the test failure does relate - just need to tweak the activity_type_id on the example file to reflect the change

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by monishdeb** [comment]
I have tested the patch on my local against multilingual 4.7.18 upgrade and it worked. 

However. the test failure is related to hard-coded activity_type_id value at this line https://github.com/civicrm/civicrm-core/blob/master/api/v3/examples/Activity/Create.php#L11. The failure will occur in this particular unit-test when a activity type got deleted from install/upgrade. Desired changes will be https://gist.github.com/monishdeb/89b8f7f4ae67d99b67d2d939dca0a997

**Comment by eileenmcnaughton** [comment]
wip label based on test fail & unresolved question about activity types

**Comment by JoeMurray** [comment]
Monish, could you respond to comment on your gist?

**Comment by JoeMurray** [comment]
@pradpnayak In response to @eileenmcnaughton question: let's delete the activity type only if there are no activities of that type, and leave them otherwise.

**Comment by pradpnayak** [comment]
@JoeMurray  @monishdeb i have created separate PR for api test fix at https://github.com/civicrm/civicrm-core/pull/10077

**Comment by pradpnayak** [comment]
@eileenmcnaughton @monishdeb @JoeMurray  I have updated the PR with suggested changes to sql i.e to delete activity type if activity is not present.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
This looks good now - the activity type will only be deleted if there are no activities of the type

**Comment by eileenmcnaughton** [comment]
@pradpnayak I have not updated JIRA - unsure if this completes the ticket or there are more

**Comment by pradpnayak** [comment]
@eileenmcnaughton  there is one more PR for this issue https://github.com/civicrm/civicrm-core/pull/9974

**Pull request merged**
