### PR TITLE
dev/core#3218: format value by locale before export

### PR DESCRIPTION
**Pull request by pminf**
Fix for issue [3218: CSV exports does not respect localization configuration](https://lab.civicrm.org/dev/core/-/issues/3218). Formats date, datetime, and money field mysql values for csv export and its preview.

### CODE REVIEW

**Comment by colemanw** [comment]
@civicrm-builder add to whitelist

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by mlutfy** [comment]
@pminf I suspect that the use of the `match` operator is causing tests to fail. The operator is new to PHP 8.0, but we still support PHP 7.3 (it will be dropped in December, but PHP 7.4 will be there for a while).

**Comment by emembeka** [comment]
As a total civi newbie, and collegue of @pminf I implemented a version that is not using the match operator. in #30544 
I don't know why a new pull request was created, as I committed to pminf's branch, sorry for that.

**Comment by colemanw** [comment]
Ok closing in favor of https://github.com/civicrm/civicrm-core/pull/30544

**Pull request closed without merging**
