### PR TITLE
SearchKit - Support download formats xlsx, ods, pdf

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds support for additional file formats from the SearchKit "Download Spreadsheet" action.

Screenshot from 2021-09-02 14-39-16

Before
----------------------------------------
Can download spreadsheet as .csv format only.

After
----------------------------------------
Additional formats supported

Technical Details
----------------------------------------
Requires the PhpSpreadsheet package which comes with a bunch of composer dependencies.

### CODE REVIEW

**Comment by colemanw** [comment]
@seamuslee001 I noticed that PhpSpreadsheet adds a dependency on HtmlPurifier, which is already in our Packages directory. Perhaps we could switch to using it from Composer?

**Comment by demeritcowboy** [comment]
jenkins retest this please (CRM_Utils_TokenConsistencyTest.testCaseTokenConsistency)

**Comment by demeritcowboy** [comment]
I notice date fields are exported to excel as text not dates. How important that is maybe depends why you're exporting it and who the recipient is, and whether your OS has the same date format as civi is displaying (which may then interpret it wrong when you open it).

The pdf table has 0 cell padding, but that's maybe getting into a bigger question about formatting the pdf in general, so just a comment.

**Comment by colemanw** [comment]
Agreed. Dates, numbers, and currencies all need formatters applied to the spreadsheet table cell. Before I get to that though I just want to get a "Concept approved" from @eileenmcnaughton or @seamuslee001 or @mlutfy that it's ok to bring the `PhpSpreadsheet` package into core.

**Comment by eileenmcnaughton** [comment]
It seems consistent with other package choices to me - I'm +1

**Comment by seamuslee001** [comment]
I think its ok but we just need to make sure we do some solid testing with d7 sites that have the html purifier module set up

**Comment by seamuslee001** [comment]
Just noting that the reason for concern here isn't the PhpSpreadsheet package its self but the fact it drags in the htmlpurifier package as well and there has been poor experiences with bringing this into composer before see https://chat.civicrm.org/civicrm/pl/jyxh8963j7ne9khhpuczunh9ha conversation in Prod mtce on this

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
(rebuilding the test site to see how pdfs play with the bootstrapping)

**Comment by colemanw** [comment]
@seamuslee001 can you take a look at this PR for moving HTMLPurifier: https://github.com/civicrm/civicrm-core/pull/21432

**Comment by seamuslee001** [comment]
@colemanw can you rebase this pr now that we have the htmlpurifier issue merged

**Comment by eileenmcnaughton** [comment]
@colemanw these do download but I did observe some things....

Search is at http://core-21351-12lhk.test-1.civicrm.org:8001/civicrm/admin/search#/edit/1

1) I was under the impression the advantage of these other formats over 'just a csv' was that they would carry through formatting so I thought (incorrectly) the css would come through
image

2) in the pdf variant the alignment is a bit hard going
image

3) I had thought the links might come through - but they didn't
image

4) my downloads (all formats) were sorted by contact id ascending even though that was not what was on the screen

My sense is that you would prefer this was merged & those issues (to the extent they are issues) could be dealt with in follow ups once your more challenging change is made and I'm OK with that

**Pull request merged**
