### PR TITLE
CRM-21721, fixed notice error for Division by zero

### PR DESCRIPTION
**Pull request by pradpnayak**
----------------------------------------
* CRM-21721: Notice : Division by zero
  https://issues.civicrm.org/jira/browse/CRM-21721

### CODE REVIEW

**Comment by mattwire** [comment]
Hey @pradpnayak this looks like a duplicate of https://github.com/civicrm/civicrm-core/pull/11292

**Comment by pradpnayak** [comment]
Ohhh.. I will close this against #11292

**Comment by pradpnayak** [comment]
@mattwire reopening this as per our discussion on #11292

**Comment by eileenmcnaughton** [comment]
While I have a strong preference for unit tests on ALL changes that touch contributions I think I could let this slip through due to the triviality & the fact it's a non-core fix (interacts with a hook). This makes sense to me & from the discussion I feel it has been agreed - @mattwire  if you confirm I will merge this.

Ok course - I really would prefer a unit test if either of you feel Ok to do one...

**Comment by mattwire** [comment]
Ok I added a unit test in #11623

**Comment by mattwire** [comment]
@eileenmcnaughton Confirm this is good to merge, and unit test should then pass in #11623

**Comment by eileenmcnaughton** [comment]
Thanks @mattwire - merging based on your review & this being an agreed code change based on you both having worked on the bug

**Pull request merged**
