### PR TITLE
dev/core#2717  - further cleanup

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
@kcristiano this takes https://github.com/civicrm/civicrm-core/pull/20935 & rips out more code that I hope isn't needed but perhaps you can figure out how to reach it (or how to no longer reach it)

Before
----------------------------------------
batch code is crazy

After
----------------------------------------
still crazy, minor improvement

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
ah well this test fails says this code is hit via the tests - I'm  just not 100% sure if it can be retrieved from the UI

**Comment by kcristiano** [comment]
Initial `r-run` has the same issues as https://github.com/civicrm/civicrm-core/pull/20935

let me know if you prefer me to dig further into this PR or continue on #20935

**Comment by eileenmcnaughton** [comment]
@kcristiano I've updated this to include https://github.com/civicrm/civicrm-core/pull/21152 -which fixes the end_date issue so you can test all together if you prefer.

#21152 updates only new memberships 
- #20935 updates only renewals.
This includes both & takes the renewals side a bit further & has a moderate to high likelihood of going too far - but when we clarify that I can capture in a test & fix

**Comment by kcristiano** [comment]
Staring `r-run`  I'll do Multiple situations

First Run:

- First run for renewals
- Select contacts with expired memberships
- set all fields including expiry dates
- Submit

Expect current memberships and expiry dates as submitted

Actual Resulst:

Cirrent memebrships and expiry dates as submitted

**Comment by kcristiano** [comment]
First Run:

- First run for New members
 - Select contacts with No prior memberships
 - Set all fields including expiry dates
 - Submit

Expect current memberships and expiry dates as submitted

Actual Result:

Cirrent memebrships and expiry dates as submitted

**Comment by kcristiano** [comment]
Third Run:

- Mix of New and renew
-   Select 2 contacts with No prior memberships, 2 with lapsed memberships
- Set all fields including expiry dates
- Submit

Expect current memberships and expiry dates as submitted

Actual Result:

Current memberships and expiry dates as submitted

@eileenmcnaughton I think you prefer this PR over #20935   It looks better on initial runs, but has failing tests.  

Let me know if you want me to dig into this one and confirm that the removed code is no longer an issue.

**Comment by eileenmcnaughton** [comment]
@kcristiano yeah - let's just cut straight to this one - it cleans up the most & the failing test may just be an invalid use case. The hardest part is the rigourous r-run testing you are doing.  This gets us to
1) renew path in the code
2) non renew uses order api

It doesn't yet tackle 'renew path uses order api' - which is the final chunk we would hope to do.

**Comment by eileenmcnaughton** [comment]
@kcristiano So I dug into the failing test - it is linked with https://issues.civicrm.org/jira/browse/CRM-18000 and it seems to be as described there ie 

It starts with an EXPIRED membership  and the option 'renew' is deliberately selected on the form - it expects a new expiry this year. The issue was coming from the commit ['rip out the bit I really hope isn't needed'](https://github.com/civicrm/civicrm-core/pull/21126/commits/0bf20da39deb52f1917d061d0f8d93af1f7be1c8)
so I removed that commit. That suggests a bigger chunk of work to deal with that situation but, for now we should have something mergeable 

```
      $membershipParams = [
        'membership_type_id' => $this->_membershipTypeID2,
        'contact_id' => $contactID,
        'start_date' => '01/01/2015',
        'join_date' => '01/01/2010',
        'end_date' => '12/31/2015',
      ];
```

**Comment by kcristiano** [comment]
@eileenmcnaughton 

I do see the failing tests, but `r-run` has been good.   Based on your comment should we merge and then fix the test?   

Please let me know if I need to dig further into this, but I think it would be good if we can get it in the next RC

**Pull request merged**
