### PR TITLE
CRM-20527: batch data entry does not retain currency

### PR DESCRIPTION
**Pull request by monishdeb**
* [CRM-20527: batch data entry does not retain currency](https://issues.civicrm.org/jira/browse/CRM-20527)

### CODE REVIEW

**Comment by lcdservices** [comment]
tested and confirmed it's working correctly for batch data entry

**Comment by pradpnayak** [comment]
QA'd
Currency field is set to last selected value rather default value set in system.

**Comment by monishdeb** [comment]
@eileenmcnaughton can you merge it?

**Comment by eileenmcnaughton** [comment]
Yep - thanks @monishdeb @pradpnayak @lcdservices

**Pull request merged**
