### PR TITLE
Package Riverlea theme extension during CiviCRM build

### PR DESCRIPTION
**Pull request by vingle**
Overview
----------------------------------------
Following [discussion](https://chat.civicrm.org/civicrm/pl/i5hz77r5ab8cxjobzyzz9wcsfw) this packages the most recent release of the RiverLea theme framework extension (https://lab.civicrm.org/extensions/riverlea) during the CiviCRM build process.

Before
----------------------------------------
RiverLea isn't packaged, so needs to be installed manually.

After
----------------------------------------
It is. Anyone can enable RiverLea to try one of its four subthemes/'streams'.

Technical Details
----------------------------------------
RiverLea is a large extension. To better understand it, a good starting point is to look at the GitLab readme, changelog, issues, & PR history.

Comments
----------------------------------------
I am kind of guessing this is the right way to add this, but cannot test.

### CODE REVIEW

**Comment by ufundo** [comment]
Hmmm, now we've got a more different error... so I guess that's progress...

I'm gonna try the job again cause maybe it's extension directory timeout.

**Comment by vingle** [comment]
> maybe it's extension directory timeout.

um, riverlea isn't in the extension directory tho… I guess naîvely I thought it might pick it up from lab.civicrm.org/extensions

**Comment by vingle** [comment]
Test this please.

(Have added to the extensions directory).

**Comment by vingle** [comment]
Test this please

**Comment by vingle** [comment]
@ufundo run-distmaker is failing

**Comment by ufundo** [comment]
Looks like the fail was downloading iatspayments info from the extension feed.

 The url in the logs seems valid and works for me, if slowly - so my guess is its just a network timeout issue during the job. I've hit retry and crossed my fingers

**Comment by vingle** [comment]
Seems to pass…

test this please

**Comment by vingle** [comment]
It's not there… It is now on the AddNew screen - but I think that's just via the updated extdir listing.

**Comment by mlutfy** [comment]
This will require a rebase if/when #31325 is merged, because some files are being renamed.

> "It's not there… It is now on the AddNew screen - but I think that's just via the updated extdir listing."

Is that from running distmaker? Because I think a demo site will use a zip file that was already generated (and apply patches on top of it, when testing a PR). So the only way to test is by running distmaker.

**Comment by vingle** [comment]
Thanks @mlutfy - is running distmaker different to asking - test this please?

Have taken it out of WIP, tho still not 100% sure if it works.

**Comment by mlutfy** [comment]
oh, I forgot that the `run-distmaker` label, so it runs, but I don't think it is what is generating the demo site.

I'll run it again, because the fail seems unrelated:

```
In Process.php line 16:
                                                                           
  Process failed:                                                          
  [[ COMMAND: git am --ignore-whitespace ]]                                
  [[ CWD: /home/homer/buildkit/build/build-0/src ]]                        
  [[ EXIT CODE: 128 ]]                                                     
  [[ STDOUT ]]                                                             
  Applying: Package Riverlea theme extension during CiviCRM build          
  Applying: Fix issue #5550                                                
  Patch failed at 0002 Fix issue #5550                                     
  When you have resolved this problem, run "git am --continue".            
  If you prefer to skip this patch, run "git am --skip" instead.           
  To restore the original branch and stop patching, run "git am --abort".  
                                                                           
  [[ STDERR ]]                                                             
  error: patch failed: css/civicrm.css:3341                                
  error: css/civicrm.css: patch does not apply                             
  hint: Use 'git am --show-current-patch=diff' to see the failed patch 
```

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by mlutfy** [comment]
I yolo-merged #31325  which required a rebase, so I created an alternative PR #31389 for this.

The main issues were: 1) a commit relating to the CSS fix on checkboxes from another PR, 2) the PR was using your master branch as the source branch, which can be a bit messy if a PR isn't merged. You might need to reset your git repo (or at least revert the master branch) now that they have both diverged.

**Pull request closed without merging**
