### PR TITLE
CRM-21008 - Checkbox to explicitely change the employer when doing a shared address

### PR DESCRIPTION
**Pull request by samuelsov**
Overview
----------------------------------------
Following the work done https://github.com/civicrm/civicrm-core/pull/12574, adding a checkbox on shared addresses so that people can explicitly update the employer instead of assuming it's what the user wants.

Before
----------------------------------------
When doing a shared address on a individual with an organization address, CiviCRM always update the relationships to disable any current employee/employer relationship and set the shared address organization as the only current relationship.

After
----------------------------------------
When the checkbox is checked, it does exactly the same as before but if not checked, it won't mess with the current relationships.

Creating a new shared address:
crm-21008 - 28-08-2018 11-15

Updating with or without checking the box:
crm-21008 - 28-08-2018 11-06

Not an organization, no checkbox available:
crm-21008 - 28-08-2018 11-16

Comments
----------------------------------------
The API has not be updated yet but the default behavior is to not create the relationship if the parameter is not set. I like the explicit behavior better but we might want to discuss this for backward compatibility.

---

 * [CRM-21008: "Use another contact's address" creates duplicate relationships](https://issues.civicrm.org/jira/browse/CRM-21008)

### CODE REVIEW

**Comment by mlutfy** [comment]
Odd.. from Jenkins: "GitHub pull request #12739 of commit 95d04120f97c7b7a278a193bb451789ed344c710, has merge conflicts."

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by samuelsov** [comment]
Hmm, seems to be a problem with the rebase i've done. I will probably restart from scratch and do a new PR.

**Comment by colemanw** [comment]
Good idea. Thanks for your work on this @samuelsov

**Pull request closed without merging**
