### PR TITLE
Adds an accessible accordion, applies to news-feed dashlet

### PR DESCRIPTION
**Pull request by vingle**
Overview
----------------------------------------
[None](https://lab.civicrm.org/dev/core/-/issues/3294) of CiviCRM's [8 accordion patterns](https://lab.civicrm.org/dev/user-interface/-/issues/60) are accessible / keyboard controllable. This PR adds support for a 9th method, using native HTML's `<details><summary>` [element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) then applies this onto the newsfeed on the home dashlet. 

Before
----------------------------------------
Accordions are not keyboard/etc accessible.

image

After
----------------------------------------
They are. 

image

Technical Details
----------------------------------------
To make this work, the JS and the expand/collapse icon CSS is adjusted so it doesn't target `<details>`. 
This PR includes a small style fix - JQueery UI tries to make accordions use font Verdana, which isn't used by Civi's Grenwich theme. This PR stops this, so the accordion should match the font of the parent theme by default.

Comments
----------------------------------------
Because `<details>` brings its own expand/collapse triangle icon, any theme that uses custom collapse/expand icons will have two sets of icons. This can be adjusted by changing `.crm-container .crm-accordion-header:before,` to `.crm-container div.crm-accordion-header:before`, as seen in the civicrm.css change.

### CODE REVIEW

**Comment by mlutfy** [comment]
@vingle Is the new accordion documented in the theme-test extension?

**Comment by vingle** [comment]
> @vingle Is the new accordion documented in the theme-test extension?

Kinda… Accordion 11 in the latest Themetest is a `<detaill><summary>`  'prototype' but the css was a little different - have [just updated it](https://lab.civicrm.org/extensions/themetest/-/commit/36d7cdf04d675fbfbd63f1d11738b35a048f8440).

image

**Comment by vingle** [comment]
@mlutfy Will update avatar

image

**Comment by colemanw** [comment]
Tested this on the demo site & it works perfectly. Thanks @vingle

**Comment by vingle** [comment]
76! And that only addresses the `.crm-accordion-wrapper` accordions - there's also `.crm-collapsible` and `.af-collapsible` accordions..

**Pull request merged**
