### PR TITLE
dev/core#3514 Define hook to alter data once it has been mapped but before work is done on it.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
dev/core#3514 Define hook to alter data once it has been mapped but before work is done on it.

Before
----------------------------------------

After
----------------------------------------
Hook parameters look like

image

Technical Details
----------------------------------------
- validation is done on the results of `getMappedRow` - so this is a chance to alter before vaildation fails
- I kinda want to get the custom fields switched to api v4 style before putting this in...
- the existing `import` hook is pretty flawed - it doesn't get called at a sensible point in the code
- one of my concerns is to only pass out data that has become pretty fixed - hence wanting to switch to apiv4
- this is currently only on contribution as it doesnt' share the parent function & I want to go through entity-by-entity carefully for fixed-ness
- 

Comments
----------------------------------------

### CODE REVIEW

**Comment by mattwire** [comment]
@eileenmcnaughton Agree on switching to API4 for custom fields - so what's the plan with that? :-)

**Comment by eileenmcnaughton** [comment]
@mattwire sadly the plan is that I have to do the work - but did you just volunteer to review the patch :-)

It's basically an upgrade script plus a couple of tweaks in the code

**Comment by eileenmcnaughton** [comment]
@mattwire I put up a PR to do the conversion - https://github.com/civicrm/civicrm-core/pull/25886 - but it is failed at the moment cos of what I think is an apiv4 bug.

**Comment by colemanw** [comment]
Makes sense and test cover is good

**Pull request merged**
