### PR TITLE
dev/core#470: Current employer disapears when disabling expired relationships

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Steps to replicate:

1. Create a current relationship (set empty end-date) on individual A as  organization A and mark as current employer
2. Create a past relationship on individual A as  organization B without marking as current employer
3. Run Disable expired relationships cron job

Before
----------------------------------------
Result: Clear the employer field of Contact A

After
----------------------------------------
Result: Does not clear the employer field of Contact A

Technical Details
----------------------------------------
This PR replaces #13334 which  is stalled & stale

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit can you review this too?

**Comment by jitendrapurohit** [comment]
I was able to replicate this and confirm that the current employer field works as expected.

**Review by jitendrapurohit — APPROVED** [review]

**Comment by seamuslee001** [comment]
Merging as per @jitendrapurohit's review

**Comment by francescbassas** [comment]
Please note that steps to replicate here are subtly different from those described on https://lab.civicrm.org/dev/core/issues/470.

1. Create a current relationship on **individual A** as employee of **organization B** and mark as current employer
2. Create a past relationship on **individual A** as employee of **organization B** without marking as current employer

https://lab.civicrm.org/dev/core/issues/470 it is not yet fixed.

**Pull request merged**
