### PR TITLE
allow distinction to be made whether relationships are shown for user…

### PR DESCRIPTION
**Pull request by yashodha**
… dashboard or relationship tab for hook usage

Overview
----------------------------------------
allow distinction to be made whether relationships are shown for user dashboard or relationship tab for hook usage

Comments
----------------------------------------
We could also add another parameter in the hook to indicate context but that would involve making changes to a commonly used hook signature.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire  I'm pretty sure this is the hook you wanted & I thought it was a bad idea because we'd be stuck with the horrible function forever if we added a hook - anyway now you own it - over to you to review this

**Comment by yashodha** [comment]
@mattwire this is related to changes in https://github.com/civicrm/civicrm-core/pull/14184

**Comment by mattwire** [comment]
@yashodha Can you add a code comment that explains why we are doing this (per explanation on the PR). Also can you add a PR to extend the documentation here: https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_searchColumns/

Can you explain why you want to do this? As you can't differentiate the column headers are you wanting to display different information on the rows depending on which context is displaying?

**Comment by jaapjansma** [comment]
Betty and I are reviewing PR's and we came across this one.

At December 4th, @mattwire requested to add documentation, @yashodha, were you able to do so and could you link the changes in this PR? If not are you still going to do this? As we do think the documentation is required.

**Comment by jaapjansma** [comment]
Betty and I are reviewing PR's and we came across this one. @mattwire has asked some good questions and no answers has been given since then so we will close this PR as we don't see that this PR gets any follow up.

**Pull request closed without merging**
