### PR TITLE
dev/core#442 Fix Style issues on word replacements, credit card expir…

### PR DESCRIPTION
**Pull request by seamuslee001**
…y date section, dedupe execptions and tags and groups section

Overview
----------------------------------------
_This makes the following changes, 

* switches the fields to be text not text area on word replacements
* switches the class from crm-form-date to crm-form-select for the Credit Card Date fields
* Fixes a missing line break error in the Tags and Groups Form on edit contacts
* Adds in crm-form-text class to the Dedupe Exceptions input fields

Before
----------------------------------------
Strange styling

After
----------------------------------------
Better styling

ping @AkA84 @MikeyMJCO @colemanw

### CODE REVIEW

**Comment by AkA84** [comment]
hey @seamuslee001 thanks a lot for this! Is the end result the same as the "after" screenshots on https://lab.civicrm.org/dev/core/issues/442?

**Comment by seamuslee001** [comment]
They should be but if you could confirm that would be great

**Comment by AkA84** [comment]
@seamuslee001 checked and all looks good, thanks!

**Comment by seamuslee001** [comment]
@colemanw @eileenmcnaughton do the changes here look sensible to you?

**Comment by mattwire** [comment]
@seamuslee001 I've tested all these and they are all sensible/"correct".  Ok to merge @eileenmcnaughton

**Pull request merged**
