### PR TITLE
dev/core#1602 Fix join date filtering in search builder by standardis…

### PR DESCRIPTION
**Pull request by seamuslee001**
…ing date field handling in Membership Query BAO

Overview
----------------------------------------
This is my alternate to #16573 and aims to do more of a standardised fix without generating deprecated notices

Before
----------------------------------------
Join date field wouldn't filter correctly within Search builder

After
----------------------------------------
Correct filter is applied when searching via Search builder using the Join date field

ping @eileenmcnaughton @lcdservices

### CODE REVIEW

**Comment by lcdservices** [comment]
@seamuslee001 I ran through a test and this is working as expected.

**Comment by eileenmcnaughton** [comment]
good to merge on test pass then

**Comment by eileenmcnaughton** [comment]
@seamuslee001 do you want to put up a 5.22 pr now - still trying to attract @totten's attention to a drop but this can go in I think

**Comment by seamuslee001** [comment]
test fail unrelated

**Pull request merged**
