### PR TITLE
CRM-19064 Added an API for Personal Campaign Page

### PR DESCRIPTION
**Pull request by digitlimit**
This API exposes CiviCRM Personal Campaign Page (PCP).

---
- [CRM-19064: API for personal campaign page](https://issues.civicrm.org/jira/browse/CRM-19064)

### CODE REVIEW

**Comment by totten** [comment]
jenkins, ok to test

**Comment by digitlimit** [comment]
@totten is there any issue with this PR, been update 5 days since checks commenced. 
Why is it taking so long?

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by mlutfy** [comment]
@digitlimit Thanks for sending a patch! Do you have a JIRA issue for this pull-request? (c.f. https://wiki.civicrm.org/confluence/display/CRMDOC/Contributing+to+CiviCRM+using+GitHub step 8 : create a JIRA issue on https://issues.civicrm.org).

Also I was wondering why you used "p_c_p" in the function name, instead of "pcp"?

Does the API call need documentation/tests?

**Comment by digitlimit** [comment]
@mlutfy thanks for your response.



I have created an issue here:
https://issues.civicrm.org/jira/browse/CRM-18195

**Comment by eileenmcnaughton** [comment]
ok to test

**Comment by eileenmcnaughton** [comment]
Oddly enough AllCoreTables handles IM OK - but not PCP - I wonder why

**Comment by digitlimit** [comment]
@eileenmcnaughton Please can you explain what you mean here?

> Oddly enough AllCoreTables handles IM OK - but not PCP - I wonder why

**Comment by eileenmcnaughton** [comment]
I mean that the IM class suffers from the same oddness as PCP - ie. it's all caps rather than camel case - so I thought that whatever meant the im api isn't oddly named would work for pcp too.... 

Unless people have only actually tested 'Im' not 'IM' in their api calls.

**Comment by PalanteJon** [comment]
@eileenmcnaughton The IM (and ACL) APIs have a special exception in api/v3/util.php.  I wrote this PCP API a while ago, but I also hacked util.php to keep the name consistent: http://civicrm.stackexchange.com/questions/3030/incoporating-pcps-in-wordpress/3037#3037

**Comment by monishdeb** [comment]
Jenkin, test this please

**Comment by monishdeb** [comment]
Please fix the style error as per https://test.civicrm.org/job/CiviCRM-Core-PR/8497/checkstyleResult/new/

**Comment by colemanw** [comment]
jenkins, retest this please

**Comment by colemanw** [comment]
jenkins, retest this please

**Comment by colemanw** [comment]
jenkins, retest this please

**Comment by colemanw** [comment]
jenkins, retest this please

**Comment by colemanw** [comment]
jenkins, retest this please

**Comment by colemanw** [comment]
The current round of test failures look legit - syntax conformance tests are falling over on the Pcp entity.

**Comment by digitlimit** [comment]
@colemanw  please where can view the syntax errors so I can correct them

**Comment by colemanw** [comment]
These are not syntax errors they are test failures. Click the "details" link below (next to "Merged build finished") to see them.

**Comment by PalanteJon** [comment]
OK, I've reviewed the code.
PCP entity is unique in that:
* Its name isn't in camelcase - only one of three entities (ACL, IM, PCP) to not be.
* Of those entities, PCP is the only one whose id is defined in the XML scheme with a uniqueName of pcp_id.

This causes _civicrm_api_get_entity_name_from_camel in api/api.php to return the incorrect name.

There's a precedent for writing an exception into that function (for entities with "U_F" in their name) so I wrote one here.  This gets us from 10 tests failing to 1.  I'll submit an update when I've got that test passing.

**Comment by digitlimit** [comment]
@PalanteJon I would like to work on this with you.

**Comment by PalanteJon** [comment]
@digitlimit Great!

I've reverted your reversion - "p_c_p" as the entity name will only make the testing suite angrier :smile:

When I ran some of the tests manually through the API Explorer (e.g. making a "Get" request with no parameters) I could reload the page and get one or both of these errors:

> Notice: Undefined index: p_c_p_id in civicrm_api3_generic_getfields() (line 111 of /home/jon/local/civicrm-buildkit/build/bmaster/modules/civicrm/api/v3/Generic.php).
> Notice: Undefined index: p_c_p_id in _civicrm_api3_build_fields_array() (line 962 of /home/jon/local/civicrm-buildkit/build/bmaster/modules/civicrm/api/v3/utils.php).

Note that this was AFTER I reverted the field name.

To fix that, I also added this code (below):

```php
diff --git a/api/api.php b/api/api.php
index e20c451..a7aafad 100644
--- a/api/api.php
+++ b/api/api.php
@@ -180,6 +180,11 @@ function _civicrm_api_get_entity_name_from_camel($entity) {
   if (!$entity || $entity === strtolower($entity)) {
     return $entity;
   }
+  // Handle PCP as a special case:
+  // https://github.com/civicrm/civicrm-core/pull/7878#issuecomment-219061074
+  else if ($entity == 'PCP') {
+    return 'pcp';
+  }
   else {
     $entity = ltrim(strtolower(str_replace('U_F',
           'uf',
```

Now we're down to one error:
> 1) api_v3_SyntaxConformanceTest::testCreateSingleValueAlter with data set #50 ('Pcp')
api result array comparison failed checking if status_id was correctly updated

Do you have civicrm-buildkit installed?  If so, you can run the unit tests on your own.  This will let you know if a change you made fixed itself.

Meanwhile, I opened up the file at <civicrmroot>/tests/phpunit/api/v3/SyntaxConformanceTest.php and looked at the test.  It's a long test!  If you want to debug and see what's going on, this page will help: https://wiki.civicrm.org/confluence/display/CRMDOC/Testing

**Comment by JoeMurray** [comment]
Heh Frank, as Release Manager this month, I'm trying to recruit people to help pare down the backlog of almost 100 PRs, some going back to last summer. I'm wondering if you would be able to help QA another PR if I got someone to QA this PR?

**Comment by digitlimit** [comment]
Yes I do love to, dough I have been so much occupied lately due to office pressure but I am sure I can squeeze out some time.

**Comment by JoeMurray** [comment]
@darrick would you be interested in reviewing this PR, as it combines your API and contribute interests?

**Comment by JoeMurray** [comment]
@digitlimit we need a JIRA issue that explains the intent of this PR - could you make one? Thanks, Joe

**Comment by PalanteJon** [comment]
@joemurray @darrick I've got this PR in my queue, actually.  Sorry if
the Google docs don't reflect that!  Also, this is more-or-less assigned
to https://issues.civicrm.org/jira/browse/CRM-18191.

**Comment by JoeMurray** [comment]
Thanks, @PalanteJon - I've updated the Google Release doc with Issue # and assigned to you.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
Check the PR I just added (#8697) - that resolves your blocker issue. (NB if someone can QA that PR then it can be merged in advance of this one being completed)

**Comment by mickadoo** [comment]
I'd like to have an API for Personal Campaign Pages and am willing to help getting this merged. I tried checking why the build failed on Jenkins but the link is broken? 

Regarding the required changes - I saw [this answer](http://civicrm.stackexchange.com/a/3037) on stackexchange and it works for me when I tested it.

**Comment by PalanteJon** [comment]
Jenkins re test this please

**Comment by PalanteJon** [comment]
@mickadoo Unfortunately that post was by me.  It "works for me" too - but it definitely fails on some tests it shouldn't.  The good news is that we're past the point outlined by that answer.

**Comment by eileenmcnaughton** [comment]
I think it passes if you merge first the patch in #8697)

**Comment by litespeedmarc** [comment]
jenkins, retest this please

**Comment by seamuslee001** [comment]
@litespeedmarc @colemanw there has already been a PR that has accomplished this https://github.com/civicrm/civicrm-core/pull/9049

**Comment by litespeedmarc** [comment]
This is great then.  I've went ahead & closed the JIRA.  Can anyone close the PR?

**Comment by monishdeb** [comment]
Closed in favor of #9049

**Pull request closed without merging**
