### PR TITLE
CRM-15629 Fix for IPN issue on 4.6 branch.  Call wp-load via  CRM_Utils_...

### PR DESCRIPTION
**Pull request by kcristiano**
...System::loadBootStrap()  Original PR https://github.com/civicrm/civicrm-core/pull/5749

---
- CRM-15629: Paypal IPN not working on Wordpress the first time
  https://issues.civicrm.org/jira/browse/CRM-15629

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Looks like jenkins is not liking your 'else' formatting. ie. it wants
}
else {

}

rather than } else {

**Comment by kcristiano** [comment]
Thanks @eileenmcnaughton  I just updated for the formatting

**Comment by kurund** [comment]
@kcristiano looks like commit has gone stale, can you please rebase or submit new PR

**Comment by kcristiano** [comment]
@kurund I can do that.   When is 4.6.3 releasing, I want to try and get this in that release.

**Comment by kurund** [comment]
@kcristiano looks like you have fake merge commit. I will cherry-pick your changes and test and let you know,

**Comment by kcristiano** [comment]
@totten  I read your comments again on https://github.com/civicrm/civicrm-core/pull/5749.   Understand the need to define in /settings

This PR #5751 is against 4.6 and the matching PR in civicrm-wordpress is #75 https://github.com/civicrm/civicrm-wordpress/pull/75

@kurund I'd appreciate any help you can give to get this in 4.6 before the next build.  If you wnat me to delete and start over I can do that.

**Comment by kurund** [comment]
jenkins, retest this please

**Comment by kurund** [comment]
closing this in favor of https://github.com/civicrm/civicrm-core/pull/5833

**Pull request closed without merging**
