### PR TITLE
CRM-19453

### PR DESCRIPTION
**Pull request by spalmstr**
This is another attempt at a PR of the same code.  It was easier to recreate the branch than attempt to do another push to it as that push failed.  I hope at last the PR will succeed.

---

 * [CRM-19453: System-\>Directories fails to display under Joomla](https://issues.civicrm.org/jira/browse/CRM-19453)

### CODE REVIEW

**Comment by spalmstr** [comment]
Success at last?

**Review by seamuslee001 — APPROVED** [review]
As per previous PR tested the changes on Linux and i think its fine @spalmstr I assume you have tested this on a windows install and works?

**Comment by spalmstr** [comment]
Wonderful!

**Comment by eileenmcnaughton** [comment]
Yes, success at last!

**Pull request merged**
