### PR TITLE
CRM-19788 Add in pre and post hooks to recurring contributions

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @eileenmcnaughton

---

 * [CRM-19788: Add in Pre and Post contribution hooks to recurring contribution create](https://issues.civicrm.org/jira/browse/CRM-19788)

### CODE REVIEW

**Comment by jackrabbithanna** [comment]
@seamuslee001 I think this is a good candidate to get merged for October, I don't see any harm in have more hook calls... I will merge it in at the appropriate time unless you can think of a reason not to.

**Comment by jackrabbithanna** [comment]
Jenkins test this please

**Comment by seamuslee001** [comment]
Nope no reason not to @jackrabbithanna

**Comment by eileenmcnaughton** [comment]
Note this is not applicable to 4.7 as we don't bypass normal functions in 4.7 anymore so hooks are called

**Comment by jackrabbithanna** [comment]
Merging #9561

**Comment by jake-mw** [comment]
@jackrabbithanna @seamuslee001 @eileenmcnaughton This change has caused a regression on sites that are running recurring transactions through iATS (and likely will create problems for others including Paypal IPN) if they have Hook::pre implementations for contributions.

The pattern for calling Hook::pre elsewhere in core is to pass $params as an associative array of details for the object about to be changed. This code in BaseIPN::completeTransaction is passing an Object instead.

As a result we're seeing "PHP Fatal error:  Cannot use object of type CRM_Contribute_BAO_Contribution as array" from hook implementations that worked fine prior to this change, and that are properly written for handling other contrib create/edit paths through core.

**Comment by davejenx** [comment]
@jake-mw I agree and I think this PR isn't specific to recurring contributions. I came across this while porting a customised site from 4.6.30 to 4.6.33 . I had customised BaseIPN.php to call the pre hook around line 700 in a similar way to this patch, but converting the contribution to an array before passing to the hook as the $params parameter. (Didn't submit to core due to the preceding comments "@todo this section should call the api  in order to have hooks called").
The call to the post hook is I think correct in passing as an object, as this forms the $objectRef parameter to the post hook.
@seamuslee001

**Comment by jake-mw** [comment]
@davejenx Agreed, post is correct as object, but pre should be an array for consistency with the rest of core.

**Comment by jackrabbithanna** [comment]
I'm going make another PR and reverse this PR unless somebody issues a PR fixing this before the next release window...if you do, please post on here.

**Comment by jackrabbithanna** [comment]
Created https://github.com/civicrm/civicrm-core/pull/11327 which will undo this PR

**Pull request merged**
