### PR TITLE
dev/core#1873 Fix issue causing some urls to fail on safari because of trailing "/"

### PR DESCRIPTION
**Pull request by seamuslee001**
…ra trailing /

Overview
----------------------------------------
This fixes an issue with safari where by an extra trailing / was causing an unknown path error https://civicrm.stackexchange.com/questions/2581/unknown-path-error-when-trying-to-access-new-mailing-with-version-4-6-2/16180

Before
----------------------------------------
Some urls fail on safari

After
----------------------------------------
Urls work on safari

ping @totten @demeritcowboy @monishdeb

### CODE REVIEW

**Comment by seamuslee001** [comment]
jenkins re test this please

**Comment by seamuslee001** [comment]
ping @totten

**Comment by totten** [comment]
I tried on Safari 12.1.2... and the existing code/redirect worked fine without a patch...

At a glance, neither the explanation nor the StackExchange thread gave me a clear understanding of this issue. e.g. The thread has conflicting reports about causes and resolutions - and no decisive explanation. However, trying to synthesize the comments, here's a theory: the problem arises from combining two things:

1. __(Server) Path Normalization__: Ordinarily, as a web user, I expect that `http://example.org/foo` and `http://example.org/foo/` give the same content. However, as a site owner, you may not *like* having multiple URLs for the same thing (maybe it confounds your logging/analytics, or maybe to allow very path-relative hyperlinks, or for SEO reasons... etc). To ensure consistency, some deployments have a policy to *proactively normalize* paths (i.e. pick one URL as canonical and redirect any aliases).

    The normalization policy could go either way on aesthetic grounds ("we want trailing slashes"; "we don't want trailing slashes"; "it depends on the specific page!"). The policy could be a general rule (pattern/regex-based) or specific (whitelists). One could implement the policy with different techniques (Drupal module, WP plugin, nginx config, apache `.htaccess`, a reverse-proxy, ad nauseum).

    But the net-effect is that path-normalization works by issuing an extra HTTP redirect, creating an additional step in a chain of redirects.

    Under vanilla conditions (no path-normalizer), these CiviMail requests are just:

    * (A1) Request `http://my_domain.com/civicrm/mailing/send?reset=1`. Per Civi controller logic, this responds with `Location: http://my_domain.com/civicrm/a/#/mailing/new`
    * (A2) Request `http://my_domain.com/civicrm/a/#/mailing/new` - this serves the actual page/content/HTML/JS

    But if you have path-normalizer, then there's an intermediate redirect:

    * (B1) Request: `http://my_domain.com/civicrm/mailing/send?reset=1` - per Civi controller logic, this responds with `Location: http://my_domain.com/civicrm/a/#/mailing/new`
    * (B2) Request: `http://my_domain.com/civicrm/a/#/mailing/new` - the path-normalizer wants to remove the trailing slash, so it responds with `Location: http://my_domain.com/civicrm/a`
    * (B3, disputed) Request: `http://my_domain.com/civicrm/a` or `http://my_domain.com/civicrm/a/#/mailing/new`

2. __(Client) Safari's Multi-Step Redirect Handling__: For A1=>A2, the browsers (Chrome/Firefox/Safari) agree that A2 should use the fragment that was explicitly given in the `Location:` header (ie `#/mailing/new`). The problem arises when there are multiple redirects.

    RFC 7231 section [7.1.2](https://tools.ietf.org/html/rfc7231#section-7.1.2) says, "If the Location value... does not have a fragment component, a user agent MUST process the redirection as if the [Location] value inherits the fragment..." My testing (Chrome 83/Firefox 75/Safari 12) shows that B3 always inherits from *somewhere*, but the browsers disagree on where to inherit from. In Chrome+Firefox, B3 inherits the fragment from B2. In Safari, B3 inherits from B1 (which, in our case, happens to have a blank `#fragment`). 

With this theory, I can reproduce: eg [hack-in some superfluous redirects](https://gist.github.com/totten/39fc91eb972e49d46152625c18aaed28) (like a path-normalizer). Then open `civicrm/mailing/send?reset=1` in Safari 12... and we have a failure.

----

With the approach in this patch, two concerns come to mind:

1. The convention of `civicrm/a/#/foo` is not something we made up -- it comes from the AngularJS docs/tutorials that existed when that was written. In a quick sniff test on my local, `civicrm/a#/foo` does seem to work - and (as far as I can think) it ought to work as long as all hyperlinks are consistently generated through the proper APIs. OTOH, I feel like there may been some bug years ago when some code had used `civicrm/a#/foo`, but I don't remember that clearly. I'm not sure if the `civicrm/a/#/foo` was advised on aesthetic grounds or functional grounds.
2. Path-normalization is ultimately an arbitrary, superficial preference, and this approach seems to endorse the idea that all Civi paths should be normalized to omit the trailing `/`. But (in the big picture/broader world), if you deploy on a random set of hosts/environments, the preferences are just as likely to go the other way. In which case... the patch shifts the bug from one population (*systems which normalize without `/`*) to a different population (*systems which normalize with `/`*). OTOH, maybe Civi's install-base is not "random"; maybe anti-slash policy is the only policy actually used. (Or maybe pro-slash is used, but those users don't have a reason to complain.)

Given the ambiguity, my gut says it's safest to give a diagnostic -- e.g. as part of `CRM_Utils_Check_*`, it could send an HTTP request for `civicrm/a/` and see if it gets back a redirect. If that happens, show a warning that this deployment has a path-normalization rule that will break in Safari.

It's worth considering that (when handling a web-system that uses `#fragments`), the browsers only agree on what to do if you limit request-handling to a maximum of 1 redirect. Multiple redirects are not portable. That's a very annoying realization. Long-term, it basically means either (a) we regulate to keep the overall system within budget ("maximum 1 redirect"), or (b) we get out of the `#fragment` business, or (c) Apple fixes Safari.

This patch is basically a regulation saying, "Civi will align-with/bless the policy of normalizing web URLs to omit the trailing slash". That's not crazy - it's close to the status quo. It might work. It's hard to validate formally, but... it might work...

**Comment by seamuslee001** [comment]
@totten I know that I believe @monishdeb had run into issues with these URLs maybe something has happened in more recent Safari versions?

**Comment by eileenmcnaughton** [comment]
I'm going to close this as I think it's very unclear based on the analysis that it is safe to merge / the right approach. Let's pick it up in gitlab if it's still an issue

**Pull request closed without merging**
