### PR TITLE
CRM-18713 - SMS

### PR DESCRIPTION
**Pull request by jmcclelland**
- [CRM-18713: SMS activity requires mobile phone to be set as primary](https://issues.civicrm.org/jira/browse/CRM-18713)

### CODE REVIEW

**Comment by JoeMurray** [comment]
Jamie, as Release Manager this month, I'm trying to recruit people to help pare down the backlog of almost 100 PRs, some going back to last summer. I'm wondering if you would be able to help QA another PR if I got someone to QA this PR?

**Comment by PalanteJon** [comment]
@JoeMurray Since I know it's a matter of time before you post one of these messages on one of my PRs - you can put me down for this one.  I've been working on SMS recently.

**Comment by jmcclelland** [comment]
Sure Joe - you can assign me a ticket to QA

**Comment by JoeMurray** [comment]
Thanks, @PalanteJon - I put you down for another before noticing your message here (again).

**Comment by PalanteJon** [comment]
I know that most QA conversations are happening on Github, but since
there was already a significant conversation on Jira, I updated it there.

**Comment by davejenx** [comment]
Hi @jmcclelland ! At the Edale sprint, trying to review/close some PRs. Reading the conversation at CRM-18713, has this PR been superseded by later ones: 8626 (merged) & 8628 (open)? If so, can this one be closed?

**Comment by jmcclelland** [comment]
Yes #8626 supercedes this pull request. It would be nice to get #8628 merged, but that is a more significant change.

**Pull request closed without merging**
