### PR TITLE
[NFC] CRM-21739 Test improvements for mailing getRecipients

### PR DESCRIPTION
**Pull request by JKingsnorth**
Add test for getRecipients method to ensure that mailing groups included/excluded from email mailings are included in the recipient list for a mailing.

 * [CRM-21739: Create unit test for getRecipients](https://issues.civicrm.org/jira/browse/CRM-21739)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins Re test this please

**Comment by eileenmcnaughton** [comment]
@JKingsnorth it's passing is it still wip?

**Comment by JKingsnorth** [comment]
Yes indeed, I have a whole suite of additional tests to add.

**Comment by JKingsnorth** [comment]
@eileenmcnaughton @seamuslee001 @monishdeb I've done all I can on tests for this for now. Better than nothing I hope! This should help prevent future regressions in the functionality to include/exclude mailing groups in email mailings.

There are still some significant gaps in the tests, but this is a starting point at least.

Tests are passing locally, so if someone could review the test logic then it would be great to get this merged.

**Comment by monishdeb** [comment]
Great work @JKingsnorth :) Will test and merge this PR shortly 👍

**Comment by monishdeb** [comment]
Reviewed the code and it covers the scenario well. Also the test build passes now, hence merging.

**Pull request merged**
