### PR TITLE
CRM-20644: Column names on Advanced search results displayed on contacts are out of order

### PR DESCRIPTION
**Pull request by devarun**
The ordering of the column headers should be done in the Selector class it self, it will avoid any disarrangement  of headers with the final row data.

---

 * [CRM-20644: Column names on Advanced search results displayed on contacts are out of order.](https://issues.civicrm.org/jira/browse/CRM-20644)

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins ok to test

**Comment by seamuslee001** [comment]
Jenkins, ok to test

**Review by jitendrapurohit — APPROVED** [review]
I see this was added in https://github.com/civicrm/civicrm-core/pull/10334 as a minor fix. @monishdeb Any objection on this line being removed? From my testing I found it to be fixing the issue mentioned on the ticket CRM-20644.

**Comment by monishdeb** [comment]
Yes this will impact 'Find Contribution' result list and extension (via ```searchColumn``` hook), where column header ordering is done using ```weight```. See the original PR https://github.com/civicrm/civicrm-core/pull/10295/files#diff-84f0f2b3474502a214c56aa1c62db5a0R609 where ```weight``` is used as a index in ```$_columnHeaders``` and using ksort aligns the position of headers on basis of this index.

Since it's affecting 'Advance Search' now, we need to reorder the position of column headers from backend where headers are initialised (as done in ```CRM_Contribute_Selector_Search:: getColumnHeaders(..)```). If we remove the ksort then there would be no significance of using weight for column headers.

**Comment by jitendrapurohit** [comment]
@monishdeb @devarun Okay, looks like keys are not always `weight` as per the header array returned in AdvancedSearch.

    $reorderedHeaders

    Array
    (
     [contact_type] => Array
       (
            [desc] => Contact Type
        )

    [sort_name] => Array
        (
            [name] => Name
            [sort] => sort_name
            [direction] => 1
        )
    .
    .
    .

worth adding a condition to ksort only if we have integer keys ?

**Comment by totten** [comment]
jenkins, ok to test

**Comment by totten** [comment]
@monishdeb @jitendrapurohit @devarun - with whatever fix you sort out, it's probably a good idea to target a fix at `4.7.21-rc`.

**Comment by devarun** [comment]
@jitendrapurohit @monishdeb 

The last commit will address both kind of keys, keeping the headers having `weight` before the headers having no `weight` set and will allow usage of `string` keys.

Please test.

**Comment by KarinG** [comment]
Confirming this fixes the Search -> Find Contacts -> Search  - results listings - the headers are no longer mangled; Find Contributions -> Search - results listings - also look good.

**Comment by jitendrapurohit** [comment]
@devarun can you please create a PR against 4.7.21-rc as mentioned by totten in his comment ?

**Comment by eileenmcnaughton** [comment]
closing per comments on #10556

**Pull request closed without merging**
