### PR TITLE
CRM-16368 refactor of backoffice membership form 

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
The is a rebase of work by @lolas-freeform with some updates to make the tests pass

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Added another commit to set shared variables in preProcess function as some breakage had occurred in the refactoring.

**Comment by eileenmcnaughton** [comment]
NB I tested that the participant add to event still works. Really need to separate that form from the task inheritance to clean up the code. Realistically as long as a list of ids is passed from the task not much else is required from that. Tasks need a bit of love really

**Comment by kurund** [comment]
jenkins, test this please

**Comment by eileenmcnaughton** [comment]
test failure is unrelated

**Pull request merged**
