### PR TITLE
CRM-19738 Allow a custom check to determine the validity of a wizard step in Angular.

### PR DESCRIPTION
**Pull request by saurabhbatra96**
* [CRM-19738: Allow a custom check to determine the validity of a wizard step in Angular.](https://issues.civicrm.org/jira/browse/CRM-19738)

### CODE REVIEW

**Comment by saurabhbatra96** [comment]
@totten could you have a look please. Also, how can I pass the value of a variable into this custom directive?
Example:

**HTML**
```
<div crm-ui-wizard-step crm-ui-wizard-step-valid="dsFormValid" crm-title="ts('Upload Data')" ng-form="dsForm">
```

**JS**
```
$scope.dsFormValid = "false";
```
Just passes the string "dsFormValid" to the directive instead of the value of the variable.

**Comment by totten** [comment]
Seamus just pinged me about this one. @saurabhbatra96 ,  kudos on writing a patch which is straight-forward to read.

This might be an interesting alternative to consider from `ang/crmMailing/EditMailingCtrl/wizard.html`:

```html
<div crm-ui-wizard-step crm-title="ts('Content')" ng-form="contentForm">
  ...
        <div crm-ui-accordion="{title: ts('HTML'), help: hs('html')}">
          <div crm-mailing-body-html crm-mailing="mailing"></div>
        </div>
        <div crm-ui-accordion="{title: ts('Plain Text'), collapsed: !mailing.body_text, help: hs('text')}">
          <div crm-mailing-body-text crm-mailing="mailing"></div>
        </div>
        <span ng-model="placeholder" crm-ui-validate="mailing.body_html || mailing.body_text"></span>
  ...
</div>
```

The user isn't allowed to proceed past this wizard-step unless they provide some kind of email (`crm-ui-validate="mailing.body_html || mailing.body_text"`).

Considerations:
 * Both `crm-ui-validate` and `crm-ui-wizard-step-valid` allow you define special/multi-variable validations.
 * `crm-ui-validate` is more general -- it works with any form (not just `crm-ui-wizard`).
 * Angular's form system allows you to have forms and subforms (and subsubforms, etal). Validation issues in the subform are expected to bubble up to the parent form. That's useful if you want building-blocks that can be reused/rearranged, and it even works when there's a bit of indirection. (Ex: `crm-mailing-block-summary` is a building-block. A validation error inside it will bubble up to whatever form includes it, whether that's a wizard or the main form or something else). `crm-ui-validate` participates in this bubbling, but (if I read correctly) `crm-ui-wizard-step-valid` would not.
 * Theoretically, there might be some edge-case where you want to control a wizard's validation *without* any bubbling effects. But I can't imagine a realistic scenario. 
 * We probably need more docs/links/discussions about the `crm-ui-*` library.

In practical terms, I'd be -1 on `crm-ui-wizard-step-valid` unless there's some scenario that cannot be handled by `crm-ui-validate`.

**Comment by eileenmcnaughton** [comment]
@totten I'm concerned that @saurabhbatra96 might not be Civi focussed much at the moment. I suggest that if we can't progress, or get a strong indication of intent to follow u this in the next week we close the issue & track through JIRA (with a link to the PR )

**Comment by saurabhbatra96** [comment]
@totten I cannot remember in minute detail as to why this PR was necessary, but I was aware of `crm-ui-validate` when I wrote this.

I believe the use case was to check whether an action (button press/file upload complete, something of this sort) had been completed or not. The action triggered by the event automatically set the `step-valid` boolean variable to true or false.

However, in hindsight, I kind of knew that this PR was more of a hot-fix rather than a proposed new feature, my aim being to trigger this discussion regarding the limitations of `crm-ui-validate` for my use-case.

PS: Hi @eileenmcnaughton , long time no see! :-)

**Comment by saurabhbatra96** [comment]
Related issue: https://github.com/saurabhbatra96/com.saurabhbatra96.civiimport/issues/5

**Comment by eileenmcnaughton** [comment]
Hey @saurabhbatra96 - hope all is well with you! 

I'm guessing you are not going to pick this up again anytime soon? If not I'll close & we can track through JIRA.

**Comment by saurabhbatra96** [comment]
@eileenmcnaughton That sounds good!

**Pull request closed without merging**
