### PR TITLE
CRM-20439: Rename card_type to card_type_id of civicrm_financial_trxn table (IIDA-126)

### PR DESCRIPTION
**Pull request by monishdeb**
* [CRM-20439: Rename card_type to card_type_id of civicrm_financial_trxn table \(IIDA-126\)](https://issues.civicrm.org/jira/browse/CRM-20439)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I'm happy to go for a quick merge on this on the basis the field is still very new & being actively worked on & will continue to be tested over the rc period

**Comment by pradpnayak** [comment]
@monishdeb  I think you have missed updating some places in CRM/Contribute/BAO/Contribution.php and/or CRM/Core/BAO/FinancialTrxn.php 
eg https://github.com/civicrm/civicrm-core/blob/master/CRM/Contribute/BAO/Contribution.php#L4092
https://github.com/civicrm/civicrm-core/blob/master/CRM/Contribute/BAO/Contribution.php#L4092

And also in unit test

**Comment by seamuslee001** [comment]
Do we need to alter any values in the db before changing the field type?

**Comment by monishdeb** [comment]
Thanks @pradpnayak for pointing those test failures. Made those changes, have a look

@seamuslee001 we are already storing the integer value of credit card type, it's just the column name is misnomer here.

**Comment by seamuslee001** [comment]
ok cool just thought ask the question

**Pull request merged**
