### PR TITLE
CRM-21256 Improve performance of payment processor load

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Improve performance of "Submit Credit Card Contribution" page load.

Comments
----------------------------------------
Proposed replacement for #11060

---

 * [CRM-21256: Payment processor contribution page performance improvement](https://issues.civicrm.org/jira/browse/CRM-21256)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire ...

**Comment by eileenmcnaughton** [comment]
@seamuslee001 -per brief discussion - here is the comment docblock

```
  /**
   * Is there a processor on this site with the specified capability.
   *
   * The capabilities are defined on CRM_Core_Payment and can be extended by
   * processors.
   *
   * examples are
   *  - supportsBackOffice
   *  - supportsLiveMode
   *  - supportsFutureRecurDate
   *  - supportsCancelRecurring
   *  - supportsRecurContributionsForPledges
   *
   * They are passed as array('BackOffice');
```

But the issue is that many pages check for 'are there live processors' more than once so the goal here is to add caching once the question is answered

**Comment by eileenmcnaughton** [comment]
lol - that's for the enthusiastic review.. I guess

**Comment by seamuslee001** [comment]
:-)

**Comment by seamuslee001** [comment]
I am happy with the code and and think it won't do any harm and will hopefully improve performance

**Comment by eileenmcnaughton** [comment]
much more enthused - I'm going to merge it off that since I think the test coverage is solid on this

**Pull request merged**
