### PR TITLE
[NFC] code cleanup: split out 2 functions that are mostly unrelated.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Code cleanup only

Before
----------------------------------------
One function does 2 very different things depending on one parameter

After
----------------------------------------
Function is split into 2

Technical Details
----------------------------------------
The handling of line items & financial items has been munged together in a way that gains little, adds confusion,
and blocks the financial items portion from being re-usable.

This is a code cleanup preparatory to the actual changes in pr #10962

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@monishdeb another nfc subset of #10962

**Comment by seamuslee001** [comment]
@eileenmcnaughton you have 2 style issues https://test.civicrm.org/job/CiviCRM-Core-PR/18057/checkstyleResult/new/

**Comment by eileenmcnaughton** [comment]
thanks @seamuslee001 -hopefully fixed now

**Comment by eileenmcnaughton** [comment]
Note if anyone wants to review this I think the easiest steps are actually to redo the refactor & see if you get the same results. Basically I copied the function & renamed it & then changed the second place to call the second function. Once you start pulling out parameters that are no longer required it kinda falls into place

**Comment by eileenmcnaughton** [comment]
little green tick

**Comment by mlutfy** [comment]
Merging based on code review. I see that there are a few unit tests calling `changeFeeSelections`, so hopefully that would catch the supported use-cases.

**Pull request merged**
