### PR TITLE
CRM-21577 add links to be able to add payments from the contribution …

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
…block

Overview
----------------------------------------
Adds links to the payment block allowing a payment to be made (if applicable). This opens the option for us to use the block in more places where we have many to one payments & adds some convenience for users

Before
----------------------------------------
No links
screenshot 2017-12-19 14 39 15

After
----------------------------------------
screenshot 2017-12-19 14 40 04

Technical Details
----------------------------------------
This is a spin off from #10776 just adding the links.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@monish can you review this - we can consider #10776  after.

**Comment by monishdeb** [comment]
As we are already providing those two payment (action) links against a contribution, I don't feel that there is need to show them again below its payment. Also this could be otherwise implemented via  extension using ```crmRegion = payment-info-block``` . So in my opinion I don't think it should be core change ? Or am I missing something here in terms of usability ?

**Comment by eileenmcnaughton** [comment]
@monishdeb once we have those links in the payment block we can put it on the contribution form / membership form etc in place of the one-2-one fields. 

i think it's a mild advantage in usablility (since in the cases I looked at the links were not easily available) but in terms of being able to address the problems with us misprocessing payments due to the forms showing it as a one to one rather than a many to one it's an important piece.

**Comment by monishdeb** [comment]
Oh ok, I agree. So I did a thorough testing on my local and its all working fine. This is a sub-PR which  pulls most of the code from #10776 (which I already tested earlier) except the changes made for backoffice contribution. 

Merging now :)

**Pull request merged**
