### PR TITLE
[Test framework] - Combine triplicate createCase functions

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
These are just copies of the same function.

There's one that uses a specific date so that tests can compare the results to a date, but otherwise they are copy/paste.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Comment by colemanw** [comment]
Wow. 3 of them!

**Comment by demeritcowboy** [comment]
Yep, and just ignore the git blame on them.

**Comment by colemanw** [comment]
Haha, well at least you get credit for cleaning them up.

**Pull request merged**
