### PR TITLE
SearchKit - Add links to admin table and refresh after popups

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds quick-action links to the admin results table.

Screenshot from 2021-09-01 15-42-22

Technical Details
--------------
Adds optional outline button styles which look better IMO.
Also fixes a bug where editing or deleting a contact in a popup wasn't refreshing the search results.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Well it works - it opens the viiew option in a new tab but the others in a pop-up - which is a bit odd.

I'm just trying to get my head around this as a change of UI - ie because it was previously something you could add at the level of 'search display' but this is when creating a search display - I guess it is useful for ad-hoc searching & checking on stuff. But then I find myself wondering - why the crud links, why not all the links that would be available on an individual record (e.g 'send receipt')

**Comment by colemanw** [comment]
> why not all the links that would be available on an individual record (e.g 'send receipt')

These are the ones currently in the metadata so were easiest to add, but I agree it would be great to add more in the future.

**Comment by eileenmcnaughton** [comment]
@colemanw ok - that's weird then - I thought we were already picking up the metadata that caused those actions I mentioned to be available in legacy search results for a contribution search? Why is 'view' not in a popup.

I'm coming round to adding these in here - although I think it will add even more pressure on our permissions model - ie the more we make this useful as an ad hoc searching mechanism the more our permissions to access this screen might be too tight.

**Comment by eileenmcnaughton** [comment]
@colemanw check `CRM_Contribute_Task::tasks()` - there are some declared as 'single mode' in there - do think those should be in the schema directly?

```
 self::PDF_RECEIPT => [
          'title' => ts('Receipts - print or email'),
          'class' => 'CRM_Contribute_Form_Task_PDF',
          'result' => FALSE,
          'title_single_mode' => ts('Send Receipt'),
          'name' => ts('Send Receipt'),
          'url' => 'civicrm/contribute/task?reset=1&task=receipt',
          'key' => 'receipt',
          'icon' => 'fa-envelope-o',
          'filters' => ['contribution_status_id' => [CRM_Core_PseudoConstant::getKey('CRM_Contribute_BAO_Contribution', 'contribution_status_id', 'Completed')]],
          'is_single_mode' => TRUE,
        ],
```

**Comment by colemanw** [comment]
I have an idea about how to get those into searchKit and I don't think it will be necessary to add them to the schema. Happy to pursue that in a follow-up PR.

**Comment by eileenmcnaughton** [comment]
OK - I'm satisfied this is mergeable then

**Pull request merged**
