### PR TITLE
add d8 to candidtate - this might not be final plan, but gets setup.s…

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
…h to 'chug along'

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@torrance I added the drupal 8 template to this - BUT from what I can tell all changes to Utils_System_Drupal8 are already merged

**Comment by eileenmcnaughton** [comment]
@torrance I feel pretty comfortable about the safety of the install patch - but, from what I can tell these are the only parts of the patch that are not already applied - I see no other changes when I apply 
https://raw.githubusercontent.com/eileenmcnaughton/civicrm-drupal/8.x-master/civicrm.patch

**Comment by eileenmcnaughton** [comment]
@totten Any concerns on this - the change in install seems pretty safe to me. TBH it could possibly go in 4.6 since all Torrance's testing has been against that - but can look at that later

**Comment by colemanw** [comment]
It's annoying that we have 'drupal6' 'drupal' and 'drupal8' as 3 different CMSs. There must be a saner way to manage CMS version dependencies. Esp if we ever needed to (god forbid) support multiple versions of WP or J!

**Comment by eileenmcnaughton** [comment]
I'm in 2 minds. Afterall the differences for d8 are quite big so an argument to think of it as a different cms can be made

**Pull request merged**
