### PR TITLE
(dev/core#1304) Queue - Add high-level tracking table

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

Consider a typical use-case per https://docs.civicrm.org/dev/en/latest/framework/queues/

```php
/*Step 1*/ 
$queue = CRM_Queue_Service::singleton()->create([
  'type'  => 'Sql',
  'name'  => 'my-own-queue',
  'reset' => FALSE,
]);
/*Step 2*/
$task = $queue->createItem(new CRM_Queue_Task(
  ['CRM_Demoqueue_Page_DemoQueue', 'doMyWork'], // callback
  ['whatever', ['contact_id' => 123]], // arguments
  "Task $i" // title
));
```

It is intuitive that step 2 creates a SQL record for the queue item (`INSERT INTO civicrm_queue_item` with `queue_name=>my-own-queue`). What may be less intuitive is that `my-own-queue` does not exist anywhere else -- there is no parent. There is no way to get a list of `queue_name`s (unless the queue, at the very moment of querying, happens to have live data init).

This PR allows registering the parent record `my-own-queue`. It contributes towards https://lab.civicrm.org/dev/core/-/issues/1304. 

~~Depends: #22343~~ (Merged)

Before
----------------------------------------

* SQL-backed queues are created implicitly - by inserting items in `civicrm_queue_item`
* Non-SQL queues are not visible/discoverable

After
----------------------------------------
    
* One *may* register and discover queues via `civicrm_queue`. This registration can work with any type of queue (eg `Sql`, `SqlParallel`, or some future/non-SQL type).

Technical Details
----------------------------------------

Why? For dev/core#1304, we aim to provide a standard/generic/automatic runner for use with new background tasks. This system needs a way to distinguish between:

* (a) existing queues/tasks that run in the current style *with foreground/AJAX execution*, 
* (b) existing queues/tasks that run in the background with a bespoke runner (*not currently done in core - but does happen in contrib*), and
* (c) new queues/tasks which should use a standard/generic/automatic runner

This PR allows (a) and (b) to continue working as they do today. For (c), one would insert a record like:

```php
$dao = new CRM_Queue_DAO_Queue();
$dao->type = 'Sql';
$dao->name = 'my-own-queue';
$dao->is_autorun = 1;
```

The standard/generic/automatic runner can then `SELECT * FROM civicrm_queue WHERE is_autorun=1` and begin dequeuing items as appropriate.

Note @colemanw - I've included the commit to expose APIv4 access. This seems to somehow get conflated with `MailingEventQueue` -- eg it doesn't pass tests, and I get wrong data from `cv api4 Queue.getFields`. Would be great if you can see how to make the prettier `Queue` name work.

If that's not possible, then maybe we can give the API an alternate name like `SystemQueue` or `PersistentQueue` or `RegisteredQueue`?

### CODE REVIEW

**Comment by totten** [comment]
Note: This doesn't currently have a test of its own - but it does get test-coverage (a) in the follow-up PR #22325 and (b) in the `ConformanceTest`.

**Comment by colemanw** [comment]
@totten I see you got tests passing. Is that a fluke or did you figure it out?

My only concern with this PR is that it renames that other DAO. The name change is a good one and I see that APIv3 was already fudging those names anyway, but to hedge against unforeseen impacts maybe we should wait a few days and merge this after the RC is cut?

**Comment by totten** [comment]
@colemanw Yeah, I figured it out. There’s more discussion about the DAO-name/entity-name change in #22343 (the pre-req for this PR).

At a high level I think it would be reasonable to try and merge all the queue bits when we branch for the next RC - that way the changes are more cogently attached to a single version.

**Comment by totten** [comment]
Dependency has been merged. Rebased. Updated to specify schema version 5.47. Added upgrade steps for 5.47.

@eileenmcnaughton @colemanw - I think the main question at this point is whether y'all are down with the schema.

**Comment by eileenmcnaughton** [comment]
@totten yeah I think so - my money says that some field or other will be added to it & when we think more about batches that will change it in some way - but really the only fields to consider are

- type
- is_autorun

The later is just basically 'should this run in the background' & I don't feel like another name would be clearer

The first is a bit unusual in that if feels like 'type_id' with some way of listing availble types would be a more 'normal' approach - but I think you are trying to keep the field freeform & perhaps for a table with so little user interaction discoverability doesn't matter.

**Comment by eileenmcnaughton** [comment]
Added merge-ready - if some combo of @colemanw @seamuslee001 & @demeritcowboy are good with the type field (or don't care enough to comment) we should merge

**Comment by demeritcowboy** [comment]
I appreciate the ping but I'll admit I don't have any interest in the recent queue PRs unless it allows feedback during queue runs to be given to the user. (Currently your only option is to throw an error and then let them wait staring at the frozen progress bar until they get tired of waiting.) I didn't see that as a goal in the ticket, but again admit I haven't fully read through it. I've also been assuming this is all part of some paid work, and if so there should be others who can test/chime-in.

**Comment by eileenmcnaughton** [comment]
Agreed with @totten that with a pseudoconstant function this becomes MOP

**Comment by totten** [comment]
@eileenmcnaughton I've pushed an update to add pseudoconstant.

On a related topic (but hopefully not blocking for this specific PR)....

> (@demeritcowboy) Currently your only option is to throw an error and then let them wait staring at the frozen progress bar until they get tired of waiting.

You are correct that that issue isn't a focus of dev/core#1304 , but I think that's a really interesting point about the current AJAX `QueueRunner`. I'd be curious sometime to talk/learn about how you'd expect error-handling for that scenario.

The ticket's goal is more about providing background processing queues -- instead of a web-browser with repeated AJAX-calls, you have some headless agent running tasks. In the schema proposed here, the flag `is_autorun` would distinguish between those types of queues. Compare:

* (*Background use-case*) If the app-developer wants a generic background agent to automatically pickup tasks for this queue...then set `is_autorun=1`.
* (*Foreground use-case*) If the app-developer wants to put this front of a user (browser/AJAX), then they should use `is_autorun=0` and setup some other agent for running (ie `CRM_Queue_Runner->runAllViaWeb()`).

So I think you're saying that the existing foreground runner (`runAllViaWeb()`) needs a better API for handling errors? I guess the background runner also needs some kind of API for handling errors - although I guess the context is different. In foreground usage, you might respond to an error by changing the UI/screen/appearance. In background usage, there is no UI - all you can do is some kind of background reaction. (A log-record and/or hook-notification come to mind.) I'm not immediately seeing a way for them to have the same DX for error-handling... but maybe you have some ideas on error-handling DX?

**Pull request merged**
