### PR TITLE
Fix use col "Soft Credit Amount Stats" and any filter of contribution…

### PR DESCRIPTION
**Pull request by CsarRamos**
Overview
----------------------------------------
When try to use report contribution summary with col "Soft Credit Amount Stats" and add any filter of contribution stats ex: Cotribution Count "total_count_value" the report show error: "DB Error: no such field"

Before
----------------------------------------
You cannot use the contribution filters stats with the "Soft Credit Amount Stats"  column

After
----------------------------------------
You use all stats with all filters

Technical Details
----------------------------------------
Fixed needed columns when use this fields

Comments
----------------------------------------
issue: https://lab.civicrm.org/dev/core/issues/1575

### CODE REVIEW

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by mlutfy** [comment]
@agh1 Is this something you could review? (I think you have worked on this issue before?)

**Comment by jaapjansma** [comment]
test this please

**Comment by jaapjansma** [comment]
* General standards
    * Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
        * __PASS__ : The goal/problem/solution have been adequately explained in the PR.
    * User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
        * __PASS__: The change would be intuitive or unnoticeable for a majority of users who work with this feature.
    * Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
        * __PASS__: The changes do not require documentation.
    * Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
        * __PASS__: We tested this in dmaster and in the test environment of this PR.  In dmaster we get an error and with this PR it works.
* Developer standards
    * Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
        * __PASS__: The change preserves compatibility with existing callers/code/downstream.
    * Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
        * __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
    * Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
        * __PASS__: The change is trivial enough that it does not require tests.
    * Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
        * __PASS__: The test results have failures, but these have been individually inspected and found to be irrelevant.

@eileenmcnaughton or @mattwire could one of you merge this PR?

**Comment by mattwire** [comment]
test this please

**Comment by seamuslee001** [comment]
Merging as per the review

**Pull request merged**
