### PR TITLE
dev/core#792 Fix Contributions not recording if selected membership is none when using a membership priceset

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
See https://lab.civicrm.org/dev/core/issues/792

Basically if you have a priceset on the contribution page with an optional membership and submit without selecting a membership (but do select another amount) no contribution will be created and no payment will be taken - a contact will be created and they will see the "thankyou for your payment" but there will be no record of any contribution in CiviCRM.

Before
----------------------------------------
Broken

After
----------------------------------------
Fixed (I hope).

Technical Details
----------------------------------------
Looks like $this->_useForMember was put in the If statement as a shortcut instead of checking that there is actually a selected membership.
I've extracted the check that extracts memberships from the priceset and we're now calling this instead of using $this->_useForMember as well as calling the same function later to actually extract the memberships for processing.

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire looks like a code improvement - can we get a test on it?

**Comment by jitendrapurohit** [comment]
A test is added to verify this fix - https://github.com/civicrm/civicrm-core/pull/15228

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit thanks for doing the test - have you also reviewed this PR?

**Comment by jitendrapurohit** [comment]
I've tested a few cases in which this has worked fine, but not done the complete review. I'll test more and comment on this once done.

**Comment by jitendrapurohit** [comment]
@eileenmcnaughton I've done manual testing by applying these changes and checked various combination for membership priceset, separate contribution without priceset, etc and it has worked fine in all of them. +1 to get this merged 👍

**Pull request merged**
