### PR TITLE
SearchKit - Fix adding deep joins

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
This fixes a UI bug that was preventing joins past a depth of 2 to be added.

### CODE REVIEW

**Comment by francescbassas** [comment]
@avall-llovera please, test this

**Comment by aydun** [comment]
Quick test looks good - resolves the problem I was seeing previously.

**Comment by avall-llovera** [comment]
Tested. Works well, now we can join (almost) unlimited depth.

**Comment by seamuslee001** [comment]
merging based on the above testing

**Pull request merged**
