### PR TITLE
[TEST][EXPORT] Improve unit test on export.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This updates the methodology used to test the membership export. I also made it check a bunch more fields while I was at it

Before
----------------------------------------
Less test cover

After
----------------------------------------
More test cover

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
test this please

**Comment by colemanw** [comment]
Adding MOP based on code review.

**Comment by colemanw** [comment]
@eileenmcnaughton 

> Test Result (1 failure / ±0)
>  CRM_Export_BAO_ExportTest.testMergeSameAddress

**Comment by eileenmcnaughton** [comment]
Argh cleanup issues -updated

**Pull request merged**
