### PR TITLE
CRM-16842 add EntityBatch API (fixed).

### PR DESCRIPTION
**Pull request by saurabhbatra96**
## Original PR: https://github.com/civicrm/civicrm-core/pull/6211
- CRM-16842:
  https://issues.civicrm.org/jira/browse/CRM-16842

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by monishdeb** [comment]
add to whitelist

**Comment by saurabhbatra96** [comment]
Not exactly sure what is going wrong here. Might be related to an issue I was watching recently:
https://issues.civicrm.org/jira/browse/CRM-17303

**Comment by eileenmcnaughton** [comment]
Yes - it's definitely a new-ish failure & definitely not caused by this PR so I'm merging. As a note there are a few intermittant failures in the test suite that seem to depend on some timezone interaction.

**Comment by seamuslee001** [comment]
@saurabhbatra96 @eileenmcnaughton I think i got that test failure fixed. Issue was that between midnight and 10 am UTC it would only be passing a single digit for an hour when the radio date needs it in 24 ie. 04 or 06. So have manually set the hours and minutes to avoid this. In the civi Mail UI it is already in 24 hour time.

**Pull request merged**
