### PR TITLE
Typo fix: remove space before question mark.

### PR DESCRIPTION
**Pull request by AdamHillier**

### CODE REVIEW

**Comment by JKingsnorth** [comment]
Jenkins test this please

**Comment by JKingsnorth** [comment]
This is a non-functional change

**Comment by totten** [comment]
jenkins, ok to test

**Comment by colemanw** [comment]
I don't see the point of putting two sentence fragments in two different `{ts}` strings. It's one sentence. It should be just one `{ts}`.

**Comment by colemanw** [comment]
I know it's a pre-existing condition, but the reason I suggest fixing it now is because then we only change the string once instead of making translators re-translate and then change it again.

**Comment by AdamHillier** [comment]
That makes sense, I've fixed it.

A few lines later in the elseif there's the exact same string, with the translation also split, but merging that would include a <span> in the string for translating. Is there any way around that?

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
Ok this looks like it's had quite enough QA for the scale of the patch :-) Setting to merge on pass

@samuelsov do you have any advice on Adam's question?

**Pull request merged**
