### PR TITLE
Afform - Drop directive support for attribute, only support elements as afforms

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
This changes every afform directive from AE to only E.

Before
----------------------------------------
Afforms could be invoked in these ways:

```html
<!-- Basic call -->
<div my-afform></div>
<my-afform></my-afform>

<!-- Call with data -->
<div my-afform="{...}"></div>
```

After
----------------------------------------
Afforms can only be invoked like this:

```html
<!-- Basic call -->
<my-afform></my-afform>

<!-- Call with data -->
<my-afform options="{...}"></my-afform>
```

Comments
----------------------------------------
My reasons for wanting this change are:

1. It's recommended best-practice by Angular docs.
2. It allows us to migrate afforms from directives to components.
3. Makes it easier to scan an html document for afforms - you don't have to look through it twice.

### CODE REVIEW

**Comment by colemanw** [comment]
@totten I was in the middle of writing some code to scan an afform's html for other embedded afforms (e.g. blocks) and the code was easier to write and more efficient at runtime with this change. Also the other reasons I mentioned above.

**Comment by seamuslee001** [comment]
@colemanw test fail relates here but might need to be sorted once there is agreement if this is the right change to make or not

**Comment by totten** [comment]
So the nice thing about `A`ttribute mode is that there's a simple/straight-forward way to make a reusable/parameterized block, e.g. from [the docs](https://github.com/civicrm/civicrm-core/blob/master/ext/afform/docs/embed.md#embedding-forms-afform-as-reusable-building-block):

> Moreover, you can pass options to helloWorld:
> 
> ```html
> <div hello-world="{phaseOfMoon: 'waxing'}"></div>
> ```
>
> Now, in `ang/helloWorld.aff.html`, you can use `options.phaseOfMoon`:
>
> ```html
> Hello, {{routeParams.name}}. The moon is currently {{options.phaseOfMoon}}.
> ```

Setting aside for the moment the contract-break (because maybe that's manageable), the main question would be -- if you're strictly using `E`lement mode, then how do you pass through parameters?

**Comment by colemanw** [comment]
@totten if we need to pass params to an afform directive, we can pick any string as the standard attribute name. There's no reason for it to be the directive name. We could pick `options` or `params` or `settings` or whatever.

But I'm not convinced we aren't getting into YAGNI terriroty here. Aside from the tests, no afform uses this feature.

**Comment by totten** [comment]
> if we need to pass params to afform directives, we can pick any string as the standard attribute name. There's no reason for it to be the directive name. We could pick `options` or `params` or `settings` or whatever.

OK, that's a good idea. If there's a generic `options`, then I think that covers it.

```html
<!-- Consumer -->
<hello-world options="{phaseOfMoon: 'waxing'}" />

<!-- Implementation: hello-world.aff.html --> 
Hello, {{routeParams.name}}. The moon is currently {{options.phaseOfMoon}}.
```

> But I'm not convinced we aren't getting into YAGNI terriroty here.

I'm not convinced we won't gett lost in triple negative territory. :upside_down_face:

More seriously, the comment didn't resonate with me, but maybe it's a contrast between these two framings:

1. "Afform is an interoperable flavor of Angular that strictly uses HTML. It's an on-ramp into Angular and provides the essence of Angular in a skinnier format."
2. "Afform is a storage substrate and runtime for the GUI builder for CRUD forms."

If one primarily thinks of it as a substrate for the GUI form-builder, then (by definition) it only needs the features supported by the GUI form-builder. Anything else is not needed. (This line of reasoning seems a bit circular, but I can see how it gets one to "YAGNI" right now.)

OTOH, if one primarily thinks of it as an HTML-oriented flavor of Angular, then it needs enough functionality to convey the essence of Angular (i.e. routes, modules, directives/components). If it allows you to create directives/components -- but they can't accept *any* parameters -- then I think it would lose the essence. Of course, that's subjective. But I do think that supporting an `options` would suffice to convey this essence.

Going back to the main thrust of the PR...  I like the main points - i.e. now that we have `component()`s, it makes more sense to map `*.aff.html` files to `component()`s. And using a singular format (`E`lement) instead of multiple formats (`AE`) reduces potential ambiguity and should ultimately make it easier to read/write/validate. It's obviously a notational break, but that seems manageable.

**Comment by colemanw** [comment]
@totten I don't think we disagree about not keeping `A`ttribute support :)

I've updated this PR to update docs & tests with only `E`lements and the `options` attribute, which still strikes me as suspiciously unused, but perhaps we'll revisit that question at a later date. At any rate it's a good thing it's unused for now because when migrating the directive to a component the options will be bound to the controller object not the scope.

**Comment by totten** [comment]
* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __Soft Pass__: I added a few more examples to Before/After. I still want to add with some more suggestions in case one is affected by the `r-tech` issues, but will this post-merge.
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __Pass__: Does not change user interface or business logic
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __Pass__: There's an included update for dev docs.
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __Soft Pass__:
        * I used the updated docs to make a couple example forms with manual HTML (building on each other), and this worked. :+1:
        * I used the GUI editor a bit to play around with the blocks (which make use of nested forms). The GUI editor seemed to work with the blocks as expected, and the resulting form would open/display correctly.
        * I had trouble submitting data. (The example form would open -- but the "Submit" button was inert and failed to fire an AJAX call.) The same problem appears in current `master`, so I doubt it's a problem in this patch. Based on bisecting, it appears to be a regression circa 65d7084b48717b3ce9fadab9eb810d934f63c4ce. :warning: 
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __Needs work__: This is the trickiest one.
        * It is a compatibility break, but it's needed to align with Angular 1.5+, and the eventual BC-break won't get any smaller if left alone.
        * It's fairly niche at this time -- not accessible in the GUI. 
        * Grepping `universe`, I only found three published files that need an update:
            * Within `civicrm-core`, the old notation appears in `oauthProviderDetail.aff.html` and `oauthClientAdmin.aff.html`. 
            * Ping @eileenmcnaughton - in https://github.com/eileenmcnaughton/deduper/blob/1.4/ang/deduper/dupefindCntrl.html , the calls to `conflict-basic` and `contact-basic` would need an update, e.g. `<conflict-basic options="{...}">`.)
          * I clearly didn't recollect the usages within  `oauthProviderDetail.aff.html` and `oauthClientAdmin.aff.html`  - they only appeared with tooling (ie grepping universe and running https://gist.github.com/totten/df8ac9307a9ddb730ad8c451c2e37c90). In an ideal world, our tooling would be able to flag all deviations (whether in core/universe or private/local). But I'll be happy if we use this as an excuse to chip away a bit.
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __Pass__
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __Pass__
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __Pass__

So I think the take-away on things needing attention:

* (Immediate/Hard-Blocker) Update civicrm-core's oauth-client
* (Near/Not quite blocker) Chip away at validation/analysis tooling
* (Near/Not quite blocker) Update `deduper`

**Comment by totten** [comment]
Pushed up the fix for oauth-client.

**Comment by eileenmcnaughton** [comment]
Unrelated fail - I understand the merge-ready to mean you are good with it now but want someone to double check the bit you did @totten

**Comment by colemanw** [comment]
Changes look good. Test fail unrelated.

**Pull request merged**
