### PR TITLE
dev/core#2164 Exporting in localized civicrm crashes due to long translations in columns T_Boolean

### PR DESCRIPTION
**Pull request by bjendres**
Overview
----------------------------------------
Patch for [CORE-2146](https://lab.civicrm.org/dev/core/-/issues/2164). Quote from there:
> Export tmp tables are created with varchar(16) for T_BOOLEAN types. This may be sufficient for the short-worded language 
> English but if translated we get longer export values. So this should be 32 or more

Before
----------------------------------------
Export of all contact data with at least one contact with an email on hold in German l10n crashes with ``Data too long`` exception.

After
----------------------------------------
Export works again.

Technical Details
----------------------------------------
This is a re-implementation of @wannesderoy's https://github.com/civicrm/civicrm-core/pull/18920

### CODE REVIEW

**Comment by monishdeb** [comment]
Test failure seems related https://test.civicrm.org/job/CiviCRM-Core-PR/40108/

**Comment by bjendres** [comment]
Yes, thanks @monishdeb. It seems to be more complicated than I thought, and maybe we have to extend all the ID fields to 64 characters as well. I'll adjust the PR

**Comment by eileenmcnaughton** [comment]
Not quite yet...

CRM_Export_BAO_ExportTest.testExportSpecifyFields with data set #0
CRM_Export_BAO_ExportTest.testGetSQLColumnsAndHeaders with data set #0
CRM_Export_BAO_ExportTest.testGetSQLColumnsAndHeaders with data set #1
CRM_Export_BAO_ExportTest.testGetSQLColumnsAndHeaders with data set #2
CRM_Export_BAO_ExportTest.testGetSQLColumnsAndHeaders with data set #3
CRM_Export_BAO_ExportTest.testGetSQLColumnsAndHeaders with data set #4
CRM_Export_BAO_ExportTest.testGetSQLColumnsAndHeaders with data set #5
CRM_Export_BAO_ExportTest.testGetSQLColumnsAndHeaders with data set #6

(Can you squash them at the end?)

**Comment by eileenmcnaughton** [comment]
@bjendres are you able to squash the commits now you have beaten jenkins into submission?

**Comment by bjendres** [comment]
> @bjendres are you able to squash the commits now you have beaten jenkins into submission?

looks like I'm not. idk what happened, but nothing good. I'll open a new PR :(

**Comment by bjendres** [comment]
(messed up and) withdrawn in favour of https://github.com/civicrm/civicrm-core/pull/19963

**Pull request closed without merging**
