### PR TITLE
CRM-18483: Paypal Std transaction failure fix

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
This includes 3 patches in 4.7.12 not yet merged to master & one patch on master. However, another patch on the joomla! repo is also required

---
- [CRM-18483: Paypal payments - Pending (Incomplete Transaction)](https://issues.civicrm.org/jira/browse/CRM-18483)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton Eileen can you please rebase this now?

**Comment by eileenmcnaughton** [comment]
done!

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by eileenmcnaughton** [comment]
I'm merging this based on the success testing so far. That at least means people can check out the dist for testing  - there still seem to be some remaining issues

**Pull request merged**
