### PR TITLE
SearchKit - Make hierarchical tables collapsible

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
SK tables with nested hierarchies can now display them as collapsed, which makes it visually easier to work with parent/child rows.

image

---

image

### CODE REVIEW

**Comment by aydun** [comment]
Looks good - that all seems to work well.  One test failure to sort out.

Just to note in passing that groups are odd in that they can have multiple parents.  The hierarchical display shows them under one parent correctly but there is no indication of the connection to the other parent. But that is not from this PR and niche anyway.

**Comment by colemanw** [comment]
@aydun I've been thinking that since the "multiple parents" thing is so problematic, esp from a performance POV, we really ought to add a setting to turn it off, and have that setting be the default.

**Comment by aydun** [comment]
@colemanw That seems reasonable.  Would be interesting to know if people actually use multiple parents.  How about a status check that looks for groups with multiple parents and asks people to respond on a lab issue?

**Comment by colemanw** [comment]
@aydun https://github.com/civicrm/civicrm-core/pull/31413

**Pull request merged**
