### PR TITLE
Ensure that original array is modified not copy of array when in php7…

### PR DESCRIPTION
**Pull request by seamuslee001**
… when loading saved search

@totten @monishdeb I haven't actually seen any evidence of things not working quite right in this space yet but just looking at the code it just looked like another foreach issue waiting to happen

### CODE REVIEW

**Comment by seamuslee001** [comment]
jenkins re test this please

**Comment by jitendrapurohit** [comment]
I guess we don't have to worry here as foreach behaves strangely only when the main iterating variable is passed by-ref to the function (for eg refer : https://github.com/civicrm/civicrm-core/pull/9024#issuecomment-246944550). As `$result` is generated inside `getFormValues()`, this should work in the same way as it did in previous versions.

Moreover, I see there are multiple places inside foreach() where `$value` gets modified, which inturn will go on updating the main variable `$result` (which was not the case before). So it **may** lead to adverse effect.

**Comment by seamuslee001** [comment]
@jitendrapurohit I thought that the unset() which happens within the foreach would mean we still need to pass $value by reference as we want to affect $result not the copy of $result which is generated when foreach starts.

**Comment by jitendrapurohit** [comment]
Unsetting of any of the values amid behaves in the same way in both the versions unless it is passed `by-ref`. So, `$result` would be the same after the foreach ends.

Only when it is passed by-ref to the function, unsetting a key in between would directly unset it from `$result` and would not loop that key in the next iteration (PHP 5).

Whereas, in PHP 7, as the copy of a variable iterates, the address it is different and the unset in that case will remove the key from the copied variable and would not affect the loop call. Example here would be helpful in explaining the exact behavior https://github.com/civicrm/civicrm-core/pull/9024#issuecomment-246944550.

**Pull request closed without merging**
