### PR TITLE
Move upgrade code to correct version

### PR DESCRIPTION
**Pull request by colemanw**
See https://github.com/civicrm/civicrm-core/pull/20553

### CODE REVIEW

**Comment by colemanw** [comment]
@monishdeb

**Comment by monishdeb** [comment]
Thank you for the PR @colemanw . Reviewed the patch, and looks good with the version change.

**Comment by colemanw** [comment]
No problem. I made the same mistake on my PR #20554 so I'll rebase that one once this is merged :)

**Comment by colemanw** [comment]
Ok this is merged and I've rebased the other PR. @monishdeb would you be able to review that one?

**Pull request merged**
