### PR TITLE
CRM-18298 - Implement hook_geocodeFormat

### PR DESCRIPTION
**Pull request by MegaphoneJon**
- [CRM-19298](https://issues.civicrm.org/jira/browse/CRM-19298)

---
- [CRM-18298: Implement hook_geocodeFormat](https://issues.civicrm.org/jira/browse/CRM-18298)

### CODE REVIEW

**Comment by JKingsnorth** [comment]
For information, the actual issue this relates to is [CRM-18298](https://issues.civicrm.org/jira/browse/CRM-18298)

**Comment by colemanw** [comment]
@PalanteJon I'm fine with merging this. Can you fix the conflict and also add this to http://wiki.civicrm.org/confluence/display/CRMDOC/Hook+Reference

**Comment by PalanteJon** [comment]
Conflict merged, documentation written: https://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_geocoderFormat

**Comment by PalanteJon** [comment]
Oh crap, I thought I rebased.  Let me fix this freaking PR.

**Comment by PalanteJon** [comment]
Closing in favor of https://github.com/civicrm/civicrm-core/pull/8168.

**Pull request closed without merging**
