### PR TITLE
Fix Invoice date

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Alternate to https://github.com/civicrm/civicrm-core/pull/28630

### CODE REVIEW

**Comment by agileware-justin** [comment]
@eileenmcnaughton I'm more inclined to go with both this and the other PR to be honest because changing customised message templates is such a major pain in the bum that it's not funny.

The original PR means that the desired behaviour works without requiring any message template changes, https://github.com/civicrm/civicrm-core/pull/28630

And then for new CiviCRM sites (5.69+) this PR will work and also be used when the message template is customised.

So the best of both worlds.

You could argue doing a message template upgrader to fix the existing customised message templates - go for it, as long as it works.

However, a Status Alert or an Upgrade Message informing people to manually update the Message Template is really not helpful.

**Comment by eileenmcnaughton** [comment]
@agileware-justin except that we are working towards removing those variable assignments anyway - so in general we are not fixing variables assigned to templates except when they can't be otherwise done by tokens / smarty native stuff.

I wasn't thinking to do a push-upgrade for this -(ie I wasn't going to pro-actively encourage sites with customisations to update their templates) at this stage because it feels like the sort of thing that we haven't heard much noise about & sites that wanted it could have made exactly this change on any of the last ? 10 or so? versions

**Comment by agileware-justin** [comment]
This is the output when using `{contribution.receive_date|crmDate:"F j, Y"}` on CiviCRM 6.67.3

image

**Comment by eileenmcnaughton** [comment]
@agileware-justin yeah - I didn't test it - I was mostly trying to point to the approach we would take - here  is similar code form the event template `'{event.end_date|crmDate:"%Y%m%d"}'` - so the format string needs %. 

But the underlying code calls the smarty date handling function - ie

```
  public static function crmDate($value, array $filter, string $format) {
    if ($value instanceof \DateTime) {
      // @todo cludgey.
      require_once 'CRM/Core/Smarty/plugins/modifier.crmDate.php';
      return \smarty_modifier_crmDate($value->format('Y-m-d H:i:s'), $filter[1] ?? NULL);
    }
    if ($value === '') {
      return $value;
    }
```

So any of the variants found grepping for `crmDate:` should be the right approach - including variants like `crmDate:"full"` - which gets the date from the site's settings

**Comment by agileware-justin** [comment]
> @agileware-justin except that we are working towards removing those variable assignments anyway - so in general we are not fixing variables assigned to templates except when they can't be otherwise done by tokens / smarty native stuff.

With respect, I do not think this is the correct approach. It's wrong - should be fixed, have provided a fix.

> I wasn't thinking to do a push-upgrade for this -(ie I wasn't going to pro-actively encourage sites with customisations to update their templates) at this stage because it feels like the sort of thing that we haven't heard much noise about & sites that wanted it could have made exactly this change on any of the last ? 10 or so? versions as a customisation if they wanted it

People have noticed and been complaining about it...
https://civicrm.stackexchange.com/questions/21128/how-do-i-print-the-received-date-on-an-invoice
https://lab.civicrm.org/dev/core/-/issues/1403
https://forum.civicrm.org/index.php%3Ftopic=16420.0.html

**Comment by agileware-justin** [comment]
> So any of the variants found grepping for crmDate: should be the right approach - including variants like crmDate:"full" - which gets the date from the site's settings

The short date format would be preferred. That way, people can customise it in their settings, I think its: crmDate:"shortdate"

**Comment by eileenmcnaughton** [comment]
So this is the list of site-configured formats

https://github.com/civicrm/civicrm-core/blob/fc6f60f48a72ce4f0531809a49ff41ad4b9608ad/CRM/Core/Smarty/plugins/modifier.crmDate.php#L40-L50

**Comment by eileenmcnaughton** [comment]
@agileware-justin you are correct that there have been many discussions about dates over the years - without much clear consensus, and with pretty long periods of time when it doesn't come up at all. The token has been available since December 2021 so I guess it hasn't come up much in the last couple of years or we would have changed it to the token when it did.

 I'm fine with updating the default template since the existing behaviour doesn't seem right to me - I'm not in a hurry to impose the change on people - given that it was originally coded the way it is on purpose. However, if there are people who want it I think they could use `{$smarty.now}

**Comment by eileenmcnaughton** [comment]
@agileware-justin re short date - I removed the date formatting for now - I think that defaults back to an ISO date so perhaps "shortdate" would be better - but that could also be tweaked as a follow up - cos I'm not going to look at this further today

**Comment by eileenmcnaughton** [comment]
I'll close this out actually - my main goal here was to demonstrate the approach we would be looking to use to change the template - but I'm just mindful that I'm getting sucked into something that isn't my paid work

**Pull request closed without merging**
