### PR TITLE
Allow to skip geocoding when creating an address with the api

### PR DESCRIPTION
**Pull request by wdecraene**
[CRM-17777](https://issues.civicrm.org/jira/browse/CRM-17777)

### CODE REVIEW

**Comment by colemanw** [comment]
I think this belongs in the "options" array rather than directly in `$params` although it's a gray area and the downside to "options" is that they are not (yet) discoverable via the api explorer.

**Comment by wdecraene** [comment]
I agree, but I implemented this extra parameter based on the (existing) street_parsing parameter.  So maybe this parameter should be added for now and when cleaning the api optional parameters should move to an options array ?

**Comment by colemanw** [comment]
Agreed.

**Comment by colemanw** [comment]
jenkins, test this please

**Comment by wdecraene** [comment]
Removed spaces to apply to the coding standards.

**Comment by wdecraene** [comment]
jenkins, retest this please

**Comment by wdecraene** [comment]
Apparently, I couldn't trigger jenkins to retest (yet).

@colemanw Can you trigger to restest? Thanks in advance!

**Comment by colemanw** [comment]
jenkins, add to whitelist

**Pull request merged**
