### PR TITLE
CRM-17718 update repeattransaction & IPNs to prefer contribution recur data

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
This isn't nearly as scary as it looks. The main changes are

1) changes to the edit recurring contribution form to allow campaign id & financial type to be edited - with some limitations

2) getting the calls to repeat recurring transactions to 'prefer' those values over the original contribution

3) a bit of tidy up

4) tests

Note that 2, 3 & 4 are pretty heavily tested so the main QA focus is the form change. I used existing functions to conditionally add campaign (if it's enabled, if there are some etc) and added the following checks for conditionally adding financial type
1) ACLs are not enabled for financial types - out of scope. I used an existing function
2) the 'template contribution' only has one line item. Too complicated otherwise

---

 https://issues.civicrm.org/jira/browse/CRM-17718

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by davecivicrm** [comment]
retest this please

**Comment by davecivicrm** [comment]
Jenkins, retest this please.

**Comment by davecivicrm** [comment]
@eileenmcnaughton I'm wondering if these test regressions are related to this PR:
https://test.civicrm.org/job/CiviCRM-Core-PR/7150/

I don't recall seeing them previously. I'll try asking Jenkins to re-run the test to see if that changes things.

**Comment by davecivicrm** [comment]
Jenkins, retest this please.

**Comment by davecivicrm** [comment]
@eileenmcnaughton I provided feedback on the form changes on the Jira issue.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by davecivicrm** [comment]
Jenkins, retest this please.

**Pull request merged**
