### PR TITLE
APIv4 - Add FinancialAccount, FinancialType entities, and EntityFinancialType bridgeEntity

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Exposes 3 entities to the API.

Technical Details
----------------------------------------
Nothing fancy, just uses all the default DAOEntity settings.
Marked EntityFinancialType as an EntityBridge since it just serves to link other things together.

### CODE REVIEW

**Comment by colemanw** [comment]
retest this please

**Comment by seamuslee001** [comment]
Test fail looks unrelated but not 100% sure

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
retest this please

**Comment by eileenmcnaughton** [comment]
@colemanw will need to be changed to reflect your other PR

**Comment by colemanw** [comment]
Mysterious test failure persists :(

**Pull request closed without merging**
