### PR TITLE
CRM-20266, Added card type and pan truncation form fields on Particip…

### PR DESCRIPTION
**Pull request by pradpnayak**
…ant Form

----------------------------------------
* CRM-20266: Store CC type and last 4 digits from Event Registration form
  https://issues.civicrm.org/jira/browse/CRM-20266

### CODE REVIEW

**Comment by pradpnayak** [comment]
depends on https://github.com/civicrm/civicrm-core/pull/10050

**Comment by colemanw** [comment]
@eileenmcnaughton can you review this one?

**Comment by JoeMurray** [comment]
please retest this

**Comment by JoeMurray** [comment]
jenkins, please test this

**Comment by eileenmcnaughton** [comment]
Per comments elsewhere #10157  was created to add these fields to the payment form & was intended to replace this

**Comment by monishdeb** [comment]
@JoeMurray @pradpnayak @eileenmcnaughton I am closing this PR in favor of https://github.com/civicrm/civicrm-core/pull/10157

**Pull request closed without merging**
