### PR TITLE
Up the deprecation on old hook

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
@nganivet @totten does this make sense to do? Looks like this has been deprecated for about 18 months

### CODE REVIEW

**Comment by nganivet** [comment]
This is fine with me. Should it be deleted from the developer documentation as well?

**Comment by eileenmcnaughton** [comment]
yep it should be - possibly you did when you deprecated the hook?

**Comment by nganivet** [comment]
Just checked and this is not in the latest version of the wiki nor in the books. So no changes needed.

**Comment by eileenmcnaughton** [comment]
OK I merged - I'd rather rip it out but at least this takes us a step closer

**Pull request merged**
