### PR TITLE
dev/core#1576 Use URLs for patches, avoid local path issues with composer-patches

### PR DESCRIPTION
**Pull request by xurizaemon**
Overview
----------------------------------------
Resolve [LAB-1576](https://lab.civicrm.org/dev/core/issues/1576) by using remote URLs.

Before
----------------------------------------
`composer` patches some dependencies, loading the `*.patch` files from within `civicrm-core.git`.

This works when using `civicrm-core` as the root-project - but not when using it as a library. In the latter case, it attempts to load the patches but fails to find them in the given location.

After
----------------------------------------
`composer` patch the same dependencies, fetching the `*.patch` files from absolute URLs.

This ought to resolve any ambiguity in loading the `*.patch` files.

### CODE REVIEW

**Comment by seamuslee001** [comment]
@xurizaemon the problem there is that if lets say someone is trying to download 5.22 but the patch changes in the 5.24 series then you would be downloading the 5.24 version of the patch not the 5.22 version

**Comment by xurizaemon** [comment]
In that event, you'd replace `master` in the URL with the appropriate tag to lock the patch at that release state.

**Comment by xurizaemon** [comment]
Can you see why that's failed @seamuslee001 ? I'm not familiar with the build process. Per https://test.civicrm.org/job/CiviCRM-Core-PR/31937/console if I check out `216a68f77af904ae637e52e9f07c5a3867893d90` and then execute `curl https://patch-diff.githubusercontent.com/raw/civicrm/civicrm-core/pull/16473.patch | patch -p1 --dry-run` the patch seems to apply.

**Comment by totten** [comment]
Ah, interesting. So is it correct to infer from the relative-path of a patch-file is always evaluated relative to the root-project -- and thus breaks down when the same project is loaded as dependency?

> Do you see why that's failed @seamuslee001 ? I'm unfamiliar with the build process.

__tldr__: The buildbot complained about a merge-conflict, so rebase the PR.

__longer__: Under the hood, `git` has multiple techniques for applying patches. The build-bot uses `git am`, which is more forgiving about some things and less forgiving about others. The Github UI seems more like `git merge`, which behaves slightly differently. There are some edge-cases (*don't ask me exactly what*) where `git am` and `git merge` disagree about whether a patch is mergeable/conflicted.

Regardless of which agent complains about a merge-conflict (Github UI or build-bot), the solution is the same -- update/rebase the PR.

> In that event, you'd replace master in the URL with the appropriate tag to lock the patch at that release state.

Oof, that sounds like it'd add new steps every time one branches or tags? Also, it doesn't solve the PR dev/review problem: suppose you want to add a new patch-file or modify an existing patch-file. At the time when you write a revision locally (and also the time when the build-bot tests the patch), the proposed patch-file has not been published to `master` (or any official branch).

I noticed that a lot of folks in the Drupal community use patch-URLs that reference the issue-tracker (i.e. the patch is initially posted as an attachment). I think that workflow makes sense:

1. Post the proposed patch-file in some (relatively) immutable store. A content-addressable system with CDN would be ideal, but I think that a Gitlab file-attachment would do. A reference to a previously-published revision somewhere on Github could also do it.
2. Submit a PR to add/modify the patch-URL in`civicrm-core:composer.json`.
3. The patch-URL as given will remain the same (until someone needs a new patch file).

I've pushed up an updated branch which (a) is rebased and (b) uses a less mutable URL.

**Comment by totten** [comment]
* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __Pass__: I  updated the description with a bit more explanation.
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __Pass__: No user impact
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __Pass__: No user impact
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __Soft Pass__:
        * For the scenario with `civicrm-core` as root-project, I ran `composer install` and spot-checked the file patch-files and outputs.
        * For the scenario with `civicrm-core` as a library, there's no worthwhile way to take the proposal and do a realistic simulation of `composer install` after this revision. We'll just have to check up on it post-merge. (And, happily, there is some loose coverage for that scenario in E2E matrix.)
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __Pass__
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __Pass__
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __Soft Pass__: We may want a note somewhere in the dev-docs to indicate that patch URLs should be essentially immutable, but that doesn't need to block merge.
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __Soft Pass__: The last test-run was successful. I'm push a cleanup to remove some unusued files (and shouldn't change outcome), but we may want to wait for the new test run to finish.

Additionally, since I did both review and revision on this PR, I'm gonna hold off on merging myself and give it a `merge ready` (inviting @seamuslee001 or @eileenmcnaughton to give a skim)

**Comment by seamuslee001** [comment]
@totten is there a reason why we are actually deleting the patches rather than just keeping a copy and updating the relevant commit # if we need to change?

**Comment by totten** [comment]
You know, it frustrates me that `composer.json` doesn't allow docblocks. I don't think someone can look at this and correctly *intuit* a good workflow. But there's nowhere good to put forward-looking notes.

If we were looking forward to future patches, I think a better example would be dev/core#1562 and the `cache/integration-test` patches. Those patches are already written and merged and published on Github. They're just not available in a suitably published release, so we have to apply them explicitly. When first working on that issue, I actually found the patches by looking at the commit log for upstream's repo. If you asked me at the time to give a durable link to the needful patches, I would've given something like:

https://github.com/civicrm/civicrm-core/pull/16522/commits/b49989433dee5dba840fb3cc527791991cf173b7#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R241

```js
         "Allow adding tests": "https://github.com/php-cache/integration-tests/commit/05f97174c09364dc10c084a38ba0cfd5124f4cec.patch",
```

This meets the functional requirements - using an immutable URL on a fairly reliable server/CDN. It's also kinda nice how it points the way to contributing to the original project/repo. And if you're playing the game of coordinating with the upstream library maintainers, it's fairly easy to make URLs like that.

> (@seamuslee001) is there a reason why we are actually deleting the patches rather than just keeping a copy and updating the relevant commit # if we need to change?

IMHO, the files' existence would be misleading because they're not actually used.

Let's consider the old workflow and a new/hypothetical workflow (which I'm inferring from your comments).

* There's an old workflow with patch-files in `tools/.../MY.PATCH`.
    1. Find the patch file
    2. Update it
    3. Run `composer install`
    4. (If there's a problem, go back to step 1.)
* There's a new/hypothetical workflow (with patch-URLs pointing to `https://raw.githubusercontent.com/civicrm/civicrm-core/COMMIT/tools/.../MY.PATCH`): 
    1. Find the patch file
    2. Update it
    3. Commit the patch file
    4. Push to Github. Possibly open a WIP PR.
    5. Edit `composer.json` to use the URL of the patch-file.
    6. Run `composer install`
    7. (If there's a problem, go back to step 1.)

The new workflow would be (even) less intuitive than the old workflow.

But here's the really tricky part: if you don't get the memo about the new workflow, and if you're not an expert in the build-system, and if you follow the simpler/older/more-obvious workflow, then *the system won't complain* about the mistake. The `composer.json` still links to the old patch-file. That old patch-file is probably still a valid patch-file. Moreover, since it's a patch in a dependency, there's better-than-average odds that we don't have test-coverage for it. 

Of course, if the author+reviewer are knowledgeable and/or diligent, then someone will recognize a mistake. But the contributor community actually diverse in skills/experience/interests/etc. My guess: if you did 10 trials with different/random authors trying to update these patches, then you'd get 2-5 instances where the author doesn't realize that their change isn't going to be used.

**Comment by HeneryH** [comment]
Is there a quick hack I can do to get a good install?  My composer require give the following error:

`# composer require roundearth/civicrm-composer-plugin civicrm/civicrm-drupal-8
Using version dev-master for roundearth/civicrm-composer-plugin   
Using version ^5.23 for civicrm/civicrm-drupal-8
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)                     
Package operations: 28 installs, 0 updates, 0 removals
No patches supplied.
Gathering patches for dependencies. This might take a minute.
  - Installing zetacomponents/mail (1.9.1): Loading from cache
  - Applying patches for zetacomponents/mail
    tools/scripts/composer/patches/civicrm-custom-patches-zetacompoents-mail.patch (CiviCRM Custom Patches for ZetaCompoents mail)
   Could not apply patch! Skipping. The error was: The "tools/scripts/composer/patches/civicrm-custom-patches-zetacompoents-mail.patch" file could not be downloaded: failed to open stream: No such file or directory

In RemoteFilesystem.php line 515:
                                                                                                                           
  The "tools/scripts/composer/patches/civicrm-custom-patches-zetacompoents-mail.patch" file could not be downloaded: failed to open stream: No such file or directory                                                                             
                                                                                                                           

`

**Comment by MegaphoneJon** [comment]
@HeneryH I've been running a site in production for over a year without these patches and been unaffected because I'm using a third-party mailing extension.  However, as a quick fix, you can download those patches and apply them manually - the patch should indicate the file to patch.  `patch <filename> -i <patch file>`

**Pull request merged**
