### PR TITLE
CRM-16367 (Payment): adding the corrected PaymentToken table definition.

### PR DESCRIPTION
**Pull request by torenware**
First pass on adding the new payment token entity.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Add to whitelist

**Comment by colemanw** [comment]
jenkins, add to whitelist

**Comment by torenware** [comment]
I've now added the API definition and a phpunit test for that API.

@kurund: I noticed that while bin/setup.sh created the new table in the civi table, it did *not* create the table in the test database.  Do I need to update something else so the table will be automatically available to phpunit?

**Comment by torenware** [comment]
@eileenmcnaughton Do I need to do anything to inform the system that Jenkins should take another pass on the failed test?  The style issues should now be corrected.

**Comment by eileenmcnaughton** [comment]
when you do another push that will trigger it

**Comment by torenware** [comment]
If so, then we should know if I fixed it right shortly.

R

Rob Thorne
Torenware Networks

**Pull request closed without merging**
