### PR TITLE
CRM-16876 Proper fix for displaying countries in all capitials when p…

### PR DESCRIPTION
**Pull request by seamuslee001**
…roducing maling labels

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton @colemanw @mlutfy Hi folks

I think this is a much more stable fix for CRM-16876

**Comment by colemanw** [comment]
Does that mode indicate that we are printing mailing labels?

My original suggestion for uppercasing country names was to use css. That would be the ultimate in flexibility because it would be very easy to override.

**Comment by seamuslee001** [comment]
@colemanw according to the dotbloc 

GIven that this outputs to pdf i wasn;t sure there would be easy ways to add in such css and this seemed the most simplest fix. 
    * @param bool $mailing
    *   If true indicates, the call has been made from mailing label.

**Comment by mlutfy** [comment]
Would it be possible to fix with CSS? I tested and it didn't work (the HTML was escaped). How about sending it through Smarty? (as for custom greetings)

CiviCRM should provide a sane default for most people, and seems like upper-casing the country name is an international convention that should not cause problems to existing users in most locales, but imho it's a short term solution.

For example, [Canada Post recommends](https://www.canadapost.ca/tools/pg/manual/PGaddress-e.asp) that mailing labels be fully uppercase, not just the country name. [1] As it has been pointed out before, in Canada (and many other places) people do not print the country name for letters sent from inside the same country. Punctuation (including commas to separate different sections) should be avoided.

For the US, it seems that USPS/UPU also recommends uppercasing everything and not using punctuation.

In Australia, according to the UPU, the two last lines should be uppercase (city, state/province, postcode and country name).

For non-anglophone/francophone countries, foreign country names should be written in an "internationally recognised language", for which I haven't found a definition, but I would assume that this means English or French (English being the safer bet). So.. someone sending a letter from Bulgaria to France will want to have "FRANCE" on the mailing label, not "ФРАНЦИЯ". Same goes for the state/province.

In other words, if we want to fix mailing labels, we should consider:

- uppercase of some / all parts
- conditional display of the country
- conditional translation of the state/province and country.

So strtoupper() is only a partial fix for item 1. CSS would fix item 1, Smarty could help fix item 1 and 2, and item 3 might require a new token (and separate issue anyway).

This website is very practical to see formats in all countries:
http://www.upu.int/en/activities/addressing/postal-addressing-systems-in-member-countries.html

@nganivet  Any thoughts?

p.s. for multi-national organisations, we also need country-specific mailing-formats, but that's also a separate issue.

p.p.s. as tech people we often think that postal mail is deprecated stuff, but I noticed that users really use this feature heavily. It's a "major" feature of CiviCRM.

**Comment by seamuslee001** [comment]
@mlutfy Nice research, I like it. In regards to smarty, i think that is possible. but not sure how to implement, that would have to happen before we output to pdf.

**Comment by colemanw** [comment]
Looks like you could add it to print.css, as that is included in pdf 
generation:
https://github.com/civicrm/civicrm-core/blob/4.7.10/CRM/Utils/PDF/Utils.php#L97

Address elements would need to be wrapped in a span to identify them. 
That might be the tricky part because we wouldn't want tokens to always 
generate html (sometimes they are used in plain-text contexts).

**Comment by nganivet** [comment]
It seems like this is a much wider issue, and the proposed patch has limited scope. Our customers also have had lots of issues with address formats as CiviCRM is currently incapable of producing mailing labels with addresses in multiple countries.

Instead of this patch, I would propose we leverage a library such as https://github.com/commerceguys/addressing to 'reformat' all addresses before printing on a mailing label. This way the format would be proper whichever country the recipient is in, and we could produce labels for recipients in multiple countries in the same batch.

> The address format interface has getters for the following country-specific metadata:
> [...]
>     Which fields need to be uppercased for the actual mailing (to facilitate automated sorting of mail)

**Comment by seamuslee001** [comment]
@nganivet Nice find, I think it does make sense to do this, I have now reformatted the code to do it, @colemanw @mlutfy Folks can you review the updated code,

**Comment by seamuslee001** [comment]
There is one problem which is the plugin requires php 5.4

**Comment by colemanw** [comment]
Maybe it ought to be in an extension.
LEXIM!

**Comment by JoeMurray** [comment]
I think changing the functionality on how mailing addresses appear is a good candidate for LExIM, especially if we get to swap out old code in favour of an external library. Great work here!

**Comment by seamuslee001** [comment]
Yeh so i'm now coming around the swap out need to be lexim but i'm just wondering given what has been on this thread and what the original ticket is about should i go back to my original patch of if we are making mailing labels putting the country in all caps? @mlutfy @JoeMurray @colemanw @nganivet

**Comment by eileenmcnaughton** [comment]
@seamuslee001 is this an issue you are vested in? If so I would suggest focus your efforts on the extension & see whether there are other gaps.

If not I would probably close it all out as a won't fix for now & let some future person do the extension

**Comment by nganivet** [comment]
OK ... now you lost me on that LExIM stuff. I thought the LE stands for Leap by Extension, and the IM for Improve Monthly. This patch is clearly not a Leap (ie. no screen redesign, no grand reap/replace or any significant refactor) and more of an Improvement, so why ask for an extension? Can't we just merge the patch that @seamuslee001 produced in the next point release?

**Comment by eileenmcnaughton** [comment]
My reservation is that this appears to change behaviour with no opt-in element. I'm pretty sure that I have added custom fields to mailing labels on customer sites and this looks like it would un-add them and other customisation. I can't say that hand-on-heart I have customised mailing labels but it feels like it might be better as an opt-in.

As an opt-in an extension feels like a better fit than a setting - although the presence of a test does make that a harder call

**Comment by seamuslee001** [comment]
@nganivet The issue is that it doesn't work with our test suite (php 5.3)

**Comment by seamuslee001** [comment]
There appears to me to be a pretty standard thing that the country is in all caps in mailing labels

**Comment by eileenmcnaughton** [comment]
@seamuslee001 you are referring to your original PR? Yes, capitalising countries is common enough that I did a token in the past that removed the country if it matched the domain address country, or capitalised it otherwise -I feel like it was the AU standard not to include the country for domestic?

It's possible to include tokens in mailing labels. So, while I'm not completely sold on the original fix I don't think it would break something.

This commerce_guys one would probably break the rendering of tokens in mailing labels I think? Athough it is the better fix

**Comment by seamuslee001** [comment]
Closing this as https://github.com/civicrm/civicrm-core/pull/8908 has been merged

**Pull request closed without merging**
