### PR TITLE
[REF] Fix the default to_financial_account_id for generated transactions

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This fixes the default financial account id used in th to_financial_account_id column of civicrm_financial_trxn for the sample data
CiviCRM Financial Trxn is meant to store the account associated with the payment processor not the account id for the financial type as per the test here https://github.com/civicrm/civicrm-core/blob/aef4c7b3f337105999421301c2f7297fc0a47176/tests/phpunit/CRM/Event/Form/ParticipantTest.php#L702 and https://github.com/civicrm/civicrm-core/blob/aef4c7b3f337105999421301c2f7297fc0a47176/tests/phpunit/CRM/Event/Form/ParticipantTest.php#L722 and https://github.com/civicrm/civicrm-core/blob/2207b37c4023188ea09b44754a7d5e265bb67e46/tests/phpunit/api/v3/TaxContributionPageTest.php#L430

Before
----------------------------------------
Incorrect donation financial account id used

After
----------------------------------------
Correct default financial_trxn_id account used in sample data

ping @eileenmcnaughton @monishdeb

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
So it looks to me that the default financial account goes from 'Donation' to 'Accounts Receivable'

Can you update the PR template (or create a gitlab) explaining why / impacts

**Comment by seamuslee001** [comment]
I have updated the template a bit @eileenmcnaughton hopefully may explain it a bit better

**Comment by eileenmcnaughton** [comment]
@seamuslee001 hmm - it's explaining it in terms of tests - but this affects demo data too? I think you are saying there is a problem with the existing demo data but I'm not sure what - can you demonstrate with screenshots?

**Comment by seamuslee001** [comment]
@eileenmcnaughton so the current demo data has the to_financial_account_id set to Donation for the Financial Trxn however it should be set to one of the ones that has a relationship of Revenue. Where as the financial item contains the information of what the asset is iirc. 

So on a demo site I created a basic Check Donation the record in civicrm_financial_trxn was

```
mysql> SELECT * FROM civicrm_financial_trxn ORDER BY id DESC LIMIT 1;
+----+---------------------------+-------------------------+---------------------+--------------+------------+------------+----------+------------+---------+------------------+-----------+----------------------+-----------------------+--------------+--------------+----------------+-----------------+
| id | from_financial_account_id | to_financial_account_id | trxn_date           | total_amount | fee_amount | net_amount | currency | is_payment | trxn_id | trxn_result_code | status_id | payment_processor_id | payment_instrument_id | card_type_id | check_number | pan_truncation | order_reference |
+----+---------------------------+-------------------------+---------------------+--------------+------------+------------+----------+------------+---------+------------------+-----------+----------------------+-----------------------+--------------+--------------+----------------+-----------------+
| 94 |                      NULL |                       6 | 2020-07-24 17:33:00 |        50.00 |       0.00 |      50.00 | USD      |          1 | 12345   | NULL             |         1 |                 NULL |                     4 |         NULL | NULL         | NULL           | NULL            |
+----+---------------------------+-------------------------+---------------------+--------------+------------+------------+----------+------------+---------+------------------+-----------+----------------------+-----------------------+--------------+--------------+----------------+-----------------+
1 row in set (0.00 sec)
```
The financial item is:

```
mysql> SELECT * FROM civicrm_financial_item ORDER BY id DESC LIMIT 1;
+----+---------------------+---------------------+------------+---------------------+--------+----------+----------------------+-----------+-------------------+-----------+
| id | created_date        | transaction_date    | contact_id | description         | amount | currency | financial_account_id | status_id | entity_table      | entity_id |
+----+---------------------+---------------------+------------+---------------------+--------+----------+----------------------+-----------+-------------------+-----------+
| 94 | 2020-07-24 17:33:37 | 2020-07-24 17:33:00 |        202 | Contribution Amount |  50.00 | USD      |                    1 |         1 | civicrm_line_item |        97 |
+----+---------------------+---------------------+------------+---------------------+--------+----------+----------------------+-----------+-------------------+-----------+
1 row in set (0.00 sec)
```

Relevant Financial Accounts are:
```
+----+--------------------------------+------------+---------------------------+-----------------+-------------------+-----------------------------------------------------------------------+-----------+-------------------+---------------+--------+----------+-------------+-----------+------------+
| id | name                           | contact_id | financial_account_type_id | accounting_code | account_type_code | description                                                           | parent_id | is_header_account | is_deductible | is_tax | tax_rate | is_reserved | is_active | is_default |
+----+--------------------------------+------------+---------------------------+-----------------+-------------------+-----------------------------------------------------------------------+-----------+-------------------+---------------+--------+----------+-------------+-----------+------------+
+----+--------------------------------+------------+---------------------------+-----------------+-------------------+-----------------------------------------------------------------------+-----------+-------------------+---------------+--------+----------+-------------+-----------+------------+
|  1 | Donation                       |          1 |                         3 | 4200            | INC               | Default account for donations                                         |      NULL |                 0 |             1 |      0 |     NULL |           0 |         1 |          1 |
|  6 | Deposit Bank Account           |          1 |                         1 | 1100            | BANK              | All manually recorded cash and cheques go to this account             |      NULL |                 0 |             0 |      0 |     NULL |           0 |         1 |          1 |
```

**Comment by seamuslee001** [comment]
Running the booking report on dmaster it shows the following
booking_report_current_demo

On my local with the new demo data

booking_report_new

**Comment by seamuslee001** [comment]
@eileenmcnaughton do the screenshots help here?

**Comment by eileenmcnaughton** [comment]
Yes - that is clear in the screen shots. I just created a new campaign donation on a site and the debit bank account shows as Deposit Bank account - so this is consistent with that

**Pull request merged**
