### PR TITLE
Add commenting to explain +1/-1 days for membership dates calc

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Pulled out from CRM-21682.  This adds two lines of comments to make the code easier to understand.

@seamuslee001 Happy to merge?

---

 * [CRM-21682: Automatic membership renewal fixes](https://issues.civicrm.org/jira/browse/CRM-21682)

### CODE REVIEW

**Comment by mattwire** [comment]
Jenkins test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 this one just needs you to confirm

**Comment by seamuslee001** [comment]
Comment makes sense merging

**Pull request merged**
