### PR TITLE
CRM-20781: Truncate long text in mail listing

### PR DESCRIPTION
**Pull request by monishdeb**
* [CRM-20781: Truncate long text in mail listing ](https://issues.civicrm.org/jira/browse/CRM-20781)

### CODE REVIEW

**Comment by monishdeb** [comment]
Before : 
image

After :
image

**Comment by monishdeb** [comment]
@lcdservices is max length 30 would be enough or should I make it 20?

**Comment by monishdeb** [comment]
Jenkin test this please

**Comment by lcdservices** [comment]
I think 20. Truncating at 30 won't make enough of a difference. also, can the full value be added as a title tag so it can be visible on hover?

**Comment by monishdeb** [comment]
@lcdservices done :) 

image

**Comment by lcdservices** [comment]
looks good. working as expected.

**Comment by monishdeb** [comment]
Cool

**Comment by eileenmcnaughton** [comment]
The scope of this PR is very narrow so taking @lcdservices comments as review

**Pull request merged**
