### PR TITLE
dev/core#3682 Add support for a domain.site_header token in our message templates, mechanism to support others

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Add support for a domain.site_header token in our message templates, mechanism to support others

Before
----------------------------------------
Most message template customisations are only customised to add branding - which is a lot of overhead to add a logo

After
----------------------------------------
This adds support for `{domain.token_site_header}` specifically and by the same mechanism any other html snippet using `{domain.token_xx}` where the token html is stored as a `MessageComponent`

The new token is added to the message templates & on new installs it will add a row like `<tr></tr>` to help in indicate it is expected to be a row

Example usage is
image

image

There is a link to edit it at the bottom of the domain contact form

image

Which goes to the relevant message template
image

Technical Details
----------------------------------------
We have talked a LOT about adding this feature & it has always gotten bogged down in scope creep & bike-shedding.

This PR represents the simplest option we have discussed - notably it does not include

1) the ability to recursively use these tokens
2) any significant feature re-write
3) a lot of help to users to adopt this new functionality - for existing sites this would be pretty much invisible at the moment and for new sites it is pretty discrete. I feel like there are various ways to tackle that through documentation, system checks, better links etc but I'm not looking to leave that to others to follow up with - my goal here is to break the deadlock that has held us back from having this functionality in any form despite years of discussion

Comments
----------------------------------------

### CODE REVIEW

**Comment by twomice** [comment]
@eileenmcnaughton Looks like this requires CiviMail to be enabled, without which one can't access "Headers, Footers and Automated Messages", and (more surprisingly) one gets a fatal error when trying to edit a Message Template (e.g. this error when opening /civicrm/admin/messageTemplates/add?action=update&id=9&reset=1, for "Contributions - Invoice" template): 

`Error: Class "Civi\Api4\MailingComponent" not found in CRM_Core_DomainTokens->getDomainTokens() (line 64 of /home/jenkins/bknix-dfl/build/core-30441-4m11l/web/sites/all/modules/civicrm/CRM/Core/DomainTokens.php).`

I'm guessing that "CiviMail is now a requiured extension" wasn't a position you intended to adopt, but this PR would seem to make it so.

**Comment by twomice** [comment]
As discussed, I'm gonna work on something here at the sprint, see if I can get this going as a new entity instead of depending on Mailing Components.

**Comment by twomice** [comment]
See #30451.

**Comment by eileenmcnaughton** [comment]
closing in favour of #30451

**Pull request closed without merging**
