### PR TITLE
CRM-19735 - allow contact's second membership to inherit.

### PR DESCRIPTION
**Pull request by davejenx**
* [CRM-19735: Contact's second membership fails to inherit](https://issues.civicrm.org/jira/browse/CRM-19735)

### CODE REVIEW

**Comment by KarinG** [comment]
We've had this patch in our 4.6  repo for over a week now and a couple of dozen family Memberships later I'm convinced this is doing a better job at inheriting Membership than current core 4.6.x - I've not had to 'fix' anything - to properly inherit since. Let's get it in!

**Comment by KarinG** [comment]
@jackrabbithanna - pinging you in - this is a small 4.6 only fix -> [the issue does not exist in 4.7 - because of other larger refactoring that has taken place there]

**Comment by davejenx** [comment]
Turns out this issue does occur in 4.7 but only for back end price sets - see https://issues.civicrm.org/jira/browse/CRM-20955 and #10745 .

**Comment by KarinG** [comment]
Ah - thanks for the heads up @davejenx - your 4.6 patch has been working great. Will take a look at #10745

**Comment by davejenx** [comment]
@KarinG Glad this patch has been helpful.
See also https://issues.civicrm.org/jira/browse/CRM-20966 and #10759 which occurs in a similar scenario.

**Comment by davejenx** [comment]
Note that this issue masks [Contribution deleted when relationship deleted, incorrect line items & membership_payments for second inherited membership created in back end via price set](https://issues.civicrm.org/jira/browse/CRM-20966) so fixing this issue, allowing inheritance to work, paves the way for that issue to occur. I've submitted PRs #10759 (4.7) & #10760 (4.6) for that.

**Pull request merged**
