### PR TITLE
Remove reference to CiviAuction

### PR DESCRIPTION
**Pull request by colemanw**
Before
----------------------------------------
:hankey: LOL :8ball: IDK :shrug: 

After
----------------------------------------
:magic_wand: :cloud:

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
hmm

**Comment by colemanw** [comment]
Maybe someone was trying to build an open-source Ebay?

**Comment by seamuslee001** [comment]
Going once, Going Twice ..........

**Comment by seamuslee001** [comment]
@joemurray was this one of your bright ideas?

**Comment by eileenmcnaughton** [comment]
ohh - @demeritcowboy as the reiging champion of clever PR comments you might have a challenge to beat ^^

**Comment by demeritcowboy** [comment]
Maybe somebody said "we need to be able to add _option_ items" and it got misheard.

**Comment by demeritcowboy** [comment]
But my vote is for "Going once, Going Twice"

Anyway looks like https://github.com/civicrm/civicrm-svn/commit/57131792a6304488bd27616f7f9897d684166d7d

and

https://issues.civicrm.org/jira/browse/CRM-15918

**Comment by eileenmcnaughton** [comment]
lol - well I'm glad I've been consistent on it...

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
Going... going... gone.

**Pull request merged**
