### PR TITLE
Add in Wrapper template around DatePickerRange template to have bette…

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
This adds in a wrapper template around the DatePickerRange template to better style on search forms 

Before
----------------------------------------
activity_before

After
----------------------------------------
activity_after

Note this is after applying #14214

ping @jitendrapurohit @eileenmcnaughton @demeritcowboy

### CODE REVIEW

**Comment by demeritcowboy** [comment]
I maybe interpreted the original comment on 14214 differently. While this PR doesn't cause a problem, the new wrapper is now

(a) tied to tables
(b) tied to a 3-column table
(c) tied to a first column with colspan="2"

So I interpreted it more like the wrapper would be

```
<td colspan="$colspan" class="$datePickerRangeRowClass">
    {include file="CRM/Core/DatePickerRange.tpl" fieldName=$fieldName}
</td>
```

Maybe I misunderstood the comment, in which case just ignore me.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy yes the wrapper is tied to a particular layout but it's also just a small shortcut / stdisation. I think we know we have a bunch of search screens that would use it - so it's worth having but I think it's easier for other screens to bypass the wrapper or have a more appropriate wrapper than to make it super generic.

Having said that your version makes sense but I think we should have a default of 2 for the colspan - ie add in an else

**Comment by demeritcowboy** [comment]
Sounds good. Thanks. @seamuslee001 that's what you get for pinging me hehe. I don't really have any stake in this I do all my searches by converting to hexadecimal and then opening the mysql ibdata file in vim...

**Comment by demeritcowboy** [comment]
Oh, no I meant the wrapper is just one td, because now it would still be tied to minimum 2 tds.

**Comment by seamuslee001** [comment]
ok sorted now @demeritcowboy

**Comment by demeritcowboy** [comment]
Cool. Thanks!

**Comment by jitendrapurohit** [comment]
Tested the final PR. The display of date input fields looks fine now. Thanks @seamuslee001 

Find Activities -

image

Advanced Search -

image

Contact Summary Page -> Activities Tab -

image


which I think is also fine?

**Comment by eileenmcnaughton** [comment]
definite improvement - let's merge & also the select 2 one - do people think we should port to 5.13? @demeritcowboy @seamuslee001 @jitendrapurohit

**Pull request merged**
