### PR TITLE
Run tests on Smarty4 instead of 3

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Run tests on Smarty4 instead of 3

Before
----------------------------------------
We finally got them onto v3

After
----------------------------------------
We push on to v4

Technical Details
----------------------------------------
From my digging /testing  there are no issues in Smarty4 that we have not already solved for v3 so I'm expecting this to pass now the packages patch is merged & then we can switch the 'encouraged version' from v3 to v4 & basically let Smarty rest there for a few months

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
As expected - just need to register a couple of plugins

CRM_Activity_Form_ActivityTest::testInboundEmailDisplaysWithLineBreaks
Using php-function "json_encode" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
This looks good @eileenmcnaughton - giving `merge-ready` in case you wanted to wait till after `5.71` branch.

**Comment by eileenmcnaughton** [comment]
nah - I think we should got for it now - it's a bit stricter but otherwise similar

**Pull request merged**
