### PR TITLE
Bug Fix for Incorrect Search Builder for activity

### PR DESCRIPTION
**Pull request by sujit-baniya**
Bug Fix https://issues.civicrm.org/jira/browse/CRM-17571
Cannot search for Activity type and status in Search Builder (it translates values incorrectly)

### CODE REVIEW

**Comment by colemanw** [comment]
jenkins, add to whitelist

**Comment by colemanw** [comment]
@itsursujit clicking on the test failures link leads to: https://test.civicrm.org/job/CiviCRM-Core-PR/8090/checkstyleResult/new/
Click the "details" tab to see what needs fixing with the code style (mostly whitespace issues)

**Comment by monishdeb** [comment]
In my opinion I think the fix need to be done in Search builder as the drop down which populates against activity_status is in array('value' => 'label') format whereas it should be in array('label' => 'label') format (as activity_status is of type string and its the array key(s) which we get eventually in as in $value) because changing the column name due to incorrect value will also affect Activity.Get api. Also check my comment in https://github.com/civicrm/civicrm-core/pull/7835

**Comment by monishdeb** [comment]
Closing in favour of #7913

**Pull request closed without merging**
