### PR TITLE
dev/core#2486 - Use read-only permissions for FinancialItem API

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Add permissions for financial_item entity

Before
----------------------------------------
No permission declared for financial_item

After
----------------------------------------
Financial Item got permissions, and prevent create/update action. 
Screenshot 2021-06-04 at 12 08 19 PM

Comments
----------------------------------------

This is a follow-up to #20433.

ping @colemanw @eileenmcnaughton @totten

### CODE REVIEW

**Comment by colemanw** [comment]
So FinancialItems are never allowed to be created or updated?

**Comment by monishdeb** [comment]
> So FinancialItems are never allowed to be created or updated?

@colemanw not entirely true. Theres a discussion in MM api channel [here](https://chat.civicrm.org/civicrm/pl/xz4nc5eo6f813p8wwaux8obgpa) where we decided to make the FinancialItem API readonly, because this an entity which must add additional entries as in entity_financial_trxn, FI.create needs additional field like FinancialTrxn.id etc. And there is a possibility that it might messup the financial entries and thus the financial reports esp bookkeeping report. The very concern stems up with the fact that defaulting the FinancialItem.entity_table = civicrm_line_item is not enough, there are other factors tied up with FinancialItem entity. So its better for now to make it readonly for API4 and rely on Order w/o Payment API to create backoffice/live donations.

**Comment by totten** [comment]
(For posterity: this PR+discussion is an offshoot from https://chat.civicrm.org/civicrm/pl/ey1myeenuj813qcxoi8hjwqhdh)

@colemanw Correct. I understand these to be special-purpose logging-tables.  Here's a description of the financial entities from @JoeMurray: https://civicrm.stackexchange.com/questions/28197/what-is-a-line-item-and-what-is-a-financial-item-and-how-are-those-two-linked-t with a notable excerpt:

> An important principle of accounting is that books should be auditable. One part of that is to retain records about all of the changes that have been made on items. So if a purchase is made with pay later selected, and two partial payments are made, the number of things purchased is changed, a refund is made, etc., then all of these are tracked in the financial tables in CiviCRM. Entries in civicrm_financial_item and civicrm_financial_trxn tables are intended to never be edited or deleted.

**Comment by eileenmcnaughton** [comment]
I'm fine with this - but I would note that we call the apiv3 version of this api from internal code -  we have traditionally encouraged api use in internal code for readability & consistency reasons

**Comment by totten** [comment]
@eileenmcnaughton Yeah, it seems to me that (in this approach) you should be able to call APIv4 `FinancialItem::create()` internally as well -- just pass `checkPermissions=>FALSE`. A purer approach might remove the `FinancialItem::create()` and `FinancialItem::update()` API implementations completely, which would make it impossible. Here, it's more like, "This can only be called internally."

**Comment by eileenmcnaughton** [comment]
@totten OK that's great - ie we mostly use checkPermissions = FALSE once we are deep in the BAO

**Comment by eileenmcnaughton** [comment]
@totten I don't have any concerns about this based on the above - go ahead & merge if this makes sense to you

**Comment by eileenmcnaughton** [comment]
@totten I don't have any concerns about this based on the above - go ahead & merge if this makes sense to you

**Comment by totten** [comment]
`r-run`: I used these commands (before and after the patch):

```bash
cv ev -U admin 'civicrm_api4("FinancialItem","create",["checkPermissions"=>TRUE]);'
cv ev -U admin 'civicrm_api4("FinancialItem","create",["checkPermissions"=>FALSE]);'
```

As expected, the patch introduces an authorization-failure if you enable permissions -- and it still allows the call if you skip permissions.

Merging.

**Comment by monishdeb** [comment]
Thanks @totten for merging this. 

@eileenmcnaughton should make similar change to LineItem and EntityFinancialTrxn ?

**Comment by eileenmcnaughton** [comment]
@monishdeb yeah - probably - I think there might be others too

**Pull request merged**
