### PR TITLE
Dev/Core#120 Advanced Search - Contacts throws Fata Error v 5.1.1

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
This is f/u PR of https://github.com/civicrm/civicrm-core/pull/12064 and https://github.com/civicrm/civicrm-core/pull/12043 which is missed on v5.1.1 and caused a regression due after merging https://github.com/civicrm/civicrm-core/pull/12074 https://github.com/civicrm/civicrm-core/pull/11996 against 5.1 which depends on those two fn.

### CODE REVIEW

**Comment by monishdeb** [comment]
ping @seamuslee001 @kcristiano @eileenmcnaughton

**Comment by kcristiano** [comment]
I have tested this on Drupal 7 and WP and this fixes the stated issue.

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by eileenmcnaughton** [comment]
Test fails are fine - we know 5.1 can't pass on these tests

**Comment by seamuslee001** [comment]
@eileenmcnaughton can you also backport your report pager fix then as monish has changed CRM/Report/Form.php here

**Pull request merged**
