### PR TITLE
distmaker - Stop trying to bundle SQL files

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

SQL schema should generally be created on-the-fly using `schema/*.php` -- making the `*.mysql` files obsolete.

(Follow-up to 9d4682697bb93c880a513e5e1cbfe596697ba11d from #30022.)

Before
----------------------------------------

Distmaker will try to include pre-generated SQL files.

However, depending on how `distmaker` is run, you may not have any SQL files... because  9d4682697bb93c880a513e5e1cbfe596697ba11d stopped `distmaker` from trying to make its own copies.

After
----------------------------------------

Distmaker doesn't try to include these SQL files.

Comments
----------------------------------------

* I have not tested the resulting zip/tar files. That seems like the important thing to do...
* Generally, my impression is that we have two main areas the SQL files might still be used:
    * In CI/civibuild, the Civi-WP tests use them. (*Should non-issue after [buildkit#854](https://github.com/civicrm/civicrm-buildkit/pull/854)*) But they should be generated on-the-fly for the active branch. We don't need them in tarballs. 
    * ~~In Drush-Backdrop, it might still use them.~~ (*Should be non-issue after [civicrm-backdrop#182](https://github.com/civicrm/civicrm-backdrop/pull/182)*)

### CODE REVIEW

**Comment by kcristiano** [comment]
Added patch to master and ran distmaker.  Files build successfully.  I will test install.

**Comment by kcristiano** [comment]
WP installs fine for master.  @totten let me know if you need testing on other CMS

**Comment by seamuslee001** [comment]
@totten does this affect the l10n sql files that might need to be generated? also how does this affect the "install with sample data option" on say WP?

**Comment by totten** [comment]
> (@seamuslee001) does this affect the l10n sql files that might need to be generated? also how does this affect the "install with sample data option" on say WP?

* 🟢  For normal l10n installations, I think we're OK. The SQL should be generated+translated on-the-fly (based on `*.mo` data).
* 🔴  For sample data, good catch -- the current commit breaks that. (Confirmed by spot-checking autobuild: `civicrm-5.78.alpha1-drupal-202408200146.tar.gz` doesn't have `civicrm_generated.mysql`.) So this needs revision.

**Comment by totten** [comment]
I've done a little audit to see which of these files are actually used...

```
civicrm_case_sql.mysql                  Unused AFAICS
civicrm_demo_processor.mysql            Unused AFAICS
civicrm_generated_report.mysql          Unused AFAICS... and empty
case_sample.mysql                       Unused AFAICS

civicrm_generated.mysql                 New+old installer; drush-bd; setup.sh; regen.sh; civibuild (old path)
civicrm_devel_config.mysql              regen.sh
civicrm_dummy_processor.mysql           regen.sh
civicrm_sample_custom_data.mysql        regen.sh
civicrm_sample.mysql                    regen.sh

civicrm_acl*.mysql                      Old installer; drush-bd; drush-d8
civicrm_data*.mysql                     Old installer; drush-bd; drush-d8; setup.sh; regen.sh; civibuild (old path)
civicrm.mysql                           Old installer; drush-bd; drush-d8; setup.sh; regen.sh; civibuild (old path)

civicrm_navigation.mysql                `multisite` ext

civicrm_drop.mysql                      CRM_Core_DAO::dropAllTables
                                        (Various uninstall procedures)
```

So (for status quo) it's also important to keep `civicrm_navigation.mysql` and `civicrm_drop.mysql` in the tarballs.

**Comment by eileenmcnaughton** [comment]
Merge-ready - pending other merges

**Comment by totten** [comment]
In another [discussion](https://github.com/civicrm/civicrm-core/pull/30946#issuecomment-2307389774), @kcristiano commented on trying to run `distmaker` with latest revision of this PR -- and having trouble. 

The fundamental question at play: ___Does `GenCode` provide SQL files that we need for `distmaker`?___ 

* At the time of 5.76.alpha (9d4682697bb93c880a513e5e1cbfe596697ba11d), we thought the answer was "No".
    * (*And in fairness, the large majority of SQL files aren't needed.*)
* When Kevin runs `distmaker` on 5.76+, it fails... and it should fail... because our answer was wrong.
    * (*The problem has been asymptomatic for regular autobuilds... because the autobuilder still runs `GenCode`... just by different means. To see a problem, you have to make your own clean environment and run `distmaker.sh` directly.*)
* Specifically, GenCode provides `civicrm_navigation.mysql`  (*used by multidomain deployers*) and `civicrm_drop.mysql` (*used by uninstaller on D7/BD/J*).
* This PR has had two revisions, which play out a bit differently:
    * The original 3db202d8e014b4b8179e99424ff3240fcbbc1bab fixes the failure on manual runs of `distmaker` (e.g. for Kevin) -- but it doesn't lead to well-formed tarballs, because they're missing files that are being used elsewhere.
    * The newer ed65e543c9a551e131a1b8eca5ae22972e7d0b29 produces well-formed tarballs in CI -- but it doesn't fix the manual `distmaker`.

Some possible resolutions are:

1. Commit `civicrm_drop.mysql` and `civicrm_navigation.mysql` to `git` (*as with `civicrm_generated.mysql`*). Then `GenCode` is optional. (*But I might be concerned about the files getting stale...*)
2. Restore the `GenCode` step of `distmaker` (*mostly reverting 9d4682697bb93c880a513e5e1cbfe596697ba11d*). Then `GenCode` is automatic (like it used to be).
3. Update the various dependencies that consume `civicrm_drop.mysql` and `civicrm_navigation.mysql` so they can be omitted from the tarballs. Then `GenCode` really isn't necessary.

I'm leaning toward the second as the near-term fix -- but also +1 for a long-term fix  to make the files unnecessary.

**Comment by totten** [comment]
@kcristiano Added a commit. I'd expect it to work better for you now.

**Pull request merged**
