### PR TITLE
CRM-21407 - Fix ISO compliance for German counties

### PR DESCRIPTION
**Pull request by tschuettler**
Overview
----------------------------------------
Fix spelling and abbriviation for German counties.

Before
----------------------------------------
Not ISO3166-2 compliant

After
----------------------------------------
ISO3166-2 compliant

Comments
----------------------------------------
I used target version 4.7.29. Can be modified if required.

---

 * [CRM-21407: ISO compliance for German counties](https://issues.civicrm.org/jira/browse/CRM-21407)

### CODE REVIEW

**Comment by totten** [comment]
(*CiviCRM Review Template WORD-1.0*)



 * ([`r-jira`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-jira)) __Pass__
 * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __Pass__
 * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __Pass__
 * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __Pass__
 * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __Pass__
 * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __Untested__
 * ([`r-users`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-users)) __Pass__
* ([`r-technical`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-technical)) __Undecided__

For `r-technical`, I'm a little uncertain.
 * Suppose somebody has a workflow where they periodically import data from another service (via GUI or API or somesuch)...
 * Maybe... some folks have coded the import to match the current abbreviations (eg with `BR` instead of `BE`). Then upgrading would break their routine?
 * Maybe... *everyone* in Germany knows that it's `BE`, and this hasn't really come up, or the system is silently failing in ways that people don't recognize.
 * Maybe... the abbreviation has actually changed historically. (Ex: In the US, California is conventionally "CA", but "Cal" or "Calif" are historically valid.) This really requires a bit more cultural knowledge.

Any opinions @tschuettler @systopia. Proceed as-is? Add a note to make this a bit more visible to upgraders?

**Comment by seamuslee001** [comment]
@totten its probably worthwhile noting that i believe we have been aiming to be consistent with `ISO3166-2` I agree that it might have caused some issues on import but I think its better to keep the standard. The only improvement could be a pre/post upgrade message or similar but also i would have thought that on the Import you would use the full name not the abbreviation.  BE certainly is correct as per https://en.wikipedia.org/wiki/ISO_3166-2:DE also ping @mlutfy for thoughts

**Comment by mlutfy** [comment]
If we get a few reactions from people in Germany, I would be OK with merging this. I suspect it simply went unnoticed for many years.

I tried finding which convention used "BR", but couldn't find any. If people noticed the error but did not report it, it's hard to find sympathy about breaking their workflow.

**Comment by systopia** [comment]
> If we get a few reactions from people in Germany, I would be OK with merging this. I suspect it simply went unnoticed for many years.

Thanks @mlutfy, I'd also agree with the merge. 

And since @totten made a good point about people currently using ``BR``, I'll also send an email out to the German mailing list just in case.

**Comment by tschuettler** [comment]
To make matters worse `BR` was used in the draft `ISO/DIS 3166-2`, but it was for the county `Brandenburg`: http://www.statoids.com/ude.html

@systopia Thanks for writing the mail.

**Pull request merged**
