### PR TITLE
[REF][PHP8.2] Fix creation of dynamic properties in Payflow Pro exten…

### PR DESCRIPTION
**Pull request by seamuslee001**
…sion

Overview
----------------------------------------
Similar to #25353 but for the Payflow Pro extension

Before
----------------------------------------
Tests fail on PHP8.2

After
----------------------------------------
Tests pass on PHP8.2

ping @demeritcowboy @eileenmcnaughton @braders

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Same as Elavon - seems safe enough although I'd rather figure out how to make these extensions non-php8.2 compatible

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Test fails unrelated

**Pull request merged**
