### PR TITLE
CRM-17869 - Revert custom field date search refactoring to support relative dates

### PR DESCRIPTION
**Pull request by colemanw**
- [CRM-17869: Custom field relative date filter searching removed in date picker tidy up](https://issues.civicrm.org/jira/browse/CRM-17869)

### CODE REVIEW

**Comment by monishdeb** [comment]
Great work! Happy to test this improvement when its ready :)

**Comment by colemanw** [comment]
@monishdeb it's ready for review. Thanks.

**Comment by monishdeb** [comment]
@colemanw tested on each component's Search form, working like a charm. However I encountered a issue with saved date range criteria of a smart group. Steps to replicate -
1. Selected custom date field of range - 1st Oct to 31st Oct on Advance Search
2. Created smart group on above date range criteria. 
3. On edit Smart group criteria form, the date range widget is broken 
image

And these are default values in ISO format 
```
...
    [custom_8_to] => 2016-10-31 23:59:59
    [custom_8_from] => 2016-10-01 0:00:00
...
```
 As per my earlier change [here](https://github.com/civicrm/civicrm-core/blob/master/CRM/Contact/BAO/SavedSearch.php#L436). Is this the expected format ?

**Comment by monishdeb** [comment]
@colemanw this is my PR https://github.com/civicrm/civicrm-core/pull/9334 on top of your patch and its working fine 
image

**Pull request merged**
