### PR TITLE
Add pseudoconstant for Relationship.relationship_type_id

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Updates the relationship schema to add a pseudoconstant to the `relationship_type_id` field.

Before
----------------------------------------
No pseudoconstant declared, but APIv3 would return an option list for the field (but in a nonstandard format).

After
----------------------------------------
Pseudoconstant declared. APIv3 and APIv4 return option list in standard format, unless legacy `"is_form"` param is set.

Technical Details
----------------------------------------
This adds basic pseudoconstant support for the field using `name_a_b` and `label_a_b` (it does not support other properties like `name_b_a`)

For legacy purposes it preserves the work done in https://github.com/civicrm/civicrm-core/pull/11853 to return a list like `[1_a_b => Child of, 1_b_a => Parent of]` if the `"is_form"` flag is set.
This was very nonstandard but is used to support in-place editing of the relationship type list on the relationship form.

### CODE REVIEW

**Comment by seamuslee001** [comment]
@colemanw test fails relate

**Comment by eileenmcnaughton** [comment]
Test Result (6 failures / -25)
api_v3_RelationshipTest.testRelationshipCreateWithIncorrectData with data set "APIv4"
api_v3_RelationshipTest.testGetTypeOperators with data set "APIv4"
api_v3_RelationshipTest.testGetRelationshipByTypeDAO with data set "APIv3"
api_v3_RelationshipTest.testGetRelationshipByTypeArrayDAO with data set "APIv4"
api_v3_RelationshipTest.testGetRelationshipByTypeReciprocal
api.v4.Entity.ConformanceTest.testConformance with data set "Relationship"

**Comment by eileenmcnaughton** [comment]
We discussed this & code approach seems OK - I'm going to give it a r-run

**Comment by eileenmcnaughton** [comment]
OK - this seems to work the same - @colemanw explained that for apiv3 it will be possible to pass the name_a value for the relationship - whereas the v4 api uses either name_a or name_b

**Comment by colemanw** [comment]
@eileenmcnaughton corection - both api versions will only use `name_a_b` and `label_a_b` not the inverse. But api3 still accepts the oddball `is_form` for the sake of #11853

**Pull request merged**
