### PR TITLE
Make clearMessages() clear all (not just one) message per default.

### PR DESCRIPTION
**Pull request by xurizaemon**
Make clearMessages() clear all (not just one) message per default.
Also minor typo fix in exception message.

CRM-19726

---

 * [CRM-19726: CiviMailUtils::clearMessages\(\) should clear all messages by default](https://issues.civicrm.org/jira/browse/CRM-19726)

### CODE REVIEW

**Comment by xurizaemon** [comment]
Looks like this has upset the AuthorizeNet IPN test. Will check into that.

**Comment by xurizaemon** [comment]
jenkins, test this please

**Comment by seamuslee001** [comment]
@xurizaemon pls rebase this

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by eileenmcnaughton** [comment]
Patch is not applying. Change makes sense but @xurizaemon can you rebase & squash to cheer up jenkins?

**Comment by seamuslee001** [comment]
Jenkins test this please

**Comment by eileenmcnaughton** [comment]
stil not applying - might need to replace this pr

**Comment by xurizaemon** [comment]
closing in favour of #10669 thanks @seamuslee001

**Pull request closed without merging**
