### PR TITLE
[NFC] CRM-19033 improve standardisation of tests

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
- [CRM-19033: Improve standardisation of test classes by removing the duplicate functions](https://issues.civicrm.org/jira/browse/CRM-19033)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
why is this running but no links?

https://test.civicrm.org/job/CiviCRM-Core-PR/10410/consoleFull

**Comment by eileenmcnaughton** [comment]
@totten can you help me to understand if this is safe to merge...

1) changes are restricted to the test suite
2) the test appears to pass https://test.civicrm.org/job/CiviCRM-Core-PR/10410/consoleFull

BUT 

3) no matter how many times I convince jenkins to test it I never get the result back on github & the orange circle never becomes a green flag

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
OK - that started. Self-setting this to merge on pass as change is so trivlal & only affects one instance of passing a null array & tests. nfc

If I can get that through will attempt to re-push some more of it

**Comment by totten** [comment]
Sometime (maybe a week ago) we had a half-day where `test-ubu1204-5` was disconnected from Jenkins, which caused a backlog. Maybe that was the issue?

Next up: standardization of spelling ;)

**Comment by eileenmcnaughton** [comment]
well even today it didn't seem to work - have been dividing & conquering to try to get it through

**Pull request merged**
