### PR TITLE
Standardise fee_label in event workflow messages

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
We already fixed it to the token in
the online template so make offline & test ones match

https://github.com/civicrm/civicrm-core/commit/e90b263a9ccd7c8106c98f5f7f82d4b267820f43#diff-2652c5ed241e0c2a68dc79d97ce2b6056ad2bc8ce37aee9bce8dd69678a160a8R187

### CODE REVIEW

**Comment by larssandergreen** [comment]
I gave this a try and am not getting anything coming through in any of the templates (with cache clearing).

**Comment by larssandergreen** [comment]
That includes the [previous PR](https://github.com/civicrm/civicrm-core/pull/26574) in 5.65, you can see in the PR after screenshots that the fee_level is missing, so we should probably backport whatever the fix is.

**Comment by eileenmcnaughton** [comment]
Yeah  - I thought event fee was part of ... event. But it isn't - it's participant.fee_label I think...

**Comment by larssandergreen** [comment]
Should work as event.fee_label, it's listed in CRM_Event_Tokens - but it doesn't.

**Comment by eileenmcnaughton** [comment]
@larssandergreen yeah - but did that ever work or was it a mistake

**Comment by larssandergreen** [comment]
It's in the Event API

**Comment by eileenmcnaughton** [comment]
Sorry - yes it is

image

**Comment by larssandergreen** [comment]
It's just not in the list of exposed tokens, I'll put up a PR in a second.

**Comment by larssandergreen** [comment]
This should do it: https://github.com/civicrm/civicrm-core/pull/27372

**Comment by eileenmcnaughton** [comment]
Ok so ^^ is merged through now

**Comment by larssandergreen** [comment]
Yes, this one is good to merge now.

**Pull request merged**
