### PR TITLE
See what tests are checking this

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
_A brief description of the pull request. Keep technical jargon to a minimum. Hyperlink relevant discussions._

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins retest this please

**Comment by eileenmcnaughton** [comment]
Maybe none - they seem unrelated - test this please

**Comment by mattwire** [comment]
@eileenmcnaughton Yes, my conclusion is that it's not being tested. And it's probably wrong since it doesn't correspond with what is documented either - see first bullet here: https://docs.civicrm.org/user/en/latest/membership/renewals/#renewal-concepts

**Comment by eileenmcnaughton** [comment]
@mattwire I admire what you are doing but part of me is trying to run away cos I tried to unravel this one once too....

**Pull request closed without merging**
