### PR TITLE
dev/core#3100 - Remove grant leftovers from core xml. Remove empty grant reports menu.

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/-/issues/3100

Before
----------------------------------------
Confusing empty menu links for Grant Reports.

After
----------------------------------------
Empty menus removed.

If you upgrade, the reports instances are still there but are under Contact Reports (see __footnote__).

If you install civigrant new, the report templates are there, just there are no canned instances for you.

__Footnote__: It puts them under Contacts by itself somehow. Before improving this should decide where these reports should go since the civireport system segregates them by component, but grant is not a component anymore.

This PR removes the empty menus and leftovers from the xml files, so at least makes it a little more consistent, and would need to be done anyway no matter where it's decided to put the grant reports.

Technical Details
----------------------------------------

Comments
----------------------------------------
Note the github diff appears to show the changes around line 578 in civicrm_navigation.tpl weirdly. That's github doing that. It's fine. Really.

Since 5.48 hasn't branched yet have put this directly against 5.47.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
CivicrmUpgradeTest.CivicrmUpgradeTest.5_45_3-setupsh_mysql_bz2
```
In Form.php line 550:
                                                                               
  [CRM_Core_Exception]                                                         
  Malformed upgrade sequence.  The incremental update 5.47.1 exceeds target version 5.47.0                                                                
                                                                              
Exception trace:
  at /home/jenkins/bknix-dfl/build/core-22893-82qnz/web/sites/all/modules/civicrm/CRM/Upgrade/Form.php:550
 CRM_Upgrade_Form::buildQueue() at phar:///home/jenkins/bknix-dfl/bin/cv/src/Command/UpgradeDbCommand.php:112
```

Yes 5.47.1 is greater than 5.47.0. So???

**Comment by demeritcowboy** [comment]
```
api\v4\Entity\SystemTest::testSystemCheck
Failed asserting that actual size 1 matches expected size 2.

/home/jenkins/bknix-dfl/build/core-22893-82z7b/web/sites/all/modules/civicrm/tests/phpunit/api/v4/Entity/SystemTest.php:59
```

???

jenkins retest this please

**Comment by colemanw** [comment]
Yea I don't see how the SystemTest could be related

**Comment by demeritcowboy** [comment]
I'll step-debug when I have a minute but my guess is there's now a mismatch in version numbers causing some system check to get skipped. Or maybe the civicrm_generated file is funny.

**Comment by demeritcowboy** [comment]
It seems both my hunches were right. There is this: https://github.com/civicrm/civicrm-core/blob/f534a70687a896ba5ee0158f085d013aada6b2d2/CRM/Utils/Check/Component/Env.php#L283

which skips the lastCron check which is what that test checks, and then also my civicrm_generated domain table is mismatched with xml\version.

This must have come up before though - writing an upgrade script for a `.1` release while `.0` was the current. Let's see...

**Comment by demeritcowboy** [comment]
Looks like that systemcheck test didn't exist the last time this was done, and then also haha there was an "[unrelated fail](https://github.com/civicrm/civicrm-core/pull/15239#issuecomment-529147125)". And before that it was 4.7!

So more new territory, because this release needs more of that...

**Comment by seamuslee001** [comment]
@demeritcowboy did you consider running the script in `tools/bin/scripts/set-version.php`

**Comment by demeritcowboy** [comment]
Of course not...

**Comment by totten** [comment]
Yup, `set-version` is how it changes all the fiddlybits at once. FWIW, I find it easier to have a separate commit for the `set-version` call (and any other changes get their own commit). This makes it easier to handle merge-conflicts/cherry-picks.

**Comment by totten** [comment]
> (@demeritcowboy) Since 5.48 hasn't branched yet have put this directly against 5.47.

That makes perfect sense. I'm looking to branch 5.48 now, and we're still gonna wait a bit on test-run, so we'll have to adapt a little. If I do branch now, then the process probably looks like this:

1. Branch `5.48` from `master`
2. Finish resolving dev/core#3100 on #22893 / `5.47`
3. Make another PR for `5.48` which just updates `civicrm_navigation.tpl`, `5.47.1.tpl`, and `FiveFortySeven.php`. Omit the `set-version` stuff. (Strictly, you might swithc the steps from `5.47.1` to `5.48.beta{1,2}` steps, but the range of affected sites would be miniscule - considering that `5.48.beta1` doesn't exist yet. As long as we get to that within, say, 12-36hr, we can just leave the steps in `5.47.1`.)
4. For `master`, we'll just merge-forward from `5.48`.

**Comment by colemanw** [comment]
Ok I've pushed up one more change, and given an r-run. Feels complete now.

**Pull request merged**
