### PR TITLE
code/dev/69: Change Approach For Setting state_province_name

### PR DESCRIPTION
**Pull request by vinuvarshith**
Overview
----------------------------------------
This issue is related to this existing issue

https://issues.civicrm.org/jira/browse/CRM-21830

The PR for the above issue is here

https://github.com/civicrm/civicrm-core/pull/11776

Though this fixes the basic issue, it still doesn't work for all fields.

Before
----------------------------------------
If state_province field name is not of the form "state_province-{$billingLocationTypeID}", then state_province_name is empty. Which means field names of form 'billing_state_province-{#}' and 'billing_state_province_id-{#}' results in empty state_province_name when "state_province_name" token is used.

After
----------------------------------------
I have changed the way "state_province_name' is set and this is simple and works for all cases.

https://lab.civicrm.org/dev/core/issues/69

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins ok to test

**Comment by vinuvarshith** [comment]
@eileenmcnaughton I have added a testcase for formatted billing address

**Comment by eileenmcnaughton** [comment]
great!

**Comment by eileenmcnaughton** [comment]
OK - I stepped through this in the test & agree the test covers a range of scenarios and that the code change makes sense. Merging

**Pull request merged**
