### PR TITLE
Follow up on #12611 - adding in three data-integrity assertions.

### PR DESCRIPTION
**Pull request by KarinG**
Overview
----------------------------------------
https://github.com/civicrm/civicrm-core/pull/12611 merged in three assertions (commented out as they failed by $5 for unknown reasons at that time). I committed to getting to the bottom of why the GUI produced $5 different results compared to the phpunit test. 

Before
----------------------------------------
Assertions would fail when commented in

After
----------------------------------------
Assertions now pass when commented in

Technical Details
----------------------------------------
I ran the entire class CRM_Member_Form_MembershipTest - and all tests pass. Letting Jenkins have a go at it next. 

After spending most of today in CRM_Contribute_Form_Contribution submit - it finally dawned on me that the phpunit tests simulate an admin created Price Set -> so is_quick_config must be set to => 0. If it is not set to => 0 then transact essentially creates the civicrm_line_item from the Contribution data and that's off by $5 (= tax_amount).

**Todo next:** I will commit to try add a similar phpunit test for Edits on Participant registrations with LineItems.

**Todo longer term:** CRM_Contribute_Form_Contribution submit is a very scary place... having more tests like the ones added here - may allow some much needed refactoring in future.

### CODE REVIEW

**Comment by KarinG** [comment]
Pinging in those that commented on https://github.com/civicrm/civicrm-core/pull/12611 - @eileenmcnaughton @mlutfy @JoeMurray

**Comment by KarinG** [comment]
Right - so I did not need to make any edits in `CRM_Contribute_Form_Contribution submit` itself - I ended up fixing how we create the Price Set in that phpunit test that I was looking at (and then I tested all in class `CRM_Member_Form_MembershipTest` - just to ensure I had not accidentally affected any other test that was perhaps using that Price Set).

**Comment by eileenmcnaughton** [comment]
test fail unrelated

**Comment by KarinG** [comment]
Jenkins, test this please

**Pull request merged**
