### PR TITLE
Rename var to make it clear that we skip participant update from event batch

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
It wasn't clear what this variable was doing - renaming it and moving where it is set makes it clear.

Before
----------------------------------------
Unclear

After
----------------------------------------
More clear

Technical Details
----------------------------------------

Comments
----------------------------------------
@eileenmcnaughton More work on repeattransaction

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I think when you look at the code now we should be able to remove this param altogether with a bit more cleanup on the batch class - we can switch to just calling Payment.create from there.

The fact the var looks like it shouldn't exist& is a hack is a good thing IMHO because it just exists for that weird form & we want to get rid of it

**Comment by mattwire** [comment]
@eileenmcnaughton If you can see a way to remove it in the shortish term I'm happy with that. I looked at removing loadRelatedObjects() but realised it still gets used to set a couple of other variables at the moment - one being the "component". This var is related to component.

**Comment by seamuslee001** [comment]
Not sure if test fail relates re-running

CRM_Contact_BAO_RelationshipTest::testSingleMembershipForTwoRelationships
incorrect count returned from Membership getcount
Failed asserting that 0 matches expected 1.

/home/jenkins/bknix-dfl/build/core-18527-8ha99/web/sites/all/modules/civicrm/Civi/Test/Api3TestTrait.php:197
/home/jenkins/bknix-dfl/build/core-18527-8ha99/web/sites/all/modules/civicrm/tests/phpunit/CRM/Contact/BAO/RelationshipTest.php:239
/home/jenkins/bknix-dfl/build/core-18527-8ha99/web/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:226
/home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar:615

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
@mattwire I guess the first thing is to UI test the form & see if it even matters if completeOrder tries again. 

The code only calls completeOrder in a weird use case - ie it needs to be Pending + pay later + have ```    $source = ts('Online Event Registration');```

CRM_Event_Form_Task_BatchTest::testSubmit is the relevant test

**Comment by mattwire** [comment]
test this please

**Comment by mattwire** [comment]
@eileenmcnaughton Tests are now passing on this (they weren't related). I couldn't immediately see another way to remove this parameter yet (without diving deep into the event batch code which I don't want to do). This cleanup helps me understand much better what's going on in `completeOrder()` in the meantime and will allow me to continue with cleanup along the complete/repeattransaction path.

Please feel free to merge or close depending on if you can see a different way to achieve that goal.

**Comment by eileenmcnaughton** [comment]
@mattwire so the fugly enotice is the 1.0 version of a deprecation notice & it tells future cleaner uppers
1) that the code is only called from one place
2) it can be removed at will & is absolutely not supported.

I feel like just renaming loses that - but a deprecation notice would capture it

**Pull request closed without merging**
