### PR TITLE
CRM-20442 - Improve user checking for mailing reports

### PR DESCRIPTION
**Pull request by davejenx**
* [CRM-20442](https://issues.civicrm.org/jira/browse/CRM-20442)

### CODE REVIEW

**Comment by PalanteJon** [comment]
Hi @davejenx - does this have a JIRA issue associated with it?

**Comment by seamuslee001** [comment]
@jon yes there is one

**Comment by seamuslee001** [comment]
@totten I have tested and proved it to work am happy with it ;-)

**Comment by totten** [comment]
Nice

**Pull request merged**
