### PR TITLE
[ref] Move copyCustomFields function from Event to Core_DAO for re-usability

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Minor refactor - move function per https://github.com/civicrm/civicrm-core/pull/13470

Before
----------------------------------------
Less readable

After
----------------------------------------
More readable

Technical Details
----------------------------------------
Note this is JUST a file move to keep it reviewable - I think the function should not be static & some genericisation should happen

Comments
----------------------------------------

### CODE REVIEW

**Comment by yashodha** [comment]
@eileenmcnaughton this would break https://github.com/civicrm/civicrm-core/blob/master/CRM/Event/BAO/Event.php#L989 though now that the function has been moved.

**Comment by eileenmcnaughton** [comment]
@yashodha - yeah - I guess it makes sense to make non-static - I just did that

But I realise the copy custom fields shouldn't be needed as it's also in generic. I think what happened is it got fixed in event first in an adhoc way 
https://github.com/eileenmcnaughton/civicrm-core/commit/63500972f0757f8f805bf209d6b4eda7e8405ee1

and then fixed generically in copyGeneric but we still have this adhoc stuff hanging around cos it wasn't done right the first time & now we have to clean up.

However the attempt was in 2016 & we have been raising the bar  - I don't think that PR would have been accepted today without unit tests - https://github.com/civicrm/civicrm-core/pull/9407

**Comment by eileenmcnaughton** [comment]
@yashodha I added a second fix that brings back the genericness

**Comment by mattwire** [comment]
Merging as test to follow in subsequent PR

**Pull request merged**
