### PR TITLE
dev/core#1217 Fix for failure to respect event_id (or any?) criteria …

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Port of https://github.com/civicrm/civicrm-core/pull/16313

Note it didn't apply completely cleanup - I had to tweak. I have not tested on 5.21 at this stage

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton in the formValues that were stored for my busted smart group attempt it stored as `s:8:"event_id";s:3:"3,2"` i'm just wondering should w put any handing into like the query object for this or not. This PR works tested creating a smart group or doing an export (that was an earlier regression so just double checking)

**Comment by eileenmcnaughton** [comment]
@seamuslee001 well - the other regressed 4 months ago I think? So better to fix but if we don't get to it then at least sorting this is worth doing

**Comment by eileenmcnaughton** [comment]
oh - not in the query object though - I'd fix the group in the DB & just handle one thing

**Comment by seamuslee001** [comment]
@eileenmcnaughton do you think we should merge this even if we don't fix the smart groups in the DB or do we have to do both?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 this is worth doing without the other because is means new ones can be created. Both is better but it's a 4 month old regression so less urgent

**Comment by eileenmcnaughton** [comment]
@seamuslee001 note that advanced search works for event smart groups & probably most people use that hence this has not been burning down the house

**Comment by seamuslee001** [comment]
yeh merging just figured need the question answer documented about reasoning

**Comment by eileenmcnaughton** [comment]
It may never have worked

**Pull request merged**
