### PR TITLE
(dev/core#2766) Provide way to distinguish the core and custom fields…

### PR DESCRIPTION
**Pull request by yashodha**
… on _Find and Merge Duplicate Contacts_ page

Overview
----------------------------------------
There is no way to distinguish the core and custom fields on Find and Merge Duplicate Contacts page.
This is particularly confusing as one of the clients had a custom field named email and created the rule using this custom field and every time someone registered an event which was configured with this aforesaid rule it was attributed to a new contact. We should be using _Custom Field: Custom Group_ format to avoid confusion as we do elsewhere in Import mapping screens, etc.

Before
----------------------------------------
before

After
----------------------------------------
after

### CODE REVIEW

**Comment by colemanw** [comment]
I agree this is an improvement.
But most other places in the UI when listing a custom field, the group name comes first, not second.
E.g. from Search Builder:
image

**Comment by yashodha** [comment]
@colemanw That's what I thought it was _Custom Group : Custom Field_. But I looked at the import screen and it was _Custom Field : Custom Group_.

email

Since we are already inconsistent, let me know which one to follow and I will rectify the others as well. Thanks!

**Comment by agileware-justin** [comment]
Related Gitlab, https://lab.civicrm.org/dev/core/-/issues/2766

**Comment by colemanw** [comment]
I think it should be custom group name first, because that keeps them grouped together when sorting fields alphabetically.

**Comment by colemanw** [comment]
Thanks @yashodha can you squash these commits? In the future when modifying a small PR it's easier to `--amend` your previous commit and force-push.

**Comment by eileenmcnaughton** [comment]
I just changed the labels to reflect that it needs a squash - but @yashodha you can self-merge once that is done

**Comment by demeritcowboy** [comment]
@yashodha can you squish?

**Comment by demeritcowboy** [comment]
@yashodha Please SQUISH!

**Comment by colemanw** [comment]
@yashodha I see you closed this and opened #21728. FYI it's usually not necessary to open a new PR, you can just force-push to the same branch and it will update the existing PR.

**Pull request closed without merging**
