### PR TITLE
Capitalise event setting title

### PR DESCRIPTION
**Pull request by christianwach**
Overview
----------------------------------------
Capitalises "show location" setting to be consistent with other settings titles.

Too small a change to warrant an issue on Lab.

Before
----------------------------------------
Setting title is "show location".

After
----------------------------------------
Setting title is "Show Location".

### CODE REVIEW

**Comment by seamuslee001** [comment]
@christianwach can you please edit it here https://github.com/civicrm/civicrm-core/blob/master/xml/schema/Event/Event.xml#L310 and then run `./bin/setup.sh -g` and commit the result

**Comment by demeritcowboy** [comment]
`cd xml; php GenCode.php` is enough to update the DAO from the xml.

**Comment by christianwach** [comment]
@demeritcowboy Thanks for the alternative, however that too craps out:

```
Warning: require_once(HTML/QuickForm/Rule/Email.php): failed to open stream: No such file or directory in /path/to/civicrm-source/git/civicrm-core/CRM/Utils/String.php on line 21

Fatal error: require_once(): Failed opening required 'HTML/QuickForm/Rule/Email.php' (include_path='.:/Usepath/to/civicrm-source/git/civicrm-core:/path/to/civicrm-source/git/civicrm-core/packages:.:../packages:../../civicrm-packages:..') in /path/to/civicrm-source/git/civicrm-core/CRM/Utils/String.php on line 21
```

Any suggestions?

**Comment by christianwach** [comment]
@demeritcowboy Thanks for that. I've force-pushed with the changes in your patch.

Yeah my repo is just a git clone. I haven't had time to set up a proper build environment and every time I do something ends up being a blocker. Hey ho, one day.

**Pull request merged**
