### PR TITLE
[wip] CRM-20524 - Core CiviCRM/Smarty - programmatically add help icons alternative approach

### PR DESCRIPTION
**Pull request by MegaphoneJon**
This places the help icon markup directly into the label.

---

 * [CRM-20524: Programmatically create help icons](https://issues.civicrm.org/jira/browse/CRM-20524)

### CODE REVIEW

**Comment by colemanw** [comment]
@PalanteJon I think the right place to stick it might be `CRM_Core_Form_Renderer::_elementToArray()` if the `CRM_Core_Form::addHelp` method adds an attribute like `crmHelp` then the renderer can read it and adjust the label markup accordingly.

**Comment by eileenmcnaughton** [comment]
I'm going to put [wip] in the title because I think this is pending response to @colemanw's feedback. Please remove when that is no longer the case.

**Comment by colemanw** [comment]
@PalanteJon your thoughts?

**Comment by PalanteJon** [comment]
I'll need to push this off for a couple of weeks @colemanw but will evaluate soon.  I agree the "wip" is correct here.

**Comment by mlutfy** [comment]
@MegaphoneJon Ping? Can we close for now?

**Pull request closed without merging**
