### PR TITLE
PR for CRM-16701: Saved Search API

### PR DESCRIPTION
**Pull request by johanv**
This might be not 100% complete, but it works for the use case 'creating smart groups using the api'. If you apply this patch, you can create e.g. a smart group for all volunteers in the default organization like this:

```
$params = array(
  'form_values' => array(
    // Is volunteer for
    'relation_type_id' => '6_a_b',
    'relation_target_name' => 'Default Organization',
  ),
  'api.Group.create' => array(
    'name' => 'my_smartgroup',
    'title' => 'my smartgroup',
    'description' => 'Volunteers for the default organization',
    'saved_search_id' => '$value.id',
    'is_active' => 1,
    'visibility' => 'User and User Admin Only',
    'is_hidden' => 0,
    'is_reserved' => 0,
  ),
);
civicrm_api3('SavedSearch', 'create', $params);
```

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Re the title failure - once you expose an entity via api the tests enforce the schema has titles for each field (in the xml/schema folder) - it's a bit mean - would be better to enforce when creating a dao - but we don't have the test mechanism for that yet and we also haven't gone through & done all the titles

**Comment by johanv** [comment]
Another problem is that some unit test create some dummy entities. When the saved search tries to compute clauses based on the form values (which are just a dummy string), things go wrong.

**Comment by johanv** [comment]
I think this forum thread is related: http://forum.civicrm.org/index.php?topic=33990.0

**Comment by davecivicrm** [comment]
Jenkins, test this please.

**Pull request merged**
