### PR TITLE
dev/core#1532 - Upgrade message about old civicase activity revisions

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
Followup to https://github.com/civicrm/civicrm-core/pull/25113

Before
----------------------------------------
Activity revisions still filterable in api4/searchkit/etc.

After
----------------------------------------
No longer selectable to be filterable in UI.

Technical Details
----------------------------------------
I also ran into https://lab.civicrm.org/extensions/caseactivityrevisionmigrator/-/issues/4 where the ON DELETE CASCADE is dangerous, so included that here.

Comments
----------------------------------------
I also updated the referenced lab snippet.

Given the timing I may need to rebase/move to beta1.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Comment by demeritcowboy** [comment]
I had added `IF EXISTS` to the sql which works on mariadb but seems it doesn't on mysql. But I only added that because I had been playing around. In real life it should always exist, even if you rerun the upgrade step.

**Comment by demeritcowboy** [comment]
jenkins what are you talking about

```
api\v4\SearchDisplay\SearchRunTest::testContributionCurrency
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'GBP'
+'JPY'

/home/jenkins/bknix-dfl/build/core-25119-3qtv6/web/sites/all/modules/civicrm/ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php:1414
```

retest this please

**Comment by demeritcowboy** [comment]
I this PR is cursed.

```
E2E\Core\AssetBuilderTest::testInvalid
GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 2001 milliseconds with 0 bytes received 
```

jenkins retest this please

**Comment by demeritcowboy** [comment]
Thanks @colemanw 
Deprecation warning: "Thanks" is deprecated. Use "Yeah baby!".

**Comment by seamuslee001** [comment]
Finally @demeritcowboy

**Pull request merged**
