### PR TITLE
CRM-21391 Convert Contact to use core Task class

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Refactor contact task form to use base class

Before
----------------------------------------
localhost_8000_civicrm_contact_search__qf_basic_display true qfkey 1ad04bc45fe854a195f0613c490cb77e_4188 1

After
----------------------------------------
localhost_8000_civicrm_contact_search__qf_basic_display true qfkey 1ad04bc45fe854a195f0613c490cb77e_4188

Technical Details
----------------------------------------
details in #11240

Comments
----------------------------------------
This is a commit from #11240.

In terms of review check that the code was a positive improvement and tested a couple of actions as well as checking the same number of actions were present

---

 * [CRM-21391: Refactor tasks to use a base class](https://issues.civicrm.org/jira/browse/CRM-21391)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I've read through the code & a bunch of similar patches & feel pretty good about it in terms of it being a previously agreed improvement & having checked most of the Constant changes to see if they are consistent.

My one concern is the handing of the Update saved search and my focus on UI testing for this would be to ensure behaviour from 'Manage Groups' / smart group search is correct

**Comment by eileenmcnaughton** [comment]
OK - looks fine from contact search - but from 'Manage Groups' when I click on smart group I ge

screenshot 2018-03-06 00 35 11

**Comment by mattwire** [comment]
@eileenmcnaughton Ok, we're getting into circular PR "hell" here!  PR #11600 has the changes that fix the issue with Manage Groups as it removes optionalTaskTitle in favour of permissionedTaskTitle.  But we can't merge that until this is merged as they now depend on each other.  Most of #11600 is changing hardcoded values to constants and the tasks bit is somewhat tangled up in that so not sure how easy it would be to split out the relevant changes into it's own PR.

**Comment by eileenmcnaughton** [comment]
OK - running this with #11600 both the issue I identified on this PR & the one I identified on that PR are resolved. Since we have just cut an rc this seems like a good time to merge!

**Pull request merged**
