### PR TITLE
[NFC] code formatting

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
IDE code formatting on 2 test classes

Before
----------------------------------------
array()

After
----------------------------------------
[]

Technical Details
----------------------------------------
@colemanw we should do the more thorough format fix too - maybe it's good right after the rc is cut?
Perhaps anytime is good

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins not happy @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
dang

**Comment by eileenmcnaughton** [comment]
I fought jenkins and I won

**Comment by seamuslee001** [comment]
Changes look fine adding MOP

**Comment by eileenmcnaughton** [comment]
unrelated fails

**Pull request merged**
