### PR TITLE
SearchKit - add address proximity (map radius) search

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Allows searching for addresses within a given distance of a location.

image

Notes
---------------------
Update: now works with most mapping providers (originally hardcoded only for Google Maps) via #23646

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
image

**Comment by eileenmcnaughton** [comment]
ok let's merge it - it would be good to test in the rc (I'm fighting geocoders right now) and it shouldn;'t affect existing code

**Comment by demeritcowboy** [comment]
Ok just I had marked it merge-ready to give the [mystery sponsor](https://lab.civicrm.org/dev/core/-/issues/3163#note_71481) time to see if it worked for their use case.

**Comment by eileenmcnaughton** [comment]
Well it can get further fixes if need be

**Comment by awestuk** [comment]
That's us! We will test asap - we need to run an upgrade first, so we're just waiting for the security drop. It looks like just what we're after though.

**Comment by awestuk** [comment]
Upgraded and tested and working well! Does exactly what we wanted. Thank you!

**Pull request merged**
