### PR TITLE
Proposed changes for CRM-16871

### PR DESCRIPTION
**Pull request by bjendres**

### CODE REVIEW

**Comment by colemanw** [comment]
jenkins, add to whitelist

**Comment by davecivicrm** [comment]
Bjorn - can you review the style warnings, correct and update the PR so the main PR test can complete please. Click Details link and then Warnings tab to see the specific issues. Thanks!

**Comment by systopia** [comment]
> Bjorn - can you review the style warnings, correct and update the PR so the main PR test can complete please. Click Details link and then Warnings tab to see the specific issues. Thanks!

@davecivicrm Do you still want me to look into this? I see that you already merged this into ``master``...

**Comment by davecivicrm** [comment]
Bjorn - Not sure what you mean by "already merged in master"?? Is there another pull request for CRM-16871 ?

**Comment by systopia** [comment]
Sorry, I confused it with my other PR (https://github.com/civicrm/civicrm-core/pull/6270 for CRM-16845). I'll have a look.

**Comment by systopia** [comment]
seems to be fine now.

**Pull request merged**
