### PR TITLE
dev/report#59: Address location type search errors when using a search profile

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Steps to replicate the issue:

1. Create a profile for use as a search view.
2. Go to Advanced Search
3. Trigger a search using that profile, and select an address location type.

Before
----------------------------------------
`DB Error: no such field`

After
----------------------------------------
No Error

Ref- https://lab.civicrm.org/dev/report/-/issues/59

ping @eileenmcnaughton @lcdservices @seamuslee001

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Looks like the test needs updating to reflect this change - it handily makes the sql change very clear
```
CRM_Contact_SelectorTest::testSelectorQueryOnNonASCIIlocationType
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'SELECT contact_a.id as contact_id, contact_a.contact_type as `contact_type`, contact_a.contact_sub_type as `contact_sub_type`, contact_a.sort_name as `sort_name`, `Non_ASCII_Location_Type-location_type`.id as `Non_ASCII_Location_Type-location_type_id`, `Non_ASCII_Location_Type-location_type`.name as `Non_ASCII_Location_Type-location_type`, `Non_ASCII_Location_Type-email`.id as `Non_ASCII_Location_Type-email_id`, `Non_ASCII_Location_Type-email`.email as `Non_ASCII_Location_Type-email`'
+'SELECT contact_a.id as contact_id, contact_a.contact_type as `contact_type`, contact_a.contact_sub_type as `contact_sub_type`, contact_a.sort_name as `sort_name`, `Non_ASCII_Location_Type-location_type`.id as `Non_ASCII_Location_Type-location_type_id`, `Non_ASCII_Location_Type-location_type`.name as `Non_ASCII_Location_Type-location_type`, `Non_ASCII_Location_Type-address`.id as `Non_ASCII_Location_Type-address_id`, `Non_ASCII_Location_Type-email`.id as `Non_ASCII_Location_Type-email_id`, `Non_ASCII_Location_Type-email`.email as `Non_ASCII_Location_Type-email`'```

**Comment by seamuslee001** [comment]
@JoeMurray

**Comment by eileenmcnaughton** [comment]
@monishdeb I'm having trouble replicating this - I think the config of the search profile might be part of the replication steps?

**Comment by seamuslee001** [comment]
I was able to replicate this problem using the Search Profile containing the following fields:

1. City - Primary
2. Phone - Phone and Primary
3. State Province field - Primary
4. Address Name - Primary

Then perform a search where you filter by the address location type and it results in a DB error and I confirmed that this fixed it @eileenmcnaughton if you can double check this PR given my replication parts.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 if you feel you have reviewed this go ahead & merge it

**Comment by seamuslee001** [comment]
Merging as per @eileenmcnaughton 's comment

**Pull request merged**
