### PR TITLE
Crm 20376 - Fix field names on PDF/Print vesion of survey report

### PR DESCRIPTION
**Pull request by jmcclelland**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@jmcclelland can you fix this up - it has gone stale. Might be good to squash the commits too

**Comment by eileenmcnaughton** [comment]
Please edit out the WIP from the title when fixed & reviewable

**Comment by jmcclelland** [comment]
Thanks for the review Eileen! I just made the requested changes.

**Comment by eileenmcnaughton** [comment]
OK - I'm happy to largely defer to you on this report- but one thing still bothering me -

$fildCnt

Is that $fieldCount ?

**Comment by jmcclelland** [comment]
Good point - let's clean that up too.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Pull request merged**
