### PR TITLE
fix to CRM-16906

### PR DESCRIPTION
**Pull request by JoeMurray**
- [CRM-16906: Ensure safe chars for Petition cookies](https://issues.civicrm.org/jira/browse/CRM-16906)

### CODE REVIEW

**Comment by davecivicrm** [comment]
Joe - please review the style warnings (https://test.civicrm.org/job/CiviCRM-Core-PR/4473/checkstyleResult/new/) and update the PR so the tests can complete. Thanks!

**Comment by pradpnayak** [comment]
Jenkins, test this please.

**Comment by kurund** [comment]
jenkins, test this please

**Comment by pradpnayak** [comment]
Submitted new PR at https://github.com/civicrm/civicrm-core/pull/6709

**Comment by davecivicrm** [comment]
Closing in favor of https://github.com/civicrm/civicrm-core/pull/6709

**Pull request closed without merging**
