### PR TITLE
Load contribution page if live payment processor is disabled but test is available

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Reviewer's cut on https://github.com/civicrm/civicrm-core/pull/16860

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
Code looks good to me, has anyone `r-run` this yet?

**Comment by eileenmcnaughton** [comment]
It's replacing a  Pr @mattwire did that caused a regression - as demonstrated in the included tests.

**Comment by mattwire** [comment]
Thanks @eileenmcnaughton I've `r-run` and it's working well!

**Pull request merged**
