### PR TITLE
Fixes issue with duplicate is_billing on inline address forms.

### PR DESCRIPTION
**Pull request by VangelisP**
Overview
----------------------------------------
In the case that someone has 2 addresses registered, they can flag both of them as billing location via the inline address editing checkbox which I believe is wrong. This behaviour does not replicate when you edit the contact.
I am assuming that this is not an intended behaviour. Source Issue: https://lab.civicrm.org/dev/core/-/issues/3080

Before
----------------------------------------
No validation takes place when someone checks the "billing location" via the inline address editing which means that a contact can have multiple billing addresses.

After
----------------------------------------
There should be a validation while saving the inline address form to check if the checkbox is already being used in another address ID and if yes, it should not store the checkbox (or unset it).

### CODE REVIEW

**Comment by VangelisP** [comment]
In regards to the failed tests, I can't seem to find any relevance with my code or why my code is causing these errors. If I'm not mistaken, they refer to something else.

**Comment by demeritcowboy** [comment]
At line 452 you are creating a brand new address record - was that intended to be something else?

**Comment by VangelisP** [comment]
> At line 452 you are creating a brand new address record - was that intended to be something else?

Ohhh ... :man_facepalming: I definitely forgot to remove those 4 lines of code from the function that I repurposed!

Sharp eyes @demeritcowboy , I'll issue a fix right now.

**Comment by VangelisP** [comment]
Squashed commits

**Comment by demeritcowboy** [comment]
* General standards
    * [`r-explain`] __PASS__
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__
    * [`r-run`] __PASS__
      * I only ran via the UI. So I'm only putting merge-ready because someone might have some unusual api usage this affects.
      * If you fill out a contribution page, it will overwrite the existing billing address for an existing contact, but this happens before the patch too and is probably already a known thing and maybe even people want that(?). In any case it's no change in how that works.
* Developer standards
    * [`r-tech`] __PASS__
    * [`r-code`] __PASS__
      * It seems a bit complex but I know it's copy/paste from handlePrimary().
    * [`r-maint`] __?__
      * A test would be a nice-to-have. That might also help confirm api usage.
    * [`r-test`] __PASS__

**Comment by jaapjansma** [comment]
@eileenmcnaughton can you merge this?

**Comment by eileenmcnaughton** [comment]
@jaapjansma I did see your last comment but this to my mind absolutely requires a unit test & I can't personally merge it without one. I did merge another one today that had been marked as not requiring a test even though I felt uncomfortable - but this is deep in the BAO layer and we already have tests around the matching is_primary functionality.

I did mentally add it to my 'long-list' of things to do last time as I understand requests to merge things that I can't merge without a test as a request that I write the unit test.

**Comment by jaapjansma** [comment]
@VangelisP are you able to provide a unit test? As per @eileenmcnaughton and @demeritcowboy comment?

**Comment by VangelisP** [comment]
While I haven't written a unit test before, I totally understand you and I am willing to give it a try, heading for a similar test as with `is_primary` on the `AddressTest.php` , am I right?

**Comment by eileenmcnaughton** [comment]
@VangelisP yep!

**Comment by VangelisP** [comment]
Although I am not quite sure why this failed nearly instantly, this is my take on the PHPUnit test with `is_billing`. Let me know if that works for you. 

I tried without the patch and it fails (obviously) and with the patch, it succeeds.

What fails? Assigned into a contact 2 addresses with `is_billing` set to 1, then tried to detect if `is_billing` is detected only once (which is correct).

**Comment by demeritcowboy** [comment]
Thanks for the test. There's fails on all the PRs right now since something is wrong with the server.

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Comment by colemanw** [comment]
Thanks for the fix @VangelisP

**Pull request merged**
