### PR TITLE
dev/core#353 fixed Source contact ID clause

### PR DESCRIPTION
**Pull request by colemanw**
5.5 replacement for https://github.com/civicrm/civicrm-core/pull/12713

See https://lab.civicrm.org/dev/core/issues/353

### CODE REVIEW

**Comment by seamuslee001** [comment]
Adding Merge on pass as this is a reviewer commit and given the testing that happened on the previous PR

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
@seamuslee001 it's hung

**Pull request merged**
