### PR TITLE
CRM-18510 - Fix regression when searching for location types

### PR DESCRIPTION
**Pull request by totten**
- [CRM-18510: Getting "One of parameters (value: `Home-street_address`) is not of the type MysqlColumnName" error when Contact Search is used.](https://issues.civicrm.org/jira/browse/CRM-18510)

### CODE REVIEW

**Comment by totten** [comment]
Testing notes:
1. Ensure that we still satisfy CRM-17983 (e.g. attempt to order on a column with `sleep(1)`).
2. Visit a large number of screens (such as the fine-grained mailing reports, "Activities" tab, "Find Participants", etc) and try sorting the data.

**Comment by totten** [comment]
@mollux, this is the updated PR.

**Comment by totten** [comment]
Discussed a bit with @mollux on MM. We've flogged this a bunch

**Comment by mollux** [comment]
@eileen, i will push the changes to the 4.6 PR, so it has the same fixes

**Pull request merged**
