### PR TITLE
Add APIv4 and pseudoconstants for RelationshipCache

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Followup on the new RelationshipCache entity to add more metadata and an api + unit test.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@colemanw related fail

api\v4\Entity\RelationshipTest::testRelCache
API_Exception: Invalid field 'near_contact_id'

/home/jenkins/bknix-dfl/build/core-17879-579vu/web/sites/all/modules/civicrm/Civi/Api4/Query/Api4SelectQuery.php:474
/home/jenkins/bknix-dfl/build/core-17879-579vu/web/sites/all/modules/civicrm/Civi/Api4/Query/Api4SelectQuery.php:356
/home/jenkins/bknix-dfl/build/core-17879-579vu/web/sites/all/modules/civicrm/Civi/Api4/Query/Api4SelectQuery.php:334
/home/jenkins/bknix-dfl/build/core-17879-579vu/web/sites/all/modules/civicrm/Civi/Api4/Query/Api4SelectQuery.php:321
/home/jenkins/bknix-dfl/build/core-17879-579vu/web/sites/all/modules/civicrm/Civi/Api4/Query/Api4SelectQuery.php:230
/home/jenkins/bknix-dfl/build/core-17879-579vu/web/sites/all/modules/civicrm/Civi/Api4/Query/Api4SelectQuery.php:114
/home/jenkins/bknix-dfl/build/core-17879-579vu/web/sites/all/modules/civicrm/Civi/Api4/Query/Api4SelectQuery.php:129
/home/jenkins/bknix-dfl/build/core-17879-579vu/web/sites/all/modules/civicrm/Civi/Api4/Generic/DAOGetAction.php:86
/home/jenkins/bknix-dfl/build/core-17879-579vu/web/sites/all/modules/civicrm/Civi/Api4/Generic/DAOGetAction.php:74
/home/jenkins/bknix-dfl/build/core-17879-579vu/web/sites/all/modules/civicrm/Civi/Api4/Provider/ActionObjectProvider.php:68
/home/jenkins/bknix-dfl/build/core-17879-579vu/web/sites/all/modules/civicrm/Civi/API/Kernel.php:150
/home/jenkins/bknix-dfl/build/core-17879-579vu/web/sites/all/modules/civicrm/Civi/Api4/Generic/AbstractAction.php:238
/home/jenkins/bknix-dfl/build/core-17879-579vu/web/sites/all/modules/civicrm/tests/phpunit/api/v4/Entity/RelationshipTest.php:46
/home/jenkins/bknix-dfl/extern/phpunit7/phpunit7.phar:615

**Comment by colemanw** [comment]
@eileenmcnaughton @totten this is failing because #17734 didn't get merged :(
Therefore the test db is still `'5.27.alpha1'`, therefore none of the new fields in `civicrm_relationship_cache` are visible to the api.

I could "fix" it in this PR by updating the test db to `5.29`, but this is going to keep happening, and it's going to frustrate people when they can't figure out why tests seem to be failing for no reason.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I think an alternative got merged so hopefully this can pass now

**Pull request merged**
