### PR TITLE
CiviImport - Fix permission checks for search forms

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Alternative to #28259, improves the way search forms are generated

Before
-------
Afform definition is conditional on current user permissions, which is weird. Also causes a bunch of permission error backtraces to fill up the logs due to:

https://github.com/civicrm/civicrm-core/blob/4e21ad6dad80a20624f58355badf12655dc3927e/Civi/API/Kernel.php#L149-L153

After
-------
Afforms are always there, but the forms themselves enforce permission "import contacts".

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

[Test Result](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6578/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/) (48 failures / +48)
[Civi\Authx\AllFlowsTest.testAnonymous](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6578/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testAnonymous/)
[Civi\Authx\AllFlowsTest.testStatelessGuardSiteKey](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6578/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatelessGuardSiteKey/)
[Civi\Authx\AllFlowsTest.testStatefulStatelessOverlap](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6578/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testStatefulStatelessOverlap/)
[Civi\Authx\AllFlowsTest.testIgnoredHeaderAuthorization](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6578/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testIgnoredHeaderAuthorization/)
[Civi\Authx\AllFlowsTest.testIgnoredHeaderAuthorization_anon](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6578/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testIgnoredHeaderAuthorization_anon/)
[Civi\Authx\AllFlowsTest.testMultipleStateless](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6578/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testMultipleStateless/)
[Civi\Authx\AllFlowsTest.testJwtMiddleware](https://test.civicrm.org/job/CiviCRM-Core-Matrix-PR/6578/BKPROF=dfl,SUITES=phpunit-core-exts,label=bknix-tmp/testReport/junit/(root)/Civi_Authx_AllFlowsTest/testJwtMiddleware/)

**Comment by eileenmcnaughton** [comment]
@colemanw it's correct to check the current user - users are not supposed to be able to see each other's imports, unless they have suitable permissions

**Comment by mattwire** [comment]
> @colemanw it's correct to check the current user - users are not supposed to be able to see each other's imports, unless they have suitable permissions

@eileenmcnaughton Does this mean the PR needs changing?

@colemanw Should this still be draft?

**Comment by eileenmcnaughton** [comment]
Closing this & created https://lab.civicrm.org/dev/core/-/issues/4848 to track the issue of too much noise

**Pull request closed without merging**
