### PR TITLE
Move two more functions to financialProcessor

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Move two more functions to financialProcessor

Before
----------------------------------------
Functions are part of the borg

After
----------------------------------------
Moved to the class they interact with

Technical Details
----------------------------------------
Part of preparing for some bug fixes

Comments
----------------------------------------

### CODE REVIEW

**Comment by demeritcowboy** [comment]
test fails don't make sense.
jenkins retest this please

**Comment by eileenmcnaughton** [comment]
@demeritcowboy the test fails seem to affect all PRs now

**Comment by demeritcowboy** [comment]
See https://github.com/civicrm/civicrm-core/pull/22269

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
thanks @demeritcowboy

**Pull request merged**
