### PR TITLE
API Explorer - Fix URL encoding in REST examples

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------
This improves the REST examples generated in "Support => Developer => Api Explorer v3".

Before
----------------------------------------

If you use `Contact`.`get` with `id=1`, it generates a "Rest" URL like this:

```
http://dmaster.bknix:8001/sites/all/modules/civicrm/extern/rest.php
  ?entity=Contact&action=get&api_key=userkey&key=sitekey&json={"sequential":1,"id":1}
```

After
----------------------------------------

In initial iteration of this PR, it simply updated the URL:

```
http://dmaster.bknix:8001/sites/all/modules/civicrm/extern/rest.php
  ?entity=Contact&action=get&api_key=FIXME_USER_KEY&key=FIXME_SITE_KEY&json=%7B%22sequential%22%3A1%2C%22id%22%3A1%7D
```

Based on some PR discussion, it seems that the single "Rest" URL was trying to do two things (explain the structure and provide a working example) - but it didn't quite achieve either, and they're a bit at-odds. So the final iteration of the PR splits this into two sections:

* "Rest" describes the HTTP request in general/readable terms.
* "curl" provides a working example of an HTTP request

Screenshots are in the discussion.

Technical Details
----------------------------------------

Notable elements:

* Apply URL encoding to the `json` param. (*This is the main thing that needed fixing.*)
* Apply URL encoding to the `entity` and `action` params. (*In practice, with normal values, this doesn't change anything.*)
* Make the placeholder/example values more obvious (eg `userkey` => `FIXME_USER_KEY`).

How much does it matter to have the `json` param encoded? Depends on the HTTP client and the specific data. Ex:

* `wget` escapes invalid characters automatically (`{` => `%7B`). 
* `curl` treats the `{...}` expression as a list for use in permutation (much like `bash` would). It sends multiple/different calls (one with `json="sequential":1`; the other with `json="id":1`).

There are some cases where these rules still yield a valid call. There are other cases where it will always yield an incorrect call. (Ex: if you set `first_name` to `Alice&Bob`, the `json` includes an unencoded `&` which mucks up the params).

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Mixed thoughts: It might be technically more correct however as an exploration tool it makes it harder to see what the params are supposed to be. And you still have to know to shell-escape things like `&` outside the json separately if using the command line.
 🤷

**Comment by totten** [comment]
@demeritcowboy Yeah, it's a good point that the output should help to educate/explain. OTOH, the status quo isn't exactly easy to read (in addition to being incorrect).

Perhaps it makes more sense to split this in two, e.g. a "Rest" section that describes the HTTP request in general/readable terms, and a "curl" section that describes the HTTP request in precise/correct terms. Just pushed this up:

Screenshot from 2021-01-27 16-13-40

**Comment by demeritcowboy** [comment]
That's kinda cool. And yes the get/post is something that people ask about.

I get an alignment problem (on both firefox and chrome). I need to set `vertical-align: bottom` on the `<pre>` element to get it to line up. When the test site here finishes will check if it's just me.

**Comment by demeritcowboy** [comment]
I see the alignment issue on the test site here too. And it's not a windows browser thing. I even tried eating a carrot but I'm still seeing it askew.

**Comment by totten** [comment]
I guess we need to tighten/reset the CSS rules a bit more.

FWIW, the alignment problem reproduces in D7 Bartik (but not in Garland, Seven, or WordPress).

**Comment by totten** [comment]
@demeritcowboy Updated examples from Garland and Bartik:

Screenshot from 2021-01-28 19-49-00

Screenshot from 2021-01-28 19-49-31

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@totten please merge once @demeritcowboy gives the thumbs up (& tests pass)

**Comment by demeritcowboy** [comment]
I think it looks good.

I was going to nitpick about curl in practice really being part of the REST section, but then you could also have a guzzle subsection, a php-curl subsection, and where do you stop. And also the other generic tools are at the bottom so that's why it's down there.

**Pull request merged**
