### PR TITLE
Crm 15829+crm 15881

### PR DESCRIPTION
**Pull request by ghost**
This pull request address issues CRM-15829 and CRM-15881.
- https://issues.civicrm.org/jira/browse/CRM-15829
- https://issues.civicrm.org/jira/browse/CRM-15881

Please note: code chunks that are being replaced by these changes have only been commented out and not completely removed. 
## CRM-15829 - Relationships and inherited pending memberships

Add pending memberships to new members of an organisation that has pending memberships
- CRM/Contact/BAO/Relationship -> line ~1459
- CRM/Contact/BAO/Relationship -> line ~1483
- CRM/Contact/BAO/Relationship -> line ~1493

Ensure these new pending memberships for an organisation's employees are not set to active
- CRM/Member/BAO/Membership - line 262
## CRM-15881 - Contact relationships (employee of)

Clear current employee when deleting a relationship that is the employer
- CRM/Contact/BAO/Relationship -> line ~621

Reload the tab ajax views to reflect removed employer display when deleting a relationship that is the employer
- CRM/Contact/Form/Relationship -> line ~395

If disabling an employer relationship (via the popup modal), unset the is_current_employer, please see comments in code
- CRM/Contact/Form/Relationship -> line ~442

Updated query to use bound variables in the SQL query string, to prevent SQL injection
- CRM/Contact/BAO/Contact/Utils.php -> line ~438

### CODE REVIEW

**Comment by colemanw** [comment]
It looks like you are restoring the file `CRM/Utils/Api.php` - is this intentional? This file was removed as part of some form layer refactoring and my preference would be to not re-add it.

**Comment by marcov4lente** [comment]
Oh dear, that was committed unintentionally, my apologies. Let me remove it quick! All other changes are intentional.

**Comment by marcov4lente** [comment]
I have updated the pull request and removed `CRM/Utils/Api.php `, as it should not have been a part of this bug fix. Thank you for your patience.

**Comment by colemanw** [comment]
I think the commit of the 2 hidden files (.gitignore and .DS_Store) was also not intentional?

**Comment by marcov4lente** [comment]
Yes that is correct. I have removed them from the repository.

**Comment by colemanw** [comment]
Almost... instead of committing the deletion of .gitignore, please just exclude it from the commit.

**Comment by davecivicrm** [comment]
I think this PR should include additions to the BAO unit test for this case(s).

**Comment by marcov4lente** [comment]
My apologies, I was slighty tied up earlier on. I have updated the pull request.

**Comment by kurund** [comment]
jenkins, test this please

**Comment by kurund** [comment]
@marcov4lente can you please fix the errors in test failure: https://test.civicrm.org/job/CiviCRM-Core-PR/3255/

**Comment by marcov4lente** [comment]
@kurund thank you for your feedback, could you kindly request that Jenkins, retest this please?

**Comment by kurund** [comment]
@marcov4lente looks like your commit has gone stale :(  Will it be possible to rebase / cherry-pick your changes and submit it as a separate PR? Let me know if you need any help.

**Comment by colemanw** [comment]
@marcov4lente when this happens to me I do the following (tweak this based on the names of your remotes if they are not "civicrm" and "marcov4lente"):

    git checkout CRM-15829+CRM-15881
    git pull --rebase civicrm master
    git push marcov4lente CRM-15829+CRM-15881 --force

This will prompt you to fix merge conflicts during the rebase, and pushing to the same branch will refresh this PR without needing to open a new one. If you can't get that working just let us know and we can do it for you from our end.

**Comment by marcov4lente** [comment]
Hi @kurund and @colemanw thank you for your feedback, yes that perhaps is a good idea. I have created a fresh pull request here https://github.com/civicrm/civicrm-core/pull/5789

**Pull request closed without merging**
