### PR TITLE
dev/core#2076 Fix for standalone event registrations confirmation email

### PR DESCRIPTION
**Pull request by kewljuice**
Overview
----------------------------------------
Fix for standalone event registrations confirmation email (event_offline_receipt) so that empty fields are not included in the mail.

https://lab.civicrm.org/dev/core/-/issues/2076

### CODE REVIEW

**Comment by jaapjansma** [comment]
@kewljuice the automatic build is failing because of a code style warning. Could you fix that?

**Comment by kewljuice** [comment]
@jaapjansma code style warning fixed.

**Comment by jaapjansma** [comment]
@kewljuice I have tested your patch on the test environment of this PR and I still get the custom field which is not used in the registration profile in the confirmation mail. So it looks like this patch does not solve the issue. 

What I have done is the following:

1. Created a custom group for participant with two custom fields
2. Created an event with online registration and a confirmation mail. Added only one custom field to the registration profile
3. Registered a person for an event through civicrms backend

Both fields are included in the confirmation mail. And I would only expect the field which I have selected in the profile. 

Can you have another look?

**Comment by eileenmcnaughton** [comment]
I'm going to close this out because I think it has stagnated because it's not clear that we should be making this change. In particular it's not clear that all sites would prefer to suppress empty fields. I think the right place to do this is in the message template - my preference is that in fact we suppress these fields by default for back office (since people often get in trouble with information they don't intend going out).

However,  this change in the message template would remove the blank rows
```
 {/if}
 {foreach from=$val item=v key=f}
-{$f}: {$v}
+  {if $v}
+    {$f}: {$v}
+  {/if}
 {/foreach}
 {/if}
 {/foreach}
```

**Pull request closed without merging**
