### PR TITLE
CRM-19999 Soften event error message on registration

### PR DESCRIPTION
**Pull request by JKingsnorth**
Let's party like it's 19999

---

 * [CRM-19999: Soften error message when registration is closed for an event](https://issues.civicrm.org/jira/browse/CRM-19999)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This seems like an improvement - you don't think it would work with an actual title do you - feels dodgey passing an empty string

**Comment by JKingsnorth** [comment]
How about 'Sorry'? I can stick that in the PR on Thursday.

**Comment by eileenmcnaughton** [comment]
Yeah sorry will do - if someone doesn't like it I'm sure we'll see an update PR :-)

**Comment by JKingsnorth** [comment]
(force) Pushed the change

**Pull request merged**
