### PR TITLE
dev/core/issues/819, Fixed fatal error on export screen

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/issues/819

Before
----------------------------------------
ExportError-Before

After
----------------------------------------
ExportError-After

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@pradpnayak is this a regression or just a bit obscure?

**Comment by pradpnayak** [comment]
@eileenmcnaughton I don't think so, I could replicate this on 5.6 and even on 4.7.31

**Comment by eileenmcnaughton** [comment]
Thanks @pradpnayak for confirming

**Comment by eileenmcnaughton** [comment]
I was able to replicate this in the UI & in a test & this fixes - I'll push the test up

**Pull request merged**
