### PR TITLE
CRM-17669 Add additional frequencies for scheduled jobs

### PR DESCRIPTION
**Pull request by konadave**
- [CRM-17669: Add additional run frequencies for scheduled jobs](https://issues.civicrm.org/jira/browse/CRM-17669)

### CODE REVIEW

**Comment by davecivicrm** [comment]
ok to test

**Comment by colemanw** [comment]
@konadave could you please avoid unnecessary merge commits in pull-requests?

**Comment by konadave** [comment]
@colemanw Sorry, didn't even realize that was here. After I made the second commit to add "Quarterly" as an option, I noticed my fork was 70 commits behind so I updated to make sure the file I was modifying hadn't been changed by someone else. If it's easier for everyone else, just close this and I'll start over.

**Comment by colemanw** [comment]
no need, you can do this (might need to tweak the name of the remote if not "civicrm")

    git reset --hard 16ced71
    git pull --rebase civicrm master
    git push -f

**Comment by colemanw** [comment]
Thee real question I have about this pull-request is that you seem to be adding only 1 option that is truly "new". "weekly" seems redundant with "mondays", "quarterly" duplicates "1stOfQtr" and "monthly" duplicates "1stOfMth". Won't this be confusing?

**Comment by konadave** [comment]
The difference between the options I propose and the three new ones you mention is that these can run any day of the week/month; e.g. start a weekly job on a Wednesday and it runs every Wednesday, or start a monthly on the 15th and it'll run every 15th. Throw in CRM-17686 and you have a whole lot more flexibility. I have that implemented on my end but I haven't created a PR yet, Eileen suggested I make sure that the core team was happy with the idea.

If both of those are accepted, then it would make sense to remove "Mondays", "1stOfQtr", and "1stOfMth". By the way, 1stOfQtr is a bit of a misnomer, as it actually runs on the 13th.

**Comment by konadave** [comment]
I've implemented and released CRM-17669 and CRM-17686 as an extension.

https://civicrm.org/extensions/flexible-jobs. Just submitted so release not listed there yet.

https://github.com/konadave/com.klangsoft.flexiblejobs

Closing pull request.

**Pull request closed without merging**
