### PR TITLE
dev/core#561 Upgrade age_asof_date to datepicker in search

### PR DESCRIPTION
**Pull request by colemanw**
- Updates the age fields on the Demographics section of Advanced Search.
- Simplifies the `updateSmartGroups` class.

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton I've run an upgrade test and can vouch that the grant fields are still updating properly after refactoring that smartGroup upgrade class.

**Comment by eileenmcnaughton** [comment]
@colemanw we have a couple of initiatives around these fields - the other is how to make it so values can be passed through the url. I really want us to be synchronising getting rid of jcalendar with a metadata-based approach that also supports that goal (which has at least one PR open that this will make stale). 

Currently the Grant search did the conversion through metadata- this  function works through the metadata. 
```
  /**
   * Get the defaults for the entity for any fields described in metadata.
   *
   * @param string $entity
   *
   * @return array
   */
  protected function getEntityDefaults($entity) {
    $defaults = [];
    foreach ($this->getSearchFieldMetadata()[$entity] as $fieldSpec) {
      if (empty($_POST[$fieldSpec['name']])) {
        $value = CRM_Utils_Request::retrieveValue($fieldSpec['name'], $this->getValidationTypeForField($entity, $fieldSpec['name']), FALSE, NULL, 'GET');
        if ($value !== FALSE) {
          $defaults[$fieldSpec['name']] = $value;
        }
      }
    }
    return $defaults;
  }
```

And the addField stuff like in this PR comes from


```
  public static function buildSearchForm(&$form) {

    $grantType = CRM_Core_OptionGroup::values('grant_type');
    $form->addSearchFieldMetadata(['Grant' => self::getSearchFieldMetadata()]);
    $form->addFormFieldsFromMetadata();
```

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
@eileenmcnaughton what are the other PRs I should be considering?
IMO the "age_asof_date" is such an oddball that it would be a waste of time to invent a metadata category for it. This type of thing is not used anywhere else in the system as far as I can tell.

**Comment by eileenmcnaughton** [comment]
@colemanw this one - https://github.com/civicrm/civicrm-core/pull/13651/files (I think I have closed other similar ones due to them going stale)

**Comment by colemanw** [comment]
@eileenmcnaughton I don't see anything in that PR that conflicts with this one.

**Comment by eileenmcnaughton** [comment]
@colemanw it will need re-work once this is merged - however, I can accept that age as of date is an anomaly & we should get the approach right for the other date field coversions, not so much this one

test error = 

Stacktrace
CRM_Upgrade_Incremental_BaseTest::testSmartGroupDatePickerConversion
Missing argument 1 for CRM_Upgrade_Incremental_SmartGroups::updateGroups(), called in /home/jenkins/bknix-dfl/build/core-13704-6uoz0/sites/all/modules/civicrm/tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php on line 94 and defined

/home/jenkins/bknix-dfl/build/core-13704-6uoz0/sites/all/modules/civicrm/CRM/Upgrade/Incremental/SmartGroups.php:40
/home/jenkins/bknix-dfl/build/core-13704-6uoz0/sites/all/modules/civicrm/tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php:94
/home/jenkins/bknix-dfl/build/core-13704-6uoz0/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:196
/home/jenkins/bknix-dfl/civicrm-buildkit/extern/phpunit5/phpunit5.phar:598

**Comment by colemanw** [comment]
@eileenmcnaughton so is that a merge-on-pass from you?

**Comment by totten** [comment]
jenkins, test this please

**Comment by eileenmcnaughton** [comment]
strategy

**Comment by eileenmcnaughton** [comment]
OK - I tested this & it worked before AND after the upgrade ....merging

**Pull request merged**
