### PR TITLE
CiviCRM form cannot submit

### PR DESCRIPTION
**Pull request by iamandanyc**
Overview
----------------------------------------
My event registration and payment form suddenly stopped working for the complimentary/free ticket option. Users cannot press "continue" to submit the form if they chose complimentary ticket.

Event registration live page: https://apprenticelearning.org/civicrm/?page=CiviCRM&q=civicrm%2Fevent%2Fregister&reset=1&id=7

Before
----------------------------------------
It was working fine and we registered a bunch of complimentary ticket users until it suddenly stopped working.

After
----------------------------------------
When you click the submit button, the next page does not load and it stays on the current page, i.e. folks cannot register.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@iamandanyc there is a load of code here - probably more than you intended - but what is missing is info about what is causing the error - is there an error message? You've obviously done some diagnosis since you've created a PR rather than a gitlab issue

**Comment by iamandanyc** [comment]
Hi @eileenmcnaughton I don't see an error message. How do I diagnose this in more detail?

I'm on this thread/section because I couldn't figure out where to go on github/am new to all of this. Thanks for your help!

**Comment by eileenmcnaughton** [comment]
So you should create an issue on gitlab - https://lab.civicrm.org/dev/core/issues with all the information you have & then jump on chat.civicrm.org & link to it & see if anyone has any ideas. I'm shooting out but hopefully someone will be there. Make sure you include your CiviCRM version & what changed when it 'suddenly' stopped working.

Also - since you gave the link I just tried it & created a successful registration - name details are all clearly 'test' so you should be able to search & kill it

**Comment by iamandanyc** [comment]
Thanks so much, @eileenmcnaughton !

I just updated the link to the version of the form I'm working on: https://apprenticelearning.org/civicrm/?page=CiviCRM&q=civicrm%2Fevent%2Fregister&reset=1&id=6 

Does complimentary ticket registration work for you here?

**Comment by eileenmcnaughton** [comment]
I get redirected from there to the home page

(note going offline now but do try chat.civicrm.org)

**Comment by iamandanyc** [comment]
Ok thank you!

My bad, just updated the correct URL: https://apprenticelearning.org/civicrm/?page=CiviCRM&q=civicrm%2Fevent%2Fregister&reset=1&id=7

**Comment by eileenmcnaughton** [comment]
closing -this as it's now on gitlab here https://lab.civicrm.org/dev/core/issues/1334 & @xurizaemon has provided some response

**Comment by xurizaemon** [comment]
Weird, I don't see how all those old commits from 2015 got associated with this issue - is it GitHub matching JIRA ids por something?

Anyway for completeness this ended up at https://lab.civicrm.org/extensions/stripe/issues/118 in the end. For now :)

**Pull request closed without merging**
