### PR TITLE
CRM-18523 - Search Builder - Fix searching on Membership ID

### PR DESCRIPTION
**Pull request by ineffyble**
Update field name in Member/BAO/Query from "member_id" to "membership_id"

---
- CRM-18523: Search Builder fails for Membership ID
  https://issues.civicrm.org/jira/browse/CRM-18523

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please 

@ineffyble I suspect that we may need to keep member_id there and add another case for membership_id just for backward compatability not sure about you @eileenmcnaughton

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by ineffyble** [comment]
Hmm, that makes sense, let me know if I should adjust my patch

**Comment by eileenmcnaughton** [comment]
sounds like it. Ideally comment to explain & even more ideally add a unit test so someone else doesn't break it later

**Comment by ineffyble** [comment]
Adjusted to keep old variable name, and commented for future reference. Will look at unit test but I may need you to give me a hand @seamuslee001.

**Comment by ineffyble** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
Have tested on demo box works fine. Tested by searching for membership ID > 10 and returned sensible results @eileenmcnaughton

**Pull request merged**
