### PR TITLE
Fix unit tests following merge of PR #12797

### PR DESCRIPTION
**Pull request by seamuslee001**
This fixes unit tests following merge of https://github.com/civicrm/civicrm-core/pull/12797 ping @colemanw @eileenmcnaughton

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
thanks @seamuslee001 I obviously missed that! @lcdservices @madhavimalgaonkar do you want to re-test with this merged?

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Merging as per the tag

**Comment by eileenmcnaughton** [comment]
thanks @lcdservices appreciate you double checking

**Pull request merged**
