### PR TITLE
Instantiate PropertyBag

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
This seems like the minimum switch over. It's still using the merge legacy
as we have to work through params - e.g is '->_params['description']'
only being part of the bag - perhaps not. Also the email
is set & then potentially overwritten

Before
----------------------------------------
array passed to doPayment

After
----------------------------------------
Our very first bag-o-cash in core

Technical Details
----------------------------------------
Earlier discussion on https://github.com/civicrm/civicrm-core/pull/17292

Comments
----------------------------------------
@mattwire @artfulrobot this seems like the sort of baby-step we can take safely...

Per comments & previous discussion there is weird handling around 'email' & I haven't figured out what wins yet, so I started the bag after that

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I also note we need to add middle_name & stateProvince to the bag

**Comment by mattwire** [comment]
@eileenmcnaughton Test failures relate

**Comment by eileenmcnaughton** [comment]
Yeah casting on amount doesn't work. It's also a bit scary because of the formatting that goes on - just doing this doesn't fix

```
diff --git a/Civi/Payment/PropertyBag.php b/Civi/Payment/PropertyBag.php
index 42cfc56079..a6c20f58c0 100644
--- a/Civi/Payment/PropertyBag.php
+++ b/Civi/Payment/PropertyBag.php
@@ -72,6 +72,7 @@ class PropertyBag implements \ArrayAccess {
     'transactionID'               => TRUE,
     'transaction_id'              => 'transactionID',
     'trxnResultCode'              => TRUE,
+    'amount'                      => TRUE,
   ];
 
   /**
@@ -385,7 +386,7 @@ class PropertyBag implements \ArrayAccess {
       throw new \InvalidArgumentException("setAmount requires a numeric amount value");
     }
 
-    return $this->set('amount', CRM_Utils_Money::format($value, NULL, NULL, TRUE), $label);
+    return $this->set('amount', \CRM_Utils_Money::format($value, NULL, NULL, TRUE), $label);
   }
 

```

**Comment by mattwire** [comment]
There are quite a few flows that still don't create a contribution before calling doPayment - see https://lab.civicrm.org/dev/financial/-/issues/53

> like checking if the payment class supports propertyBag

The problem at the moment is we can't expect one or the other so can't do the payment processor conversion because we've still got to assume we might get an array or a propertyBag.

**Comment by eileenmcnaughton** [comment]
Closing for now

**Comment by mattwire** [comment]
> Then any payment class that's being updated could be encouraged to implement the property bag, and adhere to the interface/rules of what it should do? Meanwhile the existing code gets the existing jumbled array.

@artfulrobot We certainly need to do something. My view is that allowing export as array from PropertyBag (per https://github.com/civicrm/civicrm-core/pull/17507 or similar) is all we need because it gives payment processors an option to defer conversion while not preventing us make meaningful improvements to the CiviCRM core code. I tend to be of the view that if there is not active development on a payment processor it probably shouldn't be used (for various reasons including security, reliability etc. - we are dealing with people's money after all!). So forcing developers to add a couple of lines of code in the short-term is a good way of a) Making sure the processor is supported/maintained; b) Alerting the developers of the payment processor that they need to engage/convert their code to meet the new standards.

**Pull request closed without merging**
