### PR TITLE
(dev/core/91) Search Builder Improvements

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Earlier there was a requirement where we need to remove specific MySQL operators which are not valid for specific data type e.g. String type doesn't work with >, <, <= and >= operators. And here's the fix https://github.com/civicrm/civicrm-core/commit/759094bdfa40531e4ec0cf0a644d9edd6b9247cf done earlier as per which it is fetching all columns which are String type and passing them into a separate JSON string identified as ```stringFields``` and another formatted list of valid string operators as ```stringOperators```. Similarly to identify date fields and to do a specific operation on such fields we are passing another variable ```dateFields```. These JSON object in JS are later used to specific operations. Now on the other hand, recently, I encountered another issue where the Boolean type columns don't work with IS EMPTY/IS NOT EMPTY operator and eventually leads to DB syntax error. So if I follow the same approach I need to assign another JSON string, which won't be an ideal fix. This lead me to do following 3 changes to improve the code:
1. Assign a single list of all data columns which are either Boolean, String or Date (as currently, these are the only kind that needs attention)
2. Use this list (as ```fieldTypes```) in JS to filter the operator or do field specific operations like covert a input search field to datepicker if the chosen search field is date kind.
3. Reduce list of variable assignment.

Before
----------------------------------------
 Using IS EMPTY/IS NOT EMPTY operator against Boolean fields lead to DB Error:
test-multiple-before

After
----------------------------------------
Apart from fixing the error there are other scenarios shown in this screencast like datepicker toggle when field/operator is changed to ensure that this doesn't break the existing workflow. 
test-multiple-after

### CODE REVIEW

**Comment by monishdeb** [comment]
ping @lcdservices @colemanw

**Comment by monishdeb** [comment]
Plus I score 4 = -38/+34 cleanup points ;)

**Comment by eileenmcnaughton** [comment]
lol

**Comment by colemanw** [comment]
Looks good to me too. Thanks Monish!

**Comment by monishdeb** [comment]
@colemanw @JoeMurray I wasn't able to comment on the gitlab issue as I cannot sign in and each time  
 it denies with an error "Connection refused - connect(2) for 45.79.135.8:1389". So let me provide my explanation here. I thought its ok to close https://lab.civicrm.org/dev/core/issues/91 as this PR is merged, which cover all the three points mentioned the description. But then I saw the comment from Joe 
> I think it would be good practice to provide JSON output with allowed operators for each fieldType, even if some js will be hardcoding how to handle certain fieldTypes.

That’s a good idea, but I checked with all field type, it’s only the String and Boolean field type which don't work with certain operators as hardcoded on the JS and rest all field types works with all kind of SQL operators.  So what if we pass another json variable which tells what operators are not valid for only these two kind of field type i.e. 
 
```php
CRM_Core_Resources::singleton()
       ->addScriptFile('civicrm', 'templates/CRM/Contact/Form/Search/Builder.js', 1, 'html-header')
       ->addSetting(array(
         'searchBuilder' => array(
           ...
           'invalidOperators' => [
             ‘Boolean’ => [IS EMPTY, IS NOT EMPTY],
             ’String’ => [>, <, >=, <=],
           ],
         ...
      )
   ```
And in JS  
```
if ((field in CRM.searchBuilder.invalidOperators) && 
   (CRM.searchBuilder.fieldTypes[field] in CRM.searchBuilder.invalidOperators)
) {
  CRM.searchBuilder.generalOperators = _.omit(CRM.searchBuilder.generalOperators, CRM.searchBuilder.invalidOperators);
}
```
But then with this approach we are doing hardcoding in php not in JS. Overall I still feel the current patch is ok unless there is any another issue (other than optimisation) which fall under this issue.

**Comment by eileenmcnaughton** [comment]
@monishdeb I think the issue here is mostly the process - ie. the gitlab issue was not framed as what you wanted to solve but how you wanted to solve it - which then got confusing when you used a slightly different approach & it turned out the important thing was not the json but making the bug go away.

I don't have any specific thoughts about 'doing it better next time' since I don't think a small clarification discussion should drive us into navel gazing - but maybe we sometimes are too deep in the solution to describe the problem sometimes when raising tickets :-)

**Comment by eileenmcnaughton** [comment]
Right - it's easy for us devs to  put the cart before the horse sometimes :-)

**Pull request merged**
