### PR TITLE
CRM-17522 - CiviMember - support using membership price sets on contr…

### PR DESCRIPTION
**Pull request by MegaphoneJon**
…ibution pages without requiring selecting a membership option

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I feel both happiness & fear when I look at this http://www.someecards.com/usercards/viewcard/MjAxMi1mY2JmNmRiYmRlNzI5MmU2

**Comment by PalanteJon** [comment]
Eileen - is your fear specific to this patch, or is it related to your being traumatised by changes to the contribution page generally?

Put another way - is there something specific I can do that would make you feel less fearful about this patch?

**Comment by eileenmcnaughton** [comment]
It's general not specific - I realise your have thought about this & tested it. - I'd just like you to tell me you've thought about the way it might interact with things that you haven't thought about. :-)

**Comment by colemanw** [comment]
@PalanteJon what was the issue number for this? CRM-17522 looks unrelated.

**Comment by PalanteJon** [comment]
CRM-17552.  Dave asked me for a bit of extra work here, I'm going to try to get that done in a day or so!

**Comment by eileenmcnaughton** [comment]
Hey @PalanteJon - it looks like the extra work is just a bit of sql in the upgrade script - is that right?

**Comment by PalanteJon** [comment]
That's correct Eileen!  I've been trying to wrap up all these loose ends, but have been overwhelmed.

**Comment by eileenmcnaughton** [comment]
:-)

**Comment by PalanteJon** [comment]
I was concerned this branch had gotten stale, so I created a new branch - which turned out to be unnecessary, this is the first SQL update for 4.7b8.  Anyway - closing this PR in favor of #7594

**Pull request closed without merging**
