### PR TITLE
Convert more accordions

### PR DESCRIPTION
**Pull request by aydun**
Overview
----------------------------------------
Convert accordions to the new standard `details`/`summary`

Before
----------------------------------------
Old

After
----------------------------------------
New

Technical Details
----------------------------------------
None of these have conditional `collapsed` classes

Comments
----------------------------------------
Done by script ...

### CODE REVIEW

**Comment by vingle** [comment]
Thanks @aydun - this and [the other PR](https://github.com/civicrm/civicrm-core/pull/29448) are great steps forward.

As discussed in the [UI channel](https://chat.civicrm.org/civicrm/channels/user-interface), I'm checking to see which themers have implemented the changes [post-5.69](https://lab.civicrm.org/dev/user-interface/-/wikis/DINO:-Notify-themes-+-New-theme/Changes-in-5.69), because given the amount of reviewing these need, this might be a good time to clean up / remove some classes here, as many aren't needed in Civi's default theme any more.

**Comment by vingle** [comment]
I've had a quick look at support for dropping some classes:
 - Greenwich (out-the-box Civi) - yes
 - Radstock / Wordpress Civi Admin Utilities - yes
 - Finsbury Park - yes
 - Shoreditch - no (not soon either)
 - Aah - not yet
 - Island - not yet ([opened an Issue](https://lab.civicrm.org/extensions/theisland/-/issues/16))
 
My sense is it's worth doing, but maybe as a separate PR so consensus can form on that? During the testing I might be able to figure out a simple PR to make to Shoreditch/Island if they haven't added support by then.
 
If you agree, and have the time to adjust the script, the changes needed would be as follows:

```
<div class="crm-accordion-wrapper">
  <div class="crm-accordion-header">
     Something
  </div><!-- /.crm-accordion-header -->
  <div class="crm-accordion-body">
     Something else
  </div>
</div><!-- /.crm-accordion-wrapper -->
```

becomes

```
<details class="crm-accordion-bold">
  <summary>
     Something
  </summary>
  <div class="crm-accordion-body">
     Something else
  </div>
</details>
```

And


```
<div class="crm-accordion-wrapper">
  <div class="crm-accordion-header crm-master-accordion-header">
     Something
  </div><!-- /.crm-accordion-header -->
  <div class="crm-accordion-body">
     Something else
  </div><!-- /.crm-accordion-wrapper -->
</div>
```

becomes

```
<details class="crm-accordion-light">
  <summary>
     Something
  </summary>
  <div class="crm-accordion-body">
     Something else
  </div>
</details>
```

I don't think you need `<!-- /.crm-accordion-header -->` or `<!-- /.crm-accordion-wrapper -->` as the closing divs are replaced with `</details>` and `</summary>`, so easy to spot.

**Comment by aydun** [comment]
@vingle I've updated the script & both these PR's.  Please check.

**Comment by shaneonabike** [comment]
Hey Nicol,

At the sprint we are testing out your patches. From what I understand you would idealy like to merge #29447 and #29533. I tried to apply both on a buildkit site but you have a conflict in this patch (same issue actually in #29448)

```
git apply 29447.patch 
error: the patch failed : templates/CRM/Case/Form/ActivityTab.tpl:10
error: templates/CRM/Case/Form/ActivityTab.tpl : the patch didn't apply
```
Basically, the changes in ```templates/CRM/Case/Form/ActivityTab.tpl``` on line 10 need to be removed from one of these merge requests for them to be merged properly since they are included in all of them.

I wanted to test all the changes together to see what happens!

cc @vingle

**Comment by aydun** [comment]
@shaneonabike  That's great you are testing these.  I'd suggest reviewing #29533 first then we can merge that and I'll rebase this.

**Comment by vingle** [comment]
@shaneonabike - thanks alot for looking at this. What @aydun said. 

Also - I've done my review of these 43 template files on Aidan's bigger (64 files) WIP PR: https://github.com/civicrm/civicrm-core/pull/29448#issuecomment-1971549411. I suggested there taking out ActivityTab because of the clash you found - it has two varieties of accordion in it, one of them is fixed here but both are fixed in #29533. 

NB - Aidan - amirite that all of these 43 template files are in the 64 files in #29448?

**Comment by aydun** [comment]
@vingle Yes, these are all also in #29448.  I split it into 2 PR's thinking that it might be easier to review that way since these were simpler in the markup, ie no smarty conditionals.  However, it looks like the js is more of a complicating factor, and since your mega review on #29448 covers all of them we may be best to close this one and continue working on #29448.  

We can extract out some that need other work (as done in #29533) and push other updates to this PR then rebase this to remove those extracted.  And then eventually merge this.

**Comment by vingle** [comment]
@aydun.. that makes sense. If this issue has the 29 good accordions, that'll be a big start.

The 5 'Working but do these need to be accordions?' could also either be merged, or a quick decision made on them. And the four possibly deprecated ones plus activity tab could be removed (if someone can confirm the four have indeed been replaced with SK/FB). That'd leave just 25..

**Comment by aydun** [comment]
OK, as discussed on the sprint call, we will close this and focus on the larger #29448

**Pull request closed without merging**
