### PR TITLE
FormBuilder: load assignees and targets on existing activities, via api4 read-write multivalue virtual fields

### PR DESCRIPTION
**Pull request by highfalutin**
When you edit an existing Activity in a FormBuilder submission form, the activity's source, assignee and target contacts are now loaded. (This PR was extracted from #25377, and is focused only on fixing  [dev/core#4110](https://lab.civicrm.org/dev/core/-/issues/4110).

On the API level, you can now access source/target/assignee contact ids as virtual fields. For targets and assignees, these are multiple-value fields.

Readable, writeable multi-value virtual fields for activities and targets and assignees were part of api3. So this is also relevant to [dev/core#2486](https://lab.civicrm.org/dev/core/-/issues/2486).

Before
----------------------------------------
before

FormBuilder did not autoload targets or assignees in Activity submission forms.

And in api4, to "get" contact ids connected with an activity, you had to add a join to your request. 

After
---------------
after
-------------------------

Activity contacts are autofilled in FormBuilder Activity submission forms (once the js-layer problem mentioned in #25465 is resolved).

In api4 `Activity.Get`, you can select virtual fields `source_contact_id`, `target_contact_ids`, and `assignee_contact_ids`. 

Technical Details
----------------------------------------
These virtual fields are convenient at a small scale; for pulling large numbers of Activities and their associated contacts, it's probably more performant to join explicitly onto the ActivityContact, but I haven't tested this assumption.

### CODE REVIEW

**Comment by colemanw** [comment]
@highfalutin I think renaming the fields is causing a lot of test failures. IMO we should not rename them, as it breaks backward-compat. I think I understand your motivation for doing so, but to avoid the BC break how about:

- `target_contact_id`: keep as array input/output
- `target_contact`: new FK field

**Comment by highfalutin** [comment]
jenkins, test this please

**Comment by totten** [comment]
civibot, test this please

**Comment by highfalutin** [comment]
Hi @colemanw, in the process of extracting this PR from the other, I forgot a few lines. That's what was causing the earlier failures. False alarm, I think.

**Comment by colemanw** [comment]
Ok, glad to see it passing :)
However, for the sake of BC I still think it best to not rename those fields.

**Comment by highfalutin** [comment]
I can push a commit with non-plural field names later today. I can't see the compatibility issue, though ― maybe the unlikely scenario of some piece of code needing to use both the api3 and api4 versions of Activity.Get? Anyway, I don't need to spend any more brainpower on this so I'll just make the change when I have a moment 😆

**Comment by colemanw** [comment]
@highfalutin the issue isn't compat with v3, it's the fact that those fields already have those names in v4 (albeit just for the create action) and so any code that already uses them would break.

**Comment by highfalutin** [comment]
@colemanw fwiw those legacy field names are still writeable, see the [test](https://github.com/civicrm/civicrm-core/pull/25744/commits/d15216b081befd8fb127cda613bd13e3f671296e#diff-0e1c61116bed3ba43d565c17bbaf7c556449af0d895ab14d3d6fc6205130493eR137) that I just added to make sure.

I'm not interested in dying on this hill though, so let me know if you'd still like me to remove the plural names. Thanks for your all your attention to this.

**Comment by colemanw** [comment]
Hey @highfalutin I finally got the display bug solved in #26008 and I'm circling back to this.
I hate to be a jerk about this, but every time I change the name of something in the API I end up regretting it and getting bitten by some fallout, so my preference is to use the old singular names for these fields rather then the new pluralized ones.

**Comment by colemanw** [comment]
This looks great @highfalutin ! Thanks so much for your work on it.

**Pull request merged**
