### PR TITLE
Pre-upgrade message for php-intl shows twice

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
5.27 backport of https://github.com/civicrm/civicrm-core/pull/17748

FYI @seamuslee001

### CODE REVIEW

**Comment by demeritcowboy** [comment]
unrelated test fail - it's that same sorting one from before

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by demeritcowboy** [comment]
The fail was that sorting function from last week - it will continue to fail for anything in 5.27.

**Comment by demeritcowboy** [comment]
Thanks!

**Pull request merged**
