### PR TITLE
dev/core#722 Display attachments in Activities tab

### PR DESCRIPTION
**Pull request by chamilwijesooriya**
Overview
----------------------------------------
Attachments in case activities are displayed as paper-clip icon links on the case view screen.
case view

It would be better if attachments are displayed in the activities tab for all other activities as well.

After
----------------------------------------
Displaying attachment icons next to action links
activity

Technical Details
----------------------------------------
* `CRM_Activity_BAO_Activity::getContactActivitySelector()` method is only used in `CRM_Activity_Page_AJAX::getContactActivity()` which is the ajax call to fill up the activities in Activities tab. 
* I'm not sure where to add the attachments; as a separate column or inside an existing column so added them next to the action links 

https://lab.civicrm.org/dev/core/issues/722

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I think we should add a unit test if adding this new mini-feature - I took a look & the function looks pretty easy to test & there are existing tests like CRM_Activity_BAO_ActivityTest::testGetActivitiesForAdminDashboard
that does the required set up (although the actual function isn't tested yet)

I took a look & it looks like you've had PRs merged before but haven't written a test yet - let me know if you need help with it

**Comment by eileenmcnaughton** [comment]
@colemanw you might want to comment first as to whether you think the fix is the right way to present it

**Comment by colemanw** [comment]
IMO the paperclip looks messy underneath the "View" button, esp since it's not left-aligned with the word "View". But that's how it's done for cases and I don't have any brilliant better ideas. I think fixing the alignment would help.

**Comment by chamilwijesooriya** [comment]
@eileenmcnaughton I can't seem to figure out how to get PHPUnit running on my work pc. May be I'll try on my pc and see. 

@colemanw yeah I'm also not sure where to add it. May be under the activity type? font colours aren't matching then. please check the screenshot
attachments

To fix alignment, might have to add extra html in php code 
```php
$attachments = CRM_Core_BAO_File::paperIconAttachment('civicrm_activity', $values['activity_id']);
if (!empty($attachments)) {
    $activity['links'] .= "<br /><span style='padding: 3px 5px;'>" . implode(' ', $attachments) . "</span>";
}
```

**Comment by eileenmcnaughton** [comment]
@chamilwijesooriya jump on chat & we might be able to figure it out...

**Comment by eileenmcnaughton** [comment]
I'm going to close this for now & we can track through gitlab since it stalled on 'needs test'. There was a somewhat similar one that I am trying to recall that seemed simple but caused problems - which makes me less inclined to 'merge-regardless'

**Comment by eileenmcnaughton** [comment]
@demeritcowboy pinging you in case you want to bring this back

**Comment by demeritcowboy** [comment]
Thanks @eileenmcnaughton.  Maybe you're thinking of https://lab.civicrm.org/dev/core/issues/1186 which was an issue with displaying descriptions for custom field file attachments?

I personally don't have any specific itch for this, but am happy to help in some way if anyone wants to take it up.

**Pull request closed without merging**
