### PR TITLE
Release notes 4.7.15

### PR DESCRIPTION
**Pull request by agh1**
I spent some time last month getting a system to automate the generation of the notes.  Right now, this is the result.  Next, I need to do some manual edits and walk through the entries to write the plain English descriptions.

### CODE REVIEW

**Comment by agh1** [comment]
Okay, these notes are ready to include in the new release.

**Comment by guanhuan** [comment]
Looks good to me. Thanks Andrew.

**Comment by mi-kon** [comment]
Thanks Andrew!

**Comment by guanhuan** [comment]
@totten Please merge when you are ready.

**Comment by totten** [comment]
Thanks, @agh1 and @guanhuan!

**Pull request merged**
