### PR TITLE
dev/core#1637 regression fix on WP urls

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Reverts a change in 5.23 that is causing url breakage on WP when clean urls are  not enabled (https://lab.civicrm.org/dev/core/issues/1637) and possibly Joomla  but 
 still checking that (https://lab.civicrm.org/dev/financial/issues/120)

Before
----------------------------------------
Generated url is
/wp-admin/admin.php/?page=CiviCRM&q=civicrm%2Fupgrade%2Fqueue%2Fajax%2FrunNext

After
----------------------------------------
Generated url is /wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fupgrade%2Fqueue%2Fajax%2FrunNext

Technical Details
----------------------------------------
Revert "Make $civicrm_paths less sensitive to trailing slashes. Add t…ests."

This is currently causing breakage on wordpress sites where clean urls are not enabled.

Compare the 2 urls below - the top one has an extra (breaking) slash added by this PR.

I propose a quick revert  & patch release followed by 'the right' fix at a slower pace
/wp-admin/admin.php/?page=CiviCRM&q=civicrm%2Fupgrade%2Fqueue%2Fajax%2FrunNext
/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fupgrade%2Fqueue%2Fajax%2FrunNext

This reverts commit 232fdd3dfac4ea09749d7f178818139514e48e38.
 
This is the relevant line https://github.com/civicrm/civicrm-core/pull/16404/files#diff-1544096e8e60bfe9fe73eeca2844804eR223

Comments
----------------------------------------

### CODE REVIEW

**Comment by kcristiano** [comment]
@eileenmcnaughton I did an `r-run` this does fix the trailing slash mentioned in Mattermost https://chat.civicrm.org/civicrm/pl/6kco13rhyigzxxa646a7gjt43r

Looks good to merge

It does not correct https://lab.civicrm.org/dev/core/issues/1637

**Comment by kcristiano** [comment]
I've just cleared caches and this may fix https://lab.civicrm.org/dev/core/issues/1637   Would appreciate another person testing

**Comment by christianwach** [comment]
> This is currently causing breakage on wordpress sites where clean urls are not enabled.

Also when Clean URLs _are_ enabled.

**Comment by christianwach** [comment]
Patch works after CiviCRM caches cleared as @kcristiano says.

**Comment by colemanw** [comment]
Unrelated test fails. Merging per review comments.

**Pull request merged**
