### PR TITLE
Make hook_civicrm_pre() and hook_civicrm_post() fire on CaseContacts

### PR DESCRIPTION
**Pull request by aydun**
Overview
----------------------------------------
Make hook_civicrm_pre() and hook_civicrm_post() fire on CaseContacts

Before
----------------------------------------
Modifications to CaseContacts do not trigger hook_civicrm_pre() or hook_civicrm_post()

After
----------------------------------------
Modifications to CaseContacts do trigger hook_civicrm_pre() or hook_civicrm_post()

Technical Details
----------------------------------------
Based on CRM_Core_BAO_Dashboard::create() as advised on https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_post/

Documentation PR will follow once code merged.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
* General standards
    * [`r-explain`] __PASS__
    * [`r-user`] __PASS__
    * [`r-doc`] __PASS__ Since CaseContact isn't a first-class object and only exists because of the way the many-to-many relationship is modelled and exposed in civi, "create" and "edit" have a slightly different meaning here. They are more like "link" and "re-link". In other words, what you're hooking on is the event when a case object gets linked to a client contact object or vice-versa. No actual first-class object is being created/edited.
    * [`r-run`] __PASS__ I tested this by making a little extension that logs the pre and post hook input and then created a case. It all looks right. I also tested via api explorer since I wasn't even sure how to test the "edit" otherwise. For example reassign case doesn't seem to use the object/hook, and even if it did that action actually creates a new case and a new linkage.
* Developer standards
    * [`r-tech`] __PASS__
    * [`r-code`] __PASS__
    * [`r-maint`] __COMMENTS__ I'm not sure how you'd write a test for hooks.
    * [`r-test`] __PASS__

**Comment by MegaphoneJon** [comment]
@aydun @demeritcowboy I had to learn how to test hooks recently :)  An example is in `tests/phpunit/CRM/Contribute/Form/Task/PDFLetterCommonTest.php`, testing that `hook_civicrm_tokenValues` works correctly on PDF letters.

You write a [function using the hook](https://github.com/civicrm/civicrm-core/blob/master/tests/phpunit/CRM/Contribute/Form/Task/PDFLetterCommonTest.php#L136-L140), but you can name it whatever you want.  Then you call [$this->hookClass->setHook](https://github.com/civicrm/civicrm-core/blob/master/tests/phpunit/CRM/Contribute/Form/Task/PDFLetterCommonTest.php#L100), specifying the function name.

**Comment by demeritcowboy** [comment]
@MegaphoneJon Ah cool. Do you want to post that as answer to this SE question? https://civicrm.stackexchange.com/questions/25795/how-to-write-php-unit-test-for-an-entity-using-hooks

**Comment by mattwire** [comment]
Tested by @demeritcowboy This is a standard hook with standard parameters added in a "standard" way so we can skip a unit test.

**Comment by mattwire** [comment]
@aydun Please follow up with docs PR and I'll merge

**Pull request merged**
