### PR TITLE
Clean up the distmaker scripts

### PR DESCRIPTION
**Pull request by aydun**
Overview
----------------------------------------
Clean up the distmaker scripts.  Remove references to 'php5' which are confusing and obsolete.

Renames the newish joomla5 build to 'civicrm-$version-joomla5bc.zip' to denote this requires the Back Compatibility plugin, and clears the way to use '...joomla5.zip' as the native version not requiring BC.

Before
----------------------------------------
Script names like `backdrop_php5.sh` - but not related to php5.
Variables like `D5PACK` - meaning "build the php5 package of drupal"

After
----------------------------------------
Script names like `backdrop.sh`
More reasonable variable names.

Technical Details
----------------------------------------
Should be no difference in the resulting packages.

### CODE REVIEW

**Comment by aydun** [comment]
See also https://github.com/civicrm/civicrm-core/pull/31331

**Comment by ufundo** [comment]
Appreciate this work @aydun !

Code looks good to me - adding `run-distmaker` to see if those pipelines all work. I'm not sure if any other contexts which would be necessary to `r-run` separately?

**Comment by aydun** [comment]
Thanks @ufundo.  `run-distmaker` produced the expected files.   @totten , @seamuslee001 anything to add here or are we ok to merge?

**Comment by mlutfy** [comment]
> "I would think it could be merge-on-pass."

I took that opportunity to merge, because two other PRs were blocked by this one. I did a code review and it all seems fairly low-risk, except perhaps some Joomla bits that I am less familiar with. I will try to circle back and manually `r-run` and compare the tars with previous versions.

**Comment by mlutfy** [comment]
While reviewing #31389 I also did more spot-checking for this change, and all looks OK. Thanks @aydun !

**Comment by aydun** [comment]
Thanks @mlutfy !

**Pull request merged**
