### PR TITLE
CRM-19184 remove old old old suppress group functionality by defining…

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
… 'CIVICRM_GROUPTREE'

Per JIRA this seems to have never been implemented & there are certainly no code refs now

### CODE REVIEW

**Review by seamuslee001 — APPROVED** [review]
assuming it has never been defined anywhere makes sense

**Comment by eileenmcnaughton** [comment]
i grepped & googled & didn't find

**Comment by seamuslee001** [comment]
check behind the couch?

**Comment by eileenmcnaughton** [comment]
biscuit crumbs

**Pull request merged**
