### PR TITLE
Crm 16188 4.7

### PR DESCRIPTION
**Pull request by pradpnayak**
(DO NOT MERGE - Submitted to facilitate testing)

### CODE REVIEW

**Comment by pradpnayak** [comment]
Could any one please tell the Jenkin to retest the PR?

**Comment by davecivicrm** [comment]
Jenkins, test this please.

**Comment by pradpnayak** [comment]
jenkins, retest this please

**Comment by davecivicrm** [comment]
@pradpnayak Verified that 2 of the test failures are regressions related to changes in this PR:
api_v3_TaxContributionPageTest.testCreateContributionChainedLineItems
api_v3_ContributionTest.testCreateContributionChainedLineItems

**Comment by pradpnayak** [comment]
jenkins, retest this please

**Comment by JoeMurray** [comment]
We would like this PR to be applied so we can move ahead with providing test for payment API that relies on this order api. Pradeep will be fixing the check error or indicating his sense that it is not our code causing failure.

**Comment by davecivicrm** [comment]
@pradpnayak Test failures appear to both be related to the new Order api.

**Comment by pradpnayak** [comment]
jenkins, retest this please

**Comment by davecivicrm** [comment]
@pradpnayak Still throwing failures related to Order api / syntax conformance tests :-( Might want to touch bases with @colemanw or @eileenmcnaughton if you're unsure how to resolve.

**Comment by pradpnayak** [comment]
jenkins, retest this please

**Comment by pradpnayak** [comment]
closing in favour of https://github.com/civicrm/civicrm-core/pull/7591

**Pull request closed without merging**
