### PR TITLE
CRM-19986 Fix schema differences between a new install and an upgrad…

### PR DESCRIPTION
**Pull request by seamuslee001**
…e from 4.6

### CODE REVIEW

**Comment by seamuslee001** [comment]
ping @totten

**Comment by eileenmcnaughton** [comment]
@adyun where did you get to at the sprint with creating a function for auditing these?

**Comment by eileenmcnaughton** [comment]
@aydun ^^

**Comment by aydun** [comment]
@eileenmcnaughton It's a while since I have looked at it, but it was in a fairly good state.  It checks the indexes in the db against the schema, including the effects of localization. I don't think it would take much to get it to a PR - I'll blow the dust off it when I get a chance.

**Comment by eileenmcnaughton** [comment]
@aydun if you can point towards it on github it would be great - even it not quite ready

**Comment by aydun** [comment]
I sent the link by other means, but updating this ticket - see https://github.com/aydun/civicrm-core/tree/CRM-20312

**Comment by eileenmcnaughton** [comment]
@seamuslee001 does this still add some value? Or suggest something we should test

**Comment by seamuslee001** [comment]
@eileenmcnaughton yes it does, its not index related and also ensures that the comment is correct on the table plus makes sure that the Foreign Key is there

**Comment by eileenmcnaughton** [comment]
ok

**Pull request merged**
