### PR TITLE
Re Add CRM_Case_Form_Task::PreProcessCommon()

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @eileenmcnaughton @colemanw

### CODE REVIEW

**Comment by mattwire** [comment]
@seamuslee001 So I know this was related to the case export failing?  Do we need the `$this->caseIds` and `preProcessCommon` functions because they are called from the export class?  Or is there any other reason.

**Comment by seamuslee001** [comment]
@mattwire the reason why i am thinking there maybe legacy handling is because Coleman had to make this change https://github.com/civicrm/civicrm-core/pull/11926/files#diff-d62c51b919ba7bb286f97c0b2eb837c3L89 as well

**Comment by mattwire** [comment]
@seamuslee001 So the original plan with #11411 was just to duplicate what was done elsewhere but then it was pointed out that there's a lot of duplicate code so I created the Core/Form/Task.php (similar to what I did for CRM/Core/Task) except that I only made the changes for Case/Form/Task.php.  Looking at the export code I think we should either drop preProcessCommon or move it to Core/Form/Task.php as it's obviously meant to be called by all task classes.

**Comment by eileenmcnaughton** [comment]
@mattwire there might be a quick fix & a follow up clean up here ...

@seamuslee001 this would stop the fatal - do you think we should merge this & keep testing?

**Comment by eileenmcnaughton** [comment]
(needs to be against 5.0)

**Comment by seamuslee001** [comment]
@eileenmcnaughton i would say so

**Comment by eileenmcnaughton** [comment]
@seamuslee001 nope :-(

Error: Using $this when not in object context in CRM_Core_Form_Task::preProcess() (line 82 of /Users/emcnaughton/buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Core/Form/Task.php).

**Comment by eileenmcnaughton** [comment]
Using this I AM able to get an export (yay). Im going for a quick merge as it may affect the possibly related issue & I want all to be working from the same base.

@mattwire am hoping you will follow up with a measured consideration of this function against master

**Pull request merged**
