### PR TITLE
[NFC] Minor code cleanup

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Declare exceptions, use single quotes & strict comparison, do not declare unused params

Before
----------------------------------------
_

After
----------------------------------------

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
Looks fine to me

**Pull request merged**
