### PR TITLE
SearchKit - Add icon support

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
This allows each column to have one or more icons, based on a field value or a conditional rule.

Before
----------------------------------------
No icons in search displays.

After
----------------------------------------
image

Technical Details
----------------------------------------
Supplemented by #22996 which helps SearchKit accurately know what fields contain an icon.

### CODE REVIEW

**Comment by samuelsov** [comment]
Very nice!

I'm able to make the UI for SearchKit works as in you examples but no font-awesome icons on the result list.

Probably a problem in my dev site but I am on civicore master with this PR and PR22996 + I have ensured that the db is properly updated for option_value_fields. Not sure what's wrong in my testing environment... 
I will check again later but let me know if I miss some other PR dependency.

**Comment by colemanw** [comment]
@samuelsov try clearing caches

**Comment by colemanw** [comment]
@samuelsov now that #22996 is merged I've rebased this so you can try it out on the [PR demo site](http://site-list.test-1.civicrm.org:8001/?filter=core-23034-*).

**Comment by samuelsov** [comment]
Ok, seems all good to me.

I found my mistakes:
1. Most of the activity types don't have an icon so I wasn't seeing icons at first glance
2. I was using "=" operator for contact sub type instead of "contains" (= doesn't work for multi-valued fields).
Screenshot 2022-04-01 at 15-48-21 Contacts contacts avec icones searchkit dev501 symbiodev xyz

**Comment by colemanw** [comment]
Cool. Merging per review.

**Comment by colemanw** [comment]
FYI @samuelsov if you have a moment to give your :+1: on #23073 that's a step toward getting icons for contact types.

**Pull request merged**
