### PR TITLE
Update dedupe workflow improvements from veda consulting to latest master

### PR DESCRIPTION
**Pull request by rocxa**
Original pull request (for 4.5) here:
https://github.com/veda-consulting/civicrm-core/compare/4.5...veda-consulting:dedupe-workflow-45
& more info here
http://vedaconsulting.co.uk/civicrm-dedupe-workflow-ui

### CODE REVIEW

**Comment by kurund** [comment]
@rocxa Can you please fix the warnings reported by tests. It would be great if you can also file an issue for this PR

**Comment by rocxa** [comment]
What do you guys use to get the code formatting correct for CiviCRM?
eclipses doesn't quite have enough options to get it right..  primiarly the extra comma on the last element when declaring arrays.

**Comment by rocxa** [comment]
Closing as this is already being done by Deepak.
https://github.com/civicrm/civicrm-core/compare/master...deepak-srivastava:47-dedupe-workflow

**Comment by colemanw** [comment]
@rocxa civicrm-buildkit ships with the checkstyle script so you can run it locally to save round-trip time to the test server. In terms of IDE, most of us use PHPStorm, not sure about eclipse settings.

**Pull request closed without merging**
