### PR TITLE
SearchKit - Conditional style rules for rows/cells

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Enhances SearchKit with conditional style rules. For example
- Font strikethrough if contact is deceased
- Background red if email on hold
- Text faded out if relationship is not active

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Unrelated fail - fail relates to the silly way we 'internationalise' dates - ie translate month names rather than use the php library

Test Result (2 failures / ±0)
Civi.Token.TokenProcessorTest.testRenderLocalizedSmarty
CRM_Utils_DateTest.testLocalizeConsts

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by eileenmcnaughton** [comment]
@colemanw I just tested & I think you have an if around the wrong way

image

http://core-21947-1sy6x.test-3.civicrm.org:8001/civicrm/search#/display/contacts/Table

**Comment by eileenmcnaughton** [comment]
oh hang on - I just saw the yes/no

**Comment by eileenmcnaughton** [comment]
OK - that worked - I just had to see it & not leave it blank. Merging

**Pull request merged**
