### PR TITLE
Add icon for Country entity

### PR DESCRIPTION
**Pull request by aydun**
Overview
----------------------------------------
Add an icon and description for Country

Before
----------------------------------------
No icon

After
----------------------------------------
Has icon

Technical Details
----------------------------------------
As agreed at the Manchester Dev Training !

Comments
----------------------------------------
Eileen says its ok.....

### CODE REVIEW

**Comment by aydun** [comment]
(*CiviCRM Review Template DEL-1.2*)


* General standards
    * Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
        * __PASS__ : The goal/problem/solution have been adequately explained in the PR.
      * User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
        * __PASS__: The change would be intuitive or unnoticeable for a majority of users who work with this feature.
    * Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
        * __PASS__: The changes do not require documentation.
     * Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
        * __PASS__: 
* Developer standards
    * Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
        * __PASS__: The change preserves compatibility with existing callers/code/downstream.
    * Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
        * __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
    * Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
        * __PASS__: The change sufficiently improves test coverage, or the change is trivial enough that it does not require tests.
    * Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
        * __PASS__: The test results are all-clear.
        * __PASS__: The test results have failures, but these have been individually inspected and found to be irrelevant.
        * __ISSUE__: The test failures need to be resolved.
        * __COMMENTS__:

**Comment by colemanw** [comment]
I can't think of any FontAwesome icons that would accurately depict a country. I don't think it has an international flag set. What would this be used for?

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
We have the requisite forum of 8 people agreeing at the dev training - it's all good.....

**Comment by eileenmcnaughton** [comment]
Also - you have jet lag & are asleep & this will be merged before you wake up :-)

**Comment by eileenmcnaughton** [comment]
You snooze you lose - merging.

**Pull request merged**
