### PR TITLE
Grants appear in afform

### PR DESCRIPTION
**Pull request by MegaphoneJon**
Overview
----------------------------------------
I was testing the feasibility of using Form Builder for an upcoming grant application project.  I don't think Form Builder has the features I need yet, but in the course of testing I made them Afform-compatible.

Before
----------------------------------------
No grants in Form Builder.

After
----------------------------------------
Grants in Form Builder.

Comments
----------------------------------------
Coleman's recent work made this ridiculously easy - I thought the documentation was incomplete, but nope, it's just that simple.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
What were the gaps? I'm interested to know

**Comment by MegaphoneJon** [comment]
@eileenmcnaughton I needed a contact selector that only shows contacts in a particular group.  Conditionals are also important.

I'd also like to add fields that show up in the recorded submission but not saved to Civi.  There's data we need ephemerally, but it's a lot of work to define all of those as custom fields, especially since we'll never use them again.

I'm not complaining - I appreciate the work that goes into Form Builder!

One question though - it was so trivial to add support for grants in Form Builder that there is clearly some thinking against adding more of the simple entities (e.g. pledges, groups). Or more is expected before this is merge-ready.  I don't want to submit PRs like this if it's against the overall strategy.

**Comment by eileenmcnaughton** [comment]
ah yeah - adding other entities - I think we mostly have some worries about whether there are any where adding them might give a false-sense of security about them - e.g perhaps Contributions won't transition through statuses well - but we should discuss & bite the bullet at some point

**Comment by MegaphoneJon** [comment]
Oh ok phew. Yeah, I think it makes sense in that case to start adding the simpler entities.

It seems like we can enable core entities in an extension, which could help manage user expectations. E.g. if contributions is enabled via enabling "org.civicrm.herebeafformdragons".

On the question of missing features, I also recalled another issue I found. I could set a default value for a date field, but there was no way to set the default to "now".

**Comment by colemanw** [comment]
Yay for modularity. No extra code needed for Afform, or core.

**Pull request merged**
