### PR TITLE
Disable extern/soap.php. Remove implementation and tests.

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

There are no longer any known consumers of this interface, and it is awkward to maintain.

cc @seamuslee001 

Technical Details
----------------------------------------

I left some informational stubs. There are still some other repos that reference the class `CRM_Utils_SoapServer` (e.g. `civicrm-wordpress.git`, `civismtp.git`), and we don't to make class-files unloadable. The WordPress integration can probably be updated in tandem, but sites may still have `civismtp` enabled.

(Note: Leaving stub files also addresses the Joomla loop-hole for deletion.)

### CODE REVIEW

**Comment by seamuslee001** [comment]
seems fine to me any thoughts @demeritcowboy @eileenmcnaughton @colemanw @MegaphoneJon

**Comment by eileenmcnaughton** [comment]
I'm +1 on this. I think throwing an exception is good & that looks like a good approach

**Comment by MegaphoneJon** [comment]
I've never really touched this, but love watching code get removed.  Also I think this removes the dependency on the PHP SOAP extension?

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by totten** [comment]
> (@MegaphoneJon) Also I think this removes the dependency on the PHP SOAP extension?

From a core POV, yes. Extensions may still use PHP SOAP for other reasons. A quick grep of `universe` suggests a few examples (`com.iatspayments.civicrm`, and `com.aghstrategies.tsys`, `com.groupwho.paperlesstrans`).

**Comment by seamuslee001** [comment]
Flagging as Merge ready in case anyone has any further comments

**Comment by seamuslee001** [comment]
Probably been long enough am merging now

**Pull request merged**
