### PR TITLE
Move standalone classes and standaloneusers extension into core

### PR DESCRIPTION
**Pull request by artfulrobot**
Overview
----------------------------------------

This merges some core classes that are successful in building a standalone instance with buildkit, plus the standaloneusers extension as a core extension.

Before
----------------------------------------

No support for standalone builds.

After
----------------------------------------

Standalone builts possible. 

Technical Details
----------------------------------------

- Standalone is not a ready-product.
- Enabling the extension on a CMS site would be very bad news. It's marked as hidden to dissuade people from doing that.
- Lots of to-dos, but this is the initial commit, based on the meeting had by @artfulrobot @mlutfy @totten @eileenmcnaughton @colemanw @seamuslee001 briefly summarised at https://chat.civicrm.org/civicrm/pl/7j5fwtu4ofbwpxnu8e8wp3yx7w

Comments
----------------------------------------

I have focussed on getting standalone up and running on a local buildkit dev site. Please check this initial PR carefully before merging!

### CODE REVIEW

**Comment by mattwire** [comment]
Try rebasing against master again and re-pushing. This seems to happen occasionally.

**Comment by totten** [comment]
`master` should do it, and it does look like it was based on a fairly recent `master`.

FWIW, I tried a local update (`git pull --rebase origin master`), and it showed a merge-conflict. Same issue with a pro-forma rebase onto its existing base (`git rebase -i 6f26ec536f66b4e6fef503666cf74ce2a0b8d799`).

Looking at a [graphical rendition of the branch](https://github.com/civicrm/civicrm-core/assets/1336047/6387d5ea-9278-4d93-b3a4-a91b1c51d038), there were a couple of non-linear sections -- and some tools (eg `git rebase`) struggle to put that into linear form. I figured out the conflicted segment and combined those ~3 commits as 39f449f74bca105d83a7c98c37025c6a4f1aab8e. 

(Aside @artfulrobot - There seems to be an issue where Github web UI never shows icons on the commits that you authored. This gave me a slight palpitation - several commits show *only* my icon (*as the rebaser*). But `git log` does show the right authorship. The issue seems to affect how Github UI shows all your commits/PRs. You might take a look at `https://github.com/settings/emails` and ensure that `code.commits@art********.uk` is confirmed?)

**Comment by totten** [comment]
Weehoo!

FWIW, I've been doing some light `r-run` locally.  I've been able to use the login form. 🎉 

Aside: To enable/configure the extensions, I used this one-liner:

```
cv en authx standaloneusers && cv vset +l authx_login_cred+=pass
```

**Comment by eileenmcnaughton** [comment]
Classy

**Comment by eileenmcnaughton** [comment]
Nice work!

**Pull request merged**
