### PR TITLE
CRM16421 CRM 17633: Changes to support WP in it's own directory. Allo…

### PR DESCRIPTION
**Pull request by kcristiano**
…w for civicrn.settings.extra.php for WP. Create template for civicrm.settings.extra.php. Update install/civicrm.php for all needed params for different common install scenarios. Fix linting issues in civicrm.php.

CRM 16421 CRM 17633 - update CRM_Utils_System_WordPress to allow for common install configurations

Replaces https://github.com/civicrm/civicrm-core/pull/9106

### CODE REVIEW

**Comment by kcristiano** [comment]
Please see details on https://github.com/civicrm/civicrm-core/pull/9106

**Comment by kcristiano** [comment]
This requires https://github.com/civicrm/civicrm-wordpress/pull/105

**Comment by kcristiano** [comment]
@totten tested and merged your improvements.   Works fine.  Would like this in early in an RC cycle to get more eyes/hands on the rela world testing.

**Comment by kcristiano** [comment]
@totten test failure appears unrelated.  Can you confirm?

**Comment by kcristiano** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@totten @kcristiano this appears to have been worked on and broadly agreed. Can you reconfirm & we could plan to merge at the end of the week?

**Comment by kcristiano** [comment]
@eileenmcnaughton I can confirm that this is ready for merge (in my opinion).  There is the related patch for the wordpress repo - https://github.com/civicrm/civicrm-wordpress/pull/105

**Pull request closed without merging**
