### PR TITLE
dev/wordpress#73 - Be more forgiving about slash in wpBasePage

### PR DESCRIPTION
**Pull request by totten**
Overview
--------

The correct functioning of `wpBasePage` depends on whether the administrator omitted or added a trailing slash.  This is apparent on URLs with a trailing slash, eg

```
http://wpmaster.bknix:8001/civicrm/contribute/transact/?reset=1&id=1
```

Make it less sensitive.

Before
------

Example URL works OK with default setting `wpBasePage=civicrm`

Example URL fails with setting `wpBasePage=civicrm/`

After
-----

Example URL is OK with either setting `wpBasePage=civicrm` or `wpBasePage=civicrm/`

Technical Details
-----------------

I suspect the old symptom arose in the formula which produces the WP rewrite rules - ie the formula expects that there is no trailing slash. You could theoretically patch there, but this seems like it'll provide more thorough normalization.

When testing, the results affect the WP rewrite rules, so you may need to be particularly aggressive about clearing caches whenever you make a change in code or settings, eg

```
wp cache flush ; cv flush;  wp rewrite flush
```

### CODE REVIEW

**Comment by totten** [comment]
ping @kcristiano @gah242s

**Comment by kcristiano** [comment]
@totten this works for me.

I did `r-run` against master and 5.28  Worked in both situation.  I did have to flush caches and rewrite rules but that has come to be expected.

Any thoughts @christianwach

**Comment by totten** [comment]
Discussed a little on MM; resubmitting for 5.29. See #18332.

**Comment by christianwach** [comment]
> Any thoughts @christianwach

@kcristiano Looks good to me, consistency here is really helpful.

**Pull request closed without merging**
