### PR TITLE
CRM-17231 Allow for Multipart Report to be included in the Email Proc…

### PR DESCRIPTION
**Pull request by seamuslee001**
…essor

### CODE REVIEW

**Comment by totten** [comment]
It would be really neat if we had a folder with some example messages and a unit test which looped through them.

Short of that, it might help the reviewers if you could or Chris M could comment a bit on how it was tested.

**Comment by seamuslee001** [comment]
jenkins re-test this please

**Comment by seamuslee001** [comment]
Hi folks, So the way we have tested this which may not be the best method is we have put it live on a 4.6 production system for the last couple days. We have tuned up the debugging on the report that gets generated on the fetch bounces such that we can observe what is happening and it seems to be doing its job. We have bounce messages being added to the relevant table and they are useful messages. e.g. '550 5.7.1 Message rejected as spam by Content Filtering' rather than just this was a bounce forwarded to us by Sendgrid. @davecivicrm I'll leave it up to you re 4.6 v 4.7 also it would be good to hear from the CiviSMTP folks on this

**Comment by seamuslee001** [comment]
closed as per @davecivicrm comment on case in favor of https://github.com/civicrm/civicrm-core/pull/6771/files

**Pull request closed without merging**
