### PR TITLE
Add "pledge id" as column and filter in Contribution Detail report.

### PR DESCRIPTION
**Pull request by twomice**
Overview
----------------------------------------
The Contribution Detail report currently provides no information about any pledge to which the contribution may be linked. This small change will allow display of a Pledge ID, (if any), and likewise filtering by Pledge ID (as an integer)

Before
----------------------------------------
No pledge-related data in the report.

After
----------------------------------------
New column: "Pledge ID"
New filter: "Pledge ID"

Technical Details
----------------------------------------
Added a new table to `$_columns`, conditionally joining that table in `from()`.

Comments
----------------------------------------
I acknowledge that this report has been stretched and pulled in sometimes conflicting directions, usually related to soft-credits vs contributions vs. both. However, this small improvement doesn't overlap with that conflict and seems to be a simple value add with no technical downside.

### CODE REVIEW

**Comment by Stoob** [comment]
Thanks for joining these tables Allen

**Comment by yashodha** [comment]
@twomice looks good

**Comment by jitendrapurohit** [comment]
I've tested this manually on a local setup and confirmed that the newly added Pledge ID works fine in displaying the value in results as well as filtering the result. +1 to get this merged.

**Review by jitendrapurohit — APPROVED** [review]

**Comment by yashodha** [comment]
@twomice @jitendrapurohit merging this, thanks!

**Comment by twomice** [comment]
Thank you @yashodha !

**Pull request merged**
