### PR TITLE
SearchKit - Use Contact.sort_name instead of display_name for searches and Autocompletes

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Switches the new Autocomplete widgets (in Afform and SearchKit) to show contact `sort_name` instead of `display_name`. This is consistent with every other autocomplete in the system.

Before
----------------------------------------
image

After
----------------------------------------
image

Comments
----------------------------------------
While I was updating metadata for the Contact entity, I did some others as well which improves the default SearchKit display for lots of entities (adding more useful fields as default columns when you select or join an entity) and this improved metadata made the default autocomplete display good enough to delete a couple of the entity-specific overrides.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Looks like some Martians in your db...

```
api_v4_AfformAutocompleteUsageTest::testAutocompleteWithSavedSearchFilter
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'A testAutocompleteWithSavedSearchFilter64e3dff715cce'
+'testAutocompleteWithSavedSearchFilter64e3dff715cce, A'

/home/homer/buildkit/build/build-2/web/sites/all/modules/civicrm/ext/afform/mock/tests/phpunit/api/v4/AfformAutocompleteUsageTest.php:71
```

* api_v4_AfformAutocompleteUsageTest::testCustomContactRefFieldWithGroupsFilter
* api_v4_AfformAutocompleteUsageTest::testCustomContactRefFieldOnJoinEntity

**Comment by demeritcowboy** [comment]
Did a little bit of clicking around. Looks good.

Maybe out of scope: for contacts it's not on par with contact reference custom fields - the main thing is they include the email so you can tell two similar ones apart. But the quicksearch which is where this started does include it so 👍

**Comment by colemanw** [comment]
> Looks like some Martians in your db...

Terminated. 👽 🔫 

> Maybe out of scope: for contacts it's not on par with contact reference custom fields - the main thing is they include the email so you can tell two similar ones apart. But the quicksearch which is where this started does include it so 👍

I would argue the configurability of APIv4 Autocompletes exceeds the par of ContactRef fields by quite a bit. If you want to include the email in your widget, you can configure a SearchDisplay for your Autocomplete. But I like *not* doing it by default. Giving out the email address of everyone in your db might not actually be desirable (or *legal*!) in all circumstances.

**Comment by demeritcowboy** [comment]
> you can configure a SearchDisplay for your Autocomplete

That sounds like voodoo, or maybe martian technology.

**Comment by colemanw** [comment]
retest this please

**Pull request merged**
