### PR TITLE
CRM-17854: Ensure there's a comma present before adding the new…

### PR DESCRIPTION
**Pull request by ghost**
… columns to Logging table schema

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
We've stopped merging upstream from 4.6 now so we are only accepting PRs into 4.6 now that are in 4.7 already - can you do a PR against 4.7? -Once it's merged into 4.7 I'm happy to merge this

**Comment by seamuslee001** [comment]
There seems to have been a slightly different version of the fix put into master. https://github.com/civicrm/civicrm-core/pull/7605/files by @monishdeb  Not sure which is better

**Comment by eileenmcnaughton** [comment]
@monishdeb any thoughts - I'm happy for the fix for 4.6 to be slightly different - as long as it's not broken - do you know the code well enough to comment on whether this is safe to merge?

**Comment by agileware** [comment]
Probably better to re-use the change from #7605 - the overall effect is the same (and less expensive to the regex engine)

**Comment by eileenmcnaughton** [comment]
Superceded by https://github.com/civicrm/civicrm-core/pull/7662 (thanks @seamuslee001  )

**Pull request closed without merging**
