### PR TITLE
IIDA-116 Refactored Deferred Revenue report to follow more standardized approach.

### PR DESCRIPTION
**Pull request by Edzelopez**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@monishdeb I'm happy for you to review & merge this. I think the scope is narrow enough that it's fine to be within JMA. I would prefer to see the commit  squashed. @Edzelopez it loos like a code improvement

Note that I probably would prefer to see this report in an extension. It would give JMA more flexibility to edit it. But, given it's in core & this is just editing I'm not pushing for that here

**Comment by monishdeb** [comment]
@eileenmcnaughton I have squashed all commits into one. Checking now

**Comment by Edzelopez** [comment]
@eileenmcnaughton yes, it is an improvement from what it was earlier. I have now squashed the commits.

**Comment by monishdeb** [comment]
Yup, commits has been squashed to one, checking now

**Comment by monishdeb** [comment]
@eileenmcnaughton @Edzelopez I have tested the PR on my local with Event, membership and Participant and Batch transactions data and it worked for me. Also tried with report each filter to ensure that report query behave well.

screen shot 2017-04-06 at 4 15 48 pm

**Comment by monishdeb** [comment]
@Edzelopez I have encountered test build failure for the changes made in ```getAllDeferredFinancialAccount(...)```. Updated the PR with necessary fix

**Pull request merged**
