### PR TITLE
dev/core#3930 remove custom field label index

### PR DESCRIPTION
**Pull request by herbdool**
Overview
----------------------------------------
See: https://lab.civicrm.org/dev/core/-/issues/3930

Removes custom field label index from db.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Just on the mechanics the upgrade should be in 5.56

**Comment by herbdool** [comment]
@demeritcowboy thanks, I've updated it.

**Comment by demeritcowboy** [comment]
So this was added in CRM-78!
I'm not clear on the use-case for having two fields with the same label _in the same custom group_. I read the lab ticket, but what's the situation where you do want to allow this?

**Comment by herbdool** [comment]
Not sure. I think the better question is when would we want to have a fatal error when someone tries to create a field with the same label. I don't see any reason for it. I think it's poor DX.

 In the front end there's already validation to prevent it there and that's only because it doesn't allow someone to set a different label and name.

**Comment by demeritcowboy** [comment]
> that's only because ...

Everything I can see suggests it's there because having two fields with the same label in the same group is undesirable, as a business rule not because of a technical implementation. It complements the form validation by keeping the database state consistent with the form rules.

Consider also if you did end up with two fields with the same label, then somebody later goes to clean it up in the UI and deletes the one that has data entered. Then that data gets deleted.

Maybe something for the dev-digest?

**Comment by herbdool** [comment]
Perhaps for dev-digest.

I still think it is unnecessary but perhaps a change to this would require showing both the label and the name in the UI so it is clearer that they are different. And allow people to set them differently. That's one thing I much prefer in Drupal: label/machine_name where the latter is shown and gets created automatically but someone can click edit to change it.

**Comment by demeritcowboy** [comment]
Ok I have added to the dev-digest draft.

**Comment by JoeMurray** [comment]
I think what is jarring is the hard error message. I am not supportive of removing this index for reasons @demeritcowboy indicates. I would prefer to see a friendly error message, eg "A field with that label already exists in this custom field group. Please use a unique label when creating fields." This provides a hint for users about the workaround without explaining  "If desired, duplicate field labels within a custom field group can be set by updating the unique field label to replicate another in the group." The latter is suitable for the book perhaps but to my mind not for onscreen help.

**Comment by demeritcowboy** [comment]
To clarify, the UI for users already has a reasonably friendly popup. The PR is proposing to allow creating duplicate labels via api/code.

**Comment by JoeMurray** [comment]
Then I just am not in favour.

**Comment by mattwire** [comment]
> Then I just am not in favour.

@JoeMurray Can you explain why? We still have unique machine names and there can be valid reasons for having fields with the same label. Example: A list of terms/consents with descriptions above each one and a field that simply says "Agree" for each one.

**Comment by herbdool** [comment]
For me it's mostly about the bad DX. It's no less jarring when using the API. It results in an obtuse message and requires the developer to start digging around with no hints to try to understand why it "already exists". Conflicting names and ids I can understand, but it was a surprise to learn that the labels would cause a fatal error as well. And I only found that out by looking at the `civicrm_custom_field` indices.

2022-10-31 09 17 53 xmass lndo site 0caecb5933e9

**Comment by adixon** [comment]
Here's an example to support this proposal/PR. On a multilingual site, when creating custom fields, there was some version of CiviCRM (possibly still) that would break the UI. The reason was that the translated labels of the custom fields were being auto-generated as blank, and so the second field you created would generate an errror (with an error message that was completely opaque!).

As an aside, take a look at the stackexchange posts with that error message with this google search:

site:civicrm.stackexchange.com "DB Error: already exists"

**Comment by demeritcowboy** [comment]
For the use case where you have a list of terms, I think that front end would be a profile or other forms solution, so whether it's allowed would depend on that feature. But it made me look and profiles DO allow the same label within a group.

So I may be convinced now, and then I would say it needs to be consistent, so also allow it in the UI.

The multilingual issue: I'd have to look that up but I remember it being a mariadb issue with STRICT_TRANS_TABLES, where the view default is treated differently than in mysql. More to do with multilingual architecture than whether there's a use case for two being the same. But in any case both you and Herb are making the more general argument that errors should tell you the problem.

**Comment by adixon** [comment]
I'd describe the argument as about how "shoulds" (i.e. business rules) get implemented. When they are implemented at the database level, they can be really difficult to debug. An opinionated business rule like this that doesn't actually break anything when violated should be implemented in code, IMHO (not to mention, better visibility). I feel like there are some similar examples from the financial system and those have had much worse outcomes. But I digress ...

**Pull request closed without merging**
