### PR TITLE
WIP Contribution.transact API alternative transitional version

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Let's see if unit test pass

Before
----------------------------------------
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

After
----------------------------------------
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

Technical Details
----------------------------------------
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire if this is for webform why doesn't it just implement it's own api rather than try to change a core api that does very little badly?

**Comment by mattwire** [comment]
@eileenmcnaughton This is really just to see if we actually have anything that can replace `Contribution.transact` without lot's of extra code.  And Order.create + Paymentprocessor.pay are still not quite "mature" as we've found from the sprint so potentially wrapping them both here gives us more flexibility to tweak them before we force people to stop using transact.  Alternatively this PR might just get used to generate docs on how to interact with Order/Pay.

**Comment by eileenmcnaughton** [comment]
@mattwire forcing  them to stop using this api would mean removing it - I think we should deprecate as is but I don't think we should remove it

**Comment by mattwire** [comment]
See also #15340

**Comment by mattwire** [comment]
> @mattwire forcing them to stop using this api would mean removing it - I think we should deprecate as is but I don't think we should remove it

This just continues the pain for payment processor authors as the site users just expect them to work!  See #15504 for a compromise which I'm hoping is acceptable to everyone at this stage?

**Comment by eileenmcnaughton** [comment]
I've been obviously snowed since the sprint &  am not following this ( or several other)  issues but rather trying to  get on top of the  various discussions we had at the sprint about the order api & getting stuff onto it

I just added this about how migrating off transact  api should look https://github.com/civicrm/civicrm-dev-docs/pull/705 -I think that documentation step is important because I can then point to it when I put up the PR we agreed was needed to deprecate the Contribute.transact api

I'm also working on a metaissue to track the various things - but it only just started at the moment

**Comment by mattwire** [comment]
Closing in favour of #15504 which I think satisfies all requirements as it makes no actual "changes" in core.

**Pull request closed without merging**
