### PR TITLE
CRM-18426 pay later receipts not going out

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
- [CRM-18426: Pay later receipts not going out](https://issues.civicrm.org/jira/browse/CRM-18426)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@monishdeb This is pretty 'late breaking' to be considered for this release - but I think it will be hard to do this week's testing of the merged changes without it....

**Comment by monishdeb** [comment]
Should I proceed by adding unit test on top of the patch to ensure pay_later reciept is sent ? (if needed will cherry-pick your commit and send a new PR)

**Comment by eileenmcnaughton** [comment]
That would be a fantastic approach :-)

**Comment by eileenmcnaughton** [comment]
NB it's also worth noting that we are about to get into 'test week' - where an RC release will be available & Tim is hoping that we will put together some test notes. I think we would ideally build up a sort of manual testing plan in this area that people could try out with the RC - although it might be that we can only do a one-form example this time around. Not being able to see the invoices on demo is an issue there - although I would VERY much like to  record all invoice text in full in activities & this might be the justification for getting that done now

**Comment by monishdeb** [comment]
Tested working fine however found a notice on ThankYou page Notice: Undefined property: CRM_Contribute_BAO_Contribution::$payment_status_id in CRM_Contribute_BAO_Contribution_Utils::processConfirm() (line 180 of ...

So I will submit a PR that includes 
- Unit Test to ensure receipt go out every time but
- notice fix above

But for that I am merging this PR because the above two task and https://github.com/civicrm/civicrm-core/pull/8159 depends on it.

**Comment by monishdeb** [comment]
Submitted the additional fixes in https://github.com/civicrm/civicrm-core/pull/8358

**Comment by eileenmcnaughton** [comment]
thanks - I'll take a look at your patch

**Pull request merged**
