### PR TITLE
Added new hook to alter relative date

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
Added new hook to alter relative date i.e from and to

@colemanw @eileenmcnaughton

### CODE REVIEW

**Comment by seamuslee001** [comment]
@pradpnayak can you fix the style issues pls

**Comment by pradpnayak** [comment]
Hi @seamuslee001 

Have just pushed styling fix.

Thanks
Pradeep

**Comment by pradpnayak** [comment]
jenkins retest this please

**Comment by pradpnayak** [comment]
Any one know why test is failing?

**Comment by demeritcowboy** [comment]
@pradpnayak If you look at the console output at https://test.civicrm.org/job/CiviCRM-Core-PR/28945/consoleText it ran the api tests and then stopped saying `Missing XML: CRM_AllTests.xml`, so I think something just got mixed up in the build. Jenkins test this please.

**Comment by pradpnayak** [comment]
test this please

**Comment by seamuslee001** [comment]
@demeritcowboy @pradpnayak , @totten and I have just been discussing this issue and the problem is a logic order issue

In PHPUnit before it starts running test suites it evaluates dataproviders first including https://github.com/civicrm/civicrm-core/blob/master/tests/phpunit/CRM/Activity/Form/SearchTest.php#L83 which then triggers hooks to be invoked, However at this point the CiviCRM Container has not been booted at all so the Query fails

**Comment by demeritcowboy** [comment]
Interesting. Good job tracking it down.

**Comment by totten** [comment]
Right, phpunit calls the `@dataProviders` at the very beginning of execution (while building the list of test-cases )-- before `setUp()`, before `setUpBeforeClass()`, before any test-listeners. If one wants to minimize brainhurt from bootstrap/test-sequencing issues, I'd suggest keeping the `@dataProviders` pretty flat/staticy.

You can probably fix the problem by juggling the `SearchTest` functions to avoid hooks in the `@dataProvider`.

--

`r-explain` - Could we have some more discussion of a use-case/example (i.e why+how one would want to use the hook)?  

(It doesn't have to be in the Github PR per se - a link to a Gitlab issue or a dev-docs PR would also do.*)

**Comment by MikeyMJCO** [comment]
Some issues on the docs PR on this - please update the docs PR when merged to add  the "trigger" release

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon how does this compare to your one?

**Comment by eileenmcnaughton** [comment]
(@MegaphoneJon has a hook for this)

**Comment by eileenmcnaughton** [comment]
I've added 'needs-concept-approved' because I don't want to get this merged without weigh in from @MegaphoneJon who previously had a hook proposal that 
I *think* differs

**Comment by MegaphoneJon** [comment]
Sorry, just seeing this.  I'll take a look this week.

**Comment by MikeyMJCO** [comment]
@eileenmcnaughton can you label as needs docs - the docs PR isn't merge-ready yet.

**Comment by eileenmcnaughton** [comment]
Just a couple of notes

1) you can get some other relative date options by creating option values - limited to the patterns in the 2 PRs linked from here (at the moment -just because those have been changed in the code to be flexible https://github.com/civicrm/civicrm-dev-docs/issues/707 )

2) the reason I'm worried about this Pr is that it doesn't make it clear the mechanism for adding new  labels for the UI to utilise this hook (it's certainly not in the PR template). That's the reason I'm so keen to see if @MegaphoneJon reached the same conclusion about how it should look as @pradpnayak has here.

**Comment by MikeyMJCO** [comment]
Linking docs PR for this: civicrm/civicrm-dev-docs/pull/672

**Comment by jaapjansma** [comment]
Betty and I are reviewing PR's and we came across this one. It seems that this one is ready to be reviewed however we have now conflicting files. 

@pradpnayak are you willing to fix the conflicting files? So that we can review it again.

**Comment by eileenmcnaughton** [comment]
@pradpnayak I'll close for now  & you can re-open when the conflict is resolved.

I'm still keen to see how this compares to @MegaphoneJon proposal

**Comment by MikeyMJCO** [comment]
I'm closing the linked docs PR civicrm/civicrm-dev-docs/pull/672

**Comment by pradpnayak** [comment]
@eileenmcnaughton should i reopen this or will need to use different approach for adding hook to alter relative dates?

**Comment by eileenmcnaughton** [comment]
@pradpnayak I just pinged @MegaphoneJon & he said he will  respond early next week

**Comment by MegaphoneJon** [comment]
OK, I've looked this over and compared to [my own version](https://github.com/MegaphoneJon/civicrm-core/commit/bf1b376938da7c0a45b3e11f3c8ebeb8c80218e9).  They're very similar, but I have a slight preference for my own.  

Minor reasons are that we don't have to process the relative date twice if the term is handled by the hook, and that you don't need to conform to the "term and unit" criteria - but these aren't compelling.  The first is a micro-optimization, the second can be resolved (in either direction) with a single line of code in the extension.

The only compelling reason I have to prefer mine is that the function that this hook is in is terrible.  I would really prefer to move this out of core one day - it's an 800-line function filled with copy/paste.

All that said - there's nothing you could do with one of these hooks that you couldn't do with the other, so I'm not really stuck on my own.

**Comment by eileenmcnaughton** [comment]
@pradpnayak see what you think - I'm happy to merge whatever you & @MegaphoneJon can agree on

**Comment by semseysandor** [comment]
Now is there anything that is preventing this from merging?
I would love to see this hook in core! :)

As I've read through I feel the only thing we need now is the approval from @pradpnayak as @MegaphoneJon has basically approved this.
I aggree with Jon that function (`CRM_Utils_Date::relativeToAbsolute()`) is really ugly, but still I say we should go with this solution as it is complete with tests and documentation. Actually we did something very similar for some custom relative date fields (`before the last xx days`):
https://github.com/reflexive-communications/hu.es-progress.relative-date-filters/pull/4/files#diff-a7d98b3aeb93d90fcef4de4bef73e3205cbbfa40da019f52474c492194b28f1e
But for this to work we need to patch core which is far from ideal...

So, I mean it's been 1.5 years now and we shouldn't wait forever to get this feature implemented.
If there is anything that could be done, I'm happy to put some effort in.

**Pull request closed without merging**
