### PR TITLE
(WIP) Sybunt - Rob's work

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
@KarinG @robbrandt I rebased Rob's sybunt report updates - this branch has a bunch of my fixes not yet merged so it adds a bit to the list- but adding a PR so  you can test on a sandbox

I haven't dug into Rob's changes too much

### CODE REVIEW

**Comment by KarinG** [comment]
Have blocked off some time to look at this on Saturday.

**Comment by robbrandt** [comment]
@eileenmcnaughton Thanks Eileen.

**Comment by KarinG** [comment]
Argh... I've got troubles adding 8823 as a patch to a clean dmaster [just civibuild it 5min ago]:

karins-macbook-pro:civicrm sysadmin$ cat 8823.patch | patch -p1 --dry-run
patching file CRM/Report/Form/Contribute/Detail.php
patching file CRM/Report/Form/Contribute/Summary.php
patching file CRM/Report/Form.php
patching file CRM/Report/Form/ActivitySummary.php
patching file CRM/Report/Form/Case/Demographics.php
patching file CRM/Report/Form/Case/Summary.php
patching file CRM/Report/Form/Case/TimeSpent.php
patching file CRM/Report/Form/Contact/CurrentEmployer.php
patching file CRM/Report/Form/Contact/Detail.php
patching file CRM/Report/Form/Contact/Log.php
patching file CRM/Report/Form/Contact/Summary.php
patching file CRM/Report/Form/Contribute/Bookkeeping.php
patching file CRM/Report/Form/Contribute/Detail.php
Hunk #1 FAILED at 506.
1 out of 1 hunk FAILED -- saving rejects to file CRM/Report/Form/Contribute/Detail.php.rej
patching file CRM/Report/Form/Contribute/PCP.php
patching file CRM/Report/Form/Contribute/Summary.php
patching file CRM/Report/Form/Event/IncomeCountSummary.php
patching file CRM/Report/Form/Event/ParticipantListCount.php
patching file CRM/Report/Form/Event/ParticipantListing.php
patching file CRM/Report/Form/Event/Summary.php
patching file CRM/Report/Form/Grant/Detail.php
patching file CRM/Report/Form/Grant/Statistics.php
patching file CRM/Report/Form/Mailing/Detail.php
patching file CRM/Report/Form/Mailing/Opened.php
patching file CRM/Report/Form/Mailing/Summary.php
patching file CRM/Report/Form/Member/ContributionDetail.php
patching file CRM/Report/Form/Member/Lapse.php
patching file CRM/Report/Form/Member/Summary.php
patching file CRM/Report/Form/Pledge/Detail.php
patching file CRM/Report/Form/Pledge/Pbnp.php
patching file CRM/Report/Form/Pledge/Summary.php
patching file CRM/Report/Form/Walklist/Walklist.php
patching file CRM/Report/Form/Contribute/TopDonor.php
patching file tests/phpunit/api/v3/ReportTemplateTest.php
patching file CRM/Report/Form.php
patching file CRM/Report/Form/Contribute/Summary.php
Hunk #2 succeeded at 468 (offset -3 lines).
patching file tests/phpunit/api/v3/ReportTemplateTest.php
Hunk #1 FAILED at 309.
1 out of 1 hunk FAILED -- saving rejects to file tests/phpunit/api/v3/ReportTemplateTest.php.rej
patching file CRM/Report/Form/Activity.php
patching file CRM/Report/Form/ActivitySummary.php
Hunk #1 succeeded at 40 with fuzz 2 (offset 2 lines).
patching file CRM/Report/Form/Case/Demographics.php
Hunk #1 succeeded at 39 (offset 2 lines).
patching file CRM/Report/Form/Contact/CurrentEmployer.php
Hunk #1 succeeded at 34 (offset 2 lines).
patching file CRM/Report/Form/Contact/Detail.php
Hunk #1 succeeded at 45 (offset 2 lines).
patching file CRM/Report/Form/Contact/Relationship.php
patching file CRM/Report/Form/Contact/Summary.php
Hunk #1 succeeded at 50 (offset 2 lines).
patching file CRM/Report/Form/Contribute/Bookkeeping.php
Hunk #1 succeeded at 47 (offset 2 lines).
patching file CRM/Report/Form/Contribute/Detail.php
patching file CRM/Report/Form/Contribute/Recur.php
patching file CRM/Report/Form/Contribute/Repeat.php
patching file CRM/Report/Form/Contribute/SoftCredit.php
patching file CRM/Report/Form/Contribute/Sybunt.php
patching file CRM/Report/Form/Contribute/TopDonor.php
patching file CRM/Report/Form/Event/ParticipantListCount.php
Hunk #1 succeeded at 41 (offset 2 lines).
patching file CRM/Report/Form/Mailing/Bounce.php
patching file CRM/Report/Form/Mailing/Clicks.php
patching file CRM/Report/Form/Mailing/Detail.php
Hunk #1 succeeded at 44 (offset 2 lines).
patching file CRM/Report/Form/Mailing/Opened.php
Hunk #1 succeeded at 54 with fuzz 2 (offset 2 lines).
patching file CRM/Report/Form/Member/ContributionDetail.php
Hunk #1 succeeded at 45 with fuzz 2 (offset 2 lines).
patching file CRM/Report/Form/Member/Detail.php
patching file CRM/Report/Form/Member/Lapse.php
Hunk #1 succeeded at 45 with fuzz 2.
patching file CRM/Report/Form/Member/Summary.php
Hunk #1 succeeded at 48 with fuzz 2 (offset 2 lines).
patching file CRM/Report/Form/Pledge/Detail.php
Hunk #1 succeeded at 54 (offset 2 lines).
patching file CRM/Report/Form/Pledge/Summary.php
Hunk #1 succeeded at 42 with fuzz 2.
patching file CRM/Report/Form/Contribute/Detail.php
Hunk #1 FAILED at 391.
Hunk #2 FAILED at 940.
2 out of 2 hunks FAILED -- saving rejects to file CRM/Report/Form/Contribute/Detail.php.rej
patching file CRM/Report/Form/Contribute/Repeat.php
Hunk #1 succeeded at 399 (offset -9 lines).
patching file CRM/Report/Form/Contribute/Lybunt.php
patching file CRM/Report/Form.php
Hunk #1 succeeded at 1360 with fuzz 2 (offset 19 lines).
patching file CRM/Report/Form/Contribute/Sybunt.php
Hunk #1 FAILED at 47.
Hunk #2 succeeded at 105 (offset -13 lines).
Hunk #3 succeeded at 313 (offset -13 lines).
1 out of 3 hunks FAILED -- saving rejects to file CRM/Report/Form/Contribute/Sybunt.php.rej
patching file CRM/Report/Form/Contribute/Sybunt.php
Hunk #1 succeeded at 165 (offset -9 lines).
Hunk #2 succeeded at 188 (offset -9 lines).
Hunk #3 succeeded at 228 (offset -9 lines).
Hunk #4 succeeded at 237 (offset -9 lines).
Hunk #5 succeeded at 265 (offset -9 lines).
Hunk #6 succeeded at 309 (offset -9 lines).
Hunk #7 succeeded at 366 (offset -8 lines).
Hunk #8 succeeded at 420 (offset -8 lines).
Hunk #9 succeeded at 444 (offset -8 lines).
Hunk #10 succeeded at 465 (offset -8 lines).
Hunk #11 succeeded at 537 (offset -8 lines).
Hunk #12 succeeded at 684 (offset -8 lines).
Hunk #13 succeeded at 728 (offset -8 lines).

**Comment by eileenmcnaughton** [comment]
@KarinG you will have to pull the whole branch - ie. add me as a remote & then pull my sybunt branch - there are a bunch of other changes I made in #8820 which this runs on top of. Hopefully I can get that merged at some point as it fixes the performance issues for group filter - although not on all reports

**Comment by KarinG** [comment]
Ah - ok - got it:
 * [new branch]      sybunt     -> origin/sybunt

**Comment by KarinG** [comment]
Hey @robbrandt and @eileenmcnaughton - I'm all set up and am looking at the new SYBUNT report. Here's what I've done thus far (see screenshot):

1) created a Priceset with two Pricefields - two different Financial Items (Donation and Member Dues). 
2) added an $80 Contribution in 2015 for the Adams family - using this priceset: $20 for LineItem1 (of Financial Type Donation) and $60 for LineItem2 (of Financial Type Member Dues)
3) run the report: and I'm getting $160 under Donation? Perhaps I'm not understanding what to look for - and thus how to test your edits? 

sybunt

**Comment by KarinG** [comment]
One more screenshot: showing the edits that I had made to the Adams Family contribution record: the report is not capturing this - unless I'm just not sure how to look at this? 

adams

**Pull request closed without merging**
