### PR TITLE
CRM-17512 Improve event sellout messages

### PR DESCRIPTION
**Pull request by JKingsnorth**
- [CRM-17512: Event selections message: 'spaces' not 'seats'](https://issues.civicrm.org/jira/browse/CRM-17512)

### CODE REVIEW

**Comment by davecivicrm** [comment]
Web tests need to be updated to match new strings.

**Comment by JKingsnorth** [comment]
Will fix this up tomorrow.

**Comment by JKingsnorth** [comment]
Weird, the tests passed. I thought Jenkins would have failed? Or does Jenkins not run the phpunit webtests?

**Comment by colemanw** [comment]
The webtests are too slow (and unreliable sadly) for CI. Hoping to fix that at some point.

**Comment by JKingsnorth** [comment]
Righto, I really need to get my local dev box back up and running to run tests on these things before submitting the PRs then. Sorry about that!

**Comment by colemanw** [comment]
It's ok, you're not the only one who doesn't run webtests [ducks]

**Comment by JKingsnorth** [comment]
;]

**Comment by JKingsnorth** [comment]
I've been fighting with my dev box for ages trying to get selenium to work, but no luck yet. This should fix the test cases, but I haven't been able to... test that.

**Comment by JKingsnorth** [comment]
Failure looks unrelated.

**Comment by davecivicrm** [comment]
Web tests pass locally (all methods in PricesetMaxCountTest). Thanks!

**Comment by JKingsnorth** [comment]
Thanks for checking the tests Dave. I'll get my dev box sorted.

**Pull request merged**
