### PR TITLE
CRM-20945 Remove underline on active pager step

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @colemanw @seanmadsen does this make sense to both of you?

---

 * [CRM-20945: Differentiate using CSS active selected page in AtoZ Pager](https://issues.civicrm.org/jira/browse/CRM-20945)

### CODE REVIEW

**Comment by colemanw** [comment]
@seamuslee001 can you do a screenshot to show the difference?

**Comment by seamuslee001** [comment]
@colemanw before
before pr crm-20945
After
after pr crm-20945

**Comment by colemanw** [comment]
That change is almost too subtle to notice. My design eye would want the active option to look like a depressed button. Something obvious.

**Comment by seamuslee001** [comment]
@colemanw i have tried making the active one look bit more darker whilst still keeping in line with the rest see the below screen shot. I also thought of having a white square box behind it but i felt that would break the look a bit too much
after pr crm-20945 latest

**Pull request merged**
