### PR TITLE
[REF] Swap CRM_Utils_Array::value for ??

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
PHP 7 finally has a built-in language construct that does basically the same thing as our homebrew function. Swapping the two is more efficient and easier to read.

Before
----------------------------------------
Less efficient: `CRM_Utils_Array::value($key, $array, $default)`

After
----------------------------------------
More efficient: `$array[$key] ?? $default`

Notes
-----------
I did this with a regex but then manually checked the results and tweaked some of them that were particularly weird or that could be further simplified (for example within an `if()` statement the whole thing could be swapped for `!empty()`.

Technical Details
----------------------------------------
The difference in functionality between these two constructs is negligible. Technically there is one difference: if the item exists in the array but has a value of `null`, then `CRM_Utils_Array::value()` would return `null` whereas ?? would return the default. However I think it's unlikely any developer was relying on this quirk.

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton 750 sloc is quite a large diff to read, but I actually did go through it all to check for problems (and did find a few that I corrected). Note this PR will go stale quickly.

**Comment by demeritcowboy** [comment]
@colemanw I'm totally for killing this function, but it seems like there'd be a difference if the originally passed second parameter is not actually an array? Maybe you already weeded those out?

**Comment by eileenmcnaughton** [comment]
@colemanw this feels high risk - am happy to deal with it in chunks but the chance of me missing a mistake in this many changes gives me pause

**Comment by colemanw** [comment]
Ok. Test failures show that I missed a few spots and I agree this is too much for one PR. Will close and chunk it.

**Pull request closed without merging**
