### PR TITLE
CRM-18303 - Reload contribution object after update

### PR DESCRIPTION
**Pull request by monishdeb**
- [CRM-18303: Online pledge payments paid through payment processor never complete](https://issues.civicrm.org/jira/browse/CRM-18303)

### CODE REVIEW

**Comment by monishdeb** [comment]
@eileenmcnaughton test failures got fixed in my local, waiting for the test build to run clean. Can you please verify my patch !!

**Comment by eileenmcnaughton** [comment]
@monishdeb The problem I have with this patch is it feels like it's going to break again since there is no obvious reason why the action is required in terms of logic - it basically is 'reinstate a hack to get things working' - which is why I wanted to break it down into the symptoms & pass sensible parameters rather than the whole contribution object. 

I would be inclined to replace the call to sendMail to calling the api civicrm_api3('Contribution', 'sendconfirmation') which does the reload and is tested, and which isolates the usage of various things.

The pledge function is fixed in the other PR - which possibly leaves the activity create - which could well be happening twice, but needs to be checked

**Comment by monishdeb** [comment]
@eileenmcnaughton I will then QA https://github.com/civicrm/civicrm-core/pull/8057 first and if everything works well, will merge it. As per this PR will replace the call of sendMail() by civicrm_api3('Contribution', 'sendconfirmation') and add test to assert the scenario.

**Comment by eileenmcnaughton** [comment]
@monishdeb I had a go at replacing & it's not quite there - am trying to put up an alternative & get some tests in there

**Comment by monishdeb** [comment]
@eileenmcnaughton I have just now updated the PR. Can you please verify my changes ? Will add/extend unit-test for it

**Comment by eileenmcnaughton** [comment]
Hmm - let me show you where I got to on it & we can compare - I have a test

**Comment by monishdeb** [comment]
cool

**Comment by eileenmcnaughton** [comment]
Monish - here is my go at it https://github.com/civicrm/civicrm-core/pull/8119 - I added a test to check up on loads of params.

The one thing I am haven't tested but suspect might need to be tested is whether the forms that allow setting of 'receipt_text' result in that being included appropriately on the receipts. I have tried to add a test on Membership back office form - but the test didn't seem to go through the completetransaction path so it added test cover - but not for the code path I mentioned

**Comment by monishdeb** [comment]
Closing in favor of #8119

**Pull request closed without merging**
