### PR TITLE
CRM-21852-Membership report failure fix

### PR DESCRIPTION
**Pull request by seenu4043**
Overview
----------------------------------------
Membership detail report error when ACL used (disable view all contacts)

Before
----------------------------------------
When a restricted user accesses the Membership Detail Form, an error is thrown.
image
After
----------------------------------------
When a restricted user accesses the Membership Detail Form, the report should be displayed.
image

Technical Details
----------------------------------------
buildACLClause has been used twice so I Just commented one as it's taking care in buildQuery, also buildPermissionClause has been used as it overriding buildQuery since buildQuery is deprecated(see in code)

Comments
----------------------------------------
As this is the fist time am writing code for Civicrm so I would appreciate if you could provide me feedback to improve myself better

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins ok to test

**Comment by eileenmcnaughton** [comment]
Great first PR - nice clear PR explanation with images.

Jenkins has reported some style warnings - which are probably whitespace issues - see https://www.drupal.org/docs/develop/standards/coding-standards for the drupal standards which we follow

2 questions
1) why did you move a line in the parent class
2) is the postProcess() function now similar enough to the parent function that we could just remove the whole function?

**Comment by seenu4043** [comment]
@eileenmcnaughton 

1. why did you move a line in the parent class
**because buildPermissionClause Override output from buildACLClause,**
is the postProcess() function now similar enough to the parent function that we could just remove the whole function?
No it doesn't,I actually tried to remove the whole postProcess code and use parent postprocess, apparently it doesn't work, sounds like we need build query function.

I will re-write the code for style issue and resubmit it.

**Comment by seenu4043** [comment]
https://issues.civicrm.org/jira/browse/CRM-21852, JIRA ticket number, fyi

**Comment by eileenmcnaughton** [comment]
@seenu4043 I just did some tests. This works but it works for me without moving the 
```
$this->buildPermissionClause();
```
- which is a change that is making me a little nervous

It also worked for me if I just removed this

```
  public function postProcess() {

    $this->beginPostProcess();

    // get the acl clauses built before we assemble the query
    $this->buildACLClause($this->_aliases['civicrm_contact']);
    $sql = $this->buildQuery(TRUE);

    $rows = array();
    $this->buildRows($sql, $rows);

    $this->formatDisplay($rows);
    $this->doTemplateAssignment($rows);
    $this->endPostProcess($rows);
  }
```

From CRM_Report_Form_Member_Detail - I'm wondering why that didn't work for you?

(removing redundant code is the nicest fix :-)

**Comment by eileenmcnaughton** [comment]
@seenu4043 did you see above - just wanting to understand why removing the whole function didn't work for you? I'm a bit uncomfortable with the re-ordering

**Comment by eileenmcnaughton** [comment]
Closing as Seamus reviewed alternate fix & now merged

**Pull request closed without merging**
