### PR TITLE
TokenProcessor - Allow basic filter/modifier expressions

### PR DESCRIPTION
**Pull request by totten**
Overview
---------

This demonstrates how to extend `TokenProcessor` to support rendering token-expressions with filters/modifiers.

ping @eileenmcnaughton @mattwire 

Before
------

`Hello {foo.bar}`

After
-----

`Hello {foo.bar|upper}` and `Hello {foo.bar|lower}`

Technical Details
-----------------

This only supports tokens that supply values through `civi.token.eval` (ie `$row->token(...key-value...)`).  At the time of this commit, most `{contact.*}` tokens still use `TokenCompatSubscriber::onRender()` to hack-in their values and won't work until they switch over.

The regex which recognizes the filter is pretty tight (eg accepting `|upper` or `|lower` but not `|myfunc:"yadda yadda"`).  This can be relaxed somewhat by a subsequent change, but I'd say such a change has a burden to demonstrate safety/interoparbility when running in Token-Smarty format.  (e.g.  demonstrate that matching of open/close symbols works correctly).

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Cool - I have a feeling that |upper would already be pretty useful (I'm sure I've written tokens in the past to do just that....)

**Comment by eileenmcnaughton** [comment]
test fails relate

**Comment by totten** [comment]
> test fails relate

Ah, it wasn't working on pseudo-tokens with a `:` in the name. Updated the regex. `ByTypeTest` is now  passing locally... We'll see what Jenkins has to say...

**Comment by eileenmcnaughton** [comment]
@totten I'm gonna give this merge-ready. It seems useful in itself & it works but obviously the real value is when we extend for dates. I've put a note in the dev-digest

**Comment by colemanw** [comment]
Looks good to me too.

**Pull request merged**
