### PR TITLE
Add pseudoconstant to dao

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Simply adds a pseudoconstant to a field

Before/After
----------------------------------------
No functional change

Technical Details
----------------------------------------
The list of things a profile can be used for is hard-coded. But passing it through the pseudoconstant system will allow it to be hookable.

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton this is going to be needed for the ContactSummary Editor extension, so I thought best to get it into 5.3 if we want to release by the end of June.

**Comment by eileenmcnaughton** [comment]
@colemanw the requirement is not for it to be in June release but for the services to have been delivered by then

**Comment by eileenmcnaughton** [comment]
test fails seem related

**Comment by colemanw** [comment]
Ugh. Ok back to the drawing board...

**Pull request closed without merging**
