### PR TITLE
Export code clean up - extract build row & getTransformed row off to ExportProcessor

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Code cleanup in export class

Before
----------------------------------------
Code not extracted

After
----------------------------------------
Code extracted

Technical Details
----------------------------------------
@mattwire this is actually a pretty simple code moving PR - it should be fairly easy to verify by repeating the steps to extract locally. I think the jenkins tests should be pretty sufficient here as there is no logical change in this step

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire I also added this - https://github.com/civicrm/civicrm-core/pull/13120 which doesn't conflict with this so can be tested in conjunction

**Comment by eileenmcnaughton** [comment]
This is my working branch for follow ons https://github.com/civicrm/civicrm-core/compare/master...eileenmcnaughton:export_merge?expand=1

**Comment by mattwire** [comment]
I've tested this locally with a small dataset (207 contacts) and it works fine with/without this PR.  The PR itself is extracting and moving code to the ExportProcessor class and creating a new function to build each row.  There is a small risk that this could have a cumulative performance impact on large datasets but given that the functions called multiple times are cached (pseudoconstant and i18n singleton) that impact should be minimal.  Ok to merge @eileenmcnaughton @seamuslee001

**Comment by eileenmcnaughton** [comment]
thanks @mattwire I'll push up another step later today

**Pull request merged**
