### PR TITLE
CRM-19187 Add link to public mailing

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Links are now on the Report page & the browse link drop-down.

They only show if the visibility is Public

---
- [CRM-19187: Add links to the public version of the civimails](https://issues.civicrm.org/jira/browse/CRM-19187)

### CODE REVIEW

**Comment by seamuslee001** [comment]
should this be added to the AB tests as well?

**Comment by eileenmcnaughton** [comment]
maybe but I am wary of this getting too much scope creep

**Comment by seamuslee001** [comment]
I Tested this by 
1. deploying it to a CiviBuild
2.  Creating a test mailing and submitting the mailing noting the cron was not running so no mailings would be sent.
3. Clicking on the report link saw the public url. 
4. Verified public url link worked correctly.
5. Repeated Step 2 ensuring that under publication that it was set to user and admin only
4. Clicked on report link 
5. verified public url link was not present

This is safe to merge

**Comment by seamuslee001** [comment]
Noting that i think it would be useful to extend this to AB tests but given that maybe scope creep i am ok with this being merged without it

**Pull request merged**
