### PR TITLE
[EXPORT] add getPreview function

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Adds a function to allow preview of export results.

Before
----------------------------------------
No preview

After
----------------------------------------
Preview

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@colemanw this PR gets us to the point of having a somewhat working (or at least tested) getPreview function - https://github.com/civicrm/civicrm-core/pull/14782/files#diff-4686601201fee8a8402a894c1b7df226R2698

The function still takes QF format mappings but the convert happens early on (before the processor is instantiated) & will be easy to move further out of the function completely.

This PR is WIP & not tested in its entirity. 3 sub-prs are in the q at the moment - #14780 #14774 #14773

**Comment by colemanw** [comment]
@eileenmcnaughton that's great! Awesome progress.
FYI when I call the getPreview function while loading the new exportUi I wouldn't pass in any fields, just load all fields into the dom so the results are instant while picking and rearranging fields.

**Comment by colemanw** [comment]
@eileenmcnaughton this needs rebasing and I wonder if https://github.com/civicrm/civicrm-core/pull/14780 is actually causing the test failure as those commits are in both PRs and both had the same failure.

**Comment by colemanw** [comment]
Needs another rebase

**Comment by totten** [comment]
jenkins test this please

**Comment by colemanw** [comment]
So @eileenmcnaughton we've now got this wip PR down to a single commit :)
And best of all, it works! My extension's getPreview function now looks like this:

    /**
     * @return array
     */
    protected function getPreviewData() {
      $exportParams = $this->controller->exportValues('Select');
      $isPostalOnly = (
        isset($exportParams['postal_mailing_export']['postal_mailing_export']) &&
        $exportParams['postal_mailing_export']['postal_mailing_export'] == 1
      );
      $processor = new CRM_Export_BAO_ExportProcessor($this->get('exportMode'), NULL, $this->get('queryOperator'), $this->get('mergeSameHousehold'), $isPostalOnly, $this->get('mergeSameAddress'));
      $processor->setComponentTable($this->get('componentTable'));
      $processor->setComponentClause($this->get('componentClause'));
      return $processor->getPreview(5);
    }

Which still strikes me as doing a bit too much work, in particular the bit about `$isPostalOnly` is copy-paste. But we're getting there :)

**Comment by colemanw** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
Nice - let's merge this - I'm gonna clean up a bit more as a follow up

**Pull request merged**
