### PR TITLE
CRM-14901 Add in entity_table whitelists for uf_join, entity_tag, mai…

### PR DESCRIPTION
**Pull request by seamuslee001**
…ling_group and note

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Interesting - I was inclined on first blush to say the permitted tables should have gone in the xml - but I can't think of a specific reason why that would be better.

**Comment by seamuslee001** [comment]
this was @colemanw 's idea

**Comment by eileenmcnaughton** [comment]
Yeah I was afraid someone smarter than me might have come up with it. What can you do?

**Comment by colemanw** [comment]
@eileenmcnaughton that was my first idea too, but totten suggested a callback function and I agree this way is:

1. Way easier to implement (no mucking around with GenCode and the pseudoconstant underbelly)
2. More flexible; potentially one function or option list could be shared among similar entities.

**Comment by colemanw** [comment]
@eileenmcnaughton correct me if I'm wrong but I think the test failures in this PR may be due to the recent refactoring you did of tag permissions.

**Comment by eileenmcnaughton** [comment]
yeah looks like it - those are new tests in that PR. Pretty sure they passed in CI so perhaps it was in the context of the full run they fail - I'll look soonish

**Comment by eileenmcnaughton** [comment]
I'm going to merge this - there don't seem to be any blockers @seamuslee001 can you close the issue if it's done

**Pull request merged**
