### PR TITLE
Fix html template structure with classes, divs & tags

### PR DESCRIPTION
**Pull request by mukeshcompucorp**
Overview
----------------------------------------
This PR 
- adds approripate classes and tags
- makes indentation proper

Screenshots
----------------------------------------
No Visual Changes

### CODE REVIEW

**Comment by colemanw** [comment]
@mukeshcompucorp that's odd - the diff makes a reference to shoreditch.?

**Comment by mukeshcompucorp** [comment]
Not all though, I'm just preserving standardization when something is not right and I have a template file open I fix it.

**Comment by colemanw** [comment]
@mukeshcompucorp click over to the "Files Changed" tab in this PR. There is a reference to Submodule org.civicrm.shoreditch added at ea48cd" I don't know what that means but it isn't just template changes.

**Comment by mukeshcompucorp** [comment]
@colemanw thanks, wrong commit I will amend and let you know

**Comment by mukeshcompucorp** [comment]
@colemanw Fixed the commit now

**Pull request merged**
