### PR TITLE
Shifted UpdateMemberhsip to BAO Layer

### PR DESCRIPTION
**Pull request by kartik1000**
Signed-off-by: Kartik Kathuria <kathuriakartik0@gmail.com>

Overview
----------------------------------------
This is in addition to https://github.com/civicrm/civicrm-core/pull/16677 . The PR is based on shifting updateMembership function to BAO Layer CRM_Member_BAO_Membership as it is supposed to be a BAO layer function.

### CODE REVIEW

**Comment by kartik1000** [comment]
@eileenmcnaughton, Please Look if it seems ok to you.

**Comment by eileenmcnaughton** [comment]
@kartik1000 aha - you have encountered our style checker! The link to details above will take you through. Our coding standards are here - https://docs.civicrm.org/dev/en/latest/standards/ 

(sadly we decided before the rise of PS2)

**Comment by kartik1000** [comment]
@eileenmcnaughton Can I incorporate this coding standard in phpStorm?

**Comment by eileenmcnaughton** [comment]
Yes - you can download the config file - but I think these days if you have the drupal plugin in phpstorm it kinda does the lifting

**Comment by eileenmcnaughton** [comment]
sometimes our ci gives false negatives - which is what those look like - I'll kick the tests to run again

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by kartik1000** [comment]
@eileenmcnaughton, It would be great if you can merge this as soon as possible, because The Next PR is dependent on this. As it uses static call to the update membership function.

**Comment by eileenmcnaughton** [comment]
I went through the same more & was able to get the same result - merging

**Pull request merged**
