### PR TITLE
CRM-18983. MySQL fatal error on 4.7.8 upgrade due to excess key length.

### PR DESCRIPTION
**Pull request by xurizaemon**
- [CRM-18983: CiviCRM DB error on 4.7.8 upgrade](https://issues.civicrm.org/jira/browse/CRM-18983)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test fails look related.

I don't know it helps here but this method https://github.com/civicrm/civicrm-core/commit/3fe26f4c79333858f85824b35360e08558680af3 will cope with already-existing indexes

**Comment by xurizaemon** [comment]
👍  to doing schema changes from PHP, but was amending the existing work from CRM-17967 where this came from.

Something to document in the developer docs? Are there good reasons to accept PRs which do schema changes in .sql (and thus fail a bit harder)?

**Comment by eileenmcnaughton** [comment]
yes please to documenting that  - it's fairly new functionality but I can't think of a case where it is NOT better

**Comment by seamuslee001** [comment]
Also now that there is the method i have created in the schemahandler class which checks if a specific column for a table already exists makes sense to run things from PHP

**Comment by kenahoo** [comment]
Is this the code that's going to be part of 4.7.10?  I want to upgrade to 4.7.9 as soon as I can, but I don't want to end up with a subtly different schema than 4.7.10 is expecting.

**Comment by eileenmcnaughton** [comment]
I looks like it's pending a rebase & some QA. The update will need to be adapted to make sure existing DBs are not 'disadvantaged' by it

Unless you have a large DB it probably won't matter since running that change will make for a slow upgrade on a large DB- but otherwise you might wind up with it running on more than one upgrade & it won't really matter.

If your key length is longer than it needs to be I wouldn't expect any problems - CiviCRM doesn't 'know about' that at run timeI looks like it's pending a rebase & some QA. The update will need to be adapted to make sure existing DBs are not 'disadvantaged' by it

Unless you have a large DB it probably won't matter since running that change will make for a slow upgrade on a large DB- but otherwise you might wind up with it running on more than one upgrade & it won't really matter.

If your key length is longer than it needs to be I wouldn't expect any problems - CiviCRM doesn't 'know about' that at run time

**Comment by monishdeb** [comment]
I need to make some changes and fix a additional issue occurring due to length change raised in https://issues.civicrm.org/jira/browse/CRM-19100. So closing this PR in favor of https://github.com/civicrm/civicrm-core/pull/8722

**Pull request closed without merging**
