### PR TITLE
[NFC] dev/core#1046 - minor consistency change

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
Doesn't change anything, just removes some inconsistency in variable naming and will make a bigger PR smaller.

### CODE REVIEW

**Comment by alifrumin** [comment]
@demeritcowboy I can review this next week.

**Comment by demeritcowboy** [comment]
Thanks @alifrumin !

**Comment by alifrumin** [comment]
@eileenmcnaughton this change just moves from using the variable name display**l**abel to display**L**abel 

It is a non functional change that improves consistency I believe this is ready to be merged.

**Comment by mattwire** [comment]
Merging based on @alifrumin review

**Pull request merged**
