### PR TITLE
dev/financial/issues/24, Add unit test for Link payment method to financial account when created using api

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
.https://lab.civicrm.org/dev/financial/issues/24

Before
----------------------------------------
No test

After
----------------------------------------
test

### CODE REVIEW

**Comment by pradpnayak** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@pradpnayak this PR is a unit test only - no other changes. I've updated the PR to reflect that & am merging it but I think you might have intended some further change to go in?

**Comment by pradpnayak** [comment]
@eileenmcnaughton  I was little surprise to see 'All checks have passed'  when i expected it to fail since i had not pushed code to fix it(which i have now at #12388 ). When i looked at https://test.civicrm.org/job/CiviCRM-Core-PR/21301/console i couldn't see the test was actually being executed. @eileenmcnaughton do you have a sense why  api_v3_OptionValueTest are not executed?

**Comment by eileenmcnaughton** [comment]
@pradpnayak - it's there when I expand to full log

```
ok 1195 - api_v3_OptionValueTest::testGetCount
ok 1196 - api_v3_OptionValueTest::testGetOptionValueByID
ok 1197 - api_v3_OptionValueTest::testGetOptionValueByValue
ok 1198 - api_v3_OptionValueTest::testGetOptionValueLimit
ok 1199 - api_v3_OptionValueTest::testGetOptionValueOffSet
ok 1200 - api_v3_OptionValueTest::testGetSingleValueOptionValueSort
ok 1201 - api_v3_OptionValueTest::testGetValueOptionPagination
ok 1202 - api_v3_OptionValueTest::testGetOptionGroup
ok 1203 - api_v3_OptionValueTest::testGetOptionGroupByName
ok 1204 - api_v3_OptionValueTest::testGetOptionDoesNotExist
ok 1205 - api_v3_OptionValueTest::testCreateOptionSpecifyDomain
ok 1206 - api_v3_OptionValueTest::testCreateOptionSpecifyComponentID
ok 1207 - api_v3_OptionValueTest::testCreateOptionSpecifyComponentString
ok 1208 - api_v3_OptionValueTest::testGetOptionWithComponent
ok 1209 - api_v3_OptionValueTest::testCRM12133CreateOptionWeightNoValue
ok 1210 - api_v3_OptionValueTest::testCreateOptionNoName
ok 1211 - api_v3_OptionValueTest::testCRM11876CreateOptionPseudoConstantUpdated
ok 1212 - api_v3_OptionValueTest::testUpdateOptionValueNoGroupId
ok 1213 - api_v3_OptionValueTest::testUpdateOptionValueWithGroupId
ok 1214 - api_v3_OptionValueTest::testCreateOptionValueWithSameValue
ok 1215 - api_v3_OptionValueTest::testCreateOptionValueWithSameValueLanguagesException
ok 1216 - api_v3_OptionValueTest::testCreateOptionValueWithSameValueDiffOptionGroup
ok 1217 - api_v3_OptionValueTest::testCreateUpdateOptionValueForPaymentInstrument
```

**Comment by Civiware** [comment]
@eileenmcnaughton Won't $this->callAPISuccessGetValue() throw error if the result is empty? I got below output for this function call
```
Array
(
    [count] =&gt; 0
    [is_error] =&gt; 1
    [error_message] =&gt; Expected one EntityFinancialAccount but found 0
    [xdebug] =&gt; Array
        (
            [peakMemory] =&gt; 46098416
            [memory] =&gt; 44229984
            [timeIndex] =&gt; 102.21802306175
        )

)
```
But test didn't fail. Will i need to throw error explicitly if the api throws error?

**Comment by eileenmcnaughton** [comment]
@Civiware  - are you @pradpnayak ?

**Comment by eileenmcnaughton** [comment]
@Civiware @pradpnayak - looks like there IS an issue in the test class - check the extra handling in 'getsingle'

```
  /**
   * This function exists to wrap api getsingle function & check the result
   * so we can ensure they succeed & throw exceptions without litterering the test with checks
   *
   * @param string $entity
   * @param array $params
   * @param array $checkAgainst
   *   Array to compare result against.
   *   - boolean
   *   - integer
   *   - double
   *   - string
   *   - array
   *   - object
   *
   * @throws \Exception
   * @return array|int
   */
  public function callAPISuccessGetSingle($entity, $params, $checkAgainst = NULL) {
    $params += array(
      'version' => $this->_apiversion,
    );
    $result = $this->civicrm_api($entity, 'getsingle', $params);
    if (!is_array($result) || !empty($result['is_error']) || isset($result['values'])) {
      throw new \Exception('Invalid getsingle result' . print_r($result, TRUE));
    }
    if ($checkAgainst) {
      // @todo - have gone with the fn that unsets id? should we check id?
      $this->checkArrayEquals($result, $checkAgainst);
    }
    return $result;
  }

  /**
   * This function exists to wrap api getValue function & check the result
   * so we can ensure they succeed & throw exceptions without litterering the test with checks
   * There is a type check in this
   *
   * @param string $entity
   * @param array $params
   * @param string $type
   *   Per http://php.net/manual/en/function.gettype.php possible types.
   *   - boolean
   *   - integer
   *   - double
   *   - string
   *   - array
   *   - object
   *
   * @return array|int
   */
  public function callAPISuccessGetValue($entity, $params, $type = NULL) {
    $params += array(
      'version' => $this->_apiversion,
      'debug' => 1,
    );
    $result = $this->civicrm_api($entity, 'getvalue', $params);
    if ($type) {
      if ($type == 'integer') {
        // api seems to return integers as strings
        $this->assertTrue(is_numeric($result), "expected a numeric value but got " . print_r($result, 1));
      }
      else {
        $this->assertType($type, $result, "returned result should have been of type $type but was ");
      }
    }
    return $result;
  }
```

**Comment by pradpnayak** [comment]
@eileenmcnaughton Won't $this->callAPISuccessGetValue() throw error if the result is empty? I got below output for this function call
```
Array
(
    [count] =&gt; 0
    [is_error] =&gt; 1
    [error_message] =&gt; Expected one EntityFinancialAccount but found 0
    [xdebug] =&gt; Array
        (
            [peakMemory] =&gt; 46098416
            [memory] =&gt; 44229984
            [timeIndex] =&gt; 102.21802306175
        )

)
```
But test didn't fail. Will i need to throw error explicitly if the api throws error?

**Comment by pradpnayak** [comment]
I replaced getvalue with getsingle and pushed commit at https://github.com/civicrm/civicrm-core/pull/12388/commits/d1b701c0ac07548245e69f144bbb236b12aca737

**Comment by eileenmcnaughton** [comment]
I was thinking we could 'fix' getvalue...

**Comment by pradpnayak** [comment]
@eileenmcnaughton I have created separate PR to fix getvalue at https://github.com/civicrm/civicrm-core/pull/12573

**Pull request merged**
