### PR TITLE
Update participant import to work on updates (with participant ID)

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Update participant import to work on updates (with participant ID)

Before
----------------------------------------
This must have broken in 5.51 when the field got renamed to 'id' from 'participant_id' but code was not adusted

After
----------------------------------------
works & has test

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
@eileenmcnaughton can you rebase this pls?

**Comment by eileenmcnaughton** [comment]
ok - rebased & passing

**Comment by johntwyman** [comment]
@eileenmcnaughton I've patched 5.72.0 with this PR and run through a very simple participant import (one record).

Provided I selected "Update" for "On Duplicate Entries", I was able to select "Participant ID" in the field mapping step.

The data imported correctly and the existing participants were updated.

With "Skip" selected for "On Duplicate Entries", I was unable to select "Participant ID" at all.

With no checking selected, I was able to select "Participant ID" but the import (correctly) failed as an existing record was found.

**Comment by eileenmcnaughton** [comment]
merging based on @johntwyman review

**Pull request merged**
