### PR TITLE
CRM-20955 - Allow contact's second membership to inherit when created…

### PR DESCRIPTION
**Pull request by davejenx**
… in back end using price set.

### CODE REVIEW

**Comment by KarinG** [comment]
We have had the 4.6 equivalent of this patch in production for months now - and it solved a lot of issues.

**Comment by davejenx** [comment]
This is the 4.7 equivalent of #9520 .

Note that this issue masks [Contribution deleted when relationship deleted, incorrect line items & membership_payments for second inherited membership created in back end via price set](https://issues.civicrm.org/jira/browse/CRM-20966) so fixing this issue, allowing inheritance to work, paves the way for that issue to occur. I've submitted PRs #10759 (4.7) & #10760 (4.6) for that.

**Comment by monishdeb** [comment]
@davejenx is there any unit test coverage for this fix?

**Comment by davejenx** [comment]
@monishdeb I haven't written a unit test, I'm not sure how to do that to simulate creating a pair of memberships in the back end using a price set.

**Comment by monishdeb** [comment]
@davejenx here is an example https://github.com/civicrm/civicrm-core/pull/10726/files#diff-3cd3f80dd69269a09e1d88996ce92f6fR719 where I have created a price-set that consist of a checkbox price-field and each price-option hold different membership type (id as 15 and 35). In your case you can add similar CRM unit test in ```tests/phpunit/CRM/Member/Form/MembershipTest.php``` 

 Ping me if on Mattermost dev channel (alias - @monish) if you need help with test setup.

**Comment by davejenx** [comment]
@monishdeb Great, thanks for that. I'm not able to work on this immediately but would like to get a unit test together. Will let you know how I get on.

**Comment by monishdeb** [comment]
Cool 😄👍

**Comment by lcdservices** [comment]
I've tested and confirmed this functionality. Tested in conjunction with PR-10759. Additional testing comments in CRM-20966.

**Comment by davejenx** [comment]
@lcdservices Great, thanks for testing!

**Comment by colemanw** [comment]
Better in than out. But @davejenx a followup PR with a test would be most welcome :)

**Comment by davejenx** [comment]
@monishdeb @colemanw Follow-up PR with unit tests for this + for CRM-20966 / #10759: #11184.

**Pull request merged**
