### PR TITLE
CRM-19496 Fix removing and re-adding contacts from the groups tab on …

### PR DESCRIPTION
**Pull request by seamuslee001**
…contact record

### CODE REVIEW

**Comment by seamuslee001** [comment]
@Edzelopez Edsel thanks for testing and spotting this, I think this will fix the adding removing from group from the group tab.

**Review by colemanw — APPROVED** [review]
Works as advertised.
But I don't understand why it regressed; it was certainly working before.

**Comment by BorislavZlatanov** [comment]
@seamuslee001 Hi. I'm not sure I really understand the parameters checking in the code, but I just encountered the "Cannot Delete GroupContact" error on a contact with a Pending status. Does your patch cover the Pending status as well? Thanks.

**Comment by seamuslee001** [comment]
@BorislavZlatanov I'm not 100% sure it does. I would try applying this patch and then testing again if it doesn't work then need some follow up work

**Comment by BorislavZlatanov** [comment]
@seamuslee001 Yeah, I'm running 4.7.14 and your patch is applied there. The error happens when the contact has a Pending status for the group.

Any ideas on how to change the patch to make it work for a Pending status as well?

**Comment by seamuslee001** [comment]
hmmm maybe, I'll give it a shot so contact is pending status in group x and are you trying to delete that record or just "remove" them from the group?

**Comment by BorislavZlatanov** [comment]
@seamuslee001 Right, contact has Pending status for a group (which is a newsletter list). The "Cannot Delete GroupContact" error happens when trying to either Delete or Remove the contact from the group.

**Pull request merged**
