### PR TITLE
Standardise what we pass to tokenProcessor so we don't have to add specific handling in each class for actionSchedule

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Currently when implementing an entity for tokenProcessor we have to try two different ways of getting the parameters - depending on if we were invoked via actionschedule (scheduled reminders) or via a "standard" tokenProcessor context (eg. activity search -> print document / emailapi extension with tokenprocessor (https://lab.civicrm.org/mattwire/emailapi/-/tree/newtokenprocessor)).

This PR modifies the parameters passed by actionschedule to be "standard" so that we can simplify the entity classes for tokenProcessor. Here, the work has been done for activities.

Also note the example - switching over the actionschedule token selector to use tokenProcessor to retrieve the list of activity tokens - as that is what is actually available to be processed!

Before
----------------------------------------
Two sets of parameters to check.

After
----------------------------------------
Just one set of parameters.

Technical Details
----------------------------------------
Explained above in overview.  `getEntityTableToSchemaMapping()` function is not necessarily in the right place - we need a way of mapping from entity table to the context version - ideas welcome!

Comments
----------------------------------------
@eileenmcnaughton @aydun Be great if you have time to look at this as it will help with moving forward with the tokenProcessor more quickly!

### CODE REVIEW

**Comment by aydun** [comment]
@mattwire I haven't tested, but I like the intention.  In my earlier work around this I mostly left the actionschedule stuff alone but simplifying this should make it easier to use tokenProcessor more widely.

**Comment by mattwire** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I've started looking at this but I'm not too familiar with the code. I clarified the dispatch change & did this https://github.com/civicrm/civicrm-core/pull/17154

**Comment by mattwire** [comment]
test this please

**Comment by mattwire** [comment]
test this please

**Comment by mattwire** [comment]
test this please

**Comment by mattwire** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I'm going to close this because it's stale & it's probably stalled until @totten is able to give some attention to this & related PRs. (I tried but eventually failed to get my head around the token processor plan so this is out of my wheel house)

**Comment by eileenmcnaughton** [comment]
@mattwire looks like you are still actively working on this - obviously the test issues need to be resolved before it's review ready - but you probably also want to connect with @totten on this because I think he is the only one who feels comfortable reviewing token processor related PRs (there are a few in the queue)

**Comment by eileenmcnaughton** [comment]
Note the existing test fails indicate we have test cover - but I don't know if this code approach fits the vision or not

**Comment by eileenmcnaughton** [comment]
| No changes.
-- | --
  | GitHub pull request #16983 of commit 8c29c5b163a234abc3272eeda38685534ab515c2, no merge conflicts.
  | Checkstyle: 0 warnings from one analysis.No warnings since build 1,916.New zero warnings highscore: no warnings for 2,002 days!
  | Test Result (45 failures / +45)CRM_Mailing_TokensTest.testTokensWithMailingId with data set #0CRM_Mailing_TokensTest.testTokensWithMailingId with data set #1CRM_Mailing_TokensTest.testTokensWithMailingId with data set #2CRM_Mailing_TokensTest.testTokensWithMailingId with data set #3CRM_Mailing_TokensTest.testTokensWithMailingId with data set #4CRM_Mailing_TokensTest.testTokensWithMailingId with data set #5CRM_Mailing_TokensTest.testTokensWithoutMailingJob with data set #0CRM_Mailing_TokensTest.testTokensWithoutMailingJob with data set #1CRM_Mailing_TokensTest.testTokensWithMailingObjectCivi.Token.TokenProcessorTest.testAddRowShow all failed tests >>>

**Comment by eileenmcnaughton** [comment]
I'm going to close this for now as the failing tests are long-standing. Please re-open when it's review ready (although it might be worth discussing with @totten first)

**Comment by mattwire** [comment]
test this please

**Comment by magnolia61** [comment]
Hi @mattwire I cannot review code quality but what could I do to help you test this PR? What testscenario's would I help you with?

**Comment by mattwire** [comment]
@magnolia61 The most important thing is that there is no change before or after this PR. Both contact and activity tokens should continue to work with schedule reminders with and without this PR applied so validation of that would cover the `r-run` part of the review.

**Comment by seamuslee001** [comment]
@mattwire we need some more explanation for why and we need to see this approved in gitlab first.

**Comment by mattwire** [comment]
> `This PR modifies the parameters passed by actionschedule to be "standard" so that we can simplify the entity classes for tokenProcessor. Here, the work has been done for activities.`

@seamuslee001 The explanation is simple. Currently there are two different ways of passing params to tokenProcessor. This PR reduces that to one.

I appreciate that this does require someone with better knowledge of the tokenProcessor like @totten or @aydun to review but currently any work on improving the tokenProcessor system is basically stalled on this PR. The only thing I would say needs "concept approval" is "do we want one unified way or two different ways of initiating tokenProcessor" - the answer to that would seem obvious?

**Comment by MegaphoneJon** [comment]
@mattwire This is the same issue as [CRM-19758](https://issues.civicrm.org/jira/browse/CRM-19758), correct?  The issue that's worked around in [this PR](https://github.com/twomice/com.joineryhq.reltoken/pull/9).

If so, I think you'd get a pretty strong "concept approved" from myself, @twomice, and we can probably even get @xurizaemon to cast a vote :).  Also see [this commit](https://github.com/xurizaemon/civicrm-core/commit/90539237365ec9ebf36b703116108d50ac79135c).

**Comment by twomice** [comment]
Agreed, I like the concept, and it seems silly to require extensions and other token consumers to check the format of the token params; seems an obviously good idea to pass params in a consistent format. So concept approval from me: yes. Unfortunately I don't know much about the tokenProcessor internals, so must leave that to someone else.

**Comment by eileenmcnaughton** [comment]
OK - people seem to understand what it's doing so I've switched the labels back - to be honest the 'needs-concept-approval' was more 'is this the right technical approach'

**Comment by aydun** [comment]
@mattwire This makes sense to me from reading the changes and looks ok to merge.

**Pull request closed without merging**
