### PR TITLE
Pcp api

### PR DESCRIPTION
**Pull request by alar77**
This minimal api for Personal Campaign Pages only implements get.
I noticed that the standard create for PCP attempt to create a record in civicrm_pcp_block. Understanding why in order to be able to change this behaviour is beyond the scope of this project

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
We actually have multiple PRs open to add this api (#9012 #9017 #7878) . #7878 stalled failing tests. I took a look and concluded some BAO changes would resolve that #8697 but no-one came back to that PR & reviewed / tested them so they never got merged & hence #7878 stalled.

I suspect if I get the tests to run you will see the same fails here

**Comment by eileenmcnaughton** [comment]
(NB if you wish to review / test any others please add notes as to what you have checked / tested)

**Comment by ggargani** [comment]
I had a look over all the PR and looks like the issue is in the non standard naming of PCP AND the add method weirdness (addressed by PR #8697).
My workadound was to only implement the get method which is working enouigh to support the extension I wrote.

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@ggargani did you test / review #8697 to the point where we can merge it - once that is merged I think the rest is simplified....

**Comment by ggargani** [comment]
I reviewed #8697 and it looks fine, going to merge it in my fork and test it a bit today.

**Comment by eileenmcnaughton** [comment]
great!

**Comment by ggargani** [comment]
Checked.
It basically works but I had to change class CRM_PCP_DAO_PCP &fields function, too.

The change is actually minimal:

// line 171
// from
        'pcp_id' => array(
//to
        'p_c_p_id' => array(
but this class is automatically generated, so I suppose the generator is to be patched in ordered to cope to the non standard "PCP" name.
I dont think I have the time to check and understand the whole code generation thing, so.. who could do that?

**Comment by eileenmcnaughton** [comment]
hmm - that issue is specific to the new api rather than the #8697  patch in general? I feel like that issue got solved in one of the other PRs at one point

**Comment by eileenmcnaughton** [comment]
I think the answer is on #7878 - a fix / hack at the api layer allows the fn to be pcp_get instead of p_c_p_get ...http://civicrm.stackexchange.com/questions/3030/incoporating-pcps-in-wordpress/3037#3037 -

**Comment by ggargani** [comment]
The issue is that an error is raised in civicrm/api/v3/Generic.php line 111 (_civicrm_api3_generic_getfields_) when it validates fields.
Changing the api name is not the solution (i attempted id),  because the hunt for p_c_p_id when field validation happens is due to the odd name of the table. 
#7878 (if I understand it) merely allow calling function _civicrm_api3_pcp_*_ instead of _civicrm_api3_p_c_p_*_ and still finding the correct BAO/DAO classes, but this could also be done explicitly passing the correct name instead of using __civicrm_api3_get_BAO(__FUNCTION__)_

**Comment by eileenmcnaughton** [comment]
Did you look at that thread from the comment thread on there... 

"There's some odd line of hyphens at the bottom, leave that off! Next, in civicrm/api/v3/util.php, you should see a part that looks like:

  // FIXME: DAO names should follow CamelCase convention
  if ($name == 'Im' || $name == 'Acl') {
    $name = strtoupper($name);
  }
Change that "if" statement to:

  if ($name == 'Im' || $name == 'Acl' || $name == 'Pcp') {"

**Comment by seamuslee001** [comment]
@ggargani @eileenmcnaughton I have fixed the field issue it was found by Jon but never committed I have pushed fixes to Eileen's PR and made a PR for a pcp api that is more complete IMO https://github.com/civicrm/civicrm-core/pull/9045

**Comment by ggargani** [comment]
I dont see unit test in your commit. I removed the create and delete from my implementation because without PR #8697  (allow create api to actually creare a pcp row instead a pcp_block one) and a fix for the undefined index error due to the field validation routines(civicrm_api3_generic_getfields,_civicrm_api3_build_fields_array for example), looking for p_c_p_id as unique name (instead of pcp_id as  defined in DAO), we cant successfully run the create test.
The solution is probably around AllCoreTables

**Comment by seamuslee001** [comment]
@ggargani I have updated #8697 I have fixed it by changing api/api.php and api/v3/utils.php to conform 

I ran the syntax conformance tests which auto included my version of the PCP api and they all passed with my amendment to Eileen's PR. Once Eileen's PR.

**Comment by eileenmcnaughton** [comment]
Hi,

This PR is getting blocked before the unit tests actually start - on a style issue - see 

https://test.civicrm.org/job/CiviCRM-Core-PR/11616/checkstyleResult/new/

There are some tests in the SyntaxConformanceTest class that will provide some coverage although it is MUCH preferred to have a specific unit test as well

**Comment by ggargani** [comment]
Messed something with rebase, will resubmit a clean pull request

**Comment by ggargani** [comment]
Resubmitted a cleaner patch built against the last master: #9045

**Pull request closed without merging**
