### PR TITLE
Mailing - Rename DAO files for better short names

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
REF - renaming needed to be able to add these entities to APIv4.

### CODE REVIEW

**Comment by colemanw** [comment]
retest this please

**Comment by eileenmcnaughton** [comment]
The volume of changes here makes it impossible to go through line by line but

- using a class alias to phase out a bad class name is a method we have already deployed on several `DAO`
- test cover on the DAO's themselves is solid
- I spot checked a few of the find & replaces - & the methodology of find & replace means they should be all changed in the same way

@colemanw I think the alias classes should have a deprecation doc block as a follow up

**Comment by colemanw** [comment]
Thanks @eileenmcnaughton will do

**Comment by colemanw** [comment]
FYI the bulk of the diff in this PR was generated by PHPStorm's "Refactor: Rename Class" feature, which I think does a better job of renaming usages throughout the codebase because it's based on static code analysis not just regex.

**Comment by eileenmcnaughton** [comment]
yeah - go phpstorm

**Comment by colemanw** [comment]
@eileenmcnaughton one more change I'm tempted to make is:

- `MailingEventDelivered` => `MailingEventDeliver`
- `MailingEventOpened` => `MailingEventOpen`

Nowhere else in CiviCRM do we conjugate verbs in the past-tense so it's jarringly incongruous to my eye.

:+1: :-1: ?

**Comment by eileenmcnaughton** [comment]
@colemanw I think it's more important to match the table name

**Pull request merged**
