### PR TITLE
[dev/core#1879] .ical files not populating correctly for sites with ACL's configured for events

### PR DESCRIPTION
**Pull request by alifrumin**
Overview
----------------------------------------
see https://lab.civicrm.org/dev/core/-/issues/1879

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Can you give a little more info on the details for setting up the ACL because I tried the patch and then logged in as a user in the group the ACL applied to, and then tried to download the ical and it was still mostly empty. Does it depend on specific ACL settings?

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I'd feel better with a test.....

**Comment by alifrumin** [comment]
With this ACL (Everyone can edit the fall fundraiser): 

acl

When logged in as an administrator with permissions to edit/view all events, ical files for events that do not have an ACL look like:

ical

even though this test event has a start and end date which should appear in the ical file.

@eileenmcnaughton I will work on a test.

**Comment by eileenmcnaughton** [comment]
@alifrumin I  couldn't replicate this - but you might be able to build on https://github.com/civicrm/civicrm-core/pull/18038

**Comment by alifrumin** [comment]
Thank you @eileenmcnaughton!!!

**Comment by alifrumin** [comment]
@eileenmcnaughton this works for me!!! I tested it and this fixes the bug documented in https://github.com/civicrm/civicrm-core/pull/18712. I will close the other pr in favor of this one.

**Comment by alifrumin** [comment]
Closing in favor of Eileens fix.

**Pull request closed without merging**
