### PR TITLE
Migrate KAM smartmenus to core

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Ports the KAM extension into CiviCRM core.

Before
----------------------------------------
Extension required to get the new smartmenus-based menubar.

After
----------------------------------------
New smartmenus-based menubar included with core. KAM and Slicknav extensions marked obsolete.

### CODE REVIEW

**Comment by colemanw** [comment]
The KAM extension has gone through a month's-long period of review & refinement. At this point it's been tested on all the CMSs with a wide variety of settings. I believe it's time to merge it into master so it will be part of next month's RC.

FYI @JoeMurray @aydun @monishdeb @mattwire @vingle @christianwach @themak1985 @laryn @artfulrobot

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by seamuslee001** [comment]
@colemanw this needs a rebasing now

**Comment by colemanw** [comment]
@civicrm-builder retest this please

**Comment by monishdeb** [comment]
Awesome. Will start with D8 and D7 and its accessibility behavior as listed in https://lab.civicrm.org/dev/accessibility/issues/1.  I also like to invite others to review this patch, as this is a big improvement towards Civi Menu and patch be should be scrutinized on all aspects. @colemanw should I mention this PR in dev channel?

**Comment by monishdeb** [comment]
@colemanw isn't the patch should include the packages.json commit to include the smartmenu library?

**Comment by colemanw** [comment]
@monishdeb - very strange that when I typed `bower install smartmenus` it did not update the `bower.json` file. I've now done it manually.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by colemanw** [comment]
I think this PR is a bit daunting for one person to want the responsibility of being the one to press the Merge button. But it has received extensive testing as an extension.
I'd like to get it merged into the RC so it can get more eyes on it before the release.
@totten would you be willing to merge this based on a quick code review? There is a functional change to the way `addCoreResources` works (it now accepts fully-formed URLs).

**Comment by colemanw** [comment]
@civicrm-builder retest this please.

@eileenmcnaughton what additional work is needed? FYI I have already rebased in the recent bug fixes from the KAM extension.

**Comment by eileenmcnaughton** [comment]
@colemanw my understanding is that this will be a big problem if we merge this before updating shoreditch - also I would err towards merging straight after the rc is cut to give it max review time

**Comment by colemanw** [comment]
I'm ok with bumping this back one more release & merging next week. But I'm less concerned about Shoreditch as there is already [a PR in the works](https://github.com/civicrm/org.civicrm.shoreditch/pull/364) on that side, and this would just be one of several breaking changes to core that have been released lately (another being https://github.com/civicrm/org.civicrm.shoreditch/pull/356)

**Comment by eileenmcnaughton** [comment]
@colemanw ah that one too huh? What is the status with the shoreditch sprint - I feel like a goal of that sprint should be that this is tested with shoreditch & given the 'merge-ready' flag

**Comment by mattwire** [comment]
> I feel like a goal of that sprint should be that this is tested with shoreditch & given the 'merge-ready' flag

Kind-of.  As @colemanw says there are already a few breaking changes in core as far as the shoreditch extension is concerned and outstanding PRs for the extension.  The KAM menu actually works well with shoreditch already (I'm using it on all my production sites) and I don't think anything in the shoreditch extension should be seen as a blocker to this PR being merged - in fact I think this PR needs merging before changes are merged in the shoreditch extension - so the minversion on shoreditch can be bumped to the release containing this PR and we can rip out various bits that support old versions of Civi.

**Comment by eileenmcnaughton** [comment]
@mattwire OK - that's a reasonable case - ie a bunch of work is being done on shoreditch - now-ish? so it would be better if this was merged for that to be done against....

Do you think we should just merge this now & deal with anything that comes out of it?

**Comment by mattwire** [comment]
> Do you think we should just merge this now & deal with anything that comes out of it?

I would say so, it's had pretty good user testing as an extension.  I'm sure there will be one or two issues that pop up but we're not going to find them until it's merged.  And, we've just had a security release so there are likely to be less forced upgrades to the next version (ie. more time for issues to be found).

**Comment by eileenmcnaughton** [comment]
@mattwire OK - I'll take your advice on it - I guess one thing is that this will be well tested as EVERYONE uses the menu - so devs should be giving it a good bash over the next 6 weeks

**Pull request merged**
