### PR TITLE
WIP Add metadata to display preferences settings definition

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Follow up to #12714 This adds metadata and translatable strings to the settings definitions for display preferences 

Before
----------------------------------------
Descriptions and html_type missing.  Most strings not translatable.

After
----------------------------------------
Descriptions and html_type present.  Most strings translatable.

Technical Details
----------------------------------------

Comments
----------------------------------------
@eileenmcnaughton These are the bits that were left after rebasing

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire OK cool. I was hoping to make sure that we are not duplicating descriptions when we do this & that we have got the various data types working in the trait - even if we don't do every single one

**Comment by mattwire** [comment]
Ref https://github.com/civicrm/civicrm-core/compare/master...mattwire:preferences_display_tometadata for template cleanup

**Comment by eileenmcnaughton** [comment]
@mattwire I think I merged some of these so rebasing can drop a few out & then we can merge a few more fields.

I'm currently seeing enotices on some related forms (event settings) & looking at them

**Comment by eileenmcnaughton** [comment]
Also I like where you are going with using the filters - I think we need to complete getting things out of $_VarNames & into setting first - so all handling will be done in the Setting Trait

**Comment by eileenmcnaughton** [comment]
I'm closing this - I think all these are picked up elsewhere & if there are any left once all is merged the form & metadata will need to be altered in tandem.

**Pull request closed without merging**
