### PR TITLE
CRM-15821 Provide option to notify PCP owner

### PR DESCRIPTION
**Pull request by NileemaJadhav**

### CODE REVIEW

**Comment by kurund** [comment]
add to whitelist

**Comment by davecivicrm** [comment]
PR has gone stale and I'd like to do QA tomorrow. Can you rebase please? (Sorry for delay.)

**Comment by NileemaJadhav** [comment]
Updated the PR for CiviCRM 4.6alpha4 upgrade and done with rebase

**Comment by davecivicrm** [comment]
I've posted a QA report on the issue on Jira with a few bugs / changes needed. However, the functionality is generally working so I'm going to merge this PR.

**Pull request merged**
