### PR TITLE
dev/core#1270 - fix email processor dropping attachments - ALTERNATE

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
This is an alternate to https://github.com/civicrm/civicrm-core/pull/15344

https://lab.civicrm.org/dev/core/issues/1270

The email processor will drop attachments if there's more in the incoming email than the limit set at system settings - misc. The setting is intended for activity creation in the UI, but shouldn't cause the email processor to drop attachments.

Before
----------------------------------------
Some attachments can be lost.

After
----------------------------------------
It files and keeps all the attachments.

Technical Details
----------------------------------------
Adds a new admin setting for non-UI processes parallel to the existing max_attachments setting which is then only used for UI processes.

Comments
----------------------------------------
Unfortunately the existing max_attachments setting seems to be in limboland where it currently has a hack, so to add the new setting I copied that. I'm not sure that's desired.

@pfigel

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Hmm, regarding test failure looks like I might have used something php 7.2-ish. Remembering now that tests run on 7.0. Fixing...

**Review by pfigel — APPROVED** [review]
Thanks @demeritcowboy, this LGTM! I'm not sure if I can make an educated judgment on the setting hack, but I'd be okay with it, so leaving that to the merger 😁.

For more details on the rationale behind adding a new setting, see the discussion starting [here](https://github.com/civicrm/civicrm-core/pull/15344#issuecomment-538777871).

* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) __PASS__: Explains the rationale behind why a new setting is needed/preferred.
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) __PASS__: User would expect attachments not to be dropped.
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) __PASS__: New setting is sufficiently described, old setting has been amended to make the difference clear.
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) __PASS__: I've verified that:
      * The bug is fixed (i.e. up to 100 attachments are created)
      * The setting form works
      * Attachment limits aren't affected in the UI
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) __PASS__: 
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) __PASS-ISH__: I'm uncertain about the setting hack, but wouldn't be opposed to merging as I don't see a trivial alternative and it doesn't really make things worse.
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) __PASS__: Adds tests
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) __PASS__

**Comment by seamuslee001** [comment]
Makes sense to me merging

**Comment by demeritcowboy** [comment]
Thanks! @pfigel @seamuslee001

**Pull request merged**
