### PR TITLE
Wysiwyg support for i18n event field - Confirmation Email Text

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
Add Wysiwyg text editor for "Confirmation Email Text"

BEFORE
--------
before

AFTER
-------
after

Followup of https://github.com/civicrm/civicrm-core/pull/14384 

ping @colemanw @seamuslee001

### CODE REVIEW

**Comment by mlutfy** [comment]
Hi Monish, is this the same as #13976 ? Could you provide before/after information?

Personally I would be very much in favour of having WYSIWYG for this field, but I think we have to handle upgrades?

From the other PR, Eileen had commented:

> does this change how the text is saved (ie. add html tags to it). I feel like we tried something like this before & there was some gotchas

**Comment by eileenmcnaughton** [comment]
I note that this field is in event_offline_receipt_text.tpl & currently we would not save the <p> markers. If we switch to rich text we will do so & they will look 'odd' - in the html version we see
```
  {if !empty($event.confirm_email_text) AND (empty($isOnWaitlist) AND empty($isRequireApproval))}
     <p>{$event.confirm_email_text|htmlize}</p>
    {/if}
```

Note that the upgrade script in https://github.com/civicrm/civicrm-core/pull/20867 is designed to update specific strings where a token has changed. The different between this and the main template upgrade script is it will assume the specific string should always be swapped & do it on customised as well as default templates (which makes sense here I think)

**Comment by mlutfy** [comment]
Related: https://lab.civicrm.org/extensions/richtext/-/tree/master

(although I still support changing this in core, it's a frequent request)

**Comment by demeritcowboy** [comment]
This has merge conflicts and hasn't been worked on in several months, so going to close but feel free to reopen.

**Pull request closed without merging**
