### PR TITLE
CRM-19443 backport to 4.6

### PR DESCRIPTION
**Pull request by ghost**
* [CRM-19443: date tokens not using format settings when doing print\/merge](https://issues.civicrm.org/jira/browse/CRM-19443)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@agileware 

Error: PHP Fatal error:  Call to undefined method CRM_Utils_String::endsWith() in /home/jenkins/buildkit/build/core-9750-4y991/sites/all/modules/civicrm/tests/phpunit/CRM/Member/Form/Task/PDFLetterCommonTest.php on line 80"

**Comment by agileware** [comment]
New commit to fix the test.  Hopefully there isn't anything else 4.7 specific in there :/

**Comment by agileware** [comment]
jenkins test this please

**Comment by jackrabbithanna** [comment]
small detail here, but the comment block for the test file says 4.7 and should be 4.6

**Comment by agileware** [comment]
@jackrabbithanna when you're doing the 4.6 PR cleanup, can you re-check this one too. Should be good to go. Cheers.

**Comment by jackrabbithanna** [comment]
Candidate for merging

**Comment by jackrabbithanna** [comment]
Merging #9750

**Pull request merged**
