### PR TITLE
[NFC] Fix camelCase variable name following fix for dev/core#1435

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
Fixes camel casing issue pointed out by @aydun and @yashodha 

ping @mattwire @eileenmcnaughton

### CODE REVIEW

**Review by jusfreeman — CHANGES_REQUESTED** [review]
@seamuslee001 can you just use the same name as retrieved, rather than introduce a different name in the variable?

So do this:
**$memberId** = CRM_Utils_Request::retrieve('memberId', 'Positive', $this);

Instead of this:
_$membershipId_ = CRM_Utils_Request::retrieve('memberId', 'Positive', $this);

Just keeps things simple.

**Comment by eileenmcnaughton** [comment]
Hmm my version of keeping things simple is aligning everything with the field name which I thought about doing last patch - ie $contribution_membership_id.

I would say this change is 'better in than out'

**Comment by eileenmcnaughton** [comment]
@seamuslee001 style issue

**Comment by seamuslee001** [comment]
sorted @eileenmcnaughton

**Pull request merged**
