### PR TITLE
(WIP) Auto-activate classes that support HookInterface (et al)

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

`HookInterface` and `EventSubscriberInterface` provide a way for classes to listen for events. 

```php
class Foo implements \Civi\Core\HookInterface {
  public static function hook_civicrm_foobar($foo, $bar) { ... }
}

class Foo implements EventSubscriberInterface {
  public static function getSubscribedEvents() {
    return ['hook_civicrm_foobar' => 'onFoobar'];
  }

  public static function onFoobar($event) { ... }
}
```

This update makes it easier for extensions to use these interfaces. It also has to fix a related issue with extensions are activated/deactivated during testing.

(Note: This is an off-shoot of #23854 and depends upon it.)

Before
----------------------------------------

Classes like `Foo` are autoloaded in some limited scenarios - eg BAOs and headless tests.

It's maybe possible to manually register using some mix of `dispatcher()`, `hook_container`, `EventScanner`.

After
----------------------------------------

Classes like `Foo` are autoloaded from extensions, if they enable class scanning (#23854).

```xml
<!-- FILE: myextension/info.xml -->
<mixins>
  <mixin>scan-classes@1.0.0</mixin>
</mixins>
```

Comments
----------------------------------------

There is test coverage in `mixin/scan-classes@1/example`.

This is WIP because:

* Need a new test-run to see if the drafted fix for the phpunit-harness issue works.
* Need to add EventSubscriberInterface
* Need to test/consider what (if anything) is needed for the previous integration between headless-tests and HookInterface. (Don't want them to register at runtime...)

### CODE REVIEW

**Comment by colemanw** [comment]
@totten just noting that this implementation does not appear to be backward compatible, e.g. the work is done by core and there is no mixin shim allowing an extension to fake it on an older version. Maybe that's ok because we tell extension devs they must declare a minimum core version in the `info.xml` file in order to use the mixin? But it's not the way other mixins work so might be confusing?

**Comment by totten** [comment]
@colemanw Yup, that's accurate. In keeping, civix's metadata for `scan-classes@1.0.0` says both [`minimum=>5.51` and `provided-by=>5.51`](https://github.com/totten/civix/blob/master/mixin-backports.php#L61) (*ie no backporting*).

My attitude at the time of #23854 (*which added `scan-classes@1.0.0` to 5.51*) was influenced heavily by:

1. `WorkflowMessageInterface` and `ExampleDataInterface` -- basically, if you use these interfaces, then you need other runtime functionality (patches for `sendTemplate()`, `GenericWorkflowMessage`, `ExampleDataLoader`). If we add more `interface`s in the future, then they will also need runtime support. (*By definition, an `interface` is not complete functionality.*) The `interface`s shapes your choice of `<compatibility>`.
2. `ManagedEntities` (*analogy*) -- when writing an extension with a managed-entity, you can use `mgd-php@1` - but you also need to consider the specific API `Entity` (since new entities/actions/fields are introduced over time). We don't expect to backport the various entities/actions/fields. (That is another factor that shapes your choice for `<compatibility>`.)

OTOH, the `HookInterface` has existed for a while (*5.48, 5.39, or 4.7 - depending on which aspect you look to*), so backporting is feasible. You just need the class scanner. That's what my initial experiments were like (*[example](https://github.com/totten/shimmy/blob/master/mixin/auto-listen%400.1.mixin.php)*).

So it is possible to make something that loads `HookInterface`s on older versions of core. I guess it could be something like this:

* `scan-classes@1.0.0` stays as-is (it's already published)
* `scan-classes@1.1.0` is a heavier file with more compatibility (eg `minimum=>5.48`) -- if you deploy on a newer Civi, it behaves like `1.0.0`. If you deploy on an older Civi, then it polyfills the `HookInterface` stuff.  This version is only used for backports/civix.
* `scan-classes@1.2.0` is a lighter file (*basically, the same as 1.0.0*). This is included with newer versions of core.

That does add some more complexity, and I guess it didn't seem worthwhile since I had no immediate plans to incorporate `HookInterface` in any civix templates.

I would note though... even if this PR doesn't support backports... we could still do the 1.0.0 => 1.1.0 => 1.2.0 switcheroo in the future (when/if it feels that backporting is important)...

**Comment by colemanw** [comment]
@totten I think it's fine since you've marked [minimum=>5.51](https://github.com/totten/civix/blob/master/mixin-backports.php#L61) that makes it clear enough.

**Comment by totten** [comment]
The issue description had a couple "WIP" bullets:

> * Need to add EventSubscriberInterface
> * Need to test/consider what (if anything) is needed for the previous integration between headless-tests and HookInterface. (Don't want them to register at runtime...)

Those two bullets had a similar challenge:

* Simply scanning for `EventSubscriberInterface` may catch classes intended for other subsystems or other setup flows. We don't know or control the lifecycle of all `EventSubscriberInterface`s.
* The headless-tests scan for the same interfaces (`HookInterface`, `EventSubscriberInterface`), but the classes must be loaded/activated differently. (Ex: You have 50 test-classes that define hooks. You don't want to activate all of them at the same time. You want to pick one and activate it for the duration of its own test-case -- no more, no less.)

Additionally, there was another issue with this branch (not identified in the description) -- it was geared toward `static` methods with no attention to object-methods. If you had a service-object, the object would not receive methods in the intuitive fashion.

Solution? Be clearer about the intended lifecycle for your class.  #24276 adds another flag (`AutoService`) to indicate the lifecycle. This requires a small change in usage:

```diff
--- PR#23877
+++ PR#24276
-class Foo implements HookInterface {
+class Foo extends AutoService implements HookInterface {
```

As a fringe benefit, #24276  provides a path to decomposing `Civi\Core\Container::createContainer()`.

**Pull request closed without merging**
