### PR TITLE
CRM-18311 Revert "Fix for CRM failure"

### PR DESCRIPTION
**Pull request by JKingsnorth**
This reverts commit a50d7d84b5970e26261fe3134a10c7f91dcb5e56.

---
- [CRM-18311: Merging does not overwrite values (regression, data problem)](https://issues.civicrm.org/jira/browse/CRM-18311)

### CODE REVIEW

**Comment by JKingsnorth** [comment]
This test failure is unrelated. Need to check out:
CRM_Dedupe_MergerTest

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by JKingsnorth** [comment]
Unless I'm misreading the test failure I can't see the relevance of it. My test rig is broken so I can't run the CRM_Dedupe_MergerTest at the moment :/

**Comment by eileenmcnaughton** [comment]
the test this please was an instruction to Jenkins to re-test it :-)

**Comment by JKingsnorth** [comment]
Yeah indeed, but Jenkins doesn't run that test as part of the PR suite so
I'll need to run it manually unless you could do the honours Eileen?

**Comment by JKingsnorth** [comment]
Jenkins, re-test this please

**Comment by JKingsnorth** [comment]
Ack a _different_ and still unrelated-looking test failure...

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by JKingsnorth** [comment]
The CRM_Dedupe_MergerTest is failing on dmaster at the moment (with CiviDiscount installed) so I'll try to fix up the test and then look into how this patch affects the tests too.

**Comment by JKingsnorth** [comment]
@eileenmcnaughton I think that test is failing during the createMergeActivities methods - is that something you're actively working on as part of [CRM-18105](https://issues.civicrm.org/jira/browse/CRM-18105)

**Pull request merged**
