### PR TITLE
Crm 16617 master

### PR DESCRIPTION
**Pull request by pradpnayak**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Unrelated fail @colemanw this seems Ok to me on a quick peek - it's assigned to you for QA

**Comment by xurizaemon** [comment]
As of now, this patch and #6707 are identical patchfiles. Review comments over on #6707 so far.

**Comment by colemanw** [comment]
@pradpnayak can you take a look at the comments from @xurizaemon

**Comment by colemanw** [comment]
jenkins, retest this please

**Pull request merged**
