### PR TITLE
remove crm_util_api class v1

### PR DESCRIPTION
**Pull request by mallezie**
Followup for https://issues.civicrm.org/jira/browse/CRM-16089
and for https://github.com/civicrm/civicrm-core/pull/5357

This will need codestyle checking, and further discussion.

### CODE REVIEW

**Comment by mallezie** [comment]
I went through all classes found with rgrep addSelect CRM/*/Form* -li
Fixed only the necessary ones. I didn't change the ones which explicitly defined their entity, some classes wheren't clear to me. 

For example in CRM/SMS/Form/Group.php:
```
$mailing = new CRM_Mailing_DAO_Mailing();
$mailing->id = $mailingID;
$mailing->addSelect('name');
$mailing->find(TRUE);
```
Here the addSelect is set on a DAO class, which is another issue AFAIK. 
I manually checked all the changed forms.

**Comment by colemanw** [comment]
yes the `CRM_Core_DAO->addSelect` method is different from `CRM_Core_Form::addSelect` - glad you figured that out.

**Comment by colemanw** [comment]
This looks great.
I think you also want to remove `public $entityName` from CRM_Core_Form.

**Comment by mallezie** [comment]
Nice catch! Updated, now i hope the testbot get's happy, but he's kind of busy today ;-)

**Comment by colemanw** [comment]
BTW @totten's argument has compelled me to see the usefulness of a getter function so I'm behind this PR all the way. When tests pass I'll merge it.

**Comment by colemanw** [comment]
@mallezie I'm not sure if you are as excited as me about the possibility of a `CRM_Core_Form::addField` function, but in case you are and want to have a crack at it:

- The fn signature would be pretty much the same as `addSelect`
- After resolving the $entity and $field it would call `civicrm_api3($entity, 'getfields')` to load the field's metadata (aside, maybe we need to add an api "getfield" action to make it easier to fetch a single field).
- Depending on the html type it would call `CRM_Core_Form::add` with appropriate options.
- Once implemented I think all calls to `addSelect` could be swapped for `addField` and probably that function could be deleted.

**Comment by mallezie** [comment]
@colemanw that sounds a great idea, and a nice challenge, i'm expecially excited it should make all fields consistent in the end, which would be a great win, (no more sometimes select, otherwise select2, ...). I'm gonna give it a try in the coming days / week.

**Comment by mallezie** [comment]
@colemanw lets start here https://issues.civicrm.org/jira/browse/CRM-16130

**Comment by colemanw** [comment]
@mallezie yep sounds perfect.

**Pull request merged**
