### PR TITLE
CRM-21771: error when viewing event registration with linked contribu…

### PR DESCRIPTION
**Pull request by jitendrapurohit**
…tion

Overview
----------------------------------------
Fix fatal error on View Event Registration Page.

Before
----------------------------------------
Fees section displays fatal error when the event page is viewed.

image

After
----------------------------------------
Fees section loads correctly with participant payment details.

Comments
----------------------------------------
Added unit test.

---

 * [CRM-21771: error when viewing event registration with linked contribution](https://issues.civicrm.org/jira/browse/CRM-21771)

### CODE REVIEW

**Comment by yashodha** [comment]
@jitendrapurohit  Can you give exact steps to replicate?
I created an event with associated payment and it shows properly
sc

http://dmaster.demo.civicrm.org/civicrm/contact/view/participant?reset=1&id=51&cid=203&action=view&context=participant&selectedChild=event&key=57a9a28c600c9daeb2181bbc9a9d892a_8325

**Comment by jitendrapurohit** [comment]
Hmm, the only reason I can think of why it is not replicating on the demo is the participant id would also exist as a contribution in the database.

For eg: in the above case, there would be a contribution existing in the DB with id = 51 which is actually a participant id. This makes the code bypass the `getsingle` API exception and returns the function without errors.

If you look at the unit test, I've considered `$this->_participantID4` in order to assert the function correctly. If the participant id is replaced by `$this->_participantID` - the unit test passes without any errors.

So, to replicate this, the participant we are creating should have the id not present in `civicrm_contribution` table.

**Comment by yashodha** [comment]
@jitendrapurohit yes, can confirm that it works.

**Comment by yashodha** [comment]
looks good to merge

**Comment by magnolia61** [comment]
didnt this make it into 4.7.31 as a last minute fatal error preventor?

**Comment by seamuslee001** [comment]
@magnolia61 Richard it was just merged into 4.7.31 just now this PR was against master

**Comment by magnolia61** [comment]
Thank you Seamus!

**Pull request merged**
