### PR TITLE
Afform - support relationships

### PR DESCRIPTION
**Pull request by colemanw**
Overview
--------------
Supports creating and updating relationships between contacts.
See https://lab.civicrm.org/dev/core/-/issues/3117

### CODE REVIEW

**Comment by samuelsov** [comment]
@colemanw Is there a dependency on another PR ? I have this error when I try to create a form in my instance:

`Error: Call to undefined method Civi\AfformAdmin\AfformAdminMeta::getAfformEntity() in Civi\AfformAdmin\AfformAdminMeta::getFields() (line 128 of .../web/sites/all/modules/civicrm/ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php).`

Indeed, I can't find the definition of `getAfformEntity()` in the PR or in the core code.

**Comment by colemanw** [comment]
@samuelsov I think the branch got out of sync with master so master + the patch wasn't working.
I've rebased this PR. Can you try again?

**Comment by samuelsov** [comment]
@colemanw Sorry no luck in my instance and I have the same problem in the automated build http://core-23296-1pts7.test-3.civicrm.org:8001

**Comment by colemanw** [comment]
@samuelsov ok I fixed it. It was a refactoring conflict with another PR.
Should be working now :)

**Comment by samuelsov** [comment]
@colemanw Great, very promising! I have done a few tests and I see nothing that should prevent from merging if you prefer being iterative.

My main issue is i'd like to pass the first contact id and load the relationships and other contacts from this single id. In update mode, I would expect the form to load the contact passed in url and then load all its relationships without having to pass the relationships ids in the url. It could be tricky though and I think we could exclude this from the scope of the current PR.

Deduplication doesn't seems to work either so if we submit the form with the same data, it will create duplicates so this is problematic.


Other than that, I have only seen one bug:

I get this error in the console if the relationship definition is not in the same way as the relationship type definition: `Possibly unhandled rejection: {"error_code":0,"error_message":"Invalid Relationship"}`
 
This works:
Screenshot 2022-05-05 at 15-54-03 Form Builder Form with multiple relationship core-23296-1wh93
 
But not this:
Screenshot 2022-05-05 at 15-52-55 Form Builder Form with multiple relationship core-23296-1wh93
 
Seems logical but we should forbid the second or allow for the other way `Employer is` relationship.

**Comment by seamuslee001** [comment]
@colemanw I think the above improvements from @samuelsov can be tackled in a follow up PR. As such am going to merge this

**Pull request merged**
