### PR TITLE
SearchKit - add/remove tags action for all taggable entities

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds a new angular-based action to SearchKit for bulk adding/removing tags from contacts, cases, activities, etc.

Before
----------------------------------------
Non-angular quickform popup for tagging, only works for contacts.

After
----------------------------------------
New single form handles tags and tagests for any taggable entity.

image

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
This PR is still ready for review.

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
I tested this and seems to work fine MOP

**Pull request merged**
