### PR TITLE
Allow 'Expires' placeholder text to be translated

### PR DESCRIPTION
**Pull request by braders**
Overview
----------------------------------------
Allow 'Expires' placeholder text to be translated.

Before
----------------------------------------
Text was hardcoded in English.

After
----------------------------------------
Text is passed through `ts()` function.

### CODE REVIEW

**Comment by colemanw** [comment]
Thanks for this @braders - unfortunately there is an underlying issue with the AngularJS widget that does not correctly interpret these tags before rendering. I think it's a boot order issue, I see the same problem with the placeholder attribute on the `crm-ui-select` widget as well:

image

**Comment by mlutfy** [comment]
Should we remove the placeholder, if it cannot be translated?

**Comment by demeritcowboy** [comment]
These have failed twice so probably real:

```
crmMailingRadioDate.crmMailingRadioDate crmMailingRadioDate directive should update the UI after changing the model
Error: Expected n({ length: 0, prevObject: n({ 0: <form name="myForm" class="ng-valid ng-scope ng-valid-required ng-dirty ng-valid-parse">...</form>, length: 1 }), context: undefined, selector: '.crm-form-date' }) to be null. Tip: To check for deep equality, use .toEqual() instead of .toBe().
    at <Jasmine>
    at UserContext.<anonymous> (tests/karma/unit/crmMailingRadioDateSpec.js:53:68)
    at <Jasmine>

crmMailingRadioDate.crmMailingRadioDate crmMailingRadioDate directive should update the model after changing the date and time 
Error: Expected null to be '2014-01-03'.
    at <Jasmine>
    at UserContext.<anonymous> (tests/karma/unit/crmMailingRadioDateSpec.js:141:30)
    at <Jasmine>
```

**Comment by demeritcowboy** [comment]
It's being stubborn:

```
Error: No deferred tasks to be flushed
    at self.defer.flush (bower_components/angular-mocks/angular-mocks.js:193:13)
    at $delegate.flush (bower_components/angular-mocks/angular-mocks.js:2388:20)
    at UserContext.<anonymous> (tests/karma/unit/crmMailingRadioDateSpec.js:142:16)
    at <Jasmine>
```

But taking a step back to the earlier comment about just removing it, we can't just do that because there is no label for this field so without the placeholder it's just a blank field. But even with the placeholder, I don't actually know what this field does. Why would a searchkit expire? What does that mean - there is no enable/disable - does it delete itself after that date? Maybe a meaningful label or help text instead of a placeholder?

**Comment by demeritcowboy** [comment]
Ok you've beaten it into submission, but now the problem is if you fill out the expires field it appears to save the searchkit but doesn't. Checking if that's pre-existing...

**Comment by colemanw** [comment]
> now the problem is if you fill out the expires field it appears to save the searchkit but doesn't

Hmm, I'm not seeing that locally. Is that reproducible in the demo site?

**Comment by demeritcowboy** [comment]
Yes just go new searchkit, then go to the settings tab and fill in expires, then click save.

**Comment by colemanw** [comment]
> Yes just go new searchkit, then go to the settings tab and fill in expires, then click save.

@demeritcowboy Ok, just did, and http://core-30971-3y8w6.test-1.civicrm.org:8003/civicrm/admin/search#/edit/15 looks to have saved correctly, with the expiration date I gave it (tomorrow).

**Comment by demeritcowboy** [comment]
Oh ok I think the problem then is if you enter a past date, there's no error it just ignores you and appears to save but doesn't.

**Pull request merged**
