### PR TITLE
CRM-21202, set retrieve = true so that its not reinitialized again an…

### PR DESCRIPTION
**Pull request by pradpnayak**
…d just want the DataTable instance to be returned

----------------------------------------
* CRM-21202: DataTables warning: table id=dupePairs
  https://issues.civicrm.org/jira/browse/CRM-21202

Before
----------------------------------------
multipleediterror

### CODE REVIEW

**Comment by pradpnayak** [comment]
@colemanw can you please review this for us?

**Comment by colemanw** [comment]
Test failure is unrelated.

**Comment by pradpnayak** [comment]
jenkins, retest please

**Comment by pradpnayak** [comment]
Jenkins retest this please

**Comment by seamuslee001** [comment]
Jenkins retest this please

**Comment by elisseck** [comment]
@colemanw Just tested this out - Confirmed I see the datatables warning as posted in JIRA by following steps outlined there (Create a couple of duplicate contacts, use a generic dedupe rule to find them, select them for batch merge), and no longer get the warning after this patch.

It does not appear to affect functionality at all (batch merge works as expected both before the patch if you click through the message and ignore it, and after the patch).

**Pull request merged**
