### PR TITLE
RiverLea: 1.2.2-5.81 - fixes four regressions, one visual change

### PR DESCRIPTION
**Pull request by vingle**
Overview
----------------------------------------
This PR fixes four regressions:
 - RL hadn't yet integrated the rendered Radio Button fix
 - Selected Rows in SearchKit tables are illegible in Walbrook
 - Select2 accordions didn't work and showed expanded.
 - Tags on contact dashboard don't wrap
In addition a visual change was made (still getting used to the multi-branch workflow). Strictly speaking this should go into `master` not the RC, but as we're still in the RL test period and it's a minor change hopefully it's ok.
 
Before: 1.2.0-5.81.beta
----------------------------------------

Select2 accordions:

image

Select in SK table:

image

Visual change - giant alert for 'no items' in table:

image

After: 1.2.1-5.81.beta
----------------------------------------
Select2 accordions:

image
image

Select in SK table:

image

Visual change - smaller alert for 'no items' in table 
(NB - while there is a contrast ratio issue in the action buttons on the right - these buttons shouldn't be used anyway because this UX is to apply actions to multiple rows):

image

Technical Details
----------------------------------------
1.2.2-5.81beta
 - FIXED - major regression introduced in 1.2.1-5.81beta around Select2 sub-results: https://lab.civicrm.org/extensions/riverlea/-/issues/11#note_174883
 - FIXED - contact dashboard tags didn't wrap: https://lab.civicrm.org/extensions/riverlea/-/issues/97

1.2.1-5.81beta
 - FIXED - integrated this fix to rendered radio buttons: https://github.com/civicrm/civicrm-core/pull/31345
 - FIXED - text colour on selected rows illegible: https://lab.civicrm.org/extensions/riverlea/-/issues/94#note_174585
 - FIXED - accordions inside Select2 now work. Some small tidying of Select2 list borders/padding.
 - CHANGED - reduced size of 'not found' alerts in SearchKit tables: https://github.com/civicrm/civicrm-core/pull/31605

### CODE REVIEW

**Comment by vingle** [comment]
Major regression in the original PR (1.2.1), superseded here with 1.2.2 - fixes a further smaller regression.

**Comment by colemanw** [comment]
@vingle ideally a PR shouldn't contain merge commits. Are you able to remove them?

**Comment by vingle** [comment]
@colemanw - I don't know how to do that, sorry.

**Comment by colemanw** [comment]
@vingle it's done with a rebase. The command would be
```
git pull --rebase origin master
git push -f
```
Don't worry, if anything goes wrong it's simple enough to restore as the commit history is also stored in this PR.

**Comment by vingle** [comment]
@colemanw well, that didn't go great. I think I managed to rebase my 5.81 branch to master, and now this PR has all of master in it.

**Comment by ufundo** [comment]
I do this every time :)

You could try `git rebase -i origin/5.81` - will show a list of commits, delete the ones you dont want, then close and save (and say a quick prayer)

**Comment by vingle** [comment]
Thanks @ufundo :)

I actually got that far, thanks to your previous instructions, but now I'm unable to push to my remote:

```
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
(which makes sense as my remote - https://github.com/vingle/civicrm-core/tree/5.81 - is 60 commits ahead)

I then created a new branch 5.81b naïvely hoping this be an empty place I could push my local changes to and make a new PR to replace this one but no joy `error: src refspec 5.81b does not match any. error: failed to push some refs to 'https://github.com/vingle/civicrm-core'`

**Comment by vingle** [comment]
OK - I think this is back to normal.

**Pull request merged**
