### PR TITLE
Metadata - Refresh clientside resources when clearing cache

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Ensures available user roles are always up-to-date (full fix).

Before
----------------------------------------
After saving a user role it is not immediately available for use.

After
----------------------------------------
Fixed.

Comments
-----
This builds on the partial fix from #28422 and the event added in #28428.

### CODE REVIEW

**Comment by colemanw** [comment]
@wmortada can you r-run please?

**Comment by wmortada** [comment]
Tested and can confirm that this works.

Without the PR, when you create/delete a new role, the list of roles isn't always updated.

With these changes the list of roles is updated as soon as they are changed.

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
retest this please

**Comment by colemanw** [comment]
retest this please

**Comment by totten** [comment]
@colemanw Test now passes. But I notice the last commit sounds uncertain. Still MOP?

**Comment by colemanw** [comment]
Yea that commit was a scattershot. I've narrowed it down and rebased. Still don't know exactly what was wrong with that one line but left a comment for posterity.

**Pull request merged**
