### PR TITLE
Eliminate unnecessary calculations and conversions when setting the minDate and maxDate

### PR DESCRIPTION
**Pull request by kzalewski**
Overview
----------------------------------------
This PR is simply an optimization to the setting of the date picker minDate and maxDate variables.  This eliminates two of the three calls to `date()` and it eliminates both of the calls to `strtotime()`.

Before
----------------------------------------
Prior to this optimization, the minDate was being calculated by subtracting the minYear from the current year to get the year offset, then converting that year offset to a string.  The string is then fed into `strtotime()` to calculate the Unix timestamp of the minimum date.  That Unix timestamp is then converted to YYYY-MM-DD format.  A similar calculation was performed for the maxDate.

After
----------------------------------------
Since the minYear and maxYear are already known, there is no need to convert them to year offsets, only to convert them back to YYYY-MM-DD dates.  This optimization uses the minYear and maxYear as is, and appends the current month and day as "-MM-DD".

Technical Details
----------------------------------------
This is a simple and straightforward optimization.

Comments
----------------------------------------
n/a

### CODE REVIEW

**Comment by seamuslee001** [comment]
@kzalewski Jenkins doesn't quite like the coding style

```
FILE: /home/homer/buildkit/build/build-2/web/src/CRM/Utils/Date.php
----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
 2070 | ERROR | [x] Concat operator must be surrounded by a single
      |       |     space
 2073 | ERROR | [x] Concat operator must be surrounded by a single
      |       |     space
----------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

Time: 233ms; Memory: 28MB
```

**Comment by kzalewski** [comment]
@demeritcowboy I squashed the two commits (original commit and code style commit) into a single commit and force-pushed it back up.  Please let me know if I need to do anything else.

**Comment by demeritcowboy** [comment]
Perfect.
It looks like this is your first PR here? For release notes credit can you do a separate PR to add yourself to https://github.com/civicrm/civicrm-core/blob/master/contributor-key.yml?

**Comment by colemanw** [comment]
Thanks @kzalewski for your contribution!

**Pull request merged**
