### PR TITLE
Add format type to Case Start and End Dates

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
An "Undefined index: formatType" error prevents updating these fields properly- added a format type for these two values.

Replaces https://github.com/civicrm/civicrm-core/pull/13000

https://lab.civicrm.org/dev/core/issues/467

Before
----------------------------------------
before

After
----------------------------------------
after

Comments
----------------------------------------
Tested by @ray-wright with feedback "- the fields are now usable and update in the manner you'd expect them to."

### CODE REVIEW

**Comment by mattwire** [comment]
@eileenmcnaughton Good to merge.  #13000 has been reviewed and the only thing holding it up was the DAO needing to be regenerated properly, which you've done.

**Comment by eileenmcnaughton** [comment]
thanks @mattwire

**Comment by eileenmcnaughton** [comment]
@ray-wright I was able to keep you in the commit message :-)

**Comment by ray-wright** [comment]
@eileenmcnaughton awesome!! My first contribution to core! Thanks @mattwire as well for help understanding how the DAO was generated.

**Pull request merged**
