### PR TITLE
Add searchkit and afform display

### PR DESCRIPTION
**Pull request by m-hobby**
Overview
----------------------------------------
Adds afform / searchkit display to replace 'Headers Footers and Automated Messages' in menu.

Before
----------------------------------------
Interface not using searchkit / afform
28484-hft

After
---------
Interface now using searchkit /afform
28484-hft-sk

Comments
--------
Clicking on any edit link - say Mailing Footer - (http://wpcvmaster.local:8080/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Fcomponent&action=update&id=2&reset=1)  generates a popup.  

The popup is new, and it may be  a beter UX to open in full screen as before.

### CODE REVIEW

**Comment by 19ATF72** [comment]
jenkins retest please

**Comment by kcristiano** [comment]
test this please

**Comment by kcristiano** [comment]
r-run notes.

I also applied https://github.com/civicrm/civicrm-core/pull/28472  - which is in Draft mode.  I'll come back and re-test

Before

28484-hft



After

28484-hft-sk

Clicking on any edit link - say Mailing Footer - (http://wpcvmaster.local:8080/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Fcomponent&action=update&id=2&reset=1)  generates a popup.  

The popup is new, and it may be  a beter UX to open in full screen as before.

However,  the popup is not the message template, but it is the same listing

image


The URL I get on the existing edit link (no admin UI) is (http://wpcv.local:8080/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Fcomponent&action=update&id=2&reset=1)  as these URLs look identical,  I am unsure of what the issue really is.

**Comment by kcristiano** [comment]
retested after https://github.com/civicrm/civicrm-core/pull/28472  was updated - as expected same issue with edit links.

**Comment by 19ATF72** [comment]
retest this please

**Comment by 19ATF72** [comment]
Hi @kcristiano, I have pushed 2 other PRs that have now been merged that fix this issue. 
I am able to properly edit the templates in the test environment created.
Can you have a look?
Thanks

**Comment by kcristiano** [comment]
@19ATF72 Thanks

I have reviewed and r-run looks good.  test failures look unrelated.

**Comment by kcristiano** [comment]
test this please

**Pull request merged**
