### PR TITLE
[Smarty variables] Ensure groupElementType is always set

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Ensure groupElementType is always set

Before
----------------------------------------
Not always set

After
----------------------------------------
Set...

Technical Details
----------------------------------------
Removes as isset from smarty

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
test failures relates here @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
@seamuslee001 interestingly it fails locally on https://github.com/civicrm/civicrm-core/pull/22075 - not sure why my local seems less tolerant than the remove on the isset

**Comment by eileenmcnaughton** [comment]
Oh - of course - my local must have the define set - but for the remote this isn't merged yet https://github.com/civicrm/civicrm-core/pull/22070

**Comment by eileenmcnaughton** [comment]
now failing on https://github.com/civicrm/civicrm-core/pull/22076

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Pull request merged**
