### PR TITLE
SearchKit - Fix handling of new Custom EntityReference fields

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Includes the fix from #25914 plus the rest of the issues fixed and a test added.

Before
----------------------------------------
Custom EntityReference fields incorrectly appear to have option lists but no ability to join in SearchKit.

After
----------------------------------------
Option list mirage removed, joins fixed to function correctly and use correct labels. Test added.

Technical Details
----------------------------------------
Removes redundant function `SpecFormatter::customFieldHasOptions` which was completely identical to `CRM_Core_BAO_CustomField::hasOptions` except for one line which was incorrect.

### CODE REVIEW

**Comment by briennekordis** [comment]
Thanks @colemanw. I just tested this and it works for the most part, but if the EntityRef is to a Contact, the Display Name displays correctly, but the Contact Id does not. (This is not the case with other entities, for example Event Id displays just fine)

Selection_057

**Comment by briennekordis** [comment]
The results above are from testing on a civibuild site  running 5.61.alpha1. 
I just applied the patch to a dev site running 5.60.beta1, and when I add the custom EntityRef (to Contact) field in SearchKit, there is nothing returned (not, "none found", but white space below the columns, when just removing that EntityRef returns a row).


Selection_060

**Comment by colemanw** [comment]
@briennekordis I just tested on my own `5.60.beta1` environment and the fields all appear to work correctly, including the Contact ID field.

image

I'm not sure what's going on when you test on your site - can you confirm that you cleared caches after applying the patch and created a new SearchKit search from scratch?

I'm inclined to merge this since it fixes an unreleased bug and has a test, and then see if we can debug your specific issue - could you provide a screenshot of the "Query info" section when you run that search?

**Comment by MegaphoneJon** [comment]
@colemanw This wasn't properly tested, apologies.  I'll post a follow-up ticket to discuss.

**Pull request merged**
