### PR TITLE
extract two core API permission functions

### PR DESCRIPTION
**Pull request by ErichBSchulz**
This will enable a bit of discoverability for the entity x action
matrix and preps the code base for API4.

This is pretty much a cut and paste job so should be no functional
change.

### CODE REVIEW

**Comment by ErichBSchulz** [comment]
the kind of discoverability that this refactor enables: https://github.com/ErichBSchulz/api4/blob/autodocs/autodocs/permissions.md

**Comment by seamuslee001** [comment]
That is pretty cool Erich @colemanw @totten @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
@seamuslee001 I kind of skimmed this & thought ' oh yeah' & then thought I saw some conversation between @ErichBSchulz  & @colemanw about it that suggested it impacted on some hook - but I might be wrong. Do you think it is ready to merge or could there be 'something' that it affects?

**Comment by seamuslee001** [comment]
I like the idea but i'll let Coleman have a look at it and see what he thinks

**Comment by ErichBSchulz** [comment]
I was pretty careful not to impact on the hook... I lifted self contained components around either side

**Comment by totten** [comment]
+1, I think that big-static-datasets should be sequestered from logic.

The test suite passes. My interpretation is that (before and after the change) the `$permissions` data-structure is built anew during each call to ` _civicrm_api3_permissions()`, so it seems hard to imagine ill side-effects.

**Pull request merged**
