### PR TITLE
CRM-18191 CRM-19064 refactor bizareness from PCP create to enable api…

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
… fn.

This add function is really wierd & blocking writing an api for pcp - this will get past issues in #7878

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@PalanteJon - this PR should make your PCP api work properly

**Comment by ggargani** [comment]
I checked this patch against my pcp api ( #9012 ) 
It basically works but I had to change class CRM_PCP_DAO_PCP &fields function, too.
I dont know which is the best practice, should I submit a PR against this PR ?
The change is actually minimal:
```php
// line 171
// from
        'pcp_id' => array(
//to
        'p_c_p_id' => array(
```
in order to cope with the non standard PCP name (all uppercase instead of camel)

**Review by seamuslee001 — APPROVED** [review]
As long as tests pass I think this should be good to merge.

**Comment by eileenmcnaughton** [comment]
Added merge on pass per review by @seamuslee001  & @ggargani 

There is a follow up PR for the api

**Comment by ggargani** [comment]
Mayeb I am looking in the wrong place but I still dont see tests for the api

**Comment by seamuslee001** [comment]
test failure unrelated can be merged

**Comment by eileenmcnaughton** [comment]
@seamuslee001 are there api tests in the other PR - or just the SyntaxConformance ones?

**Pull request merged**
