### PR TITLE
dev/core#3000 Fix database error when copying custom data fields from…

### PR DESCRIPTION
**Pull request by seamuslee001**
… a master address to related addresses

Overview
----------------------------------------
This aims to fix the same problem that @MegaphoneJon  is in #22268 This uses the test that he wrote and but aims to fix it in an alternate way

Before
----------------------------------------
DB error when copying custom data across from master to related address

After
----------------------------------------
no DB error

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 should this be against the rc since it is a regression no?

**Comment by seamuslee001** [comment]
@eileenmcnaughton probably should be but would appreciate @MegaphoneJon 's feedback on this first

**Comment by eileenmcnaughton** [comment]
OK - please treat @MegaphoneJon's approval as 'merge on pass' on this issue - if the 2 of you agree something between you then I think that is enough to merge

**Comment by MegaphoneJon** [comment]
OK, I looked this over and agree it should be merged, either as-is or with minor changes.
* The original problem is that there are two places that call `CRM_Core_BAO_Address::copyCustomFields()`.   Adding `$hook` as a third param on [this line](https://github.com/civicrm/civicrm-core/blob/16332a761911a974bb1ac078b877c48f9a3657fe/CRM/Core/BAO/Address.php#L81) avoids the problem.  It'd be good to add this to the patch, but if you feel it's out of scope I'll submit a separate PR.
* I still think this PR makes sense as a more robust form of error handling.
* I'm pretty sure you can't manipulate `civicrm_custom_group.table_name` to have arbitrary input - but unless we're 100%, we should be escaping or parameterizing in this PR.

**Comment by seamuslee001** [comment]
Thanks @MegaphoneJon I have added the hook as the 3rd param in that line you pointed to in regards to the SQL I think it is safe there would be other places breaking if random things were being put into that table_name param see https://github.com/civicrm/civicrm-core/blob/2324bb1df4b84e60969a6096b04fbf1e18f2f7ca/CRM/Core/BAO/CustomValue.php#L196

**Pull request merged**
