### PR TITLE
info.xml - Allow multiple `<author>`s

### PR DESCRIPTION
**Pull request by totten**
Overview
----------------------------------------

Per https://lab.civicrm.org/dev/core/-/issues/2418, this expands the schema for `info.xml` to accept additional authors. The revised schema is designed to allow backward/forward compatibility and to match the semantics of [composer.json authors](https://getcomposer.org/doc/04-schema.md#authors).

ping @MikeyMJCO @mattwire @twomice 

Before
----------------------------------------

The `info.xml` can track one `<maintainer>`.

```xml
<maintainer>
  <author>Alice</author>
  <email>alice@example.org</email>
</maintainer>
```

After
----------------------------------------

The `info.xml` may still indicate a primary `<maintainer>`. This ensures compatibility with older versions of Civi and other parts of the distribution system. Additional authors (with roles and contact info) can be listed in `<authors>`, eg

```xml
  <authors>
    <author>
      <name>Bob</name>
      <email>bob@example.com</email>
      <homepage>https://example.com/bob</homepage>
      <role>Maintainer</role>
    </author>
  </authors>
```

Here's a longer example with multiple maintainers/authors.

```xml
  <maintainer>
    <author>Alice</author>
    <email>alice@example.org</email>
  </maintainer>
  <authors>
    <author><name>Bob</name><homepage>https://example.com/bob</homepage></author>
    <author><name>Carol</name><email>carol@example.org</email><role>Maintainer</role></author>
  </authors>
```

Note that they are combined into one list:

Screenshot from 2021-02-26 14-17-23

(Note: To control the order in display, just reorder the tags..)

Comments
----------------------------------------

If we update the other parts of the distribution system and wait a year, then we can deprecate `<maintainer>` in favor of the more flexible `<authors>`.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
I tested it & it works & is pretty straightforward. I'm happy to merge it after we have confirmed that someone is undertaking to update the documentation

**Comment by eileenmcnaughton** [comment]
Discussed with @MikeyMJCO who will follow up on the docs. Merging

**Comment by MikeyMJCO** [comment]
https://lab.civicrm.org/documentation/docs/dev/-/commit/23e89f1e8002ae1f93b59a95201fcdcd02e1b77c

**Pull request merged**
