### PR TITLE
Remove deprecated files from /bin

### PR DESCRIPTION
**Pull request by colemanw**

### CODE REVIEW

**Comment by colemanw** [comment]
This was originally prompted by @totten suggesting we remove the old gitify from core since there is a newer/better one in civicrm-buildkit. But then I spotted some other junk in /bin which seems to be doing nothing but collecting cobwebs.
Correct me if I'm wrong about any of them.

**Comment by seamuslee001** [comment]
@colemanw the only one i would be interested to know the impact of is being able to run a wget cron to mail civicrm_report as a csv attachement to an email. I think that uses the mail_report file your proposing to be deleted unless i am wrong

**Comment by colemanw** [comment]
Which file?

**Comment by seamuslee001** [comment]
@colemanw civiReportMail.php I am fairly sure. It maybe that it's only hit by wget crons to <civi URL>/cron.php

**Comment by colemanw** [comment]
Any script calling that would need to do something like

    require_once "bin/deprecated/CiviReportMail.php"

I can't grep anything like that in our codebase. Grepping for `bin/deprecated` also turns up nothing.

**Comment by seamuslee001** [comment]
Hey Coleman

You may be right i was just thinking of this style of calling https://forum.civicrm.org/index.php?topic=11401.msg96449#msg96449 but i think the job=xxx in the general cron.php call for wget calls have taken over but guess it might be worthwhile having it in the notes people need to check the cron calls if using wget

Seamus

**Comment by totten** [comment]
+1.

All of these are supposed to have equivalents in the API (Job.*). Going through the list, I couldn't find an analog to `UpdateMembershipReminderDate`, but the comments on `civicrm_api3_job_process_membership()` say, "*Sending renewal reminders has been migrated from this job to the Scheduled Reminders function as of 4.3.*"

It might worth noting somewhere that these are removed in 4.7 -- for lack of a better changelog, I'll put a note in http://wiki.civicrm.org/confluence/display/CRMDOC/API+changes

**Pull request merged**
