### PR TITLE
SearchKit - Add CiviMail integration

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Add a SearchKit task for "Email - schedule/send via CiviMail", similar to that in Advanced Search, etc.

Before
----------------------------------------
No convenient way to compose CiviMail directly from SearchKit.

After
----------------------------------------
Task will automatically create a hidden group (static, not smart group) and create a new mailing with it.

before

### CODE REVIEW

**Comment by monishdeb** [comment]
@colemanw I was testing the patch in the test build site http://core-22808-7ekai.test-1.civicrm.org:8001/ (admin / aDS90rFRafzZ) 

And after building a searchkit display when I choose "Email - schedule/send via CiviMail" action, on the popup screen I am only allowed to fill the Mailing name nothing else. I cannot proceed from that point: 
before

Am I missing something here?

**Comment by colemanw** [comment]
@monishdeb that's strange that you can't see the buttons at all.
When I test locally, the **Submit** & **Cancel** buttons are there, and they work.
When I test on the demo site you linked to, the buttons are there but they don't work (**Submit** is stuck as disabled)
But your screencast doesn't have any buttons.

There may be a dependency issue. I've rebased this PR so let's see if the new sandbox site works better.

**Comment by jaapjansma** [comment]
Test this please

**Comment by monishdeb** [comment]
I checked on my local and it works for me, heres screencast: 
before


However there are few issues on the new test build site http://core-22808-7sbsp.test-3.civicrm.org:8001 but I think its not blocker to get this PR merge.

**Comment by monishdeb** [comment]
@jaapjansma can you please ensure if this patch works for you too?

**Comment by jaapjansma** [comment]
* General standards
    * Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
        * __PASS__ : The goal/problem/solution have **not** been adequately explained in the PR. However it is quite user intuitive on what to do. 
    * User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
        * __PASS__: The change would be intuitive or unnoticeable for a majority of users who work with this feature.
    * Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
        * __ISSUE__: We have not checked the documentation but I believe that this new functionality so I assume it needs updates to the documentation as well. 
    * Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
        * __PASS__: We created a new contact search with search kit and and then created an email from the results.
* Developer standards
    * Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
        * __PASS__: The change preserves compatibility with existing callers/code/downstream.
    * Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
        * __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
    * Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
        * __PASS__: The change does not include tests however I believe the change is good enough to pass without a test.
    * Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
        * __PASS__: The test results are all-clear.

We believe that this PR is merge ready. However it needs attention when it comes to user documentation! @colemanw can you also add this functionality to the user documentation?

**Comment by TomCrawshaw** [comment]
@colemanw Hi, can you say when this CiviMail integration is likely to go on general release, please?

**Comment by colemanw** [comment]
@TomCrawshaw yes, it is part of version 5.49, which is the current beta, and will become the stable release in 3 weeks.

**Pull request merged**
