### PR TITLE
SearchKit - Rename crmSearchActions module to crmSearchTasks & add hook

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds `hook_civicrm_searchKitTasks()` to make it easy for other extensions to add tasks specific to SearchKit.
Also renames the module for consistency.

Before
----------------------------------------
No hook, difficult for other extensions to add tasks.

After
----------------------------------------
Extensions can add tasks.

Technical Details
----------------------------------------
The tasks added by the extension can contain a `module` key which will trigger it to be auto-loaded as a dependency of the `crmSearchTasks` module.

### CODE REVIEW

**Comment by colemanw** [comment]
@eileenmcnaughton this diff looks daunting but it's just because I renamed the module. The word "actions" is ambiguous and in core they're called "tasks".

**Comment by eileenmcnaughton** [comment]
OK I tested this & it works - yay. Changes are noisy due to name change, as you say

**Comment by eileenmcnaughton** [comment]
@colemanw - can you please check https://lab.civicrm.org/documentation/docs/dev/-/merge_requests/914

**Comment by aydun** [comment]
@colemanw I know this is already merged but looking at the rest of `GetSearchTasks::_run()` it would seem that `$entity`, or at least `$entity['name']` and `$entity['actions']` could be useful in implementations of `hook_civicrm_searchKitTasks` when deciding what tasks to add.  Do you agree?

**Comment by colemanw** [comment]
@aydun if you inspect the `$tasks` variable being passed to the hook it looks like:
```
$tasks = [
  'Contact' => [[...], [...], etc],
  'Participant' => [[...], etc],
];
```
so the idea is that hook subscribers can just add items to the array key of the entity they want. And PHP (which can be a PITA about undefined variables compared to the more lackadaisical javascript) actually works without complaining even if the key doesn't exist yet. So given the above array your hook could do `$tasks['FooBar'][] = [...]` and it will add the entity and the task to the array.

**Comment by colemanw** [comment]
Added some code comments in #20467

**Comment by aydun** [comment]
@colemanw Ah ok - those code comments are helpful.  I was looking at the conditionals in `_run()`: if contacts, add contact tasks; if contributions, add contribution tasks - and thinking hook implementations might want to do the same.  But I get your point about Angular dependencies.

**Pull request merged**
