### PR TITLE
rtrim when converting text tokens to html to avoid trailing newlines

### PR DESCRIPTION
**Pull request by larssandergreen**
Overview
----------------------------------------
Let's see what fails with this!

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@larssandergreen I wonder about 'just trim'?

**Comment by larssandergreen** [comment]
@eileenmcnaughton I guess if someone for some reason wanted white space at the start of whatever value, we should just let them do that unless there is a strong reason not to.

**Comment by eileenmcnaughton** [comment]
@larssandergreen I just wondered whether none would be more predictable. People would probably put the whitespace in the text? I suppose they might do a poor-man's-concat but we are supposed to start to support `{ }` to address that at some point (there is a gitlab somewhere)

**Comment by larssandergreen** [comment]
@eileenmcnaughton Maybe the best thing would be to keep it simple and just rtrim newlines only, which is what causes problems, and leave the rest as is - no visible change then.

**Comment by eileenmcnaughton** [comment]
OK

**Pull request merged**
