### PR TITLE
Add permission for users to view their own invoices

### PR DESCRIPTION
**Pull request by guanhuan**
https://issues.civicrm.org/jira/browse/CRM-16269

### CODE REVIEW

**Comment by guanhuan** [comment]
Hi @colemanw , could you advise?

**Comment by davecivicrm** [comment]
Click on '3 new warnings' - then Details tab for the specific style problems causing the test failure.
screen shot 2015-05-07 at 4 35 18 pm

**Comment by guanhuan** [comment]
Ah.. Did not realise you can check the details here. Thanks @davecivicrm .

**Comment by guanhuan** [comment]
jenkins, test this please

**Comment by davecivicrm** [comment]
Guanhuan - Conditional display of Invoice button works as expected. Thanks for formatting cleanup. FYI - this hasn't been fixed in many of the .tpl files, but the tab convention throughout CiviCRM is now 2 spaces, not 4 (for future reference).

**Pull request merged**
