### PR TITLE
Remove isset from custom data tpls

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Causing test fails https://test.civicrm.org/job/CiviCRM-Core-PR/45495/testReport/junit/(root)/CRM_Custom_Form_OptionTest/testEditCustomFieldOptionValue/

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
No idea....

+++ mkdir -p sites/default/modules
+++ drush vset --yes file_private_path /home/jenkins/bknix-dfl/build/core-22124-2ucjk/.civibuild/private/default
<h1>Additional uncaught exception thrown while handling exception.</h1><h2>Original</h2><p>TYPO3\PharStreamWrapper\Exception: Unexpected file extension in &amp;quot;phar:///home/jenkins/bknix-max/bin/drush8/commands/core/locale.d8.drush.inc&amp;quot; in Drupal\Core\Security\PharExtensionInterceptor-&gt;assert() (line 38 of /home/jenkins/bknix-dfl/build/core-22124-2ucjk/web/misc/typo3/drupal-security/PharExtensionInterceptor.php).</p><h2>Additional</h2><p>TYPO3\PharStreamWrapper\Exception: Unexpected file extension in &amp;quot;phar:///home/jenkins/bknix-dfl/bin/drush8/commands/core/drupal&amp;quot; in Drupal\Core\Security\PharExtensionInterceptor-&gt;assert() (line 38 of /home/jenkins/bknix-dfl/build/core-22124-2ucjk/web/misc/typo3/drupal-security/PharExtensionInterceptor.php).</p><hr />Drush command terminated abnormally due to an unrecoverable error.       [error]

**Comment by colemanw** [comment]
@eileenmcnaughton needs rebase

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by colemanw** [comment]
retest this please

**Comment by eileenmcnaughton** [comment]
it passed!

**Pull request merged**
