### PR TITLE
fixed #CRM-18159 for 4.6 branch

### PR DESCRIPTION
**Pull request by jaapjansma**
fixed #18159: check acl upon sending of bulk mails. Use the acl as the user who created the email would have had.

See https://issues.civicrm.org/jira/browse/CRM-18159

### CODE REVIEW

**Comment by monishdeb** [comment]
Jenkin, test this please

**Comment by rohankatkar** [comment]
Jenkin test this please

**Comment by eileenmcnaughton** [comment]
Master pr is https://github.com/civicrm/civicrm-core/pull/8150

Yashi has indicated there are additional tests there that need backporting for 4.6

**Comment by mlutfy** [comment]
jenkins, test this please

**Comment by josephlacey** [comment]
HI @jaapjansma, It looks like there are a few style changes that need to be addressed before we can merge this.

> MailingJob.php:475, IncorrectExact, Priority: High
> Line indented incorrectly; expected 2 spaces, found 3
> 
> MailingJob.php:476, SpaceBeforeStar, Priority: High
> Expected 4 space(s) before asterisk; 3 found
> 
> MailingJob.php:477, SpaceBeforeStar, Priority: High
> Expected 4 space(s) before asterisk; 3 found
> 
> MailingJob.php:478, SpaceBeforeStar, Priority: High
> Expected 4 space(s) before asterisk; 3 found
> 
> MailingJob.php:479, SpaceBeforeStar, Priority: High
> Expected 4 space(s) before asterisk; 3 found
> 
> MailingJob.php:480, SpaceBeforeStar, Priority: High
> Expected 4 space(s) before asterisk; 3 found
> 
> MailingJob.php:486, Missing, Priority: High
> Concat operator must be surrounded by spaces
> 
> MailingJob.php:503, SpaceAfterKeyword, Priority: High
> There must be no space between the "array" keyword and the opening parenthesis
> 
> MailingJob.php:505, CommaLastItem, Priority: Normal
> A comma should follow the last multiline array item. Found: $whereClause

**Comment by seamuslee001** [comment]
Hi I think this should be closed and a backport of https://github.com/civicrm/civicrm-core/pull/8415/files should be done instead. Note i think this case doesn't affect those that use the hook to add acl wheres

**Comment by eileenmcnaughton** [comment]
Ok - I'll close it & let Jaap re-open a new one - although changing this functionality without adding a test gives me the heeby jeebies

**Comment by eileenmcnaughton** [comment]
Ok - I'm going to close this for now - go ahead & re-open when you have incorporated changes from the upstream version

**Comment by wdecraene** [comment]
The integration of ACL restriction is confusing...

1) Creating a new mailing and selecting some groups results in 'delivery 133 recipients' - so you think as a user that your mail will be send to these recipients.
2) If you want to send a testmail you can't because 'maybe the group is empty' (but you selected 133 recipients).
3) You can save and send the e-mail (the UI displays 'scheduled', 'started', 'complete') and the user assumes the mail was deliverd to 133 recipients. But no one did... (as you can see in the report but this is not the right place in the mailing workflow).

I think this is not a minor issue... The user gets wrong information, the mails are not delivered to the persons intended... A solution is to 1) give better messages (eg. the reason why something is empty) and 2) integrate acl's from the beginning of the mailing workflow.

01 mailing - creating
02 mailing - could not send testmail
03 mailing - empty delivery

**Comment by eileenmcnaughton** [comment]
To clarify .. when you say 'sent test mail' are you clicking on 'send test' - that should send just to that one email & in your picks you don't seem to have selected a test group - which makes me wonder if you are sending a 'live' mail to a 'test group' rather than 'sending a test mail'

If the latter then can you edit our references to 'testmail' just to make it clearer what you are talking about.

**Comment by jaapjansma** [comment]
It is clicking Send test e-mail to group and then select a group which hold more contacts than you are allowed to see. In a client installation there was a smart group which held all active members. However the user was only allowed to see the people who are living in his same area. He then selected this smart group as input for the test mail (Send test mail to group).

**Comment by wdecraene** [comment]
I clicked on "Send test email to" (so not to a test group, a single e-mail
address)

Met vriendelijke groeten,
Wim

2016-06-29 10:52 GMT+02:00 Jaap Jansma <notifications@github.com>:

**Pull request closed without merging**
