### PR TITLE
Update the post-upgrade thank you message to include URLs to CiviCRM contributors, CiviCRM members and minor rewrite

### PR DESCRIPTION
**Pull request by agileware-justin**
Update the post-upgrade thank you message to include URLs to CiviCRM contributors, CiviCRM members and minor rewrite

Overview
----------------------------------------
Update the post-upgrade thank you message to include URLs to CiviCRM contributors, CiviCRM members and minor rewrite

Before
----------------------------------------
URLs to CiviCRM contributors, CiviCRM members **were not included**. Text needed some improvement.

After
----------------------------------------
URLs to CiviCRM contributors, CiviCRM members **now included**. Text re-written.

Comments
----------------------------------------
I think it fair that URLs to the actual CiviCRM contributors, CiviCRM members should be included. Have added distinct calls to action for joining as a member or partner.
Removed the text for "upgraded to latest CiviCRM" as it's not always the case that this version is the latest.
Have explained why financially supporting CiviCRM is important.

Agileware Ref: CIVICRM-1567

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@joshgowans

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by joshgowans** [comment]
I think this is mostly a good suggestion, however a few of the links are not quite right. The revision has: https://civicrm.org/providers/contributors as the new link, however that routes to the partner listing.

A new contributor list is in development and should be located at https://civicrm.org/contributors when it is live. The current partner listing is at https://civicrm.org/partners-contributors however this URL should change to https://civicrm.org/partners

Once these lists come online, then I believe it would be cool to merge this (with the URL updates).

**Comment by agileware-justin** [comment]
@joshgowans links updated

**Comment by eileenmcnaughton** [comment]
@joshgowans ok to merge now? It won't be released for another 6 weeks so there is time for any fixes to make the links work

**Comment by agileware-justin** [comment]
"Test failure is unrelated"

**Comment by eileenmcnaughton** [comment]
may as well get the green tick & then when @joshgowans confirms it can be merged without someone having to check

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by joshgowans** [comment]
Thank @agileware-justin looks good. Sorry for delay.

**Comment by seamuslee001** [comment]
Merging as per review by @joshgowans

**Pull request merged**
