### PR TITLE
CRM-20838 - Add check for missing log tables on system status

### PR DESCRIPTION
**Pull request by jitendrapurohit**
If drupal and civicrm share same db, drupal modules don't create log tables which result into db error while using them. Check [issue description ](https://issues.civicrm.org/jira/browse/CRM-20838) for when this could happen.

Instead of handling this on update or installation hook within module, this PR checks for missing log table and displays a message + button (just like `Update Indices`) on  system status page which calls `System - updatelogtable` api and creates missing log tables.

---

 * [CRM-20838: Cannot use any civi-drupal modules if logging is enabled](https://issues.civicrm.org/jira/browse/CRM-20838)

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I think this is a good idea. The existing command that you have piggy backed onto also has some complexities to consider

1) it will actually change the data in the log_conn_id field so that going forwards it will record a uniqueid() rather than a not-very-unique id which was the old schema
2) it will convert the schema of the log tables to INNODB
3) given the above it could be a very long operation

While you could work around those things with messaging etc I suspect it makes more sense just to add a new api action System.createmissinglogtables or similar

**Comment by jitendrapurohit** [comment]
Added `createmissinglogtables` api. Also added a minor unit test to check if all works fine.

**Comment by monishdeb** [comment]
The patch works for me and addresses the points mentioned by Eileen. Also the added unit test cover the missing log table scenario well by restoring the missing ```log_civicrm_contact``` table via ```System.createmissinglogtables``` API.  

@eileenmcnaughton should I merge it then?

**Comment by eileenmcnaughton** [comment]
yep!

**Pull request merged**
