### PR TITLE
CRM-21272 move definition of isUserRegistration…

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
…Permitted to CMS classes

Overview
----------------------------------------
Alternative to https://github.com/civicrm/civicrm-core/pull/11078/files

Before
----------------------------------------

### CODE REVIEW

**Comment by colemanw** [comment]
Great improvement.

**Comment by dsnopek** [comment]
Wow, thanks!! :+1:

**Comment by herbdool** [comment]
I didn't see anything for Backdrop

**Comment by eileenmcnaughton** [comment]
hmm - does backdrop inherit the drupal base class?

**Comment by herbdool** [comment]
@eileenmcnaughton it does but we can't use the definition in the base class since Backdrop uses config_get() and has to specify the json file for the config.

**Comment by eileenmcnaughton** [comment]
ok - can you put up the backdrop version of this please? There is another call slightly further down in the function that really should be moved out to the classes.  Maybe we should figure that one out now too. (I think I left it because I didn't figure out what it should be called -something to do with whether to enter a password I think)

**Comment by herbdool** [comment]
@eileenmcnaughton you mean also move stuff on formRule? That would help Backdrop too.

**Comment by eileenmcnaughton** [comment]
I was looking at this block

     if (($isDrupal && !variable_get('user_email_verification', TRUE)) OR ($isJoomla) OR ($isWordPress)) {
        if (empty($fields['cms_pass']) ||
          empty($fields['cms_confirm_pass'])
        ) {
          $errors['cms_pass'] = ts('Please enter a password.');
        }
        if ($fields['cms_pass'] != $fields['cms_confirm_pass']) {
          $errors['cms_pass'] = ts('Password and Confirm Password values are not the same.');
        }
      }

I guess it could be something like 

$config->userSystem->isAdminCreateUserPassword()

**Comment by eileenmcnaughton** [comment]
but totally that form rule stuff too! It's actually quite easily technically to spin these off - the hardest part is trying to figure out what the function should actually be called (are we being too specific/too generic with the name & description)

**Comment by herbdool** [comment]
Agreed naming is hardest part!

**Comment by herbdool** [comment]
I think it's more about confirming password only if it's not setup to verify by email (in Drupal). It always checks with Joomla and WordPress. Maybe

**Comment by eileenmcnaughton** [comment]
but, why? I mean is it just to save them entering the password twice if it will be reset by the user? Seems odd to care about that

**Comment by herbdool** [comment]
I'm curious too. I'm going to try look more into it later today or tomorrow.

**Comment by eileenmcnaughton** [comment]
That would be great. I think chasing out the $isDrupal now - while you and drupal 8 people have some focus might save everyone time & bouncy bugs later

**Comment by herbdool** [comment]
I can see why it checks. This is that variable means: "New users will be required to validate their e-mail address prior to logging into the site, and will be assigned a system-generated password." So it doesn't allow the user to set a password if they're supposed check their email for the system-generated password.

**Comment by eileenmcnaughton** [comment]
so perhaps 

isPasswordUserGenerated or isPasswordSystemGenerated might be the fn name?

**Comment by herbdool** [comment]
I think `isPasswordUserGenerated` is good. I was thinking `isPasswordSettingPermitted`but it doesn't specify who. I'll work on this.

**Pull request merged**
