### PR TITLE
CRM-19950 : Wrong param passed to checkPermission function

### PR DESCRIPTION
**Pull request by yashodha**
* [CRM-19950: Wrong param passed to checkPermission function](https://issues.civicrm.org/jira/browse/CRM-19950)

### CODE REVIEW

**Comment by yashodha** [comment]
@eileenmcnaughton PR for the same has been merged in master

**Comment by eileenmcnaughton** [comment]
ok - I'm not involved with 4.6 in any way anymore

**Comment by seamuslee001** [comment]
pining the 4.6 managers @guanhuan @jackrabbithanna

**Comment by eileenmcnaughton** [comment]
actually I lie, I still have one 4.6 (self-appointed)  role - to point out to people doing 4.6 PRs that they need to ensure it is fixed in master first - but that doesn't apply here :-)

**Comment by guanhuan** [comment]
@yashodha should https://github.com/civicrm/civicrm-core/blob/4.6/CRM/Group/Page/Group.php#L113 be done here as well?

**Comment by yashodha** [comment]
@guanhuan  I have cleaned up all the references now.

**Comment by jackrabbithanna** [comment]
@guanhuan @seamuslee001 This isn't an official security bug for the next release, but since it deals with a problem with checkPermissions, thoughts on including this in this next release and merging now?

**Comment by seamuslee001** [comment]
I think it makes sense to me its a port directly from master.

**Comment by jackrabbithanna** [comment]
merging #9811

**Pull request merged**
