### PR TITLE
CRM-20158, added card_type and pan_truncation field

### PR DESCRIPTION
**Pull request by pradpnayak**
----------------------------------------
* CRM-20158: Store card type and last 4 digits of credit card
  https://issues.civicrm.org/jira/browse/CRM-20158

### CODE REVIEW

**Comment by pradpnayak** [comment]
@JoeMurray @eileenmcnaughton can you please review?

**Comment by eileenmcnaughton** [comment]
@KarinG I believe this is OK based on our previous discussions / requests on this

**Comment by eileenmcnaughton** [comment]
Prior discussion on #8941

**Comment by KarinG** [comment]
Hi @pradpnayak @eileenmcnaughton - how is DirectDebit/ACHEFT method handled? You can pay for a financial transaction with Credit Card, DirectDebit or cash - what happens with a DirectDebit/ACHEFT transaction?

**Comment by eileenmcnaughton** [comment]
@KarinG check your comments on the previous PR https://github.com/civicrm/civicrm-core/pull/8941#issuecomment-253380343

I'm guessing that we only record for credit card since we didn't come up with something generic for the others. Note this is added to financial_trxn table so it is per payment (which makes sense if there are multi payments against a contribution)

**Comment by KarinG** [comment]
Ok I'm lost. There is a lot of PRs floating around. If we just look at this PR first - that looks good for credit_card.

Critical next is where that PAN truncation will happen - should be right after the credit_card is handed off to the Payment Processor.

**Comment by eileenmcnaughton** [comment]
Yep I'm confused too - but if you are happy with this I'll merge this one. The others look like there is a lot of review work involved.

Actually I think this would be recorded on confirmation. Because you never really know until then. Ug that's tricky.  Some processors return it & others don't. I feel like where they return it then it should be managed at confirmation. Hmm maybe it can just be updated

**Comment by eileenmcnaughton** [comment]
I guess fundamentally I can agree
1) its OK to store more info about the card within the limits of PCI
2) I can see it would be helpful
3) this appears to be the right place to store it

**Comment by KarinG** [comment]
Yes - this is a good first step PR to build in support for people trying to query how many VISA $ vs MC $ vs AMEX $ did we get last month.

**Comment by KarinG** [comment]
Let's keep the pieces to bring this in manage-able in size and purpose.

**Comment by eileenmcnaughton** [comment]
Based on above discussion & agreement with @KarinG , passing tests and the fact the code looks correct I'm merging

**Pull request merged**
