### PR TITLE
Afform: Support conditional logic

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Adds client-side support for conditional logic to hide fields and containers based on rules using and/or/not logic.

Before
----------------------------------------
Afforms lacked conditional logic to show/hide fields

After
----------------------------------------
Any field, button, fieldset or other element can have conditional rules:
image

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
Is this draft because it's unfinished?  Do you need testers?

**Comment by kurund** [comment]
@MegaphoneJon 

I was planning to test and work on this once it's rebased against the master.

@colemanw may be change the PR status once rebased.

**Review by kurund — DISMISSED** [review]
@colemanw 

Looks good and working as expected for types: text, radio, select.

There is problem with the checkbox field.

i.e If I check particular value I want to display another field.

**Comment by mattwire** [comment]
UI for conditionals on fields that have multiple options not very friendly - eg. "Country":
image

Also, can we at the very least get a line of text below the If/And selectors that says "then the field will be shown" or similar as it's currently very unclear what will actually happen.

**Comment by kurund** [comment]
@colemanw 

Just checking if you have any updates on this issue. Looks like tests are failing too.

**Comment by mattwire** [comment]
test this please

**Comment by mattwire** [comment]
test this please

**Comment by mattwire** [comment]
@totten @seamuslee001 Why does this PR have an extra check called "default"?

**Comment by colemanw** [comment]
@mattwire I've fixed the country autocomplete field (that was a bug) and added the explainer text you suggested.

@kurund I tested this conditional toggling off a checkbox, and it seems to work ok now.

**Comment by kurund** [comment]
@colemanw 

Here is the FB configuration where it's not working.

Screenshot from 2023-04-16 05-20-42
Screenshot from 2023-04-16 05-21-06

I want to show phone field if phone is checked.

**Comment by kurund** [comment]
Another bug:

Field names are repeated multiple times on conditional configuration screen.

Screenshot from 2023-04-16 05-30-37

Screenshot from 2023-04-16 05-30-23

**Comment by mattwire** [comment]
@colemanw I just tested this again. The two bugs that @kurund found are still an issue (field names are repeated / trigger off multiple checkboxes).

Is it possible to have a visual indication when an element has conditional rules? Eg. an icon next to the cog? It can be quite confusing when you have multiple conditional elements to find which ones have conditionals set because you have to click each time on the cog and see if it says "Edit conditional rules" or "Add conditional rules".

I was surprised to not see operators eg. "is empty" for a string field and "is one of" for multiple choice?

**Comment by MegaphoneJon** [comment]
Just pinging on this again per our conversation last Thursday.

**Comment by sebalis** [comment]
Here are some issues encountered during this week’s CiviSprint in Germany, on a test instance where I patched this PR into an installation of CiviCRM 5.65.0:

## Evaluating conditions on form load with “≠ [empty]“ as a condition

We tried out a form for the Person entity, with Employer as a contact field in the Person block, and made the Function field depend on the Employer field being not equal to the empty string.

When the form is first loaded, the Function field is displayed even though the Employer field is initially empty. Once an employer is selected, the condition works, i.e. the Function field disappears if the Employer is deleted.

There are three field types offered for the Employer (i.e. contact) field. AutoComplete Contact is the one shown in the screenshot. We also tried Contact ID, and again the dependent field (Function) is initially shown and disappears if the ID is set and then reset to zero. (We disregard the third type, Select Form Contact, because we had problems understanding this type in general.)

This issue does not depend on the field used as a condition being a contact field. A text field that is empty on form load will also not hide a dependent field that uses “≠ empty” as a condition.

The problem does not seem to arise when editing an existing record.

## Adding form elements that are not fields

If conditions are used, some forms will need checkboxes or radio buttons whose values are only used as conditions, not stored as fields themselves – such as “has an employer” without specifiying who the employer might be. This need might not arise without conditional fields, which is why we regard it as related to this PR. 

A possible counter argument is that when a record is updated using the same form, we would probably need to store a value for a form control that is used in any conditions, to guarantee that the conditions can be evaluated correctly as the form is populated with the existing values. This is true, but there are still compelling use cases for this feature in forms that only be used for creating and not for updating, for which different forms would have to be used (or perhaps updating will be left to support staff via the backend).

## Conditions for activating/deactivating

In some use cases it would be preferred that instead of hiding or showing a field, a condition could cause a button or other form elements to be deactivated/activated.

**Comment by kurund** [comment]
@colemanw 

just pinging here to bring this back to your radar.

**Comment by technomaz** [comment]
> @colemanw
> 
> just pinging here to bring this back to your radar.

Agreed with @kurund as I'm having to patch this in at every upgrade, so it would be nice to get it merged. That said, I also face the issue described in "Evaluating conditions on form load with “≠ [empty]“ as a condition", so having that resolved before merging would be helpful. But I don't know that I would hold up this patch for those Sep 9 commented issues--perhaps those can be separated out as separate issues for future resolution.

**Comment by mlutfy** [comment]
A colleague and I have been testing this patch and so far it looks great. There are a few quirks, but overall very usable. If anyone can, doing a recap of the issues mentioned in this thread, and seeing which ones are still relevant, would help a lot to have a clearer picture. We will try to do so, but more likely during the sprint next week.

**Comment by mlutfy** [comment]
Any objections to merging this? We haven't found issues so far, although I don't think we have tested every issue mentioned on this thread. I feel like it would be OK to merge & address them in subsequent PRs?

**Comment by mattwire** [comment]
> Any objections to merging this? We haven't found issues so far, although I don't think we have tested every issue mentioned on this thread. I feel like it would be OK to merge & address them in subsequent PRs?

+1 from me

**Comment by mlutfy** [comment]
Tests I did:

- [ ] Display only if Checkbox option is X: does not work
- [ ] Condition based on the "employer" field being empty or not (but it works if we check against a specific employer, although I assume that's a less frequent type of condition)
- [x] Display only if Textfield equal to X: works
- [x] Display only if Country equal to X: works, and country selection is nice
- [x] When creating new conditional rules, fields are shown only once
- [x] Condition based on fields such as "Do not mail"
- [x] Condition based on the Address Location Type (ex: show only if LocationType = Billing)

I did not test all of the issues reported by @sebalis, only some bits (ex: employer field) - they are a bit difficult to test without exact steps to reproduce on a demo site, and I feel like they should be separate issues that maybe require more discussion.

**Comment by colemanw** [comment]
Ok thanks @kurund and @mattwire and @mlutfy and @technomaz for pushing this over the line.

**Pull request merged**
