### PR TITLE
dev/core#2774 : Sort by date column on multirecord field listing section on profile edit mode doesn't work

### PR DESCRIPTION
**Pull request by monishdeb**
Overview
----------------------------------------
1. create a multi-record custom data set for contacts
2. create a date field of format mm/dd/yyyy. it may be beneficial to create another text field for reference.
3. Configure a profile using those multi-record custom data field
4. Go to profile edit mode and add some data to a contact record. For the date field, select some values across multiple years.
5. Try sorting by the date on the frontend profile form in edit mode

Before
----------------------------------------
before

After
----------------------------------------
after

Comments
----------------------------------------
ping @lcdservices @seamuslee001 @eileenmcnaughton

### CODE REVIEW

**Comment by lcdservices** [comment]
Tested and this works as intended.

**Comment by eileenmcnaughton** [comment]
I think the r-run testing @lcdservices has done is appropriate to this change (I can't see a meaningful way to add a unit test )

**Comment by seamuslee001** [comment]
Merging as per @lcdservices @eileenmcnaughton 's comment

**Comment by monishdeb** [comment]
Thanks @seamuslee001

**Pull request merged**
