### PR TITLE
Remove static caching of static on Contribution page tab

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
This one is for @eileenmcnaughton ... Remove the static caching on a static function.

Before
----------------------------------------
Unnecessary code, less comments

After
----------------------------------------
Cleaner code, comments/docblocks cleaned up

Technical Details
----------------------------------------
This cleans up an early return + static caching of the `recurLinks()` function which is already static.

Comments
----------------------------------------

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by mattwire** [comment]
test this please

**Comment by totten** [comment]
I think I like this, but the rationale ("unnecessary") seemed hand-wavy. Trying to read between the lines...

Caching that initial array of 3 elements looks a lot like a micro-optimization. The micro-optimization *might* make sense if, hypothetically, `::recurLinks()` was called 10,000 times in some pageview. But that hypothetical seems only hypothetical; and even if it's given, the expected gain doesn't bear-out in benchmarking on php7. (*Make a throw-away script which calls `recurLinks()` 10k times and compare with/without `$_links`*). 

+1 for simpler code

**Comment by mattwire** [comment]
@totten Thanks :-) @eileenmcnaughton particularly doesn't like the static $_links, I didn't mind.  But it does simplify the code without!

**Comment by mattwire** [comment]
@eileenmcnaughton Please review comments and merge if you are happy?

**Comment by eileenmcnaughton** [comment]
I worked through the refactor & it seems fine - links still exist on the recurring contribution tab

**Pull request merged**
