### PR TITLE
[REF] Simple function extraction for buildMappingForm

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Simple refactor toward making this function less toxic.

Before
----------------------------------------
Toxic function unbelievably long.

After
----------------------------------------
Toxic function slightly less long.

### CODE REVIEW

**Comment by colemanw** [comment]
@totten I miss our Save the Fish warning.

**Comment by eileenmcnaughton** [comment]
I re-did the same extraction locally & was able to get the same result - merging

**Comment by eileenmcnaughton** [comment]
@colemanw I *think* the fish still shows - it's just attached to the wrong functions now

**Comment by colemanw** [comment]
@eileenmcnaughton https://github.com/civicrm/civicrm-core/blob/5.15/.toxic.json#L39

**Pull request merged**
