### PR TITLE
CRM-18515 - Allow Payment Processor with same name when using multi-domain

### PR DESCRIPTION
**Pull request by darrick**
https://issues.civicrm.org/jira/browse/CRM-18515

### CODE REVIEW

**Comment by monishdeb** [comment]
@derrick can you please squash multiple commits in this PR into one commit. Here are the steps:
1. git rebase --interactive 
2. Edit command names accordingly
  pick   1fc6c95 My pull request
  squash 6b2481b Hack hack - will be discarded
  squash dd1475d Also discarded
3. git push -f origin/CRM-18515

for reference http://stackoverflow.com/questions/9790448/how-to-update-a-pull-request

**Comment by derrick** [comment]
Looks like you meant @darrick ...

**Comment by monishdeb** [comment]
oops sorry :)

**Comment by darrick** [comment]
@monishdeb believe I just made things worse.  I tried  git rebase --interactive after git checkout orgin/CRM-18515 but only choice was NOOP.  I then tried git rebase -i origin/master but it didn't list all the commits.  So I used git rebase -i HEAD~7 which gave me all the commits and dropped all the commits except for the main one.  Then on git push it said I wasn't up to date.  So I chose git pull and then git push.

**Comment by monishdeb** [comment]
@darrick  .. seems like rebase need to be done against upstream/master not origin/master since later is outdated branch that's why you got unwanted commits piled up on top of earlier commit. (As i said above on the first step that 'git rebase --interactive' actually does rebasing against upstream/master if you don't mention it) For now its better to close the current pr and create a new branch in your local and make the changes manually as the patch is just a one file change.

**Comment by darrick** [comment]
Cleaned up PR.  https://github.com/civicrm/civicrm-core/pull/8344

**Pull request closed without merging**
