### PR TITLE
WIP: CRM-20665 - Fix memory problem for editing events.

### PR DESCRIPTION
**Pull request by johanv**
Works again:
* editing a single event
* 'manage events' page
* event dashboard
* editing an event without 'Administer CiviCRM' permission
---

 * [CRM-20665: Memory error when trying to edit an existing event](https://issues.civicrm.org/jira/browse/CRM-20665)

### CODE REVIEW

**Comment by johanv** [comment]
This will not work in it's current form, because of the dodgy caching mechanisme I didn't notice.

**Comment by eileenmcnaughton** [comment]
@johanv this seems to have stalled in WIP and the code has had a few changes in the meantime. I'm going to close & let you re-open when it's ready for review

**Comment by johanv** [comment]
I don't work any more on the project for which I created this pull request some time ago. So I am not sure this patch is still needed in recent versions of CiviCRM.
@JO0st , do you still use this patch? If not, I guess CRM-20665 can be closed.

**Comment by eileenmcnaughton** [comment]
We are sorry to lose you @johanv !!!

**Comment by johanv** [comment]
@eileenmcnaughton I did not die :-) I have a new job since june 2017. This does not mean I will completely stop contirbuting to CiviCRM (I still maintain a small instance, but not as part of my job), but I just have way less time than before to do CiviCRM work.

**Comment by eileenmcnaughton** [comment]
@johanv good to hear you will still be with us a bit then!

**Comment by JO0st** [comment]
@johanv I checked, and we still are using it

**Pull request closed without merging**
