### PR TITLE
CRM-19218 Fix unindexed join by getting option values using api

### PR DESCRIPTION
**Pull request by seamuslee001**
- [CRM-19218: Fix unindexed join in getTaxRates function](https://issues.civicrm.org/jira/browse/CRM-19218)

### CODE REVIEW

**Comment by seamuslee001** [comment]
@eileenmcnaughton I noticed this when you did your PR that you added in the todo so i'm just following up on your work

**Comment by seamuslee001** [comment]
https://issues.civicrm.org/jira/browse/CRM-19218

**Comment by seamuslee001** [comment]
@eileenmcnaughton Does this look good to you? I have added in a test as well just to be certain, even tho i think this would have been picked up by other tests I added a specific test of this function.

**Comment by seamuslee001** [comment]
@eileenmcnaughton is this good to merge?

**Comment by eileenmcnaughton** [comment]
I tested this on the PR sandbox and was able to create a contribution with a taxed type and the contribution record showed the tax_amount. With no tax type there was no tax_amount.

Note that you need to not only enable tax for a financial account / type but also add a sales account relationship to make a type taxable.

I tried testing changing the total amount to see if it was correctly recalculated but could not find a way to get past the form rule wanting the net_amount to be something different. However, that issue precedes this...

**Pull request merged**
