### PR TITLE
Package Riverlea theme extension during CiviCRM build

### PR DESCRIPTION
**Pull request by vingle**
Overview
----------------------------------------
Following [discussion](https://chat.civicrm.org/civicrm/pl/i5hz77r5ab8cxjobzyzz9wcsfw) this packages the most recent release of the RiverLea theme framework extension (https://lab.civicrm.org/extensions/riverlea) during the CiviCRM build process.

Before
----------------------------------------
RiverLea isn't packaged, so needs to be installed manually.

After
----------------------------------------
It is. Anyone can enable RiverLea to try one of its four subthemes/'streams'.

Technical Details
----------------------------------------
RiverLea is a large extension. To better understand it, a good starting point is to look at the GitLab readme, changelog, issues, & PR history.

Comments
----------------------------------------
I am kind of guessing this is the right way to add this, but cannot test.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
woohoo - although @totten might need to look

**Comment by ufundo** [comment]
Added `run-distmaker` to make testable install packages.

But it's failed complaining about backdrop_php5 - which is weird. Seems unrelated. Also sure php5 was dead long before Backdrop existed?

**Comment by ufundo** [comment]
Oh it can't apply the patch in the PR to that file. Can you try rebase maybe @vingle ?

**Comment by vingle** [comment]
@ufundo they all have php5 in the title - maybe it means more like 'high five php!' But not sure it's linked to the failures.. the bit I'm wondering about is how/where it knows that the riverlea in `dm_install_cvext riverlea "$TRG/ext/riverlea"` refers to a specific repo somewhere.

Answering my own question - I wonder if it's this line? https://github.com/civicrm/civicrm-core/blob/00b5091d8eacde77f226074113db88c15c9b6886/distmaker/dists/common.sh#L328 - in which case I wonder if the errror is that this doesn't resolve to RiverLea? Not sure how https://civicrm.org/extdir is generated but maybe it comes from /extensions?

**Comment by ufundo** [comment]
I *think* the error is in how the Jenkins job applies the PR changes to the main branch, in order to run the test -- before it gets as far as downloading any extensions or anything...

**Comment by demeritcowboy** [comment]
@vingle It looks like your patch is against the 5.77 version of the file - the file has changed since then so you need to apply the change against a newer version, preferably master since your PR is against master.

**Comment by vingle** [comment]
Have opened a new PR https://github.com/civicrm/civicrm-core/pull/31324 so closing this.

**Pull request closed without merging**
