### PR TITLE
Replace ical and office calendar image icons

### PR DESCRIPTION
**Pull request by agh1**
Overview
----------------------------------------
This slices off one commit from #17259 for ease of review.  I then added an improved way to display the icons and applied the same improvement in a parallel place.

This changes the icons on the bottom of the event info page to use Font Awesome.  These are stacked icons, the left one showing a calendar with a download icon (to download a file for the one event), and the right one showing a calendar with a link (to subscribe to the calendar).

The original icon files were used nowhere else, so this removes them.

I also altered the Event Dashboard to use similar icons for similar things at the top.  The four links (view a listing, subscribe to a RSS feed, download a calendar, link to a calendar feed) have always been difficult to differentiate with icons, so this should be helpful.

Before
----------------------------------------
image

image

After
----------------------------------------
image

image

Technical Details
----------------------------------------
Stacked Font Awesome icons don't always line up with non-stacked ones, so it's helpful that all of the icons together be stacked.

### CODE REVIEW

**Comment by jaapjansma** [comment]
* General standards
    * Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
        * __PASS__ : The goal/problem/solution have been adequately explained in the PR.
    * User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
        * __PASS__: The change would be intuitive or unnoticeable for a majority of users who work with this feature.
    * Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
        * __ISSUE__: The developer documentation should be updated.
        * __COMMENTS__: We think it might be nice to also document the changes in this PR in the developer documentation.
    * Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
        * __PASS__: We checked in both dmaster and the test environment of this PR. We have checked the Dashboard of Events, the manage event screen and the public page of an event
        * __ISSUE__: We do think it might be worth to also replace the icons on the manage event screen
* Developer standards
    * Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
        * __PASS__: The change preserves compatibility with existing callers/code/downstream.
    * Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
        * __PASS__: The functionality, purpose, and style of the code seems clear+sensible.
    * Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
        * __PASS__: The change sufficiently improves test coverage, or the change is trivial enough that it does not require tests.
    * Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
        * __PASS__: The test results are all-clear.

@agh could you also implement the icons on the manage event page?

**Comment by agh1** [comment]
@jaapjansma @mattwire I updated this to do the same thing on Manage Events as on the CiviEvent dashboard.  Since it's a lot of repeated code, and it's weird that the URLs were all defined in Smarty, I created a new `CRM_Event_BAO_Event::getICalLinks()` function that supplies them.

**Comment by agh1** [comment]
I updated this with `aria-hidden` per #17318

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by mattwire** [comment]
test this please

**Pull request merged**
