### PR TITLE
CRM-19755 reverse order of html and text

### PR DESCRIPTION
**Pull request by JoeMurray**
Make order same as rest of CiviMail

---

 * [CRM-19755: reverse order of html and text on CRM\/Mailing\/Page\/Component.php](https://issues.civicrm.org/jira/browse/CRM-19755)

### CODE REVIEW

**Review by seamuslee001 — APPROVED** [review]
Looks good to me

**Review by seamuslee001 — CHANGES_REQUESTED** [review]
@JoeMurray Joe by doing this you also need to move L52 below L53

**Comment by pradpnayak** [comment]
Tested PR, Its working
screenshot from 2016-12-13 22 54 19

**Comment by pradpnayak** [comment]
But the order of form fields on /civicrm/mailing/component?action=update&id=2 is Text and HTML below.



Here is the patch  if we want to switch the fields.
diff --git a/templates/CRM/Mailing/Form/Component.tpl b/templates/CRM/Mailing/Form/Component.tpl
index 2c50632..2191c7a 100644
--- a/templates/CRM/Mailing/Form/Component.tpl
+++ b/templates/CRM/Mailing/Form/Component.tpl
@@ -30,8 +30,8 @@
     <tr class="crm-mailing-component-form-block-name"><td class="label">{$form.name.label}</td><td>{$form.name.html}</td>
     <tr class="crm-mailing-component-form-block-component_type"><td class="label">{$form.component_type.label}</td><td>{$form.component_type.html}</td>
     <tr class="crm-mailing-component-form-block-subject"><td class="label">{$form.subject.label}</td><td>{$form.subject.html}</td>
-    <tr class="crm-mailing-component-form-block-body_text"><td class="label">{$form.body_text.label}</td><td>{$form.body_text.html}</td>
     <tr class="crm-mailing-component-form-block-body_html"><td class="label">{$form.body_html.label}</td><td>{$form.body_html.html}</td>
+    <tr class="crm-mailing-component-form-block-body_text"><td class="label">{$form.body_text.label}</td><td>{$form.body_text.html}</td>
     <tr class="crm-mailing-component-form-block-is_default"><td class="label">{$form.is_default.label}</td><td>{$form.is_default.html}</td>
     <tr class="crm-mailing-component-form-block-is_active"><td class="label">{$form.is_active.label}</td><td>{$form.is_active.html}</td>
   </table>

**Comment by pradpnayak** [comment]
Tested, working

**Pull request merged**
