### PR TITLE
Extra trailing slash was causing redirects

### PR DESCRIPTION
**Pull request by JamesOsborn-SE**
Overview
----------------------------------------
_A brief description of the pull request. Keep technical jargon to a minimum. Hyperlink relevant discussions._

Thank you page was not working providing an error.

Before
----------------------------------------
_What is the old user-interface or technical-contract (as appropriate)?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._
thank you page was not loading and  301 redirects on cleanUrls with querystrings.
https://civicrm.stackexchange.com/questions/40446/could-not-find-valid-value-for-id-for-event-thankyou?noredirect=1#comment47404_40446
image

After
----------------------------------------
_What changed? What is new old user-interface or technical-contract?_
_For optimal clarity, include a concrete example such as a screenshot, GIF ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)), or code-snippet._
thank you page works and not redirects for clean urls with query strings.

Technical Details
----------------------------------------
_If the PR involves technical details/changes/considerations which would not be manifest to a casual developer skimming the above sections, please describe the details here._

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@kcristiano @christianwach

**Comment by christianwach** [comment]
The default behaviour on vanilla WordPress is for `redirect_canonical()` to redirect the other way, e.g. `https://domain.com/some-page?x=y` redirects to `https://domain.com/some-page/?x=y`. 

Here's an example on a site that doesn't have CiviCRM installed: [https://haystack.co.uk/contact?x=y](https://haystack.co.uk/contact?x=y)

The demo site also exhibits this behaviour: [https://wpmaster.demo.civicrm.org/civicrm/event/info?reset=1&id=1](https://wpmaster.demo.civicrm.org/civicrm/event/info?reset=1&id=1)

Something else must be the cause of the Thank You page redirect - I'll see if I can replicate on my Paypal dev site.

**Comment by christianwach** [comment]
> I'll see if I can replicate on my Paypal dev site.

Works as expected on my dev site, WordPress 5.7.3 & CiviCRM 5.41.2:

Screenshot 2021-10-06 at 11 17 56

**Comment by christianwach** [comment]
Whatever the problem is that @JamesOsborn-SE is seeing, I don't think this PR will fix it.

James, do you have any Extensions and/or Plugins that could be interfering in some way?

**Comment by tadcol** [comment]
@christianwach I agree with your comments.  I see the same behavior from WP and cannot replicate on my paypal tst sites running CiviCRM 5.42.RC

**Comment by kcristiano** [comment]
@christianwach I agree with your comments.  I cannot replicate with PayPal standard on CiviCRM 5.42.RC and WP 5.8.1

**Comment by christianwach** [comment]
My best guess at the moment is that @JamesOsborn-SE is using a custom Permalink Structure that doesn't have the trailing slash. If so, then it looks like `CRM_Utils_System_WordPress::url()` needs to be more sophisticated about parsing the Permalink Structure while building URLs.

**Comment by JamesOsborn-SE** [comment]
>  non-standard Permalinks setting
I'm using the official WordPress Docker image but I have some Plugins and Extensions installed.
Oof sorry for the noise. I'll try disabling all the plugins and extensions and try again.  Is there a DB setting that can affect this that you know of?

**Comment by JamesOsborn-SE** [comment]
It turns out adding a '/' at the end of the Permalink Settings was made it work. I'm not sure how this ever worked. 
https://mysite.org/wp-admin/options-permalink.php 
We had set a Custom Structure 

From: 
`/%category%/%post_id%/%postname%`

To:
`/%category%/%post_id%/%postname%/`

**Comment by kcristiano** [comment]
Thanks for the feedback.  A trailing slash is standard   I have `/%category%/%postname%/`  on the site I am currently working on and all other than the plain/numeric add the trailing slash.  I know plain causes issues and I've never tried numeric...,.

**Pull request closed without merging**
