### PR TITLE
dev/core#4988 Standalone - use regular php session during install

### PR DESCRIPTION
**Pull request by ufundo**
Before
----------------------------------------
Installing Standalone through the web UI crashes because the installer wants to initialise a session before the SessionHandler provided by Standaloneusers extension is available.

After
----------------------------------------
Use the default php session handler during install.

Technical Details
----------------------------------------
This just opts out of the custom SessionHandler based on `CIVI_SETUP` being set - other parameters to the `session_start` call ( in particular the custom session cookie name ) are retained.

Questions:
- is there any risk to the opt-out based on `CIVI_SETUP`? could anything bad happen if CIVI_SETUP is set when it shouldn't be?
- when exactly does the transfer over to the "proper" `standaloneusers` session happen? will anything important from the session be lost at this point? e.g. notices from the install phase?

An alternative solution is to hook in early to enable the `standaloneusers` extension: https://github.com/civicrm/civicrm-core/pull/29362

### CODE REVIEW

**Comment by ufundo** [comment]
I think this approach might be better: https://github.com/civicrm/civicrm-core/pull/29354

**Comment by MegaphoneJon** [comment]
> ! ) Fatal error: Uncaught TypeError: Firebase\JWT\JWT::getKey(): Return value must be of type Firebase\JWT\Key, string returned in /var/www/sastarter.localhost/vendor/firebase/php-jwt/src/JWT.php on line 482

I've seen this in my client's logs, but haven't been able to track it down to anything in particular yet.

**Comment by seamuslee001** [comment]
@MegaphoneJon do you have this patch or something similar applied? https://github.com/civicrm/civicrm-core/pull/29345

**Comment by MegaphoneJon** [comment]
> @MegaphoneJon do you have this patch or something similar applied? #29345

I do not. But also I don't want us to hijack this PR for the discussion.  I'll look into this later and create a ticket.

**Comment by ufundo** [comment]
Converting this to draft because I think collective wisdom is that https://github.com/civicrm/civicrm-core/pull/29362 is the better solution. If you think otherwise, shout!

**Comment by ufundo** [comment]
Yep, that patch fixed the login issue for me, thanks @seamuslee001

**Comment by ufundo** [comment]
After an interesting tour round the houses I think I'm back to preferring this as being the neatest and most reliable approach. It's right at the danger point where we call the extension class, it's in the System utils rather than adding conditionals into core code, and... it works.

I've added a commit to use a distinct cookie name during install, to avoid any nasty collisions between the real session and this temporary one.

**Comment by totten** [comment]
@ufundo That sounds pretty persuasive to me...

Setting a separate cookie for the setup-screen makes perfect sense (given the different session-storage requirements).

**Comment by ufundo** [comment]
woohoo thanks @artfulrobot :)

**Pull request merged**
