### PR TITLE
Fix test set up to user Order api

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Note this includes the order api ensuring that the contribution_recur_id is passed through to
any created memberships

Overview
----------------------------------------
Fix test set up to user Order api 

Before
----------------------------------------
Test uses mishmash set up

After
----------------------------------------
Test uses api

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
This now includes https://github.com/civicrm/civicrm-core/pull/20779 as that has a fix for the situation where memberships have more than one member organization

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by eileenmcnaughton** [comment]
@colemanw also this - one line of change + test clean up. The change is so that the order recurring contribution id reaches the membership

**Comment by colemanw** [comment]
@eileenmcnaughton can you rebase this please?

**Comment by eileenmcnaughton** [comment]
unrelated fail

**Pull request merged**
