### PR TITLE
[REF] Update a few references to invoicing

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
[REF] Update a few references to invoicing

Before
----------------------------------------
Legacy access to the invoicing setting

After
----------------------------------------
`Civi::settings()->get('invoicing');`

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mlutfy I can't quite decide whether to give up on these for now or push through & do them all - but here are a few more

**Comment by eileenmcnaughton** [comment]
@mlutfy @seamuslee001 @demeritcowboy anyone up to look at this - I feel like it should be just a quick sanity check review

**Comment by demeritcowboy** [comment]
Sure I can take a look.

**Comment by demeritcowboy** [comment]
jenkins retest this please (since it's been a while)

**Pull request merged**
