### PR TITLE
1226, fixed Change log relative date search for creating smart group

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/issues/1226

Before
----------------------------------------
1226-Bug

After
----------------------------------------
1226-Bug

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@pradpnayak I switched the PR over to 5.17 rc but that didn't work since there are so many commits - can you change this to the rc?

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
(*CiviCRM Review Template WORD-1.2*)



* General standards
    * ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain)) Pass
    * ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user)) Pass
    * ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc)) Pass
    * ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run)) Pass - I replicated the issue locally and confirmed that this fixes the issue when creating smart groups
* Developer standards
    * ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech)) Pass
    * ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code)) Pass
    * ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint)) Pass
    * ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test)) Unknown

**Comment by pradpnayak** [comment]
Hi @eileenmcnaughton 

I have updated the branch.

Thanks
Pradeep

**Pull request merged**
