### PR TITLE
core/issues/923, Fixed notice error when creating/editing profile

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
https://lab.civicrm.org/dev/core/issues/923

Before
----------------------------------------
Before

After
----------------------------------------
After

### CODE REVIEW

**Comment by seamuslee001** [comment]
@pradpnayak can you put this against the RC as its a recent issue ping @eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
It's not totally clear to me from a quick look that this is a recent regression but it also seems trivial enough & safe enough to agree to put it against the rc without sinking time into more analysis

**Comment by pradpnayak** [comment]
@seamuslee001 5.13 or 5.14?

**Comment by eileenmcnaughton** [comment]
@pradpnayak always against the rc first. ie. 5.14. Once it's in the rc we merge to master & consider backporting to 5.13

**Pull request merged**
