### PR TITLE
Declare some public variables on ChangeCaseStatus

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Addresses
https://test.civicrm.org/job/CiviCRM-Core-Edge/3254/CIVIVER=master,label=bknix-tmp-edge/testReport/junit/(root)/CRM_Case_BAO_CaseTest/testCaseClosure/

I couldn't figure out where this is called from other than tests

image

### CODE REVIEW

**Comment by demeritcowboy** [comment]
This doesn't seem right. The class specified in the error in CRM_Case_Form_Activity. `_caseId` is already declared, and `_caseStatus` seems more like a modified lookup which could be local variables.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy it did seem to get through the test fails ... it has moved onto the next variable now....https://test.civicrm.org/job/CiviCRM-Core-Edge/CIVIVER=master,label=bknix-tmp-edge/lastCompletedBuild/testReport/(root)/CRM_Case_Form_ChangeStartDateTest/testChangeCaseStartDate/ 

it could be how the test it written rather than what the form is doing

**Comment by demeritcowboy** [comment]
That's a different test. The closure test is still failing.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy ug yeah

image

It did fix this one though

https://test.civicrm.org/job/CiviCRM-Core-Edge/CIVIVER=master,label=bknix-tmp-edge/3254/testReport/junit/(root)/CRM_Case_BAO_CaseTest/testChangeCaseStatusLinkedCases/

I suspect that test should be updated to use the full form flow but that felt like a rabbit hole too far

**Comment by demeritcowboy** [comment]
Hmm yeah that test I think creates the wrong form class.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy ah - that might be why it was so confusing!

**Comment by demeritcowboy** [comment]
I'll take a look at it later.

**Comment by eileenmcnaughton** [comment]
thanks @demeritcowboy

**Comment by eileenmcnaughton** [comment]
@demeritcowboy if you have space maybe you can look at moving the CustomData load on that form to ajax too?

e.g

https://github.com/civicrm/civicrm-core/pull/29229/files#diff-26fac20643032b3ff30df159806efb80129a54a29c09697676d0241d168a7e58R88

Mostly it's just trying to get the custom data to load consistently across forms (ie not ajax sometimes & in-form other times, at least backoffice) & to use less legacy code to do it

**Comment by demeritcowboy** [comment]
I've put up https://github.com/civicrm/civicrm-core/pull/29284 for part of this.

**Comment by eileenmcnaughton** [comment]
thanks @demeritcowboy

**Pull request merged**
