### PR TITLE
Fix transfer registration to transfer participant_payment row

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Overview
----------------------------------------
Fix transfer registration to transfer participant_payment row

Before
----------------------------------------
When transferring an event registration the line item is updated with the new participant id but the participant payment is not

After
----------------------------------------
payment updated

Technical Details
----------------------------------------
I found this in the process of adding more validation in the postAssert on tests to ensure participant payments & membership payments were in sync

Comments
----------------------------------------
@jitendrapurohit @MegaphoneJon this feels like a code area you have touched

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Ah - test depends on another test data cleanup being merged first

**Comment by eileenmcnaughton** [comment]
I've rebased this over #20654 - which fixes the test data. However that started as a test fix & would up with a fix fix because the tests exposed a bug

**Comment by jitendrapurohit** [comment]
ok - performed a manual testing with event transfers.

**Before -**

After the transfer is done from participant A to B, a new row is added to the participant_payment table, so there are now 2 participant attached to a single contribution id.

If `View participant` page is opened for A or B, they both display the contribution data on it.

**After -** 

After the transfer form is submitted - the existing row in `participant_payment` table is updated to hold the new participant id.

View participant page on A does not display contribution data.

I think it's fine since the registration was transferred and it is expected to see less data on it. 

But, I'm not sure about the test modified in this PR? @eileenmcnaughton Can you please confirm if the test expects to see the `Before` section i mentioned above? From the line 

    $this->callAPISuccessGetCount('ParticipantPayment', ['contribution_id' => $contribution['id']], 2);

it seems yes since it is at the end and want to check if single contribution is attached to both the participants.

But, if i put this check at the start of the function, i.e, just after 

```
$this->createEventOrder();
$contribution = $this->callAPISuccessGetSingle('Contribution', ['return' => 'id']);

$this->callAPISuccessGetCount('ParticipantPayment', ['contribution_id' => $contribution['id']], 2); <-- here.
```

It is still asserting true.

Probably, it would be good to check only 1 contribution exist with the new participant?

    $this->callAPISuccessGetCount('ParticipantPayment', ['participant_id' => $toParticipant['id']], 1);

and 0 with the old?

    $this->callAPISuccessGetCount('ParticipantPayment', ['participant_id' => $participantId], 0);

Thoughts on adding these 2 checks as well?

Thanks for the PR :)

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit I've added those 2 checks to the end of the test - is it all good now?

**Comment by monishdeb** [comment]
Reviewed the patch, tested it too. Based on @jitendrapurohit and my feedback merging it now.

**Pull request merged**
