### PR TITLE
(NFC) Convert files to use linux line endings not windows

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
After noticing `CRM/Contribute/Page/ContributionRecurPayments.php` was a new file in dos line endings in 5.3 i went and found these other files that were also in dos line endings so fixing them. You should see that there is no function change by adding ?w=1 onto the end of the PR URL

Before
----------------------------------------
Dos line endings used

After
----------------------------------------
Linux line endings used

ping @eileenmcnaughton @colemanw @totten

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I would have put it against master rather than the rc but I agree it's whitespace only & ok to merge

@MiyaNoctem looks like you submitted the wrong endings? You might need to do some config?

**Comment by colemanw** [comment]
Hmm, a few years ago I tried tackling this problem and came across `IIF.tpl` which says:

>-***** IMPORTANT *************
>Quickbooks allows almost NO variation in formatting. If editing this file pay
>close attention to whitespace, empty lines, and invisible characters.

And that gave me pause...
I think the other files are safe to change though.

**Comment by seamuslee001** [comment]
@colemanw i'll revert out the change with IIF.tpl for the moment in that case

**Comment by colemanw** [comment]
It's too bad because otherwise there's a global variable we can set in git that will force all line endings to a standard. Just need to somehow verify that it's safe to do so on that `IIF.tpl` file. Perhaps @JoeMurray would know?

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@civicrm-builder re test this please

**Comment by seamuslee001** [comment]
@civicrm-builder re test this please

**Comment by seamuslee001** [comment]
@civicrm-builder re test this please

**Pull request merged**
