### PR TITLE
dev/core#4390 remove unused code that results in errors for multiple participant registration

### PR DESCRIPTION
**Pull request by kurund**
Fixes: https://lab.civicrm.org/dev/core/-/issues/4390

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@kurund I came pretty close to doing this same PR last week.

Would you be able to move it to the 5.71 rc branch? We've only just forked & there are fixes in related code in the rc already so I think it will be less confusing if this is in the same branch if a regression in this general area arises

**Comment by eileenmcnaughton** [comment]
Dang - I tried but it has THAT commit

**Comment by kurund** [comment]
@eileenmcnaughton 

Here is the new PR: https://github.com/civicrm/civicrm-core/pull/29358

**Comment by kurund** [comment]
closing this in favor of https://github.com/civicrm/civicrm-core/pull/29358

**Pull request closed without merging**
